"document": "section Section1;\r\nshared #\"GL Account Segment\" = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_PROD_WHSE\", null),\r\n  #\"Navigation 1\" = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 3\" = #\"Navigation 2\"{[Name = \"XX_GL_ACCOUNT_VIEW\", Kind = \"View\"]}[Data],\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Navigation 3\", {{\"ACCOUNT_CODE\", \"Account Code\"}, {\"ACCOUNT_NAME\", \"Account Name\"}, {\"ACCOUNT_DESC\", \"Account Description\"}, {\"ACCOUNT_TYPE\", \"Account Type\"}, {\"ACCOUNT_SUB_GROUP\", \"Account Sub Group\"}, {\"ACCOUNT_GROUP\", \"Account Group\"}, {\"SUMMARY_ACCOUNT\", \"Summary Account\"}, {\"ENABLED_FLAG\", \"Enabled Flag\"}, {\"START_DATE_ACTIVE\", \"Active Start Date\"}, {\"END_DATE_ACTIVE\", \"Active End Date\"}, {\"CREATION_DATE\", \"Creation Date\"}, {\"LAST_UPDATE_DATE\", \"Last Update Date\"}, {\"CREATED_BY_LOGIN\", \"Created By Login\"}, {\"LAST_UPDATE_LOGIN\", \"Last Update By Login\"}, {\"SUMMARY_MULT_FACTOR\", \"Summary Multiplier\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared #\"GL Department Segment\" = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_PROD_WHSE\", null),\r\n  #\"Navigation 1\" = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 3\" = #\"Navigation 2\"{[Name = \"XX_GL_DEPARTMENT_VIEW\", Kind = \"View\"]}[Data],\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Navigation 3\", {{\"DEPARTMENT_CODE\", \"Department Code\"}, {\"DEPARTMENT_NAME\", \"Department Name\"}, {\"DEPARTMENT_DESC\", \"Department Description\"}, {\"ENABLED_FLAG\", \"Enabled Flag\"}, {\"START_DATE_ACTIVE\", \"Active Start Date\"}, {\"END_DATE_ACTIVE\", \"Active End Date\"}, {\"CREATION_DATE\", \"Creation Date\"}, {\"LAST_UPDATE_DATE\", \"Last Update Date\"}, {\"CREATED_BY_LOGIN\", \"Created By Login\"}, {\"LAST_UPDATE_LOGIN\", \"Last Update By Login\"}, {\"DEPARTMENT_SUB_GROUP\", \"Department Sub Group\"}, {\"DEPARTMENT_GROUP\", \"Department Group\"}, {\"SUMMARY_DEPARTMENT\", \"Summary Department\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared #\"GL Entity Segment\" = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_PROD_WHSE\", null),\r\n  #\"Navigation 1\" = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 3\" = #\"Navigation 2\"{[Name = \"XX_GL_ENTITY_VIEW\", Kind = \"View\"]}[Data],\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Navigation 3\", {{\"ENTITY_CODE\", \"Entrity Code\"}, {\"ENTITY_NAME\", \"Entity Name\"}, {\"ENTITY_DESC\", \"Entity Description\"}, {\"ENTITY_SUB_GROUP\", \"Entity Sub Group\"}, {\"ENTITY_GROUP\", \"Entity Group\"}, {\"SUMMARY_ENTITY\", \"Summary Entity\"}, {\"LOCAL_GAAP_ENTITY\", \"Local GAAP Entity\"}, {\"ENABLED_FLAG\", \"Enabled Flag\"}, {\"START_DATE_ACTIVE\", \"Active Start Date\"}, {\"END_DATE_ACTIVE\", \"Active End Date\"}, {\"CREATION_DATE\", \"Creation Date\"}, {\"LAST_UPDATE_DATE\", \"Last Update Date\"}, {\"CREATED_BY_LOGIN\", \"Created By Login\"}, {\"LAST_UPDATE_LOGIN\", \"Last Update By Login\"}, {\"CURRENCY_CODE\", \"Currency Code\"}, {\"USGAAP_ENTITY_FLAG\", \"US-GAAP Entity Flag\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared #\"GL Project Segment\" = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_PROD_WHSE\", null),\r\n  #\"Navigation 1\" = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 3\" = #\"Navigation 2\"{[Name = \"XX_GL_PROJECT_VIEW\", Kind = \"View\"]}[Data],\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Navigation 3\", {{\"PROJECT_CODE\", \"Project Code\"}, {\"PROJECT_NAME\", \"Project Name\"}, {\"PROJECT_DESC\", \"Project Description\"}, {\"ENABLED_FLAG\", \"Enabled Flag\"}, {\"START_DATE_ACTIVE\", \"Active Start Date\"}, {\"END_DATE_ACTIVE\", \"Active End Date\"}, {\"CREATION_DATE\", \"Creation Date\"}, {\"LAST_UPDATE_DATE\", \"Last Update Date\"}, {\"CREATED_BY_LOGIN\", \"Created By Login\"}, {\"LAST_UPDATE_LOGIN\", \"Last Update By Login\"}, {\"PROJECT_SUB_GROUP\", \"Project Sub Group\"}, {\"PROJECT_GROUP\", \"Project Group\"}, {\"SUMMARY_PROJECT\", \"Summary Project\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared XX_BI_APPS_RPT_PARAMETERS = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_PROD_WHSE\", null),\r\n  Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 1\" = Navigation{[Name = \"XXFACTS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XX_BI_APPS_RPT_PARAMETERS\", Kind = \"Table\"]}[Data]\r\nin\r\n  #\"Navigation 2\";\r\nshared #\"Entity Department Details\" = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_PROD_WHSE\", null),\r\n  Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 1\" = Navigation{[Name = \"XXDIMS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XX_ENTITY_DEPT_DETAIL\", Kind = \"Table\"]}[Data],\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Navigation 2\", {{\"DEPT_SUB_FUNCTION\", \"Department Sub Function\"}, {\"DEPT_FUNCTION\", \"Department Function\"}, {\"ENTITY_CODE\", \"Entity Code\"}, {\"ENTITY_DEPT_CODE\", \"Entity Department\"}, {\"COUNTRY\", \"Country\"}, {\"REGION\", \"Region\"}, {\"COMMENTS\", \"Comments\"}, {\"RECORD_ID\", \"Record Id\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared #\"GL Code Combinations\" = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_PROD_WHSE\", null),\r\n  Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 1\" = Navigation{[Name = \"GL\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"GL_CODE_COMBINATIONS\", Kind = \"Table\"]}[Data],\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Navigation 2\", {{\"CODE_COMBINATION_ID\", type text}, {\"LAST_UPDATED_BY\", type text}})\r\nin\r\n  #\"Changed column type\";\r\nshared #\"Bussiness Segment Mapping\" = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_PROD_WHSE\", null),\r\n  #\"Navigation 1\" = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXCOH\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 3\" = #\"Navigation 2\"{[Name = \"XXCOH_BUSINESS_SEGMENT_MAP\", Kind = \"Table\"]}[Data]\r\nin\r\n  #\"Navigation 3\";\r\nshared #\"Financial Product Mapping\" = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_PROD_WHSE\", null),\r\n  #\"Navigation 1\" = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXDIMS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 3\" = #\"Navigation 2\"{[Name = \"XX_FINPRODUCT_MAP\", Kind = \"Table\"]}[Data],\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Navigation 3\", {{\"RECORD_ID\", \"Record Id\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared #\"Fiscal Calendar Days\" = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_PROD_WHSE\", null),\r\n  Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 1\" = Navigation{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XX_FISCAL_DAYS_TAB\", Kind = \"Table\"]}[Data],\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Navigation 2\", {{\"CAL_DAY\", \"Calendar Day\"}, {\"FISCAL_WEEK_NO\", \"Fiscal Week No\"}, {\"FISCAL_MONTH_WEEK_NO\", \"Fiscal Month Week No\"}, {\"FISCAL_QTR_WEEK_NO\", \"Fiscal Qtr Week No\"}, {\"GL_PERIOD\", \"GL Period\"}, {\"PERIOD_YEAR\", \"Period Year\"}, {\"FISCAL_YEAR\", \"Fiscal Year\"}, {\"QUARTER_NUM\", \"Quarter No\"}, {\"FISCAL_QUARTER\", \"Fiscal Quarter\"}, {\"FYFQ\", \"Fiscal Year Quarter\"}, {\"PERIOD_NUM\", \"Period No\"}, {\"FISCAL_DAY\", \"Fiscal Day\"}, {\"WEEK_START_DATE\", \"Week Start Date\"}, {\"WEEK_END_DATE\", \"Week End Date\"}, {\"PERIOD_START_DATE\", \"Period Start Date\"}, {\"PERIOD_END_DATE\", \"Period End Date\"}, {\"QUARTER_START_DATE\", \"Quarter Start Date\"}, {\"QUARTER_END_DATE\", \"Quarter End Date\"}, {\"YEAR_START_DATE\", \"Year Start Date\"}, {\"YEAR_END_DATE\", \"Year End Date\"}, {\"ROW_CREATION_DATE\", \"Row Creation Date\"}, {\"FISCAL_WEEK\", \"Fiscal Week\"}, {\"FISCAL_YEAR_WEEK\", \"Fiscal Year Week\"}, {\"WEEK_END_FLAG\", \"Week End Flag\"}, {\"MONTH_END_FLAG\", \"Month End Flag\"}, {\"QUARTER_END_FLAG\", \"Quarter End Flag\"}, {\"YEAR_END_FLAG\", \"Year End Flag\"}, {\"PERIOD_SET_NAME\", \"Period Set Name\"}, {\"PERIOD_MONTH\", \"Fiscal Period Month\"}, {\"EXTRACT_DATE\", \"Refresh Date\"}, {\"PQ_LAST_FISCAL_WEEK\", \"Prior Qtr Last Fiscal Week\"}, {\"NQ_FIRST_FISCAL_WEEK\", \"Next Quarter First Fiscal Week\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Countries = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_PROD_WHSE\", null),\r\n  #\"Navigation 1\" = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXSF\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 3\" = #\"Navigation 2\"{[Name = \"XX_COUNTRIES\", Kind = \"Table\"]}[Data],\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Navigation 3\", {{\"COUNTRY_NAME\", \"Country Name\"}, {\"REGION\", \"Country Region\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared #\"Inventory Organizations\" = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_PROD_WHSE\", null),\r\n  #\"Navigation 1\" = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXDIMS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 3\" = #\"Navigation 2\"{[Name = \"XX_INVORG_DIM\", Kind = \"Table\"]}[Data],\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Navigation 3\", {{\"OPERATING_UNIT\", \"Operating Unit\"}, {\"INVORG_CODE\", \"INVORG_CODE\"}, {\"INVORG_ID\", \"INVORG_ID\"}, {\"INVORG_CATEGORY\", \"Inventory Org Category\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Subinventories = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_PROD_WHSE\", null),\r\n  Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 1\" = Navigation{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XX_SUBINVENTORY_VIEW\", Kind = \"View\"]}[Data],\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Navigation 2\", {{\"SUBINV_CLASSIFICATION\", \"Subinventory Classification\"}, {\"SUBINVENTORY\", \"Subinventory\"}, {\"SUBINV_COUNTRY\", \"Subinventory Country\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared #\"FIN Product Dimension\" = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", null),\r\n  #\"Navigation 1\" = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXDIMS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 3\" = #\"Navigation 2\"{[Name = \"XX_FINPRODUCT_DIM_VIEW\", Kind = \"View\"]}[Data]\r\nin\r\n  #\"Navigation 3\";\r\nshared #\"FIN Product UnPivot\" = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", null),\r\n  #\"Navigation 1\" = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXDIMS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 3\" = #\"Navigation 2\"{[Name = \"XX_FINPRODUCT_UNPIVOT_VIEW\", Kind = \"View\"]}[Data],\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Navigation 3\", {{\"PRODUCT_DIM\", \"Product Dimension\"}, {\"PRODUCT_DIM_VALUE\", \"Product Dimension Value\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared #\"Fiscal Context\" = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 1\" = Navigation{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XX_FISCAL_CONTEXT_V\", Kind = \"View\"]}[Data]\r\nin\r\n  #\"Navigation 2\";\r\nshared #\"Operating Unit Data Security\" = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 1\" = Navigation{[Name = \"XXADMIN\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XX_OU_DATA_SECURITY_V\", Kind = \"View\"]}[Data]\r\nin\r\n  #\"Navigation 2\";\r\nshared #\"GL Code Combinations Desc\" = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 1\" = Navigation{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXREP_GL_CODE_COMBINATIONS_V\", Kind = \"View\"]}[Data]\r\nin\r\n  #\"Navigation 2\";\r\nshared #\"Operating Units\" = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 1\" = Navigation{[Name = \"XXDIMS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XX_OPERATING_UNIT_DIM\", Kind = \"Table\"]}[Data]\r\nin\r\n  #\"Navigation 2\";\r\nshared #\"Item Commodity Categories\" = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 1\" = Navigation{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXREP_COMMODITY_CATEGORY_V\", Kind = \"View\"]}[Data]\r\nin\r\n  #\"Navigation 2\";\r\nshared #\"OTD Order Line Type Mapping\" = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 1\" = Navigation{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXREP_OTD_LINE_TYPE_MAP_V\", Kind = \"View\"]}[Data]\r\nin\r\n  #\"Navigation 2\";\r\n"