{"name":"df_global_report_kpi_information","description":"Table of report purpose and KPI details for each of the Corporate reports being created to support Operations:\n\nKPI Details:\nInventory Turns","version":"1.0","culture":"en-US","modifiedTime":"2022-06-13T10:57:34.0302724+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"Report Details":{"queryId":"7012f7fa-e1ef-4d2a-a986-4b2f4d89fbd4","queryName":"Report Details","loadEnabled":true}},"document":"section Section1;\r\nshared #\"Report Details\" = let\r\n  Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"nZJBb9NAEIX/ylNOdmWBBIhDjiQoIFU0IhGXtqo29sRexd5xd2cdLPHjmXXSlrZcQPLF3rfzvvc819ezzz+pjGIHwuUWv3DJpWlx5eswK2Zf3UBO2I/4Tj170U9rz4OtCBWJsW0AO6w8h4BHbYFvJH++Ls2ouj02se9bfV9HXzYmWFcnS+OqJzG20buAbHG12kwnm/UiV9cXFnNsG4KwKGo9HQ2mjZRMRo4e9nGedTDYRTUjVUVnpYB4Ux6oAg/kIbajN3ON0SS7exlxkUwL7PSyUHfjHvDDhD/HFz5ibzyMp+SGMs3RcUcrzUv7nQnJSCGGGpUWNmpxnTqFIqGdEmSOBaN21lDb72NbgKVJaIqE9NS1p9qIJvbkqnxi6z1XsRQl6dLUrGPFOQ9QRQpzToBMp6EjI/mznG9fQSF79xFHokNQOGGke/so0ZPS7lWuWrNr6Qx4tIGeEvaeBssx4GFGfuNe/VdtFp9G/OA2dpSfuryPtjwkBp7qVDuN7Dkqz9Rmb7yEObLsdAvL9WaDFXklHtGaIHiPjp00Ib/4kGusZ+t3t2p5Z9q/sKQd+1eEBatdWmXTUvhfEt3nJYWDcD+7vf0N\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Stakeholders = _t, #\"Report Name\" = _t, #\"Report Purpose\" = _t, #\"Key Metrics\" = _t, Consumed = _t])\r\nin\r\n  Source;\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"Report Details","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Report%20Details.csv"},"attributes":[{"name":"Stakeholders","dataType":"string"},{"name":"Report Name","dataType":"string"},{"name":"Report Purpose","dataType":"string"},{"name":"Key Metrics","dataType":"string"},{"name":"Consumed","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-15T13:57:21.0911623+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/640bd4e1-a164-430f-90fc-b9a5c9c7bc90/Report%20Details.csv?snapshot=2022-06-15T13%3A57%3A21.0788075Z"}]}]}