{"name":"InventoryTurnsModel_Flow","description":"This dataflow contains Dimension and Fact Tables that are used in the Corporate Inventory Report which is located in the \n\nWorkspace - Corporate Inventory Reports\nWorkspace - Corporate Inventory DataModels","version":"1.0","culture":"en-US","modifiedTime":"2022-05-13T11:08:38.8260131+00:00","pbi:mashup":{"fastCombine":true,"allowNativeQueries":false,"queriesMetadata":{"ListOfValues":{"queryId":"8cae74f9-5b81-42fb-b3a8-d696f9e6bdc4","queryName":"ListOfValues","queryGroupId":"6ff8692f-faa8-429c-b3f8-55f3f9367f36"},"pM20Detail":{"queryId":"727970dd-878e-4507-a281-cbedb1a6a9fd","queryName":"pM20Detail","queryGroupId":"6ff8692f-faa8-429c-b3f8-55f3f9367f36"},"pListOfValues":{"queryId":"a5da891e-62b7-40a6-8f6c-42026c16a9d1","queryName":"pListOfValues","queryGroupId":"6ff8692f-faa8-429c-b3f8-55f3f9367f36"},"pInventoryValue":{"queryId":"e55bfbcb-7032-4fbe-9faf-eed40577596d","queryName":"pInventoryValue","queryGroupId":"6ff8692f-faa8-429c-b3f8-55f3f9367f36"},"Version History Model":{"queryId":"d2e6d2c7-1432-468b-9546-412d3aa0c1ed","queryName":"Version History Model","queryGroupId":"cd422d8f-fda3-4b62-a1f7-c80ab4cce992","loadEnabled":true},"Version History Report":{"queryId":"65ac9cdb-02d4-4244-b046-4d4227489795","queryName":"Version History Report","queryGroupId":"cd422d8f-fda3-4b62-a1f7-c80ab4cce992","loadEnabled":true},"Version History":{"queryId":"fd181069-bc20-4760-afc3-dc9b8596585f","queryName":"Version History","queryGroupId":"cd422d8f-fda3-4b62-a1f7-c80ab4cce992","loadEnabled":true},"DAX_Metrics":{"queryId":"1602da3d-99ea-4a65-b10c-b4cf279fa763","queryName":"DAX_Metrics","queryGroupId":"90e550ce-413d-4ba2-8785-0d7b6dc61c85","loadEnabled":true},"FACT_M20Detail":{"queryId":"8603dd15-8b2d-4158-a26b-5a81cea997c4","queryName":"FACT_M20Detail","queryGroupId":"408246b6-1716-4dc8-8e13-24352c7eb0b0","loadEnabled":true},"FACT_M20DetailAll":{"queryId":"05f80fa7-ff6e-4d4d-b0ea-e318b5b54f7a","queryName":"FACT_M20DetailAll","queryGroupId":"408246b6-1716-4dc8-8e13-24352c7eb0b0","loadEnabled":true},"FACT_InventoryValue":{"queryId":"4bc52bc5-68a4-4ba6-9bc3-b695adcc56d4","queryName":"FACT_InventoryValue","queryGroupId":"408246b6-1716-4dc8-8e13-24352c7eb0b0","loadEnabled":true},"pActiveDirectory":{"queryId":"390694ae-5ed8-4259-9552-76289bc87dbc","queryName":"pActiveDirectory","queryGroupId":"6ff8692f-faa8-429c-b3f8-55f3f9367f36"},"pM20DetailAll":{"queryId":"b5ef2ef0-48d7-4f7d-8355-38a3f72240aa","queryName":"pM20DetailAll"},"Financial Product Mapping":{"queryId":"cc016664-60db-4836-a12d-b7d11133a059","queryName":"Financial Product Mapping","queryGroupId":"fdc8aec4-4541-4e06-92f4-c64aaa24572d","loadEnabled":true},"GL Account Segment":{"queryId":"811d830f-5c9c-4801-9759-e876cd7f8d7f","queryName":"GL Account Segment","queryGroupId":"fdc8aec4-4541-4e06-92f4-c64aaa24572d","loadEnabled":true},"GL Code Combinations":{"queryId":"348a8f53-d1b5-4d0c-8b0e-687de4daad00","queryName":"GL Code Combinations","queryGroupId":"fdc8aec4-4541-4e06-92f4-c64aaa24572d","loadEnabled":true},"GL Code Combinations Desc":{"queryId":"bd476ac5-9d07-4a47-bca8-faf0657f9590","queryName":"GL Code Combinations Desc","queryGroupId":"fdc8aec4-4541-4e06-92f4-c64aaa24572d","loadEnabled":true},"GL Project Segment":{"queryId":"8307415e-3e97-4705-aff9-22615c1f32e0","queryName":"GL Project Segment","queryGroupId":"fdc8aec4-4541-4e06-92f4-c64aaa24572d","loadEnabled":true},"DIM_Calendar":{"queryId":"6942c072-1693-448b-af86-2798aee97df6","queryName":"DIM_Calendar","queryGroupId":"fdc8aec4-4541-4e06-92f4-c64aaa24572d","loadEnabled":true},"Fiscal Context":{"queryId":"61a61f26-5a31-4b45-9bef-3b8b6b351b3f","queryName":"Fiscal Context","queryGroupId":"fdc8aec4-4541-4e06-92f4-c64aaa24572d","loadEnabled":true},"DIM_GLDepartment":{"queryId":"480f03f6-7ff0-40e4-8b95-85fff24dfeb9","queryName":"DIM_GLDepartment","queryGroupId":"fdc8aec4-4541-4e06-92f4-c64aaa24572d","loadEnabled":true},"DIM_GLEntity":{"queryId":"532b9a9f-dece-48be-a966-7bb3e0438110","queryName":"DIM_GLEntity","queryGroupId":"fdc8aec4-4541-4e06-92f4-c64aaa24572d","loadEnabled":true},"Inventory Organizations":{"queryId":"d6ead064-8341-4bf3-b2cd-0ecaca550013","queryName":"Inventory Organizations","queryGroupId":"fdc8aec4-4541-4e06-92f4-c64aaa24572d","loadEnabled":true},"Operating Units":{"queryId":"b333636e-f0d7-4928-8a2b-331928a603e7","queryName":"Operating Units","queryGroupId":"fdc8aec4-4541-4e06-92f4-c64aaa24572d","loadEnabled":true},"Operating Unit Data Security":{"queryId":"de73b955-2651-4430-9ff3-79f11c082d27","queryName":"Operating Unit Data Security","queryGroupId":"fdc8aec4-4541-4e06-92f4-c64aaa24572d","loadEnabled":true}},"document":"section Section1;\r\nshared ListOfValues = let\r\n    Source = pListOfValues,\r\n    GetListOfValues = Text.Split(Source, \",\")\r\nin\r\n    GetListOfValues;\r\nshared pM20Detail = \"C:\\Users\\PeacocCo\\Coherent, Inc\\Power BI Community - Projects\\Inventory\\2. Measure\\DataModels\\test\\data\\XXREP_M20_DETAIL_V.csv\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type any];\r\n[Description = \"Enter a comma delimited list of values\"]\r\nshared pListOfValues = \"SGP,GDP,SIO\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type text];\r\nshared pInventoryValue = \"C:\\Users\\PeacocCo\\Coherent, Inc\\Power BI Community - Projects\\Inventory\\2. Measure\\DataModels\\test\\data\\XXREP_INVVALUE_V.csv\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type any];\r\nshared #\"Version History Model\" = let\r\n    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"FcyxCoMwFEbhV/nJXOUa7NJVKThEBUeRcmtuaDAa0ICvXx3PGb5xVEVOOamH0qR1Rs+MShTli+5VxeA39MJznJerm80nzwFJjoQ1WgmYd+EkFqdPPxhNcHFH3Q8DeLNgODlR+xWJv0EOuD2ueDftp+qM6VpYTuxCPC/c3J6apj8=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Version Number\" = _t, #\"Revision Date/Time\" = _t, #\"Developer Name\" = _t, #\"Revision Notes\" = _t, #\"Revision Type\" = _t]),\r\n    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Version Number\", type text}, {\"Revision Date/Time\", type datetime}, {\"Developer Name\", type text}, {\"Revision Notes\", type text}, {\"Revision Type\", type text}})\r\nin\r\n    #\"Changed Type\";\r\nshared #\"Version History Report\" = let\r\n    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"FcqxCoAgEIDhVzmcMy6xpbWpLVrDQeKoI1HJs16/Gv+Pf11V12KLqlEGjdHYa7TQ2QF/GlPgCDP5LW3n11MUFvYBst8JComuGR6WA4SKwM2l+lC+caGcLlHOvQ==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Version Number\" = _t, #\"Revision Date/Time\" = _t, #\"Developer Name\" = _t, #\"Revision Notes\" = _t, #\"Revision Type\" = _t]),\r\n    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Version Number\", type text}, {\"Revision Date/Time\", type datetime}, {\"Developer Name\", type text}, {\"Revision Notes\", type text}, {\"Revision Type\", type text}})\r\nin\r\n    #\"Changed Type\";\r\nshared #\"Version History\" = let\r\n    Source = Table.Combine({#\"Version History Model\", #\"Version History Report\"})\r\nin\r\n    Source;\r\nshared DAX_Metrics = let\r\n    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),\r\n    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),\r\n    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})\r\nin\r\n    #\"Removed Columns\";\r\nshared FACT_M20Detail = let\r\n    Source = Csv.Document(File.Contents(pM20Detail), [Delimiter = \",\", Columns = 15, QuoteStyle = QuoteStyle.None]),\r\n    #\"Promoted headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),\r\n    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted headers\",{{\"ENTITY\", type text}, {\"DEPT\", type text}, {\"ACCT\", type text}, {\"PROJ\", type text}, {\"M20_TBU\", type text}, {\"M20_PFC\", type text}, {\"INTERCO\", type text}, {\"ACCOUNT_DESC\", type text}, {\"GL_PERIOD\", type date}, {\"TRANS_DATE\", type datetime}, {\"TRAN_QTY\", type text}, {\"ACCOUNTED_DR\", type number}, {\"ACCOUNTED_CR\", type number}, {\"NET_ACCOUNTED_AMT\", type number}, {\"ACCOUNTED_NET_USD\", type number}}),\r\n    #\"Duplicated Column\" = Table.DuplicateColumn(#\"Changed Type\", \"TRANS_DATE\", \"TRANS_DATE - Copy\"),\r\n    #\"Reordered Columns\" = Table.ReorderColumns(#\"Duplicated Column\",{\"ENTITY\", \"DEPT\", \"ACCT\", \"PROJ\", \"M20_TBU\", \"M20_PFC\", \"INTERCO\", \"ACCOUNT_DESC\", \"GL_PERIOD\", \"TRANS_DATE\", \"TRANS_DATE - Copy\", \"TRAN_QTY\", \"ACCOUNTED_DR\", \"ACCOUNTED_CR\", \"NET_ACCOUNTED_AMT\", \"ACCOUNTED_NET_USD\"}),\r\n    #\"Extracted Date\" = Table.TransformColumns(#\"Reordered Columns\",{{\"TRANS_DATE\", DateTime.Date, type date}}),\r\n    #\"Extracted Time\" = Table.TransformColumns(#\"Extracted Date\",{{\"TRANS_DATE - Copy\", DateTime.Time, type time}}),\r\n    TransTimeColumn = Table.RenameColumns(#\"Extracted Time\",{{\"TRANS_DATE - Copy\", \"TRANS_TIME\"}})\r\nin\r\n    TransTimeColumn;\r\nshared FACT_M20DetailAll = let\r\n    Source = Csv.Document(File.Contents(pM20DetailAll), [Delimiter = \",\", Columns = 15, QuoteStyle = QuoteStyle.None]),\r\n    #\"Promoted headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),\r\n    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted headers\",{{\"ENTITY\", type text}, {\"DEPT\", type text}, {\"ACCT\", type text}, {\"PROJ\", type text}, {\"M20_TBU\", type text}, {\"M20_PFC\", type text}, {\"INTERCO\", type text}, {\"ACCOUNT_DESC\", type text}, {\"GL_PERIOD\", type date}, {\"TRANS_DATE\", type datetime}, {\"TRAN_QTY\", type text}, {\"ACCOUNTED_DR\", type number}, {\"ACCOUNTED_CR\", type number}, {\"NET_ACCOUNTED_AMT\", type number}, {\"ACCOUNTED_NET_USD\", type number}}),\r\n    #\"Duplicated Column\" = Table.DuplicateColumn(#\"Changed Type\", \"TRANS_DATE\", \"TRANS_DATE - Copy\"),\r\n    #\"Extracted Time\" = Table.TransformColumns(#\"Duplicated Column\",{{\"TRANS_DATE - Copy\", DateTime.Time, type time}}),\r\n    #\"Renamed Columns\" = Table.RenameColumns(#\"Extracted Time\",{{\"TRANS_DATE - Copy\", \"TRANS_TIME\"}}),\r\n    #\"Extracted Date\" = Table.TransformColumns(#\"Renamed Columns\",{{\"TRANS_DATE\", DateTime.Date, type date}})\r\nin\r\n    #\"Extracted Date\";\r\nshared FACT_InventoryValue = let\r\n    Source = Csv.Document(File.Contents(pInventoryValue), [Delimiter = \",\", Columns = 86, Encoding = 65001, QuoteStyle = QuoteStyle.None]),\r\n    #\"Promoted headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),\r\n    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted headers\",{{\"INV_ORG_ID\", type text}, {\"INVENTORY_ITEM_ID\", type text}, {\"ITEM_ORG_ID_KEY\", type text}, {\"ITEM_ORG_CODE_KEY\", type text}, {\"OPERATING_UNIT_ID\", Int64.Type}, {\"ITEM_NUMBER\", type text}, {\"ITEM_TBU\", type text}, {\"ITEM_PRODUCT_FAMILY\", type text}, {\"SOURCE_TYPE\", type text}, {\"SUBINVENTORY_CODE\", type text}, {\"SUBINVENTORY_TYPE\", type text}, {\"ORGANIZATION_CODE\", type text}, {\"ENTITY\", type text}, {\"ACCOUNT\", type text}, {\"FIN_ENTITY\", type text}, {\"INV_QUANTITY\", Int64.Type}, {\"INV_BALANCE\", Int64.Type}, {\"INV_VALUE\", type number}, {\"INV_VALUE_USD\", type number}, {\"CURRENCY_CODE\", type text}, {\"CURRENCY_RATE\", type number}, {\"ITEM_COST\", type number}, {\"MATERIAL_COST\", type number}, {\"MATERIAL_OVERHEAD_COST\", type number}, {\"OUTSIDE_PROCESSING_COST\", type number}, {\"OVERHEAD_COST\", type number}, {\"RESOURCE_COST\", type number}, {\"TOTAL_COST\", type number}, {\"FISCAL_YEAR_ID\", Int64.Type}, {\"VALID_FLAG\", type text}, {\"COMMENTS\", type text}, {\"CREATION_DATE\", type datetimezone}, {\"CREATED_BY\", Int64.Type}, {\"FISCAL_WEEK_ID\", Int64.Type}, {\"FISCAL_WEEK\", type text}, {\"JE_SOURCE_CATEGORY\", type text}, {\"OPERATIONS_REPORTING\", type text}, {\"CS_DEMAND_SOURCE\", type text}, {\"CS_SUPPLY_SOURCE\", type text}, {\"ITEM_TYPE_CODE\", type text}, {\"EXCLUDE_FLAG\", type text}, {\"EXCLUDE_COMMENT\", type text}, {\"WIP_CLASS\", type text}, {\"WIP_CLASS_CODE\", Int64.Type}, {\"ITEM_TYPE\", type text}, {\"PLANNER_CODE\", type text}, {\"MAKE_BUY\", type text}, {\"ITEM_STATUS\", type text}, {\"ABC_CLASS\", type text}, {\"INV_STATUS\", type text}, {\"WIP_JOB_ID\", Int64.Type}, {\"ITEM_PRODUCT_LINE\", type text}, {\"ITEM_FORECAST_FIELD\", type text}, {\"ITEM_DESC\", type text}, {\"WIP_JOB_NO\", type text}, {\"ITEM_COST_USD\", Int64.Type}, {\"ORA_PRODUCT_LINE\", type text}, {\"CONC_REQ_ID\", Int64.Type}, {\"FIN_PRODUCT_LINE\", type text}, {\"ORA_FORECAST_FIELD\", type text}, {\"ORG_TBU\", type text}, {\"ORG_PRODUCT_FAMILY\", type text}, {\"ORG_PRODUCT_LINE\", type text}, {\"ORG_FORECAST_FIELD\", type text}, {\"ORG_CATEGORY_ID\", Int64.Type}, {\"PRODUCT_MAP_KEY\", type text}, {\"FIN_TBU\", type text}, {\"FIN_PFC\", type text}, {\"WEEK_START_DATE\", type datetime}, {\"WEEK_END_DATE\", type datetime}, {\"PERIOD_START_DATE\", type datetime}, {\"PERIOD_END_DATE\", type datetime}, {\"QUARTER_START_DATE\", type datetime}, {\"QUARTER_END_DATE\", type datetime}, {\"FISCAL_QUARTER\", type text}, {\"FISCAL_YEAR\", type text}, {\"MGT_PRODUCT_GROUP\", type text}, {\"MGT_SUB_PRODUCT_GROUP\", type text}, {\"BUSINESS_SEGMENT\", type text}, {\"ACCOUNT_NAME\", type text}, {\"ACCOUNT_DESC\", type text}, {\"ACCOUNT_TYPE\", type text}, {\"ACCOUNT_SUB_GROUP\", type text}, {\"ACCOUNT_GROUP\", type text}, {\"SUMMARY_ACCOUNT\", type text}, {\"INVVALUE_KEY\", type text}}),\r\n    #\"Duplicated Column\" = Table.DuplicateColumn(#\"Changed Type\", \"CREATION_DATE\", \"CREATION_DATE - Copy\"),\r\n    #\"Extracted Time\" = Table.TransformColumns(#\"Duplicated Column\",{{\"CREATION_DATE - Copy\", DateTime.Time, type time}}),\r\n    #\"Renamed Columns\" = Table.RenameColumns(#\"Extracted Time\",{{\"CREATION_DATE - Copy\", \"CREATION_TIME\"}}),\r\n    #\"Extracted Date\" = Table.TransformColumns(#\"Renamed Columns\",{{\"CREATION_DATE\", DateTime.Date, type date}})\r\nin\r\n    #\"Extracted Date\";\r\n[Description = \"Gets the Active Directory User Details for RLS and OLS\"]\r\nshared pActiveDirectory = \"coherentinc.com\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type any];\r\nshared pM20DetailAll = \"C:\\Users\\PeacocCo\\Coherent, Inc\\Power BI Community - Projects\\Inventory\\2. Measure\\DataModels\\test\\data/XXREP_M20_DETAIL_V_ALL_ACCOUNTS.csv\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type text];\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[{\"id\":\"41f7b4c7-b736-48b6-a6f5-0f193960cdbd\",\"name\":\"Query Errors - 05/05/2022 09:04:02\",\"description\":\"Errors in queries that were loaded on 05/05/2022 09:04:02.\",\"parentId\":null,\"order\":1},{\"id\":\"6ff8692f-faa8-429c-b3f8-55f3f9367f36\",\"name\":\"Parameters\",\"description\":\"\",\"parentId\":null,\"order\":1},{\"id\":\"408246b6-1716-4dc8-8e13-24352c7eb0b0\",\"name\":\"Facts\",\"description\":\"\",\"parentId\":null,\"order\":1},{\"id\":\"fdc8aec4-4541-4e06-92f4-c64aaa24572d\",\"name\":\"Dimensions\",\"description\":\"\",\"parentId\":null,\"order\":1},{\"id\":\"cd422d8f-fda3-4b62-a1f7-c80ab4cce992\",\"name\":\"Versioning\",\"description\":\"\",\"parentId\":null,\"order\":1},{\"id\":\"90e550ce-413d-4ba2-8785-0d7b6dc61c85\",\"name\":\"DAX\",\"description\":\"\",\"parentId\":null,\"order\":1},{\"id\":\"02bdbfff-1ba9-452b-9038-2c6be5e25099\",\"name\":\"Testing\",\"description\":\"\",\"parentId\":null,\"order\":1}]"}],"entities":[{"$type":"LocalEntity","name":"Version History Model","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Version%20History%20Model.csv"},"attributes":[{"name":"Version Number","dataType":"string"},{"name":"Revision Date/Time","dataType":"dateTime"},{"name":"Developer Name","dataType":"string"},{"name":"Revision Notes","dataType":"string"},{"name":"Revision Type","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-20T10:06:09.8046537+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/f81e9042-8d48-4481-91e0-d333469ccced/Version%20History%20Model.csv?snapshot=2022-05-20T10%3A06%3A08.5144783Z"}]},{"$type":"LocalEntity","name":"Version History Report","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Version%20History%20Report.csv"},"attributes":[{"name":"Version Number","dataType":"string"},{"name":"Revision Date/Time","dataType":"dateTime"},{"name":"Developer Name","dataType":"string"},{"name":"Revision Notes","dataType":"string"},{"name":"Revision Type","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-20T10:06:09.6789051+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/f81e9042-8d48-4481-91e0-d333469ccced/Version%20History%20Report.csv?snapshot=2022-05-20T10%3A06%3A08.5954317Z"}]},{"$type":"LocalEntity","name":"Version History","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Version%20History.csv"},"annotations":[{"name":"pbi:EntityTypeDisplayHint","value":"CalculatedEntity"}],"attributes":[{"name":"Version Number","dataType":"string"},{"name":"Revision Date/Time","dataType":"dateTime"},{"name":"Developer Name","dataType":"string"},{"name":"Revision Notes","dataType":"string"},{"name":"Revision Type","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-20T10:06:14.641266+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/f81e9042-8d48-4481-91e0-d333469ccced/Version%20History.csv?snapshot=2022-05-20T10%3A06%3A14.5350372Z"}]},{"$type":"LocalEntity","name":"DAX_Metrics","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"DAX_Metrics.csv"},"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-20T10:06:06.5671082+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/f81e9042-8d48-4481-91e0-d333469ccced/DAX_Metrics.csv?snapshot=2022-05-20T10%3A06%3A06.4816397Z"}]},{"$type":"LocalEntity","name":"FACT_M20Detail","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"FACT_M20Detail.csv"},"attributes":[{"name":"ENTITY","dataType":"string"},{"name":"DEPT","dataType":"string"},{"name":"ACCT","dataType":"string"},{"name":"PROJ","dataType":"string"},{"name":"M20_TBU","dataType":"string"},{"name":"M20_PFC","dataType":"string"},{"name":"INTERCO","dataType":"string"},{"name":"ACCOUNT_DESC","dataType":"string"},{"name":"GL_PERIOD","dataType":"date"},{"name":"TRANS_DATE","dataType":"date"},{"name":"TRANS_TIME","dataType":"time"},{"name":"TRAN_QTY","dataType":"string"},{"name":"ACCOUNTED_DR","dataType":"double"},{"name":"ACCOUNTED_CR","dataType":"double"},{"name":"NET_ACCOUNTED_AMT","dataType":"double"},{"name":"ACCOUNTED_NET_USD","dataType":"double"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-20T10:06:35.8896658+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/f81e9042-8d48-4481-91e0-d333469ccced/FACT_M20Detail.csv?snapshot=2022-05-20T10%3A06%3A35.7269244Z"}]},{"$type":"LocalEntity","name":"FACT_M20DetailAll","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"FACT_M20DetailAll.csv"},"attributes":[{"name":"ENTITY","dataType":"string"},{"name":"DEPT","dataType":"string"},{"name":"ACCT","dataType":"string"},{"name":"PROJ","dataType":"string"},{"name":"M20_TBU","dataType":"string"},{"name":"M20_PFC","dataType":"string"},{"name":"INTERCO","dataType":"string"},{"name":"ACCOUNT_DESC","dataType":"string"},{"name":"GL_PERIOD","dataType":"date"},{"name":"TRANS_DATE","dataType":"date"},{"name":"TRAN_QTY","dataType":"string"},{"name":"ACCOUNTED_DR","dataType":"double"},{"name":"ACCOUNTED_CR","dataType":"double"},{"name":"NET_ACCOUNTED_AMT","dataType":"double"},{"name":"ACCOUNTED_NET_USD","dataType":"double"},{"name":"TRANS_TIME","dataType":"time"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-20T10:07:14.5614131+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/f81e9042-8d48-4481-91e0-d333469ccced/FACT_M20DetailAll.csv?snapshot=2022-05-20T10%3A07%3A14.3968199Z"}]},{"$type":"LocalEntity","name":"FACT_InventoryValue","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"FACT_InventoryValue.csv"},"attributes":[{"name":"INV_ORG_ID","dataType":"string"},{"name":"INVENTORY_ITEM_ID","dataType":"string"},{"name":"ITEM_ORG_ID_KEY","dataType":"string"},{"name":"ITEM_ORG_CODE_KEY","dataType":"string"},{"name":"OPERATING_UNIT_ID","dataType":"int64"},{"name":"ITEM_NUMBER","dataType":"string"},{"name":"ITEM_TBU","dataType":"string"},{"name":"ITEM_PRODUCT_FAMILY","dataType":"string"},{"name":"SOURCE_TYPE","dataType":"string"},{"name":"SUBINVENTORY_CODE","dataType":"string"},{"name":"SUBINVENTORY_TYPE","dataType":"string"},{"name":"ORGANIZATION_CODE","dataType":"string"},{"name":"ENTITY","dataType":"string"},{"name":"ACCOUNT","dataType":"string"},{"name":"FIN_ENTITY","dataType":"string"},{"name":"INV_QUANTITY","dataType":"int64"},{"name":"INV_BALANCE","dataType":"int64"},{"name":"INV_VALUE","dataType":"double"},{"name":"INV_VALUE_USD","dataType":"double"},{"name":"CURRENCY_CODE","dataType":"string"},{"name":"CURRENCY_RATE","dataType":"double"},{"name":"ITEM_COST","dataType":"double"},{"name":"MATERIAL_COST","dataType":"double"},{"name":"MATERIAL_OVERHEAD_COST","dataType":"double"},{"name":"OUTSIDE_PROCESSING_COST","dataType":"double"},{"name":"OVERHEAD_COST","dataType":"double"},{"name":"RESOURCE_COST","dataType":"double"},{"name":"TOTAL_COST","dataType":"double"},{"name":"FISCAL_YEAR_ID","dataType":"int64"},{"name":"VALID_FLAG","dataType":"string"},{"name":"COMMENTS","dataType":"string"},{"name":"CREATION_DATE","dataType":"date"},{"name":"CREATED_BY","dataType":"int64"},{"name":"FISCAL_WEEK_ID","dataType":"int64"},{"name":"FISCAL_WEEK","dataType":"string"},{"name":"JE_SOURCE_CATEGORY","dataType":"string"},{"name":"OPERATIONS_REPORTING","dataType":"string"},{"name":"CS_DEMAND_SOURCE","dataType":"string"},{"name":"CS_SUPPLY_SOURCE","dataType":"string"},{"name":"ITEM_TYPE_CODE","dataType":"string"},{"name":"EXCLUDE_FLAG","dataType":"string"},{"name":"EXCLUDE_COMMENT","dataType":"string"},{"name":"WIP_CLASS","dataType":"string"},{"name":"WIP_CLASS_CODE","dataType":"int64"},{"name":"ITEM_TYPE","dataType":"string"},{"name":"PLANNER_CODE","dataType":"string"},{"name":"MAKE_BUY","dataType":"string"},{"name":"ITEM_STATUS","dataType":"string"},{"name":"ABC_CLASS","dataType":"string"},{"name":"INV_STATUS","dataType":"string"},{"name":"WIP_JOB_ID","dataType":"int64"},{"name":"ITEM_PRODUCT_LINE","dataType":"string"},{"name":"ITEM_FORECAST_FIELD","dataType":"string"},{"name":"ITEM_DESC","dataType":"string"},{"name":"WIP_JOB_NO","dataType":"string"},{"name":"ITEM_COST_USD","dataType":"int64"},{"name":"ORA_PRODUCT_LINE","dataType":"string"},{"name":"CONC_REQ_ID","dataType":"int64"},{"name":"FIN_PRODUCT_LINE","dataType":"string"},{"name":"ORA_FORECAST_FIELD","dataType":"string"},{"name":"ORG_TBU","dataType":"string"},{"name":"ORG_PRODUCT_FAMILY","dataType":"string"},{"name":"ORG_PRODUCT_LINE","dataType":"string"},{"name":"ORG_FORECAST_FIELD","dataType":"string"},{"name":"ORG_CATEGORY_ID","dataType":"int64"},{"name":"PRODUCT_MAP_KEY","dataType":"string"},{"name":"FIN_TBU","dataType":"string"},{"name":"FIN_PFC","dataType":"string"},{"name":"WEEK_START_DATE","dataType":"dateTime"},{"name":"WEEK_END_DATE","dataType":"dateTime"},{"name":"PERIOD_START_DATE","dataType":"dateTime"},{"name":"PERIOD_END_DATE","dataType":"dateTime"},{"name":"QUARTER_START_DATE","dataType":"dateTime"},{"name":"QUARTER_END_DATE","dataType":"dateTime"},{"name":"FISCAL_QUARTER","dataType":"string"},{"name":"FISCAL_YEAR","dataType":"string"},{"name":"MGT_PRODUCT_GROUP","dataType":"string"},{"name":"MGT_SUB_PRODUCT_GROUP","dataType":"string"},{"name":"BUSINESS_SEGMENT","dataType":"string"},{"name":"ACCOUNT_NAME","dataType":"string"},{"name":"ACCOUNT_DESC","dataType":"string"},{"name":"ACCOUNT_TYPE","dataType":"string"},{"name":"ACCOUNT_SUB_GROUP","dataType":"string"},{"name":"ACCOUNT_GROUP","dataType":"string"},{"name":"SUMMARY_ACCOUNT","dataType":"string"},{"name":"INVVALUE_KEY","dataType":"string"},{"name":"CREATION_TIME","dataType":"time"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-20T10:07:11.9832493+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/f81e9042-8d48-4481-91e0-d333469ccced/FACT_InventoryValue.csv?snapshot=2022-05-20T10%3A07%3A11.8872542Z"}]},{"$type":"ReferenceEntity","name":"Financial Product Mapping","description":"","source":"Financial Product Mapping","modelId":"00113def-72e3-4c77-92ea-121a71b998e4/9ae7027c-9e54-4c14-a321-320f1fd0fdd3","annotations":[{"name":"pbi:EntityTypeDisplayHint","value":"LinkedEntity"}]},{"$type":"ReferenceEntity","name":"GL Account Segment","description":"","source":"GL Account Segment","modelId":"00113def-72e3-4c77-92ea-121a71b998e4/9ae7027c-9e54-4c14-a321-320f1fd0fdd3","annotations":[{"name":"pbi:EntityTypeDisplayHint","value":"LinkedEntity"}]},{"$type":"ReferenceEntity","name":"GL Code Combinations","description":"","source":"GL Code Combinations","modelId":"00113def-72e3-4c77-92ea-121a71b998e4/9ae7027c-9e54-4c14-a321-320f1fd0fdd3","annotations":[{"name":"pbi:EntityTypeDisplayHint","value":"LinkedEntity"}]},{"$type":"ReferenceEntity","name":"GL Code Combinations Desc","description":"","source":"GL Code Combinations Desc","modelId":"00113def-72e3-4c77-92ea-121a71b998e4/9ae7027c-9e54-4c14-a321-320f1fd0fdd3","annotations":[{"name":"pbi:EntityTypeDisplayHint","value":"LinkedEntity"}]},{"$type":"ReferenceEntity","name":"GL Project Segment","description":"","source":"GL Project Segment","modelId":"00113def-72e3-4c77-92ea-121a71b998e4/9ae7027c-9e54-4c14-a321-320f1fd0fdd3","annotations":[{"name":"pbi:EntityTypeDisplayHint","value":"LinkedEntity"}]},{"$type":"ReferenceEntity","name":"DIM_Calendar","description":"","source":"Fiscal Calendar Days","modelId":"00113def-72e3-4c77-92ea-121a71b998e4/9ae7027c-9e54-4c14-a321-320f1fd0fdd3","annotations":[{"name":"pbi:EntityTypeDisplayHint","value":"LinkedEntity"}]},{"$type":"ReferenceEntity","name":"Fiscal Context","description":"","source":"Fiscal Context","modelId":"00113def-72e3-4c77-92ea-121a71b998e4/9ae7027c-9e54-4c14-a321-320f1fd0fdd3","annotations":[{"name":"pbi:EntityTypeDisplayHint","value":"LinkedEntity"}]},{"$type":"ReferenceEntity","name":"DIM_GLDepartment","description":"","source":"GL Department Segment","modelId":"00113def-72e3-4c77-92ea-121a71b998e4/9ae7027c-9e54-4c14-a321-320f1fd0fdd3","annotations":[{"name":"pbi:EntityTypeDisplayHint","value":"LinkedEntity"}]},{"$type":"ReferenceEntity","name":"DIM_GLEntity","description":"","source":"GL Entity Segment","modelId":"00113def-72e3-4c77-92ea-121a71b998e4/9ae7027c-9e54-4c14-a321-320f1fd0fdd3","annotations":[{"name":"pbi:EntityTypeDisplayHint","value":"LinkedEntity"}]},{"$type":"ReferenceEntity","name":"Inventory Organizations","description":"","source":"Inventory Organizations","modelId":"00113def-72e3-4c77-92ea-121a71b998e4/9ae7027c-9e54-4c14-a321-320f1fd0fdd3","annotations":[{"name":"pbi:EntityTypeDisplayHint","value":"LinkedEntity"}]},{"$type":"ReferenceEntity","name":"Operating Units","description":"","source":"Operating Units","modelId":"00113def-72e3-4c77-92ea-121a71b998e4/9ae7027c-9e54-4c14-a321-320f1fd0fdd3","annotations":[{"name":"pbi:EntityTypeDisplayHint","value":"LinkedEntity"}]},{"$type":"ReferenceEntity","name":"Operating Unit Data Security","description":"","source":"Operating Unit Data Security","modelId":"00113def-72e3-4c77-92ea-121a71b998e4/9ae7027c-9e54-4c14-a321-320f1fd0fdd3","annotations":[{"name":"pbi:EntityTypeDisplayHint","value":"LinkedEntity"}]}],"referenceModels":[{"id":"00113def-72e3-4c77-92ea-121a71b998e4/9ae7027c-9e54-4c14-a321-320f1fd0fdd3","location":"https://wabiwuscpcdsap1.blob.core.windows.net/9eb1bce4-7877-44a7-a1f6-c27ac33e64c2/model.json?snapshot=2022-05-20T07:31:00.2885067Z"}]}