{"name":"TestLinkToOnedriveUpload","description":"","version":"1.0","culture":"en-US","modifiedTime":"2022-05-13T05:59:54.0780807+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"XXREP_M20_DETAIL_V_ALL_ACCOUNTS 1":{"queryId":"19264ff8-034e-4a6a-b654-64ca059ff0c7","queryName":"XXREP_M20_DETAIL_V_ALL_ACCOUNTS 1","loadEnabled":true},"pFilePath":{"queryId":"5382c625-a26d-4f1a-be24-319995b4b81d","queryName":"pFilePath"}},"document":"section Section1;\r\nshared #\"XXREP_M20_DETAIL_V_ALL_ACCOUNTS 1\" = let\n  Source = Csv.Document(Web.Contents(pFilePath), [Delimiter = \",\", Columns = 15, QuoteStyle = QuoteStyle.None]),\n  #\"Promoted headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"ENTITY\", Int64.Type}, {\"DEPT\", Int64.Type}, {\"ACCT\", Int64.Type}, {\"PROJ\", Int64.Type}, {\"M20_TBU\", type text}, {\"M20_PFC\", type text}, {\"INTERCO\", Int64.Type}, {\"ACCOUNT_DESC\", type text}, {\"GL_PERIOD\", type date}, {\"TRANS_DATE\", type datetime}, {\"TRAN_QTY\", type text}, {\"ACCOUNTED_DR\", type number}, {\"ACCOUNTED_CR\", type number}, {\"NET_ACCOUNTED_AMT\", type number}, {\"ACCOUNTED_NET_USD\", type number}})\nin\n  #\"Changed column type\";\r\nshared pFilePath = \"https://cohrinc-my.sharepoint.com/personal/colin_peacock_coherent_com/Documents/Apps/Microsoft Power Query/Uploaded Files/XXREP_M20_DETAIL_V_ALL_ACCOUNTS 1.csv\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type text];\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"XXREP_M20_DETAIL_V_ALL_ACCOUNTS 1","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"XXREP_M20_DETAIL_V_ALL_ACCOUNTS%201.csv"},"attributes":[{"name":"ENTITY","dataType":"int64"},{"name":"DEPT","dataType":"int64"},{"name":"ACCT","dataType":"int64"},{"name":"PROJ","dataType":"int64"},{"name":"M20_TBU","dataType":"string"},{"name":"M20_PFC","dataType":"string"},{"name":"INTERCO","dataType":"int64"},{"name":"ACCOUNT_DESC","dataType":"string"},{"name":"GL_PERIOD","dataType":"date"},{"name":"TRANS_DATE","dataType":"dateTime"},{"name":"TRAN_QTY","dataType":"string"},{"name":"ACCOUNTED_DR","dataType":"double"},{"name":"ACCOUNTED_CR","dataType":"double"},{"name":"NET_ACCOUNTED_AMT","dataType":"double"},{"name":"ACCOUNTED_NET_USD","dataType":"double"}]}]}