{"name":"Dimensions","description":"","version":"1.0","culture":"en-US","modifiedTime":"2021-01-21T02:05:03.091117+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":true,"queriesMetadata":{"Country_Region":{"queryId":"30652578-1f50-410c-91d1-dce644234cc1","queryName":"Country_Region","loadEnabled":true},"Territory":{"queryId":"665602fe-0e6c-4cf1-bf23-782c98b8e3f3","queryName":"Territory","loadEnabled":true},"Sourcing_Commodity":{"queryId":"57b3839d-4d91-44cf-bfe0-0b9e9985f5f4","queryName":"Sourcing_Commodity","loadEnabled":true},"Supplier":{"queryId":"13ba7acb-09f7-44bc-bccd-6cf164c96d64","queryName":"Supplier","loadEnabled":true},"Product_Category":{"queryId":"c4eb4cec-2986-4aba-ac64-2f88e3a70042","queryName":"Product_Category","loadEnabled":true},"Organization":{"queryId":"d88f2a2e-b962-4fb0-bb8a-5f6b494d47cb","queryName":"Organization","loadEnabled":true},"Item":{"queryId":"eac05f24-27c8-4d30-adcc-ef1481168b74","queryName":"Item","loadEnabled":true},"Buyer":{"queryId":"6b38c945-282c-4739-82b4-7ea75311dd60","queryName":"Buyer","loadEnabled":true},"Planner":{"queryId":"d3f9b6ac-bcdb-449c-842c-5212ddcce4b2","queryName":"Planner","loadEnabled":true},"Corporate_Rate":{"queryId":"5035993b-d4dc-466e-9bb7-e195eadd0114","queryName":"Corporate_Rate","loadEnabled":true},"Business_Segment":{"queryId":"e6e8d8e2-c7e7-4247-b65d-0731c6ea2eb9","queryName":"Business_Segment","loadEnabled":true},"Fiscal_Calendar":{"queryId":"4109c662-20e7-4f33-bd4b-bc6720d40fff","queryName":"Fiscal_Calendar","loadEnabled":true},"Item_Type":{"queryId":"44727939-6725-49ce-bc0c-37728870cd89","queryName":"Item_Type","loadEnabled":true}},"document":"section Section1;\r\nshared Country_Region = let\r\n  Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"hVrNkuI4En4VR59qIrpjJ/awewZjDIVt3LaBLmbnIEANmjJWjbCrhnqjue8bzItt5idXNagY7eXr6FJKTuV/pvjll0+D7/uDaNSpFc2nz58GY0DMeFIi+E/388///FeQi636rraffv1MG2rR7ILpif85Md03hmRAGHVGP8meakOnCiwBhu76Xhqsj9YA3j8wYhOUrWjlyRIdiWYrmqAUR42zSkDqY6/ZaWNAPGLIRs6Hm72usTxniIHf+TNvy52qLcEUwIyVumsP/0hEq5qgZ6qnboXZtvxfIv3KUA28zLVq34mAJTgUZtPtsBHirmLfh8xe0t4G5AXAT36UvfQhqyJ1hGC6DVZXDMOV76ju1BpR28MWgNJ3Qya3xBWIK+fLr9JshPrNWtsaEHnOG4qDOAq2syF/djgpPbwSsRGqAR2guGFUQ9Hsa7GTpwOTsHUM45GXA2J4p8ECG/GwGPpYkLUwHYgfGJLi+v60vlfdkZciQPJhXb1KXllj+9r7rcZe9h4nZdeWPJTmaO1rmAJYeZk27eH6kENnXX9YATKfKHStnqHc4RyQ+LjTJzJBmPpEmle518/WfofsIcPpxLm4bk8vwhKsAAPnPrp7lm0feJhgCah8LBjxqmroDOBz5aFRrTodgqUye1r6Ed+WMcCJX2/k02anKEDNt5Kwkob+rM2ZaKdzQOUTp+kaqYIRG8xJ1AJWkYFTrxa6ei+sjw1jgGtjnXkkUQdjcdK8Pga44uzo6zsFVcARptfroThu9A5fmU0AvqhL1NJozXYUpoDCPa4RMMZwAMhuGmMonmSwlGbHHhCygsN86R50PopL/czYz8KH1KPbkGInxbDAHtMEhXzqNjWxThvHYGfsfOSgarDABh5OfGZOpDDaMAOpT3ET3eyDGcHnoBwUwdvOyQzgy7mp2Ap9vStl+0oHoU8pB0N5naLnD6cJvwEK3y691afgbiYpEjX7ny4kHYaAmXdzrY8bWE04B3hlp4/aILLOYDTz9Ea8DklgOrhjX34Vz5Sb5U9MG2ND7OiNaT8T86o5HcRJgHIEypFLqR8vrzYDkf9qVCMFhc31YQGY+i73139bGexw0r+nz1oZWNQU4Bq10bQfxlAAltceHZ6fbFIJrbHnzvKr3B6urHoNiK7JRrI5CvNIfxzxRUfZzFn/TW3oMhwTRveA6Q19jPRRNVYKoxTgC6tv1FdON5oDfC4bbTtKuoYZDAELH/H+/NQyVQx4uMF1VFMRWT/3Z5Ys3zJZ+s78vRMUyhWFjbhTjeT7xlzhxdnXa+VFFPMN1iME4sKJpNGp1bYYi6CQ0imJovag9JMlwFI1uT5gLOrHy6I7uEvpKhQGTmzfY9biOJl57jIWRssLax+z/MfF/JqPsWr6KDGeAjJn3YhmK7ETMHCXZUNWSMKyWTzmmBovxj6+7JZc1+dGniCBnOnzh7HHEftdOFSaH1lXSb5bha2V74BYbJCp4gFgeC3tWPQBLE4B7rLUVCBgPQI4Uoyp7BINVwCjCLBw1g+9eCYAJyvHakOJipoKXpwCnMIjNlJCC8j6cRF+XH5TY5yAIvlA0adilL1xMfJoKCYvlLXunvDFHIfmfvpWHgX6p7gC+Lw87kiBJ8nSimPAg8Psu+tlEIZT49rlL0NF9VPHBCuQuirrzr3MH2CSDx6OJkIhAE4qgC/AT6QwO9S36XanG1FfdsWoliapr7GYkNkHpZTB3VK0CJGhas82aLFjLwcAJ1pQEbHrDDoiFBuTzKe/SddQrcjynSwAjk9Pt7I3lmkJcIwF5S0vZADfdYhUv3nxdATwFUNTiiafIbCj2r4nh0B/550FwL/9nfEIxC7jp1rSYUGK3maaAtzLn4yQ3B5ME9zdKaOnrahRyVcAJ9zdU1tqs+A9H34/8Nn5vXgCH/c5wHexe2msQ9xHAMch7rXZ2aPmgFsd7ky8isdDP9GZcSkws53233xyJpsz6vwI4PjYTBm1EXCK2RTgqx5nmlJhcIfSno14xjfOC19h1W+B7LCFz5/NvV/pXshPmWwFqG5J4Wz259c3KcQAnxQSoYN8xF/FLCux86G/JW5tI4waIlk6xpHIjWiQYzD3StDVuQwm8qTbA3doSQlwRlGJ2vQjMgwRkmHxYR1qSx6weqvqSRQVhq1sTq3EpCCZApy6MFHtoeundUkFcJJW0v0hqR3szJ5XF4Bv1yTUosgd1zmfHWdOZ4CRS74Te3HaItOlrJ105BTzVOSIFza7dAWYflw+23CTPgB8cymi3qlnVAjpEl9b+qlbHMzSSJPK5d1Qd1HXF+E+nQAS75mGwoL6veNUmn7F6V89MSMVHZU1vVrQTqfFLTu3dArtAWY8qR3QXUrqrNuWP/uA+wAv1+Ufast2mLJO0+ibjyu1NTbMfw7GcicN8bHr2bH6HnMgHHtntKmud/oZ9xoBHPdJKZtahkLA/MPyXtuJJEJ6mnl7Z92QB8i9wYER6KMPB7YnqiIFh5S0BBQ+IVDXurUMDgC3onCqX7mS7PXNkSedrx3BU11ytB6QAnwxL6NEaQvTbABIrw/LyA64BsoKwMJ3lHwSnPeyHOCz2kxykf1m5lkCcHz5gibgCTe16HgYQNDLfAO6TL4Eoaht4OCjQ4CfoZdgLUWf/LM1wLuBPmbEvsP5U0DoY0ntJWsENpJFTszFqmU1Bjj1O+W977p+/DFwycYAX/5DruRGJuWpXiMuw0oOc839u18E1wvZHOAUMbl4fHvbyZmJfOBjJSe5sg3lHHHzZOUnlScOaM7cMy8B0Q2PyOlyRzR5A0DmUUMunjoRsLLfW4CcJZ57fT23mgYfnBPywlfr5wdVq6cnOp5lnU8APlPKVbsVykCYzHwe+io5amutDcDB8rlToeak9m4PP8wr8OqkmZyao1bzxEljGeBrSL4K2zh+HQBuJYtCdo1CYVJEAF+YKPSxTz8YFRRzpyooutOJ1d/ngf7cBaB0SF9IFDhpBXDcphSqab8MKUMe/vqzlkdW4DAB+MpqbAsmspZo78oJILtxdjBTbXtCs5bJZ4WRYwbwDa/s1qTb2tIoBPzfDV9spg/u+kHFE/2X69p0jFzhG4jYD+aK/EnazpLzRw3B5pAE8OPg3G5cqmYr6V/eadv83raXIcAXit+eWFclwJe+S2FjVcN2CcoydcJOScV0pY/2EjmRbhVGCJh9lVXuqqjbqYBtFYIuIWL72OjYb8mZHD5TInq4zUopjT2jwDth4QxPSnneHmSfn0qkgYfQOYGFL4JEUpXD65hfJ5FLRG31k8ZEt8RDbOyL0WVN1c6jvRvmdEtn8soE/YNtCQ9fOq1qyXN1ffnsUeIVEu3F336W/NeWSWgtypvjddhD/zJCy3iHX7vvIZaoH31Bp5Sx7AQuIGvYvSiy8x+8xRB+7Huq7fd2tpktQVo6M/ryyT7mRggmpTP0Lo0KEtE8wjVnAN/T+/unMC4Z3WrISiqkKUNBqSj/Fr4isHwW9eZtAnQPlzjLKw3dA5yn9/KF3yRtYijxurtyqsLyheIpWI2wHLkHqPbVlluf+MUJ4NKcuZKAR/3oxu7w159g9ABftVkJ9cIDmote7v3pqVoBfLmvEr+p98Kjugf4Co9KNK8CzeOiUdxRXPeQ1RrgZI3qIN4kiZF5NfEZQKWO2nyhphudUJUAfC1jpR+lLYeqGcBXGlTUk0A2c4BXNmRlaies4VR6I/YcR6sKMPdYXEW52za8eKWvFreMuOrMI+ZHVQEaJzDzMv825E01KW7mi/a8w2bOUCh+Gvxh4VUI8GXEqiM3gQyXYMfXdS/2fZGwiAGOuheP/OMOVt6CVxYz52q95UAg0VEZiIROQOwubhWk/Y4ZRfOd5td3vPLHw9sHvze57xckJkoAGrIPSXlRUv5utAnmXVuf6SMXolukgKlPHKbra1lMrBfeWnbxupHvDrdYA3y5YSmaTrSsmOUC4PuhwpKy7ivVISK4w09A0Ke8uyhm1RHAV9EvlWyDDD9yQHZbZj6ru/4ZBoUFFvRyCvBF5ZWoa2XNddy13VU3teKstkp8T0MrDg+Gf3B2EPgRWYSfqZTOi9yDPCJCP0SAW3l1/faMtE4BzpvEWh03YvPC1rxeAS5LjF//Bw==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Country Name\" = _t, #\"Country 2 Digits\" = _t, #\"Country 3 Digits\" = _t, Region = _t]),\r\n  #\"Changed Type\" = Table.TransformColumnTypes(Source, {{\"Country Name\", type text}, {\"Country 2 Digits\", type text}, {\"Country 3 Digits\", type text}, {\"Region\", type text}})\r\nin\r\n  #\"Changed Type\";\r\nshared Territory = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, \n  Query=\"\n  select TERRITORY_CODE,TERRITORY_SHORT_NAME,DESCRIPTION\n    from APPLSYS.FND_TERRITORIES_TL\n    where language = 'US'\n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed Columns\" = Table.RenameColumns(Source, {{\"TERRITORY_CODE\", \"Territory Code\"}, {\"TERRITORY_SHORT_NAME\", \"Terrirtory Short Name\"}, {\"DESCRIPTION\", \"Territory Description\"}})\r\nin\r\n  #\"Renamed Columns\";\r\nshared Sourcing_Commodity = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, \n  Query=\"\n  select \n  mc.category_id,\n  mc.segment1 commodity_sequence,\n  mc.segment2 sourcing_commodity,\n  mc.segment3 scc_unspsc,\n  mck.concatenated_segments,\n  mc.structure_name\nFROM\n    apps.mtl_categories_kfv   mck,\n    apps.mtl_categories_v     mc\nWHERE 1=1\n    AND mc.structure_id = mck.structure_id\n    AND mc.category_id = mck.category_id\n    AND mc.structure_name = 'Sourcing Commodity'\n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed Columns\" = Table.RenameColumns(Source, {{\"COMMODITY_SEQUENCE\", \"Sequence\"}, {\"SOURCING_COMMODITY\", \"Commodity\"}, {\"SCC_UNSPSC\", \"SCC UNSPSC Code\"}, {\"CONCATENATED_SEGMENTS\", \"Category Name\"}})\r\nin\r\n  #\"Renamed Columns\";\r\nshared Supplier = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, \n  Query=\"\n  SELECT\n    sysdate                   extract_date,\n    xxpov.segment1            supplier_number,\n    xxpov.vendor_name,\n    xxvd.vendor_type,\n    xxpov.vendor_name_alt,\n    xxpovs.vendor_site_id,\n    xxpovs.vendor_id,\n    xxpovs.vendor_site_code,\n    xxpovs.vendor_site_code_alt,\n    hou.name                  operating_unit,\n    (\n        CASE\n            WHEN xxpovs.vendor_site_code_alt IS NOT NULL THEN\n                'Yes'\n            ELSE\n                'No'\n        END\n    ) production_supplier_flag,\n    xxpovs.creation_date      supplier_creation_date,\n    xxpovs.last_update_date   supplier_last_update_date,\n    xxpovs.pay_site_flag,\n    xxpovs.purchasing_site_flag,\n    xxpovs.city,\n    xxpovs.country,\n    xxpovs.country_of_origin_code,\n    (\n        CASE\n            WHEN least(nvl(xxpov.end_date_active, sysdate + 1), nvl(xxpovs.inactive_date, sysdate + 1)) < trunc(sysdate) THEN\n                'No'\n            ELSE\n                'Yes'\n        END\n    ) active_supplier_flag,\n    CASE\n        WHEN nvl(xxpov.end_date_active, sysdate + 1) > nvl(xxpovs.inactive_date, sysdate + 1) THEN\n            xxpovs.inactive_date\n        ELSE\n            xxpov.end_date_active\n    END inactive_date,\n    xxpovs.invoice_currency_code,\n    xxpovs.payment_currency_code,\n    xxpovs.payment_method_lookup_code,\n    xxpov.vendor_type_lookup_code,\n    decode(xxpov.attribute1, 'Y', 'Yes', 'No') internal_supplier_flag,\n    decode(xxpov.attribute4, 'Y', 'Yes', 'No') isupplier_forecast_flag,\n    xxpovs.fob_lookup_code,\n    xxpovs.freight_terms_lookup_code,\n    apt.name                  payment_term,\n    xxpov.attribute5          supplier_class,\n    nvl(xxvd.vendor_category, 'Unassigned') supplier_category,\n    nvl(xxvd.ssm_lead, 'Unassigned') ssm_lead,\n    nvl(xxvd.master_vendor_name, xxpov.vendor_name) master_supplier,\n    nvl(xxvd.attribute1, 'NA') key_and_risk_flag,\n    decode(xxvd.attribute2, 'Y', 'Yes', 'No') kpi_flag\nFROM\n    apps.po_vendors            xxpov,\n    apps.po_vendor_sites_all   xxpovs,\n    apps.hr_operating_units    hou,\n    apps.ap_terms_v            apt,\n    xxdims.xx_vendor_dim       xxvd\nWHERE\n    1 = 1\n    AND xxpov.vendor_id = xxpovs.vendor_id\n    AND xxpovs.org_id = hou.organization_id\n    AND xxpovs.terms_id = apt.term_id (+)\n    AND xxpov.vendor_id = xxvd.vendor_id (+)\n    AND EXISTS (\n        SELECT\n            1\n        FROM\n            apps.po_headers_all   pha,\n            apps.po_lines_all     pla\n        WHERE\n            pha.vendor_id = xxpovs.vendor_id\n            AND pha.vendor_site_id = xxpovs.vendor_site_id\n            AND pla.po_header_id = pha.po_header_id\n            AND pla.item_id > 0\n    )\n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"EXTRACT_DATE\", \"Extract Date\"}, {\"SUPPLIER_CREATION_DATE\", \"Supplier Creation Date\"}, {\"SUPPLIER_LAST_UPDATE_DATE\", \"Supplier Last Update Date\"}, {\"SUPPLIER_NUMBER\", \"Supplier Number\"}, {\"VENDOR_NAME\", \"Supplier Name\"}, {\"VENDOR_NAME_ALT\", \"Supplier Name Alternate\"}, {\"VENDOR_SITE_CODE\", \"Supplier Site Code\"}, {\"VENDOR_SITE_CODE_ALT\", \"Supplier Site Code Alternate\"}, {\"PRODUCTION_SUPPLIER_FLAG\", \"Production Supplier Flag\"}, {\"PAY_SITE_FLAG\", \"Pay Site Flag\"}, {\"PURCHASING_SITE_FLAG\", \"Purchasing Site Flag\"}, {\"CITY\", \"City\"}, {\"COUNTRY\", \"Country\"}, {\"COUNTRY_OF_ORIGIN_CODE\", \"Country of Origin\"}, {\"ACTIVE_SUPPLIER_FLAG\", \"Active Supplier Flag\"}, {\"INACTIVE_DATE\", \"Inactive Date\"}, {\"INVOICE_CURRENCY_CODE\", \"Invoice Currency\"}, {\"PAYMENT_CURRENCY_CODE\", \"Payment Currency\"}, {\"PAYMENT_METHOD_LOOKUP_CODE\", \"Payment Method\"}, {\"VENDOR_TYPE_LOOKUP_CODE\", \"Supplier Type\"}, {\"ISUPPLIER_FORECAST_FLAG\", \"ISupplier Forecast Flag\"}, {\"FOB_LOOKUP_CODE\", \"FOB\"}, {\"FREIGHT_TERMS_LOOKUP_CODE\", \"Freight Term\"}, {\"PAYMENT_TERM\", \"Payment Term\"}, {\"INTERNAL_SUPPLIER_FLAG\", \"Internal Supplier Flag\"}, {\"SUPPLIER_CLASS\", \"Supplier Class\"}, {\"SSM_LEAD\", \"SSM Lead\"}, {\"SUPPLIER_CATEGORY\", \"Supplier Commodity\"}, {\"MASTER_SUPPLIER\", \"Master Supplier\"}, {\"KEY_AND_RISK_FLAG\", \"Key and Risk Flag\"}, {\"KPI_FLAG\", \"KPI Required Flag\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Product_Category = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, \n  Query=\"\n  SELECT\n    mc.category_id,\n    mc.segment1   tbu,\n    mc.segment2   product_family,\n    mc.segment3   product_line,\n    mc.segment4   forecast_line,\n    mck.concatenated_segments,\n    mc.STRUCTURE_NAME\nFROM\n    apps.mtl_categories_kfv   mck,\n    apps.mtl_categories_v     mc\nWHERE\n    mc.structure_name = 'Product Family/Line'\n    AND mc.structure_id = mck.structure_id\n    AND mc.category_id = mck.category_id\n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed Columns\" = Table.RenameColumns(Source, {{\"PRODUCT_FAMILY\", \"Product Family\"}, {\"PRODUCT_LINE\", \"Product Line\"}, {\"FORECAST_LINE\", \"Forecast Line\"}, {\"CONCATENATED_SEGMENTS\", \"Category Name\"}})\r\nin\r\n  #\"Renamed Columns\";\r\nshared Organization = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, \n  Query=\"\n SELECT\n    ood.organization_code,\n    mp.attribute13      organization_type,\n    hou.name            operating_unit,\n    sob.currency_code   functional_currency,\n    sob.short_name,\n    sob.description,\n    ood.organization_id,\n    ood.set_of_books_id,\n    LOC.COUNTRY org_country\nFROM\n    apps.mtl_parameters                 mp,\n    apps.org_organization_definitions   ood,\n    apps.hr_operating_units             hou,\n    apps.gl_sets_of_books_v             sob,\n    apps.hr_organization_units hou1,\n    HR.HR_LOCATIONS_ALL     loc\nWHERE\n    mp.organization_id = ood.organization_id\n    AND hou.organization_id = ood.operating_unit\n    AND sob.set_of_books_id = ood.set_of_books_id\n    and hou1.organization_id = mp.organization_id\n    AND hou1.location_id=loc.location_id (+)\n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed Columns\" = Table.RenameColumns(Source, {{\"ORGANIZATION_CODE\", \"Organization Code\"}, {\"ORGANIZATION_TYPE\", \"Organization Type\"}, {\"OPERATING_UNIT\", \"Operating Unit\"}, {\"FUNCTIONAL_CURRENCY\", \"Functional Currency\"}, {\"SHORT_NAME\", \"Short Name\"}, {\"DESCRIPTION\", \"Description\"}, {\"ORG_COUNTRY\", \"Org Country\"}})\r\nin\r\n  #\"Renamed Columns\";\r\nshared Item = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, \n  Query=\"\n SELECT\n    sysdate                          extract_date,\n    mp.organization_code,\n    mp.organization_id,\n    mp.organization_code\n    || '_'\n    || msi.segment1 item_key,\n    msi.inventory_item_id,\n    mp.organization_code||'_'||msi.planner_code planner_key,\n    msi.item_Type,\n    msi.segment1                     item_number,\n    decode(msi.mrp_planning_code, 3, 'MRP Planning', 4, 'MPS Planning',\n           6, 'Not Planned', 7, 'MRP/MPP Planned', 8,\n           'MPS/MPP Planned', 9, 'MPP Planned') mrp_planning_code,\n    itd.item_rev_num                 item_revision,\n    msi.description,\n    msi.primary_unit_of_measure,\n    msi.inventory_item_status_code   item_status,\n    msi.inventory_item_flag,\n    decode(msi.lot_control_code, 2, 'Full Control', 'No Control') lot_control_code,\n    decode(msi.serial_number_control_code, 1, 'No Control', 5, 'At Receipt',\n           2, 'Predefined', 6, 'At Sales Order Issue') serial_control_code,\n    decode(msi.receiving_routing_id, 1, 'Standard', 2, 'Inspection',\n           3, 'Direct', msi.receiving_routing_id) receipt_routing,\n    (\n        SELECT\n            agent_name\n        FROM\n            apps.po_agents_v poa\n        WHERE\n            poa.agent_id = msi.buyer_id\n    ) default_buyer,\n    msi.buyer_id,\n    decode(planning_make_buy_code, 1, 'Make', 2, 'Buy') planning_make_buy_code,\n    msi.planner_code,\n    msi.preprocessing_lead_time,\n    msi.full_lead_time               processing_lead_time,\n    msi.postprocessing_lead_time,\n    msi.lead_time_lot_size,\n    msi.fixed_lead_time,\n    msi.variable_lead_time,\n    msi.list_price_per_unit,\n    msi.creation_date                item_creation_date,\n    msi.costing_enabled_flag,\n    msi.inventory_asset_flag,\n    decode(msi.planning_time_fence_code, 1, 'Cumulative Total Lead Time', 2, 'Cumulative MFG Lead Time',\n           3, 'Total Lead Time', 4, 'User Defined', msi.planning_time_fence_code) planning_time_fence,\n    msi.planning_time_fence_days,\n    decode(msi.demand_time_fence_code, 1, 'Cumulative Total Lead Time', 2, 'Cumulative MFG Lead Time',\n           3, 'Total Lead Time', 4, 'User Defined', msi.demand_time_fence_code) demand_time_fence,\n    msi.demand_time_fence_days,\n    decode(msi.release_time_fence_code, 6, 'Kanban Item (Do Not Release)', 7, 'Do Not Release (Auto or Manual)',\n           3, 'Total Lead Time', 2, 'Cumulative Mfg Lead Time', 1,\n           'Cumulative Total Lead Time', 4, 'User Defined', 5, 'Do Not Auto Release',\n           msi.release_time_fence_code) release_time_fence,\n    msi.release_time_fence_days,\n    msi.acceptable_early_days,\n    msi.fixed_days_supply,\n    msi.minimum_order_quantity,\n    msi.maximum_order_quantity,\n    msi.min_minmax_quantity,\n    msi.max_minmax_quantity,\n    msi.fixed_lot_multiplier,\n    msi.fixed_order_quantity,\n    decode(msi.source_type, 1, 'Inventory', 2, 'Supplier',\n           3, 'Subinventory') source_type,\n    (\n        SELECT\n            organization_code\n        FROM\n            inv.mtl_parameters mps\n        WHERE\n            msi.source_organization_id = mps.organization_id\n    ) source_org,\n    nvl(decode(msi.critical_component_flag, 1, 'Yes', 2, 'No',\n               msi.critical_component_flag), 'No') critical_component_flag,\n    decode(msi.inventory_planning_code, 1, 'Reorder Point', 2, 'Min Max',\n           6, 'Not Planned', 7, 'Vendor Managed', 'Not Planned') inventory_planning_code,\n    decode(msi.wip_supply_type, 1, 'Push', 2, 'Assembly Pull',\n           3, 'Operation Pull', 4, 'Bulk', 5,\n           'Supplier', 'Phantom') wip_supply_type,\n    CASE\n        WHEN msi.cycle_count_enabled_flag = 'N' THEN\n            'Not Applicable'\n        ELSE\n            nvl((\n                SELECT\n                    abc.abc_class_name\n                FROM\n                    apps.mrp_parameters_v        mrpp, apps.mtl_abc_assignments_v   abc\n                WHERE\n                    mrpp.organization_id = mp.organization_id\n                    AND mrpp.default_abc_assignment_group = abc.assignment_group_id\n                    AND abc.organization_id = mrpp.organization_id\n                    AND abc.inventory_item_id = msi.inventory_item_id\n            ), 'Blank')\n    END current_item_abc_class,\n    msi.wip_supply_subinventory,\n    (\n        SELECT\n            concatenated_segments\n        FROM\n            apps.mtl_item_locations_kfv mloc\n        WHERE\n            mloc.inventory_location_id = msi.wip_supply_locator_id\n    ) wip_supply_locator,\n    (\n        SELECT\n            segment1\n        FROM\n            apps.mtl_item_categories_v mic\n        WHERE\n            mic.inventory_item_id = msi.inventory_item_id\n            AND mic.organization_id = msi.organization_id\n            AND mic.category_set_name = 'Supply Chain Status'\n    ) supply_chain_status,\n    (\n        SELECT\n            category_concat_segs\n        FROM\n            apps.mtl_item_categories_v mic\n        WHERE\n            mic.inventory_item_id = msi.inventory_item_id\n            AND mic.organization_id = msi.organization_id\n            AND mic.category_set_name = 'ORG Product'\n    ) org_product,\n    (\n        SELECT\n            category_concat_segs\n        FROM\n            apps.mtl_item_categories_v mic\n        WHERE\n            mic.inventory_item_id = msi.inventory_item_id\n            AND mic.organization_id = msi.organization_id\n            AND mic.category_set_name = 'Product'\n    ) mas_product,\n    nvl((\n        SELECT\n            category_concat_segs\n        FROM\n            apps.mtl_item_categories_v mic\n        WHERE\n            mic.inventory_item_id = msi.inventory_item_id\n            AND mic.organization_id = msi.organization_id\n            AND mic.category_set_name = 'ORG Product'\n    ),(\n        SELECT\n            category_concat_segs\n        FROM\n            apps.mtl_item_categories_v mic\n        WHERE\n            mic.inventory_item_id = msi.inventory_item_id\n            AND mic.organization_id = msi.organization_id\n            AND mic.category_set_name = 'Product'\n    )) product_key,\n    \n    nvl((\n        SELECT\n            category_id\n        FROM\n            apps.mtl_item_categories_v mic\n        WHERE\n            mic.inventory_item_id = msi.inventory_item_id\n            AND mic.organization_id = msi.organization_id\n            AND mic.category_set_name = 'ORG Product'\n    ),(\n        SELECT\n            category_id\n        FROM\n            apps.mtl_item_categories_v mic\n        WHERE\n            mic.inventory_item_id = msi.inventory_item_id\n            AND mic.organization_id = msi.organization_id\n            AND mic.category_set_name = 'Product'\n    )) product_key_id,\n    (\n        SELECT\n            category_concat_segs\n        FROM\n            apps.mtl_item_categories_v mic\n        WHERE\n            mic.inventory_item_id = msi.inventory_item_id\n            AND mic.organization_id = msi.organization_id\n            AND mic.category_set_name = 'Sourcing Commodity'\n    ) sourcing_commodity,\n    (\n        SELECT\n            segment1\n        FROM\n            apps.mtl_item_categories_v mic\n        WHERE\n            mic.inventory_item_id = msi.inventory_item_id\n            AND mic.organization_id = msi.organization_id\n            AND mic.category_set_name = 'Commodity'\n    ) commodity,\n    nvl(itd.last_op_po_price, itd.last_po_price) last_po_unit_price,\n    nvl(itd.last_op_po_price, itd.last_po_price) * (\n        SELECT\n            rate_to_usd\n        FROM\n            xxdims.xx_budget_rate br\n        WHERE\n            br.currency_code = nvl(itd.last_op_po_currency_code, itd.last_po_currency_code)\n    ) last_po_unit_price_usd_budget,\n    nvl(itd.last_op_po_currency_code, itd.last_po_currency_code) last_po_currency,\n    nvl(itd.apop_classification,'APOP') APOP_CLASSIFICATION,\n    nvl(itd.baseline_unit_price,0) BASELINE_UNIT_PRICE,\n    nvl(itd.last_op_po_vendor_name, itd.last_po_vendor_name) last_po_vendor_name,\n    itd.po_project\nFROM\n    inv.mtl_system_items_b     msi,\n    inv.mtl_parameters         mp,\n    xxdims.xx_porec_item_dim   itd\nWHERE\n    msi.organization_id = mp.organization_id\n    AND msi.inventory_item_id = itd.inventory_item_id (+)\n    AND msi.organization_id = itd.inv_org_id (+)\n    AND EXISTS (\n        SELECT\n            1\n        FROM\n            apps.rcv_shipment_lines rsl\n        WHERE\n            rsl.to_organization_id = msi.organization_id\n            AND rsl.item_id = msi.inventory_item_id and rsl.po_header_id >0\n    )\n  \", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"EXTRACT_DATE\", \"Extract Date\"}, {\"ORGANIZATION_CODE\", \"Organization_Code\"}, {\"ITEM_NUMBER\", \"Item Number\"}, {\"ITEM_REVISION\", \"Item Revision\"}, {\"DESCRIPTION\", \"Item Description\"}, {\"PRIMARY_UNIT_OF_MEASURE\", \"Item Primary Unit of Measure\"}, {\"ITEM_STATUS\", \"Item Status\"}, {\"ITEM_TYPE\", \"Item Type\"}, {\"INVENTORY_ITEM_FLAG\", \"Inventory Item Flag\"}, {\"LOT_CONTROL_CODE\", \"Lot Control Code\"}, {\"SERIAL_CONTROL_CODE\", \"Serial Control Code\"}, {\"RECEIPT_ROUTING\", \"Receipt Routing\"}, {\"DEFAULT_BUYER\", \"Default Buyer\"}, {\"PLANNER_CODE\", \"Planner Code\"}, {\"PREPROCESSING_LEAD_TIME\", \"Preprocessing Lead Time\"}, {\"PROCESSING_LEAD_TIME\", \"Processing Lead Time\"}, {\"LEAD_TIME_LOT_SIZE\", \"Lead Time Lot Size\"}, {\"FIXED_LEAD_TIME\", \"Fixed Lead Time\"}, {\"VARIABLE_LEAD_TIME\", \"Variable Lead Time\"}, {\"LIST_PRICE_PER_UNIT\", \"List Price Per Unit\"}, {\"COSTING_ENABLED_FLAG\", \"Costing Enabled Flag\"}, {\"INVENTORY_ASSET_FLAG\", \"Inventory Asset Flag\"}, {\"POSTPROCESSING_LEAD_TIME\", \"Post Processing Lead Time\"}, {\"PLANNING_TIME_FENCE\", \"Planning Time Fence\"}, {\"PLANNING_TIME_FENCE_DAYS\", \"Planning Time Fence Days\"}, {\"DEMAND_TIME_FENCE\", \"Demand Time Fence\"}, {\"DEMAND_TIME_FENCE_DAYS\", \"Demand Time Fence Days\"}, {\"RELEASE_TIME_FENCE\", \"Release Time Fence\"}, {\"RELEASE_TIME_FENCE_DAYS\", \"Release Time Fence Days\"}, {\"ACCEPTABLE_EARLY_DAYS\", \"Acceptable Early Days\"}, {\"FIXED_DAYS_SUPPLY\", \"Fixed Days Supply\"}, {\"MINIMUM_ORDER_QUANTITY\", \"Minimum Order Quantity\"}, {\"MAXIMUM_ORDER_QUANTITY\", \"Maximum Order Quantity\"}, {\"MIN_MINMAX_QUANTITY\", \"Min Minmax Quantity\"}, {\"MAX_MINMAX_QUANTITY\", \"Max Minmax Quantity\"}, {\"FIXED_LOT_MULTIPLIER\", \"Fixed Lot Multiplier\"}, {\"FIXED_ORDER_QUANTITY\", \"Fixed Order Quantity\"}, {\"CRITICAL_COMPONENT_FLAG\", \"Critical Component Flag\"}, {\"INVENTORY_PLANNING_CODE\", \"Inventory Planning Code\"}, {\"WIP_SUPPLY_TYPE\", \"WIP Supply Type\"}, {\"CURRENT_ITEM_ABC_CLASS\", \"Current Item ABC Class\"}, {\"WIP_SUPPLY_SUBINVENTORY\", \"WIP Supply Subinventory\"}, {\"WIP_SUPPLY_LOCATOR\", \"WIP Supply Locator\"}, {\"SUPPLY_CHAIN_STATUS\", \"Supply Chain Status\"}, {\"ORG_PRODUCT\", \"Org Product\"}, {\"MAS_PRODUCT\", \"MAS Product\"}, {\"PRODUCT_KEY\", \"Product Key\"}, {\"SOURCING_COMMODITY\", \"Sourcing Commodity\"}, {\"COMMODITY\", \"Commodity\"}, {\"ITEM_CREATION_DATE\", \"Item Creation Date\"}, {\"PLANNING_MAKE_BUY_CODE\", \"Item Make or Buy\"}, {\"SOURCE_TYPE\", \"Item Default Source Type\"}, {\"SOURCE_ORG\", \"Item Source Organization Code\"}, {\"MRP_PLANNING_CODE\", \"MRP Planning Code\"}, {\"LAST_PO_UNIT_PRICE\", \"Last PO Unit Price\"}, {\"LAST_PO_CURRENCY\", \"Last PO Currency\"}, {\"APOP_CLASSIFICATION\", \"APOP Classification\"}, {\"BASELINE_UNIT_PRICE\", \"Baseline Unit Price USD\"}, {\"LAST_PO_VENDOR_NAME\", \"Last PO Supplier Name\"}, {\"LAST_PO_UNIT_PRICE_USD_BUDGET\", \"Last PO Unit Price USD (Budget)\"}, {\"PO_PROJECT\", \"PO Project\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Buyer = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, Query=\"\n  SELECT DISTINCT\n   SYSDATE EXTRACT_DATE,\n   POA.AGENT_ID BUYER_ID,\n   POA.AGENT_NAME,\n   PPV1.PPV1_APPROVER,\n   PPV2.PPV2_APPROVER,\n   (\n      SELECT\n         HRL.LOCATION_CODE \n      FROM\n         APPS.HR_LOCATIONS HRL,\n         APPS.PER_ASSIGNMENTS_F PA \n      WHERE\n         PA.LOCATION_ID = HRL.LOCATION_ID \n         AND SYSDATE BETWEEN PA.EFFECTIVE_START_DATE AND PA.EFFECTIVE_END_DATE \n         AND PA.PERSON_ID = POA.AGENT_ID \n         AND PA.ASSIGNMENT_ID = \n         (\n            SELECT\n               MAX(PA2.ASSIGNMENT_ID) \n            FROM\n               APPS.PER_ASSIGNMENTS_F PA2 \n            WHERE\n               PA2.PERSON_ID = PA.PERSON_ID \n         )\n         AND ROWNUM = 1 \n   )\n   BUYER_LOCATION,\n   (\n      SELECT\n         SUP.FULL_NAME \n      FROM\n         APPS.PER_PEOPLE_X SUP,\n         APPS.PER_ASSIGNMENTS_F PA \n      WHERE\n         SUP.PERSON_ID = PA.SUPERVISOR_ID \n         AND SYSDATE BETWEEN PA.EFFECTIVE_START_DATE AND PA.EFFECTIVE_END_DATE \n         AND PA.PERSON_ID = POA.AGENT_ID \n         AND PA.ASSIGNMENT_ID = \n         (\n            SELECT\n               MAX(PA2.ASSIGNMENT_ID) \n            FROM\n               APPS.PER_ASSIGNMENTS_F PA2 \n            WHERE\n               PA2.PERSON_ID = PA.PERSON_ID \n         )\n         AND ROWNUM = 1 \n   )\n   SUPERVISOR \n         FROM\n            APPS.PO_AGENTS_V POA,\n            (\n               SELECT\n                  TO_CHAR(PPX.PERSON_ID) AS PERSON_ID,\n                  PPX.FULL_NAME AS PPV1_APPROVER \n               FROM\n                  APPS.PER_PEOPLE_X PPX \n            )\n            PPV1,\n            (\n               SELECT\n                  TO_CHAR(PPX.PERSON_ID) AS PERSON_ID,\n                  PPX.FULL_NAME AS PPV2_APPROVER \n               FROM\n                  APPS.PER_PEOPLE_X PPX \n            )\n            PPV2\n         WHERE\n            1 = 1 \n            AND POA.ATTRIBUTE2 = PPV1.PERSON_ID \n            AND POA.ATTRIBUTE3 = PPV2.PERSON_ID \n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"AGENT_NAME\", \"Buyer Name\"}, {\"EXTRACT_DATE\", \"Extract Date\"}, {\"PPV1_APPROVER\", \"PPV1 Approver\"}, {\"PPV2_APPROVER\", \"PPV2 Approver\"}, {\"BUYER_LOCATION\", \"Location\"}, {\"SUPERVISOR\", \"Supervisor Name\"}}),\r\n  #\"Filtered rows\" = Table.SelectRows(#\"Renamed columns\", each [Buyer Name] <> \"Oracle, Production\")\r\nin\r\n  #\"Filtered rows\";\r\nshared Planner = let\r\n  Source = Oracle.Database(\"COHREP\", \n  [HierarchicalNavigation=true, \n  Query=\"\n  SELECT\n  sysdate EXTRACT_DATE,\n  MP.organization_code,\n  MP.ORGANIZATION_CODE||'_'||MPL.PLANNER_CODE PLANNER_KEY,\n  MPL.planner_code,\n  MPL.description,\n  MPL.disable_date,\n  MPL.electronic_mail_address,\n  (SELECT\n    full_name\n  FROM APPS.PER_PEOPLE_F PPF\n  WHERE PPF.person_id = MPL.employee_id\n  AND rownum = 1)\n  PLANNER_NAME\nFROM\n  INV.MTL_PLANNERS MPL,\n  inv.mtl_parameters MP\nWHERE\n  MP.organization_id = MPL.organization_id\n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"PLANNER_CODE\", \"Planner Code\"}, {\"DESCRIPTION\", \"Planner Description\"}, {\"ELECTRONIC_MAIL_ADDRESS\", \"Planner Email Address\"}, {\"PLANNER_NAME\", \"Planner Name\"}, {\"DISABLE_DATE\", \"Disable Date\"}, {\"ORGANIZATION_CODE\", \"Organization Code\"}, {\"EXTRACT_DATE\", \"Extract Date\"}}),\r\n  #\"Added Index\" = Table.AddIndexColumn(#\"Renamed columns\", \"Index\", 1, 1, Int64.Type)\r\nin\r\n  #\"Added Index\";\r\nshared Corporate_Rate = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, \n  Query=\"\n SELECT\n    from_currency,\n    to_currency,\n    gdr.conversion_date,\n    gdr.conversion_type,\n    gdr.conversion_rate usd_rate\nFROM\n    apps.gl_daily_rates_v gdr\nWHERE\n    conversion_type = 'Corporate'\n    AND to_currency = 'USD'\n\", CommandTimeout=#duration(0, 0, 10, 0)])\r\nin\r\n  Source;\r\nshared Business_Segment = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, \n  Query=\"\n SELECT\n    business_segment_id,\n    business_segment,\n    tbu\nFROM\n    xxcoh.xxcoh_business_segment_map\n\", CommandTimeout=#duration(0, 0, 10, 0)])\r\nin\r\n  Source;\r\nshared Fiscal_Calendar = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, \r\n  Query=\"\r\n SELECT\r\n    sysdate                                                                                       extract_date,\r\n    al1.period_date                                                                               calendar_date,\r\n    al1.year_start_date                                                                           fc_year_start_date,\r\n    al1.period_year                                                                               fc_year,\r\n    al1.quarter_start_date                                                                        fc_quarter_start_date,\r\n    'Q' || al1.quarter_num                                                                        fc_quarter,\r\n    CASE\r\n        WHEN al1.quarter_num <= 2 THEN\r\n            'H1'\r\n        ELSE\r\n            'H2'\r\n    END fc_half,\r\n    al1.period_num                                                                                fc_period_number,\r\n    substr(al1.period_name, 1, 3)                                                                 fc_period_month,\r\n    al1.period_name                                                                               fc_period_name,\r\n    ( al1.period_year - 1 ) * 12 + al1.period_num                                                 fc_period_id,\r\n    ( al1.period_year - 1 ) * 4 + al1.quarter_num                                                 fc_quarter_id,\r\n    ceil((al1.period_date - TO_DATE('02-OCT-1999', 'DD-MON-RRRR')) / 7)                           fc_week_id,\r\n    al1.period_year - (\r\n        SELECT\r\n            ( cd.period_year )\r\n        FROM\r\n            (\r\n                SELECT\r\n                    gdpm.period_set_name,\r\n                    gp.period_name,\r\n                    gdpm.accounting_date period_date,\r\n                    gp.period_year,\r\n                    gp.period_num,\r\n                    gp.quarter_num,\r\n                    gp.year_start_date,\r\n                    gp.quarter_start_date\r\n                FROM\r\n                    gl.gl_date_period_map    gdpm,\r\n                    gl.gl_periods            gp\r\n                WHERE\r\n                        gdpm.period_set_name = 'COHR Calendar'\r\n                    AND gp.period_name = gdpm.period_name\r\n                    AND gdpm.period_set_name = gp.period_set_name\r\n                    AND gdpm.accounting_date = trunc(sysdate)\r\n            ) cd\r\n    ) fc_year_offset,\r\n    ( ( al1.period_year - 1 ) * 4 + al1.quarter_num ) - (\r\n        SELECT\r\n            ( cd.period_year - 1 ) * 4 + cd.quarter_num\r\n        FROM\r\n            (\r\n                SELECT\r\n                    gdpm.period_set_name,\r\n                    gp.period_name,\r\n                    gdpm.accounting_date period_date,\r\n                    gp.period_year,\r\n                    gp.period_num,\r\n                    gp.quarter_num,\r\n                    gp.year_start_date,\r\n                    gp.quarter_start_date\r\n                FROM\r\n                    gl.gl_date_period_map    gdpm,\r\n                    gl.gl_periods            gp\r\n                WHERE\r\n                        gdpm.period_set_name = 'COHR Calendar'\r\n                    AND gp.period_name = gdpm.period_name\r\n                    AND gdpm.period_set_name = gp.period_set_name\r\n                    AND gdpm.accounting_date = trunc(sysdate)\r\n            ) cd\r\n    ) fc_quarter_offset,\r\n    ( ( al1.period_year - 1 ) * 12 + al1.period_num ) - (\r\n        SELECT\r\n            ( cd.period_year - 1 ) * 12 + cd.period_num\r\n        FROM\r\n            (\r\n                SELECT\r\n                    gdpm.period_set_name,\r\n                    gp.period_name,\r\n                    gdpm.accounting_date period_date,\r\n                    gp.period_year,\r\n                    gp.period_num,\r\n                    gp.quarter_num,\r\n                    gp.year_start_date,\r\n                    gp.quarter_start_date\r\n                FROM\r\n                    gl.gl_date_period_map    gdpm,\r\n                    gl.gl_periods            gp\r\n                WHERE\r\n                        gdpm.period_set_name = 'COHR Calendar'\r\n                    AND gp.period_name = gdpm.period_name\r\n                    AND gdpm.period_set_name = gp.period_set_name\r\n                    AND gdpm.accounting_date = trunc(sysdate)\r\n            ) cd\r\n    ) fc_period_offset,\r\n    ( al1.period_date - al1.year_start_date ) + 1                                                 doy_number,\r\n    ( al1.period_date - trunc(sysdate) )                                                          fc_day_offset,\r\n    CASE\r\n        WHEN ceil((al1.period_date - al1.year_start_date + 1) / 7) < 10 THEN\r\n            'W0'\r\n            || ceil((al1.period_date - al1.year_start_date + 1) / 7)\r\n        ELSE\r\n            'W'\r\n            || ceil((al1.period_date - al1.year_start_date + 1) / 7)\r\n    END fc_week,\r\n    CASE\r\n        WHEN ceil((al1.period_date - al1.quarter_start_date + 1) / 7) < 10 THEN\r\n            'QW0'\r\n            || ceil((al1.period_date - al1.quarter_start_date + 1) / 7)\r\n        ELSE\r\n            'QW'\r\n            || ceil((al1.period_date - al1.quarter_start_date - 1) / 7)\r\n    END fc_quarter_week,\r\n    ceil((al1.period_date - TO_DATE('02-OCT-1999', 'DD-MON-RRRR')) / 7) - ceil(((trunc(sysdate)) - TO_DATE('02-OCT-1999', 'DD-MON-RRRR')) /\r\n    7) fc_week_offset,\r\n    ( al1.period_year * 100 + ceil((al1.period_date - al1.year_start_date + 1) / 7) )               fc_week_series,\r\n    ceil((al1.period_date - al1.year_start_date + 1) / 7)  fc_week_number,\r\n    to_char(al1.period_date, 'DAY')                                                                 day_name,\r\n    to_char(al1.period_date, 'D')                                                                  dow_number\r\nFROM\r\n    (\r\n        SELECT\r\n            gdpm.period_set_name,\r\n            gp.period_name,\r\n            gdpm.accounting_date period_date,\r\n            gp.period_year,\r\n            gp.period_num,\r\n            gp.quarter_num,\r\n            gp.year_start_date,\r\n            gp.quarter_start_date\r\n        FROM\r\n            gl.gl_date_period_map    gdpm,\r\n            gl.gl_periods            gp\r\n        WHERE\r\n                gdpm.period_set_name = 'COHR Calendar'\r\n            AND gp.period_name = gdpm.period_name\r\n            AND gdpm.period_set_name = gp.period_set_name\r\n    ) al1\r\n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"EXTRACT_DATE\", \"Extract Date\"}, {\"FC_YEAR_START_DATE\", \"FC Year Start Date\"}, {\"FC_YEAR\", \"FC Year\"}, {\"FC_QUARTER_START_DATE\", \"FC Quarter Start Date\"}, {\"FC_QUARTER\", \"FC Quarter\"}, {\"FC_PERIOD_NUMBER\", \"FC Period Number\"}, {\"FC_PERIOD_MONTH\", \"FC Period Month\"}, {\"FC_HALF\", \"FC Half\"}, {\"FC_PERIOD_NAME\", \"FC Period Name\"}, {\"FC_WEEK_SERIES\", \"FC Week Series\"}, {\"FC_WEEK_NUMBER\", \"FC Week Number\"}, {\"FC_QUARTER_WEEK\", \"FC Quarter Week\"}, {\"FC_WEEK\", \"FC Week\"}, {\"FC_DAY_OFFSET\", \"FC Day Offset\"}, {\"FC_WEEK_OFFSET\", \"FC Week Offset\"}, {\"FC_PERIOD_OFFSET\", \"FC Period Offset\"}, {\"FC_QUARTER_OFFSET\", \"FC Quarter Offset\"}, {\"FC_YEAR_OFFSET\", \"FC Year Offset\"}, {\"CALENDAR_DATE\", \"Calendar Date\"}, {\"FC_WEEK_ID\", \"FC Week ID\"}, {\"FC_PERIOD_ID\", \"FC Period ID\"}, {\"FC_QUARTER_ID\", \"FC Quarter ID\"}, {\"DOY_NUMBER\", \"Day of Year Number\"}, {\"DAY_NAME\", \"Day Name\"}, {\"DOW_NUMBER\", \"Day of Week Number\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Item_Type = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, \r\n  Query=\"\r\n SELECT\r\n    lookup_code,\r\n    enabled_flag,\r\n    tag,\r\n    meaning,\r\n    description,\r\n    end_date_active,\r\n    attribute13,\r\n    attribute2\r\nFROM\r\n    apps.fnd_lookup_values flv\r\nWHERE\r\n        lookup_type = 'ITEM_TYPE'\r\n    AND language = 'US'\r\n    AND enabled_flag = 'Y'\r\n    AND view_application_id = 3\r\n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"LOOKUP_CODE\", \"Item Type Code\"}, {\"ENABLED_FLAG\", \"Enabled Flag\"}, {\"TAG\", \"Tag\"}, {\"MEANING\", \"Item Type\"}, {\"DESCRIPTION\", \"Item Type Description\"}}),\r\n  #\"Removed duplicates\" = Table.Distinct(#\"Renamed columns\", {\"Item Type\"})\r\nin\r\n  #\"Removed duplicates\";\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"Country_Region","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Country_Region.csv"},"attributes":[{"name":"Country Name","dataType":"string"},{"name":"Country 2 Digits","dataType":"string"},{"name":"Country 3 Digits","dataType":"string"},{"name":"Region","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-05-20T08:00:07.1814434+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/d490049a-191e-40bc-ac3a-6c6bf7fe2f9c/Country_Region.csv?snapshot=2022-05-20T08%3A00%3A07.1617630Z"}]},{"$type":"LocalEntity","name":"Territory","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Territory.csv"},"attributes":[{"name":"Territory Code","dataType":"string"},{"name":"Terrirtory Short Name","dataType":"string"},{"name":"Territory Description","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-05-20T08:00:08.9864303+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/d490049a-191e-40bc-ac3a-6c6bf7fe2f9c/Territory.csv?snapshot=2022-05-20T08%3A00%3A08.9127642Z"}]},{"$type":"LocalEntity","name":"Sourcing_Commodity","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Sourcing_Commodity.csv"},"attributes":[{"name":"CATEGORY_ID","dataType":"double"},{"name":"Sequence","dataType":"string"},{"name":"Commodity","dataType":"string"},{"name":"SCC UNSPSC Code","dataType":"string"},{"name":"Category Name","dataType":"string"},{"name":"STRUCTURE_NAME","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-05-20T08:00:09.4239272+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/d490049a-191e-40bc-ac3a-6c6bf7fe2f9c/Sourcing_Commodity.csv?snapshot=2022-05-20T08%3A00%3A09.4044839Z"}]},{"$type":"LocalEntity","name":"Supplier","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Supplier.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Supplier Number","dataType":"string"},{"name":"Supplier Name","dataType":"string"},{"name":"VENDOR_TYPE","dataType":"string"},{"name":"Supplier Name Alternate","dataType":"string"},{"name":"VENDOR_SITE_ID","dataType":"double"},{"name":"VENDOR_ID","dataType":"double"},{"name":"Supplier Site Code","dataType":"string"},{"name":"Supplier Site Code Alternate","dataType":"string"},{"name":"OPERATING_UNIT","dataType":"string"},{"name":"Production Supplier Flag","dataType":"string"},{"name":"Supplier Creation Date","dataType":"dateTime"},{"name":"Supplier Last Update Date","dataType":"dateTime"},{"name":"Pay Site Flag","dataType":"string"},{"name":"Purchasing Site Flag","dataType":"string"},{"name":"City","dataType":"string"},{"name":"Country","dataType":"string"},{"name":"Country of Origin","dataType":"string"},{"name":"Active Supplier Flag","dataType":"string"},{"name":"Inactive Date","dataType":"dateTime"},{"name":"Invoice Currency","dataType":"string"},{"name":"Payment Currency","dataType":"string"},{"name":"Payment Method","dataType":"string"},{"name":"Supplier Type","dataType":"string"},{"name":"Internal Supplier Flag","dataType":"string"},{"name":"ISupplier Forecast Flag","dataType":"string"},{"name":"FOB","dataType":"string"},{"name":"Freight Term","dataType":"string"},{"name":"Payment Term","dataType":"string"},{"name":"Supplier Class","dataType":"string"},{"name":"Supplier Commodity","dataType":"string"},{"name":"SSM Lead","dataType":"string"},{"name":"Master Supplier","dataType":"string"},{"name":"Key and Risk Flag","dataType":"string"},{"name":"KPI Required Flag","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-05-20T08:00:22.1600191+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/d490049a-191e-40bc-ac3a-6c6bf7fe2f9c/Supplier.csv?snapshot=2022-05-20T08%3A00%3A22.1442181Z"}]},{"$type":"LocalEntity","name":"Product_Category","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Product_Category.csv"},"attributes":[{"name":"CATEGORY_ID","dataType":"double"},{"name":"TBU","dataType":"string"},{"name":"Product Family","dataType":"string"},{"name":"Product Line","dataType":"string"},{"name":"Forecast Line","dataType":"string"},{"name":"Category Name","dataType":"string"},{"name":"STRUCTURE_NAME","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-05-20T08:00:13.5265014+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/d490049a-191e-40bc-ac3a-6c6bf7fe2f9c/Product_Category.csv?snapshot=2022-05-20T08%3A00%3A13.5081435Z"}]},{"$type":"LocalEntity","name":"Organization","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Organization.csv"},"attributes":[{"name":"Organization Code","dataType":"string"},{"name":"Organization Type","dataType":"string"},{"name":"Operating Unit","dataType":"string"},{"name":"Functional Currency","dataType":"string"},{"name":"Short Name","dataType":"string"},{"name":"Description","dataType":"string"},{"name":"ORGANIZATION_ID","dataType":"int64"},{"name":"SET_OF_BOOKS_ID","dataType":"int64"},{"name":"Org Country","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-05-20T08:00:09.5176836+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/d490049a-191e-40bc-ac3a-6c6bf7fe2f9c/Organization.csv?snapshot=2022-05-20T08%3A00%3A09.4544556Z"}]},{"$type":"LocalEntity","name":"Item","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Item.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Organization_Code","dataType":"string"},{"name":"ORGANIZATION_ID","dataType":"double"},{"name":"ITEM_KEY","dataType":"string"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"PLANNER_KEY","dataType":"string"},{"name":"Item Type","dataType":"string"},{"name":"Item Number","dataType":"string"},{"name":"MRP Planning Code","dataType":"string"},{"name":"Item Revision","dataType":"string"},{"name":"Item Description","dataType":"string"},{"name":"Item Primary Unit of Measure","dataType":"string"},{"name":"Item Status","dataType":"string"},{"name":"Inventory Item Flag","dataType":"string"},{"name":"Lot Control Code","dataType":"string"},{"name":"Serial Control Code","dataType":"string"},{"name":"Receipt Routing","dataType":"string"},{"name":"Default Buyer","dataType":"string"},{"name":"BUYER_ID","dataType":"int64"},{"name":"Item Make or Buy","dataType":"string"},{"name":"Planner Code","dataType":"string"},{"name":"Preprocessing Lead Time","dataType":"double"},{"name":"Processing Lead Time","dataType":"double"},{"name":"Post Processing Lead Time","dataType":"double"},{"name":"Lead Time Lot Size","dataType":"double"},{"name":"Fixed Lead Time","dataType":"double"},{"name":"Variable Lead Time","dataType":"double"},{"name":"List Price Per Unit","dataType":"double"},{"name":"Item Creation Date","dataType":"dateTime"},{"name":"Costing Enabled Flag","dataType":"string"},{"name":"Inventory Asset Flag","dataType":"string"},{"name":"Planning Time Fence","dataType":"string"},{"name":"Planning Time Fence Days","dataType":"double"},{"name":"Demand Time Fence","dataType":"string"},{"name":"Demand Time Fence Days","dataType":"double"},{"name":"Release Time Fence","dataType":"string"},{"name":"Release Time Fence Days","dataType":"double"},{"name":"Acceptable Early Days","dataType":"double"},{"name":"Fixed Days Supply","dataType":"double"},{"name":"Minimum Order Quantity","dataType":"double"},{"name":"Maximum Order Quantity","dataType":"double"},{"name":"Min Minmax Quantity","dataType":"double"},{"name":"Max Minmax Quantity","dataType":"double"},{"name":"Fixed Lot Multiplier","dataType":"double"},{"name":"Fixed Order Quantity","dataType":"double"},{"name":"Item Default Source Type","dataType":"string"},{"name":"Item Source Organization Code","dataType":"string"},{"name":"Critical Component Flag","dataType":"string"},{"name":"Inventory Planning Code","dataType":"string"},{"name":"WIP Supply Type","dataType":"string"},{"name":"Current Item ABC Class","dataType":"string"},{"name":"WIP Supply Subinventory","dataType":"string"},{"name":"WIP Supply Locator","dataType":"string"},{"name":"Supply Chain Status","dataType":"string"},{"name":"Org Product","dataType":"string"},{"name":"MAS Product","dataType":"string"},{"name":"Product Key","dataType":"string"},{"name":"PRODUCT_KEY_ID","dataType":"double"},{"name":"Sourcing Commodity","dataType":"string"},{"name":"Commodity","dataType":"string"},{"name":"Last PO Unit Price","dataType":"double"},{"name":"Last PO Unit Price USD (Budget)","dataType":"double"},{"name":"Last PO Currency","dataType":"string"},{"name":"APOP Classification","dataType":"string"},{"name":"Baseline Unit Price USD","dataType":"double"},{"name":"Last PO Supplier Name","dataType":"string"},{"name":"PO Project","dataType":"double"}],"partitions":[{"name":"Part001","refreshTime":"2022-05-20T08:04:56.2137456+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/d490049a-191e-40bc-ac3a-6c6bf7fe2f9c/Item.csv?snapshot=2022-05-20T08%3A04%3A56.1959634Z"}]},{"$type":"LocalEntity","name":"Buyer","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Buyer.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"BUYER_ID","dataType":"int64"},{"name":"Buyer Name","dataType":"string"},{"name":"PPV1 Approver","dataType":"string"},{"name":"PPV2 Approver","dataType":"string"},{"name":"Location","dataType":"string"},{"name":"Supervisor Name","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-05-20T08:00:13.6202741+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/d490049a-191e-40bc-ac3a-6c6bf7fe2f9c/Buyer.csv?snapshot=2022-05-20T08%3A00%3A13.5821012Z"}]},{"$type":"LocalEntity","name":"Planner","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Planner.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Organization Code","dataType":"string"},{"name":"PLANNER_KEY","dataType":"string"},{"name":"Planner Code","dataType":"string"},{"name":"Planner Description","dataType":"string"},{"name":"Disable Date","dataType":"dateTime"},{"name":"Planner Email Address","dataType":"string"},{"name":"Planner Name","dataType":"string"},{"name":"Index","dataType":"int64"}],"partitions":[{"name":"Part001","refreshTime":"2022-05-20T08:00:12.9796344+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/d490049a-191e-40bc-ac3a-6c6bf7fe2f9c/Planner.csv?snapshot=2022-05-20T08%3A00%3A12.9514611Z"}]},{"$type":"LocalEntity","name":"Corporate_Rate","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Corporate_Rate.csv"},"attributes":[{"name":"FROM_CURRENCY","dataType":"string"},{"name":"TO_CURRENCY","dataType":"string"},{"name":"CONVERSION_DATE","dataType":"dateTime"},{"name":"CONVERSION_TYPE","dataType":"string"},{"name":"USD_RATE","dataType":"double"}],"partitions":[{"name":"Part001","refreshTime":"2022-05-20T08:00:13.9796237+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/d490049a-191e-40bc-ac3a-6c6bf7fe2f9c/Corporate_Rate.csv?snapshot=2022-05-20T08%3A00%3A13.9269048Z"}]},{"$type":"LocalEntity","name":"Business_Segment","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Business_Segment.csv"},"attributes":[{"name":"BUSINESS_SEGMENT_ID","dataType":"double"},{"name":"BUSINESS_SEGMENT","dataType":"string"},{"name":"TBU","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-05-20T08:00:13.6671517+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/d490049a-191e-40bc-ac3a-6c6bf7fe2f9c/Business_Segment.csv?snapshot=2022-05-20T08%3A00%3A13.6100853Z"}]},{"$type":"LocalEntity","name":"Fiscal_Calendar","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Fiscal_Calendar.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Calendar Date","dataType":"dateTime"},{"name":"FC Year Start Date","dataType":"dateTime"},{"name":"FC Year","dataType":"int64"},{"name":"FC Quarter Start Date","dataType":"dateTime"},{"name":"FC Quarter","dataType":"string"},{"name":"FC Half","dataType":"string"},{"name":"FC Period Number","dataType":"int64"},{"name":"FC Period Month","dataType":"string"},{"name":"FC Period Name","dataType":"string"},{"name":"FC Period ID","dataType":"double"},{"name":"FC Quarter ID","dataType":"double"},{"name":"FC Week ID","dataType":"double"},{"name":"FC Year Offset","dataType":"double"},{"name":"FC Quarter Offset","dataType":"double"},{"name":"FC Period Offset","dataType":"double"},{"name":"Day of Year Number","dataType":"double"},{"name":"FC Day Offset","dataType":"double"},{"name":"FC Week","dataType":"string"},{"name":"FC Quarter Week","dataType":"string"},{"name":"FC Week Offset","dataType":"double"},{"name":"FC Week Series","dataType":"double"},{"name":"FC Week Number","dataType":"double"},{"name":"Day Name","dataType":"string"},{"name":"Day of Week Number","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-05-20T08:00:14.2764984+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/d490049a-191e-40bc-ac3a-6c6bf7fe2f9c/Fiscal_Calendar.csv?snapshot=2022-05-20T08%3A00%3A14.2397264Z"}]},{"$type":"LocalEntity","name":"Item_Type","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Item_Type.csv"},"attributes":[{"name":"Item Type Code","dataType":"string"},{"name":"Enabled Flag","dataType":"string"},{"name":"Tag","dataType":"string"},{"name":"Item Type","dataType":"string"},{"name":"Item Type Description","dataType":"string"},{"name":"END_DATE_ACTIVE","dataType":"dateTime"},{"name":"ATTRIBUTE13","dataType":"string"},{"name":"ATTRIBUTE2","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-05-20T08:00:13.0108862+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/d490049a-191e-40bc-ac3a-6c6bf7fe2f9c/Item_Type.csv?snapshot=2022-05-20T08%3A00%3A12.9774461Z"}]}]}