{"name":"Facts","description":"Receipt and consign transactions","version":"1.0","culture":"en-US","modifiedTime":"2021-01-21T02:06:52.4395121+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":true,"queriesMetadata":{"Receipt":{"queryId":"efe00557-9ea4-43c8-92cf-2ab2719ffd87","queryName":"Receipt","loadEnabled":true},"Consumption_Advice":{"queryId":"20e5ff9b-f071-43b6-9513-073b2c0efe9c","queryName":"Consumption_Advice","loadEnabled":true},"Planned_External_Buy":{"queryId":"40c13d7b-e49a-43b0-81b4-9fbb53723080","queryName":"Planned_External_Buy","loadEnabled":true}},"document":"section Section1;\r\nshared Receipt = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, \n  Query=\"\n  SELECT\n    sysdate extract_date,\n    mp.organization_code,\n    rsh.receipt_num,\n    rsl.line_num                                                          receipt_line_number,\n    msi.inventory_item_id item_id,\n    rsh.receipt_source_code, \n    rt.source_document_code,\n    rsh.freight_carrier_code,\n    rsh.expected_receipt_date,\n    rsh.waybill_airbill_num,\n    (\n        SELECT\n            routing_name\n        FROM\n            apps.rcv_routing_headers rrh\n        WHERE\n            rrh.routing_header_id = rt.routing_header_id\n    ) receipt_routing,\n    msi.segment1                                                          item_number,\n    rt.unit_of_measure                                                    receipt_unit_of_measure,\n    mp.organization_code\n    || '_'\n    || msi.segment1 item_key,\n    mp.organization_code\n    || '_'\n    || msi.planner_code planner_key,\n    nvl(pra.agent_id, pha.agent_id)           buyer_id,\n    pha.segment1                             po_number,\n    pra.release_num                          release_number,\n    rsh.shipment_num                                                      receipt_shipment_number,\n    pha.vendor_site_id,\n    rt.transaction_id,\n    rt.transaction_date,\n    rt.transaction_type,\n    rsl.item_description,\n    rt.currency_code,\n    pla.line_num                                                          po_line,\n    plla.shipment_num                                                     po_shipment,\n    nvl(br.rate_to_usd, 0)                    usd_budget_rate,\n    nvl(decode(plla.consigned_flag, 'Y', 'Yes', 'No'), 'No')              consigned_receipt,\n    CASE\n        WHEN rt.source_document_code = 'PO'\n             AND rt.po_release_id IS NULL THEN\n            (\n                SELECT\n                    pha.segment1\n                FROM\n                    po.po_headers_all pha\n                WHERE\n                        pha.po_header_id = rt.po_header_id\n                    AND ROWNUM = 1\n            )\n        WHEN rt.source_document_code = 'PO'\n             AND rt.po_release_id IS NOT NULL THEN\n            (\n                SELECT\n                    pha.segment1\n                    || '_'\n                    || pra.release_num\n                FROM\n                    po.po_headers_all     pha,\n                    po.po_releases_all    pra\n                WHERE\n                        pha.po_header_id = pra.po_header_id\n                    AND rt.po_header_id = pha.po_header_id\n                    AND rt.po_release_id = pra.po_release_id\n                    AND ROWNUM = 1\n            )\n        WHEN rt.source_document_code = 'REQ'    THEN\n            (\n                SELECT\n                    prha.segment1\n                FROM\n                    po.po_requisition_headers_all    prha,\n                    po.po_requisition_lines_all      prla\n                WHERE\n                        prha.requisition_header_id = prla.requisition_header_id\n                    AND prla.requisition_line_id = rt.requisition_line_id\n                    AND ROWNUM = 1\n            )\n        WHEN rt.source_document_code = 'RMA'    THEN\n            (\n                SELECT\n                    to_char(oeh.order_number)\n                FROM\n                    ont.oe_order_headers_all oeh\n                WHERE\n                        oeh.header_id = rt.oe_order_header_id\n                    AND ROWNUM = 1\n            )\n    END receipt_source_document,\n    CASE\n        WHEN rt.transaction_type in ('RETURN TO VENDOR','RETURN TO RECEIVING','RETURN TO CUSTOMER') THEN\n            rt.quantity * - 1\n        ELSE\n            rt.quantity\n    END receipt_quantity,\n    CASE\n        WHEN rt.transaction_type in ('RETURN TO VENDOR','RETURN TO RECEIVING','RETURN TO CUSTOMER') THEN\n            rt.primary_quantity * - 1\n        ELSE\n            rt.primary_quantity\n    END primary_quantity,\n    rt.po_unit_price,\n    rt.po_line_location_id,\n    rt.destination_type_code,\n    CASE\n        WHEN rt.source_document_code IN (\n            'REQ',\n            'RMA'\n        ) THEN\n            'INVENTORY'\n        ELSE\n            (\n                SELECT\n                    destination_type_code\n                FROM\n                    apps.po_distributions_all pda\n                WHERE\n                        pda.line_location_id = rt.po_line_location_id\n                    AND ROWNUM = 1\n            )\n    END destination_type,\n    nvl((\n        SELECT\n            nvl(rdv.technical_business_unit, 'Unassigned')\n            || '.'\n            || nvl(rdv.product_family, 'Unassigned')\n            || '.'\n            || nvl(rdv.product_line, 'Unassigned')\n            || '.'\n            || nvl(rdv.forecast_field, 'Unassigned')\n        FROM\n            apps.xxcoh_mp_receipt_dist_view rdv\n        WHERE\n                rdv.transaction_id = rt.transaction_id\n            AND ROWNUM = 1\n    ), 'Unassigned.Unassigned.Unassigned.Unassigned') mas_product,\n    nvl((\n        SELECT\n            nvl(rdv.org_technical_business_unit, 'Unassigned')\n            || '.'\n            || nvl(rdv.org_product_family, 'Unassigned')\n            || '.'\n            || nvl(rdv.org_product_line, 'Unassigned')\n            || '.'\n            || nvl(rdv.org_forecast_field, 'Unassigned')\n        FROM\n            apps.xxcoh_mp_receipt_dist_view rdv\n        WHERE\n                rdv.transaction_id = rt.transaction_id\n            AND ROWNUM = 1\n    ), 'Unassigned.Unassigned.Unassigned.Unassigned') org_product,\n    nvl((\n        SELECT\n            nvl(rdv.vendor_internal, 'N')\n        FROM\n            apps.xxcoh_mp_receipt_dist_view rdv\n        WHERE\n                rdv.transaction_id = rt.transaction_id\n            AND ROWNUM = 1\n    ), 'N') vendor_internal,\n    'RECEIPT'                                data_source,\nnvl((\n        SELECT\n            item_type\n        FROM\n            xxfacts.xx_porec_fact rf\n        WHERE\n                rf.transaction_id = rt.transaction_id\n            AND ROWNUM = 1\n    ),(\n        SELECT\n            meaning\n        FROM\n            apps.fnd_lookup_values flv\n        WHERE\n                flv.lookup_type = 'ITEM_TYPE'\n            AND flv.lookup_code = msi.item_type\n            AND language = 'US'\n    )) receipt_item_type,\n    (\n        SELECT\n            SUM(nvl(accounted_dr, 0) - nvl(accounted_cr, 0)) * - 1 net_accounted\n        FROM\n            apps.rcv_receiving_sub_ledger    rrsl,\n            apps.gl_code_combinations        gcc\n        WHERE\n                gcc.code_combination_id = rrsl.code_combination_id\n            AND gcc.segment3 = '20510'\n            AND rrsl.rcv_transaction_id = rt.transaction_id\n    ) ap_accrual,\n    CASE\n        WHEN plla.consigned_flag = 'Y' THEN\n            0\n        ELSE\n            (\n                SELECT\n                    nvl(mmt.actual_cost, 0)\n                FROM\n                    inv.mtl_material_transactions mmt\n                WHERE\n                        mmt.rcv_transaction_id = rt.transaction_id\n                    AND mmt.organization_id = rt.organization_id\n                    AND ROWNUM = 1\n            )\n    END actual_cost,\n    rt.rma_reference\nFROM\n    apps.rcv_transactions                rt,\n    apps.org_organization_definitions    mp,\n    inv.mtl_system_items_b               msi,\n    po.rcv_shipment_lines                rsl,\n    po.rcv_shipment_headers              rsh,\n    apps.po_headers_all                  pha,\n    apps.po_lines_all                    pla,\n    apps.po_line_locations_all           plla,\n    apps.po_releases_all                 pra,\n    xxdims.xx_budget_rate                br\nWHERE\n        mp.organization_id = rt.organization_id\n    AND rt.shipment_line_id = rsl.shipment_line_id\n    AND rt.shipment_header_id = rsh.shipment_header_id\n    AND rsh.shipment_header_id = rsl.shipment_header_id\n    AND rsh.ship_to_org_id = rt.organization_id\n    AND rt.organization_id = msi.organization_id\n    AND rsl.item_id = msi.inventory_item_id\n    AND pha.po_header_id = rt.po_header_id\n    AND pla.po_line_id = rt.po_line_id\n    AND plla.line_location_id = rt.po_line_location_id\n    AND rt.currency_code = br.currency_code (+)\n    AND pla.item_id > 0\n    AND nvl(plla.consigned_flag, 'N') = 'N'\n    AND rt.source_document_code = 'PO'\n    AND rt.po_release_id = pra.po_release_id (+)\n    /*filter by trx type as APOP calculation doesn't need to know the actual cost which generated during deliver transaction*/\n       AND rt.transaction_type IN (\n        'RECEIVE',\n        'CORRECT',\n        'RETURN TO VENDOR'\n    )\n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"EXTRACT_DATE\", \"Extract Date\"}, {\"CONSIGNED_RECEIPT\", \"Consigned Flag\"}, {\"ORGANIZATION_CODE\", \"Organization Code\"}, {\"RECEIPT_NUM\", \"Receipt Number\"}, {\"RECEIPT_LINE_NUMBER\", \"Line Number\"}, {\"ITEM_DESCRIPTION\", \"Item Description\"}, {\"RECEIPT_SOURCE_CODE\", \"Source Code\"}, {\"SOURCE_DOCUMENT_CODE\", \"Source Document\"}, {\"FREIGHT_CARRIER_CODE\", \"Freight Carrier\"}, {\"EXPECTED_RECEIPT_DATE\", \"Expected Date\"}, {\"RECEIPT_SHIPMENT_NUMBER\", \"Shipment Number\"}, {\"WAYBILL_AIRBILL_NUM\", \"Waybill\"}, {\"RECEIPT_SOURCE_DOCUMENT\", \"Source Document Number\"}, {\"ITEM_NUMBER\", \"Item Number\"}, {\"TRANSACTION_DATE\", \"Transaction Date\"}, {\"TRANSACTION_TYPE\", \"Transaction Type\"}, {\"CURRENCY_CODE\", \"Currency Code\"}, {\"PO_UNIT_PRICE\", \"PO Unit Price\"}, {\"RECEIPT_QUANTITY\", \"Quantity\"}, {\"PRIMARY_QUANTITY\", \"Primary Quantity\"}, {\"RECEIPT_UNIT_OF_MEASURE\", \"Unit of Measure\"}, {\"DESTINATION_TYPE_CODE\", \"Receipt Destination Type\"}, {\"ACTUAL_COST\", \"Actual Cost\"}, {\"RECEIPT_ROUTING\", \"Receipt Routing\"}, {\"DESTINATION_TYPE\", \"Destination Type\"}, {\"USD_BUDGET_RATE\", \"USD Budget Rate\"}, {\"PO_NUMBER\", \"PO Number\"}, {\"RELEASE_NUMBER\", \"Release Number\"}, {\"PO_LINE\", \"PO Line\"}, {\"PO_SHIPMENT\", \"PO Shipment\"}, {\"RMA_REFERENCE\", \"RMA Reference\"}, {\"RECEIPT_ITEM_TYPE\", \"Receipt Item Type\"}, {\"AP_ACCRUAL\", \"AP Accrual\"}}),\r\n  // Remove rows that do not have AP accrual to streamline the data extract\r\n  #\"Filtered only rows with AP accrual\" = Table.SelectRows(#\"Renamed columns\", each [AP Accrual] <> null)\r\nin\r\n  #\"Filtered only rows with AP accrual\";\r\nshared Consumption_Advice = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, \n  Query=\"\nSELECT\n    sysdate                           extract_date,\n    mp.organization_code,\n    mmt.transaction_id,\n    pha.vendor_id,\n    pha.vendor_site_id,\n    mp.organization_code||'_'||msi.segment1 item_key,\n    pla.item_id,\n    msi.segment1                      item_number,\n    msi.description                   item_description,\n    'VENDOR'                          source_code,\n    'PO'                              source_document,\n    'No'                              consigned_flag,\n    CASE\n        WHEN nvl(mct.consumption_release_id, 0) = 0        THEN\n            pha.segment1\n        WHEN nvl(mct.consumption_release_id, 0) > 0        THEN\n            pha.segment1\n            || '_'\n            || (\n                SELECT\n                    release_num\n                FROM\n                    apps.po_releases_all pra\n                WHERE\n                    pra.po_release_id = mct.consumption_release_id\n            )\n    END source_document_number,\n    mmt.transaction_date,\n    mmt.transaction_quantity * - 1    quantity,\n    uom.unit_of_measure,\n    mmt.primary_quantity * - 1        primary_quantity,\n    pda.line_location_id              po_line_location_id,\n    mct.po_distribution_id,\n    mtt.transaction_type_name         transaction_type,\n    'INVENTORY'                       destination_type,\n    pha.currency_code,\n    pla.line_num                      po_line,\n    (\n        SELECT\n            mmt2.actual_cost\n        FROM\n            apps.mtl_material_transactions mmt2\n        WHERE\n            mmt2.transaction_id = mmt.transfer_transaction_id\n    ) actual_cost,\n    plla.shipment_num                 po_shipment,\n    (\n        SELECT\n            rate_to_usd\n        FROM\n            xxdims.xx_budget_rate br\n        WHERE\n            br.currency_code = pha.currency_code\n    ) usd_budget_rate,\n    mct.blanket_price                 po_unit_price,\n    (\n        SELECT\n            meaning\n        FROM\n            apps.fnd_lookup_values flv\n        WHERE\n                flv.lookup_type = 'ITEM_TYPE'\n            AND flv.lookup_code = msi.item_type\n            AND language = 'US'\n    ) receipt_item_type,\n    (\n        SELECT\n            SUM(mta.base_transaction_value) * - 1\n        FROM\n            apps.mtl_transaction_accounts    mta,\n            apps.gl_code_combinations        gcc\n        WHERE\n                mta.reference_account = gcc.code_combination_id\n            AND gcc.segment3 = '20510'\n            AND mta.transaction_id = mmt.transfer_transaction_id\n            AND mta.organization_id = mmt.organization_id\n    ) ap_accrual,\n    mp.organization_code||'_'||msi.planner_code planner_key\nFROM\n    apps.mtl_consumption_transactions    mct,\n    apps.po_distributions_all            pda,\n    apps.po_lines_all                    pla,\n    apps.po_line_locations_all           plla,\n    apps.po_headers_all                  pha,\n    apps.mtl_material_transactions       mmt,\n    apps.mtl_parameters                  mp,\n    apps.mtl_transaction_types           mtt,\n    apps.mtl_system_items_b              msi,\n    apps.mtl_units_of_measure_vl         uom\nWHERE\n        mct.transaction_id = mmt.transaction_id\n    AND mct.organization_id = mp.organization_id\n    AND mmt.organization_id = mmt.organization_id\n    AND mct.po_distribution_id = pda.po_distribution_id\n    AND pda.po_line_id = pla.po_line_id\n    AND pda.po_header_id = pha.po_header_id\n    AND uom.uom_code = mmt.transaction_uom\n    AND plla.po_line_id = pla.po_line_id\n    AND pda.line_location_id = plla.line_location_id\n    AND mtt.transaction_type_id = mmt.transaction_type_id\n    AND msi.inventory_item_id = mmt.inventory_item_id\n    AND msi.organization_id = mmt.organization_id\n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"EXTRACT_DATE\", \"Extract Date\"}, {\"ORGANIZATION_CODE\", \"Organization Code\"}, {\"ITEM_NUMBER\", \"Item Number\"}, {\"ITEM_DESCRIPTION\", \"Item Description\"}, {\"SOURCE_CODE\", \"Source Code\"}, {\"SOURCE_DOCUMENT\", \"Source Document\"}, {\"SOURCE_DOCUMENT_NUMBER\", \"Source Document Number\"}, {\"UNIT_OF_MEASURE\", \"Unit of Measure\"}, {\"PRIMARY_QUANTITY\", \"Primary Quantity\"}, {\"TRANSACTION_TYPE\", \"Transaction Type\"}, {\"CURRENCY_CODE\", \"Currency Code\"}, {\"PO_UNIT_PRICE\", \"PO Unit Price\"}, {\"TRANSACTION_DATE\", \"Transaction Date\"}, {\"QUANTITY\", \"Quantity\"}, {\"USD_BUDGET_RATE\", \"USD Budget Rate\"}, {\"CONSIGNED_FLAG\", \"Consigned Flag\"}, {\"DESTINATION_TYPE\", \"Destination Type\"}, {\"PO_LINE\", \"PO Line\"}, {\"PO_SHIPMENT\", \"PO Shipment\"}, {\"ACTUAL_COST\", \"Actual Cost\"}, {\"RECEIPT_ITEM_TYPE\", \"Receipt Item Type\"}, {\"AP_ACCRUAL\", \"AP Accrual\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Planned_External_Buy = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, Query=\"\nSELECT\n    sdd.date_run,\n    sdd.plan_name,\n    mp.organization_code||'_'||sdd.item item_key,\n    sdd.firmed,\n    sdd.supply_or_demand,\n    sdd.inventory_item_id,\n    sdd.item,\n    sdd.description,\n    sdd.make_buy,\n    sdd.item_type,\n    sdd.plan_method,\n    sdd.active_or_inactive,\n    sdd.planner_code,\n    sdd.buyer_name,\n    CASE\n        WHEN source_org_supplier LIKE 'PRD:%' THEN\n            substr(sdd.source_org_supplier, 5, 3)\n        WHEN source_org_supplier IS NULL THEN\n            mp.organization_code\n        ELSE\n            sdd.source_org_supplier\n    END source_org_supplier,\n    sdd.calc_order_type,\n    sdd.mrp_lt,\n    sdd.active_supplier_lt,\n    sdd.full_supplier_lt,\n    sdd.order_number,\n    sdd.quantity_rate,\n    abs(sdd.quantity_rate) quantity,\n    sdd.po_line_location_id,\n    sdd.old_due_date,\n    sdd.old_dock_date,\n    CASE\n        WHEN sdd.sugg_dock_date <= sdd.date_run THEN\n            sdd.date_run\n        ELSE\n            sdd.sugg_dock_date\n    END sugg_dock_date,\n    CASE\n        WHEN sdd.sugg_due_date <= sdd.date_run THEN\n            sdd.date_run\n        ELSE\n            sdd.sugg_due_date\n    END sugg_due_date,\n    sdd.calc_receipt_date_adjusted,\n    CASE\n        WHEN sdd.action = 'Reschedule Out'\n             AND sdd.sugg_due_date <= sdd.date_run THEN\n            'Past Due'\n        ELSE\n            sdd.action\n    END recommended_action,\n    sdd.reschedule_days,\n    CASE\n        WHEN sdd.calc_order_type = 'Planned Order' THEN\n            sdd.compression_days\n        ELSE\n            0\n    END compression_days,\n    (\n        SELECT\n            pvs.vendor_site_id\n        FROM\n            apps.ap_suppliers                    pv,\n            apps.po_vendor_sites_all             pvs,\n            apps.org_organization_definitions    ood\n        WHERE\n                pvs.vendor_id = pv.vendor_id\n            AND pvs.vendor_site_code = sdd.source_vendor_site_code\n            AND pv.vendor_name = sdd.source_vendor_name\n            AND pvs.org_id = ood.operating_unit\n            AND ood.organization_id = mp.organization_id\n    ) vendor_site_id,\n    CASE\n        WHEN sdd.action = 'Release'\n             AND sdd.compression_days >= 1 THEN\n            'Compressed'\n        WHEN sdd.action = 'Reschedule Out'    THEN\n            CASE\n                WHEN (\n                    SELECT\n                        ( period_year * 4 ) + quarter_num\n                    FROM\n                        gl.gl_periods\n                    WHERE\n                        trunc(nvl(sugg_dock_date, sugg_due_date)) BETWEEN start_date AND end_date\n                        AND period_set_name = 'COHR Calendar'\n                ) > (\n                    SELECT\n                        ( period_year * 4 ) + quarter_num\n                    FROM\n                        gl.gl_periods\n                    WHERE\n                        trunc(sysdate) BETWEEN start_date AND end_date\n                        AND period_set_name = 'COHR Calendar'\n                )\n                     AND (\n                    SELECT\n                        ( period_year * 4 ) + quarter_num\n                    FROM\n                        gl.gl_periods\n                    WHERE\n                        trunc(nvl(old_dock_date, old_due_date)) BETWEEN start_date AND end_date\n                        AND period_set_name = 'COHR Calendar'\n                ) = (\n                    SELECT\n                        ( period_year * 4 ) + quarter_num\n                    FROM\n                        gl.gl_periods\n                    WHERE\n                        trunc(sysdate) BETWEEN start_date AND end_date\n                        AND period_set_name = 'COHR Calendar'\n                ) THEN\n                    'Reschedule Out of Current Quarter'\n                WHEN sdd.sugg_due_date <= sdd.date_run THEN\n                    'Past Due'\n                ELSE\n                    sdd.action\n            END\n        WHEN sdd.action = 'Cancel'            THEN\n            'Cancel'\n        WHEN sdd.action = 'Reschedule In'     THEN\n            CASE\n                WHEN (\n                    SELECT\n                        ( period_year * 4 ) + quarter_num\n                    FROM\n                        gl.gl_periods\n                    WHERE\n                        trunc(nvl(sugg_dock_date, sugg_due_date)) BETWEEN start_date AND end_date\n                        AND period_set_name = 'COHR Calendar'\n                ) = (\n                    SELECT\n                        ( period_year * 4 ) + quarter_num\n                    FROM\n                        gl.gl_periods\n                    WHERE\n                        trunc(date_run) BETWEEN start_date AND end_date\n                        AND period_set_name = 'COHR Calendar'\n                )\n                     AND (\n                    SELECT\n                        ( period_year * 4 ) + quarter_num\n                    FROM\n                        gl.gl_periods\n                    WHERE\n                        trunc(nvl(old_dock_date, old_due_date)) BETWEEN start_date AND end_date\n                        AND period_set_name = 'COHR Calendar'\n                ) > (\n                    SELECT\n                        ( period_year * 4 ) + quarter_num\n                    FROM\n                        gl.gl_periods\n                    WHERE\n                        trunc(date_run) BETWEEN start_date AND end_date\n                        AND period_set_name = 'COHR Calendar'\n                ) THEN\n                    'Reschedule Into Current Quarter'\n                ELSE\n                    sdd.action\n            END\n        ELSE\n            'Not Applicable'\n    END exception\nFROM\n    xxcoh.xxcoh_supply_demand_dmart    sdd,\n    apps.mtl_parameters                mp,\n    apps.mtl_system_items_b            msi\nWHERE\n        sdd.organization_id = mp.organization_id\n    AND sdd.inventory_item_id = msi.inventory_item_id\n    AND sdd.organization_id = msi.organization_id\n    and supply_or_demand = 'Supply'\nand make_buy = 'Buy'\nand plan_name = 'CHR_MRP'\nand calc_order_type not in 'Onhand'\nand source_organization_code is null\n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"DATE_RUN\", \"Date Run\"}, {\"PLAN_NAME\", \"Plan Name\"}, {\"FIRMED\", \"Firmed\"}, {\"SUPPLY_OR_DEMAND\", \"Supply or Demand\"}, {\"ITEM\", \"Item Number\"}, {\"DESCRIPTION\", \"Item Description\"}, {\"MAKE_BUY\", \"Make Or Buy\"}, {\"ITEM_TYPE\", \"Item Type\"}, {\"PLAN_METHOD\", \"Planning Method\"}, {\"ACTIVE_OR_INACTIVE\", \"Active or Inactive\"}, {\"PLANNER_CODE\", \"Planner Code\"}, {\"BUYER_NAME\", \"Buyer Name\"}, {\"SOURCE_ORG_SUPPLIER\", \"Source Org or Supplier\"}, {\"CALC_ORDER_TYPE\", \"Order Type\"}, {\"MRP_LT\", \"MRP LT\"}, {\"ACTIVE_SUPPLIER_LT\", \"Active Supplier LT\"}, {\"FULL_SUPPLIER_LT\", \"Full Supplier LT\"}, {\"QUANTITY_RATE\", \"Quantity Rate\"}, {\"QUANTITY\", \"Quantity\"}, {\"SUGG_DUE_DATE\", \"Suggested Due Date\"}, {\"OLD_DUE_DATE\", \"Old Due Date\"}, {\"OLD_DOCK_DATE\", \"Old Dock Date\"}, {\"CALC_RECEIPT_DATE_ADJUSTED\", \"Receipt Date Adjusted\"}, {\"SUGG_DOCK_DATE\", \"Suggested Dock Date\"}, {\"RECOMMENDED_ACTION\", \"Recommended Action\"}, {\"RESCHEDULE_DAYS\", \"Reschedule Days\"}, {\"ORDER_NUMBER\", \"Order Number\"}, {\"COMPRESSION_DAYS\", \"Compression Days\"}, {\"EXCEPTION\", \"Exception\"}})\r\nin\r\n  #\"Renamed columns\";\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"Receipt","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Receipt.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Organization Code","dataType":"string"},{"name":"Receipt Number","dataType":"string"},{"name":"Line Number","dataType":"double"},{"name":"ITEM_ID","dataType":"double"},{"name":"Source Code","dataType":"string"},{"name":"Source Document","dataType":"string"},{"name":"Freight Carrier","dataType":"string"},{"name":"Expected Date","dataType":"dateTime"},{"name":"Waybill","dataType":"string"},{"name":"Receipt Routing","dataType":"string"},{"name":"Item Number","dataType":"string"},{"name":"Unit of Measure","dataType":"string"},{"name":"ITEM_KEY","dataType":"string"},{"name":"PLANNER_KEY","dataType":"string"},{"name":"BUYER_ID","dataType":"double"},{"name":"PO Number","dataType":"string"},{"name":"Release Number","dataType":"double"},{"name":"Shipment Number","dataType":"string"},{"name":"VENDOR_SITE_ID","dataType":"double"},{"name":"TRANSACTION_ID","dataType":"double"},{"name":"Transaction Date","dataType":"dateTime"},{"name":"Transaction Type","dataType":"string"},{"name":"Item Description","dataType":"string"},{"name":"Currency Code","dataType":"string"},{"name":"PO Line","dataType":"double"},{"name":"PO Shipment","dataType":"double"},{"name":"USD Budget Rate","dataType":"double"},{"name":"Consigned Flag","dataType":"string"},{"name":"Source Document Number","dataType":"string"},{"name":"Quantity","dataType":"double"},{"name":"Primary Quantity","dataType":"double"},{"name":"PO Unit Price","dataType":"double"},{"name":"PO_LINE_LOCATION_ID","dataType":"double"},{"name":"Receipt Destination Type","dataType":"string"},{"name":"Destination Type","dataType":"string"},{"name":"MAS_PRODUCT","dataType":"string"},{"name":"ORG_PRODUCT","dataType":"string"},{"name":"VENDOR_INTERNAL","dataType":"string"},{"name":"DATA_SOURCE","dataType":"string"},{"name":"Receipt Item Type","dataType":"string"},{"name":"AP Accrual","dataType":"double"},{"name":"Actual Cost","dataType":"double"},{"name":"RMA Reference","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-12T11:16:32.1430263+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cc85e283-c215-41a4-9951-1ee7470a0718/Receipt.csv?snapshot=2022-06-12T11%3A16%3A32.1108594Z"}]},{"$type":"LocalEntity","name":"Consumption_Advice","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Consumption_Advice.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Organization Code","dataType":"string"},{"name":"TRANSACTION_ID","dataType":"double"},{"name":"VENDOR_ID","dataType":"double"},{"name":"VENDOR_SITE_ID","dataType":"double"},{"name":"ITEM_KEY","dataType":"string"},{"name":"ITEM_ID","dataType":"double"},{"name":"Item Number","dataType":"string"},{"name":"Item Description","dataType":"string"},{"name":"Source Code","dataType":"string"},{"name":"Source Document","dataType":"string"},{"name":"Consigned Flag","dataType":"string"},{"name":"Source Document Number","dataType":"string"},{"name":"Transaction Date","dataType":"dateTime"},{"name":"Quantity","dataType":"double"},{"name":"Unit of Measure","dataType":"string"},{"name":"Primary Quantity","dataType":"double"},{"name":"PO_LINE_LOCATION_ID","dataType":"double"},{"name":"PO_DISTRIBUTION_ID","dataType":"double"},{"name":"Transaction Type","dataType":"string"},{"name":"Destination Type","dataType":"string"},{"name":"Currency Code","dataType":"string"},{"name":"PO Line","dataType":"double"},{"name":"Actual Cost","dataType":"double"},{"name":"PO Shipment","dataType":"double"},{"name":"USD Budget Rate","dataType":"double"},{"name":"PO Unit Price","dataType":"double"},{"name":"Receipt Item Type","dataType":"string"},{"name":"AP Accrual","dataType":"double"},{"name":"PLANNER_KEY","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-12T11:01:18.7088044+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cc85e283-c215-41a4-9951-1ee7470a0718/Consumption_Advice.csv?snapshot=2022-06-12T11%3A01%3A18.4320188Z"}]},{"$type":"LocalEntity","name":"Planned_External_Buy","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Planned_External_Buy.csv"},"attributes":[{"name":"Date Run","dataType":"dateTime"},{"name":"Plan Name","dataType":"string"},{"name":"ITEM_KEY","dataType":"string"},{"name":"Firmed","dataType":"string"},{"name":"Supply or Demand","dataType":"string"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"Item Number","dataType":"string"},{"name":"Item Description","dataType":"string"},{"name":"Make Or Buy","dataType":"string"},{"name":"Item Type","dataType":"string"},{"name":"Planning Method","dataType":"string"},{"name":"Active or Inactive","dataType":"string"},{"name":"Planner Code","dataType":"string"},{"name":"Buyer Name","dataType":"string"},{"name":"Source Org or Supplier","dataType":"string"},{"name":"Order Type","dataType":"string"},{"name":"MRP LT","dataType":"double"},{"name":"Active Supplier LT","dataType":"double"},{"name":"Full Supplier LT","dataType":"double"},{"name":"Order Number","dataType":"string"},{"name":"Quantity Rate","dataType":"double"},{"name":"Quantity","dataType":"double"},{"name":"PO_LINE_LOCATION_ID","dataType":"double"},{"name":"Old Due Date","dataType":"dateTime"},{"name":"Old Dock Date","dataType":"dateTime"},{"name":"Suggested Dock Date","dataType":"dateTime"},{"name":"Suggested Due Date","dataType":"dateTime"},{"name":"Receipt Date Adjusted","dataType":"dateTime"},{"name":"Recommended Action","dataType":"string"},{"name":"Reschedule Days","dataType":"double"},{"name":"Compression Days","dataType":"double"},{"name":"VENDOR_SITE_ID","dataType":"double"},{"name":"Exception","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-12T11:02:21.6658294+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cc85e283-c215-41a4-9951-1ee7470a0718/Planned_External_Buy.csv?snapshot=2022-06-12T11%3A02%3A21.6389642Z"}]}]}