{"name":"WIP_BALANCES_ORACLE","description":"WIP_BALANCES_ORACLE","version":"1.0","culture":"en-US","modifiedTime":"2021-11-26T14:40:10.1509751+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"Data Update Info":{"queryId":"279582d2-306d-434e-9779-c6e5718c59cb","queryName":"Data Update Info","loadEnabled":true},"XXREP_WIP_BALANCES_V":{"queryId":"e67b60af-8d2a-4d96-a364-14f23462af64","queryName":"XXREP_WIP_BALANCES_V","loadEnabled":true},"RangeEnd":{"queryId":"889357f5-1976-43e2-b17d-9ec0cb77cc8b","queryName":"RangeEnd"},"RangeStart":{"queryId":"571cd9c7-f9e6-45f3-835c-cfb49d3bfa33","queryName":"RangeStart"}},"document":"section Section1;\r\n\r\nshared #\"Data Update Info\" = let\r\n    Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n    Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n    #\"Navigation 1\" = Navigation{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n    #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXREP_DATA_UPDATE_V\", Kind = \"View\"]}[Data],\r\n    #\"Filtered rows\" = Table.SelectRows(#\"Navigation 2\", each [TABLE_NAME] = \"WIP.WIP_PERIOD_BALANCES\")\r\nin\r\n    #\"Filtered rows\";\r\n\r\nshared XXREP_WIP_BALANCES_V = let\r\n    Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n    Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n    #\"Navigation 1\" = Navigation{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n    #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXREP_WIP_BALANCES_V\", Kind = \"View\"]}[Data],\r\n    #\"XXREP_WIP_BALANCES_V-504552494F445F53544152545F44415445-autogenerated_for_incremental_refresh\" = Table.SelectRows(#\"Navigation 2\", each DateTime.From([PERIOD_START_DATE]) >= RangeStart and DateTime.From([PERIOD_START_DATE]) < RangeEnd)\r\nin\r\n    #\"XXREP_WIP_BALANCES_V-504552494F445F53544152545F44415445-autogenerated_for_incremental_refresh\";\r\n\r\nshared RangeStart = let RangeStart = #datetime(0001,01,01,00,00,00) meta [IsParameterQuery=true, List={}, Type=\"DateTime\", IsParameterQueryRequired=true, Description=\"autogenerated_for_incremental_refresh\"] in RangeStart;\r\n\r\nshared RangeEnd = let RangeEnd = #datetime(9999,12,31,23,59,59) meta [IsParameterQuery=true, List={}, Type=\"DateTime\", IsParameterQueryRequired=true, Description=\"autogenerated_for_incremental_refresh\"] in RangeEnd;\r\n\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"Data Update Info","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Data%20Update%20Info.csv"},"attributes":[{"name":"TABLE_NAME","dataType":"string"},{"name":"DATA_UPDATE_DATE","dataType":"dateTime"},{"name":"DATA_UPDATE_DESC","dataType":"string"},{"name":"DATA_FLOW_REFRESH_DATE","dataType":"dateTime"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T05:01:33.8834631+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/5b2ceaf4-b7c9-4ae8-93af-b58a93bc57f9/Data%20Update%20Info.csv?snapshot=2022-06-13T05%3A01%3A32.2762515Z"}]},{"$type":"LocalEntity","name":"XXREP_WIP_BALANCES_V","description":"","pbi:refreshPolicy":{"$type":"IncrementalRefreshPolicy","locationPattern":"XXREP_WIP_BALANCES_V/part.csv","rollingWindowGranularity":"quarter","rollingWindowPeriods":24,"incrementalGranularity":"month","incrementalPeriods":2},"annotations":[{"name":"pbi:IncrementalRefreshDetectChangeAttribute"},{"name":"pbi:IncrementalRefreshFilterByAttribute","value":"PERIOD_START_DATE"}],"attributes":[{"name":"JOB_NUMBER","dataType":"string"},{"name":"WIP_JOB_DESCRIPTION","dataType":"string"},{"name":"ACCT_PERIOD_ID","dataType":"double"},{"name":"WIP_ENTITY_ID","dataType":"double"},{"name":"WIPJOB_ORG_KEY_CODE","dataType":"string"},{"name":"WIPJOB_ORG_KEY_ID","dataType":"string"},{"name":"ORGANIZATION_ID","dataType":"double"},{"name":"TL_RESOURCE_IN","dataType":"double"},{"name":"TL_OVERHEAD_IN","dataType":"double"},{"name":"TL_OUTSIDE_PROCESSING_IN","dataType":"double"},{"name":"PL_MATERIAL_IN","dataType":"double"},{"name":"PL_MATERIAL_OVERHEAD_IN","dataType":"double"},{"name":"PL_RESOURCE_IN","dataType":"double"},{"name":"PL_OVERHEAD_IN","dataType":"double"},{"name":"PL_OUTSIDE_PROCESSING_IN","dataType":"double"},{"name":"TL_MATERIAL_OUT","dataType":"double"},{"name":"TL_MATERIAL_OVERHEAD_OUT","dataType":"double"},{"name":"TL_RESOURCE_OUT","dataType":"double"},{"name":"TL_OVERHEAD_OUT","dataType":"double"},{"name":"TL_OUTSIDE_PROCESSING_OUT","dataType":"double"},{"name":"PL_MATERIAL_OUT","dataType":"double"},{"name":"PL_MATERIAL_OVERHEAD_OUT","dataType":"double"},{"name":"PL_RESOURCE_OUT","dataType":"double"},{"name":"PL_OVERHEAD_OUT","dataType":"double"},{"name":"PL_OUTSIDE_PROCESSING_OUT","dataType":"double"},{"name":"TL_MATERIAL_VAR","dataType":"double"},{"name":"TL_MATERIAL_OVERHEAD_VAR","dataType":"double"},{"name":"TL_RESOURCE_VAR","dataType":"double"},{"name":"TL_OUTSIDE_PROCESSING_VAR","dataType":"double"},{"name":"TL_OVERHEAD_VAR","dataType":"double"},{"name":"PL_MATERIAL_VAR","dataType":"double"},{"name":"PL_MATERIAL_OVERHEAD_VAR","dataType":"double"},{"name":"PL_RESOURCE_VAR","dataType":"double"},{"name":"PL_OVERHEAD_VAR","dataType":"double"},{"name":"PL_OUTSIDE_PROCESSING_VAR","dataType":"double"},{"name":"TL_SCRAP_IN","dataType":"double"},{"name":"TL_SCRAP_OUT","dataType":"double"},{"name":"TL_SCRAP_VAR","dataType":"double"},{"name":"PERIOD_NAME","dataType":"string"},{"name":"PERIOD_START_DATE","dataType":"dateTime"},{"name":"PERIOD_CLOSE_DATE","dataType":"dateTime"},{"name":"INVORG_CODE","dataType":"string"},{"name":"INVORG_ID","dataType":"double"},{"name":"LOCAL_EXTRACT_DATE","dataType":"dateTime"},{"name":"EXTRACT_DATE","dataType":"dateTime"},{"name":"DATA_UPDATE_DESC","dataType":"string"},{"name":"TIMEZONE","dataType":"string"}],"partitions":[{"name":"IncrementalRefreshPolicyPartition-2016Q2","refreshTime":"2021-08-24T04:24:39.0812701+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/5b2ceaf4-b7c9-4ae8-93af-b58a93bc57f9/XXREP_WIP_BALANCES_V/part-2016Q2.csv?snapshot=2021-08-24T04%3A24%3A36.7679467Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2016-04-01T00:00:00","end":"2016-07-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2016Q3","refreshTime":"2021-08-24T04:24:36.7161803+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/5b2ceaf4-b7c9-4ae8-93af-b58a93bc57f9/XXREP_WIP_BALANCES_V/part-2016Q3.csv?snapshot=2021-08-24T04%3A24%3A34.0571059Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2016-07-01T00:00:00","end":"2016-10-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2016Q4","refreshTime":"2021-08-24T04:24:44.3335428+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/5b2ceaf4-b7c9-4ae8-93af-b58a93bc57f9/XXREP_WIP_BALANCES_V/part-2016Q4.csv?snapshot=2021-08-24T04%3A24%3A41.7913593Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2016-10-01T00:00:00","end":"2017-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2017Q1","refreshTime":"2021-08-24T04:24:51.8962799+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/5b2ceaf4-b7c9-4ae8-93af-b58a93bc57f9/XXREP_WIP_BALANCES_V/part-2017Q1.csv?snapshot=2021-08-24T04%3A24%3A48.7901121Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2017-01-01T00:00:00","end":"2017-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2017Q2","refreshTime":"2021-08-24T04:25:07.4938794+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/5b2ceaf4-b7c9-4ae8-93af-b58a93bc57f9/XXREP_WIP_BALANCES_V/part-2017Q2.csv?snapshot=2021-08-24T04%3A25%3A04.3296584Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2017-04-01T00:00:00","end":"2017-07-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2017Q3","refreshTime":"2021-08-24T04:25:09.9522515+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/5b2ceaf4-b7c9-4ae8-93af-b58a93bc57f9/XXREP_WIP_BALANCES_V/part-2017Q3.csv?snapshot=2021-08-24T04%3A25%3A06.5751830Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2017-07-01T00:00:00","end":"2017-10-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2017Q4","refreshTime":"2021-08-24T04:25:28.4722935+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/5b2ceaf4-b7c9-4ae8-93af-b58a93bc57f9/XXREP_WIP_BALANCES_V/part-2017Q4.csv?snapshot=2021-08-24T04%3A25%3A23.3755933Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2017-10-01T00:00:00","end":"2018-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2018Q1","refreshTime":"2021-08-24T04:24:46.4313491+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/5b2ceaf4-b7c9-4ae8-93af-b58a93bc57f9/XXREP_WIP_BALANCES_V/part-2018Q1.csv?snapshot=2021-08-24T04%3A24%3A43.8137317Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2018-01-01T00:00:00","end":"2018-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2018Q2","refreshTime":"2021-08-24T04:24:49.0902836+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/5b2ceaf4-b7c9-4ae8-93af-b58a93bc57f9/XXREP_WIP_BALANCES_V/part-2018Q2.csv?snapshot=2021-08-24T04%3A24%3A45.2777257Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2018-04-01T00:00:00","end":"2018-07-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2018Q3","refreshTime":"2021-08-24T04:25:30.9168431+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/5b2ceaf4-b7c9-4ae8-93af-b58a93bc57f9/XXREP_WIP_BALANCES_V/part-2018Q3.csv?snapshot=2021-08-24T04%3A25%3A23.2605172Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2018-07-01T00:00:00","end":"2018-10-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2018Q4","refreshTime":"2021-08-24T04:25:27.3046573+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/5b2ceaf4-b7c9-4ae8-93af-b58a93bc57f9/XXREP_WIP_BALANCES_V/part-2018Q4.csv?snapshot=2021-08-24T04%3A25%3A23.6277641Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2018-10-01T00:00:00","end":"2019-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2019Q1","refreshTime":"2021-08-24T04:25:23.2833917+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/5b2ceaf4-b7c9-4ae8-93af-b58a93bc57f9/XXREP_WIP_BALANCES_V/part-2019Q1.csv?snapshot=2021-08-24T04%3A25%3A18.6293701Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2019-01-01T00:00:00","end":"2019-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2019Q2","refreshTime":"2021-08-24T04:25:16.4838744+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/5b2ceaf4-b7c9-4ae8-93af-b58a93bc57f9/XXREP_WIP_BALANCES_V/part-2019Q2.csv?snapshot=2021-08-24T04%3A25%3A13.1476467Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2019-04-01T00:00:00","end":"2019-07-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2019Q3","refreshTime":"2021-08-24T04:25:11.2066042+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/5b2ceaf4-b7c9-4ae8-93af-b58a93bc57f9/XXREP_WIP_BALANCES_V/part-2019Q3.csv?snapshot=2021-08-24T04%3A25%3A07.6759306Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2019-07-01T00:00:00","end":"2019-10-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2019Q4","refreshTime":"2021-08-24T04:25:12.300364+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/5b2ceaf4-b7c9-4ae8-93af-b58a93bc57f9/XXREP_WIP_BALANCES_V/part-2019Q4.csv?snapshot=2021-08-24T04%3A25%3A08.1532555Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2019-10-01T00:00:00","end":"2020-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2020Q1","refreshTime":"2021-08-24T04:23:48.1753725+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/5b2ceaf4-b7c9-4ae8-93af-b58a93bc57f9/XXREP_WIP_BALANCES_V/part-2020Q1.csv?snapshot=2021-08-24T04%3A23%3A44.7166022Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2020-01-01T00:00:00","end":"2020-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2020Q2","refreshTime":"2021-08-24T04:24:51.0838206+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/5b2ceaf4-b7c9-4ae8-93af-b58a93bc57f9/XXREP_WIP_BALANCES_V/part-2020Q2.csv?snapshot=2021-08-24T04%3A24%3A47.1519984Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2020-04-01T00:00:00","end":"2020-07-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2020Q3","refreshTime":"2021-08-24T04:25:26.2092921+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/5b2ceaf4-b7c9-4ae8-93af-b58a93bc57f9/XXREP_WIP_BALANCES_V/part-2020Q3.csv?snapshot=2021-08-24T04%3A25%3A22.3398901Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2020-07-01T00:00:00","end":"2020-10-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2020Q4","refreshTime":"2021-08-24T04:25:30.8856612+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/5b2ceaf4-b7c9-4ae8-93af-b58a93bc57f9/XXREP_WIP_BALANCES_V/part-2020Q4.csv?snapshot=2021-08-24T04%3A25%3A23.4046128Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2020-10-01T00:00:00","end":"2021-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2021Q1","refreshTime":"2021-08-24T04:25:27.8004543+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/5b2ceaf4-b7c9-4ae8-93af-b58a93bc57f9/XXREP_WIP_BALANCES_V/part-2021Q1.csv?snapshot=2021-08-24T04%3A25%3A23.4376368Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2021-01-01T00:00:00","end":"2021-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2021Q2","refreshTime":"2021-08-24T04:25:28.0504527+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/5b2ceaf4-b7c9-4ae8-93af-b58a93bc57f9/XXREP_WIP_BALANCES_V/part-2021Q2.csv?snapshot=2021-08-24T04%3A25%3A23.7208284Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2021-04-01T00:00:00","end":"2021-07-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2021Q3","refreshTime":"2021-11-01T12:31:13.4403047+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/5b2ceaf4-b7c9-4ae8-93af-b58a93bc57f9/XXREP_WIP_BALANCES_V/part-2021Q3.csv?snapshot=2021-11-02T05%3A01%3A22.6385968Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2021-07-01T00:00:00","end":"2021-10-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2021Q4","refreshTime":"2022-02-01T13:30:15.2773286+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/5b2ceaf4-b7c9-4ae8-93af-b58a93bc57f9/XXREP_WIP_BALANCES_V/part-2021Q4.csv?snapshot=2022-02-02T06%3A02%3A20.8246859Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2021-10-01T00:00:00","end":"2022-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q1","refreshTime":"2022-05-01T12:30:12.061382+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/5b2ceaf4-b7c9-4ae8-93af-b58a93bc57f9/XXREP_WIP_BALANCES_V/part-2022Q1.csv?snapshot=2022-05-02T05%3A01%3A59.2650288Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-01-01T00:00:00","end":"2022-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q204","refreshTime":"2022-06-01T12:31:11.5922441+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/5b2ceaf4-b7c9-4ae8-93af-b58a93bc57f9/XXREP_WIP_BALANCES_V/part-2022Q204.csv?snapshot=2022-06-01T12%3A31%3A06.6479392Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-01T00:00:00","end":"2022-05-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q205","refreshTime":"2022-06-13T05:07:03.0625446+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/5b2ceaf4-b7c9-4ae8-93af-b58a93bc57f9/XXREP_WIP_BALANCES_V/part-2022Q205.csv?snapshot=2022-06-13T05%3A06%3A54.2084605Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-05-01T00:00:00","end":"2022-06-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q206","refreshTime":"2022-06-13T05:01:34.2897161+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/5b2ceaf4-b7c9-4ae8-93af-b58a93bc57f9/XXREP_WIP_BALANCES_V/part-2022Q206.csv?snapshot=2022-06-13T05%3A01%3A32.5021115Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-06-01T00:00:00","end":"2022-07-01T00:00:00"}}]}]}