{"name":"GL_DRILL_TRANS","description":"GL Drill Down Transactions ( refreshed weekly on Sunday)","version":"1.0","culture":"en-US","modifiedTime":"2021-07-06T06:22:03.9095868+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"XX_GL_DRILL_TRANS_VIEW":{"queryId":"0b993609-e19f-4388-a84a-9be447289d24","queryName":"XX_GL_DRILL_TRANS_VIEW","loadEnabled":true},"RangeEnd":{"queryId":"3d598e5e-69f5-4259-8251-a2451bc5fe6e","queryName":"RangeEnd"},"RangeStart":{"queryId":"204ac904-1b20-45a9-8038-81733a7c3802","queryName":"RangeStart"}},"document":"section Section1;\r\n\r\nshared XX_GL_DRILL_TRANS_VIEW = let\r\n    Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n    Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n    #\"Navigation 1\" = Navigation{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n    #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XX_GL_DRILL_TRANS_VIEW\", Kind = \"View\"]}[Data],\r\n    #\"Renamed columns\" = Table.RenameColumns(#\"Navigation 2\", {{\"SEGMENT1\", \"Entity Code\"}, {\"SEGMENT3\", \"Account Code\"}, {\"PERIOD_NAME\", \"GL Period\"}}),\r\n    #\"XX_GL_DRILL_TRANS_VIEW-504552494F445F454E445F44415445-autogenerated_for_incremental_refresh\" = Table.SelectRows(#\"Renamed columns\", each DateTime.From([PERIOD_END_DATE]) >= RangeStart and DateTime.From([PERIOD_END_DATE]) < RangeEnd)\r\nin\r\n    #\"XX_GL_DRILL_TRANS_VIEW-504552494F445F454E445F44415445-autogenerated_for_incremental_refresh\";\r\n\r\nshared RangeStart = let RangeStart = #datetime(0001,01,01,00,00,00) meta [IsParameterQuery=true, List={}, Type=\"DateTime\", IsParameterQueryRequired=true, Description=\"autogenerated_for_incremental_refresh\"] in RangeStart;\r\n\r\nshared RangeEnd = let RangeEnd = #datetime(9999,12,31,23,59,59) meta [IsParameterQuery=true, List={}, Type=\"DateTime\", IsParameterQueryRequired=true, Description=\"autogenerated_for_incremental_refresh\"] in RangeEnd;\r\n\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"XX_GL_DRILL_TRANS_VIEW","description":"","pbi:refreshPolicy":{"$type":"IncrementalRefreshPolicy","locationPattern":"XX_GL_DRILL_TRANS_VIEW/part.csv","rollingWindowGranularity":"year","rollingWindowPeriods":4,"incrementalGranularity":"day","incrementalPeriods":45},"annotations":[{"name":"pbi:IncrementalRefreshDetectChangeAttribute"},{"name":"pbi:IncrementalRefreshFilterByAttribute","value":"PERIOD_END_DATE"}],"attributes":[{"name":"GL_DATE","dataType":"dateTime"},{"name":"GL_TRANSFER_DATE","dataType":"dateTime"},{"name":"TRANSACTION_NUMBER","dataType":"string"},{"name":"ENTITY_TYPE_CODE","dataType":"string"},{"name":"ENTITY_ID","dataType":"double"},{"name":"TRX_HDR_ID","dataType":"double"},{"name":"ORG_ID","dataType":"double"},{"name":"EVENT_ID","dataType":"double"},{"name":"EVENT_DATE","dataType":"dateTime"},{"name":"EVENT_NUMBER","dataType":"double"},{"name":"TRANSACTION_DATE","dataType":"dateTime"},{"name":"APPLICATION_ID","dataType":"double"},{"name":"AE_HEADER_ID","dataType":"double"},{"name":"HEADER_DESCRIPTION","dataType":"string"},{"name":"GL_TRANSFER_STATUS_CODE","dataType":"string"},{"name":"JE_CATEGORY_NAME","dataType":"string"},{"name":"JE_SOURCE_NAME","dataType":"string"},{"name":"EVENT_CLASS_CODE","dataType":"string"},{"name":"EVENT_TYPE_CODE","dataType":"string"},{"name":"JE_BATCH_ID","dataType":"double"},{"name":"WTA_BATCH_ID","dataType":"double"},{"name":"GL_SL_LINK_TABLE","dataType":"string"},{"name":"GL_BATCH_NAME","dataType":"string"},{"name":"POSTED_DATE","dataType":"dateTime"},{"name":"GL_JE_NAME","dataType":"string"},{"name":"EXTERNAL_REFERENCE","dataType":"string"},{"name":"GL_LINE_NUMBER","dataType":"double"},{"name":"AE_LINE_NUMBER","dataType":"double"},{"name":"DISPLAYED_LINE_NUMBER","dataType":"double"},{"name":"LINE_DESCRIPTION","dataType":"string"},{"name":"ENTERED_CURRENCY","dataType":"string"},{"name":"CONVERSION_RATE","dataType":"double"},{"name":"CONVERSION_RATE_DATE","dataType":"dateTime"},{"name":"CONVERSION_RATE_TYPE_CODE","dataType":"string"},{"name":"ENTERED_DR","dataType":"double"},{"name":"ENTERED_CR","dataType":"double"},{"name":"ACCOUNTED_DR","dataType":"double"},{"name":"ACCOUNTED_CR","dataType":"double"},{"name":"ACCOUNTED_NET","dataType":"double"},{"name":"TRX_DISTRIBUTION_ID","dataType":"double"},{"name":"TRX_DISTRIBUTION_TYPE","dataType":"string"},{"name":"JE_HEADER_ID","dataType":"double"},{"name":"LEDGER_ID","dataType":"double"},{"name":"JE_CATEGORY","dataType":"string"},{"name":"JE_SOURCE","dataType":"string"},{"name":"LEDGER_NAME","dataType":"string"},{"name":"LEDGER_CURRENCY","dataType":"string"},{"name":"PERIOD_YEAR","dataType":"double"},{"name":"GL Period","dataType":"string"},{"name":"CODE_COMBINATION_ID","dataType":"double"},{"name":"ACCOUNT","dataType":"string"},{"name":"Entity Code","dataType":"string"},{"name":"SEGMENT2","dataType":"string"},{"name":"Account Code","dataType":"string"},{"name":"SEGMENT4","dataType":"string"},{"name":"SEGMENT5","dataType":"string"},{"name":"SEGMENT6","dataType":"string"},{"name":"TRAN_SOURCE","dataType":"string"},{"name":"ACCT_LINE_TYPE","dataType":"string"},{"name":"ACCT_LINE_TYPE_NAME","dataType":"string"},{"name":"PO_ORDER_NUMBER","dataType":"string"},{"name":"PO_ORDER_RELEASE_NUM","dataType":"string"},{"name":"RCV_RECEIPT_NUM","dataType":"string"},{"name":"AE_LINE_REFERENCE","dataType":"string"},{"name":"TAX_CODE","dataType":"string"},{"name":"BANK_ACCOUNT_NAME","dataType":"string"},{"name":"SOURCE_ID","dataType":"double"},{"name":"SOURCE_TABLE","dataType":"string"},{"name":"AEL_TABLE","dataType":"string"},{"name":"DOC_SEQUENCE_ID","dataType":"double"},{"name":"DOC_SEQUENCE_NAME","dataType":"string"},{"name":"DOC_SEQUENCE_VALUE","dataType":"double"},{"name":"TRX_HDR_TABLE","dataType":"string"},{"name":"TRX_HDR_CURRENCY","dataType":"string"},{"name":"TRX_CLASS","dataType":"string"},{"name":"TRX_DATE","dataType":"dateTime"},{"name":"TRX_TYPE_C","dataType":"string"},{"name":"TRX_TYPE_NAME","dataType":"string"},{"name":"TRX_CLASS_NAME","dataType":"string"},{"name":"TRX_NUMBER_DISPLAYED","dataType":"string"},{"name":"TRX_LINE_NUMBER","dataType":"double"},{"name":"TRX_LINE_TYPE","dataType":"string"},{"name":"TRX_LINE_TYPE_NAME","dataType":"string"},{"name":"INV_ORG_CODE","dataType":"string"},{"name":"TRAN_DESC1","dataType":"string"},{"name":"TRAN_DESC2","dataType":"string"},{"name":"TRAN_DESC3","dataType":"string"},{"name":"TRAN_DESC4","dataType":"string"},{"name":"TRAN_DESC5","dataType":"string"},{"name":"TRAN_DESC6","dataType":"string"},{"name":"PO_LINE_NUM","dataType":"double"},{"name":"PO_LINE_DESCRIPTION","dataType":"string"},{"name":"AP_INVOICE_NUMBER","dataType":"string"},{"name":"VENDOR_NAME","dataType":"string"},{"name":"VAT_REGISTRATION_NUM","dataType":"string"},{"name":"VOUCH_NO","dataType":"double"},{"name":"LINKURL_VOUCH_NO","dataType":"string"},{"name":"QUANTITY","dataType":"double"},{"name":"QUERY_REF","dataType":"string"},{"name":"LOCAL_GAP_ENTITY","dataType":"string"},{"name":"PERIOD_END_CONV_RATE","dataType":"double"},{"name":"ROW_CREATION_DATE","dataType":"dateTime"},{"name":"ACCOUNTED_NET_USD","dataType":"double"},{"name":"USD_CONV_RATE","dataType":"double"},{"name":"PERIOD_START_DATE","dataType":"dateTime"},{"name":"PERIOD_END_DATE","dataType":"dateTime"},{"name":"QUARTER_START_DATE","dataType":"dateTime"},{"name":"QUARTER_END_DATE","dataType":"dateTime"},{"name":"YEAR_START_DATE","dataType":"dateTime"},{"name":"YEAR_END_DATE","dataType":"dateTime"},{"name":"FISCAL_YEAR","dataType":"string"},{"name":"QUARTER_NUM","dataType":"double"},{"name":"FISCAL_QUARTER","dataType":"string"},{"name":"FYFQ","dataType":"string"},{"name":"EXPENSE_DETAIL_KEY","dataType":"string"},{"name":"GLCCID_DETAIL_KEY","dataType":"string"},{"name":"GL_ENTITY_ACC_DETAIL_KEY","dataType":"string"}],"partitions":[{"name":"IncrementalRefreshPolicyPartition-2018","refreshTime":"2021-07-06T06:43:51.6980098+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2018.csv?snapshot=2021-07-06T06%3A43%3A51.4204902Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2018-01-01T00:00:00","end":"2019-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2019","refreshTime":"2021-07-06T07:31:19.8251174+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2019.csv?snapshot=2021-07-06T07%3A26%3A33.9761979Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2019-01-01T00:00:00","end":"2020-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2020","refreshTime":"2021-07-06T08:30:10.1053465+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2020.csv?snapshot=2021-07-06T08%3A21%3A34.4147331Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2020-01-01T00:00:00","end":"2021-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2021","refreshTime":"2022-02-20T19:00:54.0317127+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2021.csv?snapshot=2022-02-27T19%3A48%3A53.4494473Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2021-01-01T00:00:00","end":"2022-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q1","refreshTime":"2022-05-15T18:00:59.4011008+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q1.csv?snapshot=2022-05-22T18%3A15%3A09.5246838Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-01-01T00:00:00","end":"2022-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20401","refreshTime":"2022-05-22T18:01:28.4488136+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20401.csv?snapshot=2022-05-22T18%3A01%3A28.1370206Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-01T00:00:00","end":"2022-04-02T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20402","refreshTime":"2022-05-22T18:27:19.6886197+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20402.csv?snapshot=2022-05-22T18%3A24%3A07.6054125Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-02T00:00:00","end":"2022-04-03T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20403","refreshTime":"2022-05-22T18:01:36.8314661+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20403.csv?snapshot=2022-05-22T18%3A01%3A36.0774511Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-03T00:00:00","end":"2022-04-04T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20404","refreshTime":"2022-05-22T18:01:39.5773669+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20404.csv?snapshot=2022-05-22T18%3A01%3A37.6475480Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-04T00:00:00","end":"2022-04-05T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20405","refreshTime":"2022-05-22T18:01:49.9115901+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20405.csv?snapshot=2022-05-22T18%3A01%3A49.6056669Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-05T00:00:00","end":"2022-04-06T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20406","refreshTime":"2022-05-22T18:01:36.4720869+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20406.csv?snapshot=2022-05-22T18%3A01%3A36.0294785Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-06T00:00:00","end":"2022-04-07T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20407","refreshTime":"2022-05-22T18:01:37.909587+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20407.csv?snapshot=2022-05-22T18%3A01%3A36.7190822Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-07T00:00:00","end":"2022-04-08T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20408","refreshTime":"2022-05-29T18:00:24.0388849+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20408.csv?snapshot=2022-05-29T18%3A00%3A23.6921718Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-08T00:00:00","end":"2022-04-09T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20409","refreshTime":"2022-05-29T18:00:24.1168855+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20409.csv?snapshot=2022-05-29T18%3A00%3A23.7181567Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-09T00:00:00","end":"2022-04-10T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20410","refreshTime":"2022-05-29T18:00:21.0049295+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20410.csv?snapshot=2022-05-29T18%3A00%3A19.9702819Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-10T00:00:00","end":"2022-04-11T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20411","refreshTime":"2022-05-29T18:00:21.238937+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20411.csv?snapshot=2022-05-29T18%3A00%3A19.8153700Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-11T00:00:00","end":"2022-04-12T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20412","refreshTime":"2022-05-29T18:00:26.8371261+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20412.csv?snapshot=2022-05-29T18%3A00%3A26.5725389Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-12T00:00:00","end":"2022-04-13T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20413","refreshTime":"2022-05-29T18:00:32.8576683+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20413.csv?snapshot=2022-05-29T18%3A00%3A32.3522627Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-13T00:00:00","end":"2022-04-14T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20414","refreshTime":"2022-05-29T18:00:33.0607925+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20414.csv?snapshot=2022-05-29T18%3A00%3A32.6400990Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-14T00:00:00","end":"2022-04-15T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20415","refreshTime":"2022-06-05T18:03:26.6876442+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20415.csv?snapshot=2022-06-05T18%3A03%3A26.3557167Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-15T00:00:00","end":"2022-04-16T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20416","refreshTime":"2022-06-05T18:03:27.0783275+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20416.csv?snapshot=2022-06-05T18%3A03%3A26.4766468Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-16T00:00:00","end":"2022-04-17T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20417","refreshTime":"2022-06-05T18:03:11.692712+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20417.csv?snapshot=2022-06-05T18%3A03%3A11.5563367Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-17T00:00:00","end":"2022-04-18T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20418","refreshTime":"2022-06-05T18:03:19.2873529+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20418.csv?snapshot=2022-06-05T18%3A03%3A19.0149911Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-18T00:00:00","end":"2022-04-19T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20419","refreshTime":"2022-06-05T18:03:19.0997958+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20419.csv?snapshot=2022-06-05T18%3A03%3A18.9020571Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-19T00:00:00","end":"2022-04-20T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20420","refreshTime":"2022-06-05T18:03:15.4017086+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20420.csv?snapshot=2022-06-05T18%3A03%3A15.1262566Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-20T00:00:00","end":"2022-04-21T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20421","refreshTime":"2022-06-05T18:04:09.9469133+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20421.csv?snapshot=2022-06-05T18%3A04%3A09.4926224Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-21T00:00:00","end":"2022-04-22T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20422","refreshTime":"2022-06-12T18:00:43.2896077+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20422.csv?snapshot=2022-06-12T18%3A00%3A42.3744466Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-22T00:00:00","end":"2022-04-23T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20423","refreshTime":"2022-06-12T18:00:28.0012051+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20423.csv?snapshot=2022-06-12T18%3A00%3A23.3634668Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-23T00:00:00","end":"2022-04-24T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20424","refreshTime":"2022-06-12T18:00:29.4230881+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20424.csv?snapshot=2022-06-12T18%3A00%3A23.7022702Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-24T00:00:00","end":"2022-04-25T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20425","refreshTime":"2022-06-12T18:00:30.8450196+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20425.csv?snapshot=2022-06-12T18%3A00%3A24.1000400Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-25T00:00:00","end":"2022-04-26T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20426","refreshTime":"2022-06-12T18:00:25.1886801+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20426.csv?snapshot=2022-06-12T18%3A00%3A23.6013282Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-26T00:00:00","end":"2022-04-27T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20427","refreshTime":"2022-06-12T18:00:40.1645517+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20427.csv?snapshot=2022-06-12T18%3A00%3A35.3185369Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-27T00:00:00","end":"2022-04-28T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20428","refreshTime":"2022-06-12T18:00:35.7323893+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20428.csv?snapshot=2022-06-12T18%3A00%3A30.9730552Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-28T00:00:00","end":"2022-04-29T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20429","refreshTime":"2022-06-12T18:00:35.2636332+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20429.csv?snapshot=2022-06-12T18%3A00%3A30.6612367Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-29T00:00:00","end":"2022-04-30T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20430","refreshTime":"2022-06-12T18:19:41.7288949+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20430.csv?snapshot=2022-06-12T18%3A17%3A21.8749989Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-30T00:00:00","end":"2022-05-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20501","refreshTime":"2022-06-12T18:00:27.4230667+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20501.csv?snapshot=2022-06-12T18%3A00%3A23.3494750Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-05-01T00:00:00","end":"2022-05-02T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20502","refreshTime":"2022-06-12T18:00:30.2980916+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20502.csv?snapshot=2022-06-12T18%3A00%3A23.2465349Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-05-02T00:00:00","end":"2022-05-03T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20503","refreshTime":"2022-06-12T18:00:26.9230649+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20503.csv?snapshot=2022-06-12T18%3A00%3A23.5993302Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-05-03T00:00:00","end":"2022-05-04T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20504","refreshTime":"2022-06-12T18:00:25.6574329+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20504.csv?snapshot=2022-06-12T18%3A00%3A23.5523575Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-05-04T00:00:00","end":"2022-05-05T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20505","refreshTime":"2022-06-12T18:00:35.4518671+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20505.csv?snapshot=2022-06-12T18%3A00%3A30.4733451Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-05-05T00:00:00","end":"2022-05-06T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20506","refreshTime":"2022-06-12T18:00:34.1542474+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20506.csv?snapshot=2022-06-12T18%3A00%3A29.9176670Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-05-06T00:00:00","end":"2022-05-07T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20507","refreshTime":"2022-06-12T18:00:38.593272+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20507.csv?snapshot=2022-06-12T18%3A00%3A32.1973464Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-05-07T00:00:00","end":"2022-05-08T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20508","refreshTime":"2022-06-12T18:00:38.9301409+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20508.csv?snapshot=2022-06-12T18%3A00%3A32.0484317Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-05-08T00:00:00","end":"2022-05-09T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20509","refreshTime":"2022-06-12T18:00:31.6106374+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20509.csv?snapshot=2022-06-12T18%3A00%3A25.0085133Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-05-09T00:00:00","end":"2022-05-10T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20510","refreshTime":"2022-06-12T18:00:39.1489026+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20510.csv?snapshot=2022-06-12T18%3A00%3A32.7450289Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-05-10T00:00:00","end":"2022-05-11T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20511","refreshTime":"2022-06-12T18:00:37.2651396+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20511.csv?snapshot=2022-06-12T18%3A00%3A32.0484317Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-05-11T00:00:00","end":"2022-05-12T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20512","refreshTime":"2022-06-12T18:00:32.6262449+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20512.csv?snapshot=2022-06-12T18%3A00%3A26.2947677Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-05-12T00:00:00","end":"2022-05-13T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20513","refreshTime":"2022-06-12T18:00:32.1106218+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20513.csv?snapshot=2022-06-12T18%3A00%3A26.0459115Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-05-13T00:00:00","end":"2022-05-14T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20514","refreshTime":"2022-06-12T18:00:32.8762478+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20514.csv?snapshot=2022-06-12T18%3A00%3A28.6623947Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-05-14T00:00:00","end":"2022-05-15T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20515","refreshTime":"2022-06-12T18:00:36.216752+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20515.csv?snapshot=2022-06-12T18%3A00%3A31.7196229Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-05-15T00:00:00","end":"2022-05-16T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20516","refreshTime":"2022-06-12T18:00:33.1418812+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20516.csv?snapshot=2022-06-12T18%3A00%3A28.5924357Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-05-16T00:00:00","end":"2022-05-17T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20517","refreshTime":"2022-06-12T18:00:34.7167433+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20517.csv?snapshot=2022-06-12T18%3A00%3A29.7487652Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-05-17T00:00:00","end":"2022-05-18T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20518","refreshTime":"2022-06-12T18:00:34.9979996+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20518.csv?snapshot=2022-06-12T18%3A00%3A30.7232001Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-05-18T00:00:00","end":"2022-05-19T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20519","refreshTime":"2022-06-12T18:00:33.532505+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20519.csv?snapshot=2022-06-12T18%3A00%3A29.8327168Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-05-19T00:00:00","end":"2022-05-20T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20520","refreshTime":"2022-06-12T18:00:38.1870176+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20520.csv?snapshot=2022-06-12T18%3A00%3A32.1623662Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-05-20T00:00:00","end":"2022-05-21T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20521","refreshTime":"2022-06-12T18:00:39.5864121+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20521.csv?snapshot=2022-06-12T18%3A00%3A33.2547330Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-05-21T00:00:00","end":"2022-05-22T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20522","refreshTime":"2022-06-12T18:00:39.8832865+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20522.csv?snapshot=2022-06-12T18%3A00%3A34.9327607Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-05-22T00:00:00","end":"2022-05-23T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20523","refreshTime":"2022-06-12T18:00:39.742657+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20523.csv?snapshot=2022-06-12T18%3A00%3A34.3780822Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-05-23T00:00:00","end":"2022-05-24T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20524","refreshTime":"2022-06-12T18:00:40.3676643+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20524.csv?snapshot=2022-06-12T18%3A00%3A35.4344695Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-05-24T00:00:00","end":"2022-05-25T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20525","refreshTime":"2022-06-12T18:00:40.6176621+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20525.csv?snapshot=2022-06-12T18%3A00%3A36.0591077Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-05-25T00:00:00","end":"2022-05-26T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20526","refreshTime":"2022-06-12T18:00:40.836399+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20526.csv?snapshot=2022-06-12T18%3A00%3A36.2539947Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-05-26T00:00:00","end":"2022-05-27T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20527","refreshTime":"2022-06-12T18:00:40.9301986+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20527.csv?snapshot=2022-06-12T18%3A00%3A36.7237229Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-05-27T00:00:00","end":"2022-05-28T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20528","refreshTime":"2022-06-12T18:19:43.3703928+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20528.csv?snapshot=2022-06-12T18%3A17%3A22.4906413Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-05-28T00:00:00","end":"2022-05-29T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20529","refreshTime":"2022-06-12T18:00:37.7182757+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20529.csv?snapshot=2022-06-12T18%3A00%3A32.3422630Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-05-29T00:00:00","end":"2022-05-30T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20530","refreshTime":"2022-06-12T18:00:41.0551767+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20530.csv?snapshot=2022-06-12T18%3A00%3A38.0349619Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-05-30T00:00:00","end":"2022-05-31T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20531","refreshTime":"2022-06-12T18:00:41.2895602+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20531.csv?snapshot=2022-06-12T18%3A00%3A38.3207965Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-05-31T00:00:00","end":"2022-06-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20601","refreshTime":"2022-06-12T18:00:39.3832791+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20601.csv?snapshot=2022-06-12T18%3A00%3A33.3107003Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-06-01T00:00:00","end":"2022-06-02T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20602","refreshTime":"2022-06-12T18:00:43.4770558+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20602.csv?snapshot=2022-06-12T18%3A00%3A42.7112513Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-06-02T00:00:00","end":"2022-06-03T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20603","refreshTime":"2022-06-12T18:00:42.8520833+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20603.csv?snapshot=2022-06-12T18%3A00%3A41.9606860Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-06-03T00:00:00","end":"2022-06-04T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20604","refreshTime":"2022-06-12T18:00:36.8745022+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20604.csv?snapshot=2022-06-12T18%3A00%3A31.8295586Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-06-04T00:00:00","end":"2022-06-05T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20605","refreshTime":"2022-06-12T18:00:41.4770484+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20605.csv?snapshot=2022-06-12T18%3A00%3A38.4567174Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-06-05T00:00:00","end":"2022-06-06T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20606","refreshTime":"2022-06-12T18:00:41.9926681+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20606.csv?snapshot=2022-06-12T18%3A00%3A40.9612658Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-06-06T00:00:00","end":"2022-06-07T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20607","refreshTime":"2022-06-12T18:00:42.5551706+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20607.csv?snapshot=2022-06-12T18%3A00%3A41.4359908Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-06-07T00:00:00","end":"2022-06-08T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20608","refreshTime":"2022-06-12T18:00:42.3520588+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20608.csv?snapshot=2022-06-12T18%3A00%3A41.3570365Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-06-08T00:00:00","end":"2022-06-09T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20609","refreshTime":"2022-06-12T18:00:41.8207943+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20609.csv?snapshot=2022-06-12T18%3A00%3A40.1857153Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-06-09T00:00:00","end":"2022-06-10T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20610","refreshTime":"2022-06-12T18:00:43.102051+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20610.csv?snapshot=2022-06-12T18%3A00%3A42.3754460Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-06-10T00:00:00","end":"2022-06-11T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20611","refreshTime":"2022-06-12T18:00:42.1957868+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20611.csv?snapshot=2022-06-12T18%3A00%3A41.0252300Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-06-11T00:00:00","end":"2022-06-12T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20612","refreshTime":"2022-06-12T18:00:42.9770613+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20612.csv?snapshot=2022-06-12T18%3A00%3A41.9616857Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-06-12T00:00:00","end":"2022-06-13T00:00:00"}}]}]}