{"name":"ITEM_CATEGORIES","description":"Item Category","version":"1.0","culture":"en-US","modifiedTime":"2021-07-08T23:57:22.4070073+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"XXREP_IM_CATEGORY_V":{"queryId":"f7081e79-81d4-42ec-a6bd-8f7dfc175527","queryName":"XXREP_IM_CATEGORY_V","loadEnabled":true},"RangeStart":{"queryId":"519ea451-fefb-43a9-a0a9-c568f7668b79","queryName":"RangeStart"},"RangeEnd":{"queryId":"b283efe5-a65d-48cb-a9c4-2bc64c2608b1","queryName":"RangeEnd"},"XXREP_IM_CATEGORY_V_Canary":{"queryId":"ef0129fe-c898-4687-abb3-eac90aa0d83a","queryName":"XXREP_IM_CATEGORY_V_Canary"}},"document":"section Section1;\r\n\r\nshared XXREP_IM_CATEGORY_V = let\r\n    Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n    Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n    #\"Navigation 1\" = Navigation{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n    #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXREP_IM_CATEGORY_V\", Kind = \"View\"]}[Data],\r\n    #\"XXREP_IM_CATEGORY_V-4954454D5F4352454154494F4E5F5245465F44415445-autogenerated_for_incremental_refresh\" = Table.SelectRows(#\"Navigation 2\", each DateTime.From([ITEM_CREATION_REF_DATE]) >= RangeStart and DateTime.From([ITEM_CREATION_REF_DATE]) < RangeEnd)\r\nin\r\n    #\"XXREP_IM_CATEGORY_V-4954454D5F4352454154494F4E5F5245465F44415445-autogenerated_for_incremental_refresh\";\r\n\r\nshared XXREP_IM_CATEGORY_V_Canary = let\r\n    Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n    Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n    #\"Navigation 1\" = Navigation{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n    #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXREP_IM_CATEGORY_V\", Kind = \"View\"]}[Data],\r\n    #\"XXREP_IM_CATEGORY_V-4954454D5F4352454154494F4E5F5245465F44415445-autogenerated_for_incremental_refresh\" = Table.SelectRows(#\"Navigation 2\", each DateTime.From([ITEM_CREATION_REF_DATE]) >= RangeStart and DateTime.From([ITEM_CREATION_REF_DATE]) < RangeEnd), #\"XXREP_IM_CATEGORY_V_Canary-524F575F4352454154494F4E5F44415445-autogenerated_for_incremental_refresh\" = DateTime.ToText(Table.Max(#\"XXREP_IM_CATEGORY_V-4954454D5F4352454154494F4E5F5245465F44415445-autogenerated_for_incremental_refresh\",each [ROW_CREATION_DATE], [ROW_CREATION_DATE=#datetime(0001,01,01,00,00,00)])[ROW_CREATION_DATE]) in #\"XXREP_IM_CATEGORY_V_Canary-524F575F4352454154494F4E5F44415445-autogenerated_for_incremental_refresh\";\r\n\r\nshared RangeStart = let RangeStart = #datetime(0001,01,01,00,00,00) meta [IsParameterQuery=true, List={}, Type=\"DateTime\", IsParameterQueryRequired=true, Description=\"autogenerated_for_incremental_refresh\"] in RangeStart;\r\n\r\nshared RangeEnd = let RangeEnd = #datetime(9999,12,31,23,59,59) meta [IsParameterQuery=true, List={}, Type=\"DateTime\", IsParameterQueryRequired=true, Description=\"autogenerated_for_incremental_refresh\"] in RangeEnd;\r\n\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"XXREP_IM_CATEGORY_V","description":"","pbi:refreshPolicy":{"$type":"IncrementalRefreshPolicy","locationPattern":"XXREP_IM_CATEGORY_V/part.csv","rollingWindowGranularity":"quarter","rollingWindowPeriods":48,"incrementalGranularity":"quarter","incrementalPeriods":48,"pollingQuery":"XXREP_IM_CATEGORY_V_Canary"},"annotations":[{"name":"pbi:IncrementalRefreshDetectChangeAttribute","value":"ROW_CREATION_DATE"},{"name":"pbi:IncrementalRefreshFilterByAttribute","value":"ITEM_CREATION_REF_DATE"}],"attributes":[{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"ORGANIZATION_ID","dataType":"double"},{"name":"ITEM_NUMBER","dataType":"string"},{"name":"DESCRIPTION","dataType":"string"},{"name":"ORGANIZATION_CODE","dataType":"string"},{"name":"ROW_UPDATED_BY","dataType":"string"},{"name":"ITEM_CREATION_DATE","dataType":"dateTime"},{"name":"ROW_CREATION_DATE","dataType":"dateTime"},{"name":"PF_ITEM_NUMBER","dataType":"string"},{"name":"ECCN_ECCN","dataType":"string"},{"name":"COO_COUNTRY_OF_ORIGIN","dataType":"string"},{"name":"HTS_HTS_SCHEDULE_B","dataType":"string"},{"name":"PLNG_GREEN_SUPPLY_STATUS","dataType":"string"},{"name":"PLNG_PLANNING_ACTION","dataType":"string"},{"name":"PLNG_FAMILY_UNIQUE","dataType":"string"},{"name":"ST_SALES_TAX_CATEGORY","dataType":"string"},{"name":"CDI_CARTON_GROUP","dataType":"string"},{"name":"CI_CARTON_GROUP","dataType":"string"},{"name":"PROD_TBU","dataType":"string"},{"name":"PROD_FAMILY","dataType":"string"},{"name":"PROD_LINE","dataType":"string"},{"name":"PROD_FORECAST_FIELD","dataType":"string"},{"name":"CON_CONTRACT_CATEGORY","dataType":"string"},{"name":"PTLX_PATLEX_PERCENT","dataType":"string"},{"name":"COMM_COMMODITY","dataType":"string"},{"name":"SLT_SERVICE_LEAD_TIME","dataType":"string"},{"name":"FF_FORECAST_FIELD","dataType":"string"},{"name":"CS_SUPPLY_SOURCE","dataType":"string"},{"name":"CS_DEMAND_SOURCE","dataType":"string"},{"name":"DBT_DB_TEMP","dataType":"string"},{"name":"BUP_BACKUP","dataType":"string"},{"name":"PO_PRIMARY_ORG","dataType":"string"},{"name":"PO_SUPPLY_CHAIN_PORG","dataType":"string"},{"name":"BCP_BCP","dataType":"string"},{"name":"CUST_CUSTOMER","dataType":"string"},{"name":"ROYLT_ROYALTY","dataType":"string"},{"name":"SC_SECURITY_CLASS","dataType":"string"},{"name":"GTD_GREEN_TRANSITION_DATE","dataType":"string"},{"name":"ROH_EU_ROHS_COMPLIANT","dataType":"string"},{"name":"ROH_CHINA_ROHS_COMPLIANT","dataType":"string"},{"name":"FDA_FDA_ACCESSION","dataType":"string"},{"name":"SCC_SEQUENCE","dataType":"string"},{"name":"SCC_COMMODITY","dataType":"string"},{"name":"SCC_UNSPSC","dataType":"string"},{"name":"OPROD_TBU","dataType":"string"},{"name":"OPROD_FAMILY","dataType":"string"},{"name":"OPROD_LINE","dataType":"string"},{"name":"OPROD_FORECAST_FIELD","dataType":"string"},{"name":"SR_OPERATING_UNIT","dataType":"string"},{"name":"SR_PERCENTAGE","dataType":"string"},{"name":"SR_VENDOR","dataType":"string"},{"name":"SR_VENDOR_SITE","dataType":"string"},{"name":"SI_INSTALL_WITH_SALE","dataType":"string"},{"name":"IT_ITEM_TYPE_CODE","dataType":"string"},{"name":"IT_ITEM_TYPE_MEANING","dataType":"string"},{"name":"OPSR_SEC_REPORTING","dataType":"string"},{"name":"OPSR_DEMAND_SOURCE","dataType":"string"},{"name":"SECR_SEC_REPORTING","dataType":"string"},{"name":"OPC_ORG","dataType":"string"},{"name":"OPC_PLANNING_CODE","dataType":"string"},{"name":"SP_SHIPMENT_PRIORITY","dataType":"string"},{"name":"FI_FISCAL_YEAR","dataType":"string"},{"name":"FI_SFDC_FORECAST_ITEM","dataType":"string"},{"name":"PG_ORG","dataType":"string"},{"name":"PG_PLANNING_GROUP","dataType":"string"},{"name":"WC_ORG","dataType":"string"},{"name":"WC_WORK_CELL","dataType":"string"},{"name":"RM_REPLENISHMENT_METHOD","dataType":"string"},{"name":"SFLT_SUPPLIER_FULL_LEAD_TIME","dataType":"string"},{"name":"SCS_SUPPLY_CHAIN_STATUS","dataType":"string"},{"name":"BPAS_BPA_STATUS","dataType":"string"},{"name":"MCOO_MULTI_COUNTRY_OF_ORIGIN","dataType":"string"},{"name":"DSO_DEFAULT_SHIPPING_ORG","dataType":"string"},{"name":"SFDCT_SFDC_TRANSFER","dataType":"string"},{"name":"IKC_ORG","dataType":"string"},{"name":"IKC_ORG_GROUP","dataType":"string"},{"name":"IKC_USERID","dataType":"string"},{"name":"EUHTS_HTS_CODE_EU","dataType":"string"},{"name":"CRI_ACCOUNT_NUMBER","dataType":"string"},{"name":"XYZ_XYZ_CLASS","dataType":"string"},{"name":"SCSD_SUPPLY_CHAIN_STATUS_DAYS","dataType":"string"},{"name":"MMKS_SOURCE","dataType":"string"},{"name":"MMKS_AUTO_UPDATE","dataType":"string"},{"name":"DO_DESIGN_ORG","dataType":"string"},{"name":"ITEM_CREATION_REF_DATE","dataType":"dateTime"}],"partitions":[{"name":"IncrementalRefreshPolicyPartition-2009Q3","refreshTime":"2021-07-09T03:00:10.9908034+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/11308dc8-08ee-448e-8659-0498c687df27/XXREP_IM_CATEGORY_V/part-2009Q3.csv?snapshot=2021-07-09T03%3A00%3A10.8333578Z","pbi:refreshBookmark":"1/1/0001 12:00:00 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2009-07-01T00:00:00","end":"2009-10-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2009Q4","refreshTime":"2021-07-09T03:02:08.7320142+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/11308dc8-08ee-448e-8659-0498c687df27/XXREP_IM_CATEGORY_V/part-2009Q4.csv?snapshot=2021-07-09T03%3A02%3A08.5103287Z","pbi:refreshBookmark":"1/1/0001 12:00:00 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2009-10-01T00:00:00","end":"2010-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2010Q1","refreshTime":"2021-07-09T03:21:53.8830539+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/11308dc8-08ee-448e-8659-0498c687df27/XXREP_IM_CATEGORY_V/part-2010Q1.csv?snapshot=2021-07-09T03%3A21%3A53.7689453Z","pbi:refreshBookmark":"1/1/0001 12:00:00 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2010-01-01T00:00:00","end":"2010-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2010Q2","refreshTime":"2021-07-09T03:24:11.8756334+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/11308dc8-08ee-448e-8659-0498c687df27/XXREP_IM_CATEGORY_V/part-2010Q2.csv?snapshot=2021-07-09T03%3A24%3A11.6175961Z","pbi:refreshBookmark":"1/1/0001 12:00:00 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2010-04-01T00:00:00","end":"2010-07-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2010Q3","refreshTime":"2021-07-09T03:31:25.5382633+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/11308dc8-08ee-448e-8659-0498c687df27/XXREP_IM_CATEGORY_V/part-2010Q3.csv?snapshot=2021-07-09T03%3A31%3A25.4353248Z","pbi:refreshBookmark":"1/1/0001 12:00:00 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2010-07-01T00:00:00","end":"2010-10-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2010Q4","refreshTime":"2021-07-09T02:16:02.6843089+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/11308dc8-08ee-448e-8659-0498c687df27/XXREP_IM_CATEGORY_V/part-2010Q4.csv?snapshot=2021-07-09T02%3A16%3A02.1420291Z","pbi:refreshBookmark":"1/1/0001 12:00:00 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2010-10-01T00:00:00","end":"2011-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2011Q1","refreshTime":"2021-08-19T05:45:19.7539845+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/11308dc8-08ee-448e-8659-0498c687df27/XXREP_IM_CATEGORY_V/part-2011Q1.csv?snapshot=2021-08-19T05%3A44%3A53.9051138Z","pbi:refreshBookmark":"8/19/2021 12:29:30 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2011-01-01T00:00:00","end":"2011-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2011Q2","refreshTime":"2021-08-19T05:48:05.3838422+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/11308dc8-08ee-448e-8659-0498c687df27/XXREP_IM_CATEGORY_V/part-2011Q2.csv?snapshot=2021-08-19T05%3A47%3A25.8893002Z","pbi:refreshBookmark":"8/19/2021 12:29:30 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2011-04-01T00:00:00","end":"2011-07-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2011Q3","refreshTime":"2021-08-19T05:47:57.4967001+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/11308dc8-08ee-448e-8659-0498c687df27/XXREP_IM_CATEGORY_V/part-2011Q3.csv?snapshot=2021-08-19T05%3A47%3A18.4800244Z","pbi:refreshBookmark":"8/19/2021 12:29:30 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2011-07-01T00:00:00","end":"2011-10-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2011Q4","refreshTime":"2021-08-19T05:44:10.2815434+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/11308dc8-08ee-448e-8659-0498c687df27/XXREP_IM_CATEGORY_V/part-2011Q4.csv?snapshot=2021-08-19T05%3A43%3A53.7803151Z","pbi:refreshBookmark":"8/19/2021 12:29:30 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2011-10-01T00:00:00","end":"2012-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2012Q1","refreshTime":"2021-08-19T05:40:47.4837495+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/11308dc8-08ee-448e-8659-0498c687df27/XXREP_IM_CATEGORY_V/part-2012Q1.csv?snapshot=2021-08-19T05%3A40%3A43.8921555Z","pbi:refreshBookmark":"8/19/2021 12:29:30 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2012-01-01T00:00:00","end":"2012-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2012Q2","refreshTime":"2021-08-19T05:39:01.5017901+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/11308dc8-08ee-448e-8659-0498c687df27/XXREP_IM_CATEGORY_V/part-2012Q2.csv?snapshot=2021-08-19T05%3A39%3A00.2583848Z","pbi:refreshBookmark":"8/18/2021 11:29:32 PM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2012-04-01T00:00:00","end":"2012-07-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2012Q3","refreshTime":"2021-08-19T05:41:15.0435581+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/11308dc8-08ee-448e-8659-0498c687df27/XXREP_IM_CATEGORY_V/part-2012Q3.csv?snapshot=2021-08-19T05%3A41%3A10.2499155Z","pbi:refreshBookmark":"8/19/2021 12:29:30 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2012-07-01T00:00:00","end":"2012-10-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2012Q4","refreshTime":"2021-08-19T05:39:37.3429727+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/11308dc8-08ee-448e-8659-0498c687df27/XXREP_IM_CATEGORY_V/part-2012Q4.csv?snapshot=2021-08-19T05%3A39%3A30.8941949Z","pbi:refreshBookmark":"8/19/2021 12:29:30 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2012-10-01T00:00:00","end":"2013-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2013Q1","refreshTime":"2021-08-19T05:40:52.8468036+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/11308dc8-08ee-448e-8659-0498c687df27/XXREP_IM_CATEGORY_V/part-2013Q1.csv?snapshot=2021-08-19T05%3A40%3A49.1558994Z","pbi:refreshBookmark":"8/18/2021 11:29:32 PM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2013-01-01T00:00:00","end":"2013-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2013Q2","refreshTime":"2021-08-19T05:39:28.2812582+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/11308dc8-08ee-448e-8659-0498c687df27/XXREP_IM_CATEGORY_V/part-2013Q2.csv?snapshot=2021-08-19T05%3A39%3A25.1370940Z","pbi:refreshBookmark":"8/18/2021 11:29:32 PM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2013-04-01T00:00:00","end":"2013-07-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2013Q3","refreshTime":"2021-08-19T05:41:28.8045785+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/11308dc8-08ee-448e-8659-0498c687df27/XXREP_IM_CATEGORY_V/part-2013Q3.csv?snapshot=2021-08-19T05%3A41%3A18.3216575Z","pbi:refreshBookmark":"8/19/2021 1:29:07 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2013-07-01T00:00:00","end":"2013-10-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2013Q4","refreshTime":"2021-08-19T05:41:23.2703745+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/11308dc8-08ee-448e-8659-0498c687df27/XXREP_IM_CATEGORY_V/part-2013Q4.csv?snapshot=2021-08-19T05%3A41%3A17.7422447Z","pbi:refreshBookmark":"8/18/2021 11:29:32 PM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2013-10-01T00:00:00","end":"2014-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2014Q1","refreshTime":"2021-08-19T05:39:35.1834816+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/11308dc8-08ee-448e-8659-0498c687df27/XXREP_IM_CATEGORY_V/part-2014Q1.csv?snapshot=2021-08-19T05%3A39%3A30.7280772Z","pbi:refreshBookmark":"8/18/2021 11:29:32 PM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2014-01-01T00:00:00","end":"2014-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2014Q2","refreshTime":"2021-08-19T05:39:12.7712469+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/11308dc8-08ee-448e-8659-0498c687df27/XXREP_IM_CATEGORY_V/part-2014Q2.csv?snapshot=2021-08-19T05%3A39%3A10.7308403Z","pbi:refreshBookmark":"8/18/2021 11:29:32 PM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2014-04-01T00:00:00","end":"2014-07-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2014Q3","refreshTime":"2021-08-19T05:39:30.7679955+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/11308dc8-08ee-448e-8659-0498c687df27/XXREP_IM_CATEGORY_V/part-2014Q3.csv?snapshot=2021-08-19T05%3A39%3A28.2242892Z","pbi:refreshBookmark":"8/18/2021 8:29:39 PM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2014-07-01T00:00:00","end":"2014-10-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2014Q4","refreshTime":"2021-08-19T05:39:22.4883796+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/11308dc8-08ee-448e-8659-0498c687df27/XXREP_IM_CATEGORY_V/part-2014Q4.csv?snapshot=2021-08-19T05%3A39%3A20.1385381Z","pbi:refreshBookmark":"8/18/2021 11:29:32 PM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2014-10-01T00:00:00","end":"2015-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2015Q1","refreshTime":"2021-08-19T05:40:20.9842142+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/11308dc8-08ee-448e-8659-0498c687df27/XXREP_IM_CATEGORY_V/part-2015Q1.csv?snapshot=2021-08-19T05%3A40%3A17.7995777Z","pbi:refreshBookmark":"8/18/2021 11:29:32 PM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2015-01-01T00:00:00","end":"2015-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2015Q2","refreshTime":"2021-08-19T05:39:15.5086339+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/11308dc8-08ee-448e-8659-0498c687df27/XXREP_IM_CATEGORY_V/part-2015Q2.csv?snapshot=2021-08-19T05%3A39%3A13.5178224Z","pbi:refreshBookmark":"8/18/2021 11:29:32 PM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2015-04-01T00:00:00","end":"2015-07-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2015Q3","refreshTime":"2021-08-19T05:39:57.1169372+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/11308dc8-08ee-448e-8659-0498c687df27/XXREP_IM_CATEGORY_V/part-2015Q3.csv?snapshot=2021-08-19T05%3A39%3A53.9606094Z","pbi:refreshBookmark":"8/18/2021 11:29:32 PM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2015-07-01T00:00:00","end":"2015-10-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2015Q4","refreshTime":"2021-08-19T05:39:08.293431+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/11308dc8-08ee-448e-8659-0498c687df27/XXREP_IM_CATEGORY_V/part-2015Q4.csv?snapshot=2021-08-19T05%3A39%3A06.7750265Z","pbi:refreshBookmark":"8/18/2021 11:29:32 PM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2015-10-01T00:00:00","end":"2016-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2016Q1","refreshTime":"2021-08-19T05:39:36.2165839+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/11308dc8-08ee-448e-8659-0498c687df27/XXREP_IM_CATEGORY_V/part-2016Q1.csv?snapshot=2021-08-19T05%3A39%3A30.4929092Z","pbi:refreshBookmark":"8/18/2021 11:29:32 PM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2016-01-01T00:00:00","end":"2016-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2016Q2","refreshTime":"2021-08-19T05:42:36.7086971+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/11308dc8-08ee-448e-8659-0498c687df27/XXREP_IM_CATEGORY_V/part-2016Q2.csv?snapshot=2021-08-19T05%3A42%3A26.3110551Z","pbi:refreshBookmark":"8/19/2021 12:29:30 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2016-04-01T00:00:00","end":"2016-07-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2016Q3","refreshTime":"2021-08-19T05:39:39.913763+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/11308dc8-08ee-448e-8659-0498c687df27/XXREP_IM_CATEGORY_V/part-2016Q3.csv?snapshot=2021-08-19T05%3A39%3A36.9044697Z","pbi:refreshBookmark":"8/18/2021 11:29:32 PM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2016-07-01T00:00:00","end":"2016-10-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2016Q4","refreshTime":"2021-08-19T05:40:09.2113307+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/11308dc8-08ee-448e-8659-0498c687df27/XXREP_IM_CATEGORY_V/part-2016Q4.csv?snapshot=2021-08-19T05%3A40%3A06.6336343Z","pbi:refreshBookmark":"8/18/2021 11:29:32 PM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2016-10-01T00:00:00","end":"2017-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2017Q1","refreshTime":"2021-08-19T05:40:50.483968+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/11308dc8-08ee-448e-8659-0498c687df27/XXREP_IM_CATEGORY_V/part-2017Q1.csv?snapshot=2021-08-19T05%3A40%3A46.8632690Z","pbi:refreshBookmark":"8/18/2021 11:29:32 PM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2017-01-01T00:00:00","end":"2017-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2017Q2","refreshTime":"2021-08-19T05:46:41.7210963+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/11308dc8-08ee-448e-8659-0498c687df27/XXREP_IM_CATEGORY_V/part-2017Q2.csv?snapshot=2021-08-19T05%3A46%3A04.2301736Z","pbi:refreshBookmark":"8/19/2021 1:29:07 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2017-04-01T00:00:00","end":"2017-07-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2017Q3","refreshTime":"2021-08-19T05:47:30.1215594+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/11308dc8-08ee-448e-8659-0498c687df27/XXREP_IM_CATEGORY_V/part-2017Q3.csv?snapshot=2021-08-19T05%3A46%3A48.3385675Z","pbi:refreshBookmark":"8/19/2021 5:29:16 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2017-07-01T00:00:00","end":"2017-10-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2017Q4","refreshTime":"2021-08-19T05:48:36.3305314+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/11308dc8-08ee-448e-8659-0498c687df27/XXREP_IM_CATEGORY_V/part-2017Q4.csv?snapshot=2021-08-19T05%3A47%3A52.0329091Z","pbi:refreshBookmark":"8/19/2021 5:29:16 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2017-10-01T00:00:00","end":"2018-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2018Q1","refreshTime":"2021-08-19T05:47:38.0640601+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/11308dc8-08ee-448e-8659-0498c687df27/XXREP_IM_CATEGORY_V/part-2018Q1.csv?snapshot=2021-08-19T05%3A46%3A52.5255507Z","pbi:refreshBookmark":"8/19/2021 5:29:16 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2018-01-01T00:00:00","end":"2018-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2018Q2","refreshTime":"2021-08-19T05:45:23.6067209+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/11308dc8-08ee-448e-8659-0498c687df27/XXREP_IM_CATEGORY_V/part-2018Q2.csv?snapshot=2021-08-19T05%3A45%3A01.0802234Z","pbi:refreshBookmark":"8/19/2021 1:29:07 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2018-04-01T00:00:00","end":"2018-07-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2018Q3","refreshTime":"2021-08-19T05:45:09.777602+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/11308dc8-08ee-448e-8659-0498c687df27/XXREP_IM_CATEGORY_V/part-2018Q3.csv?snapshot=2021-08-19T05%3A44%3A39.5518976Z","pbi:refreshBookmark":"8/19/2021 3:29:04 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2018-07-01T00:00:00","end":"2018-10-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2018Q4","refreshTime":"2021-08-19T05:41:48.4500183+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/11308dc8-08ee-448e-8659-0498c687df27/XXREP_IM_CATEGORY_V/part-2018Q4.csv?snapshot=2021-08-19T05%3A41%3A41.0788565Z","pbi:refreshBookmark":"8/19/2021 2:30:14 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2018-10-01T00:00:00","end":"2019-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2019Q1","refreshTime":"2021-08-19T05:44:38.746133+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/11308dc8-08ee-448e-8659-0498c687df27/XXREP_IM_CATEGORY_V/part-2019Q1.csv?snapshot=2021-08-19T05%3A44%3A21.9853970Z","pbi:refreshBookmark":"8/19/2021 5:29:16 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2019-01-01T00:00:00","end":"2019-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2019Q2","refreshTime":"2021-08-19T05:47:20.4688293+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/11308dc8-08ee-448e-8659-0498c687df27/XXREP_IM_CATEGORY_V/part-2019Q2.csv?snapshot=2021-08-19T05%3A46%3A45.8838198Z","pbi:refreshBookmark":"8/19/2021 5:29:16 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2019-04-01T00:00:00","end":"2019-07-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2019Q3","refreshTime":"2021-08-19T05:42:16.4854321+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/11308dc8-08ee-448e-8659-0498c687df27/XXREP_IM_CATEGORY_V/part-2019Q3.csv?snapshot=2021-08-19T05%3A42%3A08.5794352Z","pbi:refreshBookmark":"8/19/2021 2:30:14 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2019-07-01T00:00:00","end":"2019-10-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2019Q4","refreshTime":"2021-08-19T05:48:12.8013457+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/11308dc8-08ee-448e-8659-0498c687df27/XXREP_IM_CATEGORY_V/part-2019Q4.csv?snapshot=2021-08-19T05%3A47%3A35.8333727Z","pbi:refreshBookmark":"8/19/2021 5:29:16 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2019-10-01T00:00:00","end":"2020-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2020Q1","refreshTime":"2021-08-19T05:47:15.3637424+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/11308dc8-08ee-448e-8659-0498c687df27/XXREP_IM_CATEGORY_V/part-2020Q1.csv?snapshot=2021-08-19T05%3A46%3A40.5490251Z","pbi:refreshBookmark":"8/19/2021 5:29:16 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2020-01-01T00:00:00","end":"2020-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2020Q2","refreshTime":"2021-08-19T05:45:01.3613116+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/11308dc8-08ee-448e-8659-0498c687df27/XXREP_IM_CATEGORY_V/part-2020Q2.csv?snapshot=2021-08-19T05%3A44%3A38.4401070Z","pbi:refreshBookmark":"8/19/2021 5:29:16 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2020-04-01T00:00:00","end":"2020-07-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2020Q3","refreshTime":"2021-08-19T05:46:14.5871666+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/11308dc8-08ee-448e-8659-0498c687df27/XXREP_IM_CATEGORY_V/part-2020Q3.csv?snapshot=2021-08-19T05%3A45%3A45.7099868Z","pbi:refreshBookmark":"8/19/2021 5:29:16 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2020-07-01T00:00:00","end":"2020-10-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2020Q4","refreshTime":"2021-08-19T05:42:31.8286308+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/11308dc8-08ee-448e-8659-0498c687df27/XXREP_IM_CATEGORY_V/part-2020Q4.csv?snapshot=2021-08-19T05%3A42%3A20.8982054Z","pbi:refreshBookmark":"8/19/2021 3:29:04 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2020-10-01T00:00:00","end":"2021-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2021Q1","refreshTime":"2021-08-19T05:44:28.344058+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/11308dc8-08ee-448e-8659-0498c687df27/XXREP_IM_CATEGORY_V/part-2021Q1.csv?snapshot=2021-08-19T05%3A44%3A14.9223666Z","pbi:refreshBookmark":"8/19/2021 5:29:16 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2021-01-01T00:00:00","end":"2021-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2021Q2","refreshTime":"2021-08-19T05:45:34.2882396+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/11308dc8-08ee-448e-8659-0498c687df27/XXREP_IM_CATEGORY_V/part-2021Q2.csv?snapshot=2021-08-19T05%3A45%3A01.9348313Z","pbi:refreshBookmark":"8/19/2021 5:29:16 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2021-04-01T00:00:00","end":"2021-07-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2021Q3","refreshTime":"2021-08-19T05:42:26.4360323+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/11308dc8-08ee-448e-8659-0498c687df27/XXREP_IM_CATEGORY_V/part-2021Q3.csv?snapshot=2021-08-19T05%3A42%3A19.0929146Z","pbi:refreshBookmark":"8/19/2021 5:29:16 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2021-07-01T00:00:00","end":"2021-10-01T00:00:00"}}]}]}