{"name":"WIP_CUMULUS_RELATED","description":"CUMULUS Work Orders and related (refreshed hourly)","version":"1.0","culture":"en-US","modifiedTime":"2021-11-26T14:29:13.3109792+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"Data Update Info":{"queryId":"6b5c9938-325d-4fab-aaff-8e012d88bd13","queryName":"Data Update Info","loadEnabled":true},"CUM_FAILURES_DEFECTS":{"queryId":"b5584e18-db57-43cd-83ed-0f5660e8c07a","queryName":"CUM_FAILURES_DEFECTS","loadEnabled":true},"CUM_WORKORDERS":{"queryId":"5e33a201-14e9-4801-aa9b-3425b9e4e73c","queryName":"CUM_WORKORDERS","loadEnabled":true},"RangeEnd":{"queryId":"6ec92aff-52dd-4db7-84de-435fa71acd77","queryName":"RangeEnd"},"RangeStart":{"queryId":"07d9296c-0b4a-43f1-9493-cff748b8f1d8","queryName":"RangeStart"},"CUM_FAILURES_DEFECTS_Canary":{"queryId":"f6530a69-f752-433d-ba10-d00317b988a1","queryName":"CUM_FAILURES_DEFECTS_Canary"},"CUM_WORKORDERS_Canary":{"queryId":"167c69ac-044f-4dc4-bef8-b0ee182869f4","queryName":"CUM_WORKORDERS_Canary"}},"document":"section Section1;\r\n\r\nshared #\"Data Update Info\" = let\r\n    Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n    Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n    #\"Navigation 1\" = Navigation{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n    #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXREP_DATA_UPDATE_V\", Kind = \"View\"]}[Data],\r\n    #\"Filtered rows\" = Table.SelectRows(#\"Navigation 2\", each [TABLE_NAME] = \"CUMULUS.CUM_FAILURES_DEFECTS\" or [TABLE_NAME] = \"CUMULUS.CUM_WORKORDERS\")\r\nin\r\n    #\"Filtered rows\";\r\n\r\nshared CUM_FAILURES_DEFECTS = let\r\n    Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n    #\"Navigation 1\" = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n    #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"CUMULUS\", Kind = \"Schema\"]}[Data],\r\n    #\"Navigation 3\" = #\"Navigation 2\"{[Name = \"CUM_FAILURES_DEFECTS\", Kind = \"Table\"]}[Data],\r\n    #\"CUM_FAILURES_DEFECTS-4641494C5552455F44415445-autogenerated_for_incremental_refresh\" = Table.SelectRows(#\"Navigation 3\", each DateTime.From([FAILURE_DATE]) >= RangeStart and DateTime.From([FAILURE_DATE]) < RangeEnd)\r\nin\r\n    #\"CUM_FAILURES_DEFECTS-4641494C5552455F44415445-autogenerated_for_incremental_refresh\";\r\n\r\nshared CUM_FAILURES_DEFECTS_Canary = let\r\n    Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n    #\"Navigation 1\" = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n    #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"CUMULUS\", Kind = \"Schema\"]}[Data],\r\n    #\"Navigation 3\" = #\"Navigation 2\"{[Name = \"CUM_FAILURES_DEFECTS\", Kind = \"Table\"]}[Data],\r\n    #\"CUM_FAILURES_DEFECTS-4641494C5552455F44415445-autogenerated_for_incremental_refresh\" = Table.SelectRows(#\"Navigation 3\", each DateTime.From([FAILURE_DATE]) >= RangeStart and DateTime.From([FAILURE_DATE]) < RangeEnd), #\"CUM_FAILURES_DEFECTS_Canary-4D4F4449464945445F44415445-autogenerated_for_incremental_refresh\" = DateTime.ToText(Table.Max(#\"CUM_FAILURES_DEFECTS-4641494C5552455F44415445-autogenerated_for_incremental_refresh\",each [MODIFIED_DATE], [MODIFIED_DATE=#datetime(0001,01,01,00,00,00)])[MODIFIED_DATE]) in #\"CUM_FAILURES_DEFECTS_Canary-4D4F4449464945445F44415445-autogenerated_for_incremental_refresh\";\r\n\r\nshared CUM_WORKORDERS = let\r\n    Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n    #\"Navigation 1\" = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n    #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"CUMULUS\", Kind = \"Schema\"]}[Data],\r\n    #\"Navigation 3\" = #\"Navigation 2\"{[Name = \"CUM_WORKORDERS\", Kind = \"Table\"]}[Data],\r\n    #\"CUM_WORKORDERS-43524541544544-autogenerated_for_incremental_refresh\" = Table.SelectRows(#\"Navigation 3\", each DateTime.From([CREATED]) >= RangeStart and DateTime.From([CREATED]) < RangeEnd)\r\nin\r\n    #\"CUM_WORKORDERS-43524541544544-autogenerated_for_incremental_refresh\";\r\n\r\nshared CUM_WORKORDERS_Canary = let\r\n    Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n    #\"Navigation 1\" = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n    #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"CUMULUS\", Kind = \"Schema\"]}[Data],\r\n    #\"Navigation 3\" = #\"Navigation 2\"{[Name = \"CUM_WORKORDERS\", Kind = \"Table\"]}[Data],\r\n    #\"CUM_WORKORDERS-43524541544544-autogenerated_for_incremental_refresh\" = Table.SelectRows(#\"Navigation 3\", each DateTime.From([CREATED]) >= RangeStart and DateTime.From([CREATED]) < RangeEnd), #\"CUM_WORKORDERS_Canary-4D4F444946494544-autogenerated_for_incremental_refresh\" = DateTime.ToText(Table.Max(#\"CUM_WORKORDERS-43524541544544-autogenerated_for_incremental_refresh\",each [MODIFIED], [MODIFIED=#datetime(0001,01,01,00,00,00)])[MODIFIED]) in #\"CUM_WORKORDERS_Canary-4D4F444946494544-autogenerated_for_incremental_refresh\";\r\n\r\nshared RangeStart = let RangeStart = #datetime(0001,01,01,00,00,00) meta [IsParameterQuery=true, List={}, Type=\"DateTime\", IsParameterQueryRequired=true, Description=\"autogenerated_for_incremental_refresh\"] in RangeStart;\r\n\r\nshared RangeEnd = let RangeEnd = #datetime(9999,12,31,23,59,59) meta [IsParameterQuery=true, List={}, Type=\"DateTime\", IsParameterQueryRequired=true, Description=\"autogenerated_for_incremental_refresh\"] in RangeEnd;\r\n\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"Data Update Info","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Data%20Update%20Info.csv"},"attributes":[{"name":"TABLE_NAME","dataType":"string"},{"name":"DATA_UPDATE_DATE","dataType":"dateTime"},{"name":"DATA_UPDATE_DESC","dataType":"string"},{"name":"DATA_FLOW_REFRESH_DATE","dataType":"dateTime"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T09:01:11.0070829+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/Data%20Update%20Info.csv?snapshot=2022-06-13T09%3A01%3A10.4548763Z"}]},{"$type":"LocalEntity","name":"CUM_FAILURES_DEFECTS","description":"","pbi:refreshPolicy":{"$type":"IncrementalRefreshPolicy","locationPattern":"CUM_FAILURES_DEFECTS/part.csv","rollingWindowGranularity":"quarter","rollingWindowPeriods":24,"incrementalGranularity":"quarter","incrementalPeriods":24,"pollingQuery":"CUM_FAILURES_DEFECTS_Canary"},"annotations":[{"name":"pbi:IncrementalRefreshDetectChangeAttribute","value":"MODIFIED_DATE"},{"name":"pbi:IncrementalRefreshFilterByAttribute","value":"FAILURE_DATE"}],"attributes":[{"name":"FAILUREKEY","dataType":"double"},{"name":"SANDBOXKEY","dataType":"double"},{"name":"WORKORDERKEY","dataType":"double"},{"name":"FAILURE_DATE","dataType":"dateTime"},{"name":"MODIFIED_DATE","dataType":"dateTime"},{"name":"ORG","dataType":"string"},{"name":"TYPE","dataType":"string"},{"name":"PARTNUMBERKEY","dataType":"double"},{"name":"PROCESS","dataType":"string"},{"name":"PROCESS_DESCRIPTION","dataType":"string"},{"name":"QTY_REJECTED","dataType":"double"},{"name":"FAILURE_GROUP","dataType":"string"},{"name":"FAILURE","dataType":"string"},{"name":"REJECTED_BY","dataType":"string"},{"name":"EST_EFFORT_HRS","dataType":"double"},{"name":"ROOT_CAUSE_GROUP","dataType":"string"},{"name":"ROOT_CAUSE","dataType":"string"},{"name":"NCR","dataType":"string"},{"name":"FAILURE_NOTES","dataType":"string"}],"partitions":[{"name":"IncrementalRefreshPolicyPartition-2016Q2","refreshTime":"2021-11-26T14:32:33.7760031+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_FAILURES_DEFECTS/part-2016Q2.csv?snapshot=2021-11-26T14%3A32%3A33.2796103Z","pbi:refreshBookmark":"6/30/2016 11:42:48 PM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2016-04-01T00:00:00","end":"2016-07-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2016Q3","refreshTime":"2021-11-26T14:34:25.5045517+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_FAILURES_DEFECTS/part-2016Q3.csv?snapshot=2021-11-26T14%3A34%3A24.5459541Z","pbi:refreshBookmark":"9/30/2016 10:26:20 PM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2016-07-01T00:00:00","end":"2016-10-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2016Q4","refreshTime":"2021-11-26T14:34:25.0670595+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_FAILURES_DEFECTS/part-2016Q4.csv?snapshot=2021-11-26T14%3A34%3A24.4370163Z","pbi:refreshBookmark":"12/30/2016 8:14:43 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2016-10-01T00:00:00","end":"2017-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2017Q1","refreshTime":"2021-11-26T14:34:06.9616738+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_FAILURES_DEFECTS/part-2017Q1.csv?snapshot=2021-11-26T14%3A34%3A06.6382005Z","pbi:refreshBookmark":"3/31/2017 9:29:14 PM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2017-01-01T00:00:00","end":"2017-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2017Q2","refreshTime":"2021-11-26T14:34:03.0228031+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_FAILURES_DEFECTS/part-2017Q2.csv?snapshot=2021-11-26T14%3A34%3A02.6734688Z","pbi:refreshBookmark":"6/30/2017 10:23:44 PM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2017-04-01T00:00:00","end":"2017-07-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2017Q3","refreshTime":"2021-11-26T14:34:10.1088641+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_FAILURES_DEFECTS/part-2017Q3.csv?snapshot=2021-11-26T14%3A34%3A09.7304310Z","pbi:refreshBookmark":"9/30/2017 10:28:18 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2017-07-01T00:00:00","end":"2017-10-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2017Q4","refreshTime":"2021-11-26T14:34:23.2562398+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_FAILURES_DEFECTS/part-2017Q4.csv?snapshot=2021-11-26T14%3A34%3A22.8199413Z","pbi:refreshBookmark":"12/29/2017 12:43:14 PM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2017-10-01T00:00:00","end":"2018-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2018Q1","refreshTime":"2021-11-26T14:34:24.3326592+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_FAILURES_DEFECTS/part-2018Q1.csv?snapshot=2021-11-26T14%3A34%3A23.6564632Z","pbi:refreshBookmark":"3/31/2018 12:06:30 PM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2018-01-01T00:00:00","end":"2018-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2018Q2","refreshTime":"2021-11-26T14:34:24.7232886+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_FAILURES_DEFECTS/part-2018Q2.csv?snapshot=2021-11-26T14%3A34%3A24.0092609Z","pbi:refreshBookmark":"6/30/2018 11:25:52 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2018-04-01T00:00:00","end":"2018-07-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2018Q3","refreshTime":"2021-12-08T18:00:49.5171854+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_FAILURES_DEFECTS/part-2018Q3.csv?snapshot=2021-12-08T18%3A00%3A49.0533795Z","pbi:refreshBookmark":"12/8/2021 4:45:00 PM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2018-07-01T00:00:00","end":"2018-10-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2018Q4","refreshTime":"2021-11-26T14:34:03.6790675+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_FAILURES_DEFECTS/part-2018Q4.csv?snapshot=2021-11-26T14%3A34%3A03.2801215Z","pbi:refreshBookmark":"12/31/2018 1:50:38 PM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2018-10-01T00:00:00","end":"2019-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2019Q1","refreshTime":"2022-05-27T01:00:31.1881332+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_FAILURES_DEFECTS/part-2019Q1.csv?snapshot=2022-05-27T01%3A00%3A28.9240485Z","pbi:refreshBookmark":"5/26/2022 8:41:17 PM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2019-01-01T00:00:00","end":"2019-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2019Q2","refreshTime":"2022-05-10T01:01:17.0121027+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_FAILURES_DEFECTS/part-2019Q2.csv?snapshot=2022-05-10T01%3A01%3A10.0993157Z","pbi:refreshBookmark":"5/9/2022 10:39:22 PM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2019-04-01T00:00:00","end":"2019-07-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2019Q3","refreshTime":"2021-12-08T18:00:37.6938245+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_FAILURES_DEFECTS/part-2019Q3.csv?snapshot=2021-12-08T18%3A00%3A37.0172816Z","pbi:refreshBookmark":"12/8/2021 4:45:54 PM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2019-07-01T00:00:00","end":"2019-10-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2019Q4","refreshTime":"2022-03-21T11:03:22.5749683+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_FAILURES_DEFECTS/part-2019Q4.csv?snapshot=2022-03-21T11%3A03%3A20.5259194Z","pbi:refreshBookmark":"3/21/2022 9:38:38 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2019-10-01T00:00:00","end":"2020-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2020Q1","refreshTime":"2022-03-21T11:03:22.481219+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_FAILURES_DEFECTS/part-2020Q1.csv?snapshot=2022-03-21T11%3A03%3A21.1065825Z","pbi:refreshBookmark":"3/21/2022 9:38:38 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2020-01-01T00:00:00","end":"2020-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2020Q2","refreshTime":"2022-03-21T11:03:21.4697519+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_FAILURES_DEFECTS/part-2020Q2.csv?snapshot=2022-03-21T11%3A03%3A19.9372596Z","pbi:refreshBookmark":"3/21/2022 9:38:38 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2020-04-01T00:00:00","end":"2020-07-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2020Q3","refreshTime":"2022-03-21T11:03:27.3669355+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_FAILURES_DEFECTS/part-2020Q3.csv?snapshot=2022-03-21T11%3A03%3A25.3971033Z","pbi:refreshBookmark":"3/21/2022 9:38:38 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2020-07-01T00:00:00","end":"2020-10-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2020Q4","refreshTime":"2022-03-21T11:03:22.7937269+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_FAILURES_DEFECTS/part-2020Q4.csv?snapshot=2022-03-21T11%3A03%3A21.5003560Z","pbi:refreshBookmark":"3/21/2022 9:38:38 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2020-10-01T00:00:00","end":"2021-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2021Q1","refreshTime":"2022-04-29T21:01:48.6659491+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_FAILURES_DEFECTS/part-2021Q1.csv?snapshot=2022-04-29T21%3A01%3A45.1603952Z","pbi:refreshBookmark":"4/29/2022 8:11:00 PM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2021-01-01T00:00:00","end":"2021-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2021Q2","refreshTime":"2022-04-29T21:01:46.2596791+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_FAILURES_DEFECTS/part-2021Q2.csv?snapshot=2022-04-29T21%3A01%3A44.2279266Z","pbi:refreshBookmark":"4/29/2022 8:08:17 PM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2021-04-01T00:00:00","end":"2021-07-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2021Q3","refreshTime":"2022-06-13T09:01:16.5805682+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_FAILURES_DEFECTS/part-2021Q3.csv?snapshot=2022-06-13T09%3A01%3A15.6559383Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2021-07-01T00:00:00","end":"2021-10-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2021Q4","refreshTime":"2022-05-09T19:02:04.4622353+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_FAILURES_DEFECTS/part-2021Q4.csv?snapshot=2022-05-09T19%3A02%3A02.7722034Z","pbi:refreshBookmark":"5/9/2022 4:00:33 PM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2021-10-01T00:00:00","end":"2022-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q1","refreshTime":"2022-06-02T01:00:46.1619259+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_FAILURES_DEFECTS/part-2022Q1.csv?snapshot=2022-06-02T01%3A00%3A45.6055775Z","pbi:refreshBookmark":"6/1/2022 7:54:19 PM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-01-01T00:00:00","end":"2022-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q2","refreshTime":"2022-06-13T01:00:25.1056281+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_FAILURES_DEFECTS/part-2022Q2.csv?snapshot=2022-06-13T01%3A00%3A24.4545007Z","pbi:refreshBookmark":"6/12/2022 11:46:41 PM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-01T00:00:00","end":"2022-07-01T00:00:00"}}]},{"$type":"LocalEntity","name":"CUM_WORKORDERS","description":"","pbi:refreshPolicy":{"$type":"IncrementalRefreshPolicy","locationPattern":"CUM_WORKORDERS/part.csv","rollingWindowGranularity":"quarter","rollingWindowPeriods":80,"incrementalGranularity":"quarter","incrementalPeriods":20,"pollingQuery":"CUM_WORKORDERS_Canary"},"annotations":[{"name":"pbi:IncrementalRefreshDetectChangeAttribute","value":"MODIFIED"},{"name":"pbi:IncrementalRefreshFilterByAttribute","value":"CREATED"}],"attributes":[{"name":"WORKORDERKEY","dataType":"double"},{"name":"SANDBOXKEY","dataType":"double"},{"name":"WOQUEUEKEY","dataType":"double"},{"name":"WORKORDER_NUMBER","dataType":"string"},{"name":"ORACLE_WORKORDER","dataType":"string"},{"name":"ORACLE_PROJECT","dataType":"string"},{"name":"ORG","dataType":"string"},{"name":"TYPE","dataType":"string"},{"name":"CREATED","dataType":"dateTime"},{"name":"COMPLETED","dataType":"dateTime"},{"name":"MODIFIED","dataType":"dateTime"},{"name":"WORKORDER_STATUS","dataType":"string"},{"name":"QUANTITY","dataType":"double"},{"name":"CURRENT_QUANTITY","dataType":"double"},{"name":"FLOW_NAME","dataType":"string"},{"name":"SN_LOT_NUMBER","dataType":"string"},{"name":"PARTNUMBERKEY","dataType":"double"},{"name":"REV","dataType":"string"},{"name":"SERIES_DATE","dataType":"dateTime"}],"partitions":[{"name":"IncrementalRefreshPolicyPartition-2002Q2","refreshTime":"2021-11-26T14:34:04.5849539+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2002Q2.csv?snapshot=2021-11-26T14%3A34%3A04.3724962Z","pbi:refreshBookmark":"1/1/0001 12:00:00 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2002-04-01T00:00:00","end":"2002-07-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2002Q3","refreshTime":"2021-11-26T14:31:10.9999006+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2002Q3.csv?snapshot=2021-11-26T14%3A31%3A10.0822121Z","pbi:refreshBookmark":"1/1/0001 12:00:00 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2002-07-01T00:00:00","end":"2002-10-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2002Q4","refreshTime":"2021-11-26T14:32:35.884401+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2002Q4.csv?snapshot=2021-11-26T14%3A32%3A35.6882326Z","pbi:refreshBookmark":"1/1/0001 12:00:00 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2002-10-01T00:00:00","end":"2003-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2003Q1","refreshTime":"2021-11-26T14:32:30.0527575+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2003Q1.csv?snapshot=2021-11-26T14%3A32%3A29.7366369Z","pbi:refreshBookmark":"1/1/0001 12:00:00 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2003-01-01T00:00:00","end":"2003-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2003Q2","refreshTime":"2021-11-26T14:31:35.8907116+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2003Q2.csv?snapshot=2021-11-26T14%3A31%3A15.5850629Z","pbi:refreshBookmark":"1/1/0001 12:00:00 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2003-04-01T00:00:00","end":"2003-07-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2003Q3","refreshTime":"2021-11-26T14:34:03.3821681+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2003Q3.csv?snapshot=2021-11-26T14%3A34%3A03.2461411Z","pbi:refreshBookmark":"1/1/0001 12:00:00 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2003-07-01T00:00:00","end":"2003-10-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2003Q4","refreshTime":"2021-11-26T14:32:46.5653167+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2003Q4.csv?snapshot=2021-11-26T14%3A32%3A46.2631829Z","pbi:refreshBookmark":"1/1/0001 12:00:00 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2003-10-01T00:00:00","end":"2004-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2004Q1","refreshTime":"2021-11-26T14:32:22.8370449+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2004Q1.csv?snapshot=2021-11-26T14%3A32%3A21.9241065Z","pbi:refreshBookmark":"1/1/0001 12:00:00 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2004-01-01T00:00:00","end":"2004-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2004Q2","refreshTime":"2021-11-26T14:32:09.783234+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2004Q2.csv?snapshot=2021-11-26T14%3A32%3A08.7496437Z","pbi:refreshBookmark":"1/1/0001 12:00:00 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2004-04-01T00:00:00","end":"2004-07-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2004Q3","refreshTime":"2021-11-26T14:32:43.7402508+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2004Q3.csv?snapshot=2021-11-26T14%3A32%3A43.6216940Z","pbi:refreshBookmark":"1/1/0001 12:00:00 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2004-07-01T00:00:00","end":"2004-10-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2004Q4","refreshTime":"2021-11-26T14:34:06.1022765+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2004Q4.csv?snapshot=2021-11-26T14%3A34%3A05.9645856Z","pbi:refreshBookmark":"1/1/0001 12:00:00 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2004-10-01T00:00:00","end":"2005-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2005Q1","refreshTime":"2021-11-26T14:34:01.7384257+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2005Q1.csv?snapshot=2021-11-26T14%3A34%3A01.6300659Z","pbi:refreshBookmark":"1/1/0001 12:00:00 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2005-01-01T00:00:00","end":"2005-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2005Q2","refreshTime":"2021-11-26T14:33:58.1253392+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2005Q2.csv?snapshot=2021-11-26T14%3A33%3A58.0261280Z","pbi:refreshBookmark":"1/1/0001 12:00:00 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2005-04-01T00:00:00","end":"2005-07-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2005Q3","refreshTime":"2021-11-26T14:34:00.0491613+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2005Q3.csv?snapshot=2021-11-26T14%3A33%3A59.8900613Z","pbi:refreshBookmark":"1/1/0001 12:00:00 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2005-07-01T00:00:00","end":"2005-10-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2005Q4","refreshTime":"2021-11-26T14:32:46.6593098+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2005Q4.csv?snapshot=2021-11-26T14%3A32%3A46.4100996Z","pbi:refreshBookmark":"1/1/0001 12:00:00 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2005-10-01T00:00:00","end":"2006-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2006Q1","refreshTime":"2021-11-26T14:31:40.0353195+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2006Q1.csv?snapshot=2021-11-26T14%3A31%3A15.9778381Z","pbi:refreshBookmark":"1/1/0001 12:00:00 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2006-01-01T00:00:00","end":"2006-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2006Q2","refreshTime":"2021-11-26T14:32:39.6699808+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2006Q2.csv?snapshot=2021-11-26T14%3A32%3A39.5380310Z","pbi:refreshBookmark":"1/1/0001 12:00:00 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2006-04-01T00:00:00","end":"2006-07-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2006Q3","refreshTime":"2021-11-26T14:33:56.2628663+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2006Q3.csv?snapshot=2021-11-26T14%3A33%3A56.1791850Z","pbi:refreshBookmark":"1/1/0001 12:00:00 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2006-07-01T00:00:00","end":"2006-10-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2006Q4","refreshTime":"2021-11-26T14:32:42.2678949+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2006Q4.csv?snapshot=2021-11-26T14%3A32%3A41.9776344Z","pbi:refreshBookmark":"1/1/0001 12:00:00 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2006-10-01T00:00:00","end":"2007-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2007Q1","refreshTime":"2021-11-26T14:34:04.913126+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2007Q1.csv?snapshot=2021-11-26T14%3A34%3A04.8132446Z","pbi:refreshBookmark":"1/1/0001 12:00:00 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2007-01-01T00:00:00","end":"2007-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2007Q2","refreshTime":"2021-11-26T14:31:44.9753073+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2007Q2.csv?snapshot=2021-11-26T14%3A31%3A20.7341168Z","pbi:refreshBookmark":"1/1/0001 12:00:00 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2007-04-01T00:00:00","end":"2007-07-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2007Q3","refreshTime":"2021-11-26T14:33:58.9533834+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2007Q3.csv?snapshot=2021-11-26T14%3A33%3A58.7906903Z","pbi:refreshBookmark":"1/1/0001 12:00:00 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2007-07-01T00:00:00","end":"2007-10-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2007Q4","refreshTime":"2021-11-26T14:31:15.113285+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2007Q4.csv?snapshot=2021-11-26T14%3A31%3A12.9275836Z","pbi:refreshBookmark":"1/1/0001 12:00:00 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2007-10-01T00:00:00","end":"2008-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2008Q1","refreshTime":"2021-11-26T14:32:45.9247437+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2008Q1.csv?snapshot=2021-11-26T14%3A32%3A45.6815156Z","pbi:refreshBookmark":"1/1/0001 12:00:00 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2008-01-01T00:00:00","end":"2008-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2008Q2","refreshTime":"2021-11-26T14:31:37.9560256+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2008Q2.csv?snapshot=2021-11-26T14%3A31%3A15.3781813Z","pbi:refreshBookmark":"1/1/0001 12:00:00 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2008-04-01T00:00:00","end":"2008-07-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2008Q3","refreshTime":"2021-11-26T14:32:37.828775+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2008Q3.csv?snapshot=2021-11-26T14%3A32%3A37.5481684Z","pbi:refreshBookmark":"1/1/0001 12:00:00 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2008-07-01T00:00:00","end":"2008-10-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2008Q4","refreshTime":"2021-11-26T14:32:20.818797+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2008Q4.csv?snapshot=2021-11-26T14%3A32%3A19.5734516Z","pbi:refreshBookmark":"1/1/0001 12:00:00 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2008-10-01T00:00:00","end":"2009-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2009Q1","refreshTime":"2021-11-26T14:33:53.7370396+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2009Q1.csv?snapshot=2021-11-26T14%3A33%3A53.6386395Z","pbi:refreshBookmark":"1/1/0001 12:00:00 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2009-01-01T00:00:00","end":"2009-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2009Q2","refreshTime":"2021-11-26T14:32:43.379111+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2009Q2.csv?snapshot=2021-11-26T14%3A32%3A43.2638987Z","pbi:refreshBookmark":"1/1/0001 12:00:00 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2009-04-01T00:00:00","end":"2009-07-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2009Q3","refreshTime":"2021-11-26T14:33:59.4851769+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2009Q3.csv?snapshot=2021-11-26T14%3A33%3A59.3023976Z","pbi:refreshBookmark":"1/1/0001 12:00:00 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2009-07-01T00:00:00","end":"2009-10-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2009Q4","refreshTime":"2021-11-26T14:34:05.1943199+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2009Q4.csv?snapshot=2021-11-26T14%3A34%3A05.0930843Z","pbi:refreshBookmark":"1/1/0001 12:00:00 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2009-10-01T00:00:00","end":"2010-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2010Q1","refreshTime":"2021-11-26T14:33:13.9320458+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2010Q1.csv?snapshot=2021-11-26T14%3A33%3A13.8404068Z","pbi:refreshBookmark":"1/1/0001 12:00:00 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2010-01-01T00:00:00","end":"2010-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2010Q2","refreshTime":"2021-11-26T14:32:36.7125145+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2010Q2.csv?snapshot=2021-11-26T14%3A32%3A36.4857763Z","pbi:refreshBookmark":"1/1/0001 12:00:00 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2010-04-01T00:00:00","end":"2010-07-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2010Q3","refreshTime":"2021-11-26T14:32:01.1664906+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2010Q3.csv?snapshot=2021-11-26T14%3A31%3A59.2770637Z","pbi:refreshBookmark":"1/1/0001 12:00:00 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2010-07-01T00:00:00","end":"2010-10-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2010Q4","refreshTime":"2021-11-26T14:32:40.138764+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2010Q4.csv?snapshot=2021-11-26T14%3A32%3A40.0207550Z","pbi:refreshBookmark":"1/1/0001 12:00:00 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2010-10-01T00:00:00","end":"2011-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2011Q1","refreshTime":"2021-11-26T14:33:57.34242+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2011Q1.csv?snapshot=2021-11-26T14%3A33%3A57.2425759Z","pbi:refreshBookmark":"1/1/0001 12:00:00 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2011-01-01T00:00:00","end":"2011-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2011Q2","refreshTime":"2021-11-26T14:31:46.8120101+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2011Q2.csv?snapshot=2021-11-26T14%3A31%3A19.4448544Z","pbi:refreshBookmark":"1/1/0001 12:00:00 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2011-04-01T00:00:00","end":"2011-07-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2011Q3","refreshTime":"2021-11-26T14:34:04.5224613+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2011Q3.csv?snapshot=2021-11-26T14%3A34%3A04.3804919Z","pbi:refreshBookmark":"1/1/0001 12:00:00 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2011-07-01T00:00:00","end":"2011-10-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2011Q4","refreshTime":"2021-11-26T14:34:03.1166059+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2011Q4.csv?snapshot=2021-11-26T14%3A34%3A03.0102758Z","pbi:refreshBookmark":"1/1/0001 12:00:00 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2011-10-01T00:00:00","end":"2012-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2012Q1","refreshTime":"2021-11-26T14:34:00.9866288+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2012Q1.csv?snapshot=2021-11-26T14%3A34%3A00.9044807Z","pbi:refreshBookmark":"1/1/0001 12:00:00 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2012-01-01T00:00:00","end":"2012-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2012Q2","refreshTime":"2021-11-26T14:34:03.4446926+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2012Q2.csv?snapshot=2021-11-26T14%3A34%3A03.2391454Z","pbi:refreshBookmark":"9/26/2012 6:00:46 PM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2012-04-01T00:00:00","end":"2012-07-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2012Q3","refreshTime":"2021-11-26T14:33:56.637831+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2012Q3.csv?snapshot=2021-11-26T14%3A33%3A56.4210463Z","pbi:refreshBookmark":"7/26/2021 5:15:50 PM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2012-07-01T00:00:00","end":"2012-10-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2012Q4","refreshTime":"2021-11-26T14:32:29.1151159+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2012Q4.csv?snapshot=2021-11-26T14%3A32%3A27.4119672Z","pbi:refreshBookmark":"7/26/2021 5:23:36 PM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2012-10-01T00:00:00","end":"2013-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2013Q1","refreshTime":"2021-11-26T14:32:35.2575687+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2013Q1.csv?snapshot=2021-11-26T14%3A32%3A34.1720995Z","pbi:refreshBookmark":"11/22/2021 7:14:57 PM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2013-01-01T00:00:00","end":"2013-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2013Q2","refreshTime":"2021-11-26T14:34:00.1741377+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2013Q2.csv?snapshot=2021-11-26T14%3A33%3A59.8410891Z","pbi:refreshBookmark":"10/6/2021 6:52:48 PM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2013-04-01T00:00:00","end":"2013-07-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2013Q3","refreshTime":"2021-11-26T14:34:03.5071719+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2013Q3.csv?snapshot=2021-11-26T14%3A34%3A03.2381457Z","pbi:refreshBookmark":"10/22/2021 5:45:30 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2013-07-01T00:00:00","end":"2013-10-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2013Q4","refreshTime":"2021-11-26T14:32:33.305426+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2013Q4.csv?snapshot=2021-11-26T14%3A32%3A32.8928322Z","pbi:refreshBookmark":"11/22/2021 7:15:16 PM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2013-10-01T00:00:00","end":"2014-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2014Q1","refreshTime":"2021-11-26T14:34:05.5693173+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2014Q1.csv?snapshot=2021-11-26T14%3A34%3A05.3079612Z","pbi:refreshBookmark":"11/23/2021 6:37:16 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2014-01-01T00:00:00","end":"2014-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2014Q2","refreshTime":"2021-11-26T14:34:27.1310265+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2014Q2.csv?snapshot=2021-11-26T14%3A34%3A26.7476941Z","pbi:refreshBookmark":"7/23/2021 3:06:05 PM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2014-04-01T00:00:00","end":"2014-07-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2014Q3","refreshTime":"2021-11-26T14:34:01.4884602+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2014Q3.csv?snapshot=2021-11-26T14%3A34%3A01.1553372Z","pbi:refreshBookmark":"11/19/2021 4:30:40 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2014-07-01T00:00:00","end":"2014-10-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2014Q4","refreshTime":"2021-11-26T14:34:01.9900316+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2014Q4.csv?snapshot=2021-11-26T14%3A34%3A01.6510537Z","pbi:refreshBookmark":"11/10/2021 9:29:35 PM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2014-10-01T00:00:00","end":"2015-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2015Q1","refreshTime":"2021-11-26T14:33:55.6205668+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2015Q1.csv?snapshot=2021-11-26T14%3A33%3A55.2227320Z","pbi:refreshBookmark":"11/23/2021 3:29:55 PM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2015-01-01T00:00:00","end":"2015-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2015Q2","refreshTime":"2021-11-26T14:34:02.3040539+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2015Q2.csv?snapshot=2021-11-26T14%3A34%3A01.8739262Z","pbi:refreshBookmark":"11/21/2021 1:35:41 PM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2015-04-01T00:00:00","end":"2015-07-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2015Q3","refreshTime":"2021-11-26T14:34:05.9147792+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2015Q3.csv?snapshot=2021-11-26T14%3A34%3A05.4188979Z","pbi:refreshBookmark":"11/25/2021 7:02:38 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2015-07-01T00:00:00","end":"2015-10-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2015Q4","refreshTime":"2021-11-26T14:34:00.7991956+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2015Q4.csv?snapshot=2021-11-26T14%3A34%3A00.4007689Z","pbi:refreshBookmark":"11/21/2021 1:34:32 PM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2015-10-01T00:00:00","end":"2016-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2016Q1","refreshTime":"2021-11-26T14:34:02.5696775+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2016Q1.csv?snapshot=2021-11-26T14%3A34%3A01.8779238Z","pbi:refreshBookmark":"11/25/2021 8:52:29 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2016-01-01T00:00:00","end":"2016-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2016Q2","refreshTime":"2021-11-26T14:34:05.7255722+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2016Q2.csv?snapshot=2021-11-26T14%3A34%3A04.6253520Z","pbi:refreshBookmark":"11/23/2021 5:24:30 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2016-04-01T00:00:00","end":"2016-07-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2016Q3","refreshTime":"2021-11-26T14:34:29.445123+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2016Q3.csv?snapshot=2021-11-26T14%3A34%3A28.2988068Z","pbi:refreshBookmark":"11/23/2021 2:43:00 PM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2016-07-01T00:00:00","end":"2016-10-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2016Q4","refreshTime":"2021-11-26T14:34:25.6295281+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2016Q4.csv?snapshot=2021-11-26T14%3A34%3A23.8603463Z","pbi:refreshBookmark":"11/24/2021 1:19:25 PM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2016-10-01T00:00:00","end":"2017-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2017Q1","refreshTime":"2022-01-01T00:02:08.1622603+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2017Q1.csv?snapshot=2022-01-01T00%3A02%3A06.1313634Z","pbi:refreshBookmark":"12/31/2021 11:48:54 PM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2017-01-01T00:00:00","end":"2017-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2017Q2","refreshTime":"2022-03-31T17:02:56.7604579+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2017Q2.csv?snapshot=2022-03-31T17%3A02%3A51.8257896Z","pbi:refreshBookmark":"3/31/2022 2:14:42 PM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2017-04-01T00:00:00","end":"2017-07-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2017Q3","refreshTime":"2022-06-10T21:01:46.926969+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2017Q3.csv?snapshot=2022-06-10T21%3A01%3A38.3708603Z","pbi:refreshBookmark":"6/10/2022 6:35:32 PM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2017-07-01T00:00:00","end":"2017-10-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2017Q4","refreshTime":"2022-06-13T09:01:53.7623218+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2017Q4.csv?snapshot=2022-06-13T09%3A01%3A50.4832636Z","pbi:refreshBookmark":"6/13/2022 7:52:26 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2017-10-01T00:00:00","end":"2018-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2018Q1","refreshTime":"2022-06-13T09:01:57.8378137+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2018Q1.csv?snapshot=2022-06-13T09%3A01%3A54.6688995Z","pbi:refreshBookmark":"6/13/2022 7:45:21 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2018-01-01T00:00:00","end":"2018-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2018Q2","refreshTime":"2022-06-13T05:05:13.7013099+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2018Q2.csv?snapshot=2022-06-13T05%3A05%3A02.7930146Z","pbi:refreshBookmark":"6/13/2022 1:30:29 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2018-04-01T00:00:00","end":"2018-07-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2018Q3","refreshTime":"2022-06-13T09:02:05.4366092+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2018Q3.csv?snapshot=2022-06-13T09%3A02%3A01.0932706Z","pbi:refreshBookmark":"6/13/2022 6:22:54 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2018-07-01T00:00:00","end":"2018-10-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2018Q4","refreshTime":"2022-06-13T09:02:06.0928375+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2018Q4.csv?snapshot=2022-06-13T09%3A02%3A02.0757162Z","pbi:refreshBookmark":"6/13/2022 6:23:13 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2018-10-01T00:00:00","end":"2019-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2019Q1","refreshTime":"2022-06-13T09:02:04.7490853+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2019Q1.csv?snapshot=2022-06-13T09%3A02%3A00.8184261Z","pbi:refreshBookmark":"6/13/2022 7:04:15 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2019-01-01T00:00:00","end":"2019-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2019Q2","refreshTime":"2022-06-13T09:02:08.4998338+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2019Q2.csv?snapshot=2022-06-13T09%3A02%3A05.3008946Z","pbi:refreshBookmark":"6/13/2022 8:21:34 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2019-04-01T00:00:00","end":"2019-07-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2019Q3","refreshTime":"2022-06-13T09:02:16.5970947+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2019Q3.csv?snapshot=2022-06-13T09%3A02%3A13.6591722Z","pbi:refreshBookmark":"6/13/2022 8:24:35 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2019-07-01T00:00:00","end":"2019-10-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2019Q4","refreshTime":"2022-06-10T17:00:52.3221866+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2019Q4.csv?snapshot=2022-06-10T17%3A00%3A48.3799675Z","pbi:refreshBookmark":"6/10/2022 1:02:42 PM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2019-10-01T00:00:00","end":"2020-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2020Q1","refreshTime":"2022-06-13T09:02:05.0459661+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2020Q1.csv?snapshot=2022-06-13T09%3A02%3A01.2711705Z","pbi:refreshBookmark":"6/13/2022 8:24:55 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2020-01-01T00:00:00","end":"2020-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2020Q2","refreshTime":"2022-06-13T09:02:11.0400469+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2020Q2.csv?snapshot=2022-06-13T09%3A02%3A07.7375175Z","pbi:refreshBookmark":"6/13/2022 8:00:08 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2020-04-01T00:00:00","end":"2020-07-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2020Q3","refreshTime":"2022-06-11T05:10:40.6945472+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2020Q3.csv?snapshot=2022-06-11T05%3A10%3A09.1949346Z","pbi:refreshBookmark":"6/11/2022 3:10:27 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2020-07-01T00:00:00","end":"2020-10-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2020Q4","refreshTime":"2022-06-13T09:02:06.2959915+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2020Q4.csv?snapshot=2022-06-13T09%3A02%3A01.9248010Z","pbi:refreshBookmark":"6/13/2022 8:01:01 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2020-10-01T00:00:00","end":"2021-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2021Q1","refreshTime":"2022-06-13T09:02:12.8838413+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2021Q1.csv?snapshot=2022-06-13T09%3A02%3A08.9918096Z","pbi:refreshBookmark":"6/13/2022 7:45:38 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2021-01-01T00:00:00","end":"2021-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2021Q2","refreshTime":"2022-06-13T09:02:19.0749452+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2021Q2.csv?snapshot=2022-06-13T09%3A02%3A15.4811429Z","pbi:refreshBookmark":"6/13/2022 7:45:07 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2021-04-01T00:00:00","end":"2021-07-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2021Q3","refreshTime":"2022-06-13T09:02:20.6999672+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2021Q3.csv?snapshot=2022-06-13T09%3A02%3A17.0442600Z","pbi:refreshBookmark":"6/13/2022 7:41:54 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2021-07-01T00:00:00","end":"2021-10-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2021Q4","refreshTime":"2022-06-13T09:02:21.6687477+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2021Q4.csv?snapshot=2022-06-13T09%3A02%3A18.4544633Z","pbi:refreshBookmark":"6/13/2022 8:12:55 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2021-10-01T00:00:00","end":"2022-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q1","refreshTime":"2022-06-13T09:02:22.246905+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2022Q1.csv?snapshot=2022-06-13T09%3A02%3A18.8122607Z","pbi:refreshBookmark":"6/13/2022 8:24:43 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-01-01T00:00:00","end":"2022-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q2","refreshTime":"2022-06-13T09:02:21.1843288+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/05868ed4-41fd-44aa-beb3-8aaae50eaa78/CUM_WORKORDERS/part-2022Q2.csv?snapshot=2022-06-13T09%3A02%3A17.9737349Z","pbi:refreshBookmark":"6/13/2022 8:25:06 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-01T00:00:00","end":"2022-07-01T00:00:00"}}]}]}