{"name":"CUMULUS_STATIC (Refreshed Daily)","description":"CUMULUS_STATIC (Refreshed Daily","version":"1.0","culture":"en-US","modifiedTime":"2021-10-28T18:23:00.6274388+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"Cumulus Assemblies":{"queryId":"193f2282-56d8-43ff-a5d4-9ca1d67c0895","queryName":"Cumulus Assemblies","loadEnabled":true},"CUM_SANDBOXES":{"queryId":"98f02816-6459-4c60-b526-d294a1c5dadc","queryName":"CUM_SANDBOXES","loadEnabled":true},"CUM_TAGS":{"queryId":"1c01da5e-9782-4139-840b-1127a1d99fa2","queryName":"CUM_TAGS","loadEnabled":true},"CUM_USERS":{"queryId":"2c75df8a-bede-420e-9385-3f65fd722e04","queryName":"CUM_USERS","loadEnabled":true},"Cumulus Components":{"queryId":"43e9e539-deec-4d1f-a556-2b5997a9d5d4","queryName":"Cumulus Components","loadEnabled":true},"Cumulus All Items":{"queryId":"1b42ef28-b5b9-4a7b-9fd2-35971fabb093","queryName":"Cumulus All Items","loadEnabled":true}},"document":"section Section1;\r\nshared #\"Cumulus Assemblies\" = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  #\"Navigation 1\" = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"CUMULUS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 3\" = #\"Navigation 2\"{[Name = \"CUM_PARTNUMBER_V\", Kind = \"View\"]}[Data],\r\n  #\"Filtered rows\" = Table.SelectRows(#\"Navigation 3\", each [TYPE] <> \"Component\")\r\nin\r\n  #\"Filtered rows\";\r\nshared CUM_SANDBOXES = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  #\"Navigation 1\" = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"CUMULUS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 3\" = #\"Navigation 2\"{[Name = \"CUM_SANDBOXES\", Kind = \"Table\"]}[Data]\r\nin\r\n  #\"Navigation 3\";\r\nshared CUM_TAGS = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  #\"Navigation 1\" = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"CUMULUS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 3\" = #\"Navigation 2\"{[Name = \"CUM_TAGS_V\", Kind = \"View\"]}[Data]\r\nin\r\n  #\"Navigation 3\";\r\nshared CUM_USERS = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  #\"Navigation 1\" = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"CUMULUS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 3\" = #\"Navigation 2\"{[Name = \"CUM_USERS\", Kind = \"Table\"]}[Data]\r\nin\r\n  #\"Navigation 3\";\r\nshared #\"Cumulus Components\" = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  #\"Navigation 1\" = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"CUMULUS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 3\" = #\"Navigation 2\"{[Name = \"CUM_PARTNUMBER_V\", Kind = \"View\"]}[Data],\r\n  #\"Filtered rows\" = Table.SelectRows(#\"Navigation 3\", each [TYPE] = \"Component\")\r\nin\r\n  #\"Filtered rows\";\r\nshared #\"Cumulus All Items\" = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  #\"Navigation 1\" = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"CUMULUS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 3\" = #\"Navigation 2\"{[Name = \"CUM_PARTNUMBER_V\", Kind = \"View\"]}[Data]\r\nin\r\n  #\"Navigation 3\";\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"Cumulus Assemblies","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Cumulus%20Assemblies.csv"},"attributes":[{"name":"PARTNUMBERKEY","dataType":"double"},{"name":"PART_DESCRIPTION","dataType":"string"},{"name":"SANDBOXKEY","dataType":"double"},{"name":"ACTIVE","dataType":"boolean"},{"name":"CREATE_DATE","dataType":"dateTime"},{"name":"MODIFY_DATE","dataType":"dateTime"},{"name":"TYPE","dataType":"string"},{"name":"PART_NUMBER","dataType":"string"},{"name":"WIP_DISPLAY","dataType":"string"},{"name":"AGILE_AUTO_SYNC","dataType":"boolean"},{"name":"AUTO_SERIALIZE","dataType":"boolean"},{"name":"WORK_CELL","dataType":"string"},{"name":"PRODUCTION_TYPE","dataType":"string"},{"name":"FLOW_NAME","dataType":"string"},{"name":"VARIABLE_COMP_QTY","dataType":"boolean"},{"name":"MAXIMUM_LOT_SIZE","dataType":"double"},{"name":"MAXIMUMN_BATCH_SIZE","dataType":"double"},{"name":"ORACLE_GENERIC_PN","dataType":"boolean"},{"name":"INVORG_CODE","dataType":"string"},{"name":"SANDBOX","dataType":"string"},{"name":"ITEM_ORG_KEY_CODE","dataType":"string"},{"name":"ITEM_SANDBOX_KEY_ID","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T06:30:37.9471915+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/4031a2e2-23d3-4344-aca9-6f45cdd49046/Cumulus%20Assemblies.csv?snapshot=2022-06-13T06%3A30%3A35.2383353Z"}]},{"$type":"LocalEntity","name":"CUM_SANDBOXES","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"CUM_SANDBOXES.csv"},"attributes":[{"name":"SANDBOXKEY","dataType":"double"},{"name":"BUSINESS_UNIT","dataType":"string"},{"name":"MAJOR_PRODUCT_FAMILY","dataType":"string"},{"name":"SANDBOX","dataType":"string"},{"name":"RESTRICTED","dataType":"boolean"},{"name":"ITAR","dataType":"boolean"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T06:30:28.233226+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/4031a2e2-23d3-4344-aca9-6f45cdd49046/CUM_SANDBOXES.csv?snapshot=2022-06-13T06%3A30%3A25.5029379Z"}]},{"$type":"LocalEntity","name":"CUM_TAGS","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"CUM_TAGS.csv"},"attributes":[{"name":"SANDBOXKEY","dataType":"double"},{"name":"PARTNUMBERKEY","dataType":"double"},{"name":"PART_NUMBER","dataType":"string"},{"name":"TAG","dataType":"string"},{"name":"ITEM_ORG_KEY_CODE","dataType":"string"},{"name":"ITEM_SANDBOX_KEY_ID","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T06:30:37.9003285+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/4031a2e2-23d3-4344-aca9-6f45cdd49046/CUM_TAGS.csv?snapshot=2022-06-13T06%3A30%3A34.5867109Z"}]},{"$type":"LocalEntity","name":"CUM_USERS","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"CUM_USERS.csv"},"attributes":[{"name":"USERKEY","dataType":"double"},{"name":"USER_STATUS","dataType":"string"},{"name":"FIRST_NAME","dataType":"string"},{"name":"LAST_NAME","dataType":"string"},{"name":"EMAIL","dataType":"string"},{"name":"GUID","dataType":"string"},{"name":"SANDBOXKEY","dataType":"double"},{"name":"SYS_ADMINISTRATOR","dataType":"boolean"},{"name":"ADMINISTRATOR","dataType":"boolean"},{"name":"BU_ADMINISTRATOR","dataType":"boolean"},{"name":"OPERATIONS","dataType":"boolean"},{"name":"ENGINEERING","dataType":"boolean"},{"name":"PLANNING","dataType":"boolean"},{"name":"PURCHASING","dataType":"boolean"},{"name":"SERVICE","dataType":"boolean"},{"name":"ENG_SUPPORT","dataType":"boolean"},{"name":"MFG_SUPPORT","dataType":"boolean"},{"name":"MANUFACTURING","dataType":"boolean"},{"name":"BASIC","dataType":"boolean"},{"name":"VIEW_DATA","dataType":"boolean"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T06:30:31.5907318+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/4031a2e2-23d3-4344-aca9-6f45cdd49046/CUM_USERS.csv?snapshot=2022-06-13T06%3A30%3A30.5130543Z"}]},{"$type":"LocalEntity","name":"Cumulus Components","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Cumulus%20Components.csv"},"attributes":[{"name":"PARTNUMBERKEY","dataType":"double"},{"name":"PART_DESCRIPTION","dataType":"string"},{"name":"SANDBOXKEY","dataType":"double"},{"name":"ACTIVE","dataType":"boolean"},{"name":"CREATE_DATE","dataType":"dateTime"},{"name":"MODIFY_DATE","dataType":"dateTime"},{"name":"TYPE","dataType":"string"},{"name":"PART_NUMBER","dataType":"string"},{"name":"WIP_DISPLAY","dataType":"string"},{"name":"AGILE_AUTO_SYNC","dataType":"boolean"},{"name":"AUTO_SERIALIZE","dataType":"boolean"},{"name":"WORK_CELL","dataType":"string"},{"name":"PRODUCTION_TYPE","dataType":"string"},{"name":"FLOW_NAME","dataType":"string"},{"name":"VARIABLE_COMP_QTY","dataType":"boolean"},{"name":"MAXIMUM_LOT_SIZE","dataType":"double"},{"name":"MAXIMUMN_BATCH_SIZE","dataType":"double"},{"name":"ORACLE_GENERIC_PN","dataType":"boolean"},{"name":"INVORG_CODE","dataType":"string"},{"name":"SANDBOX","dataType":"string"},{"name":"ITEM_ORG_KEY_CODE","dataType":"string"},{"name":"ITEM_SANDBOX_KEY_ID","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T06:30:30.6532642+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/4031a2e2-23d3-4344-aca9-6f45cdd49046/Cumulus%20Components.csv?snapshot=2022-06-13T06%3A30%3A29.8684250Z"}]},{"$type":"LocalEntity","name":"Cumulus All Items","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Cumulus%20All%20Items.csv"},"attributes":[{"name":"PARTNUMBERKEY","dataType":"double"},{"name":"PART_DESCRIPTION","dataType":"string"},{"name":"SANDBOXKEY","dataType":"double"},{"name":"ACTIVE","dataType":"boolean"},{"name":"CREATE_DATE","dataType":"dateTime"},{"name":"MODIFY_DATE","dataType":"dateTime"},{"name":"TYPE","dataType":"string"},{"name":"PART_NUMBER","dataType":"string"},{"name":"WIP_DISPLAY","dataType":"string"},{"name":"AGILE_AUTO_SYNC","dataType":"boolean"},{"name":"AUTO_SERIALIZE","dataType":"boolean"},{"name":"WORK_CELL","dataType":"string"},{"name":"PRODUCTION_TYPE","dataType":"string"},{"name":"FLOW_NAME","dataType":"string"},{"name":"VARIABLE_COMP_QTY","dataType":"boolean"},{"name":"MAXIMUM_LOT_SIZE","dataType":"double"},{"name":"MAXIMUMN_BATCH_SIZE","dataType":"double"},{"name":"ORACLE_GENERIC_PN","dataType":"boolean"},{"name":"INVORG_CODE","dataType":"string"},{"name":"SANDBOX","dataType":"string"},{"name":"ITEM_ORG_KEY_CODE","dataType":"string"},{"name":"ITEM_SANDBOX_KEY_ID","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T06:30:38.9575091+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/4031a2e2-23d3-4344-aca9-6f45cdd49046/Cumulus%20All%20Items.csv?snapshot=2022-06-13T06%3A30%3A35.4682039Z"}]}]}