{
    "name": "M2.0 DETAIL RELATED",
    "description": "",
    "version": "1.0",
    "culture": "en-US",
    "modifiedTime": "2021-11-29T01:28:25.2793966+00:00",
    "pbi:mashup": {
        "fastCombine": false,
        "allowNativeQueries": false,
        "queriesMetadata": {
            "Data Update Info": {
                "queryId": "4a8da3ba-970b-4a51-916c-01d06c9049e8",
                "queryName": "Data Update Info",
                "loadEnabled": true
            },
            "M20_DETAIL_SUMMARY": {
                "queryId": "b7268da3-3d93-4ff2-a792-ed4738d66b0a",
                "queryName": "M20_DETAIL_SUMMARY",
                "loadEnabled": true
            },
            "RangeEnd": {
                "queryId": "a2122e4a-e362-4bed-a31a-90e49140fc0c",
                "queryName": "RangeEnd"
            },
            "RangeStart": {
                "queryId": "c23f678a-5985-4093-8819-51a99d65b705",
                "queryName": "RangeStart"
            },
            "M20_DETAIL": {
                "queryId": "9aa6cb8d-a979-4736-b301-f4dc242428cb",
                "queryName": "M20_DETAIL",
                "loadEnabled": true
            }
        },
        "document": "section Section1;\r\n\r\nshared #\"Data Update Info\" = let\r\n    Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n    Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n    #\"Navigation 1\" = Navigation{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n    #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXREP_DATA_UPDATE_V\", Kind = \"View\"]}[Data],\r\n    #\"Filtered rows\" = Table.SelectRows(#\"Navigation 2\", each [TABLE_NAME] = \"XXCOH.XXCOH_M2_REPORT_TB\")\r\nin\r\n    #\"Filtered rows\";\r\n\r\nshared M20_DETAIL = let\r\n    Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n    Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n    #\"Navigation 1\" = Navigation{[Name = \"XXSF\", Kind = \"Schema\"]}[Data],\r\n    #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXREP_M20_DETAIL_TAB\", Kind = \"Table\"]}[Data]\r\nin\r\n    #\"Navigation 2\";\r\n\r\nshared M20_DETAIL_SUMMARY = let\r\n    Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n    Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n    #\"Navigation 1\" = Navigation{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n    #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXREP_M20_SUM_V\", Kind = \"View\"]}[Data],\r\n    #\"M20_DETAIL_SUMMARY-504552494F445F454E445F44415445-autogenerated_for_incremental_refresh\" = Table.SelectRows(#\"Navigation 2\", each DateTime.From([PERIOD_END_DATE]) >= RangeStart and DateTime.From([PERIOD_END_DATE]) < RangeEnd)\r\nin\r\n    #\"M20_DETAIL_SUMMARY-504552494F445F454E445F44415445-autogenerated_for_incremental_refresh\";\r\n\r\nshared RangeStart = let RangeStart = #datetime(0001,01,01,00,00,00) meta [IsParameterQuery=true, List={}, Type=\"DateTime\", IsParameterQueryRequired=true, Description=\"autogenerated_for_incremental_refresh\"] in RangeStart;\r\n\r\nshared RangeEnd = let RangeEnd = #datetime(9999,12,31,23,59,59) meta [IsParameterQuery=true, List={}, Type=\"DateTime\", IsParameterQueryRequired=true, Description=\"autogenerated_for_incremental_refresh\"] in RangeEnd;\r\n\r\n"
    },
    "annotations": [
        {
            "name": "pbi:QueryGroups",
            "value": "[]"
        }
    ],
    "entities": [
        {
            "$type": "LocalEntity",
            "name": "Data Update Info",
            "description": "",
            "pbi:refreshPolicy": {
                "$type": "FullRefreshPolicy",
                "location": "Data%20Update%20Info.csv"
            },
            "attributes": [
                {
                    "name": "TABLE_NAME",
                    "dataType": "string"
                },
                {
                    "name": "DATA_UPDATE_DATE",
                    "dataType": "dateTime"
                },
                {
                    "name": "DATA_UPDATE_DESC",
                    "dataType": "string"
                },
                {
                    "name": "DATA_FLOW_REFRESH_DATE",
                    "dataType": "dateTime"
                }
            ],
            "partitions": [
                {
                    "name": "FullRefreshPolicyPartition",
                    "refreshTime": "2022-05-16T00:01:10.1383276+00:00",
                    "location": "https://wabiwuscpcdsa.blob.core.windows.net:443/2d452af5-f7e7-4f69-ae39-df6aed9de30a/Data%20Update%20Info.csv?snapshot=2022-05-16T00%3A01%3A09.7420578Z"
                }
            ]
        },
        {
            "$type": "LocalEntity",
            "name": "M20_DETAIL_SUMMARY",
            "description": "",
            "pbi:refreshPolicy": {
                "$type": "IncrementalRefreshPolicy",
                "locationPattern": "M20_DETAIL_SUMMARY/part.csv",
                "rollingWindowGranularity": "quarter",
                "rollingWindowPeriods": 24,
                "incrementalGranularity": "quarter",
                "incrementalPeriods": 1
            },
            "annotations": [
                {
                    "name": "pbi:IncrementalRefreshDetectChangeAttribute"
                },
                {
                    "name": "pbi:IncrementalRefreshFilterByAttribute",
                    "value": "PERIOD_END_DATE"
                }
            ],
            "attributes": [
                {
                    "name": "ENTITY",
                    "dataType": "string"
                },
                {
                    "name": "DEPT",
                    "dataType": "string"
                },
                {
                    "name": "ACCT",
                    "dataType": "string"
                },
                {
                    "name": "PROJ",
                    "dataType": "string"
                },
                {
                    "name": "INTERCO",
                    "dataType": "string"
                },
                {
                    "name": "TRANSACTION_SOURCE",
                    "dataType": "string"
                },
                {
                    "name": "GL_PERIOD",
                    "dataType": "string"
                },
                {
                    "name": "ITEM_TBU",
                    "dataType": "string"
                },
                {
                    "name": "ITEM_PFC",
                    "dataType": "string"
                },
                {
                    "name": "ITEM_PRODUCT_LINE",
                    "dataType": "string"
                },
                {
                    "name": "ITEM_ORG_TBU",
                    "dataType": "string"
                },
                {
                    "name": "ITEM_ORG_PFC",
                    "dataType": "string"
                },
                {
                    "name": "M20_TBU",
                    "dataType": "string"
                },
                {
                    "name": "M20_PFC",
                    "dataType": "string"
                },
                {
                    "name": "HFM_PRODUCT",
                    "dataType": "string"
                },
                {
                    "name": "ALT_HFM_PRODUCT",
                    "dataType": "string"
                },
                {
                    "name": "SALES_SERVICE_CODE",
                    "dataType": "string"
                },
                {
                    "name": "CURRENCY_CODE",
                    "dataType": "string"
                },
                {
                    "name": "PERIOD_START_DATE",
                    "dataType": "dateTime"
                },
                {
                    "name": "PERIOD_END_DATE",
                    "dataType": "dateTime"
                },
                {
                    "name": "QUARTER_START_DATE",
                    "dataType": "dateTime"
                },
                {
                    "name": "QUARTER_END_DATE",
                    "dataType": "dateTime"
                },
                {
                    "name": "YEAR_START_DATE",
                    "dataType": "dateTime"
                },
                {
                    "name": "YEAR_END_DATE",
                    "dataType": "dateTime"
                },
                {
                    "name": "FISCAL_YEAR",
                    "dataType": "string"
                },
                {
                    "name": "QUARTER_NUM",
                    "dataType": "double"
                },
                {
                    "name": "FISCAL_QUARTER",
                    "dataType": "string"
                },
                {
                    "name": "FYFQ",
                    "dataType": "string"
                },
                {
                    "name": "M2_DETAIL_KEY",
                    "dataType": "string"
                },
                {
                    "name": "TRAN_QTY",
                    "dataType": "double"
                },
                {
                    "name": "ACCOUNTED_DR",
                    "dataType": "double"
                },
                {
                    "name": "ACCOUNTED_CR",
                    "dataType": "double"
                },
                {
                    "name": "NET_ACCOUNTED_AMT",
                    "dataType": "double"
                },
                {
                    "name": "USD_AMT",
                    "dataType": "double"
                },
                {
                    "name": "RECCORD_COUNT",
                    "dataType": "double"
                }
            ],
            "partitions": [
                {
                    "name": "IncrementalRefreshPolicyPartition-2016Q2",
                    "refreshTime": "2021-11-29T01:29:38.8485139+00:00",
                    "location": "https://wabiwuscpcdsa.blob.core.windows.net:443/2d452af5-f7e7-4f69-ae39-df6aed9de30a/M20_DETAIL_SUMMARY/part-2016Q2.csv?snapshot=2021-11-29T01%3A29%3A37.6868945Z",
                    "pbi:source": {
                        "$type": "RangePolicyPartitionSource",
                        "start": "2016-04-01T00:00:00",
                        "end": "2016-07-01T00:00:00"
                    }
                },
                {
                    "name": "IncrementalRefreshPolicyPartition-2016Q3",
                    "refreshTime": "2021-11-29T01:29:31.0018552+00:00",
                    "location": "https://wabiwuscpcdsa.blob.core.windows.net:443/2d452af5-f7e7-4f69-ae39-df6aed9de30a/M20_DETAIL_SUMMARY/part-2016Q3.csv?snapshot=2021-11-29T01%3A29%3A30.7658828Z",
                    "pbi:source": {
                        "$type": "RangePolicyPartitionSource",
                        "start": "2016-07-01T00:00:00",
                        "end": "2016-10-01T00:00:00"
                    }
                },
                {
                    "name": "IncrementalRefreshPolicyPartition-2016Q4",
                    "refreshTime": "2021-11-29T01:30:34.9741721+00:00",
                    "location": "https://wabiwuscpcdsa.blob.core.windows.net:443/2d452af5-f7e7-4f69-ae39-df6aed9de30a/M20_DETAIL_SUMMARY/part-2016Q4.csv?snapshot=2021-11-29T01%3A30%3A34.8459578Z",
                    "pbi:source": {
                        "$type": "RangePolicyPartitionSource",
                        "start": "2016-10-01T00:00:00",
                        "end": "2017-01-01T00:00:00"
                    }
                },
                {
                    "name": "IncrementalRefreshPolicyPartition-2017Q1",
                    "refreshTime": "2021-11-29T01:31:40.0713959+00:00",
                    "location": "https://wabiwuscpcdsa.blob.core.windows.net:443/2d452af5-f7e7-4f69-ae39-df6aed9de30a/M20_DETAIL_SUMMARY/part-2017Q1.csv?snapshot=2021-11-29T01%3A31%3A39.8644953Z",
                    "pbi:source": {
                        "$type": "RangePolicyPartitionSource",
                        "start": "2017-01-01T00:00:00",
                        "end": "2017-04-01T00:00:00"
                    }
                },
                {
                    "name": "IncrementalRefreshPolicyPartition-2017Q2",
                    "refreshTime": "2021-11-29T01:30:34.9116853+00:00",
                    "location": "https://wabiwuscpcdsa.blob.core.windows.net:443/2d452af5-f7e7-4f69-ae39-df6aed9de30a/M20_DETAIL_SUMMARY/part-2017Q2.csv?snapshot=2021-11-29T01%3A30%3A34.7849922Z",
                    "pbi:source": {
                        "$type": "RangePolicyPartitionSource",
                        "start": "2017-04-01T00:00:00",
                        "end": "2017-07-01T00:00:00"
                    }
                },
                {
                    "name": "IncrementalRefreshPolicyPartition-2017Q3",
                    "refreshTime": "2021-11-29T01:30:49.0027845+00:00",
                    "location": "https://wabiwuscpcdsa.blob.core.windows.net:443/2d452af5-f7e7-4f69-ae39-df6aed9de30a/M20_DETAIL_SUMMARY/part-2017Q3.csv?snapshot=2021-11-29T01%3A30%3A48.8848679Z",
                    "pbi:source": {
                        "$type": "RangePolicyPartitionSource",
                        "start": "2017-07-01T00:00:00",
                        "end": "2017-10-01T00:00:00"
                    }
                },
                {
                    "name": "IncrementalRefreshPolicyPartition-2017Q4",
                    "refreshTime": "2021-11-29T01:31:53.2618097+00:00",
                    "location": "https://wabiwuscpcdsa.blob.core.windows.net:443/2d452af5-f7e7-4f69-ae39-df6aed9de30a/M20_DETAIL_SUMMARY/part-2017Q4.csv?snapshot=2021-11-29T01%3A31%3A53.1208573Z",
                    "pbi:source": {
                        "$type": "RangePolicyPartitionSource",
                        "start": "2017-10-01T00:00:00",
                        "end": "2018-01-01T00:00:00"
                    }
                },
                {
                    "name": "IncrementalRefreshPolicyPartition-2018Q1",
                    "refreshTime": "2021-11-29T01:31:18.427656+00:00",
                    "location": "https://wabiwuscpcdsa.blob.core.windows.net:443/2d452af5-f7e7-4f69-ae39-df6aed9de30a/M20_DETAIL_SUMMARY/part-2018Q1.csv?snapshot=2021-11-29T01%3A31%3A18.1520039Z",
                    "pbi:source": {
                        "$type": "RangePolicyPartitionSource",
                        "start": "2018-01-01T00:00:00",
                        "end": "2018-04-01T00:00:00"
                    }
                },
                {
                    "name": "IncrementalRefreshPolicyPartition-2018Q2",
                    "refreshTime": "2021-11-29T01:29:48.523952+00:00",
                    "location": "https://wabiwuscpcdsa.blob.core.windows.net:443/2d452af5-f7e7-4f69-ae39-df6aed9de30a/M20_DETAIL_SUMMARY/part-2018Q2.csv?snapshot=2021-11-29T01%3A29%3A48.4087158Z",
                    "pbi:source": {
                        "$type": "RangePolicyPartitionSource",
                        "start": "2018-04-01T00:00:00",
                        "end": "2018-07-01T00:00:00"
                    }
                },
                {
                    "name": "IncrementalRefreshPolicyPartition-2018Q3",
                    "refreshTime": "2021-11-29T01:30:10.4894763+00:00",
                    "location": "https://wabiwuscpcdsa.blob.core.windows.net:443/2d452af5-f7e7-4f69-ae39-df6aed9de30a/M20_DETAIL_SUMMARY/part-2018Q3.csv?snapshot=2021-11-29T01%3A30%3A10.4040409Z",
                    "pbi:source": {
                        "$type": "RangePolicyPartitionSource",
                        "start": "2018-07-01T00:00:00",
                        "end": "2018-10-01T00:00:00"
                    }
                },
                {
                    "name": "IncrementalRefreshPolicyPartition-2018Q4",
                    "refreshTime": "2021-11-29T01:29:45.4606255+00:00",
                    "location": "https://wabiwuscpcdsa.blob.core.windows.net:443/2d452af5-f7e7-4f69-ae39-df6aed9de30a/M20_DETAIL_SUMMARY/part-2018Q4.csv?snapshot=2021-11-29T01%3A29%3A40.7181480Z",
                    "pbi:source": {
                        "$type": "RangePolicyPartitionSource",
                        "start": "2018-10-01T00:00:00",
                        "end": "2019-01-01T00:00:00"
                    }
                },
                {
                    "name": "IncrementalRefreshPolicyPartition-2019Q1",
                    "refreshTime": "2021-11-29T01:30:53.3175509+00:00",
                    "location": "https://wabiwuscpcdsa.blob.core.windows.net:443/2d452af5-f7e7-4f69-ae39-df6aed9de30a/M20_DETAIL_SUMMARY/part-2019Q1.csv?snapshot=2021-11-29T01%3A30%3A48.6819842Z",
                    "pbi:source": {
                        "$type": "RangePolicyPartitionSource",
                        "start": "2019-01-01T00:00:00",
                        "end": "2019-04-01T00:00:00"
                    }
                },
                {
                    "name": "IncrementalRefreshPolicyPartition-2019Q2",
                    "refreshTime": "2021-11-29T01:32:22.29087+00:00",
                    "location": "https://wabiwuscpcdsa.blob.core.windows.net:443/2d452af5-f7e7-4f69-ae39-df6aed9de30a/M20_DETAIL_SUMMARY/part-2019Q2.csv?snapshot=2021-11-29T01%3A32%3A17.2779393Z",
                    "pbi:source": {
                        "$type": "RangePolicyPartitionSource",
                        "start": "2019-04-01T00:00:00",
                        "end": "2019-07-01T00:00:00"
                    }
                },
                {
                    "name": "IncrementalRefreshPolicyPartition-2019Q3",
                    "refreshTime": "2021-11-29T01:31:58.5346992+00:00",
                    "location": "https://wabiwuscpcdsa.blob.core.windows.net:443/2d452af5-f7e7-4f69-ae39-df6aed9de30a/M20_DETAIL_SUMMARY/part-2019Q3.csv?snapshot=2021-11-29T01%3A31%3A52.9699453Z",
                    "pbi:source": {
                        "$type": "RangePolicyPartitionSource",
                        "start": "2019-07-01T00:00:00",
                        "end": "2019-10-01T00:00:00"
                    }
                },
                {
                    "name": "IncrementalRefreshPolicyPartition-2019Q4",
                    "refreshTime": "2021-11-29T01:31:49.9081084+00:00",
                    "location": "https://wabiwuscpcdsa.blob.core.windows.net:443/2d452af5-f7e7-4f69-ae39-df6aed9de30a/M20_DETAIL_SUMMARY/part-2019Q4.csv?snapshot=2021-11-29T01%3A31%3A43.8382057Z",
                    "pbi:source": {
                        "$type": "RangePolicyPartitionSource",
                        "start": "2019-10-01T00:00:00",
                        "end": "2020-01-01T00:00:00"
                    }
                },
                {
                    "name": "IncrementalRefreshPolicyPartition-2020Q1",
                    "refreshTime": "2021-11-29T01:31:14.8962443+00:00",
                    "location": "https://wabiwuscpcdsa.blob.core.windows.net:443/2d452af5-f7e7-4f69-ae39-df6aed9de30a/M20_DETAIL_SUMMARY/part-2020Q1.csv?snapshot=2021-11-29T01%3A31%3A11.6017785Z",
                    "pbi:source": {
                        "$type": "RangePolicyPartitionSource",
                        "start": "2020-01-01T00:00:00",
                        "end": "2020-04-01T00:00:00"
                    }
                },
                {
                    "name": "IncrementalRefreshPolicyPartition-2020Q2",
                    "refreshTime": "2021-11-29T01:30:40.3889268+00:00",
                    "location": "https://wabiwuscpcdsa.blob.core.windows.net:443/2d452af5-f7e7-4f69-ae39-df6aed9de30a/M20_DETAIL_SUMMARY/part-2020Q2.csv?snapshot=2021-11-29T01%3A30%3A35.5945255Z",
                    "pbi:source": {
                        "$type": "RangePolicyPartitionSource",
                        "start": "2020-04-01T00:00:00",
                        "end": "2020-07-01T00:00:00"
                    }
                },
                {
                    "name": "IncrementalRefreshPolicyPartition-2020Q3",
                    "refreshTime": "2021-11-29T01:30:13.5889809+00:00",
                    "location": "https://wabiwuscpcdsa.blob.core.windows.net:443/2d452af5-f7e7-4f69-ae39-df6aed9de30a/M20_DETAIL_SUMMARY/part-2020Q3.csv?snapshot=2021-11-29T01%3A30%3A09.2237219Z",
                    "pbi:source": {
                        "$type": "RangePolicyPartitionSource",
                        "start": "2020-07-01T00:00:00",
                        "end": "2020-10-01T00:00:00"
                    }
                },
                {
                    "name": "IncrementalRefreshPolicyPartition-2020Q4",
                    "refreshTime": "2021-11-29T01:31:36.004383+00:00",
                    "location": "https://wabiwuscpcdsa.blob.core.windows.net:443/2d452af5-f7e7-4f69-ae39-df6aed9de30a/M20_DETAIL_SUMMARY/part-2020Q4.csv?snapshot=2021-11-29T01%3A31%3A29.5264513Z",
                    "pbi:source": {
                        "$type": "RangePolicyPartitionSource",
                        "start": "2020-10-01T00:00:00",
                        "end": "2021-01-01T00:00:00"
                    }
                },
                {
                    "name": "IncrementalRefreshPolicyPartition-2021Q1",
                    "refreshTime": "2021-11-29T01:31:16.9573141+00:00",
                    "location": "https://wabiwuscpcdsa.blob.core.windows.net:443/2d452af5-f7e7-4f69-ae39-df6aed9de30a/M20_DETAIL_SUMMARY/part-2021Q1.csv?snapshot=2021-11-29T01%3A31%3A11.4698538Z",
                    "pbi:source": {
                        "$type": "RangePolicyPartitionSource",
                        "start": "2021-01-01T00:00:00",
                        "end": "2021-04-01T00:00:00"
                    }
                },
                {
                    "name": "IncrementalRefreshPolicyPartition-2021Q2",
                    "refreshTime": "2021-11-29T01:32:12.1208567+00:00",
                    "location": "https://wabiwuscpcdsa.blob.core.windows.net:443/2d452af5-f7e7-4f69-ae39-df6aed9de30a/M20_DETAIL_SUMMARY/part-2021Q2.csv?snapshot=2021-11-29T01%3A32%3A05.3857921Z",
                    "pbi:source": {
                        "$type": "RangePolicyPartitionSource",
                        "start": "2021-04-01T00:00:00",
                        "end": "2021-07-01T00:00:00"
                    }
                },
                {
                    "name": "IncrementalRefreshPolicyPartition-2021Q3",
                    "refreshTime": "2021-11-29T01:32:23.1985286+00:00",
                    "location": "https://wabiwuscpcdsa.blob.core.windows.net:443/2d452af5-f7e7-4f69-ae39-df6aed9de30a/M20_DETAIL_SUMMARY/part-2021Q3.csv?snapshot=2021-11-29T01%3A32%3A17.4598343Z",
                    "pbi:source": {
                        "$type": "RangePolicyPartitionSource",
                        "start": "2021-07-01T00:00:00",
                        "end": "2021-10-01T00:00:00"
                    }
                },
                {
                    "name": "IncrementalRefreshPolicyPartition-2021Q4",
                    "refreshTime": "2022-01-02T17:31:38.0061064+00:00",
                    "location": "https://wabiwuscpcdsa.blob.core.windows.net:443/2d452af5-f7e7-4f69-ae39-df6aed9de30a/M20_DETAIL_SUMMARY/part-2021Q4.csv?snapshot=2022-01-02T17%3A31%3A33.0610997Z",
                    "pbi:source": {
                        "$type": "RangePolicyPartitionSource",
                        "start": "2021-10-01T00:00:00",
                        "end": "2022-01-01T00:00:00"
                    }
                },
                {
                    "name": "IncrementalRefreshPolicyPartition-2022Q1",
                    "refreshTime": "2022-04-03T16:30:54.7741826+00:00",
                    "location": "https://wabiwuscpcdsa.blob.core.windows.net:443/2d452af5-f7e7-4f69-ae39-df6aed9de30a/M20_DETAIL_SUMMARY/part-2022Q1.csv?snapshot=2022-04-03T16%3A30%3A45.8100140Z",
                    "pbi:source": {
                        "$type": "RangePolicyPartitionSource",
                        "start": "2022-01-01T00:00:00",
                        "end": "2022-04-01T00:00:00"
                    }
                },
                {
                    "name": "IncrementalRefreshPolicyPartition-2022Q2",
                    "refreshTime": "2022-05-16T00:01:43.4433476+00:00",
                    "location": "https://wabiwuscpcdsa.blob.core.windows.net:443/2d452af5-f7e7-4f69-ae39-df6aed9de30a/M20_DETAIL_SUMMARY/part-2022Q2.csv?snapshot=2022-05-16T00%3A01%3A37.9742373Z",
                    "pbi:source": {
                        "$type": "RangePolicyPartitionSource",
                        "start": "2022-04-01T00:00:00",
                        "end": "2022-07-01T00:00:00"
                    }
                }
            ]
        },
        {
            "$type": "LocalEntity",
            "name": "M20_DETAIL",
            "description": "",
            "pbi:refreshPolicy": {
                "$type": "FullRefreshPolicy",
                "location": "M20_DETAIL.csv"
            },
            "attributes": [
                {
                    "name": "ENTITY",
                    "dataType": "string"
                },
                {
                    "name": "DEPT",
                    "dataType": "string"
                },
                {
                    "name": "ACCT",
                    "dataType": "string"
                },
                {
                    "name": "PROJ",
                    "dataType": "string"
                },
                {
                    "name": "INTERCO",
                    "dataType": "string"
                },
                {
                    "name": "ACCOUNT_DESC",
                    "dataType": "string"
                },
                {
                    "name": "GL_PERIOD",
                    "dataType": "string"
                },
                {
                    "name": "PERIOD_START_DATE",
                    "dataType": "dateTime"
                },
                {
                    "name": "PERIOD_END_DATE",
                    "dataType": "dateTime"
                },
                {
                    "name": "ITEM_NUMBER",
                    "dataType": "string"
                },
                {
                    "name": "ITEM_DESCRIPTION",
                    "dataType": "string"
                },
                {
                    "name": "TRANSACTION_SOURCE",
                    "dataType": "string"
                },
                {
                    "name": "TRANS_DATE",
                    "dataType": "dateTime"
                },
                {
                    "name": "ACCOUNTED_DR",
                    "dataType": "double"
                },
                {
                    "name": "ACCOUNTED_CR",
                    "dataType": "double"
                },
                {
                    "name": "NET_ACCOUNTED_AMT",
                    "dataType": "double"
                },
                {
                    "name": "ACCOUNTED_NET_USD",
                    "dataType": "double"
                },
                {
                    "name": "CURRENCY_CODE",
                    "dataType": "string"
                },
                {
                    "name": "VENDOR_NAME",
                    "dataType": "string"
                },
                {
                    "name": "VENDOR_NUMBER",
                    "dataType": "string"
                },
                {
                    "name": "ORDER_LINE_TYPE",
                    "dataType": "string"
                },
                {
                    "name": "ORDER_NUMBER",
                    "dataType": "double"
                },
                {
                    "name": "TRX_TYPE_NAME",
                    "dataType": "string"
                },
                {
                    "name": "ORDER_TYPE",
                    "dataType": "string"
                },
                {
                    "name": "SALES_SERVICE_CODE",
                    "dataType": "string"
                },
                {
                    "name": "TRAN_QTY",
                    "dataType": "double"
                },
                {
                    "name": "TRX_NUMBER",
                    "dataType": "string"
                },
                {
                    "name": "EXTERNAL_SO_NUMBER",
                    "dataType": "double"
                },
                {
                    "name": "EXTERNAL_CUSTOMER",
                    "dataType": "string"
                },
                {
                    "name": "WIP_JOB_NO",
                    "dataType": "string"
                },
                {
                    "name": "PERIOD_YEAR",
                    "dataType": "double"
                },
                {
                    "name": "PO_NUMBER",
                    "dataType": "string"
                },
                {
                    "name": "JE_NAME",
                    "dataType": "string"
                },
                {
                    "name": "JE_LINE_NUM",
                    "dataType": "double"
                },
                {
                    "name": "INTERNAL_PO_NUMBER",
                    "dataType": "double"
                },
                {
                    "name": "COMMODITY_CATEGORY",
                    "dataType": "string"
                },
                {
                    "name": "FORECAST_CATEGORY",
                    "dataType": "string"
                },
                {
                    "name": "SUBINVENTORY_CODE",
                    "dataType": "string"
                },
                {
                    "name": "ACCOUNT_ALIAS_NAME",
                    "dataType": "string"
                },
                {
                    "name": "PLANNER_CODE",
                    "dataType": "string"
                },
                {
                    "name": "BUYER_ID",
                    "dataType": "double"
                },
                {
                    "name": "ACCOUNTING_LINE_TYPE",
                    "dataType": "string"
                },
                {
                    "name": "TRAN_SOURCE_NAME",
                    "dataType": "string"
                },
                {
                    "name": "MATERAIL_TRAN_REFERENCE",
                    "dataType": "string"
                },
                {
                    "name": "JE_LINE_DESCRIPTION",
                    "dataType": "string"
                },
                {
                    "name": "CREATION_DATE",
                    "dataType": "dateTime"
                },
                {
                    "name": "WIP_ACCOUNTING_CLASS",
                    "dataType": "string"
                },
                {
                    "name": "ALLOCATION_PERCENT",
                    "dataType": "double"
                },
                {
                    "name": "MARKET_CODE",
                    "dataType": "string"
                },
                {
                    "name": "ITEM_TBU",
                    "dataType": "string"
                },
                {
                    "name": "ITEM_PFC",
                    "dataType": "string"
                },
                {
                    "name": "ITEM_PRODUCT_LINE",
                    "dataType": "string"
                },
                {
                    "name": "ITEM_ORG_TBU",
                    "dataType": "string"
                },
                {
                    "name": "ITEM_ORG_PFC",
                    "dataType": "string"
                },
                {
                    "name": "M20_TBU",
                    "dataType": "string"
                },
                {
                    "name": "M20_PFC",
                    "dataType": "string"
                },
                {
                    "name": "HFM_PRODUCT",
                    "dataType": "string"
                },
                {
                    "name": "ALT_HFM_PRODUCT",
                    "dataType": "string"
                },
                {
                    "name": "COST_ELEMENT",
                    "dataType": "string"
                },
                {
                    "name": "TRANS_DIFF_START",
                    "dataType": "double"
                },
                {
                    "name": "MONTH_DAYS",
                    "dataType": "double"
                },
                {
                    "name": "REV_TRANS_DATE",
                    "dataType": "dateTime"
                },
                {
                    "name": "M2_DETAIL_KEY",
                    "dataType": "string"
                }
            ],
            "partitions": [
                {
                    "name": "FullRefreshPolicyPartition",
                    "refreshTime": "2022-05-16T00:52:55.0766115+00:00",
                    "location": "https://wabiwuscpcdsa.blob.core.windows.net:443/2d452af5-f7e7-4f69-ae39-df6aed9de30a/M20_DETAIL.csv?snapshot=2022-05-16T00%3A49%3A57.5367790Z"
                }
            ]
        }
    ]
}