{"name":"AP Invoice Payments","description":"","version":"1.0","culture":"en-US","modifiedTime":"2021-11-26T17:10:52.3410372+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"Data Update Info":{"queryId":"4f1800b0-5bd3-4f50-94d5-10377b32c0cd","queryName":"Data Update Info","loadEnabled":true},"XXREP_AP_PAY_INVOICE_TAB":{"queryId":"7ae791b9-1db0-40ea-a288-b78315075828","queryName":"XXREP_AP_PAY_INVOICE_TAB","loadEnabled":true},"RangeEnd":{"queryId":"70371f96-acfe-4949-a2be-d7f115dbdb05","queryName":"RangeEnd"},"RangeStart":{"queryId":"30b87583-77a4-469e-83fb-91ddbced7d84","queryName":"RangeStart"}},"document":"section Section1;\r\n\r\nshared #\"Data Update Info\" = let\r\n    Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n    Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n    #\"Navigation 1\" = Navigation{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n    #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXREP_DATA_UPDATE_V\", Kind = \"View\"]}[Data],\r\n    #\"Filtered rows\" = Table.SelectRows(#\"Navigation 2\", each [TABLE_NAME] = \"XXSF.XXREP_AP_PAY_INVOICE_TAB\")\r\nin\r\n    #\"Filtered rows\";\r\n\r\nshared XXREP_AP_PAY_INVOICE_TAB = let\r\n    Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n    Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n    #\"Navigation 1\" = Navigation{[Name = \"XXSF\", Kind = \"Schema\"]}[Data],\r\n    #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXREP_AP_PAY_INVOICE_TAB\", Kind = \"Table\"]}[Data],\r\n    #\"XXREP_AP_PAY_INVOICE_TAB-504552494F445F454E445F44415445-autogenerated_for_incremental_refresh\" = Table.SelectRows(#\"Navigation 2\", each DateTime.From([PERIOD_END_DATE]) >= RangeStart and DateTime.From([PERIOD_END_DATE]) < RangeEnd)\r\nin\r\n    #\"XXREP_AP_PAY_INVOICE_TAB-504552494F445F454E445F44415445-autogenerated_for_incremental_refresh\";\r\n\r\nshared RangeStart = let RangeStart = #datetime(0001,01,01,00,00,00) meta [IsParameterQuery=true, List={}, Type=\"DateTime\", IsParameterQueryRequired=true, Description=\"autogenerated_for_incremental_refresh\"] in RangeStart;\r\n\r\nshared RangeEnd = let RangeEnd = #datetime(9999,12,31,23,59,59) meta [IsParameterQuery=true, List={}, Type=\"DateTime\", IsParameterQueryRequired=true, Description=\"autogenerated_for_incremental_refresh\"] in RangeEnd;\r\n\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"Data Update Info","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Data%20Update%20Info.csv"},"attributes":[{"name":"TABLE_NAME","dataType":"string"},{"name":"DATA_UPDATE_DATE","dataType":"dateTime"},{"name":"DATA_UPDATE_DESC","dataType":"string"},{"name":"DATA_FLOW_REFRESH_DATE","dataType":"dateTime"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-15T22:01:14.8998431+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/b5e0daf7-153a-43e2-85aa-376ed68f93e9/Data%20Update%20Info.csv?snapshot=2022-05-15T22%3A01%3A13.7430739Z"}]},{"$type":"LocalEntity","name":"XXREP_AP_PAY_INVOICE_TAB","description":"","pbi:refreshPolicy":{"$type":"IncrementalRefreshPolicy","locationPattern":"XXREP_AP_PAY_INVOICE_TAB/part.csv","rollingWindowGranularity":"quarter","rollingWindowPeriods":12,"incrementalGranularity":"quarter","incrementalPeriods":1},"annotations":[{"name":"pbi:IncrementalRefreshDetectChangeAttribute"},{"name":"pbi:IncrementalRefreshFilterByAttribute","value":"PERIOD_END_DATE"}],"attributes":[{"name":"VENDOR_NO","dataType":"string"},{"name":"VENDOR_NAME","dataType":"string"},{"name":"VENDOR_SITE_CODE","dataType":"string"},{"name":"CURRENCY_CODE","dataType":"string"},{"name":"CHECK_NUMBER","dataType":"double"},{"name":"AMOUNT","dataType":"double"},{"name":"CHECK_DATE","dataType":"dateTime"},{"name":"CHECK_STATUS","dataType":"string"},{"name":"VOID_DATE","dataType":"dateTime"},{"name":"CHECK_AMOUNT","dataType":"double"},{"name":"INVOICE_NUM","dataType":"string"},{"name":"INV_CURRENCY_CODE","dataType":"string"},{"name":"INVOICE_TYPE_LOOKUP_CODE","dataType":"string"},{"name":"INVOICE_DATE","dataType":"dateTime"},{"name":"INVOICE_AMOUNT","dataType":"double"},{"name":"APPROVED_AMOUNT","dataType":"double"},{"name":"PERIOD_NAME","dataType":"string"},{"name":"PAYMENT_METHOD","dataType":"string"},{"name":"GL_ENTITY","dataType":"string"},{"name":"GL_DEPT","dataType":"string"},{"name":"GL_ACCOUNT","dataType":"string"},{"name":"GL_PROJECT","dataType":"string"},{"name":"GL_INTERCO","dataType":"string"},{"name":"GL_TBD","dataType":"string"},{"name":"FEDERAL_REPORTABLE_FLAG","dataType":"string"},{"name":"TAX_REPORTING_NAME","dataType":"string"},{"name":"CHECK_ID","dataType":"double"},{"name":"INVOICE_ID","dataType":"double"},{"name":"VENDOR_ID","dataType":"double"},{"name":"VENDOR_SITE_ID","dataType":"double"},{"name":"ORG_ID","dataType":"double"},{"name":"OPERATING_UNIT","dataType":"string"},{"name":"FUNCTIONAL_CURRENCY","dataType":"string"},{"name":"DISCOUNT_LOST","dataType":"double"},{"name":"DISCOUNT_TAKEN","dataType":"double"},{"name":"TERM_NAME","dataType":"string"},{"name":"DISCOUNT_VENDOR","dataType":"string"},{"name":"INVOICE_BASE_AMOUNT","dataType":"double"},{"name":"PAYMENT_BASE_AMOUNT","dataType":"double"},{"name":"HREF_VOUCHER_NUMBER","dataType":"string"},{"name":"VOUCHER_NUMBER","dataType":"string"},{"name":"SET_OF_BOOKS_ID","dataType":"double"},{"name":"CHECKRUN_NAME","dataType":"string"},{"name":"INTERNAL_VENDOR","dataType":"string"},{"name":"EXCL_NETTING_CHECKBOX","dataType":"string"},{"name":"DUE_DATE","dataType":"dateTime"},{"name":"INVOICE_CREATION_DATE","dataType":"dateTime"},{"name":"IS_EXCEPTION_FLAG","dataType":"string"},{"name":"EXCEPTION_NOTES","dataType":"string"},{"name":"INVOICE_FUNCTIONAL_AMOUNT","dataType":"double"},{"name":"INVOICE_USD_AMOUNT","dataType":"double"},{"name":"PAYMENT_FUNCTIONAL_AMOUNT","dataType":"double"},{"name":"PAYMENT_USD_AMOUNT","dataType":"double"},{"name":"PERIOD_START_DATE","dataType":"dateTime"},{"name":"PERIOD_END_DATE","dataType":"dateTime"},{"name":"PERIOD_YEAR","dataType":"double"},{"name":"QUARTER_NUM","dataType":"double"},{"name":"INV_TO_PAY_DAYS","dataType":"double"},{"name":"PAY_PAST_DUE_DAYS","dataType":"double"},{"name":"INV_TO_PAY_WEIGHT","dataType":"double"},{"name":"PAST_DUE_AMOUNT","dataType":"double"},{"name":"PAY_PAST_DUE_WEIGHT","dataType":"double"},{"name":"WAS_DISCOUNT_TAKEN","dataType":"string"},{"name":"ROW_CREATION_DATE","dataType":"dateTime"}],"partitions":[{"name":"IncrementalRefreshPolicyPartition-2019Q2","refreshTime":"2021-07-19T16:30:16.986046+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/b5e0daf7-153a-43e2-85aa-376ed68f93e9/XXREP_AP_PAY_INVOICE_TAB/part-2019Q2.csv?snapshot=2021-07-19T16%3A30%3A16.5298515Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2019-04-01T00:00:00","end":"2019-07-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2019Q3","refreshTime":"2021-07-19T16:30:12.4358626+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/b5e0daf7-153a-43e2-85aa-376ed68f93e9/XXREP_AP_PAY_INVOICE_TAB/part-2019Q3.csv?snapshot=2021-07-19T16%3A30%3A12.2638242Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2019-07-01T00:00:00","end":"2019-10-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2019Q4","refreshTime":"2021-07-19T16:30:37.4461704+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/b5e0daf7-153a-43e2-85aa-376ed68f93e9/XXREP_AP_PAY_INVOICE_TAB/part-2019Q4.csv?snapshot=2021-07-19T16%3A30%3A33.7840996Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2019-10-01T00:00:00","end":"2020-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2020Q1","refreshTime":"2021-07-19T16:30:35.9733814+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/b5e0daf7-153a-43e2-85aa-376ed68f93e9/XXREP_AP_PAY_INVOICE_TAB/part-2020Q1.csv?snapshot=2021-07-19T16%3A30%3A31.7946877Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2020-01-01T00:00:00","end":"2020-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2020Q2","refreshTime":"2021-07-19T16:30:38.0844401+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/b5e0daf7-153a-43e2-85aa-376ed68f93e9/XXREP_AP_PAY_INVOICE_TAB/part-2020Q2.csv?snapshot=2021-07-19T16%3A30%3A32.6673073Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2020-04-01T00:00:00","end":"2020-07-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2020Q3","refreshTime":"2021-07-19T16:30:35.7233591+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/b5e0daf7-153a-43e2-85aa-376ed68f93e9/XXREP_AP_PAY_INVOICE_TAB/part-2020Q3.csv?snapshot=2021-07-19T16%3A30%3A31.9878245Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2020-07-01T00:00:00","end":"2020-10-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2020Q4","refreshTime":"2021-07-19T16:30:37.5374425+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/b5e0daf7-153a-43e2-85aa-376ed68f93e9/XXREP_AP_PAY_INVOICE_TAB/part-2020Q4.csv?snapshot=2021-07-19T16%3A30%3A32.4821762Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2020-10-01T00:00:00","end":"2021-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2021Q1","refreshTime":"2021-07-19T16:30:39.1761157+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/b5e0daf7-153a-43e2-85aa-376ed68f93e9/XXREP_AP_PAY_INVOICE_TAB/part-2021Q1.csv?snapshot=2021-07-19T16%3A30%3A32.8344256Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2021-01-01T00:00:00","end":"2021-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2021Q2","refreshTime":"2021-07-19T16:30:39.0996465+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/b5e0daf7-153a-43e2-85aa-376ed68f93e9/XXREP_AP_PAY_INVOICE_TAB/part-2021Q2.csv?snapshot=2021-07-19T16%3A30%3A34.6987481Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2021-04-01T00:00:00","end":"2021-07-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2021Q3","refreshTime":"2021-10-03T22:02:35.5622984+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/b5e0daf7-153a-43e2-85aa-376ed68f93e9/XXREP_AP_PAY_INVOICE_TAB/part-2021Q3.csv?snapshot=2021-10-03T22%3A02%3A31.4896317Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2021-07-01T00:00:00","end":"2021-10-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2021Q4","refreshTime":"2022-01-02T23:01:26.1576509+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/b5e0daf7-153a-43e2-85aa-376ed68f93e9/XXREP_AP_PAY_INVOICE_TAB/part-2021Q4.csv?snapshot=2022-01-02T23%3A01%3A21.7054699Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2021-10-01T00:00:00","end":"2022-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q1","refreshTime":"2022-04-03T22:05:57.2773434+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/b5e0daf7-153a-43e2-85aa-376ed68f93e9/XXREP_AP_PAY_INVOICE_TAB/part-2022Q1.csv?snapshot=2022-04-03T22%3A05%3A51.9529553Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-01-01T00:00:00","end":"2022-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q2","refreshTime":"2022-05-15T22:01:32.7742233+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/b5e0daf7-153a-43e2-85aa-376ed68f93e9/XXREP_AP_PAY_INVOICE_TAB/part-2022Q2.csv?snapshot=2022-05-15T22%3A01%3A27.8289445Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-01T00:00:00","end":"2022-07-01T00:00:00"}}]}]}