{"name":"GL_DRILL_TRANS","description":"GL Drill Down Transactions ( refreshed weekly on Sunday)","version":"1.0","culture":"en-US","modifiedTime":"2021-07-06T06:22:03.9095868+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"XX_GL_DRILL_TRANS_VIEW":{"queryId":"0b993609-e19f-4388-a84a-9be447289d24","queryName":"XX_GL_DRILL_TRANS_VIEW","loadEnabled":true},"RangeEnd":{"queryId":"3d598e5e-69f5-4259-8251-a2451bc5fe6e","queryName":"RangeEnd"},"RangeStart":{"queryId":"204ac904-1b20-45a9-8038-81733a7c3802","queryName":"RangeStart"}},"document":"section Section1;\r\n\r\nshared XX_GL_DRILL_TRANS_VIEW = let\r\n    Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n    Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n    #\"Navigation 1\" = Navigation{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n    #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XX_GL_DRILL_TRANS_VIEW\", Kind = \"View\"]}[Data],\r\n    #\"Renamed columns\" = Table.RenameColumns(#\"Navigation 2\", {{\"SEGMENT1\", \"Entity Code\"}, {\"SEGMENT3\", \"Account Code\"}, {\"PERIOD_NAME\", \"GL Period\"}}),\r\n    #\"XX_GL_DRILL_TRANS_VIEW-504552494F445F454E445F44415445-autogenerated_for_incremental_refresh\" = Table.SelectRows(#\"Renamed columns\", each DateTime.From([PERIOD_END_DATE]) >= RangeStart and DateTime.From([PERIOD_END_DATE]) < RangeEnd)\r\nin\r\n    #\"XX_GL_DRILL_TRANS_VIEW-504552494F445F454E445F44415445-autogenerated_for_incremental_refresh\";\r\n\r\nshared RangeStart = let RangeStart = #datetime(0001,01,01,00,00,00) meta [IsParameterQuery=true, List={}, Type=\"DateTime\", IsParameterQueryRequired=true, Description=\"autogenerated_for_incremental_refresh\"] in RangeStart;\r\n\r\nshared RangeEnd = let RangeEnd = #datetime(9999,12,31,23,59,59) meta [IsParameterQuery=true, List={}, Type=\"DateTime\", IsParameterQueryRequired=true, Description=\"autogenerated_for_incremental_refresh\"] in RangeEnd;\r\n\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"XX_GL_DRILL_TRANS_VIEW","description":"","pbi:refreshPolicy":{"$type":"IncrementalRefreshPolicy","locationPattern":"XX_GL_DRILL_TRANS_VIEW/part.csv","rollingWindowGranularity":"year","rollingWindowPeriods":4,"incrementalGranularity":"day","incrementalPeriods":45},"annotations":[{"name":"pbi:IncrementalRefreshDetectChangeAttribute"},{"name":"pbi:IncrementalRefreshFilterByAttribute","value":"PERIOD_END_DATE"}],"attributes":[{"name":"GL_DATE","dataType":"dateTime"},{"name":"GL_TRANSFER_DATE","dataType":"dateTime"},{"name":"TRANSACTION_NUMBER","dataType":"string"},{"name":"ENTITY_TYPE_CODE","dataType":"string"},{"name":"ENTITY_ID","dataType":"double"},{"name":"TRX_HDR_ID","dataType":"double"},{"name":"ORG_ID","dataType":"double"},{"name":"EVENT_ID","dataType":"double"},{"name":"EVENT_DATE","dataType":"dateTime"},{"name":"EVENT_NUMBER","dataType":"double"},{"name":"TRANSACTION_DATE","dataType":"dateTime"},{"name":"APPLICATION_ID","dataType":"double"},{"name":"AE_HEADER_ID","dataType":"double"},{"name":"HEADER_DESCRIPTION","dataType":"string"},{"name":"GL_TRANSFER_STATUS_CODE","dataType":"string"},{"name":"JE_CATEGORY_NAME","dataType":"string"},{"name":"JE_SOURCE_NAME","dataType":"string"},{"name":"EVENT_CLASS_CODE","dataType":"string"},{"name":"EVENT_TYPE_CODE","dataType":"string"},{"name":"JE_BATCH_ID","dataType":"double"},{"name":"WTA_BATCH_ID","dataType":"double"},{"name":"GL_SL_LINK_TABLE","dataType":"string"},{"name":"GL_BATCH_NAME","dataType":"string"},{"name":"POSTED_DATE","dataType":"dateTime"},{"name":"GL_JE_NAME","dataType":"string"},{"name":"EXTERNAL_REFERENCE","dataType":"string"},{"name":"GL_LINE_NUMBER","dataType":"double"},{"name":"AE_LINE_NUMBER","dataType":"double"},{"name":"DISPLAYED_LINE_NUMBER","dataType":"double"},{"name":"LINE_DESCRIPTION","dataType":"string"},{"name":"ENTERED_CURRENCY","dataType":"string"},{"name":"CONVERSION_RATE","dataType":"double"},{"name":"CONVERSION_RATE_DATE","dataType":"dateTime"},{"name":"CONVERSION_RATE_TYPE_CODE","dataType":"string"},{"name":"ENTERED_DR","dataType":"double"},{"name":"ENTERED_CR","dataType":"double"},{"name":"ACCOUNTED_DR","dataType":"double"},{"name":"ACCOUNTED_CR","dataType":"double"},{"name":"ACCOUNTED_NET","dataType":"double"},{"name":"TRX_DISTRIBUTION_ID","dataType":"double"},{"name":"TRX_DISTRIBUTION_TYPE","dataType":"string"},{"name":"JE_HEADER_ID","dataType":"double"},{"name":"LEDGER_ID","dataType":"double"},{"name":"JE_CATEGORY","dataType":"string"},{"name":"JE_SOURCE","dataType":"string"},{"name":"LEDGER_NAME","dataType":"string"},{"name":"LEDGER_CURRENCY","dataType":"string"},{"name":"PERIOD_YEAR","dataType":"double"},{"name":"GL Period","dataType":"string"},{"name":"CODE_COMBINATION_ID","dataType":"double"},{"name":"ACCOUNT","dataType":"string"},{"name":"Entity Code","dataType":"string"},{"name":"SEGMENT2","dataType":"string"},{"name":"Account Code","dataType":"string"},{"name":"SEGMENT4","dataType":"string"},{"name":"SEGMENT5","dataType":"string"},{"name":"SEGMENT6","dataType":"string"},{"name":"TRAN_SOURCE","dataType":"string"},{"name":"ACCT_LINE_TYPE","dataType":"string"},{"name":"ACCT_LINE_TYPE_NAME","dataType":"string"},{"name":"PO_ORDER_NUMBER","dataType":"string"},{"name":"PO_ORDER_RELEASE_NUM","dataType":"string"},{"name":"RCV_RECEIPT_NUM","dataType":"string"},{"name":"AE_LINE_REFERENCE","dataType":"string"},{"name":"TAX_CODE","dataType":"string"},{"name":"BANK_ACCOUNT_NAME","dataType":"string"},{"name":"SOURCE_ID","dataType":"double"},{"name":"SOURCE_TABLE","dataType":"string"},{"name":"AEL_TABLE","dataType":"string"},{"name":"DOC_SEQUENCE_ID","dataType":"double"},{"name":"DOC_SEQUENCE_NAME","dataType":"string"},{"name":"DOC_SEQUENCE_VALUE","dataType":"double"},{"name":"TRX_HDR_TABLE","dataType":"string"},{"name":"TRX_HDR_CURRENCY","dataType":"string"},{"name":"TRX_CLASS","dataType":"string"},{"name":"TRX_DATE","dataType":"dateTime"},{"name":"TRX_TYPE_C","dataType":"string"},{"name":"TRX_TYPE_NAME","dataType":"string"},{"name":"TRX_CLASS_NAME","dataType":"string"},{"name":"TRX_NUMBER_DISPLAYED","dataType":"string"},{"name":"TRX_LINE_NUMBER","dataType":"double"},{"name":"TRX_LINE_TYPE","dataType":"string"},{"name":"TRX_LINE_TYPE_NAME","dataType":"string"},{"name":"INV_ORG_CODE","dataType":"string"},{"name":"TRAN_DESC1","dataType":"string"},{"name":"TRAN_DESC2","dataType":"string"},{"name":"TRAN_DESC3","dataType":"string"},{"name":"TRAN_DESC4","dataType":"string"},{"name":"TRAN_DESC5","dataType":"string"},{"name":"TRAN_DESC6","dataType":"string"},{"name":"PO_LINE_NUM","dataType":"double"},{"name":"PO_LINE_DESCRIPTION","dataType":"string"},{"name":"AP_INVOICE_NUMBER","dataType":"string"},{"name":"VENDOR_NAME","dataType":"string"},{"name":"VAT_REGISTRATION_NUM","dataType":"string"},{"name":"VOUCH_NO","dataType":"double"},{"name":"LINKURL_VOUCH_NO","dataType":"string"},{"name":"QUANTITY","dataType":"double"},{"name":"QUERY_REF","dataType":"string"},{"name":"LOCAL_GAP_ENTITY","dataType":"string"},{"name":"PERIOD_END_CONV_RATE","dataType":"double"},{"name":"ROW_CREATION_DATE","dataType":"dateTime"},{"name":"ACCOUNTED_NET_USD","dataType":"double"},{"name":"USD_CONV_RATE","dataType":"double"},{"name":"PERIOD_START_DATE","dataType":"dateTime"},{"name":"PERIOD_END_DATE","dataType":"dateTime"},{"name":"QUARTER_START_DATE","dataType":"dateTime"},{"name":"QUARTER_END_DATE","dataType":"dateTime"},{"name":"YEAR_START_DATE","dataType":"dateTime"},{"name":"YEAR_END_DATE","dataType":"dateTime"},{"name":"FISCAL_YEAR","dataType":"string"},{"name":"QUARTER_NUM","dataType":"double"},{"name":"FISCAL_QUARTER","dataType":"string"},{"name":"FYFQ","dataType":"string"},{"name":"EXPENSE_DETAIL_KEY","dataType":"string"},{"name":"GLCCID_DETAIL_KEY","dataType":"string"},{"name":"GL_ENTITY_ACC_DETAIL_KEY","dataType":"string"}],"partitions":[{"name":"IncrementalRefreshPolicyPartition-2018","refreshTime":"2021-07-06T06:43:51.6980098+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2018.csv?snapshot=2021-07-06T06%3A43%3A51.4204902Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2018-01-01T00:00:00","end":"2019-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2019","refreshTime":"2021-07-06T07:31:19.8251174+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2019.csv?snapshot=2021-07-06T07%3A26%3A33.9761979Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2019-01-01T00:00:00","end":"2020-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2020","refreshTime":"2021-07-06T08:30:10.1053465+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2020.csv?snapshot=2021-07-06T08%3A21%3A34.4147331Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2020-01-01T00:00:00","end":"2021-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2021","refreshTime":"2022-02-20T19:00:54.0317127+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2021.csv?snapshot=2022-02-27T19%3A48%3A53.4494473Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2021-01-01T00:00:00","end":"2022-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q101","refreshTime":"2022-03-20T18:17:02.2889204+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q101.csv?snapshot=2022-03-27T18%3A12%3A16.4654004Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-01-01T00:00:00","end":"2022-02-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q102","refreshTime":"2022-04-17T18:23:02.9631747+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q102.csv?snapshot=2022-04-24T18%3A07%3A24.5691603Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-02-01T00:00:00","end":"2022-03-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q10301","refreshTime":"2022-04-17T18:01:47.2602911+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q10301.csv?snapshot=2022-04-17T18%3A01%3A35.3792653Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-03-01T00:00:00","end":"2022-03-02T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q10302","refreshTime":"2022-04-17T18:02:00.1738994+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q10302.csv?snapshot=2022-04-17T18%3A01%3A39.0271877Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-03-02T00:00:00","end":"2022-03-03T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q10303","refreshTime":"2022-04-17T18:01:38.8711606+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q10303.csv?snapshot=2022-04-17T18%3A01%3A33.8371439Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-03-03T00:00:00","end":"2022-03-04T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q10304","refreshTime":"2022-04-24T18:00:45.9133677+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q10304.csv?snapshot=2022-04-24T18%3A00%3A42.9380253Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-03-04T00:00:00","end":"2022-03-05T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q10305","refreshTime":"2022-04-24T18:00:43.8352164+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q10305.csv?snapshot=2022-04-24T18%3A00%3A39.4210320Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-03-05T00:00:00","end":"2022-03-06T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q10306","refreshTime":"2022-04-24T18:00:45.6789867+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q10306.csv?snapshot=2022-04-24T18%3A00%3A42.8100983Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-03-06T00:00:00","end":"2022-03-07T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q10307","refreshTime":"2022-04-24T18:00:43.007091+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q10307.csv?snapshot=2022-04-24T18%3A00%3A39.4070404Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-03-07T00:00:00","end":"2022-03-08T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q10308","refreshTime":"2022-04-24T18:00:44.0383523+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q10308.csv?snapshot=2022-04-24T18%3A00%3A37.6630366Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-03-08T00:00:00","end":"2022-03-09T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q10309","refreshTime":"2022-04-24T18:00:43.6633471+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q10309.csv?snapshot=2022-04-24T18%3A00%3A37.1853084Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-03-09T00:00:00","end":"2022-03-10T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q10310","refreshTime":"2022-04-24T18:00:45.0383564+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q10310.csv?snapshot=2022-04-24T18%3A00%3A42.7301442Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-03-10T00:00:00","end":"2022-03-11T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q10311","refreshTime":"2022-05-01T18:00:58.0225502+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q10311.csv?snapshot=2022-05-01T18%3A00%3A57.6994724Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-03-11T00:00:00","end":"2022-03-12T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q10312","refreshTime":"2022-05-01T18:00:25.429714+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q10312.csv?snapshot=2022-05-01T18%3A00%3A20.0820929Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-03-12T00:00:00","end":"2022-03-13T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q10313","refreshTime":"2022-05-01T18:00:28.4377994+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q10313.csv?snapshot=2022-05-01T18%3A00%3A23.4961308Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-03-13T00:00:00","end":"2022-03-14T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q10314","refreshTime":"2022-05-01T18:01:00.0831098+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q10314.csv?snapshot=2022-05-01T18%3A00%3A58.5559805Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-03-14T00:00:00","end":"2022-03-15T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q10315","refreshTime":"2022-05-01T18:00:30.7034465+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q10315.csv?snapshot=2022-05-01T18%3A00%3A30.4581296Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-03-15T00:00:00","end":"2022-03-16T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q10316","refreshTime":"2022-05-01T18:00:59.1456031+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q10316.csv?snapshot=2022-05-01T18%3A00%3A58.0562671Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-03-16T00:00:00","end":"2022-03-17T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q10317","refreshTime":"2022-05-01T18:00:29.015933+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q10317.csv?snapshot=2022-05-01T18%3A00%3A23.7949589Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-03-17T00:00:00","end":"2022-03-18T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q10318","refreshTime":"2022-05-08T18:00:41.1774308+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q10318.csv?snapshot=2022-05-08T18%3A00%3A40.4422992Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-03-18T00:00:00","end":"2022-03-19T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q10319","refreshTime":"2022-05-08T18:00:46.5524787+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q10319.csv?snapshot=2022-05-08T18%3A00%3A42.6960062Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-03-19T00:00:00","end":"2022-03-20T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q10320","refreshTime":"2022-05-08T18:00:43.3336871+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q10320.csv?snapshot=2022-05-08T18%3A00%3A41.8744774Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-03-20T00:00:00","end":"2022-03-21T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q10321","refreshTime":"2022-05-08T18:00:42.552435+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q10321.csv?snapshot=2022-05-08T18%3A00%3A41.6865851Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-03-21T00:00:00","end":"2022-03-22T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q10322","refreshTime":"2022-05-08T18:00:44.052448+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q10322.csv?snapshot=2022-05-08T18%3A00%3A42.1932949Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-03-22T00:00:00","end":"2022-03-23T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q10323","refreshTime":"2022-05-08T18:00:55.7935226+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q10323.csv?snapshot=2022-05-08T18%3A00%3A47.7830893Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-03-23T00:00:00","end":"2022-03-24T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q10324","refreshTime":"2022-05-08T18:00:49.1462378+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q10324.csv?snapshot=2022-05-08T18%3A00%3A42.5920661Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-03-24T00:00:00","end":"2022-03-25T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q10325","refreshTime":"2022-05-15T18:00:58.8386089+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q10325.csv?snapshot=2022-05-15T18%3A00%3A58.6015767Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-03-25T00:00:00","end":"2022-03-26T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q10326","refreshTime":"2022-05-15T18:00:27.3661187+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q10326.csv?snapshot=2022-05-15T18%3A00%3A22.7670385Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-03-26T00:00:00","end":"2022-03-27T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q10327","refreshTime":"2022-05-15T18:00:59.4011008+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q10327.csv?snapshot=2022-05-15T18%3A00%3A59.2492083Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-03-27T00:00:00","end":"2022-03-28T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q10328","refreshTime":"2022-05-15T18:00:28.1317409+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q10328.csv?snapshot=2022-05-15T18%3A00%3A25.3605588Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-03-28T00:00:00","end":"2022-03-29T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q10329","refreshTime":"2022-05-15T18:00:58.8854764+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q10329.csv?snapshot=2022-05-15T18%3A00%3A58.6465513Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-03-29T00:00:00","end":"2022-03-30T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q10330","refreshTime":"2022-05-15T18:00:28.5223756+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q10330.csv?snapshot=2022-05-15T18%3A00%3A26.8077315Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-03-30T00:00:00","end":"2022-03-31T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q10331","refreshTime":"2022-05-15T18:00:28.428618+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q10331.csv?snapshot=2022-05-15T18%3A00%3A25.2626140Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-03-31T00:00:00","end":"2022-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20401","refreshTime":"2022-05-15T18:00:59.1354924+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20401.csv?snapshot=2022-05-15T18%3A00%3A58.7454943Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-01T00:00:00","end":"2022-04-02T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20402","refreshTime":"2022-05-15T18:20:36.4920064+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20402.csv?snapshot=2022-05-15T18%3A18%3A20.8404018Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-02T00:00:00","end":"2022-04-03T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20403","refreshTime":"2022-05-15T18:00:28.3504946+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20403.csv?snapshot=2022-05-15T18%3A00%3A23.9383696Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-03T00:00:00","end":"2022-04-04T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20404","refreshTime":"2022-05-15T18:00:59.0729905+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20404.csv?snapshot=2022-05-15T18%3A00%3A58.7235072Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-04T00:00:00","end":"2022-04-05T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20405","refreshTime":"2022-05-15T18:00:58.5260829+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20405.csv?snapshot=2022-05-15T18%3A00%3A58.2917537Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-05T00:00:00","end":"2022-04-06T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20406","refreshTime":"2022-05-15T18:00:59.7292158+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20406.csv?snapshot=2022-05-15T18%3A00%3A59.5990066Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-06T00:00:00","end":"2022-04-07T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20407","refreshTime":"2022-05-15T18:00:58.3854789+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20407.csv?snapshot=2022-05-15T18%3A00%3A58.1348442Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-07T00:00:00","end":"2022-04-08T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20408","refreshTime":"2022-05-15T18:00:59.9010805+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20408.csv?snapshot=2022-05-15T18%3A00%3A59.8148837Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-08T00:00:00","end":"2022-04-09T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20409","refreshTime":"2022-05-15T18:00:59.0261425+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20409.csv?snapshot=2022-05-15T18%3A00%3A58.7524903Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-09T00:00:00","end":"2022-04-10T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20410","refreshTime":"2022-05-15T18:00:59.3855005+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20410.csv?snapshot=2022-05-15T18%3A00%3A59.2542043Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-10T00:00:00","end":"2022-04-11T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20411","refreshTime":"2022-05-15T18:01:01.2135941+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20411.csv?snapshot=2022-05-15T18%3A01%3A00.9572316Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-11T00:00:00","end":"2022-04-12T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20412","refreshTime":"2022-05-15T18:00:28.8661216+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20412.csv?snapshot=2022-05-15T18%3A00%3A26.7507639Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-12T00:00:00","end":"2022-04-13T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20413","refreshTime":"2022-05-15T18:00:58.9792923+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20413.csv?snapshot=2022-05-15T18%3A00%3A58.6455521Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-13T00:00:00","end":"2022-04-14T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20414","refreshTime":"2022-05-15T18:00:28.8036296+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20414.csv?snapshot=2022-05-15T18%3A00%3A27.4203815Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-14T00:00:00","end":"2022-04-15T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20415","refreshTime":"2022-05-15T18:00:59.4636197+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20415.csv?snapshot=2022-05-15T18%3A00%3A59.3471516Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-15T00:00:00","end":"2022-04-16T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20416","refreshTime":"2022-05-15T18:01:00.791711+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20416.csv?snapshot=2022-05-15T18%3A01%3A00.6144278Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-16T00:00:00","end":"2022-04-17T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20417","refreshTime":"2022-05-15T18:01:00.8698445+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20417.csv?snapshot=2022-05-15T18%3A01%3A00.6464089Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-17T00:00:00","end":"2022-04-18T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20418","refreshTime":"2022-05-15T18:00:30.9324273+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20418.csv?snapshot=2022-05-15T18%3A00%3A30.2587613Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-18T00:00:00","end":"2022-04-19T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20419","refreshTime":"2022-05-15T18:00:32.2341424+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20419.csv?snapshot=2022-05-15T18%3A00%3A31.5020510Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-19T00:00:00","end":"2022-04-20T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20420","refreshTime":"2022-05-15T18:00:32.281011+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20420.csv?snapshot=2022-05-15T18%3A00%3A31.7888870Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-20T00:00:00","end":"2022-04-21T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20421","refreshTime":"2022-05-15T18:00:32.3591431+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20421.csv?snapshot=2022-05-15T18%3A00%3A31.8438559Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-21T00:00:00","end":"2022-04-22T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20422","refreshTime":"2022-05-15T18:00:34.2037325+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20422.csv?snapshot=2022-05-15T18%3A00%3A33.8956841Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-22T00:00:00","end":"2022-04-23T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20423","refreshTime":"2022-05-15T18:00:34.927753+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20423.csv?snapshot=2022-05-15T18%3A00%3A34.6002815Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-23T00:00:00","end":"2022-04-24T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20424","refreshTime":"2022-05-15T18:00:32.3903824+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20424.csv?snapshot=2022-05-15T18%3A00%3A32.0097609Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-24T00:00:00","end":"2022-04-25T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20425","refreshTime":"2022-05-15T18:00:33.4216395+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20425.csv?snapshot=2022-05-15T18%3A00%3A33.1980827Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-25T00:00:00","end":"2022-04-26T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20426","refreshTime":"2022-05-15T18:01:01.5982151+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20426.csv?snapshot=2022-05-15T18%3A01%3A01.2920404Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-26T00:00:00","end":"2022-04-27T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20427","refreshTime":"2022-05-15T18:01:00.8229705+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20427.csv?snapshot=2022-05-15T18%3A01%3A00.6474085Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-27T00:00:00","end":"2022-04-28T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20428","refreshTime":"2022-05-15T18:00:29.4754948+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20428.csv?snapshot=2022-05-15T18%3A00%3A28.3828326Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-28T00:00:00","end":"2022-04-29T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20429","refreshTime":"2022-05-15T18:00:34.0474259+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20429.csv?snapshot=2022-05-15T18%3A00%3A33.6758097Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-29T00:00:00","end":"2022-04-30T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20430","refreshTime":"2022-05-15T18:16:38.5423897+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20430.csv?snapshot=2022-05-15T18%3A14%3A14.5240525Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-30T00:00:00","end":"2022-05-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20501","refreshTime":"2022-05-15T18:00:34.281797+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20501.csv?snapshot=2022-05-15T18%3A00%3A33.8986827Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-05-01T00:00:00","end":"2022-05-02T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20502","refreshTime":"2022-05-15T18:00:34.1099308+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20502.csv?snapshot=2022-05-15T18%3A00%3A33.6848044Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-05-02T00:00:00","end":"2022-05-03T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20503","refreshTime":"2022-05-15T18:00:29.2255098+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20503.csv?snapshot=2022-05-15T18%3A00%3A28.0030493Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-05-03T00:00:00","end":"2022-05-04T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20504","refreshTime":"2022-05-15T18:01:01.1354747+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20504.csv?snapshot=2022-05-15T18%3A01%3A00.9162551Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-05-04T00:00:00","end":"2022-05-05T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20505","refreshTime":"2022-05-15T18:01:01.4792392+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20505.csv?snapshot=2022-05-15T18%3A01%3A01.1411266Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-05-05T00:00:00","end":"2022-05-06T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20506","refreshTime":"2022-05-15T18:00:29.6667608+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20506.csv?snapshot=2022-05-15T18%3A00%3A28.5157561Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-05-06T00:00:00","end":"2022-05-07T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20507","refreshTime":"2022-05-15T18:01:00.9948488+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20507.csv?snapshot=2022-05-15T18%3A01%3A00.8033198Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-05-07T00:00:00","end":"2022-05-08T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20508","refreshTime":"2022-05-15T18:01:02.2544676+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20508.csv?snapshot=2022-05-15T18%3A01%3A02.0106301Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-05-08T00:00:00","end":"2022-05-09T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20509","refreshTime":"2022-05-15T18:00:29.0848797+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20509.csv?snapshot=2022-05-15T18%3A00%3A28.1519637Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-05-09T00:00:00","end":"2022-05-10T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20510","refreshTime":"2022-05-15T18:01:01.4167138+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20510.csv?snapshot=2022-05-15T18%3A01%3A01.1651123Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-05-10T00:00:00","end":"2022-05-11T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20511","refreshTime":"2022-05-15T18:01:01.7544788+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20511.csv?snapshot=2022-05-15T18%3A01%3A01.4609440Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-05-11T00:00:00","end":"2022-05-12T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20512","refreshTime":"2022-05-15T18:01:01.3698438+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20512.csv?snapshot=2022-05-15T18%3A01%3A01.1381281Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-05-12T00:00:00","end":"2022-05-13T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20513","refreshTime":"2022-05-15T18:01:01.5513143+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20513.csv?snapshot=2022-05-15T18%3A01%3A01.2810466Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-05-13T00:00:00","end":"2022-05-14T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20514","refreshTime":"2022-05-15T18:01:01.0885955+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20514.csv?snapshot=2022-05-15T18%3A01%3A00.8542902Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-05-14T00:00:00","end":"2022-05-15T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q20515","refreshTime":"2022-05-15T18:00:39.0352356+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/cd061dae-1268-4fdc-80dc-4eaafd7288ea/XX_GL_DRILL_TRANS_VIEW/part-2022Q20515.csv?snapshot=2022-05-15T18%3A00%3A38.7928873Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-05-15T00:00:00","end":"2022-05-16T00:00:00"}}]}]}