{"name":"WIP_JOBS_ORACLE","description":"WIP Jobs","version":"1.0","culture":"en-US","modifiedTime":"2021-11-26T14:41:39.3286304+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"Data Update Info":{"queryId":"fa4eebd8-827e-40fa-9bc3-d691a7c402d9","queryName":"Data Update Info","loadEnabled":true},"XXREP_WIP_DISCRETE_JOBS_V":{"queryId":"90d40830-af22-45d6-959d-feb57d6d6ab6","queryName":"XXREP_WIP_DISCRETE_JOBS_V","loadEnabled":true},"RangeEnd":{"queryId":"9af10ba0-6b6c-498e-ae4f-89dbbf7c377c","queryName":"RangeEnd"},"RangeStart":{"queryId":"63b618e0-ce00-451a-9686-8d4506404745","queryName":"RangeStart"},"XXREP_WIP_DISCRETE_JOBS_V_Canary":{"queryId":"72fa122c-98a3-4b4e-9a80-e8ec32768851","queryName":"XXREP_WIP_DISCRETE_JOBS_V_Canary"}},"document":"section Section1;\r\n\r\nshared #\"Data Update Info\" = let\r\n    Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n    Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n    #\"Navigation 1\" = Navigation{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n    #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXREP_DATA_UPDATE_V\", Kind = \"View\"]}[Data],\r\n    #\"Filtered rows\" = Table.SelectRows(#\"Navigation 2\", each [TABLE_NAME] = \"WIP.WIP_DISCRETE_JOBS\")\r\nin\r\n    #\"Filtered rows\";\r\n\r\nshared XXREP_WIP_DISCRETE_JOBS_V = let\r\n    Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n    Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n    #\"Navigation 1\" = Navigation{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n    #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXREP_WIP_DISCRETE_JOBS_V\", Kind = \"View\"]}[Data],\r\n    #\"XXREP_WIP_DISCRETE_JOBS_V-4352454154494F4E5F44415445-autogenerated_for_incremental_refresh\" = Table.SelectRows(#\"Navigation 2\", each DateTime.From([CREATION_DATE]) >= RangeStart and DateTime.From([CREATION_DATE]) < RangeEnd)\r\nin\r\n    #\"XXREP_WIP_DISCRETE_JOBS_V-4352454154494F4E5F44415445-autogenerated_for_incremental_refresh\";\r\n\r\nshared XXREP_WIP_DISCRETE_JOBS_V_Canary = let\r\n    Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n    Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n    #\"Navigation 1\" = Navigation{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n    #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXREP_WIP_DISCRETE_JOBS_V\", Kind = \"View\"]}[Data],\r\n    #\"XXREP_WIP_DISCRETE_JOBS_V-4352454154494F4E5F44415445-autogenerated_for_incremental_refresh\" = Table.SelectRows(#\"Navigation 2\", each DateTime.From([CREATION_DATE]) >= RangeStart and DateTime.From([CREATION_DATE]) < RangeEnd), #\"XXREP_WIP_DISCRETE_JOBS_V_Canary-4C4153545F5550444154455F44415445-autogenerated_for_incremental_refresh\" = DateTime.ToText(Table.Max(#\"XXREP_WIP_DISCRETE_JOBS_V-4352454154494F4E5F44415445-autogenerated_for_incremental_refresh\",each [LAST_UPDATE_DATE], [LAST_UPDATE_DATE=#datetime(0001,01,01,00,00,00)])[LAST_UPDATE_DATE]) in #\"XXREP_WIP_DISCRETE_JOBS_V_Canary-4C4153545F5550444154455F44415445-autogenerated_for_incremental_refresh\";\r\n\r\nshared RangeStart = let RangeStart = #datetime(0001,01,01,00,00,00) meta [IsParameterQuery=true, List={}, Type=\"DateTime\", IsParameterQueryRequired=true, Description=\"autogenerated_for_incremental_refresh\"] in RangeStart;\r\n\r\nshared RangeEnd = let RangeEnd = #datetime(9999,12,31,23,59,59) meta [IsParameterQuery=true, List={}, Type=\"DateTime\", IsParameterQueryRequired=true, Description=\"autogenerated_for_incremental_refresh\"] in RangeEnd;\r\n\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"Data Update Info","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Data%20Update%20Info.csv"},"attributes":[{"name":"TABLE_NAME","dataType":"string"},{"name":"DATA_UPDATE_DATE","dataType":"dateTime"},{"name":"DATA_UPDATE_DESC","dataType":"string"},{"name":"DATA_FLOW_REFRESH_DATE","dataType":"dateTime"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T05:01:35.019744+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/e580c770-0c61-4350-8584-096241c53293/Data%20Update%20Info.csv?snapshot=2022-06-13T05%3A01%3A34.1519654Z"}]},{"$type":"LocalEntity","name":"XXREP_WIP_DISCRETE_JOBS_V","description":"","pbi:refreshPolicy":{"$type":"IncrementalRefreshPolicy","locationPattern":"XXREP_WIP_DISCRETE_JOBS_V/part.csv","rollingWindowGranularity":"quarter","rollingWindowPeriods":24,"incrementalGranularity":"quarter","incrementalPeriods":24,"pollingQuery":"XXREP_WIP_DISCRETE_JOBS_V_Canary"},"annotations":[{"name":"pbi:IncrementalRefreshDetectChangeAttribute","value":"LAST_UPDATE_DATE"},{"name":"pbi:IncrementalRefreshFilterByAttribute","value":"CREATION_DATE"}],"attributes":[{"name":"ORGANIZATION_ID","dataType":"double"},{"name":"WIP_ENTITY_ID","dataType":"double"},{"name":"WIPJOB_ORG_KEY_CODE","dataType":"string"},{"name":"WIPJOB_ORG_KEY_ID","dataType":"string"},{"name":"LAST_UPDATE_DATE","dataType":"dateTime"},{"name":"LAST_UPDATED_BY","dataType":"double"},{"name":"CREATION_DATE","dataType":"dateTime"},{"name":"CREATED_BY","dataType":"double"},{"name":"DESCRIPTION","dataType":"string"},{"name":"STATUS_TYPE","dataType":"double"},{"name":"PRIMARY_ITEM_ID","dataType":"double"},{"name":"CLASS_CODE","dataType":"string"},{"name":"MATERIAL_ACCOUNT","dataType":"double"},{"name":"MATERIAL_OVERHEAD_ACCOUNT","dataType":"double"},{"name":"RESOURCE_ACCOUNT","dataType":"double"},{"name":"OUTSIDE_PROCESSING_ACCOUNT","dataType":"double"},{"name":"MATERIAL_VARIANCE_ACCOUNT","dataType":"double"},{"name":"RESOURCE_VARIANCE_ACCOUNT","dataType":"double"},{"name":"OUTSIDE_PROC_VARIANCE_ACCOUNT","dataType":"double"},{"name":"STD_COST_ADJUSTMENT_ACCOUNT","dataType":"double"},{"name":"OVERHEAD_ACCOUNT","dataType":"double"},{"name":"OVERHEAD_VARIANCE_ACCOUNT","dataType":"double"},{"name":"START_QUANTITY","dataType":"double"},{"name":"QUANTITY_REMAINING","dataType":"double"},{"name":"QUANTITY_COMPLETED","dataType":"double"},{"name":"QUANTITY_SCRAPPED","dataType":"double"},{"name":"NET_QUANTITY","dataType":"double"},{"name":"BOM_REFERENCE_ID","dataType":"double"},{"name":"ROUTING_REFERENCE_ID","dataType":"double"},{"name":"COMMON_BOM_SEQUENCE_ID","dataType":"double"},{"name":"COMMON_ROUTING_SEQUENCE_ID","dataType":"double"},{"name":"BOM_REVISION","dataType":"string"},{"name":"ROUTING_REVISION","dataType":"string"},{"name":"BOM_REVISION_DATE","dataType":"dateTime"},{"name":"ROUTING_REVISION_DATE","dataType":"dateTime"},{"name":"LOT_NUMBER","dataType":"string"},{"name":"ALTERNATE_BOM_DESIGNATOR","dataType":"string"},{"name":"ALTERNATE_ROUTING_DESIGNATOR","dataType":"string"},{"name":"COMPLETION_SUBINVENTORY","dataType":"string"},{"name":"COMPLETION_LOCATOR_ID","dataType":"double"},{"name":"SUB_LOCATOR_CONTROL","dataType":"double"},{"name":"SCHEDULE_GROUP_NAME","dataType":"string"},{"name":"SCHEDULE_GROUP_ID","dataType":"double"},{"name":"BUILD_SEQUENCE","dataType":"double"},{"name":"LINE_CODE","dataType":"string"},{"name":"LINE_ID","dataType":"double"},{"name":"PROJECT_ID","dataType":"double"},{"name":"TASK_ID","dataType":"double"},{"name":"END_ITEM_UNIT_NUMBER","dataType":"string"},{"name":"DEMAND_CLASS","dataType":"string"},{"name":"SCHEDULED_START_DATE","dataType":"dateTime"},{"name":"DATE_RELEASED","dataType":"dateTime"},{"name":"SCHEDULED_COMPLETION_DATE","dataType":"dateTime"},{"name":"DATE_COMPLETED","dataType":"dateTime"},{"name":"DATE_CLOSED","dataType":"dateTime"},{"name":"OVERCOMPLETION_TOLERANCE_VALUE","dataType":"double"},{"name":"KANBAN_CARD_ID","dataType":"double"},{"name":"KANBAN_CARD_NUMBER","dataType":"string"},{"name":"PO_CREATION_TIME","dataType":"double"},{"name":"PRIORITY","dataType":"double"},{"name":"DUE_DATE","dataType":"dateTime"},{"name":"EST_SCRAP_ACCOUNT","dataType":"double"},{"name":"EST_SCRAP_VAR_ACCOUNT","dataType":"double"},{"name":"ENTITY_TYPE","dataType":"double"},{"name":"DUE_DATE_PENALTY","dataType":"double"},{"name":"DUE_DATE_TOLERANCE","dataType":"double"},{"name":"COPRODUCTS_SUPPLY","dataType":"double"},{"name":"REQUESTED_START_DATE","dataType":"dateTime"},{"name":"SERIALIZATION_START_OP","dataType":"double"},{"name":"ACTUAL_START_DATE","dataType":"dateTime"},{"name":"EXPECTED_HOLD_RELEASE_DATE","dataType":"dateTime"},{"name":"INVORG_CODE","dataType":"string"},{"name":"ASSEMBLY_ITEM_NUMBER","dataType":"string"},{"name":"JOB_SOURCE","dataType":"string"},{"name":"JOB_STATUS_CODE","dataType":"double"},{"name":"JOB_STATUS","dataType":"string"},{"name":"WIP_SUPPLY_TYPE_CODE","dataType":"double"},{"name":"WIP_SUPPLY_TYPE","dataType":"string"},{"name":"JB_TYPE","dataType":"string"},{"name":"JOB_NUMBER","dataType":"string"},{"name":"JOB_DESCRIPTION","dataType":"string"},{"name":"FIRM_PLANNED_FLAG","dataType":"string"},{"name":"JOB_TYPE","dataType":"string"},{"name":"FIRST_UNIT_START_DATE","dataType":"dateTime"},{"name":"FIRST_UNIT_COMPLETION_DATE","dataType":"dateTime"},{"name":"LAST_UNIT_START_DATE","dataType":"dateTime"},{"name":"LAST_UNIT_COMPLETION_DATE","dataType":"dateTime"},{"name":"DATE_LAST_MOVED","dataType":"dateTime"},{"name":"PROJECT_NUMBER","dataType":"string"},{"name":"PROJECT_NAME","dataType":"string"},{"name":"SALES_ORDER_NO_DFF","dataType":"double"},{"name":"SALE_ORDER_LINE_NO_DFF","dataType":"double"},{"name":"SERVICE_REQUEST_DFF","dataType":"string"},{"name":"ASSEMBLY_SN_DFF","dataType":"string"},{"name":"CREATED_BY_LOGIN","dataType":"string"},{"name":"LAST_UPDATED_BY_LOGIN","dataType":"string"},{"name":"COMPLETION_LOCATOR","dataType":"string"},{"name":"LOCAL_EXTRACT_DATE","dataType":"dateTime"},{"name":"EXTRACT_DATE","dataType":"dateTime"},{"name":"DATA_UPDATE_DESC","dataType":"string"},{"name":"ITEM_NUMBER","dataType":"string"},{"name":"ITEM_DESCRIPTION","dataType":"string"},{"name":"ITEM_TYPE","dataType":"string"},{"name":"ITEM_ORG_KEY_ID","dataType":"string"},{"name":"ITEM_ORG_KEY_CODE","dataType":"string"},{"name":"PRODUCT_FAMILY","dataType":"string"},{"name":"FORECAST_FIELD","dataType":"string"},{"name":"PRODUCT_LINE","dataType":"string"},{"name":"TBU","dataType":"string"},{"name":"ORG_PRODUCT_FAMILY","dataType":"string"},{"name":"ORG_FORECAST_FIELD","dataType":"string"},{"name":"ORG_PRODUCT_LINE","dataType":"string"},{"name":"ORG_TBU","dataType":"string"}],"partitions":[{"name":"IncrementalRefreshPolicyPartition-2016Q2","refreshTime":"2022-01-25T01:59:33.438981+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/e580c770-0c61-4350-8584-096241c53293/XXREP_WIP_DISCRETE_JOBS_V/part-2016Q2.csv?snapshot=2022-01-25T01%3A59%3A14.7769284Z","pbi:refreshBookmark":"1/24/2022 5:42:23 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2016-04-01T00:00:00","end":"2016-07-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2016Q3","refreshTime":"2021-11-26T14:45:25.3900069+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/e580c770-0c61-4350-8584-096241c53293/XXREP_WIP_DISCRETE_JOBS_V/part-2016Q3.csv?snapshot=2021-11-26T14%3A45%3A15.2951722Z","pbi:refreshBookmark":"12/3/2020 12:23:31 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2016-07-01T00:00:00","end":"2016-10-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2016Q4","refreshTime":"2021-11-26T14:45:22.5022768+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/e580c770-0c61-4350-8584-096241c53293/XXREP_WIP_DISCRETE_JOBS_V/part-2016Q4.csv?snapshot=2021-11-26T14%3A45%3A17.4519293Z","pbi:refreshBookmark":"12/3/2020 12:23:31 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2016-10-01T00:00:00","end":"2017-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2017Q1","refreshTime":"2021-11-26T14:45:25.1243841+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/e580c770-0c61-4350-8584-096241c53293/XXREP_WIP_DISCRETE_JOBS_V/part-2017Q1.csv?snapshot=2021-11-26T14%3A45%3A11.3124672Z","pbi:refreshBookmark":"4/23/2021 4:48:07 PM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2017-01-01T00:00:00","end":"2017-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2017Q2","refreshTime":"2022-06-02T05:15:18.1959454+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/e580c770-0c61-4350-8584-096241c53293/XXREP_WIP_DISCRETE_JOBS_V/part-2017Q2.csv?snapshot=2022-06-02T05%3A15%3A09.8817369Z","pbi:refreshBookmark":"6/1/2022 3:19:52 PM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2017-04-01T00:00:00","end":"2017-07-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2017Q3","refreshTime":"2021-11-26T14:45:26.5792788+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/e580c770-0c61-4350-8584-096241c53293/XXREP_WIP_DISCRETE_JOBS_V/part-2017Q3.csv?snapshot=2021-11-26T14%3A45%3A19.0699975Z","pbi:refreshBookmark":"6/14/2021 7:56:00 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2017-07-01T00:00:00","end":"2017-10-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2017Q4","refreshTime":"2021-11-26T14:45:18.0136585+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/e580c770-0c61-4350-8584-096241c53293/XXREP_WIP_DISCRETE_JOBS_V/part-2017Q4.csv?snapshot=2021-11-26T14%3A45%3A03.5479404Z","pbi:refreshBookmark":"3/8/2021 9:18:25 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2017-10-01T00:00:00","end":"2018-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2018Q1","refreshTime":"2022-04-02T12:04:28.0827025+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/e580c770-0c61-4350-8584-096241c53293/XXREP_WIP_DISCRETE_JOBS_V/part-2018Q1.csv?snapshot=2022-04-02T12%3A04%3A20.9810001Z","pbi:refreshBookmark":"4/1/2022 4:08:46 PM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2018-01-01T00:00:00","end":"2018-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2018Q2","refreshTime":"2022-03-29T20:05:11.0329342+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/e580c770-0c61-4350-8584-096241c53293/XXREP_WIP_DISCRETE_JOBS_V/part-2018Q2.csv?snapshot=2022-03-29T20%3A05%3A02.1227156Z","pbi:refreshBookmark":"3/29/2022 8:13:29 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2018-04-01T00:00:00","end":"2018-07-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2018Q3","refreshTime":"2022-06-03T12:03:31.3638642+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/e580c770-0c61-4350-8584-096241c53293/XXREP_WIP_DISCRETE_JOBS_V/part-2018Q3.csv?snapshot=2022-06-03T12%3A03%3A21.3679010Z","pbi:refreshBookmark":"6/3/2022 1:41:10 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2018-07-01T00:00:00","end":"2018-10-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2018Q4","refreshTime":"2022-03-29T20:05:06.8356581+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/e580c770-0c61-4350-8584-096241c53293/XXREP_WIP_DISCRETE_JOBS_V/part-2018Q4.csv?snapshot=2022-03-29T20%3A04%3A58.9005490Z","pbi:refreshBookmark":"3/29/2022 8:13:29 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2018-10-01T00:00:00","end":"2019-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2019Q1","refreshTime":"2022-04-02T20:02:51.3996562+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/e580c770-0c61-4350-8584-096241c53293/XXREP_WIP_DISCRETE_JOBS_V/part-2019Q1.csv?snapshot=2022-04-02T20%3A02%3A44.0343653Z","pbi:refreshBookmark":"4/2/2022 11:02:05 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2019-01-01T00:00:00","end":"2019-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2019Q2","refreshTime":"2022-01-18T21:02:57.8890543+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/e580c770-0c61-4350-8584-096241c53293/XXREP_WIP_DISCRETE_JOBS_V/part-2019Q2.csv?snapshot=2022-01-18T21%3A02%3A49.1154512Z","pbi:refreshBookmark":"1/18/2022 8:09:29 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2019-04-01T00:00:00","end":"2019-07-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2019Q3","refreshTime":"2022-06-02T05:15:42.4697006+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/e580c770-0c61-4350-8584-096241c53293/XXREP_WIP_DISCRETE_JOBS_V/part-2019Q3.csv?snapshot=2022-06-02T05%3A15%3A24.8752697Z","pbi:refreshBookmark":"6/1/2022 4:27:29 PM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2019-07-01T00:00:00","end":"2019-10-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2019Q4","refreshTime":"2022-06-03T20:02:26.4094585+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/e580c770-0c61-4350-8584-096241c53293/XXREP_WIP_DISCRETE_JOBS_V/part-2019Q4.csv?snapshot=2022-06-03T20%3A02%3A20.6047860Z","pbi:refreshBookmark":"6/3/2022 7:48:44 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2019-10-01T00:00:00","end":"2020-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2020Q1","refreshTime":"2022-06-10T20:04:14.4753035+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/e580c770-0c61-4350-8584-096241c53293/XXREP_WIP_DISCRETE_JOBS_V/part-2020Q1.csv?snapshot=2022-06-10T20%3A04%3A09.1285851Z","pbi:refreshBookmark":"6/10/2022 5:49:05 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2020-01-01T00:00:00","end":"2020-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2020Q2","refreshTime":"2022-06-09T20:03:50.5894294+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/e580c770-0c61-4350-8584-096241c53293/XXREP_WIP_DISCRETE_JOBS_V/part-2020Q2.csv?snapshot=2022-06-09T20%3A03%3A43.9051109Z","pbi:refreshBookmark":"6/9/2022 4:40:08 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2020-04-01T00:00:00","end":"2020-07-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2020Q3","refreshTime":"2022-06-10T12:09:29.0122952+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/e580c770-0c61-4350-8584-096241c53293/XXREP_WIP_DISCRETE_JOBS_V/part-2020Q3.csv?snapshot=2022-06-10T12%3A09%3A19.3667069Z","pbi:refreshBookmark":"6/10/2022 12:43:47 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2020-07-01T00:00:00","end":"2020-10-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2020Q4","refreshTime":"2022-06-10T20:04:11.7615302+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/e580c770-0c61-4350-8584-096241c53293/XXREP_WIP_DISCRETE_JOBS_V/part-2020Q4.csv?snapshot=2022-06-10T20%3A04%3A06.0423514Z","pbi:refreshBookmark":"6/10/2022 8:26:52 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2020-10-01T00:00:00","end":"2021-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2021Q1","refreshTime":"2022-06-12T20:01:34.6915133+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/e580c770-0c61-4350-8584-096241c53293/XXREP_WIP_DISCRETE_JOBS_V/part-2021Q1.csv?snapshot=2022-06-12T20%3A01%3A29.3176808Z","pbi:refreshBookmark":"6/12/2022 7:03:55 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2021-01-01T00:00:00","end":"2021-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2021Q2","refreshTime":"2022-06-11T05:15:38.9606899+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/e580c770-0c61-4350-8584-096241c53293/XXREP_WIP_DISCRETE_JOBS_V/part-2021Q2.csv?snapshot=2022-06-11T05%3A15%3A30.0365876Z","pbi:refreshBookmark":"6/10/2022 6:43:14 PM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2021-04-01T00:00:00","end":"2021-07-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2021Q3","refreshTime":"2022-06-11T12:03:41.5588082+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/e580c770-0c61-4350-8584-096241c53293/XXREP_WIP_DISCRETE_JOBS_V/part-2021Q3.csv?snapshot=2022-06-11T12%3A03%3A34.0840773Z","pbi:refreshBookmark":"6/11/2022 3:57:16 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2021-07-01T00:00:00","end":"2021-10-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2021Q4","refreshTime":"2022-06-13T05:08:57.8793177+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/e580c770-0c61-4350-8584-096241c53293/XXREP_WIP_DISCRETE_JOBS_V/part-2021Q4.csv?snapshot=2022-06-13T05%3A08%3A47.3853512Z","pbi:refreshBookmark":"6/12/2022 7:08:46 PM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2021-10-01T00:00:00","end":"2022-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q1","refreshTime":"2022-06-13T05:09:10.7079895+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/e580c770-0c61-4350-8584-096241c53293/XXREP_WIP_DISCRETE_JOBS_V/part-2022Q1.csv?snapshot=2022-06-13T05%3A08%3A55.8205299Z","pbi:refreshBookmark":"6/12/2022 7:27:55 PM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-01-01T00:00:00","end":"2022-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q2","refreshTime":"2022-06-13T05:08:11.4692995+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/e580c770-0c61-4350-8584-096241c53293/XXREP_WIP_DISCRETE_JOBS_V/part-2022Q2.csv?snapshot=2022-06-13T05%3A08%3A02.9007791Z","pbi:refreshBookmark":"6/12/2022 9:27:58 PM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-01T00:00:00","end":"2022-07-01T00:00:00"}}]}]}