{
  "name": "INV_VELOCITY",
  "description": "",
  "version": "1.0",
  "culture": "en-US",
  "modifiedTime": "2021-11-26T17:13:44.2528113+00:00",
  "pbi:mashup": {
    "fastCombine": false,
    "allowNativeQueries": false,
    "queriesMetadata": {
      "Data Update Info": {
        "queryId": "fa1a8ca7-8298-4364-a02b-efbf30a34777",
        "queryName": "Data Update Info",
        "loadEnabled": true
      },
      "Time Balance Week": {
        "queryId": "39f3aef7-6687-46bf-bd9f-3eb6d698d310",
        "queryName": "Time Balance Week",
        "loadEnabled": true
      },
      "Inventory Velocity Summary": {
        "queryId": "6a42a06c-2662-405e-a0c7-84267198ca65",
        "queryName": "Inventory Velocity Summary",
        "loadEnabled": true
      },
      "Inventory Velocity": {
        "queryId": "30dda8a2-ead3-4c8b-aa63-4b91809e2c8c",
        "queryName": "Inventory Velocity",
        "loadEnabled": true
      },
      "LT Grouping Summary": {
        "queryId": "dbc4531c-20e4-43dc-a008-c1874f6594ef",
        "queryName": "LT Grouping Summary",
        "loadEnabled": true
      }
    },
    "document": "section Section1;\r\nshared #\"Data Update Info\" = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 1\" = Navigation{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXREP_DATA_UPDATE_V\", Kind = \"View\"]}[Data],\r\n  #\"Filtered rows\" = Table.SelectRows(#\"Navigation 2\", each [TABLE_NAME] = \"XXFACTS.XX_INVASCP_FACT\")\r\nin\r\n  #\"Filtered rows\";\r\nshared #\"Time Balance Week\" = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 1\" = Navigation{[Name = \"XXDIMS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XX_ASCP_WEEK_TIMBAL_V\", Kind = \"View\"]}[Data]\r\nin\r\n  #\"Navigation 2\";\r\nshared #\"Inventory Velocity Summary\" = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 1\" = Navigation{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXREP_INVASCP_SUM_V\", Kind = \"View\"]}[Data]\r\nin\r\n  #\"Navigation 2\";\r\nshared #\"Inventory Velocity\" = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 1\" = Navigation{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXREP_INVASCP_V\", Kind = \"View\"]}[Data]\r\nin\r\n  #\"Navigation 2\";\r\nshared #\"LT Grouping Summary\" = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 1\" = Navigation{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXREP_ASCP_LT_GROUPING_V\", Kind = \"View\"]}[Data]\r\nin\r\n  #\"Navigation 2\";\r\n"
  },
  "annotations": [{ "name": "pbi:QueryGroups", "value": "[]" }],
  "entities": [
    {
      "$type": "LocalEntity",
      "name": "Data Update Info",
      "description": "",
      "pbi:refreshPolicy": {
        "$type": "FullRefreshPolicy",
        "location": "Data%20Update%20Info.csv"
      },
      "attributes": [
        { "name": "TABLE_NAME", "dataType": "string" },
        { "name": "DATA_UPDATE_DATE", "dataType": "dateTime" },
        { "name": "DATA_UPDATE_DESC", "dataType": "string" },
        { "name": "DATA_FLOW_REFRESH_DATE", "dataType": "dateTime" }
      ],
      "partitions": [
        {
          "name": "FullRefreshPolicyPartition",
          "refreshTime": "2022-05-16T01:08:02.629011+00:00",
          "location": "https://wabiwuscpcdsa.blob.core.windows.net:443/6b7916ab-8d92-495c-b8d7-19e20de52fda/Data%20Update%20Info.csv?snapshot=2022-05-16T01%3A08%3A01.0913915Z"
        }
      ]
    },
    {
      "$type": "LocalEntity",
      "name": "Time Balance Week",
      "description": "",
      "pbi:refreshPolicy": {
        "$type": "FullRefreshPolicy",
        "location": "Time%20Balance%20Week.csv"
      },
      "attributes": [
        { "name": "FISCAL_PERIOD_KEY", "dataType": "string" },
        { "name": "FISCAL_DIM_ID", "dataType": "double" },
        { "name": "FISCAL_DIM", "dataType": "string" },
        { "name": "FISCAL_DIM_VALUE", "dataType": "string" },
        { "name": "FISCAL_DIM_SORT_VALUE", "dataType": "string" },
        { "name": "FC_YEAR_OFFSET", "dataType": "double" },
        { "name": "FC_QUARTER_OFFSET", "dataType": "double" },
        { "name": "FISCAL_YEAR", "dataType": "string" },
        { "name": "FYFQ", "dataType": "string" },
        { "name": "PERIOD_YEAR", "dataType": "double" },
        { "name": "GL_PERIOD", "dataType": "string" },
        { "name": "FISCAL_WEEK_ID", "dataType": "double" }
      ],
      "partitions": [
        {
          "name": "FullRefreshPolicyPartition",
          "refreshTime": "2022-05-16T01:03:32.0252811+00:00",
          "location": "https://wabiwuscpcdsa.blob.core.windows.net:443/6b7916ab-8d92-495c-b8d7-19e20de52fda/Time%20Balance%20Week.csv?snapshot=2022-05-16T01%3A03%3A17.5199280Z"
        }
      ]
    },
    {
      "$type": "LocalEntity",
      "name": "Inventory Velocity Summary",
      "description": "",
      "pbi:refreshPolicy": {
        "$type": "FullRefreshPolicy",
        "location": "Inventory%20Velocity%20Summary.csv"
      },
      "attributes": [
        { "name": "ENTITY", "dataType": "string" },
        { "name": "ORGANIZATION_CODE", "dataType": "string" },
        { "name": "SUPPLY_SOURCE", "dataType": "string" },
        { "name": "DEMAND_SOURCE", "dataType": "string" },
        { "name": "SEC_REPORTING", "dataType": "string" },
        { "name": "ITEM_TBU", "dataType": "string" },
        { "name": "ITEM_PRODUCT_FAMILY", "dataType": "string" },
        { "name": "PRODUCT_MAP_KEY", "dataType": "string" },
        { "name": "OPERATIONS_REPORTING", "dataType": "string" },
        { "name": "ITEM_TYPE", "dataType": "string" },
        { "name": "ITEM_STATUS", "dataType": "string" },
        { "name": "ACTIVE_OR_INACTIVE", "dataType": "string" },
        { "name": "CURRENT_MRP_ABC_CLASS", "dataType": "string" },
        { "name": "PRODUCT_LINE", "dataType": "string" },
        { "name": "FISCAL_WEEK_KEY", "dataType": "string" },
        { "name": "PERIOD_YEAR", "dataType": "double" },
        { "name": "PERIOD_NAME", "dataType": "string" },
        { "name": "PERIOD_END_DATE", "dataType": "dateTime" },
        { "name": "FISCAL_WEEK_ID", "dataType": "double" },
        { "name": "WEEK_START_DATE", "dataType": "dateTime" },
        { "name": "WEEK_END_DATE", "dataType": "dateTime" },
        { "name": "INVASCP_SUMMARY_KEY", "dataType": "string" },
        { "name": "ONHAND_VALUE", "dataType": "double" },
        { "name": "ONHAND_VALUE_USD", "dataType": "double" },
        { "name": "WIP_DAYS_OF_SUPPLY_COUNT", "dataType": "double" },
        { "name": "ON_ORDER_DAYS_OF_SUPPLY_COUNT", "dataType": "double" },
        { "name": "ON_ORDER_VALUE", "dataType": "double" },
        { "name": "ON_ORDER_VALUE_USD", "dataType": "double" },
        { "name": "WIP_VALUE", "dataType": "double" },
        { "name": "WIP_VALUE_USD", "dataType": "double" },
        { "name": "ONHAND_DAYS_OF_SUPPLY", "dataType": "double" },
        { "name": "SAFETY_STOCK_VALUE", "dataType": "double" },
        { "name": "SAFETY_STOCK_VALUE_USD", "dataType": "double" },
        { "name": "ON_ORDER_DAYS_OF_SUPPLY", "dataType": "double" },
        { "name": "WIP_DAYS_OF_SUPPLY", "dataType": "double" },
        { "name": "RECORD_COUNT", "dataType": "double" }
      ],
      "partitions": [
        {
          "name": "FullRefreshPolicyPartition",
          "refreshTime": "2022-05-16T01:26:16.4844621+00:00",
          "location": "https://wabiwuscpcdsa.blob.core.windows.net:443/6b7916ab-8d92-495c-b8d7-19e20de52fda/Inventory%20Velocity%20Summary.csv?snapshot=2022-05-16T01%3A25%3A27.4841021Z"
        }
      ]
    },
    {
      "$type": "LocalEntity",
      "name": "Inventory Velocity",
      "description": "",
      "pbi:refreshPolicy": {
        "$type": "FullRefreshPolicy",
        "location": "Inventory%20Velocity.csv"
      },
      "attributes": [
        { "name": "ACCEPTABLE_EARLY_DAYS", "dataType": "double" },
        { "name": "ACTIVE_OR_INACTIVE", "dataType": "string" },
        { "name": "ACTIVE_SUPPLIER_LT", "dataType": "double" },
        { "name": "ATTRIBUTE_LT", "dataType": "double" },
        { "name": "AVE_DAILY_USAGE_26_WEEKS", "dataType": "double" },
        { "name": "AVERAGE_DAILY_DEMAND", "dataType": "double" },
        { "name": "AVG_DAILY_DEMAND_ELSE_USAGE", "dataType": "double" },
        { "name": "BLANKET_DAYS_SUPPLY_REMAINING", "dataType": "double" },
        { "name": "BUYER", "dataType": "string" },
        { "name": "COEFF_USAGE_26_WEEKS", "dataType": "double" },
        { "name": "COST_SOURCE_TYPE", "dataType": "string" },
        { "name": "CUMULATIVE_LT", "dataType": "double" },
        { "name": "CUMULATIVE_MFG_LT", "dataType": "double" },
        { "name": "CURRENCY_CODE", "dataType": "string" },
        { "name": "CURRENCY_RATE", "dataType": "double" },
        { "name": "CURRENT_ABC_CLASS", "dataType": "string" },
        { "name": "CURRENT_MRP_ABC_CLASS", "dataType": "string" },
        { "name": "DATE_RUN", "dataType": "dateTime" },
        { "name": "DAYS_0_20", "dataType": "double" },
        { "name": "DAYS_20_40", "dataType": "double" },
        { "name": "DAYS_40_PLUS", "dataType": "double" },
        { "name": "DEMAND_SOURCE", "dataType": "string" },
        { "name": "EXTENDED_VALUE", "dataType": "double" },
        { "name": "EXTENDED_VALUE_USD", "dataType": "double" },
        { "name": "FIN_PRODUCT_FAMILY", "dataType": "string" },
        { "name": "FIN_PRODUCT_GROUP", "dataType": "string" },
        { "name": "FIXED_DAYS_SUPPLY", "dataType": "double" },
        { "name": "FIXED_DAYS_SUPPLY_DAYS", "dataType": "double" },
        { "name": "FIXED_LOT_MULTP_SUP_DAYS", "dataType": "double" },
        { "name": "FIXED_LOT_SIZE_MULTIPLIER", "dataType": "double" },
        { "name": "FIXED_ORDER_QTY", "dataType": "double" },
        { "name": "FIXED_ORDER_SUPPLY_DAYS", "dataType": "double" },
        { "name": "FREEZE_DATA", "dataType": "string" },
        { "name": "GROSS_INVENTORY_TURNS", "dataType": "double" },
        { "name": "HIGH_ORDER_MODIFR_SUP_DAYS", "dataType": "double" },
        { "name": "INTRANSIT_QUANTITY", "dataType": "double" },
        { "name": "INTRANSIT_VALUE", "dataType": "double" },
        { "name": "INTRANSIT_VALUE_USD", "dataType": "double" },
        { "name": "INVASCP_KEY", "dataType": "string" },
        { "name": "INVENTORY_PLANNING_METHOD", "dataType": "string" },
        { "name": "INVENTORY_QUANTITY", "dataType": "double" },
        { "name": "INVENTORY_VALUE", "dataType": "double" },
        { "name": "INVENTORY_VALUE_USD", "dataType": "double" },
        { "name": "IR_PO_QTY", "dataType": "double" },
        { "name": "IR_PO_VALUE", "dataType": "double" },
        { "name": "IR_PO_VALUE_USD", "dataType": "double" },
        { "name": "ITEM_COST", "dataType": "double" },
        { "name": "ITEM_COST_USD", "dataType": "double" },
        { "name": "ITEM_DESCRIPTION", "dataType": "string" },
        { "name": "ITEM_NUMBER", "dataType": "string" },
        { "name": "ITEM_STATUS", "dataType": "string" },
        { "name": "ITEM_TYPE", "dataType": "string" },
        { "name": "ITEM_TYPE_CODE", "dataType": "string" },
        { "name": "KANBAN_ITEM", "dataType": "string" },
        { "name": "KANBAN_REPL_LT", "dataType": "double" },
        { "name": "KANBAN_TYPE", "dataType": "string" },
        { "name": "LAST_ABC_CLASS", "dataType": "string" },
        { "name": "LAST_MRP_ABC_CLASS", "dataType": "string" },
        { "name": "LT_GROUPING", "dataType": "string" },
        { "name": "MAS_FAMILY", "dataType": "string" },
        { "name": "MAS_FORECAST_FIELD", "dataType": "string" },
        { "name": "MAS_LINE", "dataType": "string" },
        { "name": "MAS_TBU", "dataType": "string" },
        { "name": "MAX_ORDER_QTY", "dataType": "double" },
        { "name": "ME_FLAG", "dataType": "string" },
        { "name": "MIN_MAX_ITEM", "dataType": "string" },
        { "name": "MIN_MAX_MAX_QTY", "dataType": "double" },
        { "name": "MIN_MAX_MIN_QTY", "dataType": "double" },
        { "name": "MIN_MAX_PLANNED", "dataType": "string" },
        { "name": "MIN_ORDER_QTY", "dataType": "double" },
        { "name": "MIN_ORDER_SUPPLY_DAYS", "dataType": "double" },
        { "name": "MRP_ACTIVE_OR_INACTIVE", "dataType": "string" },
        { "name": "MRP_PLANNING_METHOD", "dataType": "string" },
        { "name": "NUMBER_OF_OPEN_BLANKETS", "dataType": "double" },
        { "name": "ON_HAND_DAYS_OF_SUPPLY", "dataType": "double" },
        { "name": "ON_ORDER_DAYS_OF_SUPPLY", "dataType": "double" },
        { "name": "ONHAND_QTY_ASSET", "dataType": "double" },
        { "name": "ONHAND_QTY_NON_ASSET", "dataType": "double" },
        { "name": "ONORDER_PO_QTY", "dataType": "double" },
        { "name": "ONORDER_PO_VALUE", "dataType": "double" },
        { "name": "ONORDER_PO_VALUE_USD", "dataType": "double" },
        { "name": "OPEN_BLANKETS", "dataType": "string" },
        { "name": "OPEN_PO_QTY", "dataType": "double" },
        { "name": "OPEN_PO_VALUE", "dataType": "double" },
        { "name": "OPEN_PO_VALUE_USD", "dataType": "double" },
        { "name": "OPERATIONS_REPORTING", "dataType": "string" },
        { "name": "ORA_PRODUCT_FAMILY", "dataType": "string" },
        { "name": "ORA_PRODUCT_GROUP", "dataType": "string" },
        { "name": "ORG_FAMILY", "dataType": "string" },
        { "name": "ORG_FORECAST_FIELD", "dataType": "string" },
        { "name": "ORG_LINE", "dataType": "string" },
        { "name": "ORG_TBU", "dataType": "string" },
        { "name": "ORGANIZATION_CODE", "dataType": "string" },
        { "name": "OSP_ASSEMBLIES", "dataType": "string" },
        { "name": "PERIOD_END_DATE", "dataType": "dateTime" },
        { "name": "PERIOD_NAME", "dataType": "string" },
        { "name": "PERIOD_YEAR", "dataType": "double" },
        { "name": "PLANNER", "dataType": "string" },
        { "name": "PLANNING_METHOD", "dataType": "string" },
        { "name": "PROCESSING_LEAD_TIME", "dataType": "double" },
        { "name": "PROJ_SPEND_NEXT_26_WEEKS", "dataType": "double" },
        { "name": "PROJ_SPEND_NEXT_26_WEEKS_USD", "dataType": "double" },
        { "name": "PURCH_ASL_LT", "dataType": "double" },
        { "name": "PURCHASING_LIST_PRICE", "dataType": "double" },
        { "name": "PURCHASING_LIST_PRICE_USD", "dataType": "double" },
        { "name": "QUARTER_NUM", "dataType": "double" },
        { "name": "RECEIVING_QUANTITY", "dataType": "double" },
        { "name": "RECEIVING_VALUE", "dataType": "double" },
        { "name": "RECEIVING_VALUE_USD", "dataType": "double" },
        { "name": "SAFETY_STOCK_QTY", "dataType": "double" },
        { "name": "SAFETY_STOCK_VALUE", "dataType": "double" },
        { "name": "SAFETY_STOCK_VALUE_USD", "dataType": "double" },
        { "name": "SEC_REPORTING", "dataType": "string" },
        { "name": "SHRINKAGE", "dataType": "string" },
        { "name": "SO_USAGE_13_WEEKS", "dataType": "double" },
        { "name": "SO_USAGE_26_WEEKS", "dataType": "double" },
        { "name": "SOURCING_COMMODITY", "dataType": "string" },
        { "name": "SPC_USAGE_VOLUME_13_WEEKS_USD", "dataType": "double" },
        { "name": "SR_ASL_STATUS", "dataType": "string" },
        { "name": "SR_PCT", "dataType": "string" },
        { "name": "SR_VENDOR", "dataType": "string" },
        { "name": "SR_VENDOR_SITE_CODE", "dataType": "string" },
        { "name": "SR_VNDR_SRC_ORG", "dataType": "string" },
        { "name": "STD_DEV_USAGE_26_WEEKS", "dataType": "double" },
        { "name": "SUBINVENTORY_MIN_MAX_LT", "dataType": "double" },
        { "name": "SUM_REMAINING_AMOUNT", "dataType": "double" },
        { "name": "SUM_REMAINING_QTY_CALCULATED", "dataType": "double" },
        { "name": "SUM_USD_REMAINING_AMOUNT", "dataType": "double" },
        { "name": "SUPPLY_SOURCE", "dataType": "string" },
        { "name": "TARGET_DAYS_OF_SUPPLY", "dataType": "double" },
        { "name": "TARGET_DAYS_OF_SUPPLY_QTY", "dataType": "double" },
        { "name": "TARGET_DAYS_OF_SUPPLY_SAVINGS", "dataType": "double" },
        { "name": "TARGET_DAYS_OF_SUPPLY_VALUE", "dataType": "double" },
        { "name": "TOTAL_DAYS_OF_SUPPLY", "dataType": "double" },
        { "name": "TOTAL_GR_26_WEEKS", "dataType": "double" },
        { "name": "TOTAL_ONHAND_QTY", "dataType": "double" },
        { "name": "TOTAL_QUANTITY", "dataType": "double" },
        { "name": "TOTAL_USAGE_13_WEEKS", "dataType": "double" },
        { "name": "TOTAL_USAGE_26_WEEKS", "dataType": "double" },
        { "name": "TXN_ACTIVE_OR_INACTIVE", "dataType": "string" },
        { "name": "UOM", "dataType": "string" },
        { "name": "UOM_CODE", "dataType": "string" },
        { "name": "USAGE_WEEK_1", "dataType": "double" },
        { "name": "USAGE_WEEK_10", "dataType": "double" },
        { "name": "USAGE_WEEK_11", "dataType": "double" },
        { "name": "USAGE_WEEK_12", "dataType": "double" },
        { "name": "USAGE_WEEK_13", "dataType": "double" },
        { "name": "USAGE_WEEK_14", "dataType": "double" },
        { "name": "USAGE_WEEK_15", "dataType": "double" },
        { "name": "USAGE_WEEK_16", "dataType": "double" },
        { "name": "USAGE_WEEK_17", "dataType": "double" },
        { "name": "USAGE_WEEK_18", "dataType": "double" },
        { "name": "USAGE_WEEK_19", "dataType": "double" },
        { "name": "USAGE_WEEK_2", "dataType": "double" },
        { "name": "USAGE_WEEK_20", "dataType": "double" },
        { "name": "USAGE_WEEK_21", "dataType": "double" },
        { "name": "USAGE_WEEK_22", "dataType": "double" },
        { "name": "USAGE_WEEK_23", "dataType": "double" },
        { "name": "USAGE_WEEK_24", "dataType": "double" },
        { "name": "USAGE_WEEK_25", "dataType": "double" },
        { "name": "USAGE_WEEK_26", "dataType": "double" },
        { "name": "USAGE_WEEK_3", "dataType": "double" },
        { "name": "USAGE_WEEK_4", "dataType": "double" },
        { "name": "USAGE_WEEK_5", "dataType": "double" },
        { "name": "USAGE_WEEK_6", "dataType": "double" },
        { "name": "USAGE_WEEK_7", "dataType": "double" },
        { "name": "USAGE_WEEK_8", "dataType": "double" },
        { "name": "USAGE_WEEK_9", "dataType": "double" },
        { "name": "WEEKLY_GROSS_REQS_WEEK_0", "dataType": "double" },
        { "name": "WEEKLY_GROSS_REQS_WEEK_1", "dataType": "double" },
        { "name": "WEEKLY_GROSS_REQS_WEEK_10", "dataType": "double" },
        { "name": "WEEKLY_GROSS_REQS_WEEK_11", "dataType": "double" },
        { "name": "WEEKLY_GROSS_REQS_WEEK_12", "dataType": "double" },
        { "name": "WEEKLY_GROSS_REQS_WEEK_13", "dataType": "double" },
        { "name": "WEEKLY_GROSS_REQS_WEEK_14", "dataType": "double" },
        { "name": "WEEKLY_GROSS_REQS_WEEK_15", "dataType": "double" },
        { "name": "WEEKLY_GROSS_REQS_WEEK_16", "dataType": "double" },
        { "name": "WEEKLY_GROSS_REQS_WEEK_17", "dataType": "double" },
        { "name": "WEEKLY_GROSS_REQS_WEEK_18", "dataType": "double" },
        { "name": "WEEKLY_GROSS_REQS_WEEK_19", "dataType": "double" },
        { "name": "WEEKLY_GROSS_REQS_WEEK_2", "dataType": "double" },
        { "name": "WEEKLY_GROSS_REQS_WEEK_20", "dataType": "double" },
        { "name": "WEEKLY_GROSS_REQS_WEEK_21", "dataType": "double" },
        { "name": "WEEKLY_GROSS_REQS_WEEK_22", "dataType": "double" },
        { "name": "WEEKLY_GROSS_REQS_WEEK_23", "dataType": "double" },
        { "name": "WEEKLY_GROSS_REQS_WEEK_24", "dataType": "double" },
        { "name": "WEEKLY_GROSS_REQS_WEEK_25", "dataType": "double" },
        { "name": "WEEKLY_GROSS_REQS_WEEK_26", "dataType": "double" },
        { "name": "WEEKLY_GROSS_REQS_WEEK_3", "dataType": "double" },
        { "name": "WEEKLY_GROSS_REQS_WEEK_4", "dataType": "double" },
        { "name": "WEEKLY_GROSS_REQS_WEEK_5", "dataType": "double" },
        { "name": "WEEKLY_GROSS_REQS_WEEK_6", "dataType": "double" },
        { "name": "WEEKLY_GROSS_REQS_WEEK_7", "dataType": "double" },
        { "name": "WEEKLY_GROSS_REQS_WEEK_8", "dataType": "double" },
        { "name": "WEEKLY_GROSS_REQS_WEEK_9", "dataType": "double" },
        { "name": "WIP_DAYS_OF_SUPPLY", "dataType": "double" },
        { "name": "WIP_IN_PROCESS_QTY", "dataType": "double" },
        { "name": "WIP_IN_PROCESS_VALUE", "dataType": "double" },
        { "name": "WIP_IN_PROCESS_VALUE_USD", "dataType": "double" },
        { "name": "WO_USAGE_13_WEEKS", "dataType": "double" },
        { "name": "WO_USAGE_26_WEEKS", "dataType": "double" },
        { "name": "ITEM_TBU", "dataType": "string" },
        { "name": "ITEM_PRODUCT_FAMILY", "dataType": "string" },
        { "name": "PRODUCT_MAP_KEY", "dataType": "string" },
        { "name": "PRODUCT_LINE", "dataType": "string" },
        { "name": "FISCAL_WEEK_KEY", "dataType": "string" },
        { "name": "WEEK_START_DATE", "dataType": "dateTime" },
        { "name": "WEEK_END_DATE", "dataType": "dateTime" },
        { "name": "ITEM_ORG_KEY_ID", "dataType": "string" },
        { "name": "ITEM_ORG_KEY_CODE", "dataType": "string" },
        { "name": "INVASCP_SUMMARY_KEY", "dataType": "string" },
        { "name": "ONHAND_VALUE_USD", "dataType": "double" },
        { "name": "WIP_DAYS_OF_SUPPLY_COUNT", "dataType": "double" },
        { "name": "ON_ORDER_DAYS_OF_SUPPLY_COUNT", "dataType": "double" },
        { "name": "ON_ORDER_VALUE_USD", "dataType": "double" },
        { "name": "WIP_VALUE_USD", "dataType": "double" },
        { "name": "ONHAND_DAYS_OF_SUPPLY", "dataType": "double" }
      ],
      "partitions": [
        {
          "name": "FullRefreshPolicyPartition",
          "refreshTime": "2022-05-16T01:57:49.5667226+00:00",
          "location": "https://wabiwuscpcdsa.blob.core.windows.net:443/6b7916ab-8d92-495c-b8d7-19e20de52fda/Inventory%20Velocity.csv?snapshot=2022-05-16T01%3A53%3A13.2894593Z"
        }
      ]
    },
    {
      "$type": "LocalEntity",
      "name": "LT Grouping Summary",
      "description": "",
      "pbi:refreshPolicy": {
        "$type": "FullRefreshPolicy",
        "location": "LT%20Grouping%20Summary.csv"
      },
      "attributes": [
        { "name": "FISCAL_DIM_VALUE", "dataType": "string" },
        { "name": "FISCAL_DIM_SORT_VALUE", "dataType": "string" },
        { "name": "PERIOD_YEAR", "dataType": "double" },
        { "name": "FISCAL_WEEK_ID", "dataType": "double" },
        { "name": "LT_GROUPING_ID", "dataType": "double" },
        { "name": "LT_GROUPING", "dataType": "string" },
        { "name": "LT_GROUPING_DESC", "dataType": "string" },
        { "name": "ORGANIZATION_CODE", "dataType": "string" },
        { "name": "PLANNING_METHOD", "dataType": "string" },
        { "name": "CURRENT_MRP_ABC_CLASS", "dataType": "string" },
        { "name": "SR_VNDR_SRC_ORG", "dataType": "string" },
        { "name": "ITEM_TYPE", "dataType": "string" },
        { "name": "ACTIVE_OR_INACTIVE", "dataType": "string" },
        { "name": "INV_VALUE", "dataType": "double" },
        { "name": "ITEM_COUNT", "dataType": "double" }
      ],
      "partitions": [
        {
          "name": "FullRefreshPolicyPartition",
          "refreshTime": "2022-05-16T01:09:58.9460443+00:00",
          "location": "https://wabiwuscpcdsa.blob.core.windows.net:443/6b7916ab-8d92-495c-b8d7-19e20de52fda/LT%20Grouping%20Summary.csv?snapshot=2022-05-16T01%3A09%3A50.5160645Z"
        }
      ]
    }
  ]
}
