{"name":"M2.0_DETAILS_EXT_REVENUE","description":"M2.0 Details External Revenue ( refreshed weekly - 2 quarters)","version":"1.0","culture":"en-US","modifiedTime":"2021-11-29T00:55:04.3701846+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"XXREP_M2_REVENUE_ITEMS_V":{"queryId":"87398495-f7e8-4cb0-b0a4-a28500a24b84","queryName":"XXREP_M2_REVENUE_ITEMS_V","loadEnabled":true},"XXREP_M2_REVENUE_SUM_V":{"queryId":"85ab8ac4-9de5-4345-9325-ab3577aed22e","queryName":"XXREP_M2_REVENUE_SUM_V","loadEnabled":true},"XXREP_M2_EXT_REVENUE_V":{"queryId":"91e22769-eb4e-4759-9b12-cb420020966f","queryName":"XXREP_M2_EXT_REVENUE_V","loadEnabled":true},"Data Update Info":{"queryId":"b2a2ffe5-c63f-42fe-ba27-3c3898b25418","queryName":"Data Update Info","loadEnabled":true}},"document":"section Section1;\r\nshared XXREP_M2_REVENUE_ITEMS_V = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 1\" = Navigation{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXREP_M2_REVENUE_ITEMS_V\", Kind = \"View\"]}[Data]\r\nin\r\n  #\"Navigation 2\";\r\nshared XXREP_M2_REVENUE_SUM_V = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 1\" = Navigation{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXREP_M2_REVENUE_SUM_V\", Kind = \"View\"]}[Data]\r\nin\r\n  #\"Navigation 2\";\r\nshared XXREP_M2_EXT_REVENUE_V = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 1\" = Navigation{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXREP_M2_EXT_REVENUE_V\", Kind = \"View\"]}[Data]\r\nin\r\n  #\"Navigation 2\";\r\nshared #\"Data Update Info\" = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 1\" = Navigation{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXREP_DATA_UPDATE_V\", Kind = \"View\"]}[Data],\r\n  #\"Filtered rows\" = Table.SelectRows(#\"Navigation 2\", each [TABLE_NAME] = \"XXCOH.XXCOH_M2_REPORT_TB\")\r\nin\r\n  #\"Filtered rows\";\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"XXREP_M2_REVENUE_ITEMS_V","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"XXREP_M2_REVENUE_ITEMS_V.csv"},"attributes":[{"name":"ITEM_NUMBER","dataType":"string"},{"name":"ITEM_DESCRIPTION","dataType":"string"},{"name":"ITEM_NUMBER_DESC","dataType":"string"},{"name":"PRODUCT_TBU","dataType":"string"},{"name":"PRODUCT_FAMILY","dataType":"string"},{"name":"PRODUCT_FORECAST_FIELD","dataType":"string"},{"name":"PRODUCT_LINE","dataType":"string"},{"name":"COMMODITY","dataType":"string"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"ITEM_ORG_KEY_CODE","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-15T23:30:44.5962993+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/c9991134-95b0-4cfb-b388-c4cbec23232a/XXREP_M2_REVENUE_ITEMS_V.csv?snapshot=2022-05-15T23%3A30%3A42.5606433Z"}]},{"$type":"LocalEntity","name":"XXREP_M2_REVENUE_SUM_V","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"XXREP_M2_REVENUE_SUM_V.csv"},"attributes":[{"name":"ENTITY","dataType":"string"},{"name":"ACCT","dataType":"string"},{"name":"OPERATING_UNIT_ID","dataType":"double"},{"name":"PRODUCT_TBU","dataType":"string"},{"name":"PRODUCT_FAMILY","dataType":"string"},{"name":"PRODUCT_FORECAST_FIELD","dataType":"string"},{"name":"PRODUCT_LINE","dataType":"string"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"ITEM_NUMBER","dataType":"string"},{"name":"ITEM_DESCRIPTION","dataType":"string"},{"name":"ITEM_ORG_KEY_CODE","dataType":"string"},{"name":"COMMODITY","dataType":"string"},{"name":"LINE_TYPE_GROUPING","dataType":"string"},{"name":"MASTER_CUSTOMER_NAME","dataType":"string"},{"name":"HFM_PRODUCT","dataType":"string"},{"name":"GL_PERIOD","dataType":"string"},{"name":"PERIOD_END_DATE","dataType":"dateTime"},{"name":"PERIOD_START_DATE","dataType":"dateTime"},{"name":"QUARTER_START_DATE","dataType":"dateTime"},{"name":"QUARTER_END_DATE","dataType":"dateTime"},{"name":"YEAR_START_DATE","dataType":"dateTime"},{"name":"YEAR_END_DATE","dataType":"dateTime"},{"name":"FISCAL_YEAR","dataType":"string"},{"name":"QUARTER_NUM","dataType":"double"},{"name":"FISCAL_QUARTER","dataType":"string"},{"name":"FYFQ","dataType":"string"},{"name":"DATA_UPDATE_DATE","dataType":"dateTime"},{"name":"DATA_UPDATE_DESC","dataType":"string"},{"name":"TRAN_QTY","dataType":"double"},{"name":"USD_AMT","dataType":"double"},{"name":"DRILL_TO_DETAIL_KEY","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-15T23:43:36.9567402+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/c9991134-95b0-4cfb-b388-c4cbec23232a/XXREP_M2_REVENUE_SUM_V.csv?snapshot=2022-05-15T23%3A42%3A29.2556823Z"}]},{"$type":"LocalEntity","name":"XXREP_M2_EXT_REVENUE_V","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"XXREP_M2_EXT_REVENUE_V.csv"},"attributes":[{"name":"ENTITY","dataType":"string"},{"name":"DEPT","dataType":"string"},{"name":"ACCT","dataType":"string"},{"name":"PROJ","dataType":"string"},{"name":"INTERCO","dataType":"string"},{"name":"TBD","dataType":"string"},{"name":"CODE_COMBO_ID","dataType":"double"},{"name":"GL_PERIOD","dataType":"string"},{"name":"JE_BATCH_ID","dataType":"double"},{"name":"JE_HEADER_ID","dataType":"double"},{"name":"JE_LINE_NUM","dataType":"double"},{"name":"CAT_SEGMENT1","dataType":"string"},{"name":"CAT_SEGMENT2","dataType":"string"},{"name":"CAT_SEGMENT3","dataType":"string"},{"name":"TRANSACTION_ID","dataType":"double"},{"name":"TRANSACTION_SOURCE","dataType":"string"},{"name":"ENTERED_DR","dataType":"double"},{"name":"ENTERED_CR","dataType":"double"},{"name":"ACCOUNTED_DR","dataType":"double"},{"name":"ACCOUNTED_CR","dataType":"double"},{"name":"JE_ENTERED_DR","dataType":"double"},{"name":"JE_ENTERED_CR","dataType":"double"},{"name":"JE_ACCOUNTED_DR","dataType":"double"},{"name":"JE_ACCOUNTED_CR","dataType":"double"},{"name":"TRANS_DATE","dataType":"dateTime"},{"name":"JE_AMOUNT","dataType":"double"},{"name":"ITEM_TYPE","dataType":"string"},{"name":"CURRENCY_CODE","dataType":"string"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"ORGANIZATION_ID","dataType":"double"},{"name":"ITEM_CATEGORY_ID","dataType":"double"},{"name":"CREATION_DATE","dataType":"dateTime"},{"name":"SET_OF_BOOKS_ID","dataType":"double"},{"name":"ORG_ID","dataType":"double"},{"name":"SALES_SERVICE_CODE","dataType":"string"},{"name":"TRX_TYPE_ID","dataType":"double"},{"name":"TRX_TYPE_NAME","dataType":"string"},{"name":"ORDER_TYPE","dataType":"string"},{"name":"ORDER_LINE_TYPE","dataType":"string"},{"name":"ORDER_NUMBER","dataType":"double"},{"name":"ORDER_LINE_ID","dataType":"double"},{"name":"ORDER_HEADER_ID","dataType":"double"},{"name":"ORDER_LINE","dataType":"double"},{"name":"ORDER_LINE_TYPE_ID","dataType":"double"},{"name":"ORDER_TYPE_ID","dataType":"double"},{"name":"TRAN_QTY","dataType":"double"},{"name":"CONVERSION_RATE","dataType":"double"},{"name":"CUSTOMER_ID","dataType":"double"},{"name":"AR_TRAN_ID","dataType":"double"},{"name":"PERIOD_YEAR","dataType":"double"},{"name":"QUARTER_NUM","dataType":"double"},{"name":"ACCOUNTED_NET","dataType":"double"},{"name":"ACCOUNTED_NET_USD","dataType":"double"},{"name":"ITEM_COST","dataType":"double"},{"name":"PRIMARY_INV_ORG_CODE","dataType":"string"},{"name":"EXT_ORDER_ID","dataType":"double"},{"name":"EXT_CUSTOMER_ID","dataType":"double"},{"name":"M20_TBU","dataType":"string"},{"name":"M20_PFC","dataType":"string"},{"name":"APPLICATION_CODE","dataType":"string"},{"name":"TRANSACTION_SOURCE_NAME","dataType":"string"},{"name":"HFM_ACCOUNT","dataType":"string"},{"name":"HFM_PRODUCT","dataType":"string"},{"name":"HFM_PRODUCT_GROUP","dataType":"string"},{"name":"HFM_PRODUCT_SEQ","dataType":"double"},{"name":"MARKET_CODE","dataType":"string"},{"name":"TRN_ORDER_NUMBER","dataType":"double"},{"name":"ORG_TBU","dataType":"string"},{"name":"ORG_PFC","dataType":"string"},{"name":"SFDC_WO_ID","dataType":"string"},{"name":"SFDC_CASE_ID","dataType":"string"},{"name":"PERIOD_END_DATE","dataType":"dateTime"},{"name":"USD_ASP","dataType":"double"},{"name":"LOC_ASP","dataType":"double"},{"name":"MONTH_START_DATE","dataType":"dateTime"},{"name":"MONTH_END_DATE","dataType":"dateTime"},{"name":"QUARTER_START_DATE","dataType":"dateTime"},{"name":"QUARTER_END_DATE","dataType":"dateTime"},{"name":"YEAR_START_DATE","dataType":"dateTime"},{"name":"YEAR_END_DATE","dataType":"dateTime"},{"name":"FISCAL_YEAR","dataType":"string"},{"name":"QUARTER_NO","dataType":"double"},{"name":"FISCAL_QUARTER","dataType":"string"},{"name":"FYFQ","dataType":"string"},{"name":"DATA_UPDATE_DATE","dataType":"dateTime"},{"name":"DATA_UPDATE_DESC","dataType":"string"},{"name":"OPERATING_UNIT_ID","dataType":"double"},{"name":"ITEM_NUMBER","dataType":"string"},{"name":"ITEM_DESCRIPTION","dataType":"string"},{"name":"MASTER_CUSTOMER_NAME","dataType":"string"},{"name":"CUSTOMER_NAME","dataType":"string"},{"name":"CUSTOMER_NUMBER","dataType":"string"},{"name":"PRODUCT_TBU","dataType":"string"},{"name":"PRODUCT_FAMILY","dataType":"string"},{"name":"PRODUCT_FORECAST_FIELD","dataType":"string"},{"name":"PRODUCT_LINE","dataType":"string"},{"name":"COMMODITY","dataType":"string"},{"name":"LINE_TYPE_GROUPING","dataType":"string"},{"name":"DRILL_TO_DETAIL_KEY","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-15T23:49:12.3777488+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/c9991134-95b0-4cfb-b388-c4cbec23232a/XXREP_M2_EXT_REVENUE_V.csv?snapshot=2022-05-15T23%3A48%3A19.0324012Z"}]},{"$type":"LocalEntity","name":"Data Update Info","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Data%20Update%20Info.csv"},"attributes":[{"name":"TABLE_NAME","dataType":"string"},{"name":"DATA_UPDATE_DATE","dataType":"dateTime"},{"name":"DATA_UPDATE_DESC","dataType":"string"},{"name":"DATA_FLOW_REFRESH_DATE","dataType":"dateTime"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-15T23:30:22.383842+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/c9991134-95b0-4cfb-b388-c4cbec23232a/Data%20Update%20Info.csv?snapshot=2022-05-15T23%3A30%3A20.2933360Z"}]}]}