{"name":"Reduced Size Trial","description":"Workflow filtering to reduce data size.","version":"1.0","culture":"en-US","modifiedTime":"2021-09-07T17:18:24.7582567+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"Fields_Reduced_INVVELO_TRIAL":{"queryId":"46a31f02-0713-4368-ad18-e449608e1a9d","queryName":"Fields_Reduced_INVVELO_TRIAL","loadEnabled":true}},"document":"section Section1;\r\nshared Fields_Reduced_INVVELO_TRIAL = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 1\" = Navigation{[Name = \"XXFACTS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XX_INVASCP_FACT\", Kind = \"Table\"]}[Data],\r\n  #\"Filtered rows\" = Table.SelectRows(#\"Navigation 2\", each [PERIOD_YEAR] = 2021)\r\nin\r\n  #\"Filtered rows\";\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"Fields_Reduced_INVVELO_TRIAL","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Fields_Reduced_INVVELO_TRIAL.csv"},"attributes":[{"name":"DATE_RUN","dataType":"dateTime"},{"name":"PERIOD_YEAR","dataType":"double"},{"name":"PERIOD_NAME","dataType":"string"},{"name":"PERIOD_END_DATE","dataType":"dateTime"},{"name":"QUARTER_NUM","dataType":"double"},{"name":"FISCAL_WEEK_ID","dataType":"double"},{"name":"ME_WEEK_ID","dataType":"double"},{"name":"ME_FLAG","dataType":"string"},{"name":"FREEZE_DATA","dataType":"string"},{"name":"OSP_ASSEMBLIES","dataType":"string"},{"name":"PLANNING_METHOD","dataType":"string"},{"name":"ORGANIZATION_ID","dataType":"double"},{"name":"ORGANIZATION_CODE","dataType":"string"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"ITEM_NUMBER","dataType":"string"},{"name":"ITEM_DESCRIPTION","dataType":"string"},{"name":"UOM_CODE","dataType":"string"},{"name":"UOM","dataType":"string"},{"name":"ITEM_STATUS","dataType":"string"},{"name":"ITEM_TYPE_CODE","dataType":"string"},{"name":"ITEM_TYPE","dataType":"string"},{"name":"COST_SOURCE_TYPE","dataType":"string"},{"name":"SUPPLY_SOURCE","dataType":"string"},{"name":"DEMAND_SOURCE","dataType":"string"},{"name":"SEC_REPORTING","dataType":"string"},{"name":"OPERATIONS_REPORTING","dataType":"string"},{"name":"LAST_ABC_CLASS","dataType":"string"},{"name":"CURRENT_ABC_CLASS","dataType":"string"},{"name":"LAST_MRP_ABC_CLASS","dataType":"string"},{"name":"CURRENT_MRP_ABC_CLASS","dataType":"string"},{"name":"MAS_TBU","dataType":"string"},{"name":"MAS_FAMILY","dataType":"string"},{"name":"MAS_LINE","dataType":"string"},{"name":"MAS_FORECAST_FIELD","dataType":"string"},{"name":"ORG_TBU","dataType":"string"},{"name":"ORG_FAMILY","dataType":"string"},{"name":"ORG_LINE","dataType":"string"},{"name":"ORG_FORECAST_FIELD","dataType":"string"},{"name":"SOURCING_COMMODITY","dataType":"string"},{"name":"PLANNER","dataType":"string"},{"name":"BUYER_ID","dataType":"double"},{"name":"BUYER","dataType":"string"},{"name":"INVENTORY_PLANNING_METHOD","dataType":"string"},{"name":"MIN_MAX_MIN_QTY","dataType":"double"},{"name":"MIN_MAX_MAX_QTY","dataType":"double"},{"name":"MRP_PLANNING_METHOD","dataType":"string"},{"name":"MIN_ORDER_QTY","dataType":"double"},{"name":"MAX_ORDER_QTY","dataType":"double"},{"name":"FIXED_ORDER_QTY","dataType":"double"},{"name":"FIXED_DAYS_SUPPLY","dataType":"double"},{"name":"FIXED_LOT_SIZE_MULTIPLIER","dataType":"double"},{"name":"ACCEPTABLE_EARLY_DAYS","dataType":"double"},{"name":"SHRINKAGE","dataType":"string"},{"name":"SR_VENDOR_ID","dataType":"double"},{"name":"SR_VENDOR","dataType":"string"},{"name":"SR_VENDOR_SITE_ID","dataType":"double"},{"name":"SR_VENDOR_SITE_CODE","dataType":"string"},{"name":"SR_PCT","dataType":"string"},{"name":"SR_ASL_STATUS","dataType":"string"},{"name":"SR_VNDR_SRC_ORG","dataType":"string"},{"name":"PROCESSING_LEAD_TIME","dataType":"double"},{"name":"ITEM_COST_USD","dataType":"double"},{"name":"ITEM_COST","dataType":"double"},{"name":"CURRENCY_CODE","dataType":"string"},{"name":"CURRENCY_RATE","dataType":"double"},{"name":"OPEN_PO_QTY","dataType":"double"},{"name":"OPEN_PO_VALUE","dataType":"double"},{"name":"OPEN_PO_VALUE_USD","dataType":"double"},{"name":"SAFETY_STOCK_QTY","dataType":"double"},{"name":"SAFETY_STOCK_VALUE","dataType":"double"},{"name":"SAFETY_STOCK_VALUE_USD","dataType":"double"},{"name":"CUMULATIVE_MFG_LT","dataType":"double"},{"name":"CUMULATIVE_LT","dataType":"double"},{"name":"WEEKLY_GROSS_REQS_WEEK_0","dataType":"double"},{"name":"WEEKLY_GROSS_REQS_WEEK_1","dataType":"double"},{"name":"WEEKLY_GROSS_REQS_WEEK_2","dataType":"double"},{"name":"WEEKLY_GROSS_REQS_WEEK_3","dataType":"double"},{"name":"WEEKLY_GROSS_REQS_WEEK_4","dataType":"double"},{"name":"WEEKLY_GROSS_REQS_WEEK_5","dataType":"double"},{"name":"WEEKLY_GROSS_REQS_WEEK_6","dataType":"double"},{"name":"WEEKLY_GROSS_REQS_WEEK_7","dataType":"double"},{"name":"WEEKLY_GROSS_REQS_WEEK_8","dataType":"double"},{"name":"WEEKLY_GROSS_REQS_WEEK_9","dataType":"double"},{"name":"WEEKLY_GROSS_REQS_WEEK_10","dataType":"double"},{"name":"WEEKLY_GROSS_REQS_WEEK_11","dataType":"double"},{"name":"WEEKLY_GROSS_REQS_WEEK_12","dataType":"double"},{"name":"WEEKLY_GROSS_REQS_WEEK_13","dataType":"double"},{"name":"WEEKLY_GROSS_REQS_WEEK_14","dataType":"double"},{"name":"WEEKLY_GROSS_REQS_WEEK_15","dataType":"double"},{"name":"WEEKLY_GROSS_REQS_WEEK_16","dataType":"double"},{"name":"WEEKLY_GROSS_REQS_WEEK_17","dataType":"double"},{"name":"WEEKLY_GROSS_REQS_WEEK_18","dataType":"double"},{"name":"WEEKLY_GROSS_REQS_WEEK_19","dataType":"double"},{"name":"WEEKLY_GROSS_REQS_WEEK_20","dataType":"double"},{"name":"WEEKLY_GROSS_REQS_WEEK_21","dataType":"double"},{"name":"WEEKLY_GROSS_REQS_WEEK_22","dataType":"double"},{"name":"WEEKLY_GROSS_REQS_WEEK_23","dataType":"double"},{"name":"WEEKLY_GROSS_REQS_WEEK_24","dataType":"double"},{"name":"WEEKLY_GROSS_REQS_WEEK_25","dataType":"double"},{"name":"WEEKLY_GROSS_REQS_WEEK_26","dataType":"double"},{"name":"TOTAL_GR_26_WEEKS","dataType":"double"},{"name":"INVENTORY_QUANTITY","dataType":"double"},{"name":"INVENTORY_VALUE","dataType":"double"},{"name":"INVENTORY_VALUE_USD","dataType":"double"},{"name":"RECEIVING_QUANTITY","dataType":"double"},{"name":"RECEIVING_VALUE","dataType":"double"},{"name":"RECEIVING_VALUE_USD","dataType":"double"},{"name":"INTRANSIT_QUANTITY","dataType":"double"},{"name":"INTRANSIT_VALUE","dataType":"double"},{"name":"INTRANSIT_VALUE_USD","dataType":"double"},{"name":"TOTAL_QUANTITY","dataType":"double"},{"name":"EXTENDED_VALUE","dataType":"double"},{"name":"EXTENDED_VALUE_USD","dataType":"double"},{"name":"TOTAL_ONHAND_QTY","dataType":"double"},{"name":"ONHAND_QTY_NON_ASSET","dataType":"double"},{"name":"ONHAND_QTY_ASSET","dataType":"double"},{"name":"TOTAL_USAGE_26_WEEKS","dataType":"double"},{"name":"SO_USAGE_13_WEEKS","dataType":"double"},{"name":"SO_USAGE_26_WEEKS","dataType":"double"},{"name":"TOTAL_USAGE_13_WEEKS","dataType":"double"},{"name":"WO_USAGE_13_WEEKS","dataType":"double"},{"name":"WO_USAGE_26_WEEKS","dataType":"double"},{"name":"SPC_USAGE_VOLUME_13_WEEKS_USD","dataType":"double"},{"name":"GROSS_INVENTORY_TURNS","dataType":"double"},{"name":"AVERAGE_DAILY_DEMAND","dataType":"double"},{"name":"AVE_DAILY_USAGE_26_WEEKS","dataType":"double"},{"name":"AVG_DAILY_DEMAND_ELSE_USAGE","dataType":"double"},{"name":"PURCHASING_LIST_PRICE","dataType":"double"},{"name":"PURCHASING_LIST_PRICE_USD","dataType":"double"},{"name":"NUMBER_OF_OPEN_BLANKETS","dataType":"double"},{"name":"SUM_REMAINING_AMOUNT","dataType":"double"},{"name":"SUM_USD_REMAINING_AMOUNT","dataType":"double"},{"name":"SUM_REMAINING_QTY_CALCULATED","dataType":"double"},{"name":"BLANKET_DAYS_SUPPLY_REMAINING","dataType":"double"},{"name":"ON_HAND_DAYS_OF_SUPPLY","dataType":"double"},{"name":"ON_ORDER_DAYS_OF_SUPPLY","dataType":"double"},{"name":"WIP_IN_PROCESS_QTY","dataType":"double"},{"name":"WIP_IN_PROCESS_VALUE","dataType":"double"},{"name":"WIP_IN_PROCESS_VALUE_USD","dataType":"double"},{"name":"WIP_DAYS_OF_SUPPLY","dataType":"double"},{"name":"TOTAL_DAYS_OF_SUPPLY","dataType":"double"},{"name":"ACTIVE_SUPPLIER_LT","dataType":"double"},{"name":"ATTRIBUTE_LT","dataType":"double"},{"name":"PURCH_ASL_LT","dataType":"double"},{"name":"SUBINVENTORY_MIN_MAX_LT","dataType":"double"},{"name":"KANBAN_REPL_LT","dataType":"double"},{"name":"KANBAN_TYPE","dataType":"string"},{"name":"MIN_MAX_PLANNED","dataType":"string"},{"name":"KANBAN_ITEM","dataType":"string"},{"name":"OPEN_BLANKETS","dataType":"string"},{"name":"MIN_MAX_ITEM","dataType":"string"},{"name":"MRP_ACTIVE_OR_INACTIVE","dataType":"string"},{"name":"TXN_ACTIVE_OR_INACTIVE","dataType":"string"},{"name":"ACTIVE_OR_INACTIVE","dataType":"string"},{"name":"PROJ_SPEND_NEXT_26_WEEKS","dataType":"double"},{"name":"PROJ_SPEND_NEXT_26_WEEKS_USD","dataType":"double"},{"name":"ENTITY","dataType":"string"},{"name":"ENTITY_ID","dataType":"double"},{"name":"FIN_PRODUCT_GROUP","dataType":"string"},{"name":"FIN_PRODUCT_FAMILY","dataType":"string"},{"name":"FIN_PRODUCT_ID","dataType":"double"},{"name":"ORA_PRODUCT_ID","dataType":"double"},{"name":"IR_PO_QTY","dataType":"double"},{"name":"IR_PO_VALUE","dataType":"double"},{"name":"IR_PO_VALUE_USD","dataType":"double"},{"name":"ONORDER_PO_QTY","dataType":"double"},{"name":"ONORDER_PO_VALUE","dataType":"double"},{"name":"ONORDER_PO_VALUE_USD","dataType":"double"},{"name":"ITEM_TBU","dataType":"string"},{"name":"ITEM_PRODUCT_FAMILY","dataType":"string"},{"name":"ORA_PRODUCT_FAMILY","dataType":"string"},{"name":"ORA_PRODUCT_GROUP","dataType":"string"},{"name":"TARGET_DAYS_OF_SUPPLY","dataType":"double"},{"name":"TARGET_DAYS_OF_SUPPLY_QTY","dataType":"double"},{"name":"TARGET_DAYS_OF_SUPPLY_VALUE","dataType":"double"},{"name":"TARGET_DAYS_OF_SUPPLY_SAVINGS","dataType":"double"},{"name":"LT_GROUPING","dataType":"string"},{"name":"PRODUCT_LINE_OBI","dataType":"string"},{"name":"ITEM_STATUS_OBI","dataType":"string"},{"name":"INVASCP_KEY","dataType":"string"},{"name":"ITEM_TYPE_OBI","dataType":"string"},{"name":"LT_GROUPING_ID","dataType":"double"},{"name":"FIXED_DAYS_SUPPLY_DAYS","dataType":"double"},{"name":"MIN_ORDER_SUPPLY_DAYS","dataType":"double"},{"name":"FIXED_ORDER_SUPPLY_DAYS","dataType":"double"},{"name":"FIXED_LOT_MULTP_SUP_DAYS","dataType":"double"},{"name":"HIGH_ORDER_MODIFR_SUP_DAYS","dataType":"double"},{"name":"DAYS_0_20","dataType":"double"},{"name":"DAYS_20_40","dataType":"double"},{"name":"DAYS_40_PLUS","dataType":"double"},{"name":"USAGE_WEEK_1","dataType":"double"},{"name":"USAGE_WEEK_2","dataType":"double"},{"name":"USAGE_WEEK_3","dataType":"double"},{"name":"USAGE_WEEK_4","dataType":"double"},{"name":"USAGE_WEEK_5","dataType":"double"},{"name":"USAGE_WEEK_6","dataType":"double"},{"name":"USAGE_WEEK_7","dataType":"double"},{"name":"USAGE_WEEK_8","dataType":"double"},{"name":"USAGE_WEEK_9","dataType":"double"},{"name":"USAGE_WEEK_10","dataType":"double"},{"name":"USAGE_WEEK_11","dataType":"double"},{"name":"USAGE_WEEK_12","dataType":"double"},{"name":"USAGE_WEEK_13","dataType":"double"},{"name":"USAGE_WEEK_14","dataType":"double"},{"name":"USAGE_WEEK_15","dataType":"double"},{"name":"USAGE_WEEK_16","dataType":"double"},{"name":"USAGE_WEEK_17","dataType":"double"},{"name":"USAGE_WEEK_18","dataType":"double"},{"name":"USAGE_WEEK_19","dataType":"double"},{"name":"USAGE_WEEK_20","dataType":"double"},{"name":"USAGE_WEEK_21","dataType":"double"},{"name":"USAGE_WEEK_22","dataType":"double"},{"name":"USAGE_WEEK_23","dataType":"double"},{"name":"USAGE_WEEK_24","dataType":"double"},{"name":"USAGE_WEEK_25","dataType":"double"},{"name":"USAGE_WEEK_26","dataType":"double"},{"name":"STD_DEV_USAGE_26_WEEKS","dataType":"double"},{"name":"COEFF_USAGE_26_WEEKS","dataType":"double"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2021-09-07T18:08:21.5075237+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/f7bcec60-fe9e-49e3-b2ba-3c922cc1da6e/Fields_Reduced_INVVELO_TRIAL.csv?snapshot=2021-09-07T18%3A08%3A21.4168684Z"}]}]}