{"name":"IM CATEGORY MASTER ORG","description":"","version":"1.0","culture":"en-US","modifiedTime":"2021-07-09T18:41:03.9223943+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"XXREP_IM_CATEGORY_V":{"queryId":"d9c0253c-630b-4308-8e8c-1022b05553b9","queryName":"XXREP_IM_CATEGORY_V","loadEnabled":true}},"document":"section Section1;\r\nshared XXREP_IM_CATEGORY_V = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 1\" = Navigation{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXREP_IM_CATEGORY_V\", Kind = \"View\"]}[Data],\r\n  #\"Filtered rows\" = Table.SelectRows(#\"Navigation 2\", each ([ORGANIZATION_ID] = 63))\r\nin\r\n  #\"Filtered rows\";\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"XXREP_IM_CATEGORY_V","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"XXREP_IM_CATEGORY_V.csv"},"attributes":[{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"ORGANIZATION_ID","dataType":"double"},{"name":"ITEM_NUMBER","dataType":"string"},{"name":"DESCRIPTION","dataType":"string"},{"name":"ORGANIZATION_CODE","dataType":"string"},{"name":"ROW_UPDATED_BY","dataType":"string"},{"name":"ITEM_CREATION_DATE","dataType":"dateTime"},{"name":"ROW_CREATION_DATE","dataType":"dateTime"},{"name":"PF_ITEM_NUMBER","dataType":"string"},{"name":"ECCN_ECCN","dataType":"string"},{"name":"COO_COUNTRY_OF_ORIGIN","dataType":"string"},{"name":"HTS_HTS_SCHEDULE_B","dataType":"string"},{"name":"PLNG_GREEN_SUPPLY_STATUS","dataType":"string"},{"name":"PLNG_PLANNING_ACTION","dataType":"string"},{"name":"PLNG_FAMILY_UNIQUE","dataType":"string"},{"name":"ST_SALES_TAX_CATEGORY","dataType":"string"},{"name":"CDI_CARTON_GROUP","dataType":"string"},{"name":"CI_CARTON_GROUP","dataType":"string"},{"name":"PROD_TBU","dataType":"string"},{"name":"PROD_FAMILY","dataType":"string"},{"name":"PROD_LINE","dataType":"string"},{"name":"PROD_FORECAST_FIELD","dataType":"string"},{"name":"CON_CONTRACT_CATEGORY","dataType":"string"},{"name":"PTLX_PATLEX_PERCENT","dataType":"string"},{"name":"COMM_COMMODITY","dataType":"string"},{"name":"SLT_SERVICE_LEAD_TIME","dataType":"string"},{"name":"FF_FORECAST_FIELD","dataType":"string"},{"name":"CS_SUPPLY_SOURCE","dataType":"string"},{"name":"CS_DEMAND_SOURCE","dataType":"string"},{"name":"DBT_DB_TEMP","dataType":"string"},{"name":"BUP_BACKUP","dataType":"string"},{"name":"PO_PRIMARY_ORG","dataType":"string"},{"name":"PO_SUPPLY_CHAIN_PORG","dataType":"string"},{"name":"BCP_BCP","dataType":"string"},{"name":"CUST_CUSTOMER","dataType":"string"},{"name":"ROYLT_ROYALTY","dataType":"string"},{"name":"SC_SECURITY_CLASS","dataType":"string"},{"name":"GTD_GREEN_TRANSITION_DATE","dataType":"string"},{"name":"ROH_EU_ROHS_COMPLIANT","dataType":"string"},{"name":"ROH_CHINA_ROHS_COMPLIANT","dataType":"string"},{"name":"FDA_FDA_ACCESSION","dataType":"string"},{"name":"SCC_SEQUENCE","dataType":"string"},{"name":"SCC_COMMODITY","dataType":"string"},{"name":"SCC_UNSPSC","dataType":"string"},{"name":"OPROD_TBU","dataType":"string"},{"name":"OPROD_FAMILY","dataType":"string"},{"name":"OPROD_LINE","dataType":"string"},{"name":"OPROD_FORECAST_FIELD","dataType":"string"},{"name":"SR_OPERATING_UNIT","dataType":"string"},{"name":"SR_PERCENTAGE","dataType":"string"},{"name":"SR_VENDOR","dataType":"string"},{"name":"SR_VENDOR_SITE","dataType":"string"},{"name":"SI_INSTALL_WITH_SALE","dataType":"string"},{"name":"IT_ITEM_TYPE_CODE","dataType":"string"},{"name":"IT_ITEM_TYPE_MEANING","dataType":"string"},{"name":"OPSR_SEC_REPORTING","dataType":"string"},{"name":"OPSR_DEMAND_SOURCE","dataType":"string"},{"name":"SECR_SEC_REPORTING","dataType":"string"},{"name":"OPC_ORG","dataType":"string"},{"name":"OPC_PLANNING_CODE","dataType":"string"},{"name":"SP_SHIPMENT_PRIORITY","dataType":"string"},{"name":"FI_FISCAL_YEAR","dataType":"string"},{"name":"FI_SFDC_FORECAST_ITEM","dataType":"string"},{"name":"PG_ORG","dataType":"string"},{"name":"PG_PLANNING_GROUP","dataType":"string"},{"name":"WC_ORG","dataType":"string"},{"name":"WC_WORK_CELL","dataType":"string"},{"name":"RM_REPLENISHMENT_METHOD","dataType":"string"},{"name":"SFLT_SUPPLIER_FULL_LEAD_TIME","dataType":"string"},{"name":"SCS_SUPPLY_CHAIN_STATUS","dataType":"string"},{"name":"BPAS_BPA_STATUS","dataType":"string"},{"name":"MCOO_MULTI_COUNTRY_OF_ORIGIN","dataType":"string"},{"name":"DSO_DEFAULT_SHIPPING_ORG","dataType":"string"},{"name":"SFDCT_SFDC_TRANSFER","dataType":"string"},{"name":"IKC_ORG","dataType":"string"},{"name":"IKC_ORG_GROUP","dataType":"string"},{"name":"IKC_USERID","dataType":"string"},{"name":"EUHTS_HTS_CODE_EU","dataType":"string"},{"name":"CRI_ACCOUNT_NUMBER","dataType":"string"},{"name":"XYZ_XYZ_CLASS","dataType":"string"},{"name":"SCSD_SUPPLY_CHAIN_STATUS_DAYS","dataType":"string"},{"name":"MMKS_SOURCE","dataType":"string"},{"name":"MMKS_AUTO_UPDATE","dataType":"string"},{"name":"DO_DESIGN_ORG","dataType":"string"},{"name":"ITEM_CREATION_REF_DATE","dataType":"dateTime"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2021-07-09T18:43:32.7445768+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/fa08651e-d9d1-4c77-96f2-8418ac146682/XXREP_IM_CATEGORY_V.csv?snapshot=2021-07-09T18%3A42%3A56.8865136Z"}]}]}