{"name":"INV_VALUE","description":"","version":"1.0","culture":"en-US","modifiedTime":"2021-11-26T17:18:17.4719903+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"Data Update Info":{"queryId":"f25c9a2b-85f3-4ce9-90bf-725c7ba70079","queryName":"Data Update Info","loadEnabled":true},"Time Balance Week":{"queryId":"9f3b3a19-12d9-4b9a-8330-3a600c38175a","queryName":"Time Balance Week","loadEnabled":true},"Inventory Value Detail":{"queryId":"85885ba6-bd00-41c4-b460-a6e19cbb18f4","queryName":"Inventory Value Detail","loadEnabled":true},"Inventory Value Summary":{"queryId":"6e4d6501-1d6d-4c5f-8867-8fb787a82af2","queryName":"Inventory Value Summary","loadEnabled":true}},"document":"section Section1;\r\nshared #\"Data Update Info\" = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 1\" = Navigation{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXREP_DATA_UPDATE_V\", Kind = \"View\"]}[Data],\r\n  #\"Filtered rows\" = Table.SelectRows(#\"Navigation 2\", each [TABLE_NAME] = \"XXFACTS.XX_INVVALUE_FACT\")\r\nin\r\n  #\"Filtered rows\";\r\nshared #\"Time Balance Week\" = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 1\" = Navigation{[Name = \"XXDIMS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XX_INVVALUE_WEEK_TIMBAL_V\", Kind = \"View\"]}[Data]\r\nin\r\n  #\"Navigation 2\";\r\nshared #\"Inventory Value Detail\" = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 1\" = Navigation{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXREP_INVVALUE_V\", Kind = \"View\"]}[Data]\r\nin\r\n  #\"Navigation 2\";\r\nshared #\"Inventory Value Summary\" = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 1\" = Navigation{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXREP_INVVALUE_SUM_V\", Kind = \"View\"]}[Data]\r\nin\r\n  #\"Navigation 2\";\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"Data Update Info","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Data%20Update%20Info.csv"},"attributes":[{"name":"TABLE_NAME","dataType":"string"},{"name":"DATA_UPDATE_DATE","dataType":"dateTime"},{"name":"DATA_UPDATE_DESC","dataType":"string"},{"name":"DATA_FLOW_REFRESH_DATE","dataType":"dateTime"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T01:01:08.9703487+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/d2b6a20c-f940-4d35-9cc1-ba28c1d5c1ab/Data%20Update%20Info.csv?snapshot=2022-06-13T01%3A01%3A08.1049456Z"}]},{"$type":"LocalEntity","name":"Time Balance Week","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Time%20Balance%20Week.csv"},"attributes":[{"name":"FISCAL_PERIOD_KEY","dataType":"string"},{"name":"FISCAL_DIM_ID","dataType":"double"},{"name":"FISCAL_DIM","dataType":"string"},{"name":"FISCAL_DIM_VALUE","dataType":"string"},{"name":"FISCAL_DIM_SORT_VALUE","dataType":"string"},{"name":"FC_YEAR_OFFSET","dataType":"double"},{"name":"FC_QUARTER_OFFSET","dataType":"double"},{"name":"FISCAL_YEAR","dataType":"string"},{"name":"FYFQ","dataType":"string"},{"name":"PERIOD_YEAR","dataType":"double"},{"name":"GL_PERIOD","dataType":"string"},{"name":"FISCAL_WEEK_ID","dataType":"double"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T01:01:13.7292159+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/d2b6a20c-f940-4d35-9cc1-ba28c1d5c1ab/Time%20Balance%20Week.csv?snapshot=2022-06-13T01%3A01%3A13.5108122Z"}]},{"$type":"LocalEntity","name":"Inventory Value Detail","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Inventory%20Value%20Detail.csv"},"attributes":[{"name":"INV_ORG_ID","dataType":"double"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"ITEM_ORG_ID_KEY","dataType":"string"},{"name":"ITEM_ORG_CODE_KEY","dataType":"string"},{"name":"OPERATING_UNIT_ID","dataType":"double"},{"name":"ITEM_NUMBER","dataType":"string"},{"name":"ITEM_TBU","dataType":"string"},{"name":"ITEM_PRODUCT_FAMILY","dataType":"string"},{"name":"SOURCE_TYPE","dataType":"string"},{"name":"SUBINVENTORY_CODE","dataType":"string"},{"name":"SUBINVENTORY_TYPE","dataType":"string"},{"name":"ORGANIZATION_CODE","dataType":"string"},{"name":"ENTITY","dataType":"string"},{"name":"ACCOUNT","dataType":"string"},{"name":"FIN_ENTITY","dataType":"string"},{"name":"INV_QUANTITY","dataType":"double"},{"name":"INV_BALANCE","dataType":"double"},{"name":"INV_VALUE","dataType":"double"},{"name":"INV_VALUE_USD","dataType":"double"},{"name":"CURRENCY_CODE","dataType":"string"},{"name":"CURRENCY_RATE","dataType":"double"},{"name":"ITEM_COST","dataType":"double"},{"name":"MATERIAL_COST","dataType":"double"},{"name":"MATERIAL_OVERHEAD_COST","dataType":"double"},{"name":"OUTSIDE_PROCESSING_COST","dataType":"double"},{"name":"OVERHEAD_COST","dataType":"double"},{"name":"RESOURCE_COST","dataType":"double"},{"name":"TOTAL_COST","dataType":"double"},{"name":"FISCAL_YEAR_ID","dataType":"double"},{"name":"VALID_FLAG","dataType":"string"},{"name":"COMMENTS","dataType":"string"},{"name":"CREATION_DATE","dataType":"dateTime"},{"name":"CREATED_BY","dataType":"double"},{"name":"FISCAL_WEEK_ID","dataType":"double"},{"name":"FISCAL_WEEK","dataType":"string"},{"name":"JE_SOURCE_CATEGORY","dataType":"string"},{"name":"OPERATIONS_REPORTING","dataType":"string"},{"name":"CS_DEMAND_SOURCE","dataType":"string"},{"name":"CS_SUPPLY_SOURCE","dataType":"string"},{"name":"ITEM_TYPE_CODE","dataType":"string"},{"name":"EXCLUDE_FLAG","dataType":"string"},{"name":"EXCLUDE_COMMENT","dataType":"string"},{"name":"WIP_CLASS","dataType":"string"},{"name":"WIP_CLASS_CODE","dataType":"string"},{"name":"ITEM_TYPE","dataType":"string"},{"name":"PLANNER_CODE","dataType":"string"},{"name":"MAKE_BUY","dataType":"string"},{"name":"ITEM_STATUS","dataType":"string"},{"name":"ABC_CLASS","dataType":"string"},{"name":"INV_STATUS","dataType":"string"},{"name":"WIP_JOB_ID","dataType":"double"},{"name":"ITEM_PRODUCT_LINE","dataType":"string"},{"name":"ITEM_FORECAST_FIELD","dataType":"string"},{"name":"ITEM_DESC","dataType":"string"},{"name":"WIP_JOB_NO","dataType":"string"},{"name":"ITEM_COST_USD","dataType":"double"},{"name":"ORA_PRODUCT_LINE","dataType":"string"},{"name":"CONC_REQ_ID","dataType":"double"},{"name":"FIN_PRODUCT_LINE","dataType":"string"},{"name":"ORA_FORECAST_FIELD","dataType":"string"},{"name":"ORG_TBU","dataType":"string"},{"name":"ORG_PRODUCT_FAMILY","dataType":"string"},{"name":"ORG_PRODUCT_LINE","dataType":"string"},{"name":"ORG_FORECAST_FIELD","dataType":"string"},{"name":"ORG_CATEGORY_ID","dataType":"double"},{"name":"PRODUCT_MAP_KEY","dataType":"string"},{"name":"FIN_TBU","dataType":"string"},{"name":"FIN_PFC","dataType":"string"},{"name":"WEEK_START_DATE","dataType":"dateTime"},{"name":"WEEK_END_DATE","dataType":"dateTime"},{"name":"PERIOD_START_DATE","dataType":"dateTime"},{"name":"PERIOD_END_DATE","dataType":"dateTime"},{"name":"QUARTER_START_DATE","dataType":"dateTime"},{"name":"QUARTER_END_DATE","dataType":"dateTime"},{"name":"FISCAL_QUARTER","dataType":"string"},{"name":"FISCAL_YEAR","dataType":"string"},{"name":"MGT_PRODUCT_GROUP","dataType":"string"},{"name":"MGT_SUB_PRODUCT_GROUP","dataType":"string"},{"name":"BUSINESS_SEGMENT","dataType":"string"},{"name":"ACCOUNT_NAME","dataType":"string"},{"name":"ACCOUNT_DESC","dataType":"string"},{"name":"ACCOUNT_TYPE","dataType":"string"},{"name":"ACCOUNT_SUB_GROUP","dataType":"string"},{"name":"ACCOUNT_GROUP","dataType":"string"},{"name":"SUMMARY_ACCOUNT","dataType":"string"},{"name":"INVVALUE_KEY","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T01:44:42.5464255+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/d2b6a20c-f940-4d35-9cc1-ba28c1d5c1ab/Inventory%20Value%20Detail.csv?snapshot=2022-06-13T01%3A38%3A33.6960462Z"}]},{"$type":"LocalEntity","name":"Inventory Value Summary","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Inventory%20Value%20Summary.csv"},"attributes":[{"name":"INV_ORG_ID","dataType":"double"},{"name":"OPERATING_UNIT_ID","dataType":"double"},{"name":"ITEM_TBU","dataType":"string"},{"name":"ITEM_PRODUCT_FAMILY","dataType":"string"},{"name":"ITEM_PRODUCT_LINE","dataType":"string"},{"name":"ITEM_FORECAST_FIELD","dataType":"string"},{"name":"SOURCE_TYPE","dataType":"string"},{"name":"SUBINVENTORY_CODE","dataType":"string"},{"name":"SUBINVENTORY_TYPE","dataType":"string"},{"name":"ORGANIZATION_CODE","dataType":"string"},{"name":"ENTITY","dataType":"string"},{"name":"ACCOUNT","dataType":"string"},{"name":"FIN_ENTITY","dataType":"string"},{"name":"FIN_TBU","dataType":"string"},{"name":"FIN_PFC","dataType":"string"},{"name":"CURRENCY_CODE","dataType":"string"},{"name":"FISCAL_YEAR_ID","dataType":"double"},{"name":"FISCAL_WEEK","dataType":"string"},{"name":"FISCAL_WEEK_ID","dataType":"double"},{"name":"GL_PERIOD","dataType":"string"},{"name":"JE_SOURCE_CATEGORY","dataType":"string"},{"name":"OPERATIONS_REPORTING","dataType":"string"},{"name":"CS_DEMAND_SOURCE","dataType":"string"},{"name":"CS_SUPPLY_SOURCE","dataType":"string"},{"name":"ITEM_TYPE_CODE","dataType":"string"},{"name":"WIP_CLASS","dataType":"string"},{"name":"WIP_CLASS_CODE","dataType":"string"},{"name":"ITEM_TYPE","dataType":"string"},{"name":"PLANNER_CODE","dataType":"string"},{"name":"MAKE_BUY","dataType":"string"},{"name":"ITEM_STATUS","dataType":"string"},{"name":"ABC_CLASS","dataType":"string"},{"name":"INV_STATUS","dataType":"string"},{"name":"PRODUCT_MAP_KEY","dataType":"string"},{"name":"QUARTER_START_DATE","dataType":"dateTime"},{"name":"QUARTER_END_DATE","dataType":"dateTime"},{"name":"FISCAL_QUARTER","dataType":"string"},{"name":"FISCAL_YEAR","dataType":"string"},{"name":"MGT_PRODUCT_GROUP","dataType":"string"},{"name":"MGT_SUB_PRODUCT_GROUP","dataType":"string"},{"name":"BUSINESS_SEGMENT","dataType":"string"},{"name":"ACCOUNT_NAME","dataType":"string"},{"name":"ACCOUNT_DESC","dataType":"string"},{"name":"ACCOUNT_TYPE","dataType":"string"},{"name":"ACCOUNT_SUB_GROUP","dataType":"string"},{"name":"ACCOUNT_GROUP","dataType":"string"},{"name":"SUMMARY_ACCOUNT","dataType":"string"},{"name":"INV_QUANTITY","dataType":"double"},{"name":"INV_BALANCE","dataType":"double"},{"name":"INV_VALUE","dataType":"double"},{"name":"INV_VALUE_USD","dataType":"double"},{"name":"INVVALUE_KEY","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T01:12:56.3382025+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/d2b6a20c-f940-4d35-9cc1-ba28c1d5c1ab/Inventory%20Value%20Summary.csv?snapshot=2022-06-13T01%3A11%3A42.8319394Z"}]}]}