{"name":"WIP_RESOURCE_TRANS","description":"Oracle Work Orders resource transactions","version":"1.0","culture":"en-US","modifiedTime":"2021-11-27T06:09:43.0325358+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"Data Update Info":{"queryId":"339cfb73-b545-458b-a043-5cd216626b95","queryName":"Data Update Info","loadEnabled":true},"XXREP_RESOURCE_TRAN_V":{"queryId":"ba37edc7-9838-4df3-bff6-00790440e4ad","queryName":"XXREP_RESOURCE_TRAN_V","loadEnabled":true},"RangeEnd":{"queryId":"fd16c1f3-4376-4963-b147-9532ab359a58","queryName":"RangeEnd"},"RangeStart":{"queryId":"82aa1228-3a69-45dd-889c-03c09e3ac26b","queryName":"RangeStart"}},"document":"section Section1;\r\n\r\nshared #\"Data Update Info\" = let\r\n    Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n    Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n    #\"Navigation 1\" = Navigation{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n    #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXREP_DATA_UPDATE_V\", Kind = \"View\"]}[Data],\r\n    #\"Filtered rows\" = Table.SelectRows(#\"Navigation 2\", each [TABLE_NAME] = \"WIP.WIP_TRANSACTIONS\")\r\nin\r\n    #\"Filtered rows\";\r\n\r\nshared XXREP_RESOURCE_TRAN_V = let\r\n    Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n    #\"Navigation 1\" = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n    #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n    #\"Navigation 3\" = #\"Navigation 2\"{[Name = \"XXREP_RESOURCE_TRAN_V\", Kind = \"View\"]}[Data],\r\n    #\"XXREP_RESOURCE_TRAN_V-504552494F445F53544152545F44415445-autogenerated_for_incremental_refresh\" = Table.SelectRows(#\"Navigation 3\", each DateTime.From([PERIOD_START_DATE]) >= RangeStart and DateTime.From([PERIOD_START_DATE]) < RangeEnd)\r\nin\r\n    #\"XXREP_RESOURCE_TRAN_V-504552494F445F53544152545F44415445-autogenerated_for_incremental_refresh\";\r\n\r\nshared RangeStart = let RangeStart = #datetime(0001,01,01,00,00,00) meta [IsParameterQuery=true, List={}, Type=\"DateTime\", IsParameterQueryRequired=true, Description=\"autogenerated_for_incremental_refresh\"] in RangeStart;\r\n\r\nshared RangeEnd = let RangeEnd = #datetime(9999,12,31,23,59,59) meta [IsParameterQuery=true, List={}, Type=\"DateTime\", IsParameterQueryRequired=true, Description=\"autogenerated_for_incremental_refresh\"] in RangeEnd;\r\n\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"Data Update Info","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Data%20Update%20Info.csv"},"attributes":[{"name":"TABLE_NAME","dataType":"string"},{"name":"DATA_UPDATE_DATE","dataType":"dateTime"},{"name":"DATA_UPDATE_DESC","dataType":"string"},{"name":"DATA_FLOW_REFRESH_DATE","dataType":"dateTime"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-19T13:30:27.2206795+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/4cb07f8d-486f-4940-ab6f-d153e2724b0a/Data%20Update%20Info.csv?snapshot=2022-05-19T13%3A30%3A26.8580262Z"}]},{"$type":"LocalEntity","name":"XXREP_RESOURCE_TRAN_V","description":"","pbi:refreshPolicy":{"$type":"IncrementalRefreshPolicy","locationPattern":"XXREP_RESOURCE_TRAN_V/part.csv","rollingWindowGranularity":"quarter","rollingWindowPeriods":24,"incrementalGranularity":"quarter","incrementalPeriods":24},"annotations":[{"name":"pbi:IncrementalRefreshDetectChangeAttribute"},{"name":"pbi:IncrementalRefreshFilterByAttribute","value":"PERIOD_START_DATE"}],"attributes":[{"name":"JOB_NUMBER","dataType":"string"},{"name":"WIP_JOB_DESCRIPTION","dataType":"string"},{"name":"WIPJOB_ORG_KEY_CODE","dataType":"string"},{"name":"WIPJOB_ORG_KEY_ID","dataType":"string"},{"name":"DISCRETE_JOB_FLAG","dataType":"string"},{"name":"JOB_TYPE","dataType":"string"},{"name":"RESOURCE_TRX_REFERENCE","dataType":"string"},{"name":"TRANSACTION_ID","dataType":"double"},{"name":"TRANSACTION_TYPE","dataType":"string"},{"name":"TRANSACTION_DATE","dataType":"dateTime"},{"name":"SOURCE_CODE","dataType":"string"},{"name":"OPERATION_SEQ_NUM","dataType":"double"},{"name":"RESOURCE_SEQ_NUM","dataType":"double"},{"name":"AUTOCHARGE_TYPE","dataType":"string"},{"name":"USAGE_RATE_OR_AMOUNT","dataType":"double"},{"name":"BASIS_TYPE","dataType":"string"},{"name":"TRANSACTION_QUANTITY","dataType":"double"},{"name":"TRANSACTION_UOM","dataType":"string"},{"name":"PRIMARY_QUANTITY","dataType":"double"},{"name":"PRIMARY_UOM","dataType":"string"},{"name":"ACTUAL_RESOURCE_RATE","dataType":"double"},{"name":"STANDARD_RESOURCE_RATE","dataType":"double"},{"name":"STANDARD_RATE_FLAG","dataType":"string"},{"name":"CURRENCY_CODE","dataType":"string"},{"name":"MOVE_PRIMARY_QUANTITY","dataType":"double"},{"name":"FM_OPERATION_SEQ_NUM","dataType":"double"},{"name":"TO_OPERATION_SEQ_NUM","dataType":"double"},{"name":"ACTIVITY","dataType":"string"},{"name":"ATTRIBUTE_CATEGORY","dataType":"string"},{"name":"ATTRIBUTE1","dataType":"string"},{"name":"ATTRIBUTE2","dataType":"string"},{"name":"ORGANIZATION_ID","dataType":"double"},{"name":"WIP_ENTITY_ID","dataType":"double"},{"name":"LINE_ID","dataType":"double"},{"name":"PRIMARY_ITEM_ID","dataType":"double"},{"name":"DEPARTMENT_ID","dataType":"double"},{"name":"RESOURCE_ID","dataType":"double"},{"name":"EMPLOYEE_ID","dataType":"double"},{"name":"ACTIVITY_ID","dataType":"double"},{"name":"REASON_ID","dataType":"double"},{"name":"MOVE_TRANSACTION_ID","dataType":"double"},{"name":"COMPLETION_TRANSACTION_ID","dataType":"double"},{"name":"PROJECT_ID","dataType":"double"},{"name":"TASK_ID","dataType":"double"},{"name":"SOURCE_LINE_ID","dataType":"double"},{"name":"CREATION_DATE","dataType":"dateTime"},{"name":"CREATED_BY","dataType":"double"},{"name":"LAST_UPDATE_DATE","dataType":"dateTime"},{"name":"LAST_UPDATED_BY","dataType":"double"},{"name":"PROJECT_NAME","dataType":"string"},{"name":"PROJECT_NUMBER","dataType":"string"},{"name":"DEPARTMENT_CODE","dataType":"string"},{"name":"RESOURCE_CODE","dataType":"string"},{"name":"COST_CODE_TYPE","dataType":"double"},{"name":"ALLOW_COSTS","dataType":"string"},{"name":"ALLOW_COSTS_FLAG","dataType":"double"},{"name":"COST_CODE_TYPE_NAME","dataType":"string"},{"name":"ITEM_NUMBER","dataType":"string"},{"name":"ITEM_DESCRIPTION","dataType":"string"},{"name":"ITEM_ORG_KEY_ID","dataType":"string"},{"name":"ITEM_ORG_KEY_CODE","dataType":"string"},{"name":"ACCT_PERIOD_ID","dataType":"double"},{"name":"PERIOD_NAME","dataType":"string"},{"name":"PERIOD_START_DATE","dataType":"dateTime"},{"name":"PERIOD_CLOSE_DATE","dataType":"dateTime"},{"name":"INVORG_CODE","dataType":"string"},{"name":"INVORG_ID","dataType":"double"},{"name":"LOCAL_EXTRACT_DATE","dataType":"dateTime"},{"name":"EXTRACT_DATE","dataType":"dateTime"},{"name":"TIMEZONE","dataType":"string"},{"name":"CREATED_BY_LOGIN","dataType":"string"},{"name":"LAST_UPDATED_BY_LOGIN","dataType":"string"}],"partitions":[{"name":"IncrementalRefreshPolicyPartition-2016Q2","refreshTime":"2022-04-09T05:44:04.0753914+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/4cb07f8d-486f-4940-ab6f-d153e2724b0a/XXREP_RESOURCE_TRAN_V/part-2016Q2.csv?snapshot=2022-04-09T05%3A43%3A46.7003233Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2016-04-01T00:00:00","end":"2016-07-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2016Q3","refreshTime":"2022-05-19T13:38:44.5903232+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/4cb07f8d-486f-4940-ab6f-d153e2724b0a/XXREP_RESOURCE_TRAN_V/part-2016Q3.csv?snapshot=2022-05-19T13%3A38%3A29.5173293Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2016-07-01T00:00:00","end":"2016-10-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2016Q4","refreshTime":"2022-05-19T13:40:07.021652+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/4cb07f8d-486f-4940-ab6f-d153e2724b0a/XXREP_RESOURCE_TRAN_V/part-2016Q4.csv?snapshot=2022-05-19T13%3A39%3A51.6195544Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2016-10-01T00:00:00","end":"2017-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2017Q1","refreshTime":"2022-05-19T13:41:24.2920329+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/4cb07f8d-486f-4940-ab6f-d153e2724b0a/XXREP_RESOURCE_TRAN_V/part-2017Q1.csv?snapshot=2022-05-19T13%3A41%3A07.5551609Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2017-01-01T00:00:00","end":"2017-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2017Q2","refreshTime":"2022-05-19T13:40:47.4355668+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/4cb07f8d-486f-4940-ab6f-d153e2724b0a/XXREP_RESOURCE_TRAN_V/part-2017Q2.csv?snapshot=2022-05-19T13%3A40%3A28.8618226Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2017-04-01T00:00:00","end":"2017-07-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2017Q3","refreshTime":"2022-05-19T13:41:52.6760831+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/4cb07f8d-486f-4940-ab6f-d153e2724b0a/XXREP_RESOURCE_TRAN_V/part-2017Q3.csv?snapshot=2022-05-19T13%3A41%3A34.5456208Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2017-07-01T00:00:00","end":"2017-10-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2017Q4","refreshTime":"2022-05-19T13:42:20.6731167+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/4cb07f8d-486f-4940-ab6f-d153e2724b0a/XXREP_RESOURCE_TRAN_V/part-2017Q4.csv?snapshot=2022-05-19T13%3A41%3A55.2859213Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2017-10-01T00:00:00","end":"2018-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2018Q1","refreshTime":"2022-05-19T13:38:40.0938424+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/4cb07f8d-486f-4940-ab6f-d153e2724b0a/XXREP_RESOURCE_TRAN_V/part-2018Q1.csv?snapshot=2022-05-19T13%3A38%3A21.5921363Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2018-01-01T00:00:00","end":"2018-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2018Q2","refreshTime":"2022-05-19T13:43:08.2408864+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/4cb07f8d-486f-4940-ab6f-d153e2724b0a/XXREP_RESOURCE_TRAN_V/part-2018Q2.csv?snapshot=2022-05-19T13%3A42%3A45.0015283Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2018-04-01T00:00:00","end":"2018-07-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2018Q3","refreshTime":"2022-05-19T13:43:47.0303881+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/4cb07f8d-486f-4940-ab6f-d153e2724b0a/XXREP_RESOURCE_TRAN_V/part-2018Q3.csv?snapshot=2022-05-19T13%3A43%3A20.8326597Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2018-07-01T00:00:00","end":"2018-10-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2018Q4","refreshTime":"2022-05-19T13:44:08.8001457+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/4cb07f8d-486f-4940-ab6f-d153e2724b0a/XXREP_RESOURCE_TRAN_V/part-2018Q4.csv?snapshot=2022-05-19T13%3A43%3A46.3780827Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2018-10-01T00:00:00","end":"2019-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2019Q1","refreshTime":"2022-05-19T13:43:33.8819377+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/4cb07f8d-486f-4940-ab6f-d153e2724b0a/XXREP_RESOURCE_TRAN_V/part-2019Q1.csv?snapshot=2022-05-19T13%3A43%3A09.9163187Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2019-01-01T00:00:00","end":"2019-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2019Q2","refreshTime":"2022-05-19T13:44:53.5499504+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/4cb07f8d-486f-4940-ab6f-d153e2724b0a/XXREP_RESOURCE_TRAN_V/part-2019Q2.csv?snapshot=2022-05-19T13%3A44%3A16.0410114Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2019-04-01T00:00:00","end":"2019-07-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2019Q3","refreshTime":"2022-05-19T13:45:37.7129727+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/4cb07f8d-486f-4940-ab6f-d153e2724b0a/XXREP_RESOURCE_TRAN_V/part-2019Q3.csv?snapshot=2022-05-19T13%3A45%3A02.6286558Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2019-07-01T00:00:00","end":"2019-10-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2019Q4","refreshTime":"2022-05-19T13:47:02.2599036+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/4cb07f8d-486f-4940-ab6f-d153e2724b0a/XXREP_RESOURCE_TRAN_V/part-2019Q4.csv?snapshot=2022-05-19T13%3A46%3A27.9168168Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2019-10-01T00:00:00","end":"2020-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2020Q1","refreshTime":"2022-05-19T13:43:02.1232244+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/4cb07f8d-486f-4940-ab6f-d153e2724b0a/XXREP_RESOURCE_TRAN_V/part-2020Q1.csv?snapshot=2022-05-19T13%3A42%3A29.6978778Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2020-01-01T00:00:00","end":"2020-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2020Q2","refreshTime":"2022-05-19T13:45:50.8798652+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/4cb07f8d-486f-4940-ab6f-d153e2724b0a/XXREP_RESOURCE_TRAN_V/part-2020Q2.csv?snapshot=2022-05-19T13%3A44%3A45.6889618Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2020-04-01T00:00:00","end":"2020-07-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2020Q3","refreshTime":"2022-05-19T13:45:56.4434034+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/4cb07f8d-486f-4940-ab6f-d153e2724b0a/XXREP_RESOURCE_TRAN_V/part-2020Q3.csv?snapshot=2022-05-19T13%3A45%3A16.2493710Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2020-07-01T00:00:00","end":"2020-10-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2020Q4","refreshTime":"2022-05-19T13:45:27.9484467+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/4cb07f8d-486f-4940-ab6f-d153e2724b0a/XXREP_RESOURCE_TRAN_V/part-2020Q4.csv?snapshot=2022-05-19T13%3A44%3A52.4938209Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2020-10-01T00:00:00","end":"2021-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2021Q1","refreshTime":"2022-05-19T13:45:50.5361033+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/4cb07f8d-486f-4940-ab6f-d153e2724b0a/XXREP_RESOURCE_TRAN_V/part-2021Q1.csv?snapshot=2022-05-19T13%3A45%3A07.4197412Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2021-01-01T00:00:00","end":"2021-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2021Q2","refreshTime":"2022-05-19T13:45:53.0214966+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/4cb07f8d-486f-4940-ab6f-d153e2724b0a/XXREP_RESOURCE_TRAN_V/part-2021Q2.csv?snapshot=2022-05-19T13%3A45%3A06.2604462Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2021-04-01T00:00:00","end":"2021-07-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2021Q3","refreshTime":"2022-05-19T13:46:30.0978135+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/4cb07f8d-486f-4940-ab6f-d153e2724b0a/XXREP_RESOURCE_TRAN_V/part-2021Q3.csv?snapshot=2022-05-19T13%3A45%3A56.3330044Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2021-07-01T00:00:00","end":"2021-10-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2021Q4","refreshTime":"2022-05-19T13:46:23.8324499+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/4cb07f8d-486f-4940-ab6f-d153e2724b0a/XXREP_RESOURCE_TRAN_V/part-2021Q4.csv?snapshot=2022-05-19T13%3A45%3A53.3738028Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2021-10-01T00:00:00","end":"2022-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q1","refreshTime":"2022-05-19T13:45:52.9277372+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/4cb07f8d-486f-4940-ab6f-d153e2724b0a/XXREP_RESOURCE_TRAN_V/part-2022Q1.csv?snapshot=2022-05-19T13%3A45%3A10.7667058Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-01-01T00:00:00","end":"2022-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q2","refreshTime":"2022-05-19T13:40:58.6232184+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/4cb07f8d-486f-4940-ab6f-d153e2724b0a/XXREP_RESOURCE_TRAN_V/part-2022Q2.csv?snapshot=2022-05-19T13%3A40%3A38.6928128Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-01T00:00:00","end":"2022-07-01T00:00:00"}}]}]}