{"name":"INV_DATA_INTEGRITY","description":"","version":"1.0","culture":"en-US","modifiedTime":"2021-08-23T14:24:26.2906529+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"Inventory Data Integrity":{"queryId":"9c58b12e-ea50-43a0-961d-63e3707133fb","queryName":"Inventory Data Integrity","loadEnabled":true},"RangeStart":{"queryId":"e6c6fc17-6189-48f0-b270-c2fc70dd9eaf","queryName":"RangeStart"},"RangeEnd":{"queryId":"d69f958a-cc82-4853-984b-59894d383bb6","queryName":"RangeEnd"}},"document":"section Section1;\r\n\r\nshared #\"Inventory Data Integrity\" = let\r\n    Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n    #\"Navigation 1\" = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n    #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n    #\"Navigation 3\" = #\"Navigation 2\"{[Name = \"XXREP_INVASCP_DI_FACT_V\", Kind = \"View\"]}[Data],\r\n    #\"Inventory Data Integrity-5745454B5F53544152545F44415445-autogenerated_for_incremental_refresh\" = Table.SelectRows(#\"Navigation 3\", each DateTime.From([WEEK_START_DATE]) >= RangeStart and DateTime.From([WEEK_START_DATE]) < RangeEnd)\r\nin\r\n    #\"Inventory Data Integrity-5745454B5F53544152545F44415445-autogenerated_for_incremental_refresh\";\r\n\r\nshared RangeStart = let RangeStart = #datetime(0001,01,01,00,00,00) meta [IsParameterQuery=true, List={}, Type=\"DateTime\", IsParameterQueryRequired=true, Description=\"autogenerated_for_incremental_refresh\"] in RangeStart;\r\n\r\nshared RangeEnd = let RangeEnd = #datetime(9999,12,31,23,59,59) meta [IsParameterQuery=true, List={}, Type=\"DateTime\", IsParameterQueryRequired=true, Description=\"autogenerated_for_incremental_refresh\"] in RangeEnd;\r\n\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"Inventory Data Integrity","description":"","pbi:refreshPolicy":{"$type":"IncrementalRefreshPolicy","locationPattern":"Inventory%20Data%20Integrity/part.csv","rollingWindowGranularity":"quarter","rollingWindowPeriods":24,"incrementalGranularity":"month","incrementalPeriods":1},"annotations":[{"name":"pbi:IncrementalRefreshDetectChangeAttribute"},{"name":"pbi:IncrementalRefreshFilterByAttribute","value":"WEEK_START_DATE"}],"attributes":[{"name":"DATE_RUN","dataType":"dateTime"},{"name":"PERIOD_YEAR","dataType":"string"},{"name":"PERIOD_NAME","dataType":"string"},{"name":"PERIOD_END_DATE","dataType":"dateTime"},{"name":"QUARTER_NUM","dataType":"double"},{"name":"FISCAL_WEEK_ID","dataType":"double"},{"name":"ME_WEEK_ID","dataType":"double"},{"name":"ME_FLAG","dataType":"string"},{"name":"FREEZE_DATA","dataType":"string"},{"name":"PLANNING_METHOD","dataType":"string"},{"name":"ORGANIZATION_ID","dataType":"double"},{"name":"ORGANIZATION_CODE","dataType":"string"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"ITEM_NUMBER","dataType":"string"},{"name":"ITEM_DESCRIPTION","dataType":"string"},{"name":"UOM_CODE","dataType":"string"},{"name":"UOM","dataType":"string"},{"name":"ITEM_STATUS","dataType":"string"},{"name":"ITEM_TYPE_CODE","dataType":"string"},{"name":"ITEM_TYPE","dataType":"string"},{"name":"MAKE_BUY_TEMP","dataType":"string"},{"name":"MAKE_BUY_ATTR","dataType":"string"},{"name":"CURRENT_ABC_CLASS","dataType":"string"},{"name":"PLANNER","dataType":"string"},{"name":"TOTAL_ONHAND_QTY","dataType":"double"},{"name":"PLANNER_USER_NAME","dataType":"string"},{"name":"PLANNER_USER_NAME_VALID","dataType":"string"},{"name":"BUYER_ID","dataType":"double"},{"name":"BUYER","dataType":"string"},{"name":"BUYER_VALID","dataType":"string"},{"name":"INVENTORY_PLANNING_METHOD","dataType":"string"},{"name":"MRP_PLANNING_METHOD","dataType":"string"},{"name":"MIN_MAX_SOURCE_TYPE","dataType":"string"},{"name":"FIXED_DAYS_SUPPLY","dataType":"double"},{"name":"ACCEPTABLE_EARLY_DAYS","dataType":"double"},{"name":"PROCESSING_LEAD_TIME","dataType":"double"},{"name":"TOTAL_GR_26_WEEKS","dataType":"double"},{"name":"SR_VENDOR_ID","dataType":"double"},{"name":"SR_VENDOR","dataType":"string"},{"name":"SR_VENDOR_SITE_ID","dataType":"double"},{"name":"SR_VENDOR_SITE_CODE","dataType":"string"},{"name":"SR_PCT","dataType":"string"},{"name":"SR_ASL_STATUS","dataType":"string"},{"name":"SR_VNDR_SRC_ORG","dataType":"string"},{"name":"MAKE_BUY_SPLIT_SR","dataType":"string"},{"name":"ITEM_COST_USD","dataType":"double"},{"name":"PURCHASING_LIST_PRICE_USD","dataType":"double"},{"name":"DEF_RCV_SUBINV","dataType":"string"},{"name":"WIP_SUP_TYPE","dataType":"string"},{"name":"WIP_SUP_SUBINV","dataType":"string"},{"name":"RTG_COMPLETION_SUBINV","dataType":"string"},{"name":"ACTIVE_OR_INACTIVE","dataType":"string"},{"name":"LT_CHK","dataType":"double"},{"name":"LT_ERROR","dataType":"double"},{"name":"LT_ERROR_R","dataType":"string"},{"name":"BUYER_CHK","dataType":"double"},{"name":"BUYER_ERROR","dataType":"double"},{"name":"BUYER_ERROR_R","dataType":"string"},{"name":"PLANNER_CODE_CHK","dataType":"double"},{"name":"PLANNER_CODE_ERROR","dataType":"double"},{"name":"PLANNER_CODE_ERROR_R","dataType":"string"},{"name":"SR_EXISTS_CHK","dataType":"double"},{"name":"SR_EXISTS_ERROR","dataType":"double"},{"name":"SR_EXISTS_ERROR_R","dataType":"string"},{"name":"SR_MAKE_ITEM_CHK","dataType":"double"},{"name":"SR_MAKE_ITEM_ERROR","dataType":"double"},{"name":"SR_MAKE_ITEM_ERROR_R","dataType":"string"},{"name":"QOH_OBS_CHK","dataType":"double"},{"name":"QOH_OBS_ERROR","dataType":"double"},{"name":"QOH_OBS_ERROR_R","dataType":"string"},{"name":"MRP_OBS_CHK","dataType":"double"},{"name":"MRP_OBS_ERROR","dataType":"double"},{"name":"MRP_OBS_ERROR_R","dataType":"string"},{"name":"MAKE_BUY_CHK","dataType":"double"},{"name":"MAKE_BUY_ERROR","dataType":"double"},{"name":"MAKE_BUY_ERROR_R","dataType":"string"},{"name":"MIN_MAX_SRC_TYPE_CHK","dataType":"double"},{"name":"MIN_MAX_SRC_TYPE_ERROR","dataType":"double"},{"name":"MIN_MAX_SRC_TYPE_ERROR_R","dataType":"string"},{"name":"FDS_CHK","dataType":"double"},{"name":"FDS_ERROR","dataType":"double"},{"name":"FDS_ERROR_R","dataType":"string"},{"name":"AED_CHK","dataType":"double"},{"name":"AED_ERROR","dataType":"double"},{"name":"AED_ERROR_R","dataType":"string"},{"name":"MISSING_COST_CHK","dataType":"double"},{"name":"MISSING_COST_ERROR","dataType":"double"},{"name":"MISSING_COST_ERROR_R","dataType":"string"},{"name":"MISSING_PLP_ERROR","dataType":"double"},{"name":"MISSING_PLP_CHK","dataType":"double"},{"name":"MISSING_PLP_ERROR_R","dataType":"string"},{"name":"DEF_RCV_SUBINV_CHK","dataType":"double"},{"name":"DEF_RCV_SUBINV_ERROR","dataType":"double"},{"name":"DEF_RCV_SUBINV_ERROR_R","dataType":"string"},{"name":"DEF_WIP_SUP_TYPE_CHK","dataType":"double"},{"name":"DEF_WIP_SUP_TYPE_ERROR","dataType":"double"},{"name":"DEF_WIP_SUP_TYPE_ERROR_R","dataType":"string"},{"name":"DEF_WIP_SUP_SUB_CHK","dataType":"double"},{"name":"DEF_WIP_SUP_SUB_ERROR","dataType":"double"},{"name":"DEF_WIP_SUP_SUB_ERROR_R","dataType":"string"},{"name":"RTG_COMP_SUB_CHK","dataType":"double"},{"name":"RTG_COMP_SUB_ERROR","dataType":"double"},{"name":"RTG_COMP_SUB_ERROR_R","dataType":"string"},{"name":"ITEM_ORG_KEY_ID","dataType":"string"},{"name":"ITEM_ORG_KEY_CODE","dataType":"string"},{"name":"WEEK_START_DATE","dataType":"dateTime"},{"name":"WEEK_END_DATE","dataType":"dateTime"},{"name":"PERIOD_START_DATE","dataType":"dateTime"},{"name":"QUARTER_START_DATE","dataType":"dateTime"},{"name":"QUARTER_END_DATE","dataType":"dateTime"}],"partitions":[{"name":"IncrementalRefreshPolicyPartition-2016Q2","refreshTime":"2021-08-23T14:25:02.6114679+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/df4b833b-141c-4dae-b28f-1275694ecec4/Inventory%20Data%20Integrity/part-2016Q2.csv?snapshot=2021-08-23T14%3A25%3A02.4689888Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2016-04-01T00:00:00","end":"2016-07-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2016Q3","refreshTime":"2021-08-23T14:24:48.0198414+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/df4b833b-141c-4dae-b28f-1275694ecec4/Inventory%20Data%20Integrity/part-2016Q3.csv?snapshot=2021-08-23T14%3A24%3A47.7985864Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2016-07-01T00:00:00","end":"2016-10-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2016Q4","refreshTime":"2021-08-23T14:24:50.2981535+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/df4b833b-141c-4dae-b28f-1275694ecec4/Inventory%20Data%20Integrity/part-2016Q4.csv?snapshot=2021-08-23T14%3A24%3A49.3927189Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2016-10-01T00:00:00","end":"2017-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2017Q1","refreshTime":"2021-08-23T14:24:50.2981535+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/df4b833b-141c-4dae-b28f-1275694ecec4/Inventory%20Data%20Integrity/part-2017Q1.csv?snapshot=2021-08-23T14%3A24%3A49.3917184Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2017-01-01T00:00:00","end":"2017-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2017Q2","refreshTime":"2021-08-23T14:24:57.3325754+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/df4b833b-141c-4dae-b28f-1275694ecec4/Inventory%20Data%20Integrity/part-2017Q2.csv?snapshot=2021-08-23T14%3A24%3A57.2002512Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2017-04-01T00:00:00","end":"2017-07-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2017Q3","refreshTime":"2021-08-23T14:25:02.3664096+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/df4b833b-141c-4dae-b28f-1275694ecec4/Inventory%20Data%20Integrity/part-2017Q3.csv?snapshot=2021-08-23T14%3A25%3A02.2308195Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2017-07-01T00:00:00","end":"2017-10-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2017Q4","refreshTime":"2021-08-23T14:24:59.158808+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/df4b833b-141c-4dae-b28f-1275694ecec4/Inventory%20Data%20Integrity/part-2017Q4.csv?snapshot=2021-08-23T14%3A24%3A59.0095372Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2017-10-01T00:00:00","end":"2018-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2018Q1","refreshTime":"2021-08-23T14:25:01.9446209+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/df4b833b-141c-4dae-b28f-1275694ecec4/Inventory%20Data%20Integrity/part-2018Q1.csv?snapshot=2021-08-23T14%3A25%3A01.8055170Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2018-01-01T00:00:00","end":"2018-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2018Q2","refreshTime":"2021-08-23T14:24:49.4292609+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/df4b833b-141c-4dae-b28f-1275694ecec4/Inventory%20Data%20Integrity/part-2018Q2.csv?snapshot=2021-08-23T14%3A24%3A49.2706325Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2018-04-01T00:00:00","end":"2018-07-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2018Q3","refreshTime":"2021-08-23T14:24:59.3307073+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/df4b833b-141c-4dae-b28f-1275694ecec4/Inventory%20Data%20Integrity/part-2018Q3.csv?snapshot=2021-08-23T14%3A24%3A59.2036748Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2018-07-01T00:00:00","end":"2018-10-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2018Q4","refreshTime":"2021-08-23T14:24:49.3652624+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/df4b833b-141c-4dae-b28f-1275694ecec4/Inventory%20Data%20Integrity/part-2018Q4.csv?snapshot=2021-08-23T14%3A24%3A49.2526206Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2018-10-01T00:00:00","end":"2019-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2019Q1","refreshTime":"2021-08-23T14:24:57.6099105+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/df4b833b-141c-4dae-b28f-1275694ecec4/Inventory%20Data%20Integrity/part-2019Q1.csv?snapshot=2021-08-23T14%3A24%3A57.4444229Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2019-01-01T00:00:00","end":"2019-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2019Q2","refreshTime":"2021-08-23T14:24:51.7415621+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/df4b833b-141c-4dae-b28f-1275694ecec4/Inventory%20Data%20Integrity/part-2019Q2.csv?snapshot=2021-08-23T14%3A24%3A51.5602538Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2019-04-01T00:00:00","end":"2019-07-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2019Q3","refreshTime":"2021-08-23T14:24:54.2764228+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/df4b833b-141c-4dae-b28f-1275694ecec4/Inventory%20Data%20Integrity/part-2019Q3.csv?snapshot=2021-08-23T14%3A24%3A54.1420827Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2019-07-01T00:00:00","end":"2019-10-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2019Q4","refreshTime":"2021-08-23T14:24:51.3623847+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/df4b833b-141c-4dae-b28f-1275694ecec4/Inventory%20Data%20Integrity/part-2019Q4.csv?snapshot=2021-08-23T14%3A24%3A50.5035059Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2019-10-01T00:00:00","end":"2020-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2020Q1","refreshTime":"2021-08-23T14:24:55.6904301+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/df4b833b-141c-4dae-b28f-1275694ecec4/Inventory%20Data%20Integrity/part-2020Q1.csv?snapshot=2021-08-23T14%3A24%3A55.5730995Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2020-01-01T00:00:00","end":"2020-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2020Q2","refreshTime":"2021-08-23T14:24:52.8214951+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/df4b833b-141c-4dae-b28f-1275694ecec4/Inventory%20Data%20Integrity/part-2020Q2.csv?snapshot=2021-08-23T14%3A24%3A52.7030670Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2020-04-01T00:00:00","end":"2020-07-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2020Q3","refreshTime":"2021-08-23T14:25:01.8352274+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/df4b833b-141c-4dae-b28f-1275694ecec4/Inventory%20Data%20Integrity/part-2020Q3.csv?snapshot=2021-08-23T14%3A25%3A01.6964397Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2020-07-01T00:00:00","end":"2020-10-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2020Q4","refreshTime":"2021-08-23T14:24:51.7415621+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/df4b833b-141c-4dae-b28f-1275694ecec4/Inventory%20Data%20Integrity/part-2020Q4.csv?snapshot=2021-08-23T14%3A24%3A51.5592528Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2020-10-01T00:00:00","end":"2021-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2021Q1","refreshTime":"2021-08-23T14:25:01.6477165+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/df4b833b-141c-4dae-b28f-1275694ecec4/Inventory%20Data%20Integrity/part-2021Q1.csv?snapshot=2021-08-23T14%3A25%3A01.4472628Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2021-01-01T00:00:00","end":"2021-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2021Q2","refreshTime":"2021-08-23T14:28:13.8222183+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/df4b833b-141c-4dae-b28f-1275694ecec4/Inventory%20Data%20Integrity/part-2021Q2.csv?snapshot=2021-08-23T14%3A27%3A22.4642365Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2021-04-01T00:00:00","end":"2021-07-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2021Q3","refreshTime":"2021-10-04T01:02:10.2205323+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/df4b833b-141c-4dae-b28f-1275694ecec4/Inventory%20Data%20Integrity/part-2021Q3.csv?snapshot=2021-10-11T01%3A01%3A51.0170653Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2021-07-01T00:00:00","end":"2021-10-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2021Q4","refreshTime":"2022-01-03T02:05:22.0972841+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/df4b833b-141c-4dae-b28f-1275694ecec4/Inventory%20Data%20Integrity/part-2021Q4.csv?snapshot=2022-01-10T02%3A02%3A02.7333609Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2021-10-01T00:00:00","end":"2022-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q1","refreshTime":"2022-04-06T23:43:07.8316075+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/df4b833b-141c-4dae-b28f-1275694ecec4/Inventory%20Data%20Integrity/part-2022Q1.csv?snapshot=2022-04-11T01%3A04%3A55.6909398Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-01-01T00:00:00","end":"2022-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q204","refreshTime":"2022-05-02T01:06:19.7973508+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/df4b833b-141c-4dae-b28f-1275694ecec4/Inventory%20Data%20Integrity/part-2022Q204.csv?snapshot=2022-05-02T01%3A05%3A34.8366058Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-01T00:00:00","end":"2022-05-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q205","refreshTime":"2022-05-16T01:12:20.8059224+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/df4b833b-141c-4dae-b28f-1275694ecec4/Inventory%20Data%20Integrity/part-2022Q205.csv?snapshot=2022-05-16T01%3A11%3A58.9094870Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-05-01T00:00:00","end":"2022-06-01T00:00:00"}}]}]}