{"name":"OM_SALES_ORDERS_OTD","description":"OM_SALES_ORDERS_OTD","version":"1.0","culture":"en-US","modifiedTime":"2021-11-26T17:12:57.5864967+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"OM Transactions Data Mart":{"queryId":"5b701f1c-0803-4126-80d0-8d443d6b6d6f","queryName":"OM Transactions Data Mart","loadEnabled":true},"Data Update Info":{"queryId":"bf101a7d-00ba-4e9c-81cf-c7f7a51c6920","queryName":"Data Update Info","loadEnabled":true},"XXCOH_BOOKING_OFFICE_MAP":{"queryId":"03e536d6-da8e-4081-a6c8-e53052da34bf","queryName":"XXCOH_BOOKING_OFFICE_MAP","loadEnabled":true},"OM_Distinct_Product":{"queryId":"03106622-35d2-4cb4-9cd3-99cd613d154f","queryName":"OM_Distinct_Product","loadEnabled":true}},"document":"section Section1;\r\nshared #\"OM Transactions Data Mart\" = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 1\" = Navigation{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXREP_OM_OTD_V\", Kind = \"View\"]}[Data]\r\nin\r\n  #\"Navigation 2\";\r\nshared #\"Data Update Info\" = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 1\" = Navigation{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXREP_DATA_UPDATE_V\", Kind = \"View\"]}[Data],\r\n  #\"Filtered rows\" = Table.SelectRows(#\"Navigation 2\", each [TABLE_NAME] = \"ONT.OE_ORDER_LINES_ALL\")\r\nin\r\n  #\"Filtered rows\";\r\nshared XXCOH_BOOKING_OFFICE_MAP = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 1\" = Navigation{[Name = \"XXCOH\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXCOH_BOOKING_OFFICE_MAP\", Kind = \"Table\"]}[Data]\r\nin\r\n  #\"Navigation 2\";\r\nshared OM_Distinct_Product = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 1\" = Navigation{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXREP_WW_OMTRX_DATAMART_V\", Kind = \"View\"]}[Data],\r\n  #\"Removed other columns\" = Table.SelectColumns(#\"Navigation 2\", {\"TECHNICAL_BUSINESS_UNIT\", \"PRODUCT_FAMILY\"}),\r\n  #\"Removed duplicates\" = Table.Distinct(#\"Removed other columns\", {\"TECHNICAL_BUSINESS_UNIT\", \"PRODUCT_FAMILY\"})\r\nin\r\n  #\"Removed duplicates\";\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"OM Transactions Data Mart","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"OM%20Transactions%20Data%20Mart.csv"},"attributes":[{"name":"STALE_DATE","dataType":"string"},{"name":"RECEIVED_TO_SCHEDULED","dataType":"string"},{"name":"ORDER_HEADER_CREATED_BY","dataType":"string"},{"name":"SET_OF_BOOKS","dataType":"string"},{"name":"REGION","dataType":"string"},{"name":"OU","dataType":"string"},{"name":"CUSTOMER_NUMBER","dataType":"string"},{"name":"FULL_NAME_BILL_TO_COUNTRY","dataType":"string"},{"name":"ORDERED_QUANTITY","dataType":"double"},{"name":"ITEM_DESCRIPTION","dataType":"string"},{"name":"FIRST_SCHEDULE_DATE","dataType":"date"},{"name":"RECEIVED_TO_ENTERED","dataType":"string"},{"name":"RECEIVED_TO_BOOKED","dataType":"string"},{"name":"ENTERED_TO_BOOKED","dataType":"string"},{"name":"BOOKED_TO_SCHEDULED","dataType":"string"},{"name":"HEADER_ORDERED_DATE","dataType":"dateTime"},{"name":"HEADER_CREATION_DATE","dataType":"dateTime"},{"name":"HEADER_BOOK_DATE","dataType":"dateTime"},{"name":"BOOKING_OFFICE","dataType":"string"},{"name":"REPORTING_ENTITY","dataType":"string"},{"name":"ORDER_TYPE","dataType":"string"},{"name":"SCHEDULE_SHIP_DATE","dataType":"dateTime"},{"name":"REQUEST_SHIP_DATE","dataType":"dateTime"},{"name":"ORDER_NUMBER","dataType":"double"},{"name":"TECHNICAL_BUSINESS_UNIT","dataType":"string"},{"name":"WAREHOUSE","dataType":"string"},{"name":"ORDER_LINE","dataType":"string"},{"name":"ITEM_NUMBER","dataType":"string"},{"name":"LINE_CREATED_BY","dataType":"string"},{"name":"ORDER_STATUS","dataType":"string"},{"name":"LINE_STATUS","dataType":"string"},{"name":"CUSTOMER_NAME","dataType":"string"},{"name":"ALT_CUSTOMER_NAME","dataType":"string"},{"name":"CUSTOMER_TYPE","dataType":"string"},{"name":"CUSTOMER_CLASS","dataType":"string"},{"name":"EXTENDED_AMOUNT","dataType":"double"},{"name":"EXTENDED_AMOUNT_USD","dataType":"double"},{"name":"FUNCTIONAL_CURRENCY","dataType":"string"},{"name":"TRANSACTION_CURRENCY","dataType":"string"},{"name":"LINE_ID","dataType":"double"},{"name":"HEADER_ID","dataType":"double"},{"name":"PRODUCT_FAMILY","dataType":"string"},{"name":"PRODUCT_LINE","dataType":"string"},{"name":"SALESPERSON","dataType":"string"},{"name":"SHIP_TO_COUNTRY","dataType":"string"},{"name":"SO_LINE_TYPE_ID","dataType":"double"},{"name":"SO_LINE_TYPE","dataType":"string"},{"name":"ACTUAL_SHIPMENT_DATE","dataType":"dateTime"},{"name":"FORMATTED_HEADER_BOOKED_DATE","dataType":"string"},{"name":"FISCAL_PERIOD_HEADER_BOOKED","dataType":"string"},{"name":"FISCAL_YEAR_HEADER_BOOKED","dataType":"double"},{"name":"FISCAL_QUARTER_HEADER_BOOKED","dataType":"string"},{"name":"FISCAL_WEEK_HEADER_BOOKED","dataType":"double"},{"name":"ORDER_CATEGORY_UNIQUE","dataType":"string"},{"name":"ORDER_CLASSIFICATION_UNIQUE","dataType":"string"},{"name":"RECEIVED_TO_FIRST_SCHEDULED","dataType":"string"},{"name":"BOOKED_TO_FIRST_SCHEDULED","dataType":"string"},{"name":"SCHEDULED_VS_SHIP_DAYS","dataType":"double"},{"name":"FORECAST_FIELD","dataType":"string"},{"name":"SUBINVENTORY","dataType":"string"},{"name":"LINE_CREATION_DATE","dataType":"dateTime"},{"name":"BOOKED_DATE","dataType":"dateTime"},{"name":"SCHEDULE_ORDER","dataType":"string"},{"name":"BACKLOG_QUANTITY","dataType":"double"},{"name":"UNIT_SELLING_PRICE","dataType":"double"},{"name":"PROMISE_SHIP_DATE","dataType":"dateTime"},{"name":"HDR_RECEIVED_TO_SHIPPED_DAYS","dataType":"double"},{"name":"HDR_BOOKED_TO_ACTUAL_SHIP_DAYS","dataType":"double"},{"name":"LN_BOOKED_TO_ACTUAL_SHIP_DAYS","dataType":"double"},{"name":"RECEIVING_DATE","dataType":"dateTime"},{"name":"ORDER_CUSTOMER_PO","dataType":"string"},{"name":"LINE_CUSTOMER_PO","dataType":"string"},{"name":"ORDER_TYPE_ID","dataType":"double"},{"name":"SERIAL_CTRL","dataType":"string"},{"name":"LOT_CTRL","dataType":"string"},{"name":"LAST_UPDATE_DATE","dataType":"dateTime"},{"name":"L_LAST_UPDATED_BY","dataType":"string"},{"name":"ORDER_LAST_UPDATE_DATE","dataType":"dateTime"},{"name":"H_LAST_UPDATED_BY","dataType":"string"},{"name":"LINE_CATEGORY_CODE","dataType":"string"},{"name":"SHIP_FROM_ORG_ID","dataType":"double"},{"name":"FOB","dataType":"string"},{"name":"OPERATING_UNIT_ID","dataType":"double"},{"name":"INTMED_SHIP_TO","dataType":"double"},{"name":"ITEM_STATUS","dataType":"string"},{"name":"CUSTOMS_VALUE_ON_CI","dataType":"string"},{"name":"CUSTOMS_CURRENCY_ON_CI","dataType":"string"},{"name":"ORD_TOTAL","dataType":"double"},{"name":"FREIGHT_TERMS_CODE","dataType":"string"},{"name":"TAX_CODE","dataType":"string"},{"name":"LINE_FOB_POINT","dataType":"string"},{"name":"PLANNER_CODE","dataType":"string"},{"name":"SFDC_OPP_ID","dataType":"string"},{"name":"IMPORTER_ID","dataType":"string"},{"name":"IMPORTER_NAME","dataType":"string"},{"name":"END_CUST_NAME","dataType":"string"},{"name":"BILL_TO_COUNTRY","dataType":"string"},{"name":"SHIP_TO_ADDRESS1","dataType":"string"},{"name":"SHIP_TO_ADDRESS2","dataType":"string"},{"name":"FULL_NAME_SHIP_TO_COUNTRY","dataType":"string"},{"name":"OU_ORDER_LINE","dataType":"string"},{"name":"OU_ORDER","dataType":"string"},{"name":"PERIOD_NAME","dataType":"string"},{"name":"DATE_RUN","dataType":"date"},{"name":"H_CREATED_BY_ID","dataType":"double"},{"name":"ORDER_LINE_TYPE_ID_KEY","dataType":"string"},{"name":"DATA_UPDATE_DESC","dataType":"string"},{"name":"FIN_ENTITY","dataType":"string"},{"name":"FIN_SITE","dataType":"string"},{"name":"ORG_TECHNICAL_BUSINESS_UNIT","dataType":"string"},{"name":"ORG_PRODUCT_FAMILY","dataType":"string"},{"name":"FIN_TBU","dataType":"string"},{"name":"FIN_PFC","dataType":"string"},{"name":"FINPRODUCT_KEY","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-19T11:23:27.0764262+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/258441b2-4b73-4f32-89a3-0fd1a57ada00/OM%20Transactions%20Data%20Mart.csv?snapshot=2022-05-19T11%3A18%3A57.4378982Z"}]},{"$type":"LocalEntity","name":"Data Update Info","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Data%20Update%20Info.csv"},"attributes":[{"name":"TABLE_NAME","dataType":"string"},{"name":"DATA_UPDATE_DATE","dataType":"dateTime"},{"name":"DATA_UPDATE_DESC","dataType":"string"},{"name":"DATA_FLOW_REFRESH_DATE","dataType":"dateTime"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-19T11:01:42.5741496+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/258441b2-4b73-4f32-89a3-0fd1a57ada00/Data%20Update%20Info.csv?snapshot=2022-05-19T11%3A01%3A41.8232340Z"}]},{"$type":"LocalEntity","name":"XXCOH_BOOKING_OFFICE_MAP","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"XXCOH_BOOKING_OFFICE_MAP.csv"},"attributes":[{"name":"BOOKING_OFFICE_ID","dataType":"double"},{"name":"OM_CREATED_BY","dataType":"string"},{"name":"BOOKING_OFFICE","dataType":"string"},{"name":"CREATED_BY","dataType":"double"},{"name":"CREATION_DATE","dataType":"dateTime"},{"name":"LAST_UPDATED_BY","dataType":"double"},{"name":"LAST_UPDATE_DATE","dataType":"dateTime"},{"name":"COMMENTS","dataType":"string"},{"name":"VALID_FLAG","dataType":"string"},{"name":"OM_CREATED_BY_ID","dataType":"double"},{"name":"REGION","dataType":"string"},{"name":"USER_END_DATE","dataType":"dateTime"},{"name":"INCLUDE_FLAG","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-19T11:01:29.0568071+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/258441b2-4b73-4f32-89a3-0fd1a57ada00/XXCOH_BOOKING_OFFICE_MAP.csv?snapshot=2022-05-19T11%3A01%3A27.5138984Z"}]},{"$type":"LocalEntity","name":"OM_Distinct_Product","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"OM_Distinct_Product.csv"},"attributes":[{"name":"TECHNICAL_BUSINESS_UNIT","dataType":"string"},{"name":"PRODUCT_FAMILY","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-19T11:01:45.9833072+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/258441b2-4b73-4f32-89a3-0fd1a57ada00/OM_Distinct_Product.csv?snapshot=2022-05-19T11%3A01%3A45.0892582Z"}]}]}