{"name":"FISCAL_CALENDAR (Weekly Refresh)","description":"Fiscal Calendar - Refresh weekly on Saturday to retain offsets for 1 week after period closing ","version":"1.0","culture":"en-US","modifiedTime":"2021-10-21T19:13:07.0848061+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"Fiscal Calendar Days":{"queryId":"1fae949f-60d9-4e15-bd8a-41830e21c553","queryName":"Fiscal Calendar Days","loadEnabled":true},"Fiscal Context":{"queryId":"f0d44f95-b156-4123-9182-7682f2e9235d","queryName":"Fiscal Context","loadEnabled":true},"Time Balance Month (All)":{"queryId":"4a2fa1db-0fee-4fa9-80d8-31d82788c9bb","queryName":"Time Balance Month (All)","loadEnabled":true},"Time Balance Week (All)":{"queryId":"87544ad2-b88b-45d4-8a36-d7b32777f5ad","queryName":"Time Balance Week (All)","loadEnabled":true},"Fiscal Month UnPivot":{"queryId":"a63235d2-ed69-43f0-8e09-c7a442c47077","queryName":"Fiscal Month UnPivot","loadEnabled":true},"Fiscal Week UnPivot":{"queryId":"200095f6-91f4-4ec7-b137-41e0becd4e57","queryName":"Fiscal Week UnPivot","loadEnabled":true},"Time Balance Month (Current)":{"queryId":"ac26f83c-0845-4a50-b941-f60710abdb70","queryName":"Time Balance Month (Current)","loadEnabled":true},"Time Balance Week (Current)":{"queryId":"8b34ddc5-3e3d-4393-a7d0-78024142d162","queryName":"Time Balance Week (Current)","loadEnabled":true}},"document":"section Section1;\r\nshared #\"Fiscal Calendar Days\" = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 1\" = Navigation{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XX_FISCAL_DAYS_TAB\", Kind = \"Table\"]}[Data]\r\nin\r\n  #\"Navigation 2\";\r\nshared #\"Fiscal Context\" = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 1\" = Navigation{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XX_FISCAL_CONTEXT_V\", Kind = \"View\"]}[Data]\r\nin\r\n  #\"Navigation 2\";\r\nshared #\"Time Balance Month (All)\" = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  #\"Navigation 1\" = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXDIMS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 3\" = #\"Navigation 2\"{[Name = \"XX_TIMEBAL_MONTH_V\", Kind = \"View\"]}[Data]\r\nin\r\n  #\"Navigation 3\";\r\nshared #\"Time Balance Week (All)\" = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  #\"Navigation 1\" = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXDIMS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 3\" = #\"Navigation 2\"{[Name = \"XX_TIMEBAL_WEEK_V\", Kind = \"View\"]}[Data]\r\nin\r\n  #\"Navigation 3\";\r\nshared #\"Fiscal Month UnPivot\" = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 1\" = Navigation{[Name = \"XXDIMS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XX_PERIODS_UNPIVOT_V\", Kind = \"View\"]}[Data],\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Navigation 2\", {{\"FC_PERIOD_ID\", type text}}),\r\n  #\"Inserted conditional column\" = Table.AddColumn(#\"Changed column type\", \"FISCAL_DIM_SORT_VALUE\", each if [FISCAL_DIM] = \"Fiscal Month\" then [FC_PERIOD_ID] else if [FISCAL_DIM] = \"Fiscal Quarter\" then [FC_QUARTER_ID] else [FISCAL_DIM_VALUE]),\r\n  #\"Changed column type 1\" = Table.TransformColumnTypes(#\"Inserted conditional column\", {{\"FISCAL_DIM_SORT_VALUE\", type text}})\r\nin\r\n  #\"Changed column type 1\";\r\nshared #\"Fiscal Week UnPivot\" = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 1\" = Navigation{[Name = \"XXDIMS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XX_WEEK_UNPIVOT_V\", Kind = \"View\"]}[Data],\r\n  #\"Inserted conditional column\" = Table.AddColumn(#\"Navigation 2\", \"FISCAL_DIM_SORT_VALUE\", each if [FISCAL_DIM] = \"Fiscal Week\" then [FISCAL_WEEK_ID] else if [FISCAL_DIM] = \"Fiscal Month\" then [FC_PERIOD_ID] else if [FISCAL_DIM] = \"Fiscal Quarter\" then [FC_QUARTER_ID] else [FISCAL_DIM_VALUE]),\r\n  #\"Transform columns\" = Table.TransformColumnTypes(#\"Inserted conditional column\", {{\"FISCAL_DIM_SORT_VALUE\", type text}}),\r\n  #\"Replace errors\" = Table.ReplaceErrorValues(#\"Transform columns\", {{\"FISCAL_DIM_SORT_VALUE\", null}})\r\nin\r\n  #\"Replace errors\";\r\nshared #\"Time Balance Month (Current)\" = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  #\"Navigation 1\" = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXDIMS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 3\" = #\"Navigation 2\"{[Name = \"XX_TIMEBAL_CURMONTH_V\", Kind = \"View\"]}[Data]\r\nin\r\n  #\"Navigation 3\";\r\nshared #\"Time Balance Week (Current)\" = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  #\"Navigation 1\" = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXDIMS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 3\" = #\"Navigation 2\"{[Name = \"XX_TIMEBAL_CURWEEK_V\", Kind = \"View\"]}[Data]\r\nin\r\n  #\"Navigation 3\";\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"Fiscal Calendar Days","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Fiscal%20Calendar%20Days.csv"},"attributes":[{"name":"PERIOD_SET_NAME","dataType":"string"},{"name":"CAL_DAY","dataType":"dateTime"},{"name":"FISCAL_WEEK","dataType":"string"},{"name":"FISCAL_YEAR_WEEK","dataType":"string"},{"name":"FISCAL_WEEK_DISP","dataType":"string"},{"name":"FISCAL_MONTH_SORT_VALUE","dataType":"string"},{"name":"FISCAL_QUARTER_DISP","dataType":"string"},{"name":"FISCAL_WEEK_NO","dataType":"double"},{"name":"FISCAL_MONTH_WEEK_NO","dataType":"double"},{"name":"FISCAL_QTR_WEEK","dataType":"string"},{"name":"FISCAL_QTR_WEEK_NO","dataType":"double"},{"name":"GL_PERIOD","dataType":"string"},{"name":"PQ_LAST_GL_PERIOD","dataType":"string"},{"name":"PERIOD_YEAR","dataType":"double"},{"name":"FISCAL_YEAR","dataType":"string"},{"name":"QUARTER_NUM","dataType":"double"},{"name":"FISCAL_QUARTER","dataType":"string"},{"name":"FYFQ","dataType":"string"},{"name":"PRIOR_FYFQ","dataType":"string"},{"name":"PERIOD_NAME","dataType":"string"},{"name":"PERIOD_NUM","dataType":"double"},{"name":"FISCAL_DAY","dataType":"double"},{"name":"WEEK_START_DATE","dataType":"dateTime"},{"name":"WEEK_END_DATE","dataType":"dateTime"},{"name":"PERIOD_START_DATE","dataType":"dateTime"},{"name":"PERIOD_END_DATE","dataType":"dateTime"},{"name":"QUARTER_START_DATE","dataType":"dateTime"},{"name":"QUARTER_END_DATE","dataType":"dateTime"},{"name":"YEAR_START_DATE","dataType":"dateTime"},{"name":"YEAR_END_DATE","dataType":"dateTime"},{"name":"PERIOD_MONTH","dataType":"string"},{"name":"FC_PERIOD_ID","dataType":"double"},{"name":"FC_QUARTER_ID","dataType":"double"},{"name":"FC_WEEK_ID","dataType":"double"},{"name":"FC_YEAR_OFFSET","dataType":"double"},{"name":"FC_QUARTER_OFFSET","dataType":"double"},{"name":"FC_PERIOD_OFFSET","dataType":"double"},{"name":"FC_WEEK_OFFSET","dataType":"double"},{"name":"FC_DAYS_OFFSET","dataType":"double"},{"name":"FC_HALF","dataType":"string"},{"name":"NQ_FIRST_FISCAL_WEEK","dataType":"string"},{"name":"PQ_LAST_FISCAL_WEEK","dataType":"string"},{"name":"CALENDAR_YEAR","dataType":"double"},{"name":"CALENDAR_MONTH","dataType":"double"},{"name":"CALENDAR_YEARMONTHID","dataType":"string"},{"name":"CALENDAR_MONTHNAME","dataType":"string"},{"name":"CALENDAR_MONTHNAMESHORT","dataType":"string"},{"name":"CALENDAR_ISO_WEEK","dataType":"double"},{"name":"CALENDAR_US_WEEK","dataType":"double"},{"name":"CALENDAR_YEAR_SHORT","dataType":"string"},{"name":"CALENDAR_MTH_YEAR","dataType":"string"},{"name":"DAY_NAME","dataType":"string"},{"name":"DAY_OF_WEEK","dataType":"double"},{"name":"WORKING_DAY_FLAG","dataType":"double"},{"name":"CQ_LAST_FISCAL_WEEK","dataType":"string"},{"name":"ROW_CREATION_DATE","dataType":"date"},{"name":"WEEK_END_FLAG","dataType":"string"},{"name":"MONTH_END_FLAG","dataType":"string"},{"name":"QUARTER_END_FLAG","dataType":"string"},{"name":"YEAR_END_FLAG","dataType":"string"},{"name":"FISCAL_WEEK_INDICATOR","dataType":"string"},{"name":"FISCAL_WEEK_INDICATOR_SORT","dataType":"double"},{"name":"FISCAL_MONTH_INDICATOR","dataType":"string"},{"name":"FISCAL_MONTH_INDICATOR_SORT","dataType":"double"},{"name":"FISCAL_QUARTER_INDICATOR","dataType":"string"},{"name":"FISCAL_QUARTER_INDICATOR_SORT","dataType":"double"},{"name":"FISCAL_YEAR_INDICATOR","dataType":"string"},{"name":"FISCAL_YEAR_INDICATOR_SORT","dataType":"double"},{"name":"EXTRACT_DATE","dataType":"dateTime"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-14T23:31:03.5426651+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/78452847-dd04-4989-9023-1ade8f3c6ab7/Fiscal%20Calendar%20Days.csv?snapshot=2022-05-14T23%3A31%3A01.4376253Z"}]},{"$type":"LocalEntity","name":"Fiscal Context","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Fiscal%20Context.csv"},"attributes":[{"name":"PERIOD_SET_NAME","dataType":"string"},{"name":"CAL_DAY","dataType":"dateTime"},{"name":"FISCAL_WEEK","dataType":"string"},{"name":"FISCAL_YEAR_WEEK","dataType":"string"},{"name":"FISCAL_WEEK_DISP","dataType":"string"},{"name":"FISCAL_MONTH_SORT_VALUE","dataType":"string"},{"name":"FISCAL_QUARTER_DISP","dataType":"string"},{"name":"FISCAL_WEEK_NO","dataType":"double"},{"name":"FISCAL_MONTH_WEEK_NO","dataType":"double"},{"name":"FISCAL_QTR_WEEK","dataType":"string"},{"name":"FISCAL_QTR_WEEK_NO","dataType":"double"},{"name":"GL_PERIOD","dataType":"string"},{"name":"PQ_LAST_GL_PERIOD","dataType":"string"},{"name":"PERIOD_YEAR","dataType":"double"},{"name":"FISCAL_YEAR","dataType":"string"},{"name":"QUARTER_NUM","dataType":"double"},{"name":"FISCAL_QUARTER","dataType":"string"},{"name":"FYFQ","dataType":"string"},{"name":"PRIOR_FYFQ","dataType":"string"},{"name":"PERIOD_NAME","dataType":"string"},{"name":"PERIOD_NUM","dataType":"double"},{"name":"FISCAL_DAY","dataType":"double"},{"name":"WEEK_START_DATE","dataType":"dateTime"},{"name":"WEEK_END_DATE","dataType":"dateTime"},{"name":"PERIOD_START_DATE","dataType":"dateTime"},{"name":"PERIOD_END_DATE","dataType":"dateTime"},{"name":"QUARTER_START_DATE","dataType":"dateTime"},{"name":"QUARTER_END_DATE","dataType":"dateTime"},{"name":"YEAR_START_DATE","dataType":"dateTime"},{"name":"YEAR_END_DATE","dataType":"dateTime"},{"name":"PERIOD_MONTH","dataType":"string"},{"name":"FC_PERIOD_ID","dataType":"double"},{"name":"FC_QUARTER_ID","dataType":"double"},{"name":"FC_WEEK_ID","dataType":"double"},{"name":"FC_YEAR_OFFSET","dataType":"double"},{"name":"FC_QUARTER_OFFSET","dataType":"double"},{"name":"FC_PERIOD_OFFSET","dataType":"double"},{"name":"FC_WEEK_OFFSET","dataType":"double"},{"name":"FC_DAYS_OFFSET","dataType":"double"},{"name":"FC_HALF","dataType":"string"},{"name":"NQ_FIRST_FISCAL_WEEK","dataType":"string"},{"name":"PQ_LAST_FISCAL_WEEK","dataType":"string"},{"name":"CALENDAR_YEAR","dataType":"double"},{"name":"CALENDAR_MONTH","dataType":"double"},{"name":"CALENDAR_YEARMONTHID","dataType":"string"},{"name":"CALENDAR_MONTHNAME","dataType":"string"},{"name":"CALENDAR_MONTHNAMESHORT","dataType":"string"},{"name":"CALENDAR_ISO_WEEK","dataType":"double"},{"name":"CALENDAR_US_WEEK","dataType":"double"},{"name":"CALENDAR_YEAR_SHORT","dataType":"string"},{"name":"CALENDAR_MTH_YEAR","dataType":"string"},{"name":"DAY_NAME","dataType":"string"},{"name":"DAY_OF_WEEK","dataType":"double"},{"name":"WORKING_DAY_FLAG","dataType":"double"},{"name":"CQ_LAST_FISCAL_WEEK","dataType":"string"},{"name":"ROW_CREATION_DATE","dataType":"date"},{"name":"WEEK_END_FLAG","dataType":"string"},{"name":"MONTH_END_FLAG","dataType":"string"},{"name":"QUARTER_END_FLAG","dataType":"string"},{"name":"YEAR_END_FLAG","dataType":"string"},{"name":"FISCAL_WEEK_INDICATOR","dataType":"string"},{"name":"FISCAL_WEEK_INDICATOR_SORT","dataType":"double"},{"name":"FISCAL_MONTH_INDICATOR","dataType":"string"},{"name":"FISCAL_MONTH_INDICATOR_SORT","dataType":"double"},{"name":"FISCAL_QUARTER_INDICATOR","dataType":"string"},{"name":"FISCAL_QUARTER_INDICATOR_SORT","dataType":"double"},{"name":"FISCAL_YEAR_INDICATOR","dataType":"string"},{"name":"FISCAL_YEAR_INDICATOR_SORT","dataType":"double"},{"name":"EXTRACT_DATE","dataType":"dateTime"},{"name":"CONTEXT","dataType":"string"},{"name":"DATA_UPDATE_DESC","dataType":"string"},{"name":"CONTEXT_FYWK","dataType":"string"},{"name":"CONTEXT_PERIOD","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-14T23:30:26.4059415+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/78452847-dd04-4989-9023-1ade8f3c6ab7/Fiscal%20Context.csv?snapshot=2022-05-14T23%3A30%3A25.7999328Z"}]},{"$type":"LocalEntity","name":"Time Balance Month (All)","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Time%20Balance%20Month%20%28All%29.csv"},"attributes":[{"name":"FISCAL_PERIOD_KEY","dataType":"string"},{"name":"FISCAL_DIM_ID","dataType":"double"},{"name":"FISCAL_DIM","dataType":"string"},{"name":"FISCAL_DIM_VALUE","dataType":"string"},{"name":"FISCAL_DIM_SORT_VALUE","dataType":"string"},{"name":"FC_YEAR_OFFSET","dataType":"double"},{"name":"PERIOD_YEAR","dataType":"double"},{"name":"GL_PERIOD","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-14T23:30:25.5153118+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/78452847-dd04-4989-9023-1ade8f3c6ab7/Time%20Balance%20Month%20(All).csv?snapshot=2022-05-14T23%3A30%3A24.7735176Z"}]},{"$type":"LocalEntity","name":"Time Balance Week (All)","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Time%20Balance%20Week%20%28All%29.csv"},"attributes":[{"name":"FISCAL_PERIOD_KEY","dataType":"string"},{"name":"FISCAL_DIM_ID","dataType":"double"},{"name":"FISCAL_DIM","dataType":"string"},{"name":"FISCAL_DIM_VALUE","dataType":"string"},{"name":"FISCAL_DIM_SORT_VALUE","dataType":"string"},{"name":"FC_YEAR_OFFSET","dataType":"double"},{"name":"PERIOD_YEAR","dataType":"double"},{"name":"GL_PERIOD","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-14T23:30:24.56219+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/78452847-dd04-4989-9023-1ade8f3c6ab7/Time%20Balance%20Week%20(All).csv?snapshot=2022-05-14T23%3A30%3A23.8960178Z"}]},{"$type":"LocalEntity","name":"Fiscal Month UnPivot","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Fiscal%20Month%20UnPivot.csv"},"attributes":[{"name":"FISCAL_MONTH_KEY","dataType":"string"},{"name":"FC_PERIOD_ID","dataType":"string"},{"name":"FC_QUARTER_ID","dataType":"string"},{"name":"FISCAL_DIM","dataType":"string"},{"name":"FISCAL_DIM_VALUE","dataType":"string"},{"name":"FISCAL_DIM_SORT_VALUE","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-14T23:30:35.0293451+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/78452847-dd04-4989-9023-1ade8f3c6ab7/Fiscal%20Month%20UnPivot.csv?snapshot=2022-05-14T23%3A30%3A34.7988060Z"}]},{"$type":"LocalEntity","name":"Fiscal Week UnPivot","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Fiscal%20Week%20UnPivot.csv"},"attributes":[{"name":"FISCAL_WEEK_KEY","dataType":"string"},{"name":"FISCAL_WEEK_ID","dataType":"string"},{"name":"FC_PERIOD_ID","dataType":"string"},{"name":"FC_QUARTER_ID","dataType":"string"},{"name":"FISCAL_DIM","dataType":"string"},{"name":"FISCAL_DIM_VALUE","dataType":"string"},{"name":"FISCAL_DIM_SORT_VALUE","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-14T23:30:25.7965834+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/78452847-dd04-4989-9023-1ade8f3c6ab7/Fiscal%20Week%20UnPivot.csv?snapshot=2022-05-14T23%3A30%3A24.6076125Z"}]},{"$type":"LocalEntity","name":"Time Balance Month (Current)","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Time%20Balance%20Month%20%28Current%29.csv"},"attributes":[{"name":"FISCAL_PERIOD_KEY","dataType":"string"},{"name":"FISCAL_DIM_ID","dataType":"double"},{"name":"FISCAL_DIM","dataType":"string"},{"name":"FISCAL_DIM_VALUE","dataType":"string"},{"name":"FISCAL_DIM_SORT_VALUE","dataType":"string"},{"name":"FC_YEAR_OFFSET","dataType":"double"},{"name":"PERIOD_YEAR","dataType":"double"},{"name":"GL_PERIOD","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-14T23:30:24.4528137+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/78452847-dd04-4989-9023-1ade8f3c6ab7/Time%20Balance%20Month%20(Current).csv?snapshot=2022-05-14T23%3A30%3A21.9891059Z"}]},{"$type":"LocalEntity","name":"Time Balance Week (Current)","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Time%20Balance%20Week%20%28Current%29.csv"},"attributes":[{"name":"FISCAL_PERIOD_KEY","dataType":"string"},{"name":"FISCAL_DIM_ID","dataType":"double"},{"name":"FISCAL_DIM","dataType":"string"},{"name":"FISCAL_DIM_VALUE","dataType":"string"},{"name":"FISCAL_DIM_SORT_VALUE","dataType":"string"},{"name":"FC_YEAR_OFFSET","dataType":"double"},{"name":"PERIOD_YEAR","dataType":"double"},{"name":"GL_PERIOD","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-14T23:30:24.5153161+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/78452847-dd04-4989-9023-1ade8f3c6ab7/Time%20Balance%20Week%20(Current).csv?snapshot=2022-05-14T23%3A30%3A23.5142355Z"}]}]}