{"name":"Customer Information","description":"","version":"1.0","culture":"en-US","modifiedTime":"2021-07-11T01:53:39.4721308+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"XXCOH_RA_CUSTOMERS":{"queryId":"bac648ea-16f0-45b7-a6d0-49ddd18322db","queryName":"XXCOH_RA_CUSTOMERS","loadEnabled":true}},"document":"section Section1;\r\nshared XXCOH_RA_CUSTOMERS = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 1\" = Navigation{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXCOH_RA_CUSTOMERS\", Kind = \"View\"]}[Data],\r\n  #\"Inserted conditional column\" = Table.AddColumn(#\"Navigation 2\", \"Main Customer Name\", each if [ATTRIBUTE8] = \"Y\" then [CUSTOMER_NAME_PHONETIC] else [CUSTOMER_NAME]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Inserted conditional column\", {{\"Main Customer Name\", type text}})\r\nin\r\n  #\"Changed column type\";\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"XXCOH_RA_CUSTOMERS","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"XXCOH_RA_CUSTOMERS.csv"},"attributes":[{"name":"ROW_ID","dataType":"double"},{"name":"CUSTOMER_ID","dataType":"double"},{"name":"PARTY_ID","dataType":"double"},{"name":"PARTY_NUMBER","dataType":"string"},{"name":"PARTY_TYPE","dataType":"string"},{"name":"LAST_UPDATE_DATE","dataType":"dateTime"},{"name":"LAST_UPDATED_BY","dataType":"double"},{"name":"CREATION_DATE","dataType":"dateTime"},{"name":"CREATED_BY","dataType":"double"},{"name":"CUSTOMER_NAME","dataType":"string"},{"name":"CUSTOMER_NUMBER","dataType":"string"},{"name":"ORIG_SYSTEM_REFERENCE","dataType":"string"},{"name":"STATUS","dataType":"string"},{"name":"LAST_UPDATE_LOGIN","dataType":"double"},{"name":"CUSTOMER_TYPE","dataType":"string"},{"name":"CUSTOMER_PROSPECT_CODE","dataType":"string"},{"name":"CUSTOMER_CLASS_CODE","dataType":"string"},{"name":"PRIMARY_SALESREP_ID","dataType":"double"},{"name":"SALES_CHANNEL_CODE","dataType":"string"},{"name":"SIC_CODE","dataType":"string"},{"name":"ORDER_TYPE_ID","dataType":"double"},{"name":"PRICE_LIST_ID","dataType":"double"},{"name":"ATTRIBUTE_CATEGORY","dataType":"string"},{"name":"ATTRIBUTE1","dataType":"string"},{"name":"ATTRIBUTE2","dataType":"string"},{"name":"ATTRIBUTE3","dataType":"string"},{"name":"ATTRIBUTE4","dataType":"string"},{"name":"ATTRIBUTE5","dataType":"string"},{"name":"ATTRIBUTE6","dataType":"string"},{"name":"ATTRIBUTE7","dataType":"string"},{"name":"ATTRIBUTE8","dataType":"string"},{"name":"ATTRIBUTE9","dataType":"string"},{"name":"ATTRIBUTE10","dataType":"string"},{"name":"REQUEST_ID","dataType":"double"},{"name":"PROGRAM_APPLICATION_ID","dataType":"double"},{"name":"PROGRAM_ID","dataType":"double"},{"name":"PROGRAM_UPDATE_DATE","dataType":"dateTime"},{"name":"ANALYSIS_FY","dataType":"string"},{"name":"CUSTOMER_CATEGORY_CODE","dataType":"string"},{"name":"CUSTOMER_GROUP_CODE","dataType":"string"},{"name":"CUSTOMER_KEY","dataType":"string"},{"name":"CUSTOMER_SUBGROUP_CODE","dataType":"string"},{"name":"FISCAL_YEAREND_MONTH","dataType":"string"},{"name":"NET_WORTH","dataType":"double"},{"name":"NUM_OF_EMPLOYEES","dataType":"double"},{"name":"POTENTIAL_REVENUE_CURR_FY","dataType":"double"},{"name":"POTENTIAL_REVENUE_NEXT_FY","dataType":"double"},{"name":"RANK","dataType":"string"},{"name":"REFERENCE_USE_FLAG","dataType":"string"},{"name":"TAX_CODE","dataType":"string"},{"name":"TAX_REFERENCE","dataType":"string"},{"name":"ATTRIBUTE11","dataType":"string"},{"name":"ATTRIBUTE12","dataType":"string"},{"name":"ATTRIBUTE13","dataType":"string"},{"name":"ATTRIBUTE14","dataType":"string"},{"name":"ATTRIBUTE15","dataType":"string"},{"name":"THIRD_PARTY_FLAG","dataType":"string"},{"name":"ACCESS_TEMPLATE_ENTITY_CODE","dataType":"string"},{"name":"PRIMARY_SPECIALIST_ID","dataType":"double"},{"name":"SECONDARY_SPECIALIST_ID","dataType":"double"},{"name":"COMPETITOR_FLAG","dataType":"string"},{"name":"DUNNING_SITE_USE_ID","dataType":"double"},{"name":"STATEMENT_SITE_USE_ID","dataType":"double"},{"name":"ORIG_SYSTEM","dataType":"string"},{"name":"YEAR_ESTABLISHED","dataType":"double"},{"name":"COTERMINATE_DAY_MONTH","dataType":"string"},{"name":"FOB_POINT","dataType":"string"},{"name":"FREIGHT_TERM","dataType":"string"},{"name":"GSA_INDICATOR","dataType":"string"},{"name":"SHIP_PARTIAL","dataType":"string"},{"name":"SHIP_VIA","dataType":"string"},{"name":"WAREHOUSE_ID","dataType":"double"},{"name":"PAYMENT_TERM_ID","dataType":"double"},{"name":"TAX_EXEMPT","dataType":"string"},{"name":"TAX_EXEMPT_NUM","dataType":"string"},{"name":"TAX_EXEMPT_REASON_CODE","dataType":"string"},{"name":"JGZZ_FISCAL_CODE","dataType":"string"},{"name":"DO_NOT_MAIL_FLAG","dataType":"string"},{"name":"MISSION_STATEMENT","dataType":"string"},{"name":"CUSTOMER_NAME_PHONETIC","dataType":"string"},{"name":"TAX_HEADER_LEVEL_FLAG","dataType":"string"},{"name":"TAX_ROUNDING_RULE","dataType":"string"},{"name":"WH_UPDATE_DATE","dataType":"dateTime"},{"name":"GLOBAL_ATTRIBUTE1","dataType":"string"},{"name":"GLOBAL_ATTRIBUTE2","dataType":"string"},{"name":"GLOBAL_ATTRIBUTE3","dataType":"string"},{"name":"GLOBAL_ATTRIBUTE4","dataType":"string"},{"name":"GLOBAL_ATTRIBUTE5","dataType":"string"},{"name":"GLOBAL_ATTRIBUTE6","dataType":"string"},{"name":"GLOBAL_ATTRIBUTE7","dataType":"string"},{"name":"GLOBAL_ATTRIBUTE8","dataType":"string"},{"name":"GLOBAL_ATTRIBUTE9","dataType":"string"},{"name":"GLOBAL_ATTRIBUTE10","dataType":"string"},{"name":"GLOBAL_ATTRIBUTE11","dataType":"string"},{"name":"GLOBAL_ATTRIBUTE12","dataType":"string"},{"name":"GLOBAL_ATTRIBUTE13","dataType":"string"},{"name":"GLOBAL_ATTRIBUTE14","dataType":"string"},{"name":"GLOBAL_ATTRIBUTE15","dataType":"string"},{"name":"GLOBAL_ATTRIBUTE16","dataType":"string"},{"name":"GLOBAL_ATTRIBUTE17","dataType":"string"},{"name":"GLOBAL_ATTRIBUTE18","dataType":"string"},{"name":"GLOBAL_ATTRIBUTE19","dataType":"string"},{"name":"GLOBAL_ATTRIBUTE20","dataType":"string"},{"name":"GLOBAL_ATTRIBUTE_CATEGORY","dataType":"string"},{"name":"URL","dataType":"string"},{"name":"LANGUAGE","dataType":"string"},{"name":"TRANSLATED_CUSTOMER_NAME","dataType":"string"},{"name":"PERSON_PRE_NAME_ADJUNCT","dataType":"string"},{"name":"PERSON_FIRST_NAME","dataType":"string"},{"name":"PERSON_MIDDLE_NAME","dataType":"string"},{"name":"PERSON_LAST_NAME","dataType":"string"},{"name":"PERSON_SUFFIX","dataType":"string"},{"name":"PERSON_FIRST_NAME_PHONETIC","dataType":"string"},{"name":"PERSON_LAST_NAME_PHONETIC","dataType":"string"},{"name":"SHIP_SETS_INCLUDE_LINES_FLAG","dataType":"string"},{"name":"ARRIVALSETS_INCLUDE_LINES_FLAG","dataType":"string"},{"name":"SCHED_DATE_PUSH_FLAG","dataType":"string"},{"name":"OVER_SHIPMENT_TOLERANCE","dataType":"double"},{"name":"UNDER_SHIPMENT_TOLERANCE","dataType":"double"},{"name":"OVER_RETURN_TOLERANCE","dataType":"double"},{"name":"UNDER_RETURN_TOLERANCE","dataType":"double"},{"name":"ITEM_CROSS_REF_PREF","dataType":"string"},{"name":"DATE_TYPE_PREFERENCE","dataType":"string"},{"name":"DATES_NEGATIVE_TOLERANCE","dataType":"double"},{"name":"DATES_POSITIVE_TOLERANCE","dataType":"double"},{"name":"INVOICE_QUANTITY_RULE","dataType":"string"},{"name":"ATTRIBUTE16","dataType":"string"},{"name":"ATTRIBUTE17","dataType":"string"},{"name":"ATTRIBUTE18","dataType":"string"},{"name":"ATTRIBUTE19","dataType":"string"},{"name":"ATTRIBUTE20","dataType":"string"},{"name":"DUNS_NUMBER","dataType":"double"},{"name":"DUNS_NUMBER_C","dataType":"string"},{"name":"PARTY_LAST_UPDATE_DATE","dataType":"dateTime"},{"name":"SIC_CODE_TYPE","dataType":"string"},{"name":"Main Customer Name","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2021-11-05T19:37:29.8311291+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/68deeacc-79ff-4c25-8367-898a2ca47bf3/XXCOH_RA_CUSTOMERS.csv?snapshot=2021-11-05T19%3A37%3A24.3205051Z"}]}]}