{"name":"GL_BAL_EXP_RELATED","description":"","version":"1.0","culture":"en-US","modifiedTime":"2021-10-18T02:15:41.8799367+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"Expense Forecast":{"queryId":"0457527e-9d12-4bad-bead-79bd17f29b79","queryName":"Expense Forecast","loadEnabled":true},"GL Balances":{"queryId":"9fbc2191-c6a3-4104-91ae-c3885e5bbd05","queryName":"GL Balances","loadEnabled":true},"RangeEnd":{"queryId":"7d5a94a3-98cf-4850-adac-c31d35baa07e","queryName":"RangeEnd"},"RangeStart":{"queryId":"d81fe5f9-34e5-4b25-8ddf-933374319a1e","queryName":"RangeStart"},"Entity Department Details":{"queryId":"6e1c7ee3-de24-4823-ae45-daecfbbd009b","queryName":"Entity Department Details","loadEnabled":true}},"document":"section Section1;\r\n\r\nshared #\"Expense Forecast\" = let\r\n    Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_PROD_WHSE\", null),\r\n    Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n    #\"Navigation 1\" = Navigation{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n    #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXREP_EXP_FORECAST_V\", Kind = \"View\"]}[Data]\r\nin\r\n    #\"Navigation 2\";\r\n\r\nshared #\"Entity Department Details\" = let\r\n    Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_PROD_WHSE\", null),\r\n    Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n    #\"Navigation 1\" = Navigation{[Name = \"XXCOH\", Kind = \"Schema\"]}[Data],\r\n    #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXSF_ENTITY_DEPT_DETAIL\", Kind = \"Table\"]}[Data]\r\nin\r\n    #\"Navigation 2\";\r\n\r\nshared #\"GL Balances\" = let\r\n    Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_PROD_WHSE\", null),\r\n    #\"Navigation 1\" = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n    #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n    #\"Navigation 3\" = #\"Navigation 2\"{[Name = \"XXREP_GL_BALANCES_V\", Kind = \"View\"]}[Data],\r\n    #\"GL Balances-504552494F445F454E445F44415445-autogenerated_for_incremental_refresh\" = Table.SelectRows(#\"Navigation 3\", each DateTime.From([PERIOD_END_DATE]) >= RangeStart and DateTime.From([PERIOD_END_DATE]) < RangeEnd)\r\nin\r\n    #\"GL Balances-504552494F445F454E445F44415445-autogenerated_for_incremental_refresh\";\r\n\r\nshared RangeStart = let RangeStart = #datetime(0001,01,01,00,00,00) meta [IsParameterQuery=true, List={}, Type=\"DateTime\", IsParameterQueryRequired=true, Description=\"autogenerated_for_incremental_refresh\"] in RangeStart;\r\n\r\nshared RangeEnd = let RangeEnd = #datetime(9999,12,31,23,59,59) meta [IsParameterQuery=true, List={}, Type=\"DateTime\", IsParameterQueryRequired=true, Description=\"autogenerated_for_incremental_refresh\"] in RangeEnd;\r\n\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"Expense Forecast","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Expense%20Forecast.csv"},"attributes":[{"name":"PROJECT_CODE","dataType":"string"},{"name":"ENTITY_DEPT_CODE","dataType":"string"},{"name":"VERSION","dataType":"string"},{"name":"FISCAL_YEAR","dataType":"string"},{"name":"SCENARIO","dataType":"string"},{"name":"FISCAL_MONTH","dataType":"string"},{"name":"ACCOUNT_CODE","dataType":"string"},{"name":"AMOUNT","dataType":"double"},{"name":"CURRENCY","dataType":"string"},{"name":"DEPT_SUB_FUNCTION","dataType":"string"},{"name":"DEPT_FUNCTION","dataType":"string"},{"name":"TBU","dataType":"string"},{"name":"COUNTRY","dataType":"string"},{"name":"REGION","dataType":"string"},{"name":"PERIOD_START_DATE","dataType":"dateTime"},{"name":"PERIOD_END_DATE","dataType":"dateTime"},{"name":"QUARTER_START_DATE","dataType":"dateTime"},{"name":"QUARTER_END_DATE","dataType":"dateTime"},{"name":"YEAR_START_DATE","dataType":"dateTime"},{"name":"YEAR_END_DATE","dataType":"dateTime"},{"name":"QUARTER_NUM","dataType":"double"},{"name":"FISCAL_QUARTER","dataType":"string"},{"name":"FYFQ","dataType":"string"},{"name":"PERIOD_MONTH","dataType":"string"},{"name":"EXPENSE_KEY","dataType":"string"},{"name":"GL_PERIOD","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-12T15:01:56.8541731+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/14fe25b9-fb78-4792-bddc-dc886c775fad/Expense%20Forecast.csv?snapshot=2022-06-12T15%3A01%3A52.4624117Z"}]},{"$type":"LocalEntity","name":"GL Balances","description":"","pbi:refreshPolicy":{"$type":"IncrementalRefreshPolicy","locationPattern":"GL%20Balances/part.csv","rollingWindowGranularity":"year","rollingWindowPeriods":25,"incrementalGranularity":"quarter","incrementalPeriods":3},"annotations":[{"name":"pbi:IncrementalRefreshDetectChangeAttribute"},{"name":"pbi:IncrementalRefreshFilterByAttribute","value":"PERIOD_END_DATE"}],"attributes":[{"name":"LEDGER_ID","dataType":"double"},{"name":"LEDGER_NAME","dataType":"string"},{"name":"PERIOD_YEAR","dataType":"double"},{"name":"PERIOD_NAME","dataType":"string"},{"name":"ENTITY_CODE","dataType":"string"},{"name":"DEPARTMENT_CODE","dataType":"string"},{"name":"ENTITY_DEPT_CODE","dataType":"string"},{"name":"ACCOUNT_CODE","dataType":"string"},{"name":"PROJECT_CODE","dataType":"string"},{"name":"INTERCO_CODE","dataType":"string"},{"name":"TBD_CODE","dataType":"string"},{"name":"CURRENCY_CODE","dataType":"string"},{"name":"EOP_BS_USD_RATE","dataType":"double"},{"name":"EOP_PL_USD_RATE","dataType":"double"},{"name":"BEGIN_BALANCE_AMT","dataType":"double"},{"name":"DEBIT_AMT","dataType":"double"},{"name":"CREDIT_AMT","dataType":"double"},{"name":"PERIOD_NET_AMT","dataType":"double"},{"name":"ENDING_BALANCE_AMT","dataType":"double"},{"name":"PERIOD_START_DATE","dataType":"dateTime"},{"name":"PERIOD_END_DATE","dataType":"dateTime"},{"name":"QUARTER_START_DATE","dataType":"dateTime"},{"name":"QUARTER_END_DATE","dataType":"dateTime"},{"name":"YEAR_START_DATE","dataType":"dateTime"},{"name":"YEAR_END_DATE","dataType":"dateTime"},{"name":"FISCAL_YEAR","dataType":"string"},{"name":"QUARTER_NUM","dataType":"double"},{"name":"FISCAL_QUARTER","dataType":"string"},{"name":"FYFQ","dataType":"string"},{"name":"EXPENSE_KEY","dataType":"string"},{"name":"GLCCID_DETAIL_KEY","dataType":"string"},{"name":"GL_ENTITY_ACC_DETAIL_KEY","dataType":"string"},{"name":"PERIOD_NET_USD_PL","dataType":"double"},{"name":"PERIOD_NET_USD_BS","dataType":"double"}],"partitions":[{"name":"IncrementalRefreshPolicyPartition-1997","refreshTime":"2021-10-24T15:00:37.6557375+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/14fe25b9-fb78-4792-bddc-dc886c775fad/GL%20Balances/part-1997.csv?snapshot=2021-10-24T15%3A00%3A37.3849724Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"1997-01-01T00:00:00","end":"1998-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-1998","refreshTime":"2021-10-24T15:00:39.3411386+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/14fe25b9-fb78-4792-bddc-dc886c775fad/GL%20Balances/part-1998.csv?snapshot=2021-10-24T15%3A00%3A39.1829407Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"1998-01-01T00:00:00","end":"1999-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-1999","refreshTime":"2021-10-24T15:00:58.1320313+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/14fe25b9-fb78-4792-bddc-dc886c775fad/GL%20Balances/part-1999.csv?snapshot=2021-10-24T15%3A00%3A57.1895968Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"1999-01-01T00:00:00","end":"2000-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2000","refreshTime":"2021-10-24T15:00:50.7789117+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/14fe25b9-fb78-4792-bddc-dc886c775fad/GL%20Balances/part-2000.csv?snapshot=2021-10-24T15%3A00%3A50.3595204Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2000-01-01T00:00:00","end":"2001-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2001","refreshTime":"2021-10-24T15:00:46.6417009+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/14fe25b9-fb78-4792-bddc-dc886c775fad/GL%20Balances/part-2001.csv?snapshot=2021-10-24T15%3A00%3A46.3818050Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2001-01-01T00:00:00","end":"2002-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2002","refreshTime":"2021-10-24T15:01:27.9798673+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/14fe25b9-fb78-4792-bddc-dc886c775fad/GL%20Balances/part-2002.csv?snapshot=2021-10-24T15%3A01%3A25.9270921Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2002-01-01T00:00:00","end":"2003-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2003","refreshTime":"2021-10-24T15:00:58.6958573+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/14fe25b9-fb78-4792-bddc-dc886c775fad/GL%20Balances/part-2003.csv?snapshot=2021-10-24T15%3A00%3A53.8735020Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2003-01-01T00:00:00","end":"2004-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2004","refreshTime":"2021-10-24T15:02:06.2887608+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/14fe25b9-fb78-4792-bddc-dc886c775fad/GL%20Balances/part-2004.csv?snapshot=2021-10-24T15%3A02%3A00.7411019Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2004-01-01T00:00:00","end":"2005-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2005","refreshTime":"2021-10-24T15:02:24.4388177+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/14fe25b9-fb78-4792-bddc-dc886c775fad/GL%20Balances/part-2005.csv?snapshot=2021-10-24T15%3A02%3A14.4862098Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2005-01-01T00:00:00","end":"2006-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2006","refreshTime":"2021-10-24T15:02:22.5904715+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/14fe25b9-fb78-4792-bddc-dc886c775fad/GL%20Balances/part-2006.csv?snapshot=2021-10-24T15%3A02%3A16.7229258Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2006-01-01T00:00:00","end":"2007-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2007","refreshTime":"2021-10-24T15:02:23.874741+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/14fe25b9-fb78-4792-bddc-dc886c775fad/GL%20Balances/part-2007.csv?snapshot=2021-10-24T15%3A02%3A18.3439949Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2007-01-01T00:00:00","end":"2008-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2008","refreshTime":"2021-10-24T15:02:21.1842256+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/14fe25b9-fb78-4792-bddc-dc886c775fad/GL%20Balances/part-2008.csv?snapshot=2021-10-24T15%3A02%3A14.1284150Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2008-01-01T00:00:00","end":"2009-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2009","refreshTime":"2021-10-24T15:02:17.0907777+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/14fe25b9-fb78-4792-bddc-dc886c775fad/GL%20Balances/part-2009.csv?snapshot=2021-10-24T15%3A02%3A09.9598085Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2009-01-01T00:00:00","end":"2010-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2010","refreshTime":"2021-10-24T15:02:13.821676+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/14fe25b9-fb78-4792-bddc-dc886c775fad/GL%20Balances/part-2010.csv?snapshot=2021-10-24T15%3A02%3A07.2053896Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2010-01-01T00:00:00","end":"2011-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2011","refreshTime":"2021-10-24T15:02:23.49973+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/14fe25b9-fb78-4792-bddc-dc886c775fad/GL%20Balances/part-2011.csv?snapshot=2021-10-24T15%3A02%3A17.3945403Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2011-01-01T00:00:00","end":"2012-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2012","refreshTime":"2021-10-24T15:01:38.6388908+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/14fe25b9-fb78-4792-bddc-dc886c775fad/GL%20Balances/part-2012.csv?snapshot=2021-10-24T15%3A01%3A30.8852453Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2012-01-01T00:00:00","end":"2013-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2013","refreshTime":"2021-10-24T15:02:21.3404527+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/14fe25b9-fb78-4792-bddc-dc886c775fad/GL%20Balances/part-2013.csv?snapshot=2021-10-24T15%3A02%3A14.7400640Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2013-01-01T00:00:00","end":"2014-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2014","refreshTime":"2021-10-24T15:02:13.6810378+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/14fe25b9-fb78-4792-bddc-dc886c775fad/GL%20Balances/part-2014.csv?snapshot=2021-10-24T15%3A02%3A05.7062498Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2014-01-01T00:00:00","end":"2015-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2015","refreshTime":"2021-10-24T15:02:24.7357975+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/14fe25b9-fb78-4792-bddc-dc886c775fad/GL%20Balances/part-2015.csv?snapshot=2021-10-24T15%3A02%3A14.8579965Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2015-01-01T00:00:00","end":"2016-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2016","refreshTime":"2021-10-24T15:02:26.7375364+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/14fe25b9-fb78-4792-bddc-dc886c775fad/GL%20Balances/part-2016.csv?snapshot=2021-10-24T15%3A02%3A18.4109561Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2016-01-01T00:00:00","end":"2017-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2017","refreshTime":"2021-10-24T15:02:24.5638302+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/14fe25b9-fb78-4792-bddc-dc886c775fad/GL%20Balances/part-2017.csv?snapshot=2021-10-24T15%3A02%3A17.5024778Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2017-01-01T00:00:00","end":"2018-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2018","refreshTime":"2021-10-24T15:02:25.5514549+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/14fe25b9-fb78-4792-bddc-dc886c775fad/GL%20Balances/part-2018.csv?snapshot=2021-10-24T15%3A02%3A18.5628692Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2018-01-01T00:00:00","end":"2019-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2019","refreshTime":"2021-10-24T15:02:23.844302+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/14fe25b9-fb78-4792-bddc-dc886c775fad/GL%20Balances/part-2019.csv?snapshot=2021-10-24T15%3A02%3A14.9619363Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2019-01-01T00:00:00","end":"2020-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2020","refreshTime":"2021-10-24T15:02:25.1764211+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/14fe25b9-fb78-4792-bddc-dc886c775fad/GL%20Balances/part-2020.csv?snapshot=2021-10-24T15%3A02%3A17.5764351Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2020-01-01T00:00:00","end":"2021-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2021Q1","refreshTime":"2021-10-24T15:01:50.3005624+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/14fe25b9-fb78-4792-bddc-dc886c775fad/GL%20Balances/part-2021Q1.csv?snapshot=2021-10-24T15%3A01%3A46.6731786Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2021-01-01T00:00:00","end":"2021-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2021Q2","refreshTime":"2022-01-02T16:02:02.7586967+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/14fe25b9-fb78-4792-bddc-dc886c775fad/GL%20Balances/part-2021Q2.csv?snapshot=2022-01-02T16%3A01%3A59.8888124Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2021-04-01T00:00:00","end":"2021-07-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2021Q3","refreshTime":"2022-04-03T15:00:19.8654976+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/14fe25b9-fb78-4792-bddc-dc886c775fad/GL%20Balances/part-2021Q3.csv?snapshot=2022-04-03T15%3A00%3A17.7577617Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2021-07-01T00:00:00","end":"2021-10-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2021Q4","refreshTime":"2022-06-12T15:01:48.4540778+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/14fe25b9-fb78-4792-bddc-dc886c775fad/GL%20Balances/part-2021Q4.csv?snapshot=2022-06-12T15%3A01%3A43.6103618Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2021-10-01T00:00:00","end":"2022-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q1","refreshTime":"2022-06-12T15:01:48.7197187+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/14fe25b9-fb78-4792-bddc-dc886c775fad/GL%20Balances/part-2022Q1.csv?snapshot=2022-06-12T15%3A01%3A45.3443929Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-01-01T00:00:00","end":"2022-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q2","refreshTime":"2022-06-12T15:01:49.8156254+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/14fe25b9-fb78-4792-bddc-dc886c775fad/GL%20Balances/part-2022Q2.csv?snapshot=2022-06-12T15%3A01%3A45.3453927Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-01T00:00:00","end":"2022-07-01T00:00:00"}}]},{"$type":"LocalEntity","name":"Entity Department Details","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Entity%20Department%20Details.csv"},"attributes":[{"name":"RECORD_ID","dataType":"double"},{"name":"ENTITY_DEPT_CODE","dataType":"string"},{"name":"ENTITY_CODE","dataType":"string"},{"name":"DEPT_SUB_FUNCTION","dataType":"string"},{"name":"DEPT_FUNCTION","dataType":"string"},{"name":"TBU","dataType":"string"},{"name":"COUNTRY","dataType":"string"},{"name":"REGION","dataType":"string"},{"name":"EVP_OWNER","dataType":"string"},{"name":"STATUS","dataType":"string"},{"name":"DESCRIPTION","dataType":"string"},{"name":"LOCATION","dataType":"string"},{"name":"COMMENTS","dataType":"string"},{"name":"CREATION_DATE","dataType":"dateTime"},{"name":"CREATED_BY_LOGIN","dataType":"string"},{"name":"LAST_UPDATE_DATE","dataType":"dateTime"},{"name":"LAST_UPDATE_LOGIN","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-12T15:01:31.9463923+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/14fe25b9-fb78-4792-bddc-dc886c775fad/Entity%20Department%20Details.csv?snapshot=2022-06-12T15%3A01%3A30.3467788Z"}]}]}