{"name":"Flow_SPC_CR-Assembly","description":"Flow for SPC data of Cleanroom Assembly (Fab3).","version":"1.0","culture":"en-US","modifiedTime":"2022-03-31T15:11:08.1341849+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"CR SPC EMO":{"queryId":"a83786d7-9c35-4369-a3f5-55a201043a77","queryName":"CR SPC EMO","loadEnabled":true},"Sample file":{"queryId":"9d612193-a669-4ca6-90bf-622001eb49f0","queryName":"Sample file","queryGroupId":"4306fc91-406e-4bc5-97ae-bc94fcfaef13"},"Parameter":{"queryId":"cc45aa62-4939-40a5-b85f-a68d0797941b","queryName":"Parameter","queryGroupId":"4306fc91-406e-4bc5-97ae-bc94fcfaef13"},"Transform Sample file":{"queryId":"90aab0ba-c1f4-4581-9f2c-3871ea7648c8","queryName":"Transform Sample file","queryGroupId":"932982c1-2718-439e-8156-d37b0391a4a3"},"Transform file":{"queryId":"23ec1710-d9ad-47d8-afd7-e560e20c58bf","queryName":"Transform file","queryGroupId":"4306fc91-406e-4bc5-97ae-bc94fcfaef13"},"CR SPC CR5-6":{"queryId":"7908ec2a-438f-4699-ba4c-002ef708cdac","queryName":"CR SPC CR5-6","loadEnabled":true},"Sample file (2)":{"queryId":"eec19098-22e7-44b4-89e3-efb6e977f750","queryName":"Sample file (2)","queryGroupId":"add372f7-4ae4-44bd-abf7-59660d0d9d73"},"Parameter (2)":{"queryId":"422402c1-21ae-4c35-a3fb-a465c4c24bef","queryName":"Parameter (2)","queryGroupId":"add372f7-4ae4-44bd-abf7-59660d0d9d73"},"Transform Sample file (2)":{"queryId":"2c860b75-60d4-4e69-bbde-bcdb5b5eabf8","queryName":"Transform Sample file (2)","queryGroupId":"893d5acd-713c-41f1-b04c-bcdbb1ec97a6"},"Transform file (2)":{"queryId":"c992c000-7fe3-401e-b359-4e35cab89bae","queryName":"Transform file (2)","queryGroupId":"add372f7-4ae4-44bd-abf7-59660d0d9d73"},"CR SPC CR8-11":{"queryId":"fab570cf-0d76-4dcb-bbfb-5207b7d9a358","queryName":"CR SPC CR8-11","loadEnabled":true},"CR SPC CR12-14":{"queryId":"d56b7d58-6aea-4067-b22f-f51d750db1cc","queryName":"CR SPC CR12-14","loadEnabled":true},"CR SPC TA1":{"queryId":"e638bf07-94f6-4b10-8cbc-15fd283d8239","queryName":"CR SPC TA1","loadEnabled":true},"Sample file (3)":{"queryId":"757e10e3-1b95-4c5c-956d-0e79dfa36e88","queryName":"Sample file (3)","queryGroupId":"10c0e9b8-a612-4aef-96ba-66f40ec3950d"},"Parameter (3)":{"queryId":"995604f4-cd9c-4a56-a015-cafcbcef7694","queryName":"Parameter (3)","queryGroupId":"10c0e9b8-a612-4aef-96ba-66f40ec3950d"},"Transform Sample file (3)":{"queryId":"6a2ee67a-f47d-4f68-9625-9fbd05bd1ddb","queryName":"Transform Sample file (3)","queryGroupId":"e2aaa9ea-8bc7-48da-ac95-dc4d1e5ac915"},"Transform file (3)":{"queryId":"3690143b-d3ae-462b-b501-787e9a88e481","queryName":"Transform file (3)","queryGroupId":"10c0e9b8-a612-4aef-96ba-66f40ec3950d"},"Sample file (4)":{"queryId":"ffa1d83c-b3d4-4cd7-a9a4-572f9c92ec14","queryName":"Sample file (4)","queryGroupId":"af49ebb2-39d8-4485-a39e-7f156514d740"},"Parameter (4)":{"queryId":"382e7379-bb7f-4219-9a78-f84ddc34536a","queryName":"Parameter (4)","queryGroupId":"af49ebb2-39d8-4485-a39e-7f156514d740"},"Transform Sample file (4)":{"queryId":"e6692e59-a519-4f1b-8b71-4aad9a4e0939","queryName":"Transform Sample file (4)","queryGroupId":"390a9955-1efe-4074-bdc9-70ab5b6cb0f1"},"Transform file (4)":{"queryId":"760802bb-7f70-4e0a-be97-65584234feca","queryName":"Transform file (4)","queryGroupId":"af49ebb2-39d8-4485-a39e-7f156514d740"},"Sample file (5)":{"queryId":"5922c56f-a8ce-4d4f-b1ea-95ffa41c0f99","queryName":"Sample file (5)","queryGroupId":"7de56b56-0152-4cc1-8a44-7b668a1423c7"},"Parameter (5)":{"queryId":"9350e77d-8523-4c41-9708-88d58c44bb39","queryName":"Parameter (5)","queryGroupId":"7de56b56-0152-4cc1-8a44-7b668a1423c7"},"Transform Sample file (5)":{"queryId":"da8bb6ab-d8c2-494d-b58e-4e063631e068","queryName":"Transform Sample file (5)","queryGroupId":"f32968bc-2e77-41be-96e2-726638098ee5"},"Transform file (5)":{"queryId":"334bc096-2a19-4fbf-ad67-e137cec9ee41","queryName":"Transform file (5)","queryGroupId":"7de56b56-0152-4cc1-8a44-7b668a1423c7"},"CR SPC CR5-ReservoirSN":{"queryId":"6165609e-d112-4424-8c24-872a094dbb89","queryName":"CR SPC CR5-ReservoirSN","loadEnabled":true},"Sample file (6)":{"queryId":"3fc2231b-d18e-4427-949f-4107f57ef513","queryName":"Sample file (6)","queryGroupId":"e5873323-5f5d-4431-95e5-ed917ea71965"},"Parameter (6)":{"queryId":"105d5737-642f-4763-ba5d-ca7584bf2a60","queryName":"Parameter (6)","queryGroupId":"e5873323-5f5d-4431-95e5-ed917ea71965"},"Transform Sample file (6)":{"queryId":"d58e9a16-fca3-4bfe-afbb-875be083c94c","queryName":"Transform Sample file (6)","queryGroupId":"a5097507-3fe4-4e83-a938-d784e0cad4f0"},"Transform file (6)":{"queryId":"63d79970-bfdd-475c-8c89-34845ac02ebd","queryName":"Transform file (6)","queryGroupId":"e5873323-5f5d-4431-95e5-ed917ea71965"},"CR SPC CR5-ReservoirSN (2)":{"queryId":"49d9299c-56bc-4a83-abc4-633cbc8295d9","queryName":"CR SPC CR5-ReservoirSN (2)"}},"document":"section Section1;\r\nshared #\"CR SPC EMO\" = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Name] = \"VHP-CustomReportData-EMO_CustomReportDataResult.xlsx\" or [Name] = \"VHP-CustomReportData-EMO-KEP_CustomReportDataResult.xlsx\"),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows\", each [Attributes]?[Hidden]? <> true),\r\n  #\"Invoke custom function\" = Table.AddColumn(#\"Filtered hidden files\", \"Transform file\", each #\"Transform file\"([Content])),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Invoke custom function\", {{\"Name\", \"Source.Name\"}}),\r\n  #\"Removed other columns\" = Table.SelectColumns(#\"Renamed columns\", {\"Source.Name\", \"Transform file\"}),\r\n  #\"Expanded table column\" = Table.ExpandTableColumn(#\"Removed other columns\", \"Transform file\", Table.ColumnNames(#\"Transform file\"(#\"Sample file\"))),\r\n  #\"Filtered rows 1\" = Table.SelectRows(#\"Expanded table column\", each [WO_STATUS] = \"Closed\"),\r\n  #\"Choose columns\" = Table.SelectColumns(#\"Filtered rows 1\", {\"DATA_VALUE\", \"MEASUREMENT\", \"PART_NUMBER\", \"SERIAL_NUMBER\", \"WORK_ORDER\"}),\r\n  #\"Replaced value\" = Table.ReplaceValue(#\"Choose columns\", \"Wash Duration P1\", \"Wash Duration\", Replacer.ReplaceValue, {\"MEASUREMENT\"}),\r\n  #\"Replaced value 1\" = Table.ReplaceValue(#\"Replaced value\", \"Wash Duration P3\", \"Wash Duration\", Replacer.ReplaceValue, {\"MEASUREMENT\"}),\r\n  #\"Replaced value 2\" = Table.ReplaceValue(#\"Replaced value 1\", \"Wash Duration P5\", \"Wash Duration\", Replacer.ReplaceValue, {\"MEASUREMENT\"}),\r\n  #\"Pivoted column\" = Table.Pivot(Table.TransformColumnTypes(#\"Replaced value 2\", {{\"MEASUREMENT\", type text}}), List.Distinct(Table.TransformColumnTypes(#\"Replaced value 2\", {{\"MEASUREMENT\", type text}})[MEASUREMENT]), \"MEASUREMENT\", \"DATA_VALUE\"),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Pivoted column\", {{\"PART_NUMBER\", type text}, {\"SERIAL_NUMBER\", type text}, {\"WORK_ORDER\", type text}, {\"Select EMO Gep / Kep\", type text}, {\"Conductivity Cartridge 1 Input\", type number}, {\"Conductivity Cartridge 1 Output\", type number}, {\"Wash Duration\", type number}, {\"Ink Test\", type number}})\r\nin\r\n  #\"Changed column type\";\r\nshared #\"Sample file\" = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Name] = \"VHP-CustomReportData-EMO_CustomReportDataResult.xlsx\"),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows\", each [Attributes]?[Hidden]? <> true),\r\n  Navigation = #\"Filtered hidden files\"{0}[Content]\r\nin\r\n  Navigation;\r\nshared Parameter = let\r\n  Parameter = #\"Sample file\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type binary]\r\nin\r\n  Parameter;\r\nshared #\"Transform Sample file\" = let\r\n  Source = Excel.Workbook(Parameter, null, true),\r\n  Navigation = Source{[Item = \"CustomReportDataResult\", Kind = \"Sheet\"]}[Data],\r\n  #\"Promoted headers\" = Table.PromoteHeaders(Navigation, [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"CTL_LIMITS\", type text}, {\"DATA_TYPE\", type text}, {\"DATA_VALUE\", type text}, {\"DATE\", type text}, {\"DESCRIPTION\", type text}, {\"DEVIATIONS\", type any}, {\"FLOW\", type text}, {\"MEASUREMENT\", type text}, {\"PART_NUMBER\", type text}, {\"PASS_CTL\", type logical}, {\"PASS_SPEC\", type logical}, {\"PROCESS\", type text}, {\"PROCESS_DESCRIPTION\", type text}, {\"SERIAL_NUMBER\", type text}, {\"SPEC_LIMITS\", type text}, {\"UOM\", type text}, {\"WORK_ORDER\", type text}, {\"WO_NOTES\", type any}, {\"WO_STATUS\", type text}})\r\nin\r\n  #\"Changed column type\";\r\nshared #\"Transform file\" = let\r\n  Source = (Parameter as binary) => let\r\n  Source = Excel.Workbook(Parameter, null, true),\r\n  Navigation = Source{[Item = \"CustomReportDataResult\", Kind = \"Sheet\"]}[Data],\r\n  #\"Promoted headers\" = Table.PromoteHeaders(Navigation, [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"CTL_LIMITS\", type text}, {\"DATA_TYPE\", type text}, {\"DATA_VALUE\", type text}, {\"DATE\", type text}, {\"DESCRIPTION\", type text}, {\"DEVIATIONS\", type any}, {\"FLOW\", type text}, {\"MEASUREMENT\", type text}, {\"PART_NUMBER\", type text}, {\"PASS_CTL\", type logical}, {\"PASS_SPEC\", type logical}, {\"PROCESS\", type text}, {\"PROCESS_DESCRIPTION\", type text}, {\"SERIAL_NUMBER\", type text}, {\"SPEC_LIMITS\", type text}, {\"UOM\", type text}, {\"WORK_ORDER\", type text}, {\"WO_NOTES\", type any}, {\"WO_STATUS\", type text}})\r\nin\r\n  #\"Changed column type\"\r\nin\r\n  Source;\r\nshared #\"CR SPC CR5-6\" = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n  #\"Filtered rows 2\" = Table.SelectRows(Source, each Text.Contains([Name], \"CustomReportData-CR5-6\")),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows 2\", each [Attributes]?[Hidden]? <> true),\r\n  #\"Invoke custom function\" = Table.AddColumn(#\"Filtered hidden files\", \"Transform file (2)\", each #\"Transform file (2)\"([Content])),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Invoke custom function\", {{\"Name\", \"Source.Name\"}}),\r\n  #\"Removed other columns\" = Table.SelectColumns(#\"Renamed columns\", {\"Source.Name\", \"Transform file (2)\"}),\r\n  #\"Expanded table column\" = Table.ExpandTableColumn(#\"Removed other columns\", \"Transform file (2)\", Table.ColumnNames(#\"Transform file (2)\"(#\"Sample file (2)\"))),\r\n  #\"Filtered rows 1\" = Table.SelectRows(#\"Expanded table column\", each [WO_STATUS] <> \"Active\"),\r\n  #\"Choose columns\" = Table.SelectColumns(#\"Filtered rows 1\", {\"DATA_VALUE\", \"MEASUREMENT\", \"PART_NUMBER\", \"SERIAL_NUMBER\", \"WORK_ORDER\"}),\r\n  #\"Pivoted column\" = Table.Pivot(Table.TransformColumnTypes(#\"Choose columns\", {{\"MEASUREMENT\", type text}}), List.Distinct(Table.TransformColumnTypes(#\"Choose columns\", {{\"MEASUREMENT\", type text}})[MEASUREMENT]), \"MEASUREMENT\", \"DATA_VALUE\"),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Pivoted column\", {{\"PART_NUMBER\", type text}, {\"SERIAL_NUMBER\", type text}, {\"WORK_ORDER\", type text}, {\"Anode Supplier\", type text}, {\"Anode Coater\", type text}, {\"Anode Coating Thickness P2 S1 C\", Int64.Type}, {\"Anode Coating Thickness P1 S2 C\", Int64.Type}, {\"Anode Coating Thickness P2 S1 M\", Int64.Type}, {\"Anode Coating Thickness P1 S2 M\", Int64.Type}, {\"Anode Coating Thickness P1 S1 W\", Int64.Type}, {\"Anode Coating Thickness P1 S1 C\", Int64.Type}, {\"Anode Coating Thickness P1 S1 M\", Int64.Type}, {\"Anode Coating Thickness P1 S2 W\", Int64.Type}, {\"Anode Coating Thickness P2 S2 M\", Int64.Type}, {\"Anode Coating Thickness P2 S1 W\", Int64.Type}, {\"Anode Coating Thickness P2 S2 C\", Int64.Type}, {\"Anode Coating Thickness P2 S2 W\", Int64.Type}}),\r\n  #\"Changed column type 1\" = Table.TransformColumnTypes(#\"Changed column type\", {{\"Blasted Area Width A L\", type number}, {\"Anode Base Height C\", type number}, {\"Blasted Area Width A R\", type number}, {\"Anode Coating Thickness P2 S1 W\", type number}, {\"Blasted Area Width A CR\", type number}, {\"Blasted Area Width A CL\", type number}, {\"Anode Height C\", type number}}),\r\n  #\"Replaced errors\" = Table.ReplaceErrorValues(#\"Changed column type 1\", {{\"Anode Coating Thickness P2 S1 C\", 0}, {\"Anode Coating Thickness P1 S2 C\", 0}, {\"Anode Coating Thickness P2 S1 M\", 0}, {\"Anode Coating Thickness P1 S2 M\", 0}, {\"Anode Coating Thickness P1 S1 W\", 0}, {\"Anode Coating Thickness P1 S1 C\", 0}, {\"Anode Coating Thickness P1 S1 M\", 0}, {\"Blasted Area Width A L\", 0}, {\"Anode Coating Thickness P1 S2 W\", 0}, {\"Anode Coating Thickness P2 S2 M\", 0}, {\"Blasted Area Width A R\", 0}, {\"Blasted Area Width A CL\", 0}, {\"Anode Base Height C\", 0}, {\"Anode Coating Thickness P2 S1 W\", 0}, {\"Anode Height C\", 0}, {\"Anode Coating Thickness P2 S2 C\", 0}, {\"Anode Coating Thickness P2 S2 W\", 0}, {\"Blasted Area Width A CR\", 0}})\r\nin\r\n  #\"Replaced errors\";\r\nshared #\"Sample file (2)\" = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Name] = \"VHP-CustomReportData-CR5-6_CustomReportDataResult.xlsx\"),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows\", each [Attributes]?[Hidden]? <> true),\r\n  Navigation = #\"Filtered hidden files\"{0}[Content]\r\nin\r\n  Navigation;\r\nshared #\"Parameter (2)\" = let\r\n  #\"Parameter (2)\" = #\"Sample file (2)\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type binary]\r\nin\r\n  #\"Parameter (2)\";\r\nshared #\"Transform Sample file (2)\" = let\r\n  Source = Excel.Workbook(#\"Parameter (2)\", null, true),\r\n  Navigation = Source{[Item = \"CustomReportDataResult\", Kind = \"Sheet\"]}[Data],\r\n  #\"Promoted headers\" = Table.PromoteHeaders(Navigation, [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"CTL_LIMITS\", type text}, {\"DATA_TYPE\", type text}, {\"DATA_VALUE\", type text}, {\"DATE\", type text}, {\"DESCRIPTION\", type text}, {\"DEVIATIONS\", type text}, {\"FLOW\", type text}, {\"MEASUREMENT\", type text}, {\"PART_NUMBER\", type text}, {\"PASS_CTL\", type logical}, {\"PASS_SPEC\", type logical}, {\"PROCESS\", type text}, {\"PROCESS_DESCRIPTION\", type text}, {\"SERIAL_NUMBER\", type text}, {\"SPEC_LIMITS\", type text}, {\"UOM\", type text}, {\"WORK_ORDER\", Int64.Type}, {\"WO_NOTES\", type text}, {\"WO_STATUS\", type text}})\r\nin\r\n  #\"Changed column type\";\r\nshared #\"Transform file (2)\" = let\r\n  Source = (#\"Parameter (2)\" as binary) => let\r\n  Source = Excel.Workbook(#\"Parameter (2)\", null, true),\r\n  Navigation = Source{[Item = \"CustomReportDataResult\", Kind = \"Sheet\"]}[Data],\r\n  #\"Promoted headers\" = Table.PromoteHeaders(Navigation, [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"CTL_LIMITS\", type text}, {\"DATA_TYPE\", type text}, {\"DATA_VALUE\", type text}, {\"DATE\", type text}, {\"DESCRIPTION\", type text}, {\"DEVIATIONS\", type text}, {\"FLOW\", type text}, {\"MEASUREMENT\", type text}, {\"PART_NUMBER\", type text}, {\"PASS_CTL\", type logical}, {\"PASS_SPEC\", type logical}, {\"PROCESS\", type text}, {\"PROCESS_DESCRIPTION\", type text}, {\"SERIAL_NUMBER\", type text}, {\"SPEC_LIMITS\", type text}, {\"UOM\", type text}, {\"WORK_ORDER\", Int64.Type}, {\"WO_NOTES\", type text}, {\"WO_STATUS\", type text}})\r\nin\r\n  #\"Changed column type\"\r\nin\r\n  Source;\r\nshared #\"CR SPC CR8-11\" = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n  #\"Filtered rows 2\" = Table.SelectRows(Source, each Text.Contains([Name], \"CustomReportData-CR8\")),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows 2\", each [Attributes]?[Hidden]? <> true),\r\n  #\"Invoke custom function\" = Table.AddColumn(#\"Filtered hidden files\", \"Transform file (3)\", each #\"Transform file (3)\"([Content])),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Invoke custom function\", {{\"Name\", \"Source.Name\"}}),\r\n  #\"Removed other columns\" = Table.SelectColumns(#\"Renamed columns\", {\"Source.Name\", \"Transform file (3)\"}),\r\n  #\"Expanded table column\" = Table.ExpandTableColumn(#\"Removed other columns\", \"Transform file (3)\", Table.ColumnNames(#\"Transform file (3)\"(#\"Sample file (3)\"))),\r\n  #\"Filtered rows 1\" = Table.SelectRows(#\"Expanded table column\", each [WO_STATUS] <> \"Active\"),\r\n  #\"Choose columns\" = Table.SelectColumns(#\"Filtered rows 1\", {\"DATA_VALUE\", \"MEASUREMENT\", \"PART_NUMBER\", \"SERIAL_NUMBER\", \"WORK_ORDER\"}),\r\n  #\"Pivoted column\" = Table.Pivot(Table.TransformColumnTypes(#\"Choose columns\", {{\"MEASUREMENT\", type text}}), List.Distinct(Table.TransformColumnTypes(#\"Choose columns\", {{\"MEASUREMENT\", type text}})[MEASUREMENT]), \"MEASUREMENT\", \"DATA_VALUE\"),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Pivoted column\", {{\"PART_NUMBER\", type text}, {\"SERIAL_NUMBER\", type text}, {\"WORK_ORDER\", type text}, {\"Cathode Supplier\", type text}, {\"Electrode Plate Assembling\", type text}, {\"Electrode Distance\", type number}, {\"Electrode Distance W\", type number}, {\"Blasted Area Width C CR\", type number}, {\"Blasted Area Width C CL\", type number}, {\"Electrode Distance C\", type number}, {\"Electrode Distance M\", type number}, {\"Cathode Base Height C\", type number}, {\"Cathode Height C\", type number}, {\"Blasted Area Width C L\", type number}, {\"Blasted Area Width C R\", type number}, {\"Tube Pack Position M\", type number}, {\"Extension Gap M\", type number}, {\"Tube Pack Position W\", type number}, {\"Extension Gap W\", type number}}),\r\n  #\"Replaced errors\" = Table.ReplaceErrorValues(#\"Changed column type\", {{\"Blasted Area Width C L\", 0}, {\"Blasted Area Width C CL\", 0}, {\"Blasted Area Width C CR\", 0}, {\"Blasted Area Width C R\", 0}})\r\nin\r\n  #\"Replaced errors\";\r\nshared #\"CR SPC CR12-14\" = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n  #\"Filtered rows 2\" = Table.SelectRows(Source, each Text.Contains([Name], \"CustomReportData-CR12-14\")),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows 2\", each [Attributes]?[Hidden]? <> true),\r\n  #\"Invoke custom function\" = Table.AddColumn(#\"Filtered hidden files\", \"Transform file (4)\", each #\"Transform file (4)\"([Content])),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Invoke custom function\", {{\"Name\", \"Source.Name\"}}),\r\n  #\"Removed other columns\" = Table.SelectColumns(#\"Renamed columns\", {\"Source.Name\", \"Transform file (4)\"}),\r\n  #\"Expanded table column\" = Table.ExpandTableColumn(#\"Removed other columns\", \"Transform file (4)\", Table.ColumnNames(#\"Transform file (4)\"(#\"Sample file (4)\"))),\r\n  #\"Filtered rows 1\" = Table.SelectRows(#\"Expanded table column\", each [WO_STATUS] <> \"Active\"),\r\n  #\"Choose columns\" = Table.SelectColumns(#\"Filtered rows 1\", {\"DATA_VALUE\", \"MEASUREMENT\", \"PART_NUMBER\", \"SERIAL_NUMBER\", \"WORK_ORDER\"}),\r\n  #\"Trimmed text\" = Table.TransformColumns(#\"Choose columns\", {{\"MEASUREMENT\", each Text.Trim(Text.From(_)), type text}}),\r\n  #\"Pivoted column\" = Table.Pivot(Table.TransformColumnTypes(#\"Trimmed text\", {{\"MEASUREMENT\", type text}}), List.Distinct(Table.TransformColumnTypes(#\"Trimmed text\", {{\"MEASUREMENT\", type text}})[MEASUREMENT]), \"MEASUREMENT\", \"DATA_VALUE\"),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Pivoted column\", {{\"PART_NUMBER\", type text}, {\"SERIAL_NUMBER\", type text}, {\"WORK_ORDER\", type text}, {\"Applied He Gas Pressure for Leaktest\", Int64.Type}, {\"Comp Leak Rate Cooling Tube\", type number}, {\"Comp Leak Rate Frame W Down\", type number}, {\"Comp Leak Rate Frame M Down\", type number}, {\"Comp Leak Rate HV Feedthrough M\", type number}, {\"Comp Leak Rate Preionization Pin\", type number}, {\"Comp Leak Rate Pressure Sensor\", type number}, {\"Comp Leak Rate Window Slide W\", type number}, {\"Comp Leak Rate Window Slide M\", type number}, {\"Comp Leak Rate Baffle W Down\", type number}, {\"Comp Leak Rate Flex Tube W\", type number}, {\"Comp Leak Rate Frame M Top\", type number}, {\"Comp Leak Rate Frame W Top\", type number}, {\"Comp Leak Rate Optic M\", type number}, {\"Comp Leak Rate Optic W\", type number}, {\"Comp Leak Rate Reservoir\", type number}, {\"Comp Leak Rate Flex Tube M\", type number}, {\"Comp Leak Rate Baffle W Top\", type number}, {\"Comp Leak Rate Baffle M Down\", type number}, {\"Comp Leak Rate HV Feedthrough W\", type number}, {\"Tube Pressure Limit\", type number}, {\"Leak Rate Background\", type number}, {\"Comp Leak Rate Baffle M Top\", type number}, {\"Leak Rate Integral\", type number}, {\"Comp Leak Rate Window Slide W Drawn\", type number}, {\"Comp Leak Rate Window Slide M Drawn\", type number}, {\"Overpressure Test Passed?\", type text}}),\r\n  #\"Replaced errors\" = Table.ReplaceErrorValues(#\"Changed column type\", {{\"Comp Leak Rate HV Feedthrough W\", 0}, {\"Tube Pressure Limit\", 0}, {\"Applied He Gas Pressure for Leaktest\", 0}, {\"Leak Rate Background\", 0}, {\"Comp Leak Rate Baffle M Top\", 0}, {\"Comp Leak Rate Baffle W Top\", 0}, {\"Comp Leak Rate Baffle M Down\", 0}, {\"Comp Leak Rate Baffle W Down\", 0}, {\"Comp Leak Rate Window Slide M\", 0}, {\"Comp Leak Rate Window Slide W\", 0}, {\"Comp Leak Rate Flex Tube M\", 0}, {\"Comp Leak Rate Flex Tube W\", 0}, {\"Comp Leak Rate Frame M Top\", 0}, {\"Comp Leak Rate Frame W Top\", 0}, {\"Comp Leak Rate Frame W Down\", 0}, {\"Comp Leak Rate Optic M\", 0}, {\"Comp Leak Rate Optic W\", 0}, {\"Comp Leak Rate Cooling Tube\", 0}, {\"Comp Leak Rate Reservoir\", 0}, {\"Comp Leak Rate Pressure Sensor\", 0}, {\"Comp Leak Rate Preionization Pin\", 0}, {\"Comp Leak Rate Frame M Down\", 0}, {\"Comp Leak Rate Window Slide M Drawn\", 0}, {\"Comp Leak Rate Window Slide W Drawn\", 0}, {\"Leak Rate Integral\", 0}}),\r\n  #\"Replaced value\" = Table.ReplaceValue(#\"Replaced errors\", null, \"None\", Replacer.ReplaceValue, {\"Overpressure Test Passed?\"})\r\nin\r\n  #\"Replaced value\";\r\nshared #\"CR SPC TA1\" = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n  #\"Filtered rows 2\" = Table.SelectRows(Source, each Text.Contains([Name], \"CustomReportData-TA1\")),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows 2\", each [Attributes]?[Hidden]? <> true),\r\n  #\"Invoke custom function\" = Table.AddColumn(#\"Filtered hidden files\", \"Transform file (5)\", each #\"Transform file (5)\"([Content])),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Invoke custom function\", {{\"Name\", \"Source.Name\"}}),\r\n  #\"Removed other columns\" = Table.SelectColumns(#\"Renamed columns\", {\"Source.Name\", \"Transform file (5)\"}),\r\n  #\"Expanded table column\" = Table.ExpandTableColumn(#\"Removed other columns\", \"Transform file (5)\", Table.ColumnNames(#\"Transform file (5)\"(#\"Sample file (5)\"))),\r\n  #\"Filtered rows 1\" = Table.SelectRows(#\"Expanded table column\", each [WO_STATUS] <> \"Active\"),\r\n  #\"Choose columns\" = Table.SelectColumns(#\"Filtered rows 1\", {\"DATA_VALUE\", \"MEASUREMENT\", \"PART_NUMBER\", \"SERIAL_NUMBER\", \"WORK_ORDER\"}),\r\n  #\"Trimmed text\" = Table.TransformColumns(#\"Choose columns\", {{\"MEASUREMENT\", each Text.Trim(Text.From(_)), type text}}),\r\n  #\"Pivoted column\" = Table.Pivot(Table.TransformColumnTypes(#\"Trimmed text\", {{\"MEASUREMENT\", type text}}), List.Distinct(Table.TransformColumnTypes(#\"Trimmed text\", {{\"MEASUREMENT\", type text}})[MEASUREMENT]), \"MEASUREMENT\", \"DATA_VALUE\"),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Pivoted column\", {{\"PART_NUMBER\", type text}, {\"SERIAL_NUMBER\", type text}, {\"WORK_ORDER\", type text}, {\"Capacitor Bank  NEW or REFURB\", type text}, {\"Connection Sheet Checked and Mounted\", type text}, {\"Resistor M\", type number}, {\"Resistor W\", type number}, {\"Peaking Capacity D\", type number}, {\"Peaking Capacity G\", type number}, {\"Water Leaktest Duration\", type number}, {\"Coil M\", type number}, {\"Water Pressure Drop\", type number}, {\"Room Temperature\", type number}, {\"Coil W\", type number}, {\"Batch Number\", type text}}),\r\n  #\"Renamed columns 1\" = Table.RenameColumns(#\"Changed column type\", {{\"Batch Number\", \"Peakings Batch Number\"}})\r\nin\r\n  #\"Renamed columns 1\";\r\nshared #\"Sample file (3)\" = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Name] = \"VHP-CustomReportData-CR8-11_CustomReportDataResult.xlsx\"),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows\", each [Attributes]?[Hidden]? <> true),\r\n  Navigation = #\"Filtered hidden files\"{0}[Content]\r\nin\r\n  Navigation;\r\nshared #\"Parameter (3)\" = let\r\n  #\"Parameter (3)\" = #\"Sample file (3)\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type binary]\r\nin\r\n  #\"Parameter (3)\";\r\nshared #\"Transform Sample file (3)\" = let\r\n  Source = Excel.Workbook(#\"Parameter (3)\", null, true),\r\n  Navigation = Source{[Item = \"CustomReportDataResult\", Kind = \"Sheet\"]}[Data],\r\n  #\"Promoted headers\" = Table.PromoteHeaders(Navigation, [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"CTL_LIMITS\", type any}, {\"DATA_TYPE\", type text}, {\"DATA_VALUE\", type text}, {\"DATE\", type text}, {\"DESCRIPTION\", type text}, {\"DEVIATIONS\", type text}, {\"FLOW\", type text}, {\"MEASUREMENT\", type text}, {\"PART_NUMBER\", type text}, {\"PASS_CTL\", type logical}, {\"PASS_SPEC\", type logical}, {\"PROCESS\", type text}, {\"PROCESS_DESCRIPTION\", type text}, {\"SERIAL_NUMBER\", type text}, {\"SPEC_LIMITS\", type text}, {\"UOM\", type text}, {\"WORK_ORDER\", Int64.Type}, {\"WO_NOTES\", type text}, {\"WO_STATUS\", type text}})\r\nin\r\n  #\"Changed column type\";\r\nshared #\"Transform file (3)\" = let\r\n  Source = (#\"Parameter (3)\" as binary) => let\r\n  Source = Excel.Workbook(#\"Parameter (3)\", null, true),\r\n  Navigation = Source{[Item = \"CustomReportDataResult\", Kind = \"Sheet\"]}[Data],\r\n  #\"Promoted headers\" = Table.PromoteHeaders(Navigation, [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"CTL_LIMITS\", type any}, {\"DATA_TYPE\", type text}, {\"DATA_VALUE\", type text}, {\"DATE\", type text}, {\"DESCRIPTION\", type text}, {\"DEVIATIONS\", type text}, {\"FLOW\", type text}, {\"MEASUREMENT\", type text}, {\"PART_NUMBER\", type text}, {\"PASS_CTL\", type logical}, {\"PASS_SPEC\", type logical}, {\"PROCESS\", type text}, {\"PROCESS_DESCRIPTION\", type text}, {\"SERIAL_NUMBER\", type text}, {\"SPEC_LIMITS\", type text}, {\"UOM\", type text}, {\"WORK_ORDER\", Int64.Type}, {\"WO_NOTES\", type text}, {\"WO_STATUS\", type text}})\r\nin\r\n  #\"Changed column type\"\r\nin\r\n  Source;\r\nshared #\"Sample file (4)\" = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Name] = \"VHP-CustomReportData-CR12-14_CustomReportDataResult.xlsx\"),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows\", each [Attributes]?[Hidden]? <> true),\r\n  Navigation = #\"Filtered hidden files\"{0}[Content]\r\nin\r\n  Navigation;\r\nshared #\"Parameter (4)\" = let\r\n  #\"Parameter (4)\" = #\"Sample file (4)\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type binary]\r\nin\r\n  #\"Parameter (4)\";\r\nshared #\"Transform Sample file (4)\" = let\r\n  Source = Excel.Workbook(#\"Parameter (4)\", null, true),\r\n  Navigation = Source{[Item = \"CustomReportDataResult\", Kind = \"Sheet\"]}[Data],\r\n  #\"Promoted headers\" = Table.PromoteHeaders(Navigation, [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"CTL_LIMITS\", type text}, {\"DATA_TYPE\", type text}, {\"DATA_VALUE\", type text}, {\"DATE\", type text}, {\"DESCRIPTION\", type text}, {\"DEVIATIONS\", type text}, {\"FLOW\", type text}, {\"MEASUREMENT\", type text}, {\"PART_NUMBER\", type text}, {\"PASS_CTL\", type logical}, {\"PASS_SPEC\", type logical}, {\"PROCESS\", type text}, {\"PROCESS_DESCRIPTION\", type text}, {\"SERIAL_NUMBER\", type text}, {\"SPEC_LIMITS\", type text}, {\"UOM\", type text}, {\"WORK_ORDER\", Int64.Type}, {\"WO_NOTES\", type text}, {\"WO_STATUS\", type text}})\r\nin\r\n  #\"Changed column type\";\r\nshared #\"Transform file (4)\" = let\r\n  Source = (#\"Parameter (4)\" as binary) => let\r\n  Source = Excel.Workbook(#\"Parameter (4)\", null, true),\r\n  Navigation = Source{[Item = \"CustomReportDataResult\", Kind = \"Sheet\"]}[Data],\r\n  #\"Promoted headers\" = Table.PromoteHeaders(Navigation, [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"CTL_LIMITS\", type text}, {\"DATA_TYPE\", type text}, {\"DATA_VALUE\", type text}, {\"DATE\", type text}, {\"DESCRIPTION\", type text}, {\"DEVIATIONS\", type text}, {\"FLOW\", type text}, {\"MEASUREMENT\", type text}, {\"PART_NUMBER\", type text}, {\"PASS_CTL\", type logical}, {\"PASS_SPEC\", type logical}, {\"PROCESS\", type text}, {\"PROCESS_DESCRIPTION\", type text}, {\"SERIAL_NUMBER\", type text}, {\"SPEC_LIMITS\", type text}, {\"UOM\", type text}, {\"WORK_ORDER\", Int64.Type}, {\"WO_NOTES\", type text}, {\"WO_STATUS\", type text}})\r\nin\r\n  #\"Changed column type\"\r\nin\r\n  Source;\r\nshared #\"Sample file (5)\" = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Name] = \"VHP-CustomReportData-TA1_CustomReportDataResult.xlsx\"),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows\", each [Attributes]?[Hidden]? <> true),\r\n  Navigation = #\"Filtered hidden files\"{0}[Content]\r\nin\r\n  Navigation;\r\nshared #\"Parameter (5)\" = let\r\n  #\"Parameter (5)\" = #\"Sample file (5)\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type binary]\r\nin\r\n  #\"Parameter (5)\";\r\nshared #\"Transform Sample file (5)\" = let\r\n  Source = Excel.Workbook(#\"Parameter (5)\", null, true),\r\n  Navigation = Source{[Item = \"CustomReportDataResult\", Kind = \"Sheet\"]}[Data],\r\n  #\"Promoted headers\" = Table.PromoteHeaders(Navigation, [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"CTL_LIMITS\", type text}, {\"DATA_TYPE\", type text}, {\"DATA_VALUE\", type text}, {\"DATE\", type text}, {\"DESCRIPTION\", type text}, {\"DEVIATIONS\", type text}, {\"FLOW\", type text}, {\"MEASUREMENT\", type text}, {\"PART_NUMBER\", type text}, {\"PASS_CTL\", type logical}, {\"PASS_SPEC\", type logical}, {\"PROCESS\", type text}, {\"PROCESS_DESCRIPTION\", type text}, {\"SERIAL_NUMBER\", type text}, {\"SPEC_LIMITS\", type text}, {\"UOM\", type text}, {\"WORK_ORDER\", Int64.Type}, {\"WO_NOTES\", type text}, {\"WO_STATUS\", type text}})\r\nin\r\n  #\"Changed column type\";\r\nshared #\"Transform file (5)\" = let\r\n  Source = (#\"Parameter (5)\" as binary) => let\r\n  Source = Excel.Workbook(#\"Parameter (5)\", null, true),\r\n  Navigation = Source{[Item = \"CustomReportDataResult\", Kind = \"Sheet\"]}[Data],\r\n  #\"Promoted headers\" = Table.PromoteHeaders(Navigation, [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"CTL_LIMITS\", type text}, {\"DATA_TYPE\", type text}, {\"DATA_VALUE\", type text}, {\"DATE\", type text}, {\"DESCRIPTION\", type text}, {\"DEVIATIONS\", type text}, {\"FLOW\", type text}, {\"MEASUREMENT\", type text}, {\"PART_NUMBER\", type text}, {\"PASS_CTL\", type logical}, {\"PASS_SPEC\", type logical}, {\"PROCESS\", type text}, {\"PROCESS_DESCRIPTION\", type text}, {\"SERIAL_NUMBER\", type text}, {\"SPEC_LIMITS\", type text}, {\"UOM\", type text}, {\"WORK_ORDER\", Int64.Type}, {\"WO_NOTES\", type text}, {\"WO_STATUS\", type text}})\r\nin\r\n  #\"Changed column type\"\r\nin\r\n  Source;\r\nshared #\"CR SPC CR5-ReservoirSN\" = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Extension] = \".xlsx\"),\r\n  #\"Filtered rows 1\" = Table.SelectRows(#\"Filtered rows\", each Text.Contains([Name], \"CustomReportData_CR5-ReservoirSN\")),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows 1\", each [Attributes]?[Hidden]? <> true),\r\n  #\"Invoke custom function\" = Table.AddColumn(#\"Filtered hidden files\", \"Transform file (6)\", each #\"Transform file (6)\"([Content])),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Invoke custom function\", {{\"Name\", \"Source.Name\"}}),\r\n  #\"Removed other columns\" = Table.SelectColumns(#\"Renamed columns\", {\"Source.Name\", \"Transform file (6)\"}),\r\n  #\"Expanded table column\" = Table.ExpandTableColumn(#\"Removed other columns\", \"Transform file (6)\", Table.ColumnNames(#\"Transform file (6)\"(#\"Sample file (6)\"))),\r\n  #\"Filtered rows 3\" = Table.SelectRows(#\"Expanded table column\", each [WO_STATUS] <> \"Active\"),\r\n  #\"Choose columns\" = Table.SelectColumns(#\"Filtered rows 3\", {\"WORK_ORDER\", \"WO_STATUS\", \"SERIAL_NUMBER\", \"PART_NUMBER\", \"FLOW\", \"MEASUREMENT\", \"DATE\", \"DATA_VALUE\"}),\r\n  #\"Extracted text before delimiter\" = Table.TransformColumns(#\"Choose columns\", {{\"DATE\", each Text.BeforeDelimiter(Text.From(_), \" \", 0), type text}}),\r\n  #\"Filtered rows 4\" = Table.SelectRows(#\"Extracted text before delimiter\", each [MEASUREMENT] = \"Reservoir SN\"),\r\n  #\"Pivoted column\" = Table.Pivot(Table.TransformColumnTypes(#\"Filtered rows 4\", {{\"MEASUREMENT\", type text}}), List.Distinct(Table.TransformColumnTypes(#\"Filtered rows 4\", {{\"MEASUREMENT\", type text}})[MEASUREMENT]), \"MEASUREMENT\", \"DATA_VALUE\"),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Pivoted column\", {{\"WORK_ORDER\", type text}, {\"WO_STATUS\", type text}, {\"SERIAL_NUMBER\", type text}, {\"PART_NUMBER\", type text}, {\"Reservoir SN\", type text}, {\"FLOW\", type text}}),\r\n  #\"Changed column type with locale\" = Table.TransformColumnTypes(#\"Changed column type\", {{\"DATE\", type date}}, \"de-DE\"),\r\n  #\"Replaced value 1\" = Table.ReplaceValue(#\"Changed column type with locale\", null, \"Empty\", Replacer.ReplaceValue, {\"Reservoir SN\"}),\r\n  #\"Filtered rows 2\" = Table.SelectRows(#\"Replaced value 1\", each [FLOW] <> \"Tube Service Repair\"),\r\n  #\"Merged queries\" = Table.NestedJoin(#\"Filtered rows 2\", {\"WORK_ORDER\"}, #\"CR SPC CR5-ReservoirSN (2)\", {\"WORK_ORDER\"}, \"CR SPC CR5-ReservoirSN (2)\", JoinKind.LeftOuter),\r\n  #\"Expanded CR SPC CR5-ReservoirSN (2)\" = Table.ExpandTableColumn(#\"Merged queries\", \"CR SPC CR5-ReservoirSN (2)\", {\"Reservoir Condition\", \"Reservoir Batch\"}, {\"Reservoir Condition\", \"Reservoir Batch\"}),\r\n  #\"Removed duplicates\" = Table.Distinct(#\"Expanded CR SPC CR5-ReservoirSN (2)\", {\"WORK_ORDER\"})\r\nin\r\n  #\"Removed duplicates\";\r\nshared #\"Sample file (6)\" = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Extension] = \".xlsx\"),\r\n  #\"Filtered rows 1\" = Table.SelectRows(#\"Filtered rows\", each Text.Contains([Name], \"CustomReportData_CR5-ReservoirSN\")),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows 1\", each [Attributes]?[Hidden]? <> true),\r\n  Navigation = #\"Filtered hidden files\"{0}[Content]\r\nin\r\n  Navigation;\r\nshared #\"Parameter (6)\" = let\r\n  #\"Parameter (6)\" = #\"Sample file (6)\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type binary, BinaryIdentifier = #\"Sample file (6)\"]\r\nin\r\n  #\"Parameter (6)\";\r\nshared #\"Transform Sample file (6)\" = let\r\n  Source = Excel.Workbook(#\"Parameter (6)\", null, true),\r\n  Navigation = Source{[Item = \"CustomReportDataResult\", Kind = \"Sheet\"]}[Data],\r\n  #\"Promoted headers\" = Table.PromoteHeaders(Navigation, [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"WORK_ORDER\", Int64.Type}, {\"WO_STATUS\", type text}, {\"SERIAL_NUMBER\", type text}, {\"PART_NUMBER\", type text}, {\"DESCRIPTION\", type text}, {\"FLOW\", type text}, {\"PROCESS\", type text}, {\"PROCESS_DESCRIPTION\", type text}, {\"MEASUREMENT\", type text}, {\"DATA_TYPE\", type text}, {\"UOM\", type any}, {\"DATE\", type text}, {\"DATA_VALUE\", type text}, {\"PASS_SPEC\", type logical}, {\"PASS_CTL\", type logical}, {\"SPEC_LIMITS\", type any}, {\"CTL_LIMITS\", type any}, {\"WO_NOTES\", type text}, {\"DEVIATIONS\", type text}, {\"FLOW_STEP_DESC\", type any}})\r\nin\r\n  #\"Changed column type\";\r\nshared #\"Transform file (6)\" = let\r\n  Source = (#\"Parameter (6)\" as binary) => let\r\n  Source = Excel.Workbook(#\"Parameter (6)\", null, true),\r\n  Navigation = Source{[Item = \"CustomReportDataResult\", Kind = \"Sheet\"]}[Data],\r\n  #\"Promoted headers\" = Table.PromoteHeaders(Navigation, [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"WORK_ORDER\", Int64.Type}, {\"WO_STATUS\", type text}, {\"SERIAL_NUMBER\", type text}, {\"PART_NUMBER\", type text}, {\"DESCRIPTION\", type text}, {\"FLOW\", type text}, {\"PROCESS\", type text}, {\"PROCESS_DESCRIPTION\", type text}, {\"MEASUREMENT\", type text}, {\"DATA_TYPE\", type text}, {\"UOM\", type any}, {\"DATE\", type text}, {\"DATA_VALUE\", type text}, {\"PASS_SPEC\", type logical}, {\"PASS_CTL\", type logical}, {\"SPEC_LIMITS\", type any}, {\"CTL_LIMITS\", type any}, {\"WO_NOTES\", type text}, {\"DEVIATIONS\", type text}, {\"FLOW_STEP_DESC\", type any}})\r\nin\r\n  #\"Changed column type\"\r\nin\r\n  Source;\r\nshared #\"CR SPC CR5-ReservoirSN (2)\" = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Extension] = \".xlsx\"),\r\n  #\"Filtered rows 1\" = Table.SelectRows(#\"Filtered rows\", each Text.Contains([Name], \"CustomReportData_CR5-ReservoirSN\")),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows 1\", each [Attributes]?[Hidden]? <> true),\r\n  #\"Invoke custom function\" = Table.AddColumn(#\"Filtered hidden files\", \"Transform file (6)\", each #\"Transform file (6)\"([Content])),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Invoke custom function\", {{\"Name\", \"Source.Name\"}}),\r\n  #\"Removed other columns\" = Table.SelectColumns(#\"Renamed columns\", {\"Source.Name\", \"Transform file (6)\"}),\r\n  #\"Expanded table column\" = Table.ExpandTableColumn(#\"Removed other columns\", \"Transform file (6)\", Table.ColumnNames(#\"Transform file (6)\"(#\"Sample file (6)\"))),\r\n  #\"Filtered rows 3\" = Table.SelectRows(#\"Expanded table column\", each [WO_STATUS] <> \"Active\"),\r\n  #\"Choose columns\" = Table.SelectColumns(#\"Filtered rows 3\", {\"WORK_ORDER\", \"WO_STATUS\", \"SERIAL_NUMBER\", \"PART_NUMBER\", \"FLOW\", \"MEASUREMENT\", \"DATA_VALUE\"}),\r\n  #\"Filtered rows 4\" = Table.SelectRows(#\"Choose columns\", each [MEASUREMENT] <> \"Reservoir SN\"),\r\n  #\"Pivoted column\" = Table.Pivot(Table.TransformColumnTypes(#\"Filtered rows 4\", {{\"MEASUREMENT\", type text}}), List.Distinct(Table.TransformColumnTypes(#\"Filtered rows 4\", {{\"MEASUREMENT\", type text}})[MEASUREMENT]), \"MEASUREMENT\", \"DATA_VALUE\"),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Pivoted column\", {{\"WORK_ORDER\", type text}, {\"WO_STATUS\", type text}, {\"SERIAL_NUMBER\", type text}, {\"PART_NUMBER\", type text}, {\"Reservoir Condition\", type text}, {\"Reservoir Batch\", type text}, {\"FLOW\", type text}}),\r\n  #\"Replaced value\" = Table.ReplaceValue(#\"Changed column type\", null, \"Unknown\", Replacer.ReplaceValue, {\"Reservoir Condition\"}),\r\n  #\"Replaced value 1\" = Table.ReplaceValue(#\"Replaced value\", null, \"Empty\", Replacer.ReplaceValue, {\"Reservoir Batch\"}),\r\n  #\"Filtered rows 2\" = Table.SelectRows(#\"Replaced value 1\", each [FLOW] <> \"Tube Service Repair\")\r\nin\r\n  #\"Filtered rows 2\";\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[{\"id\":\"932982c1-2718-439e-8156-d37b0391a4a3\",\"name\":\"Transform file from CR SPC EMO\",\"description\":null,\"parentId\":null,\"order\":0},{\"id\":\"4306fc91-406e-4bc5-97ae-bc94fcfaef13\",\"name\":\"Helper queries\",\"description\":null,\"parentId\":\"932982c1-2718-439e-8156-d37b0391a4a3\",\"order\":0},{\"id\":\"893d5acd-713c-41f1-b04c-bcdbb1ec97a6\",\"name\":\"Transform file from CR SPC CR5-6\",\"description\":null,\"parentId\":null,\"order\":0},{\"id\":\"add372f7-4ae4-44bd-abf7-59660d0d9d73\",\"name\":\"Helper queries (2)\",\"description\":null,\"parentId\":\"893d5acd-713c-41f1-b04c-bcdbb1ec97a6\",\"order\":0},{\"id\":\"e2aaa9ea-8bc7-48da-ac95-dc4d1e5ac915\",\"name\":\"Transform file from CR SPC CR8-11\",\"description\":null,\"parentId\":null,\"order\":1},{\"id\":\"10c0e9b8-a612-4aef-96ba-66f40ec3950d\",\"name\":\"Helper queries (3)\",\"description\":null,\"parentId\":\"e2aaa9ea-8bc7-48da-ac95-dc4d1e5ac915\",\"order\":0},{\"id\":\"390a9955-1efe-4074-bdc9-70ab5b6cb0f1\",\"name\":\"Transform file from CR SPC CR12-14\",\"description\":null,\"parentId\":null,\"order\":2},{\"id\":\"af49ebb2-39d8-4485-a39e-7f156514d740\",\"name\":\"Helper queries (4)\",\"description\":null,\"parentId\":\"390a9955-1efe-4074-bdc9-70ab5b6cb0f1\",\"order\":0},{\"id\":\"f32968bc-2e77-41be-96e2-726638098ee5\",\"name\":\"Transform file from CR SPC TA1\",\"description\":null,\"parentId\":null,\"order\":3},{\"id\":\"7de56b56-0152-4cc1-8a44-7b668a1423c7\",\"name\":\"Helper queries (5)\",\"description\":null,\"parentId\":\"f32968bc-2e77-41be-96e2-726638098ee5\",\"order\":0},{\"id\":\"a5097507-3fe4-4e83-a938-d784e0cad4f0\",\"name\":\"Transform file from CR SPC CR5-ReservoirSN\",\"description\":null,\"parentId\":null,\"order\":0},{\"id\":\"e5873323-5f5d-4431-95e5-ed917ea71965\",\"name\":\"Helper queries (6)\",\"description\":null,\"parentId\":\"a5097507-3fe4-4e83-a938-d784e0cad4f0\",\"order\":0}]"}],"entities":[{"$type":"LocalEntity","name":"CR SPC EMO","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"CR%20SPC%20EMO.csv"},"attributes":[{"name":"PART_NUMBER","dataType":"string"},{"name":"SERIAL_NUMBER","dataType":"string"},{"name":"WORK_ORDER","dataType":"string"},{"name":"Wash Duration","dataType":"double"},{"name":"Conductivity Cartridge 1 Input","dataType":"double"},{"name":"Conductivity Cartridge 1 Output","dataType":"double"},{"name":"Ink Test","dataType":"double"},{"name":"Select EMO Gep / Kep","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-20T03:00:34.3602152+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/2acbdeec-dcdb-4fdd-bedd-bdc7d79202b2/CR%20SPC%20EMO.csv?snapshot=2022-05-20T03%3A00%3A34.3039055Z"}]},{"$type":"LocalEntity","name":"CR SPC CR5-6","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"CR%20SPC%20CR5-6.csv"},"attributes":[{"name":"PART_NUMBER","dataType":"string"},{"name":"SERIAL_NUMBER","dataType":"string"},{"name":"WORK_ORDER","dataType":"string"},{"name":"Anode Coating Thickness P2 S1 C","dataType":"int64"},{"name":"Anode Coating Thickness P1 S2 C","dataType":"int64"},{"name":"Anode Coating Thickness P2 S1 M","dataType":"int64"},{"name":"Anode Coating Thickness P1 S2 M","dataType":"int64"},{"name":"Anode Coating Thickness P1 S1 W","dataType":"int64"},{"name":"Anode Coating Thickness P1 S1 C","dataType":"int64"},{"name":"Anode Coating Thickness P1 S1 M","dataType":"int64"},{"name":"Blasted Area Width A L","dataType":"double"},{"name":"Anode Coating Thickness P1 S2 W","dataType":"int64"},{"name":"Anode Coating Thickness P2 S2 M","dataType":"int64"},{"name":"Blasted Area Width A R","dataType":"double"},{"name":"Blasted Area Width A CL","dataType":"double"},{"name":"Anode Base Height C","dataType":"double"},{"name":"Anode Coating Thickness P2 S1 W","dataType":"double"},{"name":"Anode Coater","dataType":"string"},{"name":"Anode Supplier","dataType":"string"},{"name":"Anode Height C","dataType":"double"},{"name":"Anode Coating Thickness P2 S2 C","dataType":"int64"},{"name":"Anode Coating Thickness P2 S2 W","dataType":"int64"},{"name":"Blasted Area Width A CR","dataType":"double"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-20T03:01:36.3340601+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/2acbdeec-dcdb-4fdd-bedd-bdc7d79202b2/CR%20SPC%20CR5-6.csv?snapshot=2022-05-20T03%3A01%3A36.3135153Z"}]},{"$type":"LocalEntity","name":"CR SPC CR8-11","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"CR%20SPC%20CR8-11.csv"},"attributes":[{"name":"PART_NUMBER","dataType":"string"},{"name":"SERIAL_NUMBER","dataType":"string"},{"name":"WORK_ORDER","dataType":"string"},{"name":"Electrode Distance M","dataType":"double"},{"name":"Electrode Distance C","dataType":"double"},{"name":"Electrode Distance W","dataType":"double"},{"name":"Electrode Distance","dataType":"double"},{"name":"Extension Gap W","dataType":"double"},{"name":"Tube Pack Position W","dataType":"double"},{"name":"Extension Gap M","dataType":"double"},{"name":"Tube Pack Position M","dataType":"double"},{"name":"Electrode Plate Assembling","dataType":"string"},{"name":"Cathode Height C","dataType":"double"},{"name":"Cathode Base Height C","dataType":"double"},{"name":"Cathode Supplier","dataType":"string"},{"name":"Blasted Area Width C L","dataType":"double"},{"name":"Blasted Area Width C CL","dataType":"double"},{"name":"Blasted Area Width C CR","dataType":"double"},{"name":"Blasted Area Width C R","dataType":"double"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-20T03:00:35.7508497+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/2acbdeec-dcdb-4fdd-bedd-bdc7d79202b2/CR%20SPC%20CR8-11.csv?snapshot=2022-05-20T03%3A00%3A35.6821199Z"}]},{"$type":"LocalEntity","name":"CR SPC CR12-14","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"CR%20SPC%20CR12-14.csv"},"attributes":[{"name":"PART_NUMBER","dataType":"string"},{"name":"SERIAL_NUMBER","dataType":"string"},{"name":"WORK_ORDER","dataType":"string"},{"name":"Comp Leak Rate HV Feedthrough W","dataType":"double"},{"name":"Tube Pressure Limit","dataType":"double"},{"name":"Applied He Gas Pressure for Leaktest","dataType":"int64"},{"name":"Leak Rate Background","dataType":"double"},{"name":"Comp Leak Rate Baffle M Top","dataType":"double"},{"name":"Comp Leak Rate Baffle W Top","dataType":"double"},{"name":"Comp Leak Rate Baffle M Down","dataType":"double"},{"name":"Comp Leak Rate Baffle W Down","dataType":"double"},{"name":"Comp Leak Rate Window Slide M","dataType":"double"},{"name":"Comp Leak Rate Window Slide W","dataType":"double"},{"name":"Comp Leak Rate Flex Tube M","dataType":"double"},{"name":"Comp Leak Rate Flex Tube W","dataType":"double"},{"name":"Comp Leak Rate Frame M Top","dataType":"double"},{"name":"Comp Leak Rate Frame W Top","dataType":"double"},{"name":"Comp Leak Rate Frame W Down","dataType":"double"},{"name":"Comp Leak Rate Optic M","dataType":"double"},{"name":"Comp Leak Rate Optic W","dataType":"double"},{"name":"Comp Leak Rate Cooling Tube","dataType":"double"},{"name":"Comp Leak Rate Reservoir","dataType":"double"},{"name":"Comp Leak Rate Pressure Sensor","dataType":"double"},{"name":"Comp Leak Rate HV Feedthrough M","dataType":"double"},{"name":"Comp Leak Rate Preionization Pin","dataType":"double"},{"name":"Comp Leak Rate Frame M Down","dataType":"double"},{"name":"Overpressure Test Passed?","dataType":"string"},{"name":"Comp Leak Rate Window Slide M Drawn","dataType":"double"},{"name":"Comp Leak Rate Window Slide W Drawn","dataType":"double"},{"name":"Leak Rate Integral","dataType":"double"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-20T03:00:39.6543487+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/2acbdeec-dcdb-4fdd-bedd-bdc7d79202b2/CR%20SPC%20CR12-14.csv?snapshot=2022-05-20T03%3A00%3A39.6338648Z"}]},{"$type":"LocalEntity","name":"CR SPC TA1","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"CR%20SPC%20TA1.csv"},"attributes":[{"name":"PART_NUMBER","dataType":"string"},{"name":"SERIAL_NUMBER","dataType":"string"},{"name":"WORK_ORDER","dataType":"string"},{"name":"Resistor M","dataType":"double"},{"name":"Resistor W","dataType":"double"},{"name":"Peaking Capacity D","dataType":"double"},{"name":"Peaking Capacity G","dataType":"double"},{"name":"Water Pressure Drop","dataType":"double"},{"name":"Connection Sheet Checked and Mounted","dataType":"string"},{"name":"Room Temperature","dataType":"double"},{"name":"Water Leaktest Duration","dataType":"double"},{"name":"Coil M","dataType":"double"},{"name":"Coil W","dataType":"double"},{"name":"Capacitor Bank  NEW or REFURB","dataType":"string"},{"name":"Peakings Batch Number","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-20T03:00:42.2583148+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/2acbdeec-dcdb-4fdd-bedd-bdc7d79202b2/CR%20SPC%20TA1.csv?snapshot=2022-05-20T03%3A00%3A42.2163912Z"}]},{"$type":"LocalEntity","name":"CR SPC CR5-ReservoirSN","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"CR%20SPC%20CR5-ReservoirSN.csv"},"attributes":[{"name":"WORK_ORDER","dataType":"string"},{"name":"WO_STATUS","dataType":"string"},{"name":"SERIAL_NUMBER","dataType":"string"},{"name":"PART_NUMBER","dataType":"string"},{"name":"FLOW","dataType":"string"},{"name":"DATE","dataType":"date"},{"name":"Reservoir SN","dataType":"string"},{"name":"Reservoir Condition","dataType":"string"},{"name":"Reservoir Batch","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-20T03:00:40.8731233+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/2acbdeec-dcdb-4fdd-bedd-bdc7d79202b2/CR%20SPC%20CR5-ReservoirSN.csv?snapshot=2022-05-20T03%3A00%3A40.8471730Z"}]}]}