{"name":"Flow_ShelfLifetime-EndOfDurability","description":"Cumulus Shelf-Lifetime and End-of-Durability Datapoints.\nDaily refresh.","version":"1.0","culture":"en-US","modifiedTime":"2021-11-02T13:44:12.4930417+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"Cryo_Shlt-EoD":{"queryId":"a4c998be-2481-403e-adeb-d294964e754a","queryName":"Cryo_Shlt-EoD","loadEnabled":true},"Sample file":{"queryId":"975cb078-e2c2-47f4-a525-dc12723957a0","queryName":"Sample file","queryGroupId":"a5caf481-9cde-4189-b321-c801f631bce7"},"Parameter":{"queryId":"1359b38b-edff-4dca-80b8-c32db3e179c4","queryName":"Parameter","queryGroupId":"a5caf481-9cde-4189-b321-c801f631bce7"},"Transform Sample file":{"queryId":"ea2b54b1-e4d8-482c-a694-0fe0de961495","queryName":"Transform Sample file","queryGroupId":"646d787b-ff27-44ff-9c08-ccc714966107"},"Transform file":{"queryId":"d83d4d79-9786-40a0-83d9-1471b113f4cd","queryName":"Transform file","queryGroupId":"a5caf481-9cde-4189-b321-c801f631bce7"},"ET9_ShelfLifetime":{"queryId":"34423a05-af9b-494b-955d-d60e540802da","queryName":"ET9_ShelfLifetime","loadEnabled":true},"Sample file (2)":{"queryId":"b075b91a-ec8c-4e84-88e6-2e530b719160","queryName":"Sample file (2)","queryGroupId":"69193e59-e9cf-49eb-82eb-426756d1a01a"},"Parameter (2)":{"queryId":"930d56b8-b445-48cd-a767-6231814bbfa1","queryName":"Parameter (2)","queryGroupId":"69193e59-e9cf-49eb-82eb-426756d1a01a"},"Transform Sample file (2)":{"queryId":"0ad65b91-cce8-4f80-bbb2-f15f17479de9","queryName":"Transform Sample file (2)","queryGroupId":"0b79bd94-e019-4414-a679-3a55fb29edfb"},"Transform file (2)":{"queryId":"3e97c0d7-ccca-450a-880e-aa152282dbf9","queryName":"Transform file (2)","queryGroupId":"69193e59-e9cf-49eb-82eb-426756d1a01a"},"ShLt-EoD":{"queryId":"cb80bc81-47b7-47fc-b15e-d9582e47b0f1","queryName":"ShLt-EoD","loadEnabled":true}},"document":"section Section1;\r\nshared #\"Cryo_Shlt-EoD\" = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Extension] = \".xlsx\"),\r\n  #\"Filtered rows 1\" = Table.SelectRows(#\"Filtered rows\", each Text.Contains([Name], \"Shlt-EoD\")),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows 1\", each [Attributes]?[Hidden]? <> true),\r\n  #\"Invoke custom function\" = Table.AddColumn(#\"Filtered hidden files\", \"Transform file\", each #\"Transform file\"([Content])),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Invoke custom function\", {{\"Name\", \"Source.Name\"}}),\r\n  #\"Removed other columns\" = Table.SelectColumns(#\"Renamed columns\", {\"Source.Name\", \"Transform file\"}),\r\n  #\"Expanded table column\" = Table.ExpandTableColumn(#\"Removed other columns\", \"Transform file\", Table.ColumnNames(#\"Transform file\"(#\"Sample file\"))),\r\n  #\"Choose columns\" = Table.SelectColumns(#\"Expanded table column\", {\"WORK_ORDER\", \"WO_STATUS\", \"SERIAL_NUMBER\", \"PART_NUMBER\", \"FLOW\", \"PROCESS\", \"MEASUREMENT\", \"DATE\", \"DATA_VALUE\"}),\r\n  #\"Reordered columns\" = Table.ReorderColumns(#\"Choose columns\", {\"WORK_ORDER\", \"WO_STATUS\", \"SERIAL_NUMBER\", \"PART_NUMBER\", \"FLOW\", \"DATE\", \"PROCESS\", \"MEASUREMENT\", \"DATA_VALUE\"}),\r\n  #\"Replaced value\" = Table.ReplaceValue(#\"Reordered columns\", \"Mrz\", \"Mar\", Replacer.ReplaceValue, {\"DATA_VALUE\"}),\r\n  #\"Replaced value 1\" = Table.ReplaceValue(#\"Replaced value\", \"Mai\", \"May\", Replacer.ReplaceValue, {\"DATA_VALUE\"}),\r\n  #\"Replaced value 2\" = Table.ReplaceValue(#\"Replaced value 1\", \"Okt\", \"Oct\", Replacer.ReplaceValue, {\"DATA_VALUE\"}),\r\n  #\"Replaced value 3\" = Table.ReplaceValue(#\"Replaced value 2\", \"Dez\", \"Dec\", Replacer.ReplaceValue, {\"DATA_VALUE\"}),\r\n  #\"Pivoted column\" = Table.Pivot(Table.TransformColumnTypes(#\"Replaced value 3\", {{\"MEASUREMENT\", type text}}), List.Distinct(Table.TransformColumnTypes(#\"Replaced value 3\", {{\"MEASUREMENT\", type text}})[MEASUREMENT]), \"MEASUREMENT\", \"DATA_VALUE\"),\r\n  #\"Changed column type with locale\" = Table.TransformColumnTypes(#\"Pivoted column\", {{\"DATE\", type datetime}, {\"PROCESS\", type text}, {\"FLOW\", type text}, {\"PART_NUMBER\", type text}, {\"SERIAL_NUMBER\", type text}, {\"WO_STATUS\", type text}, {\"WORK_ORDER\", Int64.Type}, {\"End of Shelf Lifetime\", type date}, {\"End of Durability\", type date}}, \"de-DE\"),\r\n  #\"Filtered rows 2\" = Table.SelectRows(#\"Changed column type with locale\", each [WO_STATUS] = \"Closed\"),\r\n  #\"Replaced errors\" = Table.ReplaceErrorValues(#\"Filtered rows 2\", {{\"End of Shelf Lifetime\", #date(2099, 12, 31)}, {\"End of Durability\", #date(2099, 12, 31)}})\r\nin\r\n  #\"Replaced errors\";\r\nshared #\"Sample file\" = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Extension] = \".xlsx\"),\r\n  #\"Filtered rows 1\" = Table.SelectRows(#\"Filtered rows\", each Text.Contains([Name], \"Shlt-EoD\")),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows 1\", each [Attributes]?[Hidden]? <> true),\r\n  Navigation = #\"Filtered hidden files\"{0}[Content]\r\nin\r\n  Navigation;\r\nshared Parameter = let\r\n  Parameter = #\"Sample file\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type binary]\r\nin\r\n  Parameter;\r\nshared #\"Transform Sample file\" = let\r\n  Source = Excel.Workbook(Parameter, null, true),\r\n  Navigation = Source{[Item = \"CustomReportDataResult\", Kind = \"Sheet\"]}[Data],\r\n  #\"Promoted headers\" = Table.PromoteHeaders(Navigation, [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"WORK_ORDER\", Int64.Type}, {\"WO_STATUS\", type text}, {\"SERIAL_NUMBER\", type text}, {\"PART_NUMBER\", Int64.Type}, {\"DESCRIPTION\", type text}, {\"FLOW\", type text}, {\"PROCESS\", type text}, {\"PROCESS_DESCRIPTION\", type text}, {\"MEASUREMENT\", type text}, {\"DATA_TYPE\", type text}, {\"UOM\", type any}, {\"DATE\", type text}, {\"DATA_VALUE\", type text}, {\"PASS_SPEC\", type logical}, {\"PASS_CTL\", type logical}, {\"SPEC_LIMITS\", type any}, {\"CTL_LIMITS\", type any}, {\"WO_NOTES\", type text}, {\"DEVIATIONS\", type any}, {\"FLOW_STEP_DESC\", type any}})\r\nin\r\n  #\"Changed column type\";\r\nshared #\"Transform file\" = let\r\n  Source = (Parameter as binary) => let\r\n  Source = Excel.Workbook(Parameter, null, true),\r\n  Navigation = Source{[Item = \"CustomReportDataResult\", Kind = \"Sheet\"]}[Data],\r\n  #\"Promoted headers\" = Table.PromoteHeaders(Navigation, [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"WORK_ORDER\", Int64.Type}, {\"WO_STATUS\", type text}, {\"SERIAL_NUMBER\", type text}, {\"PART_NUMBER\", type text}, {\"DESCRIPTION\", type text}, {\"FLOW\", type text}, {\"PROCESS\", type text}, {\"PROCESS_DESCRIPTION\", type text}, {\"MEASUREMENT\", type text}, {\"DATA_TYPE\", type text}, {\"UOM\", type any}, {\"DATE\", type text}, {\"DATA_VALUE\", type text}, {\"PASS_SPEC\", type logical}, {\"PASS_CTL\", type logical}, {\"SPEC_LIMITS\", type any}, {\"CTL_LIMITS\", type any}, {\"WO_NOTES\", type text}, {\"DEVIATIONS\", type any}, {\"FLOW_STEP_DESC\", type any}})\r\nin\r\n  #\"Changed column type\"\r\nin\r\n  Source;\r\nshared ET9_ShelfLifetime = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Extension] = \".xlsx\"),\r\n  #\"Filtered rows 1\" = Table.SelectRows(#\"Filtered rows\", each Text.Contains([Name], \"ET-9-End_of_Shelf_Lifetime\")),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows 1\", each [Attributes]?[Hidden]? <> true),\r\n  #\"Invoke custom function\" = Table.AddColumn(#\"Filtered hidden files\", \"Transform file (2)\", each #\"Transform file (2)\"([Content])),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Invoke custom function\", {{\"Name\", \"Source.Name\"}}),\r\n  #\"Removed other columns\" = Table.SelectColumns(#\"Renamed columns\", {\"Source.Name\", \"Transform file (2)\"}),\r\n  #\"Expanded table column\" = Table.ExpandTableColumn(#\"Removed other columns\", \"Transform file (2)\", Table.ColumnNames(#\"Transform file (2)\"(#\"Sample file (2)\"))),\r\n  #\"Choose columns\" = Table.SelectColumns(#\"Expanded table column\", {\"WORK_ORDER\", \"SERIAL_NUMBER\", \"PART_NUMBER\", \"FLOW\", \"PROCESS\", \"DATE\", \"DATA_VALUE\", \"WO_STATUS\"}),\r\n  #\"Reordered columns\" = Table.ReorderColumns(#\"Choose columns\", {\"WORK_ORDER\", \"WO_STATUS\", \"SERIAL_NUMBER\", \"PART_NUMBER\", \"FLOW\", \"DATE\", \"PROCESS\", \"DATA_VALUE\"}),\r\n  #\"Renamed columns 1\" = Table.RenameColumns(#\"Reordered columns\", {{\"DATA_VALUE\", \"End of Shelf Lifetime\"}}),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Renamed columns 1\", {{\"WORK_ORDER\", Int64.Type}, {\"WO_STATUS\", type text}, {\"SERIAL_NUMBER\", type text}, {\"PART_NUMBER\", type text}, {\"FLOW\", type text}, {\"PROCESS\", type text}}),\r\n  #\"Changed column type with locale\" = Table.TransformColumnTypes(#\"Changed column type\", {{\"DATE\", type datetime}, {\"End of Shelf Lifetime\", type date}}, \"de-DE\"),\r\n  #\"Filtered rows 2\" = Table.SelectRows(#\"Changed column type with locale\", each [WO_STATUS] = \"Closed\")\r\nin\r\n  #\"Filtered rows 2\";\r\nshared #\"Sample file (2)\" = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Extension] = \".xlsx\"),\r\n  #\"Filtered rows 1\" = Table.SelectRows(#\"Filtered rows\", each Text.Contains([Name], \"ET-9-End_of_Shelf_Lifetime\")),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows 1\", each [Attributes]?[Hidden]? <> true),\r\n  Navigation = #\"Filtered hidden files\"{0}[Content]\r\nin\r\n  Navigation;\r\nshared #\"Parameter (2)\" = let\r\n  #\"Parameter (2)\" = #\"Sample file (2)\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type binary]\r\nin\r\n  #\"Parameter (2)\";\r\nshared #\"Transform Sample file (2)\" = let\r\n  Source = Excel.Workbook(#\"Parameter (2)\", null, true),\r\n  Navigation = Source{[Item = \"DataPointsResult\", Kind = \"Sheet\"]}[Data],\r\n  #\"Promoted headers\" = Table.PromoteHeaders(Navigation, [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"WORK_ORDER\", Int64.Type}, {\"SERIAL_NUMBER\", type text}, {\"PART_NUMBER\", Int64.Type}, {\"DESCRIPTION\", type text}, {\"FLOW\", type text}, {\"PROCESS\", type text}, {\"PROCESS_DESCRIPTION\", type text}, {\"MEASUREMENT\", type text}, {\"DATA_TYPE\", type text}, {\"UOM\", type any}, {\"DATE\", type text}, {\"DATA_VALUE\", type text}, {\"PASS_SPEC\", type logical}, {\"PASS_CTL\", type logical}, {\"SPEC_LIMITS\", type any}, {\"CTL_LIMITS\", type any}, {\"ORG\", type text}, {\"WO_STATUS\", type text}})\r\nin\r\n  #\"Changed column type\";\r\nshared #\"Transform file (2)\" = let\r\n  Source = (#\"Parameter (2)\" as binary) => let\r\n  Source = Excel.Workbook(#\"Parameter (2)\", null, true),\r\n  Navigation = Source{[Item = \"DataPointsResult\", Kind = \"Sheet\"]}[Data],\r\n  #\"Promoted headers\" = Table.PromoteHeaders(Navigation, [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"WORK_ORDER\", Int64.Type}, {\"SERIAL_NUMBER\", type text}, {\"PART_NUMBER\", Int64.Type}, {\"DESCRIPTION\", type text}, {\"FLOW\", type text}, {\"PROCESS\", type text}, {\"PROCESS_DESCRIPTION\", type text}, {\"MEASUREMENT\", type text}, {\"DATA_TYPE\", type text}, {\"UOM\", type any}, {\"DATE\", type text}, {\"DATA_VALUE\", type text}, {\"PASS_SPEC\", type logical}, {\"PASS_CTL\", type logical}, {\"SPEC_LIMITS\", type any}, {\"CTL_LIMITS\", type any}, {\"ORG\", type text}, {\"WO_STATUS\", type text}})\r\nin\r\n  #\"Changed column type\"\r\nin\r\n  Source;\r\nshared #\"ShLt-EoD\" = let\r\n  Source = Table.Combine({ET9_ShelfLifetime, #\"Cryo_Shlt-EoD\"}),\r\n  #\"Choose columns\" = Table.SelectColumns(Source, {\"WORK_ORDER\", \"SERIAL_NUMBER\", \"DATE\", \"End of Shelf Lifetime\", \"End of Durability\"}),\r\n  #\"Sorted rows\" = Table.Buffer(Table.Sort(#\"Choose columns\", {{\"End of Shelf Lifetime\", Order.Descending}})),\r\n  #\"Removed duplicates\" = Table.Distinct(#\"Sorted rows\", {\"SERIAL_NUMBER\"})\r\nin\r\n  #\"Removed duplicates\";\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[{\"id\":\"646d787b-ff27-44ff-9c08-ccc714966107\",\"name\":\"Transform file from Cryo_Shlt-EoD\",\"description\":null,\"parentId\":null,\"order\":0},{\"id\":\"a5caf481-9cde-4189-b321-c801f631bce7\",\"name\":\"Helper queries\",\"description\":null,\"parentId\":\"646d787b-ff27-44ff-9c08-ccc714966107\",\"order\":0},{\"id\":\"0b79bd94-e019-4414-a679-3a55fb29edfb\",\"name\":\"Transform file from ET9_ShelfLifetime\",\"description\":null,\"parentId\":null,\"order\":0},{\"id\":\"69193e59-e9cf-49eb-82eb-426756d1a01a\",\"name\":\"Helper queries (2)\",\"description\":null,\"parentId\":\"0b79bd94-e019-4414-a679-3a55fb29edfb\",\"order\":0}]"}],"entities":[{"$type":"LocalEntity","name":"Cryo_Shlt-EoD","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Cryo_Shlt-EoD.csv"},"attributes":[{"name":"WORK_ORDER","dataType":"int64"},{"name":"WO_STATUS","dataType":"string"},{"name":"SERIAL_NUMBER","dataType":"string"},{"name":"PART_NUMBER","dataType":"string"},{"name":"FLOW","dataType":"string"},{"name":"DATE","dataType":"dateTime"},{"name":"PROCESS","dataType":"string"},{"name":"End of Shelf Lifetime","dataType":"date"},{"name":"End of Durability","dataType":"date"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2021-11-02T13:44:25.5089137+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/f063ee50-72ee-4c57-8a7d-0279c7ba1264/Cryo_Shlt-EoD.csv?snapshot=2021-11-02T13%3A44%3A25.3593277Z"}]},{"$type":"LocalEntity","name":"ET9_ShelfLifetime","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"ET9_ShelfLifetime.csv"},"attributes":[{"name":"WORK_ORDER","dataType":"int64"},{"name":"WO_STATUS","dataType":"string"},{"name":"SERIAL_NUMBER","dataType":"string"},{"name":"PART_NUMBER","dataType":"string"},{"name":"FLOW","dataType":"string"},{"name":"DATE","dataType":"dateTime"},{"name":"PROCESS","dataType":"string"},{"name":"End of Shelf Lifetime","dataType":"date"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2021-11-02T13:44:24.6947785+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/f063ee50-72ee-4c57-8a7d-0279c7ba1264/ET9_ShelfLifetime.csv?snapshot=2021-11-02T13%3A44%3A24.4988222Z"}]},{"$type":"LocalEntity","name":"ShLt-EoD","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"ShLt-EoD.csv"},"annotations":[{"name":"pbi:EntityTypeDisplayHint","value":"CalculatedEntity"}],"attributes":[{"name":"WORK_ORDER","dataType":"int64"},{"name":"SERIAL_NUMBER","dataType":"string"},{"name":"DATE","dataType":"dateTime"},{"name":"End of Shelf Lifetime","dataType":"date"},{"name":"End of Durability","dataType":"date"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2021-11-02T13:44:27.4011343+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/f063ee50-72ee-4c57-8a7d-0279c7ba1264/ShLt-EoD.csv?snapshot=2021-11-02T13%3A44%3A27.3601777Z"}]}]}