{"name":"Flow_Refurbishment","description":"Flow for refurbishment data / files.\nR-BOM, prices, etc.","version":"1.0","culture":"en-US","modifiedTime":"2022-02-23T15:55:43.8543883+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"R-BOM":{"queryId":"0c79909c-e1eb-4e5c-a8a9-155961e66508","queryName":"R-BOM","loadEnabled":true},"Sample file":{"queryId":"16fedc58-bc90-4239-8629-aaf31bf5429b","queryName":"Sample file","queryGroupId":"23499644-9d80-42af-8c72-0556394010da"},"Parameter":{"queryId":"a51c1198-38bb-4ca4-bb1d-4a0e5bfe09ba","queryName":"Parameter","queryGroupId":"23499644-9d80-42af-8c72-0556394010da"},"Transform Sample file":{"queryId":"c5069c15-deb0-4331-8966-4dc1d90308c0","queryName":"Transform Sample file","queryGroupId":"6e21f51a-2af4-4fc8-807b-4f8634e83dde"},"Transform file":{"queryId":"f3ee22d3-480b-4e24-a959-d38c976ef90e","queryName":"Transform file","queryGroupId":"23499644-9d80-42af-8c72-0556394010da"},"R-BOMs":{"queryId":"a5d0daee-b627-4599-806d-631d7896f577","queryName":"R-BOMs","loadEnabled":true},"R-BOMs_Revisions":{"queryId":"65b82e54-608d-410a-b27e-aa069e3eed02","queryName":"R-BOMs_Revisions","loadEnabled":true},"R-BOM Revisions":{"queryId":"72715ebe-a29e-474a-a3d9-c3173c31fc58","queryName":"R-BOM Revisions"},"Sample file (2)":{"queryId":"a9843018-fc33-4c8f-84cb-2de120d25a1c","queryName":"Sample file (2)","queryGroupId":"bc999b51-8765-4c31-a6c9-18c8cd5f867e"},"Parameter (2)":{"queryId":"bc2c5e04-5bdc-4c7a-b82a-b3a51e7b8436","queryName":"Parameter (2)","queryGroupId":"bc999b51-8765-4c31-a6c9-18c8cd5f867e"},"Transform Sample file (2)":{"queryId":"8c7342b3-aa37-4f33-bb63-c8da46d94134","queryName":"Transform Sample file (2)","queryGroupId":"8fc1ba9a-09c1-4314-9040-2fa6eaab9a4a"},"Transform file (2)":{"queryId":"30f30d80-fd24-42de-85c0-28c6680d3ed9","queryName":"Transform file (2)","queryGroupId":"bc999b51-8765-4c31-a6c9-18c8cd5f867e"},"R-BOM Categories":{"queryId":"961b7c27-0532-46a8-a3fb-7f4a1769d666","queryName":"R-BOM Categories"},"Sample file (3)":{"queryId":"5b6bfbfe-5601-4783-8c8b-b3d988c4def3","queryName":"Sample file (3)","queryGroupId":"dfc40b36-4eba-42e2-964b-b96e5d6c1eda"},"Parameter (3)":{"queryId":"9541c5fe-4f53-4acf-9bcd-83d2048c1319","queryName":"Parameter (3)","queryGroupId":"dfc40b36-4eba-42e2-964b-b96e5d6c1eda"},"Transform Sample file (3)":{"queryId":"a2fed1b7-9fb1-4d41-b203-754c9f2de958","queryName":"Transform Sample file (3)","queryGroupId":"150171cc-4a14-450d-861b-89dbf135c936"},"Transform file (3)":{"queryId":"4754dd05-f121-4810-aaee-80b9f2ce1dc8","queryName":"Transform file (3)","queryGroupId":"dfc40b36-4eba-42e2-964b-b96e5d6c1eda"},"Refurb_MayerFT old":{"queryId":"08d8c8b3-ed41-43bb-bfa7-457c0e8162c7","queryName":"Refurb_MayerFT old"},"Sample file (4)":{"queryId":"69e580c6-e8d1-4333-98ef-2fa101e3fe06","queryName":"Sample file (4)","queryGroupId":"a09de42c-7fae-4cab-bc67-07695f2a1ebd"},"Parameter (4)":{"queryId":"513e4e55-ca84-4471-b13b-7a315ccc98a8","queryName":"Parameter (4)","queryGroupId":"a09de42c-7fae-4cab-bc67-07695f2a1ebd"},"Transform Sample file (4)":{"queryId":"191c0a3b-de87-4fb6-9e2b-064b07c70ef4","queryName":"Transform Sample file (4)","queryGroupId":"d84258f9-0d20-419e-be78-f382c865c8ad"},"Transform file (4)":{"queryId":"ef69a698-d9eb-4a1d-9cc2-6b28a9d23635","queryName":"Transform file (4)","queryGroupId":"a09de42c-7fae-4cab-bc67-07695f2a1ebd"},"Disassembly_Data_Oracle":{"queryId":"23e01cdf-45fd-4e33-aecb-a1823a3b44ca","queryName":"Disassembly_Data_Oracle","loadEnabled":true},"Transform File from Disassembly_Data":{"queryId":"7e53182d-1d4e-4355-a154-86dae0d868f7","queryName":"Transform File from Disassembly_Data","queryGroupId":"39672e74-5be5-42f0-a64e-8581f8a41ee9"},"Sample File (7)":{"queryId":"b470764d-012b-4da2-bc28-cbe4ea30ff62","queryName":"Sample File (7)","queryGroupId":"39672e74-5be5-42f0-a64e-8581f8a41ee9"},"Refurb_MayerFT":{"queryId":"71299a5c-765c-4921-82a4-69f21706cb1c","queryName":"Refurb_MayerFT","loadEnabled":true},"Sample file (5)":{"queryId":"1eaeeb3b-66f1-41c0-957a-445eb2fa5c61","queryName":"Sample file (5)","queryGroupId":"c937eea0-51eb-45b7-9476-bf358bf4eca7"},"Parameter (5)":{"queryId":"488cae72-240e-45a7-b17d-fcc879c50bcc","queryName":"Parameter (5)","queryGroupId":"c937eea0-51eb-45b7-9476-bf358bf4eca7"},"Transform Sample file (5)":{"queryId":"9c18caa5-aa76-4dad-91b6-602951706d01","queryName":"Transform Sample file (5)","queryGroupId":"cf164016-d7b1-44ff-9e4c-c6064ff2ef90"},"Transform file (5)":{"queryId":"3e5ddc4b-490c-4381-8364-743fa1532b9f","queryName":"Transform file (5)","queryGroupId":"c937eea0-51eb-45b7-9476-bf358bf4eca7"},"Sample file (6)":{"queryId":"387fdcab-e958-4df8-a57f-47f61160d6ed","queryName":"Sample file (6)","queryGroupId":"1ba111a0-5d49-4722-94fd-dc2919dae73f"},"Parameter (6)":{"queryId":"6b469f60-d816-4872-8801-ccac7e3656d9","queryName":"Parameter (6)","queryGroupId":"1ba111a0-5d49-4722-94fd-dc2919dae73f"},"Transform Sample file (6)":{"queryId":"3db055e2-c9b5-425d-9326-6c5473cf35b4","queryName":"Transform Sample file (6)","queryGroupId":"f5b75aef-b39b-4391-bb1d-f8cf679eed3a"},"Transform file (6)":{"queryId":"d5af172a-9a23-411e-a81b-e652af37cc20","queryName":"Transform file (6)","queryGroupId":"1ba111a0-5d49-4722-94fd-dc2919dae73f"}},"document":"section Section1;\r\nshared #\"R-BOM\" = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Name] = \"R-BOM_1162502D.xlsx\" or [Name] = \"R-BOM_1305319D_NTB.xlsx\" or [Name] = \"R-BOM_1348099_NTB KEP.xlsx\" or [Name] = \"R-BOM_D145395_KEP.xlsx\" or [Name] = \"R-BOM_Amendments.xlsx\"),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows\", each [Attributes]?[Hidden]? <> true),\r\n  #\"Invoke custom function\" = Table.AddColumn(#\"Filtered hidden files\", \"Transform file\", each #\"Transform file\"([Content])),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Invoke custom function\", {{\"Name\", \"Source.Name\"}}),\r\n  #\"Removed other columns\" = Table.SelectColumns(#\"Renamed columns\", {\"Source.Name\", \"Transform file\"}),\r\n  #\"Expanded table column\" = Table.ExpandTableColumn(#\"Removed other columns\", \"Transform file\", Table.ColumnNames(#\"Transform file\"(#\"Sample file\"))),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Expanded table column\", {{\"Source.Name\", type text}, {\"Level\", Int64.Type}, {\"Item Number*\", type text}, {\"Part Type*\", type text}, {\"Description*\", type text}, {\"UOM*\", type text}, {\"Effectivity Date\", type text}, {\"Lifecycle Phase\", type text}, {\"Rev Release Date\", type text}, {\"Rev Incorp Date\", type text}, {\"Part Category*\", type text}, {\"Revision\", type text}, {\"Base Model\", type any}, {\"Sites\", type any}, {\"BOM.Item Description\", type text}, {\"BOM.Item Type\", type text}, {\"BOM.Rev\", type text}, {\"BOM.Lifecycle Phase\", type text}, {\"BOM.Qty\", type number}, {\"BOM.UOM\", type text}, {\"BOM.Find Num\", Int64.Type}, {\"BOM.Ref Des\", type any}, {\"BOM.BOM Notes\", type any}, {\"BOM.Optional\", type any}, {\"BOM.Mut Excl\", type any}, {\"BOM.Min Qty\", type any}, {\"BOM.Max Qty\", type any}, {\"BOM.Option Description\", type any}, {\"BOM.Configurator Rules\", type any}, {\"BOM.Appears on Quote\", type any}, {\"BOM.Configurator Pricing\", type any}, {\"BOM.Instance Description Flag\", type any}, {\"BOM.Non-English Description  \", type text}, {\"Manufacturers.Manufacturer Class\", type text}, {\"Manufacturers.AML Status\", type text}, {\"Manufacturers.Manufacturer Type\", type text}, {\"Manufacturers.Manufacturer Name\", type text}, {\"Manufacturers.MPN\", type text}, {\"Manufacturers.MPN Status\", type text}, {\"Manufacturers.Manufacturer Site\", type text}, {\"Manufacturers.Manufacturer City\", type any}, {\"Manufacturers.Manufacturer Country\", type any}, {\"Manufacturers.RoHS Compliant\", type text}, {\"Manufacturers.RoHS Exemptions\", Int64.Type}, {\"Manufacturers.REACH Compliant\", type text}, {\"Manufacturers.REACH Level\", Int64.Type}, {\"Manufacturers.Oracle Supplier ID\", type any}, {\"Manufacturers.Oracle Supplier Site ID\", type any}, {\"Manufacturers.Summary Compliance\", type any}, {\"Manufacturers.Mfr. Part Description\", type any}, {\"Manufacturers.Reference Notes\", type any}}),\r\n  #\"Choose columns\" = Table.SelectColumns(#\"Changed column type\", {\"Source.Name\", \"Level\", \"Item Number*\", \"Part Type*\", \"Description*\", \"BOM.Qty\"}),\r\n  #\"Filtered rows 1\" = Table.SelectRows(#\"Choose columns\", each [Level] <> 0),\r\n  #\"Filtered rows 2\" = Table.SelectRows(#\"Filtered rows 1\", each Text.Contains([#\"Item Number*\"], \"R\")),\r\n  #\"Duplicated column\" = Table.DuplicateColumn(#\"Filtered rows 2\", \"Item Number*\", \"Item Number* - Copy\"),\r\n  #\"Extracted text before delimiter\" = Table.TransformColumns(#\"Duplicated column\", {{\"Item Number* - Copy\", each Text.BeforeDelimiter(_, \"R\", 0), type text}}),\r\n  #\"Merged queries\" = Table.NestedJoin(#\"Extracted text before delimiter\", {\"Item Number* - Copy\"}, #\"R-BOM Revisions\", {\"Item Number*\"}, \"R-BOM Revisions\", JoinKind.LeftOuter),\r\n  #\"Expanded R-BOM Revisions\" = Table.ExpandTableColumn(#\"Merged queries\", \"R-BOM Revisions\", {\"Revision\"}, {\"Revision\"}),\r\n  #\"Removed duplicates\" = Table.Distinct(#\"Expanded R-BOM Revisions\", {\"Item Number*\"}),\r\n  #\"Removed columns\" = Table.RemoveColumns(#\"Removed duplicates\", {\"Item Number* - Copy\"}),\r\n  #\"Merged queries 1\" = Table.NestedJoin(#\"Removed columns\", {\"Item Number*\"}, #\"R-BOM Categories\", {\"Item Number\"}, \"R-BOM Categories\", JoinKind.LeftOuter),\r\n  #\"Expanded R-BOM Categories\" = Table.ExpandTableColumn(#\"Merged queries 1\", \"R-BOM Categories\", {\"Item Description Short\", \"Assembly Group\"}, {\"Item Description Short\", \"Assembly Group\"})\r\nin\r\n  #\"Expanded R-BOM Categories\";\r\nshared #\"Sample file\" = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Name] = \"R-BOM_1162502D.xlsx\" or [Name] = \"R-BOM_1305319D_NTB.xlsx\" or [Name] = \"R-BOM_1348099_NTB KEP.xlsx\" or [Name] = \"R-BOM_D145395_KEP.xlsx\"),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows\", each [Attributes]?[Hidden]? <> true),\r\n  Navigation = #\"Filtered hidden files\"{0}[Content]\r\nin\r\n  Navigation;\r\nshared Parameter = let\r\n  Parameter = #\"Sample file\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type binary]\r\nin\r\n  Parameter;\r\nshared #\"Transform Sample file\" = let\r\n  Source = Excel.Workbook(Parameter, null, true),\r\n  Navigation = Source{[Item = \"Sheet0\", Kind = \"Sheet\"]}[Data],\r\n  #\"Promoted headers\" = Table.PromoteHeaders(Navigation, [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"Level\", Int64.Type}, {\"Item Number*\", type text}, {\"Part Type*\", type text}, {\"Description*\", type text}, {\"UOM*\", type text}, {\"Effectivity Date\", type text}, {\"Lifecycle Phase\", type text}, {\"Rev Release Date\", type text}, {\"Rev Incorp Date\", type text}, {\"Part Category*\", type text}, {\"Revision\", type text}, {\"Base Model\", type any}, {\"Sites\", type any}, {\"BOM.Item Description\", type text}, {\"BOM.Item Type\", type text}, {\"BOM.Rev\", type text}, {\"BOM.Lifecycle Phase\", type text}, {\"BOM.Qty\", type number}, {\"BOM.UOM\", type text}, {\"BOM.Find Num\", Int64.Type}, {\"BOM.Ref Des\", type any}, {\"BOM.BOM Notes\", type any}, {\"BOM.Optional\", type any}, {\"BOM.Mut Excl\", type any}, {\"BOM.Min Qty\", type any}, {\"BOM.Max Qty\", type any}, {\"BOM.Option Description\", type any}, {\"BOM.Configurator Rules\", type any}, {\"BOM.Appears on Quote\", type any}, {\"BOM.Configurator Pricing\", type any}, {\"BOM.Instance Description Flag\", type any}, {\"BOM.Non-English Description  \", type text}, {\"Manufacturers.Manufacturer Class\", type text}, {\"Manufacturers.AML Status\", type text}, {\"Manufacturers.Manufacturer Type\", type text}, {\"Manufacturers.Manufacturer Name\", type text}, {\"Manufacturers.MPN\", type text}, {\"Manufacturers.MPN Status\", type text}, {\"Manufacturers.Manufacturer Site\", type text}, {\"Manufacturers.Manufacturer City\", type any}, {\"Manufacturers.Manufacturer Country\", type any}, {\"Manufacturers.RoHS Compliant\", type text}, {\"Manufacturers.RoHS Exemptions\", Int64.Type}, {\"Manufacturers.REACH Compliant\", type text}, {\"Manufacturers.REACH Level\", Int64.Type}, {\"Manufacturers.Oracle Supplier ID\", type any}, {\"Manufacturers.Oracle Supplier Site ID\", type any}, {\"Manufacturers.Summary Compliance\", type any}, {\"Manufacturers.Mfr. Part Description\", type any}, {\"Manufacturers.Reference Notes\", type any}})\r\nin\r\n  #\"Changed column type\";\r\nshared #\"Transform file\" = let\r\n  Source = (Parameter as binary) => let\r\n  Source = Excel.Workbook(Parameter, null, true),\r\n  Navigation = Source{[Item = \"Sheet0\", Kind = \"Sheet\"]}[Data],\r\n  #\"Promoted headers\" = Table.PromoteHeaders(Navigation, [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"Level\", Int64.Type}, {\"Item Number*\", type text}, {\"Part Type*\", type text}, {\"Description*\", type text}, {\"UOM*\", type text}, {\"Effectivity Date\", type text}, {\"Lifecycle Phase\", type text}, {\"Rev Release Date\", type text}, {\"Rev Incorp Date\", type text}, {\"Part Category*\", type text}, {\"Revision\", type text}, {\"Base Model\", type any}, {\"Sites\", type any}, {\"BOM.Item Description\", type text}, {\"BOM.Item Type\", type text}, {\"BOM.Rev\", type text}, {\"BOM.Lifecycle Phase\", type text}, {\"BOM.Qty\", type number}, {\"BOM.UOM\", type text}, {\"BOM.Find Num\", Int64.Type}, {\"BOM.Ref Des\", type any}, {\"BOM.BOM Notes\", type any}, {\"BOM.Optional\", type any}, {\"BOM.Mut Excl\", type any}, {\"BOM.Min Qty\", type any}, {\"BOM.Max Qty\", type any}, {\"BOM.Option Description\", type any}, {\"BOM.Configurator Rules\", type any}, {\"BOM.Appears on Quote\", type any}, {\"BOM.Configurator Pricing\", type any}, {\"BOM.Instance Description Flag\", type any}, {\"BOM.Non-English Description  \", type text}, {\"Manufacturers.Manufacturer Class\", type text}, {\"Manufacturers.AML Status\", type text}, {\"Manufacturers.Manufacturer Type\", type text}, {\"Manufacturers.Manufacturer Name\", type text}, {\"Manufacturers.MPN\", type text}, {\"Manufacturers.MPN Status\", type text}, {\"Manufacturers.Manufacturer Site\", type text}, {\"Manufacturers.Manufacturer City\", type any}, {\"Manufacturers.Manufacturer Country\", type any}, {\"Manufacturers.RoHS Compliant\", type text}, {\"Manufacturers.RoHS Exemptions\", Int64.Type}, {\"Manufacturers.REACH Compliant\", type text}, {\"Manufacturers.REACH Level\", Int64.Type}, {\"Manufacturers.Oracle Supplier ID\", type any}, {\"Manufacturers.Oracle Supplier Site ID\", type any}, {\"Manufacturers.Summary Compliance\", type any}, {\"Manufacturers.Mfr. Part Description\", type any}, {\"Manufacturers.Reference Notes\", type any}})\r\nin\r\n  #\"Changed column type\"\r\nin\r\n  Source;\r\nshared #\"R-BOMs\" = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each Text.Contains([Folder Path], \"R-BOMs\")),\r\n  #\"Filtered rows 1\" = Table.SelectRows(#\"Filtered rows\", each Text.StartsWith([Name], \"R-BOM_\")),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows 1\", each [Attributes]?[Hidden]? <> true),\r\n  #\"Invoke custom function\" = Table.AddColumn(#\"Filtered hidden files\", \"Transform file (6)\", each #\"Transform file (6)\"([Content])),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Invoke custom function\", {{\"Name\", \"Source.Name\"}}),\r\n  #\"Removed other columns\" = Table.SelectColumns(#\"Renamed columns\", {\"Source.Name\", \"Transform file (6)\"}),\r\n  #\"Expanded table column\" = Table.ExpandTableColumn(#\"Removed other columns\", \"Transform file (6)\", Table.ColumnNames(#\"Transform file (6)\"(#\"Sample file (6)\"))),\r\n  #\"Choose columns\" = Table.SelectColumns(#\"Expanded table column\", {\"Source.Name\", \"Level\", \"Item Number*\", \"Part Type*\", \"Description*\", \"BOM.Qty\"}),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Choose columns\", {{\"Level\", type text}, {\"Item Number*\", type text}, {\"Part Type*\", type text}, {\"Description*\", type text}, {\"BOM.Qty\", type number}}),\r\n  #\"Filtered rows 2\" = Table.SelectRows(#\"Changed column type\", each Text.Contains([#\"Item Number*\"], \"R\")),\r\n  #\"Inserted text before delimiter\" = Table.AddColumn(#\"Filtered rows 2\", \"ItemNumber\", each Text.BeforeDelimiter([#\"Item Number*\"], \"R\", 0), type text),\r\n  #\"Merged queries\" = Table.NestedJoin(#\"Inserted text before delimiter\", {\"ItemNumber\"}, #\"R-BOM Revisions\", {\"Item Number*\"}, \"R-BOM Revisions\", JoinKind.LeftOuter),\r\n  #\"Expanded R-BOM Revisions\" = Table.ExpandTableColumn(#\"Merged queries\", \"R-BOM Revisions\", {\"Revision\"}, {\"Revision\"}),\r\n  #\"Merged queries 1\" = Table.NestedJoin(#\"Expanded R-BOM Revisions\", {\"Item Number*\"}, #\"R-BOM Categories\", {\"Item Number\"}, \"R-BOM Categories\", JoinKind.LeftOuter),\r\n  #\"Expanded R-BOM Categories\" = Table.ExpandTableColumn(#\"Merged queries 1\", \"R-BOM Categories\", {\"Assembly Group\"}, {\"Assembly Group\"}),\r\n  #\"Inserted text between delimiters\" = Table.AddColumn(#\"Expanded R-BOM Categories\", \"Org\", each Text.BetweenDelimiters([Source.Name], \"_\", \"_\", 0, 0), type text),\r\n  #\"Choose columns 1\" = Table.SelectColumns(#\"Inserted text between delimiters\", {\"Source.Name\", \"Level\", \"Item Number*\", \"Description*\", \"BOM.Qty\", \"Revision\", \"Assembly Group\", \"Org\"}),\r\n  #\"Renamed columns 1\" = Table.RenameColumns(#\"Choose columns 1\", {{\"Item Number*\", \"Item Number\"}, {\"Description*\", \"Description\"}})\r\nin\r\n  #\"Renamed columns 1\";\r\nshared #\"R-BOMs_Revisions\" = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each Text.Contains([Folder Path], \"R-BOMs\")),\r\n  #\"Filtered rows 1\" = Table.SelectRows(#\"Filtered rows\", each Text.StartsWith([Name], \"R-BOM_\")),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows 1\", each [Attributes]?[Hidden]? <> true),\r\n  #\"Invoke custom function\" = Table.AddColumn(#\"Filtered hidden files\", \"Transform file (6)\", each #\"Transform file (6)\"([Content])),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Invoke custom function\", {{\"Name\", \"Source.Name\"}}),\r\n  #\"Removed other columns\" = Table.SelectColumns(#\"Renamed columns\", {\"Source.Name\", \"Transform file (6)\"}),\r\n  #\"Expanded table column\" = Table.ExpandTableColumn(#\"Removed other columns\", \"Transform file (6)\", Table.ColumnNames(#\"Transform file (6)\"(#\"Sample file (6)\"))),\r\n  #\"Choose columns\" = Table.SelectColumns(#\"Expanded table column\", {\"Source.Name\", \"Level\", \"Item Number*\", \"Part Type*\", \"Description*\", \"Revision\"}),\r\n  #\"Filtered rows 2\" = Table.SelectRows(#\"Choose columns\", each [Level] = 0),\r\n  #\"Extracted text before delimiter\" = Table.TransformColumns(#\"Filtered rows 2\", {{\"Revision\", each Text.BeforeDelimiter(Text.From(_), \" \", 0), type text}}),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Extracted text before delimiter\", {{\"Source.Name\", type text}, {\"Level\", type text}, {\"Item Number*\", type text}, {\"Part Type*\", type text}, {\"Description*\", type text}, {\"Revision\", type text}})\r\nin\r\n  #\"Changed column type\";\r\nshared #\"R-BOM Revisions\" = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Name] = \"D141915_Revisions_R-Parts.xlsx\"),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows\", each [Attributes]?[Hidden]? <> true),\r\n  #\"Invoke custom function\" = Table.AddColumn(#\"Filtered hidden files\", \"Transform file (2)\", each #\"Transform file (2)\"([Content])),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Invoke custom function\", {{\"Name\", \"Source.Name\"}}),\r\n  #\"Removed other columns\" = Table.SelectColumns(#\"Renamed columns\", {\"Source.Name\", \"Transform file (2)\"}),\r\n  #\"Expanded table column\" = Table.ExpandTableColumn(#\"Removed other columns\", \"Transform file (2)\", Table.ColumnNames(#\"Transform file (2)\"(#\"Sample file (2)\"))),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Expanded table column\", {{\"Source.Name\", type text}, {\"Level\", Int64.Type}, {\"Item Number*\", type text}, {\"Part Type*\", type text}, {\"Description*\", type text}, {\"UOM*\", type text}, {\"Effectivity Date\", type text}, {\"Lifecycle Phase\", type text}, {\"Rev Release Date\", type text}, {\"Rev Incorp Date\", type text}, {\"Part Category*\", type text}, {\"Revision\", type text}, {\"Base Model\", type any}, {\"Sites\", type any}, {\"BOM.Item Description\", type text}, {\"BOM.Item Type\", type text}, {\"BOM.Rev\", type text}, {\"BOM.Lifecycle Phase\", type text}, {\"BOM.Qty\", type number}, {\"BOM.UOM\", type text}, {\"BOM.Find Num\", Int64.Type}, {\"BOM.Ref Des\", type any}, {\"BOM.BOM Notes\", type text}, {\"BOM.Optional\", type any}, {\"BOM.Mut Excl\", type any}, {\"BOM.Min Qty\", type any}, {\"BOM.Max Qty\", type any}, {\"BOM.Option Description\", type text}, {\"BOM.Configurator Rules\", type any}, {\"BOM.Appears on Quote\", type any}, {\"BOM.Configurator Pricing\", type any}, {\"BOM.Instance Description Flag\", type any}, {\"BOM.Non-English Description  \", type text}, {\"Manufacturers.Manufacturer Class\", type any}, {\"Manufacturers.AML Status\", type any}, {\"Manufacturers.Manufacturer Type\", type any}, {\"Manufacturers.Manufacturer Name\", type any}, {\"Manufacturers.MPN\", type any}, {\"Manufacturers.MPN Status\", type any}, {\"Manufacturers.Manufacturer Site\", type any}, {\"Manufacturers.Manufacturer City\", type any}, {\"Manufacturers.Manufacturer Country\", type any}, {\"Manufacturers.RoHS Compliant\", type any}, {\"Manufacturers.RoHS Exemptions\", type any}, {\"Manufacturers.REACH Compliant\", type any}, {\"Manufacturers.REACH Level\", type any}, {\"Manufacturers.Oracle Supplier ID\", type any}, {\"Manufacturers.Oracle Supplier Site ID\", type any}, {\"Manufacturers.Summary Compliance\", type any}, {\"Manufacturers.Mfr. Part Description\", type any}, {\"Manufacturers.Reference Notes\", type any}}),\r\n  #\"Choose columns\" = Table.SelectColumns(#\"Changed column type\", {\"Item Number*\", \"Description*\", \"Revision\"}),\r\n  #\"Extracted first characters\" = Table.TransformColumns(#\"Choose columns\", {{\"Revision\", each Text.Start(_, 2), type text}})\r\nin\r\n  #\"Extracted first characters\";\r\nshared #\"Sample file (2)\" = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Name] = \"D141915_Revisions_R-Parts.xlsx\"),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows\", each [Attributes]?[Hidden]? <> true),\r\n  Navigation = #\"Filtered hidden files\"{0}[Content]\r\nin\r\n  Navigation;\r\nshared #\"Parameter (2)\" = let\r\n  #\"Parameter (2)\" = #\"Sample file (2)\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type binary]\r\nin\r\n  #\"Parameter (2)\";\r\nshared #\"Transform Sample file (2)\" = let\r\n  Source = Excel.Workbook(#\"Parameter (2)\", null, true),\r\n  Navigation = Source{[Item = \"Sheet0\", Kind = \"Sheet\"]}[Data],\r\n  #\"Promoted headers\" = Table.PromoteHeaders(Navigation, [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"Level\", Int64.Type}, {\"Item Number*\", type text}, {\"Part Type*\", type text}, {\"Description*\", type text}, {\"UOM*\", type text}, {\"Effectivity Date\", type text}, {\"Lifecycle Phase\", type text}, {\"Rev Release Date\", type text}, {\"Rev Incorp Date\", type text}, {\"Part Category*\", type text}, {\"Revision\", type text}, {\"Base Model\", type any}, {\"Sites\", type any}, {\"BOM.Item Description\", type text}, {\"BOM.Item Type\", type text}, {\"BOM.Rev\", type text}, {\"BOM.Lifecycle Phase\", type text}, {\"BOM.Qty\", type number}, {\"BOM.UOM\", type text}, {\"BOM.Find Num\", Int64.Type}, {\"BOM.Ref Des\", type any}, {\"BOM.BOM Notes\", type text}, {\"BOM.Optional\", type any}, {\"BOM.Mut Excl\", type any}, {\"BOM.Min Qty\", type any}, {\"BOM.Max Qty\", type any}, {\"BOM.Option Description\", type text}, {\"BOM.Configurator Rules\", type any}, {\"BOM.Appears on Quote\", type any}, {\"BOM.Configurator Pricing\", type any}, {\"BOM.Instance Description Flag\", type any}, {\"BOM.Non-English Description  \", type text}, {\"Manufacturers.Manufacturer Class\", type any}, {\"Manufacturers.AML Status\", type any}, {\"Manufacturers.Manufacturer Type\", type any}, {\"Manufacturers.Manufacturer Name\", type any}, {\"Manufacturers.MPN\", type any}, {\"Manufacturers.MPN Status\", type any}, {\"Manufacturers.Manufacturer Site\", type any}, {\"Manufacturers.Manufacturer City\", type any}, {\"Manufacturers.Manufacturer Country\", type any}, {\"Manufacturers.RoHS Compliant\", type any}, {\"Manufacturers.RoHS Exemptions\", type any}, {\"Manufacturers.REACH Compliant\", type any}, {\"Manufacturers.REACH Level\", type any}, {\"Manufacturers.Oracle Supplier ID\", type any}, {\"Manufacturers.Oracle Supplier Site ID\", type any}, {\"Manufacturers.Summary Compliance\", type any}, {\"Manufacturers.Mfr. Part Description\", type any}, {\"Manufacturers.Reference Notes\", type any}})\r\nin\r\n  #\"Changed column type\";\r\nshared #\"Transform file (2)\" = let\r\n  Source = (#\"Parameter (2)\" as binary) => let\r\n  Source = Excel.Workbook(#\"Parameter (2)\", null, true),\r\n  Navigation = Source{[Item = \"Sheet0\", Kind = \"Sheet\"]}[Data],\r\n  #\"Promoted headers\" = Table.PromoteHeaders(Navigation, [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"Level\", Int64.Type}, {\"Item Number*\", type text}, {\"Part Type*\", type text}, {\"Description*\", type text}, {\"UOM*\", type text}, {\"Effectivity Date\", type text}, {\"Lifecycle Phase\", type text}, {\"Rev Release Date\", type text}, {\"Rev Incorp Date\", type text}, {\"Part Category*\", type text}, {\"Revision\", type text}, {\"Base Model\", type any}, {\"Sites\", type any}, {\"BOM.Item Description\", type text}, {\"BOM.Item Type\", type text}, {\"BOM.Rev\", type text}, {\"BOM.Lifecycle Phase\", type text}, {\"BOM.Qty\", type number}, {\"BOM.UOM\", type text}, {\"BOM.Find Num\", Int64.Type}, {\"BOM.Ref Des\", type any}, {\"BOM.BOM Notes\", type text}, {\"BOM.Optional\", type any}, {\"BOM.Mut Excl\", type any}, {\"BOM.Min Qty\", type any}, {\"BOM.Max Qty\", type any}, {\"BOM.Option Description\", type text}, {\"BOM.Configurator Rules\", type any}, {\"BOM.Appears on Quote\", type any}, {\"BOM.Configurator Pricing\", type any}, {\"BOM.Instance Description Flag\", type any}, {\"BOM.Non-English Description  \", type text}, {\"Manufacturers.Manufacturer Class\", type any}, {\"Manufacturers.AML Status\", type any}, {\"Manufacturers.Manufacturer Type\", type any}, {\"Manufacturers.Manufacturer Name\", type any}, {\"Manufacturers.MPN\", type any}, {\"Manufacturers.MPN Status\", type any}, {\"Manufacturers.Manufacturer Site\", type any}, {\"Manufacturers.Manufacturer City\", type any}, {\"Manufacturers.Manufacturer Country\", type any}, {\"Manufacturers.RoHS Compliant\", type any}, {\"Manufacturers.RoHS Exemptions\", type any}, {\"Manufacturers.REACH Compliant\", type any}, {\"Manufacturers.REACH Level\", type any}, {\"Manufacturers.Oracle Supplier ID\", type any}, {\"Manufacturers.Oracle Supplier Site ID\", type any}, {\"Manufacturers.Summary Compliance\", type any}, {\"Manufacturers.Mfr. Part Description\", type any}, {\"Manufacturers.Reference Notes\", type any}})\r\nin\r\n  #\"Changed column type\"\r\nin\r\n  Source;\r\nshared #\"R-BOM Categories\" = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Name] = \"Categories_R-Parts.xlsx\"),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows\", each [Attributes]?[Hidden]? <> true),\r\n  #\"Invoke custom function\" = Table.AddColumn(#\"Filtered hidden files\", \"Transform file (3)\", each #\"Transform file (3)\"([Content])),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Invoke custom function\", {{\"Name\", \"Source.Name\"}}),\r\n  #\"Removed other columns\" = Table.SelectColumns(#\"Renamed columns\", {\"Source.Name\", \"Transform file (3)\"}),\r\n  #\"Expanded table column\" = Table.ExpandTableColumn(#\"Removed other columns\", \"Transform file (3)\", Table.ColumnNames(#\"Transform file (3)\"(#\"Sample file (3)\"))),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Expanded table column\", {{\"Source.Name\", type text}, {\"Item Number\", type text}, {\"Item Description\", type text}, {\"Qty\", Int64.Type}, {\"Assembly Group\", type text}}),\r\n  #\"Choose columns\" = Table.SelectColumns(#\"Changed column type\", {\"Item Number\", \"Item Description\", \"Assembly Group\"}),\r\n  #\"Renamed columns 1\" = Table.RenameColumns(#\"Choose columns\", {{\"Item Description\", \"Item Description Short\"}})\r\nin\r\n  #\"Renamed columns 1\";\r\nshared #\"Sample file (3)\" = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Name] = \"Categories_R-Parts.xlsx\"),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows\", each [Attributes]?[Hidden]? <> true),\r\n  Navigation = #\"Filtered hidden files\"{0}[Content]\r\nin\r\n  Navigation;\r\nshared #\"Parameter (3)\" = let\r\n  #\"Parameter (3)\" = #\"Sample file (3)\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type binary]\r\nin\r\n  #\"Parameter (3)\";\r\nshared #\"Transform Sample file (3)\" = let\r\n  Source = Excel.Workbook(#\"Parameter (3)\", null, true),\r\n  Navigation = Source{[Item = \"Tabelle1\", Kind = \"Table\"]}[Data],\r\n  #\"Changed column type\" = Table.TransformColumnTypes(Navigation, {{\"Item Number\", type text}, {\"Item Description\", type text}, {\"Qty\", Int64.Type}, {\"Assembly Group\", type text}})\r\nin\r\n  #\"Changed column type\";\r\nshared #\"Transform file (3)\" = let\r\n  Source = (#\"Parameter (3)\" as binary) => let\r\n  Source = Excel.Workbook(#\"Parameter (3)\", null, true),\r\n  Navigation = Source{[Item = \"Tabelle1\", Kind = \"Table\"]}[Data],\r\n  #\"Changed column type\" = Table.TransformColumnTypes(Navigation, {{\"Item Number\", type text}, {\"Item Description\", type text}, {\"Qty\", Int64.Type}, {\"Assembly Group\", type text}})\r\nin\r\n  #\"Changed column type\"\r\nin\r\n  Source;\r\nshared #\"Refurb_MayerFT old\" = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/sites/o365_group_excimer_operations_schem_exchange\", [ApiVersion = 15]),\r\n  // Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-Göttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n  #\"Filtered Rows\" = Table.SelectRows(Source, each [Name] = \"Bestände_Vyper1_TEST.xlsx\"),\r\n  #\"Invoke Custom Function1\" = Table.AddColumn(#\"Filtered Rows\", \"Transform file (4)\", each #\"Transform file (4)\"([Content])),\r\n  #\"Renamed Columns1\" = Table.RenameColumns(#\"Invoke Custom Function1\", {\"Name\", \"Source.Name\"}),\r\n  #\"Removed Other Columns1\" = Table.SelectColumns(#\"Renamed Columns1\", {\"Source.Name\", \"Transform file (4)\"}),\r\n  #\"Expanded Table Column1\" = Table.ExpandTableColumn(#\"Removed Other Columns1\", \"Transform file (4)\", Table.ColumnNames(#\"Transform file (4)\"(#\"Sample file (4)\"))),\r\n  #\"Removed Top Rows\" = Table.Skip(#\"Expanded Table Column1\", 1),\r\n  #\"Choose columns\" = Table.SelectColumns(#\"Removed Top Rows\", {\"Column1\", \"Column6\", \"Column7\", \"Column8\", \"Column9\", \"Column10\", \"Column11\", \"Column12\", \"Column13\", \"Column14\", \"Column15\", \"Column16\", \"Column17\", \"Column18\", \"Column19\", \"Column20\", \"Column21\", \"Column22\", \"Column23\", \"Column24\", \"Column25\", \"Column26\", \"Column27\", \"Column28\", \"Column29\", \"Column30\", \"Column31\", \"Column32\", \"Column33\", \"Column34\", \"Column35\", \"Column36\", \"Column37\", \"Column38\", \"Column39\", \"Column40\", \"Column41\", \"Column42\", \"Column43\", \"Column44\", \"Column45\", \"Column46\", \"Column47\", \"Column48\", \"Column49\", \"Column50\", \"Column51\", \"Column52\", \"Column53\", \"Column54\", \"Column55\", \"Column56\", \"Column57\", \"Column58\", \"Column59\", \"Column60\", \"Column61\", \"Column62\", \"Column63\", \"Column64\", \"Column65\", \"Column66\", \"Column67\", \"Column68\", \"Column69\", \"Column70\", \"Column71\", \"Column72\", \"Column73\", \"Column74\", \"Column75\", \"Column76\", \"Column77\", \"Column78\", \"Column79\", \"Column80\", \"Column81\", \"Column82\", \"Column83\", \"Column84\", \"Column85\", \"Column86\", \"Column87\", \"Column88\", \"Column89\", \"Column90\", \"Column91\", \"Column92\", \"Column93\", \"Column94\", \"Column95\", \"Column96\", \"Column97\", \"Column98\", \"Column99\", \"Column100\", \"Column101\", \"Column102\", \"Column103\", \"Column104\", \"Column105\", \"Column106\", \"Column107\", \"Column108\", \"Column109\", \"Column110\", \"Column111\", \"Column112\", \"Column113\", \"Column114\", \"Column115\", \"Column116\", \"Column117\", \"Column118\", \"Column119\", \"Column120\", \"Column121\", \"Column122\", \"Column123\", \"Column124\", \"Column125\", \"Column126\", \"Column127\", \"Column128\", \"Column129\", \"Column130\", \"Column131\", \"Column132\", \"Column133\", \"Column134\", \"Column135\", \"Column136\", \"Column137\", \"Column138\", \"Column139\", \"Column140\", \"Column141\", \"Column142\", \"Column143\", \"Column144\", \"Column145\", \"Column146\", \"Column147\", \"Column148\", \"Column149\", \"Column150\", \"Column151\", \"Column152\", \"Column153\", \"Column154\", \"Column155\", \"Column156\", \"Column157\", \"Column158\", \"Column159\", \"Column160\", \"Column161\", \"Column162\", \"Column163\", \"Column164\", \"Column165\", \"Column166\", \"Column167\", \"Column168\", \"Column169\", \"Column170\", \"Column171\", \"Column172\", \"Column173\", \"Column174\", \"Column175\", \"Column176\", \"Column177\", \"Column178\", \"Column179\", \"Column180\", \"Column181\", \"Column182\", \"Column183\", \"Column184\", \"Column185\", \"Column186\", \"Column187\", \"Column188\", \"Column189\", \"Column190\", \"Column191\", \"Column192\", \"Column193\", \"Column194\", \"Column195\", \"Column196\", \"Column197\", \"Column198\", \"Column199\", \"Column200\", \"Column201\", \"Column202\", \"Column203\", \"Column204\", \"Column205\", \"Column206\", \"Column207\", \"Column208\", \"Column209\", \"Column210\", \"Column211\", \"Column212\", \"Column213\", \"Column214\", \"Column215\", \"Column216\", \"Column217\", \"Column218\", \"Column219\", \"Column220\", \"Column221\", \"Column222\", \"Column223\", \"Column224\", \"Column225\", \"Column226\", \"Column227\", \"Column228\", \"Column229\", \"Column230\", \"Column231\", \"Column232\", \"Column233\", \"Column234\", \"Column235\", \"Column236\", \"Column237\", \"Column238\", \"Column239\", \"Column240\", \"Column241\", \"Column242\", \"Column243\", \"Column244\", \"Column245\", \"Column246\", \"Column247\", \"Column248\", \"Column249\", \"Column250\", \"Column251\", \"Column252\", \"Column253\", \"Column254\", \"Column255\", \"Column256\", \"Column257\", \"Column258\"}),\r\n  #\"Filtered rows\" = Table.SelectRows(#\"Choose columns\", each [Column1] <> null),\r\n  #\"Transposed Table\" = Table.Transpose(#\"Filtered rows\"),\r\n  #\"Replaced value\" = Table.ReplaceValue(#\"Transposed Table\", \"LP1264130\", \"1264130R\", Replacer.ReplaceValue, {\"Column91\"}),\r\n  #\"Promoted Headers\" = Table.PromoteHeaders(#\"Replaced value\", [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted Headers\", {{\"0 Bestellnummer\", type text}, {\"0 JOB\", type text}, {\"1116398R\", type text}, {\"1116431R\", type text}, {\"1116441R\", type text}, {\"1116443R\", type text}, {\"1116444R\", type text}, {\"1117312R\", type text}, {\"1117312RD\", type text}, {\"1117314R\", type text}, {\"1119080R\", type text}, {\"1124721R\", type text}, {\"1129493R\", type text}, {\"1130804R\", type text}, {\"1132232RD\", type text}, {\"1132234RD\", type text}, {\"1132388R\", type text}, {\"1136803R\", type text}, {\"1139754RD\", type text}, {\"1139974R\", type text}, {\"1139978R\", type text}, {\"1139979R\", type text}, {\"1139981R\", type text}, {\"1139982R\", type text}, {\"1139986R\", type text}, {\"1141510R\", type text}, {\"1147289R\", type text}, {\"1148065R\", type text}, {\"1167970R\", type text}, {\"1171395R\", type text}, {\"1171396R\", type text}, {\"1174788R\", type text}, {\"1174793RD\", type text}, {\"1177555R\", type text}, {\"1178136R\", type text}, {\"1180367R\", type text}, {\"1180637R\", type text}, {\"1181160R\", type text}, {\"1184220RD\", type text}, {\"1184345R\", type text}, {\"1184382R\", type text}, {\"1184405R\", type text}, {\"1185729R\", type text}, {\"1185730R\", type text}, {\"1186048R\", type text}, {\"1187340R\", type text}, {\"1196470R\", type text}, {\"1196480R\", type text}, {\"1196482R\", type text}, {\"1196675R\", type text}, {\"1196688R\", type text}, {\"1196690R\", type text}, {\"1196952R\", type text}, {\"1196954R\", type text}, {\"1196960R\", type text}, {\"1197101R\", type text}, {\"1197107R\", type text}, {\"1197735R\", type text}, {\"1197736R\", type text}, {\"1197738R\", type text}, {\"1197885R\", type text}, {\"1204030R\", type text}, {\"1204034R\", type text}, {\"1204257R\", type text}, {\"1204258R\", type text}, {\"1204259R\", type text}, {\"1204261R\", type text}, {\"1204308R\", type text}, {\"1214683R\", type text}, {\"1221450R\", type text}, {\"1223054R\", type text}, {\"1224459R\", type text}, {\"1224461R\", type text}, {\"1230160R\", type text}, {\"1234910R\", type text}, {\"1235200R\", type text}, {\"1235538R\", type text}, {\"1235543R\", type text}, {\"1235544R\", type text}, {\"1235545R\", type text}, {\"1235546R\", type text}, {\"1235568R\", type text}, {\"1235602R\", type text}, {\"1235835R\", type text}, {\"1235836R\", type text}, {\"1236235R\", type text}, {\"1263980R\", type text}, {\"1263990R\", type text}, {\"1263992R\", type text}, {\"1264130R\", type text}, {\"1265128R\", type text}, {\"1265129R\", type text}, {\"1277573R\", type text}, {\"1277578R\", type text}, {\"1278322R\", type text}, {\"1278337R\", type text}, {\"1278397R\", type text}, {\"1304630R\", type text}, {\"1304665R\", type text}, {\"1304976RD\", type text}, {\"1305354RD\", type text}, {\"1305357RD\", type text}, {\"1310025R\", type text}, {\"1310039R\", type text}, {\"1310040R\", type text}, {\"1310560R\", type text}, {\"1372433R\", type text}, {\"26339520R\", type text}, {\"263786R\", type text}, {\"265734R\", type text}, {\"340047R\", type text}, {\"340326R\", type text}, {\"340333R\", type text}, {\"340349R\", type text}, {\"340355R\", type text}, {\"340369R\", type text}, {\"341448R\", type text}, {\"341455R\", type text}, {\"341456R\", type text}, {\"342130R\", type text}, {\"342330R\", type text}, {\"361844R\", type text}, {\"362083R\", type text}, {\"362128R\", type text}, {\"362476R\", type text}, {\"363520R\", type text}, {\"363523R\", type text}, {\"364398R\", type text}, {\"36559501R\", type text}, {\"366410R\", type text}, {\"367708R\", type text}, {\"904607R\", type text}, {\"1369478R\", type text}, {\"1197889R\", type text}}),\r\n  #\"Unpivoted other columns\" = Table.UnpivotOtherColumns(#\"Changed column type\", {\"0 Bestellnummer\", \"0 JOB\"}, \"Attribute\", \"Value\"),\r\n  #\"Extracted Text Before Delimiter\" = Table.TransformColumns(#\"Unpivoted other columns\", {{\"Value\", each Text.BeforeDelimiter(_, \"g\"), type text}}),\r\n  #\"Changed Type1\" = Table.TransformColumnTypes(#\"Extracted Text Before Delimiter\", {{\"Value\", type number}}),\r\n  #\"Replaced Errors\" = Table.ReplaceErrorValues(#\"Changed Type1\", {{\"Value\", 0}}),\r\n  #\"Renamed Columns\" = Table.RenameColumns(#\"Replaced Errors\", {{\"Attribute\", \"Component\"}, {\"Value\", \"Qty Reclaimed\"}, {\"0 JOB\", \"Oracle JOB\"}, {\"0 Bestellnummer\", \"PO Bestellnummer\"}})\r\nin\r\n  #\"Renamed Columns\";\r\nshared #\"Sample file (4)\" = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/sites/o365_group_excimer_operations_schem_exchange\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Extension] = \".xlsx\" and [Name] = \"Bestände_Vyper1_TEST.xlsx\"),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows\", each [Attributes]?[Hidden]? <> true),\r\n  Navigation = #\"Filtered hidden files\"{0}[Content]\r\nin\r\n  Navigation;\r\nshared #\"Parameter (4)\" = let\r\n  #\"Parameter (4)\" = #\"Sample file (4)\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type binary]\r\nin\r\n  #\"Parameter (4)\";\r\nshared #\"Transform Sample file (4)\" = let\r\n  Source = Excel.Workbook(#\"Parameter (4)\", null, true),\r\n  Navigation = Source{[Item = \"Auslieferungen\", Kind = \"Sheet\"]}[Data]\r\nin\r\n  Navigation;\r\nshared #\"Transform file (4)\" = let\r\n  Source = (#\"Parameter (4)\" as binary) => let\r\n  Source = Excel.Workbook(#\"Parameter (4)\", null, true),\r\n  Navigation = Source{[Item = \"Auslieferungen\", Kind = \"Sheet\"]}[Data]\r\n\r\nin\r\n  Navigation\r\nin\r\n  Source;\r\nshared Disassembly_Data_Oracle = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-Göttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n  #\"Filtered Rows\" = Table.SelectRows(Source, each [Name] = \"Disassembly-Data.xlsx\"),\r\n  #\"Filtered Hidden Files1\" = Table.SelectRows(#\"Filtered Rows\", each [Attributes]?[Hidden]? <> true),\r\n  #\"Invoke Custom Function1\" = Table.AddColumn(#\"Filtered Hidden Files1\", \"Transform File from Disassembly_Data\", each #\"Transform File from Disassembly_Data\"([Content])),\r\n  #\"Renamed Columns1\" = Table.RenameColumns(#\"Invoke Custom Function1\", {\"Name\", \"Source.Name\"}),\r\n  #\"Removed Other Columns1\" = Table.SelectColumns(#\"Renamed Columns1\", {\"Source.Name\", \"Transform File from Disassembly_Data\"}),\r\n  #\"Expanded Table Column1\" = Table.ExpandTableColumn(#\"Removed Other Columns1\", \"Transform File from Disassembly_Data\", Table.ColumnNames(#\"Transform File from Disassembly_Data\"(#\"Sample File (7)\"))),\r\n  #\"Changed Type with Locale\" = Table.TransformColumnTypes(#\"Expanded Table Column1\", {{\"Component Cost Incurred loc\", Currency.Type}}, \"en-US\"),\r\n  #\"Changed Type\" = Table.TransformColumnTypes(#\"Changed Type with Locale\", {{\"Fiscal Quarter closed\", type text}, {\"Nachbuchung ? (x)\", type text}, {\"Job Start Quantity\", Int64.Type}, {\"Item Description\", type text}, {\"Item Number\", type text}, {\"Entity Description\", type text}, {\"Component Quantity Issued\", Int64.Type}, {\"Job Status\", type text}, {\"Class Code\", type text}, {\"Component Description\", type text}, {\"Component Number\", type text}, {\"Date Closed\", type date}, {\"Wip Entity Name\", type text}, {\"Owning Organization\", type text}}),\r\n  #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\", {\"Source.Name\"}),\r\n  #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns\", {{\"Owning Organization\", \"Site\"}, {\"Wip Entity Name\", \"Oracle WO\"}}),\r\n  #\"Filtered Rows1\" = Table.SelectRows(#\"Renamed Columns\", each [Oracle WO] <> null and [Oracle WO] <> \"\")\r\nin\r\n  #\"Filtered Rows1\";\r\nshared #\"Transform File from Disassembly_Data\" = let\r\n  Source = (#\"Sample File Parameter7\") => let\n        Source = Excel.Workbook(#\"Sample File Parameter7\", null, true),\n        shDissAssyData_Sheet = Source{[Item=\"shDissAssyData\",Kind=\"Sheet\"]}[Data],\n        #\"Promoted Headers\" = Table.PromoteHeaders(shDissAssyData_Sheet, [PromoteAllScalars=true])\n    in\n        #\"Promoted Headers\"\r\nin\r\n  Source;\r\nshared #\"Sample File (7)\" = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-Göttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n  #\"Filtered Rows\" = Table.SelectRows(Source, each [Name] = \"Disassembly-Data.xlsx\"),\r\n  Navigation1 = #\"Filtered Rows\"{0}[Content]\r\nin\r\n  Navigation1;\r\nshared Refurb_MayerFT = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/sites/o365_group_excimer_operations_schem_exchange\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Name] = \"Bestände_Vyper1_2021_03.xlsx\"),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows\", each [Attributes]?[Hidden]? <> true),\r\n  #\"Invoke custom function\" = Table.AddColumn(#\"Filtered hidden files\", \"Transform file (5)\", each #\"Transform file (5)\"([Content])),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Invoke custom function\", {{\"Name\", \"Source.Name\"}}),\r\n  #\"Removed other columns\" = Table.SelectColumns(#\"Renamed columns\", {\"Source.Name\", \"Transform file (5)\"}),\r\n  #\"Expanded table column\" = Table.ExpandTableColumn(#\"Removed other columns\", \"Transform file (5)\", Table.ColumnNames(#\"Transform file (5)\"(#\"Sample file (5)\"))),\r\n  #\"Removed columns\" = Table.RemoveColumns(#\"Expanded table column\", {\"Source.Name\", \"Column5\", \"Column1\"}),\r\n  #\"Promoted headers\" = Table.PromoteHeaders(#\"Removed columns\", [PromoteAllScalars = true]),\r\n  #\"Renamed columns 1\" = Table.RenameColumns(#\"Promoted headers\", {{\"Column1\", \"PO Bestellnummer\"}, {\"Column2\", \"Oracle Job\"}}),\r\n  #\"Removed top rows\" = Table.Skip(#\"Renamed columns 1\", 4),\r\n  #\"Unpivoted other columns\" = Table.UnpivotOtherColumns(#\"Removed top rows\", {\"PO Bestellnummer\", \"Oracle Job\"}, \"Attribute\", \"Value\"),\r\n  #\"Renamed columns 2\" = Table.RenameColumns(#\"Unpivoted other columns\", {{\"Attribute\", \"Component\"}, {\"Value\", \"Qty Reclaimed\"}}),\r\n  #\"Extracted text before delimiter\" = Table.TransformColumns(#\"Renamed columns 2\", {{\"Qty Reclaimed\", each Text.BeforeDelimiter(Text.From(_), \"g\", 0), type text}}),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Extracted text before delimiter\", {{\"Component\", type text}, {\"Oracle Job\", type text}, {\"PO Bestellnummer\", type text}, {\"Qty Reclaimed\", type number}}),\r\n  #\"Replaced errors\" = Table.ReplaceErrorValues(#\"Changed column type\", {{\"Qty Reclaimed\", 0}})\r\nin\r\n  #\"Replaced errors\";\r\nshared #\"Sample file (5)\" = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/sites/o365_group_excimer_operations_schem_exchange\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Name] = \"Bestände_Vyper1_2021_03.xlsx\"),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows\", each [Attributes]?[Hidden]? <> true),\r\n  Navigation = #\"Filtered hidden files\"{0}[Content]\r\nin\r\n  Navigation;\r\nshared #\"Parameter (5)\" = let\r\n  #\"Parameter (5)\" = #\"Sample file (5)\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type binary]\r\nin\r\n  #\"Parameter (5)\";\r\nshared #\"Transform Sample file (5)\" = let\r\n  Source = Excel.Workbook(#\"Parameter (5)\", null, true),\r\n  Navigation = Source{[Item = \"Auslieferungen_Neu\", Kind = \"Sheet\"]}[Data]\r\nin\r\n  Navigation;\r\nshared #\"Transform file (5)\" = let\r\n  Source = (#\"Parameter (5)\" as binary) => let\r\n  Source = Excel.Workbook(#\"Parameter (5)\", null, true),\r\n  Navigation = Source{[Item = \"Auslieferungen_Neu\", Kind = \"Sheet\"]}[Data]\r\nin\r\n  Navigation\r\nin\r\n  Source;\r\nshared #\"Sample file (6)\" = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each Text.Contains([Folder Path], \"R-BOMs\")),\r\n  #\"Filtered rows 1\" = Table.SelectRows(#\"Filtered rows\", each Text.StartsWith([Name], \"R-BOM_\")),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows 1\", each [Attributes]?[Hidden]? <> true),\r\n  Navigation = #\"Filtered hidden files\"{[Name = \"R-BOM_GEP_1162502D.xlsx\", #\"Folder Path\" = \"https://cohrinc.sharepoint.com/teams/Operations/Excimer-Göttingen/Manuf. Engineering/Shared Documents/Refurb - Salvage/R-BOMs/\"]}[Content]\r\nin\r\n  Navigation;\r\nshared #\"Parameter (6)\" = let\r\n  #\"Parameter (6)\" = #\"Sample file (6)\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type binary, BinaryIdentifier = #\"Sample file (6)\"]\r\nin\r\n  #\"Parameter (6)\";\r\nshared #\"Transform Sample file (6)\" = let\r\n  Source = Excel.Workbook(#\"Parameter (6)\", null, true),\r\n  Navigation = Source{[Item = \"Sheet0\", Kind = \"Sheet\"]}[Data],\r\n  #\"Promoted headers\" = Table.PromoteHeaders(Navigation, [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"Level\", Int64.Type}, {\"Item Number*\", type text}, {\"Part Type*\", type text}, {\"Description*\", type text}, {\"UOM*\", type text}, {\"Effectivity Date\", type text}, {\"Lifecycle Phase\", type text}, {\"Rev Release Date\", type text}, {\"Rev Incorp Date\", type text}, {\"Part Category*\", type text}, {\"Revision\", type text}, {\"Base Model\", type any}, {\"Sites\", type any}, {\"BOM.Item Description\", type text}, {\"BOM.Item Type\", type text}, {\"BOM.Rev\", type text}, {\"BOM.Lifecycle Phase\", type text}, {\"BOM.Qty\", type number}, {\"BOM.UOM\", type text}, {\"BOM.Find Num\", Int64.Type}, {\"BOM.Ref Des\", type any}, {\"BOM.BOM Notes\", type any}, {\"BOM.Optional\", type any}, {\"BOM.Mut Excl\", type any}, {\"BOM.Min Qty\", type any}, {\"BOM.Max Qty\", type any}, {\"BOM.Option Description\", type any}, {\"BOM.Configurator Rules\", type any}, {\"BOM.Appears on Quote\", type any}, {\"BOM.Configurator Pricing\", type any}, {\"BOM.Instance Description Flag\", type any}, {\"BOM.Non-English Description  \", type text}, {\"Manufacturers.Manufacturer Class\", type text}, {\"Manufacturers.AML Status\", type text}, {\"Manufacturers.Manufacturer Type\", type text}, {\"Manufacturers.Manufacturer Name\", type text}, {\"Manufacturers.MPN\", type text}, {\"Manufacturers.MPN Status\", type text}, {\"Manufacturers.Manufacturer Site\", type text}, {\"Manufacturers.Manufacturer City\", type any}, {\"Manufacturers.Manufacturer Country\", type any}, {\"Manufacturers.RoHS Compliant\", type text}, {\"Manufacturers.RoHS Exemptions\", Int64.Type}, {\"Manufacturers.REACH Compliant\", type text}, {\"Manufacturers.REACH Level\", Int64.Type}, {\"Manufacturers.Oracle Supplier ID\", type any}, {\"Manufacturers.Oracle Supplier Site ID\", type any}, {\"Manufacturers.Summary Compliance\", type any}, {\"Manufacturers.Mfr. Part Description\", type any}, {\"Manufacturers.Reference Notes\", type any}})\r\nin\r\n  #\"Changed column type\";\r\nshared #\"Transform file (6)\" = let\r\n  Source = (#\"Parameter (6)\" as binary) => let\r\n  Source = Excel.Workbook(#\"Parameter (6)\", null, true),\r\n  Navigation = Source{[Item = \"Sheet0\", Kind = \"Sheet\"]}[Data],\r\n  #\"Promoted headers\" = Table.PromoteHeaders(Navigation, [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"Level\", Int64.Type}, {\"Item Number*\", type text}, {\"Part Type*\", type text}, {\"Description*\", type text}, {\"UOM*\", type text}, {\"Effectivity Date\", type text}, {\"Lifecycle Phase\", type text}, {\"Rev Release Date\", type text}, {\"Rev Incorp Date\", type text}, {\"Part Category*\", type text}, {\"Revision\", type text}, {\"Base Model\", type any}, {\"Sites\", type any}, {\"BOM.Item Description\", type text}, {\"BOM.Item Type\", type text}, {\"BOM.Rev\", type text}, {\"BOM.Lifecycle Phase\", type text}, {\"BOM.Qty\", type number}, {\"BOM.UOM\", type text}, {\"BOM.Find Num\", Int64.Type}, {\"BOM.Ref Des\", type any}, {\"BOM.BOM Notes\", type any}, {\"BOM.Optional\", type any}, {\"BOM.Mut Excl\", type any}, {\"BOM.Min Qty\", type any}, {\"BOM.Max Qty\", type any}, {\"BOM.Option Description\", type any}, {\"BOM.Configurator Rules\", type any}, {\"BOM.Appears on Quote\", type any}, {\"BOM.Configurator Pricing\", type any}, {\"BOM.Instance Description Flag\", type any}, {\"BOM.Non-English Description  \", type text}, {\"Manufacturers.Manufacturer Class\", type text}, {\"Manufacturers.AML Status\", type text}, {\"Manufacturers.Manufacturer Type\", type text}, {\"Manufacturers.Manufacturer Name\", type text}, {\"Manufacturers.MPN\", type text}, {\"Manufacturers.MPN Status\", type text}, {\"Manufacturers.Manufacturer Site\", type text}, {\"Manufacturers.Manufacturer City\", type any}, {\"Manufacturers.Manufacturer Country\", type any}, {\"Manufacturers.RoHS Compliant\", type text}, {\"Manufacturers.RoHS Exemptions\", Int64.Type}, {\"Manufacturers.REACH Compliant\", type text}, {\"Manufacturers.REACH Level\", Int64.Type}, {\"Manufacturers.Oracle Supplier ID\", type any}, {\"Manufacturers.Oracle Supplier Site ID\", type any}, {\"Manufacturers.Summary Compliance\", type any}, {\"Manufacturers.Mfr. Part Description\", type any}, {\"Manufacturers.Reference Notes\", type any}})\r\nin\r\n  #\"Changed column type\"\r\nin\r\n  Source;\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[{\"id\":\"6e21f51a-2af4-4fc8-807b-4f8634e83dde\",\"name\":\"Transform file from R-BOM\",\"description\":null,\"parentId\":null,\"order\":0},{\"id\":\"23499644-9d80-42af-8c72-0556394010da\",\"name\":\"Helper queries\",\"description\":null,\"parentId\":\"6e21f51a-2af4-4fc8-807b-4f8634e83dde\",\"order\":0},{\"id\":\"8fc1ba9a-09c1-4314-9040-2fa6eaab9a4a\",\"name\":\"Transform file from R-BOM Revisions\",\"description\":null,\"parentId\":null,\"order\":0},{\"id\":\"bc999b51-8765-4c31-a6c9-18c8cd5f867e\",\"name\":\"Helper queries (2)\",\"description\":null,\"parentId\":\"8fc1ba9a-09c1-4314-9040-2fa6eaab9a4a\",\"order\":0},{\"id\":\"150171cc-4a14-450d-861b-89dbf135c936\",\"name\":\"Transform file from R-BOM Categories\",\"description\":null,\"parentId\":null,\"order\":0},{\"id\":\"dfc40b36-4eba-42e2-964b-b96e5d6c1eda\",\"name\":\"Helper queries (3)\",\"description\":null,\"parentId\":\"150171cc-4a14-450d-861b-89dbf135c936\",\"order\":0},{\"id\":\"d84258f9-0d20-419e-be78-f382c865c8ad\",\"name\":\"Transform file from Refurb_MayerFT\",\"description\":null,\"parentId\":null,\"order\":0},{\"id\":\"a09de42c-7fae-4cab-bc67-07695f2a1ebd\",\"name\":\"Helper queries (4)\",\"description\":null,\"parentId\":\"d84258f9-0d20-419e-be78-f382c865c8ad\",\"order\":0},{\"id\":\"39672e74-5be5-42f0-a64e-8581f8a41ee9\",\"name\":\"Transform file from Disassembly_Data\",\"description\":\"Load Oracle disassembly data\",\"parentId\":null,\"order\":0},{\"id\":\"cf164016-d7b1-44ff-9e4c-c6064ff2ef90\",\"name\":\"Transform file from Refurb_MayerFT New\",\"description\":null,\"parentId\":null,\"order\":0},{\"id\":\"c937eea0-51eb-45b7-9476-bf358bf4eca7\",\"name\":\"Helper queries (5)\",\"description\":null,\"parentId\":\"cf164016-d7b1-44ff-9e4c-c6064ff2ef90\",\"order\":0},{\"id\":\"f5b75aef-b39b-4391-bb1d-f8cf679eed3a\",\"name\":\"Transform file from R-BOMs\",\"description\":null,\"parentId\":null,\"order\":0},{\"id\":\"1ba111a0-5d49-4722-94fd-dc2919dae73f\",\"name\":\"Helper queries (6)\",\"description\":null,\"parentId\":\"f5b75aef-b39b-4391-bb1d-f8cf679eed3a\",\"order\":0}]"}],"entities":[{"$type":"LocalEntity","name":"R-BOM","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"R-BOM.csv"},"attributes":[{"name":"Source.Name","dataType":"string"},{"name":"Level","dataType":"int64"},{"name":"Item Number*","dataType":"string"},{"name":"Part Type*","dataType":"string"},{"name":"Description*","dataType":"string"},{"name":"BOM.Qty","dataType":"double"},{"name":"Revision","dataType":"string"},{"name":"Item Description Short","dataType":"string"},{"name":"Assembly Group","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-12T23:00:38.5071692+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/fea7cd4e-3077-4e1d-8a8b-471b558ee552/R-BOM.csv?snapshot=2022-06-12T23%3A00%3A38.4830918Z"}]},{"$type":"LocalEntity","name":"R-BOMs","description":"Disassembly R-BOMs.\nSharePoint Online - Excel Files.","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"R-BOMs.csv"},"attributes":[{"name":"Source.Name","dataType":"string"},{"name":"Level","dataType":"string"},{"name":"Item Number","dataType":"string"},{"name":"Description","dataType":"string"},{"name":"BOM.Qty","dataType":"double"},{"name":"Revision","dataType":"string"},{"name":"Assembly Group","dataType":"string"},{"name":"Org","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-12T23:00:40.5823084+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/fea7cd4e-3077-4e1d-8a8b-471b558ee552/R-BOMs.csv?snapshot=2022-06-12T23%3A00%3A40.5599024Z"}]},{"$type":"LocalEntity","name":"R-BOMs_Revisions","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"R-BOMs_Revisions.csv"},"attributes":[{"name":"Source.Name","dataType":"string"},{"name":"Level","dataType":"string"},{"name":"Item Number*","dataType":"string"},{"name":"Part Type*","dataType":"string"},{"name":"Description*","dataType":"string"},{"name":"Revision","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-12T23:00:30.7442388+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/fea7cd4e-3077-4e1d-8a8b-471b558ee552/R-BOMs_Revisions.csv?snapshot=2022-06-12T23%3A00%3A30.6935526Z"}]},{"$type":"LocalEntity","name":"Disassembly_Data_Oracle","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Disassembly_Data_Oracle.csv"},"attributes":[{"name":"Site","dataType":"string"},{"name":"Oracle WO","dataType":"string"},{"name":"Date Closed","dataType":"date"},{"name":"Class Code","dataType":"string"},{"name":"Job Status","dataType":"string"},{"name":"Component Number","dataType":"string"},{"name":"Component Description","dataType":"string"},{"name":"Component Quantity Issued","dataType":"int64"},{"name":"Component Cost Incurred loc","dataType":"decimal"},{"name":"Entity Description","dataType":"string"},{"name":"Item Number","dataType":"string"},{"name":"Item Description","dataType":"string"},{"name":"Job Start Quantity","dataType":"int64"},{"name":"Nachbuchung ? (x)","dataType":"string"},{"name":"Fiscal Quarter closed","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-12T23:00:44.3281895+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/fea7cd4e-3077-4e1d-8a8b-471b558ee552/Disassembly_Data_Oracle.csv?snapshot=2022-06-12T23%3A00%3A44.3037572Z"}]},{"$type":"LocalEntity","name":"Refurb_MayerFT","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Refurb_MayerFT.csv"},"attributes":[{"name":"PO Bestellnummer","dataType":"string"},{"name":"Oracle Job","dataType":"string"},{"name":"Component","dataType":"string"},{"name":"Qty Reclaimed","dataType":"double"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-12T23:00:32.8867659+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/fea7cd4e-3077-4e1d-8a8b-471b558ee552/Refurb_MayerFT.csv?snapshot=2022-06-12T23%3A00%3A32.8673079Z"}]}]}