{"name":"Flow_General Data Files","description":"Flow for general files, Assemblies, DimDates, Locations, Specs, Assembly Additional Details.","version":"1.0","culture":"en-US","modifiedTime":"2022-03-21T10:17:26.8763119+00:00","pbi:mashup":{"fastCombine":true,"allowNativeQueries":false,"queriesMetadata":{"Assemblies_Additional_Details":{"queryId":"b3d65c0b-2110-490d-b0f5-77e0887df915","queryName":"Assemblies_Additional_Details","queryGroupId":"719944be-8b04-4531-b684-88caf8948e62"},"parToken":{"queryId":"742aa80f-fbd4-4291-938b-dc8df06d6274","queryName":"parToken"},"Specs_VHP_Tube-FinalTest":{"queryId":"d70ea552-021e-4614-992f-0e2d5bdab34c","queryName":"Specs_VHP_Tube-FinalTest","loadEnabled":true},"Specs_ASSP Assembly":{"queryId":"a7897dc5-943e-428b-a61e-d637d74fa4e8","queryName":"Specs_ASSP Assembly","loadEnabled":true},"Specs_Cryo":{"queryId":"a59421b6-f527-4661-9036-5155143a8050","queryName":"Specs_Cryo","loadEnabled":true},"DimDates":{"queryId":"ef53517f-23c2-4672-a851-631d289f6529","queryName":"DimDates","loadEnabled":true},"Location_Fabs":{"queryId":"46fba9e0-c408-435b-85be-5d32183d4611","queryName":"Location_Fabs","loadEnabled":true},"Location_Sites":{"queryId":"f237cad8-458a-45fc-936c-14d7c51fe316","queryName":"Location_Sites","loadEnabled":true},"Transform Sample file (2)":{"queryId":"a94a49ed-f4d1-4da7-a8ef-ee67ff26f096","queryName":"Transform Sample file (2)","queryGroupId":"a9f787c3-5836-4971-a87f-abb5a3f0c08f"},"Sample file (2)":{"queryId":"933d374b-3abb-475e-879f-ff8f0090bcc6","queryName":"Sample file (2)","queryGroupId":"0d9c8663-2391-4f39-be01-308370107f54"},"Parameter (2)":{"queryId":"7346b28b-baa0-4996-918f-cb0cba55a8c0","queryName":"Parameter (2)","queryGroupId":"0d9c8663-2391-4f39-be01-308370107f54"},"Transform file (2)":{"queryId":"0d10479f-3ef0-4e84-a8c9-48e8b8689411","queryName":"Transform file (2)","queryGroupId":"0d9c8663-2391-4f39-be01-308370107f54"},"Transform Sample file (3)":{"queryId":"a1bf7abd-e134-4ad4-a5a0-d4df84899a4c","queryName":"Transform Sample file (3)","queryGroupId":"0eeb2670-ad87-44b4-b1db-b4803aefb3d5"},"Sample file (3)":{"queryId":"14697d14-435d-464b-8cad-6eaaa378a6e1","queryName":"Sample file (3)","queryGroupId":"04ec3c9c-05c8-4eca-bc0c-a0da46a77ec0"},"Parameter (3)":{"queryId":"c6aebaa2-08dd-4acc-a7ce-d68534ace7e5","queryName":"Parameter (3)","queryGroupId":"04ec3c9c-05c8-4eca-bc0c-a0da46a77ec0"},"Transform file (3)":{"queryId":"56d2783a-11e1-49aa-97ca-74d2f5ac543f","queryName":"Transform file (3)","queryGroupId":"04ec3c9c-05c8-4eca-bc0c-a0da46a77ec0"},"Transform Sample file (4)":{"queryId":"c1f61ed3-0474-42d4-8e7d-94dcf02025e8","queryName":"Transform Sample file (4)","queryGroupId":"3a8dfb1f-b104-4f8e-967d-ed50925bbcf0"},"Sample file (4)":{"queryId":"eaa386c4-b123-4ba0-b5f9-78c724329b2b","queryName":"Sample file (4)","queryGroupId":"722f712a-503f-41e5-97a6-ccb4688e96e8"},"Parameter (4)":{"queryId":"3ab6c41b-125b-4367-8074-e33d91769b6c","queryName":"Parameter (4)","queryGroupId":"722f712a-503f-41e5-97a6-ccb4688e96e8"},"Transform file (4)":{"queryId":"0383a724-6dcf-4537-a9f4-c0601013bfd4","queryName":"Transform file (4)","queryGroupId":"722f712a-503f-41e5-97a6-ccb4688e96e8"},"Transform Sample file (5)":{"queryId":"e2e1fa1b-5454-4513-a6e8-d8eeb16cdc06","queryName":"Transform Sample file (5)","queryGroupId":"7e966377-fc38-4fca-a6a6-819bd13c179c"},"Sample file (5)":{"queryId":"34cede7c-15cb-4010-bed8-5796ccbdda6b","queryName":"Sample file (5)","queryGroupId":"5839e6a6-69c8-4ec7-b40c-94762c590f5c"},"Parameter (5)":{"queryId":"fd3e56df-afca-4794-90c1-39de6b73f4f7","queryName":"Parameter (5)","queryGroupId":"5839e6a6-69c8-4ec7-b40c-94762c590f5c"},"Transform file (5)":{"queryId":"023de718-03c6-4d42-8ea5-e2ba6bb1d5d1","queryName":"Transform file (5)","queryGroupId":"5839e6a6-69c8-4ec7-b40c-94762c590f5c"},"Assemblies-VHP-API":{"queryId":"c11768db-d655-4fb5-875a-18ff566d8e78","queryName":"Assemblies-VHP-API","queryGroupId":"719944be-8b04-4531-b684-88caf8948e62"},"Assemblies-MP-API":{"queryId":"32cb9081-f876-45f2-9af9-f044da8c429b","queryName":"Assemblies-MP-API","queryGroupId":"719944be-8b04-4531-b684-88caf8948e62"},"Assemblies-LP-API":{"queryId":"4eee7d46-854d-4d23-a3df-49d6714ce90d","queryName":"Assemblies-LP-API","queryGroupId":"719944be-8b04-4531-b684-88caf8948e62"},"Assemblies-BDS-API":{"queryId":"27e45285-ee73-4be6-822c-8e223f723c18","queryName":"Assemblies-BDS-API","queryGroupId":"719944be-8b04-4531-b684-88caf8948e62"},"Cumulus_Assemblies":{"queryId":"c73d3405-98b2-4f1f-9546-aa332268b3b2","queryName":"Cumulus_Assemblies","loadEnabled":true},"Sample file (6)":{"queryId":"701a974e-b9c7-4d81-b855-ca30a4c99380","queryName":"Sample file (6)","queryGroupId":"17eba0d3-cc81-4bc7-a962-302e58d4879f"},"Parameter (6)":{"queryId":"af8fbb4b-ce49-4bbf-8fc3-63c56c636af0","queryName":"Parameter (6)","queryGroupId":"17eba0d3-cc81-4bc7-a962-302e58d4879f"},"Transform Sample file (6)":{"queryId":"22ed540e-ae14-4384-9f66-b503328c2712","queryName":"Transform Sample file (6)","queryGroupId":"8d02fddc-48c6-441f-92e2-0e3d3295117f"},"Transform file (6)":{"queryId":"71ef481b-ec04-4169-a653-18b9a4db7659","queryName":"Transform file (6)","queryGroupId":"17eba0d3-cc81-4bc7-a962-302e58d4879f"},"Cumulus_Assemblies_nonOracle":{"queryId":"775c79cf-e7ad-4f8a-98cc-135b4bd39440","queryName":"Cumulus_Assemblies_nonOracle","loadEnabled":true},"Cumulus_Assy_Tags":{"queryId":"f057c35b-085f-4d9b-8601-a709e63dd613","queryName":"Cumulus_Assy_Tags","loadEnabled":true},"Assemblies-Optic-API":{"queryId":"eb6132e3-a508-428a-94ef-55b9e9ad96b4","queryName":"Assemblies-Optic-API","queryGroupId":"719944be-8b04-4531-b684-88caf8948e62"},"Assemblies-General-API":{"queryId":"7a737b43-3e5e-42fd-a6ac-fccd877633be","queryName":"Assemblies-General-API","queryGroupId":"719944be-8b04-4531-b684-88caf8948e62"},"WIP_Completion_Status":{"queryId":"87061425-9ca1-4154-aac7-fb23c39eb7d5","queryName":"WIP_Completion_Status","loadEnabled":true},"Cumulus_Attribute-MainsPower":{"queryId":"e7195303-6c52-4a57-8536-dcb1c01bfe42","queryName":"Cumulus_Attribute-MainsPower","loadEnabled":true},"Cumulus_ET-LDU_Testbeds":{"queryId":"c4331139-84c3-480b-a690-8c260fa1b1b6","queryName":"Cumulus_ET-LDU_Testbeds","loadEnabled":true},"Sample file":{"queryId":"6da14d2a-cfbc-4c5c-b2a1-cac61bc0bc28","queryName":"Sample file","queryGroupId":"caa68850-1c41-4387-8d34-92a3e5e9613a"},"Parameter":{"queryId":"a3ad8775-80f2-46ca-b84a-53d0d43ccf67","queryName":"Parameter","queryGroupId":"caa68850-1c41-4387-8d34-92a3e5e9613a"},"Transform Sample file":{"queryId":"b07b9b6c-5377-449b-9387-9f580eeb5148","queryName":"Transform Sample file","queryGroupId":"cd29e21a-0788-4b7d-a13d-47c4d2a5d39f"},"Transform file":{"queryId":"f2c2cd8d-f1ba-4b5d-9915-966b55729f6f","queryName":"Transform file","queryGroupId":"caa68850-1c41-4387-8d34-92a3e5e9613a"}},"document":"section Section1;\r\nshared Assemblies_Additional_Details = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Name] = \"Assemblies_Additional_Details.xlsx\"),\r\n  #\"Invoke custom function\" = Table.AddColumn(#\"Filtered rows\", \"Transform file (2)\", each #\"Transform file (2)\"([Content])),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Invoke custom function\", {{\"Name\", \"Source.Name\"}}),\r\n  #\"Removed other columns\" = Table.SelectColumns(#\"Renamed columns\", {\"Source.Name\", \"Transform file (2)\"}),\r\n  #\"Expanded table column\" = Table.ExpandTableColumn(#\"Removed other columns\", \"Transform file (2)\", Table.ColumnNames(#\"Transform file (2)\"(#\"Sample file (2)\"))),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Expanded table column\", {{\"Column1\", type text}, {\"Column2\", type text}, {\"Column3\", type text}, {\"Column4\", type text}, {\"Column5\", type text}, {\"Column6\", type text}}),\r\n  #\"Promoted headers\" = Table.PromoteHeaders(#\"Changed column type\", [PromoteAllScalars = true]),\r\n  #\"Renamed columns 1\" = Table.RenameColumns(#\"Promoted headers\", {{\"Assemblies_Additional_Details.xlsx\", \"File Name\"}}),\r\n  #\"Changed column type 2\" = Table.TransformColumnTypes(#\"Renamed columns 1\", {{\"Part Number\", type text}, {\"Labor Seq1 (h)\", type number}, {\"Labor Seq2 (h)\", type number}, {\"Labor Seq3 (h)\", type number}, {\"Labor Seq4 (h)\", type number}})\r\nin\r\n  #\"Changed column type 2\";\r\nshared parToken = let\r\n  parToken = \"Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6ImpTMVhvMU9XRGpfNTJ2YndHTmd2UU8yVnpNYyIsImtpZCI6ImpTMVhvMU9XRGpfNTJ2YndHTmd2UU8yVnpNYyJ9.eyJhdWQiOiJodHRwczovL2NvaHJpbmMub25taWNyb3NvZnQuY29tL0N1bXVsdXNBUEkiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC8yZmFjN2NkZC03ZjY3LTQzNjItOTBmMi0zNThiZGJiOGY4MTIvIiwiaWF0IjoxNjQ3ODU2NjQ4LCJuYmYiOjE2NDc4NTY2NDgsImV4cCI6MTY0Nzg2MjE4MCwiYWNyIjoiMSIsImFpbyI6IkUyWmdZRkRpZXlXWCs1MnRibEhmRXQybUNPNFB4MHArMlpwZVdoeHRQVDFNSW1GUjNUOEEiLCJhbXIiOlsid2lhIl0sImFwcGlkIjoiZmJkNWMxM2EtNWM4MC00YWRmLWFkZGItZDAzMDRjMTJjZjJiIiwiYXBwaWRhY3IiOiIwIiwiZmFtaWx5X25hbWUiOiJBbGJlcnMiLCJnaXZlbl9uYW1lIjoiRGFuaWVsIiwiaXBhZGRyIjoiODcuMTQ4LjE1NC4zNiIsIm5hbWUiOiJBbGJlcnMsIERhbmllbCIsIm9pZCI6Ijg0ZjBkOGY2LTEyYTEtNDlmZi05NTNiLTA3NTk3OTk1NzQyMSIsIm9ucHJlbV9zaWQiOiJTLTEtNS0yMS0xOTU3OTk0NDg4LTE4NDQyMzc2MTUtMTgwMTY3NDUzMS0zMTU0NSIsInJoIjoiMC5BVmtBM1h5c0wyZF9Za09ROGpXTDI3ajRFb09GamJGYUg2eE5sa2Fud25yOTBEZFpBSVEuIiwic2NwIjoidXNlcl9pbXBlcnNvbmF0aW9uIiwic3ViIjoic0xIYU9RNjQ1TDJCY1BkUW01ZzBLTTlnLXpObWlJenk4c1NIb2hGcVNZcyIsInRpZCI6IjJmYWM3Y2RkLTdmNjctNDM2Mi05MGYyLTM1OGJkYmI4ZjgxMiIsInVuaXF1ZV9uYW1lIjoiRGFuaWVsLkFsYmVyc0Bjb2hlcmVudC5jb20iLCJ1cG4iOiJEYW5pZWwuQWxiZXJzQGNvaGVyZW50LmNvbSIsInV0aSI6IjExUzVYTFNROVVTM2FRbENuUkFqQVEiLCJ2ZXIiOiIxLjAifQ.BZZBrRSnPpNC5WTcXUznyKomMZM3uSRExIGxDj-29wRnK8_JMF6gXAH53d4bvCExnlfk3e5uwrcGpzoajAW-QR5kRhuS3n2abKuaxaha3Be26n7cuBY9gnmzXAZ5hmqmwNz9id-yqGOrtPkQyHgUREON36OaDbjy0dRZ2M0cGfdR8ZwUnN-JV5P10xnNSA7bkUbu6wDOrJLSEkp_lW5vVZqHm2k6yR7tbb6oF3W4O3xrsbXy4OzOSo3ZUG2VzZkb5IFt39TTeANUu2-n5Ca5xgllfJ0JIFW_Ik0pZjOlp_cD75cpHVS-NW1dHcz2gJMxCgwDxOZygfigjiOE8X6UUg\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type text]\r\nin\r\n  parToken;\r\nshared #\"Specs_VHP_Tube-FinalTest\" = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Name] = \"Specs_VHP_Tube-FinalTest.xlsx\"),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows\", each [Attributes]?[Hidden]? <> true),\r\n  #\"Invoke custom function\" = Table.AddColumn(#\"Filtered hidden files\", \"Transform file (3)\", each #\"Transform file (3)\"([Content])),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Invoke custom function\", {{\"Name\", \"Source.Name\"}}),\r\n  #\"Removed other columns\" = Table.SelectColumns(#\"Renamed columns\", {\"Source.Name\", \"Transform file (3)\"}),\r\n  #\"Expanded table column\" = Table.ExpandTableColumn(#\"Removed other columns\", \"Transform file (3)\", Table.ColumnNames(#\"Transform file (3)\"(#\"Sample file (3)\"))),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Expanded table column\", {{\"Source.Name\", type text}, {\"Part Number\", type text}, {\"Part Description\", type text}, {\"BW FWHM SA LSL (mm)\", type number}, {\"BW FWHM SA USL (mm)\", type number}, {\"BW FWHM LA LSL (mm)\", Int64.Type}, {\"BW FWHM LA USL (mm)\", Int64.Type}, {\"BW 1/e² SA LSL (mm)\", Int64.Type}, {\"BW 1/e² SA USL (mm)\", Int64.Type}, {\"BW 1/e² LA LSL (mm)\", Int64.Type}, {\"BW 1/e² LA USL (mm)\", Int64.Type}, {\"Beam Asym. SA LSL (%)\", Int64.Type}, {\"Beam Asym. SA USL (%)\", Int64.Type}, {\"Beam Asym. LA LSL (%)\", Int64.Type}, {\"Beam Asym. LA USL (%)\", Int64.Type}, {\"Divergency SA LSL (mrad)\", Int64.Type}, {\"Divergency SA USL (mrad)\", type number}, {\"Divergency LA LSL (mrad)\", Int64.Type}, {\"Divergency LA USL (mrad)\", type number}, {\"Beam Point. Stab. SA LSL (mrad)\", Int64.Type}, {\"Beam Point. Stab. SA USL (mrad)\", type number}, {\"Beam Point. Stab. LA LSL (mrad)\", Int64.Type}, {\"Beam Point. Stab. LA USL (mrad)\", type number}, {\"Beam Pos. Stab. SA LSL (mm)\", type number}, {\"Beam Pos. Stab. SA USL (mm)\", type number}, {\"Beam Pos. Stab. LA LSL (mm)\", type number}, {\"Beam Pos. Stab. LA USL (mm)\", type number}}),\r\n  #\"Removed columns\" = Table.RemoveColumns(#\"Changed column type\", {\"Source.Name\"}),\r\n  #\"Changed column type 1\" = Table.TransformColumnTypes(#\"Removed columns\", {{\"HV Start LSL (kV)\", type number}, {\"HV Start USL (kV)\", type number}, {\"HV Rise LSL (V)\", type number}, {\"HV Rise USL (V)\", type number}, {\"Sigma Start LSL (%)\", type number}, {\"Sigma Start USL (%)\", type number}, {\"Sigma End LSL (%)\", type number}, {\"Sigma End USL (%)\", type number}, {\"Sigma Average LSL (%)\", type number}, {\"Sigma Average USL (%)\", type number}, {\"Sigma Max LSL (%)\", type number}, {\"Sigma Max USL (%)\", type number}, {\"2nd Hump Start LSL (%)\", type number}, {\"2nd Hump Start USL (%)\", type number}, {\"2nd Hump End LSL (%)\", type number}, {\"2nd Hump End USL (%)\", type number}, {\"Transmission Loss OC P3 LSL (%/10Mio Pulse)\", type number}, {\"Transmission Loss OC P3 USL (%/10Mio Pulse)\", type number}, {\"Transmission Loss HR P3 LSL (%/10Mio Pulse)\", type number}, {\"Transmission Loss HR P3 USL (%/10Mio Pulse)\", type number}, {\"User Counter LSL (Mio. Pulses)\", type number}, {\"User Counter USL (Mio. Pulses)\", type number}, {\"10Mio Run HV Start LSL (kV)\", type number}, {\"10Mio Run HV Start USL (kV)\", type number}, {\"10Mio Run E Difference LSL (%)\", type number}, {\"10Mio Run E Difference USL (%)\", type number}, {\"75 Mio Run HV Start LSL (kV)\", type number}, {\"75 Mio Run HV Start USL (kV)\", type number}, {\"75 Mio Run HV Rise LSL (V)\", type number}, {\"75 Mio Run HV Rise USL (V)\", type number}, {\"75 Mio Run Sigma Start LSL (%)\", type number}, {\"75 Mio Run Sigma Start USL (%)\", type number}, {\"75 Mio Run Sigma Max Internal LSL (%)\", type number}, {\"75 Mio Run Sigma Max Internal USL (%)\", type number}, {\"Divergency SA End LSL (mrad)\", type number}, {\"Divergency SA End USL (mrad)\", type number}, {\"User Counter Target (Mio. Pulses)\", Int64.Type}}),\r\n  #\"Choose columns\" = Table.SelectColumns(#\"Changed column type 1\", {\"Part Number\", \"Part Description\", \"BW FWHM SA LSL (mm)\", \"BW FWHM SA USL (mm)\", \"BW FWHM LA LSL (mm)\", \"BW FWHM LA USL (mm)\", \"BW 1/e² SA LSL (mm)\", \"BW 1/e² SA USL (mm)\", \"BW 1/e² LA LSL (mm)\", \"BW 1/e² LA USL (mm)\", \"Beam Asym. SA LSL (%)\", \"Beam Asym. SA USL (%)\", \"Beam Asym. LA LSL (%)\", \"Beam Asym. LA USL (%)\", \"Divergency SA LSL (mrad)\", \"Divergency SA USL (mrad)\", \"Divergency LA LSL (mrad)\", \"Divergency LA USL (mrad)\", \"Beam Point. Stab. SA LSL (mrad)\", \"Beam Point. Stab. SA USL (mrad)\", \"Beam Point. Stab. LA LSL (mrad)\", \"Beam Point. Stab. LA USL (mrad)\", \"Beam Pos. Stab. SA LSL (mm)\", \"Beam Pos. Stab. SA USL (mm)\", \"Beam Pos. Stab. LA LSL (mm)\", \"Beam Pos. Stab. LA USL (mm)\", \"HV Start LSL (kV)\", \"HV Start USL (kV)\", \"HV Rise LSL (V)\", \"HV Rise USL (V)\", \"Sigma Start LSL (%)\", \"Sigma Start USL (%)\", \"Sigma End LSL (%)\", \"Sigma End USL (%)\", \"Sigma Average LSL (%)\", \"Sigma Average USL (%)\", \"Sigma Max LSL (%)\", \"Sigma Max USL (%)\", \"2nd Hump Start LSL (%)\", \"2nd Hump Start USL (%)\", \"2nd Hump End LSL (%)\", \"2nd Hump End USL (%)\", \"Transmission Loss OC P3 LSL (%/10Mio Pulse)\", \"Transmission Loss OC P3 USL (%/10Mio Pulse)\", \"Transmission Loss HR P3 LSL (%/10Mio Pulse)\", \"Transmission Loss HR P3 USL (%/10Mio Pulse)\", \"User Counter LSL (Mio. Pulses)\", \"User Counter USL (Mio. Pulses)\", \"10Mio Run HV Start LSL (kV)\", \"10Mio Run HV Start USL (kV)\", \"10Mio Run E Difference LSL (%)\", \"10Mio Run E Difference USL (%)\", \"75 Mio Run HV Start LSL (kV)\", \"75 Mio Run HV Start USL (kV)\", \"75 Mio Run HV Rise LSL (V)\", \"75 Mio Run HV Rise USL (V)\", \"75 Mio Run Sigma Start LSL (%)\", \"75 Mio Run Sigma Start USL (%)\", \"75 Mio Run Sigma Max Internal LSL (%)\", \"75 Mio Run Sigma Max Internal USL (%)\", \"Divergency SA End LSL (mrad)\", \"Divergency SA End USL (mrad)\", \"User Counter Target (Mio. Pulses)\"})\r\nin\r\n  #\"Choose columns\";\r\nshared #\"Specs_ASSP Assembly\" = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Name] = \"Specs_ASSP SPC.xlsx\"),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows\", each [Attributes]?[Hidden]? <> true),\r\n  #\"Invoke custom function\" = Table.AddColumn(#\"Filtered hidden files\", \"Transform file (6)\", each #\"Transform file (6)\"([Content])),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Invoke custom function\", {{\"Name\", \"Source.Name\"}}),\r\n  #\"Removed other columns\" = Table.SelectColumns(#\"Renamed columns\", {\"Source.Name\", \"Transform file (6)\"}),\r\n  #\"Expanded table column\" = Table.ExpandTableColumn(#\"Removed other columns\", \"Transform file (6)\", Table.ColumnNames(#\"Transform file (6)\"(#\"Sample file (6)\"))),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Expanded table column\", {{\"Source.Name\", type text}, {\"Part Number\", type text}, {\"Part Description\", type text}, {\"Capacity C0 LSL (nF)\", Int64.Type}, {\"Capacity C0 USL (nF)\", Int64.Type}, {\"Hold Time MA LSL (us)\", type number}, {\"Hold Time MA USL (us)\", type number}, {\"Hold Time MI LSL (us)\", Int64.Type}, {\"Hold Time MI USL (us)\", Int64.Type}, {\"Fall Time Negative Edge UCp LSL (ns)\", Int64.Type}, {\"Fall Time Negative Edge UCp USL (ns)\", Int64.Type}, {\"Transfer Time LSL (us)\", type number}, {\"Transfer Time USL (us)\", type number}, {\"Negative Voltage C1 LSL (kV)\", Int64.Type}, {\"Negative Voltage C1 USL (kV)\", Int64.Type}, {\"Negative Voltage Cp LSL (kV)\", Int64.Type}, {\"Negative Voltage Cp USL (kV)\", Int64.Type}, {\"Negative Voltage IGBT LSL (V)\", Int64.Type}, {\"Negative Voltage IGBT USL (V)\", Int64.Type}}),\r\n  #\"Choose columns\" = Table.SelectColumns(#\"Changed column type\", {\"Part Number\", \"Part Description\", \"Capacity C0 LSL (nF)\", \"Capacity C0 USL (nF)\", \"Hold Time MA LSL (us)\", \"Hold Time MA USL (us)\", \"Hold Time MI LSL (us)\", \"Hold Time MI USL (us)\", \"Fall Time Negative Edge UCp LSL (ns)\", \"Fall Time Negative Edge UCp USL (ns)\", \"Transfer Time LSL (us)\", \"Transfer Time USL (us)\", \"Negative Voltage C1 LSL (kV)\", \"Negative Voltage C1 USL (kV)\", \"Negative Voltage Cp LSL (kV)\", \"Negative Voltage Cp USL (kV)\", \"Negative Voltage IGBT LSL (V)\", \"Negative Voltage IGBT USL (V)\"})\r\nin\r\n  #\"Choose columns\";\r\nshared Specs_Cryo = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Extension] = \".xlsx\" and [Name] = \"Specs_Cryo_SPC.xlsx\"),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows\", each [Attributes]?[Hidden]? <> true),\r\n  #\"Invoke custom function\" = Table.AddColumn(#\"Filtered hidden files\", \"Transform file\", each #\"Transform file\"([Content])),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Invoke custom function\", {{\"Name\", \"Source.Name\"}}),\r\n  #\"Removed other columns\" = Table.SelectColumns(#\"Renamed columns\", {\"Source.Name\", \"Transform file\"}),\r\n  #\"Expanded table column\" = Table.ExpandTableColumn(#\"Removed other columns\", \"Transform file\", Table.ColumnNames(#\"Transform file\"(#\"Sample file\"))),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Expanded table column\", {{\"Source.Name\", type text}, {\"Part Number\", type text}, {\"Part Description\", type text}, {\"leakage rate sniffer USL (mbar*l/s)\", type number}, {\"Helium background USL (mbar*l/s)\", type number}, {\"heating resistance USL (Ω)\", type number}, {\"heating resistance LSL (Ω)\", type number}, {\"Gas Pressure Drop USL (mbar/12 h)\", Int64.Type}, {\"Gas Pressure Drop LSL (mbar/12 h)\", Int64.Type}, {\"Gas Pressure Drop USL (mbar/24 h)\", Int64.Type}, {\"Gas Pressure Drop LSL (mbar/24 h)\", Int64.Type}, {\"leakage rate USL (mbar*l/s)\", type number}, {\"leakage rate LSL (mbar*l/s)\", Int64.Type}, {\"water pressure drop USL (mbar/h)\", Int64.Type}, {\"cool down time USL (min)\", Int64.Type}, {\"cool down time LSL (min)\", Int64.Type}}),\r\n  #\"Choose columns\" = Table.SelectColumns(#\"Changed column type\", {\"Part Number\", \"Part Description\", \"leakage rate sniffer USL (mbar*l/s)\", \"Helium background USL (mbar*l/s)\", \"heating resistance USL (Ω)\", \"heating resistance LSL (Ω)\", \"Gas Pressure Drop USL (mbar/12 h)\", \"Gas Pressure Drop LSL (mbar/12 h)\", \"Gas Pressure Drop USL (mbar/24 h)\", \"Gas Pressure Drop LSL (mbar/24 h)\", \"leakage rate USL (mbar*l/s)\", \"leakage rate LSL (mbar*l/s)\", \"water pressure drop USL (mbar/h)\", \"cool down time USL (min)\", \"cool down time LSL (min)\"})\r\nin\r\n  #\"Choose columns\";\r\nshared DimDates = let\r\n  StartDate = #date(2010, 1, 1),\r\n  YearsToGenerate = 14,\r\n  FiscalYearStartMonth = 10,\r\n  BaseList = List.Dates(\r\n    StartDate,\r\n    YearsToGenerate*366,\r\n    #duration(1,0,0,0)\r\n  ),\r\n  #\"Converted to table\" = Table.FromList(BaseList, Splitter.SplitByNothing(), null, null, ExtraValues.Error),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Converted to table\", {{\"Column1\", type date}}),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Changed column type\", {{\"Column1\", \"Date\"}}),\r\n  #\"Inserted year\" = Table.AddColumn(#\"Renamed columns\", \"Year\", each Date.Year([Date]), type number),\r\n  #\"Inserted month\" = Table.AddColumn(#\"Inserted year\", \"Month\", each Date.Month([Date]), type number),\r\n  #\"Inserted month name\" = Table.AddColumn(#\"Inserted month\", \"Month name\", each Date.MonthName([Date]), type text),\r\n  #\"Inserted quarter\" = Table.AddColumn(#\"Inserted month name\", \"Quarter\", each Date.QuarterOfYear([Date]), type number),\r\n  #\"Inserted week of year\" = Table.TransformColumnTypes(Table.AddColumn(#\"Inserted quarter\", \"Week of year\", each Date.WeekOfYear([Date], Day.Monday)), {{\"Week of year\", type number}}),\r\n  #\"Inserted week of month\" = Table.AddColumn(#\"Inserted week of year\", \"Week of month\", each Date.WeekOfMonth([Date], Day.Monday), type number),\r\n  #\"Inserted day\" = Table.AddColumn(#\"Inserted week of month\", \"Day\", each Date.Day([Date]), type number),\r\n  #\"Inserted day of week\" = Table.AddColumn(#\"Inserted day\", \"Day of week\", each Date.DayOfWeek([Date], Day.Monday)+1, type number),\r\n  #\"Inserted day of year\" = Table.AddColumn(#\"Inserted day of week\", \"Day of year\", each Date.DayOfYear([Date]), type number),\r\n  #\"Inserted day name\" = Table.AddColumn(#\"Inserted day of year\", \"Day name\", each Date.DayOfWeekName([Date]), type text),\r\n  #\"Inserted text range\" = Table.AddColumn(#\"Inserted day name\", \"Text range\", each Text.Middle([Month name], 0, 3), type text),\r\n  #\"Duplicated column\" = Table.DuplicateColumn(#\"Inserted text range\", \"Quarter\", \"Quarter - Copy\"),\r\n  #\"Added prefix\" = Table.TransformColumns(#\"Duplicated column\", {{\"Quarter - Copy\", each \"Q\" & Text.From(_), type text}}),\r\n  #\"Renamed columns 1\" = Table.RenameColumns(#\"Added prefix\", {{\"Quarter - Copy\", \"Qtr\"}, {\"Text range\", \"Month short\"}}),\r\n  #\"Inserted conditional column\" = Table.AddColumn(#\"Renamed columns 1\", \"WorkDay\", each if [Day of week] = 6 then 0 else if [Day of week] = 7 then 0 else 1),\r\n  #\"Added custom\" = Table.AddColumn(#\"Inserted conditional column\", \"FiscalDate\", each Date.AddMonths([Date],13-FiscalYearStartMonth)),\r\n  #\"Changed column type 1\" = Table.TransformColumnTypes(#\"Added custom\", {{\"FiscalDate\", type date}}),\r\n  #\"Inserted year 1\" = Table.AddColumn(#\"Changed column type 1\", \"Year.1\", each Date.Year([FiscalDate]), type number),\r\n  #\"Inserted quarter 1\" = Table.AddColumn(#\"Inserted year 1\", \"Quarter.1\", each Date.QuarterOfYear([FiscalDate]), type number),\r\n  #\"Inserted month 1\" = Table.AddColumn(#\"Inserted quarter 1\", \"Month.1\", each Date.Month([FiscalDate]), type number),\r\n  #\"Renamed columns 2\" = Table.RenameColumns(#\"Inserted month 1\", {{\"Year.1\", \"Fiscal year\"}, {\"Quarter.1\", \"Fiscal quarter\"}, {\"Month.1\", \"Fiscal month\"}}),\r\n  #\"Changed column type 2\" = Table.TransformColumnTypes(#\"Renamed columns 2\", {{\"WorkDay\", Int64.Type}}),\r\n  #\"Duplicated column 1\" = Table.DuplicateColumn(#\"Changed column type 2\", \"Fiscal year\", \"Fiscal Year - Copy\"),\r\n  #\"Extracted last characters\" = Table.TransformColumns(#\"Duplicated column 1\", {{\"Fiscal Year - Copy\", each Text.End(Text.From(_), 2), type text}}),\r\n  #\"Added prefix 1\" = Table.TransformColumns(#\"Extracted last characters\", {{\"Fiscal Year - Copy\", each \"FY\" & _, type text}}),\r\n  #\"Renamed columns 3\" = Table.RenameColumns(#\"Added prefix 1\", {{\"Fiscal Year - Copy\", \"FY\"}}),\r\n  #\"Duplicated column 2\" = Table.DuplicateColumn(#\"Renamed columns 3\", \"Fiscal quarter\", \"Fiscal Quarter - Copy\"),\r\n  #\"Added prefix 2\" = Table.TransformColumns(#\"Duplicated column 2\", {{\"Fiscal Quarter - Copy\", each \"FQ\" & Text.From(_), type text}}),\r\n  #\"Duplicated column 3\" = Table.DuplicateColumn(#\"Added prefix 2\", \"Month short\", \"Month short - Copy\"),\r\n  #\"Renamed columns 4\" = Table.RenameColumns(#\"Duplicated column 3\", {{\"Fiscal Quarter - Copy\", \"FQ\"}, {\"Month short - Copy\", \"Fiscal month short\"}}),\r\n  #\"Removed columns\" = Table.RemoveColumns(#\"Renamed columns 4\", {\"FiscalDate\"}),\r\n  #\"Changed column type 3\" = Table.TransformColumnTypes(#\"Removed columns\", {{\"Year\", Int64.Type}, {\"Month\", Int64.Type}, {\"Quarter\", Int64.Type}, {\"Week of year\", Int64.Type}, {\"Week of month\", Int64.Type}, {\"Day\", Int64.Type}, {\"Day of week\", Int64.Type}, {\"Day of year\", Int64.Type}, {\"Fiscal year\", Int64.Type}, {\"Fiscal quarter\", Int64.Type}, {\"Fiscal month\", Int64.Type}}),\r\n  #\"Added index\" = Table.AddIndexColumn(#\"Changed column type 3\", \"Index\", 1, 1, Int64.Type),\r\n  #\"Added custom 1\" = Table.AddColumn(#\"Added index\", \"CW\", each if\r\nNumber.RoundDown((Date.DayOfYear([Date])-(Date.DayOfWeek([Date], Day.Monday)+1)+10)/7)=0\r\n\r\nthen\r\nNumber.RoundDown((Date.DayOfYear(#date(Date.Year([Date])-1,12,31))-(Date.DayOfWeek(#date(Date.Year([Date])-1,12,31), Day.Monday)+1)+10)/7)\r\n\r\nelse if\r\n(Number.RoundDown((Date.DayOfYear([Date])-(Date.DayOfWeek([Date], Day.Monday)+1)+10)/7)=53\r\nand (Date.DayOfWeek(#date(Date.Year([Date]),12,31), Day.Monday)+1<4))\r\n\r\nthen\r\n1\r\n\r\nelse\r\nNumber.RoundDown((Date.DayOfYear([Date])-(Date.DayOfWeek([Date], Day.Monday)+1)+10)/7)),\r\n  #\"Changed column type 4\" = Table.TransformColumnTypes(#\"Added custom 1\", {{\"CW\", Int64.Type}}),\r\n  #\"Added custom 2\" = Table.AddColumn(#\"Changed column type 4\", \"YearMonthID\", each [Year]*100 + [Month]),\r\n  #\"Inserted last characters\" = Table.AddColumn(#\"Added custom 2\", \"Year_Short\", each Text.End(Text.From([Year]), 2), type text),\r\n  #\"Inserted merged column\" = Table.AddColumn(#\"Inserted last characters\", \"Month_Year\", each Text.Combine({[Month short], [Year_Short]}, \"-\"), type text),\r\n  #\"Changed column type 5\" = Table.TransformColumnTypes(#\"Inserted merged column\", {{\"YearMonthID\", type text}}),\r\n  #\"Inserted merged column 1\" = Table.AddColumn(#\"Changed column type 5\", \"Year_CW\", each Text.Combine({[Year_Short], Text.From([CW])}, \"-CW\"), type text),\r\n  #\"Inserted merged column 2\" = Table.AddColumn(#\"Inserted merged column 1\", \"Year-Month\", each Text.Combine({Text.From([Year]), Text.From([Month])}, \"-\"), type text)\r\nin\r\n  #\"Inserted merged column 2\";\r\nshared Location_Fabs = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Name] = \"CoherentSites.xlsx\"),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows\", each [Attributes]?[Hidden]? <> true),\r\n  #\"Invoke custom function\" = Table.AddColumn(#\"Filtered hidden files\", \"Transform file (4)\", each #\"Transform file (4)\"([Content])),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Invoke custom function\", {{\"Name\", \"Source.Name\"}}),\r\n  #\"Removed other columns\" = Table.SelectColumns(#\"Renamed columns\", {\"Source.Name\", \"Transform file (4)\"}),\r\n  #\"Expanded table column\" = Table.ExpandTableColumn(#\"Removed other columns\", \"Transform file (4)\", Table.ColumnNames(#\"Transform file (4)\"(#\"Sample file (4)\"))),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Expanded table column\", {{\"Source.Name\", type text}, {\"Column1\", type text}, {\"Column2\", type text}}),\r\n  #\"Promoted headers\" = Table.PromoteHeaders(#\"Changed column type\", [PromoteAllScalars = true]),\r\n  #\"Changed column type 1\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"CoherentSites.xlsx\", type text}, {\"Department\", type text}, {\"Fab\", type text}}),\r\n  #\"Removed other columns 1\" = Table.SelectColumns(#\"Changed column type 1\", {\"Department\", \"Fab\"})\r\nin\r\n  #\"Removed other columns 1\";\r\nshared Location_Sites = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Name] = \"CoherentSites.xlsx\"),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows\", each [Attributes]?[Hidden]? <> true),\r\n  #\"Invoke custom function\" = Table.AddColumn(#\"Filtered hidden files\", \"Transform file (5)\", each #\"Transform file (5)\"([Content])),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Invoke custom function\", {{\"Name\", \"Source.Name\"}}),\r\n  #\"Removed other columns\" = Table.SelectColumns(#\"Renamed columns\", {\"Source.Name\", \"Transform file (5)\"}),\r\n  #\"Expanded table column\" = Table.ExpandTableColumn(#\"Removed other columns\", \"Transform file (5)\", Table.ColumnNames(#\"Transform file (5)\"(#\"Sample file (5)\"))),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Expanded table column\", {{\"Source.Name\", type text}, {\"Business Unit\", type text}, {\"Site Name\", type text}, {\"Country Code\", type text}, {\"Country\", type text}, {\"ZIP Code\", type text}, {\"City\", type text}, {\"Latitude\", type number}, {\"Longitude\", type number}, {\"Fab\", type text}}),\r\n  #\"Removed other columns 1\" = Table.SelectColumns(#\"Changed column type\", {\"Business Unit\", \"Site Name\", \"Country Code\", \"Country\", \"ZIP Code\", \"City\", \"Latitude\", \"Longitude\", \"Fab\"})\r\nin\r\n  #\"Removed other columns 1\";\r\nshared #\"Transform Sample file (2)\" = let\r\n  Source = Excel.Workbook(#\"Parameter (2)\", null, true),\r\n  Navigation = Source{[Item = \"Sheet1\", Kind = \"Sheet\"]}[Data]\r\nin\r\n  Navigation;\r\nshared #\"Sample file (2)\" = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Name] = \"Assemblies_Additional_Details.xlsx\"),\r\n  Navigation = #\"Filtered rows\"{0}[Content]\r\nin\r\n  Navigation;\r\nshared #\"Parameter (2)\" = let\r\n  #\"Parameter (2)\" = #\"Sample file (2)\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type binary]\r\nin\r\n  #\"Parameter (2)\";\r\nshared #\"Transform file (2)\" = let\r\n  Source = (#\"Parameter (2)\" as binary) => let\n  Source = Excel.Workbook(#\"Parameter (2)\", null, true),\n  Navigation = Source{[Item = \"Sheet1\", Kind = \"Sheet\"]}[Data]\nin\n  Navigation\r\nin\r\n  Source;\r\nshared #\"Transform Sample file (3)\" = let\r\n  Source = Excel.Workbook(#\"Parameter (3)\", null, true),\r\n  Navigation = Source{[Item = \"shSpecs\", Kind = \"Sheet\"]}[Data],\r\n  #\"Promoted headers\" = Table.PromoteHeaders(Navigation, [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"Part Number\", Int64.Type}, {\"Part Description\", type text}, {\"BW FWHM SA LSL (mm)\", type number}, {\"BW FWHM SA USL (mm)\", type number}, {\"BW FWHM LA LSL (mm)\", Int64.Type}, {\"BW FWHM LA USL (mm)\", Int64.Type}, {\"BW 1/e² SA LSL (mm)\", Int64.Type}, {\"BW 1/e² SA USL (mm)\", Int64.Type}, {\"BW 1/e² LA LSL (mm)\", Int64.Type}, {\"BW 1/e² LA USL (mm)\", Int64.Type}, {\"Beam Asym. SA LSL (%)\", Int64.Type}, {\"Beam Asym. SA USL (%)\", Int64.Type}, {\"Beam Asym. LA LSL (%)\", Int64.Type}, {\"Beam Asym. LA USL (%)\", Int64.Type}, {\"Divergency SA LSL (mrad)\", Int64.Type}, {\"Divergency SA USL (mrad)\", type number}, {\"Divergency LA LSL (mrad)\", Int64.Type}, {\"Divergency LA USL (mrad)\", type number}, {\"Beam Point. Stab. SA LSL (mrad)\", Int64.Type}, {\"Beam Point. Stab. SA USL (mrad)\", type number}, {\"Beam Point. Stab. LA LSL (mrad)\", Int64.Type}, {\"Beam Point. Stab. LA USL (mrad)\", type number}, {\"Beam Pos. Stab. SA LSL (mm)\", type number}, {\"Beam Pos. Stab. SA USL (mm)\", type number}, {\"Beam Pos. Stab. LA LSL (mm)\", type number}, {\"Beam Pos. Stab. LA USL (mm)\", type number}})\r\nin\r\n  #\"Changed column type\";\r\nshared #\"Sample file (3)\" = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Name] = \"Specs_VHP_Tube-FinalTest.xlsx\"),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows\", each [Attributes]?[Hidden]? <> true),\r\n  Navigation = #\"Filtered hidden files\"{0}[Content]\r\nin\r\n  Navigation;\r\nshared #\"Parameter (3)\" = let\r\n  #\"Parameter (3)\" = #\"Sample file (3)\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type binary]\r\nin\r\n  #\"Parameter (3)\";\r\nshared #\"Transform file (3)\" = let\r\n  Source = (#\"Parameter (3)\" as binary) => let\n  Source = Excel.Workbook(#\"Parameter (3)\", null, true),\n  Navigation = Source{[Item = \"shSpecs\", Kind = \"Sheet\"]}[Data],\n  #\"Promoted headers\" = Table.PromoteHeaders(Navigation, [PromoteAllScalars = true]),\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"Part Number\", Int64.Type}, {\"Part Description\", type text}, {\"BW FWHM SA LSL (mm)\", type number}, {\"BW FWHM SA USL (mm)\", type number}, {\"BW FWHM LA LSL (mm)\", Int64.Type}, {\"BW FWHM LA USL (mm)\", Int64.Type}, {\"BW 1/e² SA LSL (mm)\", Int64.Type}, {\"BW 1/e² SA USL (mm)\", Int64.Type}, {\"BW 1/e² LA LSL (mm)\", Int64.Type}, {\"BW 1/e² LA USL (mm)\", Int64.Type}, {\"Beam Asym. SA LSL (%)\", Int64.Type}, {\"Beam Asym. SA USL (%)\", Int64.Type}, {\"Beam Asym. LA LSL (%)\", Int64.Type}, {\"Beam Asym. LA USL (%)\", Int64.Type}, {\"Divergency SA LSL (mrad)\", Int64.Type}, {\"Divergency SA USL (mrad)\", type number}, {\"Divergency LA LSL (mrad)\", Int64.Type}, {\"Divergency LA USL (mrad)\", type number}, {\"Beam Point. Stab. SA LSL (mrad)\", Int64.Type}, {\"Beam Point. Stab. SA USL (mrad)\", type number}, {\"Beam Point. Stab. LA LSL (mrad)\", Int64.Type}, {\"Beam Point. Stab. LA USL (mrad)\", type number}, {\"Beam Pos. Stab. SA LSL (mm)\", type number}, {\"Beam Pos. Stab. SA USL (mm)\", type number}, {\"Beam Pos. Stab. LA LSL (mm)\", type number}, {\"Beam Pos. Stab. LA USL (mm)\", type number}})\nin\n  #\"Changed column type\"\r\nin\r\n  Source;\r\nshared #\"Transform Sample file (4)\" = let\r\n  Source = Excel.Workbook(#\"Parameter (4)\", null, true),\r\n  Navigation = Source{[Item = \"Department_Fabs\", Kind = \"Sheet\"]}[Data],\r\n  #\"Changed column type\" = Table.TransformColumnTypes(Navigation, {{\"Column1\", type text}, {\"Column2\", type text}})\r\nin\r\n  #\"Changed column type\";\r\nshared #\"Sample file (4)\" = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Name] = \"CoherentSites.xlsx\"),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows\", each [Attributes]?[Hidden]? <> true),\r\n  Navigation = #\"Filtered hidden files\"{0}[Content]\r\nin\r\n  Navigation;\r\nshared #\"Parameter (4)\" = let\r\n  #\"Parameter (4)\" = #\"Sample file (4)\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type binary]\r\nin\r\n  #\"Parameter (4)\";\r\nshared #\"Transform file (4)\" = let\r\n  Source = (#\"Parameter (4)\" as binary) => let\n  Source = Excel.Workbook(#\"Parameter (4)\", null, true),\n  Navigation = Source{[Item = \"Department_Fabs\", Kind = \"Sheet\"]}[Data],\n  #\"Changed column type\" = Table.TransformColumnTypes(Navigation, {{\"Column1\", type text}, {\"Column2\", type text}})\nin\n  #\"Changed column type\"\r\nin\r\n  Source;\r\nshared #\"Transform Sample file (5)\" = let\r\n  Source = Excel.Workbook(#\"Parameter (5)\", null, true),\r\n  Navigation = Source{[Item = \"WW_Factories\", Kind = \"Sheet\"]}[Data],\r\n  #\"Promoted headers\" = Table.PromoteHeaders(Navigation, [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"Business Unit\", type text}, {\"Site Name\", type text}, {\"Country Code\", type text}, {\"Country\", type text}, {\"ZIP Code\", type any}, {\"City\", type text}, {\"Latitude\", type number}, {\"Longitude\", type number}, {\"Fab\", type text}})\r\nin\r\n  #\"Changed column type\";\r\nshared #\"Sample file (5)\" = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Name] = \"CoherentSites.xlsx\"),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows\", each [Attributes]?[Hidden]? <> true),\r\n  Navigation = #\"Filtered hidden files\"{0}[Content]\r\nin\r\n  Navigation;\r\nshared #\"Parameter (5)\" = let\r\n  #\"Parameter (5)\" = #\"Sample file (5)\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type binary]\r\nin\r\n  #\"Parameter (5)\";\r\nshared #\"Transform file (5)\" = let\r\n  Source = (#\"Parameter (5)\" as binary) => let\n  Source = Excel.Workbook(#\"Parameter (5)\", null, true),\n  Navigation = Source{[Item = \"WW_Factories\", Kind = \"Sheet\"]}[Data],\n  #\"Promoted headers\" = Table.PromoteHeaders(Navigation, [PromoteAllScalars = true]),\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"Business Unit\", type text}, {\"Site Name\", type text}, {\"Country Code\", type text}, {\"Country\", type text}, {\"ZIP Code\", type any}, {\"City\", type text}, {\"Latitude\", type number}, {\"Longitude\", type number}, {\"Fab\", type text}})\nin\n  #\"Changed column type\"\r\nin\r\n  Source;\r\nshared #\"Assemblies-VHP-API\" = let\r\n  Source = Json.Document(Web.Contents(\"https://prod-cumulus.azurefd.net/prod/reporting/v1.0/api/Assemblies/Production/GEP/VHP/VHP%20Production/GEP\", [Headers=[Authorization=parToken]])),\r\n  #\"Converted to table\" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),\r\n  #\"Expanded Column1\" = Table.ExpandRecordColumn(#\"Converted to table\", \"Column1\", {\"TYPE\", \"PART_NUMBER\", \"PART_DESCRIPTION\", \"REVISION\", \"WIP_DISPLAY\", \"SERIAL_CONTROL\", \"LOT_CONTROL\", \"AGILE_AUTO_SYNC\", \"IN_SYNC\", \"AUTO_SERIALIZE\", \"WORK_CELL\", \"PRODUCTION_TYPE\", \"DEFAULT_CONTAINER\", \"FLOW_NAME\", \"TAGS\", \"AGILE_DOCUMENT\", \"CREATE_DATE\", \"MODIFY_DATE\", \"SERIAL_NUMBER_FORMAT\", \"VARIABLE_COMP_QTY\", \"MAXIMUM_LOT_SIZE\", \"MAXIMUMN_BATCH_SIZE\", \"ORACLE_GENERIC_PN\", \"ORACLE_DISCRETE_COMP\", \"ORACLE_WORK_ORDERLESS_COMP\", \"ORACLE_IMPORT_BOM\", \"ORACLE_IMPORT_BOM_BULK\", \"ORACLE_MOVE_TX\", \"ORACLE_RELEASE_TX\", \"ORACLE_MATERIAL_TX\", \"ORACLE_RESOURCE_TX\", \"ORACLE_RESOURCE_VALIDATION\", \"ORACLE_WO_IMPORT\", \"ORACLE_QUICK_WO\", \"QUEUE_AUTO_ADD\", \"ORACLE_ITEM_TYPE\", \"ORACLE_ROUTING_TYPE\", \"ORACLE_TBU\", \"ORACLE_PRODUCT_FAMILY\", \"ORACLE_PRODUCT_LINE\", \"ORACLE_FORECAST_FIELD\", \"AGILE_LIFECYCLE\"}, {\"TYPE\", \"PART_NUMBER\", \"PART_DESCRIPTION\", \"REVISION\", \"WIP_DISPLAY\", \"SERIAL_CONTROL\", \"LOT_CONTROL\", \"AGILE_AUTO_SYNC\", \"IN_SYNC\", \"AUTO_SERIALIZE\", \"WORK_CELL\", \"PRODUCTION_TYPE\", \"DEFAULT_CONTAINER\", \"FLOW_NAME\", \"TAGS\", \"AGILE_DOCUMENT\", \"CREATE_DATE\", \"MODIFY_DATE\", \"SERIAL_NUMBER_FORMAT\", \"VARIABLE_COMP_QTY\", \"MAXIMUM_LOT_SIZE\", \"MAXIMUMN_BATCH_SIZE\", \"ORACLE_GENERIC_PN\", \"ORACLE_DISCRETE_COMP\", \"ORACLE_WORK_ORDERLESS_COMP\", \"ORACLE_IMPORT_BOM\", \"ORACLE_IMPORT_BOM_BULK\", \"ORACLE_MOVE_TX\", \"ORACLE_RELEASE_TX\", \"ORACLE_MATERIAL_TX\", \"ORACLE_RESOURCE_TX\", \"ORACLE_RESOURCE_VALIDATION\", \"ORACLE_WO_IMPORT\", \"ORACLE_QUICK_WO\", \"QUEUE_AUTO_ADD\", \"ORACLE_ITEM_TYPE\", \"ORACLE_ROUTING_TYPE\", \"ORACLE_TBU\", \"ORACLE_PRODUCT_FAMILY\", \"ORACLE_PRODUCT_LINE\", \"ORACLE_FORECAST_FIELD\", \"AGILE_LIFECYCLE\"}),\r\n  #\"Added custom\" = Table.AddColumn(#\"Expanded Column1\", \"Sandbox\", each \"VHP\"),\r\n  #\"Choose columns\" = Table.SelectColumns(#\"Added custom\", {\"TYPE\", \"PART_NUMBER\", \"PART_DESCRIPTION\", \"REVISION\", \"WIP_DISPLAY\", \"IN_SYNC\", \"WORK_CELL\", \"PRODUCTION_TYPE\", \"DEFAULT_CONTAINER\", \"FLOW_NAME\", \"TAGS\", \"CREATE_DATE\", \"MODIFY_DATE\", \"ORACLE_ITEM_TYPE\", \"ORACLE_ROUTING_TYPE\", \"ORACLE_TBU\", \"ORACLE_PRODUCT_FAMILY\", \"ORACLE_PRODUCT_LINE\", \"ORACLE_FORECAST_FIELD\", \"AGILE_LIFECYCLE\", \"Sandbox\"}),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Choose columns\", {{\"TYPE\", type text}, {\"PART_NUMBER\", type text}, {\"PART_DESCRIPTION\", type text}, {\"REVISION\", type text}, {\"WIP_DISPLAY\", type text}, {\"IN_SYNC\", type logical}, {\"WORK_CELL\", type text}, {\"PRODUCTION_TYPE\", type text}, {\"DEFAULT_CONTAINER\", type text}, {\"FLOW_NAME\", type text}, {\"TAGS\", type text}, {\"CREATE_DATE\", type datetime}, {\"MODIFY_DATE\", type datetime}, {\"ORACLE_ITEM_TYPE\", type text}, {\"ORACLE_ROUTING_TYPE\", type text}, {\"ORACLE_TBU\", type text}, {\"ORACLE_PRODUCT_FAMILY\", type text}, {\"ORACLE_PRODUCT_LINE\", type text}, {\"ORACLE_FORECAST_FIELD\", type text}, {\"AGILE_LIFECYCLE\", type text}, {\"Sandbox\", type text}})\r\nin\r\n  #\"Changed column type\";\r\nshared #\"Assemblies-MP-API\" = let\r\n  Source = Json.Document(Web.Contents(\"https://prod-cumulus.azurefd.net/prod/reporting/v1.0/api/Assemblies/Production/GEP/MP/MP%20Production/GEP\", [Headers=[Authorization=parToken]])),\r\n  #\"Converted to table\" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),\r\n  #\"Expanded Column1\" = Table.ExpandRecordColumn(#\"Converted to table\", \"Column1\", {\"TYPE\", \"PART_NUMBER\", \"PART_DESCRIPTION\", \"REVISION\", \"WIP_DISPLAY\", \"SERIAL_CONTROL\", \"LOT_CONTROL\", \"AGILE_AUTO_SYNC\", \"IN_SYNC\", \"AUTO_SERIALIZE\", \"WORK_CELL\", \"PRODUCTION_TYPE\", \"DEFAULT_CONTAINER\", \"FLOW_NAME\", \"TAGS\", \"AGILE_DOCUMENT\", \"CREATE_DATE\", \"MODIFY_DATE\", \"SERIAL_NUMBER_FORMAT\", \"VARIABLE_COMP_QTY\", \"MAXIMUM_LOT_SIZE\", \"MAXIMUMN_BATCH_SIZE\", \"ORACLE_GENERIC_PN\", \"ORACLE_DISCRETE_COMP\", \"ORACLE_WORK_ORDERLESS_COMP\", \"ORACLE_IMPORT_BOM\", \"ORACLE_IMPORT_BOM_BULK\", \"ORACLE_MOVE_TX\", \"ORACLE_RELEASE_TX\", \"ORACLE_MATERIAL_TX\", \"ORACLE_RESOURCE_TX\", \"ORACLE_RESOURCE_VALIDATION\", \"ORACLE_WO_IMPORT\", \"ORACLE_QUICK_WO\", \"QUEUE_AUTO_ADD\", \"ORACLE_ITEM_TYPE\", \"ORACLE_ROUTING_TYPE\", \"ORACLE_TBU\", \"ORACLE_PRODUCT_FAMILY\", \"ORACLE_PRODUCT_LINE\", \"ORACLE_FORECAST_FIELD\", \"AGILE_LIFECYCLE\"}, {\"TYPE\", \"PART_NUMBER\", \"PART_DESCRIPTION\", \"REVISION\", \"WIP_DISPLAY\", \"SERIAL_CONTROL\", \"LOT_CONTROL\", \"AGILE_AUTO_SYNC\", \"IN_SYNC\", \"AUTO_SERIALIZE\", \"WORK_CELL\", \"PRODUCTION_TYPE\", \"DEFAULT_CONTAINER\", \"FLOW_NAME\", \"TAGS\", \"AGILE_DOCUMENT\", \"CREATE_DATE\", \"MODIFY_DATE\", \"SERIAL_NUMBER_FORMAT\", \"VARIABLE_COMP_QTY\", \"MAXIMUM_LOT_SIZE\", \"MAXIMUMN_BATCH_SIZE\", \"ORACLE_GENERIC_PN\", \"ORACLE_DISCRETE_COMP\", \"ORACLE_WORK_ORDERLESS_COMP\", \"ORACLE_IMPORT_BOM\", \"ORACLE_IMPORT_BOM_BULK\", \"ORACLE_MOVE_TX\", \"ORACLE_RELEASE_TX\", \"ORACLE_MATERIAL_TX\", \"ORACLE_RESOURCE_TX\", \"ORACLE_RESOURCE_VALIDATION\", \"ORACLE_WO_IMPORT\", \"ORACLE_QUICK_WO\", \"QUEUE_AUTO_ADD\", \"ORACLE_ITEM_TYPE\", \"ORACLE_ROUTING_TYPE\", \"ORACLE_TBU\", \"ORACLE_PRODUCT_FAMILY\", \"ORACLE_PRODUCT_LINE\", \"ORACLE_FORECAST_FIELD\", \"AGILE_LIFECYCLE\"}),\r\n  #\"Added custom\" = Table.AddColumn(#\"Expanded Column1\", \"Sandbox\", each \"MP\"),\r\n  #\"Choose columns\" = Table.SelectColumns(#\"Added custom\", {\"TYPE\", \"PART_NUMBER\", \"PART_DESCRIPTION\", \"REVISION\", \"WIP_DISPLAY\", \"IN_SYNC\", \"WORK_CELL\", \"PRODUCTION_TYPE\", \"DEFAULT_CONTAINER\", \"FLOW_NAME\", \"TAGS\", \"CREATE_DATE\", \"MODIFY_DATE\", \"ORACLE_ITEM_TYPE\", \"ORACLE_ROUTING_TYPE\", \"ORACLE_TBU\", \"ORACLE_PRODUCT_FAMILY\", \"ORACLE_PRODUCT_LINE\", \"ORACLE_FORECAST_FIELD\", \"AGILE_LIFECYCLE\", \"Sandbox\"}),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Choose columns\", {{\"TYPE\", type text}, {\"PART_NUMBER\", type text}, {\"PART_DESCRIPTION\", type text}, {\"REVISION\", type text}, {\"WIP_DISPLAY\", type text}, {\"IN_SYNC\", type logical}, {\"WORK_CELL\", type text}, {\"PRODUCTION_TYPE\", type text}, {\"DEFAULT_CONTAINER\", type text}, {\"FLOW_NAME\", type text}, {\"TAGS\", type text}, {\"CREATE_DATE\", type datetime}, {\"MODIFY_DATE\", type datetime}, {\"ORACLE_ITEM_TYPE\", type text}, {\"ORACLE_ROUTING_TYPE\", type text}, {\"ORACLE_TBU\", type text}, {\"ORACLE_PRODUCT_FAMILY\", type text}, {\"ORACLE_PRODUCT_LINE\", type text}, {\"ORACLE_FORECAST_FIELD\", type text}, {\"AGILE_LIFECYCLE\", type text}, {\"Sandbox\", type text}})\r\nin\r\n  #\"Changed column type\";\r\nshared #\"Assemblies-LP-API\" = let\r\n  Source = Json.Document(Web.Contents(\"https://prod-cumulus.azurefd.net/prod/reporting/v1.0/api/Assemblies/Production/GEP/LP/LP%20Production/GEP\", [Headers=[Authorization=parToken]])),\r\n  #\"Converted to table\" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),\r\n  #\"Expanded Column1\" = Table.ExpandRecordColumn(#\"Converted to table\", \"Column1\", {\"TYPE\", \"PART_NUMBER\", \"PART_DESCRIPTION\", \"REVISION\", \"WIP_DISPLAY\", \"SERIAL_CONTROL\", \"LOT_CONTROL\", \"AGILE_AUTO_SYNC\", \"IN_SYNC\", \"AUTO_SERIALIZE\", \"WORK_CELL\", \"PRODUCTION_TYPE\", \"DEFAULT_CONTAINER\", \"FLOW_NAME\", \"TAGS\", \"AGILE_DOCUMENT\", \"CREATE_DATE\", \"MODIFY_DATE\", \"SERIAL_NUMBER_FORMAT\", \"VARIABLE_COMP_QTY\", \"MAXIMUM_LOT_SIZE\", \"MAXIMUMN_BATCH_SIZE\", \"ORACLE_GENERIC_PN\", \"ORACLE_DISCRETE_COMP\", \"ORACLE_WORK_ORDERLESS_COMP\", \"ORACLE_IMPORT_BOM\", \"ORACLE_IMPORT_BOM_BULK\", \"ORACLE_MOVE_TX\", \"ORACLE_RELEASE_TX\", \"ORACLE_MATERIAL_TX\", \"ORACLE_RESOURCE_TX\", \"ORACLE_RESOURCE_VALIDATION\", \"ORACLE_WO_IMPORT\", \"ORACLE_QUICK_WO\", \"QUEUE_AUTO_ADD\", \"ORACLE_ITEM_TYPE\", \"ORACLE_ROUTING_TYPE\", \"ORACLE_TBU\", \"ORACLE_PRODUCT_FAMILY\", \"ORACLE_PRODUCT_LINE\", \"ORACLE_FORECAST_FIELD\", \"AGILE_LIFECYCLE\"}, {\"TYPE\", \"PART_NUMBER\", \"PART_DESCRIPTION\", \"REVISION\", \"WIP_DISPLAY\", \"SERIAL_CONTROL\", \"LOT_CONTROL\", \"AGILE_AUTO_SYNC\", \"IN_SYNC\", \"AUTO_SERIALIZE\", \"WORK_CELL\", \"PRODUCTION_TYPE\", \"DEFAULT_CONTAINER\", \"FLOW_NAME\", \"TAGS\", \"AGILE_DOCUMENT\", \"CREATE_DATE\", \"MODIFY_DATE\", \"SERIAL_NUMBER_FORMAT\", \"VARIABLE_COMP_QTY\", \"MAXIMUM_LOT_SIZE\", \"MAXIMUMN_BATCH_SIZE\", \"ORACLE_GENERIC_PN\", \"ORACLE_DISCRETE_COMP\", \"ORACLE_WORK_ORDERLESS_COMP\", \"ORACLE_IMPORT_BOM\", \"ORACLE_IMPORT_BOM_BULK\", \"ORACLE_MOVE_TX\", \"ORACLE_RELEASE_TX\", \"ORACLE_MATERIAL_TX\", \"ORACLE_RESOURCE_TX\", \"ORACLE_RESOURCE_VALIDATION\", \"ORACLE_WO_IMPORT\", \"ORACLE_QUICK_WO\", \"QUEUE_AUTO_ADD\", \"ORACLE_ITEM_TYPE\", \"ORACLE_ROUTING_TYPE\", \"ORACLE_TBU\", \"ORACLE_PRODUCT_FAMILY\", \"ORACLE_PRODUCT_LINE\", \"ORACLE_FORECAST_FIELD\", \"AGILE_LIFECYCLE\"}),\r\n  #\"Added custom\" = Table.AddColumn(#\"Expanded Column1\", \"Sandbox\", each \"LP\"),\r\n  #\"Choose columns\" = Table.SelectColumns(#\"Added custom\", {\"TYPE\", \"PART_NUMBER\", \"PART_DESCRIPTION\", \"REVISION\", \"WIP_DISPLAY\", \"IN_SYNC\", \"WORK_CELL\", \"PRODUCTION_TYPE\", \"DEFAULT_CONTAINER\", \"FLOW_NAME\", \"TAGS\", \"CREATE_DATE\", \"MODIFY_DATE\", \"ORACLE_ITEM_TYPE\", \"ORACLE_ROUTING_TYPE\", \"ORACLE_TBU\", \"ORACLE_PRODUCT_FAMILY\", \"ORACLE_PRODUCT_LINE\", \"ORACLE_FORECAST_FIELD\", \"AGILE_LIFECYCLE\", \"Sandbox\"}),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Choose columns\", {{\"TYPE\", type text}, {\"PART_NUMBER\", type text}, {\"PART_DESCRIPTION\", type text}, {\"REVISION\", type text}, {\"WIP_DISPLAY\", type text}, {\"IN_SYNC\", type logical}, {\"WORK_CELL\", type text}, {\"PRODUCTION_TYPE\", type text}, {\"DEFAULT_CONTAINER\", type text}, {\"FLOW_NAME\", type text}, {\"TAGS\", type text}, {\"CREATE_DATE\", type datetime}, {\"MODIFY_DATE\", type datetime}, {\"ORACLE_ITEM_TYPE\", type text}, {\"ORACLE_ROUTING_TYPE\", type text}, {\"ORACLE_TBU\", type text}, {\"ORACLE_PRODUCT_FAMILY\", type text}, {\"ORACLE_PRODUCT_LINE\", type text}, {\"ORACLE_FORECAST_FIELD\", type text}, {\"AGILE_LIFECYCLE\", type text}, {\"Sandbox\", type text}})\r\nin\r\n  #\"Changed column type\";\r\nshared #\"Assemblies-BDS-API\" = let\r\n  Source = Json.Document(Web.Contents(\"https://prod-cumulus.azurefd.net/prod/reporting/v1.0/api/Assemblies/Production/GEP/VHP/BDS/GEP\", [Headers=[Authorization=parToken]])),\r\n  #\"Converted to table\" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),\r\n  #\"Expanded Column1\" = Table.ExpandRecordColumn(#\"Converted to table\", \"Column1\", {\"TYPE\", \"PART_NUMBER\", \"PART_DESCRIPTION\", \"REVISION\", \"WIP_DISPLAY\", \"SERIAL_CONTROL\", \"LOT_CONTROL\", \"AGILE_AUTO_SYNC\", \"IN_SYNC\", \"AUTO_SERIALIZE\", \"WORK_CELL\", \"PRODUCTION_TYPE\", \"DEFAULT_CONTAINER\", \"FLOW_NAME\", \"TAGS\", \"AGILE_DOCUMENT\", \"CREATE_DATE\", \"MODIFY_DATE\", \"SERIAL_NUMBER_FORMAT\", \"VARIABLE_COMP_QTY\", \"MAXIMUM_LOT_SIZE\", \"MAXIMUMN_BATCH_SIZE\", \"ORACLE_GENERIC_PN\", \"ORACLE_DISCRETE_COMP\", \"ORACLE_WORK_ORDERLESS_COMP\", \"ORACLE_IMPORT_BOM\", \"ORACLE_IMPORT_BOM_BULK\", \"ORACLE_MOVE_TX\", \"ORACLE_RELEASE_TX\", \"ORACLE_MATERIAL_TX\", \"ORACLE_RESOURCE_TX\", \"ORACLE_RESOURCE_VALIDATION\", \"ORACLE_WO_IMPORT\", \"ORACLE_QUICK_WO\", \"QUEUE_AUTO_ADD\", \"ORACLE_ITEM_TYPE\", \"ORACLE_ROUTING_TYPE\", \"ORACLE_TBU\", \"ORACLE_PRODUCT_FAMILY\", \"ORACLE_PRODUCT_LINE\", \"ORACLE_FORECAST_FIELD\", \"AGILE_LIFECYCLE\"}, {\"TYPE\", \"PART_NUMBER\", \"PART_DESCRIPTION\", \"REVISION\", \"WIP_DISPLAY\", \"SERIAL_CONTROL\", \"LOT_CONTROL\", \"AGILE_AUTO_SYNC\", \"IN_SYNC\", \"AUTO_SERIALIZE\", \"WORK_CELL\", \"PRODUCTION_TYPE\", \"DEFAULT_CONTAINER\", \"FLOW_NAME\", \"TAGS\", \"AGILE_DOCUMENT\", \"CREATE_DATE\", \"MODIFY_DATE\", \"SERIAL_NUMBER_FORMAT\", \"VARIABLE_COMP_QTY\", \"MAXIMUM_LOT_SIZE\", \"MAXIMUMN_BATCH_SIZE\", \"ORACLE_GENERIC_PN\", \"ORACLE_DISCRETE_COMP\", \"ORACLE_WORK_ORDERLESS_COMP\", \"ORACLE_IMPORT_BOM\", \"ORACLE_IMPORT_BOM_BULK\", \"ORACLE_MOVE_TX\", \"ORACLE_RELEASE_TX\", \"ORACLE_MATERIAL_TX\", \"ORACLE_RESOURCE_TX\", \"ORACLE_RESOURCE_VALIDATION\", \"ORACLE_WO_IMPORT\", \"ORACLE_QUICK_WO\", \"QUEUE_AUTO_ADD\", \"ORACLE_ITEM_TYPE\", \"ORACLE_ROUTING_TYPE\", \"ORACLE_TBU\", \"ORACLE_PRODUCT_FAMILY\", \"ORACLE_PRODUCT_LINE\", \"ORACLE_FORECAST_FIELD\", \"AGILE_LIFECYCLE\"}),\r\n  #\"Added custom\" = Table.AddColumn(#\"Expanded Column1\", \"Sandbox\", each \"BDS\"),\r\n  #\"Choose columns\" = Table.SelectColumns(#\"Added custom\", {\"TYPE\", \"PART_NUMBER\", \"PART_DESCRIPTION\", \"REVISION\", \"WIP_DISPLAY\", \"IN_SYNC\", \"WORK_CELL\", \"PRODUCTION_TYPE\", \"DEFAULT_CONTAINER\", \"FLOW_NAME\", \"TAGS\", \"CREATE_DATE\", \"MODIFY_DATE\", \"ORACLE_ITEM_TYPE\", \"ORACLE_ROUTING_TYPE\", \"ORACLE_TBU\", \"ORACLE_PRODUCT_FAMILY\", \"ORACLE_PRODUCT_LINE\", \"ORACLE_FORECAST_FIELD\", \"AGILE_LIFECYCLE\", \"Sandbox\"}),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Choose columns\", {{\"TYPE\", type text}, {\"PART_NUMBER\", type text}, {\"PART_DESCRIPTION\", type text}, {\"REVISION\", type text}, {\"WIP_DISPLAY\", type text}, {\"IN_SYNC\", type logical}, {\"WORK_CELL\", type text}, {\"PRODUCTION_TYPE\", type text}, {\"DEFAULT_CONTAINER\", type text}, {\"FLOW_NAME\", type text}, {\"TAGS\", type text}, {\"CREATE_DATE\", type datetime}, {\"MODIFY_DATE\", type datetime}, {\"ORACLE_ITEM_TYPE\", type text}, {\"ORACLE_ROUTING_TYPE\", type text}, {\"ORACLE_TBU\", type text}, {\"ORACLE_PRODUCT_FAMILY\", type text}, {\"ORACLE_PRODUCT_LINE\", type text}, {\"ORACLE_FORECAST_FIELD\", type text}, {\"AGILE_LIFECYCLE\", type text}, {\"Sandbox\", type text}})\r\nin\r\n  #\"Changed column type\";\r\nshared Cumulus_Assemblies = let\r\n  Source = Table.Combine({#\"Assemblies-VHP-API\", #\"Assemblies-MP-API\", #\"Assemblies-LP-API\", #\"Assemblies-BDS-API\", #\"Assemblies-Optic-API\", #\"Assemblies-General-API\"}),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each [PART_DESCRIPTION] <> \"Dummy Assembly\"),\r\n  #\"Merged queries\" = Table.NestedJoin(#\"Filtered rows\", {\"PART_NUMBER\"}, Assemblies_Additional_Details, {\"Part Number\"}, \"Assemblies_Additional_Details\", JoinKind.LeftOuter),\r\n  #\"Expanded Assemblies_Additional_Details\" = Table.ExpandTableColumn(#\"Merged queries\", \"Assemblies_Additional_Details\", {\"Alias\", \"Classification\", \"Department\", \"Labor Seq1 (h)\", \"Labor Seq2 (h)\", \"Labor Seq3 (h)\", \"Labor Seq4 (h)\"}, {\"Alias\", \"Classification\", \"Department\", \"Labor Seq1 (h)\", \"Labor Seq2 (h)\", \"Labor Seq3 (h)\", \"Labor Seq4 (h)\"}),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Expanded Assemblies_Additional_Details\", {{\"PART_NUMBER\", \"Part Number\"}, {\"PART_DESCRIPTION\", \"Part Description\"}, {\"WIP_DISPLAY\", \"WIP DISPLAY\"}, {\"IN_SYNC\", \"IN SYNC\"}, {\"WORK_CELL\", \"Work Cell\"}, {\"PRODUCTION_TYPE\", \"PRODUCTION TYPE\"}, {\"DEFAULT_CONTAINER\", \"DEFAULT CONTAINER\"}, {\"FLOW_NAME\", \"Flow Name\"}, {\"CREATE_DATE\", \"Created\"}, {\"MODIFY_DATE\", \"Modified\"}, {\"AGILE_LIFECYCLE\", \"AGILE LIFECYCLE\"}, {\"ORACLE_ITEM_TYPE\", \"ORACLE ITEM TYPE\"}, {\"ORACLE_ROUTING_TYPE\", \"ORACLE ROUTING TYPE\"}, {\"ORACLE_TBU\", \"ORACLE TBU\"}, {\"ORACLE_PRODUCT_FAMILY\", \"ORACLE PRODUCT FAMILY\"}, {\"ORACLE_PRODUCT_LINE\", \"ORACLE PRODUCT LINE\"}, {\"ORACLE_FORECAST_FIELD\", \"ORACLE FORECAST FIELD\"}, {\"TAGS\", \"Tags\"}}),\r\n  #\"Marked key columns\" = Table.AddKey(#\"Renamed columns\", {\"Part Number\"}, false),\r\n  #\"Removed duplicates\" = Table.Distinct(#\"Marked key columns\", {\"Part Number\"})\r\nin\r\n  #\"Removed duplicates\";\r\nshared #\"Sample file (6)\" = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Name] = \"Specs_ASSP SPC.xlsx\"),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows\", each [Attributes]?[Hidden]? <> true),\r\n  Navigation = #\"Filtered hidden files\"{0}[Content]\r\nin\r\n  Navigation;\r\nshared #\"Parameter (6)\" = let\r\n  #\"Parameter (6)\" = #\"Sample file (6)\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type binary]\r\nin\r\n  #\"Parameter (6)\";\r\nshared #\"Transform Sample file (6)\" = let\r\n  Source = Excel.Workbook(#\"Parameter (6)\", null, true),\r\n  Navigation = Source{[Item = \"Tabelle2\", Kind = \"Table\"]}[Data],\r\n  #\"Changed column type\" = Table.TransformColumnTypes(Navigation, {{\"Part Number\", type any}, {\"Part Description\", type text}, {\"Capacity C0 LSL (nF)\", Int64.Type}, {\"Capacity C0 USL (nF)\", Int64.Type}, {\"Hold Time MA LSL (us)\", type number}, {\"Hold Time MA USL (us)\", type number}, {\"Hold Time MI LSL (us)\", Int64.Type}, {\"Hold Time MI USL (us)\", Int64.Type}, {\"Fall Time Negative Edge UCp LSL (ns)\", Int64.Type}, {\"Fall Time Negative Edge UCp USL (ns)\", Int64.Type}, {\"Transfer Time LSL (us)\", type number}, {\"Transfer Time USL (us)\", type number}, {\"Negative Voltage C1 LSL (kV)\", Int64.Type}, {\"Negative Voltage C1 USL (kV)\", Int64.Type}, {\"Negative Voltage Cp LSL (kV)\", Int64.Type}, {\"Negative Voltage Cp USL (kV)\", Int64.Type}, {\"Negative Voltage IGBT LSL (V)\", Int64.Type}, {\"Negative Voltage IGBT USL (V)\", Int64.Type}})\r\nin\r\n  #\"Changed column type\";\r\nshared #\"Transform file (6)\" = let\r\n  Source = (#\"Parameter (6)\" as binary) => let\r\n  Source = Excel.Workbook(#\"Parameter (6)\", null, true),\r\n  Navigation = Source{[Item = \"Tabelle2\", Kind = \"Table\"]}[Data],\r\n  #\"Changed column type\" = Table.TransformColumnTypes(Navigation, {{\"Part Number\", type any}, {\"Part Description\", type text}, {\"Capacity C0 LSL (nF)\", Int64.Type}, {\"Capacity C0 USL (nF)\", Int64.Type}, {\"Hold Time MA LSL (us)\", type number}, {\"Hold Time MA USL (us)\", type number}, {\"Hold Time MI LSL (us)\", Int64.Type}, {\"Hold Time MI USL (us)\", Int64.Type}, {\"Fall Time Negative Edge UCp LSL (ns)\", Int64.Type}, {\"Fall Time Negative Edge UCp USL (ns)\", Int64.Type}, {\"Transfer Time LSL (us)\", type number}, {\"Transfer Time USL (us)\", type number}, {\"Negative Voltage C1 LSL (kV)\", Int64.Type}, {\"Negative Voltage C1 USL (kV)\", Int64.Type}, {\"Negative Voltage Cp LSL (kV)\", Int64.Type}, {\"Negative Voltage Cp USL (kV)\", Int64.Type}, {\"Negative Voltage IGBT LSL (V)\", Int64.Type}, {\"Negative Voltage IGBT USL (V)\", Int64.Type}})\r\nin\r\n  #\"Changed column type\"\r\nin\r\n  Source;\r\nshared Cumulus_Assemblies_nonOracle = let\r\n  Source = Cumulus_Assemblies,\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each [ORACLE ITEM TYPE] = null)\r\nin\r\n  #\"Filtered rows\";\r\nshared Cumulus_Assy_Tags = let\r\n  Source = Table.Combine({#\"Assemblies-VHP-API\", #\"Assemblies-MP-API\", #\"Assemblies-LP-API\", #\"Assemblies-BDS-API\", #\"Assemblies-Optic-API\", #\"Assemblies-General-API\"}),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each [PART_DESCRIPTION] <> \"Dummy Assembly\"),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Filtered rows\", {{\"PART_NUMBER\", \"Part Number\"}, {\"PART_DESCRIPTION\", \"Part Description\"}, {\"WIP_DISPLAY\", \"WIP DISPLAY\"}, {\"IN_SYNC\", \"IN SYNC\"}, {\"WORK_CELL\", \"Work Cell\"}, {\"PRODUCTION_TYPE\", \"PRODUCTION TYPE\"}, {\"DEFAULT_CONTAINER\", \"DEFAULT CONTAINER\"}, {\"FLOW_NAME\", \"Flow Name\"}, {\"CREATE_DATE\", \"Created\"}, {\"MODIFY_DATE\", \"Modified\"}, {\"AGILE_LIFECYCLE\", \"AGILE LIFECYCLE\"}, {\"ORACLE_ITEM_TYPE\", \"ORACLE ITEM TYPE\"}, {\"ORACLE_ROUTING_TYPE\", \"ORACLE ROUTING TYPE\"}, {\"ORACLE_TBU\", \"ORACLE TBU\"}, {\"ORACLE_PRODUCT_FAMILY\", \"ORACLE PRODUCT FAMILY\"}, {\"ORACLE_PRODUCT_LINE\", \"ORACLE PRODUCT LINE\"}, {\"ORACLE_FORECAST_FIELD\", \"ORACLE FORECAST FIELD\"}, {\"TAGS\", \"Tags\"}}),\r\n  #\"Removed duplicates\" = Table.Distinct(#\"Renamed columns\", {\"Part Number\"}),\r\n  #\"Choose columns\" = Table.SelectColumns(#\"Removed duplicates\", {\"Part Number\", \"Work Cell\", \"Tags\"}),\r\n  #\"Split column by delimiter\" = Table.SplitColumn(#\"Choose columns\", \"Tags\", Splitter.SplitTextByDelimiter(\",\"), {\"Tags.1\", \"Tags.2\", \"Tags.3\", \"Tags.4\", \"Tags.5\", \"Tags.6\"}),\r\n  #\"Unpivoted other columns\" = Table.UnpivotOtherColumns(#\"Split column by delimiter\", {\"Part Number\", \"Work Cell\"}, \"Attribute\", \"Tags\"),\r\n  #\"Filtered rows 1\" = Table.SelectRows(#\"Unpivoted other columns\", each [Tags] <> \"(ALL)\"),\r\n  #\"Removed columns\" = Table.RemoveColumns(#\"Filtered rows 1\", {\"Attribute\"})\r\nin\r\n  #\"Removed columns\";\r\nshared #\"Assemblies-Optic-API\" = let\r\n  Source = Json.Document(Web.Contents(\"https://prod-cumulus.azurefd.net/prod/reporting/v1.0/api/Assemblies/Production/GEP/VHP/Optic/GEP\", [Headers=[Authorization=parToken]])),\r\n  #\"Converted to table\" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),\r\n  #\"Expanded Column1\" = Table.ExpandRecordColumn(#\"Converted to table\", \"Column1\", {\"TYPE\", \"PART_NUMBER\", \"PART_DESCRIPTION\", \"REVISION\", \"WIP_DISPLAY\", \"SERIAL_CONTROL\", \"LOT_CONTROL\", \"AGILE_AUTO_SYNC\", \"IN_SYNC\", \"AUTO_SERIALIZE\", \"WORK_CELL\", \"PRODUCTION_TYPE\", \"DEFAULT_CONTAINER\", \"FLOW_NAME\", \"TAGS\", \"AGILE_DOCUMENT\", \"CREATE_DATE\", \"MODIFY_DATE\", \"SERIAL_NUMBER_FORMAT\", \"VARIABLE_COMP_QTY\", \"MAXIMUM_LOT_SIZE\", \"MAXIMUMN_BATCH_SIZE\", \"ORACLE_GENERIC_PN\", \"ORACLE_DISCRETE_COMP\", \"ORACLE_WORK_ORDERLESS_COMP\", \"ORACLE_IMPORT_BOM\", \"ORACLE_IMPORT_BOM_BULK\", \"ORACLE_MOVE_TX\", \"ORACLE_RELEASE_TX\", \"ORACLE_MATERIAL_TX\", \"ORACLE_RESOURCE_TX\", \"ORACLE_RESOURCE_VALIDATION\", \"ORACLE_WO_IMPORT\", \"ORACLE_QUICK_WO\", \"QUEUE_AUTO_ADD\", \"ORACLE_ITEM_TYPE\", \"ORACLE_ROUTING_TYPE\", \"ORACLE_TBU\", \"ORACLE_PRODUCT_FAMILY\", \"ORACLE_PRODUCT_LINE\", \"ORACLE_FORECAST_FIELD\", \"AGILE_LIFECYCLE\"}, {\"TYPE\", \"PART_NUMBER\", \"PART_DESCRIPTION\", \"REVISION\", \"WIP_DISPLAY\", \"SERIAL_CONTROL\", \"LOT_CONTROL\", \"AGILE_AUTO_SYNC\", \"IN_SYNC\", \"AUTO_SERIALIZE\", \"WORK_CELL\", \"PRODUCTION_TYPE\", \"DEFAULT_CONTAINER\", \"FLOW_NAME\", \"TAGS\", \"AGILE_DOCUMENT\", \"CREATE_DATE\", \"MODIFY_DATE\", \"SERIAL_NUMBER_FORMAT\", \"VARIABLE_COMP_QTY\", \"MAXIMUM_LOT_SIZE\", \"MAXIMUMN_BATCH_SIZE\", \"ORACLE_GENERIC_PN\", \"ORACLE_DISCRETE_COMP\", \"ORACLE_WORK_ORDERLESS_COMP\", \"ORACLE_IMPORT_BOM\", \"ORACLE_IMPORT_BOM_BULK\", \"ORACLE_MOVE_TX\", \"ORACLE_RELEASE_TX\", \"ORACLE_MATERIAL_TX\", \"ORACLE_RESOURCE_TX\", \"ORACLE_RESOURCE_VALIDATION\", \"ORACLE_WO_IMPORT\", \"ORACLE_QUICK_WO\", \"QUEUE_AUTO_ADD\", \"ORACLE_ITEM_TYPE\", \"ORACLE_ROUTING_TYPE\", \"ORACLE_TBU\", \"ORACLE_PRODUCT_FAMILY\", \"ORACLE_PRODUCT_LINE\", \"ORACLE_FORECAST_FIELD\", \"AGILE_LIFECYCLE\"}),\r\n  #\"Added custom\" = Table.AddColumn(#\"Expanded Column1\", \"Sandbox\", each \"Optic\"),\r\n  #\"Choose columns\" = Table.SelectColumns(#\"Added custom\", {\"TYPE\", \"PART_NUMBER\", \"PART_DESCRIPTION\", \"REVISION\", \"WIP_DISPLAY\", \"IN_SYNC\", \"WORK_CELL\", \"PRODUCTION_TYPE\", \"DEFAULT_CONTAINER\", \"FLOW_NAME\", \"TAGS\", \"CREATE_DATE\", \"MODIFY_DATE\", \"ORACLE_ITEM_TYPE\", \"ORACLE_ROUTING_TYPE\", \"ORACLE_TBU\", \"ORACLE_PRODUCT_FAMILY\", \"ORACLE_PRODUCT_LINE\", \"ORACLE_FORECAST_FIELD\", \"AGILE_LIFECYCLE\", \"Sandbox\"}),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Choose columns\", {{\"TYPE\", type text}, {\"PART_NUMBER\", type text}, {\"PART_DESCRIPTION\", type text}, {\"REVISION\", type text}, {\"WIP_DISPLAY\", type text}, {\"IN_SYNC\", type logical}, {\"WORK_CELL\", type text}, {\"PRODUCTION_TYPE\", type text}, {\"DEFAULT_CONTAINER\", type text}, {\"FLOW_NAME\", type text}, {\"TAGS\", type text}, {\"CREATE_DATE\", type datetime}, {\"MODIFY_DATE\", type datetime}, {\"ORACLE_ITEM_TYPE\", type text}, {\"ORACLE_ROUTING_TYPE\", type text}, {\"ORACLE_TBU\", type text}, {\"ORACLE_PRODUCT_FAMILY\", type text}, {\"ORACLE_PRODUCT_LINE\", type text}, {\"ORACLE_FORECAST_FIELD\", type text}, {\"AGILE_LIFECYCLE\", type text}, {\"Sandbox\", type text}})\r\nin\r\n  #\"Changed column type\";\r\nshared #\"Assemblies-General-API\" = let\r\n  Source = Json.Document(Web.Contents(\"https://prod-cumulus.azurefd.net/prod/reporting/v1.0/api/Assemblies/Production/GEP/All/General/GEP\", [Headers=[Authorization=parToken]])),\r\n  #\"Converted to table\" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),\r\n  #\"Expanded Column1\" = Table.ExpandRecordColumn(#\"Converted to table\", \"Column1\", {\"TYPE\", \"PART_NUMBER\", \"PART_DESCRIPTION\", \"REVISION\", \"WIP_DISPLAY\", \"SERIAL_CONTROL\", \"LOT_CONTROL\", \"AGILE_AUTO_SYNC\", \"IN_SYNC\", \"AUTO_SERIALIZE\", \"WORK_CELL\", \"PRODUCTION_TYPE\", \"DEFAULT_CONTAINER\", \"FLOW_NAME\", \"TAGS\", \"AGILE_DOCUMENT\", \"CREATE_DATE\", \"MODIFY_DATE\", \"SERIAL_NUMBER_FORMAT\", \"VARIABLE_COMP_QTY\", \"MAXIMUM_LOT_SIZE\", \"MAXIMUMN_BATCH_SIZE\", \"ORACLE_GENERIC_PN\", \"ORACLE_DISCRETE_COMP\", \"ORACLE_WORK_ORDERLESS_COMP\", \"ORACLE_IMPORT_BOM\", \"ORACLE_IMPORT_BOM_BULK\", \"ORACLE_MOVE_TX\", \"ORACLE_RELEASE_TX\", \"ORACLE_MATERIAL_TX\", \"ORACLE_RESOURCE_TX\", \"ORACLE_RESOURCE_VALIDATION\", \"ORACLE_WO_IMPORT\", \"ORACLE_QUICK_WO\", \"QUEUE_AUTO_ADD\", \"ORACLE_ITEM_TYPE\", \"ORACLE_ROUTING_TYPE\", \"ORACLE_TBU\", \"ORACLE_PRODUCT_FAMILY\", \"ORACLE_PRODUCT_LINE\", \"ORACLE_FORECAST_FIELD\", \"AGILE_LIFECYCLE\"}, {\"TYPE\", \"PART_NUMBER\", \"PART_DESCRIPTION\", \"REVISION\", \"WIP_DISPLAY\", \"SERIAL_CONTROL\", \"LOT_CONTROL\", \"AGILE_AUTO_SYNC\", \"IN_SYNC\", \"AUTO_SERIALIZE\", \"WORK_CELL\", \"PRODUCTION_TYPE\", \"DEFAULT_CONTAINER\", \"FLOW_NAME\", \"TAGS\", \"AGILE_DOCUMENT\", \"CREATE_DATE\", \"MODIFY_DATE\", \"SERIAL_NUMBER_FORMAT\", \"VARIABLE_COMP_QTY\", \"MAXIMUM_LOT_SIZE\", \"MAXIMUMN_BATCH_SIZE\", \"ORACLE_GENERIC_PN\", \"ORACLE_DISCRETE_COMP\", \"ORACLE_WORK_ORDERLESS_COMP\", \"ORACLE_IMPORT_BOM\", \"ORACLE_IMPORT_BOM_BULK\", \"ORACLE_MOVE_TX\", \"ORACLE_RELEASE_TX\", \"ORACLE_MATERIAL_TX\", \"ORACLE_RESOURCE_TX\", \"ORACLE_RESOURCE_VALIDATION\", \"ORACLE_WO_IMPORT\", \"ORACLE_QUICK_WO\", \"QUEUE_AUTO_ADD\", \"ORACLE_ITEM_TYPE\", \"ORACLE_ROUTING_TYPE\", \"ORACLE_TBU\", \"ORACLE_PRODUCT_FAMILY\", \"ORACLE_PRODUCT_LINE\", \"ORACLE_FORECAST_FIELD\", \"AGILE_LIFECYCLE\"}),\r\n  #\"Added custom\" = Table.AddColumn(#\"Expanded Column1\", \"Sandbox\", each \"General\"),\r\n  #\"Choose columns\" = Table.SelectColumns(#\"Added custom\", {\"TYPE\", \"PART_NUMBER\", \"PART_DESCRIPTION\", \"REVISION\", \"WIP_DISPLAY\", \"IN_SYNC\", \"WORK_CELL\", \"PRODUCTION_TYPE\", \"DEFAULT_CONTAINER\", \"FLOW_NAME\", \"TAGS\", \"CREATE_DATE\", \"MODIFY_DATE\", \"ORACLE_ITEM_TYPE\", \"ORACLE_ROUTING_TYPE\", \"ORACLE_TBU\", \"ORACLE_PRODUCT_FAMILY\", \"ORACLE_PRODUCT_LINE\", \"ORACLE_FORECAST_FIELD\", \"AGILE_LIFECYCLE\", \"Sandbox\"}),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Choose columns\", {{\"TYPE\", type text}, {\"PART_NUMBER\", type text}, {\"PART_DESCRIPTION\", type text}, {\"REVISION\", type text}, {\"WIP_DISPLAY\", type text}, {\"IN_SYNC\", type logical}, {\"WORK_CELL\", type text}, {\"PRODUCTION_TYPE\", type text}, {\"DEFAULT_CONTAINER\", type text}, {\"FLOW_NAME\", type text}, {\"TAGS\", type text}, {\"CREATE_DATE\", type datetime}, {\"MODIFY_DATE\", type datetime}, {\"ORACLE_ITEM_TYPE\", type text}, {\"ORACLE_ROUTING_TYPE\", type text}, {\"ORACLE_TBU\", type text}, {\"ORACLE_PRODUCT_FAMILY\", type text}, {\"ORACLE_PRODUCT_LINE\", type text}, {\"ORACLE_FORECAST_FIELD\", type text}, {\"AGILE_LIFECYCLE\", type text}, {\"Sandbox\", type text}})\r\nin\r\n  #\"Changed column type\";\r\nshared WIP_Completion_Status = let\r\n  Source = SharePoint.Tables(\"https://cohrinc.sharepoint.com/sites/GEPMEPowerBIReports-AdminChannel\", [ApiVersion = 15]),\r\n  Navigation = Source{[Id = \"a719c189-0bdb-4f6c-8803-b7975df86607\"]}[Items],\r\n  #\"Choose columns\" = Table.SelectColumns(Navigation, {\"Title\", \"Description\", \"Flow Index\", \"WIP Completion Statu\", \"Flow\", \"Work Cell\", \"Sandbox\", \"ID\", \"Modified\", \"Created\"}),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Choose columns\", {{\"Title\", type text}, {\"Description\", type text}, {\"Flow\", type text}, {\"Work Cell\", type text}, {\"Sandbox\", type text}, {\"Flow Index\", Int64.Type}, {\"ID\", Int64.Type}, {\"WIP Completion Statu\", Percentage.Type}, {\"Modified\", type datetime}, {\"Created\", type datetime}}),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Changed column type\", {{\"Title\", \"Process\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared #\"Cumulus_Attribute-MainsPower\" = let\r\n  Source = SharePoint.Tables(\"https://cohrinc.sharepoint.com/sites/GEPMEPowerBIReports\", [ApiVersion = 15]),\r\n  Navigation = Source{[Id = \"122e0fa9-05ab-4b00-a5b8-a3651c3bf11d\"]}[Items],\r\n  #\"Choose columns\" = Table.SelectColumns(Navigation, {\"ID\", \"Title\", \"field_Assy Description\", \"field_Attribute Name\", \"field_Attribute Value\", \"field_Description\", \"field_UOM\", \"field_Sandbox\"}),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Choose columns\", {{\"ID\", type text}, {\"Title\", type text}, {\"field_Assy Description\", type text}, {\"field_Attribute Name\", type text}, {\"field_Description\", type text}, {\"field_UOM\", type text}, {\"field_Sandbox\", type text}, {\"field_Attribute Value\", type number}}),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Changed column type\", {{\"Title\", \"Part Number\"}, {\"field_Assy Description\", \"Assy Description\"}, {\"field_Attribute Name\", \"Attribute Name\"}, {\"field_Attribute Value\", \"Attribute Value\"}, {\"field_Description\", \"Attribute Description\"}, {\"field_UOM\", \"UOM\"}, {\"field_Sandbox\", \"Sandbox\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared #\"Cumulus_ET-LDU_Testbeds\" = let\r\n  Source = SharePoint.Tables(\"https://cohrinc.sharepoint.com/sites/GEPMEPowerBIReports\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Title] = \"Cumulus_ET-LDU_Testbed_Definitions\"),\r\n  #\"Removed other columns\" = Table.SelectColumns(#\"Filtered rows\", {\"Items\"}),\r\n  #\"Expanded Items\" = Table.ExpandTableColumn(#\"Removed other columns\", \"Items\", {\"ID\", \"Title\", \"field_Test Laser\", \"field_Test Laser Nummer\", \"field_Fab\"}, {\"ID\", \"Title\", \"field_Test Laser\", \"field_Test Laser Nummer\", \"field_Fab\"}),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Expanded Items\", {{\"ID\", Int64.Type}}),\r\n  #\"Changed column type 1\" = Table.TransformColumnTypes(#\"Changed column type\", {{\"ID\", type text}, {\"Title\", type text}, {\"field_Test Laser\", type text}, {\"field_Test Laser Nummer\", type text}, {\"field_Fab\", type text}}),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Changed column type 1\", {{\"Title\", \"Testbed_DRCfile\"}, {\"field_Test Laser\", \"Test Laser\"}, {\"field_Test Laser Nummer\", \"Test Laser Number\"}, {\"field_Fab\", \"Fab\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared #\"Sample file\" = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Extension] = \".xlsx\" and [Name] = \"Specs_Cryo_SPC.xlsx\"),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows\", each [Attributes]?[Hidden]? <> true),\r\n  Navigation = #\"Filtered hidden files\"{0}[Content]\r\nin\r\n  Navigation;\r\nshared Parameter = let\r\n  Parameter = #\"Sample file\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type binary, BinaryIdentifier = #\"Sample file\"]\r\nin\r\n  Parameter;\r\nshared #\"Transform Sample file\" = let\r\n  Source = Excel.Workbook(Parameter, null, true),\r\n  Navigation = Source{[Item = \"Tabelle1\", Kind = \"Sheet\"]}[Data],\r\n  #\"Promoted headers\" = Table.PromoteHeaders(Navigation, [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"Part Number\", type any}, {\"Part Description\", type text}, {\"leakage rate sniffer USL (mbar*l/s)\", type number}, {\"Helium background USL (mbar*l/s)\", type number}, {\"heating resistance USL (Ω)\", type number}, {\"heating resistance LSL (Ω)\", type number}, {\"Gas Pressure Drop USL (mbar/12 h)\", Int64.Type}, {\"Gas Pressure Drop LSL (mbar/12 h)\", Int64.Type}, {\"Gas Pressure Drop USL (mbar/24 h)\", Int64.Type}, {\"Gas Pressure Drop LSL (mbar/24 h)\", Int64.Type}, {\"leakage rate USL (mbar*l/s)\", type number}, {\"leakage rate LSL (mbar*l/s)\", Int64.Type}, {\"water pressure drop USL (mbar/h)\", Int64.Type}, {\"cool down time USL (min)\", Int64.Type}, {\"cool down time LSL (min)\", Int64.Type}})\r\nin\r\n  #\"Changed column type\";\r\nshared #\"Transform file\" = let\r\n  Source = (Parameter as binary) => let\r\n  Source = Excel.Workbook(Parameter, null, true),\r\n  Navigation = Source{[Item = \"Tabelle1\", Kind = \"Sheet\"]}[Data],\r\n  #\"Promoted headers\" = Table.PromoteHeaders(Navigation, [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"Part Number\", type any}, {\"Part Description\", type text}, {\"leakage rate sniffer USL (mbar*l/s)\", type number}, {\"Helium background USL (mbar*l/s)\", type number}, {\"heating resistance USL (Ω)\", type number}, {\"heating resistance LSL (Ω)\", type number}, {\"Gas Pressure Drop USL (mbar/12 h)\", Int64.Type}, {\"Gas Pressure Drop LSL (mbar/12 h)\", Int64.Type}, {\"Gas Pressure Drop USL (mbar/24 h)\", Int64.Type}, {\"Gas Pressure Drop LSL (mbar/24 h)\", Int64.Type}, {\"leakage rate USL (mbar*l/s)\", type number}, {\"leakage rate LSL (mbar*l/s)\", Int64.Type}, {\"water pressure drop USL (mbar/h)\", Int64.Type}, {\"cool down time USL (min)\", Int64.Type}, {\"cool down time LSL (min)\", Int64.Type}})\r\nin\r\n  #\"Changed column type\"\r\nin\r\n  Source;\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[{\"id\":\"a9f787c3-5836-4971-a87f-abb5a3f0c08f\",\"name\":\"Transform file from Assemblies_Additional_Details\",\"description\":\"\",\"parentId\":null,\"order\":1},{\"id\":\"0d9c8663-2391-4f39-be01-308370107f54\",\"name\":\"Helper queries (2)\",\"description\":\"\",\"parentId\":\"a9f787c3-5836-4971-a87f-abb5a3f0c08f\",\"order\":2},{\"id\":\"0eeb2670-ad87-44b4-b1db-b4803aefb3d5\",\"name\":\"Transform file from Specs_VHP_Tube-FinalTest\",\"description\":\"\",\"parentId\":null,\"order\":1},{\"id\":\"04ec3c9c-05c8-4eca-bc0c-a0da46a77ec0\",\"name\":\"Helper queries (3)\",\"description\":\"\",\"parentId\":\"0eeb2670-ad87-44b4-b1db-b4803aefb3d5\",\"order\":2},{\"id\":\"3a8dfb1f-b104-4f8e-967d-ed50925bbcf0\",\"name\":\"Transform file from Location_Fabs\",\"description\":\"\",\"parentId\":null,\"order\":1},{\"id\":\"722f712a-503f-41e5-97a6-ccb4688e96e8\",\"name\":\"Helper queries (4)\",\"description\":\"\",\"parentId\":\"3a8dfb1f-b104-4f8e-967d-ed50925bbcf0\",\"order\":2},{\"id\":\"7e966377-fc38-4fca-a6a6-819bd13c179c\",\"name\":\"Transform file from Location_Sites\",\"description\":\"\",\"parentId\":null,\"order\":1},{\"id\":\"5839e6a6-69c8-4ec7-b40c-94762c590f5c\",\"name\":\"Helper queries (5)\",\"description\":\"\",\"parentId\":\"7e966377-fc38-4fca-a6a6-819bd13c179c\",\"order\":2},{\"id\":\"719944be-8b04-4531-b684-88caf8948e62\",\"name\":\"Inactive\",\"description\":\"\",\"parentId\":null,\"order\":0},{\"id\":\"8d02fddc-48c6-441f-92e2-0e3d3295117f\",\"name\":\"Transform file from Specs_ASSP Assembly\",\"description\":null,\"parentId\":null,\"order\":0},{\"id\":\"17eba0d3-cc81-4bc7-a962-302e58d4879f\",\"name\":\"Helper queries (6)\",\"description\":null,\"parentId\":\"8d02fddc-48c6-441f-92e2-0e3d3295117f\",\"order\":0},{\"id\":\"cd29e21a-0788-4b7d-a13d-47c4d2a5d39f\",\"name\":\"Transform file from Specs_Cryo\",\"description\":null,\"parentId\":null,\"order\":0},{\"id\":\"caa68850-1c41-4387-8d34-92a3e5e9613a\",\"name\":\"Helper queries\",\"description\":null,\"parentId\":\"cd29e21a-0788-4b7d-a13d-47c4d2a5d39f\",\"order\":0}]"}],"entities":[{"$type":"LocalEntity","name":"Specs_VHP_Tube-FinalTest","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Specs_VHP_Tube-FinalTest.csv"},"attributes":[{"name":"Part Number","dataType":"string"},{"name":"Part Description","dataType":"string"},{"name":"BW FWHM SA LSL (mm)","dataType":"double"},{"name":"BW FWHM SA USL (mm)","dataType":"double"},{"name":"BW FWHM LA LSL (mm)","dataType":"int64"},{"name":"BW FWHM LA USL (mm)","dataType":"int64"},{"name":"BW 1/e² SA LSL (mm)","dataType":"int64"},{"name":"BW 1/e² SA USL (mm)","dataType":"int64"},{"name":"BW 1/e² LA LSL (mm)","dataType":"int64"},{"name":"BW 1/e² LA USL (mm)","dataType":"int64"},{"name":"Beam Asym. SA LSL (%)","dataType":"int64"},{"name":"Beam Asym. SA USL (%)","dataType":"int64"},{"name":"Beam Asym. LA LSL (%)","dataType":"int64"},{"name":"Beam Asym. LA USL (%)","dataType":"int64"},{"name":"Divergency SA LSL (mrad)","dataType":"int64"},{"name":"Divergency SA USL (mrad)","dataType":"double"},{"name":"Divergency LA LSL (mrad)","dataType":"int64"},{"name":"Divergency LA USL (mrad)","dataType":"double"},{"name":"Beam Point. Stab. SA LSL (mrad)","dataType":"int64"},{"name":"Beam Point. Stab. SA USL (mrad)","dataType":"double"},{"name":"Beam Point. Stab. LA LSL (mrad)","dataType":"int64"},{"name":"Beam Point. Stab. LA USL (mrad)","dataType":"double"},{"name":"Beam Pos. Stab. SA LSL (mm)","dataType":"double"},{"name":"Beam Pos. Stab. SA USL (mm)","dataType":"double"},{"name":"Beam Pos. Stab. LA LSL (mm)","dataType":"double"},{"name":"Beam Pos. Stab. LA USL (mm)","dataType":"double"},{"name":"HV Start LSL (kV)","dataType":"double"},{"name":"HV Start USL (kV)","dataType":"double"},{"name":"HV Rise LSL (V)","dataType":"double"},{"name":"HV Rise USL (V)","dataType":"double"},{"name":"Sigma Start LSL (%)","dataType":"double"},{"name":"Sigma Start USL (%)","dataType":"double"},{"name":"Sigma End LSL (%)","dataType":"double"},{"name":"Sigma End USL (%)","dataType":"double"},{"name":"Sigma Average LSL (%)","dataType":"double"},{"name":"Sigma Average USL (%)","dataType":"double"},{"name":"Sigma Max LSL (%)","dataType":"double"},{"name":"Sigma Max USL (%)","dataType":"double"},{"name":"2nd Hump Start LSL (%)","dataType":"double"},{"name":"2nd Hump Start USL (%)","dataType":"double"},{"name":"2nd Hump End LSL (%)","dataType":"double"},{"name":"2nd Hump End USL (%)","dataType":"double"},{"name":"Transmission Loss OC P3 LSL (%/10Mio Pulse)","dataType":"double"},{"name":"Transmission Loss OC P3 USL (%/10Mio Pulse)","dataType":"double"},{"name":"Transmission Loss HR P3 LSL (%/10Mio Pulse)","dataType":"double"},{"name":"Transmission Loss HR P3 USL (%/10Mio Pulse)","dataType":"double"},{"name":"User Counter LSL (Mio. Pulses)","dataType":"double"},{"name":"User Counter USL (Mio. Pulses)","dataType":"double"},{"name":"10Mio Run HV Start LSL (kV)","dataType":"double"},{"name":"10Mio Run HV Start USL (kV)","dataType":"double"},{"name":"10Mio Run E Difference LSL (%)","dataType":"double"},{"name":"10Mio Run E Difference USL (%)","dataType":"double"},{"name":"75 Mio Run HV Start LSL (kV)","dataType":"double"},{"name":"75 Mio Run HV Start USL (kV)","dataType":"double"},{"name":"75 Mio Run HV Rise LSL (V)","dataType":"double"},{"name":"75 Mio Run HV Rise USL (V)","dataType":"double"},{"name":"75 Mio Run Sigma Start LSL (%)","dataType":"double"},{"name":"75 Mio Run Sigma Start USL (%)","dataType":"double"},{"name":"75 Mio Run Sigma Max Internal LSL (%)","dataType":"double"},{"name":"75 Mio Run Sigma Max Internal USL (%)","dataType":"double"},{"name":"Divergency SA End LSL (mrad)","dataType":"double"},{"name":"Divergency SA End USL (mrad)","dataType":"double"},{"name":"User Counter Target (Mio. Pulses)","dataType":"int64"}],"partitions":[{"name":"Part001","refreshTime":"2022-03-21T10:18:00.2821889+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/054d7164-b108-46a6-8930-b43a5cd24c49/Specs_VHP_Tube-FinalTest.csv?snapshot=2022-03-21T10%3A18%3A00.2641279Z"}]},{"$type":"LocalEntity","name":"Specs_ASSP Assembly","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Specs_ASSP%20Assembly.csv"},"attributes":[{"name":"Part Number","dataType":"string"},{"name":"Part Description","dataType":"string"},{"name":"Capacity C0 LSL (nF)","dataType":"int64"},{"name":"Capacity C0 USL (nF)","dataType":"int64"},{"name":"Hold Time MA LSL (us)","dataType":"double"},{"name":"Hold Time MA USL (us)","dataType":"double"},{"name":"Hold Time MI LSL (us)","dataType":"int64"},{"name":"Hold Time MI USL (us)","dataType":"int64"},{"name":"Fall Time Negative Edge UCp LSL (ns)","dataType":"int64"},{"name":"Fall Time Negative Edge UCp USL (ns)","dataType":"int64"},{"name":"Transfer Time LSL (us)","dataType":"double"},{"name":"Transfer Time USL (us)","dataType":"double"},{"name":"Negative Voltage C1 LSL (kV)","dataType":"int64"},{"name":"Negative Voltage C1 USL (kV)","dataType":"int64"},{"name":"Negative Voltage Cp LSL (kV)","dataType":"int64"},{"name":"Negative Voltage Cp USL (kV)","dataType":"int64"},{"name":"Negative Voltage IGBT LSL (V)","dataType":"int64"},{"name":"Negative Voltage IGBT USL (V)","dataType":"int64"}],"partitions":[{"name":"Part001","refreshTime":"2022-03-21T10:18:00.3290843+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/054d7164-b108-46a6-8930-b43a5cd24c49/Specs_ASSP%20Assembly.csv?snapshot=2022-03-21T10%3A18%3A00.2821177Z"}]},{"$type":"LocalEntity","name":"Specs_Cryo","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Specs_Cryo.csv"},"attributes":[{"name":"Part Number","dataType":"string"},{"name":"Part Description","dataType":"string"},{"name":"leakage rate sniffer USL (mbar*l/s)","dataType":"double"},{"name":"Helium background USL (mbar*l/s)","dataType":"double"},{"name":"heating resistance USL (Ω)","dataType":"double"},{"name":"heating resistance LSL (Ω)","dataType":"double"},{"name":"Gas Pressure Drop USL (mbar/12 h)","dataType":"int64"},{"name":"Gas Pressure Drop LSL (mbar/12 h)","dataType":"int64"},{"name":"Gas Pressure Drop USL (mbar/24 h)","dataType":"int64"},{"name":"Gas Pressure Drop LSL (mbar/24 h)","dataType":"int64"},{"name":"leakage rate USL (mbar*l/s)","dataType":"double"},{"name":"leakage rate LSL (mbar*l/s)","dataType":"int64"},{"name":"water pressure drop USL (mbar/h)","dataType":"int64"},{"name":"cool down time USL (min)","dataType":"int64"},{"name":"cool down time LSL (min)","dataType":"int64"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-03-21T10:18:00.2665379+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/054d7164-b108-46a6-8930-b43a5cd24c49/Specs_Cryo.csv?snapshot=2022-03-21T10%3A18%3A00.2411412Z"}]},{"$type":"LocalEntity","name":"DimDates","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"DimDates.csv"},"attributes":[{"name":"Date","dataType":"date"},{"name":"Year","dataType":"int64"},{"name":"Month","dataType":"int64"},{"name":"Month name","dataType":"string"},{"name":"Quarter","dataType":"int64"},{"name":"Week of year","dataType":"int64"},{"name":"Week of month","dataType":"int64"},{"name":"Day","dataType":"int64"},{"name":"Day of week","dataType":"int64"},{"name":"Day of year","dataType":"int64"},{"name":"Day name","dataType":"string"},{"name":"Month short","dataType":"string"},{"name":"Qtr","dataType":"string"},{"name":"WorkDay","dataType":"int64"},{"name":"Fiscal year","dataType":"int64"},{"name":"Fiscal quarter","dataType":"int64"},{"name":"Fiscal month","dataType":"int64"},{"name":"FY","dataType":"string"},{"name":"FQ","dataType":"string"},{"name":"Fiscal month short","dataType":"string"},{"name":"Index","dataType":"int64"},{"name":"CW","dataType":"int64"},{"name":"YearMonthID","dataType":"string"},{"name":"Year_Short","dataType":"string"},{"name":"Month_Year","dataType":"string"},{"name":"Year_CW","dataType":"string"},{"name":"Year-Month","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-03-21T10:17:36.843418+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/054d7164-b108-46a6-8930-b43a5cd24c49/DimDates.csv?snapshot=2022-03-21T10%3A17%3A36.8105530Z"}]},{"$type":"LocalEntity","name":"Location_Fabs","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Location_Fabs.csv"},"attributes":[{"name":"Department","dataType":"string"},{"name":"Fab","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-03-21T10:18:00.3134423+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/054d7164-b108-46a6-8930-b43a5cd24c49/Location_Fabs.csv?snapshot=2022-03-21T10%3A18%3A00.2671268Z"}]},{"$type":"LocalEntity","name":"Location_Sites","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Location_Sites.csv"},"attributes":[{"name":"Business Unit","dataType":"string"},{"name":"Site Name","dataType":"string"},{"name":"Country Code","dataType":"string"},{"name":"Country","dataType":"string"},{"name":"ZIP Code","dataType":"string"},{"name":"City","dataType":"string"},{"name":"Latitude","dataType":"double"},{"name":"Longitude","dataType":"double"},{"name":"Fab","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-03-21T10:18:00.0322462+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/054d7164-b108-46a6-8930-b43a5cd24c49/Location_Sites.csv?snapshot=2022-03-21T10%3A18%3A00.0022778Z"}]},{"$type":"LocalEntity","name":"Cumulus_Assemblies","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Cumulus_Assemblies.csv"},"attributes":[{"name":"TYPE","dataType":"string"},{"name":"Part Number","dataType":"string"},{"name":"Part Description","dataType":"string"},{"name":"REVISION","dataType":"string"},{"name":"WIP DISPLAY","dataType":"string"},{"name":"IN SYNC","dataType":"boolean"},{"name":"Work Cell","dataType":"string"},{"name":"PRODUCTION TYPE","dataType":"string"},{"name":"DEFAULT CONTAINER","dataType":"string"},{"name":"Flow Name","dataType":"string"},{"name":"Tags","dataType":"string"},{"name":"Created","dataType":"dateTime"},{"name":"Modified","dataType":"dateTime"},{"name":"ORACLE ITEM TYPE","dataType":"string"},{"name":"ORACLE ROUTING TYPE","dataType":"string"},{"name":"ORACLE TBU","dataType":"string"},{"name":"ORACLE PRODUCT FAMILY","dataType":"string"},{"name":"ORACLE PRODUCT LINE","dataType":"string"},{"name":"ORACLE FORECAST FIELD","dataType":"string"},{"name":"AGILE LIFECYCLE","dataType":"string"},{"name":"Sandbox","dataType":"string"},{"name":"Alias","dataType":"string"},{"name":"Classification","dataType":"string"},{"name":"Department","dataType":"string"},{"name":"Labor Seq1 (h)","dataType":"double"},{"name":"Labor Seq2 (h)","dataType":"double"},{"name":"Labor Seq3 (h)","dataType":"double"},{"name":"Labor Seq4 (h)","dataType":"double"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-03-21T10:18:09.326749+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/054d7164-b108-46a6-8930-b43a5cd24c49/Cumulus_Assemblies.csv?snapshot=2022-03-21T10%3A18%3A08.6523264Z"}]},{"$type":"LocalEntity","name":"Cumulus_Assemblies_nonOracle","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Cumulus_Assemblies_nonOracle.csv"},"annotations":[{"name":"pbi:EntityTypeDisplayHint","value":"CalculatedEntity"}],"attributes":[{"name":"TYPE","dataType":"string"},{"name":"Part Number","dataType":"string"},{"name":"Part Description","dataType":"string"},{"name":"REVISION","dataType":"string"},{"name":"WIP DISPLAY","dataType":"string"},{"name":"IN SYNC","dataType":"boolean"},{"name":"Work Cell","dataType":"string"},{"name":"PRODUCTION TYPE","dataType":"string"},{"name":"DEFAULT CONTAINER","dataType":"string"},{"name":"Flow Name","dataType":"string"},{"name":"Tags","dataType":"string"},{"name":"Created","dataType":"dateTime"},{"name":"Modified","dataType":"dateTime"},{"name":"ORACLE ITEM TYPE","dataType":"string"},{"name":"ORACLE ROUTING TYPE","dataType":"string"},{"name":"ORACLE TBU","dataType":"string"},{"name":"ORACLE PRODUCT FAMILY","dataType":"string"},{"name":"ORACLE PRODUCT LINE","dataType":"string"},{"name":"ORACLE FORECAST FIELD","dataType":"string"},{"name":"AGILE LIFECYCLE","dataType":"string"},{"name":"Sandbox","dataType":"string"},{"name":"Alias","dataType":"string"},{"name":"Classification","dataType":"string"},{"name":"Department","dataType":"string"},{"name":"Labor Seq1 (h)","dataType":"double"},{"name":"Labor Seq2 (h)","dataType":"double"},{"name":"Labor Seq3 (h)","dataType":"double"},{"name":"Labor Seq4 (h)","dataType":"double"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-03-21T10:18:12.5708787+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/054d7164-b108-46a6-8930-b43a5cd24c49/Cumulus_Assemblies_nonOracle.csv?snapshot=2022-03-21T10%3A18%3A12.5440986Z"}]},{"$type":"LocalEntity","name":"Cumulus_Assy_Tags","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Cumulus_Assy_Tags.csv"},"attributes":[{"name":"Part Number","dataType":"string"},{"name":"Work Cell","dataType":"string"},{"name":"Tags","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-03-21T10:17:40.7655726+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/054d7164-b108-46a6-8930-b43a5cd24c49/Cumulus_Assy_Tags.csv?snapshot=2022-03-21T10%3A17%3A40.7403035Z"}]},{"$type":"LocalEntity","name":"WIP_Completion_Status","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"WIP_Completion_Status.csv"},"attributes":[{"name":"Process","dataType":"string"},{"name":"Description","dataType":"string"},{"name":"Flow Index","dataType":"int64"},{"name":"WIP Completion Statu","dataType":"double"},{"name":"Flow","dataType":"string"},{"name":"Work Cell","dataType":"string"},{"name":"Sandbox","dataType":"string"},{"name":"ID","dataType":"int64"},{"name":"Modified","dataType":"dateTime"},{"name":"Created","dataType":"dateTime"}],"partitions":[{"name":"Part001","refreshTime":"2022-03-21T10:17:54.5870915+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/054d7164-b108-46a6-8930-b43a5cd24c49/WIP_Completion_Status.csv?snapshot=2022-03-21T10%3A17%3A54.5703878Z"}]},{"$type":"LocalEntity","name":"Cumulus_Attribute-MainsPower","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Cumulus_Attribute-MainsPower.csv"},"attributes":[{"name":"ID","dataType":"string"},{"name":"Part Number","dataType":"string"},{"name":"Assy Description","dataType":"string"},{"name":"Attribute Name","dataType":"string"},{"name":"Attribute Value","dataType":"double"},{"name":"Attribute Description","dataType":"string"},{"name":"UOM","dataType":"string"},{"name":"Sandbox","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-03-21T10:17:48.0789867+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/054d7164-b108-46a6-8930-b43a5cd24c49/Cumulus_Attribute-MainsPower.csv?snapshot=2022-03-21T10%3A17%3A48.0561159Z"}]},{"$type":"LocalEntity","name":"Cumulus_ET-LDU_Testbeds","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Cumulus_ET-LDU_Testbeds.csv"},"attributes":[{"name":"ID","dataType":"string"},{"name":"Testbed_DRCfile","dataType":"string"},{"name":"Test Laser","dataType":"string"},{"name":"Test Laser Number","dataType":"string"},{"name":"Fab","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-03-21T10:17:53.6767491+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/054d7164-b108-46a6-8930-b43a5cd24c49/Cumulus_ET-LDU_Testbeds.csv?snapshot=2022-03-21T10%3A17%3A53.6509136Z"}]}]}