{"name":"Flow_SPC_ASSP_CRYO","description":"Cumulus ASSP & CRYO SPC data.","version":"1.0","culture":"en-US","modifiedTime":"2022-01-04T16:31:00.7864738+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"ASSP SPC Data":{"queryId":"bc8c6c25-bb48-457e-858c-6cb7d15c28c6","queryName":"ASSP SPC Data","queryGroupId":"e2b56a61-e003-4a42-af94-4a7062dac8b4"},"Sample file":{"queryId":"bec625b0-2489-4bfb-b543-3bd3b5288e83","queryName":"Sample file","queryGroupId":"e551fed4-556a-439a-b0c5-692dd28b6584"},"Parameter":{"queryId":"d17e0dc0-bc5b-4b79-8819-754a4d950cc2","queryName":"Parameter","queryGroupId":"e551fed4-556a-439a-b0c5-692dd28b6584"},"Transform Sample file":{"queryId":"2df3a667-2ce7-42e6-a0dc-c7d9557f5960","queryName":"Transform Sample file","queryGroupId":"3cf6d5d7-8b5d-4889-93d3-8626426f516a"},"Transform file":{"queryId":"ad574e87-a93a-440d-af51-3dce2f1dd276","queryName":"Transform file","queryGroupId":"e551fed4-556a-439a-b0c5-692dd28b6584"},"ASSP SPC API":{"queryId":"1b76f56f-cc1e-4058-9b8d-a95d212200e9","queryName":"ASSP SPC API","loadEnabled":true},"Sample file (2)":{"queryId":"5393da2b-ca18-46fd-876b-600ab5693783","queryName":"Sample file (2)","queryGroupId":"e28eaa03-961d-4424-9701-c23a2bb26d97"},"Parameter (2)":{"queryId":"4a79705a-26df-45e4-b78c-bcd39fa4ed7b","queryName":"Parameter (2)","queryGroupId":"e28eaa03-961d-4424-9701-c23a2bb26d97"},"Transform Sample file (2)":{"queryId":"385c9a65-dac0-4ae8-a1eb-9c278481a94b","queryName":"Transform Sample file (2)","queryGroupId":"5bf3fa6d-b99e-4430-8174-e1a1ae414783"},"Transform file (2)":{"queryId":"445c42c8-0142-46df-9d4e-f044c861ae8b","queryName":"Transform file (2)","queryGroupId":"e28eaa03-961d-4424-9701-c23a2bb26d97"},"ASSP SPC Specs":{"queryId":"e9fbcadb-631a-404c-b9b0-126fc671628b","queryName":"ASSP SPC Specs","queryGroupId":"e2b56a61-e003-4a42-af94-4a7062dac8b4"},"ASSP SPC UOM":{"queryId":"6b817f79-cd79-4250-9f29-799c0ef29fdb","queryName":"ASSP SPC UOM","queryGroupId":"e2b56a61-e003-4a42-af94-4a7062dac8b4"},"Cryo SPC API":{"queryId":"d912f771-3f9f-4682-b6d2-1a60e1df1e0b","queryName":"Cryo SPC API","loadEnabled":true},"Sample file (3)":{"queryId":"96f4e41f-3298-466b-867e-5aa2a73cf71c","queryName":"Sample file (3)","queryGroupId":"b11bccab-5eee-4948-81ae-9e410e0a264b"},"Parameter (3)":{"queryId":"3a757ff6-843e-4606-998f-6c1873f83eab","queryName":"Parameter (3)","queryGroupId":"b11bccab-5eee-4948-81ae-9e410e0a264b"},"Transform Sample file (3)":{"queryId":"cc5060ae-dbbb-4406-aac0-7807c4a854a0","queryName":"Transform Sample file (3)","queryGroupId":"d6f28379-255f-4f5a-a654-783a37b0cf07"},"Transform file (3)":{"queryId":"386f5550-6505-4942-8f1f-2d6b8d141802","queryName":"Transform file (3)","queryGroupId":"b11bccab-5eee-4948-81ae-9e410e0a264b"},"Cryo SPC Specs":{"queryId":"4b678362-d047-42d0-b4f1-280db83983bc","queryName":"Cryo SPC Specs","queryGroupId":"e2b56a61-e003-4a42-af94-4a7062dac8b4"},"Cryo SPC UOM":{"queryId":"a78e3dae-2471-4767-a83e-280035ef1957","queryName":"Cryo SPC UOM","queryGroupId":"e2b56a61-e003-4a42-af94-4a7062dac8b4"}},"document":"section Section1;\r\nshared #\"ASSP SPC Data\" = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Name] = \"ME-Power_BI-ASSP.xlsx\"),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows\", each [Attributes]?[Hidden]? <> true),\r\n  #\"Invoke custom function\" = Table.AddColumn(#\"Filtered hidden files\", \"Transform file\", each #\"Transform file\"([Content])),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Invoke custom function\", {{\"Name\", \"Source.Name\"}}),\r\n  #\"Removed other columns\" = Table.SelectColumns(#\"Renamed columns\", {\"Source.Name\", \"Transform file\"}),\r\n  #\"Expanded table column\" = Table.ExpandTableColumn(#\"Removed other columns\", \"Transform file\", Table.ColumnNames(#\"Transform file\"(#\"Sample file\"))),\r\n  #\"Choose columns\" = Table.SelectColumns(#\"Expanded table column\", {\"Work Order\", \"Type\", \"ORG\", \"Pass\\Fail\", \"Created\", \"Completed\", \"Part Number\", \"Description\", \"Serial Number\", \"AS-8 ASSP Pre Shipment Check : ASSP Reservoir SN\", \"AS-17 ASSP Capacity Check : Capacity C0\", \"AS-2 ASSP Leaktest : Leak Rate Oil Circuit\", \"AS-2 ASSP Leaktest : Leak Rate Reservoir\", \"AS-5 ASSP Final Test : Negative Voltage C0 Check\", \"AS-5 ASSP Final Test : Hold Time MI\", \"AS-5 ASSP Final Test : Hold Time MA\", \"AS-5 ASSP Final Test : Transfer Time\", \"AS-5 ASSP Final Test : Negative Voltage C1 Max\", \"AS-5 ASSP Final Test : Fall Time Negative Edge UCp\", \"AS-5 ASSP Final Test : Negative IGBT Voltage Max\", \"AS-5 ASSP Final Test : Negative Voltage Cp Max\", \"AS-6 ASSP Safety Test : Leakage Current\", \"AS-5 ASSP Final Test : Function Test Complete\"}),\r\n  #\"Changed column type with locale\" = Table.TransformColumnTypes(#\"Choose columns\", {{\"Created\", type date}, {\"Completed\", type date}, {\"Work Order\", type text}, {\"Type\", type text}, {\"ORG\", type text}, {\"Pass\\Fail\", type text}, {\"Part Number\", type text}, {\"Description\", type text}, {\"Serial Number\", type text}, {\"AS-8 ASSP Pre Shipment Check : ASSP Reservoir SN\", type text}, {\"AS-5 ASSP Final Test : Negative Voltage C0 Check\", type text}, {\"AS-5 ASSP Final Test : Function Test Complete\", type text}}, \"de-DE\"),\r\n  #\"Replaced errors\" = Table.ReplaceErrorValues(#\"Changed column type with locale\", {{\"AS-5 ASSP Final Test : Hold Time MI\", 0}, {\"AS-5 ASSP Final Test : Hold Time MA\", 0}, {\"AS-5 ASSP Final Test : Transfer Time\", 0}, {\"AS-5 ASSP Final Test : Negative Voltage C1 Max\", 0}, {\"AS-5 ASSP Final Test : Fall Time Negative Edge UCp\", 0}, {\"AS-5 ASSP Final Test : Negative IGBT Voltage Max\", 0}, {\"AS-5 ASSP Final Test : Negative Voltage Cp Max\", 0}}),\r\n  #\"Changed column type with locale 1\" = Table.TransformColumnTypes(#\"Replaced errors\", {{\"AS-17 ASSP Capacity Check : Capacity C0\", type number}, {\"AS-2 ASSP Leaktest : Leak Rate Oil Circuit\", type number}, {\"AS-2 ASSP Leaktest : Leak Rate Reservoir\", type number}, {\"AS-5 ASSP Final Test : Hold Time MI\", type number}, {\"AS-5 ASSP Final Test : Hold Time MA\", type number}, {\"AS-5 ASSP Final Test : Transfer Time\", type number}, {\"AS-5 ASSP Final Test : Negative Voltage C1 Max\", type number}, {\"AS-5 ASSP Final Test : Fall Time Negative Edge UCp\", type number}, {\"AS-5 ASSP Final Test : Negative IGBT Voltage Max\", type number}, {\"AS-5 ASSP Final Test : Negative Voltage Cp Max\", type number}, {\"AS-6 ASSP Safety Test : Leakage Current\", type number}}, \"de-DE\")\r\nin\r\n  #\"Changed column type with locale 1\";\r\nshared #\"Sample file\" = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Name] = \"ME-Power_BI-ASSP.xlsx\"),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows\", each [Attributes]?[Hidden]? <> true),\r\n  Navigation = #\"Filtered hidden files\"{0}[Content]\r\nin\r\n  Navigation;\r\nshared Parameter = let\r\n  Parameter = #\"Sample file\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type binary]\r\nin\r\n  Parameter;\r\nshared #\"Transform Sample file\" = let\r\n  Source = Excel.Workbook(Parameter, null, true),\r\n  Navigation = Source{[Item = \"Sheet1\", Kind = \"Sheet\"]}[Data],\r\n  #\"Promoted headers\" = Table.PromoteHeaders(Navigation, [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"Work Order\", Int64.Type}, {\"Type\", type text}, {\"ORG\", type text}, {\"Pass\\Fail\", type text}, {\"Created\", type text}, {\"Completed\", type text}, {\"Part Number\", type text}, {\"Description\", type text}, {\"Serial Number\", type text}, {\"AS-8 ASSP Pre Shipment Check : ASSP Reservoir SN Date\", type text}, {\"AS-8 ASSP Pre Shipment Check : ASSP Reservoir SN\", type text}, {\"AS-17 ASSP Capacity Check : Capacity C0 Date\", type text}, {\"AS-17 ASSP Capacity Check : Capacity C0\", Int64.Type}, {\"AS-2 ASSP Leaktest : Leak Rate Oil Circuit Date\", type text}, {\"AS-2 ASSP Leaktest : Leak Rate Oil Circuit\", type number}, {\"AS-2 ASSP Leaktest : Leak Rate Reservoir Date\", type text}, {\"AS-2 ASSP Leaktest : Leak Rate Reservoir\", type number}, {\"AS-5 ASSP Final Test : Negative Voltage C0 Check Date\", type text}, {\"AS-5 ASSP Final Test : Negative Voltage C0 Check\", type text}, {\"AS-5 ASSP Final Test : Hold Time MI Date\", type text}, {\"AS-5 ASSP Final Test : Hold Time MI\", Int64.Type}, {\"AS-5 ASSP Final Test : Hold Time MA Date\", type text}, {\"AS-5 ASSP Final Test : Hold Time MA\", type number}, {\"AS-5 ASSP Final Test : Transfer Time Date\", type text}, {\"AS-5 ASSP Final Test : Transfer Time\", type number}, {\"AS-5 ASSP Final Test : Negative Voltage C1 Max Date\", type text}, {\"AS-5 ASSP Final Test : Negative Voltage C1 Max\", type number}, {\"AS-5 ASSP Final Test : Fall Time Negative Edge UCp Date\", type text}, {\"AS-5 ASSP Final Test : Fall Time Negative Edge UCp\", type number}, {\"AS-5 ASSP Final Test : Negative IGBT Voltage Max Date\", type text}, {\"AS-5 ASSP Final Test : Negative IGBT Voltage Max\", type number}, {\"AS-5 ASSP Final Test : Negative Voltage Cp Max Date\", type text}, {\"AS-5 ASSP Final Test : Negative Voltage Cp Max\", type number}, {\"AS-6 ASSP Safety Test : Leakage Current Date\", type text}, {\"AS-6 ASSP Safety Test : Leakage Current\", type number}, {\"AS-5 ASSP Final Test : Function Test Complete Date\", type text}, {\"AS-5 ASSP Final Test : Function Test Complete\", type text}})\r\nin\r\n  #\"Changed column type\";\r\nshared #\"Transform file\" = let\r\n  Source = (Parameter as binary) => let\r\n  Source = Excel.Workbook(Parameter, null, true),\r\n  Navigation = Source{[Item = \"Sheet1\", Kind = \"Sheet\"]}[Data],\r\n  #\"Promoted headers\" = Table.PromoteHeaders(Navigation, [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"Work Order\", Int64.Type}, {\"Type\", type text}, {\"ORG\", type text}, {\"Pass\\Fail\", type text}, {\"Created\", type text}, {\"Completed\", type text}, {\"Part Number\", type text}, {\"Description\", type text}, {\"Serial Number\", type text}, {\"AS-8 ASSP Pre Shipment Check : ASSP Reservoir SN Date\", type text}, {\"AS-8 ASSP Pre Shipment Check : ASSP Reservoir SN\", type text}, {\"AS-17 ASSP Capacity Check : Capacity C0 Date\", type text}, {\"AS-17 ASSP Capacity Check : Capacity C0\", Int64.Type}, {\"AS-2 ASSP Leaktest : Leak Rate Oil Circuit Date\", type text}, {\"AS-2 ASSP Leaktest : Leak Rate Oil Circuit\", type number}, {\"AS-2 ASSP Leaktest : Leak Rate Reservoir Date\", type text}, {\"AS-2 ASSP Leaktest : Leak Rate Reservoir\", type number}, {\"AS-5 ASSP Final Test : Negative Voltage C0 Check Date\", type text}, {\"AS-5 ASSP Final Test : Negative Voltage C0 Check\", type text}, {\"AS-5 ASSP Final Test : Hold Time MI Date\", type text}, {\"AS-5 ASSP Final Test : Hold Time MI\", Int64.Type}, {\"AS-5 ASSP Final Test : Hold Time MA Date\", type text}, {\"AS-5 ASSP Final Test : Hold Time MA\", type number}, {\"AS-5 ASSP Final Test : Transfer Time Date\", type text}, {\"AS-5 ASSP Final Test : Transfer Time\", type number}, {\"AS-5 ASSP Final Test : Negative Voltage C1 Max Date\", type text}, {\"AS-5 ASSP Final Test : Negative Voltage C1 Max\", type number}, {\"AS-5 ASSP Final Test : Fall Time Negative Edge UCp Date\", type text}, {\"AS-5 ASSP Final Test : Fall Time Negative Edge UCp\", type number}, {\"AS-5 ASSP Final Test : Negative IGBT Voltage Max Date\", type text}, {\"AS-5 ASSP Final Test : Negative IGBT Voltage Max\", type number}, {\"AS-5 ASSP Final Test : Negative Voltage Cp Max Date\", type text}, {\"AS-5 ASSP Final Test : Negative Voltage Cp Max\", type number}, {\"AS-6 ASSP Safety Test : Leakage Current Date\", type text}, {\"AS-6 ASSP Safety Test : Leakage Current\", type number}, {\"AS-5 ASSP Final Test : Function Test Complete Date\", type text}, {\"AS-5 ASSP Final Test : Function Test Complete\", type text}})\r\nin\r\n  #\"Changed column type\"\r\nin\r\n  Source;\r\nshared #\"ASSP SPC API\" = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n  #\"Filtered rows 1\" = Table.SelectRows(Source, each Text.Contains([Name], \"CustomReportData-ASSP\")),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows 1\", each [Attributes]?[Hidden]? <> true),\r\n  #\"Invoke custom function\" = Table.AddColumn(#\"Filtered hidden files\", \"Transform file (2)\", each #\"Transform file (2)\"([Content])),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Invoke custom function\", {{\"Name\", \"Source.Name\"}}),\r\n  #\"Removed other columns\" = Table.SelectColumns(#\"Renamed columns\", {\"Source.Name\", \"Transform file (2)\"}),\r\n  #\"Expanded table column\" = Table.ExpandTableColumn(#\"Removed other columns\", \"Transform file (2)\", Table.ColumnNames(#\"Transform file (2)\"(#\"Sample file (2)\"))),\r\n  #\"Choose columns\" = Table.SelectColumns(#\"Expanded table column\", {\"DATA_VALUE\", \"MEASUREMENT\", \"PART_NUMBER\", \"SERIAL_NUMBER\", \"WORK_ORDER\"}),\r\n  #\"Trimmed text\" = Table.TransformColumns(#\"Choose columns\", {{\"MEASUREMENT\", each Text.Trim(Text.From(_)), type text}}),\r\n  #\"Pivoted column\" = Table.Pivot(Table.TransformColumnTypes(#\"Trimmed text\", {{\"MEASUREMENT\", type text}}), List.Distinct(Table.TransformColumnTypes(#\"Trimmed text\", {{\"MEASUREMENT\", type text}})[MEASUREMENT]), \"MEASUREMENT\", \"DATA_VALUE\"),\r\n  #\"Renamed columns 2\" = Table.RenameColumns(#\"Pivoted column\", {{\"Function Test Complete\", \"Function Test Complete\"}}),\r\n  #\"Replaced errors\" = Table.ReplaceErrorValues(#\"Renamed columns 2\", {{\"Leakage Current\", 0}}),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Replaced errors\", {{\"PART_NUMBER\", type text}, {\"SERIAL_NUMBER\", type text}, {\"WORK_ORDER\", type text}, {\"Function Test Complete\", type text}, {\"Negative Voltage C0 Check\", type text}, {\"ASSP Reservoir SN\", type text}, {\"Transfer Time\", type number}, {\"Negative IGBT Voltage Max\", type number}, {\"Hold Time MA\", type number}, {\"Fall Time Negative Edge UCp\", type number}, {\"Negative Voltage C1 Max\", type number}, {\"Negative Voltage Cp Max\", type number}, {\"Hold Time MI\", type number}, {\"Leakage Current\", type number}, {\"Leak Rate Reservoir\", type number}, {\"Leak Rate Oil Circuit\", type number}, {\"Capacity C0\", Int64.Type}}),\r\n  #\"Replaced errors 1\" = Table.ReplaceErrorValues(#\"Changed column type\", {{\"Transfer Time\", 0}, {\"Negative IGBT Voltage Max\", 0}, {\"Hold Time MA\", 0}, {\"Fall Time Negative Edge UCp\", 0}, {\"Negative Voltage C1 Max\", 0}, {\"Negative Voltage Cp Max\", 0}, {\"Hold Time MI\", 0}, {\"Leak Rate Oil Circuit\", 0}})\r\nin\r\n  #\"Replaced errors 1\";\r\nshared #\"Sample file (2)\" = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Name] = \"VHP-CustomReportData-ASSP_CustomReportDataResult.xlsx\"),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows\", each [Attributes]?[Hidden]? <> true),\r\n  Navigation = #\"Filtered hidden files\"{0}[Content]\r\nin\r\n  Navigation;\r\nshared #\"Parameter (2)\" = let\r\n  #\"Parameter (2)\" = #\"Sample file (2)\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type binary]\r\nin\r\n  #\"Parameter (2)\";\r\nshared #\"Transform Sample file (2)\" = let\r\n  Source = Excel.Workbook(#\"Parameter (2)\", null, true),\r\n  Navigation = Source{[Item = \"CustomReportDataResult\", Kind = \"Sheet\"]}[Data],\r\n  #\"Promoted headers\" = Table.PromoteHeaders(Navigation, [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"CTL_LIMITS\", type any}, {\"DATA_TYPE\", type text}, {\"DATA_VALUE\", type text}, {\"DATE\", type text}, {\"DESCRIPTION\", type text}, {\"DEVIATIONS\", type any}, {\"FLOW\", type text}, {\"MEASUREMENT\", type text}, {\"PART_NUMBER\", type text}, {\"PASS_CTL\", type logical}, {\"PASS_SPEC\", type logical}, {\"PROCESS\", type text}, {\"PROCESS_DESCRIPTION\", type text}, {\"SERIAL_NUMBER\", type text}, {\"SPEC_LIMITS\", type text}, {\"UOM\", type text}, {\"WORK_ORDER\", Int64.Type}, {\"WO_NOTES\", type text}, {\"WO_STATUS\", type text}})\r\nin\r\n  #\"Changed column type\";\r\nshared #\"Transform file (2)\" = let\r\n  Source = (#\"Parameter (2)\" as binary) => let\r\n  Source = Excel.Workbook(#\"Parameter (2)\", null, true),\r\n  Navigation = Source{[Item = \"CustomReportDataResult\", Kind = \"Sheet\"]}[Data],\r\n  #\"Promoted headers\" = Table.PromoteHeaders(Navigation, [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"CTL_LIMITS\", type any}, {\"DATA_TYPE\", type text}, {\"DATA_VALUE\", type text}, {\"DATE\", type text}, {\"DESCRIPTION\", type text}, {\"DEVIATIONS\", type any}, {\"FLOW\", type text}, {\"MEASUREMENT\", type text}, {\"PART_NUMBER\", type text}, {\"PASS_CTL\", type logical}, {\"PASS_SPEC\", type logical}, {\"PROCESS\", type text}, {\"PROCESS_DESCRIPTION\", type text}, {\"SERIAL_NUMBER\", type text}, {\"SPEC_LIMITS\", type text}, {\"UOM\", type text}, {\"WORK_ORDER\", Int64.Type}, {\"WO_NOTES\", type text}, {\"WO_STATUS\", type text}})\r\nin\r\n  #\"Changed column type\"\r\nin\r\n  Source;\r\nshared #\"ASSP SPC Specs\" = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Name] = \"VHP-CustomReportData-ASSP_CustomReportDataResult.xlsx\"),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows\", each [Attributes]?[Hidden]? <> true),\r\n  #\"Invoke custom function\" = Table.AddColumn(#\"Filtered hidden files\", \"Transform file (2)\", each #\"Transform file (2)\"([Content])),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Invoke custom function\", {{\"Name\", \"Source.Name\"}}),\r\n  #\"Removed other columns\" = Table.SelectColumns(#\"Renamed columns\", {\"Source.Name\", \"Transform file (2)\"}),\r\n  #\"Expanded table column\" = Table.ExpandTableColumn(#\"Removed other columns\", \"Transform file (2)\", Table.ColumnNames(#\"Transform file (2)\"(#\"Sample file (2)\"))),\r\n  #\"Choose columns\" = Table.SelectColumns(#\"Expanded table column\", {\"MEASUREMENT\", \"PART_NUMBER\", \"SPEC_LIMITS\"}),\r\n  #\"Trimmed text\" = Table.TransformColumns(#\"Choose columns\", {{\"MEASUREMENT\", each Text.Trim(Text.From(_)), type text}}),\r\n  #\"Removed duplicates\" = Table.Distinct(#\"Trimmed text\", {\"MEASUREMENT\", \"PART_NUMBER\"}),\r\n  #\"Pivoted column\" = Table.Pivot(Table.TransformColumnTypes(#\"Removed duplicates\", {{\"MEASUREMENT\", type text}}), List.Distinct(Table.TransformColumnTypes(#\"Removed duplicates\", {{\"MEASUREMENT\", type text}})[MEASUREMENT]), \"MEASUREMENT\", \"SPEC_LIMITS\"),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Pivoted column\", {{\"PART_NUMBER\", type text}, {\"Transfer Time\", type text}, {\"Negative IGBT Voltage Max\", type text}, {\"Function Test Complete\", type text}, {\"Capacity C0\", type text}, {\"Hold Time MA\", type text}, {\"Fall Time Negative Edge UCp\", type text}, {\"Negative Voltage C1 Max\", type text}, {\"Negative Voltage Cp Max\", type text}, {\"Negative Voltage C0 Check\", type text}, {\"ASSP Reservoir SN\", type text}, {\"Hold Time MI\", type text}, {\"Leakage Current\", type text}, {\"Leak Rate Reservoir\", type text}, {\"Leak Rate Oil Circuit\", type text}})\r\nin\r\n  #\"Changed column type\";\r\nshared #\"ASSP SPC UOM\" = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Name] = \"VHP-CustomReportData-ASSP_CustomReportDataResult.xlsx\"),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows\", each [Attributes]?[Hidden]? <> true),\r\n  #\"Invoke custom function\" = Table.AddColumn(#\"Filtered hidden files\", \"Transform file (2)\", each #\"Transform file (2)\"([Content])),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Invoke custom function\", {{\"Name\", \"Source.Name\"}}),\r\n  #\"Removed other columns\" = Table.SelectColumns(#\"Renamed columns\", {\"Source.Name\", \"Transform file (2)\"}),\r\n  #\"Expanded table column\" = Table.ExpandTableColumn(#\"Removed other columns\", \"Transform file (2)\", Table.ColumnNames(#\"Transform file (2)\"(#\"Sample file (2)\"))),\r\n  #\"Choose columns\" = Table.SelectColumns(#\"Expanded table column\", {\"MEASUREMENT\", \"UOM\"}),\r\n  #\"Trimmed text\" = Table.TransformColumns(#\"Choose columns\", {{\"MEASUREMENT\", each Text.Trim(Text.From(_)), type text}}),\r\n  #\"Removed duplicates\" = Table.Distinct(#\"Trimmed text\", {\"MEASUREMENT\"}),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Removed duplicates\", {{\"UOM\", type text}})\r\nin\r\n  #\"Changed column type\";\r\nshared #\"Cryo SPC API\" = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Name] = \"VHP-CustomReportData-Cryo_CustomReportDataResult.xlsx\"),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows\", each [Attributes]?[Hidden]? <> true),\r\n  #\"Invoke custom function\" = Table.AddColumn(#\"Filtered hidden files\", \"Transform file (3)\", each #\"Transform file (3)\"([Content])),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Invoke custom function\", {{\"Name\", \"Source.Name\"}}),\r\n  #\"Removed other columns\" = Table.SelectColumns(#\"Renamed columns\", {\"Source.Name\", \"Transform file (3)\"}),\r\n  #\"Expanded table column\" = Table.ExpandTableColumn(#\"Removed other columns\", \"Transform file (3)\", Table.ColumnNames(#\"Transform file (3)\"(#\"Sample file (3)\"))),\r\n  #\"Choose columns\" = Table.SelectColumns(#\"Expanded table column\", {\"DATA_VALUE\", \"MEASUREMENT\", \"PART_NUMBER\", \"SERIAL_NUMBER\", \"WORK_ORDER\"}),\r\n  #\"Removed duplicates\" = Table.Distinct(#\"Choose columns\", {\"WORK_ORDER\", \"SERIAL_NUMBER\", \"PART_NUMBER\", \"MEASUREMENT\", \"DATA_VALUE\"}),\r\n  #\"Pivoted column\" = Table.Pivot(Table.TransformColumnTypes(#\"Removed duplicates\", {{\"MEASUREMENT\", type text}}), List.Distinct(Table.TransformColumnTypes(#\"Removed duplicates\", {{\"MEASUREMENT\", type text}})[MEASUREMENT]), \"MEASUREMENT\", \"DATA_VALUE\"),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Pivoted column\", {{\"PART_NUMBER\", type text}, {\"SERIAL_NUMBER\", type text}, {\"WORK_ORDER\", type text}, {\"Helium Hintergrund beim Abschnüffeln dokumentieren.\", type number}, {\"Cool Down Time 145K\", type number}, {\"Gas Pressure Drop\", type number}, {\"Cool Down Time\", type number}, {\"Heating Resistance\", type number}, {\"Cool Down Time Stat\", type number}, {\"Gassystem abschnüffeln und Wert dokumentieren.\", type number}, {\"Pressure Drop\", type number}, {\"Static Leak Rate\", type number}, {\"SN Teststand\", type text}}),\r\n  #\"Replaced errors\" = Table.ReplaceErrorValues(#\"Changed column type\", {{\"Gas Pressure Drop\", 0}, {\"Pressure Drop\", 0}, {\"Gassystem abschnüffeln und Wert dokumentieren.\", 0}}),\r\n  #\"Replaced errors 1\" = Table.ReplaceErrorValues(#\"Replaced errors\", {{\"Cool Down Time Stat\", 0}, {\"Cool Down Time\", 0}, {\"Cool Down Time 145K\", 0}})\r\nin\r\n  #\"Replaced errors 1\";\r\nshared #\"Sample file (3)\" = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Name] = \"VHP-CustomReportData-Cryo_CustomReportDataResult.xlsx\"),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows\", each [Attributes]?[Hidden]? <> true),\r\n  Navigation = #\"Filtered hidden files\"{0}[Content]\r\nin\r\n  Navigation;\r\nshared #\"Parameter (3)\" = let\r\n  #\"Parameter (3)\" = #\"Sample file (3)\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type binary]\r\nin\r\n  #\"Parameter (3)\";\r\nshared #\"Transform Sample file (3)\" = let\r\n  Source = Excel.Workbook(#\"Parameter (3)\", null, true),\r\n  Navigation = Source{[Item = \"CustomReportDataResult\", Kind = \"Sheet\"]}[Data],\r\n  #\"Promoted headers\" = Table.PromoteHeaders(Navigation, [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"CTL_LIMITS\", type any}, {\"DATA_TYPE\", type text}, {\"DATA_VALUE\", type text}, {\"DATE\", type text}, {\"DESCRIPTION\", type text}, {\"DEVIATIONS\", type text}, {\"FLOW\", type text}, {\"MEASUREMENT\", type text}, {\"PART_NUMBER\", type text}, {\"PASS_CTL\", type logical}, {\"PASS_SPEC\", type logical}, {\"PROCESS\", type text}, {\"PROCESS_DESCRIPTION\", type text}, {\"SERIAL_NUMBER\", type text}, {\"SPEC_LIMITS\", type text}, {\"UOM\", type text}, {\"WORK_ORDER\", type text}, {\"WO_NOTES\", type text}, {\"WO_STATUS\", type text}})\r\nin\r\n  #\"Changed column type\";\r\nshared #\"Transform file (3)\" = let\r\n  Source = (#\"Parameter (3)\" as binary) => let\r\n  Source = Excel.Workbook(#\"Parameter (3)\", null, true),\r\n  Navigation = Source{[Item = \"CustomReportDataResult\", Kind = \"Sheet\"]}[Data],\r\n  #\"Promoted headers\" = Table.PromoteHeaders(Navigation, [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"CTL_LIMITS\", type any}, {\"DATA_TYPE\", type text}, {\"DATA_VALUE\", type text}, {\"DATE\", type text}, {\"DESCRIPTION\", type text}, {\"DEVIATIONS\", type text}, {\"FLOW\", type text}, {\"MEASUREMENT\", type text}, {\"PART_NUMBER\", type text}, {\"PASS_CTL\", type logical}, {\"PASS_SPEC\", type logical}, {\"PROCESS\", type text}, {\"PROCESS_DESCRIPTION\", type text}, {\"SERIAL_NUMBER\", type text}, {\"SPEC_LIMITS\", type text}, {\"UOM\", type text}, {\"WORK_ORDER\", type text}, {\"WO_NOTES\", type text}, {\"WO_STATUS\", type text}})\r\nin\r\n  #\"Changed column type\"\r\nin\r\n  Source;\r\nshared #\"Cryo SPC Specs\" = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Name] = \"VHP-CustomReportData-Cryo_CustomReportDataResult.xlsx\"),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows\", each [Attributes]?[Hidden]? <> true),\r\n  #\"Invoke custom function\" = Table.AddColumn(#\"Filtered hidden files\", \"Transform file (3)\", each #\"Transform file (3)\"([Content])),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Invoke custom function\", {{\"Name\", \"Source.Name\"}}),\r\n  #\"Removed other columns\" = Table.SelectColumns(#\"Renamed columns\", {\"Source.Name\", \"Transform file (3)\"}),\r\n  #\"Expanded table column\" = Table.ExpandTableColumn(#\"Removed other columns\", \"Transform file (3)\", Table.ColumnNames(#\"Transform file (3)\"(#\"Sample file (3)\"))),\r\n  #\"Choose columns\" = Table.SelectColumns(#\"Expanded table column\", {\"MEASUREMENT\", \"PART_NUMBER\", \"SPEC_LIMITS\"}),\r\n  #\"Removed duplicates\" = Table.Distinct(#\"Choose columns\", {\"MEASUREMENT\", \"PART_NUMBER\"}),\r\n  #\"Pivoted column\" = Table.Pivot(Table.TransformColumnTypes(#\"Removed duplicates\", {{\"MEASUREMENT\", type text}}), List.Distinct(Table.TransformColumnTypes(#\"Removed duplicates\", {{\"MEASUREMENT\", type text}})[MEASUREMENT]), \"MEASUREMENT\", \"SPEC_LIMITS\"),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Pivoted column\", {{\"PART_NUMBER\", type text}, {\"Helium Hintergrund beim Abschnüffeln dokumentieren.\", type text}, {\"Cool Down Time 145K\", type text}, {\"Gas Pressure Drop\", type text}, {\"Cool Down Time\", type text}, {\"Heating Resistance\", type text}, {\"Cool Down Time Stat\", type text}, {\"Gassystem abschnüffeln und Wert dokumentieren.\", type text}, {\"Pressure Drop\", type text}, {\"Static Leak Rate\", type text}})\r\nin\r\n  #\"Changed column type\";\r\nshared #\"Cryo SPC UOM\" = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Name] = \"VHP-CustomReportData-Cryo_CustomReportDataResult.xlsx\"),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows\", each [Attributes]?[Hidden]? <> true),\r\n  #\"Invoke custom function\" = Table.AddColumn(#\"Filtered hidden files\", \"Transform file (3)\", each #\"Transform file (3)\"([Content])),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Invoke custom function\", {{\"Name\", \"Source.Name\"}}),\r\n  #\"Removed other columns\" = Table.SelectColumns(#\"Renamed columns\", {\"Source.Name\", \"Transform file (3)\"}),\r\n  #\"Expanded table column\" = Table.ExpandTableColumn(#\"Removed other columns\", \"Transform file (3)\", Table.ColumnNames(#\"Transform file (3)\"(#\"Sample file (3)\"))),\r\n  #\"Choose columns\" = Table.SelectColumns(#\"Expanded table column\", {\"MEASUREMENT\", \"UOM\"}),\r\n  #\"Removed duplicates\" = Table.Distinct(#\"Choose columns\", {\"MEASUREMENT\"}),\r\n  #\"Transform columns\" = Table.TransformColumnTypes(#\"Removed duplicates\", {{\"MEASUREMENT\", type text}, {\"UOM\", type text}}),\r\n  #\"Replace errors\" = Table.ReplaceErrorValues(#\"Transform columns\", {{\"MEASUREMENT\", null}, {\"UOM\", null}})\r\nin\r\n  #\"Replace errors\";\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[{\"id\":\"3cf6d5d7-8b5d-4889-93d3-8626426f516a\",\"name\":\"Transform file from ASSP SPC Data\",\"description\":null,\"parentId\":null,\"order\":0},{\"id\":\"e551fed4-556a-439a-b0c5-692dd28b6584\",\"name\":\"Helper queries\",\"description\":null,\"parentId\":\"3cf6d5d7-8b5d-4889-93d3-8626426f516a\",\"order\":0},{\"id\":\"5bf3fa6d-b99e-4430-8174-e1a1ae414783\",\"name\":\"Transform file from ASSP SPC API\",\"description\":null,\"parentId\":null,\"order\":0},{\"id\":\"e28eaa03-961d-4424-9701-c23a2bb26d97\",\"name\":\"Helper queries (2)\",\"description\":null,\"parentId\":\"5bf3fa6d-b99e-4430-8174-e1a1ae414783\",\"order\":0},{\"id\":\"d6f28379-255f-4f5a-a654-783a37b0cf07\",\"name\":\"Transform file from Cryo SPC API\",\"description\":null,\"parentId\":null,\"order\":0},{\"id\":\"b11bccab-5eee-4948-81ae-9e410e0a264b\",\"name\":\"Helper queries (3)\",\"description\":null,\"parentId\":\"d6f28379-255f-4f5a-a654-783a37b0cf07\",\"order\":0},{\"id\":\"e2b56a61-e003-4a42-af94-4a7062dac8b4\",\"name\":\"Inactive\",\"description\":\"\",\"parentId\":null,\"order\":0}]"}],"entities":[{"$type":"LocalEntity","name":"ASSP SPC API","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"ASSP%20SPC%20API.csv"},"attributes":[{"name":"PART_NUMBER","dataType":"string"},{"name":"SERIAL_NUMBER","dataType":"string"},{"name":"WORK_ORDER","dataType":"string"},{"name":"Leakage Current","dataType":"double"},{"name":"ASSP Reservoir SN","dataType":"string"},{"name":"Negative Voltage C0 Check","dataType":"string"},{"name":"Transfer Time","dataType":"double"},{"name":"Negative IGBT Voltage Max","dataType":"double"},{"name":"Hold Time MA","dataType":"double"},{"name":"Fall Time Negative Edge UCp","dataType":"double"},{"name":"Negative Voltage C1 Max","dataType":"double"},{"name":"Negative Voltage Cp Max","dataType":"double"},{"name":"Function Test Complete","dataType":"string"},{"name":"Hold Time MI","dataType":"double"},{"name":"Leak Rate Reservoir","dataType":"double"},{"name":"Leak Rate Oil Circuit","dataType":"double"},{"name":"Capacity C0","dataType":"int64"}],"partitions":[{"name":"Part001","refreshTime":"2022-05-20T03:00:51.7473078+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/2800db57-a993-4408-b916-195f45be7a21/ASSP%20SPC%20API.csv?snapshot=2022-05-20T03%3A00%3A51.7216497Z"}]},{"$type":"LocalEntity","name":"Cryo SPC API","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Cryo%20SPC%20API.csv"},"attributes":[{"name":"PART_NUMBER","dataType":"string"},{"name":"SERIAL_NUMBER","dataType":"string"},{"name":"WORK_ORDER","dataType":"string"},{"name":"Gas Pressure Drop","dataType":"double"},{"name":"Helium Hintergrund beim Abschnüffeln dokumentieren.","dataType":"double"},{"name":"Pressure Drop","dataType":"double"},{"name":"Static Leak Rate","dataType":"double"},{"name":"Gassystem abschnüffeln und Wert dokumentieren.","dataType":"double"},{"name":"SN Teststand","dataType":"string"},{"name":"Heating Resistance","dataType":"double"},{"name":"Cool Down Time Stat","dataType":"double"},{"name":"Cool Down Time","dataType":"double"},{"name":"Cool Down Time 145K","dataType":"double"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-20T03:00:50.8487325+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/2800db57-a993-4408-b916-195f45be7a21/Cryo%20SPC%20API.csv?snapshot=2022-05-20T03%3A00%3A50.8301611Z"}]}]}