{"name":"Flow_SPC_ET-LDU","description":"Data LDU Final Test for Spare Part Tubes (Fab2).","version":"1.0","culture":"en-US","modifiedTime":"2022-05-19T10:18:51.7004454+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"ET-LDU SPC ET5":{"queryId":"1c8a6756-63db-415b-a520-ec014fa3a3e3","queryName":"ET-LDU SPC ET5","loadEnabled":true},"ET-LDU SPC ET6":{"queryId":"ec6a625e-040e-4e14-b16a-24c7d7aaa5c5","queryName":"ET-LDU SPC ET6","loadEnabled":true},"ET-LDU SPC ET7":{"queryId":"f6d6662f-8649-4444-a302-8f36f68aa1be","queryName":"ET-LDU SPC ET7","loadEnabled":true},"ET-LDU SPC ET7 - Archive":{"queryId":"e219106c-3e02-4a0c-80f3-4222878580eb","queryName":"ET-LDU SPC ET7 - Archive"},"ET-LDU SPC ET7BP":{"queryId":"931903c2-1ccc-418a-9c46-abf5b3c8c4ac","queryName":"ET-LDU SPC ET7BP","loadEnabled":true},"Sample file":{"queryId":"e04372e7-a76f-49e6-acd8-bd04be889f61","queryName":"Sample file","queryGroupId":"46daed4c-e127-40de-82a8-36f6634fcc72"},"Parameter":{"queryId":"07a3320a-4481-4925-80f4-639193e4cb4e","queryName":"Parameter","queryGroupId":"46daed4c-e127-40de-82a8-36f6634fcc72"},"Transform Sample file":{"queryId":"65d84a53-7f06-4b0e-8a36-8fa0d296223f","queryName":"Transform Sample file","queryGroupId":"13a6b852-762a-46f5-9e0d-397c85a24e84"},"Transform file":{"queryId":"00ce8c00-3db9-4e95-9755-a015f87e981d","queryName":"Transform file","queryGroupId":"46daed4c-e127-40de-82a8-36f6634fcc72"},"Sample file (2)":{"queryId":"be08168b-5c4c-4e92-a488-d964224559b6","queryName":"Sample file (2)","queryGroupId":"515a21ec-f054-4f4a-b823-af5bb97a21d7"},"Parameter (2)":{"queryId":"b5daba72-9cc0-45db-bb48-5debad94a8a8","queryName":"Parameter (2)","queryGroupId":"515a21ec-f054-4f4a-b823-af5bb97a21d7"},"Transform Sample file (2)":{"queryId":"69f25182-821a-4e32-8e04-774b951dd869","queryName":"Transform Sample file (2)","queryGroupId":"67fe7cf2-a454-4e3d-9479-cbfa8ff40e40"},"Transform file (2)":{"queryId":"105450fa-8dd0-4c19-af37-88063b6a6d43","queryName":"Transform file (2)","queryGroupId":"515a21ec-f054-4f4a-b823-af5bb97a21d7"},"Sample file (3)":{"queryId":"15c343f9-df70-4233-ac1b-c0cdebdeebbe","queryName":"Sample file (3)","queryGroupId":"32e68dad-7697-43dd-a9cf-10c263b75ebe"},"Parameter (3)":{"queryId":"93c22f01-0a8d-4fa4-aac6-52e94b801a1e","queryName":"Parameter (3)","queryGroupId":"32e68dad-7697-43dd-a9cf-10c263b75ebe"},"Transform Sample file (3)":{"queryId":"48b0da74-c701-4c26-af23-728cfc2757a1","queryName":"Transform Sample file (3)","queryGroupId":"077733af-1d94-4f95-a122-ff03aff1ea3d"},"Transform file (3)":{"queryId":"955ba1cd-b44b-47f7-9ec6-584919a4f52a","queryName":"Transform file (3)","queryGroupId":"32e68dad-7697-43dd-a9cf-10c263b75ebe"},"Sample file (4)":{"queryId":"2d3ece00-6e98-4111-b9f5-e84449c36fd2","queryName":"Sample file (4)","queryGroupId":"8864c450-4fc2-4047-bf17-63fe53873680"},"Parameter (4)":{"queryId":"a4dc03e7-2cab-4441-b4c8-b781716b3333","queryName":"Parameter (4)","queryGroupId":"8864c450-4fc2-4047-bf17-63fe53873680"},"Transform Sample file (4)":{"queryId":"c51f11f0-9ca2-4e50-98a7-69de310e3ceb","queryName":"Transform Sample file (4)","queryGroupId":"36943665-2dbf-426a-bb78-ce56815ad43b"},"Transform file (4)":{"queryId":"44bf078b-253c-4aa8-9383-30ef7bfdd6bd","queryName":"Transform file (4)","queryGroupId":"8864c450-4fc2-4047-bf17-63fe53873680"}},"document":"section Section1;\r\nshared #\"ET-LDU SPC ET5\" = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n  #\"Filtered rows 1\" = Table.SelectRows(Source, each Text.Contains([Name], \"CustomReportData-ET5\")),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows 1\", each [Attributes]?[Hidden]? <> true),\r\n  #\"Invoke custom function\" = Table.AddColumn(#\"Filtered hidden files\", \"Transform file\", each #\"Transform file\"([Content])),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Invoke custom function\", {{\"Name\", \"Source.Name\"}}),\r\n  #\"Removed other columns\" = Table.SelectColumns(#\"Renamed columns\", {\"Source.Name\", \"Transform file\"}),\r\n  #\"Expanded table column\" = Table.ExpandTableColumn(#\"Removed other columns\", \"Transform file\", Table.ColumnNames(#\"Transform file\"(#\"Sample file\"))),\r\n  #\"Filtered rows\" = Table.SelectRows(#\"Expanded table column\", each [WO_STATUS] <> \"Active\"),\r\n  #\"Choose columns\" = Table.SelectColumns(#\"Filtered rows\", {\"DATA_VALUE\", \"MEASUREMENT\", \"PART_NUMBER\", \"SERIAL_NUMBER\", \"WORK_ORDER\"}),\r\n  #\"Trimmed text\" = Table.TransformColumns(#\"Choose columns\", {{\"MEASUREMENT\", each Text.Trim(Text.From(_)), type text}}),\r\n  #\"Pivoted column\" = Table.Pivot(Table.TransformColumnTypes(#\"Trimmed text\", {{\"MEASUREMENT\", type text}}), List.Distinct(Table.TransformColumnTypes(#\"Trimmed text\", {{\"MEASUREMENT\", type text}})[MEASUREMENT]), \"MEASUREMENT\", \"DATA_VALUE\"),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Pivoted column\", {{\"PART_NUMBER\", type text}, {\"SERIAL_NUMBER\", type text}, {\"WORK_ORDER\", type text}, {\"E 10 Mio End\", type number}, {\"E Difference\", type number}, {\"User Counter 10 Mio End\", type number}, {\"HV 10 Mio Start\", type number}, {\"Test Laser\", type text}, {\"New Fill Counter 10 Mio End\", type number}, {\"User Counter 10 Mio Start\", type number}}),\r\n  #\"Replaced errors\" = Table.ReplaceErrorValues(#\"Changed column type\", {{\"E Difference\", 99999}}),\r\n  #\"Transform columns\" = Table.TransformColumnTypes(#\"Replaced errors\", {{\"Test Laser KEP\", type text}}),\r\n  #\"Replace errors\" = Table.ReplaceErrorValues(#\"Transform columns\", {{\"Test Laser KEP\", null}})\r\nin\r\n  #\"Replace errors\";\r\nshared #\"ET-LDU SPC ET6\" = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each Text.Contains([Name], \"CustomReportData-ET6\")),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows\", each [Attributes]?[Hidden]? <> true),\r\n  #\"Invoke custom function\" = Table.AddColumn(#\"Filtered hidden files\", \"Transform file (2)\", each #\"Transform file (2)\"([Content])),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Invoke custom function\", {{\"Name\", \"Source.Name\"}}),\r\n  #\"Removed other columns\" = Table.SelectColumns(#\"Renamed columns\", {\"Source.Name\", \"Transform file (2)\"}),\r\n  #\"Expanded table column\" = Table.ExpandTableColumn(#\"Removed other columns\", \"Transform file (2)\", Table.ColumnNames(#\"Transform file (2)\"(#\"Sample file (2)\"))),\r\n  #\"Filtered rows 1\" = Table.SelectRows(#\"Expanded table column\", each [WO_STATUS] <> \"Active\"),\r\n  #\"Choose columns\" = Table.SelectColumns(#\"Filtered rows 1\", {\"DATA_VALUE\", \"MEASUREMENT\", \"PART_NUMBER\", \"SERIAL_NUMBER\", \"WORK_ORDER\"}),\r\n  #\"Trimmed text\" = Table.TransformColumns(#\"Choose columns\", {{\"MEASUREMENT\", each Text.Trim(Text.From(_)), type text}}),\r\n  #\"Pivoted column\" = Table.Pivot(Table.TransformColumnTypes(#\"Trimmed text\", {{\"MEASUREMENT\", type text}}), List.Distinct(Table.TransformColumnTypes(#\"Trimmed text\", {{\"MEASUREMENT\", type text}})[MEASUREMENT]), \"MEASUREMENT\", \"DATA_VALUE\"),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Pivoted column\", {{\"PART_NUMBER\", type text}, {\"WORK_ORDER\", type text}, {\"SERIAL_NUMBER\", type text}, {\"New Fill Counter Burn-In End\", type number}, {\"HV Burn-In End\", type number}, {\"HV Burn-In Start\", type number}, {\"Energy Deviation Start\", type number}, {\"Energy Deviation Max Internal\", type number}, {\"HV Rise Burn-In\", Int64.Type}, {\"HI Number\", Int64.Type}, {\"User Counter Burn-In Start\", type number}, {\"User Counter Burn-In End\", type number}}),\r\n  #\"Replaced errors\" = Table.ReplaceErrorValues(#\"Changed column type\", {{\"HV Rise Burn-In\", 0}})\r\nin\r\n  #\"Replaced errors\";\r\nshared #\"ET-LDU SPC ET7\" = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each Text.Contains([Name], \"CustomReportData-ET7_\")),\r\n  #\"Filtered rows 2\" = Table.SelectRows(#\"Filtered rows\", each [Date modified] > #datetime(2021, 10, 31, 0, 0, 0)),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows 2\", each [Attributes]?[Hidden]? <> true),\r\n  #\"Invoke custom function\" = Table.AddColumn(#\"Filtered hidden files\", \"Transform file (3)\", each #\"Transform file (3)\"([Content])),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Invoke custom function\", {{\"Name\", \"Source.Name\"}}),\r\n  #\"Removed other columns\" = Table.SelectColumns(#\"Renamed columns\", {\"Source.Name\", \"Transform file (3)\"}),\r\n  #\"Expanded table column\" = Table.ExpandTableColumn(#\"Removed other columns\", \"Transform file (3)\", Table.ColumnNames(#\"Transform file (3)\"(#\"Sample file (3)\"))),\r\n  #\"Choose columns\" = Table.SelectColumns(#\"Expanded table column\", {\"DATA_VALUE\", \"MEASUREMENT\", \"PART_NUMBER\", \"SERIAL_NUMBER\", \"WORK_ORDER\"}),\r\n  #\"Trimmed text\" = Table.TransformColumns(#\"Choose columns\", {{\"MEASUREMENT\", each Text.Trim(Text.From(_)), type text}}),\r\n  #\"Removed duplicates\" = Table.Distinct(#\"Trimmed text\", {\"DATA_VALUE\", \"MEASUREMENT\", \"PART_NUMBER\", \"SERIAL_NUMBER\", \"WORK_ORDER\"}),\r\n  #\"Pivoted column\" = Table.Pivot(Table.TransformColumnTypes(#\"Removed duplicates\", {{\"MEASUREMENT\", type text}}), List.Distinct(Table.TransformColumnTypes(#\"Removed duplicates\", {{\"MEASUREMENT\", type text}})[MEASUREMENT]), \"MEASUREMENT\", \"DATA_VALUE\"),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Pivoted column\", {{\"Test Laser\", type text}, {\"PART_NUMBER\", type text}, {\"SERIAL_NUMBER\", type text}, {\"WORK_ORDER\", type text}, {\"GCS HV R\", type number}, {\"Energy Deviation Max Internal\", type number}, {\"Second Hump End\", type number}, {\"GCS Pulse Width R\", Int64.Type}, {\"GCS Pulse Width F\", Int64.Type}, {\"Energy Drop Max Number\", Int64.Type}, {\"Peak to Peak Fluctuations Max Number 10\", Int64.Type}, {\"HV Rise\", Int64.Type}, {\"Peak to Peak Fluctuations Max Number 100\", Int64.Type}, {\"Peak to Peak Fluctuations Max Number 20\", Int64.Type}, {\"Peak to Peak Fluctuations Max Number\", Int64.Type}, {\"Energy Deviation Difference\", type number}, {\"Tube Pressure End\", type number}, {\"User Counter\", type number}, {\"New Fill Counter End\", type number}, {\"HV End\", type number}, {\"Transmission Loss OC P3\", type number}, {\"Second Hump Start\", type number}, {\"Transmission Loss HR P3\", type number}, {\"GCS HV F\", type number}, {\"Peak to Peak Fluctuations End\", type number}, {\"Tube Pressure Rise\", type number}, {\"Tube Pressure Start\", type number}, {\"Peak to Peak Fluctuations Start\", type number}, {\"Energy Deviation Average\", type number}, {\"Peak to Peak Fluctuations Average\", type number}, {\"P2P Fluctuations 6 Sigma\", type number}, {\"HV Start\", type number}, {\"Max EGY Above Average\", type number}, {\"Energy Deviation Start\", type number}, {\"Energy Deviation End\", type number}, {\"Energy Deviation Max\", type number}, {\"HI Number\", Int64.Type}, {\"User Counter Job\", type number}, {\"User Counter Start\", type number}, {\"User Counter End\", type number}}),\r\n  #\"Replaced errors\" = Table.ReplaceErrorValues(#\"Changed column type\", {{\"Second Hump Start\", 0}, {\"HV Rise\", 0}, {\"Second Hump End\", 0}, {\"HV Start\", 0}, {\"HV End\", 0}, {\"New Fill Counter End\", 0}, {\"HI Number\", 0}, {\"Energy Deviation Difference\", 0}, {\"Energy Deviation Max Internal\", 0}, {\"Peak to Peak Fluctuations Max Number 10\", 0}, {\"Peak to Peak Fluctuations Max Number 20\", 0}, {\"Peak to Peak Fluctuations Max Number 100\", 0}, {\"Energy Drop Max Number\", 0}, {\"Tube Pressure Start\", 0}, {\"Tube Pressure End\", 0}, {\"Tube Pressure Rise\", 0}, {\"Energy Deviation Max\", 0}, {\"Energy Deviation Start\", 0}, {\"Energy Deviation End\", 0}, {\"Energy Deviation Average\", 0}, {\"Peak to Peak Fluctuations Start\", 0}, {\"Peak to Peak Fluctuations End\", 0}, {\"Peak to Peak Fluctuations Average\", 0}, {\"Peak to Peak Fluctuations Max Number\", 0}, {\"Max EGY Above Average\", 0}, {\"P2P Fluctuations 6 Sigma\", 0}, {\"Transmission Loss OC P3\", 0}, {\"Transmission Loss HR P3\", 0}, {\"GCS HV F\", 0}, {\"GCS Pulse Width F\", 0}, {\"GCS HV R\", 0}, {\"GCS Pulse Width R\", 0}, {\"User Counter\", 0}, {\"User Counter Job\", 0}}),\r\n  #\"Removed duplicates 1\" = Table.Distinct(#\"Replaced errors\", {\"WORK_ORDER\"}),\r\n  #\"Appended query\" = Table.Combine({#\"Removed duplicates 1\", #\"ET-LDU SPC ET7 - Archive\"})\r\nin\r\n  #\"Appended query\";\r\nshared #\"ET-LDU SPC ET7 - Archive\" = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each Text.Contains([Name], \"CustomReportData-ET7_\")),\r\n  #\"Filtered rows 2\" = Table.SelectRows(#\"Filtered rows\", each [Date modified] < #datetime(2021, 10, 31, 0, 0, 0)),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows 2\", each [Attributes]?[Hidden]? <> true),\r\n  #\"Invoke custom function\" = Table.AddColumn(#\"Filtered hidden files\", \"Transform file (3)\", each #\"Transform file (3)\"([Content])),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Invoke custom function\", {{\"Name\", \"Source.Name\"}}),\r\n  #\"Removed other columns\" = Table.SelectColumns(#\"Renamed columns\", {\"Source.Name\", \"Transform file (3)\"}),\r\n  #\"Expanded table column\" = Table.ExpandTableColumn(#\"Removed other columns\", \"Transform file (3)\", Table.ColumnNames(#\"Transform file (3)\"(#\"Sample file (3)\"))),\r\n  #\"Filtered rows 1\" = Table.SelectRows(#\"Expanded table column\", each [WO_STATUS] <> \"Active\"),\r\n  #\"Choose columns\" = Table.SelectColumns(#\"Filtered rows 1\", {\"DATA_VALUE\", \"MEASUREMENT\", \"PART_NUMBER\", \"SERIAL_NUMBER\", \"WORK_ORDER\"}),\r\n  #\"Trimmed text\" = Table.TransformColumns(#\"Choose columns\", {{\"MEASUREMENT\", each Text.Trim(Text.From(_)), type text}}),\r\n  #\"Removed duplicates\" = Table.Distinct(#\"Trimmed text\", {\"DATA_VALUE\", \"MEASUREMENT\", \"PART_NUMBER\", \"SERIAL_NUMBER\", \"WORK_ORDER\"}),\r\n  #\"Pivoted column\" = Table.Pivot(Table.TransformColumnTypes(#\"Removed duplicates\", {{\"MEASUREMENT\", type text}}), List.Distinct(Table.TransformColumnTypes(#\"Removed duplicates\", {{\"MEASUREMENT\", type text}})[MEASUREMENT]), \"MEASUREMENT\", \"DATA_VALUE\"),\r\n  #\"Removed columns\" = Table.RemoveColumns(#\"Pivoted column\", {\"Cycle  Time Final Customer Run\", \"Cycle Time Post Test\"}),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Removed columns\", {{\"Test Laser\", type text}, {\"PART_NUMBER\", type text}, {\"SERIAL_NUMBER\", type text}, {\"WORK_ORDER\", type text}, {\"GCS HV R\", type number}, {\"Energy Deviation Max Internal\", type number}, {\"Second Hump End\", type number}, {\"GCS Pulse Width R\", Int64.Type}, {\"GCS Pulse Width F\", Int64.Type}, {\"Energy Drop Max Number\", Int64.Type}, {\"Peak to Peak Fluctuations Max Number 10\", Int64.Type}, {\"HV Rise\", Int64.Type}, {\"Peak to Peak Fluctuations Max Number 100\", Int64.Type}, {\"Peak to Peak Fluctuations Max Number 20\", Int64.Type}, {\"Peak to Peak Fluctuations Max Number\", Int64.Type}, {\"Energy Deviation Difference\", type number}, {\"Tube Pressure End\", type number}, {\"User Counter\", type number}, {\"New Fill Counter End\", type number}, {\"HV End\", type number}, {\"Transmission Loss OC P3\", type number}, {\"Second Hump Start\", type number}, {\"Transmission Loss HR P3\", type number}, {\"GCS HV F\", type number}, {\"Peak to Peak Fluctuations End\", type number}, {\"Tube Pressure Rise\", type number}, {\"Tube Pressure Start\", type number}, {\"Peak to Peak Fluctuations Start\", type number}, {\"Energy Deviation Average\", type number}, {\"Peak to Peak Fluctuations Average\", type number}, {\"P2P Fluctuations 6 Sigma\", type number}, {\"HV Start\", type number}, {\"Max EGY Above Average\", type number}, {\"Energy Deviation Start\", type number}, {\"Energy Deviation End\", type number}, {\"Energy Deviation Max\", type number}, {\"HI Number\", Int64.Type}, {\"User Counter Job\", type number}, {\"User Counter Start\", type number}, {\"User Counter End\", type number}}),\r\n  #\"Replaced errors\" = Table.ReplaceErrorValues(#\"Changed column type\", {{\"Second Hump Start\", 0}, {\"HV Rise\", 0}, {\"Second Hump End\", 0}, {\"HV Start\", 0}, {\"HV End\", 0}, {\"New Fill Counter End\", 0}, {\"HI Number\", 0}, {\"Energy Deviation Difference\", 0}, {\"Energy Deviation Max Internal\", 0}, {\"Peak to Peak Fluctuations Max Number 10\", 0}, {\"Peak to Peak Fluctuations Max Number 20\", 0}, {\"Peak to Peak Fluctuations Max Number 100\", 0}, {\"Energy Drop Max Number\", 0}, {\"Tube Pressure Start\", 0}, {\"Tube Pressure End\", 0}, {\"Tube Pressure Rise\", 0}, {\"Energy Deviation Max\", 0}, {\"Energy Deviation Start\", 0}, {\"Energy Deviation End\", 0}, {\"Energy Deviation Average\", 0}, {\"Peak to Peak Fluctuations Start\", 0}, {\"Peak to Peak Fluctuations End\", 0}, {\"Peak to Peak Fluctuations Average\", 0}, {\"Peak to Peak Fluctuations Max Number\", 0}, {\"Max EGY Above Average\", 0}, {\"P2P Fluctuations 6 Sigma\", 0}, {\"Transmission Loss OC P3\", 0}, {\"Transmission Loss HR P3\", 0}, {\"GCS HV F\", 0}, {\"GCS Pulse Width F\", 0}, {\"GCS HV R\", 0}, {\"GCS Pulse Width R\", 0}, {\"User Counter\", 0}, {\"User Counter Job\", 0}}),\r\n  #\"Removed duplicates 1\" = Table.Distinct(#\"Replaced errors\", {\"WORK_ORDER\"})\r\nin\r\n  #\"Removed duplicates 1\";\r\nshared #\"ET-LDU SPC ET7BP\" = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each Text.Contains([Name], \"ET7-BP\")),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows\", each [Attributes]?[Hidden]? <> true),\r\n  #\"Invoke custom function\" = Table.AddColumn(#\"Filtered hidden files\", \"Transform file (4)\", each #\"Transform file (4)\"([Content])),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Invoke custom function\", {{\"Name\", \"Source.Name\"}}),\r\n  #\"Removed other columns\" = Table.SelectColumns(#\"Renamed columns\", {\"Source.Name\", \"Transform file (4)\"}),\r\n  #\"Expanded table column\" = Table.ExpandTableColumn(#\"Removed other columns\", \"Transform file (4)\", Table.ColumnNames(#\"Transform file (4)\"(#\"Sample file (4)\"))),\r\n  #\"Choose columns\" = Table.SelectColumns(#\"Expanded table column\", {\"DATA_VALUE\", \"MEASUREMENT\", \"PART_NUMBER\", \"SERIAL_NUMBER\", \"WORK_ORDER\"}),\r\n  #\"Trimmed text\" = Table.TransformColumns(#\"Choose columns\", {{\"MEASUREMENT\", each Text.Trim(Text.From(_)), type text}}),\r\n  #\"Removed duplicates\" = Table.Distinct(#\"Trimmed text\", {\"DATA_VALUE\", \"MEASUREMENT\", \"PART_NUMBER\", \"SERIAL_NUMBER\", \"WORK_ORDER\"}),\r\n  #\"Pivoted column\" = Table.Pivot(Table.TransformColumnTypes(#\"Removed duplicates\", {{\"MEASUREMENT\", type text}}), List.Distinct(Table.TransformColumnTypes(#\"Removed duplicates\", {{\"MEASUREMENT\", type text}})[MEASUREMENT]), \"MEASUREMENT\", \"DATA_VALUE\"),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Pivoted column\", {{\"PART_NUMBER\", type text}, {\"SERIAL_NUMBER\", type text}, {\"WORK_ORDER\", type text}, {\"Beam Profiler SN\", type text}, {\"Divergency FWHM Short Axis End\", type number}, {\"Beam Pointing Stability Short Axis End\", type number}, {\"Beam Position Stability Short Axis Start\", type number}, {\"Beam Width FWHM Long Axis Start\", type number}, {\"New Fill Counter End\", type number}, {\"Beam Width FWHM Short Axis Start\", type number}, {\"Beam Asymmetry Short Axis Start\", type number}, {\"Beam Asymmetry Long Axis Start\", type number}, {\"Beam Asymmetry Short Axis End\", type number}, {\"Divergency FWHM Long Axis End\", type number}, {\"Beam Pointing Stability Long Axis End\", type number}, {\"Beam Position Stability Long Axis End\", type number}, {\"Beam Position Stability Short Axis End\", type number}, {\"Beam Width 1e2 Long Axis End\", type number}, {\"Beam Position Stability Long Axis Start\", type number}, {\"Beam Width 1e2 Short Axis End\", type number}, {\"Beam Width FWHM Short Axis End\", type number}, {\"Beam Pointing Stability Long Axis Start\", type number}, {\"Beam Pointing Stability Short Axis Start\", type number}, {\"Divergency FWHM Short Axis Start\", type number}, {\"Divergency FWHM Long Axis Start\", type number}, {\"Beam Width 1e2 Short Axis Start\", type number}, {\"Beam Asymmetry Long Axis End\", type number}, {\"Beam Width FWHM Long Axis End\", type number}, {\"Beam Width 1e2 Long Axis Start\", type number}, {\"Beam Position Stability Long Axis Start 2\", type number}, {\"Divergency FWHM Short Axis Start 2\", type number}, {\"Beam Position Stability Short Axis Start 2\", type number}, {\"Divergency FWHM Short Axis End 2\", type number}, {\"Beam Position Stability Long Axis End 2\", type number}, {\"Beam Position Stability Short Axis End 2\", type number}}),\r\n  #\"Replaced errors\" = Table.ReplaceErrorValues(#\"Changed column type\", {{\"Beam Asymmetry Short Axis Start\", 0}, {\"Divergency FWHM Long Axis Start\", 0}, {\"Divergency FWHM Short Axis Start\", 0}, {\"Beam Pointing Stability Short Axis Start\", 0}, {\"Beam Pointing Stability Long Axis Start\", 0}, {\"Beam Position Stability Short Axis Start\", 0}, {\"Beam Position Stability Long Axis Start\", 0}, {\"Beam Width FWHM Long Axis Start\", 0}, {\"Beam Profiler SN\", 0}, {\"Beam Width FWHM Short Axis End\", 0}, {\"Beam Width 1e2 Short Axis End\", 0}, {\"Beam Width FWHM Long Axis End\", 0}, {\"Beam Width 1e2 Long Axis End\", 0}, {\"Beam Asymmetry Long Axis End\", 0}, {\"Beam Asymmetry Short Axis End\", 0}, {\"Divergency FWHM Long Axis End\", 0}, {\"Divergency FWHM Short Axis End\", 0}, {\"Beam Pointing Stability Short Axis End\", 0}, {\"Beam Pointing Stability Long Axis End\", 0}, {\"Beam Position Stability Short Axis End\", 0}, {\"Beam Position Stability Long Axis End\", 0}, {\"New Fill Counter End\", 0}, {\"Beam Width FWHM Short Axis Start\", 0}, {\"Beam Width 1e2 Short Axis Start\", 0}, {\"Beam Width 1e2 Long Axis Start\", 0}, {\"Beam Asymmetry Long Axis Start\", 0}, {\"Divergency FWHM Short Axis Start 2\", 0}, {\"Beam Position Stability Short Axis Start 2\", 0}, {\"Beam Position Stability Long Axis Start 2\", 0}, {\"Divergency FWHM Short Axis End 2\", 0}, {\"Beam Position Stability Long Axis End 2\", 0}, {\"Beam Position Stability Short Axis End 2\", 0}}),\r\n  #\"Removed duplicates 1\" = Table.Distinct(#\"Replaced errors\", {\"WORK_ORDER\"})\r\nin\r\n  #\"Removed duplicates 1\";\r\nshared #\"Sample file\" = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Name] = \"VHP-CustomReportData-ET5_CustomReportDataResult.xlsx\"),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows\", each [Attributes]?[Hidden]? <> true),\r\n  Navigation = #\"Filtered hidden files\"{0}[Content]\r\nin\r\n  Navigation;\r\nshared Parameter = let\r\n  Parameter = #\"Sample file\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type binary]\r\nin\r\n  Parameter;\r\nshared #\"Transform Sample file\" = let\r\n  Source = Excel.Workbook(Parameter, null, true),\r\n  Navigation = Source{[Item = \"CustomReportDataResult\", Kind = \"Sheet\"]}[Data],\r\n  #\"Promoted headers\" = Table.PromoteHeaders(Navigation, [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"CTL_LIMITS\", type any}, {\"DATA_TYPE\", type text}, {\"DATA_VALUE\", type text}, {\"DATE\", type text}, {\"DESCRIPTION\", type text}, {\"DEVIATIONS\", type text}, {\"FLOW\", type text}, {\"MEASUREMENT\", type text}, {\"PART_NUMBER\", type text}, {\"PASS_CTL\", type logical}, {\"PASS_SPEC\", type logical}, {\"PROCESS\", type text}, {\"PROCESS_DESCRIPTION\", type text}, {\"SERIAL_NUMBER\", type text}, {\"SPEC_LIMITS\", type text}, {\"UOM\", type text}, {\"WORK_ORDER\", type text}, {\"WO_NOTES\", type text}, {\"WO_STATUS\", type text}})\r\nin\r\n  #\"Changed column type\";\r\nshared #\"Transform file\" = let\r\n  Source = (Parameter as binary) => let\r\n  Source = Excel.Workbook(Parameter, null, true),\r\n  Navigation = Source{[Item = \"CustomReportDataResult\", Kind = \"Sheet\"]}[Data],\r\n  #\"Promoted headers\" = Table.PromoteHeaders(Navigation, [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"CTL_LIMITS\", type any}, {\"DATA_TYPE\", type text}, {\"DATA_VALUE\", type text}, {\"DATE\", type text}, {\"DESCRIPTION\", type text}, {\"DEVIATIONS\", type text}, {\"FLOW\", type text}, {\"MEASUREMENT\", type text}, {\"PART_NUMBER\", type text}, {\"PASS_CTL\", type logical}, {\"PASS_SPEC\", type logical}, {\"PROCESS\", type text}, {\"PROCESS_DESCRIPTION\", type text}, {\"SERIAL_NUMBER\", type text}, {\"SPEC_LIMITS\", type text}, {\"UOM\", type text}, {\"WORK_ORDER\", type text}, {\"WO_NOTES\", type text}, {\"WO_STATUS\", type text}})\r\nin\r\n  #\"Changed column type\"\r\nin\r\n  Source;\r\nshared #\"Sample file (2)\" = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Name] = \"VHP-CustomReportData-ET6_CustomReportDataResult.xlsx\"),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows\", each [Attributes]?[Hidden]? <> true),\r\n  Navigation = #\"Filtered hidden files\"{0}[Content]\r\nin\r\n  Navigation;\r\nshared #\"Parameter (2)\" = let\r\n  #\"Parameter (2)\" = #\"Sample file (2)\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type binary]\r\nin\r\n  #\"Parameter (2)\";\r\nshared #\"Transform Sample file (2)\" = let\r\n  Source = Excel.Workbook(#\"Parameter (2)\", null, true),\r\n  Navigation = Source{[Item = \"CustomReportDataResult\", Kind = \"Sheet\"]}[Data],\r\n  #\"Promoted headers\" = Table.PromoteHeaders(Navigation, [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"CTL_LIMITS\", type any}, {\"DATA_TYPE\", type text}, {\"DATA_VALUE\", type number}, {\"DATE\", type text}, {\"DESCRIPTION\", type text}, {\"DEVIATIONS\", type text}, {\"FLOW\", type text}, {\"MEASUREMENT\", type text}, {\"PART_NUMBER\", type text}, {\"PASS_CTL\", type logical}, {\"PASS_SPEC\", type logical}, {\"PROCESS\", type text}, {\"PROCESS_DESCRIPTION\", type text}, {\"SERIAL_NUMBER\", type text}, {\"SPEC_LIMITS\", type text}, {\"UOM\", type text}, {\"WORK_ORDER\", type text}, {\"WO_NOTES\", type text}, {\"WO_STATUS\", type text}})\r\nin\r\n  #\"Changed column type\";\r\nshared #\"Transform file (2)\" = let\r\n  Source = (#\"Parameter (2)\" as binary) => let\r\n  Source = Excel.Workbook(#\"Parameter (2)\", null, true),\r\n  Navigation = Source{[Item = \"CustomReportDataResult\", Kind = \"Sheet\"]}[Data],\r\n  #\"Promoted headers\" = Table.PromoteHeaders(Navigation, [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"CTL_LIMITS\", type any}, {\"DATA_TYPE\", type text}, {\"DATA_VALUE\", type number}, {\"DATE\", type text}, {\"DESCRIPTION\", type text}, {\"DEVIATIONS\", type text}, {\"FLOW\", type text}, {\"MEASUREMENT\", type text}, {\"PART_NUMBER\", type text}, {\"PASS_CTL\", type logical}, {\"PASS_SPEC\", type logical}, {\"PROCESS\", type text}, {\"PROCESS_DESCRIPTION\", type text}, {\"SERIAL_NUMBER\", type text}, {\"SPEC_LIMITS\", type text}, {\"UOM\", type text}, {\"WORK_ORDER\", type text}, {\"WO_NOTES\", type text}, {\"WO_STATUS\", type text}})\r\nin\r\n  #\"Changed column type\"\r\nin\r\n  Source;\r\nshared #\"Sample file (3)\" = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each Text.Contains([Name], \"ET7_Custom\")),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows\", each [Attributes]?[Hidden]? <> true),\r\n  Navigation = #\"Filtered hidden files\"{0}[Content]\r\nin\r\n  Navigation;\r\nshared #\"Parameter (3)\" = let\r\n  #\"Parameter (3)\" = #\"Sample file (3)\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type binary]\r\nin\r\n  #\"Parameter (3)\";\r\nshared #\"Transform Sample file (3)\" = let\r\n  Source = Excel.Workbook(#\"Parameter (3)\", null, true),\r\n  Navigation = Source{[Item = \"CustomReportDataResult\", Kind = \"Sheet\"]}[Data],\r\n  #\"Promoted headers\" = Table.PromoteHeaders(Navigation, [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"CTL_LIMITS\", type any}, {\"DATA_TYPE\", type text}, {\"DATA_VALUE\", type text}, {\"DATE\", type text}, {\"DESCRIPTION\", type text}, {\"DEVIATIONS\", type text}, {\"FLOW\", type text}, {\"MEASUREMENT\", type text}, {\"PART_NUMBER\", type text}, {\"PASS_CTL\", type logical}, {\"PASS_SPEC\", type logical}, {\"PROCESS\", type text}, {\"PROCESS_DESCRIPTION\", type text}, {\"SERIAL_NUMBER\", type text}, {\"SPEC_LIMITS\", type text}, {\"UOM\", type text}, {\"WORK_ORDER\", type text}, {\"WO_NOTES\", type text}, {\"WO_STATUS\", type text}})\r\nin\r\n  #\"Changed column type\";\r\nshared #\"Transform file (3)\" = let\r\n  Source = (#\"Parameter (3)\" as binary) => let\r\n  Source = Excel.Workbook(#\"Parameter (3)\", null, true),\r\n  Navigation = Source{[Item = \"CustomReportDataResult\", Kind = \"Sheet\"]}[Data],\r\n  #\"Promoted headers\" = Table.PromoteHeaders(Navigation, [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"CTL_LIMITS\", type any}, {\"DATA_TYPE\", type text}, {\"DATA_VALUE\", type text}, {\"DATE\", type text}, {\"DESCRIPTION\", type text}, {\"DEVIATIONS\", type text}, {\"FLOW\", type text}, {\"MEASUREMENT\", type text}, {\"PART_NUMBER\", type text}, {\"PASS_CTL\", type logical}, {\"PASS_SPEC\", type logical}, {\"PROCESS\", type text}, {\"PROCESS_DESCRIPTION\", type text}, {\"SERIAL_NUMBER\", type text}, {\"SPEC_LIMITS\", type text}, {\"UOM\", type text}, {\"WORK_ORDER\", type text}, {\"WO_NOTES\", type text}, {\"WO_STATUS\", type text}})\r\nin\r\n  #\"Changed column type\"\r\nin\r\n  Source;\r\nshared #\"Sample file (4)\" = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each Text.Contains([Name], \"ET7-BP\")),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows\", each [Attributes]?[Hidden]? <> true),\r\n  Navigation = #\"Filtered hidden files\"{0}[Content]\r\nin\r\n  Navigation;\r\nshared #\"Parameter (4)\" = let\r\n  #\"Parameter (4)\" = #\"Sample file (4)\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type binary]\r\nin\r\n  #\"Parameter (4)\";\r\nshared #\"Transform Sample file (4)\" = let\r\n  Source = Excel.Workbook(#\"Parameter (4)\", null, true),\r\n  Navigation = Source{[Item = \"CustomReportDataResult\", Kind = \"Sheet\"]}[Data],\r\n  #\"Promoted headers\" = Table.PromoteHeaders(Navigation, [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"CTL_LIMITS\", type text}, {\"DATA_TYPE\", type text}, {\"DATA_VALUE\", type text}, {\"DATE\", type text}, {\"DESCRIPTION\", type text}, {\"DEVIATIONS\", type text}, {\"FLOW\", type text}, {\"MEASUREMENT\", type text}, {\"PART_NUMBER\", type text}, {\"PASS_CTL\", type logical}, {\"PASS_SPEC\", type logical}, {\"PROCESS\", type text}, {\"PROCESS_DESCRIPTION\", type text}, {\"SERIAL_NUMBER\", type text}, {\"SPEC_LIMITS\", type text}, {\"UOM\", type text}, {\"WORK_ORDER\", type text}, {\"WO_NOTES\", type text}, {\"WO_STATUS\", type text}})\r\nin\r\n  #\"Changed column type\";\r\nshared #\"Transform file (4)\" = let\r\n  Source = (#\"Parameter (4)\" as binary) => let\r\n  Source = Excel.Workbook(#\"Parameter (4)\", null, true),\r\n  Navigation = Source{[Item = \"CustomReportDataResult\", Kind = \"Sheet\"]}[Data],\r\n  #\"Promoted headers\" = Table.PromoteHeaders(Navigation, [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"CTL_LIMITS\", type text}, {\"DATA_TYPE\", type text}, {\"DATA_VALUE\", type text}, {\"DATE\", type text}, {\"DESCRIPTION\", type text}, {\"DEVIATIONS\", type text}, {\"FLOW\", type text}, {\"MEASUREMENT\", type text}, {\"PART_NUMBER\", type text}, {\"PASS_CTL\", type logical}, {\"PASS_SPEC\", type logical}, {\"PROCESS\", type text}, {\"PROCESS_DESCRIPTION\", type text}, {\"SERIAL_NUMBER\", type text}, {\"SPEC_LIMITS\", type text}, {\"UOM\", type text}, {\"WORK_ORDER\", type text}, {\"WO_NOTES\", type text}, {\"WO_STATUS\", type text}})\r\nin\r\n  #\"Changed column type\"\r\nin\r\n  Source;\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[{\"id\":\"13a6b852-762a-46f5-9e0d-397c85a24e84\",\"name\":\"Transform file from ET-LDU SPC ET5\",\"description\":null,\"parentId\":null,\"order\":0},{\"id\":\"46daed4c-e127-40de-82a8-36f6634fcc72\",\"name\":\"Helper queries\",\"description\":null,\"parentId\":\"13a6b852-762a-46f5-9e0d-397c85a24e84\",\"order\":0},{\"id\":\"67fe7cf2-a454-4e3d-9479-cbfa8ff40e40\",\"name\":\"Transform file from ET-LDU SPC ET6\",\"description\":null,\"parentId\":null,\"order\":0},{\"id\":\"515a21ec-f054-4f4a-b823-af5bb97a21d7\",\"name\":\"Helper queries (2)\",\"description\":null,\"parentId\":\"67fe7cf2-a454-4e3d-9479-cbfa8ff40e40\",\"order\":0},{\"id\":\"077733af-1d94-4f95-a122-ff03aff1ea3d\",\"name\":\"Transform file from ET-LDU SPC ET7\",\"description\":null,\"parentId\":null,\"order\":1},{\"id\":\"32e68dad-7697-43dd-a9cf-10c263b75ebe\",\"name\":\"Helper queries (3)\",\"description\":null,\"parentId\":\"077733af-1d94-4f95-a122-ff03aff1ea3d\",\"order\":0},{\"id\":\"36943665-2dbf-426a-bb78-ce56815ad43b\",\"name\":\"Transform file from ET-LDU SPC ET7BP\",\"description\":null,\"parentId\":null,\"order\":2},{\"id\":\"8864c450-4fc2-4047-bf17-63fe53873680\",\"name\":\"Helper queries (4)\",\"description\":null,\"parentId\":\"36943665-2dbf-426a-bb78-ce56815ad43b\",\"order\":0}]"}],"entities":[{"$type":"LocalEntity","name":"ET-LDU SPC ET5","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"ET-LDU%20SPC%20ET5.csv"},"attributes":[{"name":"PART_NUMBER","dataType":"string"},{"name":"SERIAL_NUMBER","dataType":"string"},{"name":"WORK_ORDER","dataType":"string"},{"name":"E Difference","dataType":"double"},{"name":"User Counter 10 Mio End","dataType":"double"},{"name":"New Fill Counter 10 Mio End","dataType":"double"},{"name":"User Counter 10 Mio Start","dataType":"double"},{"name":"HV 10 Mio Start","dataType":"double"},{"name":"E 10 Mio End","dataType":"double"},{"name":"Test Laser","dataType":"string"},{"name":"Test Laser KEP","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T03:00:28.5384337+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/c2d7d3a0-0703-442a-87ca-ed867d09d2bb/ET-LDU%20SPC%20ET5.csv?snapshot=2022-06-13T03%3A00%3A28.3936031Z"}]},{"$type":"LocalEntity","name":"ET-LDU SPC ET6","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"ET-LDU%20SPC%20ET6.csv"},"attributes":[{"name":"PART_NUMBER","dataType":"string"},{"name":"SERIAL_NUMBER","dataType":"string"},{"name":"WORK_ORDER","dataType":"string"},{"name":"HV Rise Burn-In","dataType":"int64"},{"name":"Energy Deviation Max Internal","dataType":"double"},{"name":"Energy Deviation Start","dataType":"double"},{"name":"User Counter Burn-In Start","dataType":"double"},{"name":"User Counter Burn-In End","dataType":"double"},{"name":"New Fill Counter Burn-In End","dataType":"double"},{"name":"HV Burn-In Start","dataType":"double"},{"name":"HV Burn-In End","dataType":"double"},{"name":"HI Number","dataType":"int64"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T03:00:30.866617+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/c2d7d3a0-0703-442a-87ca-ed867d09d2bb/ET-LDU%20SPC%20ET6.csv?snapshot=2022-06-13T03%3A00%3A30.8022092Z"}]},{"$type":"LocalEntity","name":"ET-LDU SPC ET7","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"ET-LDU%20SPC%20ET7.csv"},"attributes":[{"name":"PART_NUMBER","dataType":"string"},{"name":"SERIAL_NUMBER","dataType":"string"},{"name":"WORK_ORDER","dataType":"string"},{"name":"Second Hump Start","dataType":"double"},{"name":"HV Rise","dataType":"int64"},{"name":"Second Hump End","dataType":"double"},{"name":"HV Start","dataType":"double"},{"name":"User Counter End","dataType":"double"},{"name":"HV End","dataType":"double"},{"name":"New Fill Counter End","dataType":"double"},{"name":"HI Number","dataType":"int64"},{"name":"Energy Deviation Difference","dataType":"double"},{"name":"Energy Deviation Max Internal","dataType":"double"},{"name":"Peak to Peak Fluctuations Max Number 10","dataType":"int64"},{"name":"Peak to Peak Fluctuations Max Number 20","dataType":"int64"},{"name":"Peak to Peak Fluctuations Max Number 100","dataType":"int64"},{"name":"Energy Drop Max Number","dataType":"int64"},{"name":"Tube Pressure Start","dataType":"double"},{"name":"Tube Pressure End","dataType":"double"},{"name":"Tube Pressure Rise","dataType":"double"},{"name":"Energy Deviation Max","dataType":"double"},{"name":"Energy Deviation Start","dataType":"double"},{"name":"Energy Deviation End","dataType":"double"},{"name":"Energy Deviation Average","dataType":"double"},{"name":"Peak to Peak Fluctuations Start","dataType":"double"},{"name":"Peak to Peak Fluctuations End","dataType":"double"},{"name":"User Counter Start","dataType":"double"},{"name":"Peak to Peak Fluctuations Average","dataType":"double"},{"name":"Peak to Peak Fluctuations Max Number","dataType":"int64"},{"name":"Max EGY Above Average","dataType":"double"},{"name":"P2P Fluctuations 6 Sigma","dataType":"double"},{"name":"Transmission Loss OC P3","dataType":"double"},{"name":"Transmission Loss HR P3","dataType":"double"},{"name":"Test Laser","dataType":"string"},{"name":"GCS HV F","dataType":"double"},{"name":"GCS Pulse Width F","dataType":"int64"},{"name":"GCS HV R","dataType":"double"},{"name":"GCS Pulse Width R","dataType":"int64"},{"name":"User Counter","dataType":"double"},{"name":"User Counter Job","dataType":"double"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T03:02:05.9459946+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/c2d7d3a0-0703-442a-87ca-ed867d09d2bb/ET-LDU%20SPC%20ET7.csv?snapshot=2022-06-13T03%3A01%3A58.1445803Z"}]},{"$type":"LocalEntity","name":"ET-LDU SPC ET7BP","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"ET-LDU%20SPC%20ET7BP.csv"},"attributes":[{"name":"PART_NUMBER","dataType":"string"},{"name":"SERIAL_NUMBER","dataType":"string"},{"name":"WORK_ORDER","dataType":"string"},{"name":"Beam Asymmetry Short Axis Start","dataType":"double"},{"name":"Divergency FWHM Long Axis Start","dataType":"double"},{"name":"Divergency FWHM Short Axis Start","dataType":"double"},{"name":"Beam Pointing Stability Short Axis Start","dataType":"double"},{"name":"Beam Pointing Stability Long Axis Start","dataType":"double"},{"name":"Beam Position Stability Short Axis Start","dataType":"double"},{"name":"Beam Position Stability Long Axis Start","dataType":"double"},{"name":"Beam Width FWHM Long Axis Start","dataType":"double"},{"name":"Beam Profiler SN","dataType":"string"},{"name":"Beam Width FWHM Short Axis End","dataType":"double"},{"name":"Beam Width 1e2 Short Axis End","dataType":"double"},{"name":"Beam Width FWHM Long Axis End","dataType":"double"},{"name":"Beam Width 1e2 Long Axis End","dataType":"double"},{"name":"Beam Asymmetry Long Axis End","dataType":"double"},{"name":"Beam Asymmetry Short Axis End","dataType":"double"},{"name":"Divergency FWHM Long Axis End","dataType":"double"},{"name":"Divergency FWHM Short Axis End","dataType":"double"},{"name":"Beam Pointing Stability Short Axis End","dataType":"double"},{"name":"Beam Pointing Stability Long Axis End","dataType":"double"},{"name":"Beam Position Stability Short Axis End","dataType":"double"},{"name":"Beam Position Stability Long Axis End","dataType":"double"},{"name":"New Fill Counter End","dataType":"double"},{"name":"Beam Width FWHM Short Axis Start","dataType":"double"},{"name":"Beam Width 1e2 Short Axis Start","dataType":"double"},{"name":"Beam Width 1e2 Long Axis Start","dataType":"double"},{"name":"Beam Asymmetry Long Axis Start","dataType":"double"},{"name":"Divergency FWHM Short Axis Start 2","dataType":"double"},{"name":"Beam Position Stability Short Axis Start 2","dataType":"double"},{"name":"Beam Position Stability Long Axis Start 2","dataType":"double"},{"name":"Divergency FWHM Short Axis End 2","dataType":"double"},{"name":"Beam Position Stability Long Axis End 2","dataType":"double"},{"name":"Beam Position Stability Short Axis End 2","dataType":"double"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-13T03:01:20.007516+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/c2d7d3a0-0703-442a-87ca-ed867d09d2bb/ET-LDU%20SPC%20ET7BP.csv?snapshot=2022-06-13T03%3A01%3A18.0158405Z"}]}]}