{"name":"Flow_Oracle-Exported Files V2","description":"Flow for different Oracle exported files. Daily exported to the server.","version":"1.0","culture":"en-US","modifiedTime":"2021-07-16T07:41:10.8435779+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"Excimer_WW_Inventory":{"queryId":"746be95a-b36f-4f72-b6e2-82623d4c10d8","queryName":"Excimer_WW_Inventory","loadEnabled":true},"WIP_Valuation_Details":{"queryId":"07fcc2e0-d545-4942-80c9-b2f5e6f83ca5","queryName":"WIP_Valuation_Details","loadEnabled":true},"FacilityTickets":{"queryId":"1bd57499-aaa7-452e-a1db-8db5c218f623","queryName":"FacilityTickets","loadEnabled":true},"Transform Sample file":{"queryId":"ddb31ac6-7eee-41c2-bc1c-eb56579f906d","queryName":"Transform Sample file","queryGroupId":"a8e2596e-283c-4d87-8f28-15d0fd552a6b"},"Sample file":{"queryId":"d2606bf2-d326-48a9-87a8-e6ffa78a3115","queryName":"Sample file","queryGroupId":"4e6448d8-078a-4abf-bad7-412b4f831cb5"},"Parameter":{"queryId":"6de18476-b614-4592-96a0-69ab57858f2c","queryName":"Parameter","queryGroupId":"4e6448d8-078a-4abf-bad7-412b4f831cb5"},"Transform file":{"queryId":"457fdaa0-6da6-46da-b7a4-0f9fc73b3383","queryName":"Transform file","queryGroupId":"4e6448d8-078a-4abf-bad7-412b4f831cb5"},"Transform Sample file (3)":{"queryId":"f2e7f46b-91c4-4b1a-9f8f-d0c07b5c41a2","queryName":"Transform Sample file (3)","queryGroupId":"a36e32ce-9d3a-4acd-b907-0ebe1a541d4b"},"Sample file (3)":{"queryId":"b2fbd8d0-5805-4b74-91d4-6301410bd6eb","queryName":"Sample file (3)","queryGroupId":"4e4cb43f-681e-421e-b426-ed727a150dfa"},"Parameter (3)":{"queryId":"7ddf4f8e-c6e9-423b-a637-2ddea1c76868","queryName":"Parameter (3)","queryGroupId":"4e4cb43f-681e-421e-b426-ed727a150dfa"},"Transform file (3)":{"queryId":"7437aa95-e4c1-4df8-bbd7-2f63d8b4fceb","queryName":"Transform file (3)","queryGroupId":"4e4cb43f-681e-421e-b426-ed727a150dfa"},"Transform Sample file (6)":{"queryId":"ead55c69-ab1b-4f01-b914-821e796b5b94","queryName":"Transform Sample file (6)","queryGroupId":"dc6d23b1-75bc-4d86-9ad1-9610ed49daaa"},"Sample file (6)":{"queryId":"dc9c6677-4859-4819-bbfd-d5827a2ba7a4","queryName":"Sample file (6)","queryGroupId":"36a42fe3-2e46-4817-b767-7e86f72481ee"},"Parameter (6)":{"queryId":"467a3a03-5f21-42e4-973d-3f546aece7ed","queryName":"Parameter (6)","queryGroupId":"36a42fe3-2e46-4817-b767-7e86f72481ee"},"Transform file (6)":{"queryId":"3d54c12e-2112-464b-85e1-08f18292a144","queryName":"Transform file (6)","queryGroupId":"36a42fe3-2e46-4817-b767-7e86f72481ee"},"Transform Sample File8":{"queryId":"65a7a849-17df-4ac6-ad5f-2c3b5465a9be","queryName":"Transform Sample File8","queryGroupId":"ab0f2f4a-8213-4c78-b34e-8b7bea84b2ef"},"Sample File8":{"queryId":"c54e1fe2-6ac6-434b-b00f-025e665143a5","queryName":"Sample File8","queryGroupId":"04f55ace-ad27-4339-9e3e-42b79fc6e535"},"Parameter1":{"queryId":"16b22721-19fa-4c73-9ccb-7ecbb939704a","queryName":"Parameter1","queryGroupId":"04f55ace-ad27-4339-9e3e-42b79fc6e535"},"Transform File8":{"queryId":"54079b5a-3857-410a-9029-e1bf397cf05f","queryName":"Transform File8","queryGroupId":"04f55ace-ad27-4339-9e3e-42b79fc6e535"},"TeileKat":{"queryId":"f39b4b1a-b1c2-441d-b2d4-c2dd24de2dac","queryName":"TeileKat","loadEnabled":true}},"document":"section Section1;\r\nshared Excimer_WW_Inventory = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Name] = \"Excimer_WW_Inventory_With_Serial_Nums_-_OnHandTable.xlsx\"),\r\n  #\"Invoke custom function\" = Table.AddColumn(#\"Filtered rows\", \"Transform file\", each #\"Transform file\"([Content])),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Invoke custom function\", {{\"Name\", \"Source.Name\"}}),\r\n  #\"Removed other columns\" = Table.SelectColumns(#\"Renamed columns\", {\"Source.Name\", \"Transform file\"}),\r\n  #\"Expanded Transform file\" = Table.ExpandTableColumn(#\"Removed other columns\", \"Transform file\", {\"Data Source\", \"Reporting Tbu\", \"Owning Organization\", \"Item Number\", \"Item Description\", \"Item Rev\", \"Product Family\", \"Subinventory\", \"Loc Shelf\", \"Loc Bin\", \"Quantity\", \"Lot Number\", \"Serial Number\", \"Item Cost\", \"Material Cost\", \"Material Overhead Cost\", \"Resource Cost\", \"Overhead Cost\", \"Outside Processing Cost\", \"Date IN\", \"Age mths\", \"Extended Value Usd\"}, {\"Data Source\", \"Reporting Tbu\", \"Owning Organization\", \"Item Number\", \"Item Description\", \"Item Rev\", \"Product Family\", \"Subinventory\", \"Loc Shelf\", \"Loc Bin\", \"Quantity\", \"Lot Number\", \"Serial Number\", \"Item Cost\", \"Material Cost\", \"Material Overhead Cost\", \"Resource Cost\", \"Overhead Cost\", \"Outside Processing Cost\", \"Date IN\", \"Age mths\", \"Extended Value Usd\"}),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Expanded Transform file\", {{\"Source.Name\", type text}, {\"Data Source\", type text}, {\"Reporting Tbu\", type text}, {\"Owning Organization\", type text}, {\"Item Number\", type text}, {\"Item Description\", type text}, {\"Item Rev\", type text}, {\"Product Family\", type text}, {\"Subinventory\", type text}, {\"Loc Shelf\", type text}, {\"Loc Bin\", type text}, {\"Quantity\", type number}, {\"Lot Number\", type any}, {\"Serial Number\", type text}, {\"Item Cost\", type number}, {\"Material Cost\", type number}, {\"Material Overhead Cost\", type number}, {\"Resource Cost\", Int64.Type}, {\"Overhead Cost\", Int64.Type}, {\"Outside Processing Cost\", type number}, {\"Date IN\", type any}, {\"Age mths\", type number}, {\"Extended Value Usd\", type number}}),\r\n  #\"Changed column type 1\" = Table.TransformColumnTypes(#\"Changed column type\", {{\"Lot Number\", type text}, {\"Date IN\", type datetime}, {\"Item Cost\", Currency.Type}, {\"Material Cost\", Currency.Type}, {\"Material Overhead Cost\", Currency.Type}, {\"Resource Cost\", Currency.Type}, {\"Overhead Cost\", Currency.Type}, {\"Outside Processing Cost\", Currency.Type}, {\"Extended Value Usd\", Currency.Type}}),\r\n  #\"Removed columns\" = Table.RemoveColumns(#\"Changed column type 1\", {\"Source.Name\"}),\r\n  #\"Choose columns\" = Table.SelectColumns(#\"Removed columns\", {\"Reporting Tbu\", \"Owning Organization\", \"Item Number\", \"Item Description\", \"Item Rev\", \"Product Family\", \"Subinventory\", \"Loc Shelf\", \"Loc Bin\", \"Quantity\", \"Lot Number\", \"Serial Number\", \"Item Cost\", \"Material Cost\", \"Material Overhead Cost\", \"Resource Cost\", \"Overhead Cost\", \"Outside Processing Cost\", \"Date IN\", \"Age mths\", \"Extended Value Usd\"})\r\nin\r\n  #\"Choose columns\";\r\nshared WIP_Valuation_Details = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Name] = \"Goettingen_WIP_Valuation_Details_-_Results_Open_And_Closed.xlsx\"),\r\n  #\"Invoke custom function\" = Table.AddColumn(#\"Filtered rows\", \"Transform file (3)\", each #\"Transform file (3)\"([Content])),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Invoke custom function\", {{\"Name\", \"Source.Name\"}}),\r\n  #\"Removed other columns\" = Table.SelectColumns(#\"Renamed columns\", {\"Source.Name\", \"Transform file (3)\"}),\r\n  #\"Expanded Transform file (3)\" = Table.ExpandTableColumn(#\"Removed other columns\", \"Transform file (3)\", {\"Owning Organization\", \"Subinventory\", \"Planner Code\", \"Wip Entity Name\", \"Job Type\", \"Job Status\", \"Item Number\", \"Item Description\", \"Primary Uom Code\", \"Start Quantity\", \"Quantity Completed\", \"Date Started\", \"Date Completed\", \"Quantity Scrapped\", \"Quantity Remaining\", \"Date Released\", \"Calender Days since Release\", \"Cal Mths rel'd\", \"Full Lead Time\", \"Technical Business Unit\", \"Product Family\", \"Product Line\", \"Spc Item Cost\", \"Ext SPC Start Qty\", \"Total Costs Incurred\", \"Total Costs Relieved\", \"Total Variances Relieved\", \"Total Net Activities\", \"Tot Net Activities Usd\", \"Acct Class Type\", \"Class Code\", \"Scheduled Start Date\", \"Date Closed\", \"Order Number\", \"Order Line\", \"Customer Name\", \"Agile Life Phase\", \"Lead Time Category\", \"Item Type Code\", \"Item Type\", \"Forecast Field\", \"Acct Attribute1\", \"Acct Attribute2\", \"Acct Attribute3\", \"Material Entity\", \"Material Dept\", \"Material Acct\", \"Mat Var Entity\", \"Mat Var Dept\", \"Mat Var Acct\", \"Extract date\", \"Material Costs Incurred\", \"Material Costs Relieved\", \"Material Net Activities\", \"Material Oh Costs Incurred\", \"Material Oh Costs Relieved\", \"Material Oh Net Activities\", \"Material Oh Variances Relieved\", \"Material Variances Relieved\", \"Os Process Costs Incurred\", \"Os Process Costs Relieved\", \"Os Process Net Activities\", \"Os Process Variances Relieved\", \"Overhead Costs Incurred\", \"Overhead Costs Relieved\", \"Overhead Net Activities\", \"Overhead Variances Relieved\", \"Resource Costs Incurred\", \"Resource Costs Relieved\", \"Resource Net Activities\", \"Resource Variances Relieved\"}, {\"Owning Organization\", \"Subinventory\", \"Planner Code\", \"Wip Entity Name\", \"Job Type\", \"Job Status\", \"Item Number\", \"Item Description\", \"Primary Uom Code\", \"Start Quantity\", \"Quantity Completed\", \"Date Started\", \"Date Completed\", \"Quantity Scrapped\", \"Quantity Remaining\", \"Date Released\", \"Calender Days since Release\", \"Cal Mths rel'd\", \"Full Lead Time\", \"Technical Business Unit\", \"Product Family\", \"Product Line\", \"Spc Item Cost\", \"Ext SPC Start Qty\", \"Total Costs Incurred\", \"Total Costs Relieved\", \"Total Variances Relieved\", \"Total Net Activities\", \"Tot Net Activities Usd\", \"Acct Class Type\", \"Class Code\", \"Scheduled Start Date\", \"Date Closed\", \"Order Number\", \"Order Line\", \"Customer Name\", \"Agile Life Phase\", \"Lead Time Category\", \"Item Type Code\", \"Item Type\", \"Forecast Field\", \"Acct Attribute1\", \"Acct Attribute2\", \"Acct Attribute3\", \"Material Entity\", \"Material Dept\", \"Material Acct\", \"Mat Var Entity\", \"Mat Var Dept\", \"Mat Var Acct\", \"Extract date\", \"Material Costs Incurred\", \"Material Costs Relieved\", \"Material Net Activities\", \"Material Oh Costs Incurred\", \"Material Oh Costs Relieved\", \"Material Oh Net Activities\", \"Material Oh Variances Relieved\", \"Material Variances Relieved\", \"Os Process Costs Incurred\", \"Os Process Costs Relieved\", \"Os Process Net Activities\", \"Os Process Variances Relieved\", \"Overhead Costs Incurred\", \"Overhead Costs Relieved\", \"Overhead Net Activities\", \"Overhead Variances Relieved\", \"Resource Costs Incurred\", \"Resource Costs Relieved\", \"Resource Net Activities\", \"Resource Variances Relieved\"}),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Expanded Transform file (3)\", {{\"Source.Name\", type text}, {\"Owning Organization\", type text}, {\"Subinventory\", type text}, {\"Planner Code\", type text}, {\"Wip Entity Name\", type text}, {\"Job Type\", type text}, {\"Job Status\", type text}, {\"Item Number\", type text}, {\"Item Description\", type text}, {\"Primary Uom Code\", type text}, {\"Start Quantity\", Int64.Type}, {\"Quantity Completed\", Int64.Type}, {\"Date Started\", type datetime}, {\"Date Completed\", type datetime}, {\"Quantity Scrapped\", Int64.Type}, {\"Quantity Remaining\", Int64.Type}, {\"Date Released\", type datetime}, {\"Calender Days since Release\", type number}, {\"Cal Mths rel'd\", type number}, {\"Full Lead Time\", type number}, {\"Technical Business Unit\", type text}, {\"Product Family\", type text}, {\"Product Line\", type text}, {\"Spc Item Cost\", type number}, {\"Ext SPC Start Qty\", type number}, {\"Total Costs Incurred\", type number}, {\"Total Costs Relieved\", type number}, {\"Total Variances Relieved\", type number}, {\"Total Net Activities\", type number}, {\"Tot Net Activities Usd\", type number}, {\"Acct Class Type\", type text}, {\"Class Code\", type text}, {\"Scheduled Start Date\", type date}, {\"Date Closed\", type datetime}, {\"Order Number\", type text}, {\"Order Line\", type text}, {\"Customer Name\", type text}, {\"Agile Life Phase\", type text}, {\"Lead Time Category\", type text}, {\"Item Type Code\", type text}, {\"Item Type\", type text}, {\"Forecast Field\", type text}, {\"Acct Attribute1\", type text}, {\"Acct Attribute2\", type text}, {\"Acct Attribute3\", type text}, {\"Material Entity\", type text}, {\"Material Dept\", type text}, {\"Material Acct\", type text}, {\"Mat Var Entity\", type text}, {\"Mat Var Dept\", type text}, {\"Mat Var Acct\", type text}, {\"Extract date\", type datetime}, {\"Material Costs Incurred\", type number}, {\"Material Costs Relieved\", type number}, {\"Material Net Activities\", type number}, {\"Material Oh Costs Incurred\", type number}, {\"Material Oh Costs Relieved\", type number}, {\"Material Oh Net Activities\", type number}, {\"Material Oh Variances Relieved\", type number}, {\"Material Variances Relieved\", type number}, {\"Os Process Costs Incurred\", type number}, {\"Os Process Costs Relieved\", type number}, {\"Os Process Net Activities\", type number}, {\"Os Process Variances Relieved\", type number}, {\"Overhead Costs Incurred\", type number}, {\"Overhead Costs Relieved\", type number}, {\"Overhead Net Activities\", type number}, {\"Overhead Variances Relieved\", type number}, {\"Resource Costs Incurred\", type number}, {\"Resource Costs Relieved\", type number}, {\"Resource Net Activities\", type number}, {\"Resource Variances Relieved\", type number}}),\r\n  #\"Removed columns\" = Table.RemoveColumns(#\"Changed column type\", {\"Lead Time Category\"})\r\nin\r\n  #\"Removed columns\";\r\nshared FacilityTickets = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering/\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Name] = \"facilities_request.xlsx\"),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows\", each [Attributes]?[Hidden]? <> true),\r\n  #\"Invoke custom function\" = Table.AddColumn(#\"Filtered hidden files\", \"Transform file (6)\", each #\"Transform file (6)\"([Content])),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Invoke custom function\", {{\"Name\", \"Source.Name\"}}),\r\n  #\"Removed other columns\" = Table.SelectColumns(#\"Renamed columns\", {\"Source.Name\", \"Transform file (6)\"}),\r\n  #\"Expanded table column\" = Table.ExpandTableColumn(#\"Removed other columns\", \"Transform file (6)\", Table.ColumnNames(#\"Transform file (6)\"(#\"Sample file (6)\"))),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Expanded table column\", {{\"Source.Name\", type text}, {\"Number\", type text}, {\"Opened\", type datetime}, {\"Short description\", type text}, {\"Item\", type text}, {\"Requested for\", type text}, {\"Department number\", type text}, {\"Department\", type text}, {\"Location\", type text}, {\"Assignment group\", type text}, {\"State\", type text}, {\"Updated\", type datetime}, {\"Closed\", type datetime}, {\"Opened by\", type text}}),\r\n  #\"Removed other columns 1\" = Table.SelectColumns(#\"Changed column type\", {\"Number\", \"Opened\", \"Short description\", \"Item\", \"Requested for\", \"Department number\", \"Department\", \"Location\", \"Assignment group\", \"State\", \"Updated\", \"Closed\", \"Opened by\"})\r\nin\r\n  #\"Removed other columns 1\";\r\nshared #\"Transform Sample file\" = let\r\n  Source = Excel.Workbook(Parameter, null, true),\r\n  Navigation = Source{[Item = \"Sheet\", Kind = \"Sheet\"]}[Data],\r\n  #\"Promoted headers\" = Table.PromoteHeaders(Navigation, [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"Data Source\", type text}, {\"Reporting Tbu\", type text}, {\"Owning Organization\", type text}, {\"Item Number\", type text}, {\"Item Description\", type text}, {\"Item Rev\", type text}, {\"Product Family\", type text}, {\"Subinventory\", type text}, {\"Loc Shelf\", type any}, {\"Loc Bin\", type text}, {\"Quantity\", type number}, {\"Lot Number\", type any}, {\"Serial Number\", type text}, {\"Item Cost\", type number}, {\"Material Cost\", type number}, {\"Material Overhead Cost\", type number}, {\"Resource Cost\", Int64.Type}, {\"Overhead Cost\", Int64.Type}, {\"Outside Processing Cost\", type number}, {\"Date IN\", type any}, {\"Age mths\", type number}, {\"Extended Value Usd\", type number}})\r\nin\r\n  #\"Changed column type\";\r\nshared #\"Sample file\" = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Name] = \"Excimer_WW_Inventory_With_Serial_Nums_-_OnHandTable.xlsx\"),\r\n  Navigation = #\"Filtered rows\"{0}[Content]\r\nin\r\n  Navigation;\r\nshared Parameter = let\r\n  Parameter = #\"Sample file\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type binary]\r\nin\r\n  Parameter;\r\nshared #\"Transform file\" = let\r\n  Source = (Parameter as binary) => let\n  Source = Excel.Workbook(Parameter, null, true),\n  Navigation = Source{[Item = \"Sheet\", Kind = \"Sheet\"]}[Data],\n  #\"Promoted headers\" = Table.PromoteHeaders(Navigation, [PromoteAllScalars = true]),\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"Data Source\", type text}, {\"Reporting Tbu\", type text}, {\"Owning Organization\", type text}, {\"Item Number\", type text}, {\"Item Description\", type text}, {\"Item Rev\", type text}, {\"Product Family\", type text}, {\"Subinventory\", type text}, {\"Loc Shelf\", type any}, {\"Loc Bin\", type text}, {\"Quantity\", type number}, {\"Lot Number\", type any}, {\"Serial Number\", type text}, {\"Item Cost\", type number}, {\"Material Cost\", type number}, {\"Material Overhead Cost\", type number}, {\"Resource Cost\", Int64.Type}, {\"Overhead Cost\", Int64.Type}, {\"Outside Processing Cost\", type number}, {\"Date IN\", type any}, {\"Age mths\", type number}, {\"Extended Value Usd\", type number}})\nin\n  #\"Changed column type\"\r\nin\r\n  Source;\r\nshared #\"Transform Sample file (3)\" = let\r\n  Source = Excel.Workbook(#\"Parameter (3)\", null, true),\r\n  Navigation = Source{[Item = \"Sheet\", Kind = \"Sheet\"]}[Data],\r\n  #\"Promoted headers\" = Table.PromoteHeaders(Navigation, [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"Owning Organization\", type text}, {\"Subinventory\", type text}, {\"Planner Code\", type text}, {\"Wip Entity Name\", type text}, {\"Job Type\", type text}, {\"Job Status\", type text}, {\"Item Number\", type text}, {\"Item Description\", type text}, {\"Primary Uom Code\", type text}, {\"Start Quantity\", Int64.Type}, {\"Quantity Completed\", Int64.Type}, {\"Date Started\", type datetime}, {\"Date Completed\", type datetime}, {\"Quantity Scrapped\", Int64.Type}, {\"Quantity Remaining\", Int64.Type}, {\"Date Released\", type datetime}, {\"Calender Days since Release\", type number}, {\"Cal Mths rel'd\", type number}, {\"Full Lead Time\", type number}, {\"Technical Business Unit\", type text}, {\"Product Family\", type text}, {\"Product Line\", type text}, {\"Spc Item Cost\", type number}, {\"Ext SPC Start Qty\", type number}, {\"Total Costs Incurred\", type number}, {\"Total Costs Relieved\", type number}, {\"Total Variances Relieved\", type number}, {\"Total Net Activities\", type number}, {\"Tot Net Activities Usd\", type number}, {\"Acct Class Type\", type text}, {\"Class Code\", type text}, {\"Scheduled Start Date\", type any}, {\"Date Closed\", type datetime}, {\"Order Number\", Int64.Type}, {\"Order Line\", type any}, {\"Customer Name\", type text}, {\"Agile Life Phase\", type text}, {\"Lead Time Category\", Int64.Type}, {\"Item Type Code\", type text}, {\"Item Type\", type text}, {\"Forecast Field\", type text}, {\"Acct Attribute1\", type text}, {\"Acct Attribute2\", type text}, {\"Acct Attribute3\", type text}, {\"Material Entity\", Int64.Type}, {\"Material Dept\", Int64.Type}, {\"Material Acct\", Int64.Type}, {\"Mat Var Entity\", Int64.Type}, {\"Mat Var Dept\", Int64.Type}, {\"Mat Var Acct\", Int64.Type}, {\"Extract date\", type datetime}, {\"Material Costs Incurred\", type number}, {\"Material Costs Relieved\", type number}, {\"Material Net Activities\", type number}, {\"Material Oh Costs Incurred\", type number}, {\"Material Oh Costs Relieved\", type number}, {\"Material Oh Net Activities\", type number}, {\"Material Oh Variances Relieved\", type number}, {\"Material Variances Relieved\", type number}, {\"Os Process Costs Incurred\", type number}, {\"Os Process Costs Relieved\", type number}, {\"Os Process Net Activities\", type number}, {\"Os Process Variances Relieved\", type number}, {\"Overhead Costs Incurred\", type number}, {\"Overhead Costs Relieved\", type number}, {\"Overhead Net Activities\", type number}, {\"Overhead Variances Relieved\", type number}, {\"Resource Costs Incurred\", type number}, {\"Resource Costs Relieved\", type number}, {\"Resource Net Activities\", type number}, {\"Resource Variances Relieved\", type number}})\r\nin\r\n  #\"Changed column type\";\r\nshared #\"Sample file (3)\" = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Name] = \"Goettingen_WIP_Valuation_Details_-_Results_Open_And_Closed.xlsx\"),\r\n  Navigation = #\"Filtered rows\"{0}[Content]\r\nin\r\n  Navigation;\r\nshared #\"Parameter (3)\" = let\r\n  #\"Parameter (3)\" = #\"Sample file (3)\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type binary]\r\nin\r\n  #\"Parameter (3)\";\r\nshared #\"Transform file (3)\" = let\r\n  Source = (#\"Parameter (3)\" as binary) => let\n  Source = Excel.Workbook(#\"Parameter (3)\", null, true),\n  Navigation = Source{[Item = \"Sheet\", Kind = \"Sheet\"]}[Data],\n  #\"Promoted headers\" = Table.PromoteHeaders(Navigation, [PromoteAllScalars = true]),\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"Owning Organization\", type text}, {\"Subinventory\", type text}, {\"Planner Code\", type text}, {\"Wip Entity Name\", type text}, {\"Job Type\", type text}, {\"Job Status\", type text}, {\"Item Number\", type text}, {\"Item Description\", type text}, {\"Primary Uom Code\", type text}, {\"Start Quantity\", Int64.Type}, {\"Quantity Completed\", Int64.Type}, {\"Date Started\", type datetime}, {\"Date Completed\", type datetime}, {\"Quantity Scrapped\", Int64.Type}, {\"Quantity Remaining\", Int64.Type}, {\"Date Released\", type datetime}, {\"Calender Days since Release\", type number}, {\"Cal Mths rel'd\", type number}, {\"Full Lead Time\", type number}, {\"Technical Business Unit\", type text}, {\"Product Family\", type text}, {\"Product Line\", type text}, {\"Spc Item Cost\", type number}, {\"Ext SPC Start Qty\", type number}, {\"Total Costs Incurred\", type number}, {\"Total Costs Relieved\", type number}, {\"Total Variances Relieved\", type number}, {\"Total Net Activities\", type number}, {\"Tot Net Activities Usd\", type number}, {\"Acct Class Type\", type text}, {\"Class Code\", type text}, {\"Scheduled Start Date\", type any}, {\"Date Closed\", type datetime}, {\"Order Number\", Int64.Type}, {\"Order Line\", type any}, {\"Customer Name\", type text}, {\"Agile Life Phase\", type text}, {\"Lead Time Category\", Int64.Type}, {\"Item Type Code\", type text}, {\"Item Type\", type text}, {\"Forecast Field\", type text}, {\"Acct Attribute1\", type text}, {\"Acct Attribute2\", type text}, {\"Acct Attribute3\", type text}, {\"Material Entity\", Int64.Type}, {\"Material Dept\", Int64.Type}, {\"Material Acct\", Int64.Type}, {\"Mat Var Entity\", Int64.Type}, {\"Mat Var Dept\", Int64.Type}, {\"Mat Var Acct\", Int64.Type}, {\"Extract date\", type datetime}, {\"Material Costs Incurred\", type number}, {\"Material Costs Relieved\", type number}, {\"Material Net Activities\", type number}, {\"Material Oh Costs Incurred\", type number}, {\"Material Oh Costs Relieved\", type number}, {\"Material Oh Net Activities\", type number}, {\"Material Oh Variances Relieved\", type number}, {\"Material Variances Relieved\", type number}, {\"Os Process Costs Incurred\", type number}, {\"Os Process Costs Relieved\", type number}, {\"Os Process Net Activities\", type number}, {\"Os Process Variances Relieved\", type number}, {\"Overhead Costs Incurred\", type number}, {\"Overhead Costs Relieved\", type number}, {\"Overhead Net Activities\", type number}, {\"Overhead Variances Relieved\", type number}, {\"Resource Costs Incurred\", type number}, {\"Resource Costs Relieved\", type number}, {\"Resource Net Activities\", type number}, {\"Resource Variances Relieved\", type number}})\nin\n  #\"Changed column type\"\r\nin\r\n  Source;\r\nshared #\"Transform Sample file (6)\" = let\r\n  Source = Excel.Workbook(#\"Parameter (6)\", null, true),\r\n  Navigation = Source{[Item = \"Page 1\", Kind = \"Sheet\"]}[Data],\r\n  #\"Promoted headers\" = Table.PromoteHeaders(Navigation, [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"Number\", type text}, {\"Opened\", type datetime}, {\"Short description\", type text}, {\"Item\", type text}, {\"Requested for\", type text}, {\"Department number\", Int64.Type}, {\"Department\", type text}, {\"Location\", type text}, {\"Assignment group\", type text}, {\"State\", type text}, {\"Updated\", type datetime}, {\"Closed\", type datetime}, {\"Opened by\", type text}})\r\nin\r\n  #\"Changed column type\";\r\nshared #\"Sample file (6)\" = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering/\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Name] = \"facilities_request.xlsx\"),\r\n  Navigation = #\"Filtered rows\"{0}[Content]\r\nin\r\n  Navigation;\r\nshared #\"Parameter (6)\" = let\r\n  #\"Parameter (6)\" = #\"Sample file (6)\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type binary]\r\nin\r\n  #\"Parameter (6)\";\r\nshared #\"Transform file (6)\" = let\r\n  Source = (#\"Parameter (6)\" as binary) => let\n  Source = Excel.Workbook(#\"Parameter (6)\", null, true),\n  Navigation = Source{[Item = \"Page 1\", Kind = \"Sheet\"]}[Data],\n  #\"Promoted headers\" = Table.PromoteHeaders(Navigation, [PromoteAllScalars = true]),\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"Number\", type text}, {\"Opened\", type datetime}, {\"Short description\", type text}, {\"Item\", type text}, {\"Requested for\", type text}, {\"Department number\", Int64.Type}, {\"Department\", type text}, {\"Location\", type text}, {\"Assignment group\", type text}, {\"State\", type text}, {\"Updated\", type datetime}, {\"Closed\", type datetime}, {\"Opened by\", type text}})\nin\n  #\"Changed column type\"\r\nin\r\n  Source;\r\nshared #\"Transform Sample File8\" = let\r\n  Source = Csv.Document(Parameter1, [Delimiter = \"#(tab)\", Columns = 88, Encoding = 1252, QuoteStyle = QuoteStyle.None]),\r\n  #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars = true])\r\nin\r\n  #\"Promoted Headers\";\r\nshared #\"Sample File8\" = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n  #\"Filtered Rows\" = Table.SelectRows(Source, each [Name] = \"teilkat.txt\"),\r\n  Navigation1 = #\"Filtered Rows\"{0}[Content]\r\nin\r\n  Navigation1;\r\nshared Parameter1 = let\r\n  Parameter1 = #\"Sample File8\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type binary, BinaryIdentifier = #\"Sample File8\"]\r\nin\r\n  Parameter1;\r\nshared #\"Transform File8\" = let\r\n  Source = (Parameter1) => let\n        Source = Csv.Document(Parameter1,[Delimiter=\"\t\", Columns=88, Encoding=1252, QuoteStyle=QuoteStyle.None]),\n        #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true])\n    in\n        #\"Promoted Headers\"\r\nin\r\n  Source;\r\nshared TeileKat = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n  #\"Filtered Rows\" = Table.SelectRows(Source, each [Name] = \"teilkat.txt\"),\r\n  #\"Filtered Hidden Files1\" = Table.SelectRows(#\"Filtered Rows\", each [Attributes]?[Hidden]? <> true),\r\n  #\"Invoke Custom Function1\" = Table.AddColumn(#\"Filtered Hidden Files1\", \"Transform File\", each #\"Transform File8\"([Content])),\r\n  #\"Renamed Columns1\" = Table.RenameColumns(#\"Invoke Custom Function1\", {\"Name\", \"Source.Name\"}),\r\n  #\"Removed Other Columns1\" = Table.SelectColumns(#\"Renamed Columns1\", {\"Source.Name\", \"Transform File\"}),\r\n  #\"Expanded Table Column1\" = Table.ExpandTableColumn(#\"Removed Other Columns1\", \"Transform File\", Table.ColumnNames(#\"Transform File8\"(#\"Sample File8\"))),\r\n  #\"Choose columns\" = Table.SelectColumns(#\"Expanded Table Column1\", {\"ITEM\", \"description\", \"Plannercode\", \"Buyer\", \"Item Cost\", \"Material Cost\", \"Material Overhead Cost\", \"Resource Cost\", \"OSP Cost\", \"Overheader Cost\", \"Nettable Qty\", \"Non Nettable Qty\", \"Safety Stock\", \"Sourcing commodity\", \"Product Family\", \"Product Line\", \"Forecast Field\", \"Org Product Family\", \"Org Product Line\", \"Org Forecast Field\", \"Lead Time\", \"Make/Buy Flag\", \"Item Status\", \"WIP Supply Type\", \"SubInventory + Locator\", \"Fixed Lot Multiplier\", \"Fixed Order Quantity\", \"Fixed Days Supply\", \"Minimum Order Qty\", \"Maximum Order Qty\", \"Min MinMax Quantity\", \"Max MinMax Quantity\", \"Rev\", \"UOM\", \"Qty Rcvd not Del\", \"Processing Lead Time\", \"Current Issues FY\", \"Issues Last FY\", \"Issues Last 12 Months\", \"Issues Last 90 Days\", \"Current Recipts FY\", \"Receipts Last FY\", \"Receipts Last 12 Months\", \"Receipts Last 90 Days\", \"CC Adj Last 12 Months\", \"Last Issue Date\", \"Last Receipt Date\", \"Qty on Order\", \"Gross Requirements\", \"Gross requirements days 0 - 30\", \"Gross requirements days 30 - 60\", \"Gross requirements days 60 - 90\", \"Gross requirements days 90 - 180\", \"Gross requirements days 180 - 360\", \"User Item Type\", \"Receipt Routing\", \"Inventory Planning Method\", \"MPS/MRP PLanning Method\", \"Commodity Code\", \"Creation Date\", \"Last Update Date\", \"Wip Supply Subinv\", \"Wip Supply Locator\", \"Completion Subinv\", \"Completion Locator\", \"Receiv Default Subinv\", \"Receiv Default Subinv 2\", \"Receiv Default Locator\", \"To Receiver\", \"Source org or Vendor\", \"Source type\", \"Lot Control\", \"Serial Number Control\", \"Release Time Fence\", \"By-Products\", \"By-Products days 0 - 30\", \"By-Products days 30 - 60\", \"By-Products days 60 - 90\", \"By-Products days 90 - 180\", \"By-Products days 180 - 360\", \"APOP (Average PO Price Paid)\", \"Acceptable Early Days\", \"UOM of Weight\", \"Unit Weight\", \"Cumulative Total Lead Time\"}),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Choose columns\", {{\"ITEM\", type text}, {\"description\", type text}, {\"Plannercode\", type text}, {\"Buyer\", type text}, {\"Sourcing commodity\", type text}, {\"Product Family\", type text}, {\"Product Line\", type text}, {\"Forecast Field\", type text}, {\"Org Product Family\", type text}, {\"Org Product Line\", type text}, {\"Org Forecast Field\", type text}, {\"Make/Buy Flag\", type text}, {\"Item Status\", type text}, {\"WIP Supply Type\", type text}, {\"SubInventory + Locator\", type text}, {\"Rev\", type text}, {\"UOM\", type text}, {\"User Item Type\", type text}, {\"Receipt Routing\", type text}, {\"Inventory Planning Method\", type text}, {\"MPS/MRP PLanning Method\", type text}, {\"Commodity Code\", type text}, {\"Wip Supply Subinv\", type text}, {\"Wip Supply Locator\", type text}, {\"Completion Subinv\", type text}, {\"Completion Locator\", type text}, {\"Receiv Default Subinv\", type text}, {\"Receiv Default Subinv 2\", type text}, {\"Receiv Default Locator\", type text}, {\"To Receiver\", type text}, {\"Source org or Vendor\", type text}, {\"Source type\", type text}, {\"Lot Control\", type text}, {\"Serial Number Control\", type text}, {\"UOM of Weight\", type text}}),\r\n  #\"Changed column type with locale\" = Table.TransformColumnTypes(#\"Changed column type\", {{\"Item Cost\", type number}, {\"Material Cost\", type number}, {\"Material Overhead Cost\", type number}, {\"Resource Cost\", type number}, {\"OSP Cost\", type number}, {\"Overheader Cost\", type number}, {\"Nettable Qty\", type number}, {\"Non Nettable Qty\", type number}, {\"Safety Stock\", type number}}, \"de-DE\"),\r\n  #\"Changed column type with locale 1\" = Table.TransformColumnTypes(#\"Changed column type with locale\", {{\"Lead Time\", type number}, {\"Fixed Lot Multiplier\", type number}, {\"Fixed Order Quantity\", type number}, {\"Fixed Days Supply\", type number}, {\"Minimum Order Qty\", type number}, {\"Maximum Order Qty\", type number}, {\"Min MinMax Quantity\", type number}, {\"Max MinMax Quantity\", type number}, {\"Qty Rcvd not Del\", type number}, {\"Processing Lead Time\", type number}, {\"Current Issues FY\", type number}, {\"Issues Last FY\", type number}, {\"Issues Last 12 Months\", type number}, {\"Issues Last 90 Days\", type number}, {\"Current Recipts FY\", type number}, {\"Receipts Last FY\", type number}, {\"Receipts Last 12 Months\", type number}, {\"Receipts Last 90 Days\", type number}, {\"CC Adj Last 12 Months\", type number}, {\"Qty on Order\", type number}, {\"Gross Requirements\", type number}, {\"Gross requirements days 0 - 30\", type number}, {\"Gross requirements days 30 - 60\", type number}, {\"Gross requirements days 60 - 90\", type number}, {\"Gross requirements days 90 - 180\", type number}, {\"Gross requirements days 180 - 360\", type number}, {\"Release Time Fence\", type text}, {\"By-Products\", type number}, {\"By-Products days 0 - 30\", type number}, {\"By-Products days 30 - 60\", type number}, {\"By-Products days 60 - 90\", type number}, {\"By-Products days 90 - 180\", type number}, {\"By-Products days 180 - 360\", type number}, {\"APOP (Average PO Price Paid)\", type number}, {\"Acceptable Early Days\", type number}, {\"Unit Weight\", type number}, {\"Cumulative Total Lead Time\", type number}, {\"Last Update Date\", type date}, {\"Creation Date\", type date}, {\"Last Receipt Date\", type date}, {\"Last Issue Date\", type date}}, \"de-DE\"),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Changed column type with locale 1\", {{\"ITEM\", \"Item\"}, {\"description\", \"Item Description\"}, {\"Current Issues FY\", \"Current Issued FY\"}, {\"Issues Last FY\", \"Issued Last FY\"}, {\"Issues Last 12 Months\", \"Issued Last 12 Months\"}, {\"Issues Last 90 Days\", \"Issued Last 90 Days\"}}),\r\n  #\"Added custom\" = Table.AddColumn(#\"Renamed columns\", \"Stock Value\", each [Item Cost] * [Nettable Qty]),\r\n  #\"Changed column type 1\" = Table.TransformColumnTypes(#\"Added custom\", {{\"Stock Value\", Currency.Type}}),\r\n  #\"Added custom 1\" = Table.AddColumn(#\"Changed column type 1\", \"Refurb\", each Text.Contains([Item], \"R\")),\r\n  #\"Changed column type 2\" = Table.TransformColumnTypes(#\"Added custom 1\", {{\"Refurb\", type logical}})\r\nin\r\n  #\"Changed column type 2\";\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[{\"id\":\"a8e2596e-283c-4d87-8f28-15d0fd552a6b\",\"name\":\"Transform file from Excimer_WW_Inventory\",\"description\":\"\",\"parentId\":null,\"order\":1},{\"id\":\"4e6448d8-078a-4abf-bad7-412b4f831cb5\",\"name\":\"Helper queries\",\"description\":\"\",\"parentId\":\"a8e2596e-283c-4d87-8f28-15d0fd552a6b\",\"order\":2},{\"id\":\"a36e32ce-9d3a-4acd-b907-0ebe1a541d4b\",\"name\":\"Transform file from WIP_Valuation_Details\",\"description\":\"\",\"parentId\":null,\"order\":1},{\"id\":\"4e4cb43f-681e-421e-b426-ed727a150dfa\",\"name\":\"Helper queries (3)\",\"description\":\"\",\"parentId\":\"a36e32ce-9d3a-4acd-b907-0ebe1a541d4b\",\"order\":2},{\"id\":\"dc6d23b1-75bc-4d86-9ad1-9610ed49daaa\",\"name\":\"Transform file from FacilityTickets\",\"description\":\"\",\"parentId\":null,\"order\":1},{\"id\":\"36a42fe3-2e46-4817-b767-7e86f72481ee\",\"name\":\"Helper queries (6)\",\"description\":\"\",\"parentId\":\"dc6d23b1-75bc-4d86-9ad1-9610ed49daaa\",\"order\":2},{\"id\":\"ab0f2f4a-8213-4c78-b34e-8b7bea84b2ef\",\"name\":\"Transform File from TeileKat\",\"description\":\"\",\"parentId\":null,\"order\":1},{\"id\":\"04f55ace-ad27-4339-9e3e-42b79fc6e535\",\"name\":\"Helper Queries\",\"description\":\"\",\"parentId\":\"ab0f2f4a-8213-4c78-b34e-8b7bea84b2ef\",\"order\":2}]"}],"entities":[{"$type":"LocalEntity","name":"Excimer_WW_Inventory","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Excimer_WW_Inventory.csv"},"attributes":[{"name":"Reporting Tbu","dataType":"string"},{"name":"Owning Organization","dataType":"string"},{"name":"Item Number","dataType":"string"},{"name":"Item Description","dataType":"string"},{"name":"Item Rev","dataType":"string"},{"name":"Product Family","dataType":"string"},{"name":"Subinventory","dataType":"string"},{"name":"Loc Shelf","dataType":"string"},{"name":"Loc Bin","dataType":"string"},{"name":"Quantity","dataType":"double"},{"name":"Lot Number","dataType":"string"},{"name":"Serial Number","dataType":"string"},{"name":"Item Cost","dataType":"decimal"},{"name":"Material Cost","dataType":"decimal"},{"name":"Material Overhead Cost","dataType":"decimal"},{"name":"Resource Cost","dataType":"decimal"},{"name":"Overhead Cost","dataType":"decimal"},{"name":"Outside Processing Cost","dataType":"decimal"},{"name":"Date IN","dataType":"dateTime"},{"name":"Age mths","dataType":"double"},{"name":"Extended Value Usd","dataType":"decimal"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-20T10:02:32.0359098+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/a9bf97c8-31b9-4cef-93f5-becca8246492/Excimer_WW_Inventory.csv?snapshot=2022-05-20T10%3A02%3A31.9704882Z"}]},{"$type":"LocalEntity","name":"WIP_Valuation_Details","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"WIP_Valuation_Details.csv"},"attributes":[{"name":"Source.Name","dataType":"string"},{"name":"Owning Organization","dataType":"string"},{"name":"Subinventory","dataType":"string"},{"name":"Planner Code","dataType":"string"},{"name":"Wip Entity Name","dataType":"string"},{"name":"Job Type","dataType":"string"},{"name":"Job Status","dataType":"string"},{"name":"Item Number","dataType":"string"},{"name":"Item Description","dataType":"string"},{"name":"Primary Uom Code","dataType":"string"},{"name":"Start Quantity","dataType":"int64"},{"name":"Quantity Completed","dataType":"int64"},{"name":"Date Started","dataType":"dateTime"},{"name":"Date Completed","dataType":"dateTime"},{"name":"Quantity Scrapped","dataType":"int64"},{"name":"Quantity Remaining","dataType":"int64"},{"name":"Date Released","dataType":"dateTime"},{"name":"Calender Days since Release","dataType":"double"},{"name":"Cal Mths rel'd","dataType":"double"},{"name":"Full Lead Time","dataType":"double"},{"name":"Technical Business Unit","dataType":"string"},{"name":"Product Family","dataType":"string"},{"name":"Product Line","dataType":"string"},{"name":"Spc Item Cost","dataType":"double"},{"name":"Ext SPC Start Qty","dataType":"double"},{"name":"Total Costs Incurred","dataType":"double"},{"name":"Total Costs Relieved","dataType":"double"},{"name":"Total Variances Relieved","dataType":"double"},{"name":"Total Net Activities","dataType":"double"},{"name":"Tot Net Activities Usd","dataType":"double"},{"name":"Acct Class Type","dataType":"string"},{"name":"Class Code","dataType":"string"},{"name":"Scheduled Start Date","dataType":"date"},{"name":"Date Closed","dataType":"dateTime"},{"name":"Order Number","dataType":"string"},{"name":"Order Line","dataType":"string"},{"name":"Customer Name","dataType":"string"},{"name":"Agile Life Phase","dataType":"string"},{"name":"Item Type Code","dataType":"string"},{"name":"Item Type","dataType":"string"},{"name":"Forecast Field","dataType":"string"},{"name":"Acct Attribute1","dataType":"string"},{"name":"Acct Attribute2","dataType":"string"},{"name":"Acct Attribute3","dataType":"string"},{"name":"Material Entity","dataType":"string"},{"name":"Material Dept","dataType":"string"},{"name":"Material Acct","dataType":"string"},{"name":"Mat Var Entity","dataType":"string"},{"name":"Mat Var Dept","dataType":"string"},{"name":"Mat Var Acct","dataType":"string"},{"name":"Extract date","dataType":"dateTime"},{"name":"Material Costs Incurred","dataType":"double"},{"name":"Material Costs Relieved","dataType":"double"},{"name":"Material Net Activities","dataType":"double"},{"name":"Material Oh Costs Incurred","dataType":"double"},{"name":"Material Oh Costs Relieved","dataType":"double"},{"name":"Material Oh Net Activities","dataType":"double"},{"name":"Material Oh Variances Relieved","dataType":"double"},{"name":"Material Variances Relieved","dataType":"double"},{"name":"Os Process Costs Incurred","dataType":"double"},{"name":"Os Process Costs Relieved","dataType":"double"},{"name":"Os Process Net Activities","dataType":"double"},{"name":"Os Process Variances Relieved","dataType":"double"},{"name":"Overhead Costs Incurred","dataType":"double"},{"name":"Overhead Costs Relieved","dataType":"double"},{"name":"Overhead Net Activities","dataType":"double"},{"name":"Overhead Variances Relieved","dataType":"double"},{"name":"Resource Costs Incurred","dataType":"double"},{"name":"Resource Costs Relieved","dataType":"double"},{"name":"Resource Net Activities","dataType":"double"},{"name":"Resource Variances Relieved","dataType":"double"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-20T10:02:38.8584718+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/a9bf97c8-31b9-4cef-93f5-becca8246492/WIP_Valuation_Details.csv?snapshot=2022-05-20T10%3A02%3A38.8305177Z"}]},{"$type":"LocalEntity","name":"FacilityTickets","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"FacilityTickets.csv"},"attributes":[{"name":"Number","dataType":"string"},{"name":"Opened","dataType":"dateTime"},{"name":"Short description","dataType":"string"},{"name":"Item","dataType":"string"},{"name":"Requested for","dataType":"string"},{"name":"Department number","dataType":"string"},{"name":"Department","dataType":"string"},{"name":"Location","dataType":"string"},{"name":"Assignment group","dataType":"string"},{"name":"State","dataType":"string"},{"name":"Updated","dataType":"dateTime"},{"name":"Closed","dataType":"dateTime"},{"name":"Opened by","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-20T10:02:32.4890443+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/a9bf97c8-31b9-4cef-93f5-becca8246492/FacilityTickets.csv?snapshot=2022-05-20T10%3A02%3A32.4602048Z"}]},{"$type":"LocalEntity","name":"TeileKat","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"TeileKat.csv"},"attributes":[{"name":"Item","dataType":"string"},{"name":"Item Description","dataType":"string"},{"name":"Plannercode","dataType":"string"},{"name":"Buyer","dataType":"string"},{"name":"Item Cost","dataType":"double"},{"name":"Material Cost","dataType":"double"},{"name":"Material Overhead Cost","dataType":"double"},{"name":"Resource Cost","dataType":"double"},{"name":"OSP Cost","dataType":"double"},{"name":"Overheader Cost","dataType":"double"},{"name":"Nettable Qty","dataType":"double"},{"name":"Non Nettable Qty","dataType":"double"},{"name":"Safety Stock","dataType":"double"},{"name":"Sourcing commodity","dataType":"string"},{"name":"Product Family","dataType":"string"},{"name":"Product Line","dataType":"string"},{"name":"Forecast Field","dataType":"string"},{"name":"Org Product Family","dataType":"string"},{"name":"Org Product Line","dataType":"string"},{"name":"Org Forecast Field","dataType":"string"},{"name":"Lead Time","dataType":"double"},{"name":"Make/Buy Flag","dataType":"string"},{"name":"Item Status","dataType":"string"},{"name":"WIP Supply Type","dataType":"string"},{"name":"SubInventory + Locator","dataType":"string"},{"name":"Fixed Lot Multiplier","dataType":"double"},{"name":"Fixed Order Quantity","dataType":"double"},{"name":"Fixed Days Supply","dataType":"double"},{"name":"Minimum Order Qty","dataType":"double"},{"name":"Maximum Order Qty","dataType":"double"},{"name":"Min MinMax Quantity","dataType":"double"},{"name":"Max MinMax Quantity","dataType":"double"},{"name":"Rev","dataType":"string"},{"name":"UOM","dataType":"string"},{"name":"Qty Rcvd not Del","dataType":"double"},{"name":"Processing Lead Time","dataType":"double"},{"name":"Current Issued FY","dataType":"double"},{"name":"Issued Last FY","dataType":"double"},{"name":"Issued Last 12 Months","dataType":"double"},{"name":"Issued Last 90 Days","dataType":"double"},{"name":"Current Recipts FY","dataType":"double"},{"name":"Receipts Last FY","dataType":"double"},{"name":"Receipts Last 12 Months","dataType":"double"},{"name":"Receipts Last 90 Days","dataType":"double"},{"name":"CC Adj Last 12 Months","dataType":"double"},{"name":"Last Issue Date","dataType":"date"},{"name":"Last Receipt Date","dataType":"date"},{"name":"Qty on Order","dataType":"double"},{"name":"Gross Requirements","dataType":"double"},{"name":"Gross requirements days 0 - 30","dataType":"double"},{"name":"Gross requirements days 30 - 60","dataType":"double"},{"name":"Gross requirements days 60 - 90","dataType":"double"},{"name":"Gross requirements days 90 - 180","dataType":"double"},{"name":"Gross requirements days 180 - 360","dataType":"double"},{"name":"User Item Type","dataType":"string"},{"name":"Receipt Routing","dataType":"string"},{"name":"Inventory Planning Method","dataType":"string"},{"name":"MPS/MRP PLanning Method","dataType":"string"},{"name":"Commodity Code","dataType":"string"},{"name":"Creation Date","dataType":"date"},{"name":"Last Update Date","dataType":"date"},{"name":"Wip Supply Subinv","dataType":"string"},{"name":"Wip Supply Locator","dataType":"string"},{"name":"Completion Subinv","dataType":"string"},{"name":"Completion Locator","dataType":"string"},{"name":"Receiv Default Subinv","dataType":"string"},{"name":"Receiv Default Subinv 2","dataType":"string"},{"name":"Receiv Default Locator","dataType":"string"},{"name":"To Receiver","dataType":"string"},{"name":"Source org or Vendor","dataType":"string"},{"name":"Source type","dataType":"string"},{"name":"Lot Control","dataType":"string"},{"name":"Serial Number Control","dataType":"string"},{"name":"Release Time Fence","dataType":"string"},{"name":"By-Products","dataType":"double"},{"name":"By-Products days 0 - 30","dataType":"double"},{"name":"By-Products days 30 - 60","dataType":"double"},{"name":"By-Products days 60 - 90","dataType":"double"},{"name":"By-Products days 90 - 180","dataType":"double"},{"name":"By-Products days 180 - 360","dataType":"double"},{"name":"APOP (Average PO Price Paid)","dataType":"double"},{"name":"Acceptable Early Days","dataType":"double"},{"name":"UOM of Weight","dataType":"string"},{"name":"Unit Weight","dataType":"double"},{"name":"Cumulative Total Lead Time","dataType":"double"},{"name":"Stock Value","dataType":"decimal"},{"name":"Refurb","dataType":"boolean"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-20T10:03:18.6871064+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/a9bf97c8-31b9-4cef-93f5-becca8246492/TeileKat.csv?snapshot=2022-05-20T10%3A03%3A18.6474745Z"}]}]}