{"name":"Flow_Cumulus_DailyRF","description":"Cumulus tables from Snowflake with daily refresh.","version":"1.0","culture":"en-US","modifiedTime":"2022-06-13T07:30:17.9871171+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":true,"queriesMetadata":{"CUM_PartNumberV_SF":{"queryId":"9b098db0-ca90-4629-b06c-1e8ca2eda554","queryName":"CUM_PartNumberV_SF","queryGroupId":"ee8ca336-f600-4f0d-a347-d2c7a52504d0","loadEnabled":true},"CUM_Sandboxes_SF":{"queryId":"af2d9b5d-c713-4e99-8a1b-86b2bd7b10a9","queryName":"CUM_Sandboxes_SF","queryGroupId":"ee8ca336-f600-4f0d-a347-d2c7a52504d0","loadEnabled":true},"CUM_TAGs_SF":{"queryId":"49b3c464-fd38-4a96-8ee8-7982b100be07","queryName":"CUM_TAGs_SF","queryGroupId":"ee8ca336-f600-4f0d-a347-d2c7a52504d0","loadEnabled":true},"CUM_USERS_SF":{"queryId":"757973a6-aeeb-43be-9255-5bd19a9391a9","queryName":"CUM_USERS_SF","queryGroupId":"ee8ca336-f600-4f0d-a347-d2c7a52504d0","loadEnabled":true},"Cumulus_Packaging_LP":{"queryId":"95d32700-7e81-493c-9b5e-abc5962c489c","queryName":"Cumulus_Packaging_LP","queryGroupId":"823ac51d-c902-46cb-8c59-928fcc5fbcba"},"Cumulus_Packaging_MP":{"queryId":"3a50539b-278f-4e0d-ac93-710d2dd79fb6","queryName":"Cumulus_Packaging_MP","queryGroupId":"823ac51d-c902-46cb-8c59-928fcc5fbcba"},"Cumulus_Packaging":{"queryId":"a37e719c-5264-4955-8070-c6357772d08a","queryName":"Cumulus_Packaging","queryGroupId":"823ac51d-c902-46cb-8c59-928fcc5fbcba","loadEnabled":true},"CUM_Deviations_SF":{"queryId":"c60c9712-6cb5-49de-a854-a9d4d92380a2","queryName":"CUM_Deviations_SF","queryGroupId":"ee8ca336-f600-4f0d-a347-d2c7a52504d0","loadEnabled":true}},"document":"section Section1;\r\nshared CUM_PartNumberV_SF = let\n    CUM_WOCompletion_SF = Value.NativeQuery(Snowflake.Databases(\"mma12090.snowflakecomputing.com\",\"COMPUTE_REPORTING\", [Role=\"GLBMFGOPERATIONSROLE\"]){[Name=\"PROD_DB\"]}[Data], \"SELECT *FROM PROD_DB.CUMULUS.CUM_PARTNUMBER_V WHERE INVORG_CODE='GEP' \", null, [EnableFolding=true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(CUM_WOCompletion_SF, {{\"PARTNUMBERKEY\", Int64.Type}, {\"SANDBOXKEY\", Int64.Type}}),\r\n  #\"Choose columns\" = Table.SelectColumns(#\"Changed column type\", {\"PARTNUMBERKEY\", \"PART_DESCRIPTION\", \"SANDBOXKEY\", \"ACTIVE\", \"CREATE_DATE\", \"MODIFY_DATE\", \"TYPE\", \"PART_NUMBER\", \"WIP_DISPLAY\", \"AGILE_AUTO_SYNC\", \"WORK_CELL\", \"PRODUCTION_TYPE\", \"FLOW_NAME\", \"ORACLE_GENERIC_PN\", \"INVORG_CODE\", \"SANDBOX\", \"ITEM_ORG_KEY_CODE\", \"ITEM_SANDBOX_KEY_ID\"})\nin\n    #\"Choose columns\";\r\nshared CUM_Sandboxes_SF = let\n    CUM_WOCompletion_SF = Value.NativeQuery(Snowflake.Databases(\"mma12090.snowflakecomputing.com\",\"COMPUTE_REPORTING\", [Role=\"GLBMFGOPERATIONSROLE\"]){[Name=\"PROD_DB\"]}[Data], \"SELECT *FROM PROD_DB.CUMULUS.CUM_SANDBOXES WHERE (Business_Unit='GEP' or Business_Unit='KEP') \", null, [EnableFolding=true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(CUM_WOCompletion_SF, {{\"SANDBOXKEY\", Int64.Type}}),\r\n  #\"Sorted rows\" = Table.Sort(#\"Changed column type\", {{\"SANDBOXKEY\", Order.Ascending}})\nin\n    #\"Sorted rows\";\r\nshared CUM_TAGs_SF = let\n    CUM_WOCompletion_SF = Value.NativeQuery(Snowflake.Databases(\"mma12090.snowflakecomputing.com\",\"COMPUTE_REPORTING\", [Role=\"GLBMFGOPERATIONSROLE\"]){[Name=\"PROD_DB\"]}[Data], \"SELECT *FROM PROD_DB.CUMULUS.CUM_TAGS_V WHERE (Sandboxkey=2076 or Sandboxkey=2078 or Sandboxkey=2086 or Sandboxkey=2122 or Sandboxkey=2158 or Sandboxkey=2220 or Sandboxkey=2264 or Sandboxkey=2328) \", null, [EnableFolding=true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(CUM_WOCompletion_SF, {{\"SANDBOXKEY\", Int64.Type}, {\"PARTNUMBERKEY\", Int64.Type}})\nin\n    #\"Changed column type\";\r\nshared CUM_USERS_SF = let\n    CUM_WOCompletion_SF = Value.NativeQuery(Snowflake.Databases(\"mma12090.snowflakecomputing.com\",\"COMPUTE_REPORTING\", [Role=\"GLBMFGOPERATIONSROLE\"]){[Name=\"PROD_DB\"]}[Data], \"SELECT *FROM PROD_DB.CUMULUS.CUM_USERS WHERE (Sandboxkey=2076 or Sandboxkey=2078 or Sandboxkey=2086 or Sandboxkey=2122 or Sandboxkey=2158 or Sandboxkey=2220 or Sandboxkey=2264 or Sandboxkey=2328) \", null, [EnableFolding=true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(CUM_WOCompletion_SF, {{\"USERKEY\", Int64.Type}, {\"SANDBOXKEY\", Int64.Type}})\nin\n    #\"Changed column type\";\r\nshared Cumulus_Packaging_LP = let\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\n  #\"Filtered rows\" = Table.SelectRows(Source, each ([Extension] = \".xlsx\")),\r\n  #\"Filtered rows 1\" = Table.SelectRows(#\"Filtered rows\", each Text.Contains([Name], \"Packaging\")),\r\n  Navigation = #\"Filtered rows 1\"{[#\"Folder Path\" = \"https://cohrinc.sharepoint.com/teams/Operations/Excimer-Göttingen/Manuf. Engineering/Shared Documents/Production Data/LP/\", Name = \"LP-CRD_Packaging_CustomReportDataResult.xlsx\"]}[Content],\r\n  #\"Imported Excel workbook\" = Excel.Workbook(Navigation, null, true),\r\n  #\"Navigation 1\" = #\"Imported Excel workbook\"{[Item = \"CustomReportDataResult\", Kind = \"Sheet\"]}[Data],\r\n  #\"Promoted headers\" = Table.PromoteHeaders(#\"Navigation 1\", [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"WORK_ORDER\", Int64.Type}, {\"WO_STATUS\", type text}, {\"TYPE\", type text}, {\"SERIAL_NUMBER\", type text}, {\"PART_NUMBER\", type text}, {\"DESCRIPTION\", type text}, {\"FLOW\", type text}, {\"PROCESS\", type text}, {\"PROCESS_DESCRIPTION\", type text}, {\"PROCESS_STEP_INDEX\", Int64.Type}, {\"MEASUREMENT\", type text}, {\"DATA_TYPE\", type text}, {\"UOM\", type any}, {\"DATE\", type text}, {\"DATA_VALUE\", type text}, {\"PASS_SPEC\", type logical}, {\"PASS_CTL\", type logical}, {\"SPEC_LIMITS\", type any}, {\"CTL_LIMITS\", type any}, {\"WO_NOTES\", type text}, {\"DEVIATIONS\", type text}, {\"FLOW_STEP_DESC\", type any}}),\r\n  #\"Changed column type with locale\" = Table.TransformColumnTypes(#\"Changed column type\", {{\"DATE\", type datetime}}, \"de-DE\"),\r\n  #\"Choose columns\" = Table.SelectColumns(#\"Changed column type with locale\", {\"WORK_ORDER\", \"WO_STATUS\", \"TYPE\", \"SERIAL_NUMBER\", \"PART_NUMBER\", \"DESCRIPTION\", \"FLOW\", \"PROCESS\", \"PROCESS_DESCRIPTION\", \"PROCESS_STEP_INDEX\", \"MEASUREMENT\", \"DATE\", \"DATA_VALUE\"}),\r\n  #\"Added custom\" = Table.TransformColumnTypes(Table.AddColumn(#\"Choose columns\", \"Sandbox\", each \"LP\"), {{\"Sandbox\", type text}})\nin\n  #\"Added custom\";\r\nshared Cumulus_Packaging_MP = let\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\n  #\"Filtered rows\" = Table.SelectRows(Source, each ([Extension] = \".xlsx\")),\r\n  #\"Filtered rows 1\" = Table.SelectRows(#\"Filtered rows\", each Text.Contains([Name], \"Packaging\")),\r\n  Navigation = #\"Filtered rows 1\"{[#\"Folder Path\" = \"https://cohrinc.sharepoint.com/teams/Operations/Excimer-Göttingen/Manuf. Engineering/Shared Documents/Production Data/MP/\", Name = \"MP-CRD_Packaging_CustomReportDataResult.xlsx\"]}[Content],\r\n  #\"Imported Excel workbook\" = Excel.Workbook(Navigation, null, true),\r\n  #\"Navigation 1\" = #\"Imported Excel workbook\"{[Item = \"CustomReportDataResult\", Kind = \"Sheet\"]}[Data],\r\n  #\"Promoted headers\" = Table.PromoteHeaders(#\"Navigation 1\", [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"WORK_ORDER\", Int64.Type}, {\"WO_STATUS\", type text}, {\"TYPE\", type text}, {\"SERIAL_NUMBER\", type text}, {\"PART_NUMBER\", type text}, {\"DESCRIPTION\", type text}, {\"FLOW\", type text}, {\"PROCESS\", type text}, {\"PROCESS_DESCRIPTION\", type text}, {\"PROCESS_STEP_INDEX\", Int64.Type}, {\"MEASUREMENT\", type text}, {\"DATA_TYPE\", type text}, {\"UOM\", type any}, {\"DATE\", type text}, {\"DATA_VALUE\", type text}, {\"PASS_SPEC\", type logical}, {\"PASS_CTL\", type logical}, {\"SPEC_LIMITS\", type any}, {\"CTL_LIMITS\", type any}, {\"WO_NOTES\", type text}, {\"DEVIATIONS\", type text}, {\"FLOW_STEP_DESC\", type any}}),\r\n  #\"Changed column type with locale\" = Table.TransformColumnTypes(#\"Changed column type\", {{\"DATE\", type datetime}}, \"de-DE\"),\r\n  #\"Choose columns\" = Table.SelectColumns(#\"Changed column type with locale\", {\"WORK_ORDER\", \"WO_STATUS\", \"TYPE\", \"SERIAL_NUMBER\", \"PART_NUMBER\", \"DESCRIPTION\", \"FLOW\", \"PROCESS\", \"PROCESS_DESCRIPTION\", \"PROCESS_STEP_INDEX\", \"MEASUREMENT\", \"DATE\", \"DATA_VALUE\"}),\r\n  #\"Added custom\" = Table.TransformColumnTypes(Table.AddColumn(#\"Choose columns\", \"Sandbox\", each \"MP\"), {{\"Sandbox\", type text}})\nin\n  #\"Added custom\";\r\nshared Cumulus_Packaging = let\r\n  Source = Table.Combine({Cumulus_Packaging_LP, Cumulus_Packaging_MP}),\r\n  #\"Pivoted column\" = Table.Pivot(Table.TransformColumnTypes(Source, {{\"MEASUREMENT\", type text}}), List.Distinct(Table.TransformColumnTypes(Source, {{\"MEASUREMENT\", type text}})[MEASUREMENT]), \"MEASUREMENT\", \"DATA_VALUE\")\r\nin\r\n  #\"Pivoted column\";\r\nshared CUM_Deviations_SF = let\n    CUM_WOCompletion_SF = Value.NativeQuery(Snowflake.Databases(\"mma12090.snowflakecomputing.com\",\"COMPUTE_REPORTING\", [Role=\"GLBMFGOPERATIONSROLE\"]){[Name=\"PROD_DB\"]}[Data], \"SELECT *FROM PROD_DB.CUMULUS.CUM_DEVIATIONS Where ORG is null or ORG='GEP' or ORG='KEP'\", null, [EnableFolding=true]),\n  #\"Choose columns\" = Table.SelectColumns(CUM_WOCompletion_SF, {\"DEVIATIONKEY\", \"SANDBOXKEY\", \"CREATE_DATE\", \"UPDATE_DATE\", \"ACTIVE\", \"ORG\", \"SITE\", \"AGILE_DEVIATION\", \"TITLE\", \"REASON\", \"DESCRIPTION\", \"DEVIATION\", \"TYPE\", \"MODE\", \"WORKCELL\", \"START_DATE\", \"END_DATE\", \"VALIDATION\", \"VALIDATION_PERMISSION\", \"APPLY_PARENT\", \"SHIP_REST\", \"SHIP_REST_DESC\", \"PROCESS\", \"PROCESS_DESCRIPTION\", \"SUPPLIER\", \"DEVIATION_CODE\", \"DEFECT_CODE\", \"REJECT_CODE\", \"NOTES\"}),\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Choose columns\", {{\"DEVIATIONKEY\", Int64.Type}, {\"SANDBOXKEY\", Int64.Type}}),\r\n  #\"Filtered rows\" = Table.SelectRows(#\"Changed column type\", each [SANDBOXKEY] = 2076 or [SANDBOXKEY] = 2078 or [SANDBOXKEY] = 2086 or [SANDBOXKEY] = 2122 or [SANDBOXKEY] = 2158 or [SANDBOXKEY] = 2220 or [SANDBOXKEY] = 2264 or [SANDBOXKEY] = 2328)\nin\n    #\"Filtered rows\";\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[{\"id\":\"ee8ca336-f600-4f0d-a347-d2c7a52504d0\",\"name\":\"SnowFlake\",\"description\":\"Tables from Amazon SnowFlake.\",\"parentId\":null,\"order\":0},{\"id\":\"823ac51d-c902-46cb-8c59-928fcc5fbcba\",\"name\":\"SharePoint_Cum_Packaging\",\"description\":\"Excel files on SharePoint from ReportTool.\\r\\nOnly packaging reports.\",\"parentId\":null,\"order\":1}]"}],"entities":[{"$type":"LocalEntity","name":"CUM_PartNumberV_SF","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"CUM_PartNumberV_SF.csv"},"attributes":[{"name":"PARTNUMBERKEY","dataType":"int64"},{"name":"PART_DESCRIPTION","dataType":"string"},{"name":"SANDBOXKEY","dataType":"int64"},{"name":"ACTIVE","dataType":"boolean"},{"name":"CREATE_DATE","dataType":"dateTime"},{"name":"MODIFY_DATE","dataType":"dateTime"},{"name":"TYPE","dataType":"string"},{"name":"PART_NUMBER","dataType":"string"},{"name":"WIP_DISPLAY","dataType":"string"},{"name":"AGILE_AUTO_SYNC","dataType":"boolean"},{"name":"WORK_CELL","dataType":"string"},{"name":"PRODUCTION_TYPE","dataType":"string"},{"name":"FLOW_NAME","dataType":"string"},{"name":"ORACLE_GENERIC_PN","dataType":"boolean"},{"name":"INVORG_CODE","dataType":"string"},{"name":"SANDBOX","dataType":"string"},{"name":"ITEM_ORG_KEY_CODE","dataType":"string"},{"name":"ITEM_SANDBOX_KEY_ID","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T09:03:05.3658102+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/bed535e9-b01d-4c67-a526-30fce69524aa/CUM_PartNumberV_SF.csv?snapshot=2022-06-13T09%3A03%3A05.3043904Z"}]},{"$type":"LocalEntity","name":"CUM_Sandboxes_SF","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"CUM_Sandboxes_SF.csv"},"attributes":[{"name":"SANDBOXKEY","dataType":"int64"},{"name":"BUSINESS_UNIT","dataType":"string"},{"name":"MAJOR_PRODUCT_FAMILY","dataType":"string"},{"name":"SANDBOX","dataType":"string"},{"name":"RESTRICTED","dataType":"boolean"},{"name":"ITAR","dataType":"boolean"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T09:03:04.2113392+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/bed535e9-b01d-4c67-a526-30fce69524aa/CUM_Sandboxes_SF.csv?snapshot=2022-06-13T09%3A03%3A04.1600550Z"}]},{"$type":"LocalEntity","name":"CUM_TAGs_SF","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"CUM_TAGs_SF.csv"},"attributes":[{"name":"SANDBOXKEY","dataType":"int64"},{"name":"PARTNUMBERKEY","dataType":"int64"},{"name":"PART_NUMBER","dataType":"string"},{"name":"TAG","dataType":"string"},{"name":"ITEM_ORG_KEY_CODE","dataType":"string"},{"name":"ITEM_SANDBOX_KEY_ID","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T09:03:05.3189432+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/bed535e9-b01d-4c67-a526-30fce69524aa/CUM_TAGs_SF.csv?snapshot=2022-06-13T09%3A03%3A05.2404274Z"}]},{"$type":"LocalEntity","name":"CUM_USERS_SF","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"CUM_USERS_SF.csv"},"attributes":[{"name":"USERKEY","dataType":"int64"},{"name":"USER_STATUS","dataType":"string"},{"name":"FIRST_NAME","dataType":"string"},{"name":"LAST_NAME","dataType":"string"},{"name":"EMAIL","dataType":"string"},{"name":"GUID","dataType":"string"},{"name":"SANDBOXKEY","dataType":"int64"},{"name":"SYS_ADMINISTRATOR","dataType":"boolean"},{"name":"ADMINISTRATOR","dataType":"boolean"},{"name":"BU_ADMINISTRATOR","dataType":"boolean"},{"name":"OPERATIONS","dataType":"boolean"},{"name":"ENGINEERING","dataType":"boolean"},{"name":"PLANNING","dataType":"boolean"},{"name":"PURCHASING","dataType":"boolean"},{"name":"SERVICE","dataType":"boolean"},{"name":"ENG_SUPPORT","dataType":"boolean"},{"name":"MFG_SUPPORT","dataType":"boolean"},{"name":"MANUFACTURING","dataType":"boolean"},{"name":"BASIC","dataType":"boolean"},{"name":"VIEW_DATA","dataType":"boolean"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T09:03:05.490812+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/bed535e9-b01d-4c67-a526-30fce69524aa/CUM_USERS_SF.csv?snapshot=2022-06-13T09%3A03%3A05.4583014Z"}]},{"$type":"LocalEntity","name":"Cumulus_Packaging","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Cumulus_Packaging.csv"},"attributes":[{"name":"WORK_ORDER","dataType":"int64"},{"name":"WO_STATUS","dataType":"string"},{"name":"TYPE","dataType":"string"},{"name":"SERIAL_NUMBER","dataType":"string"},{"name":"PART_NUMBER","dataType":"string"},{"name":"DESCRIPTION","dataType":"string"},{"name":"FLOW","dataType":"string"},{"name":"PROCESS","dataType":"string"},{"name":"PROCESS_DESCRIPTION","dataType":"string"},{"name":"PROCESS_STEP_INDEX","dataType":"int64"},{"name":"DATE","dataType":"dateTime"},{"name":"Sandbox","dataType":"string"},{"name":"Inspector","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T09:03:14.0279432+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/bed535e9-b01d-4c67-a526-30fce69524aa/Cumulus_Packaging.csv?snapshot=2022-06-13T09%3A03%3A13.9863518Z"}]},{"$type":"LocalEntity","name":"CUM_Deviations_SF","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"CUM_Deviations_SF.csv"},"attributes":[{"name":"DEVIATIONKEY","dataType":"int64"},{"name":"SANDBOXKEY","dataType":"int64"},{"name":"CREATE_DATE","dataType":"dateTime"},{"name":"UPDATE_DATE","dataType":"dateTime"},{"name":"ACTIVE","dataType":"boolean"},{"name":"ORG","dataType":"string"},{"name":"SITE","dataType":"string"},{"name":"AGILE_DEVIATION","dataType":"string"},{"name":"TITLE","dataType":"string"},{"name":"REASON","dataType":"string"},{"name":"DESCRIPTION","dataType":"string"},{"name":"DEVIATION","dataType":"string"},{"name":"TYPE","dataType":"string"},{"name":"MODE","dataType":"string"},{"name":"WORKCELL","dataType":"string"},{"name":"START_DATE","dataType":"dateTime"},{"name":"END_DATE","dataType":"dateTime"},{"name":"VALIDATION","dataType":"boolean"},{"name":"VALIDATION_PERMISSION","dataType":"string"},{"name":"APPLY_PARENT","dataType":"boolean"},{"name":"SHIP_REST","dataType":"boolean"},{"name":"SHIP_REST_DESC","dataType":"string"},{"name":"PROCESS","dataType":"string"},{"name":"PROCESS_DESCRIPTION","dataType":"string"},{"name":"SUPPLIER","dataType":"string"},{"name":"DEVIATION_CODE","dataType":"string"},{"name":"DEFECT_CODE","dataType":"string"},{"name":"REJECT_CODE","dataType":"string"},{"name":"NOTES","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T09:03:05.2876993+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/bed535e9-b01d-4c67-a526-30fce69524aa/CUM_Deviations_SF.csv?snapshot=2022-06-13T09%3A03%3A05.2394281Z"}]}]}