{"name":"Flow_SQL_NCR-QC-Database","description":"Flow to load data from the SQL server (GTGSQL2) for NCR- and QC-Database.","version":"1.0","culture":"en-US","modifiedTime":"2022-03-29T11:07:32.0038599+00:00","pbi:mashup":{"fastCombine":true,"allowNativeQueries":false,"queriesMetadata":{"NCRdat":{"queryId":"5401d044-30db-438b-aa09-e5f92a505b78","queryName":"NCRdat","queryGroupId":"4d9b350f-b195-4e52-92f9-8d58c6009dba","loadEnabled":true},"NCRstdLieferant":{"queryId":"cc81c76c-e90a-429e-a712-8f1e6d1c473d","queryName":"NCRstdLieferant","queryGroupId":"4d9b350f-b195-4e52-92f9-8d58c6009dba","loadEnabled":true},"Users NCRs":{"queryId":"3e5d38e1-5836-47b2-824f-2da520c395e8","queryName":"Users NCRs","queryGroupId":"4d9b350f-b195-4e52-92f9-8d58c6009dba"},"stdNCRStatus":{"queryId":"ef7949ee-5a9b-49a7-89a7-e3641c2db6f9","queryName":"stdNCRStatus","queryGroupId":"4d9b350f-b195-4e52-92f9-8d58c6009dba"},"QCdatIssue":{"queryId":"39579c5d-32a4-40f3-955c-52cc16d06578","queryName":"QCdatIssue","queryGroupId":"6cd8d050-bb69-4c0c-8b9a-47a32183c039","loadEnabled":true},"QCdatAction":{"queryId":"c34f65e3-6fb4-4318-b5dc-bda2bc72cdc6","queryName":"QCdatAction","queryGroupId":"6cd8d050-bb69-4c0c-8b9a-47a32183c039","loadEnabled":true},"QCdatActionTask":{"queryId":"c16d44ad-3f3f-4a4c-a76e-123cebdcdf22","queryName":"QCdatActionTask","queryGroupId":"6cd8d050-bb69-4c0c-8b9a-47a32183c039","loadEnabled":true},"Users QCs":{"queryId":"dead5a3d-00e5-47b5-b875-2f00a3154ab0","queryName":"Users QCs","queryGroupId":"6cd8d050-bb69-4c0c-8b9a-47a32183c039"},"stdBaseFactor":{"queryId":"4ed9cdbb-08a5-4a45-90b8-03d4ddba496e","queryName":"stdBaseFactor","queryGroupId":"6cd8d050-bb69-4c0c-8b9a-47a32183c039"},"stdEffect":{"queryId":"85821f00-225f-4c59-ae15-707c63a288a7","queryName":"stdEffect","queryGroupId":"6cd8d050-bb69-4c0c-8b9a-47a32183c039"},"stdIssueStatus":{"queryId":"57659dec-b52a-48d9-a4c0-9bd9166a7de0","queryName":"stdIssueStatus","queryGroupId":"6cd8d050-bb69-4c0c-8b9a-47a32183c039"},"stdQualityCircle":{"queryId":"bacf1af9-bf85-4b24-9a82-2d89f0d24e1f","queryName":"stdQualityCircle","queryGroupId":"6cd8d050-bb69-4c0c-8b9a-47a32183c039"},"stdActionClass":{"queryId":"af40032e-7176-4dbb-b4d8-d3fa15fc55c0","queryName":"stdActionClass","queryGroupId":"6cd8d050-bb69-4c0c-8b9a-47a32183c039"},"stdDropDown":{"queryId":"dee6af20-200c-4849-959c-222cfd0aa3e6","queryName":"stdDropDown","queryGroupId":"6cd8d050-bb69-4c0c-8b9a-47a32183c039"},"Users_NCR-QC":{"queryId":"975cc8a7-d0dd-4733-a2ec-bfdf6a362231","queryName":"Users_NCR-QC","loadEnabled":true}},"document":"section Section1;\r\nshared NCRdat = let\r\n  Source = Sql.Database(\"Degoesql_GTG_QM_NCR-DB\", \"GTG_QM_NCR-DB\"),\r\n  #\"Navigation 1\" = Source{[Schema = \"dbo\", Item = \"datNCR\"]}[Data],\r\n  #\"Expanded Users\" = Table.ExpandRecordColumn(#\"Navigation 1\", \"Users\", {\"DisplayName\"}, {\"Bearbeiter\"}),\r\n  #\"Expanded stdLieferant\" = Table.ExpandRecordColumn(#\"Expanded Users\", \"stdLieferant\", {\"LieferantNummer\", \"LieferantName\"}, {\"LieferantNummer.1\", \"LieferantName\"}),\r\n  #\"Expanded stdNCRStatus\" = Table.ExpandRecordColumn(#\"Expanded stdLieferant\", \"stdNCRStatus\", {\"NCRStatusID\", \"StatusBezeichnung\", \"Kommentar\", \"NCRAbgeschlossen\"}, {\"NCRStatusID.1\", \"StatusBezeichnung\", \"Kommentar\", \"NCRAbgeschlossen\"}),\r\n  #\"Choose columns\" = Table.SelectColumns(#\"Expanded stdNCRStatus\", {\"NCRNummer\", \"NCRNummerUser\", \"ErstelltDatum\", \"ErstelltUser\", \"UpdatedDatum\", \"UpdatedUser\", \"FSRNummer\", \"CFR\", \"LieferantNummer\", \"LieferantID\", \"Kunde\", \"ArtikelNummer\", \"ArtikelID\", \"ArtikelSN\", \"ArtikelNummer2\", \"ArtikelSN2\", \"ArtikelNummer3\", \"ArtikelSN3\", \"Anzahl\", \"PulszahlAlter\", \"Fehlercharakterisierung\", \"Fehlergruppierung\", \"DOA\", \"Verantwortlicher\", \"SelbstBehoben\", \"Demontage\", \"Systemtyp\", \"SNSystem\", \"Fehlerbeschreibung\", \"Sofortmassnahme\", \"FehlerursacheAnalyse\", \"VorbeugendeMassnahme\", \"Verantwortlich\", \"VerantwortlichLieferant\", \"VerantwortlichAbteilung\", \"Haeufungen\", \"SPCsBeruecksichtigen\", \"KostenBearbeitung\", \"Korrekturbetrag\", \"KostenPersonal\", \"Bearbeitungszeit\", \"ErstellerAbteilung\", \"JobNrWIP\", \"Sperrlager1DatumIn\", \"Sperrlager1DatumOut\", \"Sperrlager1Ort\", \"Sperrlager1JobNummer\", \"Sperrlager2DatumIn\", \"Sperrlager2DatumOut\", \"Sperrlager2Ort\", \"Sperrlager2JobNummer\", \"Sperrlager3DatumIn\", \"Sperrlager3DatumOut\", \"Sperrlager3Ort\", \"Sperrlager3JobNummer\", \"Abschlussbewertung\", \"AnnahmeNCR\", \"AnzahlAkzeptiertEingabe\", \"AnzahlAbgelehnt\", \"AbgelehntVerantwortlicher\", \"Sperrlager4DatumIn\", \"Sperrlager4DatumOut\", \"Sperrlager4Ort\", \"Sperrlager4JobNummer\", \"Sperrlager5DatumIn\", \"Sperrlager5DatumOut\", \"Sperrlager5Ort\", \"Sperrlager5JobNummer\", \"ErstelltLogin\", \"Sperrlager1JobGeplant\", \"Sperrlager1Verantwortlich\", \"Sperrlager1Abgeschlossen\", \"Sperrlager2JobGeplant\", \"Sperrlager2Verantwortlich\", \"Sperrlager2Abgeschlossen\", \"Sperrlager3JobGeplant\", \"Sperrlager3Verantwortlich\", \"Sperrlager3Abgeschlossen\", \"Sperrlager4JobGeplant\", \"Sperrlager4Verantwortlich\", \"Sperrlager4Abgeschlossen\", \"Sperrlager5JobGeplant\", \"Sperrlager5Verantwortlich\", \"Sperrlager5Abgeschlossen\", \"FehlercharakterisierungSpeziell\", \"VerantwortlicherAbteilung\", \"AbgelehntVerantwortlicherAbteilung\", \"ErstellerAbteilungSub\", \"VerantwortlichAbteilungSub\", \"CFRAbgeschlossen\", \"NCRStatusID\", \"BearbeiterID\", \"DatumGeloescht\", \"FehlerbeschreibungLieferant\", \"RMANummer\", \"RWNummer\", \"ZusatzinfoWorkflow\", \"AlterBaujahr\", \"RMALieferant\", \"Korrekturliste\", \"Anhaenge\", \"ArtikelEinkaeuferOW\", \"MangelAngelegtAm\", \"AbgeschlossenDatum\", \"Bearbeiter\", \"stdArtikel\", \"LieferantNummer.1\", \"LieferantName\", \"NCRStatusID.1\", \"StatusBezeichnung\", \"Kommentar\", \"NCRAbgeschlossen\"}),\r\n  #\"Expanded stdArtikel\" = Table.ExpandRecordColumn(#\"Choose columns\", \"stdArtikel\", {\"Bezeichnung\", \"Gruppe\", \"Einkaeufer\", \"FrozenSPC\", \"StatusAgile\", \"Revision\", \"Inaktiv\"}, {\"stdArtikel.Bezeichnung\", \"stdArtikel.Gruppe\", \"stdArtikel.Einkaeufer\", \"stdArtikel.FrozenSPC\", \"stdArtikel.StatusAgile\", \"stdArtikel.Revision\", \"stdArtikel.Inaktiv\"}),\r\n  #\"Merged queries\" = Table.NestedJoin(#\"Expanded stdArtikel\", {\"NCRStatusID.1\"}, stdNCRStatus, {\"NCRStatusID\"}, \"stdNCRStatus\", JoinKind.LeftOuter),\r\n  #\"Expanded stdNCRStatus 1\" = Table.ExpandTableColumn(#\"Merged queries\", \"stdNCRStatus\", {\"StatusBezeichnung\", \"Kommentar\"}, {\"stdNCRStatus.StatusBezeichnung\", \"stdNCRStatus.Kommentar\"}),\r\n  #\"Choose columns 1\" = Table.SelectColumns(#\"Expanded stdNCRStatus 1\", {\"NCRNummer\", \"NCRNummerUser\", \"ErstelltDatum\", \"ErstelltUser\", \"UpdatedDatum\", \"UpdatedUser\", \"FSRNummer\", \"CFR\", \"LieferantNummer\", \"Kunde\", \"ArtikelNummer\", \"ArtikelSN\", \"ArtikelNummer2\", \"ArtikelSN2\", \"ArtikelNummer3\", \"ArtikelSN3\", \"Anzahl\", \"PulszahlAlter\", \"Fehlercharakterisierung\", \"Fehlergruppierung\", \"DOA\", \"Verantwortlicher\", \"SelbstBehoben\", \"Demontage\", \"Systemtyp\", \"SNSystem\", \"Fehlerbeschreibung\", \"Sofortmassnahme\", \"FehlerursacheAnalyse\", \"VorbeugendeMassnahme\", \"Verantwortlich\", \"VerantwortlichLieferant\", \"VerantwortlichAbteilung\", \"Haeufungen\", \"SPCsBeruecksichtigen\", \"KostenBearbeitung\", \"Korrekturbetrag\", \"KostenPersonal\", \"Bearbeitungszeit\", \"ErstellerAbteilung\", \"JobNrWIP\", \"Sperrlager1DatumIn\", \"Sperrlager1DatumOut\", \"Sperrlager1Ort\", \"Sperrlager1JobNummer\", \"Sperrlager2DatumIn\", \"Sperrlager2DatumOut\", \"Sperrlager2Ort\", \"Sperrlager2JobNummer\", \"Sperrlager3DatumIn\", \"Sperrlager3DatumOut\", \"Sperrlager3Ort\", \"Sperrlager3JobNummer\", \"Abschlussbewertung\", \"AnnahmeNCR\", \"AnzahlAkzeptiertEingabe\", \"AnzahlAbgelehnt\", \"AbgelehntVerantwortlicher\", \"Sperrlager4DatumIn\", \"Sperrlager4DatumOut\", \"Sperrlager4Ort\", \"Sperrlager4JobNummer\", \"Sperrlager5DatumIn\", \"Sperrlager5DatumOut\", \"Sperrlager5Ort\", \"Sperrlager5JobNummer\", \"ErstelltLogin\", \"Sperrlager1JobGeplant\", \"Sperrlager1Verantwortlich\", \"Sperrlager1Abgeschlossen\", \"Sperrlager2JobGeplant\", \"Sperrlager2Verantwortlich\", \"Sperrlager2Abgeschlossen\", \"Sperrlager3JobGeplant\", \"Sperrlager3Verantwortlich\", \"Sperrlager3Abgeschlossen\", \"Sperrlager4JobGeplant\", \"Sperrlager4Verantwortlich\", \"Sperrlager4Abgeschlossen\", \"Sperrlager5JobGeplant\", \"Sperrlager5Verantwortlich\", \"Sperrlager5Abgeschlossen\", \"FehlercharakterisierungSpeziell\", \"VerantwortlicherAbteilung\", \"AbgelehntVerantwortlicherAbteilung\", \"ErstellerAbteilungSub\", \"VerantwortlichAbteilungSub\", \"CFRAbgeschlossen\", \"DatumGeloescht\", \"FehlerbeschreibungLieferant\", \"RMANummer\", \"RWNummer\", \"ZusatzinfoWorkflow\", \"AlterBaujahr\", \"RMALieferant\", \"Korrekturliste\", \"ArtikelEinkaeuferOW\", \"MangelAngelegtAm\", \"AbgeschlossenDatum\", \"Bearbeiter\", \"stdArtikel.Bezeichnung\", \"stdArtikel.Gruppe\", \"stdArtikel.Einkaeufer\", \"stdArtikel.FrozenSPC\", \"stdArtikel.StatusAgile\", \"stdArtikel.Revision\", \"stdArtikel.Inaktiv\", \"LieferantNummer.1\", \"LieferantName\", \"StatusBezeichnung\", \"Kommentar\", \"NCRAbgeschlossen\"})\r\nin\r\n  #\"Choose columns 1\";\r\nshared NCRstdLieferant = let\r\n  Source = Sql.Database(\"Degoesql_GTG_QM_NCR-DB\", \"GTG_QM_NCR-DB\"),\r\n  #\"Navigation 1\" = Source{[Schema = \"dbo\", Item = \"stdLieferant\"]}[Data],\r\n  #\"Choose columns\" = Table.SelectColumns(#\"Navigation 1\", {\"LieferantID\", \"LieferantNummer\", \"LieferantName\", \"Inaktiv\"})\r\nin\r\n  #\"Choose columns\";\r\nshared #\"Users NCRs\" = let\r\n  Source = Sql.Database(\"Degoesql_GTG_QM_NCR-DB\", \"GTG_QM_NCR-DB\"),\r\n  #\"Navigation 1\" = Source{[Schema = \"dbo\", Item = \"Users\"]}[Data],\r\n  #\"Choose columns\" = Table.SelectColumns(#\"Navigation 1\", {\"UserId\", \"Username\", \"DisplayName\", \"Email\"})\r\nin\r\n  #\"Choose columns\";\r\nshared stdNCRStatus = let\r\n  Source = Sql.Database(\"Degoesql_GTG_QM_NCR-DB\", \"GTG_QM_NCR-DB\"),\r\n  #\"Navigation 1\" = Source{[Schema = \"dbo\", Item = \"stdNCRStatus\"]}[Data],\r\n  #\"Choose columns\" = Table.SelectColumns(#\"Navigation 1\", {\"NCRStatusID\", \"StatusBezeichnung\", \"SortOrder\", \"Kommentar\", \"NCRAbgeschlossen\"})\r\nin\r\n  #\"Choose columns\";\r\nshared QCdatIssue = let\r\n  Source = Sql.Databases(\"Degoesql_GTG_Ops_TQC-DB\"),\r\n  #\"GTG_Ops_TQC-DB\" = Source{[Name = \"GTG_Ops_TQC-DB\"]}[Data],\r\n  dbo_datIssue = #\"GTG_Ops_TQC-DB\"{[Schema = \"dbo\", Item = \"datIssue\"]}[Data],\r\n  #\"Expanded Users(CreatorID)\" = Table.ExpandRecordColumn(dbo_datIssue, \"Users(CreatorID)\", {\"DisplayName\"}, {\"Creator\"}),\r\n  #\"Expanded Users(OwnerID)\" = Table.ExpandRecordColumn(#\"Expanded Users(CreatorID)\", \"Users(OwnerID)\", {\"DisplayName\"}, {\"Owner\"}),\r\n  #\"Expanded stdBaseFactor\" = Table.ExpandRecordColumn(#\"Expanded Users(OwnerID)\", \"stdBaseFactor\", {\"BaseFactor\"}, {\"BaseFactor\"}),\r\n  #\"Expanded stdEffect\" = Table.ExpandRecordColumn(#\"Expanded stdBaseFactor\", \"stdEffect\", {\"Effect\"}, {\"Effect\"}),\r\n  #\"Expanded stdIssueStatus\" = Table.ExpandRecordColumn(#\"Expanded stdEffect\", \"stdIssueStatus\", {\"IssueStatus\"}, {\"IssueStatus\"}),\r\n  #\"Expanded stdQualityCircle\" = Table.ExpandRecordColumn(#\"Expanded stdIssueStatus\", \"stdQualityCircle\", {\"QualityCircle\", \"Users\"}, {\"QualityCircle\", \"Users\"}),\r\n  #\"Expanded Users\" = Table.ExpandRecordColumn(#\"Expanded stdQualityCircle\", \"Users\", {\"DisplayName\"}, {\"DisplayName\"}),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Expanded Users\", {{\"DisplayName\", \"ResponsibleQC\"}}),\r\n  #\"Choose columns\" = Table.SelectColumns(#\"Renamed columns\", {\"IssueID\", \"LastUpdate\", \"LastUpdateUser\", \"DateCreated\", \"TitleShort\", \"IssueDescription\", \"ProductType\", \"PN\", \"NCRNo\", \"Comment\", \"IssueCompleted\", \"TimeToSolve\", \"TaskForce\", \"BaseFactorLevel\", \"EffectLevel\", \"CommentChangePrio\", \"AenderungNummer\", \"TotalRisk\", \"Creator\", \"Owner\", \"BaseFactor\", \"Effect\", \"IssueStatus\", \"QualityCircle\", \"ResponsibleQC\"})\r\nin\r\n  #\"Choose columns\";\r\nshared QCdatAction = let\r\n  Source = Sql.Databases(\"Degoesql_GTG_Ops_TQC-DB\"),\r\n  #\"GTG_Ops_TQC-DB\" = Source{[Name = \"GTG_Ops_TQC-DB\"]}[Data],\r\n  dbo_datAction = #\"GTG_Ops_TQC-DB\"{[Schema = \"dbo\", Item = \"datAction\"]}[Data],\r\n  #\"Expanded Users\" = Table.ExpandRecordColumn(dbo_datAction, \"Users\", {\"DisplayName\"}, {\"CreatorName\"}),\r\n  #\"Expanded stdActionClass\" = Table.ExpandRecordColumn(#\"Expanded Users\", \"stdActionClass\", {\"ActionClass\", \"ActionClassDE\", \"ActionClassLevel\"}, {\"ActionClass\", \"ActionClassDE\", \"ActionClassLevel\"}),\r\n  #\"Choose columns\" = Table.SelectColumns(#\"Expanded stdActionClass\", {\"ActionID\", \"IssueID\", \"Action\", \"DateCreated\", \"DateClosed\", \"DueDate\", \"LastUpdate\", \"RootCauseAnalysis\", \"Reason\", \"ActionNo\", \"ActionPriority\", \"CreatorName\", \"ActionClass\", \"ActionClassDE\", \"ActionClassLevel\"})\r\nin\r\n  #\"Choose columns\";\r\nshared QCdatActionTask = let\r\n  Source = Sql.Databases(\"Degoesql_GTG_Ops_TQC-DB\"),\r\n  #\"GTG_Ops_TQC-DB\" = Source{[Name = \"GTG_Ops_TQC-DB\"]}[Data],\r\n  dbo_datActionTask = #\"GTG_Ops_TQC-DB\"{[Schema = \"dbo\", Item = \"datActionTask\"]}[Data],\r\n  #\"Expanded Users\" = Table.ExpandRecordColumn(dbo_datActionTask, \"Users\", {\"DisplayName\"}, {\"Responsible\"}),\r\n  #\"Expanded datAction\" = Table.ExpandRecordColumn(#\"Expanded Users\", \"datAction\", {\"IssueID\"}, {\"datAction.IssueID\"}),\r\n  #\"Choose columns\" = Table.SelectColumns(#\"Expanded datAction\", {\"ActionTaskID\", \"ActionID\", \"DueDate\", \"Task\", \"Result\", \"TaskClosed\", \"TaskNo\", \"Responsible\", \"datAction.IssueID\"})\r\nin\r\n  #\"Choose columns\";\r\nshared #\"Users QCs\" = let\r\n  Source = Sql.Databases(\"Degoesql_GTG_Ops_TQC-DB\"),\r\n  #\"GTG_Ops_TQC-DB\" = Source{[Name = \"GTG_Ops_TQC-DB\"]}[Data],\r\n  dbo_Users = #\"GTG_Ops_TQC-DB\"{[Schema = \"dbo\", Item = \"Users\"]}[Data],\r\n  #\"Choose columns\" = Table.SelectColumns(dbo_Users, {\"UserId\", \"Username\"})\r\nin\r\n  #\"Choose columns\";\r\nshared stdBaseFactor = let\r\n  Source = Sql.Databases(\"Degoesql_GTG_Ops_TQC-DB\"),\r\n  #\"GTG_Ops_TQC-DB\" = Source{[Name = \"GTG_Ops_TQC-DB\"]}[Data],\r\n  dbo_stdBaseFactor = #\"GTG_Ops_TQC-DB\"{[Schema = \"dbo\", Item = \"stdBaseFactor\"]}[Data]\r\nin\r\n  dbo_stdBaseFactor;\r\nshared stdEffect = let\r\n  Source = Sql.Databases(\"Degoesql_GTG_Ops_TQC-DB\"),\r\n  #\"GTG_Ops_TQC-DB\" = Source{[Name = \"GTG_Ops_TQC-DB\"]}[Data],\r\n  dbo_stdEffect = #\"GTG_Ops_TQC-DB\"{[Schema = \"dbo\", Item = \"stdEffect\"]}[Data]\r\nin\r\n  dbo_stdEffect;\r\nshared stdIssueStatus = let\r\n  Source = Sql.Databases(\"Degoesql_GTG_Ops_TQC-DB\"),\r\n  #\"GTG_Ops_TQC-DB\" = Source{[Name = \"GTG_Ops_TQC-DB\"]}[Data],\r\n  dbo_stdIssueStatus = #\"GTG_Ops_TQC-DB\"{[Schema = \"dbo\", Item = \"stdIssueStatus\"]}[Data]\r\nin\r\n  dbo_stdIssueStatus;\r\nshared stdQualityCircle = let\r\n  Source = Sql.Databases(\"Degoesql_GTG_Ops_TQC-DB\"),\r\n  #\"GTG_Ops_TQC-DB\" = Source{[Name = \"GTG_Ops_TQC-DB\"]}[Data],\r\n  dbo_stdQualityCircle = #\"GTG_Ops_TQC-DB\"{[Schema = \"dbo\", Item = \"stdQualityCircle\"]}[Data],\r\n  #\"Expanded Users\" = Table.ExpandRecordColumn(dbo_stdQualityCircle, \"Users\", {\"DisplayName\"}, {\"DisplayName\"}),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Expanded Users\", {{\"DisplayName\", \"Responsible\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared stdActionClass = let\r\n  Source = Sql.Databases(\"Degoesql_GTG_Ops_TQC-DB\"),\r\n  #\"GTG_Ops_TQC-DB\" = Source{[Name = \"GTG_Ops_TQC-DB\"]}[Data],\r\n  dbo_stdActionClass = #\"GTG_Ops_TQC-DB\"{[Schema = \"dbo\", Item = \"stdActionClass\"]}[Data]\r\nin\r\n  dbo_stdActionClass;\r\nshared stdDropDown = let\r\n  Source = Sql.Databases(\"Degoesql_GTG_Ops_TQC-DB\"),\r\n  #\"GTG_Ops_TQC-DB\" = Source{[Name = \"GTG_Ops_TQC-DB\"]}[Data],\r\n  dbo_stdDropDown = #\"GTG_Ops_TQC-DB\"{[Schema = \"dbo\", Item = \"stdDropDown\"]}[Data]\r\nin\r\n  dbo_stdDropDown;\r\nshared #\"Users_NCR-QC\" = let\r\n  Source = Table.NestedJoin(#\"Users QCs\", {\"Username\"}, #\"Users NCRs\", {\"Username\"}, \"Users NCRs\", JoinKind.LeftOuter),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"UserId\", \"UserId_QC\"}}),\r\n  #\"Expanded Users NCRs\" = Table.ExpandTableColumn(#\"Renamed columns\", \"Users NCRs\", {\"UserId\", \"DisplayName\", \"Email\"}, {\"Users NCRs.UserId\", \"Users NCRs.DisplayName\", \"Users NCRs.Email\"})\r\nin\r\n  #\"Expanded Users NCRs\";\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[{\"id\":\"4d9b350f-b195-4e52-92f9-8d58c6009dba\",\"name\":\"NCR DB\",\"description\":\"NCR Database (QM)\",\"parentId\":null,\"order\":0},{\"id\":\"6cd8d050-bb69-4c0c-8b9a-47a32183c039\",\"name\":\"QC DB\",\"description\":\"Quality Circles Database (QM)\",\"parentId\":null,\"order\":1}]"}],"entities":[{"$type":"LocalEntity","name":"NCRdat","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"NCRdat.csv"},"attributes":[{"name":"NCRNummer","dataType":"string"},{"name":"NCRNummerUser","dataType":"string"},{"name":"ErstelltDatum","dataType":"dateTime"},{"name":"ErstelltUser","dataType":"string"},{"name":"UpdatedDatum","dataType":"dateTime"},{"name":"UpdatedUser","dataType":"string"},{"name":"FSRNummer","dataType":"string"},{"name":"CFR","dataType":"string"},{"name":"LieferantNummer","dataType":"string"},{"name":"Kunde","dataType":"string"},{"name":"ArtikelNummer","dataType":"string"},{"name":"ArtikelSN","dataType":"string"},{"name":"ArtikelNummer2","dataType":"string"},{"name":"ArtikelSN2","dataType":"string"},{"name":"ArtikelNummer3","dataType":"string"},{"name":"ArtikelSN3","dataType":"string"},{"name":"Anzahl","dataType":"int64"},{"name":"PulszahlAlter","dataType":"string"},{"name":"Fehlercharakterisierung","dataType":"string"},{"name":"Fehlergruppierung","dataType":"string"},{"name":"DOA","dataType":"boolean"},{"name":"Verantwortlicher","dataType":"string"},{"name":"SelbstBehoben","dataType":"boolean"},{"name":"Demontage","dataType":"boolean"},{"name":"Systemtyp","dataType":"string"},{"name":"SNSystem","dataType":"string"},{"name":"Fehlerbeschreibung","dataType":"string"},{"name":"Sofortmassnahme","dataType":"string"},{"name":"FehlerursacheAnalyse","dataType":"string"},{"name":"VorbeugendeMassnahme","dataType":"string"},{"name":"Verantwortlich","dataType":"int64"},{"name":"VerantwortlichLieferant","dataType":"string"},{"name":"VerantwortlichAbteilung","dataType":"string"},{"name":"Haeufungen","dataType":"string"},{"name":"SPCsBeruecksichtigen","dataType":"boolean"},{"name":"KostenBearbeitung","dataType":"double"},{"name":"Korrekturbetrag","dataType":"double"},{"name":"KostenPersonal","dataType":"double"},{"name":"Bearbeitungszeit","dataType":"int64"},{"name":"ErstellerAbteilung","dataType":"string"},{"name":"JobNrWIP","dataType":"string"},{"name":"Sperrlager1DatumIn","dataType":"dateTime"},{"name":"Sperrlager1DatumOut","dataType":"dateTime"},{"name":"Sperrlager1Ort","dataType":"string"},{"name":"Sperrlager1JobNummer","dataType":"string"},{"name":"Sperrlager2DatumIn","dataType":"dateTime"},{"name":"Sperrlager2DatumOut","dataType":"dateTime"},{"name":"Sperrlager2Ort","dataType":"string"},{"name":"Sperrlager2JobNummer","dataType":"string"},{"name":"Sperrlager3DatumIn","dataType":"dateTime"},{"name":"Sperrlager3DatumOut","dataType":"dateTime"},{"name":"Sperrlager3Ort","dataType":"string"},{"name":"Sperrlager3JobNummer","dataType":"string"},{"name":"Abschlussbewertung","dataType":"string"},{"name":"AnnahmeNCR","dataType":"string"},{"name":"AnzahlAkzeptiertEingabe","dataType":"int64"},{"name":"AnzahlAbgelehnt","dataType":"int64"},{"name":"AbgelehntVerantwortlicher","dataType":"string"},{"name":"Sperrlager4DatumIn","dataType":"dateTime"},{"name":"Sperrlager4DatumOut","dataType":"dateTime"},{"name":"Sperrlager4Ort","dataType":"string"},{"name":"Sperrlager4JobNummer","dataType":"string"},{"name":"Sperrlager5DatumIn","dataType":"dateTime"},{"name":"Sperrlager5DatumOut","dataType":"dateTime"},{"name":"Sperrlager5Ort","dataType":"string"},{"name":"Sperrlager5JobNummer","dataType":"string"},{"name":"ErstelltLogin","dataType":"string"},{"name":"Sperrlager1JobGeplant","dataType":"dateTime"},{"name":"Sperrlager1Verantwortlich","dataType":"string"},{"name":"Sperrlager1Abgeschlossen","dataType":"boolean"},{"name":"Sperrlager2JobGeplant","dataType":"dateTime"},{"name":"Sperrlager2Verantwortlich","dataType":"string"},{"name":"Sperrlager2Abgeschlossen","dataType":"boolean"},{"name":"Sperrlager3JobGeplant","dataType":"dateTime"},{"name":"Sperrlager3Verantwortlich","dataType":"string"},{"name":"Sperrlager3Abgeschlossen","dataType":"boolean"},{"name":"Sperrlager4JobGeplant","dataType":"dateTime"},{"name":"Sperrlager4Verantwortlich","dataType":"string"},{"name":"Sperrlager4Abgeschlossen","dataType":"boolean"},{"name":"Sperrlager5JobGeplant","dataType":"dateTime"},{"name":"Sperrlager5Verantwortlich","dataType":"string"},{"name":"Sperrlager5Abgeschlossen","dataType":"boolean"},{"name":"FehlercharakterisierungSpeziell","dataType":"string"},{"name":"VerantwortlicherAbteilung","dataType":"string"},{"name":"AbgelehntVerantwortlicherAbteilung","dataType":"string"},{"name":"ErstellerAbteilungSub","dataType":"string"},{"name":"VerantwortlichAbteilungSub","dataType":"string"},{"name":"CFRAbgeschlossen","dataType":"boolean"},{"name":"DatumGeloescht","dataType":"dateTime"},{"name":"FehlerbeschreibungLieferant","dataType":"string"},{"name":"RMANummer","dataType":"string"},{"name":"RWNummer","dataType":"string"},{"name":"ZusatzinfoWorkflow","dataType":"string"},{"name":"AlterBaujahr","dataType":"string"},{"name":"RMALieferant","dataType":"string"},{"name":"Korrekturliste","dataType":"boolean"},{"name":"ArtikelEinkaeuferOW","dataType":"string"},{"name":"MangelAngelegtAm","dataType":"dateTime"},{"name":"AbgeschlossenDatum","dataType":"dateTime"},{"name":"Bearbeiter","dataType":"string"},{"name":"stdArtikel.Bezeichnung","dataType":"string"},{"name":"stdArtikel.Gruppe","dataType":"string"},{"name":"stdArtikel.Einkaeufer","dataType":"string"},{"name":"stdArtikel.FrozenSPC","dataType":"double"},{"name":"stdArtikel.StatusAgile","dataType":"string"},{"name":"stdArtikel.Revision","dataType":"string"},{"name":"stdArtikel.Inaktiv","dataType":"boolean"},{"name":"LieferantNummer.1","dataType":"string"},{"name":"LieferantName","dataType":"string"},{"name":"StatusBezeichnung","dataType":"string"},{"name":"Kommentar","dataType":"string"},{"name":"NCRAbgeschlossen","dataType":"boolean"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T07:00:50.4958911+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/042be1fb-74d8-462d-a522-007fca113209/NCRdat.csv?snapshot=2022-06-13T07%3A00%3A49.8535047Z"}]},{"$type":"LocalEntity","name":"NCRstdLieferant","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"NCRstdLieferant.csv"},"attributes":[{"name":"LieferantID","dataType":"int64"},{"name":"LieferantNummer","dataType":"string"},{"name":"LieferantName","dataType":"string"},{"name":"Inaktiv","dataType":"boolean"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T07:00:23.7527688+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/042be1fb-74d8-462d-a522-007fca113209/NCRstdLieferant.csv?snapshot=2022-06-13T07%3A00%3A22.3830185Z"}]},{"$type":"LocalEntity","name":"QCdatIssue","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"QCdatIssue.csv"},"attributes":[{"name":"IssueID","dataType":"int64"},{"name":"LastUpdate","dataType":"dateTime"},{"name":"LastUpdateUser","dataType":"string"},{"name":"DateCreated","dataType":"dateTime"},{"name":"TitleShort","dataType":"string"},{"name":"IssueDescription","dataType":"string"},{"name":"ProductType","dataType":"string"},{"name":"PN","dataType":"string"},{"name":"NCRNo","dataType":"string"},{"name":"Comment","dataType":"string"},{"name":"IssueCompleted","dataType":"dateTime"},{"name":"TimeToSolve","dataType":"int64"},{"name":"TaskForce","dataType":"boolean"},{"name":"BaseFactorLevel","dataType":"int64"},{"name":"EffectLevel","dataType":"int64"},{"name":"CommentChangePrio","dataType":"string"},{"name":"AenderungNummer","dataType":"string"},{"name":"TotalRisk","dataType":"int64"},{"name":"Creator","dataType":"string"},{"name":"Owner","dataType":"string"},{"name":"BaseFactor","dataType":"string"},{"name":"Effect","dataType":"string"},{"name":"IssueStatus","dataType":"string"},{"name":"QualityCircle","dataType":"string"},{"name":"ResponsibleQC","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T07:00:24.8989474+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/042be1fb-74d8-462d-a522-007fca113209/QCdatIssue.csv?snapshot=2022-06-13T07%3A00%3A23.7632412Z"}]},{"$type":"LocalEntity","name":"QCdatAction","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"QCdatAction.csv"},"attributes":[{"name":"ActionID","dataType":"int64"},{"name":"IssueID","dataType":"int64"},{"name":"Action","dataType":"string"},{"name":"DateCreated","dataType":"dateTime"},{"name":"DateClosed","dataType":"dateTime"},{"name":"DueDate","dataType":"dateTime"},{"name":"LastUpdate","dataType":"dateTime"},{"name":"RootCauseAnalysis","dataType":"string"},{"name":"Reason","dataType":"string"},{"name":"ActionNo","dataType":"int64"},{"name":"ActionPriority","dataType":"int64"},{"name":"CreatorName","dataType":"string"},{"name":"ActionClass","dataType":"string"},{"name":"ActionClassDE","dataType":"string"},{"name":"ActionClassLevel","dataType":"int64"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T07:00:23.1698695+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/042be1fb-74d8-462d-a522-007fca113209/QCdatAction.csv?snapshot=2022-06-13T07%3A00%3A22.7468138Z"}]},{"$type":"LocalEntity","name":"QCdatActionTask","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"QCdatActionTask.csv"},"attributes":[{"name":"ActionTaskID","dataType":"int64"},{"name":"ActionID","dataType":"int64"},{"name":"DueDate","dataType":"dateTime"},{"name":"Task","dataType":"string"},{"name":"Result","dataType":"string"},{"name":"TaskClosed","dataType":"boolean"},{"name":"TaskNo","dataType":"int64"},{"name":"Responsible","dataType":"string"},{"name":"datAction.IssueID","dataType":"int64"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T07:00:25.5804953+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/042be1fb-74d8-462d-a522-007fca113209/QCdatActionTask.csv?snapshot=2022-06-13T07%3A00%3A25.1144769Z"}]},{"$type":"LocalEntity","name":"Users_NCR-QC","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Users_NCR-QC.csv"},"attributes":[{"name":"UserId_QC","dataType":"int64"},{"name":"Username","dataType":"string"},{"name":"Users NCRs.UserId","dataType":"int64"},{"name":"Users NCRs.DisplayName","dataType":"string"},{"name":"Users NCRs.Email","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T07:00:20.0787732+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/042be1fb-74d8-462d-a522-007fca113209/Users_NCR-QC.csv?snapshot=2022-06-13T07%3A00%3A20.0253504Z"}]}]}