{"name":"Flow_SQL_AenderungsDB","description":"Flow GTGSQL2 Server - DB \"GTGDevAenduerungsDB\" (Änderungsdatenbank / Change Requests Data Base).","version":"1.0","culture":"en-US","modifiedTime":"2021-10-30T10:58:03.9622627+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"datAenderung":{"queryId":"91481c26-4dce-4792-8f85-58adeb984738","queryName":"datAenderung","loadEnabled":true},"datAenderungCheckliste":{"queryId":"ddb586bb-ee2e-4cbf-9eab-5d4789950025","queryName":"datAenderungCheckliste"},"datAenderungProdukt":{"queryId":"956154bb-e25b-443d-bb10-c002f70cb76d","queryName":"datAenderungProdukt"},"datAenderungProperties":{"queryId":"2dbf4855-36e5-472f-a159-2b4d8743fb48","queryName":"datAenderungProperties"},"datAenderungRolle":{"queryId":"848d17fe-a7b9-42dc-9fa3-b51c69419630","queryName":"datAenderungRolle"},"datAenderungStatusHistory":{"queryId":"932daf02-ddd8-4986-b42e-cbc20a30a4cc","queryName":"datAenderungStatusHistory"},"stdAenderungStatus":{"queryId":"80897282-8587-44d9-a8d8-48ad071aa8c7","queryName":"stdAenderungStatus"},"stdAenderungTyp":{"queryId":"610ff3c0-9b62-402c-9692-56e983a11620","queryName":"stdAenderungTyp"},"stdFilter":{"queryId":"359b416b-9360-47f0-99b8-431257831271","queryName":"stdFilter"},"stdMitarbeiter":{"queryId":"f4ce9dc6-149a-47c4-973f-d380470df4ec","queryName":"stdMitarbeiter"}},"document":"section Section1;\r\nshared datAenderung = let\r\n  Source = Sql.Databases(\"Degoesql_GTGDevAenderungsDB\"),\r\n  #\"Navigation 1\" = Source{[Name = \"GTGDevAenderungsDB\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Schema = \"dbo\", Item = \"datAenderung\"]}[Data],\r\n  #\"Choose columns\" = Table.SelectColumns(#\"Navigation 2\", {\"AenderungID\", \"LastUpdate\", \"AenderungTypID\", \"AenderungNummer\", \"DatumAntragstellung\", \"Kurztitel\", \"AenderungStatusID\", \"PrioSicherheitsrelevant\", \"PrioErnst\", \"PrioDringlichkeit\", \"PrioVerlauf\", \"AntragFehlervermeidung\", \"AntragVereinfachung\", \"AntragKostenreduktion\", \"AntragKostenProGeraet\", \"AntragKundenwunsch\", \"AntragFunktionsverbesserung\", \"AntragSonstiges\", \"AntragMotivation\", \"AntragBeschreibung\", \"AntragVorNachteile\", \"AntragKompatibel\", \"AntragPflichtenheftAbsprachen\", \"FilterID\", \"datAenderungProdukt\", \"stdAenderungStatus\", \"stdAenderungTyp\", \"stdMitarbeiter(AntragstellerID)\", \"stdMitarbeiter(BearbeiterID)\"}),\r\n  #\"Expanded stdMitarbeiter(BearbeiterID)\" = Table.ExpandRecordColumn(#\"Choose columns\", \"stdMitarbeiter(BearbeiterID)\", {\"WindowsLogin\", \"Inaktiv\"}, {\"stdMitarbeiter(BearbeiterID).WindowsLogin\", \"stdMitarbeiter(BearbeiterID).Inaktiv\"}),\r\n  #\"Expanded stdMitarbeiter(AntragstellerID)\" = Table.ExpandRecordColumn(#\"Expanded stdMitarbeiter(BearbeiterID)\", \"stdMitarbeiter(AntragstellerID)\", {\"WindowsLogin\"}, {\"stdMitarbeiter(AntragstellerID).WindowsLogin\"}),\r\n  #\"Expanded stdAenderungTyp\" = Table.ExpandRecordColumn(#\"Expanded stdMitarbeiter(AntragstellerID)\", \"stdAenderungTyp\", {\"AenderungTyp\"}, {\"stdAenderungTyp.AenderungTyp\"}),\r\n  #\"Expanded stdAenderungStatus\" = Table.ExpandRecordColumn(#\"Expanded stdAenderungTyp\", \"stdAenderungStatus\", {\"StatusBezeichnung\", \"Aktuell\", \"AntragBearbeiten\", \"AenderungBearbeiten\", \"AntragLoeschen\", \"Kommentar\"}, {\"stdAenderungStatus.StatusBezeichnung\", \"stdAenderungStatus.Aktuell\", \"stdAenderungStatus.AntragBearbeiten\", \"stdAenderungStatus.AenderungBearbeiten\", \"stdAenderungStatus.AntragLoeschen\", \"stdAenderungStatus.Kommentar\"}),\r\n  #\"Expanded datAenderungProdukt\" = Table.ExpandTableColumn(#\"Expanded stdAenderungStatus\", \"datAenderungProdukt\", {\"Ausgewaehlt\", \"Bemerkung\"}, {\"datAenderungProdukt.Ausgewaehlt\", \"datAenderungProdukt.Bemerkung\"})\r\nin\r\n  #\"Expanded datAenderungProdukt\";\r\nshared datAenderungCheckliste = let\r\n  Source = Sql.Databases(\"Degoesql_GTGDevAenderungsDB\"),\r\n  #\"Navigation 1\" = Source{[Name = \"GTGDevAenderungsDB\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Schema = \"dbo\", Item = \"datAenderungCheckliste\"]}[Data]\r\nin\r\n  #\"Navigation 2\";\r\nshared datAenderungProdukt = let\r\n  Source = Sql.Databases(\"Degoesql_GTGDevAenderungsDB\"),\r\n  #\"Navigation 1\" = Source{[Name = \"GTGDevAenderungsDB\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Schema = \"dbo\", Item = \"datAenderungProdukt\"]}[Data]\r\nin\r\n  #\"Navigation 2\";\r\nshared datAenderungProperties = let\r\n  Source = Sql.Databases(\"Degoesql_GTGDevAenderungsDB\"),\r\n  #\"Navigation 1\" = Source{[Name = \"GTGDevAenderungsDB\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Schema = \"dbo\", Item = \"datAenderungProperties\"]}[Data]\r\nin\r\n  #\"Navigation 2\";\r\nshared datAenderungRolle = let\r\n  Source = Sql.Databases(\"Degoesql_GTGDevAenderungsDB\"),\r\n  #\"Navigation 1\" = Source{[Name = \"GTGDevAenderungsDB\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Schema = \"dbo\", Item = \"datAenderungRolle\"]}[Data]\r\nin\r\n  #\"Navigation 2\";\r\nshared datAenderungStatusHistory = let\r\n  Source = Sql.Databases(\"Degoesql_GTGDevAenderungsDB\"),\r\n  #\"Navigation 1\" = Source{[Name = \"GTGDevAenderungsDB\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Schema = \"dbo\", Item = \"datAenderungStatusHistory\"]}[Data]\r\nin\r\n  #\"Navigation 2\";\r\nshared stdAenderungStatus = let\r\n  Source = Sql.Databases(\"Degoesql_GTGDevAenderungsDB\"),\r\n  #\"Navigation 1\" = Source{[Name = \"GTGDevAenderungsDB\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Schema = \"dbo\", Item = \"stdAenderungStatus\"]}[Data]\r\nin\r\n  #\"Navigation 2\";\r\nshared stdAenderungTyp = let\r\n  Source = Sql.Databases(\"Degoesql_GTGDevAenderungsDB\"),\r\n  #\"Navigation 1\" = Source{[Name = \"GTGDevAenderungsDB\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Schema = \"dbo\", Item = \"stdAenderungTyp\"]}[Data]\r\nin\r\n  #\"Navigation 2\";\r\nshared stdFilter = let\r\n  Source = Sql.Databases(\"Degoesql_GTGDevAenderungsDB\"),\r\n  #\"Navigation 1\" = Source{[Name = \"GTGDevAenderungsDB\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Schema = \"dbo\", Item = \"stdFilter\"]}[Data]\r\nin\r\n  #\"Navigation 2\";\r\nshared stdMitarbeiter = let\r\n  Source = Sql.Databases(\"Degoesql_GTGDevAenderungsDB\"),\r\n  #\"Navigation 1\" = Source{[Name = \"GTGDevAenderungsDB\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Schema = \"dbo\", Item = \"stdMitarbeiter\"]}[Data]\r\nin\r\n  #\"Navigation 2\";\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"datAenderung","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"datAenderung.csv"},"attributes":[{"name":"AenderungID","dataType":"int64"},{"name":"LastUpdate","dataType":"dateTime"},{"name":"AenderungTypID","dataType":"int64"},{"name":"AenderungNummer","dataType":"string"},{"name":"DatumAntragstellung","dataType":"dateTime"},{"name":"Kurztitel","dataType":"string"},{"name":"AenderungStatusID","dataType":"int64"},{"name":"PrioSicherheitsrelevant","dataType":"boolean"},{"name":"PrioErnst","dataType":"int64"},{"name":"PrioDringlichkeit","dataType":"int64"},{"name":"PrioVerlauf","dataType":"int64"},{"name":"AntragFehlervermeidung","dataType":"boolean"},{"name":"AntragVereinfachung","dataType":"boolean"},{"name":"AntragKostenreduktion","dataType":"boolean"},{"name":"AntragKostenProGeraet","dataType":"double"},{"name":"AntragKundenwunsch","dataType":"boolean"},{"name":"AntragFunktionsverbesserung","dataType":"boolean"},{"name":"AntragSonstiges","dataType":"string"},{"name":"AntragMotivation","dataType":"string"},{"name":"AntragBeschreibung","dataType":"string"},{"name":"AntragVorNachteile","dataType":"string"},{"name":"AntragKompatibel","dataType":"boolean"},{"name":"AntragPflichtenheftAbsprachen","dataType":"string"},{"name":"FilterID","dataType":"int64"},{"name":"datAenderungProdukt.Ausgewaehlt","dataType":"boolean"},{"name":"datAenderungProdukt.Bemerkung","dataType":"string"},{"name":"stdAenderungStatus.StatusBezeichnung","dataType":"string"},{"name":"stdAenderungStatus.Aktuell","dataType":"boolean"},{"name":"stdAenderungStatus.AntragBearbeiten","dataType":"int64"},{"name":"stdAenderungStatus.AenderungBearbeiten","dataType":"int64"},{"name":"stdAenderungStatus.AntragLoeschen","dataType":"int64"},{"name":"stdAenderungStatus.Kommentar","dataType":"string"},{"name":"stdAenderungTyp.AenderungTyp","dataType":"string"},{"name":"stdMitarbeiter(AntragstellerID).WindowsLogin","dataType":"string"},{"name":"stdMitarbeiter(BearbeiterID).WindowsLogin","dataType":"string"},{"name":"stdMitarbeiter(BearbeiterID).Inaktiv","dataType":"boolean"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-20T02:00:30.162425+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/50d64c6e-b356-4cee-84e4-dbdd33220bc8/datAenderung.csv?snapshot=2022-05-20T02%3A00%3A30.1376322Z"}]}]}