{"name":"Flow_General Data","description":"General data load, multiple times per day.","version":"1.0","culture":"en-US","modifiedTime":"2022-04-21T14:12:39.6205092+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"HEMO-Status":{"queryId":"0e2f7ccb-8677-45b8-a48f-1ffba17f84bc","queryName":"HEMO-Status","queryGroupId":"a47e41c8-d952-482e-9a82-baa69f71c4ef"},"HEMO_InkTests":{"queryId":"ab9bb7b8-5492-4707-8876-b5db527ad9ec","queryName":"HEMO_InkTests","queryGroupId":"a47e41c8-d952-482e-9a82-baa69f71c4ef","loadEnabled":true},"HEMO_Remondis":{"queryId":"d6a5d1be-1f6f-42a1-a07d-7e71a8a1ce5a","queryName":"HEMO_Remondis","queryGroupId":"a47e41c8-d952-482e-9a82-baa69f71c4ef","loadEnabled":true},"HEMO_Tanks":{"queryId":"53cd8610-e733-4091-adaa-758a81ed2d56","queryName":"HEMO_Tanks","queryGroupId":"a47e41c8-d952-482e-9a82-baa69f71c4ef","loadEnabled":true},"HEMO-Status2":{"queryId":"0205887c-0220-4cc2-ac8f-cc1ecef8f643","queryName":"HEMO-Status2","queryGroupId":"a47e41c8-d952-482e-9a82-baa69f71c4ef","loadEnabled":true},"HEMO-Status2_backup":{"queryId":"ec9b22bd-cc96-441b-ab59-6796558105d5","queryName":"HEMO-Status2_backup","queryGroupId":"a47e41c8-d952-482e-9a82-baa69f71c4ef"},"MissingParts_FeedbackForm":{"queryId":"021ad61c-7614-4e6c-972e-1a8db6f15345","queryName":"MissingParts_FeedbackForm","loadEnabled":true},"MissingParts_FeedbackForm (2)":{"queryId":"acd4fb5b-fea4-4eeb-b02d-dd3fc92e40f0","queryName":"MissingParts_FeedbackForm (2)"}},"document":"section Section1;\r\nshared #\"HEMO-Status\" = let\r\n  Source = SharePoint.Tables(\"https://cohrinc.sharepoint.com/sites/GEPMEPowerBIReports/\", [ApiVersion = 15]),\r\n  Navigation = Source{[Id = \"e679f801-ff34-49f7-88ad-6011adbeff66\"]}[Items],\r\n  #\"Choose columns\" = Table.SelectColumns(Navigation, {\"ID\", \"Title\", \"Created\", \"OData_2\", \"OData_3\", \"OData_4\", \"OData_5\", \"OData_6\", \"FailureCodeEMO\", \"FailureCode\"}),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Choose columns\", {{\"Title\", type text}, {\"OData_2\", type text}, {\"OData_4\", type text}, {\"OData_5\", type text}, {\"OData_6\", type text}, {\"FailureCodeEMO\", type text}, {\"FailureCode\", type text}, {\"ID\", Int64.Type}, {\"Created\", type datetime}, {\"OData_3\", type datetime}}),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Changed column type\", {{\"Title\", \"Operator\"}, {\"OData_2\", \"EMO-Machine\"}, {\"OData_3\", \"DateTimeStatus\"}, {\"OData_4\", \"EMO-Status\"}, {\"OData_5\", \"Operation-Status\"}, {\"OData_6\", \"Comments\"}}),\r\n  #\"Inserted last characters\" = Table.AddColumn(#\"Renamed columns\", \"Org\", each Text.End([#\"EMO-Machine\"], 1), type text)\r\nin\r\n  #\"Inserted last characters\";\r\nshared HEMO_InkTests = let\r\n  Source = SharePoint.Tables(\"https://cohrinc.sharepoint.com/sites/GEPMEPowerBIReports/\", [ApiVersion = 15]),\r\n  Navigation = Source{[Id = \"aa2f427b-0787-4feb-99a8-f952bf551dda\"]}[Items],\r\n  #\"Choose columns\" = Table.SelectColumns(Navigation, {\"ID\", \"Title\", \"Modified\", \"Created\", \"Device\", \"DateTime\", \"Comments\", \"Part_Number\", \"Part_Description\", \"Oracle_WO\", \"Surface_Tension\", \"Cond_Cartr1_Input\", \"Cond_Cartr1_Output\", \"CheckVacuumPump\"}),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Choose columns\", {{\"ID\", Int64.Type}, {\"Title\", type text}, {\"Device\", type text}, {\"Comments\", type text}, {\"Part_Number\", type text}, {\"Part_Description\", type text}, {\"Oracle_WO\", type text}, {\"Modified\", type datetime}, {\"Created\", type datetime}, {\"DateTime\", type datetime}, {\"CheckVacuumPump\", type logical}, {\"Surface_Tension\", type number}, {\"Cond_Cartr1_Output\", type number}, {\"Cond_Cartr1_Input\", type number}}),\r\n  #\"Inserted last characters\" = Table.AddColumn(#\"Changed column type\", \"Org_Key\", each Text.End([Device], 1), type text)\r\nin\r\n  #\"Inserted last characters\";\r\nshared HEMO_Remondis = let\r\n  Source = SharePoint.Tables(\"https://cohrinc.sharepoint.com/sites/GEPMEPowerBIReports/\", [ApiVersion = 15]),\r\n  #\"Navigation 1\" = Source{[Id = \"c92a1956-ab11-440d-a061-b3ecb69be3fc\"]}[Items],\r\n  #\"Choose columns\" = Table.SelectColumns(#\"Navigation 1\", {\"Title\", \"Device\", \"DateTime\", \"DateDisposed\", \"PO\", \"Category\", \"WasteKey\", \"OrderQty\", \"DisposedQty\", \"WasteWeight\", \"QtyWater\", \"QtyDowclene\", \"Photo\", \"PrctDowclene\", \"Legend\", \"Comments\", \"DateDelivered\", \"ID\", \"Modified\", \"Created\"}),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Choose columns\", {{\"Title\", type text}, {\"Device\", type text}, {\"PO\", type text}, {\"Category\", type text}, {\"WasteKey\", type text}, {\"Legend\", type text}, {\"Comments\", type text}, {\"ID\", Int64.Type}, {\"Modified\", type datetime}, {\"Created\", type datetime}, {\"DateTime\", type datetime}, {\"DateDisposed\", type date}, {\"OrderQty\", Int64.Type}, {\"DisposedQty\", Int64.Type}, {\"WasteWeight\", Int64.Type}, {\"QtyWater\", Int64.Type}, {\"QtyDowclene\", Int64.Type}, {\"Photo\", type text}, {\"PrctDowclene\", type number}, {\"DateDelivered\", type date}})\r\nin\r\n  #\"Changed column type\";\r\nshared HEMO_Tanks = let\r\n  Source = SharePoint.Tables(\"https://cohrinc.sharepoint.com/sites/GEPMEPowerBIReports/\", [ApiVersion = 15]),\r\n  #\"Navigation 1\" = Source{[Id = \"e27b861e-04fd-4913-952c-14db6b6ead62\"]}[Items],\r\n  #\"Choose columns\" = Table.SelectColumns(#\"Navigation 1\", {\"Title\", \"T1_Temp\", \"T1_Sug_Refill\", \"T1_Booster\", \"T1_Chloride\", \"T1_Sug_Action\", \"T11_pH\", \"T11_Temp\", \"T11_Titration\", \"T11_Surtec_Concentr\", \"T11_Surtec_Rest\", \"T11_Sug_Surtec\", \"T11_Refill_Surtec\", \"T12_pH\", \"T12_Temp\", \"T12_Conductivity\", \"Device\", \"DateTime\", \"T1_pH\", \"ID\", \"Modified\", \"Created\"}),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Choose columns\", {{\"Created\", type datetime}, {\"Modified\", type datetime}, {\"ID\", Int64.Type}, {\"DateTime\", type datetime}, {\"T1_pH\", type number}, {\"Device\", type text}, {\"Title\", type text}, {\"T1_Temp\", type number}, {\"T1_Sug_Refill\", type number}, {\"T1_Booster\", type number}, {\"T1_Chloride\", type number}, {\"T1_Sug_Action\", type text}, {\"T11_pH\", type number}, {\"T11_Temp\", type number}, {\"T11_Titration\", type number}, {\"T11_Surtec_Concentr\", type number}, {\"T11_Surtec_Rest\", type number}, {\"T11_Sug_Surtec\", type number}, {\"T11_Refill_Surtec\", type number}, {\"T12_pH\", type number}, {\"T12_Temp\", type number}, {\"T12_Conductivity\", type number}}),\r\n  #\"Inserted last characters\" = Table.AddColumn(#\"Changed column type\", \"Org_Key\", each Text.End([Device], 1), type text)\r\nin\r\n  #\"Inserted last characters\";\r\nshared #\"HEMO-Status2\" = let\r\n  Source = SharePoint.Tables(\"https://cohrinc.sharepoint.com/sites/GEPMEPowerBIReports/\", [ApiVersion = 15]),\r\n  Navigation = Source{[Id = \"e679f801-ff34-49f7-88ad-6011adbeff66\"]}[Items],\r\n  #\"Choose columns\" = Table.SelectColumns(Navigation, {\"ID\", \"Title\", \"Created\", \"OData_2\", \"OData_3\", \"OData_4\", \"OData_5\", \"OData_6\", \"FailureCodeEMO\", \"FailureCode\"}),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Choose columns\", {{\"Title\", type text}, {\"OData_2\", type text}, {\"OData_4\", type text}, {\"OData_5\", type text}, {\"OData_6\", type text}, {\"FailureCodeEMO\", type text}, {\"FailureCode\", type text}, {\"ID\", Int64.Type}, {\"Created\", type datetimezone}, {\"OData_3\", type datetimezone}}),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Changed column type\", {{\"Title\", \"Operator\"}, {\"OData_2\", \"EMO-Machine\"}, {\"OData_3\", \"DateTimeStatus_UTC\"}, {\"OData_4\", \"EMO-Status\"}, {\"OData_5\", \"Operation-Status\"}, {\"OData_6\", \"Comments\"}, {\"Created\", \"DateTimeCreated_UTC\"}}),\r\n  #\"Added custom\" = Table.AddColumn(#\"Renamed columns\", \"DateTimeStatus\", each DateTimeZone.SwitchZone([DateTimeStatus_UTC], 1)),\r\n  #\"Changed column type 1\" = Table.TransformColumnTypes(#\"Added custom\", {{\"DateTimeStatus\", type datetimezone}}),\r\n  #\"Added custom 1\" = Table.AddColumn(#\"Changed column type 1\", \"DateTimeCreated\", each DateTimeZone.SwitchZone([DateTimeCreated_UTC], 1)),\r\n  #\"Changed column type 2\" = Table.TransformColumnTypes(#\"Added custom 1\", {{\"DateTimeCreated\", type datetimezone}}),\r\n  #\"Added custom 2\" = Table.AddColumn(#\"Changed column type 2\", \"DateStatus\", each DateTimeZone.RemoveZone([DateTimeStatus])),\r\n  #\"Changed column type 3\" = Table.TransformColumnTypes(#\"Added custom 2\", {{\"DateStatus\", type date}}),\r\n  #\"Reordered columns\" = Table.ReorderColumns(#\"Changed column type 3\", {\"ID\", \"DateTimeCreated_UTC\", \"DateTimeCreated\", \"DateTimeStatus_UTC\", \"DateStatus\", \"DateTimeStatus\", \"Operator\", \"EMO-Machine\", \"EMO-Status\", \"Operation-Status\", \"Comments\", \"FailureCodeEMO\", \"FailureCode\"}),\r\n  #\"Inserted last characters\" = Table.AddColumn(#\"Reordered columns\", \"Org_Key\", each Text.End([#\"EMO-Machine\"], 1), type text)\r\nin\r\n  #\"Inserted last characters\";\r\nshared #\"HEMO-Status2_backup\" = let\r\n  Source = SharePoint.Tables(\"https://cohrinc.sharepoint.com/sites/GEPMEPowerBIReports/\", [ApiVersion = 15]),\r\n  Navigation = Source{[Id = \"e679f801-ff34-49f7-88ad-6011adbeff66\"]}[Items],\r\n  #\"Choose columns\" = Table.SelectColumns(Navigation, {\"ID\", \"Title\", \"Created\", \"OData_2\", \"OData_3\", \"OData_4\", \"OData_5\", \"OData_6\", \"FailureCodeEMO\", \"FailureCode\"}),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Choose columns\", {{\"Title\", type text}, {\"OData_2\", type text}, {\"OData_4\", type text}, {\"OData_5\", type text}, {\"OData_6\", type text}, {\"FailureCodeEMO\", type text}, {\"FailureCode\", type text}, {\"ID\", Int64.Type}, {\"Created\", type datetimezone}, {\"OData_3\", type datetimezone}}),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Changed column type\", {{\"Title\", \"Operator\"}, {\"OData_2\", \"EMO-Machine\"}, {\"OData_3\", \"DateTimeStatus_UTC\"}, {\"OData_4\", \"EMO-Status\"}, {\"OData_5\", \"Operation-Status\"}, {\"OData_6\", \"Comments\"}, {\"Created\", \"DateTimeCreated_UTC\"}}),\r\n  #\"Added custom\" = Table.AddColumn(#\"Renamed columns\", \"DateTimeStatus\", each DateTimeZone.SwitchZone([DateTimeStatus_UTC], 2)),\r\n  #\"Changed column type 1\" = Table.TransformColumnTypes(#\"Added custom\", {{\"DateTimeStatus\", type datetimezone}}),\r\n  #\"Added custom 1\" = Table.AddColumn(#\"Changed column type 1\", \"DateTimeCreated\", each DateTimeZone.SwitchZone([DateTimeCreated_UTC], 2)),\r\n  #\"Changed column type 2\" = Table.TransformColumnTypes(#\"Added custom 1\", {{\"DateTimeCreated\", type datetimezone}}),\r\n  #\"Added custom 2\" = Table.AddColumn(#\"Changed column type 2\", \"DateStatus\", each DateTimeZone.RemoveZone([DateTimeStatus])),\r\n  #\"Changed column type 3\" = Table.TransformColumnTypes(#\"Added custom 2\", {{\"DateStatus\", type date}}),\r\n  #\"Reordered columns\" = Table.ReorderColumns(#\"Changed column type 3\", {\"ID\", \"DateTimeCreated_UTC\", \"DateTimeCreated\", \"DateTimeStatus_UTC\", \"DateStatus\", \"DateTimeStatus\", \"Operator\", \"EMO-Machine\", \"EMO-Status\", \"Operation-Status\", \"Comments\", \"FailureCodeEMO\", \"FailureCode\"})\r\nin\r\n  #\"Reordered columns\";\r\nshared MissingParts_FeedbackForm = let\r\n  Quelle = SharePoint.Tables(\"https://cohrinc.sharepoint.com/sites/GEPMEPowerBIReports\", [Implementation=\"2.0\", ViewMode=\"Default\"]),\r\n  #\"b2768ca6-db82-4ecd-869a-0f82e6dd4ea0\" = Quelle{[Id = \"b2768ca6-db82-4ecd-869a-0f82e6dd4ea0\"]}[Items],\r\n  #\"Geänderter Typ\" = Table.TransformColumnTypes(#\"b2768ca6-db82-4ecd-869a-0f82e6dd4ea0\", {{\"SupplyOrderNumber\", type text}}),\r\n  #\"Zusammengeführte Abfragen\" = Table.NestedJoin(#\"Geänderter Typ\", {\"Status\"}, #\"MissingParts_FeedbackForm (2)\", {\"Status\"}, \"MissingParts_FeedbackForm (2)\", JoinKind.LeftOuter),\r\n  #\"Expanded MissingParts_FeedbackForm (2)\" = Table.ExpandTableColumn(#\"Zusammengeführte Abfragen\", \"MissingParts_FeedbackForm (2)\", {\"Index\"}, {\"Index\"}),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Expanded MissingParts_FeedbackForm (2)\", {{\"Index\", \"Status-ID\"}}),\r\n  #\"Reordered columns\" = Table.ReorderColumns(#\"Renamed columns\", {\"SupplyOrderNumber\", \"DateTime\", \"User\", \"Status-ID\", \"Status\", \"Feedback\", \"ItemNumber\", \"Supplier\", \"Old_Due_Date\", \"ID\"})\r\nin\r\n  #\"Reordered columns\";\r\nshared #\"MissingParts_FeedbackForm (2)\" = let\r\n  Quelle = SharePoint.Tables(\"https://cohrinc.sharepoint.com/sites/GEPMEPowerBIReports\", [Implementation=\"2.0\", ViewMode=\"Default\"]),\r\n  #\"b2768ca6-db82-4ecd-869a-0f82e6dd4ea0\" = Quelle{[Id = \"b2768ca6-db82-4ecd-869a-0f82e6dd4ea0\"]}[Items],\r\n  #\"Geänderter Typ\" = Table.TransformColumnTypes(#\"b2768ca6-db82-4ecd-869a-0f82e6dd4ea0\", {{\"SupplyOrderNumber\", type text}}),\r\n  #\"Andere entfernte Spalten\" = Table.SelectColumns(#\"Geänderter Typ\", {\"Status\"}),\r\n  #\"Removed duplicates\" = Table.Distinct(#\"Andere entfernte Spalten\", {\"Status\"}),\r\n  #\"Sortierte Zeilen\" = Table.Sort(#\"Removed duplicates\", {{\"Status\", Order.Descending}}),\r\n  #\"Hinzugefügter Index\" = Table.AddIndexColumn(#\"Sortierte Zeilen\", \"Index\", 1, 1, Int64.Type)\r\nin\r\n  #\"Hinzugefügter Index\";\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[{\"id\":\"a47e41c8-d952-482e-9a82-baa69f71c4ef\",\"name\":\"HEMO\",\"description\":\"\",\"parentId\":null,\"order\":0}]"}],"entities":[{"$type":"LocalEntity","name":"HEMO_InkTests","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"HEMO_InkTests.csv"},"attributes":[{"name":"ID","dataType":"int64"},{"name":"Title","dataType":"string"},{"name":"Modified","dataType":"dateTime"},{"name":"Created","dataType":"dateTime"},{"name":"Device","dataType":"string"},{"name":"DateTime","dataType":"dateTime"},{"name":"Comments","dataType":"string"},{"name":"Part_Number","dataType":"string"},{"name":"Part_Description","dataType":"string"},{"name":"Oracle_WO","dataType":"string"},{"name":"Surface_Tension","dataType":"double"},{"name":"Cond_Cartr1_Input","dataType":"double"},{"name":"Cond_Cartr1_Output","dataType":"double"},{"name":"CheckVacuumPump","dataType":"boolean"},{"name":"Org_Key","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T10:00:13.2914495+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/559b69c5-3ad1-4ba9-b53c-4b9180382350/HEMO_InkTests.csv?snapshot=2022-06-13T10%3A00%3A13.0764820Z"}]},{"$type":"LocalEntity","name":"HEMO_Remondis","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"HEMO_Remondis.csv"},"attributes":[{"name":"Title","dataType":"string"},{"name":"Device","dataType":"string"},{"name":"DateTime","dataType":"dateTime"},{"name":"DateDisposed","dataType":"date"},{"name":"PO","dataType":"string"},{"name":"Category","dataType":"string"},{"name":"WasteKey","dataType":"string"},{"name":"OrderQty","dataType":"int64"},{"name":"DisposedQty","dataType":"int64"},{"name":"WasteWeight","dataType":"int64"},{"name":"QtyWater","dataType":"int64"},{"name":"QtyDowclene","dataType":"int64"},{"name":"Photo","dataType":"string"},{"name":"PrctDowclene","dataType":"double"},{"name":"Legend","dataType":"string"},{"name":"Comments","dataType":"string"},{"name":"DateDelivered","dataType":"date"},{"name":"ID","dataType":"int64"},{"name":"Modified","dataType":"dateTime"},{"name":"Created","dataType":"dateTime"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T10:00:11.7914351+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/559b69c5-3ad1-4ba9-b53c-4b9180382350/HEMO_Remondis.csv?snapshot=2022-06-13T10%3A00%3A11.6913219Z"}]},{"$type":"LocalEntity","name":"HEMO_Tanks","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"HEMO_Tanks.csv"},"attributes":[{"name":"Title","dataType":"string"},{"name":"T1_Temp","dataType":"double"},{"name":"T1_Sug_Refill","dataType":"double"},{"name":"T1_Booster","dataType":"double"},{"name":"T1_Chloride","dataType":"double"},{"name":"T1_Sug_Action","dataType":"string"},{"name":"T11_pH","dataType":"double"},{"name":"T11_Temp","dataType":"double"},{"name":"T11_Titration","dataType":"double"},{"name":"T11_Surtec_Concentr","dataType":"double"},{"name":"T11_Surtec_Rest","dataType":"double"},{"name":"T11_Sug_Surtec","dataType":"double"},{"name":"T11_Refill_Surtec","dataType":"double"},{"name":"T12_pH","dataType":"double"},{"name":"T12_Temp","dataType":"double"},{"name":"T12_Conductivity","dataType":"double"},{"name":"Device","dataType":"string"},{"name":"DateTime","dataType":"dateTime"},{"name":"T1_pH","dataType":"double"},{"name":"ID","dataType":"int64"},{"name":"Modified","dataType":"dateTime"},{"name":"Created","dataType":"dateTime"},{"name":"Org_Key","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T10:00:12.0258141+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/559b69c5-3ad1-4ba9-b53c-4b9180382350/HEMO_Tanks.csv?snapshot=2022-06-13T10%3A00%3A11.7562824Z"}]},{"$type":"LocalEntity","name":"HEMO-Status2","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"HEMO-Status2.csv"},"attributes":[{"name":"ID","dataType":"int64"},{"name":"DateTimeCreated_UTC","dataType":"dateTimeOffset"},{"name":"DateTimeCreated","dataType":"dateTimeOffset"},{"name":"DateTimeStatus_UTC","dataType":"dateTimeOffset"},{"name":"DateStatus","dataType":"date"},{"name":"DateTimeStatus","dataType":"dateTimeOffset"},{"name":"Operator","dataType":"string"},{"name":"EMO-Machine","dataType":"string"},{"name":"EMO-Status","dataType":"string"},{"name":"Operation-Status","dataType":"string"},{"name":"Comments","dataType":"string"},{"name":"FailureCodeEMO","dataType":"string"},{"name":"FailureCode","dataType":"string"},{"name":"Org_Key","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T10:00:17.4237199+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/559b69c5-3ad1-4ba9-b53c-4b9180382350/HEMO-Status2.csv?snapshot=2022-06-13T10%3A00%3A17.3538892Z"}]},{"$type":"LocalEntity","name":"MissingParts_FeedbackForm","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"MissingParts_FeedbackForm.csv"},"attributes":[{"name":"SupplyOrderNumber","dataType":"string"},{"name":"DateTime","dataType":"dateTime"},{"name":"User","dataType":"string"},{"name":"Status-ID","dataType":"int64"},{"name":"Status","dataType":"string"},{"name":"Feedback","dataType":"string"},{"name":"ItemNumber","dataType":"string"},{"name":"Supplier","dataType":"string"},{"name":"Old_Due_Date","dataType":"dateTime"},{"name":"ID","dataType":"int64"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T10:00:10.1039259+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/559b69c5-3ad1-4ba9-b53c-4b9180382350/MissingParts_FeedbackForm.csv?snapshot=2022-06-13T10%3A00%3A10.0513163Z"}]}]}