{"name":"Flow_Agile-BOMs","description":"Agile BOMs for assemblies.\nLoaded from manuel Excel export.","version":"1.0","culture":"en-US","modifiedTime":"2022-06-06T10:39:57.6842429+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"Agile_BOMs":{"queryId":"640d4913-5f41-4922-ab2c-54876667d2e3","queryName":"Agile_BOMs","loadEnabled":true},"Sample file":{"queryId":"c3598c8a-13f5-44c0-9d4c-5ddab2969552","queryName":"Sample file","queryGroupId":"2c7a01d5-28df-47f6-a027-c1e25421c144"},"Parameter":{"queryId":"2089d200-afab-45fc-b8d2-6c9ccd62ed95","queryName":"Parameter","queryGroupId":"2c7a01d5-28df-47f6-a027-c1e25421c144"},"Transform Sample file":{"queryId":"c7ac29a8-9202-4972-9490-d67d6b1497e4","queryName":"Transform Sample file","queryGroupId":"6cdcbf83-6fc0-48f1-b8b5-26ec8e487ebd"},"Transform file":{"queryId":"e7f4b59e-2c7d-4d4b-8f26-6d7a2c4d97c7","queryName":"Transform file","queryGroupId":"2c7a01d5-28df-47f6-a027-c1e25421c144"},"Agile_BOMs1229195":{"queryId":"ba2e2ba4-b9bb-4c6d-bcbd-bff27e0ca88d","queryName":"Agile_BOMs1229195","queryGroupId":"5e4846f4-d9d5-436e-bb22-d45872499c14"},"Agile_BOMs1229195_Grouped":{"queryId":"ae3569e1-49b0-4411-ba5f-9f10a38ea643","queryName":"Agile_BOMs1229195_Grouped","queryGroupId":"5e4846f4-d9d5-436e-bb22-d45872499c14"},"Agile_BOMs1229195R":{"queryId":"52710a4d-573e-4b63-bf69-a4dae2f4af15","queryName":"Agile_BOMs1229195R","queryGroupId":"5e4846f4-d9d5-436e-bb22-d45872499c14"},"Agile_BOMs1229195R_Grouped":{"queryId":"a79abbe2-c5c6-4f11-a0ee-35dda5df2fa3","queryName":"Agile_BOMs1229195R_Grouped","queryGroupId":"5e4846f4-d9d5-436e-bb22-d45872499c14"}},"document":"section Section1;\r\nshared Agile_BOMs = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/sites/GEPMEPowerBIReports/\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Folder Path] = \"https://cohrinc.sharepoint.com/sites/GEPMEPowerBIReports/Shared Documents/Agile_BOMs/\"),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows\", each [Attributes]?[Hidden]? <> true),\r\n  #\"Invoke custom function\" = Table.AddColumn(#\"Filtered hidden files\", \"Transform file\", each #\"Transform file\"([Content])),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Invoke custom function\", {{\"Name\", \"Source.Name\"}}),\r\n  #\"Removed other columns\" = Table.SelectColumns(#\"Renamed columns\", {\"Source.Name\", \"Transform file\"}),\r\n  #\"Filtered rows 1\" = Table.SelectRows(#\"Removed other columns\", each not Text.Contains([Source.Name], \"1229195\")),\r\n  #\"Expanded table column\" = Table.ExpandTableColumn(#\"Filtered rows 1\", \"Transform file\", Table.ColumnNames(#\"Transform file\"(#\"Sample file\"))),\r\n  #\"Choose columns\" = Table.SelectColumns(#\"Expanded table column\", {\"Level\", \"Item Number\", \"Item Description\", \"Qty\", \"UOM\", \"Find Num\", \"Assembly Item Number\", \"Assembly Description\"}),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Choose columns\", {{\"Level\", type text}, {\"Item Number\", type text}, {\"Item Description\", type text}, {\"UOM\", type text}, {\"Find Num\", type text}, {\"Assembly Item Number\", type text}, {\"Assembly Description\", type text}, {\"Qty\", type number}}),\r\n  #\"Removed blank rows\" = Table.SelectRows(#\"Changed column type\", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {\"\", null}))),\r\n  #\"Appended query\" = Table.Combine({#\"Removed blank rows\", Agile_BOMs1229195R})\r\nin\r\n  #\"Appended query\";\r\nshared #\"Sample file\" = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/sites/GEPMEPowerBIReports/\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Folder Path] = \"https://cohrinc.sharepoint.com/sites/GEPMEPowerBIReports/Shared Documents/Agile_BOMs/\"),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows\", each [Attributes]?[Hidden]? <> true),\r\n  Navigation = #\"Filtered hidden files\"{0}[Content]\r\nin\r\n  Navigation;\r\nshared Parameter = let\r\n  Parameter = #\"Sample file\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type binary, BinaryIdentifier = #\"Sample file\"]\r\nin\r\n  Parameter;\r\nshared #\"Transform Sample file\" = let\r\n  Source = Excel.Workbook(Parameter, null, true),\r\n  Navigation = Source{[Item = \"Sheet0\", Kind = \"Sheet\"]}[Data],\r\n  #\"Promoted headers\" = Table.PromoteHeaders(Navigation, [PromoteAllScalars = true])\r\nin\r\n  #\"Promoted headers\";\r\nshared #\"Transform file\" = let\r\n  Source = (Parameter as binary) => let\r\n  Source = Excel.Workbook(Parameter, null, true),\r\n  Navigation = Source{[Item = \"Sheet0\", Kind = \"Sheet\"]}[Data],\r\n  #\"Promoted headers\" = Table.PromoteHeaders(Navigation, [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"Level\", type text}, {\"Attachments (Image)\", type logical}, {\"Manufacturer (Image)\", type logical}, {\"Pending Changes (Image)\", type logical}, {\"Has Been Redlined (Image)\", type logical}, {\"Item Number\", type text}, {\"Item Description\", type text}, {\"Item Type\", type text}, {\"Rev\", type text}, {\"Lifecycle Phase\", type text}, {\"Qty\", type number}, {\"UOM\", type text}, {\"Find Num\", type text}, {\"Assembly Item Number\", type text}, {\"Assembly Description\", type text}})\r\nin\r\n  #\"Changed column type\"\r\nin\r\n  Source;\r\nshared Agile_BOMs1229195 = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/sites/GEPMEPowerBIReports/\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Folder Path] = \"https://cohrinc.sharepoint.com/sites/GEPMEPowerBIReports/Shared Documents/Agile_BOMs/\"),\r\n  #\"Filtered rows 1\" = Table.SelectRows(#\"Filtered rows\", each Text.Contains([Name], \"1229195\")),\r\n  Navigation = #\"Filtered rows 1\"{[Name = \"BOM_VHP-GCS2_1229195.xlsx\", #\"Folder Path\" = \"https://cohrinc.sharepoint.com/sites/GEPMEPowerBIReports/Shared Documents/Agile_BOMs/\"]}[Content],\r\n  #\"Imported Excel workbook\" = Excel.Workbook(Navigation, null, true),\r\n  #\"Navigation 1\" = #\"Imported Excel workbook\"{[Item = \"Sheet0\", Kind = \"Sheet\"]}[Data],\r\n  #\"Promoted headers\" = Table.PromoteHeaders(#\"Navigation 1\", [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"Level\", type text}, {\"Attachments (Image)\", type logical}, {\"Manufacturer (Image)\", type logical}, {\"Pending Changes (Image)\", type logical}, {\"Has Been Redlined (Image)\", type logical}, {\"Item Number\", type text}, {\"Item Description\", type text}, {\"Item Type\", type text}, {\"Rev\", type text}, {\"Lifecycle Phase\", type text}, {\"Qty\", type number}, {\"UOM\", type text}, {\"Find Num\", type text}, {\"Assembly Item Number\", type text}, {\"Assembly Description\", type text}}),\r\n  #\"Choose columns\" = Table.SelectColumns(#\"Changed column type\", {\"Level\", \"Item Number\", \"Item Description\", \"Qty\", \"UOM\", \"Find Num\", \"Assembly Item Number\", \"Assembly Description\"})\r\nin\r\n  #\"Choose columns\";\r\nshared Agile_BOMs1229195_Grouped = let\r\n  Source = Agile_BOMs1229195,\r\n  #\"Grouped rows\" = Table.Group(Source, {\"Item Number\"}, {{\"Total_Qty\", each List.Sum([Qty]), type nullable number}})\r\nin\r\n  #\"Grouped rows\";\r\nshared Agile_BOMs1229195R = let\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/sites/GEPMEPowerBIReports/\", [ApiVersion = 15]),\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Folder Path] = \"https://cohrinc.sharepoint.com/sites/GEPMEPowerBIReports/Shared Documents/Agile_BOMs/\"),\n  #\"Filtered rows 1\" = Table.SelectRows(#\"Filtered rows\", each Text.Contains([Name], \"1229195\")),\n  Navigation = #\"Filtered rows 1\"{[Name = \"BOM_VHP-GCS2_1229195R.xlsx\", #\"Folder Path\" = \"https://cohrinc.sharepoint.com/sites/GEPMEPowerBIReports/Shared Documents/Agile_BOMs/\"]}[Content],\n  #\"Imported Excel workbook\" = Excel.Workbook(Navigation, null, true),\n  #\"Navigation 1\" = #\"Imported Excel workbook\"{[Item = \"Sheet0\", Kind = \"Sheet\"]}[Data],\n  #\"Promoted headers\" = Table.PromoteHeaders(#\"Navigation 1\", [PromoteAllScalars = true]),\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"Level\", type text}, {\"Attachments (Image)\", type logical}, {\"Manufacturer (Image)\", type logical}, {\"Pending Changes (Image)\", type logical}, {\"Has Been Redlined (Image)\", type logical}, {\"Item Number\", type text}, {\"Item Description\", type text}, {\"Item Type\", type text}, {\"Rev\", type text}, {\"Lifecycle Phase\", type text}, {\"Qty\", type number}, {\"UOM\", type text}, {\"Find Num\", type text}, {\"Assembly Item Number\", type text}, {\"Assembly Description\", type text}}),\n  #\"Choose columns\" = Table.SelectColumns(#\"Changed column type\", {\"Level\", \"Item Number\", \"Item Description\", \"Qty\", \"UOM\", \"Find Num\", \"Assembly Item Number\", \"Assembly Description\"}),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Choose columns\", {{\"Qty\", \"Qty_R\"}}),\r\n  #\"Duplicated column\" = Table.DuplicateColumn(#\"Renamed columns\", \"Item Number\", \"Item Number - Copy\"),\r\n  #\"Split column by delimiter\" = Table.SplitColumn(#\"Duplicated column\", \"Item Number - Copy\", Splitter.SplitTextByDelimiter(\"R\"), {\"Item Number - Copy.1\", \"Item Number - Copy.2\"}),\r\n  #\"Changed column type 1\" = Table.TransformColumnTypes(#\"Split column by delimiter\", {{\"Item Number - Copy.1\", type text}, {\"Item Number - Copy.2\", type text}}),\r\n  #\"Choose columns 1\" = Table.SelectColumns(#\"Changed column type 1\", {\"Level\", \"Item Number\", \"Item Description\", \"UOM\", \"Find Num\", \"Assembly Item Number\", \"Assembly Description\", \"Item Number - Copy.1\"}),\r\n  #\"Removed duplicates\" = Table.Distinct(#\"Choose columns 1\", {\"Item Number\"}),\r\n  #\"Merged queries\" = Table.NestedJoin(#\"Removed duplicates\", {\"Item Number\"}, Agile_BOMs1229195R_Grouped, {\"Item Number\"}, \"Agile_BOMs1229195R_Grouped\", JoinKind.LeftOuter),\r\n  #\"Expanded Agile_BOMs1229195R_Grouped\" = Table.ExpandTableColumn(#\"Merged queries\", \"Agile_BOMs1229195R_Grouped\", {\"Total_Qty_R\"}, {\"Total_Qty_R\"}),\r\n  #\"Merged queries 1\" = Table.NestedJoin(#\"Expanded Agile_BOMs1229195R_Grouped\", {\"Item Number - Copy.1\"}, Agile_BOMs1229195_Grouped, {\"Item Number\"}, \"Agile_BOMs1229195_Grouped\", JoinKind.LeftOuter),\r\n  #\"Expanded Agile_BOMs1229195_Grouped\" = Table.ExpandTableColumn(#\"Merged queries 1\", \"Agile_BOMs1229195_Grouped\", {\"Total_Qty\"}, {\"Total_Qty\"}),\r\n  #\"Inserted conditional column\" = Table.AddColumn(#\"Expanded Agile_BOMs1229195_Grouped\", \"Qty\", each if [Total_Qty] = null then [Total_Qty_R] else [Total_Qty]),\r\n  #\"Changed column type 2\" = Table.TransformColumnTypes(#\"Inserted conditional column\", {{\"Qty\", type number}}),\r\n  #\"Choose columns 2\" = Table.SelectColumns(#\"Changed column type 2\", {\"Level\", \"Item Number\", \"Item Description\", \"UOM\", \"Find Num\", \"Assembly Item Number\", \"Assembly Description\", \"Qty\"})\nin\n  #\"Choose columns 2\";\r\nshared Agile_BOMs1229195R_Grouped = let\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/sites/GEPMEPowerBIReports/\", [ApiVersion = 15]),\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Folder Path] = \"https://cohrinc.sharepoint.com/sites/GEPMEPowerBIReports/Shared Documents/Agile_BOMs/\"),\n  #\"Filtered rows 1\" = Table.SelectRows(#\"Filtered rows\", each Text.Contains([Name], \"1229195\")),\n  Navigation = #\"Filtered rows 1\"{[Name = \"BOM_VHP-GCS2_1229195R.xlsx\", #\"Folder Path\" = \"https://cohrinc.sharepoint.com/sites/GEPMEPowerBIReports/Shared Documents/Agile_BOMs/\"]}[Content],\n  #\"Imported Excel workbook\" = Excel.Workbook(Navigation, null, true),\n  #\"Navigation 1\" = #\"Imported Excel workbook\"{[Item = \"Sheet0\", Kind = \"Sheet\"]}[Data],\n  #\"Promoted headers\" = Table.PromoteHeaders(#\"Navigation 1\", [PromoteAllScalars = true]),\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"Level\", type text}, {\"Attachments (Image)\", type logical}, {\"Manufacturer (Image)\", type logical}, {\"Pending Changes (Image)\", type logical}, {\"Has Been Redlined (Image)\", type logical}, {\"Item Number\", type text}, {\"Item Description\", type text}, {\"Item Type\", type text}, {\"Rev\", type text}, {\"Lifecycle Phase\", type text}, {\"Qty\", type number}, {\"UOM\", type text}, {\"Find Num\", type text}, {\"Assembly Item Number\", type text}, {\"Assembly Description\", type text}}),\n  #\"Choose columns\" = Table.SelectColumns(#\"Changed column type\", {\"Level\", \"Item Number\", \"Item Description\", \"Qty\", \"UOM\", \"Find Num\", \"Assembly Item Number\", \"Assembly Description\"}),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Choose columns\", {{\"Qty\", \"Qty_R\"}}),\r\n  #\"Grouped rows\" = Table.Group(#\"Renamed columns\", {\"Item Number\"}, {{\"Total_Qty_R\", each List.Sum([Qty_R]), type nullable number}})\nin\n  #\"Grouped rows\";\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[{\"id\":\"6cdcbf83-6fc0-48f1-b8b5-26ec8e487ebd\",\"name\":\"Transform file from Agile_BOMs\",\"description\":null,\"parentId\":null,\"order\":0},{\"id\":\"2c7a01d5-28df-47f6-a027-c1e25421c144\",\"name\":\"Helper queries\",\"description\":null,\"parentId\":\"6cdcbf83-6fc0-48f1-b8b5-26ec8e487ebd\",\"order\":0},{\"id\":\"5e4846f4-d9d5-436e-bb22-d45872499c14\",\"name\":\"Agile_BOM_1229195\",\"description\":\"Agile BOM for 1229195/R.\",\"parentId\":null,\"order\":0}]"}],"entities":[{"$type":"LocalEntity","name":"Agile_BOMs","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Agile_BOMs.csv"},"attributes":[{"name":"Level","dataType":"string"},{"name":"Item Number","dataType":"string"},{"name":"Item Description","dataType":"string"},{"name":"Qty","dataType":"double"},{"name":"UOM","dataType":"string"},{"name":"Find Num","dataType":"string"},{"name":"Assembly Item Number","dataType":"string"},{"name":"Assembly Description","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-06T10:40:14.8679762+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/f113177c-7741-47dc-b8e0-eb0ad4bb2a67/Agile_BOMs.csv?snapshot=2022-06-06T10%3A40%3A14.8334650Z"}]}]}