{"name":"Flow_Pegging_Datamart_GEP_SnFl","description":"GEP only Pegging Datamart table from Snowflake.","version":"1.0","culture":"en-US","modifiedTime":"2022-04-29T12:36:42.5535678+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":true,"queriesMetadata":{"XXREP_SUP_PEG_DATAMART_V_GEP":{"queryId":"6ef36db3-bfe5-4f9e-825d-25d4e5e6868b","queryName":"XXREP_SUP_PEG_DATAMART_V_GEP","loadEnabled":true},"XXREP_SUP_PEG_DATAMART_V_MUC":{"queryId":"3c5669b2-2cf6-41a5-bd45-d07e1aec94fd","queryName":"XXREP_SUP_PEG_DATAMART_V_MUC","loadEnabled":true}},"document":"section Section1;\r\nshared XXREP_SUP_PEG_DATAMART_V_GEP = let\n  XXREP_SUP_PEG_DATAMART_V = Value.NativeQuery(Snowflake.Databases(\"mma12090.snowflakecomputing.com\",\"COMPUTE_REPORTING\", [Role=\"GLBMFGOPERATIONSROLE\"]){[Name=\"PROD_DB\"]}[Data], \"SELECT *FROM PROD_DB.APPS.XXREP_SUP_PEG_DATAMART_V Where ORG='GEP'\", null, [EnableFolding=true]),\n  #\"Changed column type\" = Table.TransformColumnTypes(XXREP_SUP_PEG_DATAMART_V, {{\"DEMAND_ID\", Int64.Type}, {\"PEG_DATAMART_ID\", Int64.Type}, {\"PEGGING_ID\", Int64.Type}, {\"PLAN_ID\", Int64.Type}, {\"REQUEST_ID\", Int64.Type}, {\"END_ITEM_ID\", Int64.Type}, {\"SUP_ITEM_ID\", Int64.Type}, {\"END_ORGANIZATION_ID\", Int64.Type}, {\"SUP_ORGANIZATION_ID\", Int64.Type}, {\"PREV_PEGGING_ID\", Int64.Type}, {\"END_PEGGING_ID\", Int64.Type}, {\"TRANSACTION_ID\", Int64.Type}, {\"END_ITEM_TRANSACTION_ID\", Int64.Type}, {\"ORGANIZATION_ID\", Int64.Type}, {\"PO_LINE_LOCATION_ID\", Int64.Type}, {\"PO_HEADER_ID\", Int64.Type}, {\"PO_RELEASE_ID\", Int64.Type}, {\"SO_LINE_ID\", Int64.Type}})\nin\n  #\"Changed column type\";\r\nshared XXREP_SUP_PEG_DATAMART_V_MUC = let\n  XXREP_SUP_PEG_DATAMART_V = Value.NativeQuery(Snowflake.Databases(\"mma12090.snowflakecomputing.com\",\"COMPUTE_REPORTING\", [Role=\"GLBMFGOPERATIONSROLE\"]){[Name=\"PROD_DB\"]}[Data], \"SELECT *FROM PROD_DB.APPS.XXREP_SUP_PEG_DATAMART_V Where ORG='MUC'\", null, [EnableFolding=true]),\n  #\"Changed column type\" = Table.TransformColumnTypes(XXREP_SUP_PEG_DATAMART_V, {{\"DEMAND_ID\", Int64.Type}, {\"PEG_DATAMART_ID\", Int64.Type}, {\"PEGGING_ID\", Int64.Type}, {\"PLAN_ID\", Int64.Type}, {\"REQUEST_ID\", Int64.Type}, {\"END_ITEM_ID\", Int64.Type}, {\"SUP_ITEM_ID\", Int64.Type}, {\"END_ORGANIZATION_ID\", Int64.Type}, {\"SUP_ORGANIZATION_ID\", Int64.Type}, {\"PREV_PEGGING_ID\", Int64.Type}, {\"END_PEGGING_ID\", Int64.Type}, {\"TRANSACTION_ID\", Int64.Type}, {\"END_ITEM_TRANSACTION_ID\", Int64.Type}, {\"ORGANIZATION_ID\", Int64.Type}, {\"PO_LINE_LOCATION_ID\", Int64.Type}, {\"PO_HEADER_ID\", Int64.Type}, {\"PO_RELEASE_ID\", Int64.Type}, {\"SO_LINE_ID\", Int64.Type}})\nin\n  #\"Changed column type\";\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"XXREP_SUP_PEG_DATAMART_V_GEP","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"XXREP_SUP_PEG_DATAMART_V_GEP.csv"},"attributes":[{"name":"DATE_RUN","dataType":"date"},{"name":"DEMAND_ORG_FAMILY","dataType":"string"},{"name":"DEMAND_ORG_LINE","dataType":"string"},{"name":"DEMAND_ORG_FORECAST","dataType":"string"},{"name":"DEMAND_SALES_COMMODITY","dataType":"string"},{"name":"SUPPLY_ORG_FAMILY","dataType":"string"},{"name":"SUPPLY_ORG_LINE","dataType":"string"},{"name":"SUPPLY_ORG_FORECAST","dataType":"string"},{"name":"SUPPLY_SOURCE_COMMODITY","dataType":"string"},{"name":"PLAN_NAME","dataType":"string"},{"name":"ORG","dataType":"string"},{"name":"ITEM_NUMBER","dataType":"string"},{"name":"FIRMED","dataType":"string"},{"name":"DESCRIPTION","dataType":"string"},{"name":"MRP_ABC","dataType":"string"},{"name":"MAKE_BUY","dataType":"string"},{"name":"ITEM_TYPE","dataType":"string"},{"name":"PLANNER_CODE","dataType":"string"},{"name":"BUYER_NAME","dataType":"string"},{"name":"SOURCE_ORGANIZATION_CODE","dataType":"string"},{"name":"SOURCE_VENDOR_NAME","dataType":"string"},{"name":"SOURCE_VENDOR_SITE_CODE","dataType":"string"},{"name":"CONFIRMED_BY_SUPPLIER","dataType":"string"},{"name":"CALC_ORDER_TYPE","dataType":"string"},{"name":"ASCP_LEAD_TIME","dataType":"double"},{"name":"PO_TYPE","dataType":"string"},{"name":"P_PO_NUMBER","dataType":"string"},{"name":"P_RELEASE_NUMBER","dataType":"string"},{"name":"P_LINE_NUMBER","dataType":"string"},{"name":"P_SHIPMENT_NUMBER","dataType":"string"},{"name":"QUANTITY_RATE","dataType":"double"},{"name":"PROJECT_NUMBER","dataType":"string"},{"name":"PO_UNIT_PRICE","dataType":"double"},{"name":"PO_UNIT_CURRENCY","dataType":"string"},{"name":"FX_RATE","dataType":"double"},{"name":"EXT_PO_SUPPLY_PRICE_USD","dataType":"double"},{"name":"SUPPLY_PEGGED_QTY","dataType":"double"},{"name":"SUP_PEGGGED_PRICE_USD","dataType":"double"},{"name":"ACTION","dataType":"string"},{"name":"SUPPLY_CATEGORY","dataType":"string"},{"name":"CALENDAR_DAYS_LATE","dataType":"double"},{"name":"OLD_DOCK_DATE","dataType":"date"},{"name":"OLD_DUE_DATE","dataType":"date"},{"name":"RESCHEDULE_DAYS","dataType":"string"},{"name":"COMPRESSION_DAYS","dataType":"double"},{"name":"SUGG_ORDER_DATE","dataType":"date"},{"name":"SUGG_START_DATE","dataType":"date"},{"name":"SUGG_DOCK_DATE","dataType":"date"},{"name":"SUGG_DUE_DATE","dataType":"date"},{"name":"PARENT_ITEM","dataType":"string"},{"name":"PARENT_ORGANIZATION","dataType":"string"},{"name":"PARENT_ITEM_DESCRIPTION","dataType":"string"},{"name":"PARENT_ORDER_TYPE","dataType":"string"},{"name":"PARENT_ORDER_DATE","dataType":"date"},{"name":"PARENT_ORDER_QTY","dataType":"double"},{"name":"PARENT_ORDER_NUMBER","dataType":"string"},{"name":"SUPPLY_ITEM_PEG_ATTR","dataType":"string"},{"name":"END_ITEM_ORG_CODE","dataType":"string"},{"name":"END_ITEM","dataType":"string"},{"name":"END_ITEM_DESC","dataType":"string"},{"name":"END_ITEM_MAKE_BUY","dataType":"string"},{"name":"END_ITEM_PLANNER_CODE","dataType":"string"},{"name":"END_ITEM_TYPE","dataType":"string"},{"name":"END_ITEM_CUSTOMER","dataType":"string"},{"name":"END_ITEM_DEM_TYPE","dataType":"string"},{"name":"END_ITEM_ORD_NUMBER","dataType":"string"},{"name":"END_ITEM_PEG_QUANTITY","dataType":"double"},{"name":"END_ITEM_QTY","dataType":"double"},{"name":"END_ITEM_PROJECT_NUMBER","dataType":"string"},{"name":"END_ITEM_DEMAND_DATE","dataType":"date"},{"name":"END_ITEM_ORDER_NUMBER","dataType":"string"},{"name":"END_ITEM_CALC_ORDER_NUMBER","dataType":"string"},{"name":"END_ITEM_ORDER_TYPE","dataType":"string"},{"name":"END_ITEM_ORDER_LINE","dataType":"string"},{"name":"END_ITEM_PEGGING_ATTR","dataType":"string"},{"name":"CALC_END_DEMAND_CUSTOMER","dataType":"string"},{"name":"ESO_ORG_CODE","dataType":"string"},{"name":"ESO_ORD_NUM","dataType":"string"},{"name":"ESO_LINE_NUM","dataType":"string"},{"name":"ESO_CUSTOMER","dataType":"string"},{"name":"ESO_SCH_DATE","dataType":"date"},{"name":"ESO_IR_NUM","dataType":"string"},{"name":"ESO_IR_LINE_NUM","dataType":"string"},{"name":"ESO_IR_LINE_STATUS","dataType":"string"},{"name":"END_ITEM_ORG","dataType":"string"},{"name":"ORDER_NUMBER","dataType":"string"},{"name":"FIRMED_LATE","dataType":"string"},{"name":"UNCONFIRM_SUPP_COUNT","dataType":"string"},{"name":"NUM_DAYS_WORKING","dataType":"double"},{"name":"ORGANIZATION_CODE","dataType":"string"},{"name":"DEMAND_ID","dataType":"int64"},{"name":"PEG_DATAMART_ID","dataType":"int64"},{"name":"PEGGING_ID","dataType":"int64"},{"name":"PLAN_ID","dataType":"int64"},{"name":"REQUEST_ID","dataType":"int64"},{"name":"ORDER_TYPE_TEXT","dataType":"string"},{"name":"CALC_SD_TYPE","dataType":"string"},{"name":"END_ITEM_ID","dataType":"int64"},{"name":"SUP_ITEM_ID","dataType":"int64"},{"name":"END_ORGANIZATION_ID","dataType":"int64"},{"name":"SUP_ORGANIZATION_ID","dataType":"int64"},{"name":"PREV_PEGGING_ID","dataType":"int64"},{"name":"END_PEGGING_ID","dataType":"int64"},{"name":"TRANSACTION_ID","dataType":"int64"},{"name":"END_ITEM_TRANSACTION_ID","dataType":"int64"},{"name":"ORGANIZATION_ID","dataType":"int64"},{"name":"PO_LINE_LOCATION_ID","dataType":"int64"},{"name":"PO_HEADER_ID","dataType":"int64"},{"name":"PO_RELEASE_ID","dataType":"int64"},{"name":"SO_LINE_ID","dataType":"int64"},{"name":"SUPPLY_QUAN_RATE","dataType":"double"},{"name":"CUSTOMER_NAME","dataType":"string"},{"name":"PLNORG_ID","dataType":"string"},{"name":"PREV_ITEM_TRANSACTION_ID","dataType":"double"},{"name":"PREV_ITEM_DEMAND_ID","dataType":"double"},{"name":"SCHEDULE_COMMENTS","dataType":"string"},{"name":"FORECAST_NAME","dataType":"string"},{"name":"FORECAST_DESC","dataType":"string"},{"name":"PARENT_WORK_DESC","dataType":"string"},{"name":"PO_BUYER","dataType":"string"},{"name":"PO_PROMISE_DATE","dataType":"date"},{"name":"PO_DESCRIPTION","dataType":"string"},{"name":"WO_STATUS","dataType":"string"},{"name":"WO_DESC","dataType":"string"},{"name":"IT_COST","dataType":"double"},{"name":"OSP_PO","dataType":"string"},{"name":"OSP_PO_LINE","dataType":"double"},{"name":"OSP_PO_LINE_ITEM","dataType":"string"},{"name":"OSP_PO_PROMISE_DATE","dataType":"date"},{"name":"PO_ORIG_PROM_DATE","dataType":"date"},{"name":"SAFE_STK_RSN","dataType":"string"},{"name":"ROW_CREATION_DATE","dataType":"dateTime"},{"name":"ITEM_ORG_KEY_CODE","dataType":"string"},{"name":"SUPPLY_STATUS","dataType":"string"},{"name":"SOURCE_ORG_OR_SUPPLIER","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-20T05:44:25.5979215+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/306d7911-81c0-462c-8e21-d6643a589b49/XXREP_SUP_PEG_DATAMART_V_GEP.csv?snapshot=2022-05-20T05%3A44%3A25.5466091Z"}]},{"$type":"LocalEntity","name":"XXREP_SUP_PEG_DATAMART_V_MUC","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"XXREP_SUP_PEG_DATAMART_V_MUC.csv"},"attributes":[{"name":"DATE_RUN","dataType":"date"},{"name":"DEMAND_ORG_FAMILY","dataType":"string"},{"name":"DEMAND_ORG_LINE","dataType":"string"},{"name":"DEMAND_ORG_FORECAST","dataType":"string"},{"name":"DEMAND_SALES_COMMODITY","dataType":"string"},{"name":"SUPPLY_ORG_FAMILY","dataType":"string"},{"name":"SUPPLY_ORG_LINE","dataType":"string"},{"name":"SUPPLY_ORG_FORECAST","dataType":"string"},{"name":"SUPPLY_SOURCE_COMMODITY","dataType":"string"},{"name":"PLAN_NAME","dataType":"string"},{"name":"ORG","dataType":"string"},{"name":"ITEM_NUMBER","dataType":"string"},{"name":"FIRMED","dataType":"string"},{"name":"DESCRIPTION","dataType":"string"},{"name":"MRP_ABC","dataType":"string"},{"name":"MAKE_BUY","dataType":"string"},{"name":"ITEM_TYPE","dataType":"string"},{"name":"PLANNER_CODE","dataType":"string"},{"name":"BUYER_NAME","dataType":"string"},{"name":"SOURCE_ORGANIZATION_CODE","dataType":"string"},{"name":"SOURCE_VENDOR_NAME","dataType":"string"},{"name":"SOURCE_VENDOR_SITE_CODE","dataType":"string"},{"name":"CONFIRMED_BY_SUPPLIER","dataType":"string"},{"name":"CALC_ORDER_TYPE","dataType":"string"},{"name":"ASCP_LEAD_TIME","dataType":"double"},{"name":"PO_TYPE","dataType":"string"},{"name":"P_PO_NUMBER","dataType":"string"},{"name":"P_RELEASE_NUMBER","dataType":"string"},{"name":"P_LINE_NUMBER","dataType":"string"},{"name":"P_SHIPMENT_NUMBER","dataType":"string"},{"name":"QUANTITY_RATE","dataType":"double"},{"name":"PROJECT_NUMBER","dataType":"string"},{"name":"PO_UNIT_PRICE","dataType":"double"},{"name":"PO_UNIT_CURRENCY","dataType":"string"},{"name":"FX_RATE","dataType":"double"},{"name":"EXT_PO_SUPPLY_PRICE_USD","dataType":"double"},{"name":"SUPPLY_PEGGED_QTY","dataType":"double"},{"name":"SUP_PEGGGED_PRICE_USD","dataType":"double"},{"name":"ACTION","dataType":"string"},{"name":"SUPPLY_CATEGORY","dataType":"string"},{"name":"CALENDAR_DAYS_LATE","dataType":"double"},{"name":"OLD_DOCK_DATE","dataType":"date"},{"name":"OLD_DUE_DATE","dataType":"date"},{"name":"RESCHEDULE_DAYS","dataType":"string"},{"name":"COMPRESSION_DAYS","dataType":"double"},{"name":"SUGG_ORDER_DATE","dataType":"date"},{"name":"SUGG_START_DATE","dataType":"date"},{"name":"SUGG_DOCK_DATE","dataType":"date"},{"name":"SUGG_DUE_DATE","dataType":"date"},{"name":"PARENT_ITEM","dataType":"string"},{"name":"PARENT_ORGANIZATION","dataType":"string"},{"name":"PARENT_ITEM_DESCRIPTION","dataType":"string"},{"name":"PARENT_ORDER_TYPE","dataType":"string"},{"name":"PARENT_ORDER_DATE","dataType":"date"},{"name":"PARENT_ORDER_QTY","dataType":"double"},{"name":"PARENT_ORDER_NUMBER","dataType":"string"},{"name":"SUPPLY_ITEM_PEG_ATTR","dataType":"string"},{"name":"END_ITEM_ORG_CODE","dataType":"string"},{"name":"END_ITEM","dataType":"string"},{"name":"END_ITEM_DESC","dataType":"string"},{"name":"END_ITEM_MAKE_BUY","dataType":"string"},{"name":"END_ITEM_PLANNER_CODE","dataType":"string"},{"name":"END_ITEM_TYPE","dataType":"string"},{"name":"END_ITEM_CUSTOMER","dataType":"string"},{"name":"END_ITEM_DEM_TYPE","dataType":"string"},{"name":"END_ITEM_ORD_NUMBER","dataType":"string"},{"name":"END_ITEM_PEG_QUANTITY","dataType":"double"},{"name":"END_ITEM_QTY","dataType":"double"},{"name":"END_ITEM_PROJECT_NUMBER","dataType":"string"},{"name":"END_ITEM_DEMAND_DATE","dataType":"date"},{"name":"END_ITEM_ORDER_NUMBER","dataType":"string"},{"name":"END_ITEM_CALC_ORDER_NUMBER","dataType":"string"},{"name":"END_ITEM_ORDER_TYPE","dataType":"string"},{"name":"END_ITEM_ORDER_LINE","dataType":"string"},{"name":"END_ITEM_PEGGING_ATTR","dataType":"string"},{"name":"CALC_END_DEMAND_CUSTOMER","dataType":"string"},{"name":"ESO_ORG_CODE","dataType":"string"},{"name":"ESO_ORD_NUM","dataType":"string"},{"name":"ESO_LINE_NUM","dataType":"string"},{"name":"ESO_CUSTOMER","dataType":"string"},{"name":"ESO_SCH_DATE","dataType":"date"},{"name":"ESO_IR_NUM","dataType":"string"},{"name":"ESO_IR_LINE_NUM","dataType":"string"},{"name":"ESO_IR_LINE_STATUS","dataType":"string"},{"name":"END_ITEM_ORG","dataType":"string"},{"name":"ORDER_NUMBER","dataType":"string"},{"name":"FIRMED_LATE","dataType":"string"},{"name":"UNCONFIRM_SUPP_COUNT","dataType":"string"},{"name":"NUM_DAYS_WORKING","dataType":"double"},{"name":"ORGANIZATION_CODE","dataType":"string"},{"name":"DEMAND_ID","dataType":"int64"},{"name":"PEG_DATAMART_ID","dataType":"int64"},{"name":"PEGGING_ID","dataType":"int64"},{"name":"PLAN_ID","dataType":"int64"},{"name":"REQUEST_ID","dataType":"int64"},{"name":"ORDER_TYPE_TEXT","dataType":"string"},{"name":"CALC_SD_TYPE","dataType":"string"},{"name":"END_ITEM_ID","dataType":"int64"},{"name":"SUP_ITEM_ID","dataType":"int64"},{"name":"END_ORGANIZATION_ID","dataType":"int64"},{"name":"SUP_ORGANIZATION_ID","dataType":"int64"},{"name":"PREV_PEGGING_ID","dataType":"int64"},{"name":"END_PEGGING_ID","dataType":"int64"},{"name":"TRANSACTION_ID","dataType":"int64"},{"name":"END_ITEM_TRANSACTION_ID","dataType":"int64"},{"name":"ORGANIZATION_ID","dataType":"int64"},{"name":"PO_LINE_LOCATION_ID","dataType":"int64"},{"name":"PO_HEADER_ID","dataType":"int64"},{"name":"PO_RELEASE_ID","dataType":"int64"},{"name":"SO_LINE_ID","dataType":"int64"},{"name":"SUPPLY_QUAN_RATE","dataType":"double"},{"name":"CUSTOMER_NAME","dataType":"string"},{"name":"PLNORG_ID","dataType":"string"},{"name":"PREV_ITEM_TRANSACTION_ID","dataType":"double"},{"name":"PREV_ITEM_DEMAND_ID","dataType":"double"},{"name":"SCHEDULE_COMMENTS","dataType":"string"},{"name":"FORECAST_NAME","dataType":"string"},{"name":"FORECAST_DESC","dataType":"string"},{"name":"PARENT_WORK_DESC","dataType":"string"},{"name":"PO_BUYER","dataType":"string"},{"name":"PO_PROMISE_DATE","dataType":"date"},{"name":"PO_DESCRIPTION","dataType":"string"},{"name":"WO_STATUS","dataType":"string"},{"name":"WO_DESC","dataType":"string"},{"name":"IT_COST","dataType":"double"},{"name":"OSP_PO","dataType":"string"},{"name":"OSP_PO_LINE","dataType":"double"},{"name":"OSP_PO_LINE_ITEM","dataType":"string"},{"name":"OSP_PO_PROMISE_DATE","dataType":"date"},{"name":"PO_ORIG_PROM_DATE","dataType":"date"},{"name":"SAFE_STK_RSN","dataType":"string"},{"name":"ROW_CREATION_DATE","dataType":"dateTime"},{"name":"ITEM_ORG_KEY_CODE","dataType":"string"},{"name":"SUPPLY_STATUS","dataType":"string"},{"name":"SOURCE_ORG_OR_SUPPLIER","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-20T05:41:12.7809157+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/306d7911-81c0-462c-8e21-d6643a589b49/XXREP_SUP_PEG_DATAMART_V_MUC.csv?snapshot=2022-05-20T05%3A41%3A12.7183906Z"}]}]}