{"name":"obs_Flow_Cumulus_Cleaning","description":"Obsolete.\nFlow for Cumulus data of cleaning topics, e.g. EMO data, cleaning inspection CR and EMO.","version":"1.0","culture":"en-US","modifiedTime":"2022-05-31T18:03:56.7616428+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"CleaningInspection CR old":{"queryId":"d7d40dd7-14ff-42a7-8445-94f5180d135e","queryName":"CleaningInspection CR old","queryGroupId":"81a05464-3133-407d-b3fc-b4cb675b79c7"},"Sample file (2)":{"queryId":"72631502-f0e5-4681-b3c4-0f8d9fef3937","queryName":"Sample file (2)","queryGroupId":"69728958-a3c0-46e5-88f5-7b17fbcfe3f0"},"Parameter (2)":{"queryId":"1e20e8d9-f376-454a-a2e0-06ff2acc8c0f","queryName":"Parameter (2)","queryGroupId":"69728958-a3c0-46e5-88f5-7b17fbcfe3f0"},"Transform Sample file (2)":{"queryId":"eb9f43d0-c5ac-4965-a65a-b4e7e2a9b2c9","queryName":"Transform Sample file (2)","queryGroupId":"f6077aa3-4918-45b1-8b1f-80fcfbbb38f9"},"Transform file (2)":{"queryId":"996b758d-76c5-404d-9907-018c72f9f510","queryName":"Transform file (2)","queryGroupId":"69728958-a3c0-46e5-88f5-7b17fbcfe3f0"},"CleaningInspection CR":{"queryId":"8687f130-e71f-4602-8050-bf50155bb1c0","queryName":"CleaningInspection CR"},"Sample file":{"queryId":"fc65be64-1fb4-4f78-b39c-19be87ce6ec2","queryName":"Sample file","queryGroupId":"6ab2c6ba-fd03-4622-8269-d9301bd85e62"},"Parameter":{"queryId":"60e877ab-a5e9-4661-bac7-c07330bf8cb1","queryName":"Parameter","queryGroupId":"6ab2c6ba-fd03-4622-8269-d9301bd85e62"},"Transform Sample file":{"queryId":"86418468-3600-41e6-b389-8e8b89b6e288","queryName":"Transform Sample file","queryGroupId":"dc867e03-17c3-478b-a13c-52eb12aea3ef"},"Transform file":{"queryId":"db2e0cbf-9c6e-4d3e-ab40-06224691445a","queryName":"Transform file","queryGroupId":"6ab2c6ba-fd03-4622-8269-d9301bd85e62"},"PreCleaningInspection_EMO":{"queryId":"2d193c70-42fe-4225-84c9-8b335f4d04b7","queryName":"PreCleaningInspection_EMO","loadEnabled":true},"CleaningHistory":{"queryId":"59c4b063-bde0-4fc3-9996-954b454a097b","queryName":"CleaningHistory","queryGroupId":"81a05464-3133-407d-b3fc-b4cb675b79c7"},"Sample file (3)":{"queryId":"0066ee98-31a2-48b9-9d35-b015bd6f5808","queryName":"Sample file (3)","queryGroupId":"7f1c3388-b9cf-45f7-a7fc-685f61a82905"},"Parameter (3)":{"queryId":"33f1fb0d-025d-4f86-ae09-ab8a5be29887","queryName":"Parameter (3)","queryGroupId":"7f1c3388-b9cf-45f7-a7fc-685f61a82905"},"Transform Sample file (3)":{"queryId":"0efb3912-e5ea-4ddc-989d-fe4145a28d98","queryName":"Transform Sample file (3)","queryGroupId":"8186dd21-5598-440e-91ff-e6bb7a7495e3"},"Transform file (3)":{"queryId":"d2143237-8ce4-4af5-a4d7-07e99169de7e","queryName":"Transform file (3)","queryGroupId":"7f1c3388-b9cf-45f7-a7fc-685f61a82905"},"Sample file (4)":{"queryId":"361fc05d-7bd3-49fa-8adf-f985ccfc3902","queryName":"Sample file (4)","queryGroupId":"1db40640-80e8-4765-bb12-9f31e7160ccf"},"Parameter (4)":{"queryId":"0c0e3a51-ab15-48b1-8a1a-279fcf8a4c52","queryName":"Parameter (4)","queryGroupId":"1db40640-80e8-4765-bb12-9f31e7160ccf"},"Transform Sample file (4)":{"queryId":"d2ab4500-e191-4b60-92ef-124f2396dc5d","queryName":"Transform Sample file (4)","queryGroupId":"6b6e1842-beba-4c1e-aec5-b676c91b7e01"},"Transform file (4)":{"queryId":"1809c4c4-261b-4644-b8ea-0145e6b98b8f","queryName":"Transform file (4)","queryGroupId":"1db40640-80e8-4765-bb12-9f31e7160ccf"},"fCSV_FileName_CleaningInspection":{"queryId":"5afc8ba9-b94a-40de-a506-7c32ce603b89","queryName":"fCSV_FileName_CleaningInspection"},"CleaningInspectionCR_CSV":{"queryId":"449fe0d5-9791-466a-8f7a-28451c893f43","queryName":"CleaningInspectionCR_CSV","loadEnabled":true},"CleaningInspectionCR_CSV_CountRowsFiles":{"queryId":"9873ef89-31bc-4be3-b9dd-83c0c2ac81fd","queryName":"CleaningInspectionCR_CSV_CountRowsFiles"},"CleaningInspectionCR_CSV2":{"queryId":"eed99492-dbb2-4618-923c-e025202d8e72","queryName":"CleaningInspectionCR_CSV2"},"Sample file (5)":{"queryId":"d1f90e94-d412-45af-809f-ac721a2e63b4","queryName":"Sample file (5)","queryGroupId":"9d8bbfdb-3e6e-4d4c-8685-edda6e5bbfc9"},"Parameter (5)":{"queryId":"9a31ee5f-ad14-474a-99f6-dce7af1ef341","queryName":"Parameter (5)","queryGroupId":"9d8bbfdb-3e6e-4d4c-8685-edda6e5bbfc9"},"Transform Sample file (5)":{"queryId":"eec81fa7-efd5-4188-afa7-22cabbfb86c2","queryName":"Transform Sample file (5)","queryGroupId":"184d830d-6213-40b6-80d2-197c17657521"},"Transform file (5)":{"queryId":"91839ca3-5e58-462c-b185-efb3d0fdb989","queryName":"Transform file (5)","queryGroupId":"9d8bbfdb-3e6e-4d4c-8685-edda6e5bbfc9"},"RangeStart":{"queryId":"941ff042-bed4-451d-b5b5-41a64a947de9","queryName":"RangeStart"},"RangeEnd":{"queryId":"0a253c2d-20bf-4e5e-8b98-a9f7a60a30e6","queryName":"RangeEnd"}},"document":"section Section1;\r\n\r\nshared #\"CleaningInspection CR old\" = let\r\n    Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n    #\"Filtered rows\" = Table.SelectRows(Source, each [Name] = \"GEP_CleaningInspection.xlsx\" or [Name] = \"KEP_CleaningInspection.xlsx\"),\r\n    #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows\", each [Attributes]?[Hidden]? <> true),\r\n    #\"Invoke custom function\" = Table.AddColumn(#\"Filtered hidden files\", \"Transform file (2)\", each #\"Transform file (2)\"([Content])),\r\n    #\"Renamed columns\" = Table.RenameColumns(#\"Invoke custom function\", {{\"Name\", \"Source.Name\"}}),\r\n    #\"Removed other columns\" = Table.SelectColumns(#\"Renamed columns\", {\"Source.Name\", \"Transform file (2)\"}),\r\n    #\"Expanded table column\" = Table.ExpandTableColumn(#\"Removed other columns\", \"Transform file (2)\", Table.ColumnNames(#\"Transform file (2)\"(#\"Sample file (2)\"))),\r\n    #\"Changed column type\" = Table.TransformColumnTypes(#\"Expanded table column\", {{\"Source.Name\", type text}, {\"Date\", type text}, {\"Name\", type text}, {\"Org\", type text}, {\"Oracle Job\", type text}, {\"Cumulus WO\", type text}, {\"Part Number\", type text}, {\"Description\", type text}, {\"Qty\", Int64.Type}, {\"R\", type text}, {\"Gas Contact\", type text}, {\"Wipe Test OK\", type number}, {\"Wipe Test SOK\", type number}, {\"Wipe Test NOK\", type number}, {\"Ink Test 56\", type number}, {\"Ink Test 48\", type number}, {\"Ink Test 44\", type number}, {\"Visual Inspection OK\", type number}, {\"Visual Inspection NOK\", type number}, {\"Cause\", type text}, {\"Fixed\", type text}, {\"Fixed By\", type text}, {\"Remarks\", type text}, {\"Serial Number\", type text}}),\r\n    #\"Changed column type with locale\" = Table.TransformColumnTypes(#\"Changed column type\", {{\"Date\", type date}}, \"de-DE\")\r\nin\r\n    #\"Changed column type with locale\";\r\n\r\nshared #\"Sample file (2)\" = let\r\n    Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n    #\"Filtered rows\" = Table.SelectRows(Source, each [Name] = \"GEP_CleaningInspection.xlsx\" or [Name] = \"KEP_CleaningInspection.xlsx\"),\r\n    #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows\", each [Attributes]?[Hidden]? <> true),\r\n    Navigation = #\"Filtered hidden files\"{0}[Content]\r\nin\r\n    Navigation;\r\n\r\nshared #\"Parameter (2)\" = let\r\n    #\"Parameter (2)\" = #\"Sample file (2)\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type binary]\r\nin\r\n    #\"Parameter (2)\";\r\n\r\nshared #\"Transform Sample file (2)\" = let\r\n    Source = Excel.Workbook(#\"Parameter (2)\", null, true),\r\n    Navigation = Source{[Item = \"Table1\", Kind = \"Sheet\"]}[Data],\r\n    #\"Promoted headers\" = Table.PromoteHeaders(Navigation, [PromoteAllScalars = true]),\r\n    #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"Date\", type text}, {\"Name\", type text}, {\"Org\", type text}, {\"Oracle Job\", type text}, {\"Cumulus WO\", Int64.Type}, {\"Part Number\", type any}, {\"Description\", type text}, {\"Qty\", Int64.Type}, {\"R\", type text}, {\"Gas Contact\", type text}, {\"Wipe Test OK\", Int64.Type}, {\"Wipe Test SOK\", Int64.Type}, {\"Wipe Test NOK\", type any}, {\"Ink Test 56\", type any}, {\"Ink Test 48\", type any}, {\"Ink Test 44\", type any}, {\"Visual Inspection OK\", Int64.Type}, {\"Visual Inspection NOK\", type any}, {\"Cause\", type any}, {\"Fixed\", type any}, {\"Fixed By\", type any}, {\"Remarks\", type any}, {\"Serial Number\", type text}})\r\nin\r\n    #\"Changed column type\";\r\n\r\nshared #\"Transform file (2)\" = let\r\n    Source = (#\"Parameter (2)\" as binary) => let\r\n    Source = Excel.Workbook(#\"Parameter (2)\", null, true),\r\n    Navigation = Source{[Item = \"Table1\", Kind = \"Sheet\"]}[Data],\r\n    #\"Promoted headers\" = Table.PromoteHeaders(Navigation, [PromoteAllScalars = true]),\r\n    #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"Date\", type text}, {\"Name\", type text}, {\"Org\", type text}, {\"Oracle Job\", type text}, {\"Cumulus WO\", Int64.Type}, {\"Part Number\", type any}, {\"Description\", type text}, {\"Qty\", Int64.Type}, {\"R\", type text}, {\"Gas Contact\", type text}, {\"Wipe Test OK\", Int64.Type}, {\"Wipe Test SOK\", Int64.Type}, {\"Wipe Test NOK\", type any}, {\"Ink Test 56\", type any}, {\"Ink Test 48\", type any}, {\"Ink Test 44\", type any}, {\"Visual Inspection OK\", Int64.Type}, {\"Visual Inspection NOK\", type any}, {\"Cause\", type any}, {\"Fixed\", type any}, {\"Fixed By\", type any}, {\"Remarks\", type any}, {\"Serial Number\", type text}})\r\nin\r\n    #\"Changed column type\"\r\nin\r\n    Source;\r\n\r\nshared #\"CleaningInspection CR\" = let\r\n    Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n    #\"Filtered rows\" = Table.SelectRows(Source, each [Extension] = \".csv\"),\r\n    #\"Filtered rows 1\" = Table.SelectRows(#\"Filtered rows\", each Text.Contains([Name], \"GEP_CleaningInspection_GEP\") or Text.Contains([Name], \"KEP_CleaningInspection_GEP\") and not Text.Contains([Name], \"Pre\")),\r\n    #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows 1\", each [Attributes]?[Hidden]? <> true),\r\n    #\"Invoke custom function\" = Table.AddColumn(#\"Filtered hidden files\", \"Transform file\", each #\"Transform file\"([Content])),\r\n    #\"Renamed columns\" = Table.RenameColumns(#\"Invoke custom function\", {{\"Name\", \"Source.Name\"}}),\r\n    #\"Removed other columns\" = Table.SelectColumns(#\"Renamed columns\", {\"Source.Name\", \"Transform file\"}),\r\n    #\"Expanded table column\" = Table.ExpandTableColumn(#\"Removed other columns\", \"Transform file\", Table.ColumnNames(#\"Transform file\"(#\"Sample file\"))),\r\n    #\"Changed column type\" = Table.TransformColumnTypes(#\"Expanded table column\", {{\"Source.Name\", type text}, {\"Date\", type text}, {\"Name\", type text}, {\"Org\", type text}, {\"Oracle Job\", type text}, {\"Cumulus WO\", type text}, {\"Part Number\", type text}, {\"Description\", type text}, {\"Qty\", Int64.Type}, {\"R\", type text}, {\"Gas Contact\", type text}, {\"Wipe Test OK\", Int64.Type}, {\"Wipe Test SOK\", Int64.Type}, {\"Wipe Test NOK\", Int64.Type}, {\"Ink Test 56\", Int64.Type}, {\"Ink Test 48\", Int64.Type}, {\"Ink Test 44\", Int64.Type}, {\"Visual Inspection OK\", Int64.Type}, {\"Visual Inspection NOK\", Int64.Type}, {\"Cause\", type text}, {\"Fixed\", type text}, {\"Fixed By\", type text}, {\"Remarks\", type text}, {\"Serial Number\", type text}}),\r\n    #\"Choose columns\" = Table.SelectColumns(#\"Changed column type\", {\"Date\", \"Name\", \"Org\", \"Oracle Job\", \"Cumulus WO\", \"Part Number\", \"Qty\", \"R\", \"Gas Contact\", \"Wipe Test OK\", \"Wipe Test SOK\", \"Wipe Test NOK\", \"Ink Test 56\", \"Ink Test 48\", \"Ink Test 44\", \"Visual Inspection OK\", \"Visual Inspection NOK\", \"Cause\", \"Fixed\", \"Fixed By\", \"Remarks\", \"Serial Number\"}),\r\n    #\"Changed column type with locale\" = Table.TransformColumnTypes(#\"Choose columns\", {{\"Date\", type date}}, \"de-DE\")\r\nin\r\n    #\"Changed column type with locale\";\r\n\r\nshared #\"Sample file\" = let\r\n    Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n    #\"Filtered rows\" = Table.SelectRows(Source, each [Extension] = \".csv\"),\r\n    #\"Filtered rows 1\" = Table.SelectRows(#\"Filtered rows\", each Text.Contains([Name], \"CleaningInspection\")),\r\n    #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows 1\", each [Attributes]?[Hidden]? <> true),\r\n    Navigation = #\"Filtered hidden files\"{0}[Content]\r\nin\r\n    Navigation;\r\n\r\nshared Parameter = let\r\n    Parameter = #\"Sample file\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type binary]\r\nin\r\n    Parameter;\r\n\r\nshared #\"Transform Sample file\" = let\r\n    Source = Csv.Document(Parameter, [Delimiter = \";\", Columns = 23, QuoteStyle = QuoteStyle.None]),\r\n    #\"Promoted headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),\r\n    #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"Date\", type date}, {\"Name\", type text}, {\"Org\", type text}, {\"Oracle Job\", type text}, {\"Cumulus WO\", Int64.Type}, {\"Part Number\", type text}, {\"Description\", type text}, {\"Qty\", Int64.Type}, {\"R\", type text}, {\"Gas Contact\", type text}, {\"Wipe Test OK\", Int64.Type}, {\"Wipe Test SOK\", Int64.Type}, {\"Wipe Test NOK\", Int64.Type}, {\"Ink Test 56\", Int64.Type}, {\"Ink Test 48\", Int64.Type}, {\"Ink Test 44\", Int64.Type}, {\"Visual Inspection OK\", Int64.Type}, {\"Visual Inspection NOK\", Int64.Type}, {\"Cause\", type text}, {\"Fixed\", type text}, {\"Fixed By\", type text}, {\"Remarks\", type text}, {\"Serial Number\", type text}})\r\nin\r\n    #\"Changed column type\";\r\n\r\nshared #\"Transform file\" = let\r\n    Source = (Parameter as binary) => let\r\n    Source = Csv.Document(Parameter, [Delimiter = \";\", Columns = 23, QuoteStyle = QuoteStyle.None]),\r\n    #\"Promoted headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),\r\n    #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"Date\", type text}, {\"Name\", type text}, {\"Org\", type text}, {\"Oracle Job\", type text}, {\"Cumulus WO\", Int64.Type}, {\"Part Number\", type text}, {\"Description\", type text}, {\"Qty\", Int64.Type}, {\"R\", type text}, {\"Gas Contact\", type text}, {\"Wipe Test OK\", Int64.Type}, {\"Wipe Test SOK\", Int64.Type}, {\"Wipe Test NOK\", Int64.Type}, {\"Ink Test 56\", Int64.Type}, {\"Ink Test 48\", Int64.Type}, {\"Ink Test 44\", Int64.Type}, {\"Visual Inspection OK\", Int64.Type}, {\"Visual Inspection NOK\", Int64.Type}, {\"Cause\", type text}, {\"Fixed\", type text}, {\"Fixed By\", type text}, {\"Remarks\", type text}, {\"Serial Number\", type text}})\r\nin\r\n    #\"Changed column type\"\r\nin\r\n    Source;\r\n\r\nshared CleaningHistory = let\r\n    Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n    #\"Filtered rows\" = Table.SelectRows(Source, each [Name] = \"1_HistoryCleaningInsp_2020Nov.xlsx\"),\r\n    #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows\", each [Attributes]?[Hidden]? <> true),\r\n    #\"Invoke custom function\" = Table.AddColumn(#\"Filtered hidden files\", \"Transform file (3)\", each #\"Transform file (3)\"([Content])),\r\n    #\"Renamed columns\" = Table.RenameColumns(#\"Invoke custom function\", {{\"Name\", \"Source.Name\"}}),\r\n    #\"Removed other columns\" = Table.SelectColumns(#\"Renamed columns\", {\"Source.Name\", \"Transform file (3)\"}),\r\n    #\"Expanded table column\" = Table.ExpandTableColumn(#\"Removed other columns\", \"Transform file (3)\", Table.ColumnNames(#\"Transform file (3)\"(#\"Sample file (3)\"))),\r\n    #\"Changed column type\" = Table.TransformColumnTypes(#\"Expanded table column\", {{\"Source.Name\", type text}, {\"Date\", type text}, {\"Name\", type text}, {\"Org\", type text}, {\"Oracle Job\", type text}, {\"Cumulus WO\", Int64.Type}, {\"Part Number\", type text}, {\"Description\", type text}, {\"Qty\", Int64.Type}, {\"R\", type text}, {\"Gas Contact\", type text}, {\"Wipe Test OK\", Int64.Type}, {\"Wipe Test SOK\", Int64.Type}, {\"Wipe Test NOK\", Int64.Type}, {\"Ink Test 56\", Int64.Type}, {\"Ink Test 48\", Int64.Type}, {\"Ink Test 44\", Int64.Type}, {\"Visual Inspection OK\", Int64.Type}, {\"Visual Inspection NOK\", Int64.Type}, {\"Cause\", type text}, {\"Fixed\", type text}, {\"Fixed By\", type text}, {\"Remarks\", type text}, {\"Serial Number\", type text}}),\r\n    #\"Changed column type with locale\" = Table.TransformColumnTypes(#\"Changed column type\", {{\"Date\", type date}}, \"en-US\"),\r\n    #\"Choose columns\" = Table.SelectColumns(#\"Changed column type with locale\", {\"Date\", \"Name\", \"Org\", \"Oracle Job\", \"Cumulus WO\", \"Part Number\", \"Description\", \"Qty\", \"R\", \"Gas Contact\", \"Wipe Test OK\", \"Wipe Test SOK\", \"Wipe Test NOK\", \"Ink Test 56\", \"Ink Test 48\", \"Ink Test 44\", \"Visual Inspection OK\", \"Visual Inspection NOK\", \"Cause\", \"Fixed\", \"Fixed By\", \"Remarks\", \"Serial Number\"}),\r\n    #\"Choose columns 1\" = Table.SelectColumns(#\"Choose columns\", {\"Date\", \"Name\", \"Org\", \"Oracle Job\", \"Cumulus WO\", \"Part Number\", \"Qty\", \"R\", \"Gas Contact\", \"Wipe Test OK\", \"Wipe Test SOK\", \"Wipe Test NOK\", \"Ink Test 56\", \"Ink Test 48\", \"Ink Test 44\", \"Visual Inspection OK\", \"Visual Inspection NOK\", \"Cause\", \"Fixed\", \"Fixed By\", \"Remarks\", \"Serial Number\"})\r\nin\r\n    #\"Choose columns 1\";\r\n\r\nshared #\"Sample file (3)\" = let\r\n    Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n    #\"Filtered rows\" = Table.SelectRows(Source, each [Name] = \"1_HistoryCleaningInsp_2020Nov.xlsx\"),\r\n    #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows\", each [Attributes]?[Hidden]? <> true),\r\n    Navigation = #\"Filtered hidden files\"{0}[Content]\r\nin\r\n    Navigation;\r\n\r\nshared #\"Parameter (3)\" = let\r\n    #\"Parameter (3)\" = #\"Sample file (3)\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type binary]\r\nin\r\n    #\"Parameter (3)\";\r\n\r\nshared #\"Transform Sample file (3)\" = let\r\n    Source = Excel.Workbook(#\"Parameter (3)\", null, true),\r\n    Navigation = Source{[Item = \"tblCLhistory\", Kind = \"Table\"]}[Data],\r\n    #\"Changed column type\" = Table.TransformColumnTypes(Navigation, {{\"Date\", type text}, {\"Name\", type text}, {\"Org\", type text}, {\"Oracle Job\", type text}, {\"Cumulus WO\", Int64.Type}, {\"Part Number\", type text}, {\"Description\", type text}, {\"Qty\", Int64.Type}, {\"R\", type text}, {\"Gas Contact\", type text}, {\"Wipe Test OK\", Int64.Type}, {\"Wipe Test SOK\", Int64.Type}, {\"Wipe Test NOK\", type any}, {\"Ink Test 56\", type any}, {\"Ink Test 48\", type any}, {\"Ink Test 44\", type any}, {\"Visual Inspection OK\", Int64.Type}, {\"Visual Inspection NOK\", type any}, {\"Cause\", type text}, {\"Fixed\", type text}, {\"Fixed By\", type text}, {\"Remarks\", type text}, {\"Serial Number\", type text}})\r\nin\r\n    #\"Changed column type\";\r\n\r\nshared #\"Transform file (3)\" = let\r\n    Source = (#\"Parameter (3)\" as binary) => let\r\n    Source = Excel.Workbook(#\"Parameter (3)\", null, true),\r\n    Navigation = Source{[Item = \"tblCLhistory\", Kind = \"Table\"]}[Data],\r\n    #\"Changed column type\" = Table.TransformColumnTypes(Navigation, {{\"Date\", type text}, {\"Name\", type text}, {\"Org\", type text}, {\"Oracle Job\", type text}, {\"Cumulus WO\", Int64.Type}, {\"Part Number\", type text}, {\"Description\", type text}, {\"Qty\", Int64.Type}, {\"R\", type text}, {\"Gas Contact\", type text}, {\"Wipe Test OK\", Int64.Type}, {\"Wipe Test SOK\", Int64.Type}, {\"Wipe Test NOK\", type any}, {\"Ink Test 56\", type any}, {\"Ink Test 48\", type any}, {\"Ink Test 44\", type any}, {\"Visual Inspection OK\", Int64.Type}, {\"Visual Inspection NOK\", type any}, {\"Cause\", type text}, {\"Fixed\", type text}, {\"Fixed By\", type text}, {\"Remarks\", type text}, {\"Serial Number\", type text}})\r\nin\r\n    #\"Changed column type\"\r\nin\r\n    Source;\r\n\r\nshared #\"Sample file (4)\" = let\r\n    Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n    #\"Filtered rows\" = Table.SelectRows(Source, each [Extension] = \".csv\"),\r\n    #\"Filtered rows 1\" = Table.SelectRows(#\"Filtered rows\", each Text.Contains([Name], \"GEP_PreCleaningInspection_GEP\") or Text.Contains([Name], \"KEP_PreCleaningInspection_GEP\") and not Text.Contains([Name], \"Pre\")),\r\n    #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows 1\", each [Attributes]?[Hidden]? <> true),\r\n    #\"Filtered hidden files 1\" = Table.SelectRows(#\"Filtered hidden files\", each [Attributes]?[Hidden]? <> true),\r\n    Navigation = #\"Filtered hidden files 1\"{[#\"Folder Path\" = \"https://cohrinc.sharepoint.com/teams/Operations/Excimer-Göttingen/Manuf. Engineering/Shared Documents/Production Data/VHP/Datapoints CR/Cleaning/\", Name = \"GEP_PreCleaningInspection_GEP-1229195R-15933.csv\"]}[Content]\r\nin\r\n    Navigation;\r\n\r\nshared #\"Parameter (4)\" = let\r\n    #\"Parameter (4)\" = #\"Sample file (4)\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type binary]\r\nin\r\n    #\"Parameter (4)\";\r\n\r\nshared #\"Transform Sample file (4)\" = let\r\n    Source = Csv.Document(#\"Parameter (4)\", [Delimiter = \";\", Columns = 20, Encoding = 65001, QuoteStyle = QuoteStyle.None]),\r\n    #\"Promoted headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),\r\n    #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"Date\", type text}, {\"Name\", type text}, {\"Org\", type text}, {\"Oracle Job\", type text}, {\"Cumulus WO\", type text}, {\"Part Number\", type text}, {\"Description\", type text}, {\"Qty\", Int64.Type}, {\"R\", type text}, {\"Gas Contact\", type text}, {\"Inspection OK\", Int64.Type}, {\"Inspection SOK\", Int64.Type}, {\"Inspection NOK\", Int64.Type}, {\"Label USB Cleaned\", Int64.Type}, {\"Label Wipe Test\", Int64.Type}, {\"Cause\", type text}, {\"Fixed\", type text}, {\"Fixed By\", type text}, {\"Remarks\", type text}, {\"Serial Number\", type text}})\r\nin\r\n    #\"Changed column type\";\r\n\r\nshared #\"Transform file (4)\" = let\r\n    Source = (#\"Parameter (4)\" as binary) => let\r\n    Source = Csv.Document(#\"Parameter (4)\", [Delimiter = \";\", Columns = 20, Encoding = 65001, QuoteStyle = QuoteStyle.None]),\r\n    #\"Promoted headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),\r\n    #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"Date\", type text}, {\"Name\", type text}, {\"Org\", type text}, {\"Oracle Job\", type text}, {\"Cumulus WO\", type text}, {\"Part Number\", type text}, {\"Description\", type text}, {\"Qty\", Int64.Type}, {\"R\", type text}, {\"Gas Contact\", type text}, {\"Inspection OK\", Int64.Type}, {\"Inspection SOK\", Int64.Type}, {\"Inspection NOK\", Int64.Type}, {\"Label USB Cleaned\", type text}, {\"Label Wipe Test\", type text}, {\"Cause\", type text}, {\"Fixed\", type text}, {\"Fixed By\", type text}, {\"Remarks\", type text}, {\"Serial Number\", type text}})\r\nin\r\n    #\"Changed column type\"\r\nin\r\n    Source;\r\n\r\nshared fCSV_FileName_CleaningInspection = let\r\n    fCSV_FileName_CleaningInspection = (FileName as text) =>\r\n    let\r\n    Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n    Navigation = Source{[Name = FileName, #\"Folder Path\" = \"https://cohrinc.sharepoint.com/teams/Operations/Excimer-Göttingen/Manuf. Engineering/Shared Documents/Production Data/VHP/Datapoints CR/Cleaning/\"]}[Content],\r\n    #\"Imported CSV\" = Csv.Document(Navigation, [Delimiter = \";\", Columns = 23, QuoteStyle = QuoteStyle.None]),\r\n    #\"Promoted headers\" = Table.PromoteHeaders(#\"Imported CSV\", [PromoteAllScalars = true])\r\nin\r\n    #\"Promoted headers\"\r\nin\r\n    fCSV_FileName_CleaningInspection;\r\n\r\nshared CleaningInspectionCR_CSV_CountRowsFiles = let\r\n    Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n    #\"Filtered rows\" = Table.SelectRows(Source, each [Extension] = \".csv\"),\r\n    #\"Filtered rows 1\" = Table.SelectRows(#\"Filtered rows\", each Text.Contains([Name], \"GEP_CleaningInspection_GEP\") or Text.Contains([Name], \"KEP_CleaningInspection_GEP\") and not Text.Contains([Name], \"Pre\")),\r\n    #\"Counted rows\" = Table.RowCount(#\"Filtered rows 1\")\r\nin\r\n    #\"Counted rows\";\r\n\r\nshared CleaningInspectionCR_CSV2 = let\r\n    Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n    #\"Filtered rows\" = Table.SelectRows(Source, each [Extension] = \".csv\"),\r\n    #\"Filtered rows 1\" = Table.SelectRows(#\"Filtered rows\", each Text.Contains([Name], \"GEP_CleaningInspection_GEP\") or Text.Contains([Name], \"KEP_CleaningInspection_GEP\") and not Text.Contains([Name], \"Pre\")),\r\n    #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows 1\", each [Attributes]?[Hidden]? <> true),\r\n    #\"Invoke custom function\" = Table.AddColumn(#\"Filtered hidden files\", \"Transform file (5)\", each #\"Transform file (5)\"([Content])),\r\n    #\"Renamed columns\" = Table.RenameColumns(#\"Invoke custom function\", {{\"Name\", \"Source.Name\"}}),\r\n    #\"Removed other columns\" = Table.SelectColumns(#\"Renamed columns\", {\"Source.Name\", \"Transform file (5)\"}),\r\n    #\"Expanded table column\" = Table.ExpandTableColumn(#\"Removed other columns\", \"Transform file (5)\", Table.ColumnNames(#\"Transform file (5)\"(#\"Sample file (5)\"))),\r\n    #\"Changed column type\" = Table.TransformColumnTypes(#\"Expanded table column\", {{\"Source.Name\", type text}, {\"Date\", type text}, {\"Name\", type text}, {\"Org\", type text}, {\"Oracle Job\", type text}, {\"Cumulus WO\", Int64.Type}, {\"Part Number\", type text}, {\"Description\", type text}, {\"Qty\", Int64.Type}, {\"R\", type text}, {\"Gas Contact\", type text}, {\"Wipe Test OK\", Int64.Type}, {\"Wipe Test SOK\", Int64.Type}, {\"Wipe Test NOK\", Int64.Type}, {\"Ink Test 56\", Int64.Type}, {\"Ink Test 48\", Int64.Type}, {\"Ink Test 44\", Int64.Type}, {\"Visual Inspection OK\", Int64.Type}, {\"Visual Inspection NOK\", Int64.Type}, {\"Cause\", type text}, {\"Fixed\", type text}, {\"Fixed By\", type text}, {\"Remarks\", type text}, {\"Serial Number\", type text}})\r\nin\r\n    #\"Changed column type\";\r\n\r\nshared #\"Sample file (5)\" = let\r\n    Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n    #\"Filtered rows\" = Table.SelectRows(Source, each [Extension] = \".csv\"),\r\n    #\"Filtered rows 1\" = Table.SelectRows(#\"Filtered rows\", each Text.Contains([Name], \"GEP_CleaningInspection_GEP\") or Text.Contains([Name], \"KEP_CleaningInspection_GEP\") and not Text.Contains([Name], \"Pre\")),\r\n    #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows 1\", each [Attributes]?[Hidden]? <> true),\r\n    Navigation = #\"Filtered hidden files\"{0}[Content]\r\nin\r\n    Navigation;\r\n\r\nshared #\"Parameter (5)\" = let\r\n    #\"Parameter (5)\" = #\"Sample file (5)\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type binary, BinaryIdentifier = #\"Sample file (5)\"]\r\nin\r\n    #\"Parameter (5)\";\r\n\r\nshared #\"Transform Sample file (5)\" = let\r\n    Source = Csv.Document(#\"Parameter (5)\", [Delimiter = \";\", Columns = 23, QuoteStyle = QuoteStyle.None]),\r\n    #\"Promoted headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),\r\n    #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"Date\", type text}, {\"Name\", type text}, {\"Org\", type text}, {\"Oracle Job\", type text}, {\"Cumulus WO\", Int64.Type}, {\"Part Number\", type text}, {\"Description\", type text}, {\"Qty\", Int64.Type}, {\"R\", type text}, {\"Gas Contact\", type text}, {\"Wipe Test OK\", Int64.Type}, {\"Wipe Test SOK\", Int64.Type}, {\"Wipe Test NOK\", Int64.Type}, {\"Ink Test 56\", Int64.Type}, {\"Ink Test 48\", Int64.Type}, {\"Ink Test 44\", Int64.Type}, {\"Visual Inspection OK\", Int64.Type}, {\"Visual Inspection NOK\", Int64.Type}, {\"Cause\", type text}, {\"Fixed\", type text}, {\"Fixed By\", type text}, {\"Remarks\", type text}, {\"Serial Number\", type text}})\r\nin\r\n    #\"Changed column type\";\r\n\r\nshared #\"Transform file (5)\" = let\r\n    Source = (#\"Parameter (5)\" as binary) => let\r\n    Source = Csv.Document(#\"Parameter (5)\", [Delimiter = \";\", Columns = 23, QuoteStyle = QuoteStyle.None]),\r\n    #\"Promoted headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),\r\n    #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"Date\", type text}, {\"Name\", type text}, {\"Org\", type text}, {\"Oracle Job\", type text}, {\"Cumulus WO\", Int64.Type}, {\"Part Number\", type text}, {\"Description\", type text}, {\"Qty\", Int64.Type}, {\"R\", type text}, {\"Gas Contact\", type text}, {\"Wipe Test OK\", Int64.Type}, {\"Wipe Test SOK\", Int64.Type}, {\"Wipe Test NOK\", Int64.Type}, {\"Ink Test 56\", Int64.Type}, {\"Ink Test 48\", Int64.Type}, {\"Ink Test 44\", Int64.Type}, {\"Visual Inspection OK\", Int64.Type}, {\"Visual Inspection NOK\", Int64.Type}, {\"Cause\", type text}, {\"Fixed\", type text}, {\"Fixed By\", type text}, {\"Remarks\", type text}, {\"Serial Number\", type text}})\r\nin\r\n    #\"Changed column type\"\r\nin\r\n    Source;\r\n\r\nshared CleaningInspectionCR_CSV = let\r\n    Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n    #\"Filtered rows 2\" = Table.SelectRows(Source, each Text.Contains([Folder Path], \"Cleaning\")),\r\n    #\"Filtered rows\" = Table.SelectRows(#\"Filtered rows 2\", each [Extension] = \".csv\"),\r\n    #\"Filtered rows 1\" = Table.SelectRows(#\"Filtered rows\", each Text.Contains([Name], \"GEP_CleaningInspection_GEP\") or Text.Contains([Name], \"KEP_CleaningInspection_GEP\") and not Text.Contains([Name], \"Pre\")),\r\n    #\"Invoked custom function\" = Table.AddColumn(#\"Filtered rows 1\", \"fCSV_FileName\", each fCSV_FileName_CleaningInspection([Name])),\r\n    #\"Removed other columns\" = Table.SelectColumns(#\"Invoked custom function\", {\"fCSV_FileName\"}),\r\n    #\"Expanded fCSV_FileName\" = Table.ExpandTableColumn(#\"Removed other columns\", \"fCSV_FileName\", {\"Date\", \"Name\", \"Org\", \"Oracle Job\", \"Cumulus WO\", \"Part Number\", \"Description\", \"Qty\", \"R\", \"Gas Contact\", \"Wipe Test OK\", \"Wipe Test SOK\", \"Wipe Test NOK\", \"Ink Test 56\", \"Ink Test 48\", \"Ink Test 44\", \"Visual Inspection OK\", \"Visual Inspection NOK\", \"Cause\", \"Fixed\", \"Fixed By\", \"Remarks\", \"Serial Number\"}, {\"Date\", \"Name\", \"Org\", \"Oracle Job\", \"Cumulus WO\", \"Part Number\", \"Description\", \"Qty\", \"R\", \"Gas Contact\", \"Wipe Test OK\", \"Wipe Test SOK\", \"Wipe Test NOK\", \"Ink Test 56\", \"Ink Test 48\", \"Ink Test 44\", \"Visual Inspection OK\", \"Visual Inspection NOK\", \"Cause\", \"Fixed\", \"Fixed By\", \"Remarks\", \"Serial Number\"}),\r\n    #\"Changed column type\" = Table.TransformColumnTypes(#\"Expanded fCSV_FileName\", {{\"Name\", type text}, {\"Org\", type text}, {\"Oracle Job\", type text}, {\"Cumulus WO\", type text}, {\"Part Number\", type text}, {\"Description\", type text}, {\"R\", type text}, {\"Gas Contact\", type text}, {\"Cause\", type text}, {\"Fixed\", type text}, {\"Fixed By\", type text}, {\"Remarks\", type text}, {\"Serial Number\", type text}, {\"Qty\", Int64.Type}, {\"Wipe Test OK\", Int64.Type}, {\"Wipe Test SOK\", Int64.Type}, {\"Wipe Test NOK\", Int64.Type}, {\"Ink Test 56\", Int64.Type}, {\"Ink Test 48\", Int64.Type}, {\"Ink Test 44\", Int64.Type}, {\"Visual Inspection OK\", Int64.Type}, {\"Visual Inspection NOK\", Int64.Type}}),\r\n    #\"Changed column type with locale\" = Table.TransformColumnTypes(#\"Changed column type\", {{\"Date\", type datetime}}, \"de-DE\"),\r\n    #\"CleaningInspectionCR_CSV-44617465-autogenerated_for_incremental_refresh\" = Table.SelectRows(#\"Changed column type with locale\", each DateTime.From([Date]) >= RangeStart and DateTime.From([Date]) < RangeEnd)\r\nin\r\n    #\"CleaningInspectionCR_CSV-44617465-autogenerated_for_incremental_refresh\";\r\n\r\nshared RangeStart = let RangeStart = #datetime(0001,01,01,00,00,00) meta [IsParameterQuery=true, List={}, Type=\"DateTime\", IsParameterQueryRequired=true, Description=\"autogenerated_for_incremental_refresh\"] in RangeStart;\r\n\r\nshared RangeEnd = let RangeEnd = #datetime(9999,12,31,23,59,59) meta [IsParameterQuery=true, List={}, Type=\"DateTime\", IsParameterQueryRequired=true, Description=\"autogenerated_for_incremental_refresh\"] in RangeEnd;\r\n\r\nshared PreCleaningInspection_EMO = let\r\n    Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n    #\"Filtered rows\" = Table.SelectRows(Source, each [Extension] = \".csv\"),\r\n    #\"Filtered rows 1\" = Table.SelectRows(#\"Filtered rows\", each Text.Contains([Name], \"GEP_PreCleaningInspection_GEP\") or Text.Contains([Name], \"KEP_PreCleaningInspection_GEP\") and not Text.Contains([Name], \"Pre\")),\r\n    #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows 1\", each [Attributes]?[Hidden]? <> true),\r\n    #\"Filtered hidden files 1\" = Table.SelectRows(#\"Filtered hidden files\", each [Attributes]?[Hidden]? <> true),\r\n    #\"Invoke custom function\" = Table.AddColumn(#\"Filtered hidden files 1\", \"Transform file (4)\", each #\"Transform file (4)\"([Content])),\r\n    #\"Renamed columns\" = Table.RenameColumns(#\"Invoke custom function\", {{\"Name\", \"Source.Name\"}}),\r\n    #\"Removed other columns\" = Table.SelectColumns(#\"Renamed columns\", {\"Source.Name\", \"Transform file (4)\"}),\r\n    #\"Expanded table column\" = Table.ExpandTableColumn(#\"Removed other columns\", \"Transform file (4)\", Table.ColumnNames(#\"Transform file (4)\"(#\"Sample file (4)\"))),\r\n    #\"Choose columns\" = Table.SelectColumns(#\"Expanded table column\", {\"Date\", \"Name\", \"Org\", \"Oracle Job\", \"Cumulus WO\", \"Part Number\", \"Description\", \"Qty\", \"R\", \"Gas Contact\", \"Inspection OK\", \"Inspection SOK\", \"Inspection NOK\", \"Label USB Cleaned\", \"Label Wipe Test\", \"Cause\", \"Fixed\", \"Fixed By\", \"Remarks\", \"Serial Number\"}),\r\n    #\"Changed column type\" = Table.TransformColumnTypes(#\"Choose columns\", {{\"Name\", type text}, {\"Org\", type text}, {\"Oracle Job\", type text}, {\"Cumulus WO\", type text}, {\"Part Number\", type text}, {\"Description\", type text}, {\"R\", type text}, {\"Gas Contact\", type text}, {\"Label USB Cleaned\", type text}, {\"Label Wipe Test\", type text}, {\"Cause\", type text}, {\"Fixed\", type text}, {\"Fixed By\", type text}, {\"Remarks\", type text}, {\"Serial Number\", type text}, {\"Qty\", Int64.Type}, {\"Inspection OK\", Int64.Type}, {\"Inspection SOK\", Int64.Type}, {\"Inspection NOK\", Int64.Type}}),\r\n    #\"Changed column type with locale\" = Table.TransformColumnTypes(#\"Changed column type\", {{\"Date\", type datetime}}, \"de-DE\")\r\nin\r\n    #\"Changed column type with locale\";\r\n\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[{\"id\":\"f6077aa3-4918-45b1-8b1f-80fcfbbb38f9\",\"name\":\"Transform file from CleaningInspection CR old (2)\",\"description\":null,\"parentId\":null,\"order\":0},{\"id\":\"69728958-a3c0-46e5-88f5-7b17fbcfe3f0\",\"name\":\"Helper queries (2)\",\"description\":null,\"parentId\":\"f6077aa3-4918-45b1-8b1f-80fcfbbb38f9\",\"order\":0},{\"id\":\"dc867e03-17c3-478b-a13c-52eb12aea3ef\",\"name\":\"Transform file from CleaningInspection CR\",\"description\":null,\"parentId\":null,\"order\":0},{\"id\":\"6ab2c6ba-fd03-4622-8269-d9301bd85e62\",\"name\":\"Helper queries\",\"description\":null,\"parentId\":\"dc867e03-17c3-478b-a13c-52eb12aea3ef\",\"order\":0},{\"id\":\"8186dd21-5598-440e-91ff-e6bb7a7495e3\",\"name\":\"Transform file from CleaningHistory\",\"description\":null,\"parentId\":null,\"order\":0},{\"id\":\"7f1c3388-b9cf-45f7-a7fc-685f61a82905\",\"name\":\"Helper queries (3)\",\"description\":null,\"parentId\":\"8186dd21-5598-440e-91ff-e6bb7a7495e3\",\"order\":0},{\"id\":\"6b6e1842-beba-4c1e-aec5-b676c91b7e01\",\"name\":\"Transform file from PreCleaningInspection_EMO\",\"description\":null,\"parentId\":null,\"order\":0},{\"id\":\"1db40640-80e8-4765-bb12-9f31e7160ccf\",\"name\":\"Helper queries (4)\",\"description\":null,\"parentId\":\"6b6e1842-beba-4c1e-aec5-b676c91b7e01\",\"order\":0},{\"id\":\"81a05464-3133-407d-b3fc-b4cb675b79c7\",\"name\":\"Inactive\",\"description\":\"\",\"parentId\":null,\"order\":0},{\"id\":\"184d830d-6213-40b6-80d2-197c17657521\",\"name\":\"Transform file from CleaningInspectionCR_CSV2\",\"description\":null,\"parentId\":null,\"order\":0},{\"id\":\"9d8bbfdb-3e6e-4d4c-8685-edda6e5bbfc9\",\"name\":\"Helper queries (5)\",\"description\":null,\"parentId\":\"184d830d-6213-40b6-80d2-197c17657521\",\"order\":0}]"}],"entities":[{"$type":"LocalEntity","name":"PreCleaningInspection_EMO","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"PreCleaningInspection_EMO.csv"},"attributes":[{"name":"Date","dataType":"dateTime"},{"name":"Name","dataType":"string"},{"name":"Org","dataType":"string"},{"name":"Oracle Job","dataType":"string"},{"name":"Cumulus WO","dataType":"string"},{"name":"Part Number","dataType":"string"},{"name":"Description","dataType":"string"},{"name":"Qty","dataType":"int64"},{"name":"R","dataType":"string"},{"name":"Gas Contact","dataType":"string"},{"name":"Inspection OK","dataType":"int64"},{"name":"Inspection SOK","dataType":"int64"},{"name":"Inspection NOK","dataType":"int64"},{"name":"Label USB Cleaned","dataType":"string"},{"name":"Label Wipe Test","dataType":"string"},{"name":"Cause","dataType":"string"},{"name":"Fixed","dataType":"string"},{"name":"Fixed By","dataType":"string"},{"name":"Remarks","dataType":"string"},{"name":"Serial Number","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-03-07T21:33:23.8596006+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/986ee6f6-877a-4a64-b7e6-7323a3aa9ba5/PreCleaningInspection_EMO.csv?snapshot=2022-03-07T21%3A33%3A23.8420950Z"}]},{"$type":"LocalEntity","name":"CleaningInspectionCR_CSV","description":"","pbi:refreshPolicy":{"$type":"IncrementalRefreshPolicy","locationPattern":"CleaningInspectionCR_CSV/part.csv","rollingWindowGranularity":"year","rollingWindowPeriods":3,"incrementalGranularity":"month","incrementalPeriods":1},"annotations":[{"name":"pbi:IncrementalRefreshDetectChangeAttribute"},{"name":"pbi:IncrementalRefreshFilterByAttribute","value":"Date"}],"attributes":[{"name":"Date","dataType":"dateTime"},{"name":"Name","dataType":"string"},{"name":"Org","dataType":"string"},{"name":"Oracle Job","dataType":"string"},{"name":"Cumulus WO","dataType":"string"},{"name":"Part Number","dataType":"string"},{"name":"Description","dataType":"string"},{"name":"Qty","dataType":"int64"},{"name":"R","dataType":"string"},{"name":"Gas Contact","dataType":"string"},{"name":"Wipe Test OK","dataType":"int64"},{"name":"Wipe Test SOK","dataType":"int64"},{"name":"Wipe Test NOK","dataType":"int64"},{"name":"Ink Test 56","dataType":"int64"},{"name":"Ink Test 48","dataType":"int64"},{"name":"Ink Test 44","dataType":"int64"},{"name":"Visual Inspection OK","dataType":"int64"},{"name":"Visual Inspection NOK","dataType":"int64"},{"name":"Cause","dataType":"string"},{"name":"Fixed","dataType":"string"},{"name":"Fixed By","dataType":"string"},{"name":"Remarks","dataType":"string"},{"name":"Serial Number","dataType":"string"}],"partitions":[{"name":"IncrementalRefreshPolicyPartition-2019","refreshTime":"2022-03-06T14:30:07.1583664+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/986ee6f6-877a-4a64-b7e6-7323a3aa9ba5/CleaningInspectionCR_CSV/part-2019.csv?snapshot=2022-03-06T14%3A30%3A06.2179872Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2019-01-01T00:00:00","end":"2020-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2020","refreshTime":"2022-03-06T14:29:47.3511363+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/986ee6f6-877a-4a64-b7e6-7323a3aa9ba5/CleaningInspectionCR_CSV/part-2020.csv?snapshot=2022-03-06T14%3A29%3A47.3358551Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2020-01-01T00:00:00","end":"2021-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2021","refreshTime":"2022-03-06T14:31:24.0571308+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/986ee6f6-877a-4a64-b7e6-7323a3aa9ba5/CleaningInspectionCR_CSV/part-2021.csv?snapshot=2022-03-06T14%3A31%3A22.8758762Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2021-01-01T00:00:00","end":"2022-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q101","refreshTime":"2022-03-06T14:32:34.7240233+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/986ee6f6-877a-4a64-b7e6-7323a3aa9ba5/CleaningInspectionCR_CSV/part-2022Q101.csv?snapshot=2022-03-06T14%3A32%3A33.7820863Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-01-01T00:00:00","end":"2022-02-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q102","refreshTime":"2022-03-06T14:29:38.978431+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/986ee6f6-877a-4a64-b7e6-7323a3aa9ba5/CleaningInspectionCR_CSV/part-2022Q102.csv?snapshot=2022-03-06T14%3A29%3A38.9626733Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-02-01T00:00:00","end":"2022-03-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q103","refreshTime":"2022-03-07T23:27:15.23109+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/986ee6f6-877a-4a64-b7e6-7323a3aa9ba5/CleaningInspectionCR_CSV/part-2022Q103.csv?snapshot=2022-03-07T23%3A27%3A15.1137252Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-03-01T00:00:00","end":"2022-04-01T00:00:00"}}]}]}