{"name":"Flow_SQL_GTG_Daily","description":"Flow for Goettingen SQL-Server (Degoesql).\nDaily refresh.","version":"1.0","culture":"en-US","modifiedTime":"2022-03-29T11:05:09.0298393+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"ParticleDB_MeasPoint":{"queryId":"fd784a52-7ebd-4cbc-b704-42f6399c7088","queryName":"ParticleDB_MeasPoint","queryGroupId":"2e12da48-22fe-46ca-ae2f-70e599ce8ecf","loadEnabled":true},"ParticleDB_MeasSpec":{"queryId":"ccc61cbd-1eed-4bfe-95cd-901321dc7ed3","queryName":"ParticleDB_MeasSpec","queryGroupId":"2e12da48-22fe-46ca-ae2f-70e599ce8ecf","loadEnabled":true},"ParticleDB_MeasSpec_2pvt":{"queryId":"ef8401c4-12b4-4348-bec2-861463df021b","queryName":"ParticleDB_MeasSpec_2pvt","queryGroupId":"2e12da48-22fe-46ca-ae2f-70e599ce8ecf","loadEnabled":true},"ParticleDB_MeasMeasurements":{"queryId":"6f12093a-c3ea-49db-b2f4-a41f6b109f5d","queryName":"ParticleDB_MeasMeasurements","queryGroupId":"2e12da48-22fe-46ca-ae2f-70e599ce8ecf","loadEnabled":true},"ParticleDB_MeasMeasurements_2pvt":{"queryId":"5301730f-8919-4bdd-bc32-67c2ed3d8c5b","queryName":"ParticleDB_MeasMeasurements_2pvt","queryGroupId":"2e12da48-22fe-46ca-ae2f-70e599ce8ecf","loadEnabled":true},"ParticleDB_MeasOperators":{"queryId":"a08c9985-8de3-4f1f-8323-c07ee4429c9d","queryName":"ParticleDB_MeasOperators","queryGroupId":"2e12da48-22fe-46ca-ae2f-70e599ce8ecf","loadEnabled":true},"ParticleDB_MeasRooms":{"queryId":"4c8695b9-a8ea-43ac-89b2-4ac700061358","queryName":"ParticleDB_MeasRooms","queryGroupId":"2e12da48-22fe-46ca-ae2f-70e599ce8ecf","loadEnabled":true},"ParticleCategories":{"queryId":"42f6345d-5985-401c-9a7c-375ddfebdf55","queryName":"ParticleCategories","queryGroupId":"2e12da48-22fe-46ca-ae2f-70e599ce8ecf"},"ParticleDB_MeasXXXXXX":{"queryId":"b37799cc-24ec-49f8-9032-b41d00f9627f","queryName":"ParticleDB_MeasXXXXXX","queryGroupId":"2e12da48-22fe-46ca-ae2f-70e599ce8ecf"},"CleaningInspection_CR":{"queryId":"51299162-2983-46c0-9543-7ebad6ac8e29","queryName":"CleaningInspection_CR","queryGroupId":"53773bc4-c3c9-4630-8abe-d2b30a3c4e3e","loadEnabled":true},"CleaningInspection_EMO":{"queryId":"f1fe1c0d-1c04-47eb-86de-3dd350a90ffa","queryName":"CleaningInspection_EMO","queryGroupId":"53773bc4-c3c9-4630-8abe-d2b30a3c4e3e","loadEnabled":true}},"document":"section Section1;\r\nshared ParticleDB_MeasPoint = let\r\n  Source = Sql.Database(\"Degoesql_GTG_Ops_Ind-DB\", \"GTG_Ops_Ind-DB\"),\r\n  Navigation = Source{[Schema = \"dbo\", Item = \"T_MeasPoint\"]}[Data]\r\nin\r\n  Navigation;\r\nshared ParticleDB_MeasSpec = let\r\n  Source = Sql.Database(\"Degoesql_GTG_Ops_Ind-DB\", \"GTG_Ops_Ind-DB\"),\r\n  Navigation = Source{[Schema = \"dbo\", Item = \"T_MeasSpec\"]}[Data]\r\nin\r\n  Navigation;\r\nshared ParticleDB_MeasSpec_2pvt = let\r\n  Source = Sql.Database(\"Degoesql_GTG_Ops_Ind-DB\", \"GTG_Ops_Ind-DB\"),\r\n  Navigation = Source{[Schema = \"dbo\", Item = \"T_MeasSpec\"]}[Data],\r\n  #\"Unpivoted columns\" = Table.UnpivotOtherColumns(Navigation, {\"IDClass\"}, \"Attribute\", \"Value\"),\r\n  #\"Replaced value\" = Table.ReplaceValue(#\"Unpivoted columns\", \"\", \"0\", Replacer.ReplaceValue, {\"Value\"}),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Replaced value\", {{\"Value\", \"ParticleCount\"}, {\"Attribute\", \"MaxParticleCategory\"}}),\r\n  #\"Inserted last characters\" = Table.AddColumn(#\"Renamed columns\", \"ParticleSize\", each Text.End([MaxParticleCategory], 2), type text),\r\n  #\"Replaced value 1\" = Table.ReplaceValue(#\"Inserted last characters\", \"03\", \"0.3um\", Replacer.ReplaceText, {\"ParticleSize\"}),\r\n  #\"Replaced value 2\" = Table.ReplaceValue(#\"Replaced value 1\", \"05\", \"0.5um\", Replacer.ReplaceText, {\"ParticleSize\"}),\r\n  #\"Replaced value 3\" = Table.ReplaceValue(#\"Replaced value 2\", \"10\", \"1.0um\", Replacer.ReplaceText, {\"ParticleSize\"}),\r\n  #\"Replaced value 4\" = Table.ReplaceValue(#\"Replaced value 3\", \"50\", \"5.0um\", Replacer.ReplaceText, {\"ParticleSize\"}),\r\n  #\"Inserted text after delimiter\" = Table.AddColumn(#\"Replaced value 4\", \"Text after delimiter\", each Text.AfterDelimiter([MaxParticleCategory], \"MaxParticleNo\", 0), type text),\r\n  #\"Replaced value 5\" = Table.ReplaceValue(#\"Inserted text after delimiter\", \"03\", \"\", Replacer.ReplaceText, {\"Text after delimiter\"}),\r\n  #\"Replaced value 6\" = Table.ReplaceValue(#\"Replaced value 5\", \"05\", \"\", Replacer.ReplaceText, {\"Text after delimiter\"}),\r\n  #\"Replaced value 7\" = Table.ReplaceValue(#\"Replaced value 6\", \"10\", \"\", Replacer.ReplaceText, {\"Text after delimiter\"}),\r\n  #\"Replaced value 8\" = Table.ReplaceValue(#\"Replaced value 7\", \"50\", \"\", Replacer.ReplaceText, {\"Text after delimiter\"}),\r\n  #\"Replaced value 9\" = Table.ReplaceValue(#\"Replaced value 8\", \"\", \"nonISO\", Replacer.ReplaceValue, {\"Text after delimiter\"}),\r\n  #\"Renamed columns 1\" = Table.RenameColumns(#\"Replaced value 9\", {{\"Text after delimiter\", \"Spec_Type\"}})\r\nin\r\n  #\"Renamed columns 1\";\r\nshared ParticleDB_MeasMeasurements = let\r\n  Source = Sql.Database(\"Degoesql_GTG_Ops_Ind-DB\", \"GTG_Ops_Ind-DB\"),\r\n  Navigation = Source{[Schema = \"dbo\", Item = \"T_Measurement\"]}[Data]\r\nin\r\n  Navigation;\r\nshared ParticleDB_MeasMeasurements_2pvt = let\r\n  Source = Sql.Database(\"Degoesql_GTG_Ops_Ind-DB\", \"GTG_Ops_Ind-DB\"),\r\n  Navigation = Source{[Schema = \"dbo\", Item = \"T_Measurement\"]}[Data],\r\n  #\"Choose columns\" = Table.SelectColumns(Navigation, {\"IDMeasurement\", \"ParticleNo03_1\", \"ParticleNo03_2\", \"ParticleNo03_3\", \"ParticleNo05_1\", \"ParticleNo05_2\", \"ParticleNo05_3\", \"ParticleNo10_1\", \"ParticleNo10_2\", \"ParticleNo10_3\", \"ParticleNo50_1\", \"ParticleNo50_2\", \"ParticleNo50_3\", \"ParticleNo03\", \"ParticleNo05\", \"ParticleNo10\", \"ParticleNo50\"}),\r\n  #\"Unpivoted columns\" = Table.UnpivotOtherColumns(#\"Choose columns\", {\"IDMeasurement\"}, \"Attribute\", \"Value\"),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Unpivoted columns\", {{\"Attribute\", \"ParticleSize\"}, {\"Value\", \"ParticleCount_cft\"}}),\r\n  #\"Merged queries\" = Table.NestedJoin(#\"Renamed columns\", {\"ParticleSize\"}, ParticleCategories, {\"ParticleSize_ID\"}, \"ParticleCategories\", JoinKind.LeftOuter),\r\n  #\"Expanded ParticleCategories\" = Table.ExpandTableColumn(#\"Merged queries\", \"ParticleCategories\", {\"Size_Measurement\", \"SizeCategory\", \"Measurement\"}, {\"Size_Measurement\", \"SizeCategory\", \"Measurement\"})\r\nin\r\n  #\"Expanded ParticleCategories\";\r\nshared ParticleDB_MeasOperators = let\r\n  Source = Sql.Database(\"Degoesql_GTG_Ops_Ind-DB\", \"GTG_Ops_Ind-DB\"),\r\n  Navigation = Source{[Schema = \"dbo\", Item = \"T_Operator\"]}[Data]\r\nin\r\n  Navigation;\r\nshared ParticleDB_MeasRooms = let\r\n  Source = Sql.Database(\"Degoesql_GTG_Ops_Ind-DB\", \"GTG_Ops_Ind-DB\"),\r\n  Navigation = Source{[Schema = \"dbo\", Item = \"T_Room\"]}[Data]\r\nin\r\n  Navigation;\r\nshared ParticleCategories = let\r\n  Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"bZDRCoMwDEX/pc9SkoZ8wD6gsneRImMMQRFk8/sNtbSS5flwT27uMLjntH/n1/LuNwbXOfbwW9Pj+Lixu0PgFASDZ8ExKIqQUCjmcERFGRJVdSRtppwFT1ZW7mK7+0eptCKrFV+t2G4FXL3Gu5QrF7GuLOLQxMYYoY2hqTxE7SFtxmsqrFONJw==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [ParticleSize = _t, Name_New = _t]),\r\n  #\"Inserted first characters\" = Table.AddColumn(Source, \"SizeCategory\", each Text.Start([Name_New], 5), type text),\r\n  #\"Sorted rows\" = Table.Sort(#\"Inserted first characters\", {{\"ParticleSize\", Order.Ascending}}),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Sorted rows\", {{\"ParticleSize\", \"ParticleSize_ID\"}, {\"Name_New\", \"Size_Measurement\"}}),\r\n  #\"Inserted text after delimiter\" = Table.AddColumn(#\"Renamed columns\", \"Measurement\", each Text.AfterDelimiter([Size_Measurement], \"_\", 0), type text)\r\nin\r\n  #\"Inserted text after delimiter\";\r\nshared ParticleDB_MeasXXXXXX = let\r\n  Source = Sql.Database(\"Degoesql_GTG_Ops_Ind-DB\", \"GTG_Ops_Ind-DB\")\r\nin\r\n  Source;\r\nshared CleaningInspection_CR = let\r\n  Source = Sql.Database(\"Degoesql_GTG_Ops_Ind-DB\", \"GTG_Ops_Ind-DB\"),\r\n  Navigation = Source{[Item = \"CleaningInspection\", Schema = \"dbo\"]}[Data],\r\n  #\"Choose columns\" = Table.SelectColumns(Navigation, {\"CumulusWO\", \"Date\", \"Name\", \"Org\", \"OracleJob\", \"PartNumber\", \"Description\", \"Qty\", \"R\", \"GasContact\", \"WipeTestOK\", \"WipeTestSOK\", \"WipeTestNOK\", \"InkTest56\", \"InkTest48\", \"InkTest44\", \"VisualInspectionOK\", \"VisualInspectionNOK\", \"Cause\", \"Fixed\", \"FixedBy\", \"Remarks\", \"SerialNumber\"}),\r\n  #\"Changed column type with locale\" = Table.TransformColumnTypes(#\"Choose columns\", {{\"Date\", type date}, {\"Qty\", Int64.Type}, {\"WipeTestOK\", Int64.Type}, {\"WipeTestSOK\", Int64.Type}, {\"WipeTestNOK\", Int64.Type}, {\"InkTest56\", Int64.Type}, {\"InkTest48\", Int64.Type}, {\"InkTest44\", Int64.Type}, {\"VisualInspectionOK\", Int64.Type}, {\"VisualInspectionNOK\", Int64.Type}}, \"de-DE\")\r\nin\r\n  #\"Changed column type with locale\";\r\nshared CleaningInspection_EMO = let\r\n  Source = Sql.Database(\"Degoesql_GTG_Ops_Ind-DB\", \"GTG_Ops_Ind-DB\"),\r\n  Navigation = Source{[Schema = \"dbo\", Item = \"CleaningInspectionPre\"]}[Data],\r\n  #\"Choose columns\" = Table.SelectColumns(Navigation, {\"CumulusWO\", \"Date\", \"Name\", \"Org\", \"OracleJob\", \"PartNumber\", \"Description\", \"Qty\", \"R\", \"GasContact\", \"InspectionOK\", \"InspectionSOK\", \"InspectionNOK\", \"LabelUSBCleaned\", \"LabelWipeTest\", \"Cause\", \"Fixed\", \"FixedBy\", \"Remarks\", \"SerialNumber\"}),\r\n  #\"Changed column type with locale\" = Table.TransformColumnTypes(#\"Choose columns\", {{\"Date\", type date}, {\"Qty\", Int64.Type}, {\"InspectionOK\", Int64.Type}, {\"InspectionSOK\", Int64.Type}, {\"InspectionNOK\", Int64.Type}}, \"de-DE\")\r\nin\r\n  #\"Changed column type with locale\";\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[{\"id\":\"2e12da48-22fe-46ca-ae2f-70e599ce8ecf\",\"name\":\"ParticleDB\",\"description\":\"\",\"parentId\":null,\"order\":1},{\"id\":\"53773bc4-c3c9-4630-8abe-d2b30a3c4e3e\",\"name\":\"CleaningInspection\",\"description\":\"Cleaning Inspection Cleanroom Fab3.\",\"parentId\":null,\"order\":0}]"}],"entities":[{"$type":"LocalEntity","name":"ParticleDB_MeasPoint","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"ParticleDB_MeasPoint.csv"},"attributes":[{"name":"IDMeasPoint","dataType":"string"},{"name":"IDARoom","dataType":"string"},{"name":"MeasPointName","dataType":"string"},{"name":"CoordinateX","dataType":"int64"},{"name":"CoordinateY","dataType":"int64"},{"name":"Active","dataType":"boolean"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-12T23:30:16.8748822+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/57721770-5b78-4c3d-90e2-56d3e96558b8/ParticleDB_MeasPoint.csv?snapshot=2022-06-12T23%3A30%3A16.8592967Z"}]},{"$type":"LocalEntity","name":"ParticleDB_MeasSpec","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"ParticleDB_MeasSpec.csv"},"attributes":[{"name":"IDClass","dataType":"string"},{"name":"MaxParticleNoISO03","dataType":"string"},{"name":"MaxParticleNoISO05","dataType":"string"},{"name":"MaxParticleNoISO10","dataType":"string"},{"name":"MaxParticleNoISO50","dataType":"string"},{"name":"MaxParticleNo03","dataType":"string"},{"name":"MaxParticleNo05","dataType":"string"},{"name":"MaxParticleNo10","dataType":"string"},{"name":"MaxParticleNo50","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-12T23:30:15.1092458+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/57721770-5b78-4c3d-90e2-56d3e96558b8/ParticleDB_MeasSpec.csv?snapshot=2022-06-12T23%3A30%3A15.1023573Z"}]},{"$type":"LocalEntity","name":"ParticleDB_MeasSpec_2pvt","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"ParticleDB_MeasSpec_2pvt.csv"},"attributes":[{"name":"IDClass","dataType":"string"},{"name":"MaxParticleCategory","dataType":"string"},{"name":"ParticleCount","dataType":"string"},{"name":"ParticleSize","dataType":"string"},{"name":"Spec_Type","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-12T23:30:15.1092458+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/57721770-5b78-4c3d-90e2-56d3e96558b8/ParticleDB_MeasSpec_2pvt.csv?snapshot=2022-06-12T23%3A30%3A15.0803709Z"}]},{"$type":"LocalEntity","name":"ParticleDB_MeasMeasurements","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"ParticleDB_MeasMeasurements.csv"},"attributes":[{"name":"IDMeasurement","dataType":"string"},{"name":"IDAMeasDev","dataType":"string"},{"name":"IDAMeasPoint","dataType":"string"},{"name":"IDAOperator","dataType":"string"},{"name":"Session","dataType":"string"},{"name":"MeasDateTime","dataType":"dateTime"},{"name":"ParticleNo03_1","dataType":"string"},{"name":"ParticleNo03_2","dataType":"string"},{"name":"ParticleNo03_3","dataType":"string"},{"name":"ParticleNo05_1","dataType":"string"},{"name":"ParticleNo05_2","dataType":"string"},{"name":"ParticleNo05_3","dataType":"string"},{"name":"ParticleNo10_1","dataType":"string"},{"name":"ParticleNo10_2","dataType":"string"},{"name":"ParticleNo10_3","dataType":"string"},{"name":"ParticleNo50_1","dataType":"string"},{"name":"ParticleNo50_2","dataType":"string"},{"name":"ParticleNo50_3","dataType":"string"},{"name":"ParticleNo03","dataType":"string"},{"name":"ParticleNo05","dataType":"string"},{"name":"ParticleNo10","dataType":"string"},{"name":"ParticleNo50","dataType":"string"},{"name":"Unit","dataType":"string"},{"name":"Rating","dataType":"string"},{"name":"Action","dataType":"string"},{"name":"Remarks","dataType":"string"},{"name":"Status","dataType":"int64"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-12T23:30:13.3510559+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/57721770-5b78-4c3d-90e2-56d3e96558b8/ParticleDB_MeasMeasurements.csv?snapshot=2022-06-12T23%3A30%3A13.3264306Z"}]},{"$type":"LocalEntity","name":"ParticleDB_MeasMeasurements_2pvt","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"ParticleDB_MeasMeasurements_2pvt.csv"},"attributes":[{"name":"IDMeasurement","dataType":"string"},{"name":"ParticleSize","dataType":"string"},{"name":"ParticleCount_cft","dataType":"string"},{"name":"Size_Measurement","dataType":"string"},{"name":"SizeCategory","dataType":"string"},{"name":"Measurement","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-12T23:30:15.7498684+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/57721770-5b78-4c3d-90e2-56d3e96558b8/ParticleDB_MeasMeasurements_2pvt.csv?snapshot=2022-06-12T23%3A30%3A15.7349751Z"}]},{"$type":"LocalEntity","name":"ParticleDB_MeasOperators","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"ParticleDB_MeasOperators.csv"},"attributes":[{"name":"IDOperator","dataType":"string"},{"name":"FirstName","dataType":"string"},{"name":"Surname","dataType":"string"},{"name":"CostCenter","dataType":"string"},{"name":"Rights","dataType":"int64"},{"name":"Password","dataType":"string"},{"name":"Email","dataType":"string"},{"name":"TrainingDate","dataType":"dateTime"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-12T23:30:12.7104512+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/57721770-5b78-4c3d-90e2-56d3e96558b8/ParticleDB_MeasOperators.csv?snapshot=2022-06-12T23%3A30%3A12.6678292Z"}]},{"$type":"LocalEntity","name":"ParticleDB_MeasRooms","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"ParticleDB_MeasRooms.csv"},"attributes":[{"name":"IDRoom","dataType":"string"},{"name":"IDAClass","dataType":"string"},{"name":"RoomName","dataType":"string"},{"name":"Fab","dataType":"string"},{"name":"Remarks","dataType":"string"},{"name":"Area","dataType":"int64"},{"name":"Image","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-12T23:30:12.8197854+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/57721770-5b78-4c3d-90e2-56d3e96558b8/ParticleDB_MeasRooms.csv?snapshot=2022-06-12T23%3A30%3A12.7947519Z"}]},{"$type":"LocalEntity","name":"CleaningInspection_CR","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"CleaningInspection_CR.csv"},"attributes":[{"name":"CumulusWO","dataType":"string"},{"name":"Date","dataType":"date"},{"name":"Name","dataType":"string"},{"name":"Org","dataType":"string"},{"name":"OracleJob","dataType":"string"},{"name":"PartNumber","dataType":"string"},{"name":"Description","dataType":"string"},{"name":"Qty","dataType":"int64"},{"name":"R","dataType":"string"},{"name":"GasContact","dataType":"string"},{"name":"WipeTestOK","dataType":"int64"},{"name":"WipeTestSOK","dataType":"int64"},{"name":"WipeTestNOK","dataType":"int64"},{"name":"InkTest56","dataType":"int64"},{"name":"InkTest48","dataType":"int64"},{"name":"InkTest44","dataType":"int64"},{"name":"VisualInspectionOK","dataType":"int64"},{"name":"VisualInspectionNOK","dataType":"int64"},{"name":"Cause","dataType":"string"},{"name":"Fixed","dataType":"string"},{"name":"FixedBy","dataType":"string"},{"name":"Remarks","dataType":"string"},{"name":"SerialNumber","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-12T23:30:32.5344961+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/57721770-5b78-4c3d-90e2-56d3e96558b8/CleaningInspection_CR.csv?snapshot=2022-06-12T23%3A30%3A32.5278318Z"}]},{"$type":"LocalEntity","name":"CleaningInspection_EMO","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"CleaningInspection_EMO.csv"},"attributes":[{"name":"CumulusWO","dataType":"string"},{"name":"Date","dataType":"date"},{"name":"Name","dataType":"string"},{"name":"Org","dataType":"string"},{"name":"OracleJob","dataType":"string"},{"name":"PartNumber","dataType":"string"},{"name":"Description","dataType":"string"},{"name":"Qty","dataType":"int64"},{"name":"R","dataType":"string"},{"name":"GasContact","dataType":"string"},{"name":"InspectionOK","dataType":"int64"},{"name":"InspectionSOK","dataType":"int64"},{"name":"InspectionNOK","dataType":"int64"},{"name":"LabelUSBCleaned","dataType":"string"},{"name":"LabelWipeTest","dataType":"string"},{"name":"Cause","dataType":"string"},{"name":"Fixed","dataType":"string"},{"name":"FixedBy","dataType":"string"},{"name":"Remarks","dataType":"string"},{"name":"SerialNumber","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-12T23:30:15.9373719+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/57721770-5b78-4c3d-90e2-56d3e96558b8/CleaningInspection_EMO.csv?snapshot=2022-06-12T23%3A30%3A15.9208630Z"}]}]}