{"name":"Test_SalesSupport","description":"","version":"1.0","culture":"en-US","modifiedTime":"2022-07-04T15:14:23.4673264+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":true,"queriesMetadata":{"parDays2Load":{"queryId":"fc1bff57-3b04-4747-ba73-f950a1868c5e","queryName":"parDays2Load"},"XX_FISCAL_DAYS_COHR_TAB":{"queryId":"0ac32baf-64be-4548-9ffa-40b137021084","queryName":"XX_FISCAL_DAYS_COHR_TAB","loadEnabled":true},"XXCOH_NETBOOKINGS_VIEW":{"queryId":"93a1cd6e-4c9d-47b0-be89-f9dff0b73ea4","queryName":"XXCOH_NETBOOKINGS_VIEW"},"XXCOH_BILLING_VIEW":{"queryId":"d7f61882-3052-4a2a-9aae-22c486940fcf","queryName":"XXCOH_BILLING_VIEW"},"XXCOH_BACKLOG_VIEW":{"queryId":"531a5e87-d4de-4f32-b116-77b46974bb2b","queryName":"XXCOH_BACKLOG_VIEW"},"XXCOH_MS_SHIPMENT_VIEW":{"queryId":"a1d0563e-fd10-421b-a643-e2ed51352fc1","queryName":"XXCOH_MS_SHIPMENT_VIEW"}},"document":"section Section1;\r\n[Description = \"Parameter for days to load (history data).\"]\r\nshared parDays2Load = 365 meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type number];\r\nshared XX_FISCAL_DAYS_COHR_TAB = let\n    XX_FISCAL_DAYS_COHR_TAB = Value.NativeQuery(Snowflake.Databases(\"mma12090.snowflakecomputing.com\",\"COMPUTE_REPORTING\", [Role=\"GLBMFGOPERATIONSROLE\"]){[Name=\"PROD_DB\"]}[Data], \"SELECT *FROM PROD_DB.APPS.XX_FISCAL_DAYS_COHR_TAB\", null, [EnableFolding=true])\nin\n    XX_FISCAL_DAYS_COHR_TAB;\r\nshared XXCOH_NETBOOKINGS_VIEW = let\n    XXCOH_NETBOOKINGS_VIEW = Value.NativeQuery(Snowflake.Databases(\"mma12090.snowflakecomputing.com\",\"COMPUTE_REPORTING\", [Role=\"GLBMFGOPERATIONSROLE\"]){[Name=\"PROD_DB\"]}[Data], \"SELECT *FROM PROD_DB.APPS.XXCOH_NETBOOKINGS_VIEW\", null, [EnableFolding=true]),\n  #\"Choose columns\" = Table.SelectColumns(XXCOH_NETBOOKINGS_VIEW, {\"ASOF_DATE\", \"ASOF_DATE_DISP\", \"BOOKED_DATE\", \"FISCAL_WEEK_BOOKED\", \"FISCAL_QUARTER_BOOKED\", \"FISCAL_YEAR_BOOKED\", \"REPORTING_ENTITY\", \"ORDER_NUMBER\", \"ORDER_LINE\", \"ORDER_TYPE\", \"SO_LINE_TYPE\", \"BILLABLE_FLAG\", \"CUSTOMER_PO\", \"CREATED_BY\", \"ITEM_NUMBER\", \"ITEM_DESCRIPTION\", \"PRODUCT_LINE\", \"PRODUCT_FAMILY\", \"TECHNICAL_BUSINESS_UNIT\", \"FORECAST_FIELD\", \"COMMODITY\", \"WAREHOUSE\", \"ORDERED_QUANTITY\", \"ASP_QUANTITY\", \"EXTENDED_AMOUNT\", \"EXTENDED_LIST_PRICE\", \"APPLICATION_CODE_DESC\", \"APPLICATION_CODE\", \"REQUEST_SHIP_DATE\", \"SCHEDULE_SHIP_DATE\", \"CUSTOMER_NAME\", \"CUSTOMER_ALTERNATE_NAME\", \"CUSTOMER_NUMBER\", \"BILL_TO_COUNTRY\", \"SHIP_TO_COUNTRY\", \"END_USER\", \"SALESPERSON\", \"ORDER_STATUS\", \"CUSTOMER_CATEGORY\", \"TRANSACTION_CURRENCY\", \"EXTENDED_AMOUNT_USD\", \"EXTENDED_LIST_PRICE_USD\", \"EXTENDED_COST_USD\", \"LINE_ID\"})\nin\n    #\"Choose columns\";\r\nshared XXCOH_BILLING_VIEW = let\n    XXCOH_BILLING_VIEW = Value.NativeQuery(Snowflake.Databases(\"mma12090.snowflakecomputing.com\",\"COMPUTE_REPORTING\", [Role=\"GLBMFGOPERATIONSROLE\"]){[Name=\"PROD_DB\"]}[Data], \"SELECT *FROM PROD_DB.APPS.XXCOH_BILLING_VIEW WHERE Technical_Business_Unit='Excimer' \", null, [EnableFolding=true]),\n  #\"Filtered rows\" = Table.SelectRows(XXCOH_BILLING_VIEW, each Date.IsInPreviousNDays([BOOKED_DATE], parDays2Load)),\n  #\"Choose columns\" = Table.SelectColumns(#\"Filtered rows\", {\"ASOF_DATE\", \"ASOF_DATE_DISP\", \"BOOKED_DATE\", \"WAREHOUSE\", \"ORDER_NUMBER\", \"ORDER_LINE\", \"ORDER_TYPE\", \"SO_LINE_TYPE\", \"REPORTING_ENTITY\", \"INVOICE_TYPE\", \"CUSTOMER_PO\", \"ITEM_NUMBER\", \"ITEM_DESCRIPTION\", \"PRODUCT_LINE\", \"PRODUCT_FAMILY\", \"TECHNICAL_BUSINESS_UNIT\", \"FORECAST_FIELD\", \"COMMODITY\", \"INVOICED_QUANTITY\", \"ASP_QUANTITY\", \"GL_DATE\", \"REVENUE_USD\", \"UNIT_LIST_PRICE\", \"EXTENDED_AMOUNT\", \"APPLICATION_CODE_DESC\", \"APPLICATION_CODE\", \"REQUEST_SHIP_DATE\", \"BILL_TO_COUNTRY\", \"SHIP_TO_COUNTRY\", \"END_USER\", \"SALESPERSON\", \"CUSTOMER_NAME\", \"CUSTOMER_ALTERNATE_NAME\", \"CUSTOMER_NUMBER\", \"CUSTOMER_CATEGORY\", \"FISCAL_WEEK_GL_DATE\", \"FISCAL_QUARTER_GL_DATE\", \"FISCAL_YEAR_GL_DATE\", \"TRANSACTION_CURRENCY\", \"UNIT_LIST_PRICE_USD\", \"EXTENDED_AMOUNT_USD\", \"EXTENDED_COST_USD\", \"SO_LINE_ID\"})\nin\n    #\"Choose columns\";\r\nshared XXCOH_BACKLOG_VIEW = let\n    XXCOH_BACKLOG_VIEW = Value.NativeQuery(Snowflake.Databases(\"mma12090.snowflakecomputing.com\",\"COMPUTE_REPORTING\", [Role=\"GLBMFGOPERATIONSROLE\"]){[Name=\"PROD_DB\"]}[Data], \"SELECT *FROM PROD_DB.APPS.XXCOH_BACKLOG_VIEW\", null, [EnableFolding=true]),\n  #\"Choose columns\" = Table.SelectColumns(XXCOH_BACKLOG_VIEW, {\"ASOF_DATE\", \"BOOKED_DATE\", \"ORDER_NUMBER\", \"ORDER_LINE\", \"ORDER_TYPE\", \"SO_LINE_TYPE\", \"BILLABLE_FLAG\", \"HOLD_STATUS\", \"HOLD_REASON\", \"REPORTING_ENTITY\", \"CUSTOMER_PO\", \"CREATED_BY\", \"ITEM_DESCRIPTION\", \"PRODUCT_LINE\", \"PRODUCT_FAMILY\", \"TECHNICAL_BUSINESS_UNIT\", \"FORECAST_FIELD\", \"COMMODITY\", \"WAREHOUSE\", \"BACKLOG_QUANTITY\", \"ASP_QUANTITY\", \"UNIT_LIST_PRICE\", \"EXTENDED_AMOUNT\", \"APPLICATION_CODE\", \"APPLICATION_CODE_DESC\", \"REQUEST_SHIP_DATE\", \"SCHEDULE_SHIP_DATE\", \"CUSTOMER_NAME\", \"CUSTOMER_ALTERNATE_NAME\", \"CUSTOMER_NUMBER\", \"BILL_TO_COUNTRY\", \"SHIP_TO_COUNTRY\", \"END_USER\", \"SALESPERSON\", \"CUSTOMER_CATEGORY\", \"FISCAL_WEEK_BOOKED\", \"FISCAL_QUARTER_BOOKED\", \"FISCAL_YEAR_BOOKED\", \"TRANSACTION_CURRENCY\", \"UNIT_LIST_PRICE_USD\", \"EXTENDED_AMOUNT_USD\", \"EXTENDED_COST_USD\", \"ORDER_STATUS\", \"LINE_ID\", \"ASOF_DATE_DISP\"})\nin\n    #\"Choose columns\";\r\nshared XXCOH_MS_SHIPMENT_VIEW = let\n    XXCOH_MS_SHIPMENT_VIEW = Value.NativeQuery(Snowflake.Databases(\"mma12090.snowflakecomputing.com\",\"COMPUTE_REPORTING\", [Role=\"GLBMFGOPERATIONSROLE\"]){[Name=\"PROD_DB\"]}[Data], \"SELECT *FROM PROD_DB.APPS.XXCOH_MS_SHIPMENT_VIEW WHERE Technical_Business_Unit='Excimer' \", null, [EnableFolding=true]),\n  #\"Filtered rows\" = Table.SelectRows(XXCOH_MS_SHIPMENT_VIEW, each Date.IsInPreviousNDays([ENTER_DATE], #\"parDays2Load\")),\n  #\"Choose columns\" = Table.SelectColumns(#\"Filtered rows\", {\"ASOF_DATE\", \"ASOF_DATE_DISP\", \"BOOKED_DATE\", \"ORDER_NUMBER\", \"ORDER_LINE\", \"ORDER_TYPE\", \"ACTUAL_SHIPMENT_DATE\", \"REPORTING_ENTITY\", \"ITEM_NUMBER\", \"ITEM_DESCRIPTION\", \"TECHNICAL_BUSINESS_UNIT\", \"WAREHOUSE\", \"CUSTOMER_NAME\", \"CUSTOMER_ALTERNATE_NAME\", \"CUSTOMER_NUMBER\", \"SHIP_TO_COUNTRY\", \"END_USER\", \"SALESPERSON\", \"CUSTOMER_CATEGORY\", \"FISCAL_WEEK_SHIPPED\", \"FISCAL_QUARTER_SHIPPED\", \"FISCAL_YEAR_SHIPPED\", \"EXTENDED_AMOUNT_USD\", \"ORDER_STATUS\", \"LOT_NUMBER\", \"SERIAL_NUMBER\", \"SHIPPING_QUANTITY\", \"SHIPPING_QUANTITY_UOM\", \"LINE_ID\", \"ACTUAL_SHIPPED_VS_PROMISED_SHIPPPED\", \"ACTUAL_SHIPPED_VS_REQUESTED_SHIPPED\"})\nin\n    #\"Choose columns\";\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"XX_FISCAL_DAYS_COHR_TAB","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"XX_FISCAL_DAYS_COHR_TAB.csv"},"attributes":[{"name":"PERIOD_SET_NAME","dataType":"string"},{"name":"CAL_DAY","dataType":"dateTime"},{"name":"FISCAL_WEEK","dataType":"string"},{"name":"FISCAL_YEAR_WEEK","dataType":"string"},{"name":"FISCAL_WEEK_DISP","dataType":"string"},{"name":"FISCAL_MONTH_SORT_VALUE","dataType":"string"},{"name":"FISCAL_QUARTER_DISP","dataType":"string"},{"name":"FISCAL_WEEK_NO","dataType":"double"},{"name":"FISCAL_MONTH_WEEK_NO","dataType":"double"},{"name":"FISCAL_QTR_WEEK","dataType":"string"},{"name":"FISCAL_QTR_WEEK_NO","dataType":"double"},{"name":"GL_PERIOD","dataType":"string"},{"name":"PQ_LAST_GL_PERIOD","dataType":"string"},{"name":"PERIOD_YEAR","dataType":"double"},{"name":"FISCAL_YEAR","dataType":"string"},{"name":"QUARTER_NUM","dataType":"double"},{"name":"FISCAL_QUARTER","dataType":"string"},{"name":"FYFQ","dataType":"string"},{"name":"PRIOR_FYFQ","dataType":"string"},{"name":"PERIOD_NAME","dataType":"string"},{"name":"PERIOD_NUM","dataType":"double"},{"name":"FISCAL_DAY","dataType":"double"},{"name":"WEEK_START_DATE","dataType":"date"},{"name":"WEEK_END_DATE","dataType":"date"},{"name":"PERIOD_START_DATE","dataType":"dateTime"},{"name":"PERIOD_END_DATE","dataType":"dateTime"},{"name":"QUARTER_START_DATE","dataType":"dateTime"},{"name":"QUARTER_END_DATE","dataType":"dateTime"},{"name":"YEAR_START_DATE","dataType":"dateTime"},{"name":"YEAR_END_DATE","dataType":"dateTime"},{"name":"PERIOD_MONTH","dataType":"string"},{"name":"FC_PERIOD_ID","dataType":"double"},{"name":"FC_QUARTER_ID","dataType":"double"},{"name":"FC_WEEK_ID","dataType":"double"},{"name":"FC_YEAR_OFFSET","dataType":"double"},{"name":"FC_QUARTER_OFFSET","dataType":"double"},{"name":"FC_PERIOD_OFFSET","dataType":"double"},{"name":"FC_WEEK_OFFSET","dataType":"double"},{"name":"FC_DAYS_OFFSET","dataType":"double"},{"name":"FC_HALF","dataType":"string"},{"name":"NQ_FIRST_FISCAL_WEEK","dataType":"string"},{"name":"PQ_LAST_FISCAL_WEEK","dataType":"string"},{"name":"CALENDAR_YEAR","dataType":"double"},{"name":"CALENDAR_MONTH","dataType":"double"},{"name":"CALENDAR_YEARMONTHID","dataType":"string"},{"name":"CALENDAR_MONTHNAME","dataType":"string"},{"name":"CALENDAR_MONTHNAMESHORT","dataType":"string"},{"name":"CALENDAR_ISO_WEEK","dataType":"double"},{"name":"CALENDAR_US_WEEK","dataType":"double"},{"name":"CALENDAR_YEAR_SHORT","dataType":"string"},{"name":"CALENDAR_MTH_YEAR","dataType":"string"},{"name":"DAY_NAME","dataType":"string"},{"name":"DAY_OF_WEEK","dataType":"double"},{"name":"WORKING_DAY_FLAG","dataType":"double"},{"name":"CQ_LAST_FISCAL_WEEK","dataType":"string"},{"name":"ROW_CREATION_DATE","dataType":"date"},{"name":"WEEK_END_FLAG","dataType":"string"},{"name":"MONTH_END_FLAG","dataType":"string"},{"name":"QUARTER_END_FLAG","dataType":"string"},{"name":"YEAR_END_FLAG","dataType":"string"},{"name":"FISCAL_WEEK_INDICATOR","dataType":"string"},{"name":"FISCAL_WEEK_INDICATOR_SORT","dataType":"double"},{"name":"FISCAL_MONTH_INDICATOR","dataType":"string"},{"name":"FISCAL_MONTH_INDICATOR_SORT","dataType":"double"},{"name":"FISCAL_QUARTER_INDICATOR","dataType":"string"},{"name":"FISCAL_QUARTER_INDICATOR_SORT","dataType":"double"},{"name":"FISCAL_YEAR_INDICATOR","dataType":"string"},{"name":"FISCAL_YEAR_INDICATOR_SORT","dataType":"double"},{"name":"EXTRACT_DATE","dataType":"dateTime"}]}]}