{"name":"Flow_SPC_MP","description":"Flow for SPC data Medium Power Sandbox.","version":"1.0","culture":"en-US","modifiedTime":"2022-04-12T20:05:04.8539001+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"LEAP300C_SPC_Endtest":{"queryId":"b65961a4-00aa-463f-a9e1-dd8fdcd1e552","queryName":"LEAP300C_SPC_Endtest","loadEnabled":true},"LEAP300C_SPC_Montage":{"queryId":"e89cb6b9-208b-4237-bd06-9bfaa75851b7","queryName":"LEAP300C_SPC_Montage","loadEnabled":true}},"document":"section Section1;\r\nshared LEAP300C_SPC_Endtest = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each ([Extension] = \".xlsx\")),\r\n  #\"Filtered rows 1\" = Table.SelectRows(#\"Filtered rows\", each Text.Contains([Name], \"LEAP300C_Endtest\")),\r\n  Navigation = #\"Filtered rows 1\"{[Name = \"MP-CustomReportData_LEAP300C_Endtest_CustomReportDataResult.xlsx\", #\"Folder Path\" = \"https://cohrinc.sharepoint.com/teams/Operations/Excimer-Göttingen/Manuf. Engineering/Shared Documents/Production Data/MP/\"]}[Content],\r\n  #\"Imported Excel workbook\" = Excel.Workbook(Navigation, null, true),\r\n  #\"Expanded Data\" = Table.ExpandTableColumn(#\"Imported Excel workbook\", \"Data\", {\"Column1\", \"Column2\", \"Column3\", \"Column4\", \"Column5\", \"Column6\", \"Column7\", \"Column8\", \"Column9\", \"Column10\", \"Column11\", \"Column12\", \"Column13\", \"Column14\", \"Column15\", \"Column16\", \"Column17\", \"Column18\", \"Column19\", \"Column20\", \"Column21\"}, {\"Column1\", \"Column2\", \"Column3\", \"Column4\", \"Column5\", \"Column6\", \"Column7\", \"Column8\", \"Column9\", \"Column10\", \"Column11\", \"Column12\", \"Column13\", \"Column14\", \"Column15\", \"Column16\", \"Column17\", \"Column18\", \"Column19\", \"Column20\", \"Column21\"}),\r\n  #\"Promoted headers\" = Table.PromoteHeaders(#\"Expanded Data\", [PromoteAllScalars = true]),\r\n  #\"Choose columns\" = Table.SelectColumns(#\"Promoted headers\", {\"WORK_ORDER\", \"SERIAL_NUMBER\", \"PART_NUMBER\", \"MEASUREMENT\", \"DATA_VALUE\"}),\r\n  #\"Pivoted column\" = Table.Pivot(Table.TransformColumnTypes(#\"Choose columns\", {{\"MEASUREMENT\", type text}}), List.Distinct(Table.TransformColumnTypes(#\"Choose columns\", {{\"MEASUREMENT\", type text}})[MEASUREMENT]), \"MEASUREMENT\", \"DATA_VALUE\"),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Pivoted column\", {{\"WORK_ORDER\", type text}, {\"SERIAL_NUMBER\", type text}, {\"PART_NUMBER\", type text}, {\"AI Counter\", type number}, {\"Peak to Peak Distribution\", type number}, {\"Spikes above Bad Pulse\", type number}, {\"Spikes above Peak to Peak\", type number}, {\"GCS HV F\", type number}, {\"GCS HV R\", type number}, {\"GCS Pulse Width R\", type number}, {\"Energy Monitor Reading\", type number}, {\"GCS Pulse Width F\", type number}, {\"Energy End\", type number}, {\"Energy Min\", type number}, {\"Energy Max\", type number}, {\"HV End\", type number}, {\"Energy Deviation Max\", type number}, {\"Energy Deviation Average\", type number}, {\"Tube Temperature Average\", type number}, {\"External Power Start\", type number}, {\"External Power End\", type number}, {\"Tube Temperature Deviation\", type number}, {\"Tube Temperature Start\", type number}, {\"Tube Temperature End\", type number}, {\"Peak to Peak Fluctuations Max\", type number}, {\"Peak to Peak Fluctuations Average\", type number}, {\"P2P Fluctuations 6 Sigma\", type number}, {\"HI Counter\", type number}, {\"HV Rise Total\", type number}, {\"Energy Monitor Drift\", type number}, {\"Pulse Duration\", type number}, {\"Pulse TIS\", type number}, {\"Beam Width FWHM Short Axis\", type number}, {\"Beam Width FWHM Long Axis\", type number}, {\"Beam Width 1e2 Short Axis\", type number}, {\"Beam Width 1e2 Long Axis\", type number}, {\"Divergency FWHM Short Axis\", type number}, {\"Divergency FWHM Long Axis\", type number}, {\"Energy (1500V)\", type number}, {\"Energy (1550V)\", type number}, {\"Energy (1600V)\", type number}, {\"HV Start\", type number}, {\"Energy Start\", type number}, {\"HV\", type number}, {\"EMon Energy Drift\", type number}, {\"Energy (1650V)\", type number}, {\"Energy (1700V)\", type number}, {\"Energy (1750V)\", type number}, {\"Energy (1800V)\", type number}, {\"Peak to Peak Fluctuations Average Deviation\", type number}, {\"HV Change\", type number}, {\"Energy Deviation (1500V)\", type number}, {\"Energy Deviation (1550V)\", type number}, {\"Energy Deviation (1600V)\", type number}, {\"Energy Deviation (1650V)\", type number}, {\"Energy Deviation (1700V)\", type number}, {\"Energy Deviation (1750V)\", type number}, {\"Energy Deviation (1800V)\", type number}, {\"HV Rise\", type number}, {\"Energy Drop\", type number}, {\"Energy Drift\", type number}}),\r\n  #\"Replaced errors\" = Table.ReplaceErrorValues(#\"Changed column type\", {{\"WORK_ORDER\", 0}, {\"SERIAL_NUMBER\", 0}, {\"PART_NUMBER\", 0}, {\"AI Counter\", 0}, {\"Peak to Peak Distribution\", 0}, {\"Spikes above Bad Pulse\", 0}, {\"Spikes above Peak to Peak\", 0}, {\"GCS HV F\", 0}, {\"GCS HV R\", 0}, {\"GCS Pulse Width R\", 0}, {\"Energy Monitor Reading\", 0}, {\"GCS Pulse Width F\", 0}, {\"Energy End\", 0}, {\"Energy Min\", 0}, {\"Energy Max\", 0}, {\"HV End\", 0}, {\"Energy Deviation Max\", 0}, {\"Energy Deviation Average\", 0}, {\"Tube Temperature Average\", 0}, {\"External Power Start\", 0}, {\"External Power End\", 0}, {\"Tube Temperature Deviation\", 0}, {\"Tube Temperature Start\", 0}, {\"Tube Temperature End\", 0}, {\"Peak to Peak Fluctuations Max\", 0}, {\"Peak to Peak Fluctuations Average\", 0}, {\"P2P Fluctuations 6 Sigma\", 0}, {\"HI Counter\", 0}, {\"HV Rise Total\", 0}, {\"Energy Monitor Drift\", 0}, {\"Pulse Duration\", 0}, {\"Pulse TIS\", 0}, {\"Beam Width FWHM Short Axis\", 0}, {\"Beam Width FWHM Long Axis\", 0}, {\"Beam Width 1e2 Short Axis\", 0}, {\"Beam Width 1e2 Long Axis\", 0}, {\"Divergency FWHM Short Axis\", 0}, {\"Divergency FWHM Long Axis\", 0}, {\"Energy (1500V)\", 0}, {\"Energy (1550V)\", 0}, {\"Energy (1600V)\", 0}, {\"HV Start\", 0}, {\"Energy Start\", 0}, {\"HV\", 0}, {\"EMon Energy Drift\", 0}, {\"Energy (1650V)\", 0}, {\"Energy (1700V)\", 0}, {\"Energy (1750V)\", 0}, {\"Energy (1800V)\", 0}, {\"Peak to Peak Fluctuations Average Deviation\", 0}, {\"HV Change\", 0}, {\"Energy Deviation (1500V)\", 0}, {\"Energy Deviation (1550V)\", 0}, {\"Energy Deviation (1600V)\", 0}, {\"Energy Deviation (1650V)\", 0}, {\"Energy Deviation (1700V)\", 0}, {\"Energy Deviation (1750V)\", 0}, {\"Energy Deviation (1800V)\", 0}, {\"HV Rise\", 0}, {\"Energy Drop\", 0}, {\"Energy Drift\", 0}})\r\nin\r\n  #\"Replaced errors\";\r\nshared LEAP300C_SPC_Montage = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each ([Extension] = \".xlsx\")),\r\n  #\"Filtered rows 1\" = Table.SelectRows(#\"Filtered rows\", each Text.Contains([Name], \"LEAP300C_Montage\")),\r\n  Navigation = #\"Filtered rows 1\"{[Name = \"MP-CustomReportData_LEAP300C_Montage_CustomReportDataResult.xlsx\", #\"Folder Path\" = \"https://cohrinc.sharepoint.com/teams/Operations/Excimer-Göttingen/Manuf. Engineering/Shared Documents/Production Data/MP/\"]}[Content],\r\n  #\"Imported Excel workbook\" = Excel.Workbook(Navigation, null, true),\r\n  #\"Expanded Data\" = Table.ExpandTableColumn(#\"Imported Excel workbook\", \"Data\", {\"Column1\", \"Column2\", \"Column3\", \"Column4\", \"Column5\", \"Column6\", \"Column7\", \"Column8\", \"Column9\", \"Column10\", \"Column11\", \"Column12\", \"Column13\", \"Column14\", \"Column15\", \"Column16\", \"Column17\", \"Column18\", \"Column19\", \"Column20\", \"Column21\"}, {\"Column1\", \"Column2\", \"Column3\", \"Column4\", \"Column5\", \"Column6\", \"Column7\", \"Column8\", \"Column9\", \"Column10\", \"Column11\", \"Column12\", \"Column13\", \"Column14\", \"Column15\", \"Column16\", \"Column17\", \"Column18\", \"Column19\", \"Column20\", \"Column21\"}),\r\n  #\"Promoted headers\" = Table.PromoteHeaders(#\"Expanded Data\", [PromoteAllScalars = true]),\r\n  #\"Choose columns\" = Table.SelectColumns(#\"Promoted headers\", {\"WORK_ORDER\", \"SERIAL_NUMBER\", \"PART_NUMBER\", \"MEASUREMENT\", \"DATA_VALUE\"}),\r\n  #\"Pivoted column\" = Table.Pivot(Table.TransformColumnTypes(#\"Choose columns\", {{\"MEASUREMENT\", type text}}), List.Distinct(Table.TransformColumnTypes(#\"Choose columns\", {{\"MEASUREMENT\", type text}})[MEASUREMENT]), \"MEASUREMENT\", \"DATA_VALUE\"),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Pivoted column\", {{\"WORK_ORDER\", type text}, {\"SERIAL_NUMBER\", type text}, {\"PART_NUMBER\", type text}, {\"Laser Tube SN\", type text}, {\"MP Grounding Block\", type number}, {\"MP ELT Module Baseplate\", type number}, {\"MP Front Panel Chassis\", type number}, {\"MP Line Filter Z1\", type number}, {\"MP Power Supply 24V\", type number}, {\"MP Frequency Converter\", type number}, {\"MP Trapp Module\", type number}, {\"MP Door Left\", type number}, {\"MP Panel Center\", type number}, {\"MP Door Right\", type number}, {\"MP HV Power Supply\", type number}, {\"MP HV Power Supply W7 J1\", type number}, {\"MP Laser Tube\", type number}, {\"MP Dust Filter Power Supply K Version\", type number}, {\"MP Dust Filter Holder CP303\", type number}, {\"MP Dust Filter Power Supply CP303\", type number}, {\"MP Dust Filter Cover CP303\", type number}, {\"MP Support Pulser\", type number}, {\"MP Chassis Cover Back\", type number}, {\"MP Chassis Top\", type number}, {\"MP Chassis Cover Right\", type number}, {\"MP Chassis Bottom\", type number}, {\"MP Vacuum Pump\", type number}, {\"MP Gascirculation Motor\", type number}, {\"MP Gas Input Module\", type number}, {\"Isolation Test Voltage DC\", type number}, {\"Leakage Current HV Off\", type number}, {\"Pressure Drop Manifold\", type number}, {\"Gas Pressure Drop\", type number}, {\"Evacuation Time\", type number}, {\"Water Pressure Drop\", type number}, {\"Laser Software Version\", type text}, {\"Drawing Number\", type text}, {\"NPS SN\", type text}, {\"NPS Type\", type text}, {\"LCB FPGA Version\", type text}}),\r\n  #\"Replaced errors\" = Table.ReplaceErrorValues(#\"Changed column type\", {{\"MP Grounding Block\", 0}, {\"MP ELT Module Baseplate\", 0}, {\"MP Front Panel Chassis\", 0}, {\"MP Line Filter Z1\", 0}, {\"MP Power Supply 24V\", 0}, {\"MP Frequency Converter\", 0}, {\"MP Trapp Module\", 0}, {\"MP Door Left\", 0}, {\"MP Panel Center\", 0}, {\"MP Door Right\", 0}, {\"MP HV Power Supply\", 0}, {\"MP HV Power Supply W7 J1\", 0}, {\"MP Laser Tube\", 0}, {\"MP Dust Filter Power Supply K Version\", 0}, {\"MP Dust Filter Holder CP303\", 0}, {\"MP Dust Filter Power Supply CP303\", 0}, {\"MP Dust Filter Cover CP303\", 0}, {\"MP Support Pulser\", 0}, {\"MP Chassis Cover Back\", 0}, {\"MP Chassis Top\", 0}, {\"MP Chassis Cover Right\", 0}, {\"MP Chassis Bottom\", 0}, {\"MP Vacuum Pump\", 0}, {\"MP Gascirculation Motor\", 0}, {\"MP Gas Input Module\", 0}, {\"Isolation Test Voltage DC\", 0}, {\"Leakage Current HV Off\", 0}, {\"Pressure Drop Manifold\", 0}, {\"Gas Pressure Drop\", 0}, {\"Evacuation Time\", 0}, {\"Water Pressure Drop\", 0}, {\"Laser Software Version\", 0}})\r\nin\r\n  #\"Replaced errors\";\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"LEAP300C_SPC_Endtest","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"LEAP300C_SPC_Endtest.csv"},"attributes":[{"name":"WORK_ORDER","dataType":"string"},{"name":"SERIAL_NUMBER","dataType":"string"},{"name":"PART_NUMBER","dataType":"string"},{"name":"AI Counter","dataType":"double"},{"name":"Peak to Peak Distribution","dataType":"double"},{"name":"Spikes above Bad Pulse","dataType":"double"},{"name":"Spikes above Peak to Peak","dataType":"double"},{"name":"GCS HV F","dataType":"double"},{"name":"GCS HV R","dataType":"double"},{"name":"GCS Pulse Width R","dataType":"double"},{"name":"Energy Monitor Reading","dataType":"double"},{"name":"GCS Pulse Width F","dataType":"double"},{"name":"Energy End","dataType":"double"},{"name":"Energy Min","dataType":"double"},{"name":"Energy Max","dataType":"double"},{"name":"HV End","dataType":"double"},{"name":"Energy Deviation Max","dataType":"double"},{"name":"Energy Deviation Average","dataType":"double"},{"name":"Tube Temperature Average","dataType":"double"},{"name":"External Power Start","dataType":"double"},{"name":"External Power End","dataType":"double"},{"name":"Tube Temperature Deviation","dataType":"double"},{"name":"Tube Temperature Start","dataType":"double"},{"name":"Tube Temperature End","dataType":"double"},{"name":"Peak to Peak Fluctuations Max","dataType":"double"},{"name":"Peak to Peak Fluctuations Average","dataType":"double"},{"name":"P2P Fluctuations 6 Sigma","dataType":"double"},{"name":"HI Counter","dataType":"double"},{"name":"HV Rise Total","dataType":"double"},{"name":"Energy Monitor Drift","dataType":"double"},{"name":"Pulse Duration","dataType":"double"},{"name":"Pulse TIS","dataType":"double"},{"name":"Beam Width FWHM Short Axis","dataType":"double"},{"name":"Beam Width FWHM Long Axis","dataType":"double"},{"name":"Beam Width 1e2 Short Axis","dataType":"double"},{"name":"Beam Width 1e2 Long Axis","dataType":"double"},{"name":"Divergency FWHM Short Axis","dataType":"double"},{"name":"Divergency FWHM Long Axis","dataType":"double"},{"name":"Energy (1500V)","dataType":"double"},{"name":"Energy (1550V)","dataType":"double"},{"name":"Energy (1600V)","dataType":"double"},{"name":"HV Start","dataType":"double"},{"name":"Energy Start","dataType":"double"},{"name":"HV","dataType":"double"},{"name":"EMon Energy Drift","dataType":"double"},{"name":"Energy (1650V)","dataType":"double"},{"name":"Energy (1700V)","dataType":"double"},{"name":"Energy (1750V)","dataType":"double"},{"name":"Energy (1800V)","dataType":"double"},{"name":"Peak to Peak Fluctuations Average Deviation","dataType":"double"},{"name":"HV Change","dataType":"double"},{"name":"Energy Deviation (1500V)","dataType":"double"},{"name":"Energy Deviation (1550V)","dataType":"double"},{"name":"Energy Deviation (1600V)","dataType":"double"},{"name":"Energy Deviation (1650V)","dataType":"double"},{"name":"Energy Deviation (1700V)","dataType":"double"},{"name":"Energy Deviation (1750V)","dataType":"double"},{"name":"Energy Deviation (1800V)","dataType":"double"},{"name":"HV Rise","dataType":"double"},{"name":"Energy Drop","dataType":"double"},{"name":"Energy Drift","dataType":"double"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-04-12T20:05:22.1792017+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/5381e11f-f409-4b7a-bd83-a28f9c2bfa50/LEAP300C_SPC_Endtest.csv?snapshot=2022-04-12T20%3A05%3A22.1525218Z"}]},{"$type":"LocalEntity","name":"LEAP300C_SPC_Montage","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"LEAP300C_SPC_Montage.csv"},"attributes":[{"name":"WORK_ORDER","dataType":"string"},{"name":"SERIAL_NUMBER","dataType":"string"},{"name":"PART_NUMBER","dataType":"string"},{"name":"Laser Tube SN","dataType":"string"},{"name":"MP Grounding Block","dataType":"double"},{"name":"MP ELT Module Baseplate","dataType":"double"},{"name":"MP Front Panel Chassis","dataType":"double"},{"name":"MP Line Filter Z1","dataType":"double"},{"name":"MP Power Supply 24V","dataType":"double"},{"name":"MP Frequency Converter","dataType":"double"},{"name":"MP Trapp Module","dataType":"double"},{"name":"MP Door Left","dataType":"double"},{"name":"MP Panel Center","dataType":"double"},{"name":"MP Door Right","dataType":"double"},{"name":"MP HV Power Supply","dataType":"double"},{"name":"MP HV Power Supply W7 J1","dataType":"double"},{"name":"MP Laser Tube","dataType":"double"},{"name":"MP Dust Filter Power Supply K Version","dataType":"double"},{"name":"MP Dust Filter Holder CP303","dataType":"double"},{"name":"MP Dust Filter Power Supply CP303","dataType":"double"},{"name":"MP Dust Filter Cover CP303","dataType":"double"},{"name":"MP Support Pulser","dataType":"double"},{"name":"MP Chassis Cover Back","dataType":"double"},{"name":"MP Chassis Top","dataType":"double"},{"name":"MP Chassis Cover Right","dataType":"double"},{"name":"MP Chassis Bottom","dataType":"double"},{"name":"MP Vacuum Pump","dataType":"double"},{"name":"MP Gascirculation Motor","dataType":"double"},{"name":"MP Gas Input Module","dataType":"double"},{"name":"Isolation Test Voltage DC","dataType":"double"},{"name":"Leakage Current HV Off","dataType":"double"},{"name":"Pressure Drop Manifold","dataType":"double"},{"name":"Gas Pressure Drop","dataType":"double"},{"name":"Evacuation Time","dataType":"double"},{"name":"Water Pressure Drop","dataType":"double"},{"name":"Laser Software Version","dataType":"string"},{"name":"Drawing Number","dataType":"string"},{"name":"NPS SN","dataType":"string"},{"name":"NPS Type","dataType":"string"},{"name":"LCB FPGA Version","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-04-12T20:05:22.21046+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/5381e11f-f409-4b7a-bd83-a28f9c2bfa50/LEAP300C_SPC_Montage.csv?snapshot=2022-04-12T20%3A05%3A22.1705116Z"}]}]}