{"name":"Flow_General Data Daily","description":"General data files with daily refresh (once a day).","version":"1.0","culture":"en-US","modifiedTime":"2022-06-09T12:57:31.8060914+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":true,"queriesMetadata":{"Transform Sample File":{"queryId":"a256dae3-e2cf-4950-9648-67b2c2e2a058","queryName":"Transform Sample File","queryGroupId":"56b03f15-b0af-4bb7-80dc-0724afce7b2c"},"Parameter1":{"queryId":"d151b1c0-5b0c-4c68-b4bc-4fb03fde2d0f","queryName":"Parameter1","queryGroupId":"c55b0cf5-047d-4542-9778-4e2ce8c90a59"},"Sample File":{"queryId":"7c5e22d5-188b-4589-b2f4-0956a7570319","queryName":"Sample File","queryGroupId":"c55b0cf5-047d-4542-9778-4e2ce8c90a59"},"Transform File":{"queryId":"76e4f163-c520-4d05-a214-17074be52446","queryName":"Transform File","queryGroupId":"c55b0cf5-047d-4542-9778-4e2ce8c90a59"},"Escapes":{"queryId":"d45bf765-9002-46e3-a431-9ceaf4d0e78c","queryName":"Escapes","queryGroupId":"fae0b287-a26d-4a58-a05a-e0279df335c5"},"GEP Internal Customer Satisfaction":{"queryId":"aa3e981a-daa6-4b96-ba4d-bd5f9b66f148","queryName":"GEP Internal Customer Satisfaction","queryGroupId":"fae0b287-a26d-4a58-a05a-e0279df335c5"},"Parameter12":{"queryId":"802c3a66-8907-48e4-8c0a-ecfaad57af11","queryName":"Parameter12","queryGroupId":"e39c62f8-3bcc-47ba-beba-61c54a10160a"},"Sample File2":{"queryId":"aeeabff1-cc97-4413-b071-79def3552f9b","queryName":"Sample File2","queryGroupId":"e39c62f8-3bcc-47ba-beba-61c54a10160a"},"Transform File2":{"queryId":"30357eb3-d830-4dad-8a7b-622c4d1a57c2","queryName":"Transform File2","queryGroupId":"e39c62f8-3bcc-47ba-beba-61c54a10160a"},"Transform Sample File2":{"queryId":"57409193-2f25-4c7e-802a-2a14588bfb8f","queryName":"Transform Sample File2","queryGroupId":"40d28958-91bc-4d0d-b290-3cdd7f4f4411"},"Master-Cleaning-List":{"queryId":"48ee7c65-f1bc-4a6e-98ec-771221d4b793","queryName":"Master-Cleaning-List","loadEnabled":true},"Cumulus_Deviations":{"queryId":"83698f34-8040-4987-8118-941622ce966c","queryName":"Cumulus_Deviations","queryGroupId":"fae0b287-a26d-4a58-a05a-e0279df335c5"},"Sample file (2)":{"queryId":"5aad6cd6-ee0a-4a27-8d13-2da041ea2123","queryName":"Sample file (2)","queryGroupId":"26c7ecda-c1a7-47e2-9851-79b2ac9e66a4"},"Parameter":{"queryId":"32faae05-8451-43b0-994d-6a78eefb8a45","queryName":"Parameter","queryGroupId":"26c7ecda-c1a7-47e2-9851-79b2ac9e66a4"},"Transform Sample file (2)":{"queryId":"87a99a4a-c0ae-4d51-869c-6c654342046d","queryName":"Transform Sample file (2)","queryGroupId":"b4b3ec88-7642-4839-90ec-4c7b8fd6a610"},"Transform file (2)":{"queryId":"41bf6329-9fe1-4c05-8bf9-7285d8e53ede","queryName":"Transform file (2)","queryGroupId":"26c7ecda-c1a7-47e2-9851-79b2ac9e66a4"},"Cumulus_Shortages":{"queryId":"522be231-e098-4d7e-8c21-d6e5da70173c","queryName":"Cumulus_Shortages","loadEnabled":true},"Sample file (3)":{"queryId":"ebe2693b-9781-447b-9d24-c558e4076e91","queryName":"Sample file (3)","queryGroupId":"7b4fc3f5-e9ba-43cc-be7e-066e90dc0662"},"Parameter (2)":{"queryId":"344f731c-37b0-40a7-b969-cae43cd9979b","queryName":"Parameter (2)","queryGroupId":"7b4fc3f5-e9ba-43cc-be7e-066e90dc0662"},"Transform Sample file (3)":{"queryId":"629c0044-552d-4680-acfa-f1cf175fec0c","queryName":"Transform Sample file (3)","queryGroupId":"168a4ac5-ad8e-44f3-9270-23735a21c431"},"Transform file (3)":{"queryId":"97a3d96b-a067-49cb-a387-b5e04981e7db","queryName":"Transform file (3)","queryGroupId":"7b4fc3f5-e9ba-43cc-be7e-066e90dc0662"},"Cumulus_Equipment":{"queryId":"61f5ea29-c5f0-412c-b787-de8d54bcb46d","queryName":"Cumulus_Equipment","loadEnabled":true},"Sample file (4)":{"queryId":"0c2e998e-32d6-447b-94fd-0e2d6f0e4699","queryName":"Sample file (4)","queryGroupId":"29750181-0419-4931-9e13-5d62468c3d6e"},"Parameter (3)":{"queryId":"c778896d-f415-4a26-80bf-3742e3c0e37f","queryName":"Parameter (3)","queryGroupId":"29750181-0419-4931-9e13-5d62468c3d6e"},"Transform Sample file (4)":{"queryId":"6fec4450-88de-4649-9851-75db575f776b","queryName":"Transform Sample file (4)","queryGroupId":"c75e3e3f-24f1-4274-8963-67281cccb76a"},"Transform file (4)":{"queryId":"a2d31000-e59c-4dfe-b927-db1966b9207e","queryName":"Transform file (4)","queryGroupId":"29750181-0419-4931-9e13-5d62468c3d6e"},"ChangeRequests":{"queryId":"ba168f30-ebd9-4c38-bba9-013f0d25260d","queryName":"ChangeRequests","loadEnabled":true},"Sample file (5)":{"queryId":"1a040bd4-7e25-421c-a811-d7f846a14e8c","queryName":"Sample file (5)","queryGroupId":"430b5806-a86d-4603-8613-dc18dfcac97c"},"Parameter (4)":{"queryId":"8ad8ddb3-435b-4e73-873c-bf4b82fa15a2","queryName":"Parameter (4)","queryGroupId":"430b5806-a86d-4603-8613-dc18dfcac97c"},"Transform Sample file (5)":{"queryId":"7f7dc0ee-cc07-4b32-93f3-eca55b7b58d6","queryName":"Transform Sample file (5)","queryGroupId":"ea105cb7-a12a-4499-8b33-2adc23498129"},"Transform file (5)":{"queryId":"125385e4-5f13-48a1-8766-967ec4c7bb1f","queryName":"Transform file (5)","queryGroupId":"430b5806-a86d-4603-8613-dc18dfcac97c"},"XXCOH_WIP_TRX_TAB_OldNotNativeSQL":{"queryId":"67ca26ad-6ff7-4c99-8014-c2c6ee577ad7","queryName":"XXCOH_WIP_TRX_TAB_OldNotNativeSQL"},"XXCOH_MI_WIP_DETAIL_TAB_OldNotNatiiveSQL":{"queryId":"f657346f-30a3-4ced-82e5-52fd78c63190","queryName":"XXCOH_MI_WIP_DETAIL_TAB_OldNotNatiiveSQL"},"VHP-Electrodes_BlastedArea":{"queryId":"c6a32eab-6e50-4e67-9fd5-78a4a59e1eb1","queryName":"VHP-Electrodes_BlastedArea"},"VHP-Electrodes_CoatingData":{"queryId":"4586ba92-db4e-49b3-8d0c-c1ccc640ae2e","queryName":"VHP-Electrodes_CoatingData"},"Sample file (6)":{"queryId":"4b28bfeb-d971-40f8-862e-743f6404df17","queryName":"Sample file (6)","queryGroupId":"23c6368c-0ede-48c5-b82e-ade3b06469f7"},"Parameter (5)":{"queryId":"5bb01f34-914b-4319-b686-9da602a28f4c","queryName":"Parameter (5)","queryGroupId":"23c6368c-0ede-48c5-b82e-ade3b06469f7"},"Transform Sample file (6)":{"queryId":"6d035ff0-e5b0-4272-8e19-0c6b9184e154","queryName":"Transform Sample file (6)","queryGroupId":"def9b584-1e4d-43b9-a38f-13dd5ddbe665"},"Transform file (6)":{"queryId":"aada6bab-5a3f-4b8f-8bc1-a3db78e15a95","queryName":"Transform file (6)","queryGroupId":"23c6368c-0ede-48c5-b82e-ade3b06469f7"},"Sample file (7)":{"queryId":"049821e2-d7b3-4adb-bd8a-9a94451b5263","queryName":"Sample file (7)","queryGroupId":"48e6875a-5ba4-4ea8-98bc-02bd31b47f51"},"Parameter (6)":{"queryId":"2c5bdd6c-3f1a-48c1-9752-a667e200e828","queryName":"Parameter (6)","queryGroupId":"48e6875a-5ba4-4ea8-98bc-02bd31b47f51"},"Transform Sample file (7)":{"queryId":"8eaba720-01d6-4a60-82fd-d3202bb50e1d","queryName":"Transform Sample file (7)","queryGroupId":"f5892ce5-1234-4159-b723-6fe3d0cf44e3"},"Transform file (7)":{"queryId":"c99df1af-c2f1-40b6-ba89-825a519b0d17","queryName":"Transform file (7)","queryGroupId":"48e6875a-5ba4-4ea8-98bc-02bd31b47f51"},"XXCOH_WIP_TRX_TAB":{"queryId":"ffc900f7-aeb1-45e5-8f43-e60380245307","queryName":"XXCOH_WIP_TRX_TAB","loadEnabled":true},"XXCOH_MI_WIP_DETAIL_TAB":{"queryId":"b278cda9-bd52-46de-aca8-a83e372956c3","queryName":"XXCOH_MI_WIP_DETAIL_TAB","loadEnabled":true}},"document":"section Section1;\r\nshared #\"Transform Sample File\" = let\r\n    Source = Excel.Workbook(Parameter1, null, true),\r\n    tbl_Escapes_Table = Source{[Item = \"tbl_Escapes\", Kind = \"Table\"]}[Data]\r\nin\r\n    tbl_Escapes_Table;\r\nshared Parameter1 = let\r\n    Parameter1 = #\"Sample File\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type binary, BinaryIdentifier = #\"Sample File\"]\r\nin\r\n    Parameter1;\r\nshared #\"Sample File\" = let\r\n    Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n    #\"Filtered Rows\" = Table.SelectRows(Source, each [Name] = \"Escapes - RR Montage Werk3.xlsx\"),\r\n    Navigation1 = #\"Filtered Rows\"{0}[Content]\r\nin\r\n    Navigation1;\r\nshared #\"Transform File\" = let\r\n    Source = (Parameter1 as binary) => let\r\n    Source = Excel.Workbook(Parameter1, null, true),\r\n    tbl_Escapes_Table = Source{[Item=\"tbl_Escapes\",Kind=\"Table\"]}[Data]\r\nin\r\n    tbl_Escapes_Table\r\nin\r\n    Source;\r\nshared Escapes = let\r\n    Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n    #\"Filtered Rows\" = Table.SelectRows(Source, each [Name] = \"Escapes - RR Montage Werk3.xlsx\"),\r\n    #\"Invoke Custom Function1\" = Table.AddColumn(#\"Filtered Rows\", \"Transform File\", each #\"Transform File\"([Content])),\r\n    #\"Renamed Columns1\" = Table.RenameColumns(#\"Invoke Custom Function1\", {\"Name\", \"Source.Name\"}),\r\n    #\"Removed Other Columns1\" = Table.SelectColumns(#\"Renamed Columns1\", {\"Source.Name\", \"Transform File\"}),\r\n    #\"Expanded Table Column1\" = Table.ExpandTableColumn(#\"Removed Other Columns1\", \"Transform File\", Table.ColumnNames(#\"Transform File\"(#\"Sample File\"))),\r\n    #\"Changed Type\" = Table.TransformColumnTypes(#\"Expanded Table Column1\", {{\"Source.Name\", type text}, {\"Produkt Familie\", type text}, {\"Aufgetreten am\", type date}, {\"Fällig am\", type date}, {\"Gelöst am\", type date}, {\"Fehler oder Defekt\", type text}, {\"Korrektive / Präventive Maßnahme\", type text}, {\"Zuständig\", type text}, {\"Lösung / Implementierung\", type text}}),\r\n    #\"Choose columns\" = Table.SelectColumns(#\"Changed Type\", {\"Produkt Familie\", \"Aufgetreten am\", \"Fällig am\", \"Gelöst am\", \"Fehler oder Defekt\", \"Korrektive / Präventive Maßnahme\", \"Zuständig\", \"Lösung / Implementierung\"}),\r\n    #\"Filtered Rows1\" = Table.SelectRows(#\"Choose columns\", each [Aufgetreten am] <> null)\r\nin\r\n    #\"Filtered Rows1\";\r\nshared #\"GEP Internal Customer Satisfaction\" = let\r\n    Source = SharePoint.Tables(\"https://cohrinc.sharepoint.com/sites/GEPMEPowerBIReports\", [ApiVersion = 15]),\r\n    Navigation = Source{[Id = \"9f55cc1c-2b3f-4bcb-b3c6-b5620bd5c5d3\"]}[Items],\r\n    #\"Choose columns\" = Table.SelectColumns(Navigation, {\"ID\", \"Title\", \"Modified\", \"Created\", \"Fab\", \"Department\", \"CustomerFab\", \"Rating\", \"Feedback\", \"Date\"}),\r\n    #\"Changed column type\" = Table.TransformColumnTypes(#\"Choose columns\", {{\"ID\", type text}, {\"Title\", type text}, {\"Modified\", type date}, {\"Fab\", type text}, {\"Department\", type text}, {\"CustomerFab\", type text}, {\"Feedback\", type text}, {\"Created\", type date}, {\"Date\", type date}, {\"Rating\", Int64.Type}}),\r\n    #\"Renamed columns\" = Table.RenameColumns(#\"Changed column type\", {{\"Title\", \"Customer Department\"}, {\"Fab\", \"Supl Fab\"}, {\"Department\", \"Supl Department\"}})\r\nin\r\n    #\"Renamed columns\";\r\nshared Parameter12 = let\r\n    Parameter12 = #\"Sample File2\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type binary, BinaryIdentifier = #\"Sample File2\"]\r\nin\r\n    Parameter12;\r\nshared #\"Sample File2\" = let\r\n    Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n    #\"Filtered Rows\" = Table.SelectRows(Source, each [Name] = \"Master_Cleaning_List_-_buy_parts_-Traveller_Receipt.xlsm\"),\r\n    Navigation1 = #\"Filtered Rows\"{0}[Content]\r\nin\r\n    Navigation1;\r\nshared #\"Transform File2\" = let\r\n    Source = (Parameter1) => let\r\n    Source = Excel.Workbook(Parameter1, null, true),\r\n    Tabelle4_Table = Source{[Item=\"Tabelle4\",Kind=\"Table\"]}[Data]\r\nin\r\n    Tabelle4_Table\r\nin\r\n    Source;\r\nshared #\"Transform Sample File2\" = let\r\n    Source = Excel.Workbook(Parameter12, null, true),\r\n    Tabelle4_Table = Source{[Item = \"Tabelle4\", Kind = \"Table\"]}[Data]\r\nin\r\n    Tabelle4_Table;\r\nshared #\"Master-Cleaning-List\" = let\r\n    Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n    #\"Filtered Rows\" = Table.SelectRows(Source, each [Name] = \"Master_Cleaning_List_-_buy_parts_-Traveller_Receipt.xlsm\"),\r\n    #\"Invoke Custom Function1\" = Table.AddColumn(#\"Filtered Rows\", \"Transform File\", each #\"Transform File2\"([Content])),\r\n    #\"Renamed Columns1\" = Table.RenameColumns(#\"Invoke Custom Function1\", {\"Name\", \"Source.Name\"}),\r\n    #\"Removed Other Columns1\" = Table.SelectColumns(#\"Renamed Columns1\", {\"Source.Name\", \"Transform File\"}),\r\n    #\"Expanded Table Column1\" = Table.ExpandTableColumn(#\"Removed Other Columns1\", \"Transform File\", Table.ColumnNames(#\"Transform File2\"(#\"Sample File2\"))),\r\n    #\"Changed Type\" = Table.TransformColumnTypes(#\"Expanded Table Column1\", {{\"Source.Name\", type text}, {\"Item Number\", type text}, {\"DESCRIPTION\", type text}, {\"AD2000  Cert. Inspection\", type text}, {\"FAI\", type text}, {\"EMO\", type text}, {\"Miele\", type text}, {\"EMO2\", type text}, {\"Miele2\", type text}, {\"HV-Test\", type text}, {\"Ofen\", type text}, {\"andere\", type text}, {\"Losgröße\", Int64.Type}, {\"Bemerkung\", type text}, {\"Neuer Lieferant\", type text}, {\"Traveller Receipt (Title: Special Reqs)\", type text}, {\"Buyer\", type text}, {\"Receipt Routing\", type text}, {\"Std Lieferant\", type text}, {\"Info\", type text}, {\"Aktualisiert\", type text}, {\"Akt. Von\", type text}}),\r\n    #\"Replaced Errors\" = Table.ReplaceErrorValues(#\"Changed Type\", {{\"Source.Name\", \"blank\"}, {\"Item Number\", \"blank\"}, {\"DESCRIPTION\", \"blank\"}, {\"AD2000  Cert. Inspection\", \"blank\"}, {\"FAI\", \"blank\"}, {\"EMO\", \"blank\"}, {\"Miele\", \"blank\"}, {\"EMO2\", \"blank\"}, {\"Miele2\", \"blank\"}, {\"HV-Test\", \"blank\"}, {\"Ofen\", \"blank\"}, {\"andere\", \"blank\"}, {\"Losgröße\", \"blank\"}, {\"Bemerkung\", \"blank\"}, {\"Neuer Lieferant\", \"blank\"}, {\"Traveller Receipt (Title: Special Reqs)\", \"blank\"}, {\"Buyer\", \"blank\"}, {\"Receipt Routing\", \"blank\"}, {\"Std Lieferant\", \"blank\"}, {\"Info\", \"blank\"}, {\"Aktualisiert\", \"blank\"}, {\"Akt. Von\", \"blank\"}}),\r\n    #\"Removed Other Columns\" = Table.SelectColumns(#\"Replaced Errors\", {\"Item Number\", \"FAI\", \"andere\", \"Losgröße\", \"Bemerkung\", \"Neuer Lieferant\", \"Traveller Receipt (Title: Special Reqs)\", \"Buyer\", \"Receipt Routing\", \"Std Lieferant\", \"Info\", \"Aktualisiert\", \"Akt. Von\"})\r\nin\r\n    #\"Removed Other Columns\";\r\nshared Cumulus_Deviations = let\r\n    Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n    #\"Filtered rows\" = Table.SelectRows(Source, each [Extension] = \".xlsx\"),\r\n    #\"Filtered rows 1\" = Table.SelectRows(#\"Filtered rows\", each Text.Contains([Name], \"DeviationsResult\")),\r\n    #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows 1\", each [Attributes]?[Hidden]? <> true),\r\n    #\"Invoke custom function\" = Table.AddColumn(#\"Filtered hidden files\", \"Transform file (2)\", each #\"Transform file (2)\"([Content])),\r\n    #\"Renamed columns\" = Table.RenameColumns(#\"Invoke custom function\", {{\"Name\", \"Source.Name\"}}),\r\n    #\"Removed other columns\" = Table.SelectColumns(#\"Renamed columns\", {\"Source.Name\", \"Transform file (2)\"}),\r\n    #\"Expanded table column\" = Table.ExpandTableColumn(#\"Removed other columns\", \"Transform file (2)\", Table.ColumnNames(#\"Transform file (2)\"(#\"Sample file (2)\"))),\r\n    #\"Changed column type\" = Table.TransformColumnTypes(#\"Expanded table column\", {{\"Source.Name\", type text}, {\"DEVIATION_NUMBER\", Int64.Type}, {\"CREATE_DATE\", type text}, {\"MODIFY_DATE\", type datetime}, {\"MODIFIED_BY\", type text}, {\"AGILE_DEVIATION\", type text}, {\"ACTIVE\", type logical}, {\"SITE\", type text}, {\"ORG\", type text}, {\"TYPE\", type text}, {\"MODE\", type text}, {\"TITLE\", type any}, {\"REASON\", type any}, {\"DESCRIPTION\", type text}, {\"DEVIATION\", type text}, {\"PROCESS_NAME\", type any}, {\"PROCESS_DESC\", type any}, {\"START_DATE\", type any}, {\"END_DATE\", type any}, {\"PRODUCTION\", type logical}, {\"REWORK\", type logical}, {\"SERVICE\", type logical}, {\"ENGINEERING\", type logical}, {\"DEVIATION_NOTES\", type text}, {\"VALIDATION\", type logical}, {\"VALIDATION_PERMISSION\", type text}, {\"APPLY_PARENT\", type logical}, {\"SHIPPING_RESTRICTION\", type logical}, {\"SHIPPING_RESTRICTION_DESC\", type any}, {\"DEFECT_CODE\", type any}, {\"REJECT_CODE\", type any}, {\"DEVIATION_CODE\", type any}, {\"SUPPLIER\", type any}, {\"SUPPLIER_ADDRESS\", type any}, {\"SUPPLIER_PHONE\", type any}, {\"SUPPLIER_CONTACT_NAME\", type any}, {\"SUPPLIER_EMAIL\", type any}}),\r\n    #\"Changed column type 1\" = Table.TransformColumnTypes(#\"Changed column type\", {{\"TITLE\", type text}, {\"REASON\", type text}, {\"PROCESS_NAME\", type text}, {\"PROCESS_DESC\", type text}, {\"SHIPPING_RESTRICTION_DESC\", type text}, {\"DEFECT_CODE\", type text}, {\"REJECT_CODE\", type text}, {\"DEVIATION_CODE\", type text}, {\"SUPPLIER\", type text}, {\"SUPPLIER_ADDRESS\", type text}, {\"SUPPLIER_PHONE\", type text}, {\"SUPPLIER_CONTACT_NAME\", type text}, {\"SUPPLIER_EMAIL\", type text}, {\"START_DATE\", type datetime}, {\"END_DATE\", type datetime}}),\r\n    #\"Changed column type with locale\" = Table.TransformColumnTypes(#\"Changed column type 1\", {{\"CREATE_DATE\", type datetime}}, \"de-DE\"),\r\n    #\"Inserted Text Before Delimiter\" = Table.AddColumn(#\"Changed column type with locale\", \"Sandbox\", each Text.BeforeDelimiter([Source.Name], \"-\"), type text),\r\n    #\"Choose columns\" = Table.SelectColumns(#\"Inserted Text Before Delimiter\", {\"DEVIATION_NUMBER\", \"CREATE_DATE\", \"MODIFY_DATE\", \"MODIFIED_BY\", \"AGILE_DEVIATION\", \"ACTIVE\", \"SITE\", \"ORG\", \"TYPE\", \"MODE\", \"TITLE\", \"REASON\", \"DESCRIPTION\", \"DEVIATION\", \"PROCESS_NAME\", \"PROCESS_DESC\", \"START_DATE\", \"END_DATE\", \"PRODUCTION\", \"REWORK\", \"SERVICE\", \"ENGINEERING\", \"DEVIATION_NOTES\", \"VALIDATION\", \"VALIDATION_PERMISSION\", \"APPLY_PARENT\", \"SHIPPING_RESTRICTION\", \"SHIPPING_RESTRICTION_DESC\", \"DEVIATION_CODE\", \"SUPPLIER\", \"Sandbox\"})\r\nin\r\n    #\"Choose columns\";\r\nshared #\"Sample file (2)\" = let\r\n    Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n    #\"Filtered rows\" = Table.SelectRows(Source, each [Extension] = \".xlsx\"),\r\n    #\"Filtered rows 1\" = Table.SelectRows(#\"Filtered rows\", each Text.Contains([Name], \"DeviationsResult\")),\r\n    #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows 1\", each [Attributes]?[Hidden]? <> true),\r\n    Navigation = #\"Filtered hidden files\"{0}[Content]\r\nin\r\n    Navigation;\r\nshared Parameter = let\r\n    Parameter = #\"Sample file (2)\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type binary]\r\nin\r\n    Parameter;\r\nshared #\"Transform Sample file (2)\" = let\r\n    Source = Excel.Workbook(Parameter, null, true),\r\n    Navigation = Source{[Item = \"DeviationsResult\", Kind = \"Sheet\"]}[Data],\r\n    #\"Promoted headers\" = Table.PromoteHeaders(Navigation, [PromoteAllScalars = true]),\r\n    #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"DEVIATION_NUMBER\", Int64.Type}, {\"CREATE_DATE\", type text}, {\"MODIFY_DATE\", type datetime}, {\"MODIFIED_BY\", type text}, {\"AGILE_DEVIATION\", type text}, {\"ACTIVE\", type logical}, {\"SITE\", type text}, {\"ORG\", type text}, {\"TYPE\", type text}, {\"MODE\", type text}, {\"TITLE\", type any}, {\"REASON\", type any}, {\"DESCRIPTION\", type text}, {\"DEVIATION\", type text}, {\"PROCESS_NAME\", type any}, {\"PROCESS_DESC\", type any}, {\"START_DATE\", type any}, {\"END_DATE\", type any}, {\"PRODUCTION\", type logical}, {\"REWORK\", type logical}, {\"SERVICE\", type logical}, {\"ENGINEERING\", type logical}, {\"DEVIATION_NOTES\", type text}, {\"VALIDATION\", type logical}, {\"VALIDATION_PERMISSION\", type text}, {\"APPLY_PARENT\", type logical}, {\"SHIPPING_RESTRICTION\", type logical}, {\"SHIPPING_RESTRICTION_DESC\", type any}, {\"DEFECT_CODE\", type any}, {\"REJECT_CODE\", type any}, {\"DEVIATION_CODE\", type any}, {\"SUPPLIER\", type any}, {\"SUPPLIER_ADDRESS\", type any}, {\"SUPPLIER_PHONE\", type any}, {\"SUPPLIER_CONTACT_NAME\", type any}, {\"SUPPLIER_EMAIL\", type any}})\r\nin\r\n    #\"Changed column type\";\r\nshared #\"Transform file (2)\" = let\r\n    Source = (Parameter as binary) => let\r\n    Source = Excel.Workbook(Parameter, null, true),\r\n    Navigation = Source{[Item = \"DeviationsResult\", Kind = \"Sheet\"]}[Data],\r\n    #\"Promoted headers\" = Table.PromoteHeaders(Navigation, [PromoteAllScalars = true]),\r\n    #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"DEVIATION_NUMBER\", Int64.Type}, {\"CREATE_DATE\", type text}, {\"MODIFY_DATE\", type datetime}, {\"MODIFIED_BY\", type text}, {\"AGILE_DEVIATION\", type text}, {\"ACTIVE\", type logical}, {\"SITE\", type text}, {\"ORG\", type text}, {\"TYPE\", type text}, {\"MODE\", type text}, {\"TITLE\", type any}, {\"REASON\", type any}, {\"DESCRIPTION\", type text}, {\"DEVIATION\", type text}, {\"PROCESS_NAME\", type any}, {\"PROCESS_DESC\", type any}, {\"START_DATE\", type any}, {\"END_DATE\", type any}, {\"PRODUCTION\", type logical}, {\"REWORK\", type logical}, {\"SERVICE\", type logical}, {\"ENGINEERING\", type logical}, {\"DEVIATION_NOTES\", type text}, {\"VALIDATION\", type logical}, {\"VALIDATION_PERMISSION\", type text}, {\"APPLY_PARENT\", type logical}, {\"SHIPPING_RESTRICTION\", type logical}, {\"SHIPPING_RESTRICTION_DESC\", type any}, {\"DEFECT_CODE\", type any}, {\"REJECT_CODE\", type any}, {\"DEVIATION_CODE\", type any}, {\"SUPPLIER\", type any}, {\"SUPPLIER_ADDRESS\", type any}, {\"SUPPLIER_PHONE\", type any}, {\"SUPPLIER_CONTACT_NAME\", type any}, {\"SUPPLIER_EMAIL\", type any}})\r\nin\r\n    #\"Changed column type\"\r\nin\r\n    Source;\r\nshared Cumulus_Shortages = let\r\n    Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n    #\"Filtered rows\" = Table.SelectRows(Source, each [Extension] = \".xlsx\"),\r\n    #\"Filtered rows 1\" = Table.SelectRows(#\"Filtered rows\", each Text.StartsWith([Name], \"Shortages\")),\r\n    #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows 1\", each [Attributes]?[Hidden]? <> true),\r\n    #\"Invoke custom function\" = Table.AddColumn(#\"Filtered hidden files\", \"Transform file (3)\", each #\"Transform file (3)\"([Content])),\r\n    #\"Renamed columns\" = Table.RenameColumns(#\"Invoke custom function\", {{\"Name\", \"Source.Name\"}}),\r\n    #\"Removed other columns\" = Table.SelectColumns(#\"Renamed columns\", {\"Source.Name\", \"Transform file (3)\"}),\r\n    #\"Expanded table column\" = Table.ExpandTableColumn(#\"Removed other columns\", \"Transform file (3)\", Table.ColumnNames(#\"Transform file (3)\"(#\"Sample file (3)\"))),\r\n    #\"Changed column type\" = Table.TransformColumnTypes(#\"Expanded table column\", {{\"Source.Name\", type text}, {\"OPEN\", type logical}, {\"CREATED\", type datetime}, {\"SINGLE_INSTANCE\", type logical}, {\"DATE_CLOSED\", type datetime}, {\"DAYS_OPEN\", type number}, {\"QTY_SHORT\", Int64.Type}, {\"NEW_BUILDS\", type logical}, {\"HOLD_COMPLETIONS\", type logical}, {\"ASSEMBLY_COUNT\", Int64.Type}, {\"QUEUE_ITEM_COUNT\", Int64.Type}, {\"PART_NUMBER\", type text}, {\"DESCRIPTION\", type text}, {\"PLANNER_CODE\", type text}, {\"FORECAST_FIELD\", type text}, {\"PRODUCT_FAMILY\", type text}, {\"PRODUCT_LINE\", type text}, {\"BUYER\", type text}, {\"PLANNER\", type text}, {\"SUPPLIER\", type text}, {\"QTY_DUE\", Int64.Type}, {\"DUE_DATE\", type date}, {\"ROOT_CAUSE\", type text}, {\"SUBMITTED_BY\", type text}, {\"OWNER\", type text}, {\"SERIAL_NUMBERS\", type text}, {\"ASSEMBLIES_AFFECTED\", type text}, {\"ORACLE_WO\", type text}, {\"ORACLE_PROJECT\", type text}, {\"NOTES\", type text}}),\r\n    #\"Filtered rows 2\" = Table.SelectRows(#\"Changed column type\", each Date.IsInPreviousNDays([CREATED], 1200)),\r\n    #\"Choose columns\" = Table.SelectColumns(#\"Filtered rows 2\", {\"OPEN\", \"CREATED\", \"SINGLE_INSTANCE\", \"DATE_CLOSED\", \"DAYS_OPEN\", \"QTY_SHORT\", \"NEW_BUILDS\", \"HOLD_COMPLETIONS\", \"ASSEMBLY_COUNT\", \"QUEUE_ITEM_COUNT\", \"PART_NUMBER\", \"DESCRIPTION\", \"PLANNER_CODE\", \"FORECAST_FIELD\", \"PRODUCT_FAMILY\", \"PRODUCT_LINE\", \"BUYER\", \"PLANNER\", \"SUPPLIER\", \"QTY_DUE\", \"DUE_DATE\", \"ROOT_CAUSE\", \"SUBMITTED_BY\", \"OWNER\", \"SERIAL_NUMBERS\", \"ASSEMBLIES_AFFECTED\", \"ORACLE_WO\", \"ORACLE_PROJECT\", \"NOTES\"}),\r\n    #\"Renamed columns 1\" = Table.RenameColumns(#\"Choose columns\", {{\"CREATED\", \"DateTime_CREATED\"}, {\"DESCRIPTION\", \"PART_DESCRIPTION\"}, {\"NEW_BUILDS\", \"HOLD_NEW_BUILDS\"}, {\"DATE_CLOSED\", \"DateTime_CLOSED\"}}),\r\n    #\"Duplicated column\" = Table.DuplicateColumn(#\"Renamed columns 1\", \"DateTime_CREATED\", \"Date_CREATED\"),\r\n    #\"Changed column type 1\" = Table.TransformColumnTypes(#\"Duplicated column\", {{\"Date_CREATED\", type date}})\r\nin\r\n    #\"Changed column type 1\";\r\nshared #\"Sample file (3)\" = let\r\n    Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n    #\"Filtered rows\" = Table.SelectRows(Source, each [Extension] = \".xlsx\"),\r\n    #\"Filtered rows 1\" = Table.SelectRows(#\"Filtered rows\", each Text.StartsWith([Name], \"Shortages\")),\r\n    #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows 1\", each [Attributes]?[Hidden]? <> true),\r\n    Navigation = #\"Filtered hidden files\"{0}[Content]\r\nin\r\n    Navigation;\r\nshared #\"Parameter (2)\" = let\r\n    #\"Parameter (2)\" = #\"Sample file (3)\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type binary]\r\nin\r\n    #\"Parameter (2)\";\r\nshared #\"Transform Sample file (3)\" = let\r\n    Source = Excel.Workbook(#\"Parameter (2)\", null, true),\r\n    Navigation = Source{[Item = \"ShortagesResult\", Kind = \"Sheet\"]}[Data],\r\n    #\"Promoted headers\" = Table.PromoteHeaders(Navigation, [PromoteAllScalars = true]),\r\n    #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"OPEN\", type logical}, {\"CREATED\", type datetime}, {\"SINGLE_INSTANCE\", type logical}, {\"DATE_CLOSED\", type datetime}, {\"DAYS_OPEN\", type number}, {\"QTY_SHORT\", Int64.Type}, {\"NEW_BUILDS\", type logical}, {\"HOLD_COMPLETIONS\", type logical}, {\"ASSEMBLY_COUNT\", Int64.Type}, {\"QUEUE_ITEM_COUNT\", Int64.Type}, {\"PART_NUMBER\", type text}, {\"DESCRIPTION\", type text}, {\"PLANNER_CODE\", type text}, {\"FORECAST_FIELD\", type text}, {\"PRODUCT_FAMILY\", type text}, {\"PRODUCT_LINE\", type text}, {\"BUYER\", type text}, {\"PLANNER\", type any}, {\"SUPPLIER\", type any}, {\"QTY_DUE\", Int64.Type}, {\"DUE_DATE\", type datetime}, {\"ROOT_CAUSE\", type any}, {\"SUBMITTED_BY\", type text}, {\"OWNER\", type text}, {\"SERIAL_NUMBERS\", type text}, {\"ASSEMBLIES_AFFECTED\", type text}, {\"ORACLE_WO\", type any}, {\"ORACLE_PROJECT\", type any}, {\"NOTES\", type text}})\r\nin\r\n    #\"Changed column type\";\r\nshared #\"Transform file (3)\" = let\r\n    Source = (#\"Parameter (2)\" as binary) => let\r\n    Source = Excel.Workbook(#\"Parameter (2)\", null, true),\r\n    Navigation = Source{[Item = \"ShortagesResult\", Kind = \"Sheet\"]}[Data],\r\n    #\"Promoted headers\" = Table.PromoteHeaders(Navigation, [PromoteAllScalars = true]),\r\n    #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"OPEN\", type logical}, {\"CREATED\", type datetime}, {\"SINGLE_INSTANCE\", type logical}, {\"DATE_CLOSED\", type datetime}, {\"DAYS_OPEN\", type number}, {\"QTY_SHORT\", Int64.Type}, {\"NEW_BUILDS\", type logical}, {\"HOLD_COMPLETIONS\", type logical}, {\"ASSEMBLY_COUNT\", Int64.Type}, {\"QUEUE_ITEM_COUNT\", Int64.Type}, {\"PART_NUMBER\", type text}, {\"DESCRIPTION\", type text}, {\"PLANNER_CODE\", type text}, {\"FORECAST_FIELD\", type text}, {\"PRODUCT_FAMILY\", type text}, {\"PRODUCT_LINE\", type text}, {\"BUYER\", type text}, {\"PLANNER\", type any}, {\"SUPPLIER\", type any}, {\"QTY_DUE\", Int64.Type}, {\"DUE_DATE\", type datetime}, {\"ROOT_CAUSE\", type any}, {\"SUBMITTED_BY\", type text}, {\"OWNER\", type text}, {\"SERIAL_NUMBERS\", type text}, {\"ASSEMBLIES_AFFECTED\", type text}, {\"ORACLE_WO\", type any}, {\"ORACLE_PROJECT\", type any}, {\"NOTES\", type text}})\r\nin\r\n    #\"Changed column type\"\r\nin\r\n    Source;\r\nshared Cumulus_Equipment = let\r\n    Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n    #\"Filtered rows\" = Table.SelectRows(Source, each [Extension] = \".xlsx\" and [Name] = \"AssetEquipment_AssetEquipmentResult.xlsx\"),\r\n    #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows\", each [Attributes]?[Hidden]? <> true),\r\n    #\"Invoke custom function\" = Table.AddColumn(#\"Filtered hidden files\", \"Transform file (4)\", each #\"Transform file (4)\"([Content])),\r\n    #\"Renamed columns\" = Table.RenameColumns(#\"Invoke custom function\", {{\"Name\", \"Source.Name\"}}),\r\n    #\"Removed other columns\" = Table.SelectColumns(#\"Renamed columns\", {\"Source.Name\", \"Transform file (4)\"}),\r\n    #\"Expanded table column\" = Table.ExpandTableColumn(#\"Removed other columns\", \"Transform file (4)\", Table.ColumnNames(#\"Transform file (4)\"(#\"Sample file (4)\"))),\r\n    #\"Changed column type\" = Table.TransformColumnTypes(#\"Expanded table column\", {{\"Source.Name\", type text}, {\"ASSET\", Int64.Type}, {\"ENTITY\", Int64.Type}, {\"DEPARTMENT\", Int64.Type}, {\"STATUS\", type text}, {\"RESPONSIBLE_ENGINEER\", type text}, {\"ISO_17025\", type text}, {\"NEXT_PM_DUE\", type text}, {\"NEXT_CAL_DUE\", type text}, {\"MODEL\", type text}, {\"DESCRIPTION\", type text}, {\"SERIAL_NUMBER\", type text}, {\"MANUFACTURER\", type text}, {\"LEGACY_ASSET\", type text}, {\"DISTRIBUTION_GROUP\", type text}, {\"LOCKOUT_TAGOUT\", type text}, {\"CAL_SOURCE\", type text}, {\"VENDOR\", type text}, {\"NOTES\", type text}}),\r\n    #\"Changed column type 1\" = Table.TransformColumnTypes(#\"Changed column type\", {{\"NEXT_CAL_DUE\", type date}, {\"NEXT_PM_DUE\", type date}}),\r\n    #\"Replaced errors\" = Table.ReplaceErrorValues(#\"Changed column type 1\", {{\"NEXT_CAL_DUE\", #date(2100, 12, 31)}, {\"NEXT_PM_DUE\", #date(2100, 12, 31)}}),\r\n    #\"Choose columns\" = Table.SelectColumns(#\"Replaced errors\", {\"ASSET\", \"ENTITY\", \"DEPARTMENT\", \"STATUS\", \"RESPONSIBLE_ENGINEER\", \"ISO_17025\", \"NEXT_CAL_DUE\", \"NEXT_PM_DUE\", \"CAL_SOURCE\", \"MODEL\", \"DESCRIPTION\", \"SERIAL_NUMBER\", \"MANUFACTURER\", \"LEGACY_ASSET\", \"DISTRIBUTION_GROUP\", \"LOCKOUT_TAGOUT\", \"VENDOR\", \"NOTES\"})\r\nin\r\n    #\"Choose columns\";\r\nshared #\"Sample file (4)\" = let\r\n    Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n    #\"Filtered rows\" = Table.SelectRows(Source, each [Extension] = \".xlsx\" and [Name] = \"AssetEquipment_AssetEquipmentResult.xlsx\"),\r\n    #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows\", each [Attributes]?[Hidden]? <> true),\r\n    Navigation = #\"Filtered hidden files\"{0}[Content]\r\nin\r\n    Navigation;\r\nshared #\"Parameter (3)\" = let\r\n    #\"Parameter (3)\" = #\"Sample file (4)\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type binary, BinaryIdentifier = #\"Sample file (4)\"]\r\nin\r\n    #\"Parameter (3)\";\r\nshared #\"Transform Sample file (4)\" = let\r\n    Source = Excel.Workbook(#\"Parameter (3)\", null, true),\r\n    Navigation = Source{[Item = \"AssetEquipmentResult\", Kind = \"Sheet\"]}[Data],\r\n    #\"Promoted headers\" = Table.PromoteHeaders(Navigation, [PromoteAllScalars = true]),\r\n    #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"ASSET\", Int64.Type}, {\"ENTITY\", Int64.Type}, {\"DEPARTMENT\", Int64.Type}, {\"STATUS\", type text}, {\"RESPONSIBLE_ENGINEER\", type text}, {\"ISO_17025\", type text}, {\"NEXT_PM_DUE\", type text}, {\"NEXT_CAL_DUE\", type text}, {\"MODEL\", type text}, {\"DESCRIPTION\", type text}, {\"SERIAL_NUMBER\", type text}, {\"MANUFACTURER\", type text}, {\"LEGACY_ASSET\", type text}, {\"DISTRIBUTION_GROUP\", type text}, {\"LOCKOUT_TAGOUT\", type text}})\r\nin\r\n    #\"Changed column type\";\r\nshared #\"Transform file (4)\" = let\r\n    Source = (#\"Parameter (3)\" as binary) => let\r\n    Source = Excel.Workbook(#\"Parameter (3)\", null, true),\r\n    Navigation = Source{[Item = \"AssetEquipmentResult\", Kind = \"Sheet\"]}[Data],\r\n    #\"Promoted headers\" = Table.PromoteHeaders(Navigation, [PromoteAllScalars = true]),\r\n    #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"ASSET\", Int64.Type}, {\"ENTITY\", Int64.Type}, {\"DEPARTMENT\", Int64.Type}, {\"STATUS\", type text}, {\"RESPONSIBLE_ENGINEER\", type text}, {\"ISO_17025\", type text}, {\"NEXT_PM_DUE\", type text}, {\"NEXT_CAL_DUE\", type text}, {\"MODEL\", type text}, {\"DESCRIPTION\", type text}, {\"SERIAL_NUMBER\", type text}, {\"MANUFACTURER\", type text}, {\"LEGACY_ASSET\", type text}, {\"DISTRIBUTION_GROUP\", type text}, {\"LOCKOUT_TAGOUT\", type text}})\r\nin\r\n    #\"Changed column type\"\r\nin\r\n    Source;\r\nshared ChangeRequests = let\r\n    Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/sites/GEPMEChangeRequests\", [ApiVersion = 15]),\r\n    #\"Filtered rows\" = Table.SelectRows(Source, each [Extension] = \".xlsx\"),\r\n    #\"Filtered rows 1\" = Table.SelectRows(#\"Filtered rows\", each Text.Contains([Name], \"MasterFile\")),\r\n    #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows 1\", each [Attributes]?[Hidden]? <> true),\r\n    #\"Invoke custom function\" = Table.AddColumn(#\"Filtered hidden files\", \"Transform file (5)\", each #\"Transform file (5)\"([Content])),\r\n    #\"Renamed columns\" = Table.RenameColumns(#\"Invoke custom function\", {{\"Name\", \"Source.Name\"}}),\r\n    #\"Removed other columns\" = Table.SelectColumns(#\"Renamed columns\", {\"Source.Name\", \"Transform file (5)\"}),\r\n    #\"Expanded table column\" = Table.ExpandTableColumn(#\"Removed other columns\", \"Transform file (5)\", Table.ColumnNames(#\"Transform file (5)\"(#\"Sample file (5)\"))),\r\n    #\"Choose columns\" = Table.SelectColumns(#\"Expanded table column\", {\"Change_Request_ID\", \"Agile ECO\", \"Aktuelles Datum\", \"Lieferant\", \"Lieferanten Nr.\", \"Artikelnr\", \"Bauteil Beschreibung\", \"Neue Rev\", \"Bearbeiter\", \"Ab PO\", \"Gewünschte Lieferung ab\", \"Alte  #(lf)Rev\", \"Lagerbest\", \"Restm#(lf)Rahmenvertr - PO - Kanban\", \"Nacharb\", \"Bis PO\", \"Lieferung bis\", \"Price Change\", \"Delivery From PO\", \"Start Deliveries\", \"Datum\", \"Erhalten - Übernommen\", \"Feedback\", \"geprüft, OK?\"}),\r\n    #\"Changed column type\" = Table.TransformColumnTypes(#\"Choose columns\", {{\"Change_Request_ID\", type text}, {\"Agile ECO\", type text}, {\"Lieferant\", type text}, {\"Lieferanten Nr.\", type text}, {\"Artikelnr\", type text}, {\"Bauteil Beschreibung\", type text}, {\"Neue Rev\", type text}, {\"Bearbeiter\", type text}, {\"Ab PO\", type text}, {\"Gewünschte Lieferung ab\", type text}, {\"Alte  #(lf)Rev\", type text}, {\"Lagerbest\", type text}, {\"Restm#(lf)Rahmenvertr - PO - Kanban\", type text}, {\"Nacharb\", type text}, {\"Bis PO\", type text}, {\"Lieferung bis\", type text}, {\"Price Change\", type text}, {\"Delivery From PO\", type text}, {\"Start Deliveries\", type text}, {\"Erhalten - Übernommen\", type text}, {\"Feedback\", type text}, {\"geprüft, OK?\", type text}, {\"Aktuelles Datum\", type date}, {\"Datum\", type date}}),\r\n    #\"Replaced errors\" = Table.ReplaceErrorValues(#\"Changed column type\", {{\"Datum\", #date(2020, 1, 1)}})\r\nin\r\n    #\"Replaced errors\";\r\nshared #\"Sample file (5)\" = let\r\n    Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/sites/GEPMEChangeRequests\", [ApiVersion = 15]),\r\n    #\"Filtered rows\" = Table.SelectRows(Source, each [Extension] = \".xlsx\"),\r\n    #\"Filtered rows 1\" = Table.SelectRows(#\"Filtered rows\", each Text.Contains([Name], \"MasterFile\")),\r\n    #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows 1\", each [Attributes]?[Hidden]? <> true),\r\n    Navigation = #\"Filtered hidden files\"{0}[Content]\r\nin\r\n    Navigation;\r\nshared #\"Parameter (4)\" = let\r\n    #\"Parameter (4)\" = #\"Sample file (5)\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type binary, BinaryIdentifier = #\"Sample file (5)\"]\r\nin\r\n    #\"Parameter (4)\";\r\nshared #\"Transform Sample file (5)\" = let\r\n    Source = Excel.Workbook(#\"Parameter (4)\", null, true),\r\n    Navigation = Source{[Item = \"tblCRsupplier\", Kind = \"Table\"]}[Data]\r\nin\r\n    Navigation;\r\nshared #\"Transform file (5)\" = let\r\n    Source = (#\"Parameter (4)\" as binary) => let\r\n    Source = Excel.Workbook(#\"Parameter (4)\", null, true),\r\n    Navigation = Source{[Item = \"tblCRsupplier\", Kind = \"Table\"]}[Data]\r\nin\r\n    Navigation\r\nin\r\n    Source;\r\nshared XXCOH_WIP_TRX_TAB_OldNotNativeSQL = let\r\n    Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n    Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n    #\"Navigation 1\" = Navigation{[Name = \"XXSF\", Kind = \"Schema\"]}[Data],\r\n    #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXCOH_WIP_TRX_TAB\", Kind = \"Table\"]}[Data],\r\n    #\"Filtered rows\" = Table.SelectRows(#\"Navigation 2\", each [ORGANIZATION_CODE] = \"GEP\" or [ORGANIZATION_CODE] = \"KEP\"),\r\n    #\"Choose columns\" = Table.SelectColumns(#\"Filtered rows\", {\"ASOF_DATE\", \"TRANSACTION_ID\", \"ORGANIZATION_CODE\", \"SET_OF_BOOKS\", \"TRX_TYPE\", \"TRX_DATE\", \"ACCT_ENTITY\", \"ACCT_DEPT\", \"ACCT_NUMBER\", \"TRX_CURRENCY_CODE\", \"FUNC_CURRENCY_CODE\", \"ENTERED_DR\", \"ENTERED_CR\", \"ACCOUNTED_DR\", \"ACCOUNTED_CR\", \"ACCOUNTED_DR_USD\", \"ACCOUNTED_CR_USD\", \"GL_TRANSFER_STATUS\", \"WIP_JOB_NAME\", \"COST_ELEMENT_NAME\", \"PERIOD_NAME\", \"CREATED_BY\", \"ACCOUNTING_LINE_TYPE\", \"TRANSACTION_QUANTITY\", \"TRANSACTION_UOM\", \"PRIMARY_QUANTITY\", \"PRIMARY_UOM\", \"USD_RATE\", \"DEPARTMENT_CODE\", \"RESOURCE_CODE\", \"WIP_ENTITY_ID\", \"ORGANIZATION_ID\", \"INVENTORY_ITEM_ID\", \"RESOURCE_ID\"})\r\nin\r\n    #\"Choose columns\";\r\nshared XXCOH_MI_WIP_DETAIL_TAB_OldNotNatiiveSQL = let\r\n    Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n    Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n    #\"Navigation 1\" = Navigation{[Name = \"XXSF\", Kind = \"Schema\"]}[Data],\r\n    #\"Navigation 2\" = #\"Navigation 1\"{[Kind = \"Table\", Name = \"XXCOH_MI_WIP_DETAIL_TAB\"]}[Data],\r\n    #\"Filtered rows\" = Table.SelectRows(#\"Navigation 2\", each [TECHNICAL_BUSINESS_UNIT] = \"Excimer\"),\r\n    #\"Filtered rows 1\" = Table.SelectRows(#\"Filtered rows\", each [FISCAL_YEAR] > 2014),\r\n    #\"Choose columns\" = Table.SelectColumns(#\"Filtered rows 1\", {\"ASOF_DATE\", \"WIP_ENTITY_NAME\", \"ENTITY_DESCRIPTION\", \"ENTITY_TYPE\", \"JOB_TYPE\", \"JOB_STATUS\", \"CLASS_CODE\", \"ITEM__NUMBER\", \"ITEM_DESCRIPTION\", \"TECHNICAL_BUSINESS_UNIT\", \"PRODUCT_FAMILY\", \"PRODUCT_LINE\", \"FORECAST_FIELD\", \"ORG_PRODUCT_FAMILY\", \"ORG_PRODUCT_LINE\", \"ORG_FORECAST_FIELD\", \"PLANNER_CODE\", \"ITEM_CUSTOMER\", \"ORDER_NUMBER\", \"ORDER_LINE\", \"OWNING_ORGANIZATION\", \"REPORTING_TBU\", \"SUBINVENTORY\", \"OPERATING_UNIT\", \"FISCAL_PERIOD\", \"PRIMARY_UOM_CODE\", \"QUANTITY_REMAINING\", \"START_QUANTITY\", \"QUANTITY_COMPLETED\", \"QUANTITY_SCRAPPED\", \"USD_RATE\", \"BASE_CURRENCY\", \"ITEM_COST\", \"MATERIAL_COST\", \"RESOURCE_COST\", \"OVERHEAD_COST\", \"OUTSIDE_PROCESSING_COST\", \"MATERIAL_DEPT\", \"RESOURCE_DEPT\", \"OVERHEAD_DEPT\", \"OS_PROCESS_DEPT\", \"BOM_REVISION\", \"BOM_REVISION_DATE\", \"ROUTING_REVISION\", \"ROUTING_REVISION_DATE\", \"DATE_RELEASED\", \"DATE_COMPLETED\", \"DATE_CLOSED\", \"DATE_STARTED\", \"DUE_DATE\", \"DEMAND_CLASS\", \"TOTAL_LABOR_HOURS\", \"TOTAL_LABOR_VALUE\", \"SCHEDULE_GROUP_NAME\", \"TOTAL_COSTS_INCURRED\", \"TOTAL_COSTS_RELIEVED\", \"TOTAL_VARIANCES_RELIEVED\", \"TOTAL_NET_ACTIVITIES\", \"TOTAL_COSTS_INCURRED_USD\", \"TOTAL_COSTS_RELIEVED_USD\", \"TOTAL_VARIANCES_RELIEVED_USD\", \"TOTAL_NET_ACTIVITIES_USD\", \"COMP_ITEM_NUMBER\", \"COMP_ITEM_DESCRIPTION\", \"COMP_ORG\", \"COMP_PLANNER_CODE\", \"COMP_MAKE_OR_BUY\", \"COMP_TBU\", \"COMP_ORG_TBU\", \"COMP_COMMODITY\", \"COMP_PRIMARY_ORG\", \"COMP_TRX_TYPE\", \"COMP_TRX_TYPE_ID\", \"COMP_REQUIRED_QUANTITY\", \"COMP_TRX_QUANTITY\", \"COMP_QUANTITY_PER_ASSEMBLY\", \"COMP_SUPPLY_SUBINV\", \"COMP_TRX_DATE\", \"COMP_ITEM_COST\", \"COMP_MATERIAL_COST\", \"COMP_RESOURCE_COST\", \"COMP_OVERHEAD_COST\", \"COMP_OUTSIDE_PROCESSING_COST\", \"COMP_EXTENDED_ITEM_COST\", \"COMP_ITEM_COST_USD\", \"COMP_MATERIAL_COST_USD\", \"COMP_MATERIAL_OH_COST_USD\", \"COMP_RESOURCE_COST_USD\", \"COMP_OVERHEAD_COST_USD\", \"COMP_OS_PROCESSING_COST_USD\", \"COMP_EXTENDED_ITEM_COST_USD\", \"G_ITEM_COST\", \"G_MATERIAL_COST\", \"G_MATERIAL_OVERHEAD_COST\", \"G_RESOURCE_COST\", \"G_OVERHEAD_COST\", \"G_OUTSIDE_PROCESSING_COST\", \"G_COMP_ITEM_COST\", \"G_COMP_MATERIAL_COST\", \"G_COMP_MATERIAL_OVERHEAD_COST\", \"G_COMP_RESOURCE_COST\", \"G_COMP_OVERHEAD_COST\", \"G_COMP_OUTSIDE_PROCESSING_COST\", \"G_COMP_EXTENDED_ITEM_COST\", \"G_COMP_ITEM_COST_USD\", \"G_COMP_MATERIAL_COST_USD\", \"G_COMP_MATERIAL_OH_COST_USD\", \"G_COMP_RESOURCE_COST_USD\", \"G_COMP_OVERHEAD_COST_USD\", \"G_COMP_OS_PROCESSING_COST_USD\", \"G_COMP_EXTENDED_ITEM_COST_USD\", \"COMP_ITEM_ADD_BACK_COST\", \"COMP_EXT_ITEM_ADD_BACK_COST\", \"COMP_ITEM_ADD_BACK_COST_USD\", \"COMP_EXT_ITEM_ADD_BACK_CST_USD\", \"WIP_ENTITY_ID\", \"INVENTORY_ITEM_ID\", \"ORGANIZATION_ID\", \"OE_HEADER_ID\", \"OE_LINE_ID\", \"COMP_ITEM_ID\", \"COMP_ORG_ID\", \"COMP_FISCAL_PERIOD\"})\r\nin\r\n    #\"Choose columns\";\r\nshared #\"VHP-Electrodes_BlastedArea\" = let\r\n    Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n    #\"Filtered rows\" = Table.SelectRows(Source, each [Extension] = \".xlsx\" and [Name] = \"BlastedArea.xlsx\"),\r\n    #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows\", each [Attributes]?[Hidden]? <> true),\r\n    #\"Invoke custom function\" = Table.AddColumn(#\"Filtered hidden files\", \"Transform file (6)\", each #\"Transform file (6)\"([Content])),\r\n    #\"Renamed columns\" = Table.RenameColumns(#\"Invoke custom function\", {{\"Name\", \"Source.Name\"}}),\r\n    #\"Removed other columns\" = Table.SelectColumns(#\"Renamed columns\", {\"Source.Name\", \"Transform file (6)\"}),\r\n    #\"Expanded Transform file (6)\" = Table.ExpandTableColumn(#\"Removed other columns\", \"Transform file (6)\", {\"Column1\", \"Column2\", \"Column3\", \"Column4\", \"Column5\", \"Column6\", \"Column7\", \"Column8\", \"Column9\", \"Column10\", \"Column11\", \"Column12\", \"Column13\", \"Column14\", \"Column15\", \"Column16\", \"Column17\", \"Column18\", \"Column19\", \"Column20\", \"Column21\", \"Column22\", \"Column23\", \"Column24\", \"Column25\", \"Column26\"}, {\"Column1\", \"Column2\", \"Column3\", \"Column4\", \"Column5\", \"Column6\", \"Column7\", \"Column8\", \"Column9\", \"Column10\", \"Column11\", \"Column12\", \"Column13\", \"Column14\", \"Column15\", \"Column16\", \"Column17\", \"Column18\", \"Column19\", \"Column20\", \"Column21\", \"Column22\", \"Column23\", \"Column24\", \"Column25\", \"Column26\"}),\r\n    #\"Choose columns\" = Table.SelectColumns(#\"Expanded Transform file (6)\", {\"Column1\", \"Column2\", \"Column3\", \"Column4\", \"Column5\", \"Column6\", \"Column7\", \"Column8\", \"Column9\", \"Column10\", \"Column11\", \"Column12\", \"Column13\", \"Column14\", \"Column15\", \"Column16\", \"Column17\", \"Column18\", \"Column19\", \"Column20\", \"Column21\", \"Column22\", \"Column23\", \"Column24\", \"Column25\", \"Column26\"}),\r\n    #\"Trimmed text\" = Table.TransformColumns(#\"Choose columns\", {{\"Column1\", each Text.Trim(Text.From(_)), type nullable text}, {\"Column2\", each Text.Trim(Text.From(_)), type nullable text}, {\"Column3\", each Text.Trim(Text.From(_)), type nullable text}, {\"Column4\", each Text.Trim(Text.From(_)), type nullable text}, {\"Column5\", each Text.Trim(Text.From(_)), type nullable text}, {\"Column6\", each Text.Trim(Text.From(_)), type nullable text}, {\"Column7\", each Text.Trim(Text.From(_)), type nullable text}, {\"Column8\", each Text.Trim(Text.From(_)), type nullable text}, {\"Column9\", each Text.Trim(Text.From(_)), type nullable text}, {\"Column10\", each Text.Trim(Text.From(_)), type nullable text}, {\"Column11\", each Text.Trim(Text.From(_)), type nullable text}, {\"Column12\", each Text.Trim(Text.From(_)), type nullable text}, {\"Column13\", each Text.Trim(Text.From(_)), type nullable text}, {\"Column14\", each Text.Trim(Text.From(_)), type nullable text}, {\"Column15\", each Text.Trim(Text.From(_)), type nullable text}, {\"Column16\", each Text.Trim(Text.From(_)), type nullable text}, {\"Column17\", each Text.Trim(Text.From(_)), type nullable text}, {\"Column18\", each Text.Trim(Text.From(_)), type nullable text}, {\"Column19\", each Text.Trim(Text.From(_)), type nullable text}, {\"Column20\", each Text.Trim(Text.From(_)), type nullable text}, {\"Column21\", each Text.Trim(Text.From(_)), type nullable text}, {\"Column22\", each Text.Trim(Text.From(_)), type nullable text}, {\"Column23\", each Text.Trim(Text.From(_)), type nullable text}, {\"Column24\", each Text.Trim(Text.From(_)), type nullable text}, {\"Column25\", each Text.Trim(Text.From(_)), type nullable text}, {\"Column26\", each Text.Trim(Text.From(_)), type nullable text}}),\r\n    #\"Promoted headers\" = Table.PromoteHeaders(#\"Trimmed text\", [PromoteAllScalars = true]),\r\n    #\"Renamed columns 1\" = Table.RenameColumns(#\"Promoted headers\", {{\"Elektrode#(lf)Neu / Refurb / Sonder\", \"Elektrode_Status\"}, {\"Höhe Elektrode\", \"Hoehe Elektrode\"}}),\r\n    #\"Changed column type\" = Table.TransformColumnTypes(#\"Renamed columns 1\", {{\"Serien-Nr.\", type text}, {\"Schablonen-Nummer\", type text}, {\"Chargen-Nr.\", type text}, {\"Beschichter\", type text}, {\"Abst. Max Mw1 zu Mw4\", type number}, {\"Abst. Min Mw2 zu Mw3\", type number}, {\"MW1 Average\", type number}, {\"Abst. Max Mw1 zu Mw4_1\", type number}, {\"Abst. Min Mw2 zu Mw3_2\", type number}, {\"MW2 Average\", type number}, {\"Abst. Max Mw1 zu Mw4_3\", type number}, {\"Abst. Min Mw2 zu Mw3_4\", type number}, {\"MW3 Average\", type number}, {\"Abst. Max Mw1 zu Mw4_5\", type number}, {\"Abst. Min Mw2 zu Mw3_6\", type number}, {\"MW4 Average\", type number}, {\"Elektrode_Status\", type text}, {\"Hoehe Elektrode\", type number}, {\"Art.-#(lf)Nummer\", type text}, {\"Lieferdatum\", type text}, {\"Bemerkungen\", type text}, {\"abgeschliffen um\", type number}, {\"Hersteller\", type text}, {\"Auftrag\", type text}, {\"Datei\", type text}, {\"Aktualisierung\", type text}}),\r\n    #\"Extracted text before delimiter\" = Table.TransformColumns(#\"Changed column type\", {{\"Lieferdatum\", each Text.BeforeDelimiter(_, \" \", 0), type text}, {\"Aktualisierung\", each Text.BeforeDelimiter(_, \" \", 0), type text}}),\r\n    #\"Changed column type with locale\" = Table.TransformColumnTypes(#\"Extracted text before delimiter\", {{\"Lieferdatum\", type date}, {\"Aktualisierung\", type date}}, \"de-DE\")\r\nin\r\n    #\"Changed column type with locale\";\r\nshared #\"VHP-Electrodes_CoatingData\" = let\r\n    Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n    #\"Filtered rows\" = Table.SelectRows(Source, each [Extension] = \".xlsx\" and [Name] = \"CoatingData.xlsx\"),\r\n    #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows\", each [Attributes]?[Hidden]? <> true),\r\n    #\"Invoke custom function\" = Table.AddColumn(#\"Filtered hidden files\", \"Transform file (7)\", each #\"Transform file (7)\"([Content])),\r\n    #\"Renamed columns\" = Table.RenameColumns(#\"Invoke custom function\", {{\"Name\", \"Source.Name\"}}),\r\n    #\"Removed other columns\" = Table.SelectColumns(#\"Renamed columns\", {\"Source.Name\", \"Transform file (7)\"}),\r\n    #\"Expanded table column\" = Table.ExpandTableColumn(#\"Removed other columns\", \"Transform file (7)\", Table.ColumnNames(#\"Transform file (7)\"(#\"Sample file (7)\"))),\r\n    #\"Choose columns\" = Table.SelectColumns(#\"Expanded table column\", {\"Column1\", \"Column2\", \"Column3\", \"Column4\", \"Column5\", \"Column6\", \"Column7\", \"Column8\", \"Column9\", \"Column10\", \"Column11\", \"Column12\", \"Column13\", \"Column14\", \"Column15\", \"Column16\", \"Column17\", \"Column18\", \"Column19\", \"Column20\", \"Column21\", \"Column22\", \"Column23\"}),\r\n    #\"Trimmed text\" = Table.TransformColumns(#\"Choose columns\", {{\"Column1\", each Text.Trim(Text.From(_)), type nullable text}, {\"Column2\", each Text.Trim(Text.From(_)), type nullable text}, {\"Column3\", each Text.Trim(Text.From(_)), type nullable text}, {\"Column4\", each Text.Trim(Text.From(_)), type nullable text}, {\"Column5\", each Text.Trim(Text.From(_)), type nullable text}, {\"Column6\", each Text.Trim(Text.From(_)), type nullable text}, {\"Column7\", each Text.Trim(Text.From(_)), type nullable text}, {\"Column8\", each Text.Trim(Text.From(_)), type nullable text}, {\"Column9\", each Text.Trim(Text.From(_)), type nullable text}, {\"Column10\", each Text.Trim(Text.From(_)), type nullable text}, {\"Column11\", each Text.Trim(Text.From(_)), type nullable text}, {\"Column12\", each Text.Trim(Text.From(_)), type nullable text}, {\"Column13\", each Text.Trim(Text.From(_)), type nullable text}, {\"Column14\", each Text.Trim(Text.From(_)), type nullable text}, {\"Column15\", each Text.Trim(Text.From(_)), type nullable text}, {\"Column16\", each Text.Trim(Text.From(_)), type nullable text}, {\"Column17\", each Text.Trim(Text.From(_)), type nullable text}, {\"Column18\", each Text.Trim(Text.From(_)), type nullable text}, {\"Column19\", each Text.Trim(Text.From(_)), type nullable text}, {\"Column20\", each Text.Trim(Text.From(_)), type nullable text}, {\"Column21\", each Text.Trim(Text.From(_)), type nullable text}, {\"Column22\", each Text.Trim(Text.From(_)), type nullable text}, {\"Column23\", each Text.Trim(Text.From(_)), type nullable text}}),\r\n    #\"Promoted headers\" = Table.PromoteHeaders(#\"Trimmed text\", [PromoteAllScalars = true]),\r\n    #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"SN\", type text}, {\"Art. Nr.\", type text}, {\"Charge\", type text}, {\"Strahler\", type text}, {\"Gestr. Datum\", type text}, {\"Beschichter\", type text}, {\"Besch. Datum\", type text}, {\"M /li#(lf)MW1\", Int64.Type}, {\"C#(lf)MW2\", Int64.Type}, {\"W /re#(lf)MW3\", Int64.Type}, {\"M /li#(lf)MW4\", Int64.Type}, {\"C#(lf)MW5\", Int64.Type}, {\"W /re#(lf)MW6\", Int64.Type}, {\"M /li#(lf)MW7\", Int64.Type}, {\"C#(lf)MW8\", Int64.Type}, {\"W /re#(lf)MW9\", Int64.Type}, {\"M /li#(lf)MW10\", Int64.Type}, {\"C#(lf)MW11\", Int64.Type}, {\"W /re#(lf)MW12\", Int64.Type}, {\"Hersteller\", type text}, {\"Auftrag\", type text}, {\"Datei\", type text}, {\"Aktualisierung\", type text}}),\r\n    #\"Extracted text before delimiter\" = Table.TransformColumns(#\"Changed column type\", {{\"Gestr. Datum\", each Text.BeforeDelimiter(_, \" \", 0), type text}, {\"Besch. Datum\", each Text.BeforeDelimiter(_, \" \", 0), type text}, {\"Aktualisierung\", each Text.BeforeDelimiter(_, \" \", 0), type text}}),\r\n    #\"Changed column type with locale\" = Table.TransformColumnTypes(#\"Extracted text before delimiter\", {{\"Gestr. Datum\", type date}, {\"Besch. Datum\", type date}, {\"Aktualisierung\", type date}}, \"de-DE\")\r\nin\r\n    #\"Changed column type with locale\";\r\nshared #\"Sample file (6)\" = let\r\n    Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n    #\"Filtered rows\" = Table.SelectRows(Source, each [Extension] = \".xlsx\" and [Name] = \"BlastedArea.xlsx\"),\r\n    #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows\", each [Attributes]?[Hidden]? <> true),\r\n    Navigation = #\"Filtered hidden files\"{0}[Content]\r\nin\r\n    Navigation;\r\nshared #\"Parameter (5)\" = let\r\n    #\"Parameter (5)\" = #\"Sample file (6)\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type binary, BinaryIdentifier = #\"Sample file (6)\"]\r\nin\r\n    #\"Parameter (5)\";\r\nshared #\"Transform Sample file (6)\" = let\r\n    Source = Excel.Workbook(#\"Parameter (5)\", null, true),\r\n    Navigation = Source{[Item = \"BlastedArea\", Kind = \"Sheet\"]}[Data]\r\nin\r\n    Navigation;\r\nshared #\"Transform file (6)\" = let\r\n    Source = (#\"Parameter (5)\" as binary) => let\r\n    Source = Excel.Workbook(#\"Parameter (5)\", null, true),\r\n    Navigation = Source{[Item = \"BlastedArea\", Kind = \"Sheet\"]}[Data]\r\nin\r\n    Navigation\r\nin\r\n    Source;\r\nshared #\"Sample file (7)\" = let\r\n    Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n    #\"Filtered rows\" = Table.SelectRows(Source, each [Extension] = \".xlsx\" and [Name] = \"CoatingData.xlsx\"),\r\n    #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows\", each [Attributes]?[Hidden]? <> true),\r\n    Navigation = #\"Filtered hidden files\"{0}[Content]\r\nin\r\n    Navigation;\r\nshared #\"Parameter (6)\" = let\r\n    #\"Parameter (6)\" = #\"Sample file (7)\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type binary, BinaryIdentifier = #\"Sample file (7)\"]\r\nin\r\n    #\"Parameter (6)\";\r\nshared #\"Transform Sample file (7)\" = let\r\n    Source = Excel.Workbook(#\"Parameter (6)\", null, true),\r\n    Navigation = Source{[Item = \"CoatingData\", Kind = \"Sheet\"]}[Data]\r\nin\r\n    Navigation;\r\nshared #\"Transform file (7)\" = let\r\n    Source = (#\"Parameter (6)\" as binary) => let\r\n    Source = Excel.Workbook(#\"Parameter (6)\", null, true),\r\n    Navigation = Source{[Item = \"CoatingData\", Kind = \"Sheet\"]}[Data]\r\nin\r\n    Navigation\r\nin\r\n    Source;\r\nshared XXCOH_WIP_TRX_TAB = let\n    Source = Value.NativeQuery(Snowflake.Databases(\"mma12090.snowflakecomputing.com\",\"COMPUTE_REPORTING\",[Role=\"GLBMFGOPERATIONSROLE\"]){[Name=\"PROD_DB\"]}[Data], \"SELECT * FROM PROD_DB.XXSF.XXCOH_WIP_TRX_TAB Where Organization_Code='GEP' or Organization_Code='KEP'\", null, [EnableFolding=true]),\n    #\"Filtered rows 1\" = Table.SelectRows(Source, each Date.IsInPreviousNDays([TRX_DATE], 1830)),\n    #\"Choose columns\" = Table.SelectColumns(#\"Filtered rows 1\", {\"ASOF_DATE\", \"TRANSACTION_ID\", \"ORGANIZATION_CODE\", \"SET_OF_BOOKS\", \"TRX_TYPE\", \"TRX_DATE\", \"ACCT_ENTITY\", \"ACCT_DEPT\", \"ACCT_NUMBER\", \"TRX_CURRENCY_CODE\", \"FUNC_CURRENCY_CODE\", \"ENTERED_DR\", \"ENTERED_CR\", \"ACCOUNTED_DR\", \"ACCOUNTED_CR\", \"ACCOUNTED_DR_USD\", \"ACCOUNTED_CR_USD\", \"GL_TRANSFER_STATUS\", \"WIP_JOB_NAME\", \"COST_ELEMENT_NAME\", \"PERIOD_NAME\", \"CREATED_BY\", \"ACCOUNTING_LINE_TYPE\", \"TRANSACTION_QUANTITY\", \"TRANSACTION_UOM\", \"PRIMARY_QUANTITY\", \"PRIMARY_UOM\", \"USD_RATE\", \"DEPARTMENT_CODE\", \"RESOURCE_CODE\", \"WIP_ENTITY_ID\", \"ORGANIZATION_ID\", \"INVENTORY_ITEM_ID\", \"RESOURCE_ID\", \"ROW_CREATION_DATE\"})\nin\n    #\"Choose columns\";\r\nshared XXCOH_MI_WIP_DETAIL_TAB = let\n    Source = Value.NativeQuery(Snowflake.Databases(\"mma12090.snowflakecomputing.com\",\"COMPUTE_REPORTING\",[Role=\"GLBMFGOPERATIONSROLE\"]){[Name=\"PROD_DB\"]}[Data], \"SELECT * FROM PROD_DB.XXSF.XXCOH_MI_WIP_DETAIL_TAB Where Technical_Business_Unit='Excimer'\", null, [EnableFolding=true]),\n    #\"Filtered rows 1\" = Table.SelectRows(Source, each [FISCAL_YEAR] > 2016),\n    #\"Choose columns\" = Table.SelectColumns(#\"Filtered rows 1\", {\"ASOF_DATE\", \"WIP_ENTITY_NAME\", \"ENTITY_DESCRIPTION\", \"ENTITY_TYPE\", \"JOB_TYPE\", \"JOB_STATUS\", \"CLASS_CODE\", \"ITEM__NUMBER\", \"ITEM_DESCRIPTION\", \"TECHNICAL_BUSINESS_UNIT\", \"PRODUCT_FAMILY\", \"PRODUCT_LINE\", \"FORECAST_FIELD\", \"ORG_PRODUCT_FAMILY\", \"ORG_PRODUCT_LINE\", \"ORG_FORECAST_FIELD\", \"PLANNER_CODE\", \"ITEM_CUSTOMER\", \"ORDER_NUMBER\", \"ORDER_LINE\", \"OWNING_ORGANIZATION\", \"REPORTING_TBU\", \"SUBINVENTORY\", \"OPERATING_UNIT\", \"FISCAL_PERIOD\", \"PRIMARY_UOM_CODE\", \"QUANTITY_REMAINING\", \"START_QUANTITY\", \"QUANTITY_COMPLETED\", \"QUANTITY_SCRAPPED\", \"USD_RATE\", \"BASE_CURRENCY\", \"ITEM_COST\", \"MATERIAL_COST\", \"RESOURCE_COST\", \"OVERHEAD_COST\", \"OUTSIDE_PROCESSING_COST\", \"MATERIAL_DEPT\", \"RESOURCE_DEPT\", \"OVERHEAD_DEPT\", \"OS_PROCESS_DEPT\", \"BOM_REVISION\", \"BOM_REVISION_DATE\", \"ROUTING_REVISION\", \"ROUTING_REVISION_DATE\", \"DATE_RELEASED\", \"DATE_COMPLETED\", \"DATE_CLOSED\", \"DATE_STARTED\", \"DUE_DATE\", \"DEMAND_CLASS\", \"TOTAL_LABOR_HOURS\", \"TOTAL_LABOR_VALUE\", \"SCHEDULE_GROUP_NAME\", \"TOTAL_COSTS_INCURRED\", \"TOTAL_COSTS_RELIEVED\", \"TOTAL_VARIANCES_RELIEVED\", \"TOTAL_NET_ACTIVITIES\", \"TOTAL_COSTS_INCURRED_USD\", \"TOTAL_COSTS_RELIEVED_USD\", \"TOTAL_VARIANCES_RELIEVED_USD\", \"TOTAL_NET_ACTIVITIES_USD\", \"COMP_ITEM_NUMBER\", \"COMP_ITEM_DESCRIPTION\", \"COMP_ORG\", \"COMP_PLANNER_CODE\", \"COMP_MAKE_OR_BUY\", \"COMP_TBU\", \"COMP_ORG_TBU\", \"COMP_COMMODITY\", \"COMP_PRIMARY_ORG\", \"COMP_TRX_TYPE\", \"COMP_TRX_TYPE_ID\", \"COMP_REQUIRED_QUANTITY\", \"COMP_TRX_QUANTITY\", \"COMP_QUANTITY_PER_ASSEMBLY\", \"COMP_SUPPLY_SUBINV\", \"COMP_TRX_DATE\", \"COMP_ITEM_COST\", \"COMP_MATERIAL_COST\", \"COMP_RESOURCE_COST\", \"COMP_OVERHEAD_COST\", \"COMP_OUTSIDE_PROCESSING_COST\", \"COMP_EXTENDED_ITEM_COST\", \"COMP_ITEM_COST_USD\", \"COMP_MATERIAL_COST_USD\", \"COMP_MATERIAL_OH_COST_USD\", \"COMP_RESOURCE_COST_USD\", \"COMP_OVERHEAD_COST_USD\", \"COMP_OS_PROCESSING_COST_USD\", \"COMP_EXTENDED_ITEM_COST_USD\", \"G_ITEM_COST\", \"G_MATERIAL_COST\", \"G_MATERIAL_OVERHEAD_COST\", \"G_RESOURCE_COST\", \"G_OVERHEAD_COST\", \"G_OUTSIDE_PROCESSING_COST\", \"G_COMP_ITEM_COST\", \"G_COMP_MATERIAL_COST\", \"G_COMP_MATERIAL_OVERHEAD_COST\", \"G_COMP_RESOURCE_COST\", \"G_COMP_OVERHEAD_COST\", \"G_COMP_OUTSIDE_PROCESSING_COST\", \"G_COMP_EXTENDED_ITEM_COST\", \"G_COMP_ITEM_COST_USD\", \"G_COMP_MATERIAL_COST_USD\", \"G_COMP_MATERIAL_OH_COST_USD\", \"G_COMP_RESOURCE_COST_USD\", \"G_COMP_OVERHEAD_COST_USD\", \"G_COMP_OS_PROCESSING_COST_USD\", \"G_COMP_EXTENDED_ITEM_COST_USD\", \"COMP_ITEM_ADD_BACK_COST\", \"COMP_EXT_ITEM_ADD_BACK_COST\", \"COMP_ITEM_ADD_BACK_COST_USD\", \"COMP_EXT_ITEM_ADD_BACK_CST_USD\", \"WIP_ENTITY_ID\", \"INVENTORY_ITEM_ID\", \"ORGANIZATION_ID\", \"OE_HEADER_ID\", \"OE_LINE_ID\", \"COMP_ITEM_ID\", \"COMP_ORG_ID\", \"COMP_FISCAL_PERIOD\", \"ROW_CREATION_DATE\"})\nin\n    #\"Choose columns\";\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[{\"id\":\"56b03f15-b0af-4bb7-80dc-0724afce7b2c\",\"name\":\"Transform File from Escapes\",\"description\":\"\",\"parentId\":null,\"order\":1},{\"id\":\"c55b0cf5-047d-4542-9778-4e2ce8c90a59\",\"name\":\"Helper Queries\",\"description\":\"\",\"parentId\":\"56b03f15-b0af-4bb7-80dc-0724afce7b2c\",\"order\":2},{\"id\":\"40d28958-91bc-4d0d-b290-3cdd7f4f4411\",\"name\":\"Transform File from Master-Cleaning-List\",\"description\":\"\",\"parentId\":null,\"order\":1},{\"id\":\"e39c62f8-3bcc-47ba-beba-61c54a10160a\",\"name\":\"Helper Queries\",\"description\":\"\",\"parentId\":\"40d28958-91bc-4d0d-b290-3cdd7f4f4411\",\"order\":2},{\"id\":\"fae0b287-a26d-4a58-a05a-e0279df335c5\",\"name\":\"Inactive\",\"description\":\"\",\"parentId\":null,\"order\":0},{\"id\":\"b4b3ec88-7642-4839-90ec-4c7b8fd6a610\",\"name\":\"Transform file from Cumulus_Deviations\",\"description\":null,\"parentId\":null,\"order\":1},{\"id\":\"26c7ecda-c1a7-47e2-9851-79b2ac9e66a4\",\"name\":\"Helper queries (2)\",\"description\":null,\"parentId\":\"b4b3ec88-7642-4839-90ec-4c7b8fd6a610\",\"order\":0},{\"id\":\"168a4ac5-ad8e-44f3-9270-23735a21c431\",\"name\":\"Transform file from Shortages_Cumulus\",\"description\":null,\"parentId\":null,\"order\":0},{\"id\":\"7b4fc3f5-e9ba-43cc-be7e-066e90dc0662\",\"name\":\"Helper queries (3)\",\"description\":null,\"parentId\":\"168a4ac5-ad8e-44f3-9270-23735a21c431\",\"order\":0},{\"id\":\"c75e3e3f-24f1-4274-8963-67281cccb76a\",\"name\":\"Transform file from Cumulus_Equipment\",\"description\":null,\"parentId\":null,\"order\":0},{\"id\":\"29750181-0419-4931-9e13-5d62468c3d6e\",\"name\":\"Helper queries (4)\",\"description\":null,\"parentId\":\"c75e3e3f-24f1-4274-8963-67281cccb76a\",\"order\":0},{\"id\":\"ea105cb7-a12a-4499-8b33-2adc23498129\",\"name\":\"Transform file from ChangeRequests\",\"description\":null,\"parentId\":null,\"order\":0},{\"id\":\"430b5806-a86d-4603-8613-dc18dfcac97c\",\"name\":\"Helper queries (5)\",\"description\":null,\"parentId\":\"ea105cb7-a12a-4499-8b33-2adc23498129\",\"order\":0},{\"id\":\"def9b584-1e4d-43b9-a38f-13dd5ddbe665\",\"name\":\"Transform file from VHP-Electrodes_BlastedArea\",\"description\":null,\"parentId\":null,\"order\":0},{\"id\":\"23c6368c-0ede-48c5-b82e-ade3b06469f7\",\"name\":\"Helper queries (6)\",\"description\":null,\"parentId\":\"def9b584-1e4d-43b9-a38f-13dd5ddbe665\",\"order\":0},{\"id\":\"f5892ce5-1234-4159-b723-6fe3d0cf44e3\",\"name\":\"Transform file from VHP-Electrodes_CoatingData\",\"description\":null,\"parentId\":null,\"order\":0},{\"id\":\"48e6875a-5ba4-4ea8-98bc-02bd31b47f51\",\"name\":\"Helper queries (7)\",\"description\":null,\"parentId\":\"f5892ce5-1234-4159-b723-6fe3d0cf44e3\",\"order\":0}]"}],"entities":[{"$type":"LocalEntity","name":"Master-Cleaning-List","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Master-Cleaning-List.csv"},"attributes":[{"name":"Item Number","dataType":"string"},{"name":"FAI","dataType":"string"},{"name":"andere","dataType":"string"},{"name":"Losgröße","dataType":"int64"},{"name":"Bemerkung","dataType":"string"},{"name":"Neuer Lieferant","dataType":"string"},{"name":"Traveller Receipt (Title: Special Reqs)","dataType":"string"},{"name":"Buyer","dataType":"string"},{"name":"Receipt Routing","dataType":"string"},{"name":"Std Lieferant","dataType":"string"},{"name":"Info","dataType":"string"},{"name":"Aktualisiert","dataType":"string"},{"name":"Akt. Von","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T04:30:23.9857394+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/69205c50-2faf-4ac4-8f08-571f51397338/Master-Cleaning-List.csv?snapshot=2022-06-13T04%3A30%3A23.9544700Z"}]},{"$type":"LocalEntity","name":"Cumulus_Shortages","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Cumulus_Shortages.csv"},"attributes":[{"name":"OPEN","dataType":"boolean"},{"name":"DateTime_CREATED","dataType":"dateTime"},{"name":"SINGLE_INSTANCE","dataType":"boolean"},{"name":"DateTime_CLOSED","dataType":"dateTime"},{"name":"DAYS_OPEN","dataType":"double"},{"name":"QTY_SHORT","dataType":"int64"},{"name":"HOLD_NEW_BUILDS","dataType":"boolean"},{"name":"HOLD_COMPLETIONS","dataType":"boolean"},{"name":"ASSEMBLY_COUNT","dataType":"int64"},{"name":"QUEUE_ITEM_COUNT","dataType":"int64"},{"name":"PART_NUMBER","dataType":"string"},{"name":"PART_DESCRIPTION","dataType":"string"},{"name":"PLANNER_CODE","dataType":"string"},{"name":"FORECAST_FIELD","dataType":"string"},{"name":"PRODUCT_FAMILY","dataType":"string"},{"name":"PRODUCT_LINE","dataType":"string"},{"name":"BUYER","dataType":"string"},{"name":"PLANNER","dataType":"string"},{"name":"SUPPLIER","dataType":"string"},{"name":"QTY_DUE","dataType":"int64"},{"name":"DUE_DATE","dataType":"date"},{"name":"ROOT_CAUSE","dataType":"string"},{"name":"SUBMITTED_BY","dataType":"string"},{"name":"OWNER","dataType":"string"},{"name":"SERIAL_NUMBERS","dataType":"string"},{"name":"ASSEMBLIES_AFFECTED","dataType":"string"},{"name":"ORACLE_WO","dataType":"string"},{"name":"ORACLE_PROJECT","dataType":"string"},{"name":"NOTES","dataType":"string"},{"name":"Date_CREATED","dataType":"date"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T04:30:25.1272477+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/69205c50-2faf-4ac4-8f08-571f51397338/Cumulus_Shortages.csv?snapshot=2022-06-13T04%3A30%3A25.1097655Z"}]},{"$type":"LocalEntity","name":"Cumulus_Equipment","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Cumulus_Equipment.csv"},"attributes":[{"name":"ASSET","dataType":"int64"},{"name":"ENTITY","dataType":"int64"},{"name":"DEPARTMENT","dataType":"int64"},{"name":"STATUS","dataType":"string"},{"name":"RESPONSIBLE_ENGINEER","dataType":"string"},{"name":"ISO_17025","dataType":"string"},{"name":"NEXT_CAL_DUE","dataType":"date"},{"name":"NEXT_PM_DUE","dataType":"date"},{"name":"CAL_SOURCE","dataType":"string"},{"name":"MODEL","dataType":"string"},{"name":"DESCRIPTION","dataType":"string"},{"name":"SERIAL_NUMBER","dataType":"string"},{"name":"MANUFACTURER","dataType":"string"},{"name":"LEGACY_ASSET","dataType":"string"},{"name":"DISTRIBUTION_GROUP","dataType":"string"},{"name":"LOCKOUT_TAGOUT","dataType":"string"},{"name":"VENDOR","dataType":"string"},{"name":"NOTES","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T04:30:25.0491248+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/69205c50-2faf-4ac4-8f08-571f51397338/Cumulus_Equipment.csv?snapshot=2022-06-13T04%3A30%3A25.0308133Z"}]},{"$type":"LocalEntity","name":"ChangeRequests","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"ChangeRequests.csv"},"attributes":[{"name":"Change_Request_ID","dataType":"string"},{"name":"Agile ECO","dataType":"string"},{"name":"Aktuelles Datum","dataType":"date"},{"name":"Lieferant","dataType":"string"},{"name":"Lieferanten Nr.","dataType":"string"},{"name":"Artikelnr","dataType":"string"},{"name":"Bauteil Beschreibung","dataType":"string"},{"name":"Neue Rev","dataType":"string"},{"name":"Bearbeiter","dataType":"string"},{"name":"Ab PO","dataType":"string"},{"name":"Gewünschte Lieferung ab","dataType":"string"},{"name":"Alte  \nRev","dataType":"string"},{"name":"Lagerbest","dataType":"string"},{"name":"Restm\nRahmenvertr - PO - Kanban","dataType":"string"},{"name":"Nacharb","dataType":"string"},{"name":"Bis PO","dataType":"string"},{"name":"Lieferung bis","dataType":"string"},{"name":"Price Change","dataType":"string"},{"name":"Delivery From PO","dataType":"string"},{"name":"Start Deliveries","dataType":"string"},{"name":"Datum","dataType":"date"},{"name":"Erhalten - Übernommen","dataType":"string"},{"name":"Feedback","dataType":"string"},{"name":"geprüft, OK?","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T04:30:23.2744243+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/69205c50-2faf-4ac4-8f08-571f51397338/ChangeRequests.csv?snapshot=2022-06-13T04%3A30%3A23.2469010Z"}]},{"$type":"LocalEntity","name":"XXCOH_WIP_TRX_TAB","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"XXCOH_WIP_TRX_TAB.csv"},"attributes":[{"name":"ASOF_DATE","dataType":"date"},{"name":"TRANSACTION_ID","dataType":"double"},{"name":"ORGANIZATION_CODE","dataType":"string"},{"name":"SET_OF_BOOKS","dataType":"string"},{"name":"TRX_TYPE","dataType":"string"},{"name":"TRX_DATE","dataType":"dateTime"},{"name":"ACCT_ENTITY","dataType":"string"},{"name":"ACCT_DEPT","dataType":"string"},{"name":"ACCT_NUMBER","dataType":"string"},{"name":"TRX_CURRENCY_CODE","dataType":"string"},{"name":"FUNC_CURRENCY_CODE","dataType":"string"},{"name":"ENTERED_DR","dataType":"double"},{"name":"ENTERED_CR","dataType":"double"},{"name":"ACCOUNTED_DR","dataType":"double"},{"name":"ACCOUNTED_CR","dataType":"double"},{"name":"ACCOUNTED_DR_USD","dataType":"double"},{"name":"ACCOUNTED_CR_USD","dataType":"double"},{"name":"GL_TRANSFER_STATUS","dataType":"string"},{"name":"WIP_JOB_NAME","dataType":"string"},{"name":"COST_ELEMENT_NAME","dataType":"string"},{"name":"PERIOD_NAME","dataType":"string"},{"name":"CREATED_BY","dataType":"string"},{"name":"ACCOUNTING_LINE_TYPE","dataType":"string"},{"name":"TRANSACTION_QUANTITY","dataType":"double"},{"name":"TRANSACTION_UOM","dataType":"string"},{"name":"PRIMARY_QUANTITY","dataType":"double"},{"name":"PRIMARY_UOM","dataType":"string"},{"name":"USD_RATE","dataType":"double"},{"name":"DEPARTMENT_CODE","dataType":"string"},{"name":"RESOURCE_CODE","dataType":"string"},{"name":"WIP_ENTITY_ID","dataType":"double"},{"name":"ORGANIZATION_ID","dataType":"double"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"RESOURCE_ID","dataType":"double"},{"name":"ROW_CREATION_DATE","dataType":"dateTime"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T04:33:23.4685694+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/69205c50-2faf-4ac4-8f08-571f51397338/XXCOH_WIP_TRX_TAB.csv?snapshot=2022-06-13T04%3A33%3A23.4551585Z"}]},{"$type":"LocalEntity","name":"XXCOH_MI_WIP_DETAIL_TAB","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"XXCOH_MI_WIP_DETAIL_TAB.csv"},"attributes":[{"name":"ASOF_DATE","dataType":"date"},{"name":"WIP_ENTITY_NAME","dataType":"string"},{"name":"ENTITY_DESCRIPTION","dataType":"string"},{"name":"ENTITY_TYPE","dataType":"string"},{"name":"JOB_TYPE","dataType":"string"},{"name":"JOB_STATUS","dataType":"string"},{"name":"CLASS_CODE","dataType":"string"},{"name":"ITEM__NUMBER","dataType":"string"},{"name":"ITEM_DESCRIPTION","dataType":"string"},{"name":"TECHNICAL_BUSINESS_UNIT","dataType":"string"},{"name":"PRODUCT_FAMILY","dataType":"string"},{"name":"PRODUCT_LINE","dataType":"string"},{"name":"FORECAST_FIELD","dataType":"string"},{"name":"ORG_PRODUCT_FAMILY","dataType":"string"},{"name":"ORG_PRODUCT_LINE","dataType":"string"},{"name":"ORG_FORECAST_FIELD","dataType":"string"},{"name":"PLANNER_CODE","dataType":"string"},{"name":"ITEM_CUSTOMER","dataType":"string"},{"name":"ORDER_NUMBER","dataType":"double"},{"name":"ORDER_LINE","dataType":"string"},{"name":"OWNING_ORGANIZATION","dataType":"string"},{"name":"REPORTING_TBU","dataType":"string"},{"name":"SUBINVENTORY","dataType":"string"},{"name":"OPERATING_UNIT","dataType":"string"},{"name":"FISCAL_PERIOD","dataType":"double"},{"name":"PRIMARY_UOM_CODE","dataType":"string"},{"name":"QUANTITY_REMAINING","dataType":"double"},{"name":"START_QUANTITY","dataType":"double"},{"name":"QUANTITY_COMPLETED","dataType":"double"},{"name":"QUANTITY_SCRAPPED","dataType":"double"},{"name":"USD_RATE","dataType":"double"},{"name":"BASE_CURRENCY","dataType":"string"},{"name":"ITEM_COST","dataType":"double"},{"name":"MATERIAL_COST","dataType":"double"},{"name":"RESOURCE_COST","dataType":"double"},{"name":"OVERHEAD_COST","dataType":"double"},{"name":"OUTSIDE_PROCESSING_COST","dataType":"double"},{"name":"MATERIAL_DEPT","dataType":"string"},{"name":"RESOURCE_DEPT","dataType":"string"},{"name":"OVERHEAD_DEPT","dataType":"string"},{"name":"OS_PROCESS_DEPT","dataType":"string"},{"name":"BOM_REVISION","dataType":"string"},{"name":"BOM_REVISION_DATE","dataType":"dateTime"},{"name":"ROUTING_REVISION","dataType":"string"},{"name":"ROUTING_REVISION_DATE","dataType":"dateTime"},{"name":"DATE_RELEASED","dataType":"dateTime"},{"name":"DATE_COMPLETED","dataType":"dateTime"},{"name":"DATE_CLOSED","dataType":"dateTime"},{"name":"DATE_STARTED","dataType":"dateTime"},{"name":"DUE_DATE","dataType":"dateTime"},{"name":"DEMAND_CLASS","dataType":"string"},{"name":"TOTAL_LABOR_HOURS","dataType":"double"},{"name":"TOTAL_LABOR_VALUE","dataType":"double"},{"name":"SCHEDULE_GROUP_NAME","dataType":"string"},{"name":"TOTAL_COSTS_INCURRED","dataType":"double"},{"name":"TOTAL_COSTS_RELIEVED","dataType":"double"},{"name":"TOTAL_VARIANCES_RELIEVED","dataType":"double"},{"name":"TOTAL_NET_ACTIVITIES","dataType":"double"},{"name":"TOTAL_COSTS_INCURRED_USD","dataType":"double"},{"name":"TOTAL_COSTS_RELIEVED_USD","dataType":"double"},{"name":"TOTAL_VARIANCES_RELIEVED_USD","dataType":"double"},{"name":"TOTAL_NET_ACTIVITIES_USD","dataType":"double"},{"name":"COMP_ITEM_NUMBER","dataType":"string"},{"name":"COMP_ITEM_DESCRIPTION","dataType":"string"},{"name":"COMP_ORG","dataType":"string"},{"name":"COMP_PLANNER_CODE","dataType":"string"},{"name":"COMP_MAKE_OR_BUY","dataType":"string"},{"name":"COMP_TBU","dataType":"string"},{"name":"COMP_ORG_TBU","dataType":"string"},{"name":"COMP_COMMODITY","dataType":"string"},{"name":"COMP_PRIMARY_ORG","dataType":"string"},{"name":"COMP_TRX_TYPE","dataType":"string"},{"name":"COMP_TRX_TYPE_ID","dataType":"double"},{"name":"COMP_REQUIRED_QUANTITY","dataType":"double"},{"name":"COMP_TRX_QUANTITY","dataType":"double"},{"name":"COMP_QUANTITY_PER_ASSEMBLY","dataType":"double"},{"name":"COMP_SUPPLY_SUBINV","dataType":"string"},{"name":"COMP_TRX_DATE","dataType":"date"},{"name":"COMP_ITEM_COST","dataType":"double"},{"name":"COMP_MATERIAL_COST","dataType":"double"},{"name":"COMP_RESOURCE_COST","dataType":"double"},{"name":"COMP_OVERHEAD_COST","dataType":"double"},{"name":"COMP_OUTSIDE_PROCESSING_COST","dataType":"double"},{"name":"COMP_EXTENDED_ITEM_COST","dataType":"double"},{"name":"COMP_ITEM_COST_USD","dataType":"double"},{"name":"COMP_MATERIAL_COST_USD","dataType":"double"},{"name":"COMP_MATERIAL_OH_COST_USD","dataType":"double"},{"name":"COMP_RESOURCE_COST_USD","dataType":"double"},{"name":"COMP_OVERHEAD_COST_USD","dataType":"double"},{"name":"COMP_OS_PROCESSING_COST_USD","dataType":"double"},{"name":"COMP_EXTENDED_ITEM_COST_USD","dataType":"double"},{"name":"G_ITEM_COST","dataType":"double"},{"name":"G_MATERIAL_COST","dataType":"double"},{"name":"G_MATERIAL_OVERHEAD_COST","dataType":"double"},{"name":"G_RESOURCE_COST","dataType":"double"},{"name":"G_OVERHEAD_COST","dataType":"double"},{"name":"G_OUTSIDE_PROCESSING_COST","dataType":"double"},{"name":"G_COMP_ITEM_COST","dataType":"double"},{"name":"G_COMP_MATERIAL_COST","dataType":"double"},{"name":"G_COMP_MATERIAL_OVERHEAD_COST","dataType":"double"},{"name":"G_COMP_RESOURCE_COST","dataType":"double"},{"name":"G_COMP_OVERHEAD_COST","dataType":"double"},{"name":"G_COMP_OUTSIDE_PROCESSING_COST","dataType":"double"},{"name":"G_COMP_EXTENDED_ITEM_COST","dataType":"double"},{"name":"G_COMP_ITEM_COST_USD","dataType":"double"},{"name":"G_COMP_MATERIAL_COST_USD","dataType":"double"},{"name":"G_COMP_MATERIAL_OH_COST_USD","dataType":"double"},{"name":"G_COMP_RESOURCE_COST_USD","dataType":"double"},{"name":"G_COMP_OVERHEAD_COST_USD","dataType":"double"},{"name":"G_COMP_OS_PROCESSING_COST_USD","dataType":"double"},{"name":"G_COMP_EXTENDED_ITEM_COST_USD","dataType":"double"},{"name":"COMP_ITEM_ADD_BACK_COST","dataType":"double"},{"name":"COMP_EXT_ITEM_ADD_BACK_COST","dataType":"double"},{"name":"COMP_ITEM_ADD_BACK_COST_USD","dataType":"double"},{"name":"COMP_EXT_ITEM_ADD_BACK_CST_USD","dataType":"double"},{"name":"WIP_ENTITY_ID","dataType":"double"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"ORGANIZATION_ID","dataType":"double"},{"name":"OE_HEADER_ID","dataType":"double"},{"name":"OE_LINE_ID","dataType":"double"},{"name":"COMP_ITEM_ID","dataType":"double"},{"name":"COMP_ORG_ID","dataType":"double"},{"name":"COMP_FISCAL_PERIOD","dataType":"double"},{"name":"ROW_CREATION_DATE","dataType":"dateTime"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T04:59:13.3605421+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/69205c50-2faf-4ac4-8f08-571f51397338/XXCOH_MI_WIP_DETAIL_TAB.csv?snapshot=2022-06-13T04%3A59%3A13.3353865Z"}]}]}