{"name":"Flow_Oracle_Job-Data","description":"Flow for Oracle Job data GEP and KEP.\nDiscrete Jobs.\nMaterial Transactions","version":"1.0","culture":"en-US","modifiedTime":"2022-07-08T11:20:43.2140319+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":true,"queriesMetadata":{"MTL_TXN_SOURCE_TYPES":{"queryId":"472d522a-7698-4c1a-8efd-3a0ae3cf1d95","queryName":"MTL_TXN_SOURCE_TYPES","loadEnabled":true},"XXREP_WIP_DISCRETE_JOBS_V":{"queryId":"9d3ca54a-4030-423f-928b-492460208727","queryName":"XXREP_WIP_DISCRETE_JOBS_V","loadEnabled":true},"XXREP_MTL_MATERIAL_TRANSACTIONS":{"queryId":"122c7342-c315-488b-b143-dc711675e081","queryName":"XXREP_MTL_MATERIAL_TRANSACTIONS","loadEnabled":true},"RangeEnd":{"queryId":"cddeff84-5ce1-4605-8f3d-bdc79408df25","queryName":"RangeEnd"},"RangeStart":{"queryId":"f649350b-955c-48dd-86b8-a9ac275bed48","queryName":"RangeStart"},"XXREP_WIP_DISCRETE_JOBS_V_Canary":{"queryId":"f9b45c0b-44e7-4e90-83f0-846fd7ec76fa","queryName":"XXREP_WIP_DISCRETE_JOBS_V_Canary"},"XXREP_MTL_MATERIAL_TRANSACTIONS_Canary":{"queryId":"c5007dda-3f28-4bea-8a88-a6d006313aff","queryName":"XXREP_MTL_MATERIAL_TRANSACTIONS_Canary"}},"document":"section Section1;\r\n\r\nshared MTL_TXN_SOURCE_TYPES = let\r\n    Source = Value.NativeQuery(Snowflake.Databases(\"mma12090.snowflakecomputing.com\",\"COMPUTE_REPORTING\",[Role=\"GLBMFGOPERATIONSROLE\"]){[Name=\"PROD_DB\"]}[Data], \"SELECT * FROM PROD_DB.INV.MTL_TXN_SOURCE_TYPES\", null, [EnableFolding=true]),\r\n    #\"Choose columns\" = Table.SelectColumns(Source, {\"TRANSACTION_SOURCE_TYPE_ID\", \"LAST_UPDATE_DATE\", \"CREATION_DATE\", \"TRANSACTION_SOURCE_TYPE_NAME\", \"DESCRIPTION\", \"DISABLE_DATE\"}),\r\n    #\"Changed column type\" = Table.TransformColumnTypes(#\"Choose columns\", {{\"TRANSACTION_SOURCE_TYPE_ID\", Int64.Type}})\r\nin\r\n    #\"Changed column type\";\r\n\r\nshared XXREP_WIP_DISCRETE_JOBS_V = let\r\n    Source = Value.NativeQuery(Snowflake.Databases(\"mma12090.snowflakecomputing.com\",\"COMPUTE_REPORTING\",[Role=\"GLBMFGOPERATIONSROLE\"]){[Name=\"PROD_DB\"]}[Data], \"SELECT * FROM PROD_DB.APPS.XXREP_WIP_DISCRETE_JOBS_V Where ORGANIZATION_ID=944 or ORGANIZATION_ID=3306\", null, [EnableFolding=true]),\r\n    #\"Filtered rows\" = Table.SelectRows(Source, each [CREATION_DATE] > #datetime(2015, 9, 26, 0, 0, 0)),\r\n    #\"Changed column type\" = Table.TransformColumnTypes(#\"Filtered rows\", {{\"ORGANIZATION_ID\", Int64.Type}, {\"WIP_ENTITY_ID\", Int64.Type}, {\"LAST_UPDATED_BY\", Int64.Type}, {\"CREATED_BY\", Int64.Type}, {\"STATUS_TYPE\", Int64.Type}, {\"PRIMARY_ITEM_ID\", Int64.Type}, {\"MATERIAL_ACCOUNT\", Int64.Type}, {\"MATERIAL_OVERHEAD_ACCOUNT\", Int64.Type}, {\"RESOURCE_ACCOUNT\", Int64.Type}, {\"OUTSIDE_PROCESSING_ACCOUNT\", Int64.Type}, {\"MATERIAL_VARIANCE_ACCOUNT\", Int64.Type}, {\"RESOURCE_VARIANCE_ACCOUNT\", Int64.Type}, {\"OUTSIDE_PROC_VARIANCE_ACCOUNT\", Int64.Type}, {\"STD_COST_ADJUSTMENT_ACCOUNT\", Int64.Type}, {\"OVERHEAD_ACCOUNT\", Int64.Type}, {\"OVERHEAD_VARIANCE_ACCOUNT\", Int64.Type}, {\"BOM_REFERENCE_ID\", Int64.Type}, {\"ROUTING_REFERENCE_ID\", Int64.Type}, {\"COMMON_BOM_SEQUENCE_ID\", Int64.Type}, {\"COMMON_ROUTING_SEQUENCE_ID\", Int64.Type}, {\"SCHEDULE_GROUP_ID\", Int64.Type}, {\"LINE_ID\", Int64.Type}, {\"PROJECT_ID\", Int64.Type}, {\"TASK_ID\", Int64.Type}, {\"KANBAN_CARD_ID\", Int64.Type}, {\"PRIORITY\", Int64.Type}, {\"JOB_STATUS_CODE\", Int64.Type}}),\r\n    #\"XXREP_WIP_DISCRETE_JOBS_V-4352454154494F4E5F44415445-autogenerated_for_incremental_refresh\" = Table.SelectRows(#\"Changed column type\", each DateTime.From([CREATION_DATE]) >= RangeStart and DateTime.From([CREATION_DATE]) < RangeEnd)\r\nin\r\n    #\"XXREP_WIP_DISCRETE_JOBS_V-4352454154494F4E5F44415445-autogenerated_for_incremental_refresh\";\r\n\r\nshared XXREP_WIP_DISCRETE_JOBS_V_Canary = let\r\n    Source = Value.NativeQuery(Snowflake.Databases(\"mma12090.snowflakecomputing.com\",\"COMPUTE_REPORTING\",[Role=\"GLBMFGOPERATIONSROLE\"]){[Name=\"PROD_DB\"]}[Data], \"SELECT * FROM PROD_DB.APPS.XXREP_WIP_DISCRETE_JOBS_V Where ORGANIZATION_ID=944 or ORGANIZATION_ID=3306\", null, [EnableFolding=true]),\r\n    #\"Filtered rows\" = Table.SelectRows(Source, each [CREATION_DATE] > #datetime(2015, 9, 26, 0, 0, 0)),\r\n    #\"Changed column type\" = Table.TransformColumnTypes(#\"Filtered rows\", {{\"ORGANIZATION_ID\", Int64.Type}, {\"WIP_ENTITY_ID\", Int64.Type}, {\"LAST_UPDATED_BY\", Int64.Type}, {\"CREATED_BY\", Int64.Type}, {\"STATUS_TYPE\", Int64.Type}, {\"PRIMARY_ITEM_ID\", Int64.Type}, {\"MATERIAL_ACCOUNT\", Int64.Type}, {\"MATERIAL_OVERHEAD_ACCOUNT\", Int64.Type}, {\"RESOURCE_ACCOUNT\", Int64.Type}, {\"OUTSIDE_PROCESSING_ACCOUNT\", Int64.Type}, {\"MATERIAL_VARIANCE_ACCOUNT\", Int64.Type}, {\"RESOURCE_VARIANCE_ACCOUNT\", Int64.Type}, {\"OUTSIDE_PROC_VARIANCE_ACCOUNT\", Int64.Type}, {\"STD_COST_ADJUSTMENT_ACCOUNT\", Int64.Type}, {\"OVERHEAD_ACCOUNT\", Int64.Type}, {\"OVERHEAD_VARIANCE_ACCOUNT\", Int64.Type}, {\"BOM_REFERENCE_ID\", Int64.Type}, {\"ROUTING_REFERENCE_ID\", Int64.Type}, {\"COMMON_BOM_SEQUENCE_ID\", Int64.Type}, {\"COMMON_ROUTING_SEQUENCE_ID\", Int64.Type}, {\"SCHEDULE_GROUP_ID\", Int64.Type}, {\"LINE_ID\", Int64.Type}, {\"PROJECT_ID\", Int64.Type}, {\"TASK_ID\", Int64.Type}, {\"KANBAN_CARD_ID\", Int64.Type}, {\"PRIORITY\", Int64.Type}, {\"JOB_STATUS_CODE\", Int64.Type}}),\r\n    #\"XXREP_WIP_DISCRETE_JOBS_V-4352454154494F4E5F44415445-autogenerated_for_incremental_refresh\" = Table.SelectRows(#\"Changed column type\", each DateTime.From([CREATION_DATE]) >= RangeStart and DateTime.From([CREATION_DATE]) < RangeEnd), #\"XXREP_WIP_DISCRETE_JOBS_V_Canary-4C4153545F5550444154455F44415445-autogenerated_for_incremental_refresh\" = DateTime.ToText(Table.Max(#\"XXREP_WIP_DISCRETE_JOBS_V-4352454154494F4E5F44415445-autogenerated_for_incremental_refresh\",each [LAST_UPDATE_DATE], [LAST_UPDATE_DATE=#datetime(0001,01,01,00,00,00)])[LAST_UPDATE_DATE]) in #\"XXREP_WIP_DISCRETE_JOBS_V_Canary-4C4153545F5550444154455F44415445-autogenerated_for_incremental_refresh\";\r\n\r\nshared XXREP_MTL_MATERIAL_TRANSACTIONS = let\r\n    Source = Value.NativeQuery(Snowflake.Databases(\"mma12090.snowflakecomputing.com\",\"COMPUTE_REPORTING\",[Role=\"GLBMFGOPERATIONSROLE\"]){[Name=\"PROD_DB\"]}[Data], \"SELECT * FROM PROD_DB.APPS.XXREP_MTL_MATERIAL_TRANSACTIONS Where ORGANIZATION_ID=944 or ORGANIZATION_ID=3306\", null, [EnableFolding=true]),\r\n    #\"Filtered rows\" = Table.SelectRows(Source, each [TRANSACTION_DATE] > #datetime(2015, 9, 26, 0, 0, 0)),\r\n    #\"Changed column type\" = Table.TransformColumnTypes(#\"Filtered rows\", {{\"PROGRAM_ID\", Int64.Type}, {\"TRANSACTION_ID\", Int64.Type}, {\"REQUEST_ID\", Int64.Type}, {\"INVENTORY_ITEM_ID\", Int64.Type}, {\"ORGANIZATION_ID\", Int64.Type}, {\"TRANSACTION_TYPE_ID\", Int64.Type}, {\"TRANSACTION_ACTION_ID\", Int64.Type}, {\"TRANSACTION_SOURCE_TYPE_ID\", Int64.Type}, {\"TRANSACTION_SOURCE_ID\", Int64.Type}, {\"ACCT_PERIOD_ID\", Int64.Type}}),\r\n    #\"Choose columns\" = Table.SelectColumns(#\"Changed column type\", {\"TRANSACTION_ID\", \"LAST_UPDATE_DATE\", \"LAST_UPDATED_BY\", \"CREATION_DATE\", \"CREATED_BY\", \"LAST_UPDATE_LOGIN\", \"REQUEST_ID\", \"PROGRAM_APPLICATION_ID\", \"PROGRAM_ID\", \"PROGRAM_UPDATE_DATE\", \"INVENTORY_ITEM_ID\", \"REVISION\", \"ORGANIZATION_ID\", \"SUBINVENTORY_CODE\", \"LOCATOR_ID\", \"TRANSACTION_TYPE_ID\", \"TRANSACTION_ACTION_ID\", \"TRANSACTION_SOURCE_TYPE_ID\", \"TRANSACTION_SOURCE_ID\", \"TRANSACTION_SOURCE_NAME\", \"TRANSACTION_QUANTITY\", \"TRANSACTION_UOM\", \"PRIMARY_QUANTITY\", \"TRANSACTION_DATE\", \"VARIANCE_AMOUNT\", \"ACCT_PERIOD_ID\", \"TRANSACTION_REFERENCE\", \"REASON_ID\", \"DISTRIBUTION_ACCOUNT_ID\", \"ENCUMBRANCE_ACCOUNT\", \"ENCUMBRANCE_AMOUNT\", \"COST_UPDATE_ID\", \"COSTED_FLAG\", \"TRANSACTION_GROUP_ID\", \"INVOICED_FLAG\", \"ACTUAL_COST\", \"TRANSACTION_COST\", \"PRIOR_COST\", \"NEW_COST\", \"CURRENCY_CODE\", \"CURRENCY_CONVERSION_RATE\", \"CURRENCY_CONVERSION_TYPE\", \"CURRENCY_CONVERSION_DATE\", \"USSGL_TRANSACTION_CODE\", \"QUANTITY_ADJUSTED\", \"EMPLOYEE_CODE\", \"DEPARTMENT_ID\", \"OPERATION_SEQ_NUM\", \"MASTER_SCHEDULE_UPDATE_CODE\", \"RECEIVING_DOCUMENT\", \"PICKING_LINE_ID\", \"TRX_SOURCE_LINE_ID\", \"TRX_SOURCE_DELIVERY_ID\", \"REPETITIVE_LINE_ID\", \"PHYSICAL_ADJUSTMENT_ID\", \"CYCLE_COUNT_ID\", \"RMA_LINE_ID\", \"TRANSFER_TRANSACTION_ID\", \"TRANSACTION_SET_ID\", \"RCV_TRANSACTION_ID\", \"MOVE_TRANSACTION_ID\", \"COMPLETION_TRANSACTION_ID\", \"SHORTAGE_PROCESS_CODE\", \"SOURCE_CODE\", \"SOURCE_LINE_ID\", \"VENDOR_LOT_NUMBER\", \"TRANSFER_ORGANIZATION_ID\", \"TRANSFER_SUBINVENTORY\", \"TRANSFER_LOCATOR_ID\", \"SHIPMENT_NUMBER\", \"TRANSFER_COST\", \"TRANSPORTATION_DIST_ACCOUNT\", \"TRANSPORTATION_COST\", \"TRANSFER_COST_DIST_ACCOUNT\", \"WAYBILL_AIRBILL\", \"FREIGHT_CODE\", \"NUMBER_OF_CONTAINERS\", \"VALUE_CHANGE\", \"PERCENTAGE_CHANGE\", \"MOVEMENT_ID\", \"TASK_ID\", \"TO_TASK_ID\", \"PROJECT_ID\", \"TO_PROJECT_ID\", \"SOURCE_PROJECT_ID\", \"PA_EXPENDITURE_ORG_ID\", \"SOURCE_TASK_ID\", \"EXPENDITURE_TYPE\", \"ERROR_CODE\", \"ERROR_EXPLANATION\", \"PRIOR_COSTED_QUANTITY\", \"TRANSFER_PRIOR_COSTED_QUANTITY\", \"FINAL_COMPLETION_FLAG\", \"PM_COST_COLLECTED\", \"PM_COST_COLLECTOR_GROUP_ID\", \"SHIPMENT_COSTED\", \"TRANSFER_PERCENTAGE\", \"MATERIAL_ACCOUNT\", \"MATERIAL_OVERHEAD_ACCOUNT\", \"RESOURCE_ACCOUNT\", \"OUTSIDE_PROCESSING_ACCOUNT\", \"OVERHEAD_ACCOUNT\", \"COST_GROUP_ID\", \"TRANSFER_COST_GROUP_ID\", \"FLOW_SCHEDULE\", \"QA_COLLECTION_ID\", \"OVERCOMPLETION_TRANSACTION_QTY\", \"OVERCOMPLETION_PRIMARY_QTY\", \"OVERCOMPLETION_TRANSACTION_ID\", \"MVT_STAT_STATUS\", \"COMMON_BOM_SEQ_ID\", \"COMMON_ROUTING_SEQ_ID\", \"ORG_COST_GROUP_ID\", \"COST_TYPE_ID\", \"PERIODIC_PRIMARY_QUANTITY\", \"MOVE_ORDER_LINE_ID\", \"TASK_GROUP_ID\", \"PICK_SLIP_NUMBER\", \"LPN_ID\", \"TRANSFER_LPN_ID\", \"PICK_STRATEGY_ID\", \"PICK_RULE_ID\", \"PUT_AWAY_STRATEGY_ID\", \"PUT_AWAY_RULE_ID\", \"CONTENT_LPN_ID\", \"PICK_SLIP_DATE\", \"COST_CATEGORY_ID\", \"ORGANIZATION_TYPE\", \"TRANSFER_ORGANIZATION_TYPE\", \"OWNING_ORGANIZATION_ID\", \"OWNING_TP_TYPE\", \"XFR_OWNING_ORGANIZATION_ID\", \"TRANSFER_OWNING_TP_TYPE\", \"PLANNING_ORGANIZATION_ID\", \"PLANNING_TP_TYPE\", \"XFR_PLANNING_ORGANIZATION_ID\", \"TRANSFER_PLANNING_TP_TYPE\", \"SECONDARY_UOM_CODE\", \"SECONDARY_TRANSACTION_QUANTITY\", \"TRANSACTION_GROUP_SEQ\", \"SHIP_TO_LOCATION_ID\", \"RESERVATION_ID\", \"TRANSACTION_MODE\", \"TRANSACTION_BATCH_ID\", \"TRANSACTION_BATCH_SEQ\", \"INTRANSIT_ACCOUNT\", \"FOB_POINT\", \"PARENT_TRANSACTION_ID\", \"LOGICAL_TRX_TYPE_CODE\", \"TRX_FLOW_HEADER_ID\", \"LOGICAL_TRANSACTIONS_CREATED\", \"LOGICAL_TRANSACTION\", \"INTERCOMPANY_COST\", \"INTERCOMPANY_PRICING_OPTION\", \"INTERCOMPANY_CURRENCY_CODE\", \"ORIGINAL_TRANSACTION_TEMP_ID\", \"TRANSFER_PRICE\", \"EXPENSE_ACCOUNT_ID\", \"COGS_RECOGNITION_PERCENT\", \"SO_ISSUE_ACCOUNT_TYPE\", \"OPM_COSTED_FLAG\", \"MATERIAL_EXPENSE_ACCOUNT\", \"TRANSACTION_EXTRACTED\", \"XML_DOCUMENT_ID\", \"ITEM_ORG_KEY_ID\"}),\r\n    #\"XXREP_MTL_MATERIAL_TRANSACTIONS-5452414E53414354494F4E5F44415445-autogenerated_for_incremental_refresh\" = Table.SelectRows(#\"Choose columns\", each DateTime.From([TRANSACTION_DATE]) >= RangeStart and DateTime.From([TRANSACTION_DATE]) < RangeEnd)\r\nin\r\n    #\"XXREP_MTL_MATERIAL_TRANSACTIONS-5452414E53414354494F4E5F44415445-autogenerated_for_incremental_refresh\";\r\n\r\nshared XXREP_MTL_MATERIAL_TRANSACTIONS_Canary = let\r\n    Source = Value.NativeQuery(Snowflake.Databases(\"mma12090.snowflakecomputing.com\",\"COMPUTE_REPORTING\",[Role=\"GLBMFGOPERATIONSROLE\"]){[Name=\"PROD_DB\"]}[Data], \"SELECT * FROM PROD_DB.APPS.XXREP_MTL_MATERIAL_TRANSACTIONS Where ORGANIZATION_ID=944 or ORGANIZATION_ID=3306\", null, [EnableFolding=true]),\r\n    #\"Filtered rows\" = Table.SelectRows(Source, each [TRANSACTION_DATE] > #datetime(2015, 9, 26, 0, 0, 0)),\r\n    #\"Changed column type\" = Table.TransformColumnTypes(#\"Filtered rows\", {{\"PROGRAM_ID\", Int64.Type}, {\"TRANSACTION_ID\", Int64.Type}, {\"REQUEST_ID\", Int64.Type}, {\"INVENTORY_ITEM_ID\", Int64.Type}, {\"ORGANIZATION_ID\", Int64.Type}, {\"TRANSACTION_TYPE_ID\", Int64.Type}, {\"TRANSACTION_ACTION_ID\", Int64.Type}, {\"TRANSACTION_SOURCE_TYPE_ID\", Int64.Type}, {\"TRANSACTION_SOURCE_ID\", Int64.Type}, {\"ACCT_PERIOD_ID\", Int64.Type}}),\r\n    #\"Choose columns\" = Table.SelectColumns(#\"Changed column type\", {\"TRANSACTION_ID\", \"LAST_UPDATE_DATE\", \"LAST_UPDATED_BY\", \"CREATION_DATE\", \"CREATED_BY\", \"LAST_UPDATE_LOGIN\", \"REQUEST_ID\", \"PROGRAM_APPLICATION_ID\", \"PROGRAM_ID\", \"PROGRAM_UPDATE_DATE\", \"INVENTORY_ITEM_ID\", \"REVISION\", \"ORGANIZATION_ID\", \"SUBINVENTORY_CODE\", \"LOCATOR_ID\", \"TRANSACTION_TYPE_ID\", \"TRANSACTION_ACTION_ID\", \"TRANSACTION_SOURCE_TYPE_ID\", \"TRANSACTION_SOURCE_ID\", \"TRANSACTION_SOURCE_NAME\", \"TRANSACTION_QUANTITY\", \"TRANSACTION_UOM\", \"PRIMARY_QUANTITY\", \"TRANSACTION_DATE\", \"VARIANCE_AMOUNT\", \"ACCT_PERIOD_ID\", \"TRANSACTION_REFERENCE\", \"REASON_ID\", \"DISTRIBUTION_ACCOUNT_ID\", \"ENCUMBRANCE_ACCOUNT\", \"ENCUMBRANCE_AMOUNT\", \"COST_UPDATE_ID\", \"COSTED_FLAG\", \"TRANSACTION_GROUP_ID\", \"INVOICED_FLAG\", \"ACTUAL_COST\", \"TRANSACTION_COST\", \"PRIOR_COST\", \"NEW_COST\", \"CURRENCY_CODE\", \"CURRENCY_CONVERSION_RATE\", \"CURRENCY_CONVERSION_TYPE\", \"CURRENCY_CONVERSION_DATE\", \"USSGL_TRANSACTION_CODE\", \"QUANTITY_ADJUSTED\", \"EMPLOYEE_CODE\", \"DEPARTMENT_ID\", \"OPERATION_SEQ_NUM\", \"MASTER_SCHEDULE_UPDATE_CODE\", \"RECEIVING_DOCUMENT\", \"PICKING_LINE_ID\", \"TRX_SOURCE_LINE_ID\", \"TRX_SOURCE_DELIVERY_ID\", \"REPETITIVE_LINE_ID\", \"PHYSICAL_ADJUSTMENT_ID\", \"CYCLE_COUNT_ID\", \"RMA_LINE_ID\", \"TRANSFER_TRANSACTION_ID\", \"TRANSACTION_SET_ID\", \"RCV_TRANSACTION_ID\", \"MOVE_TRANSACTION_ID\", \"COMPLETION_TRANSACTION_ID\", \"SHORTAGE_PROCESS_CODE\", \"SOURCE_CODE\", \"SOURCE_LINE_ID\", \"VENDOR_LOT_NUMBER\", \"TRANSFER_ORGANIZATION_ID\", \"TRANSFER_SUBINVENTORY\", \"TRANSFER_LOCATOR_ID\", \"SHIPMENT_NUMBER\", \"TRANSFER_COST\", \"TRANSPORTATION_DIST_ACCOUNT\", \"TRANSPORTATION_COST\", \"TRANSFER_COST_DIST_ACCOUNT\", \"WAYBILL_AIRBILL\", \"FREIGHT_CODE\", \"NUMBER_OF_CONTAINERS\", \"VALUE_CHANGE\", \"PERCENTAGE_CHANGE\", \"MOVEMENT_ID\", \"TASK_ID\", \"TO_TASK_ID\", \"PROJECT_ID\", \"TO_PROJECT_ID\", \"SOURCE_PROJECT_ID\", \"PA_EXPENDITURE_ORG_ID\", \"SOURCE_TASK_ID\", \"EXPENDITURE_TYPE\", \"ERROR_CODE\", \"ERROR_EXPLANATION\", \"PRIOR_COSTED_QUANTITY\", \"TRANSFER_PRIOR_COSTED_QUANTITY\", \"FINAL_COMPLETION_FLAG\", \"PM_COST_COLLECTED\", \"PM_COST_COLLECTOR_GROUP_ID\", \"SHIPMENT_COSTED\", \"TRANSFER_PERCENTAGE\", \"MATERIAL_ACCOUNT\", \"MATERIAL_OVERHEAD_ACCOUNT\", \"RESOURCE_ACCOUNT\", \"OUTSIDE_PROCESSING_ACCOUNT\", \"OVERHEAD_ACCOUNT\", \"COST_GROUP_ID\", \"TRANSFER_COST_GROUP_ID\", \"FLOW_SCHEDULE\", \"QA_COLLECTION_ID\", \"OVERCOMPLETION_TRANSACTION_QTY\", \"OVERCOMPLETION_PRIMARY_QTY\", \"OVERCOMPLETION_TRANSACTION_ID\", \"MVT_STAT_STATUS\", \"COMMON_BOM_SEQ_ID\", \"COMMON_ROUTING_SEQ_ID\", \"ORG_COST_GROUP_ID\", \"COST_TYPE_ID\", \"PERIODIC_PRIMARY_QUANTITY\", \"MOVE_ORDER_LINE_ID\", \"TASK_GROUP_ID\", \"PICK_SLIP_NUMBER\", \"LPN_ID\", \"TRANSFER_LPN_ID\", \"PICK_STRATEGY_ID\", \"PICK_RULE_ID\", \"PUT_AWAY_STRATEGY_ID\", \"PUT_AWAY_RULE_ID\", \"CONTENT_LPN_ID\", \"PICK_SLIP_DATE\", \"COST_CATEGORY_ID\", \"ORGANIZATION_TYPE\", \"TRANSFER_ORGANIZATION_TYPE\", \"OWNING_ORGANIZATION_ID\", \"OWNING_TP_TYPE\", \"XFR_OWNING_ORGANIZATION_ID\", \"TRANSFER_OWNING_TP_TYPE\", \"PLANNING_ORGANIZATION_ID\", \"PLANNING_TP_TYPE\", \"XFR_PLANNING_ORGANIZATION_ID\", \"TRANSFER_PLANNING_TP_TYPE\", \"SECONDARY_UOM_CODE\", \"SECONDARY_TRANSACTION_QUANTITY\", \"TRANSACTION_GROUP_SEQ\", \"SHIP_TO_LOCATION_ID\", \"RESERVATION_ID\", \"TRANSACTION_MODE\", \"TRANSACTION_BATCH_ID\", \"TRANSACTION_BATCH_SEQ\", \"INTRANSIT_ACCOUNT\", \"FOB_POINT\", \"PARENT_TRANSACTION_ID\", \"LOGICAL_TRX_TYPE_CODE\", \"TRX_FLOW_HEADER_ID\", \"LOGICAL_TRANSACTIONS_CREATED\", \"LOGICAL_TRANSACTION\", \"INTERCOMPANY_COST\", \"INTERCOMPANY_PRICING_OPTION\", \"INTERCOMPANY_CURRENCY_CODE\", \"ORIGINAL_TRANSACTION_TEMP_ID\", \"TRANSFER_PRICE\", \"EXPENSE_ACCOUNT_ID\", \"COGS_RECOGNITION_PERCENT\", \"SO_ISSUE_ACCOUNT_TYPE\", \"OPM_COSTED_FLAG\", \"MATERIAL_EXPENSE_ACCOUNT\", \"TRANSACTION_EXTRACTED\", \"XML_DOCUMENT_ID\", \"ITEM_ORG_KEY_ID\"}),\r\n    #\"XXREP_MTL_MATERIAL_TRANSACTIONS-5452414E53414354494F4E5F44415445-autogenerated_for_incremental_refresh\" = Table.SelectRows(#\"Choose columns\", each DateTime.From([TRANSACTION_DATE]) >= RangeStart and DateTime.From([TRANSACTION_DATE]) < RangeEnd), #\"XXREP_MTL_MATERIAL_TRANSACTIONS_Canary-4C4153545F5550444154455F44415445-autogenerated_for_incremental_refresh\" = DateTime.ToText(Table.Max(#\"XXREP_MTL_MATERIAL_TRANSACTIONS-5452414E53414354494F4E5F44415445-autogenerated_for_incremental_refresh\",each [LAST_UPDATE_DATE], [LAST_UPDATE_DATE=#datetime(0001,01,01,00,00,00)])[LAST_UPDATE_DATE]) in #\"XXREP_MTL_MATERIAL_TRANSACTIONS_Canary-4C4153545F5550444154455F44415445-autogenerated_for_incremental_refresh\";\r\n\r\nshared RangeStart = let RangeStart = #datetime(0001,01,01,00,00,00) meta [IsParameterQuery=true, List={}, Type=\"DateTime\", IsParameterQueryRequired=true, Description=\"autogenerated_for_incremental_refresh\"] in RangeStart;\r\n\r\nshared RangeEnd = let RangeEnd = #datetime(9999,12,31,23,59,59) meta [IsParameterQuery=true, List={}, Type=\"DateTime\", IsParameterQueryRequired=true, Description=\"autogenerated_for_incremental_refresh\"] in RangeEnd;\r\n\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"MTL_TXN_SOURCE_TYPES","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"MTL_TXN_SOURCE_TYPES.csv"},"attributes":[{"name":"TRANSACTION_SOURCE_TYPE_ID","dataType":"int64"},{"name":"LAST_UPDATE_DATE","dataType":"dateTime"},{"name":"CREATION_DATE","dataType":"dateTime"},{"name":"TRANSACTION_SOURCE_TYPE_NAME","dataType":"string"},{"name":"DESCRIPTION","dataType":"string"},{"name":"DISABLE_DATE","dataType":"dateTime"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-07-10T05:17:05.4962603+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/3cb7dd71-d64b-4b66-9046-a4b1c00b1736/MTL_TXN_SOURCE_TYPES.csv?snapshot=2022-07-10T05%3A16%3A51.8461979Z"}]},{"$type":"LocalEntity","name":"XXREP_WIP_DISCRETE_JOBS_V","description":"","pbi:refreshPolicy":{"$type":"IncrementalRefreshPolicy","locationPattern":"XXREP_WIP_DISCRETE_JOBS_V/part.csv","rollingWindowGranularity":"year","rollingWindowPeriods":5,"incrementalGranularity":"quarter","incrementalPeriods":6,"pollingQuery":"XXREP_WIP_DISCRETE_JOBS_V_Canary"},"annotations":[{"name":"pbi:IncrementalRefreshDetectChangeAttribute","value":"LAST_UPDATE_DATE"},{"name":"pbi:IncrementalRefreshFilterByAttribute","value":"CREATION_DATE"}],"attributes":[{"name":"ORGANIZATION_ID","dataType":"int64"},{"name":"WIP_ENTITY_ID","dataType":"int64"},{"name":"WIPJOB_ORG_KEY_CODE","dataType":"string"},{"name":"WIPJOB_ORG_KEY_ID","dataType":"string"},{"name":"LAST_UPDATE_DATE","dataType":"dateTime"},{"name":"LAST_UPDATED_BY","dataType":"int64"},{"name":"CREATION_DATE","dataType":"dateTime"},{"name":"CREATED_BY","dataType":"int64"},{"name":"DESCRIPTION","dataType":"string"},{"name":"STATUS_TYPE","dataType":"int64"},{"name":"PRIMARY_ITEM_ID","dataType":"int64"},{"name":"CLASS_CODE","dataType":"string"},{"name":"MATERIAL_ACCOUNT","dataType":"int64"},{"name":"MATERIAL_OVERHEAD_ACCOUNT","dataType":"int64"},{"name":"RESOURCE_ACCOUNT","dataType":"int64"},{"name":"OUTSIDE_PROCESSING_ACCOUNT","dataType":"int64"},{"name":"MATERIAL_VARIANCE_ACCOUNT","dataType":"int64"},{"name":"RESOURCE_VARIANCE_ACCOUNT","dataType":"int64"},{"name":"OUTSIDE_PROC_VARIANCE_ACCOUNT","dataType":"int64"},{"name":"STD_COST_ADJUSTMENT_ACCOUNT","dataType":"int64"},{"name":"OVERHEAD_ACCOUNT","dataType":"int64"},{"name":"OVERHEAD_VARIANCE_ACCOUNT","dataType":"int64"},{"name":"START_QUANTITY","dataType":"double"},{"name":"QUANTITY_REMAINING","dataType":"double"},{"name":"QUANTITY_COMPLETED","dataType":"double"},{"name":"QUANTITY_SCRAPPED","dataType":"double"},{"name":"NET_QUANTITY","dataType":"double"},{"name":"BOM_REFERENCE_ID","dataType":"int64"},{"name":"ROUTING_REFERENCE_ID","dataType":"int64"},{"name":"COMMON_BOM_SEQUENCE_ID","dataType":"int64"},{"name":"COMMON_ROUTING_SEQUENCE_ID","dataType":"int64"},{"name":"BOM_REVISION","dataType":"string"},{"name":"ROUTING_REVISION","dataType":"string"},{"name":"BOM_REVISION_DATE","dataType":"dateTime"},{"name":"ROUTING_REVISION_DATE","dataType":"dateTime"},{"name":"LOT_NUMBER","dataType":"string"},{"name":"ALTERNATE_BOM_DESIGNATOR","dataType":"string"},{"name":"ALTERNATE_ROUTING_DESIGNATOR","dataType":"string"},{"name":"COMPLETION_SUBINVENTORY","dataType":"string"},{"name":"COMPLETION_LOCATOR_ID","dataType":"double"},{"name":"SUB_LOCATOR_CONTROL","dataType":"double"},{"name":"SCHEDULE_GROUP_NAME","dataType":"string"},{"name":"SCHEDULE_GROUP_ID","dataType":"int64"},{"name":"BUILD_SEQUENCE","dataType":"double"},{"name":"LINE_CODE","dataType":"string"},{"name":"LINE_ID","dataType":"int64"},{"name":"PROJECT_ID","dataType":"int64"},{"name":"TASK_ID","dataType":"int64"},{"name":"END_ITEM_UNIT_NUMBER","dataType":"string"},{"name":"DEMAND_CLASS","dataType":"string"},{"name":"SCHEDULED_START_DATE","dataType":"dateTime"},{"name":"DATE_RELEASED","dataType":"dateTime"},{"name":"SCHEDULED_COMPLETION_DATE","dataType":"dateTime"},{"name":"DATE_COMPLETED","dataType":"dateTime"},{"name":"DATE_CLOSED","dataType":"dateTime"},{"name":"OVERCOMPLETION_TOLERANCE_VALUE","dataType":"double"},{"name":"KANBAN_CARD_ID","dataType":"int64"},{"name":"KANBAN_CARD_NUMBER","dataType":"string"},{"name":"PO_CREATION_TIME","dataType":"double"},{"name":"PRIORITY","dataType":"int64"},{"name":"DUE_DATE","dataType":"dateTime"},{"name":"EST_SCRAP_ACCOUNT","dataType":"double"},{"name":"EST_SCRAP_VAR_ACCOUNT","dataType":"double"},{"name":"ENTITY_TYPE","dataType":"double"},{"name":"DUE_DATE_PENALTY","dataType":"double"},{"name":"DUE_DATE_TOLERANCE","dataType":"double"},{"name":"COPRODUCTS_SUPPLY","dataType":"double"},{"name":"REQUESTED_START_DATE","dataType":"dateTime"},{"name":"SERIALIZATION_START_OP","dataType":"double"},{"name":"ACTUAL_START_DATE","dataType":"dateTime"},{"name":"EXPECTED_HOLD_RELEASE_DATE","dataType":"dateTime"},{"name":"INVORG_CODE","dataType":"string"},{"name":"ASSEMBLY_ITEM_NUMBER","dataType":"string"},{"name":"JOB_SOURCE","dataType":"string"},{"name":"JOB_STATUS_CODE","dataType":"int64"},{"name":"JOB_STATUS","dataType":"string"},{"name":"WIP_SUPPLY_TYPE_CODE","dataType":"double"},{"name":"WIP_SUPPLY_TYPE","dataType":"string"},{"name":"JB_TYPE","dataType":"string"},{"name":"JOB_NUMBER","dataType":"string"},{"name":"JOB_DESCRIPTION","dataType":"string"},{"name":"FIRM_PLANNED_FLAG","dataType":"string"},{"name":"JOB_TYPE","dataType":"string"},{"name":"FIRST_UNIT_START_DATE","dataType":"dateTime"},{"name":"FIRST_UNIT_COMPLETION_DATE","dataType":"dateTime"},{"name":"LAST_UNIT_START_DATE","dataType":"dateTime"},{"name":"LAST_UNIT_COMPLETION_DATE","dataType":"dateTime"},{"name":"DATE_LAST_MOVED","dataType":"dateTime"},{"name":"PROJECT_NUMBER","dataType":"string"},{"name":"PROJECT_NAME","dataType":"string"},{"name":"SALES_ORDER_NO_DFF","dataType":"double"},{"name":"SALE_ORDER_LINE_NO_DFF","dataType":"double"},{"name":"SERVICE_REQUEST_DFF","dataType":"string"},{"name":"ASSEMBLY_SN_DFF","dataType":"string"},{"name":"CREATED_BY_LOGIN","dataType":"string"},{"name":"LAST_UPDATED_BY_LOGIN","dataType":"string"},{"name":"COMPLETION_LOCATOR","dataType":"string"},{"name":"LOCAL_EXTRACT_DATE","dataType":"dateTime"},{"name":"EXTRACT_DATE","dataType":"dateTime"},{"name":"DATA_UPDATE_DESC","dataType":"string"},{"name":"ITEM_NUMBER","dataType":"string"},{"name":"ITEM_DESCRIPTION","dataType":"string"},{"name":"ITEM_TYPE","dataType":"string"},{"name":"ITEM_ORG_KEY_ID","dataType":"string"},{"name":"ITEM_ORG_KEY_CODE","dataType":"string"},{"name":"PRODUCT_FAMILY","dataType":"string"},{"name":"FORECAST_FIELD","dataType":"string"},{"name":"PRODUCT_LINE","dataType":"string"},{"name":"TBU","dataType":"string"},{"name":"ORG_PRODUCT_FAMILY","dataType":"string"},{"name":"ORG_FORECAST_FIELD","dataType":"string"},{"name":"ORG_PRODUCT_LINE","dataType":"string"},{"name":"ORG_TBU","dataType":"string"}],"partitions":[{"name":"IncrementalRefreshPolicyPartition-2017","refreshTime":"2022-07-08T11:25:20.0166962+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/3cb7dd71-d64b-4b66-9046-a4b1c00b1736/XXREP_WIP_DISCRETE_JOBS_V/part-2017.csv?snapshot=2022-07-08T11%3A25%3A19.9190825Z","pbi:refreshBookmark":"1/24/2022 5:42:34 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2017-01-01T00:00:00","end":"2018-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2018","refreshTime":"2022-07-08T11:25:28.1573568+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/3cb7dd71-d64b-4b66-9046-a4b1c00b1736/XXREP_WIP_DISCRETE_JOBS_V/part-2018.csv?snapshot=2022-07-08T11%3A25%3A28.0714206Z","pbi:refreshBookmark":"6/30/2022 7:37:22 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2018-01-01T00:00:00","end":"2019-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2019","refreshTime":"2022-07-08T11:25:21.9542072+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/3cb7dd71-d64b-4b66-9046-a4b1c00b1736/XXREP_WIP_DISCRETE_JOBS_V/part-2019.csv?snapshot=2022-07-08T11%3A25%3A21.8229941Z","pbi:refreshBookmark":"1/24/2022 8:22:02 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2019-01-01T00:00:00","end":"2020-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2020","refreshTime":"2022-07-08T11:25:10.5362967+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/3cb7dd71-d64b-4b66-9046-a4b1c00b1736/XXREP_WIP_DISCRETE_JOBS_V/part-2020.csv?snapshot=2022-07-08T11%3A25%3A10.2326216Z","pbi:refreshBookmark":"7/8/2022 3:18:48 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2020-01-01T00:00:00","end":"2021-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2021Q1","refreshTime":"2022-07-08T11:24:59.7780768+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/3cb7dd71-d64b-4b66-9046-a4b1c00b1736/XXREP_WIP_DISCRETE_JOBS_V/part-2021Q1.csv?snapshot=2022-07-08T11%3A24%3A59.5377372Z","pbi:refreshBookmark":"6/30/2022 7:37:22 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2021-01-01T00:00:00","end":"2021-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2021Q2","refreshTime":"2022-07-08T11:24:45.9740905+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/3cb7dd71-d64b-4b66-9046-a4b1c00b1736/XXREP_WIP_DISCRETE_JOBS_V/part-2021Q2.csv?snapshot=2022-07-08T11%3A24%3A45.7895988Z","pbi:refreshBookmark":"7/8/2022 3:05:32 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2021-04-01T00:00:00","end":"2021-07-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2021Q3","refreshTime":"2022-07-08T11:25:15.7354177+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/3cb7dd71-d64b-4b66-9046-a4b1c00b1736/XXREP_WIP_DISCRETE_JOBS_V/part-2021Q3.csv?snapshot=2022-07-08T11%3A25%3A15.6005520Z","pbi:refreshBookmark":"7/8/2022 3:19:31 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2021-07-01T00:00:00","end":"2021-10-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2021Q4","refreshTime":"2022-07-10T05:15:49.1496835+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/3cb7dd71-d64b-4b66-9046-a4b1c00b1736/XXREP_WIP_DISCRETE_JOBS_V/part-2021Q4.csv?snapshot=2022-07-10T05%3A15%3A43.0164864Z","pbi:refreshBookmark":"7/8/2022 5:31:13 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2021-10-01T00:00:00","end":"2022-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q1","refreshTime":"2022-07-10T05:16:49.2690841+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/3cb7dd71-d64b-4b66-9046-a4b1c00b1736/XXREP_WIP_DISCRETE_JOBS_V/part-2022Q1.csv?snapshot=2022-07-10T05%3A16%3A36.0751835Z","pbi:refreshBookmark":"7/8/2022 5:09:59 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-01-01T00:00:00","end":"2022-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q2","refreshTime":"2022-07-10T05:14:53.321173+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/3cb7dd71-d64b-4b66-9046-a4b1c00b1736/XXREP_WIP_DISCRETE_JOBS_V/part-2022Q2.csv?snapshot=2022-07-10T05%3A14%3A39.7256584Z","pbi:refreshBookmark":"7/8/2022 4:24:19 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-01T00:00:00","end":"2022-07-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q3","refreshTime":"2022-07-10T05:15:18.3230728+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/3cb7dd71-d64b-4b66-9046-a4b1c00b1736/XXREP_WIP_DISCRETE_JOBS_V/part-2022Q3.csv?snapshot=2022-07-10T05%3A14%3A31.0995897Z","pbi:refreshBookmark":"7/8/2022 4:21:41 PM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-07-01T00:00:00","end":"2022-10-01T00:00:00"}}]},{"$type":"LocalEntity","name":"XXREP_MTL_MATERIAL_TRANSACTIONS","description":"","pbi:refreshPolicy":{"$type":"IncrementalRefreshPolicy","locationPattern":"XXREP_MTL_MATERIAL_TRANSACTIONS/part.csv","rollingWindowGranularity":"year","rollingWindowPeriods":5,"incrementalGranularity":"quarter","incrementalPeriods":6,"pollingQuery":"XXREP_MTL_MATERIAL_TRANSACTIONS_Canary"},"annotations":[{"name":"pbi:IncrementalRefreshDetectChangeAttribute","value":"LAST_UPDATE_DATE"},{"name":"pbi:IncrementalRefreshFilterByAttribute","value":"TRANSACTION_DATE"}],"attributes":[{"name":"TRANSACTION_ID","dataType":"int64"},{"name":"LAST_UPDATE_DATE","dataType":"dateTime"},{"name":"LAST_UPDATED_BY","dataType":"double"},{"name":"CREATION_DATE","dataType":"dateTime"},{"name":"CREATED_BY","dataType":"double"},{"name":"LAST_UPDATE_LOGIN","dataType":"double"},{"name":"REQUEST_ID","dataType":"int64"},{"name":"PROGRAM_APPLICATION_ID","dataType":"double"},{"name":"PROGRAM_ID","dataType":"int64"},{"name":"PROGRAM_UPDATE_DATE","dataType":"dateTime"},{"name":"INVENTORY_ITEM_ID","dataType":"int64"},{"name":"REVISION","dataType":"string"},{"name":"ORGANIZATION_ID","dataType":"int64"},{"name":"SUBINVENTORY_CODE","dataType":"string"},{"name":"LOCATOR_ID","dataType":"double"},{"name":"TRANSACTION_TYPE_ID","dataType":"int64"},{"name":"TRANSACTION_ACTION_ID","dataType":"int64"},{"name":"TRANSACTION_SOURCE_TYPE_ID","dataType":"int64"},{"name":"TRANSACTION_SOURCE_ID","dataType":"int64"},{"name":"TRANSACTION_SOURCE_NAME","dataType":"string"},{"name":"TRANSACTION_QUANTITY","dataType":"double"},{"name":"TRANSACTION_UOM","dataType":"string"},{"name":"PRIMARY_QUANTITY","dataType":"double"},{"name":"TRANSACTION_DATE","dataType":"dateTime"},{"name":"VARIANCE_AMOUNT","dataType":"double"},{"name":"ACCT_PERIOD_ID","dataType":"int64"},{"name":"TRANSACTION_REFERENCE","dataType":"string"},{"name":"REASON_ID","dataType":"double"},{"name":"DISTRIBUTION_ACCOUNT_ID","dataType":"double"},{"name":"ENCUMBRANCE_ACCOUNT","dataType":"double"},{"name":"ENCUMBRANCE_AMOUNT","dataType":"double"},{"name":"COST_UPDATE_ID","dataType":"double"},{"name":"COSTED_FLAG","dataType":"string"},{"name":"TRANSACTION_GROUP_ID","dataType":"double"},{"name":"INVOICED_FLAG","dataType":"string"},{"name":"ACTUAL_COST","dataType":"double"},{"name":"TRANSACTION_COST","dataType":"double"},{"name":"PRIOR_COST","dataType":"double"},{"name":"NEW_COST","dataType":"double"},{"name":"CURRENCY_CODE","dataType":"string"},{"name":"CURRENCY_CONVERSION_RATE","dataType":"double"},{"name":"CURRENCY_CONVERSION_TYPE","dataType":"string"},{"name":"CURRENCY_CONVERSION_DATE","dataType":"dateTime"},{"name":"USSGL_TRANSACTION_CODE","dataType":"string"},{"name":"QUANTITY_ADJUSTED","dataType":"double"},{"name":"EMPLOYEE_CODE","dataType":"string"},{"name":"DEPARTMENT_ID","dataType":"double"},{"name":"OPERATION_SEQ_NUM","dataType":"double"},{"name":"MASTER_SCHEDULE_UPDATE_CODE","dataType":"string"},{"name":"RECEIVING_DOCUMENT","dataType":"string"},{"name":"PICKING_LINE_ID","dataType":"double"},{"name":"TRX_SOURCE_LINE_ID","dataType":"double"},{"name":"TRX_SOURCE_DELIVERY_ID","dataType":"double"},{"name":"REPETITIVE_LINE_ID","dataType":"double"},{"name":"PHYSICAL_ADJUSTMENT_ID","dataType":"double"},{"name":"CYCLE_COUNT_ID","dataType":"double"},{"name":"RMA_LINE_ID","dataType":"double"},{"name":"TRANSFER_TRANSACTION_ID","dataType":"double"},{"name":"TRANSACTION_SET_ID","dataType":"double"},{"name":"RCV_TRANSACTION_ID","dataType":"double"},{"name":"MOVE_TRANSACTION_ID","dataType":"double"},{"name":"COMPLETION_TRANSACTION_ID","dataType":"double"},{"name":"SHORTAGE_PROCESS_CODE","dataType":"double"},{"name":"SOURCE_CODE","dataType":"string"},{"name":"SOURCE_LINE_ID","dataType":"double"},{"name":"VENDOR_LOT_NUMBER","dataType":"string"},{"name":"TRANSFER_ORGANIZATION_ID","dataType":"double"},{"name":"TRANSFER_SUBINVENTORY","dataType":"string"},{"name":"TRANSFER_LOCATOR_ID","dataType":"double"},{"name":"SHIPMENT_NUMBER","dataType":"string"},{"name":"TRANSFER_COST","dataType":"double"},{"name":"TRANSPORTATION_DIST_ACCOUNT","dataType":"double"},{"name":"TRANSPORTATION_COST","dataType":"double"},{"name":"TRANSFER_COST_DIST_ACCOUNT","dataType":"double"},{"name":"WAYBILL_AIRBILL","dataType":"string"},{"name":"FREIGHT_CODE","dataType":"string"},{"name":"NUMBER_OF_CONTAINERS","dataType":"double"},{"name":"VALUE_CHANGE","dataType":"double"},{"name":"PERCENTAGE_CHANGE","dataType":"double"},{"name":"MOVEMENT_ID","dataType":"double"},{"name":"TASK_ID","dataType":"double"},{"name":"TO_TASK_ID","dataType":"double"},{"name":"PROJECT_ID","dataType":"double"},{"name":"TO_PROJECT_ID","dataType":"double"},{"name":"SOURCE_PROJECT_ID","dataType":"double"},{"name":"PA_EXPENDITURE_ORG_ID","dataType":"double"},{"name":"SOURCE_TASK_ID","dataType":"double"},{"name":"EXPENDITURE_TYPE","dataType":"string"},{"name":"ERROR_CODE","dataType":"string"},{"name":"ERROR_EXPLANATION","dataType":"string"},{"name":"PRIOR_COSTED_QUANTITY","dataType":"double"},{"name":"TRANSFER_PRIOR_COSTED_QUANTITY","dataType":"double"},{"name":"FINAL_COMPLETION_FLAG","dataType":"string"},{"name":"PM_COST_COLLECTED","dataType":"string"},{"name":"PM_COST_COLLECTOR_GROUP_ID","dataType":"double"},{"name":"SHIPMENT_COSTED","dataType":"string"},{"name":"TRANSFER_PERCENTAGE","dataType":"double"},{"name":"MATERIAL_ACCOUNT","dataType":"double"},{"name":"MATERIAL_OVERHEAD_ACCOUNT","dataType":"double"},{"name":"RESOURCE_ACCOUNT","dataType":"double"},{"name":"OUTSIDE_PROCESSING_ACCOUNT","dataType":"double"},{"name":"OVERHEAD_ACCOUNT","dataType":"double"},{"name":"COST_GROUP_ID","dataType":"double"},{"name":"TRANSFER_COST_GROUP_ID","dataType":"double"},{"name":"FLOW_SCHEDULE","dataType":"string"},{"name":"QA_COLLECTION_ID","dataType":"double"},{"name":"OVERCOMPLETION_TRANSACTION_QTY","dataType":"double"},{"name":"OVERCOMPLETION_PRIMARY_QTY","dataType":"double"},{"name":"OVERCOMPLETION_TRANSACTION_ID","dataType":"double"},{"name":"MVT_STAT_STATUS","dataType":"string"},{"name":"COMMON_BOM_SEQ_ID","dataType":"double"},{"name":"COMMON_ROUTING_SEQ_ID","dataType":"double"},{"name":"ORG_COST_GROUP_ID","dataType":"double"},{"name":"COST_TYPE_ID","dataType":"double"},{"name":"PERIODIC_PRIMARY_QUANTITY","dataType":"double"},{"name":"MOVE_ORDER_LINE_ID","dataType":"double"},{"name":"TASK_GROUP_ID","dataType":"double"},{"name":"PICK_SLIP_NUMBER","dataType":"double"},{"name":"LPN_ID","dataType":"double"},{"name":"TRANSFER_LPN_ID","dataType":"double"},{"name":"PICK_STRATEGY_ID","dataType":"double"},{"name":"PICK_RULE_ID","dataType":"double"},{"name":"PUT_AWAY_STRATEGY_ID","dataType":"double"},{"name":"PUT_AWAY_RULE_ID","dataType":"double"},{"name":"CONTENT_LPN_ID","dataType":"double"},{"name":"PICK_SLIP_DATE","dataType":"dateTime"},{"name":"COST_CATEGORY_ID","dataType":"double"},{"name":"ORGANIZATION_TYPE","dataType":"double"},{"name":"TRANSFER_ORGANIZATION_TYPE","dataType":"double"},{"name":"OWNING_ORGANIZATION_ID","dataType":"double"},{"name":"OWNING_TP_TYPE","dataType":"double"},{"name":"XFR_OWNING_ORGANIZATION_ID","dataType":"double"},{"name":"TRANSFER_OWNING_TP_TYPE","dataType":"double"},{"name":"PLANNING_ORGANIZATION_ID","dataType":"double"},{"name":"PLANNING_TP_TYPE","dataType":"double"},{"name":"XFR_PLANNING_ORGANIZATION_ID","dataType":"double"},{"name":"TRANSFER_PLANNING_TP_TYPE","dataType":"double"},{"name":"SECONDARY_UOM_CODE","dataType":"string"},{"name":"SECONDARY_TRANSACTION_QUANTITY","dataType":"double"},{"name":"TRANSACTION_GROUP_SEQ","dataType":"double"},{"name":"SHIP_TO_LOCATION_ID","dataType":"double"},{"name":"RESERVATION_ID","dataType":"double"},{"name":"TRANSACTION_MODE","dataType":"double"},{"name":"TRANSACTION_BATCH_ID","dataType":"double"},{"name":"TRANSACTION_BATCH_SEQ","dataType":"double"},{"name":"INTRANSIT_ACCOUNT","dataType":"double"},{"name":"FOB_POINT","dataType":"double"},{"name":"PARENT_TRANSACTION_ID","dataType":"double"},{"name":"LOGICAL_TRX_TYPE_CODE","dataType":"double"},{"name":"TRX_FLOW_HEADER_ID","dataType":"double"},{"name":"LOGICAL_TRANSACTIONS_CREATED","dataType":"double"},{"name":"LOGICAL_TRANSACTION","dataType":"double"},{"name":"INTERCOMPANY_COST","dataType":"double"},{"name":"INTERCOMPANY_PRICING_OPTION","dataType":"double"},{"name":"INTERCOMPANY_CURRENCY_CODE","dataType":"string"},{"name":"ORIGINAL_TRANSACTION_TEMP_ID","dataType":"double"},{"name":"TRANSFER_PRICE","dataType":"double"},{"name":"EXPENSE_ACCOUNT_ID","dataType":"double"},{"name":"COGS_RECOGNITION_PERCENT","dataType":"double"},{"name":"SO_ISSUE_ACCOUNT_TYPE","dataType":"double"},{"name":"OPM_COSTED_FLAG","dataType":"string"},{"name":"MATERIAL_EXPENSE_ACCOUNT","dataType":"double"},{"name":"TRANSACTION_EXTRACTED","dataType":"string"},{"name":"XML_DOCUMENT_ID","dataType":"double"},{"name":"ITEM_ORG_KEY_ID","dataType":"string"}],"partitions":[{"name":"IncrementalRefreshPolicyPartition-2017","refreshTime":"2022-07-08T11:38:27.7494826+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/3cb7dd71-d64b-4b66-9046-a4b1c00b1736/XXREP_MTL_MATERIAL_TRANSACTIONS/part-2017.csv?snapshot=2022-07-08T11%3A38%3A27.6342489Z","pbi:refreshBookmark":"12/29/2017 3:29:28 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2017-01-01T00:00:00","end":"2018-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2018","refreshTime":"2022-07-08T11:37:27.4089899+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/3cb7dd71-d64b-4b66-9046-a4b1c00b1736/XXREP_MTL_MATERIAL_TRANSACTIONS/part-2018.csv?snapshot=2022-07-08T11%3A37%3A27.2907429Z","pbi:refreshBookmark":"12/28/2018 4:13:08 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2018-01-01T00:00:00","end":"2019-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2019","refreshTime":"2022-07-08T11:33:15.9845633+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/3cb7dd71-d64b-4b66-9046-a4b1c00b1736/XXREP_MTL_MATERIAL_TRANSACTIONS/part-2019.csv?snapshot=2022-07-08T11%3A33%3A15.8724071Z","pbi:refreshBookmark":"12/27/2019 6:43:37 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2019-01-01T00:00:00","end":"2020-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2020","refreshTime":"2022-07-08T11:32:29.6169218+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/3cb7dd71-d64b-4b66-9046-a4b1c00b1736/XXREP_MTL_MATERIAL_TRANSACTIONS/part-2020.csv?snapshot=2022-07-08T11%3A32%3A29.2480316Z","pbi:refreshBookmark":"12/30/2020 7:52:54 PM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2020-01-01T00:00:00","end":"2021-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2021Q1","refreshTime":"2022-07-08T11:26:35.6958487+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/3cb7dd71-d64b-4b66-9046-a4b1c00b1736/XXREP_MTL_MATERIAL_TRANSACTIONS/part-2021Q1.csv?snapshot=2022-07-08T11%3A26%3A35.6537822Z","pbi:refreshBookmark":"4/1/2021 8:13:54 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2021-01-01T00:00:00","end":"2021-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2021Q2","refreshTime":"2022-07-08T11:27:10.6031968+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/3cb7dd71-d64b-4b66-9046-a4b1c00b1736/XXREP_MTL_MATERIAL_TRANSACTIONS/part-2021Q2.csv?snapshot=2022-07-08T11%3A27%3A10.3389495Z","pbi:refreshBookmark":"6/30/2021 11:58:41 PM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2021-04-01T00:00:00","end":"2021-07-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2021Q3","refreshTime":"2022-07-08T11:27:27.3954558+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/3cb7dd71-d64b-4b66-9046-a4b1c00b1736/XXREP_MTL_MATERIAL_TRANSACTIONS/part-2021Q3.csv?snapshot=2022-07-08T11%3A27%3A27.2552759Z","pbi:refreshBookmark":"9/30/2021 10:21:36 PM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2021-07-01T00:00:00","end":"2021-10-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2021Q4","refreshTime":"2022-07-08T11:27:02.5229316+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/3cb7dd71-d64b-4b66-9046-a4b1c00b1736/XXREP_MTL_MATERIAL_TRANSACTIONS/part-2021Q4.csv?snapshot=2022-07-08T11%3A27%3A02.4294721Z","pbi:refreshBookmark":"12/30/2021 8:47:03 PM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2021-10-01T00:00:00","end":"2022-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q1","refreshTime":"2022-07-08T11:27:04.0385549+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/3cb7dd71-d64b-4b66-9046-a4b1c00b1736/XXREP_MTL_MATERIAL_TRANSACTIONS/part-2022Q1.csv?snapshot=2022-07-08T11%3A27%3A03.8236746Z","pbi:refreshBookmark":"4/1/2022 2:22:44 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-01-01T00:00:00","end":"2022-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q2","refreshTime":"2022-07-08T11:26:43.528659+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/3cb7dd71-d64b-4b66-9046-a4b1c00b1736/XXREP_MTL_MATERIAL_TRANSACTIONS/part-2022Q2.csv?snapshot=2022-07-08T11%3A26%3A43.4043511Z","pbi:refreshBookmark":"6/30/2022 6:53:34 AM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-01T00:00:00","end":"2022-07-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q3","refreshTime":"2022-07-10T05:18:41.1808682+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/3cb7dd71-d64b-4b66-9046-a4b1c00b1736/XXREP_MTL_MATERIAL_TRANSACTIONS/part-2022Q3.csv?snapshot=2022-07-10T05%3A18%3A41.0859199Z","pbi:refreshBookmark":"7/9/2022 9:53:14 PM","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-07-01T00:00:00","end":"2022-10-01T00:00:00"}}]}]}