{"name":"Flow_Agile-BOMs","description":"Agile BOMs assemblies.","version":"1.0","culture":"en-US","modifiedTime":"2022-02-03T22:13:07.9922181+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"Agile_BOMs":{"queryId":"640d4913-5f41-4922-ab2c-54876667d2e3","queryName":"Agile_BOMs","loadEnabled":true},"Sample file":{"queryId":"c3598c8a-13f5-44c0-9d4c-5ddab2969552","queryName":"Sample file","queryGroupId":"2c7a01d5-28df-47f6-a027-c1e25421c144"},"Parameter":{"queryId":"2089d200-afab-45fc-b8d2-6c9ccd62ed95","queryName":"Parameter","queryGroupId":"2c7a01d5-28df-47f6-a027-c1e25421c144"},"Transform Sample file":{"queryId":"c7ac29a8-9202-4972-9490-d67d6b1497e4","queryName":"Transform Sample file","queryGroupId":"6cdcbf83-6fc0-48f1-b8b5-26ec8e487ebd"},"Transform file":{"queryId":"e7f4b59e-2c7d-4d4b-8f26-6d7a2c4d97c7","queryName":"Transform file","queryGroupId":"2c7a01d5-28df-47f6-a027-c1e25421c144"}},"document":"section Section1;\r\nshared Agile_BOMs = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/sites/GEPMEPowerBIReports/\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Folder Path] = \"https://cohrinc.sharepoint.com/sites/GEPMEPowerBIReports/Shared Documents/Agile_BOMs/\"),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows\", each [Attributes]?[Hidden]? <> true),\r\n  #\"Invoke custom function\" = Table.AddColumn(#\"Filtered hidden files\", \"Transform file\", each #\"Transform file\"([Content])),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Invoke custom function\", {{\"Name\", \"Source.Name\"}}),\r\n  #\"Removed other columns\" = Table.SelectColumns(#\"Renamed columns\", {\"Source.Name\", \"Transform file\"}),\r\n  #\"Expanded table column\" = Table.ExpandTableColumn(#\"Removed other columns\", \"Transform file\", Table.ColumnNames(#\"Transform file\"(#\"Sample file\"))),\r\n  #\"Choose columns\" = Table.SelectColumns(#\"Expanded table column\", {\"Level\", \"Item Number\", \"Item Description\", \"Qty\", \"UOM\", \"Find Num\", \"Assembly Item Number\", \"Assembly Description\"}),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Choose columns\", {{\"Level\", type text}, {\"Item Number\", type text}, {\"Item Description\", type text}, {\"UOM\", type text}, {\"Find Num\", type text}, {\"Assembly Item Number\", type text}, {\"Assembly Description\", type text}, {\"Qty\", type number}})\r\nin\r\n  #\"Changed column type\";\r\nshared #\"Sample file\" = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/sites/GEPMEPowerBIReports/\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Folder Path] = \"https://cohrinc.sharepoint.com/sites/GEPMEPowerBIReports/Shared Documents/Agile_BOMs/\"),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows\", each [Attributes]?[Hidden]? <> true),\r\n  Navigation = #\"Filtered hidden files\"{0}[Content]\r\nin\r\n  Navigation;\r\nshared Parameter = let\r\n  Parameter = #\"Sample file\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type binary, BinaryIdentifier = #\"Sample file\"]\r\nin\r\n  Parameter;\r\nshared #\"Transform Sample file\" = let\r\n  Source = Excel.Workbook(Parameter, null, true),\r\n  Navigation = Source{[Item = \"Sheet0\", Kind = \"Sheet\"]}[Data],\r\n  #\"Promoted headers\" = Table.PromoteHeaders(Navigation, [PromoteAllScalars = true])\r\nin\r\n  #\"Promoted headers\";\r\nshared #\"Transform file\" = let\r\n  Source = (Parameter as binary) => let\r\n  Source = Excel.Workbook(Parameter, null, true),\r\n  Navigation = Source{[Item = \"Sheet0\", Kind = \"Sheet\"]}[Data],\r\n  #\"Promoted headers\" = Table.PromoteHeaders(Navigation, [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"Level\", type text}, {\"Attachments (Image)\", type logical}, {\"Manufacturer (Image)\", type logical}, {\"Pending Changes (Image)\", type logical}, {\"Has Been Redlined (Image)\", type logical}, {\"Item Number\", type text}, {\"Item Description\", type text}, {\"Item Type\", type text}, {\"Rev\", type text}, {\"Lifecycle Phase\", type text}, {\"Qty\", type number}, {\"UOM\", type text}, {\"Find Num\", type text}, {\"Assembly Item Number\", type text}, {\"Assembly Description\", type text}})\r\nin\r\n  #\"Changed column type\"\r\nin\r\n  Source;\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[{\"id\":\"6cdcbf83-6fc0-48f1-b8b5-26ec8e487ebd\",\"name\":\"Transform file from Agile_BOMs\",\"description\":null,\"parentId\":null,\"order\":0},{\"id\":\"2c7a01d5-28df-47f6-a027-c1e25421c144\",\"name\":\"Helper queries\",\"description\":null,\"parentId\":\"6cdcbf83-6fc0-48f1-b8b5-26ec8e487ebd\",\"order\":0}]"}],"entities":[{"$type":"LocalEntity","name":"Agile_BOMs","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Agile_BOMs.csv"},"attributes":[{"name":"Level","dataType":"string"},{"name":"Item Number","dataType":"string"},{"name":"Item Description","dataType":"string"},{"name":"Qty","dataType":"double"},{"name":"UOM","dataType":"string"},{"name":"Find Num","dataType":"string"},{"name":"Assembly Item Number","dataType":"string"},{"name":"Assembly Description","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-04-04T12:57:50.2956296+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/f113177c-7741-47dc-b8e0-eb0ad4bb2a67/Agile_BOMs.csv?snapshot=2022-04-04T12%3A57%3A50.1351993Z"}]}]}