{"name":"Flow_Logistics","description":"Flow for logistics data (recevings, transactions,...)","version":"1.0","culture":"en-US","modifiedTime":"2022-05-18T13:35:02.91161+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":true,"queriesMetadata":{"Logistics_Transactions":{"queryId":"1bbab004-1d63-4871-b091-45f291885715","queryName":"Logistics_Transactions","queryGroupId":"58788a6c-4919-4be7-91e2-6a2f3c282f00"},"Sample file (3)":{"queryId":"dfe891bf-a8a3-4eba-af9c-dce661704aa0","queryName":"Sample file (3)","queryGroupId":"9571a417-5b12-49a6-a3c1-1a841842e20c"},"Parameter (3)":{"queryId":"a18bd2f1-5eaf-4158-bdf4-70a4b3680260","queryName":"Parameter (3)","queryGroupId":"9571a417-5b12-49a6-a3c1-1a841842e20c"},"Transform Sample file (3)":{"queryId":"cda93049-263e-4de5-8498-9cb2c716233d","queryName":"Transform Sample file (3)","queryGroupId":"4a0b9267-db97-43a3-b998-863f27253b89"},"Transform file (3)":{"queryId":"2ac1f71c-b979-436f-aaf8-e7bdd85ca374","queryName":"Transform file (3)","queryGroupId":"9571a417-5b12-49a6-a3c1-1a841842e20c"},"Parameter1":{"queryId":"a0333897-70f3-4184-8ede-d89f4fbdebe7","queryName":"Parameter1","queryGroupId":"639ed2f2-25e6-46c8-b0b3-0deec5e1bacc"},"Sample File":{"queryId":"63288524-d6fe-418e-9d2e-e7cb0e4decb3","queryName":"Sample File","queryGroupId":"639ed2f2-25e6-46c8-b0b3-0deec5e1bacc"},"Transform File":{"queryId":"363df080-6e31-43b6-bf9b-35487b0a6a92","queryName":"Transform File","queryGroupId":"639ed2f2-25e6-46c8-b0b3-0deec5e1bacc"},"Transform Sample File":{"queryId":"ed88e4de-0cb1-4c12-9edc-75bbbcdeac9e","queryName":"Transform Sample File","queryGroupId":"b32a44d1-a823-41c6-88da-4ef2ab09a5a5"},"Logistics_Headers":{"queryId":"20a76f55-f291-4e9d-af0a-3fad063806f9","queryName":"Logistics_Headers","queryGroupId":"58788a6c-4919-4be7-91e2-6a2f3c282f00"},"ReceivingDailyIssues":{"queryId":"690de35f-709b-4ed9-9f5c-b53010ef2584","queryName":"ReceivingDailyIssues","loadEnabled":true},"Sample file (2)":{"queryId":"002daf48-092d-4a18-b23c-1c26f944b48e","queryName":"Sample file (2)","queryGroupId":"fb154f34-ba2c-44d6-9567-5caf0c3d7e62"},"Parameter":{"queryId":"c185a2e9-3198-4f20-ac25-06d73a6e0daf","queryName":"Parameter","queryGroupId":"fb154f34-ba2c-44d6-9567-5caf0c3d7e62"},"Transform Sample file (2)":{"queryId":"dc6c9cfa-95cf-40a2-bd9c-0720795c12c7","queryName":"Transform Sample file (2)","queryGroupId":"98626363-884f-48d8-8556-a3a6ce4a0dc2"},"Transform file (2)":{"queryId":"a2b8ec71-23b3-4fd7-a8b4-9b02b81d05f1","queryName":"Transform file (2)","queryGroupId":"fb154f34-ba2c-44d6-9567-5caf0c3d7e62"},"XXCOH_MS_SHIPMENT_VIEW":{"queryId":"b07a6a7c-8477-4b33-9ee1-366e0bbdbc1d","queryName":"XXCOH_MS_SHIPMENT_VIEW","queryGroupId":"58788a6c-4919-4be7-91e2-6a2f3c282f00"},"XXCOH_MT_MTRX_VIEW":{"queryId":"c390101a-5a1a-4389-a049-aed4c226b038","queryName":"XXCOH_MT_MTRX_VIEW","loadEnabled":true},"XXCOH_MT_MTRX_VIEW (2)":{"queryId":"1a61611e-5acc-4c1e-a663-cab92986b952","queryName":"XXCOH_MT_MTRX_VIEW (2)"},"parStartDate":{"queryId":"575ca739-40b7-4c8e-991b-e3326e968030","queryName":"parStartDate"},"XXCOH_MP_RECEIPTS_VIEW":{"queryId":"020104d4-94fc-48fd-b751-3e64ee2bb61a","queryName":"XXCOH_MP_RECEIPTS_VIEW","loadEnabled":true},"RangeEnd":{"queryId":"45912802-393e-4ac6-8757-e2a42821fc22","queryName":"RangeEnd"},"RangeStart":{"queryId":"0c3a91fa-3784-4dac-9972-e554ef7dbc43","queryName":"RangeStart"}},"document":"section Section1;\r\n\r\nshared Logistics_Transactions = let\r\n    Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n    #\"Filtered rows\" = Table.SelectRows(Source, each Text.Contains([Name], \"transactions\")),\r\n    #\"Invoke custom function\" = Table.AddColumn(#\"Filtered rows\", \"Transform file (3)\", each #\"Transform file (3)\"([Content])),\r\n    #\"Renamed columns\" = Table.RenameColumns(#\"Invoke custom function\", {{\"Name\", \"Source.Name\"}}),\r\n    #\"Removed other columns\" = Table.SelectColumns(#\"Renamed columns\", {\"Source.Name\", \"Transform file (3)\"}),\r\n    #\"Expanded table column\" = Table.ExpandTableColumn(#\"Removed other columns\", \"Transform file (3)\", Table.ColumnNames(#\"Transform file (3)\"(#\"Sample file (3)\"))),\r\n    #\"Changed column type\" = Table.TransformColumnTypes(#\"Expanded table column\", {{\"Source.Name\", type text}, {\"Transaction Type\", type text}, {\"Amount\", type number}, {\"Release\", type number}, {\"Line\", type text}, {\"Shipment\", type number}, {\"Date\", type text}, {\"Comments\", type text}, {\"Item\", type text}, {\"Rev\", type text}, {\"Unit\", type text}, {\"Destination\", type text}, {\"Receipt\", Int64.Type}, {\"Source\", type text}, {\"Order Number\", type text}, {\"Supplier\", type text}, {\"\", type text}}),\r\n    #\"Choose columns\" = Table.SelectColumns(#\"Changed column type\", {\"Transaction Type\", \"Amount\", \"Release\", \"Line\", \"Shipment\", \"Date\", \"Comments\", \"Item\", \"Rev\", \"Unit\", \"Destination\", \"Receipt\", \"Source\", \"Order Number\", \"Supplier\"}),\r\n    #\"Removed duplicates\" = Table.Distinct(#\"Choose columns\", {\"Transaction Type\", \"Amount\", \"Release\", \"Line\", \"Shipment\", \"Date\", \"Comments\", \"Item\", \"Rev\", \"Unit\", \"Destination\", \"Receipt\", \"Source\", \"Order Number\", \"Supplier\"}),\r\n    #\"Changed column type with locale\" = Table.TransformColumnTypes(#\"Removed duplicates\", {{\"Date\", type datetime}}, \"de-DE\"),\r\n    #\"Renamed columns 1\" = Table.RenameColumns(#\"Changed column type with locale\", {{\"Date\", \"DateTime US\"}}),\r\n    #\"Added custom\" = Table.AddColumn(#\"Renamed columns 1\", \"DateTime DE\", each DateTime.AddZone([DateTime US], -9)),\r\n    #\"Changed column type with locale 1\" = Table.TransformColumnTypes(#\"Added custom\", {{\"DateTime DE\", type datetime}}, \"de-DE\"),\r\n    #\"Duplicated column\" = Table.DuplicateColumn(#\"Changed column type with locale 1\", \"DateTime DE\", \"Date\"),\r\n    #\"Changed column type 1\" = Table.TransformColumnTypes(#\"Duplicated column\", {{\"Date\", type date}}),\r\n    #\"Removed columns\" = Table.RemoveColumns(#\"Changed column type 1\", {\"DateTime US\"}),\r\n    #\"Renamed columns 2\" = Table.RenameColumns(#\"Removed columns\", {{\"DateTime DE\", \"Booking DateTime DE\"}, {\"Date\", \"Booking Date\"}})\r\nin\r\n    #\"Renamed columns 2\";\r\n\r\nshared #\"Sample file (3)\" = let\r\n    Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n    #\"Filtered rows\" = Table.SelectRows(Source, each Text.Contains([Name], \"transactions\")),\r\n    Navigation = #\"Filtered rows\"{0}[Content]\r\nin\r\n    Navigation;\r\n\r\nshared #\"Parameter (3)\" = let\r\n    #\"Parameter (3)\" = #\"Sample file (3)\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type binary]\r\nin\r\n    #\"Parameter (3)\";\r\n\r\nshared #\"Transform Sample file (3)\" = let\r\n    Source = Csv.Document(#\"Parameter (3)\", [Delimiter = \"#(tab)\", Columns = 16, QuoteStyle = QuoteStyle.None]),\r\n    #\"Promoted headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),\r\n    #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"Transaction Type\", type text}, {\"Amount\", type number}, {\"Release\", Int64.Type}, {\"Line\", Int64.Type}, {\"Shipment\", Int64.Type}, {\"Date\", type text}, {\"Comments\", type text}, {\"Item\", type text}, {\"Rev\", type text}, {\"Unit\", type text}, {\"Destination\", type text}, {\"Receipt\", Int64.Type}, {\"Source\", type text}, {\"Order Number\", Int64.Type}, {\"Supplier\", type text}, {\"\", type text}})\r\nin\r\n    #\"Changed column type\";\r\n\r\nshared #\"Transform file (3)\" = let\r\n    Source = (#\"Parameter (3)\" as binary) => let\r\n    Source = Csv.Document(#\"Parameter (3)\", [Delimiter = \"#(tab)\", Columns = 16, QuoteStyle = QuoteStyle.None]),\r\n    #\"Promoted headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),\r\n    #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"Transaction Type\", type text}, {\"Amount\", type number}, {\"Release\", Int64.Type}, {\"Line\", Int64.Type}, {\"Shipment\", Int64.Type}, {\"Date\", type text}, {\"Comments\", type text}, {\"Item\", type text}, {\"Rev\", type text}, {\"Unit\", type text}, {\"Destination\", type text}, {\"Receipt\", Int64.Type}, {\"Source\", type text}, {\"Order Number\", Int64.Type}, {\"Supplier\", type text}, {\"\", type text}})\r\nin\r\n    #\"Changed column type\"\r\nin\r\n    Source;\r\n\r\nshared Parameter1 = let\r\n    Parameter1 = #\"Sample File\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type binary, BinaryIdentifier = #\"Sample File\"]\r\nin\r\n    Parameter1;\r\n\r\nshared #\"Sample File\" = let\r\n    Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n    #\"Filtered Rows\" = Table.SelectRows(Source, each Text.Contains([Name], \"Daily Receiving Problem Shelf - ab 2021\")),\r\n    Navigation1 = #\"Filtered Rows\"{0}[Content]\r\nin\r\n    Navigation1;\r\n\r\nshared #\"Transform File\" = let\r\n    Source = (Parameter1) => let\r\n    Source = Excel.Workbook(Parameter1, null, true),\r\n    tblReceivingIssues_Table = Source{[Item=\"tblReceivingIssues\",Kind=\"Table\"]}[Data]\r\nin\r\n    tblReceivingIssues_Table\r\nin\r\n    Source;\r\n\r\nshared #\"Transform Sample File\" = let\r\n    Source = Excel.Workbook(Parameter1, null, true),\r\n    tblReceivingIssues_Table = Source{[Item = \"tblReceivingIssues\", Kind = \"Table\"]}[Data],\r\n    #\"Replaced errors\" = Table.ReplaceErrorValues(tblReceivingIssues_Table, {{\"Std. Lieferant\", \"N.A.\"}}),\r\n    #\"Replaced errors 1\" = Table.ReplaceErrorValues(#\"Replaced errors\", {{\"Planner/Buyer\", \"N.A.\"}})\r\nin\r\n    #\"Replaced errors 1\";\r\n\r\nshared Logistics_Headers = let\r\n    Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n    #\"Filtered rows\" = Table.SelectRows(Source, each Text.Contains([Name], \"headers\") and Text.EndsWith([Name], \"tsv\")),\r\n    #\"Invoke custom function\" = Table.AddColumn(#\"Filtered rows\", \"Transform file (2)\", each #\"Transform file (2)\"([Content])),\r\n    #\"Renamed columns\" = Table.RenameColumns(#\"Invoke custom function\", {{\"Name\", \"Source.Name\"}}),\r\n    #\"Removed other columns\" = Table.SelectColumns(#\"Renamed columns\", {\"Source.Name\", \"Transform file (2)\"}),\r\n    #\"Expanded table column\" = Table.ExpandTableColumn(#\"Removed other columns\", \"Transform file (2)\", Table.ColumnNames(#\"Transform file (2)\"(#\"Sample file (2)\"))),\r\n    #\"Changed column type\" = Table.TransformColumnTypes(#\"Expanded table column\", {{\"Source.Name\", type text}, {\"Date\", type text}, {\"Receipt\", Int64.Type}, {\"Supplier\", type text}, {\"Shipment Number\", type text}, {\"Comments\", type text}, {\"Receiver\", type text}, {\"\", type text}}),\r\n    #\"Choose columns\" = Table.SelectColumns(#\"Changed column type\", {\"Date\", \"Receipt\", \"Supplier\", \"Shipment Number\", \"Comments\", \"Receiver\"}),\r\n    #\"Renamed columns 1\" = Table.RenameColumns(#\"Choose columns\", {{\"Date\", \"DateTime US\"}}),\r\n    #\"Changed column type with locale\" = Table.TransformColumnTypes(#\"Renamed columns 1\", {{\"DateTime US\", type datetime}}, \"de-DE\"),\r\n    #\"Added custom\" = Table.AddColumn(#\"Changed column type with locale\", \"DateTime DE\", each DateTime.AddZone([DateTime US], -9)),\r\n    #\"Changed column type with locale 1\" = Table.TransformColumnTypes(#\"Added custom\", {{\"DateTime DE\", type datetime}}, \"de-DE\"),\r\n    #\"Duplicated column\" = Table.DuplicateColumn(#\"Changed column type with locale 1\", \"DateTime DE\", \"Date\"),\r\n    #\"Changed column type 1\" = Table.TransformColumnTypes(#\"Duplicated column\", {{\"Date\", type date}}),\r\n    #\"Removed columns\" = Table.RemoveColumns(#\"Changed column type 1\", {\"DateTime US\"}),\r\n    #\"Split column by positions\" = Table.SplitColumn(#\"Removed columns\", \"Comments\", Splitter.SplitTextByPositions({0, 8, 12}), {\"Docking Date\", \"Docking Time\", \"Docking Fab\"}),\r\n    #\"Changed column type 2\" = Table.TransformColumnTypes(#\"Split column by positions\", {{\"Docking Date\", type date}, {\"Docking Time\", type time}, {\"Docking Fab\", type text}}),\r\n    #\"Merged columns\" = Table.CombineColumns(Table.TransformColumnTypes(#\"Changed column type 2\", {{\"Docking Date\", type text}, {\"Docking Time\", type text}}), {\"Docking Date\", \"Docking Time\"}, Combiner.CombineTextByDelimiter(\" \", QuoteStyle.None), \"Docking DateTime\"),\r\n    #\"Replaced errors\" = Table.ReplaceErrorValues(#\"Merged columns\", {{\"Docking DateTime\", \"1/2/1999 12:00\"}}),\r\n    #\"Changed column type 3\" = Table.TransformColumnTypes(#\"Replaced errors\", {{\"Docking DateTime\", type datetime}}),\r\n    #\"Removed duplicates\" = Table.Distinct(#\"Changed column type 3\", {\"Receipt\", \"Supplier\", \"Shipment Number\", \"Docking DateTime\", \"Docking Fab\", \"Receiver\", \"DateTime DE\", \"Date\"}),\r\n    #\"Extracted first characters\" = Table.TransformColumns(#\"Removed duplicates\", {{\"Docking Fab\", each Text.Start(_, 2), type text}})\r\nin\r\n    #\"Extracted first characters\";\r\n\r\nshared ReceivingDailyIssues = let\r\n    Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n    #\"Filtered Rows\" = Table.SelectRows(Source, each Text.Contains([Name], \"Daily Receiving Problem Shelf - ab 2021\")),\r\n    #\"Invoke Custom Function1\" = Table.AddColumn(#\"Filtered Rows\", \"Transform File\", each #\"Transform File\"([Content])),\r\n    #\"Renamed Columns1\" = Table.RenameColumns(#\"Invoke Custom Function1\", {\"Name\", \"Source.Name\"}),\r\n    #\"Removed Other Columns1\" = Table.SelectColumns(#\"Renamed Columns1\", {\"Source.Name\", \"Transform File\"}),\r\n    #\"Expanded Table Column1\" = Table.ExpandTableColumn(#\"Removed Other Columns1\", \"Transform File\", Table.ColumnNames(#\"Transform File\"(#\"Sample File\"))),\r\n    #\"Changed Type\" = Table.TransformColumnTypes(#\"Expanded Table Column1\", {{\"Source.Name\", type text}, {\"PO\", type text}, {\"Fehler\", type text}, {\"Lieferant\", type text}, {\"Artikelnr.\", type text}, {\"Menge\", Int64.Type}, {\"Einheit\", type text}, {\"Std. Lieferant\", type text}, {\"Planner/Buyer\", type text}, {\"Bearbeiter\", type text}, {\"Eingetragen am\", type date}, {\"Date Resolved\", type date}, {\"Duration (days)\", Int64.Type}, {\"Comment/Feedback\", type text}, {\"Status\", type text}}),\r\n    #\"Removed Other Columns\" = Table.SelectColumns(#\"Changed Type\", {\"PO\", \"Fehler\", \"Lieferant\", \"Artikelnr.\", \"Menge\", \"Einheit\", \"Std. Lieferant\", \"Planner/Buyer\", \"Bearbeiter\", \"Eingetragen am\", \"Date Resolved\", \"Duration (days)\", \"Comment/Feedback\", \"Status\"}),\r\n    #\"Replaced errors\" = Table.ReplaceErrorValues(#\"Removed Other Columns\", {{\"Std. Lieferant\", \"n.a.\"}}),\r\n    #\"Replaced errors 1\" = Table.ReplaceErrorValues(#\"Replaced errors\", {{\"Planner/Buyer\", \"n.a.\"}}),\r\n    #\"Replaced value\" = Table.ReplaceValue(#\"Replaced errors 1\", null, 0, Replacer.ReplaceValue, {\"Menge\"}),\r\n    #\"Replaced errors 2\" = Table.ReplaceErrorValues(#\"Replaced value\", {{\"Menge\", 0}})\r\nin\r\n    #\"Replaced errors 2\";\r\n\r\nshared #\"Sample file (2)\" = let\r\n    Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/teams/Operations/Excimer-G%C3%B6ttingen/Manuf.%20Engineering\", [ApiVersion = 15]),\r\n    #\"Filtered rows\" = Table.SelectRows(Source, each Text.Contains([Name], \"headers\") and Text.EndsWith([Name], \"tsv\")),\r\n    Navigation = #\"Filtered rows\"{0}[Content]\r\nin\r\n    Navigation;\r\n\r\nshared Parameter = let\r\n    Parameter = #\"Sample file (2)\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type binary]\r\nin\r\n    Parameter;\r\n\r\nshared #\"Transform Sample file (2)\" = let\r\n    Source = Csv.Document(Parameter, [Delimiter = \"#(tab)\", Columns = 7, QuoteStyle = QuoteStyle.None]),\r\n    #\"Promoted headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),\r\n    #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"Date\", type text}, {\"Receipt\", type number}, {\"Supplier\", type text}, {\"Shipment Number\", type text}, {\"Comments\", type text}, {\"Receiver\", type text}, {\"\", type text}})\r\nin\r\n    #\"Changed column type\";\r\n\r\nshared #\"Transform file (2)\" = let\r\n    Source = (Parameter as binary) => let\r\n    Source = Csv.Document(Parameter, [Delimiter = \"#(tab)\", Columns = 7, QuoteStyle = QuoteStyle.None]),\r\n    #\"Promoted headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),\r\n    #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"Date\", type text}, {\"Receipt\", type number}, {\"Supplier\", type text}, {\"Shipment Number\", type text}, {\"Comments\", type text}, {\"Receiver\", type text}, {\"\", type text}})\r\nin\r\n    #\"Changed column type\"\r\nin\r\n    Source;\r\n\r\nshared XXCOH_MS_SHIPMENT_VIEW = let\r\n    Source = Value.NativeQuery(Snowflake.Databases(\"mma12090.snowflakecomputing.com\",\"COMPUTE_REPORTING\",[Role=\"GLBMFGOPERATIONSROLE\"]){[Name=\"PROD_DB\"]}[Data], \"SELECT *FROM PROD_DB.APPS.XXCOH_MS_SHIPMENT_VIEW WHERE Warehouse='GEP'\", null, [EnableFolding=true]),\r\n    #\"Filtered rows\" = Table.SelectRows(Source, each [BOOKED_DATE] > parStartDate),\r\n    #\"Choose columns\" = Table.SelectColumns(#\"Filtered rows\", {\"ASOF_DATE\", \"ASOF_DATE_DISP\", \"SYSTEM_DATE\", \"ENTER_DATE\", \"BOOKED_DATE\", \"ORDER_NUMBER\", \"ORDER_LINE\", \"ORDER_TYPE\", \"SO_LINE_TYPE\", \"LINE_STATUS\", \"BILLABLE_FLAG\", \"SALES_CHANNEL\", \"ITEM_TYPE_CODE\", \"ACTUAL_SHIPMENT_DATE\", \"REGIONAL_LOCATION\", \"REPORTING_ENTITY\", \"ASP_FLAG\", \"INV_FLAG\", \"LINE_CATEGORY_CODE\", \"LINE_SOURCE_TYPE_CODE\", \"CUSTOMER_PO\", \"CREATED_BY\", \"ITEM_NUMBER\", \"ITEM_DESCRIPTION\", \"PRODUCT_LINE\", \"PRODUCT_FAMILY\", \"TECHNICAL_BUSINESS_UNIT\", \"REV_ENTITY\", \"REVENUE_ACCOUNT\", \"FORECAST_FIELD\", \"COMMODITY\", \"ORG_PRODUCT_LINE\", \"ORG_PRODUCT_FAMILY\", \"ORG_TECHNICAL_BUSINESS_UNIT\", \"ORG_FORECAST_FIELD\", \"LEAD_TIME\", \"PRIMARY_ORG\", \"WAREHOUSE\", \"SHIPPING_METHOD_CODE\", \"TR_UNIT_SELLING_PRICE\", \"TR_ITEM_UNIT_COST\", \"GROSS_MARGIN_PCT\", \"DISCOUNT_PERCENT\", \"TR_DISCOUNT_AMOUNT\", \"PRICE_LIST\", \"UNIT_SELLING_PRICE\", \"ITEM_UNIT_COST\", \"UNIT_LIST_PRICE\", \"DISCOUNT_AMOUNT\", \"APPLICATION_CODE\", \"APPLICATION_CODE_DESC\", \"MARKET_SEGMENT\", \"REQUEST_SHIP_DATE\", \"PROMISE_SHIP_DATE\", \"SCHEDULE_SHIP_DATE\", \"CUSTOMER_NAME\", \"CUSTOMER_ALTERNATE_NAME\", \"CUSTOMER_NUMBER\", \"PARTY_NUMBER\", \"SHIP_TO_NAME\", \"SHIP_TO_COUNTRY\", \"SHIP_TO_CITY\", \"SHIP_TO_STATE\", \"SHIP_TO_POSTAL_CODE\", \"SHIP_TO_COUNTY\", \"SHIP_TO_PROVINCE\", \"SHIP_TO_SITE\", \"END_USER\", \"END_USER_NUMBER\", \"END_USER_CONTACT\", \"END_USER_CITY\", \"END_USER_STATE\", \"END_USER_COUNTY\", \"END_USER_PROVINCE\", \"END_USER_POSTAL_CODE\", \"END_USER_COUNTRY_NAME\", \"MAJOR_GEOGRAPHICAL_AREA\", \"GL_CLASS\", \"CUSTOMER_CLASS\", \"CUSTOMER_CATEGORY\", \"CUSTOMER_TYPE\", \"FREIGHT_TERM\", \"FOB\", \"LEGAL_ENTITY\", \"OPERATING_UNIT\", \"TRANSACTION_CURRENCY\", \"FUNCTIONAL_CURRENCY\", \"TRX_TO_USD_RATE\", \"TRX_TO_FUNC_RATE\", \"COST_TO_FUNC_RATE\", \"COST_TO_USD_RATE\", \"UNIT_SELLING_PRICE_USD\", \"UNIT_LIST_PRICE_USD\", \"ORDER_STATUS\", \"OE_LINE_NUMBER\", \"DELIVERY_NAME\", \"DELIVERY_SHIPPING_STATUS_CODE\", \"DELIVERY_CONFIRM_DATE\", \"SHIP_FROM_LOCATION_CODE\", \"ULTIMATE_SHIP_TO\", \"SHIP_FROM_ORG_CODE\", \"SUBINVENTORY\", \"LOT_NUMBER\", \"SERIAL_NUMBER\", \"TO_SERIAL_NUMBER\", \"LEAST_NUM_OF_SERIAL_NUMBER\", \"CUST_REQUESTED_QUANTITY\", \"CUST_REQUESTED_QUANTITY_UOM\", \"PICKED_QUANTITY\", \"SHIPPED_QUANTITY\", \"CANCELLED_QUANTITY\", \"SHIPPING_QUANTITY\", \"SHIPPING_QUANTITY_UOM\", \"PICK_RELEASE_STATUS_CODE\", \"PICK_RELEASE_STATUS\", \"DATE_REQUESTED\", \"DATE_SCHEDULED\", \"OE_INTERFACED_FLAG\", \"SHIP_METHOD_CODE\", \"FREIGHT_TERMS_CODE\", \"SHIPMENT_PRIORITY_CODE\", \"SHIPPING_INSTRUCTIONS\", \"PACKING_INSTRUCTIONS\", \"CONSIGNEE\", \"WAYBILL\", \"GROSS_WEIGHT\", \"NET_WEIGHT\", \"WEIGHT_UOM_CODE\", \"VOLUME\", \"VOLUME_UOM_CODE\", \"CARRIER_NAME\", \"NO_OF_PIECES\", \"UOM_OF_PIECES\", \"MOVE_ORDER_NUMBER\", \"MOVE_ORDER_LINE_NUMBER\", \"FREIGHT_CHARGE_USD\", \"SHIP_FROM_DATE\", \"SHIP_TO_DATE\", \"END_CUST_USD_RATE\", \"PLANNER_CODE\", \"END_ASSEMBLY_PEGGING\", \"FIRST_SCHEDULE_DATE\", \"CST_CURRENCY_CODE\", \"PROJECT_NUMBER\", \"PROJECT_ID\", \"PROJECT_NAME\", \"IMPORTER_NAME\", \"IMPORTER_NUMBER\", \"IMPORTER_ADDRESS1\", \"IMPORTER_ADDRESS2\", \"IMPORTER_CITY\", \"IMPORTER_STATE\", \"IMPORTER_COUNTY\", \"IMPORTER_POSTAL_CODE\", \"IMPORTER_COUNTRY_NAME\", \"DELIVERY_PACK_DIMENSIONS\", \"DELIVERY_TYPE\", \"MODE_OF_TRANSPORT\", \"ACTUAL_SHIPPED_VS_PROMISED_SHIPPPED\", \"ACTUAL_SHIPPED_VS_REQUESTED_SHIPPED\", \"ROW_CREATION_DATE\"}),\r\n    #\"Inserted merged column\" = Table.AddColumn(#\"Choose columns\", \"OrderNumber_OrderLine\", each Text.Combine({Text.From([ORDER_NUMBER]), [ORDER_LINE]}, \"_\"), type text),\r\n    #\"Added custom\" = Table.TransformColumnTypes(Table.AddColumn(#\"Inserted merged column\", \"ReqToActual-Shipment_Days\", each Duration.Days(DateTime.From([ACTUAL_SHIPMENT_DATE])-[REQUEST_SHIP_DATE])), {{\"ReqToActual-Shipment_Days\", Int64.Type}}),\r\n    #\"Added custom 1\" = Table.TransformColumnTypes(Table.AddColumn(#\"Added custom\", \"PromToActual-Shipment_Days\", each Duration.Days(DateTime.From([ACTUAL_SHIPMENT_DATE])-[PROMISE_SHIP_DATE])), {{\"PromToActual-Shipment_Days\", Int64.Type}}),\r\n    #\"Added custom 2\" = Table.TransformColumnTypes(Table.AddColumn(#\"Added custom 1\", \"SchedToActual-Shipment_Days\", each Duration.Days(DateTime.From([ACTUAL_SHIPMENT_DATE])-[SCHEDULE_SHIP_DATE])), {{\"SchedToActual-Shipment_Days\", Int64.Type}}),\r\n    #\"Inserted conditional column\" = Table.AddColumn(#\"Added custom 2\", \"ReqToActual-Shipm_Status\", each if [#\"ReqToActual-Shipment_Days\"] = null then \"H. Not Shipped\" else if [#\"ReqToActual-Shipment_Days\"] < -9999 then \"I. Not Scheduled\" else if [#\"ReqToActual-Shipment_Days\"] < -3 then \"A. Early\" else if [#\"ReqToActual-Shipment_Days\"] < 1 then \"B. On Time\" else if [#\"ReqToActual-Shipment_Days\"] < 7 then \"C. 1 Week Late\" else if [#\"ReqToActual-Shipment_Days\"] < 14 then \"D. 2 Weeks Late\" else if [#\"ReqToActual-Shipment_Days\"] < 21 then \"E. 3 Weeks Late\" else if [#\"ReqToActual-Shipment_Days\"] < 28 then \"F. 4 Weeks Late\" else if [#\"ReqToActual-Shipment_Days\"] >= 28 then \"G. Over 1 Month\" else \"NoDates\"),\r\n    #\"Inserted conditional column 1\" = Table.AddColumn(#\"Inserted conditional column\", \"PromToActual-Shipm_Status\", each if [#\"PromToActual-Shipment_Days\"] = null then \"H. Not Shipped\" else if [#\"PromToActual-Shipment_Days\"] < -9999 then \"I. Not Scheduled\" else if [#\"PromToActual-Shipment_Days\"] < -3 then \"A. Early\" else if [#\"PromToActual-Shipment_Days\"] < 1 then \"B. On Time\" else if [#\"PromToActual-Shipment_Days\"] < 7 then \"C. 1 Week Late\" else if [#\"PromToActual-Shipment_Days\"] < 14 then \"D. 2 Weeks Late\" else if [#\"PromToActual-Shipment_Days\"] < 21 then \"E. 3 Weeks Late\" else if [#\"PromToActual-Shipment_Days\"] < 28 then \"F. 4 Weeks Late\" else if [#\"PromToActual-Shipment_Days\"] >= 28 then \"G. Over 1 Month\" else \"No Dates\"),\r\n    #\"Inserted conditional column 2\" = Table.AddColumn(#\"Inserted conditional column 1\", \"SchedToActual-Shipm_Status\", each if [#\"SchedToActual-Shipment_Days\"] = null then \"H. Not Shipped\" else if [#\"SchedToActual-Shipment_Days\"] < -9999 then \"I. Not Scheduled\" else if [#\"SchedToActual-Shipment_Days\"] < -3 then \"A. Early\" else if [#\"SchedToActual-Shipment_Days\"] < 1 then \"B. On Time\" else if [#\"SchedToActual-Shipment_Days\"] < 7 then \"C. 1 Week Late\" else if [#\"SchedToActual-Shipment_Days\"] < 14 then \"D. 2 Weeks Late\" else if [#\"SchedToActual-Shipment_Days\"] < 21 then \"E. 3 Weeks Late\" else if [#\"SchedToActual-Shipment_Days\"] < 28 then \"F. 4 Weeks Late\" else if [#\"SchedToActual-Shipment_Days\"] >= 28 then \"G. Over 1 Month\" else \"No Dates\"),\r\n    #\"Changed column type\" = Table.TransformColumnTypes(#\"Inserted conditional column 2\", {{\"ReqToActual-Shipm_Status\", type text}, {\"PromToActual-Shipm_Status\", type text}, {\"SchedToActual-Shipm_Status\", type text}}),\r\n    #\"Added custom 3\" = Table.TransformColumnTypes(Table.AddColumn(#\"Changed column type\", \"Actual_Shipment_DateTime_PST\", each DateTime.AddZone([ACTUAL_SHIPMENT_DATE], -8)), {{\"Actual_Shipment_DateTime_PST\", type datetimezone}}),\r\n    #\"Inserted local time\" = Table.AddColumn(#\"Added custom 3\", \"Actual_Shipment_DateTime_Local\", each DateTimeZone.ToLocal([Actual_Shipment_DateTime_PST]), type nullable datetimezone),\r\n    #\"Duplicated column\" = Table.DuplicateColumn(#\"Inserted local time\", \"Actual_Shipment_DateTime_Local\", \"Actual_Shipment_Date_Local\"),\r\n    #\"Changed column type 1\" = Table.TransformColumnTypes(#\"Duplicated column\", {{\"Actual_Shipment_Date_Local\", type date}}),\r\n    #\"XXCOH_MS_SHIPMENT_VIEW-41534F465F44415445-autogenerated_for_incremental_refresh\" = Table.SelectRows(#\"Changed column type 1\", each DateTime.From([ASOF_DATE]) >= #\"RangeStart\" and DateTime.From([ASOF_DATE]) < #\"RangeEnd\")\r\nin\r\n    #\"XXCOH_MS_SHIPMENT_VIEW-41534F465F44415445-autogenerated_for_incremental_refresh\";\r\n\r\nshared XXCOH_MT_MTRX_VIEW = let\r\n    Source = Value.NativeQuery(Snowflake.Databases(\"mma12090.snowflakecomputing.com\",\"COMPUTE_REPORTING\",[Role=\"GLBMFGOPERATIONSROLE\"]){[Name=\"PROD_DB\"]}[Data], \"SELECT * FROM PROD_DB.APPS.XXCOH_MT_MTRX_VIEW WHERE OWNING_ORG_CODE='GEP'\", null, [EnableFolding=true]),\r\n    #\"Filtered rows\" = Table.SelectRows(Source, each Date.IsInPreviousNDays([TRANSACTION_DATE], 90)),\r\n    #\"Choose columns\" = Table.SelectColumns(#\"Filtered rows\", {\"DATA_SOURCE\", \"ASOF_DATE\", \"CREATION_DATE\", \"TRANSACTION_DATE\", \"REVISION\", \"TRANSACTION_REFERENCE\", \"SUBINVENTORY_CODE\", \"TRANSACTION_SOURCE_NAME\", \"TRANSACTION_UOM\", \"TRANSACTION_QUANTITY\", \"MMT_PRIMARY_QUANTITY\", \"PRIOR_COSTED_QUANTITY\", \"TRANSFER_PRIOR_COSTED_QUANTITY\", \"OVERCOMPLETION_TRANSACTION_QTY\", \"OVERCOMPLETION_PRIMARY_QTY\", \"QUANTITY_ADJUSTED\", \"MMT_ACTUAL_COST\", \"TRANSACTION_COST\", \"PRIOR_COST\", \"NEW_COST\", \"TRANSFER_COST\", \"TRANSPORTATION_COST\", \"VARIANCE_AMOUNT\", \"MMT_CURRENCY_CODE\", \"MMT_CURRENCY_CONVERSION_RATE\", \"OPERATION_SEQ_NUM\", \"SOURCE_CODE\", \"VENDOR_LOT_NUMBER\", \"TRANSFER_SUBINVENTORY\", \"SHIPMENT_NUMBER\", \"WAYBILL_AIRBILL\", \"FREIGHT_CODE\", \"NUMBER_OF_CONTAINERS\", \"ERROR_CODE\", \"ERROR_EXPLANATION\", \"FINAL_COMPLETION_FLAG\", \"SHIPMENT_COSTED\", \"PICK_SLIP_NUMBER\", \"TRANSACTION_TYPE\", \"TRANSACTION_SOURCE_TYPE\", \"TRANSACTION_ACTION\", \"REASON_NAME\", \"PO_NUM\", \"PO_HEADER_ID\", \"SO_NUM\", \"SO_LINE_NUM\", \"SO_HEADER_ID\", \"SO_LINE_ID\", \"ACCT_ENTITY\", \"ACCT_DEPT\", \"ACCT_ACCOUNT\", \"ACCT_PROJ\", \"ACCT_INTERCO\", \"MOVE_ORDER_NUM\", \"MOVE_ORDER_HEADER_ID\", \"WIP_ENTITY_NAME\", \"WIP_ENTITY_ID\", \"WIP_ENTITY_TYPE\", \"ALIAS_ENTITY\", \"ALIAS_DEPT\", \"ALIAS_ACCOUNT\", \"ALIAS_PROJ\", \"ALIAS_INTERCO\", \"REQ_NUM\", \"REQ_HEADER_ID\", \"CYCLE_COUNT_HEADER_NAME\", \"CYCLE_COUNT_HEADER_ID\", \"PHYSICAL_INVENTORY_NAME\", \"PHYSICAL_INVENTORY_ID\", \"PHYSICAL_INVENTORY_ORG_ID\", \"COST_UPDATE\", \"COST_UPDATE_ID\", \"TRX_ORG_CODE\", \"TRX_OPERATING_UNIT\", \"TRX_LEGAL_ENTITY\", \"TRX_SET_OF_BOOKS\", \"TRX_FUNC_CURRENCY_CODE\", \"PLANNING_ORG_CODE\", \"OWNING_ORG_CODE\", \"TRANSFER_ORG_CODE\", \"ITEM_NUMBER\", \"ITEM_DESCRIPTION\", \"ITEM_TYPE\", \"MAKE_OR_BUY\", \"TECHNICAL_BUSINESS_UNIT\", \"PRODUCT_FAMILY\", \"PRODUCT_LINE\", \"LEAD_TIME_CATEGOEY\", \"FORECAST_FIELD\", \"COMMODITY\", \"PRIMARY_ORG\", \"SUPPLY_SOURCE\", \"DEMAND_SOURCE\", \"BACKUP_CATEGORY\", \"ITEM_CUSTOMER\", \"BCP_CODE\", \"ROYALTY\", \"PLANNING_PRODUCT_FAMILY\", \"PLANNING_LOW_LEVEL_CODE\", \"PLANNING_FAMILY_UNIQUE\", \"OPERATIONS_REPORTING\", \"SEC_REPORTING\", \"MATERIAL_ENTITY\", \"MATERIAL_DEPT\", \"MATERIAL_ACCT\", \"MATERIAL_PROJ\", \"MATERIAL_IC\", \"MATERIAL_TBD\", \"MATERIAL_OH_ENTITY\", \"MATERIAL_OH_DEPT\", \"MATERIAL_OH_ACCT\", \"MATERIAL_OH_PROJ\", \"MATERIAL_OH_IC\", \"MATERIAL_OH_TBD\", \"RESOURCE_ENTITY\", \"RESOURCE_DEPT\", \"RESOURCE_ACCT\", \"RESOURCE_PROJ\", \"RESOURCE_IC\", \"RESOURCE_TBD\", \"OVERHEAD_ENTITY\", \"OVERHEAD_DEPT\", \"OVERHEAD_ACCT\", \"OVERHEAD_PROJ\", \"OVERHEAD_IC\", \"OVERHEAD_TBD\", \"OS_PROCESS_ENTITY\", \"OS_PROCESS_DEPT\", \"OS_PROCESS_ACCT\", \"OS_PROCESS_PROJ\", \"OS_PROCESS_IC\", \"OS_PROCESS_TBD\", \"COST_GROUP\", \"COST_GROUP_TYPE\", \"CG_MATERIAL_ENTITY\", \"CG_MATERIAL_DEPT\", \"CG_MATERIAL_ACCT\", \"CG_MATERIAL_PROJ\", \"CG_MATERIAL_IC\", \"CG_MATERIAL_TBD\", \"CG_MATERIAL_OH_ENTITY\", \"CG_MATERIAL_OH_DEPT\", \"CG_MATERIAL_OH_ACCT\", \"CG_MATERIAL_OH_PROJ\", \"CG_MATERIAL_OH_IC\", \"CG_MATERIAL_OH_TBD\", \"CG_RESOURCE_ENTITY\", \"CG_RESOURCE_DEPT\", \"CG_RESOURCE_ACCT\", \"CG_RESOURCE_PROJ\", \"CG_RESOURCE_IC\", \"CG_RESOURCE_TBD\", \"CG_OVERHEAD_ENTITY\", \"CG_OVERHEAD_DEPT\", \"CG_OVERHEAD_ACCT\", \"CG_OVERHEAD_PROJ\", \"CG_OVERHEAD_IC\", \"CG_OVERHEAD_TBD\", \"CG_OS_PROCESS_ENTITY\", \"CG_OS_PROCESS_DEPT\", \"CG_OS_PROCESS_ACCT\", \"CG_OS_PROCESS_PROJ\", \"CG_OS_PROCESS_IC\", \"CG_OS_PROCESS_TBD\", \"CG_EXPENSE_ENTITY\", \"CG_EXPENSE_DEPT\", \"CG_EXPENSE_ACCT\", \"CG_EXPENSE_PROJ\", \"CG_EXPENSE_IC\", \"CG_EXPENSE_TBD\", \"CG_AVGCOSTV_ENTITY\", \"CG_AVGCOSTV_DEPT\", \"CG_AVGCOSTV_ACCT\", \"CG_AVGCOSTV_PROJ\", \"CG_AVGCOSTV_IC\", \"CG_AVGCOSTV_TBD\", \"MTA_ENTITY\", \"MTA_DEPT\", \"MTA_ACCOUNT\", \"MTA_PROJECT\", \"MTA_INTERCO\", \"MTA_TRANSACTION_DATE\", \"PRIMARY_QUANTITY\", \"GL_BATCH_ID\", \"ENTERED_DR\", \"ENTERED_CR\", \"ACCOUNTED_DR\", \"ACCOUNTED_CR\", \"ACCOUNTED_DR_USD\", \"ACCOUNTED_CR_USD\", \"ACCOUNTED_NET\", \"ACCOUNTED_NET_USD\", \"LINE_REFERENCE\", \"RESOURCE_CODE\", \"RESOURCE_DESCRIPTION\", \"ACTIVITY\", \"MTA_CURRENCY_CODE\", \"MTA_CURRENCY_CONVERSION_RATE\", \"ACTUAL_COST\", \"MATERIAL_COST\", \"MATERIAL_OH_COST\", \"RESOURCE_COST\", \"OS_PROCESSING_COST\", \"RESOURCE_OH_COST\", \"PERIOD_NAME\", \"FISCAL_PERIOD\", \"FISCAL_QUARTER\", \"FISCAL_YEAR\", \"FISCAL_WEEK\", \"TRANSACTION_ID\", \"INVENTORY_ITEM_ID\", \"ORGANIZATION_ID\", \"REPETITIVE_LINE_ID\", \"RMA_LINE_ID\", \"TRANSFER_TRANSACTION_ID\", \"TRANSACTION_CREATED_BY\", \"TRANSACTION_UPDATED_BY\", \"ORG_TECHNICAL_BUSINESS_UNIT\", \"ORG_PRODUCT_FAMILY\", \"ORG_PRODUCT_LINE\", \"ORG_FORECAST_FIELD\", \"CAL_MONTH\", \"ROW_CREATION_DATE\"}),\r\n    #\"Added custom\" = Table.TransformColumnTypes(Table.AddColumn(#\"Choose columns\", \"Transaction_DateTime_DE\", each DateTime.AddZone([TRANSACTION_DATE], -8)), {{\"Transaction_DateTime_DE\", type datetime}}),\r\n    #\"Inserted date\" = Table.AddColumn(#\"Added custom\", \"Transaction_Date_DE\", each DateTime.Date([Transaction_DateTime_DE]), type nullable date),\r\n    #\"Inserted time\" = Table.AddColumn(#\"Inserted date\", \"Transaction_Time_DE\", each DateTime.Time([Transaction_DateTime_DE]), type nullable time)\r\nin\r\n    #\"Inserted time\";\r\n\r\nshared #\"XXCOH_MT_MTRX_VIEW (2)\" = let\r\n    Source = XXCOH_MT_MTRX_VIEW,\r\n    #\"Sorted rows\" = Table.Sort(Source, {{\"ASOF_DATE\", Order.Descending}}),\r\n    #\"Kept top rows\" = Table.FirstN(#\"Sorted rows\", 10)\r\nin\r\n    #\"Kept top rows\";\r\n\r\nshared parStartDate = #datetime(2020, 12, 31, 0, 0, 0) meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type datetime];\r\n\r\nshared XXCOH_MP_RECEIPTS_VIEW = let\r\n    Source = Value.NativeQuery(Snowflake.Databases(\"mma12090.snowflakecomputing.com\",\"COMPUTE_REPORTING\",[Role=\"GLBMFGOPERATIONSROLE\"]){[Name=\"PROD_DB\"]}[Data], \"SELECT * FROM PROD_DB.APPS.XXCOH_MP_RECEIPTS_VIEW WHERE ORG_Code='GEP'\", null, [EnableFolding=true]),\r\n    #\"Changed column type\" = Table.TransformColumnTypes(Source, {{\"RECEIPT_LINE_NUM\", Int64.Type}, {\"SOURCE_NUMBER\", Int64.Type}, {\"OPERATING_UNIT_ID\", Int64.Type}, {\"LEGAL_ENTITY_ID\", Int64.Type}, {\"FISCAL_PERIOD\", Int64.Type}, {\"FISCAL_QUARTER\", Int64.Type}, {\"FISCAL_YEAR\", Int64.Type}, {\"FISCAL_WEEK\", Int64.Type}, {\"PARENT_TRANSACTION_ID\", Int64.Type}, {\"TRANSACTION_ID\", Int64.Type}, {\"INV_TRANSACTION_ID\", Int64.Type}, {\"PO_HEADER_ID\", Int64.Type}, {\"PO_LINE_ID\", Int64.Type}, {\"PO_LINE_LOCATION_ID\", Int64.Type}, {\"PO_DISTRIBUTION_ID\", Int64.Type}, {\"REQUISITION_LINE_ID\", Int64.Type}, {\"SHIPMENT_HEADER_ID\", Int64.Type}, {\"SHIPMENT_LINE_ID\", Int64.Type}, {\"ITEM_ID\", Int64.Type}, {\"FROM_ORGANIZATION_ID\", Int64.Type}, {\"TO_ORGANIZATION_ID\", Int64.Type}, {\"OE_ORDER_HEADER_ID\", Int64.Type}, {\"OE_ORDER_LINE_ID\", Int64.Type}, {\"WIP_ENTITY_ID\", Int64.Type}, {\"UNIT_PRICE\", Currency.Type}, {\"ITEM_COST\", Currency.Type}, {\"ITEM_ADD_BACK_COST\", Currency.Type}, {\"MATERIAL_COST\", Currency.Type}, {\"RESOURCE_COST\", Currency.Type}, {\"MATERIAL_OVERHEAD_COST\", Currency.Type}, {\"OVERHEAD_COST\", Currency.Type}, {\"OUTSIDE_PROCESSING_COST\", Currency.Type}, {\"UNBURDENED_COST\", Currency.Type}, {\"WIP_OPERATION_SEQ_NUM\", Int64.Type}, {\"WIP_RESOURCE_SEQ_NUM\", Int64.Type}}),\r\n    #\"Replaced value\" = Table.ReplaceValue(#\"Changed column type\", \"!\", \"1\", Replacer.ReplaceText, {\"RECEIPT_COMMENTS\"}),\r\n    #\"Replaced value 1\" = Table.ReplaceValue(#\"Replaced value\", \"\"\"\", \"2\", Replacer.ReplaceText, {\"RECEIPT_COMMENTS\"}),\r\n    #\"Replaced value 2\" = Table.ReplaceValue(#\"Replaced value 1\", \"ยง\", \"3\", Replacer.ReplaceText, {\"RECEIPT_COMMENTS\"}),\r\n    #\"Replaced value 3\" = Table.ReplaceValue(#\"Replaced value 2\", \"$\", \"4\", Replacer.ReplaceText, {\"RECEIPT_COMMENTS\"}),\r\n    #\"Replaced value 4\" = Table.ReplaceValue(#\"Replaced value 3\", \"%\", \"5\", Replacer.ReplaceText, {\"RECEIPT_COMMENTS\"}),\r\n    #\"Replaced value 5\" = Table.ReplaceValue(#\"Replaced value 4\", \"&\", \"6\", Replacer.ReplaceText, {\"RECEIPT_COMMENTS\"}),\r\n    #\"Replaced value 6\" = Table.ReplaceValue(#\"Replaced value 5\", \"/\", \"7\", Replacer.ReplaceText, {\"RECEIPT_COMMENTS\"}),\r\n    #\"Replaced value 7\" = Table.ReplaceValue(#\"Replaced value 6\", \"(\", \"8\", Replacer.ReplaceText, {\"RECEIPT_COMMENTS\"}),\r\n    #\"Replaced value 8\" = Table.ReplaceValue(#\"Replaced value 7\", \")\", \"9\", Replacer.ReplaceText, {\"RECEIPT_COMMENTS\"}),\r\n    #\"Replaced value 9\" = Table.ReplaceValue(#\"Replaced value 8\", \"=\", \"0\", Replacer.ReplaceText, {\"RECEIPT_COMMENTS\"}),\r\n    #\"Duplicated column\" = Table.DuplicateColumn(#\"Replaced value 9\", \"RECEIPT_COMMENTS\", \"RECEIPT_TimeStamp\"),\r\n    #\"Split column by positions\" = Table.SplitColumn(#\"Duplicated column\", \"RECEIPT_TimeStamp\", Splitter.SplitTextByPositions({0, 8, 12}), {\"Docking_Date\", \"Docking_Time\", \"Docking_Fab\"}),\r\n    #\"Changed column type 1\" = Table.TransformColumnTypes(#\"Split column by positions\", {{\"Docking_Date\", type date}, {\"Docking_Time\", type time}, {\"Docking_Fab\", type text}}),\r\n    #\"Added custom\" = Table.AddColumn(#\"Changed column type 1\", \"Transaction_DateTime_DE\", each DateTime.AddZone([TRANSACTION_DATE], -8)),\r\n    #\"Changed column type 2\" = Table.TransformColumnTypes(#\"Added custom\", {{\"Transaction_DateTime_DE\", type datetime}},\"de-DE\"),\r\n    #\"Duplicated column 1\" = Table.DuplicateColumn(#\"Changed column type 2\", \"Transaction_DateTime_DE\", \"Transaction_Date_DE\"),\r\n    #\"Changed column type 3\" = Table.TransformColumnTypes(#\"Duplicated column 1\", {{\"Transaction_Date_DE\", type date}}),\r\n    #\"Replaced errors\" = Table.ReplaceErrorValues(#\"Changed column type 3\", {{\"Docking_Time\", #time(0, 0, 0)}}),\r\n    #\"Replaced errors 1\" = Table.ReplaceErrorValues(#\"Replaced errors\", {{\"Docking_Date\", #date(1999, 1, 1)}}),\r\n    #\"Inserted time\" = Table.AddColumn(#\"Replaced errors 1\", \"Transaction_Time\", each DateTime.Time([Transaction_DateTime_DE]), type nullable time),\r\n    #\"Extracted first characters\" = Table.TransformColumns(#\"Inserted time\", {{\"Docking_Fab\", each Text.Start(_, 2), type text}}),\r\n    #\"XXCOH_MP_RECEIPTS_VIEW-5452414E53414354494F4E5F44415445-autogenerated_for_incremental_refresh\" = Table.SelectRows(#\"Extracted first characters\", each DateTime.From([TRANSACTION_DATE]) >= RangeStart and DateTime.From([TRANSACTION_DATE]) < RangeEnd)\r\nin\r\n    #\"XXCOH_MP_RECEIPTS_VIEW-5452414E53414354494F4E5F44415445-autogenerated_for_incremental_refresh\";\r\n\r\nshared RangeStart = let RangeStart = #datetime(0001,01,01,00,00,00) meta [IsParameterQuery=true, List={}, Type=\"DateTime\", IsParameterQueryRequired=true, Description=\"autogenerated_for_incremental_refresh\"] in RangeStart;\r\n\r\nshared RangeEnd = let RangeEnd = #datetime(9999,12,31,23,59,59) meta [IsParameterQuery=true, List={}, Type=\"DateTime\", IsParameterQueryRequired=true, Description=\"autogenerated_for_incremental_refresh\"] in RangeEnd;\r\n\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[{\"id\":\"4a0b9267-db97-43a3-b998-863f27253b89\",\"name\":\"Transform file from Logistics_Transactions\",\"description\":null,\"parentId\":null,\"order\":0},{\"id\":\"9571a417-5b12-49a6-a3c1-1a841842e20c\",\"name\":\"Helper queries (3)\",\"description\":null,\"parentId\":\"4a0b9267-db97-43a3-b998-863f27253b89\",\"order\":0},{\"id\":\"b32a44d1-a823-41c6-88da-4ef2ab09a5a5\",\"name\":\"Transform File from ReceivingDailyIssues\",\"description\":\"\",\"parentId\":null,\"order\":1},{\"id\":\"639ed2f2-25e6-46c8-b0b3-0deec5e1bacc\",\"name\":\"Helper Queries\",\"description\":\"\",\"parentId\":\"b32a44d1-a823-41c6-88da-4ef2ab09a5a5\",\"order\":2},{\"id\":\"98626363-884f-48d8-8556-a3a6ce4a0dc2\",\"name\":\"Transform file from Logistics_Headers\",\"description\":null,\"parentId\":null,\"order\":0},{\"id\":\"fb154f34-ba2c-44d6-9567-5caf0c3d7e62\",\"name\":\"Helper queries (2)\",\"description\":null,\"parentId\":\"98626363-884f-48d8-8556-a3a6ce4a0dc2\",\"order\":0},{\"id\":\"58788a6c-4919-4be7-91e2-6a2f3c282f00\",\"name\":\"Inactive\",\"description\":\"\",\"parentId\":null,\"order\":0}]"}],"entities":[{"$type":"LocalEntity","name":"ReceivingDailyIssues","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"ReceivingDailyIssues.csv"},"attributes":[{"name":"PO","dataType":"string"},{"name":"Fehler","dataType":"string"},{"name":"Lieferant","dataType":"string"},{"name":"Artikelnr.","dataType":"string"},{"name":"Menge","dataType":"double"},{"name":"Einheit","dataType":"string"},{"name":"Std. Lieferant","dataType":"string"},{"name":"Planner/Buyer","dataType":"string"},{"name":"Bearbeiter","dataType":"string"},{"name":"Eingetragen am","dataType":"date"},{"name":"Date Resolved","dataType":"date"},{"name":"Duration (days)","dataType":"int64"},{"name":"Comment/Feedback","dataType":"string"},{"name":"Status","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-20T08:30:20.9216607+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/a4199ec4-4752-4af9-930f-8512992b9b06/ReceivingDailyIssues.csv?snapshot=2022-05-20T08%3A30%3A20.8167823Z"}]},{"$type":"LocalEntity","name":"XXCOH_MT_MTRX_VIEW","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"XXCOH_MT_MTRX_VIEW.csv"},"attributes":[{"name":"DATA_SOURCE","dataType":"string"},{"name":"ASOF_DATE","dataType":"date"},{"name":"CREATION_DATE","dataType":"dateTime"},{"name":"TRANSACTION_DATE","dataType":"dateTime"},{"name":"REVISION","dataType":"string"},{"name":"TRANSACTION_REFERENCE","dataType":"string"},{"name":"SUBINVENTORY_CODE","dataType":"string"},{"name":"TRANSACTION_SOURCE_NAME","dataType":"string"},{"name":"TRANSACTION_UOM","dataType":"string"},{"name":"TRANSACTION_QUANTITY","dataType":"double"},{"name":"MMT_PRIMARY_QUANTITY","dataType":"double"},{"name":"PRIOR_COSTED_QUANTITY","dataType":"double"},{"name":"TRANSFER_PRIOR_COSTED_QUANTITY","dataType":"double"},{"name":"OVERCOMPLETION_TRANSACTION_QTY","dataType":"double"},{"name":"OVERCOMPLETION_PRIMARY_QTY","dataType":"double"},{"name":"QUANTITY_ADJUSTED","dataType":"double"},{"name":"MMT_ACTUAL_COST","dataType":"double"},{"name":"TRANSACTION_COST","dataType":"double"},{"name":"PRIOR_COST","dataType":"double"},{"name":"NEW_COST","dataType":"double"},{"name":"TRANSFER_COST","dataType":"double"},{"name":"TRANSPORTATION_COST","dataType":"double"},{"name":"VARIANCE_AMOUNT","dataType":"double"},{"name":"MMT_CURRENCY_CODE","dataType":"string"},{"name":"MMT_CURRENCY_CONVERSION_RATE","dataType":"double"},{"name":"OPERATION_SEQ_NUM","dataType":"double"},{"name":"SOURCE_CODE","dataType":"string"},{"name":"VENDOR_LOT_NUMBER","dataType":"string"},{"name":"TRANSFER_SUBINVENTORY","dataType":"string"},{"name":"SHIPMENT_NUMBER","dataType":"string"},{"name":"WAYBILL_AIRBILL","dataType":"string"},{"name":"FREIGHT_CODE","dataType":"string"},{"name":"NUMBER_OF_CONTAINERS","dataType":"double"},{"name":"ERROR_CODE","dataType":"string"},{"name":"ERROR_EXPLANATION","dataType":"string"},{"name":"FINAL_COMPLETION_FLAG","dataType":"string"},{"name":"SHIPMENT_COSTED","dataType":"string"},{"name":"PICK_SLIP_NUMBER","dataType":"double"},{"name":"TRANSACTION_TYPE","dataType":"string"},{"name":"TRANSACTION_SOURCE_TYPE","dataType":"string"},{"name":"TRANSACTION_ACTION","dataType":"string"},{"name":"REASON_NAME","dataType":"string"},{"name":"PO_NUM","dataType":"string"},{"name":"PO_HEADER_ID","dataType":"double"},{"name":"SO_NUM","dataType":"double"},{"name":"SO_LINE_NUM","dataType":"string"},{"name":"SO_HEADER_ID","dataType":"double"},{"name":"SO_LINE_ID","dataType":"double"},{"name":"ACCT_ENTITY","dataType":"string"},{"name":"ACCT_DEPT","dataType":"string"},{"name":"ACCT_ACCOUNT","dataType":"string"},{"name":"ACCT_PROJ","dataType":"string"},{"name":"ACCT_INTERCO","dataType":"string"},{"name":"MOVE_ORDER_NUM","dataType":"string"},{"name":"MOVE_ORDER_HEADER_ID","dataType":"double"},{"name":"WIP_ENTITY_NAME","dataType":"string"},{"name":"WIP_ENTITY_ID","dataType":"double"},{"name":"WIP_ENTITY_TYPE","dataType":"string"},{"name":"ALIAS_ENTITY","dataType":"string"},{"name":"ALIAS_DEPT","dataType":"string"},{"name":"ALIAS_ACCOUNT","dataType":"string"},{"name":"ALIAS_PROJ","dataType":"string"},{"name":"ALIAS_INTERCO","dataType":"string"},{"name":"REQ_NUM","dataType":"string"},{"name":"REQ_HEADER_ID","dataType":"double"},{"name":"CYCLE_COUNT_HEADER_NAME","dataType":"string"},{"name":"CYCLE_COUNT_HEADER_ID","dataType":"double"},{"name":"PHYSICAL_INVENTORY_NAME","dataType":"string"},{"name":"PHYSICAL_INVENTORY_ID","dataType":"double"},{"name":"PHYSICAL_INVENTORY_ORG_ID","dataType":"double"},{"name":"COST_UPDATE","dataType":"string"},{"name":"COST_UPDATE_ID","dataType":"double"},{"name":"TRX_ORG_CODE","dataType":"string"},{"name":"TRX_OPERATING_UNIT","dataType":"string"},{"name":"TRX_LEGAL_ENTITY","dataType":"string"},{"name":"TRX_SET_OF_BOOKS","dataType":"string"},{"name":"TRX_FUNC_CURRENCY_CODE","dataType":"string"},{"name":"PLANNING_ORG_CODE","dataType":"string"},{"name":"OWNING_ORG_CODE","dataType":"string"},{"name":"TRANSFER_ORG_CODE","dataType":"string"},{"name":"ITEM_NUMBER","dataType":"string"},{"name":"ITEM_DESCRIPTION","dataType":"string"},{"name":"ITEM_TYPE","dataType":"string"},{"name":"MAKE_OR_BUY","dataType":"string"},{"name":"TECHNICAL_BUSINESS_UNIT","dataType":"string"},{"name":"PRODUCT_FAMILY","dataType":"string"},{"name":"PRODUCT_LINE","dataType":"string"},{"name":"LEAD_TIME_CATEGOEY","dataType":"string"},{"name":"FORECAST_FIELD","dataType":"string"},{"name":"COMMODITY","dataType":"string"},{"name":"PRIMARY_ORG","dataType":"string"},{"name":"SUPPLY_SOURCE","dataType":"string"},{"name":"DEMAND_SOURCE","dataType":"string"},{"name":"BACKUP_CATEGORY","dataType":"string"},{"name":"ITEM_CUSTOMER","dataType":"string"},{"name":"BCP_CODE","dataType":"string"},{"name":"ROYALTY","dataType":"string"},{"name":"PLANNING_PRODUCT_FAMILY","dataType":"string"},{"name":"PLANNING_LOW_LEVEL_CODE","dataType":"string"},{"name":"PLANNING_FAMILY_UNIQUE","dataType":"string"},{"name":"OPERATIONS_REPORTING","dataType":"string"},{"name":"SEC_REPORTING","dataType":"string"},{"name":"MATERIAL_ENTITY","dataType":"string"},{"name":"MATERIAL_DEPT","dataType":"string"},{"name":"MATERIAL_ACCT","dataType":"string"},{"name":"MATERIAL_PROJ","dataType":"string"},{"name":"MATERIAL_IC","dataType":"string"},{"name":"MATERIAL_TBD","dataType":"string"},{"name":"MATERIAL_OH_ENTITY","dataType":"string"},{"name":"MATERIAL_OH_DEPT","dataType":"string"},{"name":"MATERIAL_OH_ACCT","dataType":"string"},{"name":"MATERIAL_OH_PROJ","dataType":"string"},{"name":"MATERIAL_OH_IC","dataType":"string"},{"name":"MATERIAL_OH_TBD","dataType":"string"},{"name":"RESOURCE_ENTITY","dataType":"string"},{"name":"RESOURCE_DEPT","dataType":"string"},{"name":"RESOURCE_ACCT","dataType":"string"},{"name":"RESOURCE_PROJ","dataType":"string"},{"name":"RESOURCE_IC","dataType":"string"},{"name":"RESOURCE_TBD","dataType":"string"},{"name":"OVERHEAD_ENTITY","dataType":"string"},{"name":"OVERHEAD_DEPT","dataType":"string"},{"name":"OVERHEAD_ACCT","dataType":"string"},{"name":"OVERHEAD_PROJ","dataType":"string"},{"name":"OVERHEAD_IC","dataType":"string"},{"name":"OVERHEAD_TBD","dataType":"string"},{"name":"OS_PROCESS_ENTITY","dataType":"string"},{"name":"OS_PROCESS_DEPT","dataType":"string"},{"name":"OS_PROCESS_ACCT","dataType":"string"},{"name":"OS_PROCESS_PROJ","dataType":"string"},{"name":"OS_PROCESS_IC","dataType":"string"},{"name":"OS_PROCESS_TBD","dataType":"string"},{"name":"COST_GROUP","dataType":"string"},{"name":"COST_GROUP_TYPE","dataType":"double"},{"name":"CG_MATERIAL_ENTITY","dataType":"string"},{"name":"CG_MATERIAL_DEPT","dataType":"string"},{"name":"CG_MATERIAL_ACCT","dataType":"string"},{"name":"CG_MATERIAL_PROJ","dataType":"string"},{"name":"CG_MATERIAL_IC","dataType":"string"},{"name":"CG_MATERIAL_TBD","dataType":"string"},{"name":"CG_MATERIAL_OH_ENTITY","dataType":"string"},{"name":"CG_MATERIAL_OH_DEPT","dataType":"string"},{"name":"CG_MATERIAL_OH_ACCT","dataType":"string"},{"name":"CG_MATERIAL_OH_PROJ","dataType":"string"},{"name":"CG_MATERIAL_OH_IC","dataType":"string"},{"name":"CG_MATERIAL_OH_TBD","dataType":"string"},{"name":"CG_RESOURCE_ENTITY","dataType":"string"},{"name":"CG_RESOURCE_DEPT","dataType":"string"},{"name":"CG_RESOURCE_ACCT","dataType":"string"},{"name":"CG_RESOURCE_PROJ","dataType":"string"},{"name":"CG_RESOURCE_IC","dataType":"string"},{"name":"CG_RESOURCE_TBD","dataType":"string"},{"name":"CG_OVERHEAD_ENTITY","dataType":"string"},{"name":"CG_OVERHEAD_DEPT","dataType":"string"},{"name":"CG_OVERHEAD_ACCT","dataType":"string"},{"name":"CG_OVERHEAD_PROJ","dataType":"string"},{"name":"CG_OVERHEAD_IC","dataType":"string"},{"name":"CG_OVERHEAD_TBD","dataType":"string"},{"name":"CG_OS_PROCESS_ENTITY","dataType":"string"},{"name":"CG_OS_PROCESS_DEPT","dataType":"string"},{"name":"CG_OS_PROCESS_ACCT","dataType":"string"},{"name":"CG_OS_PROCESS_PROJ","dataType":"string"},{"name":"CG_OS_PROCESS_IC","dataType":"string"},{"name":"CG_OS_PROCESS_TBD","dataType":"string"},{"name":"CG_EXPENSE_ENTITY","dataType":"string"},{"name":"CG_EXPENSE_DEPT","dataType":"string"},{"name":"CG_EXPENSE_ACCT","dataType":"string"},{"name":"CG_EXPENSE_PROJ","dataType":"string"},{"name":"CG_EXPENSE_IC","dataType":"string"},{"name":"CG_EXPENSE_TBD","dataType":"string"},{"name":"CG_AVGCOSTV_ENTITY","dataType":"string"},{"name":"CG_AVGCOSTV_DEPT","dataType":"string"},{"name":"CG_AVGCOSTV_ACCT","dataType":"string"},{"name":"CG_AVGCOSTV_PROJ","dataType":"string"},{"name":"CG_AVGCOSTV_IC","dataType":"string"},{"name":"CG_AVGCOSTV_TBD","dataType":"string"},{"name":"MTA_ENTITY","dataType":"string"},{"name":"MTA_DEPT","dataType":"string"},{"name":"MTA_ACCOUNT","dataType":"string"},{"name":"MTA_PROJECT","dataType":"string"},{"name":"MTA_INTERCO","dataType":"string"},{"name":"MTA_TRANSACTION_DATE","dataType":"dateTime"},{"name":"PRIMARY_QUANTITY","dataType":"double"},{"name":"GL_BATCH_ID","dataType":"double"},{"name":"ENTERED_DR","dataType":"double"},{"name":"ENTERED_CR","dataType":"double"},{"name":"ACCOUNTED_DR","dataType":"double"},{"name":"ACCOUNTED_CR","dataType":"double"},{"name":"ACCOUNTED_DR_USD","dataType":"double"},{"name":"ACCOUNTED_CR_USD","dataType":"double"},{"name":"ACCOUNTED_NET","dataType":"double"},{"name":"ACCOUNTED_NET_USD","dataType":"double"},{"name":"LINE_REFERENCE","dataType":"string"},{"name":"RESOURCE_CODE","dataType":"string"},{"name":"RESOURCE_DESCRIPTION","dataType":"string"},{"name":"ACTIVITY","dataType":"string"},{"name":"MTA_CURRENCY_CODE","dataType":"string"},{"name":"MTA_CURRENCY_CONVERSION_RATE","dataType":"double"},{"name":"ACTUAL_COST","dataType":"double"},{"name":"MATERIAL_COST","dataType":"double"},{"name":"MATERIAL_OH_COST","dataType":"double"},{"name":"RESOURCE_COST","dataType":"double"},{"name":"OS_PROCESSING_COST","dataType":"double"},{"name":"RESOURCE_OH_COST","dataType":"double"},{"name":"PERIOD_NAME","dataType":"string"},{"name":"FISCAL_PERIOD","dataType":"double"},{"name":"FISCAL_QUARTER","dataType":"double"},{"name":"FISCAL_YEAR","dataType":"double"},{"name":"FISCAL_WEEK","dataType":"double"},{"name":"TRANSACTION_ID","dataType":"double"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"ORGANIZATION_ID","dataType":"double"},{"name":"REPETITIVE_LINE_ID","dataType":"double"},{"name":"RMA_LINE_ID","dataType":"double"},{"name":"TRANSFER_TRANSACTION_ID","dataType":"double"},{"name":"TRANSACTION_CREATED_BY","dataType":"string"},{"name":"TRANSACTION_UPDATED_BY","dataType":"string"},{"name":"ORG_TECHNICAL_BUSINESS_UNIT","dataType":"string"},{"name":"ORG_PRODUCT_FAMILY","dataType":"string"},{"name":"ORG_PRODUCT_LINE","dataType":"string"},{"name":"ORG_FORECAST_FIELD","dataType":"string"},{"name":"CAL_MONTH","dataType":"string"},{"name":"ROW_CREATION_DATE","dataType":"dateTime"},{"name":"Transaction_DateTime_DE","dataType":"dateTime"},{"name":"Transaction_Date_DE","dataType":"date"},{"name":"Transaction_Time_DE","dataType":"time"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-20T08:34:17.1835562+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/a4199ec4-4752-4af9-930f-8512992b9b06/XXCOH_MT_MTRX_VIEW.csv?snapshot=2022-05-20T08%3A34%3A17.1530177Z"}]},{"$type":"LocalEntity","name":"XXCOH_MP_RECEIPTS_VIEW","description":"","pbi:refreshPolicy":{"$type":"IncrementalRefreshPolicy","locationPattern":"XXCOH_MP_RECEIPTS_VIEW/part.csv","rollingWindowGranularity":"year","rollingWindowPeriods":1,"incrementalGranularity":"quarter","incrementalPeriods":1},"annotations":[{"name":"pbi:IncrementalRefreshDetectChangeAttribute"},{"name":"pbi:IncrementalRefreshFilterByAttribute","value":"TRANSACTION_DATE"}],"attributes":[{"name":"ASOF_DATE","dataType":"date"},{"name":"ASOF_DATE_DISP","dataType":"dateTime"},{"name":"RECEIPT_NUM","dataType":"string"},{"name":"RECEIPT_COMMENTS","dataType":"string"},{"name":"RECEIPT_LINE_NUM","dataType":"int64"},{"name":"SOURCE_DOCUMENT_CODE","dataType":"string"},{"name":"DESTINATION_TYPE_CODE","dataType":"string"},{"name":"COUNTRY_OF_ORIGIN_CODE","dataType":"string"},{"name":"TRANSACTION_DATE","dataType":"dateTime"},{"name":"TRANSACTION_TYPE","dataType":"string"},{"name":"USER_ENTERED_FLAG","dataType":"string"},{"name":"ITEM_NUMBER","dataType":"string"},{"name":"ITEM_DESCRIPTION","dataType":"string"},{"name":"ITEM_REVISION","dataType":"string"},{"name":"DAYS_LATE_RECEIPT_ALLOWED","dataType":"double"},{"name":"ORDER_NUMBER","dataType":"string"},{"name":"ORDER_TYPE","dataType":"string"},{"name":"SOURCE_NAME","dataType":"string"},{"name":"ALTERNATE_SOURCE_NAME","dataType":"string"},{"name":"VENDOR_INTERNAL","dataType":"string"},{"name":"INTERDIV","dataType":"string"},{"name":"SOURCE_NUMBER","dataType":"int64"},{"name":"LINE_NUMBER","dataType":"double"},{"name":"QUANTITY","dataType":"double"},{"name":"UNIT_OF_MEASURE","dataType":"string"},{"name":"PRIMARY_QUANTITY","dataType":"double"},{"name":"PRIMARY_UNIT_OF_MEASURE","dataType":"string"},{"name":"PO_SHIPMENT_NUMBER","dataType":"double"},{"name":"PO_SHIPMENT_QUANTITY","dataType":"double"},{"name":"ORDERED_QANTITY","dataType":"double"},{"name":"ORDERED_UNIT_OF_MEASURE","dataType":"string"},{"name":"UNIT_PRICE","dataType":"decimal"},{"name":"CURRENCY_CODE","dataType":"string"},{"name":"CURRENCY_CONVERSION_RATE","dataType":"double"},{"name":"OE_CURRENCY_CODE","dataType":"string"},{"name":"PO_CURRENCY_CODE","dataType":"string"},{"name":"RSH_CURRENCY_CODE","dataType":"string"},{"name":"ITEM_COST","dataType":"decimal"},{"name":"ITEM_ADD_BACK_COST","dataType":"decimal"},{"name":"MATERIAL_COST","dataType":"decimal"},{"name":"RESOURCE_COST","dataType":"decimal"},{"name":"MATERIAL_OVERHEAD_COST","dataType":"decimal"},{"name":"OVERHEAD_COST","dataType":"decimal"},{"name":"OUTSIDE_PROCESSING_COST","dataType":"decimal"},{"name":"UNBURDENED_COST","dataType":"decimal"},{"name":"NOTE_TO_RECEIVER","dataType":"string"},{"name":"DUE_DATE","dataType":"dateTime"},{"name":"PACKING_SLIP","dataType":"string"},{"name":"FREIGHT_CARRIER","dataType":"string"},{"name":"WAYBILL_AIRBILL_NUM","dataType":"string"},{"name":"NUM_OF_CONTAINERS","dataType":"double"},{"name":"SHIPPING_DATE","dataType":"dateTime"},{"name":"FOB","dataType":"string"},{"name":"INSPECTION_STATUS_CODE","dataType":"string"},{"name":"INSPECTON_QUALITY_CODE","dataType":"string"},{"name":"FROM_ORG_CODE","dataType":"string"},{"name":"FROM_OPERATING_UNIT","dataType":"string"},{"name":"FROM_FUNC_CURRENCY_CODE","dataType":"string"},{"name":"ROUTING_NAME","dataType":"string"},{"name":"REASON_CODE","dataType":"string"},{"name":"DESTINATION_CONTEXT","dataType":"string"},{"name":"SUBINVENTORY","dataType":"string"},{"name":"TRANSACTION_CREATION_DATE","dataType":"dateTime"},{"name":"DEFAULT_SUBINVENTORY","dataType":"string"},{"name":"CURRENT_LOCATION","dataType":"string"},{"name":"ORG_CODE","dataType":"string"},{"name":"OPERATING_UNIT","dataType":"string"},{"name":"OPERATING_UNIT_ID","dataType":"int64"},{"name":"LEGAL_ENTITY","dataType":"string"},{"name":"LEGAL_ENTITY_ID","dataType":"int64"},{"name":"FUNC_CURRENCY_CODE","dataType":"string"},{"name":"BUYER","dataType":"string"},{"name":"RECEIVER","dataType":"string"},{"name":"DELIVER_TO_PERSON","dataType":"string"},{"name":"DELIVER_TO_LOCATION","dataType":"string"},{"name":"FISCAL_PERIOD","dataType":"int64"},{"name":"FISCAL_QUARTER","dataType":"int64"},{"name":"FISCAL_YEAR","dataType":"int64"},{"name":"FISCAL_WEEK","dataType":"int64"},{"name":"TR_USD_RATE","dataType":"double"},{"name":"FC_USD_RATE","dataType":"double"},{"name":"WIP_ENTITY_NAME","dataType":"string"},{"name":"WIP_DESCRIPTION","dataType":"string"},{"name":"WIP_OPERATION_SEQ_NUM","dataType":"int64"},{"name":"WIP_RESOURCE_SEQ_NUM","dataType":"int64"},{"name":"QUANTITY_BILLED","dataType":"double"},{"name":"AMOUNT_BILLED","dataType":"double"},{"name":"PO_DESTINATION_TYPE_CODE","dataType":"string"},{"name":"PARENT_TRANSACTION_ID","dataType":"int64"},{"name":"TRANSACTION_ID","dataType":"int64"},{"name":"INV_TRANSACTION_ID","dataType":"int64"},{"name":"PO_HEADER_ID","dataType":"int64"},{"name":"PO_LINE_ID","dataType":"int64"},{"name":"PO_LINE_LOCATION_ID","dataType":"int64"},{"name":"PO_DISTRIBUTION_ID","dataType":"int64"},{"name":"REQUISITION_LINE_ID","dataType":"int64"},{"name":"SHIPMENT_HEADER_ID","dataType":"int64"},{"name":"SHIPMENT_LINE_ID","dataType":"int64"},{"name":"ITEM_ID","dataType":"int64"},{"name":"FROM_ORGANIZATION_ID","dataType":"int64"},{"name":"TO_ORGANIZATION_ID","dataType":"int64"},{"name":"OE_ORDER_HEADER_ID","dataType":"int64"},{"name":"OE_ORDER_LINE_ID","dataType":"int64"},{"name":"WIP_ENTITY_ID","dataType":"int64"},{"name":"ROW_CREATION_DATE","dataType":"dateTime"},{"name":"Docking_Date","dataType":"date"},{"name":"Docking_Time","dataType":"time"},{"name":"Docking_Fab","dataType":"string"},{"name":"Transaction_DateTime_DE","dataType":"dateTime"},{"name":"Transaction_Date_DE","dataType":"date"},{"name":"Transaction_Time","dataType":"time"}],"partitions":[{"name":"IncrementalRefreshPolicyPartition-2021","refreshTime":"2022-05-01T08:52:29.4243562+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/a4199ec4-4752-4af9-930f-8512992b9b06/XXCOH_MP_RECEIPTS_VIEW/part-2021.csv?snapshot=2022-05-01T08%3A52%3A29.4087575Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2021-01-01T00:00:00","end":"2022-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q1","refreshTime":"2022-05-01T08:51:54.9892192+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/a4199ec4-4752-4af9-930f-8512992b9b06/XXCOH_MP_RECEIPTS_VIEW/part-2022Q1.csv?snapshot=2022-05-01T08%3A51%3A54.9684049Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-01-01T00:00:00","end":"2022-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q2","refreshTime":"2022-05-20T08:30:18.968516+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/a4199ec4-4752-4af9-930f-8512992b9b06/XXCOH_MP_RECEIPTS_VIEW/part-2022Q2.csv?snapshot=2022-05-20T08%3A30%3A18.9298587Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-01T00:00:00","end":"2022-07-01T00:00:00"}}]}]}