{"name":"COHREP_SITE_INVENTORY_TRX1","description":"","version":"1.0","culture":"en-US","modifiedTime":"2021-03-19T09:28:26.390536+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":true,"queriesMetadata":{"ORG":{"queryId":"3f0ec9d1-2a80-4384-8a7b-aaae2c5c237f","queryName":"ORG"},"Kanban_Card":{"queryId":"68c4871b-0590-4e1b-8d18-a3c5efc8050f","queryName":"Kanban_Card","queryGroupId":"root","loadEnabled":true},"Onhand":{"queryId":"ec674b22-8d94-4e95-93e5-f62828fa79ae","queryName":"Onhand","queryGroupId":"root","loadEnabled":true},"Open_Supply":{"queryId":"db068778-0c8e-43bf-9afa-7a2634b1353c","queryName":"Open_Supply","queryGroupId":"root","loadEnabled":true},"Cycle_Count_Activity":{"queryId":"a1e5ca18-cdf8-436c-8b8e-6ecee7cfc401","queryName":"Cycle_Count_Activity","queryGroupId":"root","loadEnabled":true},"Serial_Status":{"queryId":"af92de86-7c81-4894-bd59-a54cf393ea2e","queryName":"Serial_Status","queryGroupId":"root","loadEnabled":true},"Receiving_Default":{"queryId":"fcc5af81-cf71-4499-8817-658d01a40af7","queryName":"Receiving_Default","queryGroupId":"root","loadEnabled":true},"Consumption_Advice":{"queryId":"80af5189-c1d0-4e99-b67a-af24a6f3cc41","queryName":"Consumption_Advice","queryGroupId":"root","loadEnabled":true},"Open_WO":{"queryId":"f746c825-6c32-493b-9812-0b6c3d581ae3","queryName":"Open_WO","queryGroupId":"root","loadEnabled":true},"Open_MO":{"queryId":"9f857d3f-df46-403f-ba41-c0142ec4f606","queryName":"Open_MO","queryGroupId":"root","loadEnabled":true},"Receipt":{"queryId":"04e91d1a-bfda-49a6-892c-6afc85b91b07","queryName":"Receipt","queryGroupId":"root","loadEnabled":true},"LocalTZ":{"queryId":"d54f972d-3aaa-4324-94b1-4217ec1791cf","queryName":"LocalTZ"},"Material_Transaction":{"queryId":"f6392d5b-2e8e-4d58-95fd-2bb15e8a172e","queryName":"Material_Transaction","queryGroupId":"root","loadEnabled":true}},"document":"section Section1;\r\nshared ORG = let\r\n  ORG = \"GEP\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type text]\r\nin\r\n  ORG;\r\nshared Kanban_Card = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true,\r\n    Query=\"\r\n    select\r\n    sysdate                                                                                                                        extract_date,\r\n    from_tz(cast (sysdate as timestamp),'PST') at time zone '\"&LocalTZ&\"' local_extract_date,\r\n    mp.organization_code,\r\n    mkc.kanban_card_id,\r\n    mkc.kanban_card_number,\r\n    mkc.creation_date,\r\n    mkc.inventory_item_id,\r\n    msi.segment1                                                                                                                   item_number,\r\n    mkc.pull_sequence_id,\r\n    nvl(mkp.replenishment_lead_time, msi.preprocessing_lead_time + msi.full_lead_time + msi.postprocessing_lead_time)              kanban_lead_time,\r\n    mkp.replenishment_lead_time                                                                                                    pull_sequence_lead_time,\r\n    mkc.subinventory_name,\r\n    (\r\n        SELECT\r\n            mloc.concatenated_segments\r\n        FROM\r\n            apps.mtl_item_locations_kfv mloc\r\n        WHERE\r\n                mloc.inventory_location_id = mkc.locator_id\r\n            AND mloc.organization_id = mp.organization_id\r\n            AND mkc.subinventory_name = mloc.subinventory_code\r\n    ) kanban_locator,\r\n    mkc.source_org_code,\r\n    mkc.source_subinventory,\r\n    (select mil.concatenated_Segments from apps.mtl_item_locations_kfv mil\r\n    where mil.inventory_location_id = mkc.source_locator_id\r\n    and mil.organization_id = mkc.organization_id\r\n    and mil.subinventory_code = mkc.source_subinventory) source_locator,\r\n    decode(mkc.kanban_card_type, 1, 'Replenishable', 2, 'Non Replenishable',\r\n           'Other') kanban_card_type,\r\n    mkc.kanban_size,\r\n    mkc.source_type_meaning                                                                                                        kanban_source_type,\r\n    mkc.supply_status_name                                                                                                         kanban_supply_status,\r\n    mkc.supply_status                                                                                                              supply_status_id,\r\n    (\r\n        SELECT\r\n            MAX(kca.creation_date)\r\n        FROM\r\n            apps.mtl_kanban_card_activity_v kca\r\n        WHERE\r\n                kca.supply_status_name = 'In Process'\r\n            AND kca.creation_date >= sysdate - 365\r\n            AND kca.kanban_card_id = mkc.kanban_card_id\r\n    ) kanban_last_replenish,\r\n    (\r\n        SELECT\r\n            COUNT(kca.creation_date)\r\n        FROM\r\n            apps.mtl_kanban_card_activity_v kca\r\n        WHERE\r\n                kca.supply_status_name = 'In Process'\r\n            AND kca.creation_date >= sysdate - 365\r\n            AND kca.kanban_card_id = mkc.kanban_card_id\r\n    ) kanban_replenish_count,\r\n    (\r\n        SELECT\r\n            fu.user_name\r\n        FROM\r\n            apps.mtl_kanban_card_activity_v    kca,\r\n            apps.fnd_user                      fu\r\n        WHERE\r\n                1 = 1\r\n            AND kca.created_by = fu.user_id\r\n            AND kca.kanban_activity_id = (\r\n                SELECT\r\n                    MAX(kanban_activity_id)\r\n                FROM\r\n                    apps.mtl_kanban_card_activity_v kca2\r\n                WHERE\r\n                        kca2.supply_status_name = 'In Process'\r\n                    AND kca2.kanban_card_id = mkc.kanban_card_id\r\n            )\r\n    ) kanban_last_replenish_by,\r\n    (\r\n        SELECT\r\n            MAX(kca.creation_date)\r\n        FROM\r\n            apps.mtl_kanban_card_activity kca\r\n        WHERE\r\n                kca.supply_status = 4\r\n            AND kca.inventory_item_id = mkc.inventory_item_id\r\n            AND kca.organization_id = mkc.organization_id\r\n            AND kca.kanban_card_id = mkc.kanban_card_id\r\n    ) kanban_last_empty,\r\n    (\r\n        SELECT\r\n            fu.user_name\r\n        FROM\r\n            apps.mtl_kanban_card_activity_v    kca,\r\n            apps.fnd_user                      fu\r\n        WHERE\r\n                1 = 1\r\n            AND kca.created_by = fu.user_id\r\n            AND kca.kanban_activity_id = (\r\n                SELECT\r\n                    MAX(kanban_activity_id)\r\n                FROM\r\n                    apps.mtl_kanban_card_activity kca2\r\n                WHERE\r\n                        kca2.supply_status = 4\r\n                    AND kca2.kanban_card_id = mkc.kanban_card_id\r\n            )\r\n    ) kanban_last_empty_by,\r\n    round((sysdate -(\r\n        SELECT\r\n            MAX(kca.creation_date)\r\n        FROM\r\n            apps.mtl_kanban_card_activity kca\r\n        WHERE\r\n            kca.supply_status IN(\r\n                4, 5\r\n            )\r\n            AND kca.inventory_item_id = mkc.inventory_item_id\r\n            AND kca.organization_id = mkc.organization_id\r\n    --   AND kca.creation_date >= sysdate - 365\r\n            AND kca.kanban_card_id = mkc.kanban_card_id\r\n    )), 0) kanban_activity_age_days,\r\n    (\r\n        SELECT\r\n            SUM(moqd.primary_transaction_quantity)\r\n        FROM\r\n            inv.mtl_onhand_quantities_detail moqd\r\n        WHERE\r\n                moqd.inventory_item_id = mkc.inventory_item_id\r\n            AND moqd.subinventory_code = mkc.source_subinventory\r\n            AND mkc.organization_id = moqd.organization_id\r\n    ) kanban_source_onhand,\r\n    (\r\n        SELECT\r\n            SUM(moqd.primary_transaction_quantity)\r\n        FROM\r\n            inv.mtl_onhand_quantities_detail moqd\r\n        WHERE\r\n                moqd.inventory_item_id = msi.inventory_item_id\r\n            AND moqd.subinventory_code = mkc.subinventory_name\r\n            AND msi.organization_id = moqd.organization_id\r\n    ) kanban_onhand,\r\n    (\r\n        SELECT\r\n            item_cost\r\n        FROM\r\n            apps.cst_item_costs cic\r\n        WHERE\r\n                cic.cost_type_id = 1\r\n            AND cic.organization_id = mkc.organization_id\r\n            AND mkc.inventory_item_id = cic.inventory_item_id\r\n    ) item_cost,\r\n    (\r\n        SELECT\r\n            SUM(mkc2.kanban_size)\r\n        FROM\r\n            apps.mtl_kanban_cards_v mkc2\r\n        WHERE\r\n                mkc2.pull_sequence_id = mkc.pull_sequence_id\r\n            AND mkc2.supply_status_name = 'Full'\r\n            AND mkc2.card_status_name = 'Active'\r\n    ) total_full_size,\r\n    (\r\n        CASE\r\n            WHEN mkc.supply_status_name = 'Full'\r\n                 AND nvl((\r\n                SELECT\r\n                    SUM(moqd.primary_transaction_quantity)\r\n                FROM\r\n                    inv.mtl_onhand_quantities_detail moqd\r\n                WHERE\r\n                        moqd.inventory_item_id = mkc.inventory_item_id\r\n                    AND moqd.subinventory_code = mkc.subinventory_name\r\n                    AND mkc.organization_id = moqd.organization_id\r\n            ), 0) < (\r\n                SELECT\r\n                    SUM(mkc2.kanban_size)\r\n                FROM\r\n                    apps.mtl_kanban_cards_v mkc2\r\n                WHERE\r\n                        mkc2.pull_sequence_id = mkc.pull_sequence_id\r\n                    AND mkc2.supply_status_name = 'Full'\r\n                    AND mkc2.card_status_name = 'Active'\r\n            ) THEN\r\n                'Late to Empty'\r\n            ELSE\r\n                'Normal'\r\n        END\r\n    ) kanban_trigger_exception,\r\n    (\r\n        CASE\r\n            WHEN mkc.supply_status_name = 'In Process'\r\n                 AND mkc.source_type_meaning = 'Intra Org'\r\n                 AND (\r\n                SELECT\r\n                    COUNT(mtrl.line_id)\r\n                FROM\r\n                    inv.mtl_txn_request_lines mtrl\r\n                WHERE\r\n                        mtrl.line_status = 7\r\n                    AND mtrl.reference_id = mkc.kanban_card_id\r\n                    AND mtrl.organization_id = mkc.organization_id\r\n            ) <= 0 THEN\r\n                'Missing Supply'\r\n            WHEN mkc.supply_status_name = 'In Process'\r\n                 AND mkc.source_type_meaning = 'Intra Org'\r\n                 AND (\r\n                SELECT\r\n                    nvl(SUM(moqd.primary_transaction_quantity), 0)\r\n                FROM\r\n                    inv.mtl_onhand_quantities_detail moqd\r\n                WHERE\r\n                        moqd.inventory_item_id = mkc.inventory_item_id\r\n                    AND moqd.subinventory_code = mkc.source_subinventory\r\n                    AND mkc.organization_id = moqd.organization_id\r\n            ) = 0 THEN\r\n                'No Stock to Deliver'\r\n            WHEN mkc.supply_status_name = 'In Process'\r\n                 AND mkc.source_type_meaning = 'Intra Org'\r\n                 AND trunc(sysdate + 1) > (\r\n                SELECT\r\n                    MAX(mtrl.date_required)\r\n                FROM\r\n                    inv.mtl_txn_request_lines mtrl\r\n                WHERE\r\n                        mtrl.line_status = 7\r\n                    AND mtrl.reference_id = mkc.kanban_card_id\r\n                    AND mtrl.organization_id = mkc.organization_id\r\n            )\r\n                 AND (\r\n                SELECT\r\n                    SUM(moqd.primary_transaction_quantity)\r\n                FROM\r\n                    inv.mtl_onhand_quantities_detail moqd\r\n                WHERE\r\n                        moqd.inventory_item_id = mkc.inventory_item_id\r\n                    AND moqd.subinventory_code = mkc.source_subinventory\r\n                    AND mkc.organization_id = moqd.organization_id\r\n            ) > 0 THEN\r\n                'Late Delivery'\r\n        END\r\n    ) intra_org_card_exception,\r\n    (\r\n        CASE\r\n            WHEN mkc.supply_status_name IN (\r\n                'Empty',\r\n                'In Process'\r\n            )\r\n                 AND mkc.source_type_meaning = 'Inter Org'\r\n                 AND ( sysdate - (\r\n                SELECT\r\n                    MAX(kca.creation_date)\r\n                FROM\r\n                    apps.mtl_kanban_card_activity kca\r\n                WHERE\r\n                    kca.supply_status IN (\r\n                        4,\r\n                        5\r\n                    )\r\n                    AND kca.kanban_card_id = mkc.kanban_card_id\r\n            ) ) > 0.5\r\n                 AND (\r\n                SELECT\r\n                    COUNT(ms.req_line_id)\r\n                FROM\r\n                    inv.mtl_supply                 ms,\r\n                    po.po_requisition_lines_all    prla\r\n                WHERE\r\n                        prla.requisition_line_id = ms.req_line_id\r\n                    AND prla.kanban_card_id = mkc.kanban_card_id\r\n                    AND ms.to_organization_id = mkc.organization_id\r\n            ) <= 0 THEN\r\n                'Missing Supply'\r\n            WHEN mkc.supply_status_name = 'In Process'\r\n                 AND mkc.source_type_meaning = 'Inter Org'\r\n                 AND (\r\n                SELECT\r\n                    MIN(ms.receipt_date)\r\n                FROM\r\n                    inv.mtl_supply                 ms,\r\n                    po.po_requisition_lines_all    prla\r\n                WHERE\r\n                        prla.requisition_line_id = ms.req_line_id\r\n                    AND prla.kanban_card_id = mkc.kanban_card_id\r\n                    AND ms.to_organization_id = mkc.organization_id\r\n            ) < sysdate + 4 THEN\r\n                'Late Delivery'\r\n        END\r\n    ) inter_org_card_exception,\r\n    (\r\n        CASE\r\n            WHEN mkc.supply_status_name IN (\r\n                'In Process',\r\n                'Empty'\r\n            )\r\n                 AND mkc.source_type_meaning = 'Supplier'\r\n                 AND ( sysdate - (\r\n                SELECT\r\n                    MAX(kca.creation_date)\r\n                FROM\r\n                    apps.mtl_kanban_card_activity kca\r\n                WHERE\r\n                    kca.supply_status IN (\r\n                        4,\r\n                        5\r\n                    )\r\n                    AND kca.kanban_card_id = mkc.kanban_card_id\r\n            ) ) > 0.5\r\n                 AND ( (\r\n                SELECT\r\n                    COUNT(pda.po_distribution_id)\r\n                FROM\r\n                    inv.mtl_supply             ms,\r\n                    po.po_distributions_all    pda\r\n                WHERE\r\n                        pda.po_distribution_id = ms.po_distribution_id\r\n                    AND pda.kanban_card_id = mkc.kanban_card_id\r\n            ) + (\r\n                SELECT\r\n                    COUNT(prla.requisition_line_id)\r\n                FROM\r\n                    inv.mtl_supply                 ms,\r\n                    po.po_requisition_lines_all    prla\r\n                WHERE\r\n                        prla.requisition_line_id = ms.req_line_id\r\n                    AND prla.kanban_card_id = mkc.kanban_card_id\r\n            ) ) <= 0 THEN\r\n                'Missing Supply'\r\n            WHEN mkc.supply_status_name = 'In Process'\r\n                 AND mkc.source_type_meaning = 'Supplier'\r\n                 AND ( sysdate - (\r\n                SELECT\r\n                    MAX(kca.creation_date)\r\n                FROM\r\n                    apps.mtl_kanban_card_activity kca\r\n                WHERE\r\n                    kca.supply_status IN (\r\n                        5\r\n                    )\r\n                    AND kca.kanban_card_id = mkc.kanban_card_id\r\n            ) ) > msi.preprocessing_lead_time\r\n                 AND (\r\n                SELECT\r\n                    COUNT(pda.po_distribution_id)\r\n                FROM\r\n                    inv.mtl_supply             ms,\r\n                    po.po_distributions_all    pda\r\n                WHERE\r\n                        pda.po_distribution_id = ms.po_distribution_id\r\n                    AND pda.kanban_card_id = mkc.kanban_card_id\r\n            ) <= 0 THEN\r\n                'Late To Process'\r\n            WHEN mkc.supply_status_name = 'In Process'\r\n                 AND mkc.source_type_meaning = 'Supplier'\r\n                 AND (\r\n                SELECT\r\n                    MIN(ms.receipt_date)\r\n                FROM\r\n                    inv.mtl_supply             ms,\r\n                    po.po_distributions_all    pda\r\n                WHERE\r\n                        pda.po_distribution_id = ms.po_distribution_id\r\n                    AND pda.kanban_card_id = mkc.kanban_card_id\r\n            ) < sysdate + 1 THEN\r\n                'Late Delivery'\r\n        END\r\n    ) supplier_card_exception,\r\n    (\r\n        CASE\r\n            WHEN mkc.supply_status_name = 'In Process'\r\n                 AND mkc.source_type_meaning = 'Production'\r\n                 AND (\r\n                SELECT\r\n                    COUNT(wdj.wip_entity_id)\r\n                FROM\r\n                    apps.wip_discrete_jobs wdj\r\n                WHERE\r\n                        wdj.kanban_card_id = mkc.kanban_card_id\r\n                    AND wdj.organization_id = mp.organization_id\r\n                    AND wdj.status_type IN (\r\n                        1-- 'Released',\r\n                        ,\r\n                        3-- 'Unreleased'\r\n                    )\r\n            ) < 0 THEN\r\n                'Missing Supply'\r\n            WHEN mkc.supply_status_name = 'In Process'\r\n                 AND mkc.source_type_meaning = 'Production'\r\n                 AND trunc(sysdate + 1) > (\r\n                SELECT\r\n                    MIN(wdj.scheduled_completion_date)\r\n                FROM\r\n                    apps.wip_discrete_jobs wdj\r\n                WHERE\r\n                        wdj.kanban_card_id = mkc.kanban_card_id\r\n                    AND wdj.organization_id = mp.organization_id\r\n                    AND wdj.status_type IN (\r\n                        1-- 'Released',\r\n                        ,\r\n                        3-- 'Unreleased'\r\n                    )\r\n            ) THEN\r\n                'Late Delivery'\r\n        END\r\n    ) production_card_exception,\r\n    mkc.card_status_name\r\nFROM\r\n    apps.mtl_kanban_cards_v             mkc,\r\n    inv.mtl_parameters                  mp,\r\n    inv.mtl_system_items_b              msi,\r\n    apps.mtl_kanban_pull_sequences_v    mkp\r\nWHERE\r\n    mp.organization_id = mkc.organization_id\r\n    AND mp.organization_code = '\"&ORG&\"'\r\n    AND msi.inventory_item_id = mkc.inventory_item_id\r\n    AND msi.organization_id = mkc.organization_id\r\n    and mkc.organization_id = mkp.organization_id (+)\r\n    and mkc.inventory_item_id = mkp.inventory_item_id(+)\r\n    AND mkc.pull_sequence_id = mkp.pull_sequence_id (+)\r\n    \", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Inserted conditional column\" = Table.AddColumn(Source, \"KANBAN_CARD_EXCEPTION\", each if [INTRA_ORG_CARD_EXCEPTION] <> null then [INTRA_ORG_CARD_EXCEPTION] else if [INTER_ORG_CARD_EXCEPTION] <> null then [INTER_ORG_CARD_EXCEPTION] else if [SUPPLIER_CARD_EXCEPTION] <> null then [SUPPLIER_CARD_EXCEPTION] else if [PRODUCTION_CARD_EXCEPTION] <> null then [PRODUCTION_CARD_EXCEPTION] else if [KANBAN_TRIGGER_EXCEPTION] <> null then [KANBAN_TRIGGER_EXCEPTION] else \"Normal\"),\r\n  #\"Choose columns\" = Table.SelectColumns(#\"Inserted conditional column\", {\"EXTRACT_DATE\", \"LOCAL_EXTRACT_DATE\", \"ORGANIZATION_CODE\", \"KANBAN_CARD_ID\", \"KANBAN_CARD_NUMBER\", \"CREATION_DATE\", \"INVENTORY_ITEM_ID\", \"ITEM_NUMBER\", \"PULL_SEQUENCE_ID\", \"KANBAN_LEAD_TIME\", \"PULL_SEQUENCE_LEAD_TIME\", \"SUBINVENTORY_NAME\", \"KANBAN_LOCATOR\", \"SOURCE_ORG_CODE\", \"SOURCE_SUBINVENTORY\", \"SOURCE_LOCATOR\", \"KANBAN_CARD_TYPE\", \"KANBAN_SIZE\", \"KANBAN_SOURCE_TYPE\", \"KANBAN_SUPPLY_STATUS\", \"SUPPLY_STATUS_ID\", \"KANBAN_LAST_REPLENISH\", \"KANBAN_REPLENISH_COUNT\", \"KANBAN_LAST_REPLENISH_BY\", \"KANBAN_LAST_EMPTY\", \"KANBAN_LAST_EMPTY_BY\", \"KANBAN_ACTIVITY_AGE_DAYS\", \"KANBAN_SOURCE_ONHAND\", \"KANBAN_ONHAND\", \"ITEM_COST\", \"CARD_STATUS_NAME\", \"KANBAN_CARD_EXCEPTION\"}),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Choose columns\", {{\"KANBAN_CARD_NUMBER\", \"Card Number\"}, {\"ITEM_NUMBER\", \"Item Number\"}, {\"PULL_SEQUENCE_ID\", \"Pull Sequence Id\"}, {\"SUBINVENTORY_NAME\", \"Subinventory\"}, {\"KANBAN_LOCATOR\", \"Locator\"}, {\"KANBAN_CARD_TYPE\", \"Card Type\"}, {\"KANBAN_SIZE\", \"Card Size\"}, {\"KANBAN_SOURCE_TYPE\", \"Source Type\"}, {\"KANBAN_SUPPLY_STATUS\", \"Supply Status\"}, {\"EXTRACT_DATE\", \"Extract Date\"}, {\"CREATION_DATE\", \"Creation Date\"}, {\"SOURCE_ORG_CODE\", \"Source Org\"}, {\"KANBAN_REPLENISH_COUNT\", \"Replenish Count\"}, {\"KANBAN_LAST_REPLENISH\", \"Last Replenish Date\"}, {\"KANBAN_LAST_EMPTY\", \"Last Empty Date\"}, {\"KANBAN_ACTIVITY_AGE_DAYS\", \"Last Activity Age Days\"}, {\"KANBAN_SOURCE_ONHAND\", \"Source Onhand\"}, {\"SOURCE_SUBINVENTORY\", \"Source Subinventory\"}, {\"KANBAN_CARD_EXCEPTION\", \"Exception\"}, {\"KANBAN_LEAD_TIME\", \"Effective Lead Time\"}, {\"KANBAN_ONHAND\", \"Onhand Quantity\"}, {\"ORGANIZATION_CODE\", \"Organization Code\"}, {\"CARD_STATUS_NAME\", \"Card Status\"}, {\"PULL_SEQUENCE_LEAD_TIME\", \"Pull Sequence Lead Time\"}, {\"LOCAL_EXTRACT_DATE\", \"Local Extract Date\"}, {\"KANBAN_LAST_REPLENISH_BY\", \"Kanban Last Replenish By\"}, {\"KANBAN_LAST_EMPTY_BY\", \"Kanban Last Empty By\"}, {\"SOURCE_LOCATOR\", \"Source Locator\"}}),\r\n  #\"Transform columns\" = Table.TransformColumnTypes(#\"Renamed columns\", {{\"Exception\", type text}}),\r\n  #\"Replace errors\" = Table.ReplaceErrorValues(#\"Transform columns\", {{\"Exception\", null}})\r\nin\r\n  #\"Replace errors\";\r\nshared Onhand = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true,\r\n    Query=\"\r\n    SELECT\r\n    sysdate extract_date,\r\n    from_tz(cast (sysdate as timestamp),'PST') at time zone '\"&LocalTZ&\"' local_extract_date,\r\n    mp.organization_code,\r\n    msi.inventory_item_id,\r\n    msi.segment1,\r\n    moqd.primary_transaction_quantity,\r\n    decode(moqd.is_consigned, 1, 'Yes', 2, 'No')             consigned_flag,\r\n    (\r\n    SELECT\r\n    mloc.concatenated_segments\r\n    FROM\r\n    apps.mtl_item_locations_kfv mloc\r\n    WHERE\r\n    mloc.inventory_location_id = moqd.locator_id\r\n    AND mloc.organization_id = moqd.organization_id\r\n    AND moqd.subinventory_code = mloc.subinventory_code\r\n    ) locator,\r\n    pv.vendor_name,\r\n    pvs.vendor_site_code,\r\n    pv.vendor_id,\r\n    pvs.vendor_site_id,\r\n    moqd.date_received,\r\n    (\r\n    SELECT\r\n    item_cost\r\n    FROM\r\n    apps.cst_item_costs cic\r\n    WHERE\r\n    cic.cost_type_id = 1\r\n    AND cic.inventory_item_id = moqd.inventory_item_id\r\n    AND cic.organization_id = moqd.organization_id\r\n    ) item_cost,\r\n    moqd.subinventory_code,\r\n    decode(mseci.asset_inventory, 1, 'Yes', 'No')            asset_subinventory_flag,\r\n    decode(mseci.availability_type, 1, 'Yes', 'No')          nettable_subinventory_flag,\r\n    mseci.attribute1                                         subinventory_classification,\r\n    (\r\n    SELECT\r\n    mmt.transaction_reference\r\n    FROM\r\n    apps.mtl_material_transactions mmt\r\n    WHERE\r\n    mmt.organization_id = moqd.organization_id\r\n    AND moqd.create_transaction_id = mmt.transaction_id\r\n    AND mmt.inventory_item_id = moqd.inventory_item_id\r\n    ) transaction_reference\r\n    FROM\r\ninv.mtl_onhand_quantities_detail    moqd,\r\ninv.mtl_parameters                  mp,\r\ninv.mtl_system_items_b              msi,\r\n    apps.po_vendors                     pv,\r\n    apps.po_vendor_sites_all            pvs,\r\n    apps.mtl_secondary_inventories      mseci\r\n    WHERE\r\n    1 = 1\r\n    AND moqd.owning_organization_id = pvs.vendor_site_id (+)\r\n    AND pvs.vendor_id = pv.vendor_id (+)\r\n    AND mp.organization_id = moqd.organization_id\r\n    AND moqd.inventory_item_id = msi.inventory_item_id\r\n    AND moqd.organization_id = msi.organization_id\r\n    AND mseci.organization_id = moqd.organization_id\r\n    AND mseci.secondary_inventory_name = moqd.subinventory_code\r\n    AND mp.organization_code = '\"&ORG&\"'\r\n    \", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"EXTRACT_DATE\", \"Extract Date\"}, {\"SEGMENT1\", \"Item Number\"}, {\"PRIMARY_TRANSACTION_QUANTITY\", \"Quantity\"}, {\"CONSIGNED_FLAG\", \"Consigned Flag\"}, {\"LOCATOR\", \"Locator\"}, {\"VENDOR_NAME\", \"Owning Supplier Name\"}, {\"VENDOR_SITE_CODE\", \"Owning Supplier Site Code\"}, {\"DATE_RECEIVED\", \"Date Received\"}, {\"SUBINVENTORY_CODE\", \"Subinventory\"}, {\"ORGANIZATION_CODE\", \"Organization Code\"}, {\"ASSET_SUBINVENTORY_FLAG\", \"Asset Subinventory Flag\"}, {\"NETTABLE_SUBINVENTORY_FLAG\", \"Nettable Subinventory Flag\"}, {\"SUBINVENTORY_CLASSIFICATION\", \"Subinventory Classification\"}, {\"TRANSACTION_REFERENCE\", \"Transaction Reference\"}, {\"LOCAL_EXTRACT_DATE\", \"Local Extract Date\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Open_Supply = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true,\r\n    Query=\"\r\n    SELECT\r\n    sysdate                       extract_date,\r\n    from_tz(CAST(sysdate AS TIMESTAMP), 'PST') AT TIME ZONE '\"&LocalTZ&\"'         local_extract_date,\r\n    msi.segment1                  item_number,\r\n    mp.organization_code,\r\n    msi.inventory_item_id,\r\n    (\r\n        SELECT\r\n            mp2.organization_code\r\n        FROM\r\n            inv.mtl_parameters mp2\r\n        WHERE\r\n            mp2.organization_id = ms.from_organization_id\r\n    ) source_org,\r\n    supply_type_code,\r\n    CASE\r\n        WHEN ms.supply_type_code = 'PO'           THEN\r\n            'On Order'\r\n        WHEN ms.supply_type_code = 'REQ'\r\n             AND ms.from_organization_id > 0 THEN\r\n            'On Order'\r\n        WHEN ms.supply_type_code = 'SHIPMENT'     THEN\r\n            'In Transit'\r\n        WHEN ms.supply_type_code = 'RECEIVING'    THEN\r\n            'Receiving'\r\n        WHEN ms.supply_type_code = 'REQ'\r\n             AND ms.from_organization_id IS NULL THEN\r\n            'Purchase Requisition'\r\n        ELSE\r\n            ms.supply_type_code\r\n    END supply_status,\r\n    ms.to_org_primary_quantity    supply_quantity,\r\n    CASE\r\n        WHEN supply_type_code = 'PO'   THEN\r\n            (\r\n                SELECT\r\n                    pha.vendor_site_id\r\n                FROM\r\n                    po.po_headers_all pha\r\n                WHERE\r\n                    pha.po_header_id = ms.po_header_id\r\n            )\r\n        WHEN supply_type_code = 'REQ'  THEN\r\n            CASE\r\n                WHEN (\r\n                    SELECT\r\n                        nvl(prla.vendor_site_id, 0)\r\n                    FROM\r\n                        po.po_requisition_lines_all prla\r\n                    WHERE\r\n                        prla.requisition_line_id = ms.req_line_id\r\n                ) = 0 THEN\r\n                    (\r\n                        SELECT\r\n                            pvs.vendor_site_id\r\n                        FROM\r\n                            po.po_requisition_lines_all    prla,\r\n                            apps.po_vendors                pv,\r\n                            apps.po_vendor_sites_all       pvs\r\n                        WHERE\r\n                                prla.requisition_line_id = ms.req_line_id\r\n                            AND prla.suggested_vendor_name\r\n                                || '_'\r\n                                || prla.suggested_vendor_location = pv.vendor_name\r\n                                                                    || '_'\r\n                                                                    || pvs.vendor_site_code\r\n                            AND pv.vendor_id = pvs.vendor_id\r\n                            AND pvs.org_id = prla.org_id\r\n                    )\r\n                ELSE\r\n                    (\r\n                        SELECT\r\n                            prla.vendor_site_id\r\n                        FROM\r\n                            po.po_requisition_lines_all prla\r\n                        WHERE\r\n                            prla.requisition_line_id = ms.req_line_id\r\n                    )\r\n            END\r\n    END vendor_site_id,\r\n    ms.creation_date,\r\n    CASE\r\n        WHEN ms.supply_type_code = 'PO' THEN\r\n            (\r\n                SELECT\r\n                    plla.need_by_date\r\n                FROM\r\n                    po.po_line_locations_all plla\r\n                WHERE\r\n                    plla.line_location_id = ms.po_line_location_id\r\n            )\r\n        ELSE\r\n            ms.need_by_date\r\n    END supply_need_by_date,\r\n    ms.receipt_date,\r\n    CASE\r\n        WHEN trunc(sysdate) + 1 > ms.receipt_date THEN\r\n            'Late'\r\n        ELSE\r\n            'In Process'\r\n    END delivery_status,\r\n    CASE\r\n        WHEN supply_type_code IN (\r\n            'PO',\r\n            'SHIPMENT'\r\n        )\r\n             AND ms.po_header_id > 0\r\n             AND ms.po_release_id IS NOT NULL THEN\r\n            (\r\n                SELECT\r\n                    pha.segment1\r\n                FROM\r\n                    po.po_headers_all pha\r\n                WHERE\r\n                    pha.po_header_id = ms.po_header_id\r\n            )\r\n            || '_'\r\n            || (\r\n                SELECT\r\n                    release_num\r\n                FROM\r\n                    po.po_releases_all pra\r\n                WHERE\r\n                    pra.po_release_id = ms.po_release_id\r\n            )\r\n        WHEN supply_type_code IN (\r\n            'PO',\r\n            'SHIPMENT'\r\n        )\r\n             AND ms.po_header_id > 0\r\n             AND ms.po_release_id IS NULL THEN\r\n            (\r\n                SELECT\r\n                    pha.segment1\r\n                FROM\r\n                    po.po_headers_all pha\r\n                WHERE\r\n                    pha.po_header_id = ms.po_header_id\r\n            )\r\n        WHEN supply_type_code IN (\r\n            'REQ',\r\n            'SHIPMENT'\r\n        )\r\n             AND ms.req_header_id > 0 THEN\r\n            (\r\n                SELECT\r\n                    prha.segment1\r\n                FROM\r\n                    po.po_requisition_headers_all prha\r\n                WHERE\r\n                    prha.requisition_header_id = ms.req_header_id\r\n            )\r\n        WHEN supply_type_code = 'RECEIVING' THEN\r\n            (\r\n                SELECT\r\n                    receipt_num\r\n                FROM\r\n                    po.rcv_shipment_headers rsh\r\n                WHERE\r\n                    rsh.shipment_header_id = ms.shipment_header_id\r\n            )\r\n    END supply_document_number,\r\n    CASE\r\n        WHEN supply_type_code IN (\r\n            'REQ',\r\n            'SHIPMENT'\r\n        ) THEN\r\n            (\r\n                SELECT\r\n                    oeh.order_number\r\n                FROM\r\n                    po.po_requisition_headers_all    prha,\r\n                    ont.oe_order_headers_all         oeh,\r\n                    po.po_requisition_lines_all      prla,\r\n                    ont.oe_order_lines_all           oel\r\n                WHERE\r\n                        prha.requisition_header_id = ms.req_header_id\r\n                    AND oel.header_id = oeh.header_id\r\n                    AND oel.source_document_line_id = prla.requisition_line_id\r\n                    AND ms.req_line_id = prla.requisition_line_id\r\n                    AND oeh.orig_sys_document_ref = prha.segment1\r\n                    AND ROWNUM = 1\r\n            )\r\n    END internal_order_number,\r\n    nvl(nvl(\r\n        CASE\r\n            WHEN req_line_id > 0 THEN\r\n                (\r\n                    SELECT\r\n                        CASE\r\n                            WHEN prha.interface_source_code = 'INV'\r\n                                 AND nvl(prla.kanban_card_id, 0) > 0 THEN\r\n                                CASE\r\n                                    WHEN(\r\n                                        SELECT\r\n                                            COUNT(1)\r\n                                        FROM\r\n                                            apps.mtl_kanban_cards mkc\r\n                                        WHERE\r\n                                                mkc.kanban_card_type = 1\r\n                                            AND prla.kanban_card_id = mkc.kanban_card_id\r\n                                    ) > 0 THEN\r\n                                        'Kanban'\r\n                                    ELSE\r\n                                        'NR Kanban'\r\n                                END\r\n                            WHEN prha.interface_source_code = 'INV'\r\n                                 AND nvl(prla.kanban_card_id, 0) = 0 THEN\r\n                                'Min Max'\r\n                            WHEN prha.interface_source_code = 'MSC'\r\n                                 AND nvl(prla.kanban_card_id, 0) = 0 THEN\r\n                                'MRP'\r\n                            WHEN prha.interface_source_code IS NULL\r\n                                 AND prha.approved_date IS NOT NULL\r\n                                 AND prla.item_id IS NULL THEN\r\n                                'iProcurement'\r\n                            WHEN prha.interface_source_code IS NULL\r\n                                 AND prha.approved_date IS NOT NULL THEN\r\n                                'Manual'\r\n                            WHEN prha.interface_source_code IS NOT NULL THEN\r\n                                prha.interface_source_code\r\n                            ELSE\r\n                                'Manual'\r\n                        END\r\n                    FROM\r\n                        apps.po_requisition_headers_all    prha, apps.po_requisition_lines_all      prla\r\n                    WHERE\r\n                            prha.requisition_header_id = prla.requisition_header_id\r\n                        AND prha.org_id = prla.org_id\r\n                        AND prla.item_id = ms.item_id\r\n                        AND prla.requisition_line_id = ms.req_line_id\r\n                )\r\n        END,\r\n        CASE\r\n            WHEN po_distribution_id > 0 THEN\r\n                (\r\n                    SELECT\r\n                        CASE\r\n                            WHEN prha.interface_source_code = 'INV'\r\n                                 AND nvl(prla.kanban_card_id, 0) > 0 THEN\r\n                                CASE\r\n                                    WHEN(\r\n                                        SELECT\r\n                                            COUNT(1)\r\n                                        FROM\r\n                                            apps.mtl_kanban_cards mkc\r\n                                        WHERE\r\n                                                mkc.kanban_card_type = 1\r\n                                            AND prla.kanban_card_id = mkc.kanban_card_id\r\n                                    ) > 0 THEN\r\n                                        'Kanban'\r\n                                    ELSE\r\n                                        'NR Kanban'\r\n                                END\r\n                            WHEN prha.interface_source_code = 'INV'\r\n                                 AND nvl(prla.kanban_card_id, 0) = 0 THEN\r\n                                'Min Max'\r\n                            WHEN prha.interface_source_code = 'MSC'\r\n                                 AND nvl(prla.kanban_card_id, 0) = 0 THEN\r\n                                'MRP'\r\n                            WHEN prha.interface_source_code IS NULL\r\n                                 AND prha.approved_date IS NOT NULL\r\n                                 AND prla.item_id IS NULL THEN\r\n                                'iProcurement'\r\n                            WHEN prha.interface_source_code IS NULL\r\n                                 AND prha.approved_date IS NOT NULL THEN\r\n                                'Manual'\r\n                            WHEN prha.interface_source_code IS NOT NULL THEN\r\n                                prha.interface_source_code\r\n                            ELSE\r\n                                'Manual'\r\n                        END\r\n                    FROM\r\n                        apps.po_requisition_headers_all    prha, apps.po_requisition_lines_all      prla, apps.po_req_distributions_all      prda,\r\n                        apps.po_distributions_all          pda\r\n                    WHERE\r\n                            prha.requisition_header_id = prla.requisition_header_id\r\n                        AND prha.org_id = prla.org_id\r\n                        AND prla.item_id = ms.item_id\r\n                        AND prda.requisition_line_id = prla.requisition_line_id\r\n                        AND pda.req_distribution_id = prda.distribution_id\r\n                        AND pda.po_distribution_id = ms.po_distribution_id\r\n                )\r\n        END\r\n    ), 'Manual') trigger_source,\r\n    nvl(\r\n        CASE\r\n            WHEN req_line_id > 0 THEN\r\n                (\r\n                    SELECT\r\n                        mkc.kanban_card_number\r\n                    FROM\r\n                        apps.po_requisition_headers_all    prha, apps.po_requisition_lines_all      prla, apps.mtl_kanban_cards              mkc\r\n                    WHERE\r\n                            prha.requisition_header_id = prla.requisition_header_id\r\n                        AND prha.org_id = prla.org_id\r\n                        AND prla.item_id = ms.item_id\r\n                        AND prla.requisition_line_id = ms.req_line_id\r\n                        AND mkc.kanban_card_id = prla.kanban_card_id\r\n                )\r\n        END,\r\n        CASE\r\n            WHEN po_distribution_id > 0 THEN\r\n                (\r\n                    SELECT\r\n                        mkc.kanban_card_number\r\n                    FROM\r\n                        apps.po_requisition_headers_all    prha, apps.po_requisition_lines_all      prla,\r\n                        apps.po_req_distributions_all      prda, apps.po_distributions_all          pda, apps.mtl_kanban_cards              mkc\r\n                    WHERE\r\n                            prha.requisition_header_id = prla.requisition_header_id\r\n                        AND prha.org_id = prla.org_id\r\n                        AND prla.item_id = ms.item_id\r\n                        AND prda.requisition_line_id = prla.requisition_line_id\r\n                        AND pda.req_distribution_id = prda.distribution_id\r\n                        AND pda.po_distribution_id = ms.po_distribution_id\r\n                        AND mkc.kanban_card_id = prla.kanban_card_id\r\n                )\r\n        END\r\n    ) kanban_card_number,\r\n    nvl(\r\n        CASE\r\n            WHEN req_line_id > 0 THEN\r\n                (\r\n                    SELECT\r\n                        mkc.kanban_card_id\r\n                    FROM\r\n                        apps.po_requisition_headers_all    prha, apps.po_requisition_lines_all      prla, apps.mtl_kanban_cards              mkc\r\n                    WHERE\r\n                            prha.requisition_header_id = prla.requisition_header_id\r\n                        AND prha.org_id = prla.org_id\r\n                        AND prla.item_id = ms.item_id\r\n                        AND prla.requisition_line_id = ms.req_line_id\r\n                        AND mkc.kanban_card_id = prla.kanban_card_id\r\n                )\r\n        END,\r\n        CASE\r\n            WHEN po_distribution_id > 0 THEN\r\n                (\r\n                    SELECT\r\n                        mkc.kanban_card_id\r\n                    FROM\r\n                        apps.po_requisition_headers_all    prha, apps.po_requisition_lines_all      prla,\r\n                        apps.po_req_distributions_all      prda, apps.po_distributions_all          pda, apps.mtl_kanban_cards              mkc\r\n                    WHERE\r\n                            prha.requisition_header_id = prla.requisition_header_id\r\n                        AND prha.org_id = prla.org_id\r\n                        AND prla.item_id = ms.item_id\r\n                        AND prda.requisition_line_id = prla.requisition_line_id\r\n                        AND pda.req_distribution_id = prda.distribution_id\r\n                        AND pda.po_distribution_id = ms.po_distribution_id\r\n                        AND mkc.kanban_card_id = prla.kanban_card_id\r\n                )\r\n        END\r\n    ) kanban_card_id,\r\n    ms.to_subinventory,\r\n    nvl((\r\n        SELECT\r\n            decode(plla.consigned_flag, 'Y', 'Yes', 'No')\r\n        FROM\r\n            apps.po_line_locations_all plla\r\n        WHERE\r\n            plla.line_location_id = ms.po_line_location_id\r\n    ), 'No') consigned_supply,\r\n    CASE\r\n        WHEN supply_type_code = 'REQ'  THEN\r\n            (\r\n                SELECT\r\n                    prla.item_revision\r\n                FROM\r\n                    apps.po_requisition_lines_all prla\r\n                WHERE\r\n                    prla.requisition_line_id = ms.req_line_id\r\n            )\r\n        WHEN supply_type_code = 'PO'   THEN\r\n            (\r\n                SELECT\r\n                    pla.item_revision\r\n                FROM\r\n                    apps.po_lines_all pla\r\n                WHERE\r\n                    pla.po_line_id = ms.po_line_id\r\n            )\r\n        WHEN supply_type_code IN (\r\n            'RECEIVING',\r\n            'SHIPMENT'\r\n        ) THEN\r\n            (\r\n                SELECT\r\n                    rsl.item_revision\r\n                FROM\r\n                    apps.rcv_shipment_lines rsl\r\n                WHERE\r\n                    rsl.shipment_line_id = ms.shipment_line_id\r\n            )\r\n    END supply_item_revision\r\nFROM\r\n    inv.mtl_supply            ms,\r\n    inv.mtl_system_items_b    msi,\r\n    inv.mtl_parameters        mp\r\n    WHERE\r\n    1 = 1\r\n    AND msi.organization_id = ms.to_organization_id\r\n    AND msi.organization_id = mp.organization_id\r\n    AND msi.inventory_item_id = ms.item_id\r\n    AND mp.organization_code = '\"&ORG&\"'\r\n    \", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"EXTRACT_DATE\", \"Extract Date\"}, {\"CREATION_DATE\", \"Creation Date\"}, {\"ITEM_NUMBER\", \"Item Number\"}, {\"ORGANIZATION_CODE\", \"Organization Code\"}, {\"SOURCE_ORG\", \"Source Org Code\"}, {\"SUPPLY_TYPE_CODE\", \"Supply Type Code\"}, {\"SUPPLY_STATUS\", \"Status Code\"}, {\"SUPPLY_QUANTITY\", \"Quantity\"}, {\"SUPPLY_NEED_BY_DATE\", \"Need By Date\"}, {\"RECEIPT_DATE\", \"Expected Receipt Date\"}, {\"DELIVERY_STATUS\", \"Delivery Status\"}, {\"SUPPLY_DOCUMENT_NUMBER\", \"Document Number\"}, {\"INTERNAL_ORDER_NUMBER\", \"Internal Order Number\"}, {\"TRIGGER_SOURCE\", \"Trigger Source\"}, {\"KANBAN_CARD_NUMBER\", \"Kanban Card Number\"}, {\"TO_SUBINVENTORY\", \"To Subinventory\"}, {\"CONSIGNED_SUPPLY\", \"Consigned Supply\"}, {\"LOCAL_EXTRACT_DATE\", \"Local Extract Date\"}, {\"SUPPLY_ITEM_REVISION\", \"Supply Item Revision\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Cycle_Count_Activity = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, Query=\"\r\n    SELECT\r\n    sysdate extract_date,\r\n    from_tz(cast (sysdate as timestamp),'PST') at time zone '\"&LocalTZ&\"' local_extract_date,\r\n    al1.organization_code,\r\n    al3.cycle_count_header_name cycle_count_name,\r\n    al3.description cycle_count_description,\r\n    al3.disable_date,\r\n    al8.count_list_sequence,\r\n    al6.inventory_item_id,\r\n    al6.segment1 item_number,\r\n    al2.abc_class_name,\r\n    al8.subinventory,\r\n    al7.concatenated_segments locator,\r\n    al8.lot_number,\r\n    al8.serial_number,\r\n    al9.meaning count_status,\r\n    al8.creation_date,\r\n    al8.count_due_date,\r\n    al8.system_quantity_current,\r\n    al8.count_quantity_current,\r\n    al8.count_uom_current,\r\n    al8.count_date_current,\r\n    al10.full_name current_count_by,\r\n    al8.system_quantity_prior,\r\n    al8.count_quantity_prior,\r\n    al8.count_uom_prior,\r\n    al8.count_date_prior,\r\n    al12.full_name prior_count_by,\r\n    al8.system_quantity_first,\r\n    al8.count_quantity_first,\r\n    CASE\r\n    WHEN\r\n    al8.count_quantity_first IS NOT NULL\r\n    THEN\r\n    CASE\r\n    WHEN\r\n    (\r\n    nvl(al8.system_quantity_first, 0) - nvl(al8.count_quantity_first, 0)\r\n    )\r\n    <> 0\r\n    THEN\r\n    'Fail First Count'\r\n    ELSE\r\n    'Pass First Count'\r\n    END\r\n    ELSE\r\n    'Not Counted'\r\n    END\r\n    first_pass_status, al8.count_uom_first, al8.count_date_first, al13.full_name first_count_by, al8.adjustment_quantity,\r\n    CASE\r\n    WHEN\r\n    al8.count_quantity_first IS NOT NULL\r\n    THEN\r\n    CASE\r\n    WHEN\r\n    nvl(al8.adjustment_quantity, 0) <> 0\r\n    THEN\r\n    'Fail Count'\r\n    ELSE\r\n    'Pass Count'\r\n    END\r\n    ELSE\r\n    'Not Counted'\r\n    END\r\n    count_pass_status, al8.adjustment_date,\r\n    al8.adjustment_amount,\r\n    al11.user_name last_updated_by,\r\n    al8.approval_date count_approval_date\r\n    FROM\r\n    apps.mtl_parameters al1,\r\n    apps.mtl_abc_classes_all_v al2,\r\n    apps.mtl_cycle_count_headers_v al3,\r\n    apps.mtl_system_items_b al6,\r\n    apps.mtl_item_locations_kfv al7,\r\n    apps.mtl_cycle_count_entries_v al8,\r\n    apps.mfg_lookups al9,\r\n    apps.per_people_x al10,\r\n    apps.fnd_user al11,\r\n    apps.per_people_x al12,\r\n    apps.per_people_x al13\r\n    WHERE\r\n    al1.organization_code = '\"&ORG&\"'\r\n    AND al8.counted_by_employee_id_first = al13.person_id ( + )\r\n    AND al8.counted_by_employee_id_current = al10.person_id ( + )\r\n    AND al8.counted_by_employee_id_prior = al12.person_id ( + )\r\n    AND al8.last_updated_by = al11.user_id ( + )\r\n    AND al8.organization_id = al7.organization_id ( + )\r\n    AND al8.locator_id = al7.inventory_location_id ( + )\r\n    AND al8.cycle_count_header_id = al3.cycle_count_header_id\r\n    AND al8.inventory_item_id = al6.inventory_item_id\r\n    AND al8.organization_id = al6.organization_id\r\n    AND al8.entry_status_code = al9.lookup_code\r\n    AND al8.abc_class_id = al2.abc_class_id\r\n    AND al8.organization_id = al2.organization_id\r\n    AND al8.organization_id = al3.organization_id\r\n    AND al1.organization_id = al8.organization_id\r\n    AND al9.lookup_type = 'MTL_CC_ENTRY_STATUSES'\r\n    \", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"EXTRACT_DATE\", \"Extract Date\"}, {\"ORGANIZATION_CODE\", \"Organization Code\"}, {\"CYCLE_COUNT_NAME\", \"Cycle Count Name\"}, {\"CYCLE_COUNT_DESCRIPTION\", \"Cycle Count Description\"}, {\"DISABLE_DATE\", \"Disable Date\"}, {\"COUNT_LIST_SEQUENCE\", \"Sequence\"}, {\"ITEM_NUMBER\", \"Item Number\"}, {\"ABC_CLASS_NAME\", \"Count ABC Class\"}, {\"SUBINVENTORY\", \"Subinventory\"}, {\"LOCATOR\", \"Locator\"}, {\"LOT_NUMBER\", \"Lot Number\"}, {\"SERIAL_NUMBER\", \"Serial Number\"}, {\"COUNT_STATUS\", \"Count Status\"}, {\"CREATION_DATE\", \"Creation Date\"}, {\"COUNT_DUE_DATE\", \"Due Date\"}, {\"SYSTEM_QUANTITY_CURRENT\", \"System Quantity\"}, {\"COUNT_QUANTITY_CURRENT\", \"Count Quantity\"}, {\"COUNT_UOM_CURRENT\", \"Count Unit of Measure\"}, {\"COUNT_DATE_CURRENT\", \"Count Date\"}, {\"CURRENT_COUNT_BY\", \"Count By\"}, {\"SYSTEM_QUANTITY_PRIOR\", \"System Quantity Prior\"}, {\"COUNT_QUANTITY_PRIOR\", \"Count Quantity Prior\"}, {\"COUNT_UOM_PRIOR\", \"Count Unit of Measure Prior\"}, {\"COUNT_DATE_PRIOR\", \"Count Date Prior\"}, {\"PRIOR_COUNT_BY\", \"Count Prior By\"}, {\"SYSTEM_QUANTITY_FIRST\", \"First Count System Quantity\"}, {\"COUNT_QUANTITY_FIRST\", \"First Count Quantity\"}, {\"COUNT_UOM_FIRST\", \"First Count Unit of Measure\"}, {\"COUNT_DATE_FIRST\", \"First Count Date\"}, {\"FIRST_COUNT_BY\", \"First Count By\"}, {\"ADJUSTMENT_QUANTITY\", \"Adjustment Quantity\"}, {\"ADJUSTMENT_DATE\", \"Adjustment Date\"}, {\"FIRST_PASS_STATUS\", \"First Pass Status\"}, {\"COUNT_PASS_STATUS\", \"Count Pass Status\"}, {\"ADJUSTMENT_AMOUNT\", \"Adjustment Amount\"}, {\"LAST_UPDATED_BY\", \"Last Updated By\"}, {\"COUNT_APPROVAL_DATE\", \"Approval Date\"}, {\"LOCAL_EXTRACT_DATE\", \"Local Extract Date\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Serial_Status = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true,\r\n    Query=\"\r\n    SELECT\r\n    sysdate                                                                     extract_date,\r\n    from_tz(CAST(sysdate AS TIMESTAMP), 'PST') AT TIME ZONE '\"&LocalTZ&\"'         local_extract_date,\r\n    mp.organization_code,\r\n    (\r\n        SELECT\r\n            mp2.organization_code\r\n        FROM\r\n            apps.mtl_parameters mp2\r\n        WHERE\r\n            mp2.organization_id = msn.current_organization_id\r\n    ) current_organization,\r\n    ml.meaning                                                                  serial_number_status,\r\n    msi.inventory_item_id,\r\n    msi.segment1                                                                item_number,\r\n    msn.serial_number,\r\n    msn.completion_date,\r\n    msn.ship_date,\r\n    CASE\r\n        WHEN (\r\n            SELECT\r\n                COUNT(DISTINCT segment1)\r\n            FROM\r\n                apps.mtl_system_items_b      msi2,\r\n                apps.mtl_parameters          mp3,\r\n                apps.mtl_serial_numbers      msn2,\r\n                apps.mtl_object_genealogy    mog\r\n            WHERE\r\n                    msi2.organization_id = mp3.organization_id\r\n                AND mp3.organization_code = 'MAS'\r\n                AND msn2.gen_object_id = mog.parent_object_id\r\n                AND mog.object_id = msn.gen_object_id\r\n                AND mog.parent_object_type = 2\r\n                AND nvl(mog.end_date_active, sysdate + 1) > sysdate\r\n                AND msn2.inventory_item_id = msi2.inventory_item_id\r\n        ) > 1 THEN\r\n            'Multiple'\r\n        ELSE\r\n            (\r\n                SELECT DISTINCT\r\n                    segment1\r\n                FROM\r\n                    apps.mtl_system_items_b      msi2,\r\n                    apps.mtl_parameters          mp3,\r\n                    apps.mtl_serial_numbers      msn2,\r\n                    apps.mtl_object_genealogy    mog\r\n                WHERE\r\n                        msi2.organization_id = mp3.organization_id\r\n                    AND mp3.organization_code = 'MAS'\r\n                    AND msn2.gen_object_id = mog.parent_object_id\r\n                    AND mog.object_id = msn.gen_object_id\r\n                    AND mog.parent_object_type = 2\r\n                    AND nvl(mog.end_date_active, sysdate + 1) > sysdate\r\n                    AND msn2.inventory_item_id = msi2.inventory_item_id\r\n            )\r\n    END parent_item,\r\n    CASE\r\n        WHEN (\r\n            SELECT\r\n                COUNT(DISTINCT msn2.serial_number)\r\n            FROM\r\n                apps.mtl_system_items_b      msi2,\r\n                apps.mtl_parameters          mp3,\r\n                apps.mtl_serial_numbers      msn2,\r\n                apps.mtl_object_genealogy    mog\r\n            WHERE\r\n                    msi2.organization_id = mp3.organization_id\r\n                AND mp3.organization_code = 'MAS'\r\n                AND msn2.gen_object_id = mog.parent_object_id\r\n                AND mog.object_id = msn.gen_object_id\r\n                AND mog.parent_object_type = 2\r\n                AND nvl(mog.end_date_active, sysdate + 1) > sysdate\r\n                AND msn2.inventory_item_id = msi2.inventory_item_id\r\n        ) > 1 THEN\r\n            'Multiple'\r\n        ELSE\r\n            (\r\n                SELECT DISTINCT\r\n                    msn2.serial_number\r\n                FROM\r\n                    apps.mtl_system_items_b      msi2,\r\n                    apps.mtl_parameters          mp3,\r\n                    apps.mtl_serial_numbers      msn2,\r\n                    apps.mtl_object_genealogy    mog\r\n                WHERE\r\n                        msi2.organization_id = mp3.organization_id\r\n                    AND mp3.organization_code = 'MAS'\r\n                    AND msn2.gen_object_id = mog.parent_object_id\r\n                    AND mog.object_id = msn.gen_object_id\r\n                    AND mog.parent_object_type = 2\r\n                    AND nvl(mog.end_date_active, sysdate + 1) > sysdate\r\n                    AND msn2.inventory_item_id = msi2.inventory_item_id\r\n            )\r\n    END parent_serial_number,\r\n    current_subinventory_code,\r\n    (\r\n        SELECT\r\n            concatenated_segments\r\n        FROM\r\n            apps.mtl_item_locations_kfv mil\r\n        WHERE\r\n                mil.inventory_location_id = msn.current_locator_id\r\n            AND msn.current_organization_id = mil.organization_id\r\n            AND msn.current_subinventory_code = mil.subinventory_code\r\n    ) current_locator,\r\n    (\r\n        SELECT\r\n            wip_entity_name\r\n        FROM\r\n            apps.wip_entities we\r\n        WHERE\r\n            we.wip_entity_id = msn.original_wip_entity_id\r\n    ) original_job_number,\r\n    (\r\n        SELECT\r\n            mp4.organization_code\r\n        FROM\r\n            apps.wip_entities      we,\r\n            apps.mtl_parameters    mp4\r\n        WHERE\r\n                we.wip_entity_id = msn.original_wip_entity_id\r\n            AND mp4.organization_id = we.organization_id\r\n    ) original_job_org,\r\n    (\r\n        SELECT\r\n            tst.transaction_source_type_name\r\n        FROM\r\n            inv.mtl_txn_source_types tst\r\n        WHERE\r\n            tst.transaction_source_type_id = msn.last_txn_source_type_id\r\n    ) last_transaction_source,\r\n    msn.last_txn_source_name,\r\n    CASE\r\n        WHEN msn.last_txn_source_type_id = 1     THEN\r\n            (\r\n                SELECT\r\n                    pha.segment1\r\n                FROM\r\n                    apps.po_headers_all pha\r\n                WHERE\r\n                    pha.po_header_id = msn.last_txn_source_id\r\n            )\r\n        WHEN msn.last_txn_source_type_id = 2     THEN\r\n            (\r\n                SELECT\r\n                    segment1\r\n                FROM\r\n                    apps.mtl_sales_orders\r\n                WHERE\r\n                    sales_order_id = msn.last_txn_source_id\r\n            )\r\n        WHEN msn.last_txn_source_type_id = 4     THEN\r\n            (\r\n                SELECT\r\n                    request_number\r\n                FROM\r\n                    apps.mtl_txn_request_headers mtrh\r\n                WHERE\r\n                        mtrh.header_id = msn.last_txn_source_id\r\n                    AND mtrh.organization_id = msn.current_organization_id\r\n            )\r\n        WHEN msn.last_txn_source_type_id = 5     THEN\r\n            (\r\n                SELECT\r\n                    wip_entity_name\r\n                FROM\r\n                    apps.wip_entities\r\n                WHERE\r\n                    wip_entity_id = msn.last_txn_source_id\r\n            )\r\n        WHEN msn.last_txn_source_type_id = 6     THEN\r\n            (\r\n                SELECT\r\n                    segment1\r\n                FROM\r\n                    apps.mtl_generic_dispositions mgd\r\n                WHERE\r\n                    mgd.disposition_id = msn.last_txn_source_id\r\n            )\r\n        WHEN msn.last_txn_source_type_id = 7     THEN\r\n            (\r\n                SELECT\r\n                    rcv.shipment_num\r\n                FROM\r\n                    apps.rcv_shipment_headers    rcv,\r\n                    apps.rcv_transactions        rcvt\r\n                WHERE\r\n                        rcv.shipment_header_id = rcvt.shipment_header_id\r\n                    AND rcvt.transaction_id = msn.last_txn_source_id\r\n            )\r\n        WHEN msn.last_txn_source_type_id = 8     THEN\r\n            (\r\n                SELECT\r\n                    segment1\r\n                FROM\r\n                    apps.mtl_sales_orders\r\n                WHERE\r\n                    sales_order_id = msn.last_txn_source_id\r\n            )\r\n        WHEN msn.last_txn_source_type_id = 10    THEN\r\n            (\r\n                SELECT\r\n                    physical_inventory_name\r\n                FROM\r\n                    apps.mtl_physical_inventories\r\n                WHERE\r\n                    physical_inventory_id = msn.last_txn_source_id\r\n            )\r\n        WHEN msn.last_txn_source_type_id = 13    THEN\r\n            (\r\n                SELECT\r\n                    wip_entity_name\r\n                FROM\r\n                    apps.wip_entities\r\n                WHERE\r\n                    wip_entity_id = msn.last_txn_source_id\r\n            )\r\n        ELSE\r\n            NULL\r\n    END last_txn_source_document,\r\n    msn.reservation_id,\r\n    (\r\n        SELECT\r\n            receipt_num\r\n        FROM\r\n            apps.rcv_shipment_headers    rsh,\r\n            apps.rcv_transactions        rt\r\n        WHERE\r\n                rsh.shipment_header_id = rt.shipment_header_id\r\n            AND rt.organization_id = mp.organization_id\r\n            AND rt.source_document_code = 'PO'\r\n            AND rt.transaction_id = (\r\n                SELECT\r\n                    MAX(rst2.transaction_id)\r\n                FROM\r\n                    apps.rcv_serial_transactions    rst2,\r\n                    apps.rcv_shipment_lines         rsl\r\n                WHERE\r\n                        usage_status_code = 'CURRENT'\r\n                    AND rsl.shipment_line_id = rst2.shipment_line_id\r\n                    AND rsl.source_document_code = 'PO'\r\n                    AND rst2.serial_transaction_type = 'TRANSACTION'\r\n                    AND rsl.item_id = msn.inventory_item_id\r\n                    AND rst2.serial_num = msn.serial_number\r\n            )\r\n    ) last_receipt_number,\r\n    (\r\n        SELECT\r\n            receipt_num\r\n        FROM\r\n            apps.rcv_shipment_headers    rsh,\r\n            apps.rcv_transactions        rt\r\n        WHERE\r\n                rsh.shipment_header_id = rt.shipment_header_id\r\n            AND rt.organization_id = mp.organization_id\r\n            AND rt.source_document_code = 'PO'\r\n            AND rt.transaction_id = (\r\n                SELECT\r\n                    MAX(rst2.transaction_id)\r\n                FROM\r\n                    apps.rcv_serial_transactions    rst2,\r\n                    apps.rcv_shipment_lines         rsl\r\n                WHERE\r\n                        usage_status_code = 'CURRENT'\r\n                    AND rsl.shipment_line_id = rst2.shipment_line_id\r\n                    AND rsl.source_document_code = 'PO'\r\n                    AND rst2.serial_transaction_type = 'TRANSACTION'\r\n                    AND rsl.item_id = msn.inventory_item_id\r\n                    AND rst2.serial_num = msn.serial_number\r\n            )\r\n    ) last_po_receipt_number\r\nFROM\r\n    apps.mtl_serial_numbers    msn,\r\n    apps.mtl_system_items_b    msi,\r\n    apps.mtl_parameters        mp,\r\n    apps.mfg_lookups           ml\r\nWHERE\r\n        msi.inventory_item_id = msn.inventory_item_id\r\n    AND msi.organization_id = mp.organization_id\r\n    AND ml.lookup_code = msn.current_status\r\n    AND ml.lookup_type = 'SERIAL_NUM_STATUS'\r\n    AND msn.current_status <> 1\r\n    AND mp.organization_code = '\"&ORG&\"'\r\n    AND EXISTS (\r\n        SELECT\r\n            1\r\n        FROM\r\n            apps.mtl_unit_transactions mut\r\n        WHERE\r\n                mut.organization_id = mp.organization_id\r\n            AND mut.inventory_item_id = msn.inventory_item_id\r\n            AND mut.serial_number = msn.serial_number\r\n    )\r\n    \"\r\n    , CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"EXTRACT_DATE\", \"Extract Date\"}, {\"ORGANIZATION_CODE\", \"Organization Code\"}, {\"CURRENT_ORGANIZATION\", \"Current Organization Code\"}, {\"SERIAL_NUMBER_STATUS\", \"Serial Status\"}, {\"ITEM_NUMBER\", \"Item Number\"}, {\"SERIAL_NUMBER\", \"Serial Number\"}, {\"COMPLETION_DATE\", \"WIP Completion Date\"}, {\"SHIP_DATE\", \"Shipped Date\"}, {\"PARENT_ITEM\", \"Parent Item Number\"}, {\"PARENT_SERIAL_NUMBER\", \"Parent Serial Number\"}, {\"CURRENT_SUBINVENTORY_CODE\", \"Current Subinventory\"}, {\"CURRENT_LOCATOR\", \"Current Locator\"}, {\"ORIGINAL_JOB_NUMBER\", \"Original Job Number\"}, {\"ORIGINAL_JOB_ORG\", \"Original Job Organization\"}, {\"LAST_TRANSACTION_SOURCE\", \"Last Transaction Source\"}, {\"LAST_TXN_SOURCE_NAME\", \"Last Transaction Source Name\"}, {\"LAST_TXN_SOURCE_DOCUMENT\", \"Last Transaction Source Document\"}, {\"LAST_RECEIPT_NUMBER\", \"Last Receipt Number\"}, {\"LAST_PO_RECEIPT_NUMBER\", \"Last PO Receipt Number\"}, {\"LOCAL_EXTRACT_DATE\", \"Local Extract Date\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Receiving_Default = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, Query=\"\r\n    SELECT\r\n    sysdate extract_date,\r\n    from_tz(cast (sysdate as timestamp),'PST') at time zone '\"&LocalTZ&\"' local_extract_date,\r\n    mp.organization_code,\r\n    msi.inventory_item_id,\r\n    msi.segment1           ITEM_NUMBER,\r\n    MISD.subinventory_code DEFAULT_RECEIVING_SUBINVENTORY\r\n    ,\r\n    (SELECT MILK.concatenated_segments\r\n    FROM   apps.mtl_item_locations_kfv milk\r\n    WHERE  milk.inventory_location_id = mild.locator_id\r\n    AND milk.organization_id = mild.organization_id\r\n    AND milk.subinventory_code = mild.subinventory_code)\r\n    DEFAULT_RECEIVING_LOCATOR,\r\n    CASE\r\n    WHEN MSECI.locator_type = 2\r\n    AND MILD.locator_id IS NULL THEN 'Incomplete'\r\n    ELSE 'Complete'\r\n    END                    DEFAULT_RECEIVING_VALIDATION\r\n    FROM   apps.mtl_item_sub_defaults misd,\r\ninv.mtl_parameters mp,\r\ninv.mtl_system_items_b msi,\r\ninv.mtl_item_loc_defaults mild,\r\ninv.mtl_secondary_inventories MSECI\r\n    WHERE  1=1\r\n    AND mp.organization_id = misd.organization_id\r\n    AND msi.organization_id = mp.organization_id\r\n    AND mseci.organization_id = MISD.organization_id\r\n    AND mseci.secondary_inventory_name = MISD.subinventory_code\r\n    AND msi.inventory_item_id = misd.inventory_item_id\r\n    AND msi.inventory_item_id = mild.inventory_item_id (+)\r\n    AND msi.organization_id = mild.organization_id (+)\r\n    AND misd.subinventory_code = mild.subinventory_code (+)\r\n    AND misd.default_type = mild.default_type (+)\r\n    AND misd.default_type = 2\r\n    AND mp.organization_code = '\"&ORG&\"'\r\n    \", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"EXTRACT_DATE\", \"Extract Date\"}, {\"ORGANIZATION_CODE\", \"Organization Code\"}, {\"ITEM_NUMBER\", \"Item Number\"}, {\"DEFAULT_RECEIVING_SUBINVENTORY\", \"Default Receiving Subinventory\"}, {\"DEFAULT_RECEIVING_LOCATOR\", \"Default Receiving Locator\"}, {\"DEFAULT_RECEIVING_VALIDATION\", \"Default Receiving Validation\"}, {\"LOCAL_EXTRACT_DATE\", \"Local Extract Date\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Consumption_Advice = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true,\r\n    Query=\"\r\n    SELECT\r\n    sysdate extract_date,\r\n    from_tz(cast (sysdate as timestamp),'PST') at time zone '\"&LocalTZ&\"' local_extract_date,\r\n    mp.organization_code,\r\n    mmt.transaction_id,\r\n    pha.vendor_id,\r\n    pha.vendor_site_id,\r\n    pla.item_id,\r\n    msi.segment1                      item_number,\r\n    msi.description                   item_description,\r\n    'VENDOR'                          source_code,\r\n    'PO'                              source_document,\r\n    'No'                              consigned_flag,\r\n    CASE\r\n    WHEN nvl(mct.consumption_release_id, 0) = 0        THEN\r\n    pha.segment1\r\n    WHEN nvl(mct.consumption_release_id, 0) > 0        THEN\r\n    pha.segment1\r\n    || '_'\r\n    || (\r\n    SELECT\r\n    release_num\r\n    FROM\r\n    apps.po_releases_all pra\r\n    WHERE\r\n    pra.po_release_id = mct.consumption_release_id\r\n    )\r\n    END source_document_number,\r\n    mmt.transaction_date,\r\n    mmt.transaction_quantity * - 1    quantity,\r\n    uom.unit_of_measure,\r\n    mmt.primary_quantity * - 1        primary_quantity,\r\n    pda.line_location_id              po_line_location_id,\r\n    mct.po_distribution_id,\r\n    mtt.transaction_type_name         transaction_type,\r\n    'INVENTORY'                       po_destination_type,\r\n    pha.currency_code,\r\n    pla.line_num                      po_line,\r\n    (\r\n    SELECT\r\n    mmt2.actual_cost\r\n    FROM\r\n    apps.mtl_material_transactions mmt2\r\n    WHERE\r\n    mmt2.transaction_id = mmt.transfer_transaction_id\r\n    ) actual_cost,\r\n    plla.shipment_num                 po_shipment,\r\n    (\r\n    SELECT\r\n    rate_to_usd\r\n    FROM\r\n    xxdims.xx_budget_rate br\r\n    WHERE\r\n    br.currency_code = pha.currency_code\r\n    ) usd_budget_rate,\r\n    mct.blanket_price                 po_unit_price,\r\n    (\r\n    SELECT\r\n    meaning\r\n    FROM\r\n    apps.fnd_lookup_values flv\r\n    WHERE\r\n    flv.lookup_type = 'ITEM_TYPE'\r\n    AND flv.lookup_code = msi.item_type\r\n    AND language = 'US'\r\n    ) receipt_item_type,\r\n    (\r\n    SELECT\r\n    SUM(mta.base_transaction_value) * - 1\r\n    FROM\r\n    apps.mtl_transaction_accounts    mta,\r\n    apps.gl_code_combinations        gcc\r\n    WHERE\r\n    mta.reference_account = gcc.code_combination_id\r\n    AND gcc.segment3 = '20510'\r\n    AND mta.transaction_id = mmt.transfer_transaction_id\r\n    AND mta.organization_id = mmt.organization_id\r\n    ) ap_accrual,\r\n    gcc.concatenated_segments po_charge_account\r\n    FROM\r\n    apps.mtl_consumption_transactions    mct,\r\n    apps.po_distributions_all            pda,\r\n    apps.po_lines_all                    pla,\r\n    apps.po_line_locations_all           plla,\r\n    apps.po_headers_all                  pha,\r\n    apps.mtl_material_transactions       mmt,\r\n    apps.mtl_parameters                  mp,\r\n    apps.mtl_transaction_types           mtt,\r\n    apps.mtl_system_items_b              msi,\r\n    apps.mtl_units_of_measure_vl         uom,\r\n    apps.gl_code_combinations_kfv    gcc\r\n    WHERE\r\n    mct.transaction_id = mmt.transaction_id\r\n    AND mct.organization_id = mp.organization_id\r\n    AND mmt.organization_id = mmt.organization_id\r\n    AND mct.po_distribution_id = pda.po_distribution_id\r\n    AND pda.po_line_id = pla.po_line_id\r\n    AND pda.po_header_id = pha.po_header_id\r\n    AND uom.uom_code = mmt.transaction_uom\r\n    AND plla.po_line_id = pla.po_line_id\r\n    AND pda.line_location_id = plla.line_location_id\r\n    AND mp.organization_code = '\"&ORG&\"'\r\n    AND mtt.transaction_type_id = mmt.transaction_type_id\r\n    AND msi.inventory_item_id = mmt.inventory_item_id\r\n    AND msi.organization_id = mmt.organization_id\r\n    AND pda.code_combination_id = gcc.code_combination_id\r\n    \", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"EXTRACT_DATE\", \"Extract Date\"}, {\"ORGANIZATION_CODE\", \"Organization Code\"}, {\"ITEM_NUMBER\", \"Item Number\"}, {\"ITEM_DESCRIPTION\", \"Item Description\"}, {\"SOURCE_CODE\", \"Source Code\"}, {\"SOURCE_DOCUMENT\", \"Source Document\"}, {\"SOURCE_DOCUMENT_NUMBER\", \"Source Document Number\"}, {\"UNIT_OF_MEASURE\", \"Unit of Measure\"}, {\"PRIMARY_QUANTITY\", \"Primary Quantity\"}, {\"TRANSACTION_TYPE\", \"Transaction Type\"}, {\"CURRENCY_CODE\", \"Currency Code\"}, {\"PO_UNIT_PRICE\", \"PO Unit Price\"}, {\"TRANSACTION_DATE\", \"Transaction Date\"}, {\"QUANTITY\", \"Quantity\"}, {\"USD_BUDGET_RATE\", \"USD Budget Rate\"}, {\"CONSIGNED_FLAG\", \"Consigned Flag\"}, {\"PO_DESTINATION_TYPE\", \"PO Destination Type\"}, {\"PO_LINE\", \"PO Line\"}, {\"PO_SHIPMENT\", \"PO Shipment\"}, {\"ACTUAL_COST\", \"Actual Cost\"}, {\"RECEIPT_ITEM_TYPE\", \"Receipt Item Type\"}, {\"AP_ACCRUAL\", \"AP Accrual\"}, {\"PO_CHARGE_ACCOUNT\", \"PO Charge Account\"}, {\"LOCAL_EXTRACT_DATE\", \"Local Extract Date\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Open_WO = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true,\r\n    Query=\"\r\n    SELECT\r\n    sysdate                                                                        extract_date,\r\n    from_tz(CAST(sysdate AS TIMESTAMP), 'PST') AT TIME ZONE '\"&LocalTZ&\"'            local_extract_date,\r\n    mp.organization_code,\r\n    mkc.kanban_card_id,\r\n    mkc.kanban_card_number,\r\n    msi.inventory_item_id,\r\n    msi.segment1                                                                   item_number,\r\n    'WO'                                                                           supply_type_code,\r\n    we.wip_entity_name                                                             supply_document_number,\r\n    'On Order'                                                                     supply_status,\r\n    CASE\r\n        WHEN wdj.scheduled_completion_date < sysdate + 1 THEN\r\n            'Late'\r\n        ELSE\r\n            'In Process'\r\n    END delivery_status,\r\n    wdj.scheduled_completion_date                                                  receipt_date,\r\n    wdj.scheduled_completion_date                                                  supply_need_by_date,\r\n    wdj.creation_date                                                              creation_date,\r\n    ( wdj.start_quantity - wdj.quantity_completed - wdj.quantity_scrapped )        supply_quantity,\r\n    CASE\r\n        WHEN mkc.kanban_card_id > 0\r\n             AND mkc.kanban_card_type = 1 THEN\r\n            'Kanban'\r\n        WHEN mkc.kanban_card_id > 0     THEN\r\n            'NR Kanban'\r\n        WHEN wdj.source_code = 'MSC'    THEN\r\n            'MRP'\r\n        WHEN we.description LIKE 'Job Mass Loaded%'\r\n             AND wdj.source_code IS NULL THEN\r\n            'Min Max'\r\n        WHEN wdj.source_code IS NULL THEN\r\n            'Manual'\r\n        ELSE\r\n            wdj.source_code\r\n    END trigger_source,\r\n    wdj.completion_subinventory                                                    to_subinventory,\r\n    'No'                                                                           consigned_supply,\r\n    wdj.bom_revision                                                               supply_item_revision\r\nFROM\r\n    apps.mtl_kanban_cards_v    mkc,\r\n    inv.mtl_parameters         mp,\r\n    inv.mtl_system_items_b     msi,\r\n    apps.wip_discrete_jobs     wdj,\r\n    apps.wip_entities          we\r\n    WHERE\r\n    wdj.organization_id = mp.organization_id\r\n    AND msi.organization_id = mp.organization_id\r\n    AND mp.organization_code = '\"&ORG&\"'\r\n    AND wdj.kanban_card_id = mkc.kanban_card_id (+)\r\n    AND wdj.primary_item_id = msi.inventory_item_id\r\n    AND we.wip_entity_id = wdj.wip_entity_id\r\n    AND wdj.status_type IN (\r\n    1-- 'Released',\r\n    ,\r\n    3-- 'Unreleased'\r\n    )\r\n    \", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"SUPPLY_TYPE_CODE\", \"Supply Type Code\"}, {\"SUPPLY_DOCUMENT_NUMBER\", \"Document Number\"}, {\"SUPPLY_QUANTITY\", \"Quantity\"}, {\"RECEIPT_DATE\", \"Expected Receipt Date\"}, {\"ORGANIZATION_CODE\", \"Organization Code\"}, {\"KANBAN_CARD_NUMBER\", \"Kanban Card Number\"}, {\"EXTRACT_DATE\", \"Extract Date\"}, {\"SUPPLY_STATUS\", \"Status Code\"}, {\"DELIVERY_STATUS\", \"Delivery Status\"}, {\"ITEM_NUMBER\", \"Item Number\"}, {\"SUPPLY_NEED_BY_DATE\", \"Need By Date\"}, {\"CREATION_DATE\", \"Creation Date\"}, {\"TRIGGER_SOURCE\", \"Trigger Source\"}, {\"TO_SUBINVENTORY\", \"To Subinventory\"}, {\"CONSIGNED_SUPPLY\", \"Consigned Supply\"}, {\"LOCAL_EXTRACT_DATE\", \"Local Extract Date\"}, {\"SUPPLY_ITEM_REVISION\", \"Supply Item Revision\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Open_MO = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true,\r\n    Query=\"\r\n    SELECT\r\n    sysdate                                                                     extract_date,\r\n    from_tz(CAST(sysdate AS TIMESTAMP), 'PST') AT TIME ZONE '\"&LocalTZ&\"'         local_extract_date,\r\n    mp.organization_code,\r\n    mkc.kanban_card_id,\r\n    mkc.kanban_card_number,\r\n    msi.segment1                                                                item_number,\r\n    mtrl.inventory_item_id,\r\n    mtrl.request_number                                                         supply_document_number,\r\n    mtrl.date_required                                                          need_by_date,\r\n    mtrl.quantity - nvl(mtrl.quantity_delivered, 0)                             supply_quantity,\r\n    'MO'                                                                        supply_type_code,\r\n    'On Order'                                                                  supply_status,\r\n    mtrl.creation_date,\r\n    mtrl.date_required                                                          receipt_date,\r\n    CASE\r\n        WHEN mtrl.date_required < sysdate + 1 THEN\r\n            'Late'\r\n        ELSE\r\n            'In Process'\r\n    END delivery_status,\r\n    CASE\r\n        WHEN mkc.kanban_card_id > 0\r\n             AND mkc.kanban_card_type = 1 THEN\r\n            'Kanban'\r\n        WHEN mkc.kanban_card_id > 0 THEN\r\n            'NR Kanban'\r\n        ELSE\r\n            'Min Max'\r\n    END trigger_source,\r\n    mtrl.to_subinventory_code,\r\n    'No'                                                                        consigned_supply,\r\n    mtrl.revision SUPPLY_ITEM_REVISION\r\nFROM\r\n    apps.mtl_kanban_cards_v         mkc,\r\n    inv.mtl_parameters              mp,\r\n    inv.mtl_system_items_b          msi,\r\n    apps.mtl_txn_request_lines_v    mtrl\r\nWHERE\r\n        1 = 1\r\n    AND mp.organization_code = '\"&ORG&\"'\r\n    AND mtrl.line_status = 7\r\n    AND mtrl.inventory_item_id = msi.inventory_item_id\r\n    AND msi.organization_id = mp.organization_id\r\n    AND mtrl.organization_id = mp.organization_id\r\n    AND mtrl.reference_id = mkc.kanban_card_id (+)\r\n    AND mtrl.move_order_type = 2\r\n    \", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"SUPPLY_TYPE_CODE\", \"Supply Type Code\"}, {\"SUPPLY_DOCUMENT_NUMBER\", \"Document Number\"}, {\"SUPPLY_QUANTITY\", \"Quantity\"}, {\"RECEIPT_DATE\", \"Expected Receipt Date\"}, {\"ORGANIZATION_CODE\", \"Organization Code\"}, {\"KANBAN_CARD_NUMBER\", \"Kanban Card Number\"}, {\"EXTRACT_DATE\", \"Extract Date\"}, {\"SUPPLY_STATUS\", \"Status Code\"}, {\"DELIVERY_STATUS\", \"Delivery Status\"}, {\"ITEM_NUMBER\", \"Item Number\"}, {\"CREATION_DATE\", \"Creation Date\"}, {\"NEED_BY_DATE\", \"Need By Date\"}, {\"TRIGGER_SOURCE\", \"Trigger Source\"}, {\"TO_SUBINVENTORY_CODE\", \"To Subinventory\"}, {\"CONSIGNED_SUPPLY\", \"Consigned Supply\"}, {\"LOCAL_EXTRACT_DATE\", \"Local Extract Date\"}, {\"SUPPLY_ITEM_REVISION\", \"Supply Item Revision\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Receipt = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true,\r\n    Query=\"\r\n    SELECT\r\n    sysdate                                                                     extract_date,\r\n    from_tz(CAST(sysdate AS TIMESTAMP), 'PST') AT TIME ZONE '\"&LocalTZ&\"'         local_extract_date,\r\n    mp.organization_code,\r\n    rsh.receipt_num,\r\n    rsh.comments receipt_comment,\r\n    rsl.line_num                                                                receipt_line_number,\r\n    rsh.receipt_source_code,\r\n    rt.source_document_code,\r\n    rsh.freight_carrier_code,\r\n    rsh.expected_receipt_date,\r\n    rsh.shipment_num                                                            receipt_shipment_number,\r\n    rsh.waybill_airbill_num,\r\n    rsl.item_description,\r\n    rsl.item_id,\r\n    rt.requisition_line_id,\r\n    nvl(decode(plla.consigned_flag, 'Y', 'Yes', 'No'), 'No')                    consigned_receipt,\r\n    CASE\r\n        WHEN rt.source_document_code = 'PO'\r\n             AND rt.po_release_id IS NULL THEN\r\n            (\r\n                SELECT\r\n                    pha.segment1\r\n                FROM\r\n                    po.po_headers_all pha\r\n                WHERE\r\n                        pha.po_header_id = rt.po_header_id\r\n                    AND ROWNUM = 1\r\n            )\r\n        WHEN rt.source_document_code = 'PO'\r\n             AND rt.po_release_id IS NOT NULL THEN\r\n            (\r\n                SELECT\r\n                    pha.segment1\r\n                    || '_'\r\n                    || pra.release_num\r\n                FROM\r\n                    po.po_headers_all     pha,\r\n                    po.po_releases_all    pra\r\n                WHERE\r\n                        pha.po_header_id = pra.po_header_id\r\n                    AND rt.po_header_id = pha.po_header_id\r\n                    AND rt.po_release_id = pra.po_release_id\r\n                    AND ROWNUM = 1\r\n            )\r\n        WHEN rt.source_document_code = 'REQ'    THEN\r\n            (\r\n                SELECT\r\n                    prha.segment1\r\n                FROM\r\n                    po.po_requisition_headers_all    prha,\r\n                    po.po_requisition_lines_all      prla\r\n                WHERE\r\n                        prha.requisition_header_id = prla.requisition_header_id\r\n                    AND prla.requisition_line_id = rt.requisition_line_id\r\n                    AND ROWNUM = 1\r\n            )\r\n        WHEN rt.source_document_code = 'RMA'    THEN\r\n            (\r\n                SELECT\r\n                    to_char(oeh.order_number)\r\n                FROM\r\n                    ont.oe_order_headers_all oeh\r\n                WHERE\r\n                        oeh.header_id = rt.oe_order_header_id\r\n                    AND ROWNUM = 1\r\n            )\r\n    END receipt_source_document,\r\n    rsh.vendor_id,\r\n    rsh.vendor_site_id,\r\n    rt.transaction_id,\r\n    rt.shipment_line_id,\r\n    (\r\n        SELECT\r\n            routing_name\r\n        FROM\r\n            apps.rcv_routing_headers rrh\r\n        WHERE\r\n            rrh.routing_header_id = rt.routing_header_id\r\n    ) receipt_routing,\r\n    msi.segment1                                                                item_number,\r\n    rt.transaction_date,\r\n    rt.transaction_type,\r\n    rt.currency_code,\r\n    (\r\n        SELECT\r\n            rate_to_usd\r\n        FROM\r\n            xxdims.xx_budget_rate br\r\n        WHERE\r\n            br.currency_code = rt.currency_code\r\n    ) usd_budget_rate,\r\n    CASE\r\n        WHEN rt.transaction_type IN (\r\n            'RETURN TO VENDOR',\r\n            'RETURN TO RECEIVING',\r\n            'RETURN TO CUSTOMER'\r\n        ) THEN\r\n            rt.quantity * - 1\r\n        ELSE\r\n            rt.quantity\r\n    END receipt_quantity,\r\n    CASE\r\n        WHEN rt.transaction_type IN (\r\n            'RETURN TO VENDOR',\r\n            'RETURN TO RECEIVING',\r\n            'RETURN TO CUSTOMER'\r\n        ) THEN\r\n            rt.primary_quantity * - 1\r\n        ELSE\r\n            rt.primary_quantity\r\n    END primary_quantity,\r\n    rt.unit_of_measure                                                          receipt_unit_of_measure,\r\n    rt.po_unit_price,\r\n    rt.po_line_location_id,\r\n    rt.destination_context,\r\n    pla.line_num                                                                po_line,\r\n    plla.shipment_num                                                           po_shipment,\r\n    CASE\r\n        WHEN plla.consigned_flag = 'Y' THEN\r\n            0\r\n        ELSE\r\n            (\r\n                SELECT\r\n                    nvl(mmt.actual_cost, 0)\r\n                FROM\r\n                    inv.mtl_material_transactions mmt\r\n                WHERE\r\n                        mmt.rcv_transaction_id = rt.transaction_id\r\n                    AND mmt.organization_id = rt.organization_id\r\n                    AND mmt.inventory_item_id = rsl.item_id\r\n                    AND ROWNUM = 1\r\n            )\r\n    END actual_cost,\r\n    (\r\n        CASE\r\n            WHEN (\r\n                SELECT\r\n                    SUM(to_org_primary_quantity)\r\n                FROM\r\n                    po.rcv_supply rs\r\n                WHERE\r\n                        rs.supply_type_code = 'RECEIVING'\r\n                    AND rt.transaction_id = rs.rcv_transaction_id\r\n            ) > 0 THEN\r\n                'Yes'\r\n            ELSE\r\n                'No'\r\n        END\r\n    ) pending_deliver_flag,\r\n    (\r\n        SELECT\r\n            SUM(to_org_primary_quantity)\r\n        FROM\r\n            po.rcv_supply rs\r\n        WHERE\r\n                rs.supply_type_code = 'RECEIVING'\r\n            AND rt.transaction_id = rs.rcv_transaction_id\r\n    ) pending_delivery_quantity,\r\n    (\r\n        CASE\r\n            WHEN (\r\n                SELECT\r\n                    SUM(to_org_primary_quantity)\r\n                FROM\r\n                    po.rcv_supply rs\r\n                WHERE\r\n                        rs.supply_type_code = 'RECEIVING'\r\n                    AND rt.transaction_id = rs.rcv_transaction_id\r\n            ) > 0 THEN\r\n                round(sysdate - rt.transaction_date, 0)\r\n            ELSE\r\n                0\r\n        END\r\n    ) pending_deliver_age_days,\r\n    (\r\n        SELECT\r\n            otd_need_by_date\r\n        FROM\r\n            xxfacts.xx_porec_fact_temp_otd otd\r\n        WHERE\r\n            otd.transaction_id = rt.transaction_id\r\n    ) otd_need_by_date,\r\n    (\r\n        SELECT\r\n            otd_promised_date\r\n        FROM\r\n            xxfacts.xx_porec_fact_temp_otd otd\r\n        WHERE\r\n            otd.transaction_id = rt.transaction_id\r\n    ) otd_promised_date,\r\n    (\r\n        SELECT\r\n            otd_orig_promised_date\r\n        FROM\r\n            xxfacts.xx_porec_fact_temp_otd otd\r\n        WHERE\r\n            otd.transaction_id = rt.transaction_id\r\n    ) otd_orig_promised_date,\r\n    (\r\n        SELECT\r\n            days_to_need_by_date_adj\r\n        FROM\r\n            xxfacts.xx_porec_fact_temp_otd otd\r\n        WHERE\r\n            otd.transaction_id = rt.transaction_id\r\n    ) days_to_need_by_date,\r\n    (\r\n        SELECT\r\n            days_to_promised_date_adj\r\n        FROM\r\n            xxfacts.xx_porec_fact_temp_otd otd\r\n        WHERE\r\n            otd.transaction_id = rt.transaction_id\r\n    ) days_to_promised_date,\r\n    (\r\n        SELECT\r\n            days_to_orig_promised_date_adj\r\n        FROM\r\n            xxfacts.xx_porec_fact_temp_otd otd\r\n        WHERE\r\n            otd.transaction_id = rt.transaction_id\r\n    ) days_to_orig_promised_date,\r\n    CASE\r\n        WHEN rt.source_document_code IN (\r\n            'REQ',\r\n            'RMA'\r\n        ) THEN\r\n            'INVENTORY'\r\n        ELSE\r\n            (\r\n                SELECT\r\n                    destination_type_code\r\n                FROM\r\n                    apps.po_distributions_all pda\r\n                WHERE\r\n                        pda.line_location_id = rt.po_line_location_id\r\n                    AND ROWNUM = 1\r\n            )\r\n    END po_destination_type,\r\n    (\r\n        SELECT\r\n            transaction_type\r\n        FROM\r\n            apps.rcv_transactions rt2\r\n        WHERE\r\n            rt2.transaction_id = rt.parent_transaction_id\r\n    ) parent_transaction_type,\r\n    rt.rma_reference,\r\n    nvl((\r\n        SELECT\r\n            item_type\r\n        FROM\r\n            xxfacts.xx_porec_fact rf\r\n        WHERE\r\n                rf.transaction_id = rt.transaction_id\r\n            AND ROWNUM = 1\r\n    ),(\r\n        SELECT\r\n            meaning\r\n        FROM\r\n            apps.fnd_lookup_values flv\r\n        WHERE\r\n                flv.lookup_type = 'ITEM_TYPE'\r\n            AND flv.lookup_code = msi.item_type\r\n            AND language = 'US'\r\n    )) receipt_item_type,\r\n    (\r\n        SELECT\r\n            SUM(nvl(accounted_dr, 0) - nvl(accounted_cr, 0)) * - 1 net_accounted\r\n        FROM\r\n            apps.rcv_receiving_sub_ledger    rrsl,\r\n            apps.gl_code_combinations        gcc\r\n        WHERE\r\n                gcc.code_combination_id = rrsl.code_combination_id\r\n            AND gcc.segment3 = '20510'\r\n            AND rrsl.rcv_transaction_id = rt.transaction_id\r\n    ) ap_accrual,\r\n    (\r\n        SELECT\r\n            gcc.concatenated_segments\r\n        FROM\r\n            apps.gl_code_combinations_kfv    gcc,\r\n            apps.po_distributions_all        pda\r\n        WHERE\r\n                pda.code_combination_id = gcc.code_combination_id\r\n            AND rt.po_distribution_id = pda.po_distribution_id\r\n            AND rt.po_header_id = pda.po_header_id\r\n            AND rt.po_line_id = pda.po_line_id\r\n    ) po_charge_account\r\nFROM\r\n    apps.rcv_transactions                rt,\r\n    apps.org_organization_definitions    mp,\r\n    inv.mtl_system_items_b               msi,\r\n    po.rcv_shipment_lines                rsl,\r\n    po.rcv_shipment_headers              rsh,\r\n    apps.po_lines_all                    pla,\r\n    apps.po_line_locations_all           plla\r\nWHERE\r\n        mp.organization_id = rt.organization_id\r\n    AND rt.po_line_id = pla.po_line_id (+)\r\n    AND rt.po_line_location_id = plla.line_location_id (+)\r\n    AND mp.organization_code = '\"&ORG&\"'\r\n    AND rt.shipment_line_id = rsl.shipment_line_id\r\n    AND rt.shipment_header_id = rsh.shipment_header_id\r\n    AND rsh.shipment_header_id = rsl.shipment_header_id\r\n    AND rsh.ship_to_org_id = rt.organization_id\r\n    AND rt.organization_id = msi.organization_id (+)\r\n    AND rsl.item_id = msi.inventory_item_id (+)\r\n    \", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"EXTRACT_DATE\", \"Extract Date\"}, {\"CONSIGNED_RECEIPT\", \"Consigned Flag\"}, {\"RECEIPT_COMMENT\", \"Receipt Comment\"}, {\"ORGANIZATION_CODE\", \"Organization Code\"}, {\"RECEIPT_NUM\", \"Receipt Number\"}, {\"RECEIPT_LINE_NUMBER\", \"Line Number\"}, {\"ITEM_DESCRIPTION\", \"Item Description\"}, {\"RECEIPT_SOURCE_CODE\", \"Source Code\"}, {\"SOURCE_DOCUMENT_CODE\", \"Source Document\"}, {\"FREIGHT_CARRIER_CODE\", \"Freight Carrier\"}, {\"EXPECTED_RECEIPT_DATE\", \"Expected Date\"}, {\"RECEIPT_SHIPMENT_NUMBER\", \"Shipment Number\"}, {\"WAYBILL_AIRBILL_NUM\", \"Waybill\"}, {\"RECEIPT_SOURCE_DOCUMENT\", \"Source Document Number\"}, {\"ITEM_NUMBER\", \"Item Number\"}, {\"TRANSACTION_DATE\", \"Transaction Date\"}, {\"TRANSACTION_TYPE\", \"Transaction Type\"}, {\"CURRENCY_CODE\", \"Currency Code\"}, {\"PO_UNIT_PRICE\", \"PO Unit Price\"}, {\"RECEIPT_QUANTITY\", \"Quantity\"}, {\"PRIMARY_QUANTITY\", \"Primary Quantity\"}, {\"RECEIPT_UNIT_OF_MEASURE\", \"Unit of Measure\"}, {\"PENDING_DELIVER_FLAG\", \"Pending Deliver Flag\"}, {\"PENDING_DELIVER_AGE_DAYS\", \"Pending Deliver Age Days\"}, {\"DESTINATION_CONTEXT\", \"Receipt Destination Context\"}, {\"ACTUAL_COST\", \"Actual Cost\"}, {\"RECEIPT_ROUTING\", \"Receipt Routing\"}, {\"OTD_NEED_BY_DATE\", \"OTD Need By Date\"}, {\"OTD_PROMISED_DATE\", \"OTD Promised Date\"}, {\"OTD_ORIG_PROMISED_DATE\", \"OTD Original Promised Date\"}, {\"DAYS_TO_NEED_BY_DATE\", \"Days To Need By Date\"}, {\"DAYS_TO_PROMISED_DATE\", \"Days To Promised Date\"}, {\"DAYS_TO_ORIG_PROMISED_DATE\", \"Days To Original Promised Date\"}, {\"PENDING_DELIVERY_QUANTITY\", \"Pending Deliver Quantity\"}, {\"PO_DESTINATION_TYPE\", \"PO Destination Type\"}, {\"USD_BUDGET_RATE\", \"USD Budget Rate\"}, {\"PARENT_TRANSACTION_TYPE\", \"Parent Transaction Type\"}, {\"PO_LINE\", \"PO Line\"}, {\"PO_SHIPMENT\", \"PO Shipment\"}, {\"RMA_REFERENCE\", \"RMA Reference\"}, {\"RECEIPT_ITEM_TYPE\", \"Receipt Item Type\"}, {\"AP_ACCRUAL\", \"AP Accrual\"}, {\"PO_CHARGE_ACCOUNT\", \"PO Charge Account\"}, {\"LOCAL_EXTRACT_DATE\", \"Local Extract Date\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared LocalTZ = let\r\n  LocalZoneRegion = \"Europe/Berlin\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type text]\r\nin\r\n  LocalZoneRegion;\r\nshared Material_Transaction = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, Query=\"\r\n    SELECT\r\n    sysdate extract_date,\r\n    from_tz(cast (sysdate as timestamp),'PST') at time zone '\"&LocalTZ&\"' local_extract_date,\r\n    from_tz(cast (mmt.transaction_date as timestamp),'PST') at time zone '\"&LocalTZ&\"' local_transaction_date,\r\n    mp.organization_code,\r\n    msi.inventory_item_id,\r\n    msi.segment1,\r\n    mmt.primary_quantity,\r\n    mmt.transaction_date,\r\n    mmt.transaction_id,\r\n    mtt.transaction_type_name,\r\n    flv.meaning    transaction_action,\r\n    mmt.subinventory_code,\r\n    mmt.transfer_subinventory,\r\n    tst.transaction_source_type_name,\r\n    mmt.transfer_transaction_id,\r\n    mmt.transaction_reference,\r\n    CASE\r\n    WHEN tst.transaction_source_type_name = 'Job or Schedule'\r\n    AND (\r\n    SELECT\r\n    COUNT(1)\r\n    FROM\r\n    apps.wip_discrete_jobs_v wdj\r\n    WHERE\r\n    wdj.wip_entity_id = mmt.transaction_source_id\r\n    ) = 0 THEN\r\n    'Work Orderless'\r\n    ELSE\r\n    tst.transaction_source_type_name\r\n    END source_type,\r\n    CASE\r\n    WHEN tst.transaction_source_type_name = 'Job or Schedule' THEN\r\n    CASE\r\n    WHEN (\r\n    SELECT\r\n    wdj.class_code\r\n    FROM\r\n    apps.wip_discrete_jobs_v wdj\r\n    WHERE\r\n    wdj.wip_entity_id = mmt.transaction_source_id\r\n    AND tst.transaction_source_type_name = 'Job or Schedule'\r\n    ) IS NULL THEN\r\n    (\r\n    SELECT\r\n    wdj.class_code\r\n    FROM\r\n    apps.wip_flow_schedules wdj\r\n    WHERE\r\n    wdj.wip_entity_id = mmt.transaction_source_id\r\n    AND tst.transaction_source_type_name = 'Job or Schedule'\r\n    )\r\n    ELSE\r\n    (\r\n    SELECT\r\n    wdj.class_code\r\n    FROM\r\n    apps.wip_discrete_jobs_v wdj\r\n    WHERE\r\n    wdj.wip_entity_id = mmt.transaction_source_id\r\n    AND tst.transaction_source_type_name = 'Job or Schedule'\r\n    )\r\n    END\r\n    END wip_job_class,\r\n    CASE\r\n    WHEN mmt.transaction_source_type_id = 1     THEN\r\n    (\r\n    SELECT\r\n    pha.segment1\r\n    FROM\r\n    apps.po_headers_all pha\r\n    WHERE\r\n    pha.po_header_id = mmt.transaction_source_id\r\n    )\r\n    WHEN mmt.transaction_source_type_id = 2     THEN\r\n    (\r\n    SELECT\r\n    segment1\r\n    FROM\r\n    apps.mtl_sales_orders\r\n    WHERE\r\n    sales_order_id = mmt.transaction_source_id\r\n    )\r\n    WHEN mmt.transaction_source_type_id = 4     THEN\r\n    (\r\n    SELECT\r\n    request_number\r\n    FROM\r\n    apps.mtl_txn_request_headers mtrh\r\n    WHERE\r\n    request_number = to_char(mmt.transaction_source_id)\r\n    AND mtrh.organization_id = mmt.organization_id\r\n    )\r\n    WHEN mmt.transaction_source_type_id = 5     THEN\r\n    (\r\n    SELECT\r\n    wip_entity_name\r\n    FROM\r\n    apps.wip_entities\r\n    WHERE\r\n    wip_entity_id = mmt.transaction_source_id\r\n    )\r\n    WHEN mmt.transaction_source_type_id = 6     THEN\r\n    (\r\n    SELECT\r\n    segment1\r\n    FROM\r\n    apps.mtl_generic_dispositions mgd\r\n    WHERE\r\n    mgd.disposition_id = mmt.transaction_source_id\r\n    )\r\n    WHEN mmt.transaction_source_type_id = 7     THEN\r\n    (\r\n    SELECT\r\n    rcv.shipment_num\r\n    FROM\r\n    apps.rcv_shipment_headers    rcv,\r\n    apps.rcv_transactions        rcvt\r\n    WHERE\r\n    rcv.shipment_header_id = rcvt.shipment_header_id\r\n    AND rcvt.transaction_id = mmt.transaction_source_id\r\n    )\r\n    WHEN mmt.transaction_source_type_id = 8     THEN\r\n    (\r\n    SELECT\r\n    segment1\r\n    FROM\r\n    apps.mtl_sales_orders\r\n    WHERE\r\n    sales_order_id = mmt.transaction_source_id\r\n    )\r\n    WHEN mmt.transaction_source_type_id = 10    THEN\r\n    (\r\n    SELECT\r\n    physical_inventory_name\r\n    FROM\r\n    apps.mtl_physical_inventories\r\n    WHERE\r\n    physical_inventory_id = mmt.transaction_source_id\r\n    )\r\n    WHEN mmt.transaction_source_type_id = 13    THEN\r\n    (\r\n    SELECT\r\n    wip_entity_name\r\n    FROM\r\n    apps.wip_entities\r\n    WHERE\r\n    wip_entity_id = mmt.transaction_source_id\r\n    )\r\n    ELSE\r\n    NULL\r\n    END source_document,\r\n    CASE\r\n    WHEN flv.meaning = 'Ownership Transfer' THEN\r\n    'Ownership Transfer'\r\n    WHEN flv.meaning IN (\r\n    'Subinventory transfer',\r\n    'Staging transfer'\r\n    )\r\n    AND (\r\n    SELECT\r\n    mseci2.quantity_tracked\r\n    FROM\r\ninv.mtl_secondary_inventories mseci2\r\n    WHERE\r\n    mseci2.secondary_inventory_name = mmt.transfer_subinventory\r\n    AND mseci2.organization_id = mmt.organization_id\r\n    ) = 1 THEN\r\n    'Transfer'\r\n    WHEN flv.meaning IN (\r\n    'Cycle count adjustment',\r\n    'Delivery Adjustments'\r\n    ) THEN\r\n    'Adjustments'\r\n    WHEN flv.meaning IN (\r\n    'Subinventory transfer',\r\n    'Staging transfer'\r\n    )\r\n    AND mmt.transaction_quantity < 0\r\n    AND (\r\n    SELECT\r\n    mseci2.quantity_tracked\r\n    FROM\r\ninv.mtl_secondary_inventories mseci2\r\n    WHERE\r\n    mseci2.secondary_inventory_name = mmt.transfer_subinventory\r\n    AND mseci2.organization_id = mmt.organization_id\r\n    ) = 2 THEN\r\n    'Usage'\r\n    WHEN  mtt.transaction_type_name IN (\r\n    'WIP Issue',\r\n    'Sales order issue',\r\n    'Internal order issue',\r\n    'Int Order Intr Ship',\r\n    'Move order issue',\r\n    'WIP Return',\r\n    'Field Service Usage',\r\n    'Assembly return',\r\n    'WIP Negative Issue',\r\n    'WIP Negative Return'\r\n    ) THEN\r\n    'Usage'\r\n    WHEN mtt.transaction_type_name IN (\r\n    'RMA Return',\r\n    'RMA Receipt',\r\n    'LC Return'\r\n    ) THEN\r\n    'Return'\r\n    WHEN mtt.transaction_type_name IN (\r\n    'Account issue',\r\n    'Account alias issue',\r\n    'Miscellaneous issue'\r\n    ) THEN\r\n    'Miscellaneous out'\r\n    WHEN mtt.transaction_type_name IN (\r\n    'Account receipt',\r\n    'Account alias receipt',\r\n    'Miscellaneous receipt'\r\n    ) THEN\r\n    'Miscellaneous in'\r\n    WHEN mtt.transaction_type_name IN (\r\n    'WIP Assy Completion',\r\n    'WIP Completion Return'\r\n    ) THEN\r\n    'Build'\r\n    WHEN mmt.rcv_transaction_id > 0 THEN\r\n    'Receipt'\r\n    ELSE\r\n    'Other'\r\n    END transaction_classification,\r\n    CASE\r\n    WHEN mmt.owning_organization_id = mmt.organization_id THEN\r\n    CASE\r\n    WHEN mseci.asset_inventory = 1 THEN\r\n    mmt.actual_cost\r\n    ELSE\r\n    0\r\n    END\r\n    ELSE\r\n    0\r\n    END actual_cost,\r\n    fu.user_name created_by\r\n    FROM\r\n    apps.mtl_material_transactions    mmt,\r\n    apps.mtl_transaction_types        mtt,\r\ninv.mtl_parameters                mp,\r\ninv.mtl_system_items_b            msi,\r\n    fnd_lookup_values                 flv,\r\ninv.mtl_secondary_inventories     mseci,\r\ninv.mtl_txn_source_types          tst,\r\n    apps.fnd_user fu\r\n    WHERE\r\n    mmt.transaction_type_id = mtt.transaction_type_id\r\n    AND mp.organization_id = mmt.organization_id\r\n    AND msi.inventory_item_id = mmt.inventory_item_id\r\n    AND flv.language = 'US'\r\n    AND msi.organization_id = mp.organization_id\r\n    AND flv.lookup_code = mtt.transaction_action_id\r\n    AND flv.lookup_type = 'MTL_TRANSACTION_ACTION'\r\n    AND mseci.secondary_inventory_name = mmt.subinventory_code\r\n    AND tst.transaction_source_type_id = mtt.transaction_source_type_id\r\n    AND mseci.organization_id = mmt.organization_id\r\n    AND mp.organization_code = '\"&ORG&\"'\r\n    AND mmt.transaction_date >= (\r\n    SELECT\r\n    gp.year_start_date\r\n    FROM\r\n    gl.gl_periods            gp\r\n    WHERE\r\n    gp.period_set_name = 'COHR Calendar'\r\n    AND trunc(sysdate) between gp.start_date and gp.end_date\r\n    )\r\n    AND transaction_quantity <> 0\r\n    AND fu.user_id = mmt.created_by\r\n    \", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"ORGANIZATION_CODE\", \"Organization Code\"}, {\"SEGMENT1\", \"Item Number\"}, {\"PRIMARY_QUANTITY\", \"Primary Transaction Quantity\"}, {\"TRANSACTION_DATE\", \"Transaction Date\"}, {\"TRANSACTION_TYPE_NAME\", \"Transaction Type Name\"}, {\"TRANSACTION_ACTION\", \"Transaction Action\"}, {\"SUBINVENTORY_CODE\", \"Transaction Subinventory\"}, {\"TRANSFER_SUBINVENTORY\", \"Transfer Subinventory\"}, {\"TRANSACTION_SOURCE_TYPE_NAME\", \"Transaction Source Type Name\"}, {\"TRANSACTION_REFERENCE\", \"Transaction Reference\"}, {\"SOURCE_TYPE\", \"Calculated Transaction Source Type\"}, {\"SOURCE_DOCUMENT\", \"Source Document Number\"}, {\"TRANSACTION_CLASSIFICATION\", \"Transaction Classification\"}, {\"ACTUAL_COST\", \"Actual Cost\"}, {\"WIP_JOB_CLASS\", \"WIP Accounting Class\"}, {\"EXTRACT_DATE\", \"Extract Date\"}, {\"CREATED_BY\", \"Created By\"}, {\"LOCAL_EXTRACT_DATE\", \"Local Extract Date\"}, {\"LOCAL_TRANSACTION_DATE\", \"Local Transaction Date\"}})\r\nin\r\n  #\"Renamed columns\";\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"Kanban_Card","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Kanban_Card.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Local Extract Date","dataType":"dateTime"},{"name":"Organization Code","dataType":"string"},{"name":"KANBAN_CARD_ID","dataType":"double"},{"name":"Card Number","dataType":"string"},{"name":"Creation Date","dataType":"dateTime"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"Item Number","dataType":"string"},{"name":"Pull Sequence Id","dataType":"double"},{"name":"Effective Lead Time","dataType":"double"},{"name":"Pull Sequence Lead Time","dataType":"double"},{"name":"Subinventory","dataType":"string"},{"name":"Locator","dataType":"string"},{"name":"Source Org","dataType":"string"},{"name":"Source Subinventory","dataType":"string"},{"name":"Source Locator","dataType":"string"},{"name":"Card Type","dataType":"string"},{"name":"Card Size","dataType":"double"},{"name":"Source Type","dataType":"string"},{"name":"Supply Status","dataType":"string"},{"name":"SUPPLY_STATUS_ID","dataType":"double"},{"name":"Last Replenish Date","dataType":"dateTime"},{"name":"Replenish Count","dataType":"double"},{"name":"Kanban Last Replenish By","dataType":"string"},{"name":"Last Empty Date","dataType":"dateTime"},{"name":"Kanban Last Empty By","dataType":"string"},{"name":"Last Activity Age Days","dataType":"double"},{"name":"Source Onhand","dataType":"double"},{"name":"Onhand Quantity","dataType":"double"},{"name":"ITEM_COST","dataType":"double"},{"name":"Card Status","dataType":"string"},{"name":"Exception","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-05-20T05:07:06.7742172+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/39d6e9d2-bf49-4956-bb18-7802a6815194/Kanban_Card.csv?snapshot=2022-05-20T05%3A07%3A06.1445256Z"}]},{"$type":"LocalEntity","name":"Onhand","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Onhand.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Local Extract Date","dataType":"dateTime"},{"name":"Organization Code","dataType":"string"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"Item Number","dataType":"string"},{"name":"Quantity","dataType":"double"},{"name":"Consigned Flag","dataType":"string"},{"name":"Locator","dataType":"string"},{"name":"Owning Supplier Name","dataType":"string"},{"name":"Owning Supplier Site Code","dataType":"string"},{"name":"VENDOR_ID","dataType":"double"},{"name":"VENDOR_SITE_ID","dataType":"double"},{"name":"Date Received","dataType":"dateTime"},{"name":"ITEM_COST","dataType":"double"},{"name":"Subinventory","dataType":"string"},{"name":"Asset Subinventory Flag","dataType":"string"},{"name":"Nettable Subinventory Flag","dataType":"string"},{"name":"Subinventory Classification","dataType":"string"},{"name":"Transaction Reference","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-05-20T05:07:07.4460797+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/39d6e9d2-bf49-4956-bb18-7802a6815194/Onhand.csv?snapshot=2022-05-20T05%3A07%3A06.1445256Z"}]},{"$type":"LocalEntity","name":"Open_Supply","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Open_Supply.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Local Extract Date","dataType":"dateTime"},{"name":"Item Number","dataType":"string"},{"name":"Organization Code","dataType":"string"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"Source Org Code","dataType":"string"},{"name":"Supply Type Code","dataType":"string"},{"name":"Status Code","dataType":"string"},{"name":"Quantity","dataType":"double"},{"name":"VENDOR_SITE_ID","dataType":"double"},{"name":"Creation Date","dataType":"dateTime"},{"name":"Need By Date","dataType":"dateTime"},{"name":"Expected Receipt Date","dataType":"dateTime"},{"name":"Delivery Status","dataType":"string"},{"name":"Document Number","dataType":"string"},{"name":"Internal Order Number","dataType":"double"},{"name":"Trigger Source","dataType":"string"},{"name":"Kanban Card Number","dataType":"string"},{"name":"KANBAN_CARD_ID","dataType":"double"},{"name":"To Subinventory","dataType":"string"},{"name":"Consigned Supply","dataType":"string"},{"name":"Supply Item Revision","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-05-20T05:07:08.0085821+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/39d6e9d2-bf49-4956-bb18-7802a6815194/Open_Supply.csv?snapshot=2022-05-20T05%3A07%3A07.3158131Z"}]},{"$type":"LocalEntity","name":"Cycle_Count_Activity","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Cycle_Count_Activity.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Local Extract Date","dataType":"dateTime"},{"name":"Organization Code","dataType":"string"},{"name":"Cycle Count Name","dataType":"string"},{"name":"Cycle Count Description","dataType":"string"},{"name":"Disable Date","dataType":"dateTime"},{"name":"Sequence","dataType":"double"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"Item Number","dataType":"string"},{"name":"Count ABC Class","dataType":"string"},{"name":"Subinventory","dataType":"string"},{"name":"Locator","dataType":"string"},{"name":"Lot Number","dataType":"string"},{"name":"Serial Number","dataType":"string"},{"name":"Count Status","dataType":"string"},{"name":"Creation Date","dataType":"dateTime"},{"name":"Due Date","dataType":"dateTime"},{"name":"System Quantity","dataType":"double"},{"name":"Count Quantity","dataType":"double"},{"name":"Count Unit of Measure","dataType":"string"},{"name":"Count Date","dataType":"dateTime"},{"name":"Count By","dataType":"string"},{"name":"System Quantity Prior","dataType":"double"},{"name":"Count Quantity Prior","dataType":"double"},{"name":"Count Unit of Measure Prior","dataType":"string"},{"name":"Count Date Prior","dataType":"dateTime"},{"name":"Count Prior By","dataType":"string"},{"name":"First Count System Quantity","dataType":"double"},{"name":"First Count Quantity","dataType":"double"},{"name":"First Pass Status","dataType":"string"},{"name":"First Count Unit of Measure","dataType":"string"},{"name":"First Count Date","dataType":"dateTime"},{"name":"First Count By","dataType":"string"},{"name":"Adjustment Quantity","dataType":"double"},{"name":"Count Pass Status","dataType":"string"},{"name":"Adjustment Date","dataType":"dateTime"},{"name":"Adjustment Amount","dataType":"double"},{"name":"Last Updated By","dataType":"string"},{"name":"Approval Date","dataType":"dateTime"}],"partitions":[{"name":"Part001","refreshTime":"2022-05-20T05:08:12.3900067+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/39d6e9d2-bf49-4956-bb18-7802a6815194/Cycle_Count_Activity.csv?snapshot=2022-05-20T05%3A08%3A07.2344140Z"}]},{"$type":"LocalEntity","name":"Serial_Status","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Serial_Status.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Local Extract Date","dataType":"dateTime"},{"name":"Organization Code","dataType":"string"},{"name":"Current Organization Code","dataType":"string"},{"name":"Serial Status","dataType":"string"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"Item Number","dataType":"string"},{"name":"Serial Number","dataType":"string"},{"name":"WIP Completion Date","dataType":"dateTime"},{"name":"Shipped Date","dataType":"dateTime"},{"name":"Parent Item Number","dataType":"string"},{"name":"Parent Serial Number","dataType":"string"},{"name":"Current Subinventory","dataType":"string"},{"name":"Current Locator","dataType":"string"},{"name":"Original Job Number","dataType":"string"},{"name":"Original Job Organization","dataType":"string"},{"name":"Last Transaction Source","dataType":"string"},{"name":"Last Transaction Source Name","dataType":"string"},{"name":"Last Transaction Source Document","dataType":"string"},{"name":"RESERVATION_ID","dataType":"double"},{"name":"Last Receipt Number","dataType":"string"},{"name":"Last PO Receipt Number","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-05-20T05:37:55.4121087+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/39d6e9d2-bf49-4956-bb18-7802a6815194/Serial_Status.csv?snapshot=2022-05-20T05%3A37%3A55.3891087Z"}]},{"$type":"LocalEntity","name":"Receiving_Default","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Receiving_Default.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Local Extract Date","dataType":"dateTime"},{"name":"Organization Code","dataType":"string"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"Item Number","dataType":"string"},{"name":"Default Receiving Subinventory","dataType":"string"},{"name":"Default Receiving Locator","dataType":"string"},{"name":"Default Receiving Validation","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-05-20T05:07:06.197856+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/39d6e9d2-bf49-4956-bb18-7802a6815194/Receiving_Default.csv?snapshot=2022-05-20T05%3A07%3A06.0295954Z"}]},{"$type":"LocalEntity","name":"Consumption_Advice","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Consumption_Advice.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Local Extract Date","dataType":"dateTime"},{"name":"Organization Code","dataType":"string"},{"name":"TRANSACTION_ID","dataType":"double"},{"name":"VENDOR_ID","dataType":"double"},{"name":"VENDOR_SITE_ID","dataType":"double"},{"name":"ITEM_ID","dataType":"double"},{"name":"Item Number","dataType":"string"},{"name":"Item Description","dataType":"string"},{"name":"Source Code","dataType":"string"},{"name":"Source Document","dataType":"string"},{"name":"Consigned Flag","dataType":"string"},{"name":"Source Document Number","dataType":"string"},{"name":"Transaction Date","dataType":"dateTime"},{"name":"Quantity","dataType":"double"},{"name":"Unit of Measure","dataType":"string"},{"name":"Primary Quantity","dataType":"double"},{"name":"PO_LINE_LOCATION_ID","dataType":"double"},{"name":"PO_DISTRIBUTION_ID","dataType":"double"},{"name":"Transaction Type","dataType":"string"},{"name":"PO Destination Type","dataType":"string"},{"name":"Currency Code","dataType":"string"},{"name":"PO Line","dataType":"double"},{"name":"Actual Cost","dataType":"double"},{"name":"PO Shipment","dataType":"double"},{"name":"USD Budget Rate","dataType":"double"},{"name":"PO Unit Price","dataType":"double"},{"name":"Receipt Item Type","dataType":"string"},{"name":"AP Accrual","dataType":"double"},{"name":"PO Charge Account","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-05-20T05:06:22.4944114+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/39d6e9d2-bf49-4956-bb18-7802a6815194/Consumption_Advice.csv?snapshot=2022-05-20T05%3A06%3A22.3651383Z"}]},{"$type":"LocalEntity","name":"Open_WO","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Open_WO.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Local Extract Date","dataType":"dateTime"},{"name":"Organization Code","dataType":"string"},{"name":"KANBAN_CARD_ID","dataType":"double"},{"name":"Kanban Card Number","dataType":"string"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"Item Number","dataType":"string"},{"name":"Supply Type Code","dataType":"string"},{"name":"Document Number","dataType":"string"},{"name":"Status Code","dataType":"string"},{"name":"Delivery Status","dataType":"string"},{"name":"Expected Receipt Date","dataType":"dateTime"},{"name":"Need By Date","dataType":"dateTime"},{"name":"Creation Date","dataType":"dateTime"},{"name":"Quantity","dataType":"double"},{"name":"Trigger Source","dataType":"string"},{"name":"To Subinventory","dataType":"string"},{"name":"Consigned Supply","dataType":"string"},{"name":"Supply Item Revision","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-05-20T05:06:21.9787882+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/39d6e9d2-bf49-4956-bb18-7802a6815194/Open_WO.csv?snapshot=2022-05-20T05%3A06%3A21.7485134Z"}]},{"$type":"LocalEntity","name":"Open_MO","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Open_MO.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Local Extract Date","dataType":"dateTime"},{"name":"Organization Code","dataType":"string"},{"name":"KANBAN_CARD_ID","dataType":"double"},{"name":"Kanban Card Number","dataType":"string"},{"name":"Item Number","dataType":"string"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"Document Number","dataType":"string"},{"name":"Need By Date","dataType":"dateTime"},{"name":"Quantity","dataType":"double"},{"name":"Supply Type Code","dataType":"string"},{"name":"Status Code","dataType":"string"},{"name":"Creation Date","dataType":"dateTime"},{"name":"Expected Receipt Date","dataType":"dateTime"},{"name":"Delivery Status","dataType":"string"},{"name":"Trigger Source","dataType":"string"},{"name":"To Subinventory","dataType":"string"},{"name":"Consigned Supply","dataType":"string"},{"name":"Supply Item Revision","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-05-20T05:07:07.7117141+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/39d6e9d2-bf49-4956-bb18-7802a6815194/Open_MO.csv?snapshot=2022-05-20T05%3A07%3A06.7311689Z"}]},{"$type":"LocalEntity","name":"Receipt","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Receipt.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Local Extract Date","dataType":"dateTime"},{"name":"Organization Code","dataType":"string"},{"name":"Receipt Number","dataType":"string"},{"name":"Receipt Comment","dataType":"string"},{"name":"Line Number","dataType":"double"},{"name":"Source Code","dataType":"string"},{"name":"Source Document","dataType":"string"},{"name":"Freight Carrier","dataType":"string"},{"name":"Expected Date","dataType":"dateTime"},{"name":"Shipment Number","dataType":"string"},{"name":"Waybill","dataType":"string"},{"name":"Item Description","dataType":"string"},{"name":"ITEM_ID","dataType":"double"},{"name":"REQUISITION_LINE_ID","dataType":"double"},{"name":"Consigned Flag","dataType":"string"},{"name":"Source Document Number","dataType":"string"},{"name":"VENDOR_ID","dataType":"double"},{"name":"VENDOR_SITE_ID","dataType":"double"},{"name":"TRANSACTION_ID","dataType":"double"},{"name":"SHIPMENT_LINE_ID","dataType":"double"},{"name":"Receipt Routing","dataType":"string"},{"name":"Item Number","dataType":"string"},{"name":"Transaction Date","dataType":"dateTime"},{"name":"Transaction Type","dataType":"string"},{"name":"Currency Code","dataType":"string"},{"name":"USD Budget Rate","dataType":"double"},{"name":"Quantity","dataType":"double"},{"name":"Primary Quantity","dataType":"double"},{"name":"Unit of Measure","dataType":"string"},{"name":"PO Unit Price","dataType":"double"},{"name":"PO_LINE_LOCATION_ID","dataType":"double"},{"name":"Receipt Destination Context","dataType":"string"},{"name":"PO Line","dataType":"double"},{"name":"PO Shipment","dataType":"double"},{"name":"Actual Cost","dataType":"double"},{"name":"Pending Deliver Flag","dataType":"string"},{"name":"Pending Deliver Quantity","dataType":"double"},{"name":"Pending Deliver Age Days","dataType":"double"},{"name":"OTD Need By Date","dataType":"string"},{"name":"OTD Promised Date","dataType":"string"},{"name":"OTD Original Promised Date","dataType":"string"},{"name":"Days To Need By Date","dataType":"double"},{"name":"Days To Promised Date","dataType":"double"},{"name":"Days To Original Promised Date","dataType":"double"},{"name":"PO Destination Type","dataType":"string"},{"name":"Parent Transaction Type","dataType":"string"},{"name":"RMA Reference","dataType":"string"},{"name":"Receipt Item Type","dataType":"string"},{"name":"AP Accrual","dataType":"double"},{"name":"PO Charge Account","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-05-20T05:43:52.2275479+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/39d6e9d2-bf49-4956-bb18-7802a6815194/Receipt.csv?snapshot=2022-05-20T05%3A43%3A52.2031447Z"}]},{"$type":"LocalEntity","name":"Material_Transaction","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Material_Transaction.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Local Extract Date","dataType":"dateTime"},{"name":"Local Transaction Date","dataType":"dateTime"},{"name":"Organization Code","dataType":"string"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"Item Number","dataType":"string"},{"name":"Primary Transaction Quantity","dataType":"double"},{"name":"Transaction Date","dataType":"dateTime"},{"name":"TRANSACTION_ID","dataType":"double"},{"name":"Transaction Type Name","dataType":"string"},{"name":"Transaction Action","dataType":"string"},{"name":"Transaction Subinventory","dataType":"string"},{"name":"Transfer Subinventory","dataType":"string"},{"name":"Transaction Source Type Name","dataType":"string"},{"name":"TRANSFER_TRANSACTION_ID","dataType":"double"},{"name":"Transaction Reference","dataType":"string"},{"name":"Calculated Transaction Source Type","dataType":"string"},{"name":"WIP Accounting Class","dataType":"string"},{"name":"Source Document Number","dataType":"string"},{"name":"Transaction Classification","dataType":"string"},{"name":"Actual Cost","dataType":"double"},{"name":"Created By","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-05-20T05:08:01.8557696+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/39d6e9d2-bf49-4956-bb18-7802a6815194/Material_Transaction.csv?snapshot=2022-05-20T05%3A08%3A00.5634653Z"}]}]}