{"name":"Target_Budget","description":"Target and Budget reference","version":"1.0","culture":"en-US","modifiedTime":"2021-03-24T06:18:10.114628+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"Manufacturing_Expense_Budget":{"queryId":"a7efa6f8-16de-42e2-a00c-ac7e63d308bb","queryName":"Manufacturing_Expense_Budget","loadEnabled":true}},"document":"section Section1;\r\nshared Manufacturing_Expense_Budget = let\r\n  Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"FC Year\" = _t, #\"GL Department Code\" = _t, #\"GL Entity Code\" = _t, #\"GL Account Code\" = _t, #\"Budget Amount USD\" = _t]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(Source, {{\"Budget Amount USD\", type number}, {\"FC Year\", type number}})\r\nin\r\n  #\"Changed column type\";\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"Manufacturing_Expense_Budget","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Manufacturing_Expense_Budget.csv"},"attributes":[{"name":"FC Year","dataType":"double"},{"name":"GL Department Code","dataType":"string"},{"name":"GL Entity Code","dataType":"string"},{"name":"GL Account Code","dataType":"string"},{"name":"Budget Amount USD","dataType":"double"}],"partitions":[{"name":"Part001","refreshTime":"2021-03-24T06:18:43.3613814+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/5320a6d5-98c9-40c9-b5de-95f77b19f5b0/Manufacturing_Expense_Budget.csv?snapshot=2021-05-17T10%3A39%3A07.4899097Z"}]}]}