{"name":"COHREP_SITE_PURCHASING_MASTER1","description":"","version":"1.0","culture":"en-US","modifiedTime":"2021-03-12T01:03:19.7612816+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":true,"queriesMetadata":{"Buyer":{"queryId":"edcfb8f1-71a2-4d77-829a-99e05601b8a6","queryName":"Buyer","queryGroupId":"root","loadEnabled":true},"Supplier_Contact":{"queryId":"3d6511dd-14bf-4ee5-b7be-e82f9533ad6e","queryName":"Supplier_Contact","queryGroupId":"root","loadEnabled":true},"Supplier":{"queryId":"ce291698-373a-4fd0-ae7b-7a935ed4e51c","queryName":"Supplier","queryGroupId":"root","loadEnabled":true},"ORG":{"queryId":"43c69a79-2c80-4316-bc27-040178279912","queryName":"ORG"},"LocalTZ":{"queryId":"6e62c5f0-2417-4369-9b67-651a5cb14569","queryName":"LocalTZ"}},"document":"section Section1;\r\nshared Buyer = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, Query=\"\n  SELECT\n    sysdate extract_date,\n    from_tz(cast (sysdate as timestamp),'PST') at time zone '\"&LocalTZ&\"' local_extract_date,\n    poa.agent_id,\n    poa.agent_name,\n    ppv1.ppv1_approver,\n    ppv2.ppv2_approver,\n    CASE\n        WHEN (\n            SELECT\n                COUNT(1)\n            FROM\n                apps.fnd_user fu\n            WHERE\n                    sysdate > fu.start_date\n                AND sysdate < nvl(fu.end_date, sysdate + 1)\n                AND fu.employee_id = poa.agent_id\n        ) = 0\n             AND poa.end_date_active < sysdate THEN\n            'No'\n        ELSE\n            'Yes'\n    END active_flag,\n    (\n        SELECT\n            MAX(fu.end_date)\n        FROM\n            apps.fnd_user fu\n        WHERE\n                sysdate > fu.start_date\n            AND sysdate < nvl(fu.end_date, sysdate + 1)\n            AND fu.employee_id = poa.agent_id\n    ) user_end_date,\n    CASE\n        WHEN (\n            SELECT\n                COUNT(agent_id)\n            FROM\n                po.po_headers_all                    pha,\n                apps.org_organization_definitions    ood,\n                po.po_distributions_all              pda\n            WHERE\n                    ood.operating_unit = pha.org_id\n                AND pha.agent_id = poa.agent_id\n                AND pda.po_header_id = pha.po_header_id\n                AND ood.organization_code = '\"&ORG&\"'\n                AND ROWNUM = 1\n        ) + (\n            SELECT\n                COUNT(agent_id)\n            FROM\n                po.po_releases_all                   pra,\n                apps.org_organization_definitions    ood\n            WHERE\n                    ood.operating_unit = pra.org_id\n                AND pra.agent_id = poa.agent_id\n                AND ood.organization_code = '\"&ORG&\"'\n                AND ROWNUM = 1\n        ) > 0 THEN\n            'Yes'\n        ELSE\n            'No'\n    END po_buyer,\n    (\n        CASE\n            WHEN (\n                SELECT\n                    COUNT(inventory_item_id)\n                FROM\n                    inv.mtl_system_items_b    msi,\n                    inv.mtl_parameters        mp\n                WHERE\n                        mp.organization_id = msi.organization_id\n                    AND msi.buyer_id = poa.agent_id\n                    AND mp.organization_code = '\"&ORG&\"'\n            ) > 0 THEN\n                'Yes'\n            ELSE\n                'No'\n        END\n    ) default_buyer,\n    (\n        SELECT\n            hrl.location_code\n        FROM\n            apps.hr_locations         hrl,\n            apps.per_assignments_f    pa\n        WHERE\n                pa.location_id = hrl.location_id\n            AND sysdate BETWEEN pa.effective_start_date AND pa.effective_end_date\n            AND pa.person_id = poa.agent_id\n            AND pa.assignment_id = (\n                SELECT\n                    MAX(pa2.assignment_id)\n                FROM\n                    apps.per_assignments_f pa2\n                WHERE\n                        pa2.person_id = pa.person_id\n                    AND pa2.assignment_type = 'E'\n                    AND pa2.primary_flag = 'Y'\n            )\n            AND ROWNUM = 1\n    ) buyer_location,\n    (\n        SELECT\n            sup.full_name\n        FROM\n            apps.per_people_x         sup,\n            apps.per_assignments_f    pa\n        WHERE\n                sup.person_id = pa.supervisor_id\n            AND sysdate BETWEEN pa.effective_start_date AND pa.effective_end_date\n            AND pa.person_id = poa.agent_id\n            AND pa.assignment_id = (\n                SELECT\n                    MAX(pa2.assignment_id)\n                FROM\n                    apps.per_assignments_f pa2\n                WHERE\n                        pa2.person_id = pa.person_id\n                    AND pa2.assignment_type = 'E'\n                    AND pa2.primary_flag = 'Y'\n            )\n            AND ROWNUM = 1\n    ) supervisor\nFROM\n    apps.po_agents_v poa,\n    (\n        SELECT\n            to_char(ppx.person_id)       AS person_id,\n            ppx.full_name                AS ppv1_approver\n        FROM\n            apps.per_people_x ppx\n    ) ppv1,\n    (\n        SELECT\n            to_char(ppx.person_id)       AS person_id,\n            ppx.full_name                AS ppv2_approver\n        FROM\n            apps.per_people_x ppx\n    ) ppv2\nWHERE\n        1 = 1\n    AND poa.attribute2 = ppv1.person_id (+)\n    AND poa.attribute3 = ppv2.person_id (+)\n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"AGENT_NAME\", \"Buyer Name\"}, {\"EXTRACT_DATE\", \"Extract Date\"}, {\"ACTIVE_FLAG\", \"Buyer Active Flag\"}, {\"PPV1_APPROVER\", \"PPV1 Approver\"}, {\"PPV2_APPROVER\", \"PPV2 Approver\"}, {\"DEFAULT_BUYER\", \"Default Buyer Flag\"}, {\"BUYER_LOCATION\", \"Location\"}, {\"PO_BUYER\", \"PO Buyer Flag\"}, {\"SUPERVISOR\", \"Supervisor Name\"}, {\"USER_END_DATE\", \"User End Date\"}, {\"LOCAL_EXTRACT_DATE\", \"Local Extract Date\"}}),\r\n  #\"Filtered rows\" = Table.SelectRows(#\"Renamed columns\", each [Buyer Name] <> \"Oracle, Production\")\r\nin\r\n  #\"Filtered rows\";\r\nshared Supplier_Contact = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, Query=\"\n  SELECT distinct sysdate extract_date,\n    from_tz(cast (sysdate as timestamp),'PST') at time zone '\"&LocalTZ&\"' local_extract_date,asu.vendor_name\n,hpc.party_name Contact_Name\n,hpr.primary_phone_country_code contact_country\n,hpr.primary_phone_area_code contact_area\n,hpr.primary_phone_number contact_phone\n,hpr.email_address\n,assa.vendor_site_code\n,assa.vendor_site_id\n,asco.vendor_contact_id\n,asco.inactive_date\nFROM\n apps.hz_relationships hr\n,apps.ap_suppliers asu\n,apps.ap_supplier_sites_all assa\n,apps.ap_supplier_contacts asco\n,apps.hz_org_contacts hoc\n,apps.hz_parties hpc\n,apps.hz_parties hpr\n,apps.hz_contact_points hpcp\n,apps.org_organization_definitions ood\nWHERE hoc.party_relationship_id = hr.relationship_id\nAND hr.subject_id = asu.party_id\nAND hr.relationship_code = 'CONTACT'\nAND hr.object_table_name = 'HZ_PARTIES'\nAND asu.vendor_id = assa.vendor_id\nAND hr.object_id = hpc.party_id\nAND hr.party_id = hpr.party_id\nAND asco.relationship_id  = hoc.party_relationship_id\nAND assa.party_site_id = asco.org_party_site_id\nAND hpr.party_type='PARTY_RELATIONSHIP'\nAND hpr.party_id = hpcp.owner_table_id\nAND hpcp.owner_table_name = 'HZ_PARTIES'\nAND OOD.OPERATING_UNIT = ASSA.ORG_ID\nand ood.organization_code = '\"&ORG&\"'\n\n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"CONTACT_NAME\", \"Contact Name\"}, {\"EMAIL_ADDRESS\", \"Email Address\"}, {\"INACTIVE_DATE\", \"Inactive Date\"}, {\"VENDOR_NAME\", \"Supplier Name\"}, {\"VENDOR_SITE_CODE\", \"Supplier Site Code\"}, {\"CONTACT_PHONE\", \"Contact Phone\"}, {\"CONTACT_AREA\", \"Contact Area\"}, {\"CONTACT_COUNTRY\", \"Contact Country\"}, {\"EXTRACT_DATE\", \"Extract Date\"}, {\"LOCAL_EXTRACT_DATE\", \"Local Extract Date\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Supplier = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, \n  Query=\"\n   SELECT\n    sysdate                                                  extract_date,\n    from_tz(cast (sysdate as timestamp),'PST') at time zone '\"&LocalTZ&\"' local_extract_date,\n    xxpov.segment1                                           supplier_number,\n    xxpov.vendor_name,\n    xxpov.vendor_name_alt,\n    xxpovs.vendor_site_id,\n    xxpovs.vendor_id,\n    xxpovs.vendor_site_code,\n    xxpovs.vendor_site_code_alt,\n    (\n        CASE\n            WHEN xxpovs.vendor_site_code_alt IS NOT NULL THEN\n                'Yes'\n            ELSE\n                'No'\n        END\n    ) production_supplier_flag,\n    xxpovs.creation_date                                     supplier_creation_date,\n    xxpovs.last_update_date                                  supplier_last_update_date,\n    xxpovs.pay_site_flag,\n    xxpovs.purchasing_site_flag,\n    xxpovs.city,\n    xxpovs.country,\n    xxpovs.country_of_origin_code,\n    (\n        CASE\n            WHEN least(nvl(xxpov.end_date_active, sysdate + 1), nvl(xxpovs.inactive_date, sysdate + 1)) < trunc(sysdate) THEN\n                'No'\n            ELSE\n                'Yes'\n        END\n    ) active_supplier_flag,\n    CASE\n        WHEN nvl(xxpov.end_date_active, sysdate + 1) > nvl(xxpovs.inactive_date, sysdate + 1) THEN\n            xxpovs.inactive_date\n        ELSE\n            xxpov.end_date_active\n    END inactive_date,\n    xxpovs.invoice_currency_code,\n    xxpovs.payment_currency_code,\n    xxpovs.payment_method_lookup_code,\n    xxpov.vendor_type_lookup_code,\n    decode(xxpov.attribute1, 'Y', 'Yes', 'No')              internal_supplier_flag,\n    decode(xxpov.attribute4, 'Y', 'Yes', 'No')              isupplier_forecast_flag,\n    xxpovs.fob_lookup_code,\n    xxpovs.freight_terms_lookup_code,\n    (\n        CASE\n            WHEN (\n                SELECT\n                    COUNT(1)\n                FROM\n                    apps.hz_relationships    hr1,\n                    apps.hz_parties          hp1,\n                    apps.fnd_user            fu\n                WHERE\n                        1 = 1\n                    AND hr1.object_table_name = 'HZ_PARTIES'\n                    AND hr1.object_type = 'ORGANIZATION'\n                    AND hp1.party_id = hr1.object_id\n                    AND fu.person_party_id = hr1.subject_id\n                    AND xxpov.party_id = hp1.party_id\n                    AND nvl(fu.end_date, sysdate + 1) > sysdate\n            ) > 0 THEN\n                'Yes'\n            ELSE\n                'No'\n        END\n    ) isupplier_flag,\n    apt.name                                                 payment_term,\n    CASE\n        WHEN nvl((\n            SELECT\n                MIN(poa.creation_date)\n            FROM\n                apps.po_acceptances_v    poa, po.po_headers_all        pha\n            WHERE\n                    pha.vendor_id = xxpov.vendor_id\n                AND pha.vendor_id = xxpov.vendor_id\n                AND poa.po_header_id = pha.po_header_id\n                AND pha.vendor_site_id = xxpovs.vendor_site_id\n                AND poa.accepting_party = 'S'\n        ), sysdate) > nvl((\n            SELECT\n                MIN(poa.creation_date)\n            FROM\n                apps.po_acceptances_v    poa, po.po_releases_all       pra, po.po_headers_all        pha\n            WHERE\n                    pha.vendor_id = xxpov.vendor_id\n                AND pha.vendor_id = xxpov.vendor_id\n                AND poa.po_release_id = pra.po_release_id\n                AND pha.vendor_site_id = xxpovs.vendor_site_id\n                AND poa.accepting_party = 'S'\n                AND pha.po_header_id = pra.po_header_id\n        ), sysdate) THEN\n            (\n                SELECT\n                    MIN(poa.creation_date)\n                FROM\n                    apps.po_acceptances_v    poa,\n                    po.po_releases_all       pra,\n                    po.po_headers_all        pha\n                WHERE\n                        pha.vendor_id = xxpov.vendor_id\n                    AND pha.vendor_id = xxpov.vendor_id\n                    AND poa.po_release_id = pra.po_release_id\n                    AND pha.vendor_site_id = xxpovs.vendor_site_id\n                    AND poa.accepting_party = 'S'\n                    AND pha.po_header_id = pra.po_header_id\n            )\n        ELSE\n            (\n                SELECT\n                    MIN(poa.creation_date)\n                FROM\n                    apps.po_acceptances_v    poa,\n                    po.po_headers_all        pha\n                WHERE\n                        pha.vendor_id = xxpov.vendor_id\n                    AND pha.vendor_id = xxpov.vendor_id\n                    AND poa.po_header_id = pha.po_header_id\n                    AND pha.vendor_site_id = xxpovs.vendor_site_id\n                    AND poa.accepting_party = 'S'\n            )\n    END first_po_acceptance,\n    CASE\n        WHEN nvl((\n            SELECT\n                MAX(poa.creation_date)\n            FROM\n                apps.po_acceptances_v    poa, po.po_headers_all        pha\n            WHERE\n                    pha.vendor_id = xxpov.vendor_id\n                AND pha.vendor_id = xxpov.vendor_id\n                AND poa.po_header_id = pha.po_header_id\n                AND pha.vendor_site_id = xxpovs.vendor_site_id\n                AND poa.accepting_party = 'S'\n        ), sysdate) > nvl((\n            SELECT\n                MIN(poa.creation_date)\n            FROM\n                apps.po_acceptances_v    poa, \n                po.po_releases_all       pra, \n                po.po_headers_all        pha\n            WHERE\n                    pha.vendor_id = xxpov.vendor_id\n                AND pha.vendor_id = xxpov.vendor_id\n                AND poa.po_release_id = pra.po_release_id\n                AND pha.vendor_site_id = xxpovs.vendor_site_id\n                AND poa.accepting_party = 'S'\n                AND pha.po_header_id = pra.po_header_id\n        ), sysdate) THEN\n            (\n                SELECT\n                    MAX(poa.creation_date)\n                FROM\n                    apps.po_acceptances_v    poa,\n                    po.po_releases_all       pra,\n                    po.po_headers_all        pha\n                WHERE\n                        pha.vendor_id = xxpov.vendor_id\n                    AND pha.vendor_id = xxpov.vendor_id\n                    AND poa.po_release_id = pra.po_release_id\n                    AND pha.vendor_site_id = xxpovs.vendor_site_id\n                    AND poa.accepting_party = 'S'\n                    AND pha.po_header_id = pra.po_header_id\n            )\n        ELSE\n            (\n                SELECT\n                    MAX(poa.creation_date)\n                FROM\n                    apps.po_acceptances_v    poa,\n                    po.po_headers_all        pha\n                WHERE\n                        pha.vendor_id = xxpov.vendor_id\n                    AND pha.vendor_id = xxpov.vendor_id\n                    AND poa.po_header_id = pha.po_header_id\n                    AND pha.vendor_site_id = xxpovs.vendor_site_id\n                    AND poa.accepting_party = 'S'\n            )\n    END last_po_acceptance,\n    (\n        SELECT\n            MAX(api.invoice_date)\n        FROM\n            apps.ap_invoices_all api\n        WHERE\n                api.org_id = xxpovs.org_id\n            AND api.vendor_site_id = xxpovs.vendor_site_id\n    ) last_invoice_date,\n    (\n        SELECT\n            COUNT(1)\n        FROM\n            apps.hz_relationships    hr1,\n            apps.hz_parties          hp1,\n            apps.fnd_user            fu\n        WHERE\n                1 = 1\n            AND hr1.object_table_name = 'HZ_PARTIES'\n            AND hr1.object_type = 'ORGANIZATION'\n            AND hp1.party_id = hr1.object_id\n            AND fu.person_party_id = hr1.subject_id\n            AND xxpov.party_id = hp1.party_id\n            AND nvl(fu.end_date, sysdate + 1) > sysdate\n    ) isupplier_user_count,\n    xxpov.attribute5                                         supplier_class,\n    nvl(xxvd.vendor_category, 'Unassigned')                  supplier_category,\n    nvl(xxvd.ssm_lead, 'Unassigned')                         ssm_lead,\n    nvl(xxvd.master_vendor_name, xxpov.vendor_name)          master_supplier,\n    nvl(xxvd.attribute1, 'NA')                               key_and_risk_flag,\n    decode(xxvd.attribute2, 'Y', 'Yes', 'No')                kpi_flag\nFROM\n    apps.po_vendors                      xxpov,\n    apps.po_vendor_sites_all             xxpovs,\n    apps.org_organization_definitions    ood,\n    apps.hr_operating_units              hou,\n    apps.ap_terms_v                      apt,\n    xxdims.xx_vendor_dim                 xxvd\nWHERE\n        1 = 1\n    AND xxpov.employee_id IS NULL\n    AND xxpov.vendor_id = xxpovs.vendor_id\n    AND xxpovs.org_id = ood.operating_unit\n    AND hou.organization_id = ood.operating_unit\n    AND xxpovs.terms_id = apt.term_id (+)\n    AND xxpov.vendor_id = xxvd.vendor_id (+)\n    AND ood.organization_code = '\"&ORG&\"'\n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"EXTRACT_DATE\", \"Extract Date\"}, {\"SUPPLIER_CREATION_DATE\", \"Supplier Creation Date\"}, {\"SUPPLIER_LAST_UPDATE_DATE\", \"Supplier Last Update Date\"}, {\"SUPPLIER_NUMBER\", \"Supplier Number\"}, {\"VENDOR_NAME\", \"Supplier Name\"}, {\"VENDOR_NAME_ALT\", \"Supplier Name Alternate\"}, {\"VENDOR_SITE_CODE\", \"Supplier Site Code\"}, {\"VENDOR_SITE_CODE_ALT\", \"Supplier Site Code Alternate\"}, {\"PRODUCTION_SUPPLIER_FLAG\", \"Production Supplier Flag\"}, {\"PAY_SITE_FLAG\", \"Pay Site Flag\"}, {\"PURCHASING_SITE_FLAG\", \"Purchasing Site Flag\"}, {\"CITY\", \"City\"}, {\"COUNTRY\", \"Country\"}, {\"COUNTRY_OF_ORIGIN_CODE\", \"Country of Origin\"}, {\"ACTIVE_SUPPLIER_FLAG\", \"Active Supplier Flag\"}, {\"INACTIVE_DATE\", \"Inactive Date\"}, {\"INVOICE_CURRENCY_CODE\", \"Invoice Currency\"}, {\"PAYMENT_CURRENCY_CODE\", \"Payment Currency\"}, {\"PAYMENT_METHOD_LOOKUP_CODE\", \"Payment Method\"}, {\"VENDOR_TYPE_LOOKUP_CODE\", \"Supplier Type\"}, {\"ISUPPLIER_FORECAST_FLAG\", \"ISupplier Forecast Flag\"}, {\"FOB_LOOKUP_CODE\", \"FOB\"}, {\"FREIGHT_TERMS_LOOKUP_CODE\", \"Freight Term\"}, {\"PAYMENT_TERM\", \"Payment Term\"}, {\"ISUPPLIER_FLAG\", \"ISupplier Flag\"}, {\"FIRST_PO_ACCEPTANCE\", \"ISupplier First Acceptance\"}, {\"LAST_PO_ACCEPTANCE\", \"ISupplier Last Acceptance\"}, {\"INTERNAL_SUPPLIER_FLAG\", \"Internal Supplier Flag\"}, {\"LAST_INVOICE_DATE\", \"Last Invoice Date\"}, {\"ISUPPLIER_USER_COUNT\", \"ISupplier User Count\"}, {\"SUPPLIER_CLASS\", \"Supplier Class\"}, {\"SSM_LEAD\", \"SSM Lead\"}, {\"SUPPLIER_CATEGORY\", \"Supplier Category\"}, {\"MASTER_SUPPLIER\", \"Master Supplier\"}, {\"KEY_AND_RISK_FLAG\", \"Key and Risk Flag\"}, {\"KPI_FLAG\", \"KPI Required Flag\"}, {\"LOCAL_EXTRACT_DATE\", \"Local Extract Date\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared ORG = let\r\n  ORG = \"GEP\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type text]\r\nin\r\n  ORG;\r\nshared LocalTZ = let\r\n  Local = \"Europe/Berlin\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type text]\r\nin\r\n  Local;\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"Buyer","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Buyer.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Local Extract Date","dataType":"dateTime"},{"name":"AGENT_ID","dataType":"int64"},{"name":"Buyer Name","dataType":"string"},{"name":"PPV1 Approver","dataType":"string"},{"name":"PPV2 Approver","dataType":"string"},{"name":"Buyer Active Flag","dataType":"string"},{"name":"User End Date","dataType":"dateTime"},{"name":"PO Buyer Flag","dataType":"string"},{"name":"Default Buyer Flag","dataType":"string"},{"name":"Location","dataType":"string"},{"name":"Supervisor Name","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2021-09-22T05:22:50.0468163+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/58e4b970-3185-4974-b65e-cffb32968375/Buyer.csv?snapshot=2021-09-22T05%3A22%3A50.0104433Z"}]},{"$type":"LocalEntity","name":"Supplier_Contact","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Supplier_Contact.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Local Extract Date","dataType":"dateTime"},{"name":"Supplier Name","dataType":"string"},{"name":"Contact Name","dataType":"string"},{"name":"Contact Country","dataType":"string"},{"name":"Contact Area","dataType":"string"},{"name":"Contact Phone","dataType":"string"},{"name":"Email Address","dataType":"string"},{"name":"Supplier Site Code","dataType":"string"},{"name":"VENDOR_SITE_ID","dataType":"double"},{"name":"VENDOR_CONTACT_ID","dataType":"double"},{"name":"Inactive Date","dataType":"dateTime"}],"partitions":[{"name":"Part001","refreshTime":"2021-09-22T05:06:34.4645825+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/58e4b970-3185-4974-b65e-cffb32968375/Supplier_Contact.csv?snapshot=2021-09-22T05%3A06%3A34.4356017Z"}]},{"$type":"LocalEntity","name":"Supplier","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Supplier.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Local Extract Date","dataType":"dateTime"},{"name":"Supplier Number","dataType":"string"},{"name":"Supplier Name","dataType":"string"},{"name":"Supplier Name Alternate","dataType":"string"},{"name":"VENDOR_SITE_ID","dataType":"double"},{"name":"VENDOR_ID","dataType":"double"},{"name":"Supplier Site Code","dataType":"string"},{"name":"Supplier Site Code Alternate","dataType":"string"},{"name":"Production Supplier Flag","dataType":"string"},{"name":"Supplier Creation Date","dataType":"dateTime"},{"name":"Supplier Last Update Date","dataType":"dateTime"},{"name":"Pay Site Flag","dataType":"string"},{"name":"Purchasing Site Flag","dataType":"string"},{"name":"City","dataType":"string"},{"name":"Country","dataType":"string"},{"name":"Country of Origin","dataType":"string"},{"name":"Active Supplier Flag","dataType":"string"},{"name":"Inactive Date","dataType":"dateTime"},{"name":"Invoice Currency","dataType":"string"},{"name":"Payment Currency","dataType":"string"},{"name":"Payment Method","dataType":"string"},{"name":"Supplier Type","dataType":"string"},{"name":"Internal Supplier Flag","dataType":"string"},{"name":"ISupplier Forecast Flag","dataType":"string"},{"name":"FOB","dataType":"string"},{"name":"Freight Term","dataType":"string"},{"name":"ISupplier Flag","dataType":"string"},{"name":"Payment Term","dataType":"string"},{"name":"ISupplier First Acceptance","dataType":"dateTime"},{"name":"ISupplier Last Acceptance","dataType":"dateTime"},{"name":"Last Invoice Date","dataType":"dateTime"},{"name":"ISupplier User Count","dataType":"double"},{"name":"Supplier Class","dataType":"string"},{"name":"Supplier Category","dataType":"string"},{"name":"SSM Lead","dataType":"string"},{"name":"Master Supplier","dataType":"string"},{"name":"Key and Risk Flag","dataType":"string"},{"name":"KPI Required Flag","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2021-09-22T05:24:15.2317018+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/58e4b970-3185-4974-b65e-cffb32968375/Supplier.csv?snapshot=2021-09-22T05%3A24%3A15.2050363Z"}]}]}