{"name":"Mapping","description":"","version":"1.0","culture":"en-US","modifiedTime":"2021-03-24T22:21:22.1169252+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"Planner_Code_Mapping":{"queryId":"e8de7cdb-c0d9-4eb9-88dd-e5af4025752c","queryName":"Planner_Code_Mapping","loadEnabled":true},"Subinventory_Mapping":{"queryId":"01d58104-69a6-4ede-ae02-539f3d857865","queryName":"Subinventory_Mapping","loadEnabled":true},"Local_Item_Category":{"queryId":"ec892f56-867d-46a5-9171-d87657af6821","queryName":"Local_Item_Category","loadEnabled":true},"GL_Account_Mapping":{"queryId":"4e795055-17f6-4052-be76-aef01ec0626c","queryName":"GL_Account_Mapping","loadEnabled":true},"GL_Department_Mapping":{"queryId":"7efa4a76-2216-40b3-a426-29f067fa3262","queryName":"GL_Department_Mapping","loadEnabled":true}},"document":"section Section1;\r\nshared Planner_Code_Mapping = let\r\n  Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"hVpdb902DP0rRh721GJI2vRd9qVtzZLsSfZ1sqIYsjXYCgxJkLbA9u+nD8vXlkj3JbHPMSmKpCjKvh8/Xg3/PDw9Pb4W1fPnx6s3623z+vz9ZXM/vD5//v7nt2L87+Xx6tObj1fvr2+l5Xtxsn89MpqxkP1g9ugAGCgRULFc3xmqsdd7nIkxf/Dm53fXt9nImLgd+8x7wQwkuMZxb4Yn9njd4Op1cXN9i1gji2rmOtOBOEcjTzorctROMY+DVYpaYHH04Wp+m+rtS9MLGFMPtdY5RT8l7ndmFd0eWzyZws731mcD4cl6j5fszDRnighrneHOkhS1mSams8mTwMFVHo/7t/esyX2PwHZADA2ab9/dZFHF8fD8zYcP6PMZ7qJrQ5t6dvEhAhs2DEgcnPKCndBBc1ziPlcwKchz0uV0kQfCh77ODBw0N5JlsGSj5kiFyeFlNiwxRDDVgOhbXPNd4hJ0ceKFArCVKJHFtbot8zLyrMZLAabA+eF9urxRW30gLKq7HJcI5p/dwzHHXR61XMNmciSlScqHcJkoopEgNEH4ROsQ4h5//p563q1l0iiK0RTjCwZOuQpDMmUpJiD0UZy1gqQkSR3iqIdqVmquYMSdFxc8MqkDikwEfZQjFHWI43Nqikb3JSdcTnHWPJKSJHWIU+bRaY/AhMeA0OKmSKaiJiNDMZJi3DgEdQCTHtGurBNFguQkzQUCHY6U8a6jyLhSUJVOcuSjb2owzmI1I4KL2+iW10ASpBGG1cN4R8jNuH9JGetfkvsBQcX5R2KoibI4lUTld/sRXvp1LZgGdeeKlL8s1N3GkOuwVVe9HJgxduvfepEk7aojOdes2OuBCXbiKqJLz46LrF3AehE0QatrVrkWR05i5IPY+uJyCkDsC51eboZr31CCnI7qi8n3HevFtiurc00ljFry0W0l8OvEBwlq3O4KuNSibyBNRmTYZE56qnyjM7agt6P4JtDJhKtIdWyqlb899YXq7cY73V/EDlLFHzNyE/wxg5wNxmiKWXzjsxgbhSIMRjgDCBdE27AgtEyNvcuDy1WUWfv49SLOh2RQ2BfXkvtW2P4rhFkzDSaXZjAnlg6IpevBos4GiPnn3ZJlYHg2uAwxt9A547Yl1GC3J6EEjYajWqYmHnvySOEEEMR6t4dZwwUUJ+aP/FXrdjaTzhsNlFeTpxADdQI9qSZXt2QxuowPK5Y8qLaS0qkPhMK8ejNkMzO9MiP3u/uubvgZowNNTw9fv3756+nxs0UmZUfijYLtSRAP+ZI6xd0YubsxEcI5TXO+MsUKFUEYChR37aETr1HblnqHlLt47zfilHR+Ymfu/On+FeKSmLzqnffCvxUKyy0F5wR0axqRBxSVKKox1JmLKybrIJDlW1Iz1wRhExAd3XlgSc69D/wmgOTgQlUYx36bfMz9/02kwn2HMFYbJRQpnzQpaV1DyUUKl5O0nDyS07ScPpDzOUp5ZY1QEis3czyI1GJcbi9lPaHmfN1JMEa60o3sTQcr8swEP3GwrEX8TSjn26XjPbFNJ2PHgjxdPIy1DbG/rlo+XHYIKAg9kSmwNaRJKU1L+eS/eT+j6X/tX43WaLmPlRYpdNbKFgTvHbBeLJl3dDiIJbDDyIYuHpqklvwKCYtm2CVhLokUO6biDtkogNh5FvVeXzJUpLqckrzLdsXN1FMvmOo0FUis4kZKuAdN1VWGrnzIQPaUbmpv6+ZyPdD4Kea5Es9iBO2PXZ5LT11Ufx6ObZ5JTnC+bQq6dh2UHbXsU08b0Gde+ZcO61V0ALliQi8WprJvxfSpKMGMTLk+Rf+0+2rgAocdG5aND+NMRTRHobxqbJc593pedrndTDsBpb/LamBg8N7dXs68sk/o/YR8x+/zMBMJsZypWCK56/NmRhMjzG4mdhuq2kmKiXHACwUZhyXZ5izZljhAxRELl4wK70iI7MI67Lg3D4jOkHoWRZJvadCyZR7xtPGJZSHFl3xAgxsdiNjtcDwWOKEpAihCksFblKEUkBS1JGN0ciY0EuMI4sA5eHHGGXKXPNjlwb3TTJf38qozvLlEmYGnjH/JiBKaIMLXT4RY81LneYlY65Rk75AcOOM24gYSM8WNxkarS0XAuXVDP45uSvXDH9cRa4Dbhd0H9F1EZ65OvRhkgG9X6zQIW0dZoqMUwO1yGwN8c5mh1W1aSHSXcA+mTZ5t6qnxb31en789f/vv5bEwfz+/rCnG9GjHkMm4/ARDYmHXV+19ilk7OiivsDO45iCZUlPmlTN08EuiSPbGKNCnBJ5sZjeGNN7YMftExHBXn0aWeCHO83cXuu7hqSgfnjLOeUF+eSrkw7/rDH1YIBlEwGSqVqURl1ZRm3xa11x1kP6CJrgm+fo8M+FSKv09zAzCF5Ttd2ruPrUnX7QbJroEsjYKrkzyi452glZB8qMQ1VungUxM0jbJE2kBPlLJSL0Z3YyqZHxnZ/rzgZL7YrAHOzYMtjVKwF4ImxdbpZ/+Bw==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t, Column2 = _t, Column3 = _t]),\r\n  #\"Promoted headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars = true])\r\nin\r\n  #\"Promoted headers\";\r\nshared Subinventory_Mapping = let\r\n  Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"ddXJkqMwDADQX6FyDl3pLKRzNI4AFWAzsslkKtXF///FyCzdDjanoCeDd+X12uVC1kXTm2q332lbAe2+96+d1Mogy/hbKrhPSnBHm5BVLvUbjLne2ERICd3bh+7QaTtQR28K+EFggB7AXJQ4YQO1Ja2wZmyLMjV9Loz5NyYLIIuy8pqjMh2/gNoNpqV8RqupHKYRcgCkRJMS2J6UGVvUDeRAom8jndS6zdHroubZD4XIKVyKMYXPqfd1ildC4ZMT8OxAmdkbUYJbBhJ/59gMvApef43UlTWWhZ9+pFcrq/yP6BKNHZdsTceInTxrPyNL0B5jeIrhOYaXGGYxvMYQKirEuM3rlNIqkTSfPS9wuQ55acJX/vSiGRqRc8o9YoFSjOfFJWmZvWxAKNK6nfmw4Vvtj3Hf4FOcz3G+xDlLNwaTpRvdZulGx9c4f8X5FmfquIi4IblfVKWnx7U+bpGd4ptMtNyP5S6bh0zcWd3/PDm1y9Qt8K2Y5BBSpNUxoFBOgZxDSd1pih4qewlaZ4FcA/kK5LaWB5AR6u4Vi0JgYqQrq81UX0qUA5c88ojDksRcIxes59q+xFyHPqY6tEibIr2FrR9pZXmnPFHQK/BfIEA1l9iFjMT08OkDf8QdCk94l93kfsVCy/8eMFa/0b7/Aw==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Subinventory Name\" = _t, #\"Subinventory Group\" = _t])\r\nin\r\n  Source;\r\nshared Local_Item_Category = let\r\n  Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Item Number\" = _t, #\"Wavelength Color\" = _t, #\"Power Group\" = _t, #\"Measure Production Output\" = _t, #\"Measure Shipment OTD\" = _t, Wavelength = _t, Model = _t, #\"Forecast Type\" = _t, #\"Production Group\" = _t, #\"Forecast Group\" = _t])\r\nin\r\n  Source;\r\nshared GL_Account_Mapping = let\r\n  Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"GL Account Code\" = _t, #\"Account Category\" = _t, Nature = _t, #\"Account Group\" = _t])\r\nin\r\n  Source;\r\nshared GL_Department_Mapping = let\r\n  Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"GL Department Code\" = _t, #\"Department Product\" = _t, #\"Department Group\" = _t, #\"Department Alias\" = _t])\r\nin\r\n  Source;\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"Planner_Code_Mapping","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Planner_Code_Mapping.csv"},"attributes":[{"name":"Planner Code","dataType":"string"},{"name":"Planner Group","dataType":"string"},{"name":"Planner Product Type","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2021-03-24T22:21:57.7938176+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/dbb59174-dc71-4560-a7d8-fe1ab050dd28/Planner_Code_Mapping.csv?snapshot=2021-05-17T10%3A39%3A08.1505937Z"}]},{"$type":"LocalEntity","name":"Subinventory_Mapping","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Subinventory_Mapping.csv"},"attributes":[{"name":"Subinventory Name","dataType":"string"},{"name":"Subinventory Group","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2021-03-24T22:22:29.024935+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/dbb59174-dc71-4560-a7d8-fe1ab050dd28/Subinventory_Mapping.csv?snapshot=2021-05-17T10%3A39%3A08.2696791Z"}]},{"$type":"LocalEntity","name":"Local_Item_Category","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Local_Item_Category.csv"},"attributes":[{"name":"Item Number","dataType":"string"},{"name":"Wavelength Color","dataType":"string"},{"name":"Power Group","dataType":"string"},{"name":"Measure Production Output","dataType":"string"},{"name":"Measure Shipment OTD","dataType":"string"},{"name":"Wavelength","dataType":"string"},{"name":"Model","dataType":"string"},{"name":"Forecast Type","dataType":"string"},{"name":"Production Group","dataType":"string"},{"name":"Forecast Group","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2021-03-24T22:23:00.0446665+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/dbb59174-dc71-4560-a7d8-fe1ab050dd28/Local_Item_Category.csv?snapshot=2021-05-17T10%3A39%3A08.3117090Z"}]},{"$type":"LocalEntity","name":"GL_Account_Mapping","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"GL_Account_Mapping.csv"},"attributes":[{"name":"GL Account Code","dataType":"string"},{"name":"Account Category","dataType":"string"},{"name":"Nature","dataType":"string"},{"name":"Account Group","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2021-03-24T22:23:31.5265616+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/dbb59174-dc71-4560-a7d8-fe1ab050dd28/GL_Account_Mapping.csv?snapshot=2021-05-17T10%3A39%3A08.3627459Z"}]},{"$type":"LocalEntity","name":"GL_Department_Mapping","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"GL_Department_Mapping.csv"},"attributes":[{"name":"GL Department Code","dataType":"string"},{"name":"Department Product","dataType":"string"},{"name":"Department Group","dataType":"string"},{"name":"Department Alias","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2021-03-24T22:24:02.6286148+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/dbb59174-dc71-4560-a7d8-fe1ab050dd28/GL_Department_Mapping.csv?snapshot=2021-05-17T10%3A39%3A08.4377982Z"}]}]}