{"name":"COHREP_SITE_OM_TRX1","description":"","version":"1.0","culture":"en-US","modifiedTime":"2021-10-11T18:38:19.7906901+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":true,"queriesMetadata":{"Sales_Hold":{"queryId":"497f0c22-cee0-4d5f-8a4b-3dabf391bc94","queryName":"Sales_Hold","loadEnabled":true},"Sales_Order":{"queryId":"f2cf3a71-d8fd-4a2e-8a6e-b945b59f4f22","queryName":"Sales_Order","loadEnabled":true},"Sales_Line_Attachment":{"queryId":"d6280c18-67ac-4e0d-b33d-3ef8075417bf","queryName":"Sales_Line_Attachment","loadEnabled":true},"Sales_Shipment":{"queryId":"f4a20b67-687b-497c-a22e-8c7ba738ff0d","queryName":"Sales_Shipment","loadEnabled":true},"Sales_Backlog_History":{"queryId":"00f9936c-c65c-48f3-be1c-7dd85270c4ef","queryName":"Sales_Backlog_History","loadEnabled":true},"ORG":{"queryId":"8978842d-7087-4722-9e46-75d81c6d00ee","queryName":"ORG"},"CUSTORG":{"queryId":"a8094e3d-dfc2-4ce8-9cd8-eace0626eb00","queryName":"CUSTORG"},"LocalTZ":{"queryId":"a8827812-3295-456b-ae5c-9df6ef9d95e3","queryName":"LocalTZ"}},"document":"section Section1;\r\nshared Sales_Hold = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, Query=\"\n SELECT\n    sysdate extract_date,\n   from_tz(cast (sysdate as timestamp),'PST') at time zone '\"&LocalTZ&\"' local_extract_date,\n   ooh.hold_source_id hold_source_id,\n   decode(ooh.line_id, NULL , 'ORDER', 'LINE') hold_level,\n   ooh.header_id,\n   ooh.line_id,\n   ohs.hold_id,\n   ohd.name hold_reason,\n   ooh.released_flag hold_release_flag,\n   ooh.creation_date hold_creation_date,\n   (select user_name \n   from applsys.fnd_user \n   where user_id = ooh.created_by) hold_created_by\nFROM\n   apps.oe_order_holds_all ooh,\n   apps.oe_hold_releases hrl,\n   apps.fnd_user usr,\n   apps.fnd_user rusr,\n   apps.oe_hold_definitions ohd,\n   apps.oe_hold_sources_all ohs \nWHERE\n   header_id IN \n   (\n      SELECT\n         header_id \n      FROM\n         apps.oe_order_lines_all oel2,\n         inv.mtl_parameters mp2 \n      WHERE\n         mp2.organization_id = oel2.ship_from_org_id \n         AND mp2.organization_code = '\"&ORG&\"'\n   )\n   AND usr.user_id = ooh.created_by \n   AND rusr.user_id ( + ) = hrl.created_by \n   AND hrl.hold_release_id ( + ) = ooh.hold_release_id \n   AND rusr.user_id ( + ) = hrl.created_by \n   AND hrl.hold_release_id ( + ) = ooh.hold_release_id \n   AND ohd.hold_id ( + ) = ohs.hold_id \n   AND ohs.hold_source_id = ooh.hold_source_id \n   AND ooh.released_flag = 'N'\n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"HOLD_REASON\", \"Hold Reason\"}, {\"HOLD_RELEASE_FLAG\", \"Hold Release Flag\"}, {\"HOLD_LEVEL\", \"Hold Level\"}, {\"HOLD_CREATION_DATE\", \"Creation Date\"}, {\"HOLD_CREATED_BY\", \"Created By\"}, {\"EXTRACT_DATE\", \"Extract Date\"}, {\"LOCAL_EXTRACT_DATE\", \"Local Extract Date\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Sales_Order = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, \n  Query=\"\n  SELECT\n    sysdate extract_date,\n   from_tz(cast (sysdate as timestamp),'PST') at time zone '\"&LocalTZ&\"' local_extract_date,\n   TO_DATE(TO_CHAR((from_tz(cast (oel.actual_Shipment_date as timestamp),'PST') at time zone '\"&LocalTZ&\"'),'DD-MON-RRRR')) local_actual_ship,\n    mp.organization_code,\n    (\n        SELECT\n            name\n        FROM\n            apps.hr_operating_units hou\n        WHERE\n            hou.organization_id = oeh.org_id\n    ) booking_ou,\n    oeh.order_number,\n    oeh.header_id,\n    hp.organization_name_phonetic                                    end_customer_phonetic,\n    hp2.organization_name_phonetic                                   customer_phonetic,\n    hp.party_name                                                    end_customer_name,\n    oel.line_number,\n    oel.shipment_number,\n    oel.open_flag,\n    oel.cancelled_flag,\n    oel.ship_set_id,\n    ott1.name                                                        order_type,\n    oeh.order_type_id,\n    ott2.name                                                        line_type,\n    oel.line_type_id,\n    otta2.attribute4                                                 revenue_flag,\n    msi.inventory_item_id,\n    msi.segment1                                                     item_number,\n    oeh.transactional_curr_code,\n    oel.unit_selling_price,\n    CASE\n        WHEN oel.line_category_code = 'RETURN' THEN\n            oel.ordered_quantity * - 1\n        ELSE\n            oel.ordered_quantity\n    END ordered_quantity,\n    oel.booked_flag,\n    CASE\n        WHEN oel.line_category_code = 'RETURN' THEN\n            nvl(oel.shipped_quantity, 0) * - 1\n        ELSE\n            nvl(oel.shipped_quantity, 0)\n    END shipped_quantity,\n    decode(hca2.customer_type, 'R', 'External', 'Internal')          customer_type,\n    hp2.party_name                                                   customer,\n    oel.flow_status_code,\n    oel.shipment_priority_code,\n    oel.shippable_flag,\n    oel.shipping_method_code,\n    oel.subinventory,\n    oeh.attribute10                                                  market,\n    oeh.attribute1                                                   so_category_code,\n    oeh.attribute4                                                   regional_location,\n    otta2.attribute10                                                reporting_entity,\n    otta2.attribute6                                                 sales_or_service,\n    oel.line_category_code,\n    oel.fob_point_code,\n    oel.attribute6                                                   ci_value,\n    oel.freight_terms_code,\n    xxcraa.country,\n    xxcraa.city,\n    oel.actual_fulfillment_date,\n    oel.actual_shipment_date,\n    oel.schedule_ship_date,\n    oel.request_date,\n    oel.promise_date,\n    oeh.orig_sys_document_ref,\n    oos.name                                                         source_name,\n    msi.planner_code,\n    fu1.user_name                                                    created_by,\n    fu2.user_name                                                    last_updated_by,\n    oel.creation_date,\n    oel.last_update_date,\n    srep.name                                                        sales_rep,\n    oel.line_id,\n    oeh.booked_date,\n    oel.end_customer_id,\n    nvl(nvl((\n        SELECT\n            actual_cost\n        FROM\n            apps.mtl_material_transactions mmt\n        WHERE\n                mmt.trx_source_line_id = oel.line_id\n            AND mmt.organization_id = mp.organization_id\n            AND mmt.inventory_item_id = oel.inventory_item_id\n            AND mmt.transaction_type_id IN(\n                62, 33\n            )\n            AND ROWNUM = 1\n    ),(\n        SELECT\n            item_cost\n        FROM\n            apps.cst_item_costs cic\n        WHERE\n                cic.organization_id = mp.organization_id\n            AND cic.inventory_item_id = oel.inventory_item_id\n            AND cic.cost_type_id = 1\n    )), 0) unit_cost,\n    round(((\n        SELECT\n            actual_cost\n        FROM\n            apps.mtl_material_transactions mmt\n        WHERE\n                mmt.trx_source_line_id = oel.line_id\n            AND mmt.organization_id = mp.organization_id\n            AND mmt.inventory_item_id = oel.inventory_item_id\n            AND mmt.transaction_type_id IN(\n                62, 33\n            )\n            AND ROWNUM = 1\n    )) * nvl((\n        SELECT\n            conversion_rate\n        FROM\n            apps.gl_daily_rates                  gdr, apps.org_organization_definitions    ood, apps.gl_sets_of_books                sob\n        WHERE\n                gdr.to_currency = 'USD'\n            AND gdr.from_currency = sob.currency_code\n            AND sob.set_of_books_id = ood.set_of_books_id\n            AND ood.organization_code = mp.organization_code\n            AND gdr.conversion_date = trunc(oel.actual_shipment_date)\n            AND conversion_type = 'Corporate'\n    ), 1), 4) unit_cost_usd,\n    (\n        SELECT\n            SUM(nvl((\n                SELECT\n                    conversion_rate\n                FROM\n                    apps.gl_daily_rates gdr\n                WHERE\n                        gdr.to_currency = 'USD'\n                    AND gdr.from_currency = rcta.invoice_currency_code\n                    AND gdr.conversion_date = trunc(rcta.trx_date)\n                    AND gdr.conversion_type = 'Corporate'\n            ), 1) * nvl(rctl.revenue_amount, 0))\n        FROM\n            apps.ra_customer_trx_lines_all    rctl,\n            apps.ra_customer_trx_all          rcta\n        WHERE\n                1 = 1\n            AND rctl.interface_line_attribute1 = to_char(oeh.order_number)\n            AND rctl.interface_line_attribute6 = to_char(oel.line_id)\n            AND rcta.interface_header_context = 'ORDER ENTRY'\n            AND rctl.interface_line_context = 'ORDER ENTRY'\n            AND rctl.customer_trx_id = rcta.customer_trx_id\n    ) revenue_amount_usd,\n    nvl((\n        SELECT\n            conversion_rate\n        FROM\n            apps.gl_daily_rates gdr\n        WHERE\n                gdr.to_currency = 'USD'\n            AND gdr.from_currency = oeh.transactional_curr_code\n            AND gdr.conversion_type = 'Corporate'\n            AND gdr.conversion_date = trunc(nvl(oeh.booked_date, oeh.creation_date))\n    ), 1) book_usd_rate,\n    CASE\n        WHEN nvl((\n            SELECT\n                COUNT(source_line_id)\n            FROM\n                apps.wsh_delivery_details wdd\n            WHERE\n                wdd.source_line_id = oel.line_id\n        ), 0) + nvl((\n            SELECT\n                COUNT(oe_order_line_id)\n            FROM\n                apps.rcv_shipment_lines rsl\n            WHERE\n                    oel.line_id = rsl.oe_order_line_id\n                AND rsl.source_document_code = 'RMA'\n                AND oel.header_id = rsl.oe_order_header_id\n                AND oel.ship_from_org_id = rsl.to_organization_id\n        ), 0) + decode(oel.flow_status_code, 'AWAITING_RETURN', 1, 0) > 0 THEN\n            'Y'\n        ELSE\n            'N'\n    END delivery_detail_flag,\n    oeh.sales_channel_code,\n    CASE\n        WHEN oel.actual_shipment_date IS NULL THEN\n            'Not Applicable'\n        WHEN trunc(oel.actual_shipment_date) - trunc(oel.promise_date) < 1                   THEN\n            'On Time'\n        WHEN trunc(oel.actual_shipment_date) - trunc(oel.promise_date) <= 7                  THEN\n            '1 Week Late'\n        WHEN trunc(oel.actual_shipment_date) - trunc(oel.promise_date) <= 14                 THEN\n            '2 Weeks Late'\n        WHEN trunc(oel.actual_shipment_date) - trunc(oel.promise_date) <= 21                 THEN\n            '3 Weeks Late'\n        WHEN trunc(oel.actual_shipment_date) - trunc(oel.promise_date) <= 28                 THEN\n            '4 Weeks Late'\n        WHEN trunc(oel.actual_shipment_date) - trunc(oel.promise_date) > 28                  THEN\n            '4+ Weeks Late'\n    END otd_to_promise_status,\n    CASE\n        WHEN oel.actual_shipment_date IS NULL THEN\n            'Not Applicable'\n        WHEN trunc(oel.actual_shipment_date) - trunc(oel.request_date) < 1                   THEN\n            'On Time'\n        WHEN trunc(oel.actual_shipment_date) - trunc(oel.request_date) <= 7                  THEN\n            '1 Week Late'\n        WHEN trunc(oel.actual_shipment_date) - trunc(oel.request_date) <= 14                 THEN\n            '2 Weeks Late'\n        WHEN trunc(oel.actual_shipment_date) - trunc(oel.request_date) <= 21                 THEN\n            '3 Weeks Late'\n        WHEN trunc(oel.actual_shipment_date) - trunc(oel.request_date) <= 28                 THEN\n            '4 Weeks Late'\n        WHEN trunc(oel.actual_shipment_date) - trunc(oel.request_date) > 28                  THEN\n            '4+ Weeks Late'\n    END otd_to_request_status\nFROM\n    apps.oe_order_sources                 oos,\n    ar.hz_parties                        hp,\n    ar.hz_cust_accounts                  hca,\n    apps.xxcoh_ra_addresses_all          xxcraa,\n    ar.hz_cust_site_uses_all             csua,\n    ar.hz_parties                        hp2,\n    ar.hz_cust_accounts                  hca2,\n    jtf.jtf_rs_salesreps                 srep,\n    ont.oe_transaction_types_all         otta1,\n    ont.oe_transaction_types_all         otta2,\n    ont.oe_transaction_types_tl          ott1,\n    ont.oe_transaction_types_tl          ott2,\n    inv.mtl_parameters                   mp,\n    ont.oe_order_headers_all             oeh,\n    apps.oe_order_lines_all              oel,\n    inv.mtl_system_items_b               msi,\n    inv.mtl_parameters                   mp2,\n    apps.org_organization_definitions    ood,\n    applsys.fnd_user                     fu1,\n    applsys.fnd_user                     fu2\nWHERE\n        1 = 1\n    AND hca.party_id = hp.party_id (+)\n    AND csua.cust_acct_site_id = xxcraa.address_id\n    AND oel.end_customer_id = hca.cust_account_id (+)\n    AND oel.ship_to_org_id = csua.site_use_id\n    AND hca2.party_id = hp2.party_id\n    AND oeh.sold_to_org_id = hca2.cust_account_id\n    AND oel.salesrep_id = srep.salesrep_id (+)\n    AND oel.org_id = srep.org_id (+)\n    AND oel.header_id = oeh.header_id\n    AND oeh.org_id = oel.org_id\n    AND mp.organization_id = oel.ship_from_org_id\n    AND oeh.order_source_id = oos.order_source_id\n    AND oel.inventory_item_id = msi.inventory_item_id\n    AND msi.organization_id = mp2.organization_id\n    AND otta1.transaction_type_id = ott1.transaction_type_id\n    AND ott2.transaction_type_id = otta2.transaction_type_id\n    AND oeh.order_type_id = otta1.transaction_type_id\n    AND oel.line_type_id = otta2.transaction_type_id\n    AND ood.organization_id = mp2.organization_id\n    AND oel.created_by = fu1.user_id\n    AND oel.last_updated_by = fu2.user_id\n    AND mp.organization_code IN (\n        '\"&ORG&\"',\n         '\"&CUSTORG&\"'\n    ) --ship from org\n    AND mp2.organization_code ='\"&ORG&\"' --item org\n    AND ott1.language = 'US'\n    AND ott2.language = 'US'\n    AND ott1.language = 'US'\n    AND ott2.language = 'US'\n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"EXTRACT_DATE\", \"Extract Date\"}, {\"ORGANIZATION_CODE\", \"Ship From Org\"}, {\"ORDER_NUMBER\", \"Order Number\"}, {\"END_CUSTOMER_NAME\", \"End Customer Name\"}, {\"LINE_NUMBER\", \"Line Number\"}, {\"SHIPMENT_NUMBER\", \"Shipment Number\"}, {\"OPEN_FLAG\", \"Open Flag\"}, {\"CANCELLED_FLAG\", \"Cancelled Flag\"}, {\"SHIP_SET_ID\", \"Ship Set ID\"}, {\"ORDER_TYPE\", \"Order Type\"}, {\"LINE_TYPE\", \"Line Type\"}, {\"BOOKING_OU\", \"Operating Unit\"}, {\"REVENUE_FLAG\", \"Revenue Flag\"}, {\"ITEM_NUMBER\", \"Item Number\"}, {\"TRANSACTIONAL_CURR_CODE\", \"Currency Code\"}, {\"UNIT_SELLING_PRICE\", \"Unit Price\"}, {\"ORDERED_QUANTITY\", \"Ordered Quantity\"}, {\"CUSTOMER_TYPE\", \"Customer Type\"}, {\"CUSTOMER\", \"Customer\"}, {\"FLOW_STATUS_CODE\", \"Status\"}, {\"SHIPMENT_PRIORITY_CODE\", \"Shipment Priority\"}, {\"SHIPPABLE_FLAG\", \"Shippable Flag\"}, {\"SHIPPING_METHOD_CODE\", \"Shipping Method\"}, {\"SUBINVENTORY\", \"Ship From Subinventory\"}, {\"MARKET\", \"Market\"}, {\"SO_CATEGORY_CODE\", \"Category Code\"}, {\"REGIONAL_LOCATION\", \"Regional Location\"}, {\"REPORTING_ENTITY\", \"Reporting Entity\"}, {\"SALES_OR_SERVICE\", \"Sales or Service\"}, {\"LINE_CATEGORY_CODE\", \"Line Category\"}, {\"FOB_POINT_CODE\", \"FOB Point\"}, {\"CI_VALUE\", \"Custom Invoice Value\"}, {\"FREIGHT_TERMS_CODE\", \"Freight Terms\"}, {\"COUNTRY\", \"Ship To Country\"}, {\"CITY\", \"Ship To City\"}, {\"ACTUAL_FULFILLMENT_DATE\", \"Actual Fulfillment Date\"}, {\"ACTUAL_SHIPMENT_DATE\", \"Actual Shipment Date\"}, {\"PROMISE_DATE\", \"Promised Date\"}, {\"REQUEST_DATE\", \"Request Date\"}, {\"SCHEDULE_SHIP_DATE\", \"Schedule Ship Date\"}, {\"ORIG_SYS_DOCUMENT_REF\", \"Original Document Reference\"}, {\"PLANNER_CODE\", \"Planner\"}, {\"CREATED_BY\", \"Line Created By\"}, {\"LAST_UPDATED_BY\", \"Line Last Updated By\"}, {\"CREATION_DATE\", \"Line Creation Date\"}, {\"LAST_UPDATE_DATE\", \"Line Last Update Date\"}, {\"SALES_REP\", \"Sales Rep\"}, {\"BOOKED_DATE\", \"Book Date\"}, {\"SOURCE_NAME\", \"Source Name\"}, {\"UNIT_COST\", \"Unit Cost\"}, {\"UNIT_COST_USD\", \"Unit Cost USD\"}, {\"BOOKED_FLAG\", \"Booked Flag\"}, {\"SHIPPED_QUANTITY\", \"Shipped Quantity\"}, {\"REVENUE_AMOUNT_USD\", \"Revenue Amount USD\"}, {\"BOOK_USD_RATE\", \"Book USD Rate\"}, {\"DELIVERY_DETAIL_FLAG\", \"Delivery Detail Flag\"}, {\"SALES_CHANNEL_CODE\", \"Sales Channel\"}, {\"OTD_TO_REQUEST_STATUS\", \"OTD to Request Status\"}, {\"OTD_TO_PROMISE_STATUS\", \"OTD to Promise Status\"}, {\"LOCAL_EXTRACT_DATE\", \"Local Extract Date\"}, {\"LOCAL_ACTUAL_SHIP\", \"Local Actual Shipment Date\"}, {\"CUSTOMER_PHONETIC\", \"Customer Phonetic\"}, {\"END_CUSTOMER_PHONETIC\", \"End Customer Phonetic\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Sales_Line_Attachment = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, \n  Query=\"\n  SELECT\n   /*+index (AD XXCOH_FND_ATTACHED_DOC_01 ) */\n    sysdate                                                                                               extract_date,\n    from_tz(CAST(sysdate AS TIMESTAMP), 'PST') AT TIME ZONE '\"&LocalTZ&\"'                         local_extract_date,\n    ad.seq_num,\n    dct.user_name                                                                                         document_category,\n    dtl.description,\n    dtl.title,\n    decode(txt.short_text, NULL, fl.file_content_type, '')                                                filetype,\n    txt.short_text                                                                                        doc_text,\n    oeh.order_number,\n    oel.line_number\n    || decode(oel.shipment_number, NULL, NULL, '.' || oel.shipment_number)                order_line,\n    'Line'                                                                                                document_level,\n    oel.line_id,\n    oeh.header_id,\n    mp.organization_code,\n    ad.last_update_date,\n    usr.user_name                                                                                         last_updated_by\nFROM\n    apps.fnd_user                      usr,\n    apps.fnd_lobs                      fl,\n    apps.fnd_documents_short_text      txt,\n    apps.fnd_document_categories_tl    dct,\n    apps.fnd_documents_tl              dtl,\n    apps.fnd_documents                 dt,\n    apps.fnd_attached_documents        ad,\n    apps.oe_order_lines_all            oel,\n    apps.mtl_parameters                mp,\n    apps.oe_order_headers_all          oeh\nWHERE\n        1 = 1\n    AND usr.user_id = ad.last_updated_by\n    AND fl.file_id (+) = dt.media_id\n    AND txt.media_id (+) = dt.media_id\n    AND dct.category_id = dt.category_id\n    AND dct.language = 'US'\n    AND dtl.document_id = dt.document_id\n    AND dtl.language = 'US'\n    AND dt.document_id = ad.document_id\n    AND dt.document_id = ad.document_id\n    AND ad.entity_name = 'OE_ORDER_LINES'\n    AND ad.pk1_value = oel.line_id\n    AND mp.organization_code IN (\n        '\"&ORG&\"',\n        '\"&CUSTORG&\"'\n    )\n    AND oeh.header_id = oel.header_id\n    AND oeh.org_id = oel.org_id\n    AND mp.organization_id = oel.ship_from_org_id\n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"ORGANIZATION_CODE\", \"Ship From Org\"}, {\"EXTRACT_DATE\", \"Extract Date\"}, {\"SEQ_NUM\", \"Sequence\"}, {\"DOCUMENT_CATEGORY\", \"Document Category\"}, {\"DESCRIPTION\", \"Description\"}, {\"TITLE\", \"Title\"}, {\"FILETYPE\", \"File Type\"}, {\"DOC_TEXT\", \"Document Text\"}, {\"ORDER_NUMBER\", \"Order Number\"}, {\"ORDER_LINE\", \"Order Line\"}, {\"DOCUMENT_LEVEL\", \"Document Level\"}, {\"LAST_UPDATE_DATE\", \"Last Update Date\"}, {\"LAST_UPDATED_BY\", \"Last Updated By\"}, {\"LOCAL_EXTRACT_DATE\", \"Local Extract Date\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Sales_Shipment = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, \n  Query=\"SELECT\n    sysdate                                                                               extract_date,\n    from_tz(CAST(sysdate AS TIMESTAMP), 'PST') AT TIME ZONE '\"&LocalTZ&\"'         local_extract_date,\n    wdd.source_line_id,\n    wdd.delivery_detail_id,\n    mp2.organization_code,\n    oel.ordered_item                                                                      item_number,\n    flv.meaning                                                                           released_status,\n    wnd.name                                                                              delivery_number,\n    wnd.waybill                                                                           delivery_waybill,\n    (\n        SELECT\n            mtrh.request_number\n        FROM\n            inv.mtl_txn_request_headers    mtrh,\n            inv.mtl_txn_request_lines      mtrl\n        WHERE\n                mtrl.line_id = wdd.move_order_line_id\n            AND mtrh.header_id = mtrl.header_id\n    ) move_order_number,\n    (\n        SELECT\n            mtrl.line_number\n        FROM\n            inv.mtl_txn_request_lines mtrl\n        WHERE\n            mtrl.line_id = wdd.move_order_line_id\n    ) move_order_line_number,\n    wdd.requested_quantity,\n    wdd.requested_quantity_uom,\n    wdd.cancelled_quantity,\n    wdd.picked_quantity,\n    CASE\n        WHEN wdd.shipping_instructions IS NULL THEN\n            nvl(oel.shipping_instructions, oeh.shipping_instructions)\n        ELSE\n            nvl(oel.shipping_instructions, oeh.shipping_instructions)\n            || '/'\n            || wdd.shipping_instructions\n    END shipping_instructionsv,\n    CASE\n        WHEN wdd.packing_instructions IS NULL THEN\n            nvl(oel.packing_instructions, oeh.packing_instructions)\n        ELSE\n            nvl(oel.packing_instructions, oeh.packing_instructions)\n            || '/'\n            || wdd.packing_instructions\n    END packing_instructionsv,\n    wnd.gross_weight,\n    wnd.net_weight,\n    wnd.weight_uom_code,\n    wnd.volume,\n    wnd.volume_uom_code,\n    wnd.attribute1                                                                        delivery_pack,\n    wnd.attribute2                                                                        delivery_pack_uom,\n    wnd.attribute3                                                                        delivery_pack_dimensions,\n    wnd.confirm_date,\n    wnd.ship_method_code,\n    wnd.delivery_type,\n    wnd.service_level,\n    wnd.mode_of_transport,\n    wnd.delivery_id\nFROM\n    wsh.wsh_new_deliveries          wnd,\n    wsh.wsh_delivery_assignments    wda,\n    wsh.wsh_delivery_details        wdd,\n    apps.oe_order_lines_all         oel,\n    apps.oe_order_headers_all       oeh,\n    inv.mtl_parameters              mp2,\n    apps.fnd_lookup_values_vl       flv\nWHERE\n        1 = 1\n    AND oeh.header_id = oel.header_id\n    AND wdd.delivery_detail_id = wda.delivery_detail_id (+)\n    AND wda.delivery_id = wnd.delivery_id (+)\n    AND mp2.organization_id = wdd.organization_id\n    AND mp2.organization_code IN (\n        '\"&ORG&\"',\n        '\"&CUSTORG&\"'\n    )\n    AND mp2.organization_id = oel.ship_from_org_id\n    AND oel.line_id = wdd.source_line_id\n    AND wdd.organization_id = oel.ship_from_org_id\n    AND wdd.released_status = flv.lookup_code\n    AND flv.lookup_type = 'PICK_STATUS'\n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"EXTRACT_DATE\", \"Extract Date\"}, {\"ORGANIZATION_CODE\", \"Organization Code\"}, {\"ITEM_NUMBER\", \"Item Number\"}, {\"RELEASED_STATUS\", \"Released Status\"}, {\"DELIVERY_NUMBER\", \"Delivery Number\"}, {\"DELIVERY_WAYBILL\", \"Delivery Waybill\"}, {\"MOVE_ORDER_NUMBER\", \"Pick Move Order Number\"}, {\"MOVE_ORDER_LINE_NUMBER\", \"Pick Move Order Line Number\"}, {\"REQUESTED_QUANTITY\", \"Requested Quantity\"}, {\"REQUESTED_QUANTITY_UOM\", \"Requested Quantity UOM\"}, {\"CANCELLED_QUANTITY\", \"Cancelled Quantity\"}, {\"PICKED_QUANTITY\", \"Picked Quantity\"}, {\"SHIPPING_INSTRUCTIONSV\", \"Shipping Instructions\"}, {\"PACKING_INSTRUCTIONSV\", \"Packing Instructions\"}, {\"GROSS_WEIGHT\", \"Gross Weight\"}, {\"NET_WEIGHT\", \"Net Weight\"}, {\"WEIGHT_UOM_CODE\", \"Weight Unit of Measure\"}, {\"VOLUME\", \"Volume\"}, {\"VOLUME_UOM_CODE\", \"Volume Unit of Measure\"}, {\"DELIVERY_PACK\", \"Delivery Packing Quantity\"}, {\"DELIVERY_PACK_UOM\", \"Delivery Packing Unit Of Measure\"}, {\"DELIVERY_PACK_DIMENSIONS\", \"Delivery Pack Dimensions\"}, {\"CONFIRM_DATE\", \"Delivery Confirm Date\"}, {\"SHIP_METHOD_CODE\", \"Ship Method Code\"}, {\"DELIVERY_TYPE\", \"Delivery Type\"}, {\"SERVICE_LEVEL\", \"Service Level\"}, {\"MODE_OF_TRANSPORT\", \"Mode Of Transport\"}, {\"LOCAL_EXTRACT_DATE\", \"Local Extract Date\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Sales_Backlog_History = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, \n  Query=\"\n  SELECT\n    sysdate extract_date,\n    from_tz(CAST(sysdate AS TIMESTAMP), 'PST') AT TIME ZONE '\"&LocalTZ&\"'         local_extract_date,\n    mp.organization_code,\n    xxbl.asof_date,\n    xxbl.order_number,\n    xxbl.order_line,\n    xxbl.order_type,\n    xxbl.so_line_type,\n    xxbl.line_status,\n    xxbl.backlog_quantity,\n    xxbl.tr_item_unit_cost,\n    xxbl.ship_to_country,\n    xxbl.item_number,\n    xxbl.item_description,\n    xxbl.first_schedule_date,\n    xxbl.schedule_category_period,\n    xxbl.schedule_category,\n    xxbl.request_ship_date,\n    xxbl.promise_ship_date,\n    xxbl.schedule_ship_date,\n    oel.inventory_item_id,\n    round(xxbl.unit_selling_price_usd,2) unit_selling_price_usd,\n    xxbl.header_id,\n    xxbl.line_id\nFROM\n    xxcoh.xxcoh_backlog_tab    xxbl,\n    ont.oe_order_lines_all     oel,\n    apps.mtl_parameters        mp\nWHERE\n        xxbl.line_id = oel.line_id\n    AND xxbl.header_id = oel.header_id\n    AND oel.ship_from_org_id = mp.organization_id\n    AND mp.organization_code = '\"&ORG&\"'\n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"ORDER_NUMBER\", \"Order Number\"}, {\"ORDER_LINE\", \"Order Line\"}, {\"ORDER_TYPE\", \"Order Type\"}, {\"SO_LINE_TYPE\", \"Line Type\"}, {\"LINE_STATUS\", \"Line Status\"}, {\"BACKLOG_QUANTITY\", \"Backlog Quantity\"}, {\"TR_ITEM_UNIT_COST\", \"Item Cost\"}, {\"SHIP_TO_COUNTRY\", \"Ship To Country\"}, {\"ITEM_NUMBER\", \"Item Number\"}, {\"ITEM_DESCRIPTION\", \"Item Description\"}, {\"FIRST_SCHEDULE_DATE\", \"First Schedule Date\"}, {\"SCHEDULE_CATEGORY_PERIOD\", \"Schedule Category Period\"}, {\"SCHEDULE_CATEGORY\", \"Schedule Category\"}, {\"REQUEST_SHIP_DATE\", \"Request Ship Date\"}, {\"PROMISE_SHIP_DATE\", \"Promise Ship Date\"}, {\"SCHEDULE_SHIP_DATE\", \"Schedule Ship Date\"}, {\"UNIT_SELLING_PRICE_USD\", \"Unit Selling Price USD\"}, {\"ASOF_DATE\", \"As Of Date\"}, {\"ORGANIZATION_CODE\", \"Organization Code\"}, {\"EXTRACT_DATE\", \"Extract Date\"}, {\"LOCAL_EXTRACT_DATE\", \"Local Extract Date\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared ORG = let\r\n  ORG = \"GEP\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type text]\r\nin\r\n  ORG;\r\nshared CUSTORG = let\r\n  CUSTORG = \"COG\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type text]\r\nin\r\n  CUSTORG;\r\nshared LocalTZ = let\r\n  LocalZoneRegion = \"Europe/Berlin\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type text]\r\nin\r\n  LocalZoneRegion;\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"Sales_Hold","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Sales_Hold.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Local Extract Date","dataType":"dateTime"},{"name":"HOLD_SOURCE_ID","dataType":"double"},{"name":"Hold Level","dataType":"string"},{"name":"HEADER_ID","dataType":"double"},{"name":"LINE_ID","dataType":"double"},{"name":"HOLD_ID","dataType":"double"},{"name":"Hold Reason","dataType":"string"},{"name":"Hold Release Flag","dataType":"string"},{"name":"Creation Date","dataType":"dateTime"},{"name":"Created By","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-13T05:00:52.2518272+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/d66f604e-2736-464d-9133-35ca2d5ffd79/Sales_Hold.csv?snapshot=2022-06-13T05%3A00%3A52.1822305Z"}]},{"$type":"LocalEntity","name":"Sales_Order","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Sales_Order.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Local Extract Date","dataType":"dateTime"},{"name":"Local Actual Shipment Date","dataType":"dateTime"},{"name":"Ship From Org","dataType":"string"},{"name":"Operating Unit","dataType":"string"},{"name":"Order Number","dataType":"double"},{"name":"HEADER_ID","dataType":"double"},{"name":"End Customer Phonetic","dataType":"string"},{"name":"Customer Phonetic","dataType":"string"},{"name":"End Customer Name","dataType":"string"},{"name":"Line Number","dataType":"double"},{"name":"Shipment Number","dataType":"double"},{"name":"Open Flag","dataType":"string"},{"name":"Cancelled Flag","dataType":"string"},{"name":"Ship Set ID","dataType":"double"},{"name":"Order Type","dataType":"string"},{"name":"ORDER_TYPE_ID","dataType":"double"},{"name":"Line Type","dataType":"string"},{"name":"LINE_TYPE_ID","dataType":"double"},{"name":"Revenue Flag","dataType":"string"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"Item Number","dataType":"string"},{"name":"Currency Code","dataType":"string"},{"name":"Unit Price","dataType":"double"},{"name":"Ordered Quantity","dataType":"double"},{"name":"Booked Flag","dataType":"string"},{"name":"Shipped Quantity","dataType":"double"},{"name":"Customer Type","dataType":"string"},{"name":"Customer","dataType":"string"},{"name":"Status","dataType":"string"},{"name":"Shipment Priority","dataType":"string"},{"name":"Shippable Flag","dataType":"string"},{"name":"Shipping Method","dataType":"string"},{"name":"Ship From Subinventory","dataType":"string"},{"name":"Market","dataType":"string"},{"name":"Category Code","dataType":"string"},{"name":"Regional Location","dataType":"string"},{"name":"Reporting Entity","dataType":"string"},{"name":"Sales or Service","dataType":"string"},{"name":"Line Category","dataType":"string"},{"name":"FOB Point","dataType":"string"},{"name":"Custom Invoice Value","dataType":"string"},{"name":"Freight Terms","dataType":"string"},{"name":"Ship To Country","dataType":"string"},{"name":"Ship To City","dataType":"string"},{"name":"Actual Fulfillment Date","dataType":"dateTime"},{"name":"Actual Shipment Date","dataType":"dateTime"},{"name":"Schedule Ship Date","dataType":"dateTime"},{"name":"Request Date","dataType":"dateTime"},{"name":"Promised Date","dataType":"dateTime"},{"name":"Original Document Reference","dataType":"string"},{"name":"Source Name","dataType":"string"},{"name":"Planner","dataType":"string"},{"name":"Line Created By","dataType":"string"},{"name":"Line Last Updated By","dataType":"string"},{"name":"Line Creation Date","dataType":"dateTime"},{"name":"Line Last Update Date","dataType":"dateTime"},{"name":"Sales Rep","dataType":"string"},{"name":"LINE_ID","dataType":"double"},{"name":"Book Date","dataType":"dateTime"},{"name":"END_CUSTOMER_ID","dataType":"double"},{"name":"Unit Cost","dataType":"double"},{"name":"Unit Cost USD","dataType":"double"},{"name":"Revenue Amount USD","dataType":"double"},{"name":"Book USD Rate","dataType":"double"},{"name":"Delivery Detail Flag","dataType":"string"},{"name":"Sales Channel","dataType":"string"},{"name":"OTD to Promise Status","dataType":"string"},{"name":"OTD to Request Status","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T05:06:47.5137282+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/d66f604e-2736-464d-9133-35ca2d5ffd79/Sales_Order.csv?snapshot=2022-06-13T05%3A06%3A47.4812088Z"}]},{"$type":"LocalEntity","name":"Sales_Line_Attachment","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Sales_Line_Attachment.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Local Extract Date","dataType":"dateTime"},{"name":"Sequence","dataType":"double"},{"name":"Document Category","dataType":"string"},{"name":"Description","dataType":"string"},{"name":"Title","dataType":"string"},{"name":"File Type","dataType":"string"},{"name":"Document Text","dataType":"string"},{"name":"Order Number","dataType":"double"},{"name":"Order Line","dataType":"string"},{"name":"Document Level","dataType":"string"},{"name":"LINE_ID","dataType":"double"},{"name":"HEADER_ID","dataType":"double"},{"name":"Ship From Org","dataType":"string"},{"name":"Last Update Date","dataType":"dateTime"},{"name":"Last Updated By","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-13T05:05:45.3432328+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/d66f604e-2736-464d-9133-35ca2d5ffd79/Sales_Line_Attachment.csv?snapshot=2022-06-13T05%3A05%3A45.3022642Z"}]},{"$type":"LocalEntity","name":"Sales_Shipment","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Sales_Shipment.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Local Extract Date","dataType":"dateTime"},{"name":"SOURCE_LINE_ID","dataType":"double"},{"name":"DELIVERY_DETAIL_ID","dataType":"double"},{"name":"Organization Code","dataType":"string"},{"name":"Item Number","dataType":"string"},{"name":"Released Status","dataType":"string"},{"name":"Delivery Number","dataType":"string"},{"name":"Delivery Waybill","dataType":"string"},{"name":"Pick Move Order Number","dataType":"string"},{"name":"Pick Move Order Line Number","dataType":"double"},{"name":"Requested Quantity","dataType":"double"},{"name":"Requested Quantity UOM","dataType":"string"},{"name":"Cancelled Quantity","dataType":"double"},{"name":"Picked Quantity","dataType":"double"},{"name":"Shipping Instructions","dataType":"string"},{"name":"Packing Instructions","dataType":"string"},{"name":"Gross Weight","dataType":"double"},{"name":"Net Weight","dataType":"double"},{"name":"Weight Unit of Measure","dataType":"string"},{"name":"Volume","dataType":"double"},{"name":"Volume Unit of Measure","dataType":"string"},{"name":"Delivery Packing Quantity","dataType":"string"},{"name":"Delivery Packing Unit Of Measure","dataType":"string"},{"name":"Delivery Pack Dimensions","dataType":"string"},{"name":"Delivery Confirm Date","dataType":"dateTime"},{"name":"Ship Method Code","dataType":"string"},{"name":"Delivery Type","dataType":"string"},{"name":"Service Level","dataType":"string"},{"name":"Mode Of Transport","dataType":"string"},{"name":"DELIVERY_ID","dataType":"double"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-13T05:06:43.9175721+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/d66f604e-2736-464d-9133-35ca2d5ffd79/Sales_Shipment.csv?snapshot=2022-06-13T05%3A06%3A43.8623077Z"}]},{"$type":"LocalEntity","name":"Sales_Backlog_History","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Sales_Backlog_History.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Local Extract Date","dataType":"dateTime"},{"name":"Organization Code","dataType":"string"},{"name":"As Of Date","dataType":"dateTime"},{"name":"Order Number","dataType":"double"},{"name":"Order Line","dataType":"string"},{"name":"Order Type","dataType":"string"},{"name":"Line Type","dataType":"string"},{"name":"Line Status","dataType":"string"},{"name":"Backlog Quantity","dataType":"double"},{"name":"Item Cost","dataType":"double"},{"name":"Ship To Country","dataType":"string"},{"name":"Item Number","dataType":"string"},{"name":"Item Description","dataType":"string"},{"name":"First Schedule Date","dataType":"string"},{"name":"Schedule Category Period","dataType":"string"},{"name":"Schedule Category","dataType":"string"},{"name":"Request Ship Date","dataType":"dateTime"},{"name":"Promise Ship Date","dataType":"dateTime"},{"name":"Schedule Ship Date","dataType":"dateTime"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"Unit Selling Price USD","dataType":"double"},{"name":"HEADER_ID","dataType":"double"},{"name":"LINE_ID","dataType":"double"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-13T05:03:54.2742753+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/d66f604e-2736-464d-9133-35ca2d5ffd79/Sales_Backlog_History.csv?snapshot=2022-06-13T05%3A03%3A54.0507794Z"}]}]}