{"name":"Flow_Oracle_Resources","description":"Oracle data from Snowflake.\nResources: Routings, Sequences, Resources.","version":"1.0","culture":"en-US","modifiedTime":"2022-04-07T06:49:43.469913+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":true,"queriesMetadata":{"BOM_OPERATIONAL_ROUTINGS (2)":{"queryId":"a6888167-b0c6-4e70-bafe-48d45eb732cf","queryName":"BOM_OPERATIONAL_ROUTINGS (2)","queryGroupId":"21a338d2-0010-4c9a-9422-af2ffe687dd5"},"BOM_OPERATION_SEQUENCES_V (2)":{"queryId":"cc73aa5d-147c-4517-af27-ca3831c3e3ed","queryName":"BOM_OPERATION_SEQUENCES_V (2)","queryGroupId":"21a338d2-0010-4c9a-9422-af2ffe687dd5"},"BOM_OPERATION_RESOURCES_V (2)":{"queryId":"f1e41447-07db-42c3-b170-fa76d10b594d","queryName":"BOM_OPERATION_RESOURCES_V (2)","queryGroupId":"21a338d2-0010-4c9a-9422-af2ffe687dd5"},"XXCOH_MI_ITEM_SUMMARY_VIEW (2)":{"queryId":"10defcd0-22b8-46f6-8b69-325d5f3dc005","queryName":"XXCOH_MI_ITEM_SUMMARY_VIEW (2)","queryGroupId":"21a338d2-0010-4c9a-9422-af2ffe687dd5"},"BOM_OPERATIONAL_ROUTINGS":{"queryId":"778863c4-248a-4cec-8e3a-66ee70861e3d","queryName":"BOM_OPERATIONAL_ROUTINGS","loadEnabled":true},"BOM_OPERATION_SEQUENCES_V":{"queryId":"851c3a05-2252-4839-ad15-ecea98bcf1e6","queryName":"BOM_OPERATION_SEQUENCES_V","loadEnabled":true},"BOM_OPERATION_RESOURCES_V":{"queryId":"4ea169d3-7088-4d15-90f2-e93cce98d531","queryName":"BOM_OPERATION_RESOURCES_V","loadEnabled":true},"XXCOH_MI_ITEM_SUMMARY_VIEW":{"queryId":"a9ef0dbd-5c13-46db-b0e0-6b1b993f1d31","queryName":"XXCOH_MI_ITEM_SUMMARY_VIEW","loadEnabled":true}},"document":"section Section1;\r\nshared #\"BOM_OPERATIONAL_ROUTINGS (2)\" = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 1\" = Navigation{[Name = \"BOM\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"BOM_OPERATIONAL_ROUTINGS\", Kind = \"Table\"]}[Data],\r\n  #\"Choose columns\" = Table.SelectColumns(#\"Navigation 2\", {\"ROUTING_SEQUENCE_ID\", \"ASSEMBLY_ITEM_ID\", \"ORGANIZATION_ID\", \"ALTERNATE_ROUTING_DESIGNATOR\", \"LAST_UPDATE_DATE\", \"COMMON_ROUTING_SEQUENCE_ID\", \"ROUTING_COMMENT\", \"COMPLETION_SUBINVENTORY\"}),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Choose columns\", {{\"ROUTING_SEQUENCE_ID\", Int64.Type}, {\"ASSEMBLY_ITEM_ID\", Int64.Type}, {\"ORGANIZATION_ID\", Int64.Type}, {\"COMMON_ROUTING_SEQUENCE_ID\", Int64.Type}}),\r\n  #\"Marked key columns\" = Table.AddKey(#\"Changed column type\", {\"ROUTING_SEQUENCE_ID\"}, false)\r\nin\r\n  #\"Marked key columns\";\r\nshared #\"BOM_OPERATION_SEQUENCES_V (2)\" = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 1\" = Navigation{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"BOM_OPERATION_SEQUENCES_V\", Kind = \"View\"]}[Data],\r\n  #\"Choose columns\" = Table.SelectColumns(#\"Navigation 2\", {\"OPERATION_SEQUENCE_ID\", \"ROUTING_SEQUENCE_ID\", \"OPERATION_SEQ_NUM\", \"LAST_UPDATE_DATE\", \"STANDARD_OPERATION_CODE\", \"DEPARTMENT_CODE\", \"OPERATION_DESCRIPTION\"}),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Choose columns\", {{\"OPERATION_SEQUENCE_ID\", Int64.Type}, {\"ROUTING_SEQUENCE_ID\", Int64.Type}, {\"OPERATION_SEQ_NUM\", Int64.Type}}),\r\n  #\"Marked key columns\" = Table.AddKey(#\"Changed column type\", {\"OPERATION_SEQUENCE_ID\"}, false)\r\nin\r\n  #\"Marked key columns\";\r\nshared #\"BOM_OPERATION_RESOURCES_V (2)\" = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 1\" = Navigation{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"BOM_OPERATION_RESOURCES_V\", Kind = \"View\"]}[Data],\r\n  #\"Choose columns\" = Table.SelectColumns(#\"Navigation 2\", {\"OPERATION_SEQUENCE_ID\", \"RESOURCE_SEQ_NUM\", \"RESOURCE_CODE\", \"UOM\", \"RESOURCE_ID\", \"STANDARD_RATE_FLAG\", \"ASSIGNED_UNITS\", \"USAGE_RATE_OR_AMOUNT\", \"USAGE_RATE_OR_AMOUNT_INVERSE\", \"LAST_UPDATE_DATE\", \"RESOURCE_OFFSET_PERCENT\", \"AUTOCHARGE_TYPE\"}),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Choose columns\", {{\"OPERATION_SEQUENCE_ID\", Int64.Type}, {\"RESOURCE_SEQ_NUM\", Int64.Type}, {\"RESOURCE_ID\", Int64.Type}, {\"USAGE_RATE_OR_AMOUNT_INVERSE\", Percentage.Type}, {\"STANDARD_RATE_FLAG\", Int64.Type}, {\"AUTOCHARGE_TYPE\", Int64.Type}})\r\nin\r\n  #\"Changed column type\";\r\nshared #\"XXCOH_MI_ITEM_SUMMARY_VIEW (2)\" = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 1\" = Navigation{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXCOH_MI_ITEM_SUMMARY_VIEW\", Kind = \"View\"]}[Data],\r\n  #\"Choose columns\" = Table.SelectColumns(#\"Navigation 2\", {\"ASOF_DATE\", \"ASOF_DATE_DISP\", \"ITEM_NUMBER\", \"ORG_CODE\", \"ITEM_DESCRIPTION\", \"FUCTIONAL_CURRENCY\", \"WEEKS_7DAY\", \"WIP_ISSUES\", \"SALES_ORDER_ISSUES\", \"MISCELLANEOUS_ISSUES\", \"INTER_ORG_ISSUES\", \"TOTAL_USAGE\", \"WEEK_7DAY_AVG_USAGE\", \"WEEK_7DAY_AVG_STD_WIP_USAGE\", \"WEEK_7DAY_AVG_SO_USAGE\", \"WEEK_7DAY_AVG_MSC_ISU_USAGE\", \"WEEK_7DAY_AVG_INT_ORG_USAGE\", \"SF_COMPILE_DESIGNATOR\", \"SAFETY_STOCK_QUANTITY\", \"GR_COMPILE_DESIGNATOR\", \"GROSS_REQUIREMENTS\", \"GROSS_WEEKS_OF_SUPPLY\", \"SAFETY_STOCK_WEEKS_OF_SUPPLY\", \"SAFETY_STOCK_VALUE\", \"NUM_OF_LEAD_TIMES_SAFETY_STOCK\", \"AVERAGE_WEEKLY_SO_WIP_IO\", \"ONHAND_QUANTITY\", \"JOB_QUANTITY\", \"INTRANSIT_QUANTITY\", \"RECEIVING_QUANTITY\", \"NETTABLE_QUANTITY\", \"NON_NETTABLE_QUANTITY\", \"ITEM_COST\", \"MATERIAL_COST\", \"MATERIAL_OVERHEAD_COST\", \"RESOURCE_COST\", \"OVERHEAD_COST\", \"OUTSIDE_PROCESSING_COST\", \"ITEM_COST_USD\", \"MATERIAL_COST_USD\", \"MATERIAL_OVERHEAD_COST_USD\", \"RESOURCE_COST_USD\", \"OVERHEAD_COST_USD\", \"OUTSIDE_PROCESSING_COST_USD\", \"EXTENDED_ONHAND_VALUE\", \"EXTENDED_GROSS_VALUE\", \"EXTENDED_ONHAND_VALUE_USD\", \"EXTENDED_GROSS_VALUE_USD\", \"TECHNICAL_BUSINESS_UNIT\", \"PRODUCT_FAMILY\", \"PRODUCT_LINE\", \"FORECAST_FIELD\", \"PRIMARY_ORG\", \"ORG_TECHNICAL_BUSINESS_UNIT\", \"ORG_PRODUCT_FAMILY\", \"ORG_PRODUCT_LINE\", \"ORG_FORECAST_FIELD\", \"ITEM_CUSTOMER\", \"BCP_CODE\", \"ROYALTY\", \"PLANNING_GREEN_SUPPLY_STATUS\", \"PLANNING_ACTION\", \"PLANNING_FAMILY_UNIQUE\", \"COST_SOURCE_TYPE\", \"ITEM_TYPE\", \"FULL_LEAD_TIME\", \"PLANNING_MAKE_BUY_CODE\", \"PLANNER_CODE\", \"END_ASSEMBLY_PEGGING\", \"AGILE_LIFE_PHASE\", \"BUYER\", \"SHRINKAGE_RATE\", \"MINIMUM_ORDER_QUANTITY\", \"FIXED_ORDER_QUANTITY\", \"FIXED_LOT_MULTIPLIER\", \"FIXED_DAYS_SUPPLY\", \"MRP_PLANNING_METHOD\", \"PLANNING_TIME_FENCE\", \"PLANNING_TIME_FENCE_DAYS\", \"PREPROCESSING_LEAD_TIME\", \"POSTPROCESSING_LEAD_TIME\", \"CUM_MANUFACTURING_LEAD_TIME\", \"CUMULATIVE_TOTAL_LEAD_TIME\", \"LEAD_TIME_LOT_SIZE\", \"WIP_SUPPLY_SUBINVENTORY\", \"PLANNING_EXCEPTION_SET\", \"FIXED_LEAD_TIME\", \"DEFAULT_RECV_SUBINVENTORY\", \"GREEN_TRANSITION_DATE\", \"SUPPLY_SOURCE\", \"DEMAND_SOURCE\", \"OPERATIONS_REPORTING\", \"SEC_REPORTING\", \"INVENTORY_ASSET_FLAG\", \"INVENTORY_ITEM_ID\", \"ORGANIZATION_ID\"}),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Choose columns\", {{\"ORGANIZATION_ID\", Int64.Type}, {\"INVENTORY_ITEM_ID\", Int64.Type}, {\"MATERIAL_OVERHEAD_COST_USD\", Currency.Type}, {\"MATERIAL_COST_USD\", Currency.Type}, {\"ITEM_COST_USD\", Currency.Type}, {\"OUTSIDE_PROCESSING_COST\", Currency.Type}, {\"OVERHEAD_COST\", Currency.Type}, {\"RESOURCE_COST\", Currency.Type}, {\"MATERIAL_OVERHEAD_COST\", Currency.Type}, {\"MATERIAL_COST\", Currency.Type}, {\"ITEM_COST\", Currency.Type}})\r\nin\r\n  #\"Changed column type\";\r\nshared BOM_OPERATIONAL_ROUTINGS = let\r\n  Source = Value.NativeQuery(Snowflake.Databases(\"mma12090.snowflakecomputing.com\",\"COMPUTE_REPORTING\",[Role=\"GLBMFGOPERATIONSROLE\"]){[Name=\"PROD_DB\"]}[Data], \"SELECT *#(lf)FROM PROD_DB.BOM.BOM_OPERATIONAL_ROUTINGS\", null, [EnableFolding=true]),\r\n  #\"Choose columns\" = Table.SelectColumns(Source, {\"ROUTING_SEQUENCE_ID\", \"ASSEMBLY_ITEM_ID\", \"ORGANIZATION_ID\", \"ALTERNATE_ROUTING_DESIGNATOR\", \"LAST_UPDATE_DATE\", \"COMMON_ROUTING_SEQUENCE_ID\", \"ROUTING_COMMENT\", \"COMPLETION_SUBINVENTORY\"}),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Choose columns\", {{\"ROUTING_SEQUENCE_ID\", Int64.Type}, {\"ASSEMBLY_ITEM_ID\", Int64.Type}, {\"ORGANIZATION_ID\", Int64.Type}, {\"COMMON_ROUTING_SEQUENCE_ID\", Int64.Type}}),\r\n  #\"Marked key columns\" = Table.AddKey(#\"Changed column type\", {\"ROUTING_SEQUENCE_ID\"}, false)\r\nin\r\n  #\"Marked key columns\";\r\nshared BOM_OPERATION_SEQUENCES_V = let\r\n  Source = Value.NativeQuery(Snowflake.Databases(\"mma12090.snowflakecomputing.com\",\"COMPUTE_REPORTING\",[Role=\"GLBMFGOPERATIONSROLE\"]){[Name=\"PROD_DB\"]}[Data], \"SELECT *#(lf)FROM PROD_DB.APPS.BOM_OPERATION_SEQUENCES_V\", null, [EnableFolding=true]),\r\n  #\"Choose columns\" = Table.SelectColumns(Source, {\"OPERATION_SEQUENCE_ID\", \"ROUTING_SEQUENCE_ID\", \"OPERATION_SEQ_NUM\", \"LAST_UPDATE_DATE\", \"STANDARD_OPERATION_CODE\", \"DEPARTMENT_CODE\", \"OPERATION_DESCRIPTION\"}),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Choose columns\", {{\"OPERATION_SEQUENCE_ID\", Int64.Type}, {\"ROUTING_SEQUENCE_ID\", Int64.Type}, {\"OPERATION_SEQ_NUM\", Int64.Type}}),\r\n  #\"Marked key columns\" = Table.AddKey(#\"Changed column type\", {\"OPERATION_SEQUENCE_ID\"}, false)\r\nin\r\n  #\"Marked key columns\";\r\nshared BOM_OPERATION_RESOURCES_V = let\r\n  Source = Value.NativeQuery(Snowflake.Databases(\"mma12090.snowflakecomputing.com\",\"COMPUTE_REPORTING\",[Role=\"GLBMFGOPERATIONSROLE\"]){[Name=\"PROD_DB\"]}[Data], \"SELECT *#(lf)FROM PROD_DB.APPS.BOM_OPERATION_RESOURCES_V\", null, [EnableFolding=true]),\r\n  #\"Choose columns\" = Table.SelectColumns(Source, {\"OPERATION_SEQUENCE_ID\", \"RESOURCE_SEQ_NUM\", \"RESOURCE_CODE\", \"UOM\", \"RESOURCE_ID\", \"STANDARD_RATE_FLAG\", \"ASSIGNED_UNITS\", \"USAGE_RATE_OR_AMOUNT\", \"USAGE_RATE_OR_AMOUNT_INVERSE\", \"LAST_UPDATE_DATE\", \"RESOURCE_OFFSET_PERCENT\", \"AUTOCHARGE_TYPE\"}),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Choose columns\", {{\"OPERATION_SEQUENCE_ID\", Int64.Type}, {\"RESOURCE_SEQ_NUM\", Int64.Type}, {\"RESOURCE_ID\", Int64.Type}, {\"USAGE_RATE_OR_AMOUNT_INVERSE\", Percentage.Type}, {\"STANDARD_RATE_FLAG\", Int64.Type}, {\"AUTOCHARGE_TYPE\", Int64.Type}})\r\nin\r\n  #\"Changed column type\";\r\nshared XXCOH_MI_ITEM_SUMMARY_VIEW = let\r\n  Source = Value.NativeQuery(Snowflake.Databases(\"mma12090.snowflakecomputing.com\",\"COMPUTE_REPORTING\",[Role=\"GLBMFGOPERATIONSROLE\"]){[Name=\"PROD_DB\"]}[Data], \"SELECT *#(lf)FROM PROD_DB.APPS.XXCOH_MI_ITEM_SUMMARY_VIEW\", null, [EnableFolding=true]),\r\n  #\"Choose columns\" = Table.SelectColumns(Source, {\"ASOF_DATE\", \"ASOF_DATE_DISP\", \"ITEM_NUMBER\", \"ORG_CODE\", \"ITEM_DESCRIPTION\", \"FUCTIONAL_CURRENCY\", \"WEEKS_7DAY\", \"WIP_ISSUES\", \"SALES_ORDER_ISSUES\", \"MISCELLANEOUS_ISSUES\", \"INTER_ORG_ISSUES\", \"TOTAL_USAGE\", \"WEEK_7DAY_AVG_USAGE\", \"WEEK_7DAY_AVG_STD_WIP_USAGE\", \"WEEK_7DAY_AVG_SO_USAGE\", \"WEEK_7DAY_AVG_MSC_ISU_USAGE\", \"WEEK_7DAY_AVG_INT_ORG_USAGE\", \"SF_COMPILE_DESIGNATOR\", \"SAFETY_STOCK_QUANTITY\", \"GR_COMPILE_DESIGNATOR\", \"GROSS_REQUIREMENTS\", \"GROSS_WEEKS_OF_SUPPLY\", \"SAFETY_STOCK_WEEKS_OF_SUPPLY\", \"SAFETY_STOCK_VALUE\", \"NUM_OF_LEAD_TIMES_SAFETY_STOCK\", \"AVERAGE_WEEKLY_SO_WIP_IO\", \"ONHAND_QUANTITY\", \"JOB_QUANTITY\", \"INTRANSIT_QUANTITY\", \"RECEIVING_QUANTITY\", \"NETTABLE_QUANTITY\", \"NON_NETTABLE_QUANTITY\", \"ITEM_COST\", \"MATERIAL_COST\", \"MATERIAL_OVERHEAD_COST\", \"RESOURCE_COST\", \"OVERHEAD_COST\", \"OUTSIDE_PROCESSING_COST\", \"ITEM_COST_USD\", \"MATERIAL_COST_USD\", \"MATERIAL_OVERHEAD_COST_USD\", \"RESOURCE_COST_USD\", \"OVERHEAD_COST_USD\", \"OUTSIDE_PROCESSING_COST_USD\", \"EXTENDED_ONHAND_VALUE\", \"EXTENDED_GROSS_VALUE\", \"EXTENDED_ONHAND_VALUE_USD\", \"EXTENDED_GROSS_VALUE_USD\", \"TECHNICAL_BUSINESS_UNIT\", \"PRODUCT_FAMILY\", \"PRODUCT_LINE\", \"FORECAST_FIELD\", \"PRIMARY_ORG\", \"ORG_TECHNICAL_BUSINESS_UNIT\", \"ORG_PRODUCT_FAMILY\", \"ORG_PRODUCT_LINE\", \"ORG_FORECAST_FIELD\", \"ITEM_CUSTOMER\", \"BCP_CODE\", \"ROYALTY\", \"PLANNING_GREEN_SUPPLY_STATUS\", \"PLANNING_ACTION\", \"PLANNING_FAMILY_UNIQUE\", \"COST_SOURCE_TYPE\", \"ITEM_TYPE\", \"FULL_LEAD_TIME\", \"PLANNING_MAKE_BUY_CODE\", \"PLANNER_CODE\", \"END_ASSEMBLY_PEGGING\", \"AGILE_LIFE_PHASE\", \"BUYER\", \"SHRINKAGE_RATE\", \"MINIMUM_ORDER_QUANTITY\", \"FIXED_ORDER_QUANTITY\", \"FIXED_LOT_MULTIPLIER\", \"FIXED_DAYS_SUPPLY\", \"MRP_PLANNING_METHOD\", \"PLANNING_TIME_FENCE\", \"PLANNING_TIME_FENCE_DAYS\", \"PREPROCESSING_LEAD_TIME\", \"POSTPROCESSING_LEAD_TIME\", \"CUM_MANUFACTURING_LEAD_TIME\", \"CUMULATIVE_TOTAL_LEAD_TIME\", \"LEAD_TIME_LOT_SIZE\", \"WIP_SUPPLY_SUBINVENTORY\", \"PLANNING_EXCEPTION_SET\", \"FIXED_LEAD_TIME\", \"DEFAULT_RECV_SUBINVENTORY\", \"GREEN_TRANSITION_DATE\", \"SUPPLY_SOURCE\", \"DEMAND_SOURCE\", \"OPERATIONS_REPORTING\", \"SEC_REPORTING\", \"INVENTORY_ASSET_FLAG\", \"INVENTORY_ITEM_ID\", \"ORGANIZATION_ID\", \"ROW_CREATION_DATE\"}),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Choose columns\", {{\"ORGANIZATION_ID\", Int64.Type}, {\"INVENTORY_ITEM_ID\", Int64.Type}, {\"MATERIAL_OVERHEAD_COST_USD\", Currency.Type}, {\"MATERIAL_COST_USD\", Currency.Type}, {\"ITEM_COST_USD\", Currency.Type}, {\"OUTSIDE_PROCESSING_COST\", Currency.Type}, {\"OVERHEAD_COST\", Currency.Type}, {\"RESOURCE_COST\", Currency.Type}, {\"MATERIAL_OVERHEAD_COST\", Currency.Type}, {\"MATERIAL_COST\", Currency.Type}, {\"ITEM_COST\", Currency.Type}})\r\nin\r\n  #\"Changed column type\";\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[{\"id\":\"21a338d2-0010-4c9a-9422-af2ffe687dd5\",\"name\":\"NonNativeSQL\",\"description\":\"Old talbes without native SQL query.\",\"parentId\":null,\"order\":0}]"}],"entities":[{"$type":"LocalEntity","name":"BOM_OPERATIONAL_ROUTINGS","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"BOM_OPERATIONAL_ROUTINGS.csv"},"attributes":[{"name":"ROUTING_SEQUENCE_ID","dataType":"int64"},{"name":"ASSEMBLY_ITEM_ID","dataType":"int64"},{"name":"ORGANIZATION_ID","dataType":"int64"},{"name":"ALTERNATE_ROUTING_DESIGNATOR","dataType":"string"},{"name":"LAST_UPDATE_DATE","dataType":"dateTime"},{"name":"COMMON_ROUTING_SEQUENCE_ID","dataType":"int64"},{"name":"ROUTING_COMMENT","dataType":"string"},{"name":"COMPLETION_SUBINVENTORY","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T05:09:27.7594031+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/b30c45f9-84b5-4a12-b619-aa503d08c6d1/BOM_OPERATIONAL_ROUTINGS.csv?snapshot=2022-06-13T05%3A09%3A27.7355100Z"}]},{"$type":"LocalEntity","name":"BOM_OPERATION_SEQUENCES_V","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"BOM_OPERATION_SEQUENCES_V.csv"},"attributes":[{"name":"OPERATION_SEQUENCE_ID","dataType":"int64"},{"name":"ROUTING_SEQUENCE_ID","dataType":"int64"},{"name":"OPERATION_SEQ_NUM","dataType":"int64"},{"name":"LAST_UPDATE_DATE","dataType":"dateTime"},{"name":"STANDARD_OPERATION_CODE","dataType":"string"},{"name":"DEPARTMENT_CODE","dataType":"string"},{"name":"OPERATION_DESCRIPTION","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T05:09:18.7132002+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/b30c45f9-84b5-4a12-b619-aa503d08c6d1/BOM_OPERATION_SEQUENCES_V.csv?snapshot=2022-06-13T05%3A09%3A18.7069760Z"}]},{"$type":"LocalEntity","name":"BOM_OPERATION_RESOURCES_V","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"BOM_OPERATION_RESOURCES_V.csv"},"attributes":[{"name":"OPERATION_SEQUENCE_ID","dataType":"int64"},{"name":"RESOURCE_SEQ_NUM","dataType":"int64"},{"name":"RESOURCE_CODE","dataType":"string"},{"name":"UOM","dataType":"string"},{"name":"RESOURCE_ID","dataType":"int64"},{"name":"STANDARD_RATE_FLAG","dataType":"int64"},{"name":"ASSIGNED_UNITS","dataType":"double"},{"name":"USAGE_RATE_OR_AMOUNT","dataType":"double"},{"name":"USAGE_RATE_OR_AMOUNT_INVERSE","dataType":"double"},{"name":"LAST_UPDATE_DATE","dataType":"dateTime"},{"name":"RESOURCE_OFFSET_PERCENT","dataType":"double"},{"name":"AUTOCHARGE_TYPE","dataType":"int64"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T05:09:43.1486949+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/b30c45f9-84b5-4a12-b619-aa503d08c6d1/BOM_OPERATION_RESOURCES_V.csv?snapshot=2022-06-13T05%3A09%3A43.1201970Z"}]},{"$type":"LocalEntity","name":"XXCOH_MI_ITEM_SUMMARY_VIEW","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"XXCOH_MI_ITEM_SUMMARY_VIEW.csv"},"attributes":[{"name":"ASOF_DATE","dataType":"date"},{"name":"ASOF_DATE_DISP","dataType":"dateTime"},{"name":"ITEM_NUMBER","dataType":"string"},{"name":"ORG_CODE","dataType":"string"},{"name":"ITEM_DESCRIPTION","dataType":"string"},{"name":"FUCTIONAL_CURRENCY","dataType":"string"},{"name":"WEEKS_7DAY","dataType":"double"},{"name":"WIP_ISSUES","dataType":"double"},{"name":"SALES_ORDER_ISSUES","dataType":"double"},{"name":"MISCELLANEOUS_ISSUES","dataType":"double"},{"name":"INTER_ORG_ISSUES","dataType":"double"},{"name":"TOTAL_USAGE","dataType":"double"},{"name":"WEEK_7DAY_AVG_USAGE","dataType":"double"},{"name":"WEEK_7DAY_AVG_STD_WIP_USAGE","dataType":"double"},{"name":"WEEK_7DAY_AVG_SO_USAGE","dataType":"double"},{"name":"WEEK_7DAY_AVG_MSC_ISU_USAGE","dataType":"double"},{"name":"WEEK_7DAY_AVG_INT_ORG_USAGE","dataType":"double"},{"name":"SF_COMPILE_DESIGNATOR","dataType":"string"},{"name":"SAFETY_STOCK_QUANTITY","dataType":"double"},{"name":"GR_COMPILE_DESIGNATOR","dataType":"string"},{"name":"GROSS_REQUIREMENTS","dataType":"double"},{"name":"GROSS_WEEKS_OF_SUPPLY","dataType":"double"},{"name":"SAFETY_STOCK_WEEKS_OF_SUPPLY","dataType":"double"},{"name":"SAFETY_STOCK_VALUE","dataType":"double"},{"name":"NUM_OF_LEAD_TIMES_SAFETY_STOCK","dataType":"double"},{"name":"AVERAGE_WEEKLY_SO_WIP_IO","dataType":"double"},{"name":"ONHAND_QUANTITY","dataType":"double"},{"name":"JOB_QUANTITY","dataType":"double"},{"name":"INTRANSIT_QUANTITY","dataType":"double"},{"name":"RECEIVING_QUANTITY","dataType":"double"},{"name":"NETTABLE_QUANTITY","dataType":"double"},{"name":"NON_NETTABLE_QUANTITY","dataType":"double"},{"name":"ITEM_COST","dataType":"decimal"},{"name":"MATERIAL_COST","dataType":"decimal"},{"name":"MATERIAL_OVERHEAD_COST","dataType":"decimal"},{"name":"RESOURCE_COST","dataType":"decimal"},{"name":"OVERHEAD_COST","dataType":"decimal"},{"name":"OUTSIDE_PROCESSING_COST","dataType":"decimal"},{"name":"ITEM_COST_USD","dataType":"decimal"},{"name":"MATERIAL_COST_USD","dataType":"decimal"},{"name":"MATERIAL_OVERHEAD_COST_USD","dataType":"decimal"},{"name":"RESOURCE_COST_USD","dataType":"double"},{"name":"OVERHEAD_COST_USD","dataType":"double"},{"name":"OUTSIDE_PROCESSING_COST_USD","dataType":"double"},{"name":"EXTENDED_ONHAND_VALUE","dataType":"double"},{"name":"EXTENDED_GROSS_VALUE","dataType":"double"},{"name":"EXTENDED_ONHAND_VALUE_USD","dataType":"double"},{"name":"EXTENDED_GROSS_VALUE_USD","dataType":"double"},{"name":"TECHNICAL_BUSINESS_UNIT","dataType":"string"},{"name":"PRODUCT_FAMILY","dataType":"string"},{"name":"PRODUCT_LINE","dataType":"string"},{"name":"FORECAST_FIELD","dataType":"string"},{"name":"PRIMARY_ORG","dataType":"string"},{"name":"ORG_TECHNICAL_BUSINESS_UNIT","dataType":"string"},{"name":"ORG_PRODUCT_FAMILY","dataType":"string"},{"name":"ORG_PRODUCT_LINE","dataType":"string"},{"name":"ORG_FORECAST_FIELD","dataType":"string"},{"name":"ITEM_CUSTOMER","dataType":"string"},{"name":"BCP_CODE","dataType":"string"},{"name":"ROYALTY","dataType":"string"},{"name":"PLANNING_GREEN_SUPPLY_STATUS","dataType":"string"},{"name":"PLANNING_ACTION","dataType":"string"},{"name":"PLANNING_FAMILY_UNIQUE","dataType":"string"},{"name":"COST_SOURCE_TYPE","dataType":"string"},{"name":"ITEM_TYPE","dataType":"string"},{"name":"FULL_LEAD_TIME","dataType":"double"},{"name":"PLANNING_MAKE_BUY_CODE","dataType":"string"},{"name":"PLANNER_CODE","dataType":"string"},{"name":"END_ASSEMBLY_PEGGING","dataType":"string"},{"name":"AGILE_LIFE_PHASE","dataType":"string"},{"name":"BUYER","dataType":"string"},{"name":"SHRINKAGE_RATE","dataType":"double"},{"name":"MINIMUM_ORDER_QUANTITY","dataType":"double"},{"name":"FIXED_ORDER_QUANTITY","dataType":"double"},{"name":"FIXED_LOT_MULTIPLIER","dataType":"double"},{"name":"FIXED_DAYS_SUPPLY","dataType":"double"},{"name":"MRP_PLANNING_METHOD","dataType":"string"},{"name":"PLANNING_TIME_FENCE","dataType":"string"},{"name":"PLANNING_TIME_FENCE_DAYS","dataType":"double"},{"name":"PREPROCESSING_LEAD_TIME","dataType":"double"},{"name":"POSTPROCESSING_LEAD_TIME","dataType":"double"},{"name":"CUM_MANUFACTURING_LEAD_TIME","dataType":"double"},{"name":"CUMULATIVE_TOTAL_LEAD_TIME","dataType":"double"},{"name":"LEAD_TIME_LOT_SIZE","dataType":"double"},{"name":"WIP_SUPPLY_SUBINVENTORY","dataType":"string"},{"name":"PLANNING_EXCEPTION_SET","dataType":"string"},{"name":"FIXED_LEAD_TIME","dataType":"double"},{"name":"DEFAULT_RECV_SUBINVENTORY","dataType":"string"},{"name":"GREEN_TRANSITION_DATE","dataType":"string"},{"name":"SUPPLY_SOURCE","dataType":"string"},{"name":"DEMAND_SOURCE","dataType":"string"},{"name":"OPERATIONS_REPORTING","dataType":"string"},{"name":"SEC_REPORTING","dataType":"string"},{"name":"INVENTORY_ASSET_FLAG","dataType":"string"},{"name":"INVENTORY_ITEM_ID","dataType":"int64"},{"name":"ORGANIZATION_ID","dataType":"int64"},{"name":"ROW_CREATION_DATE","dataType":"dateTime"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T05:42:50.5659373+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/b30c45f9-84b5-4a12-b619-aa503d08c6d1/XXCOH_MI_ITEM_SUMMARY_VIEW.csv?snapshot=2022-06-13T05%3A42%3A50.5370173Z"}]}]}