{"name":"COHREP_Operations1","description":"Global Operations dimension data with no security. Examples: Item type, buyers,  categories, etc","version":"1.0","culture":"en-US","modifiedTime":"2021-03-18T04:26:41.1339211+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":true,"queriesMetadata":{"Item_Type":{"queryId":"4b0befd3-b33c-40f0-b9f0-71ae82b5ef4b","queryName":"Item_Type","queryGroupId":"root","loadEnabled":true},"Sales_Commodity":{"queryId":"fd634039-5a34-49b8-93c9-03538bb84572","queryName":"Sales_Commodity","queryGroupId":"root","loadEnabled":true},"Sourcing_Commodity":{"queryId":"e47409c1-bc93-4952-aae0-b4fc2dfac0e6","queryName":"Sourcing_Commodity","queryGroupId":"root","loadEnabled":true},"Product_Category":{"queryId":"32509368-b376-4fb7-855b-c061e5c904ce","queryName":"Product_Category","queryGroupId":"root","loadEnabled":true},"GL_Account":{"queryId":"afb00876-c3fb-432b-a814-d31ff4092ead","queryName":"GL_Account","queryGroupId":"root","loadEnabled":true},"GL_Department":{"queryId":"6223da1b-cccc-4d39-8bc2-e95e587cc9b5","queryName":"GL_Department","queryGroupId":"root","loadEnabled":true},"GL_Project":{"queryId":"a0110de0-fea3-4985-8c1e-82d14c5c659c","queryName":"GL_Project","queryGroupId":"root","loadEnabled":true},"Fiscal_Calendar":{"queryId":"c44bd07a-f954-43ea-a639-a5719fc5d871","queryName":"Fiscal_Calendar","queryGroupId":"root","loadEnabled":true},"MPN":{"queryId":"6f86fe1f-46de-4bad-9fe0-2226d857e71a","queryName":"MPN","queryGroupId":"root","loadEnabled":true},"Order_Transaction_Type":{"queryId":"d46cc972-181e-4594-95f6-80d6663a50b5","queryName":"Order_Transaction_Type","queryGroupId":"root","loadEnabled":true},"TBU":{"queryId":"eaad3d1e-9227-45cc-93bd-a2c9d6dabfcd","queryName":"TBU","queryGroupId":"root","loadEnabled":true},"Product_Family":{"queryId":"ed439a8d-f959-4367-9d0e-7c292271bf31","queryName":"Product_Family","queryGroupId":"root","loadEnabled":true},"Product_Line":{"queryId":"e72da4b3-54ec-4b9a-ae7f-b05824e833b7","queryName":"Product_Line","queryGroupId":"root","loadEnabled":true},"Forecast_Field":{"queryId":"1e9e870a-0d5f-40d5-9da7-72e6c46e5e7c","queryName":"Forecast_Field","queryGroupId":"root","loadEnabled":true},"Demand_Origin":{"queryId":"2b07df4d-6ab5-4585-9830-16aa12a7f24a","queryName":"Demand_Origin","queryGroupId":"root","loadEnabled":true},"Supply_Chain_Status":{"queryId":"76688743-6447-493c-807b-8f17dd96adb9","queryName":"Supply_Chain_Status","queryGroupId":"root","loadEnabled":true},"Business_Segment":{"queryId":"b1b01bc5-fd24-4138-9358-afee785667ef","queryName":"Business_Segment","queryGroupId":"root","loadEnabled":true},"Organization":{"queryId":"32f54de3-8f09-4d79-9682-296a18632c89","queryName":"Organization","queryGroupId":"root","loadEnabled":true},"GL_Entity":{"queryId":"885fabe7-96d6-4f8a-90e7-36ed669eafff","queryName":"GL_Entity","loadEnabled":true},"Corporate_FX_Rate":{"queryId":"d3d2b89f-c73c-4bf5-98dd-dbc5fb5644a9","queryName":"Corporate_FX_Rate","loadEnabled":true},"Budget_Rate":{"queryId":"292a011f-3add-416e-bd33-6d455a312730","queryName":"Budget_Rate","queryGroupId":"root","loadEnabled":true},"APOP_Baseline":{"queryId":"1dc28462-5b75-4278-9b11-b7ac2d672b5e","queryName":"APOP_Baseline","queryGroupId":"root","loadEnabled":true}},"document":"section Section1;\r\nshared Item_Type = let\r\n  Source = Oracle.Database(\"COHREP\", [CommandTimeout = #duration(0, 0, 10, 0), Query = \"#(lf)SELECT#(lf)  sysdate EXTRACT_DATE,#(lf)  FLV.LOOKUP_CODE ITEM_TYPE_CODE,#(lf)  MEANING ITEM_TYPE_NAME,#(lf)  ENABLED_FLAG,#(lf)  FLV.start_date_Active,#(lf)  flv.end_date_Active#(lf)FROM#(lf)  APPS.FND_LOOKUP_VALUES_VL FLV#(lf)WHERE#(lf)  LOOKUP_TYPE = 'ITEM_TYPE'#(lf)  AND VIEW_APPLICATION_ID= 3#(lf)\", HierarchicalNavigation = true]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"ITEM_TYPE_CODE\", \"Item Type Code\"}, {\"ITEM_TYPE_NAME\", \"Item Type Name\"}, {\"EXTRACT_DATE\", \"Extract Date\"}, {\"ENABLED_FLAG\", \"Enabled Flag\"}, {\"START_DATE_ACTIVE\", \"Start Date Active\"}, {\"END_DATE_ACTIVE\", \"End Date Active\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Sales_Commodity = let\r\n  Source = Oracle.Database(\"COHREP\", [CommandTimeout = #duration(0, 0, 10, 0), Query = \"#(lf)SELECT#(lf)  sysdate EXTRACT_DATE,#(lf)  category_id,#(lf)  segment1 COMMODITY#(lf)FROM#(lf)  apps.mtl_categories_v MC#(lf)WHERE#(lf)  structure_name = 'Commodity'#(lf)\", HierarchicalNavigation = true]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"COMMODITY\", \"Sales Commodity\"}, {\"EXTRACT_DATE\", \"Extract Date\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Sourcing_Commodity = let\r\n  Source = Oracle.Database(\"COHREP\", [CommandTimeout = #duration(0, 0, 10, 0), Query = \"#(lf)SELECT#(lf)  sysdate EXTRACT_DATE,#(lf)  category_id,#(lf)  segment1,#(lf)  segment2 SUBCATEGORY,#(lf)  segment3 UNSPSC_CODE,#(lf)  MC.SEGMENT1 || '.' || MC.SEGMENT2 || '.' || MC.SEGMENT3 SOURCING_COMMODITY#(lf)FROM#(lf)  apps.mtl_categories_v MC#(lf)WHERE#(lf)  structure_name = 'Sourcing Commodity'#(lf)\", HierarchicalNavigation = true]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"SOURCING_COMMODITY\", \"Sourcing Commodity\"}, {\"SUBCATEGORY\", \"Sourcing Subcategory\"}, {\"UNSPSC_CODE\", \"UNSPSC Code\"}, {\"EXTRACT_DATE\", \"Extract Date\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Product_Category = let\r\n  Source = Oracle.Database(\"COHREP\", [CommandTimeout = #duration(0, 0, 10, 0), Query = \"  #(lf)SELECT#(lf)   SYSDATE EXTRACT_DATE,#(lf)   MC.CATEGORY_ID,#(lf)   MC.SEGMENT1 TBU,#(lf)   MC.SEGMENT2 PRODUCT_FAMILY,#(lf)   MC.SEGMENT3 PRODUCT_LINE,#(lf)   MC.SEGMENT4 FORECAST,#(lf)   MC.SEGMENT1 || '.' || MC.SEGMENT2 || '.' || MC.SEGMENT3 || '.' || MC.SEGMENT4 PRODUCT_CATEGORY #(lf)FROM#(lf)   APPS.MTL_CATEGORIES_V MC #(lf)WHERE 1=1#(lf)AND Structure_name = 'Product Family/Line'#(lf)\", HierarchicalNavigation = true]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"PRODUCT_FAMILY\", \"Product Family\"}, {\"FORECAST\", \"Forecast Field\"}, {\"PRODUCT_LINE\", \"Product Line\"}, {\"PRODUCT_CATEGORY\", \"Product Category\"}, {\"EXTRACT_DATE\", \"Extract Date\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared GL_Account = let\r\n  Source = Oracle.Database(\"COHREP\", [CommandTimeout = #duration(0, 0, 10, 0), Query = \"#(lf)select#(lf)   sysdate  EXTRACT_DATE,#(lf)   VL.FLEX_VALUE ACCOUNT,#(lf)   TL.DESCRIPTION ACCOUNT_DESCRIPTION,#(lf)   VL.ENABLED_FLAG#(lf)from#(lf)   APPS.FND_FLEX_VALUES_TL TL,#(lf)   APPS.FND_FLEX_VALUES VL,#(lf)   APPS.FND_FLEX_VALUE_SETS FST #(lf)where#(lf)   1 = 1 #(lf)   AND TL.FLEX_VALUE_ID( + ) = VL.FLEX_VALUE_ID #(lf)   AND TL.LANGUAGE ( + ) = 'US' #(lf)   AND VL.FLEX_VALUE_SET_ID = FST.FLEX_VALUE_SET_ID #(lf)   AND FST.FLEX_VALUE_SET_NAME = 'COHR_Acct'#(lf)\"]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"ACCOUNT\", \"GL Account Code\"}, {\"ACCOUNT_DESCRIPTION\", \"GL Account\"}, {\"EXTRACT_DATE\", \"Extract Date\"}, {\"ENABLED_FLAG\", \"Enabled Flag\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared GL_Department = let\r\n  Source = Oracle.Database(\"COHREP\", [CommandTimeout = #duration(0, 0, 10, 0), Query = \"#(lf)select#(lf)   sysdate  EXTRACT_DATE,#(lf)   VL.FLEX_VALUE DEPARTMENT_CODE,#(lf)   TL.DESCRIPTION,#(lf)   VL.ENABLED_FLAG#(lf)from#(lf)   APPS.FND_FLEX_VALUES_TL TL,#(lf)   APPS.FND_FLEX_VALUES VL,#(lf)   APPS.FND_FLEX_VALUE_SETS FST #(lf)where#(lf)   1 = 1 #(lf)   AND TL.FLEX_VALUE_ID( + ) = VL.FLEX_VALUE_ID #(lf)   AND TL.LANGUAGE ( + ) = 'US' #(lf)   AND VL.FLEX_VALUE_SET_ID = FST.FLEX_VALUE_SET_ID #(lf)   AND FST.FLEX_VALUE_SET_NAME = 'COHR_Dept'#(lf)\", HierarchicalNavigation = true]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"DEPARTMENT_CODE\", \"GL Department Code\"}, {\"DESCRIPTION\", \"GL Department\"}, {\"EXTRACT_DATE\", \"Extract Date\"}, {\"ENABLED_FLAG\", \"Enabled Flag\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared GL_Project = let\r\n  Source = Oracle.Database(\"COHREP\", [CommandTimeout = #duration(0, 0, 10, 0), Query = \"#(lf)select#(lf)#(tab)sysdate EXTRACT_DATE,#(lf)   VL.FLEX_VALUE PROJECT_CODE,#(lf)   TL.DESCRIPTION, VL.ENABLED_FLAG#(lf)from#(lf)   APPS.FND_FLEX_VALUES_TL TL,#(lf)   APPS.FND_FLEX_VALUES VL,#(lf)   APPS.FND_FLEX_VALUE_SETS FST #(lf)where#(lf)   1 = 1 #(lf)   AND TL.FLEX_VALUE_ID( + ) = VL.FLEX_VALUE_ID #(lf)   AND TL.LANGUAGE ( + ) = 'US' #(lf)   AND VL.FLEX_VALUE_SET_ID = FST.FLEX_VALUE_SET_ID #(lf)   AND FST.FLEX_VALUE_SET_NAME = 'COHR_Proj'#(lf)\", HierarchicalNavigation = true]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"PROJECT_CODE\", \"GL Project Code\"}, {\"DESCRIPTION\", \"GL Project\"}, {\"EXTRACT_DATE\", \"Extract Date\"}, {\"ENABLED_FLAG\", \"Enabled Flag\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Fiscal_Calendar = let\r\n  Source = Oracle.Database(\"COHREP\", [CommandTimeout = #duration(0, 0, 10, 0), Query = \" SELECT#(lf)    sysdate                                                                                       extract_date,#(lf)    al1.period_date                                                                               calendar_date,#(lf)    al1.year_start_date                                                                           fc_year_start_date,#(lf)    al1.period_year                                                                               fc_year,#(lf)    al1.quarter_start_date                                                                        fc_quarter_start_date,#(lf)    'Q' || al1.quarter_num                                                                        fc_quarter,#(lf)    CASE#(lf)        WHEN al1.quarter_num <= 2 THEN#(lf)            'H1'#(lf)        ELSE#(lf)            'H2'#(lf)    END fc_half,#(lf)    al1.period_num                                                                                fc_period_number,#(lf)    substr(al1.period_name, 1, 3)                                                                 fc_period_month,#(lf)    al1.period_name                                                                               fc_period_name,#(lf)    ( al1.period_year - 1 ) * 12 + al1.period_num                                                 fc_period_id,#(lf)    ( al1.period_year - 1 ) * 4 + al1.quarter_num                                                 fc_quarter_id,#(lf)    ceil((al1.period_date - TO_DATE('02-OCT-1999', 'DD-MON-RRRR')) / 7)                           fc_week_id,#(lf)    al1.period_year - (#(lf)        SELECT#(lf)            ( cd.period_year )#(lf)        FROM#(lf)            (#(lf)                SELECT#(lf)                    gdpm.period_set_name,#(lf)                    gp.period_name,#(lf)                    gdpm.accounting_date period_date,#(lf)                    gp.period_year,#(lf)                    gp.period_num,#(lf)                    gp.quarter_num,#(lf)                    gp.year_start_date,#(lf)                    gp.quarter_start_date#(lf)                FROM#(lf)                    gl.gl_date_period_map    gdpm,#(lf)                    gl.gl_periods            gp#(lf)                WHERE#(lf)                        gdpm.period_set_name = 'COHR Calendar'#(lf)                    AND gp.period_name = gdpm.period_name#(lf)                    AND gdpm.period_set_name = gp.period_set_name#(lf)                    AND gdpm.accounting_date = trunc(sysdate)#(lf)            ) cd#(lf)    ) fc_year_offset,#(lf)    ( ( al1.period_year - 1 ) * 4 + al1.quarter_num ) - (#(lf)        SELECT#(lf)            ( cd.period_year - 1 ) * 4 + cd.quarter_num#(lf)        FROM#(lf)            (#(lf)                SELECT#(lf)                    gdpm.period_set_name,#(lf)                    gp.period_name,#(lf)                    gdpm.accounting_date period_date,#(lf)                    gp.period_year,#(lf)                    gp.period_num,#(lf)                    gp.quarter_num,#(lf)                    gp.year_start_date,#(lf)                    gp.quarter_start_date#(lf)                FROM#(lf)                    gl.gl_date_period_map    gdpm,#(lf)                    gl.gl_periods            gp#(lf)                WHERE#(lf)                        gdpm.period_set_name = 'COHR Calendar'#(lf)                    AND gp.period_name = gdpm.period_name#(lf)                    AND gdpm.period_set_name = gp.period_set_name#(lf)                    AND gdpm.accounting_date = trunc(sysdate)#(lf)            ) cd#(lf)    ) fc_quarter_offset,#(lf)    ( ( al1.period_year - 1 ) * 12 + al1.period_num ) - (#(lf)        SELECT#(lf)            ( cd.period_year - 1 ) * 12 + cd.period_num#(lf)        FROM#(lf)            (#(lf)                SELECT#(lf)                    gdpm.period_set_name,#(lf)                    gp.period_name,#(lf)                    gdpm.accounting_date period_date,#(lf)                    gp.period_year,#(lf)                    gp.period_num,#(lf)                    gp.quarter_num,#(lf)                    gp.year_start_date,#(lf)                    gp.quarter_start_date#(lf)                FROM#(lf)                    gl.gl_date_period_map    gdpm,#(lf)                    gl.gl_periods            gp#(lf)                WHERE#(lf)                        gdpm.period_set_name = 'COHR Calendar'#(lf)                    AND gp.period_name = gdpm.period_name#(lf)                    AND gdpm.period_set_name = gp.period_set_name#(lf)                    AND gdpm.accounting_date = trunc(sysdate)#(lf)            ) cd#(lf)    ) fc_period_offset,#(lf)    ( al1.period_date - al1.year_start_date ) + 1                                                 doy_number,#(lf)    ( al1.period_date - trunc(sysdate) )                                                          fc_day_offset,#(lf)    CASE#(lf)        WHEN ceil((al1.period_date - al1.year_start_date + 1) / 7) < 10 THEN#(lf)            'W0'#(lf)            || ceil((al1.period_date - al1.year_start_date + 1) / 7)#(lf)        ELSE#(lf)            'W'#(lf)            || ceil((al1.period_date - al1.year_start_date + 1) / 7)#(lf)    END fc_week,#(lf)    CASE#(lf)        WHEN ceil((al1.period_date - al1.quarter_start_date + 1) / 7) < 10 THEN#(lf)            'QW0'#(lf)            || ceil((al1.period_date - al1.quarter_start_date + 1) / 7)#(lf)        ELSE#(lf)            'QW'#(lf)            || ceil((al1.period_date - al1.quarter_start_date + 1) / 7)#(lf)    END fc_quarter_week,#(lf)    ceil((al1.period_date - TO_DATE('02-OCT-1999', 'DD-MON-RRRR')) / 7) - ceil(((trunc(sysdate)) - TO_DATE('02-OCT-1999', 'DD-MON-RRRR')) /#(lf)    7) fc_week_offset,#(lf)    ( al1.period_year * 100 + ceil((al1.period_date - al1.year_start_date + 1) / 7) )               fc_week_series,#(lf)    ( al1.period_year * 100 + al1.period_num )                                                      fc_period_series,#(lf)    ( al1.period_year * 10 + al1.quarter_num )                                                      fc_quarter_series,#(lf)    ceil((al1.period_date - al1.year_start_date + 1) / 7)  fc_week_number,#(lf)    to_char(al1.period_date, 'DAY')                                                                 day_name,#(lf)    to_char(al1.period_date, 'D')                                                                  dow_number#(lf)FROM#(lf)    (#(lf)        SELECT#(lf)            gdpm.period_set_name,#(lf)            gp.period_name,#(lf)            gdpm.accounting_date period_date,#(lf)            gp.period_year,#(lf)            gp.period_num,#(lf)            gp.quarter_num,#(lf)            gp.year_start_date,#(lf)            gp.quarter_start_date#(lf)        FROM#(lf)            gl.gl_date_period_map    gdpm,#(lf)            gl.gl_periods            gp#(lf)        WHERE#(lf)                gdpm.period_set_name = 'COHR Calendar'#(lf)            AND gp.period_name = gdpm.period_name#(lf)            AND gdpm.period_set_name = gp.period_set_name#(lf)    ) al1\", HierarchicalNavigation = true]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"EXTRACT_DATE\", \"Extract Date\"}, {\"FC_YEAR_START_DATE\", \"FC Year Start Date\"}, {\"FC_YEAR\", \"FC Year\"}, {\"FC_QUARTER_START_DATE\", \"FC Quarter Start Date\"}, {\"FC_QUARTER\", \"FC Quarter\"}, {\"FC_PERIOD_NUMBER\", \"FC Period Number\"}, {\"FC_PERIOD_MONTH\", \"FC Period Month\"}, {\"FC_HALF\", \"FC Half\"}, {\"FC_PERIOD_NAME\", \"FC Period Name\"}, {\"FC_WEEK_SERIES\", \"FC Week Series\"}, {\"FC_WEEK_NUMBER\", \"FC Week Number\"}, {\"FC_QUARTER_WEEK\", \"FC Quarter Week\"}, {\"FC_WEEK\", \"FC Week\"}, {\"FC_DAY_OFFSET\", \"FC Day Offset\"}, {\"FC_WEEK_OFFSET\", \"FC Week Offset\"}, {\"FC_PERIOD_OFFSET\", \"FC Period Offset\"}, {\"FC_QUARTER_OFFSET\", \"FC Quarter Offset\"}, {\"FC_YEAR_OFFSET\", \"FC Year Offset\"}, {\"CALENDAR_DATE\", \"Calendar Date\"}, {\"FC_WEEK_ID\", \"FC Week ID\"}, {\"FC_PERIOD_ID\", \"FC Period ID\"}, {\"FC_QUARTER_ID\", \"FC Quarter ID\"}, {\"DOY_NUMBER\", \"Day of Year Number\"}, {\"DAY_NAME\", \"Day Name\"}, {\"DOW_NUMBER\", \"Day of Week Number\"}, {\"FC_PERIOD_SERIES\", \"FC Period Series\"}, {\"FC_QUARTER_SERIES\", \"FC Quarter Series\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared MPN = let\r\n  Source = Oracle.Database(\"COHREP\", [CommandTimeout = #duration(0, 0, 10, 0), Query = \"#(lf)  SELECT#(lf)  sysdate EXTRACT_DATE,#(lf)  MPN.manufacturer_name,#(lf)  MPN.mfg_part_num,#(lf)  MPN.inventory_item_id,#(lf)  (SELECT#(lf)    MSI.segment1#(lf)  FROM inv.mtl_system_items_b MSI#(lf)  WHERE MSI.inventory_item_id = MPN.inventory_item_id#(lf)  AND rownum = 1)#(lf)  ITEM_NUMBER#(lf)FROM#(lf)  apps.MTL_MFG_PART_NUMBERS_ALL_V MPN#(lf)\", HierarchicalNavigation = true]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"EXTRACT_DATE\", \"Extract Date\"}, {\"MANUFACTURER_NAME\", \"Manufacturer Name\"}, {\"MFG_PART_NUM\", \"Manufacturer Part Number\"}, {\"ITEM_NUMBER\", \"Item Number\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Order_Transaction_Type = let\r\n  Source = Oracle.Database(\"COHREP\", [CommandTimeout = #duration(0, 0, 10, 0), Query = \"#(lf)  SELECT#(lf)  SYSDATE EXTRACT_DATE,#(lf)   OTTL.NAME,#(lf)   OTTL.DESCRIPTION,#(lf)   OTTA.SCHEDULING_LEVEL_CODE,#(lf)   OTTA.TRANSACTION_TYPE_ID,#(lf)   OTTA.TRANSACTION_TYPE_CODE,#(lf)   OTTA.ORDER_CATEGORY_CODE,#(lf)   OTTA.START_DATE_ACTIVE,#(lf)   OTTA.END_DATE_ACTIVE,#(lf)   OTTA.CONTEXT,#(lf)   OTTA.ATTRIBUTE5 TP_CLASSIFICATION,#(lf)   OTTA.ATTRIBUTE6 ENTITY,#(lf)   OTTA.ATTRIBUTE15 TAX_APPLICABILITY,#(lf)   OTTA.ATTRIBUTE13 ACCOUNTING_TYPE,#(lf)   OTTA.ATTRIBUTE4 REVENUE_FLAG#(lf)FROM#(lf)   APPS.OE_TRANSACTION_TYPES_ALL OTTA,#(lf)   APPS.OE_TRANSACTION_TYPES_TL OTTL #(lf)WHERE#(lf)   OTTA.TRANSACTION_TYPE_ID = OTTL.TRANSACTION_TYPE_ID #(lf)   AND OTTL.LANGUAGE = 'US'#(lf)\", HierarchicalNavigation = true]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"NAME\", \"Name\"}, {\"ORDER_CATEGORY_CODE\", \"Order Category Code\"}, {\"TRANSACTION_TYPE_CODE\", \"Transaction Type Code\"}, {\"SCHEDULING_LEVEL_CODE\", \"Scheduling Level Code\"}, {\"CONTEXT\", \"Context\"}, {\"TP_CLASSIFICATION\", \"TP Classification\"}, {\"ENTITY\", \"Entity\"}, {\"TAX_APPLICABILITY\", \"Tax Applicability\"}, {\"ACCOUNTING_TYPE\", \"Accounting Type\"}, {\"START_DATE_ACTIVE\", \"Start Date\"}, {\"END_DATE_ACTIVE\", \"End Date\"}, {\"DESCRIPTION\", \"Description\"}, {\"EXTRACT_DATE\", \"Extract Date\"}, {\"REVENUE_FLAG\", \"Revenue Flag\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared TBU = let\r\n  Source = Oracle.Database(\"COHREP\", [CommandTimeout = #duration(0, 0, 10, 0), Query = \"  #(lf)SELECT#(lf)   sysdate EXTRACT_DATE,#(lf)   FVS.FLEX_VALUE_SET_NAME,#(lf)   FVS.DESCRIPTION VALUE_SET_DESCRIPTION,#(lf)   FLV.FLEX_VALUE_SET_ID,#(lf)   FLV.FLEX_VALUE_ID,#(lf)   FLV.FLEX_VALUE,#(lf)   FLV.FLEX_VALUE_MEANING,#(lf)   FLV.DESCRIPTION VALUE_DESCRIPTION,#(lf)   FLV.END_DATE_ACTIVE,#(lf)   FLV.ENABLED_FLAG#(lf)FROM#(lf)   APPS.FND_FLEX_VALUES_VL FLV,#(lf)   APPS.FND_FLEX_VALUE_SETS FVS #(lf)WHERE#(lf)   FVS.FLEX_VALUE_SET_ID = FLV.FLEX_VALUE_SET_ID #(lf)   AND UPPER(FVS.FLEX_VALUE_SET_NAME) LIKE '%TBU%'#(lf)\", HierarchicalNavigation = true]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"EXTRACT_DATE\", \"Extract Date\"}, {\"FLEX_VALUE_SET_NAME\", \"Value Set Name\"}, {\"VALUE_SET_DESCRIPTION\", \"Value Set Description\"}, {\"FLEX_VALUE\", \"Flex Value\"}, {\"FLEX_VALUE_MEANING\", \"Flex Value Meaning\"}, {\"VALUE_DESCRIPTION\", \"Value Description\"}, {\"END_DATE_ACTIVE\", \"End Date Active\"}, {\"ENABLED_FLAG\", \"Enabled Flag\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Product_Family = let\r\n  Source = Oracle.Database(\"COHREP\", [CommandTimeout = #duration(0, 0, 10, 0), Query = \"  #(lf)SELECT#(lf)   sysdate EXTRACT_DATE,#(lf)   FVS.FLEX_VALUE_SET_NAME,#(lf)   FVS.DESCRIPTION VALUE_SET_DESCRIPTION,#(lf)   FLV.FLEX_VALUE_SET_ID,#(lf)   FLV.FLEX_VALUE_ID,#(lf)   FLV.FLEX_VALUE,#(lf)   FLV.FLEX_VALUE_MEANING,#(lf)   FLV.DESCRIPTION VALUE_DESCRIPTION,#(lf)   FLV.END_DATE_ACTIVE,#(lf)   FLV.ENABLED_FLAG#(lf)FROM#(lf)   APPS.FND_FLEX_VALUES_VL FLV,#(lf)   APPS.FND_FLEX_VALUE_SETS FVS #(lf)WHERE#(lf)   FVS.FLEX_VALUE_SET_ID = FLV.FLEX_VALUE_SET_ID #(lf)   AND UPPER(FVS.FLEX_VALUE_SET_NAME) LIKE 'COHR%PRODUCT%FAMILY'#(lf)\", HierarchicalNavigation = true]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"EXTRACT_DATE\", \"Extract Date\"}, {\"FLEX_VALUE_SET_NAME\", \"Value Set Name\"}, {\"VALUE_SET_DESCRIPTION\", \"Value Set Description\"}, {\"FLEX_VALUE\", \"Flex Value\"}, {\"FLEX_VALUE_MEANING\", \"Flex Value Meaning\"}, {\"VALUE_DESCRIPTION\", \"Value Description\"}, {\"END_DATE_ACTIVE\", \"End Date Active\"}, {\"ENABLED_FLAG\", \"Enabled Flag\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Product_Line = let\r\n  Source = Oracle.Database(\"COHREP\", [CommandTimeout = #duration(0, 0, 10, 0), Query = \"  #(lf)SELECT#(lf)   sysdate EXTRACT_DATE,#(lf)   FVS.FLEX_VALUE_SET_NAME,#(lf)   FVS.DESCRIPTION VALUE_SET_DESCRIPTION,#(lf)   FLV.FLEX_VALUE_SET_ID,#(lf)   FLV.FLEX_VALUE_ID,#(lf)   FLV.FLEX_VALUE,#(lf)   FLV.FLEX_VALUE_MEANING,#(lf)   FLV.DESCRIPTION VALUE_DESCRIPTION,#(lf)   FLV.END_DATE_ACTIVE,#(lf)   FLV.ENABLED_FLAG#(lf)FROM#(lf)   APPS.FND_FLEX_VALUES_VL FLV,#(lf)   APPS.FND_FLEX_VALUE_SETS FVS #(lf)WHERE#(lf)   FVS.FLEX_VALUE_SET_ID = FLV.FLEX_VALUE_SET_ID #(lf)   AND UPPER(FVS.FLEX_VALUE_SET_NAME) LIKE 'COHR%PRODUCT%LINE'#(lf)\", HierarchicalNavigation = true]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"EXTRACT_DATE\", \"Extract Date\"}, {\"FLEX_VALUE_SET_NAME\", \"Value Set Name\"}, {\"VALUE_SET_DESCRIPTION\", \"Value Set Description\"}, {\"FLEX_VALUE\", \"Flex Value\"}, {\"FLEX_VALUE_MEANING\", \"Flex Value Meaning\"}, {\"VALUE_DESCRIPTION\", \"Value Description\"}, {\"END_DATE_ACTIVE\", \"End Date Active\"}, {\"ENABLED_FLAG\", \"Enabled Flag\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Forecast_Field = let\r\n  Source = Oracle.Database(\"COHREP\", [CommandTimeout = #duration(0, 0, 10, 0), Query = \"  #(lf)SELECT#(lf)   sysdate EXTRACT_DATE,#(lf)   FVS.FLEX_VALUE_SET_NAME,#(lf)   FVS.DESCRIPTION VALUE_SET_DESCRIPTION,#(lf)   FLV.FLEX_VALUE_SET_ID,#(lf)   FLV.FLEX_VALUE_ID,#(lf)   FLV.FLEX_VALUE,#(lf)   FLV.FLEX_VALUE_MEANING,#(lf)   FLV.DESCRIPTION VALUE_DESCRIPTION,#(lf)   FLV.END_DATE_ACTIVE,#(lf)   FLV.ENABLED_FLAG#(lf)FROM#(lf)   APPS.FND_FLEX_VALUES_VL FLV,#(lf)   APPS.FND_FLEX_VALUE_SETS FVS #(lf)WHERE#(lf)   FVS.FLEX_VALUE_SET_ID = FLV.FLEX_VALUE_SET_ID #(lf)   AND UPPER(FVS.FLEX_VALUE_SET_NAME) LIKE 'COHR%FORECAST%FIELD'#(lf)\", HierarchicalNavigation = true]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"EXTRACT_DATE\", \"Extract Date\"}, {\"FLEX_VALUE_SET_NAME\", \"Value Set Name\"}, {\"VALUE_SET_DESCRIPTION\", \"Value Set Description\"}, {\"FLEX_VALUE\", \"Flex Value\"}, {\"FLEX_VALUE_MEANING\", \"Flex Value Meaning\"}, {\"VALUE_DESCRIPTION\", \"Value Description\"}, {\"END_DATE_ACTIVE\", \"End Date Active\"}, {\"ENABLED_FLAG\", \"Enabled Flag\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Demand_Origin = let\r\n  Source = Oracle.Database(\"COHREP\", [CommandTimeout = #duration(0, 0, 10, 0), Query = \"#(lf)SELECT#(lf)  sysdate EXTRACT_DATE,#(lf)  FLV.LOOKUP_CODE Demand_ORIGIN_cODE,#(lf)  MEANING Demand_Origin,#(lf)  ENABLED_FLAG#(lf)FROM#(lf)  APPS.FND_LOOKUP_VALUES_VL FLV#(lf)WHERE#(lf)  LOOKUP_TYPE = 'MRP_DEMAND_ORIGINATION'#(lf)\", HierarchicalNavigation = true]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"DEMAND_ORIGIN\", \"Demand Origin\"}, {\"DEMAND_ORIGIN_CODE\", \"Demand Origin Code\"}, {\"EXTRACT_DATE\", \"Extract Date\"}, {\"ENABLED_FLAG\", \"Enabled Flag\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Supply_Chain_Status = let\r\n  Source = Oracle.Database(\"COHREP\", [CommandTimeout = #duration(0, 0, 10, 0), Query = \"  #(lf)SELECT#(lf)   sysdate EXTRACT_DATE,#(lf)mc.*#(lf)FROM#(lf)   APPS.mtl_categories mc#(lf)WHERE#(lf)MC.STRUCTURE_ID = 50796 --Supply Chain Status#(lf)and disable_date is null#(lf)\", HierarchicalNavigation = true]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"EXTRACT_DATE\", \"Extract Date\"}, {\"SEGMENT1\", \"Supply Chain Status\"}}),\r\n  #\"Removed other columns\" = Table.SelectColumns(#\"Renamed columns\", {\"Extract Date\", \"Supply Chain Status\"}),\r\n  #\"Inserted conditional column\" = Table.AddColumn(#\"Removed other columns\", \"Active Or Inactive\", each if [Supply Chain Status] = \"MRP Active\" then \"Active\" else if [Supply Chain Status] = \"TXN Active\" then \"Active\" else \"Inactive\"),\r\n  #\"Inserted conditional column 1\" = Table.AddColumn(#\"Inserted conditional column\", \"Sort\", each if [Supply Chain Status] = \"MRP Active\" then 1 else if [Supply Chain Status] = \"TXN Active\" then 2 else if [Supply Chain Status] = \"INV Inactive\" then 3 else if [Supply Chain Status] = \"Inactive\" then 4 else \"\"),\r\n  #\"Transform columns\" = Table.TransformColumnTypes(#\"Inserted conditional column 1\", {{\"Active Or Inactive\", type text}, {\"Sort\", type text}}),\r\n  #\"Replace errors\" = Table.ReplaceErrorValues(#\"Transform columns\", {{\"Active Or Inactive\", null}, {\"Sort\", null}})\r\nin\r\n  #\"Replace errors\";\r\nshared Business_Segment = let\r\n  Source = Oracle.Database(\"COHREP\", [CommandTimeout = #duration(0, 0, 10, 0), Query = \"#(lf) SELECT#(lf)    business_segment_id,#(lf)    business_segment,#(lf)    tbu#(lf)FROM#(lf)    xxcoh.xxcoh_business_segment_map#(lf)\", HierarchicalNavigation = true])\r\nin\r\n  Source;\r\nshared Organization = let\r\n  Source = Oracle.Database(\"COHREP\", [CommandTimeout = #duration(0, 0, 10, 0), Query = \"#(lf) SELECT#(lf)    ood.organization_code,#(lf)    mp.attribute13      organization_type,#(lf)    hou.name            operating_unit,#(lf)    sob.currency_code   functional_currency,#(lf)    sob.short_name,#(lf)    sob.description,#(lf)    ood.organization_id,#(lf)    ood.set_of_books_id#(lf)FROM#(lf)    apps.mtl_parameters                 mp,#(lf)    apps.org_organization_definitions   ood,#(lf)    apps.hr_operating_units             hou,#(lf)    apps.gl_sets_of_books_v             sob#(lf)WHERE#(lf)    mp.organization_id = ood.organization_id#(lf)    AND hou.organization_id = ood.operating_unit#(lf)    AND sob.set_of_books_id = ood.set_of_books_id#(lf)\", HierarchicalNavigation = true]),\r\n  #\"Renamed Columns\" = Table.RenameColumns(Source, {{\"ORGANIZATION_CODE\", \"Organization Code\"}, {\"ORGANIZATION_TYPE\", \"Organization Type\"}, {\"OPERATING_UNIT\", \"Operating Unit\"}, {\"FUNCTIONAL_CURRENCY\", \"Functional Currency\"}, {\"SHORT_NAME\", \"Short Name\"}, {\"DESCRIPTION\", \"Description\"}})\r\nin\r\n  #\"Renamed Columns\";\r\nshared GL_Entity = let\r\n  Source = Oracle.Database(\"COHREP\", [Query = \"SELECT#(lf)    sysdate           extract_date,#(lf)    vl.flex_value     Entity,#(lf)    tl.description    Entity_description,#(lf)vl.enabled_flag#(lf)FROM#(lf)    apps.fnd_flex_values_tl     tl,#(lf)    apps.fnd_flex_values        vl,#(lf)    apps.fnd_flex_value_sets    fst#(lf)WHERE#(lf)        1 = 1#(lf)    AND tl.flex_value_id (+) = vl.flex_value_id#(lf)    AND tl.language (+) = 'US'#(lf)    AND vl.enabled_flag = 'Y'#(lf)    AND vl.flex_value_set_id = fst.flex_value_set_id#(lf)    AND fst.flex_value_set_name like 'COHR_Ent'\"]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"ENTITY\", \"GL Entity\"}, {\"ENTITY_DESCRIPTION\", \"GL Entity Description\"}, {\"EXTRACT_DATE\", \"Extract Date\"}, {\"ENABLED_FLAG\", \"Enabled Flag\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Corporate_FX_Rate = let\r\n  Source = Oracle.Database(\"COHREP\", [CommandTimeout = #duration(0, 0, 10, 0), Query = \" SELECT#(lf) sysdate extract_date,#(lf)    from_currency,#(lf)    to_currency,#(lf)    gdr.conversion_date,#(lf)    gdr.conversion_type,#(lf)    gdr.conversion_Rate usd_rate#(lf)FROM#(lf)    apps.gl_daily_rates_v                gdr#(lf)WHERE#(lf)        conversion_type = 'Corporate'#(lf)    AND to_currency = 'USD'#(lf)\", HierarchicalNavigation = true]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"FROM_CURRENCY\", \"From Currency\"}, {\"TO_CURRENCY\", \"To Currency\"}, {\"CONVERSION_DATE\", \"Conversion Date\"}, {\"CONVERSION_TYPE\", \"Conversion Type\"}, {\"USD_RATE\", \"USD Rate\"}, {\"EXTRACT_DATE\", \"Extract Date\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Budget_Rate = let\r\n  Source = Oracle.Database(\"COHREP\", [CommandTimeout = #duration(0, 0, 10, 0), Query = \"SELECT#(cr)#(lf)    currency_code,#(cr)#(lf)    period_year,#(cr)#(lf)    rate_to_usd#(cr)#(lf)FROM#(cr)#(lf)    xxdims.xx_forecast_rates#(cr)#(lf)WHERE#(cr)#(lf)    scenario = 'BUDGET'\", CreateNavigationProperties = false]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"CURRENCY_CODE\", \"Currency Code\"}, {\"PERIOD_YEAR\", \"Fiscal Year\"}, {\"RATE_TO_USD\", \"Budget Rate\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared APOP_Baseline = let\r\n  Source = Oracle.Database(\"COHREP\", [CommandTimeout = #duration(0, 0, 10, 0), Query = \"SELECT#(lf)    inv_org_code,#(lf)    item_number,#(lf)    bp.baseline_usd_price,#(lf)    period_year#(lf)FROM#(lf)    xxdims.xx_po_baseline_price bp\", CreateNavigationProperties = false]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"INV_ORG_CODE\", \"Org\"}, {\"ITEM_NUMBER\", \"Item Number\"}, {\"BASELINE_USD_PRICE\", \"Baseline Price USD\"}, {\"PERIOD_YEAR\", \"Fiscal Year\"}})\r\nin\r\n  #\"Renamed columns\";\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"Item_Type","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Item_Type.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Item Type Code","dataType":"string"},{"name":"Item Type Name","dataType":"string"},{"name":"Enabled Flag","dataType":"string"},{"name":"Start Date Active","dataType":"dateTime"},{"name":"End Date Active","dataType":"dateTime"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-13T07:01:47.6564248+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/59a66594-0011-4b6f-b901-868bbaac92c4/Item_Type.csv?snapshot=2022-06-13T07%3A01%3A47.3940167Z"}]},{"$type":"LocalEntity","name":"Sales_Commodity","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Sales_Commodity.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"CATEGORY_ID","dataType":"double"},{"name":"Sales Commodity","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-13T07:01:42.405873+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/59a66594-0011-4b6f-b901-868bbaac92c4/Sales_Commodity.csv?snapshot=2022-06-13T07%3A01%3A42.1362577Z"}]},{"$type":"LocalEntity","name":"Sourcing_Commodity","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Sourcing_Commodity.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"CATEGORY_ID","dataType":"double"},{"name":"SEGMENT1","dataType":"string"},{"name":"Sourcing Subcategory","dataType":"string"},{"name":"UNSPSC Code","dataType":"string"},{"name":"Sourcing Commodity","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-13T07:01:46.7345397+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/59a66594-0011-4b6f-b901-868bbaac92c4/Sourcing_Commodity.csv?snapshot=2022-06-13T07%3A01%3A46.5985068Z"}]},{"$type":"LocalEntity","name":"Product_Category","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Product_Category.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"CATEGORY_ID","dataType":"double"},{"name":"TBU","dataType":"string"},{"name":"Product Family","dataType":"string"},{"name":"Product Line","dataType":"string"},{"name":"Forecast Field","dataType":"string"},{"name":"Product Category","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-13T07:01:49.247069+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/59a66594-0011-4b6f-b901-868bbaac92c4/Product_Category.csv?snapshot=2022-06-13T07%3A01%3A49.0150175Z"}]},{"$type":"LocalEntity","name":"GL_Account","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"GL_Account.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"GL Account Code","dataType":"string"},{"name":"GL Account","dataType":"string"},{"name":"Enabled Flag","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-13T07:01:40.7808316+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/59a66594-0011-4b6f-b901-868bbaac92c4/GL_Account.csv?snapshot=2022-06-13T07%3A01%3A40.7171332Z"}]},{"$type":"LocalEntity","name":"GL_Department","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"GL_Department.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"GL Department Code","dataType":"string"},{"name":"GL Department","dataType":"string"},{"name":"Enabled Flag","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-13T07:01:32.5928389+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/59a66594-0011-4b6f-b901-868bbaac92c4/GL_Department.csv?snapshot=2022-06-13T07%3A01%3A32.5101966Z"}]},{"$type":"LocalEntity","name":"GL_Project","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"GL_Project.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"GL Project Code","dataType":"string"},{"name":"GL Project","dataType":"string"},{"name":"Enabled Flag","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-13T07:01:58.9672381+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/59a66594-0011-4b6f-b901-868bbaac92c4/GL_Project.csv?snapshot=2022-06-13T07%3A01%3A57.0950399Z"}]},{"$type":"LocalEntity","name":"Fiscal_Calendar","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Fiscal_Calendar.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Calendar Date","dataType":"dateTime"},{"name":"FC Year Start Date","dataType":"dateTime"},{"name":"FC Year","dataType":"int64"},{"name":"FC Quarter Start Date","dataType":"dateTime"},{"name":"FC Quarter","dataType":"string"},{"name":"FC Half","dataType":"string"},{"name":"FC Period Number","dataType":"int64"},{"name":"FC Period Month","dataType":"string"},{"name":"FC Period Name","dataType":"string"},{"name":"FC Period ID","dataType":"double"},{"name":"FC Quarter ID","dataType":"double"},{"name":"FC Week ID","dataType":"double"},{"name":"FC Year Offset","dataType":"double"},{"name":"FC Quarter Offset","dataType":"double"},{"name":"FC Period Offset","dataType":"double"},{"name":"Day of Year Number","dataType":"double"},{"name":"FC Day Offset","dataType":"double"},{"name":"FC Week","dataType":"string"},{"name":"FC Quarter Week","dataType":"string"},{"name":"FC Week Offset","dataType":"double"},{"name":"FC Week Series","dataType":"double"},{"name":"FC Period Series","dataType":"double"},{"name":"FC Quarter Series","dataType":"double"},{"name":"FC Week Number","dataType":"double"},{"name":"Day Name","dataType":"string"},{"name":"Day of Week Number","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-13T07:04:46.0888318+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/59a66594-0011-4b6f-b901-868bbaac92c4/Fiscal_Calendar.csv?snapshot=2022-06-13T07%3A04%3A44.0419117Z"}]},{"$type":"LocalEntity","name":"MPN","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"MPN.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Manufacturer Name","dataType":"string"},{"name":"Manufacturer Part Number","dataType":"string"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"Item Number","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-13T07:02:00.498497+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/59a66594-0011-4b6f-b901-868bbaac92c4/MPN.csv?snapshot=2022-06-13T07%3A01%3A59.5965002Z"}]},{"$type":"LocalEntity","name":"Order_Transaction_Type","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Order_Transaction_Type.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Name","dataType":"string"},{"name":"Description","dataType":"string"},{"name":"Scheduling Level Code","dataType":"string"},{"name":"TRANSACTION_TYPE_ID","dataType":"double"},{"name":"Transaction Type Code","dataType":"string"},{"name":"Order Category Code","dataType":"string"},{"name":"Start Date","dataType":"dateTime"},{"name":"End Date","dataType":"dateTime"},{"name":"Context","dataType":"string"},{"name":"TP Classification","dataType":"string"},{"name":"Entity","dataType":"string"},{"name":"Tax Applicability","dataType":"string"},{"name":"Accounting Type","dataType":"string"},{"name":"Revenue Flag","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-13T07:01:59.6391155+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/59a66594-0011-4b6f-b901-868bbaac92c4/Order_Transaction_Type.csv?snapshot=2022-06-13T07%3A01%3A58.0134750Z"}]},{"$type":"LocalEntity","name":"TBU","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"TBU.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Value Set Name","dataType":"string"},{"name":"Value Set Description","dataType":"string"},{"name":"FLEX_VALUE_SET_ID","dataType":"int64"},{"name":"FLEX_VALUE_ID","dataType":"int64"},{"name":"Flex Value","dataType":"string"},{"name":"Flex Value Meaning","dataType":"string"},{"name":"Value Description","dataType":"string"},{"name":"End Date Active","dataType":"dateTime"},{"name":"Enabled Flag","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-13T07:01:24.8946604+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/59a66594-0011-4b6f-b901-868bbaac92c4/TBU.csv?snapshot=2022-06-13T07%3A01%3A24.8609197Z"}]},{"$type":"LocalEntity","name":"Product_Family","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Product_Family.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Value Set Name","dataType":"string"},{"name":"Value Set Description","dataType":"string"},{"name":"FLEX_VALUE_SET_ID","dataType":"int64"},{"name":"FLEX_VALUE_ID","dataType":"int64"},{"name":"Flex Value","dataType":"string"},{"name":"Flex Value Meaning","dataType":"string"},{"name":"Value Description","dataType":"string"},{"name":"End Date Active","dataType":"dateTime"},{"name":"Enabled Flag","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-13T07:01:45.9220402+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/59a66594-0011-4b6f-b901-868bbaac92c4/Product_Family.csv?snapshot=2022-06-13T07%3A01%3A45.7410352Z"}]},{"$type":"LocalEntity","name":"Product_Line","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Product_Line.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Value Set Name","dataType":"string"},{"name":"Value Set Description","dataType":"string"},{"name":"FLEX_VALUE_SET_ID","dataType":"int64"},{"name":"FLEX_VALUE_ID","dataType":"int64"},{"name":"Flex Value","dataType":"string"},{"name":"Flex Value Meaning","dataType":"string"},{"name":"Value Description","dataType":"string"},{"name":"End Date Active","dataType":"dateTime"},{"name":"Enabled Flag","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-13T07:01:48.0470617+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/59a66594-0011-4b6f-b901-868bbaac92c4/Product_Line.csv?snapshot=2022-06-13T07%3A01%3A47.6488598Z"}]},{"$type":"LocalEntity","name":"Forecast_Field","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Forecast_Field.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Value Set Name","dataType":"string"},{"name":"Value Set Description","dataType":"string"},{"name":"FLEX_VALUE_SET_ID","dataType":"int64"},{"name":"FLEX_VALUE_ID","dataType":"int64"},{"name":"Flex Value","dataType":"string"},{"name":"Flex Value Meaning","dataType":"string"},{"name":"Value Description","dataType":"string"},{"name":"End Date Active","dataType":"dateTime"},{"name":"Enabled Flag","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-13T07:01:25.2391878+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/59a66594-0011-4b6f-b901-868bbaac92c4/Forecast_Field.csv?snapshot=2022-06-13T07%3A01%3A25.1487423Z"}]},{"$type":"LocalEntity","name":"Demand_Origin","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Demand_Origin.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Demand Origin Code","dataType":"string"},{"name":"Demand Origin","dataType":"string"},{"name":"Enabled Flag","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-13T07:01:46.4845495+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/59a66594-0011-4b6f-b901-868bbaac92c4/Demand_Origin.csv?snapshot=2022-06-13T07%3A01%3A46.3546567Z"}]},{"$type":"LocalEntity","name":"Supply_Chain_Status","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Supply_Chain_Status.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Supply Chain Status","dataType":"string"},{"name":"Active Or Inactive","dataType":"string"},{"name":"Sort","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-13T07:01:48.8866526+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/59a66594-0011-4b6f-b901-868bbaac92c4/Supply_Chain_Status.csv?snapshot=2022-06-13T07%3A01%3A48.2884647Z"}]},{"$type":"LocalEntity","name":"Business_Segment","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Business_Segment.csv"},"attributes":[{"name":"BUSINESS_SEGMENT_ID","dataType":"double"},{"name":"BUSINESS_SEGMENT","dataType":"string"},{"name":"TBU","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-13T07:04:31.460164+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/59a66594-0011-4b6f-b901-868bbaac92c4/Business_Segment.csv?snapshot=2022-06-13T07%3A04%3A30.1633601Z"}]},{"$type":"LocalEntity","name":"Organization","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Organization.csv"},"attributes":[{"name":"Organization Code","dataType":"string"},{"name":"Organization Type","dataType":"string"},{"name":"Operating Unit","dataType":"string"},{"name":"Functional Currency","dataType":"string"},{"name":"Short Name","dataType":"string"},{"name":"Description","dataType":"string"},{"name":"ORGANIZATION_ID","dataType":"int64"},{"name":"SET_OF_BOOKS_ID","dataType":"int64"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-13T07:01:43.2974713+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/59a66594-0011-4b6f-b901-868bbaac92c4/Organization.csv?snapshot=2022-06-13T07%3A01%3A42.9937288Z"}]},{"$type":"LocalEntity","name":"GL_Entity","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"GL_Entity.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"GL Entity","dataType":"string"},{"name":"GL Entity Description","dataType":"string"},{"name":"Enabled Flag","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-13T07:01:25.7392001+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/59a66594-0011-4b6f-b901-868bbaac92c4/GL_Entity.csv?snapshot=2022-06-13T07%3A01%3A25.6474343Z"}]},{"$type":"LocalEntity","name":"Corporate_FX_Rate","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Corporate_FX_Rate.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"From Currency","dataType":"string"},{"name":"To Currency","dataType":"string"},{"name":"Conversion Date","dataType":"dateTime"},{"name":"Conversion Type","dataType":"string"},{"name":"USD Rate","dataType":"double"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-13T07:02:03.4204128+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/59a66594-0011-4b6f-b901-868bbaac92c4/Corporate_FX_Rate.csv?snapshot=2022-06-13T07%3A02%3A00.0991909Z"}]},{"$type":"LocalEntity","name":"Budget_Rate","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Budget_Rate.csv"},"attributes":[{"name":"Currency Code","dataType":"string"},{"name":"Fiscal Year","dataType":"int64"},{"name":"Budget Rate","dataType":"double"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-13T07:01:32.8428395+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/59a66594-0011-4b6f-b901-868bbaac92c4/Budget_Rate.csv?snapshot=2022-06-13T07%3A01%3A32.5581668Z"}]},{"$type":"LocalEntity","name":"APOP_Baseline","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"APOP_Baseline.csv"},"attributes":[{"name":"Org","dataType":"string"},{"name":"Item Number","dataType":"string"},{"name":"Baseline Price USD","dataType":"double"},{"name":"Fiscal Year","dataType":"double"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-13T07:01:43.0152283+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/59a66594-0011-4b6f-b901-868bbaac92c4/APOP_Baseline.csv?snapshot=2022-06-13T07%3A01%3A42.9387627Z"}]}]}