{"name":"Flow_Kardex","description":"Snowflake Kardex transactions (Import / Export).\nRefresh Monday to Friday ( 4am CET).","version":"1.0","culture":"en-US","modifiedTime":"2022-03-06T16:31:44.3470649+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":true,"queriesMetadata":{"XXCOH_KARDEX_EXPORT_STG":{"queryId":"d7d6b35e-aa86-4e3f-9da8-b445c79fe982","queryName":"XXCOH_KARDEX_EXPORT_STG","loadEnabled":true},"XXCOH_KARDEX_IMPORT_STG":{"queryId":"c01b562f-e4be-4958-b5ff-497cc7388c58","queryName":"XXCOH_KARDEX_IMPORT_STG","loadEnabled":true},"RangeStart":{"queryId":"8affe644-4fe6-4800-9933-509d339c1705","queryName":"RangeStart"},"RangeEnd":{"queryId":"98b6ea38-fa33-4407-8aa6-08197d73fc8c","queryName":"RangeEnd"}},"document":"section Section1;\r\n\r\nshared XXCOH_KARDEX_EXPORT_STG = let\r\n    Source = Value.NativeQuery(Snowflake.Databases(\"mma12090.snowflakecomputing.com\",\"COMPUTE_REPORTING\",[Role=\"GLBMFGOPERATIONSROLE\"]){[Name=\"PROD_DB\"]}[Data], \"SELECT *#(lf)FROM PROD_DB.XXCOH.XXCOH_KARDEX_EXPORT_STG\", null, [EnableFolding=true]),\r\n    #\"Changed column type\" = Table.TransformColumnTypes(Source, {{\"ORGANIZATION_ID\", Int64.Type}, {\"REQUEST_ID\", Int64.Type}, {\"INVENTORY_ITEM_ID\", Int64.Type}, {\"WIP_ENTITY_ID\", Int64.Type}, {\"LOCATION_ID\", Int64.Type}, {\"EMPLOYEE_ID\", Int64.Type}, {\"CYCLE_COUNT_HEADER_ID\", Int64.Type}, {\"CYCLE_COUNT_ENTRY_ID\", Int64.Type}, {\"ROW_UID\", Int64.Type}}),\r\n    #\"Marked key columns\" = Table.AddKey(#\"Changed column type\", {\"ROW_UID\"}, false),\r\n    #\"XXCOH_KARDEX_EXPORT_STG-46494C455F50524F434553535F44415445-autogenerated_for_incremental_refresh\" = Table.SelectRows(#\"Marked key columns\", each DateTime.From([FILE_PROCESS_DATE]) >= RangeStart and DateTime.From([FILE_PROCESS_DATE]) < RangeEnd)\r\nin\r\n    #\"XXCOH_KARDEX_EXPORT_STG-46494C455F50524F434553535F44415445-autogenerated_for_incremental_refresh\";\r\n\r\nshared XXCOH_KARDEX_IMPORT_STG = let\r\n    Source = Value.NativeQuery(Snowflake.Databases(\"mma12090.snowflakecomputing.com\",\"COMPUTE_REPORTING\",[Role=\"GLBMFGOPERATIONSROLE\"]){[Name=\"PROD_DB\"]}[Data], \"SELECT *#(lf)FROM PROD_DB.XXCOH.XXCOH_KARDEX_IMPORT_STG\", null, [EnableFolding=true]),\r\n    #\"Changed column type\" = Table.TransformColumnTypes(Source, {{\"ORGANIZATION_ID\", Int64.Type}, {\"TRANSACTION_ID\", Int64.Type}, {\"LINE_ID\", Int64.Type}, {\"REQUEST_ID\", Int64.Type}, {\"ROW_UID\", Int64.Type}}),\r\n    #\"Marked key columns\" = Table.AddKey(#\"Changed column type\", {\"ROW_UID\"}, false),\r\n    #\"XXCOH_KARDEX_IMPORT_STG-4352454154494F4E5F44415445-autogenerated_for_incremental_refresh\" = Table.SelectRows(#\"Marked key columns\", each DateTime.From([CREATION_DATE]) >= RangeStart and DateTime.From([CREATION_DATE]) < RangeEnd)\r\nin\r\n    #\"XXCOH_KARDEX_IMPORT_STG-4352454154494F4E5F44415445-autogenerated_for_incremental_refresh\";\r\n\r\nshared RangeStart = let RangeStart = #datetime(0001,01,01,00,00,00) meta [IsParameterQuery=true, List={}, Type=\"DateTime\", IsParameterQueryRequired=true, Description=\"autogenerated_for_incremental_refresh\"] in RangeStart;\r\n\r\nshared RangeEnd = let RangeEnd = #datetime(9999,12,31,23,59,59) meta [IsParameterQuery=true, List={}, Type=\"DateTime\", IsParameterQueryRequired=true, Description=\"autogenerated_for_incremental_refresh\"] in RangeEnd;\r\n\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"XXCOH_KARDEX_EXPORT_STG","description":"","pbi:refreshPolicy":{"$type":"IncrementalRefreshPolicy","locationPattern":"XXCOH_KARDEX_EXPORT_STG/part.csv","rollingWindowGranularity":"year","rollingWindowPeriods":5,"incrementalGranularity":"quarter","incrementalPeriods":5},"annotations":[{"name":"pbi:IncrementalRefreshDetectChangeAttribute"},{"name":"pbi:IncrementalRefreshFilterByAttribute","value":"FILE_PROCESS_DATE"}],"attributes":[{"name":"ORG_NAME","dataType":"string"},{"name":"FILE_PROCESS_DATE","dataType":"dateTime"},{"name":"FILE_NAME","dataType":"string"},{"name":"INTERFACE_TYPE","dataType":"string"},{"name":"FILE_LINE","dataType":"double"},{"name":"ERROR_STATUS","dataType":"string"},{"name":"ERROR_MESSAGE","dataType":"string"},{"name":"DATA_STRING","dataType":"string"},{"name":"SUBINVENTORY_CODE","dataType":"string"},{"name":"EXPOR_STATUS_KARDEX","dataType":"string"},{"name":"MOVE_ORDER","dataType":"string"},{"name":"ITEM_NUMBER","dataType":"string"},{"name":"SERIAL_NUMBER","dataType":"string"},{"name":"LOT_NUMBER","dataType":"string"},{"name":"PICKED_QTY","dataType":"double"},{"name":"MOVE_ORDER_LINE_ID","dataType":"string"},{"name":"REQUEST_ID","dataType":"int64"},{"name":"ORGANIZATION_ID","dataType":"int64"},{"name":"SEND_EMAIL_FLAG","dataType":"string"},{"name":"INVENTORY_ITEM_ID","dataType":"int64"},{"name":"SEND_EMAIL_DATE","dataType":"dateTime"},{"name":"WIP_JOB_NUMBER","dataType":"string"},{"name":"OPERATION_SEQUENCE","dataType":"string"},{"name":"WIP_ENTITY_ID","dataType":"int64"},{"name":"PRIMARY_UOM_CODE","dataType":"string"},{"name":"COUNT_CYCLE_NAME","dataType":"string"},{"name":"COUNT_SEQ_NUMBER","dataType":"string"},{"name":"QUANTITY","dataType":"double"},{"name":"ITEM_DESCRIPTION","dataType":"string"},{"name":"CYCLE_COUNT_ENTRY_ID","dataType":"int64"},{"name":"CYCLE_COUNT_HEADER_ID","dataType":"int64"},{"name":"SEIBAN","dataType":"string"},{"name":"LOCATION_ID","dataType":"int64"},{"name":"COUNTED_BY","dataType":"string"},{"name":"EMPLOYEE_ID","dataType":"int64"},{"name":"COUNT_DATE","dataType":"string"},{"name":"PICKED_QTY_CHAR","dataType":"string"},{"name":"ROW_UID","dataType":"int64"},{"name":"KARDEX_USER","dataType":"string"},{"name":"ADD_INFO1","dataType":"string"},{"name":"ADD_INFO2","dataType":"string"},{"name":"ADD_INFO3","dataType":"string"},{"name":"ADD_INFO4","dataType":"string"},{"name":"ADD_INFO5","dataType":"string"},{"name":"ADD_INFO6","dataType":"string"},{"name":"ADD_INFO7","dataType":"string"}],"partitions":[{"name":"IncrementalRefreshPolicyPartition-2017","refreshTime":"2022-03-06T16:31:57.1181387+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/20621645-6cd1-4eb9-98a3-6bfc59fcc024/XXCOH_KARDEX_EXPORT_STG/part-2017.csv?snapshot=2022-03-06T16%3A31%3A56.6544788Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2017-01-01T00:00:00","end":"2018-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2018","refreshTime":"2022-03-06T16:31:57.0868664+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/20621645-6cd1-4eb9-98a3-6bfc59fcc024/XXCOH_KARDEX_EXPORT_STG/part-2018.csv?snapshot=2022-03-06T16%3A31%3A56.9992797Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2018-01-01T00:00:00","end":"2019-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2019","refreshTime":"2022-03-06T16:31:58.1984658+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/20621645-6cd1-4eb9-98a3-6bfc59fcc024/XXCOH_KARDEX_EXPORT_STG/part-2019.csv?snapshot=2022-03-06T16%3A31%3A57.3530752Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2019-01-01T00:00:00","end":"2020-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2020","refreshTime":"2022-03-06T16:32:28.2951985+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/20621645-6cd1-4eb9-98a3-6bfc59fcc024/XXCOH_KARDEX_EXPORT_STG/part-2020.csv?snapshot=2022-03-06T16%3A32%3A28.2632186Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2020-01-01T00:00:00","end":"2021-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2021Q1","refreshTime":"2022-04-01T05:13:23.3967762+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/20621645-6cd1-4eb9-98a3-6bfc59fcc024/XXCOH_KARDEX_EXPORT_STG/part-2021Q1.csv?snapshot=2022-04-01T05%3A13%3A23.3128673Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2021-01-01T00:00:00","end":"2021-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2021Q2","refreshTime":"2022-05-20T05:03:29.8633302+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/20621645-6cd1-4eb9-98a3-6bfc59fcc024/XXCOH_KARDEX_EXPORT_STG/part-2021Q2.csv?snapshot=2022-05-20T05%3A03%3A29.4957658Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2021-04-01T00:00:00","end":"2021-07-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2021Q3","refreshTime":"2022-05-20T05:03:19.5400614+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/20621645-6cd1-4eb9-98a3-6bfc59fcc024/XXCOH_KARDEX_EXPORT_STG/part-2021Q3.csv?snapshot=2022-05-20T05%3A03%3A19.2935752Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2021-07-01T00:00:00","end":"2021-10-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2021Q4","refreshTime":"2022-05-20T05:03:05.8997198+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/20621645-6cd1-4eb9-98a3-6bfc59fcc024/XXCOH_KARDEX_EXPORT_STG/part-2021Q4.csv?snapshot=2022-05-20T05%3A03%3A05.7243006Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2021-10-01T00:00:00","end":"2022-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q1","refreshTime":"2022-05-20T05:03:03.519103+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/20621645-6cd1-4eb9-98a3-6bfc59fcc024/XXCOH_KARDEX_EXPORT_STG/part-2022Q1.csv?snapshot=2022-05-20T05%3A03%3A03.0728099Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-01-01T00:00:00","end":"2022-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q2","refreshTime":"2022-05-20T05:02:58.1024968+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/20621645-6cd1-4eb9-98a3-6bfc59fcc024/XXCOH_KARDEX_EXPORT_STG/part-2022Q2.csv?snapshot=2022-05-20T05%3A02%3A57.7408452Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-01T00:00:00","end":"2022-07-01T00:00:00"}}]},{"$type":"LocalEntity","name":"XXCOH_KARDEX_IMPORT_STG","description":"","pbi:refreshPolicy":{"$type":"IncrementalRefreshPolicy","locationPattern":"XXCOH_KARDEX_IMPORT_STG/part.csv","rollingWindowGranularity":"year","rollingWindowPeriods":5,"incrementalGranularity":"quarter","incrementalPeriods":5},"annotations":[{"name":"pbi:IncrementalRefreshDetectChangeAttribute"},{"name":"pbi:IncrementalRefreshFilterByAttribute","value":"CREATION_DATE"}],"attributes":[{"name":"ORGANIZATION_ID","dataType":"int64"},{"name":"TRANSACTION_ID","dataType":"int64"},{"name":"SOURCE_NAME","dataType":"string"},{"name":"ITEM_NUMBER","dataType":"string"},{"name":"TRANSACTION_QUANTITY","dataType":"double"},{"name":"SERIAL_NUMBER","dataType":"string"},{"name":"LOT_NUMBER","dataType":"string"},{"name":"SOURCE_TYPE","dataType":"string"},{"name":"TRANSACTION_TYPE","dataType":"string"},{"name":"REASON","dataType":"string"},{"name":"REFERENCE","dataType":"string"},{"name":"ITEM_DESCRIPTION","dataType":"string"},{"name":"OUTPUT_FILE_ROW","dataType":"string"},{"name":"TRANSACTION_DATE","dataType":"dateTime"},{"name":"INTERFACE_TYPE","dataType":"string"},{"name":"CREATION_DATE","dataType":"dateTime"},{"name":"WIP_ENTITY_ID","dataType":"double"},{"name":"WIP_ENTITY_NAME","dataType":"string"},{"name":"MOVE_ORDER_NUMBER","dataType":"string"},{"name":"LINE_ID","dataType":"int64"},{"name":"SUBINVENTORY_CODE","dataType":"string"},{"name":"SEIBAN","dataType":"string"},{"name":"OPERATION_SEQ_NUM","dataType":"string"},{"name":"DATE_REQUIRED","dataType":"dateTime"},{"name":"LEVEL_NUMBER","dataType":"double"},{"name":"SUBASSY_ITEM_NUMBER","dataType":"string"},{"name":"SUBASSY_DESCRIPTION","dataType":"string"},{"name":"SOURCE_HEADER_TYPE_NAME","dataType":"string"},{"name":"SOURCE_HEADER_NUMBER","dataType":"string"},{"name":"CUSTOMER_NAME","dataType":"string"},{"name":"STATUS_FLAG","dataType":"string"},{"name":"ERROR_MESSAGE","dataType":"string"},{"name":"REQUEST_ID","dataType":"int64"},{"name":"ROW_UID","dataType":"int64"},{"name":"ADD_INFO1","dataType":"string"},{"name":"ADD_INFO2","dataType":"string"},{"name":"ADD_INFO3","dataType":"string"},{"name":"ADD_INFO4","dataType":"string"},{"name":"ADD_INFO5","dataType":"string"},{"name":"ADD_INFO6","dataType":"string"},{"name":"ADD_INFO7","dataType":"string"},{"name":"ADD_INFO8","dataType":"string"}],"partitions":[{"name":"IncrementalRefreshPolicyPartition-2017","refreshTime":"2022-03-06T16:31:57.6359597+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/20621645-6cd1-4eb9-98a3-6bfc59fcc024/XXCOH_KARDEX_IMPORT_STG/part-2017.csv?snapshot=2022-03-06T16%3A31%3A56.8283782Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2017-01-01T00:00:00","end":"2018-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2018","refreshTime":"2022-03-06T16:31:58.0265718+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/20621645-6cd1-4eb9-98a3-6bfc59fcc024/XXCOH_KARDEX_IMPORT_STG/part-2018.csv?snapshot=2022-03-06T16%3A31%3A57.4090427Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2018-01-01T00:00:00","end":"2019-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2019","refreshTime":"2022-03-06T16:31:54.396084+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/20621645-6cd1-4eb9-98a3-6bfc59fcc024/XXCOH_KARDEX_IMPORT_STG/part-2019.csv?snapshot=2022-03-06T16%3A31%3A54.1968986Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2019-01-01T00:00:00","end":"2020-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2020","refreshTime":"2022-03-06T16:32:23.3807847+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/20621645-6cd1-4eb9-98a3-6bfc59fcc024/XXCOH_KARDEX_IMPORT_STG/part-2020.csv?snapshot=2022-03-06T16%3A32%3A23.1941465Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2020-01-01T00:00:00","end":"2021-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2021Q1","refreshTime":"2022-04-01T05:11:49.2481947+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/20621645-6cd1-4eb9-98a3-6bfc59fcc024/XXCOH_KARDEX_IMPORT_STG/part-2021Q1.csv?snapshot=2022-04-01T05%3A11%3A49.1422438Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2021-01-01T00:00:00","end":"2021-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2021Q2","refreshTime":"2022-05-20T05:03:33.7761588+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/20621645-6cd1-4eb9-98a3-6bfc59fcc024/XXCOH_KARDEX_IMPORT_STG/part-2021Q2.csv?snapshot=2022-05-20T05%3A03%3A33.5784412Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2021-04-01T00:00:00","end":"2021-07-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2021Q3","refreshTime":"2022-05-20T05:03:05.8684798+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/20621645-6cd1-4eb9-98a3-6bfc59fcc024/XXCOH_KARDEX_IMPORT_STG/part-2021Q3.csv?snapshot=2022-05-20T05%3A03%3A05.4004844Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2021-07-01T00:00:00","end":"2021-10-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2021Q4","refreshTime":"2022-05-20T05:03:25.5889862+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/20621645-6cd1-4eb9-98a3-6bfc59fcc024/XXCOH_KARDEX_IMPORT_STG/part-2021Q4.csv?snapshot=2022-05-20T05%3A03%3A25.4800525Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2021-10-01T00:00:00","end":"2022-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q1","refreshTime":"2022-05-20T05:03:52.7009784+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/20621645-6cd1-4eb9-98a3-6bfc59fcc024/XXCOH_KARDEX_IMPORT_STG/part-2022Q1.csv?snapshot=2022-05-20T05%3A03%3A52.6675728Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-01-01T00:00:00","end":"2022-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q2","refreshTime":"2022-05-20T05:02:51.0117512+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/20621645-6cd1-4eb9-98a3-6bfc59fcc024/XXCOH_KARDEX_IMPORT_STG/part-2022Q2.csv?snapshot=2022-05-20T05%3A02%3A50.7987983Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-01T00:00:00","end":"2022-07-01T00:00:00"}}]}]}