{"name":"Flow_Oracle_Jobs","description":"Oracle Job data, material transaction.","version":"1.0","culture":"en-US","modifiedTime":"2022-03-08T23:17:25.6708024+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":true,"queriesMetadata":{"XXREP_MTL_MATERIAL_TRANSACTIONS_GEP-KEP":{"queryId":"f300cfaf-78e7-4680-89cf-1363b2ff1a1e","queryName":"XXREP_MTL_MATERIAL_TRANSACTIONS_GEP-KEP"},"XXREP_MTL_MATERIAL_TRANSACTIONS":{"queryId":"5ea882b9-3f05-4ca7-9edf-805ce4b186f0","queryName":"XXREP_MTL_MATERIAL_TRANSACTIONS","loadEnabled":true}},"document":"section Section1;\r\nshared #\"XXREP_MTL_MATERIAL_TRANSACTIONS_GEP-KEP\" = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\"),\r\n  PROD_DB_Database = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  APPS_Schema = PROD_DB_Database{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n  XXREP_MTL_MATERIAL_TRANSACTIONS_View = APPS_Schema{[Name = \"XXREP_MTL_MATERIAL_TRANSACTIONS\", Kind = \"View\"]}[Data],\r\n  #\"Filtered Rows\" = Table.SelectRows(XXREP_MTL_MATERIAL_TRANSACTIONS_View, each Date.IsInPreviousNDays([LAST_UPDATE_DATE], 740)),\r\n  #\"Filtered Rows1\" = Table.SelectRows(#\"Filtered Rows\", each [OWNING_ORGANIZATION_ID] = 944 or [OWNING_ORGANIZATION_ID] = 3306),\r\n  #\"Removed Other Columns\" = Table.SelectColumns(#\"Filtered Rows1\", {\"TRANSACTION_ID\", \"LAST_UPDATE_DATE\", \"CREATION_DATE\", \"REQUEST_ID\", \"PROGRAM_APPLICATION_ID\", \"PROGRAM_ID\", \"PROGRAM_UPDATE_DATE\", \"INVENTORY_ITEM_ID\", \"REVISION\", \"ORGANIZATION_ID\", \"SUBINVENTORY_CODE\", \"LOCATOR_ID\", \"TRANSACTION_TYPE_ID\", \"TRANSACTION_ACTION_ID\", \"TRANSACTION_SOURCE_TYPE_ID\", \"TRANSACTION_SOURCE_ID\", \"TRANSACTION_SOURCE_NAME\", \"TRANSACTION_QUANTITY\", \"TRANSACTION_UOM\", \"PRIMARY_QUANTITY\", \"TRANSACTION_DATE\", \"VARIANCE_AMOUNT\", \"TRANSACTION_REFERENCE\", \"REASON_ID\", \"DISTRIBUTION_ACCOUNT_ID\", \"ENCUMBRANCE_ACCOUNT\", \"ENCUMBRANCE_AMOUNT\", \"COST_UPDATE_ID\", \"COSTED_FLAG\", \"TRANSACTION_GROUP_ID\", \"INVOICED_FLAG\", \"ACTUAL_COST\", \"TRANSACTION_COST\", \"PRIOR_COST\", \"NEW_COST\", \"CURRENCY_CODE\", \"CURRENCY_CONVERSION_RATE\", \"CURRENCY_CONVERSION_TYPE\", \"CURRENCY_CONVERSION_DATE\", \"USSGL_TRANSACTION_CODE\", \"QUANTITY_ADJUSTED\", \"DEPARTMENT_ID\", \"RECEIVING_DOCUMENT\", \"PICKING_LINE_ID\", \"TRANSFER_TRANSACTION_ID\", \"RCV_TRANSACTION_ID\", \"MOVE_TRANSACTION_ID\", \"SHORTAGE_PROCESS_CODE\", \"SOURCE_CODE\", \"SOURCE_LINE_ID\", \"VENDOR_LOT_NUMBER\", \"TRANSFER_ORGANIZATION_ID\", \"TRANSFER_SUBINVENTORY\", \"TRANSFER_LOCATOR_ID\", \"SHIPMENT_NUMBER\", \"TRANSFER_COST\", \"TRANSFER_COST_DIST_ACCOUNT\", \"NUMBER_OF_CONTAINERS\", \"VALUE_CHANGE\", \"PERCENTAGE_CHANGE\", \"EXPENDITURE_TYPE\", \"ERROR_CODE\", \"ERROR_EXPLANATION\", \"FINAL_COMPLETION_FLAG\", \"PM_COST_COLLECTED\", \"PM_COST_COLLECTOR_GROUP_ID\", \"TRANSFER_PERCENTAGE\", \"MATERIAL_ACCOUNT\", \"MATERIAL_OVERHEAD_ACCOUNT\", \"RESOURCE_ACCOUNT\", \"OUTSIDE_PROCESSING_ACCOUNT\", \"OVERHEAD_ACCOUNT\", \"FLOW_SCHEDULE\", \"OVERCOMPLETION_TRANSACTION_QTY\", \"OVERCOMPLETION_PRIMARY_QTY\", \"OVERCOMPLETION_TRANSACTION_ID\", \"MVT_STAT_STATUS\", \"PERIODIC_PRIMARY_QUANTITY\", \"PICK_SLIP_NUMBER\", \"PICK_SLIP_DATE\", \"ORGANIZATION_TYPE\", \"TRANSFER_ORGANIZATION_TYPE\", \"OWNING_ORGANIZATION_ID\", \"OWNING_TP_TYPE\", \"XFR_OWNING_ORGANIZATION_ID\", \"TRANSFER_OWNING_TP_TYPE\", \"PLANNING_ORGANIZATION_ID\", \"PLANNING_TP_TYPE\", \"TRANSFER_PLANNING_TP_TYPE\", \"SECONDARY_UOM_CODE\", \"SECONDARY_TRANSACTION_QUANTITY\", \"TRANSACTION_GROUP_SEQ\", \"TRANSACTION_MODE\", \"TRANSACTION_BATCH_ID\", \"TRANSACTION_BATCH_SEQ\", \"INTRANSIT_ACCOUNT\", \"FOB_POINT\", \"LOGICAL_TRX_TYPE_CODE\", \"INTERCOMPANY_COST\", \"INTERCOMPANY_PRICING_OPTION\", \"INTERCOMPANY_CURRENCY_CODE\", \"ORIGINAL_TRANSACTION_TEMP_ID\", \"TRANSFER_PRICE\", \"EXPENSE_ACCOUNT_ID\", \"COGS_RECOGNITION_PERCENT\", \"SO_ISSUE_ACCOUNT_TYPE\", \"OPM_COSTED_FLAG\", \"MATERIAL_EXPENSE_ACCOUNT\", \"TRANSACTION_EXTRACTED\", \"XML_DOCUMENT_ID\", \"ITEM_ORG_KEY_ID\"}),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Removed Other Columns\", {{\"TRANSACTION_ID\", Int64.Type}, {\"REQUEST_ID\", Int64.Type}, {\"PROGRAM_APPLICATION_ID\", Int64.Type}, {\"PROGRAM_ID\", Int64.Type}, {\"INVENTORY_ITEM_ID\", Int64.Type}, {\"ORGANIZATION_ID\", Int64.Type}, {\"LOCATOR_ID\", Int64.Type}, {\"TRANSACTION_TYPE_ID\", Int64.Type}, {\"TRANSACTION_ACTION_ID\", Int64.Type}, {\"TRANSACTION_SOURCE_TYPE_ID\", Int64.Type}, {\"TRANSACTION_SOURCE_ID\", Int64.Type}, {\"REASON_ID\", Int64.Type}, {\"DISTRIBUTION_ACCOUNT_ID\", Int64.Type}, {\"COST_UPDATE_ID\", Int64.Type}, {\"TRANSACTION_GROUP_ID\", Int64.Type}, {\"DEPARTMENT_ID\", Int64.Type}, {\"PICKING_LINE_ID\", Int64.Type}, {\"TRANSFER_TRANSACTION_ID\", Int64.Type}, {\"RCV_TRANSACTION_ID\", Int64.Type}, {\"MOVE_TRANSACTION_ID\", Int64.Type}, {\"SOURCE_LINE_ID\", Int64.Type}, {\"TRANSFER_ORGANIZATION_ID\", Int64.Type}, {\"TRANSFER_LOCATOR_ID\", Int64.Type}, {\"PM_COST_COLLECTOR_GROUP_ID\", Int64.Type}, {\"OVERCOMPLETION_TRANSACTION_ID\", Int64.Type}, {\"ORGANIZATION_TYPE\", Int64.Type}, {\"TRANSFER_ORGANIZATION_TYPE\", Int64.Type}, {\"OWNING_ORGANIZATION_ID\", Int64.Type}, {\"OWNING_TP_TYPE\", Int64.Type}, {\"XFR_OWNING_ORGANIZATION_ID\", Int64.Type}, {\"TRANSFER_OWNING_TP_TYPE\", Int64.Type}, {\"PLANNING_ORGANIZATION_ID\", Int64.Type}, {\"PLANNING_TP_TYPE\", Int64.Type}, {\"TRANSFER_PLANNING_TP_TYPE\", Int64.Type}, {\"TRANSACTION_MODE\", Int64.Type}, {\"TRANSACTION_GROUP_SEQ\", Int64.Type}, {\"TRANSACTION_BATCH_ID\", Int64.Type}, {\"TRANSACTION_BATCH_SEQ\", Int64.Type}, {\"INTRANSIT_ACCOUNT\", Int64.Type}, {\"FOB_POINT\", Int64.Type}, {\"EXPENSE_ACCOUNT_ID\", Int64.Type}, {\"SO_ISSUE_ACCOUNT_TYPE\", Int64.Type}, {\"MATERIAL_EXPENSE_ACCOUNT\", Int64.Type}})\r\nin\r\n  #\"Changed column type\";\r\nshared XXREP_MTL_MATERIAL_TRANSACTIONS = let\r\n  Source = Value.NativeQuery(Snowflake.Databases(\"mma12090.snowflakecomputing.com\",\"COMPUTE_REPORTING\",[Role=\"GLBMFGOPERATIONSROLE\"]){[Name=\"PROD_DB\"]}[Data], \"SELECT * FROM PROD_DB.APPS.XXREP_MTL_MATERIAL_TRANSACTIONS\", null, [EnableFolding=true]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each Date.IsInPreviousNDays([LAST_UPDATE_DATE], 730)),\r\n  #\"Filtered rows 1\" = Table.SelectRows(#\"Filtered rows\", each [ORGANIZATION_ID] = 944 or [ORGANIZATION_ID] = 3306)\r\nin\r\n  #\"Filtered rows 1\";\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"XXREP_MTL_MATERIAL_TRANSACTIONS","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"XXREP_MTL_MATERIAL_TRANSACTIONS.csv"},"attributes":[{"name":"TRANSACTION_ID","dataType":"double"},{"name":"LAST_UPDATE_DATE","dataType":"dateTime"},{"name":"LAST_UPDATED_BY","dataType":"double"},{"name":"CREATION_DATE","dataType":"dateTime"},{"name":"CREATED_BY","dataType":"double"},{"name":"LAST_UPDATE_LOGIN","dataType":"double"},{"name":"REQUEST_ID","dataType":"double"},{"name":"PROGRAM_APPLICATION_ID","dataType":"double"},{"name":"PROGRAM_ID","dataType":"double"},{"name":"PROGRAM_UPDATE_DATE","dataType":"dateTime"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"REVISION","dataType":"string"},{"name":"ORGANIZATION_ID","dataType":"double"},{"name":"SUBINVENTORY_CODE","dataType":"string"},{"name":"LOCATOR_ID","dataType":"double"},{"name":"TRANSACTION_TYPE_ID","dataType":"double"},{"name":"TRANSACTION_ACTION_ID","dataType":"double"},{"name":"TRANSACTION_SOURCE_TYPE_ID","dataType":"double"},{"name":"TRANSACTION_SOURCE_ID","dataType":"double"},{"name":"TRANSACTION_SOURCE_NAME","dataType":"string"},{"name":"TRANSACTION_QUANTITY","dataType":"double"},{"name":"TRANSACTION_UOM","dataType":"string"},{"name":"PRIMARY_QUANTITY","dataType":"double"},{"name":"TRANSACTION_DATE","dataType":"dateTime"},{"name":"VARIANCE_AMOUNT","dataType":"double"},{"name":"ACCT_PERIOD_ID","dataType":"double"},{"name":"TRANSACTION_REFERENCE","dataType":"string"},{"name":"REASON_ID","dataType":"double"},{"name":"DISTRIBUTION_ACCOUNT_ID","dataType":"double"},{"name":"ENCUMBRANCE_ACCOUNT","dataType":"double"},{"name":"ENCUMBRANCE_AMOUNT","dataType":"double"},{"name":"COST_UPDATE_ID","dataType":"double"},{"name":"COSTED_FLAG","dataType":"string"},{"name":"TRANSACTION_GROUP_ID","dataType":"double"},{"name":"INVOICED_FLAG","dataType":"string"},{"name":"ACTUAL_COST","dataType":"double"},{"name":"TRANSACTION_COST","dataType":"double"},{"name":"PRIOR_COST","dataType":"double"},{"name":"NEW_COST","dataType":"double"},{"name":"CURRENCY_CODE","dataType":"string"},{"name":"CURRENCY_CONVERSION_RATE","dataType":"double"},{"name":"CURRENCY_CONVERSION_TYPE","dataType":"string"},{"name":"CURRENCY_CONVERSION_DATE","dataType":"dateTime"},{"name":"USSGL_TRANSACTION_CODE","dataType":"string"},{"name":"QUANTITY_ADJUSTED","dataType":"double"},{"name":"EMPLOYEE_CODE","dataType":"string"},{"name":"DEPARTMENT_ID","dataType":"double"},{"name":"OPERATION_SEQ_NUM","dataType":"double"},{"name":"MASTER_SCHEDULE_UPDATE_CODE","dataType":"string"},{"name":"RECEIVING_DOCUMENT","dataType":"string"},{"name":"PICKING_LINE_ID","dataType":"double"},{"name":"TRX_SOURCE_LINE_ID","dataType":"double"},{"name":"TRX_SOURCE_DELIVERY_ID","dataType":"double"},{"name":"REPETITIVE_LINE_ID","dataType":"double"},{"name":"PHYSICAL_ADJUSTMENT_ID","dataType":"double"},{"name":"CYCLE_COUNT_ID","dataType":"double"},{"name":"RMA_LINE_ID","dataType":"double"},{"name":"TRANSFER_TRANSACTION_ID","dataType":"double"},{"name":"TRANSACTION_SET_ID","dataType":"double"},{"name":"RCV_TRANSACTION_ID","dataType":"double"},{"name":"MOVE_TRANSACTION_ID","dataType":"double"},{"name":"COMPLETION_TRANSACTION_ID","dataType":"double"},{"name":"SHORTAGE_PROCESS_CODE","dataType":"double"},{"name":"SOURCE_CODE","dataType":"string"},{"name":"SOURCE_LINE_ID","dataType":"double"},{"name":"VENDOR_LOT_NUMBER","dataType":"string"},{"name":"TRANSFER_ORGANIZATION_ID","dataType":"double"},{"name":"TRANSFER_SUBINVENTORY","dataType":"string"},{"name":"TRANSFER_LOCATOR_ID","dataType":"double"},{"name":"SHIPMENT_NUMBER","dataType":"string"},{"name":"TRANSFER_COST","dataType":"double"},{"name":"TRANSPORTATION_DIST_ACCOUNT","dataType":"double"},{"name":"TRANSPORTATION_COST","dataType":"double"},{"name":"TRANSFER_COST_DIST_ACCOUNT","dataType":"double"},{"name":"WAYBILL_AIRBILL","dataType":"string"},{"name":"FREIGHT_CODE","dataType":"string"},{"name":"NUMBER_OF_CONTAINERS","dataType":"double"},{"name":"VALUE_CHANGE","dataType":"double"},{"name":"PERCENTAGE_CHANGE","dataType":"double"},{"name":"ATTRIBUTE_CATEGORY","dataType":"string"},{"name":"ATTRIBUTE1","dataType":"string"},{"name":"ATTRIBUTE2","dataType":"string"},{"name":"ATTRIBUTE3","dataType":"string"},{"name":"ATTRIBUTE4","dataType":"string"},{"name":"ATTRIBUTE5","dataType":"string"},{"name":"ATTRIBUTE6","dataType":"string"},{"name":"ATTRIBUTE7","dataType":"string"},{"name":"ATTRIBUTE8","dataType":"string"},{"name":"ATTRIBUTE9","dataType":"string"},{"name":"ATTRIBUTE10","dataType":"string"},{"name":"ATTRIBUTE11","dataType":"string"},{"name":"ATTRIBUTE12","dataType":"string"},{"name":"ATTRIBUTE13","dataType":"string"},{"name":"ATTRIBUTE14","dataType":"string"},{"name":"ATTRIBUTE15","dataType":"string"},{"name":"MOVEMENT_ID","dataType":"double"},{"name":"TASK_ID","dataType":"double"},{"name":"TO_TASK_ID","dataType":"double"},{"name":"PROJECT_ID","dataType":"double"},{"name":"TO_PROJECT_ID","dataType":"double"},{"name":"SOURCE_PROJECT_ID","dataType":"double"},{"name":"PA_EXPENDITURE_ORG_ID","dataType":"double"},{"name":"SOURCE_TASK_ID","dataType":"double"},{"name":"EXPENDITURE_TYPE","dataType":"string"},{"name":"ERROR_CODE","dataType":"string"},{"name":"ERROR_EXPLANATION","dataType":"string"},{"name":"PRIOR_COSTED_QUANTITY","dataType":"double"},{"name":"TRANSFER_PRIOR_COSTED_QUANTITY","dataType":"double"},{"name":"FINAL_COMPLETION_FLAG","dataType":"string"},{"name":"PM_COST_COLLECTED","dataType":"string"},{"name":"PM_COST_COLLECTOR_GROUP_ID","dataType":"double"},{"name":"SHIPMENT_COSTED","dataType":"string"},{"name":"TRANSFER_PERCENTAGE","dataType":"double"},{"name":"MATERIAL_ACCOUNT","dataType":"double"},{"name":"MATERIAL_OVERHEAD_ACCOUNT","dataType":"double"},{"name":"RESOURCE_ACCOUNT","dataType":"double"},{"name":"OUTSIDE_PROCESSING_ACCOUNT","dataType":"double"},{"name":"OVERHEAD_ACCOUNT","dataType":"double"},{"name":"COST_GROUP_ID","dataType":"double"},{"name":"TRANSFER_COST_GROUP_ID","dataType":"double"},{"name":"FLOW_SCHEDULE","dataType":"string"},{"name":"QA_COLLECTION_ID","dataType":"double"},{"name":"OVERCOMPLETION_TRANSACTION_QTY","dataType":"double"},{"name":"OVERCOMPLETION_PRIMARY_QTY","dataType":"double"},{"name":"OVERCOMPLETION_TRANSACTION_ID","dataType":"double"},{"name":"MVT_STAT_STATUS","dataType":"string"},{"name":"COMMON_BOM_SEQ_ID","dataType":"double"},{"name":"COMMON_ROUTING_SEQ_ID","dataType":"double"},{"name":"ORG_COST_GROUP_ID","dataType":"double"},{"name":"COST_TYPE_ID","dataType":"double"},{"name":"PERIODIC_PRIMARY_QUANTITY","dataType":"double"},{"name":"MOVE_ORDER_LINE_ID","dataType":"double"},{"name":"TASK_GROUP_ID","dataType":"double"},{"name":"PICK_SLIP_NUMBER","dataType":"double"},{"name":"LPN_ID","dataType":"double"},{"name":"TRANSFER_LPN_ID","dataType":"double"},{"name":"PICK_STRATEGY_ID","dataType":"double"},{"name":"PICK_RULE_ID","dataType":"double"},{"name":"PUT_AWAY_STRATEGY_ID","dataType":"double"},{"name":"PUT_AWAY_RULE_ID","dataType":"double"},{"name":"CONTENT_LPN_ID","dataType":"double"},{"name":"PICK_SLIP_DATE","dataType":"dateTime"},{"name":"COST_CATEGORY_ID","dataType":"double"},{"name":"ORGANIZATION_TYPE","dataType":"double"},{"name":"TRANSFER_ORGANIZATION_TYPE","dataType":"double"},{"name":"OWNING_ORGANIZATION_ID","dataType":"double"},{"name":"OWNING_TP_TYPE","dataType":"double"},{"name":"XFR_OWNING_ORGANIZATION_ID","dataType":"double"},{"name":"TRANSFER_OWNING_TP_TYPE","dataType":"double"},{"name":"PLANNING_ORGANIZATION_ID","dataType":"double"},{"name":"PLANNING_TP_TYPE","dataType":"double"},{"name":"XFR_PLANNING_ORGANIZATION_ID","dataType":"double"},{"name":"TRANSFER_PLANNING_TP_TYPE","dataType":"double"},{"name":"SECONDARY_UOM_CODE","dataType":"string"},{"name":"SECONDARY_TRANSACTION_QUANTITY","dataType":"double"},{"name":"TRANSACTION_GROUP_SEQ","dataType":"double"},{"name":"SHIP_TO_LOCATION_ID","dataType":"double"},{"name":"RESERVATION_ID","dataType":"double"},{"name":"TRANSACTION_MODE","dataType":"double"},{"name":"TRANSACTION_BATCH_ID","dataType":"double"},{"name":"TRANSACTION_BATCH_SEQ","dataType":"double"},{"name":"INTRANSIT_ACCOUNT","dataType":"double"},{"name":"FOB_POINT","dataType":"double"},{"name":"PARENT_TRANSACTION_ID","dataType":"double"},{"name":"LOGICAL_TRX_TYPE_CODE","dataType":"double"},{"name":"TRX_FLOW_HEADER_ID","dataType":"double"},{"name":"LOGICAL_TRANSACTIONS_CREATED","dataType":"double"},{"name":"LOGICAL_TRANSACTION","dataType":"double"},{"name":"INTERCOMPANY_COST","dataType":"double"},{"name":"INTERCOMPANY_PRICING_OPTION","dataType":"double"},{"name":"INTERCOMPANY_CURRENCY_CODE","dataType":"string"},{"name":"ORIGINAL_TRANSACTION_TEMP_ID","dataType":"double"},{"name":"TRANSFER_PRICE","dataType":"double"},{"name":"EXPENSE_ACCOUNT_ID","dataType":"double"},{"name":"COGS_RECOGNITION_PERCENT","dataType":"double"},{"name":"SO_ISSUE_ACCOUNT_TYPE","dataType":"double"},{"name":"OPM_COSTED_FLAG","dataType":"string"},{"name":"MATERIAL_EXPENSE_ACCOUNT","dataType":"double"},{"name":"TRANSACTION_EXTRACTED","dataType":"string"},{"name":"XML_DOCUMENT_ID","dataType":"double"},{"name":"ITEM_ORG_KEY_ID","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-20T07:10:40.0582883+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/1d817554-c5aa-4eb4-aec4-91af03a617a7/XXREP_MTL_MATERIAL_TRANSACTIONS.csv?snapshot=2022-05-20T07%3A09%3A32.6422035Z"}]}]}