{"name":"Flow_Oracle_Shipping-Receiving","description":"Flow for shipping and receiving data.","version":"1.0","culture":"en-US","modifiedTime":"2022-03-06T15:30:57.6165135+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":true,"queriesMetadata":{"XXCOH_MP_RECEIPTS_VIEW":{"queryId":"eac8d9b5-7a0b-44fc-8abc-5cd889bc482b","queryName":"XXCOH_MP_RECEIPTS_VIEW","loadEnabled":true},"XXCOH_MP_RECEIPTS_VIEW (2)":{"queryId":"b3cb3761-7207-4eba-8536-9a77f49ba5ae","queryName":"XXCOH_MP_RECEIPTS_VIEW (2)"},"RangeStart":{"queryId":"3a2de5f5-6d10-4c89-857b-110531b7076d","queryName":"RangeStart"},"RangeEnd":{"queryId":"0deb781b-4e78-416a-986f-2cce6bc1c64f","queryName":"RangeEnd"}},"document":"section Section1;\r\n\r\nshared #\"XXCOH_MP_RECEIPTS_VIEW (2)\" = let\r\n    Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\"),\r\n    PROD_DB_Database = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n    APPS_Schema = PROD_DB_Database{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n    XXCOH_MP_RECEIPTS_VIEW_View = APPS_Schema{[Name = \"XXCOH_MP_RECEIPTS_VIEW\", Kind = \"View\"]}[Data],\r\n    #\"Filtered Rows\" = Table.SelectRows(XXCOH_MP_RECEIPTS_VIEW_View, each Date.IsInPreviousNDays([TRANSACTION_DATE], 670)),\r\n    #\"Changed column type\" = Table.TransformColumnTypes(#\"Filtered Rows\", {{\"RECEIPT_LINE_NUM\", Int64.Type}, {\"SOURCE_NUMBER\", Int64.Type}, {\"OPERATING_UNIT_ID\", Int64.Type}, {\"LEGAL_ENTITY_ID\", Int64.Type}, {\"FISCAL_PERIOD\", Int64.Type}, {\"FISCAL_QUARTER\", Int64.Type}, {\"FISCAL_YEAR\", Int64.Type}, {\"FISCAL_WEEK\", Int64.Type}, {\"PARENT_TRANSACTION_ID\", Int64.Type}, {\"TRANSACTION_ID\", Int64.Type}, {\"INV_TRANSACTION_ID\", Int64.Type}, {\"PO_HEADER_ID\", Int64.Type}, {\"PO_LINE_ID\", Int64.Type}, {\"PO_LINE_LOCATION_ID\", Int64.Type}, {\"PO_DISTRIBUTION_ID\", Int64.Type}, {\"REQUISITION_LINE_ID\", Int64.Type}, {\"SHIPMENT_HEADER_ID\", Int64.Type}, {\"SHIPMENT_LINE_ID\", Int64.Type}, {\"ITEM_ID\", Int64.Type}, {\"FROM_ORGANIZATION_ID\", Int64.Type}, {\"TO_ORGANIZATION_ID\", Int64.Type}, {\"OE_ORDER_HEADER_ID\", Int64.Type}, {\"OE_ORDER_LINE_ID\", Int64.Type}, {\"WIP_ENTITY_ID\", Int64.Type}, {\"UNIT_PRICE\", Currency.Type}, {\"ITEM_COST\", Currency.Type}, {\"ITEM_ADD_BACK_COST\", Currency.Type}, {\"MATERIAL_COST\", Currency.Type}, {\"RESOURCE_COST\", Currency.Type}, {\"MATERIAL_OVERHEAD_COST\", Currency.Type}, {\"OVERHEAD_COST\", Currency.Type}, {\"OUTSIDE_PROCESSING_COST\", Currency.Type}, {\"UNBURDENED_COST\", Currency.Type}, {\"WIP_OPERATION_SEQ_NUM\", Int64.Type}, {\"WIP_RESOURCE_SEQ_NUM\", Int64.Type}})\r\nin\r\n    #\"Changed column type\";\r\n\r\nshared XXCOH_MP_RECEIPTS_VIEW = let\r\n    Source = Value.NativeQuery(Snowflake.Databases(\"mma12090.snowflakecomputing.com\",\"COMPUTE_REPORTING\",[Role=\"GLBMFGOPERATIONSROLE\"]){[Name=\"PROD_DB\"]}[Data], \"SELECT *#(lf)FROM PROD_DB.APPS.XXCOH_MP_RECEIPTS_VIEW\", null, [EnableFolding=true]),\r\n    #\"Changed column type\" = Table.TransformColumnTypes(Source, {{\"RECEIPT_LINE_NUM\", Int64.Type}, {\"SOURCE_NUMBER\", Int64.Type}, {\"OPERATING_UNIT_ID\", Int64.Type}, {\"LEGAL_ENTITY_ID\", Int64.Type}, {\"FISCAL_PERIOD\", Int64.Type}, {\"FISCAL_QUARTER\", Int64.Type}, {\"FISCAL_YEAR\", Int64.Type}, {\"FISCAL_WEEK\", Int64.Type}, {\"PARENT_TRANSACTION_ID\", Int64.Type}, {\"TRANSACTION_ID\", Int64.Type}, {\"INV_TRANSACTION_ID\", Int64.Type}, {\"PO_HEADER_ID\", Int64.Type}, {\"PO_LINE_ID\", Int64.Type}, {\"PO_LINE_LOCATION_ID\", Int64.Type}, {\"PO_DISTRIBUTION_ID\", Int64.Type}, {\"REQUISITION_LINE_ID\", Int64.Type}, {\"SHIPMENT_HEADER_ID\", Int64.Type}, {\"SHIPMENT_LINE_ID\", Int64.Type}, {\"ITEM_ID\", Int64.Type}, {\"FROM_ORGANIZATION_ID\", Int64.Type}, {\"TO_ORGANIZATION_ID\", Int64.Type}, {\"OE_ORDER_HEADER_ID\", Int64.Type}, {\"OE_ORDER_LINE_ID\", Int64.Type}, {\"WIP_ENTITY_ID\", Int64.Type}, {\"UNIT_PRICE\", Currency.Type}, {\"ITEM_COST\", Currency.Type}, {\"ITEM_ADD_BACK_COST\", Currency.Type}, {\"MATERIAL_COST\", Currency.Type}, {\"RESOURCE_COST\", Currency.Type}, {\"MATERIAL_OVERHEAD_COST\", Currency.Type}, {\"OVERHEAD_COST\", Currency.Type}, {\"OUTSIDE_PROCESSING_COST\", Currency.Type}, {\"UNBURDENED_COST\", Currency.Type}, {\"WIP_OPERATION_SEQ_NUM\", Int64.Type}, {\"WIP_RESOURCE_SEQ_NUM\", Int64.Type}}),\r\n    #\"XXCOH_MP_RECEIPTS_VIEW-5452414E53414354494F4E5F44415445-autogenerated_for_incremental_refresh\" = Table.SelectRows(#\"Changed column type\", each DateTime.From([TRANSACTION_DATE]) >= RangeStart and DateTime.From([TRANSACTION_DATE]) < RangeEnd)\r\nin\r\n    #\"XXCOH_MP_RECEIPTS_VIEW-5452414E53414354494F4E5F44415445-autogenerated_for_incremental_refresh\";\r\n\r\nshared RangeStart = let RangeStart = #datetime(0001,01,01,00,00,00) meta [IsParameterQuery=true, List={}, Type=\"DateTime\", IsParameterQueryRequired=true, Description=\"autogenerated_for_incremental_refresh\"] in RangeStart;\r\n\r\nshared RangeEnd = let RangeEnd = #datetime(9999,12,31,23,59,59) meta [IsParameterQuery=true, List={}, Type=\"DateTime\", IsParameterQueryRequired=true, Description=\"autogenerated_for_incremental_refresh\"] in RangeEnd;\r\n\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"XXCOH_MP_RECEIPTS_VIEW","description":"","pbi:refreshPolicy":{"$type":"IncrementalRefreshPolicy","locationPattern":"XXCOH_MP_RECEIPTS_VIEW/part.csv","rollingWindowGranularity":"year","rollingWindowPeriods":6,"incrementalGranularity":"quarter","incrementalPeriods":5},"annotations":[{"name":"pbi:IncrementalRefreshDetectChangeAttribute"},{"name":"pbi:IncrementalRefreshFilterByAttribute","value":"TRANSACTION_DATE"}],"attributes":[{"name":"ASOF_DATE","dataType":"date"},{"name":"ASOF_DATE_DISP","dataType":"dateTime"},{"name":"RECEIPT_NUM","dataType":"string"},{"name":"RECEIPT_COMMENTS","dataType":"string"},{"name":"RECEIPT_LINE_NUM","dataType":"int64"},{"name":"SOURCE_DOCUMENT_CODE","dataType":"string"},{"name":"DESTINATION_TYPE_CODE","dataType":"string"},{"name":"COUNTRY_OF_ORIGIN_CODE","dataType":"string"},{"name":"TRANSACTION_DATE","dataType":"dateTime"},{"name":"TRANSACTION_TYPE","dataType":"string"},{"name":"USER_ENTERED_FLAG","dataType":"string"},{"name":"ITEM_NUMBER","dataType":"string"},{"name":"ITEM_DESCRIPTION","dataType":"string"},{"name":"ITEM_REVISION","dataType":"string"},{"name":"DAYS_LATE_RECEIPT_ALLOWED","dataType":"double"},{"name":"ORDER_NUMBER","dataType":"string"},{"name":"ORDER_TYPE","dataType":"string"},{"name":"SOURCE_NAME","dataType":"string"},{"name":"ALTERNATE_SOURCE_NAME","dataType":"string"},{"name":"VENDOR_INTERNAL","dataType":"string"},{"name":"INTERDIV","dataType":"string"},{"name":"SOURCE_NUMBER","dataType":"int64"},{"name":"LINE_NUMBER","dataType":"double"},{"name":"QUANTITY","dataType":"double"},{"name":"UNIT_OF_MEASURE","dataType":"string"},{"name":"PRIMARY_QUANTITY","dataType":"double"},{"name":"PRIMARY_UNIT_OF_MEASURE","dataType":"string"},{"name":"PO_SHIPMENT_NUMBER","dataType":"double"},{"name":"PO_SHIPMENT_QUANTITY","dataType":"double"},{"name":"ORDERED_QANTITY","dataType":"double"},{"name":"ORDERED_UNIT_OF_MEASURE","dataType":"string"},{"name":"UNIT_PRICE","dataType":"decimal"},{"name":"CURRENCY_CODE","dataType":"string"},{"name":"CURRENCY_CONVERSION_RATE","dataType":"double"},{"name":"OE_CURRENCY_CODE","dataType":"string"},{"name":"PO_CURRENCY_CODE","dataType":"string"},{"name":"RSH_CURRENCY_CODE","dataType":"string"},{"name":"ITEM_COST","dataType":"decimal"},{"name":"ITEM_ADD_BACK_COST","dataType":"decimal"},{"name":"MATERIAL_COST","dataType":"decimal"},{"name":"RESOURCE_COST","dataType":"decimal"},{"name":"MATERIAL_OVERHEAD_COST","dataType":"decimal"},{"name":"OVERHEAD_COST","dataType":"decimal"},{"name":"OUTSIDE_PROCESSING_COST","dataType":"decimal"},{"name":"UNBURDENED_COST","dataType":"decimal"},{"name":"NOTE_TO_RECEIVER","dataType":"string"},{"name":"DUE_DATE","dataType":"dateTime"},{"name":"PACKING_SLIP","dataType":"string"},{"name":"FREIGHT_CARRIER","dataType":"string"},{"name":"WAYBILL_AIRBILL_NUM","dataType":"string"},{"name":"NUM_OF_CONTAINERS","dataType":"double"},{"name":"SHIPPING_DATE","dataType":"dateTime"},{"name":"FOB","dataType":"string"},{"name":"INSPECTION_STATUS_CODE","dataType":"string"},{"name":"INSPECTON_QUALITY_CODE","dataType":"string"},{"name":"FROM_ORG_CODE","dataType":"string"},{"name":"FROM_OPERATING_UNIT","dataType":"string"},{"name":"FROM_FUNC_CURRENCY_CODE","dataType":"string"},{"name":"ROUTING_NAME","dataType":"string"},{"name":"REASON_CODE","dataType":"string"},{"name":"DESTINATION_CONTEXT","dataType":"string"},{"name":"SUBINVENTORY","dataType":"string"},{"name":"TRANSACTION_CREATION_DATE","dataType":"dateTime"},{"name":"DEFAULT_SUBINVENTORY","dataType":"string"},{"name":"CURRENT_LOCATION","dataType":"string"},{"name":"ORG_CODE","dataType":"string"},{"name":"OPERATING_UNIT","dataType":"string"},{"name":"OPERATING_UNIT_ID","dataType":"int64"},{"name":"LEGAL_ENTITY","dataType":"string"},{"name":"LEGAL_ENTITY_ID","dataType":"int64"},{"name":"FUNC_CURRENCY_CODE","dataType":"string"},{"name":"BUYER","dataType":"string"},{"name":"RECEIVER","dataType":"string"},{"name":"DELIVER_TO_PERSON","dataType":"string"},{"name":"DELIVER_TO_LOCATION","dataType":"string"},{"name":"FISCAL_PERIOD","dataType":"int64"},{"name":"FISCAL_QUARTER","dataType":"int64"},{"name":"FISCAL_YEAR","dataType":"int64"},{"name":"FISCAL_WEEK","dataType":"int64"},{"name":"TR_USD_RATE","dataType":"double"},{"name":"FC_USD_RATE","dataType":"double"},{"name":"WIP_ENTITY_NAME","dataType":"string"},{"name":"WIP_DESCRIPTION","dataType":"string"},{"name":"WIP_OPERATION_SEQ_NUM","dataType":"int64"},{"name":"WIP_RESOURCE_SEQ_NUM","dataType":"int64"},{"name":"QUANTITY_BILLED","dataType":"double"},{"name":"AMOUNT_BILLED","dataType":"double"},{"name":"PO_DESTINATION_TYPE_CODE","dataType":"string"},{"name":"PARENT_TRANSACTION_ID","dataType":"int64"},{"name":"TRANSACTION_ID","dataType":"int64"},{"name":"INV_TRANSACTION_ID","dataType":"int64"},{"name":"PO_HEADER_ID","dataType":"int64"},{"name":"PO_LINE_ID","dataType":"int64"},{"name":"PO_LINE_LOCATION_ID","dataType":"int64"},{"name":"PO_DISTRIBUTION_ID","dataType":"int64"},{"name":"REQUISITION_LINE_ID","dataType":"int64"},{"name":"SHIPMENT_HEADER_ID","dataType":"int64"},{"name":"SHIPMENT_LINE_ID","dataType":"int64"},{"name":"ITEM_ID","dataType":"int64"},{"name":"FROM_ORGANIZATION_ID","dataType":"int64"},{"name":"TO_ORGANIZATION_ID","dataType":"int64"},{"name":"OE_ORDER_HEADER_ID","dataType":"int64"},{"name":"OE_ORDER_LINE_ID","dataType":"int64"},{"name":"WIP_ENTITY_ID","dataType":"int64"},{"name":"ROW_CREATION_DATE","dataType":"dateTime"}],"partitions":[{"name":"IncrementalRefreshPolicyPartition-2016","refreshTime":"2022-03-06T15:37:20.7308438+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/4977484e-ee39-4a2b-9af2-f9dd289a2eb9/XXCOH_MP_RECEIPTS_VIEW/part-2016.csv?snapshot=2022-03-06T15%3A37%3A20.6978144Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2016-01-01T00:00:00","end":"2017-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2017","refreshTime":"2022-03-06T15:38:04.852746+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/4977484e-ee39-4a2b-9af2-f9dd289a2eb9/XXCOH_MP_RECEIPTS_VIEW/part-2017.csv?snapshot=2022-03-06T15%3A38%3A04.8132264Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2017-01-01T00:00:00","end":"2018-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2018","refreshTime":"2022-03-06T15:38:54.40627+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/4977484e-ee39-4a2b-9af2-f9dd289a2eb9/XXCOH_MP_RECEIPTS_VIEW/part-2018.csv?snapshot=2022-03-06T15%3A38%3A54.3755132Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2018-01-01T00:00:00","end":"2019-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2019","refreshTime":"2022-03-06T15:38:02.2268487+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/4977484e-ee39-4a2b-9af2-f9dd289a2eb9/XXCOH_MP_RECEIPTS_VIEW/part-2019.csv?snapshot=2022-03-06T15%3A38%3A02.1757551Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2019-01-01T00:00:00","end":"2020-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2020","refreshTime":"2022-03-06T15:37:48.3762329+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/4977484e-ee39-4a2b-9af2-f9dd289a2eb9/XXCOH_MP_RECEIPTS_VIEW/part-2020.csv?snapshot=2022-03-06T15%3A37%3A48.3337808Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2020-01-01T00:00:00","end":"2021-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2021Q1","refreshTime":"2022-04-01T06:05:07.9581361+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/4977484e-ee39-4a2b-9af2-f9dd289a2eb9/XXCOH_MP_RECEIPTS_VIEW/part-2021Q1.csv?snapshot=2022-04-01T06%3A05%3A07.8909037Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2021-01-01T00:00:00","end":"2021-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2021Q2","refreshTime":"2022-06-13T06:05:14.0272534+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/4977484e-ee39-4a2b-9af2-f9dd289a2eb9/XXCOH_MP_RECEIPTS_VIEW/part-2021Q2.csv?snapshot=2022-06-13T06%3A05%3A14.0037332Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2021-04-01T00:00:00","end":"2021-07-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2021Q3","refreshTime":"2022-06-13T06:05:17.965877+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/4977484e-ee39-4a2b-9af2-f9dd289a2eb9/XXCOH_MP_RECEIPTS_VIEW/part-2021Q3.csv?snapshot=2022-06-13T06%3A05%3A17.9484643Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2021-07-01T00:00:00","end":"2021-10-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2021Q4","refreshTime":"2022-06-13T06:05:10.627382+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/4977484e-ee39-4a2b-9af2-f9dd289a2eb9/XXCOH_MP_RECEIPTS_VIEW/part-2021Q4.csv?snapshot=2022-06-13T06%3A05%3A10.5946940Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2021-10-01T00:00:00","end":"2022-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q1","refreshTime":"2022-06-13T06:05:13.5808095+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/4977484e-ee39-4a2b-9af2-f9dd289a2eb9/XXCOH_MP_RECEIPTS_VIEW/part-2022Q1.csv?snapshot=2022-06-13T06%3A05%3A13.5539929Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-01-01T00:00:00","end":"2022-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q2","refreshTime":"2022-06-13T06:05:06.2876921+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/4977484e-ee39-4a2b-9af2-f9dd289a2eb9/XXCOH_MP_RECEIPTS_VIEW/part-2022Q2.csv?snapshot=2022-06-13T06%3A05%3A06.2531935Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-01T00:00:00","end":"2022-07-01T00:00:00"}}]}]}