{"name":"Flow_Oracle_SupplierData","description":"Flow to load supplier data.","version":"1.0","culture":"en-US","modifiedTime":"2022-04-05T08:53:26.465283+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":true,"queriesMetadata":{"PO_APPROVED_SUPPLIER_LIST":{"queryId":"a667dc2f-0d8c-4d16-a791-8a74b09ef1c0","queryName":"PO_APPROVED_SUPPLIER_LIST","loadEnabled":true},"XX_VENDOR_DIM":{"queryId":"d593c2c7-fcbb-4e08-9784-23d6cc139049","queryName":"XX_VENDOR_DIM","loadEnabled":true},"PO_VENDORS":{"queryId":"7fe5bac4-58fb-4b84-ba66-391d2a807446","queryName":"PO_VENDORS","loadEnabled":true},"RangeStart":{"queryId":"3e28a52c-f97e-4fff-8b2a-b0de1a37df64","queryName":"RangeStart"},"RangeEnd":{"queryId":"c47937a0-e26d-417f-99c2-09d29503b744","queryName":"RangeEnd"}},"document":"section Section1;\r\n\r\nshared XX_VENDOR_DIM = let\r\n    Source = Value.NativeQuery(Snowflake.Databases(\"mma12090.snowflakecomputing.com\",\"COMPUTE_REPORTING\",[Role=\"GLBMFGOPERATIONSROLE\"]){[Name=\"PROD_DB\"]}[Data], \"SELECT *#(lf)FROM PROD_DB.XXDIMS.XX_VENDOR_DIM\", null, [EnableFolding=true]),\r\n    #\"Removed Other Columns\" = Table.SelectColumns(Source, {\"VENDOR_ID\", \"VENDOR\", \"VENDOR_TYPE\", \"VENDOR_NAME\", \"VENDOR_CATEGORY\", \"MASTER_VENDOR_NAME\"}),\r\n    #\"Changed column type\" = Table.TransformColumnTypes(#\"Removed Other Columns\", {{\"VENDOR_ID\", Int64.Type}}),\r\n    #\"Marked key columns\" = Table.AddKey(#\"Changed column type\", {\"VENDOR_ID\"}, false)\r\nin\r\n    #\"Marked key columns\";\r\n\r\nshared PO_APPROVED_SUPPLIER_LIST = let\r\n    Source = Value.NativeQuery(Snowflake.Databases(\"mma12090.snowflakecomputing.com\",\"COMPUTE_REPORTING\",[Role=\"GLBMFGOPERATIONSROLE\"]){[Name=\"PROD_DB\"]}[Data], \"SELECT *#(lf)FROM PROD_DB.PO.PO_APPROVED_SUPPLIER_LIST\", null, [EnableFolding=true]),\r\n    #\"Choose columns\" = Table.SelectColumns(Source, {\"ASL_ID\", \"USING_ORGANIZATION_ID\", \"OWNING_ORGANIZATION_ID\", \"VENDOR_BUSINESS_TYPE\", \"ASL_STATUS_ID\", \"LAST_UPDATE_DATE\", \"CREATION_DATE\", \"MANUFACTURER_ID\", \"VENDOR_ID\", \"ITEM_ID\", \"CATEGORY_ID\", \"VENDOR_SITE_ID\", \"PRIMARY_VENDOR_ITEM\", \"MANUFACTURER_ASL_ID\", \"REVIEW_BY_DATE\", \"COMMENTS\", \"REQUEST_ID\", \"PROGRAM_APPLICATION_ID\", \"PROGRAM_ID\", \"PROGRAM_UPDATE_DATE\", \"DISABLE_FLAG\", \"IP_CATEGORY_ID\", \"LAST_UPDATED_PROGRAM\"}),\r\n    #\"Changed column type\" = Table.TransformColumnTypes(#\"Choose columns\", {{\"ASL_ID\", Int64.Type}, {\"USING_ORGANIZATION_ID\", Int64.Type}, {\"OWNING_ORGANIZATION_ID\", Int64.Type}, {\"ASL_STATUS_ID\", Int64.Type}, {\"MANUFACTURER_ID\", Int64.Type}, {\"VENDOR_ID\", Int64.Type}, {\"ITEM_ID\", Int64.Type}, {\"CATEGORY_ID\", Int64.Type}, {\"VENDOR_SITE_ID\", Int64.Type}, {\"MANUFACTURER_ASL_ID\", Int64.Type}, {\"REQUEST_ID\", Int64.Type}, {\"PROGRAM_APPLICATION_ID\", Int64.Type}, {\"PROGRAM_ID\", Int64.Type}, {\"IP_CATEGORY_ID\", Int64.Type}}),\r\n    #\"PO_APPROVED_SUPPLIER_LIST-4C4153545F5550444154455F44415445-autogenerated_for_incremental_refresh\" = Table.SelectRows(#\"Changed column type\", each DateTime.From([LAST_UPDATE_DATE]) >= RangeStart and DateTime.From([LAST_UPDATE_DATE]) < RangeEnd)\r\nin\r\n    #\"PO_APPROVED_SUPPLIER_LIST-4C4153545F5550444154455F44415445-autogenerated_for_incremental_refresh\";\r\n\r\nshared PO_VENDORS = let\r\n    Source = Value.NativeQuery(Snowflake.Databases(\"mma12090.snowflakecomputing.com\",\"COMPUTE_REPORTING\",[Role=\"GLBMFGOPERATIONSROLE\"]){[Name=\"PROD_DB\"]}[Data], \"SELECT *#(lf)FROM PROD_DB.APPS.PO_VENDORS\", null, [EnableFolding=true]),\r\n    #\"Removed Other Columns\" = Table.SelectColumns(Source, {\"VENDOR_ID\", \"LAST_UPDATE_DATE\", \"VENDOR_NAME\", \"VENDOR_NAME_ALT\", \"SEGMENT1\", \"SUMMARY_FLAG\", \"ENABLED_FLAG\", \"CREATION_DATE\", \"VENDOR_TYPE_LOOKUP_CODE\", \"CUSTOMER_NUM\", \"ONE_TIME_FLAG\", \"PARENT_VENDOR_ID\", \"ORGANIZATION_TYPE_LOOKUP_CODE\", \"START_DATE_ACTIVE\", \"END_DATE_ACTIVE\", \"MINORITY_GROUP_LOOKUP_CODE\", \"SMALL_BUSINESS_FLAG\", \"STANDARD_INDUSTRY_CLASS\", \"INSPECTION_REQUIRED_FLAG\", \"RECEIPT_REQUIRED_FLAG\", \"VAT_REGISTRATION_NUM\", \"TAX_REPORTING_NAME\", \"PARTY_ID\", \"PARENT_PARTY_ID\", \"NI_NUMBER\", \"PARTY_NUMBER\"}),\r\n    #\"PO_VENDORS-4C4153545F5550444154455F44415445-autogenerated_for_incremental_refresh\" = Table.SelectRows(#\"Removed Other Columns\", each DateTime.From([LAST_UPDATE_DATE]) >= RangeStart and DateTime.From([LAST_UPDATE_DATE]) < RangeEnd)\r\nin\r\n    #\"PO_VENDORS-4C4153545F5550444154455F44415445-autogenerated_for_incremental_refresh\";\r\n\r\nshared RangeStart = let RangeStart = #datetime(0001,01,01,00,00,00) meta [IsParameterQuery=true, List={}, Type=\"DateTime\", IsParameterQueryRequired=true, Description=\"autogenerated_for_incremental_refresh\"] in RangeStart;\r\n\r\nshared RangeEnd = let RangeEnd = #datetime(9999,12,31,23,59,59) meta [IsParameterQuery=true, List={}, Type=\"DateTime\", IsParameterQueryRequired=true, Description=\"autogenerated_for_incremental_refresh\"] in RangeEnd;\r\n\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"PO_APPROVED_SUPPLIER_LIST","description":"","pbi:refreshPolicy":{"$type":"IncrementalRefreshPolicy","locationPattern":"PO_APPROVED_SUPPLIER_LIST/part.csv","rollingWindowGranularity":"year","rollingWindowPeriods":15,"incrementalGranularity":"month","incrementalPeriods":6},"annotations":[{"name":"pbi:IncrementalRefreshDetectChangeAttribute"},{"name":"pbi:IncrementalRefreshFilterByAttribute","value":"LAST_UPDATE_DATE"}],"attributes":[{"name":"ASL_ID","dataType":"int64"},{"name":"USING_ORGANIZATION_ID","dataType":"int64"},{"name":"OWNING_ORGANIZATION_ID","dataType":"int64"},{"name":"VENDOR_BUSINESS_TYPE","dataType":"string"},{"name":"ASL_STATUS_ID","dataType":"int64"},{"name":"LAST_UPDATE_DATE","dataType":"dateTime"},{"name":"CREATION_DATE","dataType":"dateTime"},{"name":"MANUFACTURER_ID","dataType":"int64"},{"name":"VENDOR_ID","dataType":"int64"},{"name":"ITEM_ID","dataType":"int64"},{"name":"CATEGORY_ID","dataType":"int64"},{"name":"VENDOR_SITE_ID","dataType":"int64"},{"name":"PRIMARY_VENDOR_ITEM","dataType":"string"},{"name":"MANUFACTURER_ASL_ID","dataType":"int64"},{"name":"REVIEW_BY_DATE","dataType":"dateTime"},{"name":"COMMENTS","dataType":"string"},{"name":"REQUEST_ID","dataType":"int64"},{"name":"PROGRAM_APPLICATION_ID","dataType":"int64"},{"name":"PROGRAM_ID","dataType":"int64"},{"name":"PROGRAM_UPDATE_DATE","dataType":"dateTime"},{"name":"DISABLE_FLAG","dataType":"string"},{"name":"IP_CATEGORY_ID","dataType":"int64"},{"name":"LAST_UPDATED_PROGRAM","dataType":"string"}],"partitions":[{"name":"IncrementalRefreshPolicyPartition-2007","refreshTime":"2022-04-04T15:19:44.5405111+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/7e24304b-8c84-47a8-a94d-57be002b7b43/PO_APPROVED_SUPPLIER_LIST/part-2007.csv?snapshot=2022-04-04T15%3A19%3A44.5075826Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2007-01-01T00:00:00","end":"2008-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2008","refreshTime":"2022-04-04T15:19:41.8335722+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/7e24304b-8c84-47a8-a94d-57be002b7b43/PO_APPROVED_SUPPLIER_LIST/part-2008.csv?snapshot=2022-04-04T15%3A19%3A41.8081172Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2008-01-01T00:00:00","end":"2009-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2009","refreshTime":"2022-04-04T15:19:44.1945111+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/7e24304b-8c84-47a8-a94d-57be002b7b43/PO_APPROVED_SUPPLIER_LIST/part-2009.csv?snapshot=2022-04-04T15%3A19%3A44.1737727Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2009-01-01T00:00:00","end":"2010-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2010","refreshTime":"2022-04-04T15:19:44.5561176+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/7e24304b-8c84-47a8-a94d-57be002b7b43/PO_APPROVED_SUPPLIER_LIST/part-2010.csv?snapshot=2022-04-04T15%3A19%3A44.5365662Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2010-01-01T00:00:00","end":"2011-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2011","refreshTime":"2022-04-04T15:19:41.536673+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/7e24304b-8c84-47a8-a94d-57be002b7b43/PO_APPROVED_SUPPLIER_LIST/part-2011.csv?snapshot=2022-04-04T15%3A19%3A41.5102869Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2011-01-01T00:00:00","end":"2012-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2012","refreshTime":"2022-04-04T15:19:42.4116656+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/7e24304b-8c84-47a8-a94d-57be002b7b43/PO_APPROVED_SUPPLIER_LIST/part-2012.csv?snapshot=2022-04-04T15%3A19%3A42.3807920Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2012-01-01T00:00:00","end":"2013-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2013","refreshTime":"2022-04-04T15:19:43.6463797+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/7e24304b-8c84-47a8-a94d-57be002b7b43/PO_APPROVED_SUPPLIER_LIST/part-2013.csv?snapshot=2022-04-04T15%3A19%3A43.6290822Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2013-01-01T00:00:00","end":"2014-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2014","refreshTime":"2022-04-04T15:19:43.5525918+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/7e24304b-8c84-47a8-a94d-57be002b7b43/PO_APPROVED_SUPPLIER_LIST/part-2014.csv?snapshot=2022-04-04T15%3A19%3A43.5251414Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2014-01-01T00:00:00","end":"2015-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2015","refreshTime":"2022-04-04T15:19:44.1619975+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/7e24304b-8c84-47a8-a94d-57be002b7b43/PO_APPROVED_SUPPLIER_LIST/part-2015.csv?snapshot=2022-04-04T15%3A19%3A44.1287987Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2015-01-01T00:00:00","end":"2016-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2016","refreshTime":"2022-04-04T15:19:43.5057849+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/7e24304b-8c84-47a8-a94d-57be002b7b43/PO_APPROVED_SUPPLIER_LIST/part-2016.csv?snapshot=2022-04-04T15%3A19%3A43.4801669Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2016-01-01T00:00:00","end":"2017-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2017","refreshTime":"2022-04-04T15:19:44.3373394+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/7e24304b-8c84-47a8-a94d-57be002b7b43/PO_APPROVED_SUPPLIER_LIST/part-2017.csv?snapshot=2022-04-04T15%3A19%3A44.3156922Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2017-01-01T00:00:00","end":"2018-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2018","refreshTime":"2022-04-04T15:19:44.2869678+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/7e24304b-8c84-47a8-a94d-57be002b7b43/PO_APPROVED_SUPPLIER_LIST/part-2018.csv?snapshot=2022-04-04T15%3A19%3A44.2667196Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2018-01-01T00:00:00","end":"2019-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2019","refreshTime":"2022-04-04T15:19:44.2557203+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/7e24304b-8c84-47a8-a94d-57be002b7b43/PO_APPROVED_SUPPLIER_LIST/part-2019.csv?snapshot=2022-04-04T15%3A19%3A44.2297402Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2019-01-01T00:00:00","end":"2020-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2020","refreshTime":"2022-04-04T15:19:44.5092358+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/7e24304b-8c84-47a8-a94d-57be002b7b43/PO_APPROVED_SUPPLIER_LIST/part-2020.csv?snapshot=2022-04-04T15%3A19%3A44.4885935Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2020-01-01T00:00:00","end":"2021-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2021","refreshTime":"2022-06-01T06:01:48.9742776+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/7e24304b-8c84-47a8-a94d-57be002b7b43/PO_APPROVED_SUPPLIER_LIST/part-2021.csv?snapshot=2022-06-02T06%3A06%3A51.7384420Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2021-01-01T00:00:00","end":"2022-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q101","refreshTime":"2022-06-13T06:01:55.2172843+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/7e24304b-8c84-47a8-a94d-57be002b7b43/PO_APPROVED_SUPPLIER_LIST/part-2022Q101.csv?snapshot=2022-06-13T06%3A01%3A53.1766747Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-01-01T00:00:00","end":"2022-02-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q102","refreshTime":"2022-06-13T06:01:47.1917611+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/7e24304b-8c84-47a8-a94d-57be002b7b43/PO_APPROVED_SUPPLIER_LIST/part-2022Q102.csv?snapshot=2022-06-13T06%3A01%3A46.4055695Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-02-01T00:00:00","end":"2022-03-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q103","refreshTime":"2022-06-13T06:01:52.6704428+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/7e24304b-8c84-47a8-a94d-57be002b7b43/PO_APPROVED_SUPPLIER_LIST/part-2022Q103.csv?snapshot=2022-06-13T06%3A01%3A49.6936786Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-03-01T00:00:00","end":"2022-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q204","refreshTime":"2022-06-13T06:01:50.4360354+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/7e24304b-8c84-47a8-a94d-57be002b7b43/PO_APPROVED_SUPPLIER_LIST/part-2022Q204.csv?snapshot=2022-06-13T06%3A01%3A48.3784349Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-01T00:00:00","end":"2022-05-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q205","refreshTime":"2022-06-13T06:01:54.2016821+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/7e24304b-8c84-47a8-a94d-57be002b7b43/PO_APPROVED_SUPPLIER_LIST/part-2022Q205.csv?snapshot=2022-06-13T06%3A01%3A52.6829588Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-05-01T00:00:00","end":"2022-06-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q206","refreshTime":"2022-06-13T06:02:22.0307562+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/7e24304b-8c84-47a8-a94d-57be002b7b43/PO_APPROVED_SUPPLIER_LIST/part-2022Q206.csv?snapshot=2022-06-13T06%3A02%3A21.9531213Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-06-01T00:00:00","end":"2022-07-01T00:00:00"}}]},{"$type":"LocalEntity","name":"XX_VENDOR_DIM","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"XX_VENDOR_DIM.csv"},"attributes":[{"name":"VENDOR_ID","dataType":"int64"},{"name":"VENDOR","dataType":"string"},{"name":"VENDOR_TYPE","dataType":"string"},{"name":"VENDOR_NAME","dataType":"string"},{"name":"VENDOR_CATEGORY","dataType":"string"},{"name":"MASTER_VENDOR_NAME","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T06:01:36.3379426+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/7e24304b-8c84-47a8-a94d-57be002b7b43/XX_VENDOR_DIM.csv?snapshot=2022-06-13T06%3A01%3A34.6853118Z"}]},{"$type":"LocalEntity","name":"PO_VENDORS","description":"","pbi:refreshPolicy":{"$type":"IncrementalRefreshPolicy","locationPattern":"PO_VENDORS/part.csv","rollingWindowGranularity":"year","rollingWindowPeriods":20,"incrementalGranularity":"month","incrementalPeriods":6},"annotations":[{"name":"pbi:IncrementalRefreshDetectChangeAttribute"},{"name":"pbi:IncrementalRefreshFilterByAttribute","value":"LAST_UPDATE_DATE"}],"attributes":[{"name":"VENDOR_ID","dataType":"double"},{"name":"LAST_UPDATE_DATE","dataType":"dateTime"},{"name":"VENDOR_NAME","dataType":"string"},{"name":"VENDOR_NAME_ALT","dataType":"string"},{"name":"SEGMENT1","dataType":"string"},{"name":"SUMMARY_FLAG","dataType":"string"},{"name":"ENABLED_FLAG","dataType":"string"},{"name":"CREATION_DATE","dataType":"dateTime"},{"name":"VENDOR_TYPE_LOOKUP_CODE","dataType":"string"},{"name":"CUSTOMER_NUM","dataType":"string"},{"name":"ONE_TIME_FLAG","dataType":"string"},{"name":"PARENT_VENDOR_ID","dataType":"double"},{"name":"ORGANIZATION_TYPE_LOOKUP_CODE","dataType":"string"},{"name":"START_DATE_ACTIVE","dataType":"dateTime"},{"name":"END_DATE_ACTIVE","dataType":"dateTime"},{"name":"MINORITY_GROUP_LOOKUP_CODE","dataType":"string"},{"name":"SMALL_BUSINESS_FLAG","dataType":"string"},{"name":"STANDARD_INDUSTRY_CLASS","dataType":"string"},{"name":"INSPECTION_REQUIRED_FLAG","dataType":"string"},{"name":"RECEIPT_REQUIRED_FLAG","dataType":"string"},{"name":"VAT_REGISTRATION_NUM","dataType":"string"},{"name":"TAX_REPORTING_NAME","dataType":"string"},{"name":"PARTY_ID","dataType":"double"},{"name":"PARENT_PARTY_ID","dataType":"double"},{"name":"NI_NUMBER","dataType":"string"},{"name":"PARTY_NUMBER","dataType":"string"}],"partitions":[{"name":"IncrementalRefreshPolicyPartition-2002","refreshTime":"2022-04-05T08:54:04.024804+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/7e24304b-8c84-47a8-a94d-57be002b7b43/PO_VENDORS/part-2002.csv?snapshot=2022-04-05T08%3A54%3A03.9780793Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2002-01-01T00:00:00","end":"2003-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2003","refreshTime":"2022-04-05T08:54:04.415405+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/7e24304b-8c84-47a8-a94d-57be002b7b43/PO_VENDORS/part-2003.csv?snapshot=2022-04-05T08%3A54%3A04.3758530Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2003-01-01T00:00:00","end":"2004-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2004","refreshTime":"2022-04-05T08:54:03.7903896+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/7e24304b-8c84-47a8-a94d-57be002b7b43/PO_VENDORS/part-2004.csv?snapshot=2022-04-05T08%3A54%3A03.7632011Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2004-01-01T00:00:00","end":"2005-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2005","refreshTime":"2022-04-05T08:54:03.6653774+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/7e24304b-8c84-47a8-a94d-57be002b7b43/PO_VENDORS/part-2005.csv?snapshot=2022-04-05T08%3A54%3A03.6452681Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2005-01-01T00:00:00","end":"2006-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2006","refreshTime":"2022-04-05T08:54:04.6444229+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/7e24304b-8c84-47a8-a94d-57be002b7b43/PO_VENDORS/part-2006.csv?snapshot=2022-04-05T08%3A54%3A04.6147177Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2006-01-01T00:00:00","end":"2007-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2007","refreshTime":"2022-04-05T08:54:05.1287942+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/7e24304b-8c84-47a8-a94d-57be002b7b43/PO_VENDORS/part-2007.csv?snapshot=2022-04-05T08%3A54%3A05.1054741Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2007-01-01T00:00:00","end":"2008-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2008","refreshTime":"2022-04-05T08:54:04.024804+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/7e24304b-8c84-47a8-a94d-57be002b7b43/PO_VENDORS/part-2008.csv?snapshot=2022-04-05T08%3A54%3A03.9930708Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2008-01-01T00:00:00","end":"2009-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2009","refreshTime":"2022-04-05T08:54:04.3997244+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/7e24304b-8c84-47a8-a94d-57be002b7b43/PO_VENDORS/part-2009.csv?snapshot=2022-04-05T08%3A54%3A04.3548658Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2009-01-01T00:00:00","end":"2010-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2010","refreshTime":"2022-04-05T08:54:05.1912615+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/7e24304b-8c84-47a8-a94d-57be002b7b43/PO_VENDORS/part-2010.csv?snapshot=2022-04-05T08%3A54%3A05.1793970Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2010-01-01T00:00:00","end":"2011-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2011","refreshTime":"2022-04-05T08:54:05.2537949+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/7e24304b-8c84-47a8-a94d-57be002b7b43/PO_VENDORS/part-2011.csv?snapshot=2022-04-05T08%3A54%3A05.2333669Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2011-01-01T00:00:00","end":"2012-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2012","refreshTime":"2022-04-05T08:54:04.5872182+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/7e24304b-8c84-47a8-a94d-57be002b7b43/PO_VENDORS/part-2012.csv?snapshot=2022-04-05T08%3A54%3A04.5687439Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2012-01-01T00:00:00","end":"2013-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2013","refreshTime":"2022-04-05T08:54:05.238151+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/7e24304b-8c84-47a8-a94d-57be002b7b43/PO_VENDORS/part-2013.csv?snapshot=2022-04-05T08%3A54%3A05.2093798Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2013-01-01T00:00:00","end":"2014-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2014","refreshTime":"2022-04-05T08:54:04.0715968+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/7e24304b-8c84-47a8-a94d-57be002b7b43/PO_VENDORS/part-2014.csv?snapshot=2022-04-05T08%3A54%3A04.0040645Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2014-01-01T00:00:00","end":"2015-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2015","refreshTime":"2022-04-05T08:54:05.2225058+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/7e24304b-8c84-47a8-a94d-57be002b7b43/PO_VENDORS/part-2015.csv?snapshot=2022-04-05T08%3A54%3A05.1793970Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2015-01-01T00:00:00","end":"2016-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2016","refreshTime":"2022-04-05T08:54:05.1759449+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/7e24304b-8c84-47a8-a94d-57be002b7b43/PO_VENDORS/part-2016.csv?snapshot=2022-04-05T08%3A54%3A05.1574096Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2016-01-01T00:00:00","end":"2017-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2017","refreshTime":"2022-04-05T08:54:04.3841386+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/7e24304b-8c84-47a8-a94d-57be002b7b43/PO_VENDORS/part-2017.csv?snapshot=2022-04-05T08%3A54%3A04.3548658Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2017-01-01T00:00:00","end":"2018-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2018","refreshTime":"2022-04-05T08:54:04.0872465+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/7e24304b-8c84-47a8-a94d-57be002b7b43/PO_VENDORS/part-2018.csv?snapshot=2022-04-05T08%3A54%3A04.0070627Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2018-01-01T00:00:00","end":"2019-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2019","refreshTime":"2022-04-05T08:54:04.3372152+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/7e24304b-8c84-47a8-a94d-57be002b7b43/PO_VENDORS/part-2019.csv?snapshot=2022-04-05T08%3A54%3A04.2998965Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2019-01-01T00:00:00","end":"2020-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2020","refreshTime":"2022-04-05T08:54:04.4934652+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/7e24304b-8c84-47a8-a94d-57be002b7b43/PO_VENDORS/part-2020.csv?snapshot=2022-04-05T08%3A54%3A04.4777953Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2020-01-01T00:00:00","end":"2021-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2021","refreshTime":"2022-06-01T06:04:45.3092568+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/7e24304b-8c84-47a8-a94d-57be002b7b43/PO_VENDORS/part-2021.csv?snapshot=2022-06-02T06%3A02%3A34.8322347Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2021-01-01T00:00:00","end":"2022-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q101","refreshTime":"2022-06-13T06:02:13.7917984+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/7e24304b-8c84-47a8-a94d-57be002b7b43/PO_VENDORS/part-2022Q101.csv?snapshot=2022-06-13T06%3A02%3A12.8973310Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-01-01T00:00:00","end":"2022-02-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q102","refreshTime":"2022-06-13T06:02:11.2605315+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/7e24304b-8c84-47a8-a94d-57be002b7b43/PO_VENDORS/part-2022Q102.csv?snapshot=2022-06-13T06%3A02%3A10.9874292Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-02-01T00:00:00","end":"2022-03-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q103","refreshTime":"2022-06-13T06:02:15.6609266+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/7e24304b-8c84-47a8-a94d-57be002b7b43/PO_VENDORS/part-2022Q103.csv?snapshot=2022-06-13T06%3A02%3A13.8607765Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-03-01T00:00:00","end":"2022-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q204","refreshTime":"2022-06-13T06:02:10.916786+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/7e24304b-8c84-47a8-a94d-57be002b7b43/PO_VENDORS/part-2022Q204.csv?snapshot=2022-06-13T06%3A02%3A07.3835024Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-01T00:00:00","end":"2022-05-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q205","refreshTime":"2022-06-13T06:02:07.1980104+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/7e24304b-8c84-47a8-a94d-57be002b7b43/PO_VENDORS/part-2022Q205.csv?snapshot=2022-06-13T06%3A02%3A07.0536922Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-05-01T00:00:00","end":"2022-06-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q206","refreshTime":"2022-06-13T06:02:07.5573937+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/7e24304b-8c84-47a8-a94d-57be002b7b43/PO_VENDORS/part-2022Q206.csv?snapshot=2022-06-13T06%3A02%3A07.2545766Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-06-01T00:00:00","end":"2022-07-01T00:00:00"}}]}]}