{"name":"Cumulus_Oracle_Data","description":"Oracle Work Orders resource transactions","version":"1.0","culture":"en-US","modifiedTime":"2022-03-28T20:05:27.7635863+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":true,"queriesMetadata":{"parStartDate":{"queryId":"e3410611-c40b-41a0-bbe4-b1b9514d01bb","queryName":"parStartDate"},"fx_ConvertToSK":{"queryId":"36480255-f548-468b-bb41-d9aaa742aa5b","queryName":"fx_ConvertToSK"},"ODBC_Client_Version":{"queryId":"6bf4c638-21f7-4852-ab00-fd7a4ee31d05","queryName":"ODBC_Client_Version"},"XXREP_BOM_DEPT_RESOURCE_V":{"queryId":"eca93884-0dfa-4c2a-bbb3-faf9bf4ccab0","queryName":"XXREP_BOM_DEPT_RESOURCE_V"},"Data Update Info":{"queryId":"339cfb73-b545-458b-a043-5cd216626b95","queryName":"Data Update Info"},"XXREP_WIP_DISCRETE_JOBS_V":{"queryId":"1265ad3f-de66-4a8b-9cc1-2b03c032cf89","queryName":"XXREP_WIP_DISCRETE_JOBS_V","loadEnabled":true},"XXREP_OM_OTD_V":{"queryId":"6a7ab262-6f29-4953-a2ef-cf8022cd5acc","queryName":"XXREP_OM_OTD_V","loadEnabled":true},"XXCOH_MS_SHIPMENT_VIEW":{"queryId":"ace6b8db-f6a9-4000-989e-137613d2a6c8","queryName":"XXCOH_MS_SHIPMENT_VIEW","loadEnabled":true},"XXREP_RESOURCE_TRAN_V":{"queryId":"ba37edc7-9838-4df3-bff6-00790440e4ad","queryName":"XXREP_RESOURCE_TRAN_V","loadEnabled":true},"XXREP_WW_OMTRX_DATAMART_V":{"queryId":"011d5071-8c1f-46fc-a4e6-4f8913b3c4c8","queryName":"XXREP_WW_OMTRX_DATAMART_V","loadEnabled":true},"RangeEnd":{"queryId":"8aeaebb2-ab60-4624-b685-23d84f2c4b19","queryName":"RangeEnd"},"RangeStart":{"queryId":"6b286869-dc55-4998-9200-bfab776dd06c","queryName":"RangeStart"}},"document":"section Section1;\r\n\r\nshared parStartDate = #datetime(2018, 12, 31, 0, 0, 0) meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type datetime];\r\n\r\nshared fx_ConvertToSK = let\r\n    Query = (irparams as datetime) => Date.Year(irparams)*10000 + Date.Month(irparams)*100 + Date.Day(irparams)\r\nin\r\n    Query;\r\n\r\nshared ODBC_Client_Version = let\r\n    Source = Value.NativeQuery(Snowflake.Databases(\"mma12090.snowflakecomputing.com\",\"COMPUTE_REPORTING\",[Role=\"GLBMFGOPERATIONSROLE\"]){[Name=\"PROD_DB\"]}[Data], \"SELECT CURRENT_CLIENT()\", null, [EnableFolding=true])\r\nin\r\n    Source;\r\n\r\nshared XXREP_BOM_DEPT_RESOURCE_V = let\r\n    Source = Value.NativeQuery(Snowflake.Databases(\"mma12090.snowflakecomputing.com\",\"COMPUTE_REPORTING\",[Role=\"GLBMFGOPERATIONSROLE\"]){[Name=\"PROD_DB\"]}[Data], \"SELECT *#(lf)FROM PROD_DB.APPS.XXREP_BOM_DEPT_RESOURCE_V\", null, [EnableFolding=true]),\r\n    #\"Choose columns\" = Table.SelectColumns(Source, {\"DEPARTMENT_ID\", \"DEPARTMENT_CODE\", \"DEPARTMENT_DESCRIPTION\"}),\r\n    #\"Removed duplicates\" = Table.Distinct(#\"Choose columns\", {\"DEPARTMENT_ID\"}),\r\n    #\"Replaced value\" = Table.ReplaceValue(#\"Removed duplicates\", null, \"No Description Available\", Replacer.ReplaceValue, {\"DEPARTMENT_DESCRIPTION\"})\r\nin\r\n    #\"Replaced value\";\r\n\r\nshared #\"Data Update Info\" = let\r\n    Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n    Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n    #\"Navigation 1\" = Navigation{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n    #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXREP_DATA_UPDATE_V\", Kind = \"View\"]}[Data],\r\n    #\"Filtered rows\" = Table.SelectRows(#\"Navigation 2\", each [TABLE_NAME] = \"WIP.WIP_TRANSACTIONS\")\r\nin\r\n    #\"Filtered rows\";\r\n\r\nshared XXREP_WIP_DISCRETE_JOBS_V = let\r\n    Source = Value.NativeQuery(Snowflake.Databases(\"mma12090.snowflakecomputing.com\",\"COMPUTE_REPORTING\",[Role=\"GLBMFGOPERATIONSROLE\"]){[Name=\"PROD_DB\"]}[Data], \"SELECT *FROM PROD_DB.APPS.XXREP_WIP_DISCRETE_JOBS_V\", null, [EnableFolding=true]),\r\n    #\"Filtered rows\" = Table.SelectRows(Source, each [LAST_UPDATE_DATE] > parStartDate),\r\n    #\"Choose columns\" = Table.SelectColumns(#\"Filtered rows\", {\"ORGANIZATION_ID\", \"WIP_ENTITY_ID\", \"WIPJOB_ORG_KEY_CODE\", \"WIPJOB_ORG_KEY_ID\", \"LAST_UPDATE_DATE\", \"CREATION_DATE\", \"PRIMARY_ITEM_ID\", \"CLASS_CODE\", \"START_QUANTITY\", \"QUANTITY_REMAINING\", \"QUANTITY_COMPLETED\", \"QUANTITY_SCRAPPED\", \"NET_QUANTITY\", \"LOT_NUMBER\", \"COMPLETION_SUBINVENTORY\", \"SCHEDULED_START_DATE\", \"DATE_RELEASED\", \"SCHEDULED_COMPLETION_DATE\", \"DATE_COMPLETED\", \"DATE_CLOSED\", \"DUE_DATE\", \"ENTITY_TYPE\", \"REQUESTED_START_DATE\", \"ACTUAL_START_DATE\", \"INVORG_CODE\", \"JOB_STATUS\", \"WIP_SUPPLY_TYPE\", \"JOB_NUMBER\", \"JOB_TYPE\", \"FIRST_UNIT_START_DATE\", \"FIRST_UNIT_COMPLETION_DATE\", \"LAST_UNIT_START_DATE\", \"LAST_UNIT_COMPLETION_DATE\", \"ITEM_NUMBER\", \"ITEM_ORG_KEY_ID\", \"ITEM_ORG_KEY_CODE\", \"ORG_TBU\"}),\r\n    #\"Changed column type\" = Table.TransformColumnTypes(#\"Choose columns\", {{\"ORGANIZATION_ID\", Int64.Type}, {\"WIP_ENTITY_ID\", Int64.Type}, {\"PRIMARY_ITEM_ID\", Int64.Type}, {\"SCHEDULED_START_DATE\", type date}, {\"DATE_RELEASED\", type date}, {\"SCHEDULED_COMPLETION_DATE\", type date}, {\"DUE_DATE\", type date}, {\"ENTITY_TYPE\", Int64.Type}, {\"REQUESTED_START_DATE\", type date}, {\"ACTUAL_START_DATE\", type date}, {\"FIRST_UNIT_START_DATE\", type date}, {\"FIRST_UNIT_COMPLETION_DATE\", type date}, {\"LAST_UNIT_START_DATE\", type date}, {\"LAST_UNIT_COMPLETION_DATE\", type date}}),\r\n    #\"Uppercased text\" = Table.TransformColumns(#\"Changed column type\", {{\"WIPJOB_ORG_KEY_CODE\", each Text.Upper(_), type text}}),\r\n    #\"Removed duplicates\" = Table.Distinct(#\"Uppercased text\", {\"WIPJOB_ORG_KEY_CODE\"})\r\nin\r\n    #\"Removed duplicates\";\r\n\r\nshared XXREP_OM_OTD_V = let\r\n    Source = Value.NativeQuery(Snowflake.Databases(\"mma12090.snowflakecomputing.com\",\"COMPUTE_REPORTING\",[Role=\"GLBMFGOPERATIONSROLE\"]){[Name=\"PROD_DB\"]}[Data], \"SELECT *FROM PROD_DB.APPS.XXREP_OM_OTD_V\", null, [EnableFolding=true]),\r\n    #\"Filtered rows\" = Table.SelectRows(Source, each [LAST_UPDATE_DATE] > parStartDate),\r\n    #\"Changed column type\" = Table.TransformColumnTypes(#\"Filtered rows\", {{\"LINE_ID\", Int64.Type}, {\"HEADER_ID\", Int64.Type}, {\"FISCAL_YEAR_HEADER_BOOKED\", Int64.Type}, {\"FISCAL_WEEK_HEADER_BOOKED\", Int64.Type}, {\"UNIT_SELLING_PRICE\", Currency.Type}, {\"ORDER_TYPE_ID\", Int64.Type}, {\"SHIP_FROM_ORG_ID\", Int64.Type}, {\"OPERATING_UNIT_ID\", Int64.Type}, {\"H_CREATED_BY_ID\", Int64.Type}, {\"EXTENDED_AMOUNT_USD\", Currency.Type}, {\"EXTENDED_AMOUNT\", Currency.Type}}),\r\n    #\"Added custom\" = Table.AddColumn(#\"Changed column type\", \"Actual_Shipment_DateTime_PST\", each DateTime.AddZone([ACTUAL_SHIPMENT_DATE], -8)),\r\n    #\"Changed column type 1\" = Table.TransformColumnTypes(#\"Added custom\", {{\"Actual_Shipment_DateTime_PST\", type datetimezone}}),\r\n    #\"Inserted local time\" = Table.AddColumn(#\"Changed column type 1\", \"Actual_Shipment_DateTime_Local\", each DateTimeZone.ToLocal([Actual_Shipment_DateTime_PST]), type nullable datetimezone),\r\n    #\"Duplicated column\" = Table.DuplicateColumn(#\"Inserted local time\", \"Actual_Shipment_DateTime_Local\", \"Actual_Shipment_Date_Local\"),\r\n    #\"Changed column type 2\" = Table.TransformColumnTypes(#\"Duplicated column\", {{\"Actual_Shipment_Date_Local\", type date}}),\r\n    #\"Added custom 1\" = Table.TransformColumnTypes(Table.AddColumn(#\"Changed column type 2\", \"LastUpdateInt_IncrRefresh\", each Date.Year([LAST_UPDATE_DATE])*10000 + Date.Month([LAST_UPDATE_DATE])*100 + Date.Day([LAST_UPDATE_DATE])), {{\"LastUpdateInt_IncrRefresh\", Int64.Type}}),\r\n    #\"XXREP_OM_OTD_V-4C4153545F5550444154455F44415445-autogenerated_for_incremental_refresh\" = Table.SelectRows(#\"Added custom 1\", each DateTime.From([LAST_UPDATE_DATE]) >= RangeStart and DateTime.From([LAST_UPDATE_DATE]) < RangeEnd)\r\nin\r\n    #\"XXREP_OM_OTD_V-4C4153545F5550444154455F44415445-autogenerated_for_incremental_refresh\";\r\n\r\nshared XXCOH_MS_SHIPMENT_VIEW = let\r\n    Source = Value.NativeQuery(Snowflake.Databases(\"mma12090.snowflakecomputing.com\",\"COMPUTE_REPORTING\",[Role=\"GLBMFGOPERATIONSROLE\"]){[Name=\"PROD_DB\"]}[Data], \"SELECT *FROM PROD_DB.APPS.XXCOH_MS_SHIPMENT_VIEW\", null, [EnableFolding=true]),\r\n    #\"Filtered rows\" = Table.SelectRows(Source, each [BOOKED_DATE] > parStartDate),\r\n    #\"Choose columns\" = Table.SelectColumns(#\"Filtered rows\", {\"ASOF_DATE\", \"ASOF_DATE_DISP\", \"SYSTEM_DATE\", \"ENTER_DATE\", \"BOOKED_DATE\", \"ORDER_NUMBER\", \"ORDER_LINE\", \"ORDER_TYPE\", \"SO_LINE_TYPE\", \"LINE_STATUS\", \"BILLABLE_FLAG\", \"SALES_CHANNEL\", \"AGREEMENT_NUMBER\", \"ITEM_TYPE_CODE\", \"ACTUAL_SHIPMENT_DATE\", \"REGIONAL_LOCATION\", \"REPORTING_ENTITY\", \"ASP_FLAG\", \"INV_FLAG\", \"LINE_CATEGORY_CODE\", \"LINE_SOURCE_TYPE_CODE\", \"CUSTOMER_PO\", \"CREATED_BY\", \"ITEM_NUMBER\", \"ITEM_DESCRIPTION\", \"PRODUCT_LINE\", \"PRODUCT_FAMILY\", \"TECHNICAL_BUSINESS_UNIT\", \"REV_ENTITY\", \"REVENUE_ACCOUNT\", \"FORECAST_FIELD\", \"COMMODITY\", \"ORG_PRODUCT_LINE\", \"ORG_PRODUCT_FAMILY\", \"ORG_TECHNICAL_BUSINESS_UNIT\", \"ORG_FORECAST_FIELD\", \"LEAD_TIME\", \"PRIMARY_ORG\", \"ITEM_CUSTOMER\", \"BCP_CODE\", \"ROYALTY\", \"WAREHOUSE\", \"SHIPPING_METHOD_CODE\", \"TR_UNIT_SELLING_PRICE\", \"TR_ITEM_UNIT_COST\", \"GROSS_MARGIN_PCT\", \"DISCOUNT_PERCENT\", \"TR_DISCOUNT_AMOUNT\", \"PRICE_LIST\", \"UNIT_SELLING_PRICE\", \"ITEM_UNIT_COST\", \"UNIT_LIST_PRICE\", \"DISCOUNT_AMOUNT\", \"APPLICATION_CODE\", \"APPLICATION_CODE_DESC\", \"MARKET_SEGMENT\", \"REQUEST_SHIP_DATE\", \"PROMISE_SHIP_DATE\", \"SCHEDULE_SHIP_DATE\", \"CUSTOMER_NAME\", \"CUSTOMER_ALTERNATE_NAME\", \"CUSTOMER_NUMBER\", \"PARTY_NUMBER\", \"SHIP_TO_NAME\", \"SHIP_TO_COUNTRY\", \"SHIP_TO_CITY\", \"SHIP_TO_STATE\", \"SHIP_TO_POSTAL_CODE\", \"SHIP_TO_COUNTY\", \"SHIP_TO_PROVINCE\", \"SHIP_TO_SITE\", \"SHIP_TO_CONTACT\", \"END_USER\", \"END_USER_NUMBER\", \"END_USER_CONTACT\", \"END_USER_CITY\", \"END_USER_STATE\", \"END_USER_COUNTY\", \"END_USER_PROVINCE\", \"END_USER_POSTAL_CODE\", \"END_USER_COUNTRY_NAME\", \"MAJOR_GEOGRAPHICAL_AREA\", \"GL_CLASS\", \"CUSTOMER_CLASS\", \"CUSTOMER_CATEGORY\", \"CUSTOMER_TYPE\", \"FREIGHT_TERM\", \"FOB\", \"LEGAL_ENTITY\", \"OPERATING_UNIT\", \"TRANSACTION_CURRENCY\", \"FUNCTIONAL_CURRENCY\", \"TRX_TO_USD_RATE\", \"TRX_TO_FUNC_RATE\", \"COST_TO_FUNC_RATE\", \"COST_TO_USD_RATE\", \"UNIT_SELLING_PRICE_USD\", \"UNIT_LIST_PRICE_USD\", \"ORDER_STATUS\", \"OE_LINE_NUMBER\", \"DELIVERY_NAME\", \"DELIVERY_SHIPPING_STATUS_CODE\", \"DELIVERY_CONFIRM_DATE\", \"ITEM_REVISION\", \"SHIP_SET_ID\", \"ARRIVAL_SET_ID\", \"SHIP_MODEL_COMPLETE_FLAG\", \"TRACKING_NUMBER\", \"COUNTRY_OF_ORIGIN\", \"CLASSIFICATION\", \"SHIP_FROM_LOCATION_CODE\", \"ULTIMATE_SHIP_TO\", \"SHIP_FROM_ORG_CODE\", \"SUBINVENTORY\", \"LOT_NUMBER\", \"SERIAL_NUMBER\", \"TO_SERIAL_NUMBER\", \"LEAST_NUM_OF_SERIAL_NUMBER\", \"CUST_REQUESTED_QUANTITY\", \"CUST_REQUESTED_QUANTITY_UOM\", \"PICKED_QUANTITY\", \"SHIPPED_QUANTITY\", \"DELIVERED_QUANTITY\", \"RECEIVED_QUANTITY\", \"CANCELLED_QUANTITY\", \"SHIPPING_QUANTITY\", \"SHIPPING_QUANTITY_UOM\", \"PICK_RELEASE_STATUS_CODE\", \"PICK_RELEASE_STATUS\", \"DATE_REQUESTED\", \"DATE_SCHEDULED\", \"OE_INTERFACED_FLAG\", \"SHIP_METHOD_CODE\", \"FREIGHT_TERMS_CODE\", \"SHIPMENT_PRIORITY_CODE\", \"SHIPPING_INSTRUCTIONS\", \"PACKING_INSTRUCTIONS\", \"CONSIGNEE\", \"WAYBILL\", \"GROSS_WEIGHT\", \"NET_WEIGHT\", \"WEIGHT_UOM_CODE\", \"VOLUME\", \"VOLUME_UOM_CODE\", \"CARRIER_NAME\", \"NO_OF_PIECES\", \"UOM_OF_PIECES\", \"MOVE_ORDER_NUMBER\", \"MOVE_ORDER_LINE_NUMBER\", \"FREIGHT_CHARGE\", \"FREIGHT_CHARGE_USD\", \"FREIGHT_CURRENCY_CODE\", \"SHIP_FROM_DATE\", \"SHIP_TO_DATE\", \"END_CUST_USD_RATE\", \"PLANNER_CODE\", \"END_ASSEMBLY_PEGGING\", \"FIRST_SCHEDULE_DATE\", \"EXTERNAL_ORDER_NUMBER\", \"INTERCO_PO_NUM\", \"CST_CURRENCY_CODE\", \"PROJECT_NUMBER\", \"PROJECT_ID\", \"PROJECT_NAME\", \"IMPORTER_NAME\", \"IMPORTER_NUMBER\", \"IMPORTER_ADDRESS1\", \"IMPORTER_ADDRESS2\", \"IMPORTER_CITY\", \"IMPORTER_STATE\", \"IMPORTER_COUNTY\", \"IMPORTER_POSTAL_CODE\", \"IMPORTER_PROVINCE\", \"IMPORTER_COUNTRY_NAME\", \"DELIVERY_PACK_DIMENSIONS\", \"DELIVERY_TYPE\", \"MODE_OF_TRANSPORT\", \"ROW_CREATION_DATE\"}),\r\n    #\"Inserted merged column\" = Table.AddColumn(#\"Choose columns\", \"OrderNumber_OrderLine\", each Text.Combine({Text.From([ORDER_NUMBER]), [ORDER_LINE]}, \"_\"), type text),\r\n    #\"Added custom\" = Table.TransformColumnTypes(Table.AddColumn(#\"Inserted merged column\", \"ReqToActual-Shipment_Days\", each Duration.Days(DateTime.From([ACTUAL_SHIPMENT_DATE])-[REQUEST_SHIP_DATE])), {{\"ReqToActual-Shipment_Days\", Int64.Type}}),\r\n    #\"Added custom 1\" = Table.TransformColumnTypes(Table.AddColumn(#\"Added custom\", \"PromToActual-Shipment_Days\", each Duration.Days(DateTime.From([ACTUAL_SHIPMENT_DATE])-[PROMISE_SHIP_DATE])), {{\"PromToActual-Shipment_Days\", Int64.Type}}),\r\n    #\"Added custom 2\" = Table.TransformColumnTypes(Table.AddColumn(#\"Added custom 1\", \"SchedToActual-Shipment_Days\", each Duration.Days(DateTime.From([ACTUAL_SHIPMENT_DATE])-[SCHEDULE_SHIP_DATE])), {{\"SchedToActual-Shipment_Days\", Int64.Type}}),\r\n    #\"Inserted conditional column\" = Table.AddColumn(#\"Added custom 2\", \"ReqToActual-Shipm_Status\", each if [#\"ReqToActual-Shipment_Days\"] = null then \"H. Not Shipped\" else if [#\"ReqToActual-Shipment_Days\"] < -9999 then \"I. Not Scheduled\" else if [#\"ReqToActual-Shipment_Days\"] < -3 then \"A. Early\" else if [#\"ReqToActual-Shipment_Days\"] < 1 then \"B. On Time\" else if [#\"ReqToActual-Shipment_Days\"] < 7 then \"C. 1 Week Late\" else if [#\"ReqToActual-Shipment_Days\"] < 14 then \"D. 2 Weeks Late\" else if [#\"ReqToActual-Shipment_Days\"] < 21 then \"E. 3 Weeks Late\" else if [#\"ReqToActual-Shipment_Days\"] < 28 then \"F. 4 Weeks Late\" else if [#\"ReqToActual-Shipment_Days\"] >= 28 then \"G. Over 1 Month\" else \"NoDates\"),\r\n    #\"Inserted conditional column 1\" = Table.AddColumn(#\"Inserted conditional column\", \"PromToActual-Shipm_Status\", each if [#\"PromToActual-Shipment_Days\"] = null then \"H. Not Shipped\" else if [#\"PromToActual-Shipment_Days\"] < -9999 then \"I. Not Scheduled\" else if [#\"PromToActual-Shipment_Days\"] < -3 then \"A. Early\" else if [#\"PromToActual-Shipment_Days\"] < 1 then \"B. On Time\" else if [#\"PromToActual-Shipment_Days\"] < 7 then \"C. 1 Week Late\" else if [#\"PromToActual-Shipment_Days\"] < 14 then \"D. 2 Weeks Late\" else if [#\"PromToActual-Shipment_Days\"] < 21 then \"E. 3 Weeks Late\" else if [#\"PromToActual-Shipment_Days\"] < 28 then \"F. 4 Weeks Late\" else if [#\"PromToActual-Shipment_Days\"] >= 28 then \"G. Over 1 Month\" else \"No Dates\"),\r\n    #\"Inserted conditional column 2\" = Table.AddColumn(#\"Inserted conditional column 1\", \"SchedToActual-Shipm_Status\", each if [#\"SchedToActual-Shipment_Days\"] = null then \"H. Not Shipped\" else if [#\"SchedToActual-Shipment_Days\"] < -9999 then \"I. Not Scheduled\" else if [#\"SchedToActual-Shipment_Days\"] < -3 then \"A. Early\" else if [#\"SchedToActual-Shipment_Days\"] < 1 then \"B. On Time\" else if [#\"SchedToActual-Shipment_Days\"] < 7 then \"C. 1 Week Late\" else if [#\"SchedToActual-Shipment_Days\"] < 14 then \"D. 2 Weeks Late\" else if [#\"SchedToActual-Shipment_Days\"] < 21 then \"E. 3 Weeks Late\" else if [#\"SchedToActual-Shipment_Days\"] < 28 then \"F. 4 Weeks Late\" else if [#\"SchedToActual-Shipment_Days\"] >= 28 then \"G. Over 1 Month\" else \"No Dates\"),\r\n    #\"Changed column type\" = Table.TransformColumnTypes(#\"Inserted conditional column 2\", {{\"ReqToActual-Shipm_Status\", type text}, {\"PromToActual-Shipm_Status\", type text}, {\"SchedToActual-Shipm_Status\", type text}}),\r\n    #\"Added custom 3\" = Table.TransformColumnTypes(Table.AddColumn(#\"Changed column type\", \"Actual_Shipment_DateTime_PST\", each DateTime.AddZone([ACTUAL_SHIPMENT_DATE], -8)), {{\"Actual_Shipment_DateTime_PST\", type datetimezone}}),\r\n    #\"Inserted local time\" = Table.AddColumn(#\"Added custom 3\", \"Actual_Shipment_DateTime_Local\", each DateTimeZone.ToLocal([Actual_Shipment_DateTime_PST]), type nullable datetimezone),\r\n    #\"Duplicated column\" = Table.DuplicateColumn(#\"Inserted local time\", \"Actual_Shipment_DateTime_Local\", \"Actual_Shipment_Date_Local\"),\r\n    #\"Changed column type 1\" = Table.TransformColumnTypes(#\"Duplicated column\", {{\"Actual_Shipment_Date_Local\", type date}}),\r\n    #\"XXCOH_MS_SHIPMENT_VIEW-41534F465F44415445-autogenerated_for_incremental_refresh\" = Table.SelectRows(#\"Changed column type 1\", each DateTime.From([ASOF_DATE]) >= RangeStart and DateTime.From([ASOF_DATE]) < RangeEnd)\r\nin\r\n    #\"XXCOH_MS_SHIPMENT_VIEW-41534F465F44415445-autogenerated_for_incremental_refresh\";\r\n\r\nshared XXREP_RESOURCE_TRAN_V = let\r\n    Source = Value.NativeQuery(Snowflake.Databases(\"mma12090.snowflakecomputing.com\",\"COMPUTE_REPORTING\",[Role=\"GLBMFGOPERATIONSROLE\"]){[Name=\"PROD_DB\"]}[Data], \"SELECT * FROM PROD_DB.APPS.XXREP_RESOURCE_TRAN_V\", null, [EnableFolding=true]),\r\n    #\"Filtered rows\" = Table.SelectRows(Source, each [LAST_UPDATE_DATE] > parStartDate),\r\n    #\"Choose columns\" = Table.SelectColumns(#\"Filtered rows\", {\"JOB_NUMBER\", \"WIPJOB_ORG_KEY_CODE\", \"WIPJOB_ORG_KEY_ID\", \"JOB_TYPE\", \"TRANSACTION_TYPE\", \"TRANSACTION_DATE\", \"TRANSACTION_QUANTITY\", \"TRANSACTION_UOM\", \"ORGANIZATION_ID\", \"WIP_ENTITY_ID\", \"DEPARTMENT_ID\", \"MOVE_TRANSACTION_ID\", \"LAST_UPDATE_DATE\", \"DEPARTMENT_CODE\", \"RESOURCE_CODE\", \"ITEM_NUMBER\", \"PERIOD_NAME\", \"INVORG_CODE\", \"INVORG_ID\", \"LOCAL_EXTRACT_DATE\"}),\r\n    #\"Merged queries\" = Table.NestedJoin(#\"Choose columns\", {\"DEPARTMENT_ID\"}, XXREP_BOM_DEPT_RESOURCE_V, {\"DEPARTMENT_ID\"}, \"XXREP_BOM_DEPT_RESOURCE_V\", JoinKind.LeftOuter),\r\n    #\"Expanded XXREP_BOM_DEPT_RESOURCE_V\" = Table.ExpandTableColumn(#\"Merged queries\", \"XXREP_BOM_DEPT_RESOURCE_V\", {\"DEPARTMENT_DESCRIPTION\"}, {\"DEPARTMENT_DESCRIPTION\"}),\r\n    #\"Filtered rows 1\" = Table.SelectRows(#\"Expanded XXREP_BOM_DEPT_RESOURCE_V\", each [TRANSACTION_TYPE] = \"RESOURCE TRANSACTION\"),\r\n    #\"Choose columns 1\" = Table.SelectColumns(#\"Filtered rows 1\", {\"JOB_NUMBER\", \"WIPJOB_ORG_KEY_CODE\", \"WIPJOB_ORG_KEY_ID\", \"JOB_TYPE\", \"TRANSACTION_TYPE\", \"TRANSACTION_DATE\", \"TRANSACTION_QUANTITY\", \"TRANSACTION_UOM\", \"ORGANIZATION_ID\", \"LAST_UPDATE_DATE\", \"DEPARTMENT_CODE\", \"RESOURCE_CODE\", \"ITEM_NUMBER\", \"PERIOD_NAME\", \"INVORG_CODE\", \"INVORG_ID\", \"DEPARTMENT_DESCRIPTION\"}),\r\n    #\"Changed column type\" = Table.TransformColumnTypes(#\"Choose columns 1\", {{\"ORGANIZATION_ID\", Int64.Type}, {\"INVORG_ID\", Int64.Type}, {\"TRANSACTION_DATE\", type date}}),\r\n    #\"XXREP_RESOURCE_TRAN_V-4C4153545F5550444154455F44415445-autogenerated_for_incremental_refresh\" = Table.SelectRows(#\"Changed column type\", each DateTime.From([LAST_UPDATE_DATE]) >= RangeStart and DateTime.From([LAST_UPDATE_DATE]) < RangeEnd)\r\nin\r\n    #\"XXREP_RESOURCE_TRAN_V-4C4153545F5550444154455F44415445-autogenerated_for_incremental_refresh\";\r\n\r\nshared XXREP_WW_OMTRX_DATAMART_V = let\r\n    Source = Value.NativeQuery(Snowflake.Databases(\"mma12090.snowflakecomputing.com\",\"COMPUTE_REPORTING\",[Role=\"GLBMFGOPERATIONSROLE\"]){[Name=\"PROD_DB\"]}[Data], \"SELECT *FROM PROD_DB.APPS.XXREP_WW_OMTRX_DATAMART_V\", null, [EnableFolding=true]),\r\n    #\"Filtered rows\" = Table.SelectRows(Source, each [LAST_UPDATE_DATE] > parStartDate),\r\n    #\"Choose columns\" = Table.SelectColumns(#\"Filtered rows\", {\"REGION\", \"OU\", \"ORDERED_QUANTITY\", \"FIRST_SCHEDULE_DATE\", \"HEADER_ORDERED_DATE\", \"HEADER_CREATION_DATE\", \"HEADER_BOOK_DATE\", \"BOOKING_OFFICE\", \"REPORTING_ENTITY\", \"ORDER_TYPE\", \"SCHEDULE_SHIP_DATE\", \"REQUEST_SHIP_DATE\", \"ORDER_NUMBER\", \"TECHNICAL_BUSINESS_UNIT\", \"WAREHOUSE\", \"ORDER_LINE\", \"ITEM_NUMBER\", \"ORDER_STATUS\", \"LINE_STATUS\", \"CUSTOMER_NAME\", \"CUSTOMER_TYPE\", \"CUSTOMER_CLASS\", \"SHIP_TO_COUNTRY\", \"SO_LINE_TYPE\", \"ACTUAL_SHIPMENT_DATE\", \"FISCAL_PERIOD_HEADER_BOOKED\", \"FISCAL_YEAR_HEADER_BOOKED\", \"SCHEDULED_VS_SHIP_DAYS\", \"FORECAST_FIELD\", \"SUBINVENTORY\", \"LINE_CREATION_DATE\", \"BOOKED_DATE\", \"BACKLOG_QUANTITY\", \"PROMISE_SHIP_DATE\", \"LAST_UPDATE_DATE\", \"ORDER_LAST_UPDATE_DATE\", \"SHIP_FROM_ORG_ID\", \"ITEM_STATUS\", \"PLANNER_CODE\", \"END_CUST_NAME\", \"OU_ORDER_LINE\", \"PERIOD_NAME\"}),\r\n    #\"Added custom\" = Table.AddColumn(#\"Choose columns\", \"Actual_Shipment_DateTime_PST\", each DateTime.AddZone([ACTUAL_SHIPMENT_DATE], -8)),\r\n    #\"Changed column type\" = Table.TransformColumnTypes(#\"Added custom\", {{\"Actual_Shipment_DateTime_PST\", type datetimezone}, {\"SCHEDULE_SHIP_DATE\", type date}, {\"REQUEST_SHIP_DATE\", type date}, {\"ORDER_NUMBER\", Int64.Type}, {\"ACTUAL_SHIPMENT_DATE\", type date}, {\"FISCAL_YEAR_HEADER_BOOKED\", Int64.Type}, {\"LINE_CREATION_DATE\", type date}, {\"BOOKED_DATE\", type date}, {\"PROMISE_SHIP_DATE\", type date}, {\"SHIP_FROM_ORG_ID\", Int64.Type}}),\r\n    #\"Inserted local time\" = Table.AddColumn(#\"Changed column type\", \"Actual_Shipment_DateTime_Local\", each DateTimeZone.ToLocal([Actual_Shipment_DateTime_PST]), type datetimezone),\r\n    #\"Duplicated column\" = Table.DuplicateColumn(#\"Inserted local time\", \"Actual_Shipment_DateTime_Local\", \"Actual_Shipment_Date_Local\"),\r\n    #\"Changed column type 1\" = Table.TransformColumnTypes(#\"Duplicated column\", {{\"Actual_Shipment_Date_Local\", type date}, {\"HEADER_BOOK_DATE\", type date}, {\"ORDER_LAST_UPDATE_DATE\", type date}}),\r\n    #\"XXREP_WW_OMTRX_DATAMART_V-4C4153545F5550444154455F44415445-autogenerated_for_incremental_refresh\" = Table.SelectRows(#\"Changed column type 1\", each DateTime.From([LAST_UPDATE_DATE]) >= RangeStart and DateTime.From([LAST_UPDATE_DATE]) < RangeEnd)\r\nin\r\n    #\"XXREP_WW_OMTRX_DATAMART_V-4C4153545F5550444154455F44415445-autogenerated_for_incremental_refresh\";\r\n\r\nshared RangeStart = let RangeStart = #datetime(0001,01,01,00,00,00) meta [IsParameterQuery=true, List={}, Type=\"DateTime\", IsParameterQueryRequired=true, Description=\"autogenerated_for_incremental_refresh\"] in RangeStart;\r\n\r\nshared RangeEnd = let RangeEnd = #datetime(9999,12,31,23,59,59) meta [IsParameterQuery=true, List={}, Type=\"DateTime\", IsParameterQueryRequired=true, Description=\"autogenerated_for_incremental_refresh\"] in RangeEnd;\r\n\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"XXREP_WIP_DISCRETE_JOBS_V","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"XXREP_WIP_DISCRETE_JOBS_V.csv"},"attributes":[{"name":"ORGANIZATION_ID","dataType":"int64"},{"name":"WIP_ENTITY_ID","dataType":"int64"},{"name":"WIPJOB_ORG_KEY_CODE","dataType":"string"},{"name":"WIPJOB_ORG_KEY_ID","dataType":"string"},{"name":"LAST_UPDATE_DATE","dataType":"dateTime"},{"name":"CREATION_DATE","dataType":"dateTime"},{"name":"PRIMARY_ITEM_ID","dataType":"int64"},{"name":"CLASS_CODE","dataType":"string"},{"name":"START_QUANTITY","dataType":"double"},{"name":"QUANTITY_REMAINING","dataType":"double"},{"name":"QUANTITY_COMPLETED","dataType":"double"},{"name":"QUANTITY_SCRAPPED","dataType":"double"},{"name":"NET_QUANTITY","dataType":"double"},{"name":"LOT_NUMBER","dataType":"string"},{"name":"COMPLETION_SUBINVENTORY","dataType":"string"},{"name":"SCHEDULED_START_DATE","dataType":"date"},{"name":"DATE_RELEASED","dataType":"date"},{"name":"SCHEDULED_COMPLETION_DATE","dataType":"date"},{"name":"DATE_COMPLETED","dataType":"dateTime"},{"name":"DATE_CLOSED","dataType":"dateTime"},{"name":"DUE_DATE","dataType":"date"},{"name":"ENTITY_TYPE","dataType":"int64"},{"name":"REQUESTED_START_DATE","dataType":"date"},{"name":"ACTUAL_START_DATE","dataType":"date"},{"name":"INVORG_CODE","dataType":"string"},{"name":"JOB_STATUS","dataType":"string"},{"name":"WIP_SUPPLY_TYPE","dataType":"string"},{"name":"JOB_NUMBER","dataType":"string"},{"name":"JOB_TYPE","dataType":"string"},{"name":"FIRST_UNIT_START_DATE","dataType":"date"},{"name":"FIRST_UNIT_COMPLETION_DATE","dataType":"date"},{"name":"LAST_UNIT_START_DATE","dataType":"date"},{"name":"LAST_UNIT_COMPLETION_DATE","dataType":"date"},{"name":"ITEM_NUMBER","dataType":"string"},{"name":"ITEM_ORG_KEY_ID","dataType":"string"},{"name":"ITEM_ORG_KEY_CODE","dataType":"string"},{"name":"ORG_TBU","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T05:14:23.276998+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/81c2e363-ed59-43f0-804a-3c3b1891ee63/XXREP_WIP_DISCRETE_JOBS_V.csv?snapshot=2022-06-13T05%3A14%3A23.2401603Z"}]},{"$type":"LocalEntity","name":"XXREP_OM_OTD_V","description":"","pbi:refreshPolicy":{"$type":"IncrementalRefreshPolicy","locationPattern":"XXREP_OM_OTD_V/part.csv","rollingWindowGranularity":"year","rollingWindowPeriods":3,"incrementalGranularity":"quarter","incrementalPeriods":3},"annotations":[{"name":"pbi:IncrementalRefreshDetectChangeAttribute"},{"name":"pbi:IncrementalRefreshFilterByAttribute","value":"LAST_UPDATE_DATE"}],"attributes":[{"name":"STALE_DATE","dataType":"string"},{"name":"RECEIVED_TO_SCHEDULED","dataType":"string"},{"name":"ORDER_HEADER_CREATED_BY","dataType":"string"},{"name":"SET_OF_BOOKS","dataType":"string"},{"name":"REGION","dataType":"string"},{"name":"OU","dataType":"string"},{"name":"CUSTOMER_NUMBER","dataType":"string"},{"name":"FULL_NAME_BILL_TO_COUNTRY","dataType":"string"},{"name":"ORDERED_QUANTITY","dataType":"double"},{"name":"ITEM_DESCRIPTION","dataType":"string"},{"name":"FIRST_SCHEDULE_DATE","dataType":"date"},{"name":"RECEIVED_TO_ENTERED","dataType":"string"},{"name":"RECEIVED_TO_BOOKED","dataType":"string"},{"name":"ENTERED_TO_BOOKED","dataType":"string"},{"name":"BOOKED_TO_SCHEDULED","dataType":"string"},{"name":"HEADER_ORDERED_DATE","dataType":"dateTime"},{"name":"HEADER_CREATION_DATE","dataType":"dateTime"},{"name":"HEADER_BOOK_DATE","dataType":"dateTime"},{"name":"BOOKING_OFFICE","dataType":"string"},{"name":"REPORTING_ENTITY","dataType":"string"},{"name":"ORDER_TYPE","dataType":"string"},{"name":"SCHEDULE_SHIP_DATE","dataType":"dateTime"},{"name":"REQUEST_SHIP_DATE","dataType":"dateTime"},{"name":"ORDER_NUMBER","dataType":"double"},{"name":"TECHNICAL_BUSINESS_UNIT","dataType":"string"},{"name":"WAREHOUSE","dataType":"string"},{"name":"ORDER_LINE","dataType":"string"},{"name":"ITEM_NUMBER","dataType":"string"},{"name":"LINE_CREATED_BY","dataType":"string"},{"name":"ORDER_STATUS","dataType":"string"},{"name":"LINE_STATUS","dataType":"string"},{"name":"CUSTOMER_NAME","dataType":"string"},{"name":"ALT_CUSTOMER_NAME","dataType":"string"},{"name":"CUSTOMER_TYPE","dataType":"string"},{"name":"CUSTOMER_CLASS","dataType":"string"},{"name":"EXTENDED_AMOUNT","dataType":"decimal"},{"name":"EXTENDED_AMOUNT_USD","dataType":"decimal"},{"name":"FUNCTIONAL_CURRENCY","dataType":"string"},{"name":"TRANSACTION_CURRENCY","dataType":"string"},{"name":"LINE_ID","dataType":"int64"},{"name":"HEADER_ID","dataType":"int64"},{"name":"PRODUCT_FAMILY","dataType":"string"},{"name":"PRODUCT_LINE","dataType":"string"},{"name":"SALESPERSON","dataType":"string"},{"name":"SHIP_TO_COUNTRY","dataType":"string"},{"name":"SO_LINE_TYPE_ID","dataType":"double"},{"name":"SO_LINE_TYPE","dataType":"string"},{"name":"ACTUAL_SHIPMENT_DATE","dataType":"dateTime"},{"name":"FORMATTED_HEADER_BOOKED_DATE","dataType":"string"},{"name":"FISCAL_PERIOD_HEADER_BOOKED","dataType":"string"},{"name":"FISCAL_YEAR_HEADER_BOOKED","dataType":"int64"},{"name":"FISCAL_QUARTER_HEADER_BOOKED","dataType":"string"},{"name":"FISCAL_WEEK_HEADER_BOOKED","dataType":"int64"},{"name":"ORDER_CATEGORY_UNIQUE","dataType":"string"},{"name":"ORDER_CLASSIFICATION_UNIQUE","dataType":"string"},{"name":"RECEIVED_TO_FIRST_SCHEDULED","dataType":"string"},{"name":"BOOKED_TO_FIRST_SCHEDULED","dataType":"string"},{"name":"SCHEDULED_VS_SHIP_DAYS","dataType":"double"},{"name":"FORECAST_FIELD","dataType":"string"},{"name":"SUBINVENTORY","dataType":"string"},{"name":"LINE_CREATION_DATE","dataType":"dateTime"},{"name":"BOOKED_DATE","dataType":"dateTime"},{"name":"SCHEDULE_ORDER","dataType":"string"},{"name":"BACKLOG_QUANTITY","dataType":"double"},{"name":"UNIT_SELLING_PRICE","dataType":"decimal"},{"name":"PROMISE_SHIP_DATE","dataType":"dateTime"},{"name":"HDR_RECEIVED_TO_SHIPPED_DAYS","dataType":"double"},{"name":"HDR_BOOKED_TO_ACTUAL_SHIP_DAYS","dataType":"double"},{"name":"LN_BOOKED_TO_ACTUAL_SHIP_DAYS","dataType":"double"},{"name":"RECEIVING_DATE","dataType":"dateTime"},{"name":"ORDER_CUSTOMER_PO","dataType":"string"},{"name":"LINE_CUSTOMER_PO","dataType":"string"},{"name":"ORDER_TYPE_ID","dataType":"int64"},{"name":"SERIAL_CTRL","dataType":"string"},{"name":"LOT_CTRL","dataType":"string"},{"name":"LAST_UPDATE_DATE","dataType":"dateTime"},{"name":"L_LAST_UPDATED_BY","dataType":"string"},{"name":"ORDER_LAST_UPDATE_DATE","dataType":"dateTime"},{"name":"H_LAST_UPDATED_BY","dataType":"string"},{"name":"LINE_CATEGORY_CODE","dataType":"string"},{"name":"SHIP_FROM_ORG_ID","dataType":"int64"},{"name":"FOB","dataType":"string"},{"name":"OPERATING_UNIT_ID","dataType":"int64"},{"name":"INTMED_SHIP_TO","dataType":"double"},{"name":"ITEM_STATUS","dataType":"string"},{"name":"CUSTOMS_VALUE_ON_CI","dataType":"string"},{"name":"CUSTOMS_CURRENCY_ON_CI","dataType":"string"},{"name":"ORD_TOTAL","dataType":"double"},{"name":"FREIGHT_TERMS_CODE","dataType":"string"},{"name":"TAX_CODE","dataType":"string"},{"name":"LINE_FOB_POINT","dataType":"string"},{"name":"PLANNER_CODE","dataType":"string"},{"name":"SFDC_OPP_ID","dataType":"string"},{"name":"IMPORTER_ID","dataType":"string"},{"name":"IMPORTER_NAME","dataType":"string"},{"name":"END_CUST_NAME","dataType":"string"},{"name":"BILL_TO_COUNTRY","dataType":"string"},{"name":"SHIP_TO_ADDRESS1","dataType":"string"},{"name":"SHIP_TO_ADDRESS2","dataType":"string"},{"name":"FULL_NAME_SHIP_TO_COUNTRY","dataType":"string"},{"name":"OU_ORDER_LINE","dataType":"string"},{"name":"OU_ORDER","dataType":"string"},{"name":"PERIOD_NAME","dataType":"string"},{"name":"DATE_RUN","dataType":"date"},{"name":"H_CREATED_BY_ID","dataType":"int64"},{"name":"ORDER_LINE_TYPE_ID_KEY","dataType":"string"},{"name":"DATA_UPDATE_DESC","dataType":"string"},{"name":"FIN_ENTITY","dataType":"string"},{"name":"FIN_SITE","dataType":"string"},{"name":"ORG_TECHNICAL_BUSINESS_UNIT","dataType":"string"},{"name":"ORG_PRODUCT_FAMILY","dataType":"string"},{"name":"FIN_TBU","dataType":"string"},{"name":"FIN_PFC","dataType":"string"},{"name":"FINPRODUCT_KEY","dataType":"string"},{"name":"Actual_Shipment_DateTime_PST","dataType":"dateTimeOffset"},{"name":"Actual_Shipment_DateTime_Local","dataType":"dateTimeOffset"},{"name":"Actual_Shipment_Date_Local","dataType":"date"},{"name":"LastUpdateInt_IncrRefresh","dataType":"int64"}],"partitions":[{"name":"IncrementalRefreshPolicyPartition-2019","refreshTime":"2022-03-28T20:10:44.2230049+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/81c2e363-ed59-43f0-804a-3c3b1891ee63/XXREP_OM_OTD_V/part-2019.csv?snapshot=2022-03-28T20%3A10%3A44.2061714Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2019-01-01T00:00:00","end":"2020-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2020","refreshTime":"2022-03-28T20:10:41.1291357+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/81c2e363-ed59-43f0-804a-3c3b1891ee63/XXREP_OM_OTD_V/part-2020.csv?snapshot=2022-03-28T20%3A10%3A41.0649748Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2020-01-01T00:00:00","end":"2021-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2021Q1","refreshTime":"2022-03-28T20:08:13.2665041+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/81c2e363-ed59-43f0-804a-3c3b1891ee63/XXREP_OM_OTD_V/part-2021Q1.csv?snapshot=2022-03-28T20%3A08%3A13.2198721Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2021-01-01T00:00:00","end":"2021-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2021Q2","refreshTime":"2022-03-28T20:08:12.9383313+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/81c2e363-ed59-43f0-804a-3c3b1891ee63/XXREP_OM_OTD_V/part-2021Q2.csv?snapshot=2022-03-28T20%3A08%3A12.8950581Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2021-04-01T00:00:00","end":"2021-07-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2021Q3","refreshTime":"2022-04-01T05:13:39.9475515+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/81c2e363-ed59-43f0-804a-3c3b1891ee63/XXREP_OM_OTD_V/part-2021Q3.csv?snapshot=2022-04-01T05%3A13%3A39.8207448Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2021-07-01T00:00:00","end":"2021-10-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2021Q4","refreshTime":"2022-06-13T05:10:42.5453356+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/81c2e363-ed59-43f0-804a-3c3b1891ee63/XXREP_OM_OTD_V/part-2021Q4.csv?snapshot=2022-06-13T05%3A10%3A42.4392175Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2021-10-01T00:00:00","end":"2022-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q1","refreshTime":"2022-06-13T05:11:03.0203679+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/81c2e363-ed59-43f0-804a-3c3b1891ee63/XXREP_OM_OTD_V/part-2022Q1.csv?snapshot=2022-06-13T05%3A11%3A02.8564732Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-01-01T00:00:00","end":"2022-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q2","refreshTime":"2022-06-13T05:11:09.7726452+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/81c2e363-ed59-43f0-804a-3c3b1891ee63/XXREP_OM_OTD_V/part-2022Q2.csv?snapshot=2022-06-13T05%3A11%3A09.6665549Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-01T00:00:00","end":"2022-07-01T00:00:00"}}]},{"$type":"LocalEntity","name":"XXCOH_MS_SHIPMENT_VIEW","description":"","pbi:refreshPolicy":{"$type":"IncrementalRefreshPolicy","locationPattern":"XXCOH_MS_SHIPMENT_VIEW/part.csv","rollingWindowGranularity":"year","rollingWindowPeriods":3,"incrementalGranularity":"quarter","incrementalPeriods":3},"annotations":[{"name":"pbi:IncrementalRefreshDetectChangeAttribute"},{"name":"pbi:IncrementalRefreshFilterByAttribute","value":"ASOF_DATE"}],"attributes":[{"name":"ASOF_DATE","dataType":"dateTime"},{"name":"ASOF_DATE_DISP","dataType":"dateTime"},{"name":"SYSTEM_DATE","dataType":"dateTime"},{"name":"ENTER_DATE","dataType":"dateTime"},{"name":"BOOKED_DATE","dataType":"dateTime"},{"name":"ORDER_NUMBER","dataType":"double"},{"name":"ORDER_LINE","dataType":"string"},{"name":"ORDER_TYPE","dataType":"string"},{"name":"SO_LINE_TYPE","dataType":"string"},{"name":"LINE_STATUS","dataType":"string"},{"name":"BILLABLE_FLAG","dataType":"string"},{"name":"SALES_CHANNEL","dataType":"string"},{"name":"AGREEMENT_NUMBER","dataType":"string"},{"name":"ITEM_TYPE_CODE","dataType":"string"},{"name":"ACTUAL_SHIPMENT_DATE","dataType":"dateTime"},{"name":"REGIONAL_LOCATION","dataType":"string"},{"name":"REPORTING_ENTITY","dataType":"string"},{"name":"ASP_FLAG","dataType":"string"},{"name":"INV_FLAG","dataType":"string"},{"name":"LINE_CATEGORY_CODE","dataType":"string"},{"name":"LINE_SOURCE_TYPE_CODE","dataType":"string"},{"name":"CUSTOMER_PO","dataType":"string"},{"name":"CREATED_BY","dataType":"string"},{"name":"ITEM_NUMBER","dataType":"string"},{"name":"ITEM_DESCRIPTION","dataType":"string"},{"name":"PRODUCT_LINE","dataType":"string"},{"name":"PRODUCT_FAMILY","dataType":"string"},{"name":"TECHNICAL_BUSINESS_UNIT","dataType":"string"},{"name":"REV_ENTITY","dataType":"string"},{"name":"REVENUE_ACCOUNT","dataType":"string"},{"name":"FORECAST_FIELD","dataType":"string"},{"name":"COMMODITY","dataType":"string"},{"name":"ORG_PRODUCT_LINE","dataType":"string"},{"name":"ORG_PRODUCT_FAMILY","dataType":"string"},{"name":"ORG_TECHNICAL_BUSINESS_UNIT","dataType":"string"},{"name":"ORG_FORECAST_FIELD","dataType":"string"},{"name":"LEAD_TIME","dataType":"string"},{"name":"PRIMARY_ORG","dataType":"string"},{"name":"ITEM_CUSTOMER","dataType":"string"},{"name":"BCP_CODE","dataType":"string"},{"name":"ROYALTY","dataType":"string"},{"name":"WAREHOUSE","dataType":"string"},{"name":"SHIPPING_METHOD_CODE","dataType":"string"},{"name":"TR_UNIT_SELLING_PRICE","dataType":"double"},{"name":"TR_ITEM_UNIT_COST","dataType":"string"},{"name":"GROSS_MARGIN_PCT","dataType":"double"},{"name":"DISCOUNT_PERCENT","dataType":"double"},{"name":"TR_DISCOUNT_AMOUNT","dataType":"double"},{"name":"PRICE_LIST","dataType":"string"},{"name":"UNIT_SELLING_PRICE","dataType":"double"},{"name":"ITEM_UNIT_COST","dataType":"double"},{"name":"UNIT_LIST_PRICE","dataType":"double"},{"name":"DISCOUNT_AMOUNT","dataType":"double"},{"name":"APPLICATION_CODE","dataType":"string"},{"name":"APPLICATION_CODE_DESC","dataType":"string"},{"name":"MARKET_SEGMENT","dataType":"string"},{"name":"REQUEST_SHIP_DATE","dataType":"dateTime"},{"name":"PROMISE_SHIP_DATE","dataType":"dateTime"},{"name":"SCHEDULE_SHIP_DATE","dataType":"dateTime"},{"name":"CUSTOMER_NAME","dataType":"string"},{"name":"CUSTOMER_ALTERNATE_NAME","dataType":"string"},{"name":"CUSTOMER_NUMBER","dataType":"string"},{"name":"PARTY_NUMBER","dataType":"string"},{"name":"SHIP_TO_NAME","dataType":"string"},{"name":"SHIP_TO_COUNTRY","dataType":"string"},{"name":"SHIP_TO_CITY","dataType":"string"},{"name":"SHIP_TO_STATE","dataType":"string"},{"name":"SHIP_TO_POSTAL_CODE","dataType":"string"},{"name":"SHIP_TO_COUNTY","dataType":"string"},{"name":"SHIP_TO_PROVINCE","dataType":"string"},{"name":"SHIP_TO_SITE","dataType":"string"},{"name":"SHIP_TO_CONTACT","dataType":"string"},{"name":"END_USER","dataType":"string"},{"name":"END_USER_NUMBER","dataType":"string"},{"name":"END_USER_CONTACT","dataType":"string"},{"name":"END_USER_CITY","dataType":"string"},{"name":"END_USER_STATE","dataType":"string"},{"name":"END_USER_COUNTY","dataType":"string"},{"name":"END_USER_PROVINCE","dataType":"string"},{"name":"END_USER_POSTAL_CODE","dataType":"string"},{"name":"END_USER_COUNTRY_NAME","dataType":"string"},{"name":"MAJOR_GEOGRAPHICAL_AREA","dataType":"string"},{"name":"GL_CLASS","dataType":"string"},{"name":"CUSTOMER_CLASS","dataType":"string"},{"name":"CUSTOMER_CATEGORY","dataType":"string"},{"name":"CUSTOMER_TYPE","dataType":"string"},{"name":"FREIGHT_TERM","dataType":"string"},{"name":"FOB","dataType":"string"},{"name":"LEGAL_ENTITY","dataType":"string"},{"name":"OPERATING_UNIT","dataType":"string"},{"name":"TRANSACTION_CURRENCY","dataType":"string"},{"name":"FUNCTIONAL_CURRENCY","dataType":"string"},{"name":"TRX_TO_USD_RATE","dataType":"double"},{"name":"TRX_TO_FUNC_RATE","dataType":"double"},{"name":"COST_TO_FUNC_RATE","dataType":"double"},{"name":"COST_TO_USD_RATE","dataType":"double"},{"name":"UNIT_SELLING_PRICE_USD","dataType":"double"},{"name":"UNIT_LIST_PRICE_USD","dataType":"double"},{"name":"ORDER_STATUS","dataType":"string"},{"name":"OE_LINE_NUMBER","dataType":"string"},{"name":"DELIVERY_NAME","dataType":"string"},{"name":"DELIVERY_SHIPPING_STATUS_CODE","dataType":"string"},{"name":"DELIVERY_CONFIRM_DATE","dataType":"dateTime"},{"name":"ITEM_REVISION","dataType":"string"},{"name":"SHIP_SET_ID","dataType":"double"},{"name":"ARRIVAL_SET_ID","dataType":"double"},{"name":"SHIP_MODEL_COMPLETE_FLAG","dataType":"string"},{"name":"TRACKING_NUMBER","dataType":"string"},{"name":"COUNTRY_OF_ORIGIN","dataType":"string"},{"name":"CLASSIFICATION","dataType":"string"},{"name":"SHIP_FROM_LOCATION_CODE","dataType":"string"},{"name":"ULTIMATE_SHIP_TO","dataType":"string"},{"name":"SHIP_FROM_ORG_CODE","dataType":"string"},{"name":"SUBINVENTORY","dataType":"string"},{"name":"LOT_NUMBER","dataType":"string"},{"name":"SERIAL_NUMBER","dataType":"string"},{"name":"TO_SERIAL_NUMBER","dataType":"string"},{"name":"LEAST_NUM_OF_SERIAL_NUMBER","dataType":"double"},{"name":"CUST_REQUESTED_QUANTITY","dataType":"double"},{"name":"CUST_REQUESTED_QUANTITY_UOM","dataType":"string"},{"name":"PICKED_QUANTITY","dataType":"double"},{"name":"SHIPPED_QUANTITY","dataType":"double"},{"name":"DELIVERED_QUANTITY","dataType":"double"},{"name":"RECEIVED_QUANTITY","dataType":"double"},{"name":"CANCELLED_QUANTITY","dataType":"double"},{"name":"SHIPPING_QUANTITY","dataType":"double"},{"name":"SHIPPING_QUANTITY_UOM","dataType":"string"},{"name":"PICK_RELEASE_STATUS_CODE","dataType":"string"},{"name":"PICK_RELEASE_STATUS","dataType":"string"},{"name":"DATE_REQUESTED","dataType":"dateTime"},{"name":"DATE_SCHEDULED","dataType":"dateTime"},{"name":"OE_INTERFACED_FLAG","dataType":"string"},{"name":"SHIP_METHOD_CODE","dataType":"string"},{"name":"FREIGHT_TERMS_CODE","dataType":"string"},{"name":"SHIPMENT_PRIORITY_CODE","dataType":"string"},{"name":"SHIPPING_INSTRUCTIONS","dataType":"string"},{"name":"PACKING_INSTRUCTIONS","dataType":"string"},{"name":"CONSIGNEE","dataType":"string"},{"name":"WAYBILL","dataType":"string"},{"name":"GROSS_WEIGHT","dataType":"double"},{"name":"NET_WEIGHT","dataType":"double"},{"name":"WEIGHT_UOM_CODE","dataType":"string"},{"name":"VOLUME","dataType":"double"},{"name":"VOLUME_UOM_CODE","dataType":"string"},{"name":"CARRIER_NAME","dataType":"string"},{"name":"NO_OF_PIECES","dataType":"string"},{"name":"UOM_OF_PIECES","dataType":"string"},{"name":"MOVE_ORDER_NUMBER","dataType":"string"},{"name":"MOVE_ORDER_LINE_NUMBER","dataType":"double"},{"name":"FREIGHT_CHARGE","dataType":"double"},{"name":"FREIGHT_CHARGE_USD","dataType":"double"},{"name":"FREIGHT_CURRENCY_CODE","dataType":"string"},{"name":"SHIP_FROM_DATE","dataType":"dateTime"},{"name":"SHIP_TO_DATE","dataType":"dateTime"},{"name":"END_CUST_USD_RATE","dataType":"double"},{"name":"PLANNER_CODE","dataType":"string"},{"name":"END_ASSEMBLY_PEGGING","dataType":"string"},{"name":"FIRST_SCHEDULE_DATE","dataType":"date"},{"name":"EXTERNAL_ORDER_NUMBER","dataType":"string"},{"name":"INTERCO_PO_NUM","dataType":"string"},{"name":"CST_CURRENCY_CODE","dataType":"string"},{"name":"PROJECT_NUMBER","dataType":"string"},{"name":"PROJECT_ID","dataType":"double"},{"name":"PROJECT_NAME","dataType":"string"},{"name":"IMPORTER_NAME","dataType":"string"},{"name":"IMPORTER_NUMBER","dataType":"string"},{"name":"IMPORTER_ADDRESS1","dataType":"string"},{"name":"IMPORTER_ADDRESS2","dataType":"string"},{"name":"IMPORTER_CITY","dataType":"string"},{"name":"IMPORTER_STATE","dataType":"string"},{"name":"IMPORTER_COUNTY","dataType":"string"},{"name":"IMPORTER_POSTAL_CODE","dataType":"string"},{"name":"IMPORTER_PROVINCE","dataType":"string"},{"name":"IMPORTER_COUNTRY_NAME","dataType":"string"},{"name":"DELIVERY_PACK_DIMENSIONS","dataType":"string"},{"name":"DELIVERY_TYPE","dataType":"string"},{"name":"MODE_OF_TRANSPORT","dataType":"string"},{"name":"ROW_CREATION_DATE","dataType":"dateTime"},{"name":"OrderNumber_OrderLine","dataType":"string"},{"name":"ReqToActual-Shipment_Days","dataType":"int64"},{"name":"PromToActual-Shipment_Days","dataType":"int64"},{"name":"SchedToActual-Shipment_Days","dataType":"int64"},{"name":"ReqToActual-Shipm_Status","dataType":"string"},{"name":"PromToActual-Shipm_Status","dataType":"string"},{"name":"SchedToActual-Shipm_Status","dataType":"string"},{"name":"Actual_Shipment_DateTime_PST","dataType":"dateTimeOffset"},{"name":"Actual_Shipment_DateTime_Local","dataType":"dateTimeOffset"},{"name":"Actual_Shipment_Date_Local","dataType":"date"}],"partitions":[{"name":"IncrementalRefreshPolicyPartition-2019","refreshTime":"2022-03-28T20:06:09.5805023+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/81c2e363-ed59-43f0-804a-3c3b1891ee63/XXCOH_MS_SHIPMENT_VIEW/part-2019.csv?snapshot=2022-03-28T20%3A06%3A09.5029245Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2019-01-01T00:00:00","end":"2020-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2020","refreshTime":"2022-03-28T20:06:21.2843146+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/81c2e363-ed59-43f0-804a-3c3b1891ee63/XXCOH_MS_SHIPMENT_VIEW/part-2020.csv?snapshot=2022-03-28T20%3A06%3A21.2491778Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2020-01-01T00:00:00","end":"2021-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2021Q1","refreshTime":"2022-03-28T20:06:02.7208462+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/81c2e363-ed59-43f0-804a-3c3b1891ee63/XXCOH_MS_SHIPMENT_VIEW/part-2021Q1.csv?snapshot=2022-03-28T20%3A06%3A02.6698493Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2021-01-01T00:00:00","end":"2021-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2021Q2","refreshTime":"2022-03-28T20:06:02.5958485+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/81c2e363-ed59-43f0-804a-3c3b1891ee63/XXCOH_MS_SHIPMENT_VIEW/part-2021Q2.csv?snapshot=2022-03-28T20%3A06%3A02.5389253Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2021-04-01T00:00:00","end":"2021-07-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2021Q3","refreshTime":"2022-04-01T05:07:04.8043181+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/81c2e363-ed59-43f0-804a-3c3b1891ee63/XXCOH_MS_SHIPMENT_VIEW/part-2021Q3.csv?snapshot=2022-04-01T05%3A07%3A04.7827538Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2021-07-01T00:00:00","end":"2021-10-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2021Q4","refreshTime":"2022-06-13T05:09:34.5951742+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/81c2e363-ed59-43f0-804a-3c3b1891ee63/XXCOH_MS_SHIPMENT_VIEW/part-2021Q4.csv?snapshot=2022-06-13T05%3A09%3A34.5612642Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2021-10-01T00:00:00","end":"2022-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q1","refreshTime":"2022-06-13T05:19:27.249359+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/81c2e363-ed59-43f0-804a-3c3b1891ee63/XXCOH_MS_SHIPMENT_VIEW/part-2022Q1.csv?snapshot=2022-06-13T05%3A19%3A27.2212731Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-01-01T00:00:00","end":"2022-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q2","refreshTime":"2022-06-13T05:11:08.5676091+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/81c2e363-ed59-43f0-804a-3c3b1891ee63/XXCOH_MS_SHIPMENT_VIEW/part-2022Q2.csv?snapshot=2022-06-13T05%3A11%3A08.3772983Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-01T00:00:00","end":"2022-07-01T00:00:00"}}]},{"$type":"LocalEntity","name":"XXREP_RESOURCE_TRAN_V","description":"","pbi:refreshPolicy":{"$type":"IncrementalRefreshPolicy","locationPattern":"XXREP_RESOURCE_TRAN_V/part.csv","rollingWindowGranularity":"year","rollingWindowPeriods":2,"incrementalGranularity":"quarter","incrementalPeriods":3},"annotations":[{"name":"pbi:IncrementalRefreshDetectChangeAttribute"},{"name":"pbi:IncrementalRefreshFilterByAttribute","value":"LAST_UPDATE_DATE"}],"attributes":[{"name":"JOB_NUMBER","dataType":"string"},{"name":"WIPJOB_ORG_KEY_CODE","dataType":"string"},{"name":"WIPJOB_ORG_KEY_ID","dataType":"string"},{"name":"JOB_TYPE","dataType":"string"},{"name":"TRANSACTION_TYPE","dataType":"string"},{"name":"TRANSACTION_DATE","dataType":"date"},{"name":"TRANSACTION_QUANTITY","dataType":"double"},{"name":"TRANSACTION_UOM","dataType":"string"},{"name":"ORGANIZATION_ID","dataType":"int64"},{"name":"LAST_UPDATE_DATE","dataType":"dateTime"},{"name":"DEPARTMENT_CODE","dataType":"string"},{"name":"RESOURCE_CODE","dataType":"string"},{"name":"ITEM_NUMBER","dataType":"string"},{"name":"PERIOD_NAME","dataType":"string"},{"name":"INVORG_CODE","dataType":"string"},{"name":"INVORG_ID","dataType":"int64"},{"name":"DEPARTMENT_DESCRIPTION","dataType":"string"}],"partitions":[{"name":"IncrementalRefreshPolicyPartition-2020","refreshTime":"2022-03-28T20:11:40.9786+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/81c2e363-ed59-43f0-804a-3c3b1891ee63/XXREP_RESOURCE_TRAN_V/part-2020.csv?snapshot=2022-03-28T20%3A11%3A40.9525907Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2020-01-01T00:00:00","end":"2021-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2021Q1","refreshTime":"2022-03-28T20:09:58.107124+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/81c2e363-ed59-43f0-804a-3c3b1891ee63/XXREP_RESOURCE_TRAN_V/part-2021Q1.csv?snapshot=2022-03-28T20%3A09%3A58.0776573Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2021-01-01T00:00:00","end":"2021-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2021Q2","refreshTime":"2022-03-28T20:09:48.4558518+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/81c2e363-ed59-43f0-804a-3c3b1891ee63/XXREP_RESOURCE_TRAN_V/part-2021Q2.csv?snapshot=2022-03-28T20%3A09%3A48.3972164Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2021-04-01T00:00:00","end":"2021-07-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2021Q3","refreshTime":"2022-04-01T05:09:37.2755219+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/81c2e363-ed59-43f0-804a-3c3b1891ee63/XXREP_RESOURCE_TRAN_V/part-2021Q3.csv?snapshot=2022-04-01T05%3A09%3A37.2511032Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2021-07-01T00:00:00","end":"2021-10-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2021Q4","refreshTime":"2022-06-13T05:12:29.7877763+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/81c2e363-ed59-43f0-804a-3c3b1891ee63/XXREP_RESOURCE_TRAN_V/part-2021Q4.csv?snapshot=2022-06-13T05%3A12%3A29.6905064Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2021-10-01T00:00:00","end":"2022-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q1","refreshTime":"2022-06-13T05:12:29.319022+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/81c2e363-ed59-43f0-804a-3c3b1891ee63/XXREP_RESOURCE_TRAN_V/part-2022Q1.csv?snapshot=2022-06-13T05%3A12%3A29.2387658Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-01-01T00:00:00","end":"2022-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q2","refreshTime":"2022-06-13T05:12:11.3488546+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/81c2e363-ed59-43f0-804a-3c3b1891ee63/XXREP_RESOURCE_TRAN_V/part-2022Q2.csv?snapshot=2022-06-13T05%3A12%3A11.2311299Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-01T00:00:00","end":"2022-07-01T00:00:00"}}]},{"$type":"LocalEntity","name":"XXREP_WW_OMTRX_DATAMART_V","description":"","pbi:refreshPolicy":{"$type":"IncrementalRefreshPolicy","locationPattern":"XXREP_WW_OMTRX_DATAMART_V/part.csv","rollingWindowGranularity":"year","rollingWindowPeriods":2,"incrementalGranularity":"quarter","incrementalPeriods":3},"annotations":[{"name":"pbi:IncrementalRefreshDetectChangeAttribute"},{"name":"pbi:IncrementalRefreshFilterByAttribute","value":"LAST_UPDATE_DATE"}],"attributes":[{"name":"REGION","dataType":"string"},{"name":"OU","dataType":"string"},{"name":"ORDERED_QUANTITY","dataType":"double"},{"name":"FIRST_SCHEDULE_DATE","dataType":"date"},{"name":"HEADER_ORDERED_DATE","dataType":"dateTime"},{"name":"HEADER_CREATION_DATE","dataType":"dateTime"},{"name":"HEADER_BOOK_DATE","dataType":"date"},{"name":"BOOKING_OFFICE","dataType":"string"},{"name":"REPORTING_ENTITY","dataType":"string"},{"name":"ORDER_TYPE","dataType":"string"},{"name":"SCHEDULE_SHIP_DATE","dataType":"date"},{"name":"REQUEST_SHIP_DATE","dataType":"date"},{"name":"ORDER_NUMBER","dataType":"int64"},{"name":"TECHNICAL_BUSINESS_UNIT","dataType":"string"},{"name":"WAREHOUSE","dataType":"string"},{"name":"ORDER_LINE","dataType":"string"},{"name":"ITEM_NUMBER","dataType":"string"},{"name":"ORDER_STATUS","dataType":"string"},{"name":"LINE_STATUS","dataType":"string"},{"name":"CUSTOMER_NAME","dataType":"string"},{"name":"CUSTOMER_TYPE","dataType":"string"},{"name":"CUSTOMER_CLASS","dataType":"string"},{"name":"SHIP_TO_COUNTRY","dataType":"string"},{"name":"SO_LINE_TYPE","dataType":"string"},{"name":"ACTUAL_SHIPMENT_DATE","dataType":"date"},{"name":"FISCAL_PERIOD_HEADER_BOOKED","dataType":"string"},{"name":"FISCAL_YEAR_HEADER_BOOKED","dataType":"int64"},{"name":"SCHEDULED_VS_SHIP_DAYS","dataType":"double"},{"name":"FORECAST_FIELD","dataType":"string"},{"name":"SUBINVENTORY","dataType":"string"},{"name":"LINE_CREATION_DATE","dataType":"date"},{"name":"BOOKED_DATE","dataType":"date"},{"name":"BACKLOG_QUANTITY","dataType":"double"},{"name":"PROMISE_SHIP_DATE","dataType":"date"},{"name":"LAST_UPDATE_DATE","dataType":"dateTime"},{"name":"ORDER_LAST_UPDATE_DATE","dataType":"date"},{"name":"SHIP_FROM_ORG_ID","dataType":"int64"},{"name":"ITEM_STATUS","dataType":"string"},{"name":"PLANNER_CODE","dataType":"string"},{"name":"END_CUST_NAME","dataType":"string"},{"name":"OU_ORDER_LINE","dataType":"string"},{"name":"PERIOD_NAME","dataType":"string"},{"name":"Actual_Shipment_DateTime_PST","dataType":"dateTimeOffset"},{"name":"Actual_Shipment_DateTime_Local","dataType":"dateTimeOffset"},{"name":"Actual_Shipment_Date_Local","dataType":"date"}],"partitions":[{"name":"IncrementalRefreshPolicyPartition-2020","refreshTime":"2022-03-28T20:08:14.9727099+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/81c2e363-ed59-43f0-804a-3c3b1891ee63/XXREP_WW_OMTRX_DATAMART_V/part-2020.csv?snapshot=2022-03-28T20%3A08%3A14.9178964Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2020-01-01T00:00:00","end":"2021-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2021Q1","refreshTime":"2022-03-28T20:06:44.1721506+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/81c2e363-ed59-43f0-804a-3c3b1891ee63/XXREP_WW_OMTRX_DATAMART_V/part-2021Q1.csv?snapshot=2022-03-28T20%3A06%3A44.1330346Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2021-01-01T00:00:00","end":"2021-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2021Q2","refreshTime":"2022-03-28T20:06:48.8636436+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/81c2e363-ed59-43f0-804a-3c3b1891ee63/XXREP_WW_OMTRX_DATAMART_V/part-2021Q2.csv?snapshot=2022-03-28T20%3A06%3A48.8183435Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2021-04-01T00:00:00","end":"2021-07-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2021Q3","refreshTime":"2022-04-01T05:09:39.7325025+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/81c2e363-ed59-43f0-804a-3c3b1891ee63/XXREP_WW_OMTRX_DATAMART_V/part-2021Q3.csv?snapshot=2022-04-01T05%3A09%3A39.7146872Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2021-07-01T00:00:00","end":"2021-10-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2021Q4","refreshTime":"2022-06-13T05:10:01.3614705+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/81c2e363-ed59-43f0-804a-3c3b1891ee63/XXREP_WW_OMTRX_DATAMART_V/part-2021Q4.csv?snapshot=2022-06-13T05%3A10%3A00.5423193Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2021-10-01T00:00:00","end":"2022-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q1","refreshTime":"2022-06-13T05:10:02.5802335+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/81c2e363-ed59-43f0-804a-3c3b1891ee63/XXREP_WW_OMTRX_DATAMART_V/part-2022Q1.csv?snapshot=2022-06-13T05%3A10%3A02.3672690Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-01-01T00:00:00","end":"2022-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q2","refreshTime":"2022-06-13T05:10:24.966094+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/81c2e363-ed59-43f0-804a-3c3b1891ee63/XXREP_WW_OMTRX_DATAMART_V/part-2022Q2.csv?snapshot=2022-06-13T05%3A10%3A22.4317273Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-01T00:00:00","end":"2022-07-01T00:00:00"}}]}]}