{"name":"Flow_DIMs","description":"Flow for dimensional tables.","version":"1.0","culture":"en-US","modifiedTime":"2022-06-18T15:24:34.6232139+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":true,"queriesMetadata":{"parDateRange":{"queryId":"75172583-34f2-4e0c-aedd-548a0c26f299","queryName":"parDateRange"},"XX_INVORG_DIM":{"queryId":"d079f5be-6201-4a73-95e8-db4d248068c0","queryName":"XX_INVORG_DIM","loadEnabled":true}},"document":"section Section1;\r\n[Description = \"Parameter for date range in days, data to load.\"]\r\nshared parDateRange = let\n    Parameter1 = 740 meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type number]\nin\n    Parameter1;\r\nshared XX_INVORG_DIM = let\n    Source = Value.NativeQuery(Snowflake.Databases(\"mma12090.snowflakecomputing.com\",\"COMPUTE_REPORTING\",[Role=\"GLBMFGOPERATIONSROLE\"]){[Name=\"PROD_DB\"]}[Data], \"SELECT * FROM PROD_DB.XXDIMS.XX_INVORG_DIM\", null, [EnableFolding=true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(Source, {{\"INVORG_ID\", Int64.Type}, {\"OPERATING_UNIT_ID\", Int64.Type}, {\"LEDGER_ID\", Int64.Type}, {\"CREATION_DATE\", type date}}),\r\n  #\"Choose columns\" = Table.SelectColumns(#\"Changed column type\", {\"INVORG_ID\", \"OPERATING_UNIT_ID\", \"LEDGER_ID\", \"GL_ENTITY\", \"OPERATING_UNIT\", \"LEDGER\", \"INVORG_CODE\", \"CURRENCY_CODE\", \"INVORG_CATEGORY\", \"INV_ORG_CODE_CUSTOWNED\", \"TIMEZONE\", \"DISABLE_DATE\", \"CREATION_DATE\", \"LAST_UPDATE_DATE\", \"INVORG_GROUP\", \"LABOR_TARGET_PCT\", \"BASELINE_FYFQ\", \"COUNTRY_CODE\", \"INVORG_TYPE\", \"REPORTING_PRODUCT_GROUP\", \"REPORTING_OWNED_BY\"})\nin\n    #\"Choose columns\";\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"XX_INVORG_DIM","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"XX_INVORG_DIM.csv"},"attributes":[{"name":"INVORG_ID","dataType":"int64"},{"name":"OPERATING_UNIT_ID","dataType":"int64"},{"name":"LEDGER_ID","dataType":"int64"},{"name":"GL_ENTITY","dataType":"string"},{"name":"OPERATING_UNIT","dataType":"string"},{"name":"LEDGER","dataType":"string"},{"name":"INVORG_CODE","dataType":"string"},{"name":"CURRENCY_CODE","dataType":"string"},{"name":"INVORG_CATEGORY","dataType":"string"},{"name":"INV_ORG_CODE_CUSTOWNED","dataType":"string"},{"name":"TIMEZONE","dataType":"string"},{"name":"DISABLE_DATE","dataType":"date"},{"name":"CREATION_DATE","dataType":"date"},{"name":"LAST_UPDATE_DATE","dataType":"dateTime"},{"name":"INVORG_GROUP","dataType":"string"},{"name":"LABOR_TARGET_PCT","dataType":"double"},{"name":"BASELINE_FYFQ","dataType":"string"},{"name":"COUNTRY_CODE","dataType":"string"},{"name":"INVORG_TYPE","dataType":"string"},{"name":"REPORTING_PRODUCT_GROUP","dataType":"string"},{"name":"REPORTING_OWNED_BY","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-18T15:24:47.787179+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/fac44c74-04bb-4751-9c78-49cd2a78aa6c/XX_INVORG_DIM.csv?snapshot=2022-06-18T15%3A24%3A47.7680236Z"}]}]}