{"name":"Test_Snowflake","description":"Test flow for Snowflake data.","version":"1.0","culture":"en-US","modifiedTime":"2022-03-06T13:19:06.8547633+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":true,"queriesMetadata":{"COHR_WH":{"queryId":"2185a891-1041-48b8-bef2-2c73878039a8","queryName":"COHR_WH"},"WIP_TRANSACTIONS":{"queryId":"4c9e1a49-cf79-446c-a696-cc7a242c9538","queryName":"WIP_TRANSACTIONS"},"WIP_TRANSACTIONS (2)":{"queryId":"6e568bf3-cd43-4b73-8e7d-27afc1c4007c","queryName":"WIP_TRANSACTIONS (2)"},"WIP_DISCRETE_JOBS_V":{"queryId":"bb402bec-a75f-4bdb-ab0e-02a573da463b","queryName":"WIP_DISCRETE_JOBS_V","loadEnabled":true},"RangeStart":{"queryId":"02231d1f-a8cc-4a46-a2d8-1e3fb6206ef9","queryName":"RangeStart"},"RangeEnd":{"queryId":"29501e04-a20c-4332-92f9-152fea54d163","queryName":"RangeEnd"}},"document":"section Section1;\r\n\r\nshared COHR_WH = let\r\n    Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n    #\"Navigation 1\" = Source{[Name = \"COHR_WH\", Kind = \"Database\"]}[Data]\r\nin\r\n    #\"Navigation 1\";\r\n\r\nshared WIP_TRANSACTIONS = let\r\n    Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n    #\"Navigation 1\" = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n    #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"WIP\", Kind = \"Schema\"]}[Data],\r\n    #\"Navigation 3\" = #\"Navigation 2\"{[Name = \"WIP_TRANSACTIONS\", Kind = \"Table\"]}[Data],\r\n    #\"Filtered rows\" = Table.SelectRows(#\"Navigation 3\", each Date.IsInPreviousNDays([TRANSACTION_DATE], 740)),\r\n    #\"Choose columns\" = Table.SelectColumns(#\"Filtered rows\", {\"TRANSACTION_ID\", \"ORGANIZATION_ID\", \"WIP_ENTITY_ID\", \"PRIMARY_ITEM_ID\", \"DEPARTMENT_ID\", \"TRANSACTION_TYPE\", \"TRANSACTION_DATE\", \"RESOURCE_ID\", \"TRANSACTION_QUANTITY\", \"TRANSACTION_UOM\"})\r\nin\r\n    #\"Choose columns\";\r\n\r\nshared #\"WIP_TRANSACTIONS (2)\" = let\r\n    Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n    #\"Navigation 1\" = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n    Navigation = #\"Navigation 1\"{[Kind = \"Schema\", Name = \"APPS\"]}[Data],\r\n    #\"Navigation 2\" = Navigation{[Name = \"XXREP_RESOURCE_TRAN_V\", Kind = \"View\"]}[Data],\r\n    #\"Filtered rows\" = Table.SelectRows(#\"Navigation 2\", each Date.IsInPreviousNDays([TRANSACTION_DATE], 30))\r\nin\r\n    #\"Filtered rows\";\r\n\r\nshared WIP_DISCRETE_JOBS_V = let\r\n    Source = Value.NativeQuery(Snowflake.Databases(\"mma12090.snowflakecomputing.com\",\"COMPUTE_REPORTING\",[Role=\"GLBMFGOPERATIONSROLE\"]){[Name=\"PROD_DB\"]}[Data], \"SELECT *#(lf)FROM PROD_DB.APPS.WIP_DISCRETE_JOBS_V\", null, [EnableFolding=true]),\r\n    #\"WIP_DISCRETE_JOBS_V-4C4153545F5550444154455F44415445-autogenerated_for_incremental_refresh\" = Table.SelectRows(Source, each DateTime.From([LAST_UPDATE_DATE]) >= RangeStart and DateTime.From([LAST_UPDATE_DATE]) < RangeEnd)\r\nin\r\n    #\"WIP_DISCRETE_JOBS_V-4C4153545F5550444154455F44415445-autogenerated_for_incremental_refresh\";\r\n\r\nshared RangeStart = let RangeStart = #datetime(0001,01,01,00,00,00) meta [IsParameterQuery=true, List={}, Type=\"DateTime\", IsParameterQueryRequired=true, Description=\"autogenerated_for_incremental_refresh\"] in RangeStart;\r\n\r\nshared RangeEnd = let RangeEnd = #datetime(9999,12,31,23,59,59) meta [IsParameterQuery=true, List={}, Type=\"DateTime\", IsParameterQueryRequired=true, Description=\"autogenerated_for_incremental_refresh\"] in RangeEnd;\r\n\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"WIP_DISCRETE_JOBS_V","description":"","pbi:refreshPolicy":{"$type":"IncrementalRefreshPolicy","locationPattern":"WIP_DISCRETE_JOBS_V/part.csv","rollingWindowGranularity":"year","rollingWindowPeriods":2,"incrementalGranularity":"month","incrementalPeriods":1},"annotations":[{"name":"pbi:IncrementalRefreshDetectChangeAttribute"},{"name":"pbi:IncrementalRefreshFilterByAttribute","value":"LAST_UPDATE_DATE"}],"attributes":[{"name":"WIP_ENTITY_ID","dataType":"double"},{"name":"WIP_ENTITY_NAME","dataType":"string"},{"name":"ORGANIZATION_ID","dataType":"double"},{"name":"LAST_UPDATE_DATE","dataType":"dateTime"},{"name":"LAST_UPDATED_BY","dataType":"double"},{"name":"CREATION_DATE","dataType":"dateTime"},{"name":"CREATED_BY","dataType":"double"},{"name":"LAST_UPDATE_LOGIN","dataType":"double"},{"name":"REQUEST_ID","dataType":"double"},{"name":"PROGRAM_APPLICATION_ID","dataType":"double"},{"name":"PROGRAM_ID","dataType":"double"},{"name":"PROGRAM_UPDATE_DATE","dataType":"dateTime"},{"name":"DESCRIPTION","dataType":"string"},{"name":"STATUS_TYPE","dataType":"double"},{"name":"PRIMARY_ITEM_ID","dataType":"double"},{"name":"FIRM_PLANNED_FLAG","dataType":"double"},{"name":"JOB_TYPE","dataType":"double"},{"name":"JOB_TYPE_MEANING","dataType":"string"},{"name":"WIP_SUPPLY_TYPE","dataType":"double"},{"name":"CLASS_CODE","dataType":"string"},{"name":"MATERIAL_ACCOUNT","dataType":"double"},{"name":"MATERIAL_OVERHEAD_ACCOUNT","dataType":"double"},{"name":"RESOURCE_ACCOUNT","dataType":"double"},{"name":"OUTSIDE_PROCESSING_ACCOUNT","dataType":"double"},{"name":"MATERIAL_VARIANCE_ACCOUNT","dataType":"double"},{"name":"RESOURCE_VARIANCE_ACCOUNT","dataType":"double"},{"name":"OUTSIDE_PROC_VARIANCE_ACCOUNT","dataType":"double"},{"name":"STD_COST_ADJUSTMENT_ACCOUNT","dataType":"double"},{"name":"OVERHEAD_ACCOUNT","dataType":"double"},{"name":"OVERHEAD_VARIANCE_ACCOUNT","dataType":"double"},{"name":"SCHEDULED_START_DATE","dataType":"dateTime"},{"name":"DATE_RELEASED","dataType":"dateTime"},{"name":"SCHEDULED_COMPLETION_DATE","dataType":"dateTime"},{"name":"DATE_COMPLETED","dataType":"dateTime"},{"name":"DATE_CLOSED","dataType":"dateTime"},{"name":"START_QUANTITY","dataType":"double"},{"name":"QUANTITY_REMAINING","dataType":"double"},{"name":"QUANTITY_COMPLETED","dataType":"double"},{"name":"QUANTITY_SCRAPPED","dataType":"double"},{"name":"NET_QUANTITY","dataType":"double"},{"name":"BOM_REFERENCE_ID","dataType":"double"},{"name":"ROUTING_REFERENCE_ID","dataType":"double"},{"name":"COMMON_BOM_SEQUENCE_ID","dataType":"double"},{"name":"COMMON_ROUTING_SEQUENCE_ID","dataType":"double"},{"name":"BOM_REVISION","dataType":"string"},{"name":"ROUTING_REVISION","dataType":"string"},{"name":"BOM_REVISION_DATE","dataType":"dateTime"},{"name":"ROUTING_REVISION_DATE","dataType":"dateTime"},{"name":"LOT_NUMBER","dataType":"string"},{"name":"ALTERNATE_BOM_DESIGNATOR","dataType":"string"},{"name":"ALTERNATE_ROUTING_DESIGNATOR","dataType":"string"},{"name":"COMPLETION_SUBINVENTORY","dataType":"string"},{"name":"COMPLETION_LOCATOR_ID","dataType":"double"},{"name":"SUB_LOCATOR_CONTROL","dataType":"double"},{"name":"DEMAND_CLASS","dataType":"string"},{"name":"SCHEDULE_GROUP_NAME","dataType":"string"},{"name":"SCHEDULE_GROUP_ID","dataType":"double"},{"name":"BUILD_SEQUENCE","dataType":"double"},{"name":"LINE_CODE","dataType":"string"},{"name":"LINE_ID","dataType":"double"},{"name":"PROJECT_NAME","dataType":"string"},{"name":"PROJECT_NUMBER","dataType":"string"},{"name":"PROJECT_ID","dataType":"double"},{"name":"TASK_ID","dataType":"double"},{"name":"END_ITEM_UNIT_NUMBER","dataType":"string"},{"name":"ATTRIBUTE_CATEGORY","dataType":"string"},{"name":"ATTRIBUTE1","dataType":"string"},{"name":"ATTRIBUTE2","dataType":"string"},{"name":"ATTRIBUTE3","dataType":"string"},{"name":"ATTRIBUTE4","dataType":"string"},{"name":"ATTRIBUTE5","dataType":"string"},{"name":"ATTRIBUTE6","dataType":"string"},{"name":"ATTRIBUTE7","dataType":"string"},{"name":"ATTRIBUTE8","dataType":"string"},{"name":"ATTRIBUTE9","dataType":"string"},{"name":"ATTRIBUTE10","dataType":"string"},{"name":"ATTRIBUTE11","dataType":"string"},{"name":"ATTRIBUTE12","dataType":"string"},{"name":"ATTRIBUTE13","dataType":"string"},{"name":"ATTRIBUTE14","dataType":"string"},{"name":"ATTRIBUTE15","dataType":"string"},{"name":"STATUS_TYPE_DISP","dataType":"string"},{"name":"WIP_SUPPLY_TYPE_DISP","dataType":"string"},{"name":"OVERCOMPLETION_TOLERANCE_TYPE","dataType":"double"},{"name":"OVERCOMPLETION_TOLERANCE_VALUE","dataType":"double"},{"name":"KANBAN_CARD_ID","dataType":"double"},{"name":"KANBAN_CARD_NUMBER","dataType":"string"},{"name":"PO_CREATION_TIME","dataType":"double"},{"name":"PRIORITY","dataType":"double"},{"name":"DUE_DATE","dataType":"dateTime"},{"name":"EST_SCRAP_ACCOUNT","dataType":"double"},{"name":"EST_SCRAP_VAR_ACCOUNT","dataType":"double"},{"name":"ENTITY_TYPE","dataType":"double"},{"name":"DUE_DATE_PENALTY","dataType":"double"},{"name":"DUE_DATE_TOLERANCE","dataType":"double"},{"name":"COPRODUCTS_SUPPLY","dataType":"double"},{"name":"REQUESTED_START_DATE","dataType":"dateTime"},{"name":"SERIALIZATION_START_OP","dataType":"double"},{"name":"ACTUAL_START_DATE","dataType":"dateTime"},{"name":"EXPECTED_HOLD_RELEASE_DATE","dataType":"dateTime"}],"partitions":[{"name":"IncrementalRefreshPolicyPartition-2020","refreshTime":"2022-03-06T13:20:43.3949857+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/3cdce573-f5aa-4c9d-989c-57dd36dffa12/WIP_DISCRETE_JOBS_V/part-2020.csv?snapshot=2022-03-06T13%3A20%3A43.3542912Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2020-01-01T00:00:00","end":"2021-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2021","refreshTime":"2022-03-06T13:20:54.7370445+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/3cdce573-f5aa-4c9d-989c-57dd36dffa12/WIP_DISCRETE_JOBS_V/part-2021.csv?snapshot=2022-03-06T13%3A20%3A54.7176953Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2021-01-01T00:00:00","end":"2022-01-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q1","refreshTime":"2022-04-03T19:02:21.2516981+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/3cdce573-f5aa-4c9d-989c-57dd36dffa12/WIP_DISCRETE_JOBS_V/part-2022Q1.csv?snapshot=2022-04-10T19%3A01%3A08.3037012Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-01-01T00:00:00","end":"2022-04-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q204","refreshTime":"2022-05-01T19:01:31.2212173+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/3cdce573-f5aa-4c9d-989c-57dd36dffa12/WIP_DISCRETE_JOBS_V/part-2022Q204.csv?snapshot=2022-05-01T19%3A01%3A31.2113956Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-04-01T00:00:00","end":"2022-05-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q205","refreshTime":"2022-06-05T19:02:07.5818713+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/3cdce573-f5aa-4c9d-989c-57dd36dffa12/WIP_DISCRETE_JOBS_V/part-2022Q205.csv?snapshot=2022-06-05T19%3A02%3A07.5090651Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-05-01T00:00:00","end":"2022-06-01T00:00:00"}},{"name":"IncrementalRefreshPolicyPartition-2022Q206","refreshTime":"2022-06-12T19:01:27.249871+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/3cdce573-f5aa-4c9d-989c-57dd36dffa12/WIP_DISCRETE_JOBS_V/part-2022Q206.csv?snapshot=2022-06-12T19%3A01%3A27.2138082Z","pbi:source":{"$type":"RangePolicyPartitionSource","start":"2022-06-01T00:00:00","end":"2022-07-01T00:00:00"}}]}]}