{"name":"Manual_Reference1","description":"","version":"1.0","culture":"en-US","modifiedTime":"2021-03-19T04:06:54.1738466+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":true,"queriesMetadata":{"APOP_Quadrant":{"queryId":"c8bf1688-1d37-4b59-a43c-7ee31d00b1bd","queryName":"APOP_Quadrant","loadEnabled":true},"Replenishment_Method":{"queryId":"781ed36e-62ba-4b9f-b790-893fb299c25d","queryName":"Replenishment_Method","loadEnabled":true},"Country_Region":{"queryId":"175a49e2-741d-4b8f-9e26-704ce0d1982a","queryName":"Country_Region","loadEnabled":true},"ABC_Class":{"queryId":"d9fce7a7-069f-4d4e-a19c-3093baa5880e","queryName":"ABC_Class","loadEnabled":true}},"document":"section Section1;\r\nshared APOP_Quadrant = let\r\n  Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"jZHBCsIwDIZfpew8oU6dehWZDJmKHscOZQtScO3o6kGf3jrS2ioDD38bSP/kS1qW0WQaxZHVTsoGw4MUgOEWagWsBz+sYrRSo9k/1gtrPdtwpEYZ48pciVGRC97yJ5CT4jWQXDhvGpZymXc5iq2SUYih8xc7RfRFiPDrctjUUq+MNqzBuc8g4Co1ZxqIlmQP0CF/dmMan2OtgNvufD5K4C0gYLdrXwYgBe97aMix66TSd8H1A594Zdww7gvWY8NgzjN/6KsX\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Qty Sign\" = _t, #\"Price Sign\" = _t, #\"Quadrant ID\" = _t, Rating = _t, #\"Rating Sort\" = _t, Action = _t, #\"Action Sort\" = _t, #\"Quantity Group\" = _t, #\"Price Group\" = _t]),\r\n  #\"Changed Type\" = Table.TransformColumnTypes(Source, {{\"Qty Sign\", Int64.Type}, {\"Price Sign\", Int64.Type}, {\"Quadrant ID\", Int64.Type}})\r\nin\r\n  #\"Changed Type\";\r\nshared Replenishment_Method = let\r\n  Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45W8g0KUNJRMlSK1YlW8k7MS0rMA3KNwVzfzDwF38QKIN8IzA/z9QSyTcBsv/wShYCcxLy81BSgmClEzBHINFOKjQUA\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Replenishment Method\" = _t, Sort = _t])\r\nin\r\n  Source;\r\nshared Country_Region = let\r\n  Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"hVrNkuI4En4VR59qIrpjJ/awewZjDIVt3LaBLmbnIEANmjJWjbCrhnqjue8bzItt5idXNagY7eXr6FJKTuV/pvjll0+D7/uDaNSpFc2nz58GY0DMeFIi+E/388///FeQi636rraffv1MG2rR7ILpif85Md03hmRAGHVGP8meakOnCiwBhu76Xhqsj9YA3j8wYhOUrWjlyRIdiWYrmqAUR42zSkDqY6/ZaWNAPGLIRs6Hm72usTxniIHf+TNvy52qLcEUwIyVumsP/0hEq5qgZ6qnboXZtvxfIv3KUA28zLVq34mAJTgUZtPtsBHirmLfh8xe0t4G5AXAT36UvfQhqyJ1hGC6DVZXDMOV76ju1BpR28MWgNJ3Qya3xBWIK+fLr9JshPrNWtsaEHnOG4qDOAq2syF/djgpPbwSsRGqAR2guGFUQ9Hsa7GTpwOTsHUM45GXA2J4p8ECG/GwGPpYkLUwHYgfGJLi+v60vlfdkZciQPJhXb1KXllj+9r7rcZe9h4nZdeWPJTmaO1rmAJYeZk27eH6kENnXX9YATKfKHStnqHc4RyQ+LjTJzJBmPpEmle518/WfofsIcPpxLm4bk8vwhKsAAPnPrp7lm0feJhgCah8LBjxqmroDOBz5aFRrTodgqUye1r6Ed+WMcCJX2/k02anKEDNt5Kwkob+rM2ZaKdzQOUTp+kaqYIRG8xJ1AJWkYFTrxa6ei+sjw1jgGtjnXkkUQdjcdK8Pga44uzo6zsFVcARptfroThu9A5fmU0AvqhL1NJozXYUpoDCPa4RMMZwAMhuGmMonmSwlGbHHhCygsN86R50PopL/czYz8KH1KPbkGInxbDAHtMEhXzqNjWxThvHYGfsfOSgarDABh5OfGZOpDDaMAOpT3ET3eyDGcHnoBwUwdvOyQzgy7mp2Ap9vStl+0oHoU8pB0N5naLnD6cJvwEK3y691afgbiYpEjX7ny4kHYaAmXdzrY8bWE04B3hlp4/aILLOYDTz9Ea8DklgOrhjX34Vz5Sb5U9MG2ND7OiNaT8T86o5HcRJgHIEypFLqR8vrzYDkf9qVCMFhc31YQGY+i73139bGexw0r+nz1oZWNQU4Bq10bQfxlAAltceHZ6fbFIJrbHnzvKr3B6urHoNiK7JRrI5CvNIfxzxRUfZzFn/TW3oMhwTRveA6Q19jPRRNVYKoxTgC6tv1FdON5oDfC4bbTtKuoYZDAELH/H+/NQyVQx4uMF1VFMRWT/3Z5Ys3zJZ+s78vRMUyhWFjbhTjeT7xlzhxdnXa+VFFPMN1iME4sKJpNGp1bYYi6CQ0imJovag9JMlwFI1uT5gLOrHy6I7uEvpKhQGTmzfY9biOJl57jIWRssLax+z/MfF/JqPsWr6KDGeAjJn3YhmK7ETMHCXZUNWSMKyWTzmmBovxj6+7JZc1+dGniCBnOnzh7HHEftdOFSaH1lXSb5bha2V74BYbJCp4gFgeC3tWPQBLE4B7rLUVCBgPQI4Uoyp7BINVwCjCLBw1g+9eCYAJyvHakOJipoKXpwCnMIjNlJCC8j6cRF+XH5TY5yAIvlA0adilL1xMfJoKCYvlLXunvDFHIfmfvpWHgX6p7gC+Lw87kiBJ8nSimPAg8Psu+tlEIZT49rlL0NF9VPHBCuQuirrzr3MH2CSDx6OJkIhAE4qgC/AT6QwO9S36XanG1FfdsWoliapr7GYkNkHpZTB3VK0CJGhas82aLFjLwcAJ1pQEbHrDDoiFBuTzKe/SddQrcjynSwAjk9Pt7I3lmkJcIwF5S0vZADfdYhUv3nxdATwFUNTiiafIbCj2r4nh0B/550FwL/9nfEIxC7jp1rSYUGK3maaAtzLn4yQ3B5ME9zdKaOnrahRyVcAJ9zdU1tqs+A9H34/8Nn5vXgCH/c5wHexe2msQ9xHAMch7rXZ2aPmgFsd7ky8isdDP9GZcSkws53233xyJpsz6vwI4PjYTBm1EXCK2RTgqx5nmlJhcIfSno14xjfOC19h1W+B7LCFz5/NvV/pXshPmWwFqG5J4Wz259c3KcQAnxQSoYN8xF/FLCux86G/JW5tI4waIlk6xpHIjWiQYzD3StDVuQwm8qTbA3doSQlwRlGJ2vQjMgwRkmHxYR1qSx6weqvqSRQVhq1sTq3EpCCZApy6MFHtoeundUkFcJJW0v0hqR3szJ5XF4Bv1yTUosgd1zmfHWdOZ4CRS74Te3HaItOlrJ105BTzVOSIFza7dAWYflw+23CTPgB8cymi3qlnVAjpEl9b+qlbHMzSSJPK5d1Qd1HXF+E+nQAS75mGwoL6veNUmn7F6V89MSMVHZU1vVrQTqfFLTu3dArtAWY8qR3QXUrqrNuWP/uA+wAv1+Ufast2mLJO0+ibjyu1NTbMfw7GcicN8bHr2bH6HnMgHHtntKmud/oZ9xoBHPdJKZtahkLA/MPyXtuJJEJ6mnl7Z92QB8i9wYER6KMPB7YnqiIFh5S0BBQ+IVDXurUMDgC3onCqX7mS7PXNkSedrx3BU11ytB6QAnwxL6NEaQvTbABIrw/LyA64BsoKwMJ3lHwSnPeyHOCz2kxykf1m5lkCcHz5gibgCTe16HgYQNDLfAO6TL4Eoaht4OCjQ4CfoZdgLUWf/LM1wLuBPmbEvsP5U0DoY0ntJWsENpJFTszFqmU1Bjj1O+W977p+/DFwycYAX/5DruRGJuWpXiMuw0oOc839u18E1wvZHOAUMbl4fHvbyZmJfOBjJSe5sg3lHHHzZOUnlScOaM7cMy8B0Q2PyOlyRzR5A0DmUUMunjoRsLLfW4CcJZ57fT23mgYfnBPywlfr5wdVq6cnOp5lnU8APlPKVbsVykCYzHwe+io5amutDcDB8rlToeak9m4PP8wr8OqkmZyao1bzxEljGeBrSL4K2zh+HQBuJYtCdo1CYVJEAF+YKPSxTz8YFRRzpyooutOJ1d/ngf7cBaB0SF9IFDhpBXDcphSqab8MKUMe/vqzlkdW4DAB+MpqbAsmspZo78oJILtxdjBTbXtCs5bJZ4WRYwbwDa/s1qTb2tIoBPzfDV9spg/u+kHFE/2X69p0jFzhG4jYD+aK/EnazpLzRw3B5pAE8OPg3G5cqmYr6V/eadv83raXIcAXit+eWFclwJe+S2FjVcN2CcoydcJOScV0pY/2EjmRbhVGCJh9lVXuqqjbqYBtFYIuIWL72OjYb8mZHD5TInq4zUopjT2jwDth4QxPSnneHmSfn0qkgYfQOYGFL4JEUpXD65hfJ5FLRG31k8ZEt8RDbOyL0WVN1c6jvRvmdEtn8soE/YNtCQ9fOq1qyXN1ffnsUeIVEu3F336W/NeWSWgtypvjddhD/zJCy3iHX7vvIZaoH31Bp5Sx7AQuIGvYvSiy8x+8xRB+7Huq7fd2tpktQVo6M/ryyT7mRggmpTP0Lo0KEtE8wjVnAN/T+/unMC4Z3WrISiqkKUNBqSj/Fr4isHwW9eZtAnQPlzjLKw3dA5yn9/KF3yRtYijxurtyqsLyheIpWI2wHLkHqPbVlluf+MUJ4NKcuZKAR/3oxu7w159g9ABftVkJ9cIDmote7v3pqVoBfLmvEr+p98Kjugf4Co9KNK8CzeOiUdxRXPeQ1RrgZI3qIN4kiZF5NfEZQKWO2nyhphudUJUAfC1jpR+lLYeqGcBXGlTUk0A2c4BXNmRlaies4VR6I/YcR6sKMPdYXEW52za8eKWvFreMuOrMI+ZHVQEaJzDzMv825E01KW7mi/a8w2bOUCh+Gvxh4VUI8GXEqiM3gQyXYMfXdS/2fZGwiAGOuheP/OMOVt6CVxYz52q95UAg0VEZiIROQOwubhWk/Y4ZRfOd5td3vPLHw9sHvze57xckJkoAGrIPSXlRUv5utAnmXVuf6SMXolukgKlPHKbra1lMrBfeWnbxupHvDrdYA3y5YSmaTrSsmOUC4PuhwpKy7ivVISK4w09A0Ke8uyhm1RHAV9EvlWyDDD9yQHZbZj6ru/4ZBoUFFvRyCvBF5ZWoa2XNddy13VU3teKstkp8T0MrDg+Gf3B2EPgRWYSfqZTOi9yDPCJCP0SAW3l1/faMtE4BzpvEWh03YvPC1rxeAS5LjF//Bw==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Country Name\" = _t, #\"Country 2 Digits\" = _t, #\"Country 3 Digits\" = _t, Region = _t]),\r\n  #\"Changed Type\" = Table.TransformColumnTypes(Source, {{\"Country Name\", type text}, {\"Country 2 Digits\", type text}, {\"Country 3 Digits\", type text}, {\"Region\", type text}})\r\nin\r\n  #\"Changed Type\";\r\nshared ABC_Class = let\r\n  Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WMlTSUXJUitWJVjICspzALGMgyxnMMgGyXCMCwGwzINsvv0TBsaAgJzM5MSknFSxsCtKWk5iXrRQbCwA=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Sort Order\" = _t, #\"ABC-EXP Class\" = _t]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(Source, {{\"Sort Order\", Int64.Type}}),\r\n  #\"Sorted rows\" = Table.Sort(#\"Changed column type\", {{\"Sort Order\", Order.Ascending}})\r\nin\r\n  #\"Sorted rows\";\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"APOP_Quadrant","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"APOP_Quadrant.csv"},"attributes":[{"name":"Qty Sign","dataType":"int64"},{"name":"Price Sign","dataType":"int64"},{"name":"Quadrant ID","dataType":"int64"},{"name":"Rating","dataType":"string"},{"name":"Rating Sort","dataType":"string"},{"name":"Action","dataType":"string"},{"name":"Action Sort","dataType":"string"},{"name":"Quantity Group","dataType":"string"},{"name":"Price Group","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2021-03-19T04:07:57.5847735+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/c8454994-3560-4488-9782-198736fc771d/APOP_Quadrant.csv?snapshot=2021-05-17T10%3A37%3A32.7008552Z"}]},{"$type":"LocalEntity","name":"Replenishment_Method","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Replenishment_Method.csv"},"attributes":[{"name":"Replenishment Method","dataType":"string"},{"name":"Sort","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2021-03-19T04:08:28.5890528+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/c8454994-3560-4488-9782-198736fc771d/Replenishment_Method.csv?snapshot=2021-05-17T10%3A37%3A32.7318777Z"}]},{"$type":"LocalEntity","name":"Country_Region","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Country_Region.csv"},"attributes":[{"name":"Country Name","dataType":"string"},{"name":"Country 2 Digits","dataType":"string"},{"name":"Country 3 Digits","dataType":"string"},{"name":"Region","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2021-03-19T04:08:59.6158745+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/c8454994-3560-4488-9782-198736fc771d/Country_Region.csv?snapshot=2021-05-17T10%3A37%3A32.7669017Z"}]},{"$type":"LocalEntity","name":"ABC_Class","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"ABC_Class.csv"},"attributes":[{"name":"Sort Order","dataType":"int64"},{"name":"ABC-EXP Class","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2021-03-19T04:09:30.7097822+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/c8454994-3560-4488-9782-198736fc771d/ABC_Class.csv?snapshot=2021-05-17T10%3A37%3A32.8249428Z"}]}]}