{"name":"Pegging_Datamart","description":"Pegging datamart table.\nTest flow, not yet operational!","version":"1.0","culture":"en-US","modifiedTime":"2022-04-27T07:45:11.4040414+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":true,"queriesMetadata":{"ASCP_MSC_Full_Pegging":{"queryId":"a94a6ab9-3594-4681-be2b-3440235da043","queryName":"ASCP_MSC_Full_Pegging"},"XXREP_SUP_PEG_DATAMART_V_nonNativeQuery":{"queryId":"f3890f41-6ea4-4aeb-b9a5-d6c32ad37ff2","queryName":"XXREP_SUP_PEG_DATAMART_V_nonNativeQuery"},"MSC_Pegging_Demand_V":{"queryId":"e6fe9058-863b-4b1f-b08b-0a6321824f6e","queryName":"MSC_Pegging_Demand_V"},"XXCOH_SUP_PEG_DATAMART_GT":{"queryId":"9765d4a4-45db-41ca-929d-d2db064ed8fb","queryName":"XXCOH_SUP_PEG_DATAMART_GT"},"XXREP_SUP_PEG_DATAMART_V":{"queryId":"45d4d94c-0009-4713-8a4e-62dab48aa6f2","queryName":"XXREP_SUP_PEG_DATAMART_V","loadEnabled":true},"XXREP_SUP_PEG_DATAMART_V_CountRows":{"queryId":"b3dfb1cc-8028-4ddb-bd77-41d8cac0763e","queryName":"XXREP_SUP_PEG_DATAMART_V_CountRows"}},"document":"section Section1;\r\nshared ASCP_MSC_Full_Pegging = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 1\" = Navigation{[Name = \"ASCP\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"MSC_FULL_PEGGING\", Kind = \"Table\"]}[Data],\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Navigation 2\", {{\"DEMAND_DATE\", type date}, {\"SUPPLY_DATE\", type date}, {\"PEGGING_ID\", Int64.Type}, {\"SUPPLY_TYPE\", Int64.Type}, {\"END_ORIGINATION_TYPE\", Int64.Type}, {\"INVENTORY_ITEM_ID\", Int64.Type}, {\"ORGANIZATION_ID\", Int64.Type}, {\"PLAN_ID\", Int64.Type}, {\"PREV_PEGGING_ID\", Int64.Type}, {\"END_PEGGING_ID\", Int64.Type}, {\"TRANSACTION_ID\", Int64.Type}, {\"DISPOSITION_ID\", Int64.Type}, {\"DEMAND_ID\", Int64.Type}, {\"PROJECT_ID\", Int64.Type}, {\"TASK_ID\", Int64.Type}, {\"SR_INSTANCE_ID\", Int64.Type}, {\"UPDATED\", Int64.Type}, {\"STATUS\", Int64.Type}, {\"LAST_UPDATED_BY\", Int64.Type}, {\"CREATED_BY\", Int64.Type}, {\"LAST_UPDATE_LOGIN\", Int64.Type}, {\"REQUEST_ID\", Int64.Type}, {\"PROGRAM_APPLICATION_ID\", Int64.Type}, {\"PROGRAM_ID\", Int64.Type}, {\"DEST_TRANSACTION_ID\", Int64.Type}, {\"CREATION_DATE\", type time}}),\r\n  #\"Choose columns\" = Table.SelectColumns(#\"Changed column type\", {\"PEGGING_ID\", \"DEMAND_QUANTITY\", \"SUPPLY_QUANTITY\", \"ALLOCATED_QUANTITY\", \"END_ITEM_USAGE\", \"DEMAND_DATE\", \"SUPPLY_DATE\", \"SUPPLY_TYPE\", \"END_ORIGINATION_TYPE\", \"INVENTORY_ITEM_ID\", \"ORGANIZATION_ID\", \"PLAN_ID\", \"PREV_PEGGING_ID\", \"END_PEGGING_ID\", \"TRANSACTION_ID\", \"DISPOSITION_ID\", \"DEMAND_ID\", \"PROJECT_ID\", \"TASK_ID\", \"SR_INSTANCE_ID\", \"DEMAND_CLASS\", \"UPDATED\", \"STATUS\", \"LAST_UPDATE_DATE\", \"CREATION_DATE\", \"CREATED_BY\", \"REQUEST_ID\", \"PROGRAM_APPLICATION_ID\", \"PROGRAM_ID\", \"PROGRAM_UPDATE_DATE\", \"ATTRIBUTE_CATEGORY\", \"UNIT_NUMBER\", \"DEST_TRANSACTION_ID\", \"RESERVED_QTY\"})\r\nin\r\n  #\"Choose columns\";\r\nshared XXREP_SUP_PEG_DATAMART_V_nonNativeQuery = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 1\" = Navigation{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXREP_SUP_PEG_DATAMART_V\", Kind = \"View\"]}[Data]\r\nin\r\n  #\"Navigation 2\";\r\nshared MSC_Pegging_Demand_V = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 1\" = Navigation{[Kind = \"Schema\", Name = \"APPS\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"MSC_PEGGING_DEMAND_V\", Kind = \"View\"]}[Data]\r\nin\r\n  #\"Navigation 2\";\r\nshared XXCOH_SUP_PEG_DATAMART_GT = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 1\" = Navigation{[Name = \"XXSF\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXCOH_SUP_PEG_DATAMART_GT\", Kind = \"Table\"]}[Data],\r\n  #\"Choose columns\" = Table.SelectColumns(#\"Navigation 2\", {\"DATE_RUN\", \"DEMAND_ORG_FAMILY\", \"DEMAND_ORG_LINE\", \"DEMAND_ORG_FORECAST\", \"DEMAND_SALES_COMMODITY\", \"SUPPLY_ORG_FAMILY\", \"SUPPLY_ORG_LINE\", \"SUPPLY_ORG_FORECAST\", \"SUPPLY_SOURCE_COMMODITY\", \"PLAN_NAME\", \"ORG\", \"ITEM_NUMBER\", \"FIRMED\", \"DESCRIPTION\", \"MRP_ABC\", \"MAKE_BUY\", \"ITEM_TYPE\", \"PLANNER_CODE\", \"BUYER_NAME\", \"SOURCE_ORGANIZATION_CODE\", \"SOURCE_VENDOR_NAME\", \"SOURCE_VENDOR_SITE_CODE\", \"CONFIRMED_BY_SUPPLIER\", \"CALC_ORDER_TYPE\", \"ASCP_LEAD_TIME\", \"PO_TYPE\", \"P_PO_NUMBER\", \"P_RELEASE_NUMBER\", \"P_LINE_NUMBER\", \"P_SHIPMENT_NUMBER\", \"QUANTITY_RATE\", \"PROJECT_NUMBER\", \"PO_UNIT_PRICE\", \"PO_UNIT_CURRENCY\", \"FX_RATE\", \"EXT_PO_SUPPLY_PRICE_USD\", \"SUPPLY_PEGGED_QTY\", \"SUP_PEGGGED_PRICE_USD\", \"ACTION\", \"SUPPLY_CATEGORY\", \"CALENDAR_DAYS_LATE\", \"OLD_DOCK_DATE\", \"OLD_DUE_DATE\", \"RESCHEDULE_DAYS\", \"COMPRESSION_DAYS\", \"SUGG_ORDER_DATE\", \"SUGG_START_DATE\", \"SUGG_DOCK_DATE\", \"SUGG_DUE_DATE\", \"PARENT_ITEM\", \"PARENT_ORGANIZATION\", \"PARENT_ITEM_DESCRIPTION\", \"PARENT_ORDER_TYPE\", \"PARENT_ORDER_DATE\", \"PARENT_ORDER_QTY\", \"PARENT_ORDER_NUMBER\", \"SUPPLY_ITEM_PEG_ATTR\", \"END_ITEM_ORG_CODE\", \"END_ITEM\", \"END_ITEM_DESC\", \"END_ITEM_MAKE_BUY\", \"END_ITEM_PLANNER_CODE\", \"END_ITEM_TYPE\", \"END_ITEM_CUSTOMER\", \"END_ITEM_DEM_TYPE\", \"END_ITEM_ORD_NUMBER\", \"END_ITEM_PEG_QUANTITY\", \"END_ITEM_QTY\", \"END_ITEM_PROJECT_NUMBER\", \"END_ITEM_DEMAND_DATE\", \"END_ITEM_ORDER_NUMBER\", \"END_ITEM_CALC_ORDER_NUMBER\", \"END_ITEM_ORDER_TYPE\", \"END_ITEM_ORDER_LINE\", \"END_ITEM_PEGGING_ATTR\", \"CALC_END_DEMAND_CUSTOMER\", \"ESO_ORG_CODE\", \"ESO_ORD_NUM\", \"ESO_LINE_NUM\", \"ESO_CUSTOMER\", \"ESO_SCH_DATE\", \"ESO_IR_NUM\", \"ESO_IR_LINE_NUM\", \"ESO_IR_LINE_STATUS\", \"END_ITEM_ORG\", \"ORDER_NUMBER\", \"FIRMED_LATE\", \"UNCONFIRM_SUPP_COUNT\", \"NUM_DAYS_WORKING\", \"ORGANIZATION_CODE\", \"PLAN_ID\", \"ORDER_TYPE_TEXT\", \"CALC_SD_TYPE\", \"SUPPLY_QUAN_RATE\", \"CUSTOMER_NAME\", \"SCHEDULE_COMMENTS\", \"FORECAST_NAME\", \"FORECAST_DESC\", \"PARENT_WORK_DESC\", \"PO_BUYER\", \"PO_PROMISE_DATE\", \"PO_DESCRIPTION\", \"WO_STATUS\", \"WO_DESC\", \"IT_COST\", \"OSP_PO\", \"OSP_PO_LINE\", \"OSP_PO_LINE_ITEM\", \"OSP_PO_PROMISE_DATE\", \"PO_ORIG_PROM_DATE\", \"SAFE_STK_RSN\"})\r\nin\r\n  #\"Choose columns\";\r\nshared XXREP_SUP_PEG_DATAMART_V = let\r\n  XXREP_SUP_PEG_DATAMART_V = Value.NativeQuery(Snowflake.Databases(\"mma12090.snowflakecomputing.com\",\"COMPUTE_REPORTING\", [Role=\"GLBMFGOPERATIONSROLE\"]){[Name=\"PROD_DB\"]}[Data], \"SELECT *FROM PROD_DB.APPS.XXREP_SUP_PEG_DATAMART_V\", null, [EnableFolding=true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(XXREP_SUP_PEG_DATAMART_V, {{\"DEMAND_ID\", Int64.Type}, {\"PEG_DATAMART_ID\", Int64.Type}, {\"PEGGING_ID\", Int64.Type}, {\"PLAN_ID\", Int64.Type}, {\"REQUEST_ID\", Int64.Type}, {\"END_ITEM_ID\", Int64.Type}, {\"SUP_ITEM_ID\", Int64.Type}, {\"END_ORGANIZATION_ID\", Int64.Type}, {\"SUP_ORGANIZATION_ID\", Int64.Type}, {\"PREV_PEGGING_ID\", Int64.Type}, {\"END_PEGGING_ID\", Int64.Type}, {\"TRANSACTION_ID\", Int64.Type}, {\"END_ITEM_TRANSACTION_ID\", Int64.Type}, {\"ORGANIZATION_ID\", Int64.Type}, {\"PO_LINE_LOCATION_ID\", Int64.Type}, {\"PO_HEADER_ID\", Int64.Type}, {\"PO_RELEASE_ID\", Int64.Type}, {\"SO_LINE_ID\", Int64.Type}})\r\nin\r\n  #\"Changed column type\";\r\nshared XXREP_SUP_PEG_DATAMART_V_CountRows = let\r\n  XXREP_SUP_PEG_DATAMART_V = Value.NativeQuery(Snowflake.Databases(\"mma12090.snowflakecomputing.com\",\"COMPUTE_REPORTING\", [Role=\"GLBMFGOPERATIONSROLE\"]){[Name=\"PROD_DB\"]}[Data], \"SELECT PEG_DATAMART_ID FROM PROD_DB.APPS.XXREP_SUP_PEG_DATAMART_V\", null, [EnableFolding=true]),\r\n  #\"Counted rows\" = Table.RowCount(XXREP_SUP_PEG_DATAMART_V),\r\n  #\"Convert to table\" = Table.FromValue(#\"Counted rows\")\r\nin\r\n  #\"Convert to table\";\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"XXREP_SUP_PEG_DATAMART_V","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"XXREP_SUP_PEG_DATAMART_V.csv"},"attributes":[{"name":"DATE_RUN","dataType":"date"},{"name":"DEMAND_ORG_FAMILY","dataType":"string"},{"name":"DEMAND_ORG_LINE","dataType":"string"},{"name":"DEMAND_ORG_FORECAST","dataType":"string"},{"name":"DEMAND_SALES_COMMODITY","dataType":"string"},{"name":"SUPPLY_ORG_FAMILY","dataType":"string"},{"name":"SUPPLY_ORG_LINE","dataType":"string"},{"name":"SUPPLY_ORG_FORECAST","dataType":"string"},{"name":"SUPPLY_SOURCE_COMMODITY","dataType":"string"},{"name":"PLAN_NAME","dataType":"string"},{"name":"ORG","dataType":"string"},{"name":"ITEM_NUMBER","dataType":"string"},{"name":"FIRMED","dataType":"string"},{"name":"DESCRIPTION","dataType":"string"},{"name":"MRP_ABC","dataType":"string"},{"name":"MAKE_BUY","dataType":"string"},{"name":"ITEM_TYPE","dataType":"string"},{"name":"PLANNER_CODE","dataType":"string"},{"name":"BUYER_NAME","dataType":"string"},{"name":"SOURCE_ORGANIZATION_CODE","dataType":"string"},{"name":"SOURCE_VENDOR_NAME","dataType":"string"},{"name":"SOURCE_VENDOR_SITE_CODE","dataType":"string"},{"name":"CONFIRMED_BY_SUPPLIER","dataType":"string"},{"name":"CALC_ORDER_TYPE","dataType":"string"},{"name":"ASCP_LEAD_TIME","dataType":"double"},{"name":"PO_TYPE","dataType":"string"},{"name":"P_PO_NUMBER","dataType":"string"},{"name":"P_RELEASE_NUMBER","dataType":"string"},{"name":"P_LINE_NUMBER","dataType":"string"},{"name":"P_SHIPMENT_NUMBER","dataType":"string"},{"name":"QUANTITY_RATE","dataType":"double"},{"name":"PROJECT_NUMBER","dataType":"string"},{"name":"PO_UNIT_PRICE","dataType":"double"},{"name":"PO_UNIT_CURRENCY","dataType":"string"},{"name":"FX_RATE","dataType":"double"},{"name":"EXT_PO_SUPPLY_PRICE_USD","dataType":"double"},{"name":"SUPPLY_PEGGED_QTY","dataType":"double"},{"name":"SUP_PEGGGED_PRICE_USD","dataType":"double"},{"name":"ACTION","dataType":"string"},{"name":"SUPPLY_CATEGORY","dataType":"string"},{"name":"CALENDAR_DAYS_LATE","dataType":"double"},{"name":"OLD_DOCK_DATE","dataType":"date"},{"name":"OLD_DUE_DATE","dataType":"date"},{"name":"RESCHEDULE_DAYS","dataType":"string"},{"name":"COMPRESSION_DAYS","dataType":"double"},{"name":"SUGG_ORDER_DATE","dataType":"date"},{"name":"SUGG_START_DATE","dataType":"date"},{"name":"SUGG_DOCK_DATE","dataType":"date"},{"name":"SUGG_DUE_DATE","dataType":"date"},{"name":"PARENT_ITEM","dataType":"string"},{"name":"PARENT_ORGANIZATION","dataType":"string"},{"name":"PARENT_ITEM_DESCRIPTION","dataType":"string"},{"name":"PARENT_ORDER_TYPE","dataType":"string"},{"name":"PARENT_ORDER_DATE","dataType":"date"},{"name":"PARENT_ORDER_QTY","dataType":"double"},{"name":"PARENT_ORDER_NUMBER","dataType":"string"},{"name":"SUPPLY_ITEM_PEG_ATTR","dataType":"string"},{"name":"END_ITEM_ORG_CODE","dataType":"string"},{"name":"END_ITEM","dataType":"string"},{"name":"END_ITEM_DESC","dataType":"string"},{"name":"END_ITEM_MAKE_BUY","dataType":"string"},{"name":"END_ITEM_PLANNER_CODE","dataType":"string"},{"name":"END_ITEM_TYPE","dataType":"string"},{"name":"END_ITEM_CUSTOMER","dataType":"string"},{"name":"END_ITEM_DEM_TYPE","dataType":"string"},{"name":"END_ITEM_ORD_NUMBER","dataType":"string"},{"name":"END_ITEM_PEG_QUANTITY","dataType":"double"},{"name":"END_ITEM_QTY","dataType":"double"},{"name":"END_ITEM_PROJECT_NUMBER","dataType":"string"},{"name":"END_ITEM_DEMAND_DATE","dataType":"date"},{"name":"END_ITEM_ORDER_NUMBER","dataType":"string"},{"name":"END_ITEM_CALC_ORDER_NUMBER","dataType":"string"},{"name":"END_ITEM_ORDER_TYPE","dataType":"string"},{"name":"END_ITEM_ORDER_LINE","dataType":"string"},{"name":"END_ITEM_PEGGING_ATTR","dataType":"string"},{"name":"CALC_END_DEMAND_CUSTOMER","dataType":"string"},{"name":"ESO_ORG_CODE","dataType":"string"},{"name":"ESO_ORD_NUM","dataType":"string"},{"name":"ESO_LINE_NUM","dataType":"string"},{"name":"ESO_CUSTOMER","dataType":"string"},{"name":"ESO_SCH_DATE","dataType":"date"},{"name":"ESO_IR_NUM","dataType":"string"},{"name":"ESO_IR_LINE_NUM","dataType":"string"},{"name":"ESO_IR_LINE_STATUS","dataType":"string"},{"name":"END_ITEM_ORG","dataType":"string"},{"name":"ORDER_NUMBER","dataType":"string"},{"name":"FIRMED_LATE","dataType":"string"},{"name":"UNCONFIRM_SUPP_COUNT","dataType":"string"},{"name":"NUM_DAYS_WORKING","dataType":"double"},{"name":"ORGANIZATION_CODE","dataType":"string"},{"name":"DEMAND_ID","dataType":"int64"},{"name":"PEG_DATAMART_ID","dataType":"int64"},{"name":"PEGGING_ID","dataType":"int64"},{"name":"PLAN_ID","dataType":"int64"},{"name":"REQUEST_ID","dataType":"int64"},{"name":"ORDER_TYPE_TEXT","dataType":"string"},{"name":"CALC_SD_TYPE","dataType":"string"},{"name":"END_ITEM_ID","dataType":"int64"},{"name":"SUP_ITEM_ID","dataType":"int64"},{"name":"END_ORGANIZATION_ID","dataType":"int64"},{"name":"SUP_ORGANIZATION_ID","dataType":"int64"},{"name":"PREV_PEGGING_ID","dataType":"int64"},{"name":"END_PEGGING_ID","dataType":"int64"},{"name":"TRANSACTION_ID","dataType":"int64"},{"name":"END_ITEM_TRANSACTION_ID","dataType":"int64"},{"name":"ORGANIZATION_ID","dataType":"int64"},{"name":"PO_LINE_LOCATION_ID","dataType":"int64"},{"name":"PO_HEADER_ID","dataType":"int64"},{"name":"PO_RELEASE_ID","dataType":"int64"},{"name":"SO_LINE_ID","dataType":"int64"},{"name":"SUPPLY_QUAN_RATE","dataType":"double"},{"name":"CUSTOMER_NAME","dataType":"string"},{"name":"PLNORG_ID","dataType":"string"},{"name":"PREV_ITEM_TRANSACTION_ID","dataType":"double"},{"name":"PREV_ITEM_DEMAND_ID","dataType":"double"},{"name":"SCHEDULE_COMMENTS","dataType":"string"},{"name":"FORECAST_NAME","dataType":"string"},{"name":"FORECAST_DESC","dataType":"string"},{"name":"PARENT_WORK_DESC","dataType":"string"},{"name":"PO_BUYER","dataType":"string"},{"name":"PO_PROMISE_DATE","dataType":"date"},{"name":"PO_DESCRIPTION","dataType":"string"},{"name":"WO_STATUS","dataType":"string"},{"name":"WO_DESC","dataType":"string"},{"name":"IT_COST","dataType":"double"},{"name":"OSP_PO","dataType":"string"},{"name":"OSP_PO_LINE","dataType":"double"},{"name":"OSP_PO_LINE_ITEM","dataType":"string"},{"name":"OSP_PO_PROMISE_DATE","dataType":"date"},{"name":"PO_ORIG_PROM_DATE","dataType":"date"},{"name":"SAFE_STK_RSN","dataType":"string"},{"name":"ROW_CREATION_DATE","dataType":"dateTime"},{"name":"ITEM_ORG_KEY_CODE","dataType":"string"},{"name":"SUPPLY_STATUS","dataType":"string"},{"name":"SOURCE_ORG_OR_SUPPLIER","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T06:34:35.8903897+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/04117986-b2bf-48de-99d3-eea8ea805a9c/XXREP_SUP_PEG_DATAMART_V.csv?snapshot=2022-06-13T06%3A29%3A55.0568714Z"}]}]}