{"name":"lokale_Daten Paladin","description":"Protokoll Hauptdaten\nYield\nProduktionsplan\nZeitstempel\n\n","version":"1.0","culture":"en-US","modifiedTime":"2022-06-13T06:17:31.2065341+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":true,"queriesMetadata":{"PaladinProtokoll_Hauptdaten":{"queryId":"56db734f-99ea-417a-a47b-6b48048f88ed","queryName":"PaladinProtokoll_Hauptdaten","loadEnabled":true},"PaladinProduktionsplan":{"queryId":"b1354e01-1df6-4fca-8141-892d37b001be","queryName":"PaladinProduktionsplan","loadEnabled":true},"PaladinZeitstempel":{"queryId":"fbca45f7-f086-495e-a597-920bbdb22ba3","queryName":"PaladinZeitstempel","loadEnabled":true},"PaladinNCRs":{"queryId":"6e22061b-1c85-44fe-b6c7-e10ecb4da283","queryName":"PaladinNCRs","loadEnabled":true},"MA_Tagesdaten":{"queryId":"e9246d52-3694-4d7c-be04-85047c3377a2","queryName":"MA_Tagesdaten","loadEnabled":true},"DIM_GRUPPIERUNG_PALADIN":{"queryId":"0f8aa080-206b-46f4-a496-99ca59022665","queryName":"DIM_GRUPPIERUNG_PALADIN","loadEnabled":true}},"document":"section Section1;\r\nshared PaladinProtokoll_Hauptdaten = let\r\n  Source = Sql.Database(\"lbksql_Paladin\", \"lbk_Paladin_DB\", [CommandTimeout = #duration(0, 0, 10, 0), Query = \"SELECT * from S_PBI_PaladinHauptdaten\"])\r\nin\r\n  Source;\r\nshared PaladinProduktionsplan = let\r\n  Source = Sql.Database(\"lbksql_Produktionsplaene\", \"lbk_Produktionsplaene_DB\", [CommandTimeout = #duration(0, 0, 5, 0), Query = \"Select * from S_PBI_PaladinProdplan\"]),\r\n  #\"Calculated date 2\" = Table.TransformColumns(Source, {{\"Soll_start\", each DateTime.Date(_), type nullable date}, {\"IR_Part\", each DateTime.Date(_), type nullable date}, {\"Soll_IR_Part\", each DateTime.Date(_), type nullable date},  {\"Grün_Part\", each DateTime.Date(_), type nullable date}, {\"Soll_grün_Part\", each DateTime.Date(_), type nullable date}, {\"UV_Part\", each DateTime.Date(_), type nullable date},{\"Testende_plus_OATage\", each DateTime.Date(_), type nullable date}, {\"versendet\", each DateTime.Date(_), type nullable date}, {\"Problem\", each DateTime.Date(_), type nullable date},{\"Soll_UV_Part\", each DateTime.Date(_), type nullable date}, {\"Kollimation\", each DateTime.Date(_), type nullable date}, {\"Soll_Kollimation\", each DateTime.Date(_), type nullable date}, {\"Datenaufnahme\", each DateTime.Date(_), type nullable date}, {\"Soll_Datenaufnahme\", each DateTime.Date(_), type nullable date},{\"erste_RR_dat\", each DateTime.Date(_), type nullable date}, {\"Im Test seit\", each DateTime.Date(_), type nullable date},{\"Soll_RRDate\", each DateTime.Date(_), type nullable date}, {\"soll_testende\", each DateTime.Date(_), type nullable date}, {\"Testende\", each DateTime.Date(_), type nullable date}, {\"Ausfall\", each DateTime.Date(_), type nullable date}, {\"liefdat\", each DateTime.Date(_), type nullable date},{\"in_den_Endtest\", each DateTime.Date(_), type nullable date}}),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Calculated date 2\", {{\"PN\", Int64.Type}}),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Changed column type\", {{\"soll_testende\", \"Soll_Testende\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared PaladinZeitstempel = let\r\n  Source = Sql.Database(\"lbksql_Paladin\", \"lbk_Paladin_DB\", [CommandTimeout = #duration(0, 0, 5, 0), Query = \"SELECT  * FROM S_PBI_PaladinZeitstempel\"])\r\nin\r\n  Source;\r\nshared PaladinNCRs = let\r\n  Source = Sql.Database(\"lbksql_QMonitor\", \"Lbk_QMonitor_DB\", [CommandTimeout = #duration(0, 0, 5, 0), Query = \"Select * From S_PBI_NCR_Faelle_Paladin where  [rekdat] >= getdate()-720\"]),\r\n  #\"Sorted rows 1\" = Table.Sort(Source, {{\"rekdat\", Order.Descending}}),\r\n  #\"Calculated date\" = Table.TransformColumns(#\"Sorted rows 1\", {{\"rekdat\", each DateTime.Date(_), type date}}),\r\n  #\"Sorted rows\" = Table.Sort(#\"Calculated date\", {{\"rekdat\", Order.Descending}}),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Sorted rows\", {{\"Modelgruppe\", \"Modelgruppe-NCRs\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared MA_Tagesdaten = let\r\n  Source = Excel.Workbook(File.Contents(\"\\\\cohr\\eu\\delbc\\groups\\Operations\\Stand-Up\\Daten\\Paladin Eingabe MA.xlsm\"), null, true),\r\n  Navigation = Source{[Item = \"Tagesdaten\", Kind = \"Sheet\"]}[Data],\r\n  #\"Promoted headers\" = Table.PromoteHeaders(Navigation, [PromoteAllScalars = true]),\r\n  #\"Removed columns\" = Table.RemoveColumns(#\"Promoted headers\", {\"Quartal\"}),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Removed columns\", {{\"Adv#(lf)Anzahl MA RR\", \"Adv AnzahlMA RR\"}, {\"Adv#(lf)Veränd-erung\", \"Adv Veränderung\"}, {\"Adv#(lf)ge-plant\", \"Adv geplant\"}, {\"Adv abw#(lf)un-gepl.\", \"Adv abw ungepl.\"}, {\"Adv abw#(lf)gepl.\", \"Adv abw gepl.\"}, {\"Comp#(lf)Veränd-erung\", \"Comp Veränderung\"}, {\"Comp#(lf)ge-plant\", \"Comp geplant\"}, {\"Comp abw#(lf)un-gepl.\", \"Comp abw ungepl.\"}, {\"Scan abw#(lf)un-gepl.\", \"Scan abw ungepl.\"}, {\"Scan abw#(lf)gepl.\", \"Scan abw gepl.\"}, {\"ET#(lf)Veränd erung\", \"ET Veränderung\"}, {\"ET#(lf)ge-plant\", \"ET geplant\"}, {\"Adv#(lf)an-wesend\", \"Adv anwesend\"}, {\"Adv#(lf)einge-plant\", \"Adv eingeplant\"}, {\"Adv#(lf)Anteil\", \"Adv Anteil\"}, {\"Comp#(lf)an-wesend\", \"Comp anwesend\"}, {\"Comp#(lf)einge-plant\", \"Comp eingeplant\"}, {\"Scan#(lf)an-wesend\", \"Scan anwesend\"}, {\"Scan#(lf)einge-plant\", \"Scan eingeplant\"}, {\"Scan#(lf)Anteil\", \"Scan Anteil\"}, {\"ET#(lf)an-wesend\", \"ET anwesend\"}, {\"ET#(lf)einge-plant\", \"ET eingeplant\"}, {\"ET#(lf)Anteil\", \"ET Anteil\"}, {\"Scan#(lf)ge-plant\", \"Scan geplant\"}, {\"Scan#(lf)Veränd-erung\", \"Scan Veränderung\"}, {\"ET#(lf)abw#(lf)un-gepl.\", \"ET abw ungepl.\"}, {\"Comp#(lf)Anteil\", \"Comp Anteil\"}, {\"Scan#(lf)Anzahl #(lf)MA RR\", \"Scan AnzahlMA RR\"}, {\"Comp#(lf)Anzahl #(lf)MA RR\", \"Comp AnzahlMA RR\"}, {\"Comp#(lf)abw#(lf)gepl.\", \"Comp abw gepl.\"}, {\"ET#(lf)abw#(lf)gepl.\", \"ET abw gepl.\"}, {\"ET#(lf)Anzahl #(lf)MA\", \"ET AnzahlMA\"}}),\r\n  #\"Changed column type num/Date\" = Table.TransformColumnTypes(#\"Renamed columns\", {{\"Comp Anteil\", type number}, {\"Scan Anteil\", type number}, {\"Adv AnzahlMA RR\", Int64.Type}, {\"ET anwesend\", Int64.Type}, {\"ET eingeplant\", Int64.Type}, {\"Comp anwesend\", Int64.Type}, {\"Comp eingeplant\", Int64.Type}, {\"Scan anwesend\", Int64.Type}, {\"Scan eingeplant\", Int64.Type}, {\"Adv eingeplant\", Int64.Type}, {\"Adv Veränderung\", Int64.Type}, {\"Adv abw ungepl.\", Int64.Type}, {\"Adv abw gepl.\", Int64.Type}, {\"Comp AnzahlMA RR\", Int64.Type}, {\"Comp Veränderung\", Int64.Type}, {\"Comp abw ungepl.\", Int64.Type}, {\"Comp abw gepl.\", Int64.Type}, {\"Scan AnzahlMA RR\", Int64.Type}, {\"Scan Veränderung\", Int64.Type}, {\"Scan abw ungepl.\", Int64.Type}, {\"Scan abw gepl.\", Int64.Type}, {\"ET AnzahlMA\", Int64.Type}, {\"ET Veränderung\", Int64.Type}, {\"ET abw ungepl.\", Int64.Type}, {\"ET abw gepl.\", Int64.Type}, {\"Adv anwesend\", Int64.Type}, {\"Adv Anteil\", type number}, {\"ET Anteil\", type number}, {\"Datum\", type date}}),\r\n  #\"Changed column type  text\" = Table.TransformColumnTypes(#\"Changed column type num/Date\", {{\"Adv geplant\", type text}, {\"Comp geplant\", type text}, {\"Scan geplant\", type text},{\"ET geplant\", type text},{\"KW\", type text}}),\r\n  #\"Replaced value null->0\" = Table.ReplaceValue(#\"Changed column type  text\", null, 0, Replacer.ReplaceValue, {\"Adv Veränderung\", \"Adv abw ungepl.\", \"Adv abw gepl.\", \"Comp Veränderung\", \"Comp abw ungepl.\", \"Comp abw gepl.\", \"Scan Veränderung\", \"Scan abw ungepl.\", \"Scan abw gepl.\"}),\r\n  #\"Changed column type- mittlere Anw\" = Table.TransformColumnTypes(#\"Replaced value null->0\", {{\"Adv#(lf)Mittlere Anw / Wo\", type number}, {\"Comp#(lf)Mittlere Anw / Wo\", type number}, {\"Scan#(lf)Mittlere Anw / Wo\", type number}, {\"ET#(lf)Mittlere Anw / Wo\", type number}, {\"Adv#(lf)Mittlere Anw / Q\", type number}, {\"Comp#(lf)Mittlere Anw / Q\", type number}, {\"Scan#(lf)Mittlere Anw / Q\", type number}, {\"ET#(lf)Mittlere Anw / Q\", type number}}),\r\n  #\"Replaced errors\" = Table.ReplaceErrorValues(#\"Changed column type- mittlere Anw\", {{\"Adv#(lf)Mittlere Anw / Wo\", null}, {\"Comp#(lf)Mittlere Anw / Wo\", null}, {\"Scan#(lf)Mittlere Anw / Wo\", null}, {\"ET#(lf)Mittlere Anw / Wo\", null}, {\"Adv#(lf)Mittlere Anw / Q\", null}, {\"Comp#(lf)Mittlere Anw / Q\", null}, {\"Scan#(lf)Mittlere Anw / Q\", null}, {\"ET#(lf)Mittlere Anw / Q\", null}})\r\nin\r\n  #\"Replaced errors\";\r\nshared DIM_GRUPPIERUNG_PALADIN = let\n  Source = Sql.Database(\"lbksql_Teilekatalog\", \"lbk_Teilekatalog_DB\", [CommandTimeout = #duration(0, 0, 5, 0), Query = \"SELECT  * FROM S_PBI_PaladinGruppierung\"]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each ([Lasertyp_Prodplan] <> \"Advanced Ruecklaeufer\" and [Lasertyp_Prodplan] <> \"Compact Ruecklaeufer\" and [Lasertyp_Prodplan] <> \"Dual Ruecklaeufer\" and [Lasertyp_Prodplan] <> \"FRU Diode Scan Dual\" and [Lasertyp_Prodplan] <> \"Scan Ruecklaeufer\" and [Lasertyp_Prodplan] <> \"SESSE 35W\"))\nin\n  #\"Filtered rows\";\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"PaladinProtokoll_Hauptdaten","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"PaladinProtokoll_Hauptdaten.csv"},"attributes":[{"name":"PN","dataType":"double"},{"name":"PNindex","dataType":"string"},{"name":"Lasertyp","dataType":"string"},{"name":"Typ","dataType":"double"},{"name":"AFO_tab","dataType":"string"},{"name":"Fehlerart","dataType":"string"},{"name":"Entwicklung","dataType":"boolean"},{"name":"Anlernlaser","dataType":"boolean"},{"name":"prodplan_model","dataType":"string"},{"name":"ersterStartZeitstempel_PNIndex","dataType":"dateTime"},{"name":"Beginn des Baus","dataType":"dateTime"},{"name":"Datum_fertig_RR","dataType":"dateTime"},{"name":"deltaDays","dataType":"int64"},{"name":"Station","dataType":"string"},{"name":"Station_UV","dataType":"string"},{"name":"In_Use","dataType":"boolean"},{"name":"minZeitstempelPNIndex","dataType":"dateTime"},{"name":"Datum_AnlagePNIndex","dataType":"dateTime"},{"name":"Datum_ET_Start","dataType":"dateTime"},{"name":"Datum_ET_Ende","dataType":"dateTime"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T06:30:19.5529699+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/c85bc41e-2151-478e-8748-d4d71ab7e27e/PaladinProtokoll_Hauptdaten.csv?snapshot=2022-06-13T06%3A30%3A18.7876123Z"}]},{"$type":"LocalEntity","name":"PaladinProduktionsplan","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"PaladinProduktionsplan.csv"},"attributes":[{"name":"ID1","dataType":"int64"},{"name":"ID","dataType":"int64"},{"name":"Lasertyp","dataType":"string"},{"name":"Teilenr","dataType":"string"},{"name":"PN","dataType":"int64"},{"name":"Ausfall","dataType":"date"},{"name":"RepID","dataType":"int64"},{"name":"RepNeu","dataType":"string"},{"name":"Rückläufer","dataType":"boolean"},{"name":"Soll_start","dataType":"date"},{"name":"IR_Part","dataType":"date"},{"name":"Soll_IR_Part","dataType":"date"},{"name":"Grün_Part","dataType":"date"},{"name":"Soll_grün_Part","dataType":"date"},{"name":"UV_Part","dataType":"date"},{"name":"Soll_UV_Part","dataType":"date"},{"name":"Kollimation","dataType":"date"},{"name":"Soll_Kollimation","dataType":"date"},{"name":"Datenaufnahme","dataType":"date"},{"name":"Soll_Datenaufnahme","dataType":"date"},{"name":"in_den_Endtest","dataType":"date"},{"name":"erste_RR_dat","dataType":"date"},{"name":"Soll_RRDate","dataType":"date"},{"name":"Im Test seit","dataType":"date"},{"name":"Soll_Testende","dataType":"date"},{"name":"Testende","dataType":"date"},{"name":"Problem","dataType":"date"},{"name":"liefdat","dataType":"date"},{"name":"Testende_plus_OATage","dataType":"date"},{"name":"versendet","dataType":"date"},{"name":"in_Entw","dataType":"boolean"},{"name":"Bemerkung","dataType":"string"},{"name":"Kunde","dataType":"string"},{"name":"Kopf_System","dataType":"string"},{"name":"aktuell","dataType":"boolean"},{"name":"ETfertig","dataType":"int64"},{"name":"RRfertig","dataType":"int64"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T06:30:10.403351+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/c85bc41e-2151-478e-8748-d4d71ab7e27e/PaladinProduktionsplan.csv?snapshot=2022-06-13T06%3A30%3A10.0296896Z"}]},{"$type":"LocalEntity","name":"PaladinZeitstempel","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"PaladinZeitstempel.csv"},"attributes":[{"name":"PNindex","dataType":"string"},{"name":"SchrittNr","dataType":"string"},{"name":"DeltaMinuten","dataType":"int64"},{"name":"direkt_indirekt_support","dataType":"string"},{"name":"Durchlauf","dataType":"double"},{"name":"start","dataType":"string"},{"name":"Zeitstempel_start","dataType":"dateTime"},{"name":"stop","dataType":"string"},{"name":"Zeitstempel_stop","dataType":"dateTime"},{"name":"nachgetragen","dataType":"string"},{"name":"Arbeitsschritt","dataType":"string"},{"name":"Hinweis","dataType":"string"},{"name":"Station","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T06:30:21.7156988+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/c85bc41e-2151-478e-8748-d4d71ab7e27e/PaladinZeitstempel.csv?snapshot=2022-06-13T06%3A30%3A21.4350794Z"}]},{"$type":"LocalEntity","name":"PaladinNCRs","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"PaladinNCRs.csv"},"attributes":[{"name":"RekNum_","dataType":"string"},{"name":"rekdat","dataType":"date"},{"name":"Model","dataType":"string"},{"name":"Komponente","dataType":"string"},{"name":"Abteilung","dataType":"string"},{"name":"teilenum","dataType":"string"},{"name":"Anzahl","dataType":"int64"},{"name":"Fehlerbild","dataType":"string"},{"name":"Modelgruppe-NCRs","dataType":"string"},{"name":"Produktgruppe","dataType":"string"},{"name":"Lasertyp","dataType":"string"},{"name":"TeileNr_defekt","dataType":"string"},{"name":"NCRUrsache","dataType":"string"},{"name":"NCRUrsacheStufe1","dataType":"string"},{"name":"NCRUrsache_Beschreibung","dataType":"string"},{"name":"rekAbschluss_Am","dataType":"dateTime"},{"name":"Fehler_bem","dataType":"string"},{"name":"Aktion","dataType":"string"},{"name":"AgilePQM_Date","dataType":"dateTime"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T06:30:09.5283844+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/c85bc41e-2151-478e-8748-d4d71ab7e27e/PaladinNCRs.csv?snapshot=2022-06-13T06%3A30%3A09.3840638Z"}]},{"$type":"LocalEntity","name":"MA_Tagesdaten","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"MA_Tagesdaten.csv"},"attributes":[{"name":"Datum","dataType":"date"},{"name":"Adv AnzahlMA RR","dataType":"int64"},{"name":"Adv Veränderung","dataType":"double"},{"name":"Adv geplant","dataType":"string"},{"name":"Adv abw ungepl.","dataType":"double"},{"name":"Adv abw gepl.","dataType":"double"},{"name":"Comp AnzahlMA RR","dataType":"int64"},{"name":"Comp Veränderung","dataType":"double"},{"name":"Comp geplant","dataType":"string"},{"name":"Comp abw ungepl.","dataType":"double"},{"name":"Comp abw gepl.","dataType":"double"},{"name":"Scan AnzahlMA RR","dataType":"int64"},{"name":"Scan Veränderung","dataType":"double"},{"name":"Scan geplant","dataType":"string"},{"name":"Scan abw ungepl.","dataType":"double"},{"name":"Scan abw gepl.","dataType":"double"},{"name":"ET AnzahlMA","dataType":"int64"},{"name":"ET Veränderung","dataType":"int64"},{"name":"ET geplant","dataType":"string"},{"name":"ET abw ungepl.","dataType":"int64"},{"name":"ET abw gepl.","dataType":"int64"},{"name":"Adv anwesend","dataType":"int64"},{"name":"Adv eingeplant","dataType":"int64"},{"name":"Adv Anteil","dataType":"double"},{"name":"Comp anwesend","dataType":"int64"},{"name":"Comp eingeplant","dataType":"int64"},{"name":"Comp Anteil","dataType":"double"},{"name":"Scan anwesend","dataType":"int64"},{"name":"Scan eingeplant","dataType":"int64"},{"name":"Scan Anteil","dataType":"double"},{"name":"ET anwesend","dataType":"int64"},{"name":"ET eingeplant","dataType":"int64"},{"name":"ET Anteil","dataType":"double"},{"name":"KW","dataType":"string"},{"name":"Adv\nMittlere Anw / Wo","dataType":"double"},{"name":"Comp\nMittlere Anw / Wo","dataType":"double"},{"name":"Scan\nMittlere Anw / Wo","dataType":"double"},{"name":"ET\nMittlere Anw / Wo","dataType":"double"},{"name":"Adv\nMittlere Anw / Q","dataType":"double"},{"name":"Comp\nMittlere Anw / Q","dataType":"double"},{"name":"Scan\nMittlere Anw / Q","dataType":"double"},{"name":"ET\nMittlere Anw / Q","dataType":"double"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T06:30:17.6913256+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/c85bc41e-2151-478e-8748-d4d71ab7e27e/MA_Tagesdaten.csv?snapshot=2022-06-13T06%3A30%3A17.5603236Z"}]},{"$type":"LocalEntity","name":"DIM_GRUPPIERUNG_PALADIN","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"DIM_GRUPPIERUNG_PALADIN.csv"},"attributes":[{"name":"Lasertyp_Prodplan","dataType":"string"},{"name":"LasertypGruppe_Produktivitaet","dataType":"string"},{"name":"LasertypGruppe_Produktivitaet_Endtest","dataType":"string"},{"name":"LasertypGruppe_Yield","dataType":"string"},{"name":"Lasertyp_Yield","dataType":"string"},{"name":"LasertypGruppe_fuerPowerBI","dataType":"string"},{"name":"NCR_Model","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T06:30:06.8269884+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/c85bc41e-2151-478e-8748-d4d71ab7e27e/DIM_GRUPPIERUNG_PALADIN.csv?snapshot=2022-06-13T06%3A30%3A06.7925655Z"}]}]}