{"name":"COHERENT_SNOWFLAKE_CUMULUS","description":"","version":"1.0","culture":"en-US","modifiedTime":"2022-05-18T07:27:06.8734559+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"CUM_FAILURES_DEFECTS":{"queryId":"1912e131-3321-48c0-b357-e7c60ca4b66d","queryName":"CUM_FAILURES_DEFECTS","loadEnabled":true},"CUM_PARTNUMBER_V":{"queryId":"2bf2d315-763e-4e89-b5ec-5922fc47d89f","queryName":"CUM_PARTNUMBER_V","loadEnabled":true},"CUM_SANDBOXES":{"queryId":"378fc0d4-960e-4d64-bd63-ce2d787ec39d","queryName":"CUM_SANDBOXES","loadEnabled":true},"CUM_TAGS_V":{"queryId":"8b5c4501-a944-46f9-822e-4a28eca3cbaf","queryName":"CUM_TAGS_V","loadEnabled":true},"CUM_TIME_STUDIES":{"queryId":"d4bb8d70-2ee4-4e74-a0c2-cd483850a10b","queryName":"CUM_TIME_STUDIES","loadEnabled":true},"CUM_WORKORDERS":{"queryId":"0116b32f-718c-42ae-b8ee-88423dc6bcb5","queryName":"CUM_WORKORDERS","loadEnabled":true},"SandboxKey_OBISXT":{"queryId":"93c557ff-e26d-4380-b63c-4975ada17f1b","queryName":"SandboxKey_OBISXT"},"SandboxKey_Sapphire":{"queryId":"8c0d7247-ed40-4a98-a8b4-c233fabcdc1d","queryName":"SandboxKey_Sapphire"},"SandboxKey_AzureNX":{"queryId":"bbaba140-b195-4a6b-8d81-240b848cf2b4","queryName":"SandboxKey_AzureNX"},"SandboxKey_FlareNX":{"queryId":"6b761867-1ae5-495d-bc7a-2483cca50f3e","queryName":"SandboxKey_FlareNX"},"SandboxKey_CompassCW":{"queryId":"9a8c2654-bb9a-403c-9411-06df664d26fd","queryName":"SandboxKey_CompassCW"},"CUM_QUEUE":{"queryId":"01dd0304-90e4-419c-b093-95b79c5885da","queryName":"CUM_QUEUE","loadEnabled":true}},"document":"section Section1;\r\nshared CUM_FAILURES_DEFECTS = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  #\"Navigation 1\" = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"CUMULUS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 3\" = #\"Navigation 2\"{[Name = \"CUM_FAILURES_DEFECTS\", Kind = \"Table\"]}[Data],\r\n  #\"Filtered rows\" = Table.SelectRows(#\"Navigation 3\", each [SANDBOXKEY] = SandboxKey_OBISXT or [SANDBOXKEY] = SandboxKey_Sapphire or [SANDBOXKEY] = SandboxKey_AzureNX or [SANDBOXKEY] = SandboxKey_FlareNX or [SANDBOXKEY] = SandboxKey_CompassCW),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Filtered rows\", {{\"FAILUREKEY\", Int64.Type}, {\"SANDBOXKEY\", Int64.Type}, {\"WORKORDERKEY\", Int64.Type}, {\"PARTNUMBERKEY\", Int64.Type}}),\r\n  #\"NewColumn [Date_Failure]\" = Table.DuplicateColumn(#\"Changed column type\", \"FAILURE_DATE\", \"Date_Failure\"),\r\n  #\"Calculated date-[Date_Failure]\" = Table.TransformColumns(#\"NewColumn [Date_Failure]\", {{\"Date_Failure\", each DateTime.Date(_), type nullable date}}),\r\n  #\"Replaced value-Column [NCR]\" = Table.ReplaceValue(#\"Calculated date-[Date_Failure]\", null, \"None\", Replacer.ReplaceValue, {\"NCR\"}),\r\n  #\"Renamed columns-[TYPE]\" = Table.RenameColumns(#\"Replaced value-Column [NCR]\", {{\"TYPE\", \"REJECT_TYPE\"}})\r\nin\r\n  #\"Renamed columns-[TYPE]\";\r\nshared CUM_PARTNUMBER_V = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  #\"Navigation 1\" = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"CUMULUS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 3\" = #\"Navigation 2\"{[Name = \"CUM_PARTNUMBER_V\", Kind = \"View\"]}[Data],\r\n  #\"Filtered rows\" = Table.SelectRows(#\"Navigation 3\", each [SANDBOXKEY] = SandboxKey_OBISXT or [SANDBOXKEY] = SandboxKey_Sapphire or [SANDBOXKEY] = SandboxKey_AzureNX or [SANDBOXKEY] = SandboxKey_FlareNX or [SANDBOXKEY] = SandboxKey_CompassCW),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Filtered rows\", {{\"PARTNUMBERKEY\", Int64.Type}, {\"SANDBOXKEY\", Int64.Type}})\r\nin\r\n  #\"Changed column type\";\r\nshared CUM_SANDBOXES = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  #\"Navigation 1\" = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"CUMULUS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 3\" = #\"Navigation 2\"{[Name = \"CUM_SANDBOXES\", Kind = \"Table\"]}[Data],\r\n  #\"Filtered rows\" = Table.SelectRows(#\"Navigation 3\", each [SANDBOXKEY] = SandboxKey_OBISXT or [SANDBOXKEY] = SandboxKey_Sapphire or [SANDBOXKEY] = SandboxKey_AzureNX or [SANDBOXKEY] = SandboxKey_FlareNX or [SANDBOXKEY] = SandboxKey_CompassCW)\r\nin\r\n  #\"Filtered rows\";\r\nshared CUM_TAGS_V = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  #\"Navigation 1\" = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"CUMULUS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 3\" = #\"Navigation 2\"{[Name = \"CUM_TAGS_V\", Kind = \"View\"]}[Data],\r\n  #\"Filtered rows\" = Table.SelectRows(#\"Navigation 3\", each [SANDBOXKEY] = SandboxKey_OBISXT or [SANDBOXKEY] = SandboxKey_Sapphire or [SANDBOXKEY] = SandboxKey_AzureNX or [SANDBOXKEY] = SandboxKey_FlareNX or [SANDBOXKEY] = SandboxKey_CompassCW),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Filtered rows\", {{\"SANDBOXKEY\", Int64.Type}, {\"PARTNUMBERKEY\", Int64.Type}})\r\nin\r\n  #\"Changed column type\";\r\nshared CUM_TIME_STUDIES = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  #\"Navigation 1\" = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"CUMULUS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 3\" = #\"Navigation 2\"{[Name = \"CUM_TIME_STUDIES\", Kind = \"Table\"]}[Data],\r\n  #\"Filtered rows\" = Table.SelectRows(#\"Navigation 3\", each [ORG] = \"LDP\")\r\nin\r\n  #\"Filtered rows\";\r\nshared CUM_WORKORDERS = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  #\"Navigation 1\" = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"CUMULUS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 3\" = #\"Navigation 2\"{[Name = \"CUM_WORKORDERS\", Kind = \"Table\"]}[Data],\r\n  #\"Filtered rows\" = Table.SelectRows(#\"Navigation 3\", each [SANDBOXKEY] = SandboxKey_OBISXT or [SANDBOXKEY] = SandboxKey_Sapphire or [SANDBOXKEY] = SandboxKey_AzureNX or [SANDBOXKEY] = SandboxKey_FlareNX or [SANDBOXKEY] = SandboxKey_CompassCW),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Filtered rows\", {{\"WORKORDERKEY\", Int64.Type}, {\"SANDBOXKEY\", Int64.Type}, {\"WOQUEUEKEY\", Int64.Type}, {\"PARTNUMBERKEY\", Int64.Type}}),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Changed column type\", {{\"CREATED\", \"DateTime_CREATED\"}, {\"COMPLETED\", \"DateTime_COMPLETED\"}, {\"MODIFIED\", \"DateTime_MODIFIED\"}, {\"SERIES_DATE\", \"DateTime_SeriesStart\"}, {\"TYPE\", \"WORKORDER_TYPE\"}}),\r\n  #\"Replaced value-ORACLE_WORKORDER\" = Table.ReplaceValue(#\"Renamed columns\", \"\", \"None\", Replacer.ReplaceValue, {\"ORACLE_WORKORDER\"}),\r\n  #\"Replaced value.-RACLE_WO\" = Table.ReplaceValue(#\"Replaced value-ORACLE_WORKORDER\", null, \"None\", Replacer.ReplaceValue, {\"ORACLE_WORKORDER\"}),\r\n  #\"Duplicated column\" = Table.DuplicateColumn(#\"Replaced value.-RACLE_WO\", \"DateTime_CREATED\", \"Date_CREATED\"),\r\n  #\"Duplicated column 1\" = Table.DuplicateColumn(#\"Duplicated column\", \"DateTime_COMPLETED\", \"Date_COMPLETED\"),\r\n  #\"Calculated date\" = Table.TransformColumns(#\"Duplicated column 1\", {{\"Date_CREATED\", each DateTime.Date(_), type nullable date}, {\"Date_COMPLETED\", each DateTime.Date(_), type nullable date}}),\r\n  #\"Added custom\" = Table.AddColumn(#\"Calculated date\", \"ITEM_SANDBOX_KEY_ID\", each Text.Combine({Number.ToText([PARTNUMBERKEY]),Number.ToText([SANDBOXKEY])},\"_\")),\r\n  #\"Changed column type 1\" = Table.TransformColumnTypes(#\"Added custom\", {{\"ITEM_SANDBOX_KEY_ID\", type text}})\r\nin\r\n  #\"Changed column type 1\";\r\nshared SandboxKey_OBISXT = let\r\n  Param_SandboxKey = 2246 meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type any, List = {1024, 2102, 2160, 2162, 2168, 2202, 2212, 2228, 2232, 2246, 2278, 2334, 2352}]\r\nin\r\n  Param_SandboxKey;\r\nshared SandboxKey_Sapphire = let\r\n  Param_SandboxKey = 2162 meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type any, List = {1024, 2102, 2160, 2162, 2168, 2202, 2212, 2228, 2232, 2246, 2278, 2334, 2352}]\r\nin\r\n  Param_SandboxKey;\r\nshared SandboxKey_AzureNX = let\r\n  Param_SandboxKey = 2212 meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type any, List = {1024, 2102, 2160, 2162, 2168, 2202, 2212, 2228, 2232, 2246, 2278, 2334, 2352}]\r\nin\r\n  Param_SandboxKey;\r\nshared SandboxKey_FlareNX = let\r\n  Param_SandboxKey = 2202 meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type any, List = {1024, 2102, 2160, 2162, 2168, 2202, 2212, 2228, 2232, 2246, 2278, 2334, 2352}]\r\nin\r\n  Param_SandboxKey;\r\nshared SandboxKey_CompassCW = let\r\n  Param_SandboxKey = 2168 meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type any, List = {1024, 2102, 2160, 2162, 2168, 2202, 2212, 2228, 2232, 2246, 2278, 2334, 2352}]\r\nin\r\n  Param_SandboxKey;\r\nshared CUM_QUEUE = let\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\n  #\"Navigation 1\" = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"CUMULUS\", Kind = \"Schema\"]}[Data],\n  #\"Navigation 3\" = #\"Navigation 2\"{[Name = \"CUM_QUEUE\", Kind = \"Table\"]}[Data],\n  #\"Filtered rows\" = Table.SelectRows(#\"Navigation 3\", each [SANDBOXKEY] = SandboxKey_OBISXT or [SANDBOXKEY] = SandboxKey_Sapphire or [SANDBOXKEY] = SandboxKey_AzureNX or [SANDBOXKEY] = SandboxKey_FlareNX or [SANDBOXKEY] = SandboxKey_CompassCW)\nin\n  #\"Filtered rows\";\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"CUM_FAILURES_DEFECTS","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"CUM_FAILURES_DEFECTS.csv"},"attributes":[{"name":"FAILUREKEY","dataType":"int64"},{"name":"SANDBOXKEY","dataType":"int64"},{"name":"WORKORDERKEY","dataType":"int64"},{"name":"FAILURE_DATE","dataType":"dateTime"},{"name":"MODIFIED_DATE","dataType":"dateTime"},{"name":"ORG","dataType":"string"},{"name":"REJECT_TYPE","dataType":"string"},{"name":"PARTNUMBERKEY","dataType":"int64"},{"name":"PROCESS","dataType":"string"},{"name":"PROCESS_DESCRIPTION","dataType":"string"},{"name":"QTY_REJECTED","dataType":"double"},{"name":"FAILURE_GROUP","dataType":"string"},{"name":"FAILURE","dataType":"string"},{"name":"REJECTED_BY","dataType":"string"},{"name":"EST_EFFORT_HRS","dataType":"double"},{"name":"ROOT_CAUSE_GROUP","dataType":"string"},{"name":"ROOT_CAUSE","dataType":"string"},{"name":"NCR","dataType":"string"},{"name":"FAILURE_NOTES","dataType":"string"},{"name":"Date_Failure","dataType":"date"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-20T03:02:01.9602199+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/edd8082a-10f6-4c54-a05a-127745162d69/CUM_FAILURES_DEFECTS.csv?snapshot=2022-05-20T03%3A02%3A01.9426883Z"}]},{"$type":"LocalEntity","name":"CUM_PARTNUMBER_V","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"CUM_PARTNUMBER_V.csv"},"attributes":[{"name":"PARTNUMBERKEY","dataType":"int64"},{"name":"PART_DESCRIPTION","dataType":"string"},{"name":"SANDBOXKEY","dataType":"int64"},{"name":"ACTIVE","dataType":"boolean"},{"name":"CREATE_DATE","dataType":"dateTime"},{"name":"MODIFY_DATE","dataType":"dateTime"},{"name":"TYPE","dataType":"string"},{"name":"PART_NUMBER","dataType":"string"},{"name":"WIP_DISPLAY","dataType":"string"},{"name":"AGILE_AUTO_SYNC","dataType":"boolean"},{"name":"AUTO_SERIALIZE","dataType":"boolean"},{"name":"WORK_CELL","dataType":"string"},{"name":"PRODUCTION_TYPE","dataType":"string"},{"name":"FLOW_NAME","dataType":"string"},{"name":"VARIABLE_COMP_QTY","dataType":"boolean"},{"name":"MAXIMUM_LOT_SIZE","dataType":"double"},{"name":"MAXIMUMN_BATCH_SIZE","dataType":"double"},{"name":"ORACLE_GENERIC_PN","dataType":"boolean"},{"name":"INVORG_CODE","dataType":"string"},{"name":"SANDBOX","dataType":"string"},{"name":"ITEM_ORG_KEY_CODE","dataType":"string"},{"name":"ITEM_SANDBOX_KEY_ID","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-20T03:02:06.656173+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/edd8082a-10f6-4c54-a05a-127745162d69/CUM_PARTNUMBER_V.csv?snapshot=2022-05-20T03%3A02%3A06.6270141Z"}]},{"$type":"LocalEntity","name":"CUM_SANDBOXES","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"CUM_SANDBOXES.csv"},"attributes":[{"name":"SANDBOXKEY","dataType":"double"},{"name":"BUSINESS_UNIT","dataType":"string"},{"name":"MAJOR_PRODUCT_FAMILY","dataType":"string"},{"name":"SANDBOX","dataType":"string"},{"name":"RESTRICTED","dataType":"boolean"},{"name":"ITAR","dataType":"boolean"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-20T03:02:09.0155692+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/edd8082a-10f6-4c54-a05a-127745162d69/CUM_SANDBOXES.csv?snapshot=2022-05-20T03%3A02%3A08.8737311Z"}]},{"$type":"LocalEntity","name":"CUM_TAGS_V","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"CUM_TAGS_V.csv"},"attributes":[{"name":"SANDBOXKEY","dataType":"int64"},{"name":"PARTNUMBERKEY","dataType":"int64"},{"name":"PART_NUMBER","dataType":"string"},{"name":"TAG","dataType":"string"},{"name":"ITEM_ORG_KEY_CODE","dataType":"string"},{"name":"ITEM_SANDBOX_KEY_ID","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-20T03:02:18.8977904+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/edd8082a-10f6-4c54-a05a-127745162d69/CUM_TAGS_V.csv?snapshot=2022-05-20T03%3A02%3A18.6511489Z"}]},{"$type":"LocalEntity","name":"CUM_TIME_STUDIES","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"CUM_TIME_STUDIES.csv"},"attributes":[{"name":"TIMESTUDY_NUMBER","dataType":"double"},{"name":"ACTIVE","dataType":"boolean"},{"name":"ORG","dataType":"string"},{"name":"START_DATE","dataType":"dateTime"},{"name":"END_DATE","dataType":"dateTime"},{"name":"DESCRIPTION","dataType":"string"},{"name":"ALL_COMPONENTS","dataType":"boolean"},{"name":"SCOPE","dataType":"string"},{"name":"SCOPE_DETAIL","dataType":"string"},{"name":"PRODUCTION","dataType":"boolean"},{"name":"REWORK","dataType":"boolean"},{"name":"SERVICE","dataType":"boolean"},{"name":"ENGINEERING","dataType":"boolean"},{"name":"AUTO_END","dataType":"boolean"},{"name":"AUTO_END_COUNT","dataType":"double"},{"name":"AUTO_END_CURRENT_COUNT","dataType":"double"},{"name":"HIDE_CLOCK","dataType":"boolean"},{"name":"HIDE_DURATION","dataType":"boolean"},{"name":"ANONYMOUS","dataType":"boolean"},{"name":"NOTES","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-20T03:02:02.6634653+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/edd8082a-10f6-4c54-a05a-127745162d69/CUM_TIME_STUDIES.csv?snapshot=2022-05-20T03%3A02%3A02.6392905Z"}]},{"$type":"LocalEntity","name":"CUM_WORKORDERS","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"CUM_WORKORDERS.csv"},"attributes":[{"name":"WORKORDERKEY","dataType":"int64"},{"name":"SANDBOXKEY","dataType":"int64"},{"name":"WOQUEUEKEY","dataType":"int64"},{"name":"WORKORDER_NUMBER","dataType":"string"},{"name":"ORACLE_WORKORDER","dataType":"string"},{"name":"ORACLE_PROJECT","dataType":"string"},{"name":"ORG","dataType":"string"},{"name":"WORKORDER_TYPE","dataType":"string"},{"name":"DateTime_CREATED","dataType":"dateTime"},{"name":"DateTime_COMPLETED","dataType":"dateTime"},{"name":"DateTime_MODIFIED","dataType":"dateTime"},{"name":"WORKORDER_STATUS","dataType":"string"},{"name":"QUANTITY","dataType":"double"},{"name":"CURRENT_QUANTITY","dataType":"double"},{"name":"FLOW_NAME","dataType":"string"},{"name":"SN_LOT_NUMBER","dataType":"string"},{"name":"PARTNUMBERKEY","dataType":"int64"},{"name":"REV","dataType":"string"},{"name":"DateTime_SeriesStart","dataType":"dateTime"},{"name":"CURRENT_PROCESS","dataType":"string"},{"name":"CURRENT_PROCESS_DESC","dataType":"string"},{"name":"SNOWFLAKE_UPDATE_DATE","dataType":"dateTime"},{"name":"WO_EST_COMP_DATE","dataType":"dateTime"},{"name":"PROCESS_EST_COMP_DATE","dataType":"dateTime"},{"name":"START_DATE","dataType":"dateTime"},{"name":"DUE_DATE","dataType":"dateTime"},{"name":"SHIP_DATE","dataType":"dateTime"},{"name":"WORK_ORDER_AGE","dataType":"string"},{"name":"WORK_ORDER_SERIES_AGE","dataType":"string"},{"name":"EXPEDITED","dataType":"boolean"},{"name":"Date_CREATED","dataType":"date"},{"name":"Date_COMPLETED","dataType":"date"},{"name":"ITEM_SANDBOX_KEY_ID","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-20T03:02:03.5071047+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/edd8082a-10f6-4c54-a05a-127745162d69/CUM_WORKORDERS.csv?snapshot=2022-05-20T03%3A02%3A03.4788111Z"}]},{"$type":"LocalEntity","name":"CUM_QUEUE","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"CUM_QUEUE.csv"},"attributes":[{"name":"WOQUEUEKEY","dataType":"double"},{"name":"SANDBOXKEY","dataType":"double"},{"name":"CREATE_DATE","dataType":"dateTime"},{"name":"MODIFIED_DATE","dataType":"dateTime"},{"name":"ORG","dataType":"string"},{"name":"QUEUE_CONTAINER","dataType":"string"},{"name":"PARTNUMBERKEY","dataType":"double"},{"name":"DEMAND_TYPE","dataType":"string"},{"name":"SALES_ORDER","dataType":"string"},{"name":"LINE_NUMBER","dataType":"string"},{"name":"START_DATE","dataType":"dateTime"},{"name":"SCHEDULE_DATE","dataType":"dateTime"},{"name":"DUE_DATE","dataType":"dateTime"},{"name":"CUSTOMER","dataType":"string"},{"name":"CUSTOMER_PO","dataType":"string"},{"name":"WORK_ORDER_TYPE","dataType":"string"},{"name":"QUANTITY","dataType":"double"},{"name":"ORACLE_WORK_ORDER","dataType":"string"},{"name":"ORACLE_PROJECT","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-20T03:02:04.1790273+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/edd8082a-10f6-4c54-a05a-127745162d69/CUM_QUEUE.csv?snapshot=2022-05-20T03%3A02%3A04.1564252Z"}]}]}