{"name":"COHERENT_SNOWFLAKE_AGILEPQM","description":"22.02,22 - für die WEP Auswertung \n                 dataset - DM_xNCR_Daten.pbix","version":"1.0","culture":"en-US","modifiedTime":"2022-04-29T06:10:21.6519401+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"XXREP_ALL_NCR_DATAMART_V":{"queryId":"23ba911d-7afa-4fe1-b644-fd2043d4f2a6","queryName":"XXREP_ALL_NCR_DATAMART_V","loadEnabled":true},"XXCOH_AGILE_SIGNOFF_DATAMART_NCRs":{"queryId":"cd001ed9-ab56-42b3-869d-d5c7131469b3","queryName":"XXCOH_AGILE_SIGNOFF_DATAMART_NCRs","loadEnabled":true},"XXREP_ALL_NCR_DATAMART_V only for test":{"queryId":"9c458d13-3ca6-4385-8eca-21150e4fc757","queryName":"XXREP_ALL_NCR_DATAMART_V only for test","loadEnabled":true},"g_290422XXCOH_AGILE_SIGNOFF_DATAMART_forTest":{"queryId":"4f31a01d-8309-4940-98c8-c5e6f58d8ac5","queryName":"g_290422XXCOH_AGILE_SIGNOFF_DATAMART_forTest","loadEnabled":true},"XXCOH_AGILE_SIGNOFF_DATAMART":{"queryId":"ff9c7858-8621-4949-8470-3fd7d6d4f6d7","queryName":"XXCOH_AGILE_SIGNOFF_DATAMART","loadEnabled":true},"DATAFLOW_COMMENTS":{"queryId":"e8e2a63f-e2ee-4f2e-bfd4-d3ef5bccf284","queryName":"DATAFLOW_COMMENTS","loadEnabled":true}},"document":"section Section1;\r\nshared XXREP_ALL_NCR_DATAMART_V = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 1\" = Navigation{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXREP_ALL_NCR_DATAMART_V\", Kind = \"View\"]}[Data],\r\n  #\"Filtered rows_OrgID1\" = Table.SelectRows(#\"Navigation 2\", each [ORG] = \"LDP\" and [STATUS] <> \"Cancel\"),\r\n  #\"Sorted rows 1\" = Table.Sort(#\"Filtered rows_OrgID1\", {{\"DATE_ORIGINATED\", Order.Descending}}),\r\n  #\"Duplicated column\" = Table.DuplicateColumn(#\"Sorted rows 1\", \"DATAMART_REBUILD_DATE\", \"DATAMART_REBUILD_DATE_ONLY\"),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Duplicated column\", {{\"DATAMART_REBUILD_DATE_ONLY\", type date}}),\r\n  #\"Reordered columns\" = Table.ReorderColumns(#\"Changed column type\", {\"NCR_NUMBER\", \"NCR_DESCRIPTION\", \"STATUS\", \"ORIGIN\", \"ORG\", \"SUPPLIER\", \"ORIGINATOR\", \"ACCESS_ORGS\", \"DATE_ORIGINATED\", \"DATE_ORIGINATED_LEGACY\", \"DATE_CLOSED\", \"ITEM\", \"ITEM_DESCRIPTION\", \"DEFECT_DESCRIPTION\", \"QTY_INSP\", \"DEFECT_QTY\", \"UOM\", \"RESPONSIBILITY\", \"LOT_NUMBER\", \"MSO_NUMBER\", \"PO_NUM\", \"RMA_NUM\", \"WO_NUM\", \"COST\", \"REV\", \"FAI_REQD\", \"FAILURE_MODE\", \"SUB_FAILURE_MODE\", \"FAILURE_CATEGORY\", \"NPF\", \"RPR\", \"RTV\", \"RWK_E\", \"RWK_I\", \"SCP\", \"UAI\", \"SERIAL_NUM\", \"VENDOR_ID\", \"VENDOR_SITE_ID\", \"REQUEST_ID\", \"NCR_DATAMART_ID\", \"CUMULUS_USER\", \"PRODUCT_CAT\", \"SEVERITY\", \"QTY_MRB\", \"MRB_COST\", \"TOT_DISPOSITION_COST\", \"TOT_SCRAP_COST\", \"INTEGRATION_SOURCE\", \"ORACLE_SUPPLIER_NUMBER\", \"LEGAL\", \"ATTRIBUTE1\", \"ATTRIBUTE2\", \"ATTRIBUTE3\", \"ATTRIBUTE4\", \"ATTRIBUTE5\", \"ATTRIBUTE6\", \"ATTRIBUTE7\", \"ATTRIBUTE8\", \"ATTRIBUTE9\", \"ATTRIBUTE10\", \"DATAMART_REBUILD_DATE\", \"DATAMART_REBUILD_DATE_ONLY\"})\r\nin\r\n  #\"Reordered columns\";\r\nshared XXCOH_AGILE_SIGNOFF_DATAMART_NCRs = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\"),\r\n  PROD_DB_Database = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  ASCP_Schema = PROD_DB_Database{[Name = \"ASCP\", Kind = \"Schema\"]}[Data],\r\n  XXCOH_AGILE_SIGNOFF_DATAMART_Table = ASCP_Schema{[Name = \"XXCOH_AGILE_SIGNOFF_DATAMART\", Kind = \"Table\"]}[Data],\r\n  #\"Filtered rows\" = Table.SelectRows(XXCOH_AGILE_SIGNOFF_DATAMART_Table, each [SIGNOFF_OBJ_TYPE] = \"NCR\"),\r\n  #\"Reordered columns\" = Table.ReorderColumns(#\"Filtered rows\", {\"SIGNOFF_OBJ\", \"SIGNOFF_OBJ_TYPE\", \"SIGNOFF_OBJ_DESC\", \"CURRENT_WORKFLOW_STATUS\", \"WORKFLOW_STATUS\", \"ACTION\", \"REQUIRED\", \"REVIEWER\", \"SIGNOFF_USER\", \"STATUS_CHANGED_BY\", \"RUN_DATETIME\", \"LOCAL_CLIENT_TIME\", \"SIGNOFF_COMMENTS\", \"WORKFLOW\", \"SIGNOFF_DURATION\", \"REQUEST_ID\"}),\r\n  #\"Sorted rows\" = Table.Sort(#\"Reordered columns\", {{\"RUN_DATETIME\", Order.Descending}, {\"LOCAL_CLIENT_TIME\", Order.Descending}}),\r\n  #\"Filtered rows 1\" = Table.SelectRows(#\"Sorted rows\", each [CURRENT_WORKFLOW_STATUS] = \"Closed\")\r\nin\r\n  #\"Filtered rows 1\";\r\nshared #\"XXREP_ALL_NCR_DATAMART_V only for test\" = let\r\n  Source = XXREP_ALL_NCR_DATAMART_V,\r\n  #\"Removed columns 2\" = Table.RemoveColumns(Source, {\"NCR_DESCRIPTION\"}),\r\n  #\"Removed columns\" = Table.RemoveColumns(#\"Removed columns 2\", {\"SUPPLIER\", \"ITEM\", \"ITEM_DESCRIPTION\", \"DEFECT_DESCRIPTION\", \"QTY_INSP\", \"DEFECT_QTY\", \"UOM\", \"RESPONSIBILITY\", \"LOT_NUMBER\", \"MSO_NUMBER\", \"PO_NUM\", \"RMA_NUM\", \"WO_NUM\", \"COST\", \"REV\", \"FAI_REQD\", \"FAILURE_MODE\", \"SUB_FAILURE_MODE\", \"FAILURE_CATEGORY\", \"NPF\", \"RPR\", \"RTV\", \"RWK_E\", \"RWK_I\", \"SCP\", \"UAI\", \"SERIAL_NUM\", \"VENDOR_ID\", \"VENDOR_SITE_ID\", \"REQUEST_ID\", \"CUMULUS_USER\", \"PRODUCT_CAT\", \"SEVERITY\", \"QTY_MRB\", \"MRB_COST\", \"TOT_DISPOSITION_COST\", \"TOT_SCRAP_COST\", \"INTEGRATION_SOURCE\", \"ORACLE_SUPPLIER_NUMBER\"}),\r\n  #\"Reordered columns\" = Table.ReorderColumns(#\"Removed columns\", {\"NCR_NUMBER\", \"STATUS\", \"ORIGIN\", \"ORG\", \"ORIGINATOR\", \"ACCESS_ORGS\", \"DATE_ORIGINATED_LEGACY\", \"DATE_ORIGINATED\", \"DATE_CLOSED\", \"NCR_DATAMART_ID\", \"LEGAL\", \"ATTRIBUTE1\", \"ATTRIBUTE2\", \"ATTRIBUTE3\", \"ATTRIBUTE4\", \"ATTRIBUTE5\", \"ATTRIBUTE6\", \"ATTRIBUTE7\", \"ATTRIBUTE8\", \"ATTRIBUTE9\", \"ATTRIBUTE10\", \"DATAMART_REBUILD_DATE\"}),\r\n  #\"Removed columns 1\" = Table.RemoveColumns(#\"Reordered columns\", {\"ATTRIBUTE1\", \"ATTRIBUTE2\", \"ATTRIBUTE3\", \"ATTRIBUTE4\", \"ATTRIBUTE5\", \"ATTRIBUTE6\", \"ATTRIBUTE7\", \"ATTRIBUTE8\", \"ATTRIBUTE9\", \"ATTRIBUTE10\", \"LEGAL\"}),\r\n  #\"Sorted rows\" = Table.Sort(#\"Removed columns 1\", {{\"DATE_ORIGINATED\", Order.Descending}})\r\nin\r\n  #\"Sorted rows\";\r\nshared g_290422XXCOH_AGILE_SIGNOFF_DATAMART_forTest = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\"),\r\n  PROD_DB_Database = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  ASCP_Schema = PROD_DB_Database{[Name = \"ASCP\", Kind = \"Schema\"]}[Data],\r\n  XXCOH_AGILE_SIGNOFF_DATAMART_Table = ASCP_Schema{[Name = \"XXCOH_AGILE_SIGNOFF_DATAMART\", Kind = \"Table\"]}[Data],\r\n  #\"Filtered rows 1\" = Table.SelectRows(XXCOH_AGILE_SIGNOFF_DATAMART_Table, each Text.Contains([SIGNOFF_OBJ], \"NCR\")),\r\n  #\"Sorted rows\" = Table.Sort(#\"Filtered rows 1\", {{\"RUN_DATETIME\", Order.Descending}})\r\nin\r\n  #\"Sorted rows\";\r\nshared XXCOH_AGILE_SIGNOFF_DATAMART = let\r\n  Source = Table.NestedJoin(XXREP_ALL_NCR_DATAMART_V, {\"NCR_NUMBER\"}, XXCOH_AGILE_SIGNOFF_DATAMART_NCRs, {\"SIGNOFF_OBJ\"}, \"XXCOH_AGILE_SIGNOFF_DATAMART\", JoinKind.LeftOuter),\r\n  #\"Removed columns\" = Table.RemoveColumns(Source, {\"ORG\", \"SUPPLIER\", \"ACCESS_ORGS\", \"NCR_DESCRIPTION\", \"ATTRIBUTE10\", \"ATTRIBUTE9\", \"ATTRIBUTE8\", \"ATTRIBUTE7\", \"ATTRIBUTE6\", \"ATTRIBUTE5\", \"ATTRIBUTE4\", \"ATTRIBUTE3\", \"ATTRIBUTE2\", \"ATTRIBUTE1\", \"LEGAL\", \"ORACLE_SUPPLIER_NUMBER\", \"INTEGRATION_SOURCE\", \"TOT_SCRAP_COST\", \"TOT_DISPOSITION_COST\", \"MRB_COST\", \"QTY_MRB\", \"SEVERITY\", \"PRODUCT_CAT\", \"CUMULUS_USER\", \"NCR_DATAMART_ID\", \"REQUEST_ID\", \"VENDOR_SITE_ID\", \"VENDOR_ID\", \"SERIAL_NUM\", \"UAI\", \"SCP\", \"RWK_I\", \"RWK_E\", \"RTV\", \"RPR\", \"NPF\", \"FAILURE_CATEGORY\", \"SUB_FAILURE_MODE\", \"FAILURE_MODE\", \"FAI_REQD\", \"REV\", \"COST\", \"WO_NUM\", \"RMA_NUM\", \"PO_NUM\", \"MSO_NUMBER\", \"LOT_NUMBER\", \"RESPONSIBILITY\", \"UOM\", \"DEFECT_QTY\", \"QTY_INSP\", \"DEFECT_DESCRIPTION\", \"ITEM_DESCRIPTION\", \"ITEM\"}),\r\n  #\"Reordered columns 1\" = Table.ReorderColumns(#\"Removed columns\", {\"NCR_NUMBER\", \"STATUS\", \"DATE_ORIGINATED\", \"DATE_ORIGINATED_LEGACY\", \"DATE_CLOSED\", \"DATAMART_REBUILD_DATE\", \"XXCOH_AGILE_SIGNOFF_DATAMART\"}),\r\n  #\"Expanded XXCOH_AGILE_SIGNOFF_DATAMART 1\" = Table.ExpandTableColumn(#\"Reordered columns 1\", \"XXCOH_AGILE_SIGNOFF_DATAMART\", {\"SIGNOFF_OBJ\", \"SIGNOFF_OBJ_TYPE\", \"SIGNOFF_OBJ_DESC\", \"CURRENT_WORKFLOW_STATUS\", \"WORKFLOW_STATUS\", \"ACTION\", \"REQUIRED\", \"REVIEWER\", \"SIGNOFF_USER\", \"STATUS_CHANGED_BY\", \"LOCAL_CLIENT_TIME\", \"SIGNOFF_COMMENTS\", \"WORKFLOW\", \"SIGNOFF_DURATION\", \"REQUEST_ID\", \"RUN_DATETIME\"}, {\"SIGNOFF_OBJ\", \"SIGNOFF_OBJ_TYPE\", \"SIGNOFF_OBJ_DESC\", \"CURRENT_WORKFLOW_STATUS\", \"WORKFLOW_STATUS\", \"ACTION\", \"REQUIRED\", \"REVIEWER\", \"SIGNOFF_USER\", \"STATUS_CHANGED_BY\", \"LOCAL_CLIENT_TIME\", \"SIGNOFF_COMMENTS\", \"WORKFLOW\", \"SIGNOFF_DURATION\", \"REQUEST_ID\", \"RUN_DATETIME\"}),\r\n  #\"Removed columns 1\" = Table.RemoveColumns(#\"Expanded XXCOH_AGILE_SIGNOFF_DATAMART 1\", {\"SIGNOFF_OBJ\", \"SIGNOFF_OBJ_TYPE\", \"SIGNOFF_OBJ_DESC\"}),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Removed columns 1\", {{\"SIGNOFF_DURATION\", Int64.Type}}),\r\n  #\"Reordered columns\" = Table.ReorderColumns(#\"Changed column type\", {\"NCR_NUMBER\", \"STATUS\", \"ORIGIN\", \"ORIGINATOR\", \"CURRENT_WORKFLOW_STATUS\", \"DATE_ORIGINATED\", \"DATE_ORIGINATED_LEGACY\", \"DATE_CLOSED\", \"WORKFLOW_STATUS\", \"SIGNOFF_DURATION\", \"ACTION\", \"REQUIRED\", \"REVIEWER\", \"SIGNOFF_USER\", \"STATUS_CHANGED_BY\", \"LOCAL_CLIENT_TIME\", \"SIGNOFF_COMMENTS\", \"WORKFLOW\", \"REQUEST_ID\", \"DATAMART_REBUILD_DATE\", \"RUN_DATETIME\"}),\r\n  #\"Duplicated column\" = Table.DuplicateColumn(#\"Reordered columns\", \"RUN_DATETIME\", \"RUN_DATE_ONLY\"),\r\n  #\"Changed column type 1\" = Table.TransformColumnTypes(#\"Duplicated column\", {{\"RUN_DATE_ONLY\", type date}}),\r\n  #\"Sorted rows\" = Table.Sort(#\"Changed column type 1\", {{\"DATE_ORIGINATED\", Order.Descending}})\r\nin\r\n  #\"Sorted rows\";\r\nshared DATAFLOW_COMMENTS = let\r\n  Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"lVBda8IwFP0rlzyLc+5hL9sg1rR261pJ41TaEqKNWyFtJMkE//0SRHzYywaBC+ee3PNRVej+cTx5GE8n0ykaoc2GkiXHWcbziPI5ZvgdU8Y//OqgDXgQ7qAMwyNVQZMGnqFG2XxZIxBDC1XJMFuVDTy9eDwSw16qGnnyoB0IpaDrj9o42cJeWGlBGAniJDoldkpCPfibaZLmmJF5kCc8IwmOtg10FmR/dGcIyjODmtEv61Gx4DhJM8LLNMmLOL4F8I6t57gvCa1wAg5G98DEDhadddqcoRsAf3ZKhljX38XslbPtklwy+hM18gajFaUkZ3xd0Lc4K9b8mjiQIqWtbAPPHwrvXzb92siDNNK3Bk7DXyIZ2etTqFOr736wF9nQT/MD\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Date = _t, Query = _t, Comments = _t, Filter = _t, Problem = _t, #\"Comments From\" = _t]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(Source, {{\"Date\", type text}, {\"Query\", type text}, {\"Comments\", type text}, {\"Comments From\", type text}})\r\nin\r\n  #\"Changed column type\";\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"XXREP_ALL_NCR_DATAMART_V","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"XXREP_ALL_NCR_DATAMART_V.csv"},"attributes":[{"name":"NCR_NUMBER","dataType":"string"},{"name":"NCR_DESCRIPTION","dataType":"string"},{"name":"STATUS","dataType":"string"},{"name":"ORIGIN","dataType":"string"},{"name":"ORG","dataType":"string"},{"name":"SUPPLIER","dataType":"string"},{"name":"ORIGINATOR","dataType":"string"},{"name":"ACCESS_ORGS","dataType":"string"},{"name":"DATE_ORIGINATED","dataType":"date"},{"name":"DATE_ORIGINATED_LEGACY","dataType":"dateTime"},{"name":"DATE_CLOSED","dataType":"date"},{"name":"ITEM","dataType":"string"},{"name":"ITEM_DESCRIPTION","dataType":"string"},{"name":"DEFECT_DESCRIPTION","dataType":"string"},{"name":"QTY_INSP","dataType":"double"},{"name":"DEFECT_QTY","dataType":"double"},{"name":"UOM","dataType":"string"},{"name":"RESPONSIBILITY","dataType":"string"},{"name":"LOT_NUMBER","dataType":"string"},{"name":"MSO_NUMBER","dataType":"string"},{"name":"PO_NUM","dataType":"string"},{"name":"RMA_NUM","dataType":"string"},{"name":"WO_NUM","dataType":"string"},{"name":"COST","dataType":"double"},{"name":"REV","dataType":"string"},{"name":"FAI_REQD","dataType":"string"},{"name":"FAILURE_MODE","dataType":"string"},{"name":"SUB_FAILURE_MODE","dataType":"string"},{"name":"FAILURE_CATEGORY","dataType":"string"},{"name":"NPF","dataType":"double"},{"name":"RPR","dataType":"double"},{"name":"RTV","dataType":"double"},{"name":"RWK_E","dataType":"double"},{"name":"RWK_I","dataType":"double"},{"name":"SCP","dataType":"double"},{"name":"UAI","dataType":"double"},{"name":"SERIAL_NUM","dataType":"string"},{"name":"VENDOR_ID","dataType":"double"},{"name":"VENDOR_SITE_ID","dataType":"double"},{"name":"REQUEST_ID","dataType":"double"},{"name":"NCR_DATAMART_ID","dataType":"double"},{"name":"CUMULUS_USER","dataType":"string"},{"name":"PRODUCT_CAT","dataType":"string"},{"name":"SEVERITY","dataType":"string"},{"name":"QTY_MRB","dataType":"double"},{"name":"MRB_COST","dataType":"double"},{"name":"TOT_DISPOSITION_COST","dataType":"double"},{"name":"TOT_SCRAP_COST","dataType":"double"},{"name":"INTEGRATION_SOURCE","dataType":"string"},{"name":"ORACLE_SUPPLIER_NUMBER","dataType":"string"},{"name":"LEGAL","dataType":"string"},{"name":"ATTRIBUTE1","dataType":"string"},{"name":"ATTRIBUTE2","dataType":"string"},{"name":"ATTRIBUTE3","dataType":"string"},{"name":"ATTRIBUTE4","dataType":"string"},{"name":"ATTRIBUTE5","dataType":"string"},{"name":"ATTRIBUTE6","dataType":"string"},{"name":"ATTRIBUTE7","dataType":"string"},{"name":"ATTRIBUTE8","dataType":"string"},{"name":"ATTRIBUTE9","dataType":"string"},{"name":"ATTRIBUTE10","dataType":"string"},{"name":"DATAMART_REBUILD_DATE","dataType":"dateTime"},{"name":"DATAMART_REBUILD_DATE_ONLY","dataType":"date"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-11T22:01:18.1800455+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/05ff13f6-eb01-4d32-ba83-9abfd40df349/XXREP_ALL_NCR_DATAMART_V.csv?snapshot=2022-06-11T22%3A01%3A17.1762680Z"}]},{"$type":"LocalEntity","name":"XXCOH_AGILE_SIGNOFF_DATAMART_NCRs","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"XXCOH_AGILE_SIGNOFF_DATAMART_NCRs.csv"},"attributes":[{"name":"SIGNOFF_OBJ","dataType":"string"},{"name":"SIGNOFF_OBJ_TYPE","dataType":"string"},{"name":"SIGNOFF_OBJ_DESC","dataType":"string"},{"name":"CURRENT_WORKFLOW_STATUS","dataType":"string"},{"name":"WORKFLOW_STATUS","dataType":"string"},{"name":"ACTION","dataType":"string"},{"name":"REQUIRED","dataType":"string"},{"name":"REVIEWER","dataType":"string"},{"name":"SIGNOFF_USER","dataType":"string"},{"name":"STATUS_CHANGED_BY","dataType":"string"},{"name":"RUN_DATETIME","dataType":"dateTime"},{"name":"LOCAL_CLIENT_TIME","dataType":"dateTime"},{"name":"SIGNOFF_COMMENTS","dataType":"string"},{"name":"WORKFLOW","dataType":"string"},{"name":"SIGNOFF_DURATION","dataType":"string"},{"name":"REQUEST_ID","dataType":"string"},{"name":"RUN_USER","dataType":"string"},{"name":"ATTRIBUTE1","dataType":"string"},{"name":"ATTRIBUTE2","dataType":"string"},{"name":"ATTRIBUTE3","dataType":"string"},{"name":"ATTRIBUTE4","dataType":"string"},{"name":"ATTRIBUTE5","dataType":"string"},{"name":"ATTRIBUTE6","dataType":"string"},{"name":"ATTRIBUTE7","dataType":"string"},{"name":"ATTRIBUTE8","dataType":"string"},{"name":"ATTRIBUTE9","dataType":"string"},{"name":"ATTRIBUTE10","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-11T22:02:01.8978178+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/05ff13f6-eb01-4d32-ba83-9abfd40df349/XXCOH_AGILE_SIGNOFF_DATAMART_NCRs.csv?snapshot=2022-06-11T22%3A01%3A52.6018855Z"}]},{"$type":"LocalEntity","name":"XXREP_ALL_NCR_DATAMART_V only for test","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"XXREP_ALL_NCR_DATAMART_V%20only%20for%20test.csv"},"annotations":[{"name":"pbi:EntityTypeDisplayHint","value":"CalculatedEntity"}],"attributes":[{"name":"NCR_NUMBER","dataType":"string"},{"name":"STATUS","dataType":"string"},{"name":"ORIGIN","dataType":"string"},{"name":"ORG","dataType":"string"},{"name":"ORIGINATOR","dataType":"string"},{"name":"ACCESS_ORGS","dataType":"string"},{"name":"DATE_ORIGINATED_LEGACY","dataType":"dateTime"},{"name":"DATE_ORIGINATED","dataType":"date"},{"name":"DATE_CLOSED","dataType":"date"},{"name":"NCR_DATAMART_ID","dataType":"double"},{"name":"DATAMART_REBUILD_DATE","dataType":"dateTime"},{"name":"DATAMART_REBUILD_DATE_ONLY","dataType":"date"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-11T22:01:20.914437+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/05ff13f6-eb01-4d32-ba83-9abfd40df349/XXREP_ALL_NCR_DATAMART_V%20only%20for%20test.csv?snapshot=2022-06-11T22%3A01%3A20.8820298Z"}]},{"$type":"LocalEntity","name":"g_290422XXCOH_AGILE_SIGNOFF_DATAMART_forTest","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"g_290422XXCOH_AGILE_SIGNOFF_DATAMART_forTest.csv"},"attributes":[{"name":"SIGNOFF_OBJ","dataType":"string"},{"name":"SIGNOFF_OBJ_TYPE","dataType":"string"},{"name":"SIGNOFF_OBJ_DESC","dataType":"string"},{"name":"CURRENT_WORKFLOW_STATUS","dataType":"string"},{"name":"WORKFLOW_STATUS","dataType":"string"},{"name":"ACTION","dataType":"string"},{"name":"REQUIRED","dataType":"string"},{"name":"REVIEWER","dataType":"string"},{"name":"SIGNOFF_USER","dataType":"string"},{"name":"STATUS_CHANGED_BY","dataType":"string"},{"name":"LOCAL_CLIENT_TIME","dataType":"dateTime"},{"name":"SIGNOFF_COMMENTS","dataType":"string"},{"name":"WORKFLOW","dataType":"string"},{"name":"SIGNOFF_DURATION","dataType":"string"},{"name":"REQUEST_ID","dataType":"string"},{"name":"RUN_DATETIME","dataType":"dateTime"},{"name":"RUN_USER","dataType":"string"},{"name":"ATTRIBUTE1","dataType":"string"},{"name":"ATTRIBUTE2","dataType":"string"},{"name":"ATTRIBUTE3","dataType":"string"},{"name":"ATTRIBUTE4","dataType":"string"},{"name":"ATTRIBUTE5","dataType":"string"},{"name":"ATTRIBUTE6","dataType":"string"},{"name":"ATTRIBUTE7","dataType":"string"},{"name":"ATTRIBUTE8","dataType":"string"},{"name":"ATTRIBUTE9","dataType":"string"},{"name":"ATTRIBUTE10","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-11T22:01:55.7935593+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/05ff13f6-eb01-4d32-ba83-9abfd40df349/g_290422XXCOH_AGILE_SIGNOFF_DATAMART_forTest.csv?snapshot=2022-06-11T22%3A01%3A55.7849658Z"}]},{"$type":"LocalEntity","name":"XXCOH_AGILE_SIGNOFF_DATAMART","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"XXCOH_AGILE_SIGNOFF_DATAMART.csv"},"annotations":[{"name":"pbi:EntityTypeDisplayHint","value":"CalculatedEntity"}],"attributes":[{"name":"NCR_NUMBER","dataType":"string"},{"name":"STATUS","dataType":"string"},{"name":"ORIGIN","dataType":"string"},{"name":"ORIGINATOR","dataType":"string"},{"name":"CURRENT_WORKFLOW_STATUS","dataType":"string"},{"name":"DATE_ORIGINATED","dataType":"date"},{"name":"DATE_ORIGINATED_LEGACY","dataType":"dateTime"},{"name":"DATE_CLOSED","dataType":"date"},{"name":"DATAMART_REBUILD_DATE_ONLY","dataType":"date"},{"name":"WORKFLOW_STATUS","dataType":"string"},{"name":"SIGNOFF_DURATION","dataType":"int64"},{"name":"ACTION","dataType":"string"},{"name":"REQUIRED","dataType":"string"},{"name":"REVIEWER","dataType":"string"},{"name":"SIGNOFF_USER","dataType":"string"},{"name":"STATUS_CHANGED_BY","dataType":"string"},{"name":"LOCAL_CLIENT_TIME","dataType":"dateTime"},{"name":"SIGNOFF_COMMENTS","dataType":"string"},{"name":"WORKFLOW","dataType":"string"},{"name":"REQUEST_ID","dataType":"string"},{"name":"DATAMART_REBUILD_DATE","dataType":"dateTime"},{"name":"RUN_DATETIME","dataType":"dateTime"},{"name":"RUN_DATE_ONLY","dataType":"date"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-11T22:02:23.23601+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/05ff13f6-eb01-4d32-ba83-9abfd40df349/XXCOH_AGILE_SIGNOFF_DATAMART.csv?snapshot=2022-06-11T22%3A02%3A23.1704595Z"}]},{"$type":"LocalEntity","name":"DATAFLOW_COMMENTS","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"DATAFLOW_COMMENTS.csv"},"attributes":[{"name":"Date","dataType":"string"},{"name":"Query","dataType":"string"},{"name":"Comments","dataType":"string"},{"name":"Filter","dataType":"string"},{"name":"Problem","dataType":"string"},{"name":"Comments From","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-11T22:01:03.7137232+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/05ff13f6-eb01-4d32-ba83-9abfd40df349/DATAFLOW_COMMENTS.csv?snapshot=2022-06-11T22%3A01%3A03.6794227Z"}]}]}