{"name":"COHREP_SITE_INVENTORY_VELOCITY_TRX1","description":"","version":"1.0","culture":"en-US","modifiedTime":"2021-01-29T09:47:14.8235004+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":true,"queriesMetadata":{"Inventory_Velocity":{"queryId":"9a7cdfe9-8954-4419-8a39-1c236648ef36","queryName":"Inventory_Velocity","queryGroupId":"root","loadEnabled":true},"ORG":{"queryId":"b522362a-e798-4d0a-ac5d-f5605bd1d732","queryName":"ORG"},"YearOffset":{"queryId":"54890c1e-de20-47a5-a6c8-30dcf297aad9","queryName":"YearOffset"}},"document":"section Section1;\r\nshared Inventory_Velocity = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, \n  Query=\"\n SELECT\n    to_date(al1.date_run) - 1                    snapshot_date,\n    al1.period_year * 100 + al1.fiscal_week_id run_id,\n    (\n        SELECT\n            MAX(period_date)\n        FROM\n            (\n                SELECT\n                    gdpm.period_set_name,\n                    gp.period_name,\n                    gdpm.accounting_date                                                                             period_date,\n                    gp.period_year,\n                    gp.period_num,\n                    gp.quarter_num,\n                    gp.year_start_date,\n                    gp.quarter_start_date,\n                    ( gp.period_year * 100 + ceil((gdpm.accounting_date - gp.year_start_date + 1) / 7) )             week_series\n                FROM\n                    gl.gl_date_period_map    gdpm,\n                    gl.gl_periods            gp\n                WHERE\n                        gdpm.period_set_name = 'COHR Calendar'\n                    AND gp.period_name = gdpm.period_name\n                    AND gdpm.period_set_name = gp.period_set_name\n            ) cal\n        WHERE\n            cal.week_series = al1.period_year * 100 + al1.fiscal_week_id\n    ) run_id_date,\n    al1.me_flag,\n    al1.freeze_data,\n    al1.osp_assemblies,\n    al1.planning_method,\n    al1.organization_code,\n    al1.item_number,\n    al1.item_description,\n    al1.uom,\n    al1.item_status,\n    al1.item_type,\n    nvl(SUBSTR(al1.current_mrp_abc_class,1,1), 'Blank')        current_abc_class,       \n    CASE\n        WHEN al1.org_tbu IS NULL THEN\n            NULL\n        ELSE\n            al1.org_tbu\n            || '.'\n            || al1.org_family\n            || '.'\n            || al1.org_line\n            || '.'\n            || al1.org_forecast_field\n    END org_product,\n    CASE\n        WHEN al1.mas_tbu IS NULL THEN\n            NULL\n        ELSE\n            al1.mas_tbu\n            || '.'\n            || al1.mas_family\n            || '.'\n            || al1.mas_line\n            || '.'\n            || al1.mas_forecast_field\n    END mas_product,\n    CASE\n        WHEN al1.org_tbu IS NOT NULL THEN\n            al1.org_tbu\n            || '.'\n            || al1.org_family\n            || '.'\n            || al1.org_line\n            || '.'\n            || al1.org_forecast_field\n        WHEN al1.mas_tbu IS NOT NULL THEN\n            al1.mas_tbu\n            || '.'\n            || al1.mas_family\n            || '.'\n            || al1.mas_line\n            || '.'\n            || al1.mas_forecast_field\n        ELSE\n            NULL\n    END product_key,\n    al1.planner,\n    al1.buyer,\n    al1.min_max_min_qty,\n    al1.min_max_max_qty,\n    al1.min_order_qty,\n    al1.max_order_qty,\n    al1.fixed_order_qty,\n    al1.fixed_days_supply,\n    al1.fixed_lot_size_multiplier,\n    al1.acceptable_early_days,\n    al1.processing_lead_time,\n    al1.cumulative_mfg_lt,\n    al1.cumulative_lt,\n    CASE\n        WHEN al1.planning_method = 'Min-Max' THEN\n            al1.attribute_lt\n        ELSE\n            al1.active_supplier_lt\n    END effective_lead_time,\n    al1.active_supplier_lt,\n    al1.purch_asl_lt,\n    al1.subinventory_min_max_lt,\n    al1.kanban_repl_lt,\n    al1.total_gr_26_weeks,\n    al1.average_daily_demand,\n    al1.gross_inventory_turns,\n    al1.item_cost,\n    al1.currency_rate,\n    al1.item_cost_usd,\n    al1.sourcing_commodity,\n    al1.sr_vendor,\n    al1.sr_vendor_site_code,\n    al1.sr_pct,\n    al1.sr_asl_status,\n    al1.sr_vndr_src_org,\n    al1.safety_stock_qty,\n    al1.safety_stock_value,\n    al1.safety_stock_value_usd,\n    al1.inventory_value,\n    al1.inventory_value_usd,\n    al1.receiving_quantity,\n    al1.receiving_value,\n    al1.receiving_value_usd,\n    al1.intransit_quantity,\n    al1.intransit_value,\n    al1.intransit_value_usd,\n    al1.total_quantity,\n    al1.total_onhand_qty,\n    al1.on_hand_days_of_supply,\n    al1.open_po_qty,\n    al1.open_po_value,\n    al1.open_po_value_usd,\n    al1.on_order_days_of_supply,\n    al1.wip_in_process_qty,\n    al1.wip_in_process_value,\n    al1.wip_in_process_value_usd,\n    al1.wip_days_of_supply,\n    al1.total_days_of_supply,\n    al1.proj_spend_next_26_weeks,\n    al1.proj_spend_next_26_weeks_usd,\n    al1.open_blankets,\n    al1.number_of_open_blankets,\n    al1.sum_remaining_amount,\n    al1.sum_usd_remaining_amount,\n    al1.sum_remaining_qty_calculated,\n    al1.blanket_days_supply_remaining,\n    al1.active_or_inactive,\n    al1.attribute_lt,\n    al1.onhand_qty_non_asset,\n    al1.onhand_qty_asset,\n    al1.ir_po_qty,\n    al1.ir_po_value,\n    al1.ir_po_value_usd,\n    al1.onorder_po_qty,\n    al1.onorder_po_value,\n    al1.onorder_po_value_usd,\n    al1.sr_vendor_site_id,\n    al1.weekly_gross_reqs_week_0,\n    al1.weekly_gross_reqs_week_1,\n    al1.weekly_gross_reqs_week_2,\n    al1.weekly_gross_reqs_week_3,\n    al1.weekly_gross_reqs_week_4,\n    al1.weekly_gross_reqs_week_5,\n    al1.weekly_gross_reqs_week_6,\n    al1.weekly_gross_reqs_week_7,\n    al1.weekly_gross_reqs_week_8,\n    al1.weekly_gross_reqs_week_9,\n    al1.weekly_gross_reqs_week_10,\n    al1.weekly_gross_reqs_week_11,\n    al1.weekly_gross_reqs_week_12,\n    al1.weekly_gross_reqs_week_13,\n    al1.weekly_gross_reqs_week_14,\n    al1.weekly_gross_reqs_week_15,\n    al1.weekly_gross_reqs_week_16,\n    al1.weekly_gross_reqs_week_17,\n    al1.weekly_gross_reqs_week_18,\n    al1.weekly_gross_reqs_week_19,\n    al1.weekly_gross_reqs_week_20,\n    al1.weekly_gross_reqs_week_21,\n    al1.weekly_gross_reqs_week_22,\n    al1.weekly_gross_reqs_week_23,\n    al1.weekly_gross_reqs_week_24,\n    al1.weekly_gross_reqs_week_25,\n    al1.weekly_gross_reqs_week_26,\n    al1.total_usage_26_weeks,\n    al1.so_usage_13_weeks,\n    al1.so_usage_26_weeks,\n    al1.wo_usage_13_weeks,\n    al1.wo_usage_26_weeks,\n    al1.spc_usage_volume_13_weeks_usd,\n    al1.ave_daily_usage_26_weeks,\n    al1.kanban_type,\n    al1.lt_grouping,\n    al1.lt_grouping_id,\n    al1.sec_reporting,\n    al1.operations_reporting\nFROM\n    apps.xx_invascp_fact al1\nWHERE\n     al1.organization_code = '\"&ORG&\"'\n       AND ( al1.me_flag = 'Y'\n          OR al1.period_name = (\n        SELECT\n            gp.period_name\n        FROM\n            gl.gl_date_period_map    gdpm,\n            gl.gl_periods            gp\n        WHERE\n                gdpm.period_set_name = 'COHR Calendar'\n            AND gp.period_name = gdpm.period_name\n            AND gdpm.period_set_name = gp.period_set_name\n            AND gdpm.accounting_date = trunc(sysdate)\n    ) )\n    and al1.period_year >= (select period_year - \"&YearOffset&\"\n    from gl.gl_periods            gp\nwhere trunc(sysdate) between gp.start_date and gp.end_date\nand period_set_name = 'COHR Calendar')\n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"SNAPSHOT_DATE\", \"Snapshot Date\"}, {\"ITEM_NUMBER\", \"Item Number\"}, {\"ITEM_DESCRIPTION\", \"Item Description\"}, {\"UOM\", \"Unit of Measure\"}, {\"ITEM_STATUS\", \"Item Status\"}, {\"ITEM_TYPE\", \"Item Type\"}, {\"PLANNER\", \"Planner Code\"}, {\"BUYER\", \"Default Buyer\"}, {\"MIN_MAX_MIN_QTY\", \"Min Max Minimum Quantity\"}, {\"MIN_MAX_MAX_QTY\", \"Min Max Maximum Quantity\"}, {\"MIN_ORDER_QTY\", \"MInimum Order Quantity\"}, {\"MAX_ORDER_QTY\", \"Maximum Order Quantity\"}, {\"FIXED_ORDER_QTY\", \"Fixed Order Quantity\"}, {\"FIXED_DAYS_SUPPLY\", \"Fixed Days Supply\"}, {\"FIXED_LOT_SIZE_MULTIPLIER\", \"Fixed Lot Multiplier\"}, {\"ACCEPTABLE_EARLY_DAYS\", \"Acceptable Early Days\"}, {\"PROCESSING_LEAD_TIME\", \"Processing Lead Time\"}, {\"CUMULATIVE_MFG_LT\", \"Cummulative Manufacturing Lead Time\"}, {\"CUMULATIVE_LT\", \"Cumulative Lead Time\"}, {\"ACTIVE_SUPPLIER_LT\", \"Active Supplier Lead Time\"}, {\"PURCH_ASL_LT\", \"Purchasing ASL Lead Time\"}, {\"SUBINVENTORY_MIN_MAX_LT\", \"Subinventory Min Max Lead Time\"}, {\"KANBAN_REPL_LT\", \"Kanban Replenishment Lead Time\"}, {\"TOTAL_GR_26_WEEKS\", \"Gross Requirement 26 Weeks\"}, {\"AVERAGE_DAILY_DEMAND\", \"Average Daily Demand\"}, {\"GROSS_INVENTORY_TURNS\", \"Gross Inventory Turn\"}, {\"ITEM_COST\", \"Item Cost\"}, {\"CURRENCY_RATE\", \"Currency Rate\"}, {\"ITEM_COST_USD\", \"Item Cost USD\"}, {\"SOURCING_COMMODITY\", \"Sourcing Commodity\"}, {\"SR_VENDOR\", \"Sourcing Rule Vendor\"}, {\"SR_VENDOR_SITE_CODE\", \"Sourcing Rule Vendor Site Code\"}, {\"SR_PCT\", \"Sourcing Rule  Percent\"}, {\"SR_ASL_STATUS\", \"Sourcing Rule ASL Status\"}, {\"SR_VNDR_SRC_ORG\", \"Sourcing Vendor or ORG\"}, {\"SAFETY_STOCK_QTY\", \"Safety Stock Quantity\"}, {\"SAFETY_STOCK_VALUE\", \"Safety Stock Value\"}, {\"SAFETY_STOCK_VALUE_USD\", \"Safety Stock Value USD\"}, {\"INVENTORY_VALUE_USD\", \"Onhand Value USD\"}, {\"RECEIVING_QUANTITY\", \"Receiving Quantity\"}, {\"RECEIVING_VALUE\", \"Receiving Value\"}, {\"RECEIVING_VALUE_USD\", \"Receiving Value USD\"}, {\"INTRANSIT_QUANTITY\", \"Intransit Quantity\"}, {\"INTRANSIT_VALUE\", \"Intransit Value\"}, {\"INTRANSIT_VALUE_USD\", \"Intransit Value USD\"}, {\"TOTAL_QUANTITY\", \"Total Quantity\"}, {\"TOTAL_ONHAND_QTY\", \"Total Onhand  Quantity\"}, {\"ON_HAND_DAYS_OF_SUPPLY\", \"Onhand Days of Supply\"}, {\"OPEN_PO_QTY\", \"Open PO Quantity\"}, {\"INVENTORY_VALUE\", \"Onhand Value\"}, {\"OPEN_PO_VALUE\", \"Open PO Value\"}, {\"OPEN_PO_VALUE_USD\", \"Open PO Value USD\"}, {\"ON_ORDER_DAYS_OF_SUPPLY\", \"On Order Days of Supply\"}, {\"WIP_IN_PROCESS_QTY\", \"WIP Quantity\"}, {\"WIP_IN_PROCESS_VALUE\", \"WIP Value\"}, {\"WIP_IN_PROCESS_VALUE_USD\", \"WIP Value USD\"}, {\"WIP_DAYS_OF_SUPPLY\", \"WIP Days of Supply\"}, {\"TOTAL_DAYS_OF_SUPPLY\", \"Total Days of Supply\"}, {\"PROJ_SPEND_NEXT_26_WEEKS\", \"Projected Spend Next 26 Weeks\"}, {\"PROJ_SPEND_NEXT_26_WEEKS_USD\", \"Projected Spend Next 26 Weeks USD\"}, {\"OPEN_BLANKETS\", \"Open Blanket\"}, {\"NUMBER_OF_OPEN_BLANKETS\", \"Number of Open Blanket\"}, {\"SUM_REMAINING_AMOUNT\", \"Total Blanket Remaining Amount\"}, {\"SUM_USD_REMAINING_AMOUNT\", \"Total Blanket Remaining Amount USD\"}, {\"SUM_REMAINING_QTY_CALCULATED\", \"Total Blanket Remaining Quantity\"}, {\"BLANKET_DAYS_SUPPLY_REMAINING\", \"Blanket Remaining Days of Supply\"}, {\"ACTIVE_OR_INACTIVE\", \"Supply Chain Status\"}, {\"ONHAND_QTY_NON_ASSET\", \"Onhand Quantity Non Asset\"}, {\"ONHAND_QTY_ASSET\", \"Onhand Quantity Asset\"}, {\"IR_PO_QTY\", \"IR PO Quantity\"}, {\"IR_PO_VALUE\", \"IR PO Value\"}, {\"IR_PO_VALUE_USD\", \"IR PO Value USD\"}, {\"ONORDER_PO_QTY\", \"On Order PO Quantity\"}, {\"ONORDER_PO_VALUE\", \"On Order PO Value\"}, {\"ONORDER_PO_VALUE_USD\", \"On Order PO Value USD\"}, {\"SR_VENDOR_SITE_ID\", \"Sourcing Rule Vendor Site ID\"}, {\"MAS_PRODUCT\", \"MAS Product\"}, {\"FREEZE_DATA\", \"Freeze Data\"}, {\"ORG_PRODUCT\", \"Org Product\"}, {\"PRODUCT_KEY\", \"Product Key\"}, {\"ORGANIZATION_CODE\", \"Organization Code\"}, {\"OSP_ASSEMBLIES\", \"OSP Assemblies\"}, {\"PLANNING_METHOD\", \"Planning Method\"}, {\"CURRENT_ABC_CLASS\", \"Current ABC Class\"}, {\"ME_FLAG\", \"Month End Flag\"}, {\"ATTRIBUTE_LT\", \"Attribute Lead Time\"}, {\"WEEKLY_GROSS_REQS_WEEK_0\", \"GR W0\"}, {\"WEEKLY_GROSS_REQS_WEEK_1\", \"GR W1\"}, {\"WEEKLY_GROSS_REQS_WEEK_2\", \"GR W2\"}, {\"WEEKLY_GROSS_REQS_WEEK_3\", \"GR W3\"}, {\"WEEKLY_GROSS_REQS_WEEK_4\", \"GR W4\"}, {\"WEEKLY_GROSS_REQS_WEEK_5\", \"GR W5\"}, {\"WEEKLY_GROSS_REQS_WEEK_6\", \"GR W6\"}, {\"WEEKLY_GROSS_REQS_WEEK_7\", \"GR W7\"}, {\"WEEKLY_GROSS_REQS_WEEK_8\", \"GR W8\"}, {\"WEEKLY_GROSS_REQS_WEEK_9\", \"GR W9\"}, {\"WEEKLY_GROSS_REQS_WEEK_10\", \"GR W10\"}, {\"WEEKLY_GROSS_REQS_WEEK_11\", \"GR W11\"}, {\"WEEKLY_GROSS_REQS_WEEK_12\", \"GR W12\"}, {\"WEEKLY_GROSS_REQS_WEEK_13\", \"GR W13\"}, {\"WEEKLY_GROSS_REQS_WEEK_14\", \"GR W14\"}, {\"WEEKLY_GROSS_REQS_WEEK_15\", \"GR W15\"}, {\"WEEKLY_GROSS_REQS_WEEK_16\", \"GR W16\"}, {\"WEEKLY_GROSS_REQS_WEEK_17\", \"GR W17\"}, {\"WEEKLY_GROSS_REQS_WEEK_18\", \"GR W18\"}, {\"WEEKLY_GROSS_REQS_WEEK_19\", \"GR W19\"}, {\"WEEKLY_GROSS_REQS_WEEK_20\", \"GR W20\"}, {\"WEEKLY_GROSS_REQS_WEEK_21\", \"GR W21\"}, {\"WEEKLY_GROSS_REQS_WEEK_22\", \"GR W22\"}, {\"WEEKLY_GROSS_REQS_WEEK_23\", \"GR W23\"}, {\"WEEKLY_GROSS_REQS_WEEK_24\", \"GR W24\"}, {\"WEEKLY_GROSS_REQS_WEEK_25\", \"GR W25\"}, {\"WEEKLY_GROSS_REQS_WEEK_26\", \"GR W26\"}, {\"KANBAN_TYPE\", \"Kanban Type\"}, {\"TOTAL_USAGE_26_WEEKS\", \"Total Usage 26 Weeks\"}, {\"AVE_DAILY_USAGE_26_WEEKS\", \"Average Daily Usage 26 Weeks\"}, {\"SO_USAGE_13_WEEKS\", \"Sales Usage 13 Weeks\"}, {\"SO_USAGE_26_WEEKS\", \"Sales Usage 26 Weeks\"}, {\"SPC_USAGE_VOLUME_13_WEEKS_USD\", \"Usage 13 Weeks Value USD\"}, {\"WO_USAGE_26_WEEKS\", \"WO Usage 26 Weeks\"}, {\"WO_USAGE_13_WEEKS\", \"WO Usage 13 Weeks\"}, {\"LT_GROUPING\", \"Inventory Velocity LT Grouping\"}, {\"SEC_REPORTING\", \"SEC Reporting\"}, {\"OPERATIONS_REPORTING\", \"Operations Reporting\"}, {\"EFFECTIVE_LEAD_TIME\", \"Effective Lead Time\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared ORG = let\r\n  ORG = \"LDP\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type text]\r\nin\r\n  ORG;\r\nshared YearOffset = let\r\n  YearOffset = \"5\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type text]\r\nin\r\n  YearOffset;\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"Inventory_Velocity","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Inventory_Velocity.csv"},"attributes":[{"name":"Snapshot Date","dataType":"dateTime"},{"name":"RUN_ID","dataType":"double"},{"name":"RUN_ID_DATE","dataType":"dateTime"},{"name":"Month End Flag","dataType":"string"},{"name":"Freeze Data","dataType":"string"},{"name":"OSP Assemblies","dataType":"string"},{"name":"Planning Method","dataType":"string"},{"name":"Organization Code","dataType":"string"},{"name":"Item Number","dataType":"string"},{"name":"Item Description","dataType":"string"},{"name":"Unit of Measure","dataType":"string"},{"name":"Item Status","dataType":"string"},{"name":"Item Type","dataType":"string"},{"name":"Current ABC Class","dataType":"string"},{"name":"Org Product","dataType":"string"},{"name":"MAS Product","dataType":"string"},{"name":"Product Key","dataType":"string"},{"name":"Planner Code","dataType":"string"},{"name":"Default Buyer","dataType":"string"},{"name":"Min Max Minimum Quantity","dataType":"double"},{"name":"Min Max Maximum Quantity","dataType":"double"},{"name":"MInimum Order Quantity","dataType":"double"},{"name":"Maximum Order Quantity","dataType":"double"},{"name":"Fixed Order Quantity","dataType":"double"},{"name":"Fixed Days Supply","dataType":"double"},{"name":"Fixed Lot Multiplier","dataType":"double"},{"name":"Acceptable Early Days","dataType":"double"},{"name":"Processing Lead Time","dataType":"double"},{"name":"Cummulative Manufacturing Lead Time","dataType":"double"},{"name":"Cumulative Lead Time","dataType":"double"},{"name":"Effective Lead Time","dataType":"double"},{"name":"Active Supplier Lead Time","dataType":"double"},{"name":"Purchasing ASL Lead Time","dataType":"double"},{"name":"Subinventory Min Max Lead Time","dataType":"double"},{"name":"Kanban Replenishment Lead Time","dataType":"double"},{"name":"Gross Requirement 26 Weeks","dataType":"double"},{"name":"Average Daily Demand","dataType":"double"},{"name":"Gross Inventory Turn","dataType":"double"},{"name":"Item Cost","dataType":"double"},{"name":"Currency Rate","dataType":"double"},{"name":"Item Cost USD","dataType":"double"},{"name":"Sourcing Commodity","dataType":"string"},{"name":"Sourcing Rule Vendor","dataType":"string"},{"name":"Sourcing Rule Vendor Site Code","dataType":"string"},{"name":"Sourcing Rule  Percent","dataType":"string"},{"name":"Sourcing Rule ASL Status","dataType":"string"},{"name":"Sourcing Vendor or ORG","dataType":"string"},{"name":"Safety Stock Quantity","dataType":"double"},{"name":"Safety Stock Value","dataType":"double"},{"name":"Safety Stock Value USD","dataType":"double"},{"name":"Onhand Value","dataType":"double"},{"name":"Onhand Value USD","dataType":"double"},{"name":"Receiving Quantity","dataType":"double"},{"name":"Receiving Value","dataType":"double"},{"name":"Receiving Value USD","dataType":"double"},{"name":"Intransit Quantity","dataType":"double"},{"name":"Intransit Value","dataType":"double"},{"name":"Intransit Value USD","dataType":"double"},{"name":"Total Quantity","dataType":"double"},{"name":"Total Onhand  Quantity","dataType":"double"},{"name":"Onhand Days of Supply","dataType":"double"},{"name":"Open PO Quantity","dataType":"double"},{"name":"Open PO Value","dataType":"double"},{"name":"Open PO Value USD","dataType":"double"},{"name":"On Order Days of Supply","dataType":"double"},{"name":"WIP Quantity","dataType":"double"},{"name":"WIP Value","dataType":"double"},{"name":"WIP Value USD","dataType":"double"},{"name":"WIP Days of Supply","dataType":"double"},{"name":"Total Days of Supply","dataType":"double"},{"name":"Projected Spend Next 26 Weeks","dataType":"double"},{"name":"Projected Spend Next 26 Weeks USD","dataType":"double"},{"name":"Open Blanket","dataType":"string"},{"name":"Number of Open Blanket","dataType":"double"},{"name":"Total Blanket Remaining Amount","dataType":"double"},{"name":"Total Blanket Remaining Amount USD","dataType":"double"},{"name":"Total Blanket Remaining Quantity","dataType":"double"},{"name":"Blanket Remaining Days of Supply","dataType":"double"},{"name":"Supply Chain Status","dataType":"string"},{"name":"Attribute Lead Time","dataType":"double"},{"name":"Onhand Quantity Non Asset","dataType":"double"},{"name":"Onhand Quantity Asset","dataType":"double"},{"name":"IR PO Quantity","dataType":"double"},{"name":"IR PO Value","dataType":"double"},{"name":"IR PO Value USD","dataType":"double"},{"name":"On Order PO Quantity","dataType":"double"},{"name":"On Order PO Value","dataType":"double"},{"name":"On Order PO Value USD","dataType":"double"},{"name":"Sourcing Rule Vendor Site ID","dataType":"double"},{"name":"GR W0","dataType":"double"},{"name":"GR W1","dataType":"double"},{"name":"GR W2","dataType":"double"},{"name":"GR W3","dataType":"double"},{"name":"GR W4","dataType":"double"},{"name":"GR W5","dataType":"double"},{"name":"GR W6","dataType":"double"},{"name":"GR W7","dataType":"double"},{"name":"GR W8","dataType":"double"},{"name":"GR W9","dataType":"double"},{"name":"GR W10","dataType":"double"},{"name":"GR W11","dataType":"double"},{"name":"GR W12","dataType":"double"},{"name":"GR W13","dataType":"double"},{"name":"GR W14","dataType":"double"},{"name":"GR W15","dataType":"double"},{"name":"GR W16","dataType":"double"},{"name":"GR W17","dataType":"double"},{"name":"GR W18","dataType":"double"},{"name":"GR W19","dataType":"double"},{"name":"GR W20","dataType":"double"},{"name":"GR W21","dataType":"double"},{"name":"GR W22","dataType":"double"},{"name":"GR W23","dataType":"double"},{"name":"GR W24","dataType":"double"},{"name":"GR W25","dataType":"double"},{"name":"GR W26","dataType":"double"},{"name":"Total Usage 26 Weeks","dataType":"double"},{"name":"Sales Usage 13 Weeks","dataType":"double"},{"name":"Sales Usage 26 Weeks","dataType":"double"},{"name":"WO Usage 13 Weeks","dataType":"double"},{"name":"WO Usage 26 Weeks","dataType":"double"},{"name":"Usage 13 Weeks Value USD","dataType":"double"},{"name":"Average Daily Usage 26 Weeks","dataType":"double"},{"name":"Kanban Type","dataType":"string"},{"name":"Inventory Velocity LT Grouping","dataType":"string"},{"name":"LT_GROUPING_ID","dataType":"double"},{"name":"SEC Reporting","dataType":"string"},{"name":"Operations Reporting","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-13T02:02:15.0770369+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/4352cd6d-69ea-4397-bdc3-e36996a327f0/Inventory_Velocity.csv?snapshot=2022-06-13T02%3A02%3A15.0167678Z"}]}]}