{"name":"COHREP_GLOBAL1","description":"Global data with no security. Examples: Item type, buyers,  categories, etc","version":"1.0","culture":"en-US","modifiedTime":"2020-09-13T04:50:06.2377562+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":true,"queriesMetadata":{"Item_Type":{"queryId":"4b0befd3-b33c-40f0-b9f0-71ae82b5ef4b","queryName":"Item_Type","queryGroupId":"root","loadEnabled":true},"Sales_Commodity":{"queryId":"fd634039-5a34-49b8-93c9-03538bb84572","queryName":"Sales_Commodity","queryGroupId":"root","loadEnabled":true},"Sourcing_Commodity":{"queryId":"e47409c1-bc93-4952-aae0-b4fc2dfac0e6","queryName":"Sourcing_Commodity","queryGroupId":"root","loadEnabled":true},"Product_Category":{"queryId":"32509368-b376-4fb7-855b-c061e5c904ce","queryName":"Product_Category","queryGroupId":"root","loadEnabled":true},"GL_Account":{"queryId":"afb00876-c3fb-432b-a814-d31ff4092ead","queryName":"GL_Account","queryGroupId":"root","loadEnabled":true},"GL_Department":{"queryId":"6223da1b-cccc-4d39-8bc2-e95e587cc9b5","queryName":"GL_Department","queryGroupId":"root","loadEnabled":true},"GL_Project":{"queryId":"a0110de0-fea3-4985-8c1e-82d14c5c659c","queryName":"GL_Project","queryGroupId":"root","loadEnabled":true},"Country_Region":{"queryId":"f74d8c81-fb43-438b-8083-2079141671b0","queryName":"Country_Region","queryGroupId":"root","loadEnabled":true},"Replenishment_Method":{"queryId":"12ed2001-a242-49f4-b9ef-19147d417bcf","queryName":"Replenishment_Method","queryGroupId":"root","loadEnabled":true},"Supply_Chain_Status":{"queryId":"53f2188f-a90a-4cf2-8ddc-86f24e9dae57","queryName":"Supply_Chain_Status","queryGroupId":"root","loadEnabled":true},"ABC_Class":{"queryId":"194b188a-e65d-41eb-a18e-4563e0962c84","queryName":"ABC_Class","queryGroupId":"root","loadEnabled":true},"Fiscal_Calendar":{"queryId":"c44bd07a-f954-43ea-a639-a5719fc5d871","queryName":"Fiscal_Calendar","queryGroupId":"root","loadEnabled":true},"MPN":{"queryId":"6f86fe1f-46de-4bad-9fe0-2226d857e71a","queryName":"MPN","queryGroupId":"root","loadEnabled":true},"Order_Transaction_Type":{"queryId":"d46cc972-181e-4594-95f6-80d6663a50b5","queryName":"Order_Transaction_Type","queryGroupId":"root","loadEnabled":true},"TBU":{"queryId":"eaad3d1e-9227-45cc-93bd-a2c9d6dabfcd","queryName":"TBU","queryGroupId":"root","loadEnabled":true},"Product_Family":{"queryId":"ed439a8d-f959-4367-9d0e-7c292271bf31","queryName":"Product_Family","queryGroupId":"root","loadEnabled":true},"Product_Line":{"queryId":"e72da4b3-54ec-4b9a-ae7f-b05824e833b7","queryName":"Product_Line","queryGroupId":"root","loadEnabled":true},"Forecast_Field":{"queryId":"1e9e870a-0d5f-40d5-9da7-72e6c46e5e7c","queryName":"Forecast_Field","queryGroupId":"root","loadEnabled":true}},"document":"section Section1;\r\nshared Item_Type = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, Query=\"\nSELECT\n  sysdate EXTRACT_DATE,\n  FLV.LOOKUP_CODE ITEM_TYPE_CODE,\n  MEANING ITEM_TYPE_NAME,\n  ENABLED_FLAG\nFROM\n  APPS.FND_LOOKUP_VALUES_VL FLV\nWHERE\n  LOOKUP_TYPE = 'ITEM_TYPE'\n  AND enabled_flag = 'Y'\n  AND exists (select 1 from inv.mtl_system_items_b msi where msi.item_type = flv.lookup_code)\n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"ITEM_TYPE_CODE\", \"Item Type Code\"}, {\"ITEM_TYPE_NAME\", \"Item Type Name\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Sales_Commodity = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, Query=\"\nSELECT\n  sysdate EXTRACT_DATE,\n  category_id,\n  segment1 COMMODITY\nFROM\n  apps.mtl_categories_v MC\nWHERE\n  structure_name = 'Commodity'\n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"COMMODITY\", \"Sales Commodity\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Sourcing_Commodity = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, Query=\"\nSELECT\n  sysdate EXTRACT_DATE,\n  category_id,\n  segment1,\n  segment2 SUBCATEGORY,\n  segment3 UNSPSC_CODE,\n  MC.SEGMENT1 || '.' || MC.SEGMENT2 || '.' || MC.SEGMENT3 SOURCING_COMMODITY\nFROM\n  apps.mtl_categories_v MC\nWHERE\n  structure_name = 'Sourcing Commodity'\n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"SOURCING_COMMODITY\", \"Sourcing Commodity\"}, {\"SUBCATEGORY\", \"Sourcing Subcategory\"}, {\"UNSPSC_CODE\", \"UNSPSC Code\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Product_Category = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, Query=\"  \nSELECT\n   SYSDATE EXTRACT_DATE,\n   MC.CATEGORY_ID,\n   MC.SEGMENT1 TBU,\n   MC.SEGMENT2 PRODUCT_FAMILY,\n   MC.SEGMENT3 PRODUCT_LINE,\n   MC.SEGMENT4 FORECAST,\n   MC.SEGMENT1 || '.' || MC.SEGMENT2 || '.' || MC.SEGMENT3 || '.' || MC.SEGMENT4 PRODUCT_CATEGORY \nFROM\n   APPS.MTL_CATEGORIES_V MC \nWHERE 1=1\nAND Structure_name = 'Product Family/Line'\n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"PRODUCT_FAMILY\", \"Product Family\"}, {\"FORECAST\", \"Forecast Field\"}, {\"PRODUCT_LINE\", \"Product Line\"}, {\"PRODUCT_CATEGORY\", \"Product Category\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared GL_Account = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, \n  Query=\"\nselect\n   sysdate  EXTRACT_DATE,\n   VL.FLEX_VALUE ACCOUNT,\n   TL.DESCRIPTION ACCOUNT_DESCRIPTION \nfrom\n   APPS.FND_FLEX_VALUES_TL TL,\n   APPS.FND_FLEX_VALUES VL,\n   APPS.FND_FLEX_VALUE_SETS FST \nwhere\n   1 = 1 \n   AND TL.FLEX_VALUE_ID( + ) = VL.FLEX_VALUE_ID \n   AND TL.LANGUAGE ( + ) = 'US' \n   AND VL.ENABLED_FLAG = 'Y' \n   AND VL.FLEX_VALUE_SET_ID = FST.FLEX_VALUE_SET_ID \n   AND FST.FLEX_VALUE_SET_NAME = 'COHR_Acct'\n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"ACCOUNT\", \"GL Account Code\"}, {\"ACCOUNT_DESCRIPTION\", \"GL Account\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared GL_Department = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, \n  Query=\"\nselect\n   sysdate  EXTRACT_DATE,\n   VL.FLEX_VALUE DEPARTMENT_CODE,\n   TL.DESCRIPTION\nfrom\n   APPS.FND_FLEX_VALUES_TL TL,\n   APPS.FND_FLEX_VALUES VL,\n   APPS.FND_FLEX_VALUE_SETS FST \nwhere\n   1 = 1 \n   AND TL.FLEX_VALUE_ID( + ) = VL.FLEX_VALUE_ID \n   AND TL.LANGUAGE ( + ) = 'US' \n   AND VL.ENABLED_FLAG = 'Y' \n   AND VL.FLEX_VALUE_SET_ID = FST.FLEX_VALUE_SET_ID \n   AND FST.FLEX_VALUE_SET_NAME = 'COHR_Dept'\n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"DEPARTMENT_CODE\", \"GL Department Code\"}, {\"DESCRIPTION\", \"GL Department\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared GL_Project = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, \n  Query=\"\nselect\n\tsysdate EXTRACT_DATE,\n   VL.FLEX_VALUE PROJECT_CODE,\n   TL.DESCRIPTION\nfrom\n   APPS.FND_FLEX_VALUES_TL TL,\n   APPS.FND_FLEX_VALUES VL,\n   APPS.FND_FLEX_VALUE_SETS FST \nwhere\n   1 = 1 \n   AND TL.FLEX_VALUE_ID( + ) = VL.FLEX_VALUE_ID \n   AND TL.LANGUAGE ( + ) = 'US' \n   AND VL.ENABLED_FLAG = 'Y' \n   AND VL.FLEX_VALUE_SET_ID = FST.FLEX_VALUE_SET_ID \n   AND FST.FLEX_VALUE_SET_NAME = 'COHR_Proj'\n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"PROJECT_CODE\", \"GL Project Code\"}, {\"DESCRIPTION\", \"GL Project\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Country_Region = let\r\n  Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"hVrNkuI4En4VR59qIrpjJ/awewZjDIVt3LaBLmbnIEANmjJWjbCrhnqjue8bzItt5idXNagY7eXr6FJKTuV/pvjll0+D7/uDaNSpFc2nz58GY0DMeFIi+E/388///FeQi636rraffv1MG2rR7ILpif85Md03hmRAGHVGP8meakOnCiwBhu76Xhqsj9YA3j8wYhOUrWjlyRIdiWYrmqAUR42zSkDqY6/ZaWNAPGLIRs6Hm72usTxniIHf+TNvy52qLcEUwIyVumsP/0hEq5qgZ6qnboXZtvxfIv3KUA28zLVq34mAJTgUZtPtsBHirmLfh8xe0t4G5AXAT36UvfQhqyJ1hGC6DVZXDMOV76ju1BpR28MWgNJ3Qya3xBWIK+fLr9JshPrNWtsaEHnOG4qDOAq2syF/djgpPbwSsRGqAR2guGFUQ9Hsa7GTpwOTsHUM45GXA2J4p8ECG/GwGPpYkLUwHYgfGJLi+v60vlfdkZciQPJhXb1KXllj+9r7rcZe9h4nZdeWPJTmaO1rmAJYeZk27eH6kENnXX9YATKfKHStnqHc4RyQ+LjTJzJBmPpEmle518/WfofsIcPpxLm4bk8vwhKsAAPnPrp7lm0feJhgCah8LBjxqmroDOBz5aFRrTodgqUye1r6Ed+WMcCJX2/k02anKEDNt5Kwkob+rM2ZaKdzQOUTp+kaqYIRG8xJ1AJWkYFTrxa6ei+sjw1jgGtjnXkkUQdjcdK8Pga44uzo6zsFVcARptfroThu9A5fmU0AvqhL1NJozXYUpoDCPa4RMMZwAMhuGmMonmSwlGbHHhCygsN86R50PopL/czYz8KH1KPbkGInxbDAHtMEhXzqNjWxThvHYGfsfOSgarDABh5OfGZOpDDaMAOpT3ET3eyDGcHnoBwUwdvOyQzgy7mp2Ap9vStl+0oHoU8pB0N5naLnD6cJvwEK3y691afgbiYpEjX7ny4kHYaAmXdzrY8bWE04B3hlp4/aILLOYDTz9Ea8DklgOrhjX34Vz5Sb5U9MG2ND7OiNaT8T86o5HcRJgHIEypFLqR8vrzYDkf9qVCMFhc31YQGY+i73139bGexw0r+nz1oZWNQU4Bq10bQfxlAAltceHZ6fbFIJrbHnzvKr3B6urHoNiK7JRrI5CvNIfxzxRUfZzFn/TW3oMhwTRveA6Q19jPRRNVYKoxTgC6tv1FdON5oDfC4bbTtKuoYZDAELH/H+/NQyVQx4uMF1VFMRWT/3Z5Ys3zJZ+s78vRMUyhWFjbhTjeT7xlzhxdnXa+VFFPMN1iME4sKJpNGp1bYYi6CQ0imJovag9JMlwFI1uT5gLOrHy6I7uEvpKhQGTmzfY9biOJl57jIWRssLax+z/MfF/JqPsWr6KDGeAjJn3YhmK7ETMHCXZUNWSMKyWTzmmBovxj6+7JZc1+dGniCBnOnzh7HHEftdOFSaH1lXSb5bha2V74BYbJCp4gFgeC3tWPQBLE4B7rLUVCBgPQI4Uoyp7BINVwCjCLBw1g+9eCYAJyvHakOJipoKXpwCnMIjNlJCC8j6cRF+XH5TY5yAIvlA0adilL1xMfJoKCYvlLXunvDFHIfmfvpWHgX6p7gC+Lw87kiBJ8nSimPAg8Psu+tlEIZT49rlL0NF9VPHBCuQuirrzr3MH2CSDx6OJkIhAE4qgC/AT6QwO9S36XanG1FfdsWoliapr7GYkNkHpZTB3VK0CJGhas82aLFjLwcAJ1pQEbHrDDoiFBuTzKe/SddQrcjynSwAjk9Pt7I3lmkJcIwF5S0vZADfdYhUv3nxdATwFUNTiiafIbCj2r4nh0B/550FwL/9nfEIxC7jp1rSYUGK3maaAtzLn4yQ3B5ME9zdKaOnrahRyVcAJ9zdU1tqs+A9H34/8Nn5vXgCH/c5wHexe2msQ9xHAMch7rXZ2aPmgFsd7ky8isdDP9GZcSkws53233xyJpsz6vwI4PjYTBm1EXCK2RTgqx5nmlJhcIfSno14xjfOC19h1W+B7LCFz5/NvV/pXshPmWwFqG5J4Wz259c3KcQAnxQSoYN8xF/FLCux86G/JW5tI4waIlk6xpHIjWiQYzD3StDVuQwm8qTbA3doSQlwRlGJ2vQjMgwRkmHxYR1qSx6weqvqSRQVhq1sTq3EpCCZApy6MFHtoeundUkFcJJW0v0hqR3szJ5XF4Bv1yTUosgd1zmfHWdOZ4CRS74Te3HaItOlrJ105BTzVOSIFza7dAWYflw+23CTPgB8cymi3qlnVAjpEl9b+qlbHMzSSJPK5d1Qd1HXF+E+nQAS75mGwoL6veNUmn7F6V89MSMVHZU1vVrQTqfFLTu3dArtAWY8qR3QXUrqrNuWP/uA+wAv1+Ufast2mLJO0+ibjyu1NTbMfw7GcicN8bHr2bH6HnMgHHtntKmud/oZ9xoBHPdJKZtahkLA/MPyXtuJJEJ6mnl7Z92QB8i9wYER6KMPB7YnqiIFh5S0BBQ+IVDXurUMDgC3onCqX7mS7PXNkSedrx3BU11ytB6QAnwxL6NEaQvTbABIrw/LyA64BsoKwMJ3lHwSnPeyHOCz2kxykf1m5lkCcHz5gibgCTe16HgYQNDLfAO6TL4Eoaht4OCjQ4CfoZdgLUWf/LM1wLuBPmbEvsP5U0DoY0ntJWsENpJFTszFqmU1Bjj1O+W977p+/DFwycYAX/5DruRGJuWpXiMuw0oOc839u18E1wvZHOAUMbl4fHvbyZmJfOBjJSe5sg3lHHHzZOUnlScOaM7cMy8B0Q2PyOlyRzR5A0DmUUMunjoRsLLfW4CcJZ57fT23mgYfnBPywlfr5wdVq6cnOp5lnU8APlPKVbsVykCYzHwe+io5amutDcDB8rlToeak9m4PP8wr8OqkmZyao1bzxEljGeBrSL4K2zh+HQBuJYtCdo1CYVJEAF+YKPSxTz8YFRRzpyooutOJ1d/ngf7cBaB0SF9IFDhpBXDcphSqab8MKUMe/vqzlkdW4DAB+MpqbAsmspZo78oJILtxdjBTbXtCs5bJZ4WRYwbwDa/s1qTb2tIoBPzfDV9spg/u+kHFE/2X69p0jFzhG4jYD+aK/EnazpLzRw3B5pAE8OPg3G5cqmYr6V/eadv83raXIcAXit+eWFclwJe+S2FjVcN2CcoydcJOScV0pY/2EjmRbhVGCJh9lVXuqqjbqYBtFYIuIWL72OjYb8mZHD5TInq4zUopjT2jwDth4QxPSnneHmSfn0qkgYfQOYGFL4JEUpXD65hfJ5FLRG31k8ZEt8RDbOyL0WVN1c6jvRvmdEtn8soE/YNtCQ9fOq1qyXN1ffnsUeIVEu3F336W/NeWSWgtypvjddhD/zJCy3iHX7vvIZaoH31Bp5Sx7AQuIGvYvSiy8x+8xRB+7Huq7fd2tpktQVo6M/ryyT7mRggmpTP0Lo0KEtE8wjVnAN/T+/unMC4Z3WrISiqkKUNBqSj/Fr4isHwW9eZtAnQPlzjLKw3dA5yn9/KF3yRtYijxurtyqsLyheIpWI2wHLkHqPbVlluf+MUJ4NKcuZKAR/3oxu7w159g9ABftVkJ9cIDmote7v3pqVoBfLmvEr+p98Kjugf4Co9KNK8CzeOiUdxRXPeQ1RrgZI3qIN4kiZF5NfEZQKWO2nyhphudUJUAfC1jpR+lLYeqGcBXGlTUk0A2c4BXNmRlaies4VR6I/YcR6sKMPdYXEW52za8eKWvFreMuOrMI+ZHVQEaJzDzMv825E01KW7mi/a8w2bOUCh+Gvxh4VUI8GXEqiM3gQyXYMfXdS/2fZGwiAGOuheP/OMOVt6CVxYz52q95UAg0VEZiIROQOwubhWk/Y4ZRfOd5td3vPLHw9sHvze57xckJkoAGrIPSXlRUv5utAnmXVuf6SMXolukgKlPHKbra1lMrBfeWnbxupHvDrdYA3y5YSmaTrSsmOUC4PuhwpKy7ivVISK4w09A0Ke8uyhm1RHAV9EvlWyDDD9yQHZbZj6ru/4ZBoUFFvRyCvBF5ZWoa2XNddy13VU3teKstkp8T0MrDg+Gf3B2EPgRWYSfqZTOi9yDPCJCP0SAW3l1/faMtE4BzpvEWh03YvPC1rxeAS5LjF//Bw==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Country Name\" = _t, #\"Country 2 Digits\" = _t, #\"Country 3 Digits\" = _t, Region = _t]),\r\n  #\"Changed Type\" = Table.TransformColumnTypes(Source, {{\"Country Name\", type text}, {\"Country 2 Digits\", type text}, {\"Country 3 Digits\", type text}, {\"Region\", type text}})\r\nin\r\n  #\"Changed Type\";\r\nshared Replenishment_Method = let\r\n  Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45W8g0KUIrViVbyTsxLSswDM30z8xR8EyvA7DBfTzDtl1+iEJCTmJeXmgLhOyrFxgIA\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Replenishment Method\" = _t])\r\nin\r\n  Source;\r\nshared Supply_Chain_Status = let\r\n  Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WikwtVtKBkr5BAQqOySWZZalKsTrRSr6JlUmpQGG/fCAREuGHLAfRAJbx9AtT8MxLRMiBRSFScOFYAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Is Supply Exist\" = _t, #\"Is Demand Exist\" = _t, #\"Supply Chain Status\" = _t])\r\nin\r\n  Source;\r\nshared ABC_Class = let\r\n  Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WMlTSUXJUitWJVjICspzALGMgyxnMMgGyXCMCwGwzINsvv0TBsaAgJzM5MSknFSxsCtKWk5iXrRQbCwA=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Sort Order\" = _t, #\"ABC-EXP Class\" = _t]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(Source, {{\"Sort Order\", Int64.Type}}),\r\n  #\"Sorted rows\" = Table.Sort(#\"Changed column type\", {{\"Sort Order\", Order.Ascending}})\r\nin\r\n  #\"Sorted rows\";\r\nshared Fiscal_Calendar = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, \n  Query=\"\n SELECT\n    sysdate                                                                                       extract_date,\n    al1.period_date                                                                               calendar_date,\n    al1.year_start_date                                                                           fc_year_start_date,\n    al1.period_year                                                                               fc_year,\n    al1.quarter_start_date                                                                        fc_quarter_start_date,\n    'Q' || al1.quarter_num                                                                        fc_quarter,\n    CASE\n        WHEN al1.quarter_num <= 2 THEN\n            'H1'\n        ELSE\n            'H2'\n    END fc_half,\n    al1.period_num                                                                                fc_period_number,\n    substr(al1.period_name, 1, 3)                                                                 fc_period_month,\n    al1.period_name                                                                               fc_period_name,\n    ( al1.period_year - 1 ) * 12 + al1.period_num                                                 fc_period_id,\n    ( al1.period_year - 1 ) * 4 + al1.quarter_num                                                 fc_quarter_id,\n    ceil((al1.period_date - TO_DATE('02-OCT-1999', 'DD-MON-RRRR')) / 7)                           fc_week_id,\n    al1.period_year - (\n        SELECT\n            ( cd.period_year )\n        FROM\n            (\n                SELECT\n                    gdpm.period_set_name,\n                    gp.period_name,\n                    gdpm.accounting_date period_date,\n                    gp.period_year,\n                    gp.period_num,\n                    gp.quarter_num,\n                    gp.year_start_date,\n                    gp.quarter_start_date\n                FROM\n                    gl.gl_date_period_map    gdpm,\n                    gl.gl_periods            gp\n                WHERE\n                        gdpm.period_set_name = 'COHR Calendar'\n                    AND gp.period_name = gdpm.period_name\n                    AND gdpm.period_set_name = gp.period_set_name\n                    AND gdpm.accounting_date = trunc(sysdate)\n            ) cd\n    ) fc_year_offset,\n    ( ( al1.period_year - 1 ) * 4 + al1.quarter_num ) - (\n        SELECT\n            ( cd.period_year - 1 ) * 4 + cd.quarter_num\n        FROM\n            (\n                SELECT\n                    gdpm.period_set_name,\n                    gp.period_name,\n                    gdpm.accounting_date period_date,\n                    gp.period_year,\n                    gp.period_num,\n                    gp.quarter_num,\n                    gp.year_start_date,\n                    gp.quarter_start_date\n                FROM\n                    gl.gl_date_period_map    gdpm,\n                    gl.gl_periods            gp\n                WHERE\n                        gdpm.period_set_name = 'COHR Calendar'\n                    AND gp.period_name = gdpm.period_name\n                    AND gdpm.period_set_name = gp.period_set_name\n                    AND gdpm.accounting_date = trunc(sysdate)\n            ) cd\n    ) fc_quarter_offset,\n    ( ( al1.period_year - 1 ) * 12 + al1.period_num ) - (\n        SELECT\n            ( cd.period_year - 1 ) * 12 + cd.period_num\n        FROM\n            (\n                SELECT\n                    gdpm.period_set_name,\n                    gp.period_name,\n                    gdpm.accounting_date period_date,\n                    gp.period_year,\n                    gp.period_num,\n                    gp.quarter_num,\n                    gp.year_start_date,\n                    gp.quarter_start_date\n                FROM\n                    gl.gl_date_period_map    gdpm,\n                    gl.gl_periods            gp\n                WHERE\n                        gdpm.period_set_name = 'COHR Calendar'\n                    AND gp.period_name = gdpm.period_name\n                    AND gdpm.period_set_name = gp.period_set_name\n                    AND gdpm.accounting_date = trunc(sysdate)\n            ) cd\n    ) fc_period_offset,\n    ( al1.period_date - al1.year_start_date ) + 1                                                 doy_number,\n    ( al1.period_date - trunc(sysdate) )                                                          fc_day_offset,\n    CASE\n        WHEN ceil((al1.period_date - al1.year_start_date + 1) / 7) < 10 THEN\n            'W0'\n            || ceil((al1.period_date - al1.year_start_date + 1) / 7)\n        ELSE\n            'W'\n            || ceil((al1.period_date - al1.year_start_date + 1) / 7)\n    END fc_week,\n    CASE\n        WHEN ceil((al1.period_date - al1.quarter_start_date + 1) / 7) < 10 THEN\n            'QW0'\n            || ceil((al1.period_date - al1.quarter_start_date + 1) / 7)\n        ELSE\n            'QW'\n            || ceil((al1.period_date - al1.quarter_start_date - 1) / 7)\n    END fc_quarter_week,\n    ceil((al1.period_date - TO_DATE('02-OCT-1999', 'DD-MON-RRRR')) / 7) - ceil(((trunc(sysdate)) - TO_DATE('02-OCT-1999', 'DD-MON-RRRR')) /\n    7) fc_week_offset,\n    ( al1.period_year * 100 + ceil((al1.period_date - al1.year_start_date + 1) / 7) )               fc_week_series,\n    ceil((al1.period_date - al1.year_start_date + 1) / 7)  fc_week_number,\n    to_char(al1.period_date, 'DAY')                                                                 day_name,\n    to_char(al1.period_date, 'D')                                                                  dow_number\nFROM\n    (\n        SELECT\n            gdpm.period_set_name,\n            gp.period_name,\n            gdpm.accounting_date period_date,\n            gp.period_year,\n            gp.period_num,\n            gp.quarter_num,\n            gp.year_start_date,\n            gp.quarter_start_date\n        FROM\n            gl.gl_date_period_map    gdpm,\n            gl.gl_periods            gp\n        WHERE\n                gdpm.period_set_name = 'COHR Calendar'\n            AND gp.period_name = gdpm.period_name\n            AND gdpm.period_set_name = gp.period_set_name\n    ) al1\n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"EXTRACT_DATE\", \"Extract Date\"}, {\"FC_YEAR_START_DATE\", \"FC Year Start Date\"}, {\"FC_YEAR\", \"FC Year\"}, {\"FC_QUARTER_START_DATE\", \"FC Quarter Start Date\"}, {\"FC_QUARTER\", \"FC Quarter\"}, {\"FC_PERIOD_NUMBER\", \"FC Period Number\"}, {\"FC_PERIOD_MONTH\", \"FC Period Month\"}, {\"FC_HALF\", \"FC Half\"}, {\"FC_PERIOD_NAME\", \"FC Period Name\"}, {\"FC_WEEK_SERIES\", \"FC Week Series\"}, {\"FC_WEEK_NUMBER\", \"FC Week Number\"}, {\"FC_QUARTER_WEEK\", \"FC Quarter Week\"}, {\"FC_WEEK\", \"FC Week\"}, {\"FC_DAY_OFFSET\", \"FC Day Offset\"}, {\"FC_WEEK_OFFSET\", \"FC Week Offset\"}, {\"FC_PERIOD_OFFSET\", \"FC Period Offset\"}, {\"FC_QUARTER_OFFSET\", \"FC Quarter Offset\"}, {\"FC_YEAR_OFFSET\", \"FC Year Offset\"}, {\"CALENDAR_DATE\", \"Calendar Date\"}, {\"FC_WEEK_ID\", \"FC Week ID\"}, {\"FC_PERIOD_ID\", \"FC Period ID\"}, {\"FC_QUARTER_ID\", \"FC Quarter ID\"}, {\"DOY_NUMBER\", \"Day of Year Number\"}, {\"DAY_NAME\", \"Day Name\"}, {\"DOW_NUMBER\", \"Day of Week Number\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared MPN = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, \n  Query=\"\n  SELECT\n  sysdate EXTRACT_DATE,\n  MPN.manufacturer_name,\n  MPN.mfg_part_num,\n  MPN.inventory_item_id,\n  (SELECT\n    MSI.segment1\n  FROM inv.mtl_system_items_b MSI\n  WHERE MSI.inventory_item_id = MPN.inventory_item_id\n  AND rownum = 1)\n  ITEM_NUMBER\nFROM\n  apps.MTL_MFG_PART_NUMBERS_ALL_V MPN\n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"EXTRACT_DATE\", \"Extract Date\"}, {\"MANUFACTURER_NAME\", \"Manufacturer Name\"}, {\"MFG_PART_NUM\", \"Manufacturer Part Number\"}, {\"ITEM_NUMBER\", \"Item Number\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Order_Transaction_Type = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, \n  Query=\"\n  SELECT\n  SYSDATE EXTRACT_DATE,\n   OTTL.NAME,\n   OTTL.DESCRIPTION,\n   OTTA.SCHEDULING_LEVEL_CODE,\n   OTTA.TRANSACTION_TYPE_ID,\n   OTTA.TRANSACTION_TYPE_CODE,\n   OTTA.ORDER_CATEGORY_CODE,\n   OTTA.START_DATE_ACTIVE,\n   OTTA.END_DATE_ACTIVE,\n   OTTA.CONTEXT,\n   OTTA.ATTRIBUTE5 TP_CLASSIFICATION,\n   OTTA.ATTRIBUTE6 ENTITY,\n   OTTA.ATTRIBUTE15 TAX_APPLICABILITY,\n   OTTA.ATTRIBUTE13 ACCOUNTING_TYPE,\n   OTTA.ATTRIBUTE4 REVENUE_FLAG\nFROM\n   APPS.OE_TRANSACTION_TYPES_ALL OTTA,\n   APPS.OE_TRANSACTION_TYPES_TL OTTL \nWHERE\n   OTTA.TRANSACTION_TYPE_ID = OTTL.TRANSACTION_TYPE_ID \n   AND OTTL.LANGUAGE = 'US'\n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"NAME\", \"Name\"}, {\"ORDER_CATEGORY_CODE\", \"Order Category Code\"}, {\"TRANSACTION_TYPE_CODE\", \"Transaction Type Code\"}, {\"SCHEDULING_LEVEL_CODE\", \"Scheduling Level Code\"}, {\"CONTEXT\", \"Context\"}, {\"TP_CLASSIFICATION\", \"TP Classification\"}, {\"ENTITY\", \"Entity\"}, {\"TAX_APPLICABILITY\", \"Tax Applicability\"}, {\"ACCOUNTING_TYPE\", \"Accounting Type\"}, {\"START_DATE_ACTIVE\", \"Start Date\"}, {\"END_DATE_ACTIVE\", \"End Date\"}, {\"DESCRIPTION\", \"Description\"}, {\"EXTRACT_DATE\", \"Extract Date\"}, {\"REVENUE_FLAG\", \"Revenue Flag\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared TBU = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, Query=\"  \nSELECT\n   sysdate EXTRACT_DATE,\n   FVS.FLEX_VALUE_SET_NAME,\n   FVS.DESCRIPTION VALUE_SET_DESCRIPTION,\n   FLV.FLEX_VALUE_SET_ID,\n   FLV.FLEX_VALUE_ID,\n   FLV.FLEX_VALUE,\n   FLV.FLEX_VALUE_MEANING,\n   FLV.DESCRIPTION VALUE_DESCRIPTION,\n   FLV.END_DATE_ACTIVE,\n   FLV.ENABLED_FLAG\nFROM\n   APPS.FND_FLEX_VALUES_VL FLV,\n   APPS.FND_FLEX_VALUE_SETS FVS \nWHERE\n   FVS.FLEX_VALUE_SET_ID = FLV.FLEX_VALUE_SET_ID \n   AND UPPER(FVS.FLEX_VALUE_SET_NAME) LIKE '%TBU%'\n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"EXTRACT_DATE\", \"Extract Date\"}, {\"FLEX_VALUE_SET_NAME\", \"Value Set Name\"}, {\"VALUE_SET_DESCRIPTION\", \"Value Set Description\"}, {\"FLEX_VALUE\", \"Flex Value\"}, {\"FLEX_VALUE_MEANING\", \"Flex Value Meaning\"}, {\"VALUE_DESCRIPTION\", \"Value Description\"}, {\"END_DATE_ACTIVE\", \"End Date Active\"}, {\"ENABLED_FLAG\", \"Enabled Flag\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Product_Family = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, Query=\"  \nSELECT\n   sysdate EXTRACT_DATE,\n   FVS.FLEX_VALUE_SET_NAME,\n   FVS.DESCRIPTION VALUE_SET_DESCRIPTION,\n   FLV.FLEX_VALUE_SET_ID,\n   FLV.FLEX_VALUE_ID,\n   FLV.FLEX_VALUE,\n   FLV.FLEX_VALUE_MEANING,\n   FLV.DESCRIPTION VALUE_DESCRIPTION,\n   FLV.END_DATE_ACTIVE,\n   FLV.ENABLED_FLAG\nFROM\n   APPS.FND_FLEX_VALUES_VL FLV,\n   APPS.FND_FLEX_VALUE_SETS FVS \nWHERE\n   FVS.FLEX_VALUE_SET_ID = FLV.FLEX_VALUE_SET_ID \n   AND UPPER(FVS.FLEX_VALUE_SET_NAME) LIKE 'COHR%PRODUCT%FAMILY'\n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"EXTRACT_DATE\", \"Extract Date\"}, {\"FLEX_VALUE_SET_NAME\", \"Value Set Name\"}, {\"VALUE_SET_DESCRIPTION\", \"Value Set Description\"}, {\"FLEX_VALUE\", \"Flex Value\"}, {\"FLEX_VALUE_MEANING\", \"Flex Value Meaning\"}, {\"VALUE_DESCRIPTION\", \"Value Description\"}, {\"END_DATE_ACTIVE\", \"End Date Active\"}, {\"ENABLED_FLAG\", \"Enabled Flag\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Product_Line = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, Query=\"  \nSELECT\n   sysdate EXTRACT_DATE,\n   FVS.FLEX_VALUE_SET_NAME,\n   FVS.DESCRIPTION VALUE_SET_DESCRIPTION,\n   FLV.FLEX_VALUE_SET_ID,\n   FLV.FLEX_VALUE_ID,\n   FLV.FLEX_VALUE,\n   FLV.FLEX_VALUE_MEANING,\n   FLV.DESCRIPTION VALUE_DESCRIPTION,\n   FLV.END_DATE_ACTIVE,\n   FLV.ENABLED_FLAG\nFROM\n   APPS.FND_FLEX_VALUES_VL FLV,\n   APPS.FND_FLEX_VALUE_SETS FVS \nWHERE\n   FVS.FLEX_VALUE_SET_ID = FLV.FLEX_VALUE_SET_ID \n   AND UPPER(FVS.FLEX_VALUE_SET_NAME) LIKE 'COHR%PRODUCT%LINE'\n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"EXTRACT_DATE\", \"Extract Date\"}, {\"FLEX_VALUE_SET_NAME\", \"Value Set Name\"}, {\"VALUE_SET_DESCRIPTION\", \"Value Set Description\"}, {\"FLEX_VALUE\", \"Flex Value\"}, {\"FLEX_VALUE_MEANING\", \"Flex Value Meaning\"}, {\"VALUE_DESCRIPTION\", \"Value Description\"}, {\"END_DATE_ACTIVE\", \"End Date Active\"}, {\"ENABLED_FLAG\", \"Enabled Flag\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Forecast_Field = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, Query=\"  \nSELECT\n   sysdate EXTRACT_DATE,\n   FVS.FLEX_VALUE_SET_NAME,\n   FVS.DESCRIPTION VALUE_SET_DESCRIPTION,\n   FLV.FLEX_VALUE_SET_ID,\n   FLV.FLEX_VALUE_ID,\n   FLV.FLEX_VALUE,\n   FLV.FLEX_VALUE_MEANING,\n   FLV.DESCRIPTION VALUE_DESCRIPTION,\n   FLV.END_DATE_ACTIVE,\n   FLV.ENABLED_FLAG\nFROM\n   APPS.FND_FLEX_VALUES_VL FLV,\n   APPS.FND_FLEX_VALUE_SETS FVS \nWHERE\n   FVS.FLEX_VALUE_SET_ID = FLV.FLEX_VALUE_SET_ID \n   AND UPPER(FVS.FLEX_VALUE_SET_NAME) LIKE 'COHR%FORECAST%FIELD'\n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"EXTRACT_DATE\", \"Extract Date\"}, {\"FLEX_VALUE_SET_NAME\", \"Value Set Name\"}, {\"VALUE_SET_DESCRIPTION\", \"Value Set Description\"}, {\"FLEX_VALUE\", \"Flex Value\"}, {\"FLEX_VALUE_MEANING\", \"Flex Value Meaning\"}, {\"VALUE_DESCRIPTION\", \"Value Description\"}, {\"END_DATE_ACTIVE\", \"End Date Active\"}, {\"ENABLED_FLAG\", \"Enabled Flag\"}})\r\nin\r\n  #\"Renamed columns\";\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"Item_Type","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Item_Type.csv"},"attributes":[{"name":"EXTRACT_DATE","dataType":"dateTime"},{"name":"Item Type Code","dataType":"string"},{"name":"Item Type Name","dataType":"string"},{"name":"ENABLED_FLAG","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-13T07:01:47.4344716+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/bf2bc9ad-494e-4117-9977-ce0471137f3e/Item_Type.csv?snapshot=2022-06-13T07%3A01%3A47.4158780Z"}]},{"$type":"LocalEntity","name":"Sales_Commodity","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Sales_Commodity.csv"},"attributes":[{"name":"EXTRACT_DATE","dataType":"dateTime"},{"name":"CATEGORY_ID","dataType":"double"},{"name":"Sales Commodity","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-13T07:01:39.5181544+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/bf2bc9ad-494e-4117-9977-ce0471137f3e/Sales_Commodity.csv?snapshot=2022-06-13T07%3A01%3A39.4844709Z"}]},{"$type":"LocalEntity","name":"Sourcing_Commodity","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Sourcing_Commodity.csv"},"attributes":[{"name":"EXTRACT_DATE","dataType":"dateTime"},{"name":"CATEGORY_ID","dataType":"double"},{"name":"SEGMENT1","dataType":"string"},{"name":"Sourcing Subcategory","dataType":"string"},{"name":"UNSPSC Code","dataType":"string"},{"name":"Sourcing Commodity","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-13T07:01:49.8987388+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/bf2bc9ad-494e-4117-9977-ce0471137f3e/Sourcing_Commodity.csv?snapshot=2022-06-13T07%3A01%3A49.8774533Z"}]},{"$type":"LocalEntity","name":"Product_Category","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Product_Category.csv"},"attributes":[{"name":"EXTRACT_DATE","dataType":"dateTime"},{"name":"CATEGORY_ID","dataType":"double"},{"name":"TBU","dataType":"string"},{"name":"Product Family","dataType":"string"},{"name":"Product Line","dataType":"string"},{"name":"Forecast Field","dataType":"string"},{"name":"Product Category","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-13T07:01:39.9556319+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/bf2bc9ad-494e-4117-9977-ce0471137f3e/Product_Category.csv?snapshot=2022-06-13T07%3A01%3A39.9262143Z"}]},{"$type":"LocalEntity","name":"GL_Account","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"GL_Account.csv"},"attributes":[{"name":"EXTRACT_DATE","dataType":"dateTime"},{"name":"GL Account Code","dataType":"string"},{"name":"GL Account","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-13T07:01:31.5423237+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/bf2bc9ad-494e-4117-9977-ce0471137f3e/GL_Account.csv?snapshot=2022-06-13T07%3A01%3A31.4441264Z"}]},{"$type":"LocalEntity","name":"GL_Department","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"GL_Department.csv"},"attributes":[{"name":"EXTRACT_DATE","dataType":"dateTime"},{"name":"GL Department Code","dataType":"string"},{"name":"GL Department","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-13T07:01:51.586715+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/bf2bc9ad-494e-4117-9977-ce0471137f3e/GL_Department.csv?snapshot=2022-06-13T07%3A01%3A51.5684736Z"}]},{"$type":"LocalEntity","name":"GL_Project","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"GL_Project.csv"},"attributes":[{"name":"EXTRACT_DATE","dataType":"dateTime"},{"name":"GL Project Code","dataType":"string"},{"name":"GL Project","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-13T07:01:47.8406724+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/bf2bc9ad-494e-4117-9977-ce0471137f3e/GL_Project.csv?snapshot=2022-06-13T07%3A01%3A47.8156461Z"}]},{"$type":"LocalEntity","name":"Country_Region","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Country_Region.csv"},"attributes":[{"name":"Country Name","dataType":"string"},{"name":"Country 2 Digits","dataType":"string"},{"name":"Country 3 Digits","dataType":"string"},{"name":"Region","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-13T07:01:11.702814+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/bf2bc9ad-494e-4117-9977-ce0471137f3e/Country_Region.csv?snapshot=2022-06-13T07%3A01%3A11.6695778Z"}]},{"$type":"LocalEntity","name":"Replenishment_Method","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Replenishment_Method.csv"},"attributes":[{"name":"Replenishment Method","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-13T07:01:14.3819869+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/bf2bc9ad-494e-4117-9977-ce0471137f3e/Replenishment_Method.csv?snapshot=2022-06-13T07%3A01%3A14.3440286Z"}]},{"$type":"LocalEntity","name":"Supply_Chain_Status","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Supply_Chain_Status.csv"},"attributes":[{"name":"Is Supply Exist","dataType":"string"},{"name":"Is Demand Exist","dataType":"string"},{"name":"Supply Chain Status","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-13T07:01:11.2653281+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/bf2bc9ad-494e-4117-9977-ce0471137f3e/Supply_Chain_Status.csv?snapshot=2022-06-13T07%3A01%3A11.2248345Z"}]},{"$type":"LocalEntity","name":"ABC_Class","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"ABC_Class.csv"},"attributes":[{"name":"Sort Order","dataType":"int64"},{"name":"ABC-EXP Class","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-13T07:01:14.9610664+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/bf2bc9ad-494e-4117-9977-ce0471137f3e/ABC_Class.csv?snapshot=2022-06-13T07%3A01%3A14.9017065Z"}]},{"$type":"LocalEntity","name":"Fiscal_Calendar","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Fiscal_Calendar.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Calendar Date","dataType":"dateTime"},{"name":"FC Year Start Date","dataType":"dateTime"},{"name":"FC Year","dataType":"int64"},{"name":"FC Quarter Start Date","dataType":"dateTime"},{"name":"FC Quarter","dataType":"string"},{"name":"FC Half","dataType":"string"},{"name":"FC Period Number","dataType":"int64"},{"name":"FC Period Month","dataType":"string"},{"name":"FC Period Name","dataType":"string"},{"name":"FC Period ID","dataType":"double"},{"name":"FC Quarter ID","dataType":"double"},{"name":"FC Week ID","dataType":"double"},{"name":"FC Year Offset","dataType":"double"},{"name":"FC Quarter Offset","dataType":"double"},{"name":"FC Period Offset","dataType":"double"},{"name":"Day of Year Number","dataType":"double"},{"name":"FC Day Offset","dataType":"double"},{"name":"FC Week","dataType":"string"},{"name":"FC Quarter Week","dataType":"string"},{"name":"FC Week Offset","dataType":"double"},{"name":"FC Week Series","dataType":"double"},{"name":"FC Week Number","dataType":"double"},{"name":"Day Name","dataType":"string"},{"name":"Day of Week Number","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-13T07:01:32.0891866+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/bf2bc9ad-494e-4117-9977-ce0471137f3e/Fiscal_Calendar.csv?snapshot=2022-06-13T07%3A01%3A32.0427800Z"}]},{"$type":"LocalEntity","name":"MPN","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"MPN.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Manufacturer Name","dataType":"string"},{"name":"Manufacturer Part Number","dataType":"string"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"Item Number","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-13T07:01:32.6051806+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/bf2bc9ad-494e-4117-9977-ce0471137f3e/MPN.csv?snapshot=2022-06-13T07%3A01%3A32.5744722Z"}]},{"$type":"LocalEntity","name":"Order_Transaction_Type","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Order_Transaction_Type.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Name","dataType":"string"},{"name":"Description","dataType":"string"},{"name":"Scheduling Level Code","dataType":"string"},{"name":"TRANSACTION_TYPE_ID","dataType":"double"},{"name":"Transaction Type Code","dataType":"string"},{"name":"Order Category Code","dataType":"string"},{"name":"Start Date","dataType":"dateTime"},{"name":"End Date","dataType":"dateTime"},{"name":"Context","dataType":"string"},{"name":"TP Classification","dataType":"string"},{"name":"Entity","dataType":"string"},{"name":"Tax Applicability","dataType":"string"},{"name":"Accounting Type","dataType":"string"},{"name":"Revenue Flag","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-13T07:01:31.7922959+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/bf2bc9ad-494e-4117-9977-ce0471137f3e/Order_Transaction_Type.csv?snapshot=2022-06-13T07%3A01%3A31.7589458Z"}]},{"$type":"LocalEntity","name":"TBU","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"TBU.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Value Set Name","dataType":"string"},{"name":"Value Set Description","dataType":"string"},{"name":"FLEX_VALUE_SET_ID","dataType":"int64"},{"name":"FLEX_VALUE_ID","dataType":"int64"},{"name":"Flex Value","dataType":"string"},{"name":"Flex Value Meaning","dataType":"string"},{"name":"Value Description","dataType":"string"},{"name":"End Date Active","dataType":"dateTime"},{"name":"Enabled Flag","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-13T07:01:31.4485951+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/bf2bc9ad-494e-4117-9977-ce0471137f3e/TBU.csv?snapshot=2022-06-13T07%3A01%3A31.3961543Z"}]},{"$type":"LocalEntity","name":"Product_Family","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Product_Family.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Value Set Name","dataType":"string"},{"name":"Value Set Description","dataType":"string"},{"name":"FLEX_VALUE_SET_ID","dataType":"int64"},{"name":"FLEX_VALUE_ID","dataType":"int64"},{"name":"Flex Value","dataType":"string"},{"name":"Flex Value Meaning","dataType":"string"},{"name":"Value Description","dataType":"string"},{"name":"End Date Active","dataType":"dateTime"},{"name":"Enabled Flag","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-13T07:01:31.057935+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/bf2bc9ad-494e-4117-9977-ce0471137f3e/Product_Family.csv?snapshot=2022-06-13T07%3A01%3A31.0363626Z"}]},{"$type":"LocalEntity","name":"Product_Line","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Product_Line.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Value Set Name","dataType":"string"},{"name":"Value Set Description","dataType":"string"},{"name":"FLEX_VALUE_SET_ID","dataType":"int64"},{"name":"FLEX_VALUE_ID","dataType":"int64"},{"name":"Flex Value","dataType":"string"},{"name":"Flex Value Meaning","dataType":"string"},{"name":"Value Description","dataType":"string"},{"name":"End Date Active","dataType":"dateTime"},{"name":"Enabled Flag","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-13T07:01:39.8775074+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/bf2bc9ad-494e-4117-9977-ce0471137f3e/Product_Line.csv?snapshot=2022-06-13T07%3A01%3A39.8472610Z"}]},{"$type":"LocalEntity","name":"Forecast_Field","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Forecast_Field.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Value Set Name","dataType":"string"},{"name":"Value Set Description","dataType":"string"},{"name":"FLEX_VALUE_SET_ID","dataType":"int64"},{"name":"FLEX_VALUE_ID","dataType":"int64"},{"name":"Flex Value","dataType":"string"},{"name":"Flex Value Meaning","dataType":"string"},{"name":"Value Description","dataType":"string"},{"name":"End Date Active","dataType":"dateTime"},{"name":"Enabled Flag","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-13T07:01:39.9713327+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/bf2bc9ad-494e-4117-9977-ce0471137f3e/Forecast_Field.csv?snapshot=2022-06-13T07%3A01%3A39.9422062Z"}]}]}