{"name":"lokale_Daten_InputFolder","description":"Folder:\n \\\\cohr\\eu\\delbc\\groups\\Operations\\Statistiken\\Input\n\n02.06.22 - -DIM_RESOURCETRANS_GROUPS - Produktivitaet Resources Report","version":"1.0","culture":"en-US","modifiedTime":"2022-06-10T11:48:26.4683616+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"TARGETS_COSTOFPOORQUALITY":{"queryId":"ae17b445-d07a-44d5-b700-8b042834c853","queryName":"TARGETS_COSTOFPOORQUALITY","loadEnabled":true},"PaladinGruppierung":{"queryId":"d4421904-a844-418e-b382-e244e16efc91","queryName":"PaladinGruppierung","loadEnabled":true},"RESOURCETRANS_GROUPS":{"queryId":"b76019e3-f734-4d35-8b96-a2689a777689","queryName":"RESOURCETRANS_GROUPS","loadEnabled":true},"DIM_FISCALMONTHYEAR":{"queryId":"39f3d934-ad37-4fa7-8daf-5cc2276ced48","queryName":"DIM_FISCALMONTHYEAR","loadEnabled":true},"DIM_PRODUCTFAMILY":{"queryId":"64928cbb-0590-494a-8518-590df6c64045","queryName":"DIM_PRODUCTFAMILY","loadEnabled":true},"MappingFolder":{"queryId":"2dcc4806-6e49-443a-b254-bd6be42b7dd8","queryName":"MappingFolder"},"TARGETS_PRODUKTION":{"queryId":"49daded9-4b41-498f-9a2d-30f539e8c27a","queryName":"TARGETS_PRODUKTION","loadEnabled":true},"DIM_LASERTYP":{"queryId":"80ff4169-9519-4586-8900-e6eb1f9d0aad","queryName":"DIM_LASERTYP","loadEnabled":true}},"document":"section Section1;\r\nshared TARGETS_COSTOFPOORQUALITY = let\r\n  Source = Excel.Workbook(File.Contents(MappingFolder & \"PowerBI_MappingData.xlsx\"), null, true),\r\n  #\"Navigation 1\" = Source{[Item = \"CostOfPoorQuality_Target\", Kind = \"Sheet\"]}[Data],\r\n  #\"Promoted headers\" = Table.PromoteHeaders(#\"Navigation 1\", [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"TARGET_DATE\", type date}, {\"Detail\", type text}, {\"TARGET\", type number}, {\"Note\", type text}})\r\nin\r\n  #\"Changed column type\";\r\nshared PaladinGruppierung = let\r\n  Source = Excel.Workbook(File.Contents(MappingFolder &\"PowerBI_MappingData.xlsx\"), null, true),\r\n  #\"Navigation 1\" = Source{[Item = \"PaladinGruppierung\", Kind = \"Sheet\"]}[Data],\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Navigation 1\", {{\"Column1\", type text}, {\"Column2\", type text}, {\"Column3\", type text}, {\"Column4\", type text}, {\"Column5\", type text}, {\"Column6\", type text}, {\"Column7\", type text}})\r\nin\r\n  #\"Changed column type\";\r\nshared RESOURCETRANS_GROUPS = let\r\n  Source = Excel.Workbook(File.Contents(MappingFolder & \"PowerBI_MappingData.xlsx\"), null, true),\r\n  #\"Navigation 1\" = Source{[Item = \"ResourceTransactionsGruppierung\", Kind = \"Sheet\"]}[Data],\r\n  #\"Promoted headers\" = Table.PromoteHeaders(#\"Navigation 1\", [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"LasertypVerweistabelle\", type text}, {\"LasertypGruppe\", type text}, {\"DepartmentCode\", type text}, {\"InterflexKST\", Int64.Type}, {\"InterflexKSTBezeichnung\", type text}, {\"Abteilung\", type text}, {\"Hinweis\", type text}})\r\nin\r\n  #\"Changed column type\";\r\nshared DIM_FISCALMONTHYEAR = let\n  Source = Excel.Workbook(File.Contents(MappingFolder & \"PowerBI_MappingData.xlsx\"), null, true),\n  #\"Navigation 1\" = Source{[Item = \"DIM_FISCALMONTHYEAR\", Kind = \"Sheet\"]}[Data],\n  #\"Promoted headers\" = Table.PromoteHeaders(#\"Navigation 1\", [PromoteAllScalars = true]),\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"SortColumn\", Int64.Type}, {\"FiscalMonthYear\", type text}, {\"FiscalYear\", type text}, {\"FiscalYearQuarter\", type text}, {\"JahrMonat\", type date}}),\n  #\"Transform columns\" = Table.TransformColumnTypes(#\"Changed column type\", {{\"FMY\", type text}}),\n  #\"Replace errors\" = Table.ReplaceErrorValues(#\"Transform columns\", {{\"FMY\", null}})\nin\n  #\"Replace errors\";\r\nshared DIM_PRODUCTFAMILY = let\n  Source = Excel.Workbook(File.Contents(MappingFolder & \"PowerBI_MappingData.xlsx\"), null, true),\n  #\"Navigation 1\" = Source{[Item = \"DIM_PRODUCTFAMILY\", Kind = \"Sheet\"]}[Data],\n  #\"Promoted headers\" = Table.PromoteHeaders(#\"Navigation 1\", [PromoteAllScalars = true]),\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"Product Family\", type text}})\nin\n  #\"Changed column type\";\r\nshared MappingFolder = \"\\\\cohr\\EU\\DELBC\\GROUPS\\Operations\\Statistiken\\Input\\MappingData\\\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type text];\r\nshared TARGETS_PRODUKTION = let\r\n  Source = Excel.Workbook(File.Contents(MappingFolder & \"PowerBI_MappingData.xlsx\"), null, true),\r\n  #\"Navigation 1\" = Source{[Item = \"Produktion_Targets\", Kind = \"Sheet\"]}[Data],\r\n  #\"Promoted headers\" = Table.PromoteHeaders(#\"Navigation 1\", [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"TARGET_DATE\", type date}, {\"Lasertyp\", type text}, {\"Produktivitaet-Note\", type text}, {\"Yield-Neubauten-Note\", type text}, {\"Produktivitaet-TARGET\", type number}, {\"Yield-Neubauten-Target\", type number}, {\"Produktfamilie\", type text}})\r\nin\r\n  #\"Changed column type\";\r\nshared DIM_LASERTYP = let\n  Source = Excel.Workbook(File.Contents(MappingFolder & \"PowerBI_MappingData.xlsx\"), null, true),\n  #\"Navigation 1\" = Source{[Item = \"DIM_LASERTYP\", Kind = \"Sheet\"]}[Data],\n  #\"Promoted headers\" = Table.PromoteHeaders(#\"Navigation 1\", [PromoteAllScalars = true]),\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"Lasertyp\", type text}})\nin\n  #\"Changed column type\";\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"TARGETS_COSTOFPOORQUALITY","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"TARGETS_COSTOFPOORQUALITY.csv"},"attributes":[{"name":"TARGET_DATE","dataType":"date"},{"name":"Detail","dataType":"string"},{"name":"TARGET","dataType":"double"},{"name":"Note","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-10T11:49:32.3835798+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/01e81895-238b-4361-9de4-ee7723b90742/TARGETS_COSTOFPOORQUALITY.csv?snapshot=2022-06-10T11%3A49%3A31.7920322Z"}]},{"$type":"LocalEntity","name":"PaladinGruppierung","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"PaladinGruppierung.csv"},"attributes":[{"name":"Column1","dataType":"string"},{"name":"Column2","dataType":"string"},{"name":"Column3","dataType":"string"},{"name":"Column4","dataType":"string"},{"name":"Column5","dataType":"string"},{"name":"Column6","dataType":"string"},{"name":"Column7","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-10T11:49:23.0502485+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/01e81895-238b-4361-9de4-ee7723b90742/PaladinGruppierung.csv?snapshot=2022-06-10T11%3A49%3A23.0405923Z"}]},{"$type":"LocalEntity","name":"RESOURCETRANS_GROUPS","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"RESOURCETRANS_GROUPS.csv"},"attributes":[{"name":"LasertypVerweistabelle","dataType":"string"},{"name":"LasertypGruppe","dataType":"string"},{"name":"DepartmentCode","dataType":"string"},{"name":"InterflexKST","dataType":"int64"},{"name":"InterflexKSTBezeichnung","dataType":"string"},{"name":"Abteilung","dataType":"string"},{"name":"Hinweis","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-10T11:49:22.8310653+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/01e81895-238b-4361-9de4-ee7723b90742/RESOURCETRANS_GROUPS.csv?snapshot=2022-06-10T11%3A49%3A22.8117380Z"}]},{"$type":"LocalEntity","name":"DIM_FISCALMONTHYEAR","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"DIM_FISCALMONTHYEAR.csv"},"attributes":[{"name":"SortColumn","dataType":"int64"},{"name":"FiscalMonthYear","dataType":"string"},{"name":"FiscalYear","dataType":"string"},{"name":"FiscalYearQuarter","dataType":"string"},{"name":"JahrMonat","dataType":"date"},{"name":"FMY","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-10T11:49:22.8627116+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/01e81895-238b-4361-9de4-ee7723b90742/DIM_FISCALMONTHYEAR.csv?snapshot=2022-06-10T11%3A49%3A22.8627050Z"}]},{"$type":"LocalEntity","name":"DIM_PRODUCTFAMILY","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"DIM_PRODUCTFAMILY.csv"},"attributes":[{"name":"Product Family","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-10T11:49:23.4096589+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/01e81895-238b-4361-9de4-ee7723b90742/DIM_PRODUCTFAMILY.csv?snapshot=2022-06-10T11%3A49%3A23.4123554Z"}]},{"$type":"LocalEntity","name":"TARGETS_PRODUKTION","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"TARGETS_PRODUKTION.csv"},"attributes":[{"name":"TARGET_DATE","dataType":"date"},{"name":"Produktfamilie","dataType":"string"},{"name":"Lasertyp","dataType":"string"},{"name":"Produktivitaet-TARGET","dataType":"double"},{"name":"Produktivitaet-Note","dataType":"string"},{"name":"Yield-Neubauten-Target","dataType":"double"},{"name":"Yield-Neubauten-Note","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-10T11:49:22.7373994+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/01e81895-238b-4361-9de4-ee7723b90742/TARGETS_PRODUKTION.csv?snapshot=2022-06-10T11%3A49%3A22.7217947Z"}]},{"$type":"LocalEntity","name":"DIM_LASERTYP","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"DIM_LASERTYP.csv"},"attributes":[{"name":"Lasertyp","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-10T11:49:29.5078401+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/01e81895-238b-4361-9de4-ee7723b90742/DIM_LASERTYP.csv?snapshot=2022-06-10T11%3A49%3A29.0957438Z"}]}]}