{"name":"COHERENT_SNOWFLAKE_onlyForTest","description":"verschiedene Tabellen von Snowflake","version":"1.0","culture":"en-US","modifiedTime":"2022-06-01T17:51:47.739356+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"XXREP_RESOURCE_TRAN_V":{"queryId":"fdde91a1-087d-4698-8828-9fbdb40f0378","queryName":"XXREP_RESOURCE_TRAN_V","loadEnabled":true},"InvOrg_Code":{"queryId":"385d2545-1cf0-4981-968a-adc7ad8c05ce","queryName":"InvOrg_Code"},"XXCOH_MT_MTRX_VIEW":{"queryId":"59c98d45-e20f-4296-93da-de884151d2ce","queryName":"XXCOH_MT_MTRX_VIEW","loadEnabled":true},"XXCOH_IM_ITEM_VIEW":{"queryId":"dbb5904c-f19e-4089-b708-ac4155851bd7","queryName":"XXCOH_IM_ITEM_VIEW","loadEnabled":true},"XXCOH_IM_CATEGORY_VIEW":{"queryId":"7aa8f999-0786-4fb4-99a1-82bb350a3c18","queryName":"XXCOH_IM_CATEGORY_VIEW","loadEnabled":true},"XXREP_MTL_SYSTEM_ITEMS_V":{"queryId":"4e60f7cc-b679-4462-930f-c73c35816b66","queryName":"XXREP_MTL_SYSTEM_ITEMS_V","loadEnabled":true},"Organization_ID":{"queryId":"1c3fc304-151e-4275-8546-a8e02e566ab2","queryName":"Organization_ID"},"RESOURCE_TRAN_LDP":{"queryId":"9a121810-08cc-4981-bb41-192086e0da5d","queryName":"RESOURCE_TRAN_LDP","loadEnabled":true},"XXCOH_WIP_TRX_VIEW":{"queryId":"99924e07-f42c-4a77-b65a-c6c199a3a82d","queryName":"XXCOH_WIP_TRX_VIEW","loadEnabled":true},"XXCOH_MI_WIP_FIN_VIEW":{"queryId":"9624f946-2599-44bf-a065-28b00bb2e6c2","queryName":"XXCOH_MI_WIP_FIN_VIEW","loadEnabled":true},"TechnicalBusinessUnit":{"queryId":"b96d58a9-06f8-46f9-baa5-b46f32cd15f4","queryName":"TechnicalBusinessUnit"},"XXREP_MFG_MTL_ITEM_ATTRIBUTES_V":{"queryId":"61864e4f-4b51-4100-9be6-ccf404de7e3b","queryName":"XXREP_MFG_MTL_ITEM_ATTRIBUTES_V","loadEnabled":true},"XXREP_MFG_PURCHASE_ORDER_V":{"queryId":"c5490039-d40a-4c2d-ac70-e0909e2482e2","queryName":"XXREP_MFG_PURCHASE_ORDER_V","loadEnabled":true},"XXCOH_MP_REQ_VIEW":{"queryId":"90115216-09cb-413a-a936-e4f080bc8e72","queryName":"XXCOH_MP_REQ_VIEW","loadEnabled":true},"XXCOH_MP_RECEIPTS_VIEW":{"queryId":"d50cae15-a288-465e-8d3b-4a1338cd7839","queryName":"XXCOH_MP_RECEIPTS_VIEW","loadEnabled":true},"XXCOH_MP_PO_VIEW":{"queryId":"e3f0e571-51b8-4f00-8a33-7f17b9b71831","queryName":"XXCOH_MP_PO_VIEW","loadEnabled":true},"XXREP_MFG_BLANKET_AGREEMENT_V":{"queryId":"c3761f86-fab6-4cf8-8d5f-cd1ba6281dd5","queryName":"XXREP_MFG_BLANKET_AGREEMENT_V","loadEnabled":true},"XXCOH_BACKLOG_FLASH_CUR_PRD_V":{"queryId":"e21b8093-3b2a-40ca-8fb9-9a0b98f8fa70","queryName":"XXCOH_BACKLOG_FLASH_CUR_PRD_V","loadEnabled":true},"XXCOH_BACKLOG_FLASH_PREV_PRD_V":{"queryId":"80cb6534-297f-4d8b-83a7-8fcfa241b4d6","queryName":"XXCOH_BACKLOG_FLASH_PREV_PRD_V","loadEnabled":true},"XXCOH_MI_INVENTORY":{"queryId":"62986d00-60f0-4b7b-83f6-7eb794d85004","queryName":"XXCOH_MI_INVENTORY","loadEnabled":true},"DeliverTo":{"queryId":"bd9f19aa-ca08-4eca-9e15-6154f111c20b","queryName":"DeliverTo"},"Parameter":{"queryId":"2a942daa-2729-403e-a2b7-7df5acc28b28","queryName":"Parameter"}},"document":"section Section1;\r\nshared XXREP_RESOURCE_TRAN_V = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 1\" = Navigation{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXREP_RESOURCE_TRAN_V\", Kind = \"View\"]}[Data],\r\n  #\"Filtered rows_OrgID1\" = Table.SelectRows(#\"Navigation 2\", each [ORGANIZATION_ID] = Organization_ID)\r\nin\r\n  #\"Filtered rows_OrgID1\";\r\nshared InvOrg_Code = let\r\n  Inv_Org = \"LDP\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type any]\r\nin\r\n  Inv_Org;\r\nshared XXCOH_MT_MTRX_VIEW = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 1\" = Navigation{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXCOH_MT_MTRX_VIEW\", Kind = \"View\"]}[Data],\r\n  #\"Reordered columns\" = Table.ReorderColumns(#\"Navigation 2\", {\"DATA_SOURCE\", \"ASOF_DATE\", \"CREATION_DATE\", \"TRANSACTION_DATE\", \"REVISION\", \"TRANSACTION_REFERENCE\", \"SUBINVENTORY_CODE\", \"TRANSACTION_SOURCE_NAME\", \"TRANSACTION_UOM\", \"TRANSACTION_QUANTITY\", \"MMT_PRIMARY_QUANTITY\", \"PRIOR_COSTED_QUANTITY\", \"TRANSFER_PRIOR_COSTED_QUANTITY\", \"OVERCOMPLETION_TRANSACTION_QTY\", \"OVERCOMPLETION_PRIMARY_QTY\", \"QUANTITY_ADJUSTED\", \"MMT_ACTUAL_COST\", \"TRANSACTION_COST\", \"PRIOR_COST\", \"NEW_COST\", \"TRANSFER_COST\", \"TRANSPORTATION_COST\", \"VARIANCE_AMOUNT\", \"MMT_CURRENCY_CODE\", \"MMT_CURRENCY_CONVERSION_RATE\", \"OPERATION_SEQ_NUM\", \"SOURCE_CODE\", \"VENDOR_LOT_NUMBER\", \"TRANSFER_SUBINVENTORY\", \"SHIPMENT_NUMBER\", \"WAYBILL_AIRBILL\", \"FREIGHT_CODE\", \"NUMBER_OF_CONTAINERS\", \"ERROR_CODE\", \"ERROR_EXPLANATION\", \"FINAL_COMPLETION_FLAG\", \"SHIPMENT_COSTED\", \"PICK_SLIP_NUMBER\", \"TRANSACTION_TYPE\", \"TRANSACTION_SOURCE_TYPE\", \"TRANSACTION_ACTION\", \"REASON_NAME\", \"PO_NUM\", \"PO_HEADER_ID\", \"SO_NUM\", \"SO_LINE_NUM\", \"SO_HEADER_ID\", \"SO_LINE_ID\", \"ACCT_ENTITY\", \"ACCT_DEPT\", \"ACCT_ACCOUNT\", \"ACCT_PROJ\", \"ACCT_INTERCO\", \"MOVE_ORDER_NUM\", \"MOVE_ORDER_HEADER_ID\", \"WIP_ENTITY_NAME\", \"WIP_ENTITY_ID\", \"WIP_ENTITY_TYPE\", \"ALIAS_ENTITY\", \"ALIAS_DEPT\", \"ALIAS_ACCOUNT\", \"ALIAS_PROJ\", \"ALIAS_INTERCO\", \"REQ_NUM\", \"REQ_HEADER_ID\", \"CYCLE_COUNT_HEADER_NAME\", \"CYCLE_COUNT_HEADER_ID\", \"PHYSICAL_INVENTORY_NAME\", \"PHYSICAL_INVENTORY_ID\", \"PHYSICAL_INVENTORY_ORG_ID\", \"COST_UPDATE\", \"COST_UPDATE_ID\", \"TRX_ORG_CODE\", \"TRX_OPERATING_UNIT\", \"TRX_LEGAL_ENTITY\", \"TRX_SET_OF_BOOKS\", \"TRX_FUNC_CURRENCY_CODE\", \"PLANNING_ORG_CODE\", \"OWNING_ORG_CODE\", \"TRANSFER_ORG_CODE\", \"XFR_OWNING_ORG_CODE\", \"XFR_PLANNING_ORG_CODE\", \"ITEM_NUMBER\", \"ITEM_DESCRIPTION\", \"ITEM_TYPE\", \"MAKE_OR_BUY\", \"TECHNICAL_BUSINESS_UNIT\", \"PRODUCT_FAMILY\", \"PRODUCT_LINE\", \"LEAD_TIME_CATEGOEY\", \"FORECAST_FIELD\", \"COMMODITY\", \"PRIMARY_ORG\", \"SUPPLY_SOURCE\", \"DEMAND_SOURCE\", \"BACKUP_CATEGORY\", \"ITEM_CUSTOMER\", \"BCP_CODE\", \"ROYALTY\", \"PLANNING_PRODUCT_FAMILY\", \"PLANNING_LOW_LEVEL_CODE\", \"PLANNING_FAMILY_UNIQUE\", \"OPERATIONS_REPORTING\", \"SEC_REPORTING\", \"MATERIAL_ENTITY\", \"MATERIAL_DEPT\", \"MATERIAL_ACCT\", \"MATERIAL_PROJ\", \"MATERIAL_IC\", \"MATERIAL_TBD\", \"MATERIAL_OH_ENTITY\", \"MATERIAL_OH_DEPT\", \"MATERIAL_OH_ACCT\", \"MATERIAL_OH_PROJ\", \"MATERIAL_OH_IC\", \"MATERIAL_OH_TBD\", \"RESOURCE_ENTITY\", \"RESOURCE_DEPT\", \"RESOURCE_ACCT\", \"RESOURCE_PROJ\", \"RESOURCE_IC\", \"RESOURCE_TBD\", \"OVERHEAD_ENTITY\", \"OVERHEAD_DEPT\", \"OVERHEAD_ACCT\", \"OVERHEAD_PROJ\", \"OVERHEAD_IC\", \"OVERHEAD_TBD\", \"OS_PROCESS_ENTITY\", \"OS_PROCESS_DEPT\", \"OS_PROCESS_ACCT\", \"OS_PROCESS_PROJ\", \"OS_PROCESS_IC\", \"OS_PROCESS_TBD\", \"COST_GROUP\", \"COST_GROUP_TYPE\", \"CG_MATERIAL_ENTITY\", \"CG_MATERIAL_DEPT\", \"CG_MATERIAL_ACCT\", \"CG_MATERIAL_PROJ\", \"CG_MATERIAL_IC\", \"CG_MATERIAL_TBD\", \"CG_MATERIAL_OH_ENTITY\", \"CG_MATERIAL_OH_DEPT\", \"CG_MATERIAL_OH_ACCT\", \"CG_MATERIAL_OH_PROJ\", \"CG_MATERIAL_OH_IC\", \"CG_MATERIAL_OH_TBD\", \"CG_RESOURCE_ENTITY\", \"CG_RESOURCE_DEPT\", \"CG_RESOURCE_ACCT\", \"CG_RESOURCE_PROJ\", \"CG_RESOURCE_IC\", \"CG_RESOURCE_TBD\", \"CG_OVERHEAD_ENTITY\", \"CG_OVERHEAD_DEPT\", \"CG_OVERHEAD_ACCT\", \"CG_OVERHEAD_PROJ\", \"CG_OVERHEAD_IC\", \"CG_OVERHEAD_TBD\", \"CG_OS_PROCESS_ENTITY\", \"CG_OS_PROCESS_DEPT\", \"CG_OS_PROCESS_ACCT\", \"CG_OS_PROCESS_PROJ\", \"CG_OS_PROCESS_IC\", \"CG_OS_PROCESS_TBD\", \"CG_EXPENSE_ENTITY\", \"CG_EXPENSE_DEPT\", \"CG_EXPENSE_ACCT\", \"CG_EXPENSE_PROJ\", \"CG_EXPENSE_IC\", \"CG_EXPENSE_TBD\", \"CG_AVGCOSTV_ENTITY\", \"CG_AVGCOSTV_DEPT\", \"CG_AVGCOSTV_ACCT\", \"CG_AVGCOSTV_PROJ\", \"CG_AVGCOSTV_IC\", \"CG_AVGCOSTV_TBD\", \"XFR_COST_GROUP\", \"XFR_COST_GROUP_TYPE\", \"XFRCG_MATERIAL_ENTITY\", \"XFRCG_MATERIAL_DEPT\", \"XFRCG_MATERIAL_ACCT\", \"XFRCG_MATERIAL_PROJ\", \"XFRCG_MATERIAL_IC\", \"XFRCG_MATERIAL_TBD\", \"XFRCG_MATERIAL_OH_ENTITY\", \"XFRCG_MATERIAL_OH_DEPT\", \"XFRCG_MATERIAL_OH_ACCT\", \"XFRCG_MATERIAL_OH_PROJ\", \"XFRCG_MATERIAL_OH_IC\", \"XFRCG_MATERIAL_OH_TBD\", \"XFRCG_RESOURCE_ENTITY\", \"XFRCG_RESOURCE_DEPT\", \"XFRCG_RESOURCE_ACCT\", \"XFRCG_RESOURCE_PROJ\", \"XFRCG_RESOURCE_IC\", \"XFRCG_RESOURCE_TBD\", \"XFRCG_OVERHEAD_ENTITY\", \"XFRCG_OVERHEAD_DEPT\", \"XFRCG_OVERHEAD_ACCT\", \"XFRCG_OVERHEAD_PROJ\", \"XFRCG_OVERHEAD_IC\", \"XFRCG_OVERHEAD_TBD\", \"XFRCG_OS_PROCESS_ENTITY\", \"XFRCG_OS_PROCESS_DEPT\", \"XFRCG_OS_PROCESS_ACCT\", \"XFRCG_OS_PROCESS_PROJ\", \"XFRCG_OS_PROCESS_IC\", \"XFRCG_OS_PROCESS_TBD\", \"XFRCG_EXPENSE_ENTITY\", \"XFRCG_EXPENSE_DEPT\", \"XFRCG_EXPENSE_ACCT\", \"XFRCG_EXPENSE_PROJ\", \"XFRCG_EXPENSE_IC\", \"XFRCG_EXPENSE_TBD\", \"XFRCG_AVGCOSTV_ENTITY\", \"XFRCG_AVGCOSTV_DEPT\", \"XFRCG_AVGCOSTV_ACCT\", \"XFRCG_AVGCOSTV_PROJ\", \"XFRCG_AVGCOSTV_IC\", \"XFRCG_AVGCOSTV_TBD\", \"MTA_ENTITY\", \"MTA_DEPT\", \"MTA_ACCOUNT\", \"MTA_PROJECT\", \"MTA_INTERCO\", \"MTA_TRANSACTION_DATE\", \"PRIMARY_QUANTITY\", \"GL_BATCH_ID\", \"ENTERED_DR\", \"ENTERED_CR\", \"ACCOUNTED_DR\", \"ACCOUNTED_CR\", \"ACCOUNTED_DR_USD\", \"ACCOUNTED_CR_USD\", \"ACCOUNTED_NET\", \"ACCOUNTED_NET_USD\", \"LINE_REFERENCE\", \"RESOURCE_CODE\", \"RESOURCE_DESCRIPTION\", \"ACTIVITY\", \"MTA_CURRENCY_CODE\", \"MTA_CURRENCY_CONVERSION_RATE\", \"ACTUAL_COST\", \"MATERIAL_COST\", \"MATERIAL_OH_COST\", \"RESOURCE_COST\", \"OS_PROCESSING_COST\", \"RESOURCE_OH_COST\", \"PERIOD_NAME\", \"FISCAL_PERIOD\", \"FISCAL_QUARTER\", \"FISCAL_YEAR\", \"FISCAL_WEEK\", \"TRANSACTION_ID\", \"INVENTORY_ITEM_ID\", \"ORGANIZATION_ID\", \"RMA_LINE_ID\", \"REPETITIVE_LINE_ID\", \"TRANSFER_TRANSACTION_ID\", \"TRANSACTION_CREATED_BY\", \"TRANSACTION_UPDATED_BY\", \"ORG_TECHNICAL_BUSINESS_UNIT\", \"ORG_PRODUCT_FAMILY\", \"ORG_PRODUCT_LINE\", \"ORG_FORECAST_FIELD\", \"CAL_MONTH\", \"ROW_CREATION_DATE\"}),\r\n  #\"Filtered rows\" = Table.SelectRows(#\"Reordered columns\", each [PRIMARY_ORG] = InvOrg_Code)\r\nin\r\n  #\"Filtered rows\";\r\nshared XXCOH_IM_ITEM_VIEW = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 1\" = Navigation{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXCOH_IM_ITEM_VIEW\", Kind = \"View\"]}[Data],\r\n  #\"Filtered rows\" = Table.SelectRows(#\"Navigation 2\", each [ORGANIZATION_CODE] = InvOrg_Code),\r\n  #\"Removed columns\" = Table.RemoveColumns(#\"Filtered rows\", {\"LAST_UPDATED_BY\", \"CREATED_BY\", \"LAST_UPDATE_LOGIN\", \"SUMMARY_FLAG\", \"BUYER_ID\", \"SEGMENT1\", \"ATTRIBUTE_CATEGORY\", \"ATTRIBUTE13\", \"ATTRIBUTE14\", \"ATTRIBUTE15\"})\r\nin\r\n  #\"Removed columns\";\r\nshared XXCOH_IM_CATEGORY_VIEW = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 1\" = Navigation{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXCOH_IM_CATEGORY_VIEW\", Kind = \"View\"]}[Data],\r\n  #\"Filtered rows\" = Table.SelectRows(#\"Navigation 2\", each [ORGANIZATION_CODE] = InvOrg_Code),\r\n  #\"Filtered rows 1\" = Table.SelectRows(#\"Filtered rows\", each not Text.StartsWith([ITEM_NUMBER], \"D\")),\r\n  #\"Removed columns\" = Table.RemoveColumns(#\"Filtered rows 1\", {\"ROW_UPDATED_BY\", \"PF_ITEM_NUMBER\", \"ECCN_ECCN\", \"COO_COUNTRY_OF_ORIGIN\", \"HTS_HTS_SCHEDULE_B\", \"PLNG_GREEN_SUPPLY_STATUS\", \"PLNG_PLANNING_ACTION\", \"PLNG_FAMILY_UNIQUE\", \"ST_SALES_TAX_CATEGORY\", \"CDI_CARTON_GROUP\", \"CI_CARTON_GROUP\", \"CON_CONTRACT_CATEGORY\", \"PTLX_PATLEX_PERCENT\", \"COMM_COMMODITY\", \"SLT_SERVICE_LEAD_TIME\", \"FF_FORECAST_FIELD\", \"CS_SUPPLY_SOURCE\", \"CS_DEMAND_SOURCE\", \"DBT_DB_TEMP\", \"BUP_BACKUP\", \"PO_PRIMARY_ORG\", \"PO_SUPPLY_CHAIN_PORG\", \"BCP_BCP\", \"CUST_CUSTOMER\", \"ROYLT_ROYALTY\", \"SC_SECURITY_CLASS\", \"GTD_GREEN_TRANSITION_DATE\", \"ROH_EU_ROHS_COMPLIANT\", \"ROH_CHINA_ROHS_COMPLIANT\", \"FDA_FDA_ACCESSION\", \"SCC_SEQUENCE\", \"SCC_COMMODITY\", \"SCC_UNSPSC\", \"SR_OPERATING_UNIT\", \"SR_PERCENTAGE\", \"SR_VENDOR\", \"SR_VENDOR_SITE\", \"SI_INSTALL_WITH_SALE\", \"IT_ITEM_TYPE_CODE\", \"OPSR_SEC_REPORTING\", \"OPSR_DEMAND_SOURCE\", \"SECR_SEC_REPORTING\", \"OPC_ORG\", \"OPC_PLANNING_CODE\", \"SP_SHIPMENT_PRIORITY\", \"FI_FISCAL_YEAR\", \"FI_SFDC_FORECAST_ITEM\", \"PG_ORG\", \"PG_PLANNING_GROUP\", \"WC_ORG\", \"WC_WORK_CELL\", \"RM_REPLENISHMENT_METHOD\", \"SFLT_SUPPLIER_FULL_LEAD_TIME\", \"SCS_SUPPLY_CHAIN_STATUS\", \"BPAS_BPA_STATUS\", \"MCOO_MULTI_COUNTRY_OF_ORIGIN\", \"DSO_DEFAULT_SHIPPING_ORG\", \"SFDCT_SFDC_TRANSFER\", \"IKC_ORG\", \"IKC_ORG_GROUP\", \"IKC_USERID\", \"EUHTS_HTS_CODE_EU\", \"CRI_ACCOUNT_NUMBER\", \"XYZ_XYZ_CLASS\", \"SCSD_SUPPLY_CHAIN_STATUS_DAYS\", \"MMKS_SOURCE\", \"MMKS_AUTO_UPDATE\", \"DO_DESIGN_ORG\"}),\r\n  #\"Reordered columns\" = Table.ReorderColumns(#\"Removed columns\", {\"INVENTORY_ITEM_ID\", \"ORGANIZATION_ID\", \"ITEM_NUMBER\", \"DESCRIPTION\", \"ORGANIZATION_CODE\", \"ITEM_CREATION_DATE\", \"ROW_CREATION_DATE\", \"OPROD_TBU\", \"PROD_TBU\", \"PROD_FAMILY\", \"PROD_LINE\", \"PROD_FORECAST_FIELD\", \"OPROD_FAMILY\", \"OPROD_LINE\", \"OPROD_FORECAST_FIELD\", \"IT_ITEM_TYPE_MEANING\"}),\r\n  #\"Removed columns 1\" = Table.RemoveColumns(#\"Reordered columns\", {\"ROW_CREATION_DATE\"}),\r\n  #\"Reordered columns 1\" = Table.ReorderColumns(#\"Removed columns 1\", {\"INVENTORY_ITEM_ID\", \"ORGANIZATION_ID\", \"ITEM_NUMBER\", \"DESCRIPTION\", \"OPROD_TBU\", \"ORGANIZATION_CODE\", \"ITEM_CREATION_DATE\", \"PROD_TBU\", \"PROD_FAMILY\", \"PROD_LINE\", \"PROD_FORECAST_FIELD\", \"OPROD_FAMILY\", \"OPROD_LINE\", \"OPROD_FORECAST_FIELD\", \"IT_ITEM_TYPE_MEANING\"})\r\nin\r\n  #\"Reordered columns 1\";\r\nshared XXREP_MTL_SYSTEM_ITEMS_V = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 1\" = Navigation{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXREP_MTL_SYSTEM_ITEMS_V\", Kind = \"View\"]}[Data],\r\n  #\"Filtered rows\" = Table.SelectRows(#\"Navigation 2\", each [ORGANIZATION_CODE] = InvOrg_Code)\r\nin\r\n  #\"Filtered rows\";\r\nshared Organization_ID = let\r\n  Inv_Org = 587 meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type any]\r\nin\r\n  Inv_Org;\r\nshared RESOURCE_TRAN_LDP = let\r\n  Source = XXREP_RESOURCE_TRAN_V,\r\n  #\"Removed columns\" = Table.RemoveColumns(Source, {\"CREATED_BY_LOGIN\", \"INVORG_ID\"}),\r\n  #\"Filtered rows\" = Table.SelectRows(#\"Removed columns\", each Date.IsInPreviousNYears([TRANSACTION_DATE], 2))\r\nin\r\n  #\"Filtered rows\";\r\nshared XXCOH_WIP_TRX_VIEW = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 1\" = Navigation{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n  #\"Filtered rows 1\" = Table.SelectRows(#\"Navigation 1\", each [Name] = \"WIP_DISCRETE_JOBS_V\" or [Name] = \"XXCOH_MI_WIP_FIN_VIEW\" or [Name] = \"XXCOH_WIP_TRX_VIEW\" or [Name] = \"XXREP_WIP_ACT_CLASSES_V\" or [Name] = \"XXREP_WIP_BALANCES_V\" or [Name] = \"XXREP_WIP_DISCRETE_JOBS_V\" or [Name] = \"XXSF_MI_WIP_RES_ACCT_V\" or [Name] = \"XXSF_MI_WIP_RESOURCE_V\"),\r\n  #\"Navigation 2\" = #\"Filtered rows 1\"{[Name = \"XXCOH_WIP_TRX_VIEW\", Kind = \"View\"]}[Data],\r\n  #\"Filtered rows_OrgID1\" = Table.SelectRows(#\"Navigation 2\", each [ORGANIZATION_ID] = Organization_ID),\r\n  #\"Filtered rows\" = Table.SelectRows(#\"Filtered rows_OrgID1\", each Date.IsInPreviousNYears([TRX_DATE], 2))\r\nin\r\n  #\"Filtered rows\";\r\nshared XXCOH_MI_WIP_FIN_VIEW = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 1\" = Navigation{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXCOH_MI_WIP_FIN_VIEW\", Kind = \"View\"]}[Data],\r\n  #\"Filtered rows_BusinessUnit\" = Table.SelectRows(#\"Navigation 2\", each [FIN_TBU] = TechnicalBusinessUnit)\r\nin\r\n  #\"Filtered rows_BusinessUnit\";\r\nshared TechnicalBusinessUnit = let\r\n  Inv_Org = \"DPSS_Germany\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type any]\r\nin\r\n  Inv_Org;\r\nshared XXREP_MFG_MTL_ITEM_ATTRIBUTES_V = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 1\" = Navigation{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXREP_MFG_MTL_ITEM_ATTRIBUTES_V\", Kind = \"View\"]}[Data],\r\n  #\"Filtered rows\" = Table.SelectRows(#\"Navigation 2\", each [ORGANIZATION_CODE] = InvOrg_Code)\r\nin\r\n  #\"Filtered rows\";\r\nshared XXREP_MFG_PURCHASE_ORDER_V = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 1\" = Navigation{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXREP_MFG_PURCHASE_ORDER_V\", Kind = \"View\"]}[Data],\r\n  #\"Filtered rows\" = Table.SelectRows(#\"Navigation 2\", each [ORGANIZATION_CODE] = InvOrg_Code)\r\nin\r\n  #\"Filtered rows\";\r\nshared XXCOH_MP_REQ_VIEW = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 1\" = Navigation{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXCOH_MP_REQ_VIEW\", Kind = \"View\"]}[Data],\r\n  #\"Filtered rows\" = Table.SelectRows(#\"Navigation 2\", each [OPERATING_UNIT_ID] = Organization_ID)\r\nin\r\n  #\"Filtered rows\";\r\nshared XXCOH_MP_RECEIPTS_VIEW = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 1\" = Navigation{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXCOH_MP_RECEIPTS_VIEW\", Kind = \"View\"]}[Data],\r\n  #\"Filtered rows 1\" = Table.SelectRows(#\"Navigation 2\", each [ORG_CODE] = InvOrg_Code),\r\n  #\"Reordered columns\" = Table.ReorderColumns(#\"Filtered rows 1\", {\"ASOF_DATE\", \"ASOF_DATE_DISP\", \"RECEIPT_NUM\", \"SOURCE_DOCUMENT_CODE\", \"RECEIPT_COMMENTS\", \"RECEIPT_LINE_NUM\", \"DESTINATION_TYPE_CODE\", \"COUNTRY_OF_ORIGIN_CODE\", \"TRANSACTION_DATE\", \"TRANSACTION_TYPE\", \"USER_ENTERED_FLAG\", \"ITEM_NUMBER\", \"ITEM_DESCRIPTION\", \"ITEM_REVISION\", \"DAYS_LATE_RECEIPT_ALLOWED\", \"ORDER_NUMBER\", \"ORDER_TYPE\", \"SOURCE_NAME\", \"ALTERNATE_SOURCE_NAME\", \"VENDOR_INTERNAL\", \"INTERDIV\", \"SOURCE_NUMBER\", \"LINE_NUMBER\", \"QUANTITY\", \"UNIT_OF_MEASURE\", \"PRIMARY_QUANTITY\", \"PRIMARY_UNIT_OF_MEASURE\", \"PO_SHIPMENT_NUMBER\", \"PO_SHIPMENT_QUANTITY\", \"ORDERED_QANTITY\", \"ORDERED_UNIT_OF_MEASURE\", \"UNIT_PRICE\", \"CURRENCY_CODE\", \"CURRENCY_CONVERSION_RATE\", \"OE_CURRENCY_CODE\", \"PO_CURRENCY_CODE\", \"RSH_CURRENCY_CODE\", \"ITEM_COST\", \"ITEM_ADD_BACK_COST\", \"MATERIAL_COST\", \"RESOURCE_COST\", \"MATERIAL_OVERHEAD_COST\", \"OVERHEAD_COST\", \"OUTSIDE_PROCESSING_COST\", \"UNBURDENED_COST\", \"NOTE_TO_RECEIVER\", \"DUE_DATE\", \"PACKING_SLIP\", \"FREIGHT_CARRIER\", \"WAYBILL_AIRBILL_NUM\", \"NUM_OF_CONTAINERS\", \"SHIPPING_DATE\", \"FOB\", \"INSPECTION_STATUS_CODE\", \"INSPECTON_QUALITY_CODE\", \"FROM_ORG_CODE\", \"FROM_OPERATING_UNIT\", \"FROM_FUNC_CURRENCY_CODE\", \"ROUTING_NAME\", \"REASON_CODE\", \"DESTINATION_CONTEXT\", \"SUBINVENTORY\", \"TRANSACTION_CREATION_DATE\", \"DEFAULT_SUBINVENTORY\", \"CURRENT_LOCATION\", \"ORG_CODE\", \"OPERATING_UNIT\", \"OPERATING_UNIT_ID\", \"LEGAL_ENTITY\", \"LEGAL_ENTITY_ID\", \"FUNC_CURRENCY_CODE\", \"BUYER\", \"RECEIVER\", \"DELIVER_TO_PERSON\", \"DELIVER_TO_LOCATION\", \"FISCAL_PERIOD\", \"FISCAL_QUARTER\", \"FISCAL_YEAR\", \"FISCAL_WEEK\", \"TR_USD_RATE\", \"FC_USD_RATE\", \"WIP_ENTITY_NAME\", \"WIP_DESCRIPTION\", \"WIP_OPERATION_SEQ_NUM\", \"WIP_RESOURCE_SEQ_NUM\", \"QUANTITY_BILLED\", \"AMOUNT_BILLED\", \"PO_DESTINATION_TYPE_CODE\", \"PARENT_TRANSACTION_ID\", \"TRANSACTION_ID\", \"INV_TRANSACTION_ID\", \"PO_HEADER_ID\", \"PO_LINE_ID\", \"PO_LINE_LOCATION_ID\", \"PO_DISTRIBUTION_ID\", \"REQUISITION_LINE_ID\", \"SHIPMENT_HEADER_ID\", \"SHIPMENT_LINE_ID\", \"ITEM_ID\", \"FROM_ORGANIZATION_ID\", \"TO_ORGANIZATION_ID\", \"OE_ORDER_HEADER_ID\", \"OE_ORDER_LINE_ID\", \"WIP_ENTITY_ID\", \"ROW_CREATION_DATE\"}),\r\n  #\"Removed columns\" = Table.RemoveColumns(#\"Reordered columns\", {\"COUNTRY_OF_ORIGIN_CODE\"}),\r\n  #\"Reordered columns 1\" = Table.ReorderColumns(#\"Removed columns\", {\"ASOF_DATE\", \"ASOF_DATE_DISP\", \"SOURCE_DOCUMENT_CODE\", \"RECEIPT_NUM\", \"RECEIPT_LINE_NUM\", \"RECEIPT_COMMENTS\", \"DESTINATION_TYPE_CODE\", \"TRANSACTION_DATE\", \"TRANSACTION_TYPE\", \"USER_ENTERED_FLAG\", \"ITEM_NUMBER\", \"ITEM_DESCRIPTION\", \"ITEM_REVISION\", \"DAYS_LATE_RECEIPT_ALLOWED\", \"ORDER_NUMBER\", \"ORDER_TYPE\", \"SOURCE_NAME\", \"ALTERNATE_SOURCE_NAME\", \"VENDOR_INTERNAL\", \"INTERDIV\", \"SOURCE_NUMBER\", \"LINE_NUMBER\", \"QUANTITY\", \"UNIT_OF_MEASURE\", \"PRIMARY_QUANTITY\", \"PRIMARY_UNIT_OF_MEASURE\", \"PO_SHIPMENT_NUMBER\", \"PO_SHIPMENT_QUANTITY\", \"ORDERED_QANTITY\", \"ORDERED_UNIT_OF_MEASURE\", \"UNIT_PRICE\", \"CURRENCY_CODE\", \"CURRENCY_CONVERSION_RATE\", \"OE_CURRENCY_CODE\", \"PO_CURRENCY_CODE\", \"RSH_CURRENCY_CODE\", \"ITEM_COST\", \"ITEM_ADD_BACK_COST\", \"MATERIAL_COST\", \"RESOURCE_COST\", \"MATERIAL_OVERHEAD_COST\", \"OVERHEAD_COST\", \"OUTSIDE_PROCESSING_COST\", \"UNBURDENED_COST\", \"NOTE_TO_RECEIVER\", \"DUE_DATE\", \"PACKING_SLIP\", \"FREIGHT_CARRIER\", \"WAYBILL_AIRBILL_NUM\", \"NUM_OF_CONTAINERS\", \"SHIPPING_DATE\", \"FOB\", \"INSPECTION_STATUS_CODE\", \"INSPECTON_QUALITY_CODE\", \"FROM_ORG_CODE\", \"FROM_OPERATING_UNIT\", \"FROM_FUNC_CURRENCY_CODE\", \"ROUTING_NAME\", \"REASON_CODE\", \"DESTINATION_CONTEXT\", \"SUBINVENTORY\", \"TRANSACTION_CREATION_DATE\", \"DEFAULT_SUBINVENTORY\", \"CURRENT_LOCATION\", \"ORG_CODE\", \"OPERATING_UNIT\", \"OPERATING_UNIT_ID\", \"LEGAL_ENTITY\", \"LEGAL_ENTITY_ID\", \"FUNC_CURRENCY_CODE\", \"BUYER\", \"RECEIVER\", \"DELIVER_TO_PERSON\", \"DELIVER_TO_LOCATION\", \"FISCAL_PERIOD\", \"FISCAL_QUARTER\", \"FISCAL_YEAR\", \"FISCAL_WEEK\", \"TR_USD_RATE\", \"FC_USD_RATE\", \"WIP_ENTITY_NAME\", \"WIP_DESCRIPTION\", \"WIP_OPERATION_SEQ_NUM\", \"WIP_RESOURCE_SEQ_NUM\", \"QUANTITY_BILLED\", \"AMOUNT_BILLED\", \"PO_DESTINATION_TYPE_CODE\", \"PARENT_TRANSACTION_ID\", \"TRANSACTION_ID\", \"INV_TRANSACTION_ID\", \"PO_HEADER_ID\", \"PO_LINE_ID\", \"PO_LINE_LOCATION_ID\", \"PO_DISTRIBUTION_ID\", \"REQUISITION_LINE_ID\", \"SHIPMENT_HEADER_ID\", \"SHIPMENT_LINE_ID\", \"ITEM_ID\", \"FROM_ORGANIZATION_ID\", \"TO_ORGANIZATION_ID\", \"OE_ORDER_HEADER_ID\", \"OE_ORDER_LINE_ID\", \"WIP_ENTITY_ID\", \"ROW_CREATION_DATE\"}),\r\n  #\"Removed columns 1\" = Table.RemoveColumns(#\"Reordered columns 1\", {\"DAYS_LATE_RECEIPT_ALLOWED\", \"ITEM_REVISION\"}),\r\n  #\"Reordered columns 2\" = Table.ReorderColumns(#\"Removed columns 1\", {\"ASOF_DATE\", \"ASOF_DATE_DISP\", \"SOURCE_DOCUMENT_CODE\", \"RECEIPT_NUM\", \"RECEIPT_LINE_NUM\", \"ORDER_NUMBER\", \"RECEIPT_COMMENTS\", \"DESTINATION_TYPE_CODE\", \"TRANSACTION_DATE\", \"TRANSACTION_TYPE\", \"USER_ENTERED_FLAG\", \"ITEM_NUMBER\", \"ITEM_DESCRIPTION\", \"ORDER_TYPE\", \"SOURCE_NAME\", \"ALTERNATE_SOURCE_NAME\", \"VENDOR_INTERNAL\", \"INTERDIV\", \"SOURCE_NUMBER\", \"LINE_NUMBER\", \"QUANTITY\", \"UNIT_OF_MEASURE\", \"PRIMARY_QUANTITY\", \"PRIMARY_UNIT_OF_MEASURE\", \"PO_SHIPMENT_NUMBER\", \"PO_SHIPMENT_QUANTITY\", \"ORDERED_QANTITY\", \"ORDERED_UNIT_OF_MEASURE\", \"UNIT_PRICE\", \"CURRENCY_CODE\", \"CURRENCY_CONVERSION_RATE\", \"OE_CURRENCY_CODE\", \"PO_CURRENCY_CODE\", \"RSH_CURRENCY_CODE\", \"ITEM_COST\", \"ITEM_ADD_BACK_COST\", \"MATERIAL_COST\", \"RESOURCE_COST\", \"MATERIAL_OVERHEAD_COST\", \"OVERHEAD_COST\", \"OUTSIDE_PROCESSING_COST\", \"UNBURDENED_COST\", \"NOTE_TO_RECEIVER\", \"DUE_DATE\", \"PACKING_SLIP\", \"FREIGHT_CARRIER\", \"WAYBILL_AIRBILL_NUM\", \"NUM_OF_CONTAINERS\", \"SHIPPING_DATE\", \"FOB\", \"INSPECTION_STATUS_CODE\", \"INSPECTON_QUALITY_CODE\", \"FROM_ORG_CODE\", \"FROM_OPERATING_UNIT\", \"FROM_FUNC_CURRENCY_CODE\", \"ROUTING_NAME\", \"REASON_CODE\", \"DESTINATION_CONTEXT\", \"SUBINVENTORY\", \"TRANSACTION_CREATION_DATE\", \"DEFAULT_SUBINVENTORY\", \"CURRENT_LOCATION\", \"ORG_CODE\", \"OPERATING_UNIT\", \"OPERATING_UNIT_ID\", \"LEGAL_ENTITY\", \"LEGAL_ENTITY_ID\", \"FUNC_CURRENCY_CODE\", \"BUYER\", \"RECEIVER\", \"DELIVER_TO_PERSON\", \"DELIVER_TO_LOCATION\", \"FISCAL_PERIOD\", \"FISCAL_QUARTER\", \"FISCAL_YEAR\", \"FISCAL_WEEK\", \"TR_USD_RATE\", \"FC_USD_RATE\", \"WIP_ENTITY_NAME\", \"WIP_DESCRIPTION\", \"WIP_OPERATION_SEQ_NUM\", \"WIP_RESOURCE_SEQ_NUM\", \"QUANTITY_BILLED\", \"AMOUNT_BILLED\", \"PO_DESTINATION_TYPE_CODE\", \"PARENT_TRANSACTION_ID\", \"TRANSACTION_ID\", \"INV_TRANSACTION_ID\", \"PO_HEADER_ID\", \"PO_LINE_ID\", \"PO_LINE_LOCATION_ID\", \"PO_DISTRIBUTION_ID\", \"REQUISITION_LINE_ID\", \"SHIPMENT_HEADER_ID\", \"SHIPMENT_LINE_ID\", \"ITEM_ID\", \"FROM_ORGANIZATION_ID\", \"TO_ORGANIZATION_ID\", \"OE_ORDER_HEADER_ID\", \"OE_ORDER_LINE_ID\", \"WIP_ENTITY_ID\", \"ROW_CREATION_DATE\"}),\r\n  #\"Removed columns 2\" = Table.RemoveColumns(#\"Reordered columns 2\", {\"OPERATING_UNIT\", \"OPERATING_UNIT_ID\", \"LEGAL_ENTITY\", \"LEGAL_ENTITY_ID\", \"BUYER\", \"RECEIVER\", \"DELIVER_TO_PERSON\"})\r\nin\r\n  #\"Removed columns 2\";\r\nshared XXCOH_MP_PO_VIEW = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 1\" = Navigation{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXCOH_MP_PO_VIEW\", Kind = \"View\"]}[Data],\r\n  #\"Filtered rows 1\" = Table.SelectRows(#\"Navigation 2\", each [SHIP_TO_LOCATION] = \"LDP - Estlandring\" or [SHIP_TO_LOCATION] = \"LDP - Luebeck\")\r\nin\r\n  #\"Filtered rows 1\";\r\nshared XXREP_MFG_BLANKET_AGREEMENT_V = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 1\" = Navigation{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXREP_MFG_BLANKET_AGREEMENT_V\", Kind = \"View\"]}[Data],\r\n  #\"Filtered rows 1\" = Table.SelectRows(#\"Navigation 2\", each Text.Contains([SHIP_TO_LOCATION], \"LDP\"))\r\nin\r\n  #\"Filtered rows 1\";\r\nshared XXCOH_BACKLOG_FLASH_CUR_PRD_V = let\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\n  #\"Navigation 1\" = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\n  #\"Navigation 3\" = #\"Navigation 2\"{[Name = \"XXCOH_BACKLOG_FLASH_CUR_PRD_V\", Kind = \"View\"]}[Data]\nin\n  #\"Navigation 3\";\r\nshared XXCOH_BACKLOG_FLASH_PREV_PRD_V = let\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\n  #\"Navigation 1\" = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\n  #\"Navigation 3\" = #\"Navigation 2\"{[Name = \"XXCOH_BACKLOG_FLASH_PREV_PRD_V\", Kind = \"View\"]}[Data],\r\n  #\"Filtered rows\" = Table.SelectRows(#\"Navigation 3\", each ([FIN_PRODUCT_GROUP] = \"DPSS Germany\"))\nin\n  #\"Filtered rows\";\r\nshared XXCOH_MI_INVENTORY = let\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\n  #\"Navigation 1\" = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\n  #\"Navigation 3\" = #\"Navigation 2\"{[Name = \"XXCOH_MI_INVENTORY_VIEW\", Kind = \"View\"]}[Data]\nin\n  #\"Navigation 3\";\r\nshared DeliverTo = null meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type text, List = {\"DEU-Lübeck,LDP - Lubeck\"}];\r\nshared Parameter = \"DEU-Lübeck\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type text, List = {\"DEU-Lübeck\", \"LDP - Lubeck\"}, DefaultValue = \"LDP - Lubeck\"];\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"XXREP_RESOURCE_TRAN_V","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"XXREP_RESOURCE_TRAN_V.csv"},"attributes":[{"name":"JOB_NUMBER","dataType":"string"},{"name":"WIP_JOB_DESCRIPTION","dataType":"string"},{"name":"WIPJOB_ORG_KEY_CODE","dataType":"string"},{"name":"WIPJOB_ORG_KEY_ID","dataType":"string"},{"name":"DISCRETE_JOB_FLAG","dataType":"string"},{"name":"JOB_TYPE","dataType":"string"},{"name":"RESOURCE_TRX_REFERENCE","dataType":"string"},{"name":"TRANSACTION_ID","dataType":"double"},{"name":"TRANSACTION_TYPE","dataType":"string"},{"name":"TRANSACTION_DATE","dataType":"dateTime"},{"name":"SOURCE_CODE","dataType":"string"},{"name":"OPERATION_SEQ_NUM","dataType":"double"},{"name":"RESOURCE_SEQ_NUM","dataType":"double"},{"name":"AUTOCHARGE_TYPE","dataType":"string"},{"name":"USAGE_RATE_OR_AMOUNT","dataType":"double"},{"name":"BASIS_TYPE","dataType":"string"},{"name":"TRANSACTION_QUANTITY","dataType":"double"},{"name":"TRANSACTION_UOM","dataType":"string"},{"name":"PRIMARY_QUANTITY","dataType":"double"},{"name":"PRIMARY_UOM","dataType":"string"},{"name":"ACTUAL_RESOURCE_RATE","dataType":"double"},{"name":"STANDARD_RESOURCE_RATE","dataType":"double"},{"name":"STANDARD_RATE_FLAG","dataType":"string"},{"name":"CURRENCY_CODE","dataType":"string"},{"name":"MOVE_PRIMARY_QUANTITY","dataType":"double"},{"name":"FM_OPERATION_SEQ_NUM","dataType":"double"},{"name":"TO_OPERATION_SEQ_NUM","dataType":"double"},{"name":"ACTIVITY","dataType":"string"},{"name":"ATTRIBUTE_CATEGORY","dataType":"string"},{"name":"ATTRIBUTE1","dataType":"string"},{"name":"ATTRIBUTE2","dataType":"string"},{"name":"ORGANIZATION_ID","dataType":"double"},{"name":"WIP_ENTITY_ID","dataType":"double"},{"name":"LINE_ID","dataType":"double"},{"name":"PRIMARY_ITEM_ID","dataType":"double"},{"name":"DEPARTMENT_ID","dataType":"double"},{"name":"RESOURCE_ID","dataType":"double"},{"name":"EMPLOYEE_ID","dataType":"double"},{"name":"ACTIVITY_ID","dataType":"double"},{"name":"REASON_ID","dataType":"double"},{"name":"MOVE_TRANSACTION_ID","dataType":"double"},{"name":"COMPLETION_TRANSACTION_ID","dataType":"double"},{"name":"PROJECT_ID","dataType":"double"},{"name":"TASK_ID","dataType":"double"},{"name":"SOURCE_LINE_ID","dataType":"double"},{"name":"CREATION_DATE","dataType":"dateTime"},{"name":"CREATED_BY","dataType":"double"},{"name":"LAST_UPDATE_DATE","dataType":"dateTime"},{"name":"LAST_UPDATED_BY","dataType":"double"},{"name":"PROJECT_NAME","dataType":"string"},{"name":"PROJECT_NUMBER","dataType":"string"},{"name":"DEPARTMENT_CODE","dataType":"string"},{"name":"RESOURCE_CODE","dataType":"string"},{"name":"COST_CODE_TYPE","dataType":"double"},{"name":"ALLOW_COSTS","dataType":"string"},{"name":"ALLOW_COSTS_FLAG","dataType":"double"},{"name":"COST_CODE_TYPE_NAME","dataType":"string"},{"name":"ITEM_NUMBER","dataType":"string"},{"name":"ITEM_DESCRIPTION","dataType":"string"},{"name":"ITEM_ORG_KEY_ID","dataType":"string"},{"name":"ITEM_ORG_KEY_CODE","dataType":"string"},{"name":"ACCT_PERIOD_ID","dataType":"double"},{"name":"PERIOD_NAME","dataType":"string"},{"name":"PERIOD_START_DATE","dataType":"dateTime"},{"name":"PERIOD_CLOSE_DATE","dataType":"dateTime"},{"name":"INVORG_CODE","dataType":"string"},{"name":"INVORG_ID","dataType":"double"},{"name":"LOCAL_EXTRACT_DATE","dataType":"dateTime"},{"name":"EXTRACT_DATE","dataType":"dateTime"},{"name":"TIMEZONE","dataType":"string"},{"name":"CREATED_BY_LOGIN","dataType":"string"},{"name":"LAST_UPDATED_BY_LOGIN","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-04-13T09:41:50.2983422+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/238d817d-4dd8-4196-99ff-688e83f7a240/XXREP_RESOURCE_TRAN_V.csv?snapshot=2022-04-13T09%3A40%3A58.2812119Z"}]},{"$type":"LocalEntity","name":"XXCOH_MT_MTRX_VIEW","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"XXCOH_MT_MTRX_VIEW.csv"},"attributes":[{"name":"DATA_SOURCE","dataType":"string"},{"name":"ASOF_DATE","dataType":"date"},{"name":"CREATION_DATE","dataType":"dateTime"},{"name":"TRANSACTION_DATE","dataType":"dateTime"},{"name":"REVISION","dataType":"string"},{"name":"TRANSACTION_REFERENCE","dataType":"string"},{"name":"SUBINVENTORY_CODE","dataType":"string"},{"name":"TRANSACTION_SOURCE_NAME","dataType":"string"},{"name":"TRANSACTION_UOM","dataType":"string"},{"name":"TRANSACTION_QUANTITY","dataType":"double"},{"name":"MMT_PRIMARY_QUANTITY","dataType":"double"},{"name":"PRIOR_COSTED_QUANTITY","dataType":"double"},{"name":"TRANSFER_PRIOR_COSTED_QUANTITY","dataType":"double"},{"name":"OVERCOMPLETION_TRANSACTION_QTY","dataType":"double"},{"name":"OVERCOMPLETION_PRIMARY_QTY","dataType":"double"},{"name":"QUANTITY_ADJUSTED","dataType":"double"},{"name":"MMT_ACTUAL_COST","dataType":"double"},{"name":"TRANSACTION_COST","dataType":"double"},{"name":"PRIOR_COST","dataType":"double"},{"name":"NEW_COST","dataType":"double"},{"name":"TRANSFER_COST","dataType":"double"},{"name":"TRANSPORTATION_COST","dataType":"double"},{"name":"VARIANCE_AMOUNT","dataType":"double"},{"name":"MMT_CURRENCY_CODE","dataType":"string"},{"name":"MMT_CURRENCY_CONVERSION_RATE","dataType":"double"},{"name":"OPERATION_SEQ_NUM","dataType":"double"},{"name":"SOURCE_CODE","dataType":"string"},{"name":"VENDOR_LOT_NUMBER","dataType":"string"},{"name":"TRANSFER_SUBINVENTORY","dataType":"string"},{"name":"SHIPMENT_NUMBER","dataType":"string"},{"name":"WAYBILL_AIRBILL","dataType":"string"},{"name":"FREIGHT_CODE","dataType":"string"},{"name":"NUMBER_OF_CONTAINERS","dataType":"double"},{"name":"ERROR_CODE","dataType":"string"},{"name":"ERROR_EXPLANATION","dataType":"string"},{"name":"FINAL_COMPLETION_FLAG","dataType":"string"},{"name":"SHIPMENT_COSTED","dataType":"string"},{"name":"PICK_SLIP_NUMBER","dataType":"double"},{"name":"TRANSACTION_TYPE","dataType":"string"},{"name":"TRANSACTION_SOURCE_TYPE","dataType":"string"},{"name":"TRANSACTION_ACTION","dataType":"string"},{"name":"REASON_NAME","dataType":"string"},{"name":"PO_NUM","dataType":"string"},{"name":"PO_HEADER_ID","dataType":"double"},{"name":"SO_NUM","dataType":"double"},{"name":"SO_LINE_NUM","dataType":"string"},{"name":"SO_HEADER_ID","dataType":"double"},{"name":"SO_LINE_ID","dataType":"double"},{"name":"ACCT_ENTITY","dataType":"string"},{"name":"ACCT_DEPT","dataType":"string"},{"name":"ACCT_ACCOUNT","dataType":"string"},{"name":"ACCT_PROJ","dataType":"string"},{"name":"ACCT_INTERCO","dataType":"string"},{"name":"MOVE_ORDER_NUM","dataType":"string"},{"name":"MOVE_ORDER_HEADER_ID","dataType":"double"},{"name":"WIP_ENTITY_NAME","dataType":"string"},{"name":"WIP_ENTITY_ID","dataType":"double"},{"name":"WIP_ENTITY_TYPE","dataType":"string"},{"name":"ALIAS_ENTITY","dataType":"string"},{"name":"ALIAS_DEPT","dataType":"string"},{"name":"ALIAS_ACCOUNT","dataType":"string"},{"name":"ALIAS_PROJ","dataType":"string"},{"name":"ALIAS_INTERCO","dataType":"string"},{"name":"REQ_NUM","dataType":"string"},{"name":"REQ_HEADER_ID","dataType":"double"},{"name":"CYCLE_COUNT_HEADER_NAME","dataType":"string"},{"name":"CYCLE_COUNT_HEADER_ID","dataType":"double"},{"name":"PHYSICAL_INVENTORY_NAME","dataType":"string"},{"name":"PHYSICAL_INVENTORY_ID","dataType":"double"},{"name":"PHYSICAL_INVENTORY_ORG_ID","dataType":"double"},{"name":"COST_UPDATE","dataType":"string"},{"name":"COST_UPDATE_ID","dataType":"double"},{"name":"TRX_ORG_CODE","dataType":"string"},{"name":"TRX_OPERATING_UNIT","dataType":"string"},{"name":"TRX_LEGAL_ENTITY","dataType":"string"},{"name":"TRX_SET_OF_BOOKS","dataType":"string"},{"name":"TRX_FUNC_CURRENCY_CODE","dataType":"string"},{"name":"PLANNING_ORG_CODE","dataType":"string"},{"name":"OWNING_ORG_CODE","dataType":"string"},{"name":"TRANSFER_ORG_CODE","dataType":"string"},{"name":"XFR_OWNING_ORG_CODE","dataType":"string"},{"name":"XFR_PLANNING_ORG_CODE","dataType":"string"},{"name":"ITEM_NUMBER","dataType":"string"},{"name":"ITEM_DESCRIPTION","dataType":"string"},{"name":"ITEM_TYPE","dataType":"string"},{"name":"MAKE_OR_BUY","dataType":"string"},{"name":"TECHNICAL_BUSINESS_UNIT","dataType":"string"},{"name":"PRODUCT_FAMILY","dataType":"string"},{"name":"PRODUCT_LINE","dataType":"string"},{"name":"LEAD_TIME_CATEGOEY","dataType":"string"},{"name":"FORECAST_FIELD","dataType":"string"},{"name":"COMMODITY","dataType":"string"},{"name":"PRIMARY_ORG","dataType":"string"},{"name":"SUPPLY_SOURCE","dataType":"string"},{"name":"DEMAND_SOURCE","dataType":"string"},{"name":"BACKUP_CATEGORY","dataType":"string"},{"name":"ITEM_CUSTOMER","dataType":"string"},{"name":"BCP_CODE","dataType":"string"},{"name":"ROYALTY","dataType":"string"},{"name":"PLANNING_PRODUCT_FAMILY","dataType":"string"},{"name":"PLANNING_LOW_LEVEL_CODE","dataType":"string"},{"name":"PLANNING_FAMILY_UNIQUE","dataType":"string"},{"name":"OPERATIONS_REPORTING","dataType":"string"},{"name":"SEC_REPORTING","dataType":"string"},{"name":"MATERIAL_ENTITY","dataType":"string"},{"name":"MATERIAL_DEPT","dataType":"string"},{"name":"MATERIAL_ACCT","dataType":"string"},{"name":"MATERIAL_PROJ","dataType":"string"},{"name":"MATERIAL_IC","dataType":"string"},{"name":"MATERIAL_TBD","dataType":"string"},{"name":"MATERIAL_OH_ENTITY","dataType":"string"},{"name":"MATERIAL_OH_DEPT","dataType":"string"},{"name":"MATERIAL_OH_ACCT","dataType":"string"},{"name":"MATERIAL_OH_PROJ","dataType":"string"},{"name":"MATERIAL_OH_IC","dataType":"string"},{"name":"MATERIAL_OH_TBD","dataType":"string"},{"name":"RESOURCE_ENTITY","dataType":"string"},{"name":"RESOURCE_DEPT","dataType":"string"},{"name":"RESOURCE_ACCT","dataType":"string"},{"name":"RESOURCE_PROJ","dataType":"string"},{"name":"RESOURCE_IC","dataType":"string"},{"name":"RESOURCE_TBD","dataType":"string"},{"name":"OVERHEAD_ENTITY","dataType":"string"},{"name":"OVERHEAD_DEPT","dataType":"string"},{"name":"OVERHEAD_ACCT","dataType":"string"},{"name":"OVERHEAD_PROJ","dataType":"string"},{"name":"OVERHEAD_IC","dataType":"string"},{"name":"OVERHEAD_TBD","dataType":"string"},{"name":"OS_PROCESS_ENTITY","dataType":"string"},{"name":"OS_PROCESS_DEPT","dataType":"string"},{"name":"OS_PROCESS_ACCT","dataType":"string"},{"name":"OS_PROCESS_PROJ","dataType":"string"},{"name":"OS_PROCESS_IC","dataType":"string"},{"name":"OS_PROCESS_TBD","dataType":"string"},{"name":"COST_GROUP","dataType":"string"},{"name":"COST_GROUP_TYPE","dataType":"double"},{"name":"CG_MATERIAL_ENTITY","dataType":"string"},{"name":"CG_MATERIAL_DEPT","dataType":"string"},{"name":"CG_MATERIAL_ACCT","dataType":"string"},{"name":"CG_MATERIAL_PROJ","dataType":"string"},{"name":"CG_MATERIAL_IC","dataType":"string"},{"name":"CG_MATERIAL_TBD","dataType":"string"},{"name":"CG_MATERIAL_OH_ENTITY","dataType":"string"},{"name":"CG_MATERIAL_OH_DEPT","dataType":"string"},{"name":"CG_MATERIAL_OH_ACCT","dataType":"string"},{"name":"CG_MATERIAL_OH_PROJ","dataType":"string"},{"name":"CG_MATERIAL_OH_IC","dataType":"string"},{"name":"CG_MATERIAL_OH_TBD","dataType":"string"},{"name":"CG_RESOURCE_ENTITY","dataType":"string"},{"name":"CG_RESOURCE_DEPT","dataType":"string"},{"name":"CG_RESOURCE_ACCT","dataType":"string"},{"name":"CG_RESOURCE_PROJ","dataType":"string"},{"name":"CG_RESOURCE_IC","dataType":"string"},{"name":"CG_RESOURCE_TBD","dataType":"string"},{"name":"CG_OVERHEAD_ENTITY","dataType":"string"},{"name":"CG_OVERHEAD_DEPT","dataType":"string"},{"name":"CG_OVERHEAD_ACCT","dataType":"string"},{"name":"CG_OVERHEAD_PROJ","dataType":"string"},{"name":"CG_OVERHEAD_IC","dataType":"string"},{"name":"CG_OVERHEAD_TBD","dataType":"string"},{"name":"CG_OS_PROCESS_ENTITY","dataType":"string"},{"name":"CG_OS_PROCESS_DEPT","dataType":"string"},{"name":"CG_OS_PROCESS_ACCT","dataType":"string"},{"name":"CG_OS_PROCESS_PROJ","dataType":"string"},{"name":"CG_OS_PROCESS_IC","dataType":"string"},{"name":"CG_OS_PROCESS_TBD","dataType":"string"},{"name":"CG_EXPENSE_ENTITY","dataType":"string"},{"name":"CG_EXPENSE_DEPT","dataType":"string"},{"name":"CG_EXPENSE_ACCT","dataType":"string"},{"name":"CG_EXPENSE_PROJ","dataType":"string"},{"name":"CG_EXPENSE_IC","dataType":"string"},{"name":"CG_EXPENSE_TBD","dataType":"string"},{"name":"CG_AVGCOSTV_ENTITY","dataType":"string"},{"name":"CG_AVGCOSTV_DEPT","dataType":"string"},{"name":"CG_AVGCOSTV_ACCT","dataType":"string"},{"name":"CG_AVGCOSTV_PROJ","dataType":"string"},{"name":"CG_AVGCOSTV_IC","dataType":"string"},{"name":"CG_AVGCOSTV_TBD","dataType":"string"},{"name":"XFR_COST_GROUP","dataType":"string"},{"name":"XFR_COST_GROUP_TYPE","dataType":"double"},{"name":"XFRCG_MATERIAL_ENTITY","dataType":"string"},{"name":"XFRCG_MATERIAL_DEPT","dataType":"string"},{"name":"XFRCG_MATERIAL_ACCT","dataType":"string"},{"name":"XFRCG_MATERIAL_PROJ","dataType":"string"},{"name":"XFRCG_MATERIAL_IC","dataType":"string"},{"name":"XFRCG_MATERIAL_TBD","dataType":"string"},{"name":"XFRCG_MATERIAL_OH_ENTITY","dataType":"string"},{"name":"XFRCG_MATERIAL_OH_DEPT","dataType":"string"},{"name":"XFRCG_MATERIAL_OH_ACCT","dataType":"string"},{"name":"XFRCG_MATERIAL_OH_PROJ","dataType":"string"},{"name":"XFRCG_MATERIAL_OH_IC","dataType":"string"},{"name":"XFRCG_MATERIAL_OH_TBD","dataType":"string"},{"name":"XFRCG_RESOURCE_ENTITY","dataType":"string"},{"name":"XFRCG_RESOURCE_DEPT","dataType":"string"},{"name":"XFRCG_RESOURCE_ACCT","dataType":"string"},{"name":"XFRCG_RESOURCE_PROJ","dataType":"string"},{"name":"XFRCG_RESOURCE_IC","dataType":"string"},{"name":"XFRCG_RESOURCE_TBD","dataType":"string"},{"name":"XFRCG_OVERHEAD_ENTITY","dataType":"string"},{"name":"XFRCG_OVERHEAD_DEPT","dataType":"string"},{"name":"XFRCG_OVERHEAD_ACCT","dataType":"string"},{"name":"XFRCG_OVERHEAD_PROJ","dataType":"string"},{"name":"XFRCG_OVERHEAD_IC","dataType":"string"},{"name":"XFRCG_OVERHEAD_TBD","dataType":"string"},{"name":"XFRCG_OS_PROCESS_ENTITY","dataType":"string"},{"name":"XFRCG_OS_PROCESS_DEPT","dataType":"string"},{"name":"XFRCG_OS_PROCESS_ACCT","dataType":"string"},{"name":"XFRCG_OS_PROCESS_PROJ","dataType":"string"},{"name":"XFRCG_OS_PROCESS_IC","dataType":"string"},{"name":"XFRCG_OS_PROCESS_TBD","dataType":"string"},{"name":"XFRCG_EXPENSE_ENTITY","dataType":"string"},{"name":"XFRCG_EXPENSE_DEPT","dataType":"string"},{"name":"XFRCG_EXPENSE_ACCT","dataType":"string"},{"name":"XFRCG_EXPENSE_PROJ","dataType":"string"},{"name":"XFRCG_EXPENSE_IC","dataType":"string"},{"name":"XFRCG_EXPENSE_TBD","dataType":"string"},{"name":"XFRCG_AVGCOSTV_ENTITY","dataType":"string"},{"name":"XFRCG_AVGCOSTV_DEPT","dataType":"string"},{"name":"XFRCG_AVGCOSTV_ACCT","dataType":"string"},{"name":"XFRCG_AVGCOSTV_PROJ","dataType":"string"},{"name":"XFRCG_AVGCOSTV_IC","dataType":"string"},{"name":"XFRCG_AVGCOSTV_TBD","dataType":"string"},{"name":"MTA_ENTITY","dataType":"string"},{"name":"MTA_DEPT","dataType":"string"},{"name":"MTA_ACCOUNT","dataType":"string"},{"name":"MTA_PROJECT","dataType":"string"},{"name":"MTA_INTERCO","dataType":"string"},{"name":"MTA_TRANSACTION_DATE","dataType":"dateTime"},{"name":"PRIMARY_QUANTITY","dataType":"double"},{"name":"GL_BATCH_ID","dataType":"double"},{"name":"ENTERED_DR","dataType":"double"},{"name":"ENTERED_CR","dataType":"double"},{"name":"ACCOUNTED_DR","dataType":"double"},{"name":"ACCOUNTED_CR","dataType":"double"},{"name":"ACCOUNTED_DR_USD","dataType":"double"},{"name":"ACCOUNTED_CR_USD","dataType":"double"},{"name":"ACCOUNTED_NET","dataType":"double"},{"name":"ACCOUNTED_NET_USD","dataType":"double"},{"name":"LINE_REFERENCE","dataType":"string"},{"name":"RESOURCE_CODE","dataType":"string"},{"name":"RESOURCE_DESCRIPTION","dataType":"string"},{"name":"ACTIVITY","dataType":"string"},{"name":"MTA_CURRENCY_CODE","dataType":"string"},{"name":"MTA_CURRENCY_CONVERSION_RATE","dataType":"double"},{"name":"ACTUAL_COST","dataType":"double"},{"name":"MATERIAL_COST","dataType":"double"},{"name":"MATERIAL_OH_COST","dataType":"double"},{"name":"RESOURCE_COST","dataType":"double"},{"name":"OS_PROCESSING_COST","dataType":"double"},{"name":"RESOURCE_OH_COST","dataType":"double"},{"name":"PERIOD_NAME","dataType":"string"},{"name":"FISCAL_PERIOD","dataType":"double"},{"name":"FISCAL_QUARTER","dataType":"double"},{"name":"FISCAL_YEAR","dataType":"double"},{"name":"FISCAL_WEEK","dataType":"double"},{"name":"TRANSACTION_ID","dataType":"double"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"ORGANIZATION_ID","dataType":"double"},{"name":"RMA_LINE_ID","dataType":"double"},{"name":"REPETITIVE_LINE_ID","dataType":"double"},{"name":"TRANSFER_TRANSACTION_ID","dataType":"double"},{"name":"TRANSACTION_CREATED_BY","dataType":"string"},{"name":"TRANSACTION_UPDATED_BY","dataType":"string"},{"name":"ORG_TECHNICAL_BUSINESS_UNIT","dataType":"string"},{"name":"ORG_PRODUCT_FAMILY","dataType":"string"},{"name":"ORG_PRODUCT_LINE","dataType":"string"},{"name":"ORG_FORECAST_FIELD","dataType":"string"},{"name":"CAL_MONTH","dataType":"string"},{"name":"ROW_CREATION_DATE","dataType":"dateTime"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-04-13T12:01:49.101581+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/238d817d-4dd8-4196-99ff-688e83f7a240/XXCOH_MT_MTRX_VIEW.csv?snapshot=2022-04-13T12%3A01%3A49.0463014Z"}]},{"$type":"LocalEntity","name":"XXCOH_IM_ITEM_VIEW","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"XXCOH_IM_ITEM_VIEW.csv"},"attributes":[{"name":"ITEM_ORG_KEY_ID","dataType":"string"},{"name":"ITEM_ORG_KEY_CODE","dataType":"string"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"ORGANIZATION_ID","dataType":"double"},{"name":"LAST_UPDATE_DATE","dataType":"dateTime"},{"name":"CREATION_DATE","dataType":"dateTime"},{"name":"ENABLED_FLAG","dataType":"string"},{"name":"DESCRIPTION","dataType":"string"},{"name":"PURCHASING_ITEM_FLAG","dataType":"string"},{"name":"SHIPPABLE_ITEM_FLAG","dataType":"string"},{"name":"CUSTOMER_ORDER_FLAG","dataType":"string"},{"name":"INTERNAL_ORDER_FLAG","dataType":"string"},{"name":"SERVICE_ITEM_FLAG","dataType":"string"},{"name":"INVENTORY_ITEM_FLAG","dataType":"string"},{"name":"ENG_ITEM_FLAG","dataType":"string"},{"name":"INVENTORY_ASSET_FLAG","dataType":"string"},{"name":"PURCHASING_ENABLED_FLAG","dataType":"string"},{"name":"CUSTOMER_ORDER_ENABLED_FLAG","dataType":"string"},{"name":"INTERNAL_ORDER_ENABLED_FLAG","dataType":"string"},{"name":"SO_TRANSACTIONS_FLAG","dataType":"string"},{"name":"MTL_TRANSACTIONS_ENABLED_FLAG","dataType":"string"},{"name":"STOCK_ENABLED_FLAG","dataType":"string"},{"name":"BOM_ENABLED_FLAG","dataType":"string"},{"name":"BUILD_IN_WIP_FLAG","dataType":"string"},{"name":"REVISION_QTY_CONTROL_CODE","dataType":"double"},{"name":"ITEM_CATALOG_GROUP_ID","dataType":"double"},{"name":"CATALOG_STATUS_FLAG","dataType":"string"},{"name":"RETURNABLE_FLAG","dataType":"string"},{"name":"DEFAULT_SHIPPING_ORG","dataType":"double"},{"name":"COLLATERAL_FLAG","dataType":"string"},{"name":"TAXABLE_FLAG","dataType":"string"},{"name":"QTY_RCV_EXCEPTION_CODE","dataType":"string"},{"name":"ALLOW_ITEM_DESC_UPDATE_FLAG","dataType":"string"},{"name":"INSPECTION_REQUIRED_FLAG","dataType":"string"},{"name":"RECEIPT_REQUIRED_FLAG","dataType":"string"},{"name":"MARKET_PRICE","dataType":"double"},{"name":"RFQ_REQUIRED_FLAG","dataType":"string"},{"name":"QTY_RCV_TOLERANCE","dataType":"double"},{"name":"LIST_PRICE_PER_UNIT","dataType":"double"},{"name":"PRICE_TOLERANCE_PERCENT","dataType":"double"},{"name":"UNIT_OF_ISSUE","dataType":"string"},{"name":"ENFORCE_SHIP_TO_LOCATION_CODE","dataType":"string"},{"name":"ALLOW_EXPRESS_DELIVERY_FLAG","dataType":"string"},{"name":"DAYS_EARLY_RECEIPT_ALLOWED","dataType":"double"},{"name":"DAYS_LATE_RECEIPT_ALLOWED","dataType":"double"},{"name":"RECEIPT_DAYS_EXCEPTION_CODE","dataType":"string"},{"name":"RECEIVING_ROUTING_ID","dataType":"double"},{"name":"RECEIVE_CLOSE_TOLERANCE","dataType":"double"},{"name":"AUTO_LOT_ALPHA_PREFIX","dataType":"string"},{"name":"START_AUTO_LOT_NUMBER","dataType":"string"},{"name":"LOT_CONTROL_CODE","dataType":"double"},{"name":"SHELF_LIFE_CODE","dataType":"double"},{"name":"SHELF_LIFE_DAYS","dataType":"double"},{"name":"SERIAL_NUMBER_CONTROL_CODE","dataType":"double"},{"name":"START_AUTO_SERIAL_NUMBER","dataType":"string"},{"name":"AUTO_SERIAL_ALPHA_PREFIX","dataType":"string"},{"name":"SOURCE_TYPE","dataType":"double"},{"name":"SOURCE_ORGANIZATION_ID","dataType":"double"},{"name":"SOURCE_SUBINVENTORY","dataType":"string"},{"name":"EXPENSE_ACCOUNT","dataType":"double"},{"name":"RESTRICT_SUBINVENTORIES_CODE","dataType":"double"},{"name":"UNIT_WEIGHT","dataType":"double"},{"name":"WEIGHT_UOM_CODE","dataType":"string"},{"name":"VOLUME_UOM_CODE","dataType":"string"},{"name":"UNIT_VOLUME","dataType":"double"},{"name":"RESTRICT_LOCATORS_CODE","dataType":"double"},{"name":"LOCATION_CONTROL_CODE","dataType":"double"},{"name":"SHRINKAGE_RATE","dataType":"double"},{"name":"ACCEPTABLE_EARLY_DAYS","dataType":"double"},{"name":"PLANNING_TIME_FENCE_CODE","dataType":"double"},{"name":"DEMAND_TIME_FENCE_CODE","dataType":"double"},{"name":"LEAD_TIME_LOT_SIZE","dataType":"double"},{"name":"STD_LOT_SIZE","dataType":"double"},{"name":"CUM_MANUFACTURING_LEAD_TIME","dataType":"double"},{"name":"OVERRUN_PERCENTAGE","dataType":"double"},{"name":"MRP_CALCULATE_ATP_FLAG","dataType":"string"},{"name":"ACCEPTABLE_RATE_INCREASE","dataType":"double"},{"name":"ACCEPTABLE_RATE_DECREASE","dataType":"double"},{"name":"CUMULATIVE_TOTAL_LEAD_TIME","dataType":"double"},{"name":"PLANNING_TIME_FENCE_DAYS","dataType":"double"},{"name":"DEMAND_TIME_FENCE_DAYS","dataType":"double"},{"name":"END_ASSEMBLY_PEGGING_FLAG","dataType":"string"},{"name":"REPETITIVE_PLANNING_FLAG","dataType":"string"},{"name":"PLANNING_EXCEPTION_SET","dataType":"string"},{"name":"BOM_ITEM_TYPE","dataType":"double"},{"name":"PICK_COMPONENTS_FLAG","dataType":"string"},{"name":"REPLENISH_TO_ORDER_FLAG","dataType":"string"},{"name":"BASE_ITEM_ID","dataType":"double"},{"name":"ATP_COMPONENTS_FLAG","dataType":"string"},{"name":"ATP_FLAG","dataType":"string"},{"name":"FIXED_LEAD_TIME","dataType":"double"},{"name":"VARIABLE_LEAD_TIME","dataType":"double"},{"name":"WIP_SUPPLY_LOCATOR_ID","dataType":"double"},{"name":"WIP_SUPPLY_TYPE","dataType":"double"},{"name":"WIP_SUPPLY_SUBINVENTORY","dataType":"string"},{"name":"PRIMARY_UOM_CODE","dataType":"string"},{"name":"PRIMARY_UNIT_OF_MEASURE","dataType":"string"},{"name":"ALLOWED_UNITS_LOOKUP_CODE","dataType":"double"},{"name":"COST_OF_SALES_ACCOUNT","dataType":"double"},{"name":"SALES_ACCOUNT","dataType":"double"},{"name":"DEFAULT_INCLUDE_IN_ROLLUP_FLAG","dataType":"string"},{"name":"INVENTORY_ITEM_STATUS_CODE","dataType":"string"},{"name":"INVENTORY_PLANNING_CODE","dataType":"double"},{"name":"PLANNER_CODE","dataType":"string"},{"name":"PLANNING_MAKE_BUY_CODE","dataType":"double"},{"name":"FIXED_LOT_MULTIPLIER","dataType":"double"},{"name":"ROUNDING_CONTROL_TYPE","dataType":"double"},{"name":"POSTPROCESSING_LEAD_TIME","dataType":"double"},{"name":"PREPROCESSING_LEAD_TIME","dataType":"double"},{"name":"FULL_LEAD_TIME","dataType":"double"},{"name":"ORDER_COST","dataType":"double"},{"name":"MRP_SAFETY_STOCK_PERCENT","dataType":"double"},{"name":"MRP_SAFETY_STOCK_CODE","dataType":"double"},{"name":"MIN_MINMAX_QUANTITY","dataType":"double"},{"name":"MAX_MINMAX_QUANTITY","dataType":"double"},{"name":"MINIMUM_ORDER_QUANTITY","dataType":"double"},{"name":"FIXED_ORDER_QUANTITY","dataType":"double"},{"name":"FIXED_DAYS_SUPPLY","dataType":"double"},{"name":"MAXIMUM_ORDER_QUANTITY","dataType":"double"},{"name":"ATP_RULE_ID","dataType":"double"},{"name":"RESERVABLE_TYPE","dataType":"double"},{"name":"POSITIVE_MEASUREMENT_ERROR","dataType":"double"},{"name":"NEGATIVE_MEASUREMENT_ERROR","dataType":"double"},{"name":"VENDOR_WARRANTY_FLAG","dataType":"string"},{"name":"SERVICEABLE_COMPONENT_FLAG","dataType":"string"},{"name":"SERVICEABLE_PRODUCT_FLAG","dataType":"string"},{"name":"PAYMENT_TERMS_ID","dataType":"double"},{"name":"PREVENTIVE_MAINTENANCE_FLAG","dataType":"string"},{"name":"TIME_BILLABLE_FLAG","dataType":"string"},{"name":"MATERIAL_BILLABLE_FLAG","dataType":"string"},{"name":"EXPENSE_BILLABLE_FLAG","dataType":"string"},{"name":"PRORATE_SERVICE_FLAG","dataType":"string"},{"name":"COVERAGE_SCHEDULE_ID","dataType":"double"},{"name":"SERVICE_DURATION_PERIOD_CODE","dataType":"string"},{"name":"SERVICE_DURATION","dataType":"double"},{"name":"INVOICEABLE_ITEM_FLAG","dataType":"string"},{"name":"INVOICE_ENABLED_FLAG","dataType":"string"},{"name":"MUST_USE_APPROVED_VENDOR_FLAG","dataType":"string"},{"name":"REQUEST_ID","dataType":"double"},{"name":"PROGRAM_APPLICATION_ID","dataType":"double"},{"name":"PROGRAM_ID","dataType":"double"},{"name":"PROGRAM_UPDATE_DATE","dataType":"dateTime"},{"name":"OUTSIDE_OPERATION_FLAG","dataType":"string"},{"name":"OUTSIDE_OPERATION_UOM_TYPE","dataType":"string"},{"name":"SAFETY_STOCK_BUCKET_DAYS","dataType":"double"},{"name":"AUTO_REDUCE_MPS","dataType":"double"},{"name":"COSTING_ENABLED_FLAG","dataType":"string"},{"name":"AUTO_CREATED_CONFIG_FLAG","dataType":"string"},{"name":"CYCLE_COUNT_ENABLED_FLAG","dataType":"string"},{"name":"ITEM_TYPE","dataType":"string"},{"name":"SHIP_MODEL_COMPLETE_FLAG","dataType":"string"},{"name":"MRP_PLANNING_CODE","dataType":"double"},{"name":"RETURN_INSPECTION_REQUIREMENT","dataType":"double"},{"name":"ATO_FORECAST_CONTROL","dataType":"double"},{"name":"RELEASE_TIME_FENCE_CODE","dataType":"double"},{"name":"RELEASE_TIME_FENCE_DAYS","dataType":"double"},{"name":"CONTAINER_ITEM_FLAG","dataType":"string"},{"name":"VEHICLE_ITEM_FLAG","dataType":"string"},{"name":"PRODUCT_FAMILY_ITEM_ID","dataType":"double"},{"name":"PURCHASING_TAX_CODE","dataType":"string"},{"name":"OVERCOMPLETION_TOLERANCE_TYPE","dataType":"double"},{"name":"OVERCOMPLETION_TOLERANCE_VALUE","dataType":"double"},{"name":"EFFECTIVITY_CONTROL","dataType":"double"},{"name":"CHECK_SHORTAGES_FLAG","dataType":"string"},{"name":"EQUIPMENT_TYPE","dataType":"double"},{"name":"DEFECT_TRACKING_ON_FLAG","dataType":"string"},{"name":"EVENT_FLAG","dataType":"string"},{"name":"ELECTRONIC_FLAG","dataType":"string"},{"name":"DOWNLOADABLE_FLAG","dataType":"string"},{"name":"COMMS_NL_TRACKABLE_FLAG","dataType":"string"},{"name":"ASSET_CREATION_CODE","dataType":"string"},{"name":"ORDERABLE_ON_WEB_FLAG","dataType":"string"},{"name":"BACK_ORDERABLE_FLAG","dataType":"string"},{"name":"WEB_STATUS","dataType":"string"},{"name":"INDIVISIBLE_FLAG","dataType":"string"},{"name":"BULK_PICKED_FLAG","dataType":"string"},{"name":"LOT_STATUS_ENABLED","dataType":"string"},{"name":"SERIAL_STATUS_ENABLED","dataType":"string"},{"name":"DEFAULT_SERIAL_STATUS_ID","dataType":"double"},{"name":"LOT_SPLIT_ENABLED","dataType":"string"},{"name":"LOT_MERGE_ENABLED","dataType":"string"},{"name":"FINANCING_ALLOWED_FLAG","dataType":"string"},{"name":"EAM_ACT_NOTIFICATION_FLAG","dataType":"string"},{"name":"DUAL_UOM_CONTROL","dataType":"double"},{"name":"DUAL_UOM_DEVIATION_HIGH","dataType":"double"},{"name":"DUAL_UOM_DEVIATION_LOW","dataType":"double"},{"name":"CONTRACT_ITEM_TYPE_CODE","dataType":"string"},{"name":"SERV_REQ_ENABLED_CODE","dataType":"string"},{"name":"SERV_BILLING_ENABLED_FLAG","dataType":"string"},{"name":"PLANNED_INV_POINT_FLAG","dataType":"string"},{"name":"LOT_TRANSLATE_ENABLED","dataType":"string"},{"name":"DEFAULT_SO_SOURCE_TYPE","dataType":"string"},{"name":"CREATE_SUPPLY_FLAG","dataType":"string"},{"name":"LOT_SUBSTITUTION_ENABLED","dataType":"string"},{"name":"OBJECT_VERSION_NUMBER","dataType":"double"},{"name":"TRACKING_QUANTITY_IND","dataType":"string"},{"name":"ONT_PRICING_QTY_SOURCE","dataType":"string"},{"name":"VMI_MINIMUM_UNITS","dataType":"double"},{"name":"VMI_MAXIMUM_UNITS","dataType":"double"},{"name":"SO_AUTHORIZATION_FLAG","dataType":"double"},{"name":"CONSIGNED_FLAG","dataType":"double"},{"name":"ASN_AUTOEXPIRE_FLAG","dataType":"double"},{"name":"VMI_FORECAST_TYPE","dataType":"double"},{"name":"EXCLUDE_FROM_BUDGET_FLAG","dataType":"double"},{"name":"DRP_PLANNED_FLAG","dataType":"double"},{"name":"CRITICAL_COMPONENT_FLAG","dataType":"double"},{"name":"CONTINOUS_TRANSFER","dataType":"double"},{"name":"CONVERGENCE","dataType":"double"},{"name":"DIVERGENCE","dataType":"double"},{"name":"CHILD_LOT_FLAG","dataType":"string"},{"name":"CHILD_LOT_VALIDATION_FLAG","dataType":"string"},{"name":"COPY_LOT_ATTRIBUTE_FLAG","dataType":"string"},{"name":"GRADE_CONTROL_FLAG","dataType":"string"},{"name":"HAZARDOUS_MATERIAL_FLAG","dataType":"string"},{"name":"LOT_DIVISIBLE_FLAG","dataType":"string"},{"name":"PROCESS_COSTING_ENABLED_FLAG","dataType":"string"},{"name":"PROCESS_EXECUTION_ENABLED_FLAG","dataType":"string"},{"name":"PROCESS_QUALITY_ENABLED_FLAG","dataType":"string"},{"name":"PROCESS_SUPPLY_LOCATOR_ID","dataType":"double"},{"name":"PROCESS_SUPPLY_SUBINVENTORY","dataType":"string"},{"name":"RECIPE_ENABLED_FLAG","dataType":"string"},{"name":"PREPOSITION_POINT","dataType":"string"},{"name":"REPAIR_PROGRAM","dataType":"double"},{"name":"OUTSOURCED_ASSEMBLY","dataType":"double"},{"name":"GDSN_OUTBOUND_ENABLED_FLAG","dataType":"string"},{"name":"SERIAL_TAGGING_FLAG","dataType":"string"},{"name":"IB_ITEM_TRACKING_LEVEL","dataType":"string"},{"name":"MCC_CONTROL_CODE","dataType":"double"},{"name":"START_DATE_ACTIVE","dataType":"dateTime"},{"name":"END_DATE_ACTIVE","dataType":"dateTime"},{"name":"ORGANIZATION_CODE","dataType":"string"},{"name":"ITEM_DESCRIPTION","dataType":"string"},{"name":"USER_ITEM_TYPE","dataType":"string"},{"name":"BOM_ITEM_TYPE_DESCRIPTION","dataType":"string"},{"name":"COST_SOURCE_TYPE","dataType":"string"},{"name":"DEFAULT_BUYER","dataType":"string"},{"name":"ITEM_CATALOG_GROUP","dataType":"string"},{"name":"DEFAULT_RECV_SUBINVENTORY","dataType":"string"},{"name":"END_ASSEMBLY_PEGGING","dataType":"string"},{"name":"EFFECTIVITY_DATE","dataType":"dateTime"},{"name":"REVISION","dataType":"string"},{"name":"POWERBI_REFRESH_PARTITION","dataType":"dateTime"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-04-13T09:36:42.7042478+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/238d817d-4dd8-4196-99ff-688e83f7a240/XXCOH_IM_ITEM_VIEW.csv?snapshot=2022-04-13T09%3A36%3A42.6906139Z"}]},{"$type":"LocalEntity","name":"XXCOH_IM_CATEGORY_VIEW","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"XXCOH_IM_CATEGORY_VIEW.csv"},"attributes":[{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"ORGANIZATION_ID","dataType":"double"},{"name":"ITEM_NUMBER","dataType":"string"},{"name":"DESCRIPTION","dataType":"string"},{"name":"OPROD_TBU","dataType":"string"},{"name":"ORGANIZATION_CODE","dataType":"string"},{"name":"ITEM_CREATION_DATE","dataType":"dateTime"},{"name":"PROD_TBU","dataType":"string"},{"name":"PROD_FAMILY","dataType":"string"},{"name":"PROD_LINE","dataType":"string"},{"name":"PROD_FORECAST_FIELD","dataType":"string"},{"name":"OPROD_FAMILY","dataType":"string"},{"name":"OPROD_LINE","dataType":"string"},{"name":"OPROD_FORECAST_FIELD","dataType":"string"},{"name":"IT_ITEM_TYPE_MEANING","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-04-13T09:36:26.5531898+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/238d817d-4dd8-4196-99ff-688e83f7a240/XXCOH_IM_CATEGORY_VIEW.csv?snapshot=2022-04-13T09%3A36%3A26.5327426Z"}]},{"$type":"LocalEntity","name":"XXREP_MTL_SYSTEM_ITEMS_V","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"XXREP_MTL_SYSTEM_ITEMS_V.csv"},"attributes":[{"name":"ITEM_ORG_KEY_ID","dataType":"string"},{"name":"ITEM_ORG_KEY_CODE","dataType":"string"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"ORGANIZATION_ID","dataType":"double"},{"name":"LAST_UPDATE_DATE","dataType":"dateTime"},{"name":"LAST_UPDATED_BY","dataType":"double"},{"name":"CREATION_DATE","dataType":"dateTime"},{"name":"CREATED_BY","dataType":"double"},{"name":"LAST_UPDATE_LOGIN","dataType":"double"},{"name":"SUMMARY_FLAG","dataType":"string"},{"name":"ENABLED_FLAG","dataType":"string"},{"name":"DESCRIPTION","dataType":"string"},{"name":"BUYER_ID","dataType":"double"},{"name":"SEGMENT1","dataType":"string"},{"name":"ATTRIBUTE_CATEGORY","dataType":"string"},{"name":"ATTRIBUTE13","dataType":"string"},{"name":"ATTRIBUTE14","dataType":"string"},{"name":"ATTRIBUTE15","dataType":"string"},{"name":"PURCHASING_ITEM_FLAG","dataType":"string"},{"name":"SHIPPABLE_ITEM_FLAG","dataType":"string"},{"name":"CUSTOMER_ORDER_FLAG","dataType":"string"},{"name":"INTERNAL_ORDER_FLAG","dataType":"string"},{"name":"SERVICE_ITEM_FLAG","dataType":"string"},{"name":"INVENTORY_ITEM_FLAG","dataType":"string"},{"name":"ENG_ITEM_FLAG","dataType":"string"},{"name":"INVENTORY_ASSET_FLAG","dataType":"string"},{"name":"PURCHASING_ENABLED_FLAG","dataType":"string"},{"name":"CUSTOMER_ORDER_ENABLED_FLAG","dataType":"string"},{"name":"INTERNAL_ORDER_ENABLED_FLAG","dataType":"string"},{"name":"SO_TRANSACTIONS_FLAG","dataType":"string"},{"name":"MTL_TRANSACTIONS_ENABLED_FLAG","dataType":"string"},{"name":"STOCK_ENABLED_FLAG","dataType":"string"},{"name":"BOM_ENABLED_FLAG","dataType":"string"},{"name":"BUILD_IN_WIP_FLAG","dataType":"string"},{"name":"REVISION_QTY_CONTROL_CODE","dataType":"double"},{"name":"ITEM_CATALOG_GROUP_ID","dataType":"double"},{"name":"CATALOG_STATUS_FLAG","dataType":"string"},{"name":"RETURNABLE_FLAG","dataType":"string"},{"name":"DEFAULT_SHIPPING_ORG","dataType":"double"},{"name":"COLLATERAL_FLAG","dataType":"string"},{"name":"TAXABLE_FLAG","dataType":"string"},{"name":"QTY_RCV_EXCEPTION_CODE","dataType":"string"},{"name":"ALLOW_ITEM_DESC_UPDATE_FLAG","dataType":"string"},{"name":"INSPECTION_REQUIRED_FLAG","dataType":"string"},{"name":"RECEIPT_REQUIRED_FLAG","dataType":"string"},{"name":"MARKET_PRICE","dataType":"double"},{"name":"RFQ_REQUIRED_FLAG","dataType":"string"},{"name":"QTY_RCV_TOLERANCE","dataType":"double"},{"name":"LIST_PRICE_PER_UNIT","dataType":"double"},{"name":"PRICE_TOLERANCE_PERCENT","dataType":"double"},{"name":"UNIT_OF_ISSUE","dataType":"string"},{"name":"ENFORCE_SHIP_TO_LOCATION_CODE","dataType":"string"},{"name":"ALLOW_EXPRESS_DELIVERY_FLAG","dataType":"string"},{"name":"DAYS_EARLY_RECEIPT_ALLOWED","dataType":"double"},{"name":"DAYS_LATE_RECEIPT_ALLOWED","dataType":"double"},{"name":"RECEIPT_DAYS_EXCEPTION_CODE","dataType":"string"},{"name":"RECEIVING_ROUTING_ID","dataType":"double"},{"name":"RECEIVE_CLOSE_TOLERANCE","dataType":"double"},{"name":"AUTO_LOT_ALPHA_PREFIX","dataType":"string"},{"name":"START_AUTO_LOT_NUMBER","dataType":"string"},{"name":"LOT_CONTROL_CODE","dataType":"double"},{"name":"SHELF_LIFE_CODE","dataType":"double"},{"name":"SHELF_LIFE_DAYS","dataType":"double"},{"name":"SERIAL_NUMBER_CONTROL_CODE","dataType":"double"},{"name":"START_AUTO_SERIAL_NUMBER","dataType":"string"},{"name":"AUTO_SERIAL_ALPHA_PREFIX","dataType":"string"},{"name":"SOURCE_TYPE","dataType":"double"},{"name":"SOURCE_ORGANIZATION_ID","dataType":"double"},{"name":"SOURCE_SUBINVENTORY","dataType":"string"},{"name":"EXPENSE_ACCOUNT","dataType":"double"},{"name":"RESTRICT_SUBINVENTORIES_CODE","dataType":"double"},{"name":"UNIT_WEIGHT","dataType":"double"},{"name":"WEIGHT_UOM_CODE","dataType":"string"},{"name":"VOLUME_UOM_CODE","dataType":"string"},{"name":"UNIT_VOLUME","dataType":"double"},{"name":"RESTRICT_LOCATORS_CODE","dataType":"double"},{"name":"LOCATION_CONTROL_CODE","dataType":"double"},{"name":"SHRINKAGE_RATE","dataType":"double"},{"name":"ACCEPTABLE_EARLY_DAYS","dataType":"double"},{"name":"PLANNING_TIME_FENCE_CODE","dataType":"double"},{"name":"DEMAND_TIME_FENCE_CODE","dataType":"double"},{"name":"LEAD_TIME_LOT_SIZE","dataType":"double"},{"name":"STD_LOT_SIZE","dataType":"double"},{"name":"CUM_MANUFACTURING_LEAD_TIME","dataType":"double"},{"name":"OVERRUN_PERCENTAGE","dataType":"double"},{"name":"MRP_CALCULATE_ATP_FLAG","dataType":"string"},{"name":"ACCEPTABLE_RATE_INCREASE","dataType":"double"},{"name":"ACCEPTABLE_RATE_DECREASE","dataType":"double"},{"name":"CUMULATIVE_TOTAL_LEAD_TIME","dataType":"double"},{"name":"PLANNING_TIME_FENCE_DAYS","dataType":"double"},{"name":"DEMAND_TIME_FENCE_DAYS","dataType":"double"},{"name":"END_ASSEMBLY_PEGGING_FLAG","dataType":"string"},{"name":"REPETITIVE_PLANNING_FLAG","dataType":"string"},{"name":"PLANNING_EXCEPTION_SET","dataType":"string"},{"name":"BOM_ITEM_TYPE","dataType":"double"},{"name":"PICK_COMPONENTS_FLAG","dataType":"string"},{"name":"REPLENISH_TO_ORDER_FLAG","dataType":"string"},{"name":"BASE_ITEM_ID","dataType":"double"},{"name":"ATP_COMPONENTS_FLAG","dataType":"string"},{"name":"ATP_FLAG","dataType":"string"},{"name":"FIXED_LEAD_TIME","dataType":"double"},{"name":"VARIABLE_LEAD_TIME","dataType":"double"},{"name":"WIP_SUPPLY_LOCATOR_ID","dataType":"double"},{"name":"WIP_SUPPLY_TYPE","dataType":"double"},{"name":"WIP_SUPPLY_SUBINVENTORY","dataType":"string"},{"name":"PRIMARY_UOM_CODE","dataType":"string"},{"name":"PRIMARY_UNIT_OF_MEASURE","dataType":"string"},{"name":"ALLOWED_UNITS_LOOKUP_CODE","dataType":"double"},{"name":"COST_OF_SALES_ACCOUNT","dataType":"double"},{"name":"SALES_ACCOUNT","dataType":"double"},{"name":"DEFAULT_INCLUDE_IN_ROLLUP_FLAG","dataType":"string"},{"name":"INVENTORY_ITEM_STATUS_CODE","dataType":"string"},{"name":"INVENTORY_PLANNING_CODE","dataType":"double"},{"name":"PLANNER_CODE","dataType":"string"},{"name":"PLANNING_MAKE_BUY_CODE","dataType":"double"},{"name":"FIXED_LOT_MULTIPLIER","dataType":"double"},{"name":"ROUNDING_CONTROL_TYPE","dataType":"double"},{"name":"POSTPROCESSING_LEAD_TIME","dataType":"double"},{"name":"PREPROCESSING_LEAD_TIME","dataType":"double"},{"name":"FULL_LEAD_TIME","dataType":"double"},{"name":"ORDER_COST","dataType":"double"},{"name":"MRP_SAFETY_STOCK_PERCENT","dataType":"double"},{"name":"MRP_SAFETY_STOCK_CODE","dataType":"double"},{"name":"MIN_MINMAX_QUANTITY","dataType":"double"},{"name":"MAX_MINMAX_QUANTITY","dataType":"double"},{"name":"MINIMUM_ORDER_QUANTITY","dataType":"double"},{"name":"FIXED_ORDER_QUANTITY","dataType":"double"},{"name":"FIXED_DAYS_SUPPLY","dataType":"double"},{"name":"MAXIMUM_ORDER_QUANTITY","dataType":"double"},{"name":"ATP_RULE_ID","dataType":"double"},{"name":"RESERVABLE_TYPE","dataType":"double"},{"name":"POSITIVE_MEASUREMENT_ERROR","dataType":"double"},{"name":"NEGATIVE_MEASUREMENT_ERROR","dataType":"double"},{"name":"VENDOR_WARRANTY_FLAG","dataType":"string"},{"name":"SERVICEABLE_COMPONENT_FLAG","dataType":"string"},{"name":"SERVICEABLE_PRODUCT_FLAG","dataType":"string"},{"name":"PAYMENT_TERMS_ID","dataType":"double"},{"name":"PREVENTIVE_MAINTENANCE_FLAG","dataType":"string"},{"name":"TIME_BILLABLE_FLAG","dataType":"string"},{"name":"MATERIAL_BILLABLE_FLAG","dataType":"string"},{"name":"EXPENSE_BILLABLE_FLAG","dataType":"string"},{"name":"PRORATE_SERVICE_FLAG","dataType":"string"},{"name":"COVERAGE_SCHEDULE_ID","dataType":"double"},{"name":"SERVICE_DURATION_PERIOD_CODE","dataType":"string"},{"name":"SERVICE_DURATION","dataType":"double"},{"name":"INVOICEABLE_ITEM_FLAG","dataType":"string"},{"name":"INVOICE_ENABLED_FLAG","dataType":"string"},{"name":"MUST_USE_APPROVED_VENDOR_FLAG","dataType":"string"},{"name":"REQUEST_ID","dataType":"double"},{"name":"PROGRAM_APPLICATION_ID","dataType":"double"},{"name":"PROGRAM_ID","dataType":"double"},{"name":"PROGRAM_UPDATE_DATE","dataType":"dateTime"},{"name":"OUTSIDE_OPERATION_FLAG","dataType":"string"},{"name":"OUTSIDE_OPERATION_UOM_TYPE","dataType":"string"},{"name":"SAFETY_STOCK_BUCKET_DAYS","dataType":"double"},{"name":"AUTO_REDUCE_MPS","dataType":"double"},{"name":"COSTING_ENABLED_FLAG","dataType":"string"},{"name":"AUTO_CREATED_CONFIG_FLAG","dataType":"string"},{"name":"CYCLE_COUNT_ENABLED_FLAG","dataType":"string"},{"name":"ITEM_TYPE","dataType":"string"},{"name":"SHIP_MODEL_COMPLETE_FLAG","dataType":"string"},{"name":"MRP_PLANNING_CODE","dataType":"double"},{"name":"RETURN_INSPECTION_REQUIREMENT","dataType":"double"},{"name":"ATO_FORECAST_CONTROL","dataType":"double"},{"name":"RELEASE_TIME_FENCE_CODE","dataType":"double"},{"name":"RELEASE_TIME_FENCE_DAYS","dataType":"double"},{"name":"CONTAINER_ITEM_FLAG","dataType":"string"},{"name":"VEHICLE_ITEM_FLAG","dataType":"string"},{"name":"PRODUCT_FAMILY_ITEM_ID","dataType":"double"},{"name":"PURCHASING_TAX_CODE","dataType":"string"},{"name":"OVERCOMPLETION_TOLERANCE_TYPE","dataType":"double"},{"name":"OVERCOMPLETION_TOLERANCE_VALUE","dataType":"double"},{"name":"EFFECTIVITY_CONTROL","dataType":"double"},{"name":"CHECK_SHORTAGES_FLAG","dataType":"string"},{"name":"EQUIPMENT_TYPE","dataType":"double"},{"name":"DEFECT_TRACKING_ON_FLAG","dataType":"string"},{"name":"EVENT_FLAG","dataType":"string"},{"name":"ELECTRONIC_FLAG","dataType":"string"},{"name":"DOWNLOADABLE_FLAG","dataType":"string"},{"name":"COMMS_NL_TRACKABLE_FLAG","dataType":"string"},{"name":"ASSET_CREATION_CODE","dataType":"string"},{"name":"ORDERABLE_ON_WEB_FLAG","dataType":"string"},{"name":"BACK_ORDERABLE_FLAG","dataType":"string"},{"name":"WEB_STATUS","dataType":"string"},{"name":"INDIVISIBLE_FLAG","dataType":"string"},{"name":"BULK_PICKED_FLAG","dataType":"string"},{"name":"LOT_STATUS_ENABLED","dataType":"string"},{"name":"SERIAL_STATUS_ENABLED","dataType":"string"},{"name":"DEFAULT_SERIAL_STATUS_ID","dataType":"double"},{"name":"LOT_SPLIT_ENABLED","dataType":"string"},{"name":"LOT_MERGE_ENABLED","dataType":"string"},{"name":"FINANCING_ALLOWED_FLAG","dataType":"string"},{"name":"EAM_ACT_NOTIFICATION_FLAG","dataType":"string"},{"name":"DUAL_UOM_CONTROL","dataType":"double"},{"name":"DUAL_UOM_DEVIATION_HIGH","dataType":"double"},{"name":"DUAL_UOM_DEVIATION_LOW","dataType":"double"},{"name":"CONTRACT_ITEM_TYPE_CODE","dataType":"string"},{"name":"SERV_REQ_ENABLED_CODE","dataType":"string"},{"name":"SERV_BILLING_ENABLED_FLAG","dataType":"string"},{"name":"PLANNED_INV_POINT_FLAG","dataType":"string"},{"name":"LOT_TRANSLATE_ENABLED","dataType":"string"},{"name":"DEFAULT_SO_SOURCE_TYPE","dataType":"string"},{"name":"CREATE_SUPPLY_FLAG","dataType":"string"},{"name":"LOT_SUBSTITUTION_ENABLED","dataType":"string"},{"name":"OBJECT_VERSION_NUMBER","dataType":"double"},{"name":"TRACKING_QUANTITY_IND","dataType":"string"},{"name":"ONT_PRICING_QTY_SOURCE","dataType":"string"},{"name":"VMI_MINIMUM_UNITS","dataType":"double"},{"name":"VMI_MAXIMUM_UNITS","dataType":"double"},{"name":"SO_AUTHORIZATION_FLAG","dataType":"double"},{"name":"CONSIGNED_FLAG","dataType":"double"},{"name":"ASN_AUTOEXPIRE_FLAG","dataType":"double"},{"name":"VMI_FORECAST_TYPE","dataType":"double"},{"name":"EXCLUDE_FROM_BUDGET_FLAG","dataType":"double"},{"name":"DRP_PLANNED_FLAG","dataType":"double"},{"name":"CRITICAL_COMPONENT_FLAG","dataType":"double"},{"name":"CONTINOUS_TRANSFER","dataType":"double"},{"name":"CONVERGENCE","dataType":"double"},{"name":"DIVERGENCE","dataType":"double"},{"name":"CHILD_LOT_FLAG","dataType":"string"},{"name":"CHILD_LOT_VALIDATION_FLAG","dataType":"string"},{"name":"COPY_LOT_ATTRIBUTE_FLAG","dataType":"string"},{"name":"GRADE_CONTROL_FLAG","dataType":"string"},{"name":"HAZARDOUS_MATERIAL_FLAG","dataType":"string"},{"name":"LOT_DIVISIBLE_FLAG","dataType":"string"},{"name":"PROCESS_COSTING_ENABLED_FLAG","dataType":"string"},{"name":"PROCESS_EXECUTION_ENABLED_FLAG","dataType":"string"},{"name":"PROCESS_QUALITY_ENABLED_FLAG","dataType":"string"},{"name":"PROCESS_SUPPLY_LOCATOR_ID","dataType":"double"},{"name":"PROCESS_SUPPLY_SUBINVENTORY","dataType":"string"},{"name":"RECIPE_ENABLED_FLAG","dataType":"string"},{"name":"PREPOSITION_POINT","dataType":"string"},{"name":"REPAIR_PROGRAM","dataType":"double"},{"name":"OUTSOURCED_ASSEMBLY","dataType":"double"},{"name":"GDSN_OUTBOUND_ENABLED_FLAG","dataType":"string"},{"name":"SERIAL_TAGGING_FLAG","dataType":"string"},{"name":"IB_ITEM_TRACKING_LEVEL","dataType":"string"},{"name":"MCC_CONTROL_CODE","dataType":"double"},{"name":"START_DATE_ACTIVE","dataType":"dateTime"},{"name":"END_DATE_ACTIVE","dataType":"dateTime"},{"name":"ORGANIZATION_CODE","dataType":"string"},{"name":"ITEM_DESCRIPTION","dataType":"string"},{"name":"USER_ITEM_TYPE","dataType":"string"},{"name":"BOM_ITEM_TYPE_DESCRIPTION","dataType":"string"},{"name":"COST_SOURCE_TYPE","dataType":"string"},{"name":"DEFAULT_BUYER","dataType":"string"},{"name":"ITEM_CATALOG_GROUP","dataType":"string"},{"name":"DEFAULT_RECV_SUBINVENTORY","dataType":"string"},{"name":"END_ASSEMBLY_PEGGING","dataType":"string"},{"name":"EFFECTIVITY_DATE","dataType":"dateTime"},{"name":"REVISION","dataType":"string"},{"name":"POWERBI_REFRESH_PARTITION","dataType":"dateTime"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-04-13T09:36:41.8169819+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/238d817d-4dd8-4196-99ff-688e83f7a240/XXREP_MTL_SYSTEM_ITEMS_V.csv?snapshot=2022-04-13T09%3A36%3A41.8051143Z"}]},{"$type":"LocalEntity","name":"RESOURCE_TRAN_LDP","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"RESOURCE_TRAN_LDP.csv"},"annotations":[{"name":"pbi:EntityTypeDisplayHint","value":"CalculatedEntity"}],"attributes":[{"name":"JOB_NUMBER","dataType":"string"},{"name":"WIP_JOB_DESCRIPTION","dataType":"string"},{"name":"WIPJOB_ORG_KEY_CODE","dataType":"string"},{"name":"WIPJOB_ORG_KEY_ID","dataType":"string"},{"name":"DISCRETE_JOB_FLAG","dataType":"string"},{"name":"JOB_TYPE","dataType":"string"},{"name":"RESOURCE_TRX_REFERENCE","dataType":"string"},{"name":"TRANSACTION_ID","dataType":"double"},{"name":"TRANSACTION_TYPE","dataType":"string"},{"name":"TRANSACTION_DATE","dataType":"dateTime"},{"name":"SOURCE_CODE","dataType":"string"},{"name":"OPERATION_SEQ_NUM","dataType":"double"},{"name":"RESOURCE_SEQ_NUM","dataType":"double"},{"name":"AUTOCHARGE_TYPE","dataType":"string"},{"name":"USAGE_RATE_OR_AMOUNT","dataType":"double"},{"name":"BASIS_TYPE","dataType":"string"},{"name":"TRANSACTION_QUANTITY","dataType":"double"},{"name":"TRANSACTION_UOM","dataType":"string"},{"name":"PRIMARY_QUANTITY","dataType":"double"},{"name":"PRIMARY_UOM","dataType":"string"},{"name":"ACTUAL_RESOURCE_RATE","dataType":"double"},{"name":"STANDARD_RESOURCE_RATE","dataType":"double"},{"name":"STANDARD_RATE_FLAG","dataType":"string"},{"name":"CURRENCY_CODE","dataType":"string"},{"name":"MOVE_PRIMARY_QUANTITY","dataType":"double"},{"name":"FM_OPERATION_SEQ_NUM","dataType":"double"},{"name":"TO_OPERATION_SEQ_NUM","dataType":"double"},{"name":"ACTIVITY","dataType":"string"},{"name":"ATTRIBUTE_CATEGORY","dataType":"string"},{"name":"ATTRIBUTE1","dataType":"string"},{"name":"ATTRIBUTE2","dataType":"string"},{"name":"ORGANIZATION_ID","dataType":"double"},{"name":"WIP_ENTITY_ID","dataType":"double"},{"name":"LINE_ID","dataType":"double"},{"name":"PRIMARY_ITEM_ID","dataType":"double"},{"name":"DEPARTMENT_ID","dataType":"double"},{"name":"RESOURCE_ID","dataType":"double"},{"name":"EMPLOYEE_ID","dataType":"double"},{"name":"ACTIVITY_ID","dataType":"double"},{"name":"REASON_ID","dataType":"double"},{"name":"MOVE_TRANSACTION_ID","dataType":"double"},{"name":"COMPLETION_TRANSACTION_ID","dataType":"double"},{"name":"PROJECT_ID","dataType":"double"},{"name":"TASK_ID","dataType":"double"},{"name":"SOURCE_LINE_ID","dataType":"double"},{"name":"CREATION_DATE","dataType":"dateTime"},{"name":"CREATED_BY","dataType":"double"},{"name":"LAST_UPDATE_DATE","dataType":"dateTime"},{"name":"LAST_UPDATED_BY","dataType":"double"},{"name":"PROJECT_NAME","dataType":"string"},{"name":"PROJECT_NUMBER","dataType":"string"},{"name":"DEPARTMENT_CODE","dataType":"string"},{"name":"RESOURCE_CODE","dataType":"string"},{"name":"COST_CODE_TYPE","dataType":"double"},{"name":"ALLOW_COSTS","dataType":"string"},{"name":"ALLOW_COSTS_FLAG","dataType":"double"},{"name":"COST_CODE_TYPE_NAME","dataType":"string"},{"name":"ITEM_NUMBER","dataType":"string"},{"name":"ITEM_DESCRIPTION","dataType":"string"},{"name":"ITEM_ORG_KEY_ID","dataType":"string"},{"name":"ITEM_ORG_KEY_CODE","dataType":"string"},{"name":"ACCT_PERIOD_ID","dataType":"double"},{"name":"PERIOD_NAME","dataType":"string"},{"name":"PERIOD_START_DATE","dataType":"dateTime"},{"name":"PERIOD_CLOSE_DATE","dataType":"dateTime"},{"name":"INVORG_CODE","dataType":"string"},{"name":"LOCAL_EXTRACT_DATE","dataType":"dateTime"},{"name":"EXTRACT_DATE","dataType":"dateTime"},{"name":"TIMEZONE","dataType":"string"},{"name":"LAST_UPDATED_BY_LOGIN","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-04-13T09:42:15.8737403+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/238d817d-4dd8-4196-99ff-688e83f7a240/RESOURCE_TRAN_LDP.csv?snapshot=2022-04-13T09%3A42%3A15.8453898Z"}]},{"$type":"LocalEntity","name":"XXCOH_WIP_TRX_VIEW","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"XXCOH_WIP_TRX_VIEW.csv"},"attributes":[{"name":"ASOF_DATE","dataType":"date"},{"name":"ASOF_DATE_DISP","dataType":"dateTime"},{"name":"TRANSACTION_ID","dataType":"double"},{"name":"WIP_SUB_LEDGER_ID","dataType":"double"},{"name":"ORGANIZATION_CODE","dataType":"string"},{"name":"SET_OF_BOOKS","dataType":"string"},{"name":"TRX_TYPE","dataType":"string"},{"name":"TRX_DATE","dataType":"dateTime"},{"name":"ACCT_ENTITY","dataType":"string"},{"name":"ACCT_DEPT","dataType":"string"},{"name":"ACCT_NUMBER","dataType":"string"},{"name":"TRX_CURRENCY_CODE","dataType":"string"},{"name":"FUNC_CURRENCY_CODE","dataType":"string"},{"name":"ENTERED_DR","dataType":"double"},{"name":"ENTERED_CR","dataType":"double"},{"name":"ACCOUNTED_DR","dataType":"double"},{"name":"ACCOUNTED_CR","dataType":"double"},{"name":"ACCOUNTED_DR_USD","dataType":"double"},{"name":"ACCOUNTED_CR_USD","dataType":"double"},{"name":"GL_TRANSFER_STATUS","dataType":"string"},{"name":"WIP_JOB_NAME","dataType":"string"},{"name":"COST_ELEMENT_NAME","dataType":"string"},{"name":"PERIOD_NAME","dataType":"string"},{"name":"FISCAL_PERIOD","dataType":"double"},{"name":"FISCAL_QUARTER","dataType":"double"},{"name":"FISCAL_YEAR","dataType":"double"},{"name":"FISCAL_WEEK","dataType":"double"},{"name":"CREATED_BY","dataType":"string"},{"name":"ACCOUNTING_LINE_TYPE","dataType":"string"},{"name":"TRANSACTION_QUANTITY","dataType":"double"},{"name":"TRANSACTION_UOM","dataType":"string"},{"name":"PRIMARY_QUANTITY","dataType":"double"},{"name":"PRIMARY_UOM","dataType":"string"},{"name":"USD_RATE","dataType":"double"},{"name":"DEPARTMENT_CODE","dataType":"string"},{"name":"RESOURCE_CODE","dataType":"string"},{"name":"MAT_VAR_ENTITY","dataType":"string"},{"name":"MAT_VAR_DEPT","dataType":"string"},{"name":"MAT_VAR_ACCT","dataType":"string"},{"name":"WIP_ENTITY_ID","dataType":"double"},{"name":"ORGANIZATION_ID","dataType":"double"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"EMPLOYEE_ID","dataType":"double"},{"name":"RESOURCE_ID","dataType":"double"},{"name":"ROW_CREATION_DATE","dataType":"dateTime"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-04-13T09:40:19.2372198+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/238d817d-4dd8-4196-99ff-688e83f7a240/XXCOH_WIP_TRX_VIEW.csv?snapshot=2022-04-13T09%3A40%3A19.2202797Z"}]},{"$type":"LocalEntity","name":"XXCOH_MI_WIP_FIN_VIEW","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"XXCOH_MI_WIP_FIN_VIEW.csv"},"attributes":[{"name":"ASOF_DATE","dataType":"date"},{"name":"ASOF_DATE_DISP","dataType":"dateTime"},{"name":"DATA_SOURCE","dataType":"string"},{"name":"ITEM_NUMBER","dataType":"string"},{"name":"ITEM_DESCRIPTION","dataType":"string"},{"name":"OWNING_ORGANIZATION","dataType":"string"},{"name":"WIP_ENTITY_NAME","dataType":"string"},{"name":"ENTITY_DESCRIPTION","dataType":"string"},{"name":"ENTITY_TYPE","dataType":"string"},{"name":"LINE_CODE","dataType":"string"},{"name":"JOB_TYPE","dataType":"string"},{"name":"JOB_STATUS","dataType":"string"},{"name":"START_QUANTITY","dataType":"double"},{"name":"QUANTITY_COMPLETED","dataType":"double"},{"name":"QUANTITY_SCRAPPED","dataType":"double"},{"name":"QUANTITY_REMAINING","dataType":"double"},{"name":"SCHEDULED_START_DATE","dataType":"dateTime"},{"name":"SCHEDULED_COMPLETION_DATE","dataType":"dateTime"},{"name":"DATE_RELEASED","dataType":"dateTime"},{"name":"DATE_COMPLETED","dataType":"dateTime"},{"name":"DATE_CLOSED","dataType":"dateTime"},{"name":"DUE_DATE","dataType":"dateTime"},{"name":"DEMAND_CLASS","dataType":"string"},{"name":"CLASS_CODE","dataType":"string"},{"name":"BASE_CURRENCY","dataType":"string"},{"name":"SUBINVENTORY","dataType":"string"},{"name":"LOC_BIN","dataType":"string"},{"name":"LOT_NUMBER","dataType":"string"},{"name":"BOM_REVISION","dataType":"string"},{"name":"BOM_REVISION_DATE","dataType":"dateTime"},{"name":"ROUTING_REVISION","dataType":"string"},{"name":"ROUTING_REVISION_DATE","dataType":"dateTime"},{"name":"PLANNER_CODE","dataType":"string"},{"name":"END_ASSEMBLY_PEGGING","dataType":"string"},{"name":"PLANNING_MAKE_BUY_CODE","dataType":"string"},{"name":"BUYER","dataType":"string"},{"name":"PRIMARY_UOM_CODE","dataType":"string"},{"name":"MAX_MINMAX_QUANTITY","dataType":"double"},{"name":"MIN_MINMAX_QUANTITY","dataType":"double"},{"name":"MINIMUM_ORDER_QUANTITY","dataType":"double"},{"name":"FIXED_LOT_MULTIPLIER","dataType":"double"},{"name":"SCHEDULE_GROUP_NAME","dataType":"string"},{"name":"OVERCOMPLETION_TOLERANCE_TYPE","dataType":"double"},{"name":"OVERCOMPLETION_TOLERANCE_VALUE","dataType":"double"},{"name":"MATERIAL_ENTITY","dataType":"string"},{"name":"MATERIAL_DEPT","dataType":"string"},{"name":"MATERIAL_ACCT","dataType":"string"},{"name":"MATERIAL_OH_ENTITY","dataType":"string"},{"name":"MATERIAL_OH_DEPT","dataType":"string"},{"name":"MATERIAL_OH_ACCT","dataType":"string"},{"name":"RESOURCE_ENTITY","dataType":"string"},{"name":"RESOURCE_DEPT","dataType":"string"},{"name":"RESOURCE_ACCT","dataType":"string"},{"name":"OVERHEAD_ENTITY","dataType":"string"},{"name":"OVERHEAD_DEPT","dataType":"string"},{"name":"OVERHEAD_ACCT","dataType":"string"},{"name":"OS_PROCESS_ENTITY","dataType":"string"},{"name":"OS_PROCESS_DEPT","dataType":"string"},{"name":"OS_PROCESS_ACCT","dataType":"string"},{"name":"EXPENSE_ENTITY","dataType":"string"},{"name":"EXPENSE_DEPT","dataType":"string"},{"name":"EXPENSE_ACCT","dataType":"string"},{"name":"ACCT_ATTRIBUTE1","dataType":"string"},{"name":"ACCT_ATTRIBUTE2","dataType":"string"},{"name":"ACCT_ATTRIBUTE3","dataType":"string"},{"name":"ACCT_ATTRIBUTE4","dataType":"string"},{"name":"ACCT_CLASS_TYPE","dataType":"string"},{"name":"MAT_VAR_ENTITY","dataType":"string"},{"name":"MAT_VAR_DEPT","dataType":"string"},{"name":"MAT_VAR_ACCT","dataType":"string"},{"name":"RSC_VAR_ENTITY","dataType":"string"},{"name":"RSC_VAR_DEPT","dataType":"string"},{"name":"RSC_VAR_ACCT","dataType":"string"},{"name":"OH_VAR_ENTITY","dataType":"string"},{"name":"OH_VAR_DEPT","dataType":"string"},{"name":"OH_VAR_ACCT","dataType":"string"},{"name":"OS_PROC_VAR_ENTITY","dataType":"string"},{"name":"OS_PROC_VAR_DEPT","dataType":"string"},{"name":"OS_PROC_VAR_ACCT","dataType":"string"},{"name":"AGILE_LIFE_PHASE","dataType":"string"},{"name":"BOM_ITEM_TYPE","dataType":"string"},{"name":"BOM_ENABLED_FLAG","dataType":"string"},{"name":"BUILD_IN_WIP_FLAG","dataType":"string"},{"name":"COSTING_ENABLED_FLAG","dataType":"string"},{"name":"CREATE_SUPPLY_FLAG","dataType":"string"},{"name":"CUSTOMER_ORDER_ENABLED_FLAG","dataType":"string"},{"name":"CUSTOMER_ORDER_FLAG","dataType":"string"},{"name":"CYCLE_COUNT_ENABLED_FLAG","dataType":"string"},{"name":"DEFAULT_SO_SOURCE_TYPE","dataType":"string"},{"name":"INSPECTION_REQUIRED_FLAG","dataType":"string"},{"name":"INVENTORY_ASSET_FLAG","dataType":"string"},{"name":"INVENTORY_ITEM_FLAG","dataType":"string"},{"name":"MUST_USE_APPROVED_VENDOR_FLAG","dataType":"string"},{"name":"PURCHASING_ENABLED_FLAG","dataType":"string"},{"name":"PURCHASING_ITEM_FLAG","dataType":"string"},{"name":"ITEM_TYPE_CODE","dataType":"string"},{"name":"ITEM_CATALOG_GROUP","dataType":"string"},{"name":"ITEM_TYPE","dataType":"string"},{"name":"LATEST_ITEM_REVISION","dataType":"string"},{"name":"REVISION_EFFECTIVITY_DATE","dataType":"dateTime"},{"name":"FULL_LEAD_TIME","dataType":"double"},{"name":"TECHNICAL_BUSINESS_UNIT","dataType":"string"},{"name":"PRODUCT_FAMILY","dataType":"string"},{"name":"PRODUCT_LINE","dataType":"string"},{"name":"FORECAST_FIELD","dataType":"string"},{"name":"LEAD_TIME_CATEGORY","dataType":"string"},{"name":"COMMODITY","dataType":"string"},{"name":"PRIMARY_ORG","dataType":"string"},{"name":"ORG_TECHNICAL_BUSINESS_UNIT","dataType":"string"},{"name":"ORG_PRODUCT_FAMILY","dataType":"string"},{"name":"ORG_PRODUCT_LINE","dataType":"string"},{"name":"ORG_FORECAST_FIELD","dataType":"string"},{"name":"ITEM_CUSTOMER","dataType":"string"},{"name":"BCP_CODE","dataType":"string"},{"name":"ROYALTY","dataType":"string"},{"name":"PLANNING_GREEN_SUPPLY_STATUS","dataType":"string"},{"name":"PLANNING_ACTION","dataType":"string"},{"name":"PLANNING_FAMILY_UNIQUE","dataType":"string"},{"name":"SPC_ITEM_COST","dataType":"double"},{"name":"SPC_ITEM_ADD_BACK_COST","dataType":"double"},{"name":"SPC_MATERIAL_COST","dataType":"double"},{"name":"SPC_RESOURCE_COST","dataType":"double"},{"name":"SPC_MATERIAL_OVERHEAD_COST","dataType":"double"},{"name":"SPC_OVERHEAD_COST","dataType":"double"},{"name":"SPC_OUTSIDE_PROCESSING_COST","dataType":"double"},{"name":"SPC_TL_ITEM_COST","dataType":"double"},{"name":"SPC_TL_MATERIAL","dataType":"double"},{"name":"SPC_TL_RESOURCE","dataType":"double"},{"name":"SPC_TL_MATERIAL_OVERHEAD","dataType":"double"},{"name":"SPC_TL_OVERHEAD","dataType":"double"},{"name":"SPC_TL_OUTSIDE_PROCESSING","dataType":"double"},{"name":"SPC_SHRINKAGE_RATE","dataType":"double"},{"name":"LEGAL_ENTITY","dataType":"string"},{"name":"OPERATING_UNIT","dataType":"string"},{"name":"SET_OF_BOOKS","dataType":"string"},{"name":"ORG_LOCATION_CODE","dataType":"string"},{"name":"REGION_1","dataType":"string"},{"name":"TOWN_OR_CITY","dataType":"string"},{"name":"SITE","dataType":"string"},{"name":"REPORTING_TBU","dataType":"string"},{"name":"FISCAL_PERIOD","dataType":"double"},{"name":"FISCAL_QUARTER","dataType":"double"},{"name":"FISCAL_YEAR","dataType":"double"},{"name":"FISCAL_WEEK","dataType":"double"},{"name":"FISCAL_SYSDATE_GEN","dataType":"date"},{"name":"SCHE_CMPL_FISCAL_PERIOD","dataType":"double"},{"name":"SCHE_CMPL_FISCAL_QUARTER","dataType":"double"},{"name":"SCHE_CMPL_FISCAL_YEAR","dataType":"double"},{"name":"SCHE_CMPL_FISCAL_WEEK","dataType":"double"},{"name":"CUSTOMER_NAME","dataType":"string"},{"name":"ALTERNATE_CUSTOMER_NAME","dataType":"string"},{"name":"ORDER_NUMBER","dataType":"double"},{"name":"ORDER_LINE","dataType":"string"},{"name":"SALESPERSON","dataType":"string"},{"name":"AGREEMENT_NUMBER","dataType":"string"},{"name":"TL_RESOURCE_IN","dataType":"double"},{"name":"TL_OVERHEAD_IN","dataType":"double"},{"name":"TL_OUTSIDE_PROCESSING_IN","dataType":"double"},{"name":"PL_MATERIAL_IN","dataType":"double"},{"name":"PL_MATERIAL_OVERHEAD_IN","dataType":"double"},{"name":"PL_RESOURCE_IN","dataType":"double"},{"name":"PL_OVERHEAD_IN","dataType":"double"},{"name":"PL_OUTSIDE_PROCESSING_IN","dataType":"double"},{"name":"TL_MATERIAL_OUT","dataType":"double"},{"name":"TL_MATERIAL_OVERHEAD_OUT","dataType":"double"},{"name":"TL_RESOURCE_OUT","dataType":"double"},{"name":"TL_OVERHEAD_OUT","dataType":"double"},{"name":"TL_OUTSIDE_PROCESSING_OUT","dataType":"double"},{"name":"PL_MATERIAL_OUT","dataType":"double"},{"name":"PL_MATERIAL_OVERHEAD_OUT","dataType":"double"},{"name":"PL_RESOURCE_OUT","dataType":"double"},{"name":"PL_OVERHEAD_OUT","dataType":"double"},{"name":"PL_OUTSIDE_PROCESSING_OUT","dataType":"double"},{"name":"TL_MATERIAL_VAR","dataType":"double"},{"name":"TL_MATERIAL_OVERHEAD_VAR","dataType":"double"},{"name":"TL_RESOURCE_VAR","dataType":"double"},{"name":"TL_OVERHEAD_VAR","dataType":"double"},{"name":"TL_OUTSIDE_PROCESSING_VAR","dataType":"double"},{"name":"PL_MATERIAL_VAR","dataType":"double"},{"name":"PL_MATERIAL_OVERHEAD_VAR","dataType":"double"},{"name":"PL_RESOURCE_VAR","dataType":"double"},{"name":"PL_OVERHEAD_VAR","dataType":"double"},{"name":"PL_OUTSIDE_PROCESSING_VAR","dataType":"double"},{"name":"TL_SCRAP_IN","dataType":"double"},{"name":"TL_SCRAP_OUT","dataType":"double"},{"name":"TL_SCRAP_VAR","dataType":"double"},{"name":"MATERIAL_COSTS_INCURRED","dataType":"double"},{"name":"MATERIAL_OH_COSTS_INCURRED","dataType":"double"},{"name":"RESOURCE_COSTS_INCURRED","dataType":"double"},{"name":"OVERHEAD_COSTS_INCURRED","dataType":"double"},{"name":"OS_PROCESS_COSTS_INCURRED","dataType":"double"},{"name":"MATERIAL_COSTS_RELIEVED","dataType":"double"},{"name":"MATERIAL_OH_COSTS_RELIEVED","dataType":"double"},{"name":"RESOURCE_COSTS_RELIEVED","dataType":"double"},{"name":"OVERHEAD_COSTS_RELIEVED","dataType":"double"},{"name":"OS_PROCESS_COSTS_RELIEVED","dataType":"double"},{"name":"MATERIAL_VARIANCES_RELIEVED","dataType":"double"},{"name":"MATERIAL_OH_VARIANCES_RELIEVED","dataType":"double"},{"name":"RESOURCE_VARIANCES_RELIEVED","dataType":"double"},{"name":"OVERHEAD_VARIANCES_RELIEVED","dataType":"double"},{"name":"OS_PROCESS_VARIANCES_RELIEVED","dataType":"double"},{"name":"MATERIAL_NET_ACTIVITIES","dataType":"double"},{"name":"MATERIAL_OH_NET_ACTIVITIES","dataType":"double"},{"name":"RESOURCE_NET_ACTIVITIES","dataType":"double"},{"name":"OVERHEAD_NET_ACTIVITIES","dataType":"double"},{"name":"OS_PROCESS_NET_ACTIVITIES","dataType":"double"},{"name":"TOTAL_COSTS_INCURRED","dataType":"double"},{"name":"TOTAL_COSTS_RELIEVED","dataType":"double"},{"name":"TOTAL_VARIANCES_RELIEVED","dataType":"double"},{"name":"TOTAL_NET_ACTIVITIES","dataType":"double"},{"name":"USD_RATE","dataType":"double"},{"name":"TOTAL_COSTS_INCURRED_USD","dataType":"double"},{"name":"TOTAL_COSTS_RELIEVED_USD","dataType":"double"},{"name":"TOTAL_VARIANCES_RELIEVED_USD","dataType":"double"},{"name":"TOT_NET_ACTIVITIES_USD","dataType":"double"},{"name":"DATE_STARTED","dataType":"dateTime"},{"name":"WIP_ENTITY_ID","dataType":"double"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"ORGANIZATION_ID","dataType":"double"},{"name":"LOCATOR_ID","dataType":"double"},{"name":"ROUTING_REFERENCE_ID","dataType":"double"},{"name":"OPERATING_UNIT_ID","dataType":"double"},{"name":"LEGAL_ENTITY_ID","dataType":"double"},{"name":"OE_HEADER_ID","dataType":"double"},{"name":"OE_LINE_ID","dataType":"double"},{"name":"PROJECT_ID","dataType":"double"},{"name":"PROJECT_NAME","dataType":"string"},{"name":"PROJECT_NUMBER","dataType":"string"},{"name":"INCIDENT_NUMBER","dataType":"string"},{"name":"FIN_TBU","dataType":"string"},{"name":"FIN_PFC","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-04-13T09:39:22.9200221+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/238d817d-4dd8-4196-99ff-688e83f7a240/XXCOH_MI_WIP_FIN_VIEW.csv?snapshot=2022-04-13T09%3A39%3A22.8961017Z"}]},{"$type":"LocalEntity","name":"XXREP_MFG_MTL_ITEM_ATTRIBUTES_V","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"XXREP_MFG_MTL_ITEM_ATTRIBUTES_V.csv"},"attributes":[{"name":"EXTRACT_DATE","dataType":"date"},{"name":"LOCAL_EXTRACT_DATE","dataType":"string"},{"name":"ORGANIZATION_CODE","dataType":"string"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"ORGANIZATION_ID","dataType":"double"},{"name":"ITEM_ORG_KEY_ID","dataType":"string"},{"name":"ITEM_ORG_KEY_CODE","dataType":"string"},{"name":"ITEM_NUMBER","dataType":"string"},{"name":"MRP_PLANNING_CODE","dataType":"string"},{"name":"ITEM_REVISION","dataType":"string"},{"name":"DESCRIPTION","dataType":"string"},{"name":"PRIMARY_UNIT_OF_MEASURE","dataType":"string"},{"name":"ITEM_STATUS","dataType":"string"},{"name":"ITEM_TYPE","dataType":"string"},{"name":"INVENTORY_ITEM_FLAG","dataType":"string"},{"name":"LOT_CONTROL_CODE","dataType":"string"},{"name":"SERIAL_CONTROL_CODE","dataType":"string"},{"name":"RECEIPT_ROUTING","dataType":"string"},{"name":"DEFAULT_BUYER","dataType":"string"},{"name":"BUYER_ID","dataType":"double"},{"name":"PLANNING_MAKE_BUY_CODE","dataType":"string"},{"name":"USD_RATE","dataType":"double"},{"name":"PLANNER_CODE","dataType":"string"},{"name":"PREPROCESSING_LEAD_TIME","dataType":"double"},{"name":"PROCESSING_LEAD_TIME","dataType":"double"},{"name":"POSTPROCESSING_LEAD_TIME","dataType":"double"},{"name":"LEAD_TIME_LOT_SIZE","dataType":"double"},{"name":"FIXED_LEAD_TIME","dataType":"double"},{"name":"VARIABLE_LEAD_TIME","dataType":"double"},{"name":"APOP","dataType":"string"},{"name":"LIST_PRICE_PER_UNIT","dataType":"double"},{"name":"ITEM_CREATION_DATE","dataType":"dateTime"},{"name":"COSTING_ENABLED_FLAG","dataType":"string"},{"name":"INVENTORY_ASSET_FLAG","dataType":"string"},{"name":"PLANNING_TIME_FENCE","dataType":"string"},{"name":"PLANNING_TIME_FENCE_DAYS","dataType":"double"},{"name":"DEMAND_TIME_FENCE","dataType":"string"},{"name":"DEMAND_TIME_FENCE_DAYS","dataType":"double"},{"name":"RELEASE_TIME_FENCE","dataType":"string"},{"name":"RELEASE_TIME_FENCE_DAYS","dataType":"double"},{"name":"ACCEPTABLE_EARLY_DAYS","dataType":"double"},{"name":"FIXED_DAYS_SUPPLY","dataType":"double"},{"name":"MINIMUM_ORDER_QUANTITY","dataType":"double"},{"name":"MAXIMUM_ORDER_QUANTITY","dataType":"double"},{"name":"MIN_MINMAX_QUANTITY","dataType":"double"},{"name":"MAX_MINMAX_QUANTITY","dataType":"double"},{"name":"FIXED_LOT_MULTIPLIER","dataType":"double"},{"name":"FIXED_ORDER_QUANTITY","dataType":"double"},{"name":"SOURCE_TYPE","dataType":"string"},{"name":"SOURCE_ORG","dataType":"string"},{"name":"CRITICAL_COMPONENT_FLAG","dataType":"string"},{"name":"INVENTORY_PLANNING_CODE","dataType":"string"},{"name":"WIP_SUPPLY_TYPE","dataType":"string"},{"name":"CURRENT_ITEM_ABC_CLASS","dataType":"string"},{"name":"WIP_SUPPLY_SUBINVENTORY","dataType":"string"},{"name":"WIP_SUPPLY_LOCATOR","dataType":"string"},{"name":"SUPPLY_CHAIN_STATUS","dataType":"string"},{"name":"ORG_PRODUCT","dataType":"string"},{"name":"MAS_PRODUCT","dataType":"string"},{"name":"PRODUCT_KEY","dataType":"string"},{"name":"COUNTRY_OF_ORIGIN","dataType":"string"},{"name":"SOURCING_COMMODITY","dataType":"string"},{"name":"PRODUCT_FAMILY","dataType":"string"},{"name":"COMMODITY","dataType":"string"},{"name":"SUPPLIER_FULL_LEAD_TIME","dataType":"string"},{"name":"SALES_AVAILABILITY","dataType":"string"},{"name":"PRIMARY_ORG","dataType":"string"},{"name":"SHIPMENT_PRIORITY","dataType":"string"},{"name":"REPLENISHMENT_METHOD","dataType":"string"},{"name":"SOURCING_RULE","dataType":"string"},{"name":"COST_CATEGORY","dataType":"string"},{"name":"LAST_PO_UNIT_PRICE","dataType":"double"},{"name":"LAST_PO_UNIT_PRICE_USD_BUDGET","dataType":"double"},{"name":"LAST_PO_CURRENCY","dataType":"string"},{"name":"APOP_CLASSIFICATION","dataType":"string"},{"name":"BASELINE_UNIT_PRICE","dataType":"double"},{"name":"LAST_PO_VENDOR_NAME","dataType":"string"},{"name":"ASSEMBLY_PRODUCT_CATEGORY","dataType":"string"},{"name":"PO_PROJECT","dataType":"double"},{"name":"CUM_MFG_LT","dataType":"double"},{"name":"CUM_TOTAL_LT","dataType":"double"},{"name":"DEFAULT_SHIPPING_ORG","dataType":"string"},{"name":"TRACK_INSTALL_BASE","dataType":"string"},{"name":"ATP_CHECK","dataType":"string"},{"name":"ATP_COMPONENTS","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-04-13T09:37:07.49939+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/238d817d-4dd8-4196-99ff-688e83f7a240/XXREP_MFG_MTL_ITEM_ATTRIBUTES_V.csv?snapshot=2022-04-13T09%3A37%3A07.4816069Z"}]},{"$type":"LocalEntity","name":"XXREP_MFG_PURCHASE_ORDER_V","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"XXREP_MFG_PURCHASE_ORDER_V.csv"},"attributes":[{"name":"EXTRACT_DATE","dataType":"date"},{"name":"PO_RELEASE_ID","dataType":"double"},{"name":"PO_APPROVAL_MODE","dataType":"string"},{"name":"ORGANIZATION_CODE","dataType":"string"},{"name":"PO_NUMBER","dataType":"string"},{"name":"PO_KEY_AGENT_ID","dataType":"double"},{"name":"PO_AGENT_ID","dataType":"double"},{"name":"PO_BUYER","dataType":"string"},{"name":"PO_KEY_BUYER","dataType":"string"},{"name":"RELEASE_NUM","dataType":"double"},{"name":"REVISION_NUM","dataType":"double"},{"name":"CREATION_DATE","dataType":"dateTime"},{"name":"PO_KEY_ORIGINAL_APPROVED_DATE","dataType":"dateTime"},{"name":"FUNCTIONAL_RATE","dataType":"double"},{"name":"PO_KEY","dataType":"string"},{"name":"COMMENTS","dataType":"string"},{"name":"APPROVED_FLAG","dataType":"string"},{"name":"APPROVED_DATE","dataType":"dateTime"},{"name":"PO_KEY_APPROVED_DATE","dataType":"dateTime"},{"name":"FOB_LOOKUP_CODE","dataType":"string"},{"name":"PO_TYPE","dataType":"string"},{"name":"PURCHASING_CATEGORY","dataType":"string"},{"name":"SHIPMENT_CLOSED_DATE","dataType":"dateTime"},{"name":"CLOSED_FOR_RECEIVING_DATE","dataType":"dateTime"},{"name":"CLOSED_FOR_INVOICE_DATE","dataType":"dateTime"},{"name":"CLOSED_REASON","dataType":"string"},{"name":"CLOSED_DATE","dataType":"dateTime"},{"name":"CLOSED_CODE","dataType":"string"},{"name":"DESTINATION_SUBINVENTORY","dataType":"string"},{"name":"LAST_PO_ACCEPTANCE_DATE","dataType":"dateTime"},{"name":"LINE_TYPE","dataType":"string"},{"name":"DOCUMENT_CREATION_METHOD","dataType":"string"},{"name":"CONSUMPTION_ADVICE_FLAG","dataType":"string"},{"name":"RATE_DATE","dataType":"dateTime"},{"name":"PO_LINE_ID","dataType":"double"},{"name":"ITEM_ID","dataType":"double"},{"name":"LINE_NUM","dataType":"double"},{"name":"PO_ITEM_NUMBER","dataType":"string"},{"name":"PO_ITEM_REVISION","dataType":"string"},{"name":"PO_ITEM_DESCRIPTION","dataType":"string"},{"name":"PO_UNIT_OF_MEASURE","dataType":"string"},{"name":"PLANNER_CODE","dataType":"string"},{"name":"CURRENCY_CODE","dataType":"string"},{"name":"UNIT_PRICE","dataType":"double"},{"name":"LINE_LOCATION_ID","dataType":"double"},{"name":"SHIPMENT_NUM","dataType":"double"},{"name":"NEED_BY_DATE","dataType":"dateTime"},{"name":"PROMISED_DATE","dataType":"dateTime"},{"name":"QUANTITY","dataType":"double"},{"name":"QUANTITY_RECEIVED","dataType":"double"},{"name":"QUANTITY_CANCELLED","dataType":"double"},{"name":"QUANTITY_BILLED","dataType":"double"},{"name":"QUANTITY_ACCEPTED","dataType":"double"},{"name":"QUANTITY_DELIVERED","dataType":"double"},{"name":"DOCUMENT_REFERENCE_TYPE","dataType":"string"},{"name":"DOCUMENT_REFERENCE_NUMBER","dataType":"string"},{"name":"VENDOR_ID","dataType":"double"},{"name":"VENDOR_SITE_ID","dataType":"double"},{"name":"CONSIGNED_FLAG","dataType":"string"},{"name":"ITEM_TYPE","dataType":"string"},{"name":"PPV_APOP_OR_ITEM_COST","dataType":"string"},{"name":"PPV_RATE_PERCENT","dataType":"string"},{"name":"PPV_APPROVAL_REQUIRED","dataType":"string"},{"name":"PPV_REASON","dataType":"string"},{"name":"DESTINATION_TYPE_CODE","dataType":"string"},{"name":"FIRST_APPROVED_DATE","dataType":"dateTime"},{"name":"REQUISITION_APPROVED_DATE","dataType":"dateTime"},{"name":"IS_PO_SHIPMENT_OPEN","dataType":"string"},{"name":"PO_SOURCE","dataType":"string"},{"name":"SUGG_EARLIEST_DOCK_DATE","dataType":"dateTime"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-04-13T09:39:33.0812658+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/238d817d-4dd8-4196-99ff-688e83f7a240/XXREP_MFG_PURCHASE_ORDER_V.csv?snapshot=2022-04-13T09%3A39%3A33.0603587Z"}]},{"$type":"LocalEntity","name":"XXCOH_MP_REQ_VIEW","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"XXCOH_MP_REQ_VIEW.csv"},"attributes":[{"name":"ASOF_DATE","dataType":"date"},{"name":"ASOF_DATE_DISP","dataType":"dateTime"},{"name":"REQ_NUM","dataType":"string"},{"name":"DESCRIPTION","dataType":"string"},{"name":"TYPE_NAME","dataType":"string"},{"name":"PREPARER","dataType":"string"},{"name":"AUTHORIZATION_STATUS","dataType":"string"},{"name":"CLOSED_CODE","dataType":"string"},{"name":"START_DATE_ACTIVE","dataType":"dateTime"},{"name":"END_DATE_ACTIVE","dataType":"dateTime"},{"name":"INTERFACE_SOURCE_CODE","dataType":"string"},{"name":"TRANSFERRED_TO_OE_FLAG","dataType":"string"},{"name":"FUNC_CURRENCY_CODE","dataType":"string"},{"name":"OPERATING_UNIT_ID","dataType":"double"},{"name":"OPERATING_UNIT","dataType":"string"},{"name":"LEGAL_ENTITY_ID","dataType":"double"},{"name":"LEGAL_ENTITY","dataType":"string"},{"name":"SET_OF_BOOKS","dataType":"string"},{"name":"REQ_CREATION_DATE","dataType":"dateTime"},{"name":"OE_ORDER_NUM","dataType":"double"},{"name":"OE_HEADER_ID","dataType":"double"},{"name":"OE_SOURCE_DOCUMENT_LINE_ID","dataType":"double"},{"name":"ACTION_SEQUENCE_NUM","dataType":"double"},{"name":"ACTION_CODE","dataType":"string"},{"name":"ACTION_DATE","dataType":"dateTime"},{"name":"ACTIONER","dataType":"string"},{"name":"ACTION_NOTE","dataType":"string"},{"name":"LINE_NUM","dataType":"double"},{"name":"LINE_TYPE","dataType":"string"},{"name":"ITEM_NUMBER","dataType":"string"},{"name":"ITEM_DESCRIPTION","dataType":"string"},{"name":"ITEM_REVISION","dataType":"string"},{"name":"ITEM_CATEGORY","dataType":"string"},{"name":"PLANNER_CODE","dataType":"string"},{"name":"TECHNICAL_BUSINESS_UNIT","dataType":"string"},{"name":"PRODUCT_FAMILY","dataType":"string"},{"name":"PRODUCT_LINE","dataType":"string"},{"name":"FORECAST_FIELD","dataType":"string"},{"name":"COMMODITY","dataType":"string"},{"name":"PRIMARY_ORG","dataType":"string"},{"name":"ORG_TECHNICAL_BUSINESS_UNIT","dataType":"string"},{"name":"ORG_PRODUCT_FAMILY","dataType":"string"},{"name":"ORG_PRODUCT_LINE","dataType":"string"},{"name":"ORG_FORECAST_FIELD","dataType":"string"},{"name":"ITEM_CUSTOMER","dataType":"string"},{"name":"BCP_CODE","dataType":"string"},{"name":"ROYALTY","dataType":"string"},{"name":"QUANTITY","dataType":"double"},{"name":"QUANTITY_RECEIVED","dataType":"double"},{"name":"QUANTITY_DELIVERED","dataType":"double"},{"name":"QUANTITY_CANCELLED","dataType":"double"},{"name":"QUANTITY_DUE","dataType":"double"},{"name":"QUANTITY_UNDELIVERED","dataType":"double"},{"name":"UNIT_MEAS_LOOKUP_CODE","dataType":"string"},{"name":"UNIT_PRICE","dataType":"double"},{"name":"NEED_BY_DATE","dataType":"dateTime"},{"name":"SUGGESTED_BUYER","dataType":"string"},{"name":"NOTE_TO_AGENT","dataType":"string"},{"name":"SUGGESTED_VENDOR_NAME","dataType":"string"},{"name":"SUGGESTED_VENDOR_LOCATION","dataType":"string"},{"name":"SUGGESTED_VENDOR_CONTACT","dataType":"string"},{"name":"SUGGESTED_VENDOR_PHONE","dataType":"string"},{"name":"SUGGESTED_VENDOR_PRODUCT_CODE","dataType":"string"},{"name":"CANCEL_FLAG","dataType":"string"},{"name":"CANCEL_DATE","dataType":"dateTime"},{"name":"CANCEL_REASON","dataType":"string"},{"name":"LINE_CLOSED_CODE","dataType":"string"},{"name":"CLOSED_REASON","dataType":"string"},{"name":"CLOSED_DATE","dataType":"dateTime"},{"name":"MODIFIED_BY_AGENT_FLAG","dataType":"string"},{"name":"TRANSACTION_REASON","dataType":"string"},{"name":"REFERENCE_NUM","dataType":"string"},{"name":"URGENT_FLAG","dataType":"string"},{"name":"JUSTIFICATION","dataType":"string"},{"name":"NOTE_TO_RECEIVER","dataType":"string"},{"name":"DESTINATION_TYPE_CODE","dataType":"string"},{"name":"SOURCE_TYPE_CODE","dataType":"string"},{"name":"REQUESTOR","dataType":"string"},{"name":"DESTINATION_ORG","dataType":"string"},{"name":"DELIVER_TO_LOCATION","dataType":"string"},{"name":"DESTINATION_SUBINVENTORY","dataType":"string"},{"name":"SOURCE_ORG","dataType":"string"},{"name":"SOURCE_SUBINVENTORY","dataType":"string"},{"name":"VENDOR_NAME","dataType":"string"},{"name":"VENDOR_ALTERNATE_NAME","dataType":"string"},{"name":"VENDOR_INTERNAL","dataType":"string"},{"name":"INTERDIV","dataType":"string"},{"name":"VENDOR_SITE_CODE","dataType":"string"},{"name":"ADDRESS_LINE1","dataType":"string"},{"name":"ADDRESS_LINE2","dataType":"string"},{"name":"ADDRESS_LINE3","dataType":"string"},{"name":"ADDRESS_LINES_ALT","dataType":"string"},{"name":"CITY","dataType":"string"},{"name":"STATE","dataType":"string"},{"name":"ZIP","dataType":"string"},{"name":"PROVINCE","dataType":"string"},{"name":"COUNTRY","dataType":"string"},{"name":"VENDOR_CUSTOMER_NUM","dataType":"string"},{"name":"LAST_NAME","dataType":"string"},{"name":"FIRST_NAME","dataType":"string"},{"name":"MIDDLE_NAME","dataType":"string"},{"name":"PREFIX","dataType":"string"},{"name":"TITLE","dataType":"string"},{"name":"MAIL_STOP","dataType":"string"},{"name":"AREA_CODE","dataType":"string"},{"name":"PHONE","dataType":"string"},{"name":"OUTSIDE_OPERATION_FLAG","dataType":"string"},{"name":"CURRENCY_CODE","dataType":"string"},{"name":"RATE","dataType":"double"},{"name":"RATE_TYPE","dataType":"string"},{"name":"RATE_DATE","dataType":"dateTime"},{"name":"CURRENCY_UNIT_PRICE","dataType":"double"},{"name":"DOCUMENT_TYPE_CODE","dataType":"string"},{"name":"DESTINATION_CONTEXT","dataType":"string"},{"name":"INVENTORY_SOURCE_CONTEXT","dataType":"string"},{"name":"VENDOR_SOURCE_CONTEXT","dataType":"string"},{"name":"CATALOG_TYPE","dataType":"string"},{"name":"CATALOG_SOURCE","dataType":"string"},{"name":"MANUFACTURER_NAME","dataType":"string"},{"name":"MANUFACTURER_PART_NUMBER","dataType":"string"},{"name":"REQUESTER_EMAIL","dataType":"string"},{"name":"REQUESTER_FAX","dataType":"string"},{"name":"REQUESTER_PHONE","dataType":"string"},{"name":"TAX_STATUS_INDICATOR","dataType":"string"},{"name":"TAX_USER_OVERRIDE_FLAG","dataType":"string"},{"name":"TAX_CODE","dataType":"string"},{"name":"NOTE_TO_VENDOR","dataType":"string"},{"name":"PREFERRED_GRADE","dataType":"string"},{"name":"SUPPLIER_REF_NUMBER","dataType":"string"},{"name":"REQS_IN_POOL_FLAG","dataType":"string"},{"name":"BLANKET_PO_NUMBER","dataType":"string"},{"name":"WIP_ENTITY_NAME","dataType":"string"},{"name":"FISCAL_PERIOD_DUE","dataType":"double"},{"name":"FISCAL_QUARTER_DUE","dataType":"double"},{"name":"FISCAL_YEAR_DUE","dataType":"double"},{"name":"FISCAL_WEEK_DUE","dataType":"double"},{"name":"ITEM_COST","dataType":"double"},{"name":"PRICE_VARIANCE","dataType":"double"},{"name":"TRANSACTION_REASON_CODE","dataType":"string"},{"name":"BLANKET_PO_LINE_NUM","dataType":"double"},{"name":"DISTRIBUTION_QUANTITY","dataType":"double"},{"name":"CHARGE_ENTITY","dataType":"string"},{"name":"CHARGE_DEPT","dataType":"string"},{"name":"CHARGE_ACCOUNT","dataType":"string"},{"name":"CHARGE_IC","dataType":"string"},{"name":"CHARGE_PROJECT","dataType":"string"},{"name":"CHARGE_TBD","dataType":"string"},{"name":"ACCRUAL_ENTITY","dataType":"string"},{"name":"ACCRUAL_DEPT","dataType":"string"},{"name":"ACCRUAL_ACCOUNT","dataType":"string"},{"name":"ACCRUAL_IC","dataType":"string"},{"name":"ACCRUAL_PROJECT","dataType":"string"},{"name":"ACCRUAL_TBD","dataType":"string"},{"name":"VARIANCE_ENTITY","dataType":"string"},{"name":"VARIANCE_DEPT","dataType":"string"},{"name":"VARIANCE_ACCOUNT","dataType":"string"},{"name":"VARIANCE_IC","dataType":"string"},{"name":"VARIANCE_PROJECT","dataType":"string"},{"name":"VARIANCE_TBD","dataType":"string"},{"name":"GL_CANCELLED_DATE","dataType":"dateTime"},{"name":"GL_CLOSED_DATE","dataType":"dateTime"},{"name":"DISTRIBUTION_NUM","dataType":"double"},{"name":"RECOVERABLE_TAX","dataType":"double"},{"name":"NONRECOVERABLE_TAX","dataType":"double"},{"name":"REQUISITION_HEADER_ID","dataType":"double"},{"name":"REQUISITION_LINE_ID","dataType":"double"},{"name":"DISTRIBUTION_ID","dataType":"double"},{"name":"WIP_ENTITY_ID","dataType":"double"},{"name":"WIP_LINE_ID","dataType":"double"},{"name":"SALESREP_NAME","dataType":"string"},{"name":"END_CUSTOMER_NAME","dataType":"string"},{"name":"END_CUSTOMER_NUMBER","dataType":"string"},{"name":"EXT_SO_ORDER_NUMBER","dataType":"double"},{"name":"EXT_SO_LINE_NUMBER","dataType":"double"},{"name":"EXT_SO_SHIPMENT_NUMBER","dataType":"double"},{"name":"EXT_SO_HEADER_ID","dataType":"double"},{"name":"EXT_SO_LINE_ID","dataType":"double"},{"name":"ROW_CREATION_DATE","dataType":"dateTime"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-04-13T09:36:17.4317479+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/238d817d-4dd8-4196-99ff-688e83f7a240/XXCOH_MP_REQ_VIEW.csv?snapshot=2022-04-13T09%3A36%3A17.4168929Z"}]},{"$type":"LocalEntity","name":"XXCOH_MP_RECEIPTS_VIEW","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"XXCOH_MP_RECEIPTS_VIEW.csv"},"attributes":[{"name":"ASOF_DATE","dataType":"date"},{"name":"ASOF_DATE_DISP","dataType":"dateTime"},{"name":"SOURCE_DOCUMENT_CODE","dataType":"string"},{"name":"RECEIPT_NUM","dataType":"string"},{"name":"RECEIPT_LINE_NUM","dataType":"double"},{"name":"ORDER_NUMBER","dataType":"string"},{"name":"RECEIPT_COMMENTS","dataType":"string"},{"name":"DESTINATION_TYPE_CODE","dataType":"string"},{"name":"TRANSACTION_DATE","dataType":"dateTime"},{"name":"TRANSACTION_TYPE","dataType":"string"},{"name":"USER_ENTERED_FLAG","dataType":"string"},{"name":"ITEM_NUMBER","dataType":"string"},{"name":"ITEM_DESCRIPTION","dataType":"string"},{"name":"ORDER_TYPE","dataType":"string"},{"name":"SOURCE_NAME","dataType":"string"},{"name":"ALTERNATE_SOURCE_NAME","dataType":"string"},{"name":"VENDOR_INTERNAL","dataType":"string"},{"name":"INTERDIV","dataType":"string"},{"name":"SOURCE_NUMBER","dataType":"double"},{"name":"LINE_NUMBER","dataType":"double"},{"name":"QUANTITY","dataType":"double"},{"name":"UNIT_OF_MEASURE","dataType":"string"},{"name":"PRIMARY_QUANTITY","dataType":"double"},{"name":"PRIMARY_UNIT_OF_MEASURE","dataType":"string"},{"name":"PO_SHIPMENT_NUMBER","dataType":"double"},{"name":"PO_SHIPMENT_QUANTITY","dataType":"double"},{"name":"ORDERED_QANTITY","dataType":"double"},{"name":"ORDERED_UNIT_OF_MEASURE","dataType":"string"},{"name":"UNIT_PRICE","dataType":"double"},{"name":"CURRENCY_CODE","dataType":"string"},{"name":"CURRENCY_CONVERSION_RATE","dataType":"double"},{"name":"OE_CURRENCY_CODE","dataType":"string"},{"name":"PO_CURRENCY_CODE","dataType":"string"},{"name":"RSH_CURRENCY_CODE","dataType":"string"},{"name":"ITEM_COST","dataType":"double"},{"name":"ITEM_ADD_BACK_COST","dataType":"double"},{"name":"MATERIAL_COST","dataType":"double"},{"name":"RESOURCE_COST","dataType":"double"},{"name":"MATERIAL_OVERHEAD_COST","dataType":"double"},{"name":"OVERHEAD_COST","dataType":"double"},{"name":"OUTSIDE_PROCESSING_COST","dataType":"double"},{"name":"UNBURDENED_COST","dataType":"double"},{"name":"NOTE_TO_RECEIVER","dataType":"string"},{"name":"DUE_DATE","dataType":"dateTime"},{"name":"PACKING_SLIP","dataType":"string"},{"name":"FREIGHT_CARRIER","dataType":"string"},{"name":"WAYBILL_AIRBILL_NUM","dataType":"string"},{"name":"NUM_OF_CONTAINERS","dataType":"double"},{"name":"SHIPPING_DATE","dataType":"dateTime"},{"name":"FOB","dataType":"string"},{"name":"INSPECTION_STATUS_CODE","dataType":"string"},{"name":"INSPECTON_QUALITY_CODE","dataType":"string"},{"name":"FROM_ORG_CODE","dataType":"string"},{"name":"FROM_OPERATING_UNIT","dataType":"string"},{"name":"FROM_FUNC_CURRENCY_CODE","dataType":"string"},{"name":"ROUTING_NAME","dataType":"string"},{"name":"REASON_CODE","dataType":"string"},{"name":"DESTINATION_CONTEXT","dataType":"string"},{"name":"SUBINVENTORY","dataType":"string"},{"name":"TRANSACTION_CREATION_DATE","dataType":"dateTime"},{"name":"DEFAULT_SUBINVENTORY","dataType":"string"},{"name":"CURRENT_LOCATION","dataType":"string"},{"name":"ORG_CODE","dataType":"string"},{"name":"FUNC_CURRENCY_CODE","dataType":"string"},{"name":"DELIVER_TO_LOCATION","dataType":"string"},{"name":"FISCAL_PERIOD","dataType":"double"},{"name":"FISCAL_QUARTER","dataType":"double"},{"name":"FISCAL_YEAR","dataType":"double"},{"name":"FISCAL_WEEK","dataType":"double"},{"name":"TR_USD_RATE","dataType":"double"},{"name":"FC_USD_RATE","dataType":"double"},{"name":"WIP_ENTITY_NAME","dataType":"string"},{"name":"WIP_DESCRIPTION","dataType":"string"},{"name":"WIP_OPERATION_SEQ_NUM","dataType":"double"},{"name":"WIP_RESOURCE_SEQ_NUM","dataType":"double"},{"name":"QUANTITY_BILLED","dataType":"double"},{"name":"AMOUNT_BILLED","dataType":"double"},{"name":"PO_DESTINATION_TYPE_CODE","dataType":"string"},{"name":"PARENT_TRANSACTION_ID","dataType":"double"},{"name":"TRANSACTION_ID","dataType":"double"},{"name":"INV_TRANSACTION_ID","dataType":"double"},{"name":"PO_HEADER_ID","dataType":"double"},{"name":"PO_LINE_ID","dataType":"double"},{"name":"PO_LINE_LOCATION_ID","dataType":"double"},{"name":"PO_DISTRIBUTION_ID","dataType":"double"},{"name":"REQUISITION_LINE_ID","dataType":"double"},{"name":"SHIPMENT_HEADER_ID","dataType":"double"},{"name":"SHIPMENT_LINE_ID","dataType":"double"},{"name":"ITEM_ID","dataType":"double"},{"name":"FROM_ORGANIZATION_ID","dataType":"double"},{"name":"TO_ORGANIZATION_ID","dataType":"double"},{"name":"OE_ORDER_HEADER_ID","dataType":"double"},{"name":"OE_ORDER_LINE_ID","dataType":"double"},{"name":"WIP_ENTITY_ID","dataType":"double"},{"name":"ROW_CREATION_DATE","dataType":"dateTime"}]},{"$type":"LocalEntity","name":"XXCOH_MP_PO_VIEW","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"XXCOH_MP_PO_VIEW.csv"},"attributes":[{"name":"ASOF_DATE","dataType":"date"},{"name":"ASOF_DATE_DISP","dataType":"dateTime"},{"name":"PO_NUM","dataType":"string"},{"name":"TYPE_LOOKUP_CODE","dataType":"string"},{"name":"DOC_TYPE_NAME","dataType":"string"},{"name":"CLOSED_CODE","dataType":"string"},{"name":"CLOSED_DATE","dataType":"dateTime"},{"name":"SHIP_VIA_LOOKUP_CODE","dataType":"string"},{"name":"CURRENCY_CODE","dataType":"string"},{"name":"RATE_TYPE","dataType":"string"},{"name":"RATE_DATE","dataType":"dateTime"},{"name":"RATE","dataType":"double"},{"name":"START_DATE","dataType":"dateTime"},{"name":"END_DATE","dataType":"dateTime"},{"name":"RELEASE_NUMBER","dataType":"double"},{"name":"RELEASE_DATE","dataType":"dateTime"},{"name":"BLANKET_TOTAL_AMOUNT","dataType":"double"},{"name":"BLANKET_TOTAL_AMOUNT_DISP","dataType":"string"},{"name":"AUTHORIZATION_STATUS","dataType":"string"},{"name":"REVISION_NUM","dataType":"double"},{"name":"REVISED_DATE","dataType":"dateTime"},{"name":"APPROVED_FLAG","dataType":"string"},{"name":"APPROVED_DATE","dataType":"dateTime"},{"name":"AMOUNT_LIMIT","dataType":"double"},{"name":"AMOUNT_LIMIT_DISP","dataType":"string"},{"name":"MIN_RELEASE_AMOUNT","dataType":"double"},{"name":"MIN_RELEASE_AMOUNT_DISP","dataType":"string"},{"name":"PRINT_COUNT","dataType":"double"},{"name":"PRINT_COUNT_DISP","dataType":"string"},{"name":"PRINTED_DATE","dataType":"dateTime"},{"name":"CONFIRMING_ORDER_FLAG","dataType":"string"},{"name":"COMMENTS","dataType":"string"},{"name":"ACCEPTANCE_REQUIRED_FLAG","dataType":"string"},{"name":"ACCEPTANCE_DUE_DATE","dataType":"dateTime"},{"name":"USER_HOLD_FLAG","dataType":"string"},{"name":"CANCEL_FLAG","dataType":"string"},{"name":"FIRM_STATUS_LOOKUP_CODE","dataType":"string"},{"name":"FIRM_DATE","dataType":"dateTime"},{"name":"FROZEN_FLAG","dataType":"string"},{"name":"PAY_ON_CODE","dataType":"string"},{"name":"BUYER","dataType":"string"},{"name":"CAN_PREPARER_APPROVE_FLAG","dataType":"string"},{"name":"SECURITY_LEVEL_CODE","dataType":"string"},{"name":"VENDOR_NAME","dataType":"string"},{"name":"VENDOR_ALTERNATE_NAME","dataType":"string"},{"name":"VENDOR_NUMBER","dataType":"string"},{"name":"VENDOR_INTERNAL","dataType":"string"},{"name":"INTERDIV","dataType":"string"},{"name":"VENDOR_TYPE_1099","dataType":"string"},{"name":"VAT_CODE","dataType":"string"},{"name":"VENDOR_SITE_CODE","dataType":"string"},{"name":"ADDRESS_LINE1","dataType":"string"},{"name":"ADDRESS_LINE2","dataType":"string"},{"name":"ADDRESS_LINE3","dataType":"string"},{"name":"CITY","dataType":"string"},{"name":"STATE","dataType":"string"},{"name":"ZIP","dataType":"string"},{"name":"COUNTRY","dataType":"string"},{"name":"PHONE","dataType":"string"},{"name":"FAX","dataType":"string"},{"name":"VENDOR_CONTACT","dataType":"string"},{"name":"PAYMENT_TERM","dataType":"string"},{"name":"SHIP_TO_LOCATION","dataType":"string"},{"name":"BILL_TO_LOCATION","dataType":"string"},{"name":"ORDER_DATE","dataType":"dateTime"},{"name":"FOB","dataType":"string"},{"name":"FREIGHT","dataType":"string"},{"name":"NOTE_TO_RECEIVER","dataType":"string"},{"name":"NOTE_TO_VENDOR","dataType":"string"},{"name":"FROM_PO_NUM","dataType":"string"},{"name":"FROM_TYPE_LOOKUP_CODE","dataType":"string"},{"name":"HEADER_CREATION_DATE","dataType":"dateTime"},{"name":"LEGAL_ENTITY_ID","dataType":"double"},{"name":"LEGAL_ENTITY","dataType":"string"},{"name":"OPERATING_UNIT_ID","dataType":"double"},{"name":"OPERATING_UNIT","dataType":"string"},{"name":"SET_OF_BOOKS","dataType":"string"},{"name":"FUNC_CURRENCY_CODE","dataType":"string"},{"name":"LINE_NUM","dataType":"double"},{"name":"LINE_TYPE","dataType":"string"},{"name":"ORDER_TYPE_LOOKUP_CODE","dataType":"string"},{"name":"OUTSIDE_OPERATION_FLAG","dataType":"string"},{"name":"RECEIVING_FLAG","dataType":"string"},{"name":"LINE_CREATION_DATE","dataType":"dateTime"},{"name":"ITEM_NUMBER","dataType":"string"},{"name":"ITEM_CATEGORY","dataType":"string"},{"name":"ITEM_DESCRIPTION","dataType":"string"},{"name":"ITEM_REVISION","dataType":"string"},{"name":"PLANNED_ITEM_FLAG","dataType":"string"},{"name":"STOCK_ENABLED_FLAG","dataType":"string"},{"name":"OUTSIDE_OPERATION_UOM_TYPE","dataType":"string"},{"name":"PLANNER_CODE","dataType":"string"},{"name":"MAKE_BUY","dataType":"string"},{"name":"TECHNICAL_BUSINESS_UNIT","dataType":"string"},{"name":"PRODUCT_FAMILY","dataType":"string"},{"name":"PRODUCT_LINE","dataType":"string"},{"name":"COMMODITY","dataType":"string"},{"name":"PRIMARY_ORG","dataType":"string"},{"name":"ORG_TECHNICAL_BUSINESS_UNIT","dataType":"string"},{"name":"ORG_PRODUCT_FAMILY","dataType":"string"},{"name":"ORG_PRODUCT_LINE","dataType":"string"},{"name":"ITEM_CUSTOMER","dataType":"string"},{"name":"BCP_CODE","dataType":"string"},{"name":"ROYALTY","dataType":"string"},{"name":"PREFERRED_GRADE","dataType":"string"},{"name":"VENDOR_PRODUCT_NUM","dataType":"string"},{"name":"UNIT_MEAS_LOOKUP_CODE","dataType":"string"},{"name":"SECONDARY_UNIT_OF_MEASURE","dataType":"string"},{"name":"QUANTITY_COMMITTED","dataType":"double"},{"name":"QUANTITY_COMMITTED_DISP","dataType":"string"},{"name":"COMMITTED_AMOUNT","dataType":"double"},{"name":"COMMITTED_AMOUNT_DISP","dataType":"string"},{"name":"ALLOW_PRICE_OVERRIDE_FLAG","dataType":"string"},{"name":"NOT_TO_EXCEED_PRICE","dataType":"double"},{"name":"NOT_TO_EXCEED_PRICE_DISP","dataType":"string"},{"name":"LIST_PRICE_PER_UNIT","dataType":"double"},{"name":"LIST_PRICE_PER_UNIT_DISP","dataType":"string"},{"name":"UNIT_PRICE","dataType":"double"},{"name":"UNIT_PRICE_DISP","dataType":"string"},{"name":"LINE_QUANTITY","dataType":"double"},{"name":"LINE_QUANTITY_DISP","dataType":"string"},{"name":"LINE_AMOUNT","dataType":"double"},{"name":"LINE_AMOUNT_DISP","dataType":"string"},{"name":"LINE_NOTE_TO_VENDOR","dataType":"string"},{"name":"MIN_ORDER_QUANTITY","dataType":"double"},{"name":"MIN_ORDER_QUANTITY_DISP","dataType":"string"},{"name":"MAX_ORDER_QUANTITY","dataType":"double"},{"name":"MAX_ORDER_QUANTITY_DISP","dataType":"string"},{"name":"QTY_RCV_TOLERANCE","dataType":"double"},{"name":"QTY_RCV_TOLERANCE_DISP","dataType":"string"},{"name":"OVER_TOLERANCE_ERROR_FLAG","dataType":"string"},{"name":"MARKET_PRICE","dataType":"double"},{"name":"MARKET_PRICE_DISP","dataType":"string"},{"name":"UNORDERED_FLAG","dataType":"string"},{"name":"LINE_CANCEL_FLAG","dataType":"string"},{"name":"LINE_CANCEL_DATE","dataType":"dateTime"},{"name":"LINE_CANCELLED_BY","dataType":"double"},{"name":"LINE_CANCEL_REASON","dataType":"string"},{"name":"LINE_CLOSED_FLAG","dataType":"string"},{"name":"LINE_CLOSED_DATE","dataType":"dateTime"},{"name":"LINE_CLOSED_CODE","dataType":"string"},{"name":"LINE_CLOSED_REASON","dataType":"string"},{"name":"LINE_CLOSED_BY","dataType":"double"},{"name":"CONTRACT_NUM","dataType":"string"},{"name":"TAXABLE_FLAG","dataType":"string"},{"name":"TAX_NAME","dataType":"string"},{"name":"TYPE_1099","dataType":"string"},{"name":"CAPITAL_EXPENSE_FLAG","dataType":"string"},{"name":"NEGOTIATED_BY_PREPARER_FLAG","dataType":"string"},{"name":"LINE_MIN_RELEASE_AMOUNT","dataType":"double"},{"name":"LINE_MIN_RELEASE_AMOUNT_DISP","dataType":"string"},{"name":"PRICE_TYPE_LOOKUP_CODE","dataType":"string"},{"name":"PRICE_BREAK_LOOKUP_CODE","dataType":"string"},{"name":"TRANSACTION_REASON_CODE","dataType":"string"},{"name":"QC_GRADE","dataType":"string"},{"name":"BASE_UOM","dataType":"string"},{"name":"BASE_QTY","dataType":"double"},{"name":"BASE_QTY_DISP","dataType":"string"},{"name":"SECONDARY_UOM","dataType":"string"},{"name":"SECONDARY_QTY","dataType":"double"},{"name":"SECONDARY_QTY_DISP","dataType":"string"},{"name":"SECONDARY_QUANTITY","dataType":"double"},{"name":"SECONDARY_QUANTITY_DISP","dataType":"string"},{"name":"EXPIRATION_DATE","dataType":"dateTime"},{"name":"DEFAULT_SUBINVENTORY","dataType":"string"},{"name":"FISCAL_PERIOD_DUE","dataType":"double"},{"name":"FISCAL_QUARTER_DUE","dataType":"double"},{"name":"FISCAL_YEAR_DUE","dataType":"double"},{"name":"FISCAL_WEEK_DUE","dataType":"double"},{"name":"SHIPMENT_NUM","dataType":"double"},{"name":"SHIPMENT_TYPE","dataType":"string"},{"name":"LINE_SHIP_TO_LOCATION","dataType":"string"},{"name":"SHIP_TO_ORG","dataType":"string"},{"name":"SHPMNT_QUANTITY","dataType":"double"},{"name":"SHPMNT_QUANTITY_DISP","dataType":"string"},{"name":"QUANTITY_SHIPPED","dataType":"double"},{"name":"QUANTITY_SHIPPED_DISP","dataType":"string"},{"name":"QUANTITY_ACCEPTED","dataType":"double"},{"name":"QUANTITY_ACCEPTED_DISP","dataType":"string"},{"name":"QUANTITY_RECEIVED","dataType":"double"},{"name":"QUANTITY_RECEIVED_DISP","dataType":"string"},{"name":"QUANTITY_REJECTED","dataType":"double"},{"name":"QUANTITY_REJECTED_DISP","dataType":"string"},{"name":"QUANTITY_DUE","dataType":"double"},{"name":"QUANTITY_DUE_DISP","dataType":"string"},{"name":"PRICE_OVERRIDE","dataType":"double"},{"name":"PRICE_OVERRIDE_DISP","dataType":"string"},{"name":"AMOUNT","dataType":"double"},{"name":"AMOUNT_DISP","dataType":"string"},{"name":"LAST_ACCEPT_DATE","dataType":"dateTime"},{"name":"NEED_BY_DATE","dataType":"dateTime"},{"name":"PROMISED_DATE","dataType":"dateTime"},{"name":"SHPMNT_FIRM_STATUS_LOOKUP_CODE","dataType":"string"},{"name":"LEAD_TIME_UNIT","dataType":"string"},{"name":"INSPECTION_REQUIRED_FLAG","dataType":"string"},{"name":"RECEIPT_REQUIRED_FLAG","dataType":"string"},{"name":"RECEIVE_CLOSE_TOLERANCE","dataType":"double"},{"name":"RECEIVE_CLOSE_TOLERANCE_DISP","dataType":"string"},{"name":"INVOICE_CLOSE_TOLERANCE","dataType":"double"},{"name":"INVOICE_CLOSE_TOLERANCE_DISP","dataType":"string"},{"name":"QTY_RCV_EXCEPTION_CODE","dataType":"string"},{"name":"DAYS_EARLY_RECEIPT_ALLOWED","dataType":"double"},{"name":"DAYS_LATE_RECEIPT_ALLOWED","dataType":"double"},{"name":"RECEIVING_ROUTING_NAME","dataType":"string"},{"name":"ENFORCE_SHIP_TO_LOCATION_CODE","dataType":"string"},{"name":"RECEIPT_DAYS_EXCEPTION_CODE","dataType":"string"},{"name":"ALLOW_SUBSTITUTE_RECEIPTS_FLAG","dataType":"string"},{"name":"SHPMNT_APPROVED_FLAG","dataType":"string"},{"name":"SHPMNT_CANCEL_FLAG","dataType":"string"},{"name":"SHPMNT_CANCEL_DATE","dataType":"dateTime"},{"name":"SHPMNT_CANCEL_REASON","dataType":"string"},{"name":"SHPMNT_CANCELLED_BY","dataType":"double"},{"name":"SHPMNT_CLOSED_CODE","dataType":"string"},{"name":"SHPMNT_STATUS","dataType":"string"},{"name":"SHPMNT_CLOSED_BY","dataType":"double"},{"name":"SHPMNT_CLOSED_DATE","dataType":"dateTime"},{"name":"SHPMNT_CLOSED_REASON","dataType":"string"},{"name":"COUNTRY_OF_ORIGIN","dataType":"string"},{"name":"TAX_USER_OVERRIDE_FLAG","dataType":"string"},{"name":"MATCHING_TYPE","dataType":"string"},{"name":"MATCH_OPTION","dataType":"string"},{"name":"CALCULATE_TAX_FLAG","dataType":"string"},{"name":"SHPMNT_NOTE_TO_RECEIVER","dataType":"string"},{"name":"CHANGE_PROMISED_DATE_REASON","dataType":"string"},{"name":"SHPMNT_SECONDARY_UOM","dataType":"string"},{"name":"SHPMNT_SECONDARY_QUANTITY","dataType":"double"},{"name":"SECONDARY_QUANTITY_RECEIVED","dataType":"double"},{"name":"SECONDARY_QUANTITY_ACCEPTED","dataType":"double"},{"name":"SECONDARY_QUANTITY_REJECTED","dataType":"double"},{"name":"SECONDARY_QUANTITY_CANCELLED","dataType":"double"},{"name":"ITEM_COST","dataType":"double"},{"name":"UNBURDENED_COST","dataType":"double"},{"name":"PRICE_VARIANCE","dataType":"double"},{"name":"ON_LINE_REQ","dataType":"string"},{"name":"CHARGE_ENTITY","dataType":"string"},{"name":"CHARGE_DEPT","dataType":"string"},{"name":"CHARGE_ACCT","dataType":"string"},{"name":"CHARGE_PROJ","dataType":"string"},{"name":"CHARGE_IC","dataType":"string"},{"name":"CHARGE_TBD","dataType":"string"},{"name":"VARIANCE_ENTITY","dataType":"string"},{"name":"VARIANCE_DEPT","dataType":"string"},{"name":"VARIANCE_ACCT","dataType":"string"},{"name":"VARIANCE_IC","dataType":"string"},{"name":"VARIANCE_PROJ","dataType":"string"},{"name":"VARIANCE_TBD","dataType":"string"},{"name":"ACCRUAL_ENTITY","dataType":"string"},{"name":"ACCRUAL_DEPT","dataType":"string"},{"name":"ACCRUAL_ACCT","dataType":"string"},{"name":"ACCRUAL_IC","dataType":"string"},{"name":"ACCRUAL_PROJ","dataType":"string"},{"name":"ACCRUAL_TBD","dataType":"string"},{"name":"QUANTITY_ORDERED","dataType":"double"},{"name":"QUANTITY_DELIVERED","dataType":"double"},{"name":"QUANTITY_BILLED","dataType":"double"},{"name":"QUANTITY_CANCELLED","dataType":"double"},{"name":"REQ_HEADER_REFERENCE_NUM","dataType":"string"},{"name":"REQ_LINE_REFERENCE_NUM","dataType":"double"},{"name":"AMOUNT_BILLED","dataType":"double"},{"name":"ACCRUED_FLAG","dataType":"string"},{"name":"FAILED_FUNDS_LOOKUP_CODE","dataType":"string"},{"name":"GL_CANCELLED_DATE","dataType":"dateTime"},{"name":"DESTINATION_TYPE_CODE","dataType":"string"},{"name":"DESTINATION_ORG","dataType":"string"},{"name":"DESTINATION_SUBINVENTORY","dataType":"string"},{"name":"DESTINATION_CONTEXT","dataType":"string"},{"name":"DISTRIBUTION_NUM","dataType":"double"},{"name":"EXPENDITURE_TYPE","dataType":"string"},{"name":"EXPENDITURE_ORGANIZATION_ID","dataType":"double"},{"name":"GL_CLOSED_DATE","dataType":"dateTime"},{"name":"ACCRUE_ON_RECEIPT_FLAG","dataType":"string"},{"name":"EXPENDITURE_ITEM_DATE","dataType":"dateTime"},{"name":"END_ITEM_UNIT_NUMBER","dataType":"string"},{"name":"TAX_RECOVERY_OVERRIDE_FLAG","dataType":"string"},{"name":"RECOVERABLE_TAX","dataType":"double"},{"name":"NONRECOVERABLE_TAX","dataType":"double"},{"name":"RECOVERY_RATE","dataType":"double"},{"name":"USD_RATE","dataType":"double"},{"name":"FUNC_USD_RATE","dataType":"double"},{"name":"REQUESTOR","dataType":"string"},{"name":"ACCEPTANCE_ACTION","dataType":"string"},{"name":"ACCEPTANCE_REVISION_NUM","dataType":"double"},{"name":"ACCEPTANCE_ACTION_DATE","dataType":"dateTime"},{"name":"ACCEPTANCE_FULL_NAME","dataType":"string"},{"name":"ACCEPTANCE_ACCEPTED_FLAG","dataType":"string"},{"name":"ACCEPTANCE_TYPE","dataType":"string"},{"name":"PO_HEADER_ID","dataType":"double"},{"name":"PO_LINE_ID","dataType":"double"},{"name":"LINE_LOCATION_ID","dataType":"double"},{"name":"PO_DISTRIBUTION_ID","dataType":"double"},{"name":"WIP_ENTITY_ID","dataType":"double"},{"name":"PROJECT_NUMBER","dataType":"string"},{"name":"PROJECT_NAME","dataType":"string"},{"name":"PROJECT_ID","dataType":"double"},{"name":"END_ASSEMBLY_PEGGING","dataType":"string"},{"name":"RELEASE_CLOSED_CODE","dataType":"string"},{"name":"RELEASE_AUTHORIZATION_STATUS","dataType":"string"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"ORGANIZATION_ID","dataType":"double"},{"name":"ROW_CREATION_DATE","dataType":"dateTime"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-04-13T09:43:40.631366+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/238d817d-4dd8-4196-99ff-688e83f7a240/XXCOH_MP_PO_VIEW.csv?snapshot=2022-04-13T09%3A43%3A40.5955073Z"}]},{"$type":"LocalEntity","name":"XXREP_MFG_BLANKET_AGREEMENT_V","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"XXREP_MFG_BLANKET_AGREEMENT_V.csv"},"attributes":[{"name":"EXTRACT_DATE","dataType":"date"},{"name":"SEGMENT1","dataType":"string"},{"name":"REVISION_NUM","dataType":"double"},{"name":"LINE_NUM","dataType":"double"},{"name":"VENDOR_ID","dataType":"double"},{"name":"VENDOR_SITE_ID","dataType":"double"},{"name":"AGENT_ID","dataType":"double"},{"name":"BUYER_NAME","dataType":"string"},{"name":"GLOBAL_AGREEMENT_FLAG","dataType":"string"},{"name":"ITEM_REVISION","dataType":"string"},{"name":"SHIP_TO_LOCATION","dataType":"string"},{"name":"CURRENCY_CODE","dataType":"string"},{"name":"RATE_DATE","dataType":"dateTime"},{"name":"RATE_TYPE","dataType":"string"},{"name":"START_DATE","dataType":"dateTime"},{"name":"BLANKET_EXPIRATION_DATE","dataType":"date"},{"name":"PO_HEADER_ID","dataType":"double"},{"name":"BLANKET_ITEM_REVISION","dataType":"string"},{"name":"VENDOR_NAME","dataType":"string"},{"name":"VENDOR_SITE_CODE","dataType":"string"},{"name":"ITEM_DESCRIPTION","dataType":"string"},{"name":"BLANKET_UNIT_OF_MEASURE","dataType":"string"},{"name":"BLANKET_FIRST_APPROVED_DATE","dataType":"dateTime"},{"name":"FIRST_APPROVED_DATE","dataType":"dateTime"},{"name":"BLANKET_OPEN_FLAG","dataType":"string"},{"name":"QUANTITY_RELEASED","dataType":"double"},{"name":"QUANTITY_COMMITTED","dataType":"double"},{"name":"CREATION_DATE","dataType":"dateTime"},{"name":"UNIT_PRICE","dataType":"double"},{"name":"ITEM_NUMBER","dataType":"string"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"APPROVED_DATE","dataType":"dateTime"},{"name":"BLANKET_AUTHORIZATION_STATUS","dataType":"string"},{"name":"LAST_UPDATE_DATE","dataType":"dateTime"},{"name":"PO_LINE_ID","dataType":"double"},{"name":"PLANNER_CODE","dataType":"string"},{"name":"AMOUNT_LIMIT","dataType":"double"},{"name":"CANCEL_DATE","dataType":"dateTime"},{"name":"CLOSED_DATE","dataType":"dateTime"},{"name":"BLANKET_AGE_DAYS","dataType":"double"},{"name":"BLANKET_EXPIRED_FLAG","dataType":"string"},{"name":"ASL_KEY","dataType":"string"},{"name":"USED_IN_ASL_FLAG","dataType":"string"},{"name":"FUNCTIONAL_RATE","dataType":"double"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-04-13T09:36:45.6826497+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/238d817d-4dd8-4196-99ff-688e83f7a240/XXREP_MFG_BLANKET_AGREEMENT_V.csv?snapshot=2022-04-13T09%3A36%3A45.6659338Z"}]},{"$type":"LocalEntity","name":"XXCOH_BACKLOG_FLASH_CUR_PRD_V","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"XXCOH_BACKLOG_FLASH_CUR_PRD_V.csv"},"attributes":[{"name":"AGREEMENT_NUMBER","dataType":"string"},{"name":"APPLICATION_CODE","dataType":"string"},{"name":"APPLICATION_CODE_DESC","dataType":"string"},{"name":"ASP_QUANTITY","dataType":"double"},{"name":"ASOF_DATE","dataType":"date"},{"name":"BACKLOG_QUANTITY","dataType":"double"},{"name":"BOOKED_DATE","dataType":"dateTime"},{"name":"BUSINESS_SEGMENT","dataType":"string"},{"name":"COMMODITY","dataType":"string"},{"name":"COMMODITY_GROUP","dataType":"string"},{"name":"CONVERSION_FLAG","dataType":"string"},{"name":"CREATED_BY","dataType":"string"},{"name":"CUSTOMER_NAME","dataType":"string"},{"name":"CUSTOMER_NAME_REPORTING","dataType":"string"},{"name":"CUSTOMER_NUMBER","dataType":"string"},{"name":"CUSTOMER_MASTER","dataType":"string"},{"name":"CUSTOMER_PO","dataType":"string"},{"name":"DATE_CREATED","dataType":"dateTime"},{"name":"DPAS","dataType":"string"},{"name":"EXTENDED_AMOUNT","dataType":"double"},{"name":"EXTENDED_AMOUNT_USD","dataType":"double"},{"name":"EXTENDED_COST_USD","dataType":"double"},{"name":"FIN_BACKLOG_ROLLUP","dataType":"string"},{"name":"FIN_BACKLOG_STATUS","dataType":"string"},{"name":"FIN_CORP_MARKET","dataType":"string"},{"name":"FIN_ENTITY","dataType":"string"},{"name":"FIN_FORECAST_FIELD","dataType":"string"},{"name":"FIN_MGMT_MARKET","dataType":"string"},{"name":"FIN_PRODUCT_GROUP","dataType":"string"},{"name":"FIN_PRODUCT_FAMILY","dataType":"string"},{"name":"FIN_SITE","dataType":"string"},{"name":"FIN_UNIT","dataType":"double"},{"name":"FISCAL_PERIOD","dataType":"double"},{"name":"FISCAL_PERIOD_NAME","dataType":"string"},{"name":"FOB","dataType":"string"},{"name":"FORECAST_FIELD","dataType":"string"},{"name":"FREIGHT_TERM","dataType":"string"},{"name":"FISCAL_QTR","dataType":"double"},{"name":"FY_QTR","dataType":"string"},{"name":"HOLD_STATUS","dataType":"string"},{"name":"HOLD_REASON","dataType":"string"},{"name":"IMPORTER_OF_RECORD","dataType":"string"},{"name":"ITEM_DESCRIPTION","dataType":"string"},{"name":"ITEM_NUMBER","dataType":"string"},{"name":"ITEM_UNIT_COST_USD","dataType":"double"},{"name":"MARKET_SEGMENT","dataType":"string"},{"name":"OPERATING_UNIT","dataType":"string"},{"name":"OPERATING_UNIT_ID","dataType":"double"},{"name":"ORDER_LINE","dataType":"string"},{"name":"ORDER_NUMBER","dataType":"double"},{"name":"ORDER_SOURCE","dataType":"string"},{"name":"ORG_FORECAST_FIELD","dataType":"string"},{"name":"ORG_PRODUCT_FAMILY","dataType":"string"},{"name":"ORG_TECHNICAL_BUSINESS_UNIT","dataType":"string"},{"name":"PRODUCT_FAMILY","dataType":"string"},{"name":"PAYMENT_TERM","dataType":"string"},{"name":"PROJECT_NUMBER","dataType":"string"},{"name":"PRODUCT_LINE","dataType":"string"},{"name":"PROMISE_SHIP_DATE","dataType":"dateTime"},{"name":"REGIONAL_LOCATION","dataType":"string"},{"name":"REPORTING_ENTITY","dataType":"string"},{"name":"REQUEST_SHIP_DATE","dataType":"dateTime"},{"name":"REVENUE_ACCOUNT","dataType":"string"},{"name":"SALES_CHANNEL","dataType":"string"},{"name":"SALESPERSON","dataType":"string"},{"name":"SCHEDULE_CATEGORY","dataType":"string"},{"name":"SCHEDULE_CATEGORY_PERIOD","dataType":"string"},{"name":"SCHEDULE_CATEGORY_PERIOD_NUMBER","dataType":"string"},{"name":"SCHEDULE_SHIP_DATE","dataType":"dateTime"},{"name":"SHIP_TO_CITY","dataType":"string"},{"name":"SHIP_TO_COUNTRY","dataType":"string"},{"name":"SHIP_TO_POSTAL_CODE","dataType":"string"},{"name":"SHIP_TO_PROVINCE","dataType":"string"},{"name":"SHIP_TO_STATE","dataType":"string"},{"name":"SO_LINE_TYPE","dataType":"string"},{"name":"SOURCE","dataType":"string"},{"name":"SUBINVENTORY","dataType":"string"},{"name":"TECHNICAL_BUSINESS_UNIT","dataType":"string"},{"name":"TR_EXTENDED_AMOUNT","dataType":"double"},{"name":"TRANSACTION_CURRENCY","dataType":"string"},{"name":"UNIT_LIST_PRICE_USD","dataType":"double"},{"name":"WAREHOUSE","dataType":"string"},{"name":"LEDGER_ID","dataType":"double"},{"name":"BCK_KEY","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-04-13T09:36:48.3631402+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/238d817d-4dd8-4196-99ff-688e83f7a240/XXCOH_BACKLOG_FLASH_CUR_PRD_V.csv?snapshot=2022-04-13T09%3A36%3A48.3484176Z"}]},{"$type":"LocalEntity","name":"XXCOH_BACKLOG_FLASH_PREV_PRD_V","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"XXCOH_BACKLOG_FLASH_PREV_PRD_V.csv"},"attributes":[{"name":"AGREEMENT_NUMBER","dataType":"string"},{"name":"APPLICATION_CODE","dataType":"string"},{"name":"APPLICATION_CODE_DESC","dataType":"string"},{"name":"ASP_QUANTITY","dataType":"double"},{"name":"ASOF_DATE","dataType":"date"},{"name":"BACKLOG_QUANTITY","dataType":"double"},{"name":"BOOKED_DATE","dataType":"dateTime"},{"name":"BUSINESS_SEGMENT","dataType":"string"},{"name":"COMMODITY","dataType":"string"},{"name":"COMMODITY_GROUP","dataType":"string"},{"name":"CONVERSION_FLAG","dataType":"string"},{"name":"CREATED_BY","dataType":"string"},{"name":"CUSTOMER_NAME","dataType":"string"},{"name":"CUSTOMER_NAME_REPORTING","dataType":"string"},{"name":"CUSTOMER_NUMBER","dataType":"string"},{"name":"CUSTOMER_MASTER","dataType":"string"},{"name":"CUSTOMER_PO","dataType":"string"},{"name":"DATE_CREATED","dataType":"dateTime"},{"name":"DPAS","dataType":"string"},{"name":"EXTENDED_AMOUNT","dataType":"double"},{"name":"EXTENDED_AMOUNT_USD","dataType":"double"},{"name":"EXTENDED_COST_USD","dataType":"double"},{"name":"FIN_BACKLOG_ROLLUP","dataType":"string"},{"name":"FIN_BACKLOG_STATUS","dataType":"string"},{"name":"FIN_CORP_MARKET","dataType":"string"},{"name":"FIN_ENTITY","dataType":"string"},{"name":"FIN_FORECAST_FIELD","dataType":"string"},{"name":"FIN_MGMT_MARKET","dataType":"string"},{"name":"FIN_PRODUCT_GROUP","dataType":"string"},{"name":"FIN_PRODUCT_FAMILY","dataType":"string"},{"name":"FIN_SITE","dataType":"string"},{"name":"FIN_UNIT","dataType":"double"},{"name":"FISCAL_PERIOD","dataType":"double"},{"name":"FISCAL_PERIOD_NAME","dataType":"string"},{"name":"FOB","dataType":"string"},{"name":"FORECAST_FIELD","dataType":"string"},{"name":"FREIGHT_TERM","dataType":"string"},{"name":"FISCAL_QTR","dataType":"double"},{"name":"FY_QTR","dataType":"string"},{"name":"HOLD_STATUS","dataType":"string"},{"name":"HOLD_REASON","dataType":"string"},{"name":"IMPORTER_OF_RECORD","dataType":"string"},{"name":"ITEM_DESCRIPTION","dataType":"string"},{"name":"ITEM_NUMBER","dataType":"string"},{"name":"ITEM_UNIT_COST_USD","dataType":"double"},{"name":"MARKET_SEGMENT","dataType":"string"},{"name":"OPERATING_UNIT","dataType":"string"},{"name":"OPERATING_UNIT_ID","dataType":"double"},{"name":"ORDER_LINE","dataType":"string"},{"name":"ORDER_NUMBER","dataType":"double"},{"name":"ORDER_SOURCE","dataType":"string"},{"name":"ORG_FORECAST_FIELD","dataType":"string"},{"name":"ORG_PRODUCT_FAMILY","dataType":"string"},{"name":"ORG_TECHNICAL_BUSINESS_UNIT","dataType":"string"},{"name":"PRODUCT_FAMILY","dataType":"string"},{"name":"PAYMENT_TERM","dataType":"string"},{"name":"PROJECT_NUMBER","dataType":"string"},{"name":"PRODUCT_LINE","dataType":"string"},{"name":"PROMISE_SHIP_DATE","dataType":"dateTime"},{"name":"REGIONAL_LOCATION","dataType":"string"},{"name":"REPORTING_ENTITY","dataType":"string"},{"name":"REQUEST_SHIP_DATE","dataType":"dateTime"},{"name":"REVENUE_ACCOUNT","dataType":"string"},{"name":"SALES_CHANNEL","dataType":"string"},{"name":"SALESPERSON","dataType":"string"},{"name":"SCHEDULE_CATEGORY","dataType":"string"},{"name":"SCHEDULE_CATEGORY_PERIOD","dataType":"string"},{"name":"SCHEDULE_CATEGORY_PERIOD_NUMBER","dataType":"string"},{"name":"SCHEDULE_SHIP_DATE","dataType":"dateTime"},{"name":"SHIP_TO_CITY","dataType":"string"},{"name":"SHIP_TO_COUNTRY","dataType":"string"},{"name":"SHIP_TO_POSTAL_CODE","dataType":"string"},{"name":"SHIP_TO_PROVINCE","dataType":"string"},{"name":"SHIP_TO_STATE","dataType":"string"},{"name":"SO_LINE_TYPE","dataType":"string"},{"name":"SOURCE","dataType":"string"},{"name":"SUBINVENTORY","dataType":"string"},{"name":"TECHNICAL_BUSINESS_UNIT","dataType":"string"},{"name":"TR_EXTENDED_AMOUNT","dataType":"double"},{"name":"TRANSACTION_CURRENCY","dataType":"string"},{"name":"UNIT_LIST_PRICE_USD","dataType":"double"},{"name":"WAREHOUSE","dataType":"string"},{"name":"LEDGER_ID","dataType":"double"},{"name":"BCK_KEY","dataType":"string"}]},{"$type":"LocalEntity","name":"XXCOH_MI_INVENTORY","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"XXCOH_MI_INVENTORY.csv"},"attributes":[{"name":"ASOF_DATE","dataType":"date"},{"name":"ASOF_DATE_DISP","dataType":"dateTime"},{"name":"DATA_SOURCE","dataType":"string"},{"name":"ITEM_NUMBER","dataType":"string"},{"name":"ITEM_DESCRIPTION","dataType":"string"},{"name":"ITEM_REV","dataType":"string"},{"name":"REV_EFF_DATE","dataType":"dateTime"},{"name":"AGILE_LIFE_PHASE","dataType":"string"},{"name":"OWNING_ORGANIZATION","dataType":"string"},{"name":"SUBINVENTORY","dataType":"string"},{"name":"LOC_BIN","dataType":"string"},{"name":"QUANTITY","dataType":"double"},{"name":"PRIMARY_UOM_CODE","dataType":"string"},{"name":"LOT_NUMBER","dataType":"string"},{"name":"PLANNER_CODE","dataType":"string"},{"name":"PLANNING_MAKE_BUY_CODE","dataType":"string"},{"name":"BUYER","dataType":"string"},{"name":"ITEM_COST","dataType":"double"},{"name":"ITEM_ADD_BACK_COST","dataType":"double"},{"name":"G_ITEM_COST","dataType":"double"},{"name":"F_ITEM_COST","dataType":"double"},{"name":"PD_ITEM_COST","dataType":"double"},{"name":"BASE_CURRENCY","dataType":"string"},{"name":"EXTENDED_VALUE","dataType":"double"},{"name":"G_EXTENDED_VALUE","dataType":"double"},{"name":"F_EXTENDED_VALUE","dataType":"double"},{"name":"EXTENDED_VALUE_USD","dataType":"double"},{"name":"G_EXTENDED_VALUE_USD","dataType":"double"},{"name":"F_EXTENDED_VALUE_USD","dataType":"double"},{"name":"USD_RATE","dataType":"double"},{"name":"EXT_ITEM_COST_USD","dataType":"double"},{"name":"G_EXT_ITEM_COST_USD","dataType":"double"},{"name":"F_EXT_ITEM_COST_USD","dataType":"double"},{"name":"EXT_MATERIAL_COST_USD","dataType":"double"},{"name":"G_EXT_MATERIAL_COST_USD","dataType":"double"},{"name":"F_EXT_MATERIAL_COST_USD","dataType":"double"},{"name":"EXT_MATERIAL_OH_COST_USD","dataType":"double"},{"name":"G_EXT_MATERIAL_OH_COST_USD","dataType":"double"},{"name":"F_EXT_MATERIAL_OH_COST_USD","dataType":"double"},{"name":"EXT_RESOURCE_COST_USD","dataType":"double"},{"name":"G_EXT_RESOURCE_COST_USD","dataType":"double"},{"name":"F_EXT_RESOURCE_COST_USD","dataType":"double"},{"name":"EXT_OVERHEAD_COST_USD","dataType":"double"},{"name":"G_EXT_OVERHEAD_COST_USD","dataType":"double"},{"name":"F_EXT_OVERHEAD_COST_USD","dataType":"double"},{"name":"EXT_OS_PROCESSING_COST_USD","dataType":"double"},{"name":"G_EXT_OS_PROCESSING_COST_USD","dataType":"double"},{"name":"F_EXT_OS_PROCESSING_COST_USD","dataType":"double"},{"name":"PD_EXTENDED_VALUE","dataType":"double"},{"name":"PD_EXTENDED_VALUE_USD","dataType":"double"},{"name":"PD_EXT_ITEM_COST_USD","dataType":"double"},{"name":"PD_EXT_MATERIAL_COST_USD","dataType":"double"},{"name":"PD_EXT_MATERIAL_OH_COST_USD","dataType":"double"},{"name":"PD_EXT_RESOURCE_COST_USD","dataType":"double"},{"name":"PD_EXT_OVERHEAD_COST_USD","dataType":"double"},{"name":"PD_EXT_OS_PROCESSING_COST_USD","dataType":"double"},{"name":"MAX_MINMAX_QUANTITY","dataType":"double"},{"name":"MIN_MINMAX_QUANTITY","dataType":"double"},{"name":"MINIMUM_ORDER_QUANTITY","dataType":"double"},{"name":"FIXED_LOT_MULTIPLIER","dataType":"double"},{"name":"DATE_IN","dataType":"dateTime"},{"name":"DATE_LAST_ACTIVITY","dataType":"dateTime"},{"name":"LOCATOR","dataType":"string"},{"name":"LOC_SUBINV","dataType":"string"},{"name":"LOC_ROW","dataType":"string"},{"name":"LOC_RACK","dataType":"string"},{"name":"LOC_SHELF","dataType":"string"},{"name":"SUBINV_ASSET_FLAG","dataType":"string"},{"name":"SUBINV_QUANTITY_TRACKED_FLAG","dataType":"string"},{"name":"SUBINV_NETTABLE_FLAG","dataType":"string"},{"name":"SUBINV_LOCATOR_TYPE","dataType":"string"},{"name":"MATERIAL_ENTITY","dataType":"string"},{"name":"MATERIAL_DEPT","dataType":"string"},{"name":"MATERIAL_ACCT","dataType":"string"},{"name":"MATERIAL_OH_ENTITY","dataType":"string"},{"name":"MATERIAL_OH_DEPT","dataType":"string"},{"name":"MATERIAL_OH_ACCT","dataType":"string"},{"name":"RESOURCE_ENTITY","dataType":"string"},{"name":"RESOURCE_DEPT","dataType":"string"},{"name":"RESOURCE_ACCT","dataType":"string"},{"name":"OVERHEAD_ENTITY","dataType":"string"},{"name":"OVERHEAD_DEPT","dataType":"string"},{"name":"OVERHEAD_ACCT","dataType":"string"},{"name":"OS_PROCESS_ENTITY","dataType":"string"},{"name":"OS_PROCESS_DEPT","dataType":"string"},{"name":"OS_PROCESS_ACCT","dataType":"string"},{"name":"EXPENSE_ENTITY","dataType":"string"},{"name":"EXPENSE_DEPT","dataType":"string"},{"name":"EXPENSE_ACCT","dataType":"string"},{"name":"BOM_ITEM_TYPE","dataType":"string"},{"name":"BOM_ENABLED_FLAG","dataType":"string"},{"name":"BUILD_IN_WIP_FLAG","dataType":"string"},{"name":"COSTING_ENABLED_FLAG","dataType":"string"},{"name":"CREATE_SUPPLY_FLAG","dataType":"string"},{"name":"CUSTOMER_ORDER_ENABLED_FLAG","dataType":"string"},{"name":"CUSTOMER_ORDER_FLAG","dataType":"string"},{"name":"CYCLE_COUNT_ENABLED_FLAG","dataType":"string"},{"name":"INSPECTION_REQUIRED_FLAG","dataType":"string"},{"name":"INVENTORY_ASSET_FLAG","dataType":"string"},{"name":"INVENTORY_ITEM_FLAG","dataType":"string"},{"name":"MUST_USE_APPROVED_VENDOR_FLAG","dataType":"string"},{"name":"PURCHASING_ENABLED_FLAG","dataType":"string"},{"name":"PURCHASING_ITEM_FLAG","dataType":"string"},{"name":"ITEM_TYPE_CODE","dataType":"string"},{"name":"ITEM_CATALOG_GROUP","dataType":"string"},{"name":"ITEM_TYPE","dataType":"string"},{"name":"MAXIMUM_ORDER_QUANTITY","dataType":"double"},{"name":"FIXED_ORDER_QUANTITY","dataType":"double"},{"name":"FIXED_DAYS_SUPPLY","dataType":"double"},{"name":"SHRINKAGE_RATE","dataType":"double"},{"name":"ACCEPTABLE_EARLY_DAYS","dataType":"double"},{"name":"LEAD_TIME_LOT_SIZE","dataType":"double"},{"name":"PREPROCESSING_LEAD_TIME","dataType":"double"},{"name":"POSTPROCESSING_LEAD_TIME","dataType":"double"},{"name":"FIXED_LEAD_TIME","dataType":"double"},{"name":"VARIABLE_LEAD_TIME","dataType":"double"},{"name":"CUM_MANUFACTURING_LEAD_TIME","dataType":"double"},{"name":"CUMULATIVE_TOTAL_LEAD_TIME","dataType":"double"},{"name":"FULL_LEAD_TIME","dataType":"double"},{"name":"SUPPLY_SOURCE","dataType":"string"},{"name":"DEMAND_SOURCE","dataType":"string"},{"name":"COST_SOURCE_TYPE","dataType":"string"},{"name":"TECHNICAL_BUSINESS_UNIT","dataType":"string"},{"name":"PRODUCT_FAMILY","dataType":"string"},{"name":"PRODUCT_LINE","dataType":"string"},{"name":"FORECAST_FIELD","dataType":"string"},{"name":"LEAD_TIME_CATEGORY","dataType":"string"},{"name":"COMMODITY","dataType":"string"},{"name":"PRIMARY_ORG","dataType":"string"},{"name":"ORG_TECHNICAL_BUSINESS_UNIT","dataType":"string"},{"name":"ORG_PRODUCT_FAMILY","dataType":"string"},{"name":"ORG_PRODUCT_LINE","dataType":"string"},{"name":"ORG_FORECAST_FIELD","dataType":"string"},{"name":"BACKUP_CATEGORY","dataType":"string"},{"name":"ITEM_CUSTOMER","dataType":"string"},{"name":"BCP_CODE","dataType":"string"},{"name":"ROYALTY","dataType":"string"},{"name":"PLANNING_GREEN_SUPPLY_STATUS","dataType":"string"},{"name":"PLANNING_ACTION","dataType":"string"},{"name":"PLANNING_FAMILY_UNIQUE","dataType":"string"},{"name":"OPERATIONS_REPORTING","dataType":"string"},{"name":"SEC_REPORTING","dataType":"string"},{"name":"MATERIAL_COST","dataType":"double"},{"name":"MATERIAL_OVERHEAD_COST","dataType":"double"},{"name":"RESOURCE_COST","dataType":"double"},{"name":"OVERHEAD_COST","dataType":"double"},{"name":"OUTSIDE_PROCESSING_COST","dataType":"double"},{"name":"G_MATERIAL_COST","dataType":"double"},{"name":"G_MATERIAL_OVERHEAD_COST","dataType":"double"},{"name":"G_OUTSIDE_PROCESSING_COST","dataType":"double"},{"name":"G_OVERHEAD_COST","dataType":"double"},{"name":"G_RESOURCE_COST","dataType":"double"},{"name":"F_MATERIAL_COST","dataType":"double"},{"name":"F_MATERIAL_OVERHEAD_COST","dataType":"double"},{"name":"F_RESOURCE_COST","dataType":"double"},{"name":"F_OVERHEAD_COST","dataType":"double"},{"name":"F_OUTSIDE_PROCESSING_COST","dataType":"double"},{"name":"PD_MATERIAL_COST","dataType":"double"},{"name":"PD_MATERIAL_OVERHEAD_COST","dataType":"double"},{"name":"PD_RESOURCE_COST","dataType":"double"},{"name":"PD_OVERHEAD_COST","dataType":"double"},{"name":"PD_OUTSIDE_PROCESSING_COST","dataType":"double"},{"name":"FISCAL_PERIOD","dataType":"double"},{"name":"FISCAL_QUARTER","dataType":"double"},{"name":"FISCAL_YEAR","dataType":"double"},{"name":"FISCAL_WEEK","dataType":"double"},{"name":"FISCAL_SYSDATE_GEN","dataType":"date"},{"name":"LEGAL_ENTITY","dataType":"string"},{"name":"OPERATING_UNIT","dataType":"string"},{"name":"SET_OF_BOOKS","dataType":"string"},{"name":"ORG_LOCATION_CODE","dataType":"string"},{"name":"REGION_1","dataType":"string"},{"name":"TOWN_OR_CITY","dataType":"string"},{"name":"SITE","dataType":"string"},{"name":"REPORTING_TBU","dataType":"string"},{"name":"SOURCE_ID","dataType":"double"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"ORGANIZATION_ID","dataType":"double"},{"name":"COST_GROUP_ID","dataType":"double"},{"name":"LOCATOR_ID","dataType":"double"},{"name":"OPERATING_UNIT_ID","dataType":"double"},{"name":"LEGAL_ENTITY_ID","dataType":"double"},{"name":"ROW_CREATION_DATE","dataType":"dateTime"}]}]}