{"name":"DF_FISCAL_CALENDAR_DAYS","description":"Fiscal Calendar von Snowflake\nPROD_DB/APPS/XX_FISCAL_DAYS_VIEW","version":"1.0","culture":"en-US","modifiedTime":"2022-04-14T05:28:36.355114+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"XX_FISCAL_DAYS_VIEW":{"queryId":"61a9ad43-dff1-4ba7-a040-4599a1bd9d8b","queryName":"XX_FISCAL_DAYS_VIEW","loadEnabled":true}},"document":"section Section1;\r\nshared XX_FISCAL_DAYS_VIEW = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  #\"Navigation 1\" = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 3\" = #\"Navigation 2\"{[Name = \"XX_FISCAL_DAYS_VIEW\", Kind = \"View\"]}[Data],\r\n  #\"Calculated date\" = Table.TransformColumns(#\"Navigation 3\", {{\"CAL_DAY\", each DateTime.Date(_), type nullable date}}),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Calculated date\", {{\"FISCAL_WEEK_NO\", Int64.Type}, {\"FISCAL_MONTH_WEEK_NO\", Int64.Type}, {\"FISCAL_QTR_WEEK_NO\", Int64.Type}, {\"PERIOD_YEAR\", Int64.Type}, {\"QUARTER_NUM\", Int64.Type}, {\"PERIOD_NUM\", Int64.Type}, {\"FISCAL_DAY\", Int64.Type}, {\"FC_PERIOD_ID\", Int64.Type}, {\"FC_QUARTER_ID\", Int64.Type}, {\"FC_WEEK_ID\", Int64.Type}, {\"FC_YEAR_OFFSET\", Int64.Type}, {\"FC_QUARTER_OFFSET\", Int64.Type}, {\"FC_PERIOD_OFFSET\", Int64.Type}, {\"FC_WEEK_OFFSET\", Int64.Type}, {\"FC_DAYS_OFFSET\", Int64.Type}, {\"CALENDAR_YEAR\", Int64.Type}, {\"CALENDAR_MONTH\", Int64.Type}, {\"CALENDAR_YEARMONTHID\", Int64.Type}, {\"CALENDAR_ISO_WEEK\", Int64.Type}, {\"CALENDAR_US_WEEK\", Int64.Type}, {\"CALENDAR_YEAR_SHORT\", Int64.Type}, {\"DAY_OF_WEEK\", Int64.Type}, {\"WORKING_DAY_FLAG\", Int64.Type}, {\"FISCAL_WEEK_INDICATOR_SORT\", Int64.Type}, {\"FISCAL_MONTH_INDICATOR_SORT\", Int64.Type}, {\"FISCAL_QUARTER_INDICATOR_SORT\", Int64.Type}, {\"FISCAL_YEAR_INDICATOR_SORT\", Int64.Type}})\r\nin\r\n  #\"Changed column type\";\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"XX_FISCAL_DAYS_VIEW","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"XX_FISCAL_DAYS_VIEW.csv"},"attributes":[{"name":"PERIOD_SET_NAME","dataType":"string"},{"name":"CAL_DAY","dataType":"date"},{"name":"FISCAL_WEEK","dataType":"string"},{"name":"FISCAL_YEAR_WEEK","dataType":"string"},{"name":"FISCAL_WEEK_DISP","dataType":"string"},{"name":"FISCAL_MONTH_SORT_VALUE","dataType":"string"},{"name":"FISCAL_QUARTER_DISP","dataType":"string"},{"name":"FISCAL_WEEK_NO","dataType":"int64"},{"name":"FISCAL_MONTH_WEEK_NO","dataType":"int64"},{"name":"FISCAL_QTR_WEEK","dataType":"string"},{"name":"FISCAL_QTR_WEEK_NO","dataType":"int64"},{"name":"GL_PERIOD","dataType":"string"},{"name":"PQ_LAST_GL_PERIOD","dataType":"string"},{"name":"PERIOD_YEAR","dataType":"int64"},{"name":"FISCAL_YEAR","dataType":"string"},{"name":"QUARTER_NUM","dataType":"int64"},{"name":"FISCAL_QUARTER","dataType":"string"},{"name":"FYFQ","dataType":"string"},{"name":"PRIOR_FYFQ","dataType":"string"},{"name":"PERIOD_NAME","dataType":"string"},{"name":"PERIOD_NUM","dataType":"int64"},{"name":"FISCAL_DAY","dataType":"int64"},{"name":"WEEK_START_DATE","dataType":"dateTime"},{"name":"WEEK_END_DATE","dataType":"dateTime"},{"name":"PERIOD_START_DATE","dataType":"dateTime"},{"name":"PERIOD_END_DATE","dataType":"dateTime"},{"name":"QUARTER_START_DATE","dataType":"dateTime"},{"name":"QUARTER_END_DATE","dataType":"dateTime"},{"name":"YEAR_START_DATE","dataType":"dateTime"},{"name":"YEAR_END_DATE","dataType":"dateTime"},{"name":"PERIOD_MONTH","dataType":"string"},{"name":"FC_PERIOD_ID","dataType":"int64"},{"name":"FC_QUARTER_ID","dataType":"int64"},{"name":"FC_WEEK_ID","dataType":"int64"},{"name":"FC_YEAR_OFFSET","dataType":"int64"},{"name":"FC_QUARTER_OFFSET","dataType":"int64"},{"name":"FC_PERIOD_OFFSET","dataType":"int64"},{"name":"FC_WEEK_OFFSET","dataType":"int64"},{"name":"FC_DAYS_OFFSET","dataType":"int64"},{"name":"FC_HALF","dataType":"string"},{"name":"NQ_FIRST_FISCAL_WEEK","dataType":"string"},{"name":"PQ_LAST_FISCAL_WEEK","dataType":"string"},{"name":"CALENDAR_YEAR","dataType":"int64"},{"name":"CALENDAR_MONTH","dataType":"int64"},{"name":"CALENDAR_YEARMONTHID","dataType":"int64"},{"name":"CALENDAR_MONTHNAME","dataType":"string"},{"name":"CALENDAR_MONTHNAMESHORT","dataType":"string"},{"name":"CALENDAR_ISO_WEEK","dataType":"int64"},{"name":"CALENDAR_US_WEEK","dataType":"int64"},{"name":"CALENDAR_YEAR_SHORT","dataType":"int64"},{"name":"CALENDAR_MTH_YEAR","dataType":"string"},{"name":"DAY_NAME","dataType":"string"},{"name":"DAY_OF_WEEK","dataType":"int64"},{"name":"WORKING_DAY_FLAG","dataType":"int64"},{"name":"CQ_LAST_FISCAL_WEEK","dataType":"string"},{"name":"ROW_CREATION_DATE","dataType":"date"},{"name":"WEEK_END_FLAG","dataType":"string"},{"name":"MONTH_END_FLAG","dataType":"string"},{"name":"QUARTER_END_FLAG","dataType":"string"},{"name":"YEAR_END_FLAG","dataType":"string"},{"name":"FISCAL_WEEK_INDICATOR","dataType":"string"},{"name":"FISCAL_WEEK_INDICATOR_SORT","dataType":"int64"},{"name":"FISCAL_MONTH_INDICATOR","dataType":"string"},{"name":"FISCAL_MONTH_INDICATOR_SORT","dataType":"int64"},{"name":"FISCAL_QUARTER_INDICATOR","dataType":"string"},{"name":"FISCAL_QUARTER_INDICATOR_SORT","dataType":"int64"},{"name":"FISCAL_YEAR_INDICATOR","dataType":"string"},{"name":"FISCAL_YEAR_INDICATOR_SORT","dataType":"int64"},{"name":"EXTRACT_DATE","dataType":"dateTime"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T02:01:14.1877426+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/58fdad08-fc2b-4432-82ea-0f2d6861cb38/XX_FISCAL_DAYS_VIEW.csv?snapshot=2022-06-13T02%3A01%3A14.1277361Z"}]}]}