{"name":"COHREP_SITE_WIP_MASTER1","description":"","version":"1.0","culture":"en-US","modifiedTime":"2020-08-29T09:06:56.7151027+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":true,"queriesMetadata":{"WIP_Class":{"queryId":"d3ec8519-1d77-416d-9c1d-96f3e205d209","queryName":"WIP_Class","queryGroupId":"root","loadEnabled":true},"ORG":{"queryId":"1cf10fc1-3f3e-4bf4-a968-cf3783666e1d","queryName":"ORG"},"WIP_Department_Resource":{"queryId":"d20369f8-b4c6-425b-8224-6084e86bd4f9","queryName":"WIP_Department_Resource","queryGroupId":"root","loadEnabled":true}},"document":"section Section1;\r\nshared WIP_Class = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, \n  Query=\"\n  SELECT\n   SYSDATE EXTRACT_DATE,\n   MP.ORGANIZATION_CODE,\n   WAC.CLASS_CODE,\n   WAC.DESCRIPTION,\n   WAC.CLASS_TYPE CLASS_TYPE_CODE,\n   WLO.MEANING CLASS_TYPE,\n   WAC.DISABLE_DATE,\n   MAC.CONCATENATED_SEGMENTS MATERIAL_ACCOUNT,\n   MOHAC.CONCATENATED_SEGMENTS MATERIAL_OVERHEAD_ACCOUNT,\n   RESAC.CONCATENATED_SEGMENTS RESOURCE_ACCOUNT,\n   OHAC.CONCATENATED_SEGMENTS OVERHEAD_ACCOUNT,\n   OSPAC.CONCATENATED_SEGMENTS OUTSIDE_PROCESSING_ACCOUNT,\n   MVAC.CONCATENATED_SEGMENTS MATERIAL_VARIANCE_ACCOUNT,\n   RESVAC.CONCATENATED_SEGMENTS RESOURCE_VARIANCE_ACCOUNT,\n   OHVAC.CONCATENATED_SEGMENTS OVERHEAD_VARIANCE_ACCOUNT,\n   OSPVAC.CONCATENATED_SEGMENTS OSP_VARIANCE_ACCOUNT,\n   SADJAC.CONCATENATED_SEGMENTS STD_COST_ADJ_ACCOUNT,\n   WAC.ATTRIBUTE1 WORK_TYPE,\n   WAC.ATTRIBUTE2 ACCOUNTING_TYPE,\n   WAC.ATTRIBUTE3 ACTIVITY,\n   WAC.CREATION_DATE,\n   CU.USER_NAME CREATED_BY,\n   WAC.LAST_UPDATE_DATE,\n   LU.USER_NAME LAST_UPDATED_BY \nFROM\n   APPS.FND_USER CU,\n   APPS.FND_USER LU,\n   APPS.GL_CODE_COMBINATIONS_KFV MAC,\n   APPS.GL_CODE_COMBINATIONS_KFV MOHAC,\n   APPS.GL_CODE_COMBINATIONS_KFV RESAC,\n   APPS.GL_CODE_COMBINATIONS_KFV OHAC,\n   APPS.GL_CODE_COMBINATIONS_KFV OSPAC,\n   APPS.GL_CODE_COMBINATIONS_KFV MVAC,\n   APPS.GL_CODE_COMBINATIONS_KFV OHVAC,\n   APPS.GL_CODE_COMBINATIONS_KFV RESVAC,\n   APPS.GL_CODE_COMBINATIONS_KFV OSPVAC,\n   APPS.GL_CODE_COMBINATIONS_KFV SADJAC,\n   APPS.FND_LOOKUP_VALUES WLO,\n   APPS.WIP_ACCOUNTING_CLASSES WAC,\n   APPS.MTL_PARAMETERS MP \nWHERE\n   MP.ORGANIZATION_CODE = '\"&ORG&\"' \n   AND CU.USER_ID ( + ) = WAC.CREATED_BY \n   AND LU.USER_ID ( + ) = WAC.LAST_UPDATED_BY \n   AND MAC.CODE_COMBINATION_ID ( + ) = WAC.MATERIAL_ACCOUNT \n   AND MOHAC.CODE_COMBINATION_ID ( + ) = WAC.MATERIAL_OVERHEAD_ACCOUNT \n   AND RESAC.CODE_COMBINATION_ID ( + ) = WAC.RESOURCE_ACCOUNT \n   AND OHAC.CODE_COMBINATION_ID ( + ) = WAC.OVERHEAD_ACCOUNT \n   AND OSPAC.CODE_COMBINATION_ID ( + ) = WAC.OUTSIDE_PROCESSING_ACCOUNT \n   AND MVAC.CODE_COMBINATION_ID ( + ) = WAC.MATERIAL_VARIANCE_ACCOUNT \n   AND RESVAC.CODE_COMBINATION_ID ( + ) = WAC.RESOURCE_VARIANCE_ACCOUNT \n   AND OHVAC.CODE_COMBINATION_ID ( + ) = WAC.OVERHEAD_VARIANCE_ACCOUNT \n   AND OSPVAC.CODE_COMBINATION_ID ( + ) = WAC.OUTSIDE_PROC_VARIANCE_ACCOUNT \n   AND SADJAC.CODE_COMBINATION_ID ( + ) = WAC.STD_COST_ADJUSTMENT_ACCOUNT \n   AND WLO.LANGUAGE = 'US' \n   AND WLO.LOOKUP_TYPE = 'WIP_CLASS_TYPE' \n   AND WLO.LOOKUP_CODE = WAC.CLASS_TYPE \n   AND WAC.ORGANIZATION_ID = MP.ORGANIZATION_ID\"\n, CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"ORGANIZATION_CODE\", \"Organization Code\"}, {\"CLASS_CODE\", \"Class Code\"}, {\"DESCRIPTION\", \"Class Description\"}, {\"CLASS_TYPE\", \"Class Type\"}, {\"WORK_TYPE\", \"Work Type\"}, {\"ACCOUNTING_TYPE\", \"Accounting Type\"}, {\"ACTIVITY\", \"Activity\"}, {\"MATERIAL_ACCOUNT\", \"Material Account\"}, {\"MATERIAL_OVERHEAD_ACCOUNT\", \"Material Overhead Account\"}, {\"RESOURCE_ACCOUNT\", \"Resource Account\"}, {\"OVERHEAD_ACCOUNT\", \"Overhead Account\"}, {\"OUTSIDE_PROCESSING_ACCOUNT\", \"OSP Account\"}, {\"MATERIAL_VARIANCE_ACCOUNT\", \"Material Variance Account\"}, {\"RESOURCE_VARIANCE_ACCOUNT\", \"Resource Variance Account\"}, {\"OVERHEAD_VARIANCE_ACCOUNT\", \"Overhead Variance Account\"}, {\"OSP_VARIANCE_ACCOUNT\", \"OSP Variance Account\"}, {\"STD_COST_ADJ_ACCOUNT\", \"Cost Adjustment Account\"}}),\r\n  ConvertToList = Table.AddColumn(#\"Renamed columns\", \"ClassCodeToList\", each Text.ToList([Class Code])),\r\n  LowerCaseChars = {\"a\"..\"z\"},\r\n  // add Character.FromNumber(8203) to make the column unique\r\n  AddInvisibleChars = Table.AddColumn(ConvertToList, \"AddInvisibleChars\", each List.Transform(\n            [ClassCodeToList], \n            each \n            if \n            List.Contains(#\"LowerCaseChars\", _) \n            then \n            _ & Character.FromNumber(8203) \n            else _\n            )),\r\n  // Add case sensitive column as result of adding invisible characters Character.FromNumber(8203)\r\n  AddCaseSensitiveColumn = Table.AddColumn(AddInvisibleChars, \"Class Code CS\", each Text.Combine([AddInvisibleChars])),\r\n  #\"Removed columns\" = Table.RemoveColumns(AddCaseSensitiveColumn, {\"ClassCodeToList\", \"AddInvisibleChars\"}),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Removed columns\", {{\"Class Code CS\", type text}})\r\nin\r\n  #\"Changed column type\";\r\nshared ORG = let\r\n  ORG = \"LDP\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type text]\r\nin\r\n  ORG;\r\nshared WIP_Department_Resource = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, \n  Query=\"\n  select sysdate extract_date\n,bdept.department_id\n,bdept.department_code\n,bdept.description department_description\n,bdept.location_code\n,bdr.resource_id\n,bdr.resource_code\n,bdr.resource_description\n,bdr.unit_of_measure\n,crc.resource_rate\n,decode(bdr.available_24_hours_flag,1,'Yes',2,'No') hours24_flag\n,BRT.MEANING RESOURCE_TYPE\n,BACT.MEANING AUTOCHARGE_TYPE\n,decode(br.DEFAULT_BASIS_TYPE,1,'Item',2,'Lot') DEFAULT_BASIS_TYPE\nfrom apps.BOM_DEPARTMENTS_V bdept\n, apps.mtl_parameters mp\n,apps.BOM_DEPARTMENT_RESOURCES_V  bdr\n,apps.CST_RESOURCE_COSTS_V crc\n,APPS.BOM_RESOURCES_V br\n,(SELECT LOOKUP_CODE,MEANING FROM apps.mfg_lookups_v\nWHERE lookup_type = 'BOM_RESOURCE_TYPE') BRT\n,(SELECT LOOKUP_CODE,MEANING FROM apps.mfg_lookups_v\nWHERE lookup_type =  'BOM_AUTOCHARGE_TYPE') BACT\nwhere mp.organization_id = bdept.organization_id\nand mp.organization_code = '\"&ORG&\"'\nand bdr.organization_id = bdept.organization_id\nand bdr.department_id = bdept.department_id\nand  bdr.resource_id = crc.resource_id (+)\nand bdr.organization_id = crc.organization_id(+)\nand 1 = crc.cost_type_id  (+)\nAND BR.RESOURCE_ID = BDR.RESOURCE_ID\nAND BRT.LOOKUP_CODE = BR.RESOURCE_TYPE\nAND BACT.LOOKUP_CODE = br.autocharge_type\"\n, CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"EXTRACT_DATE\", \"Extract Date\"}, {\"DEPARTMENT_CODE\", \"Department Code\"}, {\"DEPARTMENT_DESCRIPTION\", \"Department Description\"}, {\"LOCATION_CODE\", \"Location Code\"}, {\"RESOURCE_CODE\", \"Resource Code\"}, {\"RESOURCE_DESCRIPTION\", \"Resource Description\"}, {\"UNIT_OF_MEASURE\", \"Unit of Measure\"}, {\"RESOURCE_RATE\", \"Resource Rate\"}, {\"RESOURCE_TYPE\", \"Resource Type\"}, {\"AUTOCHARGE_TYPE\", \"Autocharge Type\"}, {\"DEFAULT_BASIS_TYPE\", \"Default Basis\"}, {\"HOURS24_FLAG\", \"24 Hours Flag\"}})\r\nin\r\n  #\"Renamed columns\";\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"WIP_Class","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"WIP_Class.csv"},"attributes":[{"name":"EXTRACT_DATE","dataType":"dateTime"},{"name":"Organization Code","dataType":"string"},{"name":"Class Code","dataType":"string"},{"name":"Class Description","dataType":"string"},{"name":"CLASS_TYPE_CODE","dataType":"double"},{"name":"Class Type","dataType":"string"},{"name":"DISABLE_DATE","dataType":"dateTime"},{"name":"Material Account","dataType":"string"},{"name":"Material Overhead Account","dataType":"string"},{"name":"Resource Account","dataType":"string"},{"name":"Overhead Account","dataType":"string"},{"name":"OSP Account","dataType":"string"},{"name":"Material Variance Account","dataType":"string"},{"name":"Resource Variance Account","dataType":"string"},{"name":"Overhead Variance Account","dataType":"string"},{"name":"OSP Variance Account","dataType":"string"},{"name":"Cost Adjustment Account","dataType":"string"},{"name":"Work Type","dataType":"string"},{"name":"Accounting Type","dataType":"string"},{"name":"Activity","dataType":"string"},{"name":"CREATION_DATE","dataType":"dateTime"},{"name":"CREATED_BY","dataType":"string"},{"name":"LAST_UPDATE_DATE","dataType":"dateTime"},{"name":"LAST_UPDATED_BY","dataType":"string"},{"name":"Class Code CS","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-13T05:06:48.107453+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/0eed4503-00f9-4610-bcc3-3443a6414d56/WIP_Class.csv?snapshot=2022-06-13T05%3A06%3A48.0565441Z"}]},{"$type":"LocalEntity","name":"WIP_Department_Resource","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"WIP_Department_Resource.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"DEPARTMENT_ID","dataType":"double"},{"name":"Department Code","dataType":"string"},{"name":"Department Description","dataType":"string"},{"name":"Location Code","dataType":"string"},{"name":"RESOURCE_ID","dataType":"double"},{"name":"Resource Code","dataType":"string"},{"name":"Resource Description","dataType":"string"},{"name":"Unit of Measure","dataType":"string"},{"name":"Resource Rate","dataType":"double"},{"name":"24 Hours Flag","dataType":"string"},{"name":"Resource Type","dataType":"string"},{"name":"Autocharge Type","dataType":"string"},{"name":"Default Basis","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-13T05:06:46.3252487+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/0eed4503-00f9-4610-bcc3-3443a6414d56/WIP_Department_Resource.csv?snapshot=2022-06-13T05%3A06%3A46.2965394Z"}]}]}