{"name":"DF_FINANCE","description":"RSV-Tables","version":"1.0","culture":"en-US","modifiedTime":"2022-06-14T06:38:01.6394632+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"EarliestDate":{"queryId":"1875c273-4431-4474-a0bd-680e7e4e1518","queryName":"EarliestDate"},"XXCOH_RSV_HEADERS":{"queryId":"4e52af24-1eb6-4aa6-9b1f-736917a8d722","queryName":"XXCOH_RSV_HEADERS","loadEnabled":true},"Organization Code":{"queryId":"e4182ec1-1ceb-47b8-b321-1bd35b0e6bd3","queryName":"Organization Code"},"XXCOH_RSV_LINES":{"queryId":"0052ca5e-38e0-4fa0-a6d4-705988e88659","queryName":"XXCOH_RSV_LINES","loadEnabled":true}},"document":"section Section1;\r\nshared EarliestDate = #datetime(2021, 1, 1, 0, 0, 0) meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type datetime];\r\nshared XXCOH_RSV_HEADERS = let\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\n  Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\n  #\"Navigation 1\" = Navigation{[Name = \"XXCOH\", Kind = \"Schema\"]}[Data],\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXCOH_RSV_HEADERS\", Kind = \"Table\"]}[Data],\r\n  #\"Filtered rows-> Organzation Code\" = Table.SelectRows(#\"Navigation 2\", each List.Contains(#\"Organization Code\", [ORGANIZATION_CODE]))\nin\n  #\"Filtered rows-> Organzation Code\";\r\nshared #\"Organization Code\" = {\"LDP\", \"SPG\"} meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type list];\r\nshared XXCOH_RSV_LINES = let\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\n  Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\n  #\"Navigation 1\" = Navigation{[Name = \"XXCOH\", Kind = \"Schema\"]}[Data],\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXCOH_RSV_LINES\", Kind = \"Table\"]}[Data],\r\n  #\"Filtered rows\" = Table.SelectRows(#\"Navigation 2\", each ([FIN_TBU] = \"DPSS_Germany\"))\nin\n  #\"Filtered rows\";\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"XXCOH_RSV_HEADERS","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"XXCOH_RSV_HEADERS.csv"},"attributes":[{"name":"CONTROL_ID","dataType":"double"},{"name":"RESERVE_HEADER_ID","dataType":"double"},{"name":"RUN_DATE","dataType":"dateTime"},{"name":"RESERVE_PERIOD","dataType":"string"},{"name":"RESERVE_TYPE","dataType":"string"},{"name":"ORGANIZATION_ID","dataType":"double"},{"name":"ORGANIZATION_CODE","dataType":"string"},{"name":"LEDGER_ID","dataType":"double"},{"name":"HEADER_STATUS","dataType":"string"},{"name":"STATUS_DATE","dataType":"dateTime"},{"name":"REVIEW1_ENTITY","dataType":"string"},{"name":"REVIEW1_USER","dataType":"string"},{"name":"REVIEW1_DATE","dataType":"dateTime"},{"name":"REVIEW1_CLOSED","dataType":"dateTime"},{"name":"REVIEW2_ENTITY","dataType":"string"},{"name":"REVIEW2_USER","dataType":"string"},{"name":"REVIEW2_DATE","dataType":"dateTime"},{"name":"REVIEW2_CLOSED","dataType":"dateTime"},{"name":"REVIEW3_ENTITY","dataType":"string"},{"name":"REVIEW3_USER","dataType":"string"},{"name":"REVIEW3_DATE","dataType":"dateTime"},{"name":"REVIEW3_CLOSED","dataType":"dateTime"},{"name":"FINAL_APPROVE_DATE","dataType":"dateTime"},{"name":"GL_JE_EXPORTED","dataType":"dateTime"},{"name":"RESERVE_FROZEN","dataType":"dateTime"},{"name":"GL_PERIOD_NAME","dataType":"string"},{"name":"CURRENCY_CODE","dataType":"string"},{"name":"USD_RATE","dataType":"double"},{"name":"USD_RATE_DATE","dataType":"dateTime"},{"name":"PLAN_ID","dataType":"double"},{"name":"PLAN_NAME","dataType":"string"},{"name":"CREATION_DATE","dataType":"dateTime"},{"name":"CREATED_BY","dataType":"double"},{"name":"LAST_UPDATE_DATE","dataType":"dateTime"},{"name":"LAST_UPDATED_BY","dataType":"double"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-14T05:39:18.6400771+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/cc979e46-bfea-4a3e-bc5d-5541fa2389f7/XXCOH_RSV_HEADERS.csv?snapshot=2022-06-14T05%3A39%3A10.3049865Z"}]},{"$type":"LocalEntity","name":"XXCOH_RSV_LINES","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"XXCOH_RSV_LINES.csv"},"attributes":[{"name":"CONTROL_ID","dataType":"double"},{"name":"RESERVE_HEADER_ID","dataType":"double"},{"name":"RESERVE_LINE_ID","dataType":"double"},{"name":"RESERVE_PERIOD","dataType":"string"},{"name":"RESERVE_TYPE","dataType":"string"},{"name":"ORGANIZATION_CODE","dataType":"string"},{"name":"ORGANIZATION_ID","dataType":"double"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"LINE_STATUS","dataType":"string"},{"name":"ITEM_NUMBER","dataType":"string"},{"name":"ITEM_DESCRIPTION","dataType":"string"},{"name":"SYSTEM_RESERVE_QUANTITY","dataType":"double"},{"name":"SYSTEM_RESERVE_EXT_VALUE","dataType":"double"},{"name":"SYSTEM_RESERVE_TRF_EXT_VALUE","dataType":"double"},{"name":"SYSTEM_RESERVE_CATEGORY","dataType":"string"},{"name":"SYSTEM_RESERVE_RATE","dataType":"double"},{"name":"SYSTEM_RESERVE_AMOUNT","dataType":"double"},{"name":"SYSTEM_RESERVE_TRF_AMOUNT","dataType":"double"},{"name":"SYSTEM_RESERVE_COMMENT","dataType":"string"},{"name":"REVIEW1_RESERVE_QUANTITY","dataType":"double"},{"name":"REVIEW1_RESERVE_EXT_VALUE","dataType":"double"},{"name":"REVIEW1_RESERVE_TRF_EXT_VALUE","dataType":"double"},{"name":"REVIEW1_RESERVE_CATEGORY","dataType":"string"},{"name":"REVIEW1_RESERVE_RATE","dataType":"double"},{"name":"REVIEW1_RESERVE_AMOUNT","dataType":"double"},{"name":"REVIEW1_RESERVE_TRF_AMOUNT","dataType":"double"},{"name":"REVIEW1_OVERRIDE_REASON","dataType":"string"},{"name":"REVIEW1_COMMENT","dataType":"string"},{"name":"REVIEW2_RESERVE_QUANTITY","dataType":"double"},{"name":"REVIEW2_RESERVE_EXT_VALUE","dataType":"double"},{"name":"REVIEW2_RESERVE_TRF_EXT_VALUE","dataType":"double"},{"name":"REVIEW2_RESERVE_CATEGORY","dataType":"string"},{"name":"REVIEW2_RESERVE_RATE","dataType":"double"},{"name":"REVIEW2_RESERVE_AMOUNT","dataType":"double"},{"name":"REVIEW2_RESERVE_TRF_AMOUNT","dataType":"double"},{"name":"REVIEW2_OVERRIDE_REASON","dataType":"string"},{"name":"REVIEW2_COMMENT","dataType":"string"},{"name":"FINAL_RESERVE_QUANTITY","dataType":"double"},{"name":"FINAL_RESERVE_EXT_VALUE","dataType":"double"},{"name":"FINAL_RESERVE_TRF_EXT_VALUE","dataType":"double"},{"name":"FINAL_RESERVE_CATEGORY","dataType":"string"},{"name":"FINAL_RESERVE_RATE","dataType":"double"},{"name":"FINAL_RESERVE_AMOUNT","dataType":"double"},{"name":"FINAL_RESERVE_TRF_AMOUNT","dataType":"double"},{"name":"FINAL_RESERVE_AMOUNT_USD","dataType":"double"},{"name":"FINAL_TAKEN_FROM","dataType":"string"},{"name":"FINAL_FINANCE_APPROVE_DATE","dataType":"dateTime"},{"name":"REVIEW1_USER","dataType":"string"},{"name":"REVIEW1_DATE","dataType":"dateTime"},{"name":"REVIEW2_USER","dataType":"string"},{"name":"REVIEW2_DATE","dataType":"dateTime"},{"name":"REVIEW3_USER","dataType":"string"},{"name":"REVIEW3_DATE","dataType":"dateTime"},{"name":"OPERATING_UNIT","dataType":"string"},{"name":"LEDGER_SHORT_NAME","dataType":"string"},{"name":"CURRENCY_CODE","dataType":"string"},{"name":"ORGANIZATION_CATEGORY","dataType":"string"},{"name":"RESERVE_ENTITY","dataType":"string"},{"name":"RESERVE_DEPARTMENT","dataType":"string"},{"name":"RESERVE_ACCOUNT","dataType":"string"},{"name":"RESERVE_IC","dataType":"string"},{"name":"TBU","dataType":"string"},{"name":"PRODUCT_FAMILY","dataType":"string"},{"name":"PRODUCT_LINE","dataType":"string"},{"name":"ORG_TBU","dataType":"string"},{"name":"ORG_PRODUCT_FAMILY","dataType":"string"},{"name":"ORG_PRODUCT_LINE","dataType":"string"},{"name":"FIN_TBU","dataType":"string"},{"name":"FIN_PRODUCT_FAMILY","dataType":"string"},{"name":"PLANNER_CODE","dataType":"string"},{"name":"GREEN_SUPPLY_STATUS","dataType":"string"},{"name":"ASSET_FLAG","dataType":"string"},{"name":"NETTABLE_FLAG","dataType":"string"},{"name":"MAKE_BUY","dataType":"string"},{"name":"SERVICE_LEAD_TIME","dataType":"string"},{"name":"DATE_LAST_ACTIVITY","dataType":"dateTime"},{"name":"LOT_SIZE","dataType":"double"},{"name":"ITEM_COST_STANDARD","dataType":"double"},{"name":"ITEM_TRF_COST","dataType":"double"},{"name":"ITEM_PRICE","dataType":"double"},{"name":"CLASS_CODE","dataType":"string"},{"name":"ACCT_CLASS_TYPE","dataType":"string"},{"name":"ITEM_TYPE","dataType":"string"},{"name":"ITEM_STATUS_CODE","dataType":"string"},{"name":"ABC_CLASS_CODE","dataType":"string"},{"name":"SUBINVENTORY","dataType":"string"},{"name":"LOT_NUMBER","dataType":"string"},{"name":"SITE_CODE","dataType":"string"},{"name":"CONTROL_ORG_CODE","dataType":"string"},{"name":"LOCATOR_ID","dataType":"double"},{"name":"LOC_SUB","dataType":"string"},{"name":"LOC_ROW","dataType":"string"},{"name":"LOC_RACK","dataType":"string"},{"name":"LOC_SHELF","dataType":"string"},{"name":"LOC_BIN","dataType":"string"},{"name":"NETTABLE_OH_QUANTITY","dataType":"double"},{"name":"NONNETTABLE_OH_QUANTITY","dataType":"double"},{"name":"NETTABLE_RCV_QUANTITY","dataType":"double"},{"name":"NONNETTABLE_RCV_QUANTITY","dataType":"double"},{"name":"NETTABLE_ITRN_QUANTITY","dataType":"double"},{"name":"NONNETTABLE_ITRN_QUANTITY","dataType":"double"},{"name":"WIP_REMAINING_QUANTITY","dataType":"double"},{"name":"TOT_NETTABLE_QUANTITY","dataType":"double"},{"name":"TOT_NONNETTABLE_QUANTITY","dataType":"double"},{"name":"TOT_RESULTING_QUANTITY","dataType":"double"},{"name":"TOT_NETTABLE_EXT_VALUE","dataType":"double"},{"name":"TOT_NONNETTABLE_EXT_VALUE","dataType":"double"},{"name":"TOT_ONHAND_EXT_VALUE","dataType":"double"},{"name":"TOT_RECEIVING_EXT_VALUE","dataType":"double"},{"name":"TOT_INTRANSIT_EXT_VALUE","dataType":"double"},{"name":"DEMAND_0_03","dataType":"double"},{"name":"DEMAND_0_12","dataType":"double"},{"name":"DEMAND_0_18","dataType":"double"},{"name":"DEMAND_0_24","dataType":"double"},{"name":"DEMAND_SUBSTITUTE","dataType":"double"},{"name":"USAGE_0_03","dataType":"double"},{"name":"USAGE_0_12","dataType":"double"},{"name":"USAGE_0_18","dataType":"double"},{"name":"USAGE_0_24","dataType":"double"},{"name":"USAGE_13_24","dataType":"double"},{"name":"USAGE_SUBSTITUTE","dataType":"double"},{"name":"OPEN_ORDER_0_03","dataType":"double"},{"name":"OPEN_ORDER_0_12","dataType":"double"},{"name":"OPEN_ORDER_0_18","dataType":"double"},{"name":"OPEN_ORDER_0_24","dataType":"double"},{"name":"OPEN_ORDER_SUBSTITUTE","dataType":"double"},{"name":"RESULTING_QUANTITY_LEFTOVER","dataType":"double"},{"name":"WIP_ENTITY_NAME","dataType":"string"},{"name":"WIP_JOB_TYPE","dataType":"string"},{"name":"WIP_JOB_STATUS","dataType":"string"},{"name":"WIP_DATE_RELEASED","dataType":"dateTime"},{"name":"WIP_TOTAL_COSTS_INCURRED","dataType":"double"},{"name":"WIP_TOTAL_COSTS_RELIEVED","dataType":"double"},{"name":"WIP_TOTAL_VARIANCES_RELIEVED","dataType":"double"},{"name":"WIP_TOTAL_NET_ACTIVITIES","dataType":"double"},{"name":"WIP_DAYS_RELEASED","dataType":"double"},{"name":"WIP_MONTHS_RELEASED","dataType":"double"},{"name":"WIP_AGING_BUCKET","dataType":"string"},{"name":"WIP_ENTITY_ID","dataType":"double"},{"name":"SERIAL_NUM_CONTROL_CODE","dataType":"double"},{"name":"SERIAL_NUMBER","dataType":"string"},{"name":"SERIAL_NUMBER_OVERRIDE","dataType":"string"},{"name":"SERIAL_NUMBER_FINAL","dataType":"string"},{"name":"SERIAL_NUMBER_HISTORY","dataType":"string"},{"name":"SERIAL_NUM_STATUS","dataType":"string"},{"name":"LC_TRACKING_ID","dataType":"double"},{"name":"LC_QUANTITY","dataType":"double"},{"name":"LC_EARLIEST_TRX_DATE","dataType":"dateTime"},{"name":"LC_LATEST_STOCK_DATE","dataType":"dateTime"},{"name":"LC_START_DATE","dataType":"dateTime"},{"name":"LC_START_DATE_OVERRIDE","dataType":"dateTime"},{"name":"LC_START_DATE_FINAL","dataType":"dateTime"},{"name":"LC_LOCATION_STATUS","dataType":"string"},{"name":"LC_PERIOD_RESERVE_AMOUNT","dataType":"double"},{"name":"LC_CURRENT_RESERVE_AMOUNT","dataType":"double"},{"name":"PERIOD_NAME","dataType":"string"},{"name":"PERIOD_YEAR","dataType":"double"},{"name":"PERIOD_QUARTER","dataType":"double"},{"name":"PERIOD_NUM","dataType":"double"},{"name":"LC_PERIOD_COUNT","dataType":"double"},{"name":"LC_DAYS_COUNT","dataType":"double"},{"name":"LC_STATUS","dataType":"string"},{"name":"OPERATING_UNIT_ID","dataType":"double"},{"name":"LEDGER_ID","dataType":"double"},{"name":"RESERVE_ACCOUNT_ID","dataType":"double"},{"name":"CREATION_DATE","dataType":"dateTime"},{"name":"CREATED_BY","dataType":"double"},{"name":"LAST_UPDATE_DATE","dataType":"dateTime"},{"name":"LAST_UPDATED_BY","dataType":"double"},{"name":"QUANTITY1","dataType":"double"},{"name":"QUANTITY2","dataType":"double"},{"name":"QUANTITY3","dataType":"double"},{"name":"QUANTITY4","dataType":"double"},{"name":"QUANTITY5","dataType":"double"},{"name":"DEMAND1","dataType":"double"},{"name":"DEMAND2","dataType":"double"},{"name":"DEMAND3","dataType":"double"},{"name":"DEMAND4","dataType":"double"},{"name":"DEMAND5","dataType":"double"},{"name":"USAGE1","dataType":"double"},{"name":"USAGE2","dataType":"double"},{"name":"USAGE3","dataType":"double"},{"name":"USAGE4","dataType":"double"},{"name":"USAGE5","dataType":"double"},{"name":"OPEN_ORDER1","dataType":"double"},{"name":"OPEN_ORDER2","dataType":"double"},{"name":"OPEN_ORDER3","dataType":"double"},{"name":"OPEN_ORDER4","dataType":"double"},{"name":"OPEN_ORDER5","dataType":"double"},{"name":"TOTAL1","dataType":"double"},{"name":"TOTAL2","dataType":"double"},{"name":"TOTAL3","dataType":"double"},{"name":"TOTAL4","dataType":"double"},{"name":"TOTAL5","dataType":"double"},{"name":"DATE1","dataType":"dateTime"},{"name":"DATE2","dataType":"dateTime"},{"name":"DATE3","dataType":"dateTime"},{"name":"DATE4","dataType":"dateTime"},{"name":"DATE5","dataType":"dateTime"},{"name":"LOCATION1","dataType":"string"},{"name":"LOCATION2","dataType":"string"},{"name":"LOCATION3","dataType":"string"},{"name":"LOCATION4","dataType":"string"},{"name":"LOCATION5","dataType":"string"},{"name":"PRIOR_RESERVE_QUANTITY","dataType":"double"},{"name":"PRIOR_RESERVE_EXT_VALUE","dataType":"double"},{"name":"PRIOR_RESERVE_TRF_EXT_VALUE","dataType":"double"},{"name":"PRIOR_RESERVE_CATEGORY","dataType":"string"},{"name":"PRIOR_RESERVE_RATE","dataType":"double"},{"name":"PRIOR_RESERVE_AMOUNT","dataType":"double"},{"name":"PRIOR_RESERVE_TRF_AMOUNT","dataType":"double"},{"name":"PRIOR_RESERVE_AMOUNT_USD","dataType":"double"},{"name":"PRIOR_OH_QUANTITY","dataType":"double"},{"name":"PRIOR_COMMENT","dataType":"string"},{"name":"FORECAST","dataType":"string"},{"name":"ORG_FORECAST","dataType":"string"},{"name":"FIN_FORECAST","dataType":"string"},{"name":"PRIOR_OVERRIDE_REASON","dataType":"string"},{"name":"SYSTEM_RESERVE_AMOUNT_USD","dataType":"double"},{"name":"USER_DEFINED_1","dataType":"string"},{"name":"USER_DEFINED_2","dataType":"string"},{"name":"USER_DEFINED_3","dataType":"string"},{"name":"USER_DEFINED_4","dataType":"string"},{"name":"OPS_REPORTING","dataType":"string"},{"name":"SEC_REPORTING","dataType":"string"},{"name":"OPEN_PO_0_12","dataType":"double"},{"name":"OPEN_PO_0_24","dataType":"double"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-14T05:41:30.4112311+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/cc979e46-bfea-4a3e-bc5d-5541fa2389f7/XXCOH_RSV_LINES.csv?snapshot=2022-06-14T05%3A41%3A30.3616712Z"}]}]}