{"name":"COHREP_SITE_PURCHASING_MASTER1","description":"","version":"1.0","culture":"en-US","modifiedTime":"2020-08-28T10:01:50.7655607+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":true,"queriesMetadata":{"Buyer":{"queryId":"edcfb8f1-71a2-4d77-829a-99e05601b8a6","queryName":"Buyer","queryGroupId":"root","loadEnabled":true},"Supplier_Contact":{"queryId":"3d6511dd-14bf-4ee5-b7be-e82f9533ad6e","queryName":"Supplier_Contact","queryGroupId":"root","loadEnabled":true},"Supplier":{"queryId":"ce291698-373a-4fd0-ae7b-7a935ed4e51c","queryName":"Supplier","queryGroupId":"root","loadEnabled":true},"ORG":{"queryId":"43c69a79-2c80-4316-bc27-040178279912","queryName":"ORG"}},"document":"section Section1;\r\nshared Buyer = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, Query=\"\n  SELECT DISTINCT\n   SYSDATE EXTRACT_DATE,\n   POA.AGENT_ID,\n   POA.AGENT_NAME,\n   PPV1.PPV1_APPROVER,\n   PPV2.PPV2_APPROVER,\n   CASE\n      WHEN\n         NVL( LEAST( POA.END_DATE_ACTIVE, FU.END_DATE ), SYSDATE + 1 ) < SYSDATE \n      THEN\n         'No' \n      ELSE\n         'Yes' \n   END\n   ACTIVE_FLAG, FU.END_DATE USER_END_DATE, \n   CASE\n      WHEN\n         (\n            SELECT\n               COUNT(AGENT_ID) \n            FROM\n               PO.PO_HEADERS_ALL PHA,\n               APPS.ORG_ORGANIZATION_DEFINITIONS OOD,\n               PO.PO_DISTRIBUTIONS_ALL PDA\n            WHERE\n               OOD.OPERATING_UNIT = PHA.ORG_ID \n               AND PHA.AGENT_ID = POA.AGENT_ID\n               AND PDA.PO_HEADER_ID = PHA.PO_HEADER_ID\n               AND OOD.ORGANIZATION_CODE = '\"&ORG&\"' \n         )\n          + (\n         SELECT\n            COUNT(AGENT_ID) \n         FROM\n            PO.PO_RELEASES_ALL PRA , APPS.ORG_ORGANIZATION_DEFINITIONS OOD \n         WHERE\n            OOD.OPERATING_UNIT = PRA.ORG_ID \n            AND PRA.AGENT_ID = POA.AGENT_ID \n            AND OOD.ORGANIZATION_CODE = '\"&ORG&\"' ) > 0 \n         THEN\n            'Yes' \n         ELSE\n            'No' \n   END\n   PO_BUYER, \n   (\n      CASE\n         WHEN\n            (\n               SELECT\n                  COUNT(INVENTORY_ITEM_ID) \n               FROM\n                  INV.MTL_SYSTEM_ITEMS_B MSI,\n                  INV.MTL_PARAMETERS MP \n               WHERE\n                  MP.ORGANIZATION_ID = MSI.ORGANIZATION_ID \n                  AND MSI.BUYER_ID = POA.AGENT_ID \n                  AND MP.ORGANIZATION_CODE = '\"&ORG&\"' \n            )\n            > 0 \n         THEN\n            'Yes' \n         ELSE\n            'No' \n      END\n   )\n   DEFAULT_BUYER, \n   (\n      SELECT\n         HRL.LOCATION_CODE \n      FROM\n         APPS.HR_LOCATIONS HRL,\n         APPS.PER_ASSIGNMENTS_F PA \n      WHERE\n         PA.LOCATION_ID = HRL.LOCATION_ID \n         AND SYSDATE BETWEEN PA.EFFECTIVE_START_DATE AND PA.EFFECTIVE_END_DATE \n         AND PA.PERSON_ID = POA.AGENT_ID \n         AND PA.ASSIGNMENT_ID = \n         (\n            SELECT\n               MAX(PA2.ASSIGNMENT_ID) \n            FROM\n               APPS.PER_ASSIGNMENTS_F PA2 \n            WHERE\n               PA2.PERSON_ID = PA.PERSON_ID \n         )\n         AND ROWNUM = 1 \n   )\n   BUYER_LOCATION,\n   (\n      SELECT\n         SUP.FULL_NAME \n      FROM\n         APPS.PER_PEOPLE_X SUP,\n         APPS.PER_ASSIGNMENTS_F PA \n      WHERE\n         SUP.PERSON_ID = PA.SUPERVISOR_ID \n         AND SYSDATE BETWEEN PA.EFFECTIVE_START_DATE AND PA.EFFECTIVE_END_DATE \n         AND PA.PERSON_ID = POA.AGENT_ID \n         AND PA.ASSIGNMENT_ID = \n         (\n            SELECT\n               MAX(PA2.ASSIGNMENT_ID) \n            FROM\n               APPS.PER_ASSIGNMENTS_F PA2 \n            WHERE\n               PA2.PERSON_ID = PA.PERSON_ID \n         )\n         AND ROWNUM = 1 \n   )\n   SUPERVISOR \n         FROM\n            APPS.PO_AGENTS_V POA,\n            (\n               SELECT\n                  TO_CHAR(PPX.PERSON_ID) AS PERSON_ID,\n                  PPX.FULL_NAME AS PPV1_APPROVER \n               FROM\n                  APPS.PER_PEOPLE_X PPX \n            )\n            PPV1,\n            (\n               SELECT\n                  TO_CHAR(PPX.PERSON_ID) AS PERSON_ID,\n                  PPX.FULL_NAME AS PPV2_APPROVER \n               FROM\n                  APPS.PER_PEOPLE_X PPX \n            )\n            PPV2,\n            APPLSYS.FND_USER FU \n         WHERE\n            1 = 1 \n            AND POA.ATTRIBUTE2 = PPV1.PERSON_ID \n            AND POA.ATTRIBUTE3 = PPV2.PERSON_ID \n            AND FU.EMPLOYEE_ID = POA.AGENT_ID\n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"AGENT_NAME\", \"Buyer Name\"}, {\"EXTRACT_DATE\", \"Extract Date\"}, {\"ACTIVE_FLAG\", \"Buyer Active Flag\"}, {\"PPV1_APPROVER\", \"PPV1 Approver\"}, {\"PPV2_APPROVER\", \"PPV2 Approver\"}, {\"DEFAULT_BUYER\", \"Default Buyer Flag\"}, {\"BUYER_LOCATION\", \"Location\"}, {\"PO_BUYER\", \"PO Buyer Flag\"}, {\"SUPERVISOR\", \"Supervisor Name\"}, {\"USER_END_DATE\", \"User End Date\"}}),\r\n  #\"Filtered rows\" = Table.SelectRows(#\"Renamed columns\", each [Buyer Name] <> \"Oracle, Production\")\r\nin\r\n  #\"Filtered rows\";\r\nshared Supplier_Contact = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, Query=\"\n  SELECT distinct asu.vendor_name\n,hpc.party_name Contact_Name\n,hpr.primary_phone_country_code contact_country\n,hpr.primary_phone_area_code contact_area\n,hpr.primary_phone_number contact_phone\n,hpr.email_address\n,assa.vendor_site_code\n,assa.vendor_site_id\n,asco.vendor_contact_id\n,asco.inactive_date\nFROM\n apps.hz_relationships hr\n,apps.ap_suppliers asu\n,apps.ap_supplier_sites_all assa\n,apps.ap_supplier_contacts asco\n,apps.hz_org_contacts hoc\n,apps.hz_parties hpc\n,apps.hz_parties hpr\n,apps.hz_contact_points hpcp\n,apps.org_organization_definitions ood\nWHERE hoc.party_relationship_id = hr.relationship_id\nAND hr.subject_id = asu.party_id\nAND hr.relationship_code = 'CONTACT'\nAND hr.object_table_name = 'HZ_PARTIES'\nAND asu.vendor_id = assa.vendor_id\nAND hr.object_id = hpc.party_id\nAND hr.party_id = hpr.party_id\nAND asco.relationship_id  = hoc.party_relationship_id\nAND assa.party_site_id = asco.org_party_site_id\nAND hpr.party_type='PARTY_RELATIONSHIP'\nAND hpr.party_id = hpcp.owner_table_id\nAND hpcp.owner_table_name = 'HZ_PARTIES'\nAND OOD.OPERATING_UNIT = ASSA.ORG_ID\nand ood.organization_code = '\"&ORG&\"'\n\n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"CONTACT_NAME\", \"Contact Name\"}, {\"EMAIL_ADDRESS\", \"Email Address\"}, {\"INACTIVE_DATE\", \"Inactive Date\"}, {\"VENDOR_NAME\", \"Supplier Name\"}, {\"VENDOR_SITE_CODE\", \"Supplier Site Code\"}, {\"CONTACT_PHONE\", \"Contact Phone\"}, {\"CONTACT_AREA\", \"Contact Area\"}, {\"CONTACT_COUNTRY\", \"Contact Country\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Supplier = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, \n  Query=\"\n   SELECT\n   SYSDATE EXTRACT_DATE,\n   XXPOV.SEGMENT1 SUPPLIER_NUMBER,\n   XXPOV.VENDOR_NAME,\n   XXPOV.VENDOR_NAME_ALT,\n   XXPOVS.VENDOR_SITE_ID,\n   XXPOVS.VENDOR_ID,\n   XXPOVS.VENDOR_SITE_CODE,\n   XXPOVS.VENDOR_SITE_CODE_ALT,\n   (\n      CASE\n         WHEN\n            XXPOVS.VENDOR_SITE_CODE_ALT IS NOT NULL \n         THEN\n            'Yes' \n         ELSE\n            'No' \n      END\n   )\n   PRODUCTION_SUPPLIER_FLAG, XXPOVS.CREATION_DATE SUPPLIER_CREATION_DATE, XXPOVS.LAST_UPDATE_DATE SUPPLIER_LAST_UPDATE_DATE, XXPOVS.PAY_SITE_FLAG, XXPOVS.PURCHASING_SITE_FLAG, XXPOVS.CITY, XXPOVS.COUNTRY, XXPOVS.COUNTRY_OF_ORIGIN_CODE, \n   (\n      CASE\n         WHEN\n            LEAST ( NVL( XXPOV.END_DATE_ACTIVE, SYSDATE + 1 ), NVL(XXPOVS.INACTIVE_DATE, SYSDATE + 1) ) < TRUNC(SYSDATE) \n         THEN\n            'No' \n         ELSE\n            'Yes' \n      END\n   )\n   ACTIVE_SUPPLIER_FLAG, \n   CASE\n      WHEN\n         NVL( XXPOV.END_DATE_ACTIVE, SYSDATE + 1) > NVL(XXPOVS.INACTIVE_DATE, SYSDATE + 1) \n      THEN\n         XXPOVS.INACTIVE_DATE \n      ELSE\n         XXPOV.END_DATE_ACTIVE \n   END\n   INACTIVE_DATE, XXPOVS.INVOICE_CURRENCY_CODE, XXPOVS.PAYMENT_CURRENCY_CODE, XXPOVS.PAYMENT_METHOD_LOOKUP_CODE, XXPOV.VENDOR_TYPE_LOOKUP_CODE, DECODE( XXPOV.ATTRIBUTE1, 'Y', 'Yes', 'No') INTERNAL_SUPPLIER_FLAG, DECODE( XXPOV.ATTRIBUTE4, 'Y', 'Yes', 'No') ISUPPLIER_FORECAST_FLAG, XXPOVS.FOB_LOOKUP_CODE, XXPOVS.FREIGHT_TERMS_LOOKUP_CODE, \n   (\n      CASE\n         WHEN\n            (\n               SELECT\n                  COUNT(1) \n               FROM\n                  APPS.HZ_RELATIONSHIPS HR1,\n                  APPS.HZ_PARTIES HP1,\n                  APPS.FND_USER FU \n               WHERE\n                  1 = 1 \n                  AND HR1.OBJECT_TABLE_NAME = 'HZ_PARTIES' \n                  AND HR1.OBJECT_TYPE = 'ORGANIZATION' \n                  AND HP1.PARTY_ID = HR1.OBJECT_ID \n                  AND FU.PERSON_PARTY_ID = HR1.SUBJECT_ID \n                  AND XXPOV.PARTY_ID = HP1.PARTY_ID \n                  AND NVL(FU.END_DATE, SYSDATE + 1) > SYSDATE \n            )\n            > 0 \n         THEN\n            'Yes' \n         ELSE\n            'No' \n      END\n   )\n   ISUPPLIER_FLAG, APT.NAME PAYMENT_TERM, \n   CASE\n      WHEN\n         NVL( ( \n         SELECT\n            MIN(POA.CREATION_DATE) \n         FROM\n            APPS.PO_ACCEPTANCES_V POA, PO.PO_HEADERS_ALL PHA \n         WHERE\n            PHA.VENDOR_ID = XXPOV.VENDOR_ID \n            AND PHA.VENDOR_ID = XXPOV.VENDOR_ID \n            AND POA.PO_HEADER_ID = PHA.PO_HEADER_ID \n            AND PHA.VENDOR_SITE_ID = XXPOVS.VENDOR_SITE_ID \n            AND POA.ACCEPTING_PARTY = 'S' ), SYSDATE ) > NVL( ( \n            SELECT\n               MIN(POA.CREATION_DATE) \n            FROM\n               APPS.PO_ACCEPTANCES_V POA, PO.PO_RELEASES_ALL PRA, PO.PO_HEADERS_ALL PHA \n            WHERE\n               PHA.VENDOR_ID = XXPOV.VENDOR_ID \n               AND PHA.VENDOR_ID = XXPOV.VENDOR_ID \n               AND POA.PO_RELEASE_ID = PRA.PO_RELEASE_ID \n               AND PHA.VENDOR_SITE_ID = XXPOVS.VENDOR_SITE_ID \n               AND POA.ACCEPTING_PARTY = 'S' \n               AND PHA.PO_HEADER_ID = PRA.PO_HEADER_ID ), SYSDATE ) \n            THEN\n( \n               SELECT\n                  MIN(POA.CREATION_DATE) \n               FROM\n                  APPS.PO_ACCEPTANCES_V POA, PO.PO_RELEASES_ALL PRA, PO.PO_HEADERS_ALL PHA \n               WHERE\n                  PHA.VENDOR_ID = XXPOV.VENDOR_ID \n                  AND PHA.VENDOR_ID = XXPOV.VENDOR_ID \n                  AND POA.PO_RELEASE_ID = PRA.PO_RELEASE_ID \n                  AND PHA.VENDOR_SITE_ID = XXPOVS.VENDOR_SITE_ID \n                  AND POA.ACCEPTING_PARTY = 'S' \n                  AND PHA.PO_HEADER_ID = PRA.PO_HEADER_ID ) \n               ELSE\n( \n                  SELECT\n                     MIN(POA.CREATION_DATE) \n                  FROM\n                     APPS.PO_ACCEPTANCES_V POA, PO.PO_HEADERS_ALL PHA \n                  WHERE\n                     PHA.VENDOR_ID = XXPOV.VENDOR_ID \n                     AND PHA.VENDOR_ID = XXPOV.VENDOR_ID \n                     AND POA.PO_HEADER_ID = PHA.PO_HEADER_ID \n                     AND PHA.VENDOR_SITE_ID = XXPOVS.VENDOR_SITE_ID \n                     AND POA.ACCEPTING_PARTY = 'S' ) \n   END\n   FIRST_PO_ACCEPTANCE,\n   CASE\n      WHEN\n         NVL( ( \n         SELECT\n            MAX(POA.CREATION_DATE) \n         FROM\n            APPS.PO_ACCEPTANCES_V POA, PO.PO_HEADERS_ALL PHA \n         WHERE\n            PHA.VENDOR_ID = XXPOV.VENDOR_ID \n            AND PHA.VENDOR_ID = XXPOV.VENDOR_ID \n            AND POA.PO_HEADER_ID = PHA.PO_HEADER_ID \n            AND PHA.VENDOR_SITE_ID = XXPOVS.VENDOR_SITE_ID \n            AND POA.ACCEPTING_PARTY = 'S' ), SYSDATE ) > NVL( ( \n            SELECT\n               MIN(POA.CREATION_DATE) \n            FROM\n               APPS.PO_ACCEPTANCES_V POA, PO.PO_RELEASES_ALL PRA, PO.PO_HEADERS_ALL PHA \n            WHERE\n               PHA.VENDOR_ID = XXPOV.VENDOR_ID \n               AND PHA.VENDOR_ID = XXPOV.VENDOR_ID \n               AND POA.PO_RELEASE_ID = PRA.PO_RELEASE_ID \n               AND PHA.VENDOR_SITE_ID = XXPOVS.VENDOR_SITE_ID \n               AND POA.ACCEPTING_PARTY = 'S' \n               AND PHA.PO_HEADER_ID = PRA.PO_HEADER_ID ), SYSDATE ) \n            THEN\n( \n               SELECT\n                  MAX(POA.CREATION_DATE) \n               FROM\n                  APPS.PO_ACCEPTANCES_V POA, PO.PO_RELEASES_ALL PRA, PO.PO_HEADERS_ALL PHA \n               WHERE\n                  PHA.VENDOR_ID = XXPOV.VENDOR_ID \n                  AND PHA.VENDOR_ID = XXPOV.VENDOR_ID \n                  AND POA.PO_RELEASE_ID = PRA.PO_RELEASE_ID \n                  AND PHA.VENDOR_SITE_ID = XXPOVS.VENDOR_SITE_ID \n                  AND POA.ACCEPTING_PARTY = 'S' \n                  AND PHA.PO_HEADER_ID = PRA.PO_HEADER_ID ) \n               ELSE\n( \n                  SELECT\n                     MAX(POA.CREATION_DATE) \n                  FROM\n                     APPS.PO_ACCEPTANCES_V POA, PO.PO_HEADERS_ALL PHA \n                  WHERE\n                     PHA.VENDOR_ID = XXPOV.VENDOR_ID \n                     AND PHA.VENDOR_ID = XXPOV.VENDOR_ID \n                     AND POA.PO_HEADER_ID = PHA.PO_HEADER_ID \n                     AND PHA.VENDOR_SITE_ID = XXPOVS.VENDOR_SITE_ID \n                     AND POA.ACCEPTING_PARTY = 'S' ) \n   END\n   LAST_PO_ACCEPTANCE,\n   (\n      SELECT\n         MAX(API.INVOICE_DATE) \n      FROM\n         APPS.AP_INVOICES_ALL API \n      WHERE\n         API.ORG_ID = XXPOVS.ORG_ID \n         AND API.VENDOR_SITE_ID = XXPOVS.VENDOR_SITE_ID \n   )\n   LAST_INVOICE_DATE,\n   (\n      SELECT\n         COUNT(1) \n      FROM\n         APPS.HZ_RELATIONSHIPS HR1,\n         APPS.HZ_PARTIES HP1,\n         APPS.FND_USER FU \n      WHERE\n         1 = 1 \n         AND HR1.OBJECT_TABLE_NAME = 'HZ_PARTIES' \n         AND HR1.OBJECT_TYPE = 'ORGANIZATION' \n         AND HP1.PARTY_ID = HR1.OBJECT_ID \n         AND FU.PERSON_PARTY_ID = HR1.SUBJECT_ID \n         AND XXPOV.PARTY_ID = HP1.PARTY_ID \n         AND NVL(FU.END_DATE, SYSDATE + 1) > SYSDATE \n   )\n   ISUPPLIER_USER_COUNT,\n   (\n      SELECT\n         P.FULL_NAME \n      FROM\n         APPS.PER_ALL_PEOPLE_F P \n      WHERE\n         P.CURRENT_EMPLOYEE_FLAG = 'Y' \n         AND TRUNC (SYSDATE) BETWEEN P.EFFECTIVE_START_DATE AND P.EFFECTIVE_END_DATE \n         AND TO_CHAR(P.PERSON_ID) = XXPOV.ATTRIBUTE2 \n   )\n   SUPPLIER_LEAD,\n   XXPOV.ATTRIBUTE5 SUPPLIER_CLASS,\n   NVL(XXVD.VENDOR_CATEGORY, 'Unassigned') SUPPLIER_CATEGORY,\n   NVL(XXVD.SSM_LEAD, 'Unassigned') SSM_LEAD,\n   NVL(XXVD.MASTER_VENDOR_NAME, XXPOV.VENDOR_NAME)MASTER_SUPPLIER,\n   NVL(XXVD.ATTRIBUTE1, 'NA') KEY_AND_RISK_FLAG,\n   DECODE(XXVD.ATTRIBUTE2, 'Y', 'Yes', 'No') KPI_FLAG \n                  FROM\n                     APPS.PO_VENDORS XXPOV,\n                     APPS.PO_VENDOR_SITES_ALL XXPOVS,\n                     APPS.ORG_ORGANIZATION_DEFINITIONS OOD,\n                     APPS.HR_OPERATING_UNITS HOU,\n                     APPS.AP_TERMS_V APT,\n                     XXDIMS.XX_VENDOR_DIM XXVD \n                  WHERE\n                     1 = 1 \n                     AND XXPOV.EMPLOYEE_ID IS NULL \n                     AND XXPOV.VENDOR_ID = XXPOVS.VENDOR_ID \n                     AND XXPOVS.ORG_ID = OOD.OPERATING_UNIT \n                     AND HOU.ORGANIZATION_ID = OOD.OPERATING_UNIT \n                     AND XXPOVS.TERMS_ID = APT.TERM_ID ( + ) \n                     AND XXPOV.VENDOR_ID = XXVD.VENDOR_ID ( + ) \n                     AND OOD.ORGANIZATION_CODE = '\"&ORG&\"'\n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"EXTRACT_DATE\", \"Extract Date\"}, {\"SUPPLIER_CREATION_DATE\", \"Supplier Creation Date\"}, {\"SUPPLIER_LAST_UPDATE_DATE\", \"Supplier Last Update Date\"}, {\"SUPPLIER_NUMBER\", \"Supplier Number\"}, {\"VENDOR_NAME\", \"Supplier Name\"}, {\"VENDOR_NAME_ALT\", \"Supplier Name Alternate\"}, {\"VENDOR_SITE_CODE\", \"Supplier Site Code\"}, {\"VENDOR_SITE_CODE_ALT\", \"Supplier Site Code Alternate\"}, {\"PRODUCTION_SUPPLIER_FLAG\", \"Production Supplier Flag\"}, {\"PAY_SITE_FLAG\", \"Pay Site Flag\"}, {\"PURCHASING_SITE_FLAG\", \"Purchasing Site Flag\"}, {\"CITY\", \"City\"}, {\"COUNTRY\", \"Country\"}, {\"COUNTRY_OF_ORIGIN_CODE\", \"Country of Origin\"}, {\"ACTIVE_SUPPLIER_FLAG\", \"Active Supplier Flag\"}, {\"INACTIVE_DATE\", \"Inactive Date\"}, {\"INVOICE_CURRENCY_CODE\", \"Invoice Currency\"}, {\"PAYMENT_CURRENCY_CODE\", \"Payment Currency\"}, {\"PAYMENT_METHOD_LOOKUP_CODE\", \"Payment Method\"}, {\"VENDOR_TYPE_LOOKUP_CODE\", \"Supplier Type\"}, {\"ISUPPLIER_FORECAST_FLAG\", \"ISupplier Forecast Flag\"}, {\"FOB_LOOKUP_CODE\", \"FOB\"}, {\"FREIGHT_TERMS_LOOKUP_CODE\", \"Freight Term\"}, {\"PAYMENT_TERM\", \"Payment Term\"}, {\"ISUPPLIER_FLAG\", \"ISupplier Flag\"}, {\"FIRST_PO_ACCEPTANCE\", \"ISupplier First Acceptance\"}, {\"LAST_PO_ACCEPTANCE\", \"ISupplier Last Acceptance\"}, {\"INTERNAL_SUPPLIER_FLAG\", \"Internal Supplier Flag\"}, {\"LAST_INVOICE_DATE\", \"Last Invoice Date\"}, {\"ISUPPLIER_USER_COUNT\", \"ISupplier User Count\"}, {\"SUPPLIER_LEAD\", \"Supplier Lead\"}, {\"SUPPLIER_CLASS\", \"Supplier Class\"}, {\"SSM_LEAD\", \"SSM Lead\"}, {\"SUPPLIER_CATEGORY\", \"Supplier Category\"}, {\"MASTER_SUPPLIER\", \"Master Supplier\"}, {\"KEY_AND_RISK_FLAG\", \"Key and Risk Flag\"}, {\"KPI_FLAG\", \"KPI Required Flag\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared ORG = let\r\n  ORG = \"LDP\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type text]\r\nin\r\n  ORG;\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"Buyer","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Buyer.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"AGENT_ID","dataType":"int64"},{"name":"Buyer Name","dataType":"string"},{"name":"PPV1 Approver","dataType":"string"},{"name":"PPV2 Approver","dataType":"string"},{"name":"Buyer Active Flag","dataType":"string"},{"name":"User End Date","dataType":"dateTime"},{"name":"PO Buyer Flag","dataType":"string"},{"name":"Default Buyer Flag","dataType":"string"},{"name":"Location","dataType":"string"},{"name":"Supervisor Name","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-13T05:03:06.2765275+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/97c3e4fe-bcd3-4d60-bb61-245f3aa35cbe/Buyer.csv?snapshot=2022-06-13T05%3A03%3A01.5913855Z"}]},{"$type":"LocalEntity","name":"Supplier_Contact","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Supplier_Contact.csv"},"attributes":[{"name":"Supplier Name","dataType":"string"},{"name":"Contact Name","dataType":"string"},{"name":"Contact Country","dataType":"string"},{"name":"Contact Area","dataType":"string"},{"name":"Contact Phone","dataType":"string"},{"name":"Email Address","dataType":"string"},{"name":"Supplier Site Code","dataType":"string"},{"name":"VENDOR_SITE_ID","dataType":"double"},{"name":"VENDOR_CONTACT_ID","dataType":"double"},{"name":"Inactive Date","dataType":"dateTime"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-13T05:02:49.1819342+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/97c3e4fe-bcd3-4d60-bb61-245f3aa35cbe/Supplier_Contact.csv?snapshot=2022-06-13T05%3A02%3A47.6833533Z"}]},{"$type":"LocalEntity","name":"Supplier","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Supplier.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Supplier Number","dataType":"string"},{"name":"Supplier Name","dataType":"string"},{"name":"Supplier Name Alternate","dataType":"string"},{"name":"VENDOR_SITE_ID","dataType":"double"},{"name":"VENDOR_ID","dataType":"double"},{"name":"Supplier Site Code","dataType":"string"},{"name":"Supplier Site Code Alternate","dataType":"string"},{"name":"Production Supplier Flag","dataType":"string"},{"name":"Supplier Creation Date","dataType":"dateTime"},{"name":"Supplier Last Update Date","dataType":"dateTime"},{"name":"Pay Site Flag","dataType":"string"},{"name":"Purchasing Site Flag","dataType":"string"},{"name":"City","dataType":"string"},{"name":"Country","dataType":"string"},{"name":"Country of Origin","dataType":"string"},{"name":"Active Supplier Flag","dataType":"string"},{"name":"Inactive Date","dataType":"dateTime"},{"name":"Invoice Currency","dataType":"string"},{"name":"Payment Currency","dataType":"string"},{"name":"Payment Method","dataType":"string"},{"name":"Supplier Type","dataType":"string"},{"name":"Internal Supplier Flag","dataType":"string"},{"name":"ISupplier Forecast Flag","dataType":"string"},{"name":"FOB","dataType":"string"},{"name":"Freight Term","dataType":"string"},{"name":"ISupplier Flag","dataType":"string"},{"name":"Payment Term","dataType":"string"},{"name":"ISupplier First Acceptance","dataType":"dateTime"},{"name":"ISupplier Last Acceptance","dataType":"dateTime"},{"name":"Last Invoice Date","dataType":"dateTime"},{"name":"ISupplier User Count","dataType":"double"},{"name":"Supplier Lead","dataType":"string"},{"name":"Supplier Class","dataType":"string"},{"name":"Supplier Category","dataType":"string"},{"name":"SSM Lead","dataType":"string"},{"name":"Master Supplier","dataType":"string"},{"name":"Key and Risk Flag","dataType":"string"},{"name":"KPI Required Flag","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-13T05:02:56.1593287+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/97c3e4fe-bcd3-4d60-bb61-245f3aa35cbe/Supplier.csv?snapshot=2022-06-13T05%3A02%3A53.5975351Z"}]}]}