{"name":"lokale_Daten_Interflex","description":"","version":"1.0","culture":"en-US","modifiedTime":"2022-06-02T10:33:48.695898+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":true,"queriesMetadata":{"Produktivitaet_fuerPowerBI":{"queryId":"8b6d5863-0afe-4641-aaeb-3b2857bbefd6","queryName":"Produktivitaet_fuerPowerBI","loadEnabled":true},"gestempelteZeit_proKst":{"queryId":"c68402fa-6f1f-418f-993f-a7e4e70d641f","queryName":"gestempelteZeit_proKst","loadEnabled":true},"FACT_INTERFLEXZEITEN_UEBERSICHT":{"queryId":"e3005a68-e2fc-463c-890a-0c88208c35dc","queryName":"FACT_INTERFLEXZEITEN_UEBERSICHT","loadEnabled":true},"FACT_InterflexZeiten":{"queryId":"52b74758-0215-4a2b-b546-4dae58503fb1","queryName":"FACT_InterflexZeiten","loadEnabled":true},"DIM_InterflexKostenstellen":{"queryId":"d826b630-e12c-413a-bd4e-18e0a39f1201","queryName":"DIM_InterflexKostenstellen","loadEnabled":true}},"document":"section Section1;\r\nshared Produktivitaet_fuerPowerBI = let\r\n  Source = Sql.Database(\"lbksql_Statistiken\", \"lbk_Statistiken_DB\", [CommandTimeout = #duration(0, 0, 10, 0), Query = \"Select * From S0_Produktivitaet_fuerPowerBI\"]),\r\n  #\"Calculated date\" = Table.TransformColumns(Source, {{\"StartDatum\", each DateTime.Date(_), type date}})\r\nin\r\n  #\"Calculated date\";\r\nshared gestempelteZeit_proKst = let\r\n  Source = Sql.Database(\"lbksql_LBKZeitrueckmeldungenProd\", \"lbk_ZeitrueckmeldungenProd_DB\", [CommandTimeout = #duration(0, 0, 10, 0), Query = \"Select * From S1_LDP_Prod_Daten_proKst_gestempelt\"]),\r\n  #\"Removed columns\" = Table.RemoveColumns(Source, {\"Date_gestempelteKst_ID\"}),\r\n  #\"Calculated date\" = Table.TransformColumns(#\"Removed columns\", {{\"Datum\", each DateTime.Date(_), type date}}),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Calculated date\", {{\"SumZeit_gestempelt\", \"SumZeit_gestempelt[h]\"}}),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Renamed columns\", {{\"gestempelte-Kostenstelle\", Int64.Type}})\r\nin\r\n  #\"Changed column type\";\r\nshared FACT_INTERFLEXZEITEN_UEBERSICHT = let\r\n  Source = Sql.Database(\"lbksql_LBKZeitrueckmeldungenProd\", \"lbk_ZeitrueckmeldungenProd_DB\", [CommandTimeout = #duration(0, 0, 10, 0), Query = \"Select * From S_InterflexZeiten_Uebersicht\"]),\r\n  #\"Calculated date\" = Table.TransformColumns(Source, {{\"Datum\", each DateTime.Date(_), type date}}),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Calculated date\", {{\"Kostenstelle\", Int64.Type}})\r\nin\r\n  #\"Changed column type\";\r\nshared FACT_InterflexZeiten = let\r\n  Source = Sql.Database(\"lbksql_LBKZeitrueckmeldungenProd\", \"lbk_ZeitrueckmeldungenProd_DB\", [CommandTimeout = #duration(0, 0, 10, 0), Query = \"Select * From S_PBI_Interflex_gestempelteZeiten\"]),\r\n  #\"Calculated date\" = Table.TransformColumns(Source, {{\"Datum\", each DateTime.Date(_), type date}})\r\nin\r\n  #\"Calculated date\";\r\nshared DIM_InterflexKostenstellen = let\r\n  Source = Sql.Database(\"lbksql_LBKZeitrueckmeldungenProd\", \"lbk_ZeitrueckmeldungenProd_DB\", [CommandTimeout = #duration(0, 0, 10, 0), Query = \"Select * From S_PBI_InterflexKostenstellen\"])\r\nin\r\n  Source;\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"Produktivitaet_fuerPowerBI","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Produktivitaet_fuerPowerBI.csv"},"attributes":[{"name":"ProductLine","dataType":"string"},{"name":"StartDatum","dataType":"date"},{"name":"gestempelteZeit","dataType":"double"},{"name":"AnzahlLaser_inklFaktor","dataType":"double"},{"name":"AnzahlLaser","dataType":"int64"},{"name":"Prod_proWoche","dataType":"double"},{"name":"Std_proLaser_proWoche","dataType":"double"},{"name":"Prod_imMittel","dataType":"double"},{"name":"Std_proLaser_imMittel","dataType":"double"},{"name":"Ziel","dataType":"double"},{"name":"Abteilung","dataType":"string"},{"name":"Lasertyp","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T00:00:16.8895931+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/e919a6ba-4d0b-4442-87c8-24c3784782f3/Produktivitaet_fuerPowerBI.csv?snapshot=2022-06-13T00%3A00%3A16.8396492Z"}]},{"$type":"LocalEntity","name":"gestempelteZeit_proKst","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"gestempelteZeit_proKst.csv"},"attributes":[{"name":"Datum","dataType":"date"},{"name":"gestempelte-Kostenstelle","dataType":"int64"},{"name":"gestempelte-Produktgruppe","dataType":"string"},{"name":"gestempelte-Abteilung","dataType":"string"},{"name":"SumZeit_gestempelt[h]","dataType":"double"},{"name":"fuerProduktivitaet","dataType":"boolean"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T00:00:17.7180464+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/e919a6ba-4d0b-4442-87c8-24c3784782f3/gestempelteZeit_proKst.csv?snapshot=2022-06-13T00%3A00%3A17.6781673Z"}]},{"$type":"LocalEntity","name":"FACT_INTERFLEXZEITEN_UEBERSICHT","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"FACT_INTERFLEXZEITEN_UEBERSICHT.csv"},"attributes":[{"name":"Datum","dataType":"date"},{"name":"Kostenstelle","dataType":"int64"},{"name":"Produktgruppe","dataType":"string"},{"name":"Abteilung","dataType":"string"},{"name":"SumZeit_gestempelt","dataType":"double"},{"name":"fuerProduktivitaet","dataType":"boolean"},{"name":"AnzahLMA_abwesend","dataType":"int64"},{"name":"AnzahLMA_Gleitzeit_kleiner_halberTag","dataType":"int64"},{"name":"AnzahLMA_anwesend","dataType":"int64"},{"name":"AnzahlMA_Kst100","dataType":"int64"},{"name":"AnzahlMA_ungeplant_abwesend","dataType":"int64"},{"name":"AnzahLMA_geliehen","dataType":"int64"},{"name":"AnzahLMA_verliehen","dataType":"int64"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T00:01:23.8635732+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/e919a6ba-4d0b-4442-87c8-24c3784782f3/FACT_INTERFLEXZEITEN_UEBERSICHT.csv?snapshot=2022-06-13T00%3A01%3A23.8241357Z"}]},{"$type":"LocalEntity","name":"FACT_InterflexZeiten","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"FACT_InterflexZeiten.csv"},"attributes":[{"name":"Datum","dataType":"date"},{"name":"Stamm-Kostenstelle","dataType":"double"},{"name":"gestempelte-Kostenstelle","dataType":"double"},{"name":"gestempelte Zeit [h]","dataType":"double"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T00:00:19.6393186+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/e919a6ba-4d0b-4442-87c8-24c3784782f3/FACT_InterflexZeiten.csv?snapshot=2022-06-13T00%3A00%3A19.6160529Z"}]},{"$type":"LocalEntity","name":"DIM_InterflexKostenstellen","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"DIM_InterflexKostenstellen.csv"},"attributes":[{"name":"Kostenstelle","dataType":"int64"},{"name":"Gruppe","dataType":"string"},{"name":"Bezeichnung","dataType":"string"},{"name":"fuerProduktivitaet","dataType":"boolean"},{"name":"abgeschaltet","dataType":"dateTime"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T00:00:16.8270763+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/e919a6ba-4d0b-4442-87c8-24c3784782f3/DIM_InterflexKostenstellen.csv?snapshot=2022-06-13T00%3A00%3A16.7806832Z"}]}]}