{"name":"lokale_Daten_Cumulus","description":"Daten wurde aus der XML Datei auf den SQL-Server geschrieben","version":"1.0","culture":"en-US","modifiedTime":"2021-10-25T06:35:07.9859032+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"Cumulus_Assemblies (PBIdataflow-SQL-Cumulus)":{"queryId":"6bf047c0-886d-4ab8-ac4f-ac2305c7f37c","queryName":"Cumulus_Assemblies (PBIdataflow-SQL-Cumulus)","loadEnabled":true},"Cumulus_WOActive (PBIdataflow-SQL-Cumulus)":{"queryId":"96be9bd3-bb63-4e63-9f0e-c5b2cb7ce544","queryName":"Cumulus_WOActive (PBIdataflow-SQL-Cumulus)","loadEnabled":true},"Cumulus_WOCompletions (PBIdataflow-SQL-Cumulus)":{"queryId":"69068226-09c4-499b-b13b-5648fd8ac587","queryName":"Cumulus_WOCompletions (PBIdataflow-SQL-Cumulus)","loadEnabled":true},"Sapphire_TimeStudies_660":{"queryId":"558a9196-4be0-4498-9dbd-d1ee05c9efcb","queryName":"Sapphire_TimeStudies_660","loadEnabled":true},"Sapphire_TimeStudies_605":{"queryId":"4ae7b8ef-e371-4efb-b191-ee73f9968df6","queryName":"Sapphire_TimeStudies_605","loadEnabled":true},"Sapphire_TimeStudies":{"queryId":"31d85e48-0a71-43dc-b78b-7bebf25c5180","queryName":"Sapphire_TimeStudies","loadEnabled":true}},"document":"section Section1;\r\nshared #\"Cumulus_Assemblies (PBIdataflow-SQL-Cumulus)\" = let\r\n  Source = Sql.Database(\"delbcsql_CumulusDaten\", \"CumulusDaten\"),\r\n  #\"Navigation 1\" = Source{[Schema = \"dbo\", Item = \"Cumulus_Assemblies_fuerPBI\"]}[Data]\r\nin\r\n  #\"Navigation 1\";\r\nshared #\"Cumulus_WOActive (PBIdataflow-SQL-Cumulus)\" = let\r\n  Source = Sql.Database(\"delbcsql_CumulusDaten\", \"CumulusDaten\"),\r\n  #\"Navigation 1\" = Source{[Schema = \"dbo\", Item = \"Cumulus_WOActive_fuerPBI\"]}[Data],\r\n  #\"Calculated date\" = Table.TransformColumns(#\"Navigation 1\", {{\"CREATE_DATE\", each DateTime.Date(_), type date}})\r\nin\r\n  #\"Calculated date\";\r\nshared #\"Cumulus_WOCompletions (PBIdataflow-SQL-Cumulus)\" = let\r\n  Source = Sql.Database(\"delbcsql_CumulusDaten\", \"CumulusDaten\"),\r\n  #\"Navigation 1\" = Source{[Schema = \"dbo\", Item = \"Cumulus_WOCompletions_fuerPBI\"]}[Data],\r\n  #\"Calculated date\" = Table.TransformColumns(#\"Navigation 1\", {{\"CREATE_DATE\", each DateTime.Date(_), type date}}),\r\n  #\"Calculated date 1\" = Table.TransformColumns(#\"Calculated date\", {{\"COMPLETE_DATE\", each DateTime.Date(_), type date}})\r\nin\r\n  #\"Calculated date 1\";\r\nshared Sapphire_TimeStudies_660 = let\r\n  Quelle = Xml.Tables(File.Contents(\"\\\\cohr\\eu\\delbc\\groups\\Operations\\Database\\benoetigteDateien\\CumulusDaten\\CumulusDaten_xmlDateien\\CumulusTimeStudies_Data\\Sapphire_TimeStudyPoints_660.xml\")),\r\n  Table0 = Quelle{0}[Table],\r\n  #\"Ge채nderter Typ\" = Table.TransformColumnTypes(Table0, {{\"POINT_DATE\", type datetime}, {\"IGNORE_POINT\", type logical}, {\"DURATION_MINUTES\", type number}, {\"DURATION_HOURS\", type number}, {\"WORK_ORDER\", type text}, {\"WORK_ORDER_TYPE\", type text}, {\"ORG\", type text}, {\"PART_NUMBER\", type text}, {\"DESCRIPTION\", type text}, {\"SERIAL_NUMBER\", type text}, {\"QTY\", Int64.Type}, {\"PROCESS\", type text}, {\"FLOW_INDEX\", Int64.Type}}),\r\n  #\"Calculated date\" = Table.TransformColumns(#\"Ge채nderter Typ\", {{\"POINT_DATE\", each DateTime.Date(_), type date}}),\r\n  #\"Added custom\" = Table.AddColumn(#\"Calculated date\", \"TS Number\", each 660),\r\n  #\"Reordered columns\" = Table.ReorderColumns(#\"Added custom\", {\"TS Number\", \"POINT_DATE\", \"IGNORE_POINT\", \"DURATION_MINUTES\", \"DURATION_HOURS\", \"WORK_ORDER\", \"WORK_ORDER_TYPE\", \"ORG\", \"PART_NUMBER\", \"DESCRIPTION\", \"SERIAL_NUMBER\", \"QTY\", \"OPERATOR\", \"PROCESS\", \"FLOW_INDEX\", \"FLOW_STEP_DESCRIPTION\", \"NOTES\"}),\r\n  #\"Transform columns\" = Table.TransformColumnTypes(#\"Reordered columns\", {{\"TS Number\", type text}, {\"NOTES\", type text}}),\r\n  #\"Replace errors\" = Table.ReplaceErrorValues(#\"Transform columns\", {{\"TS Number\", null}, {\"NOTES\", null}}),\r\n  #\"Remove columns\" = Table.RemoveColumns(#\"Replace errors\", Table.ColumnsOfType(#\"Replace errors\", {type table, type record, type list, type nullable binary, type binary, type function}))\r\nin\r\n  #\"Remove columns\";\r\nshared Sapphire_TimeStudies_605 = let\r\n  Quelle = Xml.Tables(File.Contents(\"\\\\cohr\\eu\\delbc\\groups\\Operations\\Database\\benoetigteDateien\\CumulusDaten\\CumulusDaten_xmlDateien\\CumulusTimeStudies_Data\\Sapphire_TimeStudyPoints_605.xml\")),\r\n  Table0 = Quelle{0}[Table],\r\n  #\"Ge채nderter Typ\" = Table.TransformColumnTypes(Table0, {{\"POINT_DATE\", type datetime}, {\"IGNORE_POINT\", type logical}, {\"DURATION_MINUTES\", type number}, {\"DURATION_HOURS\", type number}, {\"WORK_ORDER\", type text}, {\"WORK_ORDER_TYPE\", type text}, {\"ORG\", type text}, {\"PART_NUMBER\", type text}, {\"DESCRIPTION\", type text}, {\"SERIAL_NUMBER\", type text}, {\"QTY\", Int64.Type}, {\"PROCESS\", type text}, {\"FLOW_INDEX\", Int64.Type}}),\r\n  #\"Calculated date\" = Table.TransformColumns(#\"Ge채nderter Typ\", {{\"POINT_DATE\", each DateTime.Date(_), type date}}),\r\n  #\"Added custom\" = Table.AddColumn(#\"Calculated date\", \"TS Number\", each 605),\r\n  #\"Reordered columns\" = Table.ReorderColumns(#\"Added custom\", {\"TS Number\", \"POINT_DATE\", \"IGNORE_POINT\", \"DURATION_MINUTES\", \"DURATION_HOURS\", \"WORK_ORDER\", \"WORK_ORDER_TYPE\", \"ORG\", \"PART_NUMBER\", \"DESCRIPTION\", \"SERIAL_NUMBER\", \"QTY\", \"OPERATOR\", \"PROCESS\", \"FLOW_INDEX\", \"FLOW_STEP_DESCRIPTION\", \"NOTES\"}),\r\n  #\"Transform columns\" = Table.TransformColumnTypes(#\"Reordered columns\", {{\"TS Number\", type text}, {\"NOTES\", type text}}),\r\n  #\"Replace errors\" = Table.ReplaceErrorValues(#\"Transform columns\", {{\"TS Number\", null}, {\"NOTES\", null}}),\r\n  #\"Remove columns\" = Table.RemoveColumns(#\"Replace errors\", Table.ColumnsOfType(#\"Replace errors\", {type table, type record, type list, type nullable binary, type binary, type function}))\r\nin\r\n  #\"Remove columns\";\r\nshared Sapphire_TimeStudies = let\r\n  Source = Table.Combine({Sapphire_TimeStudies_605, Sapphire_TimeStudies_660})\r\nin\r\n  Source;\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"Cumulus_Assemblies (PBIdataflow-SQL-Cumulus)","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Cumulus_Assemblies%20%28PBIdataflow-SQL-Cumulus%29.csv"},"attributes":[{"name":"ProductFamily","dataType":"string"},{"name":"PART_NUMBER","dataType":"string"},{"name":"PART_DESCRIPTION","dataType":"string"},{"name":"TAGS","dataType":"string"},{"name":"TYPE","dataType":"string"},{"name":"PRODUCTION_TYPE","dataType":"string"},{"name":"SapphireGroup_RR_ET","dataType":"string"},{"name":"ORACLE_ITEM_TYPE","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-20T04:30:10.6464699+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/d48a4c7e-9981-444c-aff3-db9e43773479/Cumulus_Assemblies%20(PBIdataflow-SQL-Cumulus).csv?snapshot=2022-05-20T04%3A30%3A10.6277353Z"}]},{"$type":"LocalEntity","name":"Cumulus_WOActive (PBIdataflow-SQL-Cumulus)","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Cumulus_WOActive%20%28PBIdataflow-SQL-Cumulus%29.csv"},"attributes":[{"name":"ProductFamily","dataType":"string"},{"name":"TYPE","dataType":"string"},{"name":"WORK_ORDER","dataType":"string"},{"name":"CREATE_DATE","dataType":"date"},{"name":"PART_NUMBER","dataType":"string"},{"name":"CURRENT_PROCESS","dataType":"string"},{"name":"CURRENT_PROCESS_DESCRIPTION","dataType":"string"},{"name":"FLOW","dataType":"string"},{"name":"NOTES","dataType":"string"},{"name":"QTY","dataType":"int64"},{"name":"SERIAL_NUMBER","dataType":"string"},{"name":"STATUS","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-20T04:30:09.3639847+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/d48a4c7e-9981-444c-aff3-db9e43773479/Cumulus_WOActive%20(PBIdataflow-SQL-Cumulus).csv?snapshot=2022-05-20T04%3A30%3A09.3414766Z"}]},{"$type":"LocalEntity","name":"Cumulus_WOCompletions (PBIdataflow-SQL-Cumulus)","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Cumulus_WOCompletions%20%28PBIdataflow-SQL-Cumulus%29.csv"},"attributes":[{"name":"ProductFamily","dataType":"string"},{"name":"WORK_ORDER","dataType":"string"},{"name":"STATUS","dataType":"string"},{"name":"CREATE_DATE","dataType":"date"},{"name":"COMPLETE_DATE","dataType":"date"},{"name":"TYPE","dataType":"string"},{"name":"FLOW","dataType":"string"},{"name":"SERIAL_NUMBER","dataType":"string"},{"name":"PART_NUMBER","dataType":"string"},{"name":"DESCRIPTION","dataType":"string"},{"name":"QTY","dataType":"int64"},{"name":"CYCLE_TIME_SERIES_MINUTES","dataType":"double"},{"name":"CYCLE_TIME_WORKORDER_MINUTES","dataType":"double"},{"name":"DEVIATIONS","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-20T04:30:12.9836769+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/d48a4c7e-9981-444c-aff3-db9e43773479/Cumulus_WOCompletions%20(PBIdataflow-SQL-Cumulus).csv?snapshot=2022-05-20T04%3A30%3A12.9464004Z"}]},{"$type":"LocalEntity","name":"Sapphire_TimeStudies_660","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Sapphire_TimeStudies_660.csv"},"attributes":[{"name":"TS Number","dataType":"string"},{"name":"POINT_DATE","dataType":"date"},{"name":"IGNORE_POINT","dataType":"boolean"},{"name":"DURATION_MINUTES","dataType":"double"},{"name":"DURATION_HOURS","dataType":"double"},{"name":"WORK_ORDER","dataType":"string"},{"name":"WORK_ORDER_TYPE","dataType":"string"},{"name":"ORG","dataType":"string"},{"name":"PART_NUMBER","dataType":"string"},{"name":"DESCRIPTION","dataType":"string"},{"name":"SERIAL_NUMBER","dataType":"string"},{"name":"QTY","dataType":"int64"},{"name":"PROCESS","dataType":"string"},{"name":"FLOW_INDEX","dataType":"int64"},{"name":"NOTES","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-20T04:30:21.3528261+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/d48a4c7e-9981-444c-aff3-db9e43773479/Sapphire_TimeStudies_660.csv?snapshot=2022-05-20T04%3A30%3A20.6009925Z"}]},{"$type":"LocalEntity","name":"Sapphire_TimeStudies_605","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Sapphire_TimeStudies_605.csv"},"attributes":[{"name":"TS Number","dataType":"string"},{"name":"POINT_DATE","dataType":"date"},{"name":"IGNORE_POINT","dataType":"boolean"},{"name":"DURATION_MINUTES","dataType":"double"},{"name":"DURATION_HOURS","dataType":"double"},{"name":"WORK_ORDER","dataType":"string"},{"name":"WORK_ORDER_TYPE","dataType":"string"},{"name":"ORG","dataType":"string"},{"name":"PART_NUMBER","dataType":"string"},{"name":"DESCRIPTION","dataType":"string"},{"name":"SERIAL_NUMBER","dataType":"string"},{"name":"QTY","dataType":"int64"},{"name":"PROCESS","dataType":"string"},{"name":"FLOW_INDEX","dataType":"int64"},{"name":"NOTES","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-20T04:30:32.4363478+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/d48a4c7e-9981-444c-aff3-db9e43773479/Sapphire_TimeStudies_605.csv?snapshot=2022-05-20T04%3A30%3A31.1079415Z"}]},{"$type":"LocalEntity","name":"Sapphire_TimeStudies","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Sapphire_TimeStudies.csv"},"annotations":[{"name":"pbi:EntityTypeDisplayHint","value":"CalculatedEntity"}],"attributes":[{"name":"TS Number","dataType":"string"},{"name":"POINT_DATE","dataType":"date"},{"name":"IGNORE_POINT","dataType":"boolean"},{"name":"DURATION_MINUTES","dataType":"double"},{"name":"DURATION_HOURS","dataType":"double"},{"name":"WORK_ORDER","dataType":"string"},{"name":"WORK_ORDER_TYPE","dataType":"string"},{"name":"ORG","dataType":"string"},{"name":"PART_NUMBER","dataType":"string"},{"name":"DESCRIPTION","dataType":"string"},{"name":"SERIAL_NUMBER","dataType":"string"},{"name":"QTY","dataType":"int64"},{"name":"PROCESS","dataType":"string"},{"name":"FLOW_INDEX","dataType":"int64"},{"name":"NOTES","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-20T04:34:24.8596088+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/d48a4c7e-9981-444c-aff3-db9e43773479/Sapphire_TimeStudies.csv?snapshot=2022-05-20T04%3A34%3A24.8084244Z"}]}]}