{"name":"lokale_Daten","description":"Verbindungen zum SQL-Server und zu den Files aus dem Statistiken\\InputOrdner\nYield\nCycleTime\nProduktivität\nUnfälle \nSavings","version":"1.0","culture":"en-US","modifiedTime":"2022-06-09T07:11:35.5651712+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":true,"queriesMetadata":{"BacklogHistory":{"queryId":"5e2be702-8334-4c23-b1ba-7525225debb6","queryName":"BacklogHistory","loadEnabled":true},"Teilekat_txtFile":{"queryId":"bf47fe01-f16e-42b2-9e86-5ebc3cd6067e","queryName":"Teilekat_txtFile","loadEnabled":true},"Teilekat_txtFile_Kategorien":{"queryId":"7c51bccf-ce14-400c-a4e5-6a4517f045e7","queryName":"Teilekat_txtFile_Kategorien","loadEnabled":true},"DIM_ITEM_REFERENCETABLE_INTERN":{"queryId":"b3f554a2-663a-4ecf-a79e-2bd361da060f","queryName":"DIM_ITEM_REFERENCETABLE_INTERN","loadEnabled":true},"ReschedulingData_SVC":{"queryId":"5a260781-1690-4f81-b567-945abdcccd97","queryName":"ReschedulingData_SVC","loadEnabled":true},"ReschedulingData_Orders":{"queryId":"a24cd649-6768-4c95-b834-ee9de963974a","queryName":"ReschedulingData_Orders","loadEnabled":true}},"document":"section Section1;\r\nshared BacklogHistory = let\r\n  Source = Sql.Database(\"lbksql_DatenERPSystem\", \"LBK_DatenERPSystem_DB\", [Query = \"Select * From S5_Backlog\"]),\r\n  #\"Calculated date\" = Table.TransformColumns(Source, {{\"ReportedDate\", each DateTime.Date(_), type date}}),\r\n  #\"Sorted rows\" = Table.Sort(#\"Calculated date\", {{\"ReportedDate\", Order.Descending}})\r\nin\r\n  #\"Sorted rows\";\r\nshared Teilekat_txtFile = let\r\n  Source = Csv.Document(File.Contents(\"\\\\cohr\\eu\\delbc\\groups\\Operations\\OracleExportFiles\\teilkat.txt\"), [Delimiter = \"#(tab)\", Columns = 90, QuoteStyle = QuoteStyle.None]),\r\n  #\"Promoted headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"ITEM\", type text}, {\"ORG ID\", Int64.Type}, {\"description\", type text}, {\"Plannercode\", type text}, {\"Buyer\", type text}, {\"Item Cost\", type number}, {\"Material Cost\", type number}, {\"Material Overhead Cost\", type number}, {\"Resource Cost\", type number}, {\"OSP Cost\", type number}, {\"Overheader Cost\", type number}, {\"Nettable Qty\", Int64.Type}, {\"Non Nettable Qty\", Int64.Type}, {\"Safety Stock\", Int64.Type}, {\"Sourcing commodity\", type text}, {\"Product Family\", type text}, {\"Product Line\", type text}, {\"Forecast Field\", type text}, {\"Org Product Family\", type text}, {\"Org Product Line\", type text}, {\"Org Forecast Field\", type text}, {\"Lead Time\", type number}, {\"Make/Buy Flag\", type text}, {\"Item Status\", type text}, {\"WIP Supply Type\", type text}, {\"SubInventory + Locator\", type text}, {\"Fixed Lot Multiplier\", Int64.Type}, {\"Fixed Order Quantity\", Int64.Type}, {\"Fixed Days Supply\", Int64.Type}, {\"Minimum Order Qty\", Int64.Type}, {\"Maximum Order Qty\", Int64.Type}, {\"Min MinMax Quantity\", type text}, {\"Max MinMax Quantity\", type text}, {\"Rev\", type text}, {\"UOM\", type text}, {\"Qty Rcvd not Del\", type text}, {\"Processing Lead Time\", type number}, {\"Current Issues FY\", Int64.Type}, {\"Issues Last FY\", Int64.Type}, {\"Issues Last 12 Months\", Int64.Type}, {\"Issues Last 90 Days\", Int64.Type}, {\"Current Recipts FY\", Int64.Type}, {\"Receipts Last FY\", Int64.Type}, {\"Receipts Last 12 Months\", Int64.Type}, {\"Receipts Last 90 Days\", Int64.Type}, {\"CC Adj Last 12 Months\", type text}, {\"Last Issue Date\", type date}, {\"Last Receipt Date\", type date}, {\"Qty on Order\", Int64.Type}, {\"Gross Requirements\", type number}, {\"Gross requirements days 0 - 30\", type number}, {\"Gross requirements days 30 - 60\", type number}, {\"Gross requirements days 60 - 90\", type number}, {\"Gross requirements days 90 - 180\", type number}, {\"Gross requirements days 180 - 360\", type number}, {\"User Item Type\", type text}, {\"Receipt Routing\", type text}, {\"Inventory Planning Method\", type text}, {\"MPS/MRP PLanning Method\", type text}, {\"Commodity Code\", type text}, {\"Creation Date\", type date}, {\"Last Update Date\", type date}, {\"Wip Supply Subinv\", type text}, {\"Wip Supply Locator\", type text}, {\"Completion Subinv\", type text}, {\"Completion Locator\", type text}, {\"Receiv Default Subinv\", type text}, {\"Receiv Default Subinv 2\", type text}, {\"Receiv Default Locator\", type text}, {\"To Receiver\", type text}, {\"Source org or Vendor\", type text}, {\"Source type\", type text}, {\"Lot Control\", type text}, {\"Serial Number Control\", type text}, {\"Release Time Fence\", type text}, {\"By-Products\", type text}, {\"By-Products days 0 - 30\", type text}, {\"By-Products days 30 - 60\", type text}, {\"By-Products days 60 - 90\", type text}, {\"By-Products days 90 - 180\", type text}, {\"By-Products days 180 - 360\", type text}, {\"APOP (Average PO Price Paid)\", type number}, {\"Acceptable Early Days\", Int64.Type}, {\"UOM of Weight\", type text}, {\"Unit Weight\", type number}, {\"Cumulative Total Lead Time\", type number}, {\"Agile Design Org\", type text}, {\"Intransit Qty\", type number}, {\"Preprocessing Lead Time\", type number}, {\"Postprocessing Lead Time\", type number}}),\r\n  #\"Replaced value\" = Table.ReplaceValue(#\"Changed column type\", null, 0, Replacer.ReplaceValue, {\"Issues Last 12 Months\"}),\r\n  #\"Added custom\" = Table.AddColumn(#\"Replaced value\", \"issues in last12months\", each if [Issues Last 12 Months] > 0 then \"Ja\" else \"Nein\"),\r\n  #\"Transform columns\" = Table.TransformColumnTypes(#\"Added custom\", {{\"issues in last12months\", type text}}),\r\n  #\"Replace errors\" = Table.ReplaceErrorValues(#\"Transform columns\", {{\"issues in last12months\", null}})\r\nin\r\n  #\"Replace errors\";\r\nshared Teilekat_txtFile_Kategorien = let\n  Source = Teilekat_txtFile,\n  #\"Removed columns\" = Table.RemoveColumns(Source, {\"ORG ID\", \"Material Cost\", \"Material Overhead Cost\", \"Resource Cost\", \"OSP Cost\", \"Overheader Cost\", \"Nettable Qty\", \"Non Nettable Qty\", \"Safety Stock\", \"Sourcing commodity\", \"Product Family\", \"Product Line\", \"Forecast Field\", \"Lead Time\", \"SubInventory + Locator\", \"Fixed Lot Multiplier\", \"Fixed Order Quantity\", \"Fixed Days Supply\", \"Minimum Order Qty\", \"Maximum Order Qty\", \"Min MinMax Quantity\", \"Max MinMax Quantity\", \"Qty Rcvd not Del\", \"Processing Lead Time\", \"Current Issues FY\", \"Issues Last FY\", \"Issues Last 12 Months\", \"Issues Last 90 Days\", \"Current Recipts FY\", \"Receipts Last FY\", \"Receipts Last 12 Months\", \"Receipts Last 90 Days\", \"CC Adj Last 12 Months\", \"Gross requirements days 0 - 30\", \"Gross requirements days 30 - 60\", \"Gross requirements days 60 - 90\", \"Gross requirements days 90 - 180\", \"Gross requirements days 180 - 360\", \"Wip Supply Subinv\", \"Wip Supply Locator\", \"Completion Subinv\", \"Completion Locator\", \"Receiv Default Subinv\", \"Receiv Default Subinv 2\", \"Receiv Default Locator\", \"Source org or Vendor\", \"Source type\", \"Lot Control\", \"Serial Number Control\", \"Release Time Fence\", \"By-Products\", \"By-Products days 0 - 30\", \"By-Products days 30 - 60\", \"By-Products days 60 - 90\", \"By-Products days 90 - 180\", \"By-Products days 180 - 360\", \"APOP (Average PO Price Paid)\", \"Acceptable Early Days\", \"UOM of Weight\", \"Unit Weight\", \"Cumulative Total Lead Time\"}),\n  #\"Filtered rows\" = Table.SelectRows(#\"Removed columns\", each not Text.StartsWith([ITEM], \"D\"))\nin\n  #\"Filtered rows\";\r\nshared DIM_ITEM_REFERENCETABLE_INTERN = let\r\n  Source = Sql.Database(\"lbksql_Teilekatalog\", \"LBK_Teilekatalog_DB\", [Query = \"Select * From S_PBI_Verweistabelle\"]),\r\n  #\"Reordered columns\" = Table.ReorderColumns(Source, {\"Item\", \"Bezeichnung\", \"Lasertyp\", \"Product Family\",   \"Leistungsklasse\", \"Lasertyp_prodplan\", \"Auslieferbezeichnung\", \"commodityCode\", \"Wellenlaenge\", \"Leistung_mW\", \"GruppierungFuerAuswertung\", \"OTDGruppe\", \"TechFam\", \"zaehlenFuerStatistiken\"}),\r\n  #\"Removed columns\" = Table.RemoveColumns(#\"Reordered columns\", {\"Forecast Field\", \"ForecastField\"})\r\nin\r\n  #\"Removed columns\";\r\nshared ReschedulingData_SVC = let\r\n  Source = Sql.Database(\"lbksql_Auslieferungen\", \"LBK_Auslieferungen_DB\", [Query = \"Select * From Sicht_Rescheduling_Data_SVC\"]),\r\n  #\"Calculated date\" = Table.TransformColumns(Source, {{\"Datum\", each DateTime.Date(_), type nullable date}, {\"scheduledDate_old\", each DateTime.Date(_), type nullable date}, {\"scheduledDate_new\", each DateTime.Date(_), type nullable date}, {\"TestendePlusOA_Eintrag\", each DateTime.Date(_), type nullable date}, {\"promisedDate\", each DateTime.Date(_), type nullable date}}),\r\n  #\"Calculated date 1\" = Table.TransformColumns(#\"Calculated date\", {{\"geaendertes_Feld_Eintrag\", each DateTime.Date(_), type nullable date}}),\r\n  #\"Removed columns\" = Table.RemoveColumns(#\"Calculated date 1\", {\"ersteEintrag\"}),\r\n  #\"Sorted rows\" = Table.Sort(#\"Removed columns\", {{\"Datum\", Order.Descending}})\r\nin\r\n  #\"Sorted rows\";\r\nshared ReschedulingData_Orders = let\r\n  Source = Sql.Database(\"lbksql_Auslieferungen\", \"LBK_Auslieferungen_DB\", [Query = \"Select * From Sicht_Rescheduling_Data\"]),\r\n  #\"Sorted rows\" = Table.Sort(Source, {{\"Datum\", Order.Descending}}),\r\n  #\"Calculated date\" = Table.TransformColumns(#\"Sorted rows\", {{\"Datum\", each DateTime.Date(_), type nullable date}, {\"RequestDate\", each DateTime.Date(_), type nullable date}, {\"PromisedDate\", each DateTime.Date(_), type nullable date}, {\"scheduledDate_old\", each DateTime.Date(_), type nullable date}, {\"scheduledDate_new\", each DateTime.Date(_), type nullable date}}),\r\n  #\"Removed columns\" = Table.RemoveColumns(#\"Calculated date\", {\"ersteEintrag\", \"Timestamp\"})\r\nin\r\n  #\"Removed columns\";\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"BacklogHistory","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"BacklogHistory.csv"},"attributes":[{"name":"ReportedDate","dataType":"date"},{"name":"OrderNr_Line","dataType":"string"},{"name":"PrimaryOrg","dataType":"string"},{"name":"Reporting Entity","dataType":"string"},{"name":"Product Family","dataType":"string"},{"name":"Item Number","dataType":"string"},{"name":"Item Description","dataType":"string"},{"name":"Backlog Quantity","dataType":"double"},{"name":"Request Ship Date","dataType":"dateTime"},{"name":"Promise Ship Date","dataType":"dateTime"},{"name":"Schedule Ship Date","dataType":"dateTime"},{"name":"Technical Business Unit","dataType":"string"},{"name":"totaldeltaDays","dataType":"double"},{"name":"Schedule Category","dataType":"string"},{"name":"Warehouse","dataType":"string"},{"name":"BillableFlag","dataType":"string"},{"name":"Line Status","dataType":"string"},{"name":"Customer","dataType":"string"},{"name":"Application Code","dataType":"string"},{"name":"Market Segment","dataType":"string"},{"name":"MasterCustomer","dataType":"string"},{"name":"Order Type","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T06:30:17.5038259+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/7d16328f-64c0-481d-923f-68fbdd2bb2bd/BacklogHistory.csv?snapshot=2022-06-13T06%3A30%3A17.2792023Z"}]},{"$type":"LocalEntity","name":"Teilekat_txtFile","description":"txt-File im Folder L:\\Operations\\Statistiken\\Input\nwird täglich dort reinkopiert","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Teilekat_txtFile.csv"},"attributes":[{"name":"ITEM","dataType":"string"},{"name":"ORG ID","dataType":"int64"},{"name":"description","dataType":"string"},{"name":"Plannercode","dataType":"string"},{"name":"Buyer","dataType":"string"},{"name":"Item Cost","dataType":"double"},{"name":"Material Cost","dataType":"double"},{"name":"Material Overhead Cost","dataType":"double"},{"name":"Resource Cost","dataType":"double"},{"name":"OSP Cost","dataType":"double"},{"name":"Overheader Cost","dataType":"double"},{"name":"Nettable Qty","dataType":"int64"},{"name":"Non Nettable Qty","dataType":"int64"},{"name":"Safety Stock","dataType":"int64"},{"name":"Sourcing commodity","dataType":"string"},{"name":"Product Family","dataType":"string"},{"name":"Product Line","dataType":"string"},{"name":"Forecast Field","dataType":"string"},{"name":"Org Product Family","dataType":"string"},{"name":"Org Product Line","dataType":"string"},{"name":"Org Forecast Field","dataType":"string"},{"name":"Lead Time","dataType":"double"},{"name":"Make/Buy Flag","dataType":"string"},{"name":"Item Status","dataType":"string"},{"name":"WIP Supply Type","dataType":"string"},{"name":"SubInventory + Locator","dataType":"string"},{"name":"Fixed Lot Multiplier","dataType":"int64"},{"name":"Fixed Order Quantity","dataType":"int64"},{"name":"Fixed Days Supply","dataType":"int64"},{"name":"Minimum Order Qty","dataType":"int64"},{"name":"Maximum Order Qty","dataType":"int64"},{"name":"Min MinMax Quantity","dataType":"string"},{"name":"Max MinMax Quantity","dataType":"string"},{"name":"Rev","dataType":"string"},{"name":"UOM","dataType":"string"},{"name":"Qty Rcvd not Del","dataType":"string"},{"name":"Processing Lead Time","dataType":"double"},{"name":"Current Issues FY","dataType":"int64"},{"name":"Issues Last FY","dataType":"int64"},{"name":"Issues Last 12 Months","dataType":"double"},{"name":"Issues Last 90 Days","dataType":"int64"},{"name":"Current Recipts FY","dataType":"int64"},{"name":"Receipts Last FY","dataType":"int64"},{"name":"Receipts Last 12 Months","dataType":"int64"},{"name":"Receipts Last 90 Days","dataType":"int64"},{"name":"CC Adj Last 12 Months","dataType":"string"},{"name":"Last Issue Date","dataType":"date"},{"name":"Last Receipt Date","dataType":"date"},{"name":"Qty on Order","dataType":"int64"},{"name":"Gross Requirements","dataType":"double"},{"name":"Gross requirements days 0 - 30","dataType":"double"},{"name":"Gross requirements days 30 - 60","dataType":"double"},{"name":"Gross requirements days 60 - 90","dataType":"double"},{"name":"Gross requirements days 90 - 180","dataType":"double"},{"name":"Gross requirements days 180 - 360","dataType":"double"},{"name":"User Item Type","dataType":"string"},{"name":"Receipt Routing","dataType":"string"},{"name":"Inventory Planning Method","dataType":"string"},{"name":"MPS/MRP PLanning Method","dataType":"string"},{"name":"Commodity Code","dataType":"string"},{"name":"Creation Date","dataType":"date"},{"name":"Last Update Date","dataType":"date"},{"name":"Wip Supply Subinv","dataType":"string"},{"name":"Wip Supply Locator","dataType":"string"},{"name":"Completion Subinv","dataType":"string"},{"name":"Completion Locator","dataType":"string"},{"name":"Receiv Default Subinv","dataType":"string"},{"name":"Receiv Default Subinv 2","dataType":"string"},{"name":"Receiv Default Locator","dataType":"string"},{"name":"To Receiver","dataType":"string"},{"name":"Source org or Vendor","dataType":"string"},{"name":"Source type","dataType":"string"},{"name":"Lot Control","dataType":"string"},{"name":"Serial Number Control","dataType":"string"},{"name":"Release Time Fence","dataType":"string"},{"name":"By-Products","dataType":"string"},{"name":"By-Products days 0 - 30","dataType":"string"},{"name":"By-Products days 30 - 60","dataType":"string"},{"name":"By-Products days 60 - 90","dataType":"string"},{"name":"By-Products days 90 - 180","dataType":"string"},{"name":"By-Products days 180 - 360","dataType":"string"},{"name":"APOP (Average PO Price Paid)","dataType":"double"},{"name":"Acceptable Early Days","dataType":"int64"},{"name":"UOM of Weight","dataType":"string"},{"name":"Unit Weight","dataType":"double"},{"name":"Cumulative Total Lead Time","dataType":"double"},{"name":"Agile Design Org","dataType":"string"},{"name":"Intransit Qty","dataType":"double"},{"name":"Preprocessing Lead Time","dataType":"double"},{"name":"Postprocessing Lead Time","dataType":"double"},{"name":"issues in last12months","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T06:30:38.3222338+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/7d16328f-64c0-481d-923f-68fbdd2bb2bd/Teilekat_txtFile.csv?snapshot=2022-06-13T06%3A30%3A35.7076007Z"}]},{"$type":"LocalEntity","name":"Teilekat_txtFile_Kategorien","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Teilekat_txtFile_Kategorien.csv"},"annotations":[{"name":"pbi:EntityTypeDisplayHint","value":"CalculatedEntity"}],"attributes":[{"name":"ITEM","dataType":"string"},{"name":"description","dataType":"string"},{"name":"Plannercode","dataType":"string"},{"name":"Buyer","dataType":"string"},{"name":"Item Cost","dataType":"double"},{"name":"Org Product Family","dataType":"string"},{"name":"Org Product Line","dataType":"string"},{"name":"Org Forecast Field","dataType":"string"},{"name":"Make/Buy Flag","dataType":"string"},{"name":"Item Status","dataType":"string"},{"name":"WIP Supply Type","dataType":"string"},{"name":"Rev","dataType":"string"},{"name":"UOM","dataType":"string"},{"name":"Last Issue Date","dataType":"date"},{"name":"Last Receipt Date","dataType":"date"},{"name":"Qty on Order","dataType":"int64"},{"name":"Gross Requirements","dataType":"double"},{"name":"User Item Type","dataType":"string"},{"name":"Receipt Routing","dataType":"string"},{"name":"Inventory Planning Method","dataType":"string"},{"name":"MPS/MRP PLanning Method","dataType":"string"},{"name":"Commodity Code","dataType":"string"},{"name":"Creation Date","dataType":"date"},{"name":"Last Update Date","dataType":"date"},{"name":"To Receiver","dataType":"string"},{"name":"Agile Design Org","dataType":"string"},{"name":"Intransit Qty","dataType":"double"},{"name":"Preprocessing Lead Time","dataType":"double"},{"name":"Postprocessing Lead Time","dataType":"double"},{"name":"issues in last12months","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T06:30:41.8172369+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/7d16328f-64c0-481d-923f-68fbdd2bb2bd/Teilekat_txtFile_Kategorien.csv?snapshot=2022-06-13T06%3A30%3A41.7531259Z"}]},{"$type":"LocalEntity","name":"DIM_ITEM_REFERENCETABLE_INTERN","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"DIM_ITEM_REFERENCETABLE_INTERN.csv"},"attributes":[{"name":"Item","dataType":"string"},{"name":"Bezeichnung","dataType":"string"},{"name":"Lasertyp","dataType":"string"},{"name":"Product Family","dataType":"string"},{"name":"OrgForecastField","dataType":"string"},{"name":"Leistungsklasse","dataType":"string"},{"name":"Lasertyp_prodplan","dataType":"string"},{"name":"Auslieferbezeichnung","dataType":"string"},{"name":"commodityCode","dataType":"string"},{"name":"Wellenlaenge","dataType":"string"},{"name":"Leistung_mW","dataType":"int64"},{"name":"GruppierungFuerAuswertung","dataType":"string"},{"name":"OTDGruppe","dataType":"string"},{"name":"TechFam","dataType":"string"},{"name":"zaehlenFuerStatistiken","dataType":"boolean"},{"name":"Faktor_Produktivitaet","dataType":"double"},{"name":"FuerProduktivitaet","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T06:30:09.0283342+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/7d16328f-64c0-481d-923f-68fbdd2bb2bd/DIM_ITEM_REFERENCETABLE_INTERN.csv?snapshot=2022-06-13T06%3A30%3A09.0129567Z"}]},{"$type":"LocalEntity","name":"ReschedulingData_SVC","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"ReschedulingData_SVC.csv"},"attributes":[{"name":"tab_Rep_ID","dataType":"int64"},{"name":"Datum","dataType":"date"},{"name":"scheduledDate_old","dataType":"date"},{"name":"scheduledDate_new","dataType":"date"},{"name":"reschedule","dataType":"string"},{"name":"Update_Oracle","dataType":"boolean"},{"name":"Grund","dataType":"string"},{"name":"Problem","dataType":"string"},{"name":"geaendertes_Feld","dataType":"string"},{"name":"TestendePlusOA_Eintrag","dataType":"date"},{"name":"geaendertes_Feld_Eintrag","dataType":"date"},{"name":"SRTyp","dataType":"string"},{"name":"ITEM","dataType":"string"},{"name":"promisedDate","dataType":"date"},{"name":"Product Family","dataType":"string"},{"name":"Bezeichnung","dataType":"string"},{"name":"Bemerkung","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T06:30:21.1375648+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/7d16328f-64c0-481d-923f-68fbdd2bb2bd/ReschedulingData_SVC.csv?snapshot=2022-06-13T06%3A30%3A20.6232776Z"}]},{"$type":"LocalEntity","name":"ReschedulingData_Orders","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"ReschedulingData_Orders.csv"},"attributes":[{"name":"ID","dataType":"int64"},{"name":"Datum","dataType":"date"},{"name":"SO","dataType":"double"},{"name":"Line","dataType":"string"},{"name":"Customer","dataType":"string"},{"name":"Qty","dataType":"double"},{"name":"PartNumber","dataType":"string"},{"name":"RequestDate","dataType":"date"},{"name":"PromisedDate","dataType":"date"},{"name":"scheduledDate_old","dataType":"date"},{"name":"scheduledDate_new","dataType":"date"},{"name":"Grund","dataType":"string"},{"name":"Problem","dataType":"string"},{"name":"Bemerkung","dataType":"string"},{"name":"Description","dataType":"string"},{"name":"Productfamily","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T06:30:14.5244173+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/7d16328f-64c0-481d-923f-68fbdd2bb2bd/ReschedulingData_Orders.csv?snapshot=2022-06-13T06%3A30%3A13.8241882Z"}]}]}