{"name":"COHREP_SITE_OM_TRX1","description":"","version":"1.0","culture":"en-US","modifiedTime":"2020-09-25T04:58:33.5898999+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":true,"queriesMetadata":{"Sales_Customer_Org":{"queryId":"cc533ec5-8199-40d3-95d1-09452e8d4874","queryName":"Sales_Customer_Org","queryGroupId":"root","loadEnabled":true},"Sales_Hold":{"queryId":"b3cadad1-5c2c-43ce-8c03-241935ae1543","queryName":"Sales_Hold","queryGroupId":"root","loadEnabled":true},"Sales":{"queryId":"d4aefb36-e13c-4d52-bc45-e00e74f29ef4","queryName":"Sales","queryGroupId":"root","loadEnabled":true},"ORG":{"queryId":"5cc05505-f32f-476a-9cfb-9d26ef5af016","queryName":"ORG"},"CUSTORG":{"queryId":"df435f66-b68f-4c5d-992b-8e29fd35f8ae","queryName":"CUSTORG"},"Sales_Line_Attachment":{"queryId":"c7e70622-7292-43c1-b502-0ebabcbaf0af","queryName":"Sales_Line_Attachment","queryGroupId":"root","loadEnabled":true},"Sales_Shipment":{"queryId":"229fcf0e-38e3-46c9-993b-57e084ba853e","queryName":"Sales_Shipment","queryGroupId":"root","loadEnabled":true},"Sales_Shipment_Customer_Org":{"queryId":"b81f4f63-d65a-4447-8c8e-45a5ea28a8d4","queryName":"Sales_Shipment_Customer_Org","queryGroupId":"root","loadEnabled":true},"Sales_Backlog":{"queryId":"d82037f6-b3b7-4d71-82fb-c4fc99de216b","queryName":"Sales_Backlog","queryGroupId":"root","loadEnabled":true}},"document":"section Section1;\r\nshared Sales_Customer_Org = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, \n  Query=\"\n  SELECT \n  SYSDATE EXTRACT_DATE, \n  MP.ORGANIZATION_CODE, \n  (\n    SELECT \n      NAME \n    FROM \n      APPS.HR_OPERATING_UNITS HOU \n    WHERE \n      HOU.ORGANIZATION_ID = OEH.ORG_ID\n  ) BOOKING_OU, \n  OEH.ORDER_NUMBER, \n  OEH.HEADER_ID, \n  HP.PARTY_NAME END_CUSTOMER_NAME, \n  OEL.LINE_NUMBER, \n  OEL.SHIPMENT_NUMBER, \n  OEL.OPEN_FLAG, \n  OEL.CANCELLED_FLAG, \n  OEL.SHIP_SET_ID, \n  OTT1.NAME ORDER_TYPE, \n  OEH.ORDER_TYPE_ID, \n  OTT2.NAME LINE_TYPE, \n  OEL.LINE_TYPE_ID, \n  OTTA2.ATTRIBUTE4 REVENUE_FLAG, \n  MSI.INVENTORY_ITEM_ID, \n  MSI.SEGMENT1 ITEM_NUMBER, \n  OEH.TRANSACTIONAL_CURR_CODE, \n  OEL.UNIT_SELLING_PRICE, \n  CASE WHEN OEL.LINE_CATEGORY_CODE = 'RETURN' \n  THEN OEL.ORDERED_QUANTITY * -1 ELSE OEL.ORDERED_QUANTITY \n  END ORDERED_QUANTITY, \n  OEL.BOOKED_FLAG, \n  CASE WHEN OEL.LINE_CATEGORY_CODE = 'RETURN' \n  THEN NVL(OEL.SHIPPED_QUANTITY, 0)* -1 ELSE NVL(OEL.SHIPPED_QUANTITY, 0) \n  END SHIPPED_QUANTITY, \n  DECODE(\n    HCA2.CUSTOMER_TYPE, 'R', 'External', \n    'Internal'\n  ) CUSTOMER_TYPE, \n  HP2.PARTY_NAME CUSTOMER, \n  OEL.FLOW_STATUS_CODE, \n  OEL.SHIPMENT_PRIORITY_CODE, \n  OEL.SHIPPABLE_FLAG, \n  OEL.SHIPPING_METHOD_CODE, \n  OEL.SUBINVENTORY, \n  OEH.ATTRIBUTE10 MARKET, \n  OEH.ATTRIBUTE1 SO_CATEGORY_CODE, \n  OEH.ATTRIBUTE4 REGIONAL_LOCATION, \n  OTTA2.ATTRIBUTE10 REPORTING_ENTITY, \n  OTTA2.ATTRIBUTE6 SALES_OR_SERVICE, \n  OEL.LINE_CATEGORY_CODE, \n  OEL.FOB_POINT_CODE, \n  OEL.ATTRIBUTE6 CI_VALUE, \n  OEL.FREIGHT_TERMS_CODE, \n  XXCRAA.COUNTRY, \n  XXCRAA.CITY, \n  OEL.ACTUAL_FULFILLMENT_DATE, \n  OEL.ACTUAL_SHIPMENT_DATE, \n  OEL.SCHEDULE_SHIP_DATE, \n  OEL.REQUEST_DATE, \n  OEL.PROMISE_DATE, \n  OEH.ORIG_SYS_DOCUMENT_REF, \n  OOS.NAME SOURCE_NAME, \n  MSI.PLANNER_CODE, \n  FU1.USER_NAME CREATED_BY, \n  FU2.USER_NAME LAST_UPDATED_BY, \n  OEL.CREATION_DATE, \n  OEL.LAST_UPDATE_DATE, \n  SREP.NAME SALES_REP, \n  OEL.LINE_ID, \n  OEH.BOOKED_DATE, \n  OEL.END_CUSTOMER_ID, \n  ROUND(\n    (\n      (\n        SELECT \n          ACTUAL_COST \n        FROM \n          APPS.MTL_MATERIAL_TRANSACTIONS MMT \n        WHERE \n          MMT.TRX_SOURCE_LINE_ID = OEL.LINE_ID \n          AND MMT.ORGANIZATION_ID = MP.ORGANIZATION_ID \n          AND MMT.INVENTORY_ITEM_ID = OEL.INVENTORY_ITEM_ID \n          AND MMT.TRANSACTION_TYPE_ID IN (62, 33) \n          AND ROWNUM = 1\n      )\n    ) * NVL(\n      (\n        SELECT \n          CONVERSION_RATE \n        FROM \n          APPS.GL_DAILY_RATES GDR, \n          APPS.ORG_ORGANIZATION_DEFINITIONS OOD, \n          APPS.GL_SETS_OF_BOOKS SOB \n        WHERE \n          GDR.TO_CURRENCY = 'USD' \n          AND GDR.FROM_CURRENCY = SOB.CURRENCY_CODE \n          AND SOB.SET_OF_BOOKS_ID = OOD.SET_OF_BOOKS_ID \n          AND OOD.ORGANIZATION_CODE = MP.ORGANIZATION_CODE \n          AND GDR.CONVERSION_DATE = TRUNC(OEL.ACTUAL_SHIPMENT_DATE) \n          AND CONVERSION_TYPE = 'Corporate'\n      ), \n      1\n    ), \n    4\n  ) UNIT_COST_USD, \n  (\n    SELECT \n      SUM(\n        NVL(\n          (\n            SELECT \n              CONVERSION_RATE \n            FROM \n              APPS.GL_DAILY_RATES GDR \n            WHERE \n              GDR.TO_CURRENCY = 'USD' \n              AND GDR.FROM_CURRENCY = RCTA.INVOICE_CURRENCY_CODE \n              AND GDR.CONVERSION_DATE = TRUNC(RCTA.TRX_DATE) \n              AND GDR.CONVERSION_TYPE = 'Corporate'\n          ), \n          1\n        )* NVL(RCTL.REVENUE_AMOUNT, 0)\n      ) \n    FROM \n      APPS.RA_CUSTOMER_TRX_LINES_ALL RCTL, \n      APPS.RA_CUSTOMER_TRX_ALL RCTA \n    WHERE \n      1 = 1 \n      AND RCTL.INTERFACE_LINE_ATTRIBUTE1 = TO_CHAR (OEH.ORDER_NUMBER) \n      AND RCTL.INTERFACE_LINE_ATTRIBUTE6 = TO_CHAR (OEL.LINE_ID) \n      AND RCTA.INTERFACE_HEADER_CONTEXT = 'ORDER ENTRY' \n      AND RCTL.INTERFACE_LINE_CONTEXT = 'ORDER ENTRY' \n      AND RCTL.CUSTOMER_TRX_ID = RCTA.CUSTOMER_TRX_ID\n  ) REVENUE_AMOUNT_USD, \n  NVL(\n    (\n      SELECT \n        CONVERSION_RATE \n      FROM \n        APPS.GL_DAILY_RATES GDR \n      WHERE \n        GDR.TO_CURRENCY = 'USD' \n        AND GDR.FROM_CURRENCY = OEH.TRANSACTIONAL_CURR_CODE \n        AND GDR.CONVERSION_TYPE = 'Corporate' \n        AND GDR.CONVERSION_DATE= TRUNC(\n          NVL(\n            OEH.BOOKED_DATE, OEH.CREATION_DATE\n          )\n        )\n    ), \n    1\n  ) BOOK_USD_RATE, \n  CASE WHEN NVL(\n    (\n      SELECT \n        count(source_line_id) \n      FROM \n        apps.wsh_Delivery_details wdd \n      WHERE \n        wdd.source_line_id = oel.line_id\n    ), \n    0\n  ) + NVL(\n    (\n      SELECT \n        COUNT(OE_ORDER_LINE_ID) \n      FROM \n        APPS.RCV_SHIPMENT_LINES RSL \n      WHERE \n        oel.line_id = rsl.oe_order_line_id \n        AND RSL.SOURCE_DOCUMENT_CODE = 'RMA' \n        AND OEL.HEADER_ID = RSL.OE_ORDER_HEADER_ID \n        AND OEL.SHIP_FROM_ORG_ID = RSL.TO_ORGANIZATION_ID\n    ), \n    0\n  ) + decode(\n    OEL.FLOW_STATUS_CODE, 'AWAITING_RETURN', \n    1, 0\n  )> 0 THEN 'Y' ELSE 'N' END DELIVERY_DETAIL_FLAG \n      FROM\n         ONT.OE_ORDER_SOURCES OOS,\n         AR.HZ_PARTIES HP,\n         AR.HZ_CUST_ACCOUNTS HCA,\n         APPS.XXCOH_RA_ADDRESSES_ALL XXCRAA,\n         AR.HZ_CUST_SITE_USES_ALL CSUA,\n         AR.HZ_PARTIES HP2,\n         AR.HZ_CUST_ACCOUNTS HCA2,\n         JTF.JTF_RS_SALESREPS SREP,\n         ONT.OE_TRANSACTION_TYPES_ALL OTTA1,\n         ONT.OE_TRANSACTION_TYPES_ALL OTTA2,\n         ONT.OE_TRANSACTION_TYPES_TL OTT1,\n         ONT.OE_TRANSACTION_TYPES_TL OTT2,\n         INV.MTL_PARAMETERS MP,\n         ONT.OE_ORDER_HEADERS_ALL OEH,\n         APPS.OE_ORDER_LINES_ALL OEL,\n         INV.MTL_SYSTEM_ITEMS_B MSI,\n         INV.MTL_PARAMETERS MP2,\n         APPS.ORG_ORGANIZATION_DEFINITIONS OOD,\n         APPLSYS.FND_USER FU1,\n         APPLSYS.FND_USER FU2 \n      WHERE\n         1 = 1 \n         AND HCA.PARTY_ID = HP.PARTY_ID ( + ) \n         AND CSUA.CUST_ACCT_SITE_ID = XXCRAA.ADDRESS_ID \n         AND OEL.END_CUSTOMER_ID = HCA.CUST_ACCOUNT_ID ( + ) \n         AND OEL.SHIP_TO_ORG_ID = CSUA.SITE_USE_ID \n         AND HCA2.PARTY_ID = HP2.PARTY_ID \n         AND OEH.SOLD_TO_ORG_ID = HCA2.CUST_ACCOUNT_ID \n         AND OEL.SALESREP_ID = SREP.SALESREP_ID ( + ) \n         AND OEL.ORG_ID = SREP.ORG_ID ( + ) \n         AND OEL.HEADER_ID = OEH.HEADER_ID \n         AND OEH.ORG_ID = OEL.ORG_ID \n         AND MP.ORGANIZATION_ID = OEL.SHIP_FROM_ORG_ID \n         AND OEH.ORDER_SOURCE_ID = OOS.ORDER_SOURCE_ID \n         AND OEL.INVENTORY_ITEM_ID = MSI.INVENTORY_ITEM_ID \n         AND MSI.ORGANIZATION_ID = MP2.ORGANIZATION_ID \n         AND OTTA1.TRANSACTION_TYPE_ID = OTT1.TRANSACTION_TYPE_ID \n         AND OTT2.TRANSACTION_TYPE_ID = OTTA2.TRANSACTION_TYPE_ID \n         AND OEH.ORDER_TYPE_ID = OTTA1.TRANSACTION_TYPE_ID \n         AND OEL.LINE_TYPE_ID = OTTA2.TRANSACTION_TYPE_ID \n         AND OOD.ORGANIZATION_ID = MP2.ORGANIZATION_ID \n         AND OEL.CREATED_BY = FU1.USER_ID \n         AND OEL.LAST_UPDATED_BY = FU2.USER_ID \n         AND MP.ORGANIZATION_CODE = '\"&CUSTORG&\"' \t\t\t--ship from org\n         AND MP2.ORGANIZATION_CODE = '\"&ORG&\"' \t\t\t--item org\n         AND OTT1.LANGUAGE = 'US' \n         AND OTT2.LANGUAGE = 'US'\n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"EXTRACT_DATE\", \"Extract Date\"}, {\"ORGANIZATION_CODE\", \"Ship From Org\"}, {\"ORDER_NUMBER\", \"Order Number\"}, {\"END_CUSTOMER_NAME\", \"End Customer Name\"}, {\"LINE_NUMBER\", \"Line Number\"}, {\"SHIPMENT_NUMBER\", \"Shipment Number\"}, {\"OPEN_FLAG\", \"Open Flag\"}, {\"CANCELLED_FLAG\", \"Cancelled Flag\"}, {\"SHIP_SET_ID\", \"Ship Set ID\"}, {\"ORDER_TYPE\", \"Order Type\"}, {\"LINE_TYPE\", \"Line Type\"}, {\"BOOKING_OU\", \"Operating Unit\"}, {\"REVENUE_FLAG\", \"Revenue Flag\"}, {\"ITEM_NUMBER\", \"Item Number\"}, {\"TRANSACTIONAL_CURR_CODE\", \"Currency Code\"}, {\"UNIT_SELLING_PRICE\", \"Unit Price\"}, {\"ORDERED_QUANTITY\", \"Ordered Quantity\"}, {\"CUSTOMER_TYPE\", \"Customer Type\"}, {\"CUSTOMER\", \"Customer\"}, {\"FLOW_STATUS_CODE\", \"Status\"}, {\"SHIPMENT_PRIORITY_CODE\", \"Shipment Priority\"}, {\"SHIPPABLE_FLAG\", \"Shippable Flag\"}, {\"SHIPPING_METHOD_CODE\", \"Shipping Method\"}, {\"SUBINVENTORY\", \"Ship From Subinventory\"}, {\"MARKET\", \"Market\"}, {\"SO_CATEGORY_CODE\", \"Category Code\"}, {\"REGIONAL_LOCATION\", \"Regional Location\"}, {\"REPORTING_ENTITY\", \"Reporting Entity\"}, {\"SALES_OR_SERVICE\", \"Sales or Service\"}, {\"LINE_CATEGORY_CODE\", \"Line Category\"}, {\"FOB_POINT_CODE\", \"FOB Point\"}, {\"CI_VALUE\", \"Custom Invoice Value\"}, {\"FREIGHT_TERMS_CODE\", \"Freight Terms\"}, {\"COUNTRY\", \"Ship To Country\"}, {\"CITY\", \"Ship To City\"}, {\"ACTUAL_FULFILLMENT_DATE\", \"Actual Fulfillment Date\"}, {\"ACTUAL_SHIPMENT_DATE\", \"Actual Shipment Date\"}, {\"PROMISE_DATE\", \"Promised Date\"}, {\"REQUEST_DATE\", \"Request Date\"}, {\"SCHEDULE_SHIP_DATE\", \"Schedule Ship Date\"}, {\"ORIG_SYS_DOCUMENT_REF\", \"Original Document Reference\"}, {\"PLANNER_CODE\", \"Planner\"}, {\"CREATED_BY\", \"Line Created By\"}, {\"LAST_UPDATED_BY\", \"Line Last Updated By\"}, {\"CREATION_DATE\", \"Line Creation Date\"}, {\"LAST_UPDATE_DATE\", \"Line Last Update Date\"}, {\"SALES_REP\", \"Sales Rep\"}, {\"BOOKED_DATE\", \"Book Date\"}, {\"SOURCE_NAME\", \"Source Name\"}, {\"UNIT_COST_USD\", \"Unit Cost USD\"}, {\"BOOKED_FLAG\", \"Booked Flag\"}, {\"SHIPPED_QUANTITY\", \"Shipped Quantity\"}, {\"REVENUE_AMOUNT_USD\", \"Revenue Amount USD\"}, {\"BOOK_USD_RATE\", \"Book USD Rate\"}, {\"DELIVERY_DETAIL_FLAG\", \"Delivery Detail Flag\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Sales_Hold = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, Query=\"\n SELECT\n   sysdate EXTRACT_DATE,\n   ooh.hold_source_id hold_source_id,\n   decode(ooh.line_id, NULL , 'ORDER', 'LINE') hold_level,\n   ooh.header_id,\n   ooh.line_id,\n   ohs.hold_id,\n   ohd.name hold_reason,\n   ooh.released_flag hold_release_flag,\n   ooh.creation_date hold_creation_date,\n   (select user_name \n   from applsys.fnd_user \n   where user_id = ooh.created_by) hold_created_by\nFROM\n   apps.oe_order_holds_all ooh,\n   apps.oe_hold_releases hrl,\n   apps.fnd_user usr,\n   apps.fnd_user rusr,\n   apps.oe_hold_definitions ohd,\n   apps.oe_hold_sources_all ohs \nWHERE\n   header_id IN \n   (\n      SELECT\n         header_id \n      FROM\n         apps.oe_order_lines_all oel2,\n         inv.mtl_parameters mp2 \n      WHERE\n         mp2.organization_id = oel2.ship_from_org_id \n         AND mp2.organization_code = '\"&ORG&\"'\n   )\n   AND usr.user_id = ooh.created_by \n   AND rusr.user_id ( + ) = hrl.created_by \n   AND hrl.hold_release_id ( + ) = ooh.hold_release_id \n   AND rusr.user_id ( + ) = hrl.created_by \n   AND hrl.hold_release_id ( + ) = ooh.hold_release_id \n   AND ohd.hold_id ( + ) = ohs.hold_id \n   AND ohs.hold_source_id = ooh.hold_source_id \n   AND ooh.released_flag = 'N'\n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"HOLD_REASON\", \"Hold Reason\"}, {\"HOLD_RELEASE_FLAG\", \"Hold Release Flag\"}, {\"HOLD_LEVEL\", \"Hold Level\"}, {\"HOLD_CREATION_DATE\", \"Creation Date\"}, {\"HOLD_CREATED_BY\", \"Created By\"}, {\"EXTRACT_DATE\", \"Extract Date\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Sales = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, \n  Query=\"\n  SELECT \n  SYSDATE EXTRACT_DATE, \n  MP.ORGANIZATION_CODE, \n  (\n    SELECT \n      NAME \n    FROM \n      APPS.HR_OPERATING_UNITS HOU \n    WHERE \n      HOU.ORGANIZATION_ID = OEH.ORG_ID\n  ) BOOKING_OU, \n  OEH.ORDER_NUMBER, \n  OEH.HEADER_ID, \n  HP.PARTY_NAME END_CUSTOMER_NAME, \n  OEL.LINE_NUMBER, \n  OEL.SHIPMENT_NUMBER, \n  OEL.OPEN_FLAG, \n  OEL.CANCELLED_FLAG, \n  OEL.SHIP_SET_ID, \n  OTT1.NAME ORDER_TYPE, \n  OEH.ORDER_TYPE_ID, \n  OTT2.NAME LINE_TYPE, \n  OEL.LINE_TYPE_ID, \n  OTTA2.ATTRIBUTE4 REVENUE_FLAG, \n  MSI.INVENTORY_ITEM_ID, \n  MSI.SEGMENT1 ITEM_NUMBER, \n  OEH.TRANSACTIONAL_CURR_CODE, \n  OEL.UNIT_SELLING_PRICE, \n  CASE WHEN OEL.LINE_CATEGORY_CODE = 'RETURN' THEN OEL.ORDERED_QUANTITY * -1 ELSE OEL.ORDERED_QUANTITY END ORDERED_QUANTITY, \n  OEL.BOOKED_FLAG, \n  CASE WHEN OEL.LINE_CATEGORY_CODE = 'RETURN' THEN NVL(OEL.SHIPPED_QUANTITY, 0)* -1 ELSE NVL(OEL.SHIPPED_QUANTITY, 0) END SHIPPED_QUANTITY, \n  DECODE(\n    HCA2.CUSTOMER_TYPE, 'R', 'External', \n    'Internal'\n  ) CUSTOMER_TYPE, \n  HP2.PARTY_NAME CUSTOMER, \n  OEL.FLOW_STATUS_CODE, \n  OEL.SHIPMENT_PRIORITY_CODE, \n  OEL.SHIPPABLE_FLAG, \n  OEL.SHIPPING_METHOD_CODE, \n  OEL.SUBINVENTORY, \n  OEH.ATTRIBUTE10 MARKET, \n  OEH.ATTRIBUTE1 SO_CATEGORY_CODE, \n  OEH.ATTRIBUTE4 REGIONAL_LOCATION, \n  OTTA2.ATTRIBUTE10 REPORTING_ENTITY, \n  OTTA2.ATTRIBUTE6 SALES_OR_SERVICE, \n  OEL.LINE_CATEGORY_CODE, \n  OEL.FOB_POINT_CODE, \n  OEL.ATTRIBUTE6 CI_VALUE, \n  OEL.FREIGHT_TERMS_CODE, \n  XXCRAA.COUNTRY, \n  XXCRAA.CITY, \n  OEL.ACTUAL_FULFILLMENT_DATE, \n  OEL.ACTUAL_SHIPMENT_DATE, \n  OEL.SCHEDULE_SHIP_DATE, \n  OEL.REQUEST_DATE, \n  OEL.PROMISE_DATE, \n  OEH.ORIG_SYS_DOCUMENT_REF, \n  OOS.NAME SOURCE_NAME, \n  MSI.PLANNER_CODE, \n  FU1.USER_NAME CREATED_BY, \n  FU2.USER_NAME LAST_UPDATED_BY, \n  OEL.CREATION_DATE, \n  OEL.LAST_UPDATE_DATE, \n  SREP.NAME SALES_REP, \n  OEL.LINE_ID, \n  OEH.BOOKED_DATE, \n  OEL.END_CUSTOMER_ID, \n  ROUND(\n    (\n      (\n        SELECT \n          ACTUAL_COST \n        FROM \n          APPS.MTL_MATERIAL_TRANSACTIONS MMT \n        WHERE \n          MMT.TRX_SOURCE_LINE_ID = OEL.LINE_ID \n          AND MMT.ORGANIZATION_ID = MP.ORGANIZATION_ID \n          AND MMT.INVENTORY_ITEM_ID = OEL.INVENTORY_ITEM_ID \n          AND MMT.TRANSACTION_TYPE_ID IN (62, 33) \n          AND ROWNUM = 1\n      )\n    ) * NVL(\n      (\n        SELECT \n          CONVERSION_RATE \n        FROM \n          APPS.GL_DAILY_RATES GDR, \n          APPS.ORG_ORGANIZATION_DEFINITIONS OOD, \n          APPS.GL_SETS_OF_BOOKS SOB \n        WHERE \n          GDR.TO_CURRENCY = 'USD' \n          AND GDR.FROM_CURRENCY = SOB.CURRENCY_CODE \n          AND SOB.SET_OF_BOOKS_ID = OOD.SET_OF_BOOKS_ID \n          AND OOD.ORGANIZATION_CODE = MP.ORGANIZATION_CODE \n          AND GDR.CONVERSION_DATE = TRUNC(OEL.ACTUAL_SHIPMENT_DATE) \n          AND CONVERSION_TYPE = 'Corporate'\n      ), \n      1\n    ), \n    4\n  ) UNIT_COST_USD, \n  (\n    SELECT \n      SUM(\n        NVL(\n          (\n            SELECT \n              CONVERSION_RATE \n            FROM \n              APPS.GL_DAILY_RATES GDR \n            WHERE \n              GDR.TO_CURRENCY = 'USD' \n              AND GDR.FROM_CURRENCY = RCTA.INVOICE_CURRENCY_CODE \n              AND GDR.CONVERSION_DATE = TRUNC(RCTA.TRX_DATE) \n              AND GDR.CONVERSION_TYPE = 'Corporate'\n          ), \n          1\n        )* NVL(RCTL.REVENUE_AMOUNT, 0)\n      ) \n    FROM \n      APPS.RA_CUSTOMER_TRX_LINES_ALL RCTL, \n      APPS.RA_CUSTOMER_TRX_ALL RCTA \n    WHERE \n      1 = 1 \n      AND RCTL.INTERFACE_LINE_ATTRIBUTE1 = TO_CHAR (OEH.ORDER_NUMBER) \n      AND RCTL.INTERFACE_LINE_ATTRIBUTE6 = TO_CHAR (OEL.LINE_ID) \n      AND RCTA.INTERFACE_HEADER_CONTEXT = 'ORDER ENTRY' \n      AND RCTL.INTERFACE_LINE_CONTEXT = 'ORDER ENTRY' \n      AND RCTL.CUSTOMER_TRX_ID = RCTA.CUSTOMER_TRX_ID\n  ) REVENUE_AMOUNT_USD, \n  NVL(\n    (\n      SELECT \n        CONVERSION_RATE \n      FROM \n        APPS.GL_DAILY_RATES GDR \n      WHERE \n        GDR.TO_CURRENCY = 'USD' \n        AND GDR.FROM_CURRENCY = OEH.TRANSACTIONAL_CURR_CODE \n        AND GDR.CONVERSION_TYPE = 'Corporate' \n        AND GDR.CONVERSION_DATE= TRUNC(\n          NVL(\n            OEH.BOOKED_DATE, OEH.CREATION_DATE\n          )\n        )\n    ), \n    1\n  ) BOOK_USD_RATE, \n  CASE WHEN NVL(\n    (\n      SELECT \n        count(source_line_id) \n      FROM \n        apps.wsh_Delivery_details wdd \n      WHERE \n        wdd.source_line_id = oel.line_id\n    ), \n    0\n  ) + NVL(\n    (\n      SELECT \n        COUNT(OE_ORDER_LINE_ID) \n      FROM \n        APPS.RCV_SHIPMENT_LINES RSL \n      WHERE \n        oel.line_id = rsl.oe_order_line_id \n        AND RSL.SOURCE_DOCUMENT_CODE = 'RMA' \n        AND OEL.HEADER_ID = RSL.OE_ORDER_HEADER_ID \n        AND OEL.SHIP_FROM_ORG_ID = RSL.TO_ORGANIZATION_ID\n    ), \n    0\n  ) + decode(\n    OEL.FLOW_STATUS_CODE, 'AWAITING_RETURN', \n    1, 0\n  )> 0 THEN 'Y' ELSE 'N' END DELIVERY_DETAIL_FLAG \n  FROM \n  ONT.OE_ORDER_SOURCES OOS, \n  AR.HZ_PARTIES HP, \n  AR.HZ_CUST_ACCOUNTS HCA, \n  APPS.XXCOH_RA_ADDRESSES_ALL XXCRAA, \n  AR.HZ_CUST_SITE_USES_ALL CSUA, \n  AR.HZ_PARTIES HP2, \n  AR.HZ_CUST_ACCOUNTS HCA2, \n  JTF.JTF_RS_SALESREPS SREP, \n  ONT.OE_TRANSACTION_TYPES_ALL OTTA1, \n  ONT.OE_TRANSACTION_TYPES_ALL OTTA2, \n  ONT.OE_TRANSACTION_TYPES_TL OTT1, \n  ONT.OE_TRANSACTION_TYPES_TL OTT2, \n  INV.MTL_PARAMETERS MP, \n  ONT.OE_ORDER_HEADERS_ALL OEH, \n  APPS.OE_ORDER_LINES_ALL OEL, \n  INV.MTL_SYSTEM_ITEMS_B MSI, \n  INV.MTL_PARAMETERS MP2, \n  APPS.ORG_ORGANIZATION_DEFINITIONS OOD, \n  APPLSYS.FND_USER FU1, \n  APPLSYS.FND_USER FU2 \nWHERE \n  1 = 1 \n  AND HCA.PARTY_ID = HP.PARTY_ID (+) \n  AND CSUA.CUST_ACCT_SITE_ID = XXCRAA.ADDRESS_ID \n  AND OEL.END_CUSTOMER_ID = HCA.CUST_ACCOUNT_ID (+) \n  AND OEL.SHIP_TO_ORG_ID = CSUA.SITE_USE_ID \n  AND HCA2.PARTY_ID = HP2.PARTY_ID \n  AND OEH.SOLD_TO_ORG_ID = HCA2.CUST_ACCOUNT_ID \n  AND OEL.SALESREP_ID = SREP.SALESREP_ID (+) \n  AND OEL.ORG_ID = SREP.ORG_ID (+) \n  AND OEL.HEADER_ID = OEH.HEADER_ID \n  AND OEH.ORG_ID = OEL.ORG_ID \n  AND MP.ORGANIZATION_ID = OEL.SHIP_FROM_ORG_ID \n  AND OEH.ORDER_SOURCE_ID = OOS.ORDER_SOURCE_ID \n  AND OEL.INVENTORY_ITEM_ID = MSI.INVENTORY_ITEM_ID \n  AND MSI.ORGANIZATION_ID = MP2.ORGANIZATION_ID \n  AND OTTA1.TRANSACTION_TYPE_ID = OTT1.TRANSACTION_TYPE_ID \n  AND OTT2.TRANSACTION_TYPE_ID = OTTA2.TRANSACTION_TYPE_ID \n  AND OEH.ORDER_TYPE_ID = OTTA1.TRANSACTION_TYPE_ID \n  AND OEL.LINE_TYPE_ID = OTTA2.TRANSACTION_TYPE_ID \n  AND OOD.ORGANIZATION_ID = MP2.ORGANIZATION_ID \n  AND OEL.CREATED_BY = FU1.USER_ID \n  AND OEL.LAST_UPDATED_BY = FU2.USER_ID \n  AND MP.ORGANIZATION_CODE = '\"&ORG&\"' --ship from org\n  AND MP2.ORGANIZATION_CODE = '\"&ORG&\"' --item org\n  AND OTT1.LANGUAGE = 'US' \n  AND OTT2.LANGUAGE = 'US'\n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"EXTRACT_DATE\", \"Extract Date\"}, {\"ORGANIZATION_CODE\", \"Ship From Org\"}, {\"ORDER_NUMBER\", \"Order Number\"}, {\"END_CUSTOMER_NAME\", \"End Customer Name\"}, {\"LINE_NUMBER\", \"Line Number\"}, {\"SHIPMENT_NUMBER\", \"Shipment Number\"}, {\"OPEN_FLAG\", \"Open Flag\"}, {\"CANCELLED_FLAG\", \"Cancelled Flag\"}, {\"SHIP_SET_ID\", \"Ship Set ID\"}, {\"ORDER_TYPE\", \"Order Type\"}, {\"LINE_TYPE\", \"Line Type\"}, {\"BOOKING_OU\", \"Operating Unit\"}, {\"REVENUE_FLAG\", \"Revenue Flag\"}, {\"ITEM_NUMBER\", \"Item Number\"}, {\"TRANSACTIONAL_CURR_CODE\", \"Currency Code\"}, {\"UNIT_SELLING_PRICE\", \"Unit Price\"}, {\"ORDERED_QUANTITY\", \"Ordered Quantity\"}, {\"CUSTOMER_TYPE\", \"Customer Type\"}, {\"CUSTOMER\", \"Customer\"}, {\"FLOW_STATUS_CODE\", \"Status\"}, {\"SHIPMENT_PRIORITY_CODE\", \"Shipment Priority\"}, {\"SHIPPABLE_FLAG\", \"Shippable Flag\"}, {\"SHIPPING_METHOD_CODE\", \"Shipping Method\"}, {\"SUBINVENTORY\", \"Ship From Subinventory\"}, {\"MARKET\", \"Market\"}, {\"SO_CATEGORY_CODE\", \"Category Code\"}, {\"REGIONAL_LOCATION\", \"Regional Location\"}, {\"REPORTING_ENTITY\", \"Reporting Entity\"}, {\"SALES_OR_SERVICE\", \"Sales or Service\"}, {\"LINE_CATEGORY_CODE\", \"Line Category\"}, {\"FOB_POINT_CODE\", \"FOB Point\"}, {\"CI_VALUE\", \"Custom Invoice Value\"}, {\"FREIGHT_TERMS_CODE\", \"Freight Terms\"}, {\"COUNTRY\", \"Ship To Country\"}, {\"CITY\", \"Ship To City\"}, {\"ACTUAL_FULFILLMENT_DATE\", \"Actual Fulfillment Date\"}, {\"ACTUAL_SHIPMENT_DATE\", \"Actual Shipment Date\"}, {\"PROMISE_DATE\", \"Promised Date\"}, {\"REQUEST_DATE\", \"Request Date\"}, {\"SCHEDULE_SHIP_DATE\", \"Schedule Ship Date\"}, {\"ORIG_SYS_DOCUMENT_REF\", \"Original Document Reference\"}, {\"PLANNER_CODE\", \"Planner\"}, {\"CREATED_BY\", \"Line Created By\"}, {\"LAST_UPDATED_BY\", \"Line Last Updated By\"}, {\"CREATION_DATE\", \"Line Creation Date\"}, {\"LAST_UPDATE_DATE\", \"Line Last Update Date\"}, {\"SALES_REP\", \"Sales Rep\"}, {\"BOOKED_DATE\", \"Book Date\"}, {\"SOURCE_NAME\", \"Source Name\"}, {\"UNIT_COST_USD\", \"Unit Cost USD\"}, {\"BOOKED_FLAG\", \"Booked Flag\"}, {\"SHIPPED_QUANTITY\", \"Shipped Quantity\"}, {\"REVENUE_AMOUNT_USD\", \"Revenue Amount USD\"}, {\"BOOK_USD_RATE\", \"Book USD Rate\"}, {\"DELIVERY_DETAIL_FLAG\", \"Delivery Detail Flag\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared ORG = let\r\n  ORG = \"LDP\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type text]\r\nin\r\n  ORG;\r\nshared CUSTORG = let\r\n  CUSTORG = \"COL\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type text]\r\nin\r\n  CUSTORG;\r\nshared Sales_Line_Attachment = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, \n  Query=\"SELECT\n   /*+index (AD XXCOH_FND_ATTACHED_DOC_01 ) */\n   Sysdate EXTRACT_DATE,\n   AD.SEQ_NUM,\n   DCT.USER_NAME DOCUMENT_CATEGORY,\n   DTL.DESCRIPTION,\n   DTL.TITLE,\n   DECODE(TXT.SHORT_TEXT, NULL, FL.FILE_CONTENT_TYPE, '') FILETYPE,\n   TXT.SHORT_TEXT DOC_TEXT,\n   OEH.ORDER_NUMBER,\n   OEL.LINE_NUMBER || DECODE(OEL.SHIPMENT_NUMBER, NULL, NULL, '.' || OEL.SHIPMENT_NUMBER) ORDER_LINE,\n   'Line' DOCUMENT_LEVEL,\n   OEL.LINE_ID,\n   OEH.HEADER_ID,\n   MP.ORGANIZATION_CODE,\n   AD.LAST_UPDATE_DATE,\n   USR.USER_NAME LAST_UPDATED_BY \nFROM\n   APPS.FND_USER USR,\n   APPS.FND_LOBS FL,\n   APPS.FND_DOCUMENTS_SHORT_TEXT TXT,\n   APPS.FND_DOCUMENT_CATEGORIES_TL DCT,\n   APPS.FND_DOCUMENTS_TL DTL,\n   APPS.FND_DOCUMENTS DT,\n   APPS.FND_ATTACHED_DOCUMENTS AD,\n   APPS.OE_ORDER_LINES_ALL OEL,\n   APPS.MTL_PARAMETERS MP,\n   APPS.OE_ORDER_HEADERS_ALL OEH \nWHERE\n   1 = 1 \n   AND USR.USER_ID = AD.LAST_UPDATED_BY \n   AND FL.FILE_ID ( + ) = DT.MEDIA_ID \n   AND TXT.MEDIA_ID ( + ) = DT.MEDIA_ID \n   AND DCT.CATEGORY_ID = DT.CATEGORY_ID \n   AND DCT.LANGUAGE = 'US' \n   AND DTL.DOCUMENT_ID = DT.DOCUMENT_ID \n   AND DTL.LANGUAGE = 'US' \n   AND DT.DOCUMENT_ID = AD.DOCUMENT_ID \n   AND DT.DOCUMENT_ID = AD.DOCUMENT_ID \n   AND AD.ENTITY_NAME = 'OE_ORDER_LINES' \n   AND AD.PK1_VALUE = OEL.LINE_ID \n   AND MP.ORGANIZATION_CODE in ('\"&ORG&\"','\"&CUSTORG&\"')\n   AND OEH.HEADER_ID = OEL.HEADER_ID \n   AND OEH.ORG_ID = OEL.ORG_ID \n   AND MP.ORGANIZATION_ID = OEL.SHIP_FROM_ORG_ID\n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"ORGANIZATION_CODE\", \"Ship From Org\"}, {\"EXTRACT_DATE\", \"Extract Date\"}, {\"SEQ_NUM\", \"Sequence\"}, {\"DOCUMENT_CATEGORY\", \"Document Category\"}, {\"DESCRIPTION\", \"Description\"}, {\"TITLE\", \"Title\"}, {\"FILETYPE\", \"File Type\"}, {\"DOC_TEXT\", \"Document Text\"}, {\"ORDER_NUMBER\", \"Order Number\"}, {\"ORDER_LINE\", \"Order Line\"}, {\"DOCUMENT_LEVEL\", \"Document Level\"}, {\"LAST_UPDATE_DATE\", \"Last Update Date\"}, {\"LAST_UPDATED_BY\", \"Last Updated By\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Sales_Shipment = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, \n  Query=\"select sysdate extract_date\n, WDD.SOURCE_LINE_ID\n,WDD.DELIVERY_DETAIL_ID\n,MP2.organization_code\n,OEL.ORDERED_ITEM ITEM_NUMBER\n, FLV.MEANING released_status\n , WND.NAME DELIVERY_NUMBER\n , WND.WAYBILL DELIVERY_WAYBILL\n , (SELECT MTRH.request_number FROM INV.MTL_TXN_REQUEST_HEADERS MTRH, INV.MTL_TXN_rEQUEST_LINES MTRL WHERE MTRL.LINE_ID = WDD.MOVE_ORDER_LINE_ID AND MTRH.HEADER_ID = MTRL.HEADER_ID) MOVE_ORDER_NUMBER\n  , (SELECT MTRL.LINE_NUMBER FROM INV.MTL_TXN_rEQUEST_LINES MTRL WHERE MTRL.LINE_ID = WDD.MOVE_ORDER_LINE_ID ) MOVE_ORDER_Line_NUMBER\n  ,wdd.requested_Quantity\n  ,wdd.requested_quantity_uom\n  ,wdd.cancelled_quantity\n  ,wdd.picked_quantity\n , case when WDD.SHIPPING_INSTRUCTIONS is null then NVL(oel.shipping_instructions,OEH.SHIPPING_INSTRUCTIONS) else NVL(oel.shipping_instructions,OEH.SHIPPING_INSTRUCTIONS)||'/'||wdd.shipping_instructions end SHIPPING_INSTRUCTIONSV\n , case when WDD.PACKING_INSTRUCTIONS is null then NVL(oel.packing_instructions,OEH.PACKING_INSTRUCTIONS ) else NVL(oel.packing_instructions,OEH.PACKING_INSTRUCTIONS) ||'/'|| wdd.packing_instructions end PACKING_INSTRUCTIONSV\n ,wnd.gross_weight\n ,wnd.net_weight\n ,wnd.weight_uom_code\n ,wnd.volume\n ,wnd.volume_uom_code\n ,wnd.attribute1 delivery_pack\n ,wnd.attribute2 delivery_pack_uom\n ,wnd.attribute3 delivery_pack_dimensions\n ,wnd.confirm_date\n ,wnd.ship_method_code\n ,wnd.delivery_type\n ,wnd.service_level\n ,wnd.mode_of_transport\n ,wnd.delivery_id\n FROM WSH.WSH_NEW_DELIVERIES WND\n , WSH.WSH_DELIVERY_ASSIGNMENTS WDA\n , WSH.WSH_DELIVERY_DETAILS WDD\n , APPS.OE_ORDER_LINES_ALL OEL\n ,APPS.OE_ORDER_HEADERS_aLL OEH\n , INV.MTL_PARAMETERS MP2\n ,apps.fnd_lookup_values_vl FLV\n WHERE 1=1\n AND OEH.HEADER_ID = OEL.HEADER_ID\n and WDD.DELIVERY_DETAIL_ID = WDA.DELIVERY_DETAIL_ID (+)\n AND WDA.DELIVERY_ID = WND.DELIVERY_ID (+)\n and mp2.organization_id = wdd.organization_id\n AND MP2.ORGANIZATION_CODE ='\"&ORG&\"'\n AND MP2.ORGANIZATION_ID = OEL.SHIP_FROM_ORG_ID\n AND OEL.LINE_ID = WDD.SOURCE_LINE_ID\n and wdd.organization_id = OEL.SHIP_FROM_ORG_ID\n and wdd.released_status = FLV.LOOKUP_CODE\n AND FLV.lookup_type = 'PICK_STATUS'\n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"EXTRACT_DATE\", \"Extract Date\"}, {\"ORGANIZATION_CODE\", \"Organization Code\"}, {\"ITEM_NUMBER\", \"Item Number\"}, {\"RELEASED_STATUS\", \"Released Status\"}, {\"DELIVERY_NUMBER\", \"Delivery Number\"}, {\"DELIVERY_WAYBILL\", \"Delivery Waybill\"}, {\"MOVE_ORDER_NUMBER\", \"Pick Move Order Number\"}, {\"MOVE_ORDER_LINE_NUMBER\", \"Pick Move Order Line Number\"}, {\"REQUESTED_QUANTITY\", \"Requested Quantity\"}, {\"REQUESTED_QUANTITY_UOM\", \"Requested Quantity UOM\"}, {\"CANCELLED_QUANTITY\", \"Cancelled Quantity\"}, {\"PICKED_QUANTITY\", \"Picked Quantity\"}, {\"SHIPPING_INSTRUCTIONSV\", \"Shipping Instructions\"}, {\"PACKING_INSTRUCTIONSV\", \"Packing Instructions\"}, {\"GROSS_WEIGHT\", \"Gross Weight\"}, {\"NET_WEIGHT\", \"Net Weight\"}, {\"WEIGHT_UOM_CODE\", \"Weight Unit of Measure\"}, {\"VOLUME\", \"Volume\"}, {\"VOLUME_UOM_CODE\", \"Volume Unit of Measure\"}, {\"DELIVERY_PACK\", \"Delivery Packing Quantity\"}, {\"DELIVERY_PACK_UOM\", \"Delivery Packing Unit Of Measure\"}, {\"DELIVERY_PACK_DIMENSIONS\", \"Delivery Pack Dimensions\"}, {\"CONFIRM_DATE\", \"Delivery Confirm Date\"}, {\"SHIP_METHOD_CODE\", \"Ship Method Code\"}, {\"DELIVERY_TYPE\", \"Delivery Type\"}, {\"SERVICE_LEVEL\", \"Service Level\"}, {\"MODE_OF_TRANSPORT\", \"Mode Of Transport\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Sales_Shipment_Customer_Org = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, \n  Query=\"SELECT\n   sysdate extract_date,\n   wdd.source_line_id,\n   wdd.delivery_detail_id,\n   mp2.organization_code,\n   oel.ordered_item item_number,\n   flv.meaning released_status,\n   wnd.name delivery_number,\n   wnd.waybill delivery_waybill,\n   (\n      SELECT\n         mtrh.request_number \n      FROM\n         inv.mtl_txn_request_headers mtrh,\n         inv.mtl_txn_request_lines mtrl \n      WHERE\n         mtrl.line_id = wdd.move_order_line_id \n         AND mtrh.header_id = mtrl.header_id\n   )\n   move_order_number,\n   (\n      SELECT\n         mtrl.line_number \n      FROM\n         inv.mtl_txn_request_lines mtrl \n      WHERE\n         mtrl.line_id = wdd.move_order_line_id \n   )\n   move_order_line_number,\n   wdd.requested_quantity,\n   wdd.requested_quantity_uom,\n   wdd.cancelled_quantity,\n   wdd.picked_quantity,\n   CASE\n      WHEN\n         wdd.shipping_instructions IS NULL \n      THEN\n         nvl(oel.shipping_instructions, oeh.shipping_instructions) \n      ELSE\n         nvl(oel.shipping_instructions, oeh.shipping_instructions) || '/' || wdd.shipping_instructions \n   END\n   shipping_instructionsv , \n   CASE\n      WHEN\n         wdd.packing_instructions IS NULL \n      THEN\n         nvl(oel.packing_instructions, oeh.packing_instructions ) \n      ELSE\n         nvl(oel.packing_instructions, oeh.packing_instructions) || '/' || wdd.packing_instructions \n   END\n   packing_instructionsv , wnd.gross_weight , wnd.net_weight , wnd.weight_uom_code , wnd.volume , wnd.volume_uom_code , wnd.attribute1 delivery_pack , wnd.attribute2 delivery_pack_uom , wnd.attribute3 delivery_pack_dimensions , wnd.confirm_date , wnd.ship_method_code , wnd.delivery_type , wnd.service_level , wnd.mode_of_transport , wnd.delivery_id \nFROM\n   wsh.wsh_new_deliveries wnd , wsh.wsh_delivery_assignments wda , wsh.wsh_delivery_details wdd , apps.oe_order_lines_all oel , apps.oe_order_headers_all oeh , inv.mtl_parameters mp2 , apps.fnd_lookup_values_vl flv \nWHERE\n   1 = 1 \n   AND oeh.header_id = oel.header_id \n   AND wdd.delivery_detail_id = wda.delivery_detail_id ( + ) \n   AND wda.delivery_id = wnd.delivery_id ( + ) \n   AND mp2.organization_id = wdd.organization_id \n   AND mp2.organization_code = '\"&CUSTORG&\"' \n   AND mp2.organization_id = oel.ship_from_org_id \n   AND oel.line_id = wdd.source_line_id \n   AND wdd.organization_id = oel.ship_from_org_id \n   AND wdd.released_status = flv.lookup_code \n   AND flv.lookup_type = 'PICK_STATUS'\n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"EXTRACT_DATE\", \"Extract Date\"}, {\"ORGANIZATION_CODE\", \"Organization Code\"}, {\"ITEM_NUMBER\", \"Item Number\"}, {\"RELEASED_STATUS\", \"Released Status\"}, {\"DELIVERY_NUMBER\", \"Delivery Number\"}, {\"DELIVERY_WAYBILL\", \"Delivery Waybill\"}, {\"MOVE_ORDER_NUMBER\", \"Pick Move Order Number\"}, {\"MOVE_ORDER_LINE_NUMBER\", \"Pick Move Order Line Number\"}, {\"REQUESTED_QUANTITY\", \"Requested Quantity\"}, {\"REQUESTED_QUANTITY_UOM\", \"Requested Quantity UOM\"}, {\"CANCELLED_QUANTITY\", \"Cancelled Quantity\"}, {\"PICKED_QUANTITY\", \"Picked Quantity\"}, {\"SHIPPING_INSTRUCTIONSV\", \"Shipping Instructions\"}, {\"PACKING_INSTRUCTIONSV\", \"Packing Instructions\"}, {\"GROSS_WEIGHT\", \"Gross Weight\"}, {\"NET_WEIGHT\", \"Net Weight\"}, {\"WEIGHT_UOM_CODE\", \"Weight Unit of Measure\"}, {\"VOLUME\", \"Volume\"}, {\"VOLUME_UOM_CODE\", \"Volume Unit of Measure\"}, {\"DELIVERY_PACK\", \"Delivery Packing Quantity\"}, {\"DELIVERY_PACK_UOM\", \"Delivery Packing Unit Of Measure\"}, {\"DELIVERY_PACK_DIMENSIONS\", \"Delivery Pack Dimensions\"}, {\"CONFIRM_DATE\", \"Delivery Confirm Date\"}, {\"SHIP_METHOD_CODE\", \"Ship Method Code\"}, {\"DELIVERY_TYPE\", \"Delivery Type\"}, {\"SERVICE_LEVEL\", \"Service Level\"}, {\"MODE_OF_TRANSPORT\", \"Mode Of Transport\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Sales_Backlog = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, \n  Query=\"\n  SELECT\n    mp.organization_code,\n    xxbl.asof_date,\n    xxbl.order_number,\n    xxbl.order_line,\n    xxbl.order_type,\n    xxbl.so_line_type,\n    xxbl.line_status,\n    xxbl.backlog_quantity,\n    xxbl.tr_item_unit_cost,\n    xxbl.ship_to_country,\n    xxbl.item_number,\n    xxbl.item_description,\n    xxbl.first_schedule_date,\n    xxbl.schedule_category_period,\n    xxbl.schedule_category,\n    xxbl.request_ship_date,\n    xxbl.promise_ship_date,\n    xxbl.schedule_ship_date\nFROM\n    xxcoh.xxcoh_backlog_tab    xxbl,\n    ont.oe_order_lines_all     oel,\n    apps.mtl_parameters        mp\nWHERE\n        xxbl.line_id = oel.line_id\n    AND xxbl.header_id = oel.header_id\n    AND oel.ship_from_org_id = mp.organization_id\n    AND mp.organization_code = '\"&ORG&\"'\n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"ORDER_NUMBER\", \"Order Number\"}, {\"ORDER_LINE\", \"Order Line\"}, {\"ORDER_TYPE\", \"Order Type\"}, {\"SO_LINE_TYPE\", \"Line Type\"}, {\"LINE_STATUS\", \"Line Status\"}, {\"BACKLOG_QUANTITY\", \"Backlog Quantity\"}, {\"TR_ITEM_UNIT_COST\", \"Item Cost\"}, {\"SHIP_TO_COUNTRY\", \"Ship To Country\"}, {\"ITEM_NUMBER\", \"Item Number\"}, {\"ITEM_DESCRIPTION\", \"Item Description\"}, {\"FIRST_SCHEDULE_DATE\", \"First Schedule Date\"}, {\"SCHEDULE_CATEGORY_PERIOD\", \"Schedule Category Period\"}, {\"SCHEDULE_CATEGORY\", \"Schedule Category\"}, {\"REQUEST_SHIP_DATE\", \"Request Ship Date\"}, {\"PROMISE_SHIP_DATE\", \"Promise Ship Date\"}, {\"SCHEDULE_SHIP_DATE\", \"Schedule Ship Date\"}})\r\nin\r\n  #\"Renamed columns\";\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"Sales_Customer_Org","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Sales_Customer_Org.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Ship From Org","dataType":"string"},{"name":"Operating Unit","dataType":"string"},{"name":"Order Number","dataType":"double"},{"name":"HEADER_ID","dataType":"double"},{"name":"End Customer Name","dataType":"string"},{"name":"Line Number","dataType":"double"},{"name":"Shipment Number","dataType":"double"},{"name":"Open Flag","dataType":"string"},{"name":"Cancelled Flag","dataType":"string"},{"name":"Ship Set ID","dataType":"double"},{"name":"Order Type","dataType":"string"},{"name":"ORDER_TYPE_ID","dataType":"double"},{"name":"Line Type","dataType":"string"},{"name":"LINE_TYPE_ID","dataType":"double"},{"name":"Revenue Flag","dataType":"string"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"Item Number","dataType":"string"},{"name":"Currency Code","dataType":"string"},{"name":"Unit Price","dataType":"double"},{"name":"Ordered Quantity","dataType":"double"},{"name":"Booked Flag","dataType":"string"},{"name":"Shipped Quantity","dataType":"double"},{"name":"Customer Type","dataType":"string"},{"name":"Customer","dataType":"string"},{"name":"Status","dataType":"string"},{"name":"Shipment Priority","dataType":"string"},{"name":"Shippable Flag","dataType":"string"},{"name":"Shipping Method","dataType":"string"},{"name":"Ship From Subinventory","dataType":"string"},{"name":"Market","dataType":"string"},{"name":"Category Code","dataType":"string"},{"name":"Regional Location","dataType":"string"},{"name":"Reporting Entity","dataType":"string"},{"name":"Sales or Service","dataType":"string"},{"name":"Line Category","dataType":"string"},{"name":"FOB Point","dataType":"string"},{"name":"Custom Invoice Value","dataType":"string"},{"name":"Freight Terms","dataType":"string"},{"name":"Ship To Country","dataType":"string"},{"name":"Ship To City","dataType":"string"},{"name":"Actual Fulfillment Date","dataType":"dateTime"},{"name":"Actual Shipment Date","dataType":"dateTime"},{"name":"Schedule Ship Date","dataType":"dateTime"},{"name":"Request Date","dataType":"dateTime"},{"name":"Promised Date","dataType":"dateTime"},{"name":"Original Document Reference","dataType":"string"},{"name":"Source Name","dataType":"string"},{"name":"Planner","dataType":"string"},{"name":"Line Created By","dataType":"string"},{"name":"Line Last Updated By","dataType":"string"},{"name":"Line Creation Date","dataType":"dateTime"},{"name":"Line Last Update Date","dataType":"dateTime"},{"name":"Sales Rep","dataType":"string"},{"name":"LINE_ID","dataType":"double"},{"name":"Book Date","dataType":"dateTime"},{"name":"END_CUSTOMER_ID","dataType":"double"},{"name":"Unit Cost USD","dataType":"double"},{"name":"Revenue Amount USD","dataType":"double"},{"name":"Book USD Rate","dataType":"double"},{"name":"Delivery Detail Flag","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-05-20T05:31:38.9595925+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/357f869e-abe6-4fe7-affa-5f47d7d7953f/Sales_Customer_Org.csv?snapshot=2022-05-20T05%3A31%3A38.6332979Z"}]},{"$type":"LocalEntity","name":"Sales_Hold","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Sales_Hold.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"HOLD_SOURCE_ID","dataType":"double"},{"name":"Hold Level","dataType":"string"},{"name":"HEADER_ID","dataType":"double"},{"name":"LINE_ID","dataType":"double"},{"name":"HOLD_ID","dataType":"double"},{"name":"Hold Reason","dataType":"string"},{"name":"Hold Release Flag","dataType":"string"},{"name":"Creation Date","dataType":"dateTime"},{"name":"Created By","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-05-20T05:30:43.3045454+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/357f869e-abe6-4fe7-affa-5f47d7d7953f/Sales_Hold.csv?snapshot=2022-05-20T05%3A30%3A42.5563087Z"}]},{"$type":"LocalEntity","name":"Sales","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Sales.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Ship From Org","dataType":"string"},{"name":"Operating Unit","dataType":"string"},{"name":"Order Number","dataType":"double"},{"name":"HEADER_ID","dataType":"double"},{"name":"End Customer Name","dataType":"string"},{"name":"Line Number","dataType":"double"},{"name":"Shipment Number","dataType":"double"},{"name":"Open Flag","dataType":"string"},{"name":"Cancelled Flag","dataType":"string"},{"name":"Ship Set ID","dataType":"double"},{"name":"Order Type","dataType":"string"},{"name":"ORDER_TYPE_ID","dataType":"double"},{"name":"Line Type","dataType":"string"},{"name":"LINE_TYPE_ID","dataType":"double"},{"name":"Revenue Flag","dataType":"string"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"Item Number","dataType":"string"},{"name":"Currency Code","dataType":"string"},{"name":"Unit Price","dataType":"double"},{"name":"Ordered Quantity","dataType":"double"},{"name":"Booked Flag","dataType":"string"},{"name":"Shipped Quantity","dataType":"double"},{"name":"Customer Type","dataType":"string"},{"name":"Customer","dataType":"string"},{"name":"Status","dataType":"string"},{"name":"Shipment Priority","dataType":"string"},{"name":"Shippable Flag","dataType":"string"},{"name":"Shipping Method","dataType":"string"},{"name":"Ship From Subinventory","dataType":"string"},{"name":"Market","dataType":"string"},{"name":"Category Code","dataType":"string"},{"name":"Regional Location","dataType":"string"},{"name":"Reporting Entity","dataType":"string"},{"name":"Sales or Service","dataType":"string"},{"name":"Line Category","dataType":"string"},{"name":"FOB Point","dataType":"string"},{"name":"Custom Invoice Value","dataType":"string"},{"name":"Freight Terms","dataType":"string"},{"name":"Ship To Country","dataType":"string"},{"name":"Ship To City","dataType":"string"},{"name":"Actual Fulfillment Date","dataType":"dateTime"},{"name":"Actual Shipment Date","dataType":"dateTime"},{"name":"Schedule Ship Date","dataType":"dateTime"},{"name":"Request Date","dataType":"dateTime"},{"name":"Promised Date","dataType":"dateTime"},{"name":"Original Document Reference","dataType":"string"},{"name":"Source Name","dataType":"string"},{"name":"Planner","dataType":"string"},{"name":"Line Created By","dataType":"string"},{"name":"Line Last Updated By","dataType":"string"},{"name":"Line Creation Date","dataType":"dateTime"},{"name":"Line Last Update Date","dataType":"dateTime"},{"name":"Sales Rep","dataType":"string"},{"name":"LINE_ID","dataType":"double"},{"name":"Book Date","dataType":"dateTime"},{"name":"END_CUSTOMER_ID","dataType":"double"},{"name":"Unit Cost USD","dataType":"double"},{"name":"Revenue Amount USD","dataType":"double"},{"name":"Book USD Rate","dataType":"double"},{"name":"Delivery Detail Flag","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-05-20T05:31:47.7408558+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/357f869e-abe6-4fe7-affa-5f47d7d7953f/Sales.csv?snapshot=2022-05-20T05%3A31%3A47.6971254Z"}]},{"$type":"LocalEntity","name":"Sales_Line_Attachment","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Sales_Line_Attachment.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Sequence","dataType":"double"},{"name":"Document Category","dataType":"string"},{"name":"Description","dataType":"string"},{"name":"Title","dataType":"string"},{"name":"File Type","dataType":"string"},{"name":"Document Text","dataType":"string"},{"name":"Order Number","dataType":"double"},{"name":"Order Line","dataType":"string"},{"name":"Document Level","dataType":"string"},{"name":"LINE_ID","dataType":"double"},{"name":"HEADER_ID","dataType":"double"},{"name":"Ship From Org","dataType":"string"},{"name":"Last Update Date","dataType":"dateTime"},{"name":"Last Updated By","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-05-20T05:31:01.6462078+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/357f869e-abe6-4fe7-affa-5f47d7d7953f/Sales_Line_Attachment.csv?snapshot=2022-05-20T05%3A31%3A01.4525152Z"}]},{"$type":"LocalEntity","name":"Sales_Shipment","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Sales_Shipment.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"SOURCE_LINE_ID","dataType":"double"},{"name":"DELIVERY_DETAIL_ID","dataType":"double"},{"name":"Organization Code","dataType":"string"},{"name":"Item Number","dataType":"string"},{"name":"Released Status","dataType":"string"},{"name":"Delivery Number","dataType":"string"},{"name":"Delivery Waybill","dataType":"string"},{"name":"Pick Move Order Number","dataType":"string"},{"name":"Pick Move Order Line Number","dataType":"double"},{"name":"Requested Quantity","dataType":"double"},{"name":"Requested Quantity UOM","dataType":"string"},{"name":"Cancelled Quantity","dataType":"double"},{"name":"Picked Quantity","dataType":"double"},{"name":"Shipping Instructions","dataType":"string"},{"name":"Packing Instructions","dataType":"string"},{"name":"Gross Weight","dataType":"double"},{"name":"Net Weight","dataType":"double"},{"name":"Weight Unit of Measure","dataType":"string"},{"name":"Volume","dataType":"double"},{"name":"Volume Unit of Measure","dataType":"string"},{"name":"Delivery Packing Quantity","dataType":"string"},{"name":"Delivery Packing Unit Of Measure","dataType":"string"},{"name":"Delivery Pack Dimensions","dataType":"string"},{"name":"Delivery Confirm Date","dataType":"dateTime"},{"name":"Ship Method Code","dataType":"string"},{"name":"Delivery Type","dataType":"string"},{"name":"Service Level","dataType":"string"},{"name":"Mode Of Transport","dataType":"string"},{"name":"DELIVERY_ID","dataType":"double"}],"partitions":[{"name":"Part001","refreshTime":"2022-05-20T05:31:40.0689664+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/357f869e-abe6-4fe7-affa-5f47d7d7953f/Sales_Shipment.csv?snapshot=2022-05-20T05%3A31%3A38.5773297Z"}]},{"$type":"LocalEntity","name":"Sales_Shipment_Customer_Org","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Sales_Shipment_Customer_Org.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"SOURCE_LINE_ID","dataType":"double"},{"name":"DELIVERY_DETAIL_ID","dataType":"double"},{"name":"Organization Code","dataType":"string"},{"name":"Item Number","dataType":"string"},{"name":"Released Status","dataType":"string"},{"name":"Delivery Number","dataType":"string"},{"name":"Delivery Waybill","dataType":"string"},{"name":"Pick Move Order Number","dataType":"string"},{"name":"Pick Move Order Line Number","dataType":"double"},{"name":"Requested Quantity","dataType":"double"},{"name":"Requested Quantity UOM","dataType":"string"},{"name":"Cancelled Quantity","dataType":"double"},{"name":"Picked Quantity","dataType":"double"},{"name":"Shipping Instructions","dataType":"string"},{"name":"Packing Instructions","dataType":"string"},{"name":"Gross Weight","dataType":"double"},{"name":"Net Weight","dataType":"double"},{"name":"Weight Unit of Measure","dataType":"string"},{"name":"Volume","dataType":"double"},{"name":"Volume Unit of Measure","dataType":"string"},{"name":"Delivery Packing Quantity","dataType":"string"},{"name":"Delivery Packing Unit Of Measure","dataType":"string"},{"name":"Delivery Pack Dimensions","dataType":"string"},{"name":"Delivery Confirm Date","dataType":"dateTime"},{"name":"Ship Method Code","dataType":"string"},{"name":"Delivery Type","dataType":"string"},{"name":"Service Level","dataType":"string"},{"name":"Mode Of Transport","dataType":"string"},{"name":"DELIVERY_ID","dataType":"double"}],"partitions":[{"name":"Part001","refreshTime":"2022-05-20T05:30:16.6923769+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/357f869e-abe6-4fe7-affa-5f47d7d7953f/Sales_Shipment_Customer_Org.csv?snapshot=2022-05-20T05%3A30%3A16.6571118Z"}]},{"$type":"LocalEntity","name":"Sales_Backlog","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Sales_Backlog.csv"},"attributes":[{"name":"ORGANIZATION_CODE","dataType":"string"},{"name":"ASOF_DATE","dataType":"dateTime"},{"name":"Order Number","dataType":"double"},{"name":"Order Line","dataType":"string"},{"name":"Order Type","dataType":"string"},{"name":"Line Type","dataType":"string"},{"name":"Line Status","dataType":"string"},{"name":"Backlog Quantity","dataType":"double"},{"name":"Item Cost","dataType":"double"},{"name":"Ship To Country","dataType":"string"},{"name":"Item Number","dataType":"string"},{"name":"Item Description","dataType":"string"},{"name":"First Schedule Date","dataType":"string"},{"name":"Schedule Category Period","dataType":"string"},{"name":"Schedule Category","dataType":"string"},{"name":"Request Ship Date","dataType":"dateTime"},{"name":"Promise Ship Date","dataType":"dateTime"},{"name":"Schedule Ship Date","dataType":"dateTime"}],"partitions":[{"name":"Part001","refreshTime":"2022-05-20T05:31:23.5252705+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/357f869e-abe6-4fe7-affa-5f47d7d7953f/Sales_Backlog.csv?snapshot=2022-05-20T05%3A31%3A19.0464765Z"}]}]}