{"name":"COHERENT_SNOWFLAKE","description":"verschiedene Tabellen von Snowflake\nXXCOH_IM_CATEGORY_V - Items für z.b. Forecast","version":"1.0","culture":"en-US","modifiedTime":"2022-05-19T07:48:47.318898+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"XXREP_RESOURCE_TRAN_V":{"queryId":"fdde91a1-087d-4698-8828-9fbdb40f0378","queryName":"XXREP_RESOURCE_TRAN_V","loadEnabled":true},"InvOrg_Code":{"queryId":"385d2545-1cf0-4981-968a-adc7ad8c05ce","queryName":"InvOrg_Code"},"XXCOH_IM_ITEM_VIEW":{"queryId":"dbb5904c-f19e-4089-b708-ac4155851bd7","queryName":"XXCOH_IM_ITEM_VIEW","loadEnabled":true},"XXCOH_IM_CATEGORY_VIEW":{"queryId":"7aa8f999-0786-4fb4-99a1-82bb350a3c18","queryName":"XXCOH_IM_CATEGORY_VIEW","loadEnabled":true},"XXREP_MTL_SYSTEM_ITEMS_V":{"queryId":"4e60f7cc-b679-4462-930f-c73c35816b66","queryName":"XXREP_MTL_SYSTEM_ITEMS_V","loadEnabled":true},"Organization_ID":{"queryId":"1c3fc304-151e-4275-8546-a8e02e566ab2","queryName":"Organization_ID"},"RESOURCE_TRAN_LDP_TIMES":{"queryId":"9a121810-08cc-4981-bb41-192086e0da5d","queryName":"RESOURCE_TRAN_LDP_TIMES","loadEnabled":true},"XXCOH_WIP_TRX_VIEW":{"queryId":"99924e07-f42c-4a77-b65a-c6c199a3a82d","queryName":"XXCOH_WIP_TRX_VIEW","loadEnabled":true},"XXCOH_MI_WIP_FIN_VIEW":{"queryId":"9624f946-2599-44bf-a065-28b00bb2e6c2","queryName":"XXCOH_MI_WIP_FIN_VIEW","loadEnabled":true},"TechnicalBusinessUnit":{"queryId":"b96d58a9-06f8-46f9-baa5-b46f32cd15f4","queryName":"TechnicalBusinessUnit"},"EarliestDate":{"queryId":"5b777cca-6ff5-4e4a-b807-458f06ddc06a","queryName":"EarliestDate"},"XXREP_WIP_DISCRETE_JOBS_V":{"queryId":"139602fb-9834-45f8-91a1-28145997c4d8","queryName":"XXREP_WIP_DISCRETE_JOBS_V","loadEnabled":true},"TechnicalBusinessUnit (2)":{"queryId":"1ee8269f-4584-4893-8fdd-b72907cc121e","queryName":"TechnicalBusinessUnit (2)"}},"document":"section Section1;\r\nshared XXREP_RESOURCE_TRAN_V = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 1\" = Navigation{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXREP_RESOURCE_TRAN_V\", Kind = \"View\"]}[Data],\r\n  #\"Filtered rows_OrgID_TransDate\" = Table.SelectRows(#\"Navigation 2\", each [TRANSACTION_DATE] >= EarliestDate),\r\n  #\"Filtered rows 1\" = Table.SelectRows(#\"Filtered rows_OrgID_TransDate\", each Text.EndsWith([WIPJOB_ORG_KEY_CODE], \"SPG\") or Text.EndsWith([WIPJOB_ORG_KEY_CODE], \"LDP\"))\r\nin\r\n  #\"Filtered rows 1\";\r\nshared InvOrg_Code = let\r\n  Inv_Org = \"LDP\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type any]\r\nin\r\n  Inv_Org;\r\nshared XXCOH_IM_ITEM_VIEW = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 1\" = Navigation{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXCOH_IM_ITEM_VIEW\", Kind = \"View\"]}[Data],\r\n  #\"Filtered rows - Org\" = Table.SelectRows(#\"Navigation 2\", each [ORGANIZATION_CODE] = InvOrg_Code),\r\n  #\"Removed columns\" = Table.RemoveColumns(#\"Filtered rows - Org\", {\"LAST_UPDATED_BY\", \"CREATED_BY\", \"LAST_UPDATE_LOGIN\", \"SUMMARY_FLAG\", \"BUYER_ID\", \"SEGMENT1\", \"ATTRIBUTE_CATEGORY\", \"ATTRIBUTE13\", \"ATTRIBUTE14\", \"ATTRIBUTE15\"})\r\nin\r\n  #\"Removed columns\";\r\nshared XXCOH_IM_CATEGORY_VIEW = let\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\n  Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\n  #\"Navigation 1\" = Navigation{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXCOH_IM_CATEGORY_VIEW\", Kind = \"View\"]}[Data],\r\n  #\"Filtered rows\" = Table.SelectRows(#\"Navigation 2\", each [ORGANIZATION_CODE] = \"LDP\" or [ORGANIZATION_CODE] = \"SPG\"),\n  /*#\"Filtered rows-Org\" = Table.SelectRows(#\"Navigation 2\", each [ORGANIZATION_CODE] = InvOrg_Code),*/\n  #\"Filtered rows -Item <>'D'\" = Table.SelectRows( #\"Filtered rows\", each not Text.StartsWith([ITEM_NUMBER], \"D\")),\n  #\"Removed columns\" = Table.RemoveColumns(#\"Filtered rows -Item <>'D'\", {\"ROW_UPDATED_BY\", \"PF_ITEM_NUMBER\", \"ECCN_ECCN\", \"COO_COUNTRY_OF_ORIGIN\", \"HTS_HTS_SCHEDULE_B\", \"PLNG_GREEN_SUPPLY_STATUS\", \"PLNG_PLANNING_ACTION\", \"PLNG_FAMILY_UNIQUE\", \"ST_SALES_TAX_CATEGORY\", \"CDI_CARTON_GROUP\", \"CI_CARTON_GROUP\", \"CON_CONTRACT_CATEGORY\", \"PTLX_PATLEX_PERCENT\", \"COMM_COMMODITY\", \"SLT_SERVICE_LEAD_TIME\", \"FF_FORECAST_FIELD\", \"CS_SUPPLY_SOURCE\", \"CS_DEMAND_SOURCE\", \"DBT_DB_TEMP\", \"BUP_BACKUP\", \"PO_PRIMARY_ORG\", \"PO_SUPPLY_CHAIN_PORG\", \"BCP_BCP\", \"CUST_CUSTOMER\", \"ROYLT_ROYALTY\", \"SC_SECURITY_CLASS\", \"GTD_GREEN_TRANSITION_DATE\", \"ROH_EU_ROHS_COMPLIANT\", \"ROH_CHINA_ROHS_COMPLIANT\", \"FDA_FDA_ACCESSION\", \"SCC_SEQUENCE\", \"SCC_COMMODITY\", \"SCC_UNSPSC\", \"SR_OPERATING_UNIT\", \"SR_PERCENTAGE\", \"SR_VENDOR\", \"SR_VENDOR_SITE\", \"SI_INSTALL_WITH_SALE\", \"IT_ITEM_TYPE_CODE\", \"OPSR_SEC_REPORTING\", \"OPSR_DEMAND_SOURCE\", \"SECR_SEC_REPORTING\", \"OPC_ORG\", \"OPC_PLANNING_CODE\", \"SP_SHIPMENT_PRIORITY\", \"FI_FISCAL_YEAR\", \"FI_SFDC_FORECAST_ITEM\", \"PG_ORG\", \"PG_PLANNING_GROUP\", \"WC_ORG\", \"WC_WORK_CELL\", \"RM_REPLENISHMENT_METHOD\", \"SFLT_SUPPLIER_FULL_LEAD_TIME\", \"SCS_SUPPLY_CHAIN_STATUS\", \"BPAS_BPA_STATUS\", \"MCOO_MULTI_COUNTRY_OF_ORIGIN\", \"DSO_DEFAULT_SHIPPING_ORG\", \"SFDCT_SFDC_TRANSFER\", \"IKC_ORG\", \"IKC_ORG_GROUP\", \"IKC_USERID\", \"EUHTS_HTS_CODE_EU\", \"CRI_ACCOUNT_NUMBER\", \"XYZ_XYZ_CLASS\", \"SCSD_SUPPLY_CHAIN_STATUS_DAYS\", \"MMKS_SOURCE\", \"MMKS_AUTO_UPDATE\", \"DO_DESIGN_ORG\"}),\n  #\"Reordered columns\" = Table.ReorderColumns(#\"Removed columns\", {\"INVENTORY_ITEM_ID\", \"ORGANIZATION_ID\", \"ITEM_NUMBER\", \"DESCRIPTION\", \"ORGANIZATION_CODE\", \"ITEM_CREATION_DATE\", \"ROW_CREATION_DATE\", \"OPROD_TBU\", \"PROD_TBU\", \"PROD_FAMILY\", \"PROD_LINE\", \"PROD_FORECAST_FIELD\", \"OPROD_FAMILY\", \"OPROD_LINE\", \"OPROD_FORECAST_FIELD\", \"IT_ITEM_TYPE_MEANING\"}),\n  #\"Removed columns 1\" = Table.RemoveColumns(#\"Reordered columns\", {\"ROW_CREATION_DATE\"}),\n  #\"Reordered columns 1\" = Table.ReorderColumns(#\"Removed columns 1\", {\"INVENTORY_ITEM_ID\", \"ORGANIZATION_ID\", \"ITEM_NUMBER\", \"DESCRIPTION\", \"OPROD_TBU\", \"ORGANIZATION_CODE\", \"ITEM_CREATION_DATE\", \"PROD_TBU\", \"PROD_FAMILY\", \"PROD_LINE\", \"PROD_FORECAST_FIELD\", \"OPROD_FAMILY\", \"OPROD_LINE\", \"OPROD_FORECAST_FIELD\", \"IT_ITEM_TYPE_MEANING\"})\nin\n  #\"Reordered columns 1\";\r\nshared XXREP_MTL_SYSTEM_ITEMS_V = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 1\" = Navigation{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXREP_MTL_SYSTEM_ITEMS_V\", Kind = \"View\"]}[Data],\r\n  #\"Filtered rows\" = Table.SelectRows(#\"Navigation 2\", each [ORGANIZATION_CODE] = InvOrg_Code)\r\nin\r\n  #\"Filtered rows\";\r\nshared Organization_ID = let\r\n  Inv_Org = 587 meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type any]\r\nin\r\n  Inv_Org;\r\nshared RESOURCE_TRAN_LDP_TIMES = let\r\n  Source = XXREP_RESOURCE_TRAN_V,\r\n  #\"Removed columns\" = Table.RemoveColumns(Source, {\"CREATED_BY_LOGIN\", \"INVORG_ID\",\"ATTRIBUTE1\",\"ATTRIBUTE2\",\"ATTRIBUTE_CATEGORY\",\"ACTIVITY\",\"EMPLOYEE_ID\"}),\r\n  #\"Filtered rows\" = Table.SelectRows(#\"Removed columns\", each ([TRANSACTION_UOM] = \"HR\" or [TRANSACTION_UOM] = \"MIN\" or [TRANSACTION_UOM] = \"MN\")),\r\n  #\"Duplicated column\" = Table.DuplicateColumn(#\"Filtered rows\", \"TRANSACTION_DATE\", \"TRANSACTION_DATE_ONLY\"),\r\n  #\"Calculated date\" = Table.TransformColumns(#\"Duplicated column\", {{\"TRANSACTION_DATE_ONLY\", each DateTime.Date(_), type nullable date}}),\r\n  #\"Added custom\" = Table.AddColumn(#\"Calculated date\", \"TRANSACTION_QUANTITY[h]\", each if[TRANSACTION_UOM]=\"MN\" or [TRANSACTION_UOM]=\"MIN\" then [TRANSACTION_QUANTITY]/60 else[TRANSACTION_QUANTITY]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Added custom\", {{\"TRANSACTION_QUANTITY[h]\", type number}})\r\nin\r\n  #\"Changed column type\";\r\nshared XXCOH_WIP_TRX_VIEW = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 1\" = Navigation{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n  #\"Filtered rows 1\" = Table.SelectRows(#\"Navigation 1\", each [Name] = \"WIP_DISCRETE_JOBS_V\" or [Name] = \"XXCOH_MI_WIP_FIN_VIEW\" or [Name] = \"XXCOH_WIP_TRX_VIEW\" or [Name] = \"XXREP_WIP_ACT_CLASSES_V\" or [Name] = \"XXREP_WIP_BALANCES_V\" or [Name] = \"XXREP_WIP_DISCRETE_JOBS_V\" or [Name] = \"XXSF_MI_WIP_RES_ACCT_V\" or [Name] = \"XXSF_MI_WIP_RESOURCE_V\"),\r\n  #\"Navigation 2\" = #\"Filtered rows 1\"{[Name = \"XXCOH_WIP_TRX_VIEW\", Kind = \"View\"]}[Data],\r\n  #\"Filtered rows_OrgID1\" = Table.SelectRows(#\"Navigation 2\", each [ORGANIZATION_ID] = Organization_ID),\r\n  #\"Filtered rows\" = Table.SelectRows(#\"Filtered rows_OrgID1\", each [TRX_DATE] >= EarliestDate)\r\nin\r\n  #\"Filtered rows\";\r\nshared XXCOH_MI_WIP_FIN_VIEW = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 1\" = Navigation{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXCOH_MI_WIP_FIN_VIEW\", Kind = \"View\"]}[Data],\r\n  #\"Filtered rows_BusinessUnit\" = Table.SelectRows(#\"Navigation 2\", each [FIN_TBU] = TechnicalBusinessUnit),\r\n  #\"Filtered rows\" = Table.SelectRows(#\"Filtered rows_BusinessUnit\", each [DATE_CLOSED] >= EarliestDate)\r\nin\r\n  #\"Filtered rows\";\r\nshared TechnicalBusinessUnit = let\r\n  Inv_Org = \"DPSS_Germany\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type any]\r\nin\r\n  Inv_Org;\r\nshared EarliestDate = let\r\n  EarliestDate = #datetime(2018, 12, 31, 0, 0, 0) meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type datetime]\r\nin\r\n  EarliestDate;\r\nshared XXREP_WIP_DISCRETE_JOBS_V = let\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\n  Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\n  #\"Navigation 1\" = Navigation{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXREP_WIP_DISCRETE_JOBS_V\", Kind = \"View\"]}[Data],\n  #\"Filtered rows 1\" = Table.SelectRows(#\"Navigation 2\", each [CREATION_DATE] > EarliestDate),\r\n  #\"Filtered rows\" = Table.SelectRows(#\"Filtered rows 1\", each [ORG_TBU] = #\"TechnicalBusinessUnit (2)\")\nin\n  #\"Filtered rows\";\r\nshared #\"TechnicalBusinessUnit (2)\" = let\r\n  Inv_Org = \"DPSS Germany\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type any]\r\nin\r\n  Inv_Org;\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"XXREP_RESOURCE_TRAN_V","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"XXREP_RESOURCE_TRAN_V.csv"},"attributes":[{"name":"JOB_NUMBER","dataType":"string"},{"name":"WIP_JOB_DESCRIPTION","dataType":"string"},{"name":"WIPJOB_ORG_KEY_CODE","dataType":"string"},{"name":"WIPJOB_ORG_KEY_ID","dataType":"string"},{"name":"DISCRETE_JOB_FLAG","dataType":"string"},{"name":"JOB_TYPE","dataType":"string"},{"name":"RESOURCE_TRX_REFERENCE","dataType":"string"},{"name":"TRANSACTION_ID","dataType":"double"},{"name":"TRANSACTION_TYPE","dataType":"string"},{"name":"TRANSACTION_DATE","dataType":"dateTime"},{"name":"SOURCE_CODE","dataType":"string"},{"name":"OPERATION_SEQ_NUM","dataType":"double"},{"name":"RESOURCE_SEQ_NUM","dataType":"double"},{"name":"AUTOCHARGE_TYPE","dataType":"string"},{"name":"USAGE_RATE_OR_AMOUNT","dataType":"double"},{"name":"BASIS_TYPE","dataType":"string"},{"name":"TRANSACTION_QUANTITY","dataType":"double"},{"name":"TRANSACTION_UOM","dataType":"string"},{"name":"PRIMARY_QUANTITY","dataType":"double"},{"name":"PRIMARY_UOM","dataType":"string"},{"name":"ACTUAL_RESOURCE_RATE","dataType":"double"},{"name":"STANDARD_RESOURCE_RATE","dataType":"double"},{"name":"STANDARD_RATE_FLAG","dataType":"string"},{"name":"CURRENCY_CODE","dataType":"string"},{"name":"MOVE_PRIMARY_QUANTITY","dataType":"double"},{"name":"FM_OPERATION_SEQ_NUM","dataType":"double"},{"name":"TO_OPERATION_SEQ_NUM","dataType":"double"},{"name":"ACTIVITY","dataType":"string"},{"name":"ATTRIBUTE_CATEGORY","dataType":"string"},{"name":"ATTRIBUTE1","dataType":"string"},{"name":"ATTRIBUTE2","dataType":"string"},{"name":"ORGANIZATION_ID","dataType":"double"},{"name":"WIP_ENTITY_ID","dataType":"double"},{"name":"LINE_ID","dataType":"double"},{"name":"PRIMARY_ITEM_ID","dataType":"double"},{"name":"DEPARTMENT_ID","dataType":"double"},{"name":"RESOURCE_ID","dataType":"double"},{"name":"EMPLOYEE_ID","dataType":"double"},{"name":"ACTIVITY_ID","dataType":"double"},{"name":"REASON_ID","dataType":"double"},{"name":"MOVE_TRANSACTION_ID","dataType":"double"},{"name":"COMPLETION_TRANSACTION_ID","dataType":"double"},{"name":"PROJECT_ID","dataType":"double"},{"name":"TASK_ID","dataType":"double"},{"name":"SOURCE_LINE_ID","dataType":"double"},{"name":"CREATION_DATE","dataType":"dateTime"},{"name":"CREATED_BY","dataType":"double"},{"name":"LAST_UPDATE_DATE","dataType":"dateTime"},{"name":"LAST_UPDATED_BY","dataType":"double"},{"name":"PROJECT_NAME","dataType":"string"},{"name":"PROJECT_NUMBER","dataType":"string"},{"name":"DEPARTMENT_CODE","dataType":"string"},{"name":"RESOURCE_CODE","dataType":"string"},{"name":"COST_CODE_TYPE","dataType":"double"},{"name":"ALLOW_COSTS","dataType":"string"},{"name":"ALLOW_COSTS_FLAG","dataType":"double"},{"name":"COST_CODE_TYPE_NAME","dataType":"string"},{"name":"ITEM_NUMBER","dataType":"string"},{"name":"ITEM_DESCRIPTION","dataType":"string"},{"name":"ITEM_ORG_KEY_ID","dataType":"string"},{"name":"ITEM_ORG_KEY_CODE","dataType":"string"},{"name":"ACCT_PERIOD_ID","dataType":"double"},{"name":"PERIOD_NAME","dataType":"string"},{"name":"PERIOD_START_DATE","dataType":"dateTime"},{"name":"PERIOD_CLOSE_DATE","dataType":"dateTime"},{"name":"INVORG_CODE","dataType":"string"},{"name":"INVORG_ID","dataType":"double"},{"name":"LOCAL_EXTRACT_DATE","dataType":"dateTime"},{"name":"EXTRACT_DATE","dataType":"dateTime"},{"name":"TIMEZONE","dataType":"string"},{"name":"CREATED_BY_LOGIN","dataType":"string"},{"name":"LAST_UPDATED_BY_LOGIN","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-20T01:06:03.2722809+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/85a769ac-dace-4397-a0cf-9b0dcedd673b/XXREP_RESOURCE_TRAN_V.csv?snapshot=2022-05-20T01%3A05%3A15.8318020Z"}]},{"$type":"LocalEntity","name":"XXCOH_IM_ITEM_VIEW","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"XXCOH_IM_ITEM_VIEW.csv"},"attributes":[{"name":"ITEM_ORG_KEY_ID","dataType":"string"},{"name":"ITEM_ORG_KEY_CODE","dataType":"string"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"ORGANIZATION_ID","dataType":"double"},{"name":"LAST_UPDATE_DATE","dataType":"dateTime"},{"name":"CREATION_DATE","dataType":"dateTime"},{"name":"ENABLED_FLAG","dataType":"string"},{"name":"DESCRIPTION","dataType":"string"},{"name":"PURCHASING_ITEM_FLAG","dataType":"string"},{"name":"SHIPPABLE_ITEM_FLAG","dataType":"string"},{"name":"CUSTOMER_ORDER_FLAG","dataType":"string"},{"name":"INTERNAL_ORDER_FLAG","dataType":"string"},{"name":"SERVICE_ITEM_FLAG","dataType":"string"},{"name":"INVENTORY_ITEM_FLAG","dataType":"string"},{"name":"ENG_ITEM_FLAG","dataType":"string"},{"name":"INVENTORY_ASSET_FLAG","dataType":"string"},{"name":"PURCHASING_ENABLED_FLAG","dataType":"string"},{"name":"CUSTOMER_ORDER_ENABLED_FLAG","dataType":"string"},{"name":"INTERNAL_ORDER_ENABLED_FLAG","dataType":"string"},{"name":"SO_TRANSACTIONS_FLAG","dataType":"string"},{"name":"MTL_TRANSACTIONS_ENABLED_FLAG","dataType":"string"},{"name":"STOCK_ENABLED_FLAG","dataType":"string"},{"name":"BOM_ENABLED_FLAG","dataType":"string"},{"name":"BUILD_IN_WIP_FLAG","dataType":"string"},{"name":"REVISION_QTY_CONTROL_CODE","dataType":"double"},{"name":"ITEM_CATALOG_GROUP_ID","dataType":"double"},{"name":"CATALOG_STATUS_FLAG","dataType":"string"},{"name":"RETURNABLE_FLAG","dataType":"string"},{"name":"DEFAULT_SHIPPING_ORG","dataType":"double"},{"name":"COLLATERAL_FLAG","dataType":"string"},{"name":"TAXABLE_FLAG","dataType":"string"},{"name":"QTY_RCV_EXCEPTION_CODE","dataType":"string"},{"name":"ALLOW_ITEM_DESC_UPDATE_FLAG","dataType":"string"},{"name":"INSPECTION_REQUIRED_FLAG","dataType":"string"},{"name":"RECEIPT_REQUIRED_FLAG","dataType":"string"},{"name":"MARKET_PRICE","dataType":"double"},{"name":"RFQ_REQUIRED_FLAG","dataType":"string"},{"name":"QTY_RCV_TOLERANCE","dataType":"double"},{"name":"LIST_PRICE_PER_UNIT","dataType":"double"},{"name":"PRICE_TOLERANCE_PERCENT","dataType":"double"},{"name":"UNIT_OF_ISSUE","dataType":"string"},{"name":"ENFORCE_SHIP_TO_LOCATION_CODE","dataType":"string"},{"name":"ALLOW_EXPRESS_DELIVERY_FLAG","dataType":"string"},{"name":"DAYS_EARLY_RECEIPT_ALLOWED","dataType":"double"},{"name":"DAYS_LATE_RECEIPT_ALLOWED","dataType":"double"},{"name":"RECEIPT_DAYS_EXCEPTION_CODE","dataType":"string"},{"name":"RECEIVING_ROUTING_ID","dataType":"double"},{"name":"RECEIVE_CLOSE_TOLERANCE","dataType":"double"},{"name":"AUTO_LOT_ALPHA_PREFIX","dataType":"string"},{"name":"START_AUTO_LOT_NUMBER","dataType":"string"},{"name":"LOT_CONTROL_CODE","dataType":"double"},{"name":"SHELF_LIFE_CODE","dataType":"double"},{"name":"SHELF_LIFE_DAYS","dataType":"double"},{"name":"SERIAL_NUMBER_CONTROL_CODE","dataType":"double"},{"name":"START_AUTO_SERIAL_NUMBER","dataType":"string"},{"name":"AUTO_SERIAL_ALPHA_PREFIX","dataType":"string"},{"name":"SOURCE_TYPE","dataType":"double"},{"name":"SOURCE_ORGANIZATION_ID","dataType":"double"},{"name":"SOURCE_SUBINVENTORY","dataType":"string"},{"name":"EXPENSE_ACCOUNT","dataType":"double"},{"name":"RESTRICT_SUBINVENTORIES_CODE","dataType":"double"},{"name":"UNIT_WEIGHT","dataType":"double"},{"name":"WEIGHT_UOM_CODE","dataType":"string"},{"name":"VOLUME_UOM_CODE","dataType":"string"},{"name":"UNIT_VOLUME","dataType":"double"},{"name":"RESTRICT_LOCATORS_CODE","dataType":"double"},{"name":"LOCATION_CONTROL_CODE","dataType":"double"},{"name":"SHRINKAGE_RATE","dataType":"double"},{"name":"ACCEPTABLE_EARLY_DAYS","dataType":"double"},{"name":"PLANNING_TIME_FENCE_CODE","dataType":"double"},{"name":"DEMAND_TIME_FENCE_CODE","dataType":"double"},{"name":"LEAD_TIME_LOT_SIZE","dataType":"double"},{"name":"STD_LOT_SIZE","dataType":"double"},{"name":"CUM_MANUFACTURING_LEAD_TIME","dataType":"double"},{"name":"OVERRUN_PERCENTAGE","dataType":"double"},{"name":"MRP_CALCULATE_ATP_FLAG","dataType":"string"},{"name":"ACCEPTABLE_RATE_INCREASE","dataType":"double"},{"name":"ACCEPTABLE_RATE_DECREASE","dataType":"double"},{"name":"CUMULATIVE_TOTAL_LEAD_TIME","dataType":"double"},{"name":"PLANNING_TIME_FENCE_DAYS","dataType":"double"},{"name":"DEMAND_TIME_FENCE_DAYS","dataType":"double"},{"name":"END_ASSEMBLY_PEGGING_FLAG","dataType":"string"},{"name":"REPETITIVE_PLANNING_FLAG","dataType":"string"},{"name":"PLANNING_EXCEPTION_SET","dataType":"string"},{"name":"BOM_ITEM_TYPE","dataType":"double"},{"name":"PICK_COMPONENTS_FLAG","dataType":"string"},{"name":"REPLENISH_TO_ORDER_FLAG","dataType":"string"},{"name":"BASE_ITEM_ID","dataType":"double"},{"name":"ATP_COMPONENTS_FLAG","dataType":"string"},{"name":"ATP_FLAG","dataType":"string"},{"name":"FIXED_LEAD_TIME","dataType":"double"},{"name":"VARIABLE_LEAD_TIME","dataType":"double"},{"name":"WIP_SUPPLY_LOCATOR_ID","dataType":"double"},{"name":"WIP_SUPPLY_TYPE","dataType":"double"},{"name":"WIP_SUPPLY_SUBINVENTORY","dataType":"string"},{"name":"PRIMARY_UOM_CODE","dataType":"string"},{"name":"PRIMARY_UNIT_OF_MEASURE","dataType":"string"},{"name":"ALLOWED_UNITS_LOOKUP_CODE","dataType":"double"},{"name":"COST_OF_SALES_ACCOUNT","dataType":"double"},{"name":"SALES_ACCOUNT","dataType":"double"},{"name":"DEFAULT_INCLUDE_IN_ROLLUP_FLAG","dataType":"string"},{"name":"INVENTORY_ITEM_STATUS_CODE","dataType":"string"},{"name":"INVENTORY_PLANNING_CODE","dataType":"double"},{"name":"PLANNER_CODE","dataType":"string"},{"name":"PLANNING_MAKE_BUY_CODE","dataType":"double"},{"name":"FIXED_LOT_MULTIPLIER","dataType":"double"},{"name":"ROUNDING_CONTROL_TYPE","dataType":"double"},{"name":"POSTPROCESSING_LEAD_TIME","dataType":"double"},{"name":"PREPROCESSING_LEAD_TIME","dataType":"double"},{"name":"FULL_LEAD_TIME","dataType":"double"},{"name":"ORDER_COST","dataType":"double"},{"name":"MRP_SAFETY_STOCK_PERCENT","dataType":"double"},{"name":"MRP_SAFETY_STOCK_CODE","dataType":"double"},{"name":"MIN_MINMAX_QUANTITY","dataType":"double"},{"name":"MAX_MINMAX_QUANTITY","dataType":"double"},{"name":"MINIMUM_ORDER_QUANTITY","dataType":"double"},{"name":"FIXED_ORDER_QUANTITY","dataType":"double"},{"name":"FIXED_DAYS_SUPPLY","dataType":"double"},{"name":"MAXIMUM_ORDER_QUANTITY","dataType":"double"},{"name":"ATP_RULE_ID","dataType":"double"},{"name":"RESERVABLE_TYPE","dataType":"double"},{"name":"POSITIVE_MEASUREMENT_ERROR","dataType":"double"},{"name":"NEGATIVE_MEASUREMENT_ERROR","dataType":"double"},{"name":"VENDOR_WARRANTY_FLAG","dataType":"string"},{"name":"SERVICEABLE_COMPONENT_FLAG","dataType":"string"},{"name":"SERVICEABLE_PRODUCT_FLAG","dataType":"string"},{"name":"PAYMENT_TERMS_ID","dataType":"double"},{"name":"PREVENTIVE_MAINTENANCE_FLAG","dataType":"string"},{"name":"TIME_BILLABLE_FLAG","dataType":"string"},{"name":"MATERIAL_BILLABLE_FLAG","dataType":"string"},{"name":"EXPENSE_BILLABLE_FLAG","dataType":"string"},{"name":"PRORATE_SERVICE_FLAG","dataType":"string"},{"name":"COVERAGE_SCHEDULE_ID","dataType":"double"},{"name":"SERVICE_DURATION_PERIOD_CODE","dataType":"string"},{"name":"SERVICE_DURATION","dataType":"double"},{"name":"INVOICEABLE_ITEM_FLAG","dataType":"string"},{"name":"INVOICE_ENABLED_FLAG","dataType":"string"},{"name":"MUST_USE_APPROVED_VENDOR_FLAG","dataType":"string"},{"name":"REQUEST_ID","dataType":"double"},{"name":"PROGRAM_APPLICATION_ID","dataType":"double"},{"name":"PROGRAM_ID","dataType":"double"},{"name":"PROGRAM_UPDATE_DATE","dataType":"dateTime"},{"name":"OUTSIDE_OPERATION_FLAG","dataType":"string"},{"name":"OUTSIDE_OPERATION_UOM_TYPE","dataType":"string"},{"name":"SAFETY_STOCK_BUCKET_DAYS","dataType":"double"},{"name":"AUTO_REDUCE_MPS","dataType":"double"},{"name":"COSTING_ENABLED_FLAG","dataType":"string"},{"name":"AUTO_CREATED_CONFIG_FLAG","dataType":"string"},{"name":"CYCLE_COUNT_ENABLED_FLAG","dataType":"string"},{"name":"ITEM_TYPE","dataType":"string"},{"name":"SHIP_MODEL_COMPLETE_FLAG","dataType":"string"},{"name":"MRP_PLANNING_CODE","dataType":"double"},{"name":"RETURN_INSPECTION_REQUIREMENT","dataType":"double"},{"name":"ATO_FORECAST_CONTROL","dataType":"double"},{"name":"RELEASE_TIME_FENCE_CODE","dataType":"double"},{"name":"RELEASE_TIME_FENCE_DAYS","dataType":"double"},{"name":"CONTAINER_ITEM_FLAG","dataType":"string"},{"name":"VEHICLE_ITEM_FLAG","dataType":"string"},{"name":"PRODUCT_FAMILY_ITEM_ID","dataType":"double"},{"name":"PURCHASING_TAX_CODE","dataType":"string"},{"name":"OVERCOMPLETION_TOLERANCE_TYPE","dataType":"double"},{"name":"OVERCOMPLETION_TOLERANCE_VALUE","dataType":"double"},{"name":"EFFECTIVITY_CONTROL","dataType":"double"},{"name":"CHECK_SHORTAGES_FLAG","dataType":"string"},{"name":"EQUIPMENT_TYPE","dataType":"double"},{"name":"DEFECT_TRACKING_ON_FLAG","dataType":"string"},{"name":"EVENT_FLAG","dataType":"string"},{"name":"ELECTRONIC_FLAG","dataType":"string"},{"name":"DOWNLOADABLE_FLAG","dataType":"string"},{"name":"COMMS_NL_TRACKABLE_FLAG","dataType":"string"},{"name":"ASSET_CREATION_CODE","dataType":"string"},{"name":"ORDERABLE_ON_WEB_FLAG","dataType":"string"},{"name":"BACK_ORDERABLE_FLAG","dataType":"string"},{"name":"WEB_STATUS","dataType":"string"},{"name":"INDIVISIBLE_FLAG","dataType":"string"},{"name":"BULK_PICKED_FLAG","dataType":"string"},{"name":"LOT_STATUS_ENABLED","dataType":"string"},{"name":"SERIAL_STATUS_ENABLED","dataType":"string"},{"name":"DEFAULT_SERIAL_STATUS_ID","dataType":"double"},{"name":"LOT_SPLIT_ENABLED","dataType":"string"},{"name":"LOT_MERGE_ENABLED","dataType":"string"},{"name":"FINANCING_ALLOWED_FLAG","dataType":"string"},{"name":"EAM_ACT_NOTIFICATION_FLAG","dataType":"string"},{"name":"DUAL_UOM_CONTROL","dataType":"double"},{"name":"DUAL_UOM_DEVIATION_HIGH","dataType":"double"},{"name":"DUAL_UOM_DEVIATION_LOW","dataType":"double"},{"name":"CONTRACT_ITEM_TYPE_CODE","dataType":"string"},{"name":"SERV_REQ_ENABLED_CODE","dataType":"string"},{"name":"SERV_BILLING_ENABLED_FLAG","dataType":"string"},{"name":"PLANNED_INV_POINT_FLAG","dataType":"string"},{"name":"LOT_TRANSLATE_ENABLED","dataType":"string"},{"name":"DEFAULT_SO_SOURCE_TYPE","dataType":"string"},{"name":"CREATE_SUPPLY_FLAG","dataType":"string"},{"name":"LOT_SUBSTITUTION_ENABLED","dataType":"string"},{"name":"OBJECT_VERSION_NUMBER","dataType":"double"},{"name":"TRACKING_QUANTITY_IND","dataType":"string"},{"name":"ONT_PRICING_QTY_SOURCE","dataType":"string"},{"name":"VMI_MINIMUM_UNITS","dataType":"double"},{"name":"VMI_MAXIMUM_UNITS","dataType":"double"},{"name":"SO_AUTHORIZATION_FLAG","dataType":"double"},{"name":"CONSIGNED_FLAG","dataType":"double"},{"name":"ASN_AUTOEXPIRE_FLAG","dataType":"double"},{"name":"VMI_FORECAST_TYPE","dataType":"double"},{"name":"EXCLUDE_FROM_BUDGET_FLAG","dataType":"double"},{"name":"DRP_PLANNED_FLAG","dataType":"double"},{"name":"CRITICAL_COMPONENT_FLAG","dataType":"double"},{"name":"CONTINOUS_TRANSFER","dataType":"double"},{"name":"CONVERGENCE","dataType":"double"},{"name":"DIVERGENCE","dataType":"double"},{"name":"CHILD_LOT_FLAG","dataType":"string"},{"name":"CHILD_LOT_VALIDATION_FLAG","dataType":"string"},{"name":"COPY_LOT_ATTRIBUTE_FLAG","dataType":"string"},{"name":"GRADE_CONTROL_FLAG","dataType":"string"},{"name":"HAZARDOUS_MATERIAL_FLAG","dataType":"string"},{"name":"LOT_DIVISIBLE_FLAG","dataType":"string"},{"name":"PROCESS_COSTING_ENABLED_FLAG","dataType":"string"},{"name":"PROCESS_EXECUTION_ENABLED_FLAG","dataType":"string"},{"name":"PROCESS_QUALITY_ENABLED_FLAG","dataType":"string"},{"name":"PROCESS_SUPPLY_LOCATOR_ID","dataType":"double"},{"name":"PROCESS_SUPPLY_SUBINVENTORY","dataType":"string"},{"name":"RECIPE_ENABLED_FLAG","dataType":"string"},{"name":"PREPOSITION_POINT","dataType":"string"},{"name":"REPAIR_PROGRAM","dataType":"double"},{"name":"OUTSOURCED_ASSEMBLY","dataType":"double"},{"name":"GDSN_OUTBOUND_ENABLED_FLAG","dataType":"string"},{"name":"SERIAL_TAGGING_FLAG","dataType":"string"},{"name":"IB_ITEM_TRACKING_LEVEL","dataType":"string"},{"name":"MCC_CONTROL_CODE","dataType":"double"},{"name":"START_DATE_ACTIVE","dataType":"dateTime"},{"name":"END_DATE_ACTIVE","dataType":"dateTime"},{"name":"ORGANIZATION_CODE","dataType":"string"},{"name":"ITEM_DESCRIPTION","dataType":"string"},{"name":"USER_ITEM_TYPE","dataType":"string"},{"name":"BOM_ITEM_TYPE_DESCRIPTION","dataType":"string"},{"name":"COST_SOURCE_TYPE","dataType":"string"},{"name":"DEFAULT_BUYER","dataType":"string"},{"name":"ITEM_CATALOG_GROUP","dataType":"string"},{"name":"DEFAULT_RECV_SUBINVENTORY","dataType":"string"},{"name":"END_ASSEMBLY_PEGGING","dataType":"string"},{"name":"EFFECTIVITY_DATE","dataType":"dateTime"},{"name":"REVISION","dataType":"string"},{"name":"POWERBI_REFRESH_PARTITION","dataType":"dateTime"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-20T01:01:32.7978495+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/85a769ac-dace-4397-a0cf-9b0dcedd673b/XXCOH_IM_ITEM_VIEW.csv?snapshot=2022-05-20T01%3A01%3A32.7779663Z"}]},{"$type":"LocalEntity","name":"XXCOH_IM_CATEGORY_VIEW","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"XXCOH_IM_CATEGORY_VIEW.csv"},"attributes":[{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"ORGANIZATION_ID","dataType":"double"},{"name":"ITEM_NUMBER","dataType":"string"},{"name":"DESCRIPTION","dataType":"string"},{"name":"OPROD_TBU","dataType":"string"},{"name":"ORGANIZATION_CODE","dataType":"string"},{"name":"ITEM_CREATION_DATE","dataType":"dateTime"},{"name":"PROD_TBU","dataType":"string"},{"name":"PROD_FAMILY","dataType":"string"},{"name":"PROD_LINE","dataType":"string"},{"name":"PROD_FORECAST_FIELD","dataType":"string"},{"name":"OPROD_FAMILY","dataType":"string"},{"name":"OPROD_LINE","dataType":"string"},{"name":"OPROD_FORECAST_FIELD","dataType":"string"},{"name":"IT_ITEM_TYPE_MEANING","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-20T01:01:12.0331985+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/85a769ac-dace-4397-a0cf-9b0dcedd673b/XXCOH_IM_CATEGORY_VIEW.csv?snapshot=2022-05-20T01%3A01%3A12.0108025Z"}]},{"$type":"LocalEntity","name":"XXREP_MTL_SYSTEM_ITEMS_V","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"XXREP_MTL_SYSTEM_ITEMS_V.csv"},"attributes":[{"name":"ITEM_ORG_KEY_ID","dataType":"string"},{"name":"ITEM_ORG_KEY_CODE","dataType":"string"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"ORGANIZATION_ID","dataType":"double"},{"name":"LAST_UPDATE_DATE","dataType":"dateTime"},{"name":"LAST_UPDATED_BY","dataType":"double"},{"name":"CREATION_DATE","dataType":"dateTime"},{"name":"CREATED_BY","dataType":"double"},{"name":"LAST_UPDATE_LOGIN","dataType":"double"},{"name":"SUMMARY_FLAG","dataType":"string"},{"name":"ENABLED_FLAG","dataType":"string"},{"name":"DESCRIPTION","dataType":"string"},{"name":"BUYER_ID","dataType":"double"},{"name":"SEGMENT1","dataType":"string"},{"name":"ATTRIBUTE_CATEGORY","dataType":"string"},{"name":"ATTRIBUTE13","dataType":"string"},{"name":"ATTRIBUTE14","dataType":"string"},{"name":"ATTRIBUTE15","dataType":"string"},{"name":"PURCHASING_ITEM_FLAG","dataType":"string"},{"name":"SHIPPABLE_ITEM_FLAG","dataType":"string"},{"name":"CUSTOMER_ORDER_FLAG","dataType":"string"},{"name":"INTERNAL_ORDER_FLAG","dataType":"string"},{"name":"SERVICE_ITEM_FLAG","dataType":"string"},{"name":"INVENTORY_ITEM_FLAG","dataType":"string"},{"name":"ENG_ITEM_FLAG","dataType":"string"},{"name":"INVENTORY_ASSET_FLAG","dataType":"string"},{"name":"PURCHASING_ENABLED_FLAG","dataType":"string"},{"name":"CUSTOMER_ORDER_ENABLED_FLAG","dataType":"string"},{"name":"INTERNAL_ORDER_ENABLED_FLAG","dataType":"string"},{"name":"SO_TRANSACTIONS_FLAG","dataType":"string"},{"name":"MTL_TRANSACTIONS_ENABLED_FLAG","dataType":"string"},{"name":"STOCK_ENABLED_FLAG","dataType":"string"},{"name":"BOM_ENABLED_FLAG","dataType":"string"},{"name":"BUILD_IN_WIP_FLAG","dataType":"string"},{"name":"REVISION_QTY_CONTROL_CODE","dataType":"double"},{"name":"ITEM_CATALOG_GROUP_ID","dataType":"double"},{"name":"CATALOG_STATUS_FLAG","dataType":"string"},{"name":"RETURNABLE_FLAG","dataType":"string"},{"name":"DEFAULT_SHIPPING_ORG","dataType":"double"},{"name":"COLLATERAL_FLAG","dataType":"string"},{"name":"TAXABLE_FLAG","dataType":"string"},{"name":"QTY_RCV_EXCEPTION_CODE","dataType":"string"},{"name":"ALLOW_ITEM_DESC_UPDATE_FLAG","dataType":"string"},{"name":"INSPECTION_REQUIRED_FLAG","dataType":"string"},{"name":"RECEIPT_REQUIRED_FLAG","dataType":"string"},{"name":"MARKET_PRICE","dataType":"double"},{"name":"RFQ_REQUIRED_FLAG","dataType":"string"},{"name":"QTY_RCV_TOLERANCE","dataType":"double"},{"name":"LIST_PRICE_PER_UNIT","dataType":"double"},{"name":"PRICE_TOLERANCE_PERCENT","dataType":"double"},{"name":"UNIT_OF_ISSUE","dataType":"string"},{"name":"ENFORCE_SHIP_TO_LOCATION_CODE","dataType":"string"},{"name":"ALLOW_EXPRESS_DELIVERY_FLAG","dataType":"string"},{"name":"DAYS_EARLY_RECEIPT_ALLOWED","dataType":"double"},{"name":"DAYS_LATE_RECEIPT_ALLOWED","dataType":"double"},{"name":"RECEIPT_DAYS_EXCEPTION_CODE","dataType":"string"},{"name":"RECEIVING_ROUTING_ID","dataType":"double"},{"name":"RECEIVE_CLOSE_TOLERANCE","dataType":"double"},{"name":"AUTO_LOT_ALPHA_PREFIX","dataType":"string"},{"name":"START_AUTO_LOT_NUMBER","dataType":"string"},{"name":"LOT_CONTROL_CODE","dataType":"double"},{"name":"SHELF_LIFE_CODE","dataType":"double"},{"name":"SHELF_LIFE_DAYS","dataType":"double"},{"name":"SERIAL_NUMBER_CONTROL_CODE","dataType":"double"},{"name":"START_AUTO_SERIAL_NUMBER","dataType":"string"},{"name":"AUTO_SERIAL_ALPHA_PREFIX","dataType":"string"},{"name":"SOURCE_TYPE","dataType":"double"},{"name":"SOURCE_ORGANIZATION_ID","dataType":"double"},{"name":"SOURCE_SUBINVENTORY","dataType":"string"},{"name":"EXPENSE_ACCOUNT","dataType":"double"},{"name":"RESTRICT_SUBINVENTORIES_CODE","dataType":"double"},{"name":"UNIT_WEIGHT","dataType":"double"},{"name":"WEIGHT_UOM_CODE","dataType":"string"},{"name":"VOLUME_UOM_CODE","dataType":"string"},{"name":"UNIT_VOLUME","dataType":"double"},{"name":"RESTRICT_LOCATORS_CODE","dataType":"double"},{"name":"LOCATION_CONTROL_CODE","dataType":"double"},{"name":"SHRINKAGE_RATE","dataType":"double"},{"name":"ACCEPTABLE_EARLY_DAYS","dataType":"double"},{"name":"PLANNING_TIME_FENCE_CODE","dataType":"double"},{"name":"DEMAND_TIME_FENCE_CODE","dataType":"double"},{"name":"LEAD_TIME_LOT_SIZE","dataType":"double"},{"name":"STD_LOT_SIZE","dataType":"double"},{"name":"CUM_MANUFACTURING_LEAD_TIME","dataType":"double"},{"name":"OVERRUN_PERCENTAGE","dataType":"double"},{"name":"MRP_CALCULATE_ATP_FLAG","dataType":"string"},{"name":"ACCEPTABLE_RATE_INCREASE","dataType":"double"},{"name":"ACCEPTABLE_RATE_DECREASE","dataType":"double"},{"name":"CUMULATIVE_TOTAL_LEAD_TIME","dataType":"double"},{"name":"PLANNING_TIME_FENCE_DAYS","dataType":"double"},{"name":"DEMAND_TIME_FENCE_DAYS","dataType":"double"},{"name":"END_ASSEMBLY_PEGGING_FLAG","dataType":"string"},{"name":"REPETITIVE_PLANNING_FLAG","dataType":"string"},{"name":"PLANNING_EXCEPTION_SET","dataType":"string"},{"name":"BOM_ITEM_TYPE","dataType":"double"},{"name":"PICK_COMPONENTS_FLAG","dataType":"string"},{"name":"REPLENISH_TO_ORDER_FLAG","dataType":"string"},{"name":"BASE_ITEM_ID","dataType":"double"},{"name":"ATP_COMPONENTS_FLAG","dataType":"string"},{"name":"ATP_FLAG","dataType":"string"},{"name":"FIXED_LEAD_TIME","dataType":"double"},{"name":"VARIABLE_LEAD_TIME","dataType":"double"},{"name":"WIP_SUPPLY_LOCATOR_ID","dataType":"double"},{"name":"WIP_SUPPLY_TYPE","dataType":"double"},{"name":"WIP_SUPPLY_SUBINVENTORY","dataType":"string"},{"name":"PRIMARY_UOM_CODE","dataType":"string"},{"name":"PRIMARY_UNIT_OF_MEASURE","dataType":"string"},{"name":"ALLOWED_UNITS_LOOKUP_CODE","dataType":"double"},{"name":"COST_OF_SALES_ACCOUNT","dataType":"double"},{"name":"SALES_ACCOUNT","dataType":"double"},{"name":"DEFAULT_INCLUDE_IN_ROLLUP_FLAG","dataType":"string"},{"name":"INVENTORY_ITEM_STATUS_CODE","dataType":"string"},{"name":"INVENTORY_PLANNING_CODE","dataType":"double"},{"name":"PLANNER_CODE","dataType":"string"},{"name":"PLANNING_MAKE_BUY_CODE","dataType":"double"},{"name":"FIXED_LOT_MULTIPLIER","dataType":"double"},{"name":"ROUNDING_CONTROL_TYPE","dataType":"double"},{"name":"POSTPROCESSING_LEAD_TIME","dataType":"double"},{"name":"PREPROCESSING_LEAD_TIME","dataType":"double"},{"name":"FULL_LEAD_TIME","dataType":"double"},{"name":"ORDER_COST","dataType":"double"},{"name":"MRP_SAFETY_STOCK_PERCENT","dataType":"double"},{"name":"MRP_SAFETY_STOCK_CODE","dataType":"double"},{"name":"MIN_MINMAX_QUANTITY","dataType":"double"},{"name":"MAX_MINMAX_QUANTITY","dataType":"double"},{"name":"MINIMUM_ORDER_QUANTITY","dataType":"double"},{"name":"FIXED_ORDER_QUANTITY","dataType":"double"},{"name":"FIXED_DAYS_SUPPLY","dataType":"double"},{"name":"MAXIMUM_ORDER_QUANTITY","dataType":"double"},{"name":"ATP_RULE_ID","dataType":"double"},{"name":"RESERVABLE_TYPE","dataType":"double"},{"name":"POSITIVE_MEASUREMENT_ERROR","dataType":"double"},{"name":"NEGATIVE_MEASUREMENT_ERROR","dataType":"double"},{"name":"VENDOR_WARRANTY_FLAG","dataType":"string"},{"name":"SERVICEABLE_COMPONENT_FLAG","dataType":"string"},{"name":"SERVICEABLE_PRODUCT_FLAG","dataType":"string"},{"name":"PAYMENT_TERMS_ID","dataType":"double"},{"name":"PREVENTIVE_MAINTENANCE_FLAG","dataType":"string"},{"name":"TIME_BILLABLE_FLAG","dataType":"string"},{"name":"MATERIAL_BILLABLE_FLAG","dataType":"string"},{"name":"EXPENSE_BILLABLE_FLAG","dataType":"string"},{"name":"PRORATE_SERVICE_FLAG","dataType":"string"},{"name":"COVERAGE_SCHEDULE_ID","dataType":"double"},{"name":"SERVICE_DURATION_PERIOD_CODE","dataType":"string"},{"name":"SERVICE_DURATION","dataType":"double"},{"name":"INVOICEABLE_ITEM_FLAG","dataType":"string"},{"name":"INVOICE_ENABLED_FLAG","dataType":"string"},{"name":"MUST_USE_APPROVED_VENDOR_FLAG","dataType":"string"},{"name":"REQUEST_ID","dataType":"double"},{"name":"PROGRAM_APPLICATION_ID","dataType":"double"},{"name":"PROGRAM_ID","dataType":"double"},{"name":"PROGRAM_UPDATE_DATE","dataType":"dateTime"},{"name":"OUTSIDE_OPERATION_FLAG","dataType":"string"},{"name":"OUTSIDE_OPERATION_UOM_TYPE","dataType":"string"},{"name":"SAFETY_STOCK_BUCKET_DAYS","dataType":"double"},{"name":"AUTO_REDUCE_MPS","dataType":"double"},{"name":"COSTING_ENABLED_FLAG","dataType":"string"},{"name":"AUTO_CREATED_CONFIG_FLAG","dataType":"string"},{"name":"CYCLE_COUNT_ENABLED_FLAG","dataType":"string"},{"name":"ITEM_TYPE","dataType":"string"},{"name":"SHIP_MODEL_COMPLETE_FLAG","dataType":"string"},{"name":"MRP_PLANNING_CODE","dataType":"double"},{"name":"RETURN_INSPECTION_REQUIREMENT","dataType":"double"},{"name":"ATO_FORECAST_CONTROL","dataType":"double"},{"name":"RELEASE_TIME_FENCE_CODE","dataType":"double"},{"name":"RELEASE_TIME_FENCE_DAYS","dataType":"double"},{"name":"CONTAINER_ITEM_FLAG","dataType":"string"},{"name":"VEHICLE_ITEM_FLAG","dataType":"string"},{"name":"PRODUCT_FAMILY_ITEM_ID","dataType":"double"},{"name":"PURCHASING_TAX_CODE","dataType":"string"},{"name":"OVERCOMPLETION_TOLERANCE_TYPE","dataType":"double"},{"name":"OVERCOMPLETION_TOLERANCE_VALUE","dataType":"double"},{"name":"EFFECTIVITY_CONTROL","dataType":"double"},{"name":"CHECK_SHORTAGES_FLAG","dataType":"string"},{"name":"EQUIPMENT_TYPE","dataType":"double"},{"name":"DEFECT_TRACKING_ON_FLAG","dataType":"string"},{"name":"EVENT_FLAG","dataType":"string"},{"name":"ELECTRONIC_FLAG","dataType":"string"},{"name":"DOWNLOADABLE_FLAG","dataType":"string"},{"name":"COMMS_NL_TRACKABLE_FLAG","dataType":"string"},{"name":"ASSET_CREATION_CODE","dataType":"string"},{"name":"ORDERABLE_ON_WEB_FLAG","dataType":"string"},{"name":"BACK_ORDERABLE_FLAG","dataType":"string"},{"name":"WEB_STATUS","dataType":"string"},{"name":"INDIVISIBLE_FLAG","dataType":"string"},{"name":"BULK_PICKED_FLAG","dataType":"string"},{"name":"LOT_STATUS_ENABLED","dataType":"string"},{"name":"SERIAL_STATUS_ENABLED","dataType":"string"},{"name":"DEFAULT_SERIAL_STATUS_ID","dataType":"double"},{"name":"LOT_SPLIT_ENABLED","dataType":"string"},{"name":"LOT_MERGE_ENABLED","dataType":"string"},{"name":"FINANCING_ALLOWED_FLAG","dataType":"string"},{"name":"EAM_ACT_NOTIFICATION_FLAG","dataType":"string"},{"name":"DUAL_UOM_CONTROL","dataType":"double"},{"name":"DUAL_UOM_DEVIATION_HIGH","dataType":"double"},{"name":"DUAL_UOM_DEVIATION_LOW","dataType":"double"},{"name":"CONTRACT_ITEM_TYPE_CODE","dataType":"string"},{"name":"SERV_REQ_ENABLED_CODE","dataType":"string"},{"name":"SERV_BILLING_ENABLED_FLAG","dataType":"string"},{"name":"PLANNED_INV_POINT_FLAG","dataType":"string"},{"name":"LOT_TRANSLATE_ENABLED","dataType":"string"},{"name":"DEFAULT_SO_SOURCE_TYPE","dataType":"string"},{"name":"CREATE_SUPPLY_FLAG","dataType":"string"},{"name":"LOT_SUBSTITUTION_ENABLED","dataType":"string"},{"name":"OBJECT_VERSION_NUMBER","dataType":"double"},{"name":"TRACKING_QUANTITY_IND","dataType":"string"},{"name":"ONT_PRICING_QTY_SOURCE","dataType":"string"},{"name":"VMI_MINIMUM_UNITS","dataType":"double"},{"name":"VMI_MAXIMUM_UNITS","dataType":"double"},{"name":"SO_AUTHORIZATION_FLAG","dataType":"double"},{"name":"CONSIGNED_FLAG","dataType":"double"},{"name":"ASN_AUTOEXPIRE_FLAG","dataType":"double"},{"name":"VMI_FORECAST_TYPE","dataType":"double"},{"name":"EXCLUDE_FROM_BUDGET_FLAG","dataType":"double"},{"name":"DRP_PLANNED_FLAG","dataType":"double"},{"name":"CRITICAL_COMPONENT_FLAG","dataType":"double"},{"name":"CONTINOUS_TRANSFER","dataType":"double"},{"name":"CONVERGENCE","dataType":"double"},{"name":"DIVERGENCE","dataType":"double"},{"name":"CHILD_LOT_FLAG","dataType":"string"},{"name":"CHILD_LOT_VALIDATION_FLAG","dataType":"string"},{"name":"COPY_LOT_ATTRIBUTE_FLAG","dataType":"string"},{"name":"GRADE_CONTROL_FLAG","dataType":"string"},{"name":"HAZARDOUS_MATERIAL_FLAG","dataType":"string"},{"name":"LOT_DIVISIBLE_FLAG","dataType":"string"},{"name":"PROCESS_COSTING_ENABLED_FLAG","dataType":"string"},{"name":"PROCESS_EXECUTION_ENABLED_FLAG","dataType":"string"},{"name":"PROCESS_QUALITY_ENABLED_FLAG","dataType":"string"},{"name":"PROCESS_SUPPLY_LOCATOR_ID","dataType":"double"},{"name":"PROCESS_SUPPLY_SUBINVENTORY","dataType":"string"},{"name":"RECIPE_ENABLED_FLAG","dataType":"string"},{"name":"PREPOSITION_POINT","dataType":"string"},{"name":"REPAIR_PROGRAM","dataType":"double"},{"name":"OUTSOURCED_ASSEMBLY","dataType":"double"},{"name":"GDSN_OUTBOUND_ENABLED_FLAG","dataType":"string"},{"name":"SERIAL_TAGGING_FLAG","dataType":"string"},{"name":"IB_ITEM_TRACKING_LEVEL","dataType":"string"},{"name":"MCC_CONTROL_CODE","dataType":"double"},{"name":"START_DATE_ACTIVE","dataType":"dateTime"},{"name":"END_DATE_ACTIVE","dataType":"dateTime"},{"name":"ORGANIZATION_CODE","dataType":"string"},{"name":"ITEM_DESCRIPTION","dataType":"string"},{"name":"USER_ITEM_TYPE","dataType":"string"},{"name":"BOM_ITEM_TYPE_DESCRIPTION","dataType":"string"},{"name":"COST_SOURCE_TYPE","dataType":"string"},{"name":"DEFAULT_BUYER","dataType":"string"},{"name":"ITEM_CATALOG_GROUP","dataType":"string"},{"name":"DEFAULT_RECV_SUBINVENTORY","dataType":"string"},{"name":"END_ASSEMBLY_PEGGING","dataType":"string"},{"name":"EFFECTIVITY_DATE","dataType":"dateTime"},{"name":"REVISION","dataType":"string"},{"name":"POWERBI_REFRESH_PARTITION","dataType":"dateTime"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-20T01:01:32.0791183+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/85a769ac-dace-4397-a0cf-9b0dcedd673b/XXREP_MTL_SYSTEM_ITEMS_V.csv?snapshot=2022-05-20T01%3A01%3A32.0493814Z"}]},{"$type":"LocalEntity","name":"RESOURCE_TRAN_LDP_TIMES","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"RESOURCE_TRAN_LDP_TIMES.csv"},"annotations":[{"name":"pbi:EntityTypeDisplayHint","value":"CalculatedEntity"}],"attributes":[{"name":"JOB_NUMBER","dataType":"string"},{"name":"WIP_JOB_DESCRIPTION","dataType":"string"},{"name":"WIPJOB_ORG_KEY_CODE","dataType":"string"},{"name":"WIPJOB_ORG_KEY_ID","dataType":"string"},{"name":"DISCRETE_JOB_FLAG","dataType":"string"},{"name":"JOB_TYPE","dataType":"string"},{"name":"RESOURCE_TRX_REFERENCE","dataType":"string"},{"name":"TRANSACTION_ID","dataType":"double"},{"name":"TRANSACTION_TYPE","dataType":"string"},{"name":"TRANSACTION_DATE","dataType":"dateTime"},{"name":"SOURCE_CODE","dataType":"string"},{"name":"OPERATION_SEQ_NUM","dataType":"double"},{"name":"RESOURCE_SEQ_NUM","dataType":"double"},{"name":"AUTOCHARGE_TYPE","dataType":"string"},{"name":"USAGE_RATE_OR_AMOUNT","dataType":"double"},{"name":"BASIS_TYPE","dataType":"string"},{"name":"TRANSACTION_QUANTITY","dataType":"double"},{"name":"TRANSACTION_UOM","dataType":"string"},{"name":"PRIMARY_QUANTITY","dataType":"double"},{"name":"PRIMARY_UOM","dataType":"string"},{"name":"ACTUAL_RESOURCE_RATE","dataType":"double"},{"name":"STANDARD_RESOURCE_RATE","dataType":"double"},{"name":"STANDARD_RATE_FLAG","dataType":"string"},{"name":"CURRENCY_CODE","dataType":"string"},{"name":"MOVE_PRIMARY_QUANTITY","dataType":"double"},{"name":"FM_OPERATION_SEQ_NUM","dataType":"double"},{"name":"TO_OPERATION_SEQ_NUM","dataType":"double"},{"name":"ORGANIZATION_ID","dataType":"double"},{"name":"WIP_ENTITY_ID","dataType":"double"},{"name":"LINE_ID","dataType":"double"},{"name":"PRIMARY_ITEM_ID","dataType":"double"},{"name":"DEPARTMENT_ID","dataType":"double"},{"name":"RESOURCE_ID","dataType":"double"},{"name":"ACTIVITY_ID","dataType":"double"},{"name":"REASON_ID","dataType":"double"},{"name":"MOVE_TRANSACTION_ID","dataType":"double"},{"name":"COMPLETION_TRANSACTION_ID","dataType":"double"},{"name":"PROJECT_ID","dataType":"double"},{"name":"TASK_ID","dataType":"double"},{"name":"SOURCE_LINE_ID","dataType":"double"},{"name":"CREATION_DATE","dataType":"dateTime"},{"name":"CREATED_BY","dataType":"double"},{"name":"LAST_UPDATE_DATE","dataType":"dateTime"},{"name":"LAST_UPDATED_BY","dataType":"double"},{"name":"PROJECT_NAME","dataType":"string"},{"name":"PROJECT_NUMBER","dataType":"string"},{"name":"DEPARTMENT_CODE","dataType":"string"},{"name":"RESOURCE_CODE","dataType":"string"},{"name":"COST_CODE_TYPE","dataType":"double"},{"name":"ALLOW_COSTS","dataType":"string"},{"name":"ALLOW_COSTS_FLAG","dataType":"double"},{"name":"COST_CODE_TYPE_NAME","dataType":"string"},{"name":"ITEM_NUMBER","dataType":"string"},{"name":"ITEM_DESCRIPTION","dataType":"string"},{"name":"ITEM_ORG_KEY_ID","dataType":"string"},{"name":"ITEM_ORG_KEY_CODE","dataType":"string"},{"name":"ACCT_PERIOD_ID","dataType":"double"},{"name":"PERIOD_NAME","dataType":"string"},{"name":"PERIOD_START_DATE","dataType":"dateTime"},{"name":"PERIOD_CLOSE_DATE","dataType":"dateTime"},{"name":"INVORG_CODE","dataType":"string"},{"name":"LOCAL_EXTRACT_DATE","dataType":"dateTime"},{"name":"EXTRACT_DATE","dataType":"dateTime"},{"name":"TIMEZONE","dataType":"string"},{"name":"LAST_UPDATED_BY_LOGIN","dataType":"string"},{"name":"TRANSACTION_DATE_ONLY","dataType":"date"},{"name":"TRANSACTION_QUANTITY[h]","dataType":"double"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-20T01:08:16.1952637+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/85a769ac-dace-4397-a0cf-9b0dcedd673b/RESOURCE_TRAN_LDP_TIMES.csv?snapshot=2022-05-20T01%3A08%3A16.1629641Z"}]},{"$type":"LocalEntity","name":"XXCOH_WIP_TRX_VIEW","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"XXCOH_WIP_TRX_VIEW.csv"},"attributes":[{"name":"ASOF_DATE","dataType":"date"},{"name":"ASOF_DATE_DISP","dataType":"dateTime"},{"name":"TRANSACTION_ID","dataType":"double"},{"name":"WIP_SUB_LEDGER_ID","dataType":"double"},{"name":"ORGANIZATION_CODE","dataType":"string"},{"name":"SET_OF_BOOKS","dataType":"string"},{"name":"TRX_TYPE","dataType":"string"},{"name":"TRX_DATE","dataType":"dateTime"},{"name":"ACCT_ENTITY","dataType":"string"},{"name":"ACCT_DEPT","dataType":"string"},{"name":"ACCT_NUMBER","dataType":"string"},{"name":"TRX_CURRENCY_CODE","dataType":"string"},{"name":"FUNC_CURRENCY_CODE","dataType":"string"},{"name":"ENTERED_DR","dataType":"double"},{"name":"ENTERED_CR","dataType":"double"},{"name":"ACCOUNTED_DR","dataType":"double"},{"name":"ACCOUNTED_CR","dataType":"double"},{"name":"ACCOUNTED_DR_USD","dataType":"double"},{"name":"ACCOUNTED_CR_USD","dataType":"double"},{"name":"GL_TRANSFER_STATUS","dataType":"string"},{"name":"WIP_JOB_NAME","dataType":"string"},{"name":"COST_ELEMENT_NAME","dataType":"string"},{"name":"PERIOD_NAME","dataType":"string"},{"name":"FISCAL_PERIOD","dataType":"double"},{"name":"FISCAL_QUARTER","dataType":"double"},{"name":"FISCAL_YEAR","dataType":"double"},{"name":"FISCAL_WEEK","dataType":"double"},{"name":"CREATED_BY","dataType":"string"},{"name":"ACCOUNTING_LINE_TYPE","dataType":"string"},{"name":"TRANSACTION_QUANTITY","dataType":"double"},{"name":"TRANSACTION_UOM","dataType":"string"},{"name":"PRIMARY_QUANTITY","dataType":"double"},{"name":"PRIMARY_UOM","dataType":"string"},{"name":"USD_RATE","dataType":"double"},{"name":"DEPARTMENT_CODE","dataType":"string"},{"name":"RESOURCE_CODE","dataType":"string"},{"name":"MAT_VAR_ENTITY","dataType":"string"},{"name":"MAT_VAR_DEPT","dataType":"string"},{"name":"MAT_VAR_ACCT","dataType":"string"},{"name":"WIP_ENTITY_ID","dataType":"double"},{"name":"ORGANIZATION_ID","dataType":"double"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"EMPLOYEE_ID","dataType":"double"},{"name":"RESOURCE_ID","dataType":"double"},{"name":"ROW_CREATION_DATE","dataType":"dateTime"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-20T01:06:32.7011675+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/85a769ac-dace-4397-a0cf-9b0dcedd673b/XXCOH_WIP_TRX_VIEW.csv?snapshot=2022-05-20T01%3A06%3A32.6589928Z"}]},{"$type":"LocalEntity","name":"XXCOH_MI_WIP_FIN_VIEW","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"XXCOH_MI_WIP_FIN_VIEW.csv"},"attributes":[{"name":"ASOF_DATE","dataType":"date"},{"name":"ASOF_DATE_DISP","dataType":"dateTime"},{"name":"DATA_SOURCE","dataType":"string"},{"name":"ITEM_NUMBER","dataType":"string"},{"name":"ITEM_DESCRIPTION","dataType":"string"},{"name":"OWNING_ORGANIZATION","dataType":"string"},{"name":"WIP_ENTITY_NAME","dataType":"string"},{"name":"ENTITY_DESCRIPTION","dataType":"string"},{"name":"ENTITY_TYPE","dataType":"string"},{"name":"LINE_CODE","dataType":"string"},{"name":"JOB_TYPE","dataType":"string"},{"name":"JOB_STATUS","dataType":"string"},{"name":"START_QUANTITY","dataType":"double"},{"name":"QUANTITY_COMPLETED","dataType":"double"},{"name":"QUANTITY_SCRAPPED","dataType":"double"},{"name":"QUANTITY_REMAINING","dataType":"double"},{"name":"SCHEDULED_START_DATE","dataType":"dateTime"},{"name":"SCHEDULED_COMPLETION_DATE","dataType":"dateTime"},{"name":"DATE_RELEASED","dataType":"dateTime"},{"name":"DATE_COMPLETED","dataType":"dateTime"},{"name":"DATE_CLOSED","dataType":"dateTime"},{"name":"DUE_DATE","dataType":"dateTime"},{"name":"DEMAND_CLASS","dataType":"string"},{"name":"CLASS_CODE","dataType":"string"},{"name":"BASE_CURRENCY","dataType":"string"},{"name":"SUBINVENTORY","dataType":"string"},{"name":"LOC_BIN","dataType":"string"},{"name":"LOT_NUMBER","dataType":"string"},{"name":"BOM_REVISION","dataType":"string"},{"name":"BOM_REVISION_DATE","dataType":"dateTime"},{"name":"ROUTING_REVISION","dataType":"string"},{"name":"ROUTING_REVISION_DATE","dataType":"dateTime"},{"name":"PLANNER_CODE","dataType":"string"},{"name":"END_ASSEMBLY_PEGGING","dataType":"string"},{"name":"PLANNING_MAKE_BUY_CODE","dataType":"string"},{"name":"BUYER","dataType":"string"},{"name":"PRIMARY_UOM_CODE","dataType":"string"},{"name":"MAX_MINMAX_QUANTITY","dataType":"double"},{"name":"MIN_MINMAX_QUANTITY","dataType":"double"},{"name":"MINIMUM_ORDER_QUANTITY","dataType":"double"},{"name":"FIXED_LOT_MULTIPLIER","dataType":"double"},{"name":"SCHEDULE_GROUP_NAME","dataType":"string"},{"name":"OVERCOMPLETION_TOLERANCE_TYPE","dataType":"double"},{"name":"OVERCOMPLETION_TOLERANCE_VALUE","dataType":"double"},{"name":"MATERIAL_ENTITY","dataType":"string"},{"name":"MATERIAL_DEPT","dataType":"string"},{"name":"MATERIAL_ACCT","dataType":"string"},{"name":"MATERIAL_OH_ENTITY","dataType":"string"},{"name":"MATERIAL_OH_DEPT","dataType":"string"},{"name":"MATERIAL_OH_ACCT","dataType":"string"},{"name":"RESOURCE_ENTITY","dataType":"string"},{"name":"RESOURCE_DEPT","dataType":"string"},{"name":"RESOURCE_ACCT","dataType":"string"},{"name":"OVERHEAD_ENTITY","dataType":"string"},{"name":"OVERHEAD_DEPT","dataType":"string"},{"name":"OVERHEAD_ACCT","dataType":"string"},{"name":"OS_PROCESS_ENTITY","dataType":"string"},{"name":"OS_PROCESS_DEPT","dataType":"string"},{"name":"OS_PROCESS_ACCT","dataType":"string"},{"name":"EXPENSE_ENTITY","dataType":"string"},{"name":"EXPENSE_DEPT","dataType":"string"},{"name":"EXPENSE_ACCT","dataType":"string"},{"name":"ACCT_ATTRIBUTE1","dataType":"string"},{"name":"ACCT_ATTRIBUTE2","dataType":"string"},{"name":"ACCT_ATTRIBUTE3","dataType":"string"},{"name":"ACCT_ATTRIBUTE4","dataType":"string"},{"name":"ACCT_CLASS_TYPE","dataType":"string"},{"name":"MAT_VAR_ENTITY","dataType":"string"},{"name":"MAT_VAR_DEPT","dataType":"string"},{"name":"MAT_VAR_ACCT","dataType":"string"},{"name":"RSC_VAR_ENTITY","dataType":"string"},{"name":"RSC_VAR_DEPT","dataType":"string"},{"name":"RSC_VAR_ACCT","dataType":"string"},{"name":"OH_VAR_ENTITY","dataType":"string"},{"name":"OH_VAR_DEPT","dataType":"string"},{"name":"OH_VAR_ACCT","dataType":"string"},{"name":"OS_PROC_VAR_ENTITY","dataType":"string"},{"name":"OS_PROC_VAR_DEPT","dataType":"string"},{"name":"OS_PROC_VAR_ACCT","dataType":"string"},{"name":"AGILE_LIFE_PHASE","dataType":"string"},{"name":"BOM_ITEM_TYPE","dataType":"string"},{"name":"BOM_ENABLED_FLAG","dataType":"string"},{"name":"BUILD_IN_WIP_FLAG","dataType":"string"},{"name":"COSTING_ENABLED_FLAG","dataType":"string"},{"name":"CREATE_SUPPLY_FLAG","dataType":"string"},{"name":"CUSTOMER_ORDER_ENABLED_FLAG","dataType":"string"},{"name":"CUSTOMER_ORDER_FLAG","dataType":"string"},{"name":"CYCLE_COUNT_ENABLED_FLAG","dataType":"string"},{"name":"DEFAULT_SO_SOURCE_TYPE","dataType":"string"},{"name":"INSPECTION_REQUIRED_FLAG","dataType":"string"},{"name":"INVENTORY_ASSET_FLAG","dataType":"string"},{"name":"INVENTORY_ITEM_FLAG","dataType":"string"},{"name":"MUST_USE_APPROVED_VENDOR_FLAG","dataType":"string"},{"name":"PURCHASING_ENABLED_FLAG","dataType":"string"},{"name":"PURCHASING_ITEM_FLAG","dataType":"string"},{"name":"ITEM_TYPE_CODE","dataType":"string"},{"name":"ITEM_CATALOG_GROUP","dataType":"string"},{"name":"ITEM_TYPE","dataType":"string"},{"name":"LATEST_ITEM_REVISION","dataType":"string"},{"name":"REVISION_EFFECTIVITY_DATE","dataType":"dateTime"},{"name":"FULL_LEAD_TIME","dataType":"double"},{"name":"TECHNICAL_BUSINESS_UNIT","dataType":"string"},{"name":"PRODUCT_FAMILY","dataType":"string"},{"name":"PRODUCT_LINE","dataType":"string"},{"name":"FORECAST_FIELD","dataType":"string"},{"name":"LEAD_TIME_CATEGORY","dataType":"string"},{"name":"COMMODITY","dataType":"string"},{"name":"PRIMARY_ORG","dataType":"string"},{"name":"ORG_TECHNICAL_BUSINESS_UNIT","dataType":"string"},{"name":"ORG_PRODUCT_FAMILY","dataType":"string"},{"name":"ORG_PRODUCT_LINE","dataType":"string"},{"name":"ORG_FORECAST_FIELD","dataType":"string"},{"name":"ITEM_CUSTOMER","dataType":"string"},{"name":"BCP_CODE","dataType":"string"},{"name":"ROYALTY","dataType":"string"},{"name":"PLANNING_GREEN_SUPPLY_STATUS","dataType":"string"},{"name":"PLANNING_ACTION","dataType":"string"},{"name":"PLANNING_FAMILY_UNIQUE","dataType":"string"},{"name":"SPC_ITEM_COST","dataType":"double"},{"name":"SPC_ITEM_ADD_BACK_COST","dataType":"double"},{"name":"SPC_MATERIAL_COST","dataType":"double"},{"name":"SPC_RESOURCE_COST","dataType":"double"},{"name":"SPC_MATERIAL_OVERHEAD_COST","dataType":"double"},{"name":"SPC_OVERHEAD_COST","dataType":"double"},{"name":"SPC_OUTSIDE_PROCESSING_COST","dataType":"double"},{"name":"SPC_TL_ITEM_COST","dataType":"double"},{"name":"SPC_TL_MATERIAL","dataType":"double"},{"name":"SPC_TL_RESOURCE","dataType":"double"},{"name":"SPC_TL_MATERIAL_OVERHEAD","dataType":"double"},{"name":"SPC_TL_OVERHEAD","dataType":"double"},{"name":"SPC_TL_OUTSIDE_PROCESSING","dataType":"double"},{"name":"SPC_SHRINKAGE_RATE","dataType":"double"},{"name":"LEGAL_ENTITY","dataType":"string"},{"name":"OPERATING_UNIT","dataType":"string"},{"name":"SET_OF_BOOKS","dataType":"string"},{"name":"ORG_LOCATION_CODE","dataType":"string"},{"name":"REGION_1","dataType":"string"},{"name":"TOWN_OR_CITY","dataType":"string"},{"name":"SITE","dataType":"string"},{"name":"REPORTING_TBU","dataType":"string"},{"name":"FISCAL_PERIOD","dataType":"double"},{"name":"FISCAL_QUARTER","dataType":"double"},{"name":"FISCAL_YEAR","dataType":"double"},{"name":"FISCAL_WEEK","dataType":"double"},{"name":"FISCAL_SYSDATE_GEN","dataType":"date"},{"name":"SCHE_CMPL_FISCAL_PERIOD","dataType":"double"},{"name":"SCHE_CMPL_FISCAL_QUARTER","dataType":"double"},{"name":"SCHE_CMPL_FISCAL_YEAR","dataType":"double"},{"name":"SCHE_CMPL_FISCAL_WEEK","dataType":"double"},{"name":"CUSTOMER_NAME","dataType":"string"},{"name":"ALTERNATE_CUSTOMER_NAME","dataType":"string"},{"name":"ORDER_NUMBER","dataType":"double"},{"name":"ORDER_LINE","dataType":"string"},{"name":"SALESPERSON","dataType":"string"},{"name":"AGREEMENT_NUMBER","dataType":"string"},{"name":"TL_RESOURCE_IN","dataType":"double"},{"name":"TL_OVERHEAD_IN","dataType":"double"},{"name":"TL_OUTSIDE_PROCESSING_IN","dataType":"double"},{"name":"PL_MATERIAL_IN","dataType":"double"},{"name":"PL_MATERIAL_OVERHEAD_IN","dataType":"double"},{"name":"PL_RESOURCE_IN","dataType":"double"},{"name":"PL_OVERHEAD_IN","dataType":"double"},{"name":"PL_OUTSIDE_PROCESSING_IN","dataType":"double"},{"name":"TL_MATERIAL_OUT","dataType":"double"},{"name":"TL_MATERIAL_OVERHEAD_OUT","dataType":"double"},{"name":"TL_RESOURCE_OUT","dataType":"double"},{"name":"TL_OVERHEAD_OUT","dataType":"double"},{"name":"TL_OUTSIDE_PROCESSING_OUT","dataType":"double"},{"name":"PL_MATERIAL_OUT","dataType":"double"},{"name":"PL_MATERIAL_OVERHEAD_OUT","dataType":"double"},{"name":"PL_RESOURCE_OUT","dataType":"double"},{"name":"PL_OVERHEAD_OUT","dataType":"double"},{"name":"PL_OUTSIDE_PROCESSING_OUT","dataType":"double"},{"name":"TL_MATERIAL_VAR","dataType":"double"},{"name":"TL_MATERIAL_OVERHEAD_VAR","dataType":"double"},{"name":"TL_RESOURCE_VAR","dataType":"double"},{"name":"TL_OVERHEAD_VAR","dataType":"double"},{"name":"TL_OUTSIDE_PROCESSING_VAR","dataType":"double"},{"name":"PL_MATERIAL_VAR","dataType":"double"},{"name":"PL_MATERIAL_OVERHEAD_VAR","dataType":"double"},{"name":"PL_RESOURCE_VAR","dataType":"double"},{"name":"PL_OVERHEAD_VAR","dataType":"double"},{"name":"PL_OUTSIDE_PROCESSING_VAR","dataType":"double"},{"name":"TL_SCRAP_IN","dataType":"double"},{"name":"TL_SCRAP_OUT","dataType":"double"},{"name":"TL_SCRAP_VAR","dataType":"double"},{"name":"MATERIAL_COSTS_INCURRED","dataType":"double"},{"name":"MATERIAL_OH_COSTS_INCURRED","dataType":"double"},{"name":"RESOURCE_COSTS_INCURRED","dataType":"double"},{"name":"OVERHEAD_COSTS_INCURRED","dataType":"double"},{"name":"OS_PROCESS_COSTS_INCURRED","dataType":"double"},{"name":"MATERIAL_COSTS_RELIEVED","dataType":"double"},{"name":"MATERIAL_OH_COSTS_RELIEVED","dataType":"double"},{"name":"RESOURCE_COSTS_RELIEVED","dataType":"double"},{"name":"OVERHEAD_COSTS_RELIEVED","dataType":"double"},{"name":"OS_PROCESS_COSTS_RELIEVED","dataType":"double"},{"name":"MATERIAL_VARIANCES_RELIEVED","dataType":"double"},{"name":"MATERIAL_OH_VARIANCES_RELIEVED","dataType":"double"},{"name":"RESOURCE_VARIANCES_RELIEVED","dataType":"double"},{"name":"OVERHEAD_VARIANCES_RELIEVED","dataType":"double"},{"name":"OS_PROCESS_VARIANCES_RELIEVED","dataType":"double"},{"name":"MATERIAL_NET_ACTIVITIES","dataType":"double"},{"name":"MATERIAL_OH_NET_ACTIVITIES","dataType":"double"},{"name":"RESOURCE_NET_ACTIVITIES","dataType":"double"},{"name":"OVERHEAD_NET_ACTIVITIES","dataType":"double"},{"name":"OS_PROCESS_NET_ACTIVITIES","dataType":"double"},{"name":"TOTAL_COSTS_INCURRED","dataType":"double"},{"name":"TOTAL_COSTS_RELIEVED","dataType":"double"},{"name":"TOTAL_VARIANCES_RELIEVED","dataType":"double"},{"name":"TOTAL_NET_ACTIVITIES","dataType":"double"},{"name":"USD_RATE","dataType":"double"},{"name":"TOTAL_COSTS_INCURRED_USD","dataType":"double"},{"name":"TOTAL_COSTS_RELIEVED_USD","dataType":"double"},{"name":"TOTAL_VARIANCES_RELIEVED_USD","dataType":"double"},{"name":"TOT_NET_ACTIVITIES_USD","dataType":"double"},{"name":"DATE_STARTED","dataType":"dateTime"},{"name":"WIP_ENTITY_ID","dataType":"double"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"ORGANIZATION_ID","dataType":"double"},{"name":"LOCATOR_ID","dataType":"double"},{"name":"ROUTING_REFERENCE_ID","dataType":"double"},{"name":"OPERATING_UNIT_ID","dataType":"double"},{"name":"LEGAL_ENTITY_ID","dataType":"double"},{"name":"OE_HEADER_ID","dataType":"double"},{"name":"OE_LINE_ID","dataType":"double"},{"name":"PROJECT_ID","dataType":"double"},{"name":"PROJECT_NAME","dataType":"string"},{"name":"PROJECT_NUMBER","dataType":"string"},{"name":"INCIDENT_NUMBER","dataType":"string"},{"name":"FIN_TBU","dataType":"string"},{"name":"FIN_PFC","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-20T01:02:03.6795385+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/85a769ac-dace-4397-a0cf-9b0dcedd673b/XXCOH_MI_WIP_FIN_VIEW.csv?snapshot=2022-05-20T01%3A02%3A03.6403763Z"}]},{"$type":"LocalEntity","name":"XXREP_WIP_DISCRETE_JOBS_V","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"XXREP_WIP_DISCRETE_JOBS_V.csv"},"attributes":[{"name":"ORGANIZATION_ID","dataType":"double"},{"name":"WIP_ENTITY_ID","dataType":"double"},{"name":"WIPJOB_ORG_KEY_CODE","dataType":"string"},{"name":"WIPJOB_ORG_KEY_ID","dataType":"string"},{"name":"LAST_UPDATE_DATE","dataType":"dateTime"},{"name":"LAST_UPDATED_BY","dataType":"double"},{"name":"CREATION_DATE","dataType":"dateTime"},{"name":"CREATED_BY","dataType":"double"},{"name":"DESCRIPTION","dataType":"string"},{"name":"STATUS_TYPE","dataType":"double"},{"name":"PRIMARY_ITEM_ID","dataType":"double"},{"name":"CLASS_CODE","dataType":"string"},{"name":"MATERIAL_ACCOUNT","dataType":"double"},{"name":"MATERIAL_OVERHEAD_ACCOUNT","dataType":"double"},{"name":"RESOURCE_ACCOUNT","dataType":"double"},{"name":"OUTSIDE_PROCESSING_ACCOUNT","dataType":"double"},{"name":"MATERIAL_VARIANCE_ACCOUNT","dataType":"double"},{"name":"RESOURCE_VARIANCE_ACCOUNT","dataType":"double"},{"name":"OUTSIDE_PROC_VARIANCE_ACCOUNT","dataType":"double"},{"name":"STD_COST_ADJUSTMENT_ACCOUNT","dataType":"double"},{"name":"OVERHEAD_ACCOUNT","dataType":"double"},{"name":"OVERHEAD_VARIANCE_ACCOUNT","dataType":"double"},{"name":"START_QUANTITY","dataType":"double"},{"name":"QUANTITY_REMAINING","dataType":"double"},{"name":"QUANTITY_COMPLETED","dataType":"double"},{"name":"QUANTITY_SCRAPPED","dataType":"double"},{"name":"NET_QUANTITY","dataType":"double"},{"name":"BOM_REFERENCE_ID","dataType":"double"},{"name":"ROUTING_REFERENCE_ID","dataType":"double"},{"name":"COMMON_BOM_SEQUENCE_ID","dataType":"double"},{"name":"COMMON_ROUTING_SEQUENCE_ID","dataType":"double"},{"name":"BOM_REVISION","dataType":"string"},{"name":"ROUTING_REVISION","dataType":"string"},{"name":"BOM_REVISION_DATE","dataType":"dateTime"},{"name":"ROUTING_REVISION_DATE","dataType":"dateTime"},{"name":"LOT_NUMBER","dataType":"string"},{"name":"ALTERNATE_BOM_DESIGNATOR","dataType":"string"},{"name":"ALTERNATE_ROUTING_DESIGNATOR","dataType":"string"},{"name":"COMPLETION_SUBINVENTORY","dataType":"string"},{"name":"COMPLETION_LOCATOR_ID","dataType":"double"},{"name":"SUB_LOCATOR_CONTROL","dataType":"double"},{"name":"SCHEDULE_GROUP_NAME","dataType":"string"},{"name":"SCHEDULE_GROUP_ID","dataType":"double"},{"name":"BUILD_SEQUENCE","dataType":"double"},{"name":"LINE_CODE","dataType":"string"},{"name":"LINE_ID","dataType":"double"},{"name":"PROJECT_ID","dataType":"double"},{"name":"TASK_ID","dataType":"double"},{"name":"END_ITEM_UNIT_NUMBER","dataType":"string"},{"name":"DEMAND_CLASS","dataType":"string"},{"name":"SCHEDULED_START_DATE","dataType":"dateTime"},{"name":"DATE_RELEASED","dataType":"dateTime"},{"name":"SCHEDULED_COMPLETION_DATE","dataType":"dateTime"},{"name":"DATE_COMPLETED","dataType":"dateTime"},{"name":"DATE_CLOSED","dataType":"dateTime"},{"name":"OVERCOMPLETION_TOLERANCE_VALUE","dataType":"double"},{"name":"KANBAN_CARD_ID","dataType":"double"},{"name":"KANBAN_CARD_NUMBER","dataType":"string"},{"name":"PO_CREATION_TIME","dataType":"double"},{"name":"PRIORITY","dataType":"double"},{"name":"DUE_DATE","dataType":"dateTime"},{"name":"EST_SCRAP_ACCOUNT","dataType":"double"},{"name":"EST_SCRAP_VAR_ACCOUNT","dataType":"double"},{"name":"ENTITY_TYPE","dataType":"double"},{"name":"DUE_DATE_PENALTY","dataType":"double"},{"name":"DUE_DATE_TOLERANCE","dataType":"double"},{"name":"COPRODUCTS_SUPPLY","dataType":"double"},{"name":"REQUESTED_START_DATE","dataType":"dateTime"},{"name":"SERIALIZATION_START_OP","dataType":"double"},{"name":"ACTUAL_START_DATE","dataType":"dateTime"},{"name":"EXPECTED_HOLD_RELEASE_DATE","dataType":"dateTime"},{"name":"INVORG_CODE","dataType":"string"},{"name":"ASSEMBLY_ITEM_NUMBER","dataType":"string"},{"name":"JOB_SOURCE","dataType":"string"},{"name":"JOB_STATUS_CODE","dataType":"double"},{"name":"JOB_STATUS","dataType":"string"},{"name":"WIP_SUPPLY_TYPE_CODE","dataType":"double"},{"name":"WIP_SUPPLY_TYPE","dataType":"string"},{"name":"JB_TYPE","dataType":"string"},{"name":"JOB_NUMBER","dataType":"string"},{"name":"JOB_DESCRIPTION","dataType":"string"},{"name":"FIRM_PLANNED_FLAG","dataType":"string"},{"name":"JOB_TYPE","dataType":"string"},{"name":"FIRST_UNIT_START_DATE","dataType":"dateTime"},{"name":"FIRST_UNIT_COMPLETION_DATE","dataType":"dateTime"},{"name":"LAST_UNIT_START_DATE","dataType":"dateTime"},{"name":"LAST_UNIT_COMPLETION_DATE","dataType":"dateTime"},{"name":"DATE_LAST_MOVED","dataType":"dateTime"},{"name":"PROJECT_NUMBER","dataType":"string"},{"name":"PROJECT_NAME","dataType":"string"},{"name":"SALES_ORDER_NO_DFF","dataType":"double"},{"name":"SALE_ORDER_LINE_NO_DFF","dataType":"double"},{"name":"SERVICE_REQUEST_DFF","dataType":"string"},{"name":"ASSEMBLY_SN_DFF","dataType":"string"},{"name":"CREATED_BY_LOGIN","dataType":"string"},{"name":"LAST_UPDATED_BY_LOGIN","dataType":"string"},{"name":"COMPLETION_LOCATOR","dataType":"string"},{"name":"LOCAL_EXTRACT_DATE","dataType":"dateTime"},{"name":"EXTRACT_DATE","dataType":"dateTime"},{"name":"DATA_UPDATE_DESC","dataType":"string"},{"name":"ITEM_NUMBER","dataType":"string"},{"name":"ITEM_DESCRIPTION","dataType":"string"},{"name":"ITEM_TYPE","dataType":"string"},{"name":"ITEM_ORG_KEY_ID","dataType":"string"},{"name":"ITEM_ORG_KEY_CODE","dataType":"string"},{"name":"PRODUCT_FAMILY","dataType":"string"},{"name":"FORECAST_FIELD","dataType":"string"},{"name":"PRODUCT_LINE","dataType":"string"},{"name":"TBU","dataType":"string"},{"name":"ORG_PRODUCT_FAMILY","dataType":"string"},{"name":"ORG_FORECAST_FIELD","dataType":"string"},{"name":"ORG_PRODUCT_LINE","dataType":"string"},{"name":"ORG_TBU","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-20T01:01:52.6694915+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/85a769ac-dace-4397-a0cf-9b0dcedd673b/XXREP_WIP_DISCRETE_JOBS_V.csv?snapshot=2022-05-20T01%3A01%3A52.6006690Z"}]}]}