{"name":"COHREP_SITE_PURCHASING_TRX1","description":"","version":"1.0","culture":"en-US","modifiedTime":"2020-10-31T03:52:21.6642102+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":true,"queriesMetadata":{"ORG":{"queryId":"39b1f7da-0847-46a7-a148-01fb8a10ac9d","queryName":"ORG"},"ASL_Document":{"queryId":"6c5a600c-a782-49ed-8da3-3817bf16814e","queryName":"ASL_Document","queryGroupId":"root","loadEnabled":true},"ASL_Attribute":{"queryId":"8d6699a0-5cc6-4e0f-8f30-75f21d002947","queryName":"ASL_Attribute","queryGroupId":"root","loadEnabled":true},"Purchase_Order":{"queryId":"28007281-9a95-45a3-af6f-c8359687ebff","queryName":"Purchase_Order","queryGroupId":"root","loadEnabled":true},"Blanket_Agreement":{"queryId":"a6d1d751-2a47-49de-a898-ef75eacac86e","queryName":"Blanket_Agreement","queryGroupId":"root","loadEnabled":true},"Quote":{"queryId":"d8430c6b-c38f-448b-b13d-a7521198c515","queryName":"Quote","queryGroupId":"root","loadEnabled":true}},"document":"section Section1;\r\nshared ORG = let\r\n  ORG = \"LDP\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type text]\r\nin\r\n  ORG;\r\nshared ASL_Document = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, \n  Query=\"\n  SELECT \n  SYSDATE EXTRACT_DATE, \n  PAD.ASL_ID, \n  MSI.INVENTORY_ITEM_ID, \n  MSI.SEGMENT1 ITEM_NUMBER, \n  PAD.VENDOR_ID, \n  PAD.VENDOR_SITE_ID, \n  PAD.DOCUMENT_HEADER_ID, \n  PAD.DOCUMENT_LINE_ID, \n  PAD.SEQUENCE_NUM, \n  PAD.DOCUMENT_TYPE_DSP, \n  PAD.DOCUMENT_NUM, \n  PAD.LINE_NUM, \n  PAD.DOCUMENT_STATUS_DSP, \n  PAD.USING_ORGANIZATION_ID, \n  PAD.USING_ORGANIZATION_CODE, \n  PAD.ASL_ID || '_' || PAD.USING_ORGANIZATION_ID ASL_KEY,\n  CASE WHEN PAD.USING_ORGANIZATION_ID > 0 then 'Local ASL' else 'Global ASL' end ASL_TYPE\nFROM \n  INV.MTL_SYSTEM_ITEMS_B MSI, \n  APPS.ORG_ORGANIZATION_DEFINITIONS OOD, \n  APPS.PO_ASL_DOCUMENTS_V PAD, \n  APPS.PO_VENDOR_SITES_ALL PVS \nWHERE \n  MSI.ORGANIZATION_ID = OOD.ORGANIZATION_ID \n  AND PAD.ITEM_ID = MSI.INVENTORY_ITEM_ID \n  AND PVS.VENDOR_SITE_ID = PAD.VENDOR_SITE_ID \n  AND PAD.VENDOR_ID = PVS.VENDOR_ID \n  AND PVS.ORG_ID = OOD.OPERATING_UNIT \n  AND PAD.ORG_ID = OOD.OPERATING_UNIT \n  AND OOD.ORGANIZATION_CODE = NVL(\n    PAD.USING_ORGANIZATION_CODE, OOD.ORGANIZATION_CODE\n  )\n  AND OOD.ORGANIZATION_CODE = '\"&ORG&\"' \n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"EXTRACT_DATE\", \"Extract Date\"}, {\"ITEM_NUMBER\", \"Item Number\"}, {\"SEQUENCE_NUM\", \"Sequence\"}, {\"DOCUMENT_TYPE_DSP\", \"Document Type\"}, {\"DOCUMENT_NUM\", \"Document Number\"}, {\"LINE_NUM\", \"Document Line Number\"}, {\"DOCUMENT_STATUS_DSP\", \"Document Status\"}, {\"USING_ORGANIZATION_CODE\", \"Using Organization Code\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared ASL_Attribute = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, \n  Query=\"\n  SELECT \n  SYSDATE Extract_Date, \n  PASL.ASL_ID, \n  MSI.INVENTORY_ITEM_ID, \n  MSI.SEGMENT1 ITEM_NUMBER, \n  (\n    SELECT \n      STATUS \n    FROM \n      PO.PO_ASL_STATUSES PAS \n    WHERE \n      PAS.STATUS_ID = PASL.ASL_STATUS_ID\n  ) ASL_STATUS, \n  PASL.VENDOR_ID, \n  PASL.VENDOR_SITE_ID, \n  PAA.RELEASE_GENERATION_METHOD_DSP, \n  PAA.CONSIGNED_FROM_SUPPLIER_FLAG, \n  PAA.MIN_ORDER_QTY, \n  PAA.PURCHASING_UOM, \n  PAA.PROCESSING_LEAD_TIME, \n  PAA.FIXED_LOT_MULTIPLE, \n  PAA.FIXED_ORDER_QUANTITY, \n  PAA.USING_ORGANIZATION_CODE, \n  PAA.SCHEDULER_NAME, \n  CASE WHEN PAA.USING_ORGANIZATION_ID > 0 Then 'Local ASL' else 'Global ASL' end ASL_TYPE,\n  PAA.ASL_ID || '_' || PAA.USING_ORGANIZATION_ID ASL_KEY, \n  case when (\n    select \n      SR.CATEGORY_CONCAT_SEGS \n    from \n      (\n        SELECT \n          MIC.INVENTORY_ITEM_ID, \n          MIC.CATEGORY_CONCAT_SEGS, \n          msso.VENDOR_ID, \n          msso.VENDOR_SITE_ID, \n          Decode(\n            msso.SOURCE_TYPE, 1, 'Transfer From', \n            2, 'Make At', 3, 'Buy From'\n          ) SR_SOURCE_TYPE, \n          msso.ALLOCATION_PERCENT \n        FROM \n          APPS.MTL_ITEM_CATEGORIES_V mic, \n          APPS.MRP_SR_ASSIGNMENTS_V msra, \n          MRP.MRP_SOURCING_RULES msr, \n          APPS.MRP_SR_RECEIPT_ORG_V msro, \n          APPS.MRP_SR_SOURCE_ORG_V msso, \n          INV.MTL_PARAMETERS MP \n        WHERE \n          1 = 1 \n          AND mic.CATEGORY_ID = msra.CATEGORY_ID \n          AND mic.ORGANIZATION_ID = msra.ORGANIZATION_ID \n          AND msra.SOURCING_RULE_ID = msr.SOURCING_RULE_ID \n          AND msr.SOURCING_RULE_ID = msro.SOURCING_RULE_ID \n          AND mp.organization_id = mic.organization_id \n          AND mp.organization_code = 'LDP' \n          AND MIC.CATEGORY_SET_NAME = 'Sourcing Rule' \n          AND msro.SR_RECEIPT_ID = msso.SR_RECEIPT_ID \n          AND sysdate < Nvl(msro.DISABLE_DATE, sysdate + 1) \n          AND Sysdate > Nvl(msro.EFFECTIVE_DATE, Sysdate - 1) \n          and msso.vendor_site_id is not null\n      ) sr \n    where \n      sr.vendor_site_id = paa.vendor_site_id \n      AND PAA.VENDOR_ID = SR.VENDOR_ID \n      AND sr.inventory_item_id = paa.item_id \n      AND SR.INVENTORY_ITEM_ID = PASL.ITEM_ID\n  ) is not null then 'Yes' else 'No' end ACTIVELY_SOURCED \nFROM \n  APPS.PO_APPROVED_SUPPLIER_LIST PASL, \n  APPS.PO_ASL_ATTRIBUTES_V PAA, \n  INV.MTL_SYSTEM_ITEMS_B MSI, \n  APPS.ORG_ORGANIZATION_DEFINITIONS OOD, \n  APPS.PO_VENDOR_SITES_ALL PVS \nWHERE \n  MSI.ORGANIZATION_ID = OOD.ORGANIZATION_ID \n  AND PAA.ASL_ID = PASL.ASL_ID \n  AND PAA.ITEM_ID = PASL.ITEM_ID \n  AND PAA.ITEM_ID = MSI.INVENTORY_ITEM_ID \n  AND PVS.ORG_ID = OOD.OPERATING_UNIT \n  AND PVS.VENDOR_SITE_ID = PAA.VENDOR_SITE_ID \n  AND PASL.ITEM_ID = MSI.INVENTORY_ITEM_ID\n  AND OOD.ORGANIZATION_CODE = '\"&ORG&\"' \n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"EXTRACT_DATE\", \"Extract Date\"}, {\"ACTIVELY_SOURCED\", \"Actively Sourced Flag\"}, {\"RELEASE_GENERATION_METHOD_DSP\", \"Release Method\"}, {\"CONSIGNED_FROM_SUPPLIER_FLAG\", \"Consigned From Supplier\"}, {\"MIN_ORDER_QTY\", \"Minimum Order Quantity\"}, {\"PURCHASING_UOM\", \"Purchasing UOM\"}, {\"PROCESSING_LEAD_TIME\", \"Processing Lead Time\"}, {\"FIXED_LOT_MULTIPLE\", \"Fixed Lot Multiplier\"}, {\"FIXED_ORDER_QUANTITY\", \"Fixed Order Quantity\"}, {\"USING_ORGANIZATION_CODE\", \"Using Organization Code\"}, {\"ITEM_NUMBER\", \"Item Number\"}, {\"ASL_STATUS\", \"ASL Status\"}, {\"SCHEDULER_NAME\", \"Scheduler Name\"}, {\"ASL_TYPE\", \"ASL Type\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Purchase_Order = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, \n  Query=\"\n  SELECT\n    sysdate                                                                                                      extract_date,\n    pra.po_release_id,\n    CASE\n        WHEN plla.approved_flag IN (\n            'Y',\n            'R'\n        ) THEN\n            CASE\n                WHEN (\n                    SELECT\n                        COUNT(1)\n                    FROM\n                        apps.po_action_history_v pah\n                    WHERE\n                            nvl(pra.po_release_id, pha.po_header_id) = pah.object_id\n                        AND pah.object_revision_num = 0\n                        AND pah.object_type_code IN (\n                            'PO',\n                            'RELEASE'\n                        )\n                        AND action_code = 'SUBMIT'\n                        AND nvl(pah.note, 'X') = 'AUTO RELEASE'\n                ) > 0 THEN\n                    'Automatic'\n                ELSE\n                    'Manual'\n            END\n    END po_approval_mode,\n    mp.organization_code,\n    pha.segment1                                                                                                 po_number,\n    nvl(pra.agent_id, pha.agent_id)                                                                              agent_id,\n    (\n        SELECT\n            agent_name\n        FROM\n            apps.po_agents_v poa\n        WHERE\n                poa.agent_id = nvl(pra.agent_id, pha.agent_id)\n            AND ROWNUM = 1\n    ) po_buyer,\n    pra.release_num,\n    nvl(pra.revision_num, pha.revision_num)                                                                      revision_num,\n    nvl(pra.creation_date, pha.creation_date)                                                                    creation_date,\n    CASE\n        WHEN nvl(pra.po_release_id, 0) > 0        THEN\n            (\n                SELECT\n                    approved_date\n                FROM\n                    apps.po_releases_archive_all praa\n                WHERE\n                        praa.po_release_id = pra.po_release_id\n                    AND praa.revision_num = 0\n            )\n        WHEN nvl(pra.po_release_id, 0) = 0        THEN\n            (\n                SELECT\n                    approved_date\n                FROM\n                    apps.po_headers_archive_all phaa\n                WHERE\n                        phaa.po_header_id = pha.po_header_id\n                    AND phaa.revision_num = 0\n            )\n    END po_key_original_approved_date,\n    nvl(pha.rate, 1)                                                                                             functional_rate,\n    CASE\n        WHEN pra.release_num > 0 THEN\n            pha.segment1\n            || '_'\n            || pra.release_num\n        ELSE\n            pha.segment1\n    END po_key,\n    pha.comments,\n    nvl(plla.approved_flag, 'N')                                                                                  approved_flag,\n    plla.approved_date,\n    CASE\n        WHEN pra.release_num > 0 THEN\n            pra.approved_date\n        ELSE\n            pha.approved_date\n    END po_key_approved_date,\n    pha.fob_lookup_code,\n    pha.type_lookup_code                                                                                         po_type,\n    (\n        SELECT\n            segment1\n        FROM\n            apps.mtl_categories mc\n        WHERE\n            mc.category_id = pla.category_id\n    ) purchasing_category,\n    plla.shipment_closed_date,\n    plla.closed_for_receiving_date,\n    plla.closed_for_invoice_date,\n    plla.closed_reason,\n    plla.closed_date,\n    plla.closed_code,\n    CASE\n        WHEN (\n            SELECT\n                COUNT(DISTINCT(pda.destination_subinventory))\n            FROM\n                po.po_distributions_all pda\n            WHERE\n                pda.line_location_id = plla.line_location_id\n        ) > 1 THEN\n            'Multiple'\n        ELSE\n            (\n                SELECT DISTINCT\n                    ( pda.destination_subinventory )\n                FROM\n                    po.po_distributions_all pda\n                WHERE\n                        pda.line_location_id = plla.line_location_id\n                    AND ROWNUM = 1\n            )\n    END destination_subinventory,\n    CASE\n        WHEN pra.po_release_id IS NOT NULL THEN\n            (\n                SELECT\n                    MAX(creation_date)\n                FROM\n                    apps.po_acceptances poa\n                WHERE\n                        poa.po_release_id = pra.po_release_id\n                    AND poa.accepted_flag = 'Y'\n            )\n        WHEN pra.po_release_id IS NULL THEN\n            (\n                SELECT\n                    MAX(creation_date)\n                FROM\n                    apps.po_acceptances poa\n                WHERE\n                        poa.po_header_id = pra.po_header_id\n                    AND poa.accepted_flag = 'Y'\n            )\n    END last_po_acceptance_date,\n    (\n        SELECT\n            plt.line_type\n        FROM\n            apps.po_line_types_v plt\n        WHERE\n            plt.line_type_id = pla.line_type_id\n    ) line_type,\n    nvl(pra.document_creation_method, pha.document_creation_method)                                              document_creation_method,\n    decode(nvl(pra.consigned_consumption_flag, pha.consigned_consumption_flag), 'Y', 'Yes', 'No')              consumption_advice_flag,\n    pha.rate_date,\n    pla.po_line_id,\n    pla.line_num,\n    (\n        SELECT\n            segment1\n        FROM\n            inv.mtl_system_items_b msi\n        WHERE\n                msi.organization_id = mp.organization_id\n            AND msi.inventory_item_id = pla.item_id\n    ) po_item_number,\n    pla.item_revision                                                                                            po_item_revision,\n    pla.item_description                                                                                         po_item_description,\n    pla.unit_meas_lookup_code                                                                                    po_unit_of_measure,\n    (\n        SELECT\n            planner_code\n        FROM\n            inv.mtl_system_items_b msi\n        WHERE\n                msi.organization_id = mp.organization_id\n            AND msi.inventory_item_id = pla.item_id\n    ) planner_code,\n    pha.currency_code,\n    pla.unit_price,\n    plla.line_location_id,\n    plla.shipment_num,\n    plla.need_by_date,\n    plla.promised_date,\n    plla.quantity,\n    plla.quantity_received,\n    plla.quantity_cancelled,\n    plla.quantity_billed,\n    plla.quantity_accepted,\n    (\n        SELECT\n            SUM(pda.quantity_delivered)\n        FROM\n            po.po_distributions_all pda\n        WHERE\n            pda.line_location_id = plla.line_location_id\n    ) quantity_delivered,\n    CASE\n        WHEN plla.po_release_id > 0 THEN\n            (\n                SELECT\n                    type_lookup_code\n                FROM\n                    po.po_headers_all pha\n                WHERE\n                        pha.po_header_id = plla.po_header_id\n                    AND ROWNUM = 1\n            )\n        ELSE\n            (\n                SELECT\n                    type_lookup_code\n                FROM\n                    po.po_headers_all pha\n                WHERE\n                        pha.po_header_id = pla.from_header_id\n                    AND ROWNUM = 1\n            )\n    END document_reference_type,\n    CASE\n        WHEN plla.po_release_id > 0 THEN\n            (\n                SELECT\n                    pha.segment1\n                FROM\n                    po.po_headers_all pha\n                WHERE\n                        pha.po_header_id = plla.po_header_id\n                    AND ROWNUM = 1\n            )\n        ELSE\n            (\n                SELECT\n                    pha.segment1\n                FROM\n                    po.po_headers_all pha\n                WHERE\n                        pha.po_header_id = pla.from_header_id\n                    AND ROWNUM = 1\n            )\n    END document_reference_number,\n    pha.vendor_id,\n    pha.vendor_site_id,\n    decode(plla.consigned_flag, 'Y', 'Yes', 'No')                                                                consigned_flag,\n    (\n        SELECT\n            meaning\n        FROM\n            applsys.fnd_lookup_values    flv,\n            inv.mtl_system_items_b       msi\n        WHERE\n                flv.lookup_type = 'ITEM_TYPE'\n            AND flv.language = 'US'\n            AND flv.lookup_code = msi.item_type\n            AND msi.inventory_item_id = pla.item_id\n            AND msi.organization_id = mp.organization_id\n    ) item_type,\n    pla.attribute1                                                                                               ppv_apop_or_item_cost,\n    ( pla.attribute2 ) ppv_rate_percent,\n    nvl(pla.attribute3, 'N')                                                                                     ppv_approval_required,\n    pla.attribute7                                                                                               ppv_reason,\n    (\n        SELECT\n            pda.destination_type_code\n        FROM\n            po.po_distributions_all pda\n        WHERE\n                pda.line_location_id = plla.line_location_id\n            AND ROWNUM = 1\n    ) destination_type_code,\n    (\n        SELECT\n            MIN(pllaa.approved_date)\n        FROM\n            po.po_line_locations_archive_all pllaa\n        WHERE\n            pllaa.line_location_id = plla.line_location_id\n    ) first_approved_date,\n    (\n        SELECT\n            prha.approved_date\n        FROM\n            po.po_requisition_headers_all    prha,\n            po.po_requisition_lines_all      prla,\n            po.po_req_distributions_all      prda,\n            po.po_distributions_all          pda\n        WHERE\n                prla.requisition_line_id = prda.requisition_line_id\n            AND pda.line_location_id = plla.line_location_id\n            AND pda.req_distribution_id = prda.distribution_id\n            AND prla.requisition_header_id = prha.requisition_header_id\n            AND ROWNUM = 1\n    ) requisition_approved_date,\n    (\n        CASE\n            WHEN nvl(plla.approved_flag, 'N') IN (\n                'Y',\n                'R'\n            )\n                 AND plla.closed_code NOT IN (\n                'CLOSED',\n                'CLOSED FOR RECEIVING',\n                'FINALLY CLOSED'\n            )\n                 AND nvl(plla.closed_date, trunc(sysdate) + 1) > trunc(sysdate)\n                 AND nvl(plla.cancel_date, trunc(sysdate) + 1) > trunc(sysdate)\n                 AND ( plla.quantity - nvl(plla.quantity_received, 0) - nvl(plla.quantity_cancelled, 0) ) > 0 THEN\n                'Yes'\n            ELSE\n                'No'\n        END\n    ) is_po_shipment_open,\n    nvl((\n        SELECT\n            CASE\n                WHEN prha.interface_source_code = 'INV'\n                     AND nvl(prla.kanban_card_id, 0) > 0 THEN\n                    'Kanban'\n                WHEN prha.interface_source_code = 'INV'\n                     AND nvl(prla.kanban_card_id, 0) = 0 THEN\n                    'Min Max'\n                WHEN prha.interface_source_code = 'MSC'\n                     AND nvl(prla.kanban_card_id, 0) = 0 THEN\n                    'MRP'\n                WHEN prha.interface_source_code IS NULL\n                     AND prha.approved_date IS NOT NULL\n                     AND prla.item_id IS NULL THEN\n                    'iProcurement'\n                WHEN prha.interface_source_code IS NULL\n                     AND prha.approved_date IS NOT NULL THEN\n                    'Manual'\n                WHEN prha.interface_source_code IS NOT NULL THEN\n                    prha.interface_source_code\n                ELSE\n                    'Manual'\n            END\n        FROM\n            po.po_requisition_headers_all    prha, po.po_requisition_lines_all      prla, po.po_req_distributions_all      prda, po.po_distributions_all          pda\n        WHERE\n                prla.requisition_line_id = prda.requisition_line_id\n            AND pda.line_location_id = plla.line_location_id\n            AND pda.req_distribution_id = prda.distribution_id\n            AND prla.requisition_header_id = prha.requisition_header_id\n            AND ROWNUM = 1\n    ), 'Manual') po_source,\n    (\n        SELECT\n            MIN(spd.sugg_dock_date)\n        FROM\n            xxcoh.xxcoh_sup_peg_datamart spd\n        WHERE\n                spd.organization_id = plla.ship_to_organization_id\n            AND spd.po_line_location_id = plla.line_location_id\n            AND pla.item_id = spd.sup_item_id\n            AND spd.plnorg_id = plla.ship_to_organization_id\n    ) sugg_earliest_dock_date\nFROM\n    po.po_headers_all                    pha,\n    po.po_releases_all                   pra,\n    po.po_line_locations_all             plla,\n    po.po_lines_all                      pla,\n    apps.org_organization_definitions    mp\nWHERE\n        plla.po_header_id = pha.po_header_id\n    AND plla.po_release_id = pra.po_release_id (+)\n    AND plla.ship_to_organization_id = mp.organization_id\n    AND pla.po_header_id = pha.po_header_id\n    AND pla.po_line_id = plla.po_line_id\n    AND pha.org_id = mp.operating_unit\n    AND pha.type_lookup_code IN (\n        'STANDARD',\n        'BLANKET'\n    )\n    AND mp.operating_unit = (\n        SELECT\n            operating_unit\n        FROM\n            apps.org_organization_definitions ood2\n        WHERE\n            ood2.organization_code = '\"&ORG&\"'\n    )\n    AND EXISTS (\n        SELECT\n            1\n        FROM\n            po.po_distributions_all pda\n        WHERE\n            pda.line_location_id = plla.line_location_id\n    )\n\"\n, CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"PO_NUMBER\", \"PO Number\"}, {\"PURCHASING_CATEGORY\", \"Purchasing Category\"}, {\"RELEASE_NUM\", \"Release Number\"}, {\"REVISION_NUM\", \"Revision Number\"}, {\"PO_APPROVAL_MODE\", \"Approval Mode\"}, {\"PO_KEY\", \"PO Key\"}, {\"PO_BUYER\", \"PO Buyer\"}, {\"PLANNER_CODE\", \"Planner Code\"}, {\"ITEM_TYPE\", \"Item Type\"}, {\"PO_TYPE\", \"PO Type\"}, {\"COMMENTS\", \"Comments\"}, {\"APPROVED_FLAG\", \"Approved Flag\"}, {\"FOB_LOOKUP_CODE\", \"FOB\"}, {\"EXTRACT_DATE\", \"Extract Date\"}, {\"ORGANIZATION_CODE\", \"Organization Code\"}, {\"DOCUMENT_CREATION_METHOD\", \"Creation Method\"}, {\"LINE_NUM\", \"Line Number\"}, {\"PO_ITEM_NUMBER\", \"PO Item Number\"}, {\"PO_ITEM_REVISION\", \"PO Item Revision\"}, {\"PO_ITEM_DESCRIPTION\", \"PO Item Description\"}, {\"CURRENCY_CODE\", \"Currency Code\"}, {\"UNIT_PRICE\", \"Unit Price\"}, {\"SHIPMENT_NUM\", \"Shipment Number\"}, {\"CLOSED_CODE\", \"Shipment Closed Code\"}, {\"NEED_BY_DATE\", \"Need By Date\"}, {\"PROMISED_DATE\", \"Promised Date\"}, {\"QUANTITY\", \"Shipment Quantity\"}, {\"QUANTITY_RECEIVED\", \"Quantity Received\"}, {\"QUANTITY_CANCELLED\", \"Quantity Cancelled\"}, {\"QUANTITY_ACCEPTED\", \"Quantity Accepted\"}, {\"QUANTITY_BILLED\", \"Quantity Billed\"}, {\"QUANTITY_DELIVERED\", \"Quantity Delivered\"}, {\"PPV_APOP_OR_ITEM_COST\", \"APOP or Item Cost\"}, {\"PPV_RATE_PERCENT\", \"PPV Rate Percent\"}, {\"PPV_APPROVAL_REQUIRED\", \"PPV Approval Required Flag\"}, {\"PPV_REASON\", \"PPV Reason\"}, {\"DESTINATION_TYPE_CODE\", \"Destination Type Code\"}, {\"IS_PO_SHIPMENT_OPEN\", \"Shipment Open Flag\"}, {\"LINE_TYPE\", \"Line Type\"}, {\"DOCUMENT_REFERENCE_NUMBER\", \"Document Reference Number\"}, {\"DOCUMENT_REFERENCE_TYPE\", \"Document Reference Type\"}, {\"CONSIGNED_FLAG\", \"Consigned Flag\"}, {\"PO_SOURCE\", \"PO Source\"}, {\"FIRST_APPROVED_DATE\", \"First Approved Date\"}, {\"REQUISITION_APPROVED_DATE\", \"Requisition Approved Date\"}, {\"CREATION_DATE\", \"Creation Date\"}, {\"RATE_DATE\", \"Rate Date\"}, {\"LAST_PO_ACCEPTANCE_DATE\", \"Last Acceptance Date\"}, {\"FUNCTIONAL_RATE\", \"Functional Rate\"}, {\"CLOSED_DATE\", \"Closed Date\"}, {\"CLOSED_FOR_INVOICE_DATE\", \"Closed for Invoice Date\"}, {\"CLOSED_FOR_RECEIVING_DATE\", \"Closed for Receiving Date\"}, {\"CLOSED_REASON\", \"Closed Reason\"}, {\"SHIPMENT_CLOSED_DATE\", \"Shipment Closed Date\"}, {\"CONSUMPTION_ADVICE_FLAG\", \"Consumption Advice Flag\"}, {\"PO_UNIT_OF_MEASURE\", \"Unit of Measure\"}, {\"DESTINATION_SUBINVENTORY\", \"Destination Subinventory\"}, {\"APPROVED_DATE\", \"Approved Date\"}, {\"PO_KEY_APPROVED_DATE\", \"PO Key Approved Date\"}, {\"PO_KEY_ORIGINAL_APPROVED_DATE\", \"PO Key Original Approved Date\"}, {\"SUGG_EARLIEST_DOCK_DATE\", \"Suggested Dock Date\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Blanket_Agreement = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, \n  Query=\"\n  SELECT\n    sysdate                                                                             extract_date,\n    pha.segment1,\n    pha.revision_num,\n    pla.line_num,\n    pha.vendor_id,\n    pha.vendor_site_id,\n    pha.agent_id,\n    poa.agent_name                                                                      buyer_name,\n    nvl(decode(pha.global_agreement_flag, 'Y', 'Yes', 'No'), 'No')                      global_agreement_flag,\n    (\n        SELECT\n            MAX(mir.revision)\n        FROM\n            apps.mtl_item_revisions_b mir\n        WHERE\n                mir.organization_id = msi.organization_id\n            AND mir.inventory_item_id = msi.inventory_item_id\n            AND implementation_date = (\n                SELECT\n                    MAX(implementation_date)\n                FROM\n                    apps.mtl_item_revisions_b mir\n                WHERE\n                        mir.organization_id = msi.organization_id\n                    AND mir.inventory_item_id = msi.inventory_item_id\n            )\n    ) item_revision,\n    (\n        SELECT\n            hrl.location_code\n        FROM\n            apps.hr_locations hrl\n        WHERE\n            hrl.location_id = pha.ship_to_location_id\n    ) ship_to_location,\n    pha.currency_code,\n    nvl(pha.rate_date, pha.creation_date)                                               rate_date,\n    pha.rate_type,\n    pha.start_date,\n    trunc(least(nvl(pla.expiration_date, '01-JAN-2099'), pha.end_date))                 blanket_expiration_date,\n    pha.po_header_id,\n    pla.item_revision                                                                   blanket_item_revision,\n    pov.vendor_name,\n    pvs.vendor_site_code,\n    pla.item_description,\n    pla.unit_meas_lookup_code                                                           blanket_unit_of_measure,\n    (\n        SELECT\n            MIN(phaa.approved_date)\n        FROM\n            apps.po_headers_archive_all phaa\n        WHERE\n                phaa.po_header_id = pha.po_header_id\n            AND phaa.revision_num = 0\n    ) blanket_first_approved_date,\n    (\n        SELECT\n            MIN(phaa.approved_date)\n        FROM\n            apps.po_headers_archive_all    phaa,\n            apps.po_lines_archive_all      plaa\n        WHERE\n                phaa.po_header_id = pha.po_header_id\n            AND plaa.po_header_id = phaa.po_header_id\n            AND plaa.po_line_id = pla.po_line_id\n            AND plaa.revision_num = pha.revision_num\n    ) first_approved_date,\n    (\n        CASE\n            WHEN nvl(pha.closed_code, 'OPEN') = 'OPEN'\n                 AND nvl(pla.closed_code, 'OPEN') = 'OPEN'\n                 AND pla.cancel_date IS NULL\n                 AND pla.closed_date IS NULL THEN\n                'Yes'\n            ELSE\n                'No'\n        END\n    ) blanket_open_flag,\n    nvl((\n        SELECT\n            gbpa_release\n        FROM\n            (\n                SELECT\n                    pla.from_line_id                                                 gbpar_line_id, pla.from_header_id                                               gbpar_header_id, SUM(plla.quantity - nvl(plla.quantity_cancelled,\n                    0))             gbpa_release\n                FROM\n                    po.po_line_locations_all    plla, po.po_lines_all             pla\n                WHERE\n                        plla.po_line_id = pla.po_line_id\n                    AND nvl(plla.consigned_flag, 'N') = 'N'\n                    AND plla.approved_flag IN(\n                        'Y', 'R'\n                    )\n                    AND pla.from_header_id IS NOT NULL\n                    AND pla.from_line_id IS NOT NULL\n                GROUP BY\n                    pla.item_id, pla.from_line_id, pla.from_header_id\n            ) gbpar\n        WHERE\n                gbpar.gbpar_line_id = pla.po_line_id\n            AND gbpar.gbpar_header_id = pha.po_header_id\n    ), 0) + nvl((\n        SELECT\n            bpa_release\n        FROM\n            (\n                SELECT\n                    plla.org_id, pla.po_header_id, pla.po_line_id, SUM(plla.quantity - nvl(plla.quantity_cancelled, 0)) bpa_release\n                FROM\n                    po.po_line_locations_all    plla, po.po_lines_all             pla\n                WHERE\n                        plla.po_line_id = pla.po_line_id\n                    AND nvl(plla.consigned_flag, 'N') = 'N'\n                    AND plla.po_release_id IS NOT NULL\n                GROUP BY\n                    plla.org_id, pla.po_header_id, pla.po_line_id\n            ) bpar\n        WHERE\n                bpar.po_line_id = pla.po_line_id\n            AND bpar.po_header_id = pha.po_header_id\n            AND bpar.org_id = pha.org_id\n    ), 0) quantity_released,\n    CASE\n        WHEN pla.quantity_committed IS NULL THEN\n            nvl(pla.committed_amount, pha.amount_limit) / pla.unit_price\n        ELSE\n            pla.quantity_committed\n    END quantity_committed,\n    pha.creation_date,\n    pla.unit_price,\n    msi.segment1                                                                        item_number,\n    msi.inventory_item_id,\n    pha.approved_date,\n    nvl(pha.authorization_status, 'INCOMPLETE')                                         blanket_authorization_status,\n    pha.last_update_date,\n    pla.po_line_id,\n    msi.planner_code,\n    pha.amount_limit,\n    pla.cancel_date,\n    pla.closed_date,\n    CASE\n        WHEN nvl(pla.expiration_date, pha.end_date) > trunc(sysdate) THEN\n            trunc(sysdate) - trunc(pha.start_date)\n        ELSE\n            nvl(pla.expiration_date, pha.end_date) - trunc(pha.start_date)\n    END blanket_age_days,\n    (\n        CASE\n            WHEN trunc(nvl(nvl(pla.expiration_date, pha.end_date), sysdate + 1)) < trunc(sysdate) THEN\n                'Yes'\n            ELSE\n                'No'\n        END\n    ) blanket_expired_flag,\n    (\n        SELECT\n            asld.asl_id\n            || '_'\n            || asld.using_organization_id\n        FROM\n            apps.po_asl_documents_v asld\n        WHERE\n                asld.document_line_id = pla.po_line_id\n            AND asld.vendor_site_id = pha.vendor_site_id\n            AND asld.item_id = pla.item_id\n            AND ROWNUM = 1\n    ) asl_key,\n    CASE\n        WHEN (\n            SELECT\n                asld.asl_id\n                || '_'\n                || asld.using_organization_id\n            FROM\n                apps.po_asl_documents_v asld\n            WHERE\n                    asld.document_line_id = pla.po_line_id\n                AND asld.vendor_site_id = pha.vendor_site_id\n                AND asld.item_id = pla.item_id\n                AND ROWNUM = 1\n        ) IS NOT NULL THEN\n            'Yes'\n        ELSE\n            'No'\n    END used_in_asl_flag,\n    nvl(pha.rate, 1)                                                                    functional_rate\nFROM\n    apps.org_organization_definitions    ood,\n    appsread.po_headers_all              pha,\n    po.po_lines_all                      pla,\n    apps.po_vendors                      pov,\n    apps.po_vendor_sites_all             pvs,\n    apps.po_agents_v                     poa,\n    inv.mtl_system_items_b               msi\nWHERE\n        1 = 1\n    AND ood.operating_unit = pha.org_id\n    AND pha.po_header_id = pla.po_header_id\n    AND pha.vendor_id = pov.vendor_id\n    AND pha.vendor_site_id = pvs.vendor_site_id\n    AND poa.agent_id = pha.agent_id\n    AND pha.type_lookup_code = 'BLANKET'\n    AND pla.item_id = msi.inventory_item_id\n    AND OOD.ORGANIZATION_CODE = '\"&ORG&\"' \n    AND pha.authorization_status IN (\n        'APPROVED',\n        'IN PROCESS',\n        'PRE-APPROVED',\n        'REQUIRES REAPPROVAL'\n    )\n    AND msi.organization_id = ood.organization_id \"\n, CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"SEGMENT1\", \"Blanket Number\"}, {\"REVISION_NUM\", \"Revision Number\"}, {\"BLANKET_OPEN_FLAG\", \"Open Flag\"}, {\"EXTRACT_DATE\", \"Extract Date\"}, {\"LINE_NUM\", \"Line Number\"}, {\"CREATION_DATE\", \"Creation Date\"}, {\"START_DATE\", \"Start Date\"}, {\"BLANKET_EXPIRATION_DATE\", \"Expiration Date\"}, {\"BUYER_NAME\", \"Blanket Buyer Name\"}, {\"ITEM_REVISION\", \"Item Revision\"}, {\"GLOBAL_AGREEMENT_FLAG\", \"Global Blanket Flag\"}, {\"CURRENCY_CODE\", \"Currency Code\"}, {\"RATE_DATE\", \"Rate Date\"}, {\"BLANKET_ITEM_REVISION\", \"Blanket Item Revision\"}, {\"VENDOR_NAME\", \"Vendor Name\"}, {\"VENDOR_SITE_CODE\", \"Vendor Site\"}, {\"ITEM_DESCRIPTION\", \"Item Description\"}, {\"QUANTITY_COMMITTED\", \"Committed Quantity\"}, {\"UNIT_PRICE\", \"Unit Price\"}, {\"ITEM_NUMBER\", \"Item Number\"}, {\"APPROVED_DATE\", \"Approved Date\"}, {\"FIRST_APPROVED_DATE\", \"First Approved Date\"}, {\"QUANTITY_RELEASED\", \"Released Quantity\"}, {\"AMOUNT_LIMIT\", \"Amount Limit\"}, {\"PLANNER_CODE\", \"Planner Code\"}, {\"BLANKET_AGE_DAYS\", \"Blanket Age Days\"}, {\"BLANKET_EXPIRED_FLAG\", \"Expired Flag\"}, {\"SHIP_TO_LOCATION\", \"Ship To Location\"}, {\"USED_IN_ASL_FLAG\", \"Used in ASL Flag\"}, {\"BLANKET_AUTHORIZATION_STATUS\", \"Authorization Status\"}, {\"RATE_TYPE\", \"Rate Type\"}, {\"LAST_UPDATE_DATE\", \"Last Update Date\"}, {\"CANCEL_DATE\", \"Cancel Date\"}, {\"CLOSED_DATE\", \"Closed Date\"}, {\"BLANKET_UNIT_OF_MEASURE\", \"Unit of Measure\"}, {\"BLANKET_FIRST_APPROVED_DATE\", \"Blanket First Approved Date\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Quote = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, \n  Query=\"\n  SELECT\n   sysdate extract_date,\n   ood.organization_code,\n   pha.segment1 quote_number,\n   pha.quote_type_lookup_code,\n   pha.quotation_class_code,\n   pha.quote_vendor_quote_number,\n   pha.start_date quote_start_date,\n   trunc(least(nvl(plla.end_date, '01-JAN-2099'), nvl(pla.expiration_date, '01-JAN-2099'), pha.end_date)) quote_expiration_date,\n   pha.vendor_id,\n   pha.vendor_site_id,\n   pha.reply_date,\n   pha.quote_warning_delay,\n   pla.po_line_id,\n   plla.line_location_id,\n   decode(pha.status_lookup_code, 'A', 'Active', 'C', 'Closed', 'I', 'In Process', 'P', 'Printed') quote_status,\n   (\n        SELECT\n            MAX(mir.revision)\n        FROM\n            apps.mtl_item_revisions_b mir\n        WHERE\n                mir.organization_id = msi.organization_id\n            AND mir.inventory_item_id = msi.inventory_item_id\n            AND IMPLEMENTATION_DATE = (\n                SELECT\n                    MAX(IMPLEMENTATION_DATE)\n                FROM\n                    apps.mtl_item_revisions_b mir\n                WHERE\n                        mir.organization_id = msi.organization_id\n                    AND mir.inventory_item_id = msi.inventory_item_id\n            )\n    ) item_revision,\n   CASE\n      WHEN\n         pha.status_lookup_code = 'A' \n         AND trunc(least(nvl(plla.end_date, '01-JAN-2099'), nvl(pla.expiration_date, '01-JAN-2099'), pha.end_date)) > sysdate \n         AND pha.start_date < sysdate \n      THEN\n         'Yes' \n      ELSE\n         'No' \n   END\n   quote_active \n   , pla.line_num \n   , poa.agent_name buyer_name , \n   (\n      SELECT\n         hrl.location_code \n      FROM\n         apps.hr_locations hrl \n      WHERE\n         hrl.location_id = pha.ship_to_location_id\n   )\n   ship_to_location,\n   pha.currency_code,\n   pla.item_revision quote_item_revision,\n   pla.unit_meas_lookup_code quote_unit_of_measure,\n   pov.vendor_name,\n   pvs.vendor_site_code,\n   msi.segment1 item_number,\n   pla.item_description,\n   pha.creation_date,\n      msi.inventory_item_id,\n      msi.planner_code,\n      (\n         SELECT\n            asld.asl_id || '_' || asld.using_organization_id \n         FROM\n            apps.po_asl_documents_v asld \n         WHERE\n            asld.document_line_id = pla.po_line_id \n            AND asld.vendor_site_id = pha.vendor_site_id \n            AND asld.item_id = pla.item_id \n            AND rownum = 1\n      )\n      asl_key,\n      Case when (\n         SELECT\n            asld.asl_id || '_' || asld.using_organization_id \n         FROM\n            apps.po_asl_documents_v asld \n         WHERE\n            asld.document_line_id = pla.po_line_id \n            AND asld.vendor_site_id = pha.vendor_site_id \n            AND asld.item_id = pla.item_id \n            AND rownum = 1\n      ) is not null then 'Yes' else 'No' end\n      USED_IN_ASL,\n      plla.quantity price_break_qty,\n      nvl(plla.price_override, pla.unit_price) price_break,\n      nvl(plla.price_discount, 0) / 100 price_break_discount \n   FROM\n      apps.org_organization_definitions ood,\n      appsread.po_headers_all pha,\n      po.po_lines_all pla,\n      po.po_line_locations_all plla,\n      apps.po_vendors pov,\n      apps.po_vendor_sites_all pvs,\n      apps.po_agents_v poa,\n      inv.mtl_system_items_b msi \n   WHERE\n      1 = 1 \n      AND ood.operating_unit = pha.org_id \n      AND pha.po_header_id = pla.po_header_id \n      AND pha.vendor_id = pov.vendor_id \n      AND pha.vendor_site_id = pvs.vendor_site_id \n      AND poa.agent_id = pha.agent_id \n      AND pha.type_lookup_code = 'QUOTATION' \n      AND pla.item_id = msi.inventory_item_id \n      AND ood.organization_code = '\"&ORG&\"' \n      AND msi.organization_id = ood.organization_id \n      AND pla.po_line_id = plla.po_line_id ( + )\n      \", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"EXTRACT_DATE\", \"Extract Date\"}, {\"ORGANIZATION_CODE\", \"Organization Code\"}, {\"ITEM_NUMBER\", \"Item Number\"}, {\"ITEM_REVISION\", \"Item Revision\"}, {\"QUOTE_NUMBER\", \"Quote Number\"}, {\"QUOTE_TYPE_LOOKUP_CODE\", \"Quote Type\"}, {\"QUOTE_VENDOR_QUOTE_NUMBER\", \"Supplier Quote Number\"}, {\"QUOTE_START_DATE\", \"Start Date\"}, {\"QUOTE_EXPIRATION_DATE\", \"Expiration Date\"}, {\"REPLY_DATE\", \"Supplier Reply Date\"}, {\"QUOTE_WARNING_DELAY\", \"Warning Delay\"}, {\"QUOTE_STATUS\", \"Quote Status\"}, {\"QUOTE_ACTIVE\", \"Active Flag\"}, {\"LINE_NUM\", \"Line Number\"}, {\"BUYER_NAME\", \"Quote Buyer\"}, {\"SHIP_TO_LOCATION\", \"Ship To Location\"}, {\"CURRENCY_CODE\", \"Currency Code\"}, {\"QUOTE_ITEM_REVISION\", \"Quote Item Revision\"}, {\"VENDOR_NAME\", \"Supplier Name\"}, {\"VENDOR_SITE_CODE\", \"Supplier Site Code\"}, {\"ITEM_DESCRIPTION\", \"Item Description\"}, {\"CREATION_DATE\", \"Creation Date\"}, {\"PLANNER_CODE\", \"Planner Code\"}, {\"PRICE_BREAK_QTY\", \"Break Quantity\"}, {\"PRICE_BREAK\", \"Price Break\"}, {\"PRICE_BREAK_DISCOUNT\", \"Price Discount\"}, {\"QUOTE_UNIT_OF_MEASURE\", \"Unit of Measure\"}, {\"USED_IN_ASL\", \"Used in ASL Flag\"}})\r\nin\r\n  #\"Renamed columns\";\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"ASL_Document","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"ASL_Document.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"ASL_ID","dataType":"double"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"Item Number","dataType":"string"},{"name":"VENDOR_ID","dataType":"double"},{"name":"VENDOR_SITE_ID","dataType":"double"},{"name":"DOCUMENT_HEADER_ID","dataType":"double"},{"name":"DOCUMENT_LINE_ID","dataType":"double"},{"name":"Sequence","dataType":"double"},{"name":"Document Type","dataType":"string"},{"name":"Document Number","dataType":"string"},{"name":"Document Line Number","dataType":"double"},{"name":"Document Status","dataType":"string"},{"name":"USING_ORGANIZATION_ID","dataType":"double"},{"name":"Using Organization Code","dataType":"string"},{"name":"ASL_KEY","dataType":"string"},{"name":"ASL_TYPE","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-05-20T05:30:10.4331478+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/7a172cae-58f9-41cb-8701-ccc36a28357f/ASL_Document.csv?snapshot=2022-05-20T05%3A30%3A10.4162767Z"}]},{"$type":"LocalEntity","name":"ASL_Attribute","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"ASL_Attribute.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"ASL_ID","dataType":"double"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"Item Number","dataType":"string"},{"name":"ASL Status","dataType":"string"},{"name":"VENDOR_ID","dataType":"double"},{"name":"VENDOR_SITE_ID","dataType":"double"},{"name":"Release Method","dataType":"string"},{"name":"Consigned From Supplier","dataType":"string"},{"name":"Minimum Order Quantity","dataType":"double"},{"name":"Purchasing UOM","dataType":"string"},{"name":"Processing Lead Time","dataType":"double"},{"name":"Fixed Lot Multiplier","dataType":"double"},{"name":"Fixed Order Quantity","dataType":"double"},{"name":"Using Organization Code","dataType":"string"},{"name":"Scheduler Name","dataType":"string"},{"name":"ASL Type","dataType":"string"},{"name":"ASL_KEY","dataType":"string"},{"name":"Actively Sourced Flag","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-05-20T05:32:28.8495463+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/7a172cae-58f9-41cb-8701-ccc36a28357f/ASL_Attribute.csv?snapshot=2022-05-20T05%3A32%3A28.8144791Z"}]},{"$type":"LocalEntity","name":"Purchase_Order","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Purchase_Order.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"PO_RELEASE_ID","dataType":"double"},{"name":"Approval Mode","dataType":"string"},{"name":"Organization Code","dataType":"string"},{"name":"PO Number","dataType":"string"},{"name":"AGENT_ID","dataType":"double"},{"name":"PO Buyer","dataType":"string"},{"name":"Release Number","dataType":"double"},{"name":"Revision Number","dataType":"double"},{"name":"Creation Date","dataType":"dateTime"},{"name":"PO Key Original Approved Date","dataType":"dateTime"},{"name":"Functional Rate","dataType":"double"},{"name":"PO Key","dataType":"string"},{"name":"Comments","dataType":"string"},{"name":"Approved Flag","dataType":"string"},{"name":"Approved Date","dataType":"dateTime"},{"name":"PO Key Approved Date","dataType":"dateTime"},{"name":"FOB","dataType":"string"},{"name":"PO Type","dataType":"string"},{"name":"Purchasing Category","dataType":"string"},{"name":"Shipment Closed Date","dataType":"dateTime"},{"name":"Closed for Receiving Date","dataType":"dateTime"},{"name":"Closed for Invoice Date","dataType":"dateTime"},{"name":"Closed Reason","dataType":"string"},{"name":"Closed Date","dataType":"dateTime"},{"name":"Shipment Closed Code","dataType":"string"},{"name":"Destination Subinventory","dataType":"string"},{"name":"Last Acceptance Date","dataType":"dateTime"},{"name":"Line Type","dataType":"string"},{"name":"Creation Method","dataType":"string"},{"name":"Consumption Advice Flag","dataType":"string"},{"name":"Rate Date","dataType":"dateTime"},{"name":"PO_LINE_ID","dataType":"double"},{"name":"Line Number","dataType":"double"},{"name":"PO Item Number","dataType":"string"},{"name":"PO Item Revision","dataType":"string"},{"name":"PO Item Description","dataType":"string"},{"name":"Unit of Measure","dataType":"string"},{"name":"Planner Code","dataType":"string"},{"name":"Currency Code","dataType":"string"},{"name":"Unit Price","dataType":"double"},{"name":"LINE_LOCATION_ID","dataType":"double"},{"name":"Shipment Number","dataType":"double"},{"name":"Need By Date","dataType":"dateTime"},{"name":"Promised Date","dataType":"dateTime"},{"name":"Shipment Quantity","dataType":"double"},{"name":"Quantity Received","dataType":"double"},{"name":"Quantity Cancelled","dataType":"double"},{"name":"Quantity Billed","dataType":"double"},{"name":"Quantity Accepted","dataType":"double"},{"name":"Quantity Delivered","dataType":"double"},{"name":"Document Reference Type","dataType":"string"},{"name":"Document Reference Number","dataType":"string"},{"name":"VENDOR_ID","dataType":"double"},{"name":"VENDOR_SITE_ID","dataType":"double"},{"name":"Consigned Flag","dataType":"string"},{"name":"Item Type","dataType":"string"},{"name":"APOP or Item Cost","dataType":"string"},{"name":"PPV Rate Percent","dataType":"string"},{"name":"PPV Approval Required Flag","dataType":"string"},{"name":"PPV Reason","dataType":"string"},{"name":"Destination Type Code","dataType":"string"},{"name":"First Approved Date","dataType":"dateTime"},{"name":"Requisition Approved Date","dataType":"dateTime"},{"name":"Shipment Open Flag","dataType":"string"},{"name":"PO Source","dataType":"string"},{"name":"Suggested Dock Date","dataType":"dateTime"}],"partitions":[{"name":"Part001","refreshTime":"2022-05-20T05:36:44.4449835+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/7a172cae-58f9-41cb-8701-ccc36a28357f/Purchase_Order.csv?snapshot=2022-05-20T05%3A36%3A44.4292207Z"}]},{"$type":"LocalEntity","name":"Blanket_Agreement","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Blanket_Agreement.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Blanket Number","dataType":"string"},{"name":"Revision Number","dataType":"double"},{"name":"Line Number","dataType":"double"},{"name":"VENDOR_ID","dataType":"double"},{"name":"VENDOR_SITE_ID","dataType":"double"},{"name":"AGENT_ID","dataType":"int64"},{"name":"Blanket Buyer Name","dataType":"string"},{"name":"Global Blanket Flag","dataType":"string"},{"name":"Item Revision","dataType":"string"},{"name":"Ship To Location","dataType":"string"},{"name":"Currency Code","dataType":"string"},{"name":"Rate Date","dataType":"dateTime"},{"name":"Rate Type","dataType":"string"},{"name":"Start Date","dataType":"dateTime"},{"name":"Expiration Date","dataType":"dateTime"},{"name":"PO_HEADER_ID","dataType":"double"},{"name":"Blanket Item Revision","dataType":"string"},{"name":"Vendor Name","dataType":"string"},{"name":"Vendor Site","dataType":"string"},{"name":"Item Description","dataType":"string"},{"name":"Unit of Measure","dataType":"string"},{"name":"Blanket First Approved Date","dataType":"dateTime"},{"name":"First Approved Date","dataType":"dateTime"},{"name":"Open Flag","dataType":"string"},{"name":"Released Quantity","dataType":"double"},{"name":"Committed Quantity","dataType":"double"},{"name":"Creation Date","dataType":"dateTime"},{"name":"Unit Price","dataType":"double"},{"name":"Item Number","dataType":"string"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"Approved Date","dataType":"dateTime"},{"name":"Authorization Status","dataType":"string"},{"name":"Last Update Date","dataType":"dateTime"},{"name":"PO_LINE_ID","dataType":"double"},{"name":"Planner Code","dataType":"string"},{"name":"Amount Limit","dataType":"double"},{"name":"Cancel Date","dataType":"dateTime"},{"name":"Closed Date","dataType":"dateTime"},{"name":"Blanket Age Days","dataType":"double"},{"name":"Expired Flag","dataType":"string"},{"name":"ASL_KEY","dataType":"string"},{"name":"Used in ASL Flag","dataType":"string"},{"name":"FUNCTIONAL_RATE","dataType":"double"}],"partitions":[{"name":"Part001","refreshTime":"2022-05-20T05:30:33.2055288+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/7a172cae-58f9-41cb-8701-ccc36a28357f/Blanket_Agreement.csv?snapshot=2022-05-20T05%3A30%3A32.8055297Z"}]},{"$type":"LocalEntity","name":"Quote","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Quote.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Organization Code","dataType":"string"},{"name":"Quote Number","dataType":"string"},{"name":"Quote Type","dataType":"string"},{"name":"QUOTATION_CLASS_CODE","dataType":"string"},{"name":"Supplier Quote Number","dataType":"string"},{"name":"Start Date","dataType":"dateTime"},{"name":"Expiration Date","dataType":"dateTime"},{"name":"VENDOR_ID","dataType":"double"},{"name":"VENDOR_SITE_ID","dataType":"double"},{"name":"Supplier Reply Date","dataType":"dateTime"},{"name":"Warning Delay","dataType":"double"},{"name":"PO_LINE_ID","dataType":"double"},{"name":"LINE_LOCATION_ID","dataType":"double"},{"name":"Quote Status","dataType":"string"},{"name":"Item Revision","dataType":"string"},{"name":"Active Flag","dataType":"string"},{"name":"Line Number","dataType":"double"},{"name":"Quote Buyer","dataType":"string"},{"name":"Ship To Location","dataType":"string"},{"name":"Currency Code","dataType":"string"},{"name":"Quote Item Revision","dataType":"string"},{"name":"Unit of Measure","dataType":"string"},{"name":"Supplier Name","dataType":"string"},{"name":"Supplier Site Code","dataType":"string"},{"name":"Item Number","dataType":"string"},{"name":"Item Description","dataType":"string"},{"name":"Creation Date","dataType":"dateTime"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"Planner Code","dataType":"string"},{"name":"ASL_KEY","dataType":"string"},{"name":"Used in ASL Flag","dataType":"string"},{"name":"Break Quantity","dataType":"double"},{"name":"Price Break","dataType":"double"},{"name":"Price Discount","dataType":"double"}],"partitions":[{"name":"Part001","refreshTime":"2022-05-20T05:30:16.5041497+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/7a172cae-58f9-41cb-8701-ccc36a28357f/Quote.csv?snapshot=2022-05-20T05%3A30%3A16.4728284Z"}]}]}