{"name":"COHERENT_SNOWFLAKE_PLANNING","description":"22.02.22 - MRP_SCHEDULE_DATES_V für ORG_FORECAST","version":"1.0","culture":"en-US","modifiedTime":"2022-05-19T07:32:02.572814+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"XXCOH_KANBAN_ESL":{"queryId":"5d6f6250-675a-414e-bf6f-7c2e3d9eb326","queryName":"XXCOH_KANBAN_ESL","loadEnabled":true},"Org":{"queryId":"b94cc95d-0885-46a0-97b6-e2989b02581f","queryName":"Org"},"XXCOH_MI_INVENTORY_FIN_VIEW":{"queryId":"a3b357f5-5f4c-42a6-8ef5-3374314bbbf2","queryName":"XXCOH_MI_INVENTORY_FIN_VIEW","loadEnabled":true},"XXCOH_MI_INVENTORY_SMALL":{"queryId":"18128d48-11ce-42a0-84a3-7007808bd01f","queryName":"XXCOH_MI_INVENTORY_SMALL","loadEnabled":true},"XXREP_WIP_DISCRETE_JOBS_V":{"queryId":"d669802f-ace1-433b-825f-1b7a8281d4a7","queryName":"XXREP_WIP_DISCRETE_JOBS_V","loadEnabled":true},"MRP_SCHEDULE_DATES_V":{"queryId":"a6706ab5-bab0-4d5d-8a70-69e22d4e7b21","queryName":"MRP_SCHEDULE_DATES_V","loadEnabled":true},"XXREP_MFG_GROSS_REQUIREMENTS_V":{"queryId":"041231e7-b444-4580-a7b1-ebf24ed8da7c","queryName":"XXREP_MFG_GROSS_REQUIREMENTS_V","loadEnabled":true}},"document":"section Section1;\r\nshared XXCOH_KANBAN_ESL = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 1\" = Navigation{[Name = \"XXCOH\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXCOH_KANBAN_ESL\", Kind = \"Table\"]}[Data],\r\n  #\"Filtered rows\" = Table.SelectRows(#\"Navigation 2\", each [ORG_ID] = Org),\r\n  #\"Filtered rows 1\" = Table.SelectRows(#\"Filtered rows\", each [CREATION_DATE] > #datetime(2021, 11, 1, 0, 0, 0))\r\nin\r\n  #\"Filtered rows 1\";\r\nshared Org = let\r\n  Org = 587 meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type any]\r\nin\r\n  Org;\r\nshared XXCOH_MI_INVENTORY_FIN_VIEW = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 1\" = Navigation{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXCOH_MI_INVENTORY_FIN_VIEW\", Kind = \"View\"]}[Data],\r\n  #\"Filtered rows\" = Table.SelectRows(#\"Navigation 2\", each [ORGANIZATION_ID] = Org)\r\nin\r\n  #\"Filtered rows\";\r\nshared XXCOH_MI_INVENTORY_SMALL = let\r\n  // für die Reports.. nur relevante Spalten\r\n  Source = XXCOH_MI_INVENTORY_FIN_VIEW,\r\n  #\"Removed columns\" = Table.RemoveColumns(Source, {\"REV_EFF_DATE\", \"AGILE_LIFE_PHASE\", \"PRIMARY_UOM_CODE\", \"PLANNING_MAKE_BUY_CODE\", \"BUYER\", \"ITEM_COST\", \"ITEM_ADD_BACK_COST\", \"PD_ITEM_COST\", \"BASE_CURRENCY\", \"EXTENDED_VALUE\", \"EXTENDED_VALUE_USD\", \"USD_RATE\", \"EXT_ITEM_COST_USD\", \"EXT_MATERIAL_COST_USD\", \"EXT_MATERIAL_OH_COST_USD\", \"EXT_RESOURCE_COST_USD\", \"EXT_OVERHEAD_COST_USD\", \"EXT_OS_PROCESSING_COST_USD\", \"PD_EXTENDED_VALUE\", \"PD_EXTENDED_VALUE_USD\", \"PD_EXT_ITEM_COST_USD\", \"PD_EXT_MATERIAL_COST_USD\", \"PD_EXT_MATERIAL_OH_COST_USD\", \"PD_EXT_RESOURCE_COST_USD\", \"PD_EXT_OVERHEAD_COST_USD\", \"PD_EXT_OS_PROCESSING_COST_USD\", \"MAX_MINMAX_QUANTITY\", \"MIN_MINMAX_QUANTITY\", \"MINIMUM_ORDER_QUANTITY\", \"FIXED_LOT_MULTIPLIER\", \"OWNING_ORGANIZATION\", \"LOC_ROW\", \"LOC_RACK\", \"LOC_SHELF\", \"SUBINV_ASSET_FLAG\", \"SUBINV_QUANTITY_TRACKED_FLAG\", \"SUBINV_NETTABLE_FLAG\", \"SUBINV_LOCATOR_TYPE\", \"MATERIAL_ENTITY\", \"MATERIAL_DEPT\", \"MATERIAL_ACCT\", \"MATERIAL_OH_ENTITY\", \"MATERIAL_OH_DEPT\", \"MATERIAL_OH_ACCT\", \"RESOURCE_ENTITY\", \"RESOURCE_DEPT\", \"RESOURCE_ACCT\", \"OVERHEAD_ENTITY\", \"OVERHEAD_DEPT\", \"OVERHEAD_ACCT\", \"OS_PROCESS_ENTITY\", \"OPERATING_UNIT_ID\", \"LOCATOR_ID\", \"COST_GROUP_ID\", \"INVENTORY_ITEM_ID\", \"SOURCE_ID\", \"REPORTING_TBU\", \"SITE\", \"ORG_LOCATION_CODE\", \"REGION_1\", \"TOWN_OR_CITY\", \"LEGAL_ENTITY\", \"OPERATING_UNIT\", \"FISCAL_YEAR\", \"FISCAL_WEEK\", \"FISCAL_SYSDATE_GEN\", \"SET_OF_BOOKS\", \"ORGANIZATION_ID\", \"LEGAL_ENTITY_ID\", \"PD_MATERIAL_OVERHEAD_COST\", \"PD_RESOURCE_COST\", \"PD_OVERHEAD_COST\", \"PD_OUTSIDE_PROCESSING_COST\", \"FISCAL_PERIOD\", \"FISCAL_QUARTER\", \"OS_PROCESS_DEPT\", \"OS_PROCESS_ACCT\", \"EXPENSE_ENTITY\", \"EXPENSE_DEPT\", \"EXPENSE_ACCT\", \"BOM_ITEM_TYPE\", \"BOM_ENABLED_FLAG\", \"BUILD_IN_WIP_FLAG\", \"COSTING_ENABLED_FLAG\", \"CREATE_SUPPLY_FLAG\", \"CUSTOMER_ORDER_ENABLED_FLAG\", \"CUSTOMER_ORDER_FLAG\", \"CYCLE_COUNT_ENABLED_FLAG\", \"INSPECTION_REQUIRED_FLAG\", \"INVENTORY_ASSET_FLAG\", \"INVENTORY_ITEM_FLAG\"}),\r\n  #\"Removed columns 1\" = Table.RemoveColumns(#\"Removed columns\", {\"MUST_USE_APPROVED_VENDOR_FLAG\", \"PURCHASING_ENABLED_FLAG\", \"PURCHASING_ITEM_FLAG\", \"ITEM_TYPE_CODE\"}),\r\n  #\"Removed columns 2\" = Table.RemoveColumns(#\"Removed columns 1\", {\"ITEM_CATALOG_GROUP\", \"MAXIMUM_ORDER_QUANTITY\", \"FIXED_ORDER_QUANTITY\", \"FIXED_DAYS_SUPPLY\", \"SHRINKAGE_RATE\", \"ACCEPTABLE_EARLY_DAYS\", \"LEAD_TIME_LOT_SIZE\", \"PREPROCESSING_LEAD_TIME\", \"POSTPROCESSING_LEAD_TIME\", \"FIXED_LEAD_TIME\", \"VARIABLE_LEAD_TIME\", \"CUM_MANUFACTURING_LEAD_TIME\", \"CUMULATIVE_TOTAL_LEAD_TIME\", \"FULL_LEAD_TIME\", \"SUPPLY_SOURCE\", \"DEMAND_SOURCE\", \"COST_SOURCE_TYPE\", \"TECHNICAL_BUSINESS_UNIT\", \"PRODUCT_FAMILY\", \"PRODUCT_LINE\", \"FORECAST_FIELD\", \"LEAD_TIME_CATEGORY\", \"BACKUP_CATEGORY\", \"ITEM_CUSTOMER\", \"BCP_CODE\", \"ROYALTY\", \"PLANNING_GREEN_SUPPLY_STATUS\", \"PLANNING_ACTION\", \"PLANNING_FAMILY_UNIQUE\", \"OPERATIONS_REPORTING\", \"SEC_REPORTING\", \"MATERIAL_COST\", \"MATERIAL_OVERHEAD_COST\", \"RESOURCE_COST\", \"OVERHEAD_COST\", \"OUTSIDE_PROCESSING_COST\", \"PD_MATERIAL_COST\", \"FIN_TBU\", \"FIN_PFC\", \"LOT_NUMBER\"})\r\nin\r\n  #\"Removed columns 2\";\r\nshared XXREP_WIP_DISCRETE_JOBS_V = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 1\" = Navigation{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXREP_WIP_DISCRETE_JOBS_V\", Kind = \"View\"]}[Data],\r\n  #\"Filtered rows\" = Table.SelectRows(#\"Navigation 2\", each [ORGANIZATION_ID] = Org),\r\n  #\"Filtered rows 1\" = Table.SelectRows(#\"Filtered rows\", each [CREATION_DATE] > #datetime(2021, 1, 1, 0, 0, 0))\r\nin\r\n  #\"Filtered rows 1\";\r\nshared MRP_SCHEDULE_DATES_V = let\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\n  #\"Navigation 1\" = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\n  #\"Navigation 3\" = #\"Navigation 2\"{[Name = \"MRP_SCHEDULE_DATES_V\", Kind = \"View\"]}[Data],\n  #\"Filtered rows\" = Table.SelectRows(#\"Navigation 3\", each  [SOURCE_CODE] = \"MRCSAL\" and ([SCHEDULE_DESIGNATOR] = \"LDP_MDS\")),\r\n  #\"Removed columns\" = Table.RemoveColumns(#\"Filtered rows\", {\"PROGRAM_UPDATE_DATE\", \"DDF_CONTEXT\", \"ATTRIBUTE_CATEGORY\", \"ATTRIBUTE1\", \"ATTRIBUTE2\", \"ATTRIBUTE3\", \"ATTRIBUTE4\", \"ATTRIBUTE5\", \"ATTRIBUTE6\", \"ATTRIBUTE7\", \"ATTRIBUTE8\", \"ATTRIBUTE9\", \"ATTRIBUTE10\", \"ATTRIBUTE11\", \"ATTRIBUTE12\", \"ATTRIBUTE13\", \"ATTRIBUTE14\", \"ATTRIBUTE15\", \"PROJECT_ID\", \"TASK_ID\", \"LINE_ID\", \"LINE_CODE\", \"END_ITEM_UNIT_NUMBER\"})\nin\n  #\"Removed columns\";\r\nshared XXREP_MFG_GROSS_REQUIREMENTS_V = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  #\"Navigation 1\" = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 3\" = #\"Navigation 2\"{[Name = \"XXREP_MFG_GROSS_REQUIREMENTS_V\", Kind = \"View\"]}[Data],\r\n  #\"Filtered rows\" = Table.SelectRows(#\"Navigation 3\", each [ORGANIZATION_ID] = Org)\r\nin\r\n  #\"Filtered rows\";\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"XXCOH_KANBAN_ESL","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"XXCOH_KANBAN_ESL.csv"},"attributes":[{"name":"ORACLEINSTANCE","dataType":"string"},{"name":"ORG_ID","dataType":"double"},{"name":"ORG","dataType":"string"},{"name":"KANBANCARDID","dataType":"double"},{"name":"ESLCARDID","dataType":"string"},{"name":"ESLCARDACTION","dataType":"string"},{"name":"KANBANCARDNUM","dataType":"string"},{"name":"ITEM_ID","dataType":"double"},{"name":"ITEMNUM","dataType":"string"},{"name":"DESTSUBINV","dataType":"string"},{"name":"DESTLOCATOR","dataType":"string"},{"name":"CARDSTATUS","dataType":"string"},{"name":"SUPPLYSTATUS","dataType":"string"},{"name":"CARDTYPE","dataType":"string"},{"name":"SOURCETYPE","dataType":"string"},{"name":"KANBANSIZE","dataType":"double"},{"name":"CARD_LASTUPDATEDATE","dataType":"dateTime"},{"name":"CARD_LASTUPDATEBY_NAME","dataType":"string"},{"name":"CARD_CREATIONDATE","dataType":"dateTime"},{"name":"CARD_CREATEDBY_NAME","dataType":"string"},{"name":"SUPPLIER","dataType":"string"},{"name":"SUPPLIERSITE","dataType":"string"},{"name":"SOURCEORG","dataType":"string"},{"name":"SOURCESUBINV","dataType":"string"},{"name":"SOURCELOCATOR","dataType":"string"},{"name":"ERRORCODE","dataType":"string"},{"name":"CARDINFO","dataType":"string"},{"name":"NUMBEROFCARDS","dataType":"double"},{"name":"ESLCARDRELATIONSHIP","dataType":"string"},{"name":"BOXTYPE","dataType":"string"},{"name":"ITEMDESCR","dataType":"string"},{"name":"PLANNERCODE","dataType":"string"},{"name":"PLANNERDESCR","dataType":"string"},{"name":"PLANNERPERSON","dataType":"string"},{"name":"LASTREPLENISHDOCTYPE","dataType":"string"},{"name":"LASTREPLENISHDOCNUM","dataType":"string"},{"name":"LASTREPLENISHDOCLINE","dataType":"string"},{"name":"CREATION_DATE","dataType":"dateTime"},{"name":"SEQ_ID","dataType":"double"},{"name":"PULL_SEQ_INFO","dataType":"string"},{"name":"REQUEST_ID","dataType":"double"},{"name":"FILE_NAME","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-20T03:32:14.3831714+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/c91b4835-5a63-4330-94d7-c2c615a541cd/XXCOH_KANBAN_ESL.csv?snapshot=2022-05-20T03%3A32%3A14.3563246Z"}]},{"$type":"LocalEntity","name":"XXCOH_MI_INVENTORY_FIN_VIEW","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"XXCOH_MI_INVENTORY_FIN_VIEW.csv"},"attributes":[{"name":"ASOF_DATE","dataType":"date"},{"name":"ASOF_DATE_DISP","dataType":"dateTime"},{"name":"DATA_SOURCE","dataType":"string"},{"name":"ITEM_NUMBER","dataType":"string"},{"name":"ITEM_DESCRIPTION","dataType":"string"},{"name":"ITEM_REV","dataType":"string"},{"name":"REV_EFF_DATE","dataType":"dateTime"},{"name":"AGILE_LIFE_PHASE","dataType":"string"},{"name":"OWNING_ORGANIZATION","dataType":"string"},{"name":"SUBINVENTORY","dataType":"string"},{"name":"LOC_BIN","dataType":"string"},{"name":"QUANTITY","dataType":"double"},{"name":"PRIMARY_UOM_CODE","dataType":"string"},{"name":"LOT_NUMBER","dataType":"string"},{"name":"PLANNER_CODE","dataType":"string"},{"name":"PLANNING_MAKE_BUY_CODE","dataType":"string"},{"name":"BUYER","dataType":"string"},{"name":"ITEM_COST","dataType":"double"},{"name":"ITEM_ADD_BACK_COST","dataType":"double"},{"name":"PD_ITEM_COST","dataType":"double"},{"name":"BASE_CURRENCY","dataType":"string"},{"name":"EXTENDED_VALUE","dataType":"double"},{"name":"EXTENDED_VALUE_USD","dataType":"double"},{"name":"USD_RATE","dataType":"double"},{"name":"EXT_ITEM_COST_USD","dataType":"double"},{"name":"EXT_MATERIAL_COST_USD","dataType":"double"},{"name":"EXT_MATERIAL_OH_COST_USD","dataType":"double"},{"name":"EXT_RESOURCE_COST_USD","dataType":"double"},{"name":"EXT_OVERHEAD_COST_USD","dataType":"double"},{"name":"EXT_OS_PROCESSING_COST_USD","dataType":"double"},{"name":"PD_EXTENDED_VALUE","dataType":"double"},{"name":"PD_EXTENDED_VALUE_USD","dataType":"double"},{"name":"PD_EXT_ITEM_COST_USD","dataType":"double"},{"name":"PD_EXT_MATERIAL_COST_USD","dataType":"double"},{"name":"PD_EXT_MATERIAL_OH_COST_USD","dataType":"double"},{"name":"PD_EXT_RESOURCE_COST_USD","dataType":"double"},{"name":"PD_EXT_OVERHEAD_COST_USD","dataType":"double"},{"name":"PD_EXT_OS_PROCESSING_COST_USD","dataType":"double"},{"name":"MAX_MINMAX_QUANTITY","dataType":"double"},{"name":"MIN_MINMAX_QUANTITY","dataType":"double"},{"name":"MINIMUM_ORDER_QUANTITY","dataType":"double"},{"name":"FIXED_LOT_MULTIPLIER","dataType":"double"},{"name":"DATE_IN","dataType":"dateTime"},{"name":"DATE_LAST_ACTIVITY","dataType":"dateTime"},{"name":"LOCATOR","dataType":"string"},{"name":"LOC_SUBINV","dataType":"string"},{"name":"LOC_ROW","dataType":"string"},{"name":"LOC_RACK","dataType":"string"},{"name":"LOC_SHELF","dataType":"string"},{"name":"SUBINV_ASSET_FLAG","dataType":"string"},{"name":"SUBINV_QUANTITY_TRACKED_FLAG","dataType":"string"},{"name":"SUBINV_NETTABLE_FLAG","dataType":"string"},{"name":"SUBINV_LOCATOR_TYPE","dataType":"string"},{"name":"MATERIAL_ENTITY","dataType":"string"},{"name":"MATERIAL_DEPT","dataType":"string"},{"name":"MATERIAL_ACCT","dataType":"string"},{"name":"MATERIAL_OH_ENTITY","dataType":"string"},{"name":"MATERIAL_OH_DEPT","dataType":"string"},{"name":"MATERIAL_OH_ACCT","dataType":"string"},{"name":"RESOURCE_ENTITY","dataType":"string"},{"name":"RESOURCE_DEPT","dataType":"string"},{"name":"RESOURCE_ACCT","dataType":"string"},{"name":"OVERHEAD_ENTITY","dataType":"string"},{"name":"OVERHEAD_DEPT","dataType":"string"},{"name":"OVERHEAD_ACCT","dataType":"string"},{"name":"OS_PROCESS_ENTITY","dataType":"string"},{"name":"OS_PROCESS_DEPT","dataType":"string"},{"name":"OS_PROCESS_ACCT","dataType":"string"},{"name":"EXPENSE_ENTITY","dataType":"string"},{"name":"EXPENSE_DEPT","dataType":"string"},{"name":"EXPENSE_ACCT","dataType":"string"},{"name":"BOM_ITEM_TYPE","dataType":"string"},{"name":"BOM_ENABLED_FLAG","dataType":"string"},{"name":"BUILD_IN_WIP_FLAG","dataType":"string"},{"name":"COSTING_ENABLED_FLAG","dataType":"string"},{"name":"CREATE_SUPPLY_FLAG","dataType":"string"},{"name":"CUSTOMER_ORDER_ENABLED_FLAG","dataType":"string"},{"name":"CUSTOMER_ORDER_FLAG","dataType":"string"},{"name":"CYCLE_COUNT_ENABLED_FLAG","dataType":"string"},{"name":"INSPECTION_REQUIRED_FLAG","dataType":"string"},{"name":"INVENTORY_ASSET_FLAG","dataType":"string"},{"name":"INVENTORY_ITEM_FLAG","dataType":"string"},{"name":"MUST_USE_APPROVED_VENDOR_FLAG","dataType":"string"},{"name":"PURCHASING_ENABLED_FLAG","dataType":"string"},{"name":"PURCHASING_ITEM_FLAG","dataType":"string"},{"name":"ITEM_TYPE_CODE","dataType":"string"},{"name":"ITEM_CATALOG_GROUP","dataType":"string"},{"name":"ITEM_TYPE","dataType":"string"},{"name":"MAXIMUM_ORDER_QUANTITY","dataType":"double"},{"name":"FIXED_ORDER_QUANTITY","dataType":"double"},{"name":"FIXED_DAYS_SUPPLY","dataType":"double"},{"name":"SHRINKAGE_RATE","dataType":"double"},{"name":"ACCEPTABLE_EARLY_DAYS","dataType":"double"},{"name":"LEAD_TIME_LOT_SIZE","dataType":"double"},{"name":"PREPROCESSING_LEAD_TIME","dataType":"double"},{"name":"POSTPROCESSING_LEAD_TIME","dataType":"double"},{"name":"FIXED_LEAD_TIME","dataType":"double"},{"name":"VARIABLE_LEAD_TIME","dataType":"double"},{"name":"CUM_MANUFACTURING_LEAD_TIME","dataType":"double"},{"name":"CUMULATIVE_TOTAL_LEAD_TIME","dataType":"double"},{"name":"FULL_LEAD_TIME","dataType":"double"},{"name":"SUPPLY_SOURCE","dataType":"string"},{"name":"DEMAND_SOURCE","dataType":"string"},{"name":"COST_SOURCE_TYPE","dataType":"string"},{"name":"TECHNICAL_BUSINESS_UNIT","dataType":"string"},{"name":"PRODUCT_FAMILY","dataType":"string"},{"name":"PRODUCT_LINE","dataType":"string"},{"name":"FORECAST_FIELD","dataType":"string"},{"name":"LEAD_TIME_CATEGORY","dataType":"string"},{"name":"COMMODITY","dataType":"string"},{"name":"PRIMARY_ORG","dataType":"string"},{"name":"ORG_TECHNICAL_BUSINESS_UNIT","dataType":"string"},{"name":"ORG_PRODUCT_FAMILY","dataType":"string"},{"name":"ORG_PRODUCT_LINE","dataType":"string"},{"name":"ORG_FORECAST_FIELD","dataType":"string"},{"name":"BACKUP_CATEGORY","dataType":"string"},{"name":"ITEM_CUSTOMER","dataType":"string"},{"name":"BCP_CODE","dataType":"string"},{"name":"ROYALTY","dataType":"string"},{"name":"PLANNING_GREEN_SUPPLY_STATUS","dataType":"string"},{"name":"PLANNING_ACTION","dataType":"string"},{"name":"PLANNING_FAMILY_UNIQUE","dataType":"string"},{"name":"OPERATIONS_REPORTING","dataType":"string"},{"name":"SEC_REPORTING","dataType":"string"},{"name":"MATERIAL_COST","dataType":"double"},{"name":"MATERIAL_OVERHEAD_COST","dataType":"double"},{"name":"RESOURCE_COST","dataType":"double"},{"name":"OVERHEAD_COST","dataType":"double"},{"name":"OUTSIDE_PROCESSING_COST","dataType":"double"},{"name":"PD_MATERIAL_COST","dataType":"double"},{"name":"PD_MATERIAL_OVERHEAD_COST","dataType":"double"},{"name":"PD_RESOURCE_COST","dataType":"double"},{"name":"PD_OVERHEAD_COST","dataType":"double"},{"name":"PD_OUTSIDE_PROCESSING_COST","dataType":"double"},{"name":"FISCAL_PERIOD","dataType":"double"},{"name":"FISCAL_QUARTER","dataType":"double"},{"name":"FISCAL_YEAR","dataType":"double"},{"name":"FISCAL_WEEK","dataType":"double"},{"name":"FISCAL_SYSDATE_GEN","dataType":"date"},{"name":"LEGAL_ENTITY","dataType":"string"},{"name":"OPERATING_UNIT","dataType":"string"},{"name":"SET_OF_BOOKS","dataType":"string"},{"name":"ORG_LOCATION_CODE","dataType":"string"},{"name":"REGION_1","dataType":"string"},{"name":"TOWN_OR_CITY","dataType":"string"},{"name":"SITE","dataType":"string"},{"name":"REPORTING_TBU","dataType":"string"},{"name":"SOURCE_ID","dataType":"double"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"ORGANIZATION_ID","dataType":"double"},{"name":"COST_GROUP_ID","dataType":"double"},{"name":"LOCATOR_ID","dataType":"double"},{"name":"OPERATING_UNIT_ID","dataType":"double"},{"name":"LEGAL_ENTITY_ID","dataType":"double"},{"name":"FIN_TBU","dataType":"string"},{"name":"FIN_PFC","dataType":"string"},{"name":"ORG_SUB_KEY_ID","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-20T03:32:23.0446494+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/c91b4835-5a63-4330-94d7-c2c615a541cd/XXCOH_MI_INVENTORY_FIN_VIEW.csv?snapshot=2022-05-20T03%3A32%3A20.0480786Z"}]},{"$type":"LocalEntity","name":"XXCOH_MI_INVENTORY_SMALL","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"XXCOH_MI_INVENTORY_SMALL.csv"},"annotations":[{"name":"pbi:EntityTypeDisplayHint","value":"CalculatedEntity"}],"attributes":[{"name":"ASOF_DATE","dataType":"date"},{"name":"ASOF_DATE_DISP","dataType":"dateTime"},{"name":"DATA_SOURCE","dataType":"string"},{"name":"ITEM_NUMBER","dataType":"string"},{"name":"ITEM_DESCRIPTION","dataType":"string"},{"name":"ITEM_REV","dataType":"string"},{"name":"SUBINVENTORY","dataType":"string"},{"name":"LOC_BIN","dataType":"string"},{"name":"QUANTITY","dataType":"double"},{"name":"PLANNER_CODE","dataType":"string"},{"name":"DATE_IN","dataType":"dateTime"},{"name":"DATE_LAST_ACTIVITY","dataType":"dateTime"},{"name":"LOCATOR","dataType":"string"},{"name":"LOC_SUBINV","dataType":"string"},{"name":"ITEM_TYPE","dataType":"string"},{"name":"COMMODITY","dataType":"string"},{"name":"PRIMARY_ORG","dataType":"string"},{"name":"ORG_TECHNICAL_BUSINESS_UNIT","dataType":"string"},{"name":"ORG_PRODUCT_FAMILY","dataType":"string"},{"name":"ORG_PRODUCT_LINE","dataType":"string"},{"name":"ORG_FORECAST_FIELD","dataType":"string"},{"name":"ORG_SUB_KEY_ID","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-20T03:32:25.5134325+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/c91b4835-5a63-4330-94d7-c2c615a541cd/XXCOH_MI_INVENTORY_SMALL.csv?snapshot=2022-05-20T03%3A32%3A25.4959726Z"}]},{"$type":"LocalEntity","name":"XXREP_WIP_DISCRETE_JOBS_V","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"XXREP_WIP_DISCRETE_JOBS_V.csv"},"attributes":[{"name":"ORGANIZATION_ID","dataType":"double"},{"name":"WIP_ENTITY_ID","dataType":"double"},{"name":"WIPJOB_ORG_KEY_CODE","dataType":"string"},{"name":"WIPJOB_ORG_KEY_ID","dataType":"string"},{"name":"LAST_UPDATE_DATE","dataType":"dateTime"},{"name":"LAST_UPDATED_BY","dataType":"double"},{"name":"CREATION_DATE","dataType":"dateTime"},{"name":"CREATED_BY","dataType":"double"},{"name":"DESCRIPTION","dataType":"string"},{"name":"STATUS_TYPE","dataType":"double"},{"name":"PRIMARY_ITEM_ID","dataType":"double"},{"name":"CLASS_CODE","dataType":"string"},{"name":"MATERIAL_ACCOUNT","dataType":"double"},{"name":"MATERIAL_OVERHEAD_ACCOUNT","dataType":"double"},{"name":"RESOURCE_ACCOUNT","dataType":"double"},{"name":"OUTSIDE_PROCESSING_ACCOUNT","dataType":"double"},{"name":"MATERIAL_VARIANCE_ACCOUNT","dataType":"double"},{"name":"RESOURCE_VARIANCE_ACCOUNT","dataType":"double"},{"name":"OUTSIDE_PROC_VARIANCE_ACCOUNT","dataType":"double"},{"name":"STD_COST_ADJUSTMENT_ACCOUNT","dataType":"double"},{"name":"OVERHEAD_ACCOUNT","dataType":"double"},{"name":"OVERHEAD_VARIANCE_ACCOUNT","dataType":"double"},{"name":"START_QUANTITY","dataType":"double"},{"name":"QUANTITY_REMAINING","dataType":"double"},{"name":"QUANTITY_COMPLETED","dataType":"double"},{"name":"QUANTITY_SCRAPPED","dataType":"double"},{"name":"NET_QUANTITY","dataType":"double"},{"name":"BOM_REFERENCE_ID","dataType":"double"},{"name":"ROUTING_REFERENCE_ID","dataType":"double"},{"name":"COMMON_BOM_SEQUENCE_ID","dataType":"double"},{"name":"COMMON_ROUTING_SEQUENCE_ID","dataType":"double"},{"name":"BOM_REVISION","dataType":"string"},{"name":"ROUTING_REVISION","dataType":"string"},{"name":"BOM_REVISION_DATE","dataType":"dateTime"},{"name":"ROUTING_REVISION_DATE","dataType":"dateTime"},{"name":"LOT_NUMBER","dataType":"string"},{"name":"ALTERNATE_BOM_DESIGNATOR","dataType":"string"},{"name":"ALTERNATE_ROUTING_DESIGNATOR","dataType":"string"},{"name":"COMPLETION_SUBINVENTORY","dataType":"string"},{"name":"COMPLETION_LOCATOR_ID","dataType":"double"},{"name":"SUB_LOCATOR_CONTROL","dataType":"double"},{"name":"SCHEDULE_GROUP_NAME","dataType":"string"},{"name":"SCHEDULE_GROUP_ID","dataType":"double"},{"name":"BUILD_SEQUENCE","dataType":"double"},{"name":"LINE_CODE","dataType":"string"},{"name":"LINE_ID","dataType":"double"},{"name":"PROJECT_ID","dataType":"double"},{"name":"TASK_ID","dataType":"double"},{"name":"END_ITEM_UNIT_NUMBER","dataType":"string"},{"name":"DEMAND_CLASS","dataType":"string"},{"name":"SCHEDULED_START_DATE","dataType":"dateTime"},{"name":"DATE_RELEASED","dataType":"dateTime"},{"name":"SCHEDULED_COMPLETION_DATE","dataType":"dateTime"},{"name":"DATE_COMPLETED","dataType":"dateTime"},{"name":"DATE_CLOSED","dataType":"dateTime"},{"name":"OVERCOMPLETION_TOLERANCE_VALUE","dataType":"double"},{"name":"KANBAN_CARD_ID","dataType":"double"},{"name":"KANBAN_CARD_NUMBER","dataType":"string"},{"name":"PO_CREATION_TIME","dataType":"double"},{"name":"PRIORITY","dataType":"double"},{"name":"DUE_DATE","dataType":"dateTime"},{"name":"EST_SCRAP_ACCOUNT","dataType":"double"},{"name":"EST_SCRAP_VAR_ACCOUNT","dataType":"double"},{"name":"ENTITY_TYPE","dataType":"double"},{"name":"DUE_DATE_PENALTY","dataType":"double"},{"name":"DUE_DATE_TOLERANCE","dataType":"double"},{"name":"COPRODUCTS_SUPPLY","dataType":"double"},{"name":"REQUESTED_START_DATE","dataType":"dateTime"},{"name":"SERIALIZATION_START_OP","dataType":"double"},{"name":"ACTUAL_START_DATE","dataType":"dateTime"},{"name":"EXPECTED_HOLD_RELEASE_DATE","dataType":"dateTime"},{"name":"INVORG_CODE","dataType":"string"},{"name":"ASSEMBLY_ITEM_NUMBER","dataType":"string"},{"name":"JOB_SOURCE","dataType":"string"},{"name":"JOB_STATUS_CODE","dataType":"double"},{"name":"JOB_STATUS","dataType":"string"},{"name":"WIP_SUPPLY_TYPE_CODE","dataType":"double"},{"name":"WIP_SUPPLY_TYPE","dataType":"string"},{"name":"JB_TYPE","dataType":"string"},{"name":"JOB_NUMBER","dataType":"string"},{"name":"JOB_DESCRIPTION","dataType":"string"},{"name":"FIRM_PLANNED_FLAG","dataType":"string"},{"name":"JOB_TYPE","dataType":"string"},{"name":"FIRST_UNIT_START_DATE","dataType":"dateTime"},{"name":"FIRST_UNIT_COMPLETION_DATE","dataType":"dateTime"},{"name":"LAST_UNIT_START_DATE","dataType":"dateTime"},{"name":"LAST_UNIT_COMPLETION_DATE","dataType":"dateTime"},{"name":"DATE_LAST_MOVED","dataType":"dateTime"},{"name":"PROJECT_NUMBER","dataType":"string"},{"name":"PROJECT_NAME","dataType":"string"},{"name":"SALES_ORDER_NO_DFF","dataType":"double"},{"name":"SALE_ORDER_LINE_NO_DFF","dataType":"double"},{"name":"SERVICE_REQUEST_DFF","dataType":"string"},{"name":"ASSEMBLY_SN_DFF","dataType":"string"},{"name":"CREATED_BY_LOGIN","dataType":"string"},{"name":"LAST_UPDATED_BY_LOGIN","dataType":"string"},{"name":"COMPLETION_LOCATOR","dataType":"string"},{"name":"LOCAL_EXTRACT_DATE","dataType":"dateTime"},{"name":"EXTRACT_DATE","dataType":"dateTime"},{"name":"DATA_UPDATE_DESC","dataType":"string"},{"name":"ITEM_NUMBER","dataType":"string"},{"name":"ITEM_DESCRIPTION","dataType":"string"},{"name":"ITEM_TYPE","dataType":"string"},{"name":"ITEM_ORG_KEY_ID","dataType":"string"},{"name":"ITEM_ORG_KEY_CODE","dataType":"string"},{"name":"PRODUCT_FAMILY","dataType":"string"},{"name":"FORECAST_FIELD","dataType":"string"},{"name":"PRODUCT_LINE","dataType":"string"},{"name":"TBU","dataType":"string"},{"name":"ORG_PRODUCT_FAMILY","dataType":"string"},{"name":"ORG_FORECAST_FIELD","dataType":"string"},{"name":"ORG_PRODUCT_LINE","dataType":"string"},{"name":"ORG_TBU","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-20T03:32:27.8738483+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/c91b4835-5a63-4330-94d7-c2c615a541cd/XXREP_WIP_DISCRETE_JOBS_V.csv?snapshot=2022-05-20T03%3A32%3A27.8496317Z"}]},{"$type":"LocalEntity","name":"MRP_SCHEDULE_DATES_V","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"MRP_SCHEDULE_DATES_V.csv"},"attributes":[{"name":"MPS_TRANSACTION_ID","dataType":"double"},{"name":"SCHEDULE_LEVEL","dataType":"double"},{"name":"RELIEF_FLAG","dataType":"string"},{"name":"SUPPLY_DEMAND_TYPE","dataType":"double"},{"name":"LAST_UPDATE_DATE","dataType":"dateTime"},{"name":"LAST_UPDATED_BY","dataType":"double"},{"name":"CREATION_DATE","dataType":"dateTime"},{"name":"CREATED_BY","dataType":"double"},{"name":"LAST_UPDATE_LOGIN","dataType":"double"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"ORGANIZATION_ID","dataType":"double"},{"name":"SCHEDULE_DESIGNATOR","dataType":"string"},{"name":"SCHEDULE_DATE","dataType":"dateTime"},{"name":"SCHEDULE_WORKDATE","dataType":"dateTime"},{"name":"RATE_END_DATE","dataType":"dateTime"},{"name":"SCHEDULE_QUANTITY","dataType":"double"},{"name":"ORIGINAL_QUANTITY","dataType":"double"},{"name":"REPETITIVE_DAILY_RATE","dataType":"double"},{"name":"QUANTITY_OR_RATE","dataType":"double"},{"name":"SCHEDULE_ORIGINATION_TYPE","dataType":"double"},{"name":"SCHEDULE_ORIGINATION_TEXT","dataType":"string"},{"name":"SOURCE_FORECAST_DESIGNATOR","dataType":"string"},{"name":"REFERENCE_SCHEDULE_ID","dataType":"double"},{"name":"SCHEDULE_COMMENTS","dataType":"string"},{"name":"SOURCE_ORGANIZATION_ID","dataType":"double"},{"name":"SOURCE_ORGANIZATION_CODE","dataType":"string"},{"name":"SOURCE_SCHEDULE_DESIGNATOR","dataType":"string"},{"name":"SOURCE_SALES_ORDER_ID","dataType":"double"},{"name":"SOURCE_DESIGNATOR","dataType":"string"},{"name":"SOURCE_CODE","dataType":"string"},{"name":"SOURCE_LINE_ID","dataType":"double"},{"name":"RESERVATION_ID","dataType":"double"},{"name":"FORECAST_ID","dataType":"double"},{"name":"REQUEST_ID","dataType":"double"},{"name":"PROGRAM_APPLICATION_ID","dataType":"double"},{"name":"PROGRAM_ID","dataType":"double"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-20T03:32:13.241689+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/c91b4835-5a63-4330-94d7-c2c615a541cd/MRP_SCHEDULE_DATES_V.csv?snapshot=2022-05-20T03%3A32%3A13.1989845Z"}]},{"$type":"LocalEntity","name":"XXREP_MFG_GROSS_REQUIREMENTS_V","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"XXREP_MFG_GROSS_REQUIREMENTS_V.csv"},"attributes":[{"name":"EXTRACT_DATE","dataType":"dateTime"},{"name":"LOCAL_EXTRACT_DATE","dataType":"dateTime"},{"name":"PLAN_DATE","dataType":"dateTime"},{"name":"INVORG_TIMEZONE","dataType":"string"},{"name":"ORGANIZATION_CODE","dataType":"string"},{"name":"ORGANIZATION_ID","dataType":"double"},{"name":"ITEM_NUMBER","dataType":"string"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"ITEM_ORG_KEY_ID","dataType":"string"},{"name":"ITEM_ORG_KEY_CODE","dataType":"string"},{"name":"DEMAND_DATE","dataType":"dateTime"},{"name":"DEMAND_ORIGIN","dataType":"string"},{"name":"GROSS_REQUIREMENT_QUANTITY","dataType":"double"},{"name":"COMPILE_DESIGNATOR","dataType":"string"},{"name":"DEMAND_CLASS","dataType":"string"},{"name":"ITEM_TYPE","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-20T03:32:26.0606111+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/c91b4835-5a63-4330-94d7-c2c615a541cd/XXREP_MFG_GROSS_REQUIREMENTS_V.csv?snapshot=2022-05-20T03%3A32%3A26.0376640Z"}]}]}