{"name":"COHREP_SITE_PLANNING_MASTER1","description":"","version":"1.0","culture":"en-US","modifiedTime":"2020-09-05T07:05:58.8506838+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":true,"queriesMetadata":{"Sourcing_Rule":{"queryId":"40b24e9d-6ec3-44cc-9402-6053e480d628","queryName":"Sourcing_Rule","queryGroupId":"root","loadEnabled":true},"ORG":{"queryId":"5c2a1e07-2351-4d86-b04d-200214fde2fa","queryName":"ORG"},"Planner":{"queryId":"c7fafe88-5ffd-44e7-bb70-73aee2374b30","queryName":"Planner","queryGroupId":"root","loadEnabled":true}},"document":"section Section1;\r\nshared Sourcing_Rule = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, \n  Query=\"\n  SELECT\n    sysdate                                                                         extract_date,\n    mcv.category_concat_segs                                                        sourcing_rule,\n    mcv.category_id                                                                 sourcing_rule_id,\n    decode(msso.source_type, 1, 'Transfer From', 2, 'Make At',\n           3, 'Buy From') sourcing_type,\n    msso.source_organization_code                                                   sourcing_org_code,\n    msso.vendor_id,\n    msso.vendor_site,\n    msso.vendor_name,\n    msso.vendor_site_id,\n    nvl(assa.country, hou.country)                                                  country,\n    assa.country_of_origin_code                                                     country_of_origin,\n    nvl(assa.country_of_origin_code, nvl(assa.country, hou.country))                 coo_or_country,\n    nvl(msso.vendor_name, msso.source_organization_code)                            sourcing_org_or_vendor,\n    ( msso.allocation_percent / 100 )                                               allocation_percent,\n    aps.end_date_active                                                             vendor_inactive_date,\n    assa.inactive_date                                                              vendor_site_inactive_date,\n    hou.date_to                                                                     org_end_date,\n    CASE\n        WHEN msso.source_organization_id > 0 THEN\n            CASE\n                WHEN nvl(hou.date_to, sysdate + 1) < sysdate THEN\n                    'No'\n                ELSE\n                    'Yes'\n            END\n        ELSE\n            (\n                CASE\n                    WHEN least(nvl(aps.end_date_active, sysdate + 1), nvl(assa.inactive_date, sysdate + 1)) < trunc(sysdate) THEN\n                        'No'\n                    ELSE\n                        'Yes'\n                END\n            )\n    END active_source_flag\nFROM\n    (\n        SELECT DISTINCT\n            mic.category_id,\n            mic.organization_id,\n            mic.category_concat_segs\n        FROM\n            apps.mtl_item_categories_v    mic,\n            inv.mtl_parameters            mp\n        WHERE\n                mp.organization_code = '\"&ORG&\"'\n            AND mic.organization_id = mp.organization_id\n            AND mic.category_set_name = 'Sourcing Rule'\n    ) mcv,\n    apps.mrp_sr_assignments_v     msra,\n    mrp.mrp_sourcing_rules        msr,\n    apps.mrp_sr_receipt_org_v     msro,\n    apps.mrp_sr_source_org_v      msso,\n    apps.ap_supplier_sites_all    assa,\n    apps.ap_suppliers             aps,\n    hr_organization_units_v       hou\nWHERE\n        1 = 1\n    AND mcv.category_id = msra.category_id\n    AND mcv.organization_id = msra.organization_id\n    AND msra.sourcing_rule_id = msr.sourcing_rule_id\n    AND msr.sourcing_rule_id = msro.sourcing_rule_id\n    AND msro.sr_receipt_id = msso.sr_receipt_id\n    AND sysdate < nvl(msro.disable_date, sysdate + 1)\n    AND sysdate > nvl(msro.effective_date, sysdate - 1)\n    AND msso.vendor_site_id = assa.vendor_site_id (+)\n    AND msso.vendor_id = aps.vendor_id (+)\n    AND msso.source_organization_id = hou.organization_id (+)\n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"EXTRACT_DATE\", \"Extract Date\"}, {\"SOURCING_RULE\", \"Sourcing Rule\"}, {\"SOURCING_TYPE\", \"Sourcing Type\"}, {\"SOURCING_ORG_CODE\", \"Sourcing Org\"}, {\"VENDOR_SITE\", \"Vendor Site\"}, {\"VENDOR_NAME\", \"Vendor Name\"}, {\"SOURCING_ORG_OR_VENDOR\", \"Sourcing Org or Vendor\"}, {\"ALLOCATION_PERCENT\", \"Sourcing Allocation Percent\"}, {\"COUNTRY\", \"Country\"}, {\"COUNTRY_OF_ORIGIN\", \"Country of Origin\"}, {\"COO_OR_COUNTRY\", \"COO or Country\"}, {\"VENDOR_INACTIVE_DATE\", \"Sourcing Vendor Inactive Date\"}, {\"VENDOR_SITE_INACTIVE_DATE\", \"Sourcing Vendor Site Inactive Date\"}, {\"ORG_END_DATE\", \"Sourcing Org Inactive Date\"}, {\"ACTIVE_SOURCE_FLAG\", \"Active Source Flag\"}}),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Renamed columns\", {{\"Sourcing Allocation Percent\", Percentage.Type}, {\"VENDOR_ID\", Int64.Type}, {\"VENDOR_SITE_ID\", Int64.Type}})\r\nin\r\n  #\"Changed column type\";\r\nshared ORG = let\r\n  ORG = \"LDP\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type text]\r\nin\r\n  ORG;\r\nshared Planner = let\r\n  Source = Oracle.Database(\"COHREP\", \n  [HierarchicalNavigation=true, \n  Query=\"\n  SELECT\n  sysdate EXTRACT_DATE,\n  MP.organization_code,\n  MPL.planner_code,\n  MPL.description,\n  MPL.disable_date,\n  MPL.electronic_mail_address,\n  (SELECT\n    full_name\n  FROM APPS.PER_PEOPLE_F PPF\n  WHERE PPF.person_id = MPL.employee_id\n  AND rownum = 1)\n  PLANNER_NAME\nFROM\n  INV.MTL_PLANNERS MPL,\n  inv.mtl_parameters MP\nWHERE\n  MP.organization_id = MPL.organization_id\n  AND MP.organization_code = '\"&ORG&\"'\n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"PLANNER_CODE\", \"Planner Code\"}, {\"DESCRIPTION\", \"Planner Description\"}, {\"ELECTRONIC_MAIL_ADDRESS\", \"Planner Email Address\"}, {\"PLANNER_NAME\", \"Planner Name\"}, {\"DISABLE_DATE\", \"Disable Date\"}, {\"ORGANIZATION_CODE\", \"Organization Code\"}, {\"EXTRACT_DATE\", \"Extract Date\"}}),\r\n  ConvertToList = Table.AddColumn(#\"Renamed columns\", \"ClassCodeToList\", each Text.ToList([Planner Code])),\r\n  LowerCaseChars = {\"a\"..\"z\"},\r\n  // add Character.FromNumber(8203) to make the column unique\r\n  AddInvisibleChars = Table.AddColumn(ConvertToList, \"AddInvisibleChars\", each List.Transform(\n            [ClassCodeToList], \n            each \n            if \n            List.Contains(#\"LowerCaseChars\", _) \n            then \n            _ & Character.FromNumber(8203) \n            else _\n            )),\r\n  // Add case sensitive column as result of adding invisible characters Character.FromNumber(8203)\r\n  AddCaseSensitiveColumn = Table.AddColumn(AddInvisibleChars, \"Planner Code CS\", each Text.Combine([AddInvisibleChars])),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(AddCaseSensitiveColumn, {{\"Planner Code CS\", type text}}),\r\n  #\"Removed columns\" = Table.RemoveColumns(#\"Changed column type\", {\"ClassCodeToList\", \"AddInvisibleChars\"})\r\nin\r\n  #\"Removed columns\";\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"Sourcing_Rule","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Sourcing_Rule.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Sourcing Rule","dataType":"string"},{"name":"SOURCING_RULE_ID","dataType":"double"},{"name":"Sourcing Type","dataType":"string"},{"name":"Sourcing Org","dataType":"string"},{"name":"VENDOR_ID","dataType":"int64"},{"name":"Vendor Site","dataType":"string"},{"name":"Vendor Name","dataType":"string"},{"name":"VENDOR_SITE_ID","dataType":"int64"},{"name":"Country","dataType":"string"},{"name":"Country of Origin","dataType":"string"},{"name":"COO or Country","dataType":"string"},{"name":"Sourcing Org or Vendor","dataType":"string"},{"name":"Sourcing Allocation Percent","dataType":"double"},{"name":"Sourcing Vendor Inactive Date","dataType":"dateTime"},{"name":"Sourcing Vendor Site Inactive Date","dataType":"dateTime"},{"name":"Sourcing Org Inactive Date","dataType":"dateTime"},{"name":"Active Source Flag","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-05-20T05:06:16.1046099+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/e8ace12e-1a56-4195-8d82-033a4839503f/Sourcing_Rule.csv?snapshot=2022-05-20T05%3A06%3A16.0675376Z"}]},{"$type":"LocalEntity","name":"Planner","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Planner.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Organization Code","dataType":"string"},{"name":"Planner Code","dataType":"string"},{"name":"Planner Description","dataType":"string"},{"name":"Disable Date","dataType":"dateTime"},{"name":"Planner Email Address","dataType":"string"},{"name":"Planner Name","dataType":"string"},{"name":"Planner Code CS","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-05-20T05:06:19.8329578+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/e8ace12e-1a56-4195-8d82-033a4839503f/Planner.csv?snapshot=2022-05-20T05%3A06%3A19.8173596Z"}]}]}