{"name":"Mapping","description":"- nicht umbenennen !!! \nvon William / nur in seinem Dataset benutzt\n- refresh nicht notwendig - im Dataflow erstellte Tabellen","version":"1.0","culture":"en-US","modifiedTime":"2022-06-02T04:03:48.2101182+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":true,"queriesMetadata":{"Planner_Code_Mapping":{"queryId":"e8de7cdb-c0d9-4eb9-88dd-e5af4025752c","queryName":"Planner_Code_Mapping","loadEnabled":true},"Subinventory_Mapping":{"queryId":"01d58104-69a6-4ede-ae02-539f3d857865","queryName":"Subinventory_Mapping","loadEnabled":true},"Local_Item_Category":{"queryId":"ec892f56-867d-46a5-9171-d87657af6821","queryName":"Local_Item_Category","loadEnabled":true},"GL_Account_Mapping":{"queryId":"4e795055-17f6-4052-be76-aef01ec0626c","queryName":"GL_Account_Mapping","loadEnabled":true},"GL_Department_Mapping":{"queryId":"7efa4a76-2216-40b3-a426-29f067fa3262","queryName":"GL_Department_Mapping","loadEnabled":true}},"document":"section Section1;\r\nshared Planner_Code_Mapping = let\r\n  Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"hVnBjtw2DP0VYw89JSh2k03PskeeEcayXckezzbIIWgWRYFgE2zaQ/++EmV5bOnRuezY75kURVIUpf348a7/+vnl5fm1qL59eb57s7weX7/9+3313r9++/Lvn/8Uw3/fn+8+vfl49/7+UTu+aw7uLyGDHQrd9XaL9hKBGoCtyPVdZDV0ZouLZsg/fPj13f1jNjISd2NfVNcIKxPcYJzMIGKL10es3hQP94/AGl1UkzKZDuAcA770VuSom2IeB6cUWuBw+HE1vU31dqXtGjmkHjo55xTdmLjfm1Wct9jsyRT2vnc+6xlP1lu8FBdhlGiZsNYZ7i1JUZdpzXixeRJ4uMrj8fT2SRxz3wPYDYjQoPnx3UMWVYyH7x8+fIDfZ7iPrgtt6tnZhwC2ou9BHLzyQhzgoDmusc9bObYyz0mf00UeCAp9nRnYG2W1yGAtBqNAhcnheTYiMaQR7VE23QlrviYugYsTFwqJVqIGi2txW+Zl8K3BpQAp8H54ny5vaCsFwqHmnOMaYPTtFo457vPopIxcTY6lDEtRCOeJAo0MYRiCEu0MiCf8/RP3vV/LrFEcYziGCgamfIVhmbJsRsno4zhnBUtpltrFoYdqURrVygE7Ly54MKkdik0Es5cjHLWL4zkdi6PpSsW4nOOceSylWWoX58zj0x7AjMcko8VPkU1Fw0aGYzTH+HEYagdmPWJ8WWeKBMtpngsEHI6VIddxZFwpUKWXHNRATQ3iHFYLJrjYRr+8epZgjbCi7ocrIzdh/7Iyzr8s9xOCi/PPxKCJujiUTOX3+xEu/aZuhJHt1Rcpeiza68qQ+7BVV53uhbVu6197kSXdqmM536y451404qDaiM49OxZZuoDlIWiSJ1OLyrc4emwG1TdrX9xOAcC+0OnlZvj2DRLsdNquGKnvWB7WXVmdayrlYLQa/FYifx9Vr2U7rHcFLDXr61mTgYwY7cGMFTU6w0ma9SjUBHqZ8BSpsxjrll4PXdF2buMdn25iO6lCx4zcBDpmsLNBjOGY2TeUxWgUjrCI8AYwLoi2oSCcRDt0Pg9uT1Fm6eOXhzgfloEwFddSUSvsforGLpkmR59mckos7YGly8GizgaI+UduyTIwfBtcBswtTM74bQka7PckSPBoOKplauKxJ48UJiRDLG9bWBxVI4uDoCN/dfI7m03nDQNFavIUErI9SDO2x1zdnMVwGe9WLL1TbTWn0+wIhXl1ts9mZrvWDop2903doBnDgcaXzz9+/P3Xy/MXh4ytG0kdW7k+CeKQz6lTXIfIXYdECHOG56gyxQoVQdkXEPftoRevoW1zvQPlLr7TRpyS3k/iorw//U/R3BJTVZ33XvhZoLDcUnBKQL+mgbyEqIaoQag3Fytm66Bky7fmZm4YwiUgHN17YE7OrQ9oEwA5OFMV4sQfI8WcfleRCu9nwDhtnFCkKGlS0rmGk4sUltO8nN6TM7yc2ZGjHOW8skQoiZWfOQ4itxjn11tZT6gpX3daWqt96QZ7086KvIhGHZR0rEPoJZTz9dIhT6zTybqxZJ4uBKO2IfbX1Un1tx1CFoyeyBRoDRlWyvBSlPwP7yeY/vd0NVrDch8rLSh0zsqTbFTngeVhzry9w0EsgWdEHvniYVhqzq+QsDDDbglzS6TYMRVXsFFIZueZ1ZO+ZKhInXNKq3O2K66mnnrBVoexALGKGynjHpiqiwxf+cBA7pRua7J19bgcaGiKea7EsxhD07GLuPTUxfXn4dhGTHKCo7Yp6Np0UG7Usks9baW5qIouHZan6AB2xYReLExl24qZQ1FKO4jW9ynml81/DXzg0LFh3vgQZyumOQrl1aBd5tKZad7lNjM9N7Kkt6wGBgb37u5xUpX7wmwnRB0/5WEmEmI5cbEEuUt5M8HECLObmN2Gq3aaY2IccKFg4zAn25Ql2xwHWSlg4ZxR4Y6EyS7UYce9uQc6Q+o5FCTf3KBlyzziaeMTy0KKz/kAgxsdCOz2OI4FJgxHSI7QbPBmZZCSLMUtyRidnAmNxDDIZsc5uDhjht0ld3Z56e8079jbTnx5GcmeuWTnOcNz4Z+hmFsy1eSZiu33qtB9oseZy0msKJjMO4GdCTN4XaLL5ZlhrkBvZ8Ovn1+fl2FoNz+nMK3yh8ff0gX/6X8=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t, Column2 = _t, Column3 = _t]),\r\n  #\"Promoted headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars = true])\r\nin\r\n  #\"Promoted headers\";\r\nshared Subinventory_Mapping = let\r\n  Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"ddXJkqMwDADQX6FyDl3pLKRzNI4AFWAzsslkKtXF///FyCzdDjanoCeDd+X12uVC1kXTm2q332lbAe2+96+d1Mogy/hbKrhPSnBHm5BVLvUbjLne2ERICd3bh+7QaTtQR28K+EFggB7AXJQ4YQO1Ja2wZmyLMjV9Loz5NyYLIIuy8pqjMh2/gNoNpqV8RqupHKYRcgCkRJMS2J6UGVvUDeRAom8jndS6zdHroubZD4XIKVyKMYXPqfd1ildC4ZMT8OxAmdkbUYJbBhJ/59gMvApef43UlTWWhZ9+pFcrq/yP6BKNHZdsTceInTxrPyNL0B5jeIrhOYaXGGYxvMYQKirEuM3rlNIqkTSfPS9wuQ55acJX/vSiGRqRc8o9YoFSjOfFJWmZvWxAKNK6nfmw4Vvtj3Hf4FOcz3G+xDlLNwaTpRvdZulGx9c4f8X5FmfquIi4IblfVKWnx7U+bpGd4ptMtNyP5S6bh0zcWd3/PDm1y9Qt8K2Y5BBSpNUxoFBOgZxDSd1pih4qewlaZ4FcA/kK5LaWB5AR6u4Vi0JgYqQrq81UX0qUA5c88ojDksRcIxes59q+xFyHPqY6tEibIr2FrR9pZXmnPFHQK/BfIEA1l9iFjMT08OkDf8QdCk94l93kfsVCy/8eMFa/0b7/Aw==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Subinventory Name\" = _t, #\"Subinventory Group\" = _t])\r\nin\r\n  Source;\r\nshared Local_Item_Category = let\r\n  Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Item Number\" = _t, #\"Wavelength Color\" = _t, #\"Power Group\" = _t, #\"Measure Production Output\" = _t, #\"Measure Shipment OTD\" = _t, Wavelength = _t, Model = _t, #\"Forecast Type\" = _t, #\"Production Group\" = _t, #\"Forecast Group\" = _t])\r\nin\r\n  Source;\r\nshared GL_Account_Mapping = let\r\n  Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"GL Account Code\" = _t, #\"Account Category\" = _t, Nature = _t, #\"Account Group\" = _t])\r\nin\r\n  Source;\r\nshared GL_Department_Mapping = let\r\n  Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"GL Department Code\" = _t, #\"Department Product\" = _t, #\"Department Group\" = _t, #\"Department Alias\" = _t])\r\nin\r\n  Source;\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"Planner_Code_Mapping","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Planner_Code_Mapping.csv"},"attributes":[{"name":"Planner Code","dataType":"string"},{"name":"Planner Group","dataType":"string"},{"name":"Planner Product Type","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-02T04:00:42.7580382+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/6c63bf2c-beae-4ef6-af28-f57c1cc9b3e6/Planner_Code_Mapping.csv?snapshot=2022-06-02T04%3A00%3A42.3213607Z"}]},{"$type":"LocalEntity","name":"Subinventory_Mapping","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Subinventory_Mapping.csv"},"attributes":[{"name":"Subinventory Name","dataType":"string"},{"name":"Subinventory Group","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-02T04:00:41.6538408+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/6c63bf2c-beae-4ef6-af28-f57c1cc9b3e6/Subinventory_Mapping.csv?snapshot=2022-06-02T04%3A00%3A41.4628557Z"}]},{"$type":"LocalEntity","name":"Local_Item_Category","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Local_Item_Category.csv"},"attributes":[{"name":"Item Number","dataType":"string"},{"name":"Wavelength Color","dataType":"string"},{"name":"Power Group","dataType":"string"},{"name":"Measure Production Output","dataType":"string"},{"name":"Measure Shipment OTD","dataType":"string"},{"name":"Wavelength","dataType":"string"},{"name":"Model","dataType":"string"},{"name":"Forecast Type","dataType":"string"},{"name":"Production Group","dataType":"string"},{"name":"Forecast Group","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-02T04:00:43.1486945+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/6c63bf2c-beae-4ef6-af28-f57c1cc9b3e6/Local_Item_Category.csv?snapshot=2022-06-02T04%3A00%3A42.3693338Z"}]},{"$type":"LocalEntity","name":"GL_Account_Mapping","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"GL_Account_Mapping.csv"},"attributes":[{"name":"GL Account Code","dataType":"string"},{"name":"Account Category","dataType":"string"},{"name":"Nature","dataType":"string"},{"name":"Account Group","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-02T04:00:44.2268619+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/6c63bf2c-beae-4ef6-af28-f57c1cc9b3e6/GL_Account_Mapping.csv?snapshot=2022-06-02T04%3A00%3A44.1523070Z"}]},{"$type":"LocalEntity","name":"GL_Department_Mapping","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"GL_Department_Mapping.csv"},"attributes":[{"name":"GL Department Code","dataType":"string"},{"name":"Department Product","dataType":"string"},{"name":"Department Group","dataType":"string"},{"name":"Department Alias","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-02T04:00:43.0081161+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/6c63bf2c-beae-4ef6-af28-f57c1cc9b3e6/GL_Department_Mapping.csv?snapshot=2022-06-02T04%3A00%3A42.5732161Z"}]}]}