{"name":"lokale_Daten_QMonitor","description":"Daten vom SQL-Server \nNCR Fälle nach 01.01.2018","version":"1.0","culture":"en-US","modifiedTime":"2022-03-18T09:17:46.6436889+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"WEP_Auswertung":{"queryId":"91803993-0b7c-4f47-b72c-03f90cb2df06","queryName":"WEP_Auswertung","loadEnabled":true},"NCR_Faelle":{"queryId":"2be82907-6904-48af-8595-1325c50fdcd3","queryName":"NCR_Faelle","loadEnabled":true},"WEP_TeileImmerTesten":{"queryId":"76e2a2a4-238c-45a8-ab2b-d025bfbbfdf9","queryName":"WEP_TeileImmerTesten","loadEnabled":true},"QM_Faelle":{"queryId":"a89fce84-fd75-4a9d-8146-d8b9ad8a7527","queryName":"QM_Faelle","loadEnabled":true},"SNCR_Faelle":{"queryId":"cf4b88c3-d954-481f-acd1-aad03221f601","queryName":"SNCR_Faelle","loadEnabled":true},"WEP_Auswertung_abgeschlosseneReceipts":{"queryId":"a7915620-2a85-4876-8c9e-3efc9ebdf9b5","queryName":"WEP_Auswertung_abgeschlosseneReceipts","loadEnabled":true}},"document":"section Section1;\r\nshared WEP_Auswertung = let\r\n  Source = Sql.Database(\"lbksql_QMonitor\", \"lbk_QMonitor_DB\"),\r\n  #\"Navigation 1\" = Source{[Schema = \"dbo\", Item = \"S_PBI_WEPAuswertung\"]}[Data]\r\nin\r\n  #\"Navigation 1\";\r\nshared NCR_Faelle = let\r\n  Source = Sql.Database(\"lbksql_QMonitor\", \"lbk_QMonitor_DB\"),\r\n  #\"Navigation 1\" = Source{[Schema = \"dbo\", Item = \"S_PBI_NCR_Faelle\"]}[Data]\r\nin\r\n  #\"Navigation 1\";\r\nshared WEP_TeileImmerTesten = let\r\n  Source = Sql.Database(\"lbksql_QMonitor\", \"lbk_QMonitor_DB\"),\r\n  #\"Navigation 1\" = Source{[Schema = \"dbo\", Item = \"S_PBI_WEP_TeileImmerTesten\"]}[Data]\r\nin\r\n  #\"Navigation 1\";\r\nshared QM_Faelle = let\r\n  Source = Sql.Database(\"lbksql_QMonitor\", \"lbk_QMonitor_DB\"),\r\n  #\"Navigation 1\" = Source{[Schema = \"dbo\", Item = \"S_PBI_QM_Faelle\"]}[Data],\r\n  #\"Calculated date\" = Table.TransformColumns(#\"Navigation 1\", {{\"rekdat\", each DateTime.Date(_), type nullable date}, {\"rekAbschluss_am\", each DateTime.Date(_), type nullable date}, {\"SMN_festgelegt_am\", each DateTime.Date(_), type nullable date}, {\"Erfolgskontrolle_geplantbis\", each DateTime.Date(_), type nullable date}, {\"Erfolgskontrolle_am\", each DateTime.Date(_), type nullable date}, {\"Ursache_bearbeitet_am\", each DateTime.Date(_), type nullable date}, {\"SMN_abschluss_am\", each DateTime.Date(_), type nullable date}, {\"MN_festgelegt_am\", each DateTime.Date(_), type nullable date}, {\"MN_umgesetzt_bis\", each DateTime.Date(_), type nullable date}, {\"MN_umgesetzt_am\", each DateTime.Date(_), type nullable date}})\r\nin\r\n  #\"Calculated date\";\r\nshared SNCR_Faelle = let\r\n  Source = Sql.Database(\"lbksql_QMonitor\", \"lbk_QMonitor_DB\"),\r\n  #\"Navigation 1\" = Source{[Schema = \"dbo\", Item = \"S_PBI_SNCR_Faelle\"]}[Data]\r\nin\r\n  #\"Navigation 1\";\r\nshared WEP_Auswertung_abgeschlosseneReceipts = let\r\n  Source = Sql.Database(\"lbksql_QMonitor\", \"lbk_QMonitor_DB\"),\r\n  #\"Navigation 1\" = Source{[Schema = \"dbo\", Item = \"S_PBI_WEPAuswertung_abgeschlosseneReceipts\"]}[Data]\r\nin\r\n  #\"Navigation 1\";\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"WEP_Auswertung","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"WEP_Auswertung.csv"},"attributes":[{"name":"ROWNumber","dataType":"int64"},{"name":"ReceiptDate","dataType":"dateTime"},{"name":"getestetAm","dataType":"dateTime"},{"name":"ID_PruefAuftrag","dataType":"int64"},{"name":"ItemNumber","dataType":"string"},{"name":"QTYReceived","dataType":"int64"},{"name":"QTYRejected","dataType":"int64"},{"name":"QTYReturned","dataType":"int64"},{"name":"Supplier","dataType":"string"},{"name":"PruefAuftragErgebnis","dataType":"string"},{"name":"ReceiptNumber","dataType":"int64"},{"name":"erhalten","dataType":"dateTime"},{"name":"inBearbeitung","dataType":"dateTime"},{"name":"Bemerkung","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T02:30:18.4971285+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/fd60b3b7-f7e6-4d0c-9346-4a273575a1ba/WEP_Auswertung.csv?snapshot=2022-06-13T02%3A30%3A18.4094645Z"}]},{"$type":"LocalEntity","name":"NCR_Faelle","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"NCR_Faelle.csv"},"attributes":[{"name":"RekNum_","dataType":"string"},{"name":"rekdat","dataType":"dateTime"},{"name":"Model","dataType":"string"},{"name":"Komponente","dataType":"string"},{"name":"Abteilung","dataType":"string"},{"name":"teilenum","dataType":"string"},{"name":"Anzahl","dataType":"int64"},{"name":"Fehlerbild","dataType":"string"},{"name":"Modelgruppe","dataType":"string"},{"name":"Produktgruppe","dataType":"string"},{"name":"Lasertyp","dataType":"string"},{"name":"TeileNr_defekt","dataType":"string"},{"name":"NCRUrsache","dataType":"string"},{"name":"NCRUrsacheStufe1","dataType":"string"},{"name":"NCRUrsache_Beschreibung","dataType":"string"},{"name":"rekAbschluss_Am","dataType":"dateTime"},{"name":"Fehler_bem","dataType":"string"},{"name":"Aktion","dataType":"string"},{"name":"AgilePQM_Date","dataType":"dateTime"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T02:30:23.2876644+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/fd60b3b7-f7e6-4d0c-9346-4a273575a1ba/NCR_Faelle.csv?snapshot=2022-06-13T02%3A30%3A23.1797398Z"}]},{"$type":"LocalEntity","name":"WEP_TeileImmerTesten","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"WEP_TeileImmerTesten.csv"},"attributes":[{"name":"Item","dataType":"string"},{"name":"Bemerkung","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T02:30:19.8664646+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/fd60b3b7-f7e6-4d0c-9346-4a273575a1ba/WEP_TeileImmerTesten.csv?snapshot=2022-06-13T02%3A30%3A19.7337079Z"}]},{"$type":"LocalEntity","name":"QM_Faelle","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"QM_Faelle.csv"},"attributes":[{"name":"RekNum_","dataType":"string"},{"name":"Fehlerfall","dataType":"string"},{"name":"StatusBearbeitung","dataType":"string"},{"name":"Status","dataType":"string"},{"name":"rekdat","dataType":"date"},{"name":"rekAbschluss_am","dataType":"date"},{"name":"Produkt","dataType":"string"},{"name":"Kategorie","dataType":"string"},{"name":"Kurzbeschreibung","dataType":"string"},{"name":"Kunde_Lieferant","dataType":"string"},{"name":"SMN_festgelegt_am","dataType":"date"},{"name":"SMN_Beschreibung","dataType":"string"},{"name":"SMN_festgelegt_von","dataType":"string"},{"name":"SMN_abschluss_am","dataType":"date"},{"name":"SMN_abschluss_von","dataType":"string"},{"name":"Ursache_Beschreibung","dataType":"string"},{"name":"Ursache_bearbeitet_von","dataType":"string"},{"name":"Ursache_bearbeitet_am","dataType":"date"},{"name":"Ursache_Fehler_ermittelt","dataType":"string"},{"name":"MN_Beschreibung","dataType":"string"},{"name":"MN_festgelegt_am","dataType":"date"},{"name":"MN_festgelegt_von","dataType":"string"},{"name":"MN_umgesetzt_bis","dataType":"date"},{"name":"MN_umgesetzt_am","dataType":"date"},{"name":"MN_umgesetzt_von","dataType":"string"},{"name":"ErfolgsNachweis","dataType":"string"},{"name":"Erfolgskontrolle_geplantbis","dataType":"date"},{"name":"Erfolgskontrolle_am","dataType":"date"},{"name":"Erfolgskontrolle_von","dataType":"string"},{"name":"letzte Zugriff","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T02:30:19.5281307+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/fd60b3b7-f7e6-4d0c-9346-4a273575a1ba/QM_Faelle.csv?snapshot=2022-06-13T02%3A30%3A19.4138904Z"}]},{"$type":"LocalEntity","name":"SNCR_Faelle","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"SNCR_Faelle.csv"},"attributes":[{"name":"NCR_NUMBER","dataType":"string"},{"name":"SNCRTyp","dataType":"string"},{"name":"ID_QMonitor","dataType":"string"},{"name":"ID_PruefAuftrag","dataType":"int64"},{"name":"xCARNr","dataType":"string"},{"name":"SNCRerstellt_am","dataType":"dateTime"},{"name":"SNCRerstellt_von","dataType":"string"},{"name":"Kontaktaufnahme_am","dataType":"dateTime"},{"name":"Kontaktaufnahme_von","dataType":"string"},{"name":"SupplierRueckmeldung_bis","dataType":"dateTime"},{"name":"SupplierRueckmeldung_erhalten","dataType":"dateTime"},{"name":"SNCRabschluss_am","dataType":"dateTime"},{"name":"SNCRabschluss_von","dataType":"string"},{"name":"MRBTeam_Timestamp","dataType":"dateTime"},{"name":"MRBTeam_MA","dataType":"string"},{"name":"QtyReceived","dataType":"int64"},{"name":"QTYRejected","dataType":"int64"},{"name":"QTYReturned","dataType":"int64"},{"name":"SupplierNumber","dataType":"string"},{"name":"Supplier","dataType":"string"},{"name":"ITEM","dataType":"string"},{"name":"PONumber","dataType":"string"},{"name":"RMANumber","dataType":"string"},{"name":"DEFECT_DESCRIPTION","dataType":"string"},{"name":"SNCRCharge","dataType":"string"},{"name":"SupplierRueckmeldung","dataType":"string"},{"name":"SupplierRueckmeldung_erforderlich","dataType":"string"},{"name":"ItemGroup","dataType":"string"},{"name":"Part_Component","dataType":"string"},{"name":"SNCRFehlerGruppe","dataType":"string"},{"name":"RESPONSIBILITY","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T02:30:19.6530919+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/fd60b3b7-f7e6-4d0c-9346-4a273575a1ba/SNCR_Faelle.csv?snapshot=2022-06-13T02%3A30%3A19.5278252Z"}]},{"$type":"LocalEntity","name":"WEP_Auswertung_abgeschlosseneReceipts","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"WEP_Auswertung_abgeschlosseneReceipts.csv"},"attributes":[{"name":"ROWNumber","dataType":"int64"},{"name":"ItemNumber","dataType":"string"},{"name":"Supplier","dataType":"string"},{"name":"ReceiptDate","dataType":"dateTime"},{"name":"ID_PruefAuftrag","dataType":"int64"},{"name":"PruefAuftragErgebnis","dataType":"string"},{"name":"getestetAm","dataType":"dateTime"},{"name":"QTYReceived","dataType":"int64"},{"name":"Status","dataType":"string"},{"name":"ReceiptNumber","dataType":"int64"},{"name":"erhalten","dataType":"dateTime"},{"name":"inBearbeitung","dataType":"dateTime"},{"name":"Bemerkung","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T02:30:20.963036+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/fd60b3b7-f7e6-4d0c-9346-4a273575a1ba/WEP_Auswertung_abgeschlosseneReceipts.csv?snapshot=2022-06-13T02%3A30%3A20.4832796Z"}]}]}