{
    "name": "lokale_Daten_Interflex",
    "description": "",
    "version": "1.0",
    "culture": "en-US",
    "modifiedTime": "2022-04-16T10:25:42.1868066+00:00",
    "pbi:mashup": {
        "fastCombine": false,
        "allowNativeQueries": true,
        "queriesMetadata": {
            "g_Anzahl_proKST": {
                "queryId": "f302a37b-6f91-4877-8164-bef55333e6ec",
                "queryName": "g_Anzahl_proKST",
                "loadEnabled": true
            },
            "g_Anzahl_proKst_ungeplant_abwesend": {
                "queryId": "5233b3e7-30ff-4b31-8888-8c71a800867c",
                "queryName": "g_Anzahl_proKst_ungeplant_abwesend",
                "loadEnabled": true
            },
            "g_Anzahl_proKst_Gleitzeit_kleinerhalberTag": {
                "queryId": "c63fd342-a1bf-4dc2-9fba-701cfe841134",
                "queryName": "g_Anzahl_proKst_Gleitzeit_kleinerhalberTag",
                "loadEnabled": true
            },
            "g_Anzahl_proKst_auf100_gestempelt": {
                "queryId": "bb263c07-4654-4096-a386-c1106cc82a7b",
                "queryName": "g_Anzahl_proKst_auf100_gestempelt",
                "loadEnabled": true
            },
            "g_Anzahl_proKST_anwesend": {
                "queryId": "43f10aba-4a17-43ca-b3d1-a06d6a3b079d",
                "queryName": "g_Anzahl_proKST_anwesend",
                "loadEnabled": true
            },
            "g_Anzahl_proKst_abwesend": {
                "queryId": "cee6052f-cc8a-414e-842c-815b5d3a9a01",
                "queryName": "g_Anzahl_proKst_abwesend",
                "loadEnabled": true
            },
            "g_Anzahl_proKst_geliehen": {
                "queryId": "81c907b7-6bb4-475e-b44a-a5a91286101f",
                "queryName": "g_Anzahl_proKst_geliehen",
                "loadEnabled": true
            },
            "Produktivitaet_fuerPowerBI": {
                "queryId": "8b6d5863-0afe-4641-aaeb-3b2857bbefd6",
                "queryName": "Produktivitaet_fuerPowerBI",
                "loadEnabled": true
            },
            "gestempelteZeit_proKst": {
                "queryId": "c68402fa-6f1f-418f-993f-a7e4e70d641f",
                "queryName": "gestempelteZeit_proKst",
                "loadEnabled": true
            },
            "InterflexZeiten_Uebersicht": {
                "queryId": "e3005a68-e2fc-463c-890a-0c88208c35dc",
                "queryName": "InterflexZeiten_Uebersicht",
                "loadEnabled": true
            }
        },
        "document": "section Section1;\r\nshared g_Anzahl_proKST = let\r\n  Source = Sql.Database(\"lbksql_LBKZeitrueckmeldungenProd\", \"lbk_ZeitrueckmeldungenProd_DB\", [CommandTimeout = #duration(0, 0, 10, 0), Query = \"Select * From S0_AnzahlMA_proStammkst_proTag\"]),\r\n  #\"Calculated date\" = Table.TransformColumns(Source, {{\"Datum\", each DateTime.Date(_), type date}})\r\nin\r\n  #\"Calculated date\";\r\nshared g_Anzahl_proKst_ungeplant_abwesend = let\r\n  Source = Sql.Database(\"lbksql_LBKZeitrueckmeldungenProd\", \"lbk_ZeitrueckmeldungenProd_DB\", [CommandTimeout = #duration(0, 0, 10, 0), Query = \"Select * From S0_AnzahlMA_proStammkst_ungeplantAbwesend\"]),\r\n  #\"Calculated date\" = Table.TransformColumns(Source, {{\"Datum\", each DateTime.Date(_), type date}})\r\nin\r\n  #\"Calculated date\";\r\nshared g_Anzahl_proKst_Gleitzeit_kleinerhalberTag = let\r\n  Source = Sql.Database(\"lbksql_LBKZeitrueckmeldungenProd\", \"lbk_ZeitrueckmeldungenProd_DB\", [CommandTimeout = #duration(0, 0, 10, 0), Query = \"Select * From S0_AnzahlMA_proStammkst_Gleitzeit_kleinerhalberTag\"]),\r\n  #\"Calculated date\" = Table.TransformColumns(Source, {{\"Datum\", each DateTime.Date(_), type date}})\r\nin\r\n  #\"Calculated date\";\r\nshared g_Anzahl_proKst_auf100_gestempelt = let\r\n  Source = Sql.Database(\"lbksql_LBKZeitrueckmeldungenProd\", \"lbk_ZeitrueckmeldungenProd_DB\", [CommandTimeout = #duration(0, 0, 10, 0), Query = \"Select * From S0_AnzahlMA_proStammkst_gestempelteKst_100\"]),\r\n  #\"Calculated date\" = Table.TransformColumns(Source, {{\"Datum\", each DateTime.Date(_), type date}})\r\nin\r\n  #\"Calculated date\";\r\nshared g_Anzahl_proKST_anwesend = let\r\n  Source = Sql.Database(\"lbksql_LBKZeitrueckmeldungenProd\", \"lbk_ZeitrueckmeldungenProd_DB\", [CommandTimeout = #duration(0, 0, 10, 0), Query = \"Select * From S0_AnzahlMA_proStammkst_anwesend\"]),\r\n  #\"Calculated date\" = Table.TransformColumns(Source, {{\"Datum\", each DateTime.Date(_), type date}})\r\nin\r\n  #\"Calculated date\";\r\nshared g_Anzahl_proKst_abwesend = let\r\n  Source = Sql.Database(\"lbksql_LBKZeitrueckmeldungenProd\", \"lbk_ZeitrueckmeldungenProd_DB\", [CommandTimeout = #duration(0, 0, 10, 0), Query = \"Select * From S0_AnzahlMA_proStammkst_abwesend\"]),\r\n  #\"Calculated date\" = Table.TransformColumns(Source, {{\"Datum\", each DateTime.Date(_), type date}})\r\nin\r\n  #\"Calculated date\";\r\nshared g_Anzahl_proKst_geliehen = let\r\n  Source = Sql.Database(\"lbksql_LBKZeitrueckmeldungenProd\", \"lbk_ZeitrueckmeldungenProd_DB\", [CommandTimeout = #duration(0, 0, 10, 0), Query = \"Select * From S0_AnzahlMA_geliehen\"]),\r\n  #\"Calculated date\" = Table.TransformColumns(Source, {{\"Datum\", each DateTime.Date(_), type date}})\r\nin\r\n  #\"Calculated date\";\r\nshared Produktivitaet_fuerPowerBI = let\r\n  Source = Sql.Database(\"lbksql_Statistiken\", \"lbk_Statistiken_DB\", [CommandTimeout = #duration(0, 0, 10, 0), Query = \"Select * From S0_Produktivitaet_fuerPowerBI\"]),\r\n  #\"Calculated date\" = Table.TransformColumns(Source, {{\"StartDatum\", each DateTime.Date(_), type date}})\r\nin\r\n  #\"Calculated date\";\r\nshared gestempelteZeit_proKst = let\r\n  Source = Sql.Database(\"lbksql_LBKZeitrueckmeldungenProd\", \"lbk_ZeitrueckmeldungenProd_DB\", [CommandTimeout = #duration(0, 0, 10, 0), Query = \"Select * From S1_LDP_Prod_Daten_proKst_gestempelt\"]),\r\n  #\"Removed columns\" = Table.RemoveColumns(Source, {\"Date_gestempelteKst_ID\"}),\r\n  #\"Calculated date\" = Table.TransformColumns(#\"Removed columns\", {{\"Datum\", each DateTime.Date(_), type date}}),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Calculated date\", {{\"SumZeit_gestempelt\", \"SumZeit_gestempelt[h]\"}}),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Renamed columns\", {{\"gestempelte-Kostenstelle\", Int64.Type}})\r\nin\r\n  #\"Changed column type\";\r\nshared InterflexZeiten_Uebersicht = let\r\n  Source = Sql.Database(\"lbksql_LBKZeitrueckmeldungenProd\", \"lbk_ZeitrueckmeldungenProd_DB\", [CommandTimeout = #duration(0, 0, 10, 0), Query = \"Select * From S_InterflexZeiten_Uebersicht\"]),\r\n  #\"Calculated date\" = Table.TransformColumns(Source, {{\"Datum\", each DateTime.Date(_), type date}}),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Calculated date\", {{\"Kostenstelle\", Int64.Type}})\r\nin\r\n  #\"Changed column type\";\r\n"
    },
    "annotations": [
        {
            "name": "pbi:QueryGroups",
            "value": "[]"
        }
    ],
    "entities": [
        {
            "$type": "LocalEntity",
            "name": "g_Anzahl_proKST",
            "description": "",
            "pbi:refreshPolicy": {
                "$type": "FullRefreshPolicy",
                "location": "g_Anzahl_proKST.csv"
            },
            "attributes": [
                {
                    "name": "Datum",
                    "dataType": "date"
                },
                {
                    "name": "Stamm-Kostenstelle",
                    "dataType": "double"
                },
                {
                    "name": "AnzahLMA",
                    "dataType": "int64"
                },
                {
                    "name": "Bezeichnung",
                    "dataType": "string"
                },
                {
                    "name": "Date_StammKst_ID",
                    "dataType": "string"
                }
            ],
            "partitions": [
                {
                    "name": "FullRefreshPolicyPartition",
                    "refreshTime": "2022-05-20T00:01:17.6208704+00:00",
                    "location": "https://wabiwuscpcdsap1.blob.core.windows.net:443/e919a6ba-4d0b-4442-87c8-24c3784782f3/g_Anzahl_proKST.csv?snapshot=2022-05-20T00%3A01%3A17.5586957Z"
                }
            ]
        },
        {
            "$type": "LocalEntity",
            "name": "g_Anzahl_proKst_ungeplant_abwesend",
            "description": "",
            "pbi:refreshPolicy": {
                "$type": "FullRefreshPolicy",
                "location": "g_Anzahl_proKst_ungeplant_abwesend.csv"
            },
            "attributes": [
                {
                    "name": "Datum",
                    "dataType": "date"
                },
                {
                    "name": "Stamm-Kostenstelle",
                    "dataType": "double"
                },
                {
                    "name": "Stamm-Kst-Bezeichnung",
                    "dataType": "string"
                },
                {
                    "name": "AnzahlMA_ungeplant_abwesend",
                    "dataType": "int64"
                },
                {
                    "name": "Zeit_ungeplant_abwesend",
                    "dataType": "double"
                },
                {
                    "name": "Date_StammKst_ID",
                    "dataType": "string"
                }
            ],
            "partitions": [
                {
                    "name": "FullRefreshPolicyPartition",
                    "refreshTime": "2022-05-20T00:01:29.9253763+00:00",
                    "location": "https://wabiwuscpcdsap1.blob.core.windows.net:443/e919a6ba-4d0b-4442-87c8-24c3784782f3/g_Anzahl_proKst_ungeplant_abwesend.csv?snapshot=2022-05-20T00%3A01%3A29.8555640Z"
                }
            ]
        },
        {
            "$type": "LocalEntity",
            "name": "g_Anzahl_proKst_Gleitzeit_kleinerhalberTag",
            "description": "",
            "pbi:refreshPolicy": {
                "$type": "FullRefreshPolicy",
                "location": "g_Anzahl_proKst_Gleitzeit_kleinerhalberTag.csv"
            },
            "attributes": [
                {
                    "name": "Datum",
                    "dataType": "date"
                },
                {
                    "name": "Stamm-Kostenstelle",
                    "dataType": "double"
                },
                {
                    "name": "Stamm-Kst-Bezeichnung",
                    "dataType": "string"
                },
                {
                    "name": "AnzahLMA_Gleitzeit_kleiner_halberTag",
                    "dataType": "int64"
                },
                {
                    "name": "Fehlgrund-bez",
                    "dataType": "string"
                },
                {
                    "name": "Date_StammKst_ID",
                    "dataType": "string"
                }
            ],
            "partitions": [
                {
                    "name": "FullRefreshPolicyPartition",
                    "refreshTime": "2022-05-20T00:01:17.0271645+00:00",
                    "location": "https://wabiwuscpcdsap1.blob.core.windows.net:443/e919a6ba-4d0b-4442-87c8-24c3784782f3/g_Anzahl_proKst_Gleitzeit_kleinerhalberTag.csv?snapshot=2022-05-20T00%3A01%3A16.9960217Z"
                }
            ]
        },
        {
            "$type": "LocalEntity",
            "name": "g_Anzahl_proKst_auf100_gestempelt",
            "description": "",
            "pbi:refreshPolicy": {
                "$type": "FullRefreshPolicy",
                "location": "g_Anzahl_proKst_auf100_gestempelt.csv"
            },
            "attributes": [
                {
                    "name": "Datum",
                    "dataType": "date"
                },
                {
                    "name": "Stamm-Kostenstelle",
                    "dataType": "double"
                },
                {
                    "name": "AnzahlMA_Kst100",
                    "dataType": "int64"
                },
                {
                    "name": "gestempelte-Kostenstelle",
                    "dataType": "double"
                },
                {
                    "name": "Stamm-Kst-Bezeichnung",
                    "dataType": "string"
                },
                {
                    "name": "Date_StammKst_ID",
                    "dataType": "string"
                }
            ],
            "partitions": [
                {
                    "name": "FullRefreshPolicyPartition",
                    "refreshTime": "2022-05-20T00:01:21.452052+00:00",
                    "location": "https://wabiwuscpcdsap1.blob.core.windows.net:443/e919a6ba-4d0b-4442-87c8-24c3784782f3/g_Anzahl_proKst_auf100_gestempelt.csv?snapshot=2022-05-20T00%3A01%3A21.3784797Z"
                }
            ]
        },
        {
            "$type": "LocalEntity",
            "name": "g_Anzahl_proKST_anwesend",
            "description": "",
            "pbi:refreshPolicy": {
                "$type": "FullRefreshPolicy",
                "location": "g_Anzahl_proKST_anwesend.csv"
            },
            "attributes": [
                {
                    "name": "Datum",
                    "dataType": "date"
                },
                {
                    "name": "Stamm-Kostenstelle",
                    "dataType": "double"
                },
                {
                    "name": "Stamm-Kst-Bezeichnung",
                    "dataType": "string"
                },
                {
                    "name": "AnzahLMA_anwesend",
                    "dataType": "int64"
                },
                {
                    "name": "Zeit_anwesend",
                    "dataType": "double"
                },
                {
                    "name": "Date_StammKst_ID",
                    "dataType": "string"
                }
            ],
            "partitions": [
                {
                    "name": "FullRefreshPolicyPartition",
                    "refreshTime": "2022-05-20T00:01:30.0660045+00:00",
                    "location": "https://wabiwuscpcdsap1.blob.core.windows.net:443/e919a6ba-4d0b-4442-87c8-24c3784782f3/g_Anzahl_proKST_anwesend.csv?snapshot=2022-05-20T00%3A01%3A30.0114734Z"
                }
            ]
        },
        {
            "$type": "LocalEntity",
            "name": "g_Anzahl_proKst_abwesend",
            "description": "",
            "pbi:refreshPolicy": {
                "$type": "FullRefreshPolicy",
                "location": "g_Anzahl_proKst_abwesend.csv"
            },
            "attributes": [
                {
                    "name": "Datum",
                    "dataType": "date"
                },
                {
                    "name": "Stamm-Kostenstelle",
                    "dataType": "double"
                },
                {
                    "name": "Stamm-Kst-Bezeichnung",
                    "dataType": "string"
                },
                {
                    "name": "AnzahLMA_abwesend",
                    "dataType": "int64"
                },
                {
                    "name": "Zeit_abwesend",
                    "dataType": "double"
                },
                {
                    "name": "Date_StammKst_ID",
                    "dataType": "string"
                }
            ],
            "partitions": [
                {
                    "name": "FullRefreshPolicyPartition",
                    "refreshTime": "2022-05-20T00:01:21.7904859+00:00",
                    "location": "https://wabiwuscpcdsap1.blob.core.windows.net:443/e919a6ba-4d0b-4442-87c8-24c3784782f3/g_Anzahl_proKst_abwesend.csv?snapshot=2022-05-20T00%3A01%3A21.7542626Z"
                }
            ]
        },
        {
            "$type": "LocalEntity",
            "name": "g_Anzahl_proKst_geliehen",
            "description": "",
            "pbi:refreshPolicy": {
                "$type": "FullRefreshPolicy",
                "location": "g_Anzahl_proKst_geliehen.csv"
            },
            "attributes": [
                {
                    "name": "Datum",
                    "dataType": "date"
                },
                {
                    "name": "AnzahLMA_geliehen",
                    "dataType": "int64"
                },
                {
                    "name": "gestempelte-Kostenstelle",
                    "dataType": "double"
                },
                {
                    "name": "Bezeichnung",
                    "dataType": "string"
                },
                {
                    "name": "Date_gestempelteKst_ID",
                    "dataType": "string"
                }
            ],
            "partitions": [
                {
                    "name": "FullRefreshPolicyPartition",
                    "refreshTime": "2022-05-20T00:01:30.0972481+00:00",
                    "location": "https://wabiwuscpcdsap1.blob.core.windows.net:443/e919a6ba-4d0b-4442-87c8-24c3784782f3/g_Anzahl_proKst_geliehen.csv?snapshot=2022-05-20T00%3A01%3A30.0254660Z"
                }
            ]
        },
        {
            "$type": "LocalEntity",
            "name": "Produktivitaet_fuerPowerBI",
            "description": "",
            "pbi:refreshPolicy": {
                "$type": "FullRefreshPolicy",
                "location": "Produktivitaet_fuerPowerBI.csv"
            },
            "attributes": [
                {
                    "name": "ProductLine",
                    "dataType": "string"
                },
                {
                    "name": "StartDatum",
                    "dataType": "date"
                },
                {
                    "name": "gestempelteZeit",
                    "dataType": "double"
                },
                {
                    "name": "AnzahlLaser_inklFaktor",
                    "dataType": "double"
                },
                {
                    "name": "AnzahlLaser",
                    "dataType": "int64"
                },
                {
                    "name": "Prod_proWoche",
                    "dataType": "double"
                },
                {
                    "name": "Std_proLaser_proWoche",
                    "dataType": "double"
                },
                {
                    "name": "Prod_imMittel",
                    "dataType": "double"
                },
                {
                    "name": "Std_proLaser_imMittel",
                    "dataType": "double"
                },
                {
                    "name": "Ziel",
                    "dataType": "double"
                },
                {
                    "name": "Abteilung",
                    "dataType": "string"
                },
                {
                    "name": "Lasertyp",
                    "dataType": "string"
                }
            ],
            "partitions": [
                {
                    "name": "FullRefreshPolicyPartition",
                    "refreshTime": "2022-05-20T00:01:17.0583695+00:00",
                    "location": "https://wabiwuscpcdsap1.blob.core.windows.net:443/e919a6ba-4d0b-4442-87c8-24c3784782f3/Produktivitaet_fuerPowerBI.csv?snapshot=2022-05-20T00%3A01%3A17.0260040Z"
                }
            ]
        },
        {
            "$type": "LocalEntity",
            "name": "gestempelteZeit_proKst",
            "description": "",
            "pbi:refreshPolicy": {
                "$type": "FullRefreshPolicy",
                "location": "gestempelteZeit_proKst.csv"
            },
            "attributes": [
                {
                    "name": "Datum",
                    "dataType": "date"
                },
                {
                    "name": "gestempelte-Kostenstelle",
                    "dataType": "int64"
                },
                {
                    "name": "gestempelte-Produktgruppe",
                    "dataType": "string"
                },
                {
                    "name": "gestempelte-Abteilung",
                    "dataType": "string"
                },
                {
                    "name": "SumZeit_gestempelt[h]",
                    "dataType": "double"
                },
                {
                    "name": "fuerProduktivitaet",
                    "dataType": "boolean"
                }
            ],
            "partitions": [
                {
                    "name": "FullRefreshPolicyPartition",
                    "refreshTime": "2022-05-20T00:01:21.9311153+00:00",
                    "location": "https://wabiwuscpcdsap1.blob.core.windows.net:443/e919a6ba-4d0b-4442-87c8-24c3784782f3/gestempelteZeit_proKst.csv?snapshot=2022-05-20T00%3A01%3A21.8821882Z"
                }
            ]
        },
        {
            "$type": "LocalEntity",
            "name": "InterflexZeiten_Uebersicht",
            "description": "",
            "pbi:refreshPolicy": {
                "$type": "FullRefreshPolicy",
                "location": "InterflexZeiten_Uebersicht.csv"
            },
            "attributes": [
                {
                    "name": "Datum",
                    "dataType": "date"
                },
                {
                    "name": "Kostenstelle",
                    "dataType": "int64"
                },
                {
                    "name": "Produktgruppe",
                    "dataType": "string"
                },
                {
                    "name": "Abteilung",
                    "dataType": "string"
                },
                {
                    "name": "SumZeit_gestempelt",
                    "dataType": "double"
                },
                {
                    "name": "fuerProduktivitaet",
                    "dataType": "boolean"
                },
                {
                    "name": "AnzahLMA_abwesend",
                    "dataType": "int64"
                },
                {
                    "name": "AnzahLMA_Gleitzeit_kleiner_halberTag",
                    "dataType": "int64"
                },
                {
                    "name": "AnzahLMA_anwesend",
                    "dataType": "int64"
                },
                {
                    "name": "AnzahlMA_Kst100",
                    "dataType": "int64"
                },
                {
                    "name": "AnzahlMA_ungeplant_abwesend",
                    "dataType": "int64"
                },
                {
                    "name": "AnzahLMA_geliehen",
                    "dataType": "int64"
                },
                {
                    "name": "AnzahLMA_verliehen",
                    "dataType": "int64"
                }
            ],
            "partitions": [
                {
                    "name": "FullRefreshPolicyPartition",
                    "refreshTime": "2022-05-20T00:01:48.3547442+00:00",
                    "location": "https://wabiwuscpcdsap1.blob.core.windows.net:443/e919a6ba-4d0b-4442-87c8-24c3784782f3/InterflexZeiten_Uebersicht.csv?snapshot=2022-05-20T00%3A01%3A48.2988701Z"
                }
            ]
        }
    ]
}