{"name":"COHERENT_SNOWFLAKE_PLANNING","description":"01.06.22 - XXCOH_MP_Receipts für QM/QC\n22.02.22 - MRP_SCHEDULE_DATES_V für ORG_FORECAST","version":"1.0","culture":"en-US","modifiedTime":"2022-06-13T10:12:07.7471735+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"XXCOH_KANBAN_ESL":{"queryId":"5d6f6250-675a-414e-bf6f-7c2e3d9eb326","queryName":"XXCOH_KANBAN_ESL","loadEnabled":true},"Org":{"queryId":"b94cc95d-0885-46a0-97b6-e2989b02581f","queryName":"Org"},"XXREP_WIP_DISCRETE_JOBS_V":{"queryId":"d669802f-ace1-433b-825f-1b7a8281d4a7","queryName":"XXREP_WIP_DISCRETE_JOBS_V","loadEnabled":true},"MRP_SCHEDULE_DATES_V":{"queryId":"a6706ab5-bab0-4d5d-8a70-69e22d4e7b21","queryName":"MRP_SCHEDULE_DATES_V","loadEnabled":true},"XXREP_MFG_GROSS_REQUIREMENTS_V":{"queryId":"041231e7-b444-4580-a7b1-ebf24ed8da7c","queryName":"XXREP_MFG_GROSS_REQUIREMENTS_V","loadEnabled":true},"XXCOH_MP_RECEIPTS_VIEW":{"queryId":"8c17ac22-15e3-4c0e-8e40-ccbae37458f7","queryName":"XXCOH_MP_RECEIPTS_VIEW","loadEnabled":true},"Org_Code":{"queryId":"f03aa7fe-52fa-48b5-8d90-9635d99212fe","queryName":"Org_Code"},"first Date":{"queryId":"8e00866f-92fc-4023-a0c9-393496a64107","queryName":"first Date"}},"document":"section Section1;\r\nshared XXCOH_KANBAN_ESL = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 1\" = Navigation{[Name = \"XXCOH\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXCOH_KANBAN_ESL\", Kind = \"Table\"]}[Data],\r\n  #\"Filtered rows\" = Table.SelectRows(#\"Navigation 2\", each [ORG_ID] = Org),\r\n  #\"Filtered rows 1\" = Table.SelectRows(#\"Filtered rows\", each [CREATION_DATE] > #datetime(2021, 11, 1, 0, 0, 0))\r\nin\r\n  #\"Filtered rows 1\";\r\nshared Org = let\r\n  Org = 587 meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type any]\r\nin\r\n  Org;\r\nshared XXREP_WIP_DISCRETE_JOBS_V = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 1\" = Navigation{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXREP_WIP_DISCRETE_JOBS_V\", Kind = \"View\"]}[Data],\r\n  #\"Filtered rows\" = Table.SelectRows(#\"Navigation 2\", each [ORGANIZATION_ID] = Org),\r\n  #\"Filtered rows 1\" = Table.SelectRows(#\"Filtered rows\", each [CREATION_DATE] > #datetime(2021, 1, 1, 0, 0, 0))\r\nin\r\n  #\"Filtered rows 1\";\r\nshared MRP_SCHEDULE_DATES_V = let\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\n  #\"Navigation 1\" = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\n  #\"Navigation 3\" = #\"Navigation 2\"{[Name = \"MRP_SCHEDULE_DATES_V\", Kind = \"View\"]}[Data],\n  #\"Filtered rows\" = Table.SelectRows(#\"Navigation 3\", each  [SOURCE_CODE] = \"MRCSAL\" and ([SCHEDULE_DESIGNATOR] = \"LDP_MDS\")),\r\n  #\"Removed columns\" = Table.RemoveColumns(#\"Filtered rows\", {\"PROGRAM_UPDATE_DATE\", \"DDF_CONTEXT\", \"ATTRIBUTE_CATEGORY\", \"ATTRIBUTE1\", \"ATTRIBUTE2\", \"ATTRIBUTE3\", \"ATTRIBUTE4\", \"ATTRIBUTE5\", \"ATTRIBUTE6\", \"ATTRIBUTE7\", \"ATTRIBUTE8\", \"ATTRIBUTE9\", \"ATTRIBUTE10\", \"ATTRIBUTE11\", \"ATTRIBUTE12\", \"ATTRIBUTE13\", \"ATTRIBUTE14\", \"ATTRIBUTE15\", \"PROJECT_ID\", \"TASK_ID\", \"LINE_ID\", \"LINE_CODE\", \"END_ITEM_UNIT_NUMBER\"})\nin\n  #\"Removed columns\";\r\nshared XXREP_MFG_GROSS_REQUIREMENTS_V = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  #\"Navigation 1\" = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 3\" = #\"Navigation 2\"{[Name = \"XXREP_MFG_GROSS_REQUIREMENTS_V\", Kind = \"View\"]}[Data],\r\n  #\"Filtered rows\" = Table.SelectRows(#\"Navigation 3\", each [ORGANIZATION_ID] = Org)\r\nin\r\n  #\"Filtered rows\";\r\nshared XXCOH_MP_RECEIPTS_VIEW = let\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\n  Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\n  #\"Navigation 1\" = Navigation{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXCOH_MP_RECEIPTS_VIEW\", Kind = \"View\"]}[Data],\n  #\"Filtered rows -ORG_CODE\" = Table.SelectRows(#\"Navigation 2\", each List.Contains(Org_Code, [ORG_CODE])),\r\n  #\"Filtered rows-Transaction Date\" = Table.SelectRows(#\"Filtered rows -ORG_CODE\", each [TRANSACTION_DATE] >= #\"first Date\"),\n  #\"Removed columns\" = Table.RemoveColumns(#\"Filtered rows-Transaction Date\", {\"OPERATING_UNIT\", \"OPERATING_UNIT_ID\", \"LEGAL_ENTITY\", \"LEGAL_ENTITY_ID\", \"BUYER\", \"RECEIVER\", \"DELIVER_TO_PERSON\",\"COUNTRY_OF_ORIGIN_CODE\",\"DAYS_LATE_RECEIPT_ALLOWED\"}),\r\n  #\"Reordered columns\" = Table.ReorderColumns(#\"Removed columns\", {\"ASOF_DATE\", \"ASOF_DATE_DISP\", \"TRANSACTION_DATE\", \"DUE_DATE\", \"SHIPPING_DATE\", \"DESTINATION_TYPE_CODE\", \"INSPECTION_STATUS_CODE\", \"ROUTING_NAME\",\"TRANSACTION_TYPE\",\"DESTINATION_CONTEXT\",  \"RECEIPT_NUM\", \"SOURCE_DOCUMENT_CODE\", \"RECEIPT_COMMENTS\", \"RECEIPT_LINE_NUM\", \"NOTE_TO_RECEIVER\", \"ITEM_NUMBER\", \"ITEM_DESCRIPTION\", \"ITEM_REVISION\", \"ORDER_NUMBER\", \"ORDER_TYPE\", \"SOURCE_NAME\", \"ALTERNATE_SOURCE_NAME\", \"VENDOR_INTERNAL\", \"INTERDIV\", \"SOURCE_NUMBER\", \"LINE_NUMBER\", \"QUANTITY\", \"UNIT_OF_MEASURE\", \"PRIMARY_QUANTITY\", \"PRIMARY_UNIT_OF_MEASURE\", \"PO_SHIPMENT_NUMBER\", \"PO_SHIPMENT_QUANTITY\", \"ORDERED_QANTITY\", \"ORDERED_UNIT_OF_MEASURE\", \"UNIT_PRICE\", \"CURRENCY_CODE\", \"CURRENCY_CONVERSION_RATE\", \"OE_CURRENCY_CODE\", \"PO_CURRENCY_CODE\", \"RSH_CURRENCY_CODE\", \"ITEM_COST\", \"ITEM_ADD_BACK_COST\", \"MATERIAL_COST\", \"RESOURCE_COST\", \"MATERIAL_OVERHEAD_COST\", \"OVERHEAD_COST\", \"OUTSIDE_PROCESSING_COST\", \"UNBURDENED_COST\", \"PACKING_SLIP\", \"FREIGHT_CARRIER\", \"WAYBILL_AIRBILL_NUM\", \"NUM_OF_CONTAINERS\", \"FOB\", \"INSPECTON_QUALITY_CODE\", \"FROM_ORG_CODE\", \"FROM_OPERATING_UNIT\", \"FROM_FUNC_CURRENCY_CODE\",  \"REASON_CODE\",  \"TRANSACTION_CREATION_DATE\", \"DEFAULT_SUBINVENTORY\",\"SUBINVENTORY\", \"CURRENT_LOCATION\", \"ORG_CODE\", \"FUNC_CURRENCY_CODE\", \"DELIVER_TO_LOCATION\", \"FISCAL_PERIOD\", \"FISCAL_QUARTER\", \"FISCAL_YEAR\", \"FISCAL_WEEK\", \"TR_USD_RATE\", \"FC_USD_RATE\", \"PO_DESTINATION_TYPE_CODE\", \"WIP_ENTITY_NAME\", \"WIP_DESCRIPTION\", \"WIP_OPERATION_SEQ_NUM\", \"WIP_RESOURCE_SEQ_NUM\", \"QUANTITY_BILLED\", \"AMOUNT_BILLED\", \"PARENT_TRANSACTION_ID\", \"TRANSACTION_ID\", \"INV_TRANSACTION_ID\", \"PO_HEADER_ID\", \"PO_LINE_ID\", \"PO_LINE_LOCATION_ID\", \"PO_DISTRIBUTION_ID\", \"REQUISITION_LINE_ID\", \"SHIPMENT_HEADER_ID\", \"SHIPMENT_LINE_ID\", \"ITEM_ID\", \"FROM_ORGANIZATION_ID\", \"TO_ORGANIZATION_ID\", \"OE_ORDER_HEADER_ID\", \"OE_ORDER_LINE_ID\", \"WIP_ENTITY_ID\", \"ROW_CREATION_DATE\", \"USER_ENTERED_FLAG\"})\nin\n  #\"Reordered columns\";\r\nshared Org_Code = {\"LDP\", \"LDP\"} meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type list];\r\nshared #\"first Date\" = #datetime(2020, 1, 1, 0, 0, 0) meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type datetime];\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"XXCOH_KANBAN_ESL","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"XXCOH_KANBAN_ESL.csv"},"attributes":[{"name":"ORACLEINSTANCE","dataType":"string"},{"name":"ORG_ID","dataType":"double"},{"name":"ORG","dataType":"string"},{"name":"KANBANCARDID","dataType":"double"},{"name":"ESLCARDID","dataType":"string"},{"name":"ESLCARDACTION","dataType":"string"},{"name":"KANBANCARDNUM","dataType":"string"},{"name":"ITEM_ID","dataType":"double"},{"name":"ITEMNUM","dataType":"string"},{"name":"DESTSUBINV","dataType":"string"},{"name":"DESTLOCATOR","dataType":"string"},{"name":"CARDSTATUS","dataType":"string"},{"name":"SUPPLYSTATUS","dataType":"string"},{"name":"CARDTYPE","dataType":"string"},{"name":"SOURCETYPE","dataType":"string"},{"name":"KANBANSIZE","dataType":"double"},{"name":"CARD_LASTUPDATEDATE","dataType":"dateTime"},{"name":"CARD_LASTUPDATEBY_NAME","dataType":"string"},{"name":"CARD_CREATIONDATE","dataType":"dateTime"},{"name":"CARD_CREATEDBY_NAME","dataType":"string"},{"name":"SUPPLIER","dataType":"string"},{"name":"SUPPLIERSITE","dataType":"string"},{"name":"SOURCEORG","dataType":"string"},{"name":"SOURCESUBINV","dataType":"string"},{"name":"SOURCELOCATOR","dataType":"string"},{"name":"ERRORCODE","dataType":"string"},{"name":"CARDINFO","dataType":"string"},{"name":"NUMBEROFCARDS","dataType":"double"},{"name":"ESLCARDRELATIONSHIP","dataType":"string"},{"name":"BOXTYPE","dataType":"string"},{"name":"ITEMDESCR","dataType":"string"},{"name":"PLANNERCODE","dataType":"string"},{"name":"PLANNERDESCR","dataType":"string"},{"name":"PLANNERPERSON","dataType":"string"},{"name":"LASTREPLENISHDOCTYPE","dataType":"string"},{"name":"LASTREPLENISHDOCNUM","dataType":"string"},{"name":"LASTREPLENISHDOCLINE","dataType":"string"},{"name":"CREATION_DATE","dataType":"dateTime"},{"name":"SEQ_ID","dataType":"double"},{"name":"PULL_SEQ_INFO","dataType":"string"},{"name":"REQUEST_ID","dataType":"double"},{"name":"FILE_NAME","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T10:12:33.1960437+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/c91b4835-5a63-4330-94d7-c2c615a541cd/XXCOH_KANBAN_ESL.csv?snapshot=2022-06-13T10%3A12%3A33.1370794Z"}]},{"$type":"LocalEntity","name":"XXREP_WIP_DISCRETE_JOBS_V","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"XXREP_WIP_DISCRETE_JOBS_V.csv"},"attributes":[{"name":"ORGANIZATION_ID","dataType":"double"},{"name":"WIP_ENTITY_ID","dataType":"double"},{"name":"WIPJOB_ORG_KEY_CODE","dataType":"string"},{"name":"WIPJOB_ORG_KEY_ID","dataType":"string"},{"name":"LAST_UPDATE_DATE","dataType":"dateTime"},{"name":"LAST_UPDATED_BY","dataType":"double"},{"name":"CREATION_DATE","dataType":"dateTime"},{"name":"CREATED_BY","dataType":"double"},{"name":"DESCRIPTION","dataType":"string"},{"name":"STATUS_TYPE","dataType":"double"},{"name":"PRIMARY_ITEM_ID","dataType":"double"},{"name":"CLASS_CODE","dataType":"string"},{"name":"MATERIAL_ACCOUNT","dataType":"double"},{"name":"MATERIAL_OVERHEAD_ACCOUNT","dataType":"double"},{"name":"RESOURCE_ACCOUNT","dataType":"double"},{"name":"OUTSIDE_PROCESSING_ACCOUNT","dataType":"double"},{"name":"MATERIAL_VARIANCE_ACCOUNT","dataType":"double"},{"name":"RESOURCE_VARIANCE_ACCOUNT","dataType":"double"},{"name":"OUTSIDE_PROC_VARIANCE_ACCOUNT","dataType":"double"},{"name":"STD_COST_ADJUSTMENT_ACCOUNT","dataType":"double"},{"name":"OVERHEAD_ACCOUNT","dataType":"double"},{"name":"OVERHEAD_VARIANCE_ACCOUNT","dataType":"double"},{"name":"START_QUANTITY","dataType":"double"},{"name":"QUANTITY_REMAINING","dataType":"double"},{"name":"QUANTITY_COMPLETED","dataType":"double"},{"name":"QUANTITY_SCRAPPED","dataType":"double"},{"name":"NET_QUANTITY","dataType":"double"},{"name":"BOM_REFERENCE_ID","dataType":"double"},{"name":"ROUTING_REFERENCE_ID","dataType":"double"},{"name":"COMMON_BOM_SEQUENCE_ID","dataType":"double"},{"name":"COMMON_ROUTING_SEQUENCE_ID","dataType":"double"},{"name":"BOM_REVISION","dataType":"string"},{"name":"ROUTING_REVISION","dataType":"string"},{"name":"BOM_REVISION_DATE","dataType":"dateTime"},{"name":"ROUTING_REVISION_DATE","dataType":"dateTime"},{"name":"LOT_NUMBER","dataType":"string"},{"name":"ALTERNATE_BOM_DESIGNATOR","dataType":"string"},{"name":"ALTERNATE_ROUTING_DESIGNATOR","dataType":"string"},{"name":"COMPLETION_SUBINVENTORY","dataType":"string"},{"name":"COMPLETION_LOCATOR_ID","dataType":"double"},{"name":"SUB_LOCATOR_CONTROL","dataType":"double"},{"name":"SCHEDULE_GROUP_NAME","dataType":"string"},{"name":"SCHEDULE_GROUP_ID","dataType":"double"},{"name":"BUILD_SEQUENCE","dataType":"double"},{"name":"LINE_CODE","dataType":"string"},{"name":"LINE_ID","dataType":"double"},{"name":"PROJECT_ID","dataType":"double"},{"name":"TASK_ID","dataType":"double"},{"name":"END_ITEM_UNIT_NUMBER","dataType":"string"},{"name":"DEMAND_CLASS","dataType":"string"},{"name":"SCHEDULED_START_DATE","dataType":"dateTime"},{"name":"DATE_RELEASED","dataType":"dateTime"},{"name":"SCHEDULED_COMPLETION_DATE","dataType":"dateTime"},{"name":"DATE_COMPLETED","dataType":"dateTime"},{"name":"DATE_CLOSED","dataType":"dateTime"},{"name":"OVERCOMPLETION_TOLERANCE_VALUE","dataType":"double"},{"name":"KANBAN_CARD_ID","dataType":"double"},{"name":"KANBAN_CARD_NUMBER","dataType":"string"},{"name":"PO_CREATION_TIME","dataType":"double"},{"name":"PRIORITY","dataType":"double"},{"name":"DUE_DATE","dataType":"dateTime"},{"name":"EST_SCRAP_ACCOUNT","dataType":"double"},{"name":"EST_SCRAP_VAR_ACCOUNT","dataType":"double"},{"name":"ENTITY_TYPE","dataType":"double"},{"name":"DUE_DATE_PENALTY","dataType":"double"},{"name":"DUE_DATE_TOLERANCE","dataType":"double"},{"name":"COPRODUCTS_SUPPLY","dataType":"double"},{"name":"REQUESTED_START_DATE","dataType":"dateTime"},{"name":"SERIALIZATION_START_OP","dataType":"double"},{"name":"ACTUAL_START_DATE","dataType":"dateTime"},{"name":"EXPECTED_HOLD_RELEASE_DATE","dataType":"dateTime"},{"name":"INVORG_CODE","dataType":"string"},{"name":"ASSEMBLY_ITEM_NUMBER","dataType":"string"},{"name":"JOB_SOURCE","dataType":"string"},{"name":"JOB_STATUS_CODE","dataType":"double"},{"name":"JOB_STATUS","dataType":"string"},{"name":"WIP_SUPPLY_TYPE_CODE","dataType":"double"},{"name":"WIP_SUPPLY_TYPE","dataType":"string"},{"name":"JB_TYPE","dataType":"string"},{"name":"JOB_NUMBER","dataType":"string"},{"name":"JOB_DESCRIPTION","dataType":"string"},{"name":"FIRM_PLANNED_FLAG","dataType":"string"},{"name":"JOB_TYPE","dataType":"string"},{"name":"FIRST_UNIT_START_DATE","dataType":"dateTime"},{"name":"FIRST_UNIT_COMPLETION_DATE","dataType":"dateTime"},{"name":"LAST_UNIT_START_DATE","dataType":"dateTime"},{"name":"LAST_UNIT_COMPLETION_DATE","dataType":"dateTime"},{"name":"DATE_LAST_MOVED","dataType":"dateTime"},{"name":"PROJECT_NUMBER","dataType":"string"},{"name":"PROJECT_NAME","dataType":"string"},{"name":"SALES_ORDER_NO_DFF","dataType":"double"},{"name":"SALE_ORDER_LINE_NO_DFF","dataType":"double"},{"name":"SERVICE_REQUEST_DFF","dataType":"string"},{"name":"ASSEMBLY_SN_DFF","dataType":"string"},{"name":"CREATED_BY_LOGIN","dataType":"string"},{"name":"LAST_UPDATED_BY_LOGIN","dataType":"string"},{"name":"COMPLETION_LOCATOR","dataType":"string"},{"name":"LOCAL_EXTRACT_DATE","dataType":"dateTime"},{"name":"EXTRACT_DATE","dataType":"dateTime"},{"name":"DATA_UPDATE_DESC","dataType":"string"},{"name":"ITEM_NUMBER","dataType":"string"},{"name":"ITEM_DESCRIPTION","dataType":"string"},{"name":"ITEM_TYPE","dataType":"string"},{"name":"ITEM_ORG_KEY_ID","dataType":"string"},{"name":"ITEM_ORG_KEY_CODE","dataType":"string"},{"name":"PRODUCT_FAMILY","dataType":"string"},{"name":"FORECAST_FIELD","dataType":"string"},{"name":"PRODUCT_LINE","dataType":"string"},{"name":"TBU","dataType":"string"},{"name":"ORG_PRODUCT_FAMILY","dataType":"string"},{"name":"ORG_FORECAST_FIELD","dataType":"string"},{"name":"ORG_PRODUCT_LINE","dataType":"string"},{"name":"ORG_TBU","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T10:12:44.4767416+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/c91b4835-5a63-4330-94d7-c2c615a541cd/XXREP_WIP_DISCRETE_JOBS_V.csv?snapshot=2022-06-13T10%3A12%3A44.4395934Z"}]},{"$type":"LocalEntity","name":"MRP_SCHEDULE_DATES_V","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"MRP_SCHEDULE_DATES_V.csv"},"attributes":[{"name":"MPS_TRANSACTION_ID","dataType":"double"},{"name":"SCHEDULE_LEVEL","dataType":"double"},{"name":"RELIEF_FLAG","dataType":"string"},{"name":"SUPPLY_DEMAND_TYPE","dataType":"double"},{"name":"LAST_UPDATE_DATE","dataType":"dateTime"},{"name":"LAST_UPDATED_BY","dataType":"double"},{"name":"CREATION_DATE","dataType":"dateTime"},{"name":"CREATED_BY","dataType":"double"},{"name":"LAST_UPDATE_LOGIN","dataType":"double"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"ORGANIZATION_ID","dataType":"double"},{"name":"SCHEDULE_DESIGNATOR","dataType":"string"},{"name":"SCHEDULE_DATE","dataType":"dateTime"},{"name":"SCHEDULE_WORKDATE","dataType":"dateTime"},{"name":"RATE_END_DATE","dataType":"dateTime"},{"name":"SCHEDULE_QUANTITY","dataType":"double"},{"name":"ORIGINAL_QUANTITY","dataType":"double"},{"name":"REPETITIVE_DAILY_RATE","dataType":"double"},{"name":"QUANTITY_OR_RATE","dataType":"double"},{"name":"SCHEDULE_ORIGINATION_TYPE","dataType":"double"},{"name":"SCHEDULE_ORIGINATION_TEXT","dataType":"string"},{"name":"SOURCE_FORECAST_DESIGNATOR","dataType":"string"},{"name":"REFERENCE_SCHEDULE_ID","dataType":"double"},{"name":"SCHEDULE_COMMENTS","dataType":"string"},{"name":"SOURCE_ORGANIZATION_ID","dataType":"double"},{"name":"SOURCE_ORGANIZATION_CODE","dataType":"string"},{"name":"SOURCE_SCHEDULE_DESIGNATOR","dataType":"string"},{"name":"SOURCE_SALES_ORDER_ID","dataType":"double"},{"name":"SOURCE_DESIGNATOR","dataType":"string"},{"name":"SOURCE_CODE","dataType":"string"},{"name":"SOURCE_LINE_ID","dataType":"double"},{"name":"RESERVATION_ID","dataType":"double"},{"name":"FORECAST_ID","dataType":"double"},{"name":"REQUEST_ID","dataType":"double"},{"name":"PROGRAM_APPLICATION_ID","dataType":"double"},{"name":"PROGRAM_ID","dataType":"double"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T10:12:28.5182247+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/c91b4835-5a63-4330-94d7-c2c615a541cd/MRP_SCHEDULE_DATES_V.csv?snapshot=2022-06-13T10%3A12%3A28.4757534Z"}]},{"$type":"LocalEntity","name":"XXREP_MFG_GROSS_REQUIREMENTS_V","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"XXREP_MFG_GROSS_REQUIREMENTS_V.csv"},"attributes":[{"name":"EXTRACT_DATE","dataType":"dateTime"},{"name":"LOCAL_EXTRACT_DATE","dataType":"dateTime"},{"name":"PLAN_DATE","dataType":"dateTime"},{"name":"INVORG_TIMEZONE","dataType":"string"},{"name":"ORGANIZATION_CODE","dataType":"string"},{"name":"ORGANIZATION_ID","dataType":"double"},{"name":"ITEM_NUMBER","dataType":"string"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"ITEM_ORG_KEY_ID","dataType":"string"},{"name":"ITEM_ORG_KEY_CODE","dataType":"string"},{"name":"DEMAND_DATE","dataType":"dateTime"},{"name":"DEMAND_ORIGIN","dataType":"string"},{"name":"GROSS_REQUIREMENT_QUANTITY","dataType":"double"},{"name":"COMPILE_DESIGNATOR","dataType":"string"},{"name":"DEMAND_CLASS","dataType":"string"},{"name":"ITEM_TYPE","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T10:12:47.8204434+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/c91b4835-5a63-4330-94d7-c2c615a541cd/XXREP_MFG_GROSS_REQUIREMENTS_V.csv?snapshot=2022-06-13T10%3A12%3A47.7986646Z"}]},{"$type":"LocalEntity","name":"XXCOH_MP_RECEIPTS_VIEW","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"XXCOH_MP_RECEIPTS_VIEW.csv"},"attributes":[{"name":"ASOF_DATE","dataType":"date"},{"name":"ASOF_DATE_DISP","dataType":"dateTime"},{"name":"TRANSACTION_DATE","dataType":"dateTime"},{"name":"DUE_DATE","dataType":"dateTime"},{"name":"SHIPPING_DATE","dataType":"dateTime"},{"name":"DESTINATION_TYPE_CODE","dataType":"string"},{"name":"INSPECTION_STATUS_CODE","dataType":"string"},{"name":"ROUTING_NAME","dataType":"string"},{"name":"TRANSACTION_TYPE","dataType":"string"},{"name":"DESTINATION_CONTEXT","dataType":"string"},{"name":"RECEIPT_NUM","dataType":"string"},{"name":"SOURCE_DOCUMENT_CODE","dataType":"string"},{"name":"RECEIPT_COMMENTS","dataType":"string"},{"name":"RECEIPT_LINE_NUM","dataType":"double"},{"name":"NOTE_TO_RECEIVER","dataType":"string"},{"name":"ITEM_NUMBER","dataType":"string"},{"name":"ITEM_DESCRIPTION","dataType":"string"},{"name":"ITEM_REVISION","dataType":"string"},{"name":"ORDER_NUMBER","dataType":"string"},{"name":"ORDER_TYPE","dataType":"string"},{"name":"SOURCE_NAME","dataType":"string"},{"name":"ALTERNATE_SOURCE_NAME","dataType":"string"},{"name":"VENDOR_INTERNAL","dataType":"string"},{"name":"INTERDIV","dataType":"string"},{"name":"SOURCE_NUMBER","dataType":"double"},{"name":"LINE_NUMBER","dataType":"double"},{"name":"QUANTITY","dataType":"double"},{"name":"UNIT_OF_MEASURE","dataType":"string"},{"name":"PRIMARY_QUANTITY","dataType":"double"},{"name":"PRIMARY_UNIT_OF_MEASURE","dataType":"string"},{"name":"PO_SHIPMENT_NUMBER","dataType":"double"},{"name":"PO_SHIPMENT_QUANTITY","dataType":"double"},{"name":"ORDERED_QANTITY","dataType":"double"},{"name":"ORDERED_UNIT_OF_MEASURE","dataType":"string"},{"name":"UNIT_PRICE","dataType":"double"},{"name":"CURRENCY_CODE","dataType":"string"},{"name":"CURRENCY_CONVERSION_RATE","dataType":"double"},{"name":"OE_CURRENCY_CODE","dataType":"string"},{"name":"PO_CURRENCY_CODE","dataType":"string"},{"name":"RSH_CURRENCY_CODE","dataType":"string"},{"name":"ITEM_COST","dataType":"double"},{"name":"ITEM_ADD_BACK_COST","dataType":"double"},{"name":"MATERIAL_COST","dataType":"double"},{"name":"RESOURCE_COST","dataType":"double"},{"name":"MATERIAL_OVERHEAD_COST","dataType":"double"},{"name":"OVERHEAD_COST","dataType":"double"},{"name":"OUTSIDE_PROCESSING_COST","dataType":"double"},{"name":"UNBURDENED_COST","dataType":"double"},{"name":"PACKING_SLIP","dataType":"string"},{"name":"FREIGHT_CARRIER","dataType":"string"},{"name":"WAYBILL_AIRBILL_NUM","dataType":"string"},{"name":"NUM_OF_CONTAINERS","dataType":"double"},{"name":"FOB","dataType":"string"},{"name":"INSPECTON_QUALITY_CODE","dataType":"string"},{"name":"FROM_ORG_CODE","dataType":"string"},{"name":"FROM_OPERATING_UNIT","dataType":"string"},{"name":"FROM_FUNC_CURRENCY_CODE","dataType":"string"},{"name":"REASON_CODE","dataType":"string"},{"name":"TRANSACTION_CREATION_DATE","dataType":"dateTime"},{"name":"DEFAULT_SUBINVENTORY","dataType":"string"},{"name":"SUBINVENTORY","dataType":"string"},{"name":"CURRENT_LOCATION","dataType":"string"},{"name":"ORG_CODE","dataType":"string"},{"name":"FUNC_CURRENCY_CODE","dataType":"string"},{"name":"DELIVER_TO_LOCATION","dataType":"string"},{"name":"FISCAL_PERIOD","dataType":"double"},{"name":"FISCAL_QUARTER","dataType":"double"},{"name":"FISCAL_YEAR","dataType":"double"},{"name":"FISCAL_WEEK","dataType":"double"},{"name":"TR_USD_RATE","dataType":"double"},{"name":"FC_USD_RATE","dataType":"double"},{"name":"PO_DESTINATION_TYPE_CODE","dataType":"string"},{"name":"WIP_ENTITY_NAME","dataType":"string"},{"name":"WIP_DESCRIPTION","dataType":"string"},{"name":"WIP_OPERATION_SEQ_NUM","dataType":"double"},{"name":"WIP_RESOURCE_SEQ_NUM","dataType":"double"},{"name":"QUANTITY_BILLED","dataType":"double"},{"name":"AMOUNT_BILLED","dataType":"double"},{"name":"PARENT_TRANSACTION_ID","dataType":"double"},{"name":"TRANSACTION_ID","dataType":"double"},{"name":"INV_TRANSACTION_ID","dataType":"double"},{"name":"PO_HEADER_ID","dataType":"double"},{"name":"PO_LINE_ID","dataType":"double"},{"name":"PO_LINE_LOCATION_ID","dataType":"double"},{"name":"PO_DISTRIBUTION_ID","dataType":"double"},{"name":"REQUISITION_LINE_ID","dataType":"double"},{"name":"SHIPMENT_HEADER_ID","dataType":"double"},{"name":"SHIPMENT_LINE_ID","dataType":"double"},{"name":"ITEM_ID","dataType":"double"},{"name":"FROM_ORGANIZATION_ID","dataType":"double"},{"name":"TO_ORGANIZATION_ID","dataType":"double"},{"name":"OE_ORDER_HEADER_ID","dataType":"double"},{"name":"OE_ORDER_LINE_ID","dataType":"double"},{"name":"WIP_ENTITY_ID","dataType":"double"},{"name":"ROW_CREATION_DATE","dataType":"dateTime"},{"name":"USER_ENTERED_FLAG","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T10:13:30.5020095+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/c91b4835-5a63-4330-94d7-c2c615a541cd/XXCOH_MP_RECEIPTS_VIEW.csv?snapshot=2022-06-13T10%3A13%3A30.4551869Z"}]}]}