{"name":"lokale_Daten_Service","description":"","version":"1.0","culture":"en-US","modifiedTime":"2022-06-08T04:54:17.3509323+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":true,"queriesMetadata":{"SVC_TAT_Target (xls-InputFolder)":{"queryId":"f95d490f-eb55-4dd1-af75-71a37ff92658","queryName":"SVC_TAT_Target (xls-InputFolder)","loadEnabled":true},"PaladinProdplan_Daten":{"queryId":"35f4ef5b-2d7a-4974-9af7-d45347bd411b","queryName":"PaladinProdplan_Daten","loadEnabled":true},"ServiceDaten_Verzoegerungsgruende":{"queryId":"b1b591aa-84bd-4724-a958-77a37b7716db","queryName":"ServiceDaten_Verzoegerungsgruende","loadEnabled":true},"ServiceDaten_POs_Summe":{"queryId":"062aedec-a234-4beb-8ce5-186e230defc7","queryName":"ServiceDaten_POs_Summe","loadEnabled":true},"ServiceDaten_RepairReport":{"queryId":"f27556bc-336b-4579-894b-19153243df8e","queryName":"ServiceDaten_RepairReport","loadEnabled":true},"ServiceDaten_zurID":{"queryId":"7dc262b8-1705-4b6d-b382-f3e27e2caddd","queryName":"ServiceDaten_zurID","loadEnabled":true},"ServiceDaten_KomponentenEbene":{"queryId":"6851ba42-20d7-4a4d-838c-aa6a6c67b528","queryName":"ServiceDaten_KomponentenEbene","loadEnabled":true},"ServiceDaten_FehlerEintragIntern":{"queryId":"7662dc1f-8009-4b9e-903c-c3c39b043092","queryName":"ServiceDaten_FehlerEintragIntern","loadEnabled":true},"ServiceDaten_FehlerEintraganKunde":{"queryId":"41e2ae80-43fa-4dbe-abd6-748c7ac1249c","queryName":"ServiceDaten_FehlerEintraganKunde","loadEnabled":true}},"document":"section Section1;\r\nshared #\"SVC_TAT_Target (xls-InputFolder)\" = let\r\n  // xls-File mit den Daten liegt im\r\n  // Folder:\r\n  // '\\\\cohr\\eu\\delbc\\groups\\Operations\\Statistiken\\Input\r\n  // FileName:\r\n  // PowerBI_MappingData.xlsx\r\n  Source = Excel.Workbook(File.Contents(\"\\\\cohr\\eu\\delbc\\groups\\Operations\\Statistiken\\Input\\MappingData\\PowerBI_MappingData_SVC.xlsx\"), null, true),\r\n  Navigation = Source{[Item = \"SVC_TAT_Target\", Kind = \"Sheet\"]}[Data],\r\n  #\"Promoted headers\" = Table.PromoteHeaders(Navigation, [PromoteAllScalars = true]),\r\n  #\"Reordered columns\" = Table.ReorderColumns(#\"Promoted headers\", {\"TAT Group\", \"TAT Lasertyp\", \"TAT Target Businessdays\", \"TAT Kalendertage\", \"customer\", \"remark\"}),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Reordered columns\", {{\"TAT Kalendertage\", Int64.Type}, {\"TAT Target Businessdays\", Int64.Type}, {\"TAT Lasertyp\", type text}, {\"TAT Group\", type text}, {\"customer\", type text}, {\"remark\", type text}}),\r\n  #\"Filtered rows\" = Table.SelectRows(#\"Changed column type\", each [TAT Lasertyp] <> null),\r\n  #\"Sorted rows\" = Table.Sort(#\"Filtered rows\", {{\"TAT Group\", Order.Ascending}})\r\nin\r\n  #\"Sorted rows\";\r\nshared PaladinProdplan_Daten = let\r\n  Source = Sql.Database(\"lbksql_Produktionsplaene\", \"Lbk_Produktionsplaene_DB\", [Query = \"Select RepID,PN,lasertyp,Soll_start,Soll_RRDate,in_den_endtest,Testende_plus_OATage,  versendet  FROM S_PBI_PaladinProdplan WHERE (repid>0) AND (Testende_plus_OATage Is Not Null) and [aktuell] =1\"]),\r\n  #\"Calculated date\" = Table.TransformColumns(Source, {{\"Soll_start\", each DateTime.Date(_), type date},  {\"Soll_RRDate\", each DateTime.Date(_), type nullable date},{\"in_den_endtest\", each DateTime.Date(_), type date}, {\"Testende_plus_OATage\", each DateTime.Date(_), type date},  {\"versendet\", each DateTime.Date(_), type date}})\r\nin\r\n  #\"Calculated date\";\r\nshared ServiceDaten_Verzoegerungsgruende = let\r\n  // Daten aus der Reparatur-Datenbank ab 2011\r\n  // einieg Lasertypen rausgefiltert\r\n  Source = Sql.Database(\"lbksql_Service\", \"Lbk_Service_DB\", [Query = \"Select * From S_PBI_RepDaten_Verzoegerungsgruende\"])\r\nin\r\n  Source;\r\nshared ServiceDaten_POs_Summe = let\r\n  // Zuordnung der WIP-Job Nummer zu einer echten TeileNr\r\n  // da manchmal z.B. #1072480 Evaluation/ Repair PALADIN als Teilenummer genommen wird\r\n  Source = Sql.Database(\"lbksql_Service\", \"Lbk_Service_DB\", [Query = \"Select * From S_PBI_RepDaten_POs_SumBetrag\"]),\r\n  #\"Replaced value\" = Table.ReplaceValue(Source, null, 0, Replacer.ReplaceValue, {\"AnzahlPOs_not_received\"})\r\nin\r\n  #\"Replaced value\";\r\nshared ServiceDaten_RepairReport = let\r\n  // Zuordnung der WIP-Job Nummer zu einer echten TeileNr\r\n  // da manchmal z.B. #1072480 Evaluation/ Repair PALADIN als Teilenummer genommen wird\r\n  Source = Sql.Database(\"lbksql_Service\", \"Lbk_Service_DB\", [Query = \"Select * From S_PBI_RepDaten_RepairReport\"])\r\nin\r\n  Source;\r\nshared ServiceDaten_zurID = let\r\n  // Daten aus der Reparatur-Datenbank ab 2011\r\n  // einieg Lasertypen rausgefiltert\r\n  Source = Sql.Database(\"lbksql_Service\", \"Lbk_Service_DB\", [Query = \"Select * From S_PBI_RepDaten_ServiceID_Daten\"]),\r\n  #\"Calculated date\" = Table.TransformColumns(Source, {{\"Received\", each DateTime.Date(_), type nullable date}, {\"finished\", each DateTime.Date(_), type nullable date}, {\"SRReportedDate\", each DateTime.Date(_), type nullable date}}),\r\n  #\"Sorted rows\" = Table.Sort(#\"Calculated date\", {{\"Received\", Order.Descending}}),\r\n  #\"Reordered columns\" = Table.ReorderColumns(#\"Sorted rows\", {\"ServiceID\", \"Lasertyp\", \"SRHauptKomponente\", \"Customer\", \"SR\", \"SRTyp\", \"RMA\", \"CustomerRefNr\", \"CustomerPO\", \"entitlement\", \"NMR\", \"SRReportedDate\", \"Received\", \"finished\", \"RepIn\"})\r\nin\r\n  #\"Reordered columns\";\r\nshared ServiceDaten_KomponentenEbene = let\r\n  // Daten aus der Reparatur-Datenbank ab 2011\r\n  // einieg Lasertypen rausgefiltert\r\n  Source = Sql.Database(\"lbksql_Service\", \"Lbk_Service_DB\", [Query = \"Select * From S_PBI_RepDaten_Komponentenebene\"]),\r\n  #\"Calculated date 1\" = Table.TransformColumns(Source, {{\"promisedDate\", each DateTime.Date(_), type nullable date}, {\"scheduledDate\", each DateTime.Date(_), type nullable date}, {\"Lager\", each DateTime.Date(_), type nullable date}, {\"SPG\", each DateTime.Date(_), type nullable date}, {\"Admin I\", each DateTime.Date(_), type nullable date}, {\"Service I\", each DateTime.Date(_), type nullable date}, {\"Test I\", each DateTime.Date(_), type nullable date}, {\"Reinraum\", each DateTime.Date(_), type nullable date}, {\"E-Prod\", each DateTime.Date(_), type nullable date}, {\"Extern\", each DateTime.Date(_), type nullable date}, {\"ME\", each DateTime.Date(_), type nullable date}, {\"Test II\", each DateTime.Date(_), type nullable date}, {\"Service II\", each DateTime.Date(_), type nullable date}, {\"Admin II\", each DateTime.Date(_), type nullable date}, {\"OA_Extern II\", each DateTime.Date(_), type nullable date}, {\"OA_Extern I\", each DateTime.Date(_), type nullable date}, {\"Lager II\", each DateTime.Date(_), type nullable date}, {\"finished\", each DateTime.Date(_), type nullable date}, {\"ersteAuslieferungsdatum\", each DateTime.Date(_), type nullable date}, {\"letzteAuslieferungsDatum\", each DateTime.Date(_), type nullable date}, {\"ActualShipDate\", each DateTime.Date(_), type nullable date}})\r\nin\r\n  #\"Calculated date 1\";\r\nshared ServiceDaten_FehlerEintragIntern = let\r\n  // Daten aus der Reparatur-Datenbank ab 2011\r\n  // einieg Lasertypen rausgefiltert\r\n  Source = Sql.Database(\"lbksql_Service\", \"Lbk_Service_DB\", [Query = \"Select * From S_PBI_RepDaten_FehlerEintragIntern\"])\r\nin\r\n  Source;\r\nshared ServiceDaten_FehlerEintraganKunde = let\r\n  // Daten aus der Reparatur-Datenbank ab 2011\r\n  // einieg Lasertypen rausgefiltert\r\n  Source = Sql.Database(\"lbksql_Service\", \"Lbk_Service_DB\", [Query = \"Select * From S_PBI_RepDaten_FehlerEintragAnKunde\"])\r\nin\r\n  Source;\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"SVC_TAT_Target (xls-InputFolder)","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"SVC_TAT_Target%20%28xls-InputFolder%29.csv"},"attributes":[{"name":"TAT Group","dataType":"string"},{"name":"TAT Lasertyp","dataType":"string"},{"name":"TAT Target Businessdays","dataType":"int64"},{"name":"TAT Kalendertage","dataType":"int64"},{"name":"customer","dataType":"string"},{"name":"remark","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T04:01:22.0047386+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/c8374a80-644a-4f11-8957-e45cf31acc76/SVC_TAT_Target%20(xls-InputFolder).csv?snapshot=2022-06-13T04%3A01%3A21.4913255Z"}]},{"$type":"LocalEntity","name":"PaladinProdplan_Daten","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"PaladinProdplan_Daten.csv"},"attributes":[{"name":"RepID","dataType":"int64"},{"name":"PN","dataType":"double"},{"name":"lasertyp","dataType":"string"},{"name":"Soll_start","dataType":"date"},{"name":"Soll_RRDate","dataType":"date"},{"name":"in_den_endtest","dataType":"date"},{"name":"Testende_plus_OATage","dataType":"date"},{"name":"versendet","dataType":"date"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T04:01:17.7867777+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/c8374a80-644a-4f11-8957-e45cf31acc76/PaladinProdplan_Daten.csv?snapshot=2022-06-13T04%3A01%3A17.6455294Z"}]},{"$type":"LocalEntity","name":"ServiceDaten_Verzoegerungsgruende","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"ServiceDaten_Verzoegerungsgruende.csv"},"attributes":[{"name":"RepID","dataType":"int64"},{"name":"Feldname","dataType":"string"},{"name":"Verzoegerungsgrund","dataType":"string"},{"name":"Bemerkungsfeld","dataType":"string"},{"name":"EintragAm","dataType":"dateTime"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T04:01:18.930118+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/c8374a80-644a-4f11-8957-e45cf31acc76/ServiceDaten_Verzoegerungsgruende.csv?snapshot=2022-06-13T04%3A01%3A18.7249111Z"}]},{"$type":"LocalEntity","name":"ServiceDaten_POs_Summe","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"ServiceDaten_POs_Summe.csv"},"attributes":[{"name":"ServiceID","dataType":"int64"},{"name":"PO_GesamtBetragUSD","dataType":"double"},{"name":"AnzahlPOs_not_received","dataType":"double"},{"name":"PO_Status","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T04:01:18.4926542+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/c8374a80-644a-4f11-8957-e45cf31acc76/ServiceDaten_POs_Summe.csv?snapshot=2022-06-13T04%3A01%3A18.0872777Z"}]},{"$type":"LocalEntity","name":"ServiceDaten_RepairReport","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"ServiceDaten_RepairReport.csv"},"attributes":[{"name":"ServiceID","dataType":"int64"},{"name":"Bemerkungen","dataType":"string"},{"name":"Fehlerursache","dataType":"string"},{"name":"interne_Bemerkung","dataType":"string"},{"name":"SR_Fehlerursache_ltKunde","dataType":"string"},{"name":"RR_SR_Fehler_ltEingangstest","dataType":"string"},{"name":"RR_SR_ReparaturMaßnahmen","dataType":"string"},{"name":"RR_SR_VorbeugendeMaßnahme","dataType":"string"},{"name":"RR_SR_ContainmentAction","dataType":"string"},{"name":"RR_SR_RootCause","dataType":"string"},{"name":"AnalyseStatus","dataType":"string"},{"name":"Refurbishment","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T04:01:27.0210181+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/c8374a80-644a-4f11-8957-e45cf31acc76/ServiceDaten_RepairReport.csv?snapshot=2022-06-13T04%3A01%3A26.8672414Z"}]},{"$type":"LocalEntity","name":"ServiceDaten_zurID","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"ServiceDaten_zurID.csv"},"attributes":[{"name":"ServiceID","dataType":"int64"},{"name":"Lasertyp","dataType":"string"},{"name":"SRHauptKomponente","dataType":"string"},{"name":"Customer","dataType":"string"},{"name":"SR","dataType":"string"},{"name":"SRTyp","dataType":"string"},{"name":"WIP-Job","dataType":"string"},{"name":"RMA","dataType":"string"},{"name":"CustomerRefNr","dataType":"string"},{"name":"CustomerPO","dataType":"string"},{"name":"entitlement","dataType":"string"},{"name":"NMR","dataType":"boolean"},{"name":"SRItem","dataType":"string"},{"name":"SRReportedDate","dataType":"date"},{"name":"Received","dataType":"date"},{"name":"finished","dataType":"date"},{"name":"RepIn","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T04:01:21.5672374+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/c8374a80-644a-4f11-8957-e45cf31acc76/ServiceDaten_zurID.csv?snapshot=2022-06-13T04%3A01%3A21.3054315Z"}]},{"$type":"LocalEntity","name":"ServiceDaten_KomponentenEbene","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"ServiceDaten_KomponentenEbene.csv"},"attributes":[{"name":"RepID","dataType":"int64"},{"name":"ServiceID","dataType":"int64"},{"name":"PN","dataType":"int64"},{"name":"ITEM","dataType":"string"},{"name":"System","dataType":"string"},{"name":"Komponente","dataType":"string"},{"name":"SN","dataType":"string"},{"name":"Hauptkomponente","dataType":"boolean"},{"name":"promisedDate","dataType":"date"},{"name":"scheduledDate","dataType":"date"},{"name":"Betriebsstd","dataType":"double"},{"name":"BetriebsstdDelta","dataType":"double"},{"name":"Lager","dataType":"date"},{"name":"SPG","dataType":"date"},{"name":"Admin I","dataType":"date"},{"name":"OA_Extern I","dataType":"date"},{"name":"Service I","dataType":"date"},{"name":"Test I","dataType":"date"},{"name":"Reinraum","dataType":"date"},{"name":"E-Prod","dataType":"date"},{"name":"Extern","dataType":"date"},{"name":"ME","dataType":"date"},{"name":"Test II","dataType":"date"},{"name":"Service II","dataType":"date"},{"name":"Admin II","dataType":"date"},{"name":"OA_Extern II","dataType":"date"},{"name":"Lager II","dataType":"date"},{"name":"finished","dataType":"date"},{"name":"Aktualisierung","dataType":"dateTime"},{"name":"nicht Auswerten","dataType":"boolean"},{"name":"Hinweis","dataType":"string"},{"name":"Fehler_lt_Kunde","dataType":"string"},{"name":"Wunsch_an_Produktion","dataType":"string"},{"name":"ActualShipDate","dataType":"date"},{"name":"ersteAuslieferungsdatum","dataType":"date"},{"name":"letzteAuslieferungsDatum","dataType":"date"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T04:01:28.6616887+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/c8374a80-644a-4f11-8957-e45cf31acc76/ServiceDaten_KomponentenEbene.csv?snapshot=2022-06-13T04%3A01%3A28.5292888Z"}]},{"$type":"LocalEntity","name":"ServiceDaten_FehlerEintragIntern","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"ServiceDaten_FehlerEintragIntern.csv"},"attributes":[{"name":"ServiceID","dataType":"int64"},{"name":"RepID","dataType":"int64"},{"name":"FehlerKlasse_Intern","dataType":"string"},{"name":"Fehler_Intern","dataType":"string"},{"name":"Hauptfehler_Intern","dataType":"boolean"},{"name":"Bemerkung_FehlerIntern","dataType":"string"},{"name":"Eintrag_Datum","dataType":"dateTime"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T04:01:20.3640976+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/c8374a80-644a-4f11-8957-e45cf31acc76/ServiceDaten_FehlerEintragIntern.csv?snapshot=2022-06-13T04%3A01%3A20.1830762Z"}]},{"$type":"LocalEntity","name":"ServiceDaten_FehlerEintraganKunde","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"ServiceDaten_FehlerEintraganKunde.csv"},"attributes":[{"name":"ServiceID","dataType":"int64"},{"name":"FehlerKlasse_anKunde","dataType":"string"},{"name":"Fehler_anKunde","dataType":"string"},{"name":"Bemerkung_FehleranKunde","dataType":"string"},{"name":"Eintrag_Datum","dataType":"dateTime"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T04:01:19.9301476+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/c8374a80-644a-4f11-8957-e45cf31acc76/ServiceDaten_FehlerEintraganKunde.csv?snapshot=2022-06-13T04%3A01%3A19.7233386Z"}]}]}