{"name":"COHREP_SITE_PLANNING_MASTER1","description":"","version":"1.0","culture":"en-US","modifiedTime":"2021-02-09T10:40:38.1072243+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":true,"queriesMetadata":{"Sourcing_Rule_Assignment":{"queryId":"40b24e9d-6ec3-44cc-9402-6053e480d628","queryName":"Sourcing_Rule_Assignment","queryGroupId":"root","loadEnabled":true},"ORG":{"queryId":"5c2a1e07-2351-4d86-b04d-200214fde2fa","queryName":"ORG"},"Planner":{"queryId":"c7fafe88-5ffd-44e7-bb70-73aee2374b30","queryName":"Planner","queryGroupId":"root","loadEnabled":true},"Local":{"queryId":"0fb51c24-30f1-4478-b766-e1f1a468d14f","queryName":"Local"}},"document":"section Section1;\r\nshared Sourcing_Rule_Assignment = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, \n  Query=\"\n  SELECT\n    sysdate                                                                         extract_date,\n    from_tz(cast (sysdate as timestamp),'PST') at time zone '\"&Local&\"' local_extract_date,\n    decode(msra.assignment_type,6,'Item-Organization',5,'Category-Organization',3,'Item',4,'Organization',1,'Global') assignment_type,\n    case when msra.assignment_type = 6\n    then 1\n    when msra.assignment_type = 5\n    then 2\n    when msra.assignment_type = 3\n    then 3\n    when msra.assignment_type = 4\n    then 4\n    when msra.assignment_type = 1\n    then 5 \n    end assignment_priority,\n    mas.assignment_set_id,\n    mas.assignment_set_name,\n    msra.organization_id,\n    msra.organization_code,\n    msra.description                                                                sra_description,\n    msra.sourcing_rule_type_text                                                    sourcing_rule_type,\n    msra.sourcing_rule_name,\n    msra.sourcing_rule_id,\n    msra.inventory_item_id,\n    msr.organization_id                                                             sr_organization_id,\n    msso.vendor_id,\n    msso.vendor_name,\n    msso.vendor_site_id,\n    msso.vendor_site,\n    decode(msso.source_type, 1, 'Transfer From', 2, 'Make At',\n           3, 'Buy From') sourcing_type,\n    ( msso.allocation_percent / 100 )                                               allocation_percent,\n    msso.rank,\n    msso.ship_method,\n    msso.intransit_time,\n    msro.receipt_organization_id,\n    msro.organization_code                                                          receipt_organization_code,\n    msro.effective_date                                                             receipt_effective_date,\n    msro.disable_date                                                               receipt_disable_date,\n    CASE\n        WHEN sysdate > msro.effective_date\n             AND sysdate < nvl(msro.disable_date, sysdate + 1) THEN\n            'Yes'\n        ELSE\n            'No'\n    END sr_currently_active,\n    nvl(assa.country, hou.country)                                                  country,\n    assa.country_of_origin_code                                                     country_of_origin,\n    nvl(assa.country_of_origin_code, nvl(assa.country, hou.country))                coo_or_country,\n    nvl(msso.vendor_name, msso.source_organization_code)                            sourcing_org_or_vendor,\n    aps.end_date_active                                                             vendor_inactive_date,\n    assa.inactive_date                                                              vendor_site_inactive_date,\n    hou.date_to                                                                     org_end_date,\n    CASE\n        WHEN msso.source_organization_id > 0 THEN\n            CASE\n                WHEN nvl(hou.date_to, sysdate + 1) < sysdate THEN\n                    'No'\n                ELSE\n                    'Yes'\n            END\n        ELSE\n            (\n                CASE\n                    WHEN least(nvl(aps.end_date_active, sysdate + 1), nvl(assa.inactive_date, sysdate + 1)) < trunc(sysdate) THEN\n                        'No'\n                    ELSE\n                        'Yes'\n                END\n            )\n    END active_source_flag,\n    msra.category_id,\n    (select segment1||'.'||segment2||'.'||segment3||'.'||segment4\n    from apps.mtl_categories mc\n    where mc.category_id = msra.category_id)sr_category\nFROM\n    apps.mrp_sr_assignments_v     msra,\n    apps.mrp_assignment_sets      mas,\n    apps.mrp_sr_receipt_org_v     msro,\n    apps.mrp_sr_source_org_v      msso,\n    mrp.mrp_sourcing_rules        msr,\n    apps.ap_supplier_sites_all    assa,\n    apps.ap_suppliers             aps,\n    hr_organization_units_v       hou\nWHERE\n        mas.assignment_set_name = 'MRP_GLOBAL'\n    AND mas.assignment_set_id = msra.assignment_set_id\n    AND msro.sr_receipt_id = msso.sr_receipt_id\n    AND msr.sourcing_rule_id = msro.sourcing_rule_id\n    AND msra.sourcing_rule_id = msr.sourcing_rule_id\n    AND msso.vendor_site_id = assa.vendor_site_id (+)\n    AND msso.vendor_id = aps.vendor_id (+)\n    AND msso.source_organization_id = hou.organization_id (+)\n    AND msra.organization_code = '\"&ORG&\"'\n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"EXTRACT_DATE\", \"Extract Date\"}, {\"LOCAL_EXTRACT_DATE\", \"Local Extract Date\"}, {\"ASSIGNMENT_SET_NAME\", \"Assignment Set Name\"}, {\"ORGANIZATION_CODE\", \"Organization Code\"}, {\"SOURCING_RULE_NAME\", \"Sourcing Rule Name\"}, {\"SOURCING_RULE_TYPE\", \"Sourcing Rule Type\"}, {\"VENDOR_NAME\", \"Vendor Name\"}, {\"VENDOR_SITE\", \"Vendor Site\"}, {\"ASSIGNMENT_TYPE\", \"Assignment Type\"}, {\"ASSIGNMENT_PRIORITY\", \"Assignment Priority\"}, {\"SRA_DESCRIPTION\", \"Sourcing Rule Description\"}, {\"SOURCING_TYPE\", \"Sourcing Type\"}, {\"ALLOCATION_PERCENT\", \"Sourcing Allocation Percent\"}, {\"RANK\", \"Rank\"}, {\"SHIP_METHOD\", \"Ship Method\"}, {\"INTRANSIT_TIME\", \"Intransit Time\"}, {\"RECEIPT_ORGANIZATION_CODE\", \"Receipt Organization Code\"}, {\"RECEIPT_EFFECTIVE_DATE\", \"Receipt Effective Date\"}, {\"RECEIPT_DISABLE_DATE\", \"Receipt Disable Date\"}, {\"SR_CURRENTLY_ACTIVE\", \"SR Currently Active Flag\"}, {\"COUNTRY\", \"Sourcing Country\"}, {\"COUNTRY_OF_ORIGIN\", \"Sourcing COO\"}, {\"COO_OR_COUNTRY\", \"Sourcing COO or Country\"}, {\"SOURCING_ORG_OR_VENDOR\", \"Sourcing Org or Vendor\"}, {\"VENDOR_INACTIVE_DATE\", \"Vendor Inactive Date\"}, {\"VENDOR_SITE_INACTIVE_DATE\", \"Vendor Site Inactive Date\"}, {\"ORG_END_DATE\", \"Sourcing Org Inactive Date\"}, {\"ACTIVE_SOURCE_FLAG\", \"Active Source Flag\"}, {\"SR_CATEGORY\", \"SR Category\"}}),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Renamed columns\", {{\"Sourcing Allocation Percent\", Percentage.Type}}),\r\n  #\"Renamed columns 1\" = Table.RenameColumns(#\"Changed column type\", {{\"Vendor Site Inactive Date\", \"Sourcing Vendor Site Inactive Date\"}, {\"Vendor Inactive Date\", \"Sourcing Vendor Inactive Date\"}})\r\nin\r\n  #\"Renamed columns 1\";\r\nshared ORG = let\r\n  ORG = \"LDP\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type text]\r\nin\r\n  ORG;\r\nshared Planner = let\r\n  Source = Oracle.Database(\"COHREP\", \n  [HierarchicalNavigation=true, \n  Query=\"\n  SELECT\n  sysdate EXTRACT_DATE,\n    from_tz(cast (sysdate as timestamp),'PST') at time zone '\"&Local&\"' local_extract_date,\n  MP.organization_code,\n  MPL.planner_code,\n  MPL.description,\n  MPL.disable_date,\n  MPL.electronic_mail_address,\n  (SELECT\n    full_name\n  FROM APPS.PER_PEOPLE_F PPF\n  WHERE PPF.person_id = MPL.employee_id\n  AND rownum = 1)\n  PLANNER_NAME\nFROM\n  INV.MTL_PLANNERS MPL,\n  inv.mtl_parameters MP\nWHERE\n  MP.organization_id = MPL.organization_id\n  AND MP.organization_code = '\"&ORG&\"'\n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"PLANNER_CODE\", \"Planner Code\"}, {\"DESCRIPTION\", \"Planner Description\"}, {\"ELECTRONIC_MAIL_ADDRESS\", \"Planner Email Address\"}, {\"PLANNER_NAME\", \"Planner Name\"}, {\"DISABLE_DATE\", \"Disable Date\"}, {\"ORGANIZATION_CODE\", \"Organization Code\"}, {\"EXTRACT_DATE\", \"Extract Date\"}}),\r\n  ConvertToList = Table.AddColumn(#\"Renamed columns\", \"ClassCodeToList\", each Text.ToList([Planner Code])),\r\n  LowerCaseChars = {\"a\"..\"z\"},\r\n  // add Character.FromNumber(8203) to make the column unique\r\n  AddInvisibleChars = Table.AddColumn(ConvertToList, \"AddInvisibleChars\", each List.Transform(\n            [ClassCodeToList], \n            each \n            if \n            List.Contains(#\"LowerCaseChars\", _) \n            then \n            _ & Character.FromNumber(8203) \n            else _\n            )),\r\n  // Add case sensitive column as result of adding invisible characters Character.FromNumber(8203)\r\n  AddCaseSensitiveColumn = Table.AddColumn(AddInvisibleChars, \"Planner Code CS\", each Text.Combine([AddInvisibleChars])),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(AddCaseSensitiveColumn, {{\"Planner Code CS\", type text}}),\r\n  #\"Removed columns\" = Table.RemoveColumns(#\"Changed column type\", {\"ClassCodeToList\", \"AddInvisibleChars\"}),\r\n  #\"Renamed columns 1\" = Table.RenameColumns(#\"Removed columns\", {{\"LOCAL_EXTRACT_DATE\", \"Local Extract Date\"}})\r\nin\r\n  #\"Renamed columns 1\";\r\nshared Local = let\r\n  Local = \"CET\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type text]\r\nin\r\n  Local;\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"Sourcing_Rule_Assignment","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Sourcing_Rule_Assignment.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Local Extract Date","dataType":"dateTime"},{"name":"Assignment Type","dataType":"string"},{"name":"Assignment Priority","dataType":"double"},{"name":"ASSIGNMENT_SET_ID","dataType":"double"},{"name":"Assignment Set Name","dataType":"string"},{"name":"ORGANIZATION_ID","dataType":"double"},{"name":"Organization Code","dataType":"string"},{"name":"Sourcing Rule Description","dataType":"string"},{"name":"Sourcing Rule Type","dataType":"string"},{"name":"Sourcing Rule Name","dataType":"string"},{"name":"SOURCING_RULE_ID","dataType":"double"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"SR_ORGANIZATION_ID","dataType":"double"},{"name":"VENDOR_ID","dataType":"double"},{"name":"Vendor Name","dataType":"string"},{"name":"VENDOR_SITE_ID","dataType":"double"},{"name":"Vendor Site","dataType":"string"},{"name":"Sourcing Type","dataType":"string"},{"name":"Sourcing Allocation Percent","dataType":"double"},{"name":"Rank","dataType":"double"},{"name":"Ship Method","dataType":"string"},{"name":"Intransit Time","dataType":"double"},{"name":"RECEIPT_ORGANIZATION_ID","dataType":"double"},{"name":"Receipt Organization Code","dataType":"string"},{"name":"Receipt Effective Date","dataType":"dateTime"},{"name":"Receipt Disable Date","dataType":"dateTime"},{"name":"SR Currently Active Flag","dataType":"string"},{"name":"Sourcing Country","dataType":"string"},{"name":"Sourcing COO","dataType":"string"},{"name":"Sourcing COO or Country","dataType":"string"},{"name":"Sourcing Org or Vendor","dataType":"string"},{"name":"Sourcing Vendor Inactive Date","dataType":"dateTime"},{"name":"Sourcing Vendor Site Inactive Date","dataType":"dateTime"},{"name":"Sourcing Org Inactive Date","dataType":"dateTime"},{"name":"Active Source Flag","dataType":"string"},{"name":"CATEGORY_ID","dataType":"double"},{"name":"SR Category","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-05-20T05:04:57.9683672+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/199e0687-a402-4231-bcbd-5cdd7ab69391/Sourcing_Rule_Assignment.csv?snapshot=2022-05-20T05%3A04%3A57.9074276Z"}]},{"$type":"LocalEntity","name":"Planner","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Planner.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Local Extract Date","dataType":"dateTime"},{"name":"Organization Code","dataType":"string"},{"name":"Planner Code","dataType":"string"},{"name":"Planner Description","dataType":"string"},{"name":"Disable Date","dataType":"dateTime"},{"name":"Planner Email Address","dataType":"string"},{"name":"Planner Name","dataType":"string"},{"name":"Planner Code CS","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-05-20T05:06:02.5586751+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/199e0687-a402-4231-bcbd-5cdd7ab69391/Planner.csv?snapshot=2022-05-20T05%3A06%3A02.4166923Z"}]}]}