{"name":"COHREP_SITE_INVENTORY_TRX1","description":"","version":"1.0","culture":"en-US","modifiedTime":"2020-10-27T07:14:29.2279318+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":true,"queriesMetadata":{"ORG":{"queryId":"3f0ec9d1-2a80-4384-8a7b-aaae2c5c237f","queryName":"ORG"},"Kanban_Card":{"queryId":"68c4871b-0590-4e1b-8d18-a3c5efc8050f","queryName":"Kanban_Card","queryGroupId":"root","loadEnabled":true},"Kanban_Supply":{"queryId":"d642d45d-bc2f-4173-add6-e504e7e8b8db","queryName":"Kanban_Supply","queryGroupId":"root","loadEnabled":true},"Onhand":{"queryId":"ec674b22-8d94-4e95-93e5-f62828fa79ae","queryName":"Onhand","queryGroupId":"root","loadEnabled":true},"Open_Supply":{"queryId":"db068778-0c8e-43bf-9afa-7a2634b1353c","queryName":"Open_Supply","queryGroupId":"root","loadEnabled":true},"Cycle_Count_Activity":{"queryId":"a1e5ca18-cdf8-436c-8b8e-6ecee7cfc401","queryName":"Cycle_Count_Activity","queryGroupId":"root","loadEnabled":true},"Receipt":{"queryId":"3f9255c2-2289-4c68-a489-cbfd733850b5","queryName":"Receipt","queryGroupId":"root","loadEnabled":true},"Serial_Status":{"queryId":"af92de86-7c81-4894-bd59-a54cf393ea2e","queryName":"Serial_Status","queryGroupId":"root","loadEnabled":true},"Material_Transaction":{"queryId":"f6392d5b-2e8e-4d58-95fd-2bb15e8a172e","queryName":"Material_Transaction","queryGroupId":"root","loadEnabled":true},"Receiving_Default":{"queryId":"fcc5af81-cf71-4499-8817-658d01a40af7","queryName":"Receiving_Default","queryGroupId":"root","loadEnabled":true},"Consumption_Advice":{"queryId":"80af5189-c1d0-4e99-b67a-af24a6f3cc41","queryName":"Consumption_Advice","queryGroupId":"root","loadEnabled":true},"Open_WO":{"queryId":"f746c825-6c32-493b-9812-0b6c3d581ae3","queryName":"Open_WO","queryGroupId":"root","loadEnabled":true},"Open_MO":{"queryId":"9f857d3f-df46-403f-ba41-c0142ec4f606","queryName":"Open_MO","queryGroupId":"root","loadEnabled":true}},"document":"section Section1;\r\nshared ORG = let\r\n  ORG = \"LDP\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type text]\r\nin\r\n  ORG;\r\nshared Kanban_Card = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, \n  Query=\"\n  SELECT\n    sysdate                    extract_date,\n    mp.organization_code,\n    mkc.kanban_card_id,\n    mkc.kanban_card_number,\n    mkc.creation_date,\n    mkc.inventory_item_id,\n    msi.segment1               item_number,\n    mkc.pull_sequence_id,\n    nvl(mkp.replenishment_lead_time, msi.preprocessing_lead_time + msi.full_lead_time + msi.postprocessing_lead_time) kanban_lead_time,\n    mkp.replenishment_lead_time pull_sequence_lead_time,\n    mkc.subinventory_name,\n    (\n        SELECT\n            mloc.concatenated_segments\n        FROM\n            apps.mtl_item_locations_kfv mloc\n        WHERE\n                mloc.inventory_location_id = mkc.locator_id\n            AND mloc.organization_id = mp.organization_id\n            AND mkc.subinventory_name = mloc.subinventory_code\n    ) kanban_locator,\n    mkc.source_org_code,\n    mkc.source_subinventory,\n    decode(mkc.kanban_card_type, 1, 'Replenishable', 2, 'Non Replenishable',\n           'Other') kanban_card_type,\n    mkc.kanban_size,\n    mkc.source_type_meaning    kanban_source_type,\n    mkc.supply_status_name     kanban_supply_status,\n    mkc.supply_status supply_status_id,\n    (\n        SELECT\n            MAX(kca.creation_date)\n        FROM\n            apps.mtl_kanban_card_activity_v kca\n        WHERE\n                kca.supply_status_name = 'In Process'\n            AND kca.creation_date >= sysdate - 365\n            AND kca.kanban_card_id = mkc.kanban_card_id\n    ) kanban_last_replenish,\n    (\n        SELECT\n            COUNT(kca.creation_date)\n        FROM\n            apps.mtl_kanban_card_activity_v kca\n        WHERE\n                kca.supply_status_name = 'In Process'\n            AND kca.creation_date >= sysdate - 365\n            AND kca.kanban_card_id = mkc.kanban_card_id\n    ) kanban_replenish_count,\n    (\n        SELECT\n            MAX(kca.creation_date)\n        FROM\n            apps.mtl_kanban_card_activity kca\n        WHERE\n                kca.supply_status = 4\n                and kca.inventory_item_id = mkc.inventory_item_id\n                and kca.organization_id = mkc.organization_id\n            AND kca.kanban_card_id = mkc.kanban_card_id\n    ) kanban_last_empty,\n    round((sysdate -(\n        SELECT\n            MAX(kca.creation_date)\n        FROM\n            apps.mtl_kanban_card_activity kca\n        WHERE\n            kca.supply_status IN(\n               4,5\n            )\n           and kca.inventory_item_id = mkc.inventory_item_id\n                and kca.organization_id = mkc.organization_id\n         --   AND kca.creation_date >= sysdate - 365\n            AND kca.kanban_card_id = mkc.kanban_card_id\n    )), 0) kanban_activity_age_days,\n    (\n        SELECT\n            SUM(moqd.primary_transaction_quantity)\n        FROM\n            inv.mtl_onhand_quantities_detail moqd\n        WHERE\n                moqd.inventory_item_id = mkc.inventory_item_id\n            AND moqd.subinventory_code = mkc.source_subinventory\n            AND mkc.organization_id = moqd.organization_id\n    ) kanban_source_onhand,\n    (\n        SELECT\n            SUM(moqd.primary_transaction_quantity)\n        FROM\n            inv.mtl_onhand_quantities_detail moqd\n        WHERE\n                moqd.inventory_item_id = msi.inventory_item_id\n            AND moqd.subinventory_code = mkc.subinventory_name\n            AND msi.organization_id = moqd.organization_id\n    ) kanban_onhand,\n    (\n        SELECT\n            item_cost\n        FROM\n            apps.cst_item_costs cic\n        WHERE\n                cic.cost_type_id = 1\n            AND cic.organization_id = mkc.organization_id\n            AND mkc.inventory_item_id = cic.inventory_item_id\n    ) item_cost,\n    (\n        SELECT\n            SUM(mkc2.kanban_size)\n        FROM\n            apps.mtl_kanban_cards_v mkc2\n        WHERE\n                mkc2.pull_sequence_id = mkc.pull_sequence_id\n            AND mkc2.supply_status_name = 'Full'\n            AND mkc2.card_status_name = 'Active'\n    ) total_full_size,\n    (\n        CASE\n            WHEN mkc.supply_status_name = 'Full'\n                 AND nvl((\n                SELECT\n                    SUM(moqd.primary_transaction_quantity)\n                FROM\n                    inv.mtl_onhand_quantities_detail moqd\n                WHERE\n                        moqd.inventory_item_id = mkc.inventory_item_id\n                    AND moqd.subinventory_code = mkc.subinventory_name\n                    AND mkc.organization_id = moqd.organization_id\n            ), 0) < (\n                SELECT\n                    SUM(mkc2.kanban_size)\n                FROM\n                    apps.mtl_kanban_cards_v mkc2\n                WHERE\n                        mkc2.pull_sequence_id = mkc.pull_sequence_id\n                    AND mkc2.supply_status_name = 'Full'\n                    AND mkc2.card_status_name = 'Active'\n            ) THEN\n                'Late to Empty'\n            ELSE\n                'Normal'\n        END\n    ) kanban_trigger_exception,\n    (\n        CASE\n            WHEN mkc.supply_status_name = 'In Process'\n                 AND mkc.source_type_meaning = 'Intra Org'\n                 AND (\n                SELECT\n                    COUNT(mtrl.line_id)\n                FROM\n                    inv.mtl_txn_request_lines mtrl\n                WHERE\n                        mtrl.line_status = 7\n                    AND mtrl.reference_id = mkc.kanban_card_id\n                    AND mtrl.organization_id = mkc.organization_id\n            ) <= 0 THEN\n                'Missing Supply'\n            WHEN mkc.supply_status_name = 'In Process'\n                 AND mkc.source_type_meaning = 'Intra Org'\n                 AND (\n                SELECT\n                    SUM(moqd.primary_transaction_quantity)\n                FROM\n                    inv.mtl_onhand_quantities_detail moqd\n                WHERE\n                        moqd.inventory_item_id = mkc.inventory_item_id\n                    AND moqd.subinventory_code = mkc.subinventory_name\n                    AND mkc.organization_id = moqd.organization_id\n            ) = 0 THEN\n                'No Stock to Deliver'\n            WHEN mkc.supply_status_name = 'In Process'\n                 AND mkc.source_type_meaning = 'Intra Org'\n                 AND trunc(sysdate + 1) > (\n                SELECT\n                    MAX(mtrl.date_required)\n                FROM\n                    inv.mtl_txn_request_lines mtrl\n                WHERE\n                        mtrl.line_status = 7\n                    AND mtrl.reference_id = mkc.kanban_card_id\n                    AND mtrl.organization_id = mkc.organization_id\n            )\n                 AND (\n                SELECT\n                    SUM(moqd.primary_transaction_quantity)\n                FROM\n                    inv.mtl_onhand_quantities_detail moqd\n                WHERE\n                        moqd.inventory_item_id = mkc.inventory_item_id\n                    AND moqd.subinventory_code = mkc.source_subinventory\n                    AND mkc.organization_id = moqd.organization_id\n            ) > 0 THEN\n                'Late Delivery'\n        END\n    ) intra_org_card_exception,\n    (\n        CASE\n            WHEN mkc.supply_status_name in('Empty', 'In Process')\n                 AND mkc.source_type_meaning = 'Inter Org'\n                 AND ( sysdate - (\n                SELECT\n                    MAX(kca.creation_date)\n                FROM\n                    apps.mtl_kanban_card_activity kca\n                WHERE\n                    kca.supply_status IN (\n                        4,5\n                    )\n                    AND kca.kanban_card_id = mkc.kanban_card_id\n            ) ) > 0.5\n                 AND (\n                SELECT\n                    COUNT(ms.req_line_id)\n                FROM\n                    inv.mtl_supply                 ms,\n                    po.po_requisition_lines_all    prla\n                WHERE\n                        prla.requisition_line_id = ms.req_line_id\n                    AND prla.kanban_card_id = mkc.kanban_card_id\n                    AND ms.to_organization_id = mkc.organization_id\n            ) <= 0 THEN\n                'Missing Supply'\n            WHEN mkc.supply_status_name = 'In Process'\n                 AND mkc.source_type_meaning = 'Inter Org'\n                 AND (\n                SELECT\n                    MIN(ms.receipt_date)\n                FROM\n                    inv.mtl_supply                 ms,\n                    po.po_requisition_lines_all    prla\n                WHERE\n                        prla.requisition_line_id = ms.req_line_id\n                    AND prla.kanban_card_id = mkc.kanban_card_id\n                    AND ms.to_organization_id = mkc.organization_id\n            ) < sysdate + 4 THEN\n                'Late Delivery'\n        END\n    ) inter_org_card_exception,\n    (\n        CASE\n            WHEN mkc.supply_status_name in( 'In Process','Empty')\n                 AND mkc.source_type_meaning = 'Supplier'\n                 AND ( sysdate - (\n                SELECT\n                    MAX(kca.creation_date)\n                FROM\n                    apps.mtl_kanban_card_activity kca\n                WHERE\n                    kca.supply_status IN (\n                        4,5\n                    )\n                    AND kca.kanban_card_id = mkc.kanban_card_id\n            ) ) > 0.5\n                 AND ( (\n                SELECT\n                    COUNT(pda.po_distribution_id)\n                FROM\n                    inv.mtl_supply                 ms,\n                    po.po_distributions_all    pda\n                WHERE\n                        pda.po_distribution_id = ms.po_distribution_id\n                    AND pda.kanban_card_id = mkc.kanban_card_id\n            ) + (\n                SELECT\n                    COUNT(prla.requisition_line_id)\n                FROM\n                    inv.mtl_supply                 ms,\n                    po.po_requisition_lines_all    prla\n                WHERE\n                        prla.requisition_line_id = ms.req_line_id\n                    AND prla.kanban_card_id = mkc.kanban_card_id\n            ) ) <= 0 THEN\n                'Missing Supply'\n            WHEN mkc.supply_status_name = 'In Process'\n                 AND mkc.source_type_meaning = 'Supplier'\n                 AND ( sysdate - (\n                SELECT\n                    MAX(kca.creation_date)\n                FROM\n                    apps.mtl_kanban_card_activity kca\n                WHERE\n                    kca.supply_status IN (\n                       5\n                    )\n                    AND kca.kanban_card_id = mkc.kanban_card_id\n            ) ) > msi.preprocessing_lead_time\n                 AND (\n                SELECT\n                    COUNT(pda.po_distribution_id)\n                FROM\n                    inv.mtl_supply             ms,\n                    po.po_distributions_all    pda\n                WHERE\n                        pda.po_distribution_id = ms.po_distribution_id\n                    AND pda.kanban_card_id = mkc.kanban_card_id\n            ) <= 0 THEN\n                'Late To Process'\n            WHEN mkc.supply_status_name = 'In Process'\n                 AND mkc.source_type_meaning = 'Supplier'\n                 AND (\n                SELECT\n                    MIN(ms.receipt_date)\n                FROM\n                    inv.mtl_supply             ms,\n                    po.po_distributions_all    pda\n                WHERE\n                        pda.po_distribution_id = ms.po_distribution_id\n                    AND pda.kanban_card_id = mkc.kanban_card_id\n            ) < sysdate + 1 THEN\n                'Late Delivery'\n        END\n    ) supplier_card_exception,\n    (\n        CASE\n            WHEN mkc.supply_status_name = 'In Process'\n                 AND mkc.source_type_meaning = 'Production'\n                 AND (\n                SELECT\n                    COUNT(wdj.wip_entity_id)\n                FROM\n                    apps.wip_discrete_jobs wdj\n                WHERE\n                        wdj.kanban_card_id = mkc.kanban_card_id\n                    AND wdj.organization_id = mp.organization_id\n                    AND wdj.status_type IN (\n                        1-- 'Released',\n                        ,\n                        3-- 'Unreleased'\n                    )\n            ) < 0 THEN\n                'Missing Supply'\n            WHEN mkc.supply_status_name = 'In Process'\n                 AND mkc.source_type_meaning = 'Production'\n                 AND trunc(sysdate + 1) > (\n                SELECT\n                    MIN(wdj.scheduled_completion_date)\n                FROM\n                    apps.wip_discrete_jobs wdj\n                WHERE\n                        wdj.kanban_card_id = mkc.kanban_card_id\n                    AND wdj.organization_id = mp.organization_id\n                    AND wdj.status_type IN (\n                        1-- 'Released',\n                        ,\n                        3-- 'Unreleased'\n                    )\n            ) THEN\n                'Late Delivery'\n        END\n    ) production_card_exception,\n    mkc.card_status_name\nFROM\n    apps.mtl_kanban_cards_v             mkc,\n    inv.mtl_parameters                  mp,\n    inv.mtl_system_items_b              msi,\n    apps.mtl_kanban_pull_sequences_v    mkp\nWHERE\n        mp.organization_id = mkc.organization_id\n    AND mp.organization_code = '\"&ORG&\"'\n    AND msi.inventory_item_id = mkc.inventory_item_id\n    AND msi.organization_id = mkc.organization_id\n    AND mkc.pull_sequence_id = mkp.pull_sequence_id (+)\n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Inserted conditional column\" = Table.AddColumn(Source, \"KANBAN_CARD_EXCEPTION\", each if [INTRA_ORG_CARD_EXCEPTION] <> null then [INTRA_ORG_CARD_EXCEPTION] else if [INTER_ORG_CARD_EXCEPTION] <> null then [INTER_ORG_CARD_EXCEPTION] else if [SUPPLIER_CARD_EXCEPTION] <> null then [SUPPLIER_CARD_EXCEPTION] else if [PRODUCTION_CARD_EXCEPTION] <> null then [PRODUCTION_CARD_EXCEPTION] else if [KANBAN_TRIGGER_EXCEPTION] <> null then [KANBAN_TRIGGER_EXCEPTION] else \"Normal\"),\r\n  #\"Choose columns\" = Table.SelectColumns(#\"Inserted conditional column\", {\"EXTRACT_DATE\", \"ORGANIZATION_CODE\", \"KANBAN_CARD_ID\", \"KANBAN_CARD_NUMBER\", \"CREATION_DATE\", \"INVENTORY_ITEM_ID\", \"ITEM_NUMBER\", \"PULL_SEQUENCE_ID\", \"KANBAN_LEAD_TIME\", \"SUBINVENTORY_NAME\", \"KANBAN_LOCATOR\", \"SOURCE_ORG_CODE\", \"SOURCE_SUBINVENTORY\", \"KANBAN_CARD_TYPE\", \"KANBAN_SIZE\", \"KANBAN_SOURCE_TYPE\", \"KANBAN_SUPPLY_STATUS\", \"SUPPLY_STATUS_ID\", \"KANBAN_LAST_REPLENISH\", \"KANBAN_REPLENISH_COUNT\", \"KANBAN_LAST_EMPTY\", \"KANBAN_ACTIVITY_AGE_DAYS\", \"KANBAN_SOURCE_ONHAND\", \"KANBAN_ONHAND\", \"ITEM_COST\", \"CARD_STATUS_NAME\", \"KANBAN_CARD_EXCEPTION\", \"PULL_SEQUENCE_LEAD_TIME\"}),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Choose columns\", {{\"KANBAN_CARD_NUMBER\", \"Card Number\"}, {\"ITEM_NUMBER\", \"Item Number\"}, {\"PULL_SEQUENCE_ID\", \"Pull Sequence Id\"}, {\"SUBINVENTORY_NAME\", \"Subinventory\"}, {\"KANBAN_LOCATOR\", \"Locator\"}, {\"KANBAN_CARD_TYPE\", \"Card Type\"}, {\"KANBAN_SIZE\", \"Card Size\"}, {\"KANBAN_SOURCE_TYPE\", \"Source Type\"}, {\"KANBAN_SUPPLY_STATUS\", \"Supply Status\"}, {\"EXTRACT_DATE\", \"Extract Date\"}, {\"CREATION_DATE\", \"Creation Date\"}, {\"SOURCE_ORG_CODE\", \"Source Org\"}, {\"KANBAN_REPLENISH_COUNT\", \"Replenish Count\"}, {\"KANBAN_LAST_REPLENISH\", \"Last Replenish Date\"}, {\"KANBAN_LAST_EMPTY\", \"Last Empty Date\"}, {\"KANBAN_ACTIVITY_AGE_DAYS\", \"Last Activity Age Days\"}, {\"KANBAN_SOURCE_ONHAND\", \"Source Onhand\"}, {\"SOURCE_SUBINVENTORY\", \"Source Subinventory\"}, {\"KANBAN_CARD_EXCEPTION\", \"Exception\"}, {\"KANBAN_LEAD_TIME\", \"Effective Lead Time\"}, {\"KANBAN_ONHAND\", \"Onhand Quantity\"}, {\"ORGANIZATION_CODE\", \"Organization Code\"}, {\"CARD_STATUS_NAME\", \"Card Status\"}, {\"PULL_SEQUENCE_LEAD_TIME\", \"Pull Sequence Lead Time\"}}),\r\n  #\"Transform columns\" = Table.TransformColumnTypes(#\"Renamed columns\", {{\"Exception\", type text}}),\r\n  #\"Replace errors\" = Table.ReplaceErrorValues(#\"Transform columns\", {{\"Exception\", null}})\r\nin\r\n  #\"Replace errors\";\r\nshared Kanban_Supply = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, \n  Query=\"\n  SELECT\n    sysdate extract_date,\n    organization_code,\n    kanban_card_id,\n    kanban_card_number,\n    supply_document_type,\n    supply_document_number,\n    supply_line_number,\n    supply_quantity,\n    supply_date,\n    vendor_id,\n    vendor_site_id,\n    source_org,\n    supplier_name,\n    supplier_site_code,\n    pull_sequence_id\nFROM\n    (\n        SELECT\n            sysdate                                         extract_date,\n            mp.organization_code,\n            mkc.kanban_card_id,\n            mkc.kanban_card_number,\n            msi.segment1,\n            'PO'                                            supply_document_type,\n            CASE\n                WHEN nvl(pra.release_num, 0) > 0 THEN\n                    pha.segment1\n                    || '_'\n                    || pra.release_num\n                ELSE\n                    pha.segment1\n            END supply_document_number,\n            pla.line_num\n            || '_'\n            || plla.shipment_num            supply_line_number,\n            plla.promised_date                              supply_date,\n            ms.to_org_primary_quantity                      supply_quantity,\n            pha.vendor_id,\n            pha.vendor_site_id,\n            ''                                              source_org,\n            (\n                SELECT\n                    vendor_name\n                FROM\n                    apps.po_vendors pv\n                WHERE\n                    pv.vendor_id = pha.vendor_id\n            ) supplier_name,\n            (\n                SELECT\n                    vendor_site_code\n                FROM\n                    apps.po_vendor_sites_all pvs\n                WHERE\n                    pvs.vendor_site_id = pha.vendor_site_id\n            ) supplier_site_code,\n            mkc.pull_sequence_id\n        FROM\n            apps.mtl_kanban_cards_v        mkc,\n            inv.mtl_parameters             mp,\n            inv.mtl_system_items_b         msi,\n            inv.mtl_supply                 ms,\n            po.po_requisition_lines_all    prla,\n            po.po_distributions_all        pda,\n            po.po_req_distributions_all    prda,\n            po.po_line_locations_all       plla,\n            po.po_headers_all              pha,\n            po.po_releases_all             pra,\n            po.po_lines_all                pla\n        WHERE\n                mp.organization_id = mkc.organization_id\n            AND mp.organization_code = '\"&ORG&\"'\n            AND msi.inventory_item_id = mkc.inventory_item_id\n            AND msi.organization_id = mkc.organization_id\n            AND mkc.card_status_name = 'Active'\n            AND pda.po_distribution_id = ms.po_distribution_id\n            AND pda.req_distribution_id = prda.distribution_id\n            AND prda.requisition_line_id = prla.requisition_line_id\n            AND prla.kanban_card_id = mkc.kanban_card_id\n            AND plla.line_location_id = pda.line_location_id\n            AND ms.to_organization_id = mkc.organization_id\n            AND pha.po_header_id = ms.po_header_id\n            AND ms.po_line_location_id = plla.line_location_id\n            AND pra.po_release_id (+) = ms.po_release_id\n            AND pla.po_line_id = ms.po_line_id\n    ) po\nUNION\nSELECT\n    sysdate extract_date,\n    organization_code,\n    kanban_card_id,\n    kanban_card_number,\n    supply_document_type,\n    supply_document_number,\n    supply_line_number,\n    supply_quantity,\n    supply_date,\n    vendor_id,\n    vendor_site_id,\n    source_org,\n    supplier_name,\n    supplier_site_code,\n    pull_sequence_id\nFROM\n    (\n        SELECT\n            mp.organization_code,\n            mkc.kanban_card_id,\n            mkc.kanban_card_number,\n            msi.segment1,\n            CASE\n                WHEN nvl(prla.source_organization_id, 0) > 0 THEN\n                    'IR'\n                ELSE\n                    'PR'\n            END supply_document_type,\n            prha.segment1                 supply_document_number,\n            to_char(prla.line_num)        supply_line_number,\n            ms.receipt_date               supply_date,\n            ms.to_org_primary_quantity    supply_quantity,\n            prla.vendor_id,\n            prla.vendor_site_id,\n            (\n                SELECT\n                    organization_code\n                FROM\n                    inv.mtl_parameters mp2\n                WHERE\n                    mp2.organization_id = prla.source_organization_id\n            ) source_org,\n            (\n                SELECT\n                    vendor_name\n                FROM\n                    apps.po_vendors pv\n                WHERE\n                    pv.vendor_id = prla.vendor_id\n            ) supplier_name,\n            (\n                SELECT\n                    vendor_site_code\n                FROM\n                    apps.po_vendor_sites_all pvs\n                WHERE\n                    pvs.vendor_site_id = prla.vendor_site_id\n            ) supplier_site_code,\n            mkc.pull_sequence_id\n        FROM\n            apps.mtl_kanban_cards_v          mkc,\n            inv.mtl_parameters               mp,\n            inv.mtl_system_items_b           msi,\n            inv.mtl_supply                   ms,\n            po.po_requisition_lines_all      prla,\n            po.po_requisition_headers_all    prha\n        WHERE\n                mp.organization_id = mkc.organization_id\n            AND mp.organization_code = '\"&ORG&\"'\n            AND msi.inventory_item_id = mkc.inventory_item_id\n            AND msi.organization_id = mkc.organization_id\n            AND mkc.card_status_name = 'Active'\n            AND prla.kanban_card_id = mkc.kanban_card_id\n            AND ms.to_organization_id = mkc.organization_id\n            AND prha.requisition_header_id = ms.req_header_id\n            AND ms.req_line_id = prla.requisition_line_id\n            AND prla.requisition_header_id = prha.requisition_header_id\n    ) req\nUNION\nSELECT\n    sysdate extract_date,\n    organization_code,\n    kanban_card_id,\n    kanban_card_number,\n    supply_document_type,\n    supply_document_number,\n    supply_line_number,\n    supply_quantity,\n    supply_date,\n    vendor_id,\n    vendor_site_id,\n    source_org,\n    supplier_name,\n    supplier_site_code,\n    pull_sequence_id\nFROM\n    (\n        SELECT\n            mp.organization_code,\n            mkc.kanban_card_id,\n            mkc.kanban_card_number,\n            msi.segment1,\n            'MO'                                                     supply_document_type,\n            mtrh.request_number                                      supply_document_number,\n            to_char(mtrl.line_number)                                supply_line_number,\n            mtrl.date_required                                       supply_date,\n            mtrl.quantity - nvl(mtrl.quantity_delivered, 0)           supply_quantity,\n            - 1                                                      vendor_id,\n            - 1                                                      vendor_site_id,\n            ''                                                       source_org,\n            ''                                                       supplier_name,\n            ''                                                       supplier_site_code,\n            mkc.pull_sequence_id\n        FROM\n            apps.mtl_kanban_cards_v        mkc,\n            inv.mtl_parameters             mp,\n            inv.mtl_system_items_b         msi,\n            inv.mtl_txn_request_lines      mtrl,\n            inv.mtl_txn_request_headers    mtrh\n        WHERE\n                mp.organization_id = mkc.organization_id\n            AND mp.organization_code = '\"&ORG&\"'\n            AND msi.inventory_item_id = mkc.inventory_item_id\n            AND msi.organization_id = mkc.organization_id\n            AND mkc.card_status_name = 'Active'\n            AND mtrl.organization_id = mkc.organization_id\n            AND mtrl.line_status = 7\n            AND mtrl.inventory_item_id = msi.inventory_item_id\n            AND mtrh.header_id = mtrl.header_id\n            AND mtrl.reference_id = mkc.kanban_card_id\n    ) mo\nUNION\nSELECT\n    sysdate extract_date,\n    organization_code,\n    kanban_card_id,\n    kanban_card_number,\n    supply_document_type,\n    supply_document_number,\n    supply_line_number,\n    supply_quantity,\n    supply_date,\n    vendor_id,\n    vendor_site_id,\n    source_org,\n    supplier_name,\n    supplier_site_code,\n    pull_sequence_id\nFROM\n    (\n        SELECT\n            mp.organization_code,\n            mkc.kanban_card_id,\n            mkc.kanban_card_number,\n            msi.segment1,\n            'WO'                                    supply_document_type,\n            wdj.wip_entity_name                     supply_document_number,\n            ''                                      supply_line_number,\n            wdj.scheduled_completion_date           supply_date,\n            to_number(wdj.quantity_remaining)       supply_quantity,\n            - 1                                     vendor_id,\n            - 1                                     vendor_site_id,\n            ''                                      source_org,\n            ''                                      supplier_name,\n            ''                                      supplier_site_code,\n            mkc.pull_sequence_id\n        FROM\n            apps.mtl_kanban_cards_v     mkc,\n            inv.mtl_parameters          mp,\n            inv.mtl_system_items_b      msi,\n            apps.wip_discrete_jobs_v    wdj\n        WHERE\n                mp.organization_id = mkc.organization_id\n            AND mp.organization_code = '\"&ORG&\"'\n            AND msi.inventory_item_id = mkc.inventory_item_id\n            AND msi.organization_id = mkc.organization_id\n            AND mkc.card_status_name = 'Active'\n            AND wdj.kanban_card_id = mkc.kanban_card_id\n            AND wdj.organization_id = mkc.organization_id\n            AND wdj.primary_item_id = msi.inventory_item_id\n            AND wdj.status_type_disp IN (\n                'Released',\n                'Unreleased'\n            )\n    ) wo\n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"SUPPLY_DOCUMENT_TYPE\", \"Document Type\"}, {\"SUPPLY_DOCUMENT_NUMBER\", \"Document Number\"}, {\"SUPPLY_LINE_NUMBER\", \"Line Number\"}, {\"SUPPLY_QUANTITY\", \"Quantity\"}, {\"SUPPLY_DATE\", \"Supply Date\"}, {\"ORGANIZATION_CODE\", \"Organization Code\"}, {\"KANBAN_CARD_NUMBER\", \"Card Number\"}, {\"EXTRACT_DATE\", \"Extract Date\"}, {\"SOURCE_ORG\", \"Source Org\"}, {\"SUPPLIER_NAME\", \"Supplier Name\"}, {\"SUPPLIER_SITE_CODE\", \"Supplier Site Code\"}, {\"PULL_SEQUENCE_ID\", \"Pull Sequence Id\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Onhand = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, \n  Query=\"\n SELECT\n    sysdate                                                  extract_date,\n    mp.organization_code,\n    msi.inventory_item_id,\n    msi.segment1,\n    moqd.primary_transaction_quantity,\n    decode(moqd.is_consigned, 1, 'Yes', 2, 'No')             consigned_flag,\n    (\n        SELECT\n            mloc.concatenated_segments\n        FROM\n            apps.mtl_item_locations_kfv mloc\n        WHERE\n                mloc.inventory_location_id = moqd.locator_id\n            AND mloc.organization_id = moqd.organization_id\n            AND moqd.subinventory_code = mloc.subinventory_code\n    ) locator,\n    pv.vendor_name,\n    pvs.vendor_site_code,\n    pv.vendor_id,\n    pvs.vendor_site_id,\n    moqd.date_received,\n    (\n        SELECT\n            item_cost\n        FROM\n            apps.cst_item_costs cic\n        WHERE\n                cic.cost_type_id = 1\n            AND cic.inventory_item_id = moqd.inventory_item_id\n            AND cic.organization_id = moqd.organization_id\n    ) item_cost,\n    moqd.subinventory_code,\n    decode(mseci.asset_inventory, 1, 'Yes', 'No')            asset_subinventory_flag,\n    decode(mseci.availability_type, 1, 'Yes', 'No')          nettable_subinventory_flag,\n    mseci.attribute1                                         subinventory_classification,\n    (\n        SELECT\n            mmt.transaction_reference\n        FROM\n            apps.mtl_material_transactions mmt\n        WHERE\n                mmt.organization_id = moqd.organization_id\n            AND moqd.create_transaction_id = mmt.transaction_id\n            AND mmt.inventory_item_id = moqd.inventory_item_id\n    ) transaction_reference\nFROM\n    inv.mtl_onhand_quantities_detail    moqd,\n    inv.mtl_parameters                  mp,\n    inv.mtl_system_items_b              msi,\n    apps.po_vendors                     pv,\n    apps.po_vendor_sites_all            pvs,\n    apps.mtl_secondary_inventories      mseci\nWHERE\n        1 = 1\n    AND moqd.owning_organization_id = pvs.vendor_site_id (+)\n    AND pvs.vendor_id = pv.vendor_id (+)\n    AND mp.organization_id = moqd.organization_id\n    AND moqd.inventory_item_id = msi.inventory_item_id\n    AND moqd.organization_id = msi.organization_id\n    AND mseci.organization_id = moqd.organization_id\n    AND mseci.secondary_inventory_name = moqd.subinventory_code\n    AND mp.organization_code = '\"&ORG&\"'\n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"EXTRACT_DATE\", \"Extract Date\"}, {\"SEGMENT1\", \"Item Number\"}, {\"PRIMARY_TRANSACTION_QUANTITY\", \"Quantity\"}, {\"CONSIGNED_FLAG\", \"Consigned Flag\"}, {\"LOCATOR\", \"Locator\"}, {\"VENDOR_NAME\", \"Owning Supplier Name\"}, {\"VENDOR_SITE_CODE\", \"Owning Supplier Site Code\"}, {\"DATE_RECEIVED\", \"Date Received\"}, {\"SUBINVENTORY_CODE\", \"Subinventory\"}, {\"ORGANIZATION_CODE\", \"Organization Code\"}, {\"ASSET_SUBINVENTORY_FLAG\", \"Asset Subinventory Flag\"}, {\"NETTABLE_SUBINVENTORY_FLAG\", \"Nettable Subinventory Flag\"}, {\"SUBINVENTORY_CLASSIFICATION\", \"Subinventory Classification\"}, {\"TRANSACTION_REFERENCE\", \"Transaction Reference\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Open_Supply = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, \n  Query=\"\n SELECT\n    sysdate                       extract_date,\n    msi.segment1                  item_number,\n    mp.organization_code,\n    msi.inventory_item_id,\n    (\n        SELECT\n            mp2.organization_code\n        FROM\n            inv.mtl_parameters mp2\n        WHERE\n            mp2.organization_id = ms.from_organization_id\n    ) source_org,\n    supply_type_code,\n    CASE\n        WHEN ms.supply_type_code = 'PO'           THEN\n            'On Order'\n        WHEN ms.supply_type_code = 'REQ'\n             AND ms.from_organization_id > 0 THEN\n            'On Order'\n        WHEN ms.supply_type_code = 'SHIPMENT'     THEN\n            'In Transit'\n        WHEN ms.supply_type_code = 'RECEIVING'    THEN\n            'Receiving'\n        WHEN ms.supply_type_code = 'REQ'\n             AND ms.from_organization_id IS NULL THEN\n            'Purchase Requisition'\n        ELSE\n            ms.supply_type_code\n    END supply_status,\n    ms.to_org_primary_quantity    supply_quantity,\n    CASE\n        WHEN supply_type_code = 'PO'   THEN\n            (\n                SELECT\n                    pha.vendor_site_id\n                FROM\n                    po.po_headers_all pha\n                WHERE\n                    pha.po_header_id = ms.po_header_id\n            )\n        WHEN supply_type_code = 'REQ'  THEN\n            (\n                SELECT\n                    prla.vendor_site_id\n                FROM\n                    po.po_requisition_lines_all prla\n                WHERE\n                    prla.requisition_line_id = ms.req_line_id\n            )\n    END vendor_site_id,\n    ms.creation_date,\n    CASE\n        WHEN ms.supply_type_code = 'PO' THEN\n            (\n                SELECT\n                    plla.need_by_date\n                FROM\n                    po.po_line_locations_all plla\n                WHERE\n                    plla.line_location_id = ms.po_line_location_id\n            )\n        ELSE\n            ms.need_by_date\n    END supply_need_by_date,\n    ms.receipt_date,\n    CASE\n        WHEN trunc(sysdate) + 1 > ms.receipt_date THEN\n            'Late'\n        ELSE\n            'In Process'\n    END delivery_status,\n    CASE\n        WHEN supply_type_code IN ( 'PO','SHIPMENT') AND ms.po_header_id >0\n             AND  ms.po_release_id IS NOT NULL THEN\n            (\n                SELECT\n                    pha.segment1\n                FROM\n                    po.po_headers_all pha\n                WHERE\n                    pha.po_header_id = ms.po_header_id\n            )\n            || '_'\n            || (\n                SELECT\n                    release_num\n                FROM\n                    po.po_releases_all pra\n                WHERE\n                    pra.po_release_id = ms.po_release_id\n            )\n        WHEN supply_type_code IN ( 'PO','SHIPMENT') AND ms.po_header_id >0\n             AND  ms.po_release_id IS NULL THEN\n            (\n                SELECT\n                    pha.segment1\n                FROM\n                    po.po_headers_all pha\n                WHERE\n                    pha.po_header_id = ms.po_header_id\n            )\n        WHEN supply_type_code IN (\n            'REQ',\n            'SHIPMENT'\n        ) and ms.req_header_id > 0 THEN\n            (\n                SELECT\n                    prha.segment1\n                FROM\n                    po.po_requisition_headers_all prha\n                WHERE\n                    prha.requisition_header_id = ms.req_header_id\n            )\n        WHEN supply_type_code = 'RECEIVING' THEN\n            (\n                SELECT\n                    receipt_num\n                FROM\n                    po.rcv_shipment_headers rsh\n                WHERE\n                    rsh.shipment_header_id = ms.shipment_header_id\n            )\n    END supply_document_number,\n    CASE\n        WHEN supply_type_code IN (\n            'REQ',\n            'SHIPMENT'\n        ) THEN\n            (\n                SELECT\n                    oeh.order_number\n                FROM\n                    po.po_requisition_headers_all    prha,\n                    ont.oe_order_headers_all         oeh,\n                    po.po_requisition_lines_all      prla,\n                    ont.oe_order_lines_all           oel\n                WHERE\n                        prha.requisition_header_id = ms.req_header_id\n                    AND oel.header_id = oeh.header_id\n                    AND oel.source_document_line_id = prla.requisition_line_id\n                    AND ms.req_line_id = prla.requisition_line_id\n                    AND oeh.orig_sys_document_ref = prha.segment1\n                    AND ROWNUM = 1\n            )\n    END internal_order_number,\n    nvl(nvl(\n        CASE\n            WHEN req_line_id > 0 THEN\n                (\n                    SELECT\n                        CASE\n                            WHEN prha.interface_source_code = 'INV'\n                                 AND nvl(prla.kanban_card_id, 0) > 0 THEN\n                            CASE\n                                    WHEN(\n                                        SELECT\n                                            COUNT(1)\n                                        FROM\n                                            apps.mtl_kanban_cards mkc\n                                        WHERE\n                                                mkc.kanban_card_type = 1\n                                            AND prla.kanban_card_id = mkc.kanban_card_id\n                                    ) > 0 THEN\n                                        'Kanban'\n                                    ELSE\n                                        'NR Kanban'\n                                END\n                            WHEN prha.interface_source_code = 'INV'\n                                 AND nvl(prla.kanban_card_id, 0) = 0 THEN\n                                'Min Max'\n                            WHEN prha.interface_source_code = 'MSC'\n                                 AND nvl(prla.kanban_card_id, 0) = 0 THEN\n                                'MRP'\n                            WHEN prha.interface_source_code IS NULL\n                                 AND prha.approved_date IS NOT NULL\n                                 AND prla.item_id IS NULL THEN\n                                'iProcurement'\n                            WHEN prha.interface_source_code IS NULL\n                                 AND prha.approved_date IS NOT NULL THEN\n                                'Manual'\n                            WHEN prha.interface_source_code IS NOT NULL THEN\n                                prha.interface_source_code\n                            ELSE\n                                'Manual'\n                        END\n                    FROM\n                        apps.po_requisition_headers_all    prha, apps.po_requisition_lines_all      prla\n                    WHERE\n                            prha.requisition_header_id = prla.requisition_header_id\n                        AND prha.org_id = prla.org_id\n                        AND prla.item_id = ms.item_id\n                        AND prla.requisition_line_id = ms.req_line_id\n                )\n        END,\n        CASE\n            WHEN po_distribution_id > 0 THEN\n                (\n                    SELECT\n                        CASE\n                            WHEN prha.interface_source_code = 'INV'\n                                 AND nvl(prla.kanban_card_id, 0) > 0 THEN\n                                CASE\n                                    WHEN(\n                                        SELECT\n                                            COUNT(1)\n                                        FROM\n                                            apps.mtl_kanban_cards mkc\n                                        WHERE\n                                                mkc.kanban_card_type = 1\n                                            AND prla.kanban_card_id = mkc.kanban_card_id\n                                    ) > 0 THEN\n                                        'Kanban'\n                                    ELSE\n                                        'NR Kanban'\n                                END\n                            WHEN prha.interface_source_code = 'INV'\n                                 AND nvl(prla.kanban_card_id, 0) = 0 THEN\n                                'Min Max'\n                            WHEN prha.interface_source_code = 'MSC'\n                                 AND nvl(prla.kanban_card_id, 0) = 0 THEN\n                                'MRP'\n                            WHEN prha.interface_source_code IS NULL\n                                 AND prha.approved_date IS NOT NULL\n                                 AND prla.item_id IS NULL THEN\n                                'iProcurement'\n                            WHEN prha.interface_source_code IS NULL\n                                 AND prha.approved_date IS NOT NULL THEN\n                                'Manual'\n                            WHEN prha.interface_source_code IS NOT NULL THEN\n                                prha.interface_source_code\n                            ELSE\n                                'Manual'\n                        END\n                    FROM\n                        apps.po_requisition_headers_all    prha, apps.po_requisition_lines_all      prla, apps.po_req_distributions_all      prda,\n                        apps.po_distributions_all          pda\n                    WHERE\n                            prha.requisition_header_id = prla.requisition_header_id\n                        AND prha.org_id = prla.org_id\n                        AND prla.item_id = ms.item_id\n                        AND prda.requisition_line_id = prla.requisition_line_id\n                        AND pda.req_distribution_id = prda.distribution_id\n                        AND pda.po_distribution_id = ms.po_distribution_id\n                )\n        END\n    ), 'Manual') trigger_source,\n    nvl(\n        CASE\n            WHEN req_line_id > 0 THEN\n                (\n                    SELECT\n                        mkc.kanban_card_number\n                    FROM\n                        apps.po_requisition_headers_all    prha, apps.po_requisition_lines_all      prla, apps.mtl_kanban_cards              mkc\n                    WHERE\n                            prha.requisition_header_id = prla.requisition_header_id\n                        AND prha.org_id = prla.org_id\n                        AND prla.item_id = ms.item_id\n                        AND prla.requisition_line_id = ms.req_line_id\n                        AND mkc.kanban_card_id = prla.kanban_card_id\n                )\n        END,\n        CASE\n            WHEN po_distribution_id > 0 THEN\n                (\n                    SELECT\n                        mkc.kanban_card_number\n                    FROM\n                        apps.po_requisition_headers_all    prha, apps.po_requisition_lines_all      prla,\n                        apps.po_req_distributions_all      prda, apps.po_distributions_all          pda, apps.mtl_kanban_cards              mkc\n                    WHERE\n                            prha.requisition_header_id = prla.requisition_header_id\n                        AND prha.org_id = prla.org_id\n                        AND prla.item_id = ms.item_id\n                        AND prda.requisition_line_id = prla.requisition_line_id\n                        AND pda.req_distribution_id = prda.distribution_id\n                        AND pda.po_distribution_id = ms.po_distribution_id\n                        AND mkc.kanban_card_id = prla.kanban_card_id\n                )\n        END\n    ) kanban_card_number,\n    nvl(\n        CASE\n            WHEN req_line_id > 0 THEN\n                (\n                    SELECT\n                        mkc.kanban_card_id\n                    FROM\n                        apps.po_requisition_headers_all    prha, apps.po_requisition_lines_all      prla, apps.mtl_kanban_cards              mkc\n                    WHERE\n                            prha.requisition_header_id = prla.requisition_header_id\n                        AND prha.org_id = prla.org_id\n                        AND prla.item_id = ms.item_id\n                        AND prla.requisition_line_id = ms.req_line_id\n                        AND mkc.kanban_card_id = prla.kanban_card_id\n                )\n        END,\n        CASE\n            WHEN po_distribution_id > 0 THEN\n                (\n                    SELECT\n                        mkc.kanban_card_id\n                    FROM\n                        apps.po_requisition_headers_all    prha, apps.po_requisition_lines_all      prla,\n                        apps.po_req_distributions_all      prda, apps.po_distributions_all          pda, apps.mtl_kanban_cards              mkc\n                    WHERE\n                            prha.requisition_header_id = prla.requisition_header_id\n                        AND prha.org_id = prla.org_id\n                        AND prla.item_id = ms.item_id\n                        AND prda.requisition_line_id = prla.requisition_line_id\n                        AND pda.req_distribution_id = prda.distribution_id\n                        AND pda.po_distribution_id = ms.po_distribution_id\n                        AND mkc.kanban_card_id = prla.kanban_card_id\n                )\n        END\n    ) kanban_card_id,\n    ms.to_subinventory\nFROM\n    inv.mtl_supply            ms,\n    inv.mtl_system_items_b    msi,\n    inv.mtl_parameters        mp\nWHERE\n        1 = 1\n    AND msi.organization_id = ms.to_organization_id\n    AND msi.organization_id = mp.organization_id\n    AND msi.inventory_item_id = ms.item_id\n    AND mp.organization_code = '\"&ORG&\"'\n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"EXTRACT_DATE\", \"Extract Date\"}, {\"CREATION_DATE\", \"Creation Date\"}, {\"ITEM_NUMBER\", \"Item Number\"}, {\"ORGANIZATION_CODE\", \"Organization Code\"}, {\"SOURCE_ORG\", \"Source Org Code\"}, {\"SUPPLY_TYPE_CODE\", \"Supply Type Code\"}, {\"SUPPLY_STATUS\", \"Status Code\"}, {\"SUPPLY_QUANTITY\", \"Quantity\"}, {\"SUPPLY_NEED_BY_DATE\", \"Need By Date\"}, {\"RECEIPT_DATE\", \"Expected Receipt Date\"}, {\"DELIVERY_STATUS\", \"Delivery Status\"}, {\"SUPPLY_DOCUMENT_NUMBER\", \"Document Number\"}, {\"INTERNAL_ORDER_NUMBER\", \"Internal Order Number\"}, {\"TRIGGER_SOURCE\", \"Trigger Source\"}, {\"KANBAN_CARD_NUMBER\", \"Kanban Card Number\"}, {\"TO_SUBINVENTORY\", \"To Subinventory\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Cycle_Count_Activity = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, Query=\"\n   SELECT\n   sysdate extract_date,\n   al1.organization_code,\n   al3.cycle_count_header_name cycle_count_name,\n   al3.description cycle_count_description,\n   al3.disable_date,\n   al8.count_list_sequence,\n   al6.inventory_item_id,\n   al6.segment1 item_number,\n   al2.abc_class_name,\n   al8.subinventory,\n   al7.concatenated_segments locator,\n   al8.lot_number,\n   al8.serial_number,\n   al9.meaning count_status,\n   al8.creation_date,\n   al8.count_due_date,\n   al8.system_quantity_current,\n   al8.count_quantity_current,\n   al8.count_uom_current,\n   al8.count_date_current,\n   al10.full_name current_count_by,\n   al8.system_quantity_prior,\n   al8.count_quantity_prior,\n   al8.count_uom_prior,\n   al8.count_date_prior,\n   al12.full_name prior_count_by,\n   al8.system_quantity_first,\n   al8.count_quantity_first,\n   CASE\n      WHEN\n         al8.count_quantity_first IS NOT NULL \n      THEN\n         CASE\n            WHEN\n               (\n                  nvl(al8.system_quantity_first, 0) - nvl(al8.count_quantity_first, 0) \n               )\n               <> 0 \n            THEN\n               'Fail First Count' \n            ELSE\n               'Pass First Count' \n         END\n         ELSE\n            'Not Counted' \n   END\n   first_pass_status, al8.count_uom_first, al8.count_date_first, al13.full_name first_count_by, al8.adjustment_quantity, \n   CASE\n      WHEN\n         al8.count_quantity_first IS NOT NULL \n      THEN\n         CASE\n            WHEN\n               nvl(al8.adjustment_quantity, 0) <> 0 \n            THEN\n               'Fail Count' \n            ELSE\n               'Pass Count' \n         END\n         ELSE\n            'Not Counted' \n   END\n   count_pass_status, al8.adjustment_date, \n   al8.adjustment_amount, \n   al11.user_name last_updated_by, \n   al8.approval_date count_approval_date\nFROM\n   apps.mtl_parameters al1,\n   apps.mtl_abc_classes_all_v al2,\n   apps.mtl_cycle_count_headers_v al3,\n   apps.mtl_system_items_b al6,\n   apps.mtl_item_locations_kfv al7,\n   apps.mtl_cycle_count_entries_v al8,\n   apps.mfg_lookups al9,\n   apps.per_people_x al10,\n   apps.fnd_user al11,\n   apps.per_people_x al12,\n   apps.per_people_x al13 \nWHERE\n   al1.organization_code = '\"&ORG&\"' \n   AND al8.counted_by_employee_id_first = al13.person_id ( + ) \n   AND al8.counted_by_employee_id_current = al10.person_id ( + ) \n   AND al8.counted_by_employee_id_prior = al12.person_id ( + ) \n   AND al8.last_updated_by = al11.user_id ( + ) \n   AND al8.organization_id = al7.organization_id ( + ) \n   AND al8.locator_id = al7.inventory_location_id ( + ) \n   AND al8.cycle_count_header_id = al3.cycle_count_header_id \n   AND al8.inventory_item_id = al6.inventory_item_id \n   AND al8.organization_id = al6.organization_id \n   AND al8.entry_status_code = al9.lookup_code \n   AND al8.abc_class_id = al2.abc_class_id \n   AND al8.organization_id = al2.organization_id \n   AND al8.organization_id = al3.organization_id \n   AND al1.organization_id = al8.organization_id \n   AND al9.lookup_type = 'MTL_CC_ENTRY_STATUSES'\n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"EXTRACT_DATE\", \"Extract Date\"}, {\"ORGANIZATION_CODE\", \"Organization Code\"}, {\"CYCLE_COUNT_NAME\", \"Cycle Count Name\"}, {\"CYCLE_COUNT_DESCRIPTION\", \"Cycle Count Description\"}, {\"DISABLE_DATE\", \"Disable Date\"}, {\"COUNT_LIST_SEQUENCE\", \"Sequence\"}, {\"ITEM_NUMBER\", \"Item Number\"}, {\"ABC_CLASS_NAME\", \"Count ABC Class\"}, {\"SUBINVENTORY\", \"Subinventory\"}, {\"LOCATOR\", \"Locator\"}, {\"LOT_NUMBER\", \"Lot Number\"}, {\"SERIAL_NUMBER\", \"Serial Number\"}, {\"COUNT_STATUS\", \"Count Status\"}, {\"CREATION_DATE\", \"Creation Date\"}, {\"COUNT_DUE_DATE\", \"Due Date\"}, {\"SYSTEM_QUANTITY_CURRENT\", \"System Quantity\"}, {\"COUNT_QUANTITY_CURRENT\", \"Count Quantity\"}, {\"COUNT_UOM_CURRENT\", \"Count Unit of Measure\"}, {\"COUNT_DATE_CURRENT\", \"Count Date\"}, {\"CURRENT_COUNT_BY\", \"Count By\"}, {\"SYSTEM_QUANTITY_PRIOR\", \"System Quantity Prior\"}, {\"COUNT_QUANTITY_PRIOR\", \"Count Quantity Prior\"}, {\"COUNT_UOM_PRIOR\", \"Count Unit of Measure Prior\"}, {\"COUNT_DATE_PRIOR\", \"Count Date Prior\"}, {\"PRIOR_COUNT_BY\", \"Count Prior By\"}, {\"SYSTEM_QUANTITY_FIRST\", \"First Count System Quantity\"}, {\"COUNT_QUANTITY_FIRST\", \"First Count Quantity\"}, {\"COUNT_UOM_FIRST\", \"First Count Unit of Measure\"}, {\"COUNT_DATE_FIRST\", \"First Count Date\"}, {\"FIRST_COUNT_BY\", \"First Count By\"}, {\"ADJUSTMENT_QUANTITY\", \"Adjustment Quantity\"}, {\"ADJUSTMENT_DATE\", \"Adjustment Date\"}, {\"FIRST_PASS_STATUS\", \"First Pass Status\"}, {\"COUNT_PASS_STATUS\", \"Count Pass Status\"}, {\"ADJUSTMENT_AMOUNT\", \"Adjustment Amount\"}, {\"LAST_UPDATED_BY\", \"Last Updated By\"}, {\"COUNT_APPROVAL_DATE\", \"Approval Date\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Receipt = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, \n  Query=\"\n  SELECT\n    sysdate              extract_date,\n    mp.organization_code,\n    rsh.receipt_num,\n    rsl.line_num         receipt_line_number,\n    rsh.receipt_source_code,\n    rt.source_document_code,\n    rsh.freight_carrier_code,\n    rsh.expected_receipt_date,\n    rsh.shipment_num     receipt_shipment_number,\n    rsh.waybill_airbill_num,\n    rsl.item_description,\n    rsl.item_id,\n    rt.requisition_line_id,\n    nvl(\n            decode(plla.consigned_flag, 'Y', 'Yes', 'No'),'No') consigned_receipt,\n    CASE\n        WHEN rt.source_document_code = 'PO'\n             AND rt.po_release_id IS NULL THEN\n            (\n                SELECT\n                    pha.segment1\n                FROM\n                    po.po_headers_all pha\n                WHERE\n                    pha.po_header_id = rt.po_header_id\n                    AND ROWNUM = 1\n            )\n        WHEN rt.source_document_code = 'PO'\n             AND rt.po_release_id IS NOT NULL THEN\n            (\n                SELECT\n                    pha.segment1\n                    || '_'\n                    || pra.release_num\n                FROM\n                    po.po_headers_all    pha,\n                    po.po_releases_all   pra\n                WHERE\n                    pha.po_header_id = pra.po_header_id\n                    AND rt.po_header_id = pha.po_header_id\n                    AND rt.po_release_id = pra.po_release_id\n                    AND ROWNUM = 1\n            )\n        WHEN rt.source_document_code = 'REQ' THEN\n            (\n                SELECT\n                    prha.segment1\n                FROM\n                    po.po_requisition_headers_all   prha,\n                    po.po_requisition_lines_all     prla\n                WHERE\n                    prha.requisition_header_id = prla.requisition_header_id\n                    AND prla.requisition_line_id = rt.requisition_line_id\n                    AND ROWNUM = 1\n            )\n        WHEN rt.source_document_code = 'RMA' THEN\n            (\n                SELECT\n                    to_char(oeh.order_number)\n                FROM\n                    ont.oe_order_headers_all oeh\n                WHERE\n                    oeh.header_id = rt.oe_order_header_id\n                    AND ROWNUM = 1\n            )\n    END receipt_source_document,\n    rsh.vendor_id,\n    rsh.vendor_site_id,\n    rt.transaction_id,\n    rt.shipment_line_id,\n    (\n        SELECT\n            routing_name\n        FROM\n            apps.rcv_routing_headers rrh\n        WHERE\n            rrh.routing_header_id = rt.routing_header_id\n    ) receipt_routing,\n    msi.segment1         item_number,\n    rt.transaction_date,\n    rt.transaction_type,\n    rt.currency_code,\n    (\n        SELECT\n            rate_to_usd\n        FROM\n            xxdims.xx_budget_rate br\n        WHERE\n            br.currency_code = rt.currency_code\n    ) usd_budget_rate,\n    CASE\n        WHEN rt.transaction_type = 'RETURN TO VENDOR' THEN\n            rt.quantity * - 1\n        ELSE\n            rt.quantity\n    END receipt_quantity,\n    CASE\n        WHEN rt.transaction_type = 'RETURN TO VENDOR' THEN\n            rt.primary_quantity * - 1\n        ELSE\n            rt.primary_quantity\n    END primary_quantity,\n    rt.unit_of_measure   receipt_unit_of_measure,\n    rt.po_unit_price,\n    rt.po_line_location_id,\n    rt.destination_type_code,\n    pla.line_num po_line,\n    plla.shipment_num po_shipment,\n    case when plla.consigned_flag = 'Y' then 0\n    else (\n        SELECT\n            nvl(mmt.actual_cost,0)\n        FROM\n            inv.mtl_material_transactions   mmt,\n            apps.rcv_transactions           rt2\n        WHERE\n            mmt.rcv_transaction_id = rt2.transaction_id\n            AND rsl.shipment_line_id = rt2.shipment_line_id\n            AND ROWNUM = 1\n    ) end actual_cost,\n    (\n        CASE\n            WHEN (\n                SELECT\n                    SUM(to_org_primary_quantity)\n                FROM\n                    po.rcv_supply rs\n                WHERE\n                    rs.supply_type_code = 'RECEIVING'\n                    AND rt.transaction_id = rs.rcv_transaction_id\n            ) > 0 THEN\n                'Yes'\n            ELSE\n                'No'\n        END\n    ) pending_deliver_flag,\n    (\n        SELECT\n            SUM(to_org_primary_quantity)\n        FROM\n            po.rcv_supply rs\n        WHERE\n            rs.supply_type_code = 'RECEIVING'\n            AND rt.transaction_id = rs.rcv_transaction_id\n    ) pending_delivery_quantity,\n    (\n        CASE\n            WHEN (\n                SELECT\n                    SUM(to_org_primary_quantity)\n                FROM\n                    po.rcv_supply rs\n                WHERE\n                    rs.supply_type_code = 'RECEIVING'\n                    AND rt.transaction_id = rs.rcv_transaction_id\n            ) > 0 THEN\n                round(sysdate - rt.transaction_date, 0)\n            ELSE\n                0\n        END\n    ) pending_deliver_age_days,\n    (\n        SELECT\n            otd_need_by_date\n        FROM\n            xxfacts.xx_porec_fact_temp_otd otd\n        WHERE\n            otd.transaction_id = rt.transaction_id\n    ) otd_need_by_date,\n    (\n        SELECT\n            otd_promised_date\n        FROM\n            xxfacts.xx_porec_fact_temp_otd otd\n        WHERE\n            otd.transaction_id = rt.transaction_id\n    ) otd_promised_date,\n    (\n        SELECT\n            otd_orig_promised_date\n        FROM\n            xxfacts.xx_porec_fact_temp_otd otd\n        WHERE\n            otd.transaction_id = rt.transaction_id\n    ) otd_orig_promised_date,\n    (\n        SELECT\n            days_to_need_by_date\n        FROM\n            xxfacts.xx_porec_fact_temp_otd otd\n        WHERE\n            otd.transaction_id = rt.transaction_id\n    ) days_to_need_by_date,\n    (\n        SELECT\n            days_to_promised_date\n        FROM\n            xxfacts.xx_porec_fact_temp_otd otd\n        WHERE\n            otd.transaction_id = rt.transaction_id\n    ) days_to_promised_date,\n    (\n        SELECT\n            days_to_orig_promised_date\n        FROM\n            xxfacts.xx_porec_fact_temp_otd otd\n        WHERE\n            otd.transaction_id = rt.transaction_id\n    ) days_to_orig_promised_date,\n    CASE\n        WHEN rt.source_document_code IN (\n            'REQ',\n            'RMA'\n        ) THEN\n            'INVENTORY'\n        ELSE\n            (\n                SELECT\n                    destination_type_code\n                FROM\n                    apps.po_distributions_all pda\n                WHERE\n                    pda.line_location_id = rt.po_line_location_id\n                    AND ROWNUM = 1\n            )\n    END destination_type,\n    (\n        SELECT\n            transaction_type\n        FROM\n            apps.rcv_transactions rt2\n        WHERE\n            rt2.transaction_id = rt.parent_transaction_id\n    ) parent_transaction_type\nFROM\n    apps.rcv_transactions               rt,\n    apps.org_organization_definitions   mp,\n    inv.mtl_system_items_b              msi,\n    po.rcv_shipment_lines               rsl,\n    po.rcv_shipment_headers             rsh,\n    apps.po_lines_all pla,\n    apps.po_line_locations_all plla\nWHERE\n    mp.organization_id = rt.organization_id\n    and rt.po_line_id = pla.po_line_id (+)\n    and rt.po_line_location_id = plla.line_location_id (+)\n    AND mp.organization_code = '\"&ORG&\"' \n    AND rt.transaction_type IN (\n        'RECEIVE',\n        'CORRECT',\n        'RETURN TO VENDOR'\n    )\n    AND rt.shipment_line_id = rsl.shipment_line_id\n    AND rt.shipment_header_id = rsh.shipment_header_id\n    AND rsh.shipment_header_id = rsl.shipment_header_id\n    AND rsh.ship_to_org_id = rt.organization_id\n    AND rt.organization_id = msi.organization_id (+)\n    AND rsl.item_id = msi.inventory_item_id (+)\n    AND EXISTS (\n        SELECT\n            1\n        FROM\n            apps.rcv_transactions rt2\n        WHERE\n            rt2.transaction_type in( 'RECEIVE','RETURN TO VENDOR')\n            AND ( rt2.transaction_id = rt.parent_transaction_id\n                  OR rt2.transaction_id = rt.transaction_id )\n    )\n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"EXTRACT_DATE\", \"Extract Date\"}, {\"CONSIGNED_RECEIPT\", \"Consigned Flag\"}, {\"ORGANIZATION_CODE\", \"Organization Code\"}, {\"RECEIPT_NUM\", \"Receipt Number\"}, {\"RECEIPT_LINE_NUMBER\", \"Line Number\"}, {\"ITEM_DESCRIPTION\", \"Item Description\"}, {\"RECEIPT_SOURCE_CODE\", \"Source Code\"}, {\"SOURCE_DOCUMENT_CODE\", \"Source Document\"}, {\"FREIGHT_CARRIER_CODE\", \"Freight Carrier\"}, {\"EXPECTED_RECEIPT_DATE\", \"Expected Date\"}, {\"RECEIPT_SHIPMENT_NUMBER\", \"Shipment Number\"}, {\"WAYBILL_AIRBILL_NUM\", \"Waybill\"}, {\"RECEIPT_SOURCE_DOCUMENT\", \"Source Document Number\"}, {\"ITEM_NUMBER\", \"Item Number\"}, {\"TRANSACTION_DATE\", \"Transaction Date\"}, {\"TRANSACTION_TYPE\", \"Transaction Type\"}, {\"CURRENCY_CODE\", \"Currency Code\"}, {\"PO_UNIT_PRICE\", \"PO Unit Price\"}, {\"RECEIPT_QUANTITY\", \"Quantity\"}, {\"PRIMARY_QUANTITY\", \"Primary Quantity\"}, {\"RECEIPT_UNIT_OF_MEASURE\", \"Unit of Measure\"}, {\"PENDING_DELIVER_FLAG\", \"Pending Deliver Flag\"}, {\"PENDING_DELIVER_AGE_DAYS\", \"Pending Deliver Age Days\"}, {\"DESTINATION_TYPE_CODE\", \"Receipt Destination Type\"}, {\"ACTUAL_COST\", \"Actual Cost\"}, {\"RECEIPT_ROUTING\", \"Receipt Routing\"}, {\"OTD_NEED_BY_DATE\", \"OTD Need By Date\"}, {\"OTD_PROMISED_DATE\", \"OTD Promised Date\"}, {\"OTD_ORIG_PROMISED_DATE\", \"OTD Original Promised Date\"}, {\"DAYS_TO_NEED_BY_DATE\", \"Days To Need By Date\"}, {\"DAYS_TO_PROMISED_DATE\", \"Days To Promised Date\"}, {\"DAYS_TO_ORIG_PROMISED_DATE\", \"Days To Original Promised Date\"}, {\"PENDING_DELIVERY_QUANTITY\", \"Pending Deliver Quantity\"}, {\"DESTINATION_TYPE\", \"Destination Type\"}, {\"USD_BUDGET_RATE\", \"USD Budget Rate\"}, {\"PARENT_TRANSACTION_TYPE\", \"Parent Transaction Type\"}, {\"PO_LINE\", \"PO Line\"}, {\"PO_SHIPMENT\", \"PO Shipment\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Serial_Status = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, \n  Query=\"\n  SELECT\n    sysdate         extract_date,\n    mp.organization_code,\n    (\n        SELECT\n            mp2.organization_code\n        FROM\n            apps.mtl_parameters mp2\n        WHERE\n            mp2.organization_id = msn.current_organization_id\n    ) current_organization,\n    ml.meaning      serial_number_status,\n    msi.inventory_item_id,\n    msi.segment1    item_number,\n    msn.serial_number,\n    msn.completion_date,\n    msn.ship_date,\n    (\n        SELECT\n            segment1\n        FROM\n            apps.mtl_system_items_b    msi2,\n            apps.mtl_parameters        mp3\n        WHERE\n                msi2.organization_id = mp3.organization_id\n            AND mp3.organization_code = 'MAS'\n            AND msn.parent_item_id = msi2.inventory_item_id\n    ) parent_item,\n    parent_serial_number,\n    current_subinventory_code,\n    (\n        SELECT\n            concatenated_segments\n        FROM\n            apps.mtl_item_locations_kfv mil\n        WHERE\n                mil.inventory_location_id = msn.current_locator_id\n            AND msn.current_organization_id = mil.organization_id\n            AND msn.current_subinventory_code = mil.subinventory_code\n    ) current_locator,\n    (\n        SELECT\n            wip_entity_name\n        FROM\n            apps.wip_entities we\n        WHERE\n            we.wip_entity_id = msn.original_wip_entity_id\n    ) original_job_number,\n    (\n        SELECT\n            mp4.organization_code\n        FROM\n            apps.wip_entities      we,\n            apps.mtl_parameters    mp4\n        WHERE\n                we.wip_entity_id = msn.original_wip_entity_id\n            AND mp4.organization_id = we.organization_id\n    ) original_job_org,\n    (\n        SELECT\n            tst.transaction_source_type_name\n        FROM\n            inv.mtl_txn_source_types tst\n        WHERE\n            tst.transaction_source_type_id = msn.last_txn_source_type_id\n    ) last_transaction_source,\n    msn.last_txn_source_name,\n    CASE\n        WHEN msn.last_txn_source_type_id = 1     THEN\n            (\n                SELECT\n                    pha.segment1\n                FROM\n                    apps.po_headers_all pha\n                WHERE\n                    pha.po_header_id = msn.last_txn_source_id\n            )\n        WHEN msn.last_txn_source_type_id = 2     THEN\n            (\n                SELECT\n                    segment1\n                FROM\n                    apps.mtl_sales_orders\n                WHERE\n                    sales_order_id = msn.last_txn_source_id\n            )\n        WHEN msn.last_txn_source_type_id = 4     THEN\n            (\n                SELECT\n                    request_number\n                FROM\n                    apps.mtl_txn_request_headers mtrh\n                WHERE\n                        request_number = to_char(msn.last_txn_source_id)\n                    AND mtrh.organization_id = msn.current_organization_id\n            )\n        WHEN msn.last_txn_source_type_id = 5     THEN\n            (\n                SELECT\n                    wip_entity_name\n                FROM\n                    apps.wip_entities\n                WHERE\n                    wip_entity_id = msn.last_txn_source_id\n            )\n        WHEN msn.last_txn_source_type_id = 6     THEN\n            (\n                SELECT\n                    segment1\n                FROM\n                    apps.mtl_generic_dispositions mgd\n                WHERE\n                    mgd.disposition_id = msn.last_txn_source_id\n            )\n        WHEN msn.last_txn_source_type_id = 7     THEN\n            (\n                SELECT\n                    rcv.shipment_num\n                FROM\n                    apps.rcv_shipment_headers    rcv,\n                    apps.rcv_transactions        rcvt\n                WHERE\n                        rcv.shipment_header_id = rcvt.shipment_header_id\n                    AND rcvt.transaction_id = msn.last_txn_source_id\n            )\n        WHEN msn.last_txn_source_type_id = 8     THEN\n            (\n                SELECT\n                    segment1\n                FROM\n                    apps.mtl_sales_orders\n                WHERE\n                    sales_order_id = msn.last_txn_source_id\n            )\n        WHEN msn.last_txn_source_type_id = 10    THEN\n            (\n                SELECT\n                    physical_inventory_name\n                FROM\n                    apps.mtl_physical_inventories\n                WHERE\n                    physical_inventory_id = msn.last_txn_source_id\n            )\n        WHEN msn.last_txn_source_type_id = 13    THEN\n            (\n                SELECT\n                    wip_entity_name\n                FROM\n                    apps.wip_entities\n                WHERE\n                    wip_entity_id = msn.last_txn_source_id\n            )\n        ELSE\n            NULL\n    END last_txn_source_document,\n    msn.reservation_id,\n    (\n        SELECT\n            receipt_num\n        FROM\n            apps.rcv_shipment_headers       rsh,\n            apps.rcv_transactions           rt,\n            apps.rcv_shipment_lines         rsl,\n            apps.rcv_serial_transactions    rst\n        WHERE\n                rsh.shipment_header_id = rt.shipment_header_id\n            AND rt.transaction_id = rst.transaction_id\n            AND rsl.shipment_line_id = rst.shipment_line_id\n            AND rsl.item_id = msn.inventory_item_id\n            AND rt.organization_id = msn.current_organization_id\n            AND rst.serial_num = msn.serial_number\n            AND usage_status_code = 'CURRENT'\n            AND serial_transaction_type = 'TRANSACTION'\n            AND rt.transaction_type = 'DELIVER'\n            AND rt.organization_id = mp.organization_id\n            AND ROWNUM = 1\n    ) last_receipt_number\nFROM\n    apps.mtl_serial_numbers    msn,\n    apps.mtl_system_items_b    msi,\n    apps.mtl_parameters        mp,\n    apps.mfg_lookups           ml\nWHERE\n        msi.inventory_item_id = msn.inventory_item_id\n    AND msi.organization_id = mp.organization_id\n    AND ml.lookup_code = msn.current_status\n    AND ml.lookup_type = 'SERIAL_NUM_STATUS'\n    AND msn.current_status <> 1\n    AND mp.organization_code = '\"&ORG&\"'\n    AND EXISTS (\n        SELECT\n            1\n        FROM\n            apps.mtl_unit_transactions mut\n        WHERE\n                mut.organization_id = mp.organization_id\n            AND mut.inventory_item_id = msn.inventory_item_id\n            AND mut.serial_number = msn.serial_number\n    )\n\"\n, CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"EXTRACT_DATE\", \"Extract Date\"}, {\"ORGANIZATION_CODE\", \"Organization Code\"}, {\"CURRENT_ORGANIZATION\", \"Current Organization Code\"}, {\"SERIAL_NUMBER_STATUS\", \"Serial Status\"}, {\"ITEM_NUMBER\", \"Item Number\"}, {\"SERIAL_NUMBER\", \"Serial Number\"}, {\"COMPLETION_DATE\", \"WIP Completion Date\"}, {\"SHIP_DATE\", \"Shipped Date\"}, {\"PARENT_ITEM\", \"Parent Item Number\"}, {\"PARENT_SERIAL_NUMBER\", \"Parent Serial Number\"}, {\"CURRENT_SUBINVENTORY_CODE\", \"Current Subinventory\"}, {\"CURRENT_LOCATOR\", \"Current Locator\"}, {\"ORIGINAL_JOB_NUMBER\", \"Original Job Number\"}, {\"ORIGINAL_JOB_ORG\", \"Original Job Organization\"}, {\"LAST_TRANSACTION_SOURCE\", \"Last Transaction Source\"}, {\"LAST_TXN_SOURCE_NAME\", \"Last Transaction Source Name\"}, {\"LAST_TXN_SOURCE_DOCUMENT\", \"Last Transaction Source Document\"}, {\"LAST_RECEIPT_NUMBER\", \"Last Receipt Number\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Material_Transaction = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, Query=\"\n SELECT\n    sysdate        extract_date,\n    mp.organization_code,\n    msi.inventory_item_id,\n    msi.segment1,\n    mmt.primary_quantity,\n    mmt.transaction_date,\n    mmt.transaction_id,\n    mtt.transaction_type_name,\n    flv.meaning    transaction_action,\n    mmt.subinventory_code,\n    mmt.transfer_subinventory,\n    tst.transaction_source_type_name,\n    mmt.transfer_transaction_id,\n    mmt.transaction_reference,\n    CASE\n        WHEN tst.transaction_source_type_name = 'Job or Schedule'\n             AND (\n            SELECT\n                COUNT(1)\n            FROM\n                apps.wip_discrete_jobs_v wdj\n            WHERE\n                wdj.wip_entity_id = mmt.transaction_source_id\n        ) = 0 THEN\n            'Work Orderless'\n        ELSE\n            tst.transaction_source_type_name\n    END source_type,\n    CASE\n        WHEN tst.transaction_source_type_name = 'Job or Schedule' THEN\n            CASE\n                WHEN (\n                    SELECT\n                        wdj.class_code\n                    FROM\n                        apps.wip_discrete_jobs_v wdj\n                    WHERE\n                            wdj.wip_entity_id = mmt.transaction_source_id\n                        AND tst.transaction_source_type_name = 'Job or Schedule'\n                ) IS NULL THEN\n                    (\n                        SELECT\n                            wdj.class_code\n                        FROM\n                            apps.wip_flow_schedules wdj\n                        WHERE\n                                wdj.wip_entity_id = mmt.transaction_source_id\n                            AND tst.transaction_source_type_name = 'Job or Schedule'\n                    )\n                ELSE\n                    (\n                        SELECT\n                            wdj.class_code\n                        FROM\n                            apps.wip_discrete_jobs_v wdj\n                        WHERE\n                                wdj.wip_entity_id = mmt.transaction_source_id\n                            AND tst.transaction_source_type_name = 'Job or Schedule'\n                    )\n            END\n    END wip_job_class,\n    CASE\n        WHEN mmt.transaction_source_type_id = 1     THEN\n            (\n                SELECT\n                    pha.segment1\n                FROM\n                    apps.po_headers_all pha\n                WHERE\n                    pha.po_header_id = mmt.transaction_source_id\n            )\n        WHEN mmt.transaction_source_type_id = 2     THEN\n            (\n                SELECT\n                    segment1\n                FROM\n                    apps.mtl_sales_orders\n                WHERE\n                    sales_order_id = mmt.transaction_source_id\n            )\n        WHEN mmt.transaction_source_type_id = 4     THEN\n            (\n                SELECT\n                    request_number\n                FROM\n                    apps.mtl_txn_request_headers mtrh\n                WHERE\n                        request_number = to_char(mmt.transaction_source_id)\n                    AND mtrh.organization_id = mmt.organization_id\n            )\n        WHEN mmt.transaction_source_type_id = 5     THEN\n            (\n                SELECT\n                    wip_entity_name\n                FROM\n                    apps.wip_entities\n                WHERE\n                    wip_entity_id = mmt.transaction_source_id\n            )\n        WHEN mmt.transaction_source_type_id = 6     THEN\n            (\n                SELECT\n                    segment1\n                FROM\n                    apps.mtl_generic_dispositions mgd\n                WHERE\n                    mgd.disposition_id = mmt.transaction_source_id\n            )\n        WHEN mmt.transaction_source_type_id = 7     THEN\n            (\n                SELECT\n                    rcv.shipment_num\n                FROM\n                    apps.rcv_shipment_headers    rcv,\n                    apps.rcv_transactions        rcvt\n                WHERE\n                        rcv.shipment_header_id = rcvt.shipment_header_id\n                    AND rcvt.transaction_id = mmt.transaction_source_id\n            )\n        WHEN mmt.transaction_source_type_id = 8     THEN\n            (\n                SELECT\n                    segment1\n                FROM\n                    apps.mtl_sales_orders\n                WHERE\n                    sales_order_id = mmt.transaction_source_id\n            )\n        WHEN mmt.transaction_source_type_id = 10    THEN\n            (\n                SELECT\n                    physical_inventory_name\n                FROM\n                    apps.mtl_physical_inventories\n                WHERE\n                    physical_inventory_id = mmt.transaction_source_id\n            )\n        WHEN mmt.transaction_source_type_id = 13    THEN\n            (\n                SELECT\n                    wip_entity_name\n                FROM\n                    apps.wip_entities\n                WHERE\n                    wip_entity_id = mmt.transaction_source_id\n            )\n        ELSE\n            NULL\n    END source_document,\n    CASE\n        WHEN flv.meaning = 'Ownership Transfer' THEN\n            'Ownership Transfer'\n        WHEN flv.meaning IN (\n            'Subinventory transfer',\n            'Staging transfer'\n        )\n             AND (\n            SELECT\n                mseci2.quantity_tracked\n            FROM\n                inv.mtl_secondary_inventories mseci2\n            WHERE\n                    mseci2.secondary_inventory_name = mmt.transfer_subinventory\n                AND mseci2.organization_id = mmt.organization_id\n        ) = 1 THEN\n            'Transfer'\n        WHEN flv.meaning IN (\n            'Cycle count adjustment',\n            'Assembly return',\n            'Delivery Adjustments',\n            'Negative component issues',\n            'Negative component return'\n        ) THEN\n            'Adjustments'\n        WHEN mtt.transaction_type_name IN (\n            'WIP Return'\n        ) THEN\n            'Adjustments'\n        WHEN flv.meaning IN (\n            'Subinventory transfer',\n            'Staging transfer'\n        )\n             AND mmt.transaction_quantity < 0\n             AND (\n            SELECT\n                mseci2.quantity_tracked\n            FROM\n                inv.mtl_secondary_inventories mseci2\n            WHERE\n                    mseci2.secondary_inventory_name = mmt.transfer_subinventory\n                AND mseci2.organization_id = mmt.organization_id\n        ) = 2 THEN\n            'Usage'\n        WHEN flv.meaning IN (\n            'Issue from stores',\n            'Intransit shipment'\n        )\n             AND mtt.transaction_type_name IN (\n            'WIP Issue',\n            'Sales order issue',\n            'Internal order issue',\n            'Move order issue',\n            'Field Service Usage'\n        ) THEN\n            'Usage'\n        WHEN mtt.transaction_type_name IN (\n            'Return to Vendor',\n            'RMA Return',\n            'Return to Vendor without Receipt',\n            'LC Return'\n        ) THEN\n            'Return'\n        WHEN mtt.transaction_type_name IN (\n            'Account issue',\n            'Account alias issue',\n            'Miscellaneous issue'\n        ) THEN\n            'Miscellaneous out'\n        WHEN mtt.transaction_type_name IN (\n            'Account receipt',\n            'Account alias receipt',\n            'Miscellaneous receipt'\n        ) THEN\n            'Miscellaneous in'\n        WHEN flv.meaning IN (\n            'Receipt into stores',\n            'Intransit receipt'\n        )\n             AND mmt.transaction_quantity > 0 THEN\n            'Receipt'\n        ELSE\n            'Other'\n    END transaction_classification,\n    mmt.actual_cost,\n    (\n        SELECT\n            user_name\n        FROM\n            apps.fnd_user fu\n        WHERE\n            fu.user_id = mmt.created_by\n    ) created_by\nFROM\n    apps.mtl_material_transactions    mmt,\n    apps.mtl_transaction_types        mtt,\n    inv.mtl_parameters                mp,\n    inv.mtl_system_items_b            msi,\n    fnd_lookup_values                 flv,\n    inv.mtl_secondary_inventories     mseci,\n    inv.mtl_txn_source_types          tst\nWHERE\n        mmt.transaction_type_id = mtt.transaction_type_id\n    AND mp.organization_id = mmt.organization_id\n    AND msi.inventory_item_id = mmt.inventory_item_id\n    AND flv.language = 'US'\n    AND msi.organization_id = mp.organization_id\n    AND flv.lookup_code = mtt.transaction_action_id\n    AND flv.lookup_type = 'MTL_TRANSACTION_ACTION'\n    AND mseci.secondary_inventory_name = mmt.subinventory_code\n    AND tst.transaction_source_type_id = mtt.transaction_source_type_id\n    AND mseci.organization_id = mmt.organization_id\n    AND mmt.transaction_date >= (\n        SELECT\n            gp.year_start_date\n        FROM\n            gl.gl_date_period_map    gdpm,\n            gl.gl_periods            gp\n        WHERE\n                gdpm.period_set_name = 'COHR Calendar'\n            AND gp.period_name = gdpm.period_name\n            AND gdpm.period_set_name = gp.period_set_name\n            AND gdpm.accounting_date = trunc(sysdate)\n    )\n    AND mp.organization_code = '\"&ORG&\"'\n    AND transaction_quantity <> 0\n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"ORGANIZATION_CODE\", \"Organization Code\"}, {\"SEGMENT1\", \"Item Number\"}, {\"PRIMARY_QUANTITY\", \"Primary Transaction Quantity\"}, {\"TRANSACTION_DATE\", \"Transaction Date\"}, {\"TRANSACTION_TYPE_NAME\", \"Transaction Type Name\"}, {\"TRANSACTION_ACTION\", \"Transaction Action\"}, {\"SUBINVENTORY_CODE\", \"Transaction Subinventory\"}, {\"TRANSFER_SUBINVENTORY\", \"Transfer Subinventory\"}, {\"TRANSACTION_SOURCE_TYPE_NAME\", \"Transaction Source Type Name\"}, {\"TRANSACTION_REFERENCE\", \"Transaction Reference\"}, {\"SOURCE_TYPE\", \"Calculated Transaction Source Type\"}, {\"SOURCE_DOCUMENT\", \"Source Document Number\"}, {\"TRANSACTION_CLASSIFICATION\", \"Transaction Classification\"}, {\"ACTUAL_COST\", \"Actual Cost\"}, {\"WIP_JOB_CLASS\", \"WIP Accounting Class\"}, {\"EXTRACT_DATE\", \"Extract Date\"}, {\"CREATED_BY\", \"Created By\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Receiving_Default = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, Query=\"\n SELECT SYSDATE                extract_date, \n       mp.organization_code, \n       msi.inventory_item_id, \n       msi.segment1           ITEM_NUMBER, \n       MISD.subinventory_code DEFAULT_RECEIVING_SUBINVENTORY\n       , \n       (SELECT MILK.concatenated_segments \n        FROM   apps.mtl_item_locations_kfv milk \n        WHERE  milk.inventory_location_id = mild.locator_id \n               AND milk.organization_id = mild.organization_id \n               AND milk.subinventory_code = mild.subinventory_code) \n                              DEFAULT_RECEIVING_LOCATOR, \n       CASE \n         WHEN MSECI.locator_type = 2 \n              AND MILD.locator_id IS NULL THEN 'Incomplete' \n         ELSE 'Complete' \n       END                    DEFAULT_RECEIVING_VALIDATION \nFROM   apps.mtl_item_sub_defaults misd, \n       inv.mtl_parameters mp, \n       inv.mtl_system_items_b msi, \n       inv.mtl_item_loc_defaults mild, \n       inv.mtl_secondary_inventories MSECI \nWHERE  1=1\n       AND mp.organization_id = misd.organization_id \n       AND msi.organization_id = mp.organization_id \n       AND mseci.organization_id = MISD.organization_id \n       AND mseci.secondary_inventory_name = MISD.subinventory_code \n       AND msi.inventory_item_id = misd.inventory_item_id \n       AND msi.inventory_item_id = mild.inventory_item_id (+) \n       AND msi.organization_id = mild.organization_id (+) \n       AND misd.subinventory_code = mild.subinventory_code (+) \n       AND misd.default_type = mild.default_type (+) \n       AND misd.default_type = 2  \n       AND mp.organization_code = '\"&ORG&\"'\n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"EXTRACT_DATE\", \"Extract Date\"}, {\"ORGANIZATION_CODE\", \"Organization Code\"}, {\"ITEM_NUMBER\", \"Item Number\"}, {\"DEFAULT_RECEIVING_SUBINVENTORY\", \"Default Receiving Subinventory\"}, {\"DEFAULT_RECEIVING_LOCATOR\", \"Default Receiving Locator\"}, {\"DEFAULT_RECEIVING_VALIDATION\", \"Default Receiving Validation\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Consumption_Advice = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, \n  Query=\"\nSELECT\n   SYSDATE EXTRACT_DATE,\n   MP.ORGANIZATION_CODE,\n   MMT.TRANSACTION_ID,\n   PHA.VENDOR_ID,\n   PHA.VENDOR_SITE_ID,\n   PLA.ITEM_ID,\n   MSI.SEGMENT1 ITEM_NUMBER,\n   MSI.DESCRIPTION ITEM_DESCRIPTION,\n   'VENDOR' SOURCE_CODE,\n   'PO' SOURCE_DOCUMENT,\n   'No' CONSIGNED_FLAG,\n   CASE\n      WHEN\n         NVL(MCT.CONSUMPTION_RELEASE_ID, 0) = 0 \n      THEN\n         PHA.SEGMENT1 \n      WHEN\n         NVL(MCT.CONSUMPTION_RELEASE_ID, 0) > 0 \n      THEN\n         PHA.SEGMENT1 || '_' || (\n         SELECT\n            RELEASE_NUM \n         FROM\n            APPS.PO_RELEASES_ALL PRA \n         WHERE\n            PRA.PO_RELEASE_ID = MCT.CONSUMPTION_RELEASE_ID) \n   END\n   SOURCE_DOCUMENT_NUMBER,\n   MMT.TRANSACTION_DATE,\n   MMT.TRANSACTION_QUANTITY * - 1 QUANTITY,\n   UOM.UNIT_OF_MEASURE,\n   MMT.PRIMARY_QUANTITY * - 1 PRIMARY_QUANTITY,\n   PDA.LINE_LOCATION_ID PO_LINE_LOCATION_ID,\n   MCT.PO_DISTRIBUTION_ID,\n   MTT.TRANSACTION_TYPE_NAME TRANSACTION_TYPE,\n   'INVENTORY' DESTINATION_TYPE,\n   PHA.CURRENCY_CODE,\n   pla.line_num po_line,\n   (select mmt2.actual_cost from apps.mtl_material_transactions mmt2\n   where mmt2.transaction_id = mmt.transfer_transaction_id) actual_cost,\n   plla.shipment_num po_shipment,\n      (\n         SELECT\n            RATE_TO_USD \n         FROM\n            XXDIMS.XX_BUDGET_RATE BR \n         WHERE\n            BR.CURRENCY_CODE = PHA.CURRENCY_CODE\n      )\n      USD_BUDGET_RATE,\n      MCT.BLANKET_PRICE PO_UNIT_PRICE \n   FROM\n      APPS.MTL_CONSUMPTION_TRANSACTIONS MCT,\n      APPS.PO_DISTRIBUTIONS_ALL PDA,\n      APPS.PO_LINES_ALL PLA,\n      APPS.PO_LINE_LOCATIONS_ALL PLLA,\n      APPS.PO_HEADERS_ALL PHA,\n      APPS.MTL_MATERIAL_TRANSACTIONS MMT,\n      APPS.MTL_PARAMETERS MP,\n      APPS.MTL_TRANSACTION_TYPES MTT,\n      APPS.MTL_SYSTEM_ITEMS_B MSI,\n      APPS.MTL_UNITS_OF_MEASURE_VL UOM\n   WHERE\n      MCT.TRANSACTION_ID = MMT.TRANSACTION_ID \n      AND MCT.ORGANIZATION_ID = MP.ORGANIZATION_ID \n      AND MMT.ORGANIZATION_ID = MMT.ORGANIZATION_ID \n      AND MCT.PO_DISTRIBUTION_ID = PDA.PO_DISTRIBUTION_ID \n      AND PDA.PO_LINE_ID = PLA.PO_LINE_ID \n      AND PDA.PO_HEADER_ID = PHA.PO_HEADER_ID \n      AND UOM.UOM_CODE = MMT.TRANSACTION_UOM\n      AND PLLA.PO_LINE_ID = PLA.PO_LINE_ID\n      AND PDA.LINE_LOCATION_ID = PLLA.LINE_LOCATION_ID\n      AND MP.ORGANIZATION_CODE = '\"&ORG&\"' \n      AND MTT.TRANSACTION_TYPE_ID = MMT.TRANSACTION_TYPE_ID \n      AND MSI.INVENTORY_ITEM_ID = MMT.INVENTORY_ITEM_ID \n      AND MSI.ORGANIZATION_ID = MMT.ORGANIZATION_ID\n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"EXTRACT_DATE\", \"Extract Date\"}, {\"ORGANIZATION_CODE\", \"Organization Code\"}, {\"ITEM_NUMBER\", \"Item Number\"}, {\"ITEM_DESCRIPTION\", \"Item Description\"}, {\"SOURCE_CODE\", \"Source Code\"}, {\"SOURCE_DOCUMENT\", \"Source Document\"}, {\"SOURCE_DOCUMENT_NUMBER\", \"Source Document Number\"}, {\"UNIT_OF_MEASURE\", \"Unit of Measure\"}, {\"PRIMARY_QUANTITY\", \"Primary Quantity\"}, {\"TRANSACTION_TYPE\", \"Transaction Type\"}, {\"CURRENCY_CODE\", \"Currency Code\"}, {\"PO_UNIT_PRICE\", \"PO Unit Price\"}, {\"TRANSACTION_DATE\", \"Transaction Date\"}, {\"QUANTITY\", \"Quantity\"}, {\"USD_BUDGET_RATE\", \"USD Budget Rate\"}, {\"CONSIGNED_FLAG\", \"Consigned Flag\"}, {\"DESTINATION_TYPE\", \"Destination Type\"}, {\"PO_LINE\", \"PO Line\"}, {\"PO_SHIPMENT\", \"PO Shipment\"}, {\"ACTUAL_COST\", \"Actual Cost\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Open_WO = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, \n  Query=\"\n  SELECT\n    sysdate extract_Date,\n    mp.organization_code,\n    mkc.kanban_card_id,\n    mkc.kanban_card_number,\n    msi.inventory_item_id,\n    msi.segment1 Item_number,\n    'WO'                                                                           supply_type_code,\n    we.wip_entity_name                                                             supply_document_number,\n    'On Order'                                                                     supply_status,\n    CASE\n        WHEN wdj.scheduled_completion_date < sysdate + 1 THEN\n            'Late'\n        ELSE\n            'In Process'\n    END delivery_status,\n    wdj.scheduled_completion_date                                                  receipt_date,\n    wdj.scheduled_completion_date                                                  supply_need_by_date,\n    wdj.creation_date                                                              creation_date,\n    ( wdj.start_quantity - wdj.quantity_completed - wdj.quantity_scrapped )        supply_quantity,\n    CASE\n        WHEN mkc.kanban_card_id > 0 and mkc.kanban_card_type =1    THEN\n            'Kanban'\n        WHEN mkc.kanban_card_id > 0 THEN\n            'NR Kanban'\n        WHEN wdj.source_code = 'MSC'    THEN\n            'MRP'\n        WHEN we.description LIKE 'Job Mass Loaded%'\n             AND wdj.source_code IS NULL THEN\n            'Min Max'\n           when wdj.source_code is null then 'Manual'\n        ELSE\n           wdj.source_code\n    END trigger_source,\n    wdj.completion_Subinventory to_Subinventory\nFROM\n    apps.mtl_kanban_cards_v    mkc,\n    inv.mtl_parameters         mp,\n    inv.mtl_system_items_b     msi,\n    apps.wip_discrete_jobs     wdj,\n    apps.wip_entities          we\nWHERE\n        wdj.organization_id = mp.organization_id\n    AND msi.organization_id = mp.organization_id\n    AND mp.organization_code = '\"&ORG&\"'\n    AND wdj.kanban_card_id = mkc.kanban_card_id (+)\n    AND wdj.primary_item_id = msi.inventory_item_id\n    AND we.wip_entity_id = wdj.wip_entity_id\n    AND wdj.status_type IN (\n        1-- 'Released',\n        ,\n        3-- 'Unreleased'\n    )\n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"SUPPLY_TYPE_CODE\", \"Supply Type Code\"}, {\"SUPPLY_DOCUMENT_NUMBER\", \"Document Number\"}, {\"SUPPLY_QUANTITY\", \"Quantity\"}, {\"RECEIPT_DATE\", \"Expected Receipt Date\"}, {\"ORGANIZATION_CODE\", \"Organization Code\"}, {\"KANBAN_CARD_NUMBER\", \"Kanban Card Number\"}, {\"EXTRACT_DATE\", \"Extract Date\"}, {\"SUPPLY_STATUS\", \"Status Code\"}, {\"DELIVERY_STATUS\", \"Delivery Status\"}, {\"ITEM_NUMBER\", \"Item Number\"}, {\"SUPPLY_NEED_BY_DATE\", \"Need By Date\"}, {\"CREATION_DATE\", \"Creation Date\"}, {\"TRIGGER_SOURCE\", \"Trigger Source\"}, {\"TO_SUBINVENTORY\", \"To Subinventory\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Open_MO = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, \n  Query=\"\n  SELECT\n    sysdate extract_date,\n    mp.organization_code,\n    mkc.kanban_card_id,\n    mkc.kanban_card_number,\n    msi.segment1                                             item_number,\n    mtrl.inventory_item_id,\n    mtrl.request_number                                      supply_document_number,\n    mtrl.date_required                                       need_by_date,\n    mtrl.quantity - nvl(mtrl.quantity_delivered, 0)          supply_quantity,\n    'MO'                                                     supply_type_code,\n    'On Order'                                               supply_status,\n    mtrl.creation_date,\n    mtrl.date_required                                       receipt_date,\n    CASE\n        WHEN mtrl.date_required < sysdate + 1 THEN\n            'Late'\n        ELSE\n            'In Process'\n    END delivery_status,\n    CASE\n        WHEN mkc.kanban_card_id > 0 and mkc.kanban_card_type =1    THEN\n            'Kanban'\n         WHEN mkc.kanban_card_id > 0    THEN\n            'NR Kanban'\n        ELSE\n            'Min Max'\n    END trigger_source,\n    mtrl.to_subinventory_code\nFROM\n    apps.mtl_kanban_cards_v         mkc,\n    inv.mtl_parameters              mp,\n    inv.mtl_system_items_b          msi,\n    apps.mtl_txn_request_lines_v    mtrl\nWHERE\n        1 = 1\n    AND mp.organization_code = '\"&ORG&\"'\n    AND mtrl.line_status = 7\n    AND mtrl.inventory_item_id = msi.inventory_item_id\n    AND msi.organization_id = mp.organization_id\n    AND mtrl.organization_id = mp.organization_id\n    AND mtrl.reference_id = mkc.kanban_card_id (+)\n    AND mtrl.move_order_type = 2\n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"SUPPLY_TYPE_CODE\", \"Supply Type Code\"}, {\"SUPPLY_DOCUMENT_NUMBER\", \"Document Number\"}, {\"SUPPLY_QUANTITY\", \"Quantity\"}, {\"RECEIPT_DATE\", \"Expected Receipt Date\"}, {\"ORGANIZATION_CODE\", \"Organization Code\"}, {\"KANBAN_CARD_NUMBER\", \"Kanban Card Number\"}, {\"EXTRACT_DATE\", \"Extract Date\"}, {\"SUPPLY_STATUS\", \"Status Code\"}, {\"DELIVERY_STATUS\", \"Delivery Status\"}, {\"ITEM_NUMBER\", \"Item Number\"}, {\"CREATION_DATE\", \"Creation Date\"}, {\"NEED_BY_DATE\", \"Need By Date\"}, {\"TRIGGER_SOURCE\", \"Trigger Source\"}, {\"TO_SUBINVENTORY_CODE\", \"To Subinventory\"}})\r\nin\r\n  #\"Renamed columns\";\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"Kanban_Card","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Kanban_Card.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Organization Code","dataType":"string"},{"name":"KANBAN_CARD_ID","dataType":"double"},{"name":"Card Number","dataType":"string"},{"name":"Creation Date","dataType":"dateTime"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"Item Number","dataType":"string"},{"name":"Pull Sequence Id","dataType":"double"},{"name":"Effective Lead Time","dataType":"double"},{"name":"Subinventory","dataType":"string"},{"name":"Locator","dataType":"string"},{"name":"Source Org","dataType":"string"},{"name":"Source Subinventory","dataType":"string"},{"name":"Card Type","dataType":"string"},{"name":"Card Size","dataType":"double"},{"name":"Source Type","dataType":"string"},{"name":"Supply Status","dataType":"string"},{"name":"SUPPLY_STATUS_ID","dataType":"double"},{"name":"Last Replenish Date","dataType":"dateTime"},{"name":"Replenish Count","dataType":"double"},{"name":"Last Empty Date","dataType":"dateTime"},{"name":"Last Activity Age Days","dataType":"double"},{"name":"Source Onhand","dataType":"double"},{"name":"Onhand Quantity","dataType":"double"},{"name":"ITEM_COST","dataType":"double"},{"name":"Card Status","dataType":"string"},{"name":"Exception","dataType":"string"},{"name":"Pull Sequence Lead Time","dataType":"double"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-13T06:00:58.1808144+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/362f3439-d18a-4ec9-bda8-402146970692/Kanban_Card.csv?snapshot=2022-06-13T06%3A00%3A58.1679295Z"}]},{"$type":"LocalEntity","name":"Kanban_Supply","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Kanban_Supply.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Organization Code","dataType":"string"},{"name":"KANBAN_CARD_ID","dataType":"double"},{"name":"Card Number","dataType":"string"},{"name":"Document Type","dataType":"string"},{"name":"Document Number","dataType":"string"},{"name":"Line Number","dataType":"string"},{"name":"Quantity","dataType":"double"},{"name":"Supply Date","dataType":"dateTime"},{"name":"VENDOR_ID","dataType":"double"},{"name":"VENDOR_SITE_ID","dataType":"double"},{"name":"Source Org","dataType":"string"},{"name":"Supplier Name","dataType":"string"},{"name":"Supplier Site Code","dataType":"string"},{"name":"Pull Sequence Id","dataType":"double"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-13T06:00:50.3836144+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/362f3439-d18a-4ec9-bda8-402146970692/Kanban_Supply.csv?snapshot=2022-06-13T06%3A00%3A50.3724142Z"}]},{"$type":"LocalEntity","name":"Onhand","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Onhand.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Organization Code","dataType":"string"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"Item Number","dataType":"string"},{"name":"Quantity","dataType":"double"},{"name":"Consigned Flag","dataType":"string"},{"name":"Locator","dataType":"string"},{"name":"Owning Supplier Name","dataType":"string"},{"name":"Owning Supplier Site Code","dataType":"string"},{"name":"VENDOR_ID","dataType":"double"},{"name":"VENDOR_SITE_ID","dataType":"double"},{"name":"Date Received","dataType":"dateTime"},{"name":"ITEM_COST","dataType":"double"},{"name":"Subinventory","dataType":"string"},{"name":"Asset Subinventory Flag","dataType":"string"},{"name":"Nettable Subinventory Flag","dataType":"string"},{"name":"Subinventory Classification","dataType":"string"},{"name":"Transaction Reference","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-13T06:00:17.884376+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/362f3439-d18a-4ec9-bda8-402146970692/Onhand.csv?snapshot=2022-06-13T06%3A00%3A17.8371343Z"}]},{"$type":"LocalEntity","name":"Open_Supply","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Open_Supply.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Item Number","dataType":"string"},{"name":"Organization Code","dataType":"string"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"Source Org Code","dataType":"string"},{"name":"Supply Type Code","dataType":"string"},{"name":"Status Code","dataType":"string"},{"name":"Quantity","dataType":"double"},{"name":"VENDOR_SITE_ID","dataType":"double"},{"name":"Creation Date","dataType":"dateTime"},{"name":"Need By Date","dataType":"dateTime"},{"name":"Expected Receipt Date","dataType":"dateTime"},{"name":"Delivery Status","dataType":"string"},{"name":"Document Number","dataType":"string"},{"name":"Internal Order Number","dataType":"double"},{"name":"Trigger Source","dataType":"string"},{"name":"Kanban Card Number","dataType":"string"},{"name":"KANBAN_CARD_ID","dataType":"double"},{"name":"To Subinventory","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-13T06:00:33.5795472+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/362f3439-d18a-4ec9-bda8-402146970692/Open_Supply.csv?snapshot=2022-06-13T06%3A00%3A33.5351028Z"}]},{"$type":"LocalEntity","name":"Cycle_Count_Activity","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Cycle_Count_Activity.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Organization Code","dataType":"string"},{"name":"Cycle Count Name","dataType":"string"},{"name":"Cycle Count Description","dataType":"string"},{"name":"Disable Date","dataType":"dateTime"},{"name":"Sequence","dataType":"double"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"Item Number","dataType":"string"},{"name":"Count ABC Class","dataType":"string"},{"name":"Subinventory","dataType":"string"},{"name":"Locator","dataType":"string"},{"name":"Lot Number","dataType":"string"},{"name":"Serial Number","dataType":"string"},{"name":"Count Status","dataType":"string"},{"name":"Creation Date","dataType":"dateTime"},{"name":"Due Date","dataType":"dateTime"},{"name":"System Quantity","dataType":"double"},{"name":"Count Quantity","dataType":"double"},{"name":"Count Unit of Measure","dataType":"string"},{"name":"Count Date","dataType":"dateTime"},{"name":"Count By","dataType":"string"},{"name":"System Quantity Prior","dataType":"double"},{"name":"Count Quantity Prior","dataType":"double"},{"name":"Count Unit of Measure Prior","dataType":"string"},{"name":"Count Date Prior","dataType":"dateTime"},{"name":"Count Prior By","dataType":"string"},{"name":"First Count System Quantity","dataType":"double"},{"name":"First Count Quantity","dataType":"double"},{"name":"First Pass Status","dataType":"string"},{"name":"First Count Unit of Measure","dataType":"string"},{"name":"First Count Date","dataType":"dateTime"},{"name":"First Count By","dataType":"string"},{"name":"Adjustment Quantity","dataType":"double"},{"name":"Count Pass Status","dataType":"string"},{"name":"Adjustment Date","dataType":"dateTime"},{"name":"Adjustment Amount","dataType":"double"},{"name":"Last Updated By","dataType":"string"},{"name":"Approval Date","dataType":"dateTime"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-13T06:00:28.0243645+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/362f3439-d18a-4ec9-bda8-402146970692/Cycle_Count_Activity.csv?snapshot=2022-06-13T06%3A00%3A27.9763016Z"}]},{"$type":"LocalEntity","name":"Receipt","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Receipt.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Organization Code","dataType":"string"},{"name":"Receipt Number","dataType":"string"},{"name":"Line Number","dataType":"double"},{"name":"Source Code","dataType":"string"},{"name":"Source Document","dataType":"string"},{"name":"Freight Carrier","dataType":"string"},{"name":"Expected Date","dataType":"dateTime"},{"name":"Shipment Number","dataType":"string"},{"name":"Waybill","dataType":"string"},{"name":"Item Description","dataType":"string"},{"name":"ITEM_ID","dataType":"double"},{"name":"REQUISITION_LINE_ID","dataType":"double"},{"name":"Consigned Flag","dataType":"string"},{"name":"Source Document Number","dataType":"string"},{"name":"VENDOR_ID","dataType":"double"},{"name":"VENDOR_SITE_ID","dataType":"double"},{"name":"TRANSACTION_ID","dataType":"double"},{"name":"SHIPMENT_LINE_ID","dataType":"double"},{"name":"Receipt Routing","dataType":"string"},{"name":"Item Number","dataType":"string"},{"name":"Transaction Date","dataType":"dateTime"},{"name":"Transaction Type","dataType":"string"},{"name":"Currency Code","dataType":"string"},{"name":"USD Budget Rate","dataType":"double"},{"name":"Quantity","dataType":"double"},{"name":"Primary Quantity","dataType":"double"},{"name":"Unit of Measure","dataType":"string"},{"name":"PO Unit Price","dataType":"double"},{"name":"PO_LINE_LOCATION_ID","dataType":"double"},{"name":"Receipt Destination Type","dataType":"string"},{"name":"PO Line","dataType":"double"},{"name":"PO Shipment","dataType":"double"},{"name":"Actual Cost","dataType":"double"},{"name":"Pending Deliver Flag","dataType":"string"},{"name":"Pending Deliver Quantity","dataType":"double"},{"name":"Pending Deliver Age Days","dataType":"double"},{"name":"OTD Need By Date","dataType":"string"},{"name":"OTD Promised Date","dataType":"string"},{"name":"OTD Original Promised Date","dataType":"string"},{"name":"Days To Need By Date","dataType":"double"},{"name":"Days To Promised Date","dataType":"double"},{"name":"Days To Original Promised Date","dataType":"double"},{"name":"Destination Type","dataType":"string"},{"name":"Parent Transaction Type","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-13T06:01:42.0670655+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/362f3439-d18a-4ec9-bda8-402146970692/Receipt.csv?snapshot=2022-06-13T06%3A01%3A42.0386880Z"}]},{"$type":"LocalEntity","name":"Serial_Status","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Serial_Status.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Organization Code","dataType":"string"},{"name":"Current Organization Code","dataType":"string"},{"name":"Serial Status","dataType":"string"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"Item Number","dataType":"string"},{"name":"Serial Number","dataType":"string"},{"name":"WIP Completion Date","dataType":"dateTime"},{"name":"Shipped Date","dataType":"dateTime"},{"name":"Parent Item Number","dataType":"string"},{"name":"Parent Serial Number","dataType":"string"},{"name":"Current Subinventory","dataType":"string"},{"name":"Current Locator","dataType":"string"},{"name":"Original Job Number","dataType":"string"},{"name":"Original Job Organization","dataType":"string"},{"name":"Last Transaction Source","dataType":"string"},{"name":"Last Transaction Source Name","dataType":"string"},{"name":"Last Transaction Source Document","dataType":"string"},{"name":"RESERVATION_ID","dataType":"double"},{"name":"Last Receipt Number","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-13T06:00:49.3055062+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/362f3439-d18a-4ec9-bda8-402146970692/Serial_Status.csv?snapshot=2022-06-13T06%3A00%3A49.2810432Z"}]},{"$type":"LocalEntity","name":"Material_Transaction","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Material_Transaction.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Organization Code","dataType":"string"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"Item Number","dataType":"string"},{"name":"Primary Transaction Quantity","dataType":"double"},{"name":"Transaction Date","dataType":"dateTime"},{"name":"TRANSACTION_ID","dataType":"double"},{"name":"Transaction Type Name","dataType":"string"},{"name":"Transaction Action","dataType":"string"},{"name":"Transaction Subinventory","dataType":"string"},{"name":"Transfer Subinventory","dataType":"string"},{"name":"Transaction Source Type Name","dataType":"string"},{"name":"TRANSFER_TRANSACTION_ID","dataType":"double"},{"name":"Transaction Reference","dataType":"string"},{"name":"Calculated Transaction Source Type","dataType":"string"},{"name":"WIP Accounting Class","dataType":"string"},{"name":"Source Document Number","dataType":"string"},{"name":"Transaction Classification","dataType":"string"},{"name":"Actual Cost","dataType":"double"},{"name":"Created By","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-13T06:00:33.9473075+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/362f3439-d18a-4ec9-bda8-402146970692/Material_Transaction.csv?snapshot=2022-06-13T06%3A00%3A33.9168828Z"}]},{"$type":"LocalEntity","name":"Receiving_Default","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Receiving_Default.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Organization Code","dataType":"string"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"Item Number","dataType":"string"},{"name":"Default Receiving Subinventory","dataType":"string"},{"name":"Default Receiving Locator","dataType":"string"},{"name":"Default Receiving Validation","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-13T06:00:13.6689143+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/362f3439-d18a-4ec9-bda8-402146970692/Receiving_Default.csv?snapshot=2022-06-13T06%3A00%3A13.6505420Z"}]},{"$type":"LocalEntity","name":"Consumption_Advice","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Consumption_Advice.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Organization Code","dataType":"string"},{"name":"TRANSACTION_ID","dataType":"double"},{"name":"VENDOR_ID","dataType":"double"},{"name":"VENDOR_SITE_ID","dataType":"double"},{"name":"ITEM_ID","dataType":"double"},{"name":"Item Number","dataType":"string"},{"name":"Item Description","dataType":"string"},{"name":"Source Code","dataType":"string"},{"name":"Source Document","dataType":"string"},{"name":"Consigned Flag","dataType":"string"},{"name":"Source Document Number","dataType":"string"},{"name":"Transaction Date","dataType":"dateTime"},{"name":"Quantity","dataType":"double"},{"name":"Unit of Measure","dataType":"string"},{"name":"Primary Quantity","dataType":"double"},{"name":"PO_LINE_LOCATION_ID","dataType":"double"},{"name":"PO_DISTRIBUTION_ID","dataType":"double"},{"name":"Transaction Type","dataType":"string"},{"name":"Destination Type","dataType":"string"},{"name":"Currency Code","dataType":"string"},{"name":"PO Line","dataType":"double"},{"name":"Actual Cost","dataType":"double"},{"name":"PO Shipment","dataType":"double"},{"name":"USD Budget Rate","dataType":"double"},{"name":"PO Unit Price","dataType":"double"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-13T06:00:13.5751676+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/362f3439-d18a-4ec9-bda8-402146970692/Consumption_Advice.csv?snapshot=2022-06-13T06%3A00%3A13.5436037Z"}]},{"$type":"LocalEntity","name":"Open_WO","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Open_WO.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Organization Code","dataType":"string"},{"name":"KANBAN_CARD_ID","dataType":"double"},{"name":"Kanban Card Number","dataType":"string"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"Item Number","dataType":"string"},{"name":"Supply Type Code","dataType":"string"},{"name":"Document Number","dataType":"string"},{"name":"Status Code","dataType":"string"},{"name":"Delivery Status","dataType":"string"},{"name":"Expected Receipt Date","dataType":"dateTime"},{"name":"Need By Date","dataType":"dateTime"},{"name":"Creation Date","dataType":"dateTime"},{"name":"Quantity","dataType":"double"},{"name":"Trigger Source","dataType":"string"},{"name":"To Subinventory","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-13T06:00:33.5482877+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/362f3439-d18a-4ec9-bda8-402146970692/Open_WO.csv?snapshot=2022-06-13T06%3A00%3A33.4921265Z"}]},{"$type":"LocalEntity","name":"Open_MO","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Open_MO.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Organization Code","dataType":"string"},{"name":"KANBAN_CARD_ID","dataType":"double"},{"name":"Kanban Card Number","dataType":"string"},{"name":"Item Number","dataType":"string"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"Document Number","dataType":"string"},{"name":"Need By Date","dataType":"dateTime"},{"name":"Quantity","dataType":"double"},{"name":"Supply Type Code","dataType":"string"},{"name":"Status Code","dataType":"string"},{"name":"Creation Date","dataType":"dateTime"},{"name":"Expected Receipt Date","dataType":"dateTime"},{"name":"Delivery Status","dataType":"string"},{"name":"Trigger Source","dataType":"string"},{"name":"To Subinventory","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-13T06:00:17.4625068+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/362f3439-d18a-4ec9-bda8-402146970692/Open_MO.csv?snapshot=2022-06-13T06%3A00%3A17.4253709Z"}]}]}