{"name":"COHREP_SITE_WIP_TRX1","description":"","version":"1.0","culture":"en-US","modifiedTime":"2020-08-29T09:09:43.6090918+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":true,"queriesMetadata":{"ORG":{"queryId":"4fcd04af-9d51-4e03-889d-85933c5589d7","queryName":"ORG"},"WIP_Job":{"queryId":"ce790488-d6c3-4458-929a-49d38e6e7cc5","queryName":"WIP_Job","queryGroupId":"root","loadEnabled":true},"WIP_Value":{"queryId":"9cb72038-8435-4474-8749-c37876303366","queryName":"WIP_Value","queryGroupId":"root","loadEnabled":true}},"document":"section Section1;\r\nshared ORG = let\r\n  ORG = \"LDP\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type text]\r\nin\r\n  ORG;\r\nshared WIP_Job = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, \n  Query=\"SELECT SYSDATE                                                 extract_date, \n       mp.organization_code, \n       wdjv.wip_entity_id, \n       wdjv.creation_date,\n       wdjv.wip_entity_name                                    job_number, \n       wdjv.description                                        job_description, \n       wdjv.primary_item_id, \n       Decode (wdjv.firm_planned_flag, 1, 'Yes', \n                                       'No')                   firm_planned_flag \n       , \n       Decode (wdjv.job_type, 1, 'Standard', \n                              'Non-Standard')                  job_type, \n       (SELECT msi.segment1 \n        FROM   inv.mtl_system_items_b msi \n        WHERE  msi.organization_id = mp.organization_id \n               AND msi.inventory_item_id = wdjv.primary_item_id \n               AND ROWNUM = 1) \n       assembly_item_number, \n       wdjv.bom_revision                                       job_bom_revision, \n       (SELECT wdj.source_code \n        FROM   apps.wip_discrete_jobs wdj \n        WHERE  wdj.wip_entity_id = wdjv.wip_entity_id \n               AND wdj.organization_id = mp.organization_id)   job_source, \n       wdjv.class_code,\n       wdjv.status_type_disp                                   job_status, \n       wdjv.start_quantity, \n       wdjv.scheduled_start_date, \n       wdjv.scheduled_completion_date,\n       (SELECT Min(wop.first_unit_start_date) \n        FROM   apps.wip_operations wop \n        WHERE  wop.wip_entity_id = wdjv.wip_entity_id ) first_unit_start_date,\n       (SELECT Max(wop.date_last_moved) \n        FROM   apps.wip_operations wop \n        WHERE  wop.wip_entity_id = wdjv.wip_entity_id ) last_moved_date, \n       wdjv.net_quantity, \n       nvl(wdjv.quantity_completed,0) quantity_completed, \n       nvl(wdjv.quantity_scrapped,0) quantity_scrapped, \n       nvl(wdjv.quantity_remaining,0) quantity_remaining, \n       wdjv.project_number, \n       wdjv.kanban_card_number, \n       wdjv.lot_number, \n       (SELECT order_number \n        FROM   apps.oe_order_headers_all \n        WHERE  header_id = wdjv.attribute1)                    sales_order_dff, \n       (SELECT line_number \n        FROM   apps.oe_order_lines_all \n        WHERE  line_id = wdjv.attribute2) \n       sales_order_line_dff, \n       wdjv.attribute7 service_request_dff, \n       wdjv.attribute10                                        assembly_sn_dff, \n       wdjv.date_released, \n       wdjv.date_completed, \n       wdjv.date_closed, \n       wdjv.demand_class, \n       wdjv.completion_subinventory,\n       (select concatenated_segments from apps.mtl_item_locations_kfv mil \n       where mil.organization_id = mp.organization_id \n       and mil.inventory_location_id = wdjv.completion_locator_id) completion_locator,\n       fu1.user_name                                           job_created_by, \n       fu2.user_name \n       job_last_updated_by \nFROM   apps.wip_discrete_jobs_v wdjv, \n       apps.mtl_parameters mp, \n       applsys.fnd_user fu1, \n       applsys.fnd_user fu2 \nWHERE  MP.organization_code = '\"&ORG&\"' \n       AND mp.organization_id = wdjv.organization_id\n       AND fu1.user_id = wdjv.created_by \n       AND fu2.user_id = wdjv.last_updated_by\n       \"\n, CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"EXTRACT_DATE\", \"Extract Date\"}, {\"ORGANIZATION_CODE\", \"Organization Code\"}, {\"JOB_NUMBER\", \"Job Number\"}, {\"JOB_DESCRIPTION\", \"Job Description\"}, {\"FIRM_PLANNED_FLAG\", \"Firmed Job\"}, {\"JOB_TYPE\", \"Job Type\"}, {\"ASSEMBLY_ITEM_NUMBER\", \"Assembly Item Number\"}, {\"JOB_BOM_REVISION\", \"BOM Revision\"}, {\"JOB_SOURCE\", \"Source\"}, {\"CLASS_CODE\", \"Class Code\"}, {\"JOB_STATUS\", \"Job Status\"}, {\"START_QUANTITY\", \"Quantity\"}, {\"SCHEDULED_START_DATE\", \"Scheduled Start Date\"}, {\"CREATION_DATE\", \"Creation Date\"}, {\"SCHEDULED_COMPLETION_DATE\", \"Scheduled Completion Date\"}, {\"LAST_MOVED_DATE\", \"Last Moved Date\"}, {\"FIRST_UNIT_START_DATE\", \"First Unit Start Date\"}, {\"NET_QUANTITY\", \"Net Quantity\"}, {\"QUANTITY_COMPLETED\", \"Completed Quantity\"}, {\"QUANTITY_SCRAPPED\", \"Scrapped Quantity\"}, {\"QUANTITY_REMAINING\", \"Remaining Quantity\"}, {\"PROJECT_NUMBER\", \"Project Number\"}, {\"KANBAN_CARD_NUMBER\", \"Kanban Card Number\"}, {\"LOT_NUMBER\", \"Lot Number\"}, {\"DATE_RELEASED\", \"Released Date\"}, {\"DATE_COMPLETED\", \"Completed Date\"}, {\"DATE_CLOSED\", \"Closed Date\"}, {\"DEMAND_CLASS\", \"Demand Class\"}, {\"JOB_CREATED_BY\", \"Created By\"}, {\"JOB_LAST_UPDATED_BY\", \"Last Updated By\"}, {\"COMPLETION_SUBINVENTORY\", \"Completion Subinventory\"}, {\"COMPLETION_LOCATOR\", \"Completion Locator\"}, {\"SALES_ORDER_DFF\", \"Sales Order DFF\"}, {\"SALES_ORDER_LINE_DFF\", \"Sales Order Line DFF\"}, {\"SERVICE_REQUEST_DFF\", \"Service Request DFF\"}, {\"ASSEMBLY_SN_DFF\", \"Assembly Serial Number DFF\"}}),\r\n  ConvertToList = Table.AddColumn(#\"Renamed columns\", \"ClassCodeToList\", each Text.ToList([Class Code])),\r\n  LowerCaseChars = {\"a\"..\"z\"},\r\n  // add Character.FromNumber(8203) to make the column unique\r\n  AddInvisibleChars = Table.AddColumn(ConvertToList, \"AddInvisibleChars\", each List.Transform(\n            [ClassCodeToList], \n            each \n            if \n            List.Contains(#\"LowerCaseChars\", _) \n            then \n            _ & Character.FromNumber(8203) \n            else _\n            )),\r\n  // Add case sensitive column as result of adding invisible characters Character.FromNumber(8203)\r\n  AddCaseSensitiveColumn = Table.AddColumn(AddInvisibleChars, \"Class Code CS\", each Text.Combine([AddInvisibleChars])),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(AddCaseSensitiveColumn, {{\"Class Code CS\", type text}, {\"Completed Quantity\", type number}, {\"Scrapped Quantity\", type number}, {\"Remaining Quantity\", type number}}),\r\n  #\"Removed columns\" = Table.RemoveColumns(#\"Changed column type\", {\"ClassCodeToList\", \"AddInvisibleChars\"})\r\nin\r\n  #\"Removed columns\";\r\nshared WIP_Value = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true,\n    Query=\"\n      SELECT\n         sysdate extract_date,\n         we.wip_entity_name,\n         we.wip_entity_id,\n         mp.organization_code,\n         oap.period_name,\n         wpb.acct_period_id,\n         oap.period_start_date,\n         SUM(wpb.tl_material_out),\n         SUM(wpb.tl_material_var),\n         SUM(wpb.tl_material_overhead_out),\n         SUM(wpb.tl_material_overhead_var),\n         SUM(wpb.tl_resource_in),\n         SUM(wpb.tl_resource_out),\n         SUM(wpb.tl_resource_var),\n         SUM(wpb.tl_outside_processing_in),\n         SUM(wpb.tl_outside_processing_out),\n         SUM(wpb.tl_outside_processing_var),\n         SUM(wpb.tl_overhead_in),\n         SUM(wpb.tl_overhead_out),\n         SUM(wpb.tl_overhead_var),\n         SUM(wpb.pl_material_in),\n         SUM(wpb.pl_material_out),\n         SUM(wpb.pl_material_var),\n         SUM(wpb.pl_material_overhead_in),\n         SUM(wpb.pl_material_overhead_out),\n         SUM(wpb.pl_material_overhead_var),\n         SUM(wpb.pl_resource_in),\n         SUM(wpb.pl_resource_out),\n         SUM(wpb.pl_resource_var),\n         SUM(wpb.pl_outside_processing_var),\n         SUM(wpb.pl_outside_processing_in),\n         SUM(wpb.pl_outside_processing_out),\n         SUM(wpb.pl_overhead_in),\n         SUM(wpb.pl_overhead_out),\n         SUM(wpb.pl_overhead_var)\n      FROM\n         apps.wip_period_balances wpb,\n         inv.mtl_parameters mp,\n         apps.wip_entities we,\n         apps.org_acct_periods oap\n      WHERE\n         mp.organization_id = we.organization_id \n         AND wpb.wip_entity_id = we.wip_entity_id \n         AND OAP.organization_id = we.organization_id \n         AND oap.acct_period_id = wpb.acct_period_id\n         AND mp.organization_code = '\"&ORG&\"'\n      GROUP BY\n        we.wip_entity_name,\n         we.wip_entity_id,\n         mp.organization_code,\n         oap.period_name,\n         wpb.acct_period_id,\n         oap.period_start_date\n    \", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"SUM(WPB.TL_MATERIAL_VAR)\", \"TL Material Variance\"}, {\"SUM(WPB.TL_MATERIAL_OUT)\", \"TL Material Output\"}, {\"SUM(WPB.TL_MATERIAL_OVERHEAD_OUT)\", \"TL Material Overhead Output\"}, {\"SUM(WPB.TL_MATERIAL_OVERHEAD_VAR)\", \"TL Material Overhead Variance\"}, {\"SUM(WPB.TL_RESOURCE_VAR)\", \"TL Resource Variance\"}, {\"SUM(WPB.TL_OUTSIDE_PROCESSING_VAR)\", \"TL OSP Variance\"}, {\"SUM(WPB.TL_OVERHEAD_VAR)\", \"TL Overhead Variance\"}, {\"SUM(WPB.PL_MATERIAL_VAR)\", \"PL Material Variance\"}, {\"SUM(WPB.PL_MATERIAL_OVERHEAD_VAR)\", \"PL Material Overhead Variance\"}, {\"SUM(WPB.PL_RESOURCE_VAR)\", \"PL Resource Variance\"}, {\"SUM(WPB.PL_OUTSIDE_PROCESSING_VAR)\", \"PL OSP Variance\"}, {\"SUM(WPB.PL_OVERHEAD_VAR)\", \"PL Overhead Variance\"}, {\"SUM(WPB.TL_RESOURCE_IN)\", \"TL Resource Input\"}, {\"SUM(WPB.TL_RESOURCE_OUT)\", \"TL Resource Output\"}, {\"SUM(WPB.TL_OVERHEAD_IN)\", \"TL Overhead Input\"}, {\"SUM(WPB.TL_OVERHEAD_OUT)\", \"TL Overhead Output\"}, {\"SUM(WPB.TL_OUTSIDE_PROCESSING_IN)\", \"TL OSP Input\"}, {\"SUM(WPB.TL_OUTSIDE_PROCESSING_OUT)\", \"TL OSP Output\"}, {\"SUM(WPB.PL_MATERIAL_IN)\", \"PL Material Input\"}, {\"SUM(WPB.PL_MATERIAL_OUT)\", \"PL Material Output\"}, {\"SUM(WPB.PL_MATERIAL_OVERHEAD_IN)\", \"PL Material Overhead Input\"}, {\"SUM(WPB.PL_MATERIAL_OVERHEAD_OUT)\", \"PL Material Overhead Output\"}, {\"SUM(WPB.PL_RESOURCE_IN)\", \"PL Resource Input\"}, {\"SUM(WPB.PL_RESOURCE_OUT)\", \"PL Resource Output\"}, {\"SUM(WPB.PL_OVERHEAD_IN)\", \"PL Overhead Input\"}, {\"SUM(WPB.PL_OVERHEAD_OUT)\", \"PL Overhead Output\"}, {\"SUM(WPB.PL_OUTSIDE_PROCESSING_IN)\", \"PL OSP Input\"}, {\"SUM(WPB.PL_OUTSIDE_PROCESSING_OUT)\", \"PL OSP Output\"}, {\"EXTRACT_DATE\", \"Extract Date\"}, {\"WIP_ENTITY_NAME\", \"Job Number\"}, {\"ORGANIZATION_CODE\", \"Organization Code\"}, {\"PERIOD_NAME\", \"Period Name\"}, {\"PERIOD_START_DATE\", \"Period Start Date\"}})\r\nin\r\n  #\"Renamed columns\";\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"WIP_Job","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"WIP_Job.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Organization Code","dataType":"string"},{"name":"WIP_ENTITY_ID","dataType":"double"},{"name":"Creation Date","dataType":"dateTime"},{"name":"Job Number","dataType":"string"},{"name":"Job Description","dataType":"string"},{"name":"PRIMARY_ITEM_ID","dataType":"double"},{"name":"Firmed Job","dataType":"string"},{"name":"Job Type","dataType":"string"},{"name":"Assembly Item Number","dataType":"string"},{"name":"BOM Revision","dataType":"string"},{"name":"Source","dataType":"string"},{"name":"Class Code","dataType":"string"},{"name":"Job Status","dataType":"string"},{"name":"Quantity","dataType":"double"},{"name":"Scheduled Start Date","dataType":"dateTime"},{"name":"Scheduled Completion Date","dataType":"dateTime"},{"name":"First Unit Start Date","dataType":"dateTime"},{"name":"Last Moved Date","dataType":"dateTime"},{"name":"Net Quantity","dataType":"double"},{"name":"Completed Quantity","dataType":"double"},{"name":"Scrapped Quantity","dataType":"double"},{"name":"Remaining Quantity","dataType":"double"},{"name":"Project Number","dataType":"string"},{"name":"Kanban Card Number","dataType":"string"},{"name":"Lot Number","dataType":"string"},{"name":"Sales Order DFF","dataType":"double"},{"name":"Sales Order Line DFF","dataType":"double"},{"name":"Service Request DFF","dataType":"string"},{"name":"Assembly Serial Number DFF","dataType":"string"},{"name":"Released Date","dataType":"dateTime"},{"name":"Completed Date","dataType":"dateTime"},{"name":"Closed Date","dataType":"dateTime"},{"name":"Demand Class","dataType":"string"},{"name":"Completion Subinventory","dataType":"string"},{"name":"Completion Locator","dataType":"string"},{"name":"Created By","dataType":"string"},{"name":"Last Updated By","dataType":"string"},{"name":"Class Code CS","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-05-20T06:00:42.413886+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/9f7de7c3-11e7-498e-ae49-7ea2ed94fcba/WIP_Job.csv?snapshot=2022-05-20T06%3A00%3A42.3769600Z"}]},{"$type":"LocalEntity","name":"WIP_Value","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"WIP_Value.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Job Number","dataType":"string"},{"name":"WIP_ENTITY_ID","dataType":"double"},{"name":"Organization Code","dataType":"string"},{"name":"Period Name","dataType":"string"},{"name":"ACCT_PERIOD_ID","dataType":"double"},{"name":"Period Start Date","dataType":"dateTime"},{"name":"TL Material Output","dataType":"double"},{"name":"TL Material Variance","dataType":"double"},{"name":"TL Material Overhead Output","dataType":"double"},{"name":"TL Material Overhead Variance","dataType":"double"},{"name":"TL Resource Input","dataType":"double"},{"name":"TL Resource Output","dataType":"double"},{"name":"TL Resource Variance","dataType":"double"},{"name":"TL OSP Input","dataType":"double"},{"name":"TL OSP Output","dataType":"double"},{"name":"TL OSP Variance","dataType":"double"},{"name":"TL Overhead Input","dataType":"double"},{"name":"TL Overhead Output","dataType":"double"},{"name":"TL Overhead Variance","dataType":"double"},{"name":"PL Material Input","dataType":"double"},{"name":"PL Material Output","dataType":"double"},{"name":"PL Material Variance","dataType":"double"},{"name":"PL Material Overhead Input","dataType":"double"},{"name":"PL Material Overhead Output","dataType":"double"},{"name":"PL Material Overhead Variance","dataType":"double"},{"name":"PL Resource Input","dataType":"double"},{"name":"PL Resource Output","dataType":"double"},{"name":"PL Resource Variance","dataType":"double"},{"name":"PL OSP Variance","dataType":"double"},{"name":"PL OSP Input","dataType":"double"},{"name":"PL OSP Output","dataType":"double"},{"name":"PL Overhead Input","dataType":"double"},{"name":"PL Overhead Output","dataType":"double"},{"name":"PL Overhead Variance","dataType":"double"}],"partitions":[{"name":"Part001","refreshTime":"2022-05-20T06:02:07.2412622+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/9f7de7c3-11e7-498e-ae49-7ea2ed94fcba/WIP_Value.csv?snapshot=2022-05-20T06%3A02%3A07.0677491Z"}]}]}