{"name":"lokale_Daten_Relia","description":"Verbindungen zum SQL-Server und zu den Relia-Daten","version":"1.0","culture":"en-US","modifiedTime":"2022-03-11T17:14:48.1373832+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":true,"queriesMetadata":{"Relia_Daten_interneFehler":{"queryId":"b3f5e87d-e3f1-46aa-a17d-2c1e1fc2a415","queryName":"Relia_Daten_interneFehler","loadEnabled":true},"Relia_Daten":{"queryId":"084bc519-2ca9-4215-bcbc-2be199942309","queryName":"Relia_Daten","loadEnabled":true},"Relia_Daten-zumTesten":{"queryId":"a10bffd5-6bc7-41c7-a7f7-ed9d13fb31ef","queryName":"Relia_Daten-zumTesten","loadEnabled":true},"Relia_Daten_interneFehler (2)":{"queryId":"14fd9bde-5870-4411-8777-efc85233c0c6","queryName":"Relia_Daten_interneFehler (2)","loadEnabled":true}},"document":"section Section1;\r\nshared Relia_Daten_interneFehler = let\r\n  Source = Sql.Database(\"lbksql_Service\", \"Lbk_Service_DB\", [Query = \"Select * From Relia_Daten_interneFehler Where [ProductFamily] is not null\"]),\r\n  #\"Calculated date\" = Table.TransformColumns(Source, {{\"FirstShipmentDate\", each DateTime.Date(_), type date}}),\r\n  #\"Calculated date 1\" = Table.TransformColumns(#\"Calculated date\", {{\"RL_ShipDate\", each DateTime.Date(_), type date}}),\r\n  #\"Calculated date 2\" = Table.TransformColumns(#\"Calculated date 1\", {{\"Rep_Received\", each DateTime.Date(_), type date}}),\r\n  #\"Calculated date 3\" = Table.TransformColumns(#\"Calculated date 2\", {{\"Rep_Finished\", each DateTime.Date(_), type date}}),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Calculated date 3\", {{\"Wellenlaenge\", Int64.Type}})\r\nin\r\n  #\"Changed column type\";\r\nshared Relia_Daten = let\r\n  Source = Sql.Database(\"lbksql_Service\", \"Lbk_Service_DB\", [Query = \"Select * From Relia_Daten where [ProductFamily] is not null\"]),\r\n  #\"Calculated date\" = Table.TransformColumns(Source, {{\"FirstShipmentDate\", each DateTime.Date(_), type date}}),\r\n  #\"Calculated date 1\" = Table.TransformColumns(#\"Calculated date\", {{\"RL_ShipDate\", each DateTime.Date(_), type date}}),\r\n  #\"Calculated date 2\" = Table.TransformColumns(#\"Calculated date 1\", {{\"Rep_Received\", each DateTime.Date(_), type date}}),\r\n  #\"Calculated date 3\" = Table.TransformColumns(#\"Calculated date 2\", {{\"Rep_Finished\", each DateTime.Date(_), type date}}),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Calculated date 3\", {{\"Wellenlaenge\", Int64.Type}})\r\nin\r\n  #\"Changed column type\";\r\nshared #\"Relia_Daten-zumTesten\" = let\r\n  Source = Relia_Daten,\r\n  #\"Removed columns\" = Table.RemoveColumns(Source, {\"description1\", \"ProductFamily\", \"ShipToCustomer\", \"SystemSerialNr\", \"Rep_BetriebsStd\", \"Rep_BetriebsStdDelta\", \"FirstShipmentDate\", \"RL_ShipDate\", \"Rep_Received\"}),\r\n  #\"Reordered columns\" = Table.ReorderColumns(#\"Removed columns\", {\"Rep_TabServiceID\", \"SerialNr\", \"Item\", \"commodityCode\", \"KopfPN\", \"Rep_EntitComp\", \"Rep_FailureCommodityCode\", \"Rep_FailureClass\", \"Rep_Failure\", \"Rep_FailureComment\", \"Rep_FailureClassIntern\", \"Rep_FailureIntern\", \"Rep_FailureInternComment\", \"Rep_Finished\", \"RL_RepNeu\", \"RL_SNRowNr\", \"Rep_ID\", \"Rep_SR\", \"SR_Fehlerursache_ltKunde\", \"RR_SR_Fehler_ltEingangstest\", \"RR_SR_VorbeugendeMaßnahme\", \"RR_SR_ContainmentAction\", \"RR_SR_RootCause\", \"N_ShipDate\", \"Wellenlaenge\", \"Leistung_mW\", \"TechFam\", \"OrgForecastField\", \"Leistungsklasse\", \"Lasertyp_prodplan\", \"zaehlenFuerStatistiken\", \"OTDGruppe\", \"ForecastField\"}),\r\n  #\"Removed columns 1\" = Table.RemoveColumns(#\"Reordered columns\", {\"Item\", \"SerialNr\", \"KopfPN\"}),\r\n  #\"Filtered rows\" = Table.SelectRows(#\"Removed columns 1\", each [Rep_TabServiceID] = 54059 or [Rep_TabServiceID] = 54055 or [Rep_TabServiceID] = 54069 or [Rep_TabServiceID] = 54120 or [Rep_TabServiceID] = 56183 or [Rep_TabServiceID] = 54113),\r\n  #\"Removed columns 2\" = Table.RemoveColumns(#\"Filtered rows\", {\"Rep_EntitComp\"})\r\nin\r\n  #\"Removed columns 2\";\r\nshared #\"Relia_Daten_interneFehler (2)\" = let\r\n  Source = Relia_Daten_interneFehler,\r\n  #\"Removed columns\" = Table.RemoveColumns(Source, {\"description1\", \"ProductFamily\", \"ShipToCustomer\", \"SystemSerialNr\", \"Rep_BetriebsStd\", \"Rep_BetriebsStdDelta\", \"FirstShipmentDate\", \"RL_ShipDate\", \"Rep_Received\"}),\r\n  #\"Reordered columns\" = Table.ReorderColumns(#\"Removed columns\", {\"Rep_TabServiceID\", \"SerialNr\", \"Item\", \"commodityCode\", \"KopfPN\", \"Rep_EntitComp\", \"Rep_FailureCommodityCode\", \"Rep_FailureClass\", \"Rep_Finished\", \"RL_RepNeu\", \"RL_SNRowNr\", \"Rep_ID\", \"Rep_SR\", \"SR_Fehlerursache_ltKunde\", \"RR_SR_Fehler_ltEingangstest\", \"RR_SR_VorbeugendeMaßnahme\", \"RR_SR_ContainmentAction\", \"RR_SR_RootCause\", \"N_ShipDate\", \"Wellenlaenge\", \"Leistung_mW\", \"TechFam\", \"OrgForecastField\", \"Leistungsklasse\", \"Lasertyp_prodplan\", \"zaehlenFuerStatistiken\", \"OTDGruppe\", \"ForecastField\"}),\r\n  #\"Removed columns 1\" = Table.RemoveColumns(#\"Reordered columns\", {\"Item\", \"SerialNr\", \"KopfPN\"}),\r\n  #\"Filtered rows\" = Table.SelectRows(#\"Removed columns 1\", each [Rep_TabServiceID] = 54059 or [Rep_TabServiceID] = 54055 or [Rep_TabServiceID] = 54069 or [Rep_TabServiceID] = 54120 or [Rep_TabServiceID] = 56183 or [Rep_TabServiceID] = 54113),\r\n  #\"Removed columns 2\" = Table.RemoveColumns(#\"Filtered rows\", {\"Rep_EntitComp\"}),\r\n  #\"Reordered columns 1\" = Table.ReorderColumns(#\"Removed columns 2\", {\"Hauptfehler\", \"Rep_TabServiceID\", \"commodityCode\", \"Rep_FailureCommodityCode\", \"Rep_Failure\", \"Rep_FailureClass\", \"Rep_Finished\", \"RL_RepNeu\", \"RL_SNRowNr\", \"Rep_ID\", \"Rep_SR\", \"SR_Fehlerursache_ltKunde\", \"RR_SR_Fehler_ltEingangstest\", \"RR_SR_VorbeugendeMaßnahme\", \"RR_SR_ContainmentAction\", \"RR_SR_RootCause\", \"N_ShipDate\", \"Wellenlaenge\", \"Leistung_mW\", \"Bemerkung\", \"Beschreibung\", \"TechFam\", \"OrgForecastField\", \"Leistungsklasse\", \"Lasertyp_prodplan\", \"GruppierungFuerAuswertung\", \"zaehlenFuerStatistiken\", \"OTDGruppe\", \"ForecastField\"}),\r\n  #\"Removed columns 3\" = Table.RemoveColumns(#\"Reordered columns 1\", {\"Rep_Finished\", \"RL_RepNeu\"}),\r\n  #\"Reordered columns 2\" = Table.ReorderColumns(#\"Removed columns 3\", {\"Rep_ID\", \"Hauptfehler\", \"Rep_TabServiceID\", \"commodityCode\", \"Rep_FailureClass\", \"Rep_Failure\", \"Rep_FailureCommodityCode\", \"RL_SNRowNr\", \"Rep_SR\", \"SR_Fehlerursache_ltKunde\", \"RR_SR_Fehler_ltEingangstest\", \"RR_SR_VorbeugendeMaßnahme\", \"RR_SR_ContainmentAction\", \"RR_SR_RootCause\", \"N_ShipDate\", \"Wellenlaenge\", \"Leistung_mW\", \"Bemerkung\", \"Beschreibung\", \"TechFam\", \"OrgForecastField\", \"Leistungsklasse\", \"Lasertyp_prodplan\", \"GruppierungFuerAuswertung\", \"zaehlenFuerStatistiken\", \"OTDGruppe\", \"ForecastField\"}),\r\n  #\"Filtered rows 1\" = Table.SelectRows(#\"Reordered columns 2\", each [Rep_TabServiceID] = 54113)\r\nin\r\n  #\"Filtered rows 1\";\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"Relia_Daten_interneFehler","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Relia_Daten_interneFehler.csv"},"attributes":[{"name":"SerialNr","dataType":"string"},{"name":"Item","dataType":"string"},{"name":"description1","dataType":"string"},{"name":"ProductFamily","dataType":"string"},{"name":"commodityCode","dataType":"string"},{"name":"ShipToCustomer","dataType":"string"},{"name":"KopfPN","dataType":"int64"},{"name":"SystemSerialNr","dataType":"string"},{"name":"Rep_EntitComp","dataType":"string"},{"name":"Rep_BetriebsStd","dataType":"double"},{"name":"Rep_BetriebsStdDelta","dataType":"double"},{"name":"Rep_FailureCommodityCode","dataType":"string"},{"name":"Rep_FailureClass","dataType":"string"},{"name":"Rep_Failure","dataType":"string"},{"name":"FirstShipmentDate","dataType":"date"},{"name":"RL_ShipDate","dataType":"date"},{"name":"Rep_Received","dataType":"date"},{"name":"Rep_Finished","dataType":"date"},{"name":"RL_RepNeu","dataType":"string"},{"name":"RL_SNRowNr","dataType":"int64"},{"name":"Rep_TabServiceID","dataType":"int64"},{"name":"Rep_ID","dataType":"int64"},{"name":"Rep_SR","dataType":"string"},{"name":"SR_Fehlerursache_ltKunde","dataType":"string"},{"name":"RR_SR_Fehler_ltEingangstest","dataType":"string"},{"name":"RR_SR_VorbeugendeMaßnahme","dataType":"string"},{"name":"RR_SR_ContainmentAction","dataType":"string"},{"name":"RR_SR_RootCause","dataType":"string"},{"name":"N_ShipDate","dataType":"dateTime"},{"name":"Wellenlaenge","dataType":"int64"},{"name":"Hauptfehler","dataType":"boolean"},{"name":"Leistung_mW","dataType":"int64"},{"name":"Bemerkung","dataType":"string"},{"name":"Beschreibung","dataType":"string"},{"name":"TechFam","dataType":"string"},{"name":"OrgForecastField","dataType":"string"},{"name":"Leistungsklasse","dataType":"string"},{"name":"Lasertyp_prodplan","dataType":"string"},{"name":"GruppierungFuerAuswertung","dataType":"string"},{"name":"OTDGruppe","dataType":"string"},{"name":"zaehlenFuerStatistiken","dataType":"boolean"},{"name":"ForecastField","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-20T08:02:11.4035761+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/2a45af2d-e85d-4615-a808-c472b751e583/Relia_Daten_interneFehler.csv?snapshot=2022-05-20T08%3A02%3A02.0505741Z"}]},{"$type":"LocalEntity","name":"Relia_Daten","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Relia_Daten.csv"},"attributes":[{"name":"SerialNr","dataType":"string"},{"name":"Item","dataType":"string"},{"name":"description1","dataType":"string"},{"name":"ProductFamily","dataType":"string"},{"name":"commodityCode","dataType":"string"},{"name":"ShipToCustomer","dataType":"string"},{"name":"KopfPN","dataType":"int64"},{"name":"SystemSerialNr","dataType":"string"},{"name":"Rep_EntitComp","dataType":"string"},{"name":"Rep_BetriebsStd","dataType":"double"},{"name":"Rep_BetriebsStdDelta","dataType":"double"},{"name":"Rep_FailureCommodityCode","dataType":"string"},{"name":"Rep_FailureClass","dataType":"string"},{"name":"Rep_Failure","dataType":"string"},{"name":"Rep_FailureComment","dataType":"string"},{"name":"Rep_FailureClassIntern","dataType":"string"},{"name":"Rep_FailureIntern","dataType":"string"},{"name":"Rep_FailureInternComment","dataType":"string"},{"name":"FirstShipmentDate","dataType":"date"},{"name":"RL_ShipDate","dataType":"date"},{"name":"Rep_Received","dataType":"date"},{"name":"Rep_Finished","dataType":"date"},{"name":"RL_RepNeu","dataType":"string"},{"name":"RL_SNRowNr","dataType":"int64"},{"name":"Rep_TabServiceID","dataType":"int64"},{"name":"Rep_ID","dataType":"int64"},{"name":"Rep_SR","dataType":"string"},{"name":"SR_Fehlerursache_ltKunde","dataType":"string"},{"name":"RR_SR_Fehler_ltEingangstest","dataType":"string"},{"name":"RR_SR_VorbeugendeMaßnahme","dataType":"string"},{"name":"RR_SR_ContainmentAction","dataType":"string"},{"name":"RR_SR_RootCause","dataType":"string"},{"name":"N_ShipDate","dataType":"dateTime"},{"name":"Wellenlaenge","dataType":"int64"},{"name":"Leistung_mW","dataType":"int64"},{"name":"TechFam","dataType":"string"},{"name":"OrgForecastField","dataType":"string"},{"name":"Leistungsklasse","dataType":"string"},{"name":"Lasertyp_prodplan","dataType":"string"},{"name":"zaehlenFuerStatistiken","dataType":"boolean"},{"name":"OTDGruppe","dataType":"string"},{"name":"ForecastField","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-20T08:02:02.937382+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/2a45af2d-e85d-4615-a808-c472b751e583/Relia_Daten.csv?snapshot=2022-05-20T08%3A01%3A53.8392685Z"}]},{"$type":"LocalEntity","name":"Relia_Daten-zumTesten","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Relia_Daten-zumTesten.csv"},"annotations":[{"name":"pbi:EntityTypeDisplayHint","value":"CalculatedEntity"}],"attributes":[{"name":"Rep_TabServiceID","dataType":"int64"},{"name":"commodityCode","dataType":"string"},{"name":"Rep_FailureCommodityCode","dataType":"string"},{"name":"Rep_FailureClass","dataType":"string"},{"name":"Rep_Failure","dataType":"string"},{"name":"Rep_FailureComment","dataType":"string"},{"name":"Rep_FailureClassIntern","dataType":"string"},{"name":"Rep_FailureIntern","dataType":"string"},{"name":"Rep_FailureInternComment","dataType":"string"},{"name":"Rep_Finished","dataType":"date"},{"name":"RL_RepNeu","dataType":"string"},{"name":"RL_SNRowNr","dataType":"int64"},{"name":"Rep_ID","dataType":"int64"},{"name":"Rep_SR","dataType":"string"},{"name":"SR_Fehlerursache_ltKunde","dataType":"string"},{"name":"RR_SR_Fehler_ltEingangstest","dataType":"string"},{"name":"RR_SR_VorbeugendeMaßnahme","dataType":"string"},{"name":"RR_SR_ContainmentAction","dataType":"string"},{"name":"RR_SR_RootCause","dataType":"string"},{"name":"N_ShipDate","dataType":"dateTime"},{"name":"Wellenlaenge","dataType":"int64"},{"name":"Leistung_mW","dataType":"int64"},{"name":"TechFam","dataType":"string"},{"name":"OrgForecastField","dataType":"string"},{"name":"Leistungsklasse","dataType":"string"},{"name":"Lasertyp_prodplan","dataType":"string"},{"name":"zaehlenFuerStatistiken","dataType":"boolean"},{"name":"OTDGruppe","dataType":"string"},{"name":"ForecastField","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-20T08:02:08.0735133+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/2a45af2d-e85d-4615-a808-c472b751e583/Relia_Daten-zumTesten.csv?snapshot=2022-05-20T08%3A02%3A08.0451492Z"}]},{"$type":"LocalEntity","name":"Relia_Daten_interneFehler (2)","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Relia_Daten_interneFehler%20%282%29.csv"},"annotations":[{"name":"pbi:EntityTypeDisplayHint","value":"CalculatedEntity"}],"attributes":[{"name":"Rep_ID","dataType":"int64"},{"name":"Hauptfehler","dataType":"boolean"},{"name":"Rep_TabServiceID","dataType":"int64"},{"name":"commodityCode","dataType":"string"},{"name":"Rep_FailureClass","dataType":"string"},{"name":"Rep_Failure","dataType":"string"},{"name":"Rep_FailureCommodityCode","dataType":"string"},{"name":"RL_SNRowNr","dataType":"int64"},{"name":"Rep_SR","dataType":"string"},{"name":"SR_Fehlerursache_ltKunde","dataType":"string"},{"name":"RR_SR_Fehler_ltEingangstest","dataType":"string"},{"name":"RR_SR_VorbeugendeMaßnahme","dataType":"string"},{"name":"RR_SR_ContainmentAction","dataType":"string"},{"name":"RR_SR_RootCause","dataType":"string"},{"name":"N_ShipDate","dataType":"dateTime"},{"name":"Wellenlaenge","dataType":"int64"},{"name":"Leistung_mW","dataType":"int64"},{"name":"Bemerkung","dataType":"string"},{"name":"Beschreibung","dataType":"string"},{"name":"TechFam","dataType":"string"},{"name":"OrgForecastField","dataType":"string"},{"name":"Leistungsklasse","dataType":"string"},{"name":"Lasertyp_prodplan","dataType":"string"},{"name":"GruppierungFuerAuswertung","dataType":"string"},{"name":"zaehlenFuerStatistiken","dataType":"boolean"},{"name":"OTDGruppe","dataType":"string"},{"name":"ForecastField","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-20T08:02:13.4603652+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/2a45af2d-e85d-4615-a808-c472b751e583/Relia_Daten_interneFehler%20(2).csv?snapshot=2022-05-20T08%3A02%3A13.4380652Z"}]}]}