{"name":"COHERENT_BACKLOG_BILLINGS_SHIPMENTS","description":"Daten aus Snowflake","version":"1.0","culture":"en-US","modifiedTime":"2022-05-19T12:24:14.184506+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"XXCOH_BACKLOG_VIEW":{"queryId":"f154d9a9-8c2d-4f10-bd66-9a502b88e861","queryName":"XXCOH_BACKLOG_VIEW","loadEnabled":true},"XXCOH_BILLING_VIEW":{"queryId":"beb7aa10-d13b-4f99-a24b-6b9088557821","queryName":"XXCOH_BILLING_VIEW","loadEnabled":true},"ORGTechnicalBusinessUnit":{"queryId":"c9aa082d-f81c-48c0-b39d-5dc55a2818d3","queryName":"ORGTechnicalBusinessUnit"},"XXCOH_INSTALL_BASE_VIEW":{"queryId":"ccb9339f-61db-4b66-8879-3f4942a7e607","queryName":"XXCOH_INSTALL_BASE_VIEW","loadEnabled":true},"XXCOH_MS_SHIPMENT_VIEW":{"queryId":"09d19ecf-c285-4050-9b23-73450167a737","queryName":"XXCOH_MS_SHIPMENT_VIEW","loadEnabled":true},"OrgProductFamily":{"queryId":"0f22b37d-df08-43df-9697-bd2ee754917b","queryName":"OrgProductFamily"},"OrgProductFamily (2)":{"queryId":"7bbca634-9213-4466-8bf7-c6b7446c15dc","queryName":"OrgProductFamily (2)"},"OrgProductFamily (3)":{"queryId":"9f639620-7c96-4b8f-a953-0647cb40b2eb","queryName":"OrgProductFamily (3)"},"OrgProductFamily (4)":{"queryId":"c13f3da5-fa26-4a1e-86ce-a24b7088dfc3","queryName":"OrgProductFamily (4)"},"OrgProductFamily (5)":{"queryId":"e6261a1c-d810-4ea8-a861-4ca7306150cc","queryName":"OrgProductFamily (5)"},"OrgProductFamily (6)":{"queryId":"37031990-8e4d-411b-8712-c808932d6f79","queryName":"OrgProductFamily (6)"},"OrgProductFamily (7)":{"queryId":"7228fbbf-cbff-44fa-b37d-3a2551f7a45b","queryName":"OrgProductFamily (7)"},"OrgProductFamily (8)":{"queryId":"9b519bf1-7d6c-4529-8f30-fc1e922f57d4","queryName":"OrgProductFamily (8)"},"OrgProductFamily (9)":{"queryId":"bb58c68e-687e-4478-b82b-cbfd06a66f48","queryName":"OrgProductFamily (9)"},"XXCOH_BACKLOG_FLASH_CUR_PRD_V":{"queryId":"91df2a87-a1ad-4f71-88e0-8626cc903b50","queryName":"XXCOH_BACKLOG_FLASH_CUR_PRD_V","loadEnabled":true}},"document":"section Section1;\r\nshared XXCOH_BACKLOG_VIEW = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 1\" = Navigation{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXCOH_BACKLOG_VIEW\", Kind = \"View\"]}[Data],\r\n  #\"Filtered rows OrgTechnicalBusinessUnit\" = Table.SelectRows(#\"Navigation 2\", each [ORG_TECHNICAL_BUSINESS_UNIT] = ORGTechnicalBusinessUnit),\r\n  #\"Filtered rows OrgProductFamily\" = Table.SelectRows(#\"Filtered rows OrgTechnicalBusinessUnit\", each [ORG_PRODUCT_FAMILY] = OrgProductFamily or [ORG_PRODUCT_FAMILY] = #\"OrgProductFamily (2)\" or [ORG_PRODUCT_FAMILY] = #\"OrgProductFamily (3)\" or [ORG_PRODUCT_FAMILY] = #\"OrgProductFamily (4)\" or [ORG_PRODUCT_FAMILY] = #\"OrgProductFamily (5)\" or [ORG_PRODUCT_FAMILY] = #\"OrgProductFamily (6)\" or [ORG_PRODUCT_FAMILY] = #\"OrgProductFamily (7)\" or [ORG_PRODUCT_FAMILY] = #\"OrgProductFamily (8)\"),\r\n  #\"Calculated date\" = Table.TransformColumns(#\"Filtered rows OrgProductFamily\", {{\"BOOKED_DATE\", each DateTime.Date(_), type nullable date}}),\r\n  #\"Calculated date 1\" = Table.TransformColumns(#\"Calculated date\", {{\"REQUEST_SHIP_DATE\", each DateTime.Date(_), type nullable date}, {\"PROMISE_SHIP_DATE\", each DateTime.Date(_), type nullable date}, {\"SCHEDULE_SHIP_DATE\", each DateTime.Date(_), type nullable date}}),\r\n  #\"Reordered columns\" = Table.ReorderColumns(#\"Calculated date 1\", {\"ASOF_DATE\", \"ORDER_NUMBER\", \"CUSTOMER_NUMBER\", \"CUSTOMER_NAME\", \"CUSTOMER_ALTERNATE_NAME\", \"CUSTOMER_NAME_REPORTING\", \"ASOF_DATE_DISP\", \"BACKLOG_DATE\", \"ENTER_DATE\", \"BOOKED_DATE\", \"ORDER_LINE\", \"ORDER_TYPE\", \"SO_LINE_TYPE\", \"LINE_STATUS\", \"BILLABLE_FLAG\", \"INV_FLAG\", \"LINE_CATEGORY_CODE\", \"LINE_SOURCE_TYPE_CODE\", \"SALES_CHANNEL\", \"ORDER_SOURCE\", \"ORDER_SOURCE_REFERENCE\", \"ORDER_SOURCE_LINE_REFERENCE\", \"AGREEMENT_NUMBER\", \"ITEM_TYPE_CODE\", \"HOLD_STATUS\", \"HOLD_REASON\", \"REGIONAL_LOCATION\", \"REPORTING_ENTITY\", \"CUSTOMER_PO\", \"CREATED_BY\", \"ITEM_NUMBER\", \"ITEM_DESCRIPTION\", \"ITEM_STATUS\", \"PRODUCT_LINE\", \"PRODUCT_FAMILY\", \"TECHNICAL_BUSINESS_UNIT\", \"REVENUE_ACCOUNT\", \"FORECAST_FIELD\", \"COMMODITY\", \"ORG_PRODUCT_LINE\", \"ORG_PRODUCT_FAMILY\", \"ORG_TECHNICAL_BUSINESS_UNIT\", \"ORG_FORECAST_FIELD\", \"LEAD_TIME\", \"PRIMARY_ORG\", \"ITEM_CUSTOMER\", \"BCP_CODE\", \"ROYALTY\", \"WAREHOUSE\", \"SHIPMENT_PRIORITY_CODE\", \"SHIPPING_METHOD_CODE\", \"RETURN_REASON\", \"EXPIRATION_DATE\", \"BACKLOG_QUANTITY\", \"ASP_QUANTITY\", \"ASP_FLAG\", \"COMMISSION_SALESREP\", \"COMMISSION_PERCENT\", \"OVERWRITE_CURRENCY_CI\", \"OVERWRITE_UNIT_PRICE_CI\", \"OVERWRITE_EXT_PRICE_CI\", \"END_CUST_USD_RATE\", \"OVERWRITE_UNIT_PRICE_CI_USD\", \"OVERWRITE_EXT_PRICE_CI_USD\", \"TR_UNIT_SELLING_PRICE\", \"TR_ITEM_UNIT_COST\", \"TR_ITEM_MATERIAL_COST\", \"TR_ITEM_LABOR_COST\", \"TR_ITEM_MATERIAL_OVERHEAD\", \"TR_ITEM_LABOR_OVERHEAD\", \"TR_ITEM_OUT_PROC_COST\", \"TR_UNIT_LIST_PRICE\", \"TR_EXTENDED_AMOUNT\", \"TR_EXTENDED_COST\", \"GROSS_MARGIN_PCT\", \"DISCOUNT_PERCENT\", \"TR_DISCOUNT_AMOUNT\", \"PRICE_LIST\", \"UNIT_SELLING_PRICE\", \"ITEM_UNIT_COST\", \"ITEM_MATERIAL_COST\", \"ITEM_LABOR_COST\", \"ITEM_MATERIAL_OVERHEAD\", \"ITEM_LABOR_OVERHEAD\", \"ITEM_OUT_PROC_COST\", \"UNIT_LIST_PRICE\", \"EXTENDED_AMOUNT\", \"EXTENDED_COST\", \"DISCOUNT_AMOUNT\", \"APPLICATION_CODE\", \"APPLICATION_CODE_DESC\", \"MARKET_SEGMENT\", \"REQUEST_SHIP_DATE\", \"PROMISE_SHIP_DATE\", \"SCHEDULE_SHIP_DATE\", \"TAX_REGISTRATION_NUMBER\", \"PARTY_NUMBER\", \"BILL_TO_NAME\", \"BILL_TO_COUNTRY\", \"BILL_TO_ADDRESS1\", \"BILL_TO_ADDRESS2\", \"BILL_TO_ADDRESS3\", \"BILL_TO_ADDRESS4\", \"BILL_TO_CITY\", \"BILL_TO_STATE\", \"BILL_TO_POSTAL_CODE\", \"BILL_TO_COUNTY\", \"BILL_TO_PROVINCE\", \"BILL_TO_SITE\", \"BILL_TO_CONTACT\", \"SHIP_TO_NAME\", \"SHIP_TO_COUNTRY\", \"SHIP_TO_ADDRESS1\", \"SHIP_TO_ADDRESS2\", \"SHIP_TO_ADDRESS3\", \"SHIP_TO_ADDRESS4\", \"SHIP_TO_CITY\", \"SHIP_TO_STATE\", \"SHIP_TO_POSTAL_CODE\", \"SHIP_TO_COUNTY\", \"SHIP_TO_PROVINCE\", \"SHIP_TO_SITE\", \"SHIP_TO_CONTACT\", \"END_USER\", \"END_USER_NUMBER\", \"END_USER_CONTACT\", \"SALESPERSON\", \"MAJOR_GEOGRAPHICAL_AREA\", \"GL_CLASS\", \"CUSTOMER_CLASS\", \"CUSTOMER_CATEGORY\", \"CUSTOMER_TYPE\", \"PAYMENT_TYPE\", \"CREDIT_CARD_CODE\", \"CREDIT_CARD_NUMBER\", \"CREDIT_CARD_HOLDER_NAME\", \"CREDIT_CARD_EXPIRATION_DATE\", \"CREDIT_CARD_APPROVAL_CODE\", \"FREIGHT_TERM\", \"FOB\", \"FISCAL_WEEK_BOOKED\", \"FISCAL_PERIOD_BOOKED\", \"FISCAL_QUARTER_BOOKED\", \"FISCAL_YEAR_BOOKED\", \"SCHEDULE_CATEGORY\", \"SCHEDULE_CATEGORY_PERIOD\", \"SCHEDULE_ORDER\", \"LEGAL_ENTITY_ID\", \"LEGAL_ENTITY\", \"OPERATING_UNIT_ID\", \"OPERATING_UNIT\", \"TRANSACTION_CURRENCY\", \"FUNCTIONAL_CURRENCY\", \"TRX_TO_USD_RATE\", \"TRX_TO_FUNC_RATE\", \"COST_TO_FUNC_RATE\", \"COST_TO_USD_RATE\", \"ME_TRX_TO_USD_RATE\", \"ME_TRX_TO_FUNC_RATE\", \"ME_END_CUST_USD_RATE\", \"ME_COST_TO_FUNC_RATE\", \"ME_COST_TO_USD_RATE\", \"UNIT_SELLING_PRICE_USD\", \"UNIT_LIST_PRICE_USD\", \"ITEM_UNIT_COST_USD\", \"ITEM_MATERIAL_COST_USD\", \"ITEM_LABOR_COST_USD\", \"ITEM_MATERIAL_OVERHEAD_USD\", \"ITEM_LABOR_OVERHEAD_USD\", \"ITEM_OUT_PROC_COST_USD\", \"EXTENDED_AMOUNT_USD\", \"EXTENDED_COST_USD\", \"DISCOUNT_AMOUNT_USD\", \"TERR_AREA\", \"TERR_OFFICE\", \"TERR_SALES_MGR_TERR_NUM\", \"TERR_TYPE\", \"TERR_NUM\", \"ORDER_STATUS\", \"STAGED_QTY\", \"TR_STAGED_EXT_AMOUNT\", \"STAGED_EXT_AMOUNT\", \"STAGED_EXT_AMOUNT_USD\", \"O_GROSS_MARGIN_PCT\", \"O_UNIT_SELLING_PRICE\", \"O_ITEM_UNIT_COST\", \"O_ITEM_MATERIAL_COST\", \"O_ITEM_LABOR_COST\", \"O_ITEM_MATERIAL_OVERHEAD\", \"O_ITEM_LABOR_OVERHEAD\", \"O_ITEM_OUT_PROC_COST\", \"O_UNIT_LIST_PRICE\", \"O_EXTENDED_AMOUNT\", \"O_EXTENDED_COST\", \"O_DISCOUNT_AMOUNT\", \"O_UNIT_SELLING_PRICE_USD\", \"O_UNIT_LIST_PRICE_USD\", \"O_ITEM_UNIT_COST_USD\", \"O_ITEM_MATERIAL_COST_USD\", \"O_ITEM_LABOR_COST_USD\", \"O_ITEM_MATERIAL_OVERHEAD_USD\", \"O_ITEM_LABOR_OVERHEAD_USD\", \"O_ITEM_OUT_PROC_COST_USD\", \"O_EXTENDED_AMOUNT_USD\", \"O_EXTENDED_COST_USD\", \"O_DISCOUNT_AMOUNT_USD\", \"O_OVERWRITE_UNIT_PRICE_CI_USD\", \"O_OVERWRITE_EXT_PRICE_CI_USD\", \"O_STAGED_EXT_AMOUNT\", \"O_STAGED_EXT_AMOUNT_USD\", \"REPEAT_BUSINESS\", \"M20_REPORTING_ENTITY\", \"FLASH_OFFICE\", \"PLANNER_CODE\", \"END_ASSEMBLY_PEGGING\", \"PARTIAL_SHIPMENTS_ALLOWED\", \"PAYMENT_TERM\", \"TIMESTAMP\", \"ROW_ID\", \"FIRST_SCHEDULE_DATE\", \"EXTERNAL_ORDER_NUMBER\", \"INTERCO_PO_NUM\", \"SHIPPING_INSTRUCTIONS\", \"PACKING_INSTRUCTIONS\", \"LINE_ID\", \"HEADER_ID\", \"SOURCE_DOCUMENT_LINE_ID\", \"SOURCE_DOCUMENT_ID\", \"SOURCE_DOCUMENT_TYPE_ID\", \"PROJECT_ID\", \"PROJECT_NAME\", \"PROJECT_NUMBER\", \"TR_ESTIMATED_UNIT_TRF_PRICE\", \"TR_EXT_ESTIMATED_TRF_PRICE\", \"ESTIMATED_UNIT_TRF_PRICE\", \"EXT_ESTIMATED_TRF_PRICE\", \"ESTIMATED_UNIT_TRF_PRICE_USD\", \"EXT_ESTIMATED_TRF_PRICE_USD\", \"SPL_COGS_FLAG\", \"COGS_ACCOUNT\", \"IMPORTER_NAME\", \"IMPORTER_NUMBER\", \"IMPORTER_ADDRESS1\", \"IMPORTER_ADDRESS2\", \"IMPORTER_CITY\", \"IMPORTER_STATE\", \"IMPORTER_POSTAL_CODE\", \"IMPORTER_COUNTY\", \"IMPORTER_PROVINCE\", \"IMPORTER_COUNTRY_NAME\", \"END_USER_ADDRESS1\", \"END_USER_ADDRESS2\", \"END_USER_ADDRESS3\", \"END_USER_CITY\", \"END_USER_STATE\", \"END_USER_POSTAL_CODE\", \"END_USER_COUNTY\", \"END_USER_PROVINCE\", \"CST_CURRENCY_CODE\", \"BILL_TO_ADDRESS_ID\", \"SHIP_TO_ADDRESS_ID\", \"END_USER_ADDRESS_ID\", \"IMPORTER_ADDRESS_ID\", \"FIN_SITE\", \"FIN_ENTITY\", \"FIN_PRODUCT_GROUP\", \"FIN_PRODUCT_FAMILY\", \"FIN_FORECAST_FIELD\", \"FIN_MGMT_MARKET\", \"FIN_CORP_MARKET\", \"FIN_BACKLOG_STATUS_1\", \"FIN_BACKLOG_STATUS\", \"FIN_BACKLOG_ROLLUP\", \"FIN_UNIT\", \"HFM_PRODUCT_FAMILY\", \"HFM_BACKLOG_ACCOUNT\", \"CONTRACT_START_DATE\", \"CONTRACT_END_DATE\", \"CONTRACT_HEADER_ID\", \"CONTRACT_LINE_ID\", \"PERIOD_NAME\", \"BCK_KEY\", \"ROW_CREATION_DATE\"})\r\nin\r\n  #\"Reordered columns\";\r\nshared XXCOH_BILLING_VIEW = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 1\" = Navigation{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXCOH_BILLING_VIEW\", Kind = \"View\"]}[Data],\r\n  #\"Filtered rows OrgTechnicalBusinessUnit\" = Table.SelectRows(#\"Navigation 2\", each [ORG_TECHNICAL_BUSINESS_UNIT] = ORGTechnicalBusinessUnit),\r\n  #\"Filtered rows OrgProductFamily\" = Table.SelectRows(#\"Filtered rows OrgTechnicalBusinessUnit\", each [ORG_PRODUCT_FAMILY] = OrgProductFamily or [ORG_PRODUCT_FAMILY] = #\"OrgProductFamily (2)\" or [ORG_PRODUCT_FAMILY] = #\"OrgProductFamily (3)\" or [ORG_PRODUCT_FAMILY] = #\"OrgProductFamily (4)\" or [ORG_PRODUCT_FAMILY] = #\"OrgProductFamily (5)\" or [ORG_PRODUCT_FAMILY] = #\"OrgProductFamily (6)\" or [ORG_PRODUCT_FAMILY] = #\"OrgProductFamily (7)\" or [ORG_PRODUCT_FAMILY] = #\"OrgProductFamily (8)\"),\r\n  #\"Calculated date\" = Table.TransformColumns(#\"Filtered rows OrgProductFamily\", {{\"ACTUAL_SHIPMENT_DATE\", each DateTime.Date(_), type nullable date}}),\r\n  #\"Reordered columns\" = Table.ReorderColumns(#\"Calculated date\", {\"ASOF_DATE\", \"CUSTOMER_NUMBER\", \"CUSTOMER_NAME\", \"CUSTOMER_ALTERNATE_NAME\", \"CUSTOMER_NAME_REPORTING\", \"ASOF_DATE_DISP\", \"BACKUP_DATE\", \"BOOKED_DATE\", \"INVOICE_CREATION_DATE\", \"INVOICE_DATE\", \"WAREHOUSE\", \"ORDER_NUMBER\", \"ORDER_LINE\", \"ORDER_TYPE\", \"SO_LINE_TYPE\", \"SALES_CHANNEL\", \"SHIPMENT_PRIORITY_CODE\", \"SHIPPING_METHOD_CODE\", \"RETURN_REASON\", \"LINE_CATEGORY_CODE\", \"LINE_SOURCE_TYPE_CODE\", \"REGIONAL_LOCATION\", \"REPORTING_ENTITY\", \"ASIA_INVOICE_NO\", \"INVOICE_NUMBER\", \"INVOICE_LINE\", \"INVOICE_CLASS\", \"INVOICE_TYPE\", \"FUNCTIONAL_CURRENCY\", \"CUSTOMER_PO\", \"ITEM_NUMBER\", \"ITEM_DESCRIPTION\", \"PRODUCT_LINE\", \"PRODUCT_FAMILY\", \"TECHNICAL_BUSINESS_UNIT\", \"FORECAST_FIELD\", \"COMMODITY\", \"ORG_PRODUCT_LINE\", \"ORG_PRODUCT_FAMILY\", \"ORG_TECHNICAL_BUSINESS_UNIT\", \"ORG_FORECAST_FIELD\", \"PATLEX\", \"LEAD_TIME\", \"PRIMARY_ORG\", \"BCP_CODE\", \"ITEM_CUSTOMER\", \"ROYALTY\", \"INVOICED_QUANTITY\", \"ASP_QUANTITY\", \"ASP_FLAG\", \"COMMISSION_SALESREP\", \"COMMISSION_PERCENT\", \"AMORTIZED_FLAG\", \"ACCOUNTING_RULE\", \"RULE_DURATION\", \"RULE_REMAINING\", \"RULE_COMPLETED\", \"TR_UNEARNED_REVENUE\", \"UNEARNED_REVENUE\", \"UNEARNED_REVENUE_USD\", \"ACCT_ENTITY\", \"REVENUE_DEPT\", \"REVENUE_ACCT\", \"REVENUE_IC\", \"UNEARNED_ENTITY\", \"UNEARNED_DEPT\", \"UNEARNED_ACCT\", \"UNEARNED_IC\", \"GL_DATE\", \"GL_POSTED_DATE\", \"TR_REVENUE\", \"REVENUE\", \"REVENUE_USD\", \"TR_UNIT_SELLING_PRICE\", \"TR_ITEM_UNIT_COST\", \"TR_ITEM_ADD_BACK_UNIT_COST\", \"TR_ITEM_MATERIAL_COST\", \"TR_ITEM_LABOR_COST\", \"TR_ITEM_MATERIAL_OVERHEAD\", \"TR_ITEM_LABOR_OVERHEAD\", \"TR_ITEM_OUT_PROC_COST\", \"TR_UNIT_LIST_PRICE\", \"TR_EXTENDED_AMOUNT\", \"TR_EXTENDED_COST\", \"TR_EXTENDED_ADD_BACK_COST\", \"TR_TAX_AMOUNT\", \"TR_DISCOUNT_AMOUNT\", \"PRICE_LIST\", \"UNIT_SELLING_PRICE\", \"ITEM_UNIT_COST\", \"ITEM_ADD_BACK_UNIT_COST\", \"ITEM_MATERIAL_COST\", \"ITEM_LABOR_COST\", \"ITEM_MATERIAL_OVERHEAD\", \"ITEM_LABOR_OVERHEAD\", \"ITEM_OUT_PROC_COST\", \"UNIT_LIST_PRICE\", \"EXTENDED_AMOUNT\", \"EXTENDED_COST\", \"EXTENDED_ADD_BACK_COST\", \"GROSS_MARGIN_PCT\", \"TAX_AMOUNT\", \"TAX_CODE\", \"DISCOUNT_PERCENT\", \"DISCOUNT_AMOUNT\", \"APPLICATION_CODE_DESC\", \"APPLICATION_CODE\", \"MARKET_SEGMENT\", \"REQUEST_SHIP_DATE\", \"PROMISE_SHIP_DATE\", \"SCHEDULE_SHIP_DATE\", \"ACTUAL_SHIPMENT_DATE\", \"AGREEMENT_NUMBER\", \"ITEM_TYPE_CODE\", \"PAYMENT_TYPE\", \"CREDIT_CARD_CODE\", \"CREDIT_CARD_NUMBER\", \"CREDIT_CARD_HOLDER_NAME\", \"CREDIT_CARD_EXPIRATION_DATE\", \"CREDIT_CARD_APPROVAL_CODE\", \"BILL_TO_NAME\", \"BILL_TO_COUNTRY\", \"BILL_TO_ADDRESS1\", \"BILL_TO_ADDRESS2\", \"BILL_TO_ADDRESS3\", \"BILL_TO_ADDRESS4\", \"BILL_TO_CITY\", \"BILL_TO_STATE\", \"BILL_TO_POSTAL_CODE\", \"BILL_TO_COUNTY\", \"BILL_TO_PROVINCE\", \"BILL_TO_SITE\", \"BILL_TO_CONTACT\", \"SHIP_TO_CONTACT\", \"SHIP_TO_SITE\", \"SHIP_TO_COUNTY\", \"SHIP_TO_PROVINCE\", \"SHIP_TO_NAME\", \"SHIP_TO_COUNTRY\", \"SHIP_TO_ADDRESS1\", \"SHIP_TO_ADDRESS2\", \"SHIP_TO_ADDRESS3\", \"SHIP_TO_ADDRESS4\", \"SHIP_TO_CITY\", \"SHIP_TO_STATE\", \"SHIP_TO_POSTAL_CODE\", \"END_USER\", \"END_USER_NUMBER\", \"END_USER_CONTACT\", \"END_USER_ADDRESS1\", \"END_USER_ADDRESS2\", \"END_USER_ADDRESS3\", \"END_USER_CITY\", \"END_USER_STATE\", \"END_USER_POSTAL_CODE\", \"END_USER_COUNTY\", \"END_USER_PROVINCE\", \"END_USER_COUNTRY_NAME\", \"SALESPERSON\", \"MAJOR_GEOGRAPHICAL_AREA\", \"GL_CLASS\", \"PARTY_NUMBER\", \"CUSTOMER_CLASS\", \"CUSTOMER_CATEGORY\", \"CUSTOMER_TYPE\", \"TAX_REGISTRATION_NUMBER\", \"FREIGHT_TERM\", \"FOB\", \"FISCAL_WEEK_GL_DATE\", \"FISCAL_PERIOD_GL_DATE\", \"FISCAL_QUARTER_GL_DATE\", \"FISCAL_YEAR_GL_DATE\", \"LEGAL_ENTITY_ID\", \"LEGAL_ENTITY\", \"OPERATING_UNIT_ID\", \"OPERATING_UNIT\", \"TRANSACTION_CURRENCY\", \"TRX_TO_USD_RATE\", \"TRX_TO_FUNC_RATE\", \"COST_TO_FUNC_RATE\", \"COST_TO_USD_RATE\", \"TERR_AREA\", \"TERR_OFFICE\", \"TERR_SALES_MGR_TERR_NUM\", \"TERR_TYPE\", \"TERR_NUM\", \"UNIT_SELLING_PRICE_USD\", \"UNIT_LIST_PRICE_USD\", \"ITEM_UNIT_COST_USD\", \"ITEM_ADD_BACK_UNIT_COST_USD\", \"ITEM_MATERIAL_COST_USD\", \"ITEM_LABOR_COST_USD\", \"ITEM_MATERIAL_OVERHEAD_USD\", \"ITEM_LABOR_OVERHEAD_USD\", \"ITEM_OUT_PROC_COST_USD\", \"EXTENDED_AMOUNT_USD\", \"EXTENDED_COST_USD\", \"EXTENDED_ADD_BACK_COST_USD\", \"DISCOUNT_AMOUNT_USD\", \"TAX_AMOUNT_USD\", \"G_TR_ITEM_UNIT_COST\", \"G_TR_ITEM_MATERIAL_COST\", \"G_TR_ITEM_LABOR_COST\", \"G_TR_ITEM_MATERIAL_OVERHEAD\", \"G_TR_ITEM_LABOR_OVERHEAD\", \"G_TR_ITEM_OUT_PROC_COST\", \"G_TR_EXTENDED_COST\", \"G_ITEM_UNIT_COST\", \"G_ITEM_MATERIAL_COST\", \"G_ITEM_LABOR_COST\", \"G_ITEM_MATERIAL_OVERHEAD\", \"G_ITEM_LABOR_OVERHEAD\", \"G_ITEM_OUT_PROC_COST\", \"G_EXTENDED_COST\", \"G_GROSS_MARGIN_PCT\", \"G_ITEM_UNIT_COST_USD\", \"G_ITEM_MATERIAL_COST_USD\", \"G_ITEM_LABOR_COST_USD\", \"G_ITEM_MATERIAL_OVERHEAD_USD\", \"G_ITEM_LABOR_OVERHEAD_USD\", \"G_ITEM_OUT_PROC_COST_USD\", \"G_EXTENDED_COST_USD\", \"F_TR_ITEM_UNIT_COST\", \"F_TR_ITEM_MATERIAL_COST\", \"F_TR_ITEM_LABOR_COST\", \"F_TR_ITEM_MATERIAL_OVERHEAD\", \"F_TR_ITEM_LABOR_OVERHEAD\", \"F_TR_ITEM_OUT_PROC_COST\", \"F_TR_EXTENDED_COST\", \"F_ITEM_UNIT_COST\", \"F_ITEM_MATERIAL_COST\", \"F_ITEM_LABOR_COST\", \"F_ITEM_MATERIAL_OVERHEAD\", \"F_ITEM_LABOR_OVERHEAD\", \"F_ITEM_OUT_PROC_COST\", \"F_EXTENDED_COST\", \"F_GROSS_MARGIN_PCT\", \"F_ITEM_UNIT_COST_USD\", \"F_ITEM_MATERIAL_COST_USD\", \"F_ITEM_LABOR_COST_USD\", \"F_ITEM_MATERIAL_OVERHEAD_USD\", \"F_ITEM_LABOR_OVERHEAD_USD\", \"F_ITEM_OUT_PROC_COST_USD\", \"F_EXTENDED_COST_USD\", \"OVERWRITE_CURRENCY_CI\", \"OVERWRITE_UNIT_PRICE_CI\", \"OVERWRITE_EXT_PRICE_CI\", \"END_CUST_USD_RATE\", \"OVERWRITE_UNIT_PRICE_CI_USD\", \"OVERWRITE_EXT_PRICE_CI_USD\", \"M20_REPORTING_ENTITY\", \"REPEAT_BUSINESS\", \"FLASH_OFFICE\", \"PLANNER_CODE\", \"END_ASSEMBLY_PEGGING\", \"PAYMENT_TERM\", \"TIMESTAMP\", \"REC_ENTITY\", \"REC_DEPT\", \"REC_ACCOUNT\", \"REC_PROJECT\", \"REC_INTERCO\", \"REC_TBD\", \"EXTERNAL_ORDER_NUMBER\", \"INTERCO_PO_NUM\", \"SO_LINE_ID\", \"SO_HEADER_ID\", \"CUSTOMER_TRX_ID\", \"CUSTOMER_TRX_LINE_ID\", \"CST_CURRENCY_CODE\", \"PROJECT_ID\", \"PROJECT_NAME\", \"PROJECT_NUMBER\", \"SPL_COGS_FLAG\", \"COGS_ACCOUNT\", \"IMPORTER_NAME\", \"IMPORTER_NUMBER\", \"IMPORTER_ADDRESS1\", \"IMPORTER_ADDRESS2\", \"IMPORTER_CITY\", \"IMPORTER_STATE\", \"IMPORTER_POSTAL_CODE\", \"IMPORTER_COUNTY\", \"IMPORTER_PROVINCE\", \"IMPORTER_COUNTRY_NAME\", \"BILL_TO_ADDRESS_ID\", \"SHIP_TO_ADDRESS_ID\", \"IMPORTER_ADDRESS_ID\", \"END_USER_ADDRESS_ID\", \"LAST_UPDATE_DATE\", \"SITE\", \"FIN_PRODUCT_GROUP\", \"FIN_PRODUCT_FAMILY\", \"FIN_FORECAST_FIELD\", \"FIN_MGMT_MARKET\", \"FIN_CORP_MARKET\", \"FIN_ACCOUNT\", \"FIN_UNIT_ACCOUNT\", \"FIN_UNIT\", \"BILLING_SOURCE\", \"CONTRACT_NUMBER\", \"CONTRACT_NUMBER_MODIFIER\", \"CLE_ID\", \"PERIOD_NAME\", \"DIST_ID\", \"ROW_CREATION_DATE\"})\r\nin\r\n  #\"Reordered columns\";\r\nshared ORGTechnicalBusinessUnit = let\r\n  #\"Parameter-TechnicalBusinessUnit\" = \"DPSS Germany\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type any]\r\nin\r\n  #\"Parameter-TechnicalBusinessUnit\";\r\nshared XXCOH_INSTALL_BASE_VIEW = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 1\" = Navigation{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXCOH_INSTALL_BASE_VIEW\", Kind = \"View\"]}[Data],\r\n  #\"Filtered rows OrgBusinessUnit\" = Table.SelectRows(#\"Navigation 2\", each [PROD_TBU] = ORGTechnicalBusinessUnit),\r\n  #\"Filtered rows OrgProductFamily\" = Table.SelectRows(#\"Filtered rows OrgBusinessUnit\", each [PROD_FAMILY] = OrgProductFamily or [PROD_FAMILY] = #\"OrgProductFamily (2)\" or [PROD_FAMILY] = #\"OrgProductFamily (3)\" or [PROD_FAMILY] = #\"OrgProductFamily (4)\" or [PROD_FAMILY] = #\"OrgProductFamily (5)\" or [PROD_FAMILY] = #\"OrgProductFamily (6)\" or [PROD_FAMILY] = #\"OrgProductFamily (7)\" or [PROD_FAMILY] = #\"OrgProductFamily (8)\"),\r\n  #\"Calculated date\" = Table.TransformColumns(#\"Filtered rows OrgProductFamily\", {{\"INSTALL_DATE\", each DateTime.Date(_), type nullable date}, {\"ORIGINAL_INSTALL_DATE\", each DateTime.Date(_), type nullable date}, {\"ACTIVE_START_DATE\", each DateTime.Date(_), type nullable date}, {\"ORDERED_DATE\", each DateTime.Date(_), type nullable date}, {\"SHIPPED_ON_DATE\", each DateTime.Date(_), type nullable date}, {\"ACTUAL_RETURN_DATE\", each DateTime.Date(_), type nullable date}})\r\nin\r\n  #\"Calculated date\";\r\nshared XXCOH_MS_SHIPMENT_VIEW = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 1\" = Navigation{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXCOH_MS_SHIPMENT_VIEW\", Kind = \"View\"]}[Data],\r\n  #\"Sorted rows\" = Table.Sort(#\"Navigation 2\", {{\"ENTER_DATE\", Order.Descending}}),\r\n  #\"Filtered rows OrgTechnicalBusinessUnit\" = Table.SelectRows(#\"Sorted rows\", each [ORG_TECHNICAL_BUSINESS_UNIT] = ORGTechnicalBusinessUnit),\r\n  #\"Filtered rows -ActualShipmentDate is not null\" = Table.SelectRows(#\"Filtered rows OrgTechnicalBusinessUnit\", each ([ACTUAL_SHIPMENT_DATE] <> null)),\r\n  #\"Filtered rows-Product Family\" = Table.SelectRows(#\"Filtered rows -ActualShipmentDate is not null\", each [ORG_PRODUCT_FAMILY] = OrgProductFamily or [ORG_PRODUCT_FAMILY] = #\"OrgProductFamily (2)\" or [ORG_PRODUCT_FAMILY] = #\"OrgProductFamily (3)\" or [ORG_PRODUCT_FAMILY] = #\"OrgProductFamily (4)\" or [ORG_PRODUCT_FAMILY] = #\"OrgProductFamily (5)\" or [ORG_PRODUCT_FAMILY] = #\"OrgProductFamily (6)\" or [ORG_PRODUCT_FAMILY] = #\"OrgProductFamily (7)\" or [ORG_PRODUCT_FAMILY] = #\"OrgProductFamily (8)\" or [ORG_PRODUCT_FAMILY] = #\"OrgProductFamily (9)\"),\r\n  #\"Calculated date\" = Table.TransformColumns(#\"Filtered rows-Product Family\", {{\"ACTUAL_SHIPMENT_DATE\", each DateTime.Date(_), type nullable date}}),\r\n  #\"Filtered rows\" = Table.SelectRows(#\"Calculated date\", each [ACTUAL_SHIPMENT_DATE] > #date(2011, 1, 1))\r\nin\r\n  #\"Filtered rows\";\r\nshared OrgProductFamily = let\r\n  OrgProductFamily1 = \"Azure_NX\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type any]\r\nin\r\n  OrgProductFamily1;\r\nshared #\"OrgProductFamily (2)\" = let\r\n  OrgProductFamily1 = \"Paladin\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type any]\r\nin\r\n  OrgProductFamily1;\r\nshared #\"OrgProductFamily (3)\" = let\r\n  OrgProductFamily1 = \"AVIA_LX\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type any]\r\nin\r\n  OrgProductFamily1;\r\nshared #\"OrgProductFamily (4)\" = let\r\n  OrgProductFamily1 = \"Sapphire\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type any]\r\nin\r\n  OrgProductFamily1;\r\nshared #\"OrgProductFamily (5)\" = let\r\n  OrgProductFamily1 = \"Compass CW\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type any]\r\nin\r\n  OrgProductFamily1;\r\nshared #\"OrgProductFamily (6)\" = let\r\n  OrgProductFamily1 = \"Compass QS\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type any]\r\nin\r\n  OrgProductFamily1;\r\nshared #\"OrgProductFamily (7)\" = let\r\n  OrgProductFamily1 = \"OBIS_LS\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type any]\r\nin\r\n  OrgProductFamily1;\r\nshared #\"OrgProductFamily (8)\" = let\r\n  OrgProductFamily1 = \"OBIS_XT\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type any]\r\nin\r\n  OrgProductFamily1;\r\nshared #\"OrgProductFamily (9)\" = let\r\n  OrgProductFamily1 = \"Cosmos\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type any]\r\nin\r\n  OrgProductFamily1;\r\nshared XXCOH_BACKLOG_FLASH_CUR_PRD_V = let\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\n  #\"Navigation 1\" = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\n  #\"Navigation 3\" = #\"Navigation 2\"{[Name = \"XXCOH_BACKLOG_FLASH_CUR_PRD_V\", Kind = \"View\"]}[Data],\r\n  #\"Filtered rows\" = Table.SelectRows(#\"Navigation 3\", each [FIN_PRODUCT_GROUP] = ORGTechnicalBusinessUnit)\nin\n  #\"Filtered rows\";\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"XXCOH_BACKLOG_VIEW","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"XXCOH_BACKLOG_VIEW.csv"},"attributes":[{"name":"ASOF_DATE","dataType":"date"},{"name":"ORDER_NUMBER","dataType":"double"},{"name":"CUSTOMER_NUMBER","dataType":"string"},{"name":"CUSTOMER_NAME","dataType":"string"},{"name":"CUSTOMER_ALTERNATE_NAME","dataType":"string"},{"name":"CUSTOMER_NAME_REPORTING","dataType":"string"},{"name":"ASOF_DATE_DISP","dataType":"date"},{"name":"BACKLOG_DATE","dataType":"date"},{"name":"ENTER_DATE","dataType":"dateTime"},{"name":"BOOKED_DATE","dataType":"date"},{"name":"ORDER_LINE","dataType":"string"},{"name":"ORDER_TYPE","dataType":"string"},{"name":"SO_LINE_TYPE","dataType":"string"},{"name":"LINE_STATUS","dataType":"string"},{"name":"BILLABLE_FLAG","dataType":"string"},{"name":"INV_FLAG","dataType":"string"},{"name":"LINE_CATEGORY_CODE","dataType":"string"},{"name":"LINE_SOURCE_TYPE_CODE","dataType":"string"},{"name":"SALES_CHANNEL","dataType":"string"},{"name":"ORDER_SOURCE","dataType":"string"},{"name":"ORDER_SOURCE_REFERENCE","dataType":"string"},{"name":"ORDER_SOURCE_LINE_REFERENCE","dataType":"string"},{"name":"AGREEMENT_NUMBER","dataType":"string"},{"name":"ITEM_TYPE_CODE","dataType":"string"},{"name":"HOLD_STATUS","dataType":"string"},{"name":"HOLD_REASON","dataType":"string"},{"name":"REGIONAL_LOCATION","dataType":"string"},{"name":"REPORTING_ENTITY","dataType":"string"},{"name":"CUSTOMER_PO","dataType":"string"},{"name":"CREATED_BY","dataType":"string"},{"name":"ITEM_NUMBER","dataType":"string"},{"name":"ITEM_DESCRIPTION","dataType":"string"},{"name":"ITEM_STATUS","dataType":"string"},{"name":"PRODUCT_LINE","dataType":"string"},{"name":"PRODUCT_FAMILY","dataType":"string"},{"name":"TECHNICAL_BUSINESS_UNIT","dataType":"string"},{"name":"REVENUE_ACCOUNT","dataType":"string"},{"name":"FORECAST_FIELD","dataType":"string"},{"name":"COMMODITY","dataType":"string"},{"name":"ORG_PRODUCT_LINE","dataType":"string"},{"name":"ORG_PRODUCT_FAMILY","dataType":"string"},{"name":"ORG_TECHNICAL_BUSINESS_UNIT","dataType":"string"},{"name":"ORG_FORECAST_FIELD","dataType":"string"},{"name":"LEAD_TIME","dataType":"string"},{"name":"PRIMARY_ORG","dataType":"string"},{"name":"ITEM_CUSTOMER","dataType":"string"},{"name":"BCP_CODE","dataType":"string"},{"name":"ROYALTY","dataType":"string"},{"name":"WAREHOUSE","dataType":"string"},{"name":"SHIPMENT_PRIORITY_CODE","dataType":"string"},{"name":"SHIPPING_METHOD_CODE","dataType":"string"},{"name":"RETURN_REASON","dataType":"string"},{"name":"EXPIRATION_DATE","dataType":"string"},{"name":"BACKLOG_QUANTITY","dataType":"double"},{"name":"ASP_QUANTITY","dataType":"double"},{"name":"ASP_FLAG","dataType":"string"},{"name":"COMMISSION_SALESREP","dataType":"string"},{"name":"COMMISSION_PERCENT","dataType":"double"},{"name":"OVERWRITE_CURRENCY_CI","dataType":"string"},{"name":"OVERWRITE_UNIT_PRICE_CI","dataType":"double"},{"name":"OVERWRITE_EXT_PRICE_CI","dataType":"double"},{"name":"END_CUST_USD_RATE","dataType":"double"},{"name":"OVERWRITE_UNIT_PRICE_CI_USD","dataType":"double"},{"name":"OVERWRITE_EXT_PRICE_CI_USD","dataType":"double"},{"name":"TR_UNIT_SELLING_PRICE","dataType":"double"},{"name":"TR_ITEM_UNIT_COST","dataType":"double"},{"name":"TR_ITEM_MATERIAL_COST","dataType":"double"},{"name":"TR_ITEM_LABOR_COST","dataType":"double"},{"name":"TR_ITEM_MATERIAL_OVERHEAD","dataType":"double"},{"name":"TR_ITEM_LABOR_OVERHEAD","dataType":"double"},{"name":"TR_ITEM_OUT_PROC_COST","dataType":"double"},{"name":"TR_UNIT_LIST_PRICE","dataType":"double"},{"name":"TR_EXTENDED_AMOUNT","dataType":"double"},{"name":"TR_EXTENDED_COST","dataType":"double"},{"name":"GROSS_MARGIN_PCT","dataType":"double"},{"name":"DISCOUNT_PERCENT","dataType":"double"},{"name":"TR_DISCOUNT_AMOUNT","dataType":"double"},{"name":"PRICE_LIST","dataType":"string"},{"name":"UNIT_SELLING_PRICE","dataType":"double"},{"name":"ITEM_UNIT_COST","dataType":"double"},{"name":"ITEM_MATERIAL_COST","dataType":"double"},{"name":"ITEM_LABOR_COST","dataType":"double"},{"name":"ITEM_MATERIAL_OVERHEAD","dataType":"double"},{"name":"ITEM_LABOR_OVERHEAD","dataType":"double"},{"name":"ITEM_OUT_PROC_COST","dataType":"double"},{"name":"UNIT_LIST_PRICE","dataType":"double"},{"name":"EXTENDED_AMOUNT","dataType":"double"},{"name":"EXTENDED_COST","dataType":"double"},{"name":"DISCOUNT_AMOUNT","dataType":"double"},{"name":"APPLICATION_CODE","dataType":"string"},{"name":"APPLICATION_CODE_DESC","dataType":"string"},{"name":"MARKET_SEGMENT","dataType":"string"},{"name":"REQUEST_SHIP_DATE","dataType":"date"},{"name":"PROMISE_SHIP_DATE","dataType":"date"},{"name":"SCHEDULE_SHIP_DATE","dataType":"date"},{"name":"TAX_REGISTRATION_NUMBER","dataType":"string"},{"name":"PARTY_NUMBER","dataType":"string"},{"name":"BILL_TO_NAME","dataType":"string"},{"name":"BILL_TO_COUNTRY","dataType":"string"},{"name":"BILL_TO_ADDRESS1","dataType":"string"},{"name":"BILL_TO_ADDRESS2","dataType":"string"},{"name":"BILL_TO_ADDRESS3","dataType":"string"},{"name":"BILL_TO_ADDRESS4","dataType":"string"},{"name":"BILL_TO_CITY","dataType":"string"},{"name":"BILL_TO_STATE","dataType":"string"},{"name":"BILL_TO_POSTAL_CODE","dataType":"string"},{"name":"BILL_TO_COUNTY","dataType":"string"},{"name":"BILL_TO_PROVINCE","dataType":"string"},{"name":"BILL_TO_SITE","dataType":"string"},{"name":"BILL_TO_CONTACT","dataType":"string"},{"name":"SHIP_TO_NAME","dataType":"string"},{"name":"SHIP_TO_COUNTRY","dataType":"string"},{"name":"SHIP_TO_ADDRESS1","dataType":"string"},{"name":"SHIP_TO_ADDRESS2","dataType":"string"},{"name":"SHIP_TO_ADDRESS3","dataType":"string"},{"name":"SHIP_TO_ADDRESS4","dataType":"string"},{"name":"SHIP_TO_CITY","dataType":"string"},{"name":"SHIP_TO_STATE","dataType":"string"},{"name":"SHIP_TO_POSTAL_CODE","dataType":"string"},{"name":"SHIP_TO_COUNTY","dataType":"string"},{"name":"SHIP_TO_PROVINCE","dataType":"string"},{"name":"SHIP_TO_SITE","dataType":"string"},{"name":"SHIP_TO_CONTACT","dataType":"string"},{"name":"END_USER","dataType":"string"},{"name":"END_USER_NUMBER","dataType":"string"},{"name":"END_USER_CONTACT","dataType":"string"},{"name":"SALESPERSON","dataType":"string"},{"name":"MAJOR_GEOGRAPHICAL_AREA","dataType":"string"},{"name":"GL_CLASS","dataType":"string"},{"name":"CUSTOMER_CLASS","dataType":"string"},{"name":"CUSTOMER_CATEGORY","dataType":"string"},{"name":"CUSTOMER_TYPE","dataType":"string"},{"name":"PAYMENT_TYPE","dataType":"string"},{"name":"CREDIT_CARD_CODE","dataType":"string"},{"name":"CREDIT_CARD_NUMBER","dataType":"string"},{"name":"CREDIT_CARD_HOLDER_NAME","dataType":"string"},{"name":"CREDIT_CARD_EXPIRATION_DATE","dataType":"dateTime"},{"name":"CREDIT_CARD_APPROVAL_CODE","dataType":"string"},{"name":"FREIGHT_TERM","dataType":"string"},{"name":"FOB","dataType":"string"},{"name":"FISCAL_WEEK_BOOKED","dataType":"double"},{"name":"FISCAL_PERIOD_BOOKED","dataType":"double"},{"name":"FISCAL_QUARTER_BOOKED","dataType":"double"},{"name":"FISCAL_YEAR_BOOKED","dataType":"double"},{"name":"SCHEDULE_CATEGORY","dataType":"string"},{"name":"SCHEDULE_CATEGORY_PERIOD","dataType":"string"},{"name":"SCHEDULE_ORDER","dataType":"double"},{"name":"LEGAL_ENTITY_ID","dataType":"double"},{"name":"LEGAL_ENTITY","dataType":"string"},{"name":"OPERATING_UNIT_ID","dataType":"double"},{"name":"OPERATING_UNIT","dataType":"string"},{"name":"TRANSACTION_CURRENCY","dataType":"string"},{"name":"FUNCTIONAL_CURRENCY","dataType":"string"},{"name":"TRX_TO_USD_RATE","dataType":"double"},{"name":"TRX_TO_FUNC_RATE","dataType":"double"},{"name":"COST_TO_FUNC_RATE","dataType":"double"},{"name":"COST_TO_USD_RATE","dataType":"double"},{"name":"ME_TRX_TO_USD_RATE","dataType":"double"},{"name":"ME_TRX_TO_FUNC_RATE","dataType":"double"},{"name":"ME_END_CUST_USD_RATE","dataType":"double"},{"name":"ME_COST_TO_FUNC_RATE","dataType":"double"},{"name":"ME_COST_TO_USD_RATE","dataType":"double"},{"name":"UNIT_SELLING_PRICE_USD","dataType":"double"},{"name":"UNIT_LIST_PRICE_USD","dataType":"double"},{"name":"ITEM_UNIT_COST_USD","dataType":"double"},{"name":"ITEM_MATERIAL_COST_USD","dataType":"double"},{"name":"ITEM_LABOR_COST_USD","dataType":"double"},{"name":"ITEM_MATERIAL_OVERHEAD_USD","dataType":"double"},{"name":"ITEM_LABOR_OVERHEAD_USD","dataType":"double"},{"name":"ITEM_OUT_PROC_COST_USD","dataType":"double"},{"name":"EXTENDED_AMOUNT_USD","dataType":"double"},{"name":"EXTENDED_COST_USD","dataType":"double"},{"name":"DISCOUNT_AMOUNT_USD","dataType":"double"},{"name":"TERR_AREA","dataType":"string"},{"name":"TERR_OFFICE","dataType":"string"},{"name":"TERR_SALES_MGR_TERR_NUM","dataType":"string"},{"name":"TERR_TYPE","dataType":"string"},{"name":"TERR_NUM","dataType":"string"},{"name":"ORDER_STATUS","dataType":"string"},{"name":"STAGED_QTY","dataType":"double"},{"name":"TR_STAGED_EXT_AMOUNT","dataType":"double"},{"name":"STAGED_EXT_AMOUNT","dataType":"double"},{"name":"STAGED_EXT_AMOUNT_USD","dataType":"double"},{"name":"O_GROSS_MARGIN_PCT","dataType":"string"},{"name":"O_UNIT_SELLING_PRICE","dataType":"string"},{"name":"O_ITEM_UNIT_COST","dataType":"string"},{"name":"O_ITEM_MATERIAL_COST","dataType":"string"},{"name":"O_ITEM_LABOR_COST","dataType":"string"},{"name":"O_ITEM_MATERIAL_OVERHEAD","dataType":"string"},{"name":"O_ITEM_LABOR_OVERHEAD","dataType":"string"},{"name":"O_ITEM_OUT_PROC_COST","dataType":"string"},{"name":"O_UNIT_LIST_PRICE","dataType":"string"},{"name":"O_EXTENDED_AMOUNT","dataType":"string"},{"name":"O_EXTENDED_COST","dataType":"string"},{"name":"O_DISCOUNT_AMOUNT","dataType":"string"},{"name":"O_UNIT_SELLING_PRICE_USD","dataType":"string"},{"name":"O_UNIT_LIST_PRICE_USD","dataType":"string"},{"name":"O_ITEM_UNIT_COST_USD","dataType":"string"},{"name":"O_ITEM_MATERIAL_COST_USD","dataType":"string"},{"name":"O_ITEM_LABOR_COST_USD","dataType":"string"},{"name":"O_ITEM_MATERIAL_OVERHEAD_USD","dataType":"string"},{"name":"O_ITEM_LABOR_OVERHEAD_USD","dataType":"string"},{"name":"O_ITEM_OUT_PROC_COST_USD","dataType":"string"},{"name":"O_EXTENDED_AMOUNT_USD","dataType":"string"},{"name":"O_EXTENDED_COST_USD","dataType":"string"},{"name":"O_DISCOUNT_AMOUNT_USD","dataType":"string"},{"name":"O_OVERWRITE_UNIT_PRICE_CI_USD","dataType":"string"},{"name":"O_OVERWRITE_EXT_PRICE_CI_USD","dataType":"string"},{"name":"O_STAGED_EXT_AMOUNT","dataType":"string"},{"name":"O_STAGED_EXT_AMOUNT_USD","dataType":"string"},{"name":"REPEAT_BUSINESS","dataType":"string"},{"name":"M20_REPORTING_ENTITY","dataType":"string"},{"name":"FLASH_OFFICE","dataType":"string"},{"name":"PLANNER_CODE","dataType":"string"},{"name":"END_ASSEMBLY_PEGGING","dataType":"string"},{"name":"PARTIAL_SHIPMENTS_ALLOWED","dataType":"string"},{"name":"PAYMENT_TERM","dataType":"string"},{"name":"TIMESTAMP","dataType":"date"},{"name":"ROW_ID","dataType":"double"},{"name":"FIRST_SCHEDULE_DATE","dataType":"date"},{"name":"EXTERNAL_ORDER_NUMBER","dataType":"string"},{"name":"INTERCO_PO_NUM","dataType":"string"},{"name":"SHIPPING_INSTRUCTIONS","dataType":"string"},{"name":"PACKING_INSTRUCTIONS","dataType":"string"},{"name":"LINE_ID","dataType":"double"},{"name":"HEADER_ID","dataType":"double"},{"name":"SOURCE_DOCUMENT_LINE_ID","dataType":"double"},{"name":"SOURCE_DOCUMENT_ID","dataType":"double"},{"name":"SOURCE_DOCUMENT_TYPE_ID","dataType":"double"},{"name":"PROJECT_ID","dataType":"double"},{"name":"PROJECT_NAME","dataType":"string"},{"name":"PROJECT_NUMBER","dataType":"string"},{"name":"TR_ESTIMATED_UNIT_TRF_PRICE","dataType":"double"},{"name":"TR_EXT_ESTIMATED_TRF_PRICE","dataType":"double"},{"name":"ESTIMATED_UNIT_TRF_PRICE","dataType":"double"},{"name":"EXT_ESTIMATED_TRF_PRICE","dataType":"double"},{"name":"ESTIMATED_UNIT_TRF_PRICE_USD","dataType":"double"},{"name":"EXT_ESTIMATED_TRF_PRICE_USD","dataType":"double"},{"name":"SPL_COGS_FLAG","dataType":"string"},{"name":"COGS_ACCOUNT","dataType":"string"},{"name":"IMPORTER_NAME","dataType":"string"},{"name":"IMPORTER_NUMBER","dataType":"string"},{"name":"IMPORTER_ADDRESS1","dataType":"string"},{"name":"IMPORTER_ADDRESS2","dataType":"string"},{"name":"IMPORTER_CITY","dataType":"string"},{"name":"IMPORTER_STATE","dataType":"string"},{"name":"IMPORTER_POSTAL_CODE","dataType":"string"},{"name":"IMPORTER_COUNTY","dataType":"string"},{"name":"IMPORTER_PROVINCE","dataType":"string"},{"name":"IMPORTER_COUNTRY_NAME","dataType":"string"},{"name":"END_USER_ADDRESS1","dataType":"string"},{"name":"END_USER_ADDRESS2","dataType":"string"},{"name":"END_USER_ADDRESS3","dataType":"string"},{"name":"END_USER_CITY","dataType":"string"},{"name":"END_USER_STATE","dataType":"string"},{"name":"END_USER_POSTAL_CODE","dataType":"string"},{"name":"END_USER_COUNTY","dataType":"string"},{"name":"END_USER_PROVINCE","dataType":"string"},{"name":"CST_CURRENCY_CODE","dataType":"string"},{"name":"BILL_TO_ADDRESS_ID","dataType":"double"},{"name":"SHIP_TO_ADDRESS_ID","dataType":"double"},{"name":"END_USER_ADDRESS_ID","dataType":"double"},{"name":"IMPORTER_ADDRESS_ID","dataType":"double"},{"name":"FIN_SITE","dataType":"string"},{"name":"FIN_ENTITY","dataType":"string"},{"name":"FIN_PRODUCT_GROUP","dataType":"string"},{"name":"FIN_PRODUCT_FAMILY","dataType":"string"},{"name":"FIN_FORECAST_FIELD","dataType":"string"},{"name":"FIN_MGMT_MARKET","dataType":"string"},{"name":"FIN_CORP_MARKET","dataType":"string"},{"name":"FIN_BACKLOG_STATUS_1","dataType":"string"},{"name":"FIN_BACKLOG_STATUS","dataType":"string"},{"name":"FIN_BACKLOG_ROLLUP","dataType":"string"},{"name":"FIN_UNIT","dataType":"double"},{"name":"HFM_PRODUCT_FAMILY","dataType":"string"},{"name":"HFM_BACKLOG_ACCOUNT","dataType":"string"},{"name":"CONTRACT_START_DATE","dataType":"date"},{"name":"CONTRACT_END_DATE","dataType":"date"},{"name":"CONTRACT_HEADER_ID","dataType":"string"},{"name":"CONTRACT_LINE_ID","dataType":"string"},{"name":"PERIOD_NAME","dataType":"string"},{"name":"PERIOD_START_DATE","dataType":"dateTime"},{"name":"PERIOD_END_DATE","dataType":"dateTime"},{"name":"BCK_KEY","dataType":"string"},{"name":"ROW_CREATION_DATE","dataType":"dateTime"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-17T03:02:33.6394278+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/ec19509b-a36a-47a9-8e62-7b789f57b7ea/XXCOH_BACKLOG_VIEW.csv?snapshot=2022-05-17T03%3A02%3A33.5453218Z"}]},{"$type":"LocalEntity","name":"XXCOH_BILLING_VIEW","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"XXCOH_BILLING_VIEW.csv"},"attributes":[{"name":"ASOF_DATE","dataType":"date"},{"name":"CUSTOMER_NUMBER","dataType":"string"},{"name":"CUSTOMER_NAME","dataType":"string"},{"name":"CUSTOMER_ALTERNATE_NAME","dataType":"string"},{"name":"CUSTOMER_NAME_REPORTING","dataType":"string"},{"name":"ASOF_DATE_DISP","dataType":"string"},{"name":"BACKUP_DATE","dataType":"date"},{"name":"BOOKED_DATE","dataType":"dateTime"},{"name":"INVOICE_CREATION_DATE","dataType":"dateTime"},{"name":"INVOICE_DATE","dataType":"dateTime"},{"name":"WAREHOUSE","dataType":"string"},{"name":"ORDER_NUMBER","dataType":"double"},{"name":"ORDER_LINE","dataType":"string"},{"name":"ORDER_TYPE","dataType":"string"},{"name":"SO_LINE_TYPE","dataType":"string"},{"name":"SALES_CHANNEL","dataType":"string"},{"name":"SHIPMENT_PRIORITY_CODE","dataType":"string"},{"name":"SHIPPING_METHOD_CODE","dataType":"string"},{"name":"RETURN_REASON","dataType":"string"},{"name":"LINE_CATEGORY_CODE","dataType":"string"},{"name":"LINE_SOURCE_TYPE_CODE","dataType":"string"},{"name":"REGIONAL_LOCATION","dataType":"string"},{"name":"REPORTING_ENTITY","dataType":"string"},{"name":"ASIA_INVOICE_NO","dataType":"string"},{"name":"INVOICE_NUMBER","dataType":"string"},{"name":"INVOICE_LINE","dataType":"double"},{"name":"INVOICE_CLASS","dataType":"string"},{"name":"INVOICE_TYPE","dataType":"string"},{"name":"FUNCTIONAL_CURRENCY","dataType":"string"},{"name":"CUSTOMER_PO","dataType":"string"},{"name":"ITEM_NUMBER","dataType":"string"},{"name":"ITEM_DESCRIPTION","dataType":"string"},{"name":"PRODUCT_LINE","dataType":"string"},{"name":"PRODUCT_FAMILY","dataType":"string"},{"name":"TECHNICAL_BUSINESS_UNIT","dataType":"string"},{"name":"FORECAST_FIELD","dataType":"string"},{"name":"COMMODITY","dataType":"string"},{"name":"ORG_PRODUCT_LINE","dataType":"string"},{"name":"ORG_PRODUCT_FAMILY","dataType":"string"},{"name":"ORG_TECHNICAL_BUSINESS_UNIT","dataType":"string"},{"name":"ORG_FORECAST_FIELD","dataType":"string"},{"name":"PATLEX","dataType":"string"},{"name":"LEAD_TIME","dataType":"string"},{"name":"PRIMARY_ORG","dataType":"string"},{"name":"BCP_CODE","dataType":"string"},{"name":"ITEM_CUSTOMER","dataType":"string"},{"name":"ROYALTY","dataType":"string"},{"name":"INVOICED_QUANTITY","dataType":"double"},{"name":"ASP_QUANTITY","dataType":"double"},{"name":"ASP_FLAG","dataType":"string"},{"name":"COMMISSION_SALESREP","dataType":"string"},{"name":"COMMISSION_PERCENT","dataType":"double"},{"name":"AMORTIZED_FLAG","dataType":"string"},{"name":"ACCOUNTING_RULE","dataType":"string"},{"name":"RULE_DURATION","dataType":"double"},{"name":"RULE_REMAINING","dataType":"double"},{"name":"RULE_COMPLETED","dataType":"string"},{"name":"TR_UNEARNED_REVENUE","dataType":"double"},{"name":"UNEARNED_REVENUE","dataType":"double"},{"name":"UNEARNED_REVENUE_USD","dataType":"double"},{"name":"ACCT_ENTITY","dataType":"string"},{"name":"REVENUE_DEPT","dataType":"string"},{"name":"REVENUE_ACCT","dataType":"string"},{"name":"REVENUE_IC","dataType":"string"},{"name":"UNEARNED_ENTITY","dataType":"string"},{"name":"UNEARNED_DEPT","dataType":"string"},{"name":"UNEARNED_ACCT","dataType":"string"},{"name":"UNEARNED_IC","dataType":"string"},{"name":"GL_DATE","dataType":"dateTime"},{"name":"GL_POSTED_DATE","dataType":"dateTime"},{"name":"TR_REVENUE","dataType":"double"},{"name":"REVENUE","dataType":"double"},{"name":"REVENUE_USD","dataType":"double"},{"name":"TR_UNIT_SELLING_PRICE","dataType":"double"},{"name":"TR_ITEM_UNIT_COST","dataType":"double"},{"name":"TR_ITEM_ADD_BACK_UNIT_COST","dataType":"double"},{"name":"TR_ITEM_MATERIAL_COST","dataType":"double"},{"name":"TR_ITEM_LABOR_COST","dataType":"double"},{"name":"TR_ITEM_MATERIAL_OVERHEAD","dataType":"double"},{"name":"TR_ITEM_LABOR_OVERHEAD","dataType":"double"},{"name":"TR_ITEM_OUT_PROC_COST","dataType":"double"},{"name":"TR_UNIT_LIST_PRICE","dataType":"double"},{"name":"TR_EXTENDED_AMOUNT","dataType":"double"},{"name":"TR_EXTENDED_COST","dataType":"double"},{"name":"TR_EXTENDED_ADD_BACK_COST","dataType":"double"},{"name":"TR_TAX_AMOUNT","dataType":"double"},{"name":"TR_DISCOUNT_AMOUNT","dataType":"double"},{"name":"PRICE_LIST","dataType":"string"},{"name":"UNIT_SELLING_PRICE","dataType":"double"},{"name":"ITEM_UNIT_COST","dataType":"double"},{"name":"ITEM_ADD_BACK_UNIT_COST","dataType":"double"},{"name":"ITEM_MATERIAL_COST","dataType":"double"},{"name":"ITEM_LABOR_COST","dataType":"double"},{"name":"ITEM_MATERIAL_OVERHEAD","dataType":"double"},{"name":"ITEM_LABOR_OVERHEAD","dataType":"double"},{"name":"ITEM_OUT_PROC_COST","dataType":"double"},{"name":"UNIT_LIST_PRICE","dataType":"double"},{"name":"EXTENDED_AMOUNT","dataType":"double"},{"name":"EXTENDED_COST","dataType":"double"},{"name":"EXTENDED_ADD_BACK_COST","dataType":"double"},{"name":"GROSS_MARGIN_PCT","dataType":"double"},{"name":"TAX_AMOUNT","dataType":"double"},{"name":"TAX_CODE","dataType":"string"},{"name":"DISCOUNT_PERCENT","dataType":"double"},{"name":"DISCOUNT_AMOUNT","dataType":"double"},{"name":"APPLICATION_CODE_DESC","dataType":"string"},{"name":"APPLICATION_CODE","dataType":"string"},{"name":"MARKET_SEGMENT","dataType":"string"},{"name":"REQUEST_SHIP_DATE","dataType":"dateTime"},{"name":"PROMISE_SHIP_DATE","dataType":"dateTime"},{"name":"SCHEDULE_SHIP_DATE","dataType":"dateTime"},{"name":"ACTUAL_SHIPMENT_DATE","dataType":"date"},{"name":"AGREEMENT_NUMBER","dataType":"string"},{"name":"ITEM_TYPE_CODE","dataType":"string"},{"name":"PAYMENT_TYPE","dataType":"string"},{"name":"CREDIT_CARD_CODE","dataType":"string"},{"name":"CREDIT_CARD_NUMBER","dataType":"string"},{"name":"CREDIT_CARD_HOLDER_NAME","dataType":"string"},{"name":"CREDIT_CARD_EXPIRATION_DATE","dataType":"dateTime"},{"name":"CREDIT_CARD_APPROVAL_CODE","dataType":"string"},{"name":"BILL_TO_NAME","dataType":"string"},{"name":"BILL_TO_COUNTRY","dataType":"string"},{"name":"BILL_TO_ADDRESS1","dataType":"string"},{"name":"BILL_TO_ADDRESS2","dataType":"string"},{"name":"BILL_TO_ADDRESS3","dataType":"string"},{"name":"BILL_TO_ADDRESS4","dataType":"string"},{"name":"BILL_TO_CITY","dataType":"string"},{"name":"BILL_TO_STATE","dataType":"string"},{"name":"BILL_TO_POSTAL_CODE","dataType":"string"},{"name":"BILL_TO_COUNTY","dataType":"string"},{"name":"BILL_TO_PROVINCE","dataType":"string"},{"name":"BILL_TO_SITE","dataType":"string"},{"name":"BILL_TO_CONTACT","dataType":"string"},{"name":"SHIP_TO_CONTACT","dataType":"string"},{"name":"SHIP_TO_SITE","dataType":"string"},{"name":"SHIP_TO_COUNTY","dataType":"string"},{"name":"SHIP_TO_PROVINCE","dataType":"string"},{"name":"SHIP_TO_NAME","dataType":"string"},{"name":"SHIP_TO_COUNTRY","dataType":"string"},{"name":"SHIP_TO_ADDRESS1","dataType":"string"},{"name":"SHIP_TO_ADDRESS2","dataType":"string"},{"name":"SHIP_TO_ADDRESS3","dataType":"string"},{"name":"SHIP_TO_ADDRESS4","dataType":"string"},{"name":"SHIP_TO_CITY","dataType":"string"},{"name":"SHIP_TO_STATE","dataType":"string"},{"name":"SHIP_TO_POSTAL_CODE","dataType":"string"},{"name":"END_USER","dataType":"string"},{"name":"END_USER_NUMBER","dataType":"string"},{"name":"END_USER_CONTACT","dataType":"string"},{"name":"END_USER_ADDRESS1","dataType":"string"},{"name":"END_USER_ADDRESS2","dataType":"string"},{"name":"END_USER_ADDRESS3","dataType":"string"},{"name":"END_USER_CITY","dataType":"string"},{"name":"END_USER_STATE","dataType":"string"},{"name":"END_USER_POSTAL_CODE","dataType":"string"},{"name":"END_USER_COUNTY","dataType":"string"},{"name":"END_USER_PROVINCE","dataType":"string"},{"name":"END_USER_COUNTRY_NAME","dataType":"string"},{"name":"SALESPERSON","dataType":"string"},{"name":"MAJOR_GEOGRAPHICAL_AREA","dataType":"string"},{"name":"GL_CLASS","dataType":"string"},{"name":"PARTY_NUMBER","dataType":"string"},{"name":"CUSTOMER_CLASS","dataType":"string"},{"name":"CUSTOMER_CATEGORY","dataType":"string"},{"name":"CUSTOMER_TYPE","dataType":"string"},{"name":"TAX_REGISTRATION_NUMBER","dataType":"string"},{"name":"FREIGHT_TERM","dataType":"string"},{"name":"FOB","dataType":"string"},{"name":"FISCAL_WEEK_GL_DATE","dataType":"double"},{"name":"FISCAL_PERIOD_GL_DATE","dataType":"double"},{"name":"FISCAL_QUARTER_GL_DATE","dataType":"double"},{"name":"FISCAL_YEAR_GL_DATE","dataType":"double"},{"name":"LEGAL_ENTITY_ID","dataType":"double"},{"name":"LEGAL_ENTITY","dataType":"string"},{"name":"OPERATING_UNIT_ID","dataType":"double"},{"name":"OPERATING_UNIT","dataType":"string"},{"name":"TRANSACTION_CURRENCY","dataType":"string"},{"name":"TRX_TO_USD_RATE","dataType":"double"},{"name":"TRX_TO_FUNC_RATE","dataType":"double"},{"name":"COST_TO_FUNC_RATE","dataType":"double"},{"name":"COST_TO_USD_RATE","dataType":"double"},{"name":"TERR_AREA","dataType":"string"},{"name":"TERR_OFFICE","dataType":"string"},{"name":"TERR_SALES_MGR_TERR_NUM","dataType":"string"},{"name":"TERR_TYPE","dataType":"string"},{"name":"TERR_NUM","dataType":"string"},{"name":"UNIT_SELLING_PRICE_USD","dataType":"double"},{"name":"UNIT_LIST_PRICE_USD","dataType":"double"},{"name":"ITEM_UNIT_COST_USD","dataType":"double"},{"name":"ITEM_ADD_BACK_UNIT_COST_USD","dataType":"double"},{"name":"ITEM_MATERIAL_COST_USD","dataType":"double"},{"name":"ITEM_LABOR_COST_USD","dataType":"double"},{"name":"ITEM_MATERIAL_OVERHEAD_USD","dataType":"double"},{"name":"ITEM_LABOR_OVERHEAD_USD","dataType":"double"},{"name":"ITEM_OUT_PROC_COST_USD","dataType":"double"},{"name":"EXTENDED_AMOUNT_USD","dataType":"double"},{"name":"EXTENDED_COST_USD","dataType":"double"},{"name":"EXTENDED_ADD_BACK_COST_USD","dataType":"double"},{"name":"DISCOUNT_AMOUNT_USD","dataType":"double"},{"name":"TAX_AMOUNT_USD","dataType":"double"},{"name":"G_TR_ITEM_UNIT_COST","dataType":"double"},{"name":"G_TR_ITEM_MATERIAL_COST","dataType":"double"},{"name":"G_TR_ITEM_LABOR_COST","dataType":"double"},{"name":"G_TR_ITEM_MATERIAL_OVERHEAD","dataType":"double"},{"name":"G_TR_ITEM_LABOR_OVERHEAD","dataType":"double"},{"name":"G_TR_ITEM_OUT_PROC_COST","dataType":"double"},{"name":"G_TR_EXTENDED_COST","dataType":"double"},{"name":"G_ITEM_UNIT_COST","dataType":"double"},{"name":"G_ITEM_MATERIAL_COST","dataType":"double"},{"name":"G_ITEM_LABOR_COST","dataType":"double"},{"name":"G_ITEM_MATERIAL_OVERHEAD","dataType":"double"},{"name":"G_ITEM_LABOR_OVERHEAD","dataType":"double"},{"name":"G_ITEM_OUT_PROC_COST","dataType":"double"},{"name":"G_EXTENDED_COST","dataType":"double"},{"name":"G_GROSS_MARGIN_PCT","dataType":"double"},{"name":"G_ITEM_UNIT_COST_USD","dataType":"double"},{"name":"G_ITEM_MATERIAL_COST_USD","dataType":"double"},{"name":"G_ITEM_LABOR_COST_USD","dataType":"double"},{"name":"G_ITEM_MATERIAL_OVERHEAD_USD","dataType":"double"},{"name":"G_ITEM_LABOR_OVERHEAD_USD","dataType":"double"},{"name":"G_ITEM_OUT_PROC_COST_USD","dataType":"double"},{"name":"G_EXTENDED_COST_USD","dataType":"double"},{"name":"F_TR_ITEM_UNIT_COST","dataType":"double"},{"name":"F_TR_ITEM_MATERIAL_COST","dataType":"double"},{"name":"F_TR_ITEM_LABOR_COST","dataType":"double"},{"name":"F_TR_ITEM_MATERIAL_OVERHEAD","dataType":"double"},{"name":"F_TR_ITEM_LABOR_OVERHEAD","dataType":"double"},{"name":"F_TR_ITEM_OUT_PROC_COST","dataType":"double"},{"name":"F_TR_EXTENDED_COST","dataType":"double"},{"name":"F_ITEM_UNIT_COST","dataType":"double"},{"name":"F_ITEM_MATERIAL_COST","dataType":"double"},{"name":"F_ITEM_LABOR_COST","dataType":"double"},{"name":"F_ITEM_MATERIAL_OVERHEAD","dataType":"double"},{"name":"F_ITEM_LABOR_OVERHEAD","dataType":"double"},{"name":"F_ITEM_OUT_PROC_COST","dataType":"double"},{"name":"F_EXTENDED_COST","dataType":"double"},{"name":"F_GROSS_MARGIN_PCT","dataType":"double"},{"name":"F_ITEM_UNIT_COST_USD","dataType":"double"},{"name":"F_ITEM_MATERIAL_COST_USD","dataType":"double"},{"name":"F_ITEM_LABOR_COST_USD","dataType":"double"},{"name":"F_ITEM_MATERIAL_OVERHEAD_USD","dataType":"double"},{"name":"F_ITEM_LABOR_OVERHEAD_USD","dataType":"double"},{"name":"F_ITEM_OUT_PROC_COST_USD","dataType":"double"},{"name":"F_EXTENDED_COST_USD","dataType":"double"},{"name":"OVERWRITE_CURRENCY_CI","dataType":"string"},{"name":"OVERWRITE_UNIT_PRICE_CI","dataType":"double"},{"name":"OVERWRITE_EXT_PRICE_CI","dataType":"double"},{"name":"END_CUST_USD_RATE","dataType":"double"},{"name":"OVERWRITE_UNIT_PRICE_CI_USD","dataType":"double"},{"name":"OVERWRITE_EXT_PRICE_CI_USD","dataType":"double"},{"name":"M20_REPORTING_ENTITY","dataType":"string"},{"name":"REPEAT_BUSINESS","dataType":"string"},{"name":"FLASH_OFFICE","dataType":"string"},{"name":"PLANNER_CODE","dataType":"string"},{"name":"END_ASSEMBLY_PEGGING","dataType":"string"},{"name":"PAYMENT_TERM","dataType":"string"},{"name":"TIMESTAMP","dataType":"date"},{"name":"REC_ENTITY","dataType":"string"},{"name":"REC_DEPT","dataType":"string"},{"name":"REC_ACCOUNT","dataType":"string"},{"name":"REC_PROJECT","dataType":"string"},{"name":"REC_INTERCO","dataType":"string"},{"name":"REC_TBD","dataType":"string"},{"name":"EXTERNAL_ORDER_NUMBER","dataType":"string"},{"name":"INTERCO_PO_NUM","dataType":"string"},{"name":"SO_LINE_ID","dataType":"double"},{"name":"SO_HEADER_ID","dataType":"double"},{"name":"CUSTOMER_TRX_ID","dataType":"double"},{"name":"CUSTOMER_TRX_LINE_ID","dataType":"double"},{"name":"CST_CURRENCY_CODE","dataType":"string"},{"name":"PROJECT_ID","dataType":"double"},{"name":"PROJECT_NAME","dataType":"string"},{"name":"PROJECT_NUMBER","dataType":"string"},{"name":"SPL_COGS_FLAG","dataType":"string"},{"name":"COGS_ACCOUNT","dataType":"string"},{"name":"IMPORTER_NAME","dataType":"string"},{"name":"IMPORTER_NUMBER","dataType":"string"},{"name":"IMPORTER_ADDRESS1","dataType":"string"},{"name":"IMPORTER_ADDRESS2","dataType":"string"},{"name":"IMPORTER_CITY","dataType":"string"},{"name":"IMPORTER_STATE","dataType":"string"},{"name":"IMPORTER_POSTAL_CODE","dataType":"string"},{"name":"IMPORTER_COUNTY","dataType":"string"},{"name":"IMPORTER_PROVINCE","dataType":"string"},{"name":"IMPORTER_COUNTRY_NAME","dataType":"string"},{"name":"BILL_TO_ADDRESS_ID","dataType":"double"},{"name":"SHIP_TO_ADDRESS_ID","dataType":"double"},{"name":"IMPORTER_ADDRESS_ID","dataType":"string"},{"name":"END_USER_ADDRESS_ID","dataType":"string"},{"name":"LAST_UPDATE_DATE","dataType":"date"},{"name":"SITE","dataType":"string"},{"name":"FIN_PRODUCT_GROUP","dataType":"string"},{"name":"FIN_PRODUCT_FAMILY","dataType":"string"},{"name":"FIN_FORECAST_FIELD","dataType":"string"},{"name":"FIN_MGMT_MARKET","dataType":"string"},{"name":"FIN_CORP_MARKET","dataType":"string"},{"name":"FIN_ACCOUNT","dataType":"string"},{"name":"FIN_UNIT_ACCOUNT","dataType":"string"},{"name":"FIN_UNIT","dataType":"double"},{"name":"BILLING_SOURCE","dataType":"string"},{"name":"CONTRACT_NUMBER","dataType":"string"},{"name":"CONTRACT_NUMBER_MODIFIER","dataType":"string"},{"name":"CLE_ID","dataType":"string"},{"name":"PERIOD_NAME","dataType":"string"},{"name":"PERIOD_START_DATE","dataType":"dateTime"},{"name":"PERIOD_END_DATE","dataType":"dateTime"},{"name":"DIST_ID","dataType":"double"},{"name":"ROW_CREATION_DATE","dataType":"dateTime"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-17T03:09:48.3230035+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/ec19509b-a36a-47a9-8e62-7b789f57b7ea/XXCOH_BILLING_VIEW.csv?snapshot=2022-05-17T03%3A09%3A48.2888942Z"}]},{"$type":"LocalEntity","name":"XXCOH_INSTALL_BASE_VIEW","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"XXCOH_INSTALL_BASE_VIEW.csv"},"attributes":[{"name":"INSTANCE_ID","dataType":"double"},{"name":"INSTANCE_NUMBER","dataType":"string"},{"name":"ITEM_NUMBER","dataType":"string"},{"name":"ITEM_DESCRIPTION","dataType":"string"},{"name":"SERIAL_NUMBER","dataType":"string"},{"name":"PROD_TBU","dataType":"string"},{"name":"PROD_FAMILY","dataType":"string"},{"name":"PROD_LINE","dataType":"string"},{"name":"PROD_FORECAST_FIELD","dataType":"string"},{"name":"COMMODITY","dataType":"string"},{"name":"TOP_PARENT_ID","dataType":"double"},{"name":"TOP_PARENT_INV_ITEM_ID","dataType":"double"},{"name":"TOP_PARENT_ITEM_NUMBER","dataType":"string"},{"name":"TOP_PARENT_ITEM_DESCRIPTION","dataType":"string"},{"name":"TOP_PARENT_SERIAL_NUMBER","dataType":"string"},{"name":"PARENT_ID","dataType":"double"},{"name":"PARENT_INV_ITEM_ID","dataType":"double"},{"name":"PARENT_ITEM_NUMBER","dataType":"string"},{"name":"PARENT_ITEM_DESCRIPTION","dataType":"string"},{"name":"PARENT_SERIAL_NUMBER","dataType":"string"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"LAST_VLD_ORGANIZATION_ID","dataType":"double"},{"name":"INSTALL_DATE","dataType":"date"},{"name":"ORIGINAL_INSTALL_DATE","dataType":"date"},{"name":"LOT_NUMBER","dataType":"string"},{"name":"QUANTITY","dataType":"double"},{"name":"ACTIVE_START_DATE","dataType":"date"},{"name":"ACTIVE_END_DATE","dataType":"dateTime"},{"name":"EXTERNAL_REFERENCE","dataType":"string"},{"name":"INSTANCE_USAGE_CODE","dataType":"string"},{"name":"INSTANCE_STATUS","dataType":"string"},{"name":"INSTANCE_STATUS_ID","dataType":"double"},{"name":"INSTANCE_TYPE_CODE","dataType":"string"},{"name":"ORDER_LINE_ID","dataType":"double"},{"name":"OWNER_PARTY","dataType":"string"},{"name":"OWNER_PARTY_ID","dataType":"double"},{"name":"OWNER_PARTY_ACCOUNT_ID","dataType":"double"},{"name":"LOCATION_TYPE_CODE","dataType":"string"},{"name":"CURRENT_LOCATION","dataType":"string"},{"name":"LOCATION_ID","dataType":"double"},{"name":"INSTALL_LOCATION_TYPE_CODE","dataType":"string"},{"name":"ORDER_NUMBER","dataType":"double"},{"name":"CUST_PO_NUMBER","dataType":"string"},{"name":"LINE_NUMBER","dataType":"double"},{"name":"LINK_TO_LINE_ID","dataType":"double"},{"name":"ORDER_HEADER_ID","dataType":"double"},{"name":"ORDERED_DATE","dataType":"date"},{"name":"SHIPPED_ON_DATE","dataType":"date"},{"name":"ACTUAL_RETURN_DATE","dataType":"date"},{"name":"INSTALLED_PARTY","dataType":"string"},{"name":"INSTALLED_PARTY_NUMBER","dataType":"string"},{"name":"INSTALLED_PARTY_CLEAN","dataType":"string"},{"name":"INSTALLED_ADDRESS1","dataType":"string"},{"name":"INSTALLED_ADDRESS2","dataType":"string"},{"name":"INSTALLED_COUNTRY","dataType":"string"},{"name":"INSTALLED_PARTY_ID","dataType":"double"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-17T03:04:46.0623357+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/ec19509b-a36a-47a9-8e62-7b789f57b7ea/XXCOH_INSTALL_BASE_VIEW.csv?snapshot=2022-05-17T03%3A04%3A45.9736260Z"}]},{"$type":"LocalEntity","name":"XXCOH_MS_SHIPMENT_VIEW","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"XXCOH_MS_SHIPMENT_VIEW.csv"},"attributes":[{"name":"ASOF_DATE","dataType":"dateTime"},{"name":"ASOF_DATE_DISP","dataType":"dateTime"},{"name":"SYSTEM_DATE","dataType":"dateTime"},{"name":"ENTER_DATE","dataType":"dateTime"},{"name":"BOOKED_DATE","dataType":"dateTime"},{"name":"ORDER_NUMBER","dataType":"double"},{"name":"ORDER_LINE","dataType":"string"},{"name":"ORDER_TYPE","dataType":"string"},{"name":"SO_LINE_TYPE","dataType":"string"},{"name":"LINE_STATUS","dataType":"string"},{"name":"BILLABLE_FLAG","dataType":"string"},{"name":"SALES_CHANNEL","dataType":"string"},{"name":"AGREEMENT_NUMBER","dataType":"string"},{"name":"ITEM_TYPE_CODE","dataType":"string"},{"name":"ACTUAL_SHIPMENT_DATE","dataType":"date"},{"name":"REGIONAL_LOCATION","dataType":"string"},{"name":"REPORTING_ENTITY","dataType":"string"},{"name":"ASP_FLAG","dataType":"string"},{"name":"INV_FLAG","dataType":"string"},{"name":"LINE_CATEGORY_CODE","dataType":"string"},{"name":"LINE_SOURCE_TYPE_CODE","dataType":"string"},{"name":"CUSTOMER_PO","dataType":"string"},{"name":"CREATED_BY","dataType":"string"},{"name":"ITEM_NUMBER","dataType":"string"},{"name":"ITEM_DESCRIPTION","dataType":"string"},{"name":"PRODUCT_LINE","dataType":"string"},{"name":"PRODUCT_FAMILY","dataType":"string"},{"name":"TECHNICAL_BUSINESS_UNIT","dataType":"string"},{"name":"REV_ENTITY","dataType":"string"},{"name":"REVENUE_ACCOUNT","dataType":"string"},{"name":"FORECAST_FIELD","dataType":"string"},{"name":"COMMODITY","dataType":"string"},{"name":"ORG_PRODUCT_LINE","dataType":"string"},{"name":"ORG_PRODUCT_FAMILY","dataType":"string"},{"name":"ORG_TECHNICAL_BUSINESS_UNIT","dataType":"string"},{"name":"ORG_FORECAST_FIELD","dataType":"string"},{"name":"LEAD_TIME","dataType":"string"},{"name":"PRIMARY_ORG","dataType":"string"},{"name":"ITEM_CUSTOMER","dataType":"string"},{"name":"BCP_CODE","dataType":"string"},{"name":"ROYALTY","dataType":"string"},{"name":"WAREHOUSE","dataType":"string"},{"name":"SHIPPING_METHOD_CODE","dataType":"string"},{"name":"TR_UNIT_SELLING_PRICE","dataType":"double"},{"name":"TR_ITEM_UNIT_COST","dataType":"string"},{"name":"TR_ITEM_ADD_BACK_UNIT_COST","dataType":"string"},{"name":"TR_ITEM_MATERIAL_COST","dataType":"string"},{"name":"TR_ITEM_LABOR_COST","dataType":"string"},{"name":"TR_ITEM_MATERIAL_OVERHEAD","dataType":"string"},{"name":"TR_ITEM_LABOR_OVERHEAD","dataType":"string"},{"name":"TR_ITEM_OUT_PROC_COST","dataType":"string"},{"name":"TR_UNIT_LIST_PRICE","dataType":"double"},{"name":"TR_EXTENDED_AMOUNT","dataType":"double"},{"name":"TR_EXTENDED_COST","dataType":"double"},{"name":"TR_EXTENDED_ADD_BACK_COST","dataType":"double"},{"name":"GROSS_MARGIN_PCT","dataType":"double"},{"name":"DISCOUNT_PERCENT","dataType":"double"},{"name":"TR_DISCOUNT_AMOUNT","dataType":"double"},{"name":"PRICE_LIST","dataType":"string"},{"name":"UNIT_SELLING_PRICE","dataType":"double"},{"name":"ITEM_UNIT_COST","dataType":"double"},{"name":"ITEM_ADD_BACK_UNIT_COST","dataType":"double"},{"name":"ITEM_MATERIAL_COST","dataType":"double"},{"name":"ITEM_LABOR_COST","dataType":"double"},{"name":"ITEM_MATERIAL_OVERHEAD","dataType":"double"},{"name":"ITEM_LABOR_OVERHEAD","dataType":"double"},{"name":"ITEM_OUT_PROC_COST","dataType":"double"},{"name":"UNIT_LIST_PRICE","dataType":"double"},{"name":"EXTENDED_AMOUNT","dataType":"double"},{"name":"EXTENDED_COST","dataType":"double"},{"name":"EXTENDED_ADD_BACK_COST","dataType":"double"},{"name":"DISCOUNT_AMOUNT","dataType":"double"},{"name":"APPLICATION_CODE","dataType":"string"},{"name":"APPLICATION_CODE_DESC","dataType":"string"},{"name":"MARKET_SEGMENT","dataType":"string"},{"name":"REQUEST_SHIP_DATE","dataType":"dateTime"},{"name":"PROMISE_SHIP_DATE","dataType":"dateTime"},{"name":"SCHEDULE_SHIP_DATE","dataType":"dateTime"},{"name":"CUSTOMER_NAME","dataType":"string"},{"name":"CUSTOMER_ALTERNATE_NAME","dataType":"string"},{"name":"CUSTOMER_NUMBER","dataType":"string"},{"name":"CUSTOMER_NAME_REPORTING","dataType":"string"},{"name":"TAX_REGISTRATION_NUMBER","dataType":"string"},{"name":"PARTY_NUMBER","dataType":"string"},{"name":"PAYMENT_TYPE","dataType":"string"},{"name":"CREDIT_CARD_CODE","dataType":"string"},{"name":"CREDIT_CARD_NUMBER","dataType":"string"},{"name":"CREDIT_CARD_HOLDER_NAME","dataType":"string"},{"name":"CREDIT_CARD_EXPIRATION_DATE","dataType":"dateTime"},{"name":"CREDIT_CARD_APPROVAL_CODE","dataType":"string"},{"name":"BILL_TO_NAME","dataType":"string"},{"name":"BILL_TO_COUNTRY","dataType":"string"},{"name":"BILL_TO_ADDRESS1","dataType":"string"},{"name":"BILL_TO_ADDRESS2","dataType":"string"},{"name":"BILL_TO_ADDRESS3","dataType":"string"},{"name":"BILL_TO_ADDRESS4","dataType":"string"},{"name":"BILL_TO_CITY","dataType":"string"},{"name":"BILL_TO_STATE","dataType":"string"},{"name":"BILL_TO_POSTAL_CODE","dataType":"string"},{"name":"BILL_TO_COUNTY","dataType":"string"},{"name":"BILL_TO_PROVINCE","dataType":"string"},{"name":"BILL_TO_SITE","dataType":"string"},{"name":"SHIP_TO_NAME","dataType":"string"},{"name":"SHIP_TO_COUNTRY","dataType":"string"},{"name":"SHIP_TO_ADDRESS1","dataType":"string"},{"name":"SHIP_TO_ADDRESS2","dataType":"string"},{"name":"SHIP_TO_ADDRESS3","dataType":"string"},{"name":"SHIP_TO_ADDRESS4","dataType":"string"},{"name":"SHIP_TO_CITY","dataType":"string"},{"name":"SHIP_TO_STATE","dataType":"string"},{"name":"SHIP_TO_POSTAL_CODE","dataType":"string"},{"name":"SHIP_TO_COUNTY","dataType":"string"},{"name":"SHIP_TO_PROVINCE","dataType":"string"},{"name":"SHIP_TO_SITE","dataType":"string"},{"name":"SHIP_TO_CONTACT","dataType":"string"},{"name":"END_USER","dataType":"string"},{"name":"END_USER_NUMBER","dataType":"string"},{"name":"END_USER_CONTACT","dataType":"string"},{"name":"END_USER_ADDRESS1","dataType":"string"},{"name":"END_USER_ADDRESS2","dataType":"string"},{"name":"END_USER_ADDRESS3","dataType":"string"},{"name":"END_USER_CITY","dataType":"string"},{"name":"END_USER_STATE","dataType":"string"},{"name":"END_USER_COUNTY","dataType":"string"},{"name":"END_USER_PROVINCE","dataType":"string"},{"name":"END_USER_POSTAL_CODE","dataType":"string"},{"name":"END_USER_COUNTRY_NAME","dataType":"string"},{"name":"SALESPERSON","dataType":"string"},{"name":"MAJOR_GEOGRAPHICAL_AREA","dataType":"string"},{"name":"GL_CLASS","dataType":"string"},{"name":"CUSTOMER_CLASS","dataType":"string"},{"name":"CUSTOMER_CATEGORY","dataType":"string"},{"name":"CUSTOMER_TYPE","dataType":"string"},{"name":"FREIGHT_TERM","dataType":"string"},{"name":"FOB","dataType":"string"},{"name":"FISCAL_WEEK_SHIPPED","dataType":"double"},{"name":"FISCAL_PERIOD_SHIPPED","dataType":"double"},{"name":"FISCAL_QUARTER_SHIPPED","dataType":"double"},{"name":"FISCAL_YEAR_SHIPPED","dataType":"double"},{"name":"LEGAL_ENTITY_ID","dataType":"double"},{"name":"LEGAL_ENTITY","dataType":"string"},{"name":"OPERATING_UNIT_ID","dataType":"double"},{"name":"OPERATING_UNIT","dataType":"string"},{"name":"TRANSACTION_CURRENCY","dataType":"string"},{"name":"FUNCTIONAL_CURRENCY","dataType":"string"},{"name":"TRX_TO_USD_RATE","dataType":"double"},{"name":"TRX_TO_FUNC_RATE","dataType":"double"},{"name":"COST_TO_FUNC_RATE","dataType":"double"},{"name":"COST_TO_USD_RATE","dataType":"double"},{"name":"UNIT_SELLING_PRICE_USD","dataType":"double"},{"name":"UNIT_LIST_PRICE_USD","dataType":"double"},{"name":"ITEM_UNIT_COST_USD","dataType":"double"},{"name":"ITEM_ADD_BACK_UNIT_COST_USD","dataType":"double"},{"name":"ITEM_MATERIAL_COST_USD","dataType":"double"},{"name":"ITEM_LABOR_COST_USD","dataType":"double"},{"name":"ITEM_MATERIAL_OVERHEAD_USD","dataType":"double"},{"name":"ITEM_LABOR_OVERHEAD_USD","dataType":"double"},{"name":"ITEM_OUT_PROC_COST_USD","dataType":"double"},{"name":"EXTENDED_AMOUNT_USD","dataType":"double"},{"name":"EXTENDED_COST_USD","dataType":"double"},{"name":"EXTENDED_ADD_BACK_COST_USD","dataType":"double"},{"name":"DISCOUNT_AMOUNT_USD","dataType":"double"},{"name":"TERR_AREA","dataType":"string"},{"name":"TERR_OFFICE","dataType":"string"},{"name":"TERR_SALES_MGR_TERR_NUM","dataType":"string"},{"name":"TERR_TYPE","dataType":"string"},{"name":"TERR_NUM","dataType":"string"},{"name":"ORDER_STATUS","dataType":"string"},{"name":"OE_LINE_NUMBER","dataType":"string"},{"name":"DELIVERY_NAME","dataType":"string"},{"name":"DELIVERY_SHIPPING_STATUS_CODE","dataType":"string"},{"name":"DELIVERY_CONFIRM_DATE","dataType":"dateTime"},{"name":"ITEM_REVISION","dataType":"string"},{"name":"SHIP_SET_ID","dataType":"double"},{"name":"ARRIVAL_SET_ID","dataType":"double"},{"name":"SHIP_MODEL_COMPLETE_FLAG","dataType":"string"},{"name":"TRACKING_NUMBER","dataType":"string"},{"name":"COUNTRY_OF_ORIGIN","dataType":"string"},{"name":"CLASSIFICATION","dataType":"string"},{"name":"SHIP_FROM_LOCATION_CODE","dataType":"string"},{"name":"ULTIMATE_SHIP_TO","dataType":"string"},{"name":"SHIP_FROM_ORG_CODE","dataType":"string"},{"name":"SUBINVENTORY","dataType":"string"},{"name":"LOT_NUMBER","dataType":"string"},{"name":"SERIAL_NUMBER","dataType":"string"},{"name":"TO_SERIAL_NUMBER","dataType":"string"},{"name":"LEAST_NUM_OF_SERIAL_NUMBER","dataType":"double"},{"name":"CUST_REQUESTED_QUANTITY","dataType":"double"},{"name":"CUST_REQUESTED_QUANTITY_UOM","dataType":"string"},{"name":"PICKED_QUANTITY","dataType":"double"},{"name":"SHIPPED_QUANTITY","dataType":"double"},{"name":"DELIVERED_QUANTITY","dataType":"double"},{"name":"RECEIVED_QUANTITY","dataType":"double"},{"name":"CANCELLED_QUANTITY","dataType":"double"},{"name":"SHIPPING_QUANTITY","dataType":"double"},{"name":"SHIPPING_QUANTITY_UOM","dataType":"string"},{"name":"PICK_RELEASE_STATUS_CODE","dataType":"string"},{"name":"PICK_RELEASE_STATUS","dataType":"string"},{"name":"DATE_REQUESTED","dataType":"dateTime"},{"name":"DATE_SCHEDULED","dataType":"dateTime"},{"name":"OE_INTERFACED_FLAG","dataType":"string"},{"name":"SHIP_METHOD_CODE","dataType":"string"},{"name":"FREIGHT_TERMS_CODE","dataType":"string"},{"name":"SHIPMENT_PRIORITY_CODE","dataType":"string"},{"name":"SHIPPING_INSTRUCTIONS","dataType":"string"},{"name":"PACKING_INSTRUCTIONS","dataType":"string"},{"name":"CONSIGNEE","dataType":"string"},{"name":"WAYBILL","dataType":"string"},{"name":"GROSS_WEIGHT","dataType":"double"},{"name":"NET_WEIGHT","dataType":"double"},{"name":"WEIGHT_UOM_CODE","dataType":"string"},{"name":"VOLUME","dataType":"double"},{"name":"VOLUME_UOM_CODE","dataType":"string"},{"name":"CARRIER_NAME","dataType":"string"},{"name":"NO_OF_PIECES","dataType":"string"},{"name":"UOM_OF_PIECES","dataType":"string"},{"name":"MOVE_ORDER_NUMBER","dataType":"string"},{"name":"MOVE_ORDER_LINE_NUMBER","dataType":"double"},{"name":"FREIGHT_CHARGE","dataType":"double"},{"name":"FREIGHT_CHARGE_USD","dataType":"double"},{"name":"FREIGHT_CURRENCY_CODE","dataType":"string"},{"name":"SHIP_FROM_DATE","dataType":"dateTime"},{"name":"SHIP_TO_DATE","dataType":"dateTime"},{"name":"OVERWRITE_CURRENCY_CI","dataType":"string"},{"name":"OVERWRITE_UNIT_PRICE_CI","dataType":"double"},{"name":"OVERWRITE_EXT_PRICE_CI","dataType":"double"},{"name":"END_CUST_USD_RATE","dataType":"double"},{"name":"OVERWRITE_UNIT_PRICE_CI_USD","dataType":"double"},{"name":"OVERWRITE_EXT_PRICE_CI_USD","dataType":"double"},{"name":"REPEAT_BUSINESS","dataType":"string"},{"name":"M20_REPORTING_ENTITY","dataType":"string"},{"name":"FLASH_OFFICE","dataType":"string"},{"name":"PLANNER_CODE","dataType":"string"},{"name":"END_ASSEMBLY_PEGGING","dataType":"string"},{"name":"FIRST_SCHEDULE_DATE","dataType":"date"},{"name":"EXTERNAL_ORDER_NUMBER","dataType":"string"},{"name":"INTERCO_PO_NUM","dataType":"string"},{"name":"LINE_ID","dataType":"double"},{"name":"HEADER_ID","dataType":"double"},{"name":"DELIVERY_DETAIL_ID","dataType":"double"},{"name":"CST_CURRENCY_CODE","dataType":"string"},{"name":"PROJECT_NUMBER","dataType":"string"},{"name":"PROJECT_ID","dataType":"double"},{"name":"PROJECT_NAME","dataType":"string"},{"name":"IMPORTER_NAME","dataType":"string"},{"name":"IMPORTER_NUMBER","dataType":"string"},{"name":"IMPORTER_ADDRESS1","dataType":"string"},{"name":"IMPORTER_ADDRESS2","dataType":"string"},{"name":"IMPORTER_CITY","dataType":"string"},{"name":"IMPORTER_STATE","dataType":"string"},{"name":"IMPORTER_COUNTY","dataType":"string"},{"name":"IMPORTER_POSTAL_CODE","dataType":"string"},{"name":"IMPORTER_PROVINCE","dataType":"string"},{"name":"IMPORTER_COUNTRY_NAME","dataType":"string"},{"name":"BILL_TO_ADDRESS_ID","dataType":"double"},{"name":"SHIP_TO_ADDRESS_ID","dataType":"double"},{"name":"END_USER_ADDRESS_ID","dataType":"double"},{"name":"IMPORTER_ADDRESS_ID","dataType":"double"},{"name":"DELIVERY_PACK_DIMENSIONS","dataType":"string"},{"name":"DELIVERY_TYPE","dataType":"string"},{"name":"SERVICE_LEVEL","dataType":"string"},{"name":"MODE_OF_TRANSPORT","dataType":"string"},{"name":"ACTUAL_SHIPPED_VS_PROMISED_SHIPPPED","dataType":"string"},{"name":"ACTUAL_SHIPPED_VS_REQUESTED_SHIPPED","dataType":"string"},{"name":"ROW_CREATION_DATE","dataType":"dateTime"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-17T03:08:25.0414333+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/ec19509b-a36a-47a9-8e62-7b789f57b7ea/XXCOH_MS_SHIPMENT_VIEW.csv?snapshot=2022-05-17T03%3A07%3A28.8655291Z"}]},{"$type":"LocalEntity","name":"XXCOH_BACKLOG_FLASH_CUR_PRD_V","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"XXCOH_BACKLOG_FLASH_CUR_PRD_V.csv"},"attributes":[{"name":"AGREEMENT_NUMBER","dataType":"string"},{"name":"APPLICATION_CODE","dataType":"string"},{"name":"APPLICATION_CODE_DESC","dataType":"string"},{"name":"ASP_QUANTITY","dataType":"double"},{"name":"ASOF_DATE","dataType":"date"},{"name":"BACKLOG_QUANTITY","dataType":"double"},{"name":"BOOKED_DATE","dataType":"dateTime"},{"name":"BUSINESS_SEGMENT","dataType":"string"},{"name":"COMMODITY","dataType":"string"},{"name":"COMMODITY_GROUP","dataType":"string"},{"name":"CONVERSION_FLAG","dataType":"string"},{"name":"CREATED_BY","dataType":"string"},{"name":"CUSTOMER_NAME","dataType":"string"},{"name":"CUSTOMER_NAME_REPORTING","dataType":"string"},{"name":"CUSTOMER_NUMBER","dataType":"string"},{"name":"CUSTOMER_MASTER","dataType":"string"},{"name":"CUSTOMER_PO","dataType":"string"},{"name":"DATE_CREATED","dataType":"dateTime"},{"name":"DPAS","dataType":"string"},{"name":"EXTENDED_AMOUNT","dataType":"double"},{"name":"EXTENDED_AMOUNT_USD","dataType":"double"},{"name":"EXTENDED_COST_USD","dataType":"double"},{"name":"FIN_BACKLOG_ROLLUP","dataType":"string"},{"name":"FIN_BACKLOG_STATUS","dataType":"string"},{"name":"FIN_CORP_MARKET","dataType":"string"},{"name":"FIN_ENTITY","dataType":"string"},{"name":"FIN_FORECAST_FIELD","dataType":"string"},{"name":"FIN_MGMT_MARKET","dataType":"string"},{"name":"FIN_PRODUCT_GROUP","dataType":"string"},{"name":"FIN_PRODUCT_FAMILY","dataType":"string"},{"name":"FIN_SITE","dataType":"string"},{"name":"FIN_UNIT","dataType":"double"},{"name":"FISCAL_PERIOD","dataType":"double"},{"name":"FISCAL_PERIOD_NAME","dataType":"string"},{"name":"FOB","dataType":"string"},{"name":"FORECAST_FIELD","dataType":"string"},{"name":"FREIGHT_TERM","dataType":"string"},{"name":"FISCAL_QTR","dataType":"double"},{"name":"FY_QTR","dataType":"string"},{"name":"HOLD_STATUS","dataType":"string"},{"name":"HOLD_REASON","dataType":"string"},{"name":"IMPORTER_OF_RECORD","dataType":"string"},{"name":"ITEM_DESCRIPTION","dataType":"string"},{"name":"ITEM_NUMBER","dataType":"string"},{"name":"ITEM_UNIT_COST_USD","dataType":"double"},{"name":"MARKET_SEGMENT","dataType":"string"},{"name":"OPERATING_UNIT","dataType":"string"},{"name":"OPERATING_UNIT_ID","dataType":"double"},{"name":"ORDER_LINE","dataType":"string"},{"name":"ORDER_NUMBER","dataType":"double"},{"name":"ORDER_SOURCE","dataType":"string"},{"name":"ORG_FORECAST_FIELD","dataType":"string"},{"name":"ORG_PRODUCT_FAMILY","dataType":"string"},{"name":"ORG_TECHNICAL_BUSINESS_UNIT","dataType":"string"},{"name":"PRODUCT_FAMILY","dataType":"string"},{"name":"PAYMENT_TERM","dataType":"string"},{"name":"PROJECT_NUMBER","dataType":"string"},{"name":"PRODUCT_LINE","dataType":"string"},{"name":"PROMISE_SHIP_DATE","dataType":"dateTime"},{"name":"REGIONAL_LOCATION","dataType":"string"},{"name":"REPORTING_ENTITY","dataType":"string"},{"name":"REQUEST_SHIP_DATE","dataType":"dateTime"},{"name":"REVENUE_ACCOUNT","dataType":"string"},{"name":"SALES_CHANNEL","dataType":"string"},{"name":"SALESPERSON","dataType":"string"},{"name":"SCHEDULE_CATEGORY","dataType":"string"},{"name":"SCHEDULE_CATEGORY_PERIOD","dataType":"string"},{"name":"SCHEDULE_CATEGORY_PERIOD_NUMBER","dataType":"string"},{"name":"SCHEDULE_SHIP_DATE","dataType":"dateTime"},{"name":"SHIP_TO_CITY","dataType":"string"},{"name":"SHIP_TO_COUNTRY","dataType":"string"},{"name":"SHIP_TO_POSTAL_CODE","dataType":"string"},{"name":"SHIP_TO_PROVINCE","dataType":"string"},{"name":"SHIP_TO_STATE","dataType":"string"},{"name":"SO_LINE_TYPE","dataType":"string"},{"name":"SOURCE","dataType":"string"},{"name":"SUBINVENTORY","dataType":"string"},{"name":"TECHNICAL_BUSINESS_UNIT","dataType":"string"},{"name":"TR_EXTENDED_AMOUNT","dataType":"double"},{"name":"TRANSACTION_CURRENCY","dataType":"string"},{"name":"UNIT_LIST_PRICE_USD","dataType":"double"},{"name":"WAREHOUSE","dataType":"string"},{"name":"LEDGER_ID","dataType":"double"},{"name":"BCK_KEY","dataType":"string"}]}]}