{"name":"DF_ITEM_CATEGORY","description":"Tabellen von Snowflake","version":"1.0","culture":"en-US","modifiedTime":"2022-04-14T06:18:01.0005905+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":true,"queriesMetadata":{"no_use_XXCOH_IM_CATEGORY_VIEW":{"queryId":"ec32016b-5e03-4f4e-893c-b62152962f68","queryName":"no_use_XXCOH_IM_CATEGORY_VIEW","loadEnabled":true},"no_use_XXCOH_IM_ITEM_VIEW":{"queryId":"5ed6fc03-84f9-46c2-a582-8e152106b9dc","queryName":"no_use_XXCOH_IM_ITEM_VIEW","loadEnabled":true},"no_use_XXREP_MTL_ITEM_CATEGORIES_V":{"queryId":"aa5b1243-cc30-4640-a834-0dc6f58721bb","queryName":"no_use_XXREP_MTL_ITEM_CATEGORIES_V","loadEnabled":true},"no_use_XXREP_MTL_SYSTEM_ITEMS_NO_MAS_V":{"queryId":"9d772e65-7c3e-4f45-80d6-71c41080a0f8","queryName":"no_use_XXREP_MTL_SYSTEM_ITEMS_NO_MAS_V","loadEnabled":true},"no_use_XXREP_MTL_SYSTEM_ITEMS_V":{"queryId":"c5a044b2-cbae-4b46-8cea-040c87ff2d92","queryName":"no_use_XXREP_MTL_SYSTEM_ITEMS_V","loadEnabled":true},"XXREP_MFG_MTL_ITEM_ATTRIBUTES_V":{"queryId":"afb8a6b2-4a76-4849-a27d-bec4257545bc","queryName":"XXREP_MFG_MTL_ITEM_ATTRIBUTES_V","loadEnabled":true},"InvOrg_Code":{"queryId":"fd32bd7f-1b79-4059-9062-19dbfbfa8040","queryName":"InvOrg_Code"}},"document":"section Section1;\r\nshared no_use_XXCOH_IM_CATEGORY_VIEW = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  #\"Navigation 1\" = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 3\" = #\"Navigation 2\"{[Name = \"XXCOH_IM_CATEGORY_VIEW\", Kind = \"View\"]}[Data]\r\nin\r\n  #\"Navigation 3\";\r\nshared no_use_XXCOH_IM_ITEM_VIEW = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  #\"Navigation 1\" = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 3\" = #\"Navigation 2\"{[Name = \"XXCOH_IM_ITEM_VIEW\", Kind = \"View\"]}[Data]\r\nin\r\n  #\"Navigation 3\";\r\nshared no_use_XXREP_MTL_ITEM_CATEGORIES_V = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  #\"Navigation 1\" = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 3\" = #\"Navigation 2\"{[Name = \"XXREP_MTL_ITEM_CATEGORIES_V\", Kind = \"View\"]}[Data]\r\nin\r\n  #\"Navigation 3\";\r\nshared no_use_XXREP_MTL_SYSTEM_ITEMS_NO_MAS_V = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  #\"Navigation 1\" = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 3\" = #\"Navigation 2\"{[Name = \"XXREP_MTL_SYSTEM_ITEMS_NO_MAS_V\", Kind = \"View\"]}[Data]\r\nin\r\n  #\"Navigation 3\";\r\nshared no_use_XXREP_MTL_SYSTEM_ITEMS_V = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  #\"Navigation 1\" = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 3\" = #\"Navigation 2\"{[Name = \"XXREP_MTL_SYSTEM_ITEMS_V\", Kind = \"View\"]}[Data]\r\nin\r\n  #\"Navigation 3\";\r\nshared XXREP_MFG_MTL_ITEM_ATTRIBUTES_V = let\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\n  Navigation = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\n  #\"Navigation 1\" = Navigation{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"XXREP_MFG_MTL_ITEM_ATTRIBUTES_V\", Kind = \"View\"]}[Data],\n  #\"Filtered rows\" = Table.SelectRows(#\"Navigation 2\", each [ORGANIZATION_CODE] = InvOrg_Code)\nin\n  #\"Filtered rows\";\r\nshared InvOrg_Code = \"LDP\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type any];\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"no_use_XXCOH_IM_CATEGORY_VIEW","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"no_use_XXCOH_IM_CATEGORY_VIEW.csv"},"attributes":[{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"ORGANIZATION_ID","dataType":"double"},{"name":"ITEM_NUMBER","dataType":"string"},{"name":"DESCRIPTION","dataType":"string"},{"name":"ORGANIZATION_CODE","dataType":"string"},{"name":"ROW_UPDATED_BY","dataType":"string"},{"name":"ITEM_CREATION_DATE","dataType":"dateTime"},{"name":"ROW_CREATION_DATE","dataType":"dateTime"},{"name":"PF_ITEM_NUMBER","dataType":"string"},{"name":"ECCN_ECCN","dataType":"string"},{"name":"COO_COUNTRY_OF_ORIGIN","dataType":"string"},{"name":"HTS_HTS_SCHEDULE_B","dataType":"string"},{"name":"PLNG_GREEN_SUPPLY_STATUS","dataType":"string"},{"name":"PLNG_PLANNING_ACTION","dataType":"string"},{"name":"PLNG_FAMILY_UNIQUE","dataType":"string"},{"name":"ST_SALES_TAX_CATEGORY","dataType":"string"},{"name":"CDI_CARTON_GROUP","dataType":"string"},{"name":"CI_CARTON_GROUP","dataType":"string"},{"name":"PROD_TBU","dataType":"string"},{"name":"PROD_FAMILY","dataType":"string"},{"name":"PROD_LINE","dataType":"string"},{"name":"PROD_FORECAST_FIELD","dataType":"string"},{"name":"CON_CONTRACT_CATEGORY","dataType":"string"},{"name":"PTLX_PATLEX_PERCENT","dataType":"string"},{"name":"COMM_COMMODITY","dataType":"string"},{"name":"SLT_SERVICE_LEAD_TIME","dataType":"string"},{"name":"FF_FORECAST_FIELD","dataType":"string"},{"name":"CS_SUPPLY_SOURCE","dataType":"string"},{"name":"CS_DEMAND_SOURCE","dataType":"string"},{"name":"DBT_DB_TEMP","dataType":"string"},{"name":"BUP_BACKUP","dataType":"string"},{"name":"PO_PRIMARY_ORG","dataType":"string"},{"name":"PO_SUPPLY_CHAIN_PORG","dataType":"string"},{"name":"BCP_BCP","dataType":"string"},{"name":"CUST_CUSTOMER","dataType":"string"},{"name":"ROYLT_ROYALTY","dataType":"string"},{"name":"SC_SECURITY_CLASS","dataType":"string"},{"name":"GTD_GREEN_TRANSITION_DATE","dataType":"string"},{"name":"ROH_EU_ROHS_COMPLIANT","dataType":"string"},{"name":"ROH_CHINA_ROHS_COMPLIANT","dataType":"string"},{"name":"FDA_FDA_ACCESSION","dataType":"string"},{"name":"SCC_SEQUENCE","dataType":"string"},{"name":"SCC_COMMODITY","dataType":"string"},{"name":"SCC_UNSPSC","dataType":"string"},{"name":"OPROD_TBU","dataType":"string"},{"name":"OPROD_FAMILY","dataType":"string"},{"name":"OPROD_LINE","dataType":"string"},{"name":"OPROD_FORECAST_FIELD","dataType":"string"},{"name":"SR_OPERATING_UNIT","dataType":"string"},{"name":"SR_PERCENTAGE","dataType":"string"},{"name":"SR_VENDOR","dataType":"string"},{"name":"SR_VENDOR_SITE","dataType":"string"},{"name":"SI_INSTALL_WITH_SALE","dataType":"string"},{"name":"IT_ITEM_TYPE_CODE","dataType":"string"},{"name":"IT_ITEM_TYPE_MEANING","dataType":"string"},{"name":"OPSR_SEC_REPORTING","dataType":"string"},{"name":"OPSR_DEMAND_SOURCE","dataType":"string"},{"name":"SECR_SEC_REPORTING","dataType":"string"},{"name":"OPC_ORG","dataType":"string"},{"name":"OPC_PLANNING_CODE","dataType":"string"},{"name":"SP_SHIPMENT_PRIORITY","dataType":"string"},{"name":"FI_FISCAL_YEAR","dataType":"string"},{"name":"FI_SFDC_FORECAST_ITEM","dataType":"string"},{"name":"PG_ORG","dataType":"string"},{"name":"PG_PLANNING_GROUP","dataType":"string"},{"name":"WC_ORG","dataType":"string"},{"name":"WC_WORK_CELL","dataType":"string"},{"name":"RM_REPLENISHMENT_METHOD","dataType":"string"},{"name":"SFLT_SUPPLIER_FULL_LEAD_TIME","dataType":"string"},{"name":"SCS_SUPPLY_CHAIN_STATUS","dataType":"string"},{"name":"BPAS_BPA_STATUS","dataType":"string"},{"name":"MCOO_MULTI_COUNTRY_OF_ORIGIN","dataType":"string"},{"name":"DSO_DEFAULT_SHIPPING_ORG","dataType":"string"},{"name":"SFDCT_SFDC_TRANSFER","dataType":"string"},{"name":"IKC_ORG","dataType":"string"},{"name":"IKC_ORG_GROUP","dataType":"string"},{"name":"IKC_USERID","dataType":"string"},{"name":"EUHTS_HTS_CODE_EU","dataType":"string"},{"name":"CRI_ACCOUNT_NUMBER","dataType":"string"},{"name":"XYZ_XYZ_CLASS","dataType":"string"},{"name":"SCSD_SUPPLY_CHAIN_STATUS_DAYS","dataType":"string"},{"name":"MMKS_SOURCE","dataType":"string"},{"name":"MMKS_AUTO_UPDATE","dataType":"string"},{"name":"DO_DESIGN_ORG","dataType":"string"}]},{"$type":"LocalEntity","name":"no_use_XXCOH_IM_ITEM_VIEW","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"no_use_XXCOH_IM_ITEM_VIEW.csv"},"attributes":[{"name":"ITEM_ORG_KEY_ID","dataType":"string"},{"name":"ITEM_ORG_KEY_CODE","dataType":"string"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"ORGANIZATION_ID","dataType":"double"},{"name":"LAST_UPDATE_DATE","dataType":"dateTime"},{"name":"LAST_UPDATED_BY","dataType":"double"},{"name":"CREATION_DATE","dataType":"dateTime"},{"name":"CREATED_BY","dataType":"double"},{"name":"LAST_UPDATE_LOGIN","dataType":"double"},{"name":"SUMMARY_FLAG","dataType":"string"},{"name":"ENABLED_FLAG","dataType":"string"},{"name":"DESCRIPTION","dataType":"string"},{"name":"BUYER_ID","dataType":"double"},{"name":"SEGMENT1","dataType":"string"},{"name":"ATTRIBUTE_CATEGORY","dataType":"string"},{"name":"ATTRIBUTE13","dataType":"string"},{"name":"ATTRIBUTE14","dataType":"string"},{"name":"ATTRIBUTE15","dataType":"string"},{"name":"PURCHASING_ITEM_FLAG","dataType":"string"},{"name":"SHIPPABLE_ITEM_FLAG","dataType":"string"},{"name":"CUSTOMER_ORDER_FLAG","dataType":"string"},{"name":"INTERNAL_ORDER_FLAG","dataType":"string"},{"name":"SERVICE_ITEM_FLAG","dataType":"string"},{"name":"INVENTORY_ITEM_FLAG","dataType":"string"},{"name":"ENG_ITEM_FLAG","dataType":"string"},{"name":"INVENTORY_ASSET_FLAG","dataType":"string"},{"name":"PURCHASING_ENABLED_FLAG","dataType":"string"},{"name":"CUSTOMER_ORDER_ENABLED_FLAG","dataType":"string"},{"name":"INTERNAL_ORDER_ENABLED_FLAG","dataType":"string"},{"name":"SO_TRANSACTIONS_FLAG","dataType":"string"},{"name":"MTL_TRANSACTIONS_ENABLED_FLAG","dataType":"string"},{"name":"STOCK_ENABLED_FLAG","dataType":"string"},{"name":"BOM_ENABLED_FLAG","dataType":"string"},{"name":"BUILD_IN_WIP_FLAG","dataType":"string"},{"name":"REVISION_QTY_CONTROL_CODE","dataType":"double"},{"name":"ITEM_CATALOG_GROUP_ID","dataType":"double"},{"name":"CATALOG_STATUS_FLAG","dataType":"string"},{"name":"RETURNABLE_FLAG","dataType":"string"},{"name":"DEFAULT_SHIPPING_ORG","dataType":"double"},{"name":"COLLATERAL_FLAG","dataType":"string"},{"name":"TAXABLE_FLAG","dataType":"string"},{"name":"QTY_RCV_EXCEPTION_CODE","dataType":"string"},{"name":"ALLOW_ITEM_DESC_UPDATE_FLAG","dataType":"string"},{"name":"INSPECTION_REQUIRED_FLAG","dataType":"string"},{"name":"RECEIPT_REQUIRED_FLAG","dataType":"string"},{"name":"MARKET_PRICE","dataType":"double"},{"name":"RFQ_REQUIRED_FLAG","dataType":"string"},{"name":"QTY_RCV_TOLERANCE","dataType":"double"},{"name":"LIST_PRICE_PER_UNIT","dataType":"double"},{"name":"PRICE_TOLERANCE_PERCENT","dataType":"double"},{"name":"UNIT_OF_ISSUE","dataType":"string"},{"name":"ENFORCE_SHIP_TO_LOCATION_CODE","dataType":"string"},{"name":"ALLOW_EXPRESS_DELIVERY_FLAG","dataType":"string"},{"name":"DAYS_EARLY_RECEIPT_ALLOWED","dataType":"double"},{"name":"DAYS_LATE_RECEIPT_ALLOWED","dataType":"double"},{"name":"RECEIPT_DAYS_EXCEPTION_CODE","dataType":"string"},{"name":"RECEIVING_ROUTING_ID","dataType":"double"},{"name":"RECEIVE_CLOSE_TOLERANCE","dataType":"double"},{"name":"AUTO_LOT_ALPHA_PREFIX","dataType":"string"},{"name":"START_AUTO_LOT_NUMBER","dataType":"string"},{"name":"LOT_CONTROL_CODE","dataType":"double"},{"name":"SHELF_LIFE_CODE","dataType":"double"},{"name":"SHELF_LIFE_DAYS","dataType":"double"},{"name":"SERIAL_NUMBER_CONTROL_CODE","dataType":"double"},{"name":"START_AUTO_SERIAL_NUMBER","dataType":"string"},{"name":"AUTO_SERIAL_ALPHA_PREFIX","dataType":"string"},{"name":"SOURCE_TYPE","dataType":"double"},{"name":"SOURCE_ORGANIZATION_ID","dataType":"double"},{"name":"SOURCE_SUBINVENTORY","dataType":"string"},{"name":"EXPENSE_ACCOUNT","dataType":"double"},{"name":"RESTRICT_SUBINVENTORIES_CODE","dataType":"double"},{"name":"UNIT_WEIGHT","dataType":"double"},{"name":"WEIGHT_UOM_CODE","dataType":"string"},{"name":"VOLUME_UOM_CODE","dataType":"string"},{"name":"UNIT_VOLUME","dataType":"double"},{"name":"RESTRICT_LOCATORS_CODE","dataType":"double"},{"name":"LOCATION_CONTROL_CODE","dataType":"double"},{"name":"SHRINKAGE_RATE","dataType":"double"},{"name":"ACCEPTABLE_EARLY_DAYS","dataType":"double"},{"name":"PLANNING_TIME_FENCE_CODE","dataType":"double"},{"name":"DEMAND_TIME_FENCE_CODE","dataType":"double"},{"name":"LEAD_TIME_LOT_SIZE","dataType":"double"},{"name":"STD_LOT_SIZE","dataType":"double"},{"name":"CUM_MANUFACTURING_LEAD_TIME","dataType":"double"},{"name":"OVERRUN_PERCENTAGE","dataType":"double"},{"name":"MRP_CALCULATE_ATP_FLAG","dataType":"string"},{"name":"ACCEPTABLE_RATE_INCREASE","dataType":"double"},{"name":"ACCEPTABLE_RATE_DECREASE","dataType":"double"},{"name":"CUMULATIVE_TOTAL_LEAD_TIME","dataType":"double"},{"name":"PLANNING_TIME_FENCE_DAYS","dataType":"double"},{"name":"DEMAND_TIME_FENCE_DAYS","dataType":"double"},{"name":"END_ASSEMBLY_PEGGING_FLAG","dataType":"string"},{"name":"REPETITIVE_PLANNING_FLAG","dataType":"string"},{"name":"PLANNING_EXCEPTION_SET","dataType":"string"},{"name":"BOM_ITEM_TYPE","dataType":"double"},{"name":"PICK_COMPONENTS_FLAG","dataType":"string"},{"name":"REPLENISH_TO_ORDER_FLAG","dataType":"string"},{"name":"BASE_ITEM_ID","dataType":"double"},{"name":"ATP_COMPONENTS_FLAG","dataType":"string"},{"name":"ATP_FLAG","dataType":"string"},{"name":"FIXED_LEAD_TIME","dataType":"double"},{"name":"VARIABLE_LEAD_TIME","dataType":"double"},{"name":"WIP_SUPPLY_LOCATOR_ID","dataType":"double"},{"name":"WIP_SUPPLY_TYPE","dataType":"double"},{"name":"WIP_SUPPLY_SUBINVENTORY","dataType":"string"},{"name":"PRIMARY_UOM_CODE","dataType":"string"},{"name":"PRIMARY_UNIT_OF_MEASURE","dataType":"string"},{"name":"ALLOWED_UNITS_LOOKUP_CODE","dataType":"double"},{"name":"COST_OF_SALES_ACCOUNT","dataType":"double"},{"name":"SALES_ACCOUNT","dataType":"double"},{"name":"DEFAULT_INCLUDE_IN_ROLLUP_FLAG","dataType":"string"},{"name":"INVENTORY_ITEM_STATUS_CODE","dataType":"string"},{"name":"INVENTORY_PLANNING_CODE","dataType":"double"},{"name":"PLANNER_CODE","dataType":"string"},{"name":"PLANNING_MAKE_BUY_CODE","dataType":"double"},{"name":"FIXED_LOT_MULTIPLIER","dataType":"double"},{"name":"ROUNDING_CONTROL_TYPE","dataType":"double"},{"name":"POSTPROCESSING_LEAD_TIME","dataType":"double"},{"name":"PREPROCESSING_LEAD_TIME","dataType":"double"},{"name":"FULL_LEAD_TIME","dataType":"double"},{"name":"ORDER_COST","dataType":"double"},{"name":"MRP_SAFETY_STOCK_PERCENT","dataType":"double"},{"name":"MRP_SAFETY_STOCK_CODE","dataType":"double"},{"name":"MIN_MINMAX_QUANTITY","dataType":"double"},{"name":"MAX_MINMAX_QUANTITY","dataType":"double"},{"name":"MINIMUM_ORDER_QUANTITY","dataType":"double"},{"name":"FIXED_ORDER_QUANTITY","dataType":"double"},{"name":"FIXED_DAYS_SUPPLY","dataType":"double"},{"name":"MAXIMUM_ORDER_QUANTITY","dataType":"double"},{"name":"ATP_RULE_ID","dataType":"double"},{"name":"RESERVABLE_TYPE","dataType":"double"},{"name":"POSITIVE_MEASUREMENT_ERROR","dataType":"double"},{"name":"NEGATIVE_MEASUREMENT_ERROR","dataType":"double"},{"name":"VENDOR_WARRANTY_FLAG","dataType":"string"},{"name":"SERVICEABLE_COMPONENT_FLAG","dataType":"string"},{"name":"SERVICEABLE_PRODUCT_FLAG","dataType":"string"},{"name":"PAYMENT_TERMS_ID","dataType":"double"},{"name":"PREVENTIVE_MAINTENANCE_FLAG","dataType":"string"},{"name":"TIME_BILLABLE_FLAG","dataType":"string"},{"name":"MATERIAL_BILLABLE_FLAG","dataType":"string"},{"name":"EXPENSE_BILLABLE_FLAG","dataType":"string"},{"name":"PRORATE_SERVICE_FLAG","dataType":"string"},{"name":"COVERAGE_SCHEDULE_ID","dataType":"double"},{"name":"SERVICE_DURATION_PERIOD_CODE","dataType":"string"},{"name":"SERVICE_DURATION","dataType":"double"},{"name":"INVOICEABLE_ITEM_FLAG","dataType":"string"},{"name":"INVOICE_ENABLED_FLAG","dataType":"string"},{"name":"MUST_USE_APPROVED_VENDOR_FLAG","dataType":"string"},{"name":"REQUEST_ID","dataType":"double"},{"name":"PROGRAM_APPLICATION_ID","dataType":"double"},{"name":"PROGRAM_ID","dataType":"double"},{"name":"PROGRAM_UPDATE_DATE","dataType":"dateTime"},{"name":"OUTSIDE_OPERATION_FLAG","dataType":"string"},{"name":"OUTSIDE_OPERATION_UOM_TYPE","dataType":"string"},{"name":"SAFETY_STOCK_BUCKET_DAYS","dataType":"double"},{"name":"AUTO_REDUCE_MPS","dataType":"double"},{"name":"COSTING_ENABLED_FLAG","dataType":"string"},{"name":"AUTO_CREATED_CONFIG_FLAG","dataType":"string"},{"name":"CYCLE_COUNT_ENABLED_FLAG","dataType":"string"},{"name":"ITEM_TYPE","dataType":"string"},{"name":"SHIP_MODEL_COMPLETE_FLAG","dataType":"string"},{"name":"MRP_PLANNING_CODE","dataType":"double"},{"name":"RETURN_INSPECTION_REQUIREMENT","dataType":"double"},{"name":"ATO_FORECAST_CONTROL","dataType":"double"},{"name":"RELEASE_TIME_FENCE_CODE","dataType":"double"},{"name":"RELEASE_TIME_FENCE_DAYS","dataType":"double"},{"name":"CONTAINER_ITEM_FLAG","dataType":"string"},{"name":"VEHICLE_ITEM_FLAG","dataType":"string"},{"name":"PRODUCT_FAMILY_ITEM_ID","dataType":"double"},{"name":"PURCHASING_TAX_CODE","dataType":"string"},{"name":"OVERCOMPLETION_TOLERANCE_TYPE","dataType":"double"},{"name":"OVERCOMPLETION_TOLERANCE_VALUE","dataType":"double"},{"name":"EFFECTIVITY_CONTROL","dataType":"double"},{"name":"CHECK_SHORTAGES_FLAG","dataType":"string"},{"name":"EQUIPMENT_TYPE","dataType":"double"},{"name":"DEFECT_TRACKING_ON_FLAG","dataType":"string"},{"name":"EVENT_FLAG","dataType":"string"},{"name":"ELECTRONIC_FLAG","dataType":"string"},{"name":"DOWNLOADABLE_FLAG","dataType":"string"},{"name":"COMMS_NL_TRACKABLE_FLAG","dataType":"string"},{"name":"ASSET_CREATION_CODE","dataType":"string"},{"name":"ORDERABLE_ON_WEB_FLAG","dataType":"string"},{"name":"BACK_ORDERABLE_FLAG","dataType":"string"},{"name":"WEB_STATUS","dataType":"string"},{"name":"INDIVISIBLE_FLAG","dataType":"string"},{"name":"BULK_PICKED_FLAG","dataType":"string"},{"name":"LOT_STATUS_ENABLED","dataType":"string"},{"name":"SERIAL_STATUS_ENABLED","dataType":"string"},{"name":"DEFAULT_SERIAL_STATUS_ID","dataType":"double"},{"name":"LOT_SPLIT_ENABLED","dataType":"string"},{"name":"LOT_MERGE_ENABLED","dataType":"string"},{"name":"FINANCING_ALLOWED_FLAG","dataType":"string"},{"name":"EAM_ACT_NOTIFICATION_FLAG","dataType":"string"},{"name":"DUAL_UOM_CONTROL","dataType":"double"},{"name":"DUAL_UOM_DEVIATION_HIGH","dataType":"double"},{"name":"DUAL_UOM_DEVIATION_LOW","dataType":"double"},{"name":"CONTRACT_ITEM_TYPE_CODE","dataType":"string"},{"name":"SERV_REQ_ENABLED_CODE","dataType":"string"},{"name":"SERV_BILLING_ENABLED_FLAG","dataType":"string"},{"name":"PLANNED_INV_POINT_FLAG","dataType":"string"},{"name":"LOT_TRANSLATE_ENABLED","dataType":"string"},{"name":"DEFAULT_SO_SOURCE_TYPE","dataType":"string"},{"name":"CREATE_SUPPLY_FLAG","dataType":"string"},{"name":"LOT_SUBSTITUTION_ENABLED","dataType":"string"},{"name":"OBJECT_VERSION_NUMBER","dataType":"double"},{"name":"TRACKING_QUANTITY_IND","dataType":"string"},{"name":"ONT_PRICING_QTY_SOURCE","dataType":"string"},{"name":"VMI_MINIMUM_UNITS","dataType":"double"},{"name":"VMI_MAXIMUM_UNITS","dataType":"double"},{"name":"SO_AUTHORIZATION_FLAG","dataType":"double"},{"name":"CONSIGNED_FLAG","dataType":"double"},{"name":"ASN_AUTOEXPIRE_FLAG","dataType":"double"},{"name":"VMI_FORECAST_TYPE","dataType":"double"},{"name":"EXCLUDE_FROM_BUDGET_FLAG","dataType":"double"},{"name":"DRP_PLANNED_FLAG","dataType":"double"},{"name":"CRITICAL_COMPONENT_FLAG","dataType":"double"},{"name":"CONTINOUS_TRANSFER","dataType":"double"},{"name":"CONVERGENCE","dataType":"double"},{"name":"DIVERGENCE","dataType":"double"},{"name":"CHILD_LOT_FLAG","dataType":"string"},{"name":"CHILD_LOT_VALIDATION_FLAG","dataType":"string"},{"name":"COPY_LOT_ATTRIBUTE_FLAG","dataType":"string"},{"name":"GRADE_CONTROL_FLAG","dataType":"string"},{"name":"HAZARDOUS_MATERIAL_FLAG","dataType":"string"},{"name":"LOT_DIVISIBLE_FLAG","dataType":"string"},{"name":"PROCESS_COSTING_ENABLED_FLAG","dataType":"string"},{"name":"PROCESS_EXECUTION_ENABLED_FLAG","dataType":"string"},{"name":"PROCESS_QUALITY_ENABLED_FLAG","dataType":"string"},{"name":"PROCESS_SUPPLY_LOCATOR_ID","dataType":"double"},{"name":"PROCESS_SUPPLY_SUBINVENTORY","dataType":"string"},{"name":"RECIPE_ENABLED_FLAG","dataType":"string"},{"name":"PREPOSITION_POINT","dataType":"string"},{"name":"REPAIR_PROGRAM","dataType":"double"},{"name":"OUTSOURCED_ASSEMBLY","dataType":"double"},{"name":"GDSN_OUTBOUND_ENABLED_FLAG","dataType":"string"},{"name":"SERIAL_TAGGING_FLAG","dataType":"string"},{"name":"IB_ITEM_TRACKING_LEVEL","dataType":"string"},{"name":"MCC_CONTROL_CODE","dataType":"double"},{"name":"START_DATE_ACTIVE","dataType":"dateTime"},{"name":"END_DATE_ACTIVE","dataType":"dateTime"},{"name":"ORGANIZATION_CODE","dataType":"string"},{"name":"ITEM_DESCRIPTION","dataType":"string"},{"name":"USER_ITEM_TYPE","dataType":"string"},{"name":"BOM_ITEM_TYPE_DESCRIPTION","dataType":"string"},{"name":"COST_SOURCE_TYPE","dataType":"string"},{"name":"DEFAULT_BUYER","dataType":"string"},{"name":"ITEM_CATALOG_GROUP","dataType":"string"},{"name":"DEFAULT_RECV_SUBINVENTORY","dataType":"string"},{"name":"END_ASSEMBLY_PEGGING","dataType":"string"},{"name":"EFFECTIVITY_DATE","dataType":"dateTime"},{"name":"REVISION","dataType":"string"},{"name":"POWERBI_REFRESH_PARTITION","dataType":"dateTime"}]},{"$type":"LocalEntity","name":"no_use_XXREP_MTL_ITEM_CATEGORIES_V","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"no_use_XXREP_MTL_ITEM_CATEGORIES_V.csv"},"attributes":[{"name":"ORGANIZATION_ID","dataType":"double"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"SUPPLY_CHAIN_STATUS","dataType":"string"},{"name":"ORG_PRODUCT","dataType":"string"},{"name":"PRODUCT","dataType":"string"},{"name":"COUNTRY_OF_ORIGIN","dataType":"string"},{"name":"SOURCING_COMMODITY","dataType":"string"},{"name":"PRODUCT_FAMILY","dataType":"string"},{"name":"COMMODITY","dataType":"string"},{"name":"SUPPLIER_FULL_LEAD_TIME","dataType":"string"},{"name":"SALES_AVAILABILITY","dataType":"string"},{"name":"PRIMARY_ORG","dataType":"string"},{"name":"SHIPMENT_PRIORITY","dataType":"string"},{"name":"REPLENISHMENT_METHOD","dataType":"string"},{"name":"SOURCING_RULE","dataType":"string"},{"name":"COST_SOURCE","dataType":"string"}]},{"$type":"LocalEntity","name":"no_use_XXREP_MTL_SYSTEM_ITEMS_NO_MAS_V","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"no_use_XXREP_MTL_SYSTEM_ITEMS_NO_MAS_V.csv"},"attributes":[{"name":"ITEM_ORG_KEY_ID","dataType":"string"},{"name":"ITEM_ORG_KEY_CODE","dataType":"string"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"ORGANIZATION_ID","dataType":"double"},{"name":"LAST_UPDATE_DATE","dataType":"dateTime"},{"name":"LAST_UPDATED_BY","dataType":"double"},{"name":"CREATION_DATE","dataType":"dateTime"},{"name":"CREATED_BY","dataType":"double"},{"name":"LAST_UPDATE_LOGIN","dataType":"double"},{"name":"SUMMARY_FLAG","dataType":"string"},{"name":"ENABLED_FLAG","dataType":"string"},{"name":"DESCRIPTION","dataType":"string"},{"name":"BUYER_ID","dataType":"double"},{"name":"SEGMENT1","dataType":"string"},{"name":"ATTRIBUTE_CATEGORY","dataType":"string"},{"name":"ATTRIBUTE13","dataType":"string"},{"name":"ATTRIBUTE14","dataType":"string"},{"name":"ATTRIBUTE15","dataType":"string"},{"name":"PURCHASING_ITEM_FLAG","dataType":"string"},{"name":"SHIPPABLE_ITEM_FLAG","dataType":"string"},{"name":"CUSTOMER_ORDER_FLAG","dataType":"string"},{"name":"INTERNAL_ORDER_FLAG","dataType":"string"},{"name":"SERVICE_ITEM_FLAG","dataType":"string"},{"name":"INVENTORY_ITEM_FLAG","dataType":"string"},{"name":"ENG_ITEM_FLAG","dataType":"string"},{"name":"INVENTORY_ASSET_FLAG","dataType":"string"},{"name":"PURCHASING_ENABLED_FLAG","dataType":"string"},{"name":"CUSTOMER_ORDER_ENABLED_FLAG","dataType":"string"},{"name":"INTERNAL_ORDER_ENABLED_FLAG","dataType":"string"},{"name":"SO_TRANSACTIONS_FLAG","dataType":"string"},{"name":"MTL_TRANSACTIONS_ENABLED_FLAG","dataType":"string"},{"name":"STOCK_ENABLED_FLAG","dataType":"string"},{"name":"BOM_ENABLED_FLAG","dataType":"string"},{"name":"BUILD_IN_WIP_FLAG","dataType":"string"},{"name":"REVISION_QTY_CONTROL_CODE","dataType":"double"},{"name":"ITEM_CATALOG_GROUP_ID","dataType":"double"},{"name":"CATALOG_STATUS_FLAG","dataType":"string"},{"name":"RETURNABLE_FLAG","dataType":"string"},{"name":"DEFAULT_SHIPPING_ORG","dataType":"double"},{"name":"COLLATERAL_FLAG","dataType":"string"},{"name":"TAXABLE_FLAG","dataType":"string"},{"name":"QTY_RCV_EXCEPTION_CODE","dataType":"string"},{"name":"ALLOW_ITEM_DESC_UPDATE_FLAG","dataType":"string"},{"name":"INSPECTION_REQUIRED_FLAG","dataType":"string"},{"name":"RECEIPT_REQUIRED_FLAG","dataType":"string"},{"name":"MARKET_PRICE","dataType":"double"},{"name":"RFQ_REQUIRED_FLAG","dataType":"string"},{"name":"QTY_RCV_TOLERANCE","dataType":"double"},{"name":"LIST_PRICE_PER_UNIT","dataType":"double"},{"name":"PRICE_TOLERANCE_PERCENT","dataType":"double"},{"name":"UNIT_OF_ISSUE","dataType":"string"},{"name":"ENFORCE_SHIP_TO_LOCATION_CODE","dataType":"string"},{"name":"ALLOW_EXPRESS_DELIVERY_FLAG","dataType":"string"},{"name":"DAYS_EARLY_RECEIPT_ALLOWED","dataType":"double"},{"name":"DAYS_LATE_RECEIPT_ALLOWED","dataType":"double"},{"name":"RECEIPT_DAYS_EXCEPTION_CODE","dataType":"string"},{"name":"RECEIVING_ROUTING_ID","dataType":"double"},{"name":"RECEIVE_CLOSE_TOLERANCE","dataType":"double"},{"name":"AUTO_LOT_ALPHA_PREFIX","dataType":"string"},{"name":"START_AUTO_LOT_NUMBER","dataType":"string"},{"name":"LOT_CONTROL_CODE","dataType":"double"},{"name":"SHELF_LIFE_CODE","dataType":"double"},{"name":"SHELF_LIFE_DAYS","dataType":"double"},{"name":"SERIAL_NUMBER_CONTROL_CODE","dataType":"double"},{"name":"START_AUTO_SERIAL_NUMBER","dataType":"string"},{"name":"AUTO_SERIAL_ALPHA_PREFIX","dataType":"string"},{"name":"SOURCE_TYPE","dataType":"double"},{"name":"SOURCE_ORGANIZATION_ID","dataType":"double"},{"name":"SOURCE_SUBINVENTORY","dataType":"string"},{"name":"EXPENSE_ACCOUNT","dataType":"double"},{"name":"RESTRICT_SUBINVENTORIES_CODE","dataType":"double"},{"name":"UNIT_WEIGHT","dataType":"double"},{"name":"WEIGHT_UOM_CODE","dataType":"string"},{"name":"VOLUME_UOM_CODE","dataType":"string"},{"name":"UNIT_VOLUME","dataType":"double"},{"name":"RESTRICT_LOCATORS_CODE","dataType":"double"},{"name":"LOCATION_CONTROL_CODE","dataType":"double"},{"name":"SHRINKAGE_RATE","dataType":"double"},{"name":"ACCEPTABLE_EARLY_DAYS","dataType":"double"},{"name":"PLANNING_TIME_FENCE_CODE","dataType":"double"},{"name":"DEMAND_TIME_FENCE_CODE","dataType":"double"},{"name":"LEAD_TIME_LOT_SIZE","dataType":"double"},{"name":"STD_LOT_SIZE","dataType":"double"},{"name":"CUM_MANUFACTURING_LEAD_TIME","dataType":"double"},{"name":"OVERRUN_PERCENTAGE","dataType":"double"},{"name":"MRP_CALCULATE_ATP_FLAG","dataType":"string"},{"name":"ACCEPTABLE_RATE_INCREASE","dataType":"double"},{"name":"ACCEPTABLE_RATE_DECREASE","dataType":"double"},{"name":"CUMULATIVE_TOTAL_LEAD_TIME","dataType":"double"},{"name":"PLANNING_TIME_FENCE_DAYS","dataType":"double"},{"name":"DEMAND_TIME_FENCE_DAYS","dataType":"double"},{"name":"END_ASSEMBLY_PEGGING_FLAG","dataType":"string"},{"name":"REPETITIVE_PLANNING_FLAG","dataType":"string"},{"name":"PLANNING_EXCEPTION_SET","dataType":"string"},{"name":"BOM_ITEM_TYPE","dataType":"double"},{"name":"PICK_COMPONENTS_FLAG","dataType":"string"},{"name":"REPLENISH_TO_ORDER_FLAG","dataType":"string"},{"name":"BASE_ITEM_ID","dataType":"double"},{"name":"ATP_COMPONENTS_FLAG","dataType":"string"},{"name":"ATP_FLAG","dataType":"string"},{"name":"FIXED_LEAD_TIME","dataType":"double"},{"name":"VARIABLE_LEAD_TIME","dataType":"double"},{"name":"WIP_SUPPLY_LOCATOR_ID","dataType":"double"},{"name":"WIP_SUPPLY_TYPE","dataType":"double"},{"name":"WIP_SUPPLY_SUBINVENTORY","dataType":"string"},{"name":"PRIMARY_UOM_CODE","dataType":"string"},{"name":"PRIMARY_UNIT_OF_MEASURE","dataType":"string"},{"name":"ALLOWED_UNITS_LOOKUP_CODE","dataType":"double"},{"name":"COST_OF_SALES_ACCOUNT","dataType":"double"},{"name":"SALES_ACCOUNT","dataType":"double"},{"name":"DEFAULT_INCLUDE_IN_ROLLUP_FLAG","dataType":"string"},{"name":"INVENTORY_ITEM_STATUS_CODE","dataType":"string"},{"name":"INVENTORY_PLANNING_CODE","dataType":"double"},{"name":"PLANNER_CODE","dataType":"string"},{"name":"PLANNING_MAKE_BUY_CODE","dataType":"double"},{"name":"FIXED_LOT_MULTIPLIER","dataType":"double"},{"name":"ROUNDING_CONTROL_TYPE","dataType":"double"},{"name":"POSTPROCESSING_LEAD_TIME","dataType":"double"},{"name":"PREPROCESSING_LEAD_TIME","dataType":"double"},{"name":"FULL_LEAD_TIME","dataType":"double"},{"name":"ORDER_COST","dataType":"double"},{"name":"MRP_SAFETY_STOCK_PERCENT","dataType":"double"},{"name":"MRP_SAFETY_STOCK_CODE","dataType":"double"},{"name":"MIN_MINMAX_QUANTITY","dataType":"double"},{"name":"MAX_MINMAX_QUANTITY","dataType":"double"},{"name":"MINIMUM_ORDER_QUANTITY","dataType":"double"},{"name":"FIXED_ORDER_QUANTITY","dataType":"double"},{"name":"FIXED_DAYS_SUPPLY","dataType":"double"},{"name":"MAXIMUM_ORDER_QUANTITY","dataType":"double"},{"name":"ATP_RULE_ID","dataType":"double"},{"name":"RESERVABLE_TYPE","dataType":"double"},{"name":"POSITIVE_MEASUREMENT_ERROR","dataType":"double"},{"name":"NEGATIVE_MEASUREMENT_ERROR","dataType":"double"},{"name":"VENDOR_WARRANTY_FLAG","dataType":"string"},{"name":"SERVICEABLE_COMPONENT_FLAG","dataType":"string"},{"name":"SERVICEABLE_PRODUCT_FLAG","dataType":"string"},{"name":"PAYMENT_TERMS_ID","dataType":"double"},{"name":"PREVENTIVE_MAINTENANCE_FLAG","dataType":"string"},{"name":"TIME_BILLABLE_FLAG","dataType":"string"},{"name":"MATERIAL_BILLABLE_FLAG","dataType":"string"},{"name":"EXPENSE_BILLABLE_FLAG","dataType":"string"},{"name":"PRORATE_SERVICE_FLAG","dataType":"string"},{"name":"COVERAGE_SCHEDULE_ID","dataType":"double"},{"name":"SERVICE_DURATION_PERIOD_CODE","dataType":"string"},{"name":"SERVICE_DURATION","dataType":"double"},{"name":"INVOICEABLE_ITEM_FLAG","dataType":"string"},{"name":"INVOICE_ENABLED_FLAG","dataType":"string"},{"name":"MUST_USE_APPROVED_VENDOR_FLAG","dataType":"string"},{"name":"REQUEST_ID","dataType":"double"},{"name":"PROGRAM_APPLICATION_ID","dataType":"double"},{"name":"PROGRAM_ID","dataType":"double"},{"name":"PROGRAM_UPDATE_DATE","dataType":"dateTime"},{"name":"OUTSIDE_OPERATION_FLAG","dataType":"string"},{"name":"OUTSIDE_OPERATION_UOM_TYPE","dataType":"string"},{"name":"SAFETY_STOCK_BUCKET_DAYS","dataType":"double"},{"name":"AUTO_REDUCE_MPS","dataType":"double"},{"name":"COSTING_ENABLED_FLAG","dataType":"string"},{"name":"AUTO_CREATED_CONFIG_FLAG","dataType":"string"},{"name":"CYCLE_COUNT_ENABLED_FLAG","dataType":"string"},{"name":"ITEM_TYPE","dataType":"string"},{"name":"SHIP_MODEL_COMPLETE_FLAG","dataType":"string"},{"name":"MRP_PLANNING_CODE","dataType":"double"},{"name":"RETURN_INSPECTION_REQUIREMENT","dataType":"double"},{"name":"ATO_FORECAST_CONTROL","dataType":"double"},{"name":"RELEASE_TIME_FENCE_CODE","dataType":"double"},{"name":"RELEASE_TIME_FENCE_DAYS","dataType":"double"},{"name":"CONTAINER_ITEM_FLAG","dataType":"string"},{"name":"VEHICLE_ITEM_FLAG","dataType":"string"},{"name":"PRODUCT_FAMILY_ITEM_ID","dataType":"double"},{"name":"PURCHASING_TAX_CODE","dataType":"string"},{"name":"OVERCOMPLETION_TOLERANCE_TYPE","dataType":"double"},{"name":"OVERCOMPLETION_TOLERANCE_VALUE","dataType":"double"},{"name":"EFFECTIVITY_CONTROL","dataType":"double"},{"name":"CHECK_SHORTAGES_FLAG","dataType":"string"},{"name":"EQUIPMENT_TYPE","dataType":"double"},{"name":"DEFECT_TRACKING_ON_FLAG","dataType":"string"},{"name":"EVENT_FLAG","dataType":"string"},{"name":"ELECTRONIC_FLAG","dataType":"string"},{"name":"DOWNLOADABLE_FLAG","dataType":"string"},{"name":"COMMS_NL_TRACKABLE_FLAG","dataType":"string"},{"name":"ASSET_CREATION_CODE","dataType":"string"},{"name":"ORDERABLE_ON_WEB_FLAG","dataType":"string"},{"name":"BACK_ORDERABLE_FLAG","dataType":"string"},{"name":"WEB_STATUS","dataType":"string"},{"name":"INDIVISIBLE_FLAG","dataType":"string"},{"name":"BULK_PICKED_FLAG","dataType":"string"},{"name":"LOT_STATUS_ENABLED","dataType":"string"},{"name":"SERIAL_STATUS_ENABLED","dataType":"string"},{"name":"DEFAULT_SERIAL_STATUS_ID","dataType":"double"},{"name":"LOT_SPLIT_ENABLED","dataType":"string"},{"name":"LOT_MERGE_ENABLED","dataType":"string"},{"name":"FINANCING_ALLOWED_FLAG","dataType":"string"},{"name":"EAM_ACT_NOTIFICATION_FLAG","dataType":"string"},{"name":"DUAL_UOM_CONTROL","dataType":"double"},{"name":"DUAL_UOM_DEVIATION_HIGH","dataType":"double"},{"name":"DUAL_UOM_DEVIATION_LOW","dataType":"double"},{"name":"CONTRACT_ITEM_TYPE_CODE","dataType":"string"},{"name":"SERV_REQ_ENABLED_CODE","dataType":"string"},{"name":"SERV_BILLING_ENABLED_FLAG","dataType":"string"},{"name":"PLANNED_INV_POINT_FLAG","dataType":"string"},{"name":"LOT_TRANSLATE_ENABLED","dataType":"string"},{"name":"DEFAULT_SO_SOURCE_TYPE","dataType":"string"},{"name":"CREATE_SUPPLY_FLAG","dataType":"string"},{"name":"LOT_SUBSTITUTION_ENABLED","dataType":"string"},{"name":"OBJECT_VERSION_NUMBER","dataType":"double"},{"name":"TRACKING_QUANTITY_IND","dataType":"string"},{"name":"ONT_PRICING_QTY_SOURCE","dataType":"string"},{"name":"VMI_MINIMUM_UNITS","dataType":"double"},{"name":"VMI_MAXIMUM_UNITS","dataType":"double"},{"name":"SO_AUTHORIZATION_FLAG","dataType":"double"},{"name":"CONSIGNED_FLAG","dataType":"double"},{"name":"ASN_AUTOEXPIRE_FLAG","dataType":"double"},{"name":"VMI_FORECAST_TYPE","dataType":"double"},{"name":"EXCLUDE_FROM_BUDGET_FLAG","dataType":"double"},{"name":"DRP_PLANNED_FLAG","dataType":"double"},{"name":"CRITICAL_COMPONENT_FLAG","dataType":"double"},{"name":"CONTINOUS_TRANSFER","dataType":"double"},{"name":"CONVERGENCE","dataType":"double"},{"name":"DIVERGENCE","dataType":"double"},{"name":"CHILD_LOT_FLAG","dataType":"string"},{"name":"CHILD_LOT_VALIDATION_FLAG","dataType":"string"},{"name":"COPY_LOT_ATTRIBUTE_FLAG","dataType":"string"},{"name":"GRADE_CONTROL_FLAG","dataType":"string"},{"name":"HAZARDOUS_MATERIAL_FLAG","dataType":"string"},{"name":"LOT_DIVISIBLE_FLAG","dataType":"string"},{"name":"PROCESS_COSTING_ENABLED_FLAG","dataType":"string"},{"name":"PROCESS_EXECUTION_ENABLED_FLAG","dataType":"string"},{"name":"PROCESS_QUALITY_ENABLED_FLAG","dataType":"string"},{"name":"PROCESS_SUPPLY_LOCATOR_ID","dataType":"double"},{"name":"PROCESS_SUPPLY_SUBINVENTORY","dataType":"string"},{"name":"RECIPE_ENABLED_FLAG","dataType":"string"},{"name":"PREPOSITION_POINT","dataType":"string"},{"name":"REPAIR_PROGRAM","dataType":"double"},{"name":"OUTSOURCED_ASSEMBLY","dataType":"double"},{"name":"GDSN_OUTBOUND_ENABLED_FLAG","dataType":"string"},{"name":"SERIAL_TAGGING_FLAG","dataType":"string"},{"name":"IB_ITEM_TRACKING_LEVEL","dataType":"string"},{"name":"MCC_CONTROL_CODE","dataType":"double"},{"name":"START_DATE_ACTIVE","dataType":"dateTime"},{"name":"END_DATE_ACTIVE","dataType":"dateTime"},{"name":"ORGANIZATION_CODE","dataType":"string"},{"name":"ITEM_DESCRIPTION","dataType":"string"},{"name":"USER_ITEM_TYPE","dataType":"string"},{"name":"BOM_ITEM_TYPE_DESCRIPTION","dataType":"string"},{"name":"COST_SOURCE_TYPE","dataType":"string"},{"name":"DEFAULT_BUYER","dataType":"string"},{"name":"ITEM_CATALOG_GROUP","dataType":"string"},{"name":"DEFAULT_RECV_SUBINVENTORY","dataType":"string"},{"name":"END_ASSEMBLY_PEGGING","dataType":"string"},{"name":"EFFECTIVITY_DATE","dataType":"dateTime"},{"name":"REVISION","dataType":"string"},{"name":"POWERBI_REFRESH_PARTITION","dataType":"dateTime"}]},{"$type":"LocalEntity","name":"no_use_XXREP_MTL_SYSTEM_ITEMS_V","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"no_use_XXREP_MTL_SYSTEM_ITEMS_V.csv"},"attributes":[{"name":"ITEM_ORG_KEY_ID","dataType":"string"},{"name":"ITEM_ORG_KEY_CODE","dataType":"string"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"ORGANIZATION_ID","dataType":"double"},{"name":"LAST_UPDATE_DATE","dataType":"dateTime"},{"name":"LAST_UPDATED_BY","dataType":"double"},{"name":"CREATION_DATE","dataType":"dateTime"},{"name":"CREATED_BY","dataType":"double"},{"name":"LAST_UPDATE_LOGIN","dataType":"double"},{"name":"SUMMARY_FLAG","dataType":"string"},{"name":"ENABLED_FLAG","dataType":"string"},{"name":"DESCRIPTION","dataType":"string"},{"name":"BUYER_ID","dataType":"double"},{"name":"SEGMENT1","dataType":"string"},{"name":"ATTRIBUTE_CATEGORY","dataType":"string"},{"name":"ATTRIBUTE13","dataType":"string"},{"name":"ATTRIBUTE14","dataType":"string"},{"name":"ATTRIBUTE15","dataType":"string"},{"name":"PURCHASING_ITEM_FLAG","dataType":"string"},{"name":"SHIPPABLE_ITEM_FLAG","dataType":"string"},{"name":"CUSTOMER_ORDER_FLAG","dataType":"string"},{"name":"INTERNAL_ORDER_FLAG","dataType":"string"},{"name":"SERVICE_ITEM_FLAG","dataType":"string"},{"name":"INVENTORY_ITEM_FLAG","dataType":"string"},{"name":"ENG_ITEM_FLAG","dataType":"string"},{"name":"INVENTORY_ASSET_FLAG","dataType":"string"},{"name":"PURCHASING_ENABLED_FLAG","dataType":"string"},{"name":"CUSTOMER_ORDER_ENABLED_FLAG","dataType":"string"},{"name":"INTERNAL_ORDER_ENABLED_FLAG","dataType":"string"},{"name":"SO_TRANSACTIONS_FLAG","dataType":"string"},{"name":"MTL_TRANSACTIONS_ENABLED_FLAG","dataType":"string"},{"name":"STOCK_ENABLED_FLAG","dataType":"string"},{"name":"BOM_ENABLED_FLAG","dataType":"string"},{"name":"BUILD_IN_WIP_FLAG","dataType":"string"},{"name":"REVISION_QTY_CONTROL_CODE","dataType":"double"},{"name":"ITEM_CATALOG_GROUP_ID","dataType":"double"},{"name":"CATALOG_STATUS_FLAG","dataType":"string"},{"name":"RETURNABLE_FLAG","dataType":"string"},{"name":"DEFAULT_SHIPPING_ORG","dataType":"double"},{"name":"COLLATERAL_FLAG","dataType":"string"},{"name":"TAXABLE_FLAG","dataType":"string"},{"name":"QTY_RCV_EXCEPTION_CODE","dataType":"string"},{"name":"ALLOW_ITEM_DESC_UPDATE_FLAG","dataType":"string"},{"name":"INSPECTION_REQUIRED_FLAG","dataType":"string"},{"name":"RECEIPT_REQUIRED_FLAG","dataType":"string"},{"name":"MARKET_PRICE","dataType":"double"},{"name":"RFQ_REQUIRED_FLAG","dataType":"string"},{"name":"QTY_RCV_TOLERANCE","dataType":"double"},{"name":"LIST_PRICE_PER_UNIT","dataType":"double"},{"name":"PRICE_TOLERANCE_PERCENT","dataType":"double"},{"name":"UNIT_OF_ISSUE","dataType":"string"},{"name":"ENFORCE_SHIP_TO_LOCATION_CODE","dataType":"string"},{"name":"ALLOW_EXPRESS_DELIVERY_FLAG","dataType":"string"},{"name":"DAYS_EARLY_RECEIPT_ALLOWED","dataType":"double"},{"name":"DAYS_LATE_RECEIPT_ALLOWED","dataType":"double"},{"name":"RECEIPT_DAYS_EXCEPTION_CODE","dataType":"string"},{"name":"RECEIVING_ROUTING_ID","dataType":"double"},{"name":"RECEIVE_CLOSE_TOLERANCE","dataType":"double"},{"name":"AUTO_LOT_ALPHA_PREFIX","dataType":"string"},{"name":"START_AUTO_LOT_NUMBER","dataType":"string"},{"name":"LOT_CONTROL_CODE","dataType":"double"},{"name":"SHELF_LIFE_CODE","dataType":"double"},{"name":"SHELF_LIFE_DAYS","dataType":"double"},{"name":"SERIAL_NUMBER_CONTROL_CODE","dataType":"double"},{"name":"START_AUTO_SERIAL_NUMBER","dataType":"string"},{"name":"AUTO_SERIAL_ALPHA_PREFIX","dataType":"string"},{"name":"SOURCE_TYPE","dataType":"double"},{"name":"SOURCE_ORGANIZATION_ID","dataType":"double"},{"name":"SOURCE_SUBINVENTORY","dataType":"string"},{"name":"EXPENSE_ACCOUNT","dataType":"double"},{"name":"RESTRICT_SUBINVENTORIES_CODE","dataType":"double"},{"name":"UNIT_WEIGHT","dataType":"double"},{"name":"WEIGHT_UOM_CODE","dataType":"string"},{"name":"VOLUME_UOM_CODE","dataType":"string"},{"name":"UNIT_VOLUME","dataType":"double"},{"name":"RESTRICT_LOCATORS_CODE","dataType":"double"},{"name":"LOCATION_CONTROL_CODE","dataType":"double"},{"name":"SHRINKAGE_RATE","dataType":"double"},{"name":"ACCEPTABLE_EARLY_DAYS","dataType":"double"},{"name":"PLANNING_TIME_FENCE_CODE","dataType":"double"},{"name":"DEMAND_TIME_FENCE_CODE","dataType":"double"},{"name":"LEAD_TIME_LOT_SIZE","dataType":"double"},{"name":"STD_LOT_SIZE","dataType":"double"},{"name":"CUM_MANUFACTURING_LEAD_TIME","dataType":"double"},{"name":"OVERRUN_PERCENTAGE","dataType":"double"},{"name":"MRP_CALCULATE_ATP_FLAG","dataType":"string"},{"name":"ACCEPTABLE_RATE_INCREASE","dataType":"double"},{"name":"ACCEPTABLE_RATE_DECREASE","dataType":"double"},{"name":"CUMULATIVE_TOTAL_LEAD_TIME","dataType":"double"},{"name":"PLANNING_TIME_FENCE_DAYS","dataType":"double"},{"name":"DEMAND_TIME_FENCE_DAYS","dataType":"double"},{"name":"END_ASSEMBLY_PEGGING_FLAG","dataType":"string"},{"name":"REPETITIVE_PLANNING_FLAG","dataType":"string"},{"name":"PLANNING_EXCEPTION_SET","dataType":"string"},{"name":"BOM_ITEM_TYPE","dataType":"double"},{"name":"PICK_COMPONENTS_FLAG","dataType":"string"},{"name":"REPLENISH_TO_ORDER_FLAG","dataType":"string"},{"name":"BASE_ITEM_ID","dataType":"double"},{"name":"ATP_COMPONENTS_FLAG","dataType":"string"},{"name":"ATP_FLAG","dataType":"string"},{"name":"FIXED_LEAD_TIME","dataType":"double"},{"name":"VARIABLE_LEAD_TIME","dataType":"double"},{"name":"WIP_SUPPLY_LOCATOR_ID","dataType":"double"},{"name":"WIP_SUPPLY_TYPE","dataType":"double"},{"name":"WIP_SUPPLY_SUBINVENTORY","dataType":"string"},{"name":"PRIMARY_UOM_CODE","dataType":"string"},{"name":"PRIMARY_UNIT_OF_MEASURE","dataType":"string"},{"name":"ALLOWED_UNITS_LOOKUP_CODE","dataType":"double"},{"name":"COST_OF_SALES_ACCOUNT","dataType":"double"},{"name":"SALES_ACCOUNT","dataType":"double"},{"name":"DEFAULT_INCLUDE_IN_ROLLUP_FLAG","dataType":"string"},{"name":"INVENTORY_ITEM_STATUS_CODE","dataType":"string"},{"name":"INVENTORY_PLANNING_CODE","dataType":"double"},{"name":"PLANNER_CODE","dataType":"string"},{"name":"PLANNING_MAKE_BUY_CODE","dataType":"double"},{"name":"FIXED_LOT_MULTIPLIER","dataType":"double"},{"name":"ROUNDING_CONTROL_TYPE","dataType":"double"},{"name":"POSTPROCESSING_LEAD_TIME","dataType":"double"},{"name":"PREPROCESSING_LEAD_TIME","dataType":"double"},{"name":"FULL_LEAD_TIME","dataType":"double"},{"name":"ORDER_COST","dataType":"double"},{"name":"MRP_SAFETY_STOCK_PERCENT","dataType":"double"},{"name":"MRP_SAFETY_STOCK_CODE","dataType":"double"},{"name":"MIN_MINMAX_QUANTITY","dataType":"double"},{"name":"MAX_MINMAX_QUANTITY","dataType":"double"},{"name":"MINIMUM_ORDER_QUANTITY","dataType":"double"},{"name":"FIXED_ORDER_QUANTITY","dataType":"double"},{"name":"FIXED_DAYS_SUPPLY","dataType":"double"},{"name":"MAXIMUM_ORDER_QUANTITY","dataType":"double"},{"name":"ATP_RULE_ID","dataType":"double"},{"name":"RESERVABLE_TYPE","dataType":"double"},{"name":"POSITIVE_MEASUREMENT_ERROR","dataType":"double"},{"name":"NEGATIVE_MEASUREMENT_ERROR","dataType":"double"},{"name":"VENDOR_WARRANTY_FLAG","dataType":"string"},{"name":"SERVICEABLE_COMPONENT_FLAG","dataType":"string"},{"name":"SERVICEABLE_PRODUCT_FLAG","dataType":"string"},{"name":"PAYMENT_TERMS_ID","dataType":"double"},{"name":"PREVENTIVE_MAINTENANCE_FLAG","dataType":"string"},{"name":"TIME_BILLABLE_FLAG","dataType":"string"},{"name":"MATERIAL_BILLABLE_FLAG","dataType":"string"},{"name":"EXPENSE_BILLABLE_FLAG","dataType":"string"},{"name":"PRORATE_SERVICE_FLAG","dataType":"string"},{"name":"COVERAGE_SCHEDULE_ID","dataType":"double"},{"name":"SERVICE_DURATION_PERIOD_CODE","dataType":"string"},{"name":"SERVICE_DURATION","dataType":"double"},{"name":"INVOICEABLE_ITEM_FLAG","dataType":"string"},{"name":"INVOICE_ENABLED_FLAG","dataType":"string"},{"name":"MUST_USE_APPROVED_VENDOR_FLAG","dataType":"string"},{"name":"REQUEST_ID","dataType":"double"},{"name":"PROGRAM_APPLICATION_ID","dataType":"double"},{"name":"PROGRAM_ID","dataType":"double"},{"name":"PROGRAM_UPDATE_DATE","dataType":"dateTime"},{"name":"OUTSIDE_OPERATION_FLAG","dataType":"string"},{"name":"OUTSIDE_OPERATION_UOM_TYPE","dataType":"string"},{"name":"SAFETY_STOCK_BUCKET_DAYS","dataType":"double"},{"name":"AUTO_REDUCE_MPS","dataType":"double"},{"name":"COSTING_ENABLED_FLAG","dataType":"string"},{"name":"AUTO_CREATED_CONFIG_FLAG","dataType":"string"},{"name":"CYCLE_COUNT_ENABLED_FLAG","dataType":"string"},{"name":"ITEM_TYPE","dataType":"string"},{"name":"SHIP_MODEL_COMPLETE_FLAG","dataType":"string"},{"name":"MRP_PLANNING_CODE","dataType":"double"},{"name":"RETURN_INSPECTION_REQUIREMENT","dataType":"double"},{"name":"ATO_FORECAST_CONTROL","dataType":"double"},{"name":"RELEASE_TIME_FENCE_CODE","dataType":"double"},{"name":"RELEASE_TIME_FENCE_DAYS","dataType":"double"},{"name":"CONTAINER_ITEM_FLAG","dataType":"string"},{"name":"VEHICLE_ITEM_FLAG","dataType":"string"},{"name":"PRODUCT_FAMILY_ITEM_ID","dataType":"double"},{"name":"PURCHASING_TAX_CODE","dataType":"string"},{"name":"OVERCOMPLETION_TOLERANCE_TYPE","dataType":"double"},{"name":"OVERCOMPLETION_TOLERANCE_VALUE","dataType":"double"},{"name":"EFFECTIVITY_CONTROL","dataType":"double"},{"name":"CHECK_SHORTAGES_FLAG","dataType":"string"},{"name":"EQUIPMENT_TYPE","dataType":"double"},{"name":"DEFECT_TRACKING_ON_FLAG","dataType":"string"},{"name":"EVENT_FLAG","dataType":"string"},{"name":"ELECTRONIC_FLAG","dataType":"string"},{"name":"DOWNLOADABLE_FLAG","dataType":"string"},{"name":"COMMS_NL_TRACKABLE_FLAG","dataType":"string"},{"name":"ASSET_CREATION_CODE","dataType":"string"},{"name":"ORDERABLE_ON_WEB_FLAG","dataType":"string"},{"name":"BACK_ORDERABLE_FLAG","dataType":"string"},{"name":"WEB_STATUS","dataType":"string"},{"name":"INDIVISIBLE_FLAG","dataType":"string"},{"name":"BULK_PICKED_FLAG","dataType":"string"},{"name":"LOT_STATUS_ENABLED","dataType":"string"},{"name":"SERIAL_STATUS_ENABLED","dataType":"string"},{"name":"DEFAULT_SERIAL_STATUS_ID","dataType":"double"},{"name":"LOT_SPLIT_ENABLED","dataType":"string"},{"name":"LOT_MERGE_ENABLED","dataType":"string"},{"name":"FINANCING_ALLOWED_FLAG","dataType":"string"},{"name":"EAM_ACT_NOTIFICATION_FLAG","dataType":"string"},{"name":"DUAL_UOM_CONTROL","dataType":"double"},{"name":"DUAL_UOM_DEVIATION_HIGH","dataType":"double"},{"name":"DUAL_UOM_DEVIATION_LOW","dataType":"double"},{"name":"CONTRACT_ITEM_TYPE_CODE","dataType":"string"},{"name":"SERV_REQ_ENABLED_CODE","dataType":"string"},{"name":"SERV_BILLING_ENABLED_FLAG","dataType":"string"},{"name":"PLANNED_INV_POINT_FLAG","dataType":"string"},{"name":"LOT_TRANSLATE_ENABLED","dataType":"string"},{"name":"DEFAULT_SO_SOURCE_TYPE","dataType":"string"},{"name":"CREATE_SUPPLY_FLAG","dataType":"string"},{"name":"LOT_SUBSTITUTION_ENABLED","dataType":"string"},{"name":"OBJECT_VERSION_NUMBER","dataType":"double"},{"name":"TRACKING_QUANTITY_IND","dataType":"string"},{"name":"ONT_PRICING_QTY_SOURCE","dataType":"string"},{"name":"VMI_MINIMUM_UNITS","dataType":"double"},{"name":"VMI_MAXIMUM_UNITS","dataType":"double"},{"name":"SO_AUTHORIZATION_FLAG","dataType":"double"},{"name":"CONSIGNED_FLAG","dataType":"double"},{"name":"ASN_AUTOEXPIRE_FLAG","dataType":"double"},{"name":"VMI_FORECAST_TYPE","dataType":"double"},{"name":"EXCLUDE_FROM_BUDGET_FLAG","dataType":"double"},{"name":"DRP_PLANNED_FLAG","dataType":"double"},{"name":"CRITICAL_COMPONENT_FLAG","dataType":"double"},{"name":"CONTINOUS_TRANSFER","dataType":"double"},{"name":"CONVERGENCE","dataType":"double"},{"name":"DIVERGENCE","dataType":"double"},{"name":"CHILD_LOT_FLAG","dataType":"string"},{"name":"CHILD_LOT_VALIDATION_FLAG","dataType":"string"},{"name":"COPY_LOT_ATTRIBUTE_FLAG","dataType":"string"},{"name":"GRADE_CONTROL_FLAG","dataType":"string"},{"name":"HAZARDOUS_MATERIAL_FLAG","dataType":"string"},{"name":"LOT_DIVISIBLE_FLAG","dataType":"string"},{"name":"PROCESS_COSTING_ENABLED_FLAG","dataType":"string"},{"name":"PROCESS_EXECUTION_ENABLED_FLAG","dataType":"string"},{"name":"PROCESS_QUALITY_ENABLED_FLAG","dataType":"string"},{"name":"PROCESS_SUPPLY_LOCATOR_ID","dataType":"double"},{"name":"PROCESS_SUPPLY_SUBINVENTORY","dataType":"string"},{"name":"RECIPE_ENABLED_FLAG","dataType":"string"},{"name":"PREPOSITION_POINT","dataType":"string"},{"name":"REPAIR_PROGRAM","dataType":"double"},{"name":"OUTSOURCED_ASSEMBLY","dataType":"double"},{"name":"GDSN_OUTBOUND_ENABLED_FLAG","dataType":"string"},{"name":"SERIAL_TAGGING_FLAG","dataType":"string"},{"name":"IB_ITEM_TRACKING_LEVEL","dataType":"string"},{"name":"MCC_CONTROL_CODE","dataType":"double"},{"name":"START_DATE_ACTIVE","dataType":"dateTime"},{"name":"END_DATE_ACTIVE","dataType":"dateTime"},{"name":"ORGANIZATION_CODE","dataType":"string"},{"name":"ITEM_DESCRIPTION","dataType":"string"},{"name":"USER_ITEM_TYPE","dataType":"string"},{"name":"BOM_ITEM_TYPE_DESCRIPTION","dataType":"string"},{"name":"COST_SOURCE_TYPE","dataType":"string"},{"name":"DEFAULT_BUYER","dataType":"string"},{"name":"ITEM_CATALOG_GROUP","dataType":"string"},{"name":"DEFAULT_RECV_SUBINVENTORY","dataType":"string"},{"name":"END_ASSEMBLY_PEGGING","dataType":"string"},{"name":"EFFECTIVITY_DATE","dataType":"dateTime"},{"name":"REVISION","dataType":"string"},{"name":"POWERBI_REFRESH_PARTITION","dataType":"dateTime"}]},{"$type":"LocalEntity","name":"XXREP_MFG_MTL_ITEM_ATTRIBUTES_V","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"XXREP_MFG_MTL_ITEM_ATTRIBUTES_V.csv"},"attributes":[{"name":"EXTRACT_DATE","dataType":"date"},{"name":"LOCAL_EXTRACT_DATE","dataType":"string"},{"name":"ORGANIZATION_CODE","dataType":"string"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"ORGANIZATION_ID","dataType":"double"},{"name":"ITEM_ORG_KEY_ID","dataType":"string"},{"name":"ITEM_ORG_KEY_CODE","dataType":"string"},{"name":"ITEM_NUMBER","dataType":"string"},{"name":"MRP_PLANNING_CODE","dataType":"string"},{"name":"ITEM_REVISION","dataType":"string"},{"name":"DESCRIPTION","dataType":"string"},{"name":"PRIMARY_UNIT_OF_MEASURE","dataType":"string"},{"name":"ITEM_STATUS","dataType":"string"},{"name":"ITEM_TYPE","dataType":"string"},{"name":"INVENTORY_ITEM_FLAG","dataType":"string"},{"name":"LOT_CONTROL_CODE","dataType":"string"},{"name":"SERIAL_CONTROL_CODE","dataType":"string"},{"name":"RECEIPT_ROUTING","dataType":"string"},{"name":"DEFAULT_BUYER","dataType":"string"},{"name":"BUYER_ID","dataType":"double"},{"name":"PLANNING_MAKE_BUY_CODE","dataType":"string"},{"name":"USD_RATE","dataType":"double"},{"name":"PLANNER_CODE","dataType":"string"},{"name":"PREPROCESSING_LEAD_TIME","dataType":"double"},{"name":"PROCESSING_LEAD_TIME","dataType":"double"},{"name":"POSTPROCESSING_LEAD_TIME","dataType":"double"},{"name":"LEAD_TIME_LOT_SIZE","dataType":"double"},{"name":"FIXED_LEAD_TIME","dataType":"double"},{"name":"VARIABLE_LEAD_TIME","dataType":"double"},{"name":"APOP","dataType":"string"},{"name":"LIST_PRICE_PER_UNIT","dataType":"double"},{"name":"ITEM_CREATION_DATE","dataType":"dateTime"},{"name":"COSTING_ENABLED_FLAG","dataType":"string"},{"name":"INVENTORY_ASSET_FLAG","dataType":"string"},{"name":"PLANNING_TIME_FENCE","dataType":"string"},{"name":"PLANNING_TIME_FENCE_DAYS","dataType":"double"},{"name":"DEMAND_TIME_FENCE","dataType":"string"},{"name":"DEMAND_TIME_FENCE_DAYS","dataType":"double"},{"name":"RELEASE_TIME_FENCE","dataType":"string"},{"name":"RELEASE_TIME_FENCE_DAYS","dataType":"double"},{"name":"ACCEPTABLE_EARLY_DAYS","dataType":"double"},{"name":"FIXED_DAYS_SUPPLY","dataType":"double"},{"name":"MINIMUM_ORDER_QUANTITY","dataType":"double"},{"name":"MAXIMUM_ORDER_QUANTITY","dataType":"double"},{"name":"MIN_MINMAX_QUANTITY","dataType":"double"},{"name":"MAX_MINMAX_QUANTITY","dataType":"double"},{"name":"FIXED_LOT_MULTIPLIER","dataType":"double"},{"name":"FIXED_ORDER_QUANTITY","dataType":"double"},{"name":"SOURCE_TYPE","dataType":"string"},{"name":"SOURCE_ORG","dataType":"string"},{"name":"CRITICAL_COMPONENT_FLAG","dataType":"string"},{"name":"INVENTORY_PLANNING_CODE","dataType":"string"},{"name":"WIP_SUPPLY_TYPE","dataType":"string"},{"name":"CURRENT_ITEM_ABC_CLASS","dataType":"string"},{"name":"WIP_SUPPLY_SUBINVENTORY","dataType":"string"},{"name":"WIP_SUPPLY_LOCATOR","dataType":"string"},{"name":"SUPPLY_CHAIN_STATUS","dataType":"string"},{"name":"ORG_PRODUCT","dataType":"string"},{"name":"MAS_PRODUCT","dataType":"string"},{"name":"PRODUCT_KEY","dataType":"string"},{"name":"COUNTRY_OF_ORIGIN","dataType":"string"},{"name":"SOURCING_COMMODITY","dataType":"string"},{"name":"PRODUCT_FAMILY","dataType":"string"},{"name":"COMMODITY","dataType":"string"},{"name":"SUPPLIER_FULL_LEAD_TIME","dataType":"string"},{"name":"SALES_AVAILABILITY","dataType":"string"},{"name":"PRIMARY_ORG","dataType":"string"},{"name":"SHIPMENT_PRIORITY","dataType":"string"},{"name":"REPLENISHMENT_METHOD","dataType":"string"},{"name":"SOURCING_RULE","dataType":"string"},{"name":"COST_CATEGORY","dataType":"string"},{"name":"LAST_PO_UNIT_PRICE","dataType":"double"},{"name":"LAST_PO_UNIT_PRICE_USD_BUDGET","dataType":"double"},{"name":"LAST_PO_CURRENCY","dataType":"string"},{"name":"APOP_CLASSIFICATION","dataType":"string"},{"name":"BASELINE_UNIT_PRICE","dataType":"double"},{"name":"LAST_PO_VENDOR_NAME","dataType":"string"},{"name":"ASSEMBLY_PRODUCT_CATEGORY","dataType":"string"},{"name":"PO_PROJECT","dataType":"double"},{"name":"CUM_MFG_LT","dataType":"double"},{"name":"CUM_TOTAL_LT","dataType":"double"},{"name":"DEFAULT_SHIPPING_ORG","dataType":"string"},{"name":"TRACK_INSTALL_BASE","dataType":"string"},{"name":"ATP_CHECK","dataType":"string"},{"name":"ATP_COMPONENTS","dataType":"string"}]}]}