{"name":"Target_Budget","description":"Target and Budget reference \n- nicht umbenennen !!! \nvon William / nur in seinem Dataset benutzt","version":"1.0","culture":"en-US","modifiedTime":"2021-09-17T09:38:24.1523047+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"Manufacturing_Expense_Budget":{"queryId":"a7efa6f8-16de-42e2-a00c-ac7e63d308bb","queryName":"Manufacturing_Expense_Budget","loadEnabled":true}},"document":"section Section1;\r\nshared Manufacturing_Expense_Budget = let\r\n  Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WMjIwMlTSUYIjU0sjUwMTYwWl2FgA\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"FC Year\" = _t, #\"GL Department Code\" = _t, #\"GL Entity Code\" = _t, #\"GL Account Code\" = _t, #\"Budget Amount USD\" = _t]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(Source, {{\"Budget Amount USD\", type number}, {\"FC Year\", Int64.Type}})\r\nin\r\n  #\"Changed column type\";\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"Manufacturing_Expense_Budget","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Manufacturing_Expense_Budget.csv"},"attributes":[{"name":"FC Year","dataType":"int64"},{"name":"GL Department Code","dataType":"string"},{"name":"GL Entity Code","dataType":"string"},{"name":"GL Account Code","dataType":"string"},{"name":"Budget Amount USD","dataType":"double"}],"partitions":[{"name":"Part001","refreshTime":"2021-06-23T10:24:47.0179592+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/fbb49749-e0b2-482b-a4b3-0972d2f3319b/Manufacturing_Expense_Budget.csv?snapshot=2021-06-23T10%3A24%3A46.9839401Z"}]}]}