{"name":"COHERENT_SNOWFLAKE_INVENTORY","description":"100522 für Serialized Inventory","version":"1.0","culture":"en-US","modifiedTime":"2022-05-18T07:24:37.1091313+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"XXCOH_MI_SERIAL_NUMBER_VIEW":{"queryId":"32751a81-837f-48c3-a6bc-ddf97bd9a8fb","queryName":"XXCOH_MI_SERIAL_NUMBER_VIEW","loadEnabled":true},"Org_Technical_BusinessUnit":{"queryId":"417ca8d1-7459-4683-9451-307cac01f0ed","queryName":"Org_Technical_BusinessUnit"}},"document":"section Section1;\r\nshared XXCOH_MI_SERIAL_NUMBER_VIEW = let\r\n  Source = Snowflake.Databases(\"mma12090.snowflakecomputing.com\", \"COMPUTE_REPORTING\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null]),\r\n  #\"Navigation 1\" = Source{[Name = \"PROD_DB\", Kind = \"Database\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"APPS\", Kind = \"Schema\"]}[Data],\r\n  #\"Navigation 3\" = #\"Navigation 2\"{[Name = \"XXCOH_MI_SERIAL_NUMBER_VIEW\", Kind = \"View\"]}[Data],\r\n  #\"Filtered rows\" = Table.SelectRows(#\"Navigation 3\", each [ORG_TECHNICAL_BUSINESS_UNIT] = Org_Technical_BusinessUnit)\r\nin\r\n  #\"Filtered rows\";\r\nshared Org_Technical_BusinessUnit = \"DPSS Germany\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type text];\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"XXCOH_MI_SERIAL_NUMBER_VIEW","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"XXCOH_MI_SERIAL_NUMBER_VIEW.csv"},"attributes":[{"name":"ASOF_DATE","dataType":"date"},{"name":"ASOF_DATE_DISP","dataType":"dateTime"},{"name":"DATA_SOURCE","dataType":"string"},{"name":"DATE_IN","dataType":"dateTime"},{"name":"ITEM_NUMBER","dataType":"string"},{"name":"ITEM_DESCRIPTION","dataType":"string"},{"name":"ITEM_REV","dataType":"string"},{"name":"OWNING_ORGANIZATION","dataType":"string"},{"name":"SUBINVENTORY","dataType":"string"},{"name":"LOC_SUB","dataType":"string"},{"name":"LOC_ROW","dataType":"string"},{"name":"LOC_RACK","dataType":"string"},{"name":"LOC_SHELF","dataType":"string"},{"name":"LOC_BIN","dataType":"string"},{"name":"QUANTITY","dataType":"double"},{"name":"LOT_NUMBER","dataType":"string"},{"name":"SERIAL_NUMBER","dataType":"string"},{"name":"PLANNER_CODE","dataType":"string"},{"name":"PLANNING_MAKE_BUY_CODE","dataType":"string"},{"name":"BUYER","dataType":"string"},{"name":"ITEM_COST","dataType":"double"},{"name":"ITEM_ADD_BACK_COST","dataType":"double"},{"name":"BASE_CURRENCY","dataType":"string"},{"name":"EXTENDED_VALUE","dataType":"double"},{"name":"EXTENDED_VALUE_USD","dataType":"double"},{"name":"PRIMARY_UOM_CODE","dataType":"string"},{"name":"MAX_MINMAX_QUANTITY","dataType":"double"},{"name":"MIN_MINMAX_QUANTITY","dataType":"double"},{"name":"MINIMUM_ORDER_QUANTITY","dataType":"double"},{"name":"FIXED_LOT_MULTIPLIER","dataType":"double"},{"name":"UNIT_COMPLETION_DATE","dataType":"dateTime"},{"name":"LOCATOR","dataType":"string"},{"name":"UOM","dataType":"string"},{"name":"MATERIAL_ENTITY","dataType":"string"},{"name":"MATERIAL_DEPT","dataType":"string"},{"name":"MATERIAL_ACCT","dataType":"string"},{"name":"AGILE_LIFE_PHASE","dataType":"string"},{"name":"BOM_ITEM_TYPE","dataType":"string"},{"name":"BOM_ENABLED_FLAG","dataType":"string"},{"name":"BUILD_IN_WIP_FLAG","dataType":"string"},{"name":"COSTING_ENABLED_FLAG","dataType":"string"},{"name":"CREATE_SUPPLY_FLAG","dataType":"string"},{"name":"CUSTOMER_ORDER_ENABLED_FLAG","dataType":"string"},{"name":"CUSTOMER_ORDER_FLAG","dataType":"string"},{"name":"CYCLE_COUNT_ENABLED_FLAG","dataType":"string"},{"name":"DEFAULT_SO_SOURCE_TYPE","dataType":"string"},{"name":"INSPECTION_REQUIRED_FLAG","dataType":"string"},{"name":"INVENTORY_ASSET_FLAG","dataType":"string"},{"name":"INVENTORY_ITEM_FLAG","dataType":"string"},{"name":"MUST_USE_APPROVED_VENDOR_FLAG","dataType":"string"},{"name":"PURCHASING_ENABLED_FLAG","dataType":"string"},{"name":"PURCHASING_ITEM_FLAG","dataType":"string"},{"name":"ITEM_TYPE_CODE","dataType":"string"},{"name":"ITEM_CATALOG_GROUP","dataType":"string"},{"name":"ITEM_TYPE","dataType":"string"},{"name":"REVISION_EFFECTIVITY_DATE","dataType":"dateTime"},{"name":"SUBINV_ASSET_FLAG","dataType":"string"},{"name":"TECHNICAL_BUSINESS_UNIT","dataType":"string"},{"name":"PRODUCT_FAMILY","dataType":"string"},{"name":"PRODUCT_LINE","dataType":"string"},{"name":"FORECAST_FIELD","dataType":"string"},{"name":"LEAD_TIME_CATEGORY","dataType":"string"},{"name":"COMMODITY","dataType":"string"},{"name":"PRIMARY_ORG","dataType":"string"},{"name":"ORG_TECHNICAL_BUSINESS_UNIT","dataType":"string"},{"name":"ORG_PRODUCT_FAMILY","dataType":"string"},{"name":"ORG_PRODUCT_LINE","dataType":"string"},{"name":"ORG_FORECAST_FIELD","dataType":"string"},{"name":"BACKUP_CATEGORY","dataType":"string"},{"name":"ITEM_CUSTOMER","dataType":"string"},{"name":"BCP_CODE","dataType":"string"},{"name":"ROYALTY","dataType":"string"},{"name":"PLANNING_GREEN_SUPPLY_STATUS","dataType":"string"},{"name":"PLANNING_ACTION","dataType":"string"},{"name":"PLANNING_FAMILY_UNIQUE","dataType":"string"},{"name":"MATERIAL_COST","dataType":"double"},{"name":"MATERIAL_OVERHEAD_COST","dataType":"double"},{"name":"RESOURCE_COST","dataType":"double"},{"name":"OVERHEAD_COST","dataType":"double"},{"name":"OUTSIDE_PROCESSING_COST","dataType":"double"},{"name":"LEGAL_ENTITY","dataType":"string"},{"name":"OPERATING_UNIT","dataType":"string"},{"name":"SET_OF_BOOKS","dataType":"string"},{"name":"ORG_LOCATION_CODE","dataType":"string"},{"name":"REGION_1","dataType":"string"},{"name":"TOWN_OR_CITY","dataType":"string"},{"name":"SITE","dataType":"string"},{"name":"REPORTING_TBU","dataType":"string"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"ORGANIZATION_ID","dataType":"double"},{"name":"COST_GROUP_ID","dataType":"double"},{"name":"LOCATOR_ID","dataType":"double"},{"name":"OPERATING_UNIT_ID","dataType":"double"},{"name":"LEGAL_ENTITY_ID","dataType":"double"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T05:03:17.6003064+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/1aa705cb-1e33-42ac-bb6b-4a6dfebf9967/XXCOH_MI_SERIAL_NUMBER_VIEW.csv?snapshot=2022-06-13T05%3A03%3A17.3485812Z"}]}]}