{"name":"COHREP_SITE_FIN_TRX1","description":"","version":"1.0","culture":"en-US","modifiedTime":"2021-03-10T07:05:26.1415583+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":true,"queriesMetadata":{"Item_Cost_Update_History":{"queryId":"f1610d72-ac98-404a-a225-015c27e77660","queryName":"Item_Cost_Update_History","queryGroupId":"root","loadEnabled":true},"M2":{"queryId":"c6197abf-984a-464e-a79b-752d9cdfc906","queryName":"M2","queryGroupId":"root","loadEnabled":true},"ENTITY":{"queryId":"8e4f8486-814e-40ec-83f4-24ee4776a103","queryName":"ENTITY"},"ORG":{"queryId":"96b46c27-c5ba-4c2e-8358-4e39b5f66e76","queryName":"ORG"},"EO_Reserve":{"queryId":"d816e8ac-d746-43bb-a7d6-0d7efd897839","queryName":"EO_Reserve","queryGroupId":"root","loadEnabled":true},"GL_Reserve":{"queryId":"bcd35366-2772-4f19-b713-47ae149bede0","queryName":"GL_Reserve","queryGroupId":"root","loadEnabled":true},"Corporate_FX_Rate":{"queryId":"e9a34f7f-281c-46f3-9ae8-4e3d2048d2e4","queryName":"Corporate_FX_Rate","queryGroupId":"root","loadEnabled":true},"Inventory_Value":{"queryId":"6115aa75-0701-4610-bd3a-06ec0bcc887d","queryName":"Inventory_Value","queryGroupId":"root","loadEnabled":true},"Inventory_Value_Weekly":{"queryId":"5989c5ee-0e96-47fa-b7c6-6421859d7bec","queryName":"Inventory_Value_Weekly","queryGroupId":"root","loadEnabled":true}},"document":"section Section1;\r\nshared Item_Cost_Update_History = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, \n  Query=\"\n  SELECT\n   SYSDATE EXTRACT_DATE,\n   MP.ORGANIZATION_CODE,\n   MSI.SEGMENT1 ITEM_NUMBER,\n   CSC.INVENTORY_ITEM_ID,\n   CSC.STANDARD_COST,\n   CSC.STANDARD_COST_REVISION_DATE,\n   CSC.COST_UPDATE_ID,\n   CSC.COST_UPDATE_ID||'_'||CSC.INVENTORY_ITEM_ID COST_UPDATE_KEY\nFROM\n   APPS.CST_STANDARD_COSTS CSC,\n   APPS.MTL_PARAMETERS MP,\n   INV.MTL_SYSTEM_ITEMS_B MSI \nWHERE\n   CSC.INVENTORY_ITEM_ID = MSI.INVENTORY_ITEM_ID \n   AND CSC.ORGANIZATION_ID = MSI.ORGANIZATION_ID \n   AND MP.ORGANIZATION_ID = MSI.ORGANIZATION_ID \n   AND MP.ORGANIZATION_CODE = '\"&ORG&\"'\n   ORDER BY COST_UPDATE_ID,CSC.INVENTORY_ITEM_ID\n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"EXTRACT_DATE\", \"Extract Date\"}, {\"ORGANIZATION_CODE\", \"Organization Code\"}, {\"ITEM_NUMBER\", \"Item Number\"}, {\"STANDARD_COST\", \"Standard Cost\"}, {\"STANDARD_COST_REVISION_DATE\", \"Standard Cost Revision Date\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared M2 = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, \n  Query=\"\n  SELECT\n    entity,\n    dept,\n    acct,\n    proj,\n    interco,\n    gl_period,\n    gp.end_date period_end_date,\n    item_number,\n    item_description,\n    cat_segment1,\n    cat_segment2,\n    cat_segment3,\n    transaction_source,\n    tb.inventory_item_id,\n    tb.organization_id,\n    vendor_id,\n    sales_service_code,\n    currency_code,\n    conversion_rate,\n    SUM(accounted_net)         accounted_net,\n    SUM(accounted_net_usd)     accounted_net_usd,\n    SUM(tran_qty)              transaction_quantity,\n    m20_tbu,\n    m20_pfc,\n    allocation_percent,\n    hfm_account,\n    hp_account,\n    hfm_icp,\n    hfm_function,\n    hfm_product,\n    hp_product,\n    hfm_product_group,\n    hp_spc_account,\n    alt_hfm_product,\n    alt_hfm_product_group,\n    alt_hp_product\nFROM\n    xxcoh.xxcoh_m2_report_tb tb,\n    gl.gl_periods gp\nWHERE\n    entity = '\"&ENTITY&\"'\n    AND tb.GL_PERIOD = gp.period_name\n    AND PERIOD_SET_NAME = 'COHR Calendar'\nGROUP BY\n    entity,\n    dept,\n    acct,\n    proj,\n    interco,\n    tbd,\n    gl_period,\n    gp.end_date,\n    item_number,\n    item_description,\n    cat_segment1,\n    cat_segment2,\n    cat_segment3,\n    transaction_source,\n    currency_code,\n    tb.inventory_item_id,\n    tb.organization_id,\n    set_of_books_id,\n    vendor_id,\n    sales_service_code,\n    conversion_rate,\n    m20_tbu,\n    m20_pfc,\n    allocation_percent,\n    hfm_account,\n    hp_account,\n    hfm_icp,\n    hfm_function,\n    hfm_product,\n    hp_product,\n    hfm_product_group,\n    hp_spc_account,\n    alt_hfm_product,\n    alt_hfm_product_group,\n    alt_hp_product\n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"ENTITY\", \"Entity\"}, {\"DEPT\", \"Department\"}, {\"ACCT\", \"Account\"}, {\"PROJ\", \"Project\"}, {\"INTERCO\", \"Inter Company\"}, {\"ITEM_NUMBER\", \"Item Number\"}, {\"ITEM_DESCRIPTION\", \"Description\"}, {\"TRANSACTION_QUANTITY\", \"Transaction Quantity\"}, {\"TRANSACTION_SOURCE\", \"Transaction Source\"}, {\"CURRENCY_CODE\", \"Currency\"}, {\"SALES_SERVICE_CODE\", \"Sales Service Code\"}, {\"ACCOUNTED_NET\", \"Accounted Net\"}, {\"ACCOUNTED_NET_USD\", \"Accounted Net USD\"}, {\"GL_PERIOD\", \"GL Period\"}, {\"PERIOD_END_DATE\", \"Period End Date\"}, {\"M20_TBU\", \"M20 TBU\"}, {\"M20_PFC\", \"M20 PFC\"}, {\"ALLOCATION_PERCENT\", \"Allocation Percent\"}, {\"HFM_ACCOUNT\", \"HFM Account\"}, {\"HP_ACCOUNT\", \"HP Account\"}, {\"HFM_ICP\", \"HFM ICP\"}, {\"HFM_FUNCTION\", \"HFM Function\"}, {\"HFM_PRODUCT\", \"HFM Product\"}, {\"HP_PRODUCT\", \"HP Product\"}, {\"HFM_PRODUCT_GROUP\", \"HFM Product Group\"}, {\"HP_SPC_ACCOUNT\", \"HP SPC Account\"}, {\"CAT_SEGMENT1\", \"Item TBU\"}, {\"CAT_SEGMENT2\", \"Item Product Family\"}, {\"CAT_SEGMENT3\", \"Item Product Line\"}, {\"ALT_HFM_PRODUCT\", \" Alternate HFM Product\"}, {\"ALT_HFM_PRODUCT_GROUP\", \"Alternate HFM Product Group\"}, {\"ALT_HP_PRODUCT\", \"Alternate HP Product\"}}),\r\n  #\"Renamed columns 1\" = Table.RenameColumns(#\"Renamed columns\", {{\" Alternate HFM Product\", \"Alternate HFM Product\"}})\r\nin\r\n  #\"Renamed columns 1\";\r\nshared ENTITY = let\r\n  ENTITY = \"660\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type text]\r\nin\r\n  ENTITY;\r\nshared ORG = let\r\n  ORG = \"LDP\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type text]\r\nin\r\n  ORG;\r\nshared EO_Reserve = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, Query=\"\n  SELECT\n   XRH.HEADER_STATUS,\n   XRH.ORGANIZATION_ID,\n   XRH.ORGANIZATION_CODE,\n   XRH.PLAN_NAME,\n   XRL.INVENTORY_ITEM_ID,\n   XRL.LINE_STATUS,\n   XRL.ITEM_NUMBER,\n   XRL.FINAL_RESERVE_QUANTITY,\n   XRL.FINAL_RESERVE_EXT_VALUE,\n   XRL.FINAL_RESERVE_TRF_EXT_VALUE,\n   XRL.FINAL_RESERVE_CATEGORY,\n   XRL.FINAL_RESERVE_RATE,\n   XRL.FINAL_RESERVE_TRF_AMOUNT,\n   XRL.FINAL_RESERVE_AMOUNT_USD,\n   XRL.FINAL_TAKEN_FROM,\n   XRL.FINAL_FINANCE_APPROVE_DATE,\n   XRL.ORGANIZATION_CATEGORY,\n   XRL.RESERVE_DEPARTMENT,\n   XRL.RESERVE_ACCOUNT,\n   XRL.TBU,\n   XRL.PRODUCT_FAMILY,\n   XRL.PRODUCT_LINE,\n   XRL.ORG_TBU,\n   XRL.ORG_PRODUCT_FAMILY,\n   XRL.ORG_PRODUCT_LINE,\n   XRL.PLANNER_CODE,\n   XRL.FIN_TBU,\n   XRL.FIN_PRODUCT_FAMILY,\n   XRL.PERIOD_NAME \nFROM\n   APPS.XXCOH_RSV_HEADERS XRH,\n   APPS.XXCOH_RSV_LINES XRL \nWHERE\n   1 = 1 \n   AND XRH.RESERVE_HEADER_ID = XRL.RESERVE_HEADER_ID \n   AND XRH.ORGANIZATION_CODE = '\"&ORG&\"'\n   \"\n   , CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"HEADER_STATUS\", \"Header Status\"}, {\"ORGANIZATION_CODE\", \"Organization Code\"}, {\"PERIOD_NAME\", \"GL Period Name\"}, {\"PLAN_NAME\", \"Plan Name\"}, {\"LINE_STATUS\", \"Line Status\"}, {\"ITEM_NUMBER\", \"Item Number\"}, {\"FINAL_RESERVE_QUANTITY\", \"Final Reserve Quantity\"}, {\"FINAL_RESERVE_EXT_VALUE\", \"Final Reserve Ext Value\"}, {\"FINAL_RESERVE_TRF_EXT_VALUE\", \"Final Reserve Trf Value\"}, {\"FINAL_RESERVE_CATEGORY\", \"Final Reserve Category\"}, {\"FINAL_RESERVE_RATE\", \"Final Reserve Rate\"}, {\"FINAL_RESERVE_TRF_AMOUNT\", \"Final Reserve Trf Amount\"}, {\"FINAL_RESERVE_AMOUNT_USD\", \"Final Reserve Amount USD\"}, {\"FINAL_TAKEN_FROM\", \"Final Taken From\"}, {\"FINAL_FINANCE_APPROVE_DATE\", \"Final Finance Approve Date\"}, {\"ORGANIZATION_CATEGORY\", \"Organization Category\"}, {\"RESERVE_DEPARTMENT\", \"Reserve Department\"}, {\"RESERVE_ACCOUNT\", \"Reserve Account\"}, {\"PRODUCT_FAMILY\", \"Product Family\"}, {\"PRODUCT_LINE\", \"Product Line\"}, {\"ORG_TBU\", \"ORG TBU\"}, {\"ORG_PRODUCT_FAMILY\", \"ORG Product Family\"}, {\"ORG_PRODUCT_LINE\", \"ORG Product Line\"}, {\"PLANNER_CODE\", \"Planner Code\"}, {\"FIN_TBU\", \"FIN TBU\"}, {\"FIN_PRODUCT_FAMILY\", \"FIN Product Family\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared GL_Reserve = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, Query=\"\n  SELECT\n   sysdate EXTRACT_DATE,\n   GJH.JE_HEADER_ID,\n   GCC.SEGMENT1,\n   GCC.SEGMENT2,\n   GCC.SEGMENT3,\n   GCC.SEGMENT4,\n   GCC.SEGMENT5,\n   GCC.CODE_COMBINATION_ID,\n   GJH.LEDGER_ID,\n   GJH.JE_CATEGORY,\n   GJH.JE_SOURCE,\n   GJH.CURRENCY_CODE,\n   GJH.POSTED_DATE,\n   GJL.EFFECTIVE_DATE,\n   GJL.PERIOD_NAME,\n   GJL.ACCOUNTED_DR,\n   GJL.ACCOUNTED_CR,\n   nvl(GJL.ACCOUNTED_DR,0) - nvl(GJL.ACCOUNTED_CR,0) ACCOUNTED_NET,\n   GJL.DESCRIPTION,\n   GJL.ATTRIBUTE1,\n   GJL.ATTRIBUTE2,\n   GJL.ATTRIBUTE3,\n   GJL.ATTRIBUTE4\nFROM\n   APPS.GL_CODE_COMBINATIONS GCC,\n   APPS.GL_PERIOD_STATUSES GPS,\n   APPS.GL_LEDGERS GL,\n   APPS.GL_JE_LINES GJL,\n   APPS.GL_JE_HEADERS GJH,\n   APPS.ORG_ORGANIZATION_DEFINITIONS OOD \nWHERE\n   ORGANIZATION_CODE =  '\"&ORG&\"' \n   AND OOD.SET_OF_BOOKS_ID = GL.LEDGER_ID \n   AND GL.LEDGER_ID = GJH.LEDGER_ID \n   AND GPS.LEDGER_ID = 1 \n   AND GPS.APPLICATION_ID = 101 \n   AND GJH.STATUS = 'P' \n   AND GJH.JE_HEADER_ID = GJL.JE_HEADER_ID \n   AND GJL.CODE_COMBINATION_ID = GCC.CODE_COMBINATION_ID \n   AND GCC.SEGMENT1 = '\"&ENTITY&\"' \n   AND GCC.SEGMENT3 in ( \n    '05500',\n    '05505',\n    '05510',\n    '05540',\n    '05530',\n    '05550')\n   \"\n   , CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"EXTRACT_DATE\", \"Extract Date\"}, {\"JE_CATEGORY\", \"JE Category\"}, {\"JE_SOURCE\", \"JE Source\"}, {\"CURRENCY_CODE\", \"Currency Code\"}, {\"POSTED_DATE\", \"Posted Date\"}, {\"EFFECTIVE_DATE\", \"Effective Date\"}, {\"PERIOD_NAME\", \"GL Period Name\"}, {\"ACCOUNTED_DR\", \"Accounted Dr\"}, {\"ACCOUNTED_CR\", \"Accounted Cr\"}, {\"ACCOUNTED_NET\", \"Accounted Net\"}, {\"DESCRIPTION\", \"JE Description\"}, {\"SEGMENT1\", \"Entity\"}, {\"SEGMENT2\", \"Department\"}, {\"SEGMENT3\", \"Account\"}, {\"SEGMENT4\", \"Project\"}, {\"SEGMENT5\", \"Intercompany\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Corporate_FX_Rate = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, \n  Query=\"\n SELECT\n    from_currency,\n    to_currency,\n    gdr.conversion_date,\n    gdr.conversion_type,\n    gdr.conversion_Rate usd_rate,\n    CASE\n        WHEN sob.currency_code = from_currency THEN\n            'Yes'\n        ELSE\n            'No'\n    END from_base_currency\nFROM\n    apps.gl_daily_rates_v                gdr,\n    apps.org_organization_definitions    ood,\n    apps.gl_sets_of_books                sob\nWHERE\n        conversion_type = 'Corporate'\n    AND to_currency = 'USD'\n    AND ood.set_of_books_id = sob.set_of_books_id\n    AND ood.organization_code = '\"&ORG&\"'\n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"FROM_CURRENCY\", \"From Currency\"}, {\"TO_CURRENCY\", \"To Currency\"}, {\"CONVERSION_DATE\", \"Conversion Date\"}, {\"CONVERSION_TYPE\", \"Conversion Type\"}, {\"USD_RATE\", \"USD Rate\"}, {\"FROM_BASE_CURRENCY\", \"From Base Currency Flag\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Inventory_Value = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, \n  Query=\"\n  SELECT\n   INVV.GL_PERIOD,\n   INVV.INVENTORY_ITEM_ID,\n   INVV.ITEM_NUMBER,\n   INVV.ITEM_DESC,\n   NVL(INVV.ORG_CATEGORY_ID,INVV.CATEGORY_ID) KEY_CATEGORY_ID,\n   INVV.ITEM_TBU,\n   INVV.ITEM_PRODUCT_FAMILY,\n   INVV.SOURCE_TYPE,\n   INVV.ITEM_COST,\n   INVV.COST_INCURRED,\n   INVV.COST_RELIEVED,\n   INVV.COST_VARIANCE,\n   INVV.JE_SOURCE_CATEGORY,\n   INVV.OPERATIONS_REPORTING,\n   INVV.CS_DEMAND_SOURCE,\n   INVV.CS_SUPPLY_SOURCE,\n   INVV.EXCLUDE_FLAG,\n   INVV.EXCLUDE_COMMENT,\n   INVV.WIP_CLASS,\n   INVV.WIP_CLASS_CODE,\n   INVV.ITEM_TYPE,\n   INVV.PLANNER_CODE,\n   SUBSTR(INVV.ABC_CLASS, 1, 1)ABC_CLASS,\n   INVV.ITEM_STATUS,\n   INVV.INV_STATUS,\n   INVV.SUBINVENTORY_CODE,\n   INVV.ACCOUNT,\n   INVV.INV_QUANTITY,\n   INVV.INV_VALUE,\n   INVV.INV_VALUE_USD,\n   INVV.FISCAL_PERIOD_ID,\n   INVV.FISCAL_WEEK_ID,\n   INVV.FISCAL_WEEK,\n   (INVV.FISCAL_YEAR * 100 + INVV.FISCAL_WEEK_ID) WEEK_SERIES,\n   INVV.SCENARIO,\n   INVV.FISCAL_MONTH,\n   INVV.MATERIAL_COST,\n   INVV.MATERIAL_OVERHEAD_COST,\n   INVV.OUTSIDE_PROCESSING_COST,\n   INVV.OVERHEAD_COST,\n   INVV.RESOURCE_COST,\n   INVV.WIP_JOB_ID,\n   INVV.WIP_JOB_NO,\n   ROUND(INVV.CURRENCY_RATE, 4) USD_RATE,\n   INVV.FIN_PRODUCT_GROUP,\n   INVV.FIN_PRODUCT_FAMILY,\n   INVV.FIN_FORECAST_FIELD,\n   INVV.FIN_PRODUCT_SEGMENT,\n   INVV.FIN_PRODUCT_LINE,\n   INVV.CREATION_DATE\nFROM\n   XXFACTS.XX_INVVALUE_FACT INVV,\n   APPS.MTL_PARAMETERS MP\nWHERE\n   MP.ORGANIZATION_ID = INVV.INV_ORG_ID \n   AND MP.ORGANIZATION_CODE = '\"&ORG&\"'\n   AND INVV.FISCAL_YEAR >= (\n        SELECT\n            period_year - 5\n        FROM\n            gl.gl_periods gp\n        WHERE\n            trunc(sysdate) BETWEEN gp.start_date AND gp.end_date\n            AND period_set_name = 'COHR Calendar'\n    )\n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"GL_PERIOD\", \"Period Name\"}, {\"ITEM_NUMBER\", \"Item Number\"}, {\"ITEM_DESC\", \"Item Description\"}, {\"ITEM_TBU\", \"Item TBU\"}, {\"ITEM_PRODUCT_FAMILY\", \"Item Product Family\"}, {\"SOURCE_TYPE\", \"Value Source\"}, {\"ITEM_COST\", \"Item Cost\"}, {\"COST_INCURRED\", \"Cost Incurred\"}, {\"COST_RELIEVED\", \"Cost Relieved\"}, {\"COST_VARIANCE\", \"Cost Variance\"}, {\"JE_SOURCE_CATEGORY\", \"JE Source Category\"}, {\"OPERATIONS_REPORTING\", \"Operations Reporting\"}, {\"CS_DEMAND_SOURCE\", \"Demand Source\"}, {\"CS_SUPPLY_SOURCE\", \"Supply Source\"}, {\"EXCLUDE_FLAG\", \"Exclude Flag\"}, {\"EXCLUDE_COMMENT\", \"Exclude Comment\"}, {\"WIP_CLASS\", \"WIP Class\"}, {\"WIP_CLASS_CODE\", \"WIP Class Code\"}, {\"ITEM_TYPE\", \"Item Type\"}, {\"PLANNER_CODE\", \"Planner Code\"}, {\"ABC_CLASS\", \"ABC Class\"}, {\"ITEM_STATUS\", \"Item Status\"}, {\"INV_STATUS\", \"Supply Chain Status\"}, {\"SUBINVENTORY_CODE\", \"Subinventory\"}, {\"ACCOUNT\", \"Account Code\"}, {\"INV_QUANTITY\", \"Inventory Quantity\"}, {\"INV_VALUE\", \"Inventory Value\"}, {\"INV_VALUE_USD\", \"Inventory Value USD\"}, {\"WIP_JOB_NO\", \"WIP Job Number\"}, {\"SCENARIO\", \"Scenario\"}, {\"MATERIAL_COST\", \"Material Cost\"}, {\"MATERIAL_OVERHEAD_COST\", \"Material Overhead Cost\"}, {\"OUTSIDE_PROCESSING_COST\", \"OSP Cost\"}, {\"RESOURCE_COST\", \"Resource Cost\"}, {\"OVERHEAD_COST\", \"Overhead Cost\"}, {\"USD_RATE\", \"USD Rate\"}, {\"FIN_PRODUCT_GROUP\", \"Finance Product Group\"}, {\"FIN_PRODUCT_FAMILY\", \"Finance Product Family\"}, {\"FIN_FORECAST_FIELD\", \"Finance Forecast Field\"}, {\"FIN_PRODUCT_SEGMENT\", \"Finance Product Segment\"}, {\"FIN_PRODUCT_LINE\", \"Finance Product Line\"}, {\"CREATION_DATE\", \"Creation Date\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Inventory_Value_Weekly = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, \n  Query=\"\n  SELECT\n   INVV.GL_PERIOD,\n   INVV.INVENTORY_ITEM_ID,\n   INVV.ITEM_NUMBER,\n   INVV.ITEM_DESC,\n   NVL(INVV.ORG_CATEGORY_ID,INVV.CATEGORY_ID) KEY_CATEGORY_ID,\n   INVV.ITEM_TBU,\n   INVV.ITEM_PRODUCT_FAMILY,\n   INVV.SOURCE_TYPE,\n   INVV.ITEM_COST,\n   INVV.COST_INCURRED,\n   INVV.COST_RELIEVED,\n   INVV.COST_VARIANCE,\n   INVV.JE_SOURCE_CATEGORY,\n   INVV.OPERATIONS_REPORTING,\n   INVV.CS_DEMAND_SOURCE,\n   INVV.CS_SUPPLY_SOURCE,\n   INVV.EXCLUDE_FLAG,\n   INVV.EXCLUDE_COMMENT,\n   INVV.WIP_CLASS,\n   INVV.WIP_CLASS_CODE,\n   INVV.ITEM_TYPE,\n   INVV.PLANNER_CODE,\n   SUBSTR(INVV.ABC_CLASS, 1, 1)ABC_CLASS,\n   INVV.ITEM_STATUS,\n   INVV.INV_STATUS,\n   INVV.SUBINVENTORY_CODE,\n   INVV.ACCOUNT,\n   INVV.INV_QUANTITY,\n   INVV.INV_VALUE,\n   INVV.INV_VALUE_USD,\n   INVV.FISCAL_PERIOD_ID,\n   INVV.FISCAL_WEEK_ID,\n   INVV.FISCAL_WEEK,\n   (INVV.FISCAL_YEAR * 100 + INVV.FISCAL_WEEK_ID) WEEK_SERIES,\n   INVV.SCENARIO,\n   INVV.FISCAL_MONTH,\n   INVV.MATERIAL_COST,\n   INVV.MATERIAL_OVERHEAD_COST,\n   INVV.OUTSIDE_PROCESSING_COST,\n   INVV.OVERHEAD_COST,\n   INVV.RESOURCE_COST,\n   INVV.WIP_JOB_ID,\n   INVV.WIP_JOB_NO,\n   ROUND(INVV.CURRENCY_RATE, 4) USD_RATE,\n   INVV.FIN_PRODUCT_GROUP,\n   INVV.FIN_PRODUCT_FAMILY,\n   INVV.FIN_FORECAST_FIELD,\n   INVV.FIN_PRODUCT_SEGMENT,\n   INVV.FIN_PRODUCT_LINE,\n   INVV.CREATION_DATE\nFROM\n   XXFACTS.XX_INVVALUE_FACT INVV,\n   APPS.MTL_PARAMETERS MP\nWHERE\n   MP.ORGANIZATION_ID = INVV.INV_ORG_ID \n   AND MP.ORGANIZATION_CODE = '\"&ORG&\"'\n   AND INVV.FISCAL_YEAR >= (\n        SELECT\n            period_year - 3\n        FROM\n            gl.gl_periods gp\n        WHERE\n            trunc(sysdate) BETWEEN gp.start_date AND gp.end_date\n            AND period_set_name = 'COHR Calendar'\n    )\n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"GL_PERIOD\", \"Period Name\"}, {\"ITEM_NUMBER\", \"Item Number\"}, {\"ITEM_DESC\", \"Item Description\"}, {\"ITEM_TBU\", \"Item TBU\"}, {\"ITEM_PRODUCT_FAMILY\", \"Item Product Family\"}, {\"SOURCE_TYPE\", \"Value Source\"}, {\"ITEM_COST\", \"Item Cost\"}, {\"COST_INCURRED\", \"Cost Incurred\"}, {\"COST_RELIEVED\", \"Cost Relieved\"}, {\"COST_VARIANCE\", \"Cost Variance\"}, {\"JE_SOURCE_CATEGORY\", \"JE Source Category\"}, {\"OPERATIONS_REPORTING\", \"Operations Reporting\"}, {\"CS_DEMAND_SOURCE\", \"Demand Source\"}, {\"CS_SUPPLY_SOURCE\", \"Supply Source\"}, {\"EXCLUDE_FLAG\", \"Exclude Flag\"}, {\"EXCLUDE_COMMENT\", \"Exclude Comment\"}, {\"WIP_CLASS\", \"WIP Class\"}, {\"WIP_CLASS_CODE\", \"WIP Class Code\"}, {\"ITEM_TYPE\", \"Item Type\"}, {\"PLANNER_CODE\", \"Planner Code\"}, {\"ABC_CLASS\", \"ABC Class\"}, {\"ITEM_STATUS\", \"Item Status\"}, {\"INV_STATUS\", \"Supply Chain Status\"}, {\"SUBINVENTORY_CODE\", \"Subinventory\"}, {\"ACCOUNT\", \"Account Code\"}, {\"INV_QUANTITY\", \"Inventory Quantity\"}, {\"INV_VALUE\", \"Inventory Value\"}, {\"INV_VALUE_USD\", \"Inventory Value USD\"}, {\"WIP_JOB_NO\", \"WIP Job Number\"}, {\"SCENARIO\", \"Scenario\"}, {\"MATERIAL_COST\", \"Material Cost\"}, {\"MATERIAL_OVERHEAD_COST\", \"Material Overhead Cost\"}, {\"OUTSIDE_PROCESSING_COST\", \"OSP Cost\"}, {\"RESOURCE_COST\", \"Resource Cost\"}, {\"OVERHEAD_COST\", \"Overhead Cost\"}, {\"USD_RATE\", \"USD Rate\"}, {\"FIN_PRODUCT_GROUP\", \"Finance Product Group\"}, {\"FIN_PRODUCT_FAMILY\", \"Finance Product Family\"}, {\"FIN_FORECAST_FIELD\", \"Finance Forecast Field\"}, {\"FIN_PRODUCT_SEGMENT\", \"Finance Product Segment\"}, {\"FIN_PRODUCT_LINE\", \"Finance Product Line\"}, {\"CREATION_DATE\", \"Creation Date\"}})\r\nin\r\n  #\"Renamed columns\";\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"Item_Cost_Update_History","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Item_Cost_Update_History.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Organization Code","dataType":"string"},{"name":"Item Number","dataType":"string"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"Standard Cost","dataType":"double"},{"name":"Standard Cost Revision Date","dataType":"dateTime"},{"name":"COST_UPDATE_ID","dataType":"double"},{"name":"COST_UPDATE_KEY","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-13T06:30:50.6637833+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/b41c844f-78b3-4b28-a275-29ffb69c9a32/Item_Cost_Update_History.csv?snapshot=2022-06-13T06%3A30%3A50.6441948Z"}]},{"$type":"LocalEntity","name":"M2","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"M2.csv"},"attributes":[{"name":"Entity","dataType":"string"},{"name":"Department","dataType":"string"},{"name":"Account","dataType":"string"},{"name":"Project","dataType":"string"},{"name":"Inter Company","dataType":"string"},{"name":"GL Period","dataType":"string"},{"name":"Period End Date","dataType":"dateTime"},{"name":"Item Number","dataType":"string"},{"name":"Description","dataType":"string"},{"name":"Item TBU","dataType":"string"},{"name":"Item Product Family","dataType":"string"},{"name":"Item Product Line","dataType":"string"},{"name":"Transaction Source","dataType":"string"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"ORGANIZATION_ID","dataType":"double"},{"name":"VENDOR_ID","dataType":"double"},{"name":"Sales Service Code","dataType":"string"},{"name":"Currency","dataType":"string"},{"name":"CONVERSION_RATE","dataType":"double"},{"name":"Accounted Net","dataType":"double"},{"name":"Accounted Net USD","dataType":"double"},{"name":"Transaction Quantity","dataType":"double"},{"name":"M20 TBU","dataType":"string"},{"name":"M20 PFC","dataType":"string"},{"name":"Allocation Percent","dataType":"double"},{"name":"HFM Account","dataType":"string"},{"name":"HP Account","dataType":"string"},{"name":"HFM ICP","dataType":"string"},{"name":"HFM Function","dataType":"string"},{"name":"HFM Product","dataType":"string"},{"name":"HP Product","dataType":"string"},{"name":"HFM Product Group","dataType":"string"},{"name":"HP SPC Account","dataType":"string"},{"name":"Alternate HFM Product","dataType":"string"},{"name":"Alternate HFM Product Group","dataType":"string"},{"name":"Alternate HP Product","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-13T06:33:34.4711064+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/b41c844f-78b3-4b28-a275-29ffb69c9a32/M2.csv?snapshot=2022-06-13T06%3A33%3A34.4568912Z"}]},{"$type":"LocalEntity","name":"EO_Reserve","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"EO_Reserve.csv"},"attributes":[{"name":"Header Status","dataType":"string"},{"name":"ORGANIZATION_ID","dataType":"double"},{"name":"Organization Code","dataType":"string"},{"name":"Plan Name","dataType":"string"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"Line Status","dataType":"string"},{"name":"Item Number","dataType":"string"},{"name":"Final Reserve Quantity","dataType":"double"},{"name":"Final Reserve Ext Value","dataType":"double"},{"name":"Final Reserve Trf Value","dataType":"double"},{"name":"Final Reserve Category","dataType":"string"},{"name":"Final Reserve Rate","dataType":"double"},{"name":"Final Reserve Trf Amount","dataType":"double"},{"name":"Final Reserve Amount USD","dataType":"double"},{"name":"Final Taken From","dataType":"string"},{"name":"Final Finance Approve Date","dataType":"dateTime"},{"name":"Organization Category","dataType":"string"},{"name":"Reserve Department","dataType":"string"},{"name":"Reserve Account","dataType":"string"},{"name":"TBU","dataType":"string"},{"name":"Product Family","dataType":"string"},{"name":"Product Line","dataType":"string"},{"name":"ORG TBU","dataType":"string"},{"name":"ORG Product Family","dataType":"string"},{"name":"ORG Product Line","dataType":"string"},{"name":"Planner Code","dataType":"string"},{"name":"FIN TBU","dataType":"string"},{"name":"FIN Product Family","dataType":"string"},{"name":"GL Period Name","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-13T06:30:34.7127735+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/b41c844f-78b3-4b28-a275-29ffb69c9a32/EO_Reserve.csv?snapshot=2022-06-13T06%3A30%3A34.6658876Z"}]},{"$type":"LocalEntity","name":"GL_Reserve","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"GL_Reserve.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"JE_HEADER_ID","dataType":"int64"},{"name":"Entity","dataType":"string"},{"name":"Department","dataType":"string"},{"name":"Account","dataType":"string"},{"name":"Project","dataType":"string"},{"name":"Intercompany","dataType":"string"},{"name":"CODE_COMBINATION_ID","dataType":"int64"},{"name":"LEDGER_ID","dataType":"int64"},{"name":"JE Category","dataType":"string"},{"name":"JE Source","dataType":"string"},{"name":"Currency Code","dataType":"string"},{"name":"Posted Date","dataType":"dateTime"},{"name":"Effective Date","dataType":"dateTime"},{"name":"GL Period Name","dataType":"string"},{"name":"Accounted Dr","dataType":"double"},{"name":"Accounted Cr","dataType":"double"},{"name":"Accounted Net","dataType":"double"},{"name":"JE Description","dataType":"string"},{"name":"ATTRIBUTE1","dataType":"string"},{"name":"ATTRIBUTE2","dataType":"string"},{"name":"ATTRIBUTE3","dataType":"string"},{"name":"ATTRIBUTE4","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-13T06:30:39.5984623+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/b41c844f-78b3-4b28-a275-29ffb69c9a32/GL_Reserve.csv?snapshot=2022-06-13T06%3A30%3A39.5749096Z"}]},{"$type":"LocalEntity","name":"Corporate_FX_Rate","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Corporate_FX_Rate.csv"},"attributes":[{"name":"From Currency","dataType":"string"},{"name":"To Currency","dataType":"string"},{"name":"Conversion Date","dataType":"dateTime"},{"name":"Conversion Type","dataType":"string"},{"name":"USD Rate","dataType":"double"},{"name":"From Base Currency Flag","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-13T06:30:14.9463055+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/b41c844f-78b3-4b28-a275-29ffb69c9a32/Corporate_FX_Rate.csv?snapshot=2022-06-13T06%3A30%3A14.7709592Z"}]},{"$type":"LocalEntity","name":"Inventory_Value","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Inventory_Value.csv"},"attributes":[{"name":"Period Name","dataType":"string"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"Item Number","dataType":"string"},{"name":"Item Description","dataType":"string"},{"name":"KEY_CATEGORY_ID","dataType":"double"},{"name":"Item TBU","dataType":"string"},{"name":"Item Product Family","dataType":"string"},{"name":"Value Source","dataType":"string"},{"name":"Item Cost","dataType":"double"},{"name":"Cost Incurred","dataType":"double"},{"name":"Cost Relieved","dataType":"double"},{"name":"Cost Variance","dataType":"double"},{"name":"JE Source Category","dataType":"string"},{"name":"Operations Reporting","dataType":"string"},{"name":"Demand Source","dataType":"string"},{"name":"Supply Source","dataType":"string"},{"name":"Exclude Flag","dataType":"string"},{"name":"Exclude Comment","dataType":"string"},{"name":"WIP Class","dataType":"string"},{"name":"WIP Class Code","dataType":"string"},{"name":"Item Type","dataType":"string"},{"name":"Planner Code","dataType":"string"},{"name":"ABC Class","dataType":"string"},{"name":"Item Status","dataType":"string"},{"name":"Supply Chain Status","dataType":"string"},{"name":"Subinventory","dataType":"string"},{"name":"Account Code","dataType":"string"},{"name":"Inventory Quantity","dataType":"double"},{"name":"Inventory Value","dataType":"double"},{"name":"Inventory Value USD","dataType":"double"},{"name":"FISCAL_PERIOD_ID","dataType":"double"},{"name":"FISCAL_WEEK_ID","dataType":"double"},{"name":"FISCAL_WEEK","dataType":"string"},{"name":"WEEK_SERIES","dataType":"double"},{"name":"Scenario","dataType":"string"},{"name":"FISCAL_MONTH","dataType":"string"},{"name":"Material Cost","dataType":"double"},{"name":"Material Overhead Cost","dataType":"double"},{"name":"OSP Cost","dataType":"double"},{"name":"Overhead Cost","dataType":"double"},{"name":"Resource Cost","dataType":"double"},{"name":"WIP_JOB_ID","dataType":"double"},{"name":"WIP Job Number","dataType":"string"},{"name":"USD Rate","dataType":"double"},{"name":"Finance Product Group","dataType":"string"},{"name":"Finance Product Family","dataType":"string"},{"name":"Finance Forecast Field","dataType":"string"},{"name":"Finance Product Segment","dataType":"string"},{"name":"Finance Product Line","dataType":"string"},{"name":"Creation Date","dataType":"dateTime"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-13T06:32:37.6538634+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/b41c844f-78b3-4b28-a275-29ffb69c9a32/Inventory_Value.csv?snapshot=2022-06-13T06%3A32%3A37.6393217Z"}]},{"$type":"LocalEntity","name":"Inventory_Value_Weekly","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Inventory_Value_Weekly.csv"},"attributes":[{"name":"Period Name","dataType":"string"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"Item Number","dataType":"string"},{"name":"Item Description","dataType":"string"},{"name":"KEY_CATEGORY_ID","dataType":"double"},{"name":"Item TBU","dataType":"string"},{"name":"Item Product Family","dataType":"string"},{"name":"Value Source","dataType":"string"},{"name":"Item Cost","dataType":"double"},{"name":"Cost Incurred","dataType":"double"},{"name":"Cost Relieved","dataType":"double"},{"name":"Cost Variance","dataType":"double"},{"name":"JE Source Category","dataType":"string"},{"name":"Operations Reporting","dataType":"string"},{"name":"Demand Source","dataType":"string"},{"name":"Supply Source","dataType":"string"},{"name":"Exclude Flag","dataType":"string"},{"name":"Exclude Comment","dataType":"string"},{"name":"WIP Class","dataType":"string"},{"name":"WIP Class Code","dataType":"string"},{"name":"Item Type","dataType":"string"},{"name":"Planner Code","dataType":"string"},{"name":"ABC Class","dataType":"string"},{"name":"Item Status","dataType":"string"},{"name":"Supply Chain Status","dataType":"string"},{"name":"Subinventory","dataType":"string"},{"name":"Account Code","dataType":"string"},{"name":"Inventory Quantity","dataType":"double"},{"name":"Inventory Value","dataType":"double"},{"name":"Inventory Value USD","dataType":"double"},{"name":"FISCAL_PERIOD_ID","dataType":"double"},{"name":"FISCAL_WEEK_ID","dataType":"double"},{"name":"FISCAL_WEEK","dataType":"string"},{"name":"WEEK_SERIES","dataType":"double"},{"name":"Scenario","dataType":"string"},{"name":"FISCAL_MONTH","dataType":"string"},{"name":"Material Cost","dataType":"double"},{"name":"Material Overhead Cost","dataType":"double"},{"name":"OSP Cost","dataType":"double"},{"name":"Overhead Cost","dataType":"double"},{"name":"Resource Cost","dataType":"double"},{"name":"WIP_JOB_ID","dataType":"double"},{"name":"WIP Job Number","dataType":"string"},{"name":"USD Rate","dataType":"double"},{"name":"Finance Product Group","dataType":"string"},{"name":"Finance Product Family","dataType":"string"},{"name":"Finance Forecast Field","dataType":"string"},{"name":"Finance Product Segment","dataType":"string"},{"name":"Finance Product Line","dataType":"string"},{"name":"Creation Date","dataType":"dateTime"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-13T06:31:53.4776075+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/b41c844f-78b3-4b28-a275-29ffb69c9a32/Inventory_Value_Weekly.csv?snapshot=2022-06-13T06%3A31%3A53.4531054Z"}]}]}