{"name":"lokale_Daten_Sharepoint_Shortages","description":"Dateien von Sharepoint\nz.B. Shortages ( Zuständigkeit: Christoph Carsten)\nhttps://cohrinc.sharepoint.com/sites/o365_group_delbc-anti_corona-SupplyChain","version":"1.0","culture":"en-US","modifiedTime":"2022-01-31T11:40:19.8391809+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"Shortages_Paladin":{"queryId":"3cf62733-f1bf-4e3f-af9c-7c08580df2e2","queryName":"Shortages_Paladin","loadEnabled":true},"Sample file":{"queryId":"b8a17e83-6c0e-4498-9462-a04848f45e7b","queryName":"Sample file","queryGroupId":"91ba9934-134b-45a3-8bf2-45200c7b5b0e"},"Parameter":{"queryId":"337f49af-af32-4c14-a273-a1edc747d1e2","queryName":"Parameter","queryGroupId":"91ba9934-134b-45a3-8bf2-45200c7b5b0e"},"Transform Sample file":{"queryId":"0cee5795-1ea0-45f2-8c4c-b991d5db0cfb","queryName":"Transform Sample file","queryGroupId":"f30a60a9-2b81-4a8f-874e-5811ab059de9"},"Transform file":{"queryId":"dd40cca1-c39c-4bf4-bafa-520aa44d7be7","queryName":"Transform file","queryGroupId":"91ba9934-134b-45a3-8bf2-45200c7b5b0e"},"Shortages_ObisXT":{"queryId":"9f0a60e8-0c4e-450c-8eae-e5c89cfd3fa4","queryName":"Shortages_ObisXT","loadEnabled":true},"Transform Sample file1":{"queryId":"8d578d11-0581-4e41-8d9f-66bee95c2a31","queryName":"Transform Sample file1","queryGroupId":"3bfe0a33-7f34-47ed-926a-4ca4f43856e0"},"Sample file1":{"queryId":"36e4eba8-8c0d-49b7-b49b-f80ceaef6d72","queryName":"Sample file1","queryGroupId":"777d0ab2-caa2-4090-874a-d2646b08a504"},"Parameter1":{"queryId":"cf2e69a4-5c4b-44f0-977a-fd88e8679d1e","queryName":"Parameter1","queryGroupId":"777d0ab2-caa2-4090-874a-d2646b08a504"},"Transform file1":{"queryId":"8da979e8-5c62-44bb-b05c-7d6f8c867759","queryName":"Transform file1","queryGroupId":"777d0ab2-caa2-4090-874a-d2646b08a504"},"Transform Sample file11":{"queryId":"d1f48b3c-be4f-43d2-9a1a-0e49ca5c000f","queryName":"Transform Sample file11","queryGroupId":"5eb3396e-692c-46a6-8a04-6db9d8fc631e"},"Sample file11":{"queryId":"39d2fba7-9fec-45d5-b7ed-fa4212ebb8e2","queryName":"Sample file11","queryGroupId":"bea91120-b874-4424-9aae-9e076c71c6e9"},"Parameter11":{"queryId":"484fbea6-2164-44d1-8f0b-9c83ea010c3c","queryName":"Parameter11","queryGroupId":"bea91120-b874-4424-9aae-9e076c71c6e9"},"Transform file11":{"queryId":"6bd07016-d8d5-4aef-8a35-c1f67959abce","queryName":"Transform file11","queryGroupId":"bea91120-b874-4424-9aae-9e076c71c6e9"},"Shortages_Sapphire":{"queryId":"986eb6d6-e7f5-4509-9843-cbba66a332c6","queryName":"Shortages_Sapphire","loadEnabled":true},"Transform Sample file111":{"queryId":"dfc031b7-9da5-4aea-8c53-22af45a93a7b","queryName":"Transform Sample file111","queryGroupId":"41aec7a0-74fa-499f-821c-463f8b6f6b1f"},"Sample file111":{"queryId":"81720d76-c307-4f2e-a4fb-d8e111b0fbb2","queryName":"Sample file111","queryGroupId":"55d201f4-7e45-4e54-ac4a-92251bcdffac"},"Parameter111":{"queryId":"702b46a9-bc92-46f1-b3dd-97de606639de","queryName":"Parameter111","queryGroupId":"55d201f4-7e45-4e54-ac4a-92251bcdffac"},"Transform file111":{"queryId":"31c48490-50e3-4654-bc06-9c5d84cd5cce","queryName":"Transform file111","queryGroupId":"55d201f4-7e45-4e54-ac4a-92251bcdffac"},"Shortages_115M":{"queryId":"db266058-701e-42bc-8c02-bfa0eac1f79a","queryName":"Shortages_115M","loadEnabled":true},"Transform Sample file112":{"queryId":"ce4eec0a-d754-4a18-9bfc-67567a42ac1c","queryName":"Transform Sample file112","queryGroupId":"38a02b1c-be46-4026-ae52-9f8c173afa81"},"Sample file112":{"queryId":"4b2ab083-bfcd-4e74-81ef-70b3072b2c4f","queryName":"Sample file112","queryGroupId":"f96dc9c7-92ee-4864-92bc-083a4d2b9115"},"Parameter112":{"queryId":"acb06045-53e1-4d13-a6ec-c1de193b3749","queryName":"Parameter112","queryGroupId":"f96dc9c7-92ee-4864-92bc-083a4d2b9115"},"Transform file112":{"queryId":"3f5485e5-ca64-4c8a-8c92-f8baea1c8350","queryName":"Transform file112","queryGroupId":"f96dc9c7-92ee-4864-92bc-083a4d2b9115"},"Shortages_FlareNX":{"queryId":"6e644204-64ec-456f-b010-c8344a3d04ec","queryName":"Shortages_FlareNX","loadEnabled":true},"Transform Sample file113":{"queryId":"dc3c08be-1209-4a07-8275-664d892907a7","queryName":"Transform Sample file113","queryGroupId":"5733039f-1211-431c-b1c1-c779a6852539"},"Sample file113":{"queryId":"dd08fb0e-d73e-4547-a9f5-e83f48ce7135","queryName":"Sample file113","queryGroupId":"43355a45-2b68-4967-83bd-90b518b24e27"},"Parameter113":{"queryId":"49574574-efdd-4b9a-b57f-afe1c07b15a3","queryName":"Parameter113","queryGroupId":"43355a45-2b68-4967-83bd-90b518b24e27"},"Transform file113":{"queryId":"d715436e-7854-4dc8-b4bd-713f4c0ae73f","queryName":"Transform file113","queryGroupId":"43355a45-2b68-4967-83bd-90b518b24e27"},"Shortages_Allgemein":{"queryId":"ce8de794-759c-4923-8422-9ec902f58d2d","queryName":"Shortages_Allgemein","loadEnabled":true},"Transform Sample file114":{"queryId":"11242c95-dc91-4266-864a-21ba5d9dc5c2","queryName":"Transform Sample file114","queryGroupId":"9aa16a18-0a30-48d4-8e98-40424189070b"},"Sample file114":{"queryId":"2de45407-fd9e-44a0-8da0-4f63081a42c7","queryName":"Sample file114","queryGroupId":"917fa4dc-7765-4eac-84b0-57499e35c25f"},"Parameter114":{"queryId":"6d60892a-391c-42b6-ac2c-68a8633d6b52","queryName":"Parameter114","queryGroupId":"917fa4dc-7765-4eac-84b0-57499e35c25f"},"Transform file114":{"queryId":"5db34562-4217-4d36-b18c-63ebc0f5c2f2","queryName":"Transform file114","queryGroupId":"917fa4dc-7765-4eac-84b0-57499e35c25f"},"Shortages_AzureNX":{"queryId":"dc79e50e-504f-4a83-acf7-3e02b7d9e0aa","queryName":"Shortages_AzureNX","loadEnabled":true},"Transform Sample file1141":{"queryId":"00b52354-ae35-47c4-b652-234bb5e1a6f6","queryName":"Transform Sample file1141","queryGroupId":"99ccd331-cd2e-41fb-94dc-a54717fcfa8a"},"Sample file1141":{"queryId":"02976751-4ee6-4b53-b5bd-2866bda463c3","queryName":"Sample file1141","queryGroupId":"55aff06e-d5f0-44cc-801f-a36f01d16a56"},"Parameter1141":{"queryId":"23e14fde-b154-446f-829a-7f0a9dc17d2d","queryName":"Parameter1141","queryGroupId":"55aff06e-d5f0-44cc-801f-a36f01d16a56"},"Transform file1141":{"queryId":"4e8b836b-d2d0-4d81-b3b9-29a101eb4d10","queryName":"Transform file1141","queryGroupId":"55aff06e-d5f0-44cc-801f-a36f01d16a56"},"Shortages_AviaLX":{"queryId":"09d751e0-27c9-4bcd-ab7d-02a76274491a","queryName":"Shortages_AviaLX","loadEnabled":true}},"document":"section Section1;\r\nshared Shortages_Paladin = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/sites/o365_group_delbc-anti_corona-SupplyChain\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Name] = \"aktuell_kritische_shortages.xlsx\"),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows\", each [Attributes]?[Hidden]? <> true),\r\n  #\"Invoke custom function\" = Table.AddColumn(#\"Filtered hidden files\", \"Transform file\", each #\"Transform file\"([Content])),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Invoke custom function\", {{\"Name\", \"Source.Name\"}}),\r\n  #\"Removed other columns\" = Table.SelectColumns(#\"Renamed columns\", {\"Source.Name\", \"Transform file\"}),\r\n  #\"Expanded table column\" = Table.ExpandTableColumn(#\"Removed other columns\", \"Transform file\", Table.ColumnNames(#\"Transform file\"(#\"Sample file\"))),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Expanded table column\", {{\"Source.Name\", type text}, {\"Fälligkeit\", type date}, {\"Item\", type text}, {\"Description\", type text}, {\"Supplier\", type any}, {\"Wer \", type text}, {\"Zeitraum\", type any}, {\"Bemerkungen / aktueller Stand\", type text}, {\"abgeschlossen am\", type date}, {\"Bereich\", type text}}),\r\n  #\"Filter- Faelligkeit\" = Table.SelectRows(#\"Changed column type\", each [Fälligkeit] > #date(2001, 1, 1)),\r\n  #\"Transform columns\" = Table.TransformColumnTypes(#\"Filter- Faelligkeit\", {{\"Supplier\", type text}, {\"Zeitraum\", type text}}),\r\n  #\"Replace errors\" = Table.ReplaceErrorValues(#\"Transform columns\", {{\"Supplier\", null}, {\"Zeitraum\", null}}),\r\n  #\"Renamed columns 1\" = Table.RenameColumns(#\"Replace errors\", {{\"Wer \", \"Wer\"}})\r\nin\r\n  #\"Renamed columns 1\";\r\nshared #\"Sample file\" = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/sites/o365_group_delbc-anti_corona-SupplyChain\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Name] = \"aktuell_kritische_shortages.xlsx\"),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows\", each [Attributes]?[Hidden]? <> true),\r\n  Navigation = #\"Filtered hidden files\"{0}[Content]\r\nin\r\n  Navigation;\r\nshared Parameter = let\r\n  Parameter = #\"Sample file\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type binary]\r\nin\r\n  Parameter;\r\nshared #\"Transform Sample file\" = let\r\n  Source = Excel.Workbook(Parameter, null, true),\r\n  Navigation = Source{[Item = \"Paladin\", Kind = \"Sheet\"]}[Data],\r\n  #\"Promoted headers\" = Table.PromoteHeaders(Navigation, [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"Fälligkeit\", type date}, {\"Item\", type text}, {\"Description\", type text}, {\"Supplier\", type any}, {\"Wer \", type text}, {\"Zeitraum\", type any}, {\"Bemerkungen / aktueller Stand\", type text}, {\"abgeschlossen am\", type date}, {\"Bereich\", type text}})\r\nin\r\n  #\"Changed column type\";\r\nshared #\"Transform file\" = let\r\n  Source = (Parameter as binary) => let\r\n  Source = Excel.Workbook(Parameter, null, true),\r\n  Navigation = Source{[Item = \"Paladin\", Kind = \"Sheet\"]}[Data],\r\n  #\"Promoted headers\" = Table.PromoteHeaders(Navigation, [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"Fälligkeit\", type date}, {\"Item\", type text}, {\"Description\", type text}, {\"Supplier\", type any}, {\"Wer \", type text}, {\"Zeitraum\", type any}, {\"Bemerkungen / aktueller Stand\", type text}, {\"abgeschlossen am\", type date}, {\"Bereich\", type text}})\r\nin\r\n  #\"Changed column type\"\r\nin\r\n  Source;\r\nshared Shortages_ObisXT = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/sites/o365_group_delbc-anti_corona-SupplyChain\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Name] = \"aktuell_kritische_shortages.xlsx\"),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows\", each [Attributes]?[Hidden]? <> true),\r\n  #\"Invoke custom function\" = Table.AddColumn(#\"Filtered hidden files\", \"Transform file\", each #\"Transform file1\"([Content])),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Invoke custom function\", {{\"Name\", \"Source.Name\"}}),\r\n  #\"Removed other columns\" = Table.SelectColumns(#\"Renamed columns\", {\"Source.Name\", \"Transform file\"}),\r\n  #\"Expanded table column\" = Table.ExpandTableColumn(#\"Removed other columns\", \"Transform file\", Table.ColumnNames(#\"Transform file1\"(#\"Sample file1\"))),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Expanded table column\", {{\"Source.Name\", type text}, {\"Fälligkeit\", type date}, {\"Item\", type text}, {\"Description\", type text}, {\"Supplier\", type any}, {\"Wer \", type text}, {\"Zeitraum\", type any}, {\"Bemerkungen / aktueller Stand\", type text}, {\"abgeschlossen am\", type date}, {\"Bereich\", type text}}),\r\n  #\"Filtered rows -Faelligkeit\" = Table.SelectRows(#\"Changed column type\", each [Fälligkeit] > #date(2001, 1, 1)),\r\n  #\"Transform columns\" = Table.TransformColumnTypes(#\"Filtered rows -Faelligkeit\", {{\"Supplier\", type text}, {\"Zeitraum\", type text}}),\r\n  #\"Replace errors\" = Table.ReplaceErrorValues(#\"Transform columns\", {{\"Supplier\", null}, {\"Zeitraum\", null}}),\r\n  #\"Renamed columns 1\" = Table.RenameColumns(#\"Replace errors\", {{\"Wer \", \"Wer\"}})\r\nin\r\n  #\"Renamed columns 1\";\r\nshared #\"Transform Sample file1\" = let\r\n  Source = Excel.Workbook(Parameter1, null, true),\r\n  Navigation = Source{[Item = \"Paladin\", Kind = \"Sheet\"]}[Data],\r\n  #\"Promoted headers\" = Table.PromoteHeaders(Navigation, [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"Fälligkeit\", type date}, {\"Item\", type text}, {\"Description\", type text}, {\"Supplier\", type any}, {\"Wer \", type text}, {\"Zeitraum\", type any}, {\"Bemerkungen / aktueller Stand\", type text}, {\"abgeschlossen am\", type date}, {\"Bereich\", type text}})\r\nin\r\n  #\"Changed column type\";\r\nshared #\"Sample file1\" = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/sites/o365_group_delbc-anti_corona-SupplyChain\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Name] = \"aktuell_kritische_shortages.xlsx\"),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows\", each [Attributes]?[Hidden]? <> true),\r\n  Navigation = #\"Filtered hidden files\"{0}[Content]\r\nin\r\n  Navigation;\r\nshared Parameter1 = let\r\n  Parameter = #\"Sample file1\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type binary]\r\nin\r\n  Parameter;\r\nshared #\"Transform file1\" = let\r\n  Source = (Parameter as binary) => let\n  Source = Excel.Workbook(Parameter, null, true),\n  Navigation = Source{[Item = \"Obis XT\", Kind = \"Sheet\"]}[Data],\n  #\"Promoted headers\" = Table.PromoteHeaders(Navigation, [PromoteAllScalars = true]),\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"Fälligkeit\", type date}, {\"Item\", type text}, {\"Description\", type text}, {\"Supplier\", type any}, {\"Wer \", type text}, {\"Zeitraum\", type any}, {\"Bemerkungen / aktueller Stand\", type text}, {\"abgeschlossen am\", type date}, {\"Bereich\", type text}})\nin\n  #\"Changed column type\"\r\nin\r\n  Source;\r\nshared #\"Transform Sample file11\" = let\r\n  Source = Excel.Workbook(Parameter11, null, true),\r\n  Navigation = Source{[Item = \"Paladin\", Kind = \"Sheet\"]}[Data],\r\n  #\"Promoted headers\" = Table.PromoteHeaders(Navigation, [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"Fälligkeit\", type date}, {\"Item\", type text}, {\"Description\", type text}, {\"Supplier\", type any}, {\"Wer \", type text}, {\"Zeitraum\", type any}, {\"Bemerkungen / aktueller Stand\", type text}, {\"abgeschlossen am\", type date}, {\"Bereich\", type text}})\r\nin\r\n  #\"Changed column type\";\r\nshared #\"Sample file11\" = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/sites/o365_group_delbc-anti_corona-SupplyChain\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Name] = \"aktuell_kritische_shortages.xlsx\"),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows\", each [Attributes]?[Hidden]? <> true),\r\n  Navigation = #\"Filtered hidden files\"{0}[Content]\r\nin\r\n  Navigation;\r\nshared Parameter11 = let\r\n  Parameter = #\"Sample file11\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type binary]\r\nin\r\n  Parameter;\r\nshared #\"Transform file11\" = let\r\n  Source = (Parameter as binary) => let\n  Source = Excel.Workbook(Parameter, null, true),\n  Navigation = Source{[Item = \"Sapphire\", Kind = \"Sheet\"]}[Data],\n  #\"Promoted headers\" = Table.PromoteHeaders(Navigation, [PromoteAllScalars = true]),\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"Fälligkeit\", type date}, {\"Item\", type text}, {\"Description\", type text}, {\"Supplier\", type any}, {\"Wer \", type text}, {\"Zeitraum\", type any}, {\"Bemerkungen / aktueller Stand\", type text}, {\"abgeschlossen am\", type date}, {\"Bereich\", type text}})\nin\n  #\"Changed column type\"\r\nin\r\n  Source;\r\nshared Shortages_Sapphire = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/sites/o365_group_delbc-anti_corona-SupplyChain\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Name] = \"aktuell_kritische_shortages.xlsx\"),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows\", each [Attributes]?[Hidden]? <> true),\r\n  #\"Invoke custom function\" = Table.AddColumn(#\"Filtered hidden files\", \"Transform file\", each #\"Transform file11\"([Content])),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Invoke custom function\", {{\"Name\", \"Source.Name\"}}),\r\n  #\"Removed other columns\" = Table.SelectColumns(#\"Renamed columns\", {\"Source.Name\", \"Transform file\"}),\r\n  #\"Expanded table column\" = Table.ExpandTableColumn(#\"Removed other columns\", \"Transform file\", Table.ColumnNames(#\"Transform file11\"(#\"Sample file11\"))),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Expanded table column\", {{\"Source.Name\", type text}, {\"Fälligkeit\", type date}, {\"Item\", type text}, {\"Description\", type text}, {\"Supplier\", type any}, {\"Wer \", type text}, {\"Zeitraum\", type any}, {\"Bemerkungen / aktueller Stand\", type text}, {\"abgeschlossen am\", type date}, {\"Bereich\", type text}}),\r\n  #\"Transform columns\" = Table.TransformColumnTypes(#\"Changed column type\", {{\"Supplier\", type text}, {\"Zeitraum\", type text}}),\r\n  #\"Replace errors\" = Table.ReplaceErrorValues(#\"Transform columns\", {{\"Supplier\", null}, {\"Zeitraum\", null}}),\r\n  #\"Filtered rows -Faelligkeit\" = Table.SelectRows(#\"Replace errors\", each [Fälligkeit] > #date(2001, 1, 1)),\r\n  #\"Renamed columns 1\" = Table.RenameColumns(#\"Filtered rows -Faelligkeit\", {{\"Wer \", \"Wer\"}})\r\nin\r\n  #\"Renamed columns 1\";\r\nshared #\"Transform Sample file111\" = let\r\n  Source = Excel.Workbook(Parameter111, null, true),\r\n  Navigation = Source{[Item = \"Paladin\", Kind = \"Sheet\"]}[Data],\r\n  #\"Promoted headers\" = Table.PromoteHeaders(Navigation, [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"Fälligkeit\", type date}, {\"Item\", type text}, {\"Description\", type text}, {\"Supplier\", type any}, {\"Wer \", type text}, {\"Zeitraum\", type any}, {\"Bemerkungen / aktueller Stand\", type text}, {\"abgeschlossen am\", type date}, {\"Bereich\", type text}})\r\nin\r\n  #\"Changed column type\";\r\nshared #\"Sample file111\" = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/sites/o365_group_delbc-anti_corona-SupplyChain\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Name] = \"aktuell_kritische_shortages.xlsx\"),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows\", each [Attributes]?[Hidden]? <> true),\r\n  Navigation = #\"Filtered hidden files\"{0}[Content]\r\nin\r\n  Navigation;\r\nshared Parameter111 = let\r\n  Parameter = #\"Sample file111\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type binary]\r\nin\r\n  Parameter;\r\nshared #\"Transform file111\" = let\r\n  Source = (Parameter as binary) => let\n  Source = Excel.Workbook(Parameter, null, true),\n  Navigation = Source{[Item = \"115M\", Kind = \"Sheet\"]}[Data],\n  #\"Promoted headers\" = Table.PromoteHeaders(Navigation, [PromoteAllScalars = true]),\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"Fälligkeit\", type date}, {\"Item\", type text}, {\"Description\", type text}, {\"Supplier\", type any}, {\"Wer \", type text}, {\"Zeitraum\", type any}, {\"Bemerkungen / aktueller Stand\", type text}, {\"abgeschlossen am\", type date}, {\"Bereich\", type text}})\nin\n  #\"Changed column type\"\r\nin\r\n  Source;\r\nshared Shortages_115M = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/sites/o365_group_delbc-anti_corona-SupplyChain\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Name] = \"aktuell_kritische_shortages.xlsx\"),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows\", each [Attributes]?[Hidden]? <> true),\r\n  #\"Invoke custom function\" = Table.AddColumn(#\"Filtered hidden files\", \"Transform file\", each #\"Transform file111\"([Content])),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Invoke custom function\", {{\"Name\", \"Source.Name\"}}),\r\n  #\"Removed other columns\" = Table.SelectColumns(#\"Renamed columns\", {\"Source.Name\", \"Transform file\"}),\r\n  #\"Expanded table column\" = Table.ExpandTableColumn(#\"Removed other columns\", \"Transform file\", Table.ColumnNames(#\"Transform file111\"(#\"Sample file111\"))),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Expanded table column\", {{\"Source.Name\", type text}, {\"Fälligkeit\", type date}, {\"Item\", type text}, {\"Description\", type text}, {\"Supplier\", type any}, {\"Wer \", type text}, {\"Zeitraum\", type any}, {\"Bemerkungen / aktueller Stand\", type text}, {\"abgeschlossen am\", type date}, {\"Bereich\", type text}}),\r\n  #\"Transform columns\" = Table.TransformColumnTypes(#\"Changed column type\", {{\"Supplier\", type text}, {\"Zeitraum\", type text}}),\r\n  #\"Replace errors\" = Table.ReplaceErrorValues(#\"Transform columns\", {{\"Supplier\", null}, {\"Zeitraum\", null}}),\r\n  #\"Filtered rows -Faeligkeit\" = Table.SelectRows(#\"Replace errors\", each [Fälligkeit] > #date(2001, 1, 1)),\r\n  #\"Renamed columns 1\" = Table.RenameColumns(#\"Filtered rows -Faeligkeit\", {{\"Wer \", \"Wer\"}})\r\nin\r\n  #\"Renamed columns 1\";\r\nshared #\"Transform Sample file112\" = let\r\n  Source = Excel.Workbook(Parameter112, null, true),\r\n  Navigation = Source{[Item = \"Paladin\", Kind = \"Sheet\"]}[Data],\r\n  #\"Promoted headers\" = Table.PromoteHeaders(Navigation, [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"Fälligkeit\", type date}, {\"Item\", type text}, {\"Description\", type text}, {\"Supplier\", type any}, {\"Wer \", type text}, {\"Zeitraum\", type any}, {\"Bemerkungen / aktueller Stand\", type text}, {\"abgeschlossen am\", type date}, {\"Bereich\", type text}})\r\nin\r\n  #\"Changed column type\";\r\nshared #\"Sample file112\" = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/sites/o365_group_delbc-anti_corona-SupplyChain\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Name] = \"aktuell_kritische_shortages.xlsx\"),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows\", each [Attributes]?[Hidden]? <> true),\r\n  Navigation = #\"Filtered hidden files\"{0}[Content]\r\nin\r\n  Navigation;\r\nshared Parameter112 = let\r\n  Parameter = #\"Sample file112\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type binary]\r\nin\r\n  Parameter;\r\nshared #\"Transform file112\" = let\r\n  Source = (Parameter as binary) => let\n  Source = Excel.Workbook(Parameter, null, true),\n  Navigation = Source{[Item = \"Flare NX\", Kind = \"Sheet\"]}[Data],\n  #\"Promoted headers\" = Table.PromoteHeaders(Navigation, [PromoteAllScalars = true]),\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"Fälligkeit\", type date}, {\"Item\", type text}, {\"Description\", type text}, {\"Supplier\", type any}, {\"Wer \", type text}, {\"Zeitraum\", type any}, {\"Bemerkungen / aktueller Stand\", type text}, {\"abgeschlossen am\", type date}, {\"Bereich\", type text}})\nin\n  #\"Changed column type\"\r\nin\r\n  Source;\r\nshared Shortages_FlareNX = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/sites/o365_group_delbc-anti_corona-SupplyChain\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Name] = \"aktuell_kritische_shortages.xlsx\"),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows\", each [Attributes]?[Hidden]? <> true),\r\n  #\"Invoke custom function\" = Table.AddColumn(#\"Filtered hidden files\", \"Transform file\", each #\"Transform file112\"([Content])),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Invoke custom function\", {{\"Name\", \"Source.Name\"}}),\r\n  #\"Removed other columns\" = Table.SelectColumns(#\"Renamed columns\", {\"Source.Name\", \"Transform file\"}),\r\n  #\"Expanded table column\" = Table.ExpandTableColumn(#\"Removed other columns\", \"Transform file\", Table.ColumnNames(#\"Transform file112\"(#\"Sample file112\"))),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Expanded table column\", {{\"Source.Name\", type text}, {\"Fälligkeit\", type date}, {\"Item\", type text}, {\"Description\", type text}, {\"Supplier\", type any}, {\"Wer \", type text}, {\"Zeitraum\", type any}, {\"Bemerkungen / aktueller Stand\", type text}, {\"abgeschlossen am\", type date}, {\"Bereich\", type text}}),\r\n  #\"Transform columns\" = Table.TransformColumnTypes(#\"Changed column type\", {{\"Supplier\", type text}, {\"Zeitraum\", type text}}),\r\n  #\"Replace errors\" = Table.ReplaceErrorValues(#\"Transform columns\", {{\"Supplier\", null}, {\"Zeitraum\", null}}),\r\n  #\"Filtered rows -Faelligkeit\" = Table.SelectRows(#\"Replace errors\", each [Fälligkeit] > #date(2001, 1, 1)),\r\n  #\"Renamed columns 1\" = Table.RenameColumns(#\"Filtered rows -Faelligkeit\", {{\"Wer \", \"Wer\"}})\r\nin\r\n  #\"Renamed columns 1\";\r\nshared #\"Transform Sample file113\" = let\r\n  Source = Excel.Workbook(Parameter113, null, true),\r\n  Navigation = Source{[Item = \"Paladin\", Kind = \"Sheet\"]}[Data],\r\n  #\"Promoted headers\" = Table.PromoteHeaders(Navigation, [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"Fälligkeit\", type date}, {\"Item\", type text}, {\"Description\", type text}, {\"Supplier\", type any}, {\"Wer \", type text}, {\"Zeitraum\", type any}, {\"Bemerkungen / aktueller Stand\", type text}, {\"abgeschlossen am\", type date}, {\"Bereich\", type text}})\r\nin\r\n  #\"Changed column type\";\r\nshared #\"Sample file113\" = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/sites/o365_group_delbc-anti_corona-SupplyChain\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Name] = \"aktuell_kritische_shortages.xlsx\"),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows\", each [Attributes]?[Hidden]? <> true),\r\n  Navigation = #\"Filtered hidden files\"{0}[Content]\r\nin\r\n  Navigation;\r\nshared Parameter113 = let\r\n  Parameter = #\"Sample file113\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type binary]\r\nin\r\n  Parameter;\r\nshared #\"Transform file113\" = let\r\n  Source = (Parameter as binary) => let\n  Source = Excel.Workbook(Parameter, null, true),\n  Navigation = Source{[Item = \"allgemein\", Kind = \"Sheet\"]}[Data],\n  #\"Promoted headers\" = Table.PromoteHeaders(Navigation, [PromoteAllScalars = true]),\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"Fälligkeit\", type date}, {\"Item\", type text}, {\"Description\", type text}, {\"Supplier\", type any}, {\"Wer \", type text}, {\"Zeitraum\", type any}, {\"Bemerkungen / aktueller Stand\", type text}, {\"abgeschlossen am\", type date}, {\"Bereich\", type text}})\nin\n  #\"Changed column type\"\r\nin\r\n  Source;\r\nshared Shortages_Allgemein = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/sites/o365_group_delbc-anti_corona-SupplyChain\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Name] = \"aktuell_kritische_shortages.xlsx\"),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows\", each [Attributes]?[Hidden]? <> true),\r\n  #\"Invoke custom function\" = Table.AddColumn(#\"Filtered hidden files\", \"Transform file\", each #\"Transform file113\"([Content])),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Invoke custom function\", {{\"Name\", \"Source.Name\"}}),\r\n  #\"Removed other columns\" = Table.SelectColumns(#\"Renamed columns\", {\"Source.Name\", \"Transform file\"}),\r\n  #\"Expanded table column\" = Table.ExpandTableColumn(#\"Removed other columns\", \"Transform file\", Table.ColumnNames(#\"Transform file113\"(#\"Sample file113\"))),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Expanded table column\", {{\"Source.Name\", type text}, {\"Fälligkeit\", type date}, {\"Item\", type text}, {\"Description\", type text}, {\"Supplier\", type any}, {\"Wer \", type text}, {\"Zeitraum\", type any}, {\"Bemerkungen / aktueller Stand\", type text}, {\"abgeschlossen am\", type date}, {\"Bereich\", type text}}),\r\n  #\"Transform columns\" = Table.TransformColumnTypes(#\"Changed column type\", {{\"Supplier\", type text}, {\"Zeitraum\", type text}}),\r\n  #\"Replace errors\" = Table.ReplaceErrorValues(#\"Transform columns\", {{\"Supplier\", null}, {\"Zeitraum\", null}}),\r\n  #\"Filtered rows -Faelligkeit\" = Table.SelectRows(#\"Replace errors\", each [Fälligkeit] > #date(2001, 1, 1)),\r\n  #\"Renamed columns 1\" = Table.RenameColumns(#\"Filtered rows -Faelligkeit\", {{\"Wer \", \"Wer\"}})\r\nin\r\n  #\"Renamed columns 1\";\r\nshared #\"Transform Sample file114\" = let\r\n  Source = Excel.Workbook(Parameter114, null, true),\r\n  Navigation = Source{[Item = \"Paladin\", Kind = \"Sheet\"]}[Data],\r\n  #\"Promoted headers\" = Table.PromoteHeaders(Navigation, [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"Fälligkeit\", type date}, {\"Item\", type text}, {\"Description\", type text}, {\"Supplier\", type any}, {\"Wer \", type text}, {\"Zeitraum\", type any}, {\"Bemerkungen / aktueller Stand\", type text}, {\"abgeschlossen am\", type date}, {\"Bereich\", type text}})\r\nin\r\n  #\"Changed column type\";\r\nshared #\"Sample file114\" = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/sites/o365_group_delbc-anti_corona-SupplyChain\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Name] = \"aktuell_kritische_shortages.xlsx\"),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows\", each [Attributes]?[Hidden]? <> true),\r\n  Navigation = #\"Filtered hidden files\"{0}[Content]\r\nin\r\n  Navigation;\r\nshared Parameter114 = let\r\n  Parameter = #\"Sample file114\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type binary]\r\nin\r\n  Parameter;\r\nshared #\"Transform file114\" = let\r\n  Source = (Parameter as binary) => let\n  Source = Excel.Workbook(Parameter, null, true),\n  Navigation = Source{[Item = \"Azure NX\", Kind = \"Sheet\"]}[Data],\n  #\"Promoted headers\" = Table.PromoteHeaders(Navigation, [PromoteAllScalars = true]),\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"Fälligkeit\", type date}, {\"Item\", type text}, {\"Description\", type text}, {\"Supplier\", type any}, {\"Wer \", type text}, {\"Zeitraum\", type any}, {\"Bemerkungen / aktueller Stand\", type text}, {\"abgeschlossen am\", type date}, {\"Bereich\", type text}})\nin\n  #\"Changed column type\"\r\nin\r\n  Source;\r\nshared Shortages_AzureNX = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/sites/o365_group_delbc-anti_corona-SupplyChain\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Name] = \"aktuell_kritische_shortages.xlsx\"),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows\", each [Attributes]?[Hidden]? <> true),\r\n  #\"Invoke custom function\" = Table.AddColumn(#\"Filtered hidden files\", \"Transform file\", each #\"Transform file114\"([Content])),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Invoke custom function\", {{\"Name\", \"Source.Name\"}}),\r\n  #\"Removed other columns\" = Table.SelectColumns(#\"Renamed columns\", {\"Source.Name\", \"Transform file\"}),\r\n  #\"Expanded table column\" = Table.ExpandTableColumn(#\"Removed other columns\", \"Transform file\", Table.ColumnNames(#\"Transform file114\"(#\"Sample file114\"))),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Expanded table column\", {{\"Source.Name\", type text}, {\"Fälligkeit\", type date}, {\"Item\", type text}, {\"Description\", type text}, {\"Supplier\", type any}, {\"Wer \", type text}, {\"Zeitraum\", type any}, {\"Bemerkungen / aktueller Stand\", type text}, {\"abgeschlossen am\", type date}, {\"Bereich\", type text}}),\r\n  #\"Transform columns\" = Table.TransformColumnTypes(#\"Changed column type\", {{\"Supplier\", type text}, {\"Zeitraum\", type text}}),\r\n  #\"Replace errors\" = Table.ReplaceErrorValues(#\"Transform columns\", {{\"Supplier\", null}, {\"Zeitraum\", null}}),\r\n  #\"Filtered rows -Faelligkeit\" = Table.SelectRows(#\"Replace errors\", each [Fälligkeit] > #date(2001, 1, 1)),\r\n  #\"Renamed columns 1\" = Table.RenameColumns(#\"Filtered rows -Faelligkeit\", {{\"Wer \", \"Wer\"}})\r\nin\r\n  #\"Renamed columns 1\";\r\nshared #\"Transform Sample file1141\" = let\r\n  Source = Excel.Workbook(Parameter1141, null, true),\r\n  Navigation = Source{[Item = \"Paladin\", Kind = \"Sheet\"]}[Data],\r\n  #\"Promoted headers\" = Table.PromoteHeaders(Navigation, [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"Fälligkeit\", type date}, {\"Item\", type text}, {\"Description\", type text}, {\"Supplier\", type any}, {\"Wer \", type text}, {\"Zeitraum\", type any}, {\"Bemerkungen / aktueller Stand\", type text}, {\"abgeschlossen am\", type date}, {\"Bereich\", type text}})\r\nin\r\n  #\"Changed column type\";\r\nshared #\"Sample file1141\" = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/sites/o365_group_delbc-anti_corona-SupplyChain\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Name] = \"aktuell_kritische_shortages.xlsx\"),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows\", each [Attributes]?[Hidden]? <> true),\r\n  Navigation = #\"Filtered hidden files\"{0}[Content]\r\nin\r\n  Navigation;\r\nshared Parameter1141 = let\r\n  Parameter = #\"Sample file1141\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type binary]\r\nin\r\n  Parameter;\r\nshared #\"Transform file1141\" = let\r\n  Source = (Parameter as binary) => let\n  Source = Excel.Workbook(Parameter, null, true),\n  Navigation = Source{[Item = \"Avia LX\", Kind = \"Sheet\"]}[Data],\n  #\"Promoted headers\" = Table.PromoteHeaders(Navigation, [PromoteAllScalars = true]),\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"Fälligkeit\", type date}, {\"Item\", type text}, {\"Description\", type text}, {\"Supplier\", type any}, {\"Wer \", type text}, {\"Zeitraum\", type any}, {\"Bemerkungen / aktueller Stand\", type text}, {\"abgeschlossen am\", type date}, {\"Bereich\", type text}})\nin\n  #\"Changed column type\"\r\nin\r\n  Source;\r\nshared Shortages_AviaLX = let\r\n  Source = SharePoint.Files(\"https://cohrinc.sharepoint.com/sites/o365_group_delbc-anti_corona-SupplyChain\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Name] = \"aktuell_kritische_shortages.xlsx\"),\r\n  #\"Filtered hidden files\" = Table.SelectRows(#\"Filtered rows\", each [Attributes]?[Hidden]? <> true),\r\n  #\"Invoke custom function\" = Table.AddColumn(#\"Filtered hidden files\", \"Transform file\", each #\"Transform file1141\"([Content])),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Invoke custom function\", {{\"Name\", \"Source.Name\"}}),\r\n  #\"Removed other columns\" = Table.SelectColumns(#\"Renamed columns\", {\"Source.Name\", \"Transform file\"}),\r\n  #\"Expanded table column\" = Table.ExpandTableColumn(#\"Removed other columns\", \"Transform file\", Table.ColumnNames(#\"Transform file1141\"(#\"Sample file1141\"))),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Expanded table column\", {{\"Source.Name\", type text}, {\"Fälligkeit\", type date}, {\"Item\", type text}, {\"Description\", type text}, {\"Supplier\", type any}, {\"Wer \", type text}, {\"Zeitraum\", type any}, {\"Bemerkungen / aktueller Stand\", type text}, {\"abgeschlossen am\", type date}, {\"Bereich\", type text}}),\r\n  #\"Transform columns\" = Table.TransformColumnTypes(#\"Changed column type\", {{\"Supplier\", type text}, {\"Zeitraum\", type text}}),\r\n  #\"Replace errors\" = Table.ReplaceErrorValues(#\"Transform columns\", {{\"Supplier\", null}, {\"Zeitraum\", null}}),\r\n  #\"Filtered rows -Faelligkeit\" = Table.SelectRows(#\"Replace errors\", each [Fälligkeit] > #date(2001, 1, 1)),\r\n  #\"Renamed columns 1\" = Table.RenameColumns(#\"Filtered rows -Faelligkeit\", {{\"Wer \", \"Wer\"}})\r\nin\r\n  #\"Renamed columns 1\";\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[{\"id\":\"f30a60a9-2b81-4a8f-874e-5811ab059de9\",\"name\":\"Transform file from Shortages_Paladin\",\"description\":null,\"parentId\":null,\"order\":0},{\"id\":\"91ba9934-134b-45a3-8bf2-45200c7b5b0e\",\"name\":\"Helper queries\",\"description\":null,\"parentId\":\"f30a60a9-2b81-4a8f-874e-5811ab059de9\",\"order\":0},{\"id\":\"3bfe0a33-7f34-47ed-926a-4ca4f43856e0\",\"name\":\"Transform file from Shortages_ObisXT\",\"description\":\"\",\"parentId\":null,\"order\":1},{\"id\":\"777d0ab2-caa2-4090-874a-d2646b08a504\",\"name\":\"Helper queries\",\"description\":\"\",\"parentId\":\"3bfe0a33-7f34-47ed-926a-4ca4f43856e0\",\"order\":2},{\"id\":\"5eb3396e-692c-46a6-8a04-6db9d8fc631e\",\"name\":\"Transform file from Shortages_Sapphire\",\"description\":\"\",\"parentId\":null,\"order\":1},{\"id\":\"bea91120-b874-4424-9aae-9e076c71c6e9\",\"name\":\"Helper queries\",\"description\":\"\",\"parentId\":\"5eb3396e-692c-46a6-8a04-6db9d8fc631e\",\"order\":2},{\"id\":\"41aec7a0-74fa-499f-821c-463f8b6f6b1f\",\"name\":\"Transform file from Shortages_115M\",\"description\":\"\",\"parentId\":null,\"order\":1},{\"id\":\"55d201f4-7e45-4e54-ac4a-92251bcdffac\",\"name\":\"Helper queries\",\"description\":\"\",\"parentId\":\"41aec7a0-74fa-499f-821c-463f8b6f6b1f\",\"order\":2},{\"id\":\"38a02b1c-be46-4026-ae52-9f8c173afa81\",\"name\":\"Transform file from Shortages_FlareNX\",\"description\":\"\",\"parentId\":null,\"order\":1},{\"id\":\"f96dc9c7-92ee-4864-92bc-083a4d2b9115\",\"name\":\"Helper queries\",\"description\":\"\",\"parentId\":\"38a02b1c-be46-4026-ae52-9f8c173afa81\",\"order\":2},{\"id\":\"5733039f-1211-431c-b1c1-c779a6852539\",\"name\":\"Transform file from Shortages_Allgemein\",\"description\":\"\",\"parentId\":null,\"order\":1},{\"id\":\"43355a45-2b68-4967-83bd-90b518b24e27\",\"name\":\"Helper queries\",\"description\":\"\",\"parentId\":\"5733039f-1211-431c-b1c1-c779a6852539\",\"order\":2},{\"id\":\"9aa16a18-0a30-48d4-8e98-40424189070b\",\"name\":\"Transform file from Shortages_AzureNX\",\"description\":\"\",\"parentId\":null,\"order\":1},{\"id\":\"917fa4dc-7765-4eac-84b0-57499e35c25f\",\"name\":\"Helper queries\",\"description\":\"\",\"parentId\":\"9aa16a18-0a30-48d4-8e98-40424189070b\",\"order\":2},{\"id\":\"99ccd331-cd2e-41fb-94dc-a54717fcfa8a\",\"name\":\"Transform file from Shortages_AviaLX\",\"description\":\"\",\"parentId\":null,\"order\":1},{\"id\":\"55aff06e-d5f0-44cc-801f-a36f01d16a56\",\"name\":\"Helper queries\",\"description\":\"\",\"parentId\":\"99ccd331-cd2e-41fb-94dc-a54717fcfa8a\",\"order\":2}]"}],"entities":[{"$type":"LocalEntity","name":"Shortages_Paladin","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Shortages_Paladin.csv"},"attributes":[{"name":"Source.Name","dataType":"string"},{"name":"Fälligkeit","dataType":"date"},{"name":"Item","dataType":"string"},{"name":"Description","dataType":"string"},{"name":"Supplier","dataType":"string"},{"name":"Wer","dataType":"string"},{"name":"Zeitraum","dataType":"string"},{"name":"Bemerkungen / aktueller Stand","dataType":"string"},{"name":"abgeschlossen am","dataType":"date"},{"name":"Bereich","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-20T07:30:20.2208261+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/0b27944c-8d35-4a28-a111-57d716e673ac/Shortages_Paladin.csv?snapshot=2022-05-20T07%3A30%3A20.2111747Z"}]},{"$type":"LocalEntity","name":"Shortages_ObisXT","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Shortages_ObisXT.csv"},"attributes":[{"name":"Source.Name","dataType":"string"},{"name":"Fälligkeit","dataType":"date"},{"name":"Item","dataType":"string"},{"name":"Description","dataType":"string"},{"name":"Supplier","dataType":"string"},{"name":"Wer","dataType":"string"},{"name":"Zeitraum","dataType":"string"},{"name":"Bemerkungen / aktueller Stand","dataType":"string"},{"name":"abgeschlossen am","dataType":"date"},{"name":"Bereich","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-20T07:30:34.792114+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/0b27944c-8d35-4a28-a111-57d716e673ac/Shortages_ObisXT.csv?snapshot=2022-05-20T07%3A30%3A34.6988635Z"}]},{"$type":"LocalEntity","name":"Shortages_Sapphire","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Shortages_Sapphire.csv"},"attributes":[{"name":"Source.Name","dataType":"string"},{"name":"Fälligkeit","dataType":"date"},{"name":"Item","dataType":"string"},{"name":"Description","dataType":"string"},{"name":"Supplier","dataType":"string"},{"name":"Wer","dataType":"string"},{"name":"Zeitraum","dataType":"string"},{"name":"Bemerkungen / aktueller Stand","dataType":"string"},{"name":"abgeschlossen am","dataType":"date"},{"name":"Bereich","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-20T07:30:34.1359313+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/0b27944c-8d35-4a28-a111-57d716e673ac/Shortages_Sapphire.csv?snapshot=2022-05-20T07%3A30%3A34.0222523Z"}]},{"$type":"LocalEntity","name":"Shortages_115M","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Shortages_115M.csv"},"attributes":[{"name":"Source.Name","dataType":"string"},{"name":"Fälligkeit","dataType":"date"},{"name":"Item","dataType":"string"},{"name":"Description","dataType":"string"},{"name":"Supplier","dataType":"string"},{"name":"Wer","dataType":"string"},{"name":"Zeitraum","dataType":"string"},{"name":"Bemerkungen / aktueller Stand","dataType":"string"},{"name":"abgeschlossen am","dataType":"date"},{"name":"Bereich","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-20T07:30:26.7186334+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/0b27944c-8d35-4a28-a111-57d716e673ac/Shortages_115M.csv?snapshot=2022-05-20T07%3A30%3A26.6644728Z"}]},{"$type":"LocalEntity","name":"Shortages_FlareNX","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Shortages_FlareNX.csv"},"attributes":[{"name":"Source.Name","dataType":"string"},{"name":"Fälligkeit","dataType":"date"},{"name":"Item","dataType":"string"},{"name":"Description","dataType":"string"},{"name":"Supplier","dataType":"string"},{"name":"Wer","dataType":"string"},{"name":"Zeitraum","dataType":"string"},{"name":"Bemerkungen / aktueller Stand","dataType":"string"},{"name":"abgeschlossen am","dataType":"date"},{"name":"Bereich","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-20T07:30:25.9530189+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/0b27944c-8d35-4a28-a111-57d716e673ac/Shortages_FlareNX.csv?snapshot=2022-05-20T07%3A30%3A25.8679286Z"}]},{"$type":"LocalEntity","name":"Shortages_Allgemein","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Shortages_Allgemein.csv"},"attributes":[{"name":"Source.Name","dataType":"string"},{"name":"Fälligkeit","dataType":"date"},{"name":"Item","dataType":"string"},{"name":"Description","dataType":"string"},{"name":"Supplier","dataType":"string"},{"name":"Wer","dataType":"string"},{"name":"Zeitraum","dataType":"string"},{"name":"Bemerkungen / aktueller Stand","dataType":"string"},{"name":"abgeschlossen am","dataType":"date"},{"name":"Bereich","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-20T07:30:32.6795987+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/0b27944c-8d35-4a28-a111-57d716e673ac/Shortages_Allgemein.csv?snapshot=2022-05-20T07%3A30%3A32.6030652Z"}]},{"$type":"LocalEntity","name":"Shortages_AzureNX","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Shortages_AzureNX.csv"},"attributes":[{"name":"Source.Name","dataType":"string"},{"name":"Fälligkeit","dataType":"date"},{"name":"Item","dataType":"string"},{"name":"Description","dataType":"string"},{"name":"Supplier","dataType":"string"},{"name":"Wer","dataType":"string"},{"name":"Zeitraum","dataType":"string"},{"name":"Bemerkungen / aktueller Stand","dataType":"string"},{"name":"abgeschlossen am","dataType":"date"},{"name":"Bereich","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-20T07:30:29.1171005+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/0b27944c-8d35-4a28-a111-57d716e673ac/Shortages_AzureNX.csv?snapshot=2022-05-20T07%3A30%3A29.0940781Z"}]},{"$type":"LocalEntity","name":"Shortages_AviaLX","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Shortages_AviaLX.csv"},"attributes":[{"name":"Source.Name","dataType":"string"},{"name":"Fälligkeit","dataType":"date"},{"name":"Item","dataType":"string"},{"name":"Description","dataType":"string"},{"name":"Supplier","dataType":"string"},{"name":"Wer","dataType":"string"},{"name":"Zeitraum","dataType":"string"},{"name":"Bemerkungen / aktueller Stand","dataType":"string"},{"name":"abgeschlossen am","dataType":"date"},{"name":"Bereich","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-20T07:30:34.2765+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/0b27944c-8d35-4a28-a111-57d716e673ac/Shortages_AviaLX.csv?snapshot=2022-05-20T07%3A30%3A34.2121425Z"}]}]}