{"name":"COHREP_SITE_PLANNING_TRX1","description":"","version":"1.0","culture":"en-US","modifiedTime":"2021-10-11T21:33:21.2673075+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":true,"queriesMetadata":{"Safety_Stock":{"queryId":"c4ad0b46-664d-4794-9209-86bffa98971e","queryName":"Safety_Stock","queryGroupId":"root","loadEnabled":true},"ORG":{"queryId":"83d2a14e-dcdd-42e1-be9c-892f1732b0d2","queryName":"ORG"},"Gross_Requirement":{"queryId":"52e3e08a-a1cf-452a-b866-c0eeb12358a0","queryName":"Gross_Requirement","queryGroupId":"root","loadEnabled":true},"ASCP_Pegging":{"queryId":"632b09da-f47e-4b3e-949d-5cd5272d6b5b","queryName":"ASCP_Pegging","queryGroupId":"root","loadEnabled":true},"Planned_Supply_Demand":{"queryId":"c606293f-7264-408c-8ba8-dcaf9aca7f50","queryName":"Planned_Supply_Demand","queryGroupId":"root","loadEnabled":true},"Local":{"queryId":"92c4335b-c12e-4a21-b187-7bf9b17c305e","queryName":"Local"},"Master_Demand_Schedule":{"queryId":"93fd0c97-d3c2-442d-8329-474ac6a2917b","queryName":"Master_Demand_Schedule","queryGroupId":"root","loadEnabled":true}},"document":"section Section1;\r\nshared Safety_Stock = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, Query=\"\nselect\n   sysdate extract_date,\n   mp.organization_code,\n   from_tz(cast (sysdate as timestamp),'PST') at time zone '\"&Local&\"' local_extract_date,\n   msi.inventory_item_id,\n   msi.segment1 item_number,\n   mss.safety_stock_code,\n   mss.safety_stock_percent,\n   mss.safety_stock_quantity,\n   mss.service_level,\n   mss.effectivity_date,\n   (\n      select\n         max(mss2.effectivity_date) \n      from\n         inv.mtl_Safety_Stocks mss2 \n      where\n         mss2.organization_id = mss.organization_id \n         and mss2.inventory_item_id = mss.inventory_item_id\n   )\n   latest_effectivity,\n   (\n      case\n         when\n            trunc(sysdate) > mss.effectivity_date \n            and trunc(sysdate) > (\n            select\n               max(mss2.effectivity_date) \n            from\n               inv.mtl_Safety_Stocks mss2 \n            where\n               mss2.organization_id = mss.organization_id \n               and mss2.inventory_item_id = mss.inventory_item_id) \n               and mss.effectivity_date = \n               (\n                  select\n                     max(mss2.effectivity_date) \n                  from\n                     inv.mtl_Safety_Stocks mss2 \n                  where\n                     mss2.organization_id = mss.organization_id \n                     and mss2.inventory_item_id = mss.inventory_item_id\n               )\n            then\n               'Yes' \n            else\n               'No' \n      end\n   )\n   CURRENTLY_ACTIVE \nfrom\n   inv.mtl_Safety_Stocks mss , apps.mtl_parameters mp , inv.mtl_system_items_b msi \nwhere\n   mp.organization_id = mss.organization_id \n   and msi.inventory_item_id = mss.inventory_item_id \n   and msi.organization_id = mp.organization_id \n   and mp.organization_code = '\"&ORG&\"'\n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"EXTRACT_DATE\", \"Extract Date\"}, {\"ORGANIZATION_CODE\", \"Organization Code\"}, {\"ITEM_NUMBER\", \"Item Number\"}, {\"SAFETY_STOCK_QUANTITY\", \"Safety Stock Quantity\"}, {\"EFFECTIVITY_DATE\", \"Effectivity Date\"}, {\"LATEST_EFFECTIVITY\", \"Latest Effectivity Date\"}, {\"CURRENTLY_ACTIVE\", \"Current Flag\"}, {\"SAFETY_STOCK_PERCENT\", \"Safety Stock Percent\"}, {\"SERVICE_LEVEL\", \"Service Level\"}, {\"SAFETY_STOCK_CODE\", \"Safety Stock Code\"}, {\"LOCAL_EXTRACT_DATE\", \"Local Extract Date\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared ORG = let\r\n  ORG = \"PPG\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type text]\r\nin\r\n  ORG;\r\nshared Gross_Requirement = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, \n  Query=\"\nSELECT\n    sysdate                                                                     extract_date,\n    trunc(mgr.creation_date)                                                    plan_date,\n    from_tz(CAST(sysdate AS TIMESTAMP), 'PST') AT TIME ZONE '\"&Local&\"'         local_extract_date,\n    mp.organization_code,\n    msi.segment1                                                                item_number,\n    msi.inventory_item_id,\n    using_assembly_demand_date                                                  demand_date,\n    mfgl.meaning                                                                demand_origin,\n    SUM(using_requirements_quantity)                                            gross_requirement_quantity,\n    mgr.compile_designator,\n    mgr.demand_class,\n    msi.item_type\nFROM\n    mrp.mrp_gross_requirements    mgr,\n    inv.mtl_system_items_b        msi,\n    inv.mtl_parameters            mp,\n    apps.mfg_lookups_v            mfgl\nWHERE\n        msi.organization_id = mgr.organization_id\n    AND mp.organization_code = '\"&ORG&\"'\n    AND mp.organization_id = msi.organization_id\n    AND mgr.inventory_item_id = msi.inventory_item_id\n    AND mfgl.lookup_code = to_char(mgr.origination_type)\n    AND mfgl.lookup_type = 'MRP_DEMAND_ORIGINATION'\n    AND mgr.compile_designator = 'CHR_MRP'\nGROUP BY\n    mp.organization_code,\n    msi.segment1,\n    using_assembly_demand_date,\n    mfgl.meaning,\n    mgr.compile_designator,\n    msi.inventory_item_id,\n    msi.item_type,\n    mgr.demand_class,\n    trunc(mgr.creation_date)\n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"EXTRACT_DATE\", \"Extract Date\"}, {\"PLAN_DATE\", \"Plan Date\"}, {\"ORGANIZATION_CODE\", \"Organization Code\"}, {\"ITEM_NUMBER\", \"Item Number\"}, {\"DEMAND_DATE\", \"Demand Date\"}, {\"GROSS_REQUIREMENT_QUANTITY\", \"Quantity\"}, {\"COMPILE_DESIGNATOR\", \"Compile Designator\"}, {\"DEMAND_ORIGIN\", \"Demand Origin\"}, {\"ITEM_TYPE\", \"Item Type\"}, {\"DEMAND_CLASS\", \"Demand Class\"}, {\"LOCAL_EXTRACT_DATE\", \"Local Extract Date\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared ASCP_Pegging = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, Query=\"\nSELECT\n    sysdate extract_date,\n    al1.date_run,\n    from_tz(cast (sysdate as timestamp),'PST') at time zone '\"&Local&\"' local_extract_date,\n    al1.demand_org_family,\n    al1.demand_org_line,\n    al1.demand_org_forecast,\n    al1.demand_sales_commodity,\n    al1.org,\n    al1.item_number,\n    al1.firmed,\n    al1.description,\n    al1.item_type,\n    al1.planner_code,\n    substr(al1.source_organization_code, 5, 3),\n    SUM(al1.supply_pegged_qty),\n    al1.demand_id,\n    al1.end_item_demand_date,\n    al1.end_item_qty,\n    al1.old_due_date,\n    al1.ascp_lead_time,\n    al1.quantity_rate,\n    al1.supply_category,\n    al1.old_dock_date,\n    al1.reschedule_days,\n    al1.compression_days,\n    al1.sugg_order_date,\n    al1.sugg_start_date,\n    al1.sugg_dock_date,\n    al1.sugg_due_date,\n    al1.end_item_org_code,\n    al1.end_item,\n    al1.end_item_desc,\n    al1.end_item_make_buy,\n    al1.end_item_planner_code,\n    al1.end_item_type,\n    al1.end_item_dem_type,\n    al1.end_item_calc_order_number,\n    al1.end_item_order_type,\n    al1.end_item_order_line,\n    al1.calc_end_demand_customer,\n    al1.order_number,\n    al1.firmed_late,\n    al1.order_type_text,\n    al1.schedule_comments,\n    al1.forecast_name,\n    al1.forecast_desc,\n    al1.wo_status,\n    al1.wo_desc,\n    CASE\n        WHEN nvl(al1.source_vendor_name, 'X') <> 'X' THEN\n            al1.source_vendor_name\n            || '_'\n            || al1.source_vendor_site_code\n    END,\n    al1.plan_name,\n    al1.po_line_location_id,\n    al2.category_concat_segs\nFROM\n    xxcoh.xxcoh_sup_peg_datamart    al1,\n    apps.mtl_item_categories_v      al2\nWHERE\n    ( al1.end_item_id = al2.inventory_item_id (+)\n      AND al1.end_organization_id = al2.organization_id (+) )\n    AND ( ( al1.plan_name = 'CHR_MRP'\n            AND al1.org = '\"&ORG&\"'\n            AND al2.category_set_name (+) = 'Shipment Priority' ) )\nGROUP BY\n    al1.date_run,\n    al1.demand_org_family,\n    al1.demand_org_line,\n    al1.demand_org_forecast,\n    al1.demand_sales_commodity,\n    al1.org,\n    al1.item_number,\n    al1.firmed,\n    al1.description,\n    al1.item_type,\n    al1.planner_code,\n    substr(al1.source_organization_code, 5, 3),\n    al1.demand_id,\n    al1.end_item_demand_date,\n    al1.end_item_qty,\n    al1.old_due_date,\n    al1.ascp_lead_time,\n    al1.quantity_rate,\n    al1.supply_category,\n    al1.old_dock_date,\n    al1.reschedule_days,\n    al1.compression_days,\n    al1.sugg_order_date,\n    al1.sugg_start_date,\n    al1.sugg_dock_date,\n    al1.sugg_due_date,\n    al1.end_item_org_code,\n    al1.end_item,\n    al1.end_item_desc,\n    al1.end_item_make_buy,\n    al1.end_item_planner_code,\n    al1.end_item_type,\n    al1.end_item_dem_type,\n    al1.end_item_calc_order_number,\n    al1.end_item_order_type,\n    al1.end_item_order_line,\n    al1.calc_end_demand_customer,\n    al1.order_number,\n    al1.firmed_late,\n    al1.order_type_text,\n    al1.schedule_comments,\n    al1.forecast_name,\n    al1.forecast_desc,\n    al1.wo_status,\n    al1.wo_desc,\n    CASE\n            WHEN nvl(al1.source_vendor_name, 'X') <> 'X' THEN\n                al1.source_vendor_name\n                || '_'\n                || al1.source_vendor_site_code\n    END,\n    al1.plan_name,\n    al1.po_line_location_id,\n    al2.category_concat_segs\n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed Columns\" = Table.RenameColumns(Source, {{\"DATE_RUN\", \"Date Run\"}, {\"ORG\", \"Org\"}, {\"ITEM_NUMBER\", \"Item Number\"}, {\"DESCRIPTION\", \"Item Description\"}, {\"SUBSTR(AL1.SOURCE_ORGANIZATION_CODE,5,3)\", \"Source Organization Code\"}, {\"SUM(AL1.SUPPLY_PEGGED_QTY)\", \"Supply Pegged Qty\"}, {\"SUPPLY_CATEGORY\", \"Supply Category\"}, {\"OLD_DOCK_DATE\", \"Old Dock Date\"}, {\"RESCHEDULE_DAYS\", \"Supply Reschedule Days\"}, {\"COMPRESSION_DAYS\", \"Supply Compression Days\"}, {\"SUGG_ORDER_DATE\", \"Sugg Order Date\"}, {\"SUGG_START_DATE\", \"Sugg Start Date\"}, {\"SUGG_DOCK_DATE\", \"Sugg Dock Date\"}, {\"SUGG_DUE_DATE\", \"Sugg Due Date\"}, {\"END_ITEM\", \"End Item Number\"}, {\"END_ITEM_DESC\", \"End Item Description\"}, {\"END_ITEM_MAKE_BUY\", \"End Item Make Buy\"}, {\"END_ITEM_PLANNER_CODE\", \"End Item Planner Code\"}, {\"END_ITEM_TYPE\", \"End Item Type\"}, {\"END_ITEM_DEM_TYPE\", \"End Item Demand Type\"}, {\"END_ITEM_ORDER_TYPE\", \"End Item Demand Order Type\"}, {\"END_ITEM_CALC_ORDER_NUMBER\", \"End Item Demand Order Number\"}, {\"END_ITEM_ORDER_LINE\", \"End Item Order Demand Order Line\"}, {\"CALC_END_DEMAND_CUSTOMER\", \"End Item Demand Customer\"}, {\"FIRMED_LATE\", \"Firm Late\"}, {\"FORECAST_NAME\", \"Forecast Name\"}, {\"FORECAST_DESC\", \"Forecast Description\"}, {\"WO_STATUS\", \"WO Status\"}, {\"WO_DESC\", \"WO Desciption\"}, {\"CASEWHENNVL(AL1.SOURCE_VENDOR_NAME,'X')<>'X'THENAL1.SOURCE_VENDOR_NAME||'_'||AL1.SOURCE_VENDOR_SITE_CODEEND\", \"Vendor Key\"}, {\"PLAN_NAME\", \"Plan Name\"}, {\"CATEGORY_CONCAT_SEGS\", \"Shipment Priority\"}, {\"SCHEDULE_COMMENTS\", \"End Item Demand Schedule Comments\"}, {\"OLD_DUE_DATE\", \"Old Due Date\"}, {\"END_ITEM_QTY\", \"End Item Quantity\"}, {\"END_ITEM_DEMAND_DATE\", \"End Item Demand Date\"}, {\"DEMAND_ID\", \"Demand Id\"}, {\"END_ITEM_ORG_CODE\", \"End Item Org Code\"}, {\"DEMAND_ORG_FAMILY\", \"End Item Demand Org Family\"}, {\"DEMAND_ORG_LINE\", \"End Item Demand Org Line\"}, {\"DEMAND_ORG_FORECAST\", \"End Item Demand Forecast Field\"}, {\"DEMAND_SALES_COMMODITY\", \"End Item Demand Sales Commodity\"}, {\"FIRMED\", \"Firmed\"}, {\"ASCP_LEAD_TIME\", \"ASCP Lead Time\"}, {\"ITEM_TYPE\", \"Supply Item Type\"}, {\"ORDER_NUMBER\", \"Supply Order Number\"}, {\"ORDER_TYPE_TEXT\", \"Supply Order Type\"}, {\"PLANNER_CODE\", \"Planner Code\"}, {\"QUANTITY_RATE\", \"Quantity Rate\"}, {\"EXTRACT_DATE\", \"Extract Date\"}, {\"LOCAL_EXTRACT_DATE\", \"Local Extract Date\"}})\r\nin\r\n  #\"Renamed Columns\";\r\nshared Planned_Supply_Demand = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, Query=\"\nSELECT\n    sysdate extract_date,\n    sdd.date_run,\n    from_tz(cast (sysdate as timestamp),'PST') at time zone '\"&Local&\"' local_extract_date,\n    sdd.plan_name,\n    sdd.firmed,\n    sdd.supply_or_demand,\n    sdd.inventory_item_id,\n    sdd.item,\n    sdd.description,\n    sdd.make_buy,\n    sdd.item_type,\n    sdd.plan_method,\n    sdd.active_or_inactive,\n    sdd.planner_code,\n    sdd.buyer_name,\n    CASE\n        WHEN source_org_supplier LIKE 'PRD:%' THEN\n            substr(sdd.source_org_supplier, 5, 3)\n        WHEN source_org_supplier IS NULL THEN\n            mp.organization_code\n        ELSE\n            sdd.source_org_supplier\n    END source_org_supplier,\n    sdd.calc_order_type,\n    sdd.mrp_lt,\n    sdd.active_supplier_lt,\n    sdd.full_supplier_lt,\n    sdd.order_number,\n    sdd.quantity_rate,\n    abs(sdd.quantity_rate) quantity,\n    sdd.po_line_location_id,\n    sdd.old_due_date,\n    sdd.old_dock_date,\n    CASE\n        WHEN sdd.sugg_dock_date <= sdd.date_run THEN\n            sdd.date_run\n        ELSE\n            sdd.sugg_dock_date\n    END sugg_dock_date,\n    CASE\n        WHEN sdd.sugg_due_date <= sdd.date_run THEN\n            sdd.date_run\n        ELSE\n            sdd.sugg_due_date\n    END sugg_due_date,\n    sdd.calc_receipt_date_adjusted,\n    CASE\n        WHEN sdd.action = 'Reschedule Out'\n             AND sdd.sugg_due_date <= sdd.date_run THEN\n            'Past Due'\n        ELSE\n            sdd.action\n    END recommended_action,\n    sdd.reschedule_days,\n    CASE\n        WHEN sdd.calc_order_type = 'Planned Order' THEN\n            sdd.compression_days\n        ELSE\n            0\n    END compression_days,\n    (\n        SELECT\n            pvs.vendor_site_id\n        FROM\n            apps.ap_suppliers                    pv,\n            apps.po_vendor_sites_all             pvs,\n            apps.org_organization_definitions    ood\n        WHERE\n                pvs.vendor_id = pv.vendor_id\n            AND pvs.vendor_site_code = sdd.source_vendor_site_code\n            AND pv.vendor_name = sdd.source_vendor_name\n            AND pvs.org_id = ood.operating_unit\n            AND ood.organization_id = mp.organization_id\n    ) vendor_site_id,\n    CASE\n        WHEN sdd.action = 'Release'\n             AND sdd.compression_days >= 1 THEN\n            'Compressed'\n        WHEN sdd.action = 'Reschedule Out'    THEN\n            CASE\n                WHEN (\n                    SELECT\n                        ( period_year * 4 ) + quarter_num\n                    FROM\n                        apps.gl_periods\n                    WHERE\n                        trunc(nvl(sugg_dock_date, sugg_due_date)) BETWEEN start_date AND end_date\n                        AND period_set_name = 'COHR Calendar'\n                ) > (\n                    SELECT\n                        ( period_year * 4 ) + quarter_num\n                    FROM\n                        apps.gl_periods\n                    WHERE\n                        trunc(sysdate) BETWEEN start_date AND end_date\n                        AND period_set_name = 'COHR Calendar'\n                )\n                     AND (\n                    SELECT\n                        ( period_year * 4 ) + quarter_num\n                    FROM\n                        apps.gl_periods\n                    WHERE\n                        trunc(nvl(old_dock_date, old_due_date)) BETWEEN start_date AND end_date\n                        AND period_set_name = 'COHR Calendar'\n                ) = (\n                    SELECT\n                        ( period_year * 4 ) + quarter_num\n                    FROM\n                        apps.gl_periods\n                    WHERE\n                        trunc(sysdate) BETWEEN start_date AND end_date\n                        AND period_set_name = 'COHR Calendar'\n                ) THEN\n                    'Reschedule Out of Current Quarter'\n            WHEN (\n                    SELECT\n                        ( period_year * 12 ) + period_num\n                    FROM\n                        apps.gl_periods\n                    WHERE\n                        trunc(nvl(sugg_dock_date, sugg_due_date)) BETWEEN start_date AND end_date\n                        AND period_set_name = 'COHR Calendar'\n                ) > (\n                    SELECT\n                        ( period_year * 12 ) + period_num\n                    FROM\n                        apps.gl_periods\n                    WHERE\n                        trunc(sysdate) BETWEEN start_date AND end_date\n                        AND period_set_name = 'COHR Calendar'\n                )\n                     AND (\n                    SELECT\n                        ( period_year * 12 ) + period_num\n                    FROM\n                        apps.gl_periods\n                    WHERE\n                        trunc(nvl(old_dock_date, old_due_date)) BETWEEN start_date AND end_date\n                        AND period_set_name = 'COHR Calendar'\n                ) = (\n                    SELECT\n                        ( period_year * 12 ) + period_num\n                    FROM\n                        apps.gl_periods\n                    WHERE\n                        trunc(sysdate) BETWEEN start_date AND end_date\n                        AND period_set_name = 'COHR Calendar'\n                ) THEN\n                    'Reschedule Out of Current Period'\n                WHEN sdd.sugg_due_date <= sdd.date_run THEN\n                    'Past Due'\n                ELSE\n                    sdd.action\n            END\n        WHEN sdd.action = 'Cancel'            THEN\n            'Cancel'\n        WHEN sdd.action = 'Reschedule In'     THEN\n            CASE\n            WHEN (\n                    SELECT\n                        ( period_year * 12 ) + Period_num\n                    FROM\n                        apps.gl_periods\n                    WHERE\n                        trunc(nvl(sugg_dock_date, sugg_due_date)) BETWEEN start_date AND end_date\n                        AND period_set_name = 'COHR Calendar'\n                ) = (\n                    SELECT\n                        ( period_year * 12 ) + Period_num\n                    FROM\n                        apps.gl_periods\n                    WHERE\n                        trunc(date_run) BETWEEN start_date AND end_date\n                        AND period_set_name = 'COHR Calendar'\n                )\n                     AND (\n                    SELECT\n                        ( period_year * 12 ) + Period_num\n                    FROM\n                        apps.gl_periods\n                    WHERE\n                        trunc(nvl(old_dock_date, old_due_date)) BETWEEN start_date AND end_date\n                        AND period_set_name = 'COHR Calendar'\n                ) > (\n                    SELECT\n                        ( period_year * 12 ) + Period_num\n                    FROM\n                        apps.gl_periods\n                    WHERE\n                        trunc(date_run) BETWEEN start_date AND end_date\n                        AND period_set_name = 'COHR Calendar'\n                ) THEN\n                    'Reschedule Into Current Period'\n                WHEN (\n                    SELECT\n                        ( period_year * 4 ) + quarter_num\n                    FROM\n                        apps.gl_periods\n                    WHERE\n                        trunc(nvl(sugg_dock_date, sugg_due_date)) BETWEEN start_date AND end_date\n                        AND period_set_name = 'COHR Calendar'\n                ) = (\n                    SELECT\n                        ( period_year * 4 ) + quarter_num\n                    FROM\n                        apps.gl_periods\n                    WHERE\n                        trunc(date_run) BETWEEN start_date AND end_date\n                        AND period_set_name = 'COHR Calendar'\n                )\n                     AND (\n                    SELECT\n                        ( period_year * 4 ) + quarter_num\n                    FROM\n                        apps.gl_periods\n                    WHERE\n                        trunc(nvl(old_dock_date, old_due_date)) BETWEEN start_date AND end_date\n                        AND period_set_name = 'COHR Calendar'\n                ) > (\n                    SELECT\n                        ( period_year * 4 ) + quarter_num\n                    FROM\n                        apps.gl_periods\n                    WHERE\n                        trunc(date_run) BETWEEN start_date AND end_date\n                        AND period_set_name = 'COHR Calendar'\n                ) THEN\n                    'Reschedule Into Current Quarter'\n                ELSE\n                    sdd.action\n            END\n        ELSE\n            'Not Applicable'\n    END exception,\n    sdd.customer_name\nFROM\n    xxcoh.xxcoh_supply_demand_dmart    sdd,\n    apps.mtl_parameters                mp,\n    apps.mtl_system_items_b            msi\nWHERE\n        sdd.organization_id = mp.organization_id\n    AND sdd.inventory_item_id = msi.inventory_item_id\n    AND sdd.organization_id = msi.organization_id\n    AND mp.organization_code = '\"&ORG&\"'\n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"DATE_RUN\", \"Date Run\"}, {\"PLAN_NAME\", \"Plan Name\"}, {\"FIRMED\", \"Firmed\"}, {\"SUPPLY_OR_DEMAND\", \"Supply or Demand\"}, {\"ITEM\", \"Item Number\"}, {\"DESCRIPTION\", \"Item Description\"}, {\"MAKE_BUY\", \"Make Or Buy\"}, {\"ITEM_TYPE\", \"Item Type\"}, {\"PLAN_METHOD\", \"Planning Method\"}, {\"ACTIVE_OR_INACTIVE\", \"Active or Inactive\"}, {\"PLANNER_CODE\", \"Planner Code\"}, {\"BUYER_NAME\", \"Buyer Name\"}, {\"SOURCE_ORG_SUPPLIER\", \"Source Org or Supplier\"}, {\"CALC_ORDER_TYPE\", \"Order Type\"}, {\"MRP_LT\", \"MRP LT\"}, {\"ACTIVE_SUPPLIER_LT\", \"Active Supplier LT\"}, {\"FULL_SUPPLIER_LT\", \"Full Supplier LT\"}, {\"QUANTITY_RATE\", \"Quantity Rate\"}, {\"QUANTITY\", \"Quantity\"}, {\"SUGG_DUE_DATE\", \"Suggested Due Date\"}, {\"OLD_DUE_DATE\", \"Old Due Date\"}, {\"OLD_DOCK_DATE\", \"Old Dock Date\"}, {\"CALC_RECEIPT_DATE_ADJUSTED\", \"Receipt Date Adjusted\"}, {\"SUGG_DOCK_DATE\", \"Suggested Dock Date\"}, {\"RECOMMENDED_ACTION\", \"Recommended Action\"}, {\"RESCHEDULE_DAYS\", \"Reschedule Days\"}, {\"ORDER_NUMBER\", \"Order Number\"}, {\"COMPRESSION_DAYS\", \"Compression Days\"}, {\"EXCEPTION\", \"Exception\"}, {\"CUSTOMER_NAME\", \"Customer Name\"}, {\"EXTRACT_DATE\", \"Extract Date\"}, {\"LOCAL_EXTRACT_DATE\", \"Local Extract Date\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Local = let\r\n  Local = \"Asia/Singapore\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type text]\r\nin\r\n  Local;\r\nshared Master_Demand_Schedule = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, \n  Query=\"\nSELECT\n    sysdate                                                                     extract_date,\n    trunc(mds.creation_date)                                                    mds_date,\n    from_tz(CAST(sysdate AS TIMESTAMP), 'PST') AT TIME ZONE '\"&Local&\"'         local_extract_date,\n    mp.organization_code,\n    msi.inventory_item_id,\n    msi.segment1 item_number,\n    msi.description item_description,\n    mds.source_forecast_designator,\n    mds.schedule_date,\n    mds.Schedule_Designator MDS_NAME,\n    mds.Schedule_Quantity,\n    mds.Schedule_Comments,\n    decode(mds.Schedule_Origination_Type,1,'Manual',\n    10,'Overconsumption',2,'Copied Forecast',3,'Outside Load',4,'Focus Forecasting',5,'Statistical Forecasting',8,'Exploded') schedule_origin,\n    mds.Schedule_Origination_Type SCHEDULE_ORIGIN_ID,\n    decode(msi.bom_item_type,1,'Model',2,'Option Class',3,'Planning',4,'Standard',5,'Product Family') BOM_Type,\n    msi.bom_item_type BOM_TYPE_ID,\n    msi.item_type\nFROM\n    apps.mrp_schedule_item_dates_v    mds,\n    apps.mtl_system_items_b           msi,\n    apps.mtl_parameters               mp\nWHERE\n        mp.organization_id = mds.organization_id\n    AND msi.inventory_item_id = mds.inventory_item_id\n    AND mp.organization_id = msi.organization_id\n    AND mp.organization_code = '\"&ORG&\"'\n    AND mds.source_code = 'MRCSAL'\n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"EXTRACT_DATE\", \"Extract Date\"}, {\"MDS_DATE\", \"MDS Creation Date\"}, {\"ORGANIZATION_CODE\", \"Organization Code\"}, {\"ITEM_NUMBER\", \"Item Number\"}, {\"MDS_NAME\", \"MDS Name\"}, {\"SCHEDULE_QUANTITY\", \"Quantity\"}, {\"SCHEDULE_COMMENTS\", \"Schedule Comments\"}, {\"SOURCE_FORECAST_DESIGNATOR\", \"Source Forecast Designator\"}, {\"ITEM_TYPE\", \"Item Type Code\"}, {\"LOCAL_EXTRACT_DATE\", \"Local Extract Date\"}, {\"ITEM_DESCRIPTION\", \"Item Description\"}, {\"SCHEDULE_DATE\", \"MDS Date\"}, {\"SCHEDULE_ORIGIN\", \"Schedule Origin\"}, {\"BOM_TYPE\", \"BOM Type\"}}),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Renamed columns\", {{\"Quantity\", type number}})\r\nin\r\n  #\"Changed column type\";\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"Safety_Stock","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Safety_Stock.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Organization Code","dataType":"string"},{"name":"Local Extract Date","dataType":"dateTime"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"Item Number","dataType":"string"},{"name":"Safety Stock Code","dataType":"double"},{"name":"Safety Stock Percent","dataType":"double"},{"name":"Safety Stock Quantity","dataType":"double"},{"name":"Service Level","dataType":"double"},{"name":"Effectivity Date","dataType":"dateTime"},{"name":"Latest Effectivity Date","dataType":"dateTime"},{"name":"Current Flag","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-13T08:00:17.5264498+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/204f8785-0f0a-4fca-9925-b85cdd1a822e/Safety_Stock.csv?snapshot=2022-06-13T08%3A00%3A17.4751718Z"}]},{"$type":"LocalEntity","name":"Gross_Requirement","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Gross_Requirement.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Plan Date","dataType":"dateTime"},{"name":"Local Extract Date","dataType":"dateTime"},{"name":"Organization Code","dataType":"string"},{"name":"Item Number","dataType":"string"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"Demand Date","dataType":"dateTime"},{"name":"Demand Origin","dataType":"string"},{"name":"Quantity","dataType":"double"},{"name":"Compile Designator","dataType":"string"},{"name":"Demand Class","dataType":"string"},{"name":"Item Type","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-13T08:00:18.5264544+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/204f8785-0f0a-4fca-9925-b85cdd1a822e/Gross_Requirement.csv?snapshot=2022-06-13T08%3A00%3A18.4446239Z"}]},{"$type":"LocalEntity","name":"ASCP_Pegging","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"ASCP_Pegging.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Date Run","dataType":"dateTime"},{"name":"Local Extract Date","dataType":"dateTime"},{"name":"End Item Demand Org Family","dataType":"string"},{"name":"End Item Demand Org Line","dataType":"string"},{"name":"End Item Demand Forecast Field","dataType":"string"},{"name":"End Item Demand Sales Commodity","dataType":"string"},{"name":"Org","dataType":"string"},{"name":"Item Number","dataType":"string"},{"name":"Firmed","dataType":"string"},{"name":"Item Description","dataType":"string"},{"name":"Supply Item Type","dataType":"string"},{"name":"Planner Code","dataType":"string"},{"name":"Source Organization Code","dataType":"string"},{"name":"Supply Pegged Qty","dataType":"double"},{"name":"Demand Id","dataType":"double"},{"name":"End Item Demand Date","dataType":"dateTime"},{"name":"End Item Quantity","dataType":"double"},{"name":"Old Due Date","dataType":"dateTime"},{"name":"ASCP Lead Time","dataType":"double"},{"name":"Quantity Rate","dataType":"double"},{"name":"Supply Category","dataType":"string"},{"name":"Old Dock Date","dataType":"dateTime"},{"name":"Supply Reschedule Days","dataType":"string"},{"name":"Supply Compression Days","dataType":"double"},{"name":"Sugg Order Date","dataType":"dateTime"},{"name":"Sugg Start Date","dataType":"dateTime"},{"name":"Sugg Dock Date","dataType":"dateTime"},{"name":"Sugg Due Date","dataType":"dateTime"},{"name":"End Item Org Code","dataType":"string"},{"name":"End Item Number","dataType":"string"},{"name":"End Item Description","dataType":"string"},{"name":"End Item Make Buy","dataType":"string"},{"name":"End Item Planner Code","dataType":"string"},{"name":"End Item Type","dataType":"string"},{"name":"End Item Demand Type","dataType":"string"},{"name":"End Item Demand Order Number","dataType":"string"},{"name":"End Item Demand Order Type","dataType":"string"},{"name":"End Item Order Demand Order Line","dataType":"string"},{"name":"End Item Demand Customer","dataType":"string"},{"name":"Supply Order Number","dataType":"string"},{"name":"Firm Late","dataType":"string"},{"name":"Supply Order Type","dataType":"string"},{"name":"End Item Demand Schedule Comments","dataType":"string"},{"name":"Forecast Name","dataType":"string"},{"name":"Forecast Description","dataType":"string"},{"name":"WO Status","dataType":"string"},{"name":"WO Desciption","dataType":"string"},{"name":"Vendor Key","dataType":"string"},{"name":"Plan Name","dataType":"string"},{"name":"PO_LINE_LOCATION_ID","dataType":"double"},{"name":"Shipment Priority","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-13T08:01:25.6726654+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/204f8785-0f0a-4fca-9925-b85cdd1a822e/ASCP_Pegging.csv?snapshot=2022-06-13T08%3A01%3A25.6486500Z"}]},{"$type":"LocalEntity","name":"Planned_Supply_Demand","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Planned_Supply_Demand.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Date Run","dataType":"dateTime"},{"name":"Local Extract Date","dataType":"dateTime"},{"name":"Plan Name","dataType":"string"},{"name":"Firmed","dataType":"string"},{"name":"Supply or Demand","dataType":"string"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"Item Number","dataType":"string"},{"name":"Item Description","dataType":"string"},{"name":"Make Or Buy","dataType":"string"},{"name":"Item Type","dataType":"string"},{"name":"Planning Method","dataType":"string"},{"name":"Active or Inactive","dataType":"string"},{"name":"Planner Code","dataType":"string"},{"name":"Buyer Name","dataType":"string"},{"name":"Source Org or Supplier","dataType":"string"},{"name":"Order Type","dataType":"string"},{"name":"MRP LT","dataType":"double"},{"name":"Active Supplier LT","dataType":"double"},{"name":"Full Supplier LT","dataType":"double"},{"name":"Order Number","dataType":"string"},{"name":"Quantity Rate","dataType":"double"},{"name":"Quantity","dataType":"double"},{"name":"PO_LINE_LOCATION_ID","dataType":"double"},{"name":"Old Due Date","dataType":"dateTime"},{"name":"Old Dock Date","dataType":"dateTime"},{"name":"Suggested Dock Date","dataType":"dateTime"},{"name":"Suggested Due Date","dataType":"dateTime"},{"name":"Receipt Date Adjusted","dataType":"dateTime"},{"name":"Recommended Action","dataType":"string"},{"name":"Reschedule Days","dataType":"double"},{"name":"Compression Days","dataType":"double"},{"name":"VENDOR_SITE_ID","dataType":"double"},{"name":"Exception","dataType":"string"},{"name":"Customer Name","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-13T08:01:58.9748825+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/204f8785-0f0a-4fca-9925-b85cdd1a822e/Planned_Supply_Demand.csv?snapshot=2022-06-13T08%3A01%3A58.9598277Z"}]},{"$type":"LocalEntity","name":"Master_Demand_Schedule","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Master_Demand_Schedule.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"MDS Creation Date","dataType":"dateTime"},{"name":"Local Extract Date","dataType":"dateTime"},{"name":"Organization Code","dataType":"string"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"Item Number","dataType":"string"},{"name":"Item Description","dataType":"string"},{"name":"Source Forecast Designator","dataType":"string"},{"name":"MDS Date","dataType":"dateTime"},{"name":"MDS Name","dataType":"string"},{"name":"Quantity","dataType":"double"},{"name":"Schedule Comments","dataType":"string"},{"name":"Schedule Origin","dataType":"string"},{"name":"SCHEDULE_ORIGIN_ID","dataType":"double"},{"name":"BOM Type","dataType":"string"},{"name":"BOM_TYPE_ID","dataType":"double"},{"name":"Item Type Code","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-13T08:00:17.2139447+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/204f8785-0f0a-4fca-9925-b85cdd1a822e/Master_Demand_Schedule.csv?snapshot=2022-06-13T08%3A00%3A17.1783384Z"}]}]}