{"name":"COHREP_SITE_FIN_TRX2","description":"Extract of financial related tables","version":"1.0","culture":"en-US","modifiedTime":"2021-03-08T03:43:01.4809716+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":true,"queriesMetadata":{"M2_TBU_Detail":{"queryId":"e458078d-bfee-4dbd-ba50-290ccc182817","queryName":"M2_TBU_Detail","loadEnabled":true},"LocalTZ":{"queryId":"348c686d-8b3d-4524-9e0d-623d862f1fea","queryName":"LocalTZ"},"Entity":{"queryId":"99bb2ac0-b97a-401b-a00b-6cd0fe5e0936","queryName":"Entity"},"TBU":{"queryId":"aee18836-4230-475e-b6df-13d4787694a4","queryName":"TBU"},"YearOffset":{"queryId":"437c4292-98c6-4246-b966-9503e37fbaa8","queryName":"YearOffset"},"M2_Entity_Detail":{"queryId":"48920b38-2bf1-42ee-8520-19436b8d0b0b","queryName":"M2_Entity_Detail","loadEnabled":true}},"document":"section Section1;\r\nshared M2_TBU_Detail = let\r\n  Source = Oracle.Database(\"COHREP\", [CommandTimeout = #duration(0, 0, 10, 0), Query = \"\r\n  SELECT\r\n    sysdate                                                                     extract_date,\r\n    from_tz(CAST(sysdate AS TIMESTAMP), 'PST') AT TIME ZONE '\"&LocalTZ&\"'       local_extract_date,\r\n    tb.*\r\nFROM\r\n    xxcoh.xxcoh_m2_report_tb tb\r\nWHERE\r\n        1 = 1\r\n    AND tb.period_year >= (\r\n        SELECT\r\n            period_year - \"&YearOffset&\"\r\n        FROM\r\n            gl.gl_periods gp\r\n        WHERE\r\n            trunc(sysdate) BETWEEN gp.start_date AND gp.end_date\r\n            AND period_set_name = 'COHR Calendar'\r\n    )\r\n    AND m20_tbu = '\"&TBU&\"'\"]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"ENTITY\", \"Entity\"}, {\"DEPT\", \"Department\"}, {\"ACCT\", \"Account\"}, {\"PROJ\", \"Project\"}, {\"INTERCO\", \"Inter Company\"}, {\"ITEM_NUMBER\", \"Item Number\"}, {\"ITEM_DESCRIPTION\", \"Description\"}, {\"TRANSACTION_SOURCE\", \"Transaction Source\"}, {\"CURRENCY_CODE\", \"Currency\"}, {\"SALES_SERVICE_CODE\", \"Sales Service Code\"}, {\"ACCOUNTED_NET\", \"Accounted Net\"}, {\"ACCOUNTED_NET_USD\", \"Accounted Net USD\"}, {\"GL_PERIOD\", \"GL Period\"}, {\"PERIOD_END_DATE\", \"Period End Date\"}, {\"M20_TBU\", \"M20 TBU\"}, {\"M20_PFC\", \"M20 PFC\"}, {\"ALLOCATION_PERCENT\", \"Allocation Percent\"}, {\"HFM_ACCOUNT\", \"HFM Account\"}, {\"HP_ACCOUNT\", \"HP Account\"}, {\"HFM_ICP\", \"HFM ICP\"}, {\"HFM_FUNCTION\", \"HFM Function\"}, {\"HFM_PRODUCT\", \"HFM Product\"}, {\"HP_PRODUCT\", \"HP Product\"}, {\"HFM_PRODUCT_GROUP\", \"HFM Product Group\"}, {\"HP_SPC_ACCOUNT\", \"HP SPC Account\"}, {\"CAT_SEGMENT1\", \"Item TBU\"}, {\"CAT_SEGMENT2\", \"Item Product Family\"}, {\"CAT_SEGMENT3\", \"Item Product Line\"}, {\"ALT_HFM_PRODUCT\", \"Alternate HFM Product\"}, {\"ALT_HFM_PRODUCT_GROUP\", \"Alternate HFM Product Group\"}, {\"ALT_HP_PRODUCT\", \"Alternate HP Product\"}, {\"PERIOD_YEAR\", \"Fiscal Year\"}, {\"EXTRACT_DATE\", \"Extract Date\"}, {\"CONCATENATED_SEGMENTS\", \"GL Code Combination\"}, {\"ENTERED_DR\", \"Entered DR\"}, {\"ENTERED_CR\", \"Entered CR\"}, {\"ACCOUNTED_DR\", \"Accounted DR\"}, {\"ACCOUNTED_CR\", \"Accounted CR\"}, {\"JE_ENTERED_DR\", \"JE Entered DR\"}, {\"JE_ENTERED_CR\", \"JE Entered CR\"}, {\"JE_ACCOUNTED_DR\", \"JE Accounted DR\"}, {\"JE_ACCOUNTED_CR\", \"JE Accounted CR\"}, {\"TRANS_DATE\", \"Transaction Date\"}, {\"ITEM_TYPE\", \"Item Type\"}, {\"JE_AMOUNT\", \"JE Amount\"}, {\"CREATED_BY\", \"Created By\"}, {\"CREATION_DATE\", \"Creation Date\"}, {\"PARENT_ACCOUNT\", \"Parent Account\"}, {\"PARENT_ACCOUNT_DESC\", \"Parent Account Description\"}, {\"VENDOR_NUMBER\", \"Vendor Number\"}, {\"VENDOR_NAME\", \"Vendor Name\"}, {\"TRX_TYPE_NAME\", \"Transaction Type Name\"}, {\"ORDER_TYPE\", \"Order Type\"}, {\"ORDER_LINE_TYPE\", \"Order Line Type\"}, {\"ORDER_NUMBER\", \"Order Number\"}, {\"ORDER_LINE\", \"Order Line\"}, {\"WIP_ACCOUNTING\", \"WIP Accounting\"}, {\"WIP_ACTIVITY\", \"WIP Activity\"}, {\"TRAN_QTY\", \"Transaction Quantity\"}, {\"CONVERSION_RATE\", \"Conversion Rate\"}, {\"PO_NUMBER\", \"PO Number\"}, {\"BUYER_NAME\", \"Buyer Name\"}, {\"QUARTER_NUM\", \"Quarter Number\"}, {\"ITEM_COST\", \"Item Cost\"}, {\"CORP_ITEM_COST\", \"Corporate Item Cost\"}, {\"CORP_ITEM_COST_USD\", \"Corporate Item Cost USD\"}, {\"PRIMARY_INV_ORG_CODE\", \"Primary Org\"}, {\"ACCOUNTING_LINE_TYPE\", \"Accounting Line Type\"}, {\"PO_PRICE\", \"PO Price\"}, {\"PO_UNIT_PRICE\", \"PO Unit Price\"}, {\"ITEM_MAT_COST\", \"Item Material Cost\"}, {\"TRANSACTION_SOURCE_NAME\", \"Transaction Source Name\"}, {\"APPLICATION_CODE\", \"Application Code\"}, {\"FISCAL_WEEK\", \"Fiscal Quarter Week\"}, {\"HFM_CUSTOM3\", \"HFM Custom3\"}, {\"HFM_CUSTOM4\", \"HFM Custom4\"}, {\"HFM_PRODUCT_SEQ\", \"HFM Product Sequence\"}, {\"HFM_LINE_SEQ\", \"HFM Line Sequence\"}, {\"MARKET_CODE\", \"Market Code\"}, {\"HP_MARKET\", \"HP Market\"}, {\"ALT_HFM_PRODUCT_SEQ\", \"Alternate HFM Product Sequence\"}, {\"ORG_TBU\", \"ORG TBU\"}, {\"ORG_PFC\", \"ORG PFC\"}, {\"SR_INCIDENT_NUMBER\", \"SR Incident Number\"}, {\"TRN_ORDER_NUMBER\", \"TRN Order Number\"}, {\"LOCAL_EXTRACT_DATE\", \"Local Extract Date\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared LocalTZ = let\r\n  Local = \"Asia/Singapore\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type text]\r\nin\r\n  Local;\r\nshared Entity = let\r\n  Entity = \"845\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type text]\r\nin\r\n  Entity;\r\nshared TBU = let\r\n  TBU = \"multi\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type text]\r\nin\r\n  TBU;\r\nshared YearOffset = let\r\n  YearOffset = \"3\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type text]\r\nin\r\n  YearOffset;\r\nshared M2_Entity_Detail = let\r\n  Source = Oracle.Database(\"COHREP\", [CommandTimeout = #duration(0, 0, 10, 0), Query = \"SELECT\r\n    sysdate                                                                     extract_date,\r\n    from_tz(CAST(sysdate AS TIMESTAMP), 'PST') AT TIME ZONE '\"&LocalTZ&\"'         local_extract_date,\r\n    tb.*\r\nFROM\r\n    xxcoh.xxcoh_m2_report_tb tb\r\nWHERE\r\n        1 = 1\r\n    AND tb.period_year >= (\r\n        SELECT\r\n            period_year - \"&YearOffset&\"\r\n        FROM\r\n            gl.gl_periods gp\r\n        WHERE\r\n            trunc(sysdate) BETWEEN gp.start_date AND gp.end_date\r\n            AND period_set_name = 'COHR Calendar'\r\n    )\r\n    AND tb.entity = '\"&Entity&\"'\"]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"ENTITY\", \"Entity\"}, {\"DEPT\", \"Department\"}, {\"ACCT\", \"Account\"}, {\"PROJ\", \"Project\"}, {\"INTERCO\", \"Inter Company\"}, {\"ITEM_NUMBER\", \"Item Number\"}, {\"ITEM_DESCRIPTION\", \"Description\"}, {\"TRANSACTION_SOURCE\", \"Transaction Source\"}, {\"CURRENCY_CODE\", \"Currency\"}, {\"SALES_SERVICE_CODE\", \"Sales Service Code\"}, {\"ACCOUNTED_NET\", \"Accounted Net\"}, {\"ACCOUNTED_NET_USD\", \"Accounted Net USD\"}, {\"GL_PERIOD\", \"GL Period\"}, {\"PERIOD_END_DATE\", \"Period End Date\"}, {\"M20_TBU\", \"M20 TBU\"}, {\"M20_PFC\", \"M20 PFC\"}, {\"ALLOCATION_PERCENT\", \"Allocation Percent\"}, {\"HFM_ACCOUNT\", \"HFM Account\"}, {\"HP_ACCOUNT\", \"HP Account\"}, {\"HFM_ICP\", \"HFM ICP\"}, {\"HFM_FUNCTION\", \"HFM Function\"}, {\"HFM_PRODUCT\", \"HFM Product\"}, {\"HP_PRODUCT\", \"HP Product\"}, {\"HFM_PRODUCT_GROUP\", \"HFM Product Group\"}, {\"HP_SPC_ACCOUNT\", \"HP SPC Account\"}, {\"CAT_SEGMENT1\", \"Item TBU\"}, {\"CAT_SEGMENT2\", \"Item Product Family\"}, {\"CAT_SEGMENT3\", \"Item Product Line\"}, {\"ALT_HFM_PRODUCT\", \"Alternate HFM Product\"}, {\"ALT_HFM_PRODUCT_GROUP\", \"Alternate HFM Product Group\"}, {\"ALT_HP_PRODUCT\", \"Alternate HP Product\"}, {\"PERIOD_YEAR\", \"Fiscal Year\"}, {\"EXTRACT_DATE\", \"Extract Date\"}, {\"CONCATENATED_SEGMENTS\", \"GL Code Combination\"}, {\"ENTERED_DR\", \"Entered DR\"}, {\"ENTERED_CR\", \"Entered CR\"}, {\"ACCOUNTED_DR\", \"Accounted DR\"}, {\"ACCOUNTED_CR\", \"Accounted CR\"}, {\"JE_ENTERED_DR\", \"JE Entered DR\"}, {\"JE_ENTERED_CR\", \"JE Entered CR\"}, {\"JE_ACCOUNTED_DR\", \"JE Accounted DR\"}, {\"JE_ACCOUNTED_CR\", \"JE Accounted CR\"}, {\"TRANS_DATE\", \"Transaction Date\"}, {\"ITEM_TYPE\", \"Item Type\"}, {\"JE_AMOUNT\", \"JE Amount\"}, {\"CREATED_BY\", \"Created By\"}, {\"CREATION_DATE\", \"Creation Date\"}, {\"PARENT_ACCOUNT\", \"Parent Account\"}, {\"PARENT_ACCOUNT_DESC\", \"Parent Account Description\"}, {\"VENDOR_NUMBER\", \"Vendor Number\"}, {\"VENDOR_NAME\", \"Vendor Name\"}, {\"TRX_TYPE_NAME\", \"Transaction Type Name\"}, {\"ORDER_TYPE\", \"Order Type\"}, {\"ORDER_LINE_TYPE\", \"Order Line Type\"}, {\"ORDER_NUMBER\", \"Order Number\"}, {\"ORDER_LINE\", \"Order Line\"}, {\"WIP_ACCOUNTING\", \"WIP Accounting\"}, {\"WIP_ACTIVITY\", \"WIP Activity\"}, {\"TRAN_QTY\", \"Transaction Quantity\"}, {\"CONVERSION_RATE\", \"Conversion Rate\"}, {\"PO_NUMBER\", \"PO Number\"}, {\"BUYER_NAME\", \"Buyer Name\"}, {\"QUARTER_NUM\", \"Quarter Number\"}, {\"ITEM_COST\", \"Item Cost\"}, {\"CORP_ITEM_COST\", \"Corporate Item Cost\"}, {\"CORP_ITEM_COST_USD\", \"Corporate Item Cost USD\"}, {\"PRIMARY_INV_ORG_CODE\", \"Primary Org\"}, {\"ACCOUNTING_LINE_TYPE\", \"Accounting Line Type\"}, {\"PO_PRICE\", \"PO Price\"}, {\"PO_UNIT_PRICE\", \"PO Unit Price\"}, {\"ITEM_MAT_COST\", \"Item Material Cost\"}, {\"TRANSACTION_SOURCE_NAME\", \"Transaction Source Name\"}, {\"APPLICATION_CODE\", \"Application Code\"}, {\"FISCAL_WEEK\", \"Fiscal Quarter Week\"}, {\"HFM_CUSTOM3\", \"HFM Custom3\"}, {\"HFM_CUSTOM4\", \"HFM Custom4\"}, {\"HFM_PRODUCT_SEQ\", \"HFM Product Sequence\"}, {\"HFM_LINE_SEQ\", \"HFM Line Sequence\"}, {\"MARKET_CODE\", \"Market Code\"}, {\"HP_MARKET\", \"HP Market\"}, {\"ALT_HFM_PRODUCT_SEQ\", \"Alternate HFM Product Sequence\"}, {\"ORG_TBU\", \"ORG TBU\"}, {\"ORG_PFC\", \"ORG PFC\"}, {\"SR_INCIDENT_NUMBER\", \"SR Incident Number\"}, {\"TRN_ORDER_NUMBER\", \"TRN Order Number\"}, {\"LOCAL_EXTRACT_DATE\", \"Local Extract Date\"}})\r\nin\r\n  #\"Renamed columns\";\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"M2_TBU_Detail","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"M2_TBU_Detail.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Local Extract Date","dataType":"dateTime"},{"name":"GL Code Combination","dataType":"string"},{"name":"Entity","dataType":"string"},{"name":"Department","dataType":"string"},{"name":"Account","dataType":"string"},{"name":"Project","dataType":"string"},{"name":"Inter Company","dataType":"string"},{"name":"TBD","dataType":"string"},{"name":"CODE_COMBO_ID","dataType":"double"},{"name":"GL Period","dataType":"string"},{"name":"JE_BATCH_ID","dataType":"double"},{"name":"JE_HEADER_ID","dataType":"double"},{"name":"JE_LINE_NUM","dataType":"double"},{"name":"Item Number","dataType":"string"},{"name":"Description","dataType":"string"},{"name":"Item TBU","dataType":"string"},{"name":"Item Product Family","dataType":"string"},{"name":"Item Product Line","dataType":"string"},{"name":"GL_SL_LINK_ID","dataType":"double"},{"name":"GL_SL_LINK_TABLE","dataType":"string"},{"name":"TRANSACTION_ID","dataType":"double"},{"name":"Transaction Source","dataType":"string"},{"name":"Entered DR","dataType":"double"},{"name":"Entered CR","dataType":"double"},{"name":"Accounted DR","dataType":"double"},{"name":"Accounted CR","dataType":"double"},{"name":"JE Entered DR","dataType":"double"},{"name":"JE Entered CR","dataType":"double"},{"name":"JE Accounted DR","dataType":"double"},{"name":"JE Accounted CR","dataType":"double"},{"name":"Transaction Date","dataType":"dateTime"},{"name":"JE Amount","dataType":"double"},{"name":"Item Type","dataType":"string"},{"name":"Currency","dataType":"string"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"ORGANIZATION_ID","dataType":"double"},{"name":"ITEM_CATEGORY_ID","dataType":"double"},{"name":"Created By","dataType":"double"},{"name":"Creation Date","dataType":"dateTime"},{"name":"SITE","dataType":"string"},{"name":"SET_OF_BOOKS_ID","dataType":"double"},{"name":"Parent Account","dataType":"string"},{"name":"Parent Account Description","dataType":"string"},{"name":"VENDOR_ID","dataType":"double"},{"name":"Vendor Number","dataType":"string"},{"name":"Vendor Name","dataType":"string"},{"name":"ORG_ID","dataType":"double"},{"name":"Sales Service Code","dataType":"string"},{"name":"TRX_TYPE_ID","dataType":"double"},{"name":"Transaction Type Name","dataType":"string"},{"name":"Order Type","dataType":"string"},{"name":"Order Line Type","dataType":"string"},{"name":"Order Number","dataType":"double"},{"name":"ORDER_LINE_ID","dataType":"double"},{"name":"ORDER_HEADER_ID","dataType":"double"},{"name":"Order Line","dataType":"double"},{"name":"WIP Accounting","dataType":"string"},{"name":"WIP Activity","dataType":"string"},{"name":"WIP_ENTITY_ID","dataType":"double"},{"name":"ORDER_LINE_TYPE_ID","dataType":"double"},{"name":"ORDER_TYPE_ID","dataType":"double"},{"name":"Transaction Quantity","dataType":"double"},{"name":"Conversion Rate","dataType":"double"},{"name":"CUSTOMER_ID","dataType":"double"},{"name":"AR_TRAN_ID","dataType":"double"},{"name":"BUYER_ID","dataType":"double"},{"name":"PO Number","dataType":"string"},{"name":"Buyer Name","dataType":"string"},{"name":"FC_SEGMENT1","dataType":"string"},{"name":"Fiscal Year","dataType":"double"},{"name":"Quarter Number","dataType":"double"},{"name":"Accounted Net","dataType":"double"},{"name":"Accounted Net USD","dataType":"double"},{"name":"Item Cost","dataType":"double"},{"name":"Corporate Item Cost","dataType":"double"},{"name":"Corporate Item Cost USD","dataType":"double"},{"name":"Primary Org","dataType":"string"},{"name":"EXT_ORDER_ID","dataType":"double"},{"name":"EXT_CUSTOMER_ID","dataType":"double"},{"name":"PO Price","dataType":"double"},{"name":"PO_LINE_ID","dataType":"double"},{"name":"PO_HEADER_ID","dataType":"double"},{"name":"COST_ELEMENT_ID","dataType":"double"},{"name":"Accounting Line Type","dataType":"string"},{"name":"PO Unit Price","dataType":"double"},{"name":"Item Material Cost","dataType":"double"},{"name":"AP_INVOICE_ID","dataType":"double"},{"name":"M20 TBU","dataType":"string"},{"name":"M20 PFC","dataType":"string"},{"name":"Application Code","dataType":"string"},{"name":"MMT_ID","dataType":"double"},{"name":"Transaction Source Name","dataType":"string"},{"name":"VAT_ID","dataType":"double"},{"name":"WIP_ACCOUNTING_CLASS","dataType":"string"},{"name":"Fiscal Quarter Week","dataType":"double"},{"name":"Period End Date","dataType":"dateTime"},{"name":"Allocation Percent","dataType":"double"},{"name":"COMMENTS","dataType":"string"},{"name":"HFM Account","dataType":"string"},{"name":"HP Account","dataType":"string"},{"name":"HFM ICP","dataType":"string"},{"name":"HFM Function","dataType":"string"},{"name":"HFM Product","dataType":"string"},{"name":"HP Product","dataType":"string"},{"name":"HFM Custom3","dataType":"string"},{"name":"HFM Custom4","dataType":"string"},{"name":"HFM Product Group","dataType":"string"},{"name":"HFM Product Sequence","dataType":"double"},{"name":"TEMPLATE_ID","dataType":"double"},{"name":"HFM Line Sequence","dataType":"double"},{"name":"HP SPC Account","dataType":"string"},{"name":"Market Code","dataType":"string"},{"name":"HP Market","dataType":"string"},{"name":"SR_INCIDENT_ID","dataType":"double"},{"name":"Alternate HFM Product","dataType":"string"},{"name":"Alternate HFM Product Group","dataType":"string"},{"name":"Alternate HFM Product Sequence","dataType":"double"},{"name":"Alternate HP Product","dataType":"string"},{"name":"TRN Order Number","dataType":"double"},{"name":"ORG TBU","dataType":"string"},{"name":"ORG PFC","dataType":"string"},{"name":"SR Incident Number","dataType":"string"},{"name":"SFDC_WO_ID","dataType":"string"},{"name":"SFDC_CASE_ID","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-05-19T23:01:57.4773328+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/0a2b73fc-0e67-49cc-85c5-c12e74ec8ef1/M2_TBU_Detail.csv?snapshot=2022-05-19T23%3A01%3A57.4202135Z"}]},{"$type":"LocalEntity","name":"M2_Entity_Detail","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"M2_Entity_Detail.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Local Extract Date","dataType":"dateTime"},{"name":"GL Code Combination","dataType":"string"},{"name":"Entity","dataType":"string"},{"name":"Department","dataType":"string"},{"name":"Account","dataType":"string"},{"name":"Project","dataType":"string"},{"name":"Inter Company","dataType":"string"},{"name":"TBD","dataType":"string"},{"name":"CODE_COMBO_ID","dataType":"double"},{"name":"GL Period","dataType":"string"},{"name":"JE_BATCH_ID","dataType":"double"},{"name":"JE_HEADER_ID","dataType":"double"},{"name":"JE_LINE_NUM","dataType":"double"},{"name":"Item Number","dataType":"string"},{"name":"Description","dataType":"string"},{"name":"Item TBU","dataType":"string"},{"name":"Item Product Family","dataType":"string"},{"name":"Item Product Line","dataType":"string"},{"name":"GL_SL_LINK_ID","dataType":"double"},{"name":"GL_SL_LINK_TABLE","dataType":"string"},{"name":"TRANSACTION_ID","dataType":"double"},{"name":"Transaction Source","dataType":"string"},{"name":"Entered DR","dataType":"double"},{"name":"Entered CR","dataType":"double"},{"name":"Accounted DR","dataType":"double"},{"name":"Accounted CR","dataType":"double"},{"name":"JE Entered DR","dataType":"double"},{"name":"JE Entered CR","dataType":"double"},{"name":"JE Accounted DR","dataType":"double"},{"name":"JE Accounted CR","dataType":"double"},{"name":"Transaction Date","dataType":"dateTime"},{"name":"JE Amount","dataType":"double"},{"name":"Item Type","dataType":"string"},{"name":"Currency","dataType":"string"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"ORGANIZATION_ID","dataType":"double"},{"name":"ITEM_CATEGORY_ID","dataType":"double"},{"name":"Created By","dataType":"double"},{"name":"Creation Date","dataType":"dateTime"},{"name":"SITE","dataType":"string"},{"name":"SET_OF_BOOKS_ID","dataType":"double"},{"name":"Parent Account","dataType":"string"},{"name":"Parent Account Description","dataType":"string"},{"name":"VENDOR_ID","dataType":"double"},{"name":"Vendor Number","dataType":"string"},{"name":"Vendor Name","dataType":"string"},{"name":"ORG_ID","dataType":"double"},{"name":"Sales Service Code","dataType":"string"},{"name":"TRX_TYPE_ID","dataType":"double"},{"name":"Transaction Type Name","dataType":"string"},{"name":"Order Type","dataType":"string"},{"name":"Order Line Type","dataType":"string"},{"name":"Order Number","dataType":"double"},{"name":"ORDER_LINE_ID","dataType":"double"},{"name":"ORDER_HEADER_ID","dataType":"double"},{"name":"Order Line","dataType":"double"},{"name":"WIP Accounting","dataType":"string"},{"name":"WIP Activity","dataType":"string"},{"name":"WIP_ENTITY_ID","dataType":"double"},{"name":"ORDER_LINE_TYPE_ID","dataType":"double"},{"name":"ORDER_TYPE_ID","dataType":"double"},{"name":"Transaction Quantity","dataType":"double"},{"name":"Conversion Rate","dataType":"double"},{"name":"CUSTOMER_ID","dataType":"double"},{"name":"AR_TRAN_ID","dataType":"double"},{"name":"BUYER_ID","dataType":"double"},{"name":"PO Number","dataType":"string"},{"name":"Buyer Name","dataType":"string"},{"name":"FC_SEGMENT1","dataType":"string"},{"name":"Fiscal Year","dataType":"double"},{"name":"Quarter Number","dataType":"double"},{"name":"Accounted Net","dataType":"double"},{"name":"Accounted Net USD","dataType":"double"},{"name":"Item Cost","dataType":"double"},{"name":"Corporate Item Cost","dataType":"double"},{"name":"Corporate Item Cost USD","dataType":"double"},{"name":"Primary Org","dataType":"string"},{"name":"EXT_ORDER_ID","dataType":"double"},{"name":"EXT_CUSTOMER_ID","dataType":"double"},{"name":"PO Price","dataType":"double"},{"name":"PO_LINE_ID","dataType":"double"},{"name":"PO_HEADER_ID","dataType":"double"},{"name":"COST_ELEMENT_ID","dataType":"double"},{"name":"Accounting Line Type","dataType":"string"},{"name":"PO Unit Price","dataType":"double"},{"name":"Item Material Cost","dataType":"double"},{"name":"AP_INVOICE_ID","dataType":"double"},{"name":"M20 TBU","dataType":"string"},{"name":"M20 PFC","dataType":"string"},{"name":"Application Code","dataType":"string"},{"name":"MMT_ID","dataType":"double"},{"name":"Transaction Source Name","dataType":"string"},{"name":"VAT_ID","dataType":"double"},{"name":"WIP_ACCOUNTING_CLASS","dataType":"string"},{"name":"Fiscal Quarter Week","dataType":"double"},{"name":"Period End Date","dataType":"dateTime"},{"name":"Allocation Percent","dataType":"double"},{"name":"COMMENTS","dataType":"string"},{"name":"HFM Account","dataType":"string"},{"name":"HP Account","dataType":"string"},{"name":"HFM ICP","dataType":"string"},{"name":"HFM Function","dataType":"string"},{"name":"HFM Product","dataType":"string"},{"name":"HP Product","dataType":"string"},{"name":"HFM Custom3","dataType":"string"},{"name":"HFM Custom4","dataType":"string"},{"name":"HFM Product Group","dataType":"string"},{"name":"HFM Product Sequence","dataType":"double"},{"name":"TEMPLATE_ID","dataType":"double"},{"name":"HFM Line Sequence","dataType":"double"},{"name":"HP SPC Account","dataType":"string"},{"name":"Market Code","dataType":"string"},{"name":"HP Market","dataType":"string"},{"name":"SR_INCIDENT_ID","dataType":"double"},{"name":"Alternate HFM Product","dataType":"string"},{"name":"Alternate HFM Product Group","dataType":"string"},{"name":"Alternate HFM Product Sequence","dataType":"double"},{"name":"Alternate HP Product","dataType":"string"},{"name":"TRN Order Number","dataType":"double"},{"name":"ORG TBU","dataType":"string"},{"name":"ORG PFC","dataType":"string"},{"name":"SR Incident Number","dataType":"string"},{"name":"SFDC_WO_ID","dataType":"string"},{"name":"SFDC_CASE_ID","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-05-19T23:03:05.5333992+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/0a2b73fc-0e67-49cc-85c5-c12e74ec8ef1/M2_Entity_Detail.csv?snapshot=2022-05-19T23%3A03%3A05.3350375Z"}]}]}