{"name":"Mapping","description":"Mapping tables to enrich the base data that is not stored anywhere in system","version":"1.0","culture":"en-US","modifiedTime":"2021-06-17T04:27:15.1532133+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"Planner_Code_Mapping":{"queryId":"1d60b71f-69f3-45d2-94fe-d6b4421e10e5","queryName":"Planner_Code_Mapping","loadEnabled":true},"Subinventory_Mapping":{"queryId":"1c0035fb-4487-44fe-8d19-228c2c6c6518","queryName":"Subinventory_Mapping","loadEnabled":true},"GL_Department_Mapping":{"queryId":"7591c8cc-58ac-4bdf-8c40-a25e2b1e7231","queryName":"GL_Department_Mapping","loadEnabled":true},"ORG":{"queryId":"35712e7d-f26b-4077-b396-3f1ecada378f","queryName":"ORG"},"Local_Item_Category":{"queryId":"784e5812-eb5e-47cb-894a-dbed7eabd4ff","queryName":"Local_Item_Category","loadEnabled":true},"GL_Account_Mapping":{"queryId":"68162454-c03f-4b7b-9233-1dda6ffccc11","queryName":"GL_Account_Mapping","loadEnabled":true},"External_Revenue_Flowthrough":{"queryId":"235ca463-9790-4dc6-9546-358b563b1135","queryName":"External_Revenue_Flowthrough","loadEnabled":true}},"document":"section Section1;\r\nshared Planner_Code_Mapping = let\r\n  Source = Sql.Database(\"SGSINSSQLDEV1\", \"SPG_Database_Test\"),\r\n  Navigation = Source{[Schema = \"XXFACTS\", Item = \"FFDU_INV_PlannerCodeMapping\"]}[Data],\r\n  #\"Filtered rows\" = Table.SelectRows(Navigation, each [ORG] = ORG),\r\n  #\"Removed other columns\" = Table.SelectColumns(#\"Filtered rows\", {\"PLANNER_CODE\", \"PLANNER_GROUP\", \"PLANNER_PRODUCT_TYPE\", \"GL_DEPARTMENT_CODE\"}),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Removed other columns\", {{\"PLANNER_CODE\", \"Planner Code\"}, {\"PLANNER_GROUP\", \"Planner Group\"}, {\"PLANNER_PRODUCT_TYPE\", \"Planner Product Type\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Subinventory_Mapping = let\r\n  Source = Sql.Database(\"SGSINSSQLDEV1\", \"SPG_Database_Test\"),\r\n  Navigation = Source{[Schema = \"XXFACTS\", Item = \"FFDU_INV_SubInventoryMapping\"]}[Data],\r\n  #\"Filtered rows\" = Table.SelectRows(Navigation, each [ORG] = ORG),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Filtered rows\", {{\"SUB_INVENTORY_NAME\", \"Subinventory Name\"}, {\"SUB_INVENTORY_GROUP\", \"Subinventory Group\"}}),\r\n  #\"Removed other columns\" = Table.SelectColumns(#\"Renamed columns\", {\"Subinventory Name\", \"Subinventory Group\"})\r\nin\r\n  #\"Removed other columns\";\r\nshared GL_Department_Mapping = let\r\n  Source = Sql.Database(\"SGSINSSQLDEV1\", \"SPG_Database_Test\"),\r\n  Navigation = Source{[Schema = \"XXFACTS\", Item = \"FFDU_FIN_GLDepartmentMapping\"]}[Data],\r\n  #\"Filtered rows\" = Table.SelectRows(Navigation, each [ORG] = ORG),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Filtered rows\", {{\"GL_DEPARTMENT_CODE\", \"GL Department Code\"}, {\"DEPARTMENT_PRODUCT\", \"Department Product\"}, {\"DEPARTMENT_GROUP\", \"Department Group\"}, {\"DEPARTMENT_ALIAS\", \"Department Alias\"}}),\r\n  #\"Removed other columns\" = Table.SelectColumns(#\"Renamed columns\", {\"GL Department Code\", \"Department Product\", \"Department Group\", \"Department Alias\"})\r\nin\r\n  #\"Removed other columns\";\r\nshared ORG = let\r\n  ORG = \"PPG\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type text]\r\nin\r\n  ORG;\r\nshared Local_Item_Category = let\r\n  Source = Sql.Database(\"SGSINSSQLDEV1\", \"SPG_Database_Test\"),\r\n  Navigation = Source{[Schema = \"XXFACTS\", Item = \"FFDU_FIN_LocalItemCategory\"]}[Data],\r\n  #\"Filtered rows\" = Table.SelectRows(Navigation, each [ORG] = ORG),\r\n  #\"Removed columns\" = Table.RemoveColumns(#\"Filtered rows\", {\"PK_ID\", \"ORG\", \"ADDED_BY\", \"TIMESTAMP\"}),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Removed columns\", {{\"ITEM_NUMBER\", \"Item Number\"}, {\"WAVELENGTH_COLOR\", \"Wavelength Color\"}, {\"POWER_GROUP\", \"Power Group\"}, {\"MEASURE_PRODUCTION_OUTPUT\", \"Measure Production Output\"}, {\"MEASURE_SHIPMENT_OTD\", \"Measure Shipment OTD\"}, {\"WAVELENGTH_NM\", \"Wavelength\"}, {\"MODEL\", \"Model\"}, {\"FORECAST_TYPE\", \"Forecast Type\"}, {\"PRODUCTION_GROUP\", \"Production Group\"}, {\"FORECAST_GROUP\", \"Forecast Group\"}, {\"PACK_SIZE\", \"Pack Size\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared GL_Account_Mapping = let\r\n  Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"nZpbb9w2EEb/iuGHPuVBd1GPQS5GgSA2bKdFEQTBJl4gC9iJu9kU7b+v5BWHKWpzzsenOPYZiSJH5FA879+fnl+enT47PXvz8fmLF+fv3l5/fHH+8tX8G/vv8+tXZ+eXf8y/evv8+t3lz387uzx/d3H64dn704uL5Sp9X43V/O/54ct2/33+4bfNfrf5dLudf/wJG6qqZljDsJZhPcMmhDUVw9iTNuxJG/KkoWtR25qq7hk2MGz0sbGqSNtG1r0j65Cxakn3jl2YJoJNqG3dRBIpsOxdsJphDcPAk4YKJVKoOoiRd2HGyGCFKqCbNijfQoPyLbTsah3Eaoaxts0YeJ1Dxwar68hsGXr2pD1LpIFdbWBv1oyRV2ZkNx3ZYI1ssALF0CsT0PIRAhuF0LKbokk1LP0LsImNwoRGYc6jjmGBrIAVuunIqpqRVTUjWxdG9qQjq0NGVoeMbF2YMXbTFk01rHsD695lBSSzJRv6Zc1CV+vYWt+RMQ0VqkOWKQRhbHLo2Sj07KY9mwaHibynCwYq1QUjxU9ghVlA24qw1CsIQ0tbYN27DAPBBna1agBYv1b4L3f77efDyZvNp2/7HFy3Crykwa9fbyD+MBMI+KDhnYQfs+mv7f6wu9ueXOy3d7sfd08H9PXDw7Ke6WvpUdeimOO1houN6RS81do+40rOtNqjLsOq4Upj+qoJEt5Kba+HWmuM1jON1jNSEvTHSZfjQcGn4yTMO1LKmSBdfVhfvld//tjd322/Hk5+Ofn+4/7+drfNf4xpSoK6gqCmpHlNyZ3akju1bUHQUHCnYymjBpUMblPS5U1J7zW9HjQed+daUKgKei+UvBqhJGHnoL4kaCgIKhinecdQ0ryCwQ0lWR5KsjyUJOzyPaogqKB5U0GWL5vOh9nodp7397vPu8M/c9jvm8P26fl/ien0mId8uJzbtbl9eiWaS9iGr0T9+gma49KSXmlLeqPhrVa9zLjyqK1awnZa5SVVvMs2ScOVJFiGVcLFelra4fXaMPVavvfaDq8/rhECrmw3Z3zU8EnCB22YxAJZS+Ba68ha3PZoO41a22nUWkfWg5KRc2mljOok4UtVvrxNcilfstNoSqrytqR5bUnzupKdRkE51Rx9CTUoFO00Cnqv0TtinOeS5U7X+81f26eLj3FVRVzsWNH5WE2wqSJYWHcjV182++3Nyc32frM/LM+fi3i48OvN593t7pAtAsMxu5SL92Jz+uqJZff17u/tzf/ZR5e5R9hh/QT8cns/o7vNYfft6+NkWAUOnxzX8sbGxH74L1QjqAdQQ67UEqgjUE+gAUDdBKCBdOZQgX4aQI8HMnaBjN0ErhTWLYXtax5P0Y4l3pLMPSVHes2+8cirWEPlVbkj5qpyhuVPPQ3Ln2kZlj/TMix/WBUx55DPMPakzhG1YeRJXVXuyj6NZg8gE5Y9gExYVpU7Yq4qFzHUva4qFzHH6lgxT5WLmHNEbRhJJFeVS1jW+0lYVpVLGHhSV5WLmGNfGUbeBVeVi5ijyq2Yp8pFDOWbq8rFFxBizoF3xFjbPFUuYmywPFVuxTxVLmIskTxVLmLszfJUuRXzVLmIscHyVLkV81Q5w9Ar46lyEWOj4KlyhrGbOqrcinmqXMTQKLiqnGF5BSdi6KauKmcYWozYuuCqcrZQsrahRHJVOcPYTR1VztYstnyg7nVVuYixt95T5Qxja72jykUM1SGuKhcxNjl4qlzE2E09Vc5mcvKeuqpcwkjx46lyhqHs9VQ5w9DS5qlyEXNUuYg5qpy1La/KXcVPL0SVM5iocglG39ANZ8djCUdnFwlHBymGU1UubqWRKmew9KhUlTOcnXcZLjaGnV2sOFXlEq7kDFXl7HsHU+USrjSGqnKGszMjyxmmyqXGaD3DVDnDpSSgqpzhTJVbcarKpTdVwakql76rCMcVKUg4IUpBgsBmQYp5lIJK7qS4MylIOJSzIEWVi0GSRGRBJYMrqXIWVNJ7kiq3Bmmq3BqkqXIWVNB7miqXggQXLQUJqpwFFYyTpspZUMHgaqqcBZWMU0nCaqqcBRU0T1Pl0qbzYTZC2luK4aqcxeRVuVTCIlEjlbBKwUBVOcOlJZ2qclbXSdULVeUMF0tYpsqlqlGsScWrK0lAVTnDxXpa2uFRVS7h2qNKOzyqyiVc2W5SVS7hyJIynBlehosFspbAUJUzXNz2aDsNqMqlTZWIKxlJVbm4j5FwUZVLQSU7DUWVS6V8SfMUVc6CFEPMggrKKU2VsyBFlUs7jYLek1S5Y5CryhmWV+Ui5qhyhuUduBXzVDn70ondNIvwVTlDsSpnn3HF5jBVLrG+Kmd7BleViyWor8pZIuQkKYNyulWCMgqYQTlVzqCcKmdQTpUzKKfKpVcGQFlVLkJZVS5BoJ+yqtwK5VU5g8CV8qpc2tcs0OOqXNoLs8QjqpyRripne8m8KvfhXw==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t, Column2 = _t, Column3 = _t, Column4 = _t, Column5 = _t]),\r\n  #\"Promoted headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"ORG\", type text}, {\"GL_ACCOUNT_CODE\", type text}, {\"ACCOUNT_CATEGORY\", type text}, {\"NATURE\", type text}, {\"ACCOUNT_GROUP\", type text}}),\r\n  #\"Filtered rows\" = Table.SelectRows(#\"Changed column type\", each [ORG] = ORG),\r\n  #\"Removed columns\" = Table.RemoveColumns(#\"Filtered rows\", {\"ORG\"}),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Removed columns\", {{\"GL_ACCOUNT_CODE\", \"GL Account Code\"}, {\"ACCOUNT_CATEGORY\", \"Account Category\"}, {\"NATURE\", \"Nature\"}, {\"ACCOUNT_GROUP\", \"Account Group\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared External_Revenue_Flowthrough = let\r\n  Source = Sql.Databases(\"SGSINSSQLDEV1\"),\r\n  Navigation = Source{[Name = \"SPG_Database_Test\"]}[Data],\r\n  #\"Navigation 1\" = Navigation{[Schema = \"XXFACTS\", Item = \"FFDU_FIN_ExtRevFlowthrough\"]}[Data],\r\n  #\"Filtered rows\" = Table.SelectRows(#\"Navigation 1\", each [ORG] = ORG),\r\n  #\"Removed columns\" = Table.RemoveColumns(#\"Filtered rows\", {\"ADDED_BY\", \"TIMESTAMP\", \"PK_ID\", \"ORG\"}),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Removed columns\", {{\"ITEM_PRODUCT_FAMILY\", \"Item Product Family\"}, {\"PLANNER_GROUP\", \"Planner Group\"}, {\"LASER_TYPE\", \"Laser Type\"}, {\"FC_YEAR\", \"FC Year\"}, {\"EXTERNAL_REVENUE_FLOWTHROUGH\", \"External Revenue Flowthrough\"}, {\"PLANNER_CODE\", \"Planner Code\"}})\r\nin\r\n  #\"Renamed columns\";\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"Planner_Code_Mapping","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Planner_Code_Mapping.csv"},"attributes":[{"name":"Planner Code","dataType":"string"},{"name":"Planner Group","dataType":"string"},{"name":"Planner Product Type","dataType":"string"},{"name":"GL_DEPARTMENT_CODE","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-12T23:00:35.1503086+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/dd55de83-8465-43f2-91e0-239871160ab9/Planner_Code_Mapping.csv?snapshot=2022-06-12T23%3A00%3A34.9341234Z"}]},{"$type":"LocalEntity","name":"Subinventory_Mapping","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Subinventory_Mapping.csv"},"attributes":[{"name":"Subinventory Name","dataType":"string"},{"name":"Subinventory Group","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-12T23:02:45.7525647+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/dd55de83-8465-43f2-91e0-239871160ab9/Subinventory_Mapping.csv?snapshot=2022-06-12T23%3A02%3A44.5299297Z"}]},{"$type":"LocalEntity","name":"GL_Department_Mapping","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"GL_Department_Mapping.csv"},"attributes":[{"name":"GL Department Code","dataType":"string"},{"name":"Department Product","dataType":"string"},{"name":"Department Group","dataType":"string"},{"name":"Department Alias","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-12T23:01:53.7122271+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/dd55de83-8465-43f2-91e0-239871160ab9/GL_Department_Mapping.csv?snapshot=2022-06-12T23%3A01%3A53.3492240Z"}]},{"$type":"LocalEntity","name":"Local_Item_Category","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Local_Item_Category.csv"},"attributes":[{"name":"Item Number","dataType":"string"},{"name":"Wavelength Color","dataType":"string"},{"name":"Power Group","dataType":"string"},{"name":"Measure Production Output","dataType":"string"},{"name":"Measure Shipment OTD","dataType":"string"},{"name":"Wavelength","dataType":"string"},{"name":"Model","dataType":"string"},{"name":"Forecast Type","dataType":"string"},{"name":"Production Group","dataType":"string"},{"name":"Forecast Group","dataType":"string"},{"name":"Pack Size","dataType":"double"},{"name":"SERIES_MODEL","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-12T23:00:32.2470775+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/dd55de83-8465-43f2-91e0-239871160ab9/Local_Item_Category.csv?snapshot=2022-06-12T23%3A00%3A31.7269607Z"}]},{"$type":"LocalEntity","name":"GL_Account_Mapping","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"GL_Account_Mapping.csv"},"attributes":[{"name":"GL Account Code","dataType":"string"},{"name":"Account Category","dataType":"string"},{"name":"Nature","dataType":"string"},{"name":"Account Group","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-12T23:01:37.9124346+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/dd55de83-8465-43f2-91e0-239871160ab9/GL_Account_Mapping.csv?snapshot=2022-06-12T23%3A01%3A37.7771388Z"}]},{"$type":"LocalEntity","name":"External_Revenue_Flowthrough","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"External_Revenue_Flowthrough.csv"},"attributes":[{"name":"Item Product Family","dataType":"string"},{"name":"Planner Code","dataType":"string"},{"name":"Planner Group","dataType":"string"},{"name":"Laser Type","dataType":"string"},{"name":"FC Year","dataType":"int64"},{"name":"External Revenue Flowthrough","dataType":"double"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-12T23:00:30.814452+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/dd55de83-8465-43f2-91e0-239871160ab9/External_Revenue_Flowthrough.csv?snapshot=2022-06-12T23%3A00%3A30.4726789Z"}]}]}