{"name":"COHREP_SITE_INVENTORY_MASTER1","description":"","version":"1.0","culture":"en-US","modifiedTime":"2021-02-08T08:09:54.0384706+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":true,"queriesMetadata":{"ORG":{"queryId":"ab3ac0b4-9a95-48f8-a07a-f575480cbdd1","queryName":"ORG"},"Subinventory":{"queryId":"5b1ac5f8-1dd0-4c64-8a5a-e5c91c5af21a","queryName":"Subinventory","queryGroupId":"root","loadEnabled":true},"Item_Attribute":{"queryId":"d572e816-7b82-478f-b5e6-8120086a5885","queryName":"Item_Attribute","queryGroupId":"root","loadEnabled":true},"Item_Cost":{"queryId":"c26c22fe-5daa-4760-a20b-73c7c1c90141","queryName":"Item_Cost","queryGroupId":"root","loadEnabled":true},"Item_Category":{"queryId":"b27d8925-6899-4a90-93c7-2946080ae9ba","queryName":"Item_Category","queryGroupId":"root","loadEnabled":true},"Local":{"queryId":"937df82f-ecc2-4ad9-a29d-71948d5c4292","queryName":"Local"},"Item_Subinventory":{"queryId":"1221a755-c9c9-4088-a32f-decd68f134db","queryName":"Item_Subinventory","queryGroupId":"root","loadEnabled":true}},"document":"section Section1;\r\nshared ORG = let\r\n  #\"Organization Code\" = \"PPG\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type text]\r\nin\r\n  #\"Organization Code\";\r\nshared Subinventory = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, Query=\"\nSELECT\n  sysdate EXTRACT_DATE,\n    from_tz(cast (sysdate as timestamp),'PST') at time zone '\"&Local&\"' local_extract_date,\n  MP.organization_code,\n  MSECI.secondary_inventory_name SUBINVENTORY,\n  MSECI.description,\n  MSECI.disable_date,\n  CASE\n    WHEN nvl(MSECI.disable_date, sysdate + 1) < sysdate\n      THEN\n        'No'\n    ELSE\n      'Yes'\n  END ENABLED_SUBINVENTORY,\n  DECODE(MSECI.QUANTITY_TRACKED, 1, 'Yes', 2, 'No') QUANTITY_TRACKED,\n  DECODE(MSECI.ASSET_INVENTORY, 1, 'Yes', 'No') ASSET_SUBINVENTORY,\n  DECODE(MSECI.DEPRECIABLE_FLAG, 1, 'Yes', 'No') DEPRECIABLE_SUBINVENTORY,\n  DECODE(MSECI.INVENTORY_ATP_CODE, 1, 'Yes', 'No') ATP_SUBINVENTORY,\n  DECODE(MSECI.RESERVABLE_TYPE, 1, 'Yes', 'No') RESERVABLE_SUBINVENTORY,\n  DECODE(MSECI.AVAILABILITY_TYPE, 1, 'Yes', 'No') NETTABLE_SUBINVENTORY,\n  DECODE(MSECI.LOCATOR_TYPE, 1, 'None', 2, 'Prespecified', 3, 'Dynamic Entry', 5, 'Item Level') LOCATOR_CONTROL_TYPE,\n  MSECI.attribute1 SUBINVENTORY_CLASSIFICATION,\n  MSECI.picking_order,\n  (SELECT\n    concatenated_segments\n  FROM APPS.GL_CODE_COMBINATIONS_kfv GCC\n  WHERE GCC.code_combination_id = MSECI.MATERIAL_ACCOUNT)\n  MATERIAL_ACCOUNT,\n  (SELECT\n    concatenated_segments\n  FROM APPS.GL_CODE_COMBINATIONS_kfv GCC\n  WHERE GCC.code_combination_id = MSECI.EXPENSE_ACCOUNT)\n  EXPENSE_ACCOUNT,\n  (SELECT\n    concatenated_segments\n  FROM APPS.GL_CODE_COMBINATIONS_kfv GCC\n  WHERE GCC.code_combination_id = MSECI.OUTSIDE_PROCESSING_ACCOUNT)\n  OSP_ACCOUNT,\n  (SELECT\n    concatenated_segments\n  FROM APPS.GL_CODE_COMBINATIONS_kfv GCC\n  WHERE GCC.code_combination_id = MSECI.OVERHEAD_ACCOUNT)\n  OVERHEAD_ACCOUNT,\n  (SELECT\n    concatenated_segments\n  FROM APPS.GL_CODE_COMBINATIONS_kfv GCC\n  WHERE GCC.code_combination_id = MSECI.RESOURCE_ACCOUNT)\n  RESOURCE_ACCOUNT,\n  (SELECT\n    concatenated_segments\n  FROM APPS.GL_CODE_COMBINATIONS_kfv GCC\n  WHERE GCC.code_combination_id = MSECI.MATERIAL_OVERHEAD_ACCOUNT)\n  MATERIAL_OVERHEAD_ACCOUNT\nFROM\n  inv.mtl_secondary_inventories MSECI,\n  inv.mtl_parameters MP\nWHERE\n  MP.organization_id = MSECI.organization_id\n  AND MP.organization_code = '\"&ORG&\"'\n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"EXTRACT_DATE\", \"Extract Date\"}, {\"DESCRIPTION\", \"Subinventory Description\"}, {\"SUBINVENTORY\", \"Subinventory Name\"}, {\"DISABLE_DATE\", \"Disable Date\"}, {\"ENABLED_SUBINVENTORY\", \"Enabled Flag\"}, {\"QUANTITY_TRACKED\", \"Quantity Tracked Flag\"}, {\"ASSET_SUBINVENTORY\", \"Asset Flag\"}, {\"DEPRECIABLE_SUBINVENTORY\", \"Depreciable Flag\"}, {\"ATP_SUBINVENTORY\", \"ATP Flag\"}, {\"RESERVABLE_SUBINVENTORY\", \"Reserveable Flag\"}, {\"NETTABLE_SUBINVENTORY\", \"Nettable Flag\"}, {\"LOCATOR_CONTROL_TYPE\", \"Subinventory Locator Type\"}, {\"SUBINVENTORY_CLASSIFICATION\", \"Class\"}, {\"PICKING_ORDER\", \"Picking Order\"}, {\"ORGANIZATION_CODE\", \"Organization Code\"}, {\"MATERIAL_ACCOUNT\", \"Material Account\"}, {\"EXPENSE_ACCOUNT\", \"Expense Account\"}, {\"OSP_ACCOUNT\", \"OSP Account\"}, {\"OVERHEAD_ACCOUNT\", \"Overhead Account\"}, {\"MATERIAL_OVERHEAD_ACCOUNT\", \"Material Overhead Account\"}, {\"RESOURCE_ACCOUNT\", \"Resource Account\"}, {\"LOCAL_EXTRACT_DATE\", \"Local Extract Date\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Item_Attribute = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, \n  Query=\"\n  SELECT\n    sysdate                                                                extract_date,\n    from_tz(cast (sysdate as timestamp),'PST') at time zone '\"&Local&\"' local_extract_date,\n    mp.organization_code,\n    msi.inventory_item_id,\n    msi.segment1                                                           item_number,\n    decode(msi.mrp_planning_code, 3, 'MRP Planning', 4, 'MPS Planning',\n           6, 'Not Planned', 7, 'MRP/MPP Planned', 8,\n           'MPS/MPP Planned', 9, 'MPP Planned') mrp_planning_code,\n    (\n        SELECT\n            MAX(mir.revision)\n        FROM\n            apps.mtl_item_revisions_b mir\n        WHERE\n                mir.organization_id = msi.organization_id\n            AND mir.inventory_item_id = msi.inventory_item_id\n            AND mir.organization_id = mp.organization_id\n            AND implementation_date = (\n                SELECT\n                    MAX(implementation_date)\n                FROM\n                    apps.mtl_item_revisions_b mir\n                WHERE\n                        mir.organization_id = msi.organization_id\n                    AND mir.organization_id = mp.organization_id\n                    AND mir.inventory_item_id = msi.inventory_item_id\n            )\n    ) item_revision,\n    msi.description,\n    msi.primary_unit_of_measure,\n    msi.inventory_item_status_code                                         item_status,\n    (\n        SELECT\n            meaning\n        FROM\n            apps.fnd_lookup_values_vl flv\n        WHERE\n                flv.lookup_type = 'ITEM_TYPE'\n            AND flv.lookup_code = msi.item_type\n            AND flv.view_application_id = 3\n            AND ROWNUM = 1\n    ) item_type,\n    msi.inventory_item_flag,\n    decode(msi.lot_control_code, 2, 'Full Control', 'No Control')          lot_control_code,\n    decode(msi.serial_number_control_code, 1, 'No Control', 5, 'At Receipt',\n           2, 'Predefined', 6, 'At Sales Order Issue') serial_control_code,\n    decode(msi.receiving_routing_id, 1, 'Standard', 2, 'Inspection',\n           3, 'Direct', msi.receiving_routing_id) receipt_routing,\n    (\n        SELECT\n            agent_name\n        FROM\n            apps.po_agents_v poa\n        WHERE\n            poa.agent_id = msi.buyer_id\n    ) default_buyer,\n    msi.buyer_id,\n    decode(planning_make_buy_code, 1, 'Make', 2, 'Buy')                    planning_make_buy_code,\n    nvl((\n        SELECT\n            conversion_rate\n        FROM\n            apps.gl_daily_rates_v                gdr, apps.org_organization_definitions    ood, apps.gl_sets_of_books                sob\n        WHERE\n                gdr.to_currency = 'USD'\n            AND gdr.from_currency = sob.currency_code\n            AND sob.set_of_books_id = ood.set_of_books_id\n            AND ood.organization_code = mp.organization_code\n            AND gdr.conversion_date = trunc(sysdate)\n            AND user_conversion_type = 'Corporate'\n    ), 1) usd_rate,\n    msi.planner_code,\n    msi.preprocessing_lead_time,\n    msi.full_lead_time                                                     processing_lead_time,\n    msi.postprocessing_lead_time,\n    msi.lead_time_lot_size,\n    msi.fixed_lead_time,\n    msi.variable_lead_time,\n    msi.attribute14                                                        apop,\n    msi.list_price_per_unit,\n    msi.creation_date                                                      item_creation_date,\n    msi.costing_enabled_flag,\n    msi.inventory_asset_flag,\n    decode(msi.planning_time_fence_code, 1, 'Cumulative Total Lead Time', 2, 'Cumulative MFG Lead Time',\n           3, 'Total Lead Time', 4, 'User Defined', msi.planning_time_fence_code) planning_time_fence,\n    msi.planning_time_fence_days,\n    decode(msi.demand_time_fence_code, 1, 'Cumulative Total Lead Time', 2, 'Cumulative MFG Lead Time',\n           3, 'Total Lead Time', 4, 'User Defined', msi.demand_time_fence_code) demand_time_fence,\n    msi.demand_time_fence_days,\n    decode(msi.release_time_fence_code, 6, 'Kanban Item (Do Not Release)', 7, 'Do Not Release (Auto or Manual)',\n           3, 'Total Lead Time', 2, 'Cumulative Mfg Lead Time', 1,\n           'Cumulative Total Lead Time', 4, 'User Defined', 5, 'Do Not Auto Release',\n           msi.release_time_fence_code) release_time_fence,\n    msi.release_time_fence_days,\n    msi.acceptable_early_days,\n    msi.fixed_days_supply,\n    msi.minimum_order_quantity,\n    msi.maximum_order_quantity,\n    msi.min_minmax_quantity,\n    msi.max_minmax_quantity,\n    msi.fixed_lot_multiplier,\n    msi.fixed_order_quantity,\n    decode(msi.source_type, 1, 'Inventory', 2, 'Supplier',\n           3, 'Subinventory') source_type,\n    (\n        SELECT\n            organization_code\n        FROM\n            inv.mtl_parameters mps\n        WHERE\n            msi.source_organization_id = mps.organization_id\n    ) source_org,\n    nvl(decode(msi.critical_component_flag, 1, 'Yes', 2, 'No',\n               msi.critical_component_flag), 'No') critical_component_flag,\n    decode(msi.inventory_planning_code, 1, 'Reorder Point', 2, 'Min Max',\n           6, 'Not Planned', 7, 'Vendor Managed', 'Not Planned') inventory_planning_code,\n    decode(msi.wip_supply_type, 1, 'Push', 2, 'Assembly Pull',\n           3, 'Operation Pull', 4, 'Bulk', 5,\n           'Supplier', 'Phantom') wip_supply_type,\n    CASE\n        WHEN msi.cycle_count_enabled_flag = 'N' THEN\n            'Not Applicable'\n        ELSE\n            nvl((\n                SELECT\n                    abc.abc_class_name\n                FROM\n                    apps.mrp_parameters_v         mrpp, apps.mtl_abc_assignments_v    abc\n                WHERE\n                        mrpp.organization_id = mp.organization_id\n                    AND mrpp.default_abc_assignment_group = abc.assignment_group_id\n                    AND abc.organization_id = mrpp.organization_id\n                    AND abc.inventory_item_id = msi.inventory_item_id\n            ), 'Blank')\n    END current_item_abc_class,\n    msi.wip_supply_subinventory,\n    (\n        SELECT\n            concatenated_segments\n        FROM\n            apps.mtl_item_locations_kfv mloc\n        WHERE\n                mloc.inventory_location_id = msi.wip_supply_locator_id\n            AND mloc.organization_id = mp.organization_id\n            AND msi.wip_supply_subinventory = mloc.subinventory_code\n    ) wip_supply_locator,\n    (\n        SELECT\n            segment1\n        FROM\n            apps.mtl_item_categories_v mic\n        WHERE\n                mic.inventory_item_id = msi.inventory_item_id\n            AND mic.organization_id = msi.organization_id\n            AND mic.organization_id = mp.organization_id\n            AND mic.category_set_name = 'Supply Chain Status'\n    ) supply_chain_status,\n    (\n        SELECT\n            category_concat_segs\n        FROM\n            apps.mtl_item_categories_v mic\n        WHERE\n                mic.inventory_item_id = msi.inventory_item_id\n            AND mic.organization_id = msi.organization_id\n            AND mic.organization_id = mp.organization_id\n            AND mic.category_set_name = 'ORG Product'\n    ) org_product,\n    (\n        SELECT\n            category_concat_segs\n        FROM\n            apps.mtl_item_categories_v mic\n        WHERE\n                mic.inventory_item_id = msi.inventory_item_id\n            AND mic.organization_id = msi.organization_id\n            AND mic.organization_id = mp.organization_id\n            AND mic.category_set_name = 'Product'\n    ) mas_product,\n    nvl((\n        SELECT\n            category_concat_segs\n        FROM\n            apps.mtl_item_categories_v mic\n        WHERE\n                mic.inventory_item_id = msi.inventory_item_id\n            AND mic.organization_id = msi.organization_id\n            AND mic.category_set_name = 'ORG Product'\n    ),(\n        SELECT\n            category_concat_segs\n        FROM\n            apps.mtl_item_categories_v mic\n        WHERE\n                mic.inventory_item_id = msi.inventory_item_id\n            AND mic.organization_id = msi.organization_id\n            AND mic.organization_id = mp.organization_id\n            AND mic.category_set_name = 'Product'\n    )) product_key,\n    (\n        SELECT\n            segment1\n        FROM\n            apps.mtl_item_categories_v mic\n        WHERE\n                mic.inventory_item_id = msi.inventory_item_id\n            AND mic.organization_id = msi.organization_id\n            AND mic.organization_id = mp.organization_id\n            AND mic.category_set_name = 'Country of Origin'\n    ) country_of_origin,\n    (\n        SELECT\n            category_concat_segs\n        FROM\n            apps.mtl_item_categories_v mic\n        WHERE\n                mic.inventory_item_id = msi.inventory_item_id\n            AND mic.organization_id = msi.organization_id\n            AND mic.organization_id = mp.organization_id\n            AND mic.category_set_name = 'Sourcing Commodity'\n    ) sourcing_commodity,\n    (\n        SELECT\n            category_concat_segs\n        FROM\n            apps.mtl_item_categories_v mic\n        WHERE\n                mic.inventory_item_id = msi.inventory_item_id\n            AND mic.organization_id = msi.organization_id\n            AND mic.organization_id = mp.organization_id\n            AND mic.category_set_name = 'Product Family'\n    ) product_family,\n    (\n        SELECT\n            segment1\n        FROM\n            apps.mtl_item_categories_v mic\n        WHERE\n                mic.inventory_item_id = msi.inventory_item_id\n            AND mic.organization_id = msi.organization_id\n            AND mic.organization_id = mp.organization_id\n            AND mic.category_set_name = 'Commodity'\n    ) commodity,\n    (\n        SELECT\n            segment1\n        FROM\n            apps.mtl_item_categories_v mic\n        WHERE\n                mic.inventory_item_id = msi.inventory_item_id\n            AND mic.organization_id = msi.organization_id\n            AND mic.organization_id = mp.organization_id\n            AND mic.category_set_name = 'Supplier Full Lead Time'\n    ) supplier_full_lead_time,\n    (\n        SELECT\n            segment1\n        FROM\n            apps.mtl_item_categories_v mic\n        WHERE\n                mic.inventory_item_id = msi.inventory_item_id\n            AND mic.organization_id = msi.organization_id\n            AND mic.organization_id = mp.organization_id\n            AND mic.category_set_name = 'Sales Availability'\n    ) sales_availability,\n    (\n        SELECT\n            segment1\n        FROM\n            apps.mtl_item_categories_v mic\n        WHERE\n                mic.inventory_item_id = msi.inventory_item_id\n            AND mic.organization_id = msi.organization_id\n            AND mic.organization_id = mp.organization_id\n            AND mic.category_set_name = 'Primary Org'\n    ) primary_org,\n    (\n        SELECT\n            segment1\n        FROM\n            apps.mtl_item_categories_v mic\n        WHERE\n                mic.inventory_item_id = msi.inventory_item_id\n            AND mic.organization_id = msi.organization_id\n            AND mic.organization_id = mp.organization_id\n            AND mic.category_set_name = 'Shipment Priority'\n    ) shipment_priority,\n    (\n        SELECT\n            segment1\n        FROM\n            apps.mtl_item_categories_v mic\n        WHERE\n                mic.inventory_item_id = msi.inventory_item_id\n            AND mic.organization_id = msi.organization_id\n            AND mic.organization_id = mp.organization_id\n            AND mic.category_set_name = 'Replenishment Method'\n    ) replenishment_method,\n    (\n        SELECT\n            category_concat_segs\n        FROM\n            apps.mtl_item_categories_v mic\n        WHERE\n                mic.inventory_item_id = msi.inventory_item_id\n            AND mic.organization_id = msi.organization_id\n            AND mic.organization_id = mp.organization_id\n            AND mic.category_set_name = 'Sourcing Rule'\n    ) sourcing_rule,\n    (\n        SELECT\n            category_concat_segs\n        FROM\n            apps.mtl_item_categories_v mic\n        WHERE\n                mic.inventory_item_id = msi.inventory_item_id\n            AND mic.organization_id = msi.organization_id\n            AND mic.organization_id = mp.organization_id\n            AND mic.category_set_name = 'Cost Source'\n    ) cost_category,\n    nvl(itd.last_op_po_price, itd.last_po_price)                           last_po_unit_price,\n    nvl(itd.last_op_po_price, itd.last_po_price) * (\n        SELECT\n            rate_to_usd\n        FROM\n            xxdims.xx_budget_rate br\n        WHERE\n            br.currency_code = nvl(itd.last_op_po_currency_code, itd.last_po_currency_code)\n    ) last_po_unit_price_usd_budget,\n    nvl(itd.last_op_po_currency_code, itd.last_po_currency_code)           last_po_currency,\n    itd.apop_classification,\n    itd.baseline_unit_price,\n    nvl(itd.last_op_po_vendor_name, itd.last_po_vendor_name)               last_po_vendor_name,\n    (\n        SELECT\n            assembly_category\n        FROM\n            xxcoh.xxcoh_category_changes\n        WHERE\n            component_item_no = msi.segment1\n            and rownum = 1\n    ) assembly_product_category,\n    itd.po_project,\n    round(msi.cum_manufacturing_lead_time, 4)                              cum_mfg_lt,\n    round(msi.cumulative_total_lead_time, 4)                               cum_total_lt,\n    (select mp.organization_code from apps.mtl_parameters mp\n    where mp.organization_id = msi.default_shipping_org) default_shipping_org,\n    decode(msi.COMMS_NL_TRACKABLE_FLAG,'Y','Yes','No') Track_Install_Base,\n    decode(msi.ATP_FLAG,'Y','Yes','No') ATP_Check,\n    decode(msi.ATP_COMPONENTS_FLAG,'Y','Yes','No') ATP_Components\nFROM\n    inv.mtl_system_items_b      msi,\n    inv.mtl_parameters          mp,\n    xxdims.xx_porec_item_dim    itd\nWHERE\n        msi.organization_id = mp.organization_id\n    AND msi.inventory_item_id = itd.inventory_item_id (+)\n    AND msi.organization_id = itd.inv_org_id (+)\n    AND mp.organization_code = '\"&ORG&\"'\n  \", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"EXTRACT_DATE\", \"Extract Date\"}, {\"ORGANIZATION_CODE\", \"Organization_Code\"}, {\"ITEM_NUMBER\", \"Item Number\"}, {\"ITEM_REVISION\", \"Item Revision\"}, {\"DESCRIPTION\", \"Item Description\"}, {\"PRIMARY_UNIT_OF_MEASURE\", \"Item Primary Unit of Measure\"}, {\"ITEM_STATUS\", \"Item Status\"}, {\"ITEM_TYPE\", \"Item Type\"}, {\"INVENTORY_ITEM_FLAG\", \"Inventory Item Flag\"}, {\"LOT_CONTROL_CODE\", \"Lot Control Code\"}, {\"SERIAL_CONTROL_CODE\", \"Serial Control Code\"}, {\"RECEIPT_ROUTING\", \"Receipt Routing\"}, {\"DEFAULT_BUYER\", \"Default Buyer\"}, {\"PLANNER_CODE\", \"Planner Code\"}, {\"PREPROCESSING_LEAD_TIME\", \"Preprocessing Lead Time\"}, {\"PROCESSING_LEAD_TIME\", \"Processing Lead Time\"}, {\"LEAD_TIME_LOT_SIZE\", \"Lead Time Lot Size\"}, {\"FIXED_LEAD_TIME\", \"Fixed Lead Time\"}, {\"VARIABLE_LEAD_TIME\", \"Variable Lead Time\"}, {\"LIST_PRICE_PER_UNIT\", \"List Price Per Unit\"}, {\"COSTING_ENABLED_FLAG\", \"Costing Enabled Flag\"}, {\"INVENTORY_ASSET_FLAG\", \"Inventory Asset Flag\"}, {\"POSTPROCESSING_LEAD_TIME\", \"Post Processing Lead Time\"}, {\"PLANNING_TIME_FENCE\", \"Planning Time Fence\"}, {\"PLANNING_TIME_FENCE_DAYS\", \"Planning Time Fence Days\"}, {\"DEMAND_TIME_FENCE\", \"Demand Time Fence\"}, {\"DEMAND_TIME_FENCE_DAYS\", \"Demand Time Fence Days\"}, {\"RELEASE_TIME_FENCE\", \"Release Time Fence\"}, {\"RELEASE_TIME_FENCE_DAYS\", \"Release Time Fence Days\"}, {\"ACCEPTABLE_EARLY_DAYS\", \"Acceptable Early Days\"}, {\"FIXED_DAYS_SUPPLY\", \"Fixed Days Supply\"}, {\"MINIMUM_ORDER_QUANTITY\", \"Minimum Order Quantity\"}, {\"MAXIMUM_ORDER_QUANTITY\", \"Maximum Order Quantity\"}, {\"MIN_MINMAX_QUANTITY\", \"Min Minmax Quantity\"}, {\"MAX_MINMAX_QUANTITY\", \"Max Minmax Quantity\"}, {\"FIXED_LOT_MULTIPLIER\", \"Fixed Lot Multiplier\"}, {\"FIXED_ORDER_QUANTITY\", \"Fixed Order Quantity\"}, {\"CRITICAL_COMPONENT_FLAG\", \"Critical Component Flag\"}, {\"INVENTORY_PLANNING_CODE\", \"Inventory Planning Code\"}, {\"WIP_SUPPLY_TYPE\", \"WIP Supply Type\"}, {\"CURRENT_ITEM_ABC_CLASS\", \"Current Item ABC Class\"}, {\"WIP_SUPPLY_SUBINVENTORY\", \"WIP Supply Subinventory\"}, {\"WIP_SUPPLY_LOCATOR\", \"WIP Supply Locator\"}, {\"SUPPLY_CHAIN_STATUS\", \"Supply Chain Status\"}, {\"ORG_PRODUCT\", \"Org Product\"}, {\"MAS_PRODUCT\", \"MAS Product\"}, {\"PRODUCT_KEY\", \"Product Key\"}, {\"COUNTRY_OF_ORIGIN\", \"Country Of Origin\"}, {\"SOURCING_COMMODITY\", \"Sourcing Commodity\"}, {\"COMMODITY\", \"Commodity\"}, {\"SUPPLIER_FULL_LEAD_TIME\", \"Supplier Full Lead Time\"}, {\"SALES_AVAILABILITY\", \"Sales Availability\"}, {\"PRIMARY_ORG\", \"Primary Org\"}, {\"SHIPMENT_PRIORITY\", \"Shipment Priority\"}, {\"SOURCING_RULE\", \"Sourcing Rule\"}, {\"PRODUCT_FAMILY\", \"Product Family\"}, {\"ITEM_CREATION_DATE\", \"Item Creation Date\"}, {\"REPLENISHMENT_METHOD\", \"Replenishment Method\"}, {\"PLANNING_MAKE_BUY_CODE\", \"Item Make or Buy\"}, {\"SOURCE_TYPE\", \"Item Default Source Type\"}, {\"SOURCE_ORG\", \"Item Source Organization Code\"}, {\"MRP_PLANNING_CODE\", \"MRP Planning Code\"}, {\"COST_CATEGORY\", \"Cost Category\"}, {\"LAST_PO_UNIT_PRICE\", \"Last PO Unit Price\"}, {\"LAST_PO_CURRENCY\", \"Last PO Currency\"}, {\"APOP_CLASSIFICATION\", \"APOP Classification\"}, {\"BASELINE_UNIT_PRICE\", \"Baseline Unit Price USD\"}, {\"LAST_PO_VENDOR_NAME\", \"Last PO Supplier Name\"}, {\"LAST_PO_UNIT_PRICE_USD_BUDGET\", \"Last PO Unit Price USD (Budget)\"}, {\"ASSEMBLY_PRODUCT_CATEGORY\", \"Assembly Product Category\"}, {\"PO_PROJECT\", \"PO Project\"}, {\"CUM_MFG_LT\", \"Cumulative Manufacturing Lead Time\"}, {\"CUM_TOTAL_LT\", \"Cumulative Total Lead Time\"}, {\"USD_RATE\", \"USD Rate\"}, {\"DEFAULT_SHIPPING_ORG\", \"Default Shipping Org\"}, {\"TRACK_INSTALL_BASE\", \"Install Base Track\"}, {\"ATP_CHECK\", \"ATP Check\"}, {\"ATP_COMPONENTS\", \"ATP Components Check\"}, {\"LOCAL_EXTRACT_DATE\", \"Local Extract Date\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Item_Cost = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, Query=\"\n  select\nsysdate Extract_Date\n,from_tz(cast (sysdate as timestamp),'PST') at time zone '\"&Local&\"' local_extract_date\n,mp.organization_code\n,msi.inventory_item_id\n,msi.segment1 ITEM_NUMBER\n,cic.item_cost\n,cic.material_cost\n,cic.material_overhead_cost moh_cost\n,cic.resource_cost\n,cic.outside_processing_cost osp_cost\n,decode(cic.based_on_rollup_flag,1,'Yes','No') rollup_flag\n,cic.rollup_id\n,CCT.COST_TYPE\n,CIC.CREATION_DATE\n,CIC.LAST_UPDATE_DATE\nfrom\nINV.MTL_SYSTEM_ITEMS_B MSI\n,INV.MTL_PARAMETERS MP\n,bom.cst_item_costs cic\n,APPS.CST_COST_TYPES_V CCT\nwhere msi.organization_id = mp.organization_id\nand mp.organization_code = '\"&ORG&\"'\nand cic.inventory_item_id = msi.inventory_item_id\nand cic.organization_id = msi.organization_id\nand cic.cost_type_id = 1\nAND CCT.COST_TYPE_ID = CIC.COST_TYPE_ID\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"EXTRACT_DATE\", \"Extract Date\"}, {\"ORGANIZATION_CODE\", \"Organization Code\"}, {\"ITEM_NUMBER\", \"Item Number\"}, {\"ITEM_COST\", \"Item Cost\"}, {\"MATERIAL_COST\", \"Material Cost\"}, {\"MOH_COST\", \"Material Overhead Cost\"}, {\"RESOURCE_COST\", \"Resource Cost\"}, {\"OSP_COST\", \"Outside Processing Cost\"}, {\"ROLLUP_FLAG\", \"Based On Rollup Flag\"}, {\"COST_TYPE\", \"Cost Type\"}, {\"CREATION_DATE\", \"Item Cost Creation Date\"}, {\"LAST_UPDATE_DATE\", \"Item Cost Last Update Date\"}, {\"LOCAL_EXTRACT_DATE\", \"Local Extract Date\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Item_Category = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, Query=\"\n   select sysdate extract_date,\n    from_tz(cast (sysdate as timestamp),'PST') at time zone '\"&Local&\"' local_extract_date,\n    mic.category_set_name, mic.segment1,mic.segment2,mic.segment3,mic.segment4, mic.inventory_item_id,\n case when mic.segment4 is not null then mic.segment1||'.'||mic.segment2||'.'||mic.segment3||'.'||mic.segment4\n  when mic.segment3 is not null then mic.segment1||'.'||mic.segment2||'.'||mic.segment3\n  when mic.segment2 is not null then mic.segment1||'.'||mic.segment2\n  else mic.segment1 end category_code\n FROM   apps.mtl_item_Categories_v mic, apps.mtl_parameters mp\n where mp.organization_id = mic.organization_id\n and mp.organization_code = '\"&ORG&\"'\n \", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"EXTRACT_DATE\", \"Extract Date\"}, {\"LOCAL_EXTRACT_DATE\", \"Local Extract Date\"}, {\"CATEGORY_SET_NAME\", \"Category Set Name\"}, {\"CATEGORY_CODE\", \"Category\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Local = let\r\n  Local = \"ASIA/Singapore\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type text]\r\nin\r\n  Local;\r\nshared Item_Subinventory = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, \n  Query=\"\n  SELECT\n    sysdate                                                                     extract_date,\n    from_tz(CAST(sysdate AS TIMESTAMP), 'PST') AT TIME ZONE '\"&Local&\"'         local_extract_date,\n    mp.organization_code,\n    msi.segment1,\n    msi.description,\n    msi.planner_code,\n    msi.list_price_per_unit,\n    msi.buyer_id,\n    isub.secondary_inventory subinventory,\n    isub.source_type,\n    isub.source_organization,\n    isub.processing_lead_time,\n    isub.preprocessing_lead_time,\n    isub.postprocessing_lead_time,\n    decode(isub.inventory_planning_code,2,'Yes','No') MINMAX_PLANNING,\n    isub.min_minmax_quantity,\n    isub.max_minmax_quantity,\n    isub.fixed_lot_multiple,\n    isub.minimum_order_quantity,\n    isub.maximum_order_quantity\nFROM\n    apps.mtl_item_sub_inventories_all_v    isub,\n    apps.mtl_parameters                    mp,\n    apps.mtl_system_items_b                msi\nWHERE\n        mp.organization_id = isub.organization_id\n    AND msi.organization_id = mp.organization_id\n    AND msi.inventory_item_id = isub.inventory_item_id\n    AND mp.organization_code = '\"&ORG&\"'\n  \", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"EXTRACT_DATE\", \"Extract Date\"}, {\"LOCAL_EXTRACT_DATE\", \"Local Extract Date\"}, {\"ORGANIZATION_CODE\", \"Organization Code\"}, {\"SEGMENT1\", \"Item Number\"}, {\"DESCRIPTION\", \"Item Description\"}, {\"PLANNER_CODE\", \"Planner Code\"}, {\"SUBINVENTORY\", \"Subinventory\"}, {\"LIST_PRICE_PER_UNIT\", \"List Price Per Unit\"}, {\"SOURCE_TYPE\", \"Source Type\"}, {\"SOURCE_ORGANIZATION\", \"Source Org Code\"}, {\"PROCESSING_LEAD_TIME\", \"Item Subinventory Processing Lead Time\"}, {\"MINMAX_PLANNING\", \"Item Subinventory Min Max Planning\"}, {\"MIN_MINMAX_QUANTITY\", \"Min Minmax Quantity\"}, {\"MAX_MINMAX_QUANTITY\", \"Max Minmax Quantity\"}, {\"FIXED_LOT_MULTIPLE\", \"Item Subinventory Fixed Lot Multiple\"}, {\"MINIMUM_ORDER_QUANTITY\", \"Item Subinventory Minimum Order Quantity\"}, {\"MAXIMUM_ORDER_QUANTITY\", \"Item Subinventory Maximum Order Quantity\"}, {\"PREPROCESSING_LEAD_TIME\", \"Item Subinventory Preprocessing Lead Time\"}, {\"POSTPROCESSING_LEAD_TIME\", \"Item Subinventory Post Processing Lead Time\"}})\r\nin\r\n  #\"Renamed columns\";\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"Subinventory","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Subinventory.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Local Extract Date","dataType":"dateTime"},{"name":"Organization Code","dataType":"string"},{"name":"Subinventory Name","dataType":"string"},{"name":"Subinventory Description","dataType":"string"},{"name":"Disable Date","dataType":"dateTime"},{"name":"Enabled Flag","dataType":"string"},{"name":"Quantity Tracked Flag","dataType":"string"},{"name":"Asset Flag","dataType":"string"},{"name":"Depreciable Flag","dataType":"string"},{"name":"ATP Flag","dataType":"string"},{"name":"Reserveable Flag","dataType":"string"},{"name":"Nettable Flag","dataType":"string"},{"name":"Subinventory Locator Type","dataType":"string"},{"name":"Class","dataType":"string"},{"name":"Picking Order","dataType":"double"},{"name":"Material Account","dataType":"string"},{"name":"Expense Account","dataType":"string"},{"name":"OSP Account","dataType":"string"},{"name":"Overhead Account","dataType":"string"},{"name":"Resource Account","dataType":"string"},{"name":"Material Overhead Account","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-12T23:00:13.0239197+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/00f3c10a-aa54-49fb-b402-dae3138299cf/Subinventory.csv?snapshot=2022-06-12T23%3A00%3A12.9878403Z"}]},{"$type":"LocalEntity","name":"Item_Attribute","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Item_Attribute.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Local Extract Date","dataType":"dateTime"},{"name":"Organization_Code","dataType":"string"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"Item Number","dataType":"string"},{"name":"MRP Planning Code","dataType":"string"},{"name":"Item Revision","dataType":"string"},{"name":"Item Description","dataType":"string"},{"name":"Item Primary Unit of Measure","dataType":"string"},{"name":"Item Status","dataType":"string"},{"name":"Item Type","dataType":"string"},{"name":"Inventory Item Flag","dataType":"string"},{"name":"Lot Control Code","dataType":"string"},{"name":"Serial Control Code","dataType":"string"},{"name":"Receipt Routing","dataType":"string"},{"name":"Default Buyer","dataType":"string"},{"name":"BUYER_ID","dataType":"int64"},{"name":"Item Make or Buy","dataType":"string"},{"name":"USD Rate","dataType":"double"},{"name":"Planner Code","dataType":"string"},{"name":"Preprocessing Lead Time","dataType":"double"},{"name":"Processing Lead Time","dataType":"double"},{"name":"Post Processing Lead Time","dataType":"double"},{"name":"Lead Time Lot Size","dataType":"double"},{"name":"Fixed Lead Time","dataType":"double"},{"name":"Variable Lead Time","dataType":"double"},{"name":"APOP","dataType":"string"},{"name":"List Price Per Unit","dataType":"double"},{"name":"Item Creation Date","dataType":"dateTime"},{"name":"Costing Enabled Flag","dataType":"string"},{"name":"Inventory Asset Flag","dataType":"string"},{"name":"Planning Time Fence","dataType":"string"},{"name":"Planning Time Fence Days","dataType":"double"},{"name":"Demand Time Fence","dataType":"string"},{"name":"Demand Time Fence Days","dataType":"double"},{"name":"Release Time Fence","dataType":"string"},{"name":"Release Time Fence Days","dataType":"double"},{"name":"Acceptable Early Days","dataType":"double"},{"name":"Fixed Days Supply","dataType":"double"},{"name":"Minimum Order Quantity","dataType":"double"},{"name":"Maximum Order Quantity","dataType":"double"},{"name":"Min Minmax Quantity","dataType":"double"},{"name":"Max Minmax Quantity","dataType":"double"},{"name":"Fixed Lot Multiplier","dataType":"double"},{"name":"Fixed Order Quantity","dataType":"double"},{"name":"Item Default Source Type","dataType":"string"},{"name":"Item Source Organization Code","dataType":"string"},{"name":"Critical Component Flag","dataType":"string"},{"name":"Inventory Planning Code","dataType":"string"},{"name":"WIP Supply Type","dataType":"string"},{"name":"Current Item ABC Class","dataType":"string"},{"name":"WIP Supply Subinventory","dataType":"string"},{"name":"WIP Supply Locator","dataType":"string"},{"name":"Supply Chain Status","dataType":"string"},{"name":"Org Product","dataType":"string"},{"name":"MAS Product","dataType":"string"},{"name":"Product Key","dataType":"string"},{"name":"Country Of Origin","dataType":"string"},{"name":"Sourcing Commodity","dataType":"string"},{"name":"Product Family","dataType":"string"},{"name":"Commodity","dataType":"string"},{"name":"Supplier Full Lead Time","dataType":"string"},{"name":"Sales Availability","dataType":"string"},{"name":"Primary Org","dataType":"string"},{"name":"Shipment Priority","dataType":"string"},{"name":"Replenishment Method","dataType":"string"},{"name":"Sourcing Rule","dataType":"string"},{"name":"Cost Category","dataType":"string"},{"name":"Last PO Unit Price","dataType":"double"},{"name":"Last PO Unit Price USD (Budget)","dataType":"double"},{"name":"Last PO Currency","dataType":"string"},{"name":"APOP Classification","dataType":"string"},{"name":"Baseline Unit Price USD","dataType":"double"},{"name":"Last PO Supplier Name","dataType":"string"},{"name":"Assembly Product Category","dataType":"string"},{"name":"PO Project","dataType":"double"},{"name":"Cumulative Manufacturing Lead Time","dataType":"double"},{"name":"Cumulative Total Lead Time","dataType":"double"},{"name":"Default Shipping Org","dataType":"string"},{"name":"Install Base Track","dataType":"string"},{"name":"ATP Check","dataType":"string"},{"name":"ATP Components Check","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-12T23:01:15.5112107+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/00f3c10a-aa54-49fb-b402-dae3138299cf/Item_Attribute.csv?snapshot=2022-06-12T23%3A01%3A15.4698409Z"}]},{"$type":"LocalEntity","name":"Item_Cost","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Item_Cost.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Local Extract Date","dataType":"dateTime"},{"name":"Organization Code","dataType":"string"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"Item Number","dataType":"string"},{"name":"Item Cost","dataType":"double"},{"name":"Material Cost","dataType":"double"},{"name":"Material Overhead Cost","dataType":"double"},{"name":"Resource Cost","dataType":"double"},{"name":"Outside Processing Cost","dataType":"double"},{"name":"Based On Rollup Flag","dataType":"string"},{"name":"ROLLUP_ID","dataType":"int64"},{"name":"Cost Type","dataType":"string"},{"name":"Item Cost Creation Date","dataType":"dateTime"},{"name":"Item Cost Last Update Date","dataType":"dateTime"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-12T23:00:57.856785+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/00f3c10a-aa54-49fb-b402-dae3138299cf/Item_Cost.csv?snapshot=2022-06-12T23%3A00%3A57.8167308Z"}]},{"$type":"LocalEntity","name":"Item_Category","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Item_Category.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Local Extract Date","dataType":"dateTime"},{"name":"Category Set Name","dataType":"string"},{"name":"SEGMENT1","dataType":"string"},{"name":"SEGMENT2","dataType":"string"},{"name":"SEGMENT3","dataType":"string"},{"name":"SEGMENT4","dataType":"string"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"Category","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-12T23:00:19.0134253+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/00f3c10a-aa54-49fb-b402-dae3138299cf/Item_Category.csv?snapshot=2022-06-12T23%3A00%3A18.9934776Z"}]},{"$type":"LocalEntity","name":"Item_Subinventory","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Item_Subinventory.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Local Extract Date","dataType":"dateTime"},{"name":"Organization Code","dataType":"string"},{"name":"Item Number","dataType":"string"},{"name":"Item Description","dataType":"string"},{"name":"Planner Code","dataType":"string"},{"name":"List Price Per Unit","dataType":"double"},{"name":"BUYER_ID","dataType":"int64"},{"name":"Subinventory","dataType":"string"},{"name":"Source Type","dataType":"double"},{"name":"Source Org Code","dataType":"string"},{"name":"Item Subinventory Processing Lead Time","dataType":"double"},{"name":"Item Subinventory Preprocessing Lead Time","dataType":"double"},{"name":"Item Subinventory Post Processing Lead Time","dataType":"double"},{"name":"Item Subinventory Min Max Planning","dataType":"string"},{"name":"Min Minmax Quantity","dataType":"double"},{"name":"Max Minmax Quantity","dataType":"double"},{"name":"Item Subinventory Fixed Lot Multiple","dataType":"double"},{"name":"Item Subinventory Minimum Order Quantity","dataType":"double"},{"name":"Item Subinventory Maximum Order Quantity","dataType":"double"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-12T23:00:50.0497256+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/00f3c10a-aa54-49fb-b402-dae3138299cf/Item_Subinventory.csv?snapshot=2022-06-12T23%3A00%3A50.0001109Z"}]}]}