{"name":"COHREP_SITE_PURCHASING_TRX1","description":"","version":"1.0","culture":"en-US","modifiedTime":"2021-10-11T18:25:37.1750717+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":true,"queriesMetadata":{"ORG":{"queryId":"39b1f7da-0847-46a7-a148-01fb8a10ac9d","queryName":"ORG"},"ASL_Document":{"queryId":"6c5a600c-a782-49ed-8da3-3817bf16814e","queryName":"ASL_Document","queryGroupId":"root","loadEnabled":true},"ASL_Attribute":{"queryId":"8d6699a0-5cc6-4e0f-8f30-75f21d002947","queryName":"ASL_Attribute","queryGroupId":"root","loadEnabled":true},"Purchase_Order":{"queryId":"28007281-9a95-45a3-af6f-c8359687ebff","queryName":"Purchase_Order","queryGroupId":"root","loadEnabled":true},"Blanket_Agreement":{"queryId":"a6d1d751-2a47-49de-a898-ef75eacac86e","queryName":"Blanket_Agreement","queryGroupId":"root","loadEnabled":true},"Quote":{"queryId":"d8430c6b-c38f-448b-b13d-a7521198c515","queryName":"Quote","queryGroupId":"root","loadEnabled":true},"Purchase_Order_Distribution":{"queryId":"1a325901-6035-4dcf-81ae-098d50180130","queryName":"Purchase_Order_Distribution","queryGroupId":"root","loadEnabled":true},"Requisition":{"queryId":"aea30542-4271-486c-9482-fbd40eab4605","queryName":"Requisition","queryGroupId":"root","loadEnabled":true},"Local":{"queryId":"06a7cc7a-eaf5-40b2-b5df-63d8c86764ed","queryName":"Local"}},"document":"section Section1;\r\nshared ORG = let\r\n  ORG = \"PPG\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type text]\r\nin\r\n  ORG;\r\nshared ASL_Document = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, \n  Query=\"\n  SELECT\n    sysdate extract_date,\n    from_tz(cast (sysdate as timestamp),'PST') at time zone '\"&Local&\"' local_extract_date,\n    pad.asl_id,\n    msi.inventory_item_id,\n    msi.segment1    item_number,\n    pad.vendor_id,\n    pad.vendor_site_id,\n    pad.document_header_id,\n    pad.document_line_id,\n    pad.sequence_num,\n    pad.document_type_dsp,\n    pad.document_num,\n    pad.line_num,\n    pad.document_status_dsp,\n    pad.using_organization_id,\n    pad.using_organization_code,\n    pad.asl_id\n    || '_'\n    || pad.using_organization_id asl_key,\n    CASE\n        WHEN pad.using_organization_id < 0\n             AND (\n            SELECT\n               count(1)\n            FROM\n                apps.po_asl_documents_v pad2\n            WHERE\n                    pad2.asl_id = pad.asl_id\n                AND pad2.using_organization_id > 0\n        ) > 0 THEN\n            'No'\n        ELSE\n            'Yes'\n    END ASL_USE_FLAG,\n    CASE\n        WHEN pad.using_organization_id > 0 THEN\n            'Local ASL'\n        ELSE\n            'Global ASL'\n    END asl_type\nFROM\n    inv.mtl_system_items_b               msi,\n    apps.org_organization_definitions    ood,\n    apps.po_asl_documents_v              pad,\n    apps.po_vendor_sites_all             pvs\nWHERE\n        msi.organization_id = ood.organization_id\n    AND pad.item_id = msi.inventory_item_id\n    AND pvs.vendor_site_id = pad.vendor_site_id\n    AND pad.vendor_id = pvs.vendor_id\n    AND pvs.org_id = ood.operating_unit\n    AND pad.org_id = ood.operating_unit\n    AND ood.organization_code = nvl(pad.using_organization_code, ood.organization_code)\n  AND OOD.ORGANIZATION_CODE = '\"&ORG&\"' \n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"EXTRACT_DATE\", \"Extract Date\"}, {\"ITEM_NUMBER\", \"Item Number\"}, {\"SEQUENCE_NUM\", \"Sequence\"}, {\"DOCUMENT_TYPE_DSP\", \"Document Type\"}, {\"DOCUMENT_NUM\", \"Document Number\"}, {\"LINE_NUM\", \"Document Line Number\"}, {\"DOCUMENT_STATUS_DSP\", \"Document Status\"}, {\"USING_ORGANIZATION_CODE\", \"Using Organization Code\"}, {\"ASL_USE_FLAG\", \"ASL Used Flag\"}, {\"ASL_TYPE\", \"ASL Type\"}, {\"LOCAL_EXTRACT_DATE\", \"Local Extract Date\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared ASL_Attribute = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, \n  Query=\"\n   SELECT\n    sysdate extract_date,\n    from_tz(cast (sysdate as timestamp),'PST') at time zone '\"&Local&\"' local_extract_date,\n    pasl.asl_id,\n    msi.inventory_item_id,\n    msi.segment1                                                                      item_number,\n    (\n        SELECT\n            status\n        FROM\n            apps.po_asl_statuses pas\n        WHERE\n            pas.status_id = pasl.asl_status_id\n    ) asl_status,\n    pasl.vendor_id,\n    pasl.vendor_site_id,\n    paa.release_generation_method_dsp,\n    paa.consigned_from_supplier_flag,\n    paa.min_order_qty,\n    paa.purchasing_uom,\n    paa.processing_lead_time,\n    paa.fixed_lot_multiple,\n    paa.fixed_order_quantity,\n    paa.using_organization_code,\n    paa.scheduler_name,\n    CASE\n        WHEN paa.using_organization_id < 0\n             AND (\n            SELECT\n              count (1)\n            FROM\n                apps.po_asl_attributes_v paa2\n            WHERE\n                    paa2.asl_id = paa.asl_id\n                AND paa2.using_organization_id > 0\n        ) > 0 THEN\n            'No'\n        ELSE\n            'Yes'\n    END asl_used_flag,\n    CASE\n        WHEN paa.using_organization_id > 0 THEN\n            'Local ASL'\n        ELSE\n            'Global ASL'\n    END    asl_type,\n    paa.asl_id\n    || '_'\n    || paa.using_organization_id                                    asl_key,\n    CASE\n        WHEN (\n            SELECT\n                sr.category_concat_segs\n            FROM\n                (\n                    SELECT\n                        mic.inventory_item_id,\n                        mic.category_concat_segs,\n                        msso.vendor_id,\n                        msso.vendor_site_id,\n                        decode(msso.source_type, 1, 'Transfer From', 2, 'Make At',\n                               3, 'Buy From') sr_source_type,\n                        msso.allocation_percent\n                    FROM\n                        apps.mtl_item_categories_v    mic,\n                        apps.mrp_sr_assignments_v     msra,\n                        mrp.mrp_sourcing_rules        msr,\n                        apps.mrp_sr_receipt_org_v     msro,\n                        apps.mrp_sr_source_org_v      msso,\n                        inv.mtl_parameters            mp\n                    WHERE\n                            1 = 1\n                        AND mic.category_id = msra.category_id\n                        AND mic.organization_id = msra.organization_id\n                        AND msra.sourcing_rule_id = msr.sourcing_rule_id\n                        AND msr.sourcing_rule_id = msro.sourcing_rule_id\n                        AND mp.organization_id = mic.organization_id\n                        AND mp.organization_code = '\"&ORG&\"' \n                        AND mic.category_set_name = 'Sourcing Rule'\n                        AND msro.sr_receipt_id = msso.sr_receipt_id\n                        AND sysdate < nvl(msro.disable_date, sysdate + 1)\n                        AND sysdate > nvl(msro.effective_date, sysdate - 1)\n                        AND msso.vendor_site_id IS NOT NULL\n                ) sr\n            WHERE\n                    sr.vendor_site_id = paa.vendor_site_id\n                AND paa.vendor_id = sr.vendor_id\n                AND sr.inventory_item_id = paa.item_id\n                AND sr.inventory_item_id = pasl.item_id\n        ) IS NOT NULL THEN\n            'Yes'\n        ELSE\n            'No'\n    END actively_sourced\nFROM\n    apps.po_approved_supplier_list       pasl,\n    apps.po_asl_attributes_v             paa,\n    inv.mtl_system_items_b               msi,\n    apps.org_organization_definitions    ood,\n    apps.po_vendor_sites_all             pvs\nWHERE\n        msi.organization_id = ood.organization_id\n    AND paa.asl_id = pasl.asl_id\n    AND paa.item_id = pasl.item_id\n    AND paa.item_id = msi.inventory_item_id\n    AND pvs.org_id = ood.operating_unit\n    AND pvs.vendor_site_id = paa.vendor_site_id\n    AND pasl.item_id = msi.inventory_item_id\n    AND OOD.ORGANIZATION_CODE = '\"&ORG&\"' \n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"EXTRACT_DATE\", \"Extract Date\"}, {\"ACTIVELY_SOURCED\", \"Actively Sourced Flag\"}, {\"RELEASE_GENERATION_METHOD_DSP\", \"Release Method\"}, {\"CONSIGNED_FROM_SUPPLIER_FLAG\", \"Consigned From Supplier\"}, {\"MIN_ORDER_QTY\", \"Minimum Order Quantity\"}, {\"PURCHASING_UOM\", \"Purchasing UOM\"}, {\"PROCESSING_LEAD_TIME\", \"Processing Lead Time\"}, {\"FIXED_LOT_MULTIPLE\", \"Fixed Lot Multiplier\"}, {\"FIXED_ORDER_QUANTITY\", \"Fixed Order Quantity\"}, {\"USING_ORGANIZATION_CODE\", \"Using Organization Code\"}, {\"ITEM_NUMBER\", \"Item Number\"}, {\"ASL_STATUS\", \"ASL Status\"}, {\"SCHEDULER_NAME\", \"Scheduler Name\"}, {\"ASL_TYPE\", \"ASL Type\"}, {\"ASL_USED_FLAG\", \"ASL Used Flag\"}, {\"LOCAL_EXTRACT_DATE\", \"Local Extract Date\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Purchase_Order = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, \n  Query=\"\n  SELECT\n    sysdate extract_date,\n    from_tz(cast (sysdate as timestamp),'PST') at time zone '\"&Local&\"' local_extract_date,\n    pra.po_release_id,\n    CASE\n        WHEN plla.approved_flag IN (\n            'Y',\n            'R'\n        ) THEN\n            CASE\n                WHEN (\n                    SELECT\n                        COUNT(1)\n                    FROM\n                        apps.po_action_history_v pah\n                    WHERE\n                            nvl(pra.po_release_id, pha.po_header_id) = pah.object_id\n                        AND pah.object_revision_num = 0\n                        AND pah.object_type_code IN (\n                            'PO',\n                            'RELEASE'\n                        )\n                        AND action_code = 'SUBMIT'\n                        AND nvl(pah.note, 'X') = 'AUTO RELEASE'\n                ) > 0 THEN\n                    'Automatic'\n                ELSE\n                    'Manual'\n            END\n    END po_approval_mode,\n    mp.organization_code,\n    pha.segment1                                                                                                 po_number,\n    nvl(pra.agent_id, pha.agent_id)                                                                              po_key_agent_id,\n    pha.agent_id                                                                                                 po_agent_id,\n    (\n        SELECT\n            agent_name\n        FROM\n            apps.po_agents_v poa\n        WHERE\n                poa.agent_id = pha.agent_id\n            AND ROWNUM = 1\n    ) po_buyer,\n    (\n        SELECT\n            agent_name\n        FROM\n            apps.po_agents_v poa\n        WHERE\n                poa.agent_id = nvl(pra.agent_id, pha.agent_id)\n            AND ROWNUM = 1\n    ) po_key_buyer,\n    pra.release_num,\n    nvl(pra.revision_num, pha.revision_num)                                                                      revision_num,\n    nvl(pra.creation_date, pha.creation_date)                                                                    creation_date,\n    CASE\n        WHEN nvl(pra.po_release_id, 0) > 0        THEN\n            (\n                SELECT\n                    approved_date\n                FROM\n                    apps.po_releases_archive_all praa\n                WHERE\n                        praa.po_release_id = pra.po_release_id\n                    AND praa.revision_num = 0\n            )\n        WHEN nvl(pra.po_release_id, 0) = 0        THEN\n            (\n                SELECT\n                    approved_date\n                FROM\n                    apps.po_headers_archive_all phaa\n                WHERE\n                        phaa.po_header_id = pha.po_header_id\n                    AND phaa.revision_num = 0\n            )\n    END po_key_original_approved_date,\n    nvl(pha.rate, 1)                                                                                             functional_rate,\n    CASE\n        WHEN pra.release_num > 0 THEN\n            pha.segment1\n            || '_'\n            || pra.release_num\n        ELSE\n            pha.segment1\n    END po_key,\n    pha.comments,\n    nvl(plla.approved_flag, 'N')                                                                                  approved_flag,\n    plla.approved_date,\n    CASE\n        WHEN pra.release_num > 0 THEN\n            pra.approved_date\n        ELSE\n            pha.approved_date\n    END po_key_approved_date,\n    pha.fob_lookup_code,\n    pha.type_lookup_code                                                                                         po_type,\n    (\n        SELECT\n            segment1\n        FROM\n            apps.mtl_categories mc\n        WHERE\n            mc.category_id = pla.category_id\n    ) purchasing_category,\n    plla.shipment_closed_date,\n    plla.closed_for_receiving_date,\n    plla.closed_for_invoice_date,\n    plla.closed_reason,\n    plla.closed_date,\n    plla.closed_code,\n    CASE\n        WHEN (\n            SELECT\n                COUNT(DISTINCT(pda.destination_subinventory))\n            FROM\n                po.po_distributions_all pda\n            WHERE\n                pda.line_location_id = plla.line_location_id\n        ) > 1 THEN\n            'Multiple'\n        ELSE\n            (\n                SELECT DISTINCT\n                    ( pda.destination_subinventory )\n                FROM\n                    po.po_distributions_all pda\n                WHERE\n                        pda.line_location_id = plla.line_location_id\n                    AND ROWNUM = 1\n            )\n    END destination_subinventory,\n    CASE\n        WHEN pra.po_release_id IS NOT NULL THEN\n            (\n                SELECT\n                    MAX(creation_date)\n                FROM\n                    apps.po_acceptances poa\n                WHERE\n                        poa.po_release_id = pra.po_release_id\n                    AND poa.accepted_flag = 'Y'\n            )\n        WHEN pra.po_release_id IS NULL THEN\n            (\n                SELECT\n                    MAX(creation_date)\n                FROM\n                    apps.po_acceptances poa\n                WHERE\n                        poa.po_header_id = pra.po_header_id\n                    AND poa.accepted_flag = 'Y'\n            )\n    END last_po_acceptance_date,\n    (\n        SELECT\n            plt.line_type\n        FROM\n            apps.po_line_types_v plt\n        WHERE\n            plt.line_type_id = pla.line_type_id\n    ) line_type,\n    nvl(pra.document_creation_method, pha.document_creation_method)                                              document_creation_method,\n    decode(nvl(pra.consigned_consumption_flag, pha.consigned_consumption_flag), 'Y', 'Yes', 'No')              consumption_advice_flag,\n    pha.rate_date,\n    pla.po_line_id,\n    pla.item_id,\n    pla.line_num,\n    (\n        SELECT\n            segment1\n        FROM\n            inv.mtl_system_items_b msi\n        WHERE\n                msi.organization_id = mp.organization_id\n            AND msi.inventory_item_id = pla.item_id\n    ) po_item_number,\n    pla.item_revision                                                                                            po_item_revision,\n    pla.item_description                                                                                         po_item_description,\n    pla.unit_meas_lookup_code                                                                                    po_unit_of_measure,\n    (\n        SELECT\n            planner_code\n        FROM\n            inv.mtl_system_items_b msi\n        WHERE\n                msi.organization_id = mp.organization_id\n            AND msi.inventory_item_id = pla.item_id\n    ) planner_code,\n    pha.currency_code,\n    pla.unit_price,\n    plla.line_location_id,\n    plla.shipment_num,\n    plla.need_by_date,\n    plla.promised_date,\n    plla.quantity,\n    plla.quantity_received,\n    plla.quantity_cancelled,\n    plla.quantity_billed,\n    plla.quantity_accepted,\n    (\n        SELECT\n            SUM(pda.quantity_delivered)\n        FROM\n            po.po_distributions_all pda\n        WHERE\n            pda.line_location_id = plla.line_location_id\n    ) quantity_delivered,\n    CASE\n        WHEN plla.po_release_id > 0 THEN\n            (\n                SELECT\n                    type_lookup_code\n                FROM\n                    po.po_headers_all pha\n                WHERE\n                        pha.po_header_id = plla.po_header_id\n                    AND ROWNUM = 1\n            )\n        ELSE\n            (\n                SELECT\n                    type_lookup_code\n                FROM\n                    po.po_headers_all pha\n                WHERE\n                        pha.po_header_id = pla.from_header_id\n                    AND ROWNUM = 1\n            )\n    END document_reference_type,\n    CASE\n        WHEN plla.po_release_id > 0 THEN\n            (\n                SELECT\n                    pha.segment1\n                FROM\n                    po.po_headers_all pha\n                WHERE\n                        pha.po_header_id = plla.po_header_id\n                    AND ROWNUM = 1\n            )\n        ELSE\n            (\n                SELECT\n                    pha.segment1\n                FROM\n                    po.po_headers_all pha\n                WHERE\n                        pha.po_header_id = pla.from_header_id\n                    AND ROWNUM = 1\n            )\n    END document_reference_number,\n    pha.vendor_id,\n    pha.vendor_site_id,\n    decode(plla.consigned_flag, 'Y', 'Yes', 'No')                                                                consigned_flag,\n    (\n        SELECT\n            meaning\n        FROM\n            apps.fnd_lookup_values    flv,\n            inv.mtl_system_items_b       msi\n        WHERE\n                flv.lookup_type = 'ITEM_TYPE'\n            AND flv.language = 'US'\n            AND flv.lookup_code = msi.item_type\n            AND msi.inventory_item_id = pla.item_id\n            AND msi.organization_id = mp.organization_id\n    ) item_type,\n    pla.attribute1                                                                                               ppv_apop_or_item_cost,\n    ( pla.attribute2 ) ppv_rate_percent,\n    nvl(pla.attribute3, 'N')                                                                                     ppv_approval_required,\n    pla.attribute7                                                                                               ppv_reason,\n    (\n        SELECT\n            pda.destination_type_code\n        FROM\n            po.po_distributions_all pda\n        WHERE\n                pda.line_location_id = plla.line_location_id\n            AND ROWNUM = 1\n    ) destination_type_code,\n    (\n        SELECT\n            MIN(pllaa.approved_date)\n        FROM\n            po.po_line_locations_archive_all pllaa\n        WHERE\n            pllaa.line_location_id = plla.line_location_id\n    ) first_approved_date,\n    (\n        SELECT\n            prha.approved_date\n        FROM\n            po.po_requisition_headers_all    prha,\n            po.po_requisition_lines_all      prla,\n            po.po_req_distributions_all      prda,\n            po.po_distributions_all          pda\n        WHERE\n                prla.requisition_line_id = prda.requisition_line_id\n            AND pda.line_location_id = plla.line_location_id\n            AND pda.req_distribution_id = prda.distribution_id\n            AND prla.requisition_header_id = prha.requisition_header_id\n            AND ROWNUM = 1\n    ) requisition_approved_date,\n    (\n        CASE\n            WHEN nvl(plla.approved_flag, 'N') IN (\n                'Y',\n                'R'\n            )\n                 AND plla.closed_code NOT IN (\n                'CLOSED',\n                'CLOSED FOR RECEIVING',\n                'FINALLY CLOSED'\n            )\n                 AND nvl(plla.closed_date, trunc(sysdate) + 1) > trunc(sysdate)\n                 AND nvl(plla.cancel_date, trunc(sysdate) + 1) > trunc(sysdate)\n                 AND ( plla.quantity - nvl(plla.quantity_received, 0) - nvl(plla.quantity_cancelled, 0) ) > 0 THEN\n                'Yes'\n            ELSE\n                'No'\n        END\n    ) is_po_shipment_open,\n    nvl((\n        SELECT\n            CASE\n                WHEN prha.interface_source_code = 'INV'\n                     AND nvl(prla.kanban_card_id, 0) > 0 THEN\n                    'Kanban'\n                WHEN prha.interface_source_code = 'INV'\n                     AND nvl(prla.kanban_card_id, 0) = 0 THEN\n                    'Min Max'\n                WHEN prha.interface_source_code = 'MSC'\n                     AND nvl(prla.kanban_card_id, 0) = 0 THEN\n                    'MRP'\n                WHEN prha.interface_source_code IS NULL\n                     AND prha.approved_date IS NOT NULL\n                     AND prla.item_id IS NULL THEN\n                    'iProcurement'\n                WHEN prha.interface_source_code IS NULL\n                     AND prha.approved_date IS NOT NULL THEN\n                    'Manual'\n                WHEN prha.interface_source_code IS NOT NULL THEN\n                    prha.interface_source_code\n                ELSE\n                    'Manual'\n            END\n        FROM\n            po.po_requisition_headers_all    prha, po.po_requisition_lines_all      prla, po.po_req_distributions_all      prda, po.po_distributions_all          pda\n        WHERE\n                prla.requisition_line_id = prda.requisition_line_id\n            AND pda.line_location_id = plla.line_location_id\n            AND pda.req_distribution_id = prda.distribution_id\n            AND prla.requisition_header_id = prha.requisition_header_id\n            AND ROWNUM = 1\n    ), 'Manual') po_source,\n    (\n        SELECT\n            MIN(spd.sugg_dock_date)\n        FROM\n            xxcoh.xxcoh_sup_peg_datamart spd\n        WHERE\n                spd.organization_id = plla.ship_to_organization_id\n            AND spd.po_line_location_id = plla.line_location_id\n            AND pla.item_id = spd.sup_item_id\n            AND spd.plnorg_id = plla.ship_to_organization_id\n    ) sugg_earliest_dock_date\nFROM\n    po.po_headers_all                    pha,\n    po.po_releases_all                   pra,\n    po.po_line_locations_all             plla,\n    po.po_lines_all                      pla,\n    apps.org_organization_definitions    mp\nWHERE\n        plla.po_header_id = pha.po_header_id\n    AND plla.po_release_id = pra.po_release_id (+)\n    AND plla.ship_to_organization_id = mp.organization_id\n    AND pla.po_header_id = pha.po_header_id\n    AND pla.po_line_id = plla.po_line_id\n    AND pha.org_id = mp.operating_unit\n    AND pha.type_lookup_code IN (\n        'STANDARD',\n        'BLANKET'\n    )\n    AND mp.operating_unit = (\n        SELECT\n            operating_unit\n        FROM\n            apps.org_organization_definitions ood2\n        WHERE\n            ood2.organization_code = '\"&ORG&\"'\n    )\n    AND EXISTS (\n        SELECT\n            1\n        FROM\n            po.po_distributions_all pda\n        WHERE\n            pda.line_location_id = plla.line_location_id\n    )\n\"\n, CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"PO_NUMBER\", \"PO Number\"}, {\"PURCHASING_CATEGORY\", \"Purchasing Category\"}, {\"RELEASE_NUM\", \"Release Number\"}, {\"REVISION_NUM\", \"Revision Number\"}, {\"PO_APPROVAL_MODE\", \"Approval Mode\"}, {\"PO_KEY\", \"PO Key\"}, {\"PO_BUYER\", \"PO Buyer\"}, {\"PLANNER_CODE\", \"Planner Code\"}, {\"ITEM_TYPE\", \"Item Type\"}, {\"PO_TYPE\", \"PO Type\"}, {\"COMMENTS\", \"Comments\"}, {\"APPROVED_FLAG\", \"Approved Flag\"}, {\"FOB_LOOKUP_CODE\", \"FOB\"}, {\"EXTRACT_DATE\", \"Extract Date\"}, {\"ORGANIZATION_CODE\", \"Organization Code\"}, {\"DOCUMENT_CREATION_METHOD\", \"Creation Method\"}, {\"LINE_NUM\", \"Line Number\"}, {\"PO_ITEM_NUMBER\", \"PO Item Number\"}, {\"PO_ITEM_REVISION\", \"PO Item Revision\"}, {\"PO_ITEM_DESCRIPTION\", \"PO Item Description\"}, {\"CURRENCY_CODE\", \"Currency Code\"}, {\"UNIT_PRICE\", \"Unit Price\"}, {\"SHIPMENT_NUM\", \"Shipment Number\"}, {\"CLOSED_CODE\", \"Shipment Closed Code\"}, {\"NEED_BY_DATE\", \"Need By Date\"}, {\"PROMISED_DATE\", \"Promised Date\"}, {\"QUANTITY\", \"Shipment Quantity\"}, {\"QUANTITY_RECEIVED\", \"Quantity Received\"}, {\"QUANTITY_CANCELLED\", \"Quantity Cancelled\"}, {\"QUANTITY_ACCEPTED\", \"Quantity Accepted\"}, {\"QUANTITY_BILLED\", \"Quantity Billed\"}, {\"QUANTITY_DELIVERED\", \"Quantity Delivered\"}, {\"PPV_APOP_OR_ITEM_COST\", \"APOP or Item Cost\"}, {\"PPV_RATE_PERCENT\", \"PPV Rate Percent\"}, {\"PPV_APPROVAL_REQUIRED\", \"PPV Approval Required Flag\"}, {\"PPV_REASON\", \"PPV Reason\"}, {\"DESTINATION_TYPE_CODE\", \"Destination Type Code\"}, {\"IS_PO_SHIPMENT_OPEN\", \"Shipment Open Flag\"}, {\"LINE_TYPE\", \"Line Type\"}, {\"DOCUMENT_REFERENCE_NUMBER\", \"Document Reference Number\"}, {\"DOCUMENT_REFERENCE_TYPE\", \"Document Reference Type\"}, {\"CONSIGNED_FLAG\", \"Consigned Flag\"}, {\"PO_SOURCE\", \"PO Source\"}, {\"FIRST_APPROVED_DATE\", \"First Approved Date\"}, {\"REQUISITION_APPROVED_DATE\", \"Requisition Approved Date\"}, {\"CREATION_DATE\", \"Creation Date\"}, {\"RATE_DATE\", \"Rate Date\"}, {\"LAST_PO_ACCEPTANCE_DATE\", \"Last Acceptance Date\"}, {\"FUNCTIONAL_RATE\", \"Functional Rate\"}, {\"CLOSED_DATE\", \"Closed Date\"}, {\"CLOSED_FOR_INVOICE_DATE\", \"Closed for Invoice Date\"}, {\"CLOSED_FOR_RECEIVING_DATE\", \"Closed for Receiving Date\"}, {\"CLOSED_REASON\", \"Closed Reason\"}, {\"SHIPMENT_CLOSED_DATE\", \"Shipment Closed Date\"}, {\"CONSUMPTION_ADVICE_FLAG\", \"Consumption Advice Flag\"}, {\"PO_UNIT_OF_MEASURE\", \"Unit of Measure\"}, {\"DESTINATION_SUBINVENTORY\", \"Destination Subinventory\"}, {\"APPROVED_DATE\", \"Approved Date\"}, {\"PO_KEY_APPROVED_DATE\", \"PO Key Approved Date\"}, {\"PO_KEY_ORIGINAL_APPROVED_DATE\", \"PO Key Original Approved Date\"}, {\"SUGG_EARLIEST_DOCK_DATE\", \"Suggested Dock Date\"}, {\"LOCAL_EXTRACT_DATE\", \"Local Extract Date\"}, {\"PO_KEY_BUYER\", \"PO Key Buyer\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Blanket_Agreement = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, \n  Query=\"\n  SELECT\n    sysdate extract_date,\n    from_tz(cast (sysdate as timestamp),'PST') at time zone '\"&Local&\"' local_extract_date,\n    pha.segment1,\n    pha.revision_num,\n    pla.line_num,\n    pha.vendor_id,\n    pha.vendor_site_id,\n    pha.agent_id,\n    poa.agent_name                                                                      buyer_name,\n    nvl(decode(pha.global_agreement_flag, 'Y', 'Yes', 'No'), 'No')                      global_agreement_flag,\n    (\n        SELECT\n            MAX(mir.revision)\n        FROM\n            apps.mtl_item_revisions_b mir\n        WHERE\n                mir.organization_id = msi.organization_id\n            AND mir.inventory_item_id = msi.inventory_item_id\n            AND implementation_date = (\n                SELECT\n                    MAX(implementation_date)\n                FROM\n                    apps.mtl_item_revisions_b mir\n                WHERE\n                        mir.organization_id = msi.organization_id\n                    AND mir.inventory_item_id = msi.inventory_item_id\n            )\n    ) item_revision,\n    (\n        SELECT\n            hrl.location_code\n        FROM\n            apps.hr_locations hrl\n        WHERE\n            hrl.location_id = pha.ship_to_location_id\n    ) ship_to_location,\n    pha.currency_code,\n    nvl(pha.rate_date, pha.creation_date)                                               rate_date,\n    pha.rate_type,\n    pha.start_date,\n    trunc(least(nvl(pla.expiration_date, '01-JAN-2099'), pha.end_date))                 blanket_expiration_date,\n    pha.po_header_id,\n    pla.item_revision                                                                   blanket_item_revision,\n    pov.vendor_name,\n    pvs.vendor_site_code,\n    pla.item_description,\n    pla.unit_meas_lookup_code                                                           blanket_unit_of_measure,\n    (\n        SELECT\n            MIN(phaa.approved_date)\n        FROM\n            apps.po_headers_archive_all phaa\n        WHERE\n                phaa.po_header_id = pha.po_header_id\n            AND phaa.revision_num = 0\n    ) blanket_first_approved_date,\n    (\n        SELECT\n            MIN(phaa.approved_date)\n        FROM\n            apps.po_headers_archive_all    phaa,\n            apps.po_lines_archive_all      plaa\n        WHERE\n                phaa.po_header_id = pha.po_header_id\n            AND plaa.po_header_id = phaa.po_header_id\n            AND plaa.po_line_id = pla.po_line_id\n            AND plaa.revision_num = pha.revision_num\n    ) first_approved_date,\n    (\n        CASE\n            WHEN nvl(pha.closed_code, 'OPEN') = 'OPEN'\n                 AND nvl(pla.closed_code, 'OPEN') = 'OPEN'\n                 AND pla.cancel_date IS NULL\n                 AND pla.closed_date IS NULL THEN\n                'Yes'\n            ELSE\n                'No'\n        END\n    ) blanket_open_flag,\n    nvl((\n        SELECT\n            gbpa_release\n        FROM\n            (\n                SELECT\n                    pla.from_line_id                                                 gbpar_line_id, pla.from_header_id                                               gbpar_header_id, SUM(plla.quantity - nvl(plla.quantity_cancelled,\n                    0))             gbpa_release\n                FROM\n                    po.po_line_locations_all    plla, po.po_lines_all             pla\n                WHERE\n                        plla.po_line_id = pla.po_line_id\n                    AND nvl(plla.consigned_flag, 'N') = 'N'\n                    AND plla.approved_flag IN(\n                        'Y', 'R'\n                    )\n                    AND pla.from_header_id IS NOT NULL\n                    AND pla.from_line_id IS NOT NULL\n                GROUP BY\n                    pla.item_id, pla.from_line_id, pla.from_header_id\n            ) gbpar\n        WHERE\n                gbpar.gbpar_line_id = pla.po_line_id\n            AND gbpar.gbpar_header_id = pha.po_header_id\n    ), 0) + nvl((\n        SELECT\n            bpa_release\n        FROM\n            (\n                SELECT\n                    plla.org_id, pla.po_header_id, pla.po_line_id, SUM(plla.quantity - nvl(plla.quantity_cancelled, 0)) bpa_release\n                FROM\n                    po.po_line_locations_all    plla, po.po_lines_all             pla\n                WHERE\n                        plla.po_line_id = pla.po_line_id\n                    AND nvl(plla.consigned_flag, 'N') = 'N'\n                    AND plla.po_release_id IS NOT NULL\n                GROUP BY\n                    plla.org_id, pla.po_header_id, pla.po_line_id\n            ) bpar\n        WHERE\n                bpar.po_line_id = pla.po_line_id\n            AND bpar.po_header_id = pha.po_header_id\n            AND bpar.org_id = pha.org_id\n    ), 0) quantity_released,\n    CASE\n        WHEN pla.quantity_committed IS NULL THEN\n            nvl(pla.committed_amount, pha.amount_limit) / pla.unit_price\n        ELSE\n            pla.quantity_committed\n    END quantity_committed,\n    pha.creation_date,\n    pla.unit_price,\n    msi.segment1                                                                        item_number,\n    msi.inventory_item_id,\n    pha.approved_date,\n    nvl(pha.authorization_status, 'INCOMPLETE')                                         blanket_authorization_status,\n    pha.last_update_date,\n    pla.po_line_id,\n    msi.planner_code,\n    pha.amount_limit,\n    pla.cancel_date,\n    pla.closed_date,\n    CASE\n        WHEN LEAST(pla.expiration_date, pha.end_date) > trunc(sysdate) THEN\n            trunc(sysdate) - trunc(pha.start_date)\n        ELSE\n            LEAST(pla.expiration_date, pha.end_date) - trunc(pha.start_date)\n    END blanket_age_days,\n    (\n        CASE\n            WHEN trunc(nvl(nvl(pla.expiration_date, pha.end_date), sysdate + 1)) < trunc(sysdate) THEN\n                'Yes'\n            ELSE\n                'No'\n        END\n    ) blanket_expired_flag,\n    (\n        SELECT\n            asld.asl_id\n            || '_'\n            || asld.using_organization_id\n        FROM\n            apps.po_asl_documents_v asld\n        WHERE\n                asld.document_line_id = pla.po_line_id\n            AND asld.vendor_site_id = pha.vendor_site_id\n            AND asld.item_id = pla.item_id\n            AND ROWNUM = 1\n    ) asl_key,\n    CASE\n        WHEN (\n            SELECT\n                asld.asl_id\n                || '_'\n                || asld.using_organization_id\n            FROM\n                apps.po_asl_documents_v asld\n            WHERE\n                    asld.document_line_id = pla.po_line_id\n                AND asld.vendor_site_id = pha.vendor_site_id\n                AND asld.item_id = pla.item_id\n                AND ROWNUM = 1\n        ) IS NOT NULL THEN\n            'Yes'\n        ELSE\n            'No'\n    END used_in_asl_flag,\n    nvl(pha.rate, 1)                                                                    functional_rate\nFROM\n    apps.org_organization_definitions    ood,\n    appsread.po_headers_all              pha,\n    po.po_lines_all                      pla,\n    apps.po_vendors                      pov,\n    apps.po_vendor_sites_all             pvs,\n    apps.po_agents_v                     poa,\n    inv.mtl_system_items_b               msi\nWHERE\n        1 = 1\n    AND ood.operating_unit = pha.org_id\n    AND pha.po_header_id = pla.po_header_id\n    AND pha.vendor_id = pov.vendor_id\n    AND pha.vendor_site_id = pvs.vendor_site_id\n    AND poa.agent_id = pha.agent_id\n    AND pha.type_lookup_code = 'BLANKET'\n    AND pla.item_id = msi.inventory_item_id\n    AND OOD.ORGANIZATION_CODE = '\"&ORG&\"' \n    AND pha.authorization_status IN (\n        'APPROVED',\n        'IN PROCESS',\n        'PRE-APPROVED',\n        'REQUIRES REAPPROVAL'\n    )\n    AND msi.organization_id = ood.organization_id \"\n, CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"SEGMENT1\", \"Blanket Number\"}, {\"REVISION_NUM\", \"Revision Number\"}, {\"BLANKET_OPEN_FLAG\", \"Open Flag\"}, {\"EXTRACT_DATE\", \"Extract Date\"}, {\"LINE_NUM\", \"Line Number\"}, {\"CREATION_DATE\", \"Creation Date\"}, {\"START_DATE\", \"Start Date\"}, {\"BLANKET_EXPIRATION_DATE\", \"Expiration Date\"}, {\"BUYER_NAME\", \"Blanket Buyer Name\"}, {\"ITEM_REVISION\", \"Item Revision\"}, {\"GLOBAL_AGREEMENT_FLAG\", \"Global Blanket Flag\"}, {\"CURRENCY_CODE\", \"Currency Code\"}, {\"RATE_DATE\", \"Rate Date\"}, {\"BLANKET_ITEM_REVISION\", \"Blanket Item Revision\"}, {\"VENDOR_NAME\", \"Vendor Name\"}, {\"VENDOR_SITE_CODE\", \"Vendor Site\"}, {\"ITEM_DESCRIPTION\", \"Item Description\"}, {\"QUANTITY_COMMITTED\", \"Committed Quantity\"}, {\"UNIT_PRICE\", \"Unit Price\"}, {\"ITEM_NUMBER\", \"Item Number\"}, {\"APPROVED_DATE\", \"Approved Date\"}, {\"FIRST_APPROVED_DATE\", \"First Approved Date\"}, {\"QUANTITY_RELEASED\", \"Released Quantity\"}, {\"AMOUNT_LIMIT\", \"Amount Limit\"}, {\"PLANNER_CODE\", \"Planner Code\"}, {\"BLANKET_AGE_DAYS\", \"Blanket Age Days\"}, {\"BLANKET_EXPIRED_FLAG\", \"Expired Flag\"}, {\"SHIP_TO_LOCATION\", \"Ship To Location\"}, {\"USED_IN_ASL_FLAG\", \"Used in ASL Flag\"}, {\"BLANKET_AUTHORIZATION_STATUS\", \"Authorization Status\"}, {\"RATE_TYPE\", \"Rate Type\"}, {\"LAST_UPDATE_DATE\", \"Last Update Date\"}, {\"CANCEL_DATE\", \"Cancel Date\"}, {\"CLOSED_DATE\", \"Closed Date\"}, {\"BLANKET_UNIT_OF_MEASURE\", \"Unit of Measure\"}, {\"BLANKET_FIRST_APPROVED_DATE\", \"Blanket First Approved Date\"}, {\"LOCAL_EXTRACT_DATE\", \"Local Extract Date\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Quote = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, \n  Query=\"\n  SELECT\n   sysdate extract_date,\n    from_tz(cast (sysdate as timestamp),'PST') at time zone '\"&Local&\"' local_extract_date,\n   ood.organization_code,\n   pha.segment1 quote_number,\n   pha.quote_type_lookup_code,\n   pha.quotation_class_code,\n   pha.quote_vendor_quote_number,\n   pha.start_date quote_start_date,\n   trunc(least(nvl(plla.end_date, '01-JAN-2099'), nvl(pla.expiration_date, '01-JAN-2099'), pha.end_date)) quote_expiration_date,\n   pha.vendor_id,\n   pha.vendor_site_id,\n   pha.reply_date,\n   pha.quote_warning_delay,\n   pla.po_line_id,\n   plla.line_location_id,\n   decode(pha.status_lookup_code, 'A', 'Active', 'C', 'Closed', 'I', 'In Process', 'P', 'Printed') quote_status,\n   (\n        SELECT\n            MAX(mir.revision)\n        FROM\n            apps.mtl_item_revisions_b mir\n        WHERE\n                mir.organization_id = msi.organization_id\n            AND mir.inventory_item_id = msi.inventory_item_id\n            AND IMPLEMENTATION_DATE = (\n                SELECT\n                    MAX(IMPLEMENTATION_DATE)\n                FROM\n                    apps.mtl_item_revisions_b mir\n                WHERE\n                        mir.organization_id = msi.organization_id\n                    AND mir.inventory_item_id = msi.inventory_item_id\n            )\n    ) item_revision,\n   CASE\n      WHEN\n         pha.status_lookup_code = 'A' \n         AND trunc(least(nvl(plla.end_date, '01-JAN-2099'), nvl(pla.expiration_date, '01-JAN-2099'), pha.end_date)) > sysdate \n         AND pha.start_date < sysdate \n      THEN\n         'Yes' \n      ELSE\n         'No' \n   END\n   quote_active \n   , pla.line_num \n   , poa.agent_name buyer_name , \n   (\n      SELECT\n         hrl.location_code \n      FROM\n         apps.hr_locations hrl \n      WHERE\n         hrl.location_id = pha.ship_to_location_id\n   )\n   ship_to_location,\n   pha.currency_code,\n   pla.item_revision quote_item_revision,\n   pla.unit_meas_lookup_code quote_unit_of_measure,\n   pov.vendor_name,\n   pvs.vendor_site_code,\n   msi.segment1 item_number,\n   pla.item_description,\n   pha.creation_date,\n      msi.inventory_item_id,\n      msi.planner_code,\n      (\n         SELECT\n            asld.asl_id || '_' || asld.using_organization_id \n         FROM\n            apps.po_asl_documents_v asld \n         WHERE\n            asld.document_line_id = pla.po_line_id \n            AND asld.vendor_site_id = pha.vendor_site_id \n            AND asld.item_id = pla.item_id \n            AND rownum = 1\n      )\n      asl_key,\n      Case when (\n         SELECT\n            asld.asl_id || '_' || asld.using_organization_id \n         FROM\n            apps.po_asl_documents_v asld \n         WHERE\n            asld.document_line_id = pla.po_line_id \n            AND asld.vendor_site_id = pha.vendor_site_id \n            AND asld.item_id = pla.item_id \n            AND rownum = 1\n      ) is not null then 'Yes' else 'No' end\n      USED_IN_ASL,\n      plla.quantity price_break_qty,\n      nvl(plla.price_override, pla.unit_price) price_break,\n      nvl(plla.price_discount, 0) / 100 price_break_discount \n   FROM\n      apps.org_organization_definitions ood,\n      appsread.po_headers_all pha,\n      po.po_lines_all pla,\n      po.po_line_locations_all plla,\n      apps.po_vendors pov,\n      apps.po_vendor_sites_all pvs,\n      apps.po_agents_v poa,\n      inv.mtl_system_items_b msi \n   WHERE\n      1 = 1 \n      AND ood.operating_unit = pha.org_id \n      AND pha.po_header_id = pla.po_header_id \n      AND pha.vendor_id = pov.vendor_id \n      AND pha.vendor_site_id = pvs.vendor_site_id \n      AND poa.agent_id = pha.agent_id \n      AND pha.type_lookup_code = 'QUOTATION' \n      AND pla.item_id = msi.inventory_item_id \n      AND ood.organization_code = '\"&ORG&\"' \n      AND msi.organization_id = ood.organization_id \n      AND pla.po_line_id = plla.po_line_id ( + )\n      \", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"EXTRACT_DATE\", \"Extract Date\"}, {\"ORGANIZATION_CODE\", \"Organization Code\"}, {\"ITEM_NUMBER\", \"Item Number\"}, {\"ITEM_REVISION\", \"Item Revision\"}, {\"QUOTE_NUMBER\", \"Quote Number\"}, {\"QUOTE_TYPE_LOOKUP_CODE\", \"Quote Type\"}, {\"QUOTE_VENDOR_QUOTE_NUMBER\", \"Supplier Quote Number\"}, {\"QUOTE_START_DATE\", \"Start Date\"}, {\"QUOTE_EXPIRATION_DATE\", \"Expiration Date\"}, {\"REPLY_DATE\", \"Supplier Reply Date\"}, {\"QUOTE_WARNING_DELAY\", \"Warning Delay\"}, {\"QUOTE_STATUS\", \"Quote Status\"}, {\"QUOTE_ACTIVE\", \"Active Flag\"}, {\"LINE_NUM\", \"Line Number\"}, {\"BUYER_NAME\", \"Quote Buyer\"}, {\"SHIP_TO_LOCATION\", \"Ship To Location\"}, {\"CURRENCY_CODE\", \"Currency Code\"}, {\"QUOTE_ITEM_REVISION\", \"Quote Item Revision\"}, {\"VENDOR_NAME\", \"Supplier Name\"}, {\"VENDOR_SITE_CODE\", \"Supplier Site Code\"}, {\"ITEM_DESCRIPTION\", \"Item Description\"}, {\"CREATION_DATE\", \"Creation Date\"}, {\"PLANNER_CODE\", \"Planner Code\"}, {\"PRICE_BREAK_QTY\", \"Break Quantity\"}, {\"PRICE_BREAK\", \"Price Break\"}, {\"PRICE_BREAK_DISCOUNT\", \"Price Discount\"}, {\"QUOTE_UNIT_OF_MEASURE\", \"Unit of Measure\"}, {\"USED_IN_ASL\", \"Used in ASL Flag\"}, {\"LOCAL_EXTRACT_DATE\", \"Local Extract Date\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Purchase_Order_Distribution = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, \n  Query=\"\n  SELECT\n    sysdate extract_date,\n    from_tz(cast (sysdate as timestamp),'PST') at time zone '\"&Local&\"' local_extract_date,\n    mp.organization_code,\n    case when pda.po_release_id > 0\n    then pha.segment1||'_'||pra.release_num\n    else pha.segment1\n    end po_key,\n    pha.segment1 po_number,\n    pra.release_num,\n    pha.currency_code,\n    pla.line_num line_num,\n    plla.shipment_num po_shipment_num,\n    msi.segment1 item_number,\n    pla.item_description item_description,\n    msi.planner_code,\n    pla.unit_price,\n    pda.po_distribution_id,\n    pda.po_header_id,\n    pda.po_line_id,\n    pda.line_location_id,\n    pda.po_release_id,\n    pda.code_combination_id,\n    gcc.segment1    entity_code,\n    gcc.segment2    department_code,\n    gcc.segment3    account_code,\n    gcc.segment4    project_code,\n    pda.quantity_delivered,\n    pda.quantity_billed,\n    pda.quantity_cancelled,\n    pda.req_distribution_id,\n    pda.destination_type_code,\n    pda.destination_subinventory\nFROM\n    apps.po_distributions_all            pda,\n    apps.org_organization_definitions    mp,\n    apps.gl_code_combinations            gcc,\n    apps.po_lines_all pla,\n    apps.po_headers_all pha,\n    apps.po_releases_all pra,\n    apps.po_line_locations_all plla,\n    apps.mtl_system_items msi\nWHERE\n        1 = 1\n    AND pda.org_id = mp.operating_unit\n    and pla.po_line_id= pda.po_line_id\n    AND pda.destination_organization_id = mp.organization_id\n    and mp.organization_id=msi.organization_id (+)\n    and pla.item_id = msi.inventory_item_id (+)\n    and pda.line_location_id = plla.line_location_id\n    and pda.po_line_id = pla.po_line_id\n    and pda.po_header_id = pha.po_header_id\n    and pda.po_release_id= pra.po_release_id (+)\n    AND mp.operating_unit = (\n        SELECT\n            operating_unit\n        FROM\n            apps.org_organization_definitions ood2\n        WHERE\n            ood2.organization_code = '\"&ORG&\"'\n    )\n    AND gcc.code_combination_id = pda.code_combination_id\n\"\n, CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"ORGANIZATION_CODE\", \"Organization Code\"}, {\"ENTITY_CODE\", \"Entity Code\"}, {\"DEPARTMENT_CODE\", \"Department Code\"}, {\"ACCOUNT_CODE\", \"Account Code\"}, {\"PROJECT_CODE\", \"Project Code\"}, {\"QUANTITY_DELIVERED\", \"Quantity Delivered\"}, {\"QUANTITY_BILLED\", \"Quantity Billed\"}, {\"QUANTITY_CANCELLED\", \"Quantity Cancelled\"}, {\"DESTINATION_TYPE_CODE\", \"Destination Type Code\"}, {\"DESTINATION_SUBINVENTORY\", \"Destination Subinventory\"}, {\"PO_NUMBER\", \"PO Number\"}, {\"RELEASE_NUM\", \"Release Number\"}, {\"CURRENCY_CODE\", \"Currency Code\"}, {\"UNIT_PRICE\", \"Unit Price\"}, {\"PO_KEY\", \"PO Key\"}, {\"EXTRACT_DATE\", \"Extract Date\"}, {\"LOCAL_EXTRACT_DATE\", \"Local Extract Date\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Requisition = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, Query=\"\nSELECT\n    sysdate extract_date,\n    from_tz(cast (sysdate as timestamp),'PST') at time zone '\"&Local&\"' local_extract_date,\n    prha.segment1                                           requisition_number,\n    prha.description,\n    prla.requisition_line_id,\n    (\n        SELECT\n            info.attribute_value\n        FROM\n            apps.por_template_info             info,\n            apps.por_template_attributes_tl    tmpt,\n            apps.por_template_attributes_b     tmpb,\n            apps.mtl_categories_b              mc2\n        WHERE\n                1 = 1\n            AND prla.requisition_line_id = info.requisition_line_id\n            AND info.attribute_code = tmpt.attribute_code\n            AND tmpb.attribute_code = tmpt.attribute_code\n            AND tmpt.attribute_name IN (\n                'Commitment',\n                'Fixed Asset Number'\n            )\n            AND tmpt.language = 'US'\n            AND mc2.category_id = prla.category_id\n            AND mc2.segment1 IN (\n                'Capital - Commitment',\n                'Capital - Commitment Add On'\n            )\n            AND ROWNUM = 1\n    ) cer,\n    (\n        SELECT\n            pah.creation_date\n        FROM\n            apps.po_action_history pah\n        WHERE\n                pah.object_id = prha.requisition_header_id\n            AND object_type_code = 'REQUISITION'\n            AND sequence_num = 0\n    ) submit_date,\n    prha.requisition_header_id,\n    prha.approved_date,\n    prla.line_num,\n    prla.item_id,\n    prla.item_description,\n    prla.category_id,\n    mc.segment1                                             purchasing_category,\n    decode(prla.cancel_flag, 'Y', 'Yes', 'No')              cancel_flag,\n    mp.organization_code                                    ship_to_org,\n    prla.agent_return_note                                  buyer_return_note,\n    prla.kanban_card_id,\n    CASE\n        WHEN prla.currency_code IS NULL THEN\n            (\n                SELECT\n                    sob.currency_code\n                FROM\n                    apps.gl_sets_of_books sob\n                WHERE\n                    sob.set_of_books_id = ood.set_of_books_id\n            )\n        ELSE\n            prla.currency_code\n    END currency_code,\n    nvl(prla.currency_unit_price, prla.unit_price)          currency_unit_price,\n    (\n        SELECT\n            mp.organization_code\n        FROM\n            apps.mtl_parameters mp\n        WHERE\n            mp.organization_id = prla.source_organization_id\n    ) source_org,\n    (\n        SELECT\n            full_name\n        FROM\n            apps.per_people_f ppf\n        WHERE\n                ppf.person_id = prla.to_person_id\n            AND ROWNUM = 1\n    ) to_person,\n    prla.vendor_site_id,\n    prla.destination_context,\n    nvl(prla.rate, 1)                                       rate,\n    nvl(prla.rate_date, prha.approved_date)                 rate_date,\n    prla.cancel_date,\n    prla.need_by_date,\n    prla.closed_code,\n    prla.purchase_basis,\n    prla.matching_basis,\n    prla.quantity,\n    prla.quantity_cancelled,\n    prla.quantity_received,\n    prla.quantity_delivered,\n    prla.destination_subinventory,\n    gcc.segment1                                            entity,\n    gcc.segment2                                            dept,\n    gcc.segment3                                            account,\n    gcc.segment4                                            project,\n    gcc.segment5                                            intercompany,\n    (\n        SELECT\n            pha.segment1\n        FROM\n            apps.po_headers_all           pha,\n            apps.po_line_locations_all    plla\n        WHERE\n                plla.line_location_id = prla.line_location_id\n            AND pha.po_header_id = plla.po_header_id\n            AND pha.org_id = prla.org_id\n    ) po_number,\n    pv.vendor_name,\n    pvs.vendor_site_code,\n    prla.line_location_id,\n    prda.distribution_id requisition_distribution_id,\n    msi.segment1                                            item_number\nFROM\n    po.po_requisition_headers_all        prha,\n    po.po_requisition_lines_all          prla,\n    po.po_req_distributions_all          prda,\n    apps.org_organization_definitions    ood,\n    apps.mtl_categories_b                mc,\n    apps.mtl_parameters                  mp,\n    apps.gl_code_combinations            gcc,\n    apps.po_vendors                      pv,\n    apps.po_vendor_sites_all             pvs,\n    apps.mtl_system_items_b              msi\nWHERE\n        prla.requisition_line_id = prda.requisition_line_id\n    AND prla.requisition_header_id = prha.requisition_header_id\n    AND ood.operating_unit = prha.org_id\n    AND ood.organization_code = '\"&ORG&\"'\n    AND mc.category_id = prla.category_id\n    AND prla.destination_organization_id = mp.organization_id\n    AND gcc.code_combination_id = prda.code_combination_id\n    AND prla.vendor_site_id = pvs.vendor_site_id (+)\n    AND prla.vendor_id = pv.vendor_id (+)\n    AND prla.item_id = msi.inventory_item_id (+)\n    AND mp.organization_id = msi.organization_id (+)\n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"REQUISITION_NUMBER\", \"Requisition Number\"}, {\"DESCRIPTION\", \"Description\"}, {\"CER\", \"CER Number\"}, {\"SUBMIT_DATE\", \"Submit Date\"}, {\"APPROVED_DATE\", \"Approved Date\"}, {\"LINE_NUM\", \"Line\"}, {\"ITEM_DESCRIPTION\", \"Item Description\"}, {\"PURCHASING_CATEGORY\", \"Purchasing Category\"}, {\"CANCEL_FLAG\", \"Cancel Flag\"}, {\"SHIP_TO_ORG\", \"Ship to Org\"}, {\"TO_PERSON\", \"To Person\"}, {\"DESTINATION_CONTEXT\", \"Destination\"}, {\"BUYER_RETURN_NOTE\", \"Buyer Return Notes\"}, {\"CURRENCY_UNIT_PRICE\", \"Unit Price\"}, {\"PO_NUMBER\", \"PO Number\"}, {\"VENDOR_NAME\", \"Supplier Name\"}, {\"VENDOR_SITE_CODE\", \"Supplier Site\"}, {\"SOURCE_ORG\", \"Source Org\"}, {\"CURRENCY_CODE\", \"Currency Code\"}, {\"PURCHASE_BASIS\", \"Purchase Basis\"}, {\"CANCEL_DATE\", \"Cancel Date\"}, {\"NEED_BY_DATE\", \"Need By Date\"}, {\"CLOSED_CODE\", \"Closed Code\"}, {\"QUANTITY\", \"Quantity\"}, {\"QUANTITY_CANCELLED\", \"Quantity Cancelled\"}, {\"QUANTITY_RECEIVED\", \"Quantity Received\"}, {\"QUANTITY_DELIVERED\", \"Quantity Delivered\"}, {\"DESTINATION_SUBINVENTORY\", \"Destination Subinventory\"}, {\"MATCHING_BASIS\", \"Matching Basis\"}, {\"RATE\", \"Rate to LOC\"}, {\"RATE_DATE\", \"Rate Date\"}, {\"EXTRACT_DATE\", \"Extract Date\"}, {\"DEPT\", \"GL Department Code\"}, {\"ACCOUNT\", \"GL Account Code\"}, {\"PROJECT\", \"GL Project Code\"}, {\"INTERCOMPANY\", \"GL Intercompany Code\"}, {\"ENTITY\", \"GL Entity Code\"}, {\"ITEM_NUMBER\", \"Item Number\"}, {\"LOCAL_EXTRACT_DATE\", \"Local Extract Date\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Local = let\r\n  Local = \"Asia/Singapore\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type any]\r\nin\r\n  Local;\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"ASL_Document","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"ASL_Document.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Local Extract Date","dataType":"dateTime"},{"name":"ASL_ID","dataType":"double"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"Item Number","dataType":"string"},{"name":"VENDOR_ID","dataType":"double"},{"name":"VENDOR_SITE_ID","dataType":"double"},{"name":"DOCUMENT_HEADER_ID","dataType":"double"},{"name":"DOCUMENT_LINE_ID","dataType":"double"},{"name":"Sequence","dataType":"double"},{"name":"Document Type","dataType":"string"},{"name":"Document Number","dataType":"string"},{"name":"Document Line Number","dataType":"double"},{"name":"Document Status","dataType":"string"},{"name":"USING_ORGANIZATION_ID","dataType":"double"},{"name":"Using Organization Code","dataType":"string"},{"name":"ASL_KEY","dataType":"string"},{"name":"ASL Used Flag","dataType":"string"},{"name":"ASL Type","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-05-19T23:01:38.6860702+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/ce276721-52e2-469d-9e0c-27847437e430/ASL_Document.csv?snapshot=2022-05-19T23%3A01%3A38.6247611Z"}]},{"$type":"LocalEntity","name":"ASL_Attribute","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"ASL_Attribute.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Local Extract Date","dataType":"dateTime"},{"name":"ASL_ID","dataType":"double"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"Item Number","dataType":"string"},{"name":"ASL Status","dataType":"string"},{"name":"VENDOR_ID","dataType":"double"},{"name":"VENDOR_SITE_ID","dataType":"double"},{"name":"Release Method","dataType":"string"},{"name":"Consigned From Supplier","dataType":"string"},{"name":"Minimum Order Quantity","dataType":"double"},{"name":"Purchasing UOM","dataType":"string"},{"name":"Processing Lead Time","dataType":"double"},{"name":"Fixed Lot Multiplier","dataType":"double"},{"name":"Fixed Order Quantity","dataType":"double"},{"name":"Using Organization Code","dataType":"string"},{"name":"Scheduler Name","dataType":"string"},{"name":"ASL Used Flag","dataType":"string"},{"name":"ASL Type","dataType":"string"},{"name":"ASL_KEY","dataType":"string"},{"name":"Actively Sourced Flag","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-19T23:02:42.4786996+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/ce276721-52e2-469d-9e0c-27847437e430/ASL_Attribute.csv?snapshot=2022-05-19T23%3A02%3A42.4379938Z"}]},{"$type":"LocalEntity","name":"Purchase_Order","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Purchase_Order.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Local Extract Date","dataType":"dateTime"},{"name":"PO_RELEASE_ID","dataType":"double"},{"name":"Approval Mode","dataType":"string"},{"name":"Organization Code","dataType":"string"},{"name":"PO Number","dataType":"string"},{"name":"PO_KEY_AGENT_ID","dataType":"double"},{"name":"PO_AGENT_ID","dataType":"int64"},{"name":"PO Buyer","dataType":"string"},{"name":"PO Key Buyer","dataType":"string"},{"name":"Release Number","dataType":"double"},{"name":"Revision Number","dataType":"double"},{"name":"Creation Date","dataType":"dateTime"},{"name":"PO Key Original Approved Date","dataType":"dateTime"},{"name":"Functional Rate","dataType":"double"},{"name":"PO Key","dataType":"string"},{"name":"Comments","dataType":"string"},{"name":"Approved Flag","dataType":"string"},{"name":"Approved Date","dataType":"dateTime"},{"name":"PO Key Approved Date","dataType":"dateTime"},{"name":"FOB","dataType":"string"},{"name":"PO Type","dataType":"string"},{"name":"Purchasing Category","dataType":"string"},{"name":"Shipment Closed Date","dataType":"dateTime"},{"name":"Closed for Receiving Date","dataType":"dateTime"},{"name":"Closed for Invoice Date","dataType":"dateTime"},{"name":"Closed Reason","dataType":"string"},{"name":"Closed Date","dataType":"dateTime"},{"name":"Shipment Closed Code","dataType":"string"},{"name":"Destination Subinventory","dataType":"string"},{"name":"Last Acceptance Date","dataType":"dateTime"},{"name":"Line Type","dataType":"string"},{"name":"Creation Method","dataType":"string"},{"name":"Consumption Advice Flag","dataType":"string"},{"name":"Rate Date","dataType":"dateTime"},{"name":"PO_LINE_ID","dataType":"double"},{"name":"ITEM_ID","dataType":"double"},{"name":"Line Number","dataType":"double"},{"name":"PO Item Number","dataType":"string"},{"name":"PO Item Revision","dataType":"string"},{"name":"PO Item Description","dataType":"string"},{"name":"Unit of Measure","dataType":"string"},{"name":"Planner Code","dataType":"string"},{"name":"Currency Code","dataType":"string"},{"name":"Unit Price","dataType":"double"},{"name":"LINE_LOCATION_ID","dataType":"double"},{"name":"Shipment Number","dataType":"double"},{"name":"Need By Date","dataType":"dateTime"},{"name":"Promised Date","dataType":"dateTime"},{"name":"Shipment Quantity","dataType":"double"},{"name":"Quantity Received","dataType":"double"},{"name":"Quantity Cancelled","dataType":"double"},{"name":"Quantity Billed","dataType":"double"},{"name":"Quantity Accepted","dataType":"double"},{"name":"Quantity Delivered","dataType":"double"},{"name":"Document Reference Type","dataType":"string"},{"name":"Document Reference Number","dataType":"string"},{"name":"VENDOR_ID","dataType":"double"},{"name":"VENDOR_SITE_ID","dataType":"double"},{"name":"Consigned Flag","dataType":"string"},{"name":"Item Type","dataType":"string"},{"name":"APOP or Item Cost","dataType":"string"},{"name":"PPV Rate Percent","dataType":"string"},{"name":"PPV Approval Required Flag","dataType":"string"},{"name":"PPV Reason","dataType":"string"},{"name":"Destination Type Code","dataType":"string"},{"name":"First Approved Date","dataType":"dateTime"},{"name":"Requisition Approved Date","dataType":"dateTime"},{"name":"Shipment Open Flag","dataType":"string"},{"name":"PO Source","dataType":"string"},{"name":"Suggested Dock Date","dataType":"dateTime"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-05-19T23:03:32.4086308+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/ce276721-52e2-469d-9e0c-27847437e430/Purchase_Order.csv?snapshot=2022-05-19T23%3A03%3A32.3392495Z"}]},{"$type":"LocalEntity","name":"Blanket_Agreement","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Blanket_Agreement.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Local Extract Date","dataType":"dateTime"},{"name":"Blanket Number","dataType":"string"},{"name":"Revision Number","dataType":"double"},{"name":"Line Number","dataType":"double"},{"name":"VENDOR_ID","dataType":"double"},{"name":"VENDOR_SITE_ID","dataType":"double"},{"name":"AGENT_ID","dataType":"int64"},{"name":"Blanket Buyer Name","dataType":"string"},{"name":"Global Blanket Flag","dataType":"string"},{"name":"Item Revision","dataType":"string"},{"name":"Ship To Location","dataType":"string"},{"name":"Currency Code","dataType":"string"},{"name":"Rate Date","dataType":"dateTime"},{"name":"Rate Type","dataType":"string"},{"name":"Start Date","dataType":"dateTime"},{"name":"Expiration Date","dataType":"dateTime"},{"name":"PO_HEADER_ID","dataType":"double"},{"name":"Blanket Item Revision","dataType":"string"},{"name":"Vendor Name","dataType":"string"},{"name":"Vendor Site","dataType":"string"},{"name":"Item Description","dataType":"string"},{"name":"Unit of Measure","dataType":"string"},{"name":"Blanket First Approved Date","dataType":"dateTime"},{"name":"First Approved Date","dataType":"dateTime"},{"name":"Open Flag","dataType":"string"},{"name":"Released Quantity","dataType":"double"},{"name":"Committed Quantity","dataType":"double"},{"name":"Creation Date","dataType":"dateTime"},{"name":"Unit Price","dataType":"double"},{"name":"Item Number","dataType":"string"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"Approved Date","dataType":"dateTime"},{"name":"Authorization Status","dataType":"string"},{"name":"Last Update Date","dataType":"dateTime"},{"name":"PO_LINE_ID","dataType":"double"},{"name":"Planner Code","dataType":"string"},{"name":"Amount Limit","dataType":"double"},{"name":"Cancel Date","dataType":"dateTime"},{"name":"Closed Date","dataType":"dateTime"},{"name":"Blanket Age Days","dataType":"double"},{"name":"Expired Flag","dataType":"string"},{"name":"ASL_KEY","dataType":"string"},{"name":"Used in ASL Flag","dataType":"string"},{"name":"FUNCTIONAL_RATE","dataType":"double"}],"partitions":[{"name":"Part001","refreshTime":"2022-05-19T23:01:33.9735183+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/ce276721-52e2-469d-9e0c-27847437e430/Blanket_Agreement.csv?snapshot=2022-05-19T23%3A01%3A33.9294658Z"}]},{"$type":"LocalEntity","name":"Quote","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Quote.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Local Extract Date","dataType":"dateTime"},{"name":"Organization Code","dataType":"string"},{"name":"Quote Number","dataType":"string"},{"name":"Quote Type","dataType":"string"},{"name":"QUOTATION_CLASS_CODE","dataType":"string"},{"name":"Supplier Quote Number","dataType":"string"},{"name":"Start Date","dataType":"dateTime"},{"name":"Expiration Date","dataType":"dateTime"},{"name":"VENDOR_ID","dataType":"double"},{"name":"VENDOR_SITE_ID","dataType":"double"},{"name":"Supplier Reply Date","dataType":"dateTime"},{"name":"Warning Delay","dataType":"double"},{"name":"PO_LINE_ID","dataType":"double"},{"name":"LINE_LOCATION_ID","dataType":"double"},{"name":"Quote Status","dataType":"string"},{"name":"Item Revision","dataType":"string"},{"name":"Active Flag","dataType":"string"},{"name":"Line Number","dataType":"double"},{"name":"Quote Buyer","dataType":"string"},{"name":"Ship To Location","dataType":"string"},{"name":"Currency Code","dataType":"string"},{"name":"Quote Item Revision","dataType":"string"},{"name":"Unit of Measure","dataType":"string"},{"name":"Supplier Name","dataType":"string"},{"name":"Supplier Site Code","dataType":"string"},{"name":"Item Number","dataType":"string"},{"name":"Item Description","dataType":"string"},{"name":"Creation Date","dataType":"dateTime"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"Planner Code","dataType":"string"},{"name":"ASL_KEY","dataType":"string"},{"name":"Used in ASL Flag","dataType":"string"},{"name":"Break Quantity","dataType":"double"},{"name":"Price Break","dataType":"double"},{"name":"Price Discount","dataType":"double"}],"partitions":[{"name":"Part001","refreshTime":"2022-05-19T23:01:27.9473415+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/ce276721-52e2-469d-9e0c-27847437e430/Quote.csv?snapshot=2022-05-19T23%3A01%3A27.9079332Z"}]},{"$type":"LocalEntity","name":"Purchase_Order_Distribution","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Purchase_Order_Distribution.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Local Extract Date","dataType":"dateTime"},{"name":"Organization Code","dataType":"string"},{"name":"PO Key","dataType":"string"},{"name":"PO Number","dataType":"string"},{"name":"Release Number","dataType":"double"},{"name":"Currency Code","dataType":"string"},{"name":"LINE_NUM","dataType":"double"},{"name":"PO_SHIPMENT_NUM","dataType":"double"},{"name":"ITEM_NUMBER","dataType":"string"},{"name":"ITEM_DESCRIPTION","dataType":"string"},{"name":"PLANNER_CODE","dataType":"string"},{"name":"Unit Price","dataType":"double"},{"name":"PO_DISTRIBUTION_ID","dataType":"double"},{"name":"PO_HEADER_ID","dataType":"double"},{"name":"PO_LINE_ID","dataType":"double"},{"name":"LINE_LOCATION_ID","dataType":"double"},{"name":"PO_RELEASE_ID","dataType":"double"},{"name":"CODE_COMBINATION_ID","dataType":"double"},{"name":"Entity Code","dataType":"string"},{"name":"Department Code","dataType":"string"},{"name":"Account Code","dataType":"string"},{"name":"Project Code","dataType":"string"},{"name":"Quantity Delivered","dataType":"double"},{"name":"Quantity Billed","dataType":"double"},{"name":"Quantity Cancelled","dataType":"double"},{"name":"REQ_DISTRIBUTION_ID","dataType":"double"},{"name":"Destination Type Code","dataType":"string"},{"name":"Destination Subinventory","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-05-19T23:02:08.6228679+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/ce276721-52e2-469d-9e0c-27847437e430/Purchase_Order_Distribution.csv?snapshot=2022-05-19T23%3A02%3A08.5805009Z"}]},{"$type":"LocalEntity","name":"Requisition","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Requisition.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Local Extract Date","dataType":"dateTime"},{"name":"Requisition Number","dataType":"string"},{"name":"Description","dataType":"string"},{"name":"REQUISITION_LINE_ID","dataType":"double"},{"name":"CER Number","dataType":"string"},{"name":"Submit Date","dataType":"dateTime"},{"name":"REQUISITION_HEADER_ID","dataType":"double"},{"name":"Approved Date","dataType":"dateTime"},{"name":"Line","dataType":"double"},{"name":"ITEM_ID","dataType":"double"},{"name":"Item Description","dataType":"string"},{"name":"CATEGORY_ID","dataType":"double"},{"name":"Purchasing Category","dataType":"string"},{"name":"Cancel Flag","dataType":"string"},{"name":"Ship to Org","dataType":"string"},{"name":"Buyer Return Notes","dataType":"string"},{"name":"KANBAN_CARD_ID","dataType":"double"},{"name":"Currency Code","dataType":"string"},{"name":"Unit Price","dataType":"double"},{"name":"Source Org","dataType":"string"},{"name":"To Person","dataType":"string"},{"name":"VENDOR_SITE_ID","dataType":"double"},{"name":"Destination","dataType":"string"},{"name":"Rate to LOC","dataType":"double"},{"name":"Rate Date","dataType":"dateTime"},{"name":"Cancel Date","dataType":"dateTime"},{"name":"Need By Date","dataType":"dateTime"},{"name":"Closed Code","dataType":"string"},{"name":"Purchase Basis","dataType":"string"},{"name":"Matching Basis","dataType":"string"},{"name":"Quantity","dataType":"double"},{"name":"Quantity Cancelled","dataType":"double"},{"name":"Quantity Received","dataType":"double"},{"name":"Quantity Delivered","dataType":"double"},{"name":"Destination Subinventory","dataType":"string"},{"name":"GL Entity Code","dataType":"string"},{"name":"GL Department Code","dataType":"string"},{"name":"GL Account Code","dataType":"string"},{"name":"GL Project Code","dataType":"string"},{"name":"GL Intercompany Code","dataType":"string"},{"name":"PO Number","dataType":"string"},{"name":"Supplier Name","dataType":"string"},{"name":"Supplier Site","dataType":"string"},{"name":"LINE_LOCATION_ID","dataType":"double"},{"name":"REQUISITION_DISTRIBUTION_ID","dataType":"double"},{"name":"Item Number","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-05-19T23:02:14.9602657+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/ce276721-52e2-469d-9e0c-27847437e430/Requisition.csv?snapshot=2022-05-19T23%3A02%3A14.9238465Z"}]}]}