{"name":"COHREP_SITE_WIP_TRX1","description":"","version":"1.0","culture":"en-US","modifiedTime":"2021-03-22T08:15:37.1699496+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":true,"queriesMetadata":{"ORG":{"queryId":"bc0c5fb2-e788-4428-90d4-a32b55a632c7","queryName":"ORG"},"LocalTZ":{"queryId":"3f91c359-6609-4cfb-8223-357bc7d16b1b","queryName":"LocalTZ"},"TBU":{"queryId":"7a3e3441-9d9d-4428-9110-c770e33d9a8f","queryName":"TBU"},"WIP_Job":{"queryId":"cf8b63a8-291f-4b80-806e-f58dbc1bd678","queryName":"WIP_Job","loadEnabled":true},"WIP_Value":{"queryId":"c35df7fc-92dc-44ab-a3c6-06d93a18a816","queryName":"WIP_Value","loadEnabled":true},"WIP_Job_TBU":{"queryId":"9e14061b-6e6f-459c-aad6-a0eba89cc343","queryName":"WIP_Job_TBU","loadEnabled":true},"WIP_Value_TBU":{"queryId":"9c42a777-7384-4f0c-90d6-f39cbc196639","queryName":"WIP_Value_TBU","loadEnabled":true},"Resource_Transaction":{"queryId":"2aaedbd8-005f-4f7e-b378-e1991b7504bc","queryName":"Resource_Transaction","loadEnabled":true}},"document":"section Section1;\r\nshared ORG = let\r\n  ORG = \"PPG\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type text]\r\nin\r\n  ORG;\r\nshared LocalTZ = let\r\n  Local = \"Asia/Singapore\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type any]\r\nin\r\n  Local;\r\nshared TBU = let\r\n  TBU = \"Multiple\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type text]\r\nin\r\n  TBU;\r\nshared WIP_Job = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, \n  Query=\"\n  SELECT SYSDATE                                                 extract_date, \n       from_tz(cast (sysdate as timestamp),'PST') at time zone '\"&LocalTZ&\"' local_extract_date,\n       mp.organization_code, \n       wdjv.wip_entity_id, \n       wdjv.creation_date,\n       wdjv.wip_entity_name                                    job_number, \n       wdjv.description                                        job_description, \n       wdjv.primary_item_id, \n       Decode (wdjv.firm_planned_flag, 1, 'Yes', \n                                       'No')                   firm_planned_flag \n       , \n       Decode (wdjv.job_type, 1, 'Standard', \n                              'Non-Standard')                  job_type, \n       (SELECT msi.segment1 \n        FROM   inv.mtl_system_items_b msi \n        WHERE  msi.organization_id = mp.organization_id \n               AND msi.inventory_item_id = wdjv.primary_item_id \n               AND ROWNUM = 1) \n       assembly_item_number, \n       wdjv.bom_revision                                       job_bom_revision, \n       (SELECT wdj.source_code \n        FROM   apps.wip_discrete_jobs wdj \n        WHERE  wdj.wip_entity_id = wdjv.wip_entity_id \n               AND wdj.organization_id = mp.organization_id)   job_source, \n       wdjv.class_code,\n       wdjv.status_type_disp                                   job_status, \n       wdjv.start_quantity, \n       wdjv.scheduled_start_date, \n       wdjv.scheduled_completion_date,\n       (SELECT Min(wop.first_unit_start_date) \n        FROM   apps.wip_operations wop \n        WHERE  wop.wip_entity_id = wdjv.wip_entity_id ) first_unit_start_date,\n       (SELECT Max(wop.date_last_moved) \n        FROM   apps.wip_operations wop \n        WHERE  wop.wip_entity_id = wdjv.wip_entity_id ) last_moved_date, \n       wdjv.net_quantity, \n       nvl(wdjv.quantity_completed,0) quantity_completed, \n       nvl(wdjv.quantity_scrapped,0) quantity_scrapped, \n       nvl(wdjv.quantity_remaining,0) quantity_remaining, \n       wdjv.project_number, \n       wdjv.kanban_card_number, \n       wdjv.lot_number, \n       (SELECT order_number \n        FROM   apps.oe_order_headers_all \n        WHERE  header_id = wdjv.attribute1)                    sales_order_dff, \n       (SELECT line_number \n        FROM   apps.oe_order_lines_all \n        WHERE  line_id = wdjv.attribute2) \n       sales_order_line_dff, \n       wdjv.attribute7 service_request_dff, \n       wdjv.attribute10                                        assembly_sn_dff, \n       wdjv.date_released, \n       wdjv.date_completed, \n       wdjv.date_closed, \n       wdjv.demand_class, \n       wdjv.completion_subinventory,\n       (select concatenated_segments from apps.mtl_item_locations_kfv mil \n       where mil.organization_id = mp.organization_id \n       and mil.inventory_location_id = wdjv.completion_locator_id) completion_locator,\n       fu1.user_name                                           job_created_by, \n       fu2.user_name \n       job_last_updated_by \nFROM   apps.wip_discrete_jobs_v wdjv, \n       apps.mtl_parameters mp, \n       applsys.fnd_user fu1, \n       applsys.fnd_user fu2 \nWHERE  MP.organization_code = '\"&ORG&\"' \n       AND mp.organization_id = wdjv.organization_id\n       AND fu1.user_id = wdjv.created_by \n       AND fu2.user_id = wdjv.last_updated_by\n       \"\n, CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"EXTRACT_DATE\", \"Extract Date\"}, {\"ORGANIZATION_CODE\", \"Organization Code\"}, {\"JOB_NUMBER\", \"Job Number\"}, {\"JOB_DESCRIPTION\", \"Job Description\"}, {\"FIRM_PLANNED_FLAG\", \"Firmed Job\"}, {\"JOB_TYPE\", \"Job Type\"}, {\"ASSEMBLY_ITEM_NUMBER\", \"Assembly Item Number\"}, {\"JOB_BOM_REVISION\", \"BOM Revision\"}, {\"JOB_SOURCE\", \"Source\"}, {\"CLASS_CODE\", \"Class Code\"}, {\"JOB_STATUS\", \"Job Status\"}, {\"START_QUANTITY\", \"Quantity\"}, {\"SCHEDULED_START_DATE\", \"Scheduled Start Date\"}, {\"CREATION_DATE\", \"Creation Date\"}, {\"SCHEDULED_COMPLETION_DATE\", \"Scheduled Completion Date\"}, {\"LAST_MOVED_DATE\", \"Last Moved Date\"}, {\"FIRST_UNIT_START_DATE\", \"First Unit Start Date\"}, {\"NET_QUANTITY\", \"Net Quantity\"}, {\"QUANTITY_COMPLETED\", \"Completed Quantity\"}, {\"QUANTITY_SCRAPPED\", \"Scrapped Quantity\"}, {\"QUANTITY_REMAINING\", \"Remaining Quantity\"}, {\"PROJECT_NUMBER\", \"Project Number\"}, {\"KANBAN_CARD_NUMBER\", \"Kanban Card Number\"}, {\"LOT_NUMBER\", \"Lot Number\"}, {\"DATE_RELEASED\", \"Released Date\"}, {\"DATE_COMPLETED\", \"Completed Date\"}, {\"DATE_CLOSED\", \"Closed Date\"}, {\"DEMAND_CLASS\", \"Demand Class\"}, {\"JOB_CREATED_BY\", \"Created By\"}, {\"JOB_LAST_UPDATED_BY\", \"Last Updated By\"}, {\"COMPLETION_SUBINVENTORY\", \"Completion Subinventory\"}, {\"COMPLETION_LOCATOR\", \"Completion Locator\"}, {\"SALES_ORDER_DFF\", \"Sales Order DFF\"}, {\"SALES_ORDER_LINE_DFF\", \"Sales Order Line DFF\"}, {\"SERVICE_REQUEST_DFF\", \"Service Request DFF\"}, {\"ASSEMBLY_SN_DFF\", \"Assembly Serial Number DFF\"}}),\r\n  ConvertToList = Table.AddColumn(#\"Renamed columns\", \"ClassCodeToList\", each Text.ToList([Class Code])),\r\n  LowerCaseChars = {\"a\"..\"z\"},\r\n  // add Character.FromNumber(8203) to make the column unique\r\n  AddInvisibleChars = Table.AddColumn(ConvertToList, \"AddInvisibleChars\", each List.Transform(\n            [ClassCodeToList], \n            each \n            if \n            List.Contains(#\"LowerCaseChars\", _) \n            then \n            _ & Character.FromNumber(8203) \n            else _\n            )),\r\n  // Add case sensitive column as result of adding invisible characters Character.FromNumber(8203)\r\n  AddCaseSensitiveColumn = Table.AddColumn(AddInvisibleChars, \"Class Code CS\", each Text.Combine([AddInvisibleChars])),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(AddCaseSensitiveColumn, {{\"Class Code CS\", type text}, {\"Completed Quantity\", type number}, {\"Scrapped Quantity\", type number}, {\"Remaining Quantity\", type number}}),\r\n  #\"Removed columns\" = Table.RemoveColumns(#\"Changed column type\", {\"ClassCodeToList\", \"AddInvisibleChars\"}),\r\n  #\"Renamed columns 1\" = Table.RenameColumns(#\"Removed columns\", {{\"LOCAL_EXTRACT_DATE\", \"Local Extract Date\"}})\r\nin\r\n  #\"Renamed columns 1\";\r\nshared WIP_Value = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true,\n    Query=\"\n      SELECT\n         sysdate extract_date,\n         from_tz(cast (sysdate as timestamp),'PST') at time zone '\"&LocalTZ&\"' local_extract_date,\n         we.wip_entity_name,\n         we.wip_entity_id,\n         mp.organization_code,\n         oap.period_name,\n         wpb.acct_period_id,\n         oap.period_start_date,\n         SUM(wpb.tl_material_out),\n         SUM(wpb.tl_material_var),\n         SUM(wpb.tl_material_overhead_out),\n         SUM(wpb.tl_material_overhead_var),\n         SUM(wpb.tl_resource_in),\n         SUM(wpb.tl_resource_out),\n         SUM(wpb.tl_resource_var),\n         SUM(wpb.tl_outside_processing_in),\n         SUM(wpb.tl_outside_processing_out),\n         SUM(wpb.tl_outside_processing_var),\n         SUM(wpb.tl_overhead_in),\n         SUM(wpb.tl_overhead_out),\n         SUM(wpb.tl_overhead_var),\n         SUM(wpb.pl_material_in),\n         SUM(wpb.pl_material_out),\n         SUM(wpb.pl_material_var),\n         SUM(wpb.pl_material_overhead_in),\n         SUM(wpb.pl_material_overhead_out),\n         SUM(wpb.pl_material_overhead_var),\n         SUM(wpb.pl_resource_in),\n         SUM(wpb.pl_resource_out),\n         SUM(wpb.pl_resource_var),\n         SUM(wpb.pl_outside_processing_var),\n         SUM(wpb.pl_outside_processing_in),\n         SUM(wpb.pl_outside_processing_out),\n         SUM(wpb.pl_overhead_in),\n         SUM(wpb.pl_overhead_out),\n         SUM(wpb.pl_overhead_var)\n      FROM\n         apps.wip_period_balances wpb,\n         inv.mtl_parameters mp,\n         apps.wip_entities we,\n         apps.org_acct_periods oap\n      WHERE\n         mp.organization_id = we.organization_id \n         AND wpb.wip_entity_id = we.wip_entity_id \n         AND OAP.organization_id = we.organization_id \n         AND oap.acct_period_id = wpb.acct_period_id\n         AND mp.organization_code = '\"&ORG&\"'\n      GROUP BY\n        we.wip_entity_name,\n         we.wip_entity_id,\n         mp.organization_code,\n         oap.period_name,\n         wpb.acct_period_id,\n         oap.period_start_date\n    \", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"SUM(WPB.TL_MATERIAL_VAR)\", \"TL Material Variance\"}, {\"SUM(WPB.TL_MATERIAL_OUT)\", \"TL Material Output\"}, {\"SUM(WPB.TL_MATERIAL_OVERHEAD_OUT)\", \"TL Material Overhead Output\"}, {\"SUM(WPB.TL_MATERIAL_OVERHEAD_VAR)\", \"TL Material Overhead Variance\"}, {\"SUM(WPB.TL_RESOURCE_VAR)\", \"TL Resource Variance\"}, {\"SUM(WPB.TL_OUTSIDE_PROCESSING_VAR)\", \"TL OSP Variance\"}, {\"SUM(WPB.TL_OVERHEAD_VAR)\", \"TL Overhead Variance\"}, {\"SUM(WPB.PL_MATERIAL_VAR)\", \"PL Material Variance\"}, {\"SUM(WPB.PL_MATERIAL_OVERHEAD_VAR)\", \"PL Material Overhead Variance\"}, {\"SUM(WPB.PL_RESOURCE_VAR)\", \"PL Resource Variance\"}, {\"SUM(WPB.PL_OUTSIDE_PROCESSING_VAR)\", \"PL OSP Variance\"}, {\"SUM(WPB.PL_OVERHEAD_VAR)\", \"PL Overhead Variance\"}, {\"SUM(WPB.TL_RESOURCE_IN)\", \"TL Resource Input\"}, {\"SUM(WPB.TL_RESOURCE_OUT)\", \"TL Resource Output\"}, {\"SUM(WPB.TL_OVERHEAD_IN)\", \"TL Overhead Input\"}, {\"SUM(WPB.TL_OVERHEAD_OUT)\", \"TL Overhead Output\"}, {\"SUM(WPB.TL_OUTSIDE_PROCESSING_IN)\", \"TL OSP Input\"}, {\"SUM(WPB.TL_OUTSIDE_PROCESSING_OUT)\", \"TL OSP Output\"}, {\"SUM(WPB.PL_MATERIAL_IN)\", \"PL Material Input\"}, {\"SUM(WPB.PL_MATERIAL_OUT)\", \"PL Material Output\"}, {\"SUM(WPB.PL_MATERIAL_OVERHEAD_IN)\", \"PL Material Overhead Input\"}, {\"SUM(WPB.PL_MATERIAL_OVERHEAD_OUT)\", \"PL Material Overhead Output\"}, {\"SUM(WPB.PL_RESOURCE_IN)\", \"PL Resource Input\"}, {\"SUM(WPB.PL_RESOURCE_OUT)\", \"PL Resource Output\"}, {\"SUM(WPB.PL_OVERHEAD_IN)\", \"PL Overhead Input\"}, {\"SUM(WPB.PL_OVERHEAD_OUT)\", \"PL Overhead Output\"}, {\"SUM(WPB.PL_OUTSIDE_PROCESSING_IN)\", \"PL OSP Input\"}, {\"SUM(WPB.PL_OUTSIDE_PROCESSING_OUT)\", \"PL OSP Output\"}, {\"EXTRACT_DATE\", \"Extract Date\"}, {\"WIP_ENTITY_NAME\", \"Job Number\"}, {\"ORGANIZATION_CODE\", \"Organization Code\"}, {\"PERIOD_NAME\", \"Period Name\"}, {\"PERIOD_START_DATE\", \"Period Start Date\"}, {\"LOCAL_EXTRACT_DATE\", \"Local Extract Date\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared WIP_Job_TBU = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, \n  Query=\"\n  SELECT SYSDATE                                                 extract_date, \n       from_tz(cast (sysdate as timestamp),'PST') at time zone '\"&LocalTZ&\"' local_extract_date,\n       mp.organization_code, \n       wdjv.wip_entity_id, \n       wdjv.creation_date,\n       wdjv.wip_entity_name                                    job_number, \n       wdjv.description                                        job_description, \n       wdjv.primary_item_id, \n       Decode (wdjv.firm_planned_flag, 1, 'Yes', \n                                       'No')                   firm_planned_flag \n       , \n       Decode (wdjv.job_type, 1, 'Standard', \n                              'Non-Standard')                  job_type, \n       (SELECT msi.segment1 \n        FROM   inv.mtl_system_items_b msi \n        WHERE  msi.organization_id = mp.organization_id \n               AND msi.inventory_item_id = wdjv.primary_item_id \n               AND ROWNUM = 1) \n       assembly_item_number, \n       wdjv.bom_revision                                       job_bom_revision, \n       (SELECT wdj.source_code \n        FROM   apps.wip_discrete_jobs wdj \n        WHERE  wdj.wip_entity_id = wdjv.wip_entity_id \n               AND wdj.organization_id = mp.organization_id)   job_source, \n       wdjv.class_code,\n       wdjv.status_type_disp                                   job_status, \n       wdjv.start_quantity, \n       wdjv.scheduled_start_date, \n       wdjv.scheduled_completion_date,\n       (SELECT Min(wop.first_unit_start_date) \n        FROM   apps.wip_operations wop \n        WHERE  wop.wip_entity_id = wdjv.wip_entity_id ) first_unit_start_date,\n       (SELECT Max(wop.date_last_moved) \n        FROM   apps.wip_operations wop \n        WHERE  wop.wip_entity_id = wdjv.wip_entity_id ) last_moved_date, \n       wdjv.net_quantity, \n       nvl(wdjv.quantity_completed,0) quantity_completed, \n       nvl(wdjv.quantity_scrapped,0) quantity_scrapped, \n       nvl(wdjv.quantity_remaining,0) quantity_remaining, \n       wdjv.project_number, \n       wdjv.kanban_card_number, \n       wdjv.lot_number, \n       (SELECT order_number \n        FROM   apps.oe_order_headers_all \n        WHERE  header_id = wdjv.attribute1)                    sales_order_dff, \n       (SELECT line_number \n        FROM   apps.oe_order_lines_all \n        WHERE  line_id = wdjv.attribute2) \n       sales_order_line_dff, \n       wdjv.attribute7 service_request_dff, \n       wdjv.attribute10                                        assembly_sn_dff, \n       wdjv.date_released, \n       wdjv.date_completed, \n       wdjv.date_closed, \n       wdjv.demand_class, \n       wdjv.completion_subinventory,\n       (select concatenated_segments from apps.mtl_item_locations_kfv mil \n       where mil.organization_id = mp.organization_id \n       and mil.inventory_location_id = wdjv.completion_locator_id) completion_locator,\n       fu1.user_name                                           job_created_by, \n       fu2.user_name \n       job_last_updated_by\n       FROM\n    apps.wip_discrete_jobs_v    wdjv,\n    apps.mtl_parameters         mp,\n    applsys.fnd_user            fu1,\n    applsys.fnd_user            fu2,\n    apps.mtl_system_items_b     msi \nWHERE\n        mp.organization_id = msi.organization_id\n    AND msi.inventory_item_id = wdjv.primary_item_id\n    AND mp.organization_id = wdjv.organization_id\n    AND fu1.user_id = wdjv.created_by\n    AND fu2.user_id = wdjv.last_updated_by\n    AND EXISTS (\n        SELECT\n            1\n        FROM\n            apps.mtl_item_categories_v mic\n        WHERE\n                mic.inventory_item_id = msi.inventory_item_id\n            AND mic.organization_id = msi.organization_id\n            AND mic.category_set_name IN (\n                'Product',\n                'ORG Product'\n            )\n            AND mic.segment1 = '\"&TBU&\"'\n    )\n       \"\n, CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"EXTRACT_DATE\", \"Extract Date\"}, {\"ORGANIZATION_CODE\", \"Organization Code\"}, {\"JOB_NUMBER\", \"Job Number\"}, {\"JOB_DESCRIPTION\", \"Job Description\"}, {\"FIRM_PLANNED_FLAG\", \"Firmed Job\"}, {\"JOB_TYPE\", \"Job Type\"}, {\"ASSEMBLY_ITEM_NUMBER\", \"Assembly Item Number\"}, {\"JOB_BOM_REVISION\", \"BOM Revision\"}, {\"JOB_SOURCE\", \"Source\"}, {\"CLASS_CODE\", \"Class Code\"}, {\"JOB_STATUS\", \"Job Status\"}, {\"START_QUANTITY\", \"Quantity\"}, {\"SCHEDULED_START_DATE\", \"Scheduled Start Date\"}, {\"CREATION_DATE\", \"Creation Date\"}, {\"SCHEDULED_COMPLETION_DATE\", \"Scheduled Completion Date\"}, {\"LAST_MOVED_DATE\", \"Last Moved Date\"}, {\"FIRST_UNIT_START_DATE\", \"First Unit Start Date\"}, {\"NET_QUANTITY\", \"Net Quantity\"}, {\"QUANTITY_COMPLETED\", \"Completed Quantity\"}, {\"QUANTITY_SCRAPPED\", \"Scrapped Quantity\"}, {\"QUANTITY_REMAINING\", \"Remaining Quantity\"}, {\"PROJECT_NUMBER\", \"Project Number\"}, {\"KANBAN_CARD_NUMBER\", \"Kanban Card Number\"}, {\"LOT_NUMBER\", \"Lot Number\"}, {\"DATE_RELEASED\", \"Released Date\"}, {\"DATE_COMPLETED\", \"Completed Date\"}, {\"DATE_CLOSED\", \"Closed Date\"}, {\"DEMAND_CLASS\", \"Demand Class\"}, {\"JOB_CREATED_BY\", \"Created By\"}, {\"JOB_LAST_UPDATED_BY\", \"Last Updated By\"}, {\"COMPLETION_SUBINVENTORY\", \"Completion Subinventory\"}, {\"COMPLETION_LOCATOR\", \"Completion Locator\"}, {\"SALES_ORDER_DFF\", \"Sales Order DFF\"}, {\"SALES_ORDER_LINE_DFF\", \"Sales Order Line DFF\"}, {\"SERVICE_REQUEST_DFF\", \"Service Request DFF\"}, {\"ASSEMBLY_SN_DFF\", \"Assembly Serial Number DFF\"}}),\r\n  ConvertToList = Table.AddColumn(#\"Renamed columns\", \"ClassCodeToList\", each Text.ToList([Class Code])),\r\n  LowerCaseChars = {\"a\"..\"z\"},\r\n  // add Character.FromNumber(8203) to make the column unique\r\n  AddInvisibleChars = Table.AddColumn(ConvertToList, \"AddInvisibleChars\", each List.Transform(\n            [ClassCodeToList], \n            each \n            if \n            List.Contains(#\"LowerCaseChars\", _) \n            then \n            _ & Character.FromNumber(8203) \n            else _\n            )),\r\n  // Add case sensitive column as result of adding invisible characters Character.FromNumber(8203)\r\n  AddCaseSensitiveColumn = Table.AddColumn(AddInvisibleChars, \"Class Code CS\", each Text.Combine([AddInvisibleChars])),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(AddCaseSensitiveColumn, {{\"Class Code CS\", type text}, {\"Completed Quantity\", type number}, {\"Scrapped Quantity\", type number}, {\"Remaining Quantity\", type number}}),\r\n  #\"Removed columns\" = Table.RemoveColumns(#\"Changed column type\", {\"ClassCodeToList\", \"AddInvisibleChars\"}),\r\n  #\"Renamed columns 1\" = Table.RenameColumns(#\"Removed columns\", {{\"LOCAL_EXTRACT_DATE\", \"Local Extract Date\"}})\r\nin\r\n  #\"Renamed columns 1\";\r\nshared WIP_Value_TBU = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true,\n    Query=\"\n      SELECT\n         sysdate extract_date,\n         from_tz(cast (sysdate as timestamp),'PST') at time zone '\"&LocalTZ&\"' local_extract_date,\n         we.wip_entity_name,\n         we.wip_entity_id,\n         mp.organization_code,\n         oap.period_name,\n         wpb.acct_period_id,\n         oap.period_start_date,\n         SUM(wpb.tl_material_out),\n         SUM(wpb.tl_material_var),\n         SUM(wpb.tl_material_overhead_out),\n         SUM(wpb.tl_material_overhead_var),\n         SUM(wpb.tl_resource_in),\n         SUM(wpb.tl_resource_out),\n         SUM(wpb.tl_resource_var),\n         SUM(wpb.tl_outside_processing_in),\n         SUM(wpb.tl_outside_processing_out),\n         SUM(wpb.tl_outside_processing_var),\n         SUM(wpb.tl_overhead_in),\n         SUM(wpb.tl_overhead_out),\n         SUM(wpb.tl_overhead_var),\n         SUM(wpb.pl_material_in),\n         SUM(wpb.pl_material_out),\n         SUM(wpb.pl_material_var),\n         SUM(wpb.pl_material_overhead_in),\n         SUM(wpb.pl_material_overhead_out),\n         SUM(wpb.pl_material_overhead_var),\n         SUM(wpb.pl_resource_in),\n         SUM(wpb.pl_resource_out),\n         SUM(wpb.pl_resource_var),\n         SUM(wpb.pl_outside_processing_var),\n         SUM(wpb.pl_outside_processing_in),\n         SUM(wpb.pl_outside_processing_out),\n         SUM(wpb.pl_overhead_in),\n         SUM(wpb.pl_overhead_out),\n         SUM(wpb.pl_overhead_var)\n      FROM\n         apps.wip_period_balances wpb,\n         inv.mtl_parameters mp,\n         apps.wip_entities we,\n         apps.org_acct_periods oap\n      WHERE\n         mp.organization_id = we.organization_id \n         AND wpb.wip_entity_id = we.wip_entity_id \n         AND OAP.organization_id = we.organization_id \n         AND oap.acct_period_id = wpb.acct_period_id\n        AND EXISTS (\n        SELECT\n            1\n        FROM\n            apps.mtl_item_categories_v mic\n        WHERE\n                mic.inventory_item_id = we.primary_item_id\n            AND mic.organization_id = mp.organization_id\n            AND mic.category_set_name IN (\n                'Product',\n                'ORG Product'\n            )\n            AND mic.segment1 = '\"&TBU&\"'\n    )\n      GROUP BY\n        we.wip_entity_name,\n         we.wip_entity_id,\n         mp.organization_code,\n         oap.period_name,\n         wpb.acct_period_id,\n         oap.period_start_date\n    \", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"SUM(WPB.TL_MATERIAL_VAR)\", \"TL Material Variance\"}, {\"SUM(WPB.TL_MATERIAL_OUT)\", \"TL Material Output\"}, {\"SUM(WPB.TL_MATERIAL_OVERHEAD_OUT)\", \"TL Material Overhead Output\"}, {\"SUM(WPB.TL_MATERIAL_OVERHEAD_VAR)\", \"TL Material Overhead Variance\"}, {\"SUM(WPB.TL_RESOURCE_VAR)\", \"TL Resource Variance\"}, {\"SUM(WPB.TL_OUTSIDE_PROCESSING_VAR)\", \"TL OSP Variance\"}, {\"SUM(WPB.TL_OVERHEAD_VAR)\", \"TL Overhead Variance\"}, {\"SUM(WPB.PL_MATERIAL_VAR)\", \"PL Material Variance\"}, {\"SUM(WPB.PL_MATERIAL_OVERHEAD_VAR)\", \"PL Material Overhead Variance\"}, {\"SUM(WPB.PL_RESOURCE_VAR)\", \"PL Resource Variance\"}, {\"SUM(WPB.PL_OUTSIDE_PROCESSING_VAR)\", \"PL OSP Variance\"}, {\"SUM(WPB.PL_OVERHEAD_VAR)\", \"PL Overhead Variance\"}, {\"SUM(WPB.TL_RESOURCE_IN)\", \"TL Resource Input\"}, {\"SUM(WPB.TL_RESOURCE_OUT)\", \"TL Resource Output\"}, {\"SUM(WPB.TL_OVERHEAD_IN)\", \"TL Overhead Input\"}, {\"SUM(WPB.TL_OVERHEAD_OUT)\", \"TL Overhead Output\"}, {\"SUM(WPB.TL_OUTSIDE_PROCESSING_IN)\", \"TL OSP Input\"}, {\"SUM(WPB.TL_OUTSIDE_PROCESSING_OUT)\", \"TL OSP Output\"}, {\"SUM(WPB.PL_MATERIAL_IN)\", \"PL Material Input\"}, {\"SUM(WPB.PL_MATERIAL_OUT)\", \"PL Material Output\"}, {\"SUM(WPB.PL_MATERIAL_OVERHEAD_IN)\", \"PL Material Overhead Input\"}, {\"SUM(WPB.PL_MATERIAL_OVERHEAD_OUT)\", \"PL Material Overhead Output\"}, {\"SUM(WPB.PL_RESOURCE_IN)\", \"PL Resource Input\"}, {\"SUM(WPB.PL_RESOURCE_OUT)\", \"PL Resource Output\"}, {\"SUM(WPB.PL_OVERHEAD_IN)\", \"PL Overhead Input\"}, {\"SUM(WPB.PL_OVERHEAD_OUT)\", \"PL Overhead Output\"}, {\"SUM(WPB.PL_OUTSIDE_PROCESSING_IN)\", \"PL OSP Input\"}, {\"SUM(WPB.PL_OUTSIDE_PROCESSING_OUT)\", \"PL OSP Output\"}, {\"EXTRACT_DATE\", \"Extract Date\"}, {\"WIP_ENTITY_NAME\", \"Job Number\"}, {\"ORGANIZATION_CODE\", \"Organization Code\"}, {\"PERIOD_NAME\", \"Period Name\"}, {\"PERIOD_START_DATE\", \"Period Start Date\"}, {\"LOCAL_EXTRACT_DATE\", \"Local Extract Date\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Resource_Transaction = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, \n  Query=\"\n  SELECT\n    SYSDATE                                                 extract_date, \n    from_tz(cast (sysdate as timestamp),'PST') at time zone '\"&LocalTZ&\"' local_extract_date,\n    mp.organization_code,\n    (\n        SELECT\n            we.wip_entity_name\n        FROM\n            apps.wip_entities we\n        WHERE\n            we.wip_entity_id = tr.wip_entity_id\n    ) wip_job,\n    (\n        SELECT\n            we.description\n        FROM\n            apps.wip_entities we\n        WHERE\n            we.wip_entity_id = tr.wip_entity_id\n    ) wip_job_description,\n    CASE\n        WHEN (\n            SELECT\n                COUNT(1)\n            FROM\n                apps.wip_discrete_jobs wdj\n            WHERE\n                wdj.wip_entity_id = tr.wip_entity_id\n        ) > 0 THEN\n            'Yes'\n        ELSE\n            'No'\n    END discrete_job_flag,\n    msi.segment1       item_number,\n    msi.description    item_description,\n    tr.reference       resource_trx_reference,\n    tr.transaction_id,\n    decode(tr.transaction_type, '1', 'Resource transaction', '11', 'Lot Based Split',\n           '12', 'Lot Based Merge', '13', 'Lot Based Bonus', '14',\n           'Lot Based Quantity Update', '15', 'Estimated Scrap Absorption', '16', 'Estimated Scrap Reallocation',\n           '17', 'Direct Shopfloor Delivery', '2', 'Overhead transaction', '3',\n           'Outside processing', '4', 'Cost update', '5', 'Period close variance',\n           '6', 'Job close variance', '7', 'Final completion variance', NULL) transaction_type,\n    tr.transaction_date,\n    tr.source_code,\n    tr.operation_seq_num,\n    tr.resource_seq_num,\n    decode(tr.autocharge_type, '1', 'WIP move', '2', 'Manual',\n           '3', 'PO receipt', '4', 'PO move', NULL) autocharge_type,\n    tr.usage_rate_or_amount,\n    decode(tr.basis_type, '1', 'Item', '2', 'Lot',\n           '3', 'Resource Units', '4', 'Resource Value', '5',\n           'Total Value', '6', 'Activity', NULL) basis_type,\n    tr.transaction_quantity,\n    tr.transaction_uom,\n    tr.primary_quantity,\n    tr.primary_uom,\n    tr.actual_resource_rate,\n    tr.standard_resource_rate,\n    decode(tr.standard_rate_flag, 1, 'Yes', 2, 'No',\n           tr.standard_rate_flag) standard_rate_flag,\n    tr.currency_code,\n    (select period_name from\n    apps.org_acct_periods              ac\n    where tr.acct_period_id = ac.acct_period_id) period_name,\n    --al.name,\n    --en.wip_entity_name,\n    --li.line_code,\n    --ac.period_name,\n    --sy.segment1,\n    --sy.segment1,\n    --de.department_code,\n    --re.resource_code,\n    --alpe.full_name,\n    --cac.activity,\n    --mtr.reason_name,\n  --  pr.project_name,\n    --pr.project_number,\n    cac.activity,\n    tr.attribute_category,\n    tr.attribute1,\n    tr.attribute2 /* IDS */,\n    tr.organization_id,\n    tr.wip_entity_id,\n    tr.line_id,\n    tr.primary_item_id,\n    tr.acct_period_id,\n    tr.department_id,\n    tr.resource_id,\n    tr.employee_id,\n    tr.activity_id,\n    tr.reason_id,\n    tr.move_transaction_id,\n    tr.completion_transaction_id,\n    tr.project_id,\n    tr.task_id,\n    tr.source_line_id /* WHO */,\n    tr.creation_date,\n    tr.created_by,\n    tr.last_update_date,\n    tr.last_updated_by,\n    pr.project_name,\n    pr.project_number,\n    de.department_code,\n    re.resource_code,\n    (\n        SELECT\n            wmt.primary_quantity\n        FROM\n            apps.wip_move_transactions wmt\n        WHERE\n            tr.move_transaction_id = wmt.transaction_id\n    ) move_primary_quantity,\n   (\n        SELECT\n            wmt.fm_operation_seq_num\n        FROM\n            apps.wip_move_transactions wmt\n        WHERE\n            tr.move_transaction_id = wmt.transaction_id\n    ) fm_operation_seq_num,\n   (\n        SELECT\n            wmt.to_operation_seq_num\n        FROM\n            apps.wip_move_transactions wmt\n        WHERE\n            tr.move_transaction_id = wmt.transaction_id\n    ) to_operation_seq_num\nFROM\n    apps.wip_transactions              tr,\n    apps.mtl_parameters                mp,\n    apps.cst_activities                cac,\n    apps.mtl_system_items_b            msi,\n    apps.pjmfv_project_mfg_projects    pr,\n    apps.bom_resources                 re,\n    apps.bom_departments               de\nWHERE\n        mp.organization_id = tr.organization_id\n    AND mp.organization_id = msi.organization_id (+)\n    AND tr.primary_item_id = msi.inventory_item_id (+)\n    AND tr.project_id = pr.project_id (+)\n    AND tr.activity_id = cac.activity_id (+)\n    AND tr.organization_id = re.organization_id (+)\n    AND tr.resource_id = re.resource_id (+)\n    AND tr.organization_id = de.organization_id (+)\n    AND tr.department_id = de.department_id (+)\n    AND mp.organization_code = '\"&ORG&\"' \n       \"\n, CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"ORGANIZATION_CODE\", \"Organization Code\"}, {\"WIP_JOB\", \"WIP Job\"}, {\"DISCRETE_JOB_FLAG\", \"Discrete Job Flag\"}, {\"WIP_JOB_DESCRIPTION\", \"WIP Job Description\"}, {\"PERIOD_NAME\", \"Period Name\"}, {\"ITEM_NUMBER\", \"Item Number\"}, {\"ITEM_DESCRIPTION\", \"Item Description\"}, {\"RESOURCE_TRX_REFERENCE\", \"Resource Transaction Reference\"}, {\"TRANSACTION_TYPE\", \"Transaction Type\"}, {\"TRANSACTION_DATE\", \"Transaction Date\"}, {\"SOURCE_CODE\", \"Source Code\"}, {\"OPERATION_SEQ_NUM\", \"Operation Sequence\"}, {\"RESOURCE_SEQ_NUM\", \"Resource Sequence\"}, {\"AUTOCHARGE_TYPE\", \"Autocharge Type\"}, {\"USAGE_RATE_OR_AMOUNT\", \"Usage Rate or Amount\"}, {\"BASIS_TYPE\", \"Basis Type\"}, {\"TRANSACTION_QUANTITY\", \"Transaction Quantity\"}, {\"TRANSACTION_UOM\", \"Transaction UOM\"}, {\"PRIMARY_QUANTITY\", \"Primary Quantity\"}, {\"PRIMARY_UOM\", \"Primary UOM\"}, {\"ACTUAL_RESOURCE_RATE\", \"Actual Resource Rate\"}, {\"STANDARD_RESOURCE_RATE\", \"Standard Resource Rate\"}, {\"STANDARD_RATE_FLAG\", \"Standard Rate Flag\"}, {\"CURRENCY_CODE\", \"Currency Code\"}, {\"ACTIVITY\", \"Activity Name\"}, {\"CREATED_BY\", \"Created By\"}, {\"CREATION_DATE\", \"Creation Date\"}, {\"PROJECT_NAME\", \"Project Name\"}, {\"PROJECT_NUMBER\", \"Project Number\"}, {\"DEPARTMENT_CODE\", \"Department Code\"}, {\"RESOURCE_CODE\", \"Resource Code\"}, {\"MOVE_PRIMARY_QUANTITY\", \"Move Primary Quantity\"}, {\"FM_OPERATION_SEQ_NUM\", \"From Operation Sequence\"}, {\"TO_OPERATION_SEQ_NUM\", \"To Operation Sequence\"}, {\"EXTRACT_DATE\", \"Extract Date\"}, {\"LOCAL_EXTRACT_DATE\", \"Local Extract Date\"}})\r\nin\r\n  #\"Renamed columns\";\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"WIP_Job","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"WIP_Job.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Local Extract Date","dataType":"dateTime"},{"name":"Organization Code","dataType":"string"},{"name":"WIP_ENTITY_ID","dataType":"double"},{"name":"Creation Date","dataType":"dateTime"},{"name":"Job Number","dataType":"string"},{"name":"Job Description","dataType":"string"},{"name":"PRIMARY_ITEM_ID","dataType":"double"},{"name":"Firmed Job","dataType":"string"},{"name":"Job Type","dataType":"string"},{"name":"Assembly Item Number","dataType":"string"},{"name":"BOM Revision","dataType":"string"},{"name":"Source","dataType":"string"},{"name":"Class Code","dataType":"string"},{"name":"Job Status","dataType":"string"},{"name":"Quantity","dataType":"double"},{"name":"Scheduled Start Date","dataType":"dateTime"},{"name":"Scheduled Completion Date","dataType":"dateTime"},{"name":"First Unit Start Date","dataType":"dateTime"},{"name":"Last Moved Date","dataType":"dateTime"},{"name":"Net Quantity","dataType":"double"},{"name":"Completed Quantity","dataType":"double"},{"name":"Scrapped Quantity","dataType":"double"},{"name":"Remaining Quantity","dataType":"double"},{"name":"Project Number","dataType":"string"},{"name":"Kanban Card Number","dataType":"string"},{"name":"Lot Number","dataType":"string"},{"name":"Sales Order DFF","dataType":"double"},{"name":"Sales Order Line DFF","dataType":"double"},{"name":"Service Request DFF","dataType":"string"},{"name":"Assembly Serial Number DFF","dataType":"string"},{"name":"Released Date","dataType":"dateTime"},{"name":"Completed Date","dataType":"dateTime"},{"name":"Closed Date","dataType":"dateTime"},{"name":"Demand Class","dataType":"string"},{"name":"Completion Subinventory","dataType":"string"},{"name":"Completion Locator","dataType":"string"},{"name":"Created By","dataType":"string"},{"name":"Last Updated By","dataType":"string"},{"name":"Class Code CS","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-12T23:01:08.2363827+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/28b505b1-8f44-44bd-9f88-beeb9307f1b0/WIP_Job.csv?snapshot=2022-06-12T23%3A01%3A08.1990563Z"}]},{"$type":"LocalEntity","name":"WIP_Value","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"WIP_Value.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Local Extract Date","dataType":"dateTime"},{"name":"Job Number","dataType":"string"},{"name":"WIP_ENTITY_ID","dataType":"double"},{"name":"Organization Code","dataType":"string"},{"name":"Period Name","dataType":"string"},{"name":"ACCT_PERIOD_ID","dataType":"double"},{"name":"Period Start Date","dataType":"dateTime"},{"name":"TL Material Output","dataType":"double"},{"name":"TL Material Variance","dataType":"double"},{"name":"TL Material Overhead Output","dataType":"double"},{"name":"TL Material Overhead Variance","dataType":"double"},{"name":"TL Resource Input","dataType":"double"},{"name":"TL Resource Output","dataType":"double"},{"name":"TL Resource Variance","dataType":"double"},{"name":"TL OSP Input","dataType":"double"},{"name":"TL OSP Output","dataType":"double"},{"name":"TL OSP Variance","dataType":"double"},{"name":"TL Overhead Input","dataType":"double"},{"name":"TL Overhead Output","dataType":"double"},{"name":"TL Overhead Variance","dataType":"double"},{"name":"PL Material Input","dataType":"double"},{"name":"PL Material Output","dataType":"double"},{"name":"PL Material Variance","dataType":"double"},{"name":"PL Material Overhead Input","dataType":"double"},{"name":"PL Material Overhead Output","dataType":"double"},{"name":"PL Material Overhead Variance","dataType":"double"},{"name":"PL Resource Input","dataType":"double"},{"name":"PL Resource Output","dataType":"double"},{"name":"PL Resource Variance","dataType":"double"},{"name":"PL OSP Variance","dataType":"double"},{"name":"PL OSP Input","dataType":"double"},{"name":"PL OSP Output","dataType":"double"},{"name":"PL Overhead Input","dataType":"double"},{"name":"PL Overhead Output","dataType":"double"},{"name":"PL Overhead Variance","dataType":"double"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-12T23:01:01.1778641+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/28b505b1-8f44-44bd-9f88-beeb9307f1b0/WIP_Value.csv?snapshot=2022-06-12T23%3A01%3A01.1432860Z"}]},{"$type":"LocalEntity","name":"WIP_Job_TBU","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"WIP_Job_TBU.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Local Extract Date","dataType":"dateTime"},{"name":"Organization Code","dataType":"string"},{"name":"WIP_ENTITY_ID","dataType":"double"},{"name":"Creation Date","dataType":"dateTime"},{"name":"Job Number","dataType":"string"},{"name":"Job Description","dataType":"string"},{"name":"PRIMARY_ITEM_ID","dataType":"double"},{"name":"Firmed Job","dataType":"string"},{"name":"Job Type","dataType":"string"},{"name":"Assembly Item Number","dataType":"string"},{"name":"BOM Revision","dataType":"string"},{"name":"Source","dataType":"string"},{"name":"Class Code","dataType":"string"},{"name":"Job Status","dataType":"string"},{"name":"Quantity","dataType":"double"},{"name":"Scheduled Start Date","dataType":"dateTime"},{"name":"Scheduled Completion Date","dataType":"dateTime"},{"name":"First Unit Start Date","dataType":"dateTime"},{"name":"Last Moved Date","dataType":"dateTime"},{"name":"Net Quantity","dataType":"double"},{"name":"Completed Quantity","dataType":"double"},{"name":"Scrapped Quantity","dataType":"double"},{"name":"Remaining Quantity","dataType":"double"},{"name":"Project Number","dataType":"string"},{"name":"Kanban Card Number","dataType":"string"},{"name":"Lot Number","dataType":"string"},{"name":"Sales Order DFF","dataType":"double"},{"name":"Sales Order Line DFF","dataType":"double"},{"name":"Service Request DFF","dataType":"string"},{"name":"Assembly Serial Number DFF","dataType":"string"},{"name":"Released Date","dataType":"dateTime"},{"name":"Completed Date","dataType":"dateTime"},{"name":"Closed Date","dataType":"dateTime"},{"name":"Demand Class","dataType":"string"},{"name":"Completion Subinventory","dataType":"string"},{"name":"Completion Locator","dataType":"string"},{"name":"Created By","dataType":"string"},{"name":"Last Updated By","dataType":"string"},{"name":"Class Code CS","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-12T23:00:17.3157621+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/28b505b1-8f44-44bd-9f88-beeb9307f1b0/WIP_Job_TBU.csv?snapshot=2022-06-12T23%3A00%3A17.2885869Z"}]},{"$type":"LocalEntity","name":"WIP_Value_TBU","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"WIP_Value_TBU.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Local Extract Date","dataType":"dateTime"},{"name":"Job Number","dataType":"string"},{"name":"WIP_ENTITY_ID","dataType":"double"},{"name":"Organization Code","dataType":"string"},{"name":"Period Name","dataType":"string"},{"name":"ACCT_PERIOD_ID","dataType":"double"},{"name":"Period Start Date","dataType":"dateTime"},{"name":"TL Material Output","dataType":"double"},{"name":"TL Material Variance","dataType":"double"},{"name":"TL Material Overhead Output","dataType":"double"},{"name":"TL Material Overhead Variance","dataType":"double"},{"name":"TL Resource Input","dataType":"double"},{"name":"TL Resource Output","dataType":"double"},{"name":"TL Resource Variance","dataType":"double"},{"name":"TL OSP Input","dataType":"double"},{"name":"TL OSP Output","dataType":"double"},{"name":"TL OSP Variance","dataType":"double"},{"name":"TL Overhead Input","dataType":"double"},{"name":"TL Overhead Output","dataType":"double"},{"name":"TL Overhead Variance","dataType":"double"},{"name":"PL Material Input","dataType":"double"},{"name":"PL Material Output","dataType":"double"},{"name":"PL Material Variance","dataType":"double"},{"name":"PL Material Overhead Input","dataType":"double"},{"name":"PL Material Overhead Output","dataType":"double"},{"name":"PL Material Overhead Variance","dataType":"double"},{"name":"PL Resource Input","dataType":"double"},{"name":"PL Resource Output","dataType":"double"},{"name":"PL Resource Variance","dataType":"double"},{"name":"PL OSP Variance","dataType":"double"},{"name":"PL OSP Input","dataType":"double"},{"name":"PL OSP Output","dataType":"double"},{"name":"PL Overhead Input","dataType":"double"},{"name":"PL Overhead Output","dataType":"double"},{"name":"PL Overhead Variance","dataType":"double"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-12T23:00:49.5966009+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/28b505b1-8f44-44bd-9f88-beeb9307f1b0/WIP_Value_TBU.csv?snapshot=2022-06-12T23%3A00%3A49.5652293Z"}]},{"$type":"LocalEntity","name":"Resource_Transaction","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Resource_Transaction.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Local Extract Date","dataType":"dateTime"},{"name":"Organization Code","dataType":"string"},{"name":"WIP Job","dataType":"string"},{"name":"WIP Job Description","dataType":"string"},{"name":"Discrete Job Flag","dataType":"string"},{"name":"Item Number","dataType":"string"},{"name":"Item Description","dataType":"string"},{"name":"Resource Transaction Reference","dataType":"string"},{"name":"TRANSACTION_ID","dataType":"double"},{"name":"Transaction Type","dataType":"string"},{"name":"Transaction Date","dataType":"dateTime"},{"name":"Source Code","dataType":"string"},{"name":"Operation Sequence","dataType":"double"},{"name":"Resource Sequence","dataType":"double"},{"name":"Autocharge Type","dataType":"string"},{"name":"Usage Rate or Amount","dataType":"double"},{"name":"Basis Type","dataType":"string"},{"name":"Transaction Quantity","dataType":"double"},{"name":"Transaction UOM","dataType":"string"},{"name":"Primary Quantity","dataType":"double"},{"name":"Primary UOM","dataType":"string"},{"name":"Actual Resource Rate","dataType":"double"},{"name":"Standard Resource Rate","dataType":"double"},{"name":"Standard Rate Flag","dataType":"string"},{"name":"Currency Code","dataType":"string"},{"name":"Period Name","dataType":"string"},{"name":"Activity Name","dataType":"string"},{"name":"ATTRIBUTE_CATEGORY","dataType":"string"},{"name":"ATTRIBUTE1","dataType":"string"},{"name":"ATTRIBUTE2","dataType":"string"},{"name":"ORGANIZATION_ID","dataType":"double"},{"name":"WIP_ENTITY_ID","dataType":"double"},{"name":"LINE_ID","dataType":"double"},{"name":"PRIMARY_ITEM_ID","dataType":"double"},{"name":"ACCT_PERIOD_ID","dataType":"double"},{"name":"DEPARTMENT_ID","dataType":"double"},{"name":"RESOURCE_ID","dataType":"double"},{"name":"EMPLOYEE_ID","dataType":"double"},{"name":"ACTIVITY_ID","dataType":"double"},{"name":"REASON_ID","dataType":"double"},{"name":"MOVE_TRANSACTION_ID","dataType":"double"},{"name":"COMPLETION_TRANSACTION_ID","dataType":"double"},{"name":"PROJECT_ID","dataType":"double"},{"name":"TASK_ID","dataType":"double"},{"name":"SOURCE_LINE_ID","dataType":"double"},{"name":"Creation Date","dataType":"dateTime"},{"name":"Created By","dataType":"double"},{"name":"LAST_UPDATE_DATE","dataType":"dateTime"},{"name":"LAST_UPDATED_BY","dataType":"double"},{"name":"Project Name","dataType":"string"},{"name":"Project Number","dataType":"string"},{"name":"Department Code","dataType":"string"},{"name":"Resource Code","dataType":"string"},{"name":"Move Primary Quantity","dataType":"double"},{"name":"From Operation Sequence","dataType":"double"},{"name":"To Operation Sequence","dataType":"double"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-12T23:02:13.9674514+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/28b505b1-8f44-44bd-9f88-beeb9307f1b0/Resource_Transaction.csv?snapshot=2022-06-12T23%3A02%3A13.9406488Z"}]}]}