{"name":"COHREP_SITE_FIN_TRX1","description":"","version":"1.0","culture":"en-US","modifiedTime":"2021-03-22T09:10:36.504404+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":true,"queriesMetadata":{"M2_Entity":{"queryId":"f3de4b4a-c476-4164-8325-a0f304985397","queryName":"M2_Entity","loadEnabled":true},"EO_Reserve":{"queryId":"c2e5f177-6b54-4f1e-9213-a3814be9a120","queryName":"EO_Reserve","loadEnabled":true},"GL_Reserve":{"queryId":"1d734206-b8be-407a-9f27-7bb5a0eae266","queryName":"GL_Reserve","loadEnabled":true},"Corporate_FX_Rate":{"queryId":"a34902c2-e76f-4414-822c-bf81fb871b14","queryName":"Corporate_FX_Rate","loadEnabled":true},"Inventory_Value":{"queryId":"1bbd36fb-c9db-4c9e-9b0a-fa3e6b0b13b3","queryName":"Inventory_Value","loadEnabled":true},"ENTITY":{"queryId":"d9e62998-bb9a-4273-a938-64b38a390010","queryName":"ENTITY"},"ORG":{"queryId":"91d6550d-71d2-4953-beb3-0356ffff30bf","queryName":"ORG"},"YearOffset":{"queryId":"fffb62b1-1dc1-428b-bbc9-48a181a11f9f","queryName":"YearOffset"},"LocalTZ":{"queryId":"d9128f8d-1e1f-43a7-bfe5-604248bd1fa8","queryName":"LocalTZ"}},"document":"section Section1;\r\nshared M2_Entity = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, \n  Query=\"\n  SELECT\n    sysdate extract_date,\n    from_tz(cast (sysdate as timestamp),'PST') at time zone '\"&LocalTZ&\"' local_extract_date,\n    entity,\n    dept,\n    acct,\n    proj,\n    interco,\n    gl_period,\n    tb.period_year fiscal_year,\n    gp.end_date period_end_date,\n    item_number,\n    item_description,\n    cat_segment1,\n    cat_segment2,\n    cat_segment3,\n    transaction_source,\n    tb.inventory_item_id,\n    tb.organization_id,\n    vendor_id,\n    sales_service_code,\n    currency_code,\n    conversion_rate,\n    SUM(accounted_net)         accounted_net,\n    SUM(accounted_net_usd)     accounted_net_usd,\n    SUM(tran_qty)              transaction_quantity,\n    m20_tbu,\n    m20_pfc,\n    allocation_percent,\n    hfm_account,\n    hp_account,\n    hfm_icp,\n    hfm_function,\n    hfm_product,\n    hp_product,\n    hfm_product_group,\n    hp_spc_account,\n    alt_hfm_product,\n    alt_hfm_product_group,\n    alt_hp_product\nFROM\n    xxcoh.xxcoh_m2_report_tb tb,\n    gl.gl_periods gp\nWHERE\n    entity = '\"&ENTITY&\"'\n    AND tb.GL_PERIOD = gp.period_name\n    AND PERIOD_SET_NAME = 'COHR Calendar'\n    AND tb.period_year >= (\n        SELECT\n            period_year - \"&YearOffset&\"\n        FROM\n            gl.gl_periods gp\n        WHERE\n            trunc(sysdate) BETWEEN gp.start_date AND gp.end_date\n            AND period_set_name = 'COHR Calendar'\n    )\nGROUP BY\n    entity,\n    dept,\n    acct,\n    proj,\n    interco,\n    tbd,\n    gl_period,\n    tb.period_year,\n    gp.end_date,\n    item_number,\n    item_description,\n    cat_segment1,\n    cat_segment2,\n    cat_segment3,\n    transaction_source,\n    currency_code,\n    tb.inventory_item_id,\n    tb.organization_id,\n    set_of_books_id,\n    vendor_id,\n    sales_service_code,\n    conversion_rate,\n    m20_tbu,\n    m20_pfc,\n    allocation_percent,\n    hfm_account,\n    hp_account,\n    hfm_icp,\n    hfm_function,\n    hfm_product,\n    hp_product,\n    hfm_product_group,\n    hp_spc_account,\n    alt_hfm_product,\n    alt_hfm_product_group,\n    alt_hp_product\n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"ENTITY\", \"Entity\"}, {\"DEPT\", \"Department\"}, {\"ACCT\", \"Account\"}, {\"PROJ\", \"Project\"}, {\"INTERCO\", \"Inter Company\"}, {\"ITEM_NUMBER\", \"Item Number\"}, {\"ITEM_DESCRIPTION\", \"Description\"}, {\"TRANSACTION_QUANTITY\", \"Transaction Quantity\"}, {\"TRANSACTION_SOURCE\", \"Transaction Source\"}, {\"CURRENCY_CODE\", \"Currency\"}, {\"SALES_SERVICE_CODE\", \"Sales Service Code\"}, {\"ACCOUNTED_NET\", \"Accounted Net\"}, {\"ACCOUNTED_NET_USD\", \"Accounted Net USD\"}, {\"GL_PERIOD\", \"GL Period\"}, {\"PERIOD_END_DATE\", \"Period End Date\"}, {\"M20_TBU\", \"M20 TBU\"}, {\"M20_PFC\", \"M20 PFC\"}, {\"ALLOCATION_PERCENT\", \"Allocation Percent\"}, {\"HFM_ACCOUNT\", \"HFM Account\"}, {\"HP_ACCOUNT\", \"HP Account\"}, {\"HFM_ICP\", \"HFM ICP\"}, {\"HFM_FUNCTION\", \"HFM Function\"}, {\"HFM_PRODUCT\", \"HFM Product\"}, {\"HP_PRODUCT\", \"HP Product\"}, {\"HFM_PRODUCT_GROUP\", \"HFM Product Group\"}, {\"HP_SPC_ACCOUNT\", \"HP SPC Account\"}, {\"CAT_SEGMENT1\", \"Item TBU\"}, {\"CAT_SEGMENT2\", \"Item Product Family\"}, {\"CAT_SEGMENT3\", \"Item Product Line\"}, {\"ALT_HFM_PRODUCT\", \"Alternate HFM Product\"}, {\"ALT_HFM_PRODUCT_GROUP\", \"Alternate HFM Product Group\"}, {\"ALT_HP_PRODUCT\", \"Alternate HP Product\"}, {\"FISCAL_YEAR\", \"Fiscal Year\"}, {\"EXTRACT_DATE\", \"Extract Date\"}, {\"LOCAL_EXTRACT_DATE\", \"Local Extract Date\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared EO_Reserve = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, Query=\"\n  SELECT\n  sysdate extract_date,\n    from_tz(cast (sysdate as timestamp),'PST') at time zone '\"&LocalTZ&\"' local_extract_date,\n   XRH.HEADER_STATUS,\n   XRH.PLAN_NAME,\n   XRL.*\nFROM\n   APPS.XXCOH_RSV_HEADERS XRH,\n   APPS.XXCOH_RSV_LINES XRL \nWHERE\n   1 = 1 \n   AND XRH.RESERVE_HEADER_ID = XRL.RESERVE_HEADER_ID \n   AND XRH.ORGANIZATION_CODE = '\"&ORG&\"'\n   \"\n   , CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"HEADER_STATUS\", \"Header Status\"}, {\"PERIOD_NAME\", \"GL Period Name\"}, {\"PLAN_NAME\", \"Plan Name\"}, {\"RESERVE_PERIOD\", \"Reserve Period\"}, {\"RESERVE_TYPE\", \"Reserve Type\"}, {\"ORGANIZATION_CODE\", \"Organization Code\"}, {\"LINE_STATUS\", \"Line Status\"}, {\"ITEM_NUMBER\", \"Item Number\"}, {\"ITEM_DESCRIPTION\", \"Item Description\"}, {\"SYSTEM_RESERVE_QUANTITY\", \"System Reserve Quantity\"}, {\"SYSTEM_RESERVE_EXT_VALUE\", \"System Reserve Ext Value\"}, {\"SYSTEM_RESERVE_TRF_EXT_VALUE\", \"System Reserve Trf Ext Value\"}, {\"SYSTEM_RESERVE_CATEGORY\", \"System Reserve Category\"}, {\"SYSTEM_RESERVE_RATE\", \"System Reserve Rate\"}, {\"SYSTEM_RESERVE_AMOUNT\", \"System Reserve Amount\"}, {\"SYSTEM_RESERVE_TRF_AMOUNT\", \"System Reserve Trf Amount\"}, {\"SYSTEM_RESERVE_COMMENT\", \"System Reserve Comment\"}, {\"REVIEW1_RESERVE_QUANTITY\", \"Review1 Reserve Quantity\"}, {\"REVIEW1_RESERVE_EXT_VALUE\", \"Review1 Reserve Ext Value\"}, {\"REVIEW1_RESERVE_TRF_EXT_VALUE\", \"Review1 Reserve Trf Ext Value\"}, {\"REVIEW1_RESERVE_CATEGORY\", \"Review1 Reserve Category\"}, {\"REVIEW1_RESERVE_RATE\", \"Review1 Reserve Rate\"}, {\"REVIEW1_RESERVE_AMOUNT\", \"Review1 Reserve Amount\"}, {\"REVIEW1_RESERVE_TRF_AMOUNT\", \"Review1 Reserve Trf Amount\"}, {\"REVIEW1_OVERRIDE_REASON\", \"Review1 Override Reason\"}, {\"REVIEW1_COMMENT\", \"Review1 Comment\"}, {\"REVIEW2_RESERVE_QUANTITY\", \"Review2 Reserve Quantity\"}, {\"REVIEW2_RESERVE_EXT_VALUE\", \"Review2 Reserve Ext Value\"}, {\"REVIEW2_RESERVE_TRF_EXT_VALUE\", \"Review2 Reserve Trf Ext Value\"}, {\"REVIEW2_RESERVE_CATEGORY\", \"Review2 Reserve Category\"}, {\"REVIEW2_RESERVE_RATE\", \"Review2 Reserve Rate\"}, {\"REVIEW2_RESERVE_AMOUNT\", \"Review2 Reserve Amount\"}, {\"REVIEW2_RESERVE_TRF_AMOUNT\", \"Review2 Reserve Trf Amount\"}, {\"REVIEW2_OVERRIDE_REASON\", \"Review2 Override Reason\"}, {\"REVIEW2_COMMENT\", \"Review2 Comment\"}, {\"FINAL_RESERVE_QUANTITY\", \"Final Reserve Quantity\"}, {\"FINAL_RESERVE_EXT_VALUE\", \"Final Reserve Ext Value\"}, {\"FINAL_RESERVE_TRF_EXT_VALUE\", \"Final Reserve Trf Ext Value\"}, {\"FINAL_RESERVE_CATEGORY\", \"Final Reserve Category\"}, {\"FINAL_RESERVE_RATE\", \"Final Reserve Rate\"}, {\"FINAL_RESERVE_AMOUNT\", \"Final Reserve Amount\"}, {\"FINAL_RESERVE_TRF_AMOUNT\", \"Final Reserve Trf Amount\"}, {\"FINAL_RESERVE_AMOUNT_USD\", \"Final Reserve Amount Usd\"}, {\"FINAL_TAKEN_FROM\", \"Final Taken From\"}, {\"FINAL_FINANCE_APPROVE_DATE\", \"Final Finance Approve Date\"}, {\"REVIEW1_USER\", \"Review1 User\"}, {\"REVIEW1_DATE\", \"Review1 Date\"}, {\"REVIEW2_USER\", \"Review2 User\"}, {\"REVIEW2_DATE\", \"Review2 Date\"}, {\"REVIEW3_USER\", \"Review3 User\"}, {\"REVIEW3_DATE\", \"Review3 Date\"}, {\"OPERATING_UNIT\", \"Operating Unit\"}, {\"LEDGER_SHORT_NAME\", \"Ledger Short Name\"}, {\"CURRENCY_CODE\", \"Currency Code\"}, {\"ORGANIZATION_CATEGORY\", \"Organization Category\"}, {\"RESERVE_ENTITY\", \"Reserve Entity\"}, {\"RESERVE_DEPARTMENT\", \"Reserve Department\"}, {\"RESERVE_ACCOUNT\", \"Reserve Account\"}, {\"RESERVE_IC\", \"Reserve IC\"}, {\"TBU\", \"TBU\"}, {\"PRODUCT_FAMILY\", \"Product Family\"}, {\"PRODUCT_LINE\", \"Product Line\"}, {\"ORG_TBU\", \"Org TBU\"}, {\"ORG_PRODUCT_FAMILY\", \"Org Product Family\"}, {\"ORG_PRODUCT_LINE\", \"Org Product Line\"}, {\"FIN_TBU\", \"Fin TBU\"}, {\"FIN_PRODUCT_FAMILY\", \"Fin Product Family\"}, {\"PLANNER_CODE\", \"Planner Code\"}, {\"GREEN_SUPPLY_STATUS\", \"Green Supply Status\"}, {\"ASSET_FLAG\", \"Asset Flag\"}, {\"NETTABLE_FLAG\", \"Nettable Flag\"}, {\"MAKE_BUY\", \"Make Buy\"}, {\"SERVICE_LEAD_TIME\", \"Service Lead Time\"}, {\"DATE_LAST_ACTIVITY\", \"Date Last Activity\"}, {\"LOT_SIZE\", \"Lot Size\"}, {\"ITEM_COST_STANDARD\", \"Item Cost Standard\"}, {\"ITEM_TRF_COST\", \"Item Trf Cost\"}, {\"ITEM_PRICE\", \"Item Price\"}, {\"CLASS_CODE\", \"Class Code\"}, {\"ACCT_CLASS_TYPE\", \"Acct Class Type\"}, {\"ITEM_TYPE\", \"Item Type\"}, {\"ITEM_STATUS_CODE\", \"Item Status Code\"}, {\"ABC_CLASS_CODE\", \"Abc Class Code\"}, {\"SUBINVENTORY\", \"Subinventory\"}, {\"LOT_NUMBER\", \"Lot Number\"}, {\"SITE_CODE\", \"Site Code\"}, {\"CONTROL_ORG_CODE\", \"Control Org Code\"}, {\"LOC_SUB\", \"Loc Sub\"}, {\"LOC_ROW\", \"Loc Row\"}, {\"LOC_RACK\", \"Loc Rack\"}, {\"LOC_SHELF\", \"Loc Shelf\"}, {\"LOC_BIN\", \"Loc Bin\"}, {\"NETTABLE_OH_QUANTITY\", \"Nettable Onhand Quantity\"}, {\"NONNETTABLE_OH_QUANTITY\", \"Non Nettable Onhand Quantity\"}, {\"NETTABLE_RCV_QUANTITY\", \"Nettable RCV Quantity\"}, {\"NONNETTABLE_RCV_QUANTITY\", \"Non Nettable RCV Quantity\"}, {\"NETTABLE_ITRN_QUANTITY\", \"Nettable ITRN Quantity\"}, {\"NONNETTABLE_ITRN_QUANTITY\", \"Non Nettable ITRN Quantity\"}, {\"WIP_REMAINING_QUANTITY\", \"WIP Remaining Quantity\"}, {\"TOT_NETTABLE_QUANTITY\", \"Total Nettable Quantity\"}, {\"TOT_NONNETTABLE_QUANTITY\", \"Total Non Nettable Quantity\"}, {\"TOT_RESULTING_QUANTITY\", \"Total Resulting Quantity\"}, {\"TOT_NETTABLE_EXT_VALUE\", \"Total Nettable Ext Value\"}, {\"TOT_NONNETTABLE_EXT_VALUE\", \"Total Non Nettable Ext Value\"}, {\"TOT_ONHAND_EXT_VALUE\", \"Total Onhand Ext Value\"}, {\"TOT_RECEIVING_EXT_VALUE\", \"Total Receiving Ext Value\"}, {\"TOT_INTRANSIT_EXT_VALUE\", \"Total Intransit Ext Value\"}, {\"DEMAND_0_03\", \"Demand 0-03\"}, {\"DEMAND_0_12\", \"Demand 0-12\"}, {\"DEMAND_0_18\", \"Demand 0-18\"}, {\"DEMAND_0_24\", \"Demand 0-24\"}, {\"DEMAND_SUBSTITUTE\", \"Demand Substitute\"}, {\"USAGE_0_03\", \"Usage 0-03\"}, {\"USAGE_0_12\", \"Usage 0-12\"}, {\"USAGE_0_18\", \"Usage 0-18\"}, {\"USAGE_0_24\", \"Usage 0-24\"}, {\"USAGE_13_24\", \"Usage 13-24\"}, {\"USAGE_SUBSTITUTE\", \"Usage Substitute\"}, {\"OPEN_ORDER_0_03\", \"Open Order 0-03\"}, {\"OPEN_ORDER_0_12\", \"Open Order 0-12\"}, {\"OPEN_ORDER_0_18\", \"Open Order 0-18\"}, {\"OPEN_ORDER_0_24\", \"Open Order 0-24\"}, {\"OPEN_ORDER_SUBSTITUTE\", \"Open Order Substitute\"}, {\"RESULTING_QUANTITY_LEFTOVER\", \"Resulting Quantity Leftover\"}, {\"WIP_ENTITY_NAME\", \"WIP Entity Name\"}, {\"WIP_JOB_TYPE\", \"WIP Job Type\"}, {\"WIP_JOB_STATUS\", \"WIP Job Status\"}, {\"WIP_DATE_RELEASED\", \"WIP Date Released\"}, {\"WIP_TOTAL_COSTS_INCURRED\", \"WIP Total Costs Incurred\"}, {\"WIP_TOTAL_COSTS_RELIEVED\", \"WIP Total Costs Relieved\"}, {\"WIP_TOTAL_VARIANCES_RELIEVED\", \"WIP Total Variances Relieved\"}, {\"WIP_TOTAL_NET_ACTIVITIES\", \"WIP Total Net Activities\"}, {\"WIP_DAYS_RELEASED\", \"WIP Days Released\"}, {\"WIP_MONTHS_RELEASED\", \"WIP Months Released\"}, {\"WIP_AGING_BUCKET\", \"WIP Aging Bucket\"}, {\"SERIAL_NUM_CONTROL_CODE\", \"Serial Number Control Code\"}, {\"SERIAL_NUMBER\", \"Serial Number\"}, {\"SERIAL_NUMBER_OVERRIDE\", \"Serial Number Override\"}, {\"SERIAL_NUMBER_FINAL\", \"Serial Number Final\"}, {\"SERIAL_NUMBER_HISTORY\", \"Serial Number History\"}, {\"SERIAL_NUM_STATUS\", \"Serial Number Status\"}, {\"LC_QUANTITY\", \"LC Quantity\"}, {\"LC_EARLIEST_TRX_DATE\", \"LC Earliest Trx Date\"}, {\"LC_LATEST_STOCK_DATE\", \"LC Latest Stock Date\"}, {\"LC_START_DATE\", \"LC Start Date\"}, {\"LC_START_DATE_OVERRIDE\", \"LC Start Date Override\"}, {\"LC_START_DATE_FINAL\", \"LC Start Date Final\"}, {\"LC_LOCATION_STATUS\", \"LC Location Status\"}, {\"LC_PERIOD_RESERVE_AMOUNT\", \"LC Period Reserve Amount\"}, {\"LC_CURRENT_RESERVE_AMOUNT\", \"LC Current Reserve Amount\"}, {\"PERIOD_YEAR\", \"Period Year\"}, {\"PERIOD_QUARTER\", \"Period Quarter\"}, {\"PERIOD_NUM\", \"Period Num\"}, {\"LC_PERIOD_COUNT\", \"LC Period Count\"}, {\"LC_DAYS_COUNT\", \"LC Days Count\"}, {\"LC_STATUS\", \"LC Status\"}, {\"CREATION_DATE\", \"Creation Date\"}, {\"CREATED_BY\", \"Created By\"}, {\"LAST_UPDATE_DATE\", \"Last Update Date\"}, {\"LAST_UPDATED_BY\", \"Last Updated By\"}, {\"QUANTITY1\", \"Quantity1\"}, {\"QUANTITY2\", \"Quantity2\"}, {\"QUANTITY3\", \"Quantity3\"}, {\"QUANTITY4\", \"Quantity4\"}, {\"QUANTITY5\", \"Quantity5\"}, {\"DEMAND1\", \"Demand1\"}, {\"DEMAND2\", \"Demand2\"}, {\"DEMAND3\", \"Demand3\"}, {\"DEMAND4\", \"Demand4\"}, {\"DEMAND5\", \"Demand5\"}, {\"USAGE1\", \"Usage1\"}, {\"USAGE2\", \"Usage2\"}, {\"USAGE3\", \"Usage3\"}, {\"USAGE4\", \"Usage4\"}, {\"USAGE5\", \"Usage5\"}, {\"OPEN_ORDER1\", \"Open Order1\"}, {\"OPEN_ORDER2\", \"Open Order2\"}, {\"OPEN_ORDER3\", \"Open Order3\"}, {\"OPEN_ORDER4\", \"Open Order4\"}, {\"OPEN_ORDER5\", \"Open Order5\"}, {\"TOTAL1\", \"Total1\"}, {\"TOTAL2\", \"Total2\"}, {\"TOTAL3\", \"Total3\"}, {\"TOTAL4\", \"Total4\"}, {\"TOTAL5\", \"Total5\"}, {\"DATE1\", \"Date1\"}, {\"DATE2\", \"Date2\"}, {\"DATE3\", \"Date3\"}, {\"DATE4\", \"Date4\"}, {\"DATE5\", \"Date5\"}, {\"LOCATION1\", \"Location1\"}, {\"LOCATION2\", \"Location2\"}, {\"LOCATION3\", \"Location3\"}, {\"LOCATION4\", \"Location4\"}, {\"LOCATION5\", \"Location5\"}, {\"PRIOR_RESERVE_QUANTITY\", \"Prior Reserve Quantity\"}, {\"PRIOR_RESERVE_EXT_VALUE\", \"Prior Reserve Ext Value\"}, {\"PRIOR_RESERVE_TRF_EXT_VALUE\", \"Prior Reserve Trf Ext Value\"}, {\"PRIOR_RESERVE_CATEGORY\", \"Prior Reserve Category\"}, {\"PRIOR_RESERVE_RATE\", \"Prior Reserve Rate\"}, {\"PRIOR_RESERVE_AMOUNT\", \"Prior Reserve Amount\"}, {\"PRIOR_RESERVE_TRF_AMOUNT\", \"Prior Reserve Trf Amount\"}, {\"PRIOR_RESERVE_AMOUNT_USD\", \"Prior Reserve Amount Usd\"}, {\"PRIOR_OH_QUANTITY\", \"Prior Onhand Quantity\"}, {\"PRIOR_COMMENT\", \"Prior Comment\"}, {\"FORECAST\", \"Forecast\"}, {\"ORG_FORECAST\", \"Org Forecast\"}, {\"FIN_FORECAST\", \"Fin Forecast\"}, {\"PRIOR_OVERRIDE_REASON\", \"Prior Override Reason\"}, {\"SYSTEM_RESERVE_AMOUNT_USD\", \"System Reserve Amount Usd\"}, {\"USER_DEFINED_1\", \"User Defined 1\"}, {\"USER_DEFINED_2\", \"User Defined 2\"}, {\"USER_DEFINED_3\", \"User Defined 3\"}, {\"USER_DEFINED_4\", \"User Defined 4\"}, {\"OPS_REPORTING\", \"Ops Reporting\"}, {\"SEC_REPORTING\", \"SEC Reporting\"}, {\"OPEN_PO_0_12\", \"Open PO 0-12\"}, {\"OPEN_PO_0_24\", \"Open PO 0-24\"}, {\"EXTRACT_DATE\", \"Extract Date\"}, {\"LOCAL_EXTRACT_DATE\", \"Local Extract Date\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared GL_Reserve = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, Query=\"\n  SELECT\n   sysdate EXTRACT_DATE,\n    from_tz(cast (sysdate as timestamp),'PST') at time zone '\"&LocalTZ&\"' local_extract_date,\n   GJH.JE_HEADER_ID,\n   GCC.SEGMENT1,\n   GCC.SEGMENT2,\n   GCC.SEGMENT3,\n   GCC.SEGMENT4,\n   GCC.SEGMENT5,\n   GCC.CODE_COMBINATION_ID,\n   GJH.LEDGER_ID,\n   GJH.JE_CATEGORY,\n   GJH.JE_SOURCE,\n   GJH.CURRENCY_CODE,\n   GJH.POSTED_DATE,\n   GJL.EFFECTIVE_DATE,\n   GJL.PERIOD_NAME,\n   GJL.ACCOUNTED_DR,\n   GJL.ACCOUNTED_CR,\n   nvl(GJL.ACCOUNTED_DR,0) - nvl(GJL.ACCOUNTED_CR,0) ACCOUNTED_NET,\n   GJL.DESCRIPTION,\n   GJL.ATTRIBUTE1,\n   GJL.ATTRIBUTE2,\n   GJL.ATTRIBUTE3,\n   GJL.ATTRIBUTE4\nFROM\n   APPS.GL_CODE_COMBINATIONS GCC,\n   APPS.GL_PERIOD_STATUSES GPS,\n   APPS.GL_LEDGERS GL,\n   APPS.GL_JE_LINES GJL,\n   APPS.GL_JE_HEADERS GJH,\n   APPS.ORG_ORGANIZATION_DEFINITIONS OOD \nWHERE\n   ORGANIZATION_CODE =  '\"&ORG&\"' \n   AND OOD.SET_OF_BOOKS_ID = GL.LEDGER_ID \n   AND GL.LEDGER_ID = GJH.LEDGER_ID \n   AND GPS.LEDGER_ID = 1 \n   AND GPS.APPLICATION_ID = 101 \n   AND GJH.STATUS = 'P' \n   AND GJH.JE_HEADER_ID = GJL.JE_HEADER_ID \n   AND GJL.CODE_COMBINATION_ID = GCC.CODE_COMBINATION_ID \n   AND GCC.SEGMENT1 = '\"&ENTITY&\"' \n   AND GCC.SEGMENT3 in ( \n    '05500',\n    '05505',\n    '05510',\n    '05540',\n    '05530',\n    '05550')\n   \"\n   , CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"EXTRACT_DATE\", \"Extract Date\"}, {\"JE_CATEGORY\", \"JE Category\"}, {\"JE_SOURCE\", \"JE Source\"}, {\"CURRENCY_CODE\", \"Currency Code\"}, {\"POSTED_DATE\", \"Posted Date\"}, {\"EFFECTIVE_DATE\", \"Effective Date\"}, {\"PERIOD_NAME\", \"GL Period Name\"}, {\"ACCOUNTED_DR\", \"Accounted Dr\"}, {\"ACCOUNTED_CR\", \"Accounted Cr\"}, {\"ACCOUNTED_NET\", \"Accounted Net\"}, {\"DESCRIPTION\", \"JE Description\"}, {\"SEGMENT1\", \"Entity\"}, {\"SEGMENT2\", \"Department\"}, {\"SEGMENT3\", \"Account\"}, {\"SEGMENT4\", \"Project\"}, {\"SEGMENT5\", \"Intercompany\"}, {\"LOCAL_EXTRACT_DATE\", \"Local Extract Date\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Corporate_FX_Rate = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, \n  Query=\"\n SELECT\n sysdate extract_date,\n    from_tz(cast (sysdate as timestamp),'PST') at time zone '\"&LocalTZ&\"' local_extract_date,\n    from_currency,\n    to_currency,\n    gdr.conversion_date,\n    gdr.conversion_type,\n    gdr.conversion_Rate usd_rate,\n    CASE\n        WHEN sob.currency_code = from_currency THEN\n            'Yes'\n        ELSE\n            'No'\n    END from_base_currency\nFROM\n    apps.gl_daily_rates_v                gdr,\n    apps.org_organization_definitions    ood,\n    apps.gl_sets_of_books                sob\nWHERE\n        conversion_type = 'Corporate'\n    AND to_currency = 'USD'\n    AND ood.set_of_books_id = sob.set_of_books_id\n    AND ood.organization_code = '\"&ORG&\"'\n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"FROM_CURRENCY\", \"From Currency\"}, {\"TO_CURRENCY\", \"To Currency\"}, {\"CONVERSION_DATE\", \"Conversion Date\"}, {\"CONVERSION_TYPE\", \"Conversion Type\"}, {\"USD_RATE\", \"USD Rate\"}, {\"FROM_BASE_CURRENCY\", \"From Base Currency Flag\"}, {\"EXTRACT_DATE\", \"Extract Date\"}, {\"LOCAL_EXTRACT_DATE\", \"Local Extract Date\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Inventory_Value = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, \n  Query=\"\n  SELECT\n    sysdate extract_date,\n    from_tz(cast (sysdate as timestamp),'PST') at time zone '\"&LocalTZ&\"' local_extract_date,\n    invv.gl_period,\n    invv.inventory_item_id,\n    invv.item_number,\n    invv.item_desc,\n    nvl(invv.org_category_id, invv.category_id)            key_category_id,\n    invv.item_tbu,\n    invv.item_product_family,\n    invv.source_type,\n    invv.item_cost,\n    invv.cost_incurred,\n    invv.cost_relieved,\n    invv.cost_variance,\n    invv.je_source_category,\n    invv.operations_reporting,\n    invv.cs_demand_source,\n    invv.cs_supply_source,\n    invv.exclude_flag,\n    invv.exclude_comment,\n    invv.wip_class,\n    invv.wip_class_code,\n    invv.item_type,\n    invv.planner_code,\n    substr(invv.abc_class, 1, 1)                          abc_class,\n    invv.item_status,\n    invv.inv_status,\n    invv.subinventory_code,\n    invv.account,\n    invv.inv_quantity,\n    invv.inv_value,\n    invv.inv_value_usd,\n    invv.fiscal_period_id,\n    invv.fiscal_week_id,\n    invv.fiscal_week,\n    (invv.fiscal_year * 100 + to_number(substr(fiscal_week,-2)) )        week_series,\n    invv.scenario,\n    invv.fiscal_month,\n    invv.material_cost,\n    invv.material_overhead_cost,\n    invv.outside_processing_cost,\n    invv.overhead_cost,\n    invv.resource_cost,\n    invv.wip_job_id,\n    invv.wip_job_no,\n    round(invv.currency_rate, 4)                          usd_rate,\n    invv.fin_product_group,\n    invv.fin_product_family,\n    invv.fin_forecast_field,\n    invv.fin_product_segment,\n    invv.fin_product_line,\n    invv.creation_date\nFROM\n   XXFACTS.XX_INVVALUE_FACT INVV,\n   APPS.MTL_PARAMETERS MP\nWHERE\n   MP.ORGANIZATION_ID = INVV.INV_ORG_ID \n   AND MP.ORGANIZATION_CODE = '\"&ORG&\"'\n   AND INVV.FISCAL_YEAR >= (\n        SELECT\n            period_year - \"&YearOffset&\"\n        FROM\n            gl.gl_periods gp\n        WHERE\n            trunc(sysdate) BETWEEN gp.start_date AND gp.end_date\n            AND period_set_name = 'COHR Calendar'\n    )\n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"GL_PERIOD\", \"Period Name\"}, {\"ITEM_NUMBER\", \"Item Number\"}, {\"ITEM_DESC\", \"Item Description\"}, {\"ITEM_TBU\", \"Item TBU\"}, {\"ITEM_PRODUCT_FAMILY\", \"Item Product Family\"}, {\"SOURCE_TYPE\", \"Value Source\"}, {\"ITEM_COST\", \"Item Cost\"}, {\"COST_INCURRED\", \"Cost Incurred\"}, {\"COST_RELIEVED\", \"Cost Relieved\"}, {\"COST_VARIANCE\", \"Cost Variance\"}, {\"JE_SOURCE_CATEGORY\", \"JE Source Category\"}, {\"OPERATIONS_REPORTING\", \"Operations Reporting\"}, {\"CS_DEMAND_SOURCE\", \"Demand Source\"}, {\"CS_SUPPLY_SOURCE\", \"Supply Source\"}, {\"EXCLUDE_FLAG\", \"Exclude Flag\"}, {\"EXCLUDE_COMMENT\", \"Exclude Comment\"}, {\"WIP_CLASS\", \"WIP Class\"}, {\"WIP_CLASS_CODE\", \"WIP Class Code\"}, {\"ITEM_TYPE\", \"Item Type\"}, {\"PLANNER_CODE\", \"Planner Code\"}, {\"ABC_CLASS\", \"ABC Class\"}, {\"ITEM_STATUS\", \"Item Status\"}, {\"INV_STATUS\", \"Supply Chain Status\"}, {\"SUBINVENTORY_CODE\", \"Subinventory\"}, {\"ACCOUNT\", \"Account Code\"}, {\"INV_QUANTITY\", \"Inventory Quantity\"}, {\"INV_VALUE\", \"Inventory Value\"}, {\"INV_VALUE_USD\", \"Inventory Value USD\"}, {\"WIP_JOB_NO\", \"WIP Job Number\"}, {\"SCENARIO\", \"Scenario\"}, {\"MATERIAL_COST\", \"Material Cost\"}, {\"MATERIAL_OVERHEAD_COST\", \"Material Overhead Cost\"}, {\"OUTSIDE_PROCESSING_COST\", \"OSP Cost\"}, {\"RESOURCE_COST\", \"Resource Cost\"}, {\"OVERHEAD_COST\", \"Overhead Cost\"}, {\"USD_RATE\", \"USD Rate\"}, {\"FIN_PRODUCT_GROUP\", \"Finance Product Group\"}, {\"FIN_PRODUCT_FAMILY\", \"Finance Product Family\"}, {\"FIN_FORECAST_FIELD\", \"Finance Forecast Field\"}, {\"FIN_PRODUCT_SEGMENT\", \"Finance Product Segment\"}, {\"FIN_PRODUCT_LINE\", \"Finance Product Line\"}, {\"CREATION_DATE\", \"Creation Date\"}, {\"EXTRACT_DATE\", \"Extract Date\"}, {\"LOCAL_EXTRACT_DATE\", \"Local Extract Date\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared ENTITY = let\r\n  ENTITY = \"845\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type text]\r\nin\r\n  ENTITY;\r\nshared ORG = let\r\n  ORG = \"PPG\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type text]\r\nin\r\n  ORG;\r\nshared YearOffset = let\r\n  YearOffset = \"5\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type text]\r\nin\r\n  YearOffset;\r\nshared LocalTZ = let\r\n  Local = \"ASIA/Singapore\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type text]\r\nin\r\n  Local;\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"M2_Entity","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"M2_Entity.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Local Extract Date","dataType":"dateTime"},{"name":"Entity","dataType":"string"},{"name":"Department","dataType":"string"},{"name":"Account","dataType":"string"},{"name":"Project","dataType":"string"},{"name":"Inter Company","dataType":"string"},{"name":"GL Period","dataType":"string"},{"name":"Fiscal Year","dataType":"double"},{"name":"Period End Date","dataType":"dateTime"},{"name":"Item Number","dataType":"string"},{"name":"Description","dataType":"string"},{"name":"Item TBU","dataType":"string"},{"name":"Item Product Family","dataType":"string"},{"name":"Item Product Line","dataType":"string"},{"name":"Transaction Source","dataType":"string"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"ORGANIZATION_ID","dataType":"double"},{"name":"VENDOR_ID","dataType":"double"},{"name":"Sales Service Code","dataType":"string"},{"name":"Currency","dataType":"string"},{"name":"CONVERSION_RATE","dataType":"double"},{"name":"Accounted Net","dataType":"double"},{"name":"Accounted Net USD","dataType":"double"},{"name":"Transaction Quantity","dataType":"double"},{"name":"M20 TBU","dataType":"string"},{"name":"M20 PFC","dataType":"string"},{"name":"Allocation Percent","dataType":"double"},{"name":"HFM Account","dataType":"string"},{"name":"HP Account","dataType":"string"},{"name":"HFM ICP","dataType":"string"},{"name":"HFM Function","dataType":"string"},{"name":"HFM Product","dataType":"string"},{"name":"HP Product","dataType":"string"},{"name":"HFM Product Group","dataType":"string"},{"name":"HP SPC Account","dataType":"string"},{"name":"Alternate HFM Product","dataType":"string"},{"name":"Alternate HFM Product Group","dataType":"string"},{"name":"Alternate HP Product","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-12T22:01:46.6752336+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/38b97785-f3a2-4ad9-accd-5d4737e53b88/M2_Entity.csv?snapshot=2022-06-12T22%3A01%3A46.6475807Z"}]},{"$type":"LocalEntity","name":"EO_Reserve","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"EO_Reserve.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Local Extract Date","dataType":"dateTime"},{"name":"Header Status","dataType":"string"},{"name":"Plan Name","dataType":"string"},{"name":"CONTROL_ID","dataType":"double"},{"name":"RESERVE_HEADER_ID","dataType":"double"},{"name":"RESERVE_LINE_ID","dataType":"double"},{"name":"Reserve Period","dataType":"string"},{"name":"Reserve Type","dataType":"string"},{"name":"Organization Code","dataType":"string"},{"name":"ORGANIZATION_ID","dataType":"double"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"Line Status","dataType":"string"},{"name":"Item Number","dataType":"string"},{"name":"Item Description","dataType":"string"},{"name":"System Reserve Quantity","dataType":"double"},{"name":"System Reserve Ext Value","dataType":"double"},{"name":"System Reserve Trf Ext Value","dataType":"double"},{"name":"System Reserve Category","dataType":"string"},{"name":"System Reserve Rate","dataType":"double"},{"name":"System Reserve Amount","dataType":"double"},{"name":"System Reserve Trf Amount","dataType":"double"},{"name":"System Reserve Comment","dataType":"string"},{"name":"Review1 Reserve Quantity","dataType":"double"},{"name":"Review1 Reserve Ext Value","dataType":"double"},{"name":"Review1 Reserve Trf Ext Value","dataType":"double"},{"name":"Review1 Reserve Category","dataType":"string"},{"name":"Review1 Reserve Rate","dataType":"double"},{"name":"Review1 Reserve Amount","dataType":"double"},{"name":"Review1 Reserve Trf Amount","dataType":"double"},{"name":"Review1 Override Reason","dataType":"string"},{"name":"Review1 Comment","dataType":"string"},{"name":"Review2 Reserve Quantity","dataType":"double"},{"name":"Review2 Reserve Ext Value","dataType":"double"},{"name":"Review2 Reserve Trf Ext Value","dataType":"double"},{"name":"Review2 Reserve Category","dataType":"string"},{"name":"Review2 Reserve Rate","dataType":"double"},{"name":"Review2 Reserve Amount","dataType":"double"},{"name":"Review2 Reserve Trf Amount","dataType":"double"},{"name":"Review2 Override Reason","dataType":"string"},{"name":"Review2 Comment","dataType":"string"},{"name":"Final Reserve Quantity","dataType":"double"},{"name":"Final Reserve Ext Value","dataType":"double"},{"name":"Final Reserve Trf Ext Value","dataType":"double"},{"name":"Final Reserve Category","dataType":"string"},{"name":"Final Reserve Rate","dataType":"double"},{"name":"Final Reserve Amount","dataType":"double"},{"name":"Final Reserve Trf Amount","dataType":"double"},{"name":"Final Reserve Amount Usd","dataType":"double"},{"name":"Final Taken From","dataType":"string"},{"name":"Final Finance Approve Date","dataType":"dateTime"},{"name":"Review1 User","dataType":"string"},{"name":"Review1 Date","dataType":"dateTime"},{"name":"Review2 User","dataType":"string"},{"name":"Review2 Date","dataType":"dateTime"},{"name":"Review3 User","dataType":"string"},{"name":"Review3 Date","dataType":"dateTime"},{"name":"Operating Unit","dataType":"string"},{"name":"Ledger Short Name","dataType":"string"},{"name":"Currency Code","dataType":"string"},{"name":"Organization Category","dataType":"string"},{"name":"Reserve Entity","dataType":"string"},{"name":"Reserve Department","dataType":"string"},{"name":"Reserve Account","dataType":"string"},{"name":"Reserve IC","dataType":"string"},{"name":"TBU","dataType":"string"},{"name":"Product Family","dataType":"string"},{"name":"Product Line","dataType":"string"},{"name":"Org TBU","dataType":"string"},{"name":"Org Product Family","dataType":"string"},{"name":"Org Product Line","dataType":"string"},{"name":"Fin TBU","dataType":"string"},{"name":"Fin Product Family","dataType":"string"},{"name":"Planner Code","dataType":"string"},{"name":"Green Supply Status","dataType":"string"},{"name":"Asset Flag","dataType":"string"},{"name":"Nettable Flag","dataType":"string"},{"name":"Make Buy","dataType":"string"},{"name":"Service Lead Time","dataType":"string"},{"name":"Date Last Activity","dataType":"dateTime"},{"name":"Lot Size","dataType":"double"},{"name":"Item Cost Standard","dataType":"double"},{"name":"Item Trf Cost","dataType":"double"},{"name":"Item Price","dataType":"double"},{"name":"Class Code","dataType":"string"},{"name":"Acct Class Type","dataType":"string"},{"name":"Item Type","dataType":"string"},{"name":"Item Status Code","dataType":"string"},{"name":"Abc Class Code","dataType":"string"},{"name":"Subinventory","dataType":"string"},{"name":"Lot Number","dataType":"string"},{"name":"Site Code","dataType":"string"},{"name":"Control Org Code","dataType":"string"},{"name":"LOCATOR_ID","dataType":"double"},{"name":"Loc Sub","dataType":"string"},{"name":"Loc Row","dataType":"string"},{"name":"Loc Rack","dataType":"string"},{"name":"Loc Shelf","dataType":"string"},{"name":"Loc Bin","dataType":"string"},{"name":"Nettable Onhand Quantity","dataType":"double"},{"name":"Non Nettable Onhand Quantity","dataType":"double"},{"name":"Nettable RCV Quantity","dataType":"double"},{"name":"Non Nettable RCV Quantity","dataType":"double"},{"name":"Nettable ITRN Quantity","dataType":"double"},{"name":"Non Nettable ITRN Quantity","dataType":"double"},{"name":"WIP Remaining Quantity","dataType":"double"},{"name":"Total Nettable Quantity","dataType":"double"},{"name":"Total Non Nettable Quantity","dataType":"double"},{"name":"Total Resulting Quantity","dataType":"double"},{"name":"Total Nettable Ext Value","dataType":"double"},{"name":"Total Non Nettable Ext Value","dataType":"double"},{"name":"Total Onhand Ext Value","dataType":"double"},{"name":"Total Receiving Ext Value","dataType":"double"},{"name":"Total Intransit Ext Value","dataType":"double"},{"name":"Demand 0-03","dataType":"double"},{"name":"Demand 0-12","dataType":"double"},{"name":"Demand 0-18","dataType":"double"},{"name":"Demand 0-24","dataType":"double"},{"name":"Demand Substitute","dataType":"double"},{"name":"Usage 0-03","dataType":"double"},{"name":"Usage 0-12","dataType":"double"},{"name":"Usage 0-18","dataType":"double"},{"name":"Usage 0-24","dataType":"double"},{"name":"Usage 13-24","dataType":"double"},{"name":"Usage Substitute","dataType":"double"},{"name":"Open Order 0-03","dataType":"double"},{"name":"Open Order 0-12","dataType":"double"},{"name":"Open Order 0-18","dataType":"double"},{"name":"Open Order 0-24","dataType":"double"},{"name":"Open Order Substitute","dataType":"double"},{"name":"Resulting Quantity Leftover","dataType":"double"},{"name":"WIP Entity Name","dataType":"string"},{"name":"WIP Job Type","dataType":"string"},{"name":"WIP Job Status","dataType":"string"},{"name":"WIP Date Released","dataType":"dateTime"},{"name":"WIP Total Costs Incurred","dataType":"double"},{"name":"WIP Total Costs Relieved","dataType":"double"},{"name":"WIP Total Variances Relieved","dataType":"double"},{"name":"WIP Total Net Activities","dataType":"double"},{"name":"WIP Days Released","dataType":"double"},{"name":"WIP Months Released","dataType":"double"},{"name":"WIP Aging Bucket","dataType":"string"},{"name":"WIP_ENTITY_ID","dataType":"double"},{"name":"Serial Number Control Code","dataType":"double"},{"name":"Serial Number","dataType":"string"},{"name":"Serial Number Override","dataType":"string"},{"name":"Serial Number Final","dataType":"string"},{"name":"Serial Number History","dataType":"string"},{"name":"Serial Number Status","dataType":"string"},{"name":"LC_TRACKING_ID","dataType":"double"},{"name":"LC Quantity","dataType":"double"},{"name":"LC Earliest Trx Date","dataType":"dateTime"},{"name":"LC Latest Stock Date","dataType":"dateTime"},{"name":"LC Start Date","dataType":"dateTime"},{"name":"LC Start Date Override","dataType":"dateTime"},{"name":"LC Start Date Final","dataType":"dateTime"},{"name":"LC Location Status","dataType":"string"},{"name":"LC Period Reserve Amount","dataType":"double"},{"name":"LC Current Reserve Amount","dataType":"double"},{"name":"GL Period Name","dataType":"string"},{"name":"Period Year","dataType":"double"},{"name":"Period Quarter","dataType":"double"},{"name":"Period Num","dataType":"double"},{"name":"LC Period Count","dataType":"double"},{"name":"LC Days Count","dataType":"double"},{"name":"LC Status","dataType":"string"},{"name":"OPERATING_UNIT_ID","dataType":"double"},{"name":"LEDGER_ID","dataType":"double"},{"name":"RESERVE_ACCOUNT_ID","dataType":"double"},{"name":"Creation Date","dataType":"dateTime"},{"name":"Created By","dataType":"double"},{"name":"Last Update Date","dataType":"dateTime"},{"name":"Last Updated By","dataType":"double"},{"name":"Quantity1","dataType":"double"},{"name":"Quantity2","dataType":"double"},{"name":"Quantity3","dataType":"double"},{"name":"Quantity4","dataType":"double"},{"name":"Quantity5","dataType":"double"},{"name":"Demand1","dataType":"double"},{"name":"Demand2","dataType":"double"},{"name":"Demand3","dataType":"double"},{"name":"Demand4","dataType":"double"},{"name":"Demand5","dataType":"double"},{"name":"Usage1","dataType":"double"},{"name":"Usage2","dataType":"double"},{"name":"Usage3","dataType":"double"},{"name":"Usage4","dataType":"double"},{"name":"Usage5","dataType":"double"},{"name":"Open Order1","dataType":"double"},{"name":"Open Order2","dataType":"double"},{"name":"Open Order3","dataType":"double"},{"name":"Open Order4","dataType":"double"},{"name":"Open Order5","dataType":"double"},{"name":"Total1","dataType":"double"},{"name":"Total2","dataType":"double"},{"name":"Total3","dataType":"double"},{"name":"Total4","dataType":"double"},{"name":"Total5","dataType":"double"},{"name":"Date1","dataType":"dateTime"},{"name":"Date2","dataType":"dateTime"},{"name":"Date3","dataType":"dateTime"},{"name":"Date4","dataType":"dateTime"},{"name":"Date5","dataType":"dateTime"},{"name":"Location1","dataType":"string"},{"name":"Location2","dataType":"string"},{"name":"Location3","dataType":"string"},{"name":"Location4","dataType":"string"},{"name":"Location5","dataType":"string"},{"name":"Prior Reserve Quantity","dataType":"double"},{"name":"Prior Reserve Ext Value","dataType":"double"},{"name":"Prior Reserve Trf Ext Value","dataType":"double"},{"name":"Prior Reserve Category","dataType":"string"},{"name":"Prior Reserve Rate","dataType":"double"},{"name":"Prior Reserve Amount","dataType":"double"},{"name":"Prior Reserve Trf Amount","dataType":"double"},{"name":"Prior Reserve Amount Usd","dataType":"double"},{"name":"Prior Onhand Quantity","dataType":"double"},{"name":"Prior Comment","dataType":"string"},{"name":"Forecast","dataType":"string"},{"name":"Org Forecast","dataType":"string"},{"name":"Fin Forecast","dataType":"string"},{"name":"Prior Override Reason","dataType":"string"},{"name":"System Reserve Amount Usd","dataType":"double"},{"name":"User Defined 1","dataType":"string"},{"name":"User Defined 2","dataType":"string"},{"name":"User Defined 3","dataType":"string"},{"name":"User Defined 4","dataType":"string"},{"name":"Ops Reporting","dataType":"string"},{"name":"SEC Reporting","dataType":"string"},{"name":"Open PO 0-12","dataType":"double"},{"name":"Open PO 0-24","dataType":"double"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-12T22:00:50.0921699+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/38b97785-f3a2-4ad9-accd-5d4737e53b88/EO_Reserve.csv?snapshot=2022-06-12T22%3A00%3A50.0730598Z"}]},{"$type":"LocalEntity","name":"GL_Reserve","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"GL_Reserve.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Local Extract Date","dataType":"dateTime"},{"name":"JE_HEADER_ID","dataType":"int64"},{"name":"Entity","dataType":"string"},{"name":"Department","dataType":"string"},{"name":"Account","dataType":"string"},{"name":"Project","dataType":"string"},{"name":"Intercompany","dataType":"string"},{"name":"CODE_COMBINATION_ID","dataType":"int64"},{"name":"LEDGER_ID","dataType":"int64"},{"name":"JE Category","dataType":"string"},{"name":"JE Source","dataType":"string"},{"name":"Currency Code","dataType":"string"},{"name":"Posted Date","dataType":"dateTime"},{"name":"Effective Date","dataType":"dateTime"},{"name":"GL Period Name","dataType":"string"},{"name":"Accounted Dr","dataType":"double"},{"name":"Accounted Cr","dataType":"double"},{"name":"Accounted Net","dataType":"double"},{"name":"JE Description","dataType":"string"},{"name":"ATTRIBUTE1","dataType":"string"},{"name":"ATTRIBUTE2","dataType":"string"},{"name":"ATTRIBUTE3","dataType":"string"},{"name":"ATTRIBUTE4","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-12T22:00:23.9355759+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/38b97785-f3a2-4ad9-accd-5d4737e53b88/GL_Reserve.csv?snapshot=2022-06-12T22%3A00%3A23.9150864Z"}]},{"$type":"LocalEntity","name":"Corporate_FX_Rate","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Corporate_FX_Rate.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Local Extract Date","dataType":"dateTime"},{"name":"From Currency","dataType":"string"},{"name":"To Currency","dataType":"string"},{"name":"Conversion Date","dataType":"dateTime"},{"name":"Conversion Type","dataType":"string"},{"name":"USD Rate","dataType":"double"},{"name":"From Base Currency Flag","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-12T22:00:33.0546369+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/38b97785-f3a2-4ad9-accd-5d4737e53b88/Corporate_FX_Rate.csv?snapshot=2022-06-12T22%3A00%3A33.0238543Z"}]},{"$type":"LocalEntity","name":"Inventory_Value","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Inventory_Value.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Local Extract Date","dataType":"dateTime"},{"name":"Period Name","dataType":"string"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"Item Number","dataType":"string"},{"name":"Item Description","dataType":"string"},{"name":"KEY_CATEGORY_ID","dataType":"double"},{"name":"Item TBU","dataType":"string"},{"name":"Item Product Family","dataType":"string"},{"name":"Value Source","dataType":"string"},{"name":"Item Cost","dataType":"double"},{"name":"Cost Incurred","dataType":"double"},{"name":"Cost Relieved","dataType":"double"},{"name":"Cost Variance","dataType":"double"},{"name":"JE Source Category","dataType":"string"},{"name":"Operations Reporting","dataType":"string"},{"name":"Demand Source","dataType":"string"},{"name":"Supply Source","dataType":"string"},{"name":"Exclude Flag","dataType":"string"},{"name":"Exclude Comment","dataType":"string"},{"name":"WIP Class","dataType":"string"},{"name":"WIP Class Code","dataType":"string"},{"name":"Item Type","dataType":"string"},{"name":"Planner Code","dataType":"string"},{"name":"ABC Class","dataType":"string"},{"name":"Item Status","dataType":"string"},{"name":"Supply Chain Status","dataType":"string"},{"name":"Subinventory","dataType":"string"},{"name":"Account Code","dataType":"string"},{"name":"Inventory Quantity","dataType":"double"},{"name":"Inventory Value","dataType":"double"},{"name":"Inventory Value USD","dataType":"double"},{"name":"FISCAL_PERIOD_ID","dataType":"double"},{"name":"FISCAL_WEEK_ID","dataType":"double"},{"name":"FISCAL_WEEK","dataType":"string"},{"name":"WEEK_SERIES","dataType":"double"},{"name":"Scenario","dataType":"string"},{"name":"FISCAL_MONTH","dataType":"string"},{"name":"Material Cost","dataType":"double"},{"name":"Material Overhead Cost","dataType":"double"},{"name":"OSP Cost","dataType":"double"},{"name":"Overhead Cost","dataType":"double"},{"name":"Resource Cost","dataType":"double"},{"name":"WIP_JOB_ID","dataType":"double"},{"name":"WIP Job Number","dataType":"string"},{"name":"USD Rate","dataType":"double"},{"name":"Finance Product Group","dataType":"string"},{"name":"Finance Product Family","dataType":"string"},{"name":"Finance Forecast Field","dataType":"string"},{"name":"Finance Product Segment","dataType":"string"},{"name":"Finance Product Line","dataType":"string"},{"name":"Creation Date","dataType":"dateTime"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-12T22:01:54.3430117+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/38b97785-f3a2-4ad9-accd-5d4737e53b88/Inventory_Value.csv?snapshot=2022-06-12T22%3A01%3A54.3201725Z"}]}]}