{"name":"COHREP_SITE_INVENTORY_TRX_ARCHIVE1","description":"5 years (fiscal calendar) of inventory related transactions, refreshed weekly","version":"1.0","culture":"en-US","modifiedTime":"2021-01-08T07:08:24.4393056+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":true,"queriesMetadata":{"Material_Transaction_Archive":{"queryId":"c3e9354f-71ae-4377-9bd7-f1ee55046f90","queryName":"Material_Transaction_Archive","queryGroupId":"root","loadEnabled":true},"ORG":{"queryId":"36a8d3e4-11b5-4354-bbef-96c2eec38847","queryName":"ORG"},"YearOffset":{"queryId":"d8458485-99e4-46f2-8f7c-9bc4f9c2531b","queryName":"YearOffset"},"Local":{"queryId":"9d31147a-1711-4f0e-83b2-0e0d39dc6cd1","queryName":"Local"}},"document":"section Section1;\r\nshared Material_Transaction_Archive = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, Query=\"\n    SELECT\n    sysdate extract_date,\n    from_tz(cast (sysdate as timestamp),'PST') at time zone '\"&Local&\"' local_extract_date,\n    from_tz(cast (mmt.transaction_date as timestamp),'PST') at time zone '\"&Local&\"' local_transaction_date,\n    mp.organization_code,\n    msi.inventory_item_id,\n    msi.segment1,\n    mmt.primary_quantity,\n    mmt.transaction_date,\n    mmt.transaction_id,\n    mtt.transaction_type_name,\n    flv.meaning    transaction_action,\n    mmt.subinventory_code,\n    mmt.transfer_subinventory,\n    tst.transaction_source_type_name,\n    mmt.transfer_transaction_id,\n    mmt.transaction_reference,\n    CASE\n    WHEN tst.transaction_source_type_name = 'Job or Schedule'\n    AND (\n    SELECT\n    COUNT(1)\n    FROM\n    apps.wip_discrete_jobs_v wdj\n    WHERE\n    wdj.wip_entity_id = mmt.transaction_source_id\n    ) = 0 THEN\n    'Work Orderless'\n    ELSE\n    tst.transaction_source_type_name\n    END source_type,\n    CASE\n    WHEN tst.transaction_source_type_name = 'Job or Schedule' THEN\n    CASE\n    WHEN (\n    SELECT\n    wdj.class_code\n    FROM\n    apps.wip_discrete_jobs_v wdj\n    WHERE\n    wdj.wip_entity_id = mmt.transaction_source_id\n    AND tst.transaction_source_type_name = 'Job or Schedule'\n    ) IS NULL THEN\n    (\n    SELECT\n    wdj.class_code\n    FROM\n    apps.wip_flow_schedules wdj\n    WHERE\n    wdj.wip_entity_id = mmt.transaction_source_id\n    AND tst.transaction_source_type_name = 'Job or Schedule'\n    )\n    ELSE\n    (\n    SELECT\n    wdj.class_code\n    FROM\n    apps.wip_discrete_jobs_v wdj\n    WHERE\n    wdj.wip_entity_id = mmt.transaction_source_id\n    AND tst.transaction_source_type_name = 'Job or Schedule'\n    )\n    END\n    END wip_job_class,\n    CASE\n    WHEN mmt.transaction_source_type_id = 1     THEN\n    (\n    SELECT\n    pha.segment1\n    FROM\n    apps.po_headers_all pha\n    WHERE\n    pha.po_header_id = mmt.transaction_source_id\n    )\n    WHEN mmt.transaction_source_type_id = 2     THEN\n    (\n    SELECT\n    segment1\n    FROM\n    apps.mtl_sales_orders\n    WHERE\n    sales_order_id = mmt.transaction_source_id\n    )\n    WHEN mmt.transaction_source_type_id = 4     THEN\n    (\n    SELECT\n    request_number\n    FROM\n    apps.mtl_txn_request_headers mtrh\n    WHERE\n    request_number = to_char(mmt.transaction_source_id)\n    AND mtrh.organization_id = mmt.organization_id\n    )\n    WHEN mmt.transaction_source_type_id = 5     THEN\n    (\n    SELECT\n    wip_entity_name\n    FROM\n    apps.wip_entities\n    WHERE\n    wip_entity_id = mmt.transaction_source_id\n    )\n    WHEN mmt.transaction_source_type_id = 6     THEN\n    (\n    SELECT\n    segment1\n    FROM\n    apps.mtl_generic_dispositions mgd\n    WHERE\n    mgd.disposition_id = mmt.transaction_source_id\n    )\n    WHEN mmt.transaction_source_type_id = 7     THEN\n    (\n    SELECT\n    rcv.shipment_num\n    FROM\n    apps.rcv_shipment_headers    rcv,\n    apps.rcv_transactions        rcvt\n    WHERE\n    rcv.shipment_header_id = rcvt.shipment_header_id\n    AND rcvt.transaction_id = mmt.transaction_source_id\n    )\n    WHEN mmt.transaction_source_type_id = 8     THEN\n    (\n    SELECT\n    segment1\n    FROM\n    apps.mtl_sales_orders\n    WHERE\n    sales_order_id = mmt.transaction_source_id\n    )\n    WHEN mmt.transaction_source_type_id = 10    THEN\n    (\n    SELECT\n    physical_inventory_name\n    FROM\n    apps.mtl_physical_inventories\n    WHERE\n    physical_inventory_id = mmt.transaction_source_id\n    )\n    WHEN mmt.transaction_source_type_id = 13    THEN\n    (\n    SELECT\n    wip_entity_name\n    FROM\n    apps.wip_entities\n    WHERE\n    wip_entity_id = mmt.transaction_source_id\n    )\n    ELSE\n    NULL\n    END source_document,\n    CASE\n    WHEN flv.meaning = 'Ownership Transfer' THEN\n    'Ownership Transfer'\n    WHEN flv.meaning IN (\n    'Subinventory transfer',\n    'Staging transfer'\n    )\n    AND (\n    SELECT\n    mseci2.quantity_tracked\n    FROM\ninv.mtl_secondary_inventories mseci2\n    WHERE\n    mseci2.secondary_inventory_name = mmt.transfer_subinventory\n    AND mseci2.organization_id = mmt.organization_id\n    ) = 1 THEN\n    'Transfer'\n    WHEN flv.meaning IN (\n    'Cycle count adjustment',\n    'Delivery Adjustments'\n    ) THEN\n    'Adjustments'\n    WHEN flv.meaning IN (\n    'Subinventory transfer',\n    'Staging transfer'\n    )\n    AND mmt.transaction_quantity < 0\n    AND (\n    SELECT\n    mseci2.quantity_tracked\n    FROM\ninv.mtl_secondary_inventories mseci2\n    WHERE\n    mseci2.secondary_inventory_name = mmt.transfer_subinventory\n    AND mseci2.organization_id = mmt.organization_id\n    ) = 2 THEN\n    'Usage'\n    WHEN  mtt.transaction_type_name IN (\n    'WIP Issue',\n    'Sales order issue',\n    'Internal order issue',\n    'Int Order Intr Ship',\n    'Move order issue',\n    'WIP Return',\n    'Field Service Usage',\n    'Assembly return',\n    'WIP Negative Issue',\n    'WIP Negative Return'\n    ) THEN\n    'Usage'\n    WHEN mtt.transaction_type_name IN (\n    'RMA Return',\n    'RMA Receipt',\n    'LC Return'\n    ) THEN\n    'Return'\n    WHEN mtt.transaction_type_name IN (\n    'Account issue',\n    'Account alias issue',\n    'Miscellaneous issue'\n    ) THEN\n    'Miscellaneous out'\n    WHEN mtt.transaction_type_name IN (\n    'Account receipt',\n    'Account alias receipt',\n    'Miscellaneous receipt'\n    ) THEN\n    'Miscellaneous in'\n    WHEN mtt.transaction_type_name IN (\n    'WIP Assy Completion',\n    'WIP Completion Return'\n    ) THEN\n    'Build'\n    WHEN mmt.rcv_transaction_id > 0 THEN\n    'Receipt'\n    ELSE\n    'Other'\n    END transaction_classification,\n    CASE\n    WHEN mmt.owning_organization_id = mmt.organization_id THEN\n    CASE\n    WHEN mseci.asset_inventory = 1 THEN\n    mmt.actual_cost\n    ELSE\n    0\n    END\n    ELSE\n    0\n    END actual_cost,\n    fu.user_name created_by\n    FROM\n    apps.mtl_material_transactions    mmt,\n    apps.mtl_transaction_types        mtt,\ninv.mtl_parameters                mp,\ninv.mtl_system_items_b            msi,\n    fnd_lookup_values                 flv,\ninv.mtl_secondary_inventories     mseci,\ninv.mtl_txn_source_types          tst,\n    apps.fnd_user fu\n    WHERE\n    mmt.transaction_type_id = mtt.transaction_type_id\n    AND mp.organization_id = mmt.organization_id\n    AND msi.inventory_item_id = mmt.inventory_item_id\n    AND flv.language = 'US'\n    AND msi.organization_id = mp.organization_id\n    AND flv.lookup_code = mtt.transaction_action_id\n    AND flv.lookup_type = 'MTL_TRANSACTION_ACTION'\n    AND mseci.secondary_inventory_name = mmt.subinventory_code\n    AND tst.transaction_source_type_id = mtt.transaction_source_type_id\n    AND mseci.organization_id = mmt.organization_id\n    AND mp.organization_code = '\"&ORG&\"'\n    AND mmt.transaction_date >= (SELECT\n    MIN(gp.year_start_date)\n    FROM\n    gl.gl_periods            gp\n    WHERE\n    gp.period_set_name = 'COHR Calendar'\n    AND PERIOD_YEAR =(SELECT\n    gp.PERIOD_YEAR - \"&YearOffset&\"\n    FROM\n    gl.gl_periods            gp\n    WHERE\n    gp.period_set_name = 'COHR Calendar'\n    AND trunc(sysdate) between gp.start_date and gp.end_date\n    ))\n    AND mmt.transaction_date < (\n        SELECT\n            gp.year_start_date\n        FROM\n            gl.gl_periods            gp\n        WHERE\n                gp.period_set_name = 'COHR Calendar'\n            AND trunc(sysdate) between gp.start_date and gp.end_date\n    )\n    AND transaction_quantity <> 0\n    AND fu.user_id = mmt.created_by\n    \", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"ORGANIZATION_CODE\", \"Organization Code\"}, {\"SEGMENT1\", \"Item Number\"}, {\"PRIMARY_QUANTITY\", \"Primary Transaction Quantity\"}, {\"TRANSACTION_DATE\", \"Transaction Date\"}, {\"TRANSACTION_TYPE_NAME\", \"Transaction Type Name\"}, {\"TRANSACTION_ACTION\", \"Transaction Action\"}, {\"SUBINVENTORY_CODE\", \"Transaction Subinventory\"}, {\"TRANSFER_SUBINVENTORY\", \"Transfer Subinventory\"}, {\"TRANSACTION_SOURCE_TYPE_NAME\", \"Transaction Source Type Name\"}, {\"TRANSACTION_REFERENCE\", \"Transaction Reference\"}, {\"SOURCE_TYPE\", \"Calculated Transaction Source Type\"}, {\"SOURCE_DOCUMENT\", \"Source Document Number\"}, {\"TRANSACTION_CLASSIFICATION\", \"Transaction Classification\"}, {\"ACTUAL_COST\", \"Actual Cost\"}, {\"WIP_JOB_CLASS\", \"WIP Accounting Class\"}, {\"EXTRACT_DATE\", \"Extract Date\"}, {\"CREATED_BY\", \"Created By\"}, {\"LOCAL_EXTRACT_DATE\", \"Local Extract Date\"}, {\"LOCAL_TRANSACTION_DATE\", \"Local Transaction Date\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared ORG = let\r\n  ORG = \"PPG\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type text]\r\nin\r\n  ORG;\r\nshared YearOffset = let\r\n  YearOffset = \"5\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type text]\r\nin\r\n  YearOffset;\r\nshared Local = let\r\n  LocalZoneRegion = \"Asia/Singapore\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type any]\r\nin\r\n  LocalZoneRegion;\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"Material_Transaction_Archive","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Material_Transaction_Archive.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Local Extract Date","dataType":"dateTime"},{"name":"Local Transaction Date","dataType":"dateTime"},{"name":"Organization Code","dataType":"string"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"Item Number","dataType":"string"},{"name":"Primary Transaction Quantity","dataType":"double"},{"name":"Transaction Date","dataType":"dateTime"},{"name":"TRANSACTION_ID","dataType":"double"},{"name":"Transaction Type Name","dataType":"string"},{"name":"Transaction Action","dataType":"string"},{"name":"Transaction Subinventory","dataType":"string"},{"name":"Transfer Subinventory","dataType":"string"},{"name":"Transaction Source Type Name","dataType":"string"},{"name":"TRANSFER_TRANSACTION_ID","dataType":"double"},{"name":"Transaction Reference","dataType":"string"},{"name":"Calculated Transaction Source Type","dataType":"string"},{"name":"WIP Accounting Class","dataType":"string"},{"name":"Source Document Number","dataType":"string"},{"name":"Transaction Classification","dataType":"string"},{"name":"Actual Cost","dataType":"double"},{"name":"Created By","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-12T20:02:39.2065405+00:00","location":"https://wabiwuscpcdsa.blob.core.windows.net:443/1d9ed2b2-23c0-48f8-9046-45844aca74a4/Material_Transaction_Archive.csv?snapshot=2022-06-12T20%3A02%3A39.2041662Z"}]}]}