{"name":"Target_Budget","description":"Target and Budget reference","version":"1.0","culture":"en-US","modifiedTime":"2021-06-16T04:16:49.0439915+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"Manufacturing_Expense_Budget":{"queryId":"d2c7c093-0d5f-4e8a-8ada-4100e3368644","queryName":"Manufacturing_Expense_Budget","loadEnabled":true},"Entity":{"queryId":"1e7d0d61-ea45-431a-ad62-02e27d0b3978","queryName":"Entity"},"ORG":{"queryId":"8e99d473-c476-4a81-9fdb-865442c58285","queryName":"ORG"},"Revenue_SPC_Budget":{"queryId":"988b8a53-db5f-44af-844d-d6ecadf9a1be","queryName":"Revenue_SPC_Budget","loadEnabled":true},"Manufacturing_Expense_Fcst":{"queryId":"c858b641-b53a-449d-b4b0-20f142a77706","queryName":"Manufacturing_Expense_Fcst","loadEnabled":true}},"document":"section Section1;\r\nshared Manufacturing_Expense_Budget = let\r\n  Source = Sql.Database(\"SGSINSSQLDEV1\", \"SPG_Database_Test\"),\r\n  Navigation = Source{[Schema = \"XXFACTS\", Item = \"FFDU_FIN_MfgExpenseBudget\"]}[Data],\r\n  #\"Filtered rows\" = Table.SelectRows(Navigation, each [GL_ENTITY_CODE] = Entity),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Filtered rows\", {{\"FC_YEAR\", \"FC Year\"}, {\"BUDGET_AMOUNT_USD\", \"Budget Amount USD\"}, {\"GL_DEPARTMENT_CODE\", \"GL Department Code\"}, {\"GL_ENTITY_CODE\", \"GL Entity Code\"}, {\"GL_ACCOUNT_CODE\", \"GL Account Code\"}}),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Renamed columns\", {{\"Budget Amount USD\", Currency.Type}}),\r\n  #\"Removed other columns\" = Table.SelectColumns(#\"Changed column type\", {\"FC Year\", \"GL Department Code\", \"GL Entity Code\", \"GL Account Code\", \"Budget Amount USD\", \"FC_QUARTER\"}),\r\n  #\"Renamed columns 1\" = Table.RenameColumns(#\"Removed other columns\", {{\"FC_QUARTER\", \"FC Quarter\"}})\r\nin\r\n  #\"Renamed columns 1\";\r\nshared Entity = let\r\n  Entity = \"845\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type text]\r\nin\r\n  Entity;\r\nshared ORG = let\r\n  ORG = \"PPG\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type text]\r\nin\r\n  ORG;\r\nshared Revenue_SPC_Budget = let\r\n  Source = Sql.Databases(\"SGSINSSQLDEV1\"),\r\n  Navigation = Source{[Name = \"SPG_Database_Test\"]}[Data],\r\n  #\"Navigation 1\" = Navigation{[Schema = \"XXFACTS\", Item = \"FFDU_FIN_RevSpcBudget\"]}[Data],\r\n  #\"Filtered rows\" = Table.SelectRows(#\"Navigation 1\", each [ORG] = ORG),\r\n  #\"Removed columns\" = Table.RemoveColumns(#\"Filtered rows\", {\"PK_ID\", \"ORG\", \"ADDED_BY\", \"TIMESTAMP\"}),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Removed columns\", {{\"ITEM_PRODUCT_FAMILY\", \"Item Product Family\"}, {\"ACCOUNT\", \"Account\"}, {\"VERSION\", \"Version\"}, {\"FC_YEAR\", \"FC Year\"}, {\"FC_QUARTER\", \"FC Quarter\"}, {\"PLANNER_GROUP\", \"Planner Group\"}, {\"AMOUNT_USD\", \"Amount USD\"}, {\"AOP_EXTERNAL_REVENUE_FLOWTHROUGH_USD\", \"External Revenue Flowthrough AOP USD\"}, {\"PLANNER_CODE\", \"Planner Code\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Manufacturing_Expense_Fcst = let\r\n  Source = Sql.Database(\"SGSINSSQLDEV1\", \"SPG_Database_Test\"),\r\n  Navigation = Source{[Item = \"FFDU_FIN_MfgExpenseFcst\", Schema = \"XXFACTS\"]}[Data],\r\n  #\"Filtered rows\" = Table.SelectRows(Navigation, each [GL_ENTITY_CODE] = Entity),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Filtered rows\", {{\"FC_YEAR\", \"FC Year\"}, {\"FCST_AMOUNT_USD\", \"Forecast Amount USD\"}, {\"GL_DEPARTMENT_CODE\", \"GL Department Code\"}, {\"GL_ENTITY_CODE\", \"GL Entity Code\"}, {\"GL_ACCOUNT_CODE\", \"GL Account Code\"}}),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Renamed columns\", {{\"Forecast Amount USD\", Currency.Type}}),\r\n  #\"Removed other columns\" = Table.SelectColumns(#\"Changed column type\", {\"FC Year\", \"GL Department Code\", \"GL Entity Code\", \"GL Account Code\", \"Forecast Amount USD\", \"FC_QUARTER\"}),\r\n  #\"Renamed columns 1\" = Table.RenameColumns(#\"Removed other columns\", {{\"FC_QUARTER\", \"FC Quarter\"}})\r\nin\r\n  #\"Renamed columns 1\";\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"Manufacturing_Expense_Budget","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Manufacturing_Expense_Budget.csv"},"attributes":[{"name":"FC Year","dataType":"int64"},{"name":"GL Department Code","dataType":"string"},{"name":"GL Entity Code","dataType":"string"},{"name":"GL Account Code","dataType":"string"},{"name":"Budget Amount USD","dataType":"decimal"},{"name":"FC Quarter","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-12T23:01:03.9234394+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/d075824d-9d16-40e3-8514-75b0325d47da/Manufacturing_Expense_Budget.csv?snapshot=2022-06-12T23%3A01%3A03.8209312Z"}]},{"$type":"LocalEntity","name":"Revenue_SPC_Budget","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Revenue_SPC_Budget.csv"},"attributes":[{"name":"Item Product Family","dataType":"string"},{"name":"Account","dataType":"string"},{"name":"Version","dataType":"string"},{"name":"FC Year","dataType":"int64"},{"name":"FC Quarter","dataType":"string"},{"name":"Planner Code","dataType":"string"},{"name":"Planner Group","dataType":"string"},{"name":"Amount USD","dataType":"double"},{"name":"External Revenue Flowthrough AOP USD","dataType":"double"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-12T23:02:00.0249797+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/d075824d-9d16-40e3-8514-75b0325d47da/Revenue_SPC_Budget.csv?snapshot=2022-06-12T23%3A01%3A59.4207027Z"}]},{"$type":"LocalEntity","name":"Manufacturing_Expense_Fcst","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Manufacturing_Expense_Fcst.csv"},"attributes":[{"name":"FC Year","dataType":"int64"},{"name":"GL Department Code","dataType":"string"},{"name":"GL Entity Code","dataType":"string"},{"name":"GL Account Code","dataType":"string"},{"name":"Forecast Amount USD","dataType":"decimal"},{"name":"FC Quarter","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-12T23:00:24.1776642+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/d075824d-9d16-40e3-8514-75b0325d47da/Manufacturing_Expense_Fcst.csv?snapshot=2022-06-12T23%3A00%3A23.8590958Z"}]}]}