{
    "name": "InventoryTurnsModel_2_Flow",
    "description": "This dataflow contains Dimension and Fact Tables that are used in the Corporate Inventory Report which is located in the \n\nWorkspace - Corporate Inventory Reports\nWorkspace - Corporate Inventory DataModels",
    "version": "1.0",
    "culture": "en-US",
    "modifiedTime": "2022-05-18T08:48:09.751285+00:00",
    "pbi:mashup": {
        "fastCombine": true,
        "allowNativeQueries": false,
        "queriesMetadata": {
            "FACT_M20Detail": {
                "queryId": "04f577b8-f4e2-4d49-8291-856c32c50733",
                "queryName": "FACT_M20Detail",
                "queryGroupId": "bbd6ee21-6a56-4a8c-b80f-2aad18bde5a6",
                "loadEnabled": true
            },
            "pM20Detail": {
                "queryId": "ec4c021a-4825-48ac-966b-58fa31eb935d",
                "queryName": "pM20Detail",
                "queryGroupId": "5bac1fbe-fe1d-4da2-94f5-070ea55ef66f"
            },
            "FACT_InventoryValue": {
                "queryId": "1c76083f-c3e7-46b4-9625-7d4251a90fb0",
                "queryName": "FACT_InventoryValue",
                "queryGroupId": "bbd6ee21-6a56-4a8c-b80f-2aad18bde5a6",
                "loadEnabled": true
            },
            "FACT_M20DetailAll": {
                "queryId": "5a52aebc-1d8a-40f6-a60c-b6eb154ede51",
                "queryName": "FACT_M20DetailAll",
                "queryGroupId": "bbd6ee21-6a56-4a8c-b80f-2aad18bde5a6",
                "loadEnabled": true
            },
            "FACT_M20Detail_Flow": {
                "queryId": "1cf65057-ebc4-4125-9949-72a5a80766f4",
                "queryName": "FACT_M20Detail_Flow",
                "queryGroupId": "bbd6ee21-6a56-4a8c-b80f-2aad18bde5a6",
                "loadEnabled": true
            },
            "pM20DetailAll": {
                "queryId": "2965b6ac-91d9-4192-9af1-155129dc719a",
                "queryName": "pM20DetailAll",
                "queryGroupId": "5bac1fbe-fe1d-4da2-94f5-070ea55ef66f"
            },
            "pInventoryValue": {
                "queryId": "5a176480-b080-44b9-ae62-a957632271ca",
                "queryName": "pInventoryValue",
                "queryGroupId": "5bac1fbe-fe1d-4da2-94f5-070ea55ef66f"
            },
            "DIM_Time Balance Week": {
                "queryId": "171c1f08-7c59-4a4b-8ae9-35c394332862",
                "queryName": "DIM_Time Balance Week",
                "queryGroupId": "a0966e5b-d860-4160-b742-7c26403daafe",
                "loadEnabled": true
            },
            "DIM_Financial Product Mapping": {
                "queryId": "0f5e1753-772e-46d7-b257-43eeaebd7006",
                "queryName": "DIM_Financial Product Mapping",
                "queryGroupId": "a0966e5b-d860-4160-b742-7c26403daafe",
                "loadEnabled": true
            },
            "DIM_GL Account Segment": {
                "queryId": "82ae9670-9391-4c82-b6e8-e2bef67790ef",
                "queryName": "DIM_GL Account Segment",
                "queryGroupId": "a0966e5b-d860-4160-b742-7c26403daafe",
                "loadEnabled": true
            },
            "DIM_GL Code Combinations": {
                "queryId": "82beb932-ace5-4fd2-b137-459755a29c5f",
                "queryName": "DIM_GL Code Combinations",
                "queryGroupId": "a0966e5b-d860-4160-b742-7c26403daafe",
                "loadEnabled": true
            },
            "DIM_GL Code Combinations Desc": {
                "queryId": "e09b8541-4d99-47d1-bf61-90508c3798e6",
                "queryName": "DIM_GL Code Combinations Desc",
                "queryGroupId": "a0966e5b-d860-4160-b742-7c26403daafe",
                "loadEnabled": true
            },
            "DIM_GL Project Segment": {
                "queryId": "1ea2e978-d5d4-4922-8056-14d97c932008",
                "queryName": "DIM_GL Project Segment",
                "queryGroupId": "a0966e5b-d860-4160-b742-7c26403daafe",
                "loadEnabled": true
            },
            "DIM_Calendar": {
                "queryId": "b1df9ae8-9042-4ea7-877f-b3ce191ebb5c",
                "queryName": "DIM_Calendar",
                "queryGroupId": "a0966e5b-d860-4160-b742-7c26403daafe",
                "loadEnabled": true
            },
            "DIM_Fiscal Context": {
                "queryId": "a1afd083-312b-4a1b-9db4-9a351b582fda",
                "queryName": "DIM_Fiscal Context",
                "queryGroupId": "a0966e5b-d860-4160-b742-7c26403daafe",
                "loadEnabled": true
            },
            "DIM_GLDepartment": {
                "queryId": "1d543e18-798c-4f02-a061-5fe7c4e50152",
                "queryName": "DIM_GLDepartment",
                "queryGroupId": "a0966e5b-d860-4160-b742-7c26403daafe",
                "loadEnabled": true
            },
            "DIM_Inventory Organizations": {
                "queryId": "6e0d17cf-808d-44de-a238-5a43c0025b54",
                "queryName": "DIM_Inventory Organizations",
                "queryGroupId": "a0966e5b-d860-4160-b742-7c26403daafe",
                "loadEnabled": true
            },
            "DIM_Operating Units": {
                "queryId": "b4779505-1965-4444-9c89-a461e0c68084",
                "queryName": "DIM_Operating Units",
                "queryGroupId": "a0966e5b-d860-4160-b742-7c26403daafe",
                "loadEnabled": true
            },
            "DIM_Operating Unit Data Security": {
                "queryId": "b988a535-61a2-41f8-9b81-e2f3074790db",
                "queryName": "DIM_Operating Unit Data Security",
                "queryGroupId": "a0966e5b-d860-4160-b742-7c26403daafe",
                "loadEnabled": true
            },
            "Version History Model": {
                "queryId": "d1d88b72-5b98-47c9-ac31-b235deae27d7",
                "queryName": "Version History Model",
                "queryGroupId": "a91191ed-8efb-400b-bad7-2b8a42e2d413",
                "loadEnabled": true
            },
            "Version History Report": {
                "queryId": "fdbcb66e-3942-4ea9-9c35-cae2a6b02ee7",
                "queryName": "Version History Report",
                "queryGroupId": "a91191ed-8efb-400b-bad7-2b8a42e2d413",
                "loadEnabled": true
            },
            "Version History": {
                "queryId": "2bf1e5d2-e81c-4c86-9342-1257c81a465f",
                "queryName": "Version History",
                "queryGroupId": "a91191ed-8efb-400b-bad7-2b8a42e2d413",
                "loadEnabled": true
            },
            "DIM_GLEntity": {
                "queryId": "2bc75e61-f80f-43b5-8966-59b74f141814",
                "queryName": "DIM_GLEntity",
                "queryGroupId": "a0966e5b-d860-4160-b742-7c26403daafe",
                "loadEnabled": true
            },
            "GetEntity": {
                "queryId": "00aa1ccc-3354-4a12-92fa-d65ddc953bf4",
                "queryName": "GetEntity",
                "queryGroupId": "7363d107-1f3d-48de-be9c-f033354d282e"
            },
            "GetEntityFromWorkspace": {
                "queryId": "d7288925-e451-4640-bf3f-fc75518a1b8f",
                "queryName": "GetEntityFromWorkspace",
                "queryGroupId": "7363d107-1f3d-48de-be9c-f033354d282e"
            },
            "pWorkSpace": {
                "queryId": "136ef995-7550-4d55-b665-c306895cdb40",
                "queryName": "pWorkSpace",
                "queryGroupId": "5bac1fbe-fe1d-4da2-94f5-070ea55ef66f"
            },
            "pDataFlow": {
                "queryId": "7f5f0e03-206a-413b-beab-85729ab5f679",
                "queryName": "pDataFlow",
                "queryGroupId": "5bac1fbe-fe1d-4da2-94f5-070ea55ef66f"
            },
            "pFiscalCalendarDateFilter": {
                "queryId": "d4299f69-5646-40fe-a0f6-d88c1cedebff",
                "queryName": "pFiscalCalendarDateFilter",
                "queryGroupId": "5bac1fbe-fe1d-4da2-94f5-070ea55ef66f"
            },
            "pSetMaxRows": {
                "queryId": "bea6a77d-6c5d-4e46-bc5f-0f951fe6f99b",
                "queryName": "pSetMaxRows",
                "queryGroupId": "5bac1fbe-fe1d-4da2-94f5-070ea55ef66f"
            },
            "pOrganizationOrgs": {
                "queryId": "c53f6f06-7342-4e22-ab87-beab297e444e",
                "queryName": "pOrganizationOrgs",
                "queryGroupId": "5bac1fbe-fe1d-4da2-94f5-070ea55ef66f"
            },
            "pTBU": {
                "queryId": "712aa63e-6676-42aa-9cfe-49f9254bd004",
                "queryName": "pTBU",
                "queryGroupId": "5bac1fbe-fe1d-4da2-94f5-070ea55ef66f"
            },
            "ListOfOrgs": {
                "queryId": "f1f610fc-6348-47ae-86af-692f404cb1ce",
                "queryName": "ListOfOrgs",
                "queryGroupId": "5bac1fbe-fe1d-4da2-94f5-070ea55ef66f",
                "loadEnabled": true
            },
            "DIM_Fiscal Calendar": {
                "queryId": "3b0dccaa-1e63-446a-9aaf-f7bf41d391a7",
                "queryName": "DIM_Fiscal Calendar",
                "queryGroupId": "a0966e5b-d860-4160-b742-7c26403daafe",
                "loadEnabled": true
            },
            "FACT_LT Grouping Summary": {
                "queryId": "532a43a3-86df-4f7e-b426-bab237c7fd33",
                "queryName": "FACT_LT Grouping Summary",
                "queryGroupId": "350542b3-0fe5-4a8f-9abf-594bb26638d7",
                "loadEnabled": true
            },
            "FACT_Inventory Velocity Summary": {
                "queryId": "65917f3b-8e5c-47d8-aea7-ee54873fe39b",
                "queryName": "FACT_Inventory Velocity Summary",
                "queryGroupId": "350542b3-0fe5-4a8f-9abf-594bb26638d7",
                "loadEnabled": true
            },
            "FACT_Inventory Velocity Details": {
                "queryId": "97eba921-cd37-4d0a-9b64-94cc6a1a86e1",
                "queryName": "FACT_Inventory Velocity Details",
                "queryGroupId": "350542b3-0fe5-4a8f-9abf-594bb26638d7",
                "loadEnabled": true
            },
            "DIM_Sort Values": {
                "queryId": "994c12fc-6182-4b55-840d-677feb4c9fda",
                "queryName": "DIM_Sort Values",
                "queryGroupId": "a0966e5b-d860-4160-b742-7c26403daafe",
                "loadEnabled": true
            },
            "Version History Dataflow": {
                "queryId": "16844e25-79c0-48e1-a234-7adb2c775418",
                "queryName": "Version History Dataflow",
                "queryGroupId": "a91191ed-8efb-400b-bad7-2b8a42e2d413",
                "loadEnabled": true
            },
            "INFO_DataUpdateInfoInventoryVelocity": {
                "queryId": "3200c79b-04dc-4d96-bb86-666dad853946",
                "queryName": "INFO_DataUpdateInfoInventoryVelocity",
                "queryGroupId": "d535d7f0-f50c-47a1-a1c5-b52444b9ad0e",
                "loadEnabled": true
            }
        },
        "document": "section Section1;\r\n[Description = \"many only and data has been grouped in snowflake.\"]\r\nshared FACT_M20Detail = let\n    Source = Csv.Document(File.Contents(pM20Detail),[Delimiter=\",\", Columns=15, Encoding=1252, QuoteStyle=QuoteStyle.None]),\n    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),\n    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"ENTITY\", type text}, {\"DEPT\", type text}, {\"ACCT\", type text}, {\"PROJ\", type text}, {\"M20_TBU\", type text}, {\"M20_PFC\", type text}, {\"INTERCO\", type text}, {\"ACCOUNT_DESC\", type text}, {\"GL_PERIOD\", type date}, {\"TRANS_DATE\", type datetime}, {\"TRAN_QTY\", type text}, {\"ACCOUNTED_DR\", type number}, {\"ACCOUNTED_CR\", type number}, {\"NET_ACCOUNTED_AMT\", type number}, {\"ACCOUNTED_NET_USD\", type number}}),\n    #\"Duplicated Column\" = Table.DuplicateColumn(#\"Changed Type\", \"TRANS_DATE\", \"TRANS_DATE - Copy\"),\n    #\"Reordered Columns\" = Table.ReorderColumns(#\"Duplicated Column\",{\"ENTITY\", \"DEPT\", \"ACCT\", \"PROJ\", \"M20_TBU\", \"M20_PFC\", \"INTERCO\", \"ACCOUNT_DESC\", \"GL_PERIOD\", \"TRANS_DATE\", \"TRANS_DATE - Copy\", \"TRAN_QTY\", \"ACCOUNTED_DR\", \"ACCOUNTED_CR\", \"NET_ACCOUNTED_AMT\", \"ACCOUNTED_NET_USD\"}),\n    #\"Extracted Date\" = Table.TransformColumns(#\"Reordered Columns\",{{\"TRANS_DATE\", DateTime.Date, type date}}),\n    #\"Extracted Time\" = Table.TransformColumns(#\"Extracted Date\",{{\"TRANS_DATE - Copy\", DateTime.Time, type time}}),\n    TransTimeColumn = Table.RenameColumns(#\"Extracted Time\",{{\"TRANS_DATE - Copy\", \"TRANS_TIME\"}})\nin\n    TransTimeColumn;\r\nshared pM20Detail = \"C:\\Users\\PeacocCo\\Coherent, Inc\\Power BI Community - Projects\\Inventory\\2. Measure\\DataModels\\test\\data\\XXREP_M20_DETAIL_V.csv\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type text];\r\n[Description = \"TABLENAME: XXREP_INVVALUE_V\"]\r\nshared FACT_InventoryValue = let\n    Source = Csv.Document(File.Contents(pInventoryValue),[Delimiter=\",\", Columns=86, Encoding=65001, QuoteStyle=QuoteStyle.None]),\n    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),\n    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"INV_ORG_ID\", Int64.Type}, {\"INVENTORY_ITEM_ID\", Int64.Type}, {\"ITEM_ORG_ID_KEY\", type text}, {\"ITEM_ORG_CODE_KEY\", type text}, {\"OPERATING_UNIT_ID\", Int64.Type}, {\"ITEM_NUMBER\", type text}, {\"ITEM_TBU\", type text}, {\"ITEM_PRODUCT_FAMILY\", type text}, {\"SOURCE_TYPE\", type text}, {\"SUBINVENTORY_CODE\", type text}, {\"SUBINVENTORY_TYPE\", type text}, {\"ORGANIZATION_CODE\", type text}, {\"ENTITY\", Int64.Type}, {\"ACCOUNT\", Int64.Type}, {\"FIN_ENTITY\", Int64.Type}, {\"INV_QUANTITY\", Int64.Type}, {\"INV_BALANCE\", Int64.Type}, {\"INV_VALUE\", type number}, {\"INV_VALUE_USD\", type number}, {\"CURRENCY_CODE\", type text}, {\"CURRENCY_RATE\", type number}, {\"ITEM_COST\", type number}, {\"MATERIAL_COST\", type number}, {\"MATERIAL_OVERHEAD_COST\", type number}, {\"OUTSIDE_PROCESSING_COST\", type number}, {\"OVERHEAD_COST\", type number}, {\"RESOURCE_COST\", type number}, {\"TOTAL_COST\", type number}, {\"FISCAL_YEAR_ID\", Int64.Type}, {\"VALID_FLAG\", type text}, {\"COMMENTS\", type text}, {\"CREATION_DATE\", type datetimezone}, {\"CREATED_BY\", Int64.Type}, {\"FISCAL_WEEK_ID\", Int64.Type}, {\"FISCAL_WEEK\", type text}, {\"JE_SOURCE_CATEGORY\", type text}, {\"OPERATIONS_REPORTING\", type text}, {\"CS_DEMAND_SOURCE\", type text}, {\"CS_SUPPLY_SOURCE\", type text}, {\"ITEM_TYPE_CODE\", type text}, {\"EXCLUDE_FLAG\", type text}, {\"EXCLUDE_COMMENT\", type text}, {\"WIP_CLASS\", type text}, {\"WIP_CLASS_CODE\", Int64.Type}, {\"ITEM_TYPE\", type text}, {\"PLANNER_CODE\", type text}, {\"MAKE_BUY\", type text}, {\"ITEM_STATUS\", type text}, {\"ABC_CLASS\", type text}, {\"INV_STATUS\", type text}, {\"WIP_JOB_ID\", Int64.Type}, {\"ITEM_PRODUCT_LINE\", type text}, {\"ITEM_FORECAST_FIELD\", type text}, {\"ITEM_DESC\", type text}, {\"WIP_JOB_NO\", type text}, {\"ITEM_COST_USD\", Int64.Type}, {\"ORA_PRODUCT_LINE\", type text}, {\"CONC_REQ_ID\", Int64.Type}, {\"FIN_PRODUCT_LINE\", type text}, {\"ORA_FORECAST_FIELD\", type text}, {\"ORG_TBU\", type text}, {\"ORG_PRODUCT_FAMILY\", type text}, {\"ORG_PRODUCT_LINE\", type text}, {\"ORG_FORECAST_FIELD\", type text}, {\"ORG_CATEGORY_ID\", Int64.Type}, {\"PRODUCT_MAP_KEY\", type text}, {\"FIN_TBU\", type text}, {\"FIN_PFC\", type text}, {\"WEEK_START_DATE\", type datetime}, {\"WEEK_END_DATE\", type datetime}, {\"PERIOD_START_DATE\", type datetime}, {\"PERIOD_END_DATE\", type datetime}, {\"QUARTER_START_DATE\", type datetime}, {\"QUARTER_END_DATE\", type datetime}, {\"FISCAL_QUARTER\", type text}, {\"FISCAL_YEAR\", type text}, {\"MGT_PRODUCT_GROUP\", type text}, {\"MGT_SUB_PRODUCT_GROUP\", type text}, {\"BUSINESS_SEGMENT\", type text}, {\"ACCOUNT_NAME\", type text}, {\"ACCOUNT_DESC\", type text}, {\"ACCOUNT_TYPE\", type text}, {\"ACCOUNT_SUB_GROUP\", type text}, {\"ACCOUNT_GROUP\", type text}, {\"SUMMARY_ACCOUNT\", type text}, {\"INVVALUE_KEY\", type text}}),\n    #\"Duplicated Column\" = Table.DuplicateColumn(#\"Changed Type\", \"CREATION_DATE\", \"CREATION_DATE - Copy\"),\n    #\"Extracted Time\" = Table.TransformColumns(#\"Duplicated Column\",{{\"CREATION_DATE - Copy\", DateTime.Time, type time}}),\n    #\"Renamed Columns\" = Table.RenameColumns(#\"Extracted Time\",{{\"CREATION_DATE - Copy\", \"CREATION_TIME\"}}),\n    #\"Extracted Date\" = Table.TransformColumns(#\"Renamed Columns\",{{\"CREATION_DATE\", DateTime.Date, type date}})\nin\n    #\"Extracted Date\";\r\n[Description = \"TABLENAME: XXREP_M20_DETAIL_V_ALL_ACCOUNTS\"]\r\nshared FACT_M20DetailAll = let\n    Source = Csv.Document(File.Contents(pM20DetailAll),[Delimiter=\",\", Columns=15, Encoding=1252, QuoteStyle=QuoteStyle.None]),\n    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),\n    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"ENTITY\", type text}, {\"DEPT\", type text}, {\"ACCT\", type text}, {\"PROJ\", type text}, {\"M20_TBU\", type text}, {\"M20_PFC\", type text}, {\"INTERCO\", type text}, {\"ACCOUNT_DESC\", type text}, {\"GL_PERIOD\", type date}, {\"TRANS_DATE\", type datetime}, {\"TRAN_QTY\", type text}, {\"ACCOUNTED_DR\", type number}, {\"ACCOUNTED_CR\", type number}, {\"NET_ACCOUNTED_AMT\", type number}, {\"ACCOUNTED_NET_USD\", type number}}),\n    #\"Duplicated Column\" = Table.DuplicateColumn(#\"Changed Type\", \"TRANS_DATE\", \"TRANS_DATE - Copy\"),\n    #\"Extracted Time\" = Table.TransformColumns(#\"Duplicated Column\",{{\"TRANS_DATE - Copy\", DateTime.Time, type time}}),\n    #\"Renamed Columns\" = Table.RenameColumns(#\"Extracted Time\",{{\"TRANS_DATE - Copy\", \"TRANS_TIME\"}}),\n    #\"Extracted Date\" = Table.TransformColumns(#\"Renamed Columns\",{{\"TRANS_DATE\", DateTime.Date, type date}})\nin\n    #\"Extracted Date\";\r\nshared FACT_M20Detail_Flow = let\n    Entity = GetEntityFromWorkspace(pWorkSpace, \"M2.0 Detail Related\", \"M20_Detail\"),\n    FilterMaxNoOfRows = if pSetMaxRows > 0 then Table.FirstN(Entity, pSetMaxRows) else Entity,\n    FilterTBU = if List.IsEmpty(Text.Split(pTBU, \",\")) then Entity else Table.SelectRows(FilterMaxNoOfRows, each List.Contains(List.Buffer(Text.Split(pTBU, \",\")), [M20_TBU]))\nin\n    FilterTBU;\r\nshared pM20DetailAll = \"C:\\Users\\PeacocCo\\Coherent, Inc\\Power BI Community - Projects\\Inventory\\2. Measure\\DataModels\\test\\data\\XXREP_M20_DETAIL_V_ALL_ACCOUNTS.csv\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type text];\r\nshared pInventoryValue = \"C:\\Users\\PeacocCo\\Coherent, Inc\\Power BI Community - Projects\\Inventory\\2. Measure\\DataModels\\test\\data\\XXREP_INVVALUE_V.csv\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type text];\r\nshared #\"DIM_Time Balance Week\" = let\n  Entity = GetEntityFromWorkspace(\"COHR_Dataflows\", \"INV_VELOCITY\", \"Time Balance Week\")\nin\n  Entity;\r\nshared #\"DIM_Financial Product Mapping\" = let\n    Source = GetEntity(\"Financial Product Mapping\")\nin  \n    Source;\r\nshared #\"DIM_GL Account Segment\" = let\n    Source = GetEntity(\"GL Account Segment\")\nin\n    Source;\r\nshared #\"DIM_GL Code Combinations\" = let\n    Source = GetEntity(\"GL Code Combinations\")\nin\n    Source;\r\nshared #\"DIM_GL Code Combinations Desc\" = let\n    Source = GetEntity(\"GL Code Combinations Desc\")\nin\n    Source;\r\nshared #\"DIM_GL Project Segment\" = let\n    Source = GetEntity(\"GL Project Segment\")\nin\n    Source;\r\n[Description = \"TABLENAME: Fiscal Calendar Days\"]\r\nshared DIM_Calendar = let\n    Source = GetEntity(\"Fiscal Calendar Days\")\nin\n    Source;\r\nshared #\"DIM_Fiscal Context\" = let\n    Source = GetEntity(\"Fiscal Context\")\nin\n    Source;\r\n[Description = \"TABLENAME: GL Department Segment\"]\r\nshared DIM_GLDepartment = let\n    Source = GetEntity(\"GL Department Segment\")\nin\n    Source;\r\nshared #\"DIM_Inventory Organizations\" = let\n    Source = GetEntity(\"Inventory Organizations\")\nin\n    Source;\r\nshared #\"DIM_Operating Units\" = let\n    Source = GetEntity(\"Operating Units\")\nin\n    Source;\r\nshared #\"DIM_Operating Unit Data Security\" = let\n    Source = GetEntity(\"Operating Unit Data Security\")\nin\n    Source;\r\nshared #\"Version History Model\" = let\n    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"FcyxCoMwFEbhV/nJXOUa7NJVKThEBUeRcmtuaDAa0ICvXx3PGb5xVEVOOamH0qR1Rs+MShTli+5VxeA39MJznJerm80nzwFJjoQ1WgmYd+EkFqdPPxhNcHFH3Q8DeLNgODlR+xWJv0EOuD2ueDftp+qM6VpYTuxCPC/c3J6apj8=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Version Number\" = _t, #\"Revision Date/Time\" = _t, #\"Developer Name\" = _t, #\"Revision Notes\" = _t, #\"Revision Type\" = _t]),\n    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Version Number\", type text}, {\"Revision Date/Time\", type datetime}, {\"Developer Name\", type text}, {\"Revision Notes\", type text}, {\"Revision Type\", type text}})\nin\n    #\"Changed Type\";\r\nshared #\"Version History Report\" = let\n    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"FcqxCoAgEIDhVzmcMy6xpbWpLVrDQeKoI1HJs16/Gv+Pf11V12KLqlEGjdHYa7TQ2QF/GlPgCDP5LW3n11MUFvYBst8JComuGR6WA4SKwM2l+lC+caGcLlHOvQ==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Version Number\" = _t, #\"Revision Date/Time\" = _t, #\"Developer Name\" = _t, #\"Revision Notes\" = _t, #\"Revision Type\" = _t]),\n    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Version Number\", type text}, {\"Revision Date/Time\", type datetime}, {\"Developer Name\", type text}, {\"Revision Notes\", type text}, {\"Revision Type\", type text}})\nin\n    #\"Changed Type\";\r\nshared #\"Version History\" = let\n    Source = Table.Combine({#\"Version History Model\", #\"Version History Report\"})\nin\n    Source;\r\n[Description = \"TABLENAME: GL Entity Segment\"]\r\nshared DIM_GLEntity = let\n    Source = GetEntity(\"GL Entity Segment\")\nin\n    Source;\r\nshared GetEntity = let\n    // This function retrieves a table (Entity) from the given\n    // workspaceName and dataflowName which are pre-defined\n    // parameters \n    // Set the pWorkSpace and pDataFlow parameters before\n    // invoking this function\n    ReturnEntity = (pEntity as text) => let\n        Source = PowerBI.Dataflows(null),\n        UpperCaseWorkspace = Table.TransformColumns(Source, {{\"workspaceName\", each Text.Upper(Text.From(_)), type nullable text}}),\n        Workspace = UpperCaseWorkspace{[workspaceName=Text.Upper(pWorkSpace)]}[Data],        \n        UpperCaseDataflow = Table.TransformColumns(Workspace, {{\"dataflowName\", each Text.Upper(Text.From(_)), type nullable text}}),\n        Dataflow = UpperCaseDataflow{[dataflowName=Text.Upper(pDataFlow)]}[Data],        \n        UpperCaseEntity = Table.TransformColumns(Dataflow, {{\"entity\", each Text.Upper(Text.From(_)), type nullable text}}),\n        Entity = UpperCaseEntity{[entity=Text.Upper(pEntity)]}[Data]\n    in\n        Entity\nin\n    ReturnEntity;\r\nshared GetEntityFromWorkspace = let\n    // This function retrieves a table (Entity) for the give\n    // workspaceName and dataflowName which are variables\n    // invoked in this function\n    ReturnEntity = (pWorkSpace as text, pDataFlow as text, pEntity as text) => let\n        Source = PowerBI.Dataflows(null),\n        UpperCaseWorkspace = Table.TransformColumns(Source, {{\"workspaceName\", each Text.Upper(Text.From(_)), type nullable text}}),\n        Workspace = UpperCaseWorkspace{[workspaceName=Text.Upper(pWorkSpace)]}[Data],        \n        UpperCaseDataflow = Table.TransformColumns(Workspace, {{\"dataflowName\", each Text.Upper(Text.From(_)), type nullable text}}),\n        Dataflow = UpperCaseDataflow{[dataflowName=Text.Upper(pDataFlow)]}[Data],        \n        UpperCaseEntity = Table.TransformColumns(Dataflow, {{\"entity\", each Text.Upper(Text.From(_)), type nullable text}}),\n        Entity = UpperCaseEntity{[entity=Text.Upper(pEntity)]}[Data]\n    in\n        Entity\nin\n    ReturnEntity;\r\nshared pWorkSpace = \"COHR_DATAFLOWS\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type text];\r\nshared pDataFlow = \"FIN_COMMON\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type text];\r\nshared pFiscalCalendarDateFilter = 3 meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type number];\r\n[Description = \"Use this parameter to set values to Return Max No. of Rows#(lf)Set this value to 0 to disable\"]\r\nshared pSetMaxRows = 0 meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type number];\r\nshared pOrganizationOrgs = \"BCO\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type text];\r\nshared pTBU = \"DPSS_Germany\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type text];\r\nshared ListOfOrgs = let\r\n  Source = pOrganizationOrgs,\r\n  GetListOfValues = Text.Split(Source, \",\"),\r\n  #\"Convert to table\" = Table.FromValue(GetListOfValues),\r\n  #\"Transform columns\" = Table.TransformColumnTypes(#\"Convert to table\", {{\"Value\", type text}}),\r\n  #\"Replace errors\" = Table.ReplaceErrorValues(#\"Transform columns\", {{\"Value\", null}})\r\nin\r\n  #\"Replace errors\";\r\n[Description = \"Coherent Fiscal Calendar.#(lf)Currently filtered to > 29th Sept. 2019\"]\r\nshared #\"DIM_Fiscal Calendar\" = let\n/*\nDIM_Fiscal Calendar is a modified view of the Fiscal Calendar where\n\nA date filter has been applied so that only dates after pFiscalCalendarDateFilter are included\nAdditional columns have been added Cal_Year_ofCW, Cal_Year_ofCW_Short\n*/\n    FiscalCalendarData = GetEntity(\"Fiscal Calendar Days\"),\n    TransformColumnTypes = Table.TransformColumnTypes(FiscalCalendarData,{{\"Calendar Day\", type date}, {\"Week Start Date\", type date}, {\"Week End Date\", type date}, {\"Period Start Date\", type date}, {\"Period End Date\", type date}, {\"Quarter Start Date\", type date}, {\"Quarter End Date\", type date}, {\"Year Start Date\", type date}, {\"Year End Date\", type date}, {\"Fiscal Week No\", Int64.Type}, {\"Fiscal Month Week No\", Int64.Type}, {\"Fiscal Qtr Week No\", Int64.Type}, {\"Period Year\", Int64.Type}, {\"Quarter No\", Int64.Type}, {\"Period No\", Int64.Type}, {\"Fiscal Day\", Int64.Type}, {\"FC_PERIOD_ID\", Int64.Type}, {\"FC_QUARTER_ID\", Int64.Type}, {\"FC_WEEK_ID\", Int64.Type}, {\"FC_YEAR_OFFSET\", Int64.Type}, {\"FC_QUARTER_OFFSET\", Int64.Type}, {\"FC_PERIOD_OFFSET\", Int64.Type}, {\"FC_WEEK_OFFSET\", Int64.Type}, {\"FC_DAYS_OFFSET\", Int64.Type}, {\"CALENDAR_YEAR\", Int64.Type}, {\"CALENDAR_MONTH\", Int64.Type}, {\"CALENDAR_ISO_WEEK\", Int64.Type}, {\"CALENDAR_US_WEEK\", Int64.Type}, {\"DAY_OF_WEEK\", Int64.Type}, {\"WORKING_DAY_FLAG\", Int64.Type}, {\"FISCAL_WEEK_INDICATOR_SORT\", Int64.Type}, {\"FISCAL_MONTH_INDICATOR_SORT\", Int64.Type}, {\"FISCAL_QUARTER_INDICATOR_SORT\", Int64.Type}, {\"FISCAL_YEAR_INDICATOR_SORT\", Int64.Type}}),\n    //Gets all dates from the year offset given by pFiscalCalendarDateFilter (default is set as 3 years)\n    SelectAllRowsAfterThisDate = \n    let\n        GetLastNYearsOfData = Table.AddColumn(TransformColumnTypes, \"PreviousNYears\", each Date.IsInPreviousNYears([Calendar Day], pFiscalCalendarDateFilter)),\n        GetCurrentYearsData = Table.AddColumn(GetLastNYearsOfData, \"CurrentFutureYears\", each [Calendar Day] >= Date.From(Date.StartOfYear(DateTime.FixedLocalNow()))),\n        SelectTheFilteredRows = Table.SelectRows(GetCurrentYearsData, each List.AnyTrue({[PreviousNYears], [CurrentFutureYears]})),\n        ReturnFinalValue = Table.RemoveColumns(SelectTheFilteredRows,{\"PreviousNYears\", \"CurrentFutureYears\"})\n    in\n        ReturnFinalValue,\n    RenameFiscalWeekColumns = Table.RenameColumns(SelectAllRowsAfterThisDate,{{\"Fiscal Week\", \"Fiscal Year Week\"}, {\"Fiscal Year Week\", \"Fiscal Week\"}}),\n    AddStartOfWeekCOlumn = Table.AddColumn(RenameFiscalWeekColumns, \"Start of Week\", each Date.StartOfWeek([Calendar Day]), type date),\n    #\"Inserted Year\" = Table.AddColumn(AddStartOfWeekCOlumn, \"Cal_Year_ofCW\", each Date.Year([Start of Week]), Int64.Type),\n    GetThe2DigitValueOfYear = Table.AddColumn(#\"Inserted Year\", \"Cal_Year_ofCW_Short\", each Text.End(Text.From([Cal_Year_ofCW]), 2), type number),\n    /*\n    Returns a column with the Year and CW combined and prefixes included\n    eg. Year = 2022 and CW = 26 then value returned is \"Y22_CW26\"\n    */\n    SetYearAndCWColumn = let \n        TextCalendarYear = Table.AddColumn(GetThe2DigitValueOfYear, \"TextCalendarYear\", each \"Y\" & Text.End(Text.From([Cal_Year_ofCW]), 2), type number),\n        TextCalendarISOWeek = Table.AddColumn(TextCalendarYear, \"TextCalendarISOWeek\", each \"_CW\" & Text.End(Text.From([CALENDAR_ISO_WEEK]), 2), type number),\n        CombineYearAndISOWeek = Table.AddColumn(TextCalendarISOWeek, \"CALENDAR_Year_CWiso\", each Text.Combine({[TextCalendarYear], Text.From([TextCalendarISOWeek])}), type text),\n        ReturnCalendarYearCWIso = Table.RemoveColumns(CombineYearAndISOWeek,{\"TextCalendarYear\", \"TextCalendarISOWeek\"})\n        in ReturnCalendarYearCWIso,\n    /*\n    Returns a column with the Year x 100 and CW added together\n    eg. Year = 2024 and CW = 26 then value returned is 202426\n    */\n    SetCalYearAndCWIDColumn = let\n    MultiplyCalYearCWBy100 = Table.AddColumn(SetYearAndCWColumn, \"Cal_Year_ofCWx100\", each [Cal_Year_ofCW] * 100, type number),\n    AddtheWeekToTheMultipliedValue = Table.AddColumn(MultiplyCalYearCWBy100, \"Cal_Year_CWiso_ID\", each [Cal_Year_ofCWx100] + [CALENDAR_ISO_WEEK], type number),\n    TransformTheColumnTypes = Table.TransformColumnTypes(AddtheWeekToTheMultipliedValue,{{\"Cal_Year_CWiso_ID\", Int64.Type}, {\"Cal_Year_ofCWx100\", Int64.Type}, {\"Cal_Year_ofCW_Short\", Int64.Type}}),\n    ReturnCalYearId = Table.RemoveColumns(TransformTheColumnTypes,{\"Cal_Year_ofCWx100\"})\n    in \n        ReturnCalYearId,\n    AddPrefixToCalendarISOWeek = Table.AddColumn(SetCalYearAndCWIDColumn, \"Cal_CW\", each \"CW\" & Text.From([CALENDAR_ISO_WEEK]), type text),\n    KeepColumns = Table.SelectColumns(AddPrefixToCalendarISOWeek,{\"Period Set Name\", \"Calendar Day\", \"Fiscal Year Week\", \"Fiscal Week\", \"FISCAL_WEEK_DISP\", \"FISCAL_MONTH_SORT_VALUE\", \"FISCAL_QUARTER_DISP\", \"Fiscal Week No\", \"Fiscal Month Week No\", \"FISCAL_QTR_WEEK\", \"Fiscal Qtr Week No\", \"GL Period\", \"PQ_LAST_GL_PERIOD\", \"Period Year\", \"Fiscal Year\", \"Quarter No\", \"Fiscal Quarter\", \"Fiscal Year Quarter\", \"PRIOR_FYFQ\", \"PERIOD_NAME\", \"Period No\", \"Fiscal Day\", \"Week Start Date\", \"Week End Date\", \"Period Start Date\", \"Period End Date\", \"Quarter Start Date\", \"Quarter End Date\", \"Year Start Date\", \"Year End Date\", \"Fiscal Period Month\", \"FC_PERIOD_ID\", \"FC_QUARTER_ID\", \"FC_WEEK_ID\", \"FC_YEAR_OFFSET\", \"FC_QUARTER_OFFSET\", \"FC_PERIOD_OFFSET\", \"FC_WEEK_OFFSET\", \"FC_DAYS_OFFSET\", \"FC_HALF\", \"Next Quarter First Fiscal Week\", \"Prior Qtr Last Fiscal Week\", \"CALENDAR_YEAR\", \"CALENDAR_MONTH\", \"CALENDAR_YEARMONTHID\", \"CALENDAR_MONTHNAME\", \"CALENDAR_MONTHNAMESHORT\", \"CALENDAR_ISO_WEEK\", \"CALENDAR_US_WEEK\", \"CALENDAR_YEAR_SHORT\", \"CALENDAR_MTH_YEAR\", \"DAY_NAME\", \"DAY_OF_WEEK\", \"WORKING_DAY_FLAG\", \"CQ_LAST_FISCAL_WEEK\", \"Row Creation Date\", \"Week End Flag\", \"Month End Flag\", \"Quarter End Flag\", \"Year End Flag\", \"FISCAL_WEEK_INDICATOR\", \"FISCAL_WEEK_INDICATOR_SORT\", \"FISCAL_MONTH_INDICATOR\", \"FISCAL_MONTH_INDICATOR_SORT\", \"FISCAL_QUARTER_INDICATOR\", \"FISCAL_QUARTER_INDICATOR_SORT\", \"FISCAL_YEAR_INDICATOR\", \"FISCAL_YEAR_INDICATOR_SORT\", \"Refresh Date\", \"Start of Week\", \"Cal_Year_ofCW\", \"Cal_Year_ofCW_Short\", \"CALENDAR_Year_CWiso\", \"Cal_Year_CWiso_ID\", \"Cal_CW\"})\nin\n    KeepColumns;\r\nshared #\"FACT_LT Grouping Summary\" = let\n  Entity = GetEntityFromWorkspace(\"COHR_Dataflows\", \"INV_VELOCITY\", \"LT Grouping Summary\"),\n  FilterMaxNoOfRows = if pSetMaxRows > 0 then Table.FirstN(Entity, pSetMaxRows) else Entity,\n  FilterOrganization = if List.IsEmpty(Table.ToList(ListOfOrgs)) then Entity else Table.SelectRows(FilterMaxNoOfRows, each (List.Contains(List.Buffer(Table.ToList(ListOfOrgs)), [ORGANIZATION_CODE])))\nin\n  FilterOrganization;\r\nshared #\"FACT_Inventory Velocity Summary\" = let\n  Entity = GetEntityFromWorkspace(\"COHR_Dataflows\", \"INV_VELOCITY\", \"Inventory Velocity Summary\"),\n  FilterMaxNoOfRows = if pSetMaxRows > 0 then Table.FirstN(Entity, pSetMaxRows) else Entity,\n  FilterOrganization = if List.IsEmpty(Table.ToList(ListOfOrgs)) then Entity else Table.SelectRows(FilterMaxNoOfRows, each (List.Contains(List.Buffer(Table.ToList(ListOfOrgs)), [ORGANIZATION_CODE]))),\n  KeepListOfColumns = Table.SelectColumns(FilterOrganization,{\"ACTIVE_OR_INACTIVE\", \"CURRENT_MRP_ABC_CLASS\", \"DEMAND_SOURCE\", \"ENTITY\", \"FISCAL_WEEK_ID\", \"FISCAL_WEEK_KEY\", \"ITEM_PRODUCT_FAMILY\", \"ITEM_STATUS\", \"ITEM_TBU\", \"ITEM_TYPE\", \"ON_ORDER_DAYS_OF_SUPPLY\", \"ON_ORDER_DAYS_OF_SUPPLY_COUNT\", \"ON_ORDER_VALUE\", \"ON_ORDER_VALUE_USD\", \"ONHAND_DAYS_OF_SUPPLY\", \"ONHAND_VALUE\", \"ONHAND_VALUE_USD\", \"OPERATIONS_REPORTING\", \"ORGANIZATION_CODE\", \"PERIOD_END_DATE\", \"PERIOD_NAME\", \"PERIOD_YEAR\", \"PRODUCT_LINE\", \"PRODUCT_MAP_KEY\", \"RECORD_COUNT\", \"SAFETY_STOCK_VALUE\", \"SAFETY_STOCK_VALUE_USD\", \"SEC_REPORTING\", \"SUPPLY_SOURCE\", \"WEEK_END_DATE\", \"WEEK_START_DATE\", \"WIP_DAYS_OF_SUPPLY\", \"WIP_DAYS_OF_SUPPLY_COUNT\", \"WIP_VALUE\", \"WIP_VALUE_USD\"})\nin\n  KeepListOfColumns;\r\nshared #\"FACT_Inventory Velocity Details\" = let\n  Entity = GetEntityFromWorkspace(\"COHR_Dataflows\", \"INV_VELOCITY\", \"Inventory Velocity\"),\n  FilterMaxNoOfRows = if pSetMaxRows > 0 then Table.FirstN(Entity, pSetMaxRows) else Entity,\n  FilterOrganization = if List.IsEmpty(Table.ToList(ListOfOrgs)) then Entity else Table.SelectRows(FilterMaxNoOfRows, each (List.Contains(List.Buffer(Table.ToList(ListOfOrgs)), [ORGANIZATION_CODE]))),\n  KeepTheListOfColumns = Table.SelectColumns(FilterMaxNoOfRows,{\"ACTIVE_OR_INACTIVE\", \"ACTIVE_SUPPLIER_LT\", \"AVG_DAILY_DEMAND_ELSE_USAGE\", \"BLANKET_DAYS_SUPPLY_REMAINING\", \"CURRENT_ABC_CLASS\", \"DATE_RUN\", \"FISCAL_WEEK_KEY\", \"INTRANSIT_VALUE\", \"INVENTORY_VALUE\", \"INVENTORY_VALUE_USD\", \"ITEM_COST\", \"ITEM_COST_USD\", \"ITEM_DESCRIPTION\", \"ITEM_NUMBER\", \"ITEM_TYPE\", \"KANBAN_ITEM\", \"MIN_MAX_ITEM\", \"ON_HAND_DAYS_OF_SUPPLY\", \"ON_ORDER_DAYS_OF_SUPPLY\", \"ON_ORDER_VALUE_USD\", \"ONORDER_PO_QTY\", \"ONORDER_PO_VALUE\", \"ONORDER_PO_VALUE_USD\", \"OPEN_BLANKETS\", \"ORGANIZATION_CODE\", \"PLANNING_METHOD\", \"PROJ_SPEND_NEXT_26_WEEKS_USD\", \"SAFETY_STOCK_QTY\", \"SAFETY_STOCK_VALUE\", \"SAFETY_STOCK_VALUE_USD\", \"SEC_REPORTING\", \"SR_VNDR_SRC_ORG\", \"SUM_USD_REMAINING_AMOUNT\", \"TARGET_DAYS_OF_SUPPLY\", \"TARGET_DAYS_OF_SUPPLY_SAVINGS\", \"TARGET_DAYS_OF_SUPPLY_VALUE\", \"TOTAL_GR_26_WEEKS\", \"TOTAL_ONHAND_QTY\", \"WIP_DAYS_OF_SUPPLY\", \"WIP_IN_PROCESS_QTY\", \"WIP_IN_PROCESS_VALUE\", \"WIP_IN_PROCESS_VALUE_USD\"}),\n  SortTheColumns = Table.ReorderColumns(KeepTheListOfColumns,{\"ACTIVE_OR_INACTIVE\", \"ACTIVE_SUPPLIER_LT\", \"AVG_DAILY_DEMAND_ELSE_USAGE\", \"BLANKET_DAYS_SUPPLY_REMAINING\", \"CURRENT_ABC_CLASS\", \"DATE_RUN\", \"FISCAL_WEEK_KEY\", \"INTRANSIT_VALUE\", \"ITEM_COST\", \"ITEM_COST_USD\", \"ITEM_DESCRIPTION\", \"ITEM_NUMBER\", \"ITEM_TYPE\", \"KANBAN_ITEM\", \"MIN_MAX_ITEM\", \"OPEN_BLANKETS\", \"ON_HAND_DAYS_OF_SUPPLY\", \"ON_ORDER_DAYS_OF_SUPPLY\", \"ON_ORDER_VALUE_USD\", \"ONORDER_PO_QTY\", \"ONORDER_PO_VALUE\", \"ONORDER_PO_VALUE_USD\", \"ORGANIZATION_CODE\", \"PLANNING_METHOD\", \"SAFETY_STOCK_QTY\", \"SAFETY_STOCK_VALUE\", \"SAFETY_STOCK_VALUE_USD\", \"SEC_REPORTING\", \"SR_VNDR_SRC_ORG\", \"TARGET_DAYS_OF_SUPPLY\", \"TARGET_DAYS_OF_SUPPLY_SAVINGS\", \"TOTAL_GR_26_WEEKS\", \"TOTAL_ONHAND_QTY\", \"WIP_DAYS_OF_SUPPLY\", \"WIP_IN_PROCESS_QTY\", \"WIP_IN_PROCESS_VALUE\", \"WIP_IN_PROCESS_VALUE_USD\"}),\n  FillEmptyCellValuesWithZero = Table.ReplaceValue(SortTheColumns,\"\",\"0\",Replacer.ReplaceValue,{\"OPEN_BLANKETS\"}),\n  ConvertColumnsToInt = Table.TransformColumnTypes(FillEmptyCellValuesWithZero,{{\"KANBAN_ITEM\", Int64.Type}, {\"MIN_MAX_ITEM\", Int64.Type}, {\"OPEN_BLANKETS\", Int64.Type}})\nin\n  ConvertColumnsToInt;\r\nshared #\"DIM_Sort Values\" = let\r\n  Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"jZPbToQwEIZfZcKVJuvFuuvh1oAHorAI62pC9mKErhLJlJR2lbcXt6HRWA6XdL5/Ot80pKlzj/SK5MycqESigt4gYPKd5+3J3NnOUico6CTALytxqok4gq5mxRYHLORSYyy3UkvTDCkHb6zpmcGvMlnsWXvk056R5KKBRKJUtXFYv4SDlPbwww34hAOcFlkRrETOBHjY1MB3kKiqKpu2HjCslWDwqJBkIRtj1RMBlyuS9qD2e/ajSdec99BDN1x0o90dFj7hlss/iQ2WisHRU+Id/8JdJQSjrDHLN+6jvH6GBHdM/iydZx/jmYURH0WXtukfeIalofpE7CbTsv1W0/L/DKfFtO3Nrd9+JNcuxKziQuq/ad61tNT0uDF+WmrtKNtv\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Value = _t, Type = _t, #\"Sort Order\" = _t]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(Source, {{\"Value\", type text}, {\"Type\", type text}, {\"Sort Order\", Int64.Type}})\r\nin\r\n  #\"Changed column type\";\r\nshared #\"Version History Dataflow\" = let\n    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"NY0xD4IwFAb/ypfOQApRB1eNiZs7YXiWh75Y2qZ9hL8vGh3vhru+N21jG2sq09muq+2+bg9od0f7UafoJeDG5KJ7bXwNokIeykVxJqXJxxUuMymPWEWfuJBTKN09lwqjzByKxPAzoDAiUaaZlXNBYa2XhCnmb1LCA2nJKRYu2+0/MMPwBg==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Version Number\" = _t, #\"Revision Date/Time\" = _t, #\"Developer Name\" = _t, #\"Revision Notes\" = _t, #\"Revision Type\" = _t]),\n    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Version Number\", type text}, {\"Revision Date/Time\", type datetime}, {\"Developer Name\", type text}, {\"Revision Notes\", type text}, {\"Revision Type\", type text}})\nin\n    #\"Changed Type\";\r\nshared INFO_DataUpdateInfoInventoryVelocity = let\n  Entity = GetEntityFromWorkspace(\"COHR_Dataflows\", \"INV_VELOCITY\", \"Data Update Info\")\nin\n  Entity;\r\n"
    },
    "annotations": [
        {
            "name": "pbi:QueryGroups",
            "value": "[{\"id\":\"7363d107-1f3d-48de-be9c-f033354d282e\",\"name\":\"GetEntity\",\"description\":null,\"parentId\":null,\"order\":0},{\"id\":\"5bac1fbe-fe1d-4da2-94f5-070ea55ef66f\",\"name\":\"Parameters\",\"description\":\"\",\"parentId\":null,\"order\":1},{\"id\":\"bbd6ee21-6a56-4a8c-b80f-2aad18bde5a6\",\"name\":\"Facts - Inventory Turns\",\"description\":\"\",\"parentId\":null,\"order\":2},{\"id\":\"a0966e5b-d860-4160-b742-7c26403daafe\",\"name\":\"Dimensions\",\"description\":\"\",\"parentId\":null,\"order\":4},{\"id\":\"a91191ed-8efb-400b-bad7-2b8a42e2d413\",\"name\":\"Versioning\",\"description\":\"\",\"parentId\":null,\"order\":5},{\"id\":\"350542b3-0fe5-4a8f-9abf-594bb26638d7\",\"name\":\"Facts - Inventory Velocity\",\"description\":\"\",\"parentId\":null,\"order\":3},{\"id\":\"d535d7f0-f50c-47a1-a1c5-b52444b9ad0e\",\"name\":\"Information\",\"description\":\"Data Update Information for the Inventory Velocity Tables\",\"parentId\":null,\"order\":0}]"
        }
    ],
    "entities": [
        {
            "$type": "LocalEntity",
            "name": "FACT_M20Detail",
            "description": "",
            "pbi:refreshPolicy": {
                "$type": "FullRefreshPolicy",
                "location": "FACT_M20Detail.csv"
            },
            "attributes": [
                {
                    "name": "ENTITY",
                    "dataType": "string"
                },
                {
                    "name": "DEPT",
                    "dataType": "string"
                },
                {
                    "name": "ACCT",
                    "dataType": "string"
                },
                {
                    "name": "PROJ",
                    "dataType": "string"
                },
                {
                    "name": "M20_TBU",
                    "dataType": "string"
                },
                {
                    "name": "M20_PFC",
                    "dataType": "string"
                },
                {
                    "name": "INTERCO",
                    "dataType": "string"
                },
                {
                    "name": "ACCOUNT_DESC",
                    "dataType": "string"
                },
                {
                    "name": "GL_PERIOD",
                    "dataType": "date"
                },
                {
                    "name": "TRANS_DATE",
                    "dataType": "date"
                },
                {
                    "name": "TRANS_TIME",
                    "dataType": "time"
                },
                {
                    "name": "TRAN_QTY",
                    "dataType": "string"
                },
                {
                    "name": "ACCOUNTED_DR",
                    "dataType": "double"
                },
                {
                    "name": "ACCOUNTED_CR",
                    "dataType": "double"
                },
                {
                    "name": "NET_ACCOUNTED_AMT",
                    "dataType": "double"
                },
                {
                    "name": "ACCOUNTED_NET_USD",
                    "dataType": "double"
                }
            ]
        },
        {
            "$type": "LocalEntity",
            "name": "FACT_InventoryValue",
            "description": "",
            "pbi:refreshPolicy": {
                "$type": "FullRefreshPolicy",
                "location": "FACT_InventoryValue.csv"
            },
            "attributes": [
                {
                    "name": "INV_ORG_ID",
                    "dataType": "int64"
                },
                {
                    "name": "INVENTORY_ITEM_ID",
                    "dataType": "int64"
                },
                {
                    "name": "ITEM_ORG_ID_KEY",
                    "dataType": "string"
                },
                {
                    "name": "ITEM_ORG_CODE_KEY",
                    "dataType": "string"
                },
                {
                    "name": "OPERATING_UNIT_ID",
                    "dataType": "int64"
                },
                {
                    "name": "ITEM_NUMBER",
                    "dataType": "string"
                },
                {
                    "name": "ITEM_TBU",
                    "dataType": "string"
                },
                {
                    "name": "ITEM_PRODUCT_FAMILY",
                    "dataType": "string"
                },
                {
                    "name": "SOURCE_TYPE",
                    "dataType": "string"
                },
                {
                    "name": "SUBINVENTORY_CODE",
                    "dataType": "string"
                },
                {
                    "name": "SUBINVENTORY_TYPE",
                    "dataType": "string"
                },
                {
                    "name": "ORGANIZATION_CODE",
                    "dataType": "string"
                },
                {
                    "name": "ENTITY",
                    "dataType": "int64"
                },
                {
                    "name": "ACCOUNT",
                    "dataType": "int64"
                },
                {
                    "name": "FIN_ENTITY",
                    "dataType": "int64"
                },
                {
                    "name": "INV_QUANTITY",
                    "dataType": "int64"
                },
                {
                    "name": "INV_BALANCE",
                    "dataType": "int64"
                },
                {
                    "name": "INV_VALUE",
                    "dataType": "double"
                },
                {
                    "name": "INV_VALUE_USD",
                    "dataType": "double"
                },
                {
                    "name": "CURRENCY_CODE",
                    "dataType": "string"
                },
                {
                    "name": "CURRENCY_RATE",
                    "dataType": "double"
                },
                {
                    "name": "ITEM_COST",
                    "dataType": "double"
                },
                {
                    "name": "MATERIAL_COST",
                    "dataType": "double"
                },
                {
                    "name": "MATERIAL_OVERHEAD_COST",
                    "dataType": "double"
                },
                {
                    "name": "OUTSIDE_PROCESSING_COST",
                    "dataType": "double"
                },
                {
                    "name": "OVERHEAD_COST",
                    "dataType": "double"
                },
                {
                    "name": "RESOURCE_COST",
                    "dataType": "double"
                },
                {
                    "name": "TOTAL_COST",
                    "dataType": "double"
                },
                {
                    "name": "FISCAL_YEAR_ID",
                    "dataType": "int64"
                },
                {
                    "name": "VALID_FLAG",
                    "dataType": "string"
                },
                {
                    "name": "COMMENTS",
                    "dataType": "string"
                },
                {
                    "name": "CREATION_DATE",
                    "dataType": "date"
                },
                {
                    "name": "CREATED_BY",
                    "dataType": "int64"
                },
                {
                    "name": "FISCAL_WEEK_ID",
                    "dataType": "int64"
                },
                {
                    "name": "FISCAL_WEEK",
                    "dataType": "string"
                },
                {
                    "name": "JE_SOURCE_CATEGORY",
                    "dataType": "string"
                },
                {
                    "name": "OPERATIONS_REPORTING",
                    "dataType": "string"
                },
                {
                    "name": "CS_DEMAND_SOURCE",
                    "dataType": "string"
                },
                {
                    "name": "CS_SUPPLY_SOURCE",
                    "dataType": "string"
                },
                {
                    "name": "ITEM_TYPE_CODE",
                    "dataType": "string"
                },
                {
                    "name": "EXCLUDE_FLAG",
                    "dataType": "string"
                },
                {
                    "name": "EXCLUDE_COMMENT",
                    "dataType": "string"
                },
                {
                    "name": "WIP_CLASS",
                    "dataType": "string"
                },
                {
                    "name": "WIP_CLASS_CODE",
                    "dataType": "int64"
                },
                {
                    "name": "ITEM_TYPE",
                    "dataType": "string"
                },
                {
                    "name": "PLANNER_CODE",
                    "dataType": "string"
                },
                {
                    "name": "MAKE_BUY",
                    "dataType": "string"
                },
                {
                    "name": "ITEM_STATUS",
                    "dataType": "string"
                },
                {
                    "name": "ABC_CLASS",
                    "dataType": "string"
                },
                {
                    "name": "INV_STATUS",
                    "dataType": "string"
                },
                {
                    "name": "WIP_JOB_ID",
                    "dataType": "int64"
                },
                {
                    "name": "ITEM_PRODUCT_LINE",
                    "dataType": "string"
                },
                {
                    "name": "ITEM_FORECAST_FIELD",
                    "dataType": "string"
                },
                {
                    "name": "ITEM_DESC",
                    "dataType": "string"
                },
                {
                    "name": "WIP_JOB_NO",
                    "dataType": "string"
                },
                {
                    "name": "ITEM_COST_USD",
                    "dataType": "int64"
                },
                {
                    "name": "ORA_PRODUCT_LINE",
                    "dataType": "string"
                },
                {
                    "name": "CONC_REQ_ID",
                    "dataType": "int64"
                },
                {
                    "name": "FIN_PRODUCT_LINE",
                    "dataType": "string"
                },
                {
                    "name": "ORA_FORECAST_FIELD",
                    "dataType": "string"
                },
                {
                    "name": "ORG_TBU",
                    "dataType": "string"
                },
                {
                    "name": "ORG_PRODUCT_FAMILY",
                    "dataType": "string"
                },
                {
                    "name": "ORG_PRODUCT_LINE",
                    "dataType": "string"
                },
                {
                    "name": "ORG_FORECAST_FIELD",
                    "dataType": "string"
                },
                {
                    "name": "ORG_CATEGORY_ID",
                    "dataType": "int64"
                },
                {
                    "name": "PRODUCT_MAP_KEY",
                    "dataType": "string"
                },
                {
                    "name": "FIN_TBU",
                    "dataType": "string"
                },
                {
                    "name": "FIN_PFC",
                    "dataType": "string"
                },
                {
                    "name": "WEEK_START_DATE",
                    "dataType": "dateTime"
                },
                {
                    "name": "WEEK_END_DATE",
                    "dataType": "dateTime"
                },
                {
                    "name": "PERIOD_START_DATE",
                    "dataType": "dateTime"
                },
                {
                    "name": "PERIOD_END_DATE",
                    "dataType": "dateTime"
                },
                {
                    "name": "QUARTER_START_DATE",
                    "dataType": "dateTime"
                },
                {
                    "name": "QUARTER_END_DATE",
                    "dataType": "dateTime"
                },
                {
                    "name": "FISCAL_QUARTER",
                    "dataType": "string"
                },
                {
                    "name": "FISCAL_YEAR",
                    "dataType": "string"
                },
                {
                    "name": "MGT_PRODUCT_GROUP",
                    "dataType": "string"
                },
                {
                    "name": "MGT_SUB_PRODUCT_GROUP",
                    "dataType": "string"
                },
                {
                    "name": "BUSINESS_SEGMENT",
                    "dataType": "string"
                },
                {
                    "name": "ACCOUNT_NAME",
                    "dataType": "string"
                },
                {
                    "name": "ACCOUNT_DESC",
                    "dataType": "string"
                },
                {
                    "name": "ACCOUNT_TYPE",
                    "dataType": "string"
                },
                {
                    "name": "ACCOUNT_SUB_GROUP",
                    "dataType": "string"
                },
                {
                    "name": "ACCOUNT_GROUP",
                    "dataType": "string"
                },
                {
                    "name": "SUMMARY_ACCOUNT",
                    "dataType": "string"
                },
                {
                    "name": "INVVALUE_KEY",
                    "dataType": "string"
                },
                {
                    "name": "CREATION_TIME",
                    "dataType": "time"
                }
            ]
        },
        {
            "$type": "LocalEntity",
            "name": "FACT_M20DetailAll",
            "description": "",
            "pbi:refreshPolicy": {
                "$type": "FullRefreshPolicy",
                "location": "FACT_M20DetailAll.csv"
            },
            "attributes": [
                {
                    "name": "ENTITY",
                    "dataType": "string"
                },
                {
                    "name": "DEPT",
                    "dataType": "string"
                },
                {
                    "name": "ACCT",
                    "dataType": "string"
                },
                {
                    "name": "PROJ",
                    "dataType": "string"
                },
                {
                    "name": "M20_TBU",
                    "dataType": "string"
                },
                {
                    "name": "M20_PFC",
                    "dataType": "string"
                },
                {
                    "name": "INTERCO",
                    "dataType": "string"
                },
                {
                    "name": "ACCOUNT_DESC",
                    "dataType": "string"
                },
                {
                    "name": "GL_PERIOD",
                    "dataType": "date"
                },
                {
                    "name": "TRANS_DATE",
                    "dataType": "date"
                },
                {
                    "name": "TRAN_QTY",
                    "dataType": "string"
                },
                {
                    "name": "ACCOUNTED_DR",
                    "dataType": "double"
                },
                {
                    "name": "ACCOUNTED_CR",
                    "dataType": "double"
                },
                {
                    "name": "NET_ACCOUNTED_AMT",
                    "dataType": "double"
                },
                {
                    "name": "ACCOUNTED_NET_USD",
                    "dataType": "double"
                },
                {
                    "name": "TRANS_TIME",
                    "dataType": "time"
                }
            ]
        },
        {
            "$type": "LocalEntity",
            "name": "FACT_M20Detail_Flow",
            "description": "",
            "pbi:refreshPolicy": {
                "$type": "FullRefreshPolicy",
                "location": "FACT_M20Detail_Flow.csv"
            },
            "attributes": [
                {
                    "name": "ENTITY",
                    "dataType": "string"
                },
                {
                    "name": "DEPT",
                    "dataType": "string"
                },
                {
                    "name": "ACCT",
                    "dataType": "string"
                },
                {
                    "name": "PROJ",
                    "dataType": "string"
                },
                {
                    "name": "INTERCO",
                    "dataType": "string"
                },
                {
                    "name": "ACCOUNT_DESC",
                    "dataType": "string"
                },
                {
                    "name": "GL_PERIOD",
                    "dataType": "string"
                },
                {
                    "name": "PERIOD_START_DATE",
                    "dataType": "dateTime"
                },
                {
                    "name": "PERIOD_END_DATE",
                    "dataType": "dateTime"
                },
                {
                    "name": "ITEM_NUMBER",
                    "dataType": "string"
                },
                {
                    "name": "ITEM_DESCRIPTION",
                    "dataType": "string"
                },
                {
                    "name": "TRANSACTION_SOURCE",
                    "dataType": "string"
                },
                {
                    "name": "TRANS_DATE",
                    "dataType": "dateTime"
                },
                {
                    "name": "ACCOUNTED_DR",
                    "dataType": "double"
                },
                {
                    "name": "ACCOUNTED_CR",
                    "dataType": "double"
                },
                {
                    "name": "NET_ACCOUNTED_AMT",
                    "dataType": "double"
                },
                {
                    "name": "ACCOUNTED_NET_USD",
                    "dataType": "double"
                },
                {
                    "name": "CURRENCY_CODE",
                    "dataType": "string"
                },
                {
                    "name": "VENDOR_NAME",
                    "dataType": "string"
                },
                {
                    "name": "VENDOR_NUMBER",
                    "dataType": "string"
                },
                {
                    "name": "ORDER_LINE_TYPE",
                    "dataType": "string"
                },
                {
                    "name": "ORDER_NUMBER",
                    "dataType": "double"
                },
                {
                    "name": "TRX_TYPE_NAME",
                    "dataType": "string"
                },
                {
                    "name": "ORDER_TYPE",
                    "dataType": "string"
                },
                {
                    "name": "SALES_SERVICE_CODE",
                    "dataType": "string"
                },
                {
                    "name": "TRAN_QTY",
                    "dataType": "double"
                },
                {
                    "name": "TRX_NUMBER",
                    "dataType": "string"
                },
                {
                    "name": "EXTERNAL_SO_NUMBER",
                    "dataType": "double"
                },
                {
                    "name": "EXTERNAL_CUSTOMER",
                    "dataType": "string"
                },
                {
                    "name": "WIP_JOB_NO",
                    "dataType": "string"
                },
                {
                    "name": "PERIOD_YEAR",
                    "dataType": "double"
                },
                {
                    "name": "PO_NUMBER",
                    "dataType": "string"
                },
                {
                    "name": "JE_NAME",
                    "dataType": "string"
                },
                {
                    "name": "JE_LINE_NUM",
                    "dataType": "double"
                },
                {
                    "name": "INTERNAL_PO_NUMBER",
                    "dataType": "double"
                },
                {
                    "name": "COMMODITY_CATEGORY",
                    "dataType": "string"
                },
                {
                    "name": "FORECAST_CATEGORY",
                    "dataType": "string"
                },
                {
                    "name": "SUBINVENTORY_CODE",
                    "dataType": "string"
                },
                {
                    "name": "ACCOUNT_ALIAS_NAME",
                    "dataType": "string"
                },
                {
                    "name": "PLANNER_CODE",
                    "dataType": "string"
                },
                {
                    "name": "BUYER_ID",
                    "dataType": "double"
                },
                {
                    "name": "ACCOUNTING_LINE_TYPE",
                    "dataType": "string"
                },
                {
                    "name": "TRAN_SOURCE_NAME",
                    "dataType": "string"
                },
                {
                    "name": "MATERAIL_TRAN_REFERENCE",
                    "dataType": "string"
                },
                {
                    "name": "JE_LINE_DESCRIPTION",
                    "dataType": "string"
                },
                {
                    "name": "CREATION_DATE",
                    "dataType": "dateTime"
                },
                {
                    "name": "WIP_ACCOUNTING_CLASS",
                    "dataType": "string"
                },
                {
                    "name": "ALLOCATION_PERCENT",
                    "dataType": "double"
                },
                {
                    "name": "MARKET_CODE",
                    "dataType": "string"
                },
                {
                    "name": "ITEM_TBU",
                    "dataType": "string"
                },
                {
                    "name": "ITEM_PFC",
                    "dataType": "string"
                },
                {
                    "name": "ITEM_PRODUCT_LINE",
                    "dataType": "string"
                },
                {
                    "name": "ITEM_ORG_TBU",
                    "dataType": "string"
                },
                {
                    "name": "ITEM_ORG_PFC",
                    "dataType": "string"
                },
                {
                    "name": "M20_TBU",
                    "dataType": "string"
                },
                {
                    "name": "M20_PFC",
                    "dataType": "string"
                },
                {
                    "name": "HFM_PRODUCT",
                    "dataType": "string"
                },
                {
                    "name": "ALT_HFM_PRODUCT",
                    "dataType": "string"
                },
                {
                    "name": "COST_ELEMENT",
                    "dataType": "string"
                },
                {
                    "name": "TRANS_DIFF_START",
                    "dataType": "double"
                },
                {
                    "name": "MONTH_DAYS",
                    "dataType": "double"
                },
                {
                    "name": "REV_TRANS_DATE",
                    "dataType": "dateTime"
                },
                {
                    "name": "M2_DETAIL_KEY",
                    "dataType": "string"
                }
            ]
        },
        {
            "$type": "LocalEntity",
            "name": "DIM_Time Balance Week",
            "description": "",
            "pbi:refreshPolicy": {
                "$type": "FullRefreshPolicy",
                "location": "DIM_Time%20Balance%20Week.csv"
            },
            "attributes": [
                {
                    "name": "FISCAL_PERIOD_KEY",
                    "dataType": "string"
                },
                {
                    "name": "FISCAL_DIM_ID",
                    "dataType": "double"
                },
                {
                    "name": "FISCAL_DIM",
                    "dataType": "string"
                },
                {
                    "name": "FISCAL_DIM_VALUE",
                    "dataType": "string"
                },
                {
                    "name": "FISCAL_DIM_SORT_VALUE",
                    "dataType": "string"
                },
                {
                    "name": "FC_YEAR_OFFSET",
                    "dataType": "double"
                },
                {
                    "name": "FC_QUARTER_OFFSET",
                    "dataType": "double"
                },
                {
                    "name": "FISCAL_YEAR",
                    "dataType": "string"
                },
                {
                    "name": "FYFQ",
                    "dataType": "string"
                },
                {
                    "name": "PERIOD_YEAR",
                    "dataType": "double"
                },
                {
                    "name": "GL_PERIOD",
                    "dataType": "string"
                },
                {
                    "name": "FISCAL_WEEK_ID",
                    "dataType": "double"
                }
            ]
        },
        {
            "$type": "LocalEntity",
            "name": "DIM_Financial Product Mapping",
            "description": "",
            "pbi:refreshPolicy": {
                "$type": "FullRefreshPolicy",
                "location": "DIM_Financial%20Product%20Mapping.csv"
            },
            "attributes": [
                {
                    "name": "Record Id",
                    "dataType": "double"
                },
                {
                    "name": "ENTITY",
                    "dataType": "string"
                },
                {
                    "name": "TBU",
                    "dataType": "string"
                },
                {
                    "name": "PFC",
                    "dataType": "string"
                },
                {
                    "name": "FIN_TBU",
                    "dataType": "string"
                },
                {
                    "name": "FIN_PFC",
                    "dataType": "string"
                },
                {
                    "name": "PRODUCT_SEGMENT",
                    "dataType": "string"
                },
                {
                    "name": "HFM_PRODUCT_SEQ",
                    "dataType": "double"
                },
                {
                    "name": "PRODUCT_MAP_ID",
                    "dataType": "double"
                },
                {
                    "name": "COMMENTS",
                    "dataType": "string"
                },
                {
                    "name": "CREATION_DATE",
                    "dataType": "dateTime"
                },
                {
                    "name": "ROW_CREATION_DATE",
                    "dataType": "dateTime"
                },
                {
                    "name": "FIN_DEFAULT_FORECAST_FIELD",
                    "dataType": "string"
                },
                {
                    "name": "PRODUCT_MAP_KEY",
                    "dataType": "string"
                }
            ]
        },
        {
            "$type": "LocalEntity",
            "name": "DIM_GL Account Segment",
            "description": "",
            "pbi:refreshPolicy": {
                "$type": "FullRefreshPolicy",
                "location": "DIM_GL%20Account%20Segment.csv"
            },
            "attributes": [
                {
                    "name": "Account Code",
                    "dataType": "string"
                },
                {
                    "name": "Account Name",
                    "dataType": "string"
                },
                {
                    "name": "Account Description",
                    "dataType": "string"
                },
                {
                    "name": "Enabled Flag",
                    "dataType": "string"
                },
                {
                    "name": "Account Type",
                    "dataType": "string"
                },
                {
                    "name": "Active Start Date",
                    "dataType": "dateTime"
                },
                {
                    "name": "Active End Date",
                    "dataType": "dateTime"
                },
                {
                    "name": "Creation Date",
                    "dataType": "dateTime"
                },
                {
                    "name": "Last Update Date",
                    "dataType": "dateTime"
                },
                {
                    "name": "Created By Login",
                    "dataType": "string"
                },
                {
                    "name": "Last Update By Login",
                    "dataType": "string"
                },
                {
                    "name": "Account Sub Group",
                    "dataType": "string"
                },
                {
                    "name": "Account Group",
                    "dataType": "string"
                },
                {
                    "name": "Summary Account",
                    "dataType": "string"
                },
                {
                    "name": "Summary Multiplier",
                    "dataType": "double"
                }
            ]
        },
        {
            "$type": "LocalEntity",
            "name": "DIM_GL Code Combinations",
            "description": "",
            "pbi:refreshPolicy": {
                "$type": "FullRefreshPolicy",
                "location": "DIM_GL%20Code%20Combinations.csv"
            },
            "attributes": [
                {
                    "name": "CODE_COMBINATION_ID",
                    "dataType": "string"
                },
                {
                    "name": "LAST_UPDATE_DATE",
                    "dataType": "dateTime"
                },
                {
                    "name": "LAST_UPDATED_BY",
                    "dataType": "string"
                },
                {
                    "name": "CHART_OF_ACCOUNTS_ID",
                    "dataType": "double"
                },
                {
                    "name": "DETAIL_POSTING_ALLOWED_FLAG",
                    "dataType": "string"
                },
                {
                    "name": "DETAIL_BUDGETING_ALLOWED_FLAG",
                    "dataType": "string"
                },
                {
                    "name": "ACCOUNT_TYPE",
                    "dataType": "string"
                },
                {
                    "name": "ENABLED_FLAG",
                    "dataType": "string"
                },
                {
                    "name": "SUMMARY_FLAG",
                    "dataType": "string"
                },
                {
                    "name": "SEGMENT1",
                    "dataType": "string"
                },
                {
                    "name": "SEGMENT2",
                    "dataType": "string"
                },
                {
                    "name": "SEGMENT3",
                    "dataType": "string"
                },
                {
                    "name": "SEGMENT4",
                    "dataType": "string"
                },
                {
                    "name": "SEGMENT5",
                    "dataType": "string"
                },
                {
                    "name": "SEGMENT6",
                    "dataType": "string"
                },
                {
                    "name": "SEGMENT7",
                    "dataType": "string"
                },
                {
                    "name": "SEGMENT8",
                    "dataType": "string"
                },
                {
                    "name": "SEGMENT9",
                    "dataType": "string"
                },
                {
                    "name": "SEGMENT10",
                    "dataType": "string"
                },
                {
                    "name": "SEGMENT11",
                    "dataType": "string"
                },
                {
                    "name": "SEGMENT12",
                    "dataType": "string"
                },
                {
                    "name": "SEGMENT13",
                    "dataType": "string"
                },
                {
                    "name": "SEGMENT14",
                    "dataType": "string"
                },
                {
                    "name": "SEGMENT15",
                    "dataType": "string"
                },
                {
                    "name": "SEGMENT16",
                    "dataType": "string"
                },
                {
                    "name": "SEGMENT17",
                    "dataType": "string"
                },
                {
                    "name": "SEGMENT18",
                    "dataType": "string"
                },
                {
                    "name": "SEGMENT19",
                    "dataType": "string"
                },
                {
                    "name": "SEGMENT20",
                    "dataType": "string"
                },
                {
                    "name": "SEGMENT21",
                    "dataType": "string"
                },
                {
                    "name": "SEGMENT22",
                    "dataType": "string"
                },
                {
                    "name": "SEGMENT23",
                    "dataType": "string"
                },
                {
                    "name": "SEGMENT24",
                    "dataType": "string"
                },
                {
                    "name": "SEGMENT25",
                    "dataType": "string"
                },
                {
                    "name": "SEGMENT26",
                    "dataType": "string"
                },
                {
                    "name": "SEGMENT27",
                    "dataType": "string"
                },
                {
                    "name": "SEGMENT28",
                    "dataType": "string"
                },
                {
                    "name": "SEGMENT29",
                    "dataType": "string"
                },
                {
                    "name": "SEGMENT30",
                    "dataType": "string"
                },
                {
                    "name": "DESCRIPTION",
                    "dataType": "string"
                },
                {
                    "name": "TEMPLATE_ID",
                    "dataType": "double"
                },
                {
                    "name": "ALLOCATION_CREATE_FLAG",
                    "dataType": "string"
                },
                {
                    "name": "START_DATE_ACTIVE",
                    "dataType": "dateTime"
                },
                {
                    "name": "END_DATE_ACTIVE",
                    "dataType": "dateTime"
                },
                {
                    "name": "ATTRIBUTE1",
                    "dataType": "string"
                },
                {
                    "name": "ATTRIBUTE2",
                    "dataType": "string"
                },
                {
                    "name": "ATTRIBUTE3",
                    "dataType": "string"
                },
                {
                    "name": "ATTRIBUTE4",
                    "dataType": "string"
                },
                {
                    "name": "ATTRIBUTE5",
                    "dataType": "string"
                },
                {
                    "name": "ATTRIBUTE6",
                    "dataType": "string"
                },
                {
                    "name": "ATTRIBUTE7",
                    "dataType": "string"
                },
                {
                    "name": "ATTRIBUTE8",
                    "dataType": "string"
                },
                {
                    "name": "ATTRIBUTE9",
                    "dataType": "string"
                },
                {
                    "name": "ATTRIBUTE10",
                    "dataType": "string"
                },
                {
                    "name": "CONTEXT",
                    "dataType": "string"
                },
                {
                    "name": "SEGMENT_ATTRIBUTE1",
                    "dataType": "string"
                },
                {
                    "name": "SEGMENT_ATTRIBUTE2",
                    "dataType": "string"
                },
                {
                    "name": "SEGMENT_ATTRIBUTE3",
                    "dataType": "string"
                },
                {
                    "name": "SEGMENT_ATTRIBUTE4",
                    "dataType": "string"
                },
                {
                    "name": "SEGMENT_ATTRIBUTE5",
                    "dataType": "string"
                },
                {
                    "name": "SEGMENT_ATTRIBUTE6",
                    "dataType": "string"
                },
                {
                    "name": "SEGMENT_ATTRIBUTE7",
                    "dataType": "string"
                },
                {
                    "name": "SEGMENT_ATTRIBUTE8",
                    "dataType": "string"
                },
                {
                    "name": "SEGMENT_ATTRIBUTE9",
                    "dataType": "string"
                },
                {
                    "name": "SEGMENT_ATTRIBUTE10",
                    "dataType": "string"
                },
                {
                    "name": "SEGMENT_ATTRIBUTE11",
                    "dataType": "string"
                },
                {
                    "name": "SEGMENT_ATTRIBUTE12",
                    "dataType": "string"
                },
                {
                    "name": "SEGMENT_ATTRIBUTE13",
                    "dataType": "string"
                },
                {
                    "name": "SEGMENT_ATTRIBUTE14",
                    "dataType": "string"
                },
                {
                    "name": "SEGMENT_ATTRIBUTE15",
                    "dataType": "string"
                },
                {
                    "name": "SEGMENT_ATTRIBUTE16",
                    "dataType": "string"
                },
                {
                    "name": "SEGMENT_ATTRIBUTE17",
                    "dataType": "string"
                },
                {
                    "name": "SEGMENT_ATTRIBUTE18",
                    "dataType": "string"
                },
                {
                    "name": "SEGMENT_ATTRIBUTE19",
                    "dataType": "string"
                },
                {
                    "name": "SEGMENT_ATTRIBUTE20",
                    "dataType": "string"
                },
                {
                    "name": "SEGMENT_ATTRIBUTE21",
                    "dataType": "string"
                },
                {
                    "name": "SEGMENT_ATTRIBUTE22",
                    "dataType": "string"
                },
                {
                    "name": "SEGMENT_ATTRIBUTE23",
                    "dataType": "string"
                },
                {
                    "name": "SEGMENT_ATTRIBUTE24",
                    "dataType": "string"
                },
                {
                    "name": "SEGMENT_ATTRIBUTE25",
                    "dataType": "string"
                },
                {
                    "name": "SEGMENT_ATTRIBUTE26",
                    "dataType": "string"
                },
                {
                    "name": "SEGMENT_ATTRIBUTE27",
                    "dataType": "string"
                },
                {
                    "name": "SEGMENT_ATTRIBUTE28",
                    "dataType": "string"
                },
                {
                    "name": "SEGMENT_ATTRIBUTE29",
                    "dataType": "string"
                },
                {
                    "name": "SEGMENT_ATTRIBUTE30",
                    "dataType": "string"
                },
                {
                    "name": "SEGMENT_ATTRIBUTE31",
                    "dataType": "string"
                },
                {
                    "name": "SEGMENT_ATTRIBUTE32",
                    "dataType": "string"
                },
                {
                    "name": "SEGMENT_ATTRIBUTE33",
                    "dataType": "string"
                },
                {
                    "name": "SEGMENT_ATTRIBUTE34",
                    "dataType": "string"
                },
                {
                    "name": "SEGMENT_ATTRIBUTE35",
                    "dataType": "string"
                },
                {
                    "name": "SEGMENT_ATTRIBUTE36",
                    "dataType": "string"
                },
                {
                    "name": "SEGMENT_ATTRIBUTE37",
                    "dataType": "string"
                },
                {
                    "name": "SEGMENT_ATTRIBUTE38",
                    "dataType": "string"
                },
                {
                    "name": "SEGMENT_ATTRIBUTE39",
                    "dataType": "string"
                },
                {
                    "name": "SEGMENT_ATTRIBUTE40",
                    "dataType": "string"
                },
                {
                    "name": "SEGMENT_ATTRIBUTE41",
                    "dataType": "string"
                },
                {
                    "name": "SEGMENT_ATTRIBUTE42",
                    "dataType": "string"
                },
                {
                    "name": "REFERENCE1",
                    "dataType": "string"
                },
                {
                    "name": "REFERENCE2",
                    "dataType": "string"
                },
                {
                    "name": "REFERENCE3",
                    "dataType": "string"
                },
                {
                    "name": "REFERENCE4",
                    "dataType": "string"
                },
                {
                    "name": "REFERENCE5",
                    "dataType": "string"
                },
                {
                    "name": "JGZZ_RECON_FLAG",
                    "dataType": "string"
                },
                {
                    "name": "JGZZ_RECON_CONTEXT",
                    "dataType": "string"
                },
                {
                    "name": "PRESERVE_FLAG",
                    "dataType": "string"
                },
                {
                    "name": "REFRESH_FLAG",
                    "dataType": "string"
                },
                {
                    "name": "IGI_BALANCED_BUDGET_FLAG",
                    "dataType": "string"
                },
                {
                    "name": "COMPANY_COST_CENTER_ORG_ID",
                    "dataType": "double"
                },
                {
                    "name": "REVALUATION_ID",
                    "dataType": "double"
                },
                {
                    "name": "LEDGER_SEGMENT",
                    "dataType": "string"
                },
                {
                    "name": "LEDGER_TYPE_CODE",
                    "dataType": "string"
                },
                {
                    "name": "ALTERNATE_CODE_COMBINATION_ID",
                    "dataType": "double"
                }
            ]
        },
        {
            "$type": "LocalEntity",
            "name": "DIM_GL Code Combinations Desc",
            "description": "",
            "pbi:refreshPolicy": {
                "$type": "FullRefreshPolicy",
                "location": "DIM_GL%20Code%20Combinations%20Desc.csv"
            },
            "attributes": [
                {
                    "name": "CODE_COMBINATION_ID",
                    "dataType": "double"
                },
                {
                    "name": "LAST_UPDATE_DATE",
                    "dataType": "dateTime"
                },
                {
                    "name": "DETAIL_POSTING_ALLOWED_FLAG",
                    "dataType": "string"
                },
                {
                    "name": "DETAIL_BUDGETING_ALLOWED_FLAG",
                    "dataType": "string"
                },
                {
                    "name": "ACCOUNT_TYPE",
                    "dataType": "string"
                },
                {
                    "name": "ENABLED_FLAG",
                    "dataType": "string"
                },
                {
                    "name": "SUMMARY_FLAG",
                    "dataType": "string"
                },
                {
                    "name": "START_DATE_ACTIVE",
                    "dataType": "dateTime"
                },
                {
                    "name": "END_DATE_ACTIVE",
                    "dataType": "dateTime"
                },
                {
                    "name": "SEGMENT1",
                    "dataType": "string"
                },
                {
                    "name": "SEGMENT2",
                    "dataType": "string"
                },
                {
                    "name": "SEGMENT3",
                    "dataType": "string"
                },
                {
                    "name": "SEGMENT4",
                    "dataType": "string"
                },
                {
                    "name": "SEGMENT5",
                    "dataType": "string"
                },
                {
                    "name": "SEGMENT6",
                    "dataType": "string"
                },
                {
                    "name": "CONCATENATED_SEGMENTS",
                    "dataType": "string"
                },
                {
                    "name": "ENTITY_NAME",
                    "dataType": "string"
                },
                {
                    "name": "ENTITY_DESC",
                    "dataType": "string"
                },
                {
                    "name": "DEPARTMENT_NAME",
                    "dataType": "string"
                },
                {
                    "name": "DEPARTMENT_DESC",
                    "dataType": "string"
                },
                {
                    "name": "ACCOUNT_NAME",
                    "dataType": "string"
                },
                {
                    "name": "ACCOUNT_DESC",
                    "dataType": "string"
                },
                {
                    "name": "PROJECT_NAME",
                    "dataType": "string"
                },
                {
                    "name": "PROJECT_DESC",
                    "dataType": "string"
                }
            ]
        },
        {
            "$type": "LocalEntity",
            "name": "DIM_GL Project Segment",
            "description": "",
            "pbi:refreshPolicy": {
                "$type": "FullRefreshPolicy",
                "location": "DIM_GL%20Project%20Segment.csv"
            },
            "attributes": [
                {
                    "name": "Project Code",
                    "dataType": "string"
                },
                {
                    "name": "Project Name",
                    "dataType": "string"
                },
                {
                    "name": "Project Description",
                    "dataType": "string"
                },
                {
                    "name": "Enabled Flag",
                    "dataType": "string"
                },
                {
                    "name": "Active Start Date",
                    "dataType": "dateTime"
                },
                {
                    "name": "Active End Date",
                    "dataType": "dateTime"
                },
                {
                    "name": "Creation Date",
                    "dataType": "dateTime"
                },
                {
                    "name": "Last Update Date",
                    "dataType": "dateTime"
                },
                {
                    "name": "Created By Login",
                    "dataType": "string"
                },
                {
                    "name": "Last Update By Login",
                    "dataType": "string"
                },
                {
                    "name": "Project Sub Group",
                    "dataType": "string"
                },
                {
                    "name": "Project Group",
                    "dataType": "string"
                },
                {
                    "name": "Summary Project",
                    "dataType": "string"
                }
            ]
        },
        {
            "$type": "LocalEntity",
            "name": "DIM_Calendar",
            "description": "",
            "pbi:refreshPolicy": {
                "$type": "FullRefreshPolicy",
                "location": "DIM_Calendar.csv"
            },
            "attributes": [
                {
                    "name": "Period Set Name",
                    "dataType": "string"
                },
                {
                    "name": "Calendar Day",
                    "dataType": "dateTime"
                },
                {
                    "name": "Fiscal Week",
                    "dataType": "string"
                },
                {
                    "name": "Fiscal Year Week",
                    "dataType": "string"
                },
                {
                    "name": "FISCAL_WEEK_DISP",
                    "dataType": "string"
                },
                {
                    "name": "FISCAL_MONTH_SORT_VALUE",
                    "dataType": "string"
                },
                {
                    "name": "FISCAL_QUARTER_DISP",
                    "dataType": "string"
                },
                {
                    "name": "Fiscal Week No",
                    "dataType": "double"
                },
                {
                    "name": "Fiscal Month Week No",
                    "dataType": "double"
                },
                {
                    "name": "FISCAL_QTR_WEEK",
                    "dataType": "string"
                },
                {
                    "name": "Fiscal Qtr Week No",
                    "dataType": "double"
                },
                {
                    "name": "GL Period",
                    "dataType": "string"
                },
                {
                    "name": "PQ_LAST_GL_PERIOD",
                    "dataType": "string"
                },
                {
                    "name": "Period Year",
                    "dataType": "double"
                },
                {
                    "name": "Fiscal Year",
                    "dataType": "string"
                },
                {
                    "name": "Quarter No",
                    "dataType": "double"
                },
                {
                    "name": "Fiscal Quarter",
                    "dataType": "string"
                },
                {
                    "name": "Fiscal Year Quarter",
                    "dataType": "string"
                },
                {
                    "name": "PRIOR_FYFQ",
                    "dataType": "string"
                },
                {
                    "name": "PERIOD_NAME",
                    "dataType": "string"
                },
                {
                    "name": "Period No",
                    "dataType": "double"
                },
                {
                    "name": "Fiscal Day",
                    "dataType": "double"
                },
                {
                    "name": "Week Start Date",
                    "dataType": "dateTime"
                },
                {
                    "name": "Week End Date",
                    "dataType": "dateTime"
                },
                {
                    "name": "Period Start Date",
                    "dataType": "dateTime"
                },
                {
                    "name": "Period End Date",
                    "dataType": "dateTime"
                },
                {
                    "name": "Quarter Start Date",
                    "dataType": "dateTime"
                },
                {
                    "name": "Quarter End Date",
                    "dataType": "dateTime"
                },
                {
                    "name": "Year Start Date",
                    "dataType": "dateTime"
                },
                {
                    "name": "Year End Date",
                    "dataType": "dateTime"
                },
                {
                    "name": "Fiscal Period Month",
                    "dataType": "string"
                },
                {
                    "name": "FC_PERIOD_ID",
                    "dataType": "double"
                },
                {
                    "name": "FC_QUARTER_ID",
                    "dataType": "double"
                },
                {
                    "name": "FC_WEEK_ID",
                    "dataType": "double"
                },
                {
                    "name": "FC_YEAR_OFFSET",
                    "dataType": "double"
                },
                {
                    "name": "FC_QUARTER_OFFSET",
                    "dataType": "double"
                },
                {
                    "name": "FC_PERIOD_OFFSET",
                    "dataType": "double"
                },
                {
                    "name": "FC_WEEK_OFFSET",
                    "dataType": "double"
                },
                {
                    "name": "FC_DAYS_OFFSET",
                    "dataType": "double"
                },
                {
                    "name": "FC_HALF",
                    "dataType": "string"
                },
                {
                    "name": "Next Quarter First Fiscal Week",
                    "dataType": "string"
                },
                {
                    "name": "Prior Qtr Last Fiscal Week",
                    "dataType": "string"
                },
                {
                    "name": "CALENDAR_YEAR",
                    "dataType": "double"
                },
                {
                    "name": "CALENDAR_MONTH",
                    "dataType": "double"
                },
                {
                    "name": "CALENDAR_YEARMONTHID",
                    "dataType": "string"
                },
                {
                    "name": "CALENDAR_MONTHNAME",
                    "dataType": "string"
                },
                {
                    "name": "CALENDAR_MONTHNAMESHORT",
                    "dataType": "string"
                },
                {
                    "name": "CALENDAR_ISO_WEEK",
                    "dataType": "double"
                },
                {
                    "name": "CALENDAR_US_WEEK",
                    "dataType": "double"
                },
                {
                    "name": "CALENDAR_YEAR_SHORT",
                    "dataType": "string"
                },
                {
                    "name": "CALENDAR_MTH_YEAR",
                    "dataType": "string"
                },
                {
                    "name": "DAY_NAME",
                    "dataType": "string"
                },
                {
                    "name": "DAY_OF_WEEK",
                    "dataType": "double"
                },
                {
                    "name": "WORKING_DAY_FLAG",
                    "dataType": "double"
                },
                {
                    "name": "CQ_LAST_FISCAL_WEEK",
                    "dataType": "string"
                },
                {
                    "name": "Row Creation Date",
                    "dataType": "date"
                },
                {
                    "name": "Week End Flag",
                    "dataType": "string"
                },
                {
                    "name": "Month End Flag",
                    "dataType": "string"
                },
                {
                    "name": "Quarter End Flag",
                    "dataType": "string"
                },
                {
                    "name": "Year End Flag",
                    "dataType": "string"
                },
                {
                    "name": "FISCAL_WEEK_INDICATOR",
                    "dataType": "string"
                },
                {
                    "name": "FISCAL_WEEK_INDICATOR_SORT",
                    "dataType": "double"
                },
                {
                    "name": "FISCAL_MONTH_INDICATOR",
                    "dataType": "string"
                },
                {
                    "name": "FISCAL_MONTH_INDICATOR_SORT",
                    "dataType": "double"
                },
                {
                    "name": "FISCAL_QUARTER_INDICATOR",
                    "dataType": "string"
                },
                {
                    "name": "FISCAL_QUARTER_INDICATOR_SORT",
                    "dataType": "double"
                },
                {
                    "name": "FISCAL_YEAR_INDICATOR",
                    "dataType": "string"
                },
                {
                    "name": "FISCAL_YEAR_INDICATOR_SORT",
                    "dataType": "double"
                },
                {
                    "name": "Refresh Date",
                    "dataType": "dateTime"
                }
            ]
        },
        {
            "$type": "LocalEntity",
            "name": "DIM_Fiscal Context",
            "description": "",
            "pbi:refreshPolicy": {
                "$type": "FullRefreshPolicy",
                "location": "DIM_Fiscal%20Context.csv"
            },
            "attributes": [
                {
                    "name": "PERIOD_SET_NAME",
                    "dataType": "string"
                },
                {
                    "name": "CAL_DAY",
                    "dataType": "dateTime"
                },
                {
                    "name": "FISCAL_WEEK",
                    "dataType": "string"
                },
                {
                    "name": "FISCAL_YEAR_WEEK",
                    "dataType": "string"
                },
                {
                    "name": "FISCAL_WEEK_DISP",
                    "dataType": "string"
                },
                {
                    "name": "FISCAL_MONTH_SORT_VALUE",
                    "dataType": "string"
                },
                {
                    "name": "FISCAL_QUARTER_DISP",
                    "dataType": "string"
                },
                {
                    "name": "FISCAL_WEEK_NO",
                    "dataType": "double"
                },
                {
                    "name": "FISCAL_MONTH_WEEK_NO",
                    "dataType": "double"
                },
                {
                    "name": "FISCAL_QTR_WEEK",
                    "dataType": "string"
                },
                {
                    "name": "FISCAL_QTR_WEEK_NO",
                    "dataType": "double"
                },
                {
                    "name": "GL_PERIOD",
                    "dataType": "string"
                },
                {
                    "name": "PQ_LAST_GL_PERIOD",
                    "dataType": "string"
                },
                {
                    "name": "PERIOD_YEAR",
                    "dataType": "double"
                },
                {
                    "name": "FISCAL_YEAR",
                    "dataType": "string"
                },
                {
                    "name": "QUARTER_NUM",
                    "dataType": "double"
                },
                {
                    "name": "FISCAL_QUARTER",
                    "dataType": "string"
                },
                {
                    "name": "FYFQ",
                    "dataType": "string"
                },
                {
                    "name": "PRIOR_FYFQ",
                    "dataType": "string"
                },
                {
                    "name": "PERIOD_NAME",
                    "dataType": "string"
                },
                {
                    "name": "PERIOD_NUM",
                    "dataType": "double"
                },
                {
                    "name": "FISCAL_DAY",
                    "dataType": "double"
                },
                {
                    "name": "WEEK_START_DATE",
                    "dataType": "dateTime"
                },
                {
                    "name": "WEEK_END_DATE",
                    "dataType": "dateTime"
                },
                {
                    "name": "PERIOD_START_DATE",
                    "dataType": "dateTime"
                },
                {
                    "name": "PERIOD_END_DATE",
                    "dataType": "dateTime"
                },
                {
                    "name": "QUARTER_START_DATE",
                    "dataType": "dateTime"
                },
                {
                    "name": "QUARTER_END_DATE",
                    "dataType": "dateTime"
                },
                {
                    "name": "YEAR_START_DATE",
                    "dataType": "dateTime"
                },
                {
                    "name": "YEAR_END_DATE",
                    "dataType": "dateTime"
                },
                {
                    "name": "PERIOD_MONTH",
                    "dataType": "string"
                },
                {
                    "name": "FC_PERIOD_ID",
                    "dataType": "double"
                },
                {
                    "name": "FC_QUARTER_ID",
                    "dataType": "double"
                },
                {
                    "name": "FC_WEEK_ID",
                    "dataType": "double"
                },
                {
                    "name": "FC_YEAR_OFFSET",
                    "dataType": "double"
                },
                {
                    "name": "FC_QUARTER_OFFSET",
                    "dataType": "double"
                },
                {
                    "name": "FC_PERIOD_OFFSET",
                    "dataType": "double"
                },
                {
                    "name": "FC_WEEK_OFFSET",
                    "dataType": "double"
                },
                {
                    "name": "FC_DAYS_OFFSET",
                    "dataType": "double"
                },
                {
                    "name": "FC_HALF",
                    "dataType": "string"
                },
                {
                    "name": "NQ_FIRST_FISCAL_WEEK",
                    "dataType": "string"
                },
                {
                    "name": "PQ_LAST_FISCAL_WEEK",
                    "dataType": "string"
                },
                {
                    "name": "CALENDAR_YEAR",
                    "dataType": "double"
                },
                {
                    "name": "CALENDAR_MONTH",
                    "dataType": "double"
                },
                {
                    "name": "CALENDAR_YEARMONTHID",
                    "dataType": "string"
                },
                {
                    "name": "CALENDAR_MONTHNAME",
                    "dataType": "string"
                },
                {
                    "name": "CALENDAR_MONTHNAMESHORT",
                    "dataType": "string"
                },
                {
                    "name": "CALENDAR_ISO_WEEK",
                    "dataType": "double"
                },
                {
                    "name": "CALENDAR_US_WEEK",
                    "dataType": "double"
                },
                {
                    "name": "CALENDAR_YEAR_SHORT",
                    "dataType": "string"
                },
                {
                    "name": "CALENDAR_MTH_YEAR",
                    "dataType": "string"
                },
                {
                    "name": "DAY_NAME",
                    "dataType": "string"
                },
                {
                    "name": "DAY_OF_WEEK",
                    "dataType": "double"
                },
                {
                    "name": "WORKING_DAY_FLAG",
                    "dataType": "double"
                },
                {
                    "name": "CQ_LAST_FISCAL_WEEK",
                    "dataType": "string"
                },
                {
                    "name": "ROW_CREATION_DATE",
                    "dataType": "date"
                },
                {
                    "name": "WEEK_END_FLAG",
                    "dataType": "string"
                },
                {
                    "name": "MONTH_END_FLAG",
                    "dataType": "string"
                },
                {
                    "name": "QUARTER_END_FLAG",
                    "dataType": "string"
                },
                {
                    "name": "YEAR_END_FLAG",
                    "dataType": "string"
                },
                {
                    "name": "FISCAL_WEEK_INDICATOR",
                    "dataType": "string"
                },
                {
                    "name": "FISCAL_WEEK_INDICATOR_SORT",
                    "dataType": "double"
                },
                {
                    "name": "FISCAL_MONTH_INDICATOR",
                    "dataType": "string"
                },
                {
                    "name": "FISCAL_MONTH_INDICATOR_SORT",
                    "dataType": "double"
                },
                {
                    "name": "FISCAL_QUARTER_INDICATOR",
                    "dataType": "string"
                },
                {
                    "name": "FISCAL_QUARTER_INDICATOR_SORT",
                    "dataType": "double"
                },
                {
                    "name": "FISCAL_YEAR_INDICATOR",
                    "dataType": "string"
                },
                {
                    "name": "FISCAL_YEAR_INDICATOR_SORT",
                    "dataType": "double"
                },
                {
                    "name": "EXTRACT_DATE",
                    "dataType": "dateTime"
                },
                {
                    "name": "CONTEXT",
                    "dataType": "string"
                },
                {
                    "name": "DATA_UPDATE_DESC",
                    "dataType": "string"
                },
                {
                    "name": "CONTEXT_FYWK",
                    "dataType": "string"
                },
                {
                    "name": "CONTEXT_PERIOD",
                    "dataType": "string"
                }
            ]
        },
        {
            "$type": "LocalEntity",
            "name": "DIM_GLDepartment",
            "description": "",
            "pbi:refreshPolicy": {
                "$type": "FullRefreshPolicy",
                "location": "DIM_GLDepartment.csv"
            },
            "attributes": [
                {
                    "name": "Department Code",
                    "dataType": "string"
                },
                {
                    "name": "Department Name",
                    "dataType": "string"
                },
                {
                    "name": "Department Description",
                    "dataType": "string"
                },
                {
                    "name": "Enabled Flag",
                    "dataType": "string"
                },
                {
                    "name": "Active Start Date",
                    "dataType": "dateTime"
                },
                {
                    "name": "Active End Date",
                    "dataType": "dateTime"
                },
                {
                    "name": "Creation Date",
                    "dataType": "dateTime"
                },
                {
                    "name": "Last Update Date",
                    "dataType": "dateTime"
                },
                {
                    "name": "Created By Login",
                    "dataType": "string"
                },
                {
                    "name": "Last Update By Login",
                    "dataType": "string"
                },
                {
                    "name": "Department Sub Group",
                    "dataType": "string"
                },
                {
                    "name": "Department Group",
                    "dataType": "string"
                },
                {
                    "name": "Summary Department",
                    "dataType": "string"
                }
            ]
        },
        {
            "$type": "LocalEntity",
            "name": "DIM_Inventory Organizations",
            "description": "",
            "pbi:refreshPolicy": {
                "$type": "FullRefreshPolicy",
                "location": "DIM_Inventory%20Organizations.csv"
            },
            "attributes": [
                {
                    "name": "INVORG_ID",
                    "dataType": "double"
                },
                {
                    "name": "OPERATING_UNIT_ID",
                    "dataType": "double"
                },
                {
                    "name": "LEDGER_ID",
                    "dataType": "double"
                },
                {
                    "name": "GL_ENTITY",
                    "dataType": "string"
                },
                {
                    "name": "Operating Unit",
                    "dataType": "string"
                },
                {
                    "name": "LEDGER",
                    "dataType": "string"
                },
                {
                    "name": "INVORG_CODE",
                    "dataType": "string"
                },
                {
                    "name": "CURRENCY_CODE",
                    "dataType": "string"
                },
                {
                    "name": "Inventory Org Category",
                    "dataType": "string"
                },
                {
                    "name": "INV_ORG_CODE_CUSTOWNED",
                    "dataType": "string"
                },
                {
                    "name": "TIMEZONE",
                    "dataType": "string"
                },
                {
                    "name": "DISABLE_DATE",
                    "dataType": "date"
                },
                {
                    "name": "CREATION_DATE",
                    "dataType": "dateTime"
                },
                {
                    "name": "CREATED_BY_LOGIN",
                    "dataType": "string"
                },
                {
                    "name": "LAST_UPDATE_DATE",
                    "dataType": "dateTime"
                },
                {
                    "name": "LAST_UPDATE_LOGIN",
                    "dataType": "string"
                },
                {
                    "name": "INVORG_GROUP",
                    "dataType": "string"
                },
                {
                    "name": "LABOR_TARGET_PCT",
                    "dataType": "double"
                },
                {
                    "name": "BASELINE_FYFQ",
                    "dataType": "string"
                },
                {
                    "name": "COUNTRY_CODE",
                    "dataType": "string"
                },
                {
                    "name": "INVORG_TYPE",
                    "dataType": "string"
                }
            ]
        },
        {
            "$type": "LocalEntity",
            "name": "DIM_Operating Units",
            "description": "",
            "pbi:refreshPolicy": {
                "$type": "FullRefreshPolicy",
                "location": "DIM_Operating%20Units.csv"
            },
            "attributes": [
                {
                    "name": "OPERATING_UNIT_ID",
                    "dataType": "double"
                },
                {
                    "name": "OPERATING_UNIT",
                    "dataType": "string"
                },
                {
                    "name": "DISABLE_DATE",
                    "dataType": "date"
                },
                {
                    "name": "OU_REGION",
                    "dataType": "string"
                },
                {
                    "name": "TIMEZONE",
                    "dataType": "string"
                },
                {
                    "name": "CREATION_DATE",
                    "dataType": "dateTime"
                },
                {
                    "name": "CREATED_BY_LOGIN",
                    "dataType": "string"
                },
                {
                    "name": "LAST_UPDATE_DATE",
                    "dataType": "dateTime"
                },
                {
                    "name": "LAST_UPDATE_LOGIN",
                    "dataType": "string"
                },
                {
                    "name": "INV_ORG_CODE_CUSTOWNED",
                    "dataType": "string"
                },
                {
                    "name": "LEDGER_ID",
                    "dataType": "double"
                }
            ]
        },
        {
            "$type": "LocalEntity",
            "name": "DIM_Operating Unit Data Security",
            "description": "",
            "pbi:refreshPolicy": {
                "$type": "FullRefreshPolicy",
                "location": "DIM_Operating%20Unit%20Data%20Security.csv"
            },
            "attributes": [
                {
                    "name": "OPERATING_UNIT_ID",
                    "dataType": "double"
                },
                {
                    "name": "OPERATING_UNIT_NAME",
                    "dataType": "string"
                },
                {
                    "name": "USER_EMAIL",
                    "dataType": "string"
                },
                {
                    "name": "RECORD_ID",
                    "dataType": "double"
                },
                {
                    "name": "GROUP_NAME",
                    "dataType": "string"
                },
                {
                    "name": "USER_ROLE",
                    "dataType": "string"
                },
                {
                    "name": "OPERATING_UNIT_IDS",
                    "dataType": "string"
                },
                {
                    "name": "COMMENTS",
                    "dataType": "string"
                },
                {
                    "name": "CREATION_DATE",
                    "dataType": "dateTime"
                },
                {
                    "name": "LAST_UPDATE_DATE",
                    "dataType": "dateTime"
                },
                {
                    "name": "CREATED_BY_LOGIN",
                    "dataType": "string"
                },
                {
                    "name": "LAST_UPDATE_LOGIN",
                    "dataType": "string"
                }
            ]
        },
        {
            "$type": "LocalEntity",
            "name": "Version History Model",
            "description": "",
            "pbi:refreshPolicy": {
                "$type": "FullRefreshPolicy",
                "location": "Version%20History%20Model.csv"
            },
            "attributes": [
                {
                    "name": "Version Number",
                    "dataType": "string"
                },
                {
                    "name": "Revision Date/Time",
                    "dataType": "dateTime"
                },
                {
                    "name": "Developer Name",
                    "dataType": "string"
                },
                {
                    "name": "Revision Notes",
                    "dataType": "string"
                },
                {
                    "name": "Revision Type",
                    "dataType": "string"
                }
            ]
        },
        {
            "$type": "LocalEntity",
            "name": "Version History Report",
            "description": "",
            "pbi:refreshPolicy": {
                "$type": "FullRefreshPolicy",
                "location": "Version%20History%20Report.csv"
            },
            "attributes": [
                {
                    "name": "Version Number",
                    "dataType": "string"
                },
                {
                    "name": "Revision Date/Time",
                    "dataType": "dateTime"
                },
                {
                    "name": "Developer Name",
                    "dataType": "string"
                },
                {
                    "name": "Revision Notes",
                    "dataType": "string"
                },
                {
                    "name": "Revision Type",
                    "dataType": "string"
                }
            ]
        },
        {
            "$type": "LocalEntity",
            "name": "Version History",
            "description": "",
            "pbi:refreshPolicy": {
                "$type": "FullRefreshPolicy",
                "location": "Version%20History.csv"
            },
            "annotations": [
                {
                    "name": "pbi:EntityTypeDisplayHint",
                    "value": "CalculatedEntity"
                }
            ],
            "attributes": [
                {
                    "name": "Version Number",
                    "dataType": "string"
                },
                {
                    "name": "Revision Date/Time",
                    "dataType": "dateTime"
                },
                {
                    "name": "Developer Name",
                    "dataType": "string"
                },
                {
                    "name": "Revision Notes",
                    "dataType": "string"
                },
                {
                    "name": "Revision Type",
                    "dataType": "string"
                }
            ]
        },
        {
            "$type": "LocalEntity",
            "name": "DIM_GLEntity",
            "description": "",
            "pbi:refreshPolicy": {
                "$type": "FullRefreshPolicy",
                "location": "DIM_GLEntity.csv"
            },
            "attributes": [
                {
                    "name": "Entrity Code",
                    "dataType": "string"
                },
                {
                    "name": "Entity Name",
                    "dataType": "string"
                },
                {
                    "name": "Entity Description",
                    "dataType": "string"
                },
                {
                    "name": "Enabled Flag",
                    "dataType": "string"
                },
                {
                    "name": "Active Start Date",
                    "dataType": "dateTime"
                },
                {
                    "name": "Active End Date",
                    "dataType": "dateTime"
                },
                {
                    "name": "Creation Date",
                    "dataType": "dateTime"
                },
                {
                    "name": "Last Update Date",
                    "dataType": "dateTime"
                },
                {
                    "name": "Created By Login",
                    "dataType": "string"
                },
                {
                    "name": "Last Update By Login",
                    "dataType": "string"
                },
                {
                    "name": "Entity Sub Group",
                    "dataType": "string"
                },
                {
                    "name": "Entity Group",
                    "dataType": "string"
                },
                {
                    "name": "Summary Entity",
                    "dataType": "string"
                },
                {
                    "name": "Local GAAP Entity",
                    "dataType": "string"
                },
                {
                    "name": "US-GAAP Entity Flag",
                    "dataType": "string"
                },
                {
                    "name": "Currency Code",
                    "dataType": "string"
                }
            ]
        },
        {
            "$type": "LocalEntity",
            "name": "ListOfOrgs",
            "description": "",
            "pbi:refreshPolicy": {
                "$type": "FullRefreshPolicy",
                "location": "ListOfOrgs.csv"
            },
            "attributes": [
                {
                    "name": "Value",
                    "dataType": "string"
                }
            ]
        },
        {
            "$type": "LocalEntity",
            "name": "DIM_Fiscal Calendar",
            "description": "",
            "pbi:refreshPolicy": {
                "$type": "FullRefreshPolicy",
                "location": "DIM_Fiscal%20Calendar.csv"
            },
            "attributes": [
                {
                    "name": "Period Set Name",
                    "dataType": "string"
                },
                {
                    "name": "Calendar Day",
                    "dataType": "date"
                },
                {
                    "name": "Fiscal Year Week",
                    "dataType": "string"
                },
                {
                    "name": "Fiscal Week",
                    "dataType": "string"
                },
                {
                    "name": "FISCAL_WEEK_DISP",
                    "dataType": "string"
                },
                {
                    "name": "FISCAL_MONTH_SORT_VALUE",
                    "dataType": "string"
                },
                {
                    "name": "FISCAL_QUARTER_DISP",
                    "dataType": "string"
                },
                {
                    "name": "Fiscal Week No",
                    "dataType": "int64"
                },
                {
                    "name": "Fiscal Month Week No",
                    "dataType": "int64"
                },
                {
                    "name": "FISCAL_QTR_WEEK",
                    "dataType": "string"
                },
                {
                    "name": "Fiscal Qtr Week No",
                    "dataType": "int64"
                },
                {
                    "name": "GL Period",
                    "dataType": "string"
                },
                {
                    "name": "PQ_LAST_GL_PERIOD",
                    "dataType": "string"
                },
                {
                    "name": "Period Year",
                    "dataType": "int64"
                },
                {
                    "name": "Fiscal Year",
                    "dataType": "string"
                },
                {
                    "name": "Quarter No",
                    "dataType": "int64"
                },
                {
                    "name": "Fiscal Quarter",
                    "dataType": "string"
                },
                {
                    "name": "Fiscal Year Quarter",
                    "dataType": "string"
                },
                {
                    "name": "PRIOR_FYFQ",
                    "dataType": "string"
                },
                {
                    "name": "PERIOD_NAME",
                    "dataType": "string"
                },
                {
                    "name": "Period No",
                    "dataType": "int64"
                },
                {
                    "name": "Fiscal Day",
                    "dataType": "int64"
                },
                {
                    "name": "Week Start Date",
                    "dataType": "date"
                },
                {
                    "name": "Week End Date",
                    "dataType": "date"
                },
                {
                    "name": "Period Start Date",
                    "dataType": "date"
                },
                {
                    "name": "Period End Date",
                    "dataType": "date"
                },
                {
                    "name": "Quarter Start Date",
                    "dataType": "date"
                },
                {
                    "name": "Quarter End Date",
                    "dataType": "date"
                },
                {
                    "name": "Year Start Date",
                    "dataType": "date"
                },
                {
                    "name": "Year End Date",
                    "dataType": "date"
                },
                {
                    "name": "Fiscal Period Month",
                    "dataType": "string"
                },
                {
                    "name": "FC_PERIOD_ID",
                    "dataType": "int64"
                },
                {
                    "name": "FC_QUARTER_ID",
                    "dataType": "int64"
                },
                {
                    "name": "FC_WEEK_ID",
                    "dataType": "int64"
                },
                {
                    "name": "FC_YEAR_OFFSET",
                    "dataType": "int64"
                },
                {
                    "name": "FC_QUARTER_OFFSET",
                    "dataType": "int64"
                },
                {
                    "name": "FC_PERIOD_OFFSET",
                    "dataType": "int64"
                },
                {
                    "name": "FC_WEEK_OFFSET",
                    "dataType": "int64"
                },
                {
                    "name": "FC_DAYS_OFFSET",
                    "dataType": "int64"
                },
                {
                    "name": "FC_HALF",
                    "dataType": "string"
                },
                {
                    "name": "Next Quarter First Fiscal Week",
                    "dataType": "string"
                },
                {
                    "name": "Prior Qtr Last Fiscal Week",
                    "dataType": "string"
                },
                {
                    "name": "CALENDAR_YEAR",
                    "dataType": "int64"
                },
                {
                    "name": "CALENDAR_MONTH",
                    "dataType": "int64"
                },
                {
                    "name": "CALENDAR_YEARMONTHID",
                    "dataType": "string"
                },
                {
                    "name": "CALENDAR_MONTHNAME",
                    "dataType": "string"
                },
                {
                    "name": "CALENDAR_MONTHNAMESHORT",
                    "dataType": "string"
                },
                {
                    "name": "CALENDAR_ISO_WEEK",
                    "dataType": "int64"
                },
                {
                    "name": "CALENDAR_US_WEEK",
                    "dataType": "int64"
                },
                {
                    "name": "CALENDAR_YEAR_SHORT",
                    "dataType": "string"
                },
                {
                    "name": "CALENDAR_MTH_YEAR",
                    "dataType": "string"
                },
                {
                    "name": "DAY_NAME",
                    "dataType": "string"
                },
                {
                    "name": "DAY_OF_WEEK",
                    "dataType": "int64"
                },
                {
                    "name": "WORKING_DAY_FLAG",
                    "dataType": "int64"
                },
                {
                    "name": "CQ_LAST_FISCAL_WEEK",
                    "dataType": "string"
                },
                {
                    "name": "Row Creation Date",
                    "dataType": "date"
                },
                {
                    "name": "Week End Flag",
                    "dataType": "string"
                },
                {
                    "name": "Month End Flag",
                    "dataType": "string"
                },
                {
                    "name": "Quarter End Flag",
                    "dataType": "string"
                },
                {
                    "name": "Year End Flag",
                    "dataType": "string"
                },
                {
                    "name": "FISCAL_WEEK_INDICATOR",
                    "dataType": "string"
                },
                {
                    "name": "FISCAL_WEEK_INDICATOR_SORT",
                    "dataType": "int64"
                },
                {
                    "name": "FISCAL_MONTH_INDICATOR",
                    "dataType": "string"
                },
                {
                    "name": "FISCAL_MONTH_INDICATOR_SORT",
                    "dataType": "int64"
                },
                {
                    "name": "FISCAL_QUARTER_INDICATOR",
                    "dataType": "string"
                },
                {
                    "name": "FISCAL_QUARTER_INDICATOR_SORT",
                    "dataType": "int64"
                },
                {
                    "name": "FISCAL_YEAR_INDICATOR",
                    "dataType": "string"
                },
                {
                    "name": "FISCAL_YEAR_INDICATOR_SORT",
                    "dataType": "int64"
                },
                {
                    "name": "Refresh Date",
                    "dataType": "dateTime"
                },
                {
                    "name": "Start of Week",
                    "dataType": "date"
                },
                {
                    "name": "Cal_Year_ofCW",
                    "dataType": "int64"
                },
                {
                    "name": "Cal_Year_ofCW_Short",
                    "dataType": "int64"
                },
                {
                    "name": "CALENDAR_Year_CWiso",
                    "dataType": "string"
                },
                {
                    "name": "Cal_Year_CWiso_ID",
                    "dataType": "int64"
                },
                {
                    "name": "Cal_CW",
                    "dataType": "string"
                }
            ]
        },
        {
            "$type": "LocalEntity",
            "name": "FACT_LT Grouping Summary",
            "description": "",
            "pbi:refreshPolicy": {
                "$type": "FullRefreshPolicy",
                "location": "FACT_LT%20Grouping%20Summary.csv"
            },
            "annotations": [
                {
                    "name": "pbi:EntityTypeDisplayHint",
                    "value": "CalculatedEntity"
                }
            ],
            "attributes": [
                {
                    "name": "FISCAL_DIM_VALUE",
                    "dataType": "string"
                },
                {
                    "name": "FISCAL_DIM_SORT_VALUE",
                    "dataType": "string"
                },
                {
                    "name": "PERIOD_YEAR",
                    "dataType": "double"
                },
                {
                    "name": "FISCAL_WEEK_ID",
                    "dataType": "double"
                },
                {
                    "name": "LT_GROUPING_ID",
                    "dataType": "double"
                },
                {
                    "name": "LT_GROUPING",
                    "dataType": "string"
                },
                {
                    "name": "LT_GROUPING_DESC",
                    "dataType": "string"
                },
                {
                    "name": "ORGANIZATION_CODE",
                    "dataType": "string"
                },
                {
                    "name": "PLANNING_METHOD",
                    "dataType": "string"
                },
                {
                    "name": "CURRENT_MRP_ABC_CLASS",
                    "dataType": "string"
                },
                {
                    "name": "SR_VNDR_SRC_ORG",
                    "dataType": "string"
                },
                {
                    "name": "ITEM_TYPE",
                    "dataType": "string"
                },
                {
                    "name": "ACTIVE_OR_INACTIVE",
                    "dataType": "string"
                },
                {
                    "name": "INV_VALUE",
                    "dataType": "double"
                },
                {
                    "name": "ITEM_COUNT",
                    "dataType": "double"
                }
            ]
        },
        {
            "$type": "LocalEntity",
            "name": "FACT_Inventory Velocity Summary",
            "description": "",
            "pbi:refreshPolicy": {
                "$type": "FullRefreshPolicy",
                "location": "FACT_Inventory%20Velocity%20Summary.csv"
            },
            "annotations": [
                {
                    "name": "pbi:EntityTypeDisplayHint",
                    "value": "CalculatedEntity"
                }
            ],
            "attributes": [
                {
                    "name": "ACTIVE_OR_INACTIVE",
                    "dataType": "string"
                },
                {
                    "name": "CURRENT_MRP_ABC_CLASS",
                    "dataType": "string"
                },
                {
                    "name": "DEMAND_SOURCE",
                    "dataType": "string"
                },
                {
                    "name": "ENTITY",
                    "dataType": "string"
                },
                {
                    "name": "FISCAL_WEEK_ID",
                    "dataType": "double"
                },
                {
                    "name": "FISCAL_WEEK_KEY",
                    "dataType": "string"
                },
                {
                    "name": "ITEM_PRODUCT_FAMILY",
                    "dataType": "string"
                },
                {
                    "name": "ITEM_STATUS",
                    "dataType": "string"
                },
                {
                    "name": "ITEM_TBU",
                    "dataType": "string"
                },
                {
                    "name": "ITEM_TYPE",
                    "dataType": "string"
                },
                {
                    "name": "ON_ORDER_DAYS_OF_SUPPLY",
                    "dataType": "double"
                },
                {
                    "name": "ON_ORDER_DAYS_OF_SUPPLY_COUNT",
                    "dataType": "double"
                },
                {
                    "name": "ON_ORDER_VALUE",
                    "dataType": "double"
                },
                {
                    "name": "ON_ORDER_VALUE_USD",
                    "dataType": "double"
                },
                {
                    "name": "ONHAND_DAYS_OF_SUPPLY",
                    "dataType": "double"
                },
                {
                    "name": "ONHAND_VALUE",
                    "dataType": "double"
                },
                {
                    "name": "ONHAND_VALUE_USD",
                    "dataType": "double"
                },
                {
                    "name": "OPERATIONS_REPORTING",
                    "dataType": "string"
                },
                {
                    "name": "ORGANIZATION_CODE",
                    "dataType": "string"
                },
                {
                    "name": "PERIOD_END_DATE",
                    "dataType": "dateTime"
                },
                {
                    "name": "PERIOD_NAME",
                    "dataType": "string"
                },
                {
                    "name": "PERIOD_YEAR",
                    "dataType": "double"
                },
                {
                    "name": "PRODUCT_LINE",
                    "dataType": "string"
                },
                {
                    "name": "PRODUCT_MAP_KEY",
                    "dataType": "string"
                },
                {
                    "name": "RECORD_COUNT",
                    "dataType": "double"
                },
                {
                    "name": "SAFETY_STOCK_VALUE",
                    "dataType": "double"
                },
                {
                    "name": "SAFETY_STOCK_VALUE_USD",
                    "dataType": "double"
                },
                {
                    "name": "SEC_REPORTING",
                    "dataType": "string"
                },
                {
                    "name": "SUPPLY_SOURCE",
                    "dataType": "string"
                },
                {
                    "name": "WEEK_END_DATE",
                    "dataType": "dateTime"
                },
                {
                    "name": "WEEK_START_DATE",
                    "dataType": "dateTime"
                },
                {
                    "name": "WIP_DAYS_OF_SUPPLY",
                    "dataType": "double"
                },
                {
                    "name": "WIP_DAYS_OF_SUPPLY_COUNT",
                    "dataType": "double"
                },
                {
                    "name": "WIP_VALUE",
                    "dataType": "double"
                },
                {
                    "name": "WIP_VALUE_USD",
                    "dataType": "double"
                }
            ]
        },
        {
            "$type": "LocalEntity",
            "name": "FACT_Inventory Velocity Details",
            "description": "",
            "pbi:refreshPolicy": {
                "$type": "FullRefreshPolicy",
                "location": "FACT_Inventory%20Velocity%20Details.csv"
            },
            "annotations": [
                {
                    "name": "pbi:EntityTypeDisplayHint",
                    "value": "CalculatedEntity"
                }
            ],
            "attributes": [
                {
                    "name": "ACTIVE_OR_INACTIVE",
                    "dataType": "string"
                },
                {
                    "name": "ACTIVE_SUPPLIER_LT",
                    "dataType": "double"
                },
                {
                    "name": "AVG_DAILY_DEMAND_ELSE_USAGE",
                    "dataType": "double"
                },
                {
                    "name": "BLANKET_DAYS_SUPPLY_REMAINING",
                    "dataType": "double"
                },
                {
                    "name": "CURRENT_ABC_CLASS",
                    "dataType": "string"
                },
                {
                    "name": "DATE_RUN",
                    "dataType": "dateTime"
                },
                {
                    "name": "FISCAL_WEEK_KEY",
                    "dataType": "string"
                },
                {
                    "name": "INTRANSIT_VALUE",
                    "dataType": "double"
                },
                {
                    "name": "INVENTORY_VALUE",
                    "dataType": "double"
                },
                {
                    "name": "INVENTORY_VALUE_USD",
                    "dataType": "double"
                },
                {
                    "name": "ITEM_COST",
                    "dataType": "double"
                },
                {
                    "name": "ITEM_COST_USD",
                    "dataType": "double"
                },
                {
                    "name": "ITEM_DESCRIPTION",
                    "dataType": "string"
                },
                {
                    "name": "ITEM_NUMBER",
                    "dataType": "string"
                },
                {
                    "name": "ITEM_TYPE",
                    "dataType": "string"
                },
                {
                    "name": "KANBAN_ITEM",
                    "dataType": "int64"
                },
                {
                    "name": "MIN_MAX_ITEM",
                    "dataType": "int64"
                },
                {
                    "name": "OPEN_BLANKETS",
                    "dataType": "int64"
                },
                {
                    "name": "ON_HAND_DAYS_OF_SUPPLY",
                    "dataType": "double"
                },
                {
                    "name": "ON_ORDER_DAYS_OF_SUPPLY",
                    "dataType": "double"
                },
                {
                    "name": "ON_ORDER_VALUE_USD",
                    "dataType": "double"
                },
                {
                    "name": "ONORDER_PO_QTY",
                    "dataType": "double"
                },
                {
                    "name": "ONORDER_PO_VALUE",
                    "dataType": "double"
                },
                {
                    "name": "ONORDER_PO_VALUE_USD",
                    "dataType": "double"
                },
                {
                    "name": "ORGANIZATION_CODE",
                    "dataType": "string"
                },
                {
                    "name": "PLANNING_METHOD",
                    "dataType": "string"
                },
                {
                    "name": "PROJ_SPEND_NEXT_26_WEEKS_USD",
                    "dataType": "double"
                },
                {
                    "name": "SAFETY_STOCK_QTY",
                    "dataType": "double"
                },
                {
                    "name": "SAFETY_STOCK_VALUE",
                    "dataType": "double"
                },
                {
                    "name": "SAFETY_STOCK_VALUE_USD",
                    "dataType": "double"
                },
                {
                    "name": "SEC_REPORTING",
                    "dataType": "string"
                },
                {
                    "name": "SR_VNDR_SRC_ORG",
                    "dataType": "string"
                },
                {
                    "name": "SUM_USD_REMAINING_AMOUNT",
                    "dataType": "double"
                },
                {
                    "name": "TARGET_DAYS_OF_SUPPLY",
                    "dataType": "double"
                },
                {
                    "name": "TARGET_DAYS_OF_SUPPLY_SAVINGS",
                    "dataType": "double"
                },
                {
                    "name": "TARGET_DAYS_OF_SUPPLY_VALUE",
                    "dataType": "double"
                },
                {
                    "name": "TOTAL_GR_26_WEEKS",
                    "dataType": "double"
                },
                {
                    "name": "TOTAL_ONHAND_QTY",
                    "dataType": "double"
                },
                {
                    "name": "WIP_DAYS_OF_SUPPLY",
                    "dataType": "double"
                },
                {
                    "name": "WIP_IN_PROCESS_QTY",
                    "dataType": "double"
                },
                {
                    "name": "WIP_IN_PROCESS_VALUE",
                    "dataType": "double"
                },
                {
                    "name": "WIP_IN_PROCESS_VALUE_USD",
                    "dataType": "double"
                }
            ]
        },
        {
            "$type": "LocalEntity",
            "name": "DIM_Sort Values",
            "description": "",
            "pbi:refreshPolicy": {
                "$type": "FullRefreshPolicy",
                "location": "DIM_Sort%20Values.csv"
            },
            "attributes": [
                {
                    "name": "Value",
                    "dataType": "string"
                },
                {
                    "name": "Type",
                    "dataType": "string"
                },
                {
                    "name": "Sort Order",
                    "dataType": "int64"
                }
            ]
        },
        {
            "$type": "LocalEntity",
            "name": "Version History Dataflow",
            "description": "",
            "pbi:refreshPolicy": {
                "$type": "FullRefreshPolicy",
                "location": "Version%20History%20Dataflow.csv"
            },
            "attributes": [
                {
                    "name": "Version Number",
                    "dataType": "string"
                },
                {
                    "name": "Revision Date/Time",
                    "dataType": "dateTime"
                },
                {
                    "name": "Developer Name",
                    "dataType": "string"
                },
                {
                    "name": "Revision Notes",
                    "dataType": "string"
                },
                {
                    "name": "Revision Type",
                    "dataType": "string"
                }
            ]
        },
        {
            "$type": "LocalEntity",
            "name": "INFO_DataUpdateInfoInventoryVelocity",
            "description": "",
            "pbi:refreshPolicy": {
                "$type": "FullRefreshPolicy",
                "location": "INFO_DataUpdateInfoInventoryVelocity.csv"
            },
            "attributes": [
                {
                    "name": "TABLE_NAME",
                    "dataType": "string"
                },
                {
                    "name": "DATA_UPDATE_DATE",
                    "dataType": "dateTime"
                },
                {
                    "name": "DATA_UPDATE_DESC",
                    "dataType": "string"
                },
                {
                    "name": "DATA_FLOW_REFRESH_DATE",
                    "dataType": "dateTime"
                }
            ]
        }
    ]
}