{"name":"COHREP_SITE_WIP_MASTER1","description":"","version":"1.0","culture":"en-US","modifiedTime":"2021-03-12T06:36:40.3971555+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":true,"queriesMetadata":{"WIP_Class":{"queryId":"483b4d6e-7729-491f-a5b2-64167346ad05","queryName":"WIP_Class","loadEnabled":true},"WIP_Department_Resource":{"queryId":"80b56076-b7b9-4399-bd6f-4e0e6b3c6b89","queryName":"WIP_Department_Resource","loadEnabled":true},"Routing":{"queryId":"39ead407-33f2-4edd-959e-0360b16983a0","queryName":"Routing","loadEnabled":true},"ORG":{"queryId":"6a1f3365-de41-429c-959b-9b6ad4c07db9","queryName":"ORG"},"LocalTZ":{"queryId":"1bf9fe81-52a5-4271-9c06-0167809bd5a8","queryName":"LocalTZ"}},"document":"section Section1;\r\nshared WIP_Class = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, \n  Query=\"\n  SELECT\n   SYSDATE EXTRACT_DATE,\n    from_tz(cast (sysdate as timestamp),'PST') at time zone '\"&LocalTZ&\"' local_extract_date,\n   MP.ORGANIZATION_CODE,\n   WAC.CLASS_CODE,\n   WAC.DESCRIPTION,\n   WAC.CLASS_TYPE CLASS_TYPE_CODE,\n   WLO.MEANING CLASS_TYPE,\n   WAC.DISABLE_DATE,\n   MAC.CONCATENATED_SEGMENTS MATERIAL_ACCOUNT,\n   MOHAC.CONCATENATED_SEGMENTS MATERIAL_OVERHEAD_ACCOUNT,\n   RESAC.CONCATENATED_SEGMENTS RESOURCE_ACCOUNT,\n   OHAC.CONCATENATED_SEGMENTS OVERHEAD_ACCOUNT,\n   OSPAC.CONCATENATED_SEGMENTS OUTSIDE_PROCESSING_ACCOUNT,\n   MVAC.CONCATENATED_SEGMENTS MATERIAL_VARIANCE_ACCOUNT,\n   RESVAC.CONCATENATED_SEGMENTS RESOURCE_VARIANCE_ACCOUNT,\n   OHVAC.CONCATENATED_SEGMENTS OVERHEAD_VARIANCE_ACCOUNT,\n   OSPVAC.CONCATENATED_SEGMENTS OSP_VARIANCE_ACCOUNT,\n   SADJAC.CONCATENATED_SEGMENTS STD_COST_ADJ_ACCOUNT,\n   WAC.ATTRIBUTE1 WORK_TYPE,\n   WAC.ATTRIBUTE2 ACCOUNTING_TYPE,\n   WAC.ATTRIBUTE3 ACTIVITY,\n   WAC.CREATION_DATE,\n   CU.USER_NAME CREATED_BY,\n   WAC.LAST_UPDATE_DATE,\n   LU.USER_NAME LAST_UPDATED_BY \nFROM\n   APPS.FND_USER CU,\n   APPS.FND_USER LU,\n   APPS.GL_CODE_COMBINATIONS_KFV MAC,\n   APPS.GL_CODE_COMBINATIONS_KFV MOHAC,\n   APPS.GL_CODE_COMBINATIONS_KFV RESAC,\n   APPS.GL_CODE_COMBINATIONS_KFV OHAC,\n   APPS.GL_CODE_COMBINATIONS_KFV OSPAC,\n   APPS.GL_CODE_COMBINATIONS_KFV MVAC,\n   APPS.GL_CODE_COMBINATIONS_KFV OHVAC,\n   APPS.GL_CODE_COMBINATIONS_KFV RESVAC,\n   APPS.GL_CODE_COMBINATIONS_KFV OSPVAC,\n   APPS.GL_CODE_COMBINATIONS_KFV SADJAC,\n   APPS.FND_LOOKUP_VALUES WLO,\n   APPS.WIP_ACCOUNTING_CLASSES WAC,\n   APPS.MTL_PARAMETERS MP \nWHERE\n   MP.ORGANIZATION_CODE = '\"&ORG&\"' \n   AND CU.USER_ID ( + ) = WAC.CREATED_BY \n   AND LU.USER_ID ( + ) = WAC.LAST_UPDATED_BY \n   AND MAC.CODE_COMBINATION_ID ( + ) = WAC.MATERIAL_ACCOUNT \n   AND MOHAC.CODE_COMBINATION_ID ( + ) = WAC.MATERIAL_OVERHEAD_ACCOUNT \n   AND RESAC.CODE_COMBINATION_ID ( + ) = WAC.RESOURCE_ACCOUNT \n   AND OHAC.CODE_COMBINATION_ID ( + ) = WAC.OVERHEAD_ACCOUNT \n   AND OSPAC.CODE_COMBINATION_ID ( + ) = WAC.OUTSIDE_PROCESSING_ACCOUNT \n   AND MVAC.CODE_COMBINATION_ID ( + ) = WAC.MATERIAL_VARIANCE_ACCOUNT \n   AND RESVAC.CODE_COMBINATION_ID ( + ) = WAC.RESOURCE_VARIANCE_ACCOUNT \n   AND OHVAC.CODE_COMBINATION_ID ( + ) = WAC.OVERHEAD_VARIANCE_ACCOUNT \n   AND OSPVAC.CODE_COMBINATION_ID ( + ) = WAC.OUTSIDE_PROC_VARIANCE_ACCOUNT \n   AND SADJAC.CODE_COMBINATION_ID ( + ) = WAC.STD_COST_ADJUSTMENT_ACCOUNT \n   AND WLO.LANGUAGE = 'US' \n   AND WLO.LOOKUP_TYPE = 'WIP_CLASS_TYPE' \n   AND WLO.LOOKUP_CODE = WAC.CLASS_TYPE \n   AND WAC.ORGANIZATION_ID = MP.ORGANIZATION_ID\"\n, CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"ORGANIZATION_CODE\", \"Organization Code\"}, {\"CLASS_CODE\", \"Class Code\"}, {\"DESCRIPTION\", \"Class Description\"}, {\"CLASS_TYPE\", \"Class Type\"}, {\"WORK_TYPE\", \"Work Type\"}, {\"ACCOUNTING_TYPE\", \"Accounting Type\"}, {\"ACTIVITY\", \"Activity\"}, {\"MATERIAL_ACCOUNT\", \"Material Account\"}, {\"MATERIAL_OVERHEAD_ACCOUNT\", \"Material Overhead Account\"}, {\"RESOURCE_ACCOUNT\", \"Resource Account\"}, {\"OVERHEAD_ACCOUNT\", \"Overhead Account\"}, {\"OUTSIDE_PROCESSING_ACCOUNT\", \"OSP Account\"}, {\"MATERIAL_VARIANCE_ACCOUNT\", \"Material Variance Account\"}, {\"RESOURCE_VARIANCE_ACCOUNT\", \"Resource Variance Account\"}, {\"OVERHEAD_VARIANCE_ACCOUNT\", \"Overhead Variance Account\"}, {\"OSP_VARIANCE_ACCOUNT\", \"OSP Variance Account\"}, {\"STD_COST_ADJ_ACCOUNT\", \"Cost Adjustment Account\"}, {\"CREATION_DATE\", \"Creation Date\"}, {\"CREATED_BY\", \"Created By\"}, {\"LAST_UPDATE_DATE\", \"Last Update Date\"}, {\"LAST_UPDATED_BY\", \"Last Updated By\"}, {\"EXTRACT_DATE\", \"Extract Date\"}, {\"LOCAL_EXTRACT_DATE\", \"Local Extract Date\"}}),\r\n  ConvertToList = Table.AddColumn(#\"Renamed columns\", \"ClassCodeToList\", each Text.ToList([Class Code])),\r\n  LowerCaseChars = {\"a\"..\"z\"},\r\n  // add Character.FromNumber(8203) to make the column unique\r\n  AddInvisibleChars = Table.AddColumn(ConvertToList, \"AddInvisibleChars\", each List.Transform(\n            [ClassCodeToList], \n            each \n            if \n            List.Contains(#\"LowerCaseChars\", _) \n            then \n            _ & Character.FromNumber(8203) \n            else _\n            )),\r\n  // Add case sensitive column as result of adding invisible characters Character.FromNumber(8203)\r\n  AddCaseSensitiveColumn = Table.AddColumn(AddInvisibleChars, \"Class Code CS\", each Text.Combine([AddInvisibleChars])),\r\n  #\"Removed columns\" = Table.RemoveColumns(AddCaseSensitiveColumn, {\"ClassCodeToList\", \"AddInvisibleChars\"}),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Removed columns\", {{\"Class Code CS\", type text}})\r\nin\r\n  #\"Changed column type\";\r\nshared WIP_Department_Resource = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, \n  Query=\"\n  select sysdate extract_date,\n  from_tz(cast (sysdate as timestamp),'PST') at time zone '\"&LocalTZ&\"' local_extract_date\n,bdept.department_id\n,bdept.department_code\n,bdept.description department_description\n,bdept.location_code\n,bdr.resource_id\n,bdr.resource_code\n,bdr.resource_description\n,bdr.unit_of_measure\n,crc.resource_rate\n,decode(bdr.available_24_hours_flag,1,'Yes',2,'No') hours24_flag\n,BRT.MEANING RESOURCE_TYPE\n,BACT.MEANING AUTOCHARGE_TYPE\n,decode(br.DEFAULT_BASIS_TYPE,1,'Item',2,'Lot') DEFAULT_BASIS_TYPE\nfrom apps.BOM_DEPARTMENTS_V bdept\n, apps.mtl_parameters mp\n,apps.BOM_DEPARTMENT_RESOURCES_V  bdr\n,apps.CST_RESOURCE_COSTS_V crc\n,APPS.BOM_RESOURCES_V br\n,(SELECT LOOKUP_CODE,MEANING FROM apps.mfg_lookups_v\nWHERE lookup_type = 'BOM_RESOURCE_TYPE') BRT\n,(SELECT LOOKUP_CODE,MEANING FROM apps.mfg_lookups_v\nWHERE lookup_type =  'BOM_AUTOCHARGE_TYPE') BACT\nwhere mp.organization_id = bdept.organization_id\nand mp.organization_code = '\"&ORG&\"'\nand bdr.organization_id = bdept.organization_id\nand bdr.department_id = bdept.department_id\nand  bdr.resource_id = crc.resource_id (+)\nand bdr.organization_id = crc.organization_id(+)\nand 1 = crc.cost_type_id  (+)\nAND BR.RESOURCE_ID = BDR.RESOURCE_ID\nAND BRT.LOOKUP_CODE = BR.RESOURCE_TYPE\nAND BACT.LOOKUP_CODE = br.autocharge_type\"\n, CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"EXTRACT_DATE\", \"Extract Date\"}, {\"DEPARTMENT_CODE\", \"Department Code\"}, {\"DEPARTMENT_DESCRIPTION\", \"Department Description\"}, {\"LOCATION_CODE\", \"Location Code\"}, {\"RESOURCE_CODE\", \"Resource Code\"}, {\"RESOURCE_DESCRIPTION\", \"Resource Description\"}, {\"UNIT_OF_MEASURE\", \"Unit of Measure\"}, {\"RESOURCE_RATE\", \"Resource Rate\"}, {\"RESOURCE_TYPE\", \"Resource Type\"}, {\"AUTOCHARGE_TYPE\", \"Autocharge Type\"}, {\"DEFAULT_BASIS_TYPE\", \"Default Basis\"}, {\"HOURS24_FLAG\", \"24 Hours Flag\"}, {\"LOCAL_EXTRACT_DATE\", \"Local Extract Date\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Routing = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, \n  Query=\"\n  SELECT\n    sysdate extract_date,\n    from_tz(cast (sysdate as timestamp),'PST') at time zone '\"&LocalTZ&\"' local_extract_date,\n    o.organization_code,\n    msi.inventory_item_id,\n    msi.segment1                                                                                                              item_number,\n    cmsi.segment1                                                                                                             common_routing_item,\n    decode(r.cfm_routing_flag, 1, 'Y', '')                                                                                    flow_routing,\n    r.completion_subinventory                                                                                                 completion_subinventory,\n    (\n        SELECT\n            l.concatenated_segments\n        FROM\n            apps.mtl_item_locations_kfv l\n        WHERE\n                l.subinventory_code = r.completion_subinventory\n            AND l.organization_id = r.organization_id\n            AND l.inventory_location_id = r.completion_locator_id\n    ) completion_locator,\n    ro.operation_seq_num                                                                                                      operation_seq_num,\n    ro.standard_operation_code                                                                                                std_op_code,\n    replace(replace(replace(ro.operation_description, CHR(124), ' '), CHR(13), ' '), CHR(10), ' ')                            operation_description,\n    bd.department_class_code                                                                                                  dept_class_code,\n    ro.department_code                                                                                                        dept_code,\n    replace(replace(replace(bd.description, CHR(124), ' '), CHR(13), ' '), CHR(10), ' ')                                      dept_description,\n    decode(ro.option_dependent_flag, 1, 'Y', 'N')                                                                             option_dependant,\n    ro.operation_lead_time_percent/100                                                                                            operation_lead_time,\n    ro.effectivity_date                                                                                                       effective_date,\n    ro.disable_date                                                                                                           disable_date,\n    decode(ro.count_point_flag, 1, 'Y', '')                                                                                   count_point,\n    decode(ro.autocharge_flag, 1, 'Y', '')                                                                                    autocharge,\n    decode(ro.backflush_flag, 1, 'Y', '')                                                                                     backflush,\n    decode(ro.check_skill, 1, 'Y', '')                                                                                        check_skill,\n    ro.minimum_transfer_quantity                                                                                              min_transfer_qty,\n    rr.resource_seq_num                                                                                                       resource_seq_num,\n    decode(res.resource_type, 1, 'Machine', 2, 'Person',\n           4, 'Miscellaneous', 5, 'Amount', 6,\n           'Currency') resource_type,\n    decode(res.cost_code_type, 4, 'Y', 'N')                                                                                   osp_ressource,\n    rr.resource_code                                                                                                          resource_code,\n    replace(replace(replace(res.description, CHR(124), ' '), CHR(13), ' '), CHR(10), ' ')                                     resource_description,\n    decode(rr.basis_type, 1, 'Item', 2, 'Lot')                                                                                basis,\n    rr.uom                                                                                                                    unit_of_measure,\n    rr.usage_rate_or_amount                                                                                                   usage_rate_or_amount,\n    (\n        SELECT\n            resource_rate\n        FROM\n            apps.cst_resource_costs\n        WHERE\n                resource_id = rr.resource_id\n            AND cost_type_id = 1\n    ) resource_cost,\n    decode(rr.available_24_hours_flag, 1, 'Y', 2, 'N')                                                                        dept_resource_available_24_hrs,\n    rr.schedule_seq_num                                                                                                       schedule_seq,\n    rr.substitute_group_num                                                                                                   substitute_group_number,\n    rr.assigned_units                                                                                                         assigned_units,\n    decode(rr.schedule_flag, 1, 'Yes', 2, 'No',\n           3, 'Prior', 4, 'Next') schedule_flag,\n    rr.resource_offset_percent/100                                                                                                resource_offset,\n    decode(rr.autocharge_type, 1, 'WIP move', 2, 'Manual',\n           3, 'PO receipt', 4, 'PO move') charge_type\nFROM\n    apps.bom_operational_routings     r,\n    apps.bom_operation_sequences_v    ro,\n    apps.bom_operation_resources_v    rr,\n    apps.mtl_system_items_b           msi,\n    apps.mtl_parameters               o,\n    apps.bom_resources                res,\n    apps.bom_departments              bd,\n    apps.mtl_system_items             cmsi\nWHERE 1 = 1\n    AND ( r.routing_sequence_id = ro.routing_sequence_id\n          OR r.common_routing_sequence_id = ro.routing_sequence_id )\n    AND ro.operation_sequence_id = rr.operation_sequence_id (+)\n    AND msi.inventory_item_id = r.assembly_item_id\n    AND msi.organization_id = r.organization_id\n    AND o.organization_id = r.organization_id\n    AND res.resource_id (+) = rr.resource_id\n    AND bd.department_id (+) = ro.department_id\n    AND cmsi.inventory_item_id (+) = r.common_assembly_item_id\n    AND cmsi.organization_id (+) = r.organization_id\nand o.organization_code = '\"&ORG&\"'\n\"\n, CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"EXTRACT_DATE\", \"Extract Date\"}, {\"ORGANIZATION_CODE\", \"Organization Code\"}, {\"ITEM_NUMBER\", \"Item Number\"}, {\"COMMON_ROUTING_ITEM\", \"Common Routing Item\"}, {\"FLOW_ROUTING\", \"Flow Routing Flag\"}, {\"COMPLETION_SUBINVENTORY\", \"Completion Subinventory\"}, {\"COMPLETION_LOCATOR\", \"Completion Locator\"}, {\"OPERATION_SEQ_NUM\", \"Operation Squence\"}, {\"STD_OP_CODE\", \"Standard Operation Code\"}, {\"OPERATION_DESCRIPTION\", \"Operation Description\"}, {\"DEPT_CLASS_CODE\", \"Department Class Code\"}, {\"DEPT_CODE\", \"Department Code\"}, {\"DEPT_DESCRIPTION\", \"Department Description\"}, {\"OPTION_DEPENDANT\", \"Option Dependant Flag\"}, {\"OPERATION_LEAD_TIME\", \"Operation Lead Time\"}, {\"EFFECTIVE_DATE\", \"Effective Date\"}, {\"DISABLE_DATE\", \"Disable Date\"}, {\"COUNT_POINT\", \"Count Point Flag\"}, {\"AUTOCHARGE\", \"Autocharge Flag\"}, {\"BACKFLUSH\", \"Backflush Flag\"}, {\"CHECK_SKILL\", \"Check Skill Flag\"}, {\"MIN_TRANSFER_QTY\", \"Minimum Transfer Quantity\"}, {\"RESOURCE_SEQ_NUM\", \"Resource Sequence\"}, {\"RESOURCE_TYPE\", \"Resource Type\"}, {\"OSP_RESSOURCE\", \"OSP Resource Flag\"}, {\"RESOURCE_CODE\", \"Resource Code\"}, {\"RESOURCE_DESCRIPTION\", \"Resource Description\"}, {\"BASIS\", \"Resource Basis\"}, {\"UNIT_OF_MEASURE\", \"Resource UOM Code\"}, {\"USAGE_RATE_OR_AMOUNT\", \"Resource Usage Rate\"}, {\"RESOURCE_COST\", \"Resource Cost\"}, {\"DEPT_RESOURCE_AVAILABLE_24_HRS\", \"24 Hours Resource Flag\"}, {\"SCHEDULE_SEQ\", \"Schedule Sequence\"}, {\"SUBSTITUTE_GROUP_NUMBER\", \"Substitute Group Number\"}, {\"ASSIGNED_UNITS\", \"Resource Assigned Units\"}, {\"SCHEDULE_FLAG\", \"Resource Schedule Flag\"}, {\"RESOURCE_OFFSET\", \"Resource offset\"}, {\"CHARGE_TYPE\", \"Resource Charge Type\"}, {\"LOCAL_EXTRACT_DATE\", \"Local Extract Date\"}}),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Renamed columns\", {{\"Resource offset\", Percentage.Type}, {\"Operation Lead Time\", Percentage.Type}})\r\nin\r\n  #\"Changed column type\";\r\nshared ORG = let\r\n  ORG = \"SPG\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type text]\r\nin\r\n  ORG;\r\nshared LocalTZ = let\r\n  LocalTZ = \"Asia/Singapore\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type text]\r\nin\r\n  LocalTZ;\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"WIP_Class","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"WIP_Class.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Local Extract Date","dataType":"dateTime"},{"name":"Organization Code","dataType":"string"},{"name":"Class Code","dataType":"string"},{"name":"Class Description","dataType":"string"},{"name":"CLASS_TYPE_CODE","dataType":"double"},{"name":"Class Type","dataType":"string"},{"name":"DISABLE_DATE","dataType":"dateTime"},{"name":"Material Account","dataType":"string"},{"name":"Material Overhead Account","dataType":"string"},{"name":"Resource Account","dataType":"string"},{"name":"Overhead Account","dataType":"string"},{"name":"OSP Account","dataType":"string"},{"name":"Material Variance Account","dataType":"string"},{"name":"Resource Variance Account","dataType":"string"},{"name":"Overhead Variance Account","dataType":"string"},{"name":"OSP Variance Account","dataType":"string"},{"name":"Cost Adjustment Account","dataType":"string"},{"name":"Work Type","dataType":"string"},{"name":"Accounting Type","dataType":"string"},{"name":"Activity","dataType":"string"},{"name":"Creation Date","dataType":"dateTime"},{"name":"Created By","dataType":"string"},{"name":"Last Update Date","dataType":"dateTime"},{"name":"Last Updated By","dataType":"string"},{"name":"Class Code CS","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-13T00:00:38.7472468+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/fa48a616-b968-4461-b114-e38a980622ae/WIP_Class.csv?snapshot=2022-06-13T00%3A00%3A38.7090744Z"}]},{"$type":"LocalEntity","name":"WIP_Department_Resource","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"WIP_Department_Resource.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Local Extract Date","dataType":"dateTime"},{"name":"DEPARTMENT_ID","dataType":"double"},{"name":"Department Code","dataType":"string"},{"name":"Department Description","dataType":"string"},{"name":"Location Code","dataType":"string"},{"name":"RESOURCE_ID","dataType":"double"},{"name":"Resource Code","dataType":"string"},{"name":"Resource Description","dataType":"string"},{"name":"Unit of Measure","dataType":"string"},{"name":"Resource Rate","dataType":"double"},{"name":"24 Hours Flag","dataType":"string"},{"name":"Resource Type","dataType":"string"},{"name":"Autocharge Type","dataType":"string"},{"name":"Default Basis","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-13T00:00:10.7049518+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/fa48a616-b968-4461-b114-e38a980622ae/WIP_Department_Resource.csv?snapshot=2022-06-13T00%3A00%3A10.5252797Z"}]},{"$type":"LocalEntity","name":"Routing","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Routing.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Local Extract Date","dataType":"dateTime"},{"name":"Organization Code","dataType":"string"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"Item Number","dataType":"string"},{"name":"Common Routing Item","dataType":"string"},{"name":"Flow Routing Flag","dataType":"string"},{"name":"Completion Subinventory","dataType":"string"},{"name":"Completion Locator","dataType":"string"},{"name":"Operation Squence","dataType":"double"},{"name":"Standard Operation Code","dataType":"string"},{"name":"Operation Description","dataType":"string"},{"name":"Department Class Code","dataType":"string"},{"name":"Department Code","dataType":"string"},{"name":"Department Description","dataType":"string"},{"name":"Option Dependant Flag","dataType":"string"},{"name":"Operation Lead Time","dataType":"double"},{"name":"Effective Date","dataType":"dateTime"},{"name":"Disable Date","dataType":"dateTime"},{"name":"Count Point Flag","dataType":"string"},{"name":"Autocharge Flag","dataType":"string"},{"name":"Backflush Flag","dataType":"string"},{"name":"Check Skill Flag","dataType":"string"},{"name":"Minimum Transfer Quantity","dataType":"double"},{"name":"Resource Sequence","dataType":"double"},{"name":"Resource Type","dataType":"string"},{"name":"OSP Resource Flag","dataType":"string"},{"name":"Resource Code","dataType":"string"},{"name":"Resource Description","dataType":"string"},{"name":"Resource Basis","dataType":"string"},{"name":"Resource UOM Code","dataType":"string"},{"name":"Resource Usage Rate","dataType":"double"},{"name":"Resource Cost","dataType":"double"},{"name":"24 Hours Resource Flag","dataType":"string"},{"name":"Schedule Sequence","dataType":"double"},{"name":"Substitute Group Number","dataType":"double"},{"name":"Resource Assigned Units","dataType":"double"},{"name":"Resource Schedule Flag","dataType":"string"},{"name":"Resource offset","dataType":"double"},{"name":"Resource Charge Type","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2022-06-13T00:03:06.0246784+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/fa48a616-b968-4461-b114-e38a980622ae/Routing.csv?snapshot=2022-06-13T00%3A03%3A05.9304387Z"}]}]}