{"name":"COHREP_SITE_SERVICE_TRX1","description":"Service Events","version":"1.0","culture":"en-US","modifiedTime":"2020-12-25T14:37:04.4416711+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":true,"queriesMetadata":{"Service_CRM":{"queryId":"f34cec1e-0b87-44ce-bafa-adbca3443b1d","queryName":"Service_CRM","queryGroupId":"root","loadEnabled":true},"Service_Cloud":{"queryId":"ecda3109-1d7b-4dc8-a114-0560fa5ada8d","queryName":"Service_Cloud","queryGroupId":"root","loadEnabled":true},"ORG":{"queryId":"50a00ab2-5056-4edd-8049-da80dad04a9c","queryName":"ORG"},"Local":{"queryId":"f1d1dd61-e8c1-4782-9ed8-d623a5ff86e9","queryName":"Local"}},"document":"section Section1;\r\nshared Service_CRM = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, Query=\"\nSELECT\n    sysdate                                                       extract_date,\n    from_tz(CAST(sysdate AS TIMESTAMP), 'PST') AT TIME ZONE '\"&Local&\"'         local_extract_date,\n    al2.incident_number,\n    al2.operating_unit,\n    al2.incident_type,\n    nvl(al2.alternate_customer_name, al2.customer_name),\n    al2.incident_severity,\n    al2.incident_status,\n    al2.escalation,\n    al2.incident_owner,\n    al2.incident_group_name,\n    al7.inventory_item_id,\n    al2.item_number,\n    al2.item_description,\n    al1.task_number,\n    al2.serial_number,\n    al1.task_type,\n    al2.problem_code,\n    al1.task_status,\n    al1.owner,\n    nvl(al2.technical_business_unit, 'Not Entered')               tbu,\n    al1.actual_start_date,\n    al1.actual_end_date,\n    al2.incident_close_date,\n    al2.regional_location,\n    al2.incident_date,\n    al2.entitlement,\n    al2.inc_reported_date,\n    nvl(al2.product_family, 'Not Entered')                        product_family,\n    al7.install_date,\n    MIN(al8.new_install_date)                                     original_install_date,\n    al9.header_id,\n    MAX(al10.line_id)                                             last_order_line_id,\n    al10.order_status,\n    al10.header_creation_date,\n    al10.order_number,\n    'Oracle CRM'                                                  system_source,\n    decode(nvl(al2.obq_flag, 'N'), 'Y', 'Yes', 'No')              obq_flag,\n    al2.obq_type,\n    al2.obq_notes,\n    al2.incident_instance,\n    al10.warehouse\nFROM\n    apps.xxcoh_sr_tasks_view             al1,\n    apps.xxcoh_service_request_view      al2,\n    apps.csi_installed_base_v            al7,\n    csi.csi_item_instances_h             al8,\n    apps.xxcoh_sr_om_link_v              al9,\n    appsread.xxcoh_service_order_view    al10,\n    (\n        SELECT\n            msi.inventory_item_id\n        FROM\n            apps.mtl_system_items    msi,\n            apps.mtl_parameters      mp\n        WHERE\n                mp.organization_id = msi.organization_id\n            AND mp.organization_code = '\"&ORG&\"'\n    ) msiv\nWHERE\n        al2.incident_id = al1.incident_id (+)\n    AND al2.incident_instance = al7.instance_number (+)\n    AND al7.instance_id = al8.instance_id (+)\n    AND al2.incident_id = al9.incident_id (+)\n    AND al9.header_id = al10.header_id (+)\n    AND msiv.inventory_item_id = al7.inventory_item_id\n    AND al2.incident_status NOT IN (\n        'Cancelled',\n        'Cancelled by User'\n    )\n    AND al8.old_install_date (+) IS NULL\n    AND ( NOT al8.new_install_date (+) IS NULL )\n    AND al1.task_type (+) LIKE 'Visit%'\n    AND al2.incident_type IN (\n        'Advance Replacement',\n        'Depot Repair',\n        'Field Service Visit',\n        'LSM Depot Repair/Calibration',\n        'Parts Order',\n        'Return Replacement',\n        'Upgrade'\n    )\n    AND ( NOT al1.task_status (+) = 'Cancelled' )\n    AND al2.entitlement = 'Warranty'\nGROUP BY\n    al2.incident_number,\n    al2.operating_unit,\n    al2.incident_type,\n    nvl(al2.alternate_customer_name, al2.customer_name),\n    al2.incident_severity,\n    al2.incident_status,\n    al2.escalation,\n    al2.incident_owner,\n    al2.incident_group_name,\n    al7.inventory_item_id,\n    al2.item_number,\n    al2.item_description,\n    al1.task_number,\n    al2.serial_number,\n    al1.task_type,\n    al2.problem_code,\n    al1.task_status,\n    al1.owner,\n    nvl(al2.technical_business_unit, 'Not Entered'),\n    al1.actual_start_date,\n    al1.actual_end_date,\n    al2.incident_close_date,\n    al2.regional_location,\n    al2.incident_date,\n    al2.entitlement,\n    al2.inc_reported_date,\n    nvl(al2.product_family, 'Not Entered'),\n    al7.install_date,\n    al9.header_id,\n    al10.order_status,\n    al10.header_creation_date,\n    al10.order_number,\n    'Oracle CRM',\n    sysdate,\n    decode(nvl(al2.obq_flag, 'N'), 'Y', 'Yes', 'No'),\n    al2.obq_type,\n    al2.obq_notes,\n    al2.incident_instance,\n    AL10.WAREHOUSE\n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"EXTRACT_DATE\", \"Extract Date\"}, {\"INCIDENT_NUMBER\", \"Incident Number\"}, {\"OPERATING_UNIT\", \"Operating Unit\"}, {\"INCIDENT_TYPE\", \"Incident Type\"}, {\"NVL(AL2.ALTERNATE_CUSTOMER_NAME,AL2.CUSTOMER_NAME)\", \"Customer Name\"}, {\"INCIDENT_SEVERITY\", \"Incident Severity\"}, {\"INCIDENT_STATUS\", \"Incident Status\"}, {\"ESCALATION\", \"Escalation\"}, {\"INCIDENT_OWNER\", \"Incident Owner\"}, {\"INCIDENT_GROUP_NAME\", \"Incident Group Name\"}, {\"ITEM_NUMBER\", \"Item Number\"}, {\"ITEM_DESCRIPTION\", \"Item Description\"}, {\"TASK_NUMBER\", \"Task Number\"}, {\"SERIAL_NUMBER\", \"Serial Number\"}, {\"TASK_TYPE\", \"Task Type\"}, {\"PROBLEM_CODE\", \"Problem Code\"}, {\"TASK_STATUS\", \"Task Status\"}, {\"OWNER\", \"Owner\"}, {\"ACTUAL_START_DATE\", \"Actual Start Date\"}, {\"ACTUAL_END_DATE\", \"Actual End Date\"}, {\"INCIDENT_CLOSE_DATE\", \"Incident Closed Date\"}, {\"REGIONAL_LOCATION\", \"Regional Location\"}, {\"INCIDENT_DATE\", \"Incident Date\"}, {\"ENTITLEMENT\", \"Entitlement\"}, {\"INC_REPORTED_DATE\", \"Incident Reported Date\"}, {\"PRODUCT_FAMILY\", \"Product Family\"}, {\"INSTALL_DATE\", \"Install Date\"}, {\"ORIGINAL_INSTALL_DATE\", \"Original Install Date\"}, {\"ORDER_STATUS\", \"Order Status\"}, {\"HEADER_CREATION_DATE\", \"Header Creation Date\"}, {\"OBQ_FLAG\", \"OBQ Flag\"}, {\"ORDER_NUMBER\", \"Order Number\"}, {\"SYSTEM_SOURCE\", \"System Source\"}, {\"OBQ_TYPE\", \"OBQ Type\"}, {\"OBQ_NOTES\", \"OBQ Notes\"}, {\"INCIDENT_INSTANCE\", \"Incident Instance\"}, {\"WAREHOUSE\", \"ORG\"}, {\"LOCAL_EXTRACT_DATE\", \"Local Extract Date\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared Service_Cloud = let\r\n  Source = Oracle.Database(\"COHREP\", [HierarchicalNavigation=true, Query=\"\nSELECT\n    sysdate                                                     extract_date,\n    from_tz(CAST(sysdate AS TIMESTAMP), 'PST') AT TIME ZONE '\"&Local&\"'         local_extract_date,\n    al12.casenumber                                             incident_number,\n    al12.operating_unit_c                                       operating_unit,\n    al12.c_type                                                 incident_type,\n    al12.account                                                customer_name,\n    al12.equipment_status_c                                     equipment_status,\n    al12.c_status                                               incident_status,\n    al12.isescalated                                            escalation,\n    al12.c_owner                                                incident_owner,\n    al12.service_groups_c                                       incident_group_name,\n    (\n        SELECT\n            inventory_item_id\n        FROM\n            apps.mtl_system_items_b msi\n        WHERE\n                msi.segment1 = al12.part_number_c\n            AND msi.organization_id = 63\n    ) inventory_item_id,\n    al12.part_number_c                                          item_number,\n    al12.part_descr                                             item_description,\n    al12.workordernumber                                        task_number,\n    al12.serialnumber                                           serial_number,\n    al12.wo_type                                                task_type,\n    al12.case_reason_code_c                                     problem_code,\n    al12.wo_status                                              task_status,\n    al12.wo_owner                                               owner,\n    al12.tbu_c                                                  tbu,\n    al13.sa_actualstarttime                                     actual_start_date,\n    al13.sa_actualendtime                                       actual_end_date,\n    al12.closeddate                                             incident_closed_date,\n    al12.region_location_c                                      regional_location,\n    al12.createddate                                            incident_date,\n    al12.billing_type_c                                         entitlement,\n    al12.createddate2                                           incident_reported_date,\n    al12.product_family_c                                       product_family,\n    al12.installdate                                            install_date,\n    al12.tmp_original_in33,\n    xxsov.header_id,\n    al14.ora_so_line_id_c                                       last_order_line_id,\n    xxsov.order_status,\n    xxsov.header_creation_date,\n    xxsov.order_number,\n    'Service Cloud CRM'                                         system_source,\n    decode(nvl(al15.obq_c, 'N'), 'Y', 'Yes', 'No')                  obq_flag,\n    al15.obq_type_c                                             obq_type,\n    al15.obq_notes_c                                            obq_notes,\n    al12.ora_ib_instance37                                      incident_instance,\n    XXSOV.WAREHOUSE\nFROM\n    appsread.xxcoh_service_order_view xxsov,\n    (\n        SELECT\n            d11al3.casenumber                                                                           AS casenumber,\n            substr(d11al3.operating_unit_c, 1, instr(d11al3.operating_unit_c, ':') - 1)                      AS operating_unit_c,\n            d11al3.type                                                                                 AS c_type,\n            d11al1.name                                                                                 AS account,\n            d11al3.equipment_status_c                                                                   AS equipment_status_c,\n            d11al3.status                                                                               AS c_status,\n            decode(d11al3.isescalated, 'false', 'Never Escalated', 'true', 'CARE Escalation')         AS isescalated,\n            nvl(d11al9.name, d11al5.name)                                                              AS c_owner,\n            d11al3.service_groups_c                                                                     AS service_groups_c,\n            d11al6.part_number_c                                                                        AS part_number_c,\n            d11al6.name                                                                                 AS part_descr,\n            d11al7.workordernumber                                                                      AS workordernumber,\n            d11al4.serialnumber                                                                         AS serialnumber,\n            d11al8.name                                                                                 AS wo_type,\n            d11al3.case_reason_code_c                                                                   AS case_reason_code_c,\n            d11al7.status                                                                               AS wo_status,\n            nvl(d11al11.name, d11al10.name)                                                            AS wo_owner,\n            nvl(d11al6.tbu_c, 'Not Entered')                                                           AS tbu_c,\n            d11al3.closeddate                                                                           AS closeddate,\n            d11al3.region_location_c                                                                    AS region_location_c,\n            d11al3.createddate                                                                          AS createddate,\n            d11al3.billing_type_c                                                                       AS billing_type_c,\n            d11al3.createddate                                                                          AS createddate2,\n            nvl(d11al6.coherent_product_family_c, 'Not Entered')                                       AS product_family_c,\n            d11al4.installdate                                                                          AS installdate,\n            d11al4.installdate                                                                          AS tmp_original_in33,\n            d11al3.id                                                                                   AS case_id,\n            d11al4.ora_ib_instance_id_c * 1.0                                                           AS ora_ib_instance35,\n            d11al7.id                                                                                   AS wo_id,\n            d11al2.ora_ib_instance_id_c                                                                 AS ora_ib_instance37\n        FROM\n            sfdc.account       d11al1,\n            sfdc.asset         d11al2,\n            sfdc.case          d11al3,\n            sfdc.asset         d11al4,\n            sfdc.group_sfdc    d11al5,\n            sfdc.product2      d11al6,\n            sfdc.workorder     d11al7,\n            sfdc.worktype      d11al8,\n            sfdc.user_sfdc     d11al9,\n            sfdc.group_sfdc    d11al10,\n            sfdc.user_sfdc     d11al11\n        WHERE\n                d11al3.accountid = d11al1.id (+)\n            AND d11al3.ownerid = d11al5.id (+)\n            AND d11al3.ownerid = d11al9.id (+)\n            AND d11al3.assetid = d11al2.id (+)\n            AND d11al2.rootassetid = d11al4.id (+)\n            AND d11al4.product2id = d11al6.id (+)\n            AND d11al3.id = d11al7.caseid (+)\n            AND d11al7.worktypeid = d11al8.id (+)\n            AND d11al7.ownerid = d11al10.id (+)\n            AND d11al7.ownerid = d11al11.id (+)\n            AND d11al3.isdeleted = 'false'\n            AND d11al3.status NOT IN (\n                'Canceled',\n                'Closed as Duplicate'\n            )\n            AND d11al7.isdeleted (+) = 'false'\n            AND ( NOT d11al7.status (+) = 'Canceled' )\n            AND d11al3.billing_type_c = 'Warranty'\n    ) al12,\n    (\n        SELECT\n            d12al1.casenumber                   AS casenumber,\n            d12al1.type                         AS c_type,\n            d12al1.status                       AS c_status,\n            d12al2.workordernumber              AS workordernumber,\n            d12al3.name                         AS wo_type,\n            MAX(d12al4.appointmentnumber)      AS appointmentnumber,\n            d12al4.actualstarttime              AS sa_actualstarttime,\n            d12al4.actualendtime                AS sa_actualendtime,\n            d12al1.id                           AS case_id,\n            d12al2.id                           AS wo_id,\n            d12al4.id                           AS sa_id\n        FROM\n            sfdc.case                  d12al1,\n            sfdc.workorder             d12al2,\n            sfdc.worktype              d12al3,\n            sfdc.serviceappointment    d12al4\n        WHERE\n                d12al2.worktypeid = d12al3.id (+)\n            AND d12al1.id = d12al2.caseid\n            AND d12al2.id = d12al4.parentrecordid\n            AND d12al4.isdeleted = 'false'\n            AND d12al4.status NOT IN (\n                'Canceled',\n                'None'\n            )\n        GROUP BY\n            d12al1.casenumber,\n            d12al1.type,\n            d12al1.status,\n            d12al2.workordernumber,\n            d12al3.name,\n            d12al4.actualstarttime,\n            d12al4.actualendtime,\n            d12al1.id,\n            d12al2.id,\n            d12al4.id\n    ) al13,\n    (\n        SELECT\n            d13al1.casenumber                          AS casenumber,\n            d13al1.type                                AS c_type,\n            d13al3.workordernumber                     AS workordernumber,\n            d13al2.ora_so_header_id_c                  AS ora_so_header_id_c,\n            MAX(d13al2.ora_so_line_id_c) * 1.0        AS ora_so_line_id_c,\n            d13al2.billing_type_c                      AS billing_type_c,\n            d13al1.id                                  AS case_id,\n            d13al3.id                                  AS wo_id\n        FROM\n            sfdc.case                 d13al1,\n            sfdc.workorderlineitem    d13al2,\n            sfdc.workorder            d13al3\n        WHERE\n                d13al1.id = d13al3.caseid\n            AND d13al2.workorderid = d13al3.id\n            AND d13al2.order_classification_c = 'External Order'\n            AND d13al2.ora_so_header_id_c IS NOT NULL\n        GROUP BY\n            d13al1.casenumber,\n            d13al1.type,\n            d13al3.workordernumber,\n            d13al2.ora_so_header_id_c,\n            d13al2.billing_type_c,\n            d13al1.id,\n            d13al3.id\n    ) al14,\n    (\n        SELECT\n            d14al1.id                                       AS case_id,\n            decode(d14al2.obq_c, 'true', 'Y', 'N')         AS obq_c,\n            d14al2.obq_type_c                               AS obq_type_c,\n            d14al2.obq_notes_c                              AS obq_notes_c,\n            d14al2.failure_location_c                       AS failure_location_c,\n            MAX(d14al2.createddate)                        AS createddate\n        FROM\n            sfdc.case                  d14al1,\n            sfdc.case_resolution__c    d14al2\n        WHERE\n                d14al1.id = d14al2.case_c\n            AND d14al2.obq_c = 'true'\n        GROUP BY\n            d14al1.id,\n            decode(d14al2.obq_c, 'true', 'Y', 'N'),\n            d14al2.obq_type_c,\n            d14al2.obq_notes_c,\n            d14al2.failure_location_c\n    ) al15,\n     (\n        SELECT\n            msi.inventory_item_id,MSI.SEGMENT1 ITEM_NUMBER\n        FROM\n            apps.mtl_system_items    msi,\n            apps.mtl_parameters      mp\n        WHERE\n                mp.organization_id = msi.organization_id\n            AND mp.organization_code = '\"&ORG&\"'\n    ) msiv\nWHERE\n        al12.case_id = al13.case_id (+)\n   AND al12.part_number_c = MSIV.ITEM_NUMBER\n    AND al12.wo_id = al14.wo_id (+)\n    AND xxsov.line_id (+) = al14.ora_so_line_id_c\n    AND al12.case_id = al15.case_id (+)\n    AND al12.c_type IN (\n        'Advance Replacement',\n        'Depot Repair',\n        'Field Service Visit',\n        'LSM Depot Repair/Calibration',\n        'Parts Order',\n        'Return Replacement',\n        'Upgrade'\n    )\n    AND xxsov.order_status (+) <> 'CANCELLED'\n\", CommandTimeout=#duration(0, 0, 10, 0)]),\r\n  #\"Renamed columns\" = Table.RenameColumns(Source, {{\"EXTRACT_DATE\", \"Extract Date\"}, {\"INCIDENT_NUMBER\", \"Incident Number\"}, {\"OPERATING_UNIT\", \"Operating Unit\"}, {\"INCIDENT_TYPE\", \"Incident Type\"}, {\"CUSTOMER_NAME\", \"Customer Name\"}, {\"INCIDENT_STATUS\", \"Incident Status\"}, {\"ESCALATION\", \"Escalation\"}, {\"INCIDENT_OWNER\", \"Incident Owner\"}, {\"INCIDENT_GROUP_NAME\", \"Incident Group Name\"}, {\"ITEM_NUMBER\", \"Item Number\"}, {\"ITEM_DESCRIPTION\", \"Item Description\"}, {\"TASK_NUMBER\", \"Task Number\"}, {\"SERIAL_NUMBER\", \"Serial Number\"}, {\"TASK_TYPE\", \"Task Type\"}, {\"PROBLEM_CODE\", \"Problem Code\"}, {\"TASK_STATUS\", \"Task Status\"}, {\"OWNER\", \"Owner\"}, {\"ACTUAL_START_DATE\", \"Actual Start Date\"}, {\"ACTUAL_END_DATE\", \"Actual End Date\"}, {\"INCIDENT_CLOSED_DATE\", \"Incident Closed Date\"}, {\"REGIONAL_LOCATION\", \"Regional Location\"}, {\"INCIDENT_DATE\", \"Incident Date\"}, {\"ENTITLEMENT\", \"Entitlement\"}, {\"INCIDENT_REPORTED_DATE\", \"Incident Reported Date\"}, {\"PRODUCT_FAMILY\", \"Product Family\"}, {\"INSTALL_DATE\", \"Install Date\"}, {\"ORDER_STATUS\", \"Order Status\"}, {\"HEADER_CREATION_DATE\", \"Header Creation Date\"}, {\"OBQ_FLAG\", \"OBQ Flag\"}, {\"ORDER_NUMBER\", \"Order Number\"}, {\"SYSTEM_SOURCE\", \"System Source\"}, {\"OBQ_TYPE\", \"OBQ Type\"}, {\"OBQ_NOTES\", \"OBQ Notes\"}, {\"INCIDENT_INSTANCE\", \"Incident Instance\"}, {\"WAREHOUSE\", \"ORG\"}, {\"LOCAL_EXTRACT_DATE\", \"Local Extract Date\"}})\r\nin\r\n  #\"Renamed columns\";\r\nshared ORG = let\r\n  ORG = \"SPG\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type text]\r\nin\r\n  ORG;\r\nshared Local = let\r\n  Local = \"ASIA/Singapore\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type text]\r\nin\r\n  Local;\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"Service_CRM","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Service_CRM.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Local Extract Date","dataType":"dateTime"},{"name":"Incident Number","dataType":"string"},{"name":"Operating Unit","dataType":"string"},{"name":"Incident Type","dataType":"string"},{"name":"Customer Name","dataType":"string"},{"name":"Incident Severity","dataType":"string"},{"name":"Incident Status","dataType":"string"},{"name":"Escalation","dataType":"string"},{"name":"Incident Owner","dataType":"string"},{"name":"Incident Group Name","dataType":"string"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"Item Number","dataType":"string"},{"name":"Item Description","dataType":"string"},{"name":"Task Number","dataType":"string"},{"name":"Serial Number","dataType":"string"},{"name":"Task Type","dataType":"string"},{"name":"Problem Code","dataType":"string"},{"name":"Task Status","dataType":"string"},{"name":"Owner","dataType":"string"},{"name":"TBU","dataType":"string"},{"name":"Actual Start Date","dataType":"dateTime"},{"name":"Actual End Date","dataType":"dateTime"},{"name":"Incident Closed Date","dataType":"dateTime"},{"name":"Regional Location","dataType":"string"},{"name":"Incident Date","dataType":"dateTime"},{"name":"Entitlement","dataType":"string"},{"name":"Incident Reported Date","dataType":"dateTime"},{"name":"Product Family","dataType":"string"},{"name":"Install Date","dataType":"dateTime"},{"name":"Original Install Date","dataType":"dateTime"},{"name":"HEADER_ID","dataType":"double"},{"name":"LAST_ORDER_LINE_ID","dataType":"double"},{"name":"Order Status","dataType":"string"},{"name":"Header Creation Date","dataType":"dateTime"},{"name":"Order Number","dataType":"double"},{"name":"System Source","dataType":"string"},{"name":"OBQ Flag","dataType":"string"},{"name":"OBQ Type","dataType":"string"},{"name":"OBQ Notes","dataType":"string"},{"name":"Incident Instance","dataType":"string"},{"name":"ORG","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2020-12-25T14:50:53.3855684+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/08683235-8f5c-44a5-a4d6-a0b3fbe91a5d/Service_CRM.csv?snapshot=2021-05-17T10%3A37%3A54.4022582Z"}]},{"$type":"LocalEntity","name":"Service_Cloud","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Service_Cloud.csv"},"attributes":[{"name":"Extract Date","dataType":"dateTime"},{"name":"Local Extract Date","dataType":"dateTime"},{"name":"Incident Number","dataType":"string"},{"name":"Operating Unit","dataType":"string"},{"name":"Incident Type","dataType":"string"},{"name":"Customer Name","dataType":"string"},{"name":"EQUIPMENT_STATUS","dataType":"string"},{"name":"Incident Status","dataType":"string"},{"name":"Escalation","dataType":"string"},{"name":"Incident Owner","dataType":"string"},{"name":"Incident Group Name","dataType":"string"},{"name":"INVENTORY_ITEM_ID","dataType":"double"},{"name":"Item Number","dataType":"string"},{"name":"Item Description","dataType":"string"},{"name":"Task Number","dataType":"string"},{"name":"Serial Number","dataType":"string"},{"name":"Task Type","dataType":"string"},{"name":"Problem Code","dataType":"string"},{"name":"Task Status","dataType":"string"},{"name":"Owner","dataType":"string"},{"name":"TBU","dataType":"string"},{"name":"Actual Start Date","dataType":"dateTime"},{"name":"Actual End Date","dataType":"dateTime"},{"name":"Incident Closed Date","dataType":"dateTime"},{"name":"Regional Location","dataType":"string"},{"name":"Incident Date","dataType":"dateTime"},{"name":"Entitlement","dataType":"string"},{"name":"Incident Reported Date","dataType":"dateTime"},{"name":"Product Family","dataType":"string"},{"name":"Install Date","dataType":"dateTime"},{"name":"TMP_ORIGINAL_IN33","dataType":"dateTime"},{"name":"HEADER_ID","dataType":"double"},{"name":"LAST_ORDER_LINE_ID","dataType":"double"},{"name":"Order Status","dataType":"string"},{"name":"Header Creation Date","dataType":"dateTime"},{"name":"Order Number","dataType":"double"},{"name":"System Source","dataType":"string"},{"name":"OBQ Flag","dataType":"string"},{"name":"OBQ Type","dataType":"string"},{"name":"OBQ Notes","dataType":"string"},{"name":"Incident Instance","dataType":"string"},{"name":"ORG","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2020-12-25T14:51:24.4368448+00:00","location":"https://wabiwuscpcdsap1.blob.core.windows.net:443/08683235-8f5c-44a5-a4d6-a0b3fbe91a5d/Service_Cloud.csv?snapshot=2021-05-17T10%3A37%3A54.5303493Z"}]}]}